### ISSUE TITLE
rclone md5sum: implement an Unix md5sum-like "-c" option

### ISSUE THREAD

**Issue by DurvalMenezes** [rclone/rclone#1005]
As commented here: https://github.com/ncw/rclone/issues/999#issuecomment-271163504.

**Comment by ivandeex** [comment]
@ncw 
I believe this functionality is implemented by the `check` command.
I suggest closing this issue.

**Comment by ivandeex** [comment]
Related ro https://github.com/rclone/rclone/issues/157

**Comment by ivandeex** [comment]
Closing after 4 years of inactivity

**Comment by ncw** [comment]
what `md5sum -c` does is read the file created by `md5sum` and checks it against the filesystem.

It is a nice feature and it would be nice for `rclone md5sum`. It is, as you said, very similar to `rclone check` but it is useful for detecting bitrot

**Comment by ivandeex** [comment]
@ncw
We have a more generic ticket https://github.com/rclone/rclone/issues/157 that requests `SUM` file support but does not impose whether it will be `-c` flag in exisitng `rclone Xsum` verbs or a new verb.
I think we can merge this ticket in there and decide on a particular CLI format among other things.

**Comment by ivandeex** [comment]
@ncw
I am going to tackle #157 (and #118) after I'm done with https://github.com/rclone/rclone/pulls/assigned/ivandeex, so I'll ask you questions anyway.

**Comment by ivandeex** [comment]
I was wrong. This PR requests a CLI enhancement while #157 seeks for transparent SUM integration into rclone backends.
