### ISSUE TITLE
Crypto Performance on ARMv8

### ISSUE THREAD

**Issue by gordan-bobic** [rclone/rclone#1013]
I'm using rclone on an ARMv8, and the CPU usage is about 20x higher than it is on comparable x86 CPU, presumably due to crypto performance. I am seeing about 47% CPU usage on a 2.0GHz ARMv8 core for uploading at 20Mbit/s (speed of the uplink). A Nehalem CPU is showing about 2.3% CPU usage to do the same thing.

Is there a way to link against a different crypto library at least for the SSL part, to leverage more optimized crypto code? Linking against something like OpenSSL would also allow for leveraging asynchronous crypto offload engine using /dev/crypto, particularly on low end ARM CPUs that really need all the help they can get.

**Comment by ncw** [comment]
I suspect this is because on ARMv8 go doesn't use the built in AES instructions.

There is an issue about it here: https://github.com/golang/go/issues/18498 - fixing that will bring the speed back to openssl speeds.  It looks like some progres has been made on it - it might be in go 1.9.

Which hardware are you using?

If you try doing curl or wget to an https address on the ARMv8 board, how much CPU does that use for a given amount of throughput?

There is a project to use openssl from go here: https://github.com/spacemonkeygo/openssl - it requires a patched net/http which makes it a bit tricky to install.

**Comment by gordan-bobic** [comment]
I am using an APM X-Gene 1 (Gigabyte MP30-AR0 board). OpenSSL speed tests at 95MB/s on AES128 and 75MB/s on AES256.

wget shows about 25-30% CPU usage downloading at about 80Mbit on a https download, which is still far off what openssl seems capable of.

A better implementation in Go still wouldn't immediately address the hardware accelerator/coprocessor offload, though, via the /dev/crypto interface, which OpenSSL can do.

**Comment by ncw** [comment]
> A better implementation in Go still wouldn't immediately address the hardware accelerator/coprocessor offload

Are there other crypto accelerators built in to your board other than the ARMv8 AES instructions which I believe are a standard part of ARMv8?

> via the /dev/crypto interface, which OpenSSL can do.

Are you using linux? According to wikipedia [/dev/crypto was never merged in mainline](https://en.wikipedia.org/wiki/Crypto_API_(Linux)) linux.

It looks like a great idea and go could directly target it if available...

**Comment by gordan-bobic** [comment]
The ARMv8 I use doesn't have a separate crypto coprocessor, but I have a LOT of other ARMs, including Nvidia Tegra and Marvell Kirkwood based ones that do have asynchronous crypto offload available via /dev/crypto, and they really do need it for something like this.

It is true that cryptodev was never merged into mainline, but it is pretty trivial to build it, and it exposes all of the crypto drivers built into the kernel, including the ones for hardware accelerators. Given that other crypto libraries (other than OpenSSL) have effectively non-existant support for /dev/crypto, for a long time now OpenSSL has been the only game in town for crypto offload.

**Comment by ncw** [comment]
If you wanted to have a go with https://github.com/spacemonkeygo/openssl

Then it would be relatively easy, you'd just need to add this in `fs/http.go` in the `Transport` method

```go
t.DialTLS = func(network, address string) (net.Conn, error) {
        return openssl.Dial(network, address, context.TODO(), 0)
}
```

There might be a bit more stuff, but that plus [the docs](https://godoc.org/github.com/spacemonkeygo/openssl#Dial) should give you a start.

I'm unlikely to do this by default with rclone as adding dependencies to C libraries breaks the cross compilation, but it could be set up so you could supply a build tag to make it work quite easily.

**Comment by vielmetti** [comment]
`minio` (another storage system) saw 100x speedup in crypto operations in Go on ARMv8 by using hardware support.

https://blog.minio.io/accelerating-sha256-by-100x-in-golang-on-arm-1517225f5ff4#.foika9d4j

The code base is at https://github.com/minio/sha256-simd

**Comment by gordan-bobic** [comment]
That's looks like a worthwhile option for sure, but it doesn't seem to come with the USP of OpenSSL which is /dev/crypto support for leveraging kernel crypto drivers, including the ones for hardware crypto offload.

**Comment by ncw** [comment]
If someone would do the same thing for the AES instructions and upstream that to the go project that would solve all the problems for ARMv8!

**Comment by vielmetti** [comment]
The upstream issue, "crypto/aes: add dedicated asm version of AES, AES-GCM for arm64", is now scheduled for Go 1.10 (slipped from Go 1.9).

**Comment by ncw** [comment]
Rclone is now compiled with go1.13 so this should be all fixed now.
