### ISSUE TITLE
Feature Request: Mount multiple remotes in "unioned" mode

### ISSUE THREAD

**Issue by lobianco** [rclone/rclone#1017]
I've been experiencing some intermittent flakiness with my ACD connection recently, and I've read similar reports from others. It could be really useful to mount multiple remotes in a sort of "unioned" mode (think `unionfs`) where data from the first remote is preferred, but if there's a disruption (i/o timeout, read error,  etc.), then an attempt is made to read the remainder of the data from the second remote. This would be great for e.g. media streaming where reliability is crucial. Just a thought, not sure if it's possible or what the technical implications would be 🤔 

(This assumes redundant data on all remotes of course)

**Comment by ncw** [comment]
So sort of like a RAID1 array for remotes.

**Comment by lobianco** [comment]
Yeah exactly! Only had the idea because ACD has been so flaky for me lately 😕

**Comment by ivandeex** [comment]
This issue duplicates https://github.com/rclone/rclone/issues/909
Feature implemented by https://rclone.org/union/
Closing
