### ISSUE TITLE
ACD Chunk Size

### ISSUE THREAD

**Issue by 4getit** [rclone/rclone#1039]
The name --drive-chunk-size suggests that this has effect on Google Drive only.
I use --drive-chunk-size xx and --transfers yy when copying large files from Google Drive to Google Drive and it easily saturates the 1Gbps connection.

However, when copying from Google Drive to ACD, things are very slow. Playing with --drive-chunk-size doesn't seem to help. I increased --transfers and that helped a bit but I can't get above 25%-50% of the connection capacity.

Is --drive-chunk-size supposed to work for ACD as well?
If not, shouldn't there be an --acd-chunk-size parameter?

**Comment by ncw** [comment]
@4getit wrote
> The name --drive-chunk-size suggests that this has effect on Google Drive only.

That is correct

> Is --drive-chunk-size supposed to work for ACD as well?

No.

> If not, shouldn't there be an --acd-chunk-size parameter?

ACD uploads aren't chunked in the same way so no chunk size parameter.

I think Amazon may limit total uploads speeds anyway, so you might not be able to get it to go faster.

**Comment by animosity22** [comment]
This looks answered and ACD is a zombie.
