### ISSUE TITLE
delete unnecessary log files from dropbox location after rclone sync

### ISSUE THREAD

**Issue by vkhadela** [rclone/rclone#1046]
Hi,

We have configured rclone in our system to sync the report files from Amazon s3 to dropbox.
Sync is happening properly but everytime it creates unnecessary files at dropbox location and these are log files and when you click on it is says "Extensionless files can’t be previewed"

so it creates confusion for end user due to same file name present i.e., one for directory and one for such log files.
I want to remove all such log files after every sync. Any help would be appreciated. I was trying to get help from http://rclone.org/commands/rclone_delete/ but couldn't find how to exclude directories and delete unnecessary log files. Below is the rclone version in our system and we are running on ubuntu machine.

rclone v1.34

We are running below command on ubuntu machine
/usr/sbin/rclone sync s3:path dropbox:path

Thanks,
Vipul

**Comment by ncw** [comment]
Are these log files in the source?  It sounds like you want to exclude them from the sync.

What file name do they have?  If you paste some examples I can help you construct a filter you can use with sync or delete.

**Comment by vkhadela** [comment]
The log files are at the destination. After sync, rclone creates log files at destination(dropbox in my case) and gives the same name as directory name. For example, I am syncing all the reports at one location and after sync it creates extension less file at destination. So after sync below files will be present at destination.

XYZ      - directory containing reports
XYZ      - log file
XYZ(1)  - log file
XYZ(2)  - log file

here, reports are in XYZ directory but the other files like XYZ(1), XYZ(2) are extension less files and are created by rclone. The files contain logs about when the sync started and when completed etc. 

But it creates confusion for end user. We have scheduled cron for this sync job. So when first time it runs, it creates XYZ directory and XYZ log file, and when second time it runs, it creates XYZ(1) log file, third time XYZ(2) log file, etc. Actual reports are syncing properly in XYZ directory but these log files I need to remove.

Hope I could explain the case. Let me know if any further information needed. 

Thanks,
Vipul

**Comment by ncw** [comment]
Rclone itself doesn't create log files. I don't understand where those log files are coming from. Is it a setting on your Dropbox account, or some other piece of software doing it? 

Could you post a bit of one of the logs (redact sensitive file names if you want) so I can try to identify it?

**Comment by vkhadela** [comment]
Actually the person has deleted those files manually. Only one file I had and when I opened it, it had only 1 line in it like below:
0

The files are extentionless. Is it possible to write delete with exclude filter? I mean I want to delete everything excluding all the directories. That will also work for me. So eventually only directories will be present and rest all the files will be deleted.

Thanks for the help.

Regards,
Vipul

**Comment by ncw** [comment]
Try doing

    rclone ls --include "XYZ*"

and if that lists the right files then you can do

    rclone delete --include "XYZ*"

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
