### ISSUE TITLE
crypt to amazon wont list files

### ISSUE THREAD

**Issue by clanstyles** [rclone/rclone#1056]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the [latest beta of rclone](http://rclone.org/downloads/).

If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

Both the stable v1.35 and the beta contain the same issue.
rclone-v1.35-36-ga4bf22eβ
rclone-v1.35

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux amd64

> Which cloud storage system are you using? (eg Google Drive)

Amazon Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount encfs:/ ~/localpoint -v

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

```
2017/01/20 10:42:36 Encrypted amazon drive root 'media/encfs': Root()
2017/01/20 10:42:43 fuse: <- Getattr [ID=0x2 Node=0x1 Uid=1000 Gid=1000 Pid=5280] 0x0 fl=0
2017/01/20 10:42:43 : Dir.Attr
2017/01/20 10:42:43 fuse: -> [ID=0x2] Getattr valid=1m0s ino=1 size=0 mode=drwxrwxr-x
2017/01/20 10:42:44 fuse: <- Getxattr [ID=0x3 Node=0x1 Uid=1000 Gid=1000 Pid=5282] "security.selinux" 255 @0
2017/01/20 10:42:44 fuse: -> [ID=0x3] Getxattr error=operation not supported
2017/01/20 10:42:44 fuse: <- Getxattr [ID=0x4 Node=0x1 Uid=1000 Gid=1000 Pid=5282] "system.posix_acl_access" 0 @0
2017/01/20 10:42:44 fuse: -> [ID=0x4] Getxattr error=operation not supported
2017/01/20 10:42:44 fuse: <- Open [ID=0x5 Node=0x1 Uid=1000 Gid=1000 Pid=5282] dir=true fl=OpenReadOnly+OpenDirectory+OpenNonblock
2017/01/20 10:42:44 fuse: -> [ID=0x5] Open 0x1 fl=0
2017/01/20 10:42:44 fuse: <- Read [ID=0x6 Node=0x1 Uid=1000 Gid=1000 Pid=5282] 0x1 4096 @0x0 dir=true fl=0 lock=0 ffl=OpenReadOnly+OpenDirectory+OpenNonblock
2017/01/20 10:42:44 : Dir.ReadDirAll
2017/01/20 10:42:44 : Reading directory
2017/01/20 10:42:44 : Dir.ReadDirAll OK with 0 entries
2017/01/20 10:42:44 fuse: -> [ID=0x6] Read 0
2017/01/20 10:42:44 fuse: <- Release [ID=0x7 Node=0x1 Uid=0 Gid=0 Pid=0] 0x1 fl=OpenReadOnly+OpenDirectory+OpenNonblock rfl=0 owner=0x0
2017/01/20 10:42:44 fuse: -> [ID=0x7] Release
```

I've tried to mount the actual un-encrypted drive back to back. The actual amazon config will mount and display the encrypted information. The issue is occurring between the amazon -> encryption layer. It seems that the encryption layer never gets any encrypted filenames to even attempt to decode.

**Comment by ncw** [comment]
What does this say?

    rclone ls encfs:

How did you get the encrypted files up to amazon in the first place?

What does your config file say - can you the `encfs` section (remove the passwords)?

**Comment by clanstyles** [comment]
No, all files were encrypted with rclone.

rclone ls encfs:
```
Failed to ls: directory not found
```

my config file is as follows
```
[acd]
type = amazon cloud drive
client_id =
client_secret =
token = xxxx

[encfs]
type = crypt
remote = acd:/media/encfs
filename_encryption = standard
password = xxx
password2 = xxx
```

**Comment by ncw** [comment]
So if you do `rclone ls acd:media/encfs` you see lots of encrypted looking file names?

But if you do `rclone ls encfs:` you see nothing?

Try the latter command with `-v`, so `rclone ls -v encfs:` and it may debug something useful.

It is possible that the password/password2 is wrong in which case rclone won't see any of the files.

**Comment by animosity22** [comment]
ACD is dead and this looks answered.
