### ISSUE TITLE
Q: rclone performance on ARM boards (RPi2, OrangePi)

### ISSUE THREAD

**Issue by TerrorFactor** [rclone/rclone#1061]
I noticed that the performance of rclone is very poor on ARM boards. I first tried it on a OrangePi PC, freshly installed with Armbian. If I copy a file from GDrive to local, I only get 2.6 MB/s

I figured it might be the OrangePi, driver issues of some sort, so I tried it on a freshly installed RaspberyPi 2 with Raspbian, but that is even worse: 1.8 MB/s

On an ubuntu desktop, I get 6+ MB/s. Using wget on the orangepi/rpi, I also get get ~6MB/s.

What is causing this and is there a way to circumvent this. Is this something that can be fixed?
Output of top-command while copying on the raspberry:
```
top - 23:51:51 up 33 min,  4 users,  load average: 1.60, 1.47, 1.05
Tasks: 146 total,   1 running, 145 sleeping,   0 stopped,   0 zombie
%Cpu(s): 26.9 us,  1.9 sy,  0.0 ni, 54.7 id, 15.4 wa,  0.0 hi,  1.0 si,  0.0 st
KiB Mem:    947732 total,   921792 used,    25940 free,    43380 buffers
KiB Swap:   102396 total,        0 used,   102396 free.   728116 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 3093 pi        20   0  802024  30616   9388 S 113.4  3.2  13:45.55 rclone
   84 root      20   0       0      0      0 S   1.0  0.0   0:05.69 mmcqd/0
 3142 pi        20   0    5112   2412   2024 R   1.0  0.3   0:06.53 top
    3 root      20   0       0      0      0 S   0.7  0.0   0:05.02 ksoftirqd/0
   32 root      20   0       0      0      0 S   0.3  0.0   0:01.72 kswapd0
  844 pi        20   0  104528  26216  21800 S   0.3  2.8   0:07.23 lxpanel
 3111 pi        20   0   12212   3528   2860 S   0.3  0.4   0:00.63 sshd
    1 root      20   0   22788   3932   2740 S   0.0  0.4   0:08.53 systemd
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.01 kthreadd
    5 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/0:+
    7 root      20   0       0      0      0 S   0.0  0.0   0:02.00 rcu_sched
    8 root      20   0       0      0      0 S   0.0  0.0   0:00.00 rcu_bh
    9 root      rt   0       0      0      0 S   0.0  0.0   0:00.02 migration/0
   10 root      rt   0       0      0      0 S   0.0  0.0   0:00.02 migration/1
   11 root      20   0       0      0      0 S   0.0  0.0   0:00.17 ksoftirqd/1
   13 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/1:+
   14 root      rt   0       0      0      0 S   0.0  0.0   0:00.02 migration/2
   15 root      20   0       0      0      0 S   0.0  0.0   0:00.14 ksoftirqd/2
   17 root       0 -20       0      0      0 S   0.0  0.0   0:00.00 kworker/2:+
   18 root      rt   0       0      0      0 S   0.0  0.0   0:00.01 migration/3

```

**Comment by ncw** [comment]
This is almost certainly SSL performance.

Go re-implemented its own crypto - it doesn't use OpenSSL.  Unfortunately it means that some crypto is a lot slower and AES on ARM is one of those cases.

Possible solutions:
  * it is possible to use OpenSSL with go - it isn't straight forward though
  * use any hardware support for crypto (eg AES instructions)
  * re-write the AES routines in assembler (something I keep meaning to do)
  * persuade SSL to negotiate a faster cipher (eg salsa20)

Related issue: #1013

**Comment by TerrorFactor** [comment]
That does indeed seem to be the case. Using Hamachi as VPN on my Raspberry, I also noticed a very high cpu load. Hopefully this gets fixed, it would be nice to run rclone on something that uses almost no power.
I don't really have a preference for any of your solutions.

**Comment by ncw** [comment]
Can you try this binary which I compiled with go tip?

This might pick up SALSA20 and be a lot faster.  It might just be a bit faster (say 20%) because the compiler improved.  Or it might be no difference...

[rclone-v1.35-42-g9fdeb82-arm-go-tip.zip](https://github.com/ncw/rclone/files/727832/rclone-v1.35-42-g9fdeb82-arm-go-tip.zip)

**Comment by gordan-bobic** [comment]
If you're considering votes on the matter, linking against OpenSSL gets mine. Not only is OpenSSL as omnipresent as libraries get on any kind of *nix, but it also has very mature and stable support for crypto offload using cryptodev on Linux and *BSD. Cryptodev is a standard interface for accessing crypto offload provided by kernel drivers, and most ARM machines, especially 32-bit ones, have asynchronous crypto co-processors for AES and SHA.

**Comment by TerrorFactor** [comment]
@ncw  Sorry for my late response, I didn't get to try the new version yet. I hope to get to it today. Thank you for your effort!

**Comment by TerrorFactor** [comment]
@ncw Performance has roughly doubled, I get 4MB/s on a RPi2. CPU for the rclone process goes to 140% though, so it wont be useable in my case.

**Comment by ncw** [comment]
Note that I've put in a PR for go porting the openssl AES routines to go.  This doubles the performance again for me on RPi3 - hopefully that will be in go 1.9.

https://go-review.googlesource.com/c/38366/

**Comment by protocold** [comment]
rclone-v1.35-42-g9fdeb82-arm-go-tip.zip has increased speed significantly on my arm based NAS. Is there a new version of this? :)

**Comment by ncw** [comment]
The normal rclone betas are now built with go 1.8.3 which should have those performance improvements

**Comment by vielmetti** [comment]
@ncw - there's a Go 1.9 Beta 2 that's out, can you build and benchmark vs that? I'm interested in keeping ARM performance heading in the right direction.

**Comment by protocold** [comment]
@ncw I have been following your thread on https://go-review.googlesource.com/c/38366/ but it doesnt seems like your patch has gone in. Can you possibly provide a rclone build with your ARM assembly versions of AES? Many thanks.

**Comment by ncw** [comment]
@protocold alas we've hit licencing difficulties :-(

Attached is a version of rclone built with that compiler and that patch for you to try.

[rclone-v1.39-193-g3f9d0d3b-arm.zip](https://github.com/ncw/rclone/files/1770983/rclone-v1.39-193-g3f9d0d3b-arm.zip)

**Comment by protocold** [comment]
@ncw Is this correct? I tried this rclone-v1.39-193-g3f9d0d3b-arm.zip and it is very slow compared with rclone-v1.35-42-g9fdeb82-arm-go-tip.zip

**Comment by ncw** [comment]
@protocold I didn't try benchmarking it... Though it isn't necessary comparing apples with apples as the SSL layer may negotiate a different set of ciphers etc.  Not sure the best way of figuring that out.  I think it all happens above the layer wireshark would see and below the layers rclone can debug...  Any ideas?

**Comment by protocold** [comment]
I probably dont understand all these.. but could you compile, for the same version of rclone, one with that AES patch and one without? Would that make it apple to apple or at least closer?

**Comment by ncw** [comment]
@protocold  Here is pretty much the same version: https://beta.rclone.org/v1.39-192-ge9fd2250/ you could give that a go.

**Comment by ncw** [comment]
I'm pretty sure this should be fixed for [the latest release](https://rclone.org/downloads/) which is compiled with go1.13
