### ISSUE TITLE
dropbox: warn if multiple files of the same case folded name detected

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#107]
Dropbox is case sensitive.

A sync which has both `file.txt` and `File.txt` will behave erratically.

Warn the user in this case.  Ideally just sync the alphabetically first one, so the sync is consistent.

Factored from #104

**Comment by austinginder** [comment]
Taken from: https://www.dropbox.com/developers/core/docs

> Note: Dropbox treats file names in a case-insensitive but case-preserving way. To facilitate this, the <path> values above are lower-cased versions of the actual path. The last path component of the <metadata> value will be case-preserved.

If that's true, would it be possible to catch potential duplicates through the Dropbox API by comparing the case of the file names against the case-preserved value on Dropbox? If so then which ever file is uploaded to Dropbox would become the true file and anything with a different case could be skipped.

**Comment by ncw** [comment]
@austinginder rclone relies on this property already when doing the syncs.

What I could do is set a `CaseInsensitive` flag on the dropbox backend, then use this in the `Sync` and `Copy` routines to do the ignoring there.  I think that would be the correct approach...

Potentially this could be useful for OSX which by default has case insensitive file systems too. (But the file system can be case insensitive too!)

**Comment by austinginder** [comment]
That would work. I'm using rclone to do an incremental backup of some WordPress websites to Dropbox. There are a number of sites with same named, different case files. Using a flag such as this would be perfect for my situation. I assume this would not be helpful for most people. Maybe it could be an argument I pass into rclone.

**Comment by kel30a** [comment]
I was having a similar issue with the sync command where the directory had case sensitivity issues:

**Source:** dropbox:\root
**Destination:** Windows Desktop C:\root\NuGet\file1.txt

When viewing through the dropbox web UI, the folder was named "nuget", but on the windows machine it was "NuGet". 

After running the sync command a few times, I expected it to not require any transfers after the first run, but after inspecting the logs it would intermittently delete the file and re-transfer it.

I've renamed the folder on the Dropbox side to be "NuGet" and that's working as expected - but might be a little dangerous for those with network data concerns.

**Comment by ncw** [comment]
@kel30a glad you got to the bottom of it.  That is probably a bug - the dropbox code is supposed to cope with directories in different cases as dropbox doesn't reliably preserve the case of directories as you've seen.  Can you report a separate issue please?

Thanks

Nick

**Comment by kel30a** [comment]
Done: #691

**Comment by ncw** [comment]
I'm going to close this since rclone no longer has any ACD keys and Amazon aren't issuing new ones.
