### ISSUE TITLE
Google document deleted if same name extensionless file copied over it

### ISSUE THREAD

**Issue by okaresz** [rclone/rclone#1073]
On drive exists a google document "someDoc".
On localhost exists a file named "someDoc".
If i copy or sync the local dir to the drive, the following happens regarding someDoc:
```
(attempt1:)
someDoc: corrupted on transfer: sizes differ 4 vs 0
someDoc: Removing failed copy
(attempt2:)
someDoc: Copied (new)
```

As much is I was able to track down the bug, here is what happens:
1. copy/sync  
   - when copy, dst filesys is not traversed, so Put() is called on remote fs
   - when sync, dst fs is traversed, but google doc filename is extended with the export extension, so there is no match with local file -> Copy() operation, then Put() is called to upload local file
1. In both cases, the google drive Put() checks if dst object exists, by constructing a new object from remote name string with newObjectWithInfo(). But in newObjectWithInfo() call chain, setMetaData() is used to build the file object, which doesn't set the isDocument flag.
1. so o.fs.svc.Files.Update() or o.fs.Upload() (if multiple chunks) is called on a google document, which fails.
1. Copy() operation gets the dst object from the called Put(), which still lacks the isDocument flag. Copy() then checks if local file has the same size as uploaded, but the google document reported size is zero, so it calls removeFailedCopy() on the google document, which is successfully deleted.
1. In the next attempt iteration, there is no google document and local file gets uploaded successfully.

What could be the best solution for this? (I'm not so familiar with the code to decide de optimal point for this fix)

rclone v1.35-DEV (commit 8068ef96b6c, jan 26. 2017) on Linux Mint 64bit

**Comment by ncw** [comment]
Well done for tracking that down - that is a clearly nonsensical series of events.

What do you think should happen here?

I would kind of expect an extension-less file to overwrite a google doc, but it clearly doesn't work properly!  

To fix newObjectWithInfo() shouldn't find the google doc without extension at all - that would be consistent with the ListDir code - the extensionless Google Docs are never output. That would then cause a file with the same name as the google document to be created which would probably turn out OK as far as rclone is concerned and would probably be OK with the user.

Maybe it should be giving an error instead?  That might be more what people expect.

What do you think the correct outcome is?  Once we've worked out that then we can work out how to get there!

**Comment by animosity22** [comment]
@okaresz  - I see this is an old item. I did a quick test with your scenario and it does seem to work now. Did you want to check and validate so we can close it out?

This is what I did:

```
textere@seraphim Downloads % rclone copy SomeTest.docx GD: -vv --drive-import-formats docx
2020/05/20 18:33:36 DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "copy" "SomeTest.docx" "GD:" "-vv" "--drive-import-formats" "docx"]
2020/05/20 18:33:36 DEBUG : Using config file from "/Users/textere/.config/rclone/rclone.conf"
2020/05/20 18:33:36 DEBUG : SomeTest.docx: Modification times differ by -1m23.020732714s: 2020-05-20 18:32:40.286732714 -0400 EDT, 2020-05-20 22:31:17.266 +0000 UTC
2020/05/20 18:33:38 INFO  : SomeTest.docx: Copied (replaced existing)
2020/05/20 18:33:38 INFO  :
Transferred:   	   11.653k / 11.653 kBytes, 100%, 9.294 kBytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         1.2s

2020/05/20 18:33:38 DEBUG : 6 go routines active
2020/05/20 18:33:38 DEBUG : rclone: Version "v1.51.0" finishing with parameters ["rclone" "copy" "SomeTest.docx" "GD:" "-vv" "--drive-import-formats" "docx"]
```

**Comment by ivandeex** [comment]
Related to https://github.com/rclone/rclone/issues/4412 (handling duplicate file names on Gdrive)

**Comment by ivandeex** [comment]
@okaresz Does the problem reproduce with rclone 1.54?

**Comment by ivandeex** [comment]
@okaresz 
We believe that problem was resolved presumably on provider side.
Also, this ticket was reported against rclone 1.35 which is obsolete now.
Latest versions have many improvements and I urge you to try 1.54 out.
I am going to close this stale ticket as the last comment from user landed 4 years ago.
Feel free to resubmit if your problem persists. Thank you.
