### ISSUE TITLE
Unmount don´t work

### ISSUE THREAD

**Issue by Massaguana** [rclone/rclone#1075]
When i wood like to unmount my mounted GSuite Drive with:

`fusermount -u /var/lib/plexmediaserver/Media/`

nothing happens... the files are still there visible...

mounting with:
`rclone mount --allow-non-empty --allow-other --read-only GSuiteCrypt: /var/lib/plexmediaserver/Media/ &`

No Error Message...

> What is your rclone version (eg output from `rclone -V`)
v.1.35
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
CentOS7 64-Bit 
> Which cloud storage system are you using? (eg Google Drive)
GSuite Business
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by ncw** [comment]
Did the mount succeed in the first place?  Check

```
$ mount | grep rclone
local:/tmp/a on /home/ncw/mnt/tmp type fuse.rclone (rw,nosuid,nodev,relatime,user_id=502,group_id=502)
```

**Comment by Massaguana** [comment]
here are the result:

```
[root@Plex ~]# mount | grep rclone
GSuiteCrypt: on /var/lib/plexmediaserver/Media type fuse.rclone (ro,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
[root@Plex ~]#
```

After an restart the mounts are all away... start with an new one... now it looks like my account are locked..

**Comment by ajkis** [comment]
You can unmount with 
`fusermount -uz /path to/mount`
And you can check your mount with 
`findmnt | grep "rclone mount"`

**Comment by Massaguana** [comment]
okay, -uz works... @ncw please update your Docs, there are -u for unmount

**Comment by ajkis** [comment]
@Massaguana -u is the unmount command, the -z part is to force unmount even when its busy/in use.

**Comment by ncw** [comment]
The docs have been fixed now :-)
