### ISSUE TITLE
[Feature request] Encrypt filenames only.

### ISSUE THREAD

**Issue by AggelosM** [rclone/rclone#1077]
I have encrypted all my files on ACD but not the filenames, and I think it would be nice to have the option to encrypt just the filenames without having to decrypt an then re-encrypt the whole files.

I don't know if such a think is possible though.

**Comment by ajkis** [comment]
Encrypting files names would be just rename and yea it would be great to have some option like encrypt file names and decrypt file names.

**Comment by alex-phillips** [comment]
+1 - would be a great feature to be able to swap between "standard" and "off" filename encrypting without having to redown/up everything. Simply execute rename commands on each file / folder based on which direction you're going.

**Comment by Vesnyx** [comment]
@ncw 

I would like to being implementing this sort of feature, but I'm not sure where to get started.
They way I would like to see it implemented is as an option available to all storage options. If the user created the remote with a flag like "--encrypt-names", then it would decrypt the filenames on mount. Is this possible to implement this way and which file would I begin with?

**Comment by ncw** [comment]
> @ncw
> 
> I would like to being implementing this sort of feature, but I'm not sure where to get started.
> They way I would like to see it implemented is as an option available to all storage options. If the user created the remote with a flag like "--encrypt-names", then it would decrypt the filenames on mount. Is this possible to implement this way and which file would I begin with?

THis is going to be a one off process isn't it?  Run through the remote decrypting the names, renaming the files then changing the crypt mode.

It would be possible to script this using the output from `rclone lsjson --encrypted`.  Probably mounting the underlying remote and doing renames on the files would be most effective.

**Comment by Vesnyx** [comment]
The usecase for the original issue can be solved like that.

I interpreted the issue's name slightly differently. My intention was to add a new feature to crypt that only encrypts filenames (copying a new file results in only name encryption not the data). For this, I'm not sure if it's best to implement in the crypt bucket or as a general flag. 

Essentially, creating a crypt overlay on a bucket with this option will only encrypt and decrypt filenames, not contents.

**Comment by ncw** [comment]
> The usecase for the original issue can be solved like that.
> 
> I interpreted the issue's name slightly differently. My intention was to add a new feature to crypt that only encrypts filenames (copying a new file results in only name encryption not the data). For this, I'm not sure if it's best to implement in the crypt bucket or as a general flag.
> 
> Essentially, creating a crypt overlay on a bucket with this option will only encrypt and decrypt filenames, not contents.

Oh I see.  That would still need to be run by the crypt backend but with a no_encrypt_data option or something like that.

**Comment by Vesnyx** [comment]
Yep, that's the plan. I feel like it shouldn't be too hard to implement. Just one more question before I move forward. How can I ensure backwards compatibility? I'm not sure if adding a new setting would disrupt the config file in some way. I'm gonna to format it so that the default option is to encrypt data and only if the user changes the option will it not encrypt it.

**Comment by ncw** [comment]
> I'm gonna to format it so that the default option is to encrypt data and only if the user changes the option will it not encrypt it.

That sounds fine.  A new option is probably required, where the default value is "encrypt".  Hence my suggestion `no_encrypt_data`.

**Comment by ivandeex** [comment]
Implemented by https://github.com/rclone/rclone/pull/2981
