### ISSUE TITLE
Integrate C14 with rclone

### ISSUE THREAD

**Issue by edouardb** [rclone/rclone#1080]
As mention on the discourse forum (https://forum.rclone.org/t/add-c14-from-online-net-as-target/314/4),  it would be awesome to have an integration of Online C14 (https://www.online.net/en/c14) with rclone. 

The API documentation is available at the following address: https://console.online.net/en/api/ in the `/storage/c14` section.

A few months ago we published a blogpost explaining how C14 works, It can be helpful to have a good overview of the product: https://blog.online.net/2016/07/04/c14-the-secure-cold-storage-platform-for-free-during-the-summer/

If you have any questions, let me know.

Edouard

**Comment by ncw** [comment]
I'll just note that the sftp support scheduled for release in 1.36 works really well with C14 (thanks for the test account!).

**Comment by alexanderkjeldaas** [comment]
Does this mean C14 is supported?  Then the website should probably be update, I just filed a duplicate issue regarding this.

**Comment by ivandeex** [comment]
https://www.online.net/en/c14 is 404 for me now

**Comment by ncw** [comment]
The URL is here: https://www.scaleway.com/en/c14-cold-storage/

Support for this is working and it is now in the docs, so I'm going to close this now.

**Comment by ncw** [comment]
@jarthod thanks for the update on this.

> For the record I just tried using this SFTP remote with C14 and couldn't because C14 "Archives" and the SFTP access are deprecated.

We should remove this entirely from the SFTP docs then I think.

> The new version mentionned in https://www.scaleway.com/en/c14-cold-storage is actually S3 only. This [blog post talking about rclone with SFTP access](https://blog.scaleway.com/c14-with-rclone-sync-files-and-directories-to-c14-from-anywhere/) and the [C14 CLI client](https://github.com/scaleway/c14-cli) are deprecated (I told Scaleway about this, hopefully they'll update it).

Well done.
 
> The "new" C14 Cold Storage version is still totally usable with rclone but [using the standard "Scaleway" config (S3)](https://rclone.org/s3/#scaleway) with `storage_class = GLACIER` (see the short [documentation](https://www.scaleway.com/en/docs/faq/coldstorage/#can-i-upload-an-object-directly-to-the-%22glacier%22-class)). So now it works like AWS S3 I suppose? (I never used S3)

Are you saying the new C14 storage **is** Scaleway S3 but with `storage_class = GLACIER`, or are you saying that it is just equivalent to C14?

Would you like to update the docs? The source docs are here for sftp - we need C14 removed here

https://github.com/rclone/rclone/blob/master/docs/content/sftp.md

and here for s3 where we should mention C14 and the GLACIER style interface in the Scaleway section.

https://github.com/rclone/rclone/blob/master/docs/content/s3.md

I note that we already offer GLACIER when configuring an s3 Scaleway provider

```
Press Enter to leave empty.
 1 / Default.
   \ ()
   / The Standard class for any upload.
 2 | Suitable for on-demand content like streaming or CDN.
   \ (STANDARD)
   / Archived storage.
 3 | Prices are lower, but it needs to be restored first to be accessed.
   \ (GLACIER)
```

**Comment by jarthod** [comment]
> Are you saying the new C14 storage is Scaleway S3 but with storage_class = GLACIER, or are you saying that it is just equivalent to C14?

Yes, as far as I understand even though the "glacier" offering is still called "C14 Cold Storage", it is now merged with their "Object Storage" (S3 equivalent) product. There's no longer any C14 UI or API, it's only the "Object Storage" UI now and objects created in these buckets can either have the "STANDARD" or "GLACIER" storage_class, which puts them in regular "Object Storage" or "C14" at the advertised price and access constraints.

> I note that we already offer GLACIER when configuring an s3 Scaleway provider

Nice well that's one less thing to do then ;)

Thanks for pointing to the doc files, I'll draft a PR :+1:

**Comment by jarthod** [comment]
Here is the PR: #6069
