### ISSUE TITLE
[Feature Request] Fast remote bytes used 'usageInDrive'

### ISSUE THREAD

**Issue by 4getit** [rclone/rclone#1083]
Hello,

I'm currently trying to keep several larger remotes in sync. (30TB+/20K+ files)
Since I don't want any files deleted from the source, I use the copy instead of the sync command (not sure if there's a better way).

I start a cron job every hour but it takes 10 minutes just to get the file listings only to figure out that nothing has changed. Then I move on to the next one.

I was wondering if it would be an idea to add an 'about' or 'info' command. This is not directory specific but it gives a fast number of the total bytes on the remote. 

https://developers.google.com/drive/v3/reference/about gives me 'usageInDrive' and when I try it, the result is instant.

I'm sure there would be other uses but in my case, I could then run ./rclone about xyz: on both the source and target, parse the output and skip the copy command if these numbers are the same.

I tried ./rclone size but although this can be used for directories, it goes over all files making it also very slow.

I don't know if the API's for the other remotes offer this as well.

**Comment by ncw** [comment]
This is now implemented by `rclone about remote:` :-)
