### ISSUE TITLE
Incorporation of S3 transfer acceleration endpoint into rclone?

### ISSUE THREAD

**Issue by mcianfrocco** [rclone/rclone#1090]
This is less of a 'problem' and more of a functionality request - 

Given S3's transfer acceleration feature, I was wondering if rclone could incorporate the accelerated URL endpoint into the upload command to make the upload speeds even faster? 

-mike

**Comment by ncw** [comment]
Looks like this is supported in the s3 go module [WithS3UseAccelerate](https://godoc.org/github.com/aws/aws-sdk-go/aws#Config.WithS3UseAccelerate)

Fancy sending a PR?

**Comment by mcianfrocco** [comment]
Sorry for the naive question - but you're asking for me to submit a pull request related to this issue? I definitely can, but wanted to make sure : )

**Comment by ncw** [comment]
@mcianfrocco Sorry I shouldn't have used the abbreviation.  Yes I'd love to see a pull request for this feature if you have time to make one.

Thanks

Nick

**Comment by ivandeex** [comment]
Closing after 4 years of inactivity

**Comment by BasixKOR** [comment]
In case someone was looking for this feature... it is already implemented via https://github.com/rclone/rclone/commit/b68c3ce74dd1697f1ef52895b6fbc30fd133a1d3. Sorry for the AI slop on the above.
