### ISSUE TITLE
md5sum file blank on encrypted Amazon Drive

### ISSUE THREAD

**Issue by greycubesgav** [rclone/rclone#1091]
Hi;

I'm having an issue generating an md5sum file on an encrypted Amazon Drive end point. When I run the command a file is generated but there's space padding where all the md5sums should be.

Presumably this is something to do with this issue: #854 However I can't see any documentation or comments on if the md5's should be available or not for encrypted remotes.

I'm guessing that the md5sum feature is designed to use the remote storage provider's own metadata, but when an file is encrypted remotely you would get the md5sum of the remote encrypted file, not the original decrypted version? Therefore is this command not possible with an encrypted remote?

Thanks

> What is your rclone version (eg output from `rclone -V`)
rclone v1.35
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
FreeBSD c10.3-STABLE FreeBSD 10.3-STABLE #0 r295946=5327704(9.10-STABLE): Wed Aug  3 12:13:26 PDT 2016     root@build.ixsystems.com:/tank/home/nightlies/build-freenas9/_BE/objs/tank/home/nightlies/build-freenas9/_BE/os/sys/FreeNAS.amd64  amd64
> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone md5sum ad_vault:photos/storage/2015/2015-05-01/
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
2017/02/02 20:07:27 rclone: Version "v1.35" starting with parameters ["rclone" "-v" "md5sum" "ad_vault:photos/storage/2015/2015-05-01/"]
2017/02/02 20:07:29 Encrypted amazon drive root 
'vault/xxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxx': Modify window not supported
2017/02/02 20:07:29 amazon drive root 'vault/xxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxx':: Reading ""
                                  _D603108.NEF
                                  _D603106.NEF
                                  _D603110.NEF
                                  _D603089.NEF
                                  _D603107.NEF
                                  _D603091.NEF
                                  _D603109.NEF
                                  _D603092.NEF
                                  _D603111.NEF
                                  _D603103.NEF
2017/02/02 20:07:29 amazon drive root 
'vault/xxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxx':: Finished reading""
                                  _D603104.NEF
                                  _D603090.NEF
                                  _D603102.NEF
                                  _D603093.NEF
                                  _D603112.NEF
                                  _D603105.NEF
                                  _D603113.NEF
2017/02/02 20:07:29 Go routines at exit 9

**Comment by ncw** [comment]
Unfortunately crypt remotes don't support MD5SUMs yet.

> I'm guessing that the md5sum feature is designed to use the remote storage provider's own metadata, but when an file is encrypted remotely you would get the md5sum of the remote encrypted file, not the original decrypted version?

100% correct.

I need a place to put the encrypted MD5SUM as metadata on the objects which I haven't had time to do yet.

It does mention it here in the docs:

http://rclone.org/crypt/#modified-time-and-hashes

**Comment by jaketame** [comment]
Not sure if you looked into a keystone yet but this might be of use;
https://godoc.org/github.com/paypal/go.crypto/keystore

**Comment by naeloob** [comment]
Sorry to hijack the threat.
First thanks for that great tool and the great support on it.

Back On Topic : 
Instead, or sidebyside, of putting the unencripted hash somewhere, as metadata of remote (if it that remote  supports that), or locally, how about an option to do this: 
 - Download the first 32Bytes of the file
 - Checks de "magic" string is right
 - Extracts the Nounce and makes the MD5(whatever checksum) from the crypt of the original file with that Nounce.

I think it's the only way to know that really that the encrypted file Cheksum matches the original.
Anther app or the user could change the file without updating the metadata or the local unecrypted checksum.
Also, that way you can check crypt files upped before the "new version" without upp again or download, checksum and update the metadata or localstore.

@ncw what do you think? It's possible?

Regards

**Comment by ncw** [comment]
I think the lack of MD5SUMs is covered in other issues and `rclone cryptcheck` now means you can check the checksums.
