### ISSUE TITLE
ChunkSize configurable by File Size

### ISSUE THREAD

**Issue by naeloob** [rclone/rclone#1096]
I think i will help to save time when upload files of heterogeneous sizes.

The basic Idea is make the chunkSize by file level, i mean, every file uploads with a own chunkSize.
The user can make a "table" that defines the chunkSize related to a FileSize of the File to Upload.
It can be like the BW scheduler, something like : 
--chunkRates="16M 100M,32M 1G,128M 4GB,256M "
It means : 
 - Files from 0 to 100M Chunk=16M
 - Files from 100M to 1G Chunk=32M
 - Files from 1G to 4G Chunk=128M
 - Files from 4G Chunk=256M

In a future the app could calculate that "table".

**Comment by ncw** [comment]
Unfortunately the meaning of chunk size varies from remote to remote and there are lots of different constraints, so a general purpose implementation isn't possible.

Which remote are you interested in particularly?

**Comment by naeloob** [comment]
Thanks for your answer....

What about having this parameter as a "remotename" and no global parameter, i mean, you could have a configuration for "MyGdrive1Crypt" and another one for "MyGdrive2" or "MyAmazonWork".
That way, the meaning remains from remote type and you can have diferent parameters for anyone.

Expanding the ideasome parameters could be saved on config, in the remotename part, as default parameters for that remotename.

Actually i'm interested in Gdrive, but i hope this could be usefull for any remote, of course if it apply to that remote.

Regards

PD: English is not my motherlanguage so please forgive my writing/explain mistakes.

**Comment by ncw** [comment]
You can now add a `chunk_size` config parameter to remotes which support it, so I think this is done now :-)
