### ISSUE TITLE
local to local loses mode x bits (metadata not preserved)

### ISSUE THREAD

**Issue by jkt628** [rclone/rclone#1097]
after copy local to local all the executable mode bits were lost.  to recreate:
```bash
rm -rf /tmp/foo
rclone copy /bin /tmp/foo
find /bin -executable | wc -l
find /tmp/foo -executable | wc -l
```

> What is your rclone version (eg output from `rclone -V`)
rclone v1.35-DEV

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
openSUSE Linux Leap 42.2, x86_64
CentOS 7, x86_64

> Which cloud storage system are you using? (eg Google Drive)
none

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy /bin /tmp/foo

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
[rclone-copy-bin-foo.txt](https://github.com/ncw/rclone/files/751426/rclone-copy-bin-foo.txt)

**Comment by ncw** [comment]
This is as I expected - rclone doesn't attempt to preserve the more of the file.

However at for most users it is unexpected and I'd like to fix it eventually!
