### ISSUE TITLE
ACD - 429 errors, exclude file ignored etc.

### ISSUE THREAD

**Issue by jxs714** [rclone/rclone#1099]
Hey guys,

Great job on the software, its Excellent!

Just having a few issues trying to backup linux dedicated server files to Amazon Drive. Here are the issues:

• Constant 429 too many requests errors
• Some files will just not copy and give the following error: corrupted on transfer: sizes differ SMALLSIZEFILE vs BIGGERSIZEFILE
• Excludes file isn't being considered/used
• Progress isn't displaying in command line.

Am I missing anything? Also had this problem with the copy command, but before it gave me errors saying 409 name already exists. Not sure if my commands are wrong or if Amazon has a restriction.

Would like to solve this soon. Really appreciate your help guys :)

Specs below:

version 1.35
CentOS 6.8/Cloudlinux
Amazon Drive

Command: rclone -c -v sync --exclude-from exclude.txt --log-file amazoncloudlog.txt / remote:/FOLDERNAME/$(date +%m-%d-%Y-%H:%M)

[amazoncloudlog.txt](https://github.com/ncw/rclone/files/751602/amazoncloudlog.txt)

Excludes file has the following:

/dev/*
/proc/*
/sys/*
/tmp/*
/rsync/*
/run/*
/mnt/*
/media/*
/boot/*
/lost+found
/usr/share/cagefs-skeleton/
/etc/sysconfig/network-scripts/*
/etc/fstab
/var/cagefs/*
/root/.ssh/id_rsa
/root/.ssh/id_rsa.pub
/root/.ssh/known_hosts

**Comment by ncw** [comment]
> Constant 429 too many requests errors

That is Amazon I'm afraid... rclone does lots of retries so it will get there in the end.

> • Some files will just not copy and give the following error: corrupted on transfer: sizes differ SMALLSIZEFILE vs BIGGERSIZEFILE

```
2017/02/03 16:12:03 amazoncloudlog.txt: corrupted on transfer: sizes differ 1412 vs 4683
2017/02/03 16:12:03 amazoncloudlog.txt: Removing failed copy
```

These look like files which are being written to while rclone is running.

> • Excludes file isn't being considered/used

You need to use `/sys/**`  if you want to match `/` in the path (which you do)

> • Progress isn't displaying in command line.

Use the `--stats` command to change the rate of progress printing, or `-v` for line by line account of what is happening.

**Comment by jxs714** [comment]
Hi Nick,

Thanks for the update and support! The file issue still occurs with other files where they say corrupted on transfer as well. How can i at least solve this issue with other files?

**Comment by jxs714** [comment]
Also, any way to limit the file transfer so that so many 429's dont occur?

**Comment by ncw** [comment]
> The file issue still occurs with other files where they say corrupted on transfer as well. How can i at least solve this issue with other files?

The other files looked like there were in /sys which hopefully the `/**` change will stop uploading.

> Also, any way to limit the amount of files to transfer at a time or limit the upload speed so that 429's dont occur?

You can try reducing `--transfers` and/or using `--bwlimit`.  Not sure either will help, but worth a go!

**Comment by jxs714** [comment]
Hi Nick,

Thanks for the quick response. Hmm ok. Well yeah, regardless how it goes, there are always files that end up saying corrupted on transfer. Any advice? Also, any advice on the best and cheapest platform to use that will work smooth with Rclone without these issues?

**Comment by mmiat** [comment]
similar error: https://github.com/ncw/rclone/issues/1106

**Comment by animosity22** [comment]
With ACD removed, I'm closing this out.
