### ISSUE TITLE
[ Feature Request ] ACD on files access drop and reconnect if speed less then X

### ISSUE THREAD

**Issue by ajkis** [rclone/rclone#1109]
I noticed something really interesting with ACD and its that sometimes it can throttle bandwith really badly.

For example this test was done within same minute.

> 06.02.2017 20:27:37 ACD COPY SPEED TEST START
> |   PROGRESSs   |   RATE   | AVG. RATE |
> ^C.1MiB 0:00:51 [   2MiB/s] [1.55MiB/s] [==========>                                                                                                                                                          ]  7% ETA 0:10:09
> ACD Copy ended  51 seconds
> 
U cancled it when it was still bellow 100MB transffered 
Then I run it again 

> 06.02.2017 20:28:44 ACD COPY SPEED TEST START
> |   PROGRESSs   |   RATE   | AVG. RATE |
>    1GiB 0:00:19 [  52MiB/s] [  52MiB/s] [===================================================================================================================================================================>] 100%
> ACD Copy ended  19 seconds

It both cases i was copying the same file but it seems sometimes ACD can server file on "poor" connection.

**Comment by ncw** [comment]
I have noticed the same thing - that sometimes ACD transfers are much slower and sometimes much faster.  I conjecture they are connecting to different bits of infrastructure.

I've never seen that big a difference though, only ever about 2x.

**Comment by animosity22** [comment]
Closing this out with ACD going away.
