### ISSUE TITLE
Feature request: Copy custom metadata on objects

### ISSUE THREAD

**Issue by mlanner** [rclone/rclone#111]
For object storage systems that support custom (user defined) metadata types, include a flag (`-meta`?) that will also copy custom metadata from source to destination. For example, if copying/migrating data from Amazon S3 to Swift, or from Swift to Swift, it would be very handy to be able to maintain any custom metadata set on the objects.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
@mlanner nice idea - I've wanted exactly this before when moving stuff about in Swift.  Not sure how I'd implement it - I'll have a think.

**Comment by mlanner** [comment]
@ncw How about something like: If you invoked the `-meta` flag in your Rclone command, then it will head the object, read the custom metadata and then store it in a temporary json blob. Once the object has been transferred and the md5sum has been checked, the metadata stored in json will be applied through a post to the object in the destination container/bucket. ?? It might require a few extra operations, but it would only take a hit if you invoke the `-meta` flag, and the operations would (perhaps) not be ridiculously expensive.

Only an idea. I'm sure there might be better ways to do this, as I'm not much of a developer myself.

**Comment by jamshid** [comment]
I wonder if metadata could be stored in file attributes (https://en.wikipedia.org/wiki/Extended_file_attributes), so we don't need a separate/temporary json file.

**Comment by ncw** [comment]
@jamshid not a bad idea.. I wonder if it can be done in a cross platform way from go...

**Comment by ncw** [comment]
An implementation idea - we pass the source object to the Put methods.  Do a type assertion at that point to break out the metadata - not too tricky.

**Comment by freedge** [comment]
> could be stored in file attributes

@jamshid  @ncw that's how it's done when using [JClouds with the "filesystem" blob store ](https://jclouds.apache.org/guides/filesystem/) implementation. For example:

```
$ attr -l ./Package_98/Package_98_version_13
Attribute "user.content-md5" has a 16 byte value for ./Package_98/Package_98_version_13
Attribute "user.user-metadata.sha1" has a 3 byte value for ./Package_98/Package_98_version_13
Attribute "user.content-type" has a 19 byte value for ./Package_98/Package_98_version_13
Attribute "user.user-metadata.package" has a 10 byte value for ./Package_98/Package_98_version_13
Attribute "user.user-metadata.version" has a 2 byte value for ./Package_98/Package_98_version_13
```

the user.user-metadata are the custom metadata that are set on the object (in this case that would match the headers ```x-amz-meta-package```, ```x-amz-meta-sha1```,```x-amz-meta-version``` that S3 would return)

**Comment by erik78se** [comment]
I'm also interested in this feature. Just be aware of the max size of the metadata in swift/s3 object storage vs max size for the intended transfer method you intend to use. It could otherwise end up in a situation where metadata is lost when out of space to transfer it.

**Comment by pharveybattelle** [comment]
I'm also interested in this feature, specifically to be able to preserve metadata when copying from one S3 alike system to another S3 alike system.

**Comment by pol1000000** [comment]
Hi @ncw, 
I want to say many thanks for your great job!
Rclone is really helpful with a lot of tasks!

I have some suggestions to improve implementation:

- usage of the `--meta` flag with `"<Key>=<Value>"` pairs to upload already prepared files for websites with metadata flags to gcs, S3 or other providers buckets that support such flags
eg, 
`rclone sync --meta "Content-Language=en" /local-path-with-static-content remote:path`

- compression on the fly and set `--meta "Content-Encoding=gzip"` when the uploading of some file is finished to a remote. that implemented in gsutil as flags "-Z" and "-z <file extension>" and well documented [here](https://cloud.google.com/storage/docs/gsutil/commands/cp#options). 
eg, 
`rclone sync -z "html txt js" /local-path-with-static-content remote:path`
or
`rclone sync -Z /local-path-with-static-content remote:path `

- and finally, it just would be great to combine both suggestions in one line, eg,
`rclone sync -z "html txt js" --meta "Content-Language=en" /local-path-with-static-content remote:path`
or 
`rclone sync -z "html txt js" --meta "Content-Language=en" /local-path-with-static-content remote:path`

I think it'll very useful for buckets used as CDN for static content or as hosting for static websites

**Comment by ncw** [comment]
@pol1000000 thanks for your suggestions.

I hadn't thought of a `-z` flag before.  There is another open issue #2658 about Content-Encoding: gzip which that could help with.  Can you please make a [new issue on github](https://github.com/ncw/rclone/issues/new/choose) suggesting the flag.  I think having a `-z` flag would fix the issues in #2658 if it was used for download which would mean download the compressed objects.

**Comment by ivandeex** [comment]
Blocks on https://github.com/rclone/rclone/issues/1066 (capabilities inventory)

**Comment by yccheok** [comment]
Hi, wondering is there any update on this? Thank you.

**Comment by shanness** [comment]
Hey.  Just another ping on if there is any update on this?  It's been removed from future milestones, and is costing me a fortune to keep having to use flexify.io for backing up my objects from digital ocean.  If this isn't planned for any time soon, does anyone else monitoring this know of any tools apart from flexify that support metadata backs of S3 compatible services (like Wasabi or Digital Ocean)?

**Comment by ivandeex** [comment]
No short term plans.
Volunteers welcome, pull requests, help wanted.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by shanness** [comment]
Hey everyone.  It seems s3cmd now supports full metadata syncing (released yesterday!).  Lots of metadata fixes and improvements (search this page for metadata)
https://github.com/s3tools/s3cmd/releases
```
Improved remote copy to have consistent copy of metadata in all cases: multipart or not, aws or not
```

I just did some tests, and it's preserving all metadata by default!  YAY!!

**Comment by ivandeex** [comment]
@shannes
That's great news.

Unfortunately we still lack a central metadata framework in rclone to pass, store and optionally convert representation of metadata between backend instances.

It's a long-term project. We still need to brainstorm various approaches :(

cc @ncw

**Comment by ivandeex** [comment]
@shannes
That's great news.

Unfortunately we still lack a central metadata framework in rclone to pass, store and optionally translate metadata between backend representations.

It's a long-term project. We still need to brainstorm various approaches :(

cc @ncw

**Comment by henri9813** [comment]
Hello,

Are they any update on this subject ?

Best regards,

**Comment by upintheairsheep** [comment]
Should there be a separate object for comments and activity, or have them all in the same file

**Comment by darthShadow** [comment]
@ncw Is there anything further pending from this ticket?

I believe backend-specific metadata implementations should have their own tickets as & when required and there is already a separate ticket for tracking folder metadata: #6685
