### ISSUE TITLE
Dropbox - Failed to copy: upload failed: Failed to grab locks for 253673584: lock held by connection 21020332. Please re-issue the request.

### ISSUE THREAD

**Issue by jxs714** [rclone/rclone#1110]
Hey guys,

Just tried purchasing Dropbox Pro to get passed any issues with Rclone and file transferring with Amazon Drive, and now we're at issues again without a smooth experience.

Errors:
• Failed to copy: upload failed: Failed to grab locks for 253673584: lock held by connection 21020332. Please re-issue the request.
• corrupted on transfer: sizes differ 7992724 vs 7993607

These errors are happening several files. At one point we received a "too many requests" issue the same as Amazon Drive. We arent receiving that error, but now these are new issues. 

I am convinced that whatever cloud platform used, the issue will continue to happen without a smooth experience.

Command:
rclone -c -v sync --exclude-from rcloneexcludesfirst.txt --log-file dbbackuplog.txt --retries 10 / dropbox:/backups/FOLDER

Is there any smooth experience at all with fully backing up a linux dedicated server to any of the cloud platforms with Rclone?

Please advise, thanks guys.

**Comment by ncw** [comment]
Could platforms work over the network and they are unreliable because of it.

However rclone does lots of retries, so works around errors like the above.

What did rclone print at the end of the transfer?

**Comment by jxs714** [comment]
Hi,

Thanks for the response. I stopped the transfer because of the continuous "corrupted on transfer" errors. At end, many files would copy, other wouldn't, retries didn't solve the issue for corrupted transfer, but did for some files that gave the "failed to copy" error. Having to run the command over and over would be hard to keep up with especially when rclone is being set up as 1 cron job in expectation for all files to copy safely as a backup. Having to run the command several times until important files copy (and this is not including the too many requests error) is a little worrying, especially if you copy over OS files and one day you restore to only find out that a new restored server will not operate because of files you didn't see were missed during the transfer.

**Comment by ncw** [comment]
The occasional `Failed to copy: upload failed: Failed to grab locks for 253673584: lock held by connection 21020332. ` is to be expected.

However continuous corrupted on transfer messages aren't.

Where were you copying from and to?  Were the files being modified while being copied?

**Comment by jxs714** [comment]
Hi,

Copying and backing up from a linux CentOS/Cloudlinux server to Amazon Cloud and/or dropbox pro with the same errors. Files were not be modified and were set for both copy and sync, but still gave the same errors on the first initial transfer. Sent over the original commands I've used for both the Dropbox in this post, and Amazon in the other post here: https://github.com/ncw/rclone/issues/1099

**Comment by ncw** [comment]
@jxs714 in #1099 the corrupted files were caused by your exclude of `/sys/` not working.  I pointed out how to make it work in that ticket.

If you can correct your excludes hopefully the corrupted messages will disappear.

You might find the `-x` flag useful too

    -x, --one-file-system                   Don't cross filesystem boundaries.

**Comment by ncw** [comment]
No-one has reported this error for a long time, so I'm going to assume it is fixed.
