### ISSUE TITLE
Add a "protect" filter rule, similar to rsync's

### ISSUE THREAD

**Issue by Saviq** [rclone/rclone#1115]
If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
v1.35-DEV

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 64 bit

> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync remote:tmp tmp

When syncing, I'd sometimes like to protect some local files from deletion. It's only possible with --exclude today, but that means that if a file matching that pattern is in source, it won't be copied down.

rsync (http://www.linuxcommand.org/man_pages/rsync1.html) implements a bunch of advanced filter rules:
```
exclude, - specifies an exclude pattern.
include, + specifies an include pattern.
merge, . specifies a merge-file to read for more rules.
dir-merge, : specifies a per-directory merge-file.
hide, H specifies a pattern for hiding files from the  transfer.
show, S files that match the pattern are not hidden.
protect,  P  specifies a pattern for protecting files from deletion.
risk, R files that match the pattern are not protected.
clear, ! clears the current include/exclude list (takes no arg)
```

It'd be nice if rclone had implemented those as well.

**Comment by ncw** [comment]
Nice idea.  I deliberately didn't implement all the rsync rules to keep things simple.  However protect sounds like a good next one to do.

Do you fancy having a go?

**Comment by ivandeex** [comment]
Closing after 4 years of inactivity

**Comment by freywald** [comment]
This has been closed. Please reopen the issue and implement hide and protect. Then if it behaves like rsync I can finally use --delete-excluded and protect and hide remote files (my backup directory that is within the project root) that are excluded that still shouldn't be deleted  like other files.
