### ISSUE TITLE
Fuse mount / filetransfer slow(stuck at 4.5MB) 

### ISSUE THREAD

**Issue by CiwO** [rclone/rclone#1123]
I noticed that some files are opened quite slow and I checked the fuse mount with:
mount --allow-other --read-only --verbose --log-file /rclone.log --debug-fuse XX: /XX (crypted amazon cloud drive)

Some files (20%) are transfered will full speed (tested with cp on mount to a local device).
But most files stuck at 4.5MB - the transfer starts with good speed till 4.5MB than it does nothing for 10-20seconds and than again full speed till file is tranfered complete.

It stuck allways on same offset:
r03: ReadFileHandle.Read size 131072 offset 5111808
r04: ReadFileHandle.Read size 131072 offset 5111808
r07: ReadFileHandle.Read size 131072 offset 5111808
r51: ReadFileHandle.Read size 131072 offset 5111808

I have no idea whats causing this....

Some of this filese are also currupt (bad crc) after download:
Unexpected end of archive
.mkv : packed data checksum error in .r51

**Edit1.1:**
I tested the original file - crc is OK! - I'm not sure if its broken during upload to ACD or while download due to the stuck bug above ... Any idea how to figure that out?

**Edit1.2:**
The problem is caused only when trying to download/copy files over fuse mount point:

**- Tested with download over rclone:**
./rclone copy --stats 5s server:/test/ /test/
Download over rclone copy take less then 2 minutes for 2GB rar files
unrar x ....
.mkv OK

**- Here the copy over fuse mountpoint:**
cp /amazonclouddrive/test/* /test/
openning/copy files over fuse mount quite slow (copy takes more than 8minutes) and causing below errors, trying to unrar files results in bad crc
/amazonclouddrive/test/*.r22: ReadFileHandle.Read error: low level retry 1/10: unexpected EOF
/amazonclouddrive/test/*.r22: ReadFileHandle.Read error: low level retry 2/10: unexpected EOF
/amazonclouddrive/test/*.r22': Input/output error
/amazonclouddrive/test/*.r30: ReadFileHandle.Read error: low level retry 1/10: unexpected EOF
/amazonclouddrive/test/*.r30: ReadFileHandle.Read error: low level retry 2/10: unexpected EOF
/amazonclouddrive/test/*.r30': Input/output error

.mkv - checksum error
Unexpected end of archive
*.mkv : packed data checksum error in volume *.r22
Unexpected end of archive
*.mkv : packed data checksum error in volume *.r30
Total errors: 3

**Notes:**
Ubuntu 16.04 LTS / 4.4.0-47-generic
Fuse version (2.9.4-1ubuntu3.1)
Rclone v1.35

**Comment by ncw** [comment]
Can you retry with the latest beta please?  (See downloads page).

I think this problem may be fixed already

**Comment by CiwO** [comment]
v1.35-80-g40c0298 - still stuck for serveral serconds at 4.5MB
4.5M Feb 12 17:36 ***.r00 - checked with ls -lhS after starting cp over fuse mount to local hard drive

**Comment by ncw** [comment]
The latest version may still get stuck, but it should always carry on correctly and not truncate files or give IO errors.

**Comment by CiwO** [comment]
I will try unrar once download is finished... it's still quiet slow - takes 10-15minutes for 1.5gb over fuse mount

**Comment by ncw** [comment]
Thanks.

The pauses are caused by some kind of network error, and rclone having to reconnect.  I'm not sure exactly why though, but it could be amazon, or it could be a local networking problem.  Have you checked your router has the latest firmware?

**Comment by CiwO** [comment]
I'm using rclone on a dedicated server - I tested rclone fuse mount point in three different datacenters and also at home.

The pauses was caused on all tests.

**Comment by ncw** [comment]
Very strange!  Something happening at Amazon most likely.

When you do the transfer with `rclone copy` can you see if you see a pause with that too?

**Comment by CiwO** [comment]
There is also a stop but at 5.0MB (but faster due to 4 transfers)

48M Feb 12 18:19 *.r11
40M Feb 12 18:19 *.r12
5.0M Feb 12 18:19 *.r20
5.0M Feb 12 18:19 *.r23
5.0M Feb 12 18:19 *.r24

**Comment by ncw** [comment]
OK so the pause is not to do with `rclone mount` specifically.

**Comment by breunigs** [comment]
Try downloading the file from the Amazon Drive web interface and see if you get similar slow speeds (or export a sharing link and use `curl` or something to get more insights). I experienced similar issues recently where single file speeds were in the ~300 kB/s range, but the data came in bursts. Could be you have similar issues.

**Comment by SchnorcherSepp** [comment]
i also have problems to download files from amazon but the upload works great. i think its amazons fault and they will fix it soon....
