### ISSUE TITLE
[question] Gdrive to Amazon from two servers

### ISSUE THREAD

**Issue by dschense** [rclone/rclone#1130]
Is it possible to speed up a copy transfer from Google drive to Amazon cloud drive using two Servers?

Server-A
Server-B

On both Servers connect rclone to Gdrive and Amazon.

Server-A Start: rclone copy --ignore-existing Gdrive:path Amazon:path
Server-B Start  rclone copy --ignore-existing Gdrive:path Amazon:path

to get double Speed ?

**Comment by AzureBlaze** [comment]
If you make sure the folders don't overlap you may be able to speed things up, it's important to note though that for files smaller than ~10-20MB assuming you're using a gigabit server the limiting factor will be API requests/sec and you can't get around this by running multiple sessions, it might even make the problem worse by causing api errors and exponential backoff to kick in.

**Comment by dschense** [comment]
both servers have a gbit connection. and I want to transfer 11TB of Movies. each Movie has something about 4-5 gb. 
And what do you mean with "If you make sure the folders don't overlap" ?

**Comment by AzureBlaze** [comment]
In that case it seems reasonable to expect it to be considerably faster with two servers. 

By not overlapping folders I mean make sure that the two commands aren't transferring the same files, if you have them split into major folders you can split the commands by folder or you could list all directories and create a script to copy them over, but in my experience you want to minimize the number of times rclone starts up so it's better to copy large folders at a time.

**Comment by dschense** [comment]
in my case its one folder on Gdrive with alle Movies in ( about 11TB - every Movie abount 4-5 TB) and this should be copied to one Folder on Amazon.

**Comment by AzureBlaze** [comment]
I would split the folder in in two so you can make the commands a bit easier to run. then merge them after you're done.

**Comment by ajkis** [comment]
You could trick it with FILTERS eg one rclone is copying movies starting on A,B,C,D; etc.. and the other from the other half of alphabet. Once you are done you can just run a sync and check after it to pickup possible leftovers.  http://rclone.org/filtering/

**Comment by dschense** [comment]
thanks, i will try this!
