### ISSUE TITLE
Ability to ignore case on Dedupe

### ISSUE THREAD

**Issue by cuotos** [rclone/rclone#1133]
I am syncing photos from GDrive to S3. I first run a dedupe (with rename) on GDrive as S3 doesn't allow duplicate file names.

But dedupe will consider DSCNxxx.JPG and DSCNxxx.jpg to be different files and ignore them, when I sync to S3 I get

"Warning: File found with same name but different case on S3 bucket"

It would be nice if dedupe had the option to ignore case and still rename files, resulting in

DSCNxxx-1.jpg
DSCNxxx-2.JPG

**Comment by ivandeex** [comment]
Superseded by more general
- #4854
