### ISSUE TITLE
ACD torrented files. Sometimes when I backup my incoming torrent folder, incomplete files on the cloud are overwritten by complete files (good) and sometimes they aren't (bad)

### ISSUE THREAD

**Issue by left1000** [rclone/rclone#1153]
ACD torrented files. Sometimes when I backup my incoming torrent folder, incomplete files on the cloud are overwritten by complete files (good) and sometimes they aren't (bad)

I'm just using a basic rclony copy "source" "remote:destination"
Is there a different command that will make this do what I want?
I know I could use a flag to make files ALWAYS overwrite, but the problem is that sometimes after I backup a file, especially a large video file, I delete it from my harddrive, because say, I don't think I'm likely to need it, but I rarely might. After this happens my torrent program often replaces the file, with the same name, with a <1kb file (this happens because I've left the torrent paused instead of deleting it entirely).

Is there any flag to do what I want?  I had thought the default copy command was working fine, why? because well when the file is updated to a newer local last modified date it usually ends up making the overwrite happen. I just recently ran into an example where it didn't though. It's difficult to tell when there's been a failure though without redownloading the file from ACD and finding it to be broken.

Ideally rclone would compare actual filesize and date, and only overwrite newer AND larger files. The problem is I'm not sure rclone can even see "actual" filesize for non-pre-allocated torrents where the file in windows explorer says filesize:2gb size on disk:1kb

This isn't really a bug, so I am not sure it belongs here, but I do not know who else to ask for a solution. Maybe a collection of flags can be used to achieve what I want, but I am not sure if that's true.

P.S. Where can I email log files? I've got a log file of me trying to upload with rclone copy a valid file to overwrite an invalid file, the invalid file is in theory a file that was uploaded a long time earlier, modified much earlier, created earlier on my harddrive, and the file on ACD is full mostly of random bits because it was just allocated from an incomplete torrent I'd just started, whereas the new file is completely downloaded and functional. note: I wrote this post using rclone v1.33 but I made sure to update to rclone v1.35 when attempting to generate a log of the problem I'm having (although I doubt this issue is addressed in the patches). windows7 64bit.

I've got an example where I backed up with rclone a 20% complete torrent, today, just now, with the torrent NOT pre-allocating all the space. Then I let the torrent finish and tried to back up again.

In the other example the copy on ACD has been there through dozens of rclone copy backup attempts, and for some reason still has an incomplete copy, I recently deleted the file from my computer, redownloaded the torrent entirely and generated this.

P.P.S. I've looked at one of the log files and there's nothing to say about it really, it just says that the files are the same size so no transfer will be made, EVEN THOUGH one file is many months newer than the other file. I need flags that will NOT ignore size NOR ignore date. This is supposed to be the default rclone copy behavior I thought?

Literally the only relevant part of my log file is"
Sizes identical
2017/02/19 06:37:23 FILENAME: Unchanged skipping
"
Yet the file on ACD is listed as from november and the file I'm trying to upload is from today. Does this mean ACD cannot use modification time data at all in anyway? I am aware ACD doesn't store the correct date modified time from the file you upload, but the website does display a date uploaded time. Could not this date uploaded time be used in place of date modified time of the file? This would be all I need. If the file on my computer has been changed since my last backup, then yes, I do want it replaced usually.

Ideally what solves all my problems is: if the file is newer AND it's the same size, DO overwrite. If the file is older and the same size DO NOT overwrite. If the file is newer AND it's NOT the same size DO NOT overwrite. This would work for all my cases. I cannot see this as a flag choice though?

If there is no way to use ACD's date uploaded from it's website/app.... then maybe there's a way to check ACTUAL filesize? if there's no way to use actual-filesize, nor any way to use ACD uploaded date, I guess I should start using checksum? even though that would be very slow it would detect changes in completed torrents from partial ones. That would kind of suck though since either size or date information would work, if it were able to be used. Here's an imgur of what I mean by "actual" filesize. http://imgur.com/HBw9LYZ

P.P.P.S. -u, --update
sounds like it does what I want! --update --ignore-size I think will do everything I want 100%! Wow, how'd I never know about --update before! Let me go test that theory before I close the issue.

P.P.P.P.S. Okay, --update does do the uploads I want. However it seems that --update will always ignore size! because it didn't mention the sizes being identical, and it did the upload anyways. So then, this is still an issue, there seems to be no way to do a --update command that only updates if your source file is newer AND filesizes are different. I wouldn't want to use this I'd probably prefer --update --ignore-size which is the default behavior but someone else might want to compare size in a --update command. Additionally this doesn't solve the issue of "actual" filesizes but those might be impossible for rclone to access in anyway. I know this is not very well written, but I am going to leave this issue open. Sorry if it was annoying to read. Feel free to close the issue, or even delete it. It does seem though there is room to upgrade --update. Let me know if you want my -vv's but there's no errors in them, nothing interesting. I'd also prefer not to post them here for privacy reasons, but I would be willing to email them to you if you are interested to see them.

P.P.P.P.P.S. It might also be nice to make it possible to use --update and --checksum at the same time, only waste time doing checksum's on files that are newer, this would be useful because currently --update doesn't check size at all (although allowing --update to check size might be the easier fix).

**Comment by Cr0nixx** [comment]
Not a fix, but maybe you shouldn't upload incomplete torrents that are still downloading or not finished?

**Comment by left1000** [comment]
This was not the case for my testing files, but the scenario this happens for in the wild is torrents that are unpopular/discontinued/notwellseeded meaning it might take weeks or months or even never finish. This has also been a concern of mine for a long time, but you're right, just manually checking such details would also have solved the problem, that's what I always tried to do, but I made mistakes very rarely.

--update flat out just solves the problem though, because when the torrent finishes it'll be a newer file on my harddrive than my last backup and it'll upload it. The only reason I didn't close my own issue is that --update does not work as stated in the documentation, in that --update does not check size (maybe it's not supposed to but documentation says it does).

**Comment by ncw** [comment]
> --update flat out just solves the problem though, because when the torrent finishes it'll be a newer file on my harddrive than my last backup and it'll upload it. The only reason I didn't close my own issue is that --update does not work as stated in the documentation, in that --update does not check size (maybe it's not supposed to but documentation says it does).

Glad update solves the problem.

I just had a look at the source, and update does work exactly as the docs state

> -u, --update
> 
> This forces rclone to skip any files which exist on the destination
> and have a modified time that is newer than the source file.
> 
> If an existing destination file has a modification time equal (within
> the computed modify window precision) to the source file’s, it will be
> updated if the sizes are different.

So the size is only checked *if* the times are *equal*.

I was following rsync when I wrote that flag, and here is what rsync's man page states

> -u, --update
>
> This forces rsync to skip any files which exist on the
> destination and have a modified time that is newer than the
> source file.  (If an existing destination file has a
> modification time equal to the source file’s, it will be
> updated if the sizes are different.)


As for the original problem I would probably try to solve the problem
a different way, having an incoming directory and move the things out
of the incoming directory when satisfied.  You can use
`--track-renames` to make sure the move means it doesn't need to be
uploaded again.

**Comment by left1000** [comment]
Ahh, my bad.

**Comment by animosity22** [comment]
This was answered and ACD is dead.
