### ISSUE TITLE
[Feature request]  --fuse-pass

### ISSUE THREAD

**Issue by ajkis** [rclone/rclone#1171]
With implementation of buffer-size the the data is being passed to fuse when first 4K is received. 
We could use the flag --fuse-pass XX so we set how much buffer must be filled before its passed to fuse. 

eg `--buffer-size 500M --fuse-pass 200M `

With that we could avoid a lot of initial streaming problems where video with start only to be stopped/buffering soon after. ( Plex for example have difficulties recovering from that )

**Comment by gordan-bobic** [comment]
Do you really need this to cure that problem? I find that adding --max-read-ahead=32M to my rclone parameters made the problem go away.

**Comment by ajkis** [comment]
So you recompiled your fuse to support 32M and not 128K that is hardcoded ?

**Comment by gordan-bobic** [comment]
No, I haven't, but the problem does go away for me when I bump up max-read-ahead.

**Comment by ajkis** [comment]
For me its same with max-readahead or without same performance if i use it or not. 
But then again its ACD unreliability that is the main problem here as sometimes the file will start downloading with 400Mbit and 5 minutes later the same file may start with 400KB ( and pickup later on)

**Comment by gordan-bobic** [comment]
I suspect that has much more to do with ACD's throttling requests (per minute/hour) than actual reliability.

**Comment by ajkis** [comment]
Iam not so sure about that, could be also in play but iam preforming daily tests with copy 1GB files from my unionfs/acdcrypt mount to local disk.
All files are random generated 1GB copies eg 1G.file1, file2, file3 ( so I avoid buffering ) 
![alt text](https://puu.sh/ugc2v/0bcc01990e.png "ACD speed test")

Basically in same time span i run a copy on 3 different 1G files and measure transfer speed. 
And the results pretty random.

**Comment by ajkis** [comment]
Here couple of minutes later and I added in test last line from rclone log 
![alt text](https://puu.sh/ugd0t/12b84981ba.png"ACD speed test")

The drive was remounted and all rclone processes where killed before the test, just to make sure the buffer is cleared. 

p.s. ACD speed during those 2 tests where pretty great but usually drop drastically during night time.
( will make another test after 20:00 CET and post it here )

**Comment by ajkis** [comment]
Couple of hours later check speeds now 
![alt text](https://puu.sh/ugnwE/1da09d9edf.png "ACD speed test")

If you compare speed what clone measured and what was the actual average there is huge difference, since at the begining of copying it started really slow 600K to 1Mib and it picked up later on.

So actual average speed was 10MiB per file and rclone marked it as 77MB (that would be 587 Mib ).
If we could set the buffer to fuse pass we could make sure that in those cases there would not be any buffering since rclone would wait until X amount of buffer is filled before passing it to fuse.

**Comment by ncw** [comment]
I'll have a go at this after 1.36 is out the door.

**Comment by jrarseneau** [comment]
+1 on this too

I think even a --fuse-pass of 10M or 25M would be sufficient to make things start cleaner.

**Comment by Wob76** [comment]
This sounds like a good improvement. This with Buffer might help iron out the speed variation issues with ACD.

**Comment by b-dawg** [comment]
I would definitely be interested in testing this feature once implemented.

**Comment by ivandeex** [comment]
Closing after 4 years of inactivity
