### ISSUE TITLE
[Feature request]  --buffer-size-disk or --buffer-path=/

### ISSUE THREAD

**Issue by ajkis** [rclone/rclone#1172]
Same feature as current buffer-size that is being stored in ram while --buffer-size-disk would store it on disk. 

Since buffer-size is stored in ram its not feasible to set it to some extremely amount since you will end up out of ram eg buffer-size 25G ( to cover whole movie ) as the buffer is set per file.

It would be important to add new setting in config eg buffer-path=/path/ so we can set where buffer will be stored.

**Comment by ajkis** [comment]
Or maybe instead of making new flag --buffer-size-disk we could just have additional flag -buffer-path=/path where to store buffer/ so without it its stored in ram otherwise in defined path.

**Comment by marcelowa** [comment]
What is the use case for such a buffer?
(Assuming that a "buffer" is something that gets cleared once used)

**Comment by ajkis** [comment]
> What is the use case for such a buffer?

Most of people Plex Servers are running on fast internet connections but we all have limited amount of ram so its hard to set 10G ram per connection as few streams and your all machine is out of ram ( the cache would still be swaped on disk. however the machine would suffer due no free ram )

If we overcome this by setting buffer file to disk we can easily set 10G, for example my server will in average download 10G within first 3 to 5 minutes and that would mean the whole file is cashed on disk, the rclone can now drop connection to amazon and user can seeks up and down on the file as much as he wants without any kind of problems on plex side.

**Comment by marcelowa** [comment]
If you have a server with a fast internet connection, you probably don't need a buffer at all, as @ncw noted in the forum it should handle network glitches (not seeking, not consecutive reads etc...), a small amount of ram per file should be more then enough
I think you are confusing buffering with caching which are two different features

**Comment by ajkis** [comment]
You can have best internet in world and it wont help as ACD is throttling speed a lot and average copy can change from 500K to 50MB so with limited buffer because of memory every seeks will start to redownload ( same case with disk buffer ), so what you want to achieve is to get file down asap and be done with it.

p.s. This is optional flag so those who dont need it dont use it.

**Comment by b-dawg** [comment]
I support this feature request as well.  My current setup is a cheap VPS and my media is optimized for direct play on all devices.  I'm just now starting to play with buffer size but I'm only working with 1G of ram so it doesn't take much to use it up.  Additionally, with many people using SSD VPS the access times are just as good as using RAM.  In the meantime, could I just increase my buffer size above 1G and use swap or would that cause issues with other programs?

**Comment by darknessgp** [comment]
I see this more as a disk cache rather than a buffer... Cache it to disk, let me set cache total space to something and maybe a timeout, so things cached for 30 days get removed... This way, streaming works better, as on first access or multiple block reads, we grab the whole file to cache. Then when I stop and go back later to rewatch, I can actually resume... I'm more than willing to give up 100GB of space on my hdd for a cache like this. The idea being, I can keep tons of data in ACD, but when reading, it will act like a local disk.

**Comment by ncw** [comment]
I'm going to close this as I think the vfs buffering options have fixed this problem.
