### ISSUE TITLE
How to set Chunk Size default value in cmd ?

### ISSUE THREAD

**Issue by 54timtim** [rclone/rclone#1173]
I am a rclone v1.35 new user with win7 64bit
I used rclone to upload to google drive with 1gbp but seems to fluctuate between 700KBPS - 2MBPS
So I try to change set  ''drive-chunk-size'' to 128M 
And I used  CMD type  '' rclone --drive-chunk-size=131072k
but system show the maseage of 
 ''Use ''rclone [command] --help'' for more information about a command
Command not found''

please teach me the correct way to set drive-chunk-size 
or have anyway can change drive-chunk-size default value?

many thanks!!
![_2017_02_24_16_10_47_704](https://cloud.githubusercontent.com/assets/26002654/23300997/0c2707f6-fac3-11e6-80a5-e894923515f2.p
![_2017_02_24_16_10_22_119](https://cloud.githubusercontent.com/assets/26002654/23301009/17e6cd88-fac3-11e6-8fb8-8077aa4052d3.png)
ng)

**Comment by ncw** [comment]
This is fine, but you need to pass it every time you use it.  rclone is complaining that you didn't give it a command.

So

    rclone --drive-chunk-size=131072k copy xzy remote:subdir

will work

    rclone --drive-chunk-size=128M copy xzy remote:subdir

will also work

**Comment by 54timtim** [comment]
thanks reply!!!
but I type ''rclone --drive-chunk-size=131072k copy xzy remote:subdir''
is show the maseage of 
''Failed to create file system for "remote:subdir": didn't find section in config file''
is mean not work?
![_2017_02_24_19_31_21_578](https://cloud.githubusercontent.com/assets/26002654/23302091/308ec5e8-fac8-11e6-9492-b2d32a93aaf9.png)

**Comment by ncw** [comment]
You need to create the remote first with `rclone config`

**Comment by animosity22** [comment]
This was answered. Closing out.
