### ISSUE TITLE
Build: Local builds fail because packages import from github.com rather than local tree

### ISSUE THREAD

**Issue by eharris** [rclone/rclone#1178]
I was trying to make and test local modifications to rclone, and getting frustrated that none of my changes were being picked up.

Then I noticed that many of the imports are referencing packages via `github.com/ncw/rclone/...` rather than my local source checkout, so I deleted the local cache of `$GOPATH/src/github.com/ncw/rclone`, which caused a bunch of compilation errors since lots of parts of rclone reference that and the path didn't exist any longer.  Finally things were starting to make sense!

I went and "fixed" all those by creating symlinks under `vendor/github.com/ncw/rclone` pointing to all the packages under my source working directory (crypt, dircache, fs, oauthutil, rest, and all the storage services).  After this, it was finally able to compile properly with the changes I was making being in effect.

I'm not sure if this is the proper way to resolve the problem, but it seems wrong to have the source you are trying to build import things that should come from your local build directory from (potentially) elsewhere.  That only works if you happen to be developing in the actual `$GOPATH/src/github.com/ncw/rclone` directory, which I don't want to do because I want to easily switch between rclone being built from any of several working directories.  It's also way too easy for those directories to get stomped on by an errant `go get`.

I am putting these different checkout versions and working dirs under `$GOPATH/src/local` with names like `rclone_work` or `rclone_1.34`, which makes doing a `go clean -i local/rclone_blah; go install local/rclone_blah` easy to switch versions.

**Comment by ncw** [comment]
If you want to hack on rclone, then you need to hack on it at `$GOPATH/src/github/ncw/rclone` - just use git remote to set your origin to your own fork on github.

Then use git branches to select between the versions of code you are working on - no copies of the source tree needed.

Don't worry about go get stomping on stuff - it doesn't stomp on stuff which isn't on the master branch I don't think.

**Comment by eharris** [comment]
That adds extra steps and a lot of hassle to switching between versions, because you have to make sure everything you've changed is checked in (which I often don't want) or stashed, lookup the version you want, switch to that branch or tag, and only then be able to build and use a different version.

**Comment by eharris** [comment]
Also, `go get -u github.com/ncw/rclone` definitely stomps on work in progress (or fails) if you work in the "real" directory.  I just tried to do that with some local changes and got this error:

```
> go get -u github.com/ncw/rclone
# cd /mnt/work/go/src/github.com/ncw/rclone; git pull --ff-only
Cannot pull with rebase: You have unstaged changes.
Please commit or stash them.
package github.com/ncw/rclone: exit status 1
```

**Comment by ncw** [comment]
Working in `$GOPATH/src/github/ncw/rclone` is the go way.  You **can** do it differently, but go is opinionated about things like that so you'll be swimming against the current :-(

You can have different directories with code in, but you should be changing GOPATH when you swap between them.

I've had similar arguments with the go tooling over the years (eg with symlinks) but for an easy life I've switched to doing things the go way.

I find working with branches a lot more convenient that having lots of directories full of random changes.  The discipline of having to check stuff in (even as a WIP FIXME commit) makes you describe what you are doing and helps when you come back to it later.

If you are working on rclone, you should be using git to update it rather than go get.  I'd recommend keeping a clean master branch then doing your work in feature branches which you then rebase to master.

I hope that helps

Nick

**Comment by eharris** [comment]
So it is proper (as far as go development) to have sub-packages that live within an application refer to an effectively absolute rather than a relative location, so that they appear as though they are external to the application code even when they aren't?  That seems so strange to me.

**Comment by ncw** [comment]
> So it is proper (as far as go development) to have sub-packages/dependencies that live within an application refer to an effectively absolute rather than a relative location, so that they appear as though they are external to the application code even when they aren't? That seems so strange to me.

Yes that is the recommended way.  You can use relative imports but they are frowned upon and don't work properly in some circumstances, so people don't.

[Here is a reddit discussion](https://www.reddit.com/r/golang/comments/2588lk/relative_imports_do_or_dont/) on the topic which is interesting.

Go has a reputation for opinionated tooling and this is one of those areas.

PS install the goimports tool into your editor save hook and you will never type an import line again

**Comment by ncw** [comment]
This is fixed with go modules and vendoring now.
