### ISSUE TITLE
rclone mv and cp should behave similar to Unix's mv and cp.

### ISSUE THREAD

**Issue by AndyIbanez** [rclone/rclone#1182]
When you move or copy a directory with rclone with `rclone mv DIR_ONE DIR_TWO`, it does not copy DIR_ONE into DIR_TWO. Instead, it behaves as if I were copying the *contents* of DIR_ONE into DIR_TWO: In other words, as if I were doing `DIR_ONE/* DIR_TWO`.

I'd consider this weird behavior, since us UNIX users are used to not have this behavior. `cp DIR_ONE DIR_TWO` should copy `DIR_ONE` itself into `DIR_TWO`, and not its contents.

**Comment by ncw** [comment]
There is a reason for this...

It is because under the hood rclone move and rclone copy are just rclone sync with a few tweaks, and sync syncs two directories together.

You can also use moveto and copyto which work slightly more like mv and cp.

I do kind of agree with you, but I'm not going to change the semantics of move and copy now though - I think that ship sailed a while ago!

**Comment by AndyIbanez** [comment]
That’s understandable, and thanks for the new commands. For some reason I didn’t find those in the docs.

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=dx&cv=9.4.52&pv=10.12.3&source=email_footer_2]
On Tue, Feb 28, 2017 at 1:47 PM, Nick Craig-Wood <notifications@github.com> wrote:
There is a reason for this...

It is because under the hood rclone move and rclone copy are just rclone sync with a few tweaks, and sync syncs two directories together.

You can also use moveto and copyto which work slightly more like mv and cp.

I do kind of agree with you, but I'm not going to change the semantics of move and copy now though - I think that ship sailed a while ago!

**Comment by AndyIbanez** [comment]
Hi Nick. So I'm trying the `moveto` command and it doesn't seem to do anything?

I created a folder at the root of a crypt remote called `the_test`. Inside this one I have another one called `test_within`. I want to move `the_test` (including its subdirectory) inside a folder called `fixed`.

rclone moveto `myCryptRemote:/the_test` `myCryptRemote:/fixed/`

The command doesn't print any errors, but when I `lsd` the directory is not moved.

**Comment by AndyIbanez** [comment]
For what is worth, I ended up writing a bash script to fix my mess. If you ever make the same mistake as I (assume rclone move and copy will behave like Unix's move and copy), you can use something similar to fix it:

```
#! /bin/bash

REMOTE="acd_crypt:/"
FOLDERS_TO_MOVE=`rclone lsd "$REMOTE" | grep -v "_CCC" | cut -d" " -f22-`
TARGET="$REMOTE/"
DESTINATION="$REMOTE/Vault _CCC SafetyNet Fixed"

printf '%s\n' "$FOLDERS_TO_MOVE" | while IFS= read -r line
do
	echo "Moving folder: $line"
	COMPLETE_TARGET="$TARGET/$line"
	COMPLETE_DESTINATION="$DESTINATION/$line"
	echo "To folder: $COMPLETE_DESTINATION"
	rclone move "$COMPLETE_TARGET" "$COMPLETE_DESTINATION"
done
```

This is a dirty script but it does its job.

**Comment by ncw** [comment]
> I created a folder at the root of a crypt remote called the_test. Inside this one I have another one called test_within. I want to move the_test (including its subdirectory) inside a folder called fixed.

You want this

    rclone moveto myCryptRemote:/the_test myCryptRemote:/fixed/thetest

**Comment by unnfav** [comment]
> rclone moveto myCryptRemote:/the_test myCryptRemote:/fixed/thetest

I think you meant to say
`rclone moveto myCryptRemote:/the_test myCryptRemote:/fixed/the_test`

Anyway, so, basically we need to give the name of the directory we want to move.  Correct?

**Comment by ncw** [comment]
@unnfav yes that is right, you need the full path to the file/dir in the source **and** destination
