### ISSUE TITLE
"runtime: fatal error: sweep increased allocation count" in `rclone mount`

### ISSUE THREAD

**Issue by greyltc** [rclone/rclone#1185]
I'd like to keep you all updated on a bug in go that I found while using `rclone mount` (rclone v1.35-DEV).

The command runs fine, but when I start using the mount, go/`rclone mount` crashes spectacularly (see my traces in upstream bug report).

Maybe some of you rclone devs want to chip in to help the go folks solve this bug in go1.8rc3 (and apparently also in go1.7.5):
https://github.com/golang/go/issues/19029
it seems like they need help in finding the source of an rclone structure they see in the memory dump, "five []byte all taken from the same underlying array." Can anyone help them with that?

**Comment by ncw** [comment]
I'll take a look and see if I can help - thanks for the heads up!

**Comment by greyltc** [comment]
@ncw, can you recreate this bug by following [my instructions](https://github.com/golang/go/issues/19029#issuecomment-286256385)?

**Comment by animosity22** [comment]
This looks like a frozen bug in GO so not sure there is much left to do for this one. If this is still something that needs work, let me know and we can capture the right information for it.

Thanks!
