### ISSUE TITLE
[BUG] latest beta -v --log its not showing files, something is off 

### ISSUE THREAD

**Issue by ajkis** [rclone/rclone#1187]
this is all i see in mount log file now 
2017/02/28 17:41:44 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:           21
Elapsed time:       54.2s

**Comment by ncw** [comment]
If you want debug, you'll need -vv now.  -v only shows files transferred.

**Comment by ajkis** [comment]
Yea I wanted just files not  debugging, not sure what vent wrong but when i remounted the files start showing in log. Btw chance to disable empty INFO requests, the --stats refresh should show only when there was actually something eg not keep repeating same INFO when there are no changes beside, elapsed time

> 2017/02/28 17:58:10 INFO  : 
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:           16
> Elapsed time:     7m21.2s
> 
> 2017/02/28 17:58:20 INFO  : 
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:           16
> Elapsed time:     7m31.2s
> 
> 2017/02/28 17:58:30 INFO  : 
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:           16
> Elapsed time:     7m41.2s
> 
> 2017/02/28 17:58:40 INFO  : 
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:           16
> Elapsed time:     7m51.2s

**Comment by ncw** [comment]
The stats coming at a regular interval is supposed to be like a heartbeat for rclone so you know it is still alive.
