### ISSUE TITLE
Duplicate files on drive confusing rclone - warn the user better

### ISSUE THREAD

**Issue by richardxday** [rclone/rclone#119]
Hi,

Using rclone V1.19, sync doesn't seem to work properly with Google Drive, repeated calls to sync transfer data:

$ rclone -V
rclone v1.19
$ rclone sync drive: ~/Drive/
2015/09/04 10:36:04 Local file system at /home/richard/Drive: Building file list
2015/09/04 10:36:04 Local file system at /home/richard/Drive: Waiting for checks to finish
2015/09/04 10:36:09 Local file system at /home/richard/Drive: Waiting for transfers to finish
2015/09/04 10:36:10 Waiting for deletions to finish

Transferred:      3332083 Bytes ( 579.53 kByte/s)
Errors:                 0
Checks:                52
Transferred:           64
Elapsed time:  5.614839461s

$ rclone sync drive: ~/Drive/
2015/09/04 10:36:23 Local file system at /home/richard/Drive: Building file list
2015/09/04 10:36:23 Local file system at /home/richard/Drive: Waiting for checks to finish
2015/09/04 10:36:27 Local file system at /home/richard/Drive: Waiting for transfers to finish
2015/09/04 10:36:28 Waiting for deletions to finish

Transferred:      3332083 Bytes ( 613.45 kByte/s)
Errors:                 0
Checks:                52
Transferred:           64
Elapsed time:  5.304448046s

It's my assumption that after a sync (and nothing changing on the drive) sync shouldn't need to transfer all the data again.

Even if this isn't true, when using -v I get random sets of 'Sizes differ', 'Md5sums differ', 'Modification times differ by ...' and lots of 'Copied (updating existing)' and often 'Copied (new)'.

I'm running on Ubuntu 15.04 64-bit.

One thing I've just noted is that lots of the filenames on Google Drive have ':' in them.  Could that cause an issue?

Help!

Thanks,
Richard.

**Comment by ncw** [comment]
That's odd! I wonder if you've got two files with the same name on Drive? Can you post a log with -v? There is a duplicate file warning you might want to watch out for. 

I don't think : in the files should cause any particular problems.

**Comment by richardxday** [comment]
Hi Nick,

I'm just transferring lots of stuff to my Google Drive so I'll retest and
post later on.

Thanks,
Richard

**Comment by richardxday** [comment]
This is the output from 2nd and subsequent executions of the following command on a fresh machine:
$ rclone -v sync "drive:My Tracks Backup" "Drive/My Tracks Backup"

2015/09/04 18:40:34 Local file system at Drive/My Tracks Backup: Modify window is 1ms
2015/09/04 18:40:34 Local file system at Drive/My Tracks Backup: Building file list
2015/09/04 18:40:34 Local file system at Drive/My Tracks Backup: Waiting for checks to finish
2015/09/04 18:40:34 2014-06-22 10:08 Walk To Burnley .kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-06-22 10:08 Walk To Burnley .kmz: Unchanged skipping
2015/09/04 18:40:34 2014-09-14 12:14 Walk With Gail, Jake and Inca.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-09-14 12:14 Walk With Gail, Jake and Inca.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-08-30 12:12 Walk Back From The Beach.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-08-30 12:12 Walk Back From The Beach.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-08-24 15:19 Walk Ariund Hurstwood Reservoir.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-08-24 15:19 Walk Ariund Hurstwood Reservoir.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-08-24 10:26 Cycling With Jake And Gail.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-08-24 10:26 Cycling With Jake And Gail.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-08-23 10:55 Walking And Driving.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-08-23 10:55 Walking And Driving.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-09-13 16:36 Walk With Inca.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-09-13 16:36 Walk With Inca.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-09-07 12:18 Bike With Gail.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-09-07 12:18 Bike With Gail.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-08-02 09:25 Boat Trip.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-08-02 09:25 Boat Trip.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-03-24 Drive To Work From Jo's.kmz: Sizes differ
2015/09/04 18:40:34 2014-03-20 Drive Home Via Tesco.kmz: Sizes differ
2015/09/04 18:40:34 2014-03-21 Drive Home To School Via Fuel.kmz: Sizes differ
2015/09/04 18:40:34 2014-09-07 13:40 Walk To Asda.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-09-07 13:40 Walk To Asda.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-09-02 13:22 Short Walk.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-09-02 13:22 Short Walk.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-03-14 Drive To Work.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-03-14 Drive To Work.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-03-24 Drive Home From Work.kmz: Sizes differ
2015/09/04 18:40:34 2014-03-19 Drive To Work From School.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-03-19 Drive To Work From School.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-03-25 Drive To Work.kmz: Sizes differ
2015/09/04 18:40:34 2014-08-31 12:01 Walk Back From The Weir.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-08-31 12:01 Walk Back From The Weir.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-09-20 12:09 Walk To Pick Up My Car.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-05-17 12:17 Coldwell Reservoir.kmz: Sizes differ
2015/09/04 18:40:34 2014-03-19 Drive Home From Work Via Tesco's.kmz: Sizes differ
2015/09/04 18:40:34 2014-03-17 Drive Home From Work.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-03-08 09:02 Walk Back From Garage.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-03-08 09:02 Walk Back From Garage.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-06-22 10:08 Walk To Burnley.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-06-22 10:08 Walk To Burnley.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-04-13 07:53 Biking With Gail.kmz: Sizes differ
2015/09/04 18:40:34 2014-03-14 Drive Home From Work.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-03-14 Drive Home From Work.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-03-17 Drive Home From Work.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-03-21 Drive To Work.kmz: Sizes differ
2015/09/04 18:40:34 2014-09-20 12:09 Walk To Pick Up My Car.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-05-07 08:10 Walk From Ford Garage.kmz: Sizes differ
2015/09/04 18:40:34 2014-08-31 10:59 Walk To The Weir.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-08-31 10:59 Walk To The Weir.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-01-05 Crowwood Farm.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-03-13 Drive Home.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-03-13 Drive Home.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-04-10 12:22 Walk To Meet Gail.kmz: Sizes differ
2015/09/04 18:40:34 2014-02-26 14:49 Cycling With Gail.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-02-26 14:49 Cycling With Gail.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-01-05 Crowwood Farm.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-03-18 Drive Home To School.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-03-17 Drive To Work From School.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-03-17 Drive To Work From School.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-06-26 19:57 Bike Ride.kmz: Modification times differ by -883h18m26.286s: 2014-08-02 15:56:50.502 +0000 UTC, 2014-06-26 21:38:24.216 +0100 BST
2015/09/04 18:40:34 2014-02-16 10:55.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-03-18 Drive Home To School.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-03-20 Drive To Work.kmz: Sizes differ
2015/09/04 18:40:34 2013-12-26 Short Ride.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-02-16 10:55.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-05-25 16:18 Walk In Lowther Estate.kmz: Sizes differ
2015/09/04 18:40:34 2013-12-26 Short Ride.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-02-13 MediaCityUK.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-03-13 Drive To Work.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-03-13 Drive To Work.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-02-13 MediaCityUK.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-07-20 10:55 Walking.kmz: Modification times differ by -306h6m58.393s: 2014-08-02 15:55:20.019 +0000 UTC, 2014-07-20 22:48:21.626 +0100 BST
2015/09/04 18:40:34 2014-07-03 19:04 Ride To Barrowford Locks.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-07-03 19:04 Ride To Barrowford Locks.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-03-18 Drive To Work.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-03-18 Drive To Work.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-02-26 08:13 Walk From Briercliffe.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-02-26 08:13 Walk From Briercliffe.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-02-13 Cycling.kmz: Size and modification time the same (differ by 0, within tolerance 1ms)
2015/09/04 18:40:34 2014-02-13 Cycling.kmz: Unchanged skipping
2015/09/04 18:40:34 2014-03-25 22:46.kmz: Sizes differ
2015/09/04 18:40:34 2014-07-20 10:55 Walking.kmz: Md5sums differ
2015/09/04 18:40:34 2014-06-26 19:57 Bike Ride.kmz: Md5sums differ
2015/09/04 18:40:35 2014-03-24 Drive Home From Work.kmz: Copied (updated existing)
2015/09/04 18:40:35 2014-03-21 Drive Home To School Via Fuel.kmz: Copied (updated existing)
2015/09/04 18:40:35 2014-03-24 Drive To Work From Jo's.kmz: Copied (updated existing)
2015/09/04 18:40:35 2014-03-20 Drive Home Via Tesco.kmz: Copied (updated existing)
2015/09/04 18:40:35 2014-03-25 Drive To Work.kmz: Copied (updated existing)
2015/09/04 18:40:35 2014-05-17 12:17 Coldwell Reservoir.kmz: Copied (updated existing)
2015/09/04 18:40:35 2014-03-19 Drive Home From Work Via Tesco's.kmz: Copied (updated existing)
2015/09/04 18:40:35 2014-04-13 07:53 Biking With Gail.kmz: Copied (updated existing)
2015/09/04 18:40:35 2014-05-07 08:10 Walk From Ford Garage.kmz: Copied (updated existing)
2015/09/04 18:40:35 2014-03-21 Drive To Work.kmz: Copied (updated existing)
2015/09/04 18:40:35 2014-04-10 12:22 Walk To Meet Gail.kmz: Copied (updated existing)
2015/09/04 18:40:36 2014-07-20 10:55 Walking.kmz: Copied (new)
2015/09/04 18:40:36 2014-05-25 16:18 Walk In Lowther Estate.kmz: Copied (updated existing)
2015/09/04 18:40:36 2014-03-20 Drive To Work.kmz: Copied (updated existing)
2015/09/04 18:40:36 2014-03-25 22:46.kmz: Copied (updated existing)
2015/09/04 18:40:36 2014-07-20 10:55 Walking.kmz: Copied (updated existing)
2015/09/04 18:40:36 2014-07-03 19:04 Ride To Barrowford Locks.kmz: Copied (new)
2015/09/04 18:40:36 2014-06-26 19:57 Bike Ride.kmz: Copied (new)
2015/09/04 18:40:36 2014-05-25 16:18 Walk In Lowther Estate.kmz: Copied (new)
2015/09/04 18:40:36 2014-06-26 19:57 Bike Ride.kmz: Copied (updated existing)
2015/09/04 18:40:36 2014-05-17 12:17 Coldwell Reservoir.kmz: Copied (new)
2015/09/04 18:40:37 2014-05-07 08:10 Walk From Ford Garage.kmz: Copied (new)
2015/09/04 18:40:37 2014-04-13 07:53 Biking With Gail.kmz: Copied (new)
2015/09/04 18:40:37 2014-03-25 22:46.kmz: Copied (new)
2015/09/04 18:40:37 2014-04-10 12:22 Walk To Meet Gail.kmz: Copied (new)
2015/09/04 18:40:37 2014-03-24 Drive Home From Work.kmz: Copied (new)
2015/09/04 18:40:37 2014-03-25 Drive To Work.kmz: Copied (new)
2015/09/04 18:40:37 2014-03-24 Drive To Work From Jo's.kmz: Copied (new)
2015/09/04 18:40:37 2014-03-21 Drive Home To School Via Fuel.kmz: Copied (new)
2015/09/04 18:40:37 2014-03-21 Drive To Work.kmz: Copied (new)
2015/09/04 18:40:37 2014-03-20 Drive To Work.kmz: Copied (new)
2015/09/04 18:40:37 2014-03-20 Drive Home Via Tesco.kmz: Copied (new)
2015/09/04 18:40:38 2014-03-19 Drive Home From Work Via Tesco's.kmz: Copied (new)
2015/09/04 18:40:38 2014-03-19 Drive To Work From School.kmz: Copied (new)
2015/09/04 18:40:38 2014-03-18 Drive To Work.kmz: Copied (new)
2015/09/04 18:40:38 2014-03-18 Drive Home To School.kmz: Copied (new)
2015/09/04 18:40:38 2014-03-17 Drive Home From Work.kmz: Copied (new)
2015/09/04 18:40:38 2014-03-17 Drive To Work From School.kmz: Copied (new)
2015/09/04 18:40:38 2014-03-14 Drive Home From Work.kmz: Copied (new)
2015/09/04 18:40:38 2014-03-14 Drive To Work.kmz: Copied (new)
2015/09/04 18:40:38 Local file system at Drive/My Tracks Backup: Waiting for transfers to finish
2015/09/04 18:40:38 2014-02-26 14:49 Cycling With Gail.kmz: Copied (new)
2015/09/04 18:40:38 2014-03-13 Drive To Work.kmz: Copied (new)
2015/09/04 18:40:38 2014-03-08 09:02 Walk Back From Garage.kmz: Copied (new)
2015/09/04 18:40:39 2014-02-13 Cycling.kmz: Copied (new)
2015/09/04 18:40:39 2014-02-16 10:55.kmz: Copied (new)
2015/09/04 18:40:39 2014-02-13 MediaCityUK.kmz: Copied (new)
2015/09/04 18:40:39 2014-02-26 08:13 Walk From Briercliffe.kmz: Copied (new)
2015/09/04 18:40:39 2014-03-13 Drive Home.kmz: Copied (new)
2015/09/04 18:40:39 Waiting for deletions to finish

Transferred:      2467074 Bytes ( 385.04 kByte/s)
Errors:                 0
Checks:                49
Transferred:           48
Elapsed time:  6.257154819s

2015/09/04 18:40:39 Go routines at exit 49

**Comment by ncw** [comment]
According to some quick analysis (which could be wrong) you have these files as duplicates on drive.  Duplicate files (files with the same file name) can't exist on the local filesystem but they can on Drive.  These confuse rclone no end as it syncs one, then the other each time.

Can you check in the drive web interface to see if they really are duplicated?

Posting the results of `rclone ls "drive:My Tracks Backup"` would be very interesting too!

Thanks

```
      2 2014-02-13 Cycling.kmz
      2 2014-02-13 MediaCityUK.kmz
      2 2014-02-16 10:55.kmz
      2 2014-02-26 08:13 Walk From Briercliffe.kmz
      2 2014-02-26 14:49 Cycling With Gail.kmz
      2 2014-03-08 09:02 Walk Back From Garage.kmz
      2 2014-03-13 Drive Home.kmz
      2 2014-03-13 Drive To Work.kmz
      2 2014-03-14 Drive Home From Work.kmz
      2 2014-03-14 Drive To Work.kmz
      2 2014-03-17 Drive Home From Work.kmz
      2 2014-03-17 Drive To Work From School.kmz
      2 2014-03-18 Drive Home To School.kmz
      2 2014-03-18 Drive To Work.kmz
      2 2014-03-19 Drive Home From Work Via Tesco's.kmz
      2 2014-03-19 Drive To Work From School.kmz
      2 2014-03-20 Drive Home Via Tesco.kmz
      2 2014-03-20 Drive To Work.kmz
      2 2014-03-21 Drive Home To School Via Fuel.kmz
      2 2014-03-21 Drive To Work.kmz
      2 2014-03-24 Drive Home From Work.kmz
      2 2014-03-24 Drive To Work From Jo's.kmz
      2 2014-03-25 22:46.kmz
      2 2014-03-25 Drive To Work.kmz
      2 2014-04-10 12:22 Walk To Meet Gail.kmz
      2 2014-04-13 07:53 Biking With Gail.kmz
      2 2014-05-07 08:10 Walk From Ford Garage.kmz
      2 2014-05-17 12:17 Coldwell Reservoir.kmz
      2 2014-05-25 16:18 Walk In Lowther Estate.kmz
      2 2014-06-26 19:57 Bike Ride.kmz
      2 2014-07-03 19:04 Ride To Barrowford Locks.kmz
      2 2014-07-20 10:55 Walking.kmz
```

**Comment by richardxday** [comment]
Indeed, you are right!

There are duplicated files and so I can see how this confuses rclone.

Is there a plan for handling duplicates on Google Drive?  In fact, even
detecting duplicates and offering the ability to delete all but one of the
duplications would be very helpful - I have lots of duplicates in my Google
Photos and now that they are visible from the drive interface I could sort
them out.

I think this issue can be closed now.

Thanks!
Richard.

**Comment by ncw** [comment]
Duplicated files on drive is a common theme - one which I really need to sort out properly.

If you had used Drive as the destination you would have got a warning about duplicate files- I think I need to put the same warning in for Drive as the source.

I'll re-purpose this ticket to make that happen.

**Comment by c240amg** [comment]
Yup I am getting that issue too - very weird that Google Drive allows duplicate files e.g. COMMIT_MSG and doesn't give an error. They have different contents and checksums.

**Comment by willpolley** [comment]
This would help me as well. It would be nice if rclone would delete the dupes and reupload the file.

**Comment by russwilde** [comment]
I'd like some kind of options for handling duplicates, too; I'm using rclone to backup my Google Drive (and the Google Photos folder) to S3 storage and I'm getting errors created by photos that have duplicate names.

I want to keep all the files, but would be happy for them to be renamed so that all the duplicates could be backed up.

**Comment by ncw** [comment]
@russwilde try [rclone dedupe](http://rclone.org/commands/rclone_dedupe/) that will help!

**Comment by russwilde** [comment]
@ncw Thanks; that does look very helpful. I'll give it a go.

**Comment by animosity22** [comment]
This looks solved so closing out.
