### ISSUE TITLE
[Feature request] mount -write-buffer 

### ISSUE THREAD

**Issue by ajkis** [rclone/rclone#1191]
Writing large files directly on the mount is pretty tricky due OS demands eg its really risky compared to using copy/move  that will make sure that files are uploaded successfully.

Maybe we could make a new flag --write-buffer /path to folder/ where rclone would store file that were copyied in mount and then from there move files to mount same way as rclone move does. 
It would be important that rclone shows files even when they are still in buffer.
Something like that can be now achieved with unionfs and scripting but unionfs have its own limitations.

**Comment by ncw** [comment]
Yes this is a good idea.  I think it is probably covered in #711 though.

**Comment by animosity22** [comment]
This was solved via the above issue.
