### ISSUE TITLE
Is it possible to omit the need of specifying path?

### ISSUE THREAD

**Issue by cnbuff410** [rclone/rclone#12]
What I meant is, currently if I want to sync a folder, I would do 

rclone sync source:path dest:path

But the most convenient way would be I simply go to that folder and do 

rclone sync

Because remote path is always hard to remember for storage service like GCS. Is it possible? I imagine having some kind of mapping metadata saved in config file would do it.

**Comment by animosity22** [comment]
This looks to be covered these days with the use of the alias backend.
