### ISSUE TITLE
Keep track of permissions... 

### ISSUE THREAD

**Issue by doonze** [rclone/rclone#1202]
So, what about a way to save permissions for us linux users? Currently, if we backup our system information to the cloud (like acd) all permissions are lost due to the clouds not understanding permissions. If there is a cloud that keep them I don't know what it is! 

Anyway, since rclone can of course read the privileges, any way to store them in a hidden file? (or any file, you get the idea) then if you copy back from the remote, rclone can then rewrite the files/dir back to disk with the correct privileges? In theory seems possible, but my attempt to read your GO code Nick has shown me my GO fu is really lacking. 

I know that's a HUGE request, but maybe someone out there with strong GO FU would be interested?

**Comment by calisro** [comment]
Just a side-bar in the meantime.  you can do this then back that file up.  

getfacl -R / >permissions.facl

setfacl --restore=permissions.facl

**Comment by ncw** [comment]
I think this may happen at some point, but it will involve quite a lot of metadata plumbing...

@calisro nice work-around

**Comment by doonze** [comment]
calisro.... are you saying "getfacl -R / >permissions.facl" would save ALL permissions? in entire root? then you can just rum serfacl to recreate them???? I'll google it, learn something every day with Linux, but if that's the case, then the answer is in really right there. 

However, when I google it --restore isn't an option?

**Comment by calisro** [comment]
Setfacl --restore should be there.  Check the man page

**Comment by doonze** [comment]
Yeah, I found one, the first one didn't show it, and --help didn't either. But I got in now, thanks!

**Comment by doonze** [comment]
@ncw so Nick, a solution could be to have a flag that runs Setfacl on each dir, save the backup to the directory before shipping it off to the could, then if you rclone back with the flag, it will run the restore after the dir has been redownloaded?? At least for Nix systems.....

**Comment by doonze** [comment]
Ok, for now, what I've done is my rsync scripts now run setfacl on the backup after it's done, then puts the permissions file in the root of the backup. (This is so I can take advantage of rsync excludes) Then I'll rclone it all to acd. 

For my non-rsync stuff I send to acd, I'll have my scripts run a setfacl BEFORE rclone runs, on the same paths as the rclone, then upload that to acd. 

now to figure out how to preserve links. The idea is to be able to get an exact image that can be restored and just work... hmmm... maybe I'll look into tar... I think it preserves links. That's for later.

**Comment by doonze** [comment]
update:

So to keep my permissions (and soft/hard links) in place, I've not written a scripts that rsyncs my server and mysql database in backups each day with a -del , and creates a --backup-dir with any changes/deletions throughout the week, in dated directories. (So one for each day)

I then once a week (different day for each server) tarball the latest backup, and rclone it off to acd. Then once a week I tarball up all changes and send them off to acd. So in effect I have full system backups, with all changes, local. And a weekly snapshot with all changes in the cloud. Preserving all permissions and links. Then it cleans up the changes dir every 7 days, removing LAST weeks changes that were already sent to acd. (So right before rclone moves the changes each week, there are 14 days worth, it deletes the 7 oldest and makes a tarball of the 7 left then rclones it to acd.) 

I do this weekly just to save bandwidth, I have a monthly cap. So the tar solution is a win/win, as it makes it about 1/4 the size or smaller on top of preserving permissions and links.

Here's the script if anyone cares: [](https://github.com/doonze/cloud-backup-script)

@ncw having rlone tarball something before sending it to the cloud, then having it untar when bringing it back from the cloud is one way rclone could handle preserving permissions in the cloud. Just an idea.

**Comment by dnessl** [comment]
FYI, pcloud already supports POSIX ACLs natively somehow:  If you use their proprietary FUSE filesystem daemon, any file you copy into it (cp -p) also automatically saves the original Unix username+groupname+permissions that you can then see as a POSIX ACL for that file.  In other words, if you issue the command getfacl to a file in their FUSE filesystem, it shows the original user+group+permissions, e.g. 

**drn@linux4:~/pCloudDrive>** ls -l testprog
*-rw-r--r--+ 1 drn users 35472 Aug 20 12:58 testprog*
**drn@linux4:~/pCloudDrive>** getfacl testprog 
*# file: testprog*
*# owner: drn*
*# group: users*
*user::rwx*
*group::r-x*
*other::r-x*

Then if you copy (cp -p) that file out of their FUSE filesystem into a local storage filesystem, the original permissions are restored.   You can even use the setfacl command to modify permissions of files in pcloud!

Which means that pcloud has a way to store original user+group+permissions as metadata.  Looking at pcloud's APIs, I don't immediately see where they store it in pcloud's metadata.  (I wonder if for each file they create fake pcloud-shares for each POSIX "user", "group", and "other" permission-set, and then map the read-write-execute bits to equivalent booleans in the pcloud-share.)  For compatibility with pcloud's existing functionality, I suggest asking pcloud how their FUSE fs saves Unix permissions as pcloud metadata; or I suppose someone could reverse engineer it by saving an executable file via pcloud's FUSE fs and then using the API to inspect that file's associated metedata and shares.  

**Request:**  Add code to rclone sync/copy/etc to automatically take advantage of this capability in pcloud (and in any other storage service that supports it).

**Comment by benpye** [comment]
@ncw I'd be happy to look at doing this, have you any suggestions on where to get started? Would the suggested approach of saving some extra .permissions.facl file be sufficient? It's perhaps a bit trickier as you might sync a specific directory to a remote and then another different one, we would need to merge these facl files.

**Comment by ncw** [comment]
@benpye wrote:
>  I'd be happy to look at doing this, have you any suggestions on where to get started? Would the suggested approach of saving some extra .permissions.facl file be sufficient? It's perhaps a bit trickier as you might sync a specific directory to a remote and then another different one, we would need to merge these facl files.

Quite a lot of the backends don't support user settable metadata, so if we want permissions to work with all remotes than storing them as separate files is the only solution.

Perhaps what we need is a metadata overlay remote which stores a metadata file for every file (rather like the apple double format) or maybe every directory.

There are other things extra metadata could be used for - storing hashes, controlling the chunking or compression of files, etc.

Some backends (eg sftp and possibly ftp) do support permissions to a limited extent.

**Comment by archon810** [comment]
Any updates on getting this resolved? We now have symlinks with `-l` thanks to https://github.com/rclone/rclone/issues/1152, but no acl, and that's a big bummer. Perhaps a solution similar to .rclonelink, but for acl?

**Comment by ndeubert** [comment]
I just thought I would post this here in case anyone else stumbles on this thread like I did when looking for a cloud service that keeps track of permissions... pCloud does not preserve permissions according to their customer support. No mention of FUSE though.

**Comment by LorenzoBettini** [comment]
@ndeubert Indeed I just tried that and pCloud does not preserve execution bits.
@dnessl I tried what you suggested but it only works on the very same computer and I guess that works only because of pCloud caching. If you copy something with an execution bit from computer A into pCloud and then retrieve it in computer B the execution bit was lost...
the same happens with local folder synchronization...

**Comment by ltGuillaume** [comment]
When looking at this, it seems that this also won't work for local syncs/backups. It would be really nice to see this working at least when RClone is used in that way...

**Comment by dirkpetersen** [comment]
@ncw regarding local/posix  only copies: You mentioned that syncing permissions is on your longer term roadmap. Since this is a bit lift how about starting with the execute bit? if a directory tree of software scripts and data is copied and gets a new owner and somewhat different permissions it often still stays functional but if the execute bit is not copied things simply break.

**Comment by ivandeex** [comment]
from https://github.com/rclone/rclone/issues/715

> Let's say if we sync to Google Drive or Amazon Drive, is it possible to retain file/directory ownership and permissions?

**Comment by brechtm** [comment]
For what it's worth, a simple way to implement this would be to tar or zip individual files as these store permissions. This would only work for files and this would break checksums. The latter isn't an issue when using the crypt remote though.

**Comment by cjreyn** [comment]
+1 for this functionality

**Comment by fbhradec** [comment]
+1 too! 
I just had problems with permissions after replacing rsync by rclone to sync up 2 storages in linux systems (over sftp). Things stopped working after that since nothing could write to the synced storage because all permissions where set to root, since I used to run rsync as root to actually be able to preserve permissions from all the users!!

For now, my solution is to run rsync right after rclone, so rsync can fix the messed up permissions!! Not a great solution since there's a small window during the rclone transferring where the completed files stay with wrong permissions until all rclone transfers finish and rsync runs! At least rsync runs kinda fast since there's nothing to transfer. (As long as no-one updates/creates a file between rclone finishing and rsync starting up!)

I was completed baffled to not find ANY information on the rclone website about rclone not dealing with permissions. 
There should be a big warning on the website to inform people who rely on permissions about it. 

Even if I search the website for "permissions" the only 2 entries that come back is "rclone mount" and "Amazon S3 Storage Providers - Rclone", which are not very clear about the problem. 

I was only able to confirm this after finding this issue here at github. 

The slogan  ("rsync for cloud storage") is very misleading as well, since it denotes the same default behavior as rsync if running on 2 posix `sftp` environments. 

my 2 cents...

**Comment by ltGuillaume** [comment]
I totally agree. I think handling permissions should be a priority, but as long as it's not, users should be clearly warned about RClone's lack of this feature in the documentation.

**Comment by fbhradec** [comment]
Just as a side note, rclone doesn't have any support for creating symbolic links on targets that support it. It either ignore it completely, or follow it, essentially doubling the amount of data in symlinked folders at the target. 

I understand the reason rclone does that, since there's no guarantee the backend will have support for symlinks, but in the case of a posix backend like sftp, it should support it. Just copy the symlink instead of just ignoring it, or at least add an option so we can request for the symlink to be created when available. 

I think with those 2 features implemented (permissions and proper symlink), rclone can definitely replace rsync on posix only environments.

**Comment by brechtm** [comment]
> Just as a side note, rclone doesn't have any support for creating symbolic links on targets that support it. It either ignore it completely, or follow it, essentially doubling the amount of data in symlinked folders at the target.

While rclone doesn't support creating actual symlinks on the remote, there is the `--links` flag that you can use for backup up symlinks.

**Comment by kpiq** [comment]
> +1 too! I just had problems with permissions after replacing rsync by rclone to sync up 2 storages in linux systems (over sftp). Things stopped working after that since nothing could write to the synced storage because all permissions where set to root, since I used to run rsync as root to actually be able to preserve permissions from all the users!!
> 
> For now, my solution is to run rsync right after rclone, so rsync can fix the messed up permissions!! Not a great solution since there's a small window during the rclone transferring where the completed files stay with wrong permissions until all rclone transfers finish and rsync runs! At least rsync runs kinda fast since there's nothing to transfer. (As long as no-one updates/creates a file between rclone finishing and rsync starting up!)
> 
> I was completed baffled to not find ANY information on the rclone website about rclone not dealing with permissions. There should be a big warning on the website to inform people who rely on permissions about it.
> 
> Even if I search the website for "permissions" the only 2 entries that come back is "rclone mount" and "Amazon S3 Storage Providers - Rclone", which are not very clear about the problem.
> 
> I was only able to confirm this after finding this issue here at github.
> 
> The slogan ("rsync for cloud storage") is very misleading as well, since it denotes the same default behavior as rsync if running on 2 posix `sftp` environments.
> 
> my 2 cents...

Agreed.  I migrated my Google Drive connection on Ubuntu from ocamlfuse to rclone, then moved my data to OneDrive using rclone.  I thought that using the --uid, --gid, and --umask mount options would take care of my file/directory ownership and permissions.  

Unfortunately these are ignored, and while I understand this has not been a development priority (and the lack of people raising their hand to help) the documentation should more clearly tell users the feature status of each backend.

I think rclone is an incredible piece asset and its complexity and the things it can do are mind blowing.  But using it in a production environment, where multiple users need their data individually protected by linux permissions and ACLs won't work at this time.  It can't even handle keeping a single user's metadata in line on some of the most significant cloud storage connections.   

Would love to see all linux metadata supported for cloud storage (and sftp).  Permissions, ACLs, and umask would be a starting point for OneDrive and Google Drive.

**Comment by darthShadow** [comment]
I believe this can be closed now since the metadata framework for files has been available since v1.59.0 (2022-07-09).

Directory support for metadata is being tracked in #6685 

Any backend-specific implementations can be raised as separate issues for easier tracking.
