### ISSUE TITLE
[BUG/Feature request] Rclone mount writing large files 

### ISSUE THREAD

**Issue by ajkis** [rclone/rclone#1208]
rclone v1.35-155-g10e532bβ

Since open&write was implemented i decided to test a bit more direct writing on mount and in general works quite ok, especially with smaller, medium files. 

Terminal: 
`cp: failed to close '/mnt/cloud/backup/plex/plexmediaserver-backup-2017-03-04_05-00-01.tar.gz': Input/output error`

But when I try to copy a larger file this is the error I received (the file is 13GB).
( note: i was testing couple of times not just once )

> 2017/03/05 00:25:12 DEBUG : fuse: -> [ID=0x34853] Read 131072
> 2017/03/05 00:25:12 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
> 2017/03/05 00:25:12 DEBUG : HTTP RESPONSE (req 0xc42049d700)
> 2017/03/05 00:25:12 DEBUG : Error: write tcp xx.xx.xx.xx:46086->54.194.141.175:443: write: connection reset by peer
> 2017/03/05 00:25:12 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
> 2017/03/05 00:25:12 DEBUG : backup/plex/plexmediaserver-backup-2017-03-04_05-00-01.tar.gz: Upload error detected but didn't finish upload: Put https://content-eu.drive.amazonaws.com/cdproxy/nodes/xxxx/content: write tcp 84.52.138.46:46086->54.194.141.175:443: write: connection reset by peer **("HTTP status UNKNOWN"**)
> 2017/03/05 00:25:12 DEBUG : pacer: Rate limited, sleeping for 785.931399ms (3 consecutive low level retries)
> 2017/03/05 00:25:12 DEBUG : pacer: low level retry 1/1 (error Put https://content-eu.drive.amazonaws.com/cdproxy/nodes/xxx/content: write tcp xx.xx.xx.xx:46086->54.194.141.175:443: write: connection reset by peer)

Could mount be enhanced to handle upload same way rclone copy/move would do eg never fail and keep retrying :).

p.s. There are also tons of `DEBUG : fuse: -> [ID=0x166] Getxattr error=operation not supported` that i dont remember from before.

**Comment by ajkis** [comment]
Btw i checked that file stayed partially uploaded eg i could download it with above link.

p.s. Those failed uploads should be deleted by rclone.

**Comment by ncw** [comment]
> Could mount be enhanced to handle upload same way rclone copy/move would do eg never fail and keep retrying :).

That is what is required, but it is going to take making a local copy of the file which I'll do in #711

**Comment by ncw** [comment]
This is done now :-)
