### ISSUE TITLE
Off topic but is there an easy way to convert from ENCFS to crypt for easier mount? 

### ISSUE THREAD

**Issue by jscottdouglas** [rclone/rclone#1209]
Off topic but is there an easy way to convert from ENCFS to crypt for easier mount? I started with ACDMOUNT with encfs and i have about 15TB of data on the cloud I don't want to re-download and re-upload.

How do most people process this change?

**Comment by calisro** [comment]
I see no way to do that without a redownload/upload.

**Comment by azureblaze** [comment]
This isn't even theoretically possible since you can't directly modify files in cloud storage, with the exception of proprietary stuff like google docs. Best way is to get a cheap scaleway server and decrypt then upload.

**Comment by animosity22** [comment]
This looks answered and if you still have a question, please ask in the forums and we can help out.
