### ISSUE TITLE
ACD slow transfer using mount, but normal speeds when copy

### ISSUE THREAD

**Issue by Givemeyourgits** [rclone/rclone#1215]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.35-99-g6fc114dβ

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian 64 & Ubuntu 64

> Which cloud storage system are you using? (eg Google Drive)
Amazon

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount

I'm seeing drastic changes in performance throughout the day.  At one point I'll be getting 40MiB/s and another point I'll be getting 11Kbps.  This is when using mount command with crypt.  This has been happening more and more often to the point it has become the norm.  While the performance is as low as 11kbps via mounted fuse, I can do a copy at the same exact time and get 20MiB/s and as high as 40MiB/s sustained.

When trying to stream from the fuse mount I see repeated rate limits with sleeps as high as 7 seconds.  But prior to starting, it was idle for quite a while, so I don't understand why it is being immediately rated limited especially with numbers that high.  I'm not as concerned about the rare limit if it is just a delay to start, but the problem is extremely low transfer speeds using fuse when I can start copy at the same time and get full normal speeds of 18MiB/s - 40MiB/s.

Log example:

```
2017/03/06 01:28:14 DEBUG : pacer: Rate limited, sleeping for 211.445515ms (1 consecutive low level retries)
2017/03/06 01:28:14 DEBUG : pacer: low level retry 1/10 (error <nil>)
2017/03/06 01:28:15 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      3m0.8s

2017/03/06 01:28:18 DEBUG : pacer: Rate limited, sleeping for 910.584091ms (2 consecutive low level retries)
2017/03/06 01:28:18 DEBUG : pacer: low level retry 2/10 (error <nil>)
2017/03/06 01:28:21 DEBUG : pacer: Rate limited, sleeping for 324.778273ms (3 consecutive low level retries)
2017/03/06 01:28:21 DEBUG : pacer: low level retry 3/10 (error <nil>)
2017/03/06 01:28:21 INFO  : 
Transferred:   28.484 GBytes (633.850 kBytes/s)
Errors:                 0
Checks:                 0
Transferred:          195
Elapsed time:  13h5m21.3s

2017/03/06 01:28:23 DEBUG : pacer: Rate limited, sleeping for 6.183515637s (4 consecutive low level retries)
2017/03/06 01:28:23 DEBUG : pacer: low level retry 4/10 (error <nil>)
2017/03/06 01:28:25 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     3m10.8s

2017/03/06 01:28:26 DEBUG : pacer: Rate limited, sleeping for 3.797652072s (5 consecutive low level retries)
2017/03/06 01:28:26 DEBUG : pacer: low level retry 5/10 (error <nil>)
2017/03/06 01:28:31 INFO  : 
Transferred:   28.484 GBytes (633.715 kBytes/s)
Errors:                 0
Checks:                 0
Transferred:          195
Elapsed time:  13h5m31.3s

2017/03/06 01:28:33 DEBUG : pacer: Resetting sleep to minimum 20ms on success

```

This happens so often now it is virtually un-usable.  I have two machines in different locations, one with 40MiB/s peak to ACD and the another peaks out around 23MiB/s.  Both are very reliable when doing  copy/sync, but streaming off fuse has gotten to be painful and frustrating.

**Comment by endiz** [comment]
By any chance are you using unionfs as well or is this direct off the fuse mount?

**Comment by Givemeyourgits** [comment]
No unionfs

**Comment by ncw** [comment]
What file operations are you doing via mount?  Are you doing seeking?

I've found acd performance to be very variable even with just using `rclone copy`.

**Comment by Givemeyourgits** [comment]
via mount, using plex to stream I get performance varying from 11kbps - 40MiB/s, but sub 300Kbps is becoming more and more common.  At the same time this is happening, running rclone copy I get 18-40MiB/s consistently.

**Comment by endiz** [comment]
Have you tried the latest beta and enabled caching? Maybe the amount of seeks requests for the plex transcode is rate throlling you, where rclone copy is just a single stream.

Try the --buffer-size 512M with the rclone mount command.

**Comment by Givemeyourgits** [comment]
I am using buffer 2G, the problem is it will never fill the buffer as it would take 2 days to play the movie at the rate it is downloading.  When it is working good, I get 18-40MiB/s and the buffer fills extremely fast.  But the sub 300Kbps is happening more and more often.  I know ACD varies dramatically in performance,  but rclone copy works great, never less than 10MiB/s even if a current mount plex stream is only getting 11kbps.

**Comment by seuffert** [comment]
i am having the same issue. mount bandwidth is often very slow compared to a "rclone copy" at the same time. Also, a remount solves this most of the time and mount speed is high again...

**Comment by vampywiz17** [comment]
Are you live in US and use US Amazon or leave in EU an use US amazon?

I [read this topic](https://forum.rclone.org/t/best-mount-settings-for-streaming-plex/344/281), that if the user live in EU it much better to use the  Amazon.de , it add significantly much stability and bandwith.

**Comment by seuffert** [comment]
Server in EU/DE using Amazon.de EU

**Comment by vampywiz17** [comment]
I see, Well it possible that it is a API problem...

**Comment by animosity22** [comment]
ACD is dead.
