### ISSUE TITLE
rclone logo

### ISSUE THREAD

**Issue by cg-cnu** [rclone/rclone#1251]
The current logo looks a little outdated.
Did a rough sketch of few ideas I have. 
![rclonelogo](https://cloud.githubusercontent.com/assets/2767425/24073592/9cc0c938-0c1f-11e7-8e8d-b5ff6a24396a.png)
Would love to hear your comments...

**Comment by wreckedred** [comment]
The third one in group 1 - is pretty sweet



On Sat, Mar 18, 2017 at 9:46 AM, sreenivas alapati <notifications@github.com

**Comment by ncw** [comment]
Fantastic sketches!

> The current logo looks a little outdated.

I think that is the nicest thing anyone has ever said about the logo ;-)

While I can draw and paint, I really am hopeless at graphic work so your help is much appreciated!

Here are the sketches I originally made when trying to think of logos - maybe that will give you some inspiration

![2013-07-01-200551](https://cloud.githubusercontent.com/assets/536803/24075947/12f17410-0c1e-11e7-8d05-6916c192b77d.jpg)

Of the ones you've done I like the 3rd one the best :-)

Of the current logo, I like the blue colour in the background the most.

**Comment by cg-cnu** [comment]
Thanks for the input guys!

> I think that is the nicest thing anyone has ever said about the logo ;-)

Am sorry, If it came out wrong. I didn't meant anything negative :)

I am using the colors from the previous logo. From your sketches I understood that you are looking for the text ```rclone``` in the logo and cloud icon. In the previous explorations I am playing more with the letters ```r``` and ```c```.
Based on your sketches I have come up with few more variations of the logo; If you like any of them we can explore that more. Since you like the 3rd one in the initial image, I did few more variations of it. 
![image](https://cloud.githubusercontent.com/assets/2767425/24078101/988b06e8-0c89-11e7-923f-4af40b5cb01d.png)

Right now am using a dummy font; if we finalize the layout we can explore fonts and color variations.
Let me know what you guys like better.

**Comment by ncw** [comment]
> Am sorry, If it came out wrong. I didn't meant anything negative :)

No offense taken!  You were perfectly polite :-) I was just making a joke at my own expense for designing the original logo.

> I am using the colors from the previous logo. From your sketches I understood that you are looking for the text rclone in the logo and cloud icon. In the previous explorations I am playing more with the letters r and c.

The text rclone was my original idea but I couldn't make it work. I like your ideas for the r and the C very much.

> Based on your sketches I have come up with few more variations of the logo; If you like any of them we can explore that more. Since you like the 3rd one in the initial image, I did few more variations of it.

They are fab!  I think 6 is a very clever idea with the arrows round the cloud.

I really like your concept of the rC in the cloud.  3.1 has great simplicity and is about square.  I like 3.2 and 3.3 too, but I wonder whether including the text rclone takes away from it?

Maybe you could somehow combine the cloud arrows of 6 with 3.1 ?

What do you think?

**Comment by cg-cnu** [comment]
> I like 3.2 and 3.3 too, but I wonder whether including the text rclone takes away from it?

You are right with the observation; having ``` rclone ``` next to any of the logos having ```rc``` is kinda repetitive, which kinda makes the logo less legible.

![image](https://cloud.githubusercontent.com/assets/2767425/24082180/377319b4-0ce7-11e7-9f0a-edc183045aad.png)

Here are the latest revisions... 
I feel like we are getting close :) 
Will wait for a day or two and see if I get any feedback on these at this stage.

**Comment by calisro** [comment]
I like 7 but the letters are too hard to read.  specifically the 'R'.  I'd choose 6 if 7 couldn't be made more legible. :)  Nice work.

**Comment by ncw** [comment]
Sorry for the delay in responding - been a bit hectic!

I love seeing your ideas - fantastic work :-)  I think they are all amazing!  I like the clarity of 6.  7 is a great logo - somewhat abstract but recognisable and I think 6 would work very well as a wide logo.

I thought it would be useful for you to see where the logo is used at the moment

  * [main website](http://rclone.org/) - logo and favicon
  * [github](https://github.com/ncw/rclone/) - logo
  * [forum](https://forum.rclone.org/) - logo along the top
  * [G+](https://plus.google.com/+RcloneOrg)

So some of those would suit a wide image like 6.1 very well and some would suit a squarer image like 6/7.

Though the "rclone" text in 6 will be unreadable if it is very small (eg a favicon), so maybe 7 would be a better choice for that.

**Comment by cg-cnu** [comment]
Thanks for the feedback and the inputs guys. Sorry for the delay in response. Got a little busy here...

From the feedback I got, it looks like 7 is abstract and hard to understand but having ```rclone``` next to it will make it repetitive. I personally prefer just having the cloud with arrows. So, improvised on 6 and came up with these... 

![image](https://cloud.githubusercontent.com/assets/2767425/24575717/8e62f5bc-16cb-11e7-86ee-29aec05adaf7.png)


We can use just the cloud Icon in places like favicons and executables.
And the one with text and cloud for banner images and repo.

I just started playing with the fonts. Few thoughts on the choice of fonts...
I prefer having a no caps font with all round to match the cloud icon, which forms part of the text. I have choosen fonts with different edges. I will change the edges of the arrows in the cloud based on the font edge. 

That said, I am open to any feedback on fonts or the direction we are taking :)

**Comment by calisro** [comment]
6.3 looks great.  I like 6.2 second.

**Comment by ncw** [comment]
Sorry for the delay in replying - I've been away.

I like your idea of just using the cloud icon as the favicon and the longer logo incorporating the cloud icon - nice!

Of the ones you've done - I like 6.2 as the width of the line in the cloud matches that of the font.  That said I don't really like that font - I think it looks better with thicker lines as in 6.3 or 6.4. I like the font in 6.4 - what would the cloud look like with lines that think I wonder?

Do you think the logo would look better with the letter and the cloud all the same colour?

**Comment by cg-cnu** [comment]
I have done some quick variations based on the inputs you have given...

![image](https://cloud.githubusercontent.com/assets/2767425/24971880/1833dd06-1fd7-11e7-93a2-30fc1e5b6eda.png)

I liked the edges of the font in 6.4 but not the width. So, I am not in favor of choosing that width to the cloud icon as well.  The width in 6.7 seems to be working well.

I like to use two colors, differentiating the text and the logo. The text color doesn't needs to be black. I will play with them and see what goes well. I am still not satisfied with the font. I will try more fonts and see what goes well with the logo.  I am still playing in krita; so don't mind the rough scribbles.  Over the weekend I will move to inkscape.

**Comment by calisro** [comment]
6.5 looks great.  Sharp.

**Comment by dibu28** [comment]
3.6

**Comment by ncw** [comment]
Great work - I like 6.5 - the angles on the font give it the feeling of arrows pointing your data about!  The two colours look good too.

I did some scribbles in my notebook (which I don't have with me at the moment) with actual arrows at the end of the font strokes, but I don't think it worked very well.

**Comment by cg-cnu** [comment]
Thanks for the feedback guys. I feel like, 6.5 is working well with every one. So, I went ahead with it and created the svg. Btw, the font am using is... [nova round](https://fonts.google.com/specimen/Nova+Round). Changed the color of the cloud a bit.
![image](https://cloud.githubusercontent.com/assets/2767425/25104800/647f47de-23df-11e7-8afe-4f6803c8ff48.png)

Let me know if you guys have any questions or suggestions. 
@ncw Anything else we need apart from the logo?

**Comment by cg-cnu** [comment]
Btw, the current tagline for rclone is ``` rsync for cloud storage ```. Modified it to ``` rsync for the cloud ```. Let me know if that is fine :-)

**Comment by pcjonathan** [comment]
I like the logo but the readability on the tagline is pretty low and I can only imagine it would be worse at a smaller size.

**Comment by Maxou44** [comment]
Wow ! Pretty Logo !

The color gradient is a bit strange
The line and "rsync for cloud storage" is unnecessary ;)

**Comment by ajkis** [comment]
`The line and "rsync for cloud storage" is unnecessary ;)`
what he said or maybe: `like rsync only better`

**Comment by daylightbrightledlight** [comment]
@cg-cnu I also like the logo, but the main rclone icon could be simplified up so that it would scale well with different sizes (mainly the arrows).

**Comment by Andy58** [comment]
I had the same thoughts about the logo, so here's my contribution. Let me know what you think.
![rclone](https://user-images.githubusercontent.com/4202141/45551816-4ecf9200-b82f-11e8-98f9-660ba9882f97.png)

**Comment by dibu28** [comment]
Great!

**Comment by ncw** [comment]
@Andy58 I really like your thinking behind the cloud/trefoil device and the logo animation is very cool!

That would work extremely well as a square icon and the animation would work there too.

I think the only thing I'm not 100% on is the thin R bold CLONE, but I'm about 95% on it :-)

Where do you want to go from here?  I'd like to get some community engagement on logo choice and I'm aware that @cg-cnu put in a lot of work which unfortunately didn't come to fruition.

**Comment by NurdTurd** [comment]
@Andy58 Lookin' good! 👍

**Comment by ncw** [comment]
Thanks for the additional designs.  I think you are right that A is the best option.

I think the thing to do now is to present the change, probably as a forum post and publicize it in the community via twitter etc. Are you on [the rclone forum](https://forum.rclone.org/)?  Can you register, then I'll prepare a page and you can give it the once over before we make it public.

If you want to see what assets rclone has already, you can find them here: https://github.com/ncw/rclone/tree/master/graphics 

The website could probably do with a bit of love - I don't know whether that is within your capabilities?  It is a [hugo](https://gohugo.io/) based static site with some really basic bootstrap styling that I did (design is not my forte ;-).

**Comment by Andy58** [comment]
> Thanks for the additional designs. I think you are right that A is the best option.
> 
> I think the thing to do now is to present the change, probably as a forum post and publicize it in the community via twitter etc. Are you on [the rclone forum](https://forum.rclone.org/)? Can you register, then I'll prepare a page and you can give it the once over before we make it public.

Thank you. I've registered and also done some cleanup and invisible adjustments and have a new PNG ready to go. Do I understand correctly, that you are going to set up a page / forum post? Do you want to upload the image there, or is it something you'd like me to do?

> 
> If you want to see what assets rclone has already, you can find them here: https://github.com/ncw/rclone/tree/master/graphics

I've had a look at them and will have those sizes ready and some more. I'd go with PNG, EPS and SVG as formats as they should cover all needs.

> 
> The website could probably do with a bit of love - I don't know whether that is within your capabilities? It is a [hugo](https://gohugo.io/) based static site with some really basic bootstrap styling that I did (design is not my forte ;-).

Honestly I like the design and structure of rclone's site. It's clearly arranged and foremost serves its purpose. I'll have a deeper look and think about some design enhancements. I'll look into hugo as-well.

**Comment by ncw** [comment]
@Andy58 apologies for the delay - work has been a bit hectic....

I've made a forum post to let people know what is happening and for comments: https://forum.rclone.org/t/a-new-logo-for-rclone/7019 - I also put it out on twitter: https://twitter.com/njcw/status/1046340082939154432

Do you want to prepare a pull request with updated graphics?  Or if you prefer you can share them with me and I'll commit them to the repository.

Thank you :-)

**Comment by animosity22** [comment]
This looks to be done as I can see the new logo :)

If not, please let me know and I can re-open it.
