### ISSUE TITLE
Put Rclone copy in background.

### ISSUE THREAD

**Issue by romanturbo** [rclone/rclone#1266]
Im using putty to copy files from a local device to remote google drive.
I use the following command:
`rclone copy -v /home/googledrive secret:`

The problem? Ive a lot of internet cutouts in my house, so putty loses connection, and rclone seems to stop.
Any advice?

**Comment by naeloob** [comment]
nohup rclone copy -v /home/googledrive secret: &

nohup : avoids to stop when putty losses connection
& : put rclone in background

**Comment by animosity22** [comment]
I usually just use 'screen' to put stuff in the background. 

https://www.howtoforge.com/linux_screen

**Comment by smtdev** [comment]
You can use tmux too:

https://tmux.github.io/
https://gist.github.com/henrik/1967800

Anyway, if you lose your network connection, you should start the rclone copy process again.

**Comment by animosity22** [comment]
This was answered. Closing out.
