### ISSUE TITLE
Object not found - waiting

### ISSUE THREAD

**Issue by Powerbless** [rclone/rclone#1267]
> What is your rclone version (eg output from `rclone -V`)
newest BETA from homepage

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 Enterprise 64bit, Windows Server 2012 R2 64bit
> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive EU
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone move --acd-upload-wait-per-gb 3m0s --transfers 8 source: destination:
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

`2017/03/23 08:43:40 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (138/146)
2017/03/23 08:43:46 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (139/146)
2017/03/23 08:43:51 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (140/146)
2017/03/23 08:43:56 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (141/146)
2017/03/23 08:44:01 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (142/146)
2017/03/23 08:44:06 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (143/146)
2017/03/23 08:44:11 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (144/146)
2017/03/23 08:44:16 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (145/146)
2017/03/23 08:44:22 DEBUG : pathtocontent\S01E01.mkv: Object not found - waiting (146/146)
2017/03/23 08:44:27 DEBUG : pathtocontent\S01E01.mkv: Giving up waiting for object - returning original error: HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}" ("400 Bad Request")
2017/03/23 08:44:27 DEBUG : pacer: Rate limited, sleeping for 884.491574ms (1 consecutive low level retries)
2017/03/23 08:44:27 DEBUG : pacer: low level retry 1/1 (error HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}")
2017/03/23 08:44:27 DEBUG : pathtocontent\S01E01.mkv: Received error: HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}" - low level retry 2/10
2017/03/23 08:44:27 DEBUG : pacer: Resetting sleep to minimum 20ms on success`
-----------------------------------------------
this problem is since 1 or 2 weeks....before the 2 weeks the uploads was working without anny issue. has amazon anything changed?

**Comment by ncw** [comment]
Amazon service level seems to get better and worse like the weather!  I don't know of anything changing in particular though.

**Comment by francesco2013** [comment]
I have exactly the same problem. Amazon should be ashamed of themselves. They literally STEAL the money from their customers giving you a storage that sucks donkey balls and like it is not enough it is extremely slow in downloading. 

To upload a file 6 gb with rclone 1.35 on a mounted amazondrive on Linux needs to re-upload it 6 times before it finally spawns up. Amazon is unable to do their job they are the worst IT company in the bloody world. Shame on them !

**Comment by madcatsu** [comment]
I experience the same issue from time to time with ACD jobs. Can anyone recommend a target which provides similar pricing to ACD that performs much better? Hubic looked like a decent alternative till I saw they have terrible performance issues. See #697 

The issue with ACD seems sporadic and looks like the result of rate limiting on API connections across multiple users. The worst part is when a file transfer finishes, the data appears to go missing and must be retried from scratch.

**Comment by animosity22** [comment]
This looks answered. If you still have a question, please feel free to post on the forums.

RIP ACD.
