### ISSUE TITLE
Feature Request: Parallel Downloading of a Single File (ACD)

### ISSUE THREAD

**Issue by gordan-bobic** [rclone/rclone#1276]
I am finding that a single download thread (using rclone copy) from an ACD volume tops out at about 25Mbps for me. My downlink can handle 200Mbps.

When I start another rclone copy operation, that seems to top out at about 20Mbps. It doesn't matter whether I am downloading the same file from ACD (to a different local location) or a different one, each download tops out at about 20Mbps. So while the returns seem to be diminishing with the increase in the number of threads, there clearly seems to be scope for gain from using more than one thread.

This implies there is some kind of throttling in place on ACD that limits each download thread to about that speed (at least for me).

So it would be really handy if rclone copy (downstream only, I realize upstream this won't work due to the object storage model) downloaded files in parallel with a few threads. Parameter to specify the number of threads for download would be really handy.

It would be extra handy if rather than making the chunks evenly spaced, they were of configurable size, so the front of the file would be downloaded first (e.g. 2 threads with 100MB chunks would get 0-100MB and 100-200MB simultaneously before a thread that finished would start 200-300MB chunk. This would be handy for uses such as media streaming to reduce the time before the file could be reasonably streamed from the beginning before the download actually completed. It would also probably be best if the file was created sparse with the full size of the source file at the very beginning to avoid confusing applications that are reading the file.

**Comment by ajkis** [comment]
It would help a lot with streaming as well.

**Comment by gordan-bobic** [comment]
Given the diminishing returns I observed, too many threads would be detrimental for streaming, especially when coupled with requests/hour based throttling. While I think thread count and chunk size should be configurable, I am struggling to see how more than 2-3 threads would actually do more good than harm for the streaming use case.

**Comment by ncw** [comment]
ACD supports range requests (as to nearly all the remotes) so this is certainly possible.

I'd need to make some extra internal interfaces so that the destination remote (eg local disk) could support ranged writes, or failing that the rclone core would need to buffer the chunks in memory which is probably undesirable.

I don't think this would help for streaming though as the whole point would be to download from different parts in the file simultaneously, whereas for streaming you are really only interested in the data at one given point (ie the place you are watching).

**Comment by gordan-bobic** [comment]
I think it will help with streaming to some extent because if you pause the playback until the first two segments are complete, it'll the rest will download faster and thus be more likely to be available by the time the playback reaches the next batch of segments.

**Comment by ajkis** [comment]
For some reason plex never get enough chunks/segments as Plex log is always full of 
`[0x7fc1eeff5700] DEBUG - We want 600 seconds ahead, last returned was 395.000000 and max is 995.036711.`

**Comment by gordan-bobic** [comment]
Plex also does far more small range scans than is sensible. Inotify shows 5-10 file open events per minute, varying also with the bit rate of the stream.

**Comment by hjone72** [comment]
@ajkis, aren't those log messages related to how much pre-transcode you've completed? Your settings suggest you throttle your transcoder after 600 seconds.

**Comment by zopthemop** [comment]
Implementing #497 would sort of give us this for free, in a less flexible form (changing the chunk size might not be trivial).

**Comment by ncw** [comment]
I'm going to close this since rclone no longer has any ACD keys and Amazon aren't issuing new ones.
