### ISSUE TITLE
ACD copy with --retries 1 keeps retrying

### ISSUE THREAD

**Issue by 4getit** [rclone/rclone#1282]
rclone v1.36

I'm using rclone a lot with gdrive (thank you!) but I'm having issues with ACD.

I currently have a huge batch of ~3-5GB files I want to copy from an unencrypted gdrive to an encrypted ACD.

I have a fast connection and when I start the copy with (let's say) --transfers 64, it stalls out after the first 50 files or so. The remaining and new ones all keep hanging at 100%.
I think this is because ACD is processing them but it really takes forever and the transfer stops.

(What I cannot figure out is what --acd-upload-wait-per-gb 60m exactly does. Does it wait 60 minutes  to see if the file is there or does it keep checking and is the 60m per GB a maximum/timeout?)

What I did figure out is that if I cancel the transfer, the/most files show up eventually.

So I am trying to let rclone just copy and continue without waiting/retrying. (After that, I'll do a proper sync)
However, whatever I do, it keeps retrying.

If I simply copy a single file with --retries 1 --transfers 1 --acd-upload-wait-per-gb 0 -v
It uploads the file, it stalls at 100% for a bit and then tries the file again.
As far as I understand, --retries 1 means it won't retry. But that's not what I'm seeing.

I'm not sure if I ran into a bug or need some advice.

**Comment by ncw** [comment]
You need to set `--low-level-retries` if you want to control the retry of individual operations.  It is 10 by default.

> (What I cannot figure out is what --acd-upload-wait-per-gb 60m exactly does. Does it wait 60 minutes to see if the file is there or does it keep checking and is the 60m per GB a maximum/timeout?)

It is a maximum timeout - if the file appears before then it will carry on.

**Comment by animosity22** [comment]
This looks answered. If you still have a question, please feel free to post on the forums.

ACD is also very departed.
