### ISSUE TITLE
decrypt data encrypted with encfs

### ISSUE THREAD

**Issue by thetorx** [rclone/rclone#1283]
hi there,
in the past i have sent on google drive and amazon cloud drive some data encrypted with encfs for privacy.
then i found rclone, and it was pretty convenient to mount the remote data as local.
i also tried to decrypt on the fly encfs encrypted data on a mounted path with rclone, and it works fine.
this morning reading rclone documentation i found that there is also a crypt support, so i am wondering if i am acting silly using both encfs and rclone, when maybe rclone is enough, but i can't understand what kind of encryption/decription rclone supports and if it is compatible with the the encryption i made with encfs.
can someone point me in the right direction?
thanks a lot

**Comment by Cr0nixx** [comment]
No, they are not compatible. How the crypt storage works is explained here: http://rclone.org/crypt/

**Comment by thetorx** [comment]
thanks for your answer.
i don't want to use both, i agree it's overkill in general and in my case in particular: my data are not nuke launch codes, nobody gives a damn.
i just wanted to understand if i could remove the encfs step and rely only on rclone for the data already encrypted with encfs. i had already read the info at the link you gave me, but i have short experience with compression so i could not be sure if enfs and rclone use the same standards and, sadly, from your answer i understand they are not.
thanks again

**Comment by Cr0nixx** [comment]
They are not, so you will have to reupload the data to only use rclone crypt and not encfs.

**Comment by animosity22** [comment]
This was answered. Closing out.
