### ISSUE TITLE
[BUG] ACD Weird issues that get resolved with remounting 

### ISSUE THREAD

**Issue by ajkis** [rclone/rclone#1284]
Latest beta.

I notice quite few weird issues with rclone ACD mount:

> plex@plex ~ $ ls /mnt/cloud/tmp/
> 100M.file  100Mtest  10G.file  1G.file1  1G.file2  1G.file3  1G.file4  1G.file5  20G.file
> plex@plex ~ $ copyspeedtest
> 27.03.2017 08:57:32 COPY SPEED TEST START
> ###### MOUNT SETTINGS ######
> unionfs-fuse -o cow,allow_other,nonempty,sync_read /storage/local=RW:/mnt/acdcrypt=RO /mnt/cloud
> |   PROGRESS   |   RATE   | AVG. RATE | Copy file: /mnt/cloud/tmp/1G.file1
> pv: failed to read file: /mnt/cloud/tmp/1G.file1: Input/output error

> plex@plex ~ $ stat /mnt/cloud/tmp/1G.file1
>   File: '/mnt/cloud/tmp/1G.file1'
>   Size: 1073741824      Blocks: 2097152    IO Block: 4096   regular file
> Device: 29h/41d Inode: 48317       Links: 1
> Access: (0644/-rw-r--r--)  Uid: ( 1000/    plex)   Gid: ( 1000/    plex)
> Access: 2017-02-23 12:24:03.049000000 +0100
> Modify: 2017-02-23 12:24:03.049000000 +0100
> Change: 2017-02-23 12:24:03.049000000 +0100

After remounting it started to work.
I also noticed performance impact ( lower speed ) on prolonge mounts eg when ACD was not remounted in 24h ( need more testing ) but something weird is going on.

**Comment by ncw** [comment]
Can you paste the logs from rclone mount please?

**Comment by ajkis** [comment]
I did not had it mounted in debug mode 
This is the only thing i got in log
2017/03/27 08:57:32 ERROR : tmp/1G.file1: File.Open failed: open for read: Get https://content-eu.drive.amazonaws.com/cdproxy/templink/Q1VQdTVPVmo5s-dlOcOmvZrMavOK-35z_2tPVamt2XA38XJVg: dial tcp: lookup content-eu.drive.amazonaws.com on 94.140.66.250:53: no such host
`2017/03/27 08:57:32 ERROR : tmp/1G.file2: File.Open failed: open for read: Get https://content-eu.drive.amazonaws.com/cdproxy/templink/5kQyYnyAR1e4dcErcyLRvsPP89ZeloO0MdhW_Dgs4K038XJVg: dial tcp: lookup content-eu.drive.amazonaws.com on 94.140.66.250:53: no such host
`

**Comment by ncw** [comment]
That error means that the name couldn't be resolved which is usually a temporary networking error.

**Comment by ajkis** [comment]
Hmm weird I thought retry would solve it, since internet is working during that time and a second later another files was copied without a problem.

**Comment by animosity22** [comment]
ACD has gone to sleep with the fishes.
