### ISSUE TITLE
I was wondering if it would be possible to make --crypt-show-mapping less verbose. 

### ISSUE THREAD

**Issue by johnpowell** [rclone/rclone#1290]
Perhaps instead of: 

`2017/03/28 16:14:58 NOTICE: TV: Encrypts to "jb63m2g7ieuvv7s8cptin33b18"`
`          -1 2017-03-25 18:17:25        -1 TV`

It would just do: 

`TV --> "jb63m2g7ieuvv7s8cptin33b18"`

I only suggest this since when I need it I dump it into a text file that I can work with a bit easier in Sublime.

**Comment by Cr0nixx** [comment]
I don't see how rclone should be responsible for it, you could for example pipe it into sed:

rclone -v ls --crypt-show-mapping remote:path | sed 's/^.*NOTICE: //' | sed 's/" .*/"/'

will make 

`2017/03/28 16:14:58 NOTICE: TV: Encrypts to "jb63m2g7ieuvv7s8cptin33b18"
-1 2017-03-25 18:17:25 -1 TV`

to

`TV: Encrypts to "jb63m2g7ieuvv7s8cptin33b18"`
