### ISSUE TITLE
copy to ACD - keep uploading while waiting for files to appear?

### ISSUE THREAD

**Issue by ftruzzi** [rclone/rclone#1300]
Hi,

I usually upload to ACD using the option --transfers 1 to upload one file at a time and minimize losses if my connection drops. 

I have noticed that, after uploading a file and while checking if that file is present (so when the "Object not found - waiting" message pops up), rclone doesn't upload the next file but just keeps waiting for the file to appear. When uploading large files it can sit idle for 2-3 hours, maybe just to start again because the file was not found.

It could be useful if rclone could start uploading the next file while checking if the current one has been actually uploaded. In case of failure, it could add it to the queue again.

Thanks :)

**Comment by diamondsw** [comment]
It seems like --transfers establishes a fixed queue of connections with the cloud provider; it would be useful if once data transfer is complete and "Object not found - waiting" begins that it frees up its slot in the queue. Even with more transfers enabled (such as the default 4), it's easy for all of them to be blocked waiting for Amazon, and the program just sits there doing nothing. If a retry is eventually required, it can wait for an open slot like any other pending transfer.

**Comment by ncw** [comment]
That is a nice idea.  It is a bit complicated to implement as the wait for the upload logic is in the amazon cloud drive module, wheras the restriction of the number of transfers is in the general copying layer of rclone.

**Comment by Powerbless** [comment]
at the moment amazon has very big problems with files over 6GB...this files must be uploaded 3 times before there are finished uploaded

**Comment by ncw** [comment]
I'm going to close this since rclone no longer has any ACD keys and Amazon aren't issuing new ones.
