### ISSUE TITLE
Sync subdirectories recursively excluding some

### ISSUE THREAD

**Issue by mehargags** [rclone/rclone#1306]
Hi Everyone... just tried RClone for the first time. Read for about 20 mins but could not get it straight.

I have a deep directory structure with 1000s of images inside 100s of subdirectories to be sync'd recursively to my Google Drive, but leaving out ./cache and ./thumbnails directory.

## Issue #1 rClone does not copy subdirectories
`rclone sync /synctest/images GDrive:/images`
this ... only sync files in the dir specified
Why is it not sync'ng and creating the directory structure ? What arguments need to be passed to sync all subdir recursive?

## issue #2 How to exclude certain directories
is this right ?
`rclone sync /synctest/images GDrive:/images --exclude "/thumbnails/**"`

I read you can make and load and exclusion file... but if I only need to exclude one or two directories, what will be the right parameter to pass ?

Thanks

**Comment by ncw** [comment]
> Issue 1 rClone does not copy subdirectories

rclone does copy subdirectoreis by default.  However it doesn't copy **empty** directories - is that your problem?

> issue 2 How to exclude certain directories

`--exclude "/thumbnails/**"` this will exclude thumbnails and everything in it.  If you have thumbnail directories not at the root, then you want `--exclude "thumbnails/**"`.  However I suspect you are missing the leading `.`, so what you want is `--exclude "/.thumbnails/**"`
