### ISSUE TITLE
Adding Ohio AWS region for S3

### ISSUE THREAD

**Issue by obmelvin** [rclone/rclone#1311]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
ubuntu 16.04.2 LTS

> Which cloud storage system are you using? (eg Google Drive)
drive and s3

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone ls aws:ctrl-ccoi-videos
2017/04/04 11:31:11 Failed to ls: BucketRegionError: incorrect region, the bucket is not in 'us-east-1' region
	status code: 301, request id:

I'm happy to make this change myself and submit a PR. I just want to verify that the only file needing to be changed is s3/s3.go and adding to the region and location_constraint options

**Comment by ncw** [comment]
Yes that sounds right - see 6f8501e9a1b38cdd0aaee752d325dcc6552ef750 for an example.

PR much appreciated!

Thanks

**Comment by zahiar** [comment]
Hi guys, 

Was adding London S3 region and came across this ticket, so added in the Ohio one as well :)
PR can be found here #1377

**Comment by Kriechi** [comment]
Since #1377 was merged, I suppose this issue can be closed as well?

**Comment by ncw** [comment]
I'll close this - thanks
