### ISSUE TITLE
Uploading smaller files first

### ISSUE THREAD

**Issue by trustin** [rclone/rclone#1318]
I wish there's a way to tell rclone to process smaller files first when doing `rclone sync`, so that a few huge files do not delay the upload of vast majority of small files in my backup. 

It would be even better if there's some sort of 'lane splitting' feature so that a user can assign certain set of files to their dedicated lane, probably by defining multiple lanes based on path patterns and sizes? e.g. Use 'small' lane for the files under 100MB and use 'photos' lane for '*.jpg'.

> What is your rclone version (eg output from `rclone -V`)

1.36

**Comment by ncw** [comment]
This issue has come up before (can't find the issue though!).

I like your idea of lanes - it would have to be implemented something like that.

**Comment by Skylion007** [comment]
There is probably an optimal way to order the file uploads. For instance, imagine you are uploading lots of small files and several large files. The best order to upload for Google Drive would probably be to upload in an interleaved ascending and descending order. The large files will be constrained by the time it takes to upload each large file and the small files would be limited by the limit Google Drive has on creating several small files. Maybe we could even define a sorting/heap strategy that the user could specify. For instance, the order I described, the large files first, the small files first, alphabetical, ls order, etc.

**Comment by sinky** [comment]
Would love this option too.

**Comment by beren12** [comment]
This sounds great. I wanna backup my server and it's 3million files. anywhere from 1k to 100gb :-)

**Comment by Joshfindit** [comment]
I wonder if the interface could have these goals:

- Allow lanes to be specified
- Allow lanes to use any filters that 'naked' rclone can use
- Share the transfer queue between lanes so that sync works as expected

And an interface like this:
```bash
rclone sync --lanes "--transfers 10&--max-size 10MB, --transfers 10&--min-size 10MB" src dest
```

With these nice to haves:
```bash
&--order-by date-descending # Newest first
&--delay-between # Esp for smaller files. Calculates hashes during the delay, and it mostly for things like the GDrive limitations
```

**Comment by ncw** [comment]
Actually this is done already!

See [--order-by](https://rclone.org/docs/#order-by-string) for more details.

The `mixed` mode is specifically an attempt to produce lanes so you can be uploading some large ones and some small ones.

I'll close this now :-)
