### ISSUE TITLE
Unable to get GCS to sync via encrypt

### ISSUE THREAD

**Issue by onedr0p** [rclone/rclone#1325]
I have set up `Google Cloud Storage` and I am trying to use the sync command to get it to work with the `encrypt` instance of my GCS bucket

It works fine when I don't use the encrypted one, but as soon as I use the  encrypt version of this GCS it has an error.

**Works fine:**

```
rclone sync -vv /river/Linux\ Isos google-cloud-media:media/Isos
```

**Errors:**

```
rclone sync -vv /river/Linux\ Isos google-cloud-media-secret:media/Isos
```

```
2017/04/12 19:44:58 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "sync" "-vv" "/river/Linux Isos" "google-cloud-media-secret:media/Isos"]
2017/04/12 19:44:58 INFO  : Encrypted Storage bucket  path auhdibp4p7vdg7k18qa38ifvck/t8db14ar39palg995o755le0rs/: Modify window is 1ns
2017/04/12 19:44:58 ERROR : Attempt 1/3 failed with 1 errors and: googleapi: Error 400: Required, required
2017/04/12 19:44:58 ERROR : Attempt 2/3 failed with 1 errors and: googleapi: Error 400: Required, required
2017/04/12 19:44:58 ERROR : Attempt 3/3 failed with 1 errors and: googleapi: Error 400: Required, required
2017/04/12 19:44:58 Failed to sync: googleapi: Error 400: Required, required
```
Why is the bucket name blank on the INFO line? That's odd.

Any suggestions? I have this working with dropbox and google drive. I don't think I am missing anything...

rclone ls, size seem to all be working, just not sync or copy

**Comment by ncw** [comment]
In the crypt remote did you put a bucket?

From this bit in [the crypt docs](https://rclone.org/crypt/)

> This means that if you are using a bucket based remote (eg S3, B2, swift) then you should probably put the bucket in the remote s3:bucket. If you just use s3: then rclone will make encrypted bucket names too (if using file name encryption) which may or may not be what you want.

I think that will probably fix your problem.
