### ISSUE TITLE
Mount crashed with "out of memory"

### ISSUE THREAD

**Issue by seppi91** [rclone/rclone#1326]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.36
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
 Ubuntu 16.04.2 LTS 64 Bit
> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive with crypt
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
/usr/bin/rclone mount --allow-other --buffer-size 128M --max-read-ahead 10M --checkers 20 --transfers 20 --dir-cache-time 5m --no-modtime --umask 002 --config=/etc/rclone/.rclone.conf -vvv --log-file=/var/log/rclone.log --ask-password=false acd-crypted:/ $RCLONE_MOUNTDIR

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
http://paste.ubuntu.com/24374075/

As described in title, my mount just stopped working and exited with an fatal error. My mount is running on a virtual machine on my kvm host. It has a maximum of 4GB RAM provided, as I thought this should be sufficient? Should I provide the VM even more than 4GB of memory or is this an exception within rclone?

**Comment by ncw** [comment]
You've set a buffer size of 128M - how many open files did you have?  Each open file will use 128M of memory.

**Comment by seppi91** [comment]
Well I wasn't personal active on the machine as the mount crashed. Probably it crashed while emby scanned the media directory. So it may be possible that there were multiple files open at once. When you say every open file will take 128MB of memory, does this also apply to opened files which have a size <128MB?

When I'm right setting transfers to 20 should limit the count of open files to 20? So there's a max of 20*128MB which could be used by rclone?

**Comment by ncw** [comment]
> When you say every open file will take 128MB of memory, does this also apply to opened files which have a size <128MB?

No the buffer can only be the max size of the file, rounded up a bit.

> When I'm right setting transfers to 20 should limit the count of open files to 20? So there's a max of 20*128MB which could be used by rclone?

If you were using rclone sync/copy/move then that would be correct, but it isn't under rclone's control using rclone mount how many open files there are.

**Comment by animosity22** [comment]
This looks answered. If you still have a question, please feel free to post on the forums.
