### ISSUE TITLE
sudo rclone does not gracefully handle SIGINT inside screen when entering configuration password

### ISSUE THREAD

**Issue by emilfihlman** [rclone/rclone#1332]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.36
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux hostname 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
Debian 8.7
> Which cloud storage system are you using? (eg Google Drive)
Multiple
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
Any when configuration password is used
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Not applicable

To reproduce:
1. Have a configuration password for rclone
2. Launch rclone with sudo rclone inside a screen
3. press ctrl+c when entering password
4. No character input is shown, enter works as expected

To temporarily fix:
1. Make sure your input is clear
2. Enter "reset"
3. Your terminal will now reset itself and return to full operating condition

OR
1. Launch a new terminal

**Comment by ncw** [comment]
I can't replicate this on Ubuntu 16.10.

When I CTRL-C the terminal is reset properly.

Which terminal are you using?

Do you have to use sudo to see the problem?

**Comment by emilfihlman** [comment]
Ah, you have to also be inside a screen.

**Comment by ncw** [comment]
I can't replicate this in a screen on Ubuntu 19.10 so I'm going to assume it got fixed somewhere along the way!
