### ISSUE TITLE
OneDrive Chunked Upload Resume

### ISSUE THREAD

**Issue by yonjah** [rclone/rclone#1333]
Currently when rclone uploads a large file it is being chunked and uploaded in multiple parts.
But if the upload fails for some unrecoverable error rclone will delete the multipart upload target
before exiting.
It would be great if instead deleting it the target link would be saved and rclone will try to resume the upload on a future run. 
This will probably require rclone to save both the file hash and the upload

**Comment by yonjah** [comment]
After doing the schema for the data needed to be saved for implementing this feature - 
![uploadsschema](https://cloud.githubusercontent.com/assets/1829789/25069064/e415a250-22a8-11e7-94cc-21ab4f07d093.png)
Since there are no keys and amount number of rows gonna be small (maximum the number of concurrent transfers) I don't think there is much benefit for using a proper db for this feature and just saving the data in JSON format should be enough

**Comment by ncw** [comment]
I'm currently thinking about this, but I'm going to use #87 as the tracking issue
