### ISSUE TITLE
Feature request: ETA for acd-upload-wait-per-gb post-upload

### ISSUE THREAD

**Issue by Codeman20400** [rclone/rclone#1341]
it would be helpful to have an ETA when waiting on acd to import larger files. I would assume that rclone tracks this internally, so can it be exposed in the verbose output? currently there is no way to determine how much longer rclone is going to wait unless monitored constantly.

**Comment by left1000** [comment]
I know this doesn't help you but what's the command flag to interact with the wait-per-gb system? I've never used/seen/encountered such a thing.

**Comment by Codeman20400** [comment]
the only one that i've used is the --acd-upload-wait-per-gb [duration] flag that defaults to 3min, i believe, which seems to help with 5GB+ files especially

**Comment by left1000** [comment]
is --acd-upload-wait-per-gb missing from https://rclone.org/docs/ ?
I can't find it, I do suck at finding things though.

**Comment by Codeman20400** [comment]
look at the amazon drive page, down in the specific options section

**Comment by left1000** [comment]
I've noticed lately all my files upload twice if they're above 1gb, I guess maybe I need to change 3minutes to 5minutes?

**Comment by Codeman20400** [comment]
it may help, i've seen people set it to 15m before, but keep track of what works and what doesn't

**Comment by left1000** [comment]
Then again the second upload takes less than 15minutes anyways. Really wasteful of me.

**Comment by ncw** [comment]
I'm going to close this since no-one has any keys for ACD any more.
