### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by jtHunter** [rclone/rclone#1342]
Hi,

on syncing from Amazon Drive to local i am facing issues on syncing files with long file/path names. Looks like there is a limitation when path is longer than 2048 signs. Is that correct?

rclone v1.36
MAC OSX 10.12.3
sync from AmazonDrive to Local

ERROR : MWFqcQ0pWUqrj9HzDs1Qklf1Jke991f1TcZ7JbE5LPPjhh1D6yNaQlA=/MQyVg5Dj8AIaN_sUYHiq12Qh_ZSstxmgwUtZ5lsRprkNP5af-mWMYYo=/Mebrm81cYORUglNZ7Cfm9jHt-WZEhprFipWPprvhP4BYecnLj_MoahqBhHkw8ElB7N0uewyzgvwm/Ma8qkSElrfX9iQ6kzT-6TBWs2R_2mYxbtXsH-8KBTOtrQVhBYgXqw6A=/Mdu6bJ9TeJbNIqpUq88BvyWSgBwRxprDTyGrpzUWj0-hPksRgLuUcQE=/MUrkIM1XpkIEXIqatugZYIUftj0ajBFkkp10Eajc9OdJzXUm9RmXzjw=/MQMqJ46Md8J4m8uny3NieGw3rG8MGHcB16IS553eiKTop59n7zhss5A=/MW_SW9owS5YIy0tvmUNAkT-BF0f77uFeEDN2wGkkw7z1fLeZyZxz9aE=/MTEJmANVogb3o-SoyZwi1XW5NdWoYf-In59Z2zdW2KydlxqFyrZvM-ngCJawdM_OFXa0e0hfRfzQ/MavkIUHTlhBlbtoCZ2P7e2gzhignDorEMkDaH5deTAaQAjx7Zg73C6X-9VVr-E9hkvOS1rmpVxSqg43NawAF3Yd9Vo0HnkYyoA==/MRbhxZck2J3xJEBK4fV_Q4iao2qgMNEjdyYsGMTOdCwN_6Rb0gzLT3k=/MWyWQ4DOh1WaKPX0Bj0nPuCshfsZIwAgclohjXqP-0-CD48mE9gpBtU=/MWiaAMJ1KE8kj30GD_Be68ESS00ajJ0ZrQizVoiFh4MnII44VmFSPg_nO1R7ept7YsTWKbsZBS1-/MUHgI6z5eT4Pe1yBPSDzTVZ9hSc_Q6aLhKRiNA02Vhw-Z__-4ajKWKTk5YJx19sBV_X853fcxnVO/MZOp2CUNdZMRpi7GPZApizp02Bl_9UhgJPfKQ3b55EJh9lINg1Rsi8TcNq2CcxsC9TFlfryrkshZ/MchdMF7j4_i2ik_zvLJxYIeNa5bGC_-VdOzwHwpMliuhOKilbAmuleguZ877KQr_pw6b2bY9ALAI: Failed to copy: mkdir /Volumes/BACKUP_003/AmazonDriveBackup/Encrypted/MWFqcQ0pWUqrj9HzDs1Qklf1Jke991f1TcZ7JbE5LPPjhh1D6yNaQlA=/MQyVg5Dj8AIaN_sUYHiq12Qh_ZSstxmgwUtZ5lsRprkNP5af-mWMYYo=/Mebrm81cYORUglNZ7Cfm9jHt-WZEhprFipWPprvhP4BYecnLj_MoahqBhHkw8ElB7N0uewyzgvwm/Ma8qkSElrfX9iQ6kzT-6TBWs2R_2mYxbtXsH-8KBTOtrQVhBYgXqw6A=/Mdu6bJ9TeJbNIqpUq88BvyWSgBwRxprDTyGrpzUWj0-hPksRgLuUcQE=/MUrkIM1XpkIEXIqatugZYIUftj0ajBFkkp10Eajc9OdJzXUm9RmXzjw=/MQMqJ46Md8J4m8uny3NieGw3rG8MGHcB16IS553eiKTop59n7zhss5A=/MW_SW9owS5YIy0tvmUNAkT-BF0f77uFeEDN2wGkkw7z1fLeZyZxz9aE=/MTEJmANVogb3o-SoyZwi1XW5NdWoYf-In59Z2zdW2KydlxqFyrZvM-ngCJawdM_OFXa0e0hfRfzQ/MavkIUHTlhBlbtoCZ2P7e2gzhignDorEMkDaH5deTAaQAjx7Zg73C6X-9VVr-E9hkvOS1rmpVxSqg43NawAF3Yd9Vo0HnkYyoA==/MRbhxZck2J3xJEBK4fV_Q4iao2qgMNEjdyYsGMTOdCwN_6Rb0gzLT3k=/MWyWQ4DOh1WaKPX0Bj0nPuCshfsZIwAgclohjXqP-0-CD48mE9gpBtU=/MWiaAMJ1KE8kj30GD_Be68ESS00ajJ0ZrQizVoiFh4MnII44VmFSPg_nO1R7ept7YsTWKbsZBS1-/MUHgI6z5eT4Pe1yBPSDzTVZ9hSc_Q6aLhKRiNA02Vhw-Z__-4ajKWKTk5YJx19sBV_X853fcxnVO/MZOp2CUNdZMRpi7GPZApizp02Bl_9UhgJPfKQ3b55EJh9lINg1Rsi8TcNq2CcxsC9TFlfryrkshZ: file name too long

**Comment by left1000** [comment]
this is probably an operating system's file explorer built-in limit, iirc.

**Comment by whench18** [comment]
Hello, I have a good suggestion for you. You can try the long path tool. This will help you with ll kinds of path too long issues. This is very helpful, many people already tried.
