### ISSUE TITLE
amazon ACD: very weird issue. Sometimes I'll upload two files in two seperate command line windows and one set of files goes at warp speed and another goes at snails pace.

### ISSUE THREAD

**Issue by left1000** [rclone/rclone#1344]
Weirdly closing the windows, force quitting rclone, restarting rclone, nothing, nothing seems to help. It even seems that files that upload slowly keep uploading slowly, even as I choose other folders to backup which go very fast, at the same time, nothing I can think of seems to help.

It seems like somehow once ACD decides it's going to receive a specific file slowly nothing I do (at least before I get bored and decide to just let a small file take a few hours to upload while I'm afk) can change that. Yet other files breeze through.

Warp speed would be 8-10megabytes per second and snails pace would be 40-100kilobytes per second.

Any idea what amazon is doing that causes this behavior? I'm a very heavy user with a lot of data on their service, but if this is the result of throttling, it's not working very well, and barely discouraged me enough to write this. I doubt a log would be helpful because all the file transfers still work, hence no errors.

EDIT: just noticed I'm still using rclone1.35 maybe an update would help me? (I'm on windows7)

EDIT2: One theory I have is that filesize effects this, it seems to usually be smaller files 50-200mb that suffer from this. (actually very small files transfer speeds aren't really effected at all by file transfer speed anyways at least not enough to notice).

**Comment by zenjabba** [comment]
It seems to depend on which endpoint you get allocated for each connection. I've seen the same issue and it's rather random.

**Comment by francesco2013** [comment]
I have seen this too already sometimes ACD has fast endpoints and very slow ones apparently.

**Comment by left1000** [comment]
ot oh, now I'm worried. I'm getting rate limit exceeded errors from rclone, despite not having used ACD at all in 24hours. Although I did use it a lot recently, limits might be getting strict? anyone know anything about that?

**Comment by Em31Et** [comment]
I am using both acd_cli and rclone.
acd_cli also have this issue.
Sometimes it is very slow (<500KB in 4 transfers), but after restart rclone, i got > 15MB in 4 transfers.
Can rclone auto restart on low speed at certain time?
I am very tired to monitor the speed and manually restart it.

**Comment by bayoumedic** [comment]
this is making ACD unbearable

**Comment by ncw** [comment]
I'm going to close this since rclone no longer has any ACD keys and Amazon aren't issuing new ones.
