### ISSUE TITLE
Encrypted differential backup

### ISSUE THREAD

**Issue by fantom-x** [rclone/rclone#1345]
Hi, I want to build an encrypted back up solution to ACD with rclone that hides the directory structure, timestamps, etc. as well as preserves all Linux attributes, hardlinks, etc. 

My plan is to create a single 1T file, use dm-crypt to encrypt the contents of the file, create an ext4 file system on it, and then mount it. The following commands illustrate the idea.
```
mkdir dm-crypt
truncate -s 100G dm-crypt/data.img
cryptsetup luksFormat --cipher=aes-xts-plain64 --key-size=512 --hash=sha512 --iter-time=5000 --use-random dm-crypt/data.img 
cryptsetup luksDump dm-crypt/data.img
cryptsetup luksOpen dm-crypt/data.img acd
mkfs.ext4 -m 0 -O dir_index -L acd /dev/mapper/acd 
```
At this point I can mount my new (in-file) file system and start using it. The "data.img" file is simply huge to back up as a whole, but its contents is gonna be mostly static (and encrypted with a block cypher). Can rclone upload the file (or be modified to do so) to ACD in chunks of specified size? And ignore the chunks that did not change by checksum
```
data.img.000000
data.img.000001
....
data.img.009999
```
The first upload would obviously take a while, but all subsequent ones would only upload the modified chunks.

The recovery procedure would be completely manual (well, scripted if needed): download the files, concatenate the pieces, and mount the file.

**Comment by azureblaze** [comment]
You might want to checkout hashbackup or borg.

**Comment by fantom-x** [comment]
@azureblaze Thx for the suggestions, but those do not seem to support Amazon Cloud Drive.

**Comment by azureblaze** [comment]
@fantom-x actually hashbackup has the ability to send the backup to any storage supported by rclone buily, but personally i just backup then run `rclone sync backupdir: borg:`. Where `borg:` is an rclone crypt so you can use it on any remote really.

**Comment by fantom-x** [comment]
From what I understand both of require additional disk storage to store the backup itself before uploading to the cloud. I was hoping to avoid that and directly upload parts of the file.
