### ISSUE TITLE
remote:dropbox to remote:b2 keep running into 429.. any solutions?

### ISSUE THREAD

**Issue by vesper8** [rclone/rclone#1354]
using v 1.36

trying to finish syncing a folder with a very large number of files. Unfortunately it didn't finish the first time I ran it and now when I try to run it again it first does something like 30k checks very quickly I imagine and then starts to pick up where it left off.. but at this point it's bombarded dropbox with so many checks in such a small time window that I always inevitably run into the unexpected HTTP status code 429 error

actually I'm not certain if it's B2 or Dropbox complaining about too many requests in this case.. but whichever it is.. is there a way to slow it down so it doesn't do this?

It looks like it's dropbox though because it says 

Failed to copy: failed to open source object: unexpected HTTP status code 429

**Comment by ncw** [comment]
Can you run rclone with `-vv --dump-bodies` - this wil generate a huge amount of logs!  However if you could attempt to capture the http request and the 429 response that would be very useful.  (Note the http requests have an ID you can match up with the http responses).

**Comment by vesper8** [comment]
is this enough to help?

```
2017/04/19 16:07:33 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/04/19 16:07:33 INFO  : Encrypted B2 bucket bucketName path DEV/DEV/: Waiting for checks to finish
2017/04/19 16:07:33 INFO  : Encrypted B2 bucket bucketName path DEV/DEV/: Waiting for transfers to finish
2017/04/19 16:07:33 ERROR : Attempt 2/3 failed with 0 errors and: error reading source directory "": couldn't list single level: Too Many Requests
2017/04/19 16:07:33 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/04/19 16:07:33 DEBUG : HTTP REQUEST (req 0xc420190600)
2017/04/19 16:07:33 DEBUG : POST /b2api/v1/b2_create_bucket HTTP/1.1
Host: api001.backblazeb2.com
User-Agent: rclone/v1.36
Content-Length: 90
Authorization: XXXX
Content-Type: application/json
Accept-Encoding: gzip

{"accountId":"fiuhsdfijhsdfgh","bucketName":"bucketName","bucketType":"allPrivate"}
2017/04/19 16:07:33 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/04/19 16:07:33 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/04/19 16:07:33 DEBUG : HTTP RESPONSE (req 0xc420190600)
2017/04/19 16:07:33 DEBUG : HTTP/1.1 400 Bad Request
Connection: close
Content-Length: 100
Cache-Control: max-age=0, no-cache, no-store
Content-Type: application/json;charset=UTF-8
Date: Wed, 19 Apr 2017 14:07:30 GMT
Server: Apache-Coyote/1.1

{
  "code": "duplicate_bucket_name",
  "message": "Bucket name is already in use",
  "status": 400
}
2017/04/19 16:07:33 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/04/19 16:07:33 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/04/19 16:07:33 DEBUG : HTTP REQUEST (req 0xc420190c00)
2017/04/19 16:07:33 DEBUG : POST /b2api/v1/b2_list_file_names HTTP/1.1
Host: api001.backblazeb2.com
User-Agent: rclone/v1.36
Content-Length: 122
Authorization: XXXX
Content-Type: application/json
Accept-Encoding: gzip

{"bucketId":"hdsjhasdlhasdihasdjhasdh","startFileName":"DEV/DEV/","maxFileCount":1000,"prefix":"DEV/DEV/","delimiter":"/"}
2017/04/19 16:07:33 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/04/19 16:07:33 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/04/19 16:07:33 DEBUG : HTTP REQUEST (req 0xc420191000)
2017/04/19 16:07:33 DEBUG : GET /1/metadata%2Fauto%2F%23MAC%2FBACKUP%2FDEV%2FDEV?file_limit=10000&include_deleted=false&list=true&locale=en HTTP/1.1
Host: api.dropbox.com
User-Agent: rclone/v1.36
Authorization: XXXX
Accept-Encoding: gzip

2017/04/19 16:07:33 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2017/04/19 16:07:33 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/04/19 16:07:33 DEBUG : HTTP RESPONSE (req 0xc420191000)
2017/04/19 16:07:33 DEBUG : HTTP/1.1 429 Too Many Requests
Content-Length: 30
Connection: keep-alive
Content-Type: application/json
Date: Wed, 19 Apr 2017 14:07:31 GMT
Retry-After: 300
Server: nginx
X-Dropbox-Request-Id: 2fba6a992a7660a29594673963fd6288

{"error": "Too Many Requests"}
2017/04/19 16:07:33 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/04/19 16:07:34 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2017/04/19 16:07:34 DEBUG : HTTP RESPONSE (req 0xc420190c00)
2017/04/19 16:07:34 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: max-age=0, no-cache, no-store
Content-Type: application/json;charset=UTF-8
Date: Wed, 19 Apr 2017 14:07:32 GMT
Server: Apache-Coyote/1.1
```

**Comment by ncw** [comment]
According to the [b2 docs](https://www.backblaze.com/b2/docs/calling.html) this is what a 429 error means

> 429 TOO MANY REQUESTS - B2 may limit API requests on a per-account basis.

So what is probably happening is that you are blowing your quota of requests.

Is this a free B2 account?  They have a fixed quota of requests.

This might be related to #1277 in which case you should find the temporary work-around there works.

**Comment by vesper8** [comment]
this was with a paid b2 account

i ended up finishing the sync'ing job from my local machine.. which was a lot slower than dropbox -> b2 via a digitalocean droplet.. but it worked in the end.. and I guess since it was slower I didn't run into anymore limits

**Comment by ncw** [comment]
I wonder if backblaze have put some new API limiting in place...

**Comment by ncw** [comment]
...However the `--old-sync-method` flag would probably fix it for you.

**Comment by FullstackJack** [comment]
What is the backblaze b2 request limit. I'm comparing services and curious which one would allow me to send 1000 files per second.

**Comment by ncw** [comment]
> What is the backblaze b2 request limit? I can't find information on their API limits anywhere. DigitalOcean Spaces says 200 files per second is rate limited. I'm comparing services and curious which one would allow me to send 1000± files per second.

I don't think b2 publish their request limit.  I think the only services which will support 1000 files per second will be the large cloud provider blob storage, so s3, gc3 and azureblob.

**Comment by ivandeex** [comment]
@vesper8 Does the problem reproduce with rclone 1.54?

**Comment by ivandeex** [comment]
rclone 1.54 has options `--tpslimit` and `--bwlimit` that might help you.
Please try out.

**Comment by ivandeex** [comment]
Closing stale requests
