### ISSUE TITLE
Files randomly will not transfer.

### ISSUE THREAD

**Issue by ml3000** [rclone/rclone#1355]
This is the command I am using:

`rclone copy /home/ml3000/Completed Media:Downloads -v --no-traverse --min-age 5m -L`

This is the error message I get:

`Failed to copy: googleapi: Error 404: File not found: 0B0SS70Q9WEDFajNZa2hReWdZX3M, notFound`

Its on completely random files. No matter what those files will not transfer even if I start the transfer over again.

**Comment by naeloob** [comment]
Take a read here : https://github.com/ncw/rclone/issues/1315
I think it's related to.

**Comment by sweharris** [comment]
I'm not sure.  The name "0B0SS70Q9WEDFajNZa2hReWdZX3M" doesn't match the obfuscated pattern and doesn't calculate to a zero distance.  On an unfixed copy of the obfuscation code the name displays fine with obfuscation on both Amazon and GDrive backends.

"0B0SS70Q9WEDFajNZa2hReWdZX3M" looks more like "standard" filename encryption to me!

**Comment by ncw** [comment]
What are those files called?  Do they have any funny unicode or other characters in them? 

Do the files download properly if you use the web interface?

**Comment by ml3000** [comment]
I am using standard encryption. 

One of the files I was moving was called:

The.Magnificent.Seven.2016.720p.BluRay.x264-SPARKS.mkv

Like I said its on completely random files. No matter what I do even if i start the copy again its always certain files that it gets hung up on.  

I havent tried uploading via the web interface as my goal was to have them encrytped. This is also a headless seedbox that this file is coming from. Should I try to come up with a way to try that next?

**Comment by ncw** [comment]
Can you post a log with `-vv` of the problem happening please?

**Comment by ml3000** [comment]
I am waiting for another one to fail and then ill post the log

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
