### ISSUE TITLE
Google Drive rclone mount open for read: bad response: 403: 403 Forbidden

### ISSUE THREAD

**Issue by francesco2013** [rclone/rclone#1363]
> What is your rclone version (rclone v1.36-33-g7d9faffβ)

> Which OS you are using and how many bits (eg Debian 8, 64 bit)

> Which cloud storage system are you using? (Google Drive)

> The command you were trying to run (/bin/rclone mount Gsuite_Fazionet:Plex_Media /mnt/googledrive  --buffer-size 256M --allow-other --gid 113 --uid 108 -vv --log-file /var/log/rclone-gdrive.log `)

> A log from the command with the `-vv` flag (2017/04/24 02:22:56 DEBUG : Movies/Dear John (2010) [1080p]/WWW.YIFY-TORRENTS.COM.jpg: Dir.Lookup OK
2017/04/24 02:22:56 DEBUG : Movies/Dear John (2010) [1080p]/WWW.YIFY-TORRENTS.COM.jpg: File.Attr valid=1m0s ino=0 size=130677 mode=-rw-r--r--
2017/04/24 02:22:56 DEBUG : Movies: Dir.ReadDirAll
2017/04/24 02:22:56 DEBUG : Movies: Dir.ReadDirAll OK with 1000 entries
2017/04/24 02:22:56 DEBUG : Movies/Dear John (2010) [1080p]: Dir.ReadDirAll
2017/04/24 02:22:56 DEBUG : Movies/Dear John (2010) [1080p]: Dir.ReadDirAll OK with 4 entries
2017/04/24 02:22:56 DEBUG : Movies/Dear John (2010) [1080p]/Dear.John.2010.1080p.BluRay.x264.YIFY.mp4: File.Open OpenReadOnly
2017/04/24 02:22:56 ERROR : Movies/Dear John (2010) [1080p]/Dear.John.2010.1080p.BluRay.x264.YIFY.mp4: File.Open failed: open for read: bad response: 403: 403 Forbidden
2017/04/24 02:22:56 DEBUG : Movies/Dear John (2010) [1080p]/Dear.John.2010.1080p.BluRay.x264.YIFY.mp4: File.Open OpenReadOnly
2017/04/24 02:22:56 ERROR : Movies/Dear John (2010) [1080p]/Dear.John.2010.1080p.BluRay.x264.YIFY.mp4: File.Open failed: open for read: bad response: 403: 403 Forbidden
2017/04/24 02:22:57 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]: Dir.Lookup
2017/04/24 02:22:57 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]: Dir.Lookup OK
2017/04/24 02:22:57 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]: Dir.Attr valid=1m0s ino=0 size=0 mode=drwxr-xr-x
2017/04/24 02:22:57 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]: Dir.ReadDirAll
2017/04/24 02:22:57 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]: Reading directory
2017/04/24 02:22:57 DEBUG : Google drive root 'Plex_Media': Reading "Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]/"
2017/04/24 02:22:57 DEBUG : Google drive root 'Plex_Media': Finished reading "Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]/"
2017/04/24 02:22:57 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]: Dir.ReadDirAll OK with 2 entries
2017/04/24 02:22:57 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]/Dear.Zachary.A.Letter.2008.720p.WEB-DL.DD2.0.H.264.mkv: Dir.Lookup
2017/04/24 02:22:57 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]/Dear.Zachary.A.Letter.2008.720p.WEB-DL.DD2.0.H.264.mkv: Dir.Lookup OK
2017/04/24 02:22:57 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]/Dear.Zachary.A.Letter.2008.720p.WEB-DL.DD2.0.H.264.mkv: File.Attr valid=1m0s ino=0 size=2864190861 mode=-rw-r--r--
2017/04/24 02:22:57 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]/Downloaded From PublicHD.SE.txt: Dir.Lookup
2017/04/24 02:22:57 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]/Downloaded From PublicHD.SE.txt: Dir.Lookup OK
2017/04/24 02:22:57 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]/Downloaded From PublicHD.SE.txt: File.Attr valid=1m0s ino=0 size=92 mode=-rw-r--r--
2017/04/24 02:22:57 DEBUG : Movies: Dir.ReadDirAll
2017/04/24 02:22:57 DEBUG : Movies: Dir.ReadDirAll OK with 1000 entries
2017/04/24 02:22:57 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]: Dir.ReadDirAll
2017/04/24 02:22:57 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]: Dir.ReadDirAll OK with 2 entries
2017/04/24 02:22:57 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]/Dear.Zachary.A.Letter.2008.720p.WEB-DL.DD2.0.H.264.mkv: File.Open OpenReadOnly
2017/04/24 02:22:57 ERROR : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]/Dear.Zachary.A.Letter.2008.720p.WEB-DL.DD2.0.H.264.mkv: File.Open failed: open for read: bad response: 403: 403 Forbidden
2017/04/24 02:22:58 DEBUG : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]/Dear.Zachary.A.Letter.2008.720p.WEB-DL.DD2.0.H.264.mkv: File.Open OpenReadOnly
2017/04/24 02:22:58 ERROR : Movies/Dear.Zachary.A.Letter.to.a.Son.About.His.Father.2008.720p.WEB-DL.H264-TC [PublicHD] [PublicHD]/Dear.Zachary.A.Letter.2008.720p.WEB-DL.DD2.0.H.264.mkv: File.Open failed: open for read: bad response: 403: 403 Forbidden
)

It started all of a sudden I can list the directories but I cant open the files ... it was working and it stopped. This on two different machines problem started at the same time.

Plex Cloud works on the same gdrive storage so their api requests are working .....

**Comment by francesco2013** [comment]
UPDATE: it stopped working on plex cloud too. This thing is VERY annoying. Google Drive limits ???

**Comment by ajkis** [comment]
yes your account is locked for 24h ( or less )

**Comment by francesco2013** [comment]
I have chatted with Google Drive support. That told me the following:

- Yes there is an API limit
- We dont know how high is the limit
- We dont know if only the reading API calls matter for the count or the writing too (I asked that since rclone in writing keeps on working).
- We dont know how long is a ban lasting before reset.

Pretty useless.

Any suggestion for a rclone mount con Gdrive (I use it with Plex Server) ?
Which parameters are the best to save api calls ? 

Thanks.

**Comment by animosity22** [comment]
You can't really until the metadata items are addressed and the directory structure can be cached:

https://github.com/ncw/rclone/issues/1337

**Comment by francesco2013** [comment]
thanks animosity22

**Comment by animosity22** [comment]
This was solved with the later versions. Closing out.
