### ISSUE TITLE
Google Drive Mount oauth2 token expired

### ISSUE THREAD

**Issue by tieubao81** [rclone/rclone#1364]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.36-DEV
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux CentOS-7 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -v mount --allow-non-empty --allow-other --max-read-ahead 200M --drive-chunk-size 128M --checkers 40 --dir-cache-time 30m --transfers=32 gdrive:/Media /home/plex/media
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2017/04/23 17:49:51 DEBUG : rclone: Version "v1.36-DEV" starting with parameters ["rclone" "-vv" "mount" "--allow-non-empty" "--allow-other" "--max-read-ahead" "200M" "--drive-chunk-size" "128M" "--checkers" "40" "--dir-cache-time" "30m" "--transfers=32" "gdrive:/Media" "/home/plex/media"]
2017/04/23 17:49:51 Failed to create file system for "gdrive:/Media": couldn't read info about Drive: Get https://www.googleapis.com/drive/v2/about?alt=json: oauth2: token expired and refresh token is not set

I've authorized everything correctly, but every time I mount the google drive, it gives me that error. The same setup worked on a previous Ubuntu machine running rclone 1.35. Please advise. Thank you.

**Comment by azureblaze** [comment]
Try `rclone config` choose edit,  select the remote, skip until you get to token refresh, then choose to refresh token, save and it should work.

**Comment by animosity22** [comment]
This was solved with the linked issue.
