### ISSUE TITLE
[BUG] sync not modifying mod times on destination to match source.

### ISSUE THREAD

**Issue by ajkis** [rclone/rclone#1365]
version: rclone v1.36-22-gbc25190β
command: `rclone sync acd: gdrive: `

I recently copied my 60TB library from acdUK to acdDE , the acd library is sycned with my gdrive. 
After successful `rclone sync acdUK: acdDE: ` and  `rclone check acdUK: acdDE: ` I synced l `rclone sync acd: gdrive: ` and I noticed my modify times on gdrives do not match with acd.

Iam pretty sure that this worked before and it got broken with one of the recent beta's. 

@ncw is there a way to set modify ( and other dates ) on gdrive to match the ones i have on ACD.

**Comment by ajkis** [comment]
UPDATE:

Syncing new files from acd to gdrive matches the mod times, but not for already existing ones. 
I would also add that folder times do not match even for new synced files.

**Comment by ncw** [comment]
ACD doesn't support mod times.  What you get instead is the uploaded time.  So when you copied from acdUK to acdDE the mod times will have changed.

Does that explain it?

**Comment by ajkis** [comment]
@ncw yes thats not the problem

The problem is that when syncing my new ACD drive with current GDRIVE the mod times on GDRIVE should match with new ACD. ( they do for new files, but not for existing ones )

**Comment by ncw** [comment]
acd doesn't support mod times, and rclone knows that when copying from acd to drive it shouldn't rely on the mod times, so it won't update the mod time if it is different.

However when rclone copies the file for the first time it does use the mod time as it really doesn't have anything else to go on.

**Comment by ajkis** [comment]
Can you make it so that rclone set on gdrive same times so they match acd. ( acd supports create time and that one is matching modify/changed ) 

The point of sync would be to have exactly same content with same stats 
eg` rclone sync acd: gdrive:` should produce same values for stat `/mnt/acdcrypt/movies/ file.mkv` `/mnt/gdrivecrypt/movies/file.mkv`

Its understandable that it cant be done other way eg if you `rclone sync gdrive: acd:`.

I also noticed that even with new syncs the FOLDERS dates do not match.

**Comment by ajkis** [comment]
post with example here: https://forum.rclone.org/t/ncw-sync-acd-gdrive-can-we-match-folders-file-time-dates-for-new-and-existing/2030

**Comment by qnorsten** [comment]
I actually do not know what the best way of handling this. As some people might upload to Gdrive and actually want to preserv the correct mod-times (as rclone handles it now). While some others especially those that uses it for plex would like the gdrive mod-times to be updated and matched to the acd mod-times.  Perhaps an extra optional flag is needed to specify how you want to handle this?

**Comment by ajkis** [comment]
@qnorsten I dont get the confusion you want sync to match times between source and destination and we there is a flag `--no-update-modtime  `   Don't update destination mod-time if files identical.

It does not really matter if Amazon dont support mod times when it set as source, the destination should always match same folder/files/times.

For example:
On server 1 
sync /local/ acd:  
On server 2
sync acd: gdrive 
On server  3
sync gdrive:  /local/ 

One would assume that files/folder and times are same on or my local drives but thats not the case., so I dont get what is the point of current process ?

If for some reason someone would like to match original timestamps from cloud that supports it the flag is there, if they want to have synced files eg identical in all ways then they dont use existing flag.

**Comment by qnorsten** [comment]
I forgot about --no-update modtime. Then I am on your side @ajkis :)
