### ISSUE TITLE
[BUG] ACD mount with latest version 

### ISSUE THREAD

**Issue by ajkis** [rclone/rclone#1372]
Some weird stuff happened yesterday,  after I restarted my server I could not mount acd (gdrive mounted normally ) with latest rclone version.

I was trying for more then 20 minutes and it kept looping 
`DEBUG : rclone: Version "v1.36-41-gb651784β" finishing with parameters .`

I thought the problem is in my default 5s timeouts so in log bellow i raised it. to 60.
When I replaced rclone with x.22 version the mount worked.
I tried again with x.41 version and had same problem again.
Not sure what changed in last few versions.

> 2017/04/25 21:00:26 DEBUG : rclone: Version "v1.36-41-gb651784β" finishing with parameters ["rclone" "mount" "--read-only" "--allow-other" "--a                     cd-templink-threshold" "0" "--stats" "30s" "--buffer-size" "1G" "--timeout" "60s" "--contimeout" "60s" "-vv" "--log-file=/home/plex/logs/mounta                     cdcrypt.log" "acdcrypt:" "/mnt/acdcrypt"]
> 2017/04/25 21:00:43 DEBUG : rclone: Version "v1.36-41-gb651784β" starting with parameters ["rclone" "mount" "--read-only" "--allow-other" "--ac                     d-templink-threshold" "0" "--stats" "30s" "--buffer-size" "1G" "--timeout" "60s" "--contimeout" "60s" "-vv" "--log-file=/home/plex/logs/mountac                     dcrypt.log" "acdcrypt:" "/mnt/acdcrypt"]
> 2017/04/25 21:01:02 DEBUG : rclone: Version "v1.36-41-gb651784β" starting with parameters ["rclone" "mount" "--read-only" "--allow-other" "--ac                     d-templink-threshold" "0" "--stats" "30s" "--buffer-size" "1G" "--timeout" "60s" "--contimeout" "60s" "-vv" "--log-file=/home/plex/logs/mountac                     dcrypt.log" "acdcrypt:" "/mnt/acdcrypt"]
> 2017/04/25 21:02:02 DEBUG : rclone: Version "v1.36-22-gbc25190β" starting with parameters ["rclone" "mount" "--read-only" "--allow-other" "--ac                     d-templink-threshold" "0" "--stats" "30s" "--buffer-size" "1G" "--timeout" "60s" "--contimeout" "60s" "-vv" "--log-file=/home/plex/logs/mountac                     dcrypt.log" "acdcrypt:" "/mnt/acdcrypt"]
> 2017/04/25 21:02:17 INFO  : Encrypted amazon drive root 'crypt': Modify window not supported
> 2017/04/25 21:02:17 DEBUG : Encrypted amazon drive root 'crypt': Mounting on "/mnt/acdcrypt"
> 2017/04/25 21:02:17 DEBUG : Encrypted amazon drive root 'crypt': Root()
> 2017/04/25 21:02:32 DEBUG : : Dir.Attr valid=1m0s ino=0 size=0 mode=drwxr-xr-x
> 2017/04/25 21:02:32 DEBUG : : Dir.ReadDirAll
> 2017/04/25 21:02:32 DEBUG : : Reading directory

**Comment by calisro** [comment]
Mine is mounting ok with that version.   Not saying there isn't a problem but things seem okay here.

rclone -V
rclone v1.36-41-gb651784β

**Comment by ajkis** [comment]
Its weird, i think it was fluke that instantly remounted with old version.
Had same problems today with x.22 version and i redownloaded latest one

When mount is run its timing out on getting nodes ( and i raised timeouts from 5s to 60s for testing )
The main problem is that OS shows drive as mounted but accessing any files causes huge timeout and not instant error.
eg if you do `stat /mnt/acdcrypt/testfile`  it will wait for long time before reporting any error. same goes if you try to list folders. 

From log (same with latest version):
2017/04/26 20:05:38 DEBUG : rclone: Version "v1.36-22-gbc25190Î˛" starting with parameters ["rclone" "mount" "--read-only" "--allow-other" "--acd-templink-threshold" "0" "--stats" "30s" "--buffer-size" "1G" "--timeout" "60s" "--contimeout" "60s" "-vv" "--log-file=/home/plex/logs/mountacdcrypt.log" "acdcrypt:" "/mnt/acdcrypt"]
2017/04/26 20:05:44 DEBUG : pacer: Rate limited, sleeping for 287.113937ms (1 consecutive low level retries)
2017/04/26 20:05:44 DEBUG : pacer: low level retry 1/10 (error Get https://cdws.eu-west-1.amazonaws.com/drive/v1/nodes?filters=kind%3AFOLDER+AND+isRoot%3Atrue: read tcp 84.xx.xx.46:57962->54.239.39.139:443: i/o timeout)
2017/04/26 20:05:49 DEBUG : pacer: Rate limited, sleeping for 1.331776148s (2 consecutive low level retries)
2017/04/26 20:05:49 DEBUG : pacer: low level retry 2/10 (error Get https://cdws.eu-west-1.amazonaws.com/drive/v1/nodes?filters=kind%3AFOLDER+AND+isRoot%3Atrue: net/http: TLS handshake timeout)
2017/04/26 20:05:54 DEBUG : pacer: Rate limited, sleeping for 2.760398084s (3 consecutive low level retries)
2017/04/26 20:05:54 DEBUG : pacer: low level retry 3/10 (error Get https://cdws.eu-west-1.amazonaws.com/drive/v1/nodes?filters=kind%3AFOLDER+AND+isRoot%3Atrue: read tcp 84.xx.xx.46:57968->54.239.39.139:443: i/o timeout)
2017/04/26 20:05:54 DEBUG : pacer: Resetting sleep to minimum 20ms on success

**Comment by seuffert** [comment]
i had very much the same experience the last days. 
(see https://forum.rclone.org/t/acd-429-too-many-requests/1792/232?u=seuffert)

acd keeps getting very slow (http request response time) during the evening :(

**Comment by ncw** [comment]
The `--timeout` flag is an idle timeout, so if whatever you are doing might pause reading the data then you want to set the timeout bigger than that pause.

Looking at your log, those timeouts all appear to be Amazon misbehaving :-(

**Comment by seuffert** [comment]
OMG

```
httping -l -G -c 3 "https://cdws.eu-west-1.amazonaws.com/drive/v1/nodes?filters=ki                                              nd%3AFOLDER+AND+isRoot%3Atrue"
PING cdws.eu-west-1.amazonaws.com:443 (/drive/v1/nodes?filters=kind%3AFOLDER+AND+isRoot%3Atrue):
connected to 54.239.32.36:443 (375 bytes), seq=0 time=49972.44 ms
connected to 54.239.34.70:443 (375 bytes), seq=1 time=22705.82 ms
connected to 54.239.32.36:443 (375 bytes), seq=2 time=59308.86 ms
--- https://cdws.eu-west-1.amazonaws.com/drive/v1/nodes?filters=kind%3AFOLDER+AND+isRoot%3Atrue ping statistics ---
3 connects, 3 ok, 0.00% failed, time 134989ms
round-trip min/avg/max = 22705.8/43995.7/59308.9 ms
```

**Comment by ajkis** [comment]
So average roundtrip 40 seconds ..
Iam seriously considering blocking all "slow" IP's to amazon.

**Comment by animosity22** [comment]
ACD is not with us anymore. Closing out.
