### ISSUE TITLE
rclone not trasnferring newly modified files

### ISSUE THREAD

**Issue by rpgdev** [rclone/rclone#1382]
I was downloading several related torrents that I put in the same folder for better organization (each torrent was a folder with many files). Not all the torrents completed at the same time but since I didn't want to issue a copy/sync command individually for each folder I just copied the entire folder to ACD (this was before I was familiar with the --exclude-from option, which would've been the best way to go), trusting that when the remaining torrents completed I could just issue another copy/sync command on the same folder and only the newly completed files would make it through to acd and replace the incomplete files but that's not what's happening. The unfinished torrents have finished downloading now (weeks after I first issued the aforementioned copy command) and issuing a sync or copy command is not transferring _anything_ to acd. It's very likely that all the incomplete files had already been transferred to acd with the same filesize they have now since partially downloading them seems to allocate the full filesize under my current torrent client settings but the checksum should definitely be different as well as the modified time. I tried using the -c option with no luck. Is there another option I could try? I didn't delete any of the original files (the ones that finished downloading quickly) so I could just transfer all the files all over again but I wish to learn why rclone is not behaving the way I expect it to. I already done this before (transferring before all torrents had finished, issuing another copy/sync command after) and new files seem to have been transferred, to find out now that some files might have been left out after all is troubling :/

> What is your rclone version (eg output from `rclone -V`)
1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian 8.7

> Which cloud storage system are you using? (eg Google Drive)
Amazon clouddrive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy and/or sync

**Comment by calisro** [comment]
ACD can use chksum "-c" to check the local vs remote consistency except if you are using crypt.  Are you using crypt?  If you are using crypt, it only goes by file size and thus your problem.  I believe you can run rclone cryptcheck local: remote: and that would identify any problems you have.  Then you can output that list and sync up those files.

**Comment by rpgdev** [comment]
That's _very important_ information that should be featured more prominently. God knows the amount of incomplete files I have on there now. Christ.

**Comment by calisro** [comment]
https://rclone.org/amazonclouddrive/

Modified time and MD5SUMs
Amazon Drive doesn’t allow modification times to be changed via the API so these won’t be accurate or used for syncing.

https://rclone.org/crypt/


Modified time and hashes
Crypt stores modification times using the underlying remote so support depends on that.

Hashes are not stored for crypt. However the data integrity is protected by an extremely strong crypto authenticator.

Note that you should use the rclone cryptcheck command to check the integrity of a crypted remote instead of rclone check which can’t check the checksums properly.

**Comment by calisro** [comment]
It should be easy to fix.  Just run a rclone cryptcheck.  Grab the list of files output about differing hashes and then put them in a file and then you can do a normal sync using the "--files-from" flag as an input to replace those files or just delete them and readd them.

**Comment by rpgdev** [comment]
Thanks for the suggestion. I just did the sync command again and in the future I'll just won't do what I did here. Not feasible for me to find out the several incomplete files I have on acd now from older sync/copy commands but it really sucks that this is how it turns out to be.

**Comment by calisro** [comment]
There are enhancement requests to add chksum to crypt. When that pans out, this will be addressed. You may want to close this issue if it's resolved.

**Comment by rpgdev** [comment]
Sorry to come back to this again but is the same true for copying files from encrypted remote to my server? Meaning that if I stop a copy command before it finishes all the incomplete files are going to be skipped when I reissue the command?

**Comment by calisro** [comment]
They wont be skipped because it will go by the file size.

**Comment by animosity22** [comment]
This looks answered. If you still have a question, please feel free to post on the forums.
