### ISSUE TITLE
RClone is acting silently

### ISSUE THREAD

**Issue by tim-m89** [rclone/rclone#1389]
I've got a couple of bash script wrappers around rclone. It is actually running on windows via the bash the comes with git for windows.

```bash
#!/bin/bash

declare -a paths=(
  "PathA/"
  "PathB/"
  )
for i in "${paths[@]}"
do
  /c/rclone-v1.36-windows-amd64/rclone sync "//nasbox/$i" "b2:bucket-name/$i" >> b2-sync-nasbox.log 2>&1
done
```

Since switching from rclone v1.35 to v1.36, it now makes no output at all on stdout or stderr, though appears to otherwise be syncing.

I upgraded as I was encountering issue #825, for which I probably wouldn't have known it was happening if v1.35 was also silent.

**Comment by PrinceShaji** [comment]
I have the same issue. It's hard to say if rclone is uploading or is stuck.

**Comment by azureblaze** [comment]
add --verbose=1, rclone defaults to very little output as of 1.36 onwards

**Comment by ajkis** [comment]
-v and -vv for whole log.

**Comment by ncw** [comment]
> Since switching from rclone v1.35 to v1.36, it now makes no output at all on stdout or stderr, though appears to otherwise be syncing.

I changed the defaults for rclone do be less noisy to bring it into line with rsync.

This confused a lot of people, so I apologise!

Using the `-v` flag will bring back the previous behavior more or less.

**Comment by carbolymer** [comment]
I have the same issue, but when running in cron. `-v` nor `-vv` does not help, I had to execute rclone through bash:
```
/bin/bash -c "rclone sync -v resource:name directory &>>/var/log/synclog.log"
```
then it starts to output to a file...

**Comment by ncw** [comment]
> I have the same issue, but when running in cron. `-v` nor `-vv` does not help, I had to execute rclone through bash:

Note that rclone outputs its logs to stderr which may make a difference when running it under cron.

**Comment by carbolymer** [comment]
>Note that rclone outputs its logs to stderr which may make a difference when running it under cron.

But even `&>>` does not work here.

**Comment by ncw** [comment]
> But even `&>>` does not work here.

Are you sure crontab is using bash to run the command?  `&>>` is a bash-ism.  I suspect crontab is using `/bin/sh` instead.

So try `>>file 2>&1` which should work in `/bin/sh`.

**Comment by animosity22** [comment]
This looks answered. If you still have a question, please feel free to post on the forums.
