### ISSUE TITLE
rclone 1.36 uses more memory than 1.35 (memory leak?)

### ISSUE THREAD

**Issue by lickdragon** [rclone/rclone#1391]
Hi,
  After switching to rclone 1.36 (--backup-dir switch is great!), rclone slowly consumes more and more memory.
  I am slowly backing up around 500GB of files to google drive.
  In the screenshot attached rclone 1.35 is running until about April 22nd.  The swap usage is low and constant.
  Around April 23rd, I switch to using rclone 1.36.  You can see the swap usage rising fairly steadily over the days.  Every time there is a drop in swap usage, that is rclone being restarted.  Soon after starting rclone again, swap is being used again.
  I'm guessing rclone 1.36 has a memory leak that 1.35 did not have. 
  I'll test the most recent beta next...

Debian Jessie 64 bit
google drive

rclone sync -v --config /scratch/rclone.creds  /srv/ gdrive-backups2_o:backups/smb02.physics.wisc.edu_srv/9999-mostrecent/

![screenshot_20170505_083759](https://cloud.githubusercontent.com/assets/9353776/25748023/3f89dc58-316f-11e7-9105-dd880bdfd1d7.png)

**Comment by calisro** [comment]
Could it be  
 --buffer-size int                   Buffer size when copying files. (default 16M)

contributing to linux filesystem cache?  file system cache would get flushed if needed anyway by linux.

**Comment by lickdragon** [comment]
Hi,

> Could it be
> --buffer-size int Buffer size when copying files. (default 16M)

I'm not sure if you're asking me this question, but I haven't used the 
--buffer-size switch in either 1.35 or 1.36.  (Maybe defaults have changed?)

**Comment by calisro** [comment]
Well.  that parameter was only introduced in 1.36.  So my point was that it defaults to use 15M per.  Turn it off and see what happens:
--buffer-size 0

**Comment by ncw** [comment]
How many files are there in the sync?

Your graph is of swap usage - did you actually measure the memory usage of rclone?

Here is my basic memory logger.  Save it in a file called `memusage` and then run `memusage rclone` and it will log the memory usage once per second.  You might want to change the sleep to 60 if you are running it for ages.

```
#!/bin/sh
# Monitor memory usage of the given command

COMMAND="$1"

if [ "$COMMAND" = "" ]; then
   echo "Syntax: $0 command"
   exit 1
fi

headers=""
while [ 1 ]; do
    ps $headers -C "${COMMAND}" -o pid,rss,vsz,cmd
    sleep 1
    headers="--no-headers"
done
```

**Comment by lickdragon** [comment]
> --buffer-size 0

OK, I'll test that!
C.

**Comment by lickdragon** [comment]
> How many files are there in the sync?

The number of files has not changed much between rclone 1.35 and 1.36.
Currently number of files is 2,894,318 .
Not sure what the largest directory is, if that matters.

> Your graph is of swap usage - did you actually measure the memory usage
> of rclone?

Here is the output of 'memusage' a long running (since May 5th) rclone:

   PID   RSS    VSZ CMD
  2837 1617616 3020064 /usr/local/bin/gdrive/rclone sync -v --config 
/scratch/rclone.creds /srv/ gdrive-backu

**Comment by lickdragon** [comment]
> Well. that parameter was only introduced in 1.36. So my point was that
> it defaults to use 15M per. Turn it off and see what happens:
> --buffer-size 0

Sadly, this was hot the fix.

**Comment by lickdragon** [comment]
I'm trying to git bisect this problem.  I would like to download the 
precompiled binary.  How does one determine the "commit number"?

{Version Tag}-{Commit Number}-g{Git Commit Hash}
e.g.
v1.36-{Commit Number}-gf87a694

Thanks!
C

**Comment by unnfav** [comment]
> I'm trying to git bisect this problem.  I would like to download the
precompiled binary.

https://beta.rclone.org

**Comment by ncw** [comment]
@lickdragon wrote
> Sadly, this was hot the fix.

Do you mean setting `-buffer-size 0` was the solution? Or wasnt?

> I'm trying to git bisect this problem.  I would like to download the
precompiled binary.  How does one determine the "commit number"?

The commit numbers are shown in the [git log](https://github.com/ncw/rclone/commits/master).  Note it is only the first few (6?) digits of the full commit hash in the zip file names.

@unnfav is probably right though the easiest way will be to go through the available binaries at https://beta.rclone.org and bisect from that list.

**Comment by lickdragon** [comment]
--buffer-size 0  was not the fix.

Therefore I would like to git bisect the commits.

The format of the download URL is

https://beta.rclone.org/{Version Tag}-{Commit Number}-g{Git Commit 
Hash}/rclone-{Version Tag}-{Commit Number}-g{Git Commit 
Hash}-linux-amd64.zip

As I said, I know the git hash:
f87a694

I can guess the version tag:
v1.35 (or v1.36)

But I do not know how to determine the "commit number".  beta.rclone.org 
does not list all commits/downloads. f87a694 does not appear.  (Maybe 
I'll write a script which tries commit numbers starting at 00 and counts 
upwards until it successfully downloads a binary?)

Thanks!
C.

**Comment by lickdragon** [comment]
Hi all,
   'git bisect' shows that the first bad commit is "update vendor 
directory" 1cad759306ff117cfb9bd9339db543b91e0738e9.
   So, looks like not rclone code itself which is ballooning memory 
usage. :) :(

C.

**Comment by ncw** [comment]
I added a FAQ entry about memory use

### Rclone is using too much memory or appears to have a memory leak

Rclone is written in Go which uses a garbage collector.  The default
settings for the garbage collector mean that it runs when the heap
size has doubled.

However it is possible to tune the garbage collector to use less
memory by [setting GOGC](https://dave.cheney.net/tag/gogc) to a lower
value, say `export GOGC=20`.  This will make the garbage collector
work harder, reducing memory size at the expense of CPU usage.

The most common cause of rclone using lots of memory is a single
directory with thousands or millions of files in.  Rclone has to load
this entirely into memory as rclone objects.  Each Rclone object takes
0.5k-1k of memory.

**Comment by animosity22** [comment]
This looks answered. If you still have a question, please feel free to post on the forums.
