### ISSUE TITLE
make fails on source.tar.gz

### ISSUE THREAD

**Issue by ole-tange** [rclone/rclone#1395]
Building from .tar.gz fails:

    $ wget https://github.com/ncw/rclone/archive/v1.36.tar.gz
    $ tar xvf v1.36.tar.gz
    $ cd rclone-1.36/
    fatal: Not a git repository (or any parent up to mount point /mnt/4tb)
    Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
    fatal: Not a git repository (or any parent up to mount point /mnt/4tb)
    Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
    fatal: Not a git repository (or any parent up to mount point /mnt/4tb)
    Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
    touch fs/version.go
    go install -v --ldflags "-s -X github.com/ncw/rclone/fs.Version=-"../../../go/src/github.com/ncw/rclone/fs/config.go:6:2: cannot find package "bufio" in any of:
        /mnt/4tb/home/tange/go/src/github.com/ncw/rclone/vendor/bufio (vendor tree)
        /mnt/4tb/home/tange/go/src/bufio (from $GOROOT)
        /mnt/4tb/home/tange/tmp/rclone/src/bufio (from $GOPATH)
    [... lot of other missing packages/errors ...]

I had expected either the system would build or it would tell me how to install the missing packages. This information could also be in the file INSTALL.

May I suggest you try building on a newly installed distribution? This will make it clear which packages and software you depend on for building. Then document this in INSTALL or make the makefile more intelligent.

**Comment by ncw** [comment]
This isn't a supported way of building rclone.

The recommended way of installing rclone from source is documented [in the install docs](https://rclone.org/install/#install-from-source).

You can use the makefile to build rclone, but you need to set it up as a go project first, in the right filesystem heirachy and with GOPATH set.

**Comment by animosity22** [comment]
This looks answered. If you still have a question, please feel free to post on the forums.
