### ISSUE TITLE
Use single time format

### ISSUE THREAD

**Issue by ole-tange** [rclone/rclone#1397]
In .config/rclone/rclone.conf ISO8601 time format is used:

    token = {"access_token":"xxxxxxxxxxxxxxxxxxxxxxxxxx","token_type":"Bearer","refresh\
_token":"xxxxxxxxxxxxxxxxxxx","expiry":"2017-05-07T13:18:51.969806063+02:00"}

but `-vv` does not use the same time format:

    2017/05/07 12:31:08 INFO  : src/github.com/ncw/rclone/vendor/github.com/aws/aws-sdk-go/aws/awsutil/string_value.go: Copied (new)

Consider using a single time format everywhere.

**Comment by azgul** [comment]
You can't compare the two. The expiry time for the access token needs to to have the timezone or rclone cannot know when to refresh it. It's likely just the raw json rclone gets after authorization with google/acd etc.

And the latter is a humanly readable, easy on the eyes format for logging.

**Comment by ole-tange** [comment]
Obligatory XKCD reference: https://xkcd.com/1179/

**Comment by breunigs** [comment]
something like this works:
```
diff --git a/fs/log.go b/fs/log.go
index b2b60d35..f10c42fd 100644
--- a/fs/log.go
+++ b/fs/log.go
@@ -9,6 +9,7 @@ import (
        "reflect"
        "runtime"
        "strings"
+ "time"
 )
 
 // LogLevel describes rclone's logs.  These are a subset of the syslog log levels.
@@ -65,6 +66,8 @@ var (
 // logPrint sends the text to the logger of level
 var logPrint = func(level LogLevel, text string) {
        text = fmt.Sprintf("%-6s: %s", level, text)
+ log.SetFlags(0)
+ log.SetPrefix(time.Now().Format("2006-01-02 15:04:05") + " ")
        log.Print(text)
 }
```
Although you might want to bring this up with the Go authors why they did not choose ISO 8601. I'd be curious myself, since the order they chose is `y/m/d`, too…

**Comment by animosity22** [comment]
This looks answered. If you still have a question, please feel free to post on the forums.
