### ISSUE TITLE
Sync Issue (syncing files multiple times)

### ISSUE THREAD

**Issue by spencercharest** [rclone/rclone#1400]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.36-49-g5135ff7β
(also tried 1.36 and 1.35)
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 14.04 64 bit
> Which cloud storage system are you using? (eg Google Drive)
Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync google-crypt: googleorg-crypt: 
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Hi @ncw, I'm having an issue with rclone sync. I am using sync to keep two separate Google Drive accounts in sync and there is a set of about 25 files that get copied every time sync is run (I'm sure that they already exist on the destination directory). The files are about 20GB each so it is pretty time and resource intensive when they are copied. Interestingly enough, I'm pretty sure all of these files were uploaded originally at the same time. Could this maybe be an issue of a corrupted upload? I didn't include a verbose log because I'd prefer to keep that info private.

**Comment by calisro** [comment]
When i've had this happen, they were listed as duplicates.  I found it would never recover but if I deleted BOTH versions of the duplicates, i didnt see the problem anymore.   You can use the rclone dedupe to determine if the ones you are having issues with have duplicates.  Even if they don't, try deleting the singular version before the sync and then resync again to verify the problem is gone.

**Comment by ncw** [comment]
Excellent suggestion from @calisro :-) 

If it doesn't bear fruit, then please paste some logs with `-vv` which will show the exact reasons rclone wanted to copy the files.

**Comment by animosity22** [comment]
This looks answered. If you still have a question, please feel free to post on the forums.
