### ISSUE TITLE
403'ing When Copying to Crypt Mount

### ISSUE THREAD

**Issue by Kolmain** [rclone/rclone#1405]
When I try to `rclone sync` or `rclone copy` from 1 standard remote to 1 crypt remote (can be same drive or different) all transfers get 403'd.

> What is your rclone version (eg output from `rclone -V`)

v1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.10/17.04 64bit

> Which cloud storage system are you using? (eg Google Drive)

GSuite and EDU Google Drives

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone copy UnencryptedRemote: EncryptedRemote:` 
`rclone sync UnencryptedRemote: EncryptedRemote:`

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

`2017/05/12 19:47:28 ERROR : /path/to/file.txt Failed to copy: failed to open source object: bad response: 403: 403 Forbidden`

**Comment by calisro** [comment]
24 hour ban from Google.  That's all

**Comment by Kolmain** [comment]
@calisro Isn't a 24 hour ban- the drives still work from other VMs and this has happened for days.

**Comment by ncw** [comment]
You'll have to post a bit more of the log with `-vv`.  Do you see any low level retries before the error?

**Comment by animosity22** [comment]
This looks answered. If you still have a question, please feel free to post on the forums.
