### ISSUE TITLE
serve/http writable remote with local dir as backend

### ISSUE THREAD

**Issue by vtolstov** [rclone/rclone#1418]
I need to export from one server dir, and on clients mount it via rclone to local dir.
In readonly case i'm already have http support, but for writable case we need some proto.
@ncw what do you think about utilizing POST/PUT/PATCH http methods for this?
For writing we need create file/dir, remove file/dir, modify file. As i think POST/PUT/PATCH suitable for this.

**Comment by ncw** [comment]
rclone now can `rclone serve webdav` which should fill the need for a writable remote over http.

**Comment by vtolstov** [comment]
@ncw thanks!
