### ISSUE TITLE
I get an error trying to use the new FTP functionality

### ISSUE THREAD

**Issue by rhummelmose** [rclone/rclone#1433]
[20:01:39] rhummelmose:rclone-v1.36-120-ga9d29c22β-osx-amd64 $ ./rclone lsd Bitport:
2017/05/22 21:06:10 directory not found

**Comment by sjurtf** [comment]
I just tested the same build with FTP using a non-standard port for #1434 and tested the functionality of the remote with lsd.

It worked as expected.
I used build `rclone-v1.36-124-ge75db0b1β-osx-amd64`

Please provide your FTP remote config and try issuing the rclone command with -vv to provide this issue with more details.

**Comment by ncw** [comment]
@rhummelmose Which FTP server are you testing with?

You might need to put some path in front of `Bitport:` eg `Bitport:/home/username` maybe - or you could put that in the configuration URL.

**Comment by animosity22** [comment]
This looks answered. If you still have a question, please feel free to post on the forums.
