### ISSUE TITLE
[Feature request] Size option for (lsd) command

### ISSUE THREAD

**Issue by MrFr1day** [rclone/rclone#1436]
Hi,

Is it reasonably possible to add a size option to the 'lsd' command? Instead of listing, then issuing a separate 'size' command for each sub directory.

Thanks.

**Comment by ncw** [comment]
For remotes that support it (not many, swift is an example) `rclone lsd` shows the count  already.

I have written (but not merged yet) an [ncdu](https://en.wikipedia.org/wiki/Ncdu) clone for rclone which is probably exactly what you want for an interactive way of answering the question, "what is using all my data?"

**Comment by ncw** [comment]
`rclone ncdu` is merged now and is a great tool for this kind of thing!
