### ISSUE TITLE
Renaming remote does not update config

### ISSUE THREAD

**Issue by AnthonyTTaylor** [rclone/rclone#1448]
Testing on newest built : https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

Rclone 1.36-windows
Windows 10 64bit
Google Drive
rclone config > Rename Remote

When naming a config to "gsuit Remote" then renaming to gsuitRemote
I was givng errors saying that
"2017/05/27 11:38:41 Failed to create file system for "gsuitRemote:test/": didn't find section in config file"

When checking, the names were correct

Name                 Type
====                 ====
gsuitRemote

But would not work,

After deleting the remote, and starting fresh with "qsuitRemote" to start, everything worked as expected.

**Comment by ncw** [comment]
I tried to reproduce this, but failed, by

  * running rclone config
  * renaming an existing remote
  * quitting rclone config
  * examining the config file to see if the change was correct - it was

What did you do differently to that?

**Comment by AnthonyTTaylor** [comment]
I will check when I return home,
Did you try with a remote name containing a space?

I think that is where the issue is.

**Comment by ncw** [comment]
I just tried with a space too, but still worked!

**Comment by animosity22** [comment]
This looks fixed. Closing out.
