### ISSUE TITLE
[Google Drive] Sizes differ

### ISSUE THREAD

**Issue by igoreshkas** [rclone/rclone#1450]
2017/05/26 12:15:08 DEBUG : rclone: Version "v1.36-136-g5455d34fОІ" starting with parameters ["rclone" "--exclude-from" "/backup/googledrive/targemmain/scripts/exclude.conf" "-vv" "--delete-before" "--drive-full-list=false" "--config" "/backup/googledrive/targemmain/scripts/rclone.conf" "--log-file" "/backup/googledrive/targemmain/log/rclone-2017-05-26-12.txt" "sync" "targemmain:" "/backup/googledrive/targemmain/current/"]
2017/05/26 12:15:09 INFO  : Local file system at /backup/googledrive/targemmain/current: Modify window is 1ms
2017/05/26 12:15:09 INFO  : Waiting for deletions to finish
2017/05/26 12:15:09 DEBUG : Google drive root '': Reading ""
2017/05/26 12:15:09 DEBUG : Google drive root '': Finished reading ""
...
2017/05/26 12:22:20 DEBUG : Targem Root/Welcome targem games/РќРѕРІР°СЏ РїРѕР»РёС‚РёРєР° FileExchange 2017.docx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/05/26 12:22:20 DEBUG : Targem Root/Welcome targem games/РќРѕРІР°СЏ РїРѕР»РёС‚РёРєР° FileExchange 2017.docx: Unchanged skipping
2017/05/26 12:22:20 DEBUG : Targem Root/Welcome targem games/РљР°Р»РµРЅРґР°СЂСЊ РґРѕСЃС‚СѓРїРЅРѕСЃС‚Рё РѕС„РёСЃР°, Рё СЂР°Р±РѕС‚РѕСЃРїРѕСЃРѕР±РЅРѕСЃС‚Рё СЃРµСЂРІРёСЃРѕРІ 1-9 РњР°СЏ 2017.xlsx: Sizes differ
2017/05/26 12:22:20 DEBUG : Targem Root/Welcome targem games/ TamTam.docx: Unchanged skipping
2017/05/26 12:22:20 DEBUG : Targem Root/Welcome targem games/РњР°РЅС‚РёСЃ РєР°Рє РѕС‚РјРµС‡Р°С‚СЊ РІ Р·Р°РґР°С‡Р°С… РїРѕС‚СЂР°С‡РµРЅРЅРѕРµ РІСЂРµРјСЏ.docx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/05/26 12:22:20 DEBUG : Targem Root/Welcome targem games/РњР°РЅС‚РёСЃ РєР°Рє РѕС‚РјРµС‡Р°С‚СЊ РІ Р·Р°РґР°С‡Р°С… РїРѕС‚СЂР°С‡РµРЅРЅРѕРµ РІСЂРµРјСЏ.docx: Unchanged skipping
2017/05/26 12:22:20 DEBUG : Targem Root/Welcome targem games/Links.xlsx: Sizes differ
...
2017/05/26 12:22:38 DEBUG : Targem Root/Projects/Etherlords Online/Etherlords Online - Private Tasks (10.02.2014).docx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/05/26 12:22:38 DEBUG : Targem Root/Projects/Etherlords Online/Etherlords Online - Private Tasks (10.02.2014).docx: Unchanged skipping
2017/05/26 12:22:38 DEBUG : Targem Root/Projects/Etherlords Online/Etherlords Online - Summary (03.02.2014).docx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/05/26 12:22:38 DEBUG : Targem Root/Projects/Etherlords Online/Etherlords Online - Summary (03.02.2014).docx: Unchanged skipping

**Comment by ncw** [comment]
What is the problem you are seeing?

    2017/05/26 12:22:20 DEBUG : Targem Root/Welcome targem games/Links.xlsx: Sizes differ
.
Is a normal debug message which indicates the size of something has changed and needs transferring.

**Comment by igoreshkas** [comment]
6159:2017/05/26 12:26:58 ERROR : Targem Root/PR реклама коммьюнити  эвенты/Star Conflict/(Акция на выходные) Бонусы на лояльность и скидки на контейнеры с редкими ресурсами.docx: corrupted on transfer: sizes differ 799331 vs 0
16137:2017/05/26 12:34:06 ERROR : Targem Root/Projects/SCM/Sharing to Phones/stickers/iphone/File_000.png: corrupted on transfer: sizes differ 303513 vs 304163
34170:2017/05/26 12:49:55 ERROR : Targem Root/Projects/SCM/Sharing to Phones/stickers/iphone/File_000.png: corrupted on transfer: sizes differ 430423 vs 525223
35172:2017/05/26 12:50:10 ERROR : Targem Root/PR реклама коммьюнити  эвенты/Star Conflict/Новости/Скидка дня 50% на детали к кораблю Karud.docx: corrupted on transfer: sizes differ 601837 vs 664002
36398:2017/05/26 12:52:16 ERROR : Attempt 2/3 failed with 2 errors and: corrupted on transfer: sizes differ 601837 vs 664002
43732:2017/05/26 13:03:18 ERROR : Targem Root/PR реклама коммьюнити  эвенты/Star Conflict/(Акция на выходные) Бонусы на лояльность и скидки на контейнеры с редкими ресурсами.docx: corrupted on transfer: sizes differ 667023 vs 799331
53128:2017/05/26 13:06:15 ERROR : Targem Root/Projects/SCM/Sharing to Phones/stickers/iphone/File_000.png: corrupted on transfer: sizes differ 430423 vs 525223

**Comment by henryford** [comment]
You do know that only from posting logs it's quite difficult to guess what you actually want?

The messages are clear: An upload for a certain file failed, the upload was corrupt. The sizes of the file sent from your end and the size of the file received on the target end differ. So the upload failed.

**Comment by igoreshkas** [comment]
@henryford "corrupted on transfer: sizes differ 601837 vs 664002"  

The fact is that at this point there are no problems with the connection and the file did not change exactly

**Comment by ncw** [comment]
Use `rclone dedupe targemmain:` to check for duplicates - this can make this sort of error.

**Comment by igoreshkas** [comment]
The desired folder has a complex structure, many files are in 2 sub-folders at once, is there another option, without changing the source?

**Comment by ncw** [comment]
Rclone syncing wasn't designed to cope with duplicate file names and file system​s can't cope with duplicate file names so I think the best option is to fix the source.

There aren't any more options which will help.

Rclone dedupe could be cleverer though when there are duplicate directories - it should probably collapse those first.

**Comment by igoreshkas** [comment]
@ncw Thank you for the prompt response and explanation of the essence of the problem!
Unfortunately, we can not get rid of the duplicates on the whole Google disk, but we absolutely need to make a copy of the disk using Rclone.
Could you, in the next week or two, reward Rclone for a fee - for example, to make the identification of files not by their name, but by the google file id?
Or any other solution to the problem.“36398:2017/05/26 12:52:16 ERROR : Attempt 2/3 failed with 2 errors and: corrupted on transfer: sizes differ 601837 vs 664002

43732:2017/05/26 13:03:18 ERROR : Targem Root/PR реклама коммьюнити эвенты/Star Conflict/(Акция на выходные) Бонусы на лояльность и скидки на контейнеры с редкими ресурсами.docx: corrupted on transfer: sizes differ 667023 vs 799331
53128:2017/05/26 13:06:15 ERROR : Targem Root/Projects/SCM/Sharing to Phones/stickers/iphone/File_000.png: corrupted on transfer: sizes differ 430423 vs 525223”

**Comment by igoreshkas** [comment]
@ncw  We really like your software, and really need a revision, please tell us on what terms it is possible

**Comment by animosity22** [comment]
This seems to be stale. If there is still an issue, please post on the forums and we can try to help you out.
