### ISSUE TITLE
[Feature] Filename decryption in the browser + File decryption

### ISSUE THREAD

**Issue by FWeinb** [rclone/rclone#1452]
It would be great if it where possible to decrypt filenames using javascript in the browser. I made some initial tests using [gopherjs](https://github.com/gopherjs/gopherjs) to cross compile the `cipher.go` with some [minimal](https://gist.github.com/FWeinb/03cfba821b2d305414cbf2e5bc720157) wrapper code. You can see an example of it running in the browser [here](https://codepen.io/FWeinb/pen/867c2e3deb9e40c3b4f71ab93a5b9e8e). This approach has some performance issues and the resulting javascript is very big (1MB bundle).
This is actually my very first go code so maybe there could be some improvements. 

An implementation using something like the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) or one of these [crypto libs](https://gist.github.com/jo/8619441) would be much better I think. I will try to implement the decryption schema rclone is using in pure javascript.

**Comment by yonjah** [comment]
Sounds interesting.
Are you planning to create some kind of extension that will be able to decrypt file names on the cloud provider web app ?

If you are not using the built in crypto API ( which I think is only good for generating random values anyway) I would recommend using [SJCL](http://bitwiseshiftleft.github.io/sjcl/) It seem to be the only library made by professionals. I only compared it to CryptoJS ( which you should never use any way) and the performance were much better.

**Comment by ncw** [comment]
That is fun!  [Webassembly suport for go](https://github.com/golang/go/issues/18892) would probably be the best way of approaching this in the long run.

What are your plans for this?  Are you planning to develop this further?

**Comment by FWeinb** [comment]
My initial idea was to just make a little script that would decrypt all names in the browser. This could be used as a user script to improve browsing experiences on acd/gdrive. 

The current implementation is to slow for that. I will try to implement it using pure JS next.
As I understand it the steps needed to have a pure JS implementation would need: 
 
1. Decrypting pass1 and pass2 using AES and the internal iv bytes of rclone 
2. Construct a key using pass1 and pass2 out of it 
3. Transform using EME
4. Pad using pkcs7

**Comment by FWeinb** [comment]
I did a port of the EME go module to javascript. The whole think got quite fast with just a few performance tricks. Generating the key using scrypt is the slowest but that part can be cached for the userscript I have in mind. 

[Here](https://codepen.io/FWeinb/pen/b9be8985399f73e5b6f7a0188649c6c6) is a new little web app. The js used is approx. 40kb. 

I do think it would be possible to build a streaming decrypter for decrypting files in the web browser but I did not look into it much further.

**Comment by FWeinb** [comment]
File decryption is possible too. That was actual easy than implementing EME in javascript. Will tidy up the code. Here is a gif: 

![rclone](https://cloud.githubusercontent.com/assets/1250430/26748514/aca04f16-47fe-11e7-8ab0-cbc43892e948.gif)

**Comment by Cadish** [comment]
Looks promising! Would indeed be great to have an extension/userscript to automatically decrypt file names.

**Comment by Cadish** [comment]
Any update on this?

**Comment by 2600box** [comment]
there is certainly demand

**Comment by FWeinb** [comment]
@Cadish @2600box 
I am currently in the middle of exams till the end of this weeks. After that I will have some time to publish this.

**Comment by Cadish** [comment]
How are you progressing on this? Anything you can share, so we can try to help you on this?

**Comment by sscotth** [comment]
This would be pretty easy to implement if the crypto is working. I tested the codepen but I got an error `ctr iv must be 128 bits`. My password and salt are both 20 characters [a-zA-Z].

**Comment by MulverineX** [comment]
Any progress on this?

**Comment by FWeinb** [comment]
Sorry for the long delay, I had some time to work on this and got video streaming and general file handling working. Currently this is only working for local files (drag and drop) but I hope I can make this work for streaming files over http too. 

I made a little video seeing it in action:
[![2018-01-31 03_22_58](https://user-images.githubusercontent.com/1250430/35601988-0f97605a-0636-11e8-9834-c0424e8c6182.gif)](https://vimeo.com/253542993)
(Click for better quality)

You can try it for yourself [here](https://s.codepen.io/FWeinb/debug/acdf7a0c088756a4fa4acb4075d5df71) but be aware that all browsers are very picky in what they take as input files. If the browser can't play the decrypted file it can't play an encrypted file.

**Comment by ncw** [comment]
@FWeinb looks great!  I've been interested in gopherjs too recently so I have a branch where rclone completely compiles with gopherjs.  It doesn't run though ;-)  Not quite sure where I'm going, but having rclone run in the browser would be interesting.

Do you have code for your experiment you can show?

**Comment by FWeinb** [comment]
@ncw Thanks! 
I just published a library (not yet on npm) to github [rclone-js](https://github.com/FWeinb/rclone-js) Documentation is needed but I got quite good test coverage.

**Comment by sscotth** [comment]
I threw a Chrome extension together to decrypt filenames on gdrive. Check it out and let me know how it works for you. I'll publish it if I can get a couple people to test it.

https://github.com/sscotth/rclone-chrome-extension

**Comment by Cadish** [comment]
*noob-alert*
@sscotth, how can I install this? I'm willing to test your extension

**Comment by sscotth** [comment]
@Cadish Give this a try: https://www.thesslstore.com/blog/install-a-chrome-extension-from-github/

**Comment by Cadish** [comment]
Was able to load the extension successfully, but I don't get a "RClone Decrypt" button :/

![image](https://user-images.githubusercontent.com/960727/35934014-9fad1642-0c3c-11e8-9fda-50b6a0dd834b.png)

**Comment by sscotth** [comment]
That's where it should be. Not sure what's going on though unless there are others that have the same problem to help debug.

**Comment by sscotth** [comment]
@Cadish Actually, I made some changes which may fix a problem. Pull or download again and give it another try.

**Comment by Cadish** [comment]
@sscotth The button is there now, but it doesn't decrypt the filenames nor foldernames.

**Comment by sscotth** [comment]
Make sure you set the passwords in the options. Otherwise not sure.

**Comment by ncw** [comment]
@sscotth that is very cool - and great job @FWeinb making a reusable library.

I could put a link to both projects in the [crypt documentation](https://rclone.org/crypt/) - what do you think?  Fancy sending a PR?

**Comment by kamenoccc** [comment]
Sorry for the necropost but it's sad to see that solution for online filename decryption have died. Could we get some renowned support for such a feature?

**Comment by FWeinb** [comment]
@kamenoccc
I made a library that handles the decryption of files in browser. It is available here: [https://github.com/FWeinb/rclone-js](https://github.com/FWeinb/rclone-js)

You can build a web ui with that. Integrating this with the web apis from google drive is up to the implementation I have not looked into that.

**Comment by animosity22** [comment]
This looks answered. Closing out. If you still have a question, please feel free to post on the forums.
