### ISSUE TITLE
Warn about un-normalised UTF-8, or normalise it

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#1457]
Denormalised UTF-8 uploaded from OS X by other tools than rclone is causing problems for OS X users.

Options are
  * stop denormalising the UTF-8
  * warn about denormalised UTF-8
  * normalise the UTF-8 in the sync routines

Follow up from #1431

**Comment by ivandeex** [comment]
I believe thist was fixed recently.
I suggest clising this issue.

**Comment by ivandeex** [comment]
@ncw
This request is covered by encoding options.
I'm gonna close this ticket.
