### ISSUE TITLE
Rclone fast upload, but slow checks

### ISSUE THREAD

**Issue by m4ntic0r** [rclone/rclone#1482]
I backup my files to Google Drive. Everything works fine, upload speed is good (3-4MB/s).
But when all the files are uploaded, this takes 1-2 hours it runs an other 4-5 hours doing nothing then increasing checks. So whole backup runs over 6-7 hours. Can i do something against this long check part after uploading my new or changes files?

> What is your rclone version (eg output from `rclone -V`)
1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, 64 bit

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync --backup-dir

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2017/06/13 05:46:05 INFO  : 

Transferred:   2.101 GBytes (99.235 kBytes/s)
Errors:                 0
Checks:             95600
Transferred:          325
Elapsed time:   6h10m4.7s

2017/06/13 05:47:05 INFO  : 
Transferred:   2.101 GBytes (98.969 kBytes/s)
Errors:                 0
Checks:             95679
Transferred:          325
Elapsed time:   6h11m4.7s

2017/06/13 05:48:05 INFO  : 
Transferred:   2.101 GBytes (98.702 kBytes/s)
Errors:                 0
Checks:             95747
Transferred:          325
Elapsed time:   6h12m4.7s

2017/06/13 05:49:05 INFO  : 
Transferred:   2.101 GBytes (98.438 kBytes/s)
Errors:                 0
Checks:             95809
Transferred:          325
Elapsed time:   6h13m4.7s

**Comment by ncw** [comment]
rclone will retry the whole sync if it finds errors it can't correct by doing its low level retries.

Check the log for error messages.

Try with --retries 1 (which will do 1 retry and 0 retries - badly named I know!) to make it stop after the first cycle if you want to see what is going on.

**Comment by m4ntic0r** [comment]
at the moment a new sync is running but i dont think that errors are the cause of the long time.
i have it running with LogLevel DEBUG and --retries 1 but until now i cannot see any errors except some low level retries.

from the log i made a "runtime" - "check count" diagram and look at this:
[**Link**](https://mm-vault.de/chevereto/image/42C)

From start its really fast but after ~5minutes it gets slower and slower. number of files for sync is 96170 files.

**Comment by ncw** [comment]
I think what is happening here is the google rate limiting.  Google gives you an initial burst, then log term limits you to quite a small number of transactions per second.

Are you using rclone's client_id or have you made your own?  If you haven't then I recommend you try making one and see if that makes a difference?

**Comment by bardisty** [comment]
> Are you using rclone's client_id or have you made your own? If you haven't then I recommend you try making one and see if that makes a difference?

Thanks for the tip. Looks like using your own `client_id` for Google does indeed make a difference. Some numbers:

**Using rclone's client_id:**
```
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:              2727
Transferred:            0
Elapsed time:      22m15s
```

**Using my own client_id:**
```
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:              2727
Transferred:            0
Elapsed time:    13m27.4s
```

Test command used: 
`rclone sync path/to/files gd:path/to/files --checkers 16 --checksum -v`.

How-to for anyone who wants to do the same:
https://rclone.org/drive/#making-your-own-client-id

**Comment by victor21813** [comment]
But there is another problem when you set your own client_id.
https://github.com/ncw/rclone/issues/1220
Maybe change the client_id in code file and compile it is the easy way.

**Comment by jolumafe** [comment]
I think Google restricted the client_id creation. Now a request of client_id is previously verified by google.

**Comment by animosity22** [comment]
This was answered. Closing out. If you still have a question, please feel free to post on the forums.
