### ISSUE TITLE
Question - feature - catalog / index ?

### ISSUE THREAD

**Issue by SanderM2** [rclone/rclone#1485]
Hi,

I'm planning on backing up about 8Tb of pictures to my dropbox account using rclone. But I'm kind of worried if this will actually work out well or not?

I have many many many files and everytime I run rclone it will check file info at dropbox in order to decide which files needs to be transfered/deleted/updated.

But wouldn't it be a good idea to store some kind of index/catalog on the cloud storage so rclone just has to fetch the catalog/index, make up it's mind about what changes has to be done and just transfer/delete/update the files that has changed by comparing the local storage with the catalog/index ?

**Comment by ncw** [comment]
There are various issues about keeping a database of files to speed things up.

However you should find rclone is reasonably quick - it has to do a directory listing of each directory at dropbox and one on your local disk.  It can be doing those in parallel - see the `--checkers` flag.  For dropbox, everything rclone needs to do the comparison is in the directory listing.

How many files are you syncing?

**Comment by SanderM2** [comment]
I'm talking about more than 50 million files.

**Comment by SanderM2** [comment]
With a database it would also be possible to add encryption/decryption to cloud uploads/downloads  since all required info would be in that database.  But you said there are various issues about keeping a database.... 

Encryption would be a good idea for some business related documents ;)

**Comment by ncw** [comment]
I plan to do the local database thing eventually :-)

You can already encypt stuff - see https://rclone.org/crypt/

**Comment by SanderM2** [comment]
The local database thing would be nice. Thanks ! :-)
