### ISSUE TITLE
Update the documentation (manpage) for accessing typical swift openstack storage? 

### ISSUE THREAD

**Issue by zoobab** [rclone/rclone#1493]
Hi,

I was trying to access a swift backend on openstack, but got errors like "Bad Request" with my config file:

```
$ cat  ~/.rclone.conf
[myoscluster]
type = swift
user = $OS_USERNAME
key = $OS_PASSWORD
auth = $OS_AUTH_URL
tenant = $OS_TENANT_NAME
```

After some fair amount of debugging, I found one example here:

https://elastx.se/en/blog/getting-started-application-backups-to-swift

Where he added "domain = default"

And after that it works fine.

Could you update the documentation accordingly?

Best,

(rclone v1.30, Sabayon Linux amd64 17.04, Openstack swift (served by ceph))

**Comment by ncw** [comment]
Are you using v3 auth?

**Comment by kisahm** [comment]
i'm using v3 but it doesn't work for me

```
[bucket2]
type = swift
user = username
key = password
auth = http://keystoneauthurl:5000/v3/
domain = mydomain
tenant = myproject
region = region1
```

the authorization is not working:

```
$ rclone lsd bucket2:
2018/10/24 15:49:23 Failed to create file system for "bucket2:": Authorization Failed
```

'openstack container list' works

**Comment by ncw** [comment]
@kisahm what if you set the environment variables you set for `openstack container list` then use

```
[bucket2]
type = swift
env_auth = true
```

Does that work?

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
