### ISSUE TITLE
Feature Request: Refresh modification time on remote

### ISSUE THREAD

**Issue by diamondsw** [rclone/rclone#1505]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.36
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
macOS Sierra 64-bit, Linux/AMD64
> Which cloud storage system are you using? (eg Google Drive)
Local, SFTP, Google Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync ...
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
N/A

In a forum post (https://forum.rclone.org/t/only-update-mod-time-without-copying-file/2295) we discussed refreshing the mod-time on a remote, meaning if the file checksum matches but the mod-time differs, update the mod-time on the remote to match the source. A patch was hacked together (ironically by reverting a previous commit) that would do this during a dry-run. It got me over the initial ACD > GD migration, but it's hackish.

Ideally there would be a flag (--refresh-times, perhaps?) that would signal that while syncing, if files are found with the same size but different times, perform a secondary check of the underlying checksum. If that matches, then update the mod-time on the remote to match.

I've needed it several times in the last couple months between the difference in mod-time consistency, accuracy, and treatment across multiple filesystems, cloud providers, and protocols. The hack isn't something I think I'll be able to re-apply to each version, and the way it's integrated isn't the best.

I always hesitate to request a whole new feature (as I understand it's not just the implementing it, but the maintenance of it later), but it's turned out to be more than the one-time event I thought it was.

**Comment by ncw** [comment]
> refreshing the mod-time on a remote, meaning if the file checksum matches but the mod-time differs, update the mod-time on the remote to match the source

That is exactly what `rclone copy` and `rclone sync` do normally, so I'm unsure what the patch might do, except maybe not copy files if they aren't found?

Hopefully @calisro can attach the modified file or a `git diff `here for me to have a look at!

**Comment by diamondsw** [comment]
I'll check the code and/or run some tests (I haven't tried this in a while after my experience getting data from ACD over to GD), but I'm fairly sure when it saw the bad modtimes (sometimes off by seconds, sometimes by decades) it re-uploaded the files entirely.

**Comment by calisro** [comment]
See this discussion.  

https://forum.rclone.org/t/only-update-mod-time-without-copying-file/2295/5

It was literally reintroducing the bug this commit fixed:
https://github.com/ncw/rclone/commit/b52c80e85c7d98b894ccbcfe5604150ad349d611

The difference is that the current rclone code doesn't update the mod time on existing files if the files match.  It would be good to have flag that would refresh the mod times where the files match while doing a sync.  Maybe --freshen-modtimes or something.  The hack also wouldn't copy the files but I don't think that is a necessary feature.

**Comment by calisro** [comment]
[operations.txt](https://github.com/ncw/rclone/files/1103985/operations.txt)

**Comment by diamondsw** [comment]
Here's a test on a small folder without --checksum; note it copies "Razor":
`/volume1/Apps/bin/rclone sync -vv --dry-run "/volume1/Video/Television/Battlestar Galactica (2003)/Specials" "google-private:Backup/Video/Television/Battlestar Galactica (2003)/Specials"
2017/06/27 09:29:07 DEBUG : rclone: Version "v1.36" starting with parameters ["/volume1/Apps/bin/rclone" "sync" "-vv" "--dry-run" "/volume1/Video/Television/Battlestar Galactica (2003)/Specials" "google-private:Backup/Video/Television/Battlestar Galactica (2003)/Specials"]
2017/06/27 09:29:11 INFO  : Encrypted Google drive root 'Private/fsumqvbkc3f969eqggbs2lgi3s/n0aoto8bkf5mbgl8s8g2jsoo9o/q32s5cumvqsoa6a9sd5hnlcbsk/g7uaqjqkasvk3nu8pmg9uup1n4e4qlu87q2hg0farj9524u0vri0/c7lu4pu3nkhlhppbvr1sp3vtkk': Modify window is 1ms
2017/06/27 09:29:11 NOTICE: Encrypted Google drive root 'Private/fsumqvbkc3f969eqggbs2lgi3s/n0aoto8bkf5mbgl8s8g2jsoo9o/q32s5cumvqsoa6a9sd5hnlcbsk/g7uaqjqkasvk3nu8pmg9uup1n4e4qlu87q2hg0farj9524u0vri0/c7lu4pu3nkhlhppbvr1sp3vtkk': Not making directory as dry run is set
2017/06/27 09:29:11 DEBUG : Google drive root 'Private/fsumqvbkc3f969eqggbs2lgi3s/n0aoto8bkf5mbgl8s8g2jsoo9o/q32s5cumvqsoa6a9sd5hnlcbsk/g7uaqjqkasvk3nu8pmg9uup1n4e4qlu87q2hg0farj9524u0vri0/c7lu4pu3nkhlhppbvr1sp3vtkk': Reading ""
2017/06/27 09:29:11 DEBUG : Google drive root 'Private/fsumqvbkc3f969eqggbs2lgi3s/n0aoto8bkf5mbgl8s8g2jsoo9o/q32s5cumvqsoa6a9sd5hnlcbsk/g7uaqjqkasvk3nu8pmg9uup1n4e4qlu87q2hg0farj9524u0vri0/c7lu4pu3nkhlhppbvr1sp3vtkk': Finished reading ""
2017/06/27 09:29:11 INFO  : Encrypted Google drive root 'Private/fsumqvbkc3f969eqggbs2lgi3s/n0aoto8bkf5mbgl8s8g2jsoo9o/q32s5cumvqsoa6a9sd5hnlcbsk/g7uaqjqkasvk3nu8pmg9uup1n4e4qlu87q2hg0farj9524u0vri0/c7lu4pu3nkhlhppbvr1sp3vtkk': Waiting for checks to finish
2017/06/27 09:29:11 DEBUG : Battlestar Galactica S00E04-E05 - Razor.mkv: Modification times differ by -222.242908ms: 2017-06-26 17:28:37.222242908 -0500 CDT, 2017-06-26 22:28:37 +0000 UTC
2017/06/27 09:29:11 NOTICE: Battlestar Galactica S00E04-E05 - Razor.mkv: Not copying as --dry-run
2017/06/27 09:29:11 DEBUG : Battlestar Galactica S00E02 - Miniseries Part 2.mkv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/06/27 09:29:11 DEBUG : Battlestar Galactica S00E02 - Miniseries Part 2.mkv: Unchanged skipping
2017/06/27 09:29:11 DEBUG : Battlestar Galactica S00E22 - The Plan.mkv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/06/27 09:29:11 DEBUG : Battlestar Galactica S00E22 - The Plan.mkv: Unchanged skipping
2017/06/27 09:29:11 DEBUG : Battlestar Galactica S00E01 - Miniseries Part 1.mkv: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/06/27 09:29:11 DEBUG : Battlestar Galactica S00E01 - Miniseries Part 1.mkv: Unchanged skipping
2017/06/27 09:29:11 INFO  : Encrypted Google drive root 'Private/fsumqvbkc3f969eqggbs2lgi3s/n0aoto8bkf5mbgl8s8g2jsoo9o/q32s5cumvqsoa6a9sd5hnlcbsk/g7uaqjqkasvk3nu8pmg9uup1n4e4qlu87q2hg0farj9524u0vri0/c7lu4pu3nkhlhppbvr1sp3vtkk': Waiting for transfers to finish
2017/06/27 09:29:11 INFO  : Waiting for deletions to finish
2017/06/27 09:29:11 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 4
Transferred:            1
Elapsed time:        3.9s
2017/06/27 09:29:11 DEBUG : Go routines at exit 5
2017/06/27 09:29:11 DEBUG : rclone: Version "v1.36" finishing with parameters ["/volume1/Apps/bin/rclone" "sync" "-vv" "--dry-run" "/volume1/Video/Television/Battlestar Galactica (2003)/Specials" "google-private:Backup/Video/Television/Battlestar Galactica (2003)/Specials"]`

However, add the checksum option and you'll see that nothing is copied, because the only difference is the timestamp:
`/volume1/Apps/bin/rclone sync -vv --dry-run "/volume1/Video/Television/Battlestar Galactica (2003)/Specials" "google-private:Backup/Video/Television/Battlestar Galactica (2003)/Specials" --checksum
2017/06/27 09:30:35 DEBUG : rclone: Version "v1.36" starting with parameters ["/volume1/Apps/bin/rclone" "sync" "-vv" "--dry-run" "/volume1/Video/Television/Battlestar Galactica (2003)/Specials" "google-private:Backup/Video/Television/Battlestar Galactica (2003)/Specials" "--checksum"]
2017/06/27 09:30:46 INFO  : Encrypted Google drive root 'Private/fsumqvbkc3f969eqggbs2lgi3s/n0aoto8bkf5mbgl8s8g2jsoo9o/q32s5cumvqsoa6a9sd5hnlcbsk/g7uaqjqkasvk3nu8pmg9uup1n4e4qlu87q2hg0farj9524u0vri0/c7lu4pu3nkhlhppbvr1sp3vtkk': Modify window is 1ms
2017/06/27 09:30:46 NOTICE: Encrypted Google drive root 'Private/fsumqvbkc3f969eqggbs2lgi3s/n0aoto8bkf5mbgl8s8g2jsoo9o/q32s5cumvqsoa6a9sd5hnlcbsk/g7uaqjqkasvk3nu8pmg9uup1n4e4qlu87q2hg0farj9524u0vri0/c7lu4pu3nkhlhppbvr1sp3vtkk': Not making directory as dry run is set
2017/06/27 09:30:46 DEBUG : Google drive root 'Private/fsumqvbkc3f969eqggbs2lgi3s/n0aoto8bkf5mbgl8s8g2jsoo9o/q32s5cumvqsoa6a9sd5hnlcbsk/g7uaqjqkasvk3nu8pmg9uup1n4e4qlu87q2hg0farj9524u0vri0/c7lu4pu3nkhlhppbvr1sp3vtkk': Reading ""
2017/06/27 09:30:47 DEBUG : Google drive root 'Private/fsumqvbkc3f969eqggbs2lgi3s/n0aoto8bkf5mbgl8s8g2jsoo9o/q32s5cumvqsoa6a9sd5hnlcbsk/g7uaqjqkasvk3nu8pmg9uup1n4e4qlu87q2hg0farj9524u0vri0/c7lu4pu3nkhlhppbvr1sp3vtkk': Finished reading ""
2017/06/27 09:30:47 DEBUG : Battlestar Galactica S00E01 - Miniseries Part 1.mkv: Size of src and dst objects identical
2017/06/27 09:30:47 DEBUG : Battlestar Galactica S00E22 - The Plan.mkv: Size of src and dst objects identical
2017/06/27 09:30:47 DEBUG : Battlestar Galactica S00E22 - The Plan.mkv: Unchanged skipping
2017/06/27 09:30:47 INFO  : Encrypted Google drive root 'Private/fsumqvbkc3f969eqggbs2lgi3s/n0aoto8bkf5mbgl8s8g2jsoo9o/q32s5cumvqsoa6a9sd5hnlcbsk/g7uaqjqkasvk3nu8pmg9uup1n4e4qlu87q2hg0farj9524u0vri0/c7lu4pu3nkhlhppbvr1sp3vtkk': Waiting for checks to finish
2017/06/27 09:30:47 DEBUG : Battlestar Galactica S00E02 - Miniseries Part 2.mkv: Size of src and dst objects identical
2017/06/27 09:30:47 DEBUG : Battlestar Galactica S00E02 - Miniseries Part 2.mkv: Unchanged skipping
2017/06/27 09:30:47 DEBUG : Battlestar Galactica S00E04-E05 - Razor.mkv: Size of src and dst objects identical
2017/06/27 09:30:47 DEBUG : Battlestar Galactica S00E04-E05 - Razor.mkv: Unchanged skipping
2017/06/27 09:30:47 DEBUG : Battlestar Galactica S00E01 - Miniseries Part 1.mkv: Unchanged skipping
2017/06/27 09:30:47 INFO  : Encrypted Google drive root 'Private/fsumqvbkc3f969eqggbs2lgi3s/n0aoto8bkf5mbgl8s8g2jsoo9o/q32s5cumvqsoa6a9sd5hnlcbsk/g7uaqjqkasvk3nu8pmg9uup1n4e4qlu87q2hg0farj9524u0vri0/c7lu4pu3nkhlhppbvr1sp3vtkk': Waiting for transfers to finish
2017/06/27 09:30:47 INFO  : Waiting for deletions to finish
2017/06/27 09:30:47 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 4
Transferred:            0
Elapsed time:       11.8s
2017/06/27 09:30:47 DEBUG : Go routines at exit 5
2017/06/27 09:30:47 DEBUG : rclone: Version "v1.36" finishing with parameters ["/volume1/Apps/bin/rclone" "sync" "-vv" "--dry-run" "/volume1/Video/Television/Battlestar Galactica (2003)/Specials" "google-private:Backup/Video/Television/Battlestar Galactica (2003)/Specials" "--checksum"]`

This is exactly what I'm asking to fix - if the size is the same and modification times differ, run a secondary test on the checksum. If the checksum matches, update the mod-time on the remote so they match and future runs can rely on size/mod-time

**Comment by ncw** [comment]
I would say the important effect of the patch to operations.go is to **ignore** hashes - meaning it updates the mod time if only the size matches, not the size and the hash.

Are you uploading to crypt by any chance which doesn't support hashes?

**Comment by diamondsw** [comment]
Interesting; yes, I am uploading to a crypt. It's an overlay on top of Google Drive.

**Comment by diamondsw** [comment]
Bit confused as to the status of this; does the extra information that this is affecting crypt-based remotes make the situation better or worse for this request?

**Comment by diamondsw** [comment]
I hate bumping; this just seemed to die off a few weeks back. If this is one of those "much harder than it looks from the outside" then I'm fine with it being deferred, but if it's a manageable project it would certainly help me out a lot. Right now I'm maintaining a separate patched copy of rclone and backup scripts so I can manually fix my GDrive dates every so often. Due to the number of objects involved, this is non-trivial.

**Comment by diamondsw** [comment]
Is the concern here that - without checksums available - all we have to go by is the size matching and that's not a strong enough signal that the files are the same? It would still be useful if we _know_ that the file is the same if we could reset the modtime to match. Or is there some other signal that could be examined?

**Comment by Kara-ism** [comment]
Hi, I also need this feature.
Could you make this feature refresh the time-stamp not only files but folders in future?
I use v.1.37 to synchronize time-stamps and find out that only files can be refreshed but folders remained.

**Comment by ncw** [comment]
Let me summarize where I think we have got to...

Currently rclone will update mod times on remote files if the size is identical and the hash matches but the mod time is different.

However if the hash is missing, and the size is identical, rclone doesn't update the modification time.

What we would like is rclone to update the mod time if only the size matches - is that correct?

I'd be happy to do that with a flag...  Maybe the --size-only flag could imply that behaviour?

**Comment by diamondsw** [comment]
That seems like an excellent idea, especially since it should only apply when you've told rclone to only factor in sizes. +1

**Comment by diamondsw** [comment]
I don't suppose this landed in rclone 1.38?

**Comment by ncw** [comment]
I think this needs to be gated with a flag.

Here is my attempt at some docs for the new flag.  It is complicated!  Any thoughts?

## --refresh-times

The `--refresh-times` flag can be used to update modification times of existing files.  This is useful if you uploaded files with the incorrect timestamps and you now wish to correct them.

This can be used any of the sync commands `sync`, `copy` or `move`.

When rclone comes to upload a file it will check if there is an existing file and if it matches with size (no sync flags or `--size-only`) or size and checksum (`--checksum`) then instead of re-uploading it, rclone will update the timestamp.

Note that some remotes (eg `amazon drive`, `b2`, `dropbox`, `mega`, `pcloud`, `webdav`) can't set the modification time without re-uploading the file anyway so this flag is useless with them.

If you are doing a modification time sync (ie not using `--checksum` or `--size-only`) rclone will update modification times without `--refresh-times` provided that the remote supports checksums and the checksums match on the file.  `crypt` remotes do not support checksums so to update times on a `crypt` remote you will need to use `--refresh-times`.

**Comment by ncw** [comment]
See also [discussion on the forum](https://forum.rclone.org/t/how-do-i-keep-rclone-from-not-reuploading-moved-files/6258/16)

**Comment by allobrogica** [comment]
Do we think this new (hopefully) new flag will work with a crypted sftp remote?

**Comment by ncw** [comment]
> Do we think this new (hopefully) new flag will work with a crypted sftp remote?

Should do...

I haven't had time to work on this - does anyone else want to have a go?

**Comment by Mushin** [comment]
I'm having issues with differing mod times on a Gdrive crypt and would really appreciate if this could work.

**Comment by ncw** [comment]
I've had a go at implementing the `--refresh-times` flag here

https://beta.rclone.org/branch/v1.52.1-077-g21dec334-fix-1505-refresh-times-beta/ (uploaded in 15-30 mins)

### --refresh-times ###

The `--refresh-times` flag can be used to update modification times of
existing files when they are out of sync on backends which don't
support hashes.

This is useful if you uploaded files with the incorrect timestamps and
you now wish to correct them.

This flag is **only** useful for destinations which don't support
hashes (eg `crypt`).

This can be used any of the sync commands `sync`, `copy` or `move`.

To use this flag you will need to be doing a modification time sync
(so not using `--size-only` or `--checksum`). The flag will have no
effect when using `--size-only` or `--checksum`.

If this flag is used when rclone comes to upload a file it will check
to see if there is an existing file on the destination. If this file
matches the source with size (and checksum if available) but has a
differing timestamp then instead of re-uploading it, rclone will
update the timestamp on the destination file. If the checksum does not
match rclone will upload the new file. If the checksum is absent (eg
on a `crypt` backend) then rclone will update the timestamp.

Note that some remotes can't set the modification time without
re-uploading the file so this flag is less useful on them.

Normally if you are doing a modification time sync rclone will update
modification times without `--refresh-times` provided that the remote
supports checksums **and** the checksums match on the file. However if the
checksums are absent then rclone will upload the file rather than
setting the timestamp as this is the safe behaviour.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.53

**Comment by ncw** [comment]
Forgot the issue tag. Here is the commit 3efdf5e0952950dbc1312506cb7da297ba21f9be

**Comment by Mushin** [comment]
Thanks for this - much appreciated. Is there any way I can do a --refresh-times sync without also performing any file transfers during the process? I guess I could just let all the checks and modtimes update, then cancel the run? Is there any way to tell rclone to do only the modtime updates but no data transfer?

**Comment by ncw** [comment]
> Thanks for this - much appreciated. Is there any way I can do a --refresh-times sync without also performing any file transfers during the process?

I haven't tried this, but if you use [the latest beta](https://beta.rclone.org) then rclone gains the `-i` flag. This interactively asks you what rclone should do. You can say yes to all setting of modtimes and no to all transfers.



> Also - how would rclone handle a situation where there's a modtime mismatch, and the --refresh-times, --track-renames and --track-renames-strategy "modtime" are all enabled?

I wouldn't use `--refresh-times` on a regular sync, only on a single "catchup" sync. It isn't really a general purpose flag.

**Comment by marcOcram** [comment]
I am currently using `--refresh-times` on about 95k of files (thanks for the implementation!) and I am using Backblaze B2 as backend.
I am using `--fast-list` but the transactions for `b2_list_file_names` are used more than on a normal sync. Not that it really matters for that one shot I am doing but is it an issue or is it just not compatible with `--fast-list`?
As far as I understand the code for B2, to set the modification time, it reads the meta data prior which itself makes a call to `fs.list`. Therefore I do not think that it is a bug. Maybe the documentation should include a note that `--fast-list` may not be compatible with `--refresh-times`. The same as it says that some backends just re-upload the file again.

**Comment by ncw** [comment]
> I am using `--fast-list` but the transactions for `b2_list_file_names` are used more than on a normal sync. Not that it really matters for that one shot I am doing but is it an issue or is it just not compatible with `--fast-list`?

It is still doing the sync as normal so `--fast-list` should be working fine. However setting the modtime may call `b2_list_file_names`...

I just had a look at the code, and yes I think it is doing that to read metadata from the file so it has complete metadata before copying it (which is how you set the modtime). It maybe could be more efficient, but at least you know why now!

**Comment by ilindaniel** [comment]
Hi there, sorry for bumping this ticket!

Can we add a warning to https://rclone.org/docs/ that --refresh-times will be ignored when the destination does not support mod time changes without reuploading the file, like Amazon Drive, B2, Dropbox, Mega, pCloud, WebDAV etc. like you mentioned here?: https://forum.rclone.org/t/how-do-i-keep-rclone-from-not-reuploading-moved-files/6258/14

**Comment by ncw** [comment]
> Can we add a warning to https://rclone.org/docs/ that --refresh-times will be ignored when the destination does not support mod time changes without reuploading the file, like Amazon Drive, B2, Dropbox, Mega, pCloud, WebDAV etc. like you mentioned here?: https://forum.rclone.org/t/how-do-i-keep-rclone-from-not-reuploading-moved-files/6258/14

The docs https://rclone.org/docs/#refresh-times do say:

> Note that some remotes can't set the modification time without re-uploading the file so this flag is less useful on them.

So the flag does work, it just doesn't save the bandwidth you were hoping it would... Do you think this needs to be expanded? I don't really want to put a list of backends there since the list keeps changing, eg you no longer need to upload the file again with B2.

> Edit: I think it would be also cool to output this warning to the console as soon as rclone realizes the destination does not support this flag, rather than solely on -v or -vv

That is a good idea.

Rclone could log a NOTICE (just once) if it has to upload files like this. What do you think? Something like

    NOTICE: --refresh-times in use with a backend which can't set modification times except by uploading the file again

Or I could raise these two debugs to INFO level (appear with -v) - I don't think they want to be NOTICE (appear without -v) as potentially there can be lots of them.

                                fs.Debugf(dst, "src and dst identical but can't set mod time without re-uploading")
                                fs.Debugf(dst, "src and dst identical but can't set mod time without deleting and re-uploading")

**Comment by ncw** [comment]
@ilindaniel I've put a fix for the above in 2b7994e73937192cf4eb9affd02ee727272e947d which is a bit more general - it warns the user whenever it is uploading files just to set the mod time.
