### ISSUE TITLE
old ACD token not valid, using rclone config to authorize throws error page

### ISSUE THREAD

**Issue by bunset** [rclone/rclone#1513]
It was working very well before, but now It said token not valid, I tried rclone config but amazon web page throws error rclone config can't send the token to amazon cloud drive.

Could you check if You have too the same problem?

Thank You very much for the program and kind regards,
David
> What is your rclone version (eg output from `rclone -V`) 1.36

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
mac
> Which cloud storage system are you using? (eg Google Drive)
ACD
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone config
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
rclone -vv copy /tmp remote:tmp
2017/07/01 18:22:32 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "-vv" "copy" "/tmp" "remote:tmp"]
2017/07/01 18:22:33 Failed to create file system for "remote:tmp": failed to get endpoints: Get https://drive.amazonaws.com/drive/v1/account/endpoint: oauth2: cannot fetch token: 401 Unauthorized
Response: {"error_description":"Client authentication failed","error":"invalid_client"}

**Comment by ncw** [comment]
Checkout [this forum post](https://forum.rclone.org/t/rclone-has-been-banned-from-amazon-drive/2314) then [this one](https://forum.rclone.org/t/proxy-for-amazon-cloud-drive/2848) that that should answer your questions hopefully.

**Comment by animosity22** [comment]
RIP ACD. You'll be remembered. Closing out.
