### ISSUE TITLE
Rename Identical Files on Local Disk

### ISSUE THREAD

**Issue by dav1303** [rclone/rclone#1514]
Hi

When a file with the same name exist on Google Drive Folder and when we download the folder on local disk only one file is copied

Can we imagine rclone can rename one of the file with another name before downloading it ?

Regards

**Comment by ncw** [comment]
Use [rclone dedupe](https://rclone.org/commands/rclone_dedupe/) to rename on google drive first would be my advice.

**Comment by animosity22** [comment]
This was answered. Closing out.
