### ISSUE TITLE
Prompt before performing critical operations

### ISSUE THREAD

**Issue by alexzeitgeist** [rclone/rclone#152]
I have been testing rclone with ACD and I am very impressed with how well it performs, considering that ACD support has just recently been added.

One thing I am concerned with is the use of an operation such as `rclone purge` getting executed without prompt confirmation. Stating a wrong path could accidentally erase a lot of data with the blink of an eye. It would be nice if we could imlement a confirmation prompt (displaying the actual path that we're about to erase). And we could add an -f option to force the deletion without prompt.

**Comment by ncw** [comment]
Glad you are enjoying rclone!

The unix tradition is to make command line tools which don't prompt by default, but to add a flag (eg `-i` for interactive) which then prompts before critical operations.  What do you think of that idea?

In the specific case of ACD rclone can't actually delete anything, only put it in the trash (as there is no API for permanent delete available) so you can always rescue it out of the trash.

**Comment by alexzeitgeist** [comment]
You're right - I didn't think of the trash bin functionality in ACD. And good point about the preference to avoid interactive commands. The issue I see here is that the `purge` command can be used for both, deleting individual files and whole paths without the addition of any flags. This makes accidents more likely.

As it is, the commands `rclone rmdir` and `rclone purge` seem kind of redundant. How about adopting unix style? We could use `rclone rm` and `rclone rm -r`, respectively. This way, if you just want to delete a file or files, you won't be able to accidently delete a whole path unless you define the recursive flag as well.

**Comment by eadmaster** [comment]
I second the request!
I'd like a switch to prompt confirmation before overwriting a remote file. 
Btw staying in "batch mode" (no confirmations req.) by default is still good.

**Comment by animosity22** [comment]
This looks to be covered in this issue:

https://github.com/rclone/rclone/issues/1574

And this is a bit stale as well so closing it out and we can refer to the one above.
