### ISSUE TITLE
Swift copy : add specific headers ?

### ISSUE THREAD

**Issue by martintamare** [rclone/rclone#1544]
I'm trying to address the following issue:

Now:
We use rclone sync local_drive to swift every night
Problem: if a file is deleted locally, the night after it will be delete on swift

Idea:
We would like to use rclone copy local_drive to swift and set up the correct header provided by swift
X-Delete-After: delete in X seconds

Problem: I don't see any option for this. 
Am I blind ? Or maybe this is a feature request ? 😄 

Adding header to new file is easy I think.
The tricky part is for existing file both on local_drive and swift. We don't want to copy the file (which is already the case using rclone copy), but instead do a PUT on metadata to update the header X-Delete-After

I'm willing to help to implement this if necessary ! (not familiar with golang, but an if is an if 😉 )

**Comment by ncw** [comment]
There is an issue about adding new headers for uploads in #59 which I'm hoping to get done for 1.38

> The tricky part is for existing file both on local_drive and swift. We don't want to copy the file (which is already the case using rclone copy), but instead do a PUT on metadata to update the header X-Delete-After

I think you might be better off using the swift tool for this - this isn't in-scope for #59.

**Comment by martintamare** [comment]
Totally agree for the tricky part, not in the scope of #59.
But, this could be an interesting option to implement.

What about a switch
--swift-existing-header-put ?
(not really good at finding name)

I think this is specific to swift, but maybe can it be generalized ?

**Comment by ivandeex** [comment]
@ncw
I believe now rclone supports adhoc upload headers.
I suggest closing this issue.

**Comment by martinr92** [comment]
It's working perfectly with the "--header-upload" parameter:
`rclone copy --header-upload "X-Delete-After: 60" my-file.txt OVH:"bucket/"`
