### ISSUE TITLE
Add Storj to cloud offerings

### ISSUE THREAD

**Issue by scrummie02** [rclone/rclone#1571]
Storj Sia are two decentralized cloud storage providers picking up steam.  Could these be added?

**Comment by ncw** [comment]
There is an issue about Sia already in #579.  What is storj?  Does it have an API?  Can you provide links?

**Comment by scrummie02** [comment]
https://storj.io/
It's a SIA competitor and a little easier to run and use.   They are a little more used than SIA.  Both are great but Storj allows you to pay with Fiat currency and has a S3 like interface

Here is their API
https://storj.io/api.html

**Comment by DavidVorick** [comment]
Storj also recently updated their code to become a centralized platform

**Comment by airmonitor** [comment]
+1

**Comment by felixbrucker** [comment]
The upcoming v3 version of the network and client software will be S3 compatible via minio and thus should be working OOB.

**Comment by ncw** [comment]
@felixbrucker nice!  If someone could have a go with it then make an s3 provider for it that would be very useful and make it easy to configure.  That is a matter of working out which s3 options apply, what the endpoints and regions are, etc.

**Comment by felixbrucker** [comment]
First alpha builds are slated for Q3 2018, i might be able to play around with it then.

**Comment by calebcase** [comment]
I have a working implementation here: https://github.com/calebcase/rclone/tree/feature/storj

All tests are passing and I'm interested in feedback. It integrates directly with Storj (not going through S3 or another gateway).

@ncw Should I open a PR at this point?

**Comment by ncw** [comment]
> I have a working implementation here: https://github.com/calebcase/rclone/tree/feature/storj
> 
> All tests are passing and I'm interested in feedback. It integrates directly with Storj (not going through S3 or another gateway).
> 
> @ncw Should I open a PR at this point?

Great! Yes open a PR this will aid discussion :-)

I'm going to need an account for integration testing. Can you get free accounts?

**Comment by calebcase** [comment]
Absolutely! I'll send you an email shortly.

**Comment by calebcase** [comment]
@ncw Did you get the email?

**Comment by ncw** [comment]
@calebcase I got the email - haven't had time to look at Storj yet - sorry (work and life both a bit hectic!)  However I should have some time at the weekend hopefully :-)  I left a bit of initial feedback on your PR.

**Comment by calebcase** [comment]
@ncw No worries! Just making sure it made it to you. Thanks for the feedback!

**Comment by madcatsu** [comment]
FYI - the on-demand storage product from Storj is now called Tardigrade. GA announcement was made two days ago here: https://storj.io/blog/2020/03/general-availability-for-tardigrade-is-here/

**Comment by creativeprojects** [comment]
PR merged https://github.com/rclone/rclone/pull/3699

**Comment by ncw** [comment]
Note that the backend is called tardigrade and will be in 1.52 :-)
