### ISSUE TITLE
Rclone ESXI

### ISSUE THREAD

**Issue by xxx31fr** [rclone/rclone#1578]
> What is your rclone version (eg output from `rclone -V`)

rclone-v1.37-049-g28a18303β

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

VMware ESXI (fork of Linux)

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

./rclone -V | ./rclone config ...

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

message from ESXI "Segmentation fault"

See also [the forum thread](https://forum.rclone.org/t/rclone-vmware-esxi/3144)

**Comment by ncw** [comment]
In the forum thread we tried an rclone compiled with go-tip without any luck.

Can you try a simple go binary?  This is a simple hello world compiled for linux/amd64

[hello.zip](https://github.com/ncw/rclone/files/1200519/hello.zip)

If that doesn't work then we should report this as a go issue.

Either way does ESXI have `gdb`? If so can you try it on the failing binaries like this (I made a crashing binary called `crash` - you would use rclone or hello).

```
$ gdb ./crash 
GNU gdb (Ubuntu 7.12.50.20170314-0ubuntu1) 7.12.50.20170314-git
[snip]
Reading symbols from ./crash...done.
(gdb) run
Starting program: /home/ncw/Go/crash 
[New LWP 29811]
[New LWP 29812]
[New LWP 29813]
[New LWP 29814]
[New LWP 29815]

Thread 1 "crash" received signal SIGSEGV, Segmentation fault.
main.main () at /home/ncw/Go/crash.go:7
7		*p = 1
(gdb) bt
#0  main.main () at /home/ncw/Go/crash.go:7
(gdb) 
```

**Comment by xxx31fr** [comment]
hello,

Exactly the same issue "segmentation fault".

I cannot check crash, because no gbd...

Thanks

**Comment by ncw** [comment]
I made a in issue on the go project about this: https://github.com/golang/go/issues/21347

**Comment by animosity22** [comment]
Solved via the go bug. Closing out.
