### ISSUE TITLE
Request: seperate Options for Encrypt/Decrypt

### ISSUE THREAD

**Issue by snickers2k** [rclone/rclone#1584]
I think decrypting an drive is a complete weird procedure and makes you feel it could be, that you maybe double encrypt your drive. Please add two different Options for encrypting and decrypting to clarify whats going on. Thanks!

**Comment by ncw** [comment]
If you write to the drive you are encrypting stuff, if you read from the drive you are decrypting stuff.  Does that make it clearer?

**Comment by snickers2k** [comment]
I meant the Setup for an already encrypted drive. Option 5 should be "encrypting a new drive" and Option 6 should be "decrypting an drive". Otherwise, like i said, it feels like you COULD be double encrypting an already encrypted drive. You get me ?

**Comment by ncw** [comment]
The option says this

```
 6 / Encrypt/Decrypt a remote
   \ "crypt"
``` 

So the same option does both encrypt and decrypt?

**Comment by snickers2k** [comment]
Right. And the procedure behind it is really weird, if you have already an encrypted drive and wants to decrypt it

**Comment by animosity22** [comment]
If you still have a question, please post on the forums as this looks answered.
