### ISSUE TITLE
Amazon Drive: Compare by size, then by checksum ? Metadata files ?

### ISSUE THREAD

**Issue by mathieucarbou** [rclone/rclone#1593]
- I am using the default options and the comparison is done by size.
- I am syncing to Amazon Drive

So the default behavior has some issues when we modify a text file and only change the same amount of characters, the file does not get synced.

__Qu1__: Is it because when syncing to Amazon Drive, only the size can be used and not the modification time ?  It seems like Amazon does not support it if I look at the logs:

`2017/08/11 02:30:01 INFO  : amazon drive root 'NAS': Modify window not supported`

__Qu2__: Is there a way to tell rclone to compare by checksum __only if__ the size is the same ?

__Qu3__: If Amazon Drive does not support to get metadata info about a file, such as the checksum, would it be possible then to tell rclone, when it syncs, to compute the CRC file of the local file, then upload it near to this file ? Example, `foo.txt` will be uploaded with `foo.txt.crc` (checksum), then, if rclone finds that the local file has the same size as the remote file, it could download the CRC file and compare it to the local computed CRC to determine if the file has changed.

__Qu4__: More generally, for storage that does not support metadata, would it be possible to tell rclone to save them in a file ? I.e. `foo.txt` could be uploaded with `foo.txt.rclone` and this file would contain the informations about the file: crc, mod time, etc. This way, even in the default comparison behavior, we could compare by size and mod time, and we could if we want add crc check.

Let me know what is possible right now to workaround this amazon drive issue not seeing change on files having the same sizes.

**Comment by ncw** [comment]
> Is it because when syncing to Amazon Drive, only the size can be used and not the modification time 

Yes that is right.  With no modification time available, rclone will default to just checking the size.

> Is there a way to tell rclone to compare by checksum only if the size is the same ?

That is what `--checksum` does.

>  If Amazon Drive does not support to get metadata info about a file, such as the checksum, would it be possible then to tell rclone, when it syncs, to compute the CRC file of the local file, then upload it near to this file ? Example, foo.txt will be uploaded with foo.txt.crc (checksum), then, if rclone finds that the local file has the same size as the remote file, it could download the CRC file and compare it to the local computed CRC to determine if the file has changed.

Amazon Drive supports MD5 hashes so when you use the `--checksum` flag it is doing pretty much this.

> More generally, for storage that does not support metadata, would it be possible to tell rclone to save them in a file ? I.e. foo.txt could be uploaded with foo.txt.rclone and this file would contain the informations about the file: crc, mod time, etc. This way, even in the default comparison behavior, we could compare by size and mod time, and we could if we want add crc check.

Possibly... However Amazon Drive does support metadata and it could be added to rclone to store the modtime - see #371.  I haven't done it yet though, and amazon aren't in my good books at the moment as I still don't have an official set of credentials for rclone!

> Let me know what is possible right now to workaround this amazon drive issue not seeing change on files having the same sizes.

`--checksum` is the flag you need!

PS For questions the rclone forum is probably a better place than making an issue: https://forum.rclone.org

**Comment by mathieucarbou** [comment]
oh sorry i didn't see the forum... thanks a lot!

**Comment by mathieucarbou** [comment]
I am updating it, again, because I really thing something could be improved here.

This is in relation to #1587 and my comment here: https://github.com/ncw/rclone/issues/1587#issuecomment-321953847

I added the checksum option, and I must say that on a NAS, this is really not recommended as it consumes a lot of CPU and slows down the sync process a lot! It would be faster I think to have a kind of metadata file near each file that would contain the mod time and size. In a NAS, it costs less to download a little file than to compute a MD5 of big files to end-up to a conclusion that there has been no modification.

For now, if I really want to ensure (or at least be nearly like) an exact mirror, it means I am forced to split the sync tasks across several little ones for each folder and only activate `--checksum`  in only the folder where I have "less" important files.

**Comment by animosity22** [comment]
Legacy ACD issue. Closing out.
