### ISSUE TITLE
Feature request: Maximum transfer total

### ISSUE THREAD

**Issue by 4getit** [rclone/rclone#1599]
Now with the Google policy of maximum 750GB per 24hrs, I think it would come in handy to have a flag where the maximum transferred total can be specified. When this total is reached, rclone should just stop.

For example, I'm currently copying an existing remote to a new remote but I also would like to add new stuff.
The copy will now take several days but if this copy always maxes out the 750GB, I'm never able to add new stuff.
So for example, if I could set --max-transfer-total 700GB
That means that I always have 50GB headroom and my drive uploads are still working.

**Comment by breunigs** [comment]
While not ideal, `--bwlimit 8500` would limit your upload to ~700GB *a day*. 

Do you have an idea how this would work for mounts, though? Just exiting might leave the mount in an undesirable state…

**Comment by 4getit** [comment]
Good one. I didn't think of --bwlimit as a workaround. I'm going to try that.

As for mounts, I have no idea but I assume there will be weird results when the Google limit kicks on an active mount anyways. 
Maybe the option should only work with copy, moveto, sync etc.?

**Comment by 4getit** [comment]
I've been using the --bwlimit as a workaround for 2 weeks now and it works ok. However, I still think it would make sense to be able to set a maximum. That way I can just upload whatever is possible for the day and be done with it.
Right now, with multiple remotes, I have multiple rclone's running 24/7 while that isn't necessary.

**Comment by ColeMundus** [comment]
This would make scripting especially useful to switching remotes when a specific amount is uploaded.

**Comment by animosity22** [comment]
This item is definitely done as we have a few options now for Google's quota limits so I'm going to close this one out.

If you have a different view, let me know and we can discuss. Thanks!
