### ISSUE TITLE
Dreaded userRateLimitExceeded

### ISSUE THREAD

**Issue by pcarrollarch** [rclone/rclone#1606]
Using the latest beta, I cannot get dedupe to act on a larger data set. Works fine on a smal amount of test data. But on a larger set, it constantly times out. You can leave it for hours and nothing will happen. Left it alone for the weekend. First attempt on Monday failed. It's running on a Celeron linux based QNAP NAS. 

rclone rmdirs exhibits the same behaviour on the large data set. Running an rclone sync on the same data set works perfectly. But of course it skips duplicate folders so I do not get all the data...

To me, this does not look like a rate limit problem. Otherwise I would expect all calls to fail.

# rclone -vv dedupe newest gdrive:test
2017/08/16 10:18:46 DEBUG : rclone: Version "v1.37-090-g9c47b767β" starting with parameters ["rclone" "-vv" "dedupe" "newest" "gdrive:test"]
2017/08/16 10:18:47 DEBUG : gdrive: Saved new token in config file
2017/08/16 10:18:47 INFO  : Google drive root 'test': Modify window is 1ms
2017/08/16 10:18:47 INFO  : Google drive root 'test': Looking for duplicates using newest mode.
2017/08/16 10:18:49 DEBUG : Go routines at exit 6
2017/08/16 10:18:49 DEBUG : rclone: Version "v1.37-090-g9c47b767β" finishing with parameters ["rclone" "-vv" "dedupe" "newest" "gdrive:test"]
# rclone -vv dedupe newest gdrive:Something/Bigger
2017/08/16 10:19:26 DEBUG : rclone: Version "v1.37-090-g9c47b767β" starting with parameters ["rclone" "-vv" "dedupe" "newest" "gdrive:Something/Else"]
2017/08/16 10:19:27 INFO  : Google drive root 'Something/Bigger': Modify window is 1ms
2017/08/16 10:19:27 INFO  : Google drive root 'Something/Bigger': Looking for duplicates using newest mode.
2017/08/16 10:19:34 DEBUG : pacer: Rate limited, sleeping for 1.74886657s (1 consecutive low level retries)
2017/08/16 10:19:34 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded)
2017/08/16 10:19:34 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2017/08/16 10:19:34 DEBUG : pacer: Rate limited, sleeping for 1.649146272s (1 consecutive low level retries)
2017/08/16 10:19:34 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded)
2017/08/16 10:19:34 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2017/08/16 10:19:36 DEBUG : pacer: Rate limited, sleeping for 1.454259606s (1 consecutive low level retries)
2017/08/16 10:19:36 DEBUG : pacer: low level retry 3/10 (error googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded)
2017/08/16 10:19:36 DEBUG : pacer: Rate limited, sleeping for 2.214630369s (2 consecutive low level retries)
2017/08/16 10:19:36 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded)
2017/08/16 10:19:36 DEBUG : pacer: Rate limited, sleeping for 4.17680991s (3 consecutive low level retries)
2017/08/16 10:19:36 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded)
2017/08/16 10:19:36 DEBUG : pacer: Rate limited, sleeping for 8.859277607s (4 consecutive low level retries)
2017/08/16 10:19:36 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded)
2017/08/16 10:19:36 DEBUG : pacer: Rate limited, sleeping for 16.978727474s (5 consecutive low level retries)
2017/08/16 10:19:36 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded)
2017/08/16 10:19:36 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2017/08/16 10:19:42 DEBUG : pacer: Rate limited, sleeping for 1.844537542s (1 consecutive low level retries)
2017/08/16 10:19:42 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded)
2017/08/16 10:19:42 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2017/08/16 10:19:42 DEBUG : pacer: Rate limited, sleeping for 1.228331083s (1 consecutive low level retries)
2017/08/16 10:19:42 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded)
2017/08/16 10:19:42 DEBUG : pacer: Rate limited, sleeping for 2.086382607s (2 consecutive low level retries)
2017/08/16 10:19:42 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded)
2017/08/16 10:19:42 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2017/08/16 10:19:44 DEBUG : pacer: Rate limited, sleeping for 1.590990518s (1 consecutive low level retries)
2017/08/16 10:19:44 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded)
2017/08/16 10:19:44 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2017/08/16 10:19:44 DEBUG : pacer: Rate limited, sleeping for 1.29803824s (1 consecutive low level retries)
2017/08/16 10:19:44 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: User Rate Limit Exceeded, userRateLimitExceeded)
2017/08/16 10:19:44 DEBUG : pacer: Resetting sleep to minimum 10ms on success
^C

**Comment by bittaurus** [comment]
As soon as you see:

2017/08/16 10:19:36 DEBUG : pacer: Resetting sleep to minimum 10ms on success

It means the current transaction succeeded and it's on to the next.  Google drive seems to throttle based on current global usage level, so if it's a busier time of day you wait longer.

If you wait long enough it will eventually finish.

**Comment by ncw** [comment]
You could try `--tpslimit` also though you might need [the latest beta](https://beta.rclone.org) for that, I can't remember.

**Comment by animosity22** [comment]
Those are all pretty normal messages. If you still have a question, please feel free to post on the forums as this looks to be solved.
