### ISSUE TITLE
Copying Containers (Swift) to Object inside Bucket (S3) fails

### ISSUE THREAD

**Issue by ssshah5** [rclone/rclone#1612]
Hello,

This might not be a bug or an issue but I am just trying to gather some thoughts on whether what I am trying to achieve is possible or not.

I am trying to copy all the containers (100k +) from swift based object-store to a single bucket in a S3 based object-store where the destination object does not exist. Here is the structure:
```
Swift based OS:
container1:
 - file1
 - file2
container2:
 - file1
 - file2

Expected final results in S3 based OS
Bucket1:
 - container1/file1
 - container1/file2
 - container2/file1
 - container2/file2
```
I am trying to use the command:
`rclone sync <swift-object-store>: <s3-object-store>:<bucket-name>` and I am expecting that it would take each container from swift store and create the same structure inside the bucket in s3 object store.

Following command works
`rclone sync <swift-object-store>:<container-name> <s3-object-store>:<bucket-name>/<container-name>`
However,  the above commands requires me to input the container name for each containers (I have about 100k + containers). Of course I can write a quick shell script that runs the above command inside a for loop for each of the containers. Is there any cleaner way to achieve what I want with a simple `rclone` command and without iterating each container in a loop?

**Comment by ncw** [comment]
> Is there any cleaner way to achieve what I want with a simple rclone command and without iterating each container in a loop?

Not currently, no.

the bucket based remotes (s3, swift, b2 etc) all require you to provide a bucket to actually do data transfer - the only thing you can do without is list the buckets.

I may lift this limitation in the future as it is a bit annoying, but it would require quite a bit of rework of the remotes.

**Comment by ncw** [comment]
Rclone does now support syncing from the root of bucket based remotes.
