### ISSUE TITLE
Dropbox mount ignoring files.

### ISSUE THREAD

**Issue by compliment** [rclone/rclone#1617]
![terminus_2017-08-22_05-13-14](https://user-images.githubusercontent.com/22877365/29542549-dca2e9ec-86f8-11e7-89d7-19a8de724ae4.png)

Windows 10 64-bit
Dropbox

**Comment by breunigs** [comment]
Looks like a variant of #107 or #691.

**Comment by ncw** [comment]
Actually I think this was fixed by #1558 - can you try [the latest beta](https://beta.rclone.org)?

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
