### ISSUE TITLE
PUT.io support for rclone

### ISSUE THREAD

**Issue by Rick7C2** [rclone/rclone#1631]
I would like to see support for putio in rclone that way I can set a schedule to move all files from putio to gdrive.

I found some other programs written in golang that work with putio. Maybe it could help you implement it?
https://github.com/search?l=Go&q=putio&type=Repositories&utf8=%E2%9C%93

Also here is the API documentation for PUTio

http://api.put.io/v2/docs/index.html

I hope that you or someone could make this preferably with the ability to remote transfer without first downloading to local pc then uploading. Also with delete support when moving the files from putio.

PUT.io Also supports FTP (TLS/SSL) and WebDAV but those are readonly so no delete ability there.

**Comment by ncw** [comment]
put.io has gained read only support with webdav in #580

**Comment by dnicolson** [comment]
@ncw I think this can be closed?

**Comment by ncw** [comment]
Yes this is now it's own backend!
