### ISSUE TITLE
Wrapping rclone with a preloaded library

### ISSUE THREAD

**Issue by chechoRP** [rclone/rclone#1637]
I am writing a GNU/Linux library that users can preload before their applications which wraps system calls like socket(), connect(), etc. We use LD_PRELOAD for this. (we want to do some dynamic stuff with the network).

Wrapping applications like scp and iperf works really well, but we've run into some puzzling issues when trying to wrap rclone. It appears that some of rclone's calls are wrapped and others are not. This is extremely puzzling, but seems to (maybe?) indicate that shared libraries are somehow unloaded or not shared between your pthreads? Or perhaps rclone (via Go) is using some lower level utility than socket()/connect() for performance reasons.

I know this is a shot in the dark, but can you provide any insights on how rclone handles networking with Go? Any ideas on why a preloaded library might be unloaded/not shared between pthreads in your application (they are, in general shared, as I've written a test application which works).

Thanks!

**Comment by ncw** [comment]
The standard go runtime mostly doesn't use the shared C library - it just does linux syscalls directly.

It does uses the shared C library for some name resolution things I think.

I compile the rclone release binaries so they don't use the shared C library at all, but if you compile rclone yourself it will use the C library for that bit of name resolution.

Does that fit with your observations?

**Comment by phpHavok** [comment]
That absolutely fits our observations. Thanks very much for your response! We noticed that DNS resolutions were the only calls being wrapped. So, if I understood you correctly, there is no way to compile rclone to use the C library for all networking (only for DNS lookups)? (i.e., rclone really isn't wrappable.)

**Comment by ncw** [comment]
Hmm, you could try using [gccgo](https://golang.org/doc/install/gccgo), but I'm reasonably certain that it will do the same thing in bypassing libc and going straight for syscalls too :-(

**Comment by animosity22** [comment]
This looks answered. If you still have a question, please feel free to post on the forums.
