### ISSUE TITLE
rclone mount and TinyMediaManager issue

### ISSUE THREAD

**Issue by deadman36g** [rclone/rclone#1639]
Hello all,

I am trying to use an rclone mount and tinymediamanager together to scrape metadata for my movies straight from Google Drive

I am using the following command to mount
rclone mount -v --allow-root gdrive-macOS: GDrive/

This seems to mount OK, and I am load my movies into TMM, and rename them using TMM.

When I go to download the images I get my errors. Some of the images are downloading just fine but others are downloading as movie-fanart.jpg.1504206130725.part.

The terminal is telling me 
movie-fanart.jpg.1504206130725.part: WriteFileHandle.Write can't seek in file

Is there something I can do to fix this?

I am using rclone v1.37

**Comment by ncw** [comment]
> Is there something I can do to fix this?

Alas, not at the moment.

> WriteFileHandle.Write can't seek in file

The rclone file system is somewhat limited in that you can't open a file for write and seek in it - that is what that message is telling you.

It might be that you could write the images elsewhere first, and copy them back to work around this.

**Comment by animosity22** [comment]
This looks to be fixed in later versions. If you still have a problem, please feel free to post on the forums.
