### ISSUE TITLE
Use AWS CLI-like credentials

### ISSUE THREAD

**Issue by hauleth** [rclone/rclone#1649]
It would be great if `clone` would allow using [AWS CLI profiles](http://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html) and [AWS CLI-like environment variables](http://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html).

**Comment by ncw** [comment]
rclone does support the AWS CLI variables already, eg from `rclone config`

```
Get AWS credentials from runtime (environment variables or EC2 meta data if no env vars). Only applies if access_key_id and secret_access_key is blank.
Choose a number from below, or type in your own value
 1 / Enter AWS credentials in the next step
   \ "false"
 2 / Get AWS credentials from the environment (env vars or IAM)
   \ "true"
env_auth> 2
```

It looks like the AWS SDK supports CLI profiles using the [SharedCredentialsProvider](https://godoc.org/github.com/aws/aws-sdk-go/aws/credentials#SharedCredentialsProvider).

It is probably just a question of adding it to [this list](https://github.com/ncw/rclone/blob/master/s3/s3.go#L319), testing and writing some docs.

Fancy sending a PR?

**Comment by ncw** [comment]
Rclone does support all of these now with the `env_auth = true` parameter.
