### ISSUE TITLE
Error message has wanted and got checksums reversed

### ISSUE THREAD

**Issue by jikamens** [rclone/rclone#1654]
In b2/b2.go:

```
		return errors.Errorf("object corrupted on transfer - SHA1 mismatch (want %q got %q)", receivedSHA1, calculatedSHA1)
```

The two arguments to that error message should be the other way.

**Comment by ncw** [comment]
I think they are probably the right way round, but it is arguable!  The `receivedSHA1` is the SHA1 we got when we fetched the object details, ie what we are expecting the SHA1 to be (hence `want`) but `got` is what we actually calculated.

Maybe there are better words than want and got.

BTW if you are looking at that code then you will be interested in 8207af9460fa7984b2b013567cd20e58d0ac585d I expect!

**Comment by breunigs** [comment]
> Maybe there are better words than want and got.

maybe: source / new copy
(I assume remote would be confusing, esp. when copying from remote to remote)

**Comment by animosity22** [comment]
This was fixed. Closing out.
