### ISSUE TITLE
FTP list files and folders

### ISSUE THREAD

**Issue by poloh11** [rclone/rclone#1681]
Hi,
I encounter an issue when I want to list and sync files from FTP to FTP
When I run the command 
rclone ls datalogger1:DATA/170915 it display any files
but when I run rclone ls datalogger1:DATA/170915/* it display files

so I tried to run a sync with adding the * at the end but path is altered and rsync is trying to get the files from DATA\170915\\*\int_delta_170915.txt and not DATA\170915\int_delta_170915.txt
Could you help me ?
Thanks a lot

> What is your rclone version (eg output from `rclone -V`)
1.37
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 7, 64bits

> Which cloud storage system are you using? (eg Google Drive)
FTP to FTP

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync datalogger1:DATA/170915/* ovh:folder
because rclone sync datalogger1:DATA/170915 ovh:folder show any file

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2017/09/15 10:45:58 ERROR : Attempt 3/3 failed with 3 errors and: failed to open
 source object: open: 550 DATA\170915\*\ int_delta_170915.txt: No such file or d
irectory
2017/09/15 10:45:58 Failed to sync: failed to open source object: open: 550 DATA
\170915\*\ int_delta_170915.txt: No such file or directory

**Comment by ncw** [comment]
You can't use wildcards `*` in rclone paths.

If you want to select which files you must use [filters](https://rclone.org/filtering/).

I'm unsure whether `rclone ls datalogger1:DATA/170915` is showing files or not?  Are you saying it doesn't show any files?

**Comment by poloh11** [comment]
Hi,
"rclone ls datalogger1:DATA/170915" is not showing any file, but "rclone ls datalogger1:DATA/170915/*" show files
Thanks a lot for your help

**Comment by ncw** [comment]
Can you check with [the latest beta](https://beta.rclone.org) to see if that is the same?

Also what FTP server are you using?

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
