### ISSUE TITLE
[android, question] Mounted in chroot is not visible outside

### ISSUE THREAD

**Issue by oczkers** [rclone/rclone#1685]
I've successfully mounted gdrive in gentoo chroot but it is not visible outside chroot environment, any ideas what's the cause?

**Comment by ncw** [comment]
You probably need `--allow-other` in the options

**Comment by oczkers** [comment]
I've tried it but no luck - folder is empty even when listing as a root outside chroot

**Comment by ncw** [comment]
If you want to list as root then you need `--allow-root` too IIRC

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.

**Comment by mirfatif** [comment]
It's due to Android's isolated mount namespaces for every app. Make sure to be in root/global mount namespace before mounting. Use, e.g. `su -M` or `nsenter `t 1 -m`. Details: https://android.stackexchange.com/q/197959/218526
