### ISSUE TITLE
files-from flag does not working properly

### ISSUE THREAD

**Issue by netinial** [rclone/rclone#1689]
I confirm that files-from flag does not working properly with windows 8.1

> rclone version (1.37)

> (Windows 8.1 Pro, 64 bit)

> (Google Drive)

> .\rclone\rclone.exe sync --files-from include-paths.txt C:\Users\Amasya\Desktop\rclone-test GDrive:include-paths -vv (Running with predefined environmeltal variables.)

> 2017/09/18 18:45:04 NOTICE: Config file "C:\\Users\\Amasya\\.config\\rclone\\rclone.conf" not found - using defaults
2017/09/18 18:45:04 DEBUG : rclone: Version "v1.37" starting with parameters [".\\rclone\\rclone.exe" "sync" "--files-from" "include-paths.txt" "C:\\Users\\Amasya\\Desktop\\rclone-test" "GDrive:include-paths" "-vv"]
2017/09/18 18:45:04 DEBUG : GDrive: Saved new token in config file 2017/09/18 18:45:06 INFO  : Google drive root 'include-paths': Modify window is 1ms
2017/09/18 18:45:06 DEBUG : Kitapcik-PHP.zip: Excluded from sync (and deletion) 2017/09/18 18:45:06 DEBUG : offline_javascript_dersleri.zip: Excluded from sync (and deletion)
2017/09/18 18:45:06 DEBUG : offline_php_dersleri.zip: Excluded from sync (and deletion)
2017/09/18 18:45:06 DEBUG : PHP_Kitap.zip: Excluded from sync (and deletion)
2017/09/18 18:45:06 DEBUG : Yeni Metin Belgesix.txt: Excluded from sync (and deletion)
2017/09/18 18:45:06 INFO  : Google drive root 'include-paths': Waiting for checks to finish
2017/09/18 18:45:06 INFO  : Google drive root 'include-paths': Waiting for transfers to finish
2017/09/18 18:45:06 INFO  : Waiting for deletions to finish
2017/09/18 18:45:06 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        2.2s

2017/09/18 18:45:06 DEBUG : Go routines at exit 7
2017/09/18 18:45:06 DEBUG : rclone: Version "v1.37" finishing with parameters [".\\rclone\\rclone.exe" "sync" "--files-from" "include-paths.txt" "C:\\Users\\Amasya\\Desktop\\rclone-test" "GDrive:include-paths" "-vv"]

**Comment by ncw** [comment]
What did you expect to happen?  And what actually happened?  What is the contents of `include-paths.txt`?

**Comment by netinial** [comment]
include-paths.txt includes another directory path which is C:\Users\Amasya\Desktop\rclone-test-2

I was expecting this paths will sync with gdrive also.

But sync failed.

**Comment by netinial** [comment]
I confirm that files-from flag does not working properly with **v1.38** also

**Comment by netinial** [comment]
I confirm that **--filter-from filter-file.txt** flag does not working with v1.38 on windows also.
.\rclone\rclone.exe sync --filter-from filter-file.txt D:\Active-Sync\rclone-test GDrive:backup -vv

**Comment by netinial** [comment]
This is my filter-file.txt
+ D:\Active-Sync\rclone-test2\**

**Comment by netinial** [comment]
Problem is causing when path is not inside defined variable. Otherwise cmd is working properly

**Comment by animosity22** [comment]
This looks solved. Closing out.
