### ISSUE TITLE
feature request: support for anonymously shared remotes

### ISSUE THREAD

**Issue by karlkleinpaste** [rclone/rclone#1690]
My most productive use case for rclone would be for rclone users to get anonymous access to others' storage, as made available through e.g. Google Drive "get a shareable link" selection, giving a link for access to that resource that's usable read-only by anyone with the link.  That is, I would like a remote to be configurable using such a supplied link, asking no authentication since it's not presumed that the rclone user in this case even has his own account with the same provider.

This would make it easy to provide things like dataset archives to a wide population easily.  "Feed this URL to rclone config, then rclone mount and copy what you need." The remote type should be discernible from the URL because it includes the provider host.

(I crawled through several pages of the issues list, didn't find anything that looked like this, so I hope this isn't a dupe request.)

**Comment by timofonic** [comment]
@karlkleinpaste I'm just a curious lurker, but I found your idea interesting. I'm not a developer at all, I'm going to a vocational school to study programming this month :P 

How do you imagine this to be possible? Are those links usable without login to Google Drive? The same would be interesting for other services such as MEGA, maybe yankex and mail.ru clouds too?

I'm sure the boss @ncw is busy with lots of stuff and he needs to priorize, but I would love to know what he thinks about this. This could make rclone useful by many different use cases, in my opinion.

**Comment by karlkleinpaste** [comment]
I experimented with deleting all Google cookies in Firefox, then used Chrome to go to my Google Drive, got a shareable link for something, and pasted that link into Firefox.  *poof*  There's my shared content in Firefox, without having logged into Google at all.  So yeah, this makes for a really obvious use case of unauthenticated access to others' storage.

I haven't experimented with other storage providers, so I don't know whether they too offer this kind of shareable link usable by anybody, logged in or not.

**Comment by gustavorochakv** [comment]
What's wrong with adding that folder to your drive and simply uploading as usual?

**Comment by karlkleinpaste** [comment]
"adding that folder to your drive" supposes that the intended user of the shared storage has his own account on that storage provider to begin with. My goal here is to be able to share files via rclone to users who don't have an account on the storage provider. See "asking no authentication" from original discussion.

**Comment by gustavorochakv** [comment]
Will those users who don't have a Google account also need to upload content to that folder using rclone? 

If the answer is no, then you could simply add that folder to your own drive (regardless of who is the owner) and upload content to it using rclone. The folder would continue to be shared publicly, so any content you upload would be available to everyone, regardless of whether they are authenticated or even have a Google account.


If the answer is yes, meaning you need users to upload files to a public folder anonymously, then that would indeed require changes to rclone. I know the Google Drive API allows unauthed users to list the content of public folders, but I'm not so sure whether it allows uploading new content.

**Comment by karlkleinpaste** [comment]
I feel as though you're not getting my use case at all.
That's the 2nd time you've said "add it to to your own drive" which is exactly what is NOT the use case.
I have large amounts of data in my Google drive that I wish to make available to a wide audience. Joe Random, who does not have a Google drive at all, can be handed a URL from me that is my "shareable link" to some piece of my space.
I would like Joe to be able to configure an rclone remote using that shareable link, without rclone asking Joe to login, as it currently does, since he has no Google Drive account in the 1st place. Joe cannot "add it to his own drive" because he has no drive.

**Comment by ncw** [comment]
If you know the folder_id then you can use it with the `--drive-root-folder-id` flag. I think these are in shareable links.

**Comment by turkeyphant** [comment]
> If you know the folder_id then you can use it with the `--drive-root-folder-id` flag. I think these are in shareable links.

Doesn't work. ```rclone config``` requires you to go through google ```oauth2``` and verify an acccount.

**Comment by calisro** [comment]
You want to be able to do this without any authentication in the config at all.  I don't think that is possible.  That being said, you can use an existing account (really any account! )  and use the --drive-root-folder-id  to get the content.  

root@s163042:~# rclone lsf zonegd: --drive-root-folder-id=1mcbsA8fbd09XQjDS8xx-Dsu9BwI1ZWAW
hi.txt

**Comment by turkeyphant** [comment]
> You want to be able to do this without any authentication in the config at all. I don't think that is possible. 

I agree, that seems to be the aim of the OP. But why wouldn't it be possible? You can access the same content via the web interface without any authentication at all.

**Comment by ncw** [comment]
I don't think it is possible to use the Google Drive API without authentication

From https://developers.google.com/drive/api/v3/about-auth
> Every request your application sends to the Drive API must include an authorization token. The token also identifies your application to Google.

Google have a whole heap of private APIs for google drive which the web frontend is based on which can do special things no doubt. (Google is not fond of eating its own dog food!)

**Comment by karlkleinpaste** [comment]
yeah, i'm afraid the idea is ultimately a non-starter. regrets.

**Comment by turkeyphant** [comment]
> I don't think it is possible to use the Google Drive API without authentication
> 
> From https://developers.google.com/drive/api/v3/about-auth
> 
> > Every request your application sends to the Drive API must include an authorization token. The token also identifies your application to Google.
> 
> Google have a whole heap of private APIs for google drive which the web frontend is based on which can do special things no doubt. (Google is not fond of eating its own dog food!)

Ah, that explains things. Fair enough.
