### ISSUE TITLE
409 Conflict error with ACD 

### ISSUE THREAD

**Issue by isaiah36** [rclone/rclone#1692]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
v1.37
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu Linux x64
> Which cloud storage system are you using? (eg Google Drive)
ACD
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
sync
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

``2017/09/18 14:31:47 ERROR : amazon drive root 'Music': not deleting files as there were IO errors
2017/09/18 14:31:47 ERROR : Attempt 1/3 failed with 1 errors and: HTTP code 409: "409 Conflict": response body: "{\"logref\":\"c3a60d50-9c9c-11e7-8e85-0be2b355f1e7\",\"message\":\"Node with the name front.jpg already exists under parentId ugamvglWQLCt0cWwDa8tNA conflicting NodeId: OTrbcdf2RC2orieDn4ROpQ\",\"code\":\"NAME_ALREADY_EXISTS\",\"info\":{\"nodeId\":\"OTrbcdf2RC2orieDn4ROpQ\"}}"

**Comment by ncw** [comment]
This is probbly amazon drives eventual consistency which causes problems like that.

However rclone should have retried and cleared up the error

**Comment by isaiah36** [comment]
It repeated the error for several days. I worked around it by removing the remote file via web browser. It's doing the same thing on another sync job. It is failing to update remote files when the local file has changed in size.

**Comment by animosity22** [comment]
ACD is dead :(
