### ISSUE TITLE
Feature Request - Show Remaining Traffic

### ISSUE THREAD

**Issue by Massaguana** [rclone/rclone#1702]
Hello Nick,

is it possible to add the Information in "-v" how many Traffic are remaining to complete the running transfer?

Thanks for your work...

Massaguana

**Comment by ncw** [comment]
To do this properly it requires traversing the data twice, so it would need another flag I think.

The stats that are printed every minute show how much time each individual file is expected to take.

**Comment by timofonic** [comment]
@ncw What do you mean by "flag"? Is is a programming/networking terminology?

**Comment by Massaguana** [comment]
"-v" is an flag or "-vv" also...

**Comment by timofonic** [comment]
@Massaguana  Oh! I thought that first but realized to be low-level protocol stuff! Thanks and sorry for being so dumb :D

**Comment by Massaguana** [comment]
an another flag are also nice... or something like an "simulation mode" to see what happens bevor real data are in traffic

**Comment by ncw** [comment]
This is done now :-)
