### ISSUE TITLE
dropbox: allow permanent delete of files - generalise --drive-use-trash and --b2-hard-delete

### ISSUE THREAD

**Issue by zenjabba** [rclone/rclone#1704]
Offer the option to bypass trash holding for dropbox both in sync and mount.

Eg "https://api.dropboxapi.com/2/files/permanently_delete"

[API Docs](https://www.dropbox.com/developers/documentation/http/documentation#files-permanently_delete)

**ncw edit** - we now have `--drive-use-trash` and `--b2-hard-delete` which control a similar feature - it is now time to generalise this for dropbox and maybe other remotes

**Comment by NumberedThought** [comment]
Would really love to see this one  +1

**Comment by hthighway** [comment]
This would be a welcome addition to the current dropbox support

**Comment by ncw** [comment]
Good idea.  I might make a general flag --permanent-delete which can be used with all the remotes which support this sort of thing, with rclone defaulting to using the trash.

**Comment by ivandeex** [comment]
Closing after 3 years of inactivity

**Comment by zenjabba** [comment]
Your kidding right, they closed it as "completed" after nothing got done.

**Comment by durmonator** [comment]
@ncw you have a flag for jotta, b2 and drive, why not dropbox, can you at least give us an answer, thanks

**Comment by ncw** [comment]
If someone want to send a pull request for this, that would be great. I'd be happy to talk you through it.

**Comment by drpoutine** [comment]
was this ever implemented?

**Comment by ncw** [comment]
There are individual flags for each backend. These can be set in the config file also.

      --b2-hard-delete           Permanently delete files on remote removal, otherwise hide files
      --jottacloud-hard-delete   Delete files permanently rather than putting them into the trash
      --mega-hard-delete         Delete files permanently rather than putting them into the trash
      --quatrix-hard-delete      Delete files permanently rather than putting them into the trash
      --sugarsync-hard-delete    Permanently delete files if true
      --yandex-hard-delete       Delete files permanently rather than putting them into the trash
