### ISSUE TITLE
Feature Request: force ipv4 usage for google drive

### ISSUE THREAD

**Issue by qrenz** [rclone/rclone#1711]
Lately a few of my VPS' have been having issues connecting to google drive via ipv6, forcing ipv4 usage would be an easy fix for this issue that is not already included.

**Comment by zenjabba** [comment]
You could turn off IPV6 on your VPS...

`sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1`
`sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1`

if that works put the following at the bottom of `/etc/sysctl.conf`

`net.ipv6.conf.all.disable_ipv6 = 1`
`net.ipv6.conf.default.disable_ipv6 = 1`
`net.ipv6.conf.lo.disable_ipv6 = 1`

then do `sysctl -p`

**Comment by ncw** [comment]
Or use `--bind` to bind to a local IPv4 address...

**Comment by ncw** [comment]
Another approach would be to edit `/etc/gai.conf` which I think rclone will honor, to make IPv4 preferred

**Comment by qrenz** [comment]
--bind is a great solution for this. Didn't notice it's addition in 1.38 when I had posted this. My bad...

**Comment by animosity22** [comment]
This was solved. Closing out.
