### ISSUE TITLE
If a file is being uploaded in chunks, parallel transfers should only upload chunks for that file instead of uploading other files

### ISSUE THREAD

**Issue by ORYLY** [rclone/rclone#1713]
I'm on a slow connection, uploading a directory with a few 2+ GB files to B2 using relatively small chunks (32 MB). I noticed that sometimes my pool of parallel transfers will start uploading chunks for two different files instead of uploading chunks for a single file that's not yet done.

This doesn't affect the result, but it lengthens the time for a big chunked file's upload to complete. This is a bit of an issue for slow connections, because a file's upload completion acts as a checkpoint to resume from if the sync fails or is paused.

I've played around with B2. I'm not sure if the implementations on other remotes work the same way.

**Comment by ncw** [comment]
If you set `--transfers 1` it will stop doing that.  That probably isn't what you wanted though...

I take your point about the checkpoint, however setting the number of large files to be transferred at once to one would be disadvantageous for some users I think.

**Comment by ORYLY** [comment]
> If you set `--transfers 1` it will stop doing that. That probably isn't what you wanted though...

Yeah, there are cases when a single transfer's upload bandwidth is less than the actual usable bandwidth because of something in the ISP/network/remote. Multiple transfers puts that bandwidth to use.
