### ISSUE TITLE
Cannot upload large files to Backblaze

### ISSUE THREAD

**Issue by ilinuxadmin** [rclone/rclone#1715]
I cannot upload large files (60-100GB) into BackBlaze B2 with rclone.

My environment : 
OS = Debian 9 x64
rclone version =  1.38
Cloud Storage = BackBlaze B2

The command I run 
`rclone copy -vvv sp1/WEEKLY-BACKUP_20170811_Full_v1.pbd b2:MyBucket/sp1`

Output
>2017/10/04 04:40:35 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2017/10/04 04:40:35 DEBUG : rclone: Version "v1.38" starting with parameters ["rclone" "copy" "-vvv" "sp1/WEEKLY-BACKUP_20170811_Full_v1.pbd" "b2:MyBucket/sp1"]
2017/10/04 04:40:36 INFO  : B2 bucket MyBucket path sp1/: Modify window is 1ms
2017/10/04 04:40:36 DEBUG : MONTHLY-BACKUP_20170501_Full_v1.pbd: Excluded from sync (and deletion)
2017/10/04 04:40:36 DEBUG : SP1: Excluded from sync (and deletion)
2017/10/04 04:40:36 DEBUG : MONTHLY-BACKUP_20170901_Full_v1.pbd: Excluded from sync (and deletion)
2017/10/04 04:40:36 DEBUG : MONTHLY-BACKUP_20170801_Full_v1.pbd: Excluded from sync (and deletion)
2017/10/04 04:40:36 DEBUG : SP1: Excluded from sync (and deletion)
2017/10/04 04:40:36 INFO  : B2 bucket MyBucket path sp1/: Waiting for checks to finish
2017/10/04 04:40:36 INFO  : B2 bucket MyBucket path sp1/: Waiting for transfers to finish
2017/10/04 04:41:36 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m0.9s
Transferring:
            WEEKLY-BACKUP_20170811_Full_v1.pbd:  0% done, 0 Bytes/s, ETA: -
2017/10/04 04:42:36 INFO  : 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      2m0.9s
Transferring:
            WEEKLY-BACKUP_20170811_Full_v1.pbd:  0% done, 0 Bytes/s, ETA: -
>

and it will continue like this without transferring any data!

Any idea how to fix this?

**Comment by storrgie** [comment]
as a temporary workaround use a different archive format that supports splitting?

**Comment by ncw** [comment]
How long did you wait?  rclone has to sha1 the whole file before uploading it which might take some time for a 60GB file.

**Comment by ilinuxadmin** [comment]
I waited for almost an hour!
Is there anyway to skip the checksum calculation? (just to make sure that this is not the case)

**Comment by ncw** [comment]
--b2-disable-checksum                  Disable checksums for large (> upload cutoff) files

Is how you disable the checksum.
