### ISSUE TITLE
504 GATEWAY_TIMEOUT

### ISSUE THREAD

**Issue by phantomsixthplayer** [rclone/rclone#1721]
Not sure how to resolve the below issue, any assistance welcome!

> What is your rclone version (eg output from `rclone -V`)
rclone: Version "v1.38"

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows Server 2012 R2, 64 bit

> Which cloud storage system are you using? (eg Google Drive)
Amazon Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy E:\Updates\Files acd:uploaded -vv

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2017/10/07 10:10:26 DEBUG : Controller/Ghost.zip: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 504: "504 GATEWAY_TIMEOUT": no response body ("504 GATEWAY_TIMEOUT")
2017/10/07 10:10:26 DEBUG : Controller/Ghost.zip: Object not found - waiting (1/840)
2017/10/07 10:10:32 DEBUG : Controller/Ghost.zip: Object not found - waiting (2/840)
2017/10/07 10:10:37 DEBUG : Controller/Ghost.zip: Object not found - waiting (3/840)
2017/10/07 10:10:42 DEBUG : Controller/Ghost.zip: Object not found - waiting (4/840)
2017/10/07 10:10:47 DEBUG : Controller/Ghost.zip: Object not found - waiting (5/840)
2017/10/07 10:10:52 DEBUG : Controller/Ghost.zip: Object not found - waiting (6/840)
2017/10/07 10:10:57 DEBUG : Controller/Ghost.zip: Object not found - waiting (7/840)
2017/10/07 10:11:02 DEBUG : Controller/Ghost.zip: Object found with correct size 25025314816 after waiting (8/840) - 35s - returning with no error
2017/10/07 10:11:02 INFO  : Controller/Ghost.zip: Copied (new)
2017/10/07 10:11:02 INFO  :
Transferred:   23.307 GBytes (12.058 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:    32m59.2s

2017/10/07 10:11:02 DEBUG : Go routines at exit 7
2017/10/07 10:11:02 DEBUG : rclone: Version "v1.38" finishing with parameters ["rclone" "copy" "E:\\Updates\\Files" "acd:uploaded" "-vv"]

**Comment by ncw** [comment]
Rclone handled that error for you. Notice no error logs or counted errors.

So I think everything is working

**Comment by animosity22** [comment]
This looks to be a question. If you have anything else, please use the forums.
