### ISSUE TITLE
[request] add support for RIAK

### ISSUE THREAD

**Issue by nagualcode** [rclone/rclone#1728]
Riak seems to be a very fast and scalable tool to deliver huge ammounts of files.
It would be great to have native client support on rclone.
Thank you.

**Comment by ncw** [comment]
Which riak product do you mean?  riak-s2 or something else?

Unfortunately I saw that [bash have gone into receivership](https://www.theregister.co.uk/2017/07/31/end_of_the_road_for_basho_as_court_puts_biz_into_receivership/).  I don't know which technologies their new owners are going to continue with.

**Comment by nagualcode** [comment]
Actually Riak-KV (http://basho.com/products/riak-kv/).

I do believe Riak may be continued by the new owners, since it has a wide adoption.

**Comment by nagualcode** [comment]
Open source here we go :)
https://www.theregister.co.uk/2017/08/25/bet365_to_buy_basho_release_code/

**Comment by ivandeex** [comment]
Zero interest from people since 3 years.
Closing.
cc @ncw
