### ISSUE TITLE
Can't play file ACD

### ISSUE THREAD

**Issue by giacomofabbri** [rclone/rclone#1729]
Hi ncw! Thanks for everything you made, I'm trying to use Amazon Cloud Drive till they "ban" it forever, but since last days I'm getting some error and I'm not able to play any file, even if I try to download the file using the mounted directory I'm not able to download it!
Please help me, thanks so much!
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.38
- os/arch: linux/amd64
- go version: go1.9

> Which cloud storage system are you using? (eg Google Drive)
Amazon Cloud Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount acd:/ /home/plex/.acd-sorted/ --acd-templink-threshold=0 -vv --log-file=.rclone.log
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2017/10/09 11:37:19 DEBUG : Using config file from "/home/plex/.rclone.conf"
2017/10/09 11:37:19 DEBUG : rclone: Version "v1.38" starting with parameters ["rclone" "mount" "acd:/" "/home/plex/.acd-sorted/" "--acd-templink-threshold=0" "-vv" "--log-file=.rclone.log"]
2017/10/09 11:37:20 INFO  : amazon drive root '': Modify window not supported
2017/10/09 11:37:20 DEBUG : amazon drive root '': Mounting on "/home/plex/.acd-sorted/"
2017/10/09 11:37:20 mount helper error: fusermount: failed to open /etc/mtab: Permission denied
2017/10/09 11:37:20 DEBUG : : Root:
2017/10/09 11:37:20 DEBUG : : >Root: node=/, err=<nil>
2017/10/09 11:37:51 DEBUG : /: Lookup: name="I32X95z89TYOAPbarD6p7Ge2"
2017/10/09 11:37:51 DEBUG : /: >Lookup: node=I32X95z89TYOAPbarD6p7Ge2/, err=<nil>
2017/10/09 11:37:51 DEBUG : I32X95z89TYOAPbarD6p7Ge2/: Attr:
2017/10/09 11:37:51 DEBUG : I32X95z89TYOAPbarD6p7Ge2/: >Attr: attr=valid=1m0s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
2017/10/09 11:37:51 DEBUG : I32X95z89TYOAPbarD6p7Ge2/: Lookup: name="XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21"
2017/10/09 11:37:52 DEBUG : I32X95z89TYOAPbarD6p7Ge2/: >Lookup: node=I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/, err=<nil>
2017/10/09 11:37:52 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/: Attr:
2017/10/09 11:37:52 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/: >Attr: attr=valid=1m0s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
2017/10/09 11:37:52 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/: Lookup: name="pZFXSlJMWK5nJyvr3bgik-pS"
2017/10/09 11:37:52 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/: >Lookup: node=I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/pZFXSlJM$
2017/10/09 11:37:52 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/pZFXSlJMWK5nJyvr3bgik-pS/: Attr:
2017/10/09 11:37:52 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/pZFXSlJMWK5nJyvr3bgik-pS/: >Attr: attr=valid=1m0s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
2017/10/09 11:37:53 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/pZFXSlJMWK5nJyvr3bgik-pS/: Lookup: name="85pJzC1aa,iSewSzqT1ZdEhW55oSXMWMPsvHZhe1RE2dxK6yxL6Ct6JkfZI9atjBgQ0"
2017/10/09 11:37:53 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/pZFXSlJMWK5nJyvr3bgik-pS/: >Lookup: node=I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxp$
2017/10/09 11:37:53 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/pZFXSlJMWK5nJyvr3bgik-pS/85pJzC1aa,iSewSzqT1ZdEhW55oSXMWMPsvHZhe1RE2dxK6yxL6Ct6JkfZI9atjBgQ0: Attr:
2017/10/09 11:37:53 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/pZFXSlJMWK5nJyvr3bgik-pS/85pJzC1aa,iSewSzqT1ZdEhW55oSXMWMPsvHZhe1RE2dxK6yxL6Ct6JkfZI9atjBgQ0: >Attr: a=valid=1m0s ino$
2017/10/09 11:37:53 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/pZFXSlJMWK5nJyvr3bgik-pS/85pJzC1aa,iSewSzqT1ZdEhW55oSXMWMPsvHZhe1RE2dxK6yxL6Ct6JkfZI9atjBgQ0: Open: flags=OpenReadOnly
2017/10/09 11:37:53 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/pZFXSlJMWK5nJyvr3bgik-pS/85pJzC1aa,iSewSzqT1ZdEhW55oSXMWMPsvHZhe1RE2dxK6yxL6Ct6JkfZI9atjBgQ0: >Open: fh=I32X95z89TYOA$
2017/10/09 11:37:53 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/pZFXSlJMWK5nJyvr3bgik-pS/85pJzC1aa,iSewSzqT1ZdEhW55oSXMWMPsvHZhe1RE2dxK6yxL6Ct6JkfZI9atjBgQ0 (r): Read: len=16384, of$
2017/10/09 11:37:53 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/pZFXSlJMWK5nJyvr3bgik-pS/85pJzC1aa,iSewSzqT1ZdEhW55oSXMWMPsvHZhe1RE2dxK6yxL6Ct6JkfZI9atjBgQ0: Downloading large objec$
2017/10/09 11:37:54 DEBUG : pacer: Rate limited, sleeping for 463.099863ms (1 consecutive low level retries)
2017/10/09 11:37:54 DEBUG : pacer: low level retry 1/10 (error <nil>)
2017/10/09 11:37:54 DEBUG : pacer: Rate limited, sleeping for 1.682903712s (2 consecutive low level retries)
2017/10/09 11:37:54 DEBUG : pacer: low level retry 2/10 (error <nil>)
2017/10/09 11:37:55 DEBUG : pacer: Rate limited, sleeping for 2.187022816s (3 consecutive low level retries)
2017/10/09 11:37:55 DEBUG : pacer: low level retry 3/10 (error <nil>)
2017/10/09 11:37:56 DEBUG : pacer: Rate limited, sleeping for 2.701639055s (4 consecutive low level retries)
2017/10/09 11:37:56 DEBUG : pacer: low level retry 4/10 (error <nil>)
2017/10/09 11:37:59 DEBUG : pacer: Rate limited, sleeping for 14.353380727s (5 consecutive low level retries)
2017/10/09 11:37:59 DEBUG : pacer: low level retry 5/10 (error <nil>)
2017/10/09 11:38:01 DEBUG : pacer: Rate limited, sleeping for 21.390775807s (6 consecutive low level retries)
2017/10/09 11:38:01 DEBUG : pacer: low level retry 6/10 (error <nil>)
2017/10/09 11:38:16 DEBUG : pacer: Rate limited, sleeping for 1m2.355363344s (7 consecutive low level retries)
2017/10/09 11:38:16 DEBUG : pacer: low level retry 7/10 (error <nil>)
2017/10/09 11:38:37 DEBUG : pacer: Rate limited, sleeping for 32.094238372s (8 consecutive low level retries)
2017/10/09 11:38:37 DEBUG : pacer: low level retry 8/10 (error <nil>)
2017/10/09 11:39:40 DEBUG : pacer: Rate limited, sleeping for 2m6.796952662s (9 consecutive low level retries)
2017/10/09 11:39:40 DEBUG : pacer: low level retry 9/10 (error <nil>)
2017/10/09 11:40:11 DEBUG : pacer: Rate limited, sleeping for 2m26.377979549s (10 consecutive low level retries)
2017/10/09 11:40:11 DEBUG : pacer: low level retry 10/10 (error <nil>)
2017/10/09 11:40:12 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/pZFXSlJMWK5nJyvr3bgik-pS/85pJzC1aa,iSewSzqT1ZdEhW55oSXMWMPsvHZhe1RE2dxK6yxL6Ct6JkfZI9atjBgQ0 (r): >Read: read=-1, err$
2017/10/09 11:40:12 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/pZFXSlJMWK5nJyvr3bgik-pS/85pJzC1aa,iSewSzqT1ZdEhW55oSXMWMPsvHZhe1RE2dxK6yxL6Ct6JkfZI9atjBgQ0 (r): Read: len=4096, off$
2017/10/09 11:40:12 DEBUG : I32X95z89TYOAPbarD6p7Ge2/XBEGuj2kBs9Dynqk4MWhoMFFjFC12y1GDPJkUNIvePFsUzGtjxpIKnyUfVdgh4EUT21/pZFXSlJMWK5nJyvr3bgik-pS/85pJzC1aa,iSewSzqT1ZdEhW55oSXMWMPsvHZhe1RE2dxK6yxL6Ct6JkfZI9atjBgQ0: Downloading large objec$

**Comment by ncw** [comment]
It looks like Amazon's API servers had a hiccough.  Is it working again now?

**Comment by giacomofabbri** [comment]
Nope! Not working at all, now if I try just to ls the acd directory my terminal gets unresponsive! So that's a no

**Comment by ncw** [comment]
Did you try restarting the mount?

Does `rclone lsd -vv acd:` list your directories?

**Comment by giacomofabbri** [comment]
That's what I get

> 2017/10/10 23:49:05 DEBUG : Using config file from "/home/plex/.config/rclone/rclone.conf"
2017/10/10 23:49:05 DEBUG : rclone: Version "v1.38" starting with parameters ["rclone" "lsd" "-vv" "acd:"]
2017/10/10 23:49:06 INFO  : amazon drive root '': Modify window not supported
          -1 2017-10-08 17:11:14        -1 I32X95z89TYOAPbarD6p7Ge2
          -1 2017-10-03 23:26:46        -1 KrOlSVh-zfQ3LYvwKjgdGgIM
          -1 2017-09-30 01:23:05        -1 Yih9Uqt9x3Df7UL0wCZiKyZN
          -1 2017-09-08 01:24:41        -1 ft16k5Op3-NwaPy07TChBD4b
2017/10/10 23:49:06 DEBUG : Go routines at exit 8
2017/10/10 23:49:06 DEBUG : rclone: Version "v1.38" finishing with parameters ["rclone" "lsd" "-vv" "acd:"]

And right now I'm even trying to download using rclone copy but it doesn't seem to work or maybe it's downloading very slowly even with a 1Gbps

**Comment by giacomofabbri** [comment]
Actually it's copying the file but it's extremely slow! Is there a way to enhance the "download" speed?

**Comment by jmck** [comment]
I think Amazon might have tightened the API limits causing temporary blocks.  I'm not even able to download files from Amazon Drive web interface in Chrome and I'm seeing error 429s in the console:

"Failed to load resource: the server responded with a status of 429 (Too Many Requests)"

I eventually got unblocked after a certain amount of time and have not gotten blocked again.  I'm trying to raise the issue with Amazon support and now have to do phone support.

I only had 3-4 streams going at once.

**Comment by giacomofabbri** [comment]
Let me know if you have any update from Amazon phone support and I'll wait also for a response from @ncw 
P.S. Right now I'm trying to transfer all my file from amazon to google drive, I'm halfway but I can't continue due to amazon throttling!! I hope to solve the problem!

**Comment by jmck** [comment]
it also seems directory/file listing is working but 0 bytes will transferred.

**Comment by giacomofabbri** [comment]
I was able to download a file from my acd using rclone but it was downloading very slowly!!

**Comment by animosity22** [comment]
Legacy ACD issue. Closing out.
