### ISSUE TITLE
Error opening MS Office documents (or their gdoc versions) from the fuse mount of a gdrive remote

### ISSUE THREAD

**Issue by sheepdestroyer** [rclone/rclone#1732]
Hi,

I am on fedora 26, using both release 1.38 and last git revisions of rclone.
LibreOffice is version 5.3.6.1 (did not try v5.4.x yet, will need to wait fedora 27 for that).

When trying to open MS Office docs from a fuse mount of a gdrive remote, I get the followinf error message from LibreOffice : `General input/output error while accessing /home/sheepdestroyer/Vrac/interactiv/Gdrive-Mount/ICS_CNX_EXP-Meeting - 20170920-ORI.docx.`

If trying to open the gsheet version, I get the same error : `General input/output error while accessing /home/sheepdestroyer/Vrac/interactiv/Gdrive-Mount/ICS_CNX_EXP-Meeting - 20170920-ORI.docx.docx.`

I have the same problem with vsd files (which should not get converted anyway) : `General input/output error while accessing /home/sheepdestroyer/Vrac/interactiv/Gdrive-Mount/Procs/Copy of NET_L3.vsd.`

I can directly open .txt files ; but their gdoc versions get renamed .txt.docx and I get the same error trying to open them : `General input/output error while accessing /home/sheepdestroyer/Vrac/interactiv/Gdrive-Mount/Procs/arai2c.txt.docx.`

Precision : I can open these documents if I first make a copy of them from my fuse mount to local folder first.

**Comment by ncw** [comment]
rclone mount doesn't support reading and writing from files at the same time which is probably what MS Office is doing.

So copy them out the mount first would be my advice.

This may get fixed in the future :-)

**Comment by Uldiniad** [comment]
any news regarding this? LibreOffice opens a blank document in my case (both OneDrive personal and business). Copying from the mount to a local folder is viable but inconvenient.

**Comment by Uldiniad** [comment]
I've tried `--vfs-cache-mode writes` and `full` without success on 1.44. In both cases LibreOffice displays an empty document. Should I open a new issue?

**Comment by ncw** [comment]
I managed to replicate this with `--vfs-cache-mode writes` and `full` with google drive.

I get "this document is corrupted" when I try to open it though and a blank doc the second time.

Mount with

    rclone --vfs-cache-mode full -vv --dump headers mount drive: /mnt/tmp/ 2>&1 | tee mount5.log

Open the doc with

    libreoffice /mnt/tmp/test/test.odt

I've attached a log of the problem - I can't see what is going on though!

[mount5.log](https://github.com/ncw/rclone/files/2565753/mount5.log)

This points to a bug in the VFS or libreoffice doing something really strange - any ideas @B4dM4n ?

**Comment by lvh** [comment]
FWIW `file something.docx` lists it as empty :)

**Comment by lvh** [comment]
Also, this happens when copying as well as when syncing so I think the vfs/mount tag may not be accurate.

**Comment by ncw** [comment]
Hmm, I don't think opening Google docs through `rclone mount` will work.

Previous versions of rclone used to attempt to work out the size of the converted google doc and use that.  However we found that the size could vary which mean that the filesystem thought it was 100 bytes long, but when it was downloaded it was only 99 or 101 bytes of data which lead to corruptions.

To fix this we marked all google docs as having an indeterminate size.  This size appears as 0 in `rclone mount`.

So I think we should document this and close this issue most likely.


@lvh wrote
> Also, this happens when copying as well as when syncing so I think the vfs/mount tag may not be accurate.

Not sure what you mean by that?  google docs should be copied with `rclone copy` just fine?

**Comment by Uldiniad** [comment]
just as a reminder, it does not seem to be exclusive to gdrive. i have the same issues on onedrive remotes

**Comment by ncw** [comment]
> just as a reminder, it does not seem to be exclusive to gdrive. i have the same issues on onedrive remotes

Good point. Onedrive docs also have an unknown length until downloaded.

I guess the options are any or all of
- document this in the mount docs
- don't display these files in mount
- give an error when trying to read these files

File systems really hate the idea of files that they don't know the length of so maybe not displaying them is the best solution.

A patch like this could help in theory, but it didn't because google docs don't support range requests which the vfs layer uses...

```
--- a/cmd/mount/file.go
+++ b/cmd/mount/file.go
@@ -79,6 +79,12 @@ func (f *File) Open(ctx context.Context, req *fuse.OpenRequest, resp *fuse.OpenR
                resp.Flags |= fuse.OpenNonSeekable
        }
 
+       // Bypass the page cache for 0 size files which might be
+       // indeterminate sized google docs
+       if f.File.Size() == 0 {
+               resp.Flags |= fuse.OpenDirectIO
+       }
+
        return &FileHandle{handle}, nil
 }
 
```

**Comment by ncw** [comment]
I've merged a fix which will make it so you can `cat` google drives from a mount at least.  I don't think you'll be able to double click on them though...

**Comment by ivandeex** [comment]
Resolved by commit https://github.com/rclone/rclone/commit/4e4feebf0a25cf5fefd2fa01698e593851708135 via https://github.com/rclone/rclone/issues/1732#ref-commit-4e4feeb
