### ISSUE TITLE
Dropbox application access

### ISSUE THREAD

**Issue by reinierkors** [rclone/rclone#1738]
> What is your rclone version (eg output from `rclone -V`)
```
rclone v1.38
- os/arch: linux/amd64
- go version: go1.9
```

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu, 64bit

> Which cloud storage system are you using? (eg Google Drive)

Dropbox

How can I use rclone with only application folder access? I don't want it to have full access to my whole business account. I have setup an app, with an app key & secret, but it still asks me for the access token (and full access) when I try to setup the instance.

Thanks!

**Comment by ncw** [comment]
Normally this access is done with oauth scopes, but I think dropbox does this by what scopes you made the app with.  So did you make your app with only app folder scope?

It is possible you'd need to recompile rclone and change [the scopes](https://github.com/ncw/rclone/blob/master/dropbox/dropbox.go#L55) - I'm not 100% sure.

**Comment by reinierkors** [comment]
Yes, it only has an app folder scope. I used to have rclone setup correctly, but since the recent oauth changes it does not longer work.

**Comment by iampeter** [comment]
I managed get to work pasting `{"access_token":"your-token-generated-at-the-app-page","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}` as `result` during configuration process.

**Comment by ncw** [comment]
@iampeter thanks for the work-around
