### ISSUE TITLE
Bundling of small files

### ISSUE THREAD

**Issue by lbtuda** [rclone/rclone#1739]
Hi, one major drawback when using rclone to sync to the cloud is that small files are way to slow.

There are other cloud software tools which have solved this by bundling, which would be a cool feature for rclone. Maybe it can be implemented like the crypt module?

My idea:
- upload: chain multiple small files to a large file (configurable limit), save the location of each file in an index file (per directory?). 
- download: get the index file in the required directory, lookup the byte range of the target file. Then make an ranged request (ex: [https://stackoverflow.com/questions/10303126/how-does-google-drive-api-support-content-range-for-download-requests](https://stackoverflow.com/questions/10303126/how-does-google-drive-api-support-content-range-for-download-requests)) on the block file.
- modify: this is the most complex part. I would implement two styles, one for unlimited storage drives in which i would upload the manipulated file and change its location in the index file to the new file. The old bundle can stay unmodified because of the unlimited storage (maybe offer an rebundle option). Second version is for limited storage space. in this case the "blocksize" should be set lower because it would require an deletion and reupload of the whole block. 

Maybe Example implementation:
[https://github.com/restic/restic/issues/56](https://github.com/restic/restic/issues/56)

Greetings 
Lukas

**Comment by ncw** [comment]
I think this is out of scope for rclone.

Rclone integrates really well with restic now, so I'd suggest using rclone with restic for this.
