### ISSUE TITLE
rclone config file changing file permission

### ISSUE THREAD

**Issue by ColeMundus** [rclone/rclone#1742]
I have observed this issues in rclone version `v1.37`

So I'm having issues with rclone randomly changing file permissions. Every few minutes, the file permissions change to `0600/-rw-------`. I have been experiencing this for several weeks. I have checked all my crontabs and don't use rclone with any scripts. I tried moving my config file from `~/.rclone.conf` to `~/.config/rclone/rclone.conf` and it is still doing it. I have experienced this on other machines also.

**Comment by ncw** [comment]
rclone sets the permissions to 0600 when it saves things in the config file (which it will do when tokens are refreshed).

The config file contains confidential stuff like access tokens so should be user readable only.

**Comment by ColeMundus** [comment]
Is there any way to disable this behavior?

**Comment by ncw** [comment]
> Is there any way to disable this behavior?

Not currently - why do you want to?

**Comment by snickers2k** [comment]
Same problem here.. Why we do want to?! Because we want to control our files? :D Its not about the config itself. Its about the permissions of our (in my case gdrive) files.
with transmit and other ftp apps, I have only write permission for folders, not for files. 
cli works .. really strange

**Comment by ncw** [comment]
Perhaps the best thing would be if rclone only set the permissions on the config file when writing it for the first time.

**Comment by Corxo** [comment]
Hello,
I know this is an old thread but I just found out the same problem, every day I found the rclone config file owned by the root user and I can't access it by with other users. I run a daily scheduled backup using rclone as sudo in crontab (I edit crontab as root, I don't run `sudo rclone ...`) could this be the problem?

**Comment by ncw** [comment]
> Hello,
> I know this is an old thread but I just found out the same problem, every day I found the rclone config file owned by the root user and I can't access it by with other users. I run a daily scheduled backup using rclone as sudo in crontab (I edit crontab as root, I don't run `sudo rclone ...`) could this be the problem?

Yes using rclone with sudo will leave the config file root owned.  You could use a seperate config with the sudo use with `--config`?

**Comment by marco-m** [comment]
In my opinion the current rclone behavior is correct, for the security reasons explained by @ncw, I don't see the reason to change, even as an option.
@ncw: what would you expect as implementation to satisfy this issue?
@ColeMundus: what is the rationale behind this request?

**Comment by SuperSandro2000** [comment]
@marco-m It not only changes the permission but also the owner to the current user. Annoying when you share one rclone config with a system backup script.

**Comment by ncw** [comment]
When rclone re-writes the config file it writes the new config as a new file then renames the old one out of the way and renames the new one in to place.

Rclone could copy the permissions from the old config file when writing the new one.

Copying the ownership is possible to but that isn't easy to do in a cross platform way.

**Comment by SuperSandro2000** [comment]
Maybe it would keep the permission if you rename the old file and copy it in place.

**Comment by ncw** [comment]
Rclone uses the procedure it does so that if the disk gets full while writing the config file it doesn't corrupt it (which is a real problem reported by users!).

**Comment by SuperSandro2000** [comment]
I mean if it copies the old file instead of creating a new one it should keep the permissions.

**Comment by userwiths** [comment]
Hey, just a quick heads-up.
I was looking into picking this issue up and found out that it should already be resolved thanks to [those changes](https://github.com/rclone/rclone/blame/137f7f62fbc4161b67360a45cb761a3bf255aa2c/fs/config/configfile/configfile.go#L163) from 2021.
Proceeded to pull the repo and test it locally (Linux Arch 6.7.2) and yes, now the file is saved with its previous/unchanged permissions after doing edits with the `rclone config` command.

**Comment by ncw** [comment]
@userwiths thanks for testing that and writing it up. I'll close this issue :-)
