### ISSUE TITLE
FTP: NewFs: ftpConnection Login: Invalid argument

### ISSUE THREAD

**Issue by guillaumesoucy** [rclone/rclone#1747]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`) rclone v1.38

> Which OS you are using and how many bits (eg Windows 7, 64 bit) Ubuntu Server 16.04 LTS x64

> Which cloud storage system are you using? (eg Google Drive) FTP

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`) rclone copy /home/guillaumesoucy/Downloads/microcrosse/ sf:

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Hi, 

When I try to copy data to an remote FTP server I got this:

rclone copy /home/guillaumesoucy/Downloads/microcrosse/ sf:
2017/10/16 18:25:33 ERROR : ftp://server.zsites.ca:21: Error while Logging in into server.zsites.ca:21: Invalid argument.
2017/10/16 18:25:33 Failed to create file system for "sf:": NewFs: ftpConnection Login: Invalid argument

What I need to do to get this working? There is a bug in rclone?

Thanks, 

Guillaume

**Comment by ncw** [comment]
What does your config look like?

**Comment by zawack** [comment]
Sorry for the delay.

This is the config by doing `rclone config show`

> root@server:/home# rclone config show
> [sf]
> type = ftp
> host = 209.43.40.67
> user = ponceleplatre
> port = 
> pass = dNB2pviOhkCKhX5ICKyZybOfqRIi6my7Pw


Thanks!

Guillaume

**Comment by guillaumesoucy** [comment]
Hello, 

I still have the issue. Please note when connecting using FileZilla there was no issues.

**Comment by ncw** [comment]
Sorry for the delay in responding!

I did this

```
$ ftp server.zsites.ca
Connected to server.zsites.ca.
220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
220-You are user number 1 of 50 allowed.
220-Local time is now 10:13. Server port: 21.
220-This is a private system - No anonymous login
220-IPv6 connections are also welcome on this server.
220 You will be disconnected after 15 minutes of inactivity.
```

to see what the server was.

I run the integration tests against pure-ftpd so I'm surprised it doesn't work.

What does your config look like?  It should look something like this

```
[TestFTP]
type = ftp
host = localhost
user = sftptest
pass = ENCRYPTED-PASSWORD
```

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.

The FTP backend has had lots of work since this report so if it still fails, please make another issue.

**Comment by dimejo** [comment]
FYI: I've seen the same error when connecting to Pure-FTPd with rclone v1.47.0, but no error with rclone v1.53.1.
