### ISSUE TITLE
Issue downloading large files from ftp

### ISSUE THREAD

**Issue by JavaJunkie09** [rclone/rclone#1751]
When downloading a large file from ftp to local source, rclone gets stuck at 100% when the file gets to the end of transferring. All it shows is this: 
![dxnoyqo](https://user-images.githubusercontent.com/32905506/31725975-315b6bdc-b415-11e7-87ca-7bb08ee35ede.png)

The only thing that changes is the download speed. I've let it sit for hours and it never completes the transfer. The files I have been using are 30GB-40GB.  I transferred the same file from Google Drive to local source and it worked fine, just not ftp.

Any idea what it could be or anything I can add to temporarily fix it? I also tried the beta and still nothing.
Thank you.

**Comment by ncw** [comment]
So problems when transferring FTP -> local...

Which FTP server are you transferring from?

Can you paste a log with `-vv` please?

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
