### ISSUE TITLE
Feature Request: ListR for Google Drive and Dropbox

### ISSUE THREAD

**Issue by Neurrone** [rclone/rclone#1753]
Hi,

Noticed that mounting an encrypted remote on Dropbox in Windows is really slow when listing directories. The documentation states that ListR isn't being used for Dropbox.

[Dropbox's v2 API](https://www.dropbox.com/developers/documentation/http/documentation) has a list_folder method. Similarly, [Google Drive also supports listing folder contents](https://developers.google.com/drive/v2/reference/children/list).

Can support for these be added?

**Comment by ncw** [comment]
ListR is all about listing the directory recursively, so you get the whole file system listing back at once.  `rclone mount` doesn't use the ListR interface - it lists each directory at a time.

**Comment by animosity22** [comment]
This question seems to be answered. If you have anything else, please feel free to ask on the forums.
