### ISSUE TITLE
Sync with pre-determined list of hash values on destination

### ISSUE THREAD

**Issue by Exocomp** [rclone/rclone#1761]
I would like to see an option where I can supply rclone to sync with a pre-determined list of hash values for files sitting on the destination.  That way rclone doesn't have to create the hash values on the destination on the fly everytime and it will speed up the overall process.

I see the process as follows:

1. Supply rclone sync a destination_pre_hash option & the destination hash file path & whether to create a hash file if the hash file is missing on the destination (for example on the first run)
2. If you specified to create the hash file on the destination and it is missing then do the sync as normal and then create the hash file on the destination otherwise error out gracefully
3. If rclone finds and existing hash file on the destination then it reads it and gets the file path and hash of the files
4. rclone syncs based on the source hash and the destination hash from the destination hash file

**Comment by ncw** [comment]
Are you mostly worried about the time spent hashing local files?

If so there are plans to fix this with a caching layer.

There are other tickets about storing hashes on disk for the local filesystem also.

**Comment by Exocomp** [comment]
> Are you mostly worried about the time spent hashing local files?

Yes that's right, so to avoid wasting time hashing again if it is already done on the first attempt.  Subsequent attempts would be much faster.

**Comment by ncw** [comment]
> Hi there, I was just wondering if this feature or the caching layer mentioned was every completed.

Yes it did - check the [cache backend](https://rclone.org/cache/).

**Comment by Exocomp** [comment]
Looks like it a bit much than my needs, the cache backend is holding copies of files right?

**Comment by ncw** [comment]
> Looks like it a bit much than my needs, the cache backend is holding copies of files right?

It can be setup to only cache metadata

You can set this to 0

      --cache-chunk-total-size SizeSuffix     The total size that the chunks can take up on the local disk. (default 10G)

**Comment by ncw** [comment]
I think this is a good idea but rclone will fix this by caching local metadata which there are other issues for.
