### ISSUE TITLE
Add support for S3 versions

### ISSUE THREAD

**Issue by weetmuts** [rclone/rclone#1776]
Support [S3 versions of files](http://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html) stored in a bucket.

It looks like this is much the same as b2 versions, so could be supported the same way.

**Comment by val-kulkov** [comment]
There is a very handy tool, written in Python and licensed under the MIT license, that restores point-in-time versions of a file or a prefix from a versioned bucket: https://github.com/madisoft/s3-pit-restore

I am posting this link here in case someone wants to borrow code from that tool and incorporate similar functionality in rclone. I can't do it myself, unfortunately.

**Comment by lxleguen** [comment]
Hello all.

Looking at this issue, i assume the support of S3 versioning is still missing.
Can anyone confirm?

Has rclone been validated against a S3 versioned bucket?
Does it work as with a non versioned bucket?

**Comment by ncw** [comment]
> Looking at this issue, i assume the support of S3 versioning is still missing.

It is, yes



> Has rclone been validated against a S3 versioned bucket?

It should work fine with a versioned bucket - the versioning is invisible unless you ask for it.

**Comment by lxleguen** [comment]
Thanks. Indeed it works fine (at least on a limited sample of data).

**Comment by darthShadow** [comment]
Related to https://github.com/rclone/rclone/issues/1532

**Comment by yarikoptic** [comment]
I have posted my "vision" for versioning support, in particular for rclone mount, in #5064 (sorry - failed to find this issue when I searched fire version of ;-)).

**Comment by disconnect5852** [comment]
still no support? As i see, no

**Comment by darthShadow** [comment]
This is supported as you can see from the state of the issue i.e. closed: https://rclone.org/s3/#s3-versions

Please open a new thread in the forums if you are facing any problems using the feature rather than bumping closed issues.
