### ISSUE TITLE
Add MFA one time authenication to S3 deletes

### ISSUE THREAD

**Issue by weetmuts** [rclone/rclone#1781]
s3 MFA delete is unfortunately not particularly useful. However sessions with mfa could perhaps be useful to prevent accidental deletes.

This issue can be a placeholder for when we have found a way to protect a versioned bucket from deletes using sessions and MFA.

http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_configure-api-require.html

See also [the discussion on the forum](https://forum.rclone.org/t/s3-versions-mfa-delete-to-protect-from-accidental-destruction-of-remote-backup/4106)

**Comment by ncw** [comment]
@sweharris  has made some command line tools showing the operations needed which need a bit of porting to go

https://github.com/sweharris/aws-cli-mfa

**Comment by ivandeex** [comment]
Closing after 3 years of inactivity.
