### ISSUE TITLE
Transfer rates seem to be caped at 4MBytes/s

### ISSUE THREAD

**Issue by rrbailey89** [rclone/rclone#1782]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> rclone v1.38-049-gd0b9baab)

> Ubuntu 16.04

> Google Drive

> rclone move

> 2017/10/29 16:15:37 INFO  : Google drive root 'Plex/TV Shows/How to Get Away with Murder': Modify window is 1ms
2017/10/29 16:15:38 INFO  : Google drive root 'Plex/TV Shows/How to Get Away with Murder': Waiting for checks to finish
2017/10/29 16:15:38 INFO  : Google drive root 'Plex/TV Shows/How to Get Away with Murder': Waiting for transfers to finish
2017/10/29 16:15:38 INFO  :
Transferred:   1020 kBytes (560.362 kBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        1.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  0% done, 0 Bytes/s, ETA: -

2017/10/29 16:15:39 INFO  :
Transferred:   5.996 MBytes (2.126 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        2.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  0% done, 2.996 MBytes/s, ETA: 15m3s

2017/10/29 16:15:40 INFO  :
Transferred:     8 MBytes (2.094 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        3.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  0% done, 3.061 MBytes/s, ETA: 14m43s

2017/10/29 16:15:41 INFO  :
Transferred:   9.996 MBytes (2.074 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        4.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  0% done, 2.992 MBytes/s, ETA: 15m3s

2017/10/29 16:15:42 INFO  :
Transferred:   13.996 MBytes (2.405 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        5.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  0% done, 2.928 MBytes/s, ETA: 15m21s

2017/10/29 16:15:43 INFO  :
Transferred:   21.996 MBytes (3.225 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        6.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  0% done, 3.062 MBytes/s, ETA: 14m38s

2017/10/29 16:15:44 INFO  :
Transferred:   24.996 MBytes (3.196 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        7.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  0% done, 3.316 MBytes/s, ETA: 13m30s

2017/10/29 16:15:45 INFO  :
Transferred:   27.996 MBytes (3.174 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        8.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  1% done, 3.360 MBytes/s, ETA: 13m18s

2017/10/29 16:15:46 INFO  :
Transferred:   31.996 MBytes (3.258 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        9.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  1% done, 3.337 MBytes/s, ETA: 13m23s

2017/10/29 16:15:47 INFO  :
Transferred:   35.996 MBytes (3.327 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       10.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  1% done, 3.251 MBytes/s, ETA: 13m43s

2017/10/29 16:15:48 INFO  :
Transferred:   37.996 MBytes (3.214 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       11.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  1% done, 3.299 MBytes/s, ETA: 13m30s

2017/10/29 16:15:49 INFO  :
Transferred:   39.996 MBytes (3.120 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       12.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  1% done, 3.280 MBytes/s, ETA: 13m34s

2017/10/29 16:15:50 INFO  :
Transferred:   47.996 MBytes (3.473 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       13.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  1% done, 3.133 MBytes/s, ETA: 14m10s

2017/10/29 16:15:51 INFO  :
Transferred:   51.996 MBytes (3.508 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       14.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  1% done, 3.576 MBytes/s, ETA: 12m24s

2017/10/29 16:15:52 INFO  :
Transferred:   54.996 MBytes (3.476 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       15.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  2% done, 3.474 MBytes/s, ETA: 12m44s

2017/10/29 16:15:53 INFO  :
Transferred:   61.996 MBytes (3.686 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       16.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  2% done, 3.508 MBytes/s, ETA: 12m35s

2017/10/29 16:15:54 INFO  :
Transferred:   63.996 MBytes (3.591 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       17.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  2% done, 3.669 MBytes/s, ETA: 12m1s

2017/10/29 16:15:55 INFO  :
Transferred:   68.996 MBytes (3.666 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       18.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  2% done, 3.561 MBytes/s, ETA: 12m22s

2017/10/29 16:15:56 INFO  :
Transferred:   74.996 MBytes (3.784 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       19.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  2% done, 3.718 MBytes/s, ETA: 11m49s

2017/10/29 16:15:57 INFO  :
Transferred:   79.996 MBytes (3.842 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       20.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  2% done, 3.866 MBytes/s, ETA: 11m21s

2017/10/29 16:15:58 INFO  :
Transferred:   84.996 MBytes (3.895 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       21.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  3% done, 3.874 MBytes/s, ETA: 11m18s

2017/10/29 16:15:59 INFO  :
Transferred:   91.996 MBytes (4.031 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       22.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  3% done, 4.076 MBytes/s, ETA: 10m42s

2017/10/29 16:16:00 INFO  :
Transferred:   93.996 MBytes (3.946 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       23.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  3% done, 4.200 MBytes/s, ETA: 10m23s

2017/10/29 16:16:01 INFO  :
Transferred:   98.996 MBytes (3.989 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       24.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  3% done, 4.058 MBytes/s, ETA: 10m44s

2017/10/29 16:16:02 INFO  :
Transferred:   103.996 MBytes (4.028 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       25.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  3% done, 4.119 MBytes/s, ETA: 10m33s

2017/10/29 16:16:03 INFO  :
Transferred:   108.382 MBytes (4.041 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       26.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  3% done, 4.240 MBytes/s, ETA: 10m14s

2017/10/29 16:16:04 INFO  :
Transferred:   111.996 MBytes (4.026 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       27.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  4% done, 4.225 MBytes/s, ETA: 10m15s

2017/10/29 16:16:05 INFO  :
Transferred:   117.996 MBytes (4.094 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       28.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  4% done, 4.275 MBytes/s, ETA: 10m6s

2017/10/29 16:16:06 INFO  :
Transferred:   123.996 MBytes (4.158 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       29.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  4% done, 4.192 MBytes/s, ETA: 10m17s

2017/10/29 16:16:07 INFO  :
Transferred:   127.996 MBytes (4.153 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       30.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  4% done, 4.309 MBytes/s, ETA: 9m59s

2017/10/29 16:16:08 INFO  :
Transferred:   135.996 MBytes (4.274 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       31.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  5% done, 4.418 MBytes/s, ETA: 9m43s

2017/10/29 16:16:09 INFO  :
Transferred:   140.996 MBytes (4.296 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       32.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  5% done, 4.585 MBytes/s, ETA: 9m20s

2017/10/29 16:16:10 INFO  :
Transferred:   144.996 MBytes (4.287 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       33.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  5% done, 4.612 MBytes/s, ETA: 9m16s

2017/10/29 16:16:11 INFO  :
Transferred:   149.996 MBytes (4.308 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       34.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  5% done, 4.572 MBytes/s, ETA: 9m20s

2017/10/29 16:16:12 INFO  :
Transferred:   152.996 MBytes (4.271 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       35.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  5% done, 4.600 MBytes/s, ETA: 9m16s

2017/10/29 16:16:13 INFO  :
Transferred:   155.996 MBytes (4.237 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       36.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  5% done, 4.497 MBytes/s, ETA: 9m28s

2017/10/29 16:16:14 INFO  :
Transferred:   158.996 MBytes (4.204 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       37.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  5% done, 4.400 MBytes/s, ETA: 9m40s

2017/10/29 16:16:15 INFO  :
Transferred:   162.996 MBytes (4.199 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       38.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  6% done, 4.245 MBytes/s, ETA: 10m0s

2017/10/29 16:16:16 INFO  :
Transferred:   166.996 MBytes (4.194 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       39.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  6% done, 4.294 MBytes/s, ETA: 9m52s

2017/10/29 16:16:17 INFO  :
Transferred:   172.996 MBytes (4.238 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       40.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  6% done, 4.404 MBytes/s, ETA: 9m36s

2017/10/29 16:16:18 INFO  :
Transferred:   179.996 MBytes (4.304 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       41.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  6% done, 4.378 MBytes/s, ETA: 9m38s

2017/10/29 16:16:19 INFO  :
Transferred:   181.996 MBytes (4.250 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       42.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  6% done, 4.547 MBytes/s, ETA: 9m16s

2017/10/29 16:16:20 INFO  :
Transferred:   187.996 MBytes (4.290 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       43.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  6% done, 4.383 MBytes/s, ETA: 9m36s

2017/10/29 16:16:21 INFO  :
Transferred:   190.996 MBytes (4.261 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       44.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  7% done, 4.487 MBytes/s, ETA: 9m21s

2017/10/29 16:16:22 INFO  :
Transferred:   191.996 MBytes (4.190 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       45.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  7% done, 4.391 MBytes/s, ETA: 9m33s

2017/10/29 16:16:23 INFO  :
Transferred:   193.996 MBytes (4.143 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       46.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  7% done, 4.172 MBytes/s, ETA: 10m3s

2017/10/29 16:16:24 INFO  :
Transferred:   195.996 MBytes (4.099 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       47.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  7% done, 4.032 MBytes/s, ETA: 10m24s

2017/10/29 16:16:25 INFO  :
Transferred:   198.996 MBytes (4.076 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       48.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  7% done, 3.901 MBytes/s, ETA: 10m44s

2017/10/29 16:16:26 INFO  :
Transferred:   200.996 MBytes (4.034 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       49.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  7% done, 3.843 MBytes/s, ETA: 10m53s

2017/10/29 16:16:27 INFO  :
Transferred:   207.996 MBytes (4.093 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       50.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  7% done, 3.724 MBytes/s, ETA: 11m12s

2017/10/29 16:16:28 INFO  :
Transferred:   210.996 MBytes (4.072 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       51.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  7% done, 3.935 MBytes/s, ETA: 10m35s

2017/10/29 16:16:29 INFO  :
Transferred:   211.996 MBytes (4.014 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       52.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  7% done, 3.811 MBytes/s, ETA: 10m56s

2017/10/29 16:16:30 INFO  :
Transferred:   213.996 MBytes (3.976 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       53.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  7% done, 3.629 MBytes/s, ETA: 11m28s

2017/10/29 16:16:31 INFO  :
Transferred:   215.996 MBytes (3.940 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       54.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  7% done, 3.524 MBytes/s, ETA: 11m48s

2017/10/29 16:16:32 INFO  :
Transferred:   217.996 MBytes (3.905 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       55.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  8% done, 3.490 MBytes/s, ETA: 11m54s

2017/10/29 16:16:33 INFO  :
Transferred:   221.996 MBytes (3.907 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       56.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  8% done, 3.330 MBytes/s, ETA: 12m27s

2017/10/29 16:16:34 INFO  :
Transferred:   226.996 MBytes (3.926 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       57.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  8% done, 3.502 MBytes/s, ETA: 11m49s

2017/10/29 16:16:35 INFO  :
Transferred:   230.996 MBytes (3.927 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       58.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  8% done, 3.534 MBytes/s, ETA: 11m42s

2017/10/29 16:16:36 INFO  :
Transferred:   236.996 MBytes (3.962 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:       59.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  8% done, 3.564 MBytes/s, ETA: 11m34s

2017/10/29 16:16:37 INFO  :
Transferred:   238.996 MBytes (3.930 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m0.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  8% done, 3.721 MBytes/s, ETA: 11m4s

2017/10/29 16:16:38 INFO  :
Transferred:   246.996 MBytes (3.995 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m1.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  9% done, 3.745 MBytes/s, ETA: 10m58s

2017/10/29 16:16:39 INFO  :
Transferred:   249.996 MBytes (3.980 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m2.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  9% done, 3.885 MBytes/s, ETA: 10m33s

2017/10/29 16:16:40 INFO  :
Transferred:   250.996 MBytes (3.933 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m3.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  9% done, 3.763 MBytes/s, ETA: 10m54s

2017/10/29 16:16:41 INFO  :
Transferred:   252.996 MBytes (3.903 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m4.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  9% done, 3.649 MBytes/s, ETA: 11m13s

2017/10/29 16:16:42 INFO  :
Transferred:   254.996 MBytes (3.874 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m5.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  9% done, 3.478 MBytes/s, ETA: 11m46s

2017/10/29 16:16:43 INFO  :
Transferred:   260.996 MBytes (3.906 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m6.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  9% done, 3.448 MBytes/s, ETA: 11m51s

2017/10/29 16:16:44 INFO  :
Transferred:   262.996 MBytes (3.878 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m7.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  9% done, 3.612 MBytes/s, ETA: 11m18s

2017/10/29 16:16:45 INFO  :
Transferred:   263.996 MBytes (3.836 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m8.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  9% done, 3.444 MBytes/s, ETA: 11m51s

2017/10/29 16:16:46 INFO  :
Transferred:   268.996 MBytes (3.853 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      1m9.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv:  9% done, 3.415 MBytes/s, ETA: 11m55s

2017/10/29 16:16:47 INFO  :
Transferred:   272.996 MBytes (3.855 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     1m10.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv: 10% done, 3.453 MBytes/s, ETA: 11m46s

2017/10/29 16:16:48 INFO  :
Transferred:   280 MBytes (3.899 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     1m11.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv: 10% done, 3.553 MBytes/s, ETA: 11m24s

2017/10/29 16:16:49 INFO  :
Transferred:   293.996 MBytes (4.037 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     1m12.8s
Transferring:
* ...Away with Murder - S04E05 - I Love Her.mkv: 10% done, 4.094 MBytes/s, ETA: 9m50s

A few weeks ago I was able to transfer very quickly around 50 to 100MBytes/s now every file seems to be capped at a transfer rate of 4.

**Comment by ncw** [comment]
> A few weeks ago I was able to transfer very quickly around 50 to 100MBytes/s now every file seems to be capped at a transfer rate of 4.

How fast is your Internet connection?

It could be your ISP limiting your uploads - I've heard of that.

I don't think anything significant has changed in rclone to cause that.

**Comment by ajkis** [comment]
Works  ok for me, my latest upload. 
( in case of uploading more files the speed goes to 80-100MB )

> 2017/11/10 07:37:05 INFO  : Encrypted drive 'gdrivecrypt:': Modify window is 1ms
> 2017/11/10 07:37:27 INFO  : Encrypted drive 'gdrivecrypt:': Waiting for checks to finish
> 2017/11/10 07:37:27 INFO  : Encrypted drive 'gdrivecrypt:': Waiting for transfers to finish
> 2017/11/10 07:37:46 INFO  : series/Life in Pieces/Season 03/Life in Pieces - S03E02 - WEBDL-1080p.mkv: Copied (new)
> 2017/11/10 07:37:46 INFO  : series/Life in Pieces/Season 03/Life in Pieces - S03E02 - WEBDL-1080p.mkv: Deleted
> 2017/11/10 07:37:46 INFO  : 
> Transferred:   1.660 GBytes (40.484 MBytes/s)
> Errors:                 0
> Checks:                 1
> Transferred:            1
> Elapsed time:       41.9s

**Comment by bootldrDNB** [comment]
I'm having the same issue with a VM in Azure, my downloads seem to be capped to 200Mbps _per instance_. Running multiple instances helps with the speed, but I only get 200Mbps per download. The upload is sorta slow too, no idea why as it used to be fast just a few days ago. :/

**Comment by bootldrDNB** [comment]
@ncw Hey, looks like you have a bug with --bwlimit here, if I change bwlimit to something above 200Mbps, I'm not capped anymore.

**Comment by ncw** [comment]
@bootldrDNB Do you mean that the transfer speeds go up if you add `--bwlimit`? What command line are you using and what result are you expecting? If you think you've found a bug please make a [new issue on github](https://github.com/ncw/rclone/issues/new).

**Comment by animosity22** [comment]
This looks to be a stale item. If you are still have a question, please feel free to ask on the forums and we can help out.
