### ISSUE TITLE
rclone Feature Request: Advanced "Try and Error"

### ISSUE THREAD

**Issue by RaymondSchnyder** [rclone/rclone#1795]
Hello,

So my idea is:

I found out that google drive limits the API Limit per user on speed too, for example, when i upload with 40MB/s, i get  a ban in the next 2 hours. 
But when i upload with max 25MB/s, i can upload for days, without a ban with the correct settings.

Now with 25MB/s, this is off course, slow.

My idea is now, that rclone, when it starts uploading, tries to start with the max bandwidth, if that wont work, it should automatically reduce the bandwidth till it works without an api ban.
As if you have an API Ban, you could still upload with less speed.

Is that an idea or even possible?

greetings

**Comment by ajkis** [comment]
I dont get it are you saying once you got banned you can still upload with slower speed ?

**Comment by RaymondSchnyder** [comment]
@ajkis Yes i can :D It sounds a bit stupid but, if you lower the BWlimit and the tpslimit, you can still upload if even if you are rate limited.

**Comment by animosity22** [comment]
This looks to be a stale item. if you have a question, please feel free to ask in the forums as it looks like majority of this is already covered.
