### ISSUE TITLE
rclone on dropbox not slowing down on API failure (too many requests)

### ISSUE THREAD

**Issue by zenjabba** [rclone/rclone#1807]
2017/11/08 03:10:22 DEBUG : pacer: low level retry 3/10 (error too_many_requests/.)
2017/11/08 03:10:24 DEBUG : pacer: low level retry 4/10 (error too_many_requests/..)
2017/11/08 03:10:26 DEBUG : pacer: low level retry 5/10 (error too_many_requests/.)
2017/11/08 03:10:30 DEBUG : pacer: low level retry 6/10 (error too_many_requests/...)

**Comment by ncw** [comment]
This has come up several times before, eg #1539

Also the dropbox sdk isn't returning the `Retry-After` header to rclone - see #1788

**Comment by ncw** [comment]
I'm pretty sure this is fixed now (both the issues above are fixed).
