### ISSUE TITLE
Pacer applies exponential backoff to all Google Drive error types

### ISSUE THREAD

**Issue by bobobo1618** [rclone/rclone#181]
Google Drive has a number of errors that are retryable but unrelated to rate limiting. Currently, Pacer treats any call that indicates a retry is needed as a failure that needs to be rate limiting. This slows down rclone considerably when Drive is misbehaving.

**Comment by ncw** [comment]
I see what you mean... Did you have any specific examples that you think should just be retried without increasing the delay?

**Comment by bobobo1618** [comment]
50x are the main ones.

**Comment by animosity22** [comment]
Pretty sure this is done as well. If not, please let me know.
