### ISSUE TITLE
Move folder from Google drive to another, but keep activity log of the folder. 

### ISSUE THREAD

**Issue by isaacTey** [rclone/rclone#1828]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
-rclone v1.38

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
- os/arch: darwin/amd64
> Which cloud storage system are you using? (eg Google Drive)
-googleDrive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
-rclone move or rclone move
> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Isaacs-MacBook-Pro:~ isaactey$ rclone moveto myGoogleDrive:/tst elzieGoolgleDrive:/ -vv
2017/11/16 13:00:35 DEBUG : Using config file from "/Users/isaactey/.config/rclone/rclone.conf"
2017/11/16 13:00:35 DEBUG : rclone: Version "v1.38" starting with parameters ["rclone" "moveto" "myGoogleDrive:/tst" "elzieGoolgleDrive:/" "-vv"]
2017/11/16 13:00:36 DEBUG : myGoogleDrive: Saved new token in config file
2017/11/16 13:00:37 DEBUG : elzieGoolgleDrive: Saved new token in config file
2017/11/16 13:00:38 INFO  : Google drive root '': Modify window is 1ms
2017/11/16 13:00:41 DEBUG : formMule SCRIPT.xlsx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/11/16 13:00:41 DEBUG : formMule SCRIPT.xlsx: Unchanged skipping
2017/11/16 13:00:41 ERROR : formMule SCRIPT.xlsx: Couldn't delete: can't delete a google document
2017/11/16 13:00:46 INFO  : Google drive root '': Waiting for checks to finish
2017/11/16 13:00:46 INFO  : Google drive root '': Waiting for transfers to finish
2017/11/16 13:00:47 INFO  : ownership/Everything.docx: Copied (new)
2017/11/16 13:00:47 ERROR : ownership/Everything.docx: Couldn't delete: can't delete a google document
2017/11/16 13:00:48 INFO  : ownership/tkhow9091/Untitled document.docx: Copied (new)
2017/11/16 13:00:48 ERROR : ownership/tkhow9091/Untitled document.docx: Couldn't delete: can't delete a google document
2017/11/16 13:00:50 INFO  : ownership/tkhow9091/nur/nur.docx: Copied (new)
2017/11/16 13:00:50 ERROR : ownership/tkhow9091/nur/nur.docx: Couldn't delete: can't delete a google document
2017/11/16 13:00:50 ERROR : Attempt 1/3 failed with 4 errors and: can't delete a google document
2017/11/16 13:00:52 DEBUG : formMule SCRIPT.xlsx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/11/16 13:00:52 DEBUG : formMule SCRIPT.xlsx: Unchanged skipping
2017/11/16 13:00:52 ERROR : formMule SCRIPT.xlsx: Couldn't delete: can't delete a google document
2017/11/16 13:00:52 DEBUG : pacer: Rate limited, sleeping for 1.477012186s (1 consecutive low level retries)
2017/11/16 13:00:52 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2017/11/16 13:00:52 DEBUG : pacer: Rate limited, sleeping for 1.986107694s (1 consecutive low level retries)
2017/11/16 13:00:52 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2017/11/16 13:00:53 DEBUG : pacer: Rate limited, sleeping for 2.423983972s (2 consecutive low level retries)
2017/11/16 13:00:53 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2017/11/16 13:00:53 DEBUG : pacer: Rate limited, sleeping for 2.690070883s (2 consecutive low level retries)
2017/11/16 13:00:53 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2017/11/16 13:00:54 DEBUG : pacer: Rate limited, sleeping for 4.298316075s (3 consecutive low level retries)
2017/11/16 13:00:54 DEBUG : pacer: low level retry 3/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2017/11/16 13:00:55 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2017/11/16 13:00:57 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2017/11/16 13:00:58 DEBUG : ownership/Everything.docx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/11/16 13:00:58 DEBUG : ownership/Everything.docx: Unchanged skipping
2017/11/16 13:00:58 ERROR : ownership/Everything.docx: Couldn't delete: can't delete a google document
2017/11/16 13:01:01 DEBUG : ownership/tkhow9091/Untitled document.docx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/11/16 13:01:01 DEBUG : ownership/tkhow9091/Untitled document.docx: Unchanged skipping
2017/11/16 13:01:01 ERROR : ownership/tkhow9091/Untitled document.docx: Couldn't delete: can't delete a google document
2017/11/16 13:01:02 DEBUG : ownership/tkhow9091/nur/nur.docx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/11/16 13:01:02 DEBUG : ownership/tkhow9091/nur/nur.docx: Unchanged skipping
2017/11/16 13:01:02 INFO  : Google drive root '': Waiting for checks to finish
2017/11/16 13:01:02 ERROR : ownership/tkhow9091/nur/nur.docx: Couldn't delete: can't delete a google document
2017/11/16 13:01:02 INFO  : Google drive root '': Waiting for transfers to finish
2017/11/16 13:01:02 ERROR : Attempt 2/3 failed with 4 errors and: can't delete a google document
2017/11/16 13:01:04 DEBUG : formMule SCRIPT.xlsx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/11/16 13:01:04 DEBUG : formMule SCRIPT.xlsx: Unchanged skipping
2017/11/16 13:01:04 ERROR : formMule SCRIPT.xlsx: Couldn't delete: can't delete a google document
2017/11/16 13:01:05 DEBUG : ownership/Everything.docx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/11/16 13:01:05 DEBUG : ownership/Everything.docx: Unchanged skipping
2017/11/16 13:01:05 ERROR : ownership/Everything.docx: Couldn't delete: can't delete a google document
2017/11/16 13:01:06 DEBUG : ownership/tkhow9091/Untitled document.docx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/11/16 13:01:06 DEBUG : ownership/tkhow9091/Untitled document.docx: Unchanged skipping
2017/11/16 13:01:06 ERROR : ownership/tkhow9091/Untitled document.docx: Couldn't delete: can't delete a google document
2017/11/16 13:01:07 DEBUG : ownership/tkhow9091/nur/nur.docx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2017/11/16 13:01:07 DEBUG : ownership/tkhow9091/nur/nur.docx: Unchanged skipping
2017/11/16 13:01:07 INFO  : Google drive root '': Waiting for checks to finish
2017/11/16 13:01:07 ERROR : ownership/tkhow9091/nur/nur.docx: Couldn't delete: can't delete a google document
2017/11/16 13:01:07 INFO  : Google drive root '': Waiting for transfers to finish
2017/11/16 13:01:07 ERROR : Attempt 3/3 failed with 4 errors and: can't delete a google document
2017/11/16 13:01:07 Failed to moveto: can't delete a google document

- Hi all, some question with the move/ move to. I have two google drive, and I want to move a folder from g-drive A to g-drive B. But at the same time I would like to keep the folder past activity log. Is there any way to keep the folder past activity log? 

This is what I do after rclone move, 
<img width="299" alt="screen shot 2017-11-16 at 1 04 26 pm" src="https://user-images.githubusercontent.com/33710365/32874772-3d22c994-cacf-11e7-96b4-c208eace7433.png">

I would like to keep those past activity history, is there anyway to resolve this? Thank you guys.

**Comment by ncw** [comment]
I'm not sure... Can you look in the [drive API docs](https://developers.google.com/drive/v2/reference/) and see if there is something there that would help?

**Comment by animosity22** [comment]
This looks to be a stale request. If you have a new item or question, please feel free to ask in the forums.
