### ISSUE TITLE
[feature request] please add support for socks proxies

### ISSUE THREAD

**Issue by xchern** [rclone/rclone#1861]
socks proxies are not yet supported by rclone. And proxywrappers like "proxychains" and "tsocks" do not work with golang based applications, for golang's own network libraries are usually statically linked and cannot be hooked. (https://github.com/rofl0r/proxychains-ng/issues/199)
It would be better to get socks proxies work with rclone.

**Comment by ncw** [comment]
There is a [proxy](https://godoc.org/golang.org/x/net/proxy) library supported by the go team which looks useful for this.

It supports the [configuration from the ALL_PROXY environment varialble](https://godoc.org/golang.org/x/net/proxy#FromEnvironment).

The would have to be integrated into rclone's Client or Transport which would cover all the http based remotes.  A bit more work would be required to cover the non http based remotes such as FTP/SFTP - not sure if they have replaceable Dial functions.

**Comment by ncw** [comment]
@xiaosong0911 is this something you'd like to work on?

**Comment by xiaosong0911** [comment]
@ncw I'd love to help, but I haven't yet written a line of Go, so I worry that I might be unable to work on it.

**Comment by fffx** [comment]
Check https://github.com/hmgle/graftcp, it's like proxychains and works with go program

**Comment by xiaosong0911** [comment]
@fffx That's very impressive. I will have a try.

**Comment by YLaido** [comment]
I gave graftcp a try, but no luck. I am using v2ray as the local sock5 proxy.  On my synology NAS, graftcp works fine with curl, but not with rclone, as rclone, v2ray and graftcp show no traffic at all (the log level was set to info). Wonder if anyone encounters the same problem :<

**Comment by J0s3f** [comment]
I tried grafttcp but noticed it breaks `rclone mount`.
But then I found out that rclone actually does use a socks proxy, at least for all remotes I tried (all https based like OneDrive and Gdrive) if started with `env http_proxy=socks5://localhost:1080 https_proxy=socks5://localhost:1080 rclone`

What exactly is the proxy support missing?

**Comment by ncw** [comment]
It looks like `http_proxy` support for `socks5` was [added in go 1.9](https://golang.org/doc/go1.9#net/http), so relatively recently https://github.com/golang/go/issues/18508

So maybe all that is missing is documentation? Perhaps at the end of [docs.md](https://github.com/rclone/rclone/blob/master/docs/content/docs.md)?

Anyone want to have a go at writing it?

**Comment by liori** [comment]
> So maybe all that is missing is documentation? Perhaps at the end of docs.md?

That still won't help with non-HTTP targets like SFTP.

**Comment by ncw** [comment]
> That still won't help with non-HTTP targets like SFTP

It will help with nearly all the backends but not SFTP, FTP and Tardigrade which aren't HTTP based.

Is there a Go plugin for SFTP for socks? Or is it easy to add?

**Comment by ivandeex** [comment]
@ncw

As of the time of this writing, SOCKS5 support:
- for HTTP(s) protocols -- fully implemented
- for FTP/SFTP it is requested by #3558

The two tickets are in fact duplucate now, and this one is rather _unfocused_
I propose to close this ticket in favor of #3558
I have assigned #3558 on myself as I need it in my projects and will submit a pull request by this June.

Let's close this one

**Comment by ivandeex** [comment]
If all that is left is description of `http_proxy`,`https_proxy` use in documentation, let's create a new _focused_ request just for that!

**Comment by ivandeex** [comment]
closed in favor of #3558 #5083
