### ISSUE TITLE
Support for Seafile

### ISSUE THREAD

**Issue by RomeSilvanus** [rclone/rclone#1877]
Are there any plans on supporting Seafile? 

It's a open source cloud system similar to Dropbox and they seem to have an API available here: 
https://manual.seafile.com/develop/

I couldn't fine anything about it on here so I'd though to ask.

**Comment by ncw** [comment]
That looks possible.  The API looks sensible too.  It would be straightforward to do with rclone's rest library if anyone wanted to have a go!

**Comment by yatesco** [comment]
I have used seafile for years. I recently dabbled with nextcloud but nothing beats a browsable deduped repository with end-to-end encryption on a per library basis. 

Seafile isn't as "polished" as Nextcloud, and it is much more narrowly focused, but what it does, it does amazingly well.

However, you can't just SSH your files into it, which is a significant downside. rclone support would be _amazing_. 

If ever I experience that mythical beast known as "free time" I will have a crack, but please don't hold your breath!

+1 for seafile, +1 for rclone, +1000 for rclone+seafile :-).

**Comment by LizzAlice** [comment]
Seafile support would be great!

**Comment by eleaner** [comment]
+1 from me

**Comment by ncw** [comment]
I've heard reports (thanks @yatesco ) that Seafile with the [webdav extension](https://manual.seafile.com/extension/webdav.html) works well with rclone.

**Comment by RomeSilvanus** [comment]
@ncw This does not show any encrypted libraries, only the unencrypted ones. So there is no way to access them.

![screenshot 2019-01-28 at 19 37 48](https://user-images.githubusercontent.com/7461492/51858131-3e2e3d00-2334-11e9-9ec4-88145d4b5e1f.png)
![screenshot 2019-01-28 at 19 37 59](https://user-images.githubusercontent.com/7461492/51858135-3f5f6a00-2334-11e9-9d75-9c0fa9b8dacd.png)

**Comment by ncw** [comment]
I found a forum post about [encrypted libraries and WebDAV](https://forum.seafile.com/t/webdav-seafdav-with-encrypted-libraries/2353/4).

It looks like it isn't possible :-(

**Comment by creativeprojects** [comment]
Hi,

I think I can give it a try :)

I have a few questions before going further though:

The idea would be to consider a seafile _library_ like a bucket. A target would be
`Seafile:My Library/some/path/to/file`
It works for all un-encrypted libraries. But for an encrypted library, we need to specify another password (and each encrypted library is likely to use a different password).

- Should we ask for a password when using an encrypted library?
- Should we create a different target for a encrypted library? (containing the login/password, url, library name, and library encryption password) `EncryptedLibrary:some/path/to/file`

The problem with a different target for each encrypted library is that it make things working in a different way between un-encrypted and encrypted libraries.
Now let's say we create a new target for each library to make things similar, we now face the issue that Seafile targets would be different than other bucket type targets.

What do you guys think?

**Comment by ncw** [comment]
A different target (remote) for each encrypted library sounds like there Rclone way.

The parameters can always need overridden with command line flags.

> we now face the issue that Seafile targets would be different than other bucket type targets.

Why is this a problem?

**Comment by creativeprojects** [comment]
> Why is this a problem?

I mean for consistency between all the different providers.

Well I've only used providers where you only need one target and you can access all buckets/containers/folders from the same target. Maybe some other providers work in a different way but I haven't encountered any actually

**Comment by ncw** [comment]
> > Why is this a problem?
> 
> I mean for consistency between all the different providers.
> 
> Well I've only used providers where you only need one target and you can access all buckets/containers/folders from the same target. Maybe some other providers work in a different way but I haven't encountered any actually

Jottacloud for example has different sync targets you have to configure at configure time.  You configure different google shared drives at configure time.  I think there are quite a few examples of backends working like this.

How many targets would a user typically have?  One or two?  Or are they used more like directories?

**Comment by creativeprojects** [comment]
I don't think a typical user would have many libraries. As a quick overview, separating files in libraries helps you decide which ones you want synchronized on each computer (I want my documents at work, my music on my home desktop, etc.) And the cool thing about libraries is that they can be anywhere on your disk. Say you want to synchronize your documents on a windows machine, you don't need two separate documents folder like Onedrive does.

Anyway, I looked it up, and between my shared libraries and my own I have exactly 10.

So in the end, I think it's going to be quite simple:

- You can set a remote with no library, then it will be like a bucket remote (the first _directory_ will be the library) `seafile:library/path/to/file`. You should see all nonencrypted libraries unless you pass a library password on the command line
- You can set a remote with a library name, then you can only access files inside the library `seafile:path/to/file`. For an encrypted library, you can specify the library password either in the configuration or on the command line.

That should cover all options

**Comment by ncw** [comment]
That sounds fine if it is easy to implement that way.

**Comment by creativeprojects** [comment]
Hi,

I'm making good progress on this: all the basic implementation is done.

I've managed to run all the tests in `fs/sync` and `fs/operations` successfully, but for the `backend/seafile` tests I have a last one I'm really struggling with: the `punctuation` test. I can't get my head around it.

Is there anything obvious that is usually happening with this test?

**Comment by ncw** [comment]
There will be some punctuation that seafile doesn't like. You can look in their docs to discover this maybe!

Are you using lib/encoder? Have you seen the writing a new backend docs in the CONTRIBUTING.md doc - that has a section on finding the characters a backend does allow .

See https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#writing-a-new-backend

**Comment by creativeprojects** [comment]
Yes I'm using the lib/encoder.
I've read the contributing documentation, but for some reason I completely overlooked the section about `rclone info`.
I'll have a look at it, thanks

**Comment by creativeprojects** [comment]
That's an awesome little tool indeed!
I found out the characters that were failing: I've fixed all the tests and everything seems to work now.

I'll write up the documentation and send a PR :+1:

**Comment by ncw** [comment]
> I'll write up the documentation and send a PR

Great :-)

**Comment by creativeprojects** [comment]
Hi,

Sorry, it's taking me a while to iron it out.
Recently I ran into a lot of issues with the encrypted libraries. I think I fixed all of them, but I have a question:

Non-encrypted libraries handle the http _Range_ header perfectly fine.
**But the encrypted libraries totally ignore it**.

So I ended up downloading the whole file, and chunk it afterwards.
`ioutil.NopCloser(bytes.NewReader(buffer[start:end]))`

So if there's a path in the code that want to load a big file chunk by chunk, it's going to download the whole file for each chunk. Is this an acceptable behaviour?

**Comment by ncw** [comment]
Not handling the `Range` header is going to cause problems.  It will make `rclone mount` unusable amongst other things...

This definitely should not download the whole file into RAM!

At very least this should skip by streaming rather than downloading everything!

You can use `readers.NewLimitedReadCloser(newObjectReader(in), limit)` to chop off the end of the download.  You'd need to use `io.CopyN(os.Discard, in, limit)` to discard from the start.

It might be better to throw an error than do this, I'm not sure. Or maybe optionally throw an error if a Range request is issued.

Are encrypted libraries an important feature for Seafile?

**Comment by creativeprojects** [comment]
I wasn't thinking about the `mount` feature, and for that matter that's a terrible idea indeed.

To be honest, I can't really tell if encrypted libraries are an important feature. It's handy if you don't trust your VPS provider. If it's really important files you would probably use something more robust on top of seafile anyway.

Alternatively I can use the method your proposed (I didn't know about `io.CopyN` as I'm a beginner in Go) but send a warning to the console (`LOG_WARNING`)?

**Comment by ncw** [comment]
> To be honest, I can't really tell if encrypted libraries are an important feature. It's handy if you don't trust your VPS provider. If it's really important files you would probably use something more robust on top of seafile anyway.

OK

> Alternatively I can use the method your proposed (I didn't know about `io.CopyN` as I'm a beginner in Go) but send a warning to the console (`LOG_WARNING`)?

That sounds like a reasonable compromise.  I'd use `sync.Once` to emit one NOTICE level log probably (`fs.Logf`).

**Comment by seuffert** [comment]
@creativeprojects did you find the time to wrap this up? i would really love to see a basic seafile support in rclone :)

**Comment by creativeprojects** [comment]
Hi,

I did manage to have it working. For some small copy it was faster than Webdav.

Then I tried to sync lots of tiny files (like a very big `node_modules` folder) and I started having loads of errors from the API.

Then I tried to sync some big files (like 10GB) and the API crashed in the middle. To be fair I also had it crashing with Webdav.

So maybe I messed up something somewhere, but it looks to me that the API is not very stable when hammered with too many (or big) requests. Whichever, that's very disappointing...

So in the end I'm not sure if I should propose it the way it is and see how it works under more normal loads.

**Comment by creativeprojects** [comment]
Following my previous post, I can confirm it works all fine for a decent sized library (I have about 5GB). I've been doing backups of it for the last few months.

I believe the issues I have with trying to download many many tiny files, or alternatively very big ones is due to the fact that my Seafile server is hosted on a very cheap VPS (it was a Back Friday deal and the poor host is seriously abused. Also it's saved on spinning disk).
