### ISSUE TITLE
Issue moving large files via FTP

### ISSUE THREAD

**Issue by spotdemo4** [rclone/rclone#1878]
rclone v.1.38, Windows 10, FTP

The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
>rclone move porn:tv X:\TV -vvv --stats-log-level DEBUG --no-traverse --delete-after --acd-upload-wait-per-gb 1s

A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

>2017/12/03 00:58:27 DEBUG :
Transferred:   3.764 GBytes (10.669 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      6m1.2s
Transferring:
  ...6/Arrow - S06E01 - Fallout WEBDL-1080p.mkv: 93% done, 14.440 MBytes/s, ETA: 18s

>2017/12/03 00:59:27 DEBUG :
Transferred:   4.031 GBytes (9.799 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:      7m1.2s
Transferring:
  Arrow/Season 6/Arrow - S06E01 - Fallout WEBDL-1080p.mkv

[fulllog.txt](https://github.com/ncw/rclone/files/1524535/fulllog.txt)

The files move successfully, but they are not deleted on the FTP server, and the second transfer message is repeated indefinitely. If I terminate rclone and restart it, it is able to delete the files on the FTP server on startup.

SOMETIMES it does work properly, and does successfully delete the files on the FTP server, which leads me to believe that either this is a bug, or i'm retarded. All help is appreciated.

**Comment by ncw** [comment]
There don't seem to be enough things in your log - there is nothing when one file stops and the next starts which is strange.

I suspect that this  `--acd-upload-wait-per-gb 1s` is causing the problem.  ACD takes ages for files to appear, and if they don't then rclone will think they haven't appeared and transfer them again.  Try removing that parameter, or setting it back to nearer the default which is `3m`

**Comment by spotdemo4** [comment]
@ncw OK I tried it again without the `--acd-upload-wait-per-gb 1s` flag, and it still didn't delete the file, even after waiting 6 hours. Full log here:

[full log.txt](https://github.com/ncw/rclone/files/1525503/full.log.txt)

FYI, I ran this right after running the first log, so you can see it does successfully delete the files on the FTP server on startup. Could there be a workaround solution where it first copies the files, then deletes them after with a separate command? Thanks in advance.

**Comment by ncw** [comment]
> Could there be a workaround solution where it first copies the files, then deletes them after with a separate command? Thanks in advance.

There are obviously problems at one or the other end in these transfers.

rclone is designed so that it picks up where it left off, so I'd say a good work around would be to run it again.

I still suspect the Amazon cloud drive eventual consistency in the listings - I've had a lot of trouble with that, but running it again will tidy things up.  I'd like to see a full log of the uploads not deleting - that wasn't in the full log you sent I don't think.

**Comment by animosity22** [comment]
Please post on the forums if you still have a question as this is a very stale item!
