### ISSUE TITLE
Human-readable sizes for ls

### ISSUE THREAD

**Issue by cowwoc** [rclone/rclone#1890]
rclone 1.38

As a follow-up to https://github.com/ncw/rclone/issues/1303, please add a `--human` option to `ls` similar to the `tree` command so we can view file sizes in human-readable format.

**Comment by ncw** [comment]
I'd like to re-implement the whole ls command, but I don't want to break everyone's scripts!  Nice idea though.

And checkout `rclone ncdu` for the TUI version!

**Comment by albertony** [comment]
Available in latest beta, please check it out @cowwoc. 🙈

**Comment by timotheecour** [comment]
the flag that was added is --human-readable, not `--human`, eg this works: `rclone ls --human-readable path`
