### ISSUE TITLE
Using the mount --cache-mode flag on an crypt mount results in bad performance vs a cached remote

### ISSUE THREAD

**Issue by cal2195** [rclone/rclone#1911]
Hi there,

When using the new cached remote via `mount --cache-mode full`, it appears to request entire files to be cached rather than just a number of chunks.

But if you set up a new cached remote, and link them like this:
**cloud remote -> cache -> crypt**

It results in much better performance! I presume what's going on is as described from the cache.md docs here:

```
cache and crypt

One common scenario is to keep your data encrypted in the cloud provider using the crypt remote. crypt uses a similar technique to wrap around an existing remote and handles this translation in a seamless way.

There is an issue with wrapping the remotes in this order: cloud remote -> crypt -> cache

During testing, I experienced a lot of bans with the remotes in this order. I suspect it might be related to how crypt opens files on the cloud provider which makes it think we're downloading the full file instead of small chunks. Organizing the remotes in this order yelds better results: cloud remote -> cache -> crypt
```

Using `--cache-mode` also results in plain text caching! :o

Would it be possible to have the `--cache-mode` flag cache like
**cloud remote -> cache -> crypt**
instead of
**cloud remote -> crypt -> cache**
?

This would prevent the need in setting up a new cache remote, and editing previous remotes.

This would also mean that the cached files are encrypted instead of plain text! :)

> What is your rclone version (eg output from `rclone -V`)

rclone v1.38-226-g66558213β
- os/arch: linux/amd64
- go version: go1.9.2

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Arch Linux 64bit

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount cloud: mnt --cache-mode full
rclone mount cachedcloud: mnt

**Comment by ncw** [comment]
> When using the new cached remote via mount --cache-mode full, it appears to request entire files to be cached rather than just a number of chunks.

If you are using the cache backend, then `--vfs-cache-mode full` (as it is now called in [the latest beta](https://beta.rclone.org)) is overkill.

You want to use `--vfs-cache-mode writes` at most.  The `--vfs-cache-mode` flags are to improve file system compatibility more than do actual caching - the cache backend is much better at that.

**Comment by cal2195** [comment]
I wasn't planning on using both!

I got the impression that --vfs-cache-mode was a quick way to get a cache on a mount - is this incorrect? :)

**Comment by ncw** [comment]
> I got the impression that --vfs-cache-mode was a quick way to get a cache on a mount - is this incorrect? :)

You will get a cache and it works very well for some applications, for example the downloads on rclone are served from a mount using cache mode full with the files held on cloud storage.

However it does download the file in its entirety before serving it to you which isn't ideal for some applications.  I may fix this in the future though!  I put this in #1914 to remind me

**Comment by animosity22** [comment]
This looks be a stale issue. If you have any questions, please feel free to ask in the forums and we can help.
