### ISSUE TITLE
GDrive output formatting bug

### ISSUE THREAD

**Issue by diamondsw** [rclone/rclone#1913]
> What is your rclone version (eg output from `rclone -V`)
1.38

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Mac OS X 10.12.6, Debian 9

> Which cloud storage system are you using? (eg Google Drive)
Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync tmp google:tmp

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Relevant section is simply:
```
pacer: low level retry 1/10 (error googleapi: got HTTP response code 500 with body: {
 "error": {
  "code": 500,
  "message": null
 }
}

```
Spurious 500 errors get output in this expanded format across multiple lines which makes scripting/automating mildly more inconvenient; I assume it's the response from an API call that just needs the '\n' or '\r' characters removed. I can trawl through the code to see where it's being emitted if needed.

**Comment by ncw** [comment]
That will be the default formatting of the errors as returned by the googleapi module.

[The code is here](https://github.com/ncw/rclone/blob/master/vendor/google.golang.org/api/googleapi/googleapi.go#L87) I think.

That is rclone's vendored copy of the code though, so what is needed is a PR [to the upstream project](https://github.com/google/google-api-go-client/blob/master/googleapi/googleapi.go#L87).

Changing that line to `return fmt.Sprintf("googleapi: got HTTP response code %d with body: %q", e.Code, e.Body)`

would do it.

Want to have a go at submitting an upstream PR? Unfortunately it is a google repository so you'd have to follow their process which is a bit long winded!

**Comment by diamondsw** [comment]
I'm not familiar with normal output from that API; would the additional carriage returns be considered a bug in their output, or is it only an issue with how rclone then prints it for verbose logging?

**Comment by ncw** [comment]
> I'm not familiar with normal output from that API; would the additional carriage returns be considered a bug in their output, or is it only an issue with how rclone then prints it for verbose logging?

I think go error messages which sometimes span many lines would be considered bad form.  The fix I proposed with the `%q` turns the newlines into `\n` so they stay on one line at least.
