### ISSUE TITLE
FYI I have setup Install script and wiki for Raspberry Pi as part of my pi-timolo project

### ISSUE THREAD

**Issue by pageauc** [rclone/rclone#1916]
FYI
I just recently discovered rclone and plan to make it the default on my pi-timolo project.  I have written a simple bash install script and detailed wiki to make things easier for novice raspberry pi users. https://github.com/pageauc/pi-timolo/wiki/How-to-Setup-rclone

Claude ...

**Comment by ncw** [comment]
Looks like we've been working on [the same thing at the same time!](https://github.com/ncw/rclone/blob/master/docs/content/install.md#script-installation)

Hopefully that script should work for your purpose too.

Feel free to put a link to your project on the 3rd party page in [the rclone wiki](https://github.com/ncw/rclone/wiki).
