### ISSUE TITLE
Many files are copied / deleted / re-uploaded, when they already exist

### ISSUE THREAD

**Issue by rprieto** [rclone/rclone#1925]
- RClone version: `v1.38`
- Command: `rclone sync`
- Remote: `S3`

I have a folder which is synced with S3 using timestamp comparisons (no checksums). I just ran `rclone sync` and noticed it was trying to sync photos that haven't changed since 2014. The local timestamp on `DSC_0415.JPG` is August 2014, but the output shows:

```
2017/12/18 07:58:37 INFO  : original/2014-07/DSC_0415.JPG: Copied (server side copy)
2017/12/18 07:58:37 INFO  : original/2014-07/DSC_0415.JPG: Deleted
Transferring:
* original/2014-07/DSC_0415.JPG: 100% done, 9.026 MBytes/s, ETA: 0s
```

It looks like the RClone is doing a server-side copy to the `--backup-dir`, followed by deleting the file from the remote S3 bucket, followed by re-uploading the file.

---

The only reason I can think of is that since the last sync I renamed the root folder locally, so had to run `aws s3 mv --recursive`. This means all files on S3 have a new timestamp greater than the local timestamp. When I run with `--dry-run` Rclone seems to either

- want to update the modification time on s3 (as expected)

```
2017/12/18 10:01:46 DEBUG : large/2015-06/2015-06-15 18.42.55.jpg: Modification times differ by 20881h27m10s: 2015-07-30 11:55:28 +0000 UTC, 2017-12-16 13:22:38 +0000 UTC
2017/12/18 10:01:46 NOTICE: large/2015-06/2015-06-15 18.42.55.jpg: Not updating modification time as --dry-run
2017/12/18 10:01:46 DEBUG : large/2015-06/2015-06-15 18.42.55.jpg: Unchanged skipping
```

- want to backup / delete / re-upload the file

```
2017/12/18 09:02:46 NOTICE: original/2014-07/DSC_0772.JPG: Not moving as --dry-run
2017/12/18 09:02:46 NOTICE: original/2014-07/DSC_0772.JPG: Not copying as --dry-run
```

In the case above, the file (`DSC_0772.JPG`) does exist in the target S3 bucket. I downloaded it and compared it to the local file, and they are binary-equal (`cmp -l`). I don't understand why it doesn't update the timestamp like it does with the others.

Do you know how I can troubleshoot this? It sounds similar to #1431 except I don't use Google Drive, and I think that issue was fixed in 1.38. Thanks!

**Comment by ncw** [comment]
Did `aws s3 mv --recursive` preserve the metadata, in particulare the `mtime` that rclone uses for storing the modification time?

Can you send a log with `-vv` using [the latest beta](https://beta.rclone.org) demonstrating the problem please?

Thanks

**Comment by rprieto** [comment]
Thanks for the quick reply, I will check tonight and let you know.

**Comment by animosity22** [comment]
This is very stale. Closing out. If you still have a question, please post on the forums.
