### ISSUE TITLE
The --delete-empty-src-dirs flag deletes too many Parent Directories

### ISSUE THREAD

**Issue by holygamer** [rclone/rclone#1953]
I'm using the --delete-empty-src-dirs flag as I wanted directories deleted after they were moved. This is my situation:

```
rtorrent/data/Downloads/Private Tracker 1/
rtorrent/data/Downloads/Private Tracker 2/
```

Let's say I've got The Walking Dead Season 3 Bluray torrent downloaded into the  Downloads/Private Tracker 1/ folder above.  And I've also got Mad Men Season 1 Bluray torrent downloaded into Downloads/Private Tracker 1/

When the downloads are finished I move them manually into the TransfersToGoogleDrive/Private Tracker 1 folder below.

```
rtorrent/data/TransfersToGoogleDrive/Private Tracker 1
rtorrent/data/TransfersToGoogleDrive/Private Tracker 2
```

So I end up with this:

rtorrent/data/TransfersToGoogleDrive/Private Tracker 1/The Walking Dead Season 3 Bluray/ (mkv files are inside)
rtorrent/data/TransfersToGoogleDrive/Private Tracker 1/Mad Men Season 1 Bluray/ (mkv files are inside)
I also have other tracker folders like the above with other files in.

I run the following command to move the files into my Google Drive then delete the empty (Bluray) folders: 

`rclone move ~/private/rtorrent/data/"TransfersToGoogleDrive" gdrive:/"TransfersFromSeedbox" -v --delete-empty-src-dirs`

The problem is for example that I only wanted the folders inside the following folders deleted : 
```
rtorrent/data/TransfersToGoogleDrive/Private Tracker 1/
rtorrent/data/TransfersToGoogleDrive/Private Tracker 2/
```

Instead all the Private Tracker folders are being deleted as well.

Could you please update the program so we can specify in a command which child folders to keep. I would like the 1st child folders to be kept so that my empty Private Tracker folders aren't deleted after moving their contents.

I'm using rclone version 1.39.

**Comment by ncw** [comment]
> Instead all the Private Tracker folders are being deleted as well.

Perhaps you could loop over the folder in `rtorrent/data/TransfersToGoogleDrive` and `rclone move` them individually?

**Comment by holygamer** [comment]
What do you mean by loop?

**Comment by ncw** [comment]
I meant use a shell for loop on the listing of the directory..

Something like

```
for i in `ls rtorrent/data/TransfersToGoogleDrive`; do
    rclone move $i ....
done
```

**Comment by holygamer** [comment]
That's a bit over my head. Am I supposed to enter that in SSH?. If so, how do I integrate it with this command?:

rclone move ~/private/rtorrent/data/"TransfersToGoogleDrive" gdrive:/"TransfersFromSeedbox" -v --delete-empty-src-dirs
