### ISSUE TITLE
Same Name Folders Google Drive causing a problem.

### ISSUE THREAD

**Issue by zenjabba** [rclone/rclone#1967]
When you have the following situation

\FOLDER1\Filename1.ext

and another completely different folder with the same name (which is allowed in google drive)

\FOLDER1\Filename2.ext

rclone flips between the different folders that it presents. Could it instead just "merge" them together

**Comment by ncw** [comment]
You can merge the folders with [rclone dedupe](https://rclone.org/commands/rclone_dedupe/) which will copy the contents of one folder into the other.

rclone doesn't deal well with duplicated file names in general so running `rclone dedupe` on your drive is recommended.

**Comment by zenjabba** [comment]
Tried that, just made a nasty mess.

**Comment by ncw** [comment]
> Tried that, just made a nasty mess.

In what way?  `rclone dedupe` normally works very well if a bit slowly...

**Comment by zenjabba** [comment]
Basically if it's owned by different owners but the same filename, dedupe fails

**Comment by ncw** [comment]
> Basically if it's owned by different owners but the same filename, dedupe fails

Ah ha!  Do you have a log of that happening?
