### ISSUE TITLE
FTP: Support active mode

### ISSUE THREAD

**Issue by sinnerliu** [rclone/rclone#1971]
> What is your rclone version (eg output from `rclone -V`)

1.3.9

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

centos7.4

> Which cloud storage system are you using? (eg Google Drive)

ftp

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount remote_ftp: /tmp/ftppath

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I hope add  PASV and PORT  when rclone config ftp . because ftp server only accept PASV;
thinks!

**Comment by ncw** [comment]
Rclone FTP uses EPSV mode by default.  Which ftp sever are you using and what errors did you get - can you post logs?

**Comment by sinnerliu** [comment]
[root@localhost rclone-v1.39-linux-amd64]$ ./rclone -vv ls ftp125:
2018/01/19 10:04:43 DEBUG : Using config file from "/home/root/.config/rclone/rclone.conf"
2018/01/19 10:04:43 DEBUG : rclone: Version "v1.39" starting with parameters ["./rclone" "-vv" "ls" "ftp125:"]
2018/01/19 10:04:43 DEBUG : ftp://11.51.11.125:21: Connecting to FTP server
2018/01/19 10:04:45 INFO  : ftp://11.51.11.125:21: Modify window not supported
2018/01/19 10:05:46 ERROR : : error listing: dial tcp 11.51.11.125:50276: i/o timeout
2018/01/19 10:05:46 Failed to ls: dial tcp 11.51.11.125:50276: i/o timeout

but use ftp command is ok:

[root@localhost ~]# ftp -i -n
ftp> open 11.51.11.125
Connected to 11.51.11.125 (11.51.11.125).
220 Xlight FTP 3.7 就绪...
Remote system type is UNIX类型:.
ftp> user 123 123
331 需要密码 123
230 登录成功
ftp> passive
Passive mode off.
ftp> ls
200 PORT命令执行成功
150 正在打开文本模式数据连接为 /bin/ls (165 比特).
drw-rw-rw- 1 ftp ftp                0 Sep 27  2017 .
drw-rw-rw- 1 ftp ftp                0 Sep 27  2017 ..
drw-rw-rw- 1 ftp ftp                0 Sep 27  2017 i2p
226 传送完毕 (1.031 KB/s).
ftp>

**Comment by ncw** [comment]
> Passive mode off.

Ah, you are using active mode...

Unfortunately the ftp library I'm using doesn't support active mode: https://github.com/jlaffaye/ftp/issues/29

**Comment by sinnerliu** [comment]
thinks ,I will wait for rclone support active mode

**Comment by rvalitov** [comment]
This issue is not fixed yet?

**Comment by ncw** [comment]
> This issue is not fixed yet?

It needs a volunteer to add it to  jlaffaye/ftp#29

**Comment by rajeshgoyalg** [comment]
This issue is not yet fixed. And I am getting error "Failed to copy: Put mkParentDir failed: EOF" while rclone copy.
https://forum.rclone.org/t/rclone-copy-to-ftp-error-with-put-mkparentdir-failed/21674

**Comment by ncw** [comment]
> The only fix I can provide for this ticket, will be a documentation fix saying
> `rclone will not support ftp active mode due to security concerns. please revert to other tools`.
> cc @ncw

I have used active mode a few times but not for at least 15 years. Its useful when the FTP server you are trying to connect to is behind a firewall that doesn't accept arbitrary incoming ports and doesn't snoop the FTP protocol to read which ports it should open.

FTP is a disaster area for security - passive mode for the server, active mode for the client.

@BraINstinct0 - do you have a use case for Active mode FTP?

As far as rclone support, I'd stand by my original comment

> It needs a volunteer to add it to [jlaffaye/ftp#29](https://github.com/jlaffaye/ftp/issues/29)

So I'd probably re-word your text slightly @ivandeex 

We have this at the moment

> FTP servers acting as rclone remotes must support 'passive' mode. Rclone's FTP implementation is not compatible with 'active' mode.

How about

> FTP servers acting as rclone remotes must support 'passive' mode. Rclone's FTP implementation is not compatible with 'active' mode as [the library it uses doesn't support it](https://github.com/jlaffaye/ftp/issues/29). This will likely never be supported due to security concerns.

**Comment by ivandeex** [comment]
> As far as rclone support, I'd stand by my original comment
> 
> > It needs a volunteer to add it to [jlaffaye/ftp#29](https://github.com/jlaffaye/ftp/issues/29)

I will add this text together with the link to the https://rclone.org/ftp

**Comment by ivandeex** [comment]
> As far as rclone support, I'd stand by my original comment
> 
> > It needs a volunteer to add it to [jlaffaye/ftp#29](https://github.com/jlaffaye/ftp/issues/29)

I will add this text together with the link to the https://rclone.org/ftp
