### ISSUE TITLE
Error reading source directory: CreateFile \?\c:\users\user\Recent: Access is denied

### ISSUE THREAD

**Issue by cowwoc** [rclone/rclone#1973]
> What is your rclone version (eg output from `rclone -V`)

1.38

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10, 64-bit

> Which cloud storage system are you using? (eg Google Drive)

B2

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone copy c:\users\gili -L --stats-log-level NOTICE --fast-list  -vv encrypted:public --include "Recent/**"`

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2018/01/13 12:53:17 DEBUG : Using config file from "C:\\Users\\Gili\\.rclone.conf"
2018/01/13 12:53:17 DEBUG : rclone: Version "v1.38" starting with parameters ["C:\\Program Files\\rclone-v1.38-windows-amd64\\rclone" "copy" "c:\\users\\gili" "-L" "--stats-log-level" "NOTICE" "--fast-list" "-vv" "encrypted:public" "--include" "Recent/**"]
2018/01/13 12:53:20 INFO  : Encrypted drive 'encrypted:public': Modify window is 1ms
2018/01/13 12:53:20 DEBUG : .android: Excluded from sync (and deletion)
[...snip...]
2018/01/13 12:53:35 DEBUG : Music/AlbumArt_{5293FBA6-A228-468F-8654-7742A7F930B8}_Small.jpg: Excluded from sync (and deletion)
2018/01/13 12:53:35 ERROR : Recent: error reading source directory: failed to open directory "Recent": open \\?\c:\users\gili\Recent: Access is denied.
2018/01/13 12:53:35 INFO  : Encrypted drive 'encrypted:public': Waiting for checks to finish
2018/01/13 12:53:35 INFO  : Encrypted drive 'encrypted:public': Waiting for transfers to finish
2018/01/13 12:53:35 ERROR : Attempt 3/3 failed with 1 errors
2018/01/13 12:53:35 NOTICE: 
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 1
Checks:                 0
Transferred:            0
Elapsed time:       18.2s

2018/01/13 12:53:35 DEBUG : Go routines at exit 6
```

**Comment by ncw** [comment]
Can you give instructions on how to create the Recent directory it is having problems with?

**Comment by cowwoc** [comment]
@ncw This is a hidden junction point that gets created by default for every Windows user. Meaning, it should already be there for the current user you are logged in as. Note that I am running under Windows 10 but I believe this issue exists under Windows 7 as well.

**Comment by ncw** [comment]
> This is a hidden junction point that gets created by default for every Windows user. Meaning, it should already be there for the current user you are logged in as. Note that I am running under Windows 10 but I believe this issue exists under Windows 7 as well.

Oh, I see...

I tried to replicate this on Windows 7 but rclone seems to have no problem using the "Recent Items" directory...

You could exclude it I suppose since it doesn't seem that useful to back it up?
