### ISSUE TITLE
Cannot Delete Empty Directory

### ISSUE THREAD

**Issue by AshtonKnight** [rclone/rclone#1980]
So I'm with Google Drive and from what I can see on the Google Drive dashboard, everything is good. But when I go into the terminal on my server and navigate to the mounted drive, there is a directory there that's not present on the dashboard. I deleted it from the Dashboard a while ago but didn't realise it was still present on the drive until recently.

For reference, my drive is `/mnt/Gdrive`. The directory I want to delete is `/mnt/Gdrive/TV Shows/Lethal Weapon`. Here's what I've tried so far:

`cd /mnt/Gdrive/"TV Shows"`

I then do:

`rclone rmdir "Lethal Weapon"`

but all I get is:

```
2018/01/16 18:59:21 NOTICE: Config file "/home/plexuser/.config/rclone/rclone.conf" not found - using defaults

2018/01/16 18:59:27 ERROR : Attempt 1/3 failed with 1 errors and: remove /mnt/Gdrive/TV Shows/Lethal Weapon: input/output error

2018/01/16 18:59:29 ERROR : Attempt 2/3 failed with 1 errors and: remove /mnt/Gdrive/TV Shows/Lethal Weapon: input/output error

2018/01/16 18:59:31 ERROR : Attempt 3/3 failed with 1 errors and: remove /mnt/Gdrive/TV Shows/Lethal Weapon: input/output error

2018/01/16 18:59:31 Failed to rmdir: remove /mnt/Gdrive/TV Shows/Lethal Weapon: input/output error
```

Doing just `rclone rmdirs` by itself deletes it for about 35 minutes but then it reappears. But during this time if I do `locate Lethal` it will list `/mnt/Gdrive/TV Shows/Lethal Weapon` showing that it's still there.

Anyone got any ideas?

**Comment by ncw** [comment]
> 2018/01/16 18:59:27 ERROR : Attempt 1/3 failed with 1 errors and: remove /mnt/Gdrive/TV Shows/Lethal Weapon: input/output error

There should have been a corresponding error in the mount log - can you paste it here?

Weird stuff on drive is often caused by duplicate files or directories, so run `rclone dedupe` on your drive would be advice.

**Comment by AshtonKnight** [comment]
Sorry man, I feel like an idiot. I can't find how to view the mount log.

I've done `rclone dedupe mnt/Gdrive/"TV Shows":"Lethal Weapon"` but all I got was:

```
2018/01/16 20:36:26 NOTICE: Config file "/home/plexuser/.config/rclone/rclone.conf" not found - using defaults
2018/01/16 20:36:26 ERROR : : error listing: directory not found
2018/01/16 20:36:26 Failed to dedupe: find duplicate dirs: directory not found
```

I'm SSHing via Putty into a remote Ubuntu 16.04 server if that helps. I also don't have root access.

**Comment by ncw** [comment]
@AshtonKnight wrote:
> Sorry man, I feel like an idiot. I can't find how to view the mount log.

No worries!  I presume that rclone is providing `/mnt/Gdrive/`? If so then you have an `rclone mount` process running and that should be making logs somewhere...

> I've done `rclone dedupe mnt/Gdrive/"TV Shows":"Lethal Weapon"` but all I got was:

You need to do the dedupe on the drive remote, so something like `rclone dedupe gdrive:"TV Shows"` rather than doing it on the mount.

**Comment by DonPiotr** [comment]
Hi!
I have same problem with S3-like storage:
I can't remove empty directories with:
rclone rmdirs MyS3:bucket/dir1
rclone rmdir MyS3:bucket/dir1/dir2 ; rclone rmdir MyS3:bucket/dir1
rclone mount MyS3:bucket mnt & ; rmdir mnt/dir1/dir2 ; rmdir mnt/dir1
None of those delete anything.
After last command, if I ls mounted point, dir1 isn't shown.
But when I remount it, dir1 reappears.

**Comment by ncw** [comment]
@DonPiotr this will be because you have directory markers I think.. How did the files get uploaded?

**Comment by DonPiotr** [comment]
@ncw  They are uploaded from IP Camera by FTP.

**Comment by ncw** [comment]
@DonPiotr this is a separate issue I think.

Rclone needs to take notice of directory markers (optionally probably).  Not all bits of software use directory markers.

There is a plan to make rclone understand directory markers which I'm thinking about.

**Comment by animosity22** [comment]
This looks like an old item. If you still need help, please post on https://forums.rclone.org and we can help out.
