### ISSUE TITLE
opendrive webdav: i/o timeout with files they are larger than 10GB

### ISSUE THREAD

**Issue by s20p17a1m14** [rclone/rclone#1981]
If i'm uploading files with more than 10GB i got this error:

> my log:
> DEBUG : pacer: low level retry 1/1 (error Put https://webdav.opendrive.com/“Folder1”: read tcp ...:37840->...:443: i/o timeout)
> ERROR : “Folder1”-: Failed to copy: Put https://webdav.opendrive.com/“Folder1”: read tcp ...:37840->...:443: i/o timeout

**rclone Version** v1.39-015-g28480c05ß
**OS:** Debian Linux 64bit
**Storage**: opendrive
**command**: rclone copy acd: opendrive: --update --transfers 1 --vv --timeout=120m

**Comment by ncw** [comment]
Here is what the docs say about that timeout which is what was mentioned in [the forum](https://forum.rclone.org/t/problems-moving-large-files-to-webdav/4528/5).

```go
	// ResponseHeaderTimeout, if non-zero, specifies the amount of
	// time to wait for a server's response headers after fully
	// writing the request (including its body, if any). This
	// time does not include the time to read the response body.
	ResponseHeaderTimeout time.Duration
```

So what is happening seems to be that after the file is uploaded, opendrive is taking more than 2 minutes to come back and say that the file was uploaded OK...

However @s20p17a1m14 your errors look different.  They appear to be coming from reading the files from ACD.  You've deleted the IP addresses in the log - were they from amazon or opendrive?

**Comment by animosity22** [comment]
With ACD dead, I'm guessing this isn't an issue anymore.

If you still need help, please feel free to post in the forums and we can help out.
