### ISSUE TITLE
Failed to create file system for "remote:": couldn't create Drive client: client is nil

### ISSUE THREAD

**Issue by shigutso** [rclone/rclone#1991]
> What is your rclone version (eg output from `rclone -V`)
rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 17.10 x86_64

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone ls remote:`

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

`2018/01/20 01:08:24 Failed to create file system for "remote:": couldn't create Drive client: client is nil`

This is my config file:
```
[remote]
type = drive
client_id =
client_secret =
service_account_file = /home/vitor/client_secret.json
```

What am I missing? Tried inserting the client_id and client_secret in the config file, but the same issue happens...

Thanks

**Comment by ncw** [comment]
Your config looks OK for a service account.

Your service account file should look something like

```json
{
  "type": "service_account",
  "project_id": "PROJECT",
  "private_key_id": "XXX",
  "private_key": "-----BEGIN PRIVATE KEY-----XXXX\n",
  "client_email": "rclone-test@PROJECT.iam.gserviceaccount.com",
  "client_id": "XXX",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/rclone-test%40PROJECT.iam.gserviceaccount.com"
}
```

I just had a look at the code... There is a bit of error handling missing which is embarassing since I reviewed it!  I've made a fix, so if the above doesn't help, at least you should now get a sensible error message

https://beta.rclone.org/v1.39-048-g25a41e19/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
25a41e1945423bb024865697d274b711291029ae since I forgot to link the ticket..
