### ISSUE TITLE
Failed to calculate hash due to error in source or destination results in replacing existing

### ISSUE THREAD

**Issue by vkukk** [rclone/rclone#2017]
rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2

CentOS 6 64b.

When copying (command copy) between two Openstack Swift with --checksum, if rclone fails to calculate src or dst hash, its copying from src to dst anyway, replacing existing object. I've seen that happen if src or destination responds with 408, 504.

This causes unneccessary traffic and increases costs.

rclone should skip file when it fails to calculate hash. At least there should be possibility to have configuration options to skip on error. At some next run, calculation will succeed and no data will be transferred.

**Comment by ncw** [comment]
Have you got some logs with -vv of this happening?  That would be very helpful.

**Comment by animosity22** [comment]
This looks to be a stale issue. If you still have a problem, please post on the forums and we are happy to help out.
