### ISSUE TITLE
Include full path in `rclone lsjson`

### ISSUE THREAD

**Issue by microbug** [rclone/rclone#2019]
On rclone v1.39, the lsjson output for a directory produces something like this:

```
[{
	'Path': '2011-02-01',
	'Name': '2011-02-01',
	'Size': -1,
	'ModTime': '2018-01-26T21:25:29.494Z',
	'IsDir': True
}]
```

Where `'Path'` is not the full path as suggested [on the relevant docs page](https://rclone.org/commands/rclone_lsjson/), but in fact is the path relative to the specified `remote:path` (i.e., `'Path'` above should be `vault:backups/test/2011-02-01`).

IMO, the current `'Path'` should be called `'RelativePath'`. Another item could be added called `FullPath`.

**Comment by B4dM4n** [comment]
`Path` is the full path under root specified on the commandline.

For example `rclone lsjson TestDrive:rclone-test-wodepeh0medolen1ginexir2` will result in
```
[
{"Path":"file name.txt","Name":"file name.txt","Size":100,"ModTime":"2001-02-03T04:05:06.499Z","IsDir":false}
]
```

But when using the `-R` option on the remote like `rclone lsjson -R TestDrive:`, you will see the full path:
```
[
{"Path":"rclone-test-wodepeh0medolen1ginexir2","Name":"rclone-test-wodepeh0medolen1ginexir2","Size":-1,"ModTime":"2018-01-21T21:58:44.896Z","IsDir":true},
{"Path":"rclone-test-wodepeh0medolen1ginexir2/file name.txt","Name":"file name.txt","Size":100,"ModTime":"2001-02-03T04:05:06.499Z","IsDir":false}
]
```

That implies without `-R` that `Path == Name` is always true.

Maybe a option like `--full-path` would be nice, that prodices the following output for `rclone lsjson --full-path TestDrive:rclone-test-wodepeh0medolen1ginexir2`:
```
[
{"Path":"TestDrive:rclone-test-wodepeh0medolen1ginexir2/file name.txt","Name":"file name.txt","Size":100,"ModTime":"2001-02-03T04:05:06.499Z","IsDir":false}
]
```

In the meantime you can use `jq` to modify the `Path` manually:
```
rclone lsjson -R TestDrive: | jq 'map(. + {Path: ("TestDrive:" + .Path)})'
```

**Comment by ncw** [comment]
I don't really want to change `Path` as this will break existing uses.  Adding an additional field would be possible, however since `lsjson` is designed for program use then the program can just tack the remote on itself.

I'm more inclined to update the docs to make them clearer - how does that sound?

**Comment by B4dM4n** [comment]
I created a PR to explain the Path value more precisely in the documentation.

I think @ncw is right, that json is supposed to be used in automated ways.
The result of lsjson provides all the information programs need to work on a directory tree.

**Comment by microbug** [comment]
Thanks all. I think an additional `FullPath` field would be useful.
