### ISSUE TITLE
Request: webdav client certificate authentication

### ISSUE THREAD

**Issue by onnozweers** [rclone/rclone#2025]
We use `rclone` with a WebDAV storage service with username/password authentication and that works wonderfully!

We also have use cases where people would like to use client certificates to authenticate. Would it be possible to support this?

`curl` does support this with `--cert`, but `rclone` has some significant advantages like parallel transfers and various sync options.

Kind regards,
Onno

**Comment by ncw** [comment]
Sounds like a reasonable request!

Fancy having a go?  You would have to adjust [the client config](https://github.com/ncw/rclone/blob/master/fs/fshttp/http.go#L122) to supply the client certificate.  There is an example of how to do it in [the secure client section on this page](http://www.bite-code.com/2015/06/25/tls-mutual-auth-in-golang/).

**Comment by onnozweers** [comment]
I'm afraid I don't speak any Go...

**Comment by ivandeex** [comment]
Closing after 3 years of inactivity

**Comment by ncw** [comment]
@kristanbbc 

did you try these - I think they should work for client cert auth

      --ca-cert stringArray    CA certificate used to verify servers
      --client-cert string     Client SSL certificate (PEM) for mutual TLS auth
