### ISSUE TITLE
Using FileID instead of the file location for Drive Cache

### ISSUE THREAD

**Issue by dany20mh** [rclone/rclone#2026]
I was just testing the cache option and I noticed it's cache the location of the file, so if the file move or change it's name and something like that, it will try to cache the file again, but if it cache the FileID, that won't change and it's unique.

> What is your rclone version : rclone v1.39-045-ga80d8a21β

> Which OS you are using and how many bits : macOS

> Which cloud storage system are you using? Google Drive

> The command you were trying to run : rclone mount --allow-other -vv --cache-db-path=/Volumes/SSD/cache --cache-total-chunk-size=100G --cache-info-age=1m pcache: ./mtng2

**Comment by ncw** [comment]
We don't currently have an ID method for Objects, but I was thinking of adding one.

Is this interesting to you @remusb ?

**Comment by remusb** [comment]
It's an interesting idea but do all the backends have an internal id? 
@dany20mh the file would change outside of rclone right? Like going in the Drive UI and moving stuff around. It would keep the same id but on a different path

**Comment by dany20mh** [comment]
@remusb

I’m not sure if all the backend using ID or not, but drive use the ID and it help to locate the file no matter if the name change or location move.

Right now if you set the cache location in the rclone mount, you can see it will cache the file base of its name and location, so if I move that file in the Drive UI or inside the computer, the cache become useless.

**Comment by ncw** [comment]
> It's an interesting idea but do all the backends have an internal id?

No... but we could fall back to the "remote" in that case maybe...

**Comment by remusb** [comment]
@ncw Yep. That would work.
@dany20mh I see the value in this really but sadly the persistency in cache is stored as a FS (folders contain files, files contain data) and both caching layers are built on it: folder listings and file data.

I would really like to implement this and change the model of the persistency to a flat schema using this internal id and maybe even rely on dir cache from rclone for the structure but I really see this like a 2.0 version as there's a bit too much to do now in the short term.
Until then, cache will function as a backend and handle moves and all the other fs operations like any other backend.

If you want to contribute this, I would help you.

**Comment by ivandeex** [comment]
Closing after 3 years of inactivity
