### ISSUE TITLE
feature request: read/write from/to samba (smb) drives

### ISSUE THREAD

**Issue by dtenenba** [rclone/rclone#2042]
If rclone could support reading and writing from/to samba (smb) shares that would simplify my workflow greatly.
In other words, if rclone could do what `smbclient` does.

**Comment by ncw** [comment]
If someone writes a go library to interface with smb then we'll do it, but writing a smb library is too big a project for us I think!

**Comment by dtenenba** [comment]
Thanks. Looks like there are a couple of packages out there, not sure if they are good enough:
https://github.com/stacktitan/smb
https://golanglibs.com/top?q=smb

**Comment by mathiasgredal** [comment]
Stacktitans implementation is very minimal and only includes the authentication parts. A library like https://github.com/videolabs/libdsm should most likely be ported to go before a backend could be implemented.

**Comment by ncw** [comment]
This looks like it might be complete enough: https://github.com/hirochachacha/go-smb2

**Comment by tooptoop4** [comment]
any idea when this will be available?

**Comment by ncw** [comment]
@tooptoop4 we are looking for someone to work on this. Do you want to have a go?

**Comment by tooptoop4** [comment]
@ncw its beyond my go skills

**Comment by tooptoop4** [comment]
there is a PR!!!

**Comment by ncw** [comment]
This is now merged to master.

If anyone would like to try it please use [the latest beta](https://beta.rclone.org/) and make new issues with any problems.

If all goes well it will be released in 1.60

**Comment by dtenenba** [comment]
https://rclone.org/smb/
