### ISSUE TITLE
cache: tests intermittently failing

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#2045]
I'm seeing intermittent test failures for the cache code

In the [travis tests](https://travis-ci.org/ncw/rclone/jobs/336621163#L1075)

```
--- FAIL: TestCacheNew (0.01s)
	run.go:169: Remote "Local file system at /tmp/rclone311111661", Local "Local file system at /tmp/rclone563151464", Modify Window "1ns"
	Error Trace:	cache_test.go:82
	Error:      	Received unexpected error:
	            	stat /home/travis/.cache/rclone/vfs/local/tmp/rclone311111661: no such file or directory
	Test:       	TestCacheNew
```

In the [integration tests](https://pub.rclone.org/integration-tests/2018-02/2018-02-03-054123/test-v1.39-120-g82418c30.txt)

```
--- FAIL: TestInternalUploadQueueOneFileNoRest (16.54s)
	assertions.go:247: 
                          
	Error Trace:	cache_internal_test.go:466

			cache_internal_test.go:493
		
	Error:      	Received unexpected error:
		
	            	stat /tmp/rclonecache-tmp267213561/tiuqofnr1517634156/one: no such file or directory
		
	Test:       	TestInternalUploadQueueOneFileNoRest
```

@remusb can you take a look please? Thanks!

**Comment by remusb** [comment]
@ncw most of those tests are skipped when there's no remote `TestCache`. Does it exist there?

I can simply rename the default for those internal tests, they're not supposed to run on low powered environments anyway and there's little value to have them to run on every push (outside cache)

**Comment by ncw** [comment]
On the integration test server I supply a "TestCache:" pointing at a local folder.  These run once a day.

On the travis tests there shouldn't be a `TestCache:`.

I don't mind the odd integration test run failing, but I'd like the travis tests to always pass.

I found another example of that test failing in the travis tests: https://travis-ci.org/ncw/rclone/jobs/336570479#L947

I suspect both of those tests are failing because there is a race between the file getting written to the disk and you attempting to stat it....

**Comment by remusb** [comment]
This shouldn't be causing an issue from cache anymore. I do see VFS cache fails frequently due to a race condition. I assume that would be the same one reported here?

**Comment by ncw** [comment]
I think this issue is obsolete now!
