### ISSUE TITLE
error authenticating swift connection: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by Purexo** [rclone/rclone#2058]
Hello, I've this problem but it appear randomly.

I wrote this issue because the bug, during I write this, I retest commands for logs, and it work.
I retry 5 minutes later and same bug apear 😕.

> What is your rclone version (eg output from `rclone -V`)

rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian jessie

> Which cloud storage system are you using? (eg Google Drive)

hubic

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

- `rclone lsd remote:`
- `rclone sync ./logs_backup/ remote:logs`

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
rclone -vvvv sync ./logs_backup/ remote:logs
2018/02/09 22:10:10 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2018/02/09 22:10:10 DEBUG : rclone: Version "v1.39" starting with parameters ["rclone" "-vvvv" "sync" "./logs_backup/" "remote:logs"]
2018/02/09 22:10:11 Failed to create file system for "remote:logs": error authenticating swift connection: invalid character '<' looking for beginning of value
```

**Comment by ncw** [comment]
Try running with `-vv --dump bodies` and I think you'll see that hubic is returning some kind of error message.  Can you paste it here?

**Comment by ncw** [comment]
@toddfries that looks like a different problem.  Does it do that all the time or just intermittently?

**Comment by jscinoz** [comment]
It seems to be an issue on Hubic's end, intermittently their backend will 302 to `error.xml` during authentication.

There are [some](https://forums.hubic.com/showthread.php?5173-get-token-erreur-302) [posts](https://forums.hubic.com/showthread.php?56463-Get-credentials-will-return-302-every-4-hours) on the Hubic forum about this issue, but they never reached a resolution after years, so I don't think we can expect Hubic to fix their backend.

Could rclone handle this failure by simply retrying on one of these spurious reponses?

**Comment by ncw** [comment]
At the moment rclone will retry the hubic auth 10 times if it fails 
164d1e05cafc0ce554f389b9d7d0ca620004c2a3 which made it a whole lot more reliable.

@jscinoz are you having this problem?  Can you post what happens with `-vv --dump bodies`

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
