### ISSUE TITLE
summary option for FAILED cryptchecks/checks

### ISSUE THREAD

**Issue by ljr9600** [rclone/rclone#2061]
It would be very nice to have a summary option that will list all the *failed* checks at the END of the cryptcheck or check command.  I know this will take up more memory because the info has to be saved, but in some cases, I don't run with debug on, or log the output to a file, and this "summary" or "stat" will be helpful to see the checks that failed.

Just a thought.

**Comment by ncw** [comment]
If you run with `-v --stats 1m` or `--stats 1m --stats-log-level NOTICE` then rclone will print the number of errors at the end.  Is that what you mean?
