### ISSUE TITLE
Cache mount tries to mount files with illegal characters

### ISSUE THREAD

**Issue by PiscisSwimeatus** [rclone/rclone#2063]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.39-125-g9a653fea
os/arch: windows/amd64
go version: go1.9.2

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows Server 2016 

> Which cloud storage system are you using? (eg Google Drive)

Google Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount

Cache mount tries to mount files with illegal characters *?": etc..

```
2018/02/09 17:04:40 ERROR : worker-7 <Mostly.Ghostly.Have.You.Met.My.Ghoulfriend?.2014.1080p.BluRay.x264.YIFY.mp4>: failed caching chunk in storage 109051904: open C:\rclone\CacheG3/Movies/Mostly Ghostly Have You Met My Ghoulf
riend (2014)/Mostly.Ghostly.Have.You.Met.My.Ghoulfriend?.2014.1080p.BluRay.x264.YIFY.mp4/109051904: The filename, directory name, or volume label syntax is incorrect.
```

**Comment by ncw** [comment]
I think we've seen this problem before... The problem is that the name of the file contains characters that windows can't store on the file system.

The VFS cache has the same problem too I think and I suspect just plain `rclone mount` will have this problem providng characters to Windows which it can't deal with.

There are several solutions, but the best might be a reversible mapping which maps non windows/unix safe characters to something else.  I made a scheme which uses lookalike characters from unicode plus an additional escaping mechanism.

I wonder also how Windows deals with two files like "HELLO.txt" and "hello.txt" on a mount.

@PiscisSwimeatus how does that file appear in the rclone mount and what is its actual name if you do `rclone ls` for instance?

**Comment by ncw** [comment]
@remusb any ideas on this?  What do you think of the reversible filename mapping idea?

**Comment by PiscisSwimeatus** [comment]
My tests:
![image](https://user-images.githubusercontent.com/4976642/36061055-b98c1e04-0e54-11e8-8767-d99fdd548e38.png)
![image](https://user-images.githubusercontent.com/4976642/36061058-c4af1e94-0e54-11e8-92b6-c2664e6fa4a0.png)
![image](https://user-images.githubusercontent.com/4976642/36061061-cd0bed38-0e54-11e8-9a90-f8b74e7d86f8.png)

PS C:\Users\aj> rclone ls --config "C:\rclone\rclone.conf" GoogleG3:/Special
        4 0021!.txt
        4 0022".txt
        4 0023#.txt
        4 0024$.txt
        4 0025%.txt
        4 0026&.txt
        4 0027'.txt
        4 0028(.txt
        4 0029).txt
        4 002A*.txt
        4 002B+.txt
        4 002C,.txt
        4 002D-.txt
        4 002E..txt
        4 002F／.txt
        4 003A:.txt
        4 003B;.txt
        4 003C<.txt
        4 003D=.txt
        4 003E>.txt
        4 003F?.txt
        4 005B[.txt
        4 005C\.txt
        4 005D].txt
        4 005E^.txt
        4 005F_.txt
        4 0060`.txt
        4 007B{.txt
        4 007C|.txt
        4 007D}.txt
        4 007E~.txt
        4 CASE.txt
        4 case.txt
        4 dupe.txt
        4 dupe.txt
PS C:\Users\aj>

Normal mount:

PS C:\Users\aj> rclone mount -vv --config "C:\rclone\rclone.conf" GoogleG3:/Special T:

![image](https://user-images.githubusercontent.com/4976642/36061078-3ef41bd2-0e55-11e8-9967-5d3c32ceb437.png)

**Comment by PiscisSwimeatus** [comment]
Trying to copy the files went ok:
[rclone.log](https://github.com/ncw/rclone/files/1713272/rclone.log)

![image](https://user-images.githubusercontent.com/4976642/36061127-1ecc7b46-0e56-11e8-8d6f-2cd5db8e9e44.png)

**Comment by PiscisSwimeatus** [comment]
Mount with cache:
rclone mount -vv --config "C:\rclone\rclone.conf" Special:/ T: --log-file="rclone.log"

![image](https://user-images.githubusercontent.com/4976642/36061156-93bb718c-0e56-11e8-9b8f-95512ebd4632.png)

Then trying to open them all:
[rclone.log](https://github.com/ncw/rclone/files/1713276/rclone.log)

**Comment by PiscisSwimeatus** [comment]
Let me know if you need more testing

**Comment by ncw** [comment]
@PiscisSwimeatus nice tests thanks.

It looks like WinFSP is translating the characters Windows can't copy with to `·` maybe - I didn't think that we might have to do that translation in the VFS layer.

Can you actually open one of those files from the normal mount (without the cache)?

**Comment by PiscisSwimeatus** [comment]
Looking at the normal mount copy it looks like the characters are translated back to the correct ones on Google Drive except the / one which got translated into ／:

![image](https://user-images.githubusercontent.com/4976642/36061361-71e35ee6-0e59-11e8-9492-bfde48f89da0.png)

**Comment by PiscisSwimeatus** [comment]
So it only looks like the only issue is cache chunk storage

**Comment by ncw** [comment]
@PiscisSwimeatus thanks for testing.  It looks like WinFSP is doing some clever translation for rclone which is nice.

This is still an issue with the VFS cache too.

**Comment by remusb** [comment]
I believe I've seen some Windows test failures related to weird characters in the past.

I can certainly add some mapping but I feel this should be defined at a more generic location available to other layers in rclone. Perhaps somewhere in `fs`? 
I can then use the mapper in cache where the entries are serialized and it can be done in a similar fashion in vfs.

What do you think? @ncw

**Comment by horganizzato** [comment]
I've been getting errors on windows about invalid filename because some files (auto-generated on linux) contained : and * characters.

Googling for a config option to "pretend" those special characters are really just some harmless ascii, but i haven't found anything yet. 

so, i'm running this in cygwin to manually rename the perpetrators

find /cygdrive/r/ -name "*\**" -o -name "\:"

**Comment by ivandeex** [comment]
@ncw 
This issue might have been gone after recent encoding efforts

**Comment by ivandeex** [comment]
@PiscisSwimeatus This problem is reported against obsolete rclone version. Can you reproduce it with rclone 1.54?

**Comment by PaarthShah** [comment]
Not the original reporter, and not *exactly* the original issues, but I've found that while using VFS, copying files into directories that have Windows-illegal characters in them is not possible. However, copying them into a subdirectory (with no illegal characters) of such a directory is still possible.

**Comment by ivandeex** [comment]
@PaarthShah
Since 1.39 we replaced _cache_ by _VFS_ and upgraded WinFSP.
Yours is a **different problem** for sure, and it needs its own ticket with full command and debug log.
If you submit it, we'll try to reproduce and help you.

**Comment by ivandeex** [comment]
I'm going to close this stale request as its author did not reply.
