### ISSUE TITLE
Filter tags areignored

### ISSUE THREAD

**Issue by DJIronic** [rclone/rclone#2066]
Hello,

I have a problem with excluding and filtering. I want to completely exclude .log and .sock "files" from the backup, as they not needed or event not real files. I used the command written below, but its still backup all the logs and trying to backup .sock files (they are not real files, just temp instance files). 

I am also backuping a lot of pretty small files, so the speed is just around 1,6 - 2,5 MB/s...any idea how to speed it up? (I am backuping music libraries and I don't have enough space to create ZIP archive of evertything at HDD).

> What is your rclone version

rclone v1.39
- os/arch: linux/amd64
- go version: go1.9.2

> Which OS you are using and how many bits

CentOS release 6.9

> Which cloud storage system are you using?

Google Drive (Team Drive)

> The command you were trying to run

`rclone sync /usr/local/centovacast/var/vhosts SimonDrive:/backups/sky1  --copy-links -v --exclude *.log --filter "- *.sock"`

Thank you for your help.

**Comment by animosity22** [comment]
This looks to be answered so closing out. If you still have a question, please feel free to ask on the forums.
