### ISSUE TITLE
Google Drive Shared with me Folder copy to my drive. 

### ISSUE THREAD

**Issue by vantobang** [rclone/rclone#2078]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the latest beta of rclone.

    https://beta.rclone.org/
    https://rclone.org/downloads/

If you've just got a question or aren't sure if you've found a bug then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)

Rclone-v1.39-linux / Rclone-v1.39-Windows.64

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu / Windows 10 64bit

> Which cloud storage system are you using? (eg Google Drive)

Google Gsuite

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy --drive-shared-with-me aaa aaa:DIR 

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2018/02/18 12:20:51 INFO  : Google drive root 'DIR': Modify window is 1ms
2018/02/18 12:20:51 ERROR : : error reading source directory: directory not found
2018/02/18 12:20:51 INFO  : Google drive root 'DIR': Waiting for checks to finish
2018/02/18 12:20:51 INFO  : Google drive root 'DIR': Waiting for transfers to finish
2018/02/18 12:20:51 ERROR : Attempt 1/3 failed with 1 errors
2018/02/18 12:20:52 ERROR : : error reading source directory: directory not found
2018/02/18 12:20:52 INFO  : Google drive root 'DIR': Waiting for checks to finish
2018/02/18 12:20:52 INFO  : Google drive root 'DIR': Waiting for transfers to finish
2018/02/18 12:20:52 ERROR : Attempt 2/3 failed with 1 errors
2018/02/18 12:20:52 ERROR : : error reading source directory: directory not found
2018/02/18 12:20:52 INFO  : Google drive root 'DIR': Waiting for checks to finish
2018/02/18 12:20:52 INFO  : Google drive root 'DIR': Waiting for transfers to finish
2018/02/18 12:20:52 ERROR : Attempt 3/3 failed with 1 errors
```

__________________________________________________________________________________

Hi,
I am trying to copy my gsuite's shared with me's all folders to my drive. however it get error. Anyone have succeed or know how to copy shared with me folders to my disk? 
Thansks

**Comment by ncw** [comment]
rclone copy --drive-shared-with-me aaa aaa:DIR

The error is saying that the local directory 'aaa' does not exists.

Did you mean 'aaa:'?

**Comment by vantobang** [comment]
Hi 
Thanks for replying 

aaa means remote google drive. So i want to copy aaa’s shared-folder contents to my aaa drive’s My drive.  

But it didn’t work.   

Thanks. 


&• Sent from my iPhone, please pardon typographic errors •&•

**Comment by ncw** [comment]
Sorry for the delay in replying [the rclone forum](https://forum.rclone.org/) is a better place for questions.

> aaa means remote google drive. So i want to copy aaa’s shared-folder contents to my aaa drive’s My drive.

If you want to refer to the google drive then you need to use the remote name with a colon.  So how about this?

    rclone copy --drive-shared-with-me aaa: aaa:DIR
