### ISSUE TITLE
[Feature Request] sync multiple sources to one remote drive

### ISSUE THREAD

**Issue by dinner95** [rclone/rclone#2082]
Example
rclone sync source1:/ source2:/ source3:/ destination:/

Problem:
If i want to Sync multiple sources to one destination i have to do it like this:

rclone sync source1:/ destination:/
rclone sync source2:/ destination:/
rclone sync source3:/ destination:/

If i start sync to source 2 after source 1 all stuff is gone because rclone cant find the stuff from source 1 on source 2. So sync isnt working.

I would like to see this feature and I think many others want it too.

**Comment by ncw** [comment]
I think this would be quite a complicated feature...

What is wrong with doing

```
rclone copy source1:/ destination:/
rclone copy source2:/ destination:/
rclone copy source3:/ destination:/
```

Or maybe

```
rclone sync source1:/ destination:/source1
rclone sync source2:/ destination:/source2
rclone sync source3:/ destination:/source3
```

**Comment by animosity22** [comment]
This was answered so closing out.
