### ISSUE TITLE
Rclone fails to connect with Onedrive Business Germany

### ISSUE THREAD

**Issue by msrv** [rclone/rclone#2107]
> What is your rclone version (eg output from `rclone -V`)

1.39, v1.39-189-g77f344a6

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10

> Which cloud storage system are you using? (eg Google Drive)

OneDrive for Business Germany

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

Add the rclone remote.

> A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

`2018/02/28 17:23:33 DEBUG : Starting auth server on 127.0.0.1:53682
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access
Waiting for code...
2018/02/28 17:23:50 DEBUG : Received request on auth server
2018/02/28 17:23:50 DEBUG : No code found on request
2018/02/28 17:23:50 DEBUG : Closing auth server
2018/02/28 17:23:50 Failed to configure token: failed to get code`

The browser (Edge or Firefox, does not matter) just shows a blank page with http://localhost:port, but no additional information. There is some other issue report here which is mostly similar but this is the main difference...

I am trying to use rclone with my Onedrive Business Germany Account (special Onedrive account, where the data resides in germany. Managed by Deutsche Telekom...i need this for legal reasons). 

I follow the steps to connect rclone and everything works until the final step, where the authorization is interrupted and fails.

Initially, my browser connects to: `https://login.microsoftonline.com/common/oauth2/authorize?access_type=offline&client_id=LONG NUMBER SHOWN HEREc&redirect_uri=http%3A%2F%2Flocalhost%3A53682%2F&resource=https%3A%2F%2Fapi.office.com%2Fdiscovery%2F&response_type=code&state=LONG NUMBER SHOWN HERE`

This is wrong, because my Onedrive listens to `https://login.microsoftonline.de/...`. During the login process, my browser successfully redirects to the .de domain but fails eventually with:

`https://login.microsoftonline.com/common/oauth2/authorize?access_type=offline&client_id=LONG NUMBER SHOWN HERE&redirect_uri=http%3A%2F%2Flocalhost%3A53682%2F&resource=https%3A%2F%2Fapi.office.com%2Fdiscovery%2F&response_type=code&state=LONG NUMBER SHOWN HERE`

This error happens only with rclone, as i am  able to successfully connect e.g. boxcryptor with my onedrive.

What could be the cause, any ideas?

**Comment by ncw** [comment]
Hmm, another onedrive puzzle... @olihey are you up for helping with this?

**Comment by olihey** [comment]
Hej, I don't think it's related to Germany, as I am located there as well and I have not such issues.

Overall it sounds a bit suspicious on what the browser is doing, and it seems it's returning an wrong code (or an error) to rclone.

Can you do me a favor? We have a new test implementation on how to talk to all Microsoft Services which is still in beta, well more on hold until I find more time :)
We have a beta version of rclone here: https://github.com/ncw/rclone/issues/2011#issuecomment-360537836 for Windows and Linux 64 Bit.
Can you try this version and see if you can authenticate?

**Comment by vikasrawal** [comment]
I am also having this problem. Onedrive for business in India.

**Comment by Cnly** [comment]
As rclone has gained support for regional OneDrive variants in #4963, German users should now be able to choose the `Microsoft Cloud Germany` option upon creating the remote, and I'll close this for now. Please report problems by opening new issues.

@vikasrawal OneDrive doesn't seem to have an Indian variant, so your problem may not be related to this issue. Please also open another issue with some more details if your problem is still there.

**Comment by sdbbs** [comment]
Just stumbled on this same problem: was trying to set up a OneDrive remote, and when this prompt came:

```
Option region.
Choose national cloud region for OneDrive.
Choose a number from below, or type in your own value of type string.
Press Enter for the default (global).
 1 / Microsoft Cloud Global
   \ (global)
 2 / Microsoft Cloud for US Government
   \ (us)
 3 / Microsoft Cloud Germany
   \ (de)
 4 / Azure and Office 365 operated by Vnet Group in China
   \ (cn)
region> de
```

... I answered `de` -> eventually, the `http://127.0.0.1:53682/auth?...` link wanted to redirect to `https://login.microsoftonline.de/common/oauth2/v2.0/authorize?...`, and here I got browser error "Your connection isn't private":

> This server couldn't prove that it's login.microsoftonline.de; its security certificate is from screamtest-ppe.eastus2.cloudapp.azure.com. This may be caused by a misconfiguration or an attacker intercepting your connection.

... and if click on "Continue to login.microsoftonline.de (unsafe)", then eventually it redirects to microsoft.com (where I cannot log in with an Office365 or Copilot365 or whatever they call it business account).

I eventually found a note this link login.microsoftonline.de was deprecated: https://github.com/Azure/azure-cli/issues/23775

> Thanks for reaching out to us and reporting this issue. Regarding the [Azure Germany](https://azure.microsoft.com/global-infrastructure/services/?regions=germany-north,germany-west-central&products=all&rar=true), Azure Germany is being **deprecated** in favor of standard nonsovereign Azure regions in Germany. Since August 2018, we have not been accepting new customers or deploying any new features and services into the original Microsoft Cloud Germany locations. Based on the evolution in customers' needs, we recently launched two new datacenter regions in Germany, offering customer data residency, full connectivity to Microsoft's global cloud network, as well as market competitive pricing.
> 
> More Info: [here](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/migrate/azure-best-practices/multiple-regions), [here](https://learn.microsoft.com/en-us/azure/germany/) and [here](https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/?regions=germany-north%2Cgermany-west-central&products=all&rar=true). Hope this helps.

So, if it is deprecated by Microsoft itself, maybe it's better that the option Microsoft Cloud Germany (de) is removed as an option from the regions prompt.

```
rclone.exe --version
rclone v1.69.0
- os/version: Microsoft Windows 10 Enterprise 22H2 22H2 (64 bit)
- os/kernel: 10.0.19045.5371 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.23.4
- go/linking: static
- go/tags: cmount
```

**Comment by ncw** [comment]
@sdbbs wrote
> So, if it is deprecated by Microsoft itself, maybe it's better that the option Microsoft Cloud Germany (de) is removed as an option from the regions prompt.

Did the Microsoft Cloud Global option work? And will it work for everyone who was in the `de` region previously?

**Comment by ncw** [comment]
@sdbbs I've marked the `de` region as deprecated and to try the global region first in the config help in 32e79a5c5c8eb57b7d82aa55d35f0fe0a09fc4b4 which should help with user confusion
