### ISSUE TITLE
Document that C14 storage is supported

### ISSUE THREAD

**Issue by alexanderkjeldaas** [rclone/rclone#2152]
#### What is the problem you are having with rclone?

C14 is a service from online.net, a major player in the industry. https://www.online.net/en/c14
The storage is very competivively priced http://gaul.org/object-store-comparison/

rclone should probably support it.

**Comment by ncw** [comment]
C14 is supported already with rclone using the sftp backend.

See #1080

This isn't mentioned on the website though and it probably should be!

**Comment by darthShadow** [comment]
@ncw Willing to do this. Should this be a separate page? Or should I add the details regarding fetching the C14 sftp details in the SFTP page itself?

**Comment by ncw** [comment]
> @ncw Willing to do this. Should this be a separate page? Or should I add the details regarding fetching the C14 sftp details in the SFTP page itself?

@darthShadow 

Apologies for the delay replying!  A separate paragraph in the SFTP backend is the normal way and a link from the providers list on the front page to that paragraph, eg `DigitalOcean Spaces` on the front page which links to `https://rclone.org/s3/#digitalocean-spaces`.  That would need a patch to `docs/content/about.md` and `docs/content/sftp,md`
