### ISSUE TITLE
webdav: NTLM authentication support

### ISSUE THREAD

**Issue by pyhedgehog** [rclone/rclone#2171]
#### What is the problem you are having with rclone?
* Can't connect to SharePoint using rclone.
* Can connect using Windows WebDav client (aka `net use`).
* Can connect using cadaver 0.23.3.
* Output of `curl -iX OPTIONS https://sharepoint/url` has `WWW-Authenticate: NTLM` (and no other auth variants).
* Checked that `curl -iX OPTIONS --ntlm -u user https://sharepoint/url` works (returns status 200).

#### What is your rclone version (eg output from `rclone -V`)
```
rclone v1.39
- os/arch: windows/amd64
- go version: go1.9.2
```

####  Which cloud storage system are you using? (eg Google Drive)
Sharepoint (aka OneDrive for Business - without 360 subscription).
Version headers:
```
X-AspNet-Version: 4.0.30319
MicrosoftSharePointTeamServices: 15.0.0.4927
```

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone lsd sharepoint:`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2018/03/22 17:20:54 DEBUG : Using config file from "C:\\Users\\user\\.config\\rclone\\rclone.conf"
2018/03/22 17:20:54 DEBUG : rclone: Version "v1.39" starting with parameters ["C:\\ProgramData\\chocolatey\\lib\\rclone.portable\\tools\\rclone-v1.39-windows-amd64\\rclone.exe" "lsd" "-vv" "sharepoint:"]
2018/03/22 17:20:54 INFO  : webdav root '': Modify window not supported
2018/03/22 17:20:54 DEBUG : Couldn't decode error response: EOF
2018/03/22 17:20:54 ERROR : : error listing: couldn't list files: 401 Unauthorized
2018/03/22 17:20:54 Failed to lsd: couldn't list files: 401 Unauthorized
```

**Comment by ncw** [comment]
You appear to be using the webdav backend - have you tried the onedrive backend instead? It supports onedrive for business and is fuller featured than the webdav backend.

**Comment by pyhedgehog** [comment]
That's why I've mentioned "without 360 subscription".
There are no place to enter url of onedrive.

**Comment by ncw** [comment]
Oh, I see, so you'd like to be able to use the webdav backend with NTLM authentication in order to access SharePoint.

It looks like [this library](https://github.com/Azure/go-ntlmssp) would implement it - do you agree?

That would need a username, password and URL for the authentication which sounds correct.

Fancy having a go?
