### ISSUE TITLE
Machine-parseable log output for rclone

### ISSUE THREAD

**Issue by turly** [rclone/rclone#2180]
Could we please have a machine-parseable log output for rclone?
My use case involved writing scripts to take certain actions after rclone successfully moved/copied/deleted/synced files or directories.  This is rather difficult to do right now, but a machine-parseable log would make this a lot easier.

Nick mentioned JSON output but csv would be nice too for quick-and-dirty shell scripts.

Origins:  https://forum.rclone.org/t/rclone-invoke-user-script-command-after-each-file-copy-move-delete/5149/7

**Comment by kubatasiemski** [comment]
Hi,
I would like to work with this issue.

I don't know how other users uses rclone but I think it mostly is being used in terminal or in something like that.
In my opinion, output like csv should be default.
Exactly, my proposition is:
>copy "source" "dest"
move "source" "dest"
delete "dest"

" is not allowed in path and scripts can catch path with spaces as one argument so this should works perfectly with any kind of path also when contain spaces.

**Comment by kubatasiemski** [comment]
According to issue #881:
I think it's worth discussing these two issues together.

**Comment by ncw** [comment]
@kubatasiemski glad you'd like to help with this :-)

I think the first thing is to define a go struct which has everything we'd like to see in a log.  This can then be written as CSV or JSON or whatever.

Something like

```go
struct {
    Time time.Time
    Level fs.LogLevel // INFO, DEBUG etc
    Action string // copy, move, delete, etc, blank for a normal log message
    Object string // source object (may be blank)
    Dest string // optional
    Message string // what the log would normally say
}
```

This should include all the log messages so anything calling rclone's log framework.

We'd need some special logs to add some of the other info.

It might be nice to have a source reference too - that is easy to make - eg `backend/s3/s3.go:155`

Separate actions for start/end would be interesting too as per #881 

rclone doesn't use SIGINFO, infact I never heard of it before!  Hmm it doesn't seem to exist on my linux box

```
$ kill -l | grep INFO
$
```

Anyway I like the idea of a signal to print transfer stats that would be very useful.  I suggest you make a new issue about it.

**Comment by daniel-loader** [comment]
http://man7.org/linux/man-pages/man7/signal.7.html

> SIGINFO 29,-,- A synonym for SIGPWR
> …
> (Signal 29 is SIGINFO / SIGPWR on an alpha but SIGLOST on a sparc.)
> …
> SIGPWR (which is not specified in POSIX.1-2001) is typically ignored by default on those other UNIX systems where it appears.


That said, seems BSD uses siginfo! MacOSX seems to allow `kill -INFO` and ctrl+t in the terminal to force an update. Seems to be platform specific, welcome any corrections though.

**Comment by ncw** [comment]
Rclone has the

      --use-json-log   Use json log format

flag now which makes machine parseable logs.

Whether the logs have enough info in is probably something for another issue.
