### ISSUE TITLE
backblaze and default b2-chunk-size settings

### ISSUE THREAD

**Issue by jimtalksdata** [rclone/rclone#2185]
HI,

This in in reference to the b2-chunk-size setting discussed in https://github.com/ncw/rclone/issues/456

I was trying to debug a strange go issue that turned out to be an out-of-memory error, and only later found out that the default chunk size is 96M, even though I'm syncing a folder tree with lots of small files (no files close to that size). Unfortunately, that also means that each b2 thread (I was using --transfers 32) takes almost 100mb of memory. 

If there's no need to chunk (under b2-upload-cutoff), can it default to a smaller chunk value (e.g. buffer-size or something)? Or can you not allocate memory that way?

**Comment by ncw** [comment]
It does [say this in the docs](https://rclone.org/b2/#transfers), maybe it could be clearer?

96MB used to be the minimum size for a chunk, but b2 changed it so that it is now 5MB.  I think 96MB is still the recommended chunk size which is why I haven't changed the default.

(Note B2 counts MB = 1,000,000 bytes whereas rclone counts MB as 1,048,576 bytes)

> If there's no need to chunk (under b2-upload-cutoff), can it default to a smaller chunk value (e.g. buffer-size or something)? Or can you not allocate memory that way?

If there is no need to chunk, then rclone won't buffer the file into memory.

**Comment by jimhsu** [comment]
> If there is no need to chunk, then rclone won't buffer the file into memory.

If this is the case, why does system memory use peg out at 96M * threads regardless of whether the file is over or under the chunk size? This is syncing a large file tree to a new b2 location where most of the files are a few kB.

**Comment by jimhsu** [comment]
> If there is no need to chunk, then rclone won't buffer the file into memory.

![image](https://user-images.githubusercontent.com/56103/38068244-bc83b9a0-32d5-11e8-9f33-6ae26252007f.png)

Here's the issue (output from htop). Should be self-explanatory. In both cases, I'm syncing a file tree with exclusively small files (most < 4kb) to a new crypted b2 location.

**Comment by ncw** [comment]
Even a single large file (above 200MB) to upload will have been enough for rclone to allocate the memory.  It uploads large files by chunking them up and uploading the parts in parallel (which is what backblaze recommend).

Perhaps you could try a transfer with `--b2-upload-cutoff` set bigger than your biggest file?
