### ISSUE TITLE
Minimize API calls when syncing to S3

### ISSUE THREAD

**Issue by ipmb** [rclone/rclone#2199]
Continuing a discussion with @ncw from the forum at https://forum.rclone.org/t/reduce-api-requests-for-sync/4757/4

#### What is the problem you are having with rclone?

It makes a bunch of `HeadObject` calls when syncing to S3. Performing a similar sync with `awscli` does not require the `HeadObject` API calls. The only way to remove these is to use `--size-only` which is not ideal.

#### Expected Behavior

I understand storing the "real" modification date in the S3 metadata, but I don't think it is necessary to check it to perform a sync. My understanding of the **current process** is:

1. For each local file, check if it exists on S3. If so...
2. Call `HeadObject` to get the last modified date of the file.
3. If local last modified date is greater than the last modified date stored in S3 metadata, the file needs to be synced.

I believe this **proposed process** would be sufficient:

1. For each local file, check if it exists on S3. If so...
2. If the local last modified date is greater than the date it was uploaded to S3, the file needs to be synced.

This does not preclude storing the "true" last modified date in metadata, it just doesn't require checking it to see if the file is dirty.

**Comment by ncw** [comment]
(Adapted from what I wrote on the forum)

Rclone has part of this already

    -u, --update                              Skip files that are newer on the destination.

But that will read the modification time from the metadata.

If rclone had a flag - say `--s3-use-server-modtime` or something like that then you could use that with `-u` to get the effect you wanted.  The flag would then use `LastModified` from the [ListBucket API](https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html).

It could possibly be a global flag say `--use-server-modtime` as this could apply to several backends s3 and swift are two examples which come to mind immediately.

**Comment by ncw** [comment]
@ipmb do you fancy having a go at this?

I think it would just be a matter of adding a new flag, then not calling `readMetaData` in the [ModTime method](https://github.com/ncw/rclone/blob/master/backend/s3/s3.go#L942)

Plus some docs on the new syncing method...

**Comment by ivandeex** [comment]
Closing after 3 years of inactivity
