### ISSUE TITLE
mount with cache and vfs-cache-mode writes not working

### ISSUE THREAD

**Issue by jkoopmann** [rclone/rclone#2210]
#### What is the problem you are having with rclone?

https://forum.rclone.org/t/cache-workers-and-plex-integration/5258

3 issues that might be interconnected:

1) Once I mount with cache-tmp-upload-path and try to write to the mount it results in immediate upload (instead of the waiting-time). After that the file is not accessible:

2018/04/05 15:36:40 INFO  : GDRIVECACHE: Upload Temp FS: /root/rclonewritecache
2018/04/05 15:36:40 INFO  : Encrypted drive 'PLEXDRIVE:': Modify window is 1ms
2018/04/05 15:37:38 INFO  : tpjobe1f0erqtu34e1od67us/akgompafdqpm7t5n8p2esks0: put: uploaded in temp fs
2018/04/05 15:37:38 INFO  : tpjobe1f0erqtu34e1od67us/akgompafdqpm7t5n8p2esks0: put: queued for upload
2018/04/05 15:37:38 INFO  : tpjobe1f0erqtu34e1od67us: put: cache expired
2018/04/05 15:37:38 INFO  : Video/test.txt: Copied (new)
2018/04/05 15:37:41 ERROR : Video/test.txt: WriteFileHandle: Truncate: Can't change size without --vfs-cache-mode >= writes
2018/04/05 15:38:19 ERROR : Video/test.txt: ReadFileHandle.Read error: low level retry 1/10: unexpected EOF
2018/04/05 15:38:20 ERROR : Video/test.txt: ReadFileHandle.Read error: low level retry 2/10: unexpected EOF
2018/04/05 15:38:22 ERROR : Video/test.txt: ReadFileHandle.Read error: low level retry 3/10: unexpected EOF
2018/04/05 15:38:23 ERROR : Video/test.txt: ReadFileHandle.Read error: low level retry 4/10: unexpected EOF
2018/04/05 15:38:24 ERROR : Video/test.txt: ReadFileHandle.Read error: low level retry 5/10: unexpected EOF
2018/04/05 15:38:25 ERROR : Video/test.txt: ReadFileHandle.Read error: low level retry 6/10: unexpected EOF
2018/04/05 15:38:26 ERROR : Video/test.txt: ReadFileHandle.Read error: low level retry 7/10: unexpected EOF
2018/04/05 15:38:27 ERROR : Video/test.txt: ReadFileHandle.Read error: low level retry 8/10: unexpected EOF
2018/04/05 15:38:28 ERROR : Video/test.txt: ReadFileHandle.Read error: low level retry 9/10: unexpected EOF
2018/04/05 15:38:29 ERROR : Video/test.txt: ReadFileHandle.Read error: low level retry 10/10: unexpected EOF
2018/04/05 15:38:30 ERROR : Video/test.txt: ReadFileHandle.Read error: unexpected EOF
2018/04/05 15:38:30 ERROR : Video/test.txt: WriteFileHandle: Truncate: Can't change size without --vfs-cache-mode >= writes

As you can see the file was saved 15:37:38 and the cache expired immediately despite:

2018/04/05 15:36:39 INFO  : GDRIVECACHE: Upload Temp Rest Time: 1h0m0s
2018/04/05 15:36:39 INFO  : GDRIVECACHE: Upload Temp FS: /root/rclonewritecache

2) The file is then not accessible maybe also because of the WriteFileHandle: Truncate Problem. ncw pointed out I need vfs-cache-mode=writes which I then turned on which led to problem 3)

3) I get the Truncate stuff (without vfs-cache-mode) even when only plex is accessing it in read-only. The rclone mount is done on the base system. Plex is running in a jail. The mounted drive is put into the jail readonly. Plex from within the jail CANNOT write to the mount. However once I start plex and it is trying to access files I get the Truncate errors. After turning on the vfs-cache-mode the errors are gone but the access schema leads to big file changes/uploads because something really is trying to truncate the mkv files. Again: plex can't be the reason. Either it is fuse, freebsd itself or rclone. Needless to say that things go berserk with this setup so I had to revert to rclone mount with --read-only which has less functionality but is working.

#### What is your rclone version (eg output from `rclone -V`)

rclone v1.40-040-g6e11a25dβ
- os/arch: freebsd/amd64
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

FreeBSD 11.1

####  Which cloud storage system are you using? (eg Google Drive)

GDRIVE

**Comment by ncw** [comment]
I think we need to simplify things a bit in order to find out what is going on here.

Can you try a test with mount pointing to the remote directly (without cache and crypt) and see if that has the same problems?

**Comment by jkoopmann** [comment]
Not without crypt I am afraid as the entire library is only available encrypted. But direct without cache I could try. with vfs-cache-write I suppose? Might take me until next week to give it a try though. I am a bit busy at the moment. 

Is there a way to find out what exactly is trying to truncate/write to the files?

**Comment by ncw** [comment]
>  But direct without cache I could try. with vfs-cache-write I suppose?

That would be very helpful - thanks

**Comment by jkoopmann** [comment]
Sorry. Was not able to try so far and will be quite busy the next three weeks. I hope I can continue debugging then!

**Comment by animosity22** [comment]
This seems to be a stale issue. If you still have a question, please feel free to ask in the forums.

**Comment by 13681249878** [comment]
rclone有无缓存和缓存挂载，但是我在windows上使用无缓存挂载，然后拷贝文件的时候，就一直报错：WriteFileHandle: Truncate: Can't change size without --vfs-cache-mode >writes，挂载命令如下： rclone mount admin1:/ bucket Q:

**Comment by 13681249878** [comment]
rclone has cache and cache mount, but I use cacheless mount on windows, and then when I copy files, I keep reporting an error: WriteFileHandle: Truncate: Can't change size without --vfs-cache-mode >writes, The mount command is as follows: rclone mount admin1:/ bucket Q:
