### ISSUE TITLE
multiple response.WriteHeader errors while connecting to webdav serve from nplayer on ios

### ISSUE THREAD

**Issue by tvvid** [rclone/rclone#2223]
build current github source code on circleci, artifacts uploaded to jailbroken ipad,
rclone serve webdav remote:

In this app https://itunes.apple.com/us/app/nplayer-plus/id539397400?mt=8
added connection to this webdav serve, and while small folders are opening fine,
when there is lot of files, rclone is outputing in console such message:

> http: multiple response.WriteHeader

and nplayer show message: Timeout

**Comment by ncw** [comment]
Can you post the whole log with `-vv` please?

**Comment by ncw** [comment]
BTW `http: multiple response.WriteHeader` is likely some incorrect error handling in rclone.

**Comment by tvvid** [comment]
ok, i will post later today full log.
In normal nginx, webdav from nplayer to nginx works fine,
but when rclone is serving files through webdav to nplayer there is this error.

**Comment by tvvid** [comment]
[log.txt](https://github.com/ncw/rclone/files/1890181/log.txt)

and nplayer says that Timeout happened, no files do display

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.d
