### ISSUE TITLE
Failed to create filesystem for "mydrive:/" in windows 7 using remote host configuration

### ISSUE THREAD

**Issue by him4nsh** [rclone/rclone#2225]
Hii
I am getting an issue in uploading the data to drive , showing the error **dial tcp: lookup login.live.com: no such host** , i have setup everything  and it was working smoothly . Suddenly it starts showing this error as follows.

2018/04/07 09:54:10 Failed to create file system for "mydrive:/": failed to get root: Get https://api.onedrive.com/v1.0/drive/root:/: Post https://login.live.com/oauth20_token.srf: dial tcp: lookup login.live.com: no such host

Same for other storages also ...

**Comment by ncw** [comment]
That tends to indicate that your DNS resolution has broken for some reason... Can you check your DNS resolver?

**Comment by animosity22** [comment]
DNS issue. Closing out.
