### ISSUE TITLE
vfs: implement locking or document that you shouldn't run multiple vfs caches on the same directory

### ISSUE THREAD

**Issue by Nodens-** [rclone/rclone#2227]
#### What is the problem you are having with rclone?
Upload failing at the end of the file when copying or moving with mc.
This started happening with no update to rclone so I am guessing it got triggered by a Fedora package update. It is reproducible 100% even on latest commit.

gocryptfs is running on top of rclone vfs.

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.40-DEV
- os/arch: linux/amd64
- go version: go1.9.4
commit 42f0963bf907daacb6cb718ef14a64a591fab3a0 (HEAD -> master, origin/master, origin/HEAD)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Fedora 27 x64

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
ExecStart=/usr/local/bin/rclone mount -vv --stats 5m --attr-timeout 100ms --allow-other --default-permissions --vfs-cache-mode writes --low-level-retries=200 --bwlimit=250K --log-file=/var/log/rclone/rclone.log gd: /Drive/.remote

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
[rclone.zip](https://github.com/ncw/rclone/files/1887979/rclone.zip)

**Comment by ncw** [comment]
I made an edited highlights of the second part of the log where DEBUG was turned on.

What appeared to have happened is that `/home/user/.cache/rclone/vfs/gd/Wintermute/DIR1/DIR2/DIR3/FILE1` got deleted some time while the file was being uploaded.

I don't think it was rclone - it should have made a DEBUG message if it deleted the file.

What kind of file system is `/home/user/.cache` stored on? Could some other process be deleting files from within there? Maybe a new thing in Fedora?

It would be easy to make the [copy not exit in a fatal way there](https://github.com/ncw/rclone/blob/master/fs/operations/operations.go#L340) as not being able to read the checksum doesn't need to be a fatal error at that point. Do you think I should do that?

```
2018/04/08 15:42:35 DEBUG : Wintermute/DIR1/DIR2/DIR3/: Lookup: name="FILE1"
2018/04/08 15:42:35 DEBUG : Wintermute/DIR1/DIR2/DIR3/: >Lookup: node=<nil>, err=no such file or directory
2018/04/08 15:42:35 DEBUG : Wintermute/DIR1/DIR2/DIR3/: Lookup: name="FILE1"
2018/04/08 15:42:35 DEBUG : Wintermute/DIR1/DIR2/DIR3/: >Lookup: node=<nil>, err=no such file or directory
2018/04/08 15:42:35 DEBUG : Wintermute/DIR1/DIR2/DIR3/: Create: name="FILE1"
2018/04/08 15:42:35 DEBUG : Wintermute/DIR1/DIR2/DIR3/FILE1: Open: flags=O_RDWR|O_CREATE|O_EXCL
2018/04/08 15:42:35 DEBUG : Wintermute/DIR1/DIR2/DIR3/FILE1(0xc4206bc240): Opening cached copy with flags=O_RDWR|O_CREATE|O_EXCL
2018/04/08 15:42:35 DEBUG : Wintermute/DIR1/DIR2/DIR3/FILE1: >Open: fd=Wintermute/DIR1/DIR2/DIR3/FILE1 (rw), err=<nil>
2018/04/08 15:42:35 DEBUG : Wintermute/DIR1/DIR2/DIR3/: >Create: node=Wintermute/DIR1/DIR2/DIR3/FILE1, handle=&{Wintermute/DIR1/DIR2/DIR3/FILE1 (rw)}, err=<nil>
2018/04/08 15:42:35 DEBUG : Wintermute/DIR1/DIR2/DIR3/FILE1: Attr: 
2018/04/08 15:42:35 DEBUG : Wintermute/DIR1/DIR2/DIR3/FILE1: >Attr: a=valid=100ms ino=0 size=0 mode=-rw-r--r--, err=<nil>
2018/04/08 15:42:35 DEBUG : Wintermute/DIR1/DIR2/DIR3/: Attr: 
2018/04/08 15:42:35 DEBUG : Wintermute/DIR1/DIR2/DIR3/: >Attr: attr=valid=100ms ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/04/08 15:42:35 DEBUG : &{Wintermute/DIR1/DIR2/DIR3/FILE1 (rw)}: Read: len=4096, offset=0
2018/04/08 15:42:35 DEBUG : &{Wintermute/DIR1/DIR2/DIR3/FILE1 (rw)}: >Read: read=0, err=<nil>
2018/04/08 15:42:46 DEBUG : Wintermute/DIR1/DIR2/DIR3/FILE1: Attr: 
2018/04/08 15:42:46 DEBUG : Wintermute/DIR1/DIR2/DIR3/FILE1: >Attr: a=valid=100ms ino=0 size=1282123794 mode=-rw-r--r--, err=<nil>
2018/04/08 15:42:46 DEBUG : &{Wintermute/DIR1/DIR2/DIR3/FILE1 (rw)}: Read: len=4096, offset=1282179072
2018/04/08 15:42:46 DEBUG : &{Wintermute/DIR1/DIR2/DIR3/FILE1 (rw)}: >Read: read=0, err=<nil>
2018/04/08 15:42:46 DEBUG : &{Wintermute/DIR1/DIR2/DIR3/FILE1 (rw)}: Flush: 
2018/04/08 15:42:46 DEBUG : Wintermute/DIR1/DIR2/DIR3/FILE1(0xc4206bc240): close: 
2018/04/08 15:42:46 DEBUG : Wintermute/DIR1/DIR2/DIR3/FILE1: Couldn't find file - need to transfer
2018/04/08 15:42:57 DEBUG : Wintermute/DIR1/DIR2/DIR3/FILE1: updateTime: setting atime to 2018-04-08 15:42:46.750519173 +0300 EEST
2018/04/08 15:42:59 DEBUG : Wintermute/DIR1/DIR2/DIR3: forgetting directory cache
2018/04/08 15:42:59 DEBUG : Wintermute/DIR1/DIR2/DIR3: forgetting directory cache
 *   ...FILE1:  5% /1.194G, 249.959k/s, 1h19m14s
 *   ...FILE1: 11% /1.194G, 249.932k/s, 1h14m15s
 *   ...FILE1: 17% /1.194G, 249.934k/s, 1h9m14s
 *   ...FILE1: 23% /1.194G, 249.935k/s, 1h4m14s
 *   ...FILE1: 29% /1.194G, 249.932k/s, 59m14s
 *   ...FILE1: 35% /1.194G, 249.933k/s, 54m14s
 *   ...FILE1: 41% /1.194G, 249.932k/s, 49m14s
 *   ...FILE1: 47% /1.194G, 249.933k/s, 44m14s
 *   ...FILE1: 53% /1.194G, 249.940k/s, 39m14s
 *   ...FILE1: 58% /1.194G, 249.945k/s, 34m14s
 *   ...FILE1: 64% /1.194G, 249.932k/s, 29m14s
2018/04/08 16:37:57 DEBUG : Wintermute/DIR1/DIR2/udmglk-R81xHKYx8sTVp7wS67m5D5sDYITPkBh5a3Vma7l32DgKMDIXr1vnli9lX: Removed from cache
 *   ...FILE1: 70% /1.194G, 249.934k/s, 24m14s
2018/04/08 16:42:57 DEBUG : Wintermute/DIR1/DIR2/DIR3/gocryptfs.diriv: Removed from cache
 *   ...FILE1: 76% /1.194G, 249.934k/s, 19m14s
 *   ...FILE1: 82% /1.194G, 249.933k/s, 14m14s
 *   ...FILE1: 88% /1.194G, 249.934k/s, 9m14s
 *   ...FILE1: 94% /1.194G, 250.062k/s, 4m13s
2018/04/08 17:06:13 ERROR : Wintermute/DIR1/DIR2/DIR3/FILE1: Failed to read src hash: hash: failed to stat: lstat /home/user/.cache/rclone/vfs/gd/Wintermute/DIR1/DIR2/DIR3/FILE1: no such file or directory
2018/04/08 17:06:13 INFO  : Wintermute/DIR1/DIR2/DIR3/FILE1: Copied (new)
2018/04/08 17:06:13 ERROR : Wintermute/DIR1/DIR2/DIR3/FILE1(0xc4206bc240): failed to transfer file from cache to remote: hash: failed to stat: lstat /home/user/.cache/rclone/vfs/gd/Wintermute/DIR1/DIR2/DIR3/FILE1: no such file or directory
2018/04/08 17:06:13 DEBUG : Wintermute/DIR1/DIR2/DIR3/FILE1(0xc4206bc240): >close: err=failed to transfer file from cache to remote: hash: failed to stat: lstat /home/user/.cache/rclone/vfs/gd/Wintermute/DIR1/DIR2/DIR3/FILE1: no such file or directory
2018/04/08 17:06:13 ERROR : Wintermute/DIR1/DIR2/DIR3/FILE1(0xc4206bc240): RWFileHandle.Flush error: failed to transfer file from cache to remote: hash: failed to stat: lstat /home/user/.cache/rclone/vfs/gd/Wintermute/DIR1/DIR2/DIR3/FILE1: no such file or directory
2018/04/08 17:06:13 DEBUG : &{Wintermute/DIR1/DIR2/DIR3/FILE1 (rw)}: >Flush: err=failed to transfer file from cache to remote: hash: failed to stat: lstat /home/user/.cache/rclone/vfs/gd/Wintermute/DIR1/DIR2/DIR3/FILE1: no such file or directory
2018/04/08 17:06:13 DEBUG : &{Wintermute/DIR1/DIR2/DIR3/FILE1 (rw)}: Flush: 
2018/04/08 17:06:13 DEBUG : Wintermute/DIR1/DIR2/DIR3/FILE1(0xc4206bc240): RWFileHandle.Flush nothing to do
2018/04/08 17:06:13 DEBUG : &{Wintermute/DIR1/DIR2/DIR3/FILE1 (rw)}: >Flush: err=<nil>
2018/04/08 17:06:13 DEBUG : &{Wintermute/DIR1/DIR2/DIR3/FILE1 (rw)}: Release: 
2018/04/08 17:06:13 DEBUG : Wintermute/DIR1/DIR2/DIR3/FILE1(0xc4206bc240): RWFileHandle.Release nothing to do
2018/04/08 17:06:13 DEBUG : &{Wintermute/DIR1/DIR2/DIR3/FILE1 (rw)}: >Release: err=<nil>
2018/04/08 17:07:01 DEBUG : Wintermute/DIR1/DIR2/DIR3: forgetting directory cache
```

**Comment by Nodens-** [comment]
FS is nothing exotic. Plain ext4 on ssd drive. Its not even software RAIDed heh.

As far as something in Fedora deleting the cache folder it's quite possible. The installation is the Server Fedora stub but it has a LOT of packages installed as it's used as web server, mx server, imap server, samba server, private gitlab server, proxy of a lot of internal services via apache to different subdomains and C++ building environment for my linux C projects. It's mostly daemon packages and software development related packages and libs.

I will try to identify what process deletes the file with `auditctl` and get back to you. Worst case scenario if it's not rclone doing it and it's something in Fedora that can't easily be fixed, I can change the cache directory target for rclone to something private that won't be affected by fedora packages.

Regarding the fatality of the error, I'm not sure. While the files seem properly uploaded (every single case I checked), wouldn't downgrading this error to a warning make it impossible for rclone to detect a corrupted upload unless someone actively checks the logs for this and manually verifies the files? Is that not the hash used for upload reliability validation (this is what the code comment seems to suggest)? Or is that being done chunk by chunk? I'm not familiar with the drive API.

PS I should really get myself to learn golang at some point so I can properly read the code heh.

PSS On this system there is a second rclone vfs process running by the same user account, operating on the same remote but with different mount point. This is a hackish way I came up with to get around the fact that there is no upload-only bandwidth limit. This second mount point runs with no bandwidth limit and is only used for reading from the remote. Is it possible that the second rclone process is clearing .cache as I added this along the same time with latest package updates? I will turn on its logging to see if it's anything there anyhow.

**Comment by Nodens-** [comment]
Seems like my hunch was right.  Second process seems to be cleaning the cache because there's no IPC and it doesn't know it belongs to the other process. Can this be solved via locking?

This is from the second process log:

>2018/04/10 04:50:35 DEBUG : Cleaning the cache
2018/04/10 04:50:35 DEBUG : Wintermute/n6_H7xrGF1Tq2k88_2tRWw/DOygaY-iXhKht_06SPydL9dfqhLyFQ0vMZgIUxtVbiB8SxKyTyMi7ExGigeFemJU/fc_gGiHfdqfHw6pj0wEwainiFPVPc8shd4alYd-iocJW26BRyvkaWntq-eeVKxBswxMRb6sQGjq1WqGaOusJDg: Removed from cache
2018/04/10 04:50:35 DEBUG : Wintermute/n6_H7xrGF1Tq2k88_2tRWw/DOygaY-iXhKht_06SPydL9dfqhLyFQ0vMZgIUxtVbiB8SxKyTyMi7ExGigeFemJU/gocryptfs.diriv: Removed from cache
2018/04/10 04:50:35 DEBUG : Wintermute/n6_H7xrGF1Tq2k88_2tRWw/DOygaY-iXhKht_06SPydL9dfqhLyFQ0vMZgIUxtVbiB8SxKyTyMi7ExGigeFemJU: Removed empty directory
2018/04/10 04:50:35 DEBUG : Wintermute/n6_H7xrGF1Tq2k88_2tRWw: Removed empty directory
2018/04/10 04:50:35 DEBUG : Wintermute: Removed empty directory
2018/04/10 04:50:35 DEBUG : : Removed empty directory

**Comment by ncw** [comment]
@Nodens- Ah ha - great debugging - thank you :-)

> Seems like my hunch was right. Second process seems to be cleaning the cache because there's no IPC and it doesn't know it belongs to the other process. Can this be solved via locking?

Locking is annoyingly platform dependent, but it is possible, however.  Here is a [flock library](https://github.com/theckman/go-flock) I found.

> By the way, the second process is running with no cache switches whatsoever. Basically just --allow-other and --default-permissions

A solution for this particular issue would be not to run the cache cleaner process at all if we have `--vfs-cache-mode off` (the default).  I'm not sure why we run the cache cleaner then anyway...

I should also write in the docs that if you shouldn't share the vfs cache between processes.   Hmm, that is something I could potentially enforce with a lock file...

What do you think about those ideas?

> Regarding the fatality of the error, I'm not sure. While the files seem properly uploaded (every single case I checked), wouldn't downgrading this error to a warning make it impossible for rclone to detect a corrupted upload unless someone actively checks the logs for this and manually verifies the files?

Yes that is what the check does - verify the integrity of the source file.  What I'm proposing is if the source checksum fails to be read (as it was in this case) which is a very rare occurrence, we just skip the integrity check rather than failing the upload. There will still be an ERROR in the log though.

> PS I should really get myself to learn golang at some point so I can properly read the code heh.

:-) Go is quite a simple language. C level rather than C++ level and if you know C you'll find it easy to pick up (except for the reversed type definitions!).  I recommend [the go tour](https://tour.golang.org/) if you like diving in headfirst!

**Comment by Nodens-** [comment]
> Locking is annoyingly platform dependent, but it is possible, however. Here is a flock library I found.

Indeed, platform differences are annoying. I keep forgetting rclone is supported on Windows as well :)

> What do you think about those ideas?

Both sound good. If an rclone process is not using cache it shouldn't tamper with the cache directory at all. If nothing else, it's a waste of cycles.
I also think at this point rclone could benefit from IPC implementation as that would allow a lot of things (eg shared cache directories, global bandwidth controls for all processes etc)

>Yes that is what the check does - verify the integrity of the source file. What I'm proposing is if the source checksum fails to be read (as it was in this case) which is a very rare occurrence, we just skip the integrity check rather than failing the upload. There will still be an ERROR in the log though.

Yes that is my problem with that approach. Unless you actively check logs (which is tedious when you maintain a lot of systems running it and some with multiple processes) it is possible that corrupted files will just go through and you won't notice. Even having a Logwatch rule for it, I will see it in the daily report but there's a 24 hour window where this scenario can happen:
1) Automated move of backup to cheap cloud storage
2) Upload is corrupted but the error is not fatal
3) Catastrophic failure of original data
4) Realization that uploaded backup is bad
5) Logwatch mail shows checksum was not available but it's now too late.

I may be a bit paranoid as this is an edge case but what I mostly use gsuite for is cheap storage of backups and snapshots. I'm pushing an average of 2TB total per month from 4 different servers. I'm a small time indie software developer taking mostly consigned work from clients (some huge, some small but the pay is always bad heh). This is the only way I can keep proper backups at my current budget :)
If there's even a possibility of something being corrupted, I want to know the moment it happens so I can verify it manually. So my vote is that any error that could pertain to data corruption to be kept fatal even if it's an edge case.

> :-) Go is quite a simple language. C level rather than C++ level and if you know C you'll find it easy to pick up (except for the reversed type definitions!). I recommend the go tour if you like diving in headfirst!

I'm mainly a C/C++ and asm person. I've read a few articles about Go and I find it interesting plus there are a lot of great projects written with it such as rclone and gocryptfs that I use extensively. I may as well contribute back a bit at some point :) I know the syntax is similar and I just looked up Go type definitions haha! That will take me ages to get used to..especially on function declarations hahaha. I pick up languages very fast as long as there's adequate documentation on "quirks" etc. Thanks for the link, I will check it out!

**Comment by ncw** [comment]
I've stopped the VFS cache running if `--vfs-cache-mode` is `off`

This should fix your immediate problem :-)

https://beta.rclone.org/v1.40-085-g2b7957cc/ (uploaded in 15-30 mins)

I'm going to leave this issue open for a bit to thing about whether to do locking or documentation on running multiple VFS caches at once.

> I also think at this point rclone could benefit from IPC implementation as that would allow a lot of things (eg shared cache directories, global bandwidth controls for all processes etc)

Hmm, that would be nice!  Such things a really difficult to do cross platform in my experience.

I take your point about error checking - I'll leave it how it is so that you'll get an definite error rather than just a log if the above issue happens again.

**Comment by ivandeex** [comment]
@Nodens- This problem is reported against obsolete rclone version. Can you reproduce it with rclone 1.54?

**Comment by Nodens-** [comment]
@ivandeex This is almost 3 years old. I have not been able to reproduce this since https://github.com/rclone/rclone/commit/2b7957cc74dcbbdab8e5b600fa6994207f32dbd6 I believe. For all my use-case purposes I had considered this solved. By reading the thread again, it is my understanding that @ncw left it open for the reason given in https://github.com/rclone/rclone/issues/2227#issuecomment-381669435

**Comment by ivandeex** [comment]
@Nodens-  I see. Thank you for replying.

@ncw  Do you still need https://github.com/rclone/rclone/issues/2227#issuecomment-381669435 as a reminder?

**Comment by ncw** [comment]
I've added a bit of documentation for this now which will close the issue when I push it :-)
