### ISSUE TITLE
Unable to expire cached folder

### ISSUE THREAD

**Issue by PiscisSwimeatus** [rclone/rclone#2238]
What is the problem you are having with rclone?
Unable to expire folder "/Unsorted/RadarrDrone/Unbroken (2014)" which only exists in the cache;
no referance to this folder in google remove, temp-upload or chunk folders.

What is your rclone version (eg output from rclone -V)
rclone v1.40-055-gaef1f16a-go-versionβ

os/arch: linux/amd64
go version: go1.10.1
Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04

Which cloud storage system are you using? (eg Google Drive)
Google Drive

The command you were trying to run (eg rclone copy /tmp remote:tmp)
A log from the command with the -vv flag (eg output from rclone -vv copy /tmp remote:tmp)

**Mount
/usr/bin/rclone mount CacheG3: /media/Cloud/ \
--cache-chunk-path="/media/Disk1/Rclone/Cache" \
--cache-chunk-size=32M \
--cache-db-path="/media/RAM" \
--cache-info-age=8760h \
--cache-tmp-upload-path="/media/Disk1/Rclone/Upload" \
--cache-tmp-wait-time=12h \
--cache-total-chunk-size=1024G \
--cache-workers=16 \
--drive-chunk-size=32M \
--drive-upload-cutoff=128M \
--drive-use-trash=false \
--log-level=INFO \
--attr-timeout=1m \
--retries=2 \
--low-level-retries=2 \
--rc

**Trying to expire it:**

ls -l "/media/Cloud/Unsorted/RadarrDrone"
drwxr-xr-x 1 aj aj 0 Apr 12 12:49 Unbroken (2014)

rclone rc cache/expire remote=/Unsorted/RadarrDrone withData=true
{
        "message": "cached directory cleared: /Unsorted/RadarrDrone",
        "status": "ok"
}

ls -l "/media/Cloud/Unsorted/RadarrDrone"
drwxr-xr-x 1 aj aj 0 Apr 12 12:49 Unbroken (2014)

**No referance to this anywhere:**

ls -l "/media/Disk1/Rclone/Cache/CacheG3/Unsorted/RadarrDrone"

ls -l "/media/Disk1/Rclone/Upload/Unsorted/RadarrDrone"
drwxr-xr-x 2 aj aj 4096 Apr 12 07:24 Amen.2002.1080p.BluRay.H264.AAC-RARBG
drwxr-xr-x 2 aj aj 4096 Apr 12 07:33 Better.Off.Dead.1985.1080p.BluRay.H264.AAC-RARBG
drwxr-xr-x 2 aj aj 4096 Apr 12 07:35 Blood.Road.2017.1080p.BluRay.H264.AAC-RARBG
drwxr-xr-x 2 aj aj 4096 Apr 12 07:38 Cover Versions (2018) [WEBRip] [1080p] [YTS.AM]
drwxr-xr-x 2 aj aj 4096 Apr 12 07:41 House.on.Haunted.Hill.1959.1080p.BluRay.H264.AAC-RARBG
drwxr-xr-x 2 aj aj 4096 Apr 12 07:44 Return.to.Me.2000.1080p.BluRay.H264.AAC-RARBG
drwxr-xr-x 2 aj aj 4096 Apr 12 07:44 Song.of.the.Sea.2014.1080p.BluRay.H264.AAC-RARBG
drwxr-xr-x 2 aj aj 4096 Apr 12 07:57 Stigmata.1999.1080p.BluRay.H264.AAC-RARBG
drwxr-xr-x 2 aj aj 4096 Apr 12 07:45 The.Corruptor.1999.1080p.BluRay.H264.AAC-RARBG
drwxr-xr-x 2 aj aj 4096 Apr 12 07:45 The.Last.Seduction.1994.1080p.BluRay.H264.AAC-RARBG
drwxr-xr-x 2 aj aj 4096 Apr 12 07:45 The.Mosquito.Coast.1986.1080p.BluRay.H264.AAC-RARBG
drwxr-xr-x 2 aj aj 4096 Apr 12 13:09 The.Voices.2014.1080p.BluRay.H264.AAC-RARBG
drwxr-xr-x 2 aj aj 4096 Apr 12 07:46 Valley Of Bones (2017) [WEBRip] [1080p] [YTS.AM]

![image](https://user-images.githubusercontent.com/4976642/38676898-c8e6f1a2-3e5c-11e8-9d7e-410085c56552.png)

**Comment by PiscisSwimeatus** [comment]
What's strange is that I am able to expire it sometimes, only for it to reappear some time later.

**Comment by remusb** [comment]
Let me understand. That folder doesn't exist at all and it just appears in rclone?

**Comment by animosity22** [comment]
This looks to be a stale item. Please if you still have a question, you can post on the forums and we can help out!
