### ISSUE TITLE
Plex Library Update causes rclone mount to fail. - How to resolve

### ISSUE THREAD

**Issue by drpau** [rclone/rclone#2278]
Sorry to rehash an existing issue, however, this is more of a tip for anyone else who comes across it.
I raised the below issue previously
#2102 

and am now on 1.40-130 and i created a completely new configuration with defaults.

When forcing a Library update in Plex, I experienced the same issue (essentially the rclone mount drops, and then the plex scan ends up "deleting/red trash can" items from the library).

I do not have plex integration in the cache remote.  

The resolution as detailed in #2102 is still suitable however if @remusb @seuffert could come up with a permanent fix - that would be great.

To anyone searching this: you need to enable logging on your mount command.  This artificially slows down the plex library scan - but makes it stable.  to do this, add the following to the end of your mount command:
` >/tmp/rclone.log 2>&1 &
`
for reference my full mount command is:
`/rclone mount this_one: /mnt/gdrive.de/ --allow-other --config=/volume1/rclone.conf >/tmp/rclone.log 2>&1 &
`

**Comment by easy90rider** [comment]
This does not work all the time. If I add a large amount of data to my plex, so that it has to scan a lot of files, it will crash...

My mount is crashing because of high RAM usage.
For it not to crash I have to set chunk_size to 1M.

BTW does it make any difference if you enable logging via 

`./rclone mount this_one: /mnt/gdrive.de/ --allow-other --config=/volume1/rclone.conf -v --log-file=/tmp/rclone.log`

?

**Comment by drpau** [comment]
no it doesnt make a difference, they both work the same.  
Ta for the heads up on the chunk size, i had had a 1M chunk size but now at 500M and this isnt causing issues.

However - i am also running this on a Synology DS916+ which may cause unforeseen differences.

**Comment by easy90rider** [comment]
That's strange. I had issues with large chunk size, because for each scanned file it had to download, and keep in RAM, 16MB of data instead of 1MB.

I suppose plex only needs the metadata, when it scans the files, but  I don't know how large that is.

**Comment by ncw** [comment]
> When forcing a Library update in Plex, I experienced the same issue (essentially the rclone mount drops, 

Why does the mount drop?  Does rclone crash?  If so please attach the traceback.  If not, what happens?

I suspect it might be running out of file handles or something like that?

**Comment by drpau** [comment]
@ncw in the other issue i posted a number of logs and none of them were conclusive.  while it may be running out of file handles or something like that, it doesnt actually say in the logs.

From a user experience issue, the rlcone binary is no longer running and therefore the mount disappears / is unmounted.

Causing it to crash isnt exactly welcoming as if and when i do it, i have rescan my whole plex library as it marks each of the items deleted.  This also screws up my "watched" history etc.

**Comment by ncw** [comment]
@drpau wrote:
> From a user experience issue, the rlcone binary is no longer running and therefore the mount disappears / is unmounted.

OK.

In order to have any hope of debugging this I need more info!  When rclone crashes it will almost certainly write a backtrace to stderr or the log file which will say exactly what went wrong.  If you could maybe set up a test system, cause rclone to crash (with [the latest beta](https://beta.rclone.org)) and send the backtrace then we stand a very good chance of being able to fix it.

**Comment by jrarseneau** [comment]
@drpau 

While this is not a solution, I recommend you turn off "Empty trash automatically after every scan" in your Plex Media Server settings.

Settings -> Library -> Check off the above option (Make sure you click "Show advanced" as this may be an advanced option).

At least this way, Plex won't mess up your watched history, etc.

**Comment by drpau** [comment]
thanks @jrarseneau - i do have that option set that way (learnt the hard way).  Unfortunately something else in my setup is requiring me to do a complete library scan to re-initialise the episode, if i dont do that the episode/movie always stays "unavailable" with the red bin on it.  This isnt an rclone issue but a plex issue.  Unfortunately with this it requires me to do a reanlysis of the data (and i have a lot) therefore the rescan takes a LONG time (many days).  which is why im relunctant to allow this mount to drop through a scan again and essentially break my library.

**Comment by drpau** [comment]
@zsmbrvr how do you selectively scan only red trash can items.  Plex forums employee said that the only way was a complete library scan..

ta

**Comment by zsmbrvr** [comment]
@dpedu , you select them, and click on the refresh metadata under the 3 dots OR do a Scan Library Files type of scan...

Either way it should be fine.

**Comment by remusb** [comment]
@zsmbrvr @drpau are you still having issue with the recent version?

**Comment by drpau** [comment]
@remusb i have not changed my setup to not have the >/tmp/rclone.log 2>&1 & at the end of the command.

I do not have the available bandwidth to allow it to fail again, unfortunately.  

If you are able to advise me on how to backup my library and then i will mount and test without the logfile so if it does "red bin" my entire library that i can restore it, im happy to give it a go.

Thanks

**Comment by drpau** [comment]
@remusb forget the above, i have done some investigations into it and i have made a backup and have started to test.  I am running now 1.41-101 beta and i have just kicked off a library scan.  Will report back, but initial findings are looking good.  doesnt seem to have crashed yet.

**Comment by drpau** [comment]
@remusb, unfortunately, i have ended up with a crashed library again.  red bins across all my entries.

**Comment by remusb** [comment]
What OS was this again @drpau ?

It's a bit surprising that there are no more mentions of this from other users.

**Comment by drpau** [comment]
@remusb its really annoying that no one else has it! :P but im not sure if anyone else is doing it on a synology NAS either.... so maybe im just first one :(

```
[ash-4.3# uname -a
Linux Syn 3.10.102 #15284 SMP Sat May 19 04:52:23 CST 2018 x86_64 GNU/Linux synology_braswell_916+
ash-4.3#
```

**Comment by animosity22** [comment]
This looks to be an old, stale item. If you still have a question or problem, please ask in the forums.
