### ISSUE TITLE
Add bwstats

### ISSUE THREAD

**Issue by l3uddz** [rclone/rclone#2280]
Would be awesome to have a bwstats remote control endpoint & command.

Idea is it returns the current transfer rate and transfered amounts.

**Comment by ncw** [comment]
That seems like a good idea!

Want to have a go at implementing it?

Essentially we'd need a version of this function which returned a `map[string]interface{}` which could then be jsonified.  That would need to be registerd with the rc module (which is easy).

https://github.com/ncw/rclone/blob/0479c7dcf5eda14da66ca8faaf81b2d1821d7212/fs/accounting/stats.go#L48-L84

This calls this to make the details stats on each transfer...

https://github.com/ncw/rclone/blob/0479c7dcf5eda14da66ca8faaf81b2d1821d7212/fs/accounting/accounting.go#L232-L269

I'd do away with all the human formating stuff and just return the untrimmed strings and bytes.

**Comment by ncw** [comment]
I think the work for this was done in #5116 so I'm going to close this now.
