### ISSUE TITLE
[Request] Emby Integration with Cache

### ISSUE THREAD

**Issue by jaketame** [rclone/rclone#2297]
### Request

I'm currently using Emby over Plex as it handles 4K files better than Plex does... 

Can I request that the rclone cache implementation for monitoring whats being played is implemented for Emby too?

Thanks

**Comment by jaketame** [comment]
I’m not competent enough to write something but might take a look at the Plex code and see if we can get something going.

There is a third part working on ability to direct stream .strm files from google so you get google power!

**Comment by remusb** [comment]
I'll tag it to have it in sight. Should be able to do it in the near future if no one else wants to pick it up by them

**Comment by acs-ferreira** [comment]
As this has been re-tagged from 1.43 to "Soon" more than 1yr ago, any idea if this can and will be implemented? Thanks.

**Comment by ncw** [comment]
The cache backend is a little unloved at the moment do contributions would be appreciated.

**Comment by ivandeex** [comment]
The cache backend is not supported anymore.
