### ISSUE TITLE
Log to file on windows, opened in notepad, is on a single line

### ISSUE THREAD

**Issue by zsmbrvr** [rclone/rclone#2300]
#### What is the problem you are having with rclone?
When you log to file on windows, the text in notepad is on a single line.

#### What is your rclone version (eg output from `rclone -V`)
Latest beta, v1.41-035.

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone.exe copy C:\X cloud: -v --log-file=file.txt

The issue is that linux and windows have different Newline control character, and I suppose rclone uses the linux one.

https://en.wikipedia.org/wiki/Newline

I read that notepad will be updated to support the linux line ending, but I am sure this will be updated for Windows 10 and older versions will be left with no update.

**Comment by ncw** [comment]
I suggest you open the file in wordpad or [notepad++](https://notepad-plus-plus.org/) both of which support unix line endings.

In fact notepad is about the only program I can think of that doesn't support unix line endings!

**Comment by ascendbruce** [comment]
FYI, notepad will soon support Unix line endings in Windows 10. But as @ncw mentioned, it's recommended to use other editors in the meantime.

https://www.zdnet.com/article/windows-notepad-finally-understands-everyone-elses-end-of-line-characters/
