### ISSUE TITLE
Bandwidth Usage Problem with --max-transfer 600G

### ISSUE THREAD

**Issue by xyber411** [rclone/rclone#2311]
I've been trying to stay under the limits by a healthy portion, but something interesting seems to be happening:

When I run with the --max-transfer 600G flag, once the max transfer has been reached, I get a lot of these:
ERROR : [4GB filename redacted]: RWFileHandle.Flush error: failed to transfer file from cache to remote: Post https://www.googleapis.com/upload/drive/v3/files?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType&uploadType=resumable&upload_id=[id redacted]: Max transfer limit reached as set by --max-transfer

Which is awesome!!!...  but....

Looking at my bandwidth usage, I see that the ethernet port maxes itself out (yes, I have GB fiber), for about 7 seconds (enough to check a 4GB file?), then has about 3 seconds of no usage.  The timing of the start of the bandwidth usage is very much in time with the error messages.  What's so very strange though, is it's the receiving side that is maxing out, not the sending side.  I'm unsure what to make of this, but I'm limiting my bandwidth usage to be on the safe side for now.

Any thoughts on this would be helpful.

Details:
I'm running a cached, encrypted, mount.  I try to limit this to below the 600G mark to be on the safe side with Google.
				rclone mount $CachedRclone $CachedLocal \
				--allow-other \
				--dir-cache-time=160h \
				--buffer-size 25M \
				--cache-db-path=$DBCache \
				--cache-dir=$ChunkCache \
				--cache-chunk-path=$ChunkCache \
				--cache-rps=8 \
				--cache-workers=5 \
				--cache-chunk-size=5M \
				--cache-info-age=168h \
				--cache-total-chunk-size=250G \
				--attr-timeout=1s \
				--bwlimit=7500 \ #This was not here before I noticed the error and bandwidth usage.
				--max-transfer 600G \
				--vfs-cache-mode=writes \
				--vfs-cache-max-age 0h30m0s \
				-v &

**Comment by ncw** [comment]
So what you are saying is that once the bandwidth limit is hit, you get a 7s burst of traffic on the receive side.  That is a maximum of 875 MB at 1 Gbit.

I'm not sure what is going on here but I suspect the cache is doing something...

Do you have any logs from the cache after it maxes out? (can you try with `-vv`)

**Comment by xyber411** [comment]
It will do a 7s burst of traffic once every 10s.  I'll see if I can get a -vv on it, but I'll have to hit my limit...  maybe if I reduce it, a similar thing will happen...

**Comment by animosity22** [comment]
This looks to be a stale item. If you have a question, please feel free to ask on the forums.
