### ISSUE TITLE
"key not found" error when listing OpenStack object store

### ISSUE THREAD

**Issue by l0b0** [rclone/rclone#2342]
#### What is the problem you are having with rclone?

```
$ rclone-v1.41-089-g05edb5f5β-linux-amd64/rclone -vv ls 'my object store:my_directory'
DEBUG : rclone: Version "v1.41-089-g05edb5f5β" starting with parameters ["rclone-v1.41-089-g05edb5f5β-linux-amd64/rclone" "-vv" "ls" "my object store:my_directory"]
DEBUG : Using config file from […]
Failed to create file system for "my object store:my_directory": key not found
```

(Timestamps removed and names anonymised.)

#### Which OS are you using?

Ubuntu 18.04 official Vagrant image.

####  Which cloud storage system are you using?

OpenStack object store.

#### Other

I've authenticated using an OpenStack RC file, so these are set:

```
$ env | grep -Eo '^OS_[^=]+'
OS_AUTH_URL
OS_PROJECT_DOMAIN_ID
OS_TOKEN
OS_REGION_NAME
OS_PROJECT_NAME
OS_IDENTITY_API_VERSION
OS_AUTH_TYPE
OS_USERNAME
OS_PROJECT_ID
```

`openstack object list --all --format=value my_directory` works fine.

rclone.conf:

```
[my object store]
type = swift
env_auth = true
```

I got the same result with stable v1.41.

With v1.36 from the official Ubuntu repositories I get almost the same message, but instead of "key not found" I get "user not found".

**Comment by ncw** [comment]
Can you run rclone with `rclone -vv --dump bodies lsd "my object store:"` and see if that works?  If it doesn't then can you post the output?

**Comment by l0b0** [comment]
@ncw Adding `-vv --dump bodies` (or `--dump-bodies` in case of v1.36) does not change anything - nothing new is printed.

**Comment by ncw** [comment]
Thanks for that.  That means no http transactions are being sent and a bit of grepping in the source code shows me that "no key found" means that it can't find your API KEY.

I see in your list that `OS_PASSWORD` isn't set - that is what rclone is complaining about.

**Comment by l0b0** [comment]
`OS_PASSWORD` isn't set when using an OpenStack v3 RC File. I'm also using MFA, so it wouldn't help if it was. I believe `rclone` needs to use `OS_TOKEN` instead.

**Comment by ncw** [comment]
Ah, rclone is spelling that `OS_AUTH_TOKEN` - can you try that and see if it works?

That is what it always used to be called - I wonder when it changed?

**Comment by l0b0** [comment]
https://wiki.openstack.org/wiki/CLIAuth mentions `OS_TOKEN`, while `OS_AUTH_TOKEN` is never mentioned. This has been the case since [the first version of that page in 2011](https://wiki.openstack.org/w/index.php?title=CLIAuth&direction=prev&oldid=12081).
