### ISSUE TITLE
Put mkParentDir failed: 521 directory already exists

### ISSUE THREAD

**Issue by nitsuj102284** [rclone/rclone#2363]
After receiving this error, I installed the latest beta, and still am receiving the error.

I am trying to copy files from **Google Cloud Storage** to **BunnyCDN Storage (ftp)**, but I receive an error: _Put mkParentDir failed: 521 directory already exists_.

**rclone -V output:**
rclone v1.42-013-g6b424213β
- os/arch: linux/amd64
- go version: go1.10.1

**rclone command:**
rclone copy gcs:[bucket]/HqWdw6cq57 bcdn:/storage/HqWdw6cq57

Failed to copy: Put mkParentDir failed: 521 "storage/HqWdw6cq57" directory already exists

**Comment by ncw** [comment]
521 appears to be a non standard error code...  Actually I found it in [RFC 959](https://tools.ietf.org/html/rfc959) in one of the examples meaning exactly this.

I've added support for it - can you give this a go?

https://beta.rclone.org/branch/v1.42-014-g8e0bfaba-fix-2363-bunnycdn/ (uploaded in 15-30 mins)

**Comment by nitsuj102284** [comment]
@ncw, thanks for the reply! That works, in that it is uploading the files to BunnyCDN, but while it is transferring, I'm getting this error for every file:

_ERROR: [filename] Failed to copy: update getinfo: object not found_


Any ideas?

**Comment by ncw** [comment]
What happens is rclone uploads the object, then it attempts to make sure it is there on the server.  Apparently it isn't there when rclone checks hence the error.

Rclone will do a retry and I suspect it will find the objects on the retry - is that what you see?

I suspect there is some sort of eventual consistency going on with BunnyCDN namely that objects don't appear immediately in the listings.

 I could make it sleep and retry if it got that object not found error.  It would be helpful if I had some idea how long the file was missing from the listing - you may be able to do an experiment with rclone to find out.

**Comment by nitsuj102284** [comment]
I'm not sure; when I got back to the file viewer in BunnyCDN, I see the files showing up. What is the default delay in checking to see if the file has uploaded, and what can I pass to change this behavior?

**Comment by nitsuj102284** [comment]
Also, I suspect because of this error message, it never really stops on the server, and I have to go to BunnyCDN to see that the last file was transferred, and then I go back to the terminal and control + c.

**Comment by ncw** [comment]
> I'm not sure; when I got back to the file viewer in BunnyCDN, I see the files showing up. What is the default delay in checking to see if the file has uploaded, and what can I pass to change this behavior?

There is no delay at the moment - it checks immediately.

Can you  send a log with `-vv` of a complete transfer please? Either attach a .zip file here or email it to nick@craig-wood.com.

**Comment by ncw** [comment]
I've merged the fix above here:

https://beta.rclone.org/v1.42-015-gb9b9bce0/ (uploaded in 15-30 mins)

Let me know about the log!

**Comment by nitsuj102284** [comment]
@ncw, sorry for the delay. I sent the log to your email address.

**Comment by ncw** [comment]
Thanks for the log.

Unfortunately it doesn't have the retry in it.  What I'm wondering is if you let rclone run all the way to the end it will do a retry.  I expect at that point it will transfer nothing as all the files have successfully been transferred.  Is that what you see?

**Comment by ivandeex** [comment]
@nitsuj102284 Does the problem reproduce with rclone 1.54?

**Comment by ivandeex** [comment]
No answer for several years. This request is stale. Closing.

**Comment by akiross** [comment]
I'm experiencing this issue with version 1.55 when trying to upload a file to FTP (tophost.it), but it might be me not using it properly:

I'm trying to copy a directory with a file in it to the FTP server, but on the remote there's already a file that has the name of the directory.

Here's the relevant part of the `-vv` log (other debug messages were suppressed as other files are copied correctly).

```
DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
DEBUG : rclone: Version "v1.55.0" starting with parameters ["rclone" "copy" "-vv" "public/" "example:/htdocs/"]
DEBUG : Creating backend with remote "public/"
DEBUG : fs cache: renaming cache item "public/" to be canonical "/myrepos/example/public"
DEBUG : Creating backend with remote "example:/htdocs/"
DEBUG : ftp://ftp.example.com:21/htdocs: Connecting to FTP server
ERROR : news/20210412-1100/index.html: Failed to copy: Put mkParentDir failed: is a file not a directory
ERROR : Attempt 1/3 failed with 1 errors and: Put mkParentDir failed: is a file not a directory
ERROR : Attempt 2/3 failed with 1 errors and: Put mkParentDir failed: is a file not a directory
ERROR : Attempt 3/3 failed with 1 errors and: Put mkParentDir failed: is a file not a directory
DEBUG : ftp://ftp.example.org:21/htdocs: Waiting for checks to finish
DEBUG : ftp://ftp.example.org:21/htdocs: Waiting for transfers to finish
ERROR : Attempt 3/3 failed with 1 errors and: Put mkParentDir failed: is a file not a directory
INFO  :
          0 / 0 Bytes, -, 0 Bytes/s, ETA -
    1 (retrying may help)
  843 / 843, 100%
  6.3s
ERROR:root:
DEBUG : 3 go routines active
```

I'd expect `rclone copy` to remove the file on the destination and upload the directory, but it's not: am I missing a flag or is this a bug?

Thanks

**Comment by ivandeex** [comment]
@akiross 
Thank you for your report :)
May I ask you to:
1. copy the data you already provided
2. run `rclone config show example:` to print the ftp section, replace password with `xxxxx` and add to the mix
3. click `New issue` > `Bug`
4. paste and submit
?
This way your report has more chance to be noticed by the team!

**Comment by akiross** [comment]
I am not sure this is actually a bug: I was under the impression that `rclone copy` was allowed to delete things on destination, but it is not. I was expecting it to delete existing files to replace them with directories, but from the documentation it seems that behavior would be wrong. Please disregard my previous report if this makes sense. Otherwise I'll be happy to provide more info.

**Comment by ncw** [comment]
> I am not sure this is actually a bug: I was under the impression that `rclone copy` was allowed to delete things on destination, but it is not.

It isn't allowed to delete things.

> I was expecting it to delete existing files to replace them with directories, but from the documentation it seems that behavior would be wrong. Please disregard my previous report if this makes sense. Otherwise I'll be happy to provide more info.

`rclone sync` doesn't do that either. It probably should but I've always worried about data loss.
