### ISSUE TITLE
cache: pending uploads block mount starting

### ISSUE THREAD

**Issue by bigbruhmoment1** [rclone/rclone#2364]
#### What is the problem you are having with rclone?
When RClone cache has pending offline uploads, it will no longer mount the volume if it is rebooted before the items are finished uploading.

#### What is your rclone version (eg output from `rclone -V`)
v1.41

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount cache: -vv

**Comment by ncw** [comment]
Can you show the log message please with `-vv` of it failing to mount?

Also have you tried [the latest beta](https://beta.rclone.org)?

**Comment by irule311** [comment]
There is no log message at all of it even attempting to mount. Normally, it will say mounting /media/plex, but in this situation, it doesn't have any log message. 

I will try the beta tonight.

**Comment by irule311** [comment]
I tried the latest beta and have the same problem. (v1.42-015-gb9b9bce0β)

It is almost like rclone doesn't even acknowledge that I used rclone mount. 
Everything else runs like normal.

Here are some logs. It doesn't even mention a failure to mount. Clearing the pending upload folder and cache db immediately fixes the issue.

`Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 DEBUG : cache: wrapped FNStorage:Sync at root
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Cache DB path: /media/upload/cache.db
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Cache chunk path: /media/upload/chunkcache/cache
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Chunk Memory: true
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Chunk Size: 10M
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Chunk Total Size: 10G
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Chunk Clean Interval: 1m0s
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Workers: 5
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: File Age: 28h0m0s
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Upload Temp Rest Time: 1h0m0s
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Upload Temp FS: /media/upload/pending
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 DEBUG : Adding path "cache/expire" to remote control registry
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 DEBUG : Adding path "cache/stats" to remote control registry
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : fvhol109nnm74ro7h3ujhgo44k/mkgrp1qtfn81ma1anvmjjrfhp0/cagktr80kk9nivi56fe25qbne4/61o88vibb3icda5o4bg7q5s7tup5pu4m2ipj0rghmb8unq1q3lr4rh3d0f2e0hv3b50cjv9i2oeuk: background u
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 DEBUG : cache: wrapped FNStorage:Sync at root
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Cache DB path: /media/upload/cache.db
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Cache chunk path: /media/upload/chunkcache/cache
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Chunk Memory: true
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Chunk Size: 10M
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Chunk Total Size: 10G
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Chunk Clean Interval: 1m0s
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Workers: 5
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: File Age: 28h0m0s
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Upload Temp Rest Time: 1h0m0s
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 INFO  : cache: Upload Temp FS: /media/upload/pending
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 DEBUG : Google drive root 'Sync': Checking for changes on remote
Jun 30 17:06:10 rclone rclone[1162]: 2018/06/30 17:06:10 DEBUG : Google drive root 'Sync': All changes were processed. Waiting for more.`

**Comment by ncw** [comment]
So what happens - does rclone quit at that point?

Any chance you could upload the complete log - save it with `--log-file rclone.log`, zip it and then attach.

Thanks

**Comment by irule311** [comment]
No, rclone just sits there uploading the files from the pending upload folder. After all those files are completely uploaded, I can then restart rclone, and it will mount. I am not sure what happens after the files finish uploading (assuming rclone quits after uploading, never waited long enough to see).

I will try doing it again and seeing what happens.

**Comment by ncw** [comment]
OK thanks.

How do you know rclone hasn't mounted?

**Comment by irule311** [comment]
Sorry about the long delay.

Now that you mention it, it might have been mounted for all I know. The folder that should have been mounted (/media/plex) was empty though. 

I am also trying to recreate the problem to attach a log of what happened, but it appears to have stopped occurring.

First and foremost, everything is mounted on the box and shared using samba. 

I am experiencing slow read speeds that I do not experience with plexdrive on the same box. I am also experiencing issues deleting files from the cached mount that I do not experience on a mount without cache.

**Comment by ncw** [comment]
No worries for the delay!  A log with `-vv` would be very helpful.

Can you also try v1.42 or [the latest beta](https://beta.rclone.org)?

**Comment by irule311** [comment]
So I was able to get the problem to occur again. It appears like I have to reboot the box for this issue to occur. Just restarting the service will not cause it to happen. 

The mount is actually not mounted. I used umount to attempt to unmount the directory, and it stated that it was not mounted. 

The logs also don't show anything of use. I have attached it regardless though.
BTW this is with rclone v1.42.
[rclone.log](https://github.com/ncw/rclone/files/2208390/rclone.log)

**Comment by irule311** [comment]
So I was able to get the problem to occur again. It appears like I have to reboot the box for this issue to occur. Just restarting the service will not cause it to happen.

The mount is actually not mounted. I used umount to attempt to unmount the directory, and it stated that it was not mounted.

The logs also don't show anything of use. I have attached it regardless though.
BTW this is with rclone v1.42
[rclone.log](https://github.com/ncw/rclone/files/2208418/rclone.log)

**Comment by irule311** [comment]
I let it run overnight, and it looks like it eventually crashes and restarts itself. The files never upload, however the files are still accessible when rclone finally does remount itself.

I have trimmed the log down a bit. Most of it looked like this:
```
2018/07/19 12:45:08 DEBUG : Google drive root 'Sync': Checking for changes on remote
2018/07/19 12:45:08 DEBUG : Google drive root 'Sync': All changes were processed. Waiting for more.
2018/07/19 12:45:22 DEBUG : Google drive root 'Sync': Checking for changes on remote
2018/07/19 12:45:23 DEBUG : Google drive root 'Sync': All changes were processed. Waiting for more.
2018/07/19 12:45:35 DEBUG : Cache remote cache:: starting cleanup
2018/07/19 12:45:35 DEBUG : Cache remote cache:: starting cleanup
```
[rclone2.log](https://github.com/ncw/rclone/files/2211827/rclone2.log)

**Comment by ncw** [comment]
Is that more than one log joined together?  The timestamps are really weird in it as if you have two rclone's running at once.

**Comment by irule311** [comment]
It looks like I might have copied the wrong log. Sorry about that. It is all one log though. The timestamps may be wrong but the log is correct. 

I have since attempted it again after wiping everything clean including changing to a different directory. All the settings are still the same. 

After copying a file in, it just disappears and doesn't show in the rclone mounted directory? Though in the log, it shows that it was put in the cache?

I have also attached the entire log this time. 
```
2018/07/29 16:26:16 INFO  : 8o4vmkqlfkaukqqiqth24pi5og: put: uploaded in temp fs
2018/07/29 16:26:17 INFO  : 8o4vmkqlfkaukqqiqth24pi5og: put: queued for upload
2018/07/29 16:26:17 DEBUG : 8o4vmkqlfkaukqqiqth24pi5og: pending upload found
2018/07/29 16:26:17 DEBUG : 8o4vmkqlfkaukqqiqth24pi5og: put: added to cache
```
[rclone.log](https://github.com/ncw/rclone/files/2239204/rclone.log)

**Comment by irule311** [comment]
It looks like I might have gotten the wrong log when I trimmed it. The data is correct though even though the timestamps are wrong.

I have since attempted to redo this experiment again but using a new empty directory as the base. I was unable to get rclone to stop mounting the directory when rebooting, but rclone would not continue uploading the files again after rebooting (I rebooted in the middle of it uploading 1 file).

Before reboot:
Entire Log:
[rclone.log](https://github.com/ncw/rclone/files/2239227/rclone.log)

Trimmed Log:
[rclonetrim.log](https://github.com/ncw/rclone/files/2239228/rclonetrim.log)

After reboot:
[rclone2.log](https://github.com/ncw/rclone/files/2239229/rclone2.log)

PS: The before reboot logs show rclone restarting. I had previously copied one file in (test720.mkv), but it did not show in the mount. When I restarted rclone, it appeared in the mount, and I copied another file in (test720-2.mkv).

**Comment by irule311** [comment]
I've also noticed that with larger media files ~5GB, rclone won't even be able to play them smoothly. It will take over 1 minute for it to even open (over smb in vlc) and will stutter every 2-3 seconds. I can play the same video on the same box using plexdrive smoothly. 

It seems like rclone doesn't pull data. Here is a screencap from my router showing bandwidth used along with the log. The log makes it look like its pulling data, but there is nothing being pulled from the internet.
![rclone bandwidth](https://user-images.githubusercontent.com/10052885/43371210-efad8aa8-9352-11e8-87e2-51332535125b.PNG)
[rclone.log](https://github.com/ncw/rclone/files/2239242/rclone.log)


By comparison, plexdrive seems to be pulling data at a much quicker rate. Similarly sized video files or larger load in just 5 seconds.
![plexdrive bandwidth](https://user-images.githubusercontent.com/10052885/43371250-81e41144-9353-11e8-9ab7-6b4b7bd693ec.PNG)

**Comment by irule311** [comment]
@ncw 
Do you happen to know why this is occurring or how I can fix it?

**Comment by ncw** [comment]
@irule311 if you want advice on tweaking your settings then I recommend [the rclone forum](https://forum.rclone.org/) as there are lots of knowledgeable people there.

**Comment by irule311** [comment]
Sorry for getting off topic. 

I did have the exact same issue occur again after I thought it had fixed itself. I don't have a log of before the reboot, but I do have the after reboot. I noticed that this log does not mention mounting at all when normally it does say mounting the directory. 

Rclone proceeds to just upload without mounting.
[rclone.log](https://github.com/ncw/rclone/files/2285688/rclone.log)

**Comment by irule311** [comment]
That sounds right, and it only occurs when I reboot the system. I have rclone running as a service, and restarting the service does not cause this issue.

**Comment by B4dM4n** [comment]
I couldn't find any long time locks which could block the mount process until now, but I will investigate this further.

**Comment by ivandeex** [comment]
@bigbruhmoment1 Does the problem reproduce with rclone 1.54?

**Comment by ivandeex** [comment]
This request is stale.
Also, cache backend is not supported anymore.
You should use rclone VFS instead.

**Comment by fordiy** [comment]
The problem still exist in version of 1.61.1
The mount doesn't normally start the driver letter in Windows when it so much upload pending to finish. No matter reboot to try give up the uploads, still always pending to finish all uploads then implement the mount. Here the mount cmd:
`rclone mount ALIST:/ R: --cache-dir j:\tmp\rclone --vfs-cache-mode writes --no-modtime --multi-thread-streams 8 --vfs-read-chunk-size  256M --vfs-read-chunk-size-limit 600M  --buffer-size 4096M`
