### ISSUE TITLE
Rclone Offline Upload Delete or Overwrite Files Slow

### ISSUE THREAD

**Issue by irule311** [rclone/rclone#2365]
#### What is the problem you are having with rclone?
When offline upload is used with a cache and crypt wrap, files copied are fine, however if files are renamed, deleted, or edited, it seems to crash rclone. There is no response for a long time. Without cache, it works fine.

#### What is your rclone version (eg output from `rclone -V`)
v1.41

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu server, 64bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
/usr/bin/rclone mount plex: /media/plex \
        --allow-non-empty \
        --allow-other \
        --buffer-size=0 \
        --cache-chunk-path="/media/upload/chunkcache" \
        --cache-chunk-size=10M \
        --cache-db-path="/media/upload/cache.db" \
        --cache-dir="/media/upload/vfscache" \
        --cache-info-age=28h \
        --cache-read-retries=3 \
        --cache-tmp-upload-path="/media/upload/pending" \
        --cache-tmp-wait-time="10m" \
        --cache-total-chunk-size=10G \
        --cache-workers=7 \
        --config="/home/rclone/.config/rclone/rclone.conf" \
        --contimeout=5s \
        --dir-cache-time=24h \
        --gid 0 \
        --max-read-ahead=2G \
        --timeout=5s \
        --track-renames \
        --uid 0 \
        --umask 000 \
        --vfs-cache-mode writes\
        -vv

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
There are no logs related.

**Comment by ncw** [comment]
Can you try with v1.42 and with [the latest beta](https://beta.rclone.org) please?

**Comment by animosity22** [comment]
Appears to be stale and fixed at this point. If you still have a question, please post on the forums and we are happy to help out!
