### ISSUE TITLE
Upload speed to google drive 

### ISSUE THREAD

**Issue by NguyenKhong** [rclone/rclone#2368]
#### What is the problem you are having with rclone?

I do not know about golang, but I found the issue of rclone's upload speed, it's located at line 1236 in the transport.go file under the net/http library. I tried changing to pconn.bw = bufio.NewWriterSize(persistConnWriter{pconn}, 2097152) with a 2MBytes buffer instead of 4K. The speed varies considerably from a few hundred KBytes/s to MBytes/s

#### What is your rclone version (eg output from `rclone -V`)

rclone v1.41

- os/arch: windows/amd64
- go version: go1.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 7, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive and my webdav

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

Rclone copy and sync

**Comment by ncw** [comment]
Can you show me which rclone command line you are using to measure the speed?

And show a before and after please?

Did you try increasing `--buffer-size` and `--drive-chunk-size` ?

That piece of code is in the Go standard library so I can''t patch it in the rclone source.  It might be that we can find a work-around in the rclone code.

If not though, then you'll need to make a simple example with a before and after comparison and make an issue on the go bugtracker.

**Comment by NguyenKhong** [comment]
Sorry for not giving you example.
The following is a comparison picture

- Google drive
![googledrive](https://user-images.githubusercontent.com/21167908/42137364-412a9246-7d95-11e8-81c6-6cdacdecec3b.png)

- My webdav use tcptrack to monitor
![mywebdav](https://user-images.githubusercontent.com/21167908/42137371-56621ec2-7d95-11e8-8059-24cc28bf6416.png)

**Comment by ncw** [comment]
Do you get better performance if you increase `--buffer-size` from the default 16M?

**Comment by NguyenKhong** [comment]
I tried changing the --buffer-size from 8M to 16M, 32M, 128M but it still does not increase performance

**Comment by ncw** [comment]
Thanks for the tests and the screnshots.

The bit of code you changed is in the go standard library.

If you can make a stand alone go program to demonstrate the problem they you can report a go issue.

**Comment by HazCod** [comment]
Referencing: https://github.com/golang/go/issues/22618

**Comment by ncw** [comment]
Thanks for pointing that out @HazCod - that is exactly the fix @NguyenKhong was looking for.

**Comment by animosity22** [comment]
This looks to be a stale issue. If you have a new question, please feel free to ask in the forums and we are happy to help.
