### ISSUE TITLE
rclone sync to webdav/owncloud failing to detect file move

### ISSUE THREAD

**Issue by sp31415t1** [rclone/rclone#2373]
Hi!

I made test with rclone 1.41 and webdav/owncloud account provided by transip (re-branded as Stack)

'rclone sync' failed to detect file move and create a new file and delete the old one.

source is local filesystem with debian stretch os. I will appreciate to have the ability to rename local folder without re-uploading all files and so saving my bandwidth

It is a feature request, not a bug report.

Regards,
Serge

**Comment by ncw** [comment]
What you need is `--track-renames` which will work with `sync`.

**Unfortunately** `--track-renames` requires a remote that supports hashes which owncloud and nextcloud don't.

It might be possible to add hashes to owncloud/nextcloud - I just couldn't find any documentation on how to.

**Comment by sp31415t1** [comment]
It seems that they added file hash recently, but they forget about the documentation.

I only found that (and its others references) : https://github.com/owncloud/client/issues/6153

It is also possible to do an integrity check (file hash) on upload : https://doc.owncloud.org/desktop/2.4/architecture.html#upload
But it is another subject.

**Comment by sp31415t1** [comment]
For nextcloud documentation, there is a property '{http://owncloud.org/ns}checksums':
https://docs.nextcloud.com/server/14/developer_manual/client_apis/WebDAV/index.html
maybe the requested hash

**Comment by ncw** [comment]
@sp31415t1 nice one - thanks.  Since this isn't relevant to this issue, can you please make a [new issue on github](https://github.com/ncw/rclone/issues/new) with the heading "webdav: add hash support to owncloud and nextcloud" and put your findings in there.  I've got some findings to add too :-)

**Comment by ncw** [comment]
Owncloud and nextcloud both support hashes now.
