### ISSUE TITLE
Local cache to store failed uploads from VFS, retry upload after set time.

### ISSUE THREAD

**Issue by Thomas-Geraghty** [rclone/rclone#2382]
#### What is the problem you are having with rclone?

When using VFS cache with a service that has an upload limit (i.e Google Drive), if the upload limit is reached, the VFS cache will begin deleting any non uploaded files when they reach their retries amount.

#### What is your rclone version (eg output from `rclone -V`)

rclone v1.42-005-g56e1e820β

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 17.10 64bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

This involves writing to the mount, so my mount command is

rclone mount gcrypt:/ /mnt/remote  --allow-other --vfs-cache-max-age 4h --dir-cache-time 48h  --vfs-read-chunk-size 12M --vfs-read-chunk-size-limit off --buffer-size 1G --cache-dir "/mnt/ssd2/cache/"

#### Suggestion

I'd recommend implementing a way to cache files locally if they fail to upload, and then trying to upload these files again after a set time period.

**Comment by darthShadow** [comment]
I believe this should be handled automatically when the vfs cache starts using the cache backend. Will this be implemented earlier?

**Comment by ncw** [comment]
This is an important piece missing from the --vfs-cache-writes solution at the moment - when an upload fails then rclone will keep it in the VFS cache but it won't retry it.

@darthShadow yes this would be handled with a cache backend/VFS integration - we'll have to see which come first :-)

**Comment by darthShadow** [comment]
> when an upload fails then rclone will keep it in the VFS cache but it won't retry it.

Is this true for `--vfs-cache-mode writes` too? I was under the impression that this was true only for `--vfs-cache-mode full` and even then it looks like it will be deleted after the `vfs-cache-max-age`.

> In this mode, unlike the others, when a file is written to the disk, it will be kept on the disk after it is written to the remote. It will be purged on a schedule according to --vfs-cache-max-age.

**Comment by danielloader** [comment]
Are we looking at a scenario where VFS functionality absorbs most of the need for cache or will they remain competing implementations? VFS has much better performance for me but the unreliability of upload leaves it less useful, with data sanctity being more important than speed for me at least.

**Comment by ncw** [comment]
@danielloader - I'm trying not to make the VFS layer too complicated as reliability is extremely important to me.  This issue is a bit of a hole in the reliability of the VFS layer though so I really want to fix it.

In the long run I'd like to integrate the cache backend better with the VFS layer - they would work better together then.

**Comment by ncw** [comment]
This issue should be fixed with v1.53's vfs cache layer rework.
