### ISSUE TITLE
Plex integration error + errors in log file

### ISSUE THREAD

**Issue by drpau** [rclone/rclone#2394]
**Issue 1:**
I have automation setup that plex will not start unless rclone is started (and if one crashes, the other restarts).  As rclone is needed before plex starts, rclone throws an error saying it cant connect to my plex instance (as per below) cause its not running.

I do not see any future items in the log file for successful connection to plex.  Does it retry after X time?  If not - can it?

**Issue 2:**
Additionally, i am getting a few errors in my log file which im not sure of.  Why am i getting --config recommendations, when im clearly using --config and the last error of Failed to create file system.

Thanks!

#### What is the problem you are having with rclone?
Errors in the log file:
```
2018/07/13 09:34:53 ERROR : Couldn't find home directory or read HOME or XDG_CONFIG_HOME environment variables.
2018/07/13 09:34:53 ERROR : Defaulting to storing config in current directory.
2018/07/13 09:34:53 ERROR : Use --config flag to workaround.
2018/07/13 09:34:53 ERROR : Error was: user: Current not implemented on linux/amd64
2018/07/13 09:34:53 ERROR : plex: websocket.Dial wss://10.0.1.3:32400/:/websockets/notifications?X-Plex-Token=2rA*****ctNax15: dial tcp 10.0.1.3:32400: connect: connection refused
2018/07/13 09:34:54 ERROR : /volume1/rclone_cache/cache.db: Error opening storage cache. Is there another rclone running on the same remote? failed to open a cache connection to "/volume1/rclone_cache/cache.db": timeout
2018/07/13 09:34:54 ERROR : plex: websocket.Dial wss://10.0.1.3:32400/:/websockets/notifications?X-Plex-Token=2rA****tNax15: dial tcp 10.0.1.3:32400: connect: connection refused
2018/07/13 09:34:55 ERROR : /volume1/rclone_cache/cache.db: Error opening storage cache. Is there another rclone running on the same remote? failed to open a cache connection to "/volume1/rclone_cache/cache.db": timeout
2018/07/13 09:34:55 Failed to create file system for "this_one:": failed to make remote "cache:" to wrap: failed to start cache db: failed to open a cache connection to "/volume1/rclone_cache/cache.db": timeout
```

#### What is your rclone version (eg output from `rclone -V`)
rclone1.42-026

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux Syn 3.10.105 #23739 SMP Wed Jun 20 22:39:54 CST 2018 x86_64 GNU/Linux synology_braswell_916+

####  Which cloud storage system are you using? (eg Google Drive)
google drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

/rclone mount this_one: /mnt/gdrive.de/ --allow-other --config=/volume1/rclone1.40.conf --cache-db-path=/volume1/rclone_cache > /tmp/rclone.log 2>&1 &

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

as per above.

#### my rclone conf.

ash-4.3# cat rclone1.40.conf
[gdrive_mount]
type = drive
client_id = 892488*****rulq.apps.googleusercontent.com
client_secret = VEKugWg*****3Ug
scope = drive
root_folder_id =
service_account_file =
token = {"access_token":"ya29.Gl32Bf3oIijFrY5******p3ol7xs0tFg3AhnWv","token_type":"Bearer","refresh_token":"1/1tXVWFC-N2b3VIfFmIrNdg***k","expiry":"2018-07-13T09:51:29.133344505+10:00"}

[cache]
type = cache
remote = gdrive_mount:
plex_url = https://10.0.1.3:32400
plex_username = drphoto
plex_password = LWzER******P4pXH7Rs
chunk_size = 5M
info_age = 12h
chunk_total_size = 10G
plex_token = 2rA*******x15

[this_one]
type = crypt
remote = cache:
filename_encryption = standard
directory_name_encryption = true
password = kD_HRS4I*****_why78
password2 = P*******E9BpLCWM

**Comment by animosity22** [comment]
The second item is you already have rclone running or an orphaned process and it can only run one time with the cache.

**Comment by ncw** [comment]
## Issue 1

> I do not see any future items in the log file for successful connection to plex. Does it retry after X time? If not - can it?

It looks like to me after a quick look at the code that it won't retry.  Is that right @remusb 

## Issue 2

I have fixed the `--config` ERRORs in the config file in #2397 so if you try [the latest beta](https://beta.rclone.org) you won't see those errors.

I think @animosity22 is correct about the other errors you have two rclone's running.

**Comment by drpau** [comment]
@ncw thank you for that, i will update to the latest beta.

@animosity22 its unlikely (but possible) as i use an application called "monit" to monitor the processes and when/if they crash, then restart them.  As part of that restart it does a kill on anything rclone, and also does a forced fuserumount on the directory.  That being said, it is possible that if that fails for whatever reason, then it believes 2 are there.

Thanks guys - hopefully we can get issue 1 fixed up to continue to try to have plex connections made every X until successful, if the config is in the mount.

cheers!

**Comment by animosity22** [comment]
the error is having more than 1 process access the cachedb:

`2018/07/13 09:34:55 ERROR : /volume1/rclone_cache/cache.db: Error opening storage cache. Is there another rclone running on the same remote? failed to open a cache connection to "/volume1/rclone_cache/cache.db": timeout`

I'd guess something is restarting it before it's actually fully shutdown.
