### ISSUE TITLE
Flag for copy empty dirs behavior

### ISSUE THREAD

**Issue by Hairo** [rclone/rclone#2404]
As suggested in #1837, a flag might be the best idea to give users the option to decide the behavior.

**Comment by wlerin** [comment]
This new behaviour is especially frustrating when I try to use filters to just copy a couple files from a large archive: Rclone now creates empty folders for everything in that archive even if no files in them were included.

**Comment by archon810** [comment]
@ncw Thoughts on adding this?

**Comment by wlerin** [comment]
The old behaviour was restored and a flag (`--create-empty-src-dirs`) added for those who actually want to spawn empty directories on the destination.

**Comment by archon810** [comment]
Oh, thanks, it worked. I was looking for it here https://rclone.org/docs/ but turns out it's the only option listed here https://rclone.org/commands/rclone_copy/.

**Comment by ncw** [comment]
Yes this is a command specific flag so is in the documentation for `copy`.

I'll close this now since I think we've solved the problem.
