### ISSUE TITLE
cache: pre-cache Plex On Deck content

### ISSUE THREAD

**Issue by drpau** [rclone/rclone#2407]
Considering plex integration is available albiet in its infancy, can we look at seeing how to have rclone get an upcoming list of what is "On Deck" and download / pre-cache this data?

Similar/Same idea to the unionfs script i have seen floating around which does much the same thing, but it requires a unionfs mount and the script to run.

Thanks

**Comment by ncw** [comment]
@remusb?

**Comment by B4dM4n** [comment]
Implementing more features based on Plex seems like a bad idea to me. This would increase the complexity of the `cache` even more would force us to keep up to date with the Plex development to keep this feature working. `rclone` should remain to be a common tool for working with storage providers. Besides that, there are other media solutions like Plex (for example Emby) which could also benefit from such a feature.

How about a new `rc` command to trigger caching of specific files:
```
rclone rc cache/fetch chunks=10 file=movie1.mkv file2=movie2.mkv
```
This could would keep `rclone` general and provide a way for external scripts/tools to fill the cache.

**Comment by drpau** [comment]
@jkaberg fair point, im sure rclone in all efforts are trying to improve this just as continued development.  This isnt particarly for load times, as a lof o people who use rclone may just have poor bandwidth.  This saves the use of bandwidth being used to watch media, rather than having the prepopulated (eg when lots of people at home at night, bandwidth is important, but when its not being used during the day, bandwidth can be used).

@B4dM4n i hear your point, but there is already plex integration.  This service could be dependant on if plex integration is active, then action it.  Your idea of doing a combined call for scripts isnt a bad option, but this could just be done at the OS level rather than integration into rclone.  My thoughts would be that if you are going to amend rclone, you would amend it for the integration to get it done right rather than dependant on something external.  just my opinion but.

**Comment by drpau** [comment]
@remusb @ncw - any chance of this being considered?
Appreciate may be a bit of work to do - but............ would be great to have this done.

**Comment by memnos** [comment]
This feature would be great.
Let's hope to have an answer.

**Comment by B4dM4n** [comment]
The command is not merged yet. We need to wait for a review of the code.

If you want to try it now, you would have to install Go and compile rclone manually.

**Comment by memnos** [comment]
Ok, tnx

**Comment by memnos** [comment]
I think now command has been committed.
I tried to run the .py file after changing settings and got no errors.
But how i know it is working?
What is it caching exactly?

**Comment by B4dM4n** [comment]
This could be my bad. I messed up the error return value of the fetch command.
There should be a corrected version at https://beta.rclone.org/v1.43-027-gdeda0936-beta/ soon.

To get the python script working only the following variables have to be set:
```
PLEX_URL = 'http://127.0.0.1:32400' # the plex server address
PLEX_TOKEN = '0123456789abcdef' # your plex token
RCLONE_MOUNT_PATH = '/mnt/data/' # the rclone mount point that plex is using
RCLONE_RC_ARGS = ['--rc-addr=127.0.0.1:1234'] # custom rclone arguments or [] if not needed
RCLONE_RC_CHUNKS = ':100' # the cache chunks to get
```

The `chunks=` parameter is documented in the `rclone rc` help. It is based on the `chunk_size` configuration of the cache remote and specifies the chunk range to download.
The default value `:100` will download the first 100 chunks of each file. To download the whole file use `: ` as the range.

**Comment by memnos** [comment]
I have this for every object:
Any idea?

{
        "status": {
                "erie_Tv/Chicago Med/Season02/Chicago Med.S02E08.L'escamotage.mkv": {
                        "Error": "object not found",
                        "FetchedChunks": 0
                },
                "erie_Tv/Grey's Anatomy/Season01/Grey's Anatomy.S01E01.Quando il gioco si fa duro.avi": {
                        "Error": "object not found",
                        "FetchedChunks": 0
                },

**Comment by memnos** [comment]
But after some time i got this:
2018/09/03 20:56:38 Failed to rc: connection failed: Post http://127.0.0.1:5572/cache/fetch: net/http: timeout awaiting response headers
Traceback (most recent call last):
  File "plex_ondeck.py", line 28, in <module>
    ('file%d=%s' % (i, f) for i, f in enumerate(files))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '<itertools.chain object at 0x7fefa5ceac90>' returned non-zero exit status 5

**Comment by B4dM4n** [comment]
> 2018/09/03 20:56:38 Failed to rc: connection failed: Post http://127.0.0.1:5572/cache/fetch: net/http: timeout awaiting response headers

This means that the `rclone mount` process took to long to fetch all the chunks and the `rclone rc` command canceled the request after the configured `--timeout` value (default 5m). The `rclone mount` will still continue to process all files, but you wont see the return status.

Your best option is probably to increase the `--timeout` setting.

**Comment by B4dM4n** [comment]
> files already cached are overwritten or are skipped?

All chunks found on disk will not be downloaded again.

But they will be read from the disk, which is a bit inefficient.

**Comment by drpau** [comment]
this sounds pretty promising.
@B4dM4n my apologies for not being able to understand what you are saying around the implementation but it sounds pretty sweet by the idea of getting X number of chunks in adv based on "On deck" contents.  This is a good implementation from what i can grasp.

Can you please advise me how to implement it and test?

I am running rclonev1.43-039 if that is of any benefit.

this is my config:
```
drpau@Syn:/$ sudo cat /volume1/rclone1.43.conf
Password:
[gdrive_mount]
type = drive
client_id = *******.apps.googleusercontent.com
client_secret = *******
scope = drive
root_folder_id =
service_account_file =
token = {"access_token":"*******}

[cache]
type = cache
remote = gdrive_mount:
plex_url = http://127.0.0.1:32400
plex_username = drp
plex_password = *******
chunk_size = 5M
info_age = 12h
chunk_total_size = 400G
plex_token = *******

[this_one]
type = crypt
remote = cache:
filename_encryption = standard
directory_name_encryption = true
password = *******
```

and my command to use rclone is:
`/volume1/rclone1.43-039/rclone mount this_one: /mnt/gdrive.de/ --allow-other --config=/volume1/rclone1.43.conf --cache-db-path=/volumeUSB1/usbshare > /tmp/rclone.log 2>&1 &`

**Comment by B4dM4n** [comment]
To get the script from [this post](https://github.com/ncw/rclone/issues/2407#issuecomment-417283899) working, you first need to add the `--rc` flag to your mount command.

I explained the settings for the python scipt in [this post](https://github.com/ncw/rclone/issues/2407#issuecomment-418151942).
In your case this would be the correct settings for these two settings:
```
RCLONE_MOUNT_PATH = '/mnt/gdrive.de/'
RCLONE_RC_ARGS = []
```

**Comment by drpau** [comment]
@B4dM4n thanks for that. Just fyi im on a synology nas and had to do a lot of (annoying) things to get this somewhat working on my device. long story short, had to get python 3 installed, then some modules, then install pip to get the plexapi stuff working and then edit some paths to make all the things work.

But........ finally got there.  

I too am having what appears to be timeout issues as you mentioned above.  I am on a ~8megabit down, and 1megabit (ADSL) internet connection and my guess is that this is what doesnt have enough bandwidth to complete the process therefore - timeout occurs.

I have 2 follow up questions
1: where do i add the `--timeout` to?  my rclone mount or the execution of the script?
2: is there a way of getting verbose output / any feedback when running the script to confirm what is happening?

**Comment by B4dM4n** [comment]
> 1: where do i add the --timeout to? my rclone mount or the execution of the script?

The `--timeout` flag can go into the `RCLONE_RC_ARGS` setting:
```
RCLONE_RC_ARGS = ['--timeout=1h']
```

> 2: is there a way of getting verbose output / any feedback when running the script to confirm what is happening?

`rclone rc` does currently not provide a live feedback. Only the final result is send back and then print out.
If you enable debug logging with `-vv` on your `rclone mount` command, you can watch the log output and see the downloaded chunks there, but this is not user friendly.

To get feedback after every file you could use this loop to download each file with it's own rc call:
```python
    for video in plex.library.onDeck():
        for media in video.media:
            for part in media.parts:
                check_call(chain(
                    ['rclone'],
                    RCLONE_RC_ARGS,
                    ['rc', 'cache/fetch', 'chunks='+RCLONE_RC_CHUNKS],
                    'file='+part.file[len(RCLONE_MOUNT_PATH):]
                ))
```

**Comment by drpau** [comment]
Thanks very much for the feedback - appreciate it.

I presume its working as i get a quick response from playing items on deck - however is there a way of verifying it?  And by that - i mean a simple way :) thanks :)

**Comment by B4dM4n** [comment]
The `rclone rc` response will tell you how many chunks of the file have been checked and are now in the disk cache (they could have been there already). `FetchedChunks` should have been named `ProcessedChunks`, which better describes it.
```json
{
	"status": {
		"series/file2.mkv": {
			"Error": "",
			"FetchedChunks": 100
		}
	}
}
```

To check which specific chunks are cached, you need to go tn the `--cache-dir` and find the chunk files (named after their offset from the beginning of the file) manually.

**Comment by memnos** [comment]
> > 1: where do i add the --timeout to? my rclone mount or the execution of the script?
> 
> The `--timeout` flag can go into the `RCLONE_RC_ARGS` setting:
> 
> ```
> RCLONE_RC_ARGS = ['--timeout=1h']
> ```
> > 2: is there a way of getting verbose output / any feedback when running the script to confirm what is happening?
> 
> `rclone rc` does currently not provide a live feedback. Only the final result is send back and then print out.
> If you enable debug logging with `-vv` on your `rclone mount` command, you can watch the log output and see the downloaded chunks there, but this is not user friendly.
> 
> To get feedback after every file you could use this loop to download each file with it's own rc call:
> 
> ```python
>     for video in plex.library.onDeck():
>         for media in video.media:
>             for part in media.parts:
>                 check_call(chain(
>                     ['rclone'],
>                     RCLONE_RC_ARGS,
>                     ['rc', 'cache/fetch', 'chunks='+RCLONE_RC_CHUNKS],
>                     'file='+part.file[len(RCLONE_MOUNT_PATH):]
>                 ))
> ```

You mean using that instead of:

`    for video in plex.library.onDeck():
        for media in video.media:
            for part in media.parts:
                files.append(part.file[len(RCLONE_MOUNT_PATH):])

    check_call(chain(
        ['rclone'],
        RCLONE_RC_ARGS,
        ['rc', 'cache/fetch', 'chunks='+RCLONE_RC_CHUNKS],
        ('file%d=%s' % (i, f) for i, f in enumerate(files))
    ))
`

Changing that part i have this error

`2018/09/12 08:34:11 Failed to rc: No '=' found in parameter "f"
Traceback (most recent call last):
  File "plex_ondeck_single_file.py", line 26, in <module>
    'file='+part.file[len(RCLONE_MOUNT_PATH):]
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '<itertools.chain object at 0x7fdad9d426d
`

**Comment by drpau** [comment]
just closing the loop on my end and requests - i have had the script running successfully for a few days now and have now incorporated it into my crontab schedule.

Thank you  for dev'ing this and your help in implementation

**Comment by drpau** [comment]
@B4dM4n sorry 1 last point in response to this:

> The rclone rc response will tell you how many chunks of the file have been checked and are now in the disk cache (they could have been there already). FetchedChunks should have been named ProcessedChunks, which better describes it.

my log is outputting "FetchedChunks": 100 rather than ProcessedChunks even though they have been previously Fetched.

from cronjob which ran at 13:00 daily (13/9/18).
```
 "TV/Who Is America/Season 01/Who Is America - S01E04 - Episode 4 WEBDL-1080p.mkv": {
                        "Error": "",
                        "FetchedChunks": 100
                }

```

from manually running at 14:30 (today - 13/9/2018) - approx 1.5hrs later

```
},
                "TV/Who Is America/Season 01/Who Is America - S01E04 - Episode 4 WEBDL-1080p.mkv": {
                        "Error": "",
                        "FetchedChunks": 100
                }


```

Its not erroring or causing issues - just worth a mention.  im not sure if you intended on just renaming Fetched to Processed or were expecting both to be displayed in different scenarios.

thanks

**Comment by B4dM4n** [comment]
@memnos 
I updated the [gist](https://gist.github.com/B4dM4n/c14816e02313e8d3076b3a18f7227cd9) with the working script (there was a misplaced bracket in the last one).

@drpau 
The result currently shows `FetchedChunks`, but this name is misleading.
The value returned is the number of `ProcessedChunks`, the number of chunks checked to be in the disk cache.

**Comment by memnos** [comment]
Tnx, now all seems to work properly.
Just 2 other question.

1) Is there the possibility to fetch only series on deck and not movies?
2) Is there the possibility to give cache/fetch for a dir instead on for single files?

**Comment by B4dM4n** [comment]
> Is there the possibility to fetch only series on deck and not movies?

Sure, the python plexapi can differentiate between movie's and shows. A check like `isinstance(file, plexapi.Show)` should do the trick.

> Is there the possibility to give cache/fetch for a dir instead on for single files?

This is not implemented yet, but it is definitely possible. I will put it on my to-do list, unless someone else wants to try this.

**Comment by memnos** [comment]
Sorry, but where shouls i put isinstance(file, plexapi.Show)
I'm not a coder and i'm not able to code.
Tnx

**Comment by B4dM4n** [comment]
@memnos 
There is a new version of the python script in the [gist](https://gist.github.com/B4dM4n/c14816e02313e8d3076b3a18f7227cd9#file-plex_ondeck_filter-py). It will only download show episodes, but can be changed easily to filter movies.

**Comment by drpau** [comment]
@B4dM4n unsure what has occured lately but it appears that the script is now erroring.
i am on rclone 1.46 
```
ash-4.3# ./rclone --version
rclone v1.46
- os/arch: linux/amd64
- go version: go1.11.5
ash-4.3#

````

and the script executes but logs this:
```
ash-4.3# cat /tmp/plex_ondeck.log
Traceback (most recent call last):
  File "/volume1/plex_scripts/plex_ondeck.py", line 28, in <module>
    ('file%d=%s' % (i, f) for i, f in enumerate(files))
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/subprocess.py", line 579, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/subprocess.py", line 1483, in _execute_child
    restore_signals, start_new_session, preexec_fn)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 104: ordinal not in range(128)
ash-4.3#
```
is this due to new rclone or do i have something locally broken?

**Comment by ncw** [comment]
I'm going to close this now as the script above along with the cache/fetch API seems to fix the problem.
