### ISSUE TITLE
Google Team Drive support for emptying trash

### ISSUE THREAD

**Issue by TheLinuxGuy** [rclone/rclone#2418]
Hi,

Google Team Drives behaves differently than regular Drive, it does not support the API method that seems to be used by 'rclone cleanup' [1] and thus it does not empty the trash for Team Drives when configured.

I believe Google intended to not allow a simple method to delete all data in a team drive. I think maybe rclone could obtain list of files in the trash bin for a team drive and execute a delete individually to get around this limitation by Google?

Right now emptying the trash on a Google Team Drive using 'rclone cleanup' does not seem to work.

[1] https://developers.google.com/drive/api/v2/reference/files/emptyTrash

**Comment by ncw** [comment]
Yes looking at the API it doesn't support team drives.  All the other API calls have a boolean to set supportsTeamDrives=true so I think calling this as it stands at the moment will empty your google drive trash rather than your teamdrive trash :-(

What rclone needs to do is find all the trashed items and delete them individually probably.

**Comment by zenjabba** [comment]
Any update on finding the files individually?

**Comment by zenjabba** [comment]
Just found out how to do this

`rclone delete $NAME: --drive-trashed-only --drive-use-trash=false --verbose=2`

**Comment by ferferga** [comment]
@ncw Came across this the other day. Was this forgotten somehow? Can you make cleanup behave like ``delete``?

**Comment by ncw** [comment]
Nice workaround from @zenjabba . Does anyone want to send in a pull request to implement it the backend method?

https://github.com/rclone/rclone/blob/9d4b3580a58ca9e2695e043931b3b8937c6395c0/backend/drive/drive.go#L2163

**Comment by Nottt** [comment]
This solution is good but still leave up the folders.  I have encountered multiple times a bug, where if you delete a folder, and then later server side move a file to a folder with the same name, it will move the file to the trashed folder, which causes issues.
