### ISSUE TITLE
[Feature Request] Add option --case-insensitive to rclone dedupe

### ISSUE THREAD

**Issue by cjangrist** [rclone/rclone#2430]
#### What is the problem you are having with rclone?
rclone dedupe does not merge folders when case in any one of the characters differs. Example:

The following folders are merged:
`This is My Folder 1`
`This is My Folder 1`

But the following are not:
`This is My Folder 2`
`this is My Folder 2`

#### What is your rclone version (eg output from `rclone -V`)
```
rclone v1.42
- os/arch: linux/amd64
- go version: go1.10.1
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 64 bit
Mac OS 12.6 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone dedupe

**Comment by ncw** [comment]
That seems like a reasonable request - fancy having a go?

**Comment by ivandeex** [comment]
Superseded by more general
- #4854
