### ISSUE TITLE
Unable to do Complie in the dir which be mounted by `rclone mount`

### ISSUE THREAD

**Issue by F-TD5X** [rclone/rclone#2432]
I mount a Google Drive to /mnt/GD, and then I write a simple cpp file in it. But I can't complie it with an error:"/usr/bin/ld: final link failed: Illegal seek".

rclone version: `1.42`
OS: `Archlinux amd64`
cloud storage: `Google Drive`
commands:
```
rclone mount GD:/ /mnt/GD
touch /mnt/GD/test.cpp
<type something in to test.cpp>
g++ test.cpp
<then shows the error>
```

### logs
<details>
<pre>
2018/08/02 07:37:17 DEBUG : rclone: Version "v1.42" starting with parameters ["rclone" "-vv" "mount" "GD:/" "/mnt/GD"]
2018/08/02 07:37:17 DEBUG : Using config file from "/foo/rclone.conf"
2018/08/02 07:37:17 DEBUG : Google drive root '': Mounting on "/mnt/GD"
2018/08/02 07:37:17 DEBUG : Adding path "vfs/forget" to remote control registry
2018/08/02 07:37:17 DEBUG : : Root: 
2018/08/02 07:37:17 DEBUG : : >Root: node=/, err=<nil>
2018/08/02 07:37:18 DEBUG : Google drive root '': Checking for changes on remote
2018/08/02 07:37:18 DEBUG : Google drive root '': All changes were processed. Waiting for more.
2018/08/02 07:37:25 DEBUG : /: Attr: 
2018/08/02 07:37:25 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:25 DEBUG : /: Lookup: name=".git"
2018/08/02 07:37:25 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:25 DEBUG : /: Lookup: name=".git"
2018/08/02 07:37:25 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:25 DEBUG : /: Lookup: name="HEAD"
2018/08/02 07:37:25 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:25 DEBUG : /: Lookup: name=".git"
2018/08/02 07:37:25 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:25 DEBUG : /: Lookup: name=".git"
2018/08/02 07:37:25 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:25 DEBUG : /: Lookup: name="HEAD"
2018/08/02 07:37:25 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:28 DEBUG : /: Lookup: name="g"
2018/08/02 07:37:28 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:28 DEBUG : /: Lookup: name="g"
2018/08/02 07:37:28 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:28 DEBUG : /: Attr: 
2018/08/02 07:37:28 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:28 DEBUG : /: ReadDirAll: 
2018/08/02 07:37:28 DEBUG : /: >ReadDirAll: item=6, err=<nil>
2018/08/02 07:37:28 DEBUG : /: Lookup: name="g+"
2018/08/02 07:37:28 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:28 DEBUG : /: Lookup: name="g+"
2018/08/02 07:37:28 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:28 DEBUG : /: Attr: 
2018/08/02 07:37:28 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:28 DEBUG : /: ReadDirAll: 
2018/08/02 07:37:28 DEBUG : /: >ReadDirAll: item=6, err=<nil>
2018/08/02 07:37:30 DEBUG : /: Lookup: name="t"
2018/08/02 07:37:30 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:30 DEBUG : /: Lookup: name="t"
2018/08/02 07:37:30 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:30 DEBUG : /: Attr: 
2018/08/02 07:37:30 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:30 DEBUG : /: ReadDirAll: 
2018/08/02 07:37:30 DEBUG : /: >ReadDirAll: item=6, err=<nil>
2018/08/02 07:37:30 DEBUG : /: Lookup: name="tc"
2018/08/02 07:37:30 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:30 DEBUG : /: Lookup: name="tc"
2018/08/02 07:37:30 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:30 DEBUG : /: Attr: 
2018/08/02 07:37:30 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:30 DEBUG : /: ReadDirAll: 
2018/08/02 07:37:30 DEBUG : /: >ReadDirAll: item=6, err=<nil>
2018/08/02 07:37:30 DEBUG : /: Lookup: name="tcp"
2018/08/02 07:37:30 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:30 DEBUG : /: Lookup: name="tcp"
2018/08/02 07:37:30 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:30 DEBUG : /: Attr: 
2018/08/02 07:37:30 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:30 DEBUG : /: ReadDirAll: 
2018/08/02 07:37:30 DEBUG : /: >ReadDirAll: item=6, err=<nil>
2018/08/02 07:37:30 DEBUG : /: Lookup: name="tcpp"
2018/08/02 07:37:30 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:30 DEBUG : /: Lookup: name="tcpp"
2018/08/02 07:37:30 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:30 DEBUG : /: Attr: 
2018/08/02 07:37:30 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:30 DEBUG : /: ReadDirAll: 
2018/08/02 07:37:30 DEBUG : /: >ReadDirAll: item=6, err=<nil>
2018/08/02 07:37:30 DEBUG : /: Lookup: name="tcpp"
2018/08/02 07:37:30 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:30 DEBUG : /: Lookup: name="tcpp"
2018/08/02 07:37:30 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:30 DEBUG : /: Attr: 
2018/08/02 07:37:30 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:30 DEBUG : /: Lookup: name="tcpp"
2018/08/02 07:37:30 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:30 DEBUG : /: Lookup: name="tcpp"
2018/08/02 07:37:30 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:31 DEBUG : /: Lookup: name="tcpp"
2018/08/02 07:37:31 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:31 DEBUG : /: Lookup: name="tcpp"
2018/08/02 07:37:31 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:31 DEBUG : /: Lookup: name="tcpp"
2018/08/02 07:37:31 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:31 DEBUG : /: Lookup: name="tcpp"
2018/08/02 07:37:31 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:31 DEBUG : /: ReadDirAll: 
2018/08/02 07:37:31 DEBUG : /: >ReadDirAll: item=6, err=<nil>
2018/08/02 07:37:31 DEBUG : /: Lookup: name="tcp"
2018/08/02 07:37:31 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:31 DEBUG : /: Lookup: name="tcp"
2018/08/02 07:37:31 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:31 DEBUG : /: Attr: 
2018/08/02 07:37:31 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:31 DEBUG : /: ReadDirAll: 
2018/08/02 07:37:31 DEBUG : /: >ReadDirAll: item=6, err=<nil>
2018/08/02 07:37:31 DEBUG : /: Lookup: name="tc"
2018/08/02 07:37:31 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:31 DEBUG : /: Lookup: name="tc"
2018/08/02 07:37:31 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:31 DEBUG : /: Attr: 
2018/08/02 07:37:31 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:31 DEBUG : /: ReadDirAll: 
2018/08/02 07:37:31 DEBUG : /: >ReadDirAll: item=6, err=<nil>
2018/08/02 07:37:31 DEBUG : /: Lookup: name="t"
2018/08/02 07:37:31 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:31 DEBUG : /: Lookup: name="t"
2018/08/02 07:37:31 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:31 DEBUG : /: Attr: 
2018/08/02 07:37:31 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:31 DEBUG : /: ReadDirAll: 
2018/08/02 07:37:31 DEBUG : /: >ReadDirAll: item=6, err=<nil>
2018/08/02 07:37:32 DEBUG : /: Lookup: name="t."
2018/08/02 07:37:32 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:32 DEBUG : /: Lookup: name="t."
2018/08/02 07:37:32 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:32 DEBUG : /: Attr: 
2018/08/02 07:37:32 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:32 DEBUG : /: ReadDirAll: 
2018/08/02 07:37:32 DEBUG : /: >ReadDirAll: item=6, err=<nil>
2018/08/02 07:37:32 DEBUG : /: Lookup: name="t.c"
2018/08/02 07:37:32 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:32 DEBUG : /: Lookup: name="t.c"
2018/08/02 07:37:32 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:32 DEBUG : /: Attr: 
2018/08/02 07:37:32 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:32 DEBUG : /: ReadDirAll: 
2018/08/02 07:37:32 DEBUG : /: >ReadDirAll: item=6, err=<nil>
2018/08/02 07:37:32 DEBUG : /: Lookup: name="t.cp"
2018/08/02 07:37:32 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:32 DEBUG : /: Lookup: name="t.cp"
2018/08/02 07:37:32 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:32 DEBUG : /: Attr: 
2018/08/02 07:37:32 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:32 DEBUG : /: ReadDirAll: 
2018/08/02 07:37:32 DEBUG : /: >ReadDirAll: item=6, err=<nil>
2018/08/02 07:37:32 DEBUG : /: Lookup: name="t.cpp"
2018/08/02 07:37:32 DEBUG : /: >Lookup: node=t.cpp, err=<nil>
2018/08/02 07:37:32 DEBUG : t.cpp: Attr: 
2018/08/02 07:37:32 DEBUG : t.cpp: >Attr: a=valid=1s ino=0 size=118 mode=-rw-r--r--, err=<nil>
2018/08/02 07:37:33 DEBUG : /: Lookup: name="t.cpp"
2018/08/02 07:37:33 DEBUG : /: >Lookup: node=t.cpp, err=<nil>
2018/08/02 07:37:33 DEBUG : t.cpp: Attr: 
2018/08/02 07:37:33 DEBUG : t.cpp: >Attr: a=valid=1s ino=0 size=118 mode=-rw-r--r--, err=<nil>
2018/08/02 07:37:33 DEBUG : /: Lookup: name="t.cpp"
2018/08/02 07:37:33 DEBUG : /: >Lookup: node=t.cpp, err=<nil>
2018/08/02 07:37:33 DEBUG : t.cpp: Attr: 
2018/08/02 07:37:33 DEBUG : t.cpp: >Attr: a=valid=1s ino=0 size=118 mode=-rw-r--r--, err=<nil>
2018/08/02 07:37:34 DEBUG : /: Lookup: name="t"
2018/08/02 07:37:34 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:34 DEBUG : /: Lookup: name="t"
2018/08/02 07:37:34 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:34 DEBUG : /: Attr: 
2018/08/02 07:37:34 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:34 DEBUG : /: ReadDirAll: 
2018/08/02 07:37:34 DEBUG : /: >ReadDirAll: item=6, err=<nil>
2018/08/02 07:37:36 DEBUG : /: Lookup: name="t.cpp"
2018/08/02 07:37:36 DEBUG : /: >Lookup: node=t.cpp, err=<nil>
2018/08/02 07:37:36 DEBUG : t.cpp: Attr: 
2018/08/02 07:37:36 DEBUG : t.cpp: >Attr: a=valid=1s ino=0 size=118 mode=-rw-r--r--, err=<nil>
2018/08/02 07:37:36 DEBUG : /: Lookup: name="t.cpp"
2018/08/02 07:37:36 DEBUG : /: >Lookup: node=t.cpp, err=<nil>
2018/08/02 07:37:36 DEBUG : t.cpp: Attr: 
2018/08/02 07:37:36 DEBUG : t.cpp: >Attr: a=valid=1s ino=0 size=118 mode=-rw-r--r--, err=<nil>
2018/08/02 07:37:36 DEBUG : /: Lookup: name="t"
2018/08/02 07:37:36 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:36 DEBUG : /: Lookup: name="t"
2018/08/02 07:37:36 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:36 DEBUG : /: Attr: 
2018/08/02 07:37:36 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:36 DEBUG : /: Lookup: name="t"
2018/08/02 07:37:36 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:36 DEBUG : /: Lookup: name="t.cpp.gch"
2018/08/02 07:37:36 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:36 DEBUG : t.cpp: Open: flags=OpenReadOnly
2018/08/02 07:37:36 DEBUG : t.cpp: Open: flags=O_RDONLY
2018/08/02 07:37:36 DEBUG : t.cpp: >Open: fd=t.cpp (r), err=<nil>
2018/08/02 07:37:36 DEBUG : t.cpp: >Open: fh=&{t.cpp (r)}, err=<nil>
2018/08/02 07:37:36 DEBUG : &{t.cpp (r)}: Read: len=4096, offset=0
2018/08/02 07:37:36 DEBUG : t.cpp: ChunkedReader.openRange at 0 length -1
2018/08/02 07:37:36 DEBUG : t.cpp: ChunkedReader.Read at 0 length 4096 chunkOffset 0 chunkSize -1
2018/08/02 07:37:36 DEBUG : &{t.cpp (r)}: >Read: read=118, err=<nil>
2018/08/02 07:37:36 DEBUG : &{t.cpp (r)}: Flush: 
2018/08/02 07:37:36 DEBUG : &{t.cpp (r)}: >Flush: err=<nil>
2018/08/02 07:37:36 DEBUG : &{t.cpp (r)}: Release: 
2018/08/02 07:37:36 DEBUG : t.cpp: ReadFileHandle.Release closing
2018/08/02 07:37:36 DEBUG : &{t.cpp (r)}: >Release: err=<nil>
2018/08/02 07:37:36 DEBUG : t.cpp: Attr: 
2018/08/02 07:37:36 DEBUG : t.cpp: >Attr: a=valid=1s ino=0 size=118 mode=-rw-r--r--, err=<nil>
2018/08/02 07:37:37 DEBUG : /: Lookup: name="t"
2018/08/02 07:37:37 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:37 DEBUG : /: Lookup: name="t"
2018/08/02 07:37:37 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:37 DEBUG : /: Create: name="t"
2018/08/02 07:37:37 DEBUG : t: Open: flags=O_RDWR|O_CREATE|O_TRUNC
2018/08/02 07:37:37 DEBUG : t: >Open: fd=t (w), err=<nil>
2018/08/02 07:37:37 DEBUG : /: >Create: node=t, handle=&{t (w)}, err=<nil>
2018/08/02 07:37:37 DEBUG : t: Attr: 
2018/08/02 07:37:37 DEBUG : t: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
2018/08/02 07:37:37 DEBUG : /: Lookup: name="libgcc_s.so.1"
2018/08/02 07:37:37 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:37 DEBUG : /: Lookup: name="libgcc_s.so.1"
2018/08/02 07:37:37 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:37 DEBUG : &{t (w)}: Read: len=4096, offset=0
2018/08/02 07:37:37 ERROR : t: WriteFileHandle: ReadAt: Can't read and write to file without --vfs-cache-mode >= minimal
2018/08/02 07:37:37 DEBUG : &{t (w)}: >Read: read=0, err=operation not permitted
2018/08/02 07:37:37 DEBUG : &{t (w)}: Write: len=504, offset=64
2018/08/02 07:37:37 ERROR : t: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes
2018/08/02 07:37:37 DEBUG : &{t (w)}: >Write: written=0, err=illegal seek
2018/08/02 07:37:37 DEBUG : &{t (w)}: Flush: 
2018/08/02 07:37:37 DEBUG : t: WriteFileHandle.Flush unwritten handle, writing 0 bytes to avoid race conditions
2018/08/02 07:37:37 DEBUG : &{t (w)}: >Flush: err=<nil>
2018/08/02 07:37:37 DEBUG : &{t (w)}: Release: 
2018/08/02 07:37:37 DEBUG : t: WriteFileHandle.Release closing
2018/08/02 07:37:37 DEBUG : Google drive root '': File to upload is small (0 bytes), uploading instead of streaming
2018/08/02 07:37:37 DEBUG : t: Attr: 
2018/08/02 07:37:37 DEBUG : t: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
2018/08/02 07:37:37 DEBUG : /: Remove: name="t"
2018/08/02 07:37:37 DEBUG : /: >Remove: err=<nil>
2018/08/02 07:37:37 DEBUG : /: Attr: 
2018/08/02 07:37:37 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2018/08/02 07:37:37 DEBUG : /: Lookup: name="elf_x86_64.rpo"
2018/08/02 07:37:37 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:37 DEBUG : /: Lookup: name="t.rpo"
2018/08/02 07:37:37 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:37 DEBUG : /: Lookup: name=".git"
2018/08/02 07:37:37 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:37 DEBUG : /: Lookup: name=".git"
2018/08/02 07:37:37 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:37 DEBUG : /: Lookup: name="HEAD"
2018/08/02 07:37:37 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:37 DEBUG : /: Lookup: name=".git"
2018/08/02 07:37:37 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:37 DEBUG : /: Lookup: name=".git"
2018/08/02 07:37:37 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:37 DEBUG : /: Lookup: name="HEAD"
2018/08/02 07:37:37 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/08/02 07:37:39 INFO  : t: Copied (new)
2018/08/02 07:37:39 DEBUG : &{t (w)}: >Release: err=<nil>
</pre>
</details>

**Comment by ncw** [comment]
You'll need `--vfs-cache-mode writes` in order to make seeking work.

**Comment by F-TD5X** [comment]
And how to set ACL?

**Comment by ncw** [comment]
Rclone doesn't support ACL or permissions or ownership as these don't map well to cloud providers.  It will accept the calls but won't change anything.

In general rclone tries to present you with a close to the provider as possible view of your cloud storage.

**Comment by animosity22** [comment]
This looks to be answered. If you still have a question, please post in the forums and we are happy to help out.
