### ISSUE TITLE
Failed to upload file to sharepoint(webdav) via Windows 10 webdav client

### ISSUE THREAD

**Issue by xiaolei0125** [rclone/rclone#2441]
There is issue that can't upload file between "rclone serve webdav" and windows 10 webclient(a built-in map network driver as webdav client).  
    But  some other webdav client  I have tested, are work fine with rclone serve webdav(sharepoint). 
   I am not sure if this is a problem with rclone serve webdav,  maybe windows 10 webclient's problem.

**Steps to reproduce:** 
1. Run "rclone serve webdav  mysharepoint:doc/" for sharepoint(webdav) remote.
2. Then use windows 10 webclient(a built-in map network driver as webdav client) to mount webdav server.
3.  Then upload a file to windows webdav client,  it's failed.

**Debug Detail:**
Run "rclone serve webdav --vfs-cache-mode writes od1:song/ " as a webdav server, 
Then map network driver(webdav)  in windows 10,  upload file to sharepoint failed: 
```
DEBUG : webdav root '': File to upload is small (0 bytes), uploading instead of streaming
DEBUG : HTTP REQUEST (req 0xc420660c00)
DEBUG : PUT /personal/xxx_xxx_edu/Documents/song/my.mp3 HTTP/1.1
Host: xxx-my.sharepoint.com
Content-Length: 0
DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<
DEBUG : HTTP RESPONSE (req 0xc420660c00)
DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked  
```
I test and found use "Content-Length: 0" in PUT header to sharepoint, sharepoint just reponse "200 OK" and not really creating a file, then use PROPFIND for new uploaded file, sharepoint just reponse "404 NOT FOUND" .  
So what confuses me is why windows 10 webdav client cause "rclone serve webdav" can't get file size?    

But use Android webdav client(ES FileExplore or Solid Explore) with rclone serve webdav,  it upload file 
 to sharepoint success, and rclone serve webdav can get file size normally.
```
DEBUG : webdav root '': Target remote doesn't support streaming uploads, creating temporary local FS to spool file
DEBUG : my.mp3: Sizes identical
DEBUG : HTTP REQUEST (req 0xc4202d0400)
DEBUG : PUT /personal/xxx_xxx_edu/Documents/song/my.mp3 HTTP/1.1
Host: xxx-my.sharepoint.com
Content-Length: 3898990
DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
DEBUG : HTTP RESPONSE (req 0xc4202d0400)
DEBUG : HTTP/1.1 201 CREATED
```

So only use "Content-Length: size" with actual file size in PUT header, sharepoint will reponse "201 CREATED" and creating a file success.

**Comment by ncw** [comment]
I think this problem is to do with streaming files.

WebDAV doesn't support streaming - you need to know the size of the file in advance.

So for your Android webdav client you see

> Target remote doesn't support streaming uploads, creating temporary local FS to spool file

And everything works fine.

However using it through the windows network driver we see

> File to upload is small (0 bytes), uploading instead of streaming

So it has uploaded a 0 length file instead.

So why does that happen?

Does it work if you serve a local directory

    rclone -vv serve webdav --vfs-cache-mode writes c:\path\to\dir

If it does can you send a log file and we can see exactly what windows is doing.

**Comment by xiaolei0125** [comment]
@ncw Thanks for you reply.

Run serve webdav for local directory:
```
root@vdc:~# rclone -vv serve webdav --addr :85 --vfs-cache-mode writes --cache-dir ./webdav-cache /root/webdav-data
```
copy file You.mp3(4.53M)  to windows network driver(webdav client),  it's success.  this is detail log: 
[rclone_serve_webdav_local.txt](https://github.com/ncw/rclone/files/2265646/rclone_serve_webdav_local.txt)


Run serve webdav for remote  od1(sharepoint):
```
root@vdc:~# rclone -vv serve webdav --addr :85 --vfs-cache-mode writes --cache-dir ./webdav-cache od1:
```
copy file You.mp3(4.53M)  to windows network driver(webdav client),  it's failed.  this is detail log: 
[rclone_serve_webdav_sharepoint.txt](https://github.com/ncw/rclone/files/2265647/rclone_serve_webdav_sharepoint.txt)

**Comment by xiaolei0125** [comment]
@ncw  I also test rclone serve webdav for another remote JianGuoYun.
[JianGuoYun](https://www.jianguoyun.com/) is a cloud storage which support webdav.


Run "rclone --dump headers --log-level DEBUG serve webdav --addr :85 --vfs-cache-mode writes --cache-dir ./webdav-cache JianGuoYun:
Then map windows network driver as webdav client, copy a file debug.log(4k) to it and success.
```
2018/08/07 15:57:24 DEBUG : HTTP REQUEST (req 0xc4203e0d00)
2018/08/07 15:57:24 DEBUG : PUT /dav/Work-IT/debug.log HTTP/1.1
Host: dav.jianguoyun.com
User-Agent: rclone/v1.42-066-g1f3778dbβ
Content-Length: 0
Authorization: XXXX
2018/08/07 15:57:24 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/07 15:57:24 DEBUG : HTTP RESPONSE (req 0xc4203e0d00)
2018/08/07 15:57:24 DEBUG : HTTP/1.1 201 Created
Content-Length: 0
Cache-Control: no-cache
Connection: keep-alive
```

So for JianGuoYun(webdav server), use "Content-Length: 0" in PUT header, JianGuoYun will reponse "201 CREATED" and creating a file success.
But for Sharepoint,  "Content-Length: size" in PUT header must be set actual file size to succeed，otherwise it will reponse "200 OK" and not really to create a file

**Comment by xiaolei0125** [comment]
@ncw  yes,  it's failed to upload a 0 length file with rclone to sharepoint.
I have use rclone copy  a zero length file to sharepoint and it's have same problem as rclone serve webdav.

Created a zero file named zero-file.txt,  then run "rclone --dump headers --log-level DEBUG --retries=1 copy zero-file.txt  od1:"
```
......
2018/08/08 09:04:33 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/08 09:04:33 DEBUG : zero-file.txt: Couldn't find file - need to transfer
2018/08/08 09:04:33 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/08/08 09:04:33 DEBUG : HTTP REQUEST (req 0xc0424cc200)
2018/08/08 09:04:33 DEBUG : PUT /personal/xxx_edu/Documents/zero-file.txt HTTP/1.1
Host: xxx-my.sharepoint.com
User-Agent: rclone/v1.42-066-g1f3778db
Content-Length: 0
Cookie: xxx
Accept-Encoding: gzip
2018/08/08 09:04:34 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/08 09:04:34 DEBUG : HTTP RESPONSE (req 0xc0424cc200)
2018/08/08 09:04:34 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: text/html; charset=windows-1252
Date: Wed, 08 Aug 2018 01:04:37 GMT
X-Msedge-Ref: Ref A: AF254CF267AD4BB0B8D7CCD9F9A9723A Ref B: HK2EDGE0112 Ref C: 2018-08-08T01:04:37Z
2018/08/08 09:04:34 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/08/08 09:04:34 DEBUG : HTTP REQUEST (req 0xc0424cc000)
2018/08/08 09:04:34 DEBUG : PROPFIND /personal/xxx_edu/Documents/zero-file.txt HTTP/1.1
Host: xxx-my.sharepoint.com
User-Agent: rclone/v1.42-066-g1f3778db
Cookie: xxx
Depth: 1
Accept-Encoding: gzip

2018/08/08 09:04:34 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2018/08/08 09:04:34 DEBUG : HTTP REQUEST (req 0xc0424cc000)
2018/08/08 09:04:34 DEBUG : PROPFIND /personal/xxx_edu/Documents/zero-file.txt HTTP/1.1
Host: xxx-my.sharepoint.com
User-Agent: rclone/v1.42-066-g1f3778db
Cookie: xxx
Depth: 0
Accept-Encoding: gzip
2018/08/08 09:04:35 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/08 09:04:35 DEBUG : HTTP RESPONSE (req 0xc0424cc000)
2018/08/08 09:04:35 DEBUG : HTTP/1.1 404 NOT FOUND
Accept-Ranges: bytes

2018/08/08 09:04:35 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2018/08/08 09:04:35 ERROR : zero-file.txt: Failed to copy: object not found
2018/08/08 09:04:35 ERROR : Attempt 1/1 failed with 1 errors and: object not found
2018/08/08 09:04:35 Failed to copy: object not found
```

**Comment by ncw** [comment]
@xiaolei0125 thanks for that.  It looks like that not being able to upload 0 length files is the underlying problem...

Did the file actually appear in sharepoint do you know?

Can anything else upload 0 length files to sharepoint via WebDAV?  If so can we see what they do?

You'll see various other providers have problems uploading 0 length files too if you trawl the rclone source code.

**Comment by xiaolei0125** [comment]
@ncw using ```rclone -vv copy zero-file.txt od1:test/```,   0 length file actually not appear in sharepoint, I have login to sharepoint web to confirm this.

I try to upload a  0 length file from sharepoint web, it's also failed, and said "Sorry, OneDrive cannot upload folders or empty files".

I'm not found any other webdav client to test sharepoint with 0 length files,  since sharepoint using cookie to authorization, not using user password which supported by other most webdav clients.

**Comment by ncw** [comment]
> "Sorry, OneDrive cannot upload folders or empty files".

That seems fairly definitive.  However OneDrive itself can store 0 length files just fine.

We'll have to attack the problem from the other end.

Looking back at your logs `rclone serve webdav local`

This is the problem part

```
2018/08/07 15:28:00 DEBUG : /You.mp3: OpenFile: flags=578, perm=-rw-rw-rw-
2018/08/07 15:28:00 DEBUG : /You.mp3: OpenFile: flags=O_RDWR|O_CREATE|O_TRUNC, perm=-rw-rw-rw-
2018/08/07 15:28:00 DEBUG : You.mp3: Open: flags=O_RDWR|O_CREATE|O_TRUNC
2018/08/07 15:28:00 DEBUG : You.mp3(0xc42007ca80): Opening cached copy with flags=O_RDWR|O_CREATE|O_TRUNC
2018/08/07 15:28:00 DEBUG : You.mp3: >Open: fd=You.mp3 (rw), err=<nil>
2018/08/07 15:28:00 DEBUG : /You.mp3: >OpenFile: fd=You.mp3 (rw), err=<nil>
2018/08/07 15:28:00 DEBUG : /You.mp3: >OpenFile: err = <nil>
2018/08/07 15:28:00 DEBUG : You.mp3(0xc42007ca80): close: 
2018/08/07 15:28:00 DEBUG : You.mp3: Couldn't find file - need to transfer
2018/08/07 15:28:00 INFO  : You.mp3: Copied (new)
2018/08/07 15:28:00 DEBUG : You.mp3: transferred to remote
2018/08/07 15:28:00 DEBUG : You.mp3(0xc42007ca80): >close: err=<nil>
```

This is truncating any existing file - this creates the 0 length file.

Can you stop the client doing that?  Stop it truncating the file before uploading a new one?

**Comment by xiaolei0125** [comment]
@ncw   

> Can you stop the client doing that? Stop it truncating the file before uploading a new one?
> 
What do you mean by the client，rclone or windows network driver(webdav client)?  
I don't know how to stop it truncating file before uploading.

**Comment by ncw** [comment]
> windows network driver(webdav client)? I don't know how to stop it truncating file before uploading.

I meant the windows network driver.  Maybe it has a config setting or something?

**Comment by xiaolei0125** [comment]
@ncw  I have looked for some places where Windows WebClient can be configured, such as regedit(\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WebClient\Parameters),  but I didn't find any useful configuration for truncating.

I am using Cyberduck  or CrossFTP tools now, which can't mount webdav as windows network driver, but can upload or download file with `rclone serve webdav sharepoint:`

**Comment by ncw** [comment]
I can't think of anything else to try at the moment :-(  So I'm going to mark this as a Known Issue and hope someone has some inspiration later!

**Comment by ivandeex** [comment]
@xiaolei0125 This problem is reported against obsolete rclone version. Can you reproduce it with rclone 1.54?

**Comment by ivandeex** [comment]
Closing stale tickets.
