### ISSUE TITLE
Failed to configure token for dropbox (with proxy)

### ISSUE THREAD

**Issue by kitsunesora** [rclone/rclone#2444]
#### What is the problem you are having with rclone?

When i try create new remote with dropbox, i get «Failed to configure token: failed to get token: Post https://api.dropboxapi.com/1/oauth2/token: proxyconnect tcp: tls: oversized record received with length 20527». Variables https_proxy & HTTPS_PROXY are set properly. Native dropbox client works fine.

#### What is your rclone version (eg output from `rclone -V`)

v1.42 & v1.42-067-gffd11662β

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.04.5, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Dropbox

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone config

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2018/08/06 13:37:27 DEBUG : Starting auth server on 127.0.0.1:53682
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth
Log in and authorize rclone for access
Waiting for code...
2018/08/06 13:37:33 DEBUG : Received request on auth server
2018/08/06 13:37:33 DEBUG : Successfully got code
Got code
2018/08/06 13:37:33 DEBUG : Closing auth server
2018/08/06 13:37:33 DEBUG : Closed auth server with error: accept tcp 127.0.0.1:53682: use of closed network connection
2018/08/06 13:37:33 Failed to configure token: failed to get token: Post https://api.dropboxapi.com/1/oauth2/token: proxyconnect tcp: tls: oversized record received with length 20527

**Comment by ncw** [comment]
> tls: oversized record received with length 20527

A bit of googling reveals that this is the go runtime thinking it is connecting to an https: server but actually connecting to an http: server.

So I suspect something up with the proxy settings or rclone's interpretation of them.

It might be worth getting wireshark out and seeing what the servier is actually sending back (likely unencrypted HTML) and see if that gives you a clue.

Also running with `-vv --dump bodies` may give you a clue also.

**Comment by kitsunesora** [comment]
So, rclone understand only when proxy setting is set as «domain:port» without «https://», but now with this setting (without «https://») other applications don't work. :((

**Comment by kitsunesora** [comment]
So, rclone understand only when proxy setting is set as «domain:port» without «https://», but now with this setting (without «https://») other applications don't work. :((

**Comment by ncw** [comment]
Here are the docs on [how the go runtime uses the proxy variable](https://golang.org/pkg/net/http/#ProxyFromEnvironment).

Are you saying you got it to work with `domain:port`?

Which environment variables are you setting - can you show their values?

**Comment by kitsunesora** [comment]
In `/etc/environment`:
```
http_proxy="http://proxy.festu.khv.ru:3128"
https_proxy="proxy.festu.khv.ru:3128"
```

Dropbox native client works only with http_proxy containing «http://», and Rclone receive dropbox token only with https_proxy without «https://».

**Comment by ncw** [comment]
According to the docs

I think

```
http_proxy="proxy.festu.khv.ru:3128"
https_proxy="proxy.festu.khv.ru:3128"
```
 or 

```
http_proxy="http://proxy.festu.khv.ru:3128"
https_proxy="http://proxy.festu.khv.ru:3128"
```

should be equivalent and both work.

**Comment by animosity22** [comment]
Solved via the proxy settings. If you still have an issue, please feel free to ask in the forums.

**Comment by walknotes** [comment]
> In `/etc/environment`:
> 
> ```
> http_proxy="http://proxy.festu.khv.ru:3128"
> https_proxy="proxy.festu.khv.ru:3128"
> ```
> 
> Dropbox native client works only with http_proxy containing «http://», and Rclone receive dropbox token only with https_proxy without «https://».

HTTPS_PROXY=bla bla
capital letter, that matters.
