### ISSUE TITLE
"Object not found" error when performing cloud to cloud copy

### ISSUE THREAD

**Issue by tekdubz** [rclone/rclone#2454]
#### What is the problem you are having with rclone?
I'm trying to copy files from a Swift Bucket to an S3 compatible bucket

#### What is your rclone version (eg output from `rclone -V`)
rclone V1.42

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04 / 64bits

####  Which cloud storage system are you using? (eg Google Drive)

Source : Swift
Destination : S3 compatible

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync remotesrc:folder/subfolder remotedest:folder/subfolder

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2018/08/09 09:27:38 DEBUG : CBB_Exchange/aaxm.alyotech.fr/af.users/data/af.users.edb:/20180701160058/61.cbrevision!CB_EB7A645290604987A8593CF7224B6A3D_000183: Unchanged skipping
2018/08/09 09:27:38 DEBUG : CBB_Exchange/aaxm.alyotech.fr/af.users/data/af.users.edb:/20180701160058/full.cbbitmap: Size and modification time the same (differ by 0s, within tolerance 1ns)
2018/08/09 09:27:38 DEBUG : CBB_Exchange/aaxm.alyotech.fr/af.users/data/af.users.edb:/20180701160058/full.cbbitmap: Unchanged skipping
2018/08/09 09:27:38 INFO  : S3 bucket scalian-paris-warm path MBS-87d95459-d984-40f3-b824-f816169b6726/CBB_AAXM/: Waiting for transfers to finish
2018/08/09 09:27:38 DEBUG : S3 bucket scalian-paris-warm path MBS-87d95459-d984-40f3-b824-f816169b6726/CBB_AAXM/: failed to copy 19 directories
2018/08/09 09:27:38 DEBUG : S3 bucket scalian-paris-warm path MBS-87d95459-d984-40f3-b824-f816169b6726/CBB_AAXM/: copied 1 directories
2018/08/09 09:27:38 ERROR : S3 bucket scalian-paris-warm path MBS-87d95459-d984-40f3-b824-f816169b6726/CBB_AAXM/: not deleting files as there were IO errors
2018/08/09 09:27:38 ERROR : S3 bucket scalian-paris-warm path MBS-87d95459-d984-40f3-b824-f816169b6726/CBB_AAXM/: not deleting directories as there were IO errors
2018/08/09 09:27:38 ERROR : Attempt 3/3 failed with 19 errors and: failed to open source object: Object Not Found
2018/08/09 09:27:38 Failed to sync: failed to open source object: Object Not Found

#### Additionnal information
As you can see, some files are transfered correctly while some encounter errors, and after 3 failed attempt it just stop the copy (I tried the ---ignore-errors flag to see if it would continue copying but no luck)

For the context, we have our clients data in a Swift Bucket, and we try to transfer them to an S3 compatible bucket, each command is supposed to copy the files from a backup of one of their machines.
Some machines do work without any problem, but sometimes (probably due to the type of backup used and the resulting type of files) it fails to sync.

**Comment by ncw** [comment]
Do you think you could post a complete log?  Maybe zip it and attach it here?  I can't quite see what is going on with what you've posted - thanks.

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
