### ISSUE TITLE
Changing rclone logs to easily parsable format by Logstash and Splunk (structured logging)

### ISSUE THREAD

**Issue by mdahal** [rclone/rclone#2459]
#### What is the problem you are having with rclone?
Rather than looking at a log file I am trying to implement a "Dashboard" where I can get all the information. Currently it is a bit difficult to parse rclone logs as it is not in a standardised. I would like to propose having logs in this format.

FileLog: Filename=<filename> Action=<Copied/Moved/Skiped/Sending-Chunks> Description=<"Copied New"/"Skipped as src and dst objects identical"/"Moved Server Side as object does not exist in src" 
StatusLog: Status=<"Rate limited"/"Low-Level-Retry"/"Resetting-Sleep"/"Saved-New-Token"> Reason=<"Rate Limited, sleeping for 2.58s (2 consecutive low lelvel retries"/ "low level retry error googleapi: Error 403 Rate Limited " /"Saved new token in config file" 

StatsLog: TotalCopied=<Size> Totalruntime =<runtime>  ETC.

I would like to suggest having new command --syslog-parsable for not affecting current functionality.

#### What is your rclone version (eg output from `rclone -V`)
1.42

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian 9

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -c -v sync /media/HD unicrypt:/Backups/  --backup-dir unicrypt:/old/ --suffix="-date-$(date)" --copy-links  --syslog

**Comment by ncw** [comment]
An interesting idea.  I'd prefer to follow some sort of standard (or an example from another well known program which does this) - can you fine one?

**Comment by dlong500** [comment]
In the longer term moving to a logging framework like logrus (as mentioned in #2453) would automatically resolve this issue, as that is compatible with both logstash and Splunk (along with a variety of other formatters).

**Comment by mdahal** [comment]
Looking at logrus. It appears to be an excellent solution.

**Comment by ncw** [comment]
Would either of you like to help implement logrus in rclone?

**Comment by mdahal** [comment]
It's been almost 10 years since I had done some coding. But I am definitely up for challenge. If you could give me some guidance.

**Comment by ncw** [comment]
@mdahal great!  Your first challenge is [build rclone from source](https://rclone.org/install/#install-from-source) and get used to go.  Let me know what help you need after that!

**Comment by kslr** [comment]
hi mdahal

Are you making progress now?

**Comment by wanderleihuttel** [comment]
Would be interesting also have an option to show bytes WITH and WITHOUT unit, and not only for transfer rate, but the file size. With this would be possible to sum the amount data transferred and show in scripts for example.

Below I have an example of manual execution
And more below, a table with file sizes with/without units conversion.
![image](https://user-images.githubusercontent.com/16232272/63109308-4318ae00-bf5f-11e9-83b9-0e15a1afef70.png)

**Comment by kir4h** [comment]
> Would be interesting also have an option to show bytes WITH and WITHOUT unit, and not only for transfer rate, but the file size. With this would be possible to sum the amount data transferred and show in scripts for example.
> 
> Below I have an example of manual execution
> And more below, a table with file sizes with/without units conversion.
> ![image](https://user-images.githubusercontent.com/16232272/63109308-4318ae00-bf5f-11e9-83b9-0e15a1afef70.png)

I was actually trying to figure out if there is a way of achieving so. My goal would be reading that value  and then feeding it to grafana for instance without further post-processing. I understand from your comment this is currently implemented right?

If so, @ncw , would you be open to this? (having the option of printing raw bits/bytes without converting them to a human readable format. Or maybe just printing both, "Transferred: xxMB (xx*1024*1024 bytes))

**Comment by ncw** [comment]
Rclone has the [--use-json-log](https://rclone.org/docs/#use-json-log) flag which makes all the logs into JSON format.

The stats logs look like this

```
{"level":"info","msg":"\nTransferred:   \t         0 / 0 Bytes, -, 0 Bytes/s, ETA -\nElapsed time:          0s\n\n","source":"accounting/stats.go:368","time":"2020-01-24T13:33:18.234392+00:00"}
```

Which isn't ideal - it would be nice if they were easier to read.

However I think this issue is complete, so we should open a new one if we want to add more info to the stats logs.

Note that it may be easier to [read the stats info from the api](https://rclone.org/rc/#core/stats) also
