### ISSUE TITLE
Feature Request: Write-through caching for --vfs-cache-mode=writes in order to slow writes while allowing retries

### ISSUE THREAD

**Issue by eatnumber1** [rclone/rclone#2482]
Hey,

In my use case of rclone, I'm using a torrent client ([Transmission](https://transmissionbt.com/)) on a machine with a small amount of local disk. I locally mount rclone using the following (I'm not omitting any flags, just in case they turn out to be relevant):

```
rclone mount \
    --config=/etc/rclone/torrents-mount.conf \
    --vfs-cache-mode=writes \
    --cache-writes \
    --cache-chunk-no-memory \
    --cache-dir=/var/cache/rclone \
    --cache-db-path=/var/cache/rclone/cache-backend \
    --cache-chunk-path=/var/cache/rclone/cache-backend \
    --write-back-cache \
    --attr-timeout=1m \
    --dir-cache-time=10m \
    --umask=007 \
    --gid=998 \
    --allow-other\
    --default-permissions \
    --rc \
    --fast-list \
    -vvvvvv \
    gdrive-torrents:/ \
    /mnt/torrents
```

What I'm seeing is that Transmission frequently locks up while rclone is logging thousands of lines of
```
DEBUG : /path/to/file.part: Sending chunk 1518338048 length 8388608
```

What I think is happening is that because I have `--vfs-cache-mode=writes`, when downloading a torrent the writes get [write-back](https://en.wikipedia.org/wiki/Cache_(computing)#Writing_policies) cached to disk until the call to [`close(2)`](http://man7.org/linux/man-pages/man2/close.2.html), at which point the close operation flushes the cache. Because the file is large, the close then takes tens of minutes to complete. My assumption is that Transmission is not designed for `close` to take a long time, so it does it on its main thread. This results in Transmission locking up.

So, after some thought, I think this could be fixed by adding a new cache mode: `--vfs-cache-mode=writes,write-through` which will cause every [`write(2)`](http://man7.org/linux/man-pages/man2/write.2.html) to _both_ write to disk and upload the chunk synchronously before returning. Or maybe not _every_ write; it could batch it into chunks to upload of a bounded size, but not the entire file. This would result in slowing down the writing application so it does not fill the disk with files to upload, allows `close` to be fast, and allows us to have an on-disk backup of un-uploaded chunks just in case the first upload fails and we need to try again (which we would also do synchronously).

In general, my understanding is that applications expect `write` to be slow, but don't generally expect `close` to be. If I'm right, this proposed behavior would therefore make rclone behave more appropriately in order to preserve interactivity for many applications, including Transmission.

An aside, I can't _not_ use `--vfs-cache-mode=writes`, because Transmission seeks within the written file in order to verify downloaded chunks. I also don't think I can use [`--cache-tmp-upload-path`](https://rclone.org/cache/#offline-uploading) because that doesn't seem to have an upper bound on size, so will fill my disk quickly when I download a torrent.

**Comment by ncw** [comment]
> My assumption is that Transmission is not designed for close to take a long time, so it does it on its main thread. This results in Transmission locking up.

That sounds quite plausible to me.

> So, after some thought, I think this could be fixed by adding a new cache mode: --vfs-cache-mode=writes,write-through which will cause every write(2) to both write to disk and upload the chunk synchronously before returning. Or maybe not every write; it could batch it into chunks to upload of a bounded size, but not the entire file. This would result in slowing down the writing application so it does not fill the disk with files to upload, allows close to be fast, and allows us to have an on-disk backup of un-uploaded chunks just in case the first upload fails and we need to try again (which we would also do synchronously).

The main problem with this idea is that most the cloud storage systems only let you upload a complete object and only 1 of them (swift) allows changing parts of an already written object. So rclone has to wait until the end before uploading it.  If transmission seeks about the file (which I think it does) then uploading any of it will be wasted work.

So I think what you want is write-back caching.

So rclone writes to the temp file as normal, but when it is closed it uploads it asynchronously.  So `close(2)` returns immediately with no error but rclone uploads the file in the background.

Rclone can retry the file if it fails, but if all the retries fail then the upload will fail and the application won't be notified - that is the disadvantage of write-back caching.

The vfs-cache should probably have a mechanism for continuing to retry uploads in that case.

One area of possible complexity is that once the file has been closed and upload has started what should rclone do if the file is opened again?  The obvious thing to do would be to block until the file has been uploaded.

**Comment by eatnumber1** [comment]
> > So, after some thought, I think this could be fixed by adding a new cache mode: --vfs-cache-mode=writes,write-through which will cause every write(2) to both write to disk and upload the chunk synchronously before returning. Or maybe not every write; it could batch it into chunks to upload of a bounded size, but not the entire file. This would result in slowing down the writing application so it does not fill the disk with files to upload, allows close to be fast, and allows us to have an on-disk backup of un-uploaded chunks just in case the first upload fails and we need to try again (which we would also do synchronously).
> 
> The main problem with this idea is that most the cloud storage systems only let you upload a complete object and only 1 of them (swift) allows changing parts of an already written object. So rclone has to wait until the end before uploading it. If transmission seeks about the file (which I think it does) then uploading any of it will be wasted work.

Hmm, interesting. For a consecutively written file, you don't actually need the whole file, you just need to make sure that you never have a buffer underrun long enough to get a connection timeout. You could do that by slowing the upload to match the speed at which the file is written to.

In the case of Transmission though where it's seeking around the file, then agreed, uploading at all is wasted work.

> So I think what you want is write-back caching.
> 
> So rclone writes to the temp file as normal, but when it is closed it uploads it asynchronously. So close(2) returns immediately with no error but rclone uploads the file in the background.

If we were to do some form of write-back caching, remember that I'm on a small disk. There needs to be a mechanism by which Transmission's writes are slowed down so we don't fill the disk with pending uploads. One thing that could be done is to tightly bound the number of files that are allowed to be pending, slowing writes (and only writes) of new files when the buffer fills.
 
> Rclone can retry the file if it fails, but if all the retries fail then the upload will fail and the application won't be notified - that is the disadvantage of write-back caching.
> 
> The vfs-cache should probably have a mechanism for continuing to retry uploads in that case.

Does it not already? I thought that's what `--vfs-cache-mode=writes` already did.

Also, looking at the Drive API docs now, are you sure that you can't upload a file in multiple non-sequential parts? Looking at the docs for [Resumable Upload -> Multiple Chunks](https://developers.google.com/drive/api/v3/resumable-upload), you can set a `Content-Range` header to specify both the start and end bytes of the chunk you are uploading. Does it not work if the uploaded ranges are non-consecutive?

One more possibility even if you can't upload non-consecutively would be to use a resumable upload, and upload consecutively as the next bytes of the file become available, blocking the resulting write until the upload is complete. For example:

If Transmission writes bytes 0 - 10, then 20 - 30, then 10 - 20, the write(0 - 10) would block until those bytes were uploaded, the write(20 - 30) would block only until those bytes were written to disk, and would not upload anything, then write(10 - 20) would block until bytes 10 - 30 were uploaded.

> One area of possible complexity is that once the file has been closed and upload has started what should rclone do if the file is opened again? The obvious thing to do would be to block until the file has been uploaded.

Why can't the reopened file be read from the vfs cache?

**Comment by ErAzOr2k** [comment]
I'm in the same situation as @eatnumber1 described. Some applications run into a timeout, because it takes to long to upload a file. That's the reason a made this feature request:
[](https://github.com/ncw/rclone/issues/2327)

Here I had the idea to set a delay by time. But I think a delay by some kind of "max-tmp-cache-size" would make more sense for you.

Regarding changing files that are actually uploading:
I think we would into other issues, if the file is blocked until fully uploaded. Would it be possible to to let changes happen on the tmp cache file and cancel the upload at the same time? The timer for the delay time should be resetted for that time.

**Comment by eatnumber1** [comment]
Ah, if a file is reopened for writing during an upload _and written to_ in a segment that's already been uploaded, then that's a problem. In that case, you could make a local copy of the file and upload the amended one once you were done uploading the old one.

I'd imagine that might be fairly complicated to implement, so it's gonna be up to @ncw as to what, if anything, gets done.

**Comment by ncw** [comment]
@ErAzOr2k wrote
> I think we would into other issues, if the file is blocked until fully uploaded. Would it be possible to to let changes happen on the tmp cache file and cancel the upload at the same time? The timer for the delay time should be resetted for that file.

Fully blocking the file until uploaded is the obvious thing to do.

Cancelling the upload would require re-working `context.Context` into rclone's interfaces (something I've been meaning to do) but that is a **lot** of work!

I'm willing to do the simple thing - allow the file to upload asynchronously and block if it is uploading.  That sounds plausible.

The problem with the VFS code is that it is very complicated...  You've probably heard the old programmer saying that it is twice as hard debugging code as writing it so if you write code as complex as you can understand you'll never be able to debug it?  Well I'm feeling I'm nearly there with the VFS layer ;-)

**Comment by ErAzOr2k** [comment]
Whar would it mean for applications trying to access that blocked file? What rclone just return an error, or does the application wait for rclone to be finished?

Would be great to test your suggested asynchronously upload.

**Comment by ncw** [comment]
> Whar would it mean for applications trying to access that blocked file? What rclone just return an error, or does the application wait for rclone to be finished?

The application would block is the way I would implement it.

> Would be great to test your suggested asynchronously upload.

:-)

**Comment by ncw** [comment]
I think this issue will be better served by async uploads #3186

**Comment by ClemTheStudent** [comment]
> Hey,
> 
> In my use case of rclone, I'm using a torrent client ([Transmission](https://transmissionbt.com/)) on a machine with a small amount of local disk. I locally mount rclone using the following (I'm not omitting any flags, just in case they turn out to be relevant):
> 
> ```
> rclone mount \
>     --config=/etc/rclone/torrents-mount.conf \
>     --vfs-cache-mode=writes \
>     --cache-writes \
>     --cache-chunk-no-memory \
>     --cache-dir=/var/cache/rclone \
>     --cache-db-path=/var/cache/rclone/cache-backend \
>     --cache-chunk-path=/var/cache/rclone/cache-backend \
>     --write-back-cache \
>     --attr-timeout=1m \
>     --dir-cache-time=10m \
>     --umask=007 \
>     --gid=998 \
>     --allow-other\
>     --default-permissions \
>     --rc \
>     --fast-list \
>     -vvvvvv \
>     gdrive-torrents:/ \
>     /mnt/torrents
> ```
> 
> What I'm seeing is that Transmission frequently locks up while rclone is logging thousands of lines of
> 
> ```
> DEBUG : /path/to/file.part: Sending chunk 1518338048 length 8388608
> ```
> 
> What I think is happening is that because I have `--vfs-cache-mode=writes`, when downloading a torrent the writes get [write-back](https://en.wikipedia.org/wiki/Cache_(computing)#Writing_policies) cached to disk until the call to [`close(2)`](http://man7.org/linux/man-pages/man2/close.2.html), at which point the close operation flushes the cache. Because the file is large, the close then takes tens of minutes to complete. My assumption is that Transmission is not designed for `close` to take a long time, so it does it on its main thread. This results in Transmission locking up.
> 
> So, after some thought, I think this could be fixed by adding a new cache mode: `--vfs-cache-mode=writes,write-through` which will cause every [`write(2)`](http://man7.org/linux/man-pages/man2/write.2.html) to _both_ write to disk and upload the chunk synchronously before returning. Or maybe not _every_ write; it could batch it into chunks to upload of a bounded size, but not the entire file. This would result in slowing down the writing application so it does not fill the disk with files to upload, allows `close` to be fast, and allows us to have an on-disk backup of un-uploaded chunks just in case the first upload fails and we need to try again (which we would also do synchronously).
> 
> In general, my understanding is that applications expect `write` to be slow, but don't generally expect `close` to be. If I'm right, this proposed behavior would therefore make rclone behave more appropriately in order to preserve interactivity for many applications, including Transmission.
> 
> An aside, I can't _not_ use `--vfs-cache-mode=writes`, because Transmission seeks within the written file in order to verify downloaded chunks. I also don't think I can use [`--cache-tmp-upload-path`](https://rclone.org/cache/#offline-uploading) because that doesn't seem to have an upper bound on size, so will fill my disk quickly when I download a torrent.

Did you find a solution to download torrents with low space? thx
