### ISSUE TITLE
Proxy authentication

### ISSUE THREAD

**Issue by johnwc** [rclone/rclone#2486]
I saw from #160 that we can set the proxy settings via env vars. How do we tell it the credentials if the proxy requires authentication?

**Comment by ky0nch3ng** [comment]
I suggest rclone use 0.0.0.0 as local listen port.

**Comment by johnwc** [comment]
Well I thought it was a proxy issue, it seems to not be though. This is the error, any thoughts?
2018/09/11 14:57:49 ERROR : : error reading destination directory: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
2018/09/11 14:57:49 ERROR : S3 bucket xxxxxxxx: not deleting files as there were IO errors
2018/09/11 14:57:49 ERROR : S3 bucket xxxxxxxx: not deleting directories as there were IO errors
2018/09/11 14:57:49 ERROR : Attempt 1/3 failed with 1 errors and: not deleting files as there were IO errors

**Comment by ncw** [comment]
@johnwc that looks like the config is incomplete?

Can you paste your config for that remote (XXX out any sensitive bits)?

**Comment by johnwc** [comment]
```
[aws_r]
type = s3
provider = AWS
env_auth = true
access_key_id = 
secret_access_key = 
region = us-east-1
endpoint = 
location_constraint = us-east-2
acl = private
server_side_encryption = AES256
storage_class = STANDARD
```

**Comment by ncw** [comment]
So you've got `env_auth = true` - so rclone will be looking for environment variables or a `~/.aws/credentials` file and it looks like it isn't finding them.

Which of those are you using?

The full auth stragegy is described here: https://rclone.org/s3/#authentication

**Comment by johnwc** [comment]
I am setting the env variable before hand, this works as expected on another machine.

**Comment by ncw** [comment]
If you unset the HTTP_PROXY and try again does it give the same error?

If it does then I think it must be your local config.

If you run with `-vv --dump bodies` it will show HTTP transactions rclone is doing.  I think if it gives "NoCredentialProviders: no valid providers in chain" then it won't have done any HTTP transactions at all.

I guess the other alternative is that somehow the HTTP_PROXY is interfering with the s3 sdk.  I has a brief play with this, but I couldn't get it to go wrong in the same way.

**Comment by ncw** [comment]
> What all do you want me to share out of the output?

Ideally yes.  Feel free to XXX out any bits that are confidential.

**Comment by johnwc** [comment]
I don't see any http requests.
```
C:\Users\li******sp\OneDrive - BP\Desktop\rclone-v1.42-windows-amd64>.\rclone.exe sync C:\Test\test\ aws_r:wu*****01 --buffer-size=104857600 --checksum --stats-unit=bits --transfers=9 --stats=10s --stats-log-level NOTICE -vv --dump bodies
2018/09/21 11:42:02 DEBUG : rclone: Version "v1.42-022-g03c5b823" starting with parameters [".\\rclone.exe" "sync" "C:\\Test\\test\\" "aws_r:wu*****01" "--buffer-size=104857600" "--checksum" "--stats-unit=bits" "--transfers=9" "--stats=10s" "--stats-log-level" "NOTICE" "-vv" "--dump" "bodies"]
2018/09/21 11:42:02 DEBUG : Using config file from "C:\\Users\\li******sp\\.config\\rclone\\rclone.conf"
2018/09/21 11:42:02 ERROR : : error reading destination directory: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
2018/09/21 11:42:02 INFO  : S3 bucket wu*****01: Waiting for checks to finish
2018/09/21 11:42:02 INFO  : S3 bucket wu*****01: Waiting for transfers to finish
2018/09/21 11:42:02 ERROR : S3 bucket wu*****01: not deleting files as there were IO errors
2018/09/21 11:42:02 ERROR : S3 bucket wu*****01: not deleting directories as there were IO errors
2018/09/21 11:42:02 ERROR : Attempt 1/3 failed with 1 errors and: not deleting files as there were IO errors
2018/09/21 11:42:03 ERROR : : error reading destination directory: NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by ncw** [comment]
> I don't see any http requests.

I'm pretty sure that must be your config that is the problem given that.

Which environment variables do you have set?

**Comment by ncw** [comment]
@johnwc what do you think the differences between the working server and the non-working server are?

All the errors point to the config, but there could be something else going wrong.

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
