### ISSUE TITLE
Listing files is too slow

### ISSUE THREAD

**Issue by cowwoc** [rclone/rclone#2502]
rclone 1.42
B2 server

By the looks of things, invoking `rclone ls <path>` iterates through the file list on the server one by one, listing paths that pass a certain filter. Unfortunately, this process is extremely slow for large backups.

I propose adding a centralized file list to be used as a cache. I understand this implies lock contention when multiple backups are running simultaneously but in most cases that will never be the case (e.g. my backups run nightly on a scheduler).

What do you think?

**Comment by ncw** [comment]
If you have enough memory for a full listing then use the `--fast-list` flag - that should fix the issue.

That is recommended to keep your costs down with B2 also.

**Comment by cowwoc** [comment]
`--fast-list` is much better and is probably good enough for most cases.

* Why isn't this on by default, especially if the machine has more than `X` RAM free?
* Would it be possible to return a more incremental result (a few hundred files at a time) instead of blocking until the full list is available? This would decrease memory usage and (more importantly) result in a more responsive behavior when enumerating a top-level directory. In the latter case, there is a high probability I will abort after seeing a couple of files.

**Comment by ncw** [comment]
> Why isn't this on by default, especially if the machine has more than X RAM free?

A good question.  It isn't always faster is one reason (especially if you set --checkers higher) and another is that I try not to make rclone use loads of memory by default.

> Would it be possible to return a more incremental result (a few hundred files at a time) instead of blocking until the full list is available? This would decrease memory usage 

For syncing Rclone needs all the files in a directory before it can start processing a directory and the way b2 listings work is that you don't know you've got all the files in the top level directory until the listing has finished.  Rclone needs to start in the top level directory first.

The listings are optimized for syncing, However the ordering constraints are irrelevant for `ls` so maybe you are right and these command should just return the raw output of --fast-list as it arrives and not buffer it in memory.

The raw output of some of the remotes will be quite strange which might confuse people I suppose!

Thoughts? Worth doing?

> and (more importantly) result in a more responsive behavior when enumerating a top-level directory. In the latter case, there is a high probability I will abort after seeing a couple of files.

I see.

**Comment by ncw** [comment]
There is a related issue here #2256

**Comment by cowwoc** [comment]
> maybe you are right and these command should just return the raw output of --fast-list as it arrives and not buffer it in memory.

This sounds like what I'm looking for.

> The raw output of some of the remotes will be quite strange which might confuse people I suppose!

Confuse how? Can you give an example of what kind of "strange" output we might get?

**Comment by ncw** [comment]
Just in a strange order, that's all.  So if you were to sort the output you'd get identical results each time.

**Comment by ncw** [comment]
That would depend on the backend.  For b2 for instance, you'll find you'll get all the files in order as if you'd done `find /dir . | sort`.  If you want sorted dirs then you need the current buffering rclone is doing.

**Comment by cowwoc** [comment]
Thanks for the clarification. I finally have a better understanding of what is going on.

Speaking for myself (maybe others disagree?) I would expect `ls` to return the file listing incrementally even if this means getting back unordered files, directories. My only expectation would be that I would get all the files from one directory before moving on to the next.

**Comment by ncw** [comment]
> Speaking for myself (maybe others disagree?) I would expect ls to return the file listing incrementally even if this means getting back unordered files, directories. My only expectation would be that I would get all the files from one directory before moving on to the next.

Those two constraints are satisfied without `--fast-list`.  With `--fast-list` we have to break one or the other.  Currently we break the "incremental" constraint.  If we don't buffer `--fast-list` then we'll break the "all the files from one directory" constraint.  I don't see a way around that!

**Comment by cowwoc** [comment]
@ncw Maybe I missed something, but `rclone ls <path>` doesn't seem to be incremental in spite of me omitting `--fast-list`. Or maybe it is incremental but it buffers quite a bit before the first line of output.

**Comment by ncw** [comment]
> Maybe I missed something, but rclone ls <path> doesn't seem to be incremental in spite of me omitting --fast-list. Or maybe it is incremental but it buffers quite a bit before the first line of output.

It is incremental but in quite large chunks of 1000 files or so.

**Comment by animosity22** [comment]
This looks to be answered. Closing out.
