### ISSUE TITLE
rclone dedupe creating more duplicates that then need to be deduped again

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#2512]
#### What is the problem you are having with rclone?

rclone dedupe is creating duplicates if the following situation is given:

file
file
file
file-1
file-2

So when rclone dedupe is being ran on that, this is what happens:

file
file-1
file-1
file-2
file-2

Naturally, this is silly. When I run dedupe again, this is what I get:

file
file-1
file-1-1
file-2
file-2-1

What rclone dedupe *should* do is this:

file
file-1
file-2
file-3
file-4

#### What is your rclone version (eg output from `rclone -V`)

rclone v1.42
- os/arch: openbsd/amd64
- go version: go1.10.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

OpenBSD

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone dedupe --dedupe-mode rename remote:

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

First run: rclone -vv dedupe --dedupe-mode rename gdrive:testfiles
         
2018/09/01 14:59:52 DEBUG : rclone: Version "v1.42" starting with parameters ["rclone" "-vv" "dedupe" "--dedupe-mode" "rename" "gdrive:testfiles"]
2018/09/01 14:59:52 DEBUG : Using config file from "/home/nrt/.config/rclone/rclone.conf"
2018/09/01 14:59:52 DEBUG : pacer: Rate limited, sleeping for 1.869441003s (1 consecutive low level retries)
2018/09/01 14:59:52 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 14:59:52 DEBUG : pacer: Rate limited, sleeping for 2.785122608s (2 consecutive low level retries)
2018/09/01 14:59:52 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 14:59:54 DEBUG : pacer: Rate limited, sleeping for 4.884547223s (3 consecutive low level retries)
2018/09/01 14:59:54 DEBUG : pacer: low level retry 3/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 14:59:57 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2018/09/01 14:59:57 INFO  : Google drive root 'testfiles': Looking for duplicates using rename mode.
2018/09/01 15:00:03 NOTICE: file: Found 3 duplicates - deleting identical copies
2018/09/01 15:00:03 INFO  : file-1: renamed from: file
2018/09/01 15:00:04 DEBUG : pacer: Rate limited, sleeping for 1.640210163s (1 consecutive low level retries)
2018/09/01 15:00:04 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 15:00:04 DEBUG : pacer: Rate limited, sleeping for 2.776655949s (2 consecutive low level retries)
2018/09/01 15:00:04 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 15:00:06 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2018/09/01 15:00:06 INFO  : file-2: renamed from: file
2018/09/01 15:00:11 INFO  : file-3: renamed from: file
2018/09/01 15:00:11 DEBUG : 4 go routines active
2018/09/01 15:00:11 DEBUG : rclone: Version "v1.42" finishing with parameters ["rclone" "-vv" "dedupe" "--dedupe-mode" "rename" "gdrive:testfiles"]

Second run: rclone -vv dedupe --dedupe-mode rename gdrive:testfiles

2018/09/01 15:01:10 DEBUG : rclone: Version "v1.42" starting with parameters ["rclone" "-vv" "dedupe" "--dedupe-mode" "rename" "gdrive:testfiles"]
2018/09/01 15:01:10 DEBUG : Using config file from "/home/nrt/.config/rclone/rclone.conf"
2018/09/01 15:01:11 INFO  : Google drive root 'testfiles': Looking for duplicates using rename mode.
2018/09/01 15:01:11 DEBUG : pacer: Rate limited, sleeping for 1.168642205s (1 consecutive low level retries)
2018/09/01 15:01:11 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 15:01:11 DEBUG : pacer: Rate limited, sleeping for 2.712690035s (2 consecutive low level retries)
2018/09/01 15:01:11 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 15:01:12 DEBUG : pacer: Rate limited, sleeping for 4.534932534s (3 consecutive low level retries)
2018/09/01 15:01:12 DEBUG : pacer: low level retry 3/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 15:01:15 DEBUG : pacer: Rate limited, sleeping for 8.763820527s (4 consecutive low level retries)
2018/09/01 15:01:15 DEBUG : pacer: low level retry 4/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 15:01:19 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2018/09/01 15:01:30 NOTICE: file-1: Found 2 duplicates - deleting identical copies
2018/09/01 15:01:31 DEBUG : pacer: Rate limited, sleeping for 1.512844089s (1 consecutive low level retries)
2018/09/01 15:01:31 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 15:01:31 DEBUG : pacer: Rate limited, sleeping for 2.449040475s (2 consecutive low level retries)
2018/09/01 15:01:31 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 15:01:33 DEBUG : pacer: Rate limited, sleeping for 4.983282711s (3 consecutive low level retries)
2018/09/01 15:01:33 DEBUG : pacer: low level retry 3/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 15:01:35 DEBUG : pacer: Rate limited, sleeping for 8.994125458s (4 consecutive low level retries)
2018/09/01 15:01:35 DEBUG : pacer: low level retry 4/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 15:01:41 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2018/09/01 15:01:41 INFO  : file-1-1: renamed from: file-1
2018/09/01 15:01:50 INFO  : file-1-2: renamed from: file-1
2018/09/01 15:01:50 NOTICE: file-2: Found 2 duplicates - deleting identical copies
2018/09/01 15:01:50 INFO  : file-2-1: renamed from: file-2
2018/09/01 15:01:50 DEBUG : pacer: Rate limited, sleeping for 1.455508442s (1 consecutive low level retries)
2018/09/01 15:01:50 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 15:01:51 DEBUG : pacer: Rate limited, sleeping for 2.414279284s (2 consecutive low level retries)
2018/09/01 15:01:51 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 15:01:52 DEBUG : pacer: Rate limited, sleeping for 4.435238775s (3 consecutive low level retries)
2018/09/01 15:01:52 DEBUG : pacer: low level retry 3/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 15:01:54 DEBUG : pacer: Rate limited, sleeping for 8.734559454s (4 consecutive low level retries)
2018/09/01 15:01:54 DEBUG : pacer: low level retry 4/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/09/01 15:01:59 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2018/09/01 15:01:59 INFO  : file-2-2: renamed from: file-2
2018/09/01 15:01:59 DEBUG : 5 go routines active
2018/09/01 15:01:59 DEBUG : rclone: Version "v1.42" finishing with parameters ["rclone" "-vv" "dedupe" "--dedupe-mode" "rename" "gdrive:testfiles"]

**Comment by ncw** [comment]
So what you are saying is that rclone dedupe's rename strategy of appending `-N` isn't working for you because you already have files called `-N` - is that right?

We could fix this by checking to see if the new file exists first - would that be good enough?  Or would you prefer an alternate rename strategy (say appending a random number)?

**Comment by ncw** [comment]
This shouldn't be too hard to fix

Here is where the files get renamed

https://github.com/ncw/rclone/blob/4ca26eb38cf9befdabc6b6a68a7a320fa247a21f/fs/operations/dedupe.go#L20-L43

When rclone makes `newName` it should check to see if the file exists with `f.NewObject(newName)` first and if not choose a different suffix.

**Comment by ivandeex** [comment]
@ghost This problem is reported against obsolete rclone version. Does it reproduce with rclone 1.54?

**Comment by ivandeex** [comment]
Closing stale requests.
