### ISSUE TITLE
rclone mount on mac issues with file name lengths

### ISSUE THREAD

**Issue by tcf909** [rclone/rclone#2537]
#### What is the problem you are having with rclone?
Using rclone mount on mac runs into problems when I copy a folder with in to a mount. The same folder copied from a linux machine in to the mount does not have a problem.

Mac finder displays the message "You can't copy the item 'XYZ.file' because its name is too long or includes characters that are invalid on the destination volume.

This is copying the latest wordpress.tar.gz install in to a folder.

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.43
- os/arch: darwin/amd64
- go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Mac 10.13.6

####  Which cloud storage system are you using? (eg Google Drive)
Google Cloud Storage

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -v  mount --allow-other --fast-list --dir-cache-time 15s --cache-dir /tmp/.rclone_cache --vfs-cache-mode full --vfs-cache-max-age 24h --low-level-retries 9999 WWW:digital-spaces-www-local/ digitalspaces.app/

(Also happens when not using VFS, as well if trying to use Cache to front the remote). 

It appears to be something to do with the Mac fuse implementation?

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
....(many more log entries for all file operations)...
2018/09/05 11:03:17 DEBUG : wp-includes/functions.php: File.applyPendingModTime OK
2018/09/05 11:03:17 DEBUG : wp-includes/functions.php: >Setattr: err=<nil>
2018/09/05 11:03:17 DEBUG : wp-includes/functions.php: Attr:
2018/09/05 11:03:17 DEBUG : wp-includes/functions.php: >Attr: a=valid=1s ino=0 size=187776 mode=-rw-r--r--, err=<nil>
2018/09/05 11:03:17 DEBUG : /: Lookup: name="wp-includes"
2018/09/05 11:03:17 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/09/05 11:03:17 DEBUG : /: Lookup: name="wp-includes"
2018/09/05 11:03:17 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/09/05 11:03:17 DEBUG : /: Lookup: name="wp-includes"
2018/09/05 11:03:17 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/09/05 11:03:17 DEBUG : /: Lookup: name="wp-includes"
2018/09/05 11:03:17 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/09/05 11:03:17 DEBUG : /: Lookup: name="wp-includes"
2018/09/05 11:03:17 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/09/05 11:03:17 DEBUG : /: Lookup: name="wp-includes"
2018/09/05 11:03:17 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/09/05 11:03:17 DEBUG : /: Lookup: name="wp-includes"
2018/09/05 11:03:17 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/09/05 11:03:17 DEBUG : /: Lookup: name="wp-includes"
2018/09/05 11:03:17 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/09/05 11:03:17 DEBUG : /: Lookup: name="wp-includes"
2018/09/05 11:03:17 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/09/05 11:03:17 DEBUG : /: Lookup: name="wp-includes"
2018/09/05 11:03:17 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/09/05 11:03:17 DEBUG : /: Lookup: name="wp-includes"
2018/09/05 11:03:17 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/09/05 11:03:17 DEBUG : /: Lookup: name="wp-includes"
2018/09/05 11:03:17 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory

**Comment by ncw** [comment]
Can you give an example of a file or folder which won't copy in with its full path?

**Comment by tcf909** [comment]
It happened when I was copying the latest wordpress installation folder:

https://wordpress.org/latest.tar.gz

I would download the tar.gz, decompress it to a temp folder, then copy the
contents of the folder to the mount.

It didn't seem to have a problem with 1 particular file. Just randomly
would give the error I posted.

I tried it probably 20 times with various conditions changed. Consistently
ran in to the same issue (but not on the same file).

**Comment by tcf909** [comment]
And just to reiterate:

The exact same process on my linux box worked fine (and am currently using
it without any problems).

I also didn't see an error or access in the debug logs (rclone) for the
file that the mac finder would complain about. Which leads me to believe
it's something to do with the fuse implementation, or the portable mount
used in mac (but just a guess).

**Comment by tcf909** [comment]
Let me know if you would like to jump on a screen share session or have me record a screen cast of the problem to help.

**Comment by tcf909** [comment]
Hey Nick, sorry about the delay. Lost track of this one.

The copy was being done with Finder.

It was 100% repeatable.

I will try to get you the logs today.
