### ISSUE TITLE
Plex hung on  playing in latest beta - error "page already freed" in logs

### ISSUE THREAD

**Issue by Krandor1** [rclone/rclone#2561]
#### What is the problem you are having with rclone?

I loaded the most recent beta last night and it was working fine.  This morning when trying to play something, plex hung and found the errors listed below in the log files.  

I am going to do a clear of the cache since I did upgrade versions as my next step but did want to go on and report the error seenroot@voldemort:/home/bh# rclone -V
rclone v1.43-056-gd5150193-beta
- os/arch: linux/amd64
- go version: go1.11
.  

#### What is your rclone version (eg output from `rclone -V`)

root@voldemort:/home/bh# rclone -V
rclone v1.43-056-gd5150193-beta
- os/arch: linux/amd64
- go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu

####  Which cloud storage system are you using? (eg Google Drive)

This is a gdrive -> cache -> crypt setup

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2018/09/09 10:55:32 DEBUG : tv/: >Lookup: node=<nil>, err=<nil>
2018/09/09 10:55:32 fuse: panic in handler for Lookup [ID=0x5af21 Node=0x1061 Uid=109 Gid=115 Pid=7592] "Stargate SG-1": page 83793 already freed
goroutine 400620 [running]:
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve.func2(0x126f140, 0xc000722500, 0xc003f97ef8, 0xc003f97e77)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:857 +0x1ac
panic(0xef1220, 0xc0003a8cd0)
        /home/travis/.gimme/versions/go1.11.linux.amd64/src/runtime/panic.go:513 +0x1b9
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*freelist).free(0xc0005665d0, 0x47fe68, 0x7fc324d43000)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/freelist.go:143 +0x424
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*node).spill(0xc000a74a10, 0xc005dec300, 0xc003f967e8)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/node.go:363 +0x200
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*Bucket).spill(0xc0016efcc0, 0xc0008f2900, 0x4d)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/bucket.go:568 +0x4b4
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*Bucket).spill(0xc003e751c0, 0xc00449c800, 0xc003f96cc8)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/bucket.go:535 +0x401
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*Bucket).spill(0xc003e75180, 0xc00449c700, 0xc003f96f38)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/bucket.go:535 +0x401
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*Bucket).spill(0xc003e75140, 0xc00449c500, 0xc003f971a8)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/bucket.go:535 +0x401
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*Bucket).spill(0xc0023276d8, 0x396f37fd15e3, 0x1b2d5a0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/bucket.go:535 +0x401
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*Tx).Commit(0xc0023276c0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/tx.go:160 +0x11c
github.com/ncw/rclone/vendor/github.com/coreos/bbolt.(*DB).Update(0xc0002343c0, 0xc003f97388, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/coreos/bbolt/db.go:679 +0xe8
github.com/ncw/rclone/backend/cache.(*Persistent).AddBatchDir(0xc0000cc320, 0xc00090e000, 0x351, 0x400, 0xed325aa5a, 0x1b2d5a0)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/cache/storage_persistent.go:205 +0x99
github.com/ncw/rclone/backend/cache.(*Fs).List(0xc001452540, 0xc001623a00, 0x1a, 0xc001623a00, 0x1a, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/cache/cache.go:942 +0x5eb
github.com/ncw/rclone/backend/crypt.(*Fs).List(0xc00046e1e0, 0xc000393e4c, 0x2, 0x39696a4e69f5, 0xbedd6e76d71dbd87, 0x0, 0xc006efc000, 0x42dccb)
        /home/travis/gopath/src/github.com/ncw/rclone/backend/crypt/crypt.go:274 +0x7c
github.com/ncw/rclone/fs/list.DirSorted(0x127b340, 0xc00046e1e0, 0x1b2d500, 0xc000393e4c, 0x2, 0xc0004ce480, 0xc001237a40, 0xc003c6f968, 0x43e53d, 0xc000592f94)
        /home/travis/gopath/src/github.com/ncw/rclone/fs/list/list.go:23 +0x63
github.com/ncw/rclone/vfs.(*Dir)._readDir(0xc000592f30, 0x114e508, 0xc000592f90)
        /home/travis/gopath/src/github.com/ncw/rclone/vfs/dir.go:183 +0xd6
github.com/ncw/rclone/vfs.(*Dir).stat(0xc000592f30, 0xc003d2a010, 0xd, 0x0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/vfs/dir.go:297 +0x7f
github.com/ncw/rclone/vfs.(*Dir).Stat(0xc000592f30, 0xc003d2a010, 0xd, 0x10, 0xc00a714080, 0x2, 0x2)
        /home/travis/gopath/src/github.com/ncw/rclone/vfs/dir.go:349 +0x43
github.com/ncw/rclone/cmd/mount.(*Dir).Lookup(0xc000446d50, 0x1270b80, 0xc00a712080, 0xc000722500, 0xc00a7160c0, 0x1, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/cmd/mount/dir.go:73 +0x1d0
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).handleRequest(0xc0006b20c0, 0x1270b80, 0xc00a712080, 0x1264760, 0xc000446d50, 0xc00a712040, 0x126f140, 0xc000722500, 0xc003f97ef8, 0x0, ...)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:1050 +0x31cb
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).serve(0xc0006b20c0, 0x126f140, 0xc000722500)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:878 +0x410
github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve.func1(0xc0006b20c0, 0x126f140, 0xc000722500)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:425 +0x6e
created by github.com/ncw/rclone/vendor/bazil.org/fuse/fs.(*Server).Serve
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/bazil.org/fuse/fs/serve.go:423 +0x31e
2018/09/09 10:55:32 DEBUG : Cache remote gdrivecache:enc: list 'tvvohkcnn3evfo5aej90n11fi0'

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
