### ISSUE TITLE
ResilioSync had no permission to write in mounted Google Drive

### ISSUE THREAD

**Issue by yangleitj** [rclone/rclone#2564]
#### What is the problem you are having with rclone?
ResilioSync had no permission to write in mounted Google Drive
#### What is your rclone version (eg output from `rclone -V`)
rclone v1.43.1
- os/arch: linux/amd64
- go version: go1.11
#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux rclone 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux
####  Which cloud storage system are you using? (eg Google Drive)
Google Drive
#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone mount rsyncgdrive:rsyncgdrive /root/rsyncgdrive --copy-links --no-gzip-encoding --no-check-certificate --allow-other --allow-non-empty --umask 000`
#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
`docker run -d --name ResilioSync \
-p 8888:8888 -p 55555:55555 \
-v /root/resiliosync:/mnt/sync \
--restart always \
resilio/sync`

**Comment by B4dM4n** [comment]
This is probably not a bug in rclone, but due to the [limitations](https://rclone.org/commands/rclone_mount/#limitations) that `rlcone mount` currently has:

> Without the use of “--vfs-cache-mode” this can only write files sequentially, it can only seek when reading. This means that many applications won’t work with their files on an rclone mount without “--vfs-cache-mode writes” or “--vfs-cache-mode full”. See the File Caching section for more info.

**Comment by yangleitj** [comment]
`rclone mount rsyncgdrive:rsyncgdrive /root/rsyncgdrive --copy-links --no-gzip-encoding --no-check-certificate --allow-other --allow-non-empty --umask 000 --vfs-cache-mode full`

It seemed not working.

**Comment by ncw** [comment]
`--vfs-cache-mode writes` is probably what you want.

Can you attach a log with `-vv` of the problem happening?

**Comment by animosity22** [comment]
This looks to be stale and solved by above answer. If there is still a question, please just ask on the forums.
