### ISSUE TITLE
In the lastest beta debug mode spam and not and does not see the space occupied correctly

### ISSUE THREAD

**Issue by RyukSniper** [rclone/rclone#2565]
rclone v1.43-067-gb2a6a974-beta
- os/arch: linux/amd64
- go version: go1.11

with the last beta of today, in debug mode this is spammed
2018/09/11 10:58:15 DEBUG : : Statfs:
2018/09/11 10:58:15 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274877906944 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>

and it does not display correctly how much space is used
bug on beta?

**Comment by ncw** [comment]
Which remote are you using?

Can you try some older betas and see where the problem came in?

**Comment by RyukSniper** [comment]
i use OneDrive, but i try lastest beta work without spam, but now spam statfs. mmm now i not understand...
I'm thinking that this spam is generated by the new api key graph because now I'm in throttling
2018/09/11 14:26:57 ERROR : One drive root '': Statfs failed: about failed: activityLimitReached: The request has been throttled with this error.
do you have any idea?

**Comment by ncw** [comment]
Ah ha!  Try [making your own key](https://github.com/ncw/rclone/blob/master/docs/content/onedrive.md#getting-your-own-client-id-and-key) and see if that helps.

**Comment by RyukSniper** [comment]
I have my api key :c

**Comment by ncw** [comment]
Oh, I think this is related to your other ticket #2406 - if we can sort that one out, it will fix this one.

**Comment by animosity22** [comment]
Fixed via the other ticket. Closing.
