### ISSUE TITLE
rclone dedupe, choose the main folder efficiently 

### ISSUE THREAD

**Issue by ajh0912** [rclone/rclone#2568]
#### What is the problem you are having with rclone?
Let's say 'Folder' and 'Folder (1)' exist in a certain directory, the webUI etc will show them as the same name, just 'Folder', but File Stream etc can't have the same filename so they show as '(1)' etc. Let's say I have 1000 files in 'Folder' and later on 'Folder (1)' is uploaded that has 5 files. I want to run dedupe so that I will end up with just 'Folder' that has 1005 files, or less if some of those 5 files already existed in the original folder. You'd think the way rclone would do this is to treat the 'Folder' as the original one, and copy the contents of 'Folder (1)' into 'Folder' and delete 'Folder (1)'. Instead I see rclone is copying the contents of 'Folder' into 'Folder (1)' and then deleting 'Folder'. This means there's 1000 move (or 'merge' as the CLI shows) operations instead of 5 (takes much longer, more API calls, etc.). It also means the activity pane in the webUI will now show only 'moved x files' and you'll lose the activity of the original 'Folder' because it was deleted.

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.43.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 64bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone dedupe GoogleDrive: --dedupe-mode largest -vv

**Comment by ncw** [comment]
That would be a nice enhancement, and probably not too tricky - fancy having a go?

**Comment by ajh0912** [comment]
I'm afraid I wouldn't have the programming ability, I just hope someone else thinks it's important enough and has the time to work on it. I appreciate the work you've done with rclone.

**Comment by ncw** [comment]
I think implementing this should be a matter of running `ListDir` on the folders to find the largest so it should be very easy if someone would like to have a go.

**Comment by ncw** [comment]
@asiamarek this is how I would run the tests - is that what you are doing?

```
~/go/src/github.com/ncw/rclone/fs/operations$ go test -v -run Dedup -remote TestDrive:
=== RUN   TestDeduplicateInteractive
2018/09/18 15:51:02 NOTICE: one: Found 3 duplicates - deleting identical copies
2018/09/18 15:51:02 NOTICE: one: Deleting 2/3 identical duplicates (MD5 "0f6d3e59c45e54d0f2cb30fb594620a3")
2018/09/18 15:51:04 NOTICE: one: All duplicates removed
--- PASS: TestDeduplicateInteractive (9.60s)
    run.go:173: Remote "Google drive root 'rclone-test-cezoyik7tahikoy0livedit8'", Local "Local file system at /tmp/rclone201398783", Modify Window "1ms"
=== RUN   TestDeduplicateSkip
2018/09/18 15:51:10 NOTICE: one: Found 3 duplicates - deleting identical copies
2018/09/18 15:51:10 NOTICE: one: Deleting 1/2 identical duplicates (MD5 "0f6d3e59c45e54d0f2cb30fb594620a3")
--- PASS: TestDeduplicateSkip (7.25s)
    run.go:173: Remote "Google drive root 'rclone-test-cezoyik7tahikoy0livedit8'", Local "Local file system at /tmp/rclone201398783", Modify Window "1ms"
=== RUN   TestDeduplicateFirst
2018/09/18 15:51:17 NOTICE: one: Found 3 duplicates - deleting identical copies
2018/09/18 15:51:18 NOTICE: one: Deleted 2 extra copies
--- PASS: TestDeduplicateFirst (6.72s)
    run.go:173: Remote "Google drive root 'rclone-test-cezoyik7tahikoy0livedit8'", Local "Local file system at /tmp/rclone201398783", Modify Window "1ms"
=== RUN   TestDeduplicateNewest
2018/09/18 15:51:23 NOTICE: one: Found 3 duplicates - deleting identical copies
2018/09/18 15:51:24 NOTICE: one: Deleted 2 extra copies
--- PASS: TestDeduplicateNewest (7.25s)
    run.go:173: Remote "Google drive root 'rclone-test-cezoyik7tahikoy0livedit8'", Local "Local file system at /tmp/rclone201398783", Modify Window "1ms"
=== RUN   TestDeduplicateOldest
2018/09/18 15:51:31 NOTICE: one: Found 3 duplicates - deleting identical copies
2018/09/18 15:51:32 NOTICE: one: Deleted 2 extra copies
--- PASS: TestDeduplicateOldest (7.90s)
    run.go:173: Remote "Google drive root 'rclone-test-cezoyik7tahikoy0livedit8'", Local "Local file system at /tmp/rclone201398783", Modify Window "1ms"
=== RUN   TestDeduplicateLargest
2018/09/18 15:51:39 NOTICE: one: Found 3 duplicates - deleting identical copies
2018/09/18 15:51:40 NOTICE: one: Deleted 2 extra copies
--- PASS: TestDeduplicateLargest (8.50s)
    run.go:173: Remote "Google drive root 'rclone-test-cezoyik7tahikoy0livedit8'", Local "Local file system at /tmp/rclone201398783", Modify Window "1ms"
=== RUN   TestDeduplicateRename
2018/09/18 15:51:48 NOTICE: one.txt: Found 3 duplicates - deleting identical copies
--- PASS: TestDeduplicateRename (9.25s)
    run.go:173: Remote "Google drive root 'rclone-test-cezoyik7tahikoy0livedit8'", Local "Local file system at /tmp/rclone201398783", Modify Window "1ms"
PASS
ok  	github.com/ncw/rclone/fs/operations	57.699s
```

**Comment by asiamarek** [comment]
Yeah i was doing something wrong, sorry about that, now it's working perfectly. Thanks !

As i said i want to try to solve this issue :)

**Comment by ncw** [comment]
> Yeah i was doing something wrong, sorry about that, now it's working perfectly. Thanks !
> 
> As i said i want to try to solve this issue :)

No worries, and thank you - looking forward to the PR :-)

**Comment by ajh0912** [comment]
Hi there, any updates? Much appreciated.
