### ISSUE TITLE
Request the ability to format -v --stats for limited scrollback

### ISSUE THREAD

**Issue by checktravis** [rclone/rclone#2588]
#### What is the problem you are having with rclone?

When I run a rclone task that may take a while, I run it through tmux. I can check in on it as needed by opening an attached --read-only tmux session. I add read-only in case my cat decides to run across the keyboard.

If I am running a substantial number of --transfers, the primary info scrolls up before I can read it. Would like the option of seeing the INFO and the current transfers if possible, even if the first part of the transfers list is scrolled out of view.

Suggesting the Transfers list be displayed before the INFO printout, or the ability to format / set order. 

#### What is your rclone version (eg output from `rclone -V`)

rclone v1.43.1
- os/arch: linux/amd64
- go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux Mint 4.15.0-34-generic #37-Ubuntu x86_64 GNU/Linux

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
rclone sync ${SOURCE_PATH} ${DESTINATION_PATH} \
  --backup-dir ${ARCHIVE_DESTINATION_PATH} \
  --exclude-from ${EXCLUDE_FILE} \
  -v --skip-links \
  --transfers=32 \
  --checkers=16 \
  --drive-chunk-size=16384k \
  --drive-upload-cutoff=16384k \
  --stats 15s \
  --delete-excluded
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2018/09/17 07:15:37 INFO  :                                          
Transferred:      400.710M / 435.946 MBytes, 92%, 131.474 kBytes/s, ETA 4m34s
Errors:                45                                            
Checks:              1171 / 1171, 100%                               
Transferred:         1450 / 2537, 57%                                
Elapsed time:     52m0.9s                                            
Transferring:                                                        
 *   .../New-Minty/cinnamon/img/controls/off.svg:  0% /3.224k, 0/s, -
 *   .../cinnamon/img/controls/close-pressed.svg:  0% /5.592k, 0/s, -
 *   .../cinnamon/img/controls/entry-focused.svg:  0% /4.586k, 0/s, -
 *   .../cinnamon/img/controls/scroll-handle.svg:  0% /4.243k, 0/s, -
 *   .../controls/calendar-arrow-right-hover.svg:  0% /3.827k, 0/s, -
 *   ...amon/img/controls/close-simple-hover.svg:  0% /5.211k, 0/s, -
 *   ...cinnamon/img/controls/hotcorner-icon.svg:  0% /4.938k, 0/s, -
 *   ...controls/radiobutton-checked-focused.svg:  0% /4.258k, 0/s, -
 *   ...ew-Minty/cinnamon/img/controls/close.svg:  0% /5.584k, 0/s, -
 *   ...ew-Minty/cinnamon/img/controls/entry.svg:  0% /4.275k, 0/s, -
 *   ...g/controls/calendar-arrow-left-hover.svg:  0% /3.819k, 0/s, -

```

**Comment by ncw** [comment]
Did you try the new `--progress` flag?  This makes a dynamically updating stats area with a static logs area which may fit your requirements.  You can also add `--stats-one-line` to condense the stats to one line.
