### ISSUE TITLE
Rclone mount does not shows a particular unicode filename in win7 on google drive

### ISSUE THREAD

**Issue by fhsdfuihisfg** [rclone/rclone#2596]
#### What is the problem you are having with rclone?
The particular unicode name results in file name too long error when I try to create a file with that name on ubuntu with command "touch".

The file does not show up in win7 with rclone mount. However, it shows up with google file stream. On ubuntu 18.04 LTS server, it shows up with rclone mount without problem.

The file was created in win7 and uploaded to google drive with rclone.

#### What is your rclone version (eg output from `rclone -V`)
rclone v1.43

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 7, 64bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount

**Comment by ncw** [comment]
Can you share the file name? How long is it?

Google drive can have very long file names, up to 4k I think.

However there are lots of limitations about file names when using `mount` so if it is approaching 255 characters it may not be view-able via FUSE on windows.

**Comment by fhsdfuihisfg** [comment]
For example:
一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一.txt

**Comment by ncw** [comment]
Interesting...

Wikipedia has an [article on file name limits](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits). Summary from [server fault](https://serverfault.com/questions/9546/filename-length-limits-on-linux).

```
BTRFS   255 bytes
exFAT   255 UTF-16 characters
ext2    255 bytes
ext3    255 bytes
ext3cow 255 bytes
ext4    255 bytes
FAT32   8.3 (255 UCS-2 code units with VFAT LFNs)
NTFS    255 characters
XFS     255 bytes
```

Note how the linux ones say `bytes` but the windows ones say `characters`.

Under linux file names are stored UTF-8 encoded as bytes, whereas under windows the filenames are stored as unicode characters (of various different types).

Taking the example above

```
>>> a = u"一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一.txt"
>>> len(a)
229
>>> len(a.encode("utf-8"))
679
>>> 
```

So under linux that filename will be 679 bytes which is clearly too long (> 255) whereas under Windows it will be 229 characters which is OK.

However that filename is usable from `rclone mount` on linux - you just can't copy it to a local file system.

I'm unsure why it isn't visible using `rclone mount` with Windows - I suspect either the FUSE compatibility layer or WinFSP has a byte length limit, but I'm not sure.  @billziss-gh can you shed any light here?

**Comment by billziss-gh** [comment]
WinFsp has a maximum limit for file names of 255 UTF-16 characters. Furthermore I believe that the FUSE layer further makes that limit to be 255 bytes to be inline with Linux and other UNIX systems.

**Comment by fhsdfuihisfg** [comment]
Here are more explanation:
https://github.com/dotnet/corefx/issues/32347#issuecomment-422915405

**Comment by ncw** [comment]
@billziss-gh wrote:
> WinFsp has a maximum limit for file path components of 255 UTF-16 characters. Furthermore I believe that the FUSE layer further makes that limit to be 255 bytes to be inline with Linux and other UNIX systems.

From my experiments above the Linux FUSE layer can handle longer than 255 byte files - I didn't manage to find any documentation for this though.

If the WinFsp FUSE layer is limited to 255 bytes that certainly explains the issue - thank you :-)

**Comment by billziss-gh** [comment]
To clarify I am talking about the limit being 255 on file path **components** and not the whole file path.

For example: the path `/comp1/comp2/comp3/.../compN` may be much longer than 255 (on Linux off the top of my head the limit used to be 4096, on Windows the limit is higher and probably around 2<sup>15</sup>). But each individual component `comp1`, `comp2`, ..., `compN` can be up to 255 bytes or characters.

I cannot test this right now, but have you seen that you can now create a path with components larger than 255 bytes on Linux now?

**Comment by ncw** [comment]
@billziss-gh wrote:
> To clarify I am talking about the limit being 255 on file path **components** and not the whole file path.

Ah, OK

> For example: the path `/comp1/comp2/comp3/.../compN` may be much longer than 255 (on Linux off the top of my head the limit used to be 4096, on Windows the limit is higher and probably around 215). But each individual component `comp1`, `comp2`, ..., `compN` can be up to 255 bytes or characters.
> 
> I cannot test this right now, but have you seen that you can now create a path with components larger than 255 bytes on Linux now?

Apparently so.

Testing with an rclone mount on google drive which I know supports file components up to 4k

```
rclone -vv mount drive:test /mnt/tmp/
```

Create the filename above which is 679 bytes

```
$ touch /mnt/tmp/一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一 一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一.txt
$ ls -l /mnt/tmp/
total 259054
[snip]
-rw-rw-r-- 1 ncw ncw         0 Sep 24 16:30  一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一一.txt
$ 
```

A bit of testing indicates that the limit seems to be 255 **characters** now rather than 255 **bytes** which is weird indeed.  A straight forward file with ASCII only characters can only be 255 long.

**Comment by billziss-gh** [comment]
I have added WinFsp enhancement request billziss-gh/winfsp#191 to track this.

I am about to release the final beta for WinFsp v1.4 so this cannot make it to this release.

**Comment by animosity22** [comment]
This looks to be solved by the winsfp item above and can be tracked using that.
