### ISSUE TITLE
Skipping undecryptable file name: illegal base32 data at input byte 4

### ISSUE THREAD

**Issue by snickers2k** [rclone/rclone#2600]
#### What is the problem you are having with rclone?
Skipping undecryptable file name: illegal base32 data at input byte 4

v1.43.1
Ubuntu 18
GoogleDrive

#### log 

```
2018/09/20 04:00:42 DEBUG : rclone: Version "v1.43.1" starting with parameters ["rclone" "move" "--config=/home/snikay/.config/rclone/rclone.conf" "/home/snikay/Move2Drive/" "SecretDrive:/" "-c" "--delete-after" "--min-age" "15m" "--bwlimit=15M" "--log-file=/home/snikay/logs/rclone-upload-Move2Drive.cron" "--log-level" "DEBUG"]
2018/09/20 04:00:42 DEBUG : Using config file from "/home/snikay/.config/rclone/rclone.conf"
2018/09/20 04:00:42 INFO  : Starting bandwidth limiter at 15MBytes/s
2018/09/20 04:00:44 DEBUG : n5uh46cpemve1duehr2bt7arck: Skipping undecryptable file name: bad decryption - contains control chars
2018/09/20 04:00:44 DEBUG : TEST.docx: Skipping undecryptable file name: illegal base32 data at input byte 4
2018/09/20 04:00:48 DEBUG : Series/Justified/Season 06/Justified - S06E13 - Das Versprechen/justified.s06e13.mkv: Excluded from sync (and deletion)
2018/09/20 04:00:48 DEBUG : Series/Justified/Season 06/Justified - S06E05 - Alte Freundschaften/justified.s06e05.mkv: Excluded from sync (and deletion)
2018/09/20 04:00:48 DEBUG : Series/Justified/Season 01/Justified - S01E11 - Veteranen/justified.s01e11.mkv: Excluded from sync (and deletion)
2018/09/20 04:01:02 NOTICE: Movies/Power Rangers (2017): Duplicate directory found in destination - ignoring


```

also the last entry makes no sense really. That "Power Rangers" Folder was already uploaded and does not exist anymore.

**Comment by ncw** [comment]
> TEST.docx: Skipping undecryptable file name: illegal base32 data at input byte 4

What that means is that there is a google doc on your drive.  I suggest you keep the encrypted stuff in a subdirectory so it doesn't mix with the non encrypted stuff and you won't get this error any more.



> also the last entry makes no sense really. That "Power Rangers" Folder was already uploaded and does not exist anymore.

rclone still thinks it is there for some reason...  You can run `rclone dedupe` to fix duplicates on drive.

**Comment by snickers2k** [comment]
ahh, i see. okay.
I thought that one was the reason for "justified" not being uploaded. Thats my main Problem. Sorry.
I have no clue why it is "Excluded from sync (and deletion)"

**Comment by ncw** [comment]
I expect that is excluded because of "--min-age" "15m"

**Comment by snickers2k** [comment]
no, thats not the case. It's days old. Anything else gets uploaded correctly.

**Comment by ncw** [comment]
> no, thats not the case. It's days old.
> Anything else gets uploaded correctly. These 3 files are the first files in months that doesn't get uploaded. Anything i can do to give more information? deep-debug or something? :D

`--min-age` is the only filter you are using so I can't see any other command that could cause it.

Can you run `rclone lsl "/home/snikay/Move2Drive/Series/Justified/Season 06/Justified - S06E13 - Das Versprechen/justified.s06e13.mkv"` (hopefully I got the path right!) and see what rclone things the date is.  Maybe it got set into the future somehow.

> Otherwise i just copy them to my mount via "mv" and hope it was a one-time-bug

I suspect just `touch`-ing those files and waiting 15 minutes will be enough but the above `rclone lsl` will show for sure!

**Comment by animosity22** [comment]
This looks to be a stale issue. If you still have a question, please feel free to ask on the forums and we'll help out!
