### ISSUE TITLE
Hide user password , command line from shell line, htop.

### ISSUE THREAD

**Issue by tvvid** [rclone/rclone#2605]
Currently when i run

rclone serve webdav --pass “XXX1” --user “XXX2”

this XXX1 and XXX2 is visible in htop or top .

Is it possible to make it not visible, encrypted just like encrypted config password?
or hidden in some way just to be impossible to see it.
Preferably also address and port.
Or best - whole command line to be hidden.
By making it loaded from encrypted config file or smth like that.
Just as password to config file is hidden.

**Comment by ncw** [comment]
Probably the best way of doing this is using an [htpasswd](http://www.htaccesstools.com/articles/htpasswd/) file with `--htpasswd` which would get the credentials off the command line.

**Comment by tvvid** [comment]
thanks. I didnt think about it.
Its good option.
Do you have some ideas for rest of the command, to hide what is shared ,to what ddress and port ?

**Comment by tvvid** [comment]
but when someone will look at command line he will see that rclone is using --htpasswd and file name so he can take this --htpasswd file....so its no different than username password.

it is important while having rclone on someones vps, such owner can connect to shell and seerunning processes with cmd line....

**Comment by animosity22** [comment]
This looks to be answered. Closing out.

**Comment by joshuajbrunner** [comment]
@ncw 
Does the opposite work?

Im trying to run `rclone mount --rc --rc-htpasswd=<path/to/htpasswd>` but `rclone rc job/list --rc-htpasswd=<path/to/htpasswd>` comes back with `Failed to rc: Failed to read rc response: 401 Unauthorzied: Unauthorized`
