### ISSUE TITLE
这个软件非常好，非常感谢你，希望可以有配置教程

### ISSUE THREAD

**Issue by pzb568** [rclone/rclone#2608]
Android   8.1
termux
我知道这个软件直接 pkg install rclone 就安装成功了，谷歌微软都已经授权成功，就是配置挂载点和同步设置命令非常复杂，希望可以有详细的教程，非常感谢。

**Comment by ncw** [comment]
I'm sorry I don't speak Chinese!  I have used Google translate to read what you said.

If you do a google search you will find many tutorials for rclone.

The best place to ask for help is on [the rclone forum](https://forum.rclone.org/).  Write what you have tried and what error you are getting.

I hope that helps

Nick

**Comment by pzb568** [comment]
@ncw Thank you very much

**Comment by cxyzzz** [comment]
> Android 8.1
> termux
> 我知道这个软件直接 pkg install rclone 就安装成功了，谷歌微软都已经授权成功，就是配置挂载点和同步设置命令非常复杂，希望可以有详细的教程，非常感谢。

[配置挂载点：https://cxyzzz.github.io/posts/2a60e472.html](https://cxyzzz.github.io/posts/2a60e472.html#more)
