### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by SowmediaNL** [rclone/rclone#2614]
#### What is the problem you are having with rclone?
Syncing a directory with SFTP will fail after some time, yielding errors 'too many open files'. Running the command `lsof -c rclone | wc -l` yields 1029 (this is the max. I guess). In the list printed by `lsof -c rclone`, most protocols are of type 'can't identify protocol'

#### What is your rclone version (output from `rclone version`)
rclone v1.43.1
- os/arch: linux/amd64
- go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 64 bit using Linux subsystem

####  Which cloud storage system are you using? (eg Google Drive)
SFTP

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync (local directory) (sftp connection) -P

**Comment by ncw** [comment]
I haven't managed to replicate this...

Which ssh server are you using?

Can you try `--sftp-disable-hashcheck` to see if that makes a difference?

Can you after it has run for a while and accumulated some open files kill rclone with SIGQUIT (`CTRL-\` or use `kill -QUIT`).  This will produce a backtrace which is likely very long - can you attach it here?

**Comment by ivandeex** [comment]
@SowmediaNL 
Does the problem reproduce with rclone 1.53.2 ?
If not, let's close this stale issue.

**Comment by daniele-spl** [comment]
I can see the same problem.
Version: rclone-1.53.2
OS: SLES 12 SP5

lsof output right now, application already closed some files
lsof -c rclone | wc -l
1027

Error 1:
vfs cache: failed to transfer file from cache to remote: failed to open source object

Error 2:
Non-out-of-space error encountered during open

As soon as this happens, i can see RSS of rclone is increasing to some gig and CPU is up to 400%. Normal mode is  20/30% CPU.


Could you have a look at that?
Would be good to have a ulimit like nofile setting

**Comment by ivandeex** [comment]
@daniele-spl 

Please run

rclone sync /your/local/dir your_remote:path -vvv --log-file bug.log

> After it has run for a while and accumulated some open files kill rclone with SIGQUIT (CTRL-\ or use kill -QUIT). This will produce a backtrace which is likely very long

Please attach log and trace here

**Comment by daniele-spl** [comment]
Ok there is something deeper going wrong here. 
The open file issue is just a result of the the main issue. I mean, a static limit to somewhere near 1030 anyhow is not that good, but in most cases you shouldnt come up there.

My issue was, that vfs caching did not work properly.

I get the same error like #4639 

Its really strange. After a reboot of the system I get:
2020/12/18 15:40:14 ERROR : Failed to create vfs cache - disabling: failed to make cache directory: make cache directory failed: mkdir /mnt/resource/rclonecache: permission denied

After that its doing a direct transfer to azure. Cause I open a lot of files and also a lot of small files. So the open file issue is related to the http connections to the azure storage.


Then you wrote me to enable debug log, so I restarted the service with the debug flag, It restarted without any errors. The above Error does not come up, when i restart the service or just start it without the deamon flag at command line.
BUT: It still cannot use the cache and is creating interesting logs but does nothing at all.
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at 819200 length 32768 chunkOffset 786432 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at -1 length 32768 chunkOffset 1572864 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.openRange at 1572864 length 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.RangeSeek from -1 to 1310720 length -1
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at -1 length 32768 chunkOffset 1310720 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.openRange at 1310720 length 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.RangeSeek from -1 to 1441792 length -1
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at -1 length 32768 chunkOffset 1441792 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.openRange at 1441792 length 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.RangeSeek from -1 to 1703936 length -1
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at -1 length 32768 chunkOffset 1703936 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.openRange at 1703936 length 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.RangeSeek from -1 to 1572864 length -1
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at 851968 length 32768 chunkOffset 786432 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at -1 length 32768 chunkOffset 1572864 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.openRange at 1572864 length 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.RangeSeek from -1 to 1310720 length -1
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at -1 length 32768 chunkOffset 1310720 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.openRange at 1310720 length 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.RangeSeek from -1 to 1441792 length -1
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at -1 length 32768 chunkOffset 1441792 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.openRange at 1441792 length 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.RangeSeek from -1 to 1703936 length -1
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at -1 length 32768 chunkOffset 1703936 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.openRange at 1703936 length 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.RangeSeek from -1 to 1572864 length -1
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at 884736 length 32768 chunkOffset 786432 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at -1 length 32768 chunkOffset 1572864 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.openRange at 1572864 length 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.RangeSeek from -1 to 1310720 length -1
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at -1 length 32768 chunkOffset 1310720 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.openRange at 1310720 length 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.RangeSeek from -1 to 1441792 length -1
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at -1 length 32768 chunkOffset 1441792 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.openRange at 1441792 length 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.RangeSeek from -1 to 1703936 length -1
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at -1 length 32768 chunkOffset 1703936 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.openRange at 1703936 length 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.RangeSeek from -1 to 1572864 length -1
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at 917504 length 32768 chunkOffset 786432 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.Read at -1 length 32768 chunkOffset 1572864 chunkSize 134217728
2020/12/18 16:37:30 DEBUG : test/journal.gz3: ChunkedReader.openRange at 1572864 length 134217728

Maybe I will poste this to the other issue. Ill try to find out why it does not want to create the directory. The permissions are not the problem. I checked that.

**Comment by ivandeex** [comment]
First off, this ticjet started sometime ago as SFTP related issue. Now it is transforming into AzureBlob problem.

> My issue was, that vfs caching did not work properly.
> I get the same error like #4639

That issue (#4639) is about `rclone mount`. This one (#2614) is reported against `rclone sync`.

> After a reboot of the system I get:
> 2020/12/18 15:40:14 ERROR : Failed to create vfs cache - disabling: failed to make cache directory: make cache directory failed: mkdir /mnt/resource/rclonecache: permission denied

So it's for sure `rclone mount`. Normally rclone maintains cache under `$HOME/.cache/rclone/...`. But in your case it tries `/mnt/resource/...`. This means you use some undescribed here CLI options or environment variables.

> After that its doing a direct transfer to azure.

For `rclone mount` to do transfers you had to do some action on the mounted directory. But it's missing from description.

> restart the service or just start it without the deamon flag at command line

What service? What daemon flag?

I would like to build a non-contradictory picture before I reproduce and investigate. Let's look again at the issue description https://github.com/rclone/rclone/issues/2614#issue-364823314 at the top of this page and fill the gaps.

**Comment by daniele-spl** [comment]
You are totally right. I was just looking into every direction.

Yes it is with rclone mount

I did just a cp from the mount to a local directory

I found the issue at least for me. I had the flag --buffer-size 0
Thats not working and caused all the error messages during transfer with cache configured.

These are my current testing parameters:
--cache-dir /tmp/cache --track-renames --dir-cache-time 24h --attr-timeout 4m --vfs-write-back 5s --vfs-cache-mode=full --checksum --vfs-cache-max-age 1m --vfs-cache-max-size 200G --log-file=/opt/splunk/var/log/splunk/rclone.log --log-level=DEBUG --allow-other --allow-non-empty --debug-fuse  --buffer-size 1

The same with buffer-size 0 is throwing the errors.

Thank you for your help.

**Comment by ivandeex** [comment]
Good. Please submit a new ticket then.

The question is whether the old SFTP issue still reproduces.

**Comment by ivandeex** [comment]
@SowmediaNL your issue has been reproduced recently, it is being worked on in https://github.com/rclone/rclone/issues/4883

**Comment by ivandeex** [comment]
@daniele-spl 
I reopened your report as https://github.com/rclone/rclone/issues/4892

**Comment by ivandeex** [comment]
I am going to close this now
