### ISSUE TITLE
rclone dedupe unexpectedly aborts when unable to remove directory

### ISSUE THREAD

**Issue by lenar** [rclone/rclone#2621]
#### What is the problem you are having with rclone?
```rclone dedupe``` aborts when removing empty directory without enough permissions
The missing permissions is not the problem. I can live with that dedupe sub-operation failing.
Problem is, the rclone completely aborts processing and thus not progressing to other files/folders
that might have permissions (actually owned by user not read-only shared to the user).

#### What is your rclone version (output from `rclone version`)
```
rclone v1.43-116-g22ac80e8-beta
- os/arch: linux/amd64
- go version: go1.11
```
#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
```Debian 9.5 x86_64```

####  Which cloud storage system are you using? (eg Google Drive)
```Google Drive```

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
Tried different arguments:
```rclone -v --drive-impersonate fistname.lastname@company.com --fast-list dedupe rename google:/```
```rclone -v --drive-impersonate fistname.lastname@company.com --fast-list --ignore-errors dedupe rename google:/```
```rclone -v --drive-impersonate fistname.lastname@company.com --fast-list --drive-auth-owner-only dedupe rename google:/```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2018/10/03 15:13:19 DEBUG : rclone: Version "v1.43-116-g22ac80e8-beta" starting with parameters ["rclone" "-vv" "--drive-impersonate" "firstname.lastname@company.com" "--fast-list" "--drive-auth-owner-only" "--ignore-errors" "dedupe" "rename" "google:/"]
2018/10/03 15:13:19 DEBUG : Using config file from "/home/rclone/.config/rclone/rclone.conf"
2018/10/03 15:13:19 INFO  : Google drive root '': Looking for duplicates using rename mode.
2018/10/03 15:13:43 INFO  : Company logo: Merging contents of duplicate directories
2018/10/03 15:14:11 INFO  : Company logo: merging "COMPANY-LOGO.ai"
2018/10/03 15:14:11 INFO  : Company logo: removing empty directory
2018/10/03 15:14:12 Failed to dedupe: merge duplicate dirs: MergDirs move failed to rmdir "Company logo": googleapi: Error 403: The user does not have sufficient permissions for this file., insufficientFilePermissions```

**Comment by ncw** [comment]
> `rclone dedupe` aborts when removing empty directory without enough permissions
> The missing permissions is not the problem. I can live with that dedupe sub-operation failing.
> Problem is, the rclone completely aborts processing and thus not progressing to other files/folders
> that might have permissions (actually owned by user not read-only shared to the user).

Do you think dedupe should carry on if directory delete fails?

The whole dedupe operation should exit with an error if the delete does fail as there will still be duplicate directories.

This wouldn't be too tricky to fix - fancy having a go?

**Comment by ivandeex** [comment]
Maybe a flag like `--ignore-errors` would help?

**Comment by ivandeex** [comment]
@lenar Does the problem reproduce with rclone 1.54?

**Comment by ivandeex** [comment]
Closing stale requests
