### ISSUE TITLE
rclone API integration?

### ISSUE THREAD

**Issue by craigleander** [rclone/rclone#2631]
#### What is your current rclone version (output from `rclone version`)?

- rclone v1.43.1
- os/arch: darwin/amd64
- go version: go1.11

#### What problem are you are trying to solve?

Programatic access to clone, not relying with shell calls to the clone cli

#### How do you think rclone should be changed to solve that?

Expose API that can be used in a language neutral environment, preferably REST
Or create bindings for programming languages starting with python ;)

**Comment by ncw** [comment]
Great idea!  This is kind of in-progress.  The idea being extending the `rc` layer with more commands.

The `rc` is already a REST layer for rclone: https://rclone.org/rc/

What sort of commands would you like to see?

**Comment by ncw** [comment]
In [the latest beta](https://beta.rclone.org) rclone has gained a pretty comprehensive API.

You can see the [beta rc docs](https://tip.rclone.org/rc/) here.

Let me know if there is anything else rclone should implement and I'll do it!

Note also that rclone can serve any backend as webdav or ftp which could be useful to a 3rd party program too.

**Comment by ncw** [comment]
I think this is pretty much done!  See https://rclone.org/rc
