### ISSUE TITLE
--fast-list flag scans way more than it should when used with --files-from flag

### ISSUE THREAD

**Issue by darkvertex** [rclone/rclone#2639]
[[_Continued from forum thread..._](https://forum.rclone.org/t/files-from-seems-to-filter-from-path-instead-of-taking-the-paths-as-is/6958/5)]

#### What is the problem you are having with rclone?

**`--fast-list` and `--files-from` don't mix well.**
(Tested with transferring local to Google Cloud Storage, but it may affect other storage providers.)

Using `--files-from` I can provide a list of exactly which files I want to transfer. 

Presumably, `--fast-list` would make the process more efficient in that it would list remote directories (1 call per directory) and use that information to deduce which files are missing (as opposed to the default of 1 call per file to check remotely).

Unfortunately, despite having a very explicit list of files fed via `--files-from`, when using `--fast-list` causes rclone to go into a deep folder scan of the source directory without regard for if the directories scanned are part of the file list or not. This seems extremely inefficient and sounds like a bug (from my perspective.)

In my use case, I want to transfer files exactly as they appear in one filesystem into another. My command looks something like:

```
rclone sync -vvv --stats=30s --files-from /path/to/filepathlist.txt --copy-links --fast-list --auto-confirm --transfers=100 / gcs:bucketname
```

The paths in my `--files-from` in my case are relative to the OS root. For example, let's say I have the usual Linux directories in my `/` (/boot, /dev, /etc, /lib, etc...) but also some mounts that looked like:
```
/mnt/software
/mnt/projects
/mnt/otherstuff
```
and all the paths in my `--files-from` file begin with "mnt/projects/".

When I use `--fast-list` and enable verbosity level 2 (`-vv`) or higher, I am spammed with messages that look like this:
```
DEBUG : /mnt/software/somefile Excluded from sync (and deletion)
DEBUG : /mnt/software/someotherfile Excluded from sync (and deletion)
DEBUG : /mnt/software/somedir/somefile Excluded from sync (and deletion)
DEBUG : /mnt/otherstuff/otherfile Excluded from sync (and deletion)
DEBUG : /mnt/otherstuff/otherdir/anotherfile Excluded from sync (and deletion)
```
and so on and so on. I would expect `--fast-list` to scan only relevant directories, yet it's scanning every under the source directory.

You can imagine how this gets pretty slow when you consider "/" being the source path and having very large collection of NFS network mounts with hundreds of thousands of files. :cry:

If I am to remove the `--fast-list` flag from my command, transfers begin almost immediately as no redundant source scanning happens.

#### What is your rclone version (output from `rclone version`)

Bug initially discovered with:
```
rclone v1.42
- os/arch: linux/amd64
- go version: go1.10.1
```
and at request of this issue template, tested with and confirmed still buggy with the latest beta as well:
```
rclone v1.43-139-g411a6cc4-beta
- os/arch: linux/amd64
- go version: go1.11.1
```

#### Which OS you are using and how many bits

`CentOS Linux release 7.4.1708 (Core)`

####  Which cloud storage system are you using?

Google Cloud Storage.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
rclone sync -vvv --stats=30s --files-from /path/to/filepathlist.txt --copy-links --fast-list --auto-confirm --transfers=100 / gcs:bucketname
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I'm not allowed to share the real log for confidentiality reasons with my employer, but see my main explanation for what my logs look like.

**Comment by ncw** [comment]
The way `--fast-list` works is that it uses a special primitive in the backend (`ListR`) to list all the files very quickly, builds an in-memory tree of them and then used that tree to simulate a recursive directory traversal.

`--fast-list` has to list all the files in the remote - that is what the backend primitive does.  However it could avoid building the in-memory tree for the parts of it which are excluded from the filters.  This would make rclone use less memory, but it would still be doing the same amount of work, just producing fewer logs.  I'm not sure it is an optimization worth doing.

So I think this is probably working as designed.

That means that using `--fast-list` and `--files-from` is likely to be much less efficient that using `--files-from` on its own, unless you are covering files in nearly the whole remote.

Maybe I should update the docs with that - what do you think?

**Comment by ncw** [comment]
> If I'm understanding correctly, then it would make sense to have a `--remote-fast-list` flag, so we could have the acceptable local default behaviour but be able to have faster listing for bucket-based remotes like GCS.

That is how `--fast-list` works at the moment.  Since the local backend doesn't support `--fast-list` it will just use recursive directory listings.



> In my experience with typical filelists featuring tens of thousands of paths from a hundred or so folders, doing 1 API call per path to transfer to either get its details -- like filesize, metadata, etc. or even just to check if it exists -- is **far slower** than doing 1 API call per remote folder to list its contents, then using the data of that response to compute an in-memory list of what needs transferring where.

And that is exactly what not using `--fast-list` will get you (more or less).

rclone used to have an option called `--no-traverse` which is exactly as you described above.  The main difference is that without `--fast-list` rclone will list each directory that a file is in, rather than just listing the file.  This is 1 API call still transferring a relatively small amount of data so should be equivalent to `--no-traverse` in practice.

Reading what you wrote originally again

> Presumably, `--fast-list` would make the process more efficient in that it would list remote directories (1 call per directory) and use that information to deduce which files are missing (as opposed to the default of 1 call per file to check remotely).

That isn't how `--fast-list` works, it just lists once from the root.

It does prune the things which don't pass the filter, so it ends up with an in memory representation of the same files in the `--include-files` flag.

I think just dropping`--fast-list` will work for your application - is that not what you see?

Can you share timings?

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.

**Comment by zackees** [comment]
Hit this issue.

I've updated my python lib to emit a warning when used together. Might be a good idea to issue a warning in rclone itself. This is a huge footgun that was bottlenecking my transfer.
