### ISSUE TITLE
Add bitrix24 drive support?

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#2656]
Please add support to upload files to bitrix24 drive,thanks.

**Comment by ncw** [comment]
Is there an API for bitrix24?

**Comment by buengese** [comment]
There is a [REST API](https://training.bitrix24.com/rest_help/index.php) available and integration appears to be feasible.

**Comment by ivandeex** [comment]
Proposed by a now dead account.
No +1s, no comments.

**Comment by monreal** [comment]
> Proposed by a now dead account.
> No +1s, no comments.

FWIW I just subscribed to this bug as generally projects don't like +1 comments.

**Comment by ivandeex** [comment]
Bitrix24 has been supported for quite a long time as "vendor = Bitrix24" in the webdav backend.
