### ISSUE TITLE
Swift: Unable to list subdirectory

### ISSUE THREAD

**Issue by fyx** [rclone/rclone#2662]
#### What is the problem you are having with rclone?
I'm trying list my swift container but it fails on a subdirectory. This subdirectory can be listed without issue using python-swiftclient. All other subdirectories in this container can be listed with rclone.

#### What is your rclone version (output from `rclone version`)
v1.43.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 18.04 / 64bit

####  Which cloud storage system are you using? (eg Google Drive)
OpenStack Swift

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone ls elastx-internal:ubuntu/indices

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2018/10/17 08:57:15 DEBUG : rclone: Version "v1.43.1" starting with parameters ["rclone" "-vv" "ls" "elastx-internal:ubuntu/indices"]
2018/10/17 08:57:15 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2018/10/17 08:57:16 ERROR : : error listing: object not found
2018/10/17 08:57:16 Failed to ls: object not found

**Comment by ncw** [comment]
Please can you make a full log for me?

    rclone ls elastx-internal:ubuntu/indices -vv --dump bodies --log-file rclone-log.txt

And attach the log here? (Feel free to redact any sensitive looking things).

It might be worth having a go with [the latest beta](https://beta.rclone.org), but I don't think there have been any significant changes since v1.43 in the swift backend.

Thanks

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
