### ISSUE TITLE
Deleting GDrive files with multiple parents might lead to unexpected data loss

### ISSUE THREAD

**Issue by wychen** [rclone/rclone#2670]
Follow up from https://forum.rclone.org/t/deleting-gdrive-files-with-multiple-parents-might-lead-to-unexpected-data-loss/7249.

rclone version: 1.43.1

One of the most unexpected behaviors on Google Drive might be that a file can have multiple parent directories. rclone current does little to handle this subtlety, but this might lead to unexpected data loss, like this following scenario:

There is a file ./dir1/file.
$ rclone sync ./ remote:dir1
On the web interface, copy dir1/file to dir2/file. Note that there is still just one single object, but it has two parents: dir1 and dir2.
Now remove dir1/file, and do
$ rclone sync ./ remote:dir1
At this time, we’d expect dir2/file to be intact, but it would actually be deleted by the last sync command.

I’d suggest that when trying to delete a remote file, check its parents first. If it has only one parent, delete it as usual. In the rare cases that it has multiple parents, instead of deleting it, remove the parent we are targeting from its parents. This way, the semantics of deletion is closer to what we expect from most cloud services.

**Comment by ncw** [comment]
> I’d suggest that when trying to delete a remote file, check its parents first. If it has only one parent, delete it as usual. In the rare cases that it has multiple parents, instead of deleting it, remove the parent we are targeting from its parents. This way, the semantics of deletion is closer to what we expect from most cloud services.

I think this is a great idea.  Want to send a pull request to implement it?

**Comment by ivandeex** [comment]
Closing this old bug as rclone 1.43 is not supported anymore.

cc @ncw

**Comment by ncw** [comment]
Also multiple parents are no longer allowed on Gdrive!
