### ISSUE TITLE
Add Optional Graceful Finish to --max-transfer to avoid wasted bandwidth

### ISSUE THREAD

**Issue by BinsonBuzz** [rclone/rclone#2672]
Issue:

Currently as of rclone v1.44-002-g15ce0ae5-beta `--max-transfer` executes a hard stop on transfers when the limit has been reached and any incomplete transfers at that point will be halted.  In some instances this is undesired behaviour e.g. cancelling a 50GB transfer with 1MB remaining because the limit has been reached.

Solution:

It would be useful to have a `--graceful` or similar tag which would allow any remaining transfers to be completed, even if this meant exceeding `--max-transfer`.  

`--graceful` would be desirous with google drive as an alternative to trying to set `--bwlimit` to stay within the daily 750GB limit, and any transfers that started before the 750GB limit would complete with the rclone move operation exiting cleanly, rather than getting subsequent errors from transfers that won't work.

**Comment by qweasdzxc787** [comment]
Would it be enough to clear the transfer queue when the max transfer limit is reached and `—graceful` is enabled? Would that stop any new transfers to begin while still allowing the active transfers to finish? I haven’t dug into the code enough to know how feasible that is yet. Ideas?

**Comment by realbuz** [comment]
I too am eagerly waiting for this to be available.

**Comment by VanCityGuy** [comment]
Also curious if this feature is being worked on.

**Comment by ncw** [comment]
@Saviq interesting idea..

So we might have 3 modes for `--max-transfer`
- hard cutoff at the limit (current)
- graceful stop after the limit is reached
- graceful stop before the limit is reached

I also have a patch for `--max-duration` which could use the same features.

So I propose a new flag `--cutoff-mode` with the following options
- `hard` - stop immediately the limit is reached
- `soft` or maybe `graceful` - finish existing transfers and finish when the limit is reached
- `cautious` - try to stop before the limit is reached

**Comment by g0kuz** [comment]
@ncw 

Could I test this in your beta? Can't seem to find any beta changelog if this is already active.

**Comment by TheLuBu** [comment]
Any news on this? Would love to hear about it

**Comment by Friday13th87** [comment]
i was using the cutoff method in the latest beta version and if i am using soft cutoff and have 3 transfers for example, it will wait till one of those is finished (soft cutoff) and will hard cutoff the other transfers.
if i am using --transfers 1 it is working as it should (as there is nothing to hard cutoff if the only transfer is finished)

**Comment by ncw** [comment]
@Friday13th87 do you think this is related to https://github.com/rclone/rclone/issues/4002 ?

**Comment by Friday13th87** [comment]
no i dont think so, as the behavior is completely different.
the cutoff is just not waiting for the end of all active transfers, its just waiting for one existing transfer to finish
