### ISSUE TITLE
rclone mount Windows: use next available drive letter

### ISSUE THREAD

**Issue by chrissv** [rclone/rclone#2678]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.43.1
- os/arch: windows/amd64
- go version: go1.11

#### What problem are you are trying to solve?
The built-in Windows "net use" command can take a wildcard instead of a specific drive letter when mapping a network drive. Windows will pick the next unused drive letter (after C:) for the mount point.

This request is to have the "rclone mount" command have the same functionality.

#### How do you think rclone should be changed to solve that?
It could be invoked with an argument: "rclone mount --use-next-drive cfg:"

**Comment by ncw** [comment]
This would be relatively easy to do.  There is a routine to do this already in rclone's tests!

What syntax does `net use` use to specify a wildcard instead of a specific drive letter?  Maybe rclone should use that syntax which will be familiar to Windows users?

**Comment by chrissv** [comment]
Unfortunately it uses an asterisk:
Specific drive letter: `net use f: \\share\mount`
Next available: `net use * \\share\mount`

I would not recommend matching that, as asterisks expand in the OS.
That's why a command-line argument sounds appropriate here.

Also, make sure you start looking for the next available drive letter at `C:` or later; `A:` and `B:` are historically reserved for floppy drives.
