### ISSUE TITLE
Advanced :backend: usage

### ISSUE THREAD

**Issue by The-OMG** [rclone/rclone#2681]
#### What is your current rclone version (output from `rclone version`)?
`rclone v1.43.1
- os/arch: linux/amd64
- go version: go1.11`

#### What problem are you are trying to solve?

> I have been scripting hot-swaping service accounts for large cloud to cloud transfers using Google 
> drive. I am wondering if it possible to:
> 
> 1. use the :backend: function with when I need to copy data from a remote that is already setup to a dynamic remote.
> 
> 2. Copy data from one dynamic remote to a second dynamic remote. 
> 
> So far in my testing, I have been unsuccessful in achieving my requests. What I learned so far is I can copy/move data within the same dynamic remote. For example 
> ```
> rclone move :drive:test01/ :drive:test02/
> ```
> The above works as expected. However, when I try a preconfigured remote as the source and a dynamic remote as the destination, the preconfigured remote is not recognized. For example
> ```
> rclone move teamdrive: :drive:test02/
> ```
> What actually happens is
> ```
> rclone move :drive: :drive:test02/
> ```
> No matter what remote I choose, both remotes are whatever is configured as :drive:

#### How do you think rclone should be changed to solve that?

Hopefully rclone can be modified to recognize a premade remote when using a dynamic remote. 

When using 2 dynamic remotes, I think any backend flags should apply to the :backend: that comes after. Example:
`rclone copy --drive-scope=drive '--drive-service-account-file=$HOME/.config/token1.json' '--drive-team-drive=0AEFojjZ0gu-9Uk9LKA'  :drive: --drive-scope=drive '--drive-service-account-file=$HOME/.config/token2.json' '--drive-team-drive=sdlikfu-ILDSY' :drive:` 

Synax would be `rclone [command] [backend 1 flags] [backend 1] [backend 2 flags] [backend 2] [all other rclone flags]`

**Comment by ncw** [comment]
As you've discovered when you do `--drive-scope=drive` it applies to all the `drive` remotes on the command line, dynamic or otherwise.

Rclone does have a way for you to do this, but you'll have to set environment variables instead

If you take a look at [this section](https://rclone.org/docs/#config-file) you'll see you can create remotes entirely with enviroment variables, and these won't get their config mixed up.

> When using 2 dynamic remotes, I think any backend flags should apply to the :backend: that comes after.

That is a nice idea, but unfortunately the command line parser I use doesn't support that kind of thing :-(

If you are unhappy with setting things as environment variables I could make a flag where you could say `--set remote:option=value` or something like that to be the equivalent of the environment variables

**Comment by The-OMG** [comment]
I appreciate your time with this stuff. 

So, with that new flag, I would be able to run a command like this?

```
RcloneArgs=(
            "--set :drive:drive-client-id=$CLIENT_ID"
            "--set :drive:drive-client-secret=$CLIENT_SECRET"
            "--set :drive:drive-scope=drive"
            "--set :drive:drive-service-account-file=$i"
            "--set :drive:drive-team-drive=$TD"
            "--backup-dir=:drive:/Backup/"
            "--drive-acknowledge-abuse"
            "--fast-list"
            "--max-transfer=730G"
            "--progress"
            "--track-renames"
            "--drive-chunk-size=$driveChunkSize"
        )
rclone sync "gdrive:" ":drive:$DEST" "${RcloneArgs[@]}"
```

And it would transfer from a preconfigured remote to a dynamic remote?

What about 2 dynamic remotes? How would I differentiate between two :drive: remotes?

**Comment by ncw** [comment]
> I appreciate your time with this stuff.
> 
> So, with that new flag, I would be able to run a command like this?
> 
> ```
> RcloneArgs=(
>             "--set :drive:drive-client-id=$CLIENT_ID"
>             "--set :drive:drive-client-secret=$CLIENT_SECRET"
>             "--set :drive:drive-scope=drive"
>             "--set :drive:drive-service-account-file=$i"
>             "--set :drive:drive-team-drive=$TD"
>             "--backup-dir=:drive:/Backup/"
>             "--drive-acknowledge-abuse"
>             "--fast-list"
>             "--max-transfer=730G"
>             "--progress"
>             "--track-renames"
>             "--drive-chunk-size=$driveChunkSize"
>         )
> rclone sync "gdrive:" ":drive:$DEST" "${RcloneArgs[@]}"
> ```

Something like that...

> And it would transfer from a preconfigured remote to a dynamic remote?
> 
> What about 2 dynamic remotes? How would I differentiate between two :drive: remotes?

You'd give each a different name so `--set remote1:drive-client-id=blah`  you'd need a `--set remote1:type=drive` too.  This is exactly equivalent to the way the environment variable setting works at the moment.

**Comment by The-OMG** [comment]
This would be awesome if the --set flag was built. I think this would be a better solution as it would allow my code to be cross-platform.

**Comment by ncw** [comment]
@The-OMG would you like to help implement this?

**Comment by ivandeex** [comment]
@ncw 
If I don't miss something, this request is superseded by #4996

**Comment by ivandeex** [comment]
Closing in favor of #4996
