### ISSUE TITLE
rclone often freeze (mount cmd) (mega)

### ISSUE THREAD

**Issue by chanokdanai** [rclone/rclone#2685]
I tried to mount mega drive and most of the time it's freeze when i access file or folder,what did i do wrong, it is because my mega contain too many files?

**Comment by ncw** [comment]
Does `rclone lsf yourmegaremote:` work OK?  How long does it take?

The mega remote has to read all the files into memory first so it can be slow doing that, but once it has done that it should be very quick.

**Comment by chanokdanai** [comment]
thanks for reply and...
yes it does work,but it take like 3-7min to open a folder,is it nomarl?

**Comment by ncw** [comment]
> thanks for reply and...
> yes it does work,but it take like 3-7min to open a folder,is it nomal?

That does sound like a long time!

How many files have you got in your mega?  And how fast is your internet connection?

`rclone size yourmegaremote:` will tell you how many files there are.

If you open an incognito browser window and log in again to mega, how long does it take to start working?

**Comment by MoralCode** [comment]
i've also been having some freezing issues (dolphin file manager in Kubuntu 18.04 using rclone v1.44) and I have noticed in my very limited testing that it works a lot better when you use the [`--vfs-cache-mode writes` option](https://rclone.org/commands/rclone_mount/#file-caching) in your `rclone mount` command.
Hope this helps

**Comment by animosity22** [comment]
If you still have a question, please ask on the forums and we can help out.

Closing out as this is stale.
