### ISSUE TITLE
google drive lacking support for "application/vnd.google-apps.script" mime type

### ISSUE THREAD

**Issue by micrat** [rclone/rclone#2692]
I get the following error when running rclone on google drive:

`2018/10/23 09:29:04 DEBUG : script: No export formats found for "application/vnd.google-apps.script" `

All the files of this mime type are subsequently disregarded.

I think the error could be solved by adding the line 
`"application/vnd.google-apps.script":                            ".json",`
to the mime-types definition block:
https://github.com/ncw/rclone/blob/c5ac96e9e7afd2e11b69233ed3671e8ad05d24a9/backend/drive/drive.go#L84

**Comment by B4dM4n** [comment]
Have you tried adding `--drive-export-formats=json` to your command?
What is the exact command you used?

**Comment by micrat** [comment]
Thanks, with the option you suggested I get no more errors and the scripts are downloaded from the cloud.
The command I use for syncing:
`rclone.exe sync drive_google_com: D:\Documents\cloud\drive.google.com\account\ --fast-list --config="D:\Documents\cloud\rclone.conf" --log-file D:\Documents\cloud\drive.google.com\account\\..\drive_google_com_sync_download_20181024T113226.log --log-level DEBUG --bwlimit 10k --tpslimit 10 --drive-export-formats=json`

**The sync process lasts for 2 to 10 minutes, even if there are no transferred files.**
Here annexed the log file. I experience a lot of warnings `pacer: Rate limited, sleeping for[...]`. Why I get these rate-limits?

[drive_google_com_sync_download_20181024T113226.log](https://github.com/ncw/rclone/files/2509927/drive_google_com_sync_download_20181024T113226.log)

Maybe the long duration is only due to the large number of files to be checked? Or it is due to the rate limit?
`Checks:             15785 / 15785, 100%`

In the configuration I set the keys
client_id = [...]
client_secret = [...]
following the instructions found in [https://rclone.org/drive/#making-your-own-client-id](https://rclone.org/drive/#making-your-own-client-id) but I didn't experience any benefit.

Any suggestion?

**Comment by animosity22** [comment]
This looks to be a stale issue. If you still have any questions, please post on the forums and we'll be happy to help out!
