### ISSUE TITLE
cache-writes does not work with cache-tmp-upload-path

### ISSUE THREAD

**Issue by FloGa** [rclone/rclone#2700]
#### What is the problem you are having with rclone?

Hi! Unless I mis-understood the respective features, I consider it a bug that you cannot use `cache-tmp-upload-path` together with `cache-writes` when using `mount` on a `cache` remote.

As I understood it:

- `cache-tmp-upload-path` is used to create a persistent queue of files to upload, with automatic resuming if the `mount` is killed and restarted again (maybe through a computer reboot)

- `cache-writes` writes the file to the cache before uploading it, so I can work with it immediately, without the need to download it first

By looking at the code in the cache backend, you made those two features mutually exclusive through an if-then-else block. Now, as soon as the file is uploaded from the tmp-path, it is deleted without copying it to the cache folder. I have to download the file I just uploaded again to work with it.

Is it possible to combine those two features in a future release or is this behavior intentional? If it is the latter, why?

#### What is your rclone version (output from `rclone version`)

```
rclone v1.44
- os/arch: linux/amd64
- go version: go1.10.3
```

The code in question is the current master as of 2018-10-25 (SHA1: `e76cf1217ff9a741387c8730073625f33cc4d57a`)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Gentoo Linux, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Dropbox together with Cache backend

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone -v mount db_mount_cache: mnt/`

```
$ rclone config show db_mount_cache
--------------------
[db_mount_cache]
type = cache
remote = db:rclone
plex_url = 
plex_username = 
plex_password = 
chunk_size = 
info_age = 
chunk_total_size = 
tmp_upload_path = /home/floga/.cache/rclone/cache-backend/db_mount_cache_uploads
writes = true
--------------------
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I created a small file in the mounted (empty) directory and tried to read it after uploading. As the log shows, the read fails at first, but the file is downloaded and displayed shortly afterwards.

Please note that the message `Cache Writes: enabled` is not shown. This is another bug, I will open a pull request for this. `cache-writes` is enabled via config option shown above.

```
$ rclone -vv mount db_mount_cache: mnt/
2018/10/26 15:47:53 DEBUG : rclone: Version "v1.44" starting with parameters ["rclone" "-vv" "mount" "db_mount_cache:" "mnt/"]
2018/10/26 15:47:53 DEBUG : Using config file from "/home/floga/.config/rclone/rclone.conf"
2018/10/26 15:47:53 DEBUG : db_mount_cache: wrapped db:rclone at root 
2018/10/26 15:47:53 INFO  : db_mount_cache: Cache DB path: /home/floga/.cache/rclone/cache-backend/db_mount_cache.db
2018/10/26 15:47:53 INFO  : db_mount_cache: Cache chunk path: /home/floga/.cache/rclone/cache-backend/db_mount_cache
2018/10/26 15:47:53 INFO  : db_mount_cache: Chunk Memory: true
2018/10/26 15:47:53 INFO  : db_mount_cache: Chunk Size: 5M
2018/10/26 15:47:53 INFO  : db_mount_cache: Chunk Total Size: 10G
2018/10/26 15:47:53 INFO  : db_mount_cache: Chunk Clean Interval: 1m0s
2018/10/26 15:47:53 INFO  : db_mount_cache: Workers: 4
2018/10/26 15:47:53 INFO  : db_mount_cache: File Age: 6h0m0s
2018/10/26 15:47:53 INFO  : db_mount_cache: Upload Temp Rest Time: 15s
2018/10/26 15:47:53 INFO  : db_mount_cache: Upload Temp FS: /home/floga/.cache/rclone/cache-backend/db_mount_cache_uploads
2018/10/26 15:47:53 DEBUG : Adding path "cache/expire" to remote control registry
2018/10/26 15:47:53 DEBUG : Adding path "cache/stats" to remote control registry
2018/10/26 15:47:53 DEBUG : Adding path "cache/fetch" to remote control registry
2018/10/26 15:47:53 DEBUG : Cache remote db_mount_cache:: Mounting on "mnt/"
2018/10/26 15:47:53 INFO  : Cache remote db_mount_cache:: poll-interval is not supported by this remote
2018/10/26 15:47:53 DEBUG : Adding path "vfs/forget" to remote control registry
2018/10/26 15:47:53 DEBUG : Adding path "vfs/refresh" to remote control registry
2018/10/26 15:47:53 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2018/10/26 15:47:53 DEBUG : : Root: 
2018/10/26 15:47:53 DEBUG : : >Root: node=/, err=<nil>
2018/10/26 15:47:53 DEBUG : /: Lookup: name=".Trash"
2018/10/26 15:47:53 DEBUG : Cache remote db_mount_cache:: list ''
2018/10/26 15:47:53 DEBUG : : list: error: missing cached dir: 
2018/10/26 15:47:53 DEBUG : : list: read 0 from temp fs
2018/10/26 15:47:53 DEBUG : : list: temp fs entries: []
2018/10/26 15:47:54 DEBUG : : list: read 0 from source
2018/10/26 15:47:54 DEBUG : : list: source entries: []
2018/10/26 15:47:54 DEBUG : : list: cached directories: 0
2018/10/26 15:47:54 DEBUG : : list: cached dir: '', cache ts: 2018-10-26 15:47:54.256199913 +0200 CEST m=+0.792248203
2018/10/26 15:47:54 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/10/26 15:47:54 DEBUG : /: Lookup: name=".Trash-1000"
2018/10/26 15:47:54 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/10/26 15:48:02 DEBUG : /: Lookup: name="small_file"
2018/10/26 15:48:02 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2018/10/26 15:48:02 DEBUG : /: Create: name="small_file"
2018/10/26 15:48:02 DEBUG : small_file: Open: flags=O_WRONLY|O_CREATE|O_TRUNC
2018/10/26 15:48:02 DEBUG : small_file: >Open: fd=small_file (w), err=<nil>
2018/10/26 15:48:02 DEBUG : /: >Create: node=small_file, handle=&{small_file (w)}, err=<nil>
2018/10/26 15:48:02 DEBUG : small_file: Attr: 
2018/10/26 15:48:02 DEBUG : small_file: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
2018/10/26 15:48:02 DEBUG : &{small_file (w)}: Flush: 
2018/10/26 15:48:02 DEBUG : small_file: WriteFileHandle.Flush unwritten handle, writing 0 bytes to avoid race conditions
2018/10/26 15:48:02 DEBUG : &{small_file (w)}: >Flush: err=<nil>
2018/10/26 15:48:02 DEBUG : &{small_file (w)}: Write: len=10, offset=0
2018/10/26 15:48:02 DEBUG : &{small_file (w)}: >Write: written=10, err=<nil>
2018/10/26 15:48:02 DEBUG : &{small_file (w)}: Flush: 
2018/10/26 15:48:02 DEBUG : Cache remote db_mount_cache:: File to upload is small (10 bytes), uploading instead of streaming
2018/10/26 15:48:02 DEBUG : Cache remote db_mount_cache:: put data at 'small_file'
2018/10/26 15:48:02 DEBUG : : cache: expired 
2018/10/26 15:48:02 INFO  : small_file: put: uploaded in temp fs
2018/10/26 15:48:02 INFO  : small_file: put: queued for upload
2018/10/26 15:48:02 DEBUG : small_file: pending upload found
2018/10/26 15:48:02 DEBUG : small_file: put: added to cache
2018/10/26 15:48:02 DEBUG : : cache: expired 
2018/10/26 15:48:02 INFO  : : put: cache expired
2018/10/26 15:48:02 DEBUG : small_file: object hash cached: 5980838a86634fbd3e97249cedecd6a556c53a8945a4c92e17251209431c6345
2018/10/26 15:48:02 INFO  : small_file: Copied (new)
2018/10/26 15:48:02 DEBUG : &{small_file (w)}: >Flush: err=<nil>
2018/10/26 15:48:02 DEBUG : &{small_file (w)}: Release: 
2018/10/26 15:48:02 DEBUG : small_file: WriteFileHandle.Release nothing to do
2018/10/26 15:48:02 DEBUG : &{small_file (w)}: >Release: err=<nil>
2018/10/26 15:48:17 INFO  : small_file: background upload: started upload
2018/10/26 15:48:18 DEBUG : small_file: Couldn't find file - need to transfer
2018/10/26 15:48:19 INFO  : small_file: Copied (new)
2018/10/26 15:48:19 INFO  : small_file: Deleted
2018/10/26 15:48:19 INFO  : small_file: background upload: uploaded entry
2018/10/26 15:48:19 DEBUG : : cache: expired 
2018/10/26 15:48:19 INFO  : small_file: finished background upload
2018/10/26 15:48:51 DEBUG : small_file: Open: flags=OpenReadOnly
2018/10/26 15:48:51 DEBUG : small_file: Open: flags=O_RDONLY
2018/10/26 15:48:51 DEBUG : small_file: >Open: fd=small_file (r), err=<nil>
2018/10/26 15:48:51 DEBUG : small_file: >Open: fh=&{small_file (r)}, err=<nil>
2018/10/26 15:48:51 DEBUG : small_file: Attr: 
2018/10/26 15:48:51 DEBUG : small_file: >Attr: a=valid=1s ino=0 size=10 mode=-rw-r--r--, err=<nil>
2018/10/26 15:48:51 DEBUG : &{small_file (r)}: Read: len=4096, offset=0
2018/10/26 15:48:51 DEBUG : small_file: ChunkedReader.openRange at 0 length 134217728
2018/10/26 15:48:51 DEBUG : small_file: moving offset set from 0 to 0
2018/10/26 15:48:51 DEBUG : small_file: ChunkedReader.Read at 0 length 4096 chunkOffset 0 chunkSize 134217728
2018/10/26 15:48:51 DEBUG : small_file: 0: chunk retry storage: 0
2018/10/26 15:48:51 ERROR : worker-0 <small_file>: object open failed 0: open /home/floga/.cache/rclone/cache-backend/db_mount_cache_uploads/small_file: no such file or directory
2018/10/26 15:48:52 DEBUG : small_file: 0: chunk retry storage: 1
2018/10/26 15:48:52 DEBUG : small_file: 0: chunk retry storage: 2
2018/10/26 15:48:53 DEBUG : small_file: 0: chunk retry storage: 3
2018/10/26 15:48:53 DEBUG : Cache remote db_mount_cache:: starting cleanup
2018/10/26 15:48:53 DEBUG : small_file: 0: chunk retry storage: 4
2018/10/26 15:48:54 DEBUG : worker-0 <small_file>: partial downloaded chunk 0
2018/10/26 15:48:54 DEBUG : &{small_file (r)}: >Read: read=10, err=<nil>
2018/10/26 15:48:54 DEBUG : small_file: Attr: 
2018/10/26 15:48:54 DEBUG : small_file: >Attr: a=valid=1s ino=0 size=10 mode=-rw-r--r--, err=<nil>
2018/10/26 15:48:54 DEBUG : &{small_file (r)}: Flush: 
2018/10/26 15:48:54 DEBUG : small_file: object hash cached: 5980838a86634fbd3e97249cedecd6a556c53a8945a4c92e17251209431c6345
2018/10/26 15:48:54 DEBUG : &{small_file (r)}: >Flush: err=<nil>
2018/10/26 15:48:54 DEBUG : &{small_file (r)}: Release: 
2018/10/26 15:48:54 DEBUG : small_file: ReadFileHandle.Release closing
2018/10/26 15:48:54 DEBUG : small_file: cache reader closed 10
2018/10/26 15:48:54 DEBUG : &{small_file (r)}: >Release: err=<nil>
^C2018/10/26 15:49:04 DEBUG : rclone: Version "v1.44" finishing with parameters ["rclone" "-vv" "mount" "db_mount_cache:" "mnt/"]
2018/10/26 15:49:05 DEBUG : Cache remote db_mount_cache:: Services stopped
```

**Comment by darthShadow** [comment]
I believe this is by design. Any reason why you cannot simply increase the `--cache-tmp-wait-time` to allow for any reads or writes to finish before uploading the file?

**Comment by FloGa** [comment]
Thanks for your reply! The wait-time is alright with default settings, I just do not want the file to disappear from the cache right after uploading. I thought this is the whole point of the `cache-writes` feature. The upload queue should be an independent feature that can be used *besides* `cache-writes`, not *instead of*.

**Comment by darthShadow** [comment]
I doubt `cache-writes` is much more reliable than `cache-tmp-upload` since it doesn't guarantee that the file will be available for a certain amount of time. Depending on your `--cache-chunk-total-size` and the activity on the mount, the chunks could get flushed out the next minute or could get flushed out the next day also. The `--cache-tmp-upload` is much more reliable in such cases.

**Comment by FloGa** [comment]
But with `cache-writes`, the file / chunks could remain at least somewhat longer, depending on total size, as you say. If there is no other activity, the file remains present for quite a time, while with `tmp-upload` it gets deleted immediately after upload. The point is, the chunks get deleted anyway. Could there be problems if instead of deleting them right after the upload, they are copied to the cache first? (Depending if `cache-writes` is set, of course)

If there are no blocking objections, may I try to prepare a pull request for that? My experience with Go is quite small, but the change could be as small as an additional `if` block inside the `tmp-upload` case.

**Comment by ncw** [comment]
> If there are no blocking objections, may I try to prepare a pull request for that? My experience with Go is quite small, but the change could be as small as an additional `if` block inside the `tmp-upload` case.

My all means!  Check out [the contributing docs](https://github.com/ncw/rclone/blob/master/CONTRIBUTING.md).

**Comment by FloGa** [comment]
I'm afraid this is more complicated than I thought ... Since the "Offline Uploading" happens asynchronously, it seems I can't access the value of `cache-writes` anymore.

Afterall, invalidating the cache in such cases, as it is done currently, seems to be the best solution for this. The `move` command does the same thing, i.e. it removes the cached chunks, forcing a re-download when reading the moved file.

So, before breaking something, I prefer to leave it with the current behavior.

**Comment by animosity22** [comment]
If you still have a question, please ask on the forums and we are happy to help out. This looks very stale.

**Comment by hekmon** [comment]
The issue is still relevant (at least for the current v1.51.0):
https://github.com/rclone/rclone/blob/v1.51.0/backend/cache/cache.go#L1457

I don't think the `if`/`else if` tha FloGa was referencing to should be modifed: it is used when writting data to the cache directly. So the first time the data comes in it should be directed to the tmp folder if set. But where I think FloGa is right is that once the upload is finished, before removing the file from the tmp dir, its content should go to the read cache if `cache-writes` is on.

That is, if before/during the upload the file is used as read cache directly ? (I am not sure it does, but  should not it be the case ?)

**Comment by animosity22** [comment]
@hekmon  - The cache backend has no maintainer and is most likely going to be deprecated with the new VFS cache changes so there isn't much point for me to open it back up.

if you'd like to submit a pull request or a fix, I'm sure @ncw would take a look and merge it if applicable.

**Comment by hekmon** [comment]
Ho I did not know that ! I am currently benchmarking/tweaking several values for the following layout:
* drive
* cache (with tmp-upload for async upload)
* crypt
* VFS/FUSE (with cache write to have all regular FS operations on the mount)

This is almost perfect, I was just waiting for async write in VFS #3186 because right now the write/close still wait for the encrypted part to be written within the cache tmp upload which make it pretty slow (first write to the vfs cache them crypt them write the crypted file and finally return to the top caller). My ideal setup would have been:
`write <sync> VFS write cache <async> crypt <sync> cache tmp folder <async> drive upload`

It is a shame the cache backend will be deprecated as I think it will be more space efficient (chunks) than the vfs read cache (full file): let's say an app seek a particular position in a file just to read 1MiB, the cache layer would much more efficient than the full/read cache from vfs, if the file is several GiB big file this would make a big difference (best exemple would be seeding part of ur favorite distro over rclone ;)

As I would love to take the time to sneak in this module, my spare time is currently on a very tight budget unfortunatly :(

Be aware that the mount documentation for VFS full cache still recommends to take a look at the cache backend instead by stating it is more efficient. If the cache backend is about to be deprecated, it would be good not to send people down this road any more :)

**Comment by ncw** [comment]
> It is a shame the cache backend will be deprecated as I think it will be more space efficient (chunks) than the vfs read cache (full file)

The new VFS backend will cache parts of files like the cache backend you'll be pleased to hear!

It also fixes the write/close delay with async writeback...

> Be aware that the mount documentation for VFS full cache still recommends to take a look at the cache backend instead by stating it is more efficient. If the cache backend is about to be deprecated, it would be good not to send people down this road any more :)

Noted!

**Comment by hekmon** [comment]
> The new VFS backend will cache parts of files like the cache backend you'll be pleased to hear!

You have no idea <3
 
> It also fixes the write/close delay with async writeback...

<3<3

Is https://github.com/rclone/rclone/issues/3186 the right issue to track then or is there others ? 

Thanks again :)

**Comment by ncw** [comment]
> Is #3186 the right issue to track then or is there others ?

That is a good one - I'll post updates to that in due course!
