### ISSUE TITLE
All modifications blocked while file from cache is being uploaded

### ISSUE THREAD

**Issue by darthShadow** [rclone/rclone#2703]
#### What is the problem you are having with rclone?

As soon as any file in the `--cache-tmp-upload` queue starts uploading, all modifications in the mount get blocked until the upload is done.

Related Forum Post: https://forum.rclone.org/t/sonarr-radarr-hangs-when-using-cache-temp-upload-path/5477/41

#### What is your rclone version (output from `rclone version`)

```
rclone v1.44
- os/arch: linux/amd64
- go version: go1.11.1
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

```
Ubuntu 16.04.5 64-bit
```

####  Which cloud storage system are you using? (eg Google Drive)

```
Google Drive
```

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
/home/darthshadow/rclone/bin/rclone mount GCrypt: /home/darthshadow/GMedia \
   --allow-other \
   --dir-cache-time=24h \
   --cache-db-purge \
   --cache-db-path=/dev/shm/rclone/ \
   --cache-chunk-path=/home/darthshadow/ssd/ \
   --cache-workers=4 \
   --cache-tmp-upload-path=/home/darthshadow/rclone/tmp_upload/ \
   --cache-tmp-wait-time=6h \
   --cache-chunk-size=128M \
   --cache-chunk-total-size=75G \
   --cache-chunk-clean-interval=2m \
   --cache-info-age=36h \
   --drive-chunk-size=128M \
   --vfs-read-chunk-size=256M \
   --vfs-read-chunk-size-limit=off \
   --vfs-cache-mode=writes \
   --vfs-cache-max-age=3h \
   --vfs-cache-poll-interval=1m \
   --cache-dir=/home/darthshadow/rclone/ \
   --buffer-size=0 \
   --attr-timeout=1s \
   --umask=002 \
   --log-file=/home/darthshadow/rclone/rclone.log \
   --stats=1m \
   --stats-log-level=NOTICE \
   -v
```

Will add logs later once I can disturb my mount and turn on debug logging.

**Comment by rfsbraz** [comment]
I can confirm this also happens to me on Windows

**Comment by dragonflyuk** [comment]
Does anyone have any workarounds for this issue, it really cripples sonarr\radarr if you have more than a few downloads a day.

**Comment by runaroundhome** [comment]
I had the same issue and ended up using a mergerfs/rclone hybrid setup which works great, no slow downs while uploading, and can add while it's uploading.
Not the easiest solution to setup though, but once it's setup it's amazing.

More details here:
https://forum.rclone.org/t/mergerfs-questions/8668/2

**Comment by dragonflyuk** [comment]
Thanks I'll have a play with MergeFS

**Comment by ivandeex** [comment]
@darthShadow @rfsbraz Does the problem reproduce with rclone 1.54?

**Comment by darthShadow** [comment]
Considering the cache backend is deprecated now (after all the functionality has been added to the vfs layer, which doesn't have this bug), I think this issue can be closed.

**Comment by darthShadow** [comment]
@ncw @ivandeex Do you think we can close all the bugs tagged with the "Remote: Cache" label? We can probably keep only the enhancements on a case-by-case basis if they have not already been implemented.

**Comment by ivandeex** [comment]
Closed some of those except where discussion was one year fresh
