### ISSUE TITLE
rclone and systemd

### ISSUE THREAD

**Issue by cberni** [rclone/rclone#2704]
**I follow the wiki https://github.com/ncw/rclone/wiki/rclone-fstab-mount-helper-script an installed with systemd.**

**After use the command "systemctl start gcloud.mount" I get the follow error:**
root@xxxxx:~# systemctl start gcloud.mount
Job for gcloud.mount failed.
See "systemctl status gcloud.mount" and "journalctl -xe" for details.

**int the "/var/log/syslog"**
Oct 26 15:43:43 xxxxx systemd[1]: Mounting rclone mount for gcloud:xxxxx...
Oct 26 15:43:43 xxxxx systemd[1]: gcloud.xxxxx: Mount process finished, but there is no mount.
Oct 26 15:43:43 xxxxx systemd[1]: gcloud.xxxxx: Failed with result 'protocol'.
Oct 26 15:43:43 xxxxx systemd[1]: Failed to mount rclone mount for gcloud:xxxxx.

**BUT the mount start normally:**
root@xxxxx:~# systemctl status gcloud.mount
● gcloud.mount - rclone mount for gcloud:xxxxx
   Loaded: loaded (/etc/systemd/system/gcloud.mount; disabled; vendor preset: enabled)
   Active: active (mounted) (Result: protocol) since Fri 2018-10-26 15:43:43 -03; 2min 25s ago
    Where: /gcloud
     What: gcloud:xxxxx
  Process: 20227 ExecUnmount=/bin/umount /gcloud -c (code=exited, status=0/SUCCESS)
  Process: 22065 ExecMount=/bin/mount rclonefs#gcloud:xxxxx /gcloud -t fuse -o config=/etc/animati/xxxxx-rclone.conf,allow-other (code=exited, status=0/SUC
    Tasks: 6 (limit: 4915)
   CGroup: /system.slice/gcloud.mount
           └─22068 rclone mount --config=/etc/animati/xxxxx-rclone.conf --allow-other gcloud:xxxxx /gcloud

**my mount file: (gcloud.mount)**
[Unit]
Description=rclone mount for gcloud:xxxxx
Requires=systemd-networkd.service
Wants=network-online.target
After=network-online.target

[Mount]
What=rclonefs#gcloud:xxxxx
Where=/gcloud
Type=fuse
Options=config=/etc/animati/xxxxx-rclone.conf,allow-other
TimeoutSec=300

[Install]
WantedBy=multi-user.target

**Is there a bug or should I mistaking something?**

**Comment by animosity22** [comment]
If you still have an issue with the mount, please ask on the forums and we are happy to help.
