### ISSUE TITLE
rclone sync use sha1 for local/smb shares

### ISSUE THREAD

**Issue by Exocomp** [rclone/rclone#2708]
My apologies if this has been answered before but I have searched the doc and all I see is it says "md5 or sha1" but not how I can force it to always use sha1.

When transferring files locally or to an smb share show can I use the sync verb to force it to use sha1 only when comparing files ?

**Comment by Exocomp** [comment]
I thought that md5 is broken as a hashing algorithm as it can produce collisions and can no longer be considered 100% safe for file integrity.  I guess for some things you don't necessarily care about it is file but for mission critical things it can't be trusted.

**Comment by ncw** [comment]
> I thought that md5 is broken as a hashing algorithm as it can produce collisions and can no longer be considered 100% safe for file integrity. I guess for some things you don't necessarily care about it is fine but for mission critical things it can't be trusted.

To be precise, MD5 has what is called a pre-image attack.  As in I can generate two files A & B with the same MD5SUM.  However no-one has figured out given an existing file C how to generate a file D with the same MD5SUM.

So I standy by my comment that MD5 is still good for checking file integrities!

**Comment by animosity22** [comment]
This looks answered and solved. If you have any other questions, please feel free to ask on the forums.

**Comment by messense** [comment]
> Why is it important to you? Even though MD5 isn't recommended for crypto work now-a-days it is still a very good integrity check of files which is what rclone is using it for here.

Remote may only returns sha1 hash, for example some webdav server.
