### ISSUE TITLE
Google Drive API "batching" feature to increase write throughput 

### ISSUE THREAD

**Issue by TheLinuxGuy** [rclone/rclone#2718]
#### What is your current rclone version (output from `rclone version`)?
1.43

#### What problem are you are trying to solve?
Hitting userRateLimit errors (there is a hard internal rate limit on a per user to 10 writes per second per user)

#### How do you think rclone should be changed to solve that?

Google engineers from Drive backend service have suggested all my write requests implement 
'batch' writes via API, see information here:

https://developers.google.com/drive/api/v3/batch

This will greatly improve performance and reduce amount of requests, sounds similar to what --fast-list did for improving rclone speed for validation and deduplication.

**Comment by ncw** [comment]
@B4dM4n - what do you think of this idea?

**Comment by B4dM4n** [comment]
Using batch requests sounds like a good idea. But I'm not sure if they can be used to upload files. The drive documentation says:
> Note: Currently, Google Drive does not support batch operations for media, either for upload or download.

I'm not sure which of the three [upload methods](https://developers.google.com/drive/api/v3/manage-uploads) could work with batch requests.
Using the multipart and resumable methods both resulted in a `404 Not Found` error when done via batch requests.

@TheLinuxGuy did you get any information how batch creating files should work?

**Comment by TheLinuxGuy** [comment]
I got some clarification and the documentation is correct, handling media (download or upload) via batch is not yet possible.

I am not sure how often multiple individual API calls during a 'sync' transaction are made by rclone but the batching could still enhance and reduce API calls to Google so more requests make it thru than single individual calls. I unfortunately lack some context on how that works but it seems like this may be good to implement eventually, probably not at a super high priority since it wouldn't improve media handling.

**Comment by ivandeex** [comment]
Closing after 2 years of inactivity
