### ISSUE TITLE
Make - - track-renames work with encrypted remotes

### ISSUE THREAD

**Issue by Bazzu85** [rclone/rclone#2721]
Hi, 
As title said can you update - - track-renames to work also on encrypted remotes?
Thx

**Comment by ncw** [comment]
This could be done using the same mechanism that cryptcheck uses, so using the hash(encrypted_file). To calculate this for a local file rclone has to download the nonce from the remote file, then encrypt the local file with the nonce and hash it on the fly. This would work for --track-renames purpose.

This code

https://github.com/ncw/rclone/blob/1f05d5bf4a515ba43dd59913fc83f87a7388e43b/cmd/cryptcheck/cryptcheck.go#L63-L114

Could be factored out and used when comparing files

**Comment by dandv** [comment]
Does this depend on #1033?

**Comment by ncw** [comment]
> Does this depend on #1033?

That would fix it instantly, but no it doesn't.

**Comment by ncw** [comment]
I've merged `--track-renames-strategy modtime` to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

**Comment by Xyz00777** [comment]
--track-renames is not working in actually version with encrypted drive :/
![2020-06-08_01h13_45](https://user-images.githubusercontent.com/52142054/83982229-4f725b00-a925-11ea-9235-851d2ae63f9c.png)

**Comment by calisro** [comment]
Are you using --track-renames-strategy modtime  ?

**Comment by Xyz00777** [comment]
i seen that i have not the newest version. actually uploading a big file... needs a few more hours than i will update and check again
