### ISSUE TITLE
Vmware ESXI

### ISSUE THREAD

**Issue by xxx31fr** [rclone/rclone#2735]
Hello,
I come back with this request, and i remember rclone is written in GO language.

I think I've found a way to run Go binaries on VMware ESXi.
https://blog.inkubate.io/run-unikernel-applications-on-vmware-vsphere-with-unik/
Maybe someone can try it and say me if it's possible, with that, to add a Google Drive storage as a Datastore.

Thnaks.

**Comment by animosity22** [comment]
This looks stale. If you have any questions, please ask on the forums.
