### ISSUE TITLE
Error copying file starting with empty space

### ISSUE THREAD

**Issue by antonhagg** [rclone/rclone#2744]
#### Output of `rclone version`
Rclone v1.44
-os/arch: windows/amd64
-go version: go1.11

#### Describe the issue
Tried to download multiple files from jottacloud. One of the files starts with a space and rclone seems to have trouble fetching it.

Like this: "/path/ file.txt"
Logfile shows: Failed to copy: failed to open source object: error 404: no.jotta.backup.errors.NoSuchPathException (Not found)

**Comment by ncw** [comment]
I haven't been able to replicate this with [the latest beta](https://beta.rclone.org) - can you try that?

**Comment by antonhagg** [comment]
Here is the output of a replicate of the problem with latest beta:

> 2018/11/20 00:45:29 DEBUG : rclone: Version "v1.44-097-g2191592e-beta" starting with parameters ["rclone" "copy" "jottacloud:hejsan\\testfolder" "e:\\rclone-v1.44\\hejsan" "--checksum" "--progress" "--log-file" "hejsan.txt" "--log-level" "DEBUG"]
2018/11/20 00:45:29 DEBUG : Using config file from "C:\\Users\\Ant\\.config\\rclone\\rclone.conf"
2018/11/20 00:45:29 INFO  : Local file system at \\?\e:\rclone-v1.44\hejsan: Waiting for checks to finish
2018/11/20 00:45:29 INFO  : Local file system at \\?\e:\rclone-v1.44\hejsan: Waiting for transfers to finish
**2018/11/20 00:45:29 ERROR :  Jottacloud with leading space.pdf: Failed to copy: failed to open source object: error 404: no.jotta.backup.errors.NoSuchPathException (Not Found)**
2018/11/20 00:45:29 INFO  : Jottacloud.pdf: Copied (new)
2018/11/20 00:45:29 ERROR : Attempt 1/3 failed with 1 errors and: failed to open source object: error 404: no.jotta.backup.errors.NoSuchPathException (Not Found)
2018/11/20 00:45:30 INFO  : Local file system at \\?\e:\rclone-v1.44\hejsan: Waiting for checks to finish
2018/11/20 00:45:30 DEBUG : Jottacloud.pdf: Size and MD5 of src and dst objects identical
2018/11/20 00:45:30 DEBUG : Jottacloud.pdf: Unchanged skipping
2018/11/20 00:45:30 INFO  : Local file system at \\?\e:\rclone-v1.44\hejsan: Waiting for transfers to finish
2018/11/20 00:45:30 ERROR :  Jottacloud with leading space.pdf: Failed to copy: failed to open source object: error 404: no.jotta.backup.errors.NoSuchPathException (Not Found)
2018/11/20 00:45:30 ERROR : Attempt 2/3 failed with 1 errors and: failed to open source object: error 404: no.jotta.backup.errors.NoSuchPathException (Not Found)
2018/11/20 00:45:30 INFO  : Local file system at \\?\e:\rclone-v1.44\hejsan: Waiting for checks to finish
2018/11/20 00:45:30 DEBUG : Jottacloud.pdf: Size and MD5 of src and dst objects identical
2018/11/20 00:45:30 DEBUG : Jottacloud.pdf: Unchanged skipping
2018/11/20 00:45:30 INFO  : Local file system at \\?\e:\rclone-v1.44\hejsan: Waiting for transfers to finish
2018/11/20 00:45:30 ERROR :  Jottacloud with leading space.pdf: Failed to copy: failed to open source object: error 404: no.jotta.backup.errors.NoSuchPathException (Not Found)
2018/11/20 00:45:30 ERROR : Attempt 3/3 failed with 1 errors and: failed to open source object: error 404: no.jotta.backup.errors.NoSuchPathException (Not Found)
2018/11/20 00:45:30 Failed to copy: failed to open source object: error 404: no.jotta.backup.errors.NoSuchPathException (Not Found)
>

**Comment by albertony** [comment]
Space in start and end of names are currently, in the Jottacloud backend, being replaced with the Unicode symbol for space (␠) when uploading and replaced back when downloading. That is why such files uploaded from rclone can be downloaded with rclone, but if a file with such spaces have been uploaded by other clients (official clients, web ui, ...) you will get such an error if you try to download it with rclone, and if you upload it with rclone and then download it with a different client it will leave the names with the unicode symbol.

https://github.com/ncw/rclone/blob/26e2f1a9986bde3cd2d845433c308779e97fd4d9/backend/jottacloud/replace.go#L56-L59

The intention is to prevent users from getting into trouble when using the web ui, but it is unfortunate that it breaks "compatibility" between different clients...

See also #2531 and #2750.

**Comment by ncw** [comment]
Hmm, yes, maybe we need to change this too.

I think breaking the web client is less important than general compatibility

**Comment by albertony** [comment]
Initial/trailing space characters are no longer being replaced by the Jottacloud backend, since the introduction of refactored file name encoding in v1.50 (which looks very good by the way), so shouldn't this issue be solved?

I did a retest on latest version, v1.51, and were able to successfully copy a file with space in the beginning of the name to the backend and back again. I could upload such a file using an official (whitelabel) web ui, and download it with rclone, with the initial space intact. In the web gui the file looks like it does not have the initial space. When downloading from the web ui the initial space are replaced with an underscore character (windows explorer does not allow me to create files with initial space either, but it is possible to do from command prompt etc). Hopefully I am not fooling myself in any way during the testing, but seems to work as it should now...?

Ref
https://rclone.org/jottacloud/#restricted-filename-characters
https://rclone.org/overview/#encoding

**Comment by ncw** [comment]
Yes I think this is working properly now.

Note that this is tested by the integration tests

```
        --- PASS: TestIntegration/FsMkdir/FsEncoding (24.18s)
            --- PASS: TestIntegration/FsMkdir/FsEncoding/control_chars (2.17s)
                fstests.go:604: testing "␀␁␂␃␄␅␆␇␈␉␊␋␌␍␎␏␐␑␒␓␔␕␖␗␘␙␚␛␜␝␞␟␡"
            --- PASS: TestIntegration/FsMkdir/FsEncoding/dot (1.42s)
                fstests.go:604: testing "．"
            --- PASS: TestIntegration/FsMkdir/FsEncoding/dot_dot (1.84s)
                fstests.go:604: testing "．．"
            --- PASS: TestIntegration/FsMkdir/FsEncoding/punctuation (0.94s)
                fstests.go:604: testing "!\"#$%&'()*+,-.／:;<=>?@[\\]^_`{|}~"
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_space (1.01s)
                fstests.go:604: testing " leading space"
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_tilde (1.21s)
                fstests.go:604: testing "~leading tilde"
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_CR (3.19s)
                fstests.go:604: testing "␍leading CR"
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_LF (1.19s)
                fstests.go:604: testing "␊leading LF"
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_HT (1.09s)
                fstests.go:604: testing "␉leading HT"
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_VT (1.13s)
                fstests.go:604: testing "␋leading VT"
            --- PASS: TestIntegration/FsMkdir/FsEncoding/leading_dot (1.09s)
                fstests.go:604: testing ".leading dot"
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_space (1.17s)
                fstests.go:604: testing "trailing space "
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_CR (1.04s)
                fstests.go:604: testing "trailing CR␍"
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_LF (1.37s)
                fstests.go:604: testing "trailing LF␊"
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_HT (0.97s)
                fstests.go:604: testing "trailing HT␉"
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_VT (1.08s)
                fstests.go:604: testing "trailing VT␋"
            --- PASS: TestIntegration/FsMkdir/FsEncoding/trailing_dot (0.98s)
                fstests.go:604: testing "trailing dot."
            --- PASS: TestIntegration/FsMkdir/FsEncoding/invalid_UTF-8 (1.09s)
                fstests.go:604: testing "invalid utf-8\xfe"
```

And here are the things we actually replace

https://github.com/rclone/rclone/blob/d119bfd934545ea3e94b888c6660e8199c643f5f/backend/jottacloud/jottacloud.go#L167-L172

So I'll close this now :-)
