### ISSUE TITLE
aes encrypt cannot use aes-ni on 32bit linux

### ISSUE THREAD

**Issue by bhxch** [rclone/rclone#2747]
#### What is the problem you are having with rclone?
High cpu load when uploading files.

#### What is your rclone version (output from `rclone version`)
rclone v1.44
- os/arch: linux/386
- go version: go1.11.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
CentOS6 32bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive and OneDrive.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy --verbose --cpuprofile=rclone.prof --transfers 2 --checkers 2 --contimeout 60s --timeout 300s --retries 10 --low-level-retries 30 --stats 1s example:src/ example2:de/

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
It's normal, and I have found why it have happend.

**Comment by bhxch** [comment]
When rclone copy runs on the centos6 32bit, it cannot use aes-ni.
I have used 'cat /proc/cpuinfo' to check can my cpu use aes-ni. and it can.
and i have run a speed test using openssl 1.0.0.1 with the aes-in engine on and open.so i'm sure i can use aes-ni on my cpu.

I found it by use go tools.
Here is the output of the 32bit os when i run top20:
`Showing nodes accounting for 130.69s, 96.67% of 135.19s total
Dropped 319 nodes (cum <= 0.68s)
Showing top 20 nodes out of 72
      flat  flat%   sum%        cum   cum%
    51.93s 38.41% 38.41%     51.93s 38.41%  crypto/cipher.(*gcm).mul /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/crypto/cipher/gcm.go
    46.54s 34.43% 72.84%     46.54s 34.43%  crypto/aes.encryptBlockGo /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/crypto/aes/block.go
    14.59s 10.79% 83.63%     14.74s 10.90%  syscall.Syscall /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/syscall/asm_linux_386.s
     3.52s  2.60% 86.23%      3.52s  2.60%  crypto/cipher.fastXORWords /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/crypto/cipher/xor.go
     2.72s  2.01% 88.25%      2.72s  2.01%  runtime.futex /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/sys_linux_386.s
     2.65s  1.96% 90.21%     55.51s 41.06%  crypto/cipher.(*gcm).counterCrypt /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/crypto/cipher/gcm.go
     1.49s  1.10% 91.31%      1.49s  1.10%  crypto/cipher.getUint64 /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/crypto/cipher/gcm.go (inline)
     1.31s  0.97% 92.28%     54.51s 40.32%  crypto/cipher.(*gcm).updateBlocks /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/crypto/cipher/gcm.go
     1.31s  0.97% 93.25%      1.31s  0.97%  runtime.memmove /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/memmove_386.s
     1.09s  0.81% 94.05%     47.89s 35.42%  crypto/aes.(*aesCipher).Encrypt /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/crypto/aes/cipher.go
     0.93s  0.69% 94.74%      4.45s  3.29%  crypto/cipher.xorWords /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/crypto/cipher/xor.go
     0.91s  0.67% 95.41%      0.91s  0.67%  runtime.usleep /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/sys_linux_386.s
     0.75s  0.55% 95.97%      0.75s  0.55%  crypto/cipher.gcmInc32 /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/crypto/cipher/gcm.go
     0.63s  0.47% 96.43%      0.68s   0.5%  time.now /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/timestub.go
     0.06s 0.044% 96.48%     59.16s 43.76%  io.(*LimitedReader).Read /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/io/io.go
     0.06s 0.044% 96.52%     70.25s 51.96%  net/http.persistConnWriter.Write /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/http/transport.go
     0.06s 0.044% 96.57%      1.12s  0.83%  runtime.sysmon /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/proc.go
     0.05s 0.037% 96.60%      1.01s  0.75%  github.com/ncw/rclone/fs/fshttp.(*timeoutConn).nudgeDeadline /home/travis/gopath/src/github.com/ncw/rclone/fs/fshttp/http.go
     0.05s 0.037% 96.64%     13.11s  9.70%  net.(*netFD).Write /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/fd_unix.go
     0.04s  0.03% 96.67%     58.11s 42.98%  crypto/tls.(*Conn).readRecord /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/crypto/tls/conn.go`

I found that it's the ase encrypt use too much cpu cycle. and rclone use "gcm.go" and "block.go" to encrypt. so i guess it haven't use the aes-ni.

then i reinstall the os.the new os is centos7 x86_64. it's a 64bit os.
and here is the output this time:
`Showing nodes accounting for 14.50s, 91.54% of 15.84s total
Dropped 188 nodes (cum <= 0.08s)
Showing top 20 nodes out of 89
      flat  flat%   sum%        cum   cum%
     9.63s 60.80% 60.80%      9.75s 61.55%  syscall.Syscall /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/syscall/asm_linux_amd64.s
     1.34s  8.46% 69.26%      1.34s  8.46%  crypto/aes.gcmAesDec /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/crypto/aes/gcm_amd64.s
     1.30s  8.21% 77.46%      1.30s  8.21%  crypto/aes.gcmAesEnc /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/crypto/aes/gcm_amd64.s
     0.87s  5.49% 82.95%      0.87s  5.49%  runtime.memmove /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/memmove_amd64.s
     0.47s  2.97% 85.92%      0.47s  2.97%  runtime.futex /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/sys_linux_amd64.s
     0.22s  1.39% 87.31%      0.22s  1.39%  runtime.usleep /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/sys_linux_amd64.s
     0.18s  1.14% 88.45%      0.20s  1.26%  time.now /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/timestub.go
     0.07s  0.44% 88.89%      1.47s  9.28%  crypto/tls.(*halfConn).encrypt /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/crypto/tls/conn.go
     0.07s  0.44% 89.33%      0.19s  1.20%  internal/poll.runtime_pollSetDeadline /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/netpoll.go
     0.05s  0.32% 89.65%      0.08s  0.51%  runtime.deferreturn /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/panic.go
     0.05s  0.32% 89.96%      0.08s  0.51%  runtime.reentersyscall /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/proc.go
     0.04s  0.25% 90.21%      3.13s 19.76%  crypto/tls.(*Conn).readRecord /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/crypto/tls/conn.go
     0.03s  0.19% 90.40%     10.60s 66.92%  crypto/tls.(*Conn).writeRecordLocked /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/crypto/tls/conn.go
     0.03s  0.19% 90.59%      0.39s  2.46%  github.com/ncw/rclone/fs/fshttp.(*timeoutConn).nudgeDeadline /home/travis/gopath/src/github.com/ncw/rclone/fs/fshttp/http.go
     0.03s  0.19% 90.78%      8.58s 54.17%  net.(*conn).Write /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/net/net.go
     0.03s  0.19% 90.97%      0.09s  0.57%  runtime.getitab /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/runtime/iface.go
     0.03s  0.19% 91.16%      1.40s  8.84%  syscall.Read /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/syscall/syscall_unix.go
     0.02s  0.13% 91.29%      3.32s 20.96%  bufio.(*Reader).Read /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/bufio/bufio.go
     0.02s  0.13% 91.41%     10.71s 67.61%  bufio.(*Writer).Flush /home/travis/.gimme/versions/go1.11.1.linux.amd64/src/bufio/bufio.go
     0.02s  0.13% 91.54%     10.41s 65.72%  github.com/ncw/rclone/fs/fshttp.(*timeoutConn).readOrWrite /home/travis/gopath/src/github.com/ncw/rclone/fs/fshttp/http.go`

this time, the program use "gcm_amd64.s" to encrypt. so the cpu usage is low.I think rclone use aes-ni to encrypt this time.

although the problem has been solved, i want to know the bug is belong to rclone or go liberary?

**Comment by ncw** [comment]
I took a quick look at the go source code and there are no assembler files for 386, so I would say that use of AES-NI is not implemented in the go standard library.

https://github.com/golang/go/tree/master/src/crypto/aes

This is probably the closest issue: https://github.com/golang/go/issues/4299

I'm sure that if you wanted to contribute some code then the go team would like to merge it :-)

**Comment by bhxch** [comment]
Oh, I'm a newbie about writing go code. So, what i can do is just wait.
What about build rclone with openssl? Is it possible?

And the last, I think this diffident behaviour between 32bit and 64 bit os can be include in the docs of rclone.

**Comment by animosity22** [comment]
Feel free to send a pull request to update the docs if still needed. This looks solved so closing out.
