### ISSUE TITLE
rclone copy over and over again

### ISSUE THREAD

**Issue by NunoHiggs** [rclone/rclone#2748]
#### What is the problem you are having with rclone?

rclone sync over and over again

#### What is your rclone version (output from `rclone version`)

rclone version
rclone v1.43.1
- os/arch: linux/amd64
- go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux, 64bits

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

FLAGS_RCLONE=" -vv --ignore-checksum --ignore-existing   --ignore-size   --transfers 10 --dry-run"
rclone copy $FLAGS_RCLONE API1SHARE1: GSTORE014:MEDIA

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2018/11/19 15:10:09 DEBUG : SHARE02/Series/Series/1x01.avi: Destination exists, skipping
2018/11/19 15:10:09 NOTICE: SHARE02/Series/Series/1x01.avi: Not copying as --dry-run

It sees the file, but it copies it anyway.
What am i missing?

Thanks.

**Comment by animosity22** [comment]
Did you try running with the latest version and see if that fixes it? 1.44 is the latest stable.

**Comment by NunoHiggs** [comment]
Hello,

Yes. Just updated to the latest version and the problem remains. The file get's copied again
Note that this is being copied form one gdrive to another gdrive (not the same).

2018/11/20 15:34:20 NOTICE: SHARE02/Series/Series/1x01.avi: Not copying as --dry-run
2018/11/20 15:34:20 NOTICE: SHARE02/Series/Series/1x02.avi: Not copying as --dry-run

**Comment by animosity22** [comment]
What's the actual full command you are running?

What is the lsl output of the file on the remote?

```
felix@gemini:~$ rclone lsl gcrypt:hosts
      345 2018-09-02 16:00:55.707000000 hosts
```

**Comment by NunoHiggs** [comment]
rclone copy  -vv --ignore-checksum --ignore-existing --ignore-size --transfers 10 --dry-run API1SHARE1: GSTORE014:MEDIA

rclone lsl  "API1SHARE1:/SHARE02/Series/Series/1x01.avi"

136225764 2018-10-15 14:57:40.682000000 1x01.avi
136225764 2018-09-27 14:57:56.376000000 1x01.avi

**Comment by animosity22** [comment]
Are you using a regular Google Drive account? Looks like you have 2 copies which seems odd. You can dedupe it or is there some versioning that's on ?

**Comment by NunoHiggs** [comment]
Yes i am. I am going to dedup it. I'll get back to you as soon as it finishes

**Comment by animosity22** [comment]
This looks to be a dupe issue. If you have any new questions, please just ask in the forums and we'll help out.
