### ISSUE TITLE
option checksum with values or file list stored into file

### ISSUE THREAD

**Issue by hajes** [rclone/rclone#2752]
#### What is your current rclone version (output from `rclone version`)?

rclone v1.44

#### What problem are you are trying to solve?

Copy of DropBox to local server - over 100k files. I experienced several crashes and had to start all over again.

#### How do you think rclone should be changed to solve that?

I did not find any option in manual or I am blind. It would be easier to restart rclone if all checked files and ready for download/upload would be stored in external file. rclone would read file list from file and won't start checking all over again.

**Comment by hajes** [comment]
nothing wrong with rclone...it was typical problem between keyboard and chair.

the cache backend - by metadata you mean checksums of files for example?

**Comment by ncw** [comment]
> nothing wrong with rclone...it was typical problem between keyboard and chair.

I've had plenty of those in my time too :-)



> the cache backend - by metadata you mean checksums of files for example?

Name, size, checksum, modification time - that is all metadata.  Just not the actual data (though cache can store that too if you want).

**Comment by animosity22** [comment]
This looks to be solved. If you have any new questions, please just ask on the forums and we are happy to help out.
