### ISSUE TITLE
Do not start syncing if destination doesn't exist

### ISSUE THREAD

**Issue by mrx23dot** [rclone/rclone#2770]
#### What is the problem you are having with rclone?
rclone sync "D:\DRIVE" "H:"
shouldn't start scanning files on D: when H: is not mounted.

#### What is your rclone version (output from `rclone version`)
rclone v1.44
- os/arch: windows/386
- go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 7, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
external USB HDD

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync "D:\DRIVE" "H:"

**Comment by ncw** [comment]
> rclone sync "D:\DRIVE" "H:"
> shouldn't start scanning files on D: when H: is not mounted.

What did rclone do?  Can you show logs please.

**Comment by animosity22** [comment]
This looks stale. If you have a new question, please ask on the forums and we are happy to help.
