### ISSUE TITLE
Emby can't see the mounted drive on windows

### ISSUE THREAD

**Issue by Mike5123** [rclone/rclone#2796]
#### What is the problem you are having with rclone?
Emby can't physically see the mounted gdrive, and manually typing in the location doesn't work.

Windows Explorer can open it fine, though.

#### What is your rclone version (output from `rclone version`)
v1.45

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows Server 2016, 64bit.

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount --allow-other --dir-cache-time 72h --cache-chunk-path D:\cache\ --cache-chunk-no-memory --cache-chunk-size 10M --cache-info-age 72h --cache-db-purge --cache-workers 6 --buffer-size 0M --rc --log-level INFO crypt:/emby/ F:

**Comment by ncw** [comment]
Hmmm. not sure what is happening here - I know nothing about Emby.  It might be worth asking on [the rclone forum](https://forum.rclone.org/) if you haven't already.

If you can see the drive in Windows explorer then it sounds like rclone is working.

**Comment by jad3675** [comment]
Make sure that rclone (if you have it installed as a service) is running as the same user that emby is or if you are using an open cmd windows, that it is not an elevated command prompt.

John

**Comment by abarber229** [comment]
Hey Mike5123. I had a similar issue. However, I could get Emby to see the rclone mount and scan the files. I couldn't get anything to play though. Looked to possibly be a permissions issue when the ffprobe or ffmpeg was trying to run. At least that was what I was gather from some of the other forums. Were you able to get yours up and running? If so, what did you do?

**Comment by animosity22** [comment]
This looks to be a stale issue. If you need any help, please feel free to use the forums and we can help out.
