### ISSUE TITLE
Open file failed with google API V2

### ISSUE THREAD

**Issue by yinkiu602** [rclone/rclone#2804]
#### What is the problem you are having with rclone?
When opening large files(2TB) from google drive using --drive-v2-download-min-size 0, the console will show error 403, then the files cannot be opened

#### What is your rclone version (output from `rclone version`)
rclone windows v.145 amd64

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, 64bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount own: A: --drive-v2-download-min-size 0 --fast-list -v -vv --dir-cache-time 300h

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2018/11/30 19:01:12 DEBUG : /9028041461940074152_203432960_57216: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/11/30 19:01:12 DEBUG : /9028041461940074152_203432960_57216: >Getattr: errc=0
2018/11/30 19:01:12 DEBUG : /9028041461940074152_203432960_57216: Getattr: fh=0xFFFFFFFFFFFFFFFF
2018/11/30 19:01:12 DEBUG : /9028041461940074152_203432960_57216: >Getattr: errc=0
2018/11/30 19:01:12 DEBUG : /9028041461940074152_203432960_57216: Open: flags=0x0
2018/11/30 19:01:12 DEBUG : /9028041461940074152_203432960_57216: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2018/11/30 19:01:12 DEBUG : 9028041461940074152_203432960_57216: Open: flags=O_RDONLY
2018/11/30 19:01:12 DEBUG : 9028041461940074152_203432960_57216: >Open: fd=9028041461940074152_203432960_57216 (r), err=<nil>
2018/11/30 19:01:12 DEBUG : /9028041461940074152_203432960_57216: >OpenFile: fd=9028041461940074152_203432960_57216 (r), err=<nil>
2018/11/30 19:01:12 DEBUG : /9028041461940074152_203432960_57216: >Open: errc=0, fh=0x1
2018/11/30 19:01:12 DEBUG : /9028041461940074152_203432960_57216: Getattr: fh=0x1
2018/11/30 19:01:12 DEBUG : /9028041461940074152_203432960_57216: >Getattr: errc=0
2018/11/30 19:01:12 DEBUG : /9028041461940074152_203432960_57216: Read: ofst=0, fh=0x1
2018/11/30 19:01:12 DEBUG : 9028041461940074152_203432960_57216: ChunkedReader.openRange at 0 length 134217728
2018/11/30 19:01:12 DEBUG : 9028041461940074152_203432960_57216: Using v2 download: https://doc-04-c8-docs.googleusercontent.com/docs/securesc/slp5bjjakgtttp3rq5kbd7oi08pv6rrn/12l2esmup8c5mnv3iu2csh88udaapi3m/1543572000000/04752109642334219401/15649035413175064990/1RdmMR-A3OLjg-OB1SVs6VfrNujhe4KRi?h=11980726908349233354&e=download&gd=true
2018/11/30 19:01:13 ERROR : IO error: open file failed: googleapi: got HTTP response code 403 with body:
2018/11/30 19:01:13 DEBUG : /9028041461940074152_203432960_57216: >Read: n=-5
2018/11/30 19:01:13 DEBUG : /9028041461940074152_203432960_57216: Read: ofst=1717395456, fh=0x1
2018/11/30 19:01:13 DEBUG : 9028041461940074152_203432960_57216: ChunkedReader.openRange at 0 length 134217728
2018/11/30 19:01:13 ERROR : IO error: open file failed: googleapi: got HTTP response code 403 with body:
2018/11/30 19:01:13 DEBUG : /9028041461940074152_203432960_57216: >Read: n=-5
2018/11/30 19:01:13 DEBUG : /9028041461940074152_203432960_57216: Flush: fh=0x1
2018/11/30 19:01:13 DEBUG : /9028041461940074152_203432960_57216: >Flush: errc=0
2018/11/30 19:01:13 DEBUG : /9028041461940074152_203432960_57216: Release: fh=0x1
2018/11/30 19:01:13 DEBUG : /9028041461940074152_203432960_57216: >Release: errc=0

**Comment by ncw** [comment]
403 looks like you've hit some sort of rate limit.

Maybe the v2 and v3 endpoints are rate limited independently?

What happens if you want a bit and retry?

**Comment by yinkiu602** [comment]
Well, the program that i use will wait in v3, but it will show open error in v2, and then stop opening it.

**Comment by ncw** [comment]
> Well, the program that i use will wait in v3, but it will show open error in v2, and then stop opening it.

How about now - is it working?

**Comment by yinkiu602** [comment]
Nope, it is still working only in v3
For working, i mean:
1. Will wait when rate limited
2. Program will not failed to open parts of it first

**Comment by ncw** [comment]
Hmmm... Can you try this to see if you can copy the file?

    rclone copy own:path/to/2TBfile.bin file.bin --drive-v2-download-min-size 0 --fast-list -vv

If that works then try playing with the --vfs-read-chunk-size

**Comment by yinkiu602** [comment]
rclone copy josh:plots/19659776 file.bin --drive-v2-download-min-size 0 --fast-list -vv
2018/12/08 08:15:00 DEBUG : rclone: Version "v1.44" starting with parameters ["rclone" "copy" "josh:plots/19659776" "file.bin" "--drive-v2-download-min-size" "0" "--fast-list" "-vv"]
2018/12/08 08:15:00 DEBUG : Using config file from "C:\\Users\\a\\.config\\rclone\\rclone.conf"
2018/12/08 08:15:03 DEBUG : pacer: Rate limited, sleeping for 1.439444685s (1 consecutive low level retries)
2018/12/08 08:15:03 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/12/08 08:15:03 DEBUG : pacer: Rate limited, sleeping for 2.52583819s (2 consecutive low level retries)
2018/12/08 08:15:03 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/12/08 08:15:04 DEBUG : pacer: Rate limited, sleeping for 4.543200025s (3 consecutive low level retries)
2018/12/08 08:15:04 DEBUG : pacer: low level retry 3/10 (error googleapi: Error 403: Rate Limit Exceeded, rateLimitExceeded)
2018/12/08 08:15:07 DEBUG : pacer: Resetting sleep to minimum 10ms on success
2018/12/08 08:15:12 DEBUG : 19659776: Couldn't find file - need to transfer
2018/12/08 08:15:12 DEBUG : 19659776: Using v2 download: https://doc-0s-88-docs.googleusercontent.com/docs/securesc/slp5bjjakgtttp3rq5kbd7oi08pv6rrn/3h6i81iq9ef3cir5aohhfrt4objb90dh/1544227200000/15649035413175064990/15649035413175064990/1iCswPM2Y-xqGcqsMcqHcYug9YpDHCFux?h=11980726908349233354&e=download&gd=true
2018/12/08 08:15:13 ERROR : 9028041461940074152_223549831_19659776: Failed to copy: failed to open source object: open file failed: googleapi: got HTTP response code 403 with body:
2018/12/08 08:15:13 ERROR : Attempt 1/3 failed with 1 errors and: failed to open source object: open file failed: googleapi: got HTTP response code 403 with body:
2018/12/08 08:15:13 DEBUG : 19659776: Couldn't find file - need to transfer
2018/12/08 08:15:14 DEBUG : 19659776: Using v2 download: https://doc-0s-88-docs.googleusercontent.com/docs/securesc/slp5bjjakgtttp3rq5kbd7oi08pv6rrn/3h6i81iq9ef3cir5aohhfrt4objb90dh/1544227200000/15649035413175064990/15649035413175064990/1iCswPM2Y-xqGcqsMcqHcYug9YpDHCFux?h=11980726908349233354&e=download&gd=true
2018/12/08 08:15:14 ERROR : 19659776: Failed to copy: failed to open source object: open file failed: googleapi: got HTTP response code 403 with body:
2018/12/08 08:15:14 ERROR : Attempt 2/3 failed with 1 errors and: failed to open source object: open file failed: googleapi: got HTTP response code 403 with body:
2018/12/08 08:15:14 DEBUG : 19659776: Couldn't find file - need to transfer
2018/12/08 08:15:15 DEBUG : 19659776: Using v2 download: https://doc-0s-88-docs.googleusercontent.com/docs/securesc/slp5bjjakgtttp3rq5kbd7oi08pv6rrn/3h6i81iq9ef3cir5aohhfrt4objb90dh/1544227200000/15649035413175064990/15649035413175064990/1iCswPM2Y-xqGcqsMcqHcYug9YpDHCFux?h=11980726908349233354&e=download&gd=true
2018/12/08 08:15:15 ERROR : 19659776: Failed to copy: failed to open source object: open file failed: googleapi: got HTTP response code 403 with body:
2018/12/08 08:15:15 ERROR : Attempt 3/3 failed with 1 errors and: failed to open source object: open file failed: googleapi: got HTTP response code 403 with body:
2018/12/08 08:15:15 Failed to copy: failed to open source object: open file failed: googleapi: got HTTP response code 403 with body:

**Comment by yinkiu602** [comment]
Still, it works in v2 only when it never get rate limited for once. But after 1 rate limit, it will failed to open the file?

**Comment by animosity22** [comment]
If this is still an item, please just ask on the forums and we can help out as this looks stale.
