### ISSUE TITLE
Automatic unmount after idle time

### ISSUE THREAD

**Issue by tobiisdesired** [rclone/rclone#2805]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.43.1
- os/arch: linux/amd64
- go version: go1.11

#### What problem are you are trying to solve?

An encrypted mount should automatically be unmounted after some time without access to it. So your data stays secure even if you forget to unmount it.

#### How do you think rclone should be changed to solve that?

`rclone mount` could provide an idle timeout parameter. Other tools like `encfs` have this feature.
Here is an excerpt from the `encfs` manual pages:

>   -i, --idle=MINUTES
>            Enable automatic unmount of the filesystem after a period of inactivity.  The period is specified in minutes, so the shortest timeout period that can be requested is one minute.  EncFS
>            will not automatically unmount if there are files open within the filesystem, even if they are open in read-only mode.  However simply having files open does not count as activity.

**Comment by ncw** [comment]
This is an interesting idea.

The FS can't umount if it has files open - that would break stuff alas.

You could check out autofs which unmounts file systems when not in use.  I use it for NFS mounts.  I haven't tried it with rclone mount but it should work...

**Comment by ncw** [comment]
I think running rclone on automount is the best solution here - it lets the OS do the tricky job of working out whether we have any open files.

Since we have patches in the pipeline to make that really smooth I'm going to close this one.
