### ISSUE TITLE
Certificate signed by unknown authority, Error adding google drive on FreeNAS (BSD) Jail

### ISSUE THREAD

**Issue by KenwoodFox** [rclone/rclone#2813]
Hello world, I'm getting this error when I try and add my google drive to my FreeNAS Jail with rclone installed.
```
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine or Y didn't work
y) Yes
n) No
y/n> n
If your browser doesn't open automatically go to the following link: https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=[REDACTED]
Log in and authorize rclone for access
Enter verification code> [REDACTED]
2018/12/03 17:21:39 Failed to configure token: failed to get token: Post https://accounts.google.com/o/oauth2/token: x509: certificate signed by unknown authority
```

**Comment by ncw** [comment]
If you can get the SSL roots in the correct place in the jail, or maybe set the environment variables in the link above then it will work, I'm sure.

**Comment by jacobblock** [comment]
This worked for me on freebsd 11.2 jail, managed with FreeNAS 11.2 + iocage.

```pkg install ca_root_nss```

**Comment by ncw** [comment]
Thanks for providing a solution @jacobblock 

Fancy sending a PR to add this to the FAQ section about SSL stuff? https://github.com/ncw/rclone/blob/master/docs/content/faq.md#rclone-gives-x509-failed-to-load-system-roots-and-no-roots-provided-error

**Comment by stellarpower** [comment]
There is also the `--no-check-certificate` switch for e.g. self-signed hosts.
