### ISSUE TITLE
pCloud - Samba-shared mount - NUL (0x00) added to every file

### ISSUE THREAD

**Issue by ale-rinaldi** [rclone/rclone#2814]
Hello,
I use rClone to mount a pCloud drive on my Linux server. Unlike the official client, rClone allows me to add the allow_others mount option so that Samba is fine with sharing the volume. The strange problem I'm experiencing is that, when I copy a file from a (Windows) client to the rClone mount via Samba, a NUL (0x00) byte is added to the beginning of the file, making it corrupted (even if easily fixable). This does not happen if I copy a file directly to the rClone mount in the Linux server, neither if I copy the file to a share referring to a local filesystem. From the Samba mailing list they say it's not their bug... Is some of you experiencing this? Where may I start investigating?

Thanks

**Comment by ale-rinaldi** [comment]
(pClone = pCloud, sorry for typo)

**Comment by ncw** [comment]
Very strange!

The first thing to do would be to make a log with `-vv` from the mount when copying a small file and post it here.

Another thing you could try is changing the `rclone mount` to mount a local directory (so instead of `rclone mount pcloud: /mnt/pcloud` you write `rclone mount /tmp /mnt/pcloud`) and see whether that has the problem too.

**Comment by ale-rinaldi** [comment]
Hello,
thanks for suggestion. Actually it seems like it has to do with caching: setting vfs-cache-mode to "writes", this doesn't happen. Maybe Samba doesn't perform a sequential write...

**Comment by ncw** [comment]
> Actually it seems like it has to do with caching: setting vfs-cache-mode to "writes", this doesn't happen. Maybe Samba doesn't perform a sequential write...

Interesting....

Rclone shouldn't be corrupting the data though it should be returning an error.

Can you do that log with `-vv` for me?
> The first thing to do would be to make a log with -vv from the mount when copying a small file and post it here.

Also the result of this would be useful too just to rule out something funny in the pcloud backend


> Another thing you could try is changing the `rclone mount` to mount a local directory (so instead of `rclone mount pcloud: /mnt/pcloud` you write `rclone mount /tmp /mnt/pcloud`) and see whether that has the problem too.

Thanks

**Comment by ale-rinaldi** [comment]
Hello,
sorry, didn't forget about that, but I've been out of home these day. In the next evenings I'm gonna try that and post all you need. Do I need also the `--debug-fuse` flag to produce the logs?
Thanks

**Comment by ncw** [comment]
> Hello,
> sorry, didn't forget about that, but I've been out of home these day. In the next evenings I'm gonna try that and post all you need. Do I need also the `--debug-fuse` flag to produce the logs?
> Thanks

No worries!  If you put `--debug-fuse` on that would be helpful, but if it comes without I expect that will be fine too :-)

**Comment by ale-rinaldi** [comment]
Hello,
again, I'm really sorry for this delay.
Here are the log:

- https://lk.alerinaldi.it/no-cache.txt
This is the output of the command:
```
rclone mount -vv --debug-fuse --allow-other --umask 0007 pcloud:/ /media/alerinaldi/pcloud > no-cache.txt 2>&1
```

- https://lk.alerinaldi.it/cache.txt
```
rclone mount -vv --debug-fuse --allow-other --umask 0007 --vfs-cache-mode writes --cache-dir /home/alerinaldi/pcloud-cache pcloud:/ /media/alerinaldi/pcloud > cache.txt 2>&1
```

In both cases, after starting the mount, I copied a file named "test.txt" with "A test content" in it from my PC to the Samba share which exposes /media/alerinaldi/pcloud, and then opened the just copied file from the share.

In the first case, the NUL character was added to the beginning of the file. In the second case, it didn't.

Thanks!

**Comment by ncw** [comment]
This is the problem in the `no-cache` log

> 2019/11/19 18:31:34 ERROR : test.txt: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes

Normally this error **should** propagate to the application but it seems it went missing for you somewhere in the chain of `rclone => fuse => samba => windows samba client => windows app`.  This **is** a bug, but in what I'm not sure... rclone definitely presented the error to fuse so it could be in `samba` or the `windows samba client` or the `windows app` not checking their error returns properly.

So you can fix the no-cache by adding `--vfs-cache-mode writes` (but you discovered that already).

**Comment by animosity22** [comment]
This looks to be answered and not a rclone item. Closing out. If you have any further question, you can always ask on the forums.
