### ISSUE TITLE
Openload support

### ISSUE THREAD

**Issue by ealgase** [rclone/rclone#2820]
It would be pretty useful to support Openload ([openload.co](https://openload.co)) as a remote.  Openload offers free, unlimited filestorage, and easy sharing with others.  Their API documentation is located at [openload.co/api](https://openload.co/api).

**Comment by ncw** [comment]
The API looks straight forward.  Anyone want to work on it?

**Comment by darknemesis69** [comment]
Any news?

**Comment by LittleHans8** [comment]
OpenLoad is supported FTP to upload files, you can find FTP username and password in [here](https://openload.co/account#usersettings).

I try to config OpenLoad FTP Server as a remote(type is FTP)，
and mount it in my VPS :
 `rclone mount --allow-other --allow-non-empty --vfs-cache-mode writes OpenLoad: /mnt/OpenLoad &`
when I copy a video file:
`rclone copy -P /root/small.mp4 /mnt/OpenLoad/`
 it always tips Transferring(the file upload again and again)：
```
root@mydomain:~# rclone copy -P /root/small.mp4 /mnt/OpenLoad/
Transferred:   	  978.466M / 978.466 MBytes, 100%, 1.427 MBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:    11m25.5s
Transferring:
2019-06-24 09:31:20 ERROR : small.mp4: Failed to copy: close /mnt/OpenLoad/small.mp4: input/output error
2019-06-24 09:31:20 ERROR : Attempt 1/3 failed with 2 errors and: close /mnt/OpenLoad/small.mp4: input/output error
Transferred:   	  978.466M / 978.466 MBytes, 100%, 1.427 MBytes/s, ETA 0s
Transferred:   	    1.911G / 1.911 GBytes, 100%, 2.400 MBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:    13m35.5s
Transferring:
 *                                     small.mp4:100% /978.466M, 48.068k/s, 0s^C^C
```
---------------------------------------------------------------------
Today I found setting in [here]( https://openload.co/account#conversionsettings), you can close this action('Auto-Convert Videos into streamable videos' and 'Generate a splash image for uploaded movies'), those action will be do after the video file uploaded successfully , seems occupy files ! 
After close those action, rclone return to normal.
By the way, I want to know what did rclone do after the upload was successful?

**Comment by ncw** [comment]
> By the way, I want to know what did rclone do after the upload was successful?

rclone will check the file is really there and the correct size, so if another process is altering it then that would explain the error.
