### ISSUE TITLE
[Feature request] Support Firefox Send

### ISSUE THREAD

**Issue by joeky888** [rclone/rclone#2821]
https://send.firefox.com

Firefox Send is a file sharing website,

It would be great if rclone supports it.

**Comment by ncw** [comment]
How would you see that working with rclone?

**Comment by joeky888** [comment]
Directly download/upload files to/from local file system,

also clone a file from/to Gdrive.

**Comment by bandicootdancing** [comment]
Looking for something like this as well for use cases where I only want to share a file temporarily. I'd love to quickly share something directly from one of my remotes without having to use rclone serve or download the file locally then upload to Firefox Send/Transfer.sh.

**Comment by joeky888** [comment]
[ffsend](https://github.com/timvisee/ffsend) can upload and download files from Firefox Send.

**Comment by hackervera** [comment]
ffsend has 1 gig upload limit though
