### ISSUE TITLE
Failed to mount FUSE fs : FreeBSD

### ISSUE THREAD

**Issue by doubleddav** [rclone/rclone#2828]
See rclone forum for more details: https://forum.rclone.org/t/failed-to-mount-fuse-fs-freebsd/7723

#### What is the problem you are having with rclone?
Can't mount remote cloud storage as a non root user

#### What is your rclone version (output from `rclone version`)
rclone v1.45
- os/arch: freebsd/amd64
- go version: go1.11.2

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
FreeBSD 11
FreeBSD 12

####  Which cloud storage system are you using? (eg Google Drive)
OD4B

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount --allow-other --dir-cache-time 5s --vfs-cache-mode full onedrive: /tank/onedrive

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
mount helper error: mount_fusefs: /dev/fuse on /tank/onedrive: Operation not permitted
Fatal error: failed to mount FUSE fs: mount_fusefs: exit status 71

**Comment by ncw** [comment]
Thanks for reporting that.  I'll keep an eye on the upstream bug report.

**Comment by ivandeex** [comment]
@doubleddav Does the problem reproduce with rclone 1.54?

**Comment by ivandeex** [comment]
Closing stale requests due to no reply.
