### ISSUE TITLE
duplicate file

### ISSUE THREAD

**Issue by Akira657** [rclone/rclone#2833]
#### What is the problem you are having with rclone?
 I have two file with the same file path on google drive, so must to rename one of them to sync to local.
I know there is a command 'rclone dedupe', but what I need is renaming to the format I need, and decide which file should be renamed. In this case, I try to rename using 'moveto', but command 'moveto' is path base, it doesn't know which duplicate file should be renamed. 

#### What is your rclone version (output from `rclone version`)
1.45

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
linux 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

**Comment by calisro** [comment]
you could use --backup-dir to have it move the file being replaced elsewhere but not quite sure if this will fit your use case.

**Comment by ncw** [comment]
The solution to this is to use `rclone moveto` to rename one of the files.  You can look then to see which one got the new name, and then use `rclone moveto` again to rename them to the correct names.

So

````
rclone moveto drive:dir/duplicated-file drive:dir/temp-file-name
rclone lsl --max-depth 1 drive:dir
# work out which file is which
rclone moveto drive:dir/temp-file-name drive:dir/new-name-1
rclone moveto drive:dir/duplicated-file drive:dir/new-name-2
```

**Comment by ArthurGing** [comment]
Thanks for your reply.
It solve my problem.
I have another question about account, if the account has been revoked, why the exit code is 1 not 7?

**Comment by ncw** [comment]
> I have another question about account, if the account has been revoked, why the exit code is 1 not 7?

What was the error message?  Can you post it please?  And what happened to your account?

**Comment by ArthurGing** [comment]
I revoke the google drive account and try to do any operation. I think it will return exit code 7 but it return 1.
ERROR : : error listing: couldn't list directory: googleapi: Error 401: Invalid Credentials, authError
Failed to lsl: couldn't list directory: googleapi: Error 401: Invalid Credentials, authError
