### ISSUE TITLE
Support poll-interval on union remotes

### ISSUE THREAD

**Issue by bd2814** [rclone/rclone#2837]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.45
- os/arch: windows/amd64
- go version: go1.11

#### What problem are you are trying to solve?

Uploads that occur outside of a union mount are not available until after dir-cache-time expires. The union mount does not support poll-interval, reference: https://forum.rclone.org/t/rclone-union-poll-interval/7895/4

#### How do you think rclone should be changed to solve that?

Add support for poll-interval to the union remotes

**Comment by bd2814** [comment]
Yep that fixes it.

**Comment by DigitalJosee** [comment]
This fix is on the latest beta? I've downloaded it but apparently not.

**Comment by DigitalJosee** [comment]
Yes, now it's fine, didn't know why it didn't worked when I built by myself.
