### ISSUE TITLE
Multithread with rclone mount?

### ISSUE THREAD

**Issue by DangerD256** [rclone/rclone#2838]
I'm using latest rclone to work with dropbox
The problem is that when one process runs copying of big file another process can't read directories/files.
I there any way to increase threads so it can do multiple uploads/downloads at same time?

**Comment by ncw** [comment]
`rclone mount` is already multithreaded.

Can you describe what you are doing in greater detail please and write the flags you are using for rclone mount - thanks.

**Comment by DangerD256** [comment]
--dir-cache-time 1m --vfs-read-chunk-size 200M

The problem is that i have slow upload, can i somehow to limit simultaneous file uploads to leave some threads for file reading? That might solve issue. Also file uploads are too slow, download speed fixed with --vfs-read-chunk-size

**Comment by ncw** [comment]
> --dir-cache-time 1m --vfs-read-chunk-size 200M

Are you using `--vfs-cache-mode`?

How are you copying files to the mount?

How are you listing files on the mount?

**Comment by DangerD256** [comment]
soft works well with --vfs-cache-mode off
`cp /home/mediat/public_html/upload/propertys/48138/652656.jpg /home/mediat/public_html/upload/propertys/48138/652657.jpg /home/mediat/public_html/upload/propertys/48138/652658.jpg /home/mediat/public_html/upload/propertys/48138/652659.jpg /home/mediat/public_html/upload/propertys/48138/652660.jpg /home/mediat/public_html/upload/propertys/48138/652661.jpg /home/mediat/public_html/upload/propertys/48138/652662.jpg /home/mediat/public_html/upload/propertys/48138/652663.jpg /home/mediat/public_html/upload/propertys/48138/652664.jpg /home/mediat/public_html/upload/propertys/48138/652665.jpg /home/mediat/public_html/upload/propertys/48138/652666.jpg /home/mediat/public_html/upload/propertys/48138/652667.jpg /home/mediat/public_html/upload/propertys/48138/652668.jpg /home/mediat/public_html/upload/propertys/48138/652669.jpg /home/mediat/public_html/upload/propertys/48138/652670.jpg /home/mediat/public_html/upload/propertys/48138/652671.jpg /home/mediat/public_html/upload/propertys/48138/652672.jpg /home/mediat/public_html/upload/propertys/48138/652673.jpg /home/mediat/public_html/upload/propertys/48138/652674.jpg /home/mediat/public_html/upload/propertys/48138/652675.jpg /home/mediat/public_html/upload/propertys/48138/652676.jpg /home/mediat/public_html/upload/propertys/48138/652677.jpg /home/mediat/public_html/upload/propertys/48138/652678.jpg /home/mediat/public_html/upload/propertys/48138/652679.jpg /home/mediat/public_html/upload/propertys/48138/652680.jpg /home/mediat/public_html/upload/propertys/48138/652681.jpg /home/mediat/public_html/upload/propertys/48138/652682.jpg /home/mediat/public_html/upload/propertys/48138/652683.jpg "/home/mediat/Dropbox/Media/Ready/22 Grantbrook Court Brampton, Ritchie Khroud/web/";`
Reading files using php `glob($dropbox.'/Media/*')`
Now it works like that

**Comment by animosity22** [comment]
It's better to use a rclone copy command as you can control the --transfers and such directly.

**Comment by JRWR** [comment]
I'm seeing the same, when the write cache is uploading a large file (50GB) it will IO Block all other processes trying to write to separate files. due to our current workload, we have to use a vfs mount (Rsync server for inbound data)
```
/usr/bin/rclone mount incoming: /mnt/rclone \
   --allow-other \
   --buffer-size 256M \
   --dir-cache-time 1h \
   --drive-chunk-size 64M \
   --umask 000 \
   --vfs-read-chunk-size 128M \
   --vfs-read-chunk-size-limit off \
   --vfs-cache-mode writes \
   --cache-dir /var/cache/vfs/$i \
   --vfs-cache-max-age 10m \
   --low-level-retries 100 \
   --checkers=300 --transfers=300 --drive-chunk-size=64M --fast-list -v --attr-timeout 1m
```

**Comment by animosity22** [comment]
@JRWR  That's a different issue. You can see it's tracked here -> https://github.com/ncw/rclone/issues/2811

**Comment by ncw** [comment]
> I'm seeing the same, when the write cache is uploading a large file (50GB) it will IO Block all other processes trying to write to separate files. due to our current workload, we have to use a vfs mount (Rsync server for inbound data)

What do you mean IO block?  That it uses all the IO? Disk or network? Or that rclone doesn't upload any more files?

**Comment by MikeLund** [comment]
I have the same issue with rclone 1.46 on Windows 10 with gdrive.

Mount command:
`rclone mount gcrypt: G: --allow-other --bind 192.168.1.123 --dir-cache-time 72h --fast-list --cache-chunk-path=X:\rclone-cache --cache-db-path=X:\rclone-cache --log-level INFO --vfs-cache-mode writes --cache-tmp-upload-path=X:\rclone-upload --cache-dir=X:\rclone-cache -P --drive-chunk-size 32M --buffer-size 256M --vfs-read-chunk-size 128M --vfs-read-chunk-size-limit off --rc`
(I know some of those flags might be redundant when I'm just using normal crypt+drive vfs, but don't think they'd be the problem)

So I have the same issue as OP. I have my stuff download into a temporary folder from Sonarr, then be moved into the GDrive mount when it has finished downloading. Then Plex streams from the GDrive mount. When Sonarr is doing any uploads (particularly if there are many files uploading at once), almost always you won't be stream anything on Plex, nor even look inside the mount on Windows - it all gets locked up until the uploads finish.

Is there any real workaround (I would prefer to avoid hacking up something to use `rclone copy` with Sonarr) for this or something I could try? I have 1000/50 connection, so it can become quite bogged down when uploads happen -- but everything else works amazing. Thanks!

**Comment by animosity22** [comment]
@MikeLund - perhaps best to start a new issue as it's not the same as the OP was talking about. There was an issue already solved so best to make sure you are own the new version and open an issue if you are having a problem as your behavior should have been fixed in 1.46.

**Comment by MikeLund** [comment]
Hm, but OP's issue doesn't look like it was about the deadlock (which I also had, but was thankfully fixed in 1.46)?

**Comment by animosity22** [comment]
@MikeLund  - yes. if you are seeing a problem, I'd open up a new issue as it was fixed in  -> https://github.com/ncw/rclone/issues/2811

**Comment by animosity22** [comment]
This looks to be solved. If you still have a question, please ask on the forums and we are happy to help.
