### ISSUE TITLE
Support new openssh format

### ISSUE THREAD

**Issue by edmundlaugasson** [rclone/rclone#2843]
#### What is the problem you are having with rclone?
Cannot authenticate using password protected OpenSSH key file. I need to automate syncing and cannot enter all the time credentials. Using keyfile without password is obviously a security risk.
To be honest then SSH is the most wanted protocol due to its security, reliability.

Sounds like [similar issue with that](https://github.com/duplicati/duplicati/issues/3360). That's true - please try to generate key pair with different versions of OpenSSH and try to authenticate in both: with and without password on key file. Then you can see what works and what not.

Having keyfile-based authentication only at hosting provider - so using keyfile based authentication is mandatory for me.

Tried to search from here and also forum but did not find anything appropriate. Hopefully this SSH agent problem is solved.

Error message:
`failed to parse private key file: ssh: cannot decode encrypted private keys`

Used Ed25519 key pair.

Then tried RSA keys in PEM format:
`ssh-keygen -m PEM -t rsa -b 4096`

PEM format did not help - same error message.

Although I wanted to use already Ed25519 key format:
`ssh-keygen -t ed25519 -a 1000`

In case of RSA at least maximum strength (16384-bit).
`ssh-keygen -t rsa -b 16384`

#### What is your rclone version (output from `rclone version`)
mainly using v1.45

also tested with v1.45-034-gc1dd7678-beta

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

64-bit Linux Mint 19 (based on latest Ubuntu 18.04 LTS)

```
ssh -V
OpenSSH_7.6p1 Ubuntu-4ubuntu0.1, OpenSSL 1.0.2n  7 Dec 2017
```

... but as you see from [https://www.openssh.com](https://www.openssh.com) there is already v7.9 out...

When [to search Ubuntu packages](https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=ssh&searchon=names) then there is already OpenSSH 7.9 included into newest version of Ubuntu.

####  Which cloud storage system are you using? (eg Google Drive)

OpenSSH (SFTP)

_rclone config show cloud_
```
[cloud]
type = sftp
host = server.address
user = username
key_file = /home/user/.ssh/id_rsa-PEM
disable_hashcheck = true
```
I also removed later password from RSA key and tested again - same error message! 
That testing key pair was generated with:
`ssh-keygen -m PEM -t rsa -b 4096`
...command

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone ls cloud:`

... just wanted to list the remote content. If even authentication does not work then syncing is not possible.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
<timestamp> DEBUG : rclone: Version "v1.45" starting with parameters ["rclone" "ls" "cloud:" "-vv"]
<timestamp> DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
<timestamp> Failed to create file system for "cloud:": failed to parse private key file: ssh: cannot decode encrypted private keys
```

**Comment by ncw** [comment]
> Cannot authenticate using password protected OpenSSH key file.

rclone can't use ssh keys with passwords at the moment, though it looks like [the underlying library supports it now](https://godoc.org/golang.org/x/crypto/ssh#ParseRawPrivateKeyWithPassphrase).

The canonical solution to this is to use an ssh-agent, then you can add the key to the ssh agent for passwordless access.  Does that work for you?

Can you try with your key unencrypted?

What would use expect to happen if rclone tries to use an encrypted private key? Should it prompt for the password?  Or should the config process ask for the password which rclone will then store obscured in it's config file?

**Comment by edmundlaugasson** [comment]
> The canonical solution to this is to use an ssh-agent, then you can add the key to the ssh agent for passwordless access. Does that work for you?

Unfortunately it did not. Using seahorse usually but tried also classical ssh-add command - none of them helped.

> Can you try with your key unencrypted?

That worked. Even with Ed25519 key!

Discovered another issue: it works only when private key path is full path, e.g. /home/user/.ssh/key
If it is relative path, e.g. ~/.ssh/key then it does not work. Would expect that also relative path works.

> What would use expect to happen if rclone tries to use an encrypted private key? Should it prompt for the password? Or should the config process ask for the password which rclone will then store obscured in it's config file?

Prefer to use ssh agent but if it fails then storing encrypted (hopefully strongly encrypted) password should be work.
Expect that also seahorse can be used and also other ssh agents that are used in Linux - it should not depend on used ssh agent.

**Comment by B4dM4n** [comment]
I thought I responded to this issue prior creating the PR, but it must got lost when switching PC's.

> rclone can't use ssh keys with passwords at the moment, though it looks like [the underlying library supports it now](https://godoc.org/golang.org/x/crypto/ssh#ParseRawPrivateKeyWithPassphrase).

The `ssh` package only supports encrypted keys using the `x509.DecryptPEMBlock` function. Sadly the new OpenSSH keys use their own encryption and are not supported. The new `key_file_pass` option added by the PR only adds support for old OpenSSH encrypted keys to be decrypted.

The supported keys can be identified by their header:
```
-----BEGIN EC PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: DES-EDE3-CBC,B0583C312FBFA5E4

...
```
or
```
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: DES-EDE3-CBC,6E8387FFC9A150D2

...
```

I was not abe to create those keys with `ssh-keygen`, but `puttygen` is able to:
```
puttygen -t rsa -O private-openssh -o rsa.key
puttygen -t ecdsa -O private-openssh -o ecdsa.key
```


> Unfortunately it did not. Using [seahorse](https://en.wikipedia.org/wiki/Seahorse_(software)) usually but tried also classical ssh-add command - none of them helped.

It's strange that `seahorse` would not work. I tested `ssh-agent` and `gpg-agent` and was able to connect with both of them. Can you provide a log file when trying to connect with `seahorse`? Maybe there is an issue in the communication with the agent. 

The only issue I had was a `Too many authentication failures for *username*` error when using a agent with many keys. This problem can also be solved with the PR by combining the `key_use_agent` and `key_file` options.

> Prefer to use ssh agent but if it fails then storing encrypted (hopefully strongly encrypted) password should work. 

You should not rely on password encryption inside the rclone config. Currently all passwords are only `obscured` by encrypting them with a static key. If you want to keep the passwords (and access tokens) secure you need to use [config file encryption](https://rclone.org/docs/#configuration-encryption).

**Comment by animosity22** [comment]
This looks to be answered. If you have any further questions, you can ask on the forums.
