### ISSUE TITLE
Dropbox Feature; --dropbox-credentials

### ISSUE THREAD

**Issue by jake-stripe** [rclone/rclone#2849]
Hi Nick,

During the last month or so I've been getting great use out of the `--dropbox-impersonate` flag you helped me implement in issue #2577, I'm now hoping to implement another Dropbox backend flag.

#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.45
- os/arch: darwin/amd64
- go version: go1.11.2
```

#### What problem are you are trying to solve?
I am writing a small script that shells out to Rclone in order to help individuals migrate files from Dropbox to Google Drive. Everything works great thus far, however use of the script currently requires  the end user to store plaintext Dropbox credentials on there machines as part of the Dropbox Remote entry in the user's Rclone config file (`~/.conf/rclone/rclone.conf`).

#### How do you think rclone should be changed to solve that?
I'd like to add a `--dropbox-credentials` flag so that a user is able to supply an inline JSON blob in order to fully automate authentication to Dropbox. It would work just like Drive's `--drive-service-account-credentials` flag. 

Example:
`--dropbox-client-id "CLIENT_ID"`
`--dropbox-client-secret "CLIENT_SECRET"`
**`--dropbox-credentials '{"access_token": "SUPER_SECRET_OAUTH", "token_type":"bearer", "expiry":"0001-01-01T00:00:00Z"}'`**

#### Do you have the time/ability to work on this feature request yourself?
Yes I should have time to poke at this over the holiday, but I might need a bit more golang advice- my only golang exp thus far has been the implementation of issue #2577. Worst case scenario I can work on this Q1 2019.

Please let me know your thoughts. I'm excited to poke more at this codebase and get greater exposure to golang :)

Thanks again,

-Jake

**Comment by jake-stripe** [comment]
Hey Nick,

Thanks for your response. These credentials are indeed the latter; just the`token` field in the rclone config. As for the naming convention, I'm a bit stumped myself as to what would be best to call it; Perhaps `--dropbox-token` would be more intuitive? Please let me know your thoughts.

With regards to "Would storing the credentials in a file be easier for people?"; I personally think that (outside of corporate environments) storing the creds in the config file as-is is just fine. It also feels quite intuitive.

I've gone ahead and created a [WIP branch](https://github.com/ncw/rclone/pull/2852). The gist of the changes are as follows: 

1.  The addition of the `--dropbox-token `flag in `backend/dropbox/dropbox.go`:
```
if opt.Token != "" {
		config.SetValue(name, config.ConfigToken, opt.Token)
	}
```
2. And the addition of a `SetValue` method in `fs/config/config.go`(as opposed to use of `SetValueAndSave`), such that only the runtime config is modified, rather than runtime config + the `rclone.conf` file.
```
// SetValue sets the key to the value and saves just that
// value in the RUNTIME config. No changes are writen
// back to the users on-disk config file.
func SetValue(name, key, value string) (err error) {
	// Set the value in the runtime config only
	getConfigData().SetValue(name, key, value)
	return nil
}
```

Please let me know your thoughts on the implementation. Everything builds and works great on my end (I tested with an rclone lsjson). This change was much smaller than I initially anticipated, but I'm not sure if these changes (particularly the additional `SetValue`) method are the correct way to do it.

Thank you

-Jake

**Comment by tgallant** [comment]
Hello @ncw! I am interested in this feature (especially being able to pass in the oauth token json blob for all oauth backends as discussed in #2852). I can take a crack at implementing. Do you know if there has been any other discussion of this feature elsewhere in the backlog?

**Comment by ncw** [comment]
@tgallant I don't think anyone is working on this at the moment.

What were you thinking of? I think just adding a "token" config value (advanced setting) should probably be enough to enable it. So another value like these?

```go
{
                        Name: config.ConfigClientID,
                        Help: "Google Application Client Id\nSetting your own is recommended.\nSee https://rclone.org/drive/#making-your-own-client-id for how to create your own.\nIf you leave this blank, it will use an internal key which is low performance.",
                }, {
                        Name: config.ConfigClientSecret,
                        Help: "Google Application Client Secret\nSetting your own is recommended.",
                }
```

Potentially these 3 settings could be factored out of all the oauth using backends...

**Comment by tgallant** [comment]
@ncw I can confirm that just adding a `config.ConfigToken` option to the options list works as expected. `oauthutil` can handle everything from there. It should be quick work to sprinkle that option in where needed.

```
$ ./rclone --dropbox-token '{"access_token":"foo","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"}' lsl :dropbox:
   320669 2020-01-23 20:00:13.000000000 test1.txt
   357605 2020-01-23 20:00:25.000000000 test2.txt
   320669 2020-01-23 20:00:13.000000000 test3.txt
   357605 2020-01-23 20:00:25.000000000 test4.txt
```

In terms of factoring these options out do you have anything particular in mind? Would we want these options to still be exposed as `--$BACKEND-client-id`, etc.? We could add global flags like `--oauth-token`. That would work for my particular use case since I'm interested in generating configs on the fly with the `:backend:` syntax (syncing to/from the local fs). This might not provide as much flexibility to users who are performing actions between two oauth backends. Best of both worlds might be to maintain these backend specific options but add support for global flags like `--oauth-token`, `--oauth-client-id`, `--oauth-client-secret`. What are your thoughts?

**Comment by tgallant** [comment]
thinking about this some more... how about this as an option for factoring:

in `oauthutil.go` define a `SharedOptions` data structure

```go
var SharedOptions = []fs.Option{{
	Name: config.ConfigClientID,
	Help: "OAuth Client Id\nLeave blank normally.",
}, {
	Name: config.ConfigClientSecret,
	Help: "OAuth Client Secret\nLeave blank normally.",
}, {
	Name: config.ConfigToken,
	Help: "OAuth Access Token as a JSON blob",
}}
```

then in the relevant backends define the Options like this

```go
fs.Register(&fs.RegInfo{
...

Options: append([]fs.Option{{
	Name:     "impersonate",
	Help:     "Impersonate this user when using a business account.",
	Default:  "",
	Advanced: true,
}, {
	Name:     "blah",
	Help:     "blah",
}}, oauthutil.SharedOptions...)

...
```

**Comment by ncw** [comment]
> thinking about this some more... how about this as an option for factoring:

That looks great! `token` should be an advanced setting too.

To retain the current order in `rclone config` we'll need to put the oauth config options first

**Comment by tgallant** [comment]
Thanks @ncw. I have a PR ready for review here https://github.com/rclone/rclone/pull/4479
