### ISSUE TITLE
Improve listings of the "Directory listing" in serve http with more detail

### ISSUE THREAD

**Issue by calisro** [rclone/rclone#2855]
Currently the http listings look like this:

```
Directory listing of /
AudioBooks/
Pictures/
Software/
Videos/
apk/
eBooks/
```

I'd like to see the listings more verbose.  Perhaps a flag to increase the verbosity on the listings to look more like other http servers (nginx/apache):

Name  -  Last Modified  -  Size 

Along with sortable columns.  Should be fairly easy to implement in the html delivered to the client post rendering

Similar to this:
https://www.tecmint.com/wp-content/uploads/2017/01/Apache-Directory-Listing.png

If we want to get fancy, we could use a template to have the user create their own html for those pages pretty easily by just exposing those elements to the template {{name}} {{size}} {{last modified}} etc.

**Comment by ncw** [comment]
Funnily enough we are in the process of doing this - this PR is the first step #2844

@poundifdef is looking at this.

**Comment by calisro** [comment]
Closed in favor of that issue and PR.

**Comment by darwis059** [comment]
how to add custom html template?

**Comment by ncw** [comment]
> how to add custom html template?

That isn't possible at the moment, but it might be possible to add something... Do you want to have a go?

**Comment by c64bob** [comment]
I would love to be able to format the output as an Apache Directory Listing. This way, Kodi could parse the output. Any progress using a custom html template, or providing a more verbose one?

**Comment by ncw** [comment]
I'm hoping someone will step up with some code to implement external templates.  @c64bob fancy having a go?

**Comment by c64bob** [comment]
@ncw Sure, I can try, although I'm not that experienced with go. I would add another parameter for the serve command, like`rclone serve http --custom-template /path/to/template.html` What do you think?

**Comment by ncw** [comment]
> @ncw Sure, I can try, although I'm not that experienced with go. I would add another parameter for the serve command, like`rclone serve http --custom-template /path/to/template.html` What do you think?

Something like that sounds perfect!  It might want to be a directory though as you might want some other media in there, eg images.

**Comment by poundifdef** [comment]
I had initially attempted to do exactly this! However, I never had time to complete the PR (new to golang, was planning a wedding, and so on.) But maybe this is a nice starting point?

https://github.com/rclone/rclone/pull/2874

**Comment by ncw** [comment]
@poundifdef If you wanted to warm up that pull request, that would be great!

**Comment by calisro** [comment]
I created a way to specify a user customizable external template for webdav/http.  It is an input of a single file (not a directory) so markup can be customized.  I've also created a much richer template but hesitated to upload it as the default.  or backward compatibility the basic template might be better?  But I figured this one could be uploaded to the wiki or elsewhere.  

It should be mentioned that I borrowed some code snippets from caddy (Apache 2.0 license) and I'm not sure what I need to do, if anything, for the snippets I used.  The 'rich' template I created is also based on the caddy one but heavily modified to work in rclone (and work with scrapers like kodi/emby)

Can you let me know your thoughts on the above?

**Comment by calisro** [comment]
That PR allows us to specify a template now and has additional exported markup variables as well.  Do you want to incorporate a richer template as the default?  If so, i'm not 100% sure what needs to be done.  I can see that rcserver uses the default template so I see a few things needs to happen if we replace the default.

The size and modtime would need to be added to the call directory.AddEntry(entry.Remote(), isDir) in rcserver.go since the rich template has these columns now.  That isn't so straightforward to me though.  Alternatively, the markup could be written to simply hide those columns but that seems counterproductive.  

If you can give me some direction on how I get the size/modtime into the rcserver.go function, then I think I can manage the remaining tasks of adding the parameter and modifying the tests.  

Anything else that needs to be looked at?

This is the template.  I modified it a bit more to make the sizes of files more human readable now.


[index.html.rclonecaddy.gz](https://github.com/rclone/rclone/files/4577075/index.html.rclonecaddy.gz)
