### ISSUE TITLE
Windows rclone mount regression bug v1.43.1->v1.45 - Deadlock?

### ISSUE THREAD

**Issue by iamjrock** [rclone/rclone#2857]
#### What is the problem you are having with rclone?
VFS Rclone mount freezes on file modify operations under Windows.

#### What is your rclone version (output from `rclone version`)
Occurs with all versions later than rclove v1.43.1.

Does not occur with v1.43.1.

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 2012 Server, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive -> Crypt

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

- Open a new text document in notepad and try to save it to the Mount.
- Notepad freezes at the Save screen and the mount drive is also inaccessible to both the command prompt and Windows Explorer.
- After restarting rclone, the mount/drive is accessible and the file shows in the mount folder it was saved/created in.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Full configs, -vv logs and -rc debug logs are available in this [thread](https://forum.rclone.org/t/windows-rclone-mount-regression-bug-v1-43-1-v1-45/7974).

**Comment by ncw** [comment]
Thanks for making an issue about this.

I think I've discovered the deadlock and fixed it.

I also wrote a deadlock hunter program which discovered this deadlock too.

Can you give this a test please?

https://beta.rclone.org/branch/v1.45-041-gd305dfeb-fix-2811-deadlock-beta/ (uploaded in 15-30 mins)

**Comment by iamjrock** [comment]
hmmm, thanks for this effort, sadly we're not there quite yet.

Logs below.  They show:

1. OK: Create new file in Notepad, add a single word of text and save it to the Mount
2. OK: Open the same file from the mount in Notepad
3. NOK: Adding some more text and attempt to save the file overwriting the existing file causes an "Access is denied".  Same result if just trying to save the same file witout have added the extra text.

After restarting rclone, the unedited file from step 2 is still available on the Mount for reading.

Unsurprisingly, if I use the command line to copy a file from the local drive to overwrite a file of the same name on the Mount, I also get the Access is Denied error.

The mount is running as the "Local System" aka "SYSTEM" user so I don't think this is permissions related.

Nothing in the Windows event log.

[logs.txt](https://github.com/ncw/rclone/files/2705744/logs.txt)

**Comment by ncw** [comment]
Actually that looks like the deadlock was fixed which was my first aim :-)

**Comment by ncw** [comment]
I'll take a look at the next part now...

**Comment by ncw** [comment]
I tried to see if I could replicate this on my Windows 7 VM - no luck :-(

Looking carefully through your logs I don't see rclone ever returning that permission denied error.   This makes me think that the OS decided that the access permissions were wrong rather than rclone...

Can you try running rclone as the user you are logging in as and see if you get the same problem?

**Comment by iamjrock** [comment]
OK, that worked!  So to recap the mix that worked:

* An Active Directory domain-joined Windows 2012 Server
* Logged in as a user with domain administrator privileges
* Latest rclone beta running as a nssm service under the same admin user
* Latest Winfsp beta running under the "Local System" aka SYSTEM account.

I can now browse/delete/edit files in the mount from all applications, whether they are running as the admin user or the System account.

**Comment by ncw** [comment]
Glad it is working! What do you think we should add to the docs to make that easier?

https://rclone.org/commands/rclone_mount/#installing-on-windows

**Comment by ncw** [comment]
I think this is working now so I'll close this issue
