### ISSUE TITLE
Update/upgrade option

### ISSUE THREAD

**Issue by jkaberg** [rclone/rclone#2867]
It would be cool if rclone had an update/upgrade option, eg `rclone upgrade` would pull in the latest stable release and replace the current rclone binary and do any necessary cleanups automagicly (seamless experience)

Perhaps also throw in an option for latest beta release? `rclone upgrade --beta`

An simple and nice thing to have :smile:

**Comment by ncw** [comment]
I agree that would be pretty cool!

It isn't trivial alas, mostly because there are a great number of different ways of installing rclone.

Note that `rclone version --check` will at least tell you if rclone needs updating!

**Comment by ivandeex** [comment]
There is a nice package https://github.com/jpillora/overseer for creating monitorable, gracefully restarting, self-upgrading binaries in Go:
* Works with systemd, upstart, supervisor, etc
* Graceful, zero-downtime restarts
* Easy self-upgrading binaries

**Comment by ivandeex** [comment]
Duplucate of https://github.com/rclone/rclone/issues/3269

**Comment by ivandeex** [comment]
> A bit of research comes up with (@ncw )
> 
>     * https://github.com/sanbornm/go-selfupdate
> 
>     * https://github.com/inconshreveable/go-update

**Comment by ivandeex** [comment]
This ticket duplicates #3269 so merging in.
