### ISSUE TITLE
How to use config flags at GoLang implementation

### ISSUE THREAD

**Issue by prometherion** [rclone/rclone#2868]
#### What is the problem you are having with rclone?

Lack of documentation regarding the use of some CLI flags using the GoLang source code.

#### What is your rclone version (output from `rclone version`)

I'm not using the CLI, it's a dependency of one of my project: anyway imported `v1.45` with dep (revision `d35bd15762f8f0f365fd3e1784e93add3bbdc61c`)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Running as a package in a Docker Container (Alpine 3.7)

####  Which cloud storage system are you using? (eg Google Drive)

Local FS backend

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```go
import (
        "path"

        "github.com/ncw/rclone/backend/local"
        "github.com/ncw/rclone/fs/config/configmap"
        "github.com/ncw/rclone/fs/sync"
)

func myFunc() {
        src, _ := local.NewFs("src", path.Join("path", "to", "src"), configmap.New())
	dst, _ := local.NewFs("dst", path.Join("path", "to", "dst"), configmap.New())
	_ := sync.MoveDir(dst, src, false)
}
```

How can I inject additional flags like `--no-check-updated` or `--ignore-errors`?

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Not available, just printed on _stderr_:
```
ERROR : path/to/file: Not deleting source as copy failed: can't copy - source file is being updated (mod time changed from 2018-12-27 08:52:12.986354553 +0000 UTC to 2018-12-27 08:52:12.993576811 +0000 UTC)
ERROR : Local file system at /mnt/data/path/to/file: not deleting directories as there were IO errors
```

**Comment by ncw** [comment]
> Lack of documentation regarding the use of some CLI flags using the GoLang source code.

Rclone is being restructured to be more useful as a library but it hasn't had many users yet so there may be rough edges!

> How can I inject additional flags like `--no-check-updated` or `--ignore-errors`?

Setting the global config `fs.Config.IgnoreErrors` - should do it I think. 

Note that `--no-check-updated` is a local backend config so you would pass that in the configmap

```go
m := configmap.New()
m.Set("no_check_updated", "true")
local.NewFs("src", path.Join("path", "to", "src"), m)
```

Note that making a configmap like that doesn't have the default values in, so you might at some point want to call `fs.ConfigMap` instead, and inject your config by overriding `fs.ConfigFileGet`.

**Comment by animosity22** [comment]
This looks answered so closing out.
