### ISSUE TITLE
Failed to configure token: parsing time 

### ISSUE THREAD

**Issue by zs910208565** [rclone/rclone#2872]
209/5000  
Debian mounts onedrive education and configures token display

2018/12/28 14:10:33 Failed to configure token: parsing time "" 20181228 t22:52:11. 3593771 + 08:00" "as" "the T15:2006-01-02 04:05 Z07:00" ": always parse" 1228 t22:52:11. 3593771 + 08:00 "" as" -"

**Comment by Cnly** [comment]
Hi @zs910208565, can you answer the following questions so we can better look at the problem? Thanks.

#### What is your rclone version (output from `rclone version`)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

Also, a more detailed log would be helpful, too.

**Comment by Cnly** [comment]
@zs910208565 The second question above will also be helpful. Could you also answer it?

And you mentioned that you're trying to mount OneDrive. Are you mounting with a OneDrive backend, or with a WebDAV backend?

**Comment by animosity22** [comment]
This looks stale. If you have a question, you can always ask on the forums.
