### ISSUE TITLE
File log or operation callback

### ISSUE THREAD

**Issue by kslr** [rclone/rclone#2873]
hi ncw

I want to record the upload log of each file.
in https://github.com/ncw/rclone/blob/master/fs/operations/operations.go#L357 Add notification(queue or callback), Is this a good idea? for ```rclone copy```

thank

other:
https://forum.rclone.org/t/is-there-an-option-to-call-callback-script-if-something-changed-at-destination-after-sync-no-callback-if-nothing-changed/4302/8
https://forum.rclone.org/t/rclone-invoke-user-script-command-after-each-file-copy-move-delete/5149/9

**Comment by kslr** [comment]
@ncw 
This method I used before, but need to collect logs and then parse. (syslog->filebeat->elasticsearch->python parse and write database)
I recently learned some golang, hope to integrate directly to reduce complexity and error rate.
(to->queue->parse)
rclone is an excellent software, I use it in a 20+ cluster.

**Comment by ncw** [comment]
Others have asked for a more parseable log format in the past, eg https://github.com/ncw/rclone/issues/2459 - is that interesting?  Would you like to help with that issue?

> rclone is an excellent software, I use it in a 20+ cluster.

:-)))

**Comment by kslr** [comment]
I can try to integrate Logrus, replace github.com/pkg/errors

1. Stdout 
2. Then add the ``` --logstash-address 127.0.0.1:8911``` to specify the send address (default off)
https://github.com/bshuster-repo/logrus-logstash-hook

**Comment by kslr** [comment]
Or standard JSON, no longer subject to a certain software.
```
--json-log
--json-log-level
```

**Comment by ncw** [comment]
logrus can do JSON output too I think

> With log.SetFormatter(&log.JSONFormatter{}), for easy parsing by logstash or Splunk:

**Comment by kslr** [comment]
You mean all logs are using JSON?

**Comment by ncw** [comment]
> You mean all logs are using JSON?

That is what I was thinking
 
> I mean using Logrus to process the log, then it is divided into two pieces.
> 
> 1. Normal log processing
> 2. JSON processing
> 
> So may need a command to specify

You could then have a tag for the file transfer logs.

Though maybe your idea is more useful having a --json-log and --json-log-level

**Comment by kslr** [comment]
It's going to be easier.
> You could then have a tag for the file transfer logs.

```
--log-file string
--log-format string(remove)
--log-level string
```
Do I need to rewrite these commands?

**Comment by kslr** [comment]
https://github.com/rclone/rclone/pull/3373
