### ISSUE TITLE
Inconsistent bucket name handling with B2

### ISSUE THREAD

**Issue by hyperknot** [rclone/rclone#2878]
#### What is the problem you are having with rclone?
The bucket name handling is inconsistent when using rclone config-less. In B2, I create a key which has access to one bucket only.

```
rclone lsd --b2-account x --b2-key y :b2:
> lists "mybucket"

rclone sync --b2-account x --b2-key y /src :b2:mybucket/src
> works perfectly

# try using a wrong bucket name
rclone sync --b2-account x --b2-key y /src :b2:wrongbucket/src
> synchronizes everythinig to "mybucket", even though it wasn't the one specified

# try using no bucket name at all
rclone sync --b2-account x --b2-key y /src :b2:
> deletes everything in the "mybucket", and makes the bucket root synched to /src

# try using no bucket name at all with a subdir
rclone sync --b2-account x --b2-key y /src :b2:/src
> still deletes everything in "mybucket", and makes the bucket root synched to /src
```

#### What is your rclone version (output from `rclone version`)
```
rclone v1.45
- os/arch: freebsd/amd64
- go version: go1.11.2
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
freebsd/amd64

####  Which cloud storage system are you using? (eg Google Drive)
Backblaze B2

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I can copy if required for reproduction.

Recommendation: I strongly recommend to fail, if the wrong bucket name was specified, or no bucket name was specified and it's not possible to create a bucket with the given auth key.

**Comment by ncw** [comment]
I think this is mostly fixed with [the latest beta](https://beta.rclone.org) - would you mind checking that it is?

Certainly the "wrong bucket name" case is fixed in 3de7ad5223a84e8621ddfb10363ad46b4df745b5 - I'm not sure about the no bucket name cases.

**Comment by ivandeex** [comment]
@hyperknot Does the problem reproduce with rclone 1.54?

**Comment by ivandeex** [comment]
Closing stale requests
