### ISSUE TITLE
Implement --no-config flag

### ISSUE THREAD

**Issue by hyperknot** [rclone/rclone#2879]
#### What is the problem you are having with rclone?
I believe there are two ways to use rclone: 
- interactively, using config, possibly with config password
- in pure cli mode, using `--b2-account` etc. long options

Right now, if there is a config password set, it breaks pure cli mode.

With no config:
```
rclone lsd --b2-account x --b2-key y :b2:
```
works

With config, the same command breaks with `Enter configuration password:` prompt. 

If I try a workaround and specify `--ask-password=false`, it still doesn't work, terminating in 
```
unable to decrypt configuration and not allowed to ask for password - set RCLONE_CONFIG_PASS to your configuration password
```

This means, that it is not possible to develop rclone cli scripts on a dev machine with config set. 
I always have to rename the config folder before and after testing such scripts.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.45
- os/arch: darwin/amd64
- go version: go1.11.2
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
macOS 10.14.2

####  Which cloud storage system are you using? (eg Google Drive)
Backblaze B2, but I believe it's not relevant.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Nothing except arg parsing.

**Comment by ncw** [comment]
> This means, that it is not possible to develop rclone cli scripts on a dev machine with config set.
> I always have to rename the config folder before and after testing such scripts.

You could try using `--config /dev/null` as a workaround?

**Comment by hyperknot** [comment]
Yes, that one works as a workaround.

**Comment by ncw** [comment]
To fix the issue would mean not reading the config file until necessary.

I plan at some point to add global config for rclone in the config file which would require reading the config file regardless, so I'm not sure not reading the config file is an option.

**Comment by hyperknot** [comment]
Before requiring a global config, think about all the use cases when rclone is used for automation, via server side scripts. I believe rclone might have started as a interactive, user facing program first, hence the config architecture and requiring the `obscure` command, etc.

But today, I believe rclone is widely used in server side scripts, doing overnight backups, etc. In those cases, you really want to have no state, whatsoever. You call rclone via a programming language's native functionality, passing arguments directly (without quoting issues, or `.bash_history` dangers). 

For example, here is the complete function for doing a client-side encrypted syncing from Backblaze B2, implemented in Python 3.7:

```
def rclone_sync_remote_local(dir, b2_account, b2_key, b2_bucket_name, encryption_password):
    p = subprocess.run(['rclone', 'obscure', encryption_password], capture_output=True, text=True)

    if p.returncode != 0 or p.stderr:
        print(f'error with cmd, output was: {p.stdout}\n\nerror was:\n{p.stderr}')
        return False

    passkey = p.stdout.strip()

    rclone_command = [
        'rclone',
        'sync',
        '--b2-account',
        b2_account,
        '--b2-key',
        b2_key,
        '--crypt-remote',
        f':b2:{b2_bucket_name}',
        '--crypt-filename-encryption=off',
        '--crypt-directory-name-encryption=false',
        '--crypt-password',
        passkey,
        '--transfers=32',
        '--fast-list',
        '--local-no-check-updated',
        '--config=/dev/null',
        '--log-file',
        f'{shared_dir}/restore_{dir}.log',
        '-v',
        '--stats=10s',
        '--stats-file-name-length=0',
        '--stats-one-line',
        f':crypt:/{dir}',
        f'{shared_dir}/{dir}',
    ]

    print(f'Restoring {dir}')
    p = subprocess.run(rclone_command, capture_output=True, text=True)

    if p.returncode != 0 or p.stderr:
        print(f'error with cmd, output was: {p.stdout}\n\nerror was:\n{p.stderr}')
        return False
```

This is a really nice, reliable solution, which is actually much faster than using backblaze's native cli. In terms of encryption, I believe rclone is probably the only solution which supports a fast, built-in client side encryption which works across storage providers.

I hope this use case explains, why making sure that rclone can always work without any kind of state is critical for this workflow. +Also explains why a `--no-obscure` flag would be really nice for scripted usage.

**Comment by ncw** [comment]
> Before requiring a global config,

Don't worry, rclone will never require a global config.

My plan is to add a `globals` section to the config file so you can put frequently used options in.

So what this would mean is that if rclone finds a config file it will open it and look in it.

Today rclone does the same, if there is a config file, it will open it.  I could make it so that rclone didn't open the config file unless there was config that required it which would fix this issue.  However in the future adding that globals section would require rclone to always open the config file if it exists.

Maybe the best solution to this would be to make a config option something so you could say specifically - do not use a config file.  Say `--config ""`.  What do you think of that idea?


> This is a really nice, reliable solution, which is actually much faster than using backblaze's native cli. In terms of encryption, I believe rclone is probably the only solution which supports a fast, built-in client side encryption which works across storage providers.

Indeed - very nice :-)



> I hope this use case explains, why making sure that rclone can always work without any kind of state is critical for this workflow. +Also explains why a `--no-obscure` flag would be really nice for scripted usage.

I see you found the relevant issue for that :-)

**Comment by hyperknot** [comment]
Sure! I'd simply call it `--no-config`, although I wonder what is the use case of `--ask-password=false` then?

**Comment by ivandeex** [comment]
I think that we don't need a `--no-config` flag anymore.
The `--config=/dev/null` trick works perfectly on Unix.
Then, since the commit https://github.com/rclone/rclone/commit/bb0b6432ae5d74a741815a8cc1f0cf2d46e3dddb has landed on master, starting with 1.55 release there will be an OS independent way to disable config file access: `--config=/notfound` and `--config=""`
We just need it documented, which is requested by #5125

**Comment by albertony** [comment]
> The `--config=/dev/null` trick works perfectly on Unix.

Seems `--config=NUL` works on Windows:

```
rclone config file --config=NUL
Configuration file is stored at:
\NUL
```

Pointing to non-existing file also works, I guess, but shows a NOTICE that is avoided by using `NUL`
```
rclone config file --config=notfound
2021/03/16 12:05:18 NOTICE: Config file "C:\\redacted\\notfound" not found - using defaults
Configuration file doesn't exist, but rclone will use this path:
C:\redacted\notfound
```

Corresponds to behavior on Unix?

**Comment by ivandeex** [comment]
@ncw I suggest closing this. We don't need another flag. The current one is enough.

**Comment by ncw** [comment]
Yes this is covered by `--config=""` now so we can close.
