### ISSUE TITLE
chocolatey - install beta

### ISSUE THREAD

**Issue by 88lex** [rclone/rclone#2888]
Chocolatey is a pretty handy way to install apps on Windows, including rclone. I note that the versions of rclone included in the choco repo are quite old. Is there any way to update the link in choco so that we could install both latest and beta?

#### What problem are you are trying to solve?
Manual install of rclone files in Windows

#### How do you think rclone should be changed to solve that?

Add links to rclone windows files in the chocolatey repo. (Old ones exist, and install fine. But no updated versions).

Thank you!

**Comment by ncw** [comment]
rclone didn't make it into chocolately as part of the rclone project.  According to chocolately it was: https://chocolatey.org/profiles/kkzinger who put it in.

It might be best to give them a nudge.  If they (or you) would like to submit automation for getting rclone into chocolately I'd be receptive :-)

**Comment by lex8888** [comment]
Fair enough. I'll poke kkzinger. Looks like someone else has also poked him re the newer versions of rclone.

**Comment by animosity22** [comment]
Closing as this looks answered.
