### ISSUE TITLE
Copy Folders With # character Dosen't Work

### ISSUE THREAD

**Issue by felipe-negri** [rclone/rclone#2920]
#### What is the problem you are having with rclone?

Directory not found when the character # as on the String 

#### What is your rclone version (output from `rclone version`)

v1.45

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubunt 18.04

####  Which cloud storage system are you using? (eg Google Drive)

OneDrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy( But happn with all commands)

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

`019/01/17 01:09:10 DEBUG : rclone: Version "v1.45" starting with parameters ["rclone" "copy" "OneDrive:Integracao/Comics_Prontas/Album1 #XD" "./tmp/album" "-vv"]
2019/01/17 01:09:10 DEBUG : Using config file from "/home/hiroshi/.config/rclone/rclone.conf"
2019/01/17 01:09:13 ERROR : : error reading source directory: directory not found
2019/01/17 01:09:13 INFO  : Local file system at /home/hiroshi/Documents/projetos/telegram-album-bot/tmp/album: Waiting for checks to finish
2019/01/17 01:09:13 INFO  : Local file system at /home/hiroshi/Documents/projetos/telegram-album-bot/tmp/album: Waiting for transfers to finish
2019/01/17 01:09:13 ERROR : Attempt 1/3 failed with 1 errors
2019/01/17 01:09:14 ERROR : : error reading source directory: directory not found
2019/01/17 01:09:14 INFO  : Local file system at /home/hiroshi/Documents/projetos/telegram-album-bot/tmp/album: Waiting for checks to finish
2019/01/17 01:09:14 INFO  : Local file system at /home/hiroshi/Documents/projetos/telegram-album-bot/tmp/album: Waiting for transfers to finish
2019/01/17 01:09:14 ERROR : Attempt 2/3 failed with 1 errors
2019/01/17 01:09:14 ERROR : : error reading source directory: directory not found
2019/01/17 01:09:14 INFO  : Local file system at /home/hiroshi/Documents/projetos/telegram-album-bot/tmp/album: Waiting for checks to finish
2019/01/17 01:09:14 INFO  : Local file system at /home/hiroshi/Documents/projetos/telegram-album-bot/tmp/album: Waiting for transfers to finish
2019/01/17 01:09:14 ERROR : Attempt 3/3 failed with 1 errors
2019/01/17 01:09:14 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 1 (retrying may help)
Checks:                 0 / 0, -
Transferred:            0 / 0, -
Elapsed time:        4.1s

2019/01/17 01:09:14 DEBUG : 4 go routines active`

**Comment by ncw** [comment]
How did you upload those file?  Were they uploaded with rclone?

The `#` character is a reserved character for onedrive business so rclone translates it back and forth into a unicode lookalike `＃`.

However it isn't a reserved character for plain onedrive so rclone probably shouldn't be translating it for onedrive backends not onedrive business backends...

**Comment by felipe-negri** [comment]
I didn`t upload the folder with rclone

**Comment by ivandeex** [comment]
@ncw @Cnly @felipe-negri
This issue has been probably solved by recent improvements in filename encoding and needs a retest

**Comment by Cnly** [comment]
This should have been fixed by by #4909. A beta version has been uploaded here: https://beta.rclone.org/branch/onedrive-dont-encode-hash-percent/v1.54.0-beta.5038.2aed3d595.onedrive-dont-encode-hash-percent/. Any help with the testing would be appreciated!

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54
