### ISSUE TITLE
B2 single bucket application keys

### ISSUE THREAD

**Issue by loadcorp** [rclone/rclone#2923]
#### What is your current rclone version (output from `rclone version`)?

Version 1.45

#### What problem are you are trying to solve?

Can't use single key of bucket in B2 Cloud. I can use only key which covered all buckets.

#### How do you think rclone should be changed to solve that?

Rclone must work with single keys too.

Examples:

1. In B2 cloud I am click on 'Add Application Key' and in fields 'Allow access to bucket(s):' I choose All. Then your software working correctly, but I am giving to access to my all buckets (which is not what I want in some cases).

Logs of transfer:

> 2019/01/18 06:08:39
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:        1.8s
> 
> 2019/01/18 06:08:39 B2 bucket testingbucketsz: Waiting for checks to finish
> 2019/01/18 06:08:39 B2 bucket testingbucketsz: Waiting for transfers to finish
> 2019/01/18 06:08:40
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:        2.8s
> Transferring:
> *                                       123.png:  0% done, 0 Bytes/s, ETA: -
> 
> 2019/01/18 06:08:41
> Transferred:   38.847 kBytes (10.204 kBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:        3.8s
> Transferring:
> * 123.png
> 
> 2019/01/18 06:08:42
> Transferred:   38.847 kBytes (8.081 kBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:        4.8s
> Transferring:
> * 123.png
> 
> 2019/01/18 06:08:43
> Transferred:   38.847 kBytes (6.689 kBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:        5.8s
> Transferring:
> * 123.png
> 
> 2019/01/18 06:08:43
> Transferred:   38.847 kBytes (6.059 kBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            1
> Elapsed time:        6.4s

2. In B2 cloud I am click on 'Add Application Key' and in fields 'Allow access to bucket(s):' I choose ONLY ONE bucket which with I want to work. In this way your software does not want to work correctly.

Logs:

> 2019/01/18 06:24:03
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:        1.7s
> 
> 2019/01/18 06:24:04
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:        2.7s
> 
> 2019/01/18 06:24:05
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:        3.7s
> 
> 2019/01/18 06:24:06
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:        4.7s
> 
> 2019/01/18 06:24:06 Attempt 1/3 failed with 1 errors and: failed to create bucket: Unknown 401  (401 unauthorized)
> 2019/01/18 06:24:07
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:        5.7s
> 
> 2019/01/18 06:24:08
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:        6.7s
> 
> 2019/01/18 06:24:09
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:        7.7s
> 
> 2019/01/18 06:24:10
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:        8.7s
> 
> 2019/01/18 06:24:10 Attempt 2/3 failed with 1 errors and: failed to create bucket: Unknown 401  (401 unauthorized)
> 2019/01/18 06:24:11
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:        9.7s
> 
> 2019/01/18 06:24:12
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:       10.7s
> 
> 2019/01/18 06:24:13
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:       11.7s
> 
> 2019/01/18 06:24:14
> Transferred:      0 Bytes (0 Bytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:       12.7s
> 
> 2019/01/18 06:24:14 Attempt 3/3 failed with 1 errors and: failed to create bucket: Unknown 401  (401 unauthorized)
> 2019/01/18 06:24:14 Failed to copy: failed to create bucket: Unknown 401  (401 unauthorized)

**Comment by ncw** [comment]
> Can't use single key of bucket in B2 Cloud. I can use only key which covered all buckets.

Rclone does work with [B2 application keys](https://rclone.org/b2/#application-keys).

Can you show the rclone commands you are using please?

**Comment by cyphar** [comment]
I've hit this issue too. This is with an already-existing bucket. I've been using `rclone` for a while to copy data, and all I did was change the `account` and `key` options in `rclone.conf`. Here is the command I'm using:

```
% rclone -v sync --one-file-system --b2-hard-delete --fast-list --transfers 1 /store/glacier-backup/.zfs/snapshot/rclone:1559970872 b2cyphar:cyphar/glacier
```

The issue **only** happens if you create an application key which is *restricted to a specific bucket*. If you make one that isn't restricted to a bucket, it works perfectly fine. So it's definitely an `rclone` bug with these types of keys.

**Comment by ncw** [comment]
@cyphar wrote:
> I've hit this issue too. This is with an already-existing bucket. I've been using `rclone` for a while to copy data, and all I did was change the `account` and `key` options in `rclone.conf`. Here is the command I'm using:

I'm under the impression that rclone does work with keys linked to a single bucket.  It certainly does with my testing.

> ```
> % rclone -v sync --one-file-system --b2-hard-delete --fast-list --transfers 1 /store/glacier-backup/.zfs/snapshot/rclone:1559970872 b2cyphar:cyphar/glacier
> ```
> 
> The issue **only** happens if you create an application key which is _restricted to a specific bucket_. If you make one that isn't restricted to a bucket, it works perfectly fine. So it's definitely an `rclone` bug with these types of keys.

What version of rclone are you using?  Can you try 1.47 if it isn't [the latest release](https://rclone.org/downloads/)?

What are the log messages you are getting?

**Comment by ncw** [comment]
Single bucket keys should definitely be working.

If not then please open a fresh issue - thanks.
