### ISSUE TITLE
dropbox file id

### ISSUE THREAD

**Issue by ArthurGing** [rclone/rclone#2928]
#### What is the problem you are having with rclone?
I try to lsf and lsjson to my dropbox account, but it didn't show file id.
Then I list my account using dropbox api with https request, the file id is in response.
How to get file id of dropbox file with rclone?

#### What is your rclone version (output from `rclone version`)
1.45

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
linux 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
dropbox

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone lsf --format stpim remote: -R
rclone lsjson remote: -R

**Comment by ncw** [comment]
It looks like the dropbox backend doesn't store the IDs of the files at the moment.

This would be relatively easy to add - do you want to have a go?

**Comment by ArthurGing** [comment]
I try to modify dropbox.go and it worked, but I don't know this modify is correct or not, I'm unfamiliar with go language.

[dropbox.zip](https://github.com/ncw/rclone/files/2780954/dropbox.zip)

**Comment by ncw** [comment]
@ArthurGing wrote

> I try to modify dropbox.go and it worked, but I am not sure this modify is correct or not, I'm unfamiliar with go language.

That looks very good - I don't see anything I'd like to change :-)  I think you didn't start from the latest code, so your diff looks like this cleaned up a bit.

Do you want to send a pull request with that?  You might need to run `go fmt` on the code.

```diff
--- backend/dropbox/dropbox.go	2019-01-14 17:46:54.350989559 +0000
+++ /home/ncw/Downloads/dropbox.go	2019-01-22 09:20:36.000000000 +0000
@@ -173,6 +172,7 @@
 	bytes   int64     // size of the object
 	modTime time.Time // time it was last modified
 	hash    string    // content_hash of the object
+        id      string    // file Id
 }
 
 // ------------------------------------------------------------
@@ -519,7 +510,7 @@
 			leaf := path.Base(entryPath)
 			remote := path.Join(dir, leaf)
 			if folderInfo != nil {
-				d := fs.NewDir(remote, time.Now())
+				d := fs.NewDir(remote, time.Now()).SetID(folderInfo.Id)
 				entries = append(entries, d)
 			} else if fileInfo != nil {
 				o, err := f.newObjectWithInfo(remote, fileInfo)
@@ -909,6 +900,7 @@
 	o.bytes = int64(info.Size)
 	o.modTime = info.ClientModified
 	o.hash = info.ContentHash
+        o.id = info.Id
 	return nil
 }
 
@@ -957,6 +949,11 @@
 	return o.modTime
 }
 
+// ID returns the ID of the Object if known, or "" if not
+func (o *Object) ID() string {
+	return o.id
+}
+
 // SetModTime sets the modification time of the local fs object
 //
 // Commits the datastore
@@ -1147,4 +1144,5 @@
 	_ fs.DirMover     = (*Fs)(nil)
 	_ fs.Abouter      = (*Fs)(nil)
 	_ fs.Object       = (*Object)(nil)
+        _ fs.IDer         = (*Object)(nil)
 )
```
