### ISSUE TITLE
openmediavault Plugin

### ISSUE THREAD

**Issue by Samuel12321** [rclone/rclone#2931]
#### What problem are you are trying to solve?
Make it easy for people to sync files fom a Open media vault NAS to a cloud service

#### How do you think rclone should be changed to solve that?
- An OMV plugin could be made

**Comment by ncw** [comment]
I don't think an issue to build a plugin for open media vault belongs here...

I think here is the right place

https://github.com/openmediavault/openmediavault

**Comment by animosity22** [comment]
Closing as it would be done via openmediavault.
