### ISSUE TITLE
Cache truncates drive response body in logs

### ISSUE THREAD

**Issue by splitice** [rclone/rclone#2935]
#### What is the problem you are having with rclone?

Verbose output logs are incomplete

#### What is your rclone version (output from `rclone version`)

mmap-beta

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 64bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
Jan 25 04:23:59 localhost rclone[573]: 2019/01/25 04:23:59 ERROR : k519e9m2f1rcm04pqi8m8hemro/qs224os1aeg4bgd1selph9ndjk/ligpvjbpre6cksk0v7ij0t0af0/0prcsqal1k3rosbuugh3qa5k9o/p930n5c3n7uu8fcv5vssain579t5f7jr65djhlhp6nhge0l2sl3k7fe3fm6lkb1ag482j4dtdrlngej5bacmgjvjkmbeb89d0jgrtbjk1b36tgstl1ehgk4uhs98ahbg: (0/581218983
Jan 25 04:24:00 localhost rclone[573]: 2019/01/25 04:24:00 ERROR : worker-0 <p930n5c3n7uu8fcv5vssain579t5f7jr65djhlhp6nhge0l2sl3k7fe3fm6lkb1ag482j4dtdrlngej5bacmgjvjkmbeb89d0jgrtbjk1b36tgstl1ehgk4uhs98ahbg>: object open failed 0: open file failed: googleapi: got HTTP response code 403 with body:
Jan 25 04:24:10 localhost rclone[573]: 2019/01/25 04:24:10 ERROR : worker-0 <p930n5c3n7uu8fcv5vssain579t5f7jr65djhlhp6nhge0l2sl3k7fe3fm6lkb1ag482j4dtdrlngej5bacmgjvjkmbeb89d0jgrtbjk1b36tgstl1ehgk4uhs98ahbg>: object open failed 0: open file failed: googleapi: got HTTP response code 403 with body:
```

The actual error would be along the lines of downloadQuota exceeded which would be useful to include in that line.

**Comment by ncw** [comment]
I just had a look through the code of the drive SDK.

It looks like that this error isn't truncated - there just wasn't anything in the body.

Either that or it is a bug in the drive SDK not capturing the body.

I don't think it is anything to do with the cache or rclone's code truncating the message.

Is it easy to replicate?

**Comment by splitice** [comment]
Right now the error I'm hitting is the downloadQuotaExceeded - and if I remove the cache layer (so that it's just drive & crypt) I get the message in the logs.

**Comment by ncw** [comment]
> Right now the error I'm hitting is the downloadQuotaExceeded - and if I remove the cache layer (so that it's just drive & crypt) I get the message in the logs.

So what does the error look like without cache? The same or different?

**Comment by splitice** [comment]
It was along the lines of:

```
Failed to copy: failed to open source object: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
```

As this issue was a side effect of using the v2 API (which no longer seems advisable due to new rate limiting) and I have hence removed it - I don't see it any more.

**Comment by ncw** [comment]
> As this issue was a side effect of using the v2 API (which no longer seems advisable due to new rate limiting) and I have hence removed it - I don't see it any more.

Ah... Do you think this could have been entirely to do with the v2 API?  That might make more sense.  I just can't see how the cache might mangle error codes :-(

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
