### ISSUE TITLE
rc: allow unix domain socket in rc-addr

### ISSUE THREAD

**Issue by namibj** [rclone/rclone#2950]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.45
- os/arch: linux/amd64
- go version: go1.11.2

#### What problem are you are trying to solve?
Accessing rclone securely over a unix socket.
If others can connect to [::1]:5572, I would need to manage passwords and/or preferably certificates. I would also need to wary of others already using this port, and implement a way to find out which port I need to connect to. This is error prone and at least on Linux and BSD it is not needed.

#### How do you think rclone should be changed to solve that?
I would like rclone rc/rclone rcd to allow binding to an unix domain socket.
It could be offered via rc-addr and a way to specify file permissions for the socket.
Maybe via prefixing the path with the e.g. 0700 (default) permissions and a char that is not allowed in the existing syntax, so that no parsing ambiguity is introduced.

In the _future_ this could be extended (these require a unix domain socket, but I can live without them for now. The out-of-band streaming in both directions without fuse is the only thing I'd "need" any time soon) to sending/receiving file descriptors, to allow for the following features/usecases:
- secure access to temporary files, which can be
  - created with open(2) and the O_TMPFILE flag
  - (this one is Linux >=3.11 only)
  - _inside_ an existing directory as far as backing storage is concerned,
- secure/invisible (pre)processing of data,
  - think handling tarballs on-the-fly in both directions,
  - etc.,
- efficient streaming of pre/post-processing actions
  - either via a fifo created via pipe(2),
  - an anonymous seekable file from open(2) with the O_TMPFILE flag,
  - a seekable ram-only file from memfd_create(2) (Linux >=3.17 only),
  - an anonymous file backed by rclone fuse for the above cases, but lazy-loading and explicit use of the rclone data cache,
- etc.

See [SIGINT gotcha](https://stackoverflow.com/questions/16681944/how-to-reliably-unlink-a-unix-domain-socket-in-go-programming-language) on stackoverflow for how to prevent littering the filesystem, as the socket needs manual cleanup.

**Comment by ncw** [comment]
It looks like [serving http over a unix socket](https://gist.github.com/teknoraver/5ffacb8757330715bcbcc90e6d46ac74) isn't too tricky.

`rclone serve restic` serves http/2 multiplexed over stdin/stdout which works well.  The rc server doesn't support this at the moment, but it could.

Do you want to work on adding unix socket support to [the http library](https://github.com/ncw/rclone/blob/master/cmd/serve/httplib/httplib.go)?

**Comment by B4dM4n** [comment]
A while ago I added support for unix sockets to rc in very quick and dirty fashion: [B4dM4n:rc-unix](https://github.com/ncw/rclone/compare/master...B4dM4n:rc-unix)

I'm using this for my rclone mounts and it's working great. The only issue is that the socket file is not always deleted on exit (I just realized mount does not use `cmd.resolveExitCode` or trigger `atexit.Run` in another way).

If someone wants to build a clean implementation, this could be used as a starting point.

**Comment by Aidolii** [comment]
WinSock support would be nice as well...

**Comment by ncw** [comment]
I'll just note that I think this

> The only issue is that the socket file is not always deleted on exit (I just realized mount does not use cmd.resolveExitCode or trigger atexit.Run in another way).

Is fixed if anyone wants to have a go at merging @B4dM4n 's changes.

**Comment by ncw** [comment]
@scj643 if you want to have a go at this it would be great.

**Comment by darthShadow** [comment]
I believe this is addressed with the recent addition of unix socket support in the lib/http code and the subsequent refactor to use lib/http for the rc server.
