### ISSUE TITLE
Google drive: rclone from different devices show different contents

### ISSUE THREAD

**Issue by tscmacdonald** [rclone/rclone#2957]
#### What is the problem you are having with rclone?

I'm storing music on a gsuite google drive, which is mounted as a directory on my Windows laptop using Google File Stream (rclone v1.45/Windows 10). I also access this drive from a headless server (rclone v1.45/Ubuntu Xenial), but when doing so I can only see an incomplete selection of the files. Many directories are not visible to `rclone ls`, and attempting to pull from them gives file not found errors.

The complete list of files is visible through the Drive web interface, through the Google File Stream mount on my Windows device, and through `rclone ls` on my Windows device. 

#### What is your rclone version (output from `rclone version`)
*Windows laptop:*
rclone v1.45
- os/arch: windows/amd64
- go version: go1.11

*Server:*
rclone v1.45
- os/arch: linux/arm
- go version: go1.11.2

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
*Laptop:*
Windows 10, 64 bit
*Server*
Ubuntu Xenial 16.04

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone lsd gdrive:directory`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Logs from linux and windows devices attached.

[rclone-log-linux.txt](https://github.com/ncw/rclone/files/2843138/rclone-log-linux.txt)
[rclone-log-windows.txt](https://github.com/ncw/rclone/files/2843139/rclone-log-windows.txt)

**Comment by calisro** [comment]
You sure that's the same remote?  Why does the command line on linux say gsuites: and the log say tscmacdonald-gsuites? Thought that was odd.


 root@server:~# rclone -vv lsd gdrive:music
2019/02/07 23:59:54 DEBUG : rclone: Version "v1.45" starting with parameters ["rclone" "-vv" "lsd" "tscmacdonald-gdrive:music"]

**Comment by tscmacdonald** [comment]
@calisro It is, yes, but I attempted to edit the log to remove my name from the command. Looks like I missed one.

Files pushed to the drive from the Linux device appear when accessed from the Windows device, but the opposite doesn't always seem to be true.

**Comment by tscmacdonald** [comment]
I've just run `rclone lsd` from a raspberrypi, and it sees the full and correct list of directories. *I've also just noticed that all the directories that do not appear from the Xenial device were last modified in 2017*: the Xenial device is *only displaying files modified in 2019*, while my Windows laptop + rpi are showing all files correctly (including some with older timestamps).

**Comment by ncw** [comment]
Make sure you run an [rclone dedupe](https://rclone.org/commands/rclone_dedupe/) - duplicated directories can cause symptoms like this.

**Comment by tscmacdonald** [comment]
@ncw dedupe cleaned up a few directories, but none of the problematic ones had duplicates. Following a dedupe run, my server still can't see any of the pre-2019 directories.

**Comment by ncw** [comment]
> @ncw dedupe cleaned up a few directories, but none of the problematic ones had duplicates. Following a dedupe run, my server still can't see any of the pre-2019 directories.

Can you copy the config file from the Windows machine and try it on the Ubuntu one?

Use `rclone config file` to find the config file, then you can use `--config` to use it on the Ubuntu machine.

**Comment by animosity22** [comment]
This looks to be stale. If you still have a question, please just ask on the forums and we can help out.
