### ISSUE TITLE
Extracting progress parameters for reporting

### ISSUE THREAD

**Issue by lucanello** [rclone/rclone#2970]
#### What is your current rclone version (output from `rclone version`)?
v1.45

#### What problem are you are trying to solve?
Currently there is the possibility to display progress at the end of each transfer in the command line. I want to automate my backups and therefore use the summary for my reportings. In order to achieve that, there has to be the possibility to extract the parameters of the total files transferred, the file sizes, the duration, the transfer speed etc.

#### How do you think rclone should be changed to solve that?
The parameters could be saved to a file for further use or simply be returned as array or so.

**Comment by ncw** [comment]
If you use the `-v` flag, rclone will log how it processes each file.

This isn't exactly what you want but it might be helpful.

**Comment by lucanello** [comment]
@ncw Thanks for your answer! I am planning to use the logging-function and a python script which extracts those informations from the log. But that's not really the clean way to do it. It will be super-difficult to decode the summary because it's formatted with spaces etc.
I thought the implementation of having the ability to extract the parameters would be easier. Are there any future plan on this?

**Comment by ncw** [comment]
There are some issues about rclone using a structured logging output which would probably help with your plan, but none about producing a report I don't think.

**Comment by lucanello** [comment]
@ncw Is it so complicated to implement a new argument which is working like the logging function but with the output formatted as json? It doesn't sound like a huge project but unfortunately I have no programming skills to solve this. It would be awesome if you could solve this issue which will be important for future extensibility.

**Comment by ncw** [comment]
The relevant issues are
- https://github.com/ncw/rclone/issues/2459
- https://github.com/ncw/rclone/issues/2453

To use a structured logger.  That is probably a better way of going than just using an ad-hoc JSON dump

**Comment by ncw** [comment]
We now have --use-json-log which I think covers this issue (along with `-v` flag).
