### ISSUE TITLE
reverse connect feature

### ISSUE THREAD

**Issue by vtolstov** [rclone/rclone#2972]
i love rclone and can't find older discussion when i'm create read-only http support.
May be i'm wrong... So as i remember you try to create some feature that allows one backend to export as another.
My use case - i want to export local fs like s3 endpoint.

**Comment by ncw** [comment]
> i love rclone and can't find older discussion when i'm create read-only http support.
> May be i'm wrong... So as i remember you try to create some feature that allows one backend to export as another.
> My use case - i want to export local fs like s3 endpoint.

You can use `rclone serve` to export backends,

These are the most general purpose ones

  ftp         Serve remote:path over FTP.
  http        Serve the remote over HTTP.
  webdav      Serve remote:path over webdav.

And those all have backends which can read them.

**Comment by vtolstov** [comment]
And If i want to programming way to serve local file dir via s3 api?
May be with custom hooks for auth and permissions?

**Comment by ncw** [comment]
Rclone doesn't serve s3 API yet :-(

You could use [minio](https://github.com/minio/minio) to serve a local directory with S3

**Comment by vtolstov** [comment]
i want something not like minio provides, i need to go library to represent each api like interface, so i can provide interface implementation by own code...
Do you think about something like that?

**Comment by ncw** [comment]
> i want something not like minio provides, i need to go library to represent each api like interface, so i can provide interface implementation by own code...
> Do you think about something like that?

So you would like to use rclone as a library?

It is possible to do this.  Here is a simple example

```go
package main

import (
	"fmt"
	"log"

	_ "github.com/ncw/rclone/backend/drive"
	"github.com/ncw/rclone/fs"
)

func main() {
	f, err := fs.NewFs("drive:")
	if err != nil {
		log.Fatal(err)
	}
	entries, err := f.List("")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(entries)
}
```

**Comment by vtolstov** [comment]
i want to use rclone as library, but not like client to some storage, but as like proxy for it. to external world rclone will provide for example s3 api, and internally for rclone and for each request to rclone external s3 api , my implementation of s3 rclone interface called.

**Comment by ncw** [comment]
> i want to use rclone as library, but not like client to some storage, but as like proxy for it. to external world rclone will provide for example s3 api, and internally for rclone and for each request to rclone external s3 api , my implementation of s3 rclone interface called.

You can use `rclone serve` for this to serve an rclone backend in various standard forms - see `rclone serve -h`

You can also use [rclone api](https://rclone.org/rc/).  Using `rclone rcd --rc-serve` runs a remote control server which gives access to all the remotes (docs for [--rc-serve](https://rclone.org/rc/#rc-serve)).

You can do pretty much anything rclone can do using the rc API.  It is a simple JSON based HTTP API.

**Comment by vtolstov** [comment]
ah ok, so i need to write for rclone serve s3 and swift protocols to able to do that i need.

**Comment by animosity22** [comment]
Looks to be answered. Closing out.
