### ISSUE TITLE
Option to compress cache databases with zstd

### ISSUE THREAD

**Issue by ealgase** [rclone/rclone#2978]
#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.46
- os/arch: linux/amd64
- go version: go1.11.5
```
#### What problem are you are trying to solve?

My .db file for my cache remote is 85M, which takes up a significant amount of space (I'm operating on a system with very little storage).  

#### How do you think rclone should be changed to solve that?

I tried using `zstd` to compress it and it shrunk to 7.1M, which is significant.  `zstd` is incredibly fast to compress and decompress so it wouldn't take significantly more time to access the database (it may take less if the disk has low speed).

**Comment by ncw** [comment]
You could try compacting the database: https://github.com/boltdb/bolt/pull/460 that might help.
