### ISSUE TITLE
grep inside file contents

### ISSUE THREAD

**Issue by eadmaster** [rclone/rclone#2983]
some storage providers like gdrive have a [feature to search inside the files](https://gsuitetips.com/tips/drive/advanced-searches-on-google-drive/).

Can i access this feature from rclone?
The [`ls` command seems able to search the filenames only](https://rclone.org/commands/rclone_ls/), not the contents.

**Comment by animosity22** [comment]
Like this?

`
felix@gemini:/GD$ cp /etc/hosts .
felix@gemini:/GD$ rclone cat gcrypt:hosts
127.0.0.1	localhost
192.168.1.30	host
`

**Comment by eadmaster** [comment]
grepping over `rclone cat` output is slow, a server-side solution would be better...

**Comment by animosity22** [comment]
assuming the cloud provider offers that API.

**Comment by ncw** [comment]
This could be implemented by an optional API which uses the provider specific search and falls back to `rclone cat`.

The drive search API will show a list of filenames, so will work like `grep -l`: https://developers.google.com/drive/api/v3/search-parameters

**Comment by ivandeex** [comment]
Closing after 2 years of inactivity
