### ISSUE TITLE
rc JSON parsing errors when path contains single quote

### ISSUE THREAD

**Issue by bfranske** [rclone/rclone#2986]
#### What is the problem you are having with rclone?
When passing commands to rclone as remote control (rc) and one of the parameters is a path that contains a single quote (e.g. as an apostrophe) there doesn't seem to be a way to escape it when sending the path as JSON. See below for examples

#### What is your rclone version (output from `rclone version`)
rclone v1.46
- os/arch: linux/amd64
- go version: go1.11.5

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 64bit, MacOS 64bit

####  Which cloud storage system are you using? (eg Google Drive)
not applicable

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone rc operations/list --json '{"fs":"/", "remote":"big-storage/Ben's Test"}'`
or
`rclone rc operations/list --json '{"fs":"/", "remote":"big-storage/Ben\'s Test"}'`
or any other similar command (e.g. sync/sync) which may have a path in it with single quotes. Clearly this is due to the fact BASH is already using single quotes to take in the JSON string so single quotes can't be used inside the string.

Note that using params works:
`rclone rc operations/list fs="/" remote="big-storage/Ben's Test"`
Produces the expected output:
`{
        "list": [
                {
                        "IsDir": false,
                        "MimeType": "application/octet-stream",
                        "ModTime": "2019-02-19T18:47:39.738305018-06:00",
                        "Name": "testfile",
                        "Path": "big-storage/Ben's Test/testfile",
                        "Size": 0
                }
        ]
}`

Also, using double quotes to encase the JSON string and then escaping the double quotes inside the string also works:
`rclone rc operations/list --json "{\"fs\":\"/\", \"remote\":\"big-storage/Ben's Test\"}"`

So **maybe** the solution is simply to update the documentation for rc to show how to escape JSON for the types of characters that may be encountered in paths. This would likely require further testing of characters that could exist in paths to verify they can all be escaped properly.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
not applicable

**Comment by ncw** [comment]
This is a bash problem really, rather than an rclone problem...

The `--json` flag is there for testing - it isn't wildly convenient typing JSON in on the command line!

An alternative might be `--jsonfile` to read from a file or from stdin.

> So **maybe** the solution is simply to update the documentation for rc to show how to escape JSON for the types of characters that may be encountered in paths. This would likely require further testing of characters that could exist in paths to verify they can all be escaped properly.

Perhaps recommending the single quotes, but stating: if you want to add a single quote `'` into the `--json` parameter while using bash, then use `'"'"'` instead (that closes the string, adds a single quote in double quotes, then opens the string again).

**Comment by animosity22** [comment]
This looks to be answered so closing out.
