### ISSUE TITLE
[Bug or feature?] Is cache poll-interval supposed to be the same as chunk-clean-interval ?

### ISSUE THREAD

**Issue by jmoriau** [rclone/rclone#2998]
I thought I was going crazy, trying all sorts of settings to not have the cache poll for changes every minutes. Nothing would work.

So though I'd look through the code if I could see anything obvious.

Then I found this line : https://github.com/ncw/rclone/blob/a0d4c04687f06f9704f82cce291d458836884d13/backend/cache/cache.go#L510

```go
if doChangeNotify := wrappedFs.Features().ChangeNotify; doChangeNotify != nil {
		pollInterval := make(chan time.Duration, 1)

		pollInterval <- time.Duration(f.opt.ChunkCleanInterval) <--------

		doChangeNotify(f.receiveChangeNotify, pollInterval)
	}
```

So my question is this : is it supposed to be this way ? I would have thought that ChunkCleanInterval and PollInterval are unrelated to each other.
Because obviously I want a fairly quick ChunkCleanInterval but if possible I would like a 24h PollInterval.
I haven't used the cache for like a year but I think it used to be that we could set both to different durations.

**Comment by ncw** [comment]
I just looked through the source history.  It has been this way since the start of the cache backend.

It would be easy enough to factor into a new config variable - fancy sending a PR?

**Comment by jmoriau** [comment]
I've never written any Go, I usually stick to Ruby/Rust, and sadly I don't have enough time until the exams are over.
But if it's still unresolved by June then I'll happily get to it then!

Thanks!

**Comment by ncw** [comment]
> I've never written any Go, I usually stick to Ruby/Rust, and sadly I don't have enough time until the exams are over.
> But if it's still unresolved by June then I'll happily get to it then!

The change should be quite simple - adding a new config option like this one

https://github.com/ncw/rclone/blob/0bc0f62277c8b52528bfb34e1e64e87ff4ffb217/backend/cache/cache.go#L271-L281

Add it to the `Options` struct

https://github.com/ncw/rclone/blob/0bc0f62277c8b52528bfb34e1e64e87ff4ffb217/backend/cache/cache.go#L287

Then use it in the offending code above

**Comment by ivandeex** [comment]
Closing after 2 years of inactivity
