### ISSUE TITLE
Issue on Team Drive Configuration

### ISSUE THREAD

**Issue by dav1303** [rclone/rclone#3001]
Hi

When I try to add a team drive access it seems there is an issue since today.

The Team Drive list not appears anymore and when I fill a team drive ID it not works also

It seems something has change on Google Side because it has works well before.

Remote config
Configure this as a team drive?
y) Yes
n) No
y/n> y
Fetching team drive list...
Listing team drives failed: googleapi: Error 500: Internal Error, internalError
Choose a number from below, or type in your own value

Thanks

**Comment by dav1303** [comment]
Just to precise I'll try using a SA and give a json file to be able to use impersonification

**Comment by ncw** [comment]
> Error 500: Internal Error, internalError

This is google's server giving the error and the 500 indicates that it is a problem with the server.

Is it working now?

**Comment by arcticlinux** [comment]
I'm also experiencing this issue.  I was thinking I am not doing the configuration properly, but I have tried a number of times.

Either the server is broken or the configuration procedure is slightly different now?

**Comment by ncw** [comment]
> I'm also experiencing this issue. I was thinking I am not doing the configuration properly, but I have tried a number of times.
> 
> Either the server is broken or the configuration procedure is slightly different now?

The fetching of the list of team drives might fail, but if you know the ID of it then you can still configure it.

**Comment by arcticlinux** [comment]
I did try configuring it manually, maybe I'm doing it wrong?

I've tried it both these ways:

[GSuiteTest]
type = drive
scope = drive
client_id = XXXXXYYYYYZZZZZAAAAAB
service_account_file = /home/test/rclone.json
team_drive = 0A0B0C0D0E0F0G0H0I0

[GSuiteTest]
type = drive
service_account_file = /home/test/rclone.json
team_drive = 0A0B0C0D0E0F0G0H0I0

**Comment by arcticlinux** [comment]
I got it to work, you have to use --drive-impersonate for it to work.

**Comment by dav1303** [comment]
Hi guys

The issue on my side was link to the Access conf on Team Drive.

In fact i'll try tout configure and give an Access tout a Team Drive where the user is not included as Team Drive Owner

That's why i have got this error 500

Regards

**Comment by animosity22** [comment]
Permissions error on the user side. Closing out.
