### ISSUE TITLE
Double space in remote file path causes error

### ISSUE THREAD

**Issue by yannos** [rclone/rclone#3004]
#### Output of `rclone version`
rclone v1.36 on Ubuntu 18.04

#### Describe the issue

When attempting to copy a remote folder to local, if a subdirectory in the remote folder has a double space in it, it causes an error and the copy fails.

The error message reports the directory with the double space changed to a forward slash and space.

For example, if the remote dir is path/double  space

Then `rclone copy remote:/ local:/`

will fail with:
 
> 2019/02/01 11:27:00 Failed to copy: error reading source directory "path/double/ space": directory not found

Note path/double  space is reported as path/double/ space in the error message

**Comment by ncw** [comment]
Which backend are you using?

Can you try with a more recent verson of rclone - see [the latest release](https://rclone.org/downloads/).

**Comment by yannos** [comment]
Google Drive

**Comment by ncw** [comment]
Did a newer rclone give the same problem?

**Comment by animosity22** [comment]
This looks to be stale. If you still have a question, please just ask on the forums and we can help out.
