### ISSUE TITLE
Minimal Arm Build

### ISSUE THREAD

**Issue by scj643** [rclone/rclone#3005]
A minimal version of rclone that has a smaller binary size should be made for embedded devices.

For example home routers running OpenWRT where the storage is lacking.

**Comment by ncw** [comment]
It is quite easy to build custom rclone's...

What you do is instead of importing all the backends and commands here, you just import the ones you want.

https://github.com/ncw/rclone/blob/4fddec113cdd9994d93fa8b993024e4e7c8d7d00/rclone.go#L7-L9

Which do you think rclone should include?

**Comment by scj643** [comment]
Google Drive, Dropbox, and OneDrive. Also maybe ftp and sftp. The logic behind this is that rclone would be used for streaming backups to these remotes.

**Comment by ncw** [comment]
> Google Drive, Dropbox, and OneDrive. Also maybe ftp and sftp. The logic behind this is that rclone would be used for streaming backups to these remotes.

And which commands?  `sync`, `copy` etc?

**Comment by scj643** [comment]
I would think sync, copy, and mount (OpenWRT has it's own fuse utils)

**Comment by calisro** [comment]
Does GO have the ability to strip the binaries and potentially compress? Might that reduce the size enough (if that isn't already being done) for embedded devices (although compression might marginally increase CPU usage?)

**Comment by ncw** [comment]
> Does GO have the ability to strip the binaries and potentially compress? Might that reduce the size enough (if that isn't already being done) for embedded devices (although compression might marginally increase CPU usage?)

I do strip the release binaries with the `-s` flag using `go build -ldflags="-s"`

Here is an article about [making go binaries smaller](https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/).

I did a little test - the `rclone -s` is the normal release binary.  It rusns out that adding `-w` does nothing extra.  Using `upx -9` compresses the binary a lot though to 9.4M

```
-rwxrwxr-x 1 ncw ncw 39945012 Mar  1 14:02 rclone-normal
-rwxrwxr-x 1 ncw ncw 33620788 Mar  1 14:03 rclone-w
-rwxrwxr-x 1 ncw ncw 29646400 Mar  1 14:03 rclone-s
-rwxrwxr-x 1 ncw ncw 29646400 Mar  1 14:02 rclone-s-w
-rwxrwxr-x 1 ncw ncw  9465920 Mar  1 14:03 rclone-s-upx
```

Note that UPX-ing stuff uses more RAM when it runs - a modern OS pages only the bits of the binary in use into memory, whereas UPX has to get it all into memory to decompress it.

```
$ memusage rclone-s
  PID   RSS    VSZ CMD
24832 23860 589352 ./rclone-s rcd
```

vs

```
$ memusage rclone-s-upx
  PID   RSS    VSZ CMD
24926 34104 589736 ./rclone-s-upx rcd
```

Note the increased RSS which the OS can't page out since it isn't backed by a file.

I made a cutdown rclone with a limited selection of backends and commands which about halves the binary size.

```
-rwxrwxr-x  1 ncw ncw 21959833 Mar  1 14:16 rclone-cutdown-normal
-rwxrwxr-x  1 ncw ncw 16234336 Mar  1 14:16 rclone-cutdown-s
-rwxrwxr-x  1 ncw ncw  5648288 Mar  1 14:16 rclone-cutdown-s-upx
```

I did this by changing `rclone.go` in the root to look like this

```go
// Sync files and directories to and from local and remote object stores
//
// Nick Craig-Wood <nick@craig-wood.com>
package main

import (
	// Active file systems
	_ "github.com/ncw/rclone/backend/drive"
	_ "github.com/ncw/rclone/backend/dropbox"
	_ "github.com/ncw/rclone/backend/ftp"
	_ "github.com/ncw/rclone/backend/onedrive"
	_ "github.com/ncw/rclone/backend/sftp"

	// Active commands
	_ "github.com/ncw/rclone/cmd/copy"
	_ "github.com/ncw/rclone/cmd/copyto"
	_ "github.com/ncw/rclone/cmd/mount"
	_ "github.com/ncw/rclone/cmd/move"
	_ "github.com/ncw/rclone/cmd/moveto"
	_ "github.com/ncw/rclone/cmd/rcat"
	_ "github.com/ncw/rclone/cmd/sync"
)

import (
	"github.com/ncw/rclone/cmd"
)

func main() {
	cmd.Main()
}
```

**Comment by scj643** [comment]
`free`
```
             total       used       free     shared    buffers     cached
Mem:        511928     109232     402696      33812       2112      53892
-/+ buffers/cache:      53228     458700
```

`df -h`
```
Filesystem                Size      Used Available Use% Mounted on
/dev/root                 2.3M      2.3M         0 100% /rom
tmpfs                   250.0M     33.0M    216.9M  13% /tmp
/dev/ubi0_1              24.0M      9.0M     13.7M  40% /overlay
overlayfs:/overlay       24.0M      9.0M     13.7M  40% /
ubi1:syscfg              29.6M    268.0K     27.8M   1% /tmp/syscfg
tmpfs                   512.0K         0    512.0K   0% /dev
```

Overlay is where the package would get installed.

**Comment by scj643** [comment]
The router I'm using right now is a 	Linksys WRT1900ACS

**Comment by ncw** [comment]
OK try this which is an complete ARM build, run through `upx -9`.  The executable is just under 8M. so will fit in your `/overlay`.

```
GOARCH=arm GOARM=7 go build -v -ldflags "-s"
mv rclone rclone-v1.46.0-054-g1692c6bd-beta-arm
upx -9 rclone-v1.46.0-054-g1692c6bd-beta-arm
```

I had to .gz it to attach it here.


[rclone-v1.46.0-054-g1692c6bd-beta-arm.gz](https://github.com/ncw/rclone/files/2931676/rclone-v1.46.0-054-g1692c6bd-beta-arm.gz)

**Comment by seuffert** [comment]
> `free`
> 
> ```
>              total       used       free     shared    buffers     cached
> Mem:        511928     109232     402696      33812       2112      53892
> -/+ buffers/cache:      53228     458700
> ```
> 
> `df -h`
> 
> ```
> Filesystem                Size      Used Available Use% Mounted on
> /dev/root                 2.3M      2.3M         0 100% /rom
> tmpfs                   250.0M     33.0M    216.9M  13% /tmp
> /dev/ubi0_1              24.0M      9.0M     13.7M  40% /overlay
> overlayfs:/overlay       24.0M      9.0M     13.7M  40% /
> ubi1:syscfg              29.6M    268.0K     27.8M   1% /tmp/syscfg
> tmpfs                   512.0K         0    512.0K   0% /dev
> ```
> 
> Overlay is where the package would get installed.

i have a simple usb flash drive (ext4) for this plugged into my router => plenty of storage. no need for extra compression

**Comment by ncw** [comment]
This issue gives instructions on how to make a minimal build.

I don't want to make that part of the rclone release process as I think it is too specialized.
