### ISSUE TITLE
Further Save as/new Problems with Libreoffice

### ISSUE THREAD

**Issue by cyberpunkbln** [rclone/rclone#3006]
#### What is the problem you are having with rclone?
Hi,
i think it gives some little problems with libreoffice save as / save new mechanism. All other save as/mechanism funtioned. firefox, notepad++ and so on. But i think libreoffices cache/temp system is a problem.

#### What is your rclone version (output from `rclone version`)
1.46

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Win 10 / 64 Bit
WinFSP

####  Which cloud storage system are you using? (eg Google Drive)
local

[https://privatebin.net/?240c63f4f34e7c32#KTNMn/lHsjIrN8WDLlViq2p/Rv47XSp4VKcCorBuSwk=](https://privatebin.net/?240c63f4f34e7c32#KTNMn/lHsjIrN8WDLlViq2p/Rv47XSp4VKcCorBuSwk=)

thx

**Comment by ncw** [comment]
Can you describe what you are doing with libreoffice? And what the errors are?

This appears to be the problem, which looks like the `.TMP` file was deleted before the download was completed.

```
2019/02/21 17:51:17 INFO  : Documents/Dokumente/Vorlage2.odt: Deleted
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP: Getattr: fh=0x4
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP: >Getattr: errc=0
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP: Unlink: 
2019/02/21 17:51:17 INFO  : Documents/Dokumente/lu75885cd3ot.tmp: Moved (server side)
2019/02/21 17:51:17 DEBUG : Documents/Dokumente/lu75885cd3ot.tmp: Updating file with Documents/Dokumente/Vorlage2.odt 0xc00007c460
2019/02/21 17:51:17 DEBUG : Documents/Dokumente/lu75885cd3ot.tmp(0xc0001fa360): >close: err=<nil>
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/lu75885cd3ot.tmp: >Release: errc=0
2019/02/21 17:51:17 INFO  : Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP: Deleted
2019/02/21 17:51:17 INFO  : Documents/Dokumente/Vorlage2.odt: Moved (server side)
2019/02/21 17:51:17 DEBUG : Documents/Dokumente/Vorlage2.odt: Updating file with Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP 0xc00007cf00
2019/02/21 17:51:17 DEBUG : Documents/Dokumente/Vorlage2.odt(0xc0001fa300): >close: err=<nil>
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/Vorlage2.odt: >Release: errc=0
2019/02/21 17:51:17 ERROR : Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP: Failed to copy: chtimes \\?\d:\EncVolumes\Rclone\Local\oksve7tm9vmffe1ojshhgmn5go\2d8sk1ols2rborjoomo6tqm19s\kj9uc3p88bcg55eits1aptdr28\4kuid5j7q5bq4ffjscf77brj54\li9umnjfu5cudjsel3pard90g70oce5qrqtngbkt3qtc30f1oeq0: Das System kann die angegebene Datei nicht finden.
2019/02/21 17:51:17 ERROR : Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP(0xc0000c28a0): failed to transfer file from cache to remote: chtimes \\?\d:\EncVolumes\Rclone\Local\oksve7tm9vmffe1ojshhgmn5go\2d8sk1ols2rborjoomo6tqm19s\kj9uc3p88bcg55eits1aptdr28\4kuid5j7q5bq4ffjscf77brj54\li9umnjfu5cudjsel3pard90g70oce5qrqtngbkt3qtc30f1oeq0: Das System kann die angegebene Datei nicht finden.
2019/02/21 17:51:17 INFO  : Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP: Removed from cache
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP: >Unlink: errc=0
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP: Flush: fh=0x4
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP: >Flush: errc=0
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP: Release: fh=0x4
2019/02/21 17:51:17 DEBUG : Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP(0xc00012cba0): RWFileHandle.Release closing
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/Vorlage2.odt: Getattr: fh=0xFFFFFFFFFFFFFFFF
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/Vorlage2.odt: >Getattr: errc=0
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/Vorlage2.odt: Getattr: fh=0xFFFFFFFFFFFFFFFF
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/Vorlage2.odt: >Getattr: errc=0
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/Vorlage2.odt: Open: flags=0x0
2019/02/21 17:51:17 DEBUG : Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP(0xc00012cba0): close: 
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/Vorlage2.odt: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2019/02/21 17:51:17 DEBUG : Documents/Dokumente/Vorlage2.odt: Open: flags=O_RDONLY
2019/02/21 17:51:17 DEBUG : Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP(0xc0000c28a0): >close: err=failed to transfer file from cache to remote: chtimes \\?\d:\EncVolumes\Rclone\Local\oksve7tm9vmffe1ojshhgmn5go\2d8sk1ols2rborjoomo6tqm19s\kj9uc3p88bcg55eits1aptdr28\4kuid5j7q5bq4ffjscf77brj54\li9umnjfu5cudjsel3pard90g70oce5qrqtngbkt3qtc30f1oeq0: Das System kann die angegebene Datei nicht finden.
2019/02/21 17:51:17 ERROR : Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP(0xc0000c28a0): RWFileHandle.Release error: failed to transfer file from cache to remote: chtimes \\?\d:\EncVolumes\Rclone\Local\oksve7tm9vmffe1ojshhgmn5go\2d8sk1ols2rborjoomo6tqm19s\kj9uc3p88bcg55eits1aptdr28\4kuid5j7q5bq4ffjscf77brj54\li9umnjfu5cudjsel3pard90g70oce5qrqtngbkt3qtc30f1oeq0: Das System kann die angegebene Datei nicht finden.
2019/02/21 17:51:17 DEBUG : Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP(0xc00012cba0): >close: err=<nil>
2019/02/21 17:51:17 DEBUG : /Documents/Dokumente/Vorlage2.odt~RF13423b67.TMP: >Release: errc=0
2019/02/21 17:51:17 ERROR : IO error: failed to transfer file from cache to remote: chtimes \\?\d:\EncVolumes\Rclone\Local\oksve7tm9vmffe1ojshhgmn5go\2d8sk1ols2rborjoomo6tqm19s\kj9uc3p88bcg55eits1aptdr28\4kuid5j7q5bq4ffjscf77brj54\li9umnjfu5cudjsel3pard90g70oce5qrqtngbkt3qtc30f1oeq0: Das System kann die angegebene Datei nicht finden.
```

**Comment by cyberpunkbln** [comment]
@ncw 
Hello, less time at the moment.

When i open an document in libreoffice and save above the document with save, all functioned. The error only appears when i open an new document and will save this new and when i want to save a copy from an opened document as save as or copy save.

Hmmm Firefox and others like Notepad++ and atom functioned very well. Firefox is the only one that uses an cache-system with .part files and functioned.

Can it be that the ~ sign is the problem? Cached but don't readable or rclone think it is deleted why he cannot read a file under windows with ~ in the filename?

Only an idea, why the cache system under firefox functioned well and save new files in software that don't use a cache system functioned very well, too.

PS: Cryptomator with dokan functioned in this case in libreoffice.

**Comment by ncw** [comment]
I haven't managed to replicate this.

I tried
- Windows 7
- rclone [the latest beta](https://beta.rclone.org)
- drive backend and local backend
- loading a document into libreoffice
- trying "Save As" to the mounted drive

Can you have a go with [the latest beta](https://beta.rclone.org) and see if you can still replicate it?

If you can can you state
- which backend you are using?
- are you using crypt?

Can you paste another log file with `-vv` too - thanks.

**Comment by cyberpunkbln** [comment]
Hello,
so i use the latest beta.

libreoffice - open - save as
libreoffice - new - save

allright the same issue, i can save now without  an error and the file will be shown correct in the explorer with correct size. But when i close libreoffice and try to open libreoffice says that is a corrupted file.

And when i try to delete and then make an refresh in the explorer, the files appears new and i cannot delete the files.

[https://privatebin.net/?ef8140d3475386ff#ZlS7lKUUVq1uhsTc02XjfPY+my6vlzxeJ+WIrFJoQR4=](https://privatebin.net/?ef8140d3475386ff#ZlS7lKUUVq1uhsTc02XjfPY+my6vlzxeJ+WIrFJoQR4=)

**Comment by cyberpunkbln** [comment]
@ncw 
Hello, the failure only comes when i use and crypted Remote and vfs-cache full. When i use an Local Remote and vfs-cache full, libreoffice new-saveas functioned, but when is use remote local the vfs-cache full is obsolte why it use no vfs-cache at saveas-actions.

**Comment by ncw** [comment]
> @ncw
> Hello, the failure only comes when i use and crypted Remote and vfs-cache full. When i use an Local Remote and vfs-cache full, libreoffice new-saveas functioned.

I managed to make it go wrong once, but unfortunately I didn't capture a log.  I can't seem to make it go wrong again :-(

Does it go wrong every time for you?

Can you send me another log with a screen shot of the error that libreoffice gives you?

Your old logs have expired, alas

**Comment by cyberpunkbln** [comment]
Hello,
sorry for my late reply. Here my new test with 1.47 and encrypted local.

[https://privatebin.net/?876fe96f5c7c85a1#+XWuONu+Sj3C7cMmd5bSY3xZJGBlGiPWwTPhw3I9ckk=](https://privatebin.net/?876fe96f5c7c85a1#+XWuONu+Sj3C7cMmd5bSY3xZJGBlGiPWwTPhw3I9ckk=)

0.odt is a explorer right click new linbreoffice document
1.odt ist full 0.odt with text and save as 1.odt
2.odt is a file->new doc->ctrl+n, fills with text and then save (not save as) as 2.odt

encrypted local volume with 1024 bit pw and 1024 bit salt
all others in the log-file

thx

**Comment by cyberpunkbln** [comment]
@ncw In the last releases the Problem is still present. And now i can say it's not only a problem from Libreoffice. All programs that fill an container (zip as an example) or file (libreoffice as an example) that uses her own caching system. Libreoffice is the best example for that, with her own caching system. But only when i use crypt and vfs-cache=minimal/writes/full.

Windows 10 Notepad functioned very well, because he uses no own cache-system.

Cryptomator and Dokan has not this problem.

**Comment by timtoo** [comment]
I think this may be the same problem? This is just trying to zip a small xml file into a OneDrive mounted folder. Here are logs: [rclone-vv--debug-fuse.txt](https://github.com/rclone/rclone/files/4048725/rclone-verbose-fuse-debug.txt), [strace.log](https://github.com/rclone/rclone/files/4048726/strace1.log)

rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.4

type=onedrive
drive_type = personal
vfs_cache_mode = writes
buffer_size = 128M
vfs_cache_max_size = 5G

Command from within a mounted OneDrive folder:

$ zip rclone_onedrive_test.zip ~/*.xml
  adding: home/x/starport-scan1.xml
zip I/O error: Illegal seek
zip error: Input file read failure (was zipping home/x/starport-scan1.xml)

**Comment by timtoo** [comment]
Tried the same zip test on a google drive and a local mount with all defaults (no configuration other than the auth tokens for google) and it has the same result.

**Comment by ncw** [comment]
@timtoo the error in your log is this

> 2020/01/10 19:15:11 ERROR : tmp/zi0gpOHy: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes


If you follow the advice in the log message and add `--vfs-cache-mode writes` then hopefully it will work.

**Comment by timtoo** [comment]
@ncw that makes sense. I hadn't thought of that for my second two quick tests. I had assumed in my first test I did have effectively have `--vfs-cache-mode writes` via the rclone.conf, as seen in previous snippet. 

Is including `vfs_cache_mode = writes` in rclone.conf not correct? Adding `--vfs-cache-max-size writes` on command line does work, as you patiently suggested, but when I add it to rclone.conf, in the format that the rclone.conf seems to use, it does not work. I suspect now that my rclone.conf is not right. 

Sorry for the confusion.

**Comment by ncw** [comment]
> Is including `vfs_cache_mode = writes` in rclone.conf not correct?

Unfortunately this only works on the command line at the moment (or via environment variable).

**Comment by ivandeex** [comment]
@cyberpunkbln 
This bug is reported against an obsolete version of rclone. Can you reproduce it with rclone 1.54?
