### ISSUE TITLE
Handle requester pay for s3

### ISSUE THREAD

**Issue by ryanlayer** [rclone/rclone#301]
It seems that this may be as easy as including the correct header on the requests.

**Comment by ncw** [comment]
I keep meaning to add a flag to allow people to add headers...

What would the header need to be?

**Comment by ryanlayer** [comment]
x-amz-request-payer:requester

On Tue, Jan 19, 2016 at 3:31 PM, Nick Craig-Wood <notifications@github.com>
wrote:

> I keep meaning to add a flag to allow people to add headers...
>
> What would the header need to be?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncw/rclone/issues/301#issuecomment-173009152>.
>



-- 
Ryan Layer

**Comment by ryanlayer** [comment]
Here is more from amazon:

http://docs.aws.amazon.com/AmazonS3/latest/dev/ObjectsinRequesterPaysBuckets.html
<http://www.google.com/url?q=http%3A%2F%2Fdocs.aws.amazon.com%2FAmazonS3%2Flatest%2Fdev%2FObjectsinRequesterPaysBuckets.html&sa=D&sntz=1&usg=AFQjCNG0ywhWK-L5CupbkyzxJKHWwgmFmg>

On Tue, Jan 19, 2016 at 3:33 PM, Ryan Layer <ryan.layer@gmail.com> wrote:

> x-amz-request-payer:requester
>
> On Tue, Jan 19, 2016 at 3:31 PM, Nick Craig-Wood <notifications@github.com
> > wrote:
>
>> I keep meaning to add a flag to allow people to add headers...
>>
>> What would the header need to be?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ncw/rclone/issues/301#issuecomment-173009152>.
>>
>
>
>
> --
> Ryan Layer
>



-- 
Ryan Layer

**Comment by ncw** [comment]
This looks relatively simple to add to the [Get](https://godoc.org/github.com/aws/aws-sdk-go/service/s3#GetObjectInput) and [Put](https://godoc.org/github.com/aws/aws-sdk-go/service/s3#PutObjectInput) code just setting the `RequestPayer` attribute to `requester`.

It could be controlled by a flag `--s3-requester-pay`

Any takers?

**Comment by ryanlayer** [comment]
Yes please!

On Wed, Jan 20, 2016 at 10:03 AM, Nick Craig-Wood <notifications@github.com>
wrote:

> This looks relatively simple to add to the Get
> <https://godoc.org/github.com/aws/aws-sdk-go/service/s3#GetObjectInput>
> and Put
> <https://godoc.org/github.com/aws/aws-sdk-go/service/s3#PutObjectInput>
> code just setting the RequestPayer attribute to requester.
>
> It could be controlled by a flag --s3-requester-pay
>
> Any takers?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ncw/rclone/issues/301#issuecomment-173275092>.
>



-- 
Ryan Layer

**Comment by rlaunch** [comment]
Tried using the following argument `--header "x-amz-request-payer:requester"` but had this error:
`ERROR : : error reading source directory: AccessDenied: There were headers present in the request which were not signed`

**Comment by ncw** [comment]
@rlaunch - you'll need a space, and you want to use --header-upload or --header-download depending on whether you are uploading or downloading.

    --header-upload "x-amz-request-payer: requester"

or

    --header-download "x-amz-request-payer: requester"

If that doesn't work can you run with `-vv --dump headers` and paste some debug.

**Comment by ncw** [comment]
I've merged @kelvk 's fix for this this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54 - thank you!
