### ISSUE TITLE
Copy URL for multiple files

### ISSUE THREAD

**Issue by brxie** [rclone/rclone#3013]
#### What is the problem you are having with rclone?
Thank you for developing an awesome tool!

I have a question referring to the Rclone daemon.
I'm unable to execute `/operations/copyurl` job for multiple URL's.

Is there a way to copy multiple files in a single request?

#### What is your rclone version (output from `rclone version`)

rclone v1.46
- os/arch: linux/amd64
- go version: go1.11.5

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04.5 LTS

####  Which cloud storage system are you using? (eg Google Drive)
S3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`POST operations/copyurl`
```
{
    "url": [
        "http://humanstxt.org/humans.txt",
        "https://norvig.com/big.txt"
    ],
    "fs": "ONE_DATA:multi_copy2",
    "remote": [
        "humans3.txt",
        "big1.txt"
    ]
}
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
{
	"error": "expecting string value for key \"remote\" (was []interface {})",
	"input": {
		"fs": "ONE_DATA:multi_copy2",
		"remote": [
			"humans3.txt",
			"big1.txt"
		],
		"url": [
			"http://humanstxt.org/humans.txt",
			"https://norvig.com/big.txt"
		]
	},
	"path": "operations/copyurl",
	"status": 400
}

```

**Comment by ncw** [comment]
Apologies for the delay in answering!

You will have to do one request to the rc per copyurl.
