### ISSUE TITLE
the mode of file and dir on local driver doesn't been synced

### ISSUE THREAD

**Issue by ssrs100** [rclone/rclone#3016]
#### What is the problem you are having with rclone?

file or dir mode not the same with source after doing rclone

linux system umask is 0000

#### What is your rclone version (output from `rclone version`)

latest

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

64

####  Which cloud storage system are you using? (eg Google Drive)

sas

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy 1.txt tmp

**Comment by ncw** [comment]
Rclone does not attempt to preserve permissions at the moment.

It is possible to use getfacl/setfacl to list and back up the permissions
