### ISSUE TITLE
Large file uploads to B2 fail to resume after interruption

### ISSUE THREAD

**Issue by tristanbrown** [rclone/rclone#3019]
Rclone fails to resume large file uploads that have been partially completed. The first run below completed uploading a 100.7 MB part of each file. Using the B2 web interface or CLI, I can see the "Started large file" with an "Uploaded Parts Size" of 100.7 MB. When I try to resume the upload using rclone, it starts from 0%, and creates a completely new "Started large file," ignoring the one that's already there. This is a crypt remote, if it matters. 

I've also tested this using the B2 CLI, and the `b2 sync` script does properly resume large file uploads. 
```
PS E:\Tristan> rclone sync F:/School trbarch:School -P --fast-list
Transferred:      978.401M / 9.038 GBytes, 11%, 702.027 kBytes/s, ETA 3h21m11s                                  Errors:                 0
Checks:                 0 / 0, -
Transferred:          586 / 10598, 6%
Elapsed time:    23m47.1s
Transferring:
* Research/Lab Notebook .eBook_P450sProject.pdf: 20% /796.468M, 156.161k/s, 1h8m48s 
* Research/Lab Notebook .k_AminationProject.pdf: 63% /287.863M, 154.048k/s, 11m45s
* Research/Lab Notebook .k_BerryGroup-TRB-I.pdf: 22% /752.495M, 150.385k/s, 1h6m24s
* Research/Lab Notebook .tebook_ArnoldGroup.pdf: 16% /1.059G, 162.879k/s, 1h34m53s
Terminate batch job (Y/N)? y

PS E:\Tristan> rclone sync 'F:\School\Research\Lab Notebook Images' 'trbarch:School/Research/Lab Notebook Images' -P --fast-list --transfers 1
Transferred:        4.637M / 4.999 GBytes, 0%, 407.210 kBytes/s, ETA 3h34m21s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 402, 0%
Elapsed time:       11.6s
Transferring:
 *  LabNoteBook_P450sProject.pdf:  0% /796.468M, 443.960k/s, 30m26s
Terminate batch job (Y/N)? y 
```

**Comment by ncw** [comment]
If you stop and start rclone then it won't resume the transfer, you are correct.

There are some issue about this here, eg #87 

Rclone will do everything in its power to upload your file if you don't stop it though, including reconnecting to the source and retrying segments.

**Comment by tristanbrown** [comment]
I see a lot of comments at #87 requesting this feature for Google Drive where it's not ordinarily supported...but B2 already supports this natively through their CLI. Would it be as difficult to implement here? 
I like the way rclone handles encryption, so that's why I'm using this instead of `b2 sync`. But the inability to resume large uploads makes my archiving task require a lot more babysitting than I'd like.

**Comment by ncw** [comment]
What needs to happen is that rclone keeps a record of large files it is uploading, something like this
- source fs
- destination fs
- name of local file
- timestamp of local file
- size of local file
- upload ID
- time transfer started

Then when it restarts it can read that file and restart the upload.  It isn't trivial alas!

**Comment by tristanbrown** [comment]
B2 already seems to have a way to query incomplete large file parts, and it still seems to put these "started large file" entries in the same version history chain. Shouldn't this make it possible for rclone to reconstruct that history each time the upload is triggered?

**Comment by ncw** [comment]
> B2 already seems to have a way to query incomplete large file parts, and it still seems to put these "started large file" entries in the same version history chain. Shouldn't this make it possible for rclone to reconstruct that history each time the upload is triggered?

Rclone really needs to know that the local file hasn't changed between runs so I think some local storage is essential.

**Comment by ncw** [comment]
There are plans afoot to implemenent this, but I'll use #87 to track.
