### ISSUE TITLE
No output from "df"

### ISSUE THREAD

**Issue by rolfn** [rclone/rclone#3021]
#### What is the problem you are having with rclone?

I don't see my successful mounted webdav store (gmx email provider) with "df" under Linux.

#### What is your rclone version (output from `rclone version`)

rclone v1.46.0-012-g78a30bd5-fix-2964-webdav-beta
- os/arch: linux/amd64
- go version: go1.11.5

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

x86_64 GNU/Linux (openSUSE Tumbleweed)

####  Which cloud storage system are you using? (eg Google Drive)

webdav

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

/usr/bin/rclone --vfs-cache-mode writes mount RolfsGMX: /home/nieprasc/gmx \
--config /home/nieprasc/.config/rclone/rclone.conf
   
Thanks for the excellent  software!

...Rolf

**Comment by ncw** [comment]
> I don't see my successful mounted webdav store (gmx email provider) with "df" under Linux.

It should appear like this.  Can you see it in `/proc/mounts` ?

```
Filesystem                    Size  Used Avail Use% Mounted on
drive:test                     17G  7.6G  1.9G  81% /mnt/tmp
```

What do you get if you type `df /home/nieprasc/gmx` - does that work?

And what does `rclone about RolfsGMX:` output?

**Comment by rolfn** [comment]
With
```
cat /proc/mounts
```
I get
```
RolfsGMX: /home/nieprasc/gmx fuse.rclone rw,nosuid,nodev,relatime,user_id=1000,group_id=100 0 0
```

**Comment by ncw** [comment]
Does it show up with 'df -a' ?

If it does then it is df deciding it is a dummy file system for some reason.

**Comment by rolfn** [comment]
`LANG=c df -a` works:
```
Filesystem                     1K-blocks       Used     Available Use% Mounted on
...
RolfsGMX:                              0          0 1099511627776   0% /home/nieprasc/gmx
```

**Comment by ncw** [comment]
> `LANG=c df -a` works:
> 
> ```
> Filesystem                     1K-blocks       Used     Available Use% Mounted on
> ...
> RolfsGMX:                              0          0 1099511627776   0% /home/nieprasc/gmx
> ```

I can only assume this is a bug or feature of `df` when it sees the 1PB file system with 0 bytes used.

**Comment by animosity22** [comment]
This looks to be answered. If you have a new question, you can just ask on the forums and we can help out.
