### ISSUE TITLE
 Failed to copy: can't copy - source file is being updated (mod time changed from 2018-07-03 15:14:11.819130985 -0400 EDT to 2018-07-03 15:14:11.821105924 -0400 EDT)

### ISSUE THREAD

**Issue by MohanaPriyaNarapareddy** [rclone/rclone#3029]

**Comment by ncw** [comment]
Are you using glusterfs maybe?  This doesn't have completely consistent local timestamps.

You can use this to fix

      --local-no-check-updated           Don't check to see if the files change during upload

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.

**Comment by crisanto-cc** [comment]
Solucionado, Gracias

**Comment by Dryrtan** [comment]
Solved my problem, thanks
