### ISSUE TITLE
Ability to spread the files over several providers to get more storage

### ISSUE THREAD

**Issue by ariselseng** [rclone/rclone#303]
Hi,
I am not sure if this ever would be inside the scope of rclone. 
But it would be awesome if had a local cache of all files and where they were stored and the ability to spread it out over multiple configs/providers. This would be handy for people that were using more than 10TB.

**Comment by ncw** [comment]
Interesting idea!  Probably beyond the scope of rclone, but maybe one day!

**Comment by cowai** [comment]
It could handled simple round-robin and on fail, try of the other provided storage options.
```shell
 $ rclone unsafesync /giantpool/ hubic1:/giantpool-part,hubic2:/giantpool-part --i-know-this-is-dangerous

**Comment by calisro** [comment]
There are a lot of union filesystems that can do this.  Perhaps use that in hte meantime.

**Comment by ivandeex** [comment]
This is now possible with https://rclone.org/union

I suggest closing this issue.

**Comment by ncw** [comment]
I agree - I'll close this now :-)

**Comment by ivandeex** [comment]
Housekeeping is fun 😸
