### ISSUE TITLE
Allow serving multiple protocols (eg. http and ftp)

### ISSUE THREAD

**Issue by calind** [rclone/rclone#3031]
#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.46
- os/arch: darwin/amd64
- go version: go1.11.5
```

#### What problem are you are trying to solve?
I'm trying to serve a bucket over http while allowing it to be changed trough ftp. It would be great if one instance of rclone could serve both, so that it shares the cache and reduce the API calls.

#### How do you think rclone should be changed to solve that?
Start each server in a goroutine.

**Comment by ncw** [comment]
This is more a problem with how to arrange the command lines than anything else...

Both ftp and http have lots of options and they aren't all the same.

How would you suggest that would work?

**Comment by calisro** [comment]
You may be able to use sslh to multiplex if you really want to.  I've done this with tinc and openvpn before for specific reasons.

**Comment by ivandeex** [comment]
Closing after 2 years of inactivity
