### ISSUE TITLE
Additional Writing to Duplicate Files

### ISSUE THREAD

**Issue by y1026** [rclone/rclone#3037]
Hi.

If the copy command is used, the same filename will be overwritten if it exists.

Is there a way to add without overwriting?

For example, ">>" in the Linux redirection.

Thanks.

**Comment by ncw** [comment]
You are asking for appending to a file.

I can't think of any backends that would support this in their API.  Certainly this isn't supported by s3, azureblob, gcs, google drive, swift, b2 - I haven't searched the other APIs.

So the answer is no, you can't add to a file - sorry!

You'll need to download the file, append to it locally, then upload it again, or just upload the difference and combine them when you download.
