### ISSUE TITLE
Max Buffer Size

### ISSUE THREAD

**Issue by ayaremrah** [rclone/rclone#3049]
Max buffer size should be set for every rclone instance if buffer-size is set.
For example if buffer-size is set to 100MB and max-buffer-size is set to 1000MB, rclone should not allocate more then 1000MB memory no matter how many files it open. if a new file requests its own allocation when max-buffer-size is reached, rclone may release previous allocated memory based on LIFO or less demanding file allocation first.

**Comment by ncw** [comment]
When rclone reaches the buffer limit, what do you think it should do

1. block and wait for memory usage
2. allocate transfers with no buffers (as if you had written `--buffer-size 0`)

Releasing in use buffers is probably too hard.

What do you think?

**Comment by ayaremrah** [comment]
that's right, releasing in use buffer is hard and it can cause mulfunctions. 
1. Blocking may not be good for some applications but it could be added as a parameter for anyone needing it.
2. This could be the best option i think. To add, if buffer limit is reached then cache the chunks to disk as again for a set max cache size. Disk cache size maybe managed as it is in the current cache logic.if all is maxed out then allocate with no buffers.

these are my cents. if it is not doable then what you suggest in 2 would be enough i think.

**Comment by animosity22** [comment]
If you wanted to cache things to disk if memory got too high, you could always have a larger swap file to handle it on the system. 

In reality, the buffer size should be set to the maximum files open per file and having a large buffer really doesn't add much value to be honest as if it's closed, the buffer is dumped anyway.

Depending on what you use, it may double cache on the OS as well so it really depends on what the goal is.

**Comment by ayaremrah** [comment]
it's right for standalone applications. But for this case, you are putting rclone between OS and the application, so for the application you use, rclone takes place of the OS to manage the memory and cache.

**Comment by animosity22** [comment]
That's where having a properly configured system and rclone comes in though.

Much of the issue is already mitigated by having a properly sized instance of rclone and buffer size.

It's really no different than configuring a database or any other application to exhaust the system. If done improperly, you run out of memory.

What application are you using that is opening so many files that is creating your actual issue?

**Comment by ayaremrah** [comment]
it's a bittorrent client which is normal to open too many files. Without memory-buffer, when fetching chunks it's useless with rclone. But when memory-buffer is set it works wonders for a cloud mounted drive. if memory buffer of rclone can be handled with good options, it will make random reads better and more efficient(p2p wise). it's already doing this efficiently when buffer is set but we should also set a limit for the total memory not to encounter any kind of crashes.

**Comment by animosity22** [comment]
Have you tried the cache backend? I would think that might handle the P2P traffic better but in general, I think a cloud mount is a very bad use case for torrenting as their pattern is really all over the board.

**Comment by ayaremrah** [comment]
i tried every possible settings with rclone and i ended up using only vfs chunk reading and memory buffer to be the most efficient. Btw it's only for seeding. i get 10-20 MB/s upload speeds with google drive with this setting. i could not get over 1 MB/s with any other config.

**Comment by ayaremrah** [comment]
i also use this setting with a bigger chunk size for plex streming.

**Comment by animosity22** [comment]
I think it would heavily depend on how the peers were seeing and if they were doing a lot of sequential reads or not.

I would think the cache backend and you could use the "--cache-chunk-no-memory' option and a smaller 32M chunk size and let local storage manage the disk pool to seed out and cap it that way as you'd have a 0 buffer-size with the cache backend anyway.

I'd keep a separate mount for Plex streaming and just use the default VFS backend.

Personally, I just use a 6TB local disk for all my seeding and such as it's just much more efficient for my setup/use case.

**Comment by ayaremrah** [comment]
i think it's all about the 100 ms delaying between the API calls. Most of the time when a torrent client requests a chunk, possible future chunks are either behind or in front of the current chunk. So when you set a vfs read chunk size, say, 16 MB then you already have it in memory for the next operations. This makes it the most efficient for seeding i think.  p2p clients favor the fastest peers. With cache backend it did not work somehow. Maybe it's because the natural latency with the cache backend.

**Comment by animosity22** [comment]
vfs-read-chunk-size is what chunk size it requests from the backend and doesn't store any of that in memory.

buffer-size is what is stored in memory and is dropped when a file is closed.

There is a good write up on the vfs read chunk size -> 

https://forum.rclone.org/t/new-feature-vfs-read-chunk-size/5683

**Comment by ivandeex** [comment]
This ticket is almost 2 years stale. CLosing
