### ISSUE TITLE
offline cache (index) backend

### ISSUE THREAD

**Issue by saviodsouza** [rclone/rclone#3060]
#### Output of `rclone version`

1.46

#### Describe the issue

I need only a index cache without expire to use with union remote like

I first backup my data to minio I want to keep this offline so I need a index to keep online.
When I create a union remote

Minio(offline)-------->index(rw)-------->union(rw):

So the new offline cache backend has to have options

Name : offlinemyminio
Offline remote: myminio:
Offline cache: $home/.config/rclone/myminio.db

Rclone lsd offlinemyminio:
The above command should query home/user/.config/rclone/myminio.db & list myminio: buckets here with size, etc

There should be a way to update the index
Rclone offlinemyminio:  reindex
The above command should hit myminio: and update the index with file size etc

When working with union remote:

Any deletion on myminio should be updated in the index

I should be able to move all data from union: to myminio: when I get it online and old union remote and new minio LS should be same.

The current cache backends don't support this.

What I gain is I am able to keep backups offline for a week or a month while I still continue to take daily or hourly backups.

Hope I am clear

**Comment by calisro** [comment]
> There should be a way to update the index
> Rclone offlinemyminio: reindex
> The above command should hit myminio: and update the index with file size etc

You can use the --rc remote control to force a rescan if you're running a 'serve' process.  If you're not, then you can just clear the DB and issue a command that relists everything like 'rclone lsl offlinemyminio: --cache-db-purge'.  That will clear the DB and repopulate it with the metadata.

> Any deletion on myminio should be updated in the index

Some of the remotes support this like google drive.  I'm not sure if minio has support for a change log like that.  

Maybe I misunderstood though.

**Comment by saviodsouza** [comment]
> 
> Some of the remotes support this like google drive. I'm not sure if minio has support for a change log like that.
> 
My perpose of offline index backend is to keep cold backups and primary backend independent, let it be minio or AWS or Dropbox.

This new backend with also help in incremental offline sync.
I have a pc without internet access I first backup using testicles or borg, or something similar
Let's take any online storage for example  let's take dropbox here.
At first time I sync 100 GB of backup from another network with internet access
I then create a offline index and store it on my thumb drive.
I create a new union remote with the offline index backend as my primary and a sub folder in my external hard drive as secondary
I continue daily offline Backups on my union remote.
After a week or two I take the external hard drive and sync the secondary backend of the union remote to dropbox

https://github.com/ncw/rclone/projects/2
This backend would help the rclone backup implementation as it helps to keep snapshots offline from the working environment (Implement a high level rclone backup command for incremental backups with snapshots of previous state)

I am open to comments
