### ISSUE TITLE
Disguise filename in order to protect from removal by Cloud Providers

### ISSUE THREAD

**Issue by gabriellluz** [rclone/rclone#3061]
#### What is your current rclone version (output from `rclone version`)?
1.45

#### What problem are you are trying to solve?
When I upload files to OneDrive with encrypted filenames, my OneDrive thinks it's ransomware and keeps me warning about that. In the future, they might remove them automatically.

#### How do you think rclone should be changed to solve that?
I think an option should be created in order to disguise those filenames like "filename01.rar" or something that looks like a backup structure but can be easily mounted with rclone.

**Comment by ncw** [comment]
Is it the encrypted filenames or the encrypted contents that is the problem?

You could also try one of the other file name encryption modes

#### --crypt-filename-encryption

How to encrypt the filenames.

- Config:      filename_encryption
- Env Var:     RCLONE_CRYPT_FILENAME_ENCRYPTION
- Type:        string
- Default:     "standard"
- Examples:
    - "off"
        - Don't encrypt the file names.  Adds a ".bin" extension only.
    - "standard"
        - Encrypt the filenames see the docs for the details.
    - "obfuscate"
        - Very simple filename obfuscation.

**Comment by gabriellluz** [comment]
I don't want my titles to be shown.

For example:
I'd like something like this:

Original structure:
TVSHOW-S01E01.mkv
TVSHOW-S01E02.mkv
TVSHOW-S01E03.mkv
TVSHOW-S01E04.mkv

"Disguised" structure:

bkps20032019-142-00001.mkv or .rar
bkps20032019-142-00002.mkv or .rar
bkps20032019-142-00003.mkv or .rar
bkps20032019-142-00004.mkv or .rar

I don't want a structure like this. If I use a structure like this, OneDrive staff think it's ransomware and keeps me annoying with messages and threatening to remove my files.
h156O9zEW1ybRSR05PYXW9ysAKfBes20E2o5TuL1Jq4=
h156O9zEsdfsdfsvsdfvPYXW9ysAKfBes20E2o5TuL1Jq4=
h156O9zEW1ybRSR05PYXW9ysAKfBes20E2o5TuL1Jq4=
h156O9zEW1ybRSR05PYXWsdfsdfsdas20E2o5TuL1Jq4=

Also, if I setup my file like above, it's more like to get them removed by cloud providers.

Syncovery has that resource. You can create a filename "mask" with a ".sz" extension, which is ZIP encryption and compression at the same time. Syncovery can't mount files, though.

I want basically rclone to do this:
- let me create a filename mask like this:

Choose a filename mask: "backup-gps-20032019".

Then it creates an encrypted XML file that makes it easy to mount the folder.
So I get a structure like this: (keep in mind that those files below don't have to necessarily be inside zip or rar files. It's just a filename with a zip extension, not really a compressed file)

"backup-gps-20032019-00000000.zip" (xml file with the structure)
"backup-gps-20032019-00000001.zip"
"backup-gps-20032019-00000002.zip"
"backup-gps-20032019-00000003.zip"
"backup-gps-20032019-00000004.zip"

Everytime I add new files to that same folder, it just changes the XML file which is "backup-gps-20032019-00000000.zip" and just create new files according the same "backup-gps" mask, so we get new files like this:
**"backup-gps-20032019-00000005.zip"
"backup-gps-20032019-00000006.zip"**

When I mount the folder, it just reads the xml content so I get something like this:
**bkps20032019-142-00001.mkv
bkps20032019-142-00002.mkv
bkps20032019-142-00003.mkv
bkps20032019-142-00004.mkv**


If rclone can do it, just tell me how I can use it. Because I want to use a similar structure and be able to mount it.

**Comment by ncw** [comment]
Rclone can't do that right now.  However it does have the `obfuscate` setting file names - why don't you give that a go?

The file names will end up looking something like

```
69.Gjmf obnf xjui't.uyu
128.pyvnoB_xkwo_GsDryED_mBIzD/20.jgnnq
```

**Comment by caspertone2003** [comment]
Just a comment.
Some cloud storage analyse the contents of zip files, so, if you name a file zip and the contents does not correspond, also show a warning or a complain.
So, just having nice filenames with encrypted contents inside will not solve the issue.

Only way forward in the future for content scanning cloud storage is to use nice filenames with zip extension and encrypted zip content, but inside content filenames need to be ofuscated as encrypted ziped files do not hide file names of contents; if not zip encrypted they can be read; this could be a solution until they do not accept those (encrypted zipped). Besides, perhaps some kind of "salt" has to be added inside the zip to avoid content matching via hashing.
Perhaps the best point to implement all those games would be winfsp... but I am not expert enough to tell.

**Comment by gabriellluz** [comment]
> Rclone can't do that right now. However it does have the `obfuscate` setting file names - why don't you give that a go?
> 
> The file names will end up looking something like
> 
> ```
> 69.Gjmf obnf xjui't.uyu
> 128.pyvnoB_xkwo_GsDryED_mBIzD/20.jgnnq
> ```

I've tried that already but OneDrive keeps saying I have ransomware and then it gives me 30 days in order to take action so I can keep my files.

**Comment by gabriellluz** [comment]
> Just a comment.
> Some cloud storage analyse the contents of zip files, so, if you name a file zip and the contents does not correspond, also show a warning or a complain.
> So, just having nice filenames with encrypted contents inside will not solve the issue.
> 
> Only way forward in the future for content scanning cloud storage is to use nice filenames with zip extension and encrypted zip content, but inside content filenames need to be ofuscated as encrypted ziped files do not hide file names of contents; if not zip encrypted they can be read; this could be a solution until they do not accept those (encrypted zipped). Besides, perhaps some kind of "salt" has to be added inside the zip to avoid content matching via hashing.
> Perhaps the best point to implement all those games would be winfsp... but I am not expert enough to tell.

Yes, I understand you. Content must be encrypted too. But I think encrypting filenames will make them do what they're doing now: tell me I have ransomware. If they change their policy they might as well remove my files without further notice.

**Comment by calisro** [comment]
Perhaps there is a way to disable the randsomware scanning protection?  I see you can do this in defender and they reference onedrive but i'm not sure if this is relevant to your exact situation.

https://www.winhelponline.com/blog/set-up-onedrive-yellow-exclamation-defender-security-center/

**Comment by gabriellluz** [comment]
> Perhaps there is a way to disable the randsomware scanning protection? I see you can do this in defender and they reference onedrive but i'm not sure if this is relevant to your exact situation.
> 
> https://www.winhelponline.com/blog/set-up-onedrive-yellow-exclamation-defender-security-center/

If you're talking about the Windows App, this is useless and has no effect on my account. I think your link only makes changes to OneDrive app.
I'm using rclone to do that.

**Comment by calisro** [comment]
If it were me, I'd open a ticket with onedrive because they are the ones flagging real data as randsomware.  They may be able to either disable it, tell you how to, or confirm that there is no way.  If they allow you to disable it in their tools, they likely allow you to disable it in the cloud storage end.  But hey, it is MS.

**Comment by gabriellluz** [comment]
> If it were me, I'd open a ticket with onedrive because they are the ones flagging real data as randsomware. They may be able to either disable it, tell you how to, or confirm that there is no way. If they allow you to disable it in their tools, they likely allow you to disable it in the cloud storage end. But hey, it is MS.

That won't fix the problem.

Imagine someone trying to find something in your cloud drives. If they know which files are encrypted, then they know what to encrypt. If the filenames are disguised, people won't bother trying to decrypt or download them in order to decrypt them in the future.

**Comment by calisro** [comment]
The issue was about ransomware on OneDrive. Not security by obsecurity.

**Comment by gabriellluz** [comment]
> The issue was about ransomware on OneDrive. Not security by obsecurity.

My title says "cloud providers". OneDrive was an example. Once a cloud provider adds a ransomware security layer, I'll have the mentioned problem above.

**Comment by gabriellluz** [comment]
Maybe something like this? A RAR virtual file system, something like that.

[https://github.com/shaohao/vfs_rar](https://github.com/shaohao/vfs_rar)

**Comment by calisro** [comment]
https://github.com/ncw/rclone/issues/3084

This is implicitly trying to do the same thing minus the randsomware concern.  Might want to close this and support that issue instead.
