### ISSUE TITLE
Support poll-interval for OneDrive

### ISSUE THREAD

**Issue by Randomico** [rclone/rclone#3062]
What is your current rclone version (output from `rclone version`)?
Rclone 1.44
Arch-OS: ARM - 64

What problem are you are trying to solve?
Files uploaded outside the OneDrive mount are not updating until dir-cache-time expires.
Currently, this feature is supported by other remotes, OneDrive is not on the list.

How do you think rclone should be changed to solve that?
If possible, add poll-interval support for OneDrive mount.

**Comment by Cnly** [comment]
I took a quick look at the API docs and found https://docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0 seems to be the API we need for this. @Randomico do you want to help implement this feature? :)

**Comment by Randomico** [comment]
> I took a quick look at the API docs and found https://docs.microsoft.com/en-us/graph/api/driveitem-delta?view=graph-rest-1.0 seems to be the API we need for this. @Randomico do you want to help implement this feature? :)

Hey, if i had the expertise i certainly would, but im a noob at these matters =(

**Comment by jackitsdotcom** [comment]
Still running into this issue here. I might have a look into how I can adapt to the new API but I am a novice.
