### ISSUE TITLE
Support premiumize.me cloud provider

### ISSUE THREAD

**Issue by hamdulillah** [rclone/rclone#3063]
#### What is your current rclone version (output from `rclone version`)?

1.46.0

#### What problem are you are trying to solve?

there is no support for the provider premiumize.me

#### How do you think rclone should be changed to solve that?

rclone should allow to manage files on premiumize.me and mount the cloud drive.

The API is described at https://app.swaggerhub.com/apis-docs/premiumize.me/api/1.4

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.49

Any testing much appreciated :-)

**Comment by J0s3f** [comment]
I tested it and have no problems so far. Copying from/to cloud and mounting on windows works.
Thank you!

**Comment by ncw** [comment]
> I tested it and have no problems so far. Copying from/to cloud and mounting on windows works.
> Thank you!

Thanks for testing :-)

**Comment by ncw** [comment]
PS Anyone looking for the docs - the beta docs are here: https://tip.rclone.org/premiumizeme/
