### ISSUE TITLE
GDrive: unable to access all shared folders if they have the same name using rclone

### ISSUE THREAD

**Issue by avatar-lavventura** [rclone/rclone#3064]
I am using `rclone` to access shared files on my google drive.

*For example*, a Google Drive user shares two folders that have the same name. Hence, I am unable to access those both folders through `rclone`; I am only able to obtain the latest shared folder. I think, if there is duplicated shared folders with same folder name, I could only view the latest shared folder.

Those two folders are shared with my Google Drive.

    $ ls foo
    hello.txt
    $ ls foo
    goodbye.txt

On my `rclone`, I can only obtain the latest shared folder :

    $ rclone ls remote: --drive-shared-with-me
       201942 foo/hello.txt
       201942 foo/hello.txt
    $ rclone ls remote:foo --drive-shared-with-me
       goodbye.txt

--------

I was using (https://github.com/gdrive-org/gdrive) that was allowing me to download folders that have the same name through their unique ID: 

` gdrive download --recursive ID_of_the_folder`.  

=> I guess that option is not available through `rclone`.

    $ gdrive list
     Id                                  Name  Type   Size     Created
     14IC1hufjb5WArh_75_G_dvmZgmlIK50V   doo   bin    4.7 KB   2019-03-22 16:37:27
     1veladRJ4mfm6t0W9mntb8FILG-fqgQH2   doo   bin    4.7 KB   2018-05-03 19:23:38

    $ gdrive download --recursive 14IC1hufjb5WArh_75_G_dvmZgmlIK50V  # ID_of_the_folder
    $ gdrive download --recursive 1veladRJ4mfm6t0W9mntb8FILG-fqgQH2  # ID_of_the_folder

**[Q]** Is there any way to handle this issue through `rclone`?

**Comment by ncw** [comment]
If you have a duplicate folder then you can use 

      --drive-root-folder-id string   ID of the root folder

So

    rclone ls remote: --drive-shared-with-me --drive-root-folder-id 14IC1hufjb5WArh_75_G_dvmZgmlIK50V

**Comment by avatar-lavventura** [comment]
I am not sure why but I guess `--drive-root-folder-id` seems like does not working. @ncw 

    $ gdrive info 1xnGc-FFWgYu2xflIWg9lYjnqWkyb0siR
    Id: 1xnGc-FFWgYu2xflIWg9lYjnqWkyb0siR
    Name: b5431f59c7a6fbcc2003362227044d07.tar.gz
    Path: b5431f59c7a6fbcc2003362227044d07/b5431f59c7a6fbcc2003362227044d07.tar.gz
    Description: b5431f59c7a6fbcc2003362227044d07.tar.gz
    Mime: application/gzip
    Size: 540.0 B
    Created: 2019-03-26 13:48:28
    Modified: 2019-03-26 13:48:30
    Md5sum: b5431f59c7a6fbcc2003362227044d07
    Shared: True
    Parents: 1Y8LbCsojP5JADhSgbAGkV7732y7g5vC7
    ViewUrl: https://drive.google.com/file/d/1xnGc-FFWgYu2xflIWg9lYjnqWkyb0siR/view?usp=drivesdk
    DownloadUrl: https://drive.google.com/uc?id=1xnGc-FFWgYu2xflIWg9lYjnqWkyb0siR&export=download

    $ rclone ls remote:b5431f59c7a6fbcc2003362227044d07
          540 b5431f59c7a6fbcc2003362227044d07.tar.gz

-------

Following line returns empty:

    $ rclone ls remote: --drive-root-folder-id='1xnGc-FFWgYu2xflIWg9lYjnqWkyb0siR'

-------

    $ rclone ls remote:b5431f59c7a6fbcc2003362227044d07 --drive-root-folder-id='1xnGc-FFWgYu2xflIWg9lYjnqWkyb0siR'
    2019/03/26 13:57:47 ERROR : : error listing: directory not found
    2019/03/26 13:57:47 Failed to ls: directory not found

**Comment by ncw** [comment]
I think you may need `--drive-shared-with-me`

**Comment by avatar-lavventura** [comment]
Please note that the folder is not shared with me and created under my own GDrive folder. When I add `--drive-shared-with-me` it returns all the shared files so I had do do `| grep <folder name>`. @ncw 

```
$ rclone ls remote: --drive-root-folder-id '1xnGc-FFWgYu2xflIWg9lYjnqWkyb0siR' --drive-shared-with-me | grep 'b5431f59c7a6fbcc2003362227044d07'
      540 b5431f59c7a6fbcc2003362227044d07.tar.gz
$ rclone lsjson remote: --drive-root-folder-id '1xnGc-FFWgYu2xflIWg9lYjnqWkyb0siR' --drive-shared-with-me | grep 'b5431f59c7a6fbcc2003362227044d07'
{"Path":"b5431f59c7a6fbcc2003362227044d07.tar.gz","Name":"b5431f59c7a6fbcc2003362227044d07.tar.gz","Size":540,"MimeType":"application/gzip","ModTime":"2019-03-26T10:48:30.971Z","IsDir":false,"ID":"1xnGc-FFWgYu2xflIWg9lYjnqWkyb0siR"},
```

----

Following line also does not work:

```
$ rclone ls remote:b5431f59c7a6fbcc2003362227044d07 --drive-root-folder-id '1xnGc-FFWgYu2xflIWg9lYjnqWkyb0siR' --drive-shared-with-me
2019/03/26 23:04:27 ERROR : : error listing: directory not found
2019/03/26 23:04:27 Failed to ls: directory not found
```

**Comment by ncw** [comment]
> Please note that the folder is not shared with me and created under my own GDrive folder. When I add `--drive-shared-with-me` it returns all the shared files, if there is hundreds of shared files it prints all of them which seems little bit inefficient.

Are the things you are trying to access shared with you? If so you will need the `--drive-shared-with-me` flag.



> it returns all the shared files, if there is hundreds of shared files it prints all of them which seems little bit inefficient.

You can control the depth of listing with `--max-depth 1` or use the `rclone lsf` command which works more like `ls` in unix and will show directories too.

> Following line also does not work:
> $ rclone ls remote:b5431f59c7a6fbcc2003362227044d07 --drive-root-folder-id '1xnGc-FFWgYu2xflIW

That should be as below, the `--drive-root-folder-id` selects the directory as the root so there is no need to change into it.

    rclone ls remote: --drive-root-folder-id '1xnGc-FFWgYu2xflIW

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
