### ISSUE TITLE
Unable to setup Onedrive connection

### ISSUE THREAD

**Issue by abhi18av** [rclone/rclone#3068]
Hi @ncw , I'm using latest `rclone v1.46` and I have used the previous versions perfectly fine however, this time I'm facing issues while configuring for `onedrive personal`.

```
Choose a number from below, or type in an existing value
 1 / OneDrive Personal or Business
   \ "onedrive"
 2 / Root Sharepoint site
   \ "sharepoint"
 3 / Type in driveID
   \ "driveid"
 4 / Type in SiteID
   \ "siteid"
 5 / Search a Sharepoint site
   \ "search"
Your choice> onedrive
2019/03/23 03:50:08 Failed to query available drives: HTTP error 401 (401 Unauthorized) returned body: "{\r\n  \"error\": {\r\n    \"code\": \"InvalidAuthenticationToken\",\r\n    \"message\": \"CompactToken parsing failed with error code: 8004920A\",\r\n    \"innerError\": {\r\n      \"request-id\": \"0e66656f-53ac-46b5-b245-c51684201f0c\",\r\n      \"date\": \"2019-03-23T03:50:08\"\r\n    }\r\n  }\r\n}"
```

Could you please guide me here a bit?

**Comment by ncw** [comment]
This looks like it is this issue: https://github.com/OneDrive/onedrive-api-docs/issues/785

There are various things to try in that thread.

Did you try creating a new remote - does that work or do you get the same error?

@Cnly any ideas?

**Comment by Cnly** [comment]
Sorry that I missed this conversation; I found it when I was looking through some old issues. Personally I have never encountered such a problem with OneDrive Personal or Business, so I really can't reproduce it :( And that OneDrive issue also seems to have been ignored by the OneDrive team - there have been no updates from them for a long time.

By the way, @abhi18av I wonder if you're still seeing this now?

**Comment by ncw** [comment]
I'm going to close this now as we haven't heard from you for a while.

**Comment by abhi18av** [comment]
Oh, I can confirm that this is working fine now. Apologies for the late update 😅
