### ISSUE TITLE
Rclone dry run should provide a summary of total number of files and total amount of data that will be copied or transferred

### ISSUE THREAD

**Issue by pspanchal** [rclone/rclone#3074]
#### What is your current rclone version (output from `rclone version`)?
1.46

#### What problem are you are trying to solve?
Trying to understand how to get the total amount of files and total amount of data to be transferred without actually transferring the same

#### How do you think rclone should be changed to solve that?
RClone dry-run should ideally display this 

Also this summary would be good to be displayed at the end of transfer or sync to a separate log file

**Comment by ncw** [comment]
If you use the `-v` flag then you will get this info I think.
