### ISSUE TITLE
Rclone remote cache   mounted and served

### ISSUE THREAD

**Issue by segator** [rclone/rclone#3099]
rclone v1.46

Right now when using remote backend cache you only are able to use a single rclone command at a time(database in use) so if you for example mount you are not able to do any other rclone command like copy cachestats and so on,
This is worst when we want to mount but also to serve at the same time
For example to mount on your local pc but serve for other clients as http using your cached backend.

**Comment by calisro** [comment]
You can mount it and then serve from the mount. Both would then be passing through the cache.

**Comment by segator** [comment]
How you automate the boot of this?
Other solution will be cache + serve then mount use served but then 3 level of cache, too much

Remote cache + vfs serve + vfs mount

**Comment by calisro** [comment]
You would automate the start like any other rclone process. You're just pointing it at the mount. 

That being said of you're just running an http server against a mount it could also use other things for that like caddy.  Rclone will definitely work too like that. But just mentioning.

**Comment by segator** [comment]
yes I understand what I'm worried 

is not instant rclone mount, so you can not guarantee chainning 2 services the second have the folder really mounted, So if you want to be sure always will works you need to somehow check before start the service, the rclone mount the directory.

**Comment by caspertone2003** [comment]
Not knowing which OS is being used.
I mount several in W10 using start command, and then I need a timeout to wait for the mount. I am sure there could be something more sofisticated, but timeout 20 seconds just gives time to finishing the mount.

**Comment by segator** [comment]
I'm using ubuntu 18.

**Comment by calisro** [comment]
What I personally do is use caddy to serve a http based on the rclone mount. It can also automatically start the rclone mount itself via it's config.

**Comment by animosity22** [comment]
This looks to be answered. If you have any further questions, please just ask on the forums.
