### ISSUE TITLE
Check validity of crypt remotes when renaming a remote

### ISSUE THREAD

**Issue by tuxsoy** [rclone/rclone#3100]
It's possible to rename remotes such that crypt remotes get invalidated.

I'm currently using the following version of rclone:

```
rclone v1.46
- os/arch: linux/amd64
- go version: go1.11.5
```

As an example, consider the following:
1. Create an unencrypted remote called "remote"
2. Create an encrypted remote of (1) called "encrypted_remote"
3. Rename (1) to "unencrypted_remote"
4. Rename (2) to "remote"

The following error message would be displayed in this case:

```
Failed to create file system for "remote:path": can't point crypt remote at itself - check the value of the remote setting
```

It would be much better if rclone could automatically track the remote name and change it while renaming.

**Comment by calisro** [comment]
You can change the names of the remotes without issue. What's your config look like?

**Comment by tuxsoy** [comment]
The final config should look similar to the following:

```
[unencrypted_remote]
type = drive
scope = drive
token = ...

[remote]
type = crypt
remote = remote:crypt
filename_encryption = standard
directory_name_encryption = true
password = ...
password2 = ...
```

It's a quick fix on the user side. Just need to edit the remote for `remote` to `unencrypted_remote:crypt`. But it would be nice if rclone can figure that out automatically.

**Comment by animosity22** [comment]
How would rclone figure out what the names would be?

**Comment by ncw** [comment]
So what you'd like to see is

If you rename a remote, rclone runs through the config file renaming any `remote =` lines if it features?

That is of course possible, but it is a lot of code for something which doesn't happen very often.

**Comment by tuxsoy** [comment]
> That is of course possible, but it is a lot of code for something which doesn't happen very often.

I was hoping that this would be a simple feature to add. Feel free to close the issue if that's not the case.

**Comment by ncw** [comment]
> > That is of course possible, but it is a lot of code for something which doesn't happen very often.
> 
> I was hoping that this would be a simple feature to add. Feel free to close the issue if that's not the case.

One of the problems is that different remotes use different conventions, so the `crypt` backend uses `remote` whereas the `union` backend uses `remotes` which is a space separated list of backends....

I'll leave this open in the hope that someone would like to help.

**Comment by ivandeex** [comment]
Closing after 2 years of inactivity
