### ISSUE TITLE
Input/output error on linux with rclone mount of s3 bucket and empty file

### ISSUE THREAD

**Issue by hading** [rclone/rclone#3103]
#### What is the problem you are having with rclone?

If I mount a bucket with 'rclone mount' and then try to operate on an empty file (to read it) then I receive an input/output error.

#### What is your rclone version (output from `rclone version`)

$ rclone version
rclone v1.46
- os/arch: linux/amd64
- go version: go1.11.5

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

$ cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core) 

64 bit

I should note that I do _not_ see this issue in OSX 10.14.4 with the same version of rclone.

####  Which cloud storage system are you using? (eg Google Drive)

AWS S3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

$ touch empty-file 
Mon 09:06:58 medusa@aws-medusa-prod ~/tmp
$ md5sum empty-file 
d41d8cd98f00b204e9800998ecf8427e  empty-file
Mon 09:07:01 medusa@aws-medusa-prod ~/tmp
$  rclone mount medusa-user:medusa-prod-main s3 -vv --log-file ./rclone.log &
[1] 18822
Mon 09:07:10 medusa@aws-medusa-prod ~/tmp
$ cp empty-file s3/.
Mon 09:07:23 medusa@aws-medusa-prod ~/tmp
$ md5sum s3/empty-file 
md5sum: s3/empty-file: Input/output error
Mon 09:07:29 medusa@aws-medusa-prod ~/tmp
$ cat s3/empty-file 
cat: s3/empty-file: Input/output error
Mon 09:07:34 medusa@aws-medusa-prod ~/tmp

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2019/04/08 09:07:10 DEBUG : rclone: Version "v1.46" starting with parameters ["rclone" "mount" "medusa-user:medusa-prod-main" "s3" "-vv" "--log-file" "./rclone.log"]
2019/04/08 09:07:10 DEBUG : Using config file from "/home/medusa/.config/rclone/rclone.conf"
2019/04/08 09:07:10 DEBUG : S3 bucket medusa-prod-main: Mounting on "s3"
2019/04/08 09:07:10 INFO  : S3 bucket medusa-prod-main: poll-interval is not supported by this remote
2019/04/08 09:07:10 DEBUG : Adding path "vfs/forget" to remote control registry
2019/04/08 09:07:10 DEBUG : Adding path "vfs/refresh" to remote control registry
2019/04/08 09:07:10 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2019/04/08 09:07:10 DEBUG : : Root: 
2019/04/08 09:07:10 DEBUG : : >Root: node=/, err=<nil>
2019/04/08 09:07:23 DEBUG : /: Attr: 
2019/04/08 09:07:23 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2019/04/08 09:07:23 DEBUG : /: Lookup: name="empty-file"
2019/04/08 09:07:23 DEBUG : pacer: Reducing sleep to 0s
2019/04/08 09:07:23 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2019/04/08 09:07:23 DEBUG : /: Lookup: name="empty-file"
2019/04/08 09:07:23 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2019/04/08 09:07:23 DEBUG : /: Create: name="empty-file"
2019/04/08 09:07:23 DEBUG : empty-file: Open: flags=O_WRONLY|O_CREATE|O_EXCL
2019/04/08 09:07:23 DEBUG : empty-file: >Open: fd=empty-file (w), err=<nil>
2019/04/08 09:07:23 DEBUG : /: >Create: node=empty-file, handle=&{empty-file (w)}, err=<nil>
2019/04/08 09:07:23 DEBUG : empty-file: Attr: 
2019/04/08 09:07:23 DEBUG : empty-file: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
2019/04/08 09:07:23 DEBUG : &{empty-file (w)}: Flush: 
2019/04/08 09:07:23 DEBUG : empty-file: WriteFileHandle.Flush unwritten handle, writing 0 bytes to avoid race conditions
2019/04/08 09:07:23 DEBUG : &{empty-file (w)}: >Flush: err=<nil>
2019/04/08 09:07:23 DEBUG : &{empty-file (w)}: Release: 
2019/04/08 09:07:23 DEBUG : empty-file: WriteFileHandle.Release closing
2019/04/08 09:07:23 DEBUG : S3 bucket medusa-prod-main: File to upload is small (0 bytes), uploading instead of streaming
2019/04/08 09:07:23 INFO  : empty-file: Copied (new)
2019/04/08 09:07:23 DEBUG : &{empty-file (w)}: >Release: err=<nil>
2019/04/08 09:07:29 DEBUG : empty-file: Open: flags=OpenReadOnly
2019/04/08 09:07:29 DEBUG : empty-file: Open: flags=O_RDONLY
2019/04/08 09:07:29 DEBUG : empty-file: >Open: fd=empty-file (r), err=<nil>
2019/04/08 09:07:29 DEBUG : empty-file: >Open: fh=&{empty-file (r)}, err=<nil>
2019/04/08 09:07:29 DEBUG : empty-file: Attr: 
2019/04/08 09:07:29 DEBUG : empty-file: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
2019/04/08 09:07:29 DEBUG : &{empty-file (r)}: Read: len=4096, offset=0
2019/04/08 09:07:29 DEBUG : empty-file: ChunkedReader.openRange at 0 length 134217728
2019/04/08 09:07:29 DEBUG : &{empty-file (r)}: >Read: read=0, err=InvalidRange: The requested range is not satisfiable
	status code: 416, request id: AFCA84BEFB787C85, host id: R7F8w8csCAVEN5CGbRm2ZGWGlzJ5sKTjZM28onfDhYtXzHXm2ZU2ro6MnIhFOnQcTv25EJIdfgE=
2019/04/08 09:07:29 DEBUG : &{empty-file (r)}: Flush: 
2019/04/08 09:07:29 DEBUG : &{empty-file (r)}: >Flush: err=<nil>
2019/04/08 09:07:29 DEBUG : &{empty-file (r)}: Release: 
2019/04/08 09:07:29 DEBUG : &{empty-file (r)}: >Release: err=<nil>
2019/04/08 09:07:34 DEBUG : empty-file: Open: flags=OpenReadOnly
2019/04/08 09:07:34 DEBUG : empty-file: Open: flags=O_RDONLY
2019/04/08 09:07:34 DEBUG : empty-file: >Open: fd=empty-file (r), err=<nil>
2019/04/08 09:07:34 DEBUG : empty-file: >Open: fh=&{empty-file (r)}, err=<nil>
2019/04/08 09:07:34 DEBUG : empty-file: Attr: 
2019/04/08 09:07:34 DEBUG : empty-file: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
2019/04/08 09:07:34 DEBUG : &{empty-file (r)}: Read: len=4096, offset=0
2019/04/08 09:07:34 DEBUG : empty-file: ChunkedReader.openRange at 0 length 134217728
2019/04/08 09:07:34 DEBUG : &{empty-file (r)}: >Read: read=0, err=InvalidRange: The requested range is not satisfiable
	status code: 416, request id: 05EC2C49B2D0AC61, host id: tHShqNt44irCsLI5bMkWwWSQtjzEaRXt9OziDxExSmmKtUHNsfUl+Rvs5fE0aqIx3lr+s0Wezys=
2019/04/08 09:07:34 DEBUG : &{empty-file (r)}: Flush: 
2019/04/08 09:07:34 DEBUG : &{empty-file (r)}: >Flush: err=<nil>
2019/04/08 09:07:34 DEBUG : &{empty-file (r)}: Release: 
2019/04/08 09:07:34 DEBUG : &{empty-file (r)}: >Release: err=<nil>
2019/04/08 09:07:59 DEBUG : rclone: Version "v1.46" finishing with parameters ["rclone" "mount" "medusa-user:medusa-prod-main" "s3" "-vv" "--log-file" "./rclone.log"]

**Comment by ncw** [comment]
I think we've already fixed this in 415eeca6cf5e05b5137a6ef092787a23ccd308a7 - can you try [the latest beta](https://beta.rclone.org) to see if it works for you?

**Comment by hading** [comment]
I tried it with the latest beta when I filed the ticket, but I will retry with whatever is available today when I get a few minutes. Thanks.

**Comment by ncw** [comment]
I just checked the commit - looks like it was only fixed for drive not s3 - sorry!

A similar fix will probably work for s3.

This needs an integration test too...

**Comment by acs-ferreira** [comment]
I confirm this on **rclone v1.50.2**

**Comment by ncw** [comment]
@acs-ferreira I can't replicate this problem any more - what exactly are you trying?

```
rclone-v1.50.1 mount -vv s3:rclone/ /mnt/tmp/
```

```
$ md5sum /mnt/tmp/empty 
d41d8cd98f00b204e9800998ecf8427e  /mnt/tmp/empty
$ cat /mnt/tmp/empty 
$ md5sum /mnt/tmp/empty 
d41d8cd98f00b204e9800998ecf8427e  /mnt/tmp/empty
$ ls -l /mnt/tmp/empty 
-rw-rw-r-- 1 ncw ncw 0 Dec  3 10:40 /mnt/tmp/empty
```

**Comment by acs-ferreira** [comment]
I've mount a Scaleway S3 backend, then `touch .testfile` then `rm .testfile` produced the error.

**Comment by ncw** [comment]
@acs-ferreira 

I don't have a scaleway account, but I can't reproduce this with aws s3, ceph or digital ocean.

Can you run your failing commands and post the log from the mount with `-vv --dump bodies` (feel free to edit for privacy).

**Comment by ivandeex** [comment]
This ticket is more than 1 year stale. Feel free to reopen if the problem persists.
