### ISSUE TITLE
Is it taking too long?

### ISSUE THREAD

**Issue by arvenil** [rclone/rclone#3109]
#### Output of `rclone version`
```
# rclone version
rclone v1.46
- os/arch: darwin/amd64
- go version: go1.11.5
```

#### Describe the issue

I have two disks, one is `photos01` and second `photos02` as backup. Both were in sync but then I've rearranged dirs and names and added some photos to `photos01`. Naturally I wanted to use rsync but it doesn't handle well renames - if file was moved or renamed rsync would copy it again. However rclone has `--track-renames` option so I thought about using it. Below is result:

```sh
rclone sync \
	-P \
	--track-renames \
	--backup-dir=/backup/rclone-photos01-to-photos02-$(date "+%Y_%m_%d-%H_%M_%S") \
	--log-file=/logs/rclone-photos01-to-photos02-$(date "+%Y_%m_%d-%H_%M_%S").log \
	/Volumes/Photos\ 01 \
	/Volumes/PHOTOS\ 02
```

```
Transferred:   	   26.913G / 26.913 GBytes, 100%, 1.338 MBytes/s, ETA 0s
Errors:                 6 (retrying may help)
Checks:             48179 / 48179, 100%
Transferred:          344 / 344, 100%
Elapsed time:  5h43m10.6s
```

Almost 6h seems to be a lot of time to copy 26 GBytes... is this expected? I mean I understand some overhead in case of comparing files but still 6h is much more than I expected. There is 13649 (some of them hidden, not sure if `sync` synchronizes them too, I didn't care for them in this case) files on disk. I observed it also a bit during the process and I remember that after 2h it was still 0 bytes transferred.
```
find /Volumes/Photos\ 01 | wc -l
   13649
```

Is there any way I can figure out what took it so long? Any suggestions to speed this up?

**Comment by arvenil** [comment]
Second pass, no changes to disks:
```
Transferred:   	    2.622M / 2.622 MBytes, 100%, 516 Bytes/s, ETA 0s
Errors:                64 (retrying may help)
Checks:             40838 / 40838, 100%
Transferred:            1 / 1, 100%
Elapsed time:  1h28m40.1s
```

**Comment by ncw** [comment]
> Is there any way I can figure out what took it so long?

It has to make MD5SUMs of all the files that are out of place.  If this is many GB then this will take a lot of CPU power.  On my laptop rclone takes 8s to MD5SUM a 1GB file, so 125MByte/s but then it does have an SSD...

What kind of disks are these? HD or SSD?

If you use `-vv` then there may be a clue in the log.

**Comment by arvenil** [comment]
Hey, thanks for the replay. Checksums explain a lot... I thought by default it compares just size and dates? What are the Checks? Considering there is only ~13k files ~40k checks looks suspicious too.

**Comment by arvenil** [comment]
@ncw Hey, thanks for the replay. Checksums explain a lot... I thought by default it compares just size and dates, not checksums? There is option `-c, --checksum` but I'm not passing it so I thought it's gonna be just size and dates?

What are the Checks? Considering there is only ~13k files ~40k checks looks suspicious too.

**Comment by ncw** [comment]
> Hey, thanks for the replay. Checksums explain a lot... I thought by default it compares just size and dates, not checksums?

It does yes, but when using `--track-renames` it computes the checksum too to be 100% certain you've got the right file.




> What are the Checks? Considering there is only ~13k files ~40k checks looks suspicious too.

A check is comparing a src file to a dst file.  This could be bigger than 13k if there were retries. (Rclone does 3 by default, so 3*13k ~= 40k)
