### ISSUE TITLE
How to keep the file owner when use rclone sync

### ISSUE THREAD

**Issue by lohasfeng123** [rclone/rclone#3110]
Hello,
How to keep the file owner when use rclone sync?

ll local/
-rw------- 1 sure sure 0 Apr 12 11:03 testfile

rclone sync local/ dest/

ll dest/
-rw------- 1 root root 0 Apr 12 11:03 testfile

Thanks

**Comment by calisro** [comment]
Rclone doesn't track ownership. You could do this though:

getfacl -R /some/path > /backup/path  (or use rclone rcat/cat to send directly)

And back that up with rclone.  To restore it you'd just restore your data and then run

setfacl --restore=file  (or again rclone cat/rcat)

**Comment by ncw** [comment]
Nice answer @calisro  - do you fancy making a PR to add this to [the FAQ](https://github.com/ncw/rclone/blob/master/docs/content/faq.md)?  This question comes up often enough to deserve it I think.

**Comment by calisro** [comment]
Yes I'll do that. Np.

**Comment by animosity22** [comment]
Answered.
