### ISSUE TITLE
Rclone rc core/stats doesn't show all stats

### ISSUE THREAD

**Issue by turkeyphant** [rclone/rclone#3129]
When running rclone with `--progress` you get several stats that aren't available from `rclone rc core/stats` most importantly the ETA.

Is there any way to access the ETA with a `rclone rc` command?

https://forum.rclone.org/t/rclone-rc-core-stats-and-additional-stats/9699

#### What is your current rclone version (output from `rclone version`)?
1.47.0

#### What problem are you are trying to solve?
Get stats from remote control to serve on web interfaces

#### How do you think rclone should be changed to solve that?
Include all states visible from `--progress` in `core/stats` (and potentially more information too).

**Comment by gary-kim** [comment]
I just made a working version that includes the eta. It shouldn't be hard to add the rest.
@ncw Do you think that this is an improvement that would be nice to have?

**Comment by ncw** [comment]
@gary-kim sounds interesting!

I note we have an outstanding PR https://github.com/ncw/rclone/pull/2308 which didn't get merged yet - is what you are doing related to that?  Maybe you'd like to finish the PR off (or I can)?

**Comment by gary-kim** [comment]
Just saw that PR.

I'm not sure that the PR is still necessary. It seems like a lot of what it adds has been added to rclone.

**Comment by ivandeex** [comment]
@turkeyphant Do you still need this feature?

**Comment by turkeyphant** [comment]
I don't use rc as much but it would be much appreciated.

**Comment by kizilcahmet98** [comment]
@gary-kim  

Any progress on the subject?

**Comment by kizilcahmet98** [comment]
@turkeyphant 

What solution did you use? Can you share?

**Comment by turkeyphant** [comment]
> @turkeyphant
> 
> What solution did you use? Can you share?

No solution I'm afraid. I just don't use rc if possible.

**Comment by Galdanwing** [comment]
Hi, is there any progress on this? Sorry for the necro

**Comment by ncw** [comment]
[The stats now do include the eta](https://rclone.org/rc/#core-stats) so I'm going to close this. If anyone thinks there are still stats missing, please make a new issue describing what is missing - thanks.
