### ISSUE TITLE
Folder creation and deletion fails for Digital Ocean S3 spaces.

### ISSUE THREAD

**Issue by jpbakke** [rclone/rclone#3130]
#### What is the problem you are having with rclone?
When workin with S3 compatible digital ocean spaces, I cannot create (via mkdir) or delete (via purge, rmdir, rmdirs) folders.  If I use a sync or copy, the folder structure is correct.  If I purge a folder with files and subfolders, the files are deleted, but all the folders remain.  If I try to rmdir or rmdirs folders that are empty, I don't get any error but the folder are not removed.  If I manually use mkdir to create a new folder, that folder does not get created.  I've verified that I can create an delete folders without any issues in 'S3 Browser' (windows application) and using the linux s3cmd application.

#### What is your rclone version (output from `rclone version`)
1.47.0

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux Ubuntu 18.04 64-bit

####  Which cloud storage system are you using? (eg Google Drive)
Digital Ocean spaces

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
mkdir
purge
rmdir 
rmdirs

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp 
I've attached a full debug log of my results
[problem.txt](https://github.com/ncw/rclone/files/3113728/problem.txt)

The file sync and copy features work correctly.  But when I try to purge or delete a folder with contents, rclone leaves the folders behind no matter what I try.

-Jeff

**Comment by jpbakke** [comment]
Further testing: the 'delete' command appears to fail for both folders (expected) AND a regular file.

**Comment by jpbakke** [comment]
Install current beta version: v1.47.0-019-g3d475dc0-beta
Same problems... mkdir fails, rmdir fails.

**Comment by ncw** [comment]
How did the folders get created?

S3 compatible storage systems don't actually have the concept of a folder.  They are key value stores.  By convention the key is a path name `dir/subdir/file` but there is no need to create a "directory" `dir/sub/`.

This works very well, but means you can't have empty directories.

To work around this, some tools create 0 length files called `dir/sub/` which are known as directory markers.

Rclone reads these directory markers as directories, but when you do `rmdir` it doesn't delete them as rclone's preferred mode of operation is not to use directory markers.

So if you upload things with rclone, it won't create directory markers (which saves objects and operations) and everything will work just fine.

**Comment by jpbakke** [comment]
Aha, I think you've provided a useful piece of information.  If I copy or sync files that create 'folders' using RClone, I appear to be able to purge the 'folders' correctly.  If I manually create the 'folder' objects using S3 browser, then apparently its doing something different to represent the 'folder' than Rclone and rclone doesn't appear to be able to delete the folders.

I need to go back and do more testing, but this might solve my problem.  Thanks.

-Jeff
