### ISSUE TITLE
Google Drive - Server Side Copy Duplicates Folder with --drive-shared-with-me

### ISSUE THREAD

**Issue by animosity22** [rclone/rclone#3132]
#### What is the problem you are having with rclone?
If you run a server side copy twice, you get two of the same folders and it repeats.

#### What is your rclone version (output from `rclone version`)
rclone v1.47.0
- os/arch: linux/amd64
- go version: go1.12.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
ArchLinux

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy --drive-shared-with-me GD:Test GD:Countries/Test -vv

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
rclone copy --drive-shared-with-me GD:Test GD:Countries/Test -vv
2019/04/24 18:59:10 DEBUG : rclone: Version "v1.47.0" starting with parameters ["rclone" "copy" "--drive-shared-with-me" "GD:Test" "GD:Countries/Test" "-vv"]
2019/04/24 18:59:10 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2019/04/24 18:59:11 INFO  : Google drive root 'Countries/Test': Waiting for checks to finish
2019/04/24 18:59:11 INFO  : Google drive root 'Countries/Test': Waiting for transfers to finish
2019/04/24 18:59:17 INFO  : (Public) U22.17.0.1 - Mastery Checklist by ／u／Sekwah.xlsx: Copied (server side copy)
2019/04/24 18:59:17 INFO  : TestSheet.xlsx: Copied (server side copy)
2019/04/24 18:59:17 INFO  : Test2.xlsx: Copied (server side copy)
2019/04/24 18:59:17 INFO  :
Transferred:   	       off / off, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            3 / 3, 100%
Elapsed time:        7.7s

2019/04/24 18:59:17 DEBUG : 8 go routines active
2019/04/24 18:59:17 DEBUG : rclone: Version "v1.47.0" finishing with parameters ["rclone" "copy" "--drive-shared-with-me" "GD:Test" "GD:Countries/Test" "-vv"]
[felix@gemini scripts]$ rclone copy --drive-shared-with-me GD:Test GD:Countries/Test -vv
2019/04/24 18:59:23 DEBUG : rclone: Version "v1.47.0" starting with parameters ["rclone" "copy" "--drive-shared-with-me" "GD:Test" "GD:Countries/Test" "-vv"]
2019/04/24 18:59:23 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2019/04/24 18:59:24 INFO  : Google drive root 'Countries/Test': Waiting for checks to finish
2019/04/24 18:59:24 INFO  : Google drive root 'Countries/Test': Waiting for transfers to finish
2019/04/24 18:59:28 INFO  : Test2.xlsx: Copied (server side copy)
2019/04/24 18:59:29 INFO  : (Public) U22.17.0.1 - Mastery Checklist by ／u／Sekwah.xlsx: Copied (server side copy)
2019/04/24 18:59:29 INFO  : TestSheet.xlsx: Copied (server side copy)
2019/04/24 18:59:29 INFO  :
Transferred:   	       off / off, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            3 / 3, 100%
Elapsed time:        6.3s

2019/04/24 18:59:29 DEBUG : 8 go routines active
2019/04/24 18:59:29 DEBUG : rclone: Version "v1.47.0" finishing with parameters ["rclone" "copy" "--drive-shared-with-me" "GD:Test" "GD:Countries/Test" "-vv"]
```

![image](https://user-images.githubusercontent.com/5088712/56699411-514a7200-66c3-11e9-915a-f0de0ac533c0.png)

**Comment by RicardoCip** [comment]
Has anyone got a solution for rclone to duplicate the output directory each time they try to copy a folder that is shared with me?

**Comment by Makeshift** [comment]
I ended up with several thousand duplicate folders today from this one - ouch. I've had the dedupe running now for a few hours...

Being that this only seems to happen with the `--drive-shared-with-me` flag enabled, I found it odd that it would affect things that don't require it to be enabled (like team drives, I had it enabled accidentally). I also found it a bit odd that it didn't affect my first team drive, but went absolutely insane on my second one.

**Comment by animosity22** [comment]
@Makeshift  - the bug report I have is for using the flag. You can share on a Google Drive or on a Team Drive (Shared Drive).

**Comment by Makeshift** [comment]
@animosity22 Ah, it didn't occur to me you could share individual folders in a team drive. That makes sense, thanks!

**Comment by ncw** [comment]
> rclone copy --drive-shared-with-me GD:Test GD:Countries/Test -vv

The reason this creates a duplicate is

- the `--drive-shared-with-me` flag applies to **both** the source and the destination google drive
- when rclone creates the directory in the dest, it can't see it the next time you run the copy as it is using `--drive-shared-with-me` in the dest so it creates another

This suggests a work-around, create another remote with the `shared_with_me = true` in it. then do `rclone copy drivesharedwithme: drive:`. I've tested that and it works.

Another solution would be to allow all files to be visible in `--drive-shared-with-me` not just the shared files. That would work but would be quite a big change.

A final idea I has was to modify the remote syntax so you could do this which would set the `--drive-shared-with-me` flag a bit more precisely.

    rclone copy drive,shared_with_me=true: drive:

**Comment by l0g4n7** [comment]
> > rclone copy --drive-shared-with-me GD:Test GD:Countries/Test -vv
> 
> The reason this creates a duplicate is
> 
> * the `--drive-shared-with-me` flag applies to **both** the source and the destination google drive
> * when rclone creates the directory in the dest, it can't see it the next time you run the copy as it is using `--drive-shared-with-me` in the dest so it creates another
> 
> This suggests a work-around, create another remote with the `shared_with_me = true` in it. then do `rclone copy drivesharedwithme: drive:`. I've tested that and it works.
> 
> Another solution would be to allow all files to be visible in `--drive-shared-with-me` not just the shared files. That would work but would be quite a big change.
> 
> A final idea I has was to modify the remote syntax so you could do this which would set the `--drive-shared-with-me` flag a bit more precisely.
> 
> ```
> rclone copy drive,shared_with_me=true: drive:
> ```
![Capture](https://user-images.githubusercontent.com/65089059/81482879-fb0f8900-925b-11ea-8c68-4992fa8398ff.PNG)

 it doesn't work. syntax error.

**Comment by darthShadow** [comment]
> it doesn't work. syntax error.

That was just a proposal of something that could be implemented 😄
It hasn't been done yet.

**Comment by l0g4n7** [comment]
> > it doesn't work. syntax error.
> 
> That was just a proposal of something that could be implemented 😄
> It hasn't been done yet.

ow. sorry. new here. 

I tried adding a separate remote of the same drive with shared with me true in config. 

rclone copy drivesharedwithme: drive:

But this one doesn't perform a server side copy.

**Comment by calisro** [comment]
These questions are better answered in the forum.  But you can try adding --drive-server-side-across-configs

**Comment by l0g4n7** [comment]
> These questions are better answered in the forum. But you can try adding --drive-server-side-across-configs

would u tell a bit details??

**Comment by animosity22** [comment]
> > These questions are better answered in the forum. But you can try adding --drive-server-side-across-configs
> 
> would u tell a bit details??

He's saying post in the forums as it's not part of the issue. If you have a use question, please use the https://forums.rclone.org

**Comment by ncw** [comment]
See also: https://forum.rclone.org/t/starred-only-duplicate-folders/19347 - this affects `--drive-starred-only` also.

**Comment by arbarbosa1979** [comment]
> 
> 
> > > These questions are better answered in the forum. But you can try adding --drive-server-side-across-configs
> > 
> > 
> > would u tell a bit details??
> 
> He's saying post in the forums as it's not part of the issue. If you have a use question, please use the https://forums.rclone.org

You put one more letter (s) in the url:
[(https://forum.rclone.org)](https://forum.rclone.org) and not [(https://forums.rclone.org)](https://forums.rclone.org)

**Comment by animosity22** [comment]
Fixed.

**Comment by pri-pro** [comment]
I faced the same problem with version v1.54.0-beta.5062.db2c38b21
temporary fix: making a shortcut, and skipping (--drive-shared-with-me) flag.
Looks like this bug still exists

**Comment by animosity22** [comment]
@pri-pro  - That's why the issue is still open as it still exists.

**Comment by debek** [comment]
I have got the same issue. Does anybody know how to solve it temporary?

**Comment by darthShadow** [comment]
Was answered by ncw earlier in the thread:

> create another remote with the shared_with_me = true in it. then do rclone copy --drive-server-side-across-configs drivesharedwithme: drive:

**Comment by debek** [comment]
> Was answered by ncw earlier in the thread:
> 
> > create another remote with the shared_with_me = true in it. then do rclone copy --drive-server-side-across-configs drivesharedwithme: drive:

dedupe is now a solution when somebody want to copy lof of 1GB files :)

**Comment by darthShadow** [comment]
And this solution doesn't require dedupe.

**Comment by ncw** [comment]
This problem is now fixed with the new connection string syntax added to v1.55

    rclone copy GD,shared_with_me:Test GD:Countries/Test -vv

This means is is possible to add the `shared_with_me` to just the source on the command line.

I will hence close this issue!
