### ISSUE TITLE
Trailing characters with –stats-one-line -P –stats

### ISSUE THREAD

**Issue by MagTun** [rclone/rclone#3136]
#### What is the problem you are having with rclone?
When the stats created by  `–stats-one-line -P –stats` are updated every couple of second, there are trailing characters (cf the yellow highlight on the picture). 
![aaa](https://user-images.githubusercontent.com/15843700/56744887-a052de80-6779-11e9-83f0-8a5ffc779c9c.png)

I was able to reproduce the bug  on cmd and powershell and with a config with a password and without a password (cf [the thread on the forum](https://forum.rclone.org/t/trailing-characters-with-stats-one-line-p-stats/9600))

#### What is your rclone version (output from `rclone version`)
rclone v1.47.0
- os/arch: windows/amd64
- go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 version 1809 build 17763.437 (I had no such bug when I was on Windows 10 1803)

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive  +  DropBox 

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone sync “local folder” “remote name:remote folder” --log-file “path to log” --log-level INFO --delete-after --copy-links --stats-one-line -P --stats 5s`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Doesn't apply

**Comment by ncw** [comment]
Is it possible this is a Windows bug?  I'm not familiar with the Windows 10 build numbers - is `Windows 10 version 1809 build 17763.437` a stable release?

I don't see this bug in Windows 7 or Windows 2016 Server (all I have access to right now).

**Comment by ncw** [comment]
This should be fixed in v1.50 - if not please ping me here

**Comment by MagTun** [comment]
I tested it in a couple of different situation and it seems that it's fixed. I will come back to you if I see it again! In any case, thanks a lot for your time!

**Comment by ncw** [comment]
> I tested it in a couple of different situation and it seems that it's fixed. I will come back to you if I see it again! In any case, thanks a lot for your time!

Thanks for testing :-)
