### ISSUE TITLE
drive: update API usage to adapt to changes in the v3 API

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#3139]
Adapt to [changes announced by google for the Drive API](https://cloud.google.com/blog/products/application-development/upcoming-changes-to-the-google-drive-api-and-google-picker-api).

I don't think we will need to so anything for the drive downloads, but the Drives API needs looking at, and how exactly that interacts with teamdrives.

> Next, we’re introducing a new Drive API resource collection, called “Drives,” to replace the “Team Drives” resource collection. This new resource collection can help you create, delete, get, list and update your shared drives, and features all the same fields, resources and available methods as the “Team Drives” resource collection. If you have been using the “Team Drives” resource collection in your applications, consider migrating as soon as possible as all related fields for Drive API , Drive Activity API and Google Picker API, will no longer be supported starting June 1, 2020.
> 
> It’s also important to note that starting June 1, 2020, applications will no longer be able to opt-in to support Team Drives. This means that Team Drive items, including both Team Drives and files within a Team Drive, will be returned in all relevant requests, if applicable, so you’ll need to support this functionality by default

@B4dM4n thoughts on these?

**Comment by Admin9705** [comment]
Awesome @ncw - For all the members at https://pgblitz.com, we love your work!  More random headaches from no where.  We'll be able to provide feedback and testing when we can!

**Comment by danjames92** [comment]
@Admin97

> Awesome @ncw - For all the members at https://pgblitz.com, we love your work! More random headaches from no where. We'll be able to provide feedback and testing when we can!

You're not contributing to the conversation in any meaningful way except advertising your service. Please do not waste ncw's time with this garbage in future.
