### ISSUE TITLE
MEGA.nz: Generating folder link while transferring causes panic runtime error

### ISSUE THREAD

**Issue by AssRap3r** [rclone/rclone#3140]
#### What is the problem you are having with rclone?
Generating a folder link via the mega web UI results in a panic runtime error which stops transfers

#### What is your rclone version (output from `rclone version`)
rclone v1.47.0
- os/arch: linux/amd64
- go version: go1.12.4

(also tested with rclone v1.47.0-019-g3d475dc0-beta)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64

####  Which cloud storage system are you using? (eg Google Drive)
MEGA

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -v --stats 1s --transfers 8 copy DSM dsm:

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd06645]

goroutine 115 [running]:
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.blockDecrypt(0x0, 0x0, 0xc0005a2220, 0x10, 0x12, 0xc0005a2220, 0x10, 0x12, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/utils.go:202 +0x205
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.(*Mega).addFSNode(0xc000229600, 0xc00055df60, 0x8, 0xc00055df68, 0x8, 0xc00055df70, 0xb, 0x1, 0xc0005a21a0, 0x16, ...)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/mega.go:715 +0x327
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.(*Mega).processAddNode(0xc000229600, 0xc0001f2420, 0x159, 0x160, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/mega.go:1639 +0x1e6
github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.(*Mega).pollEvents(0xc000229600)
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/mega.go:1817 +0xae0
created by github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega.(*Mega).getFileSystem
        /home/travis/gopath/src/github.com/ncw/rclone/vendor/github.com/t3rm1n4l/go-mega/mega.go:842 +0x3da

#### Steps to reproduce
1) Upload files to MEGA
2) Create a new folder via web interface
3) Generate link for the folder (Right click -> Get link)
4) Watch rclone loses its shit like a misgendered social studies student

this does not happen with [megous MEGACMD](https://megatools.megous.com/).

**Comment by ncw** [comment]
This will be rclone failing to understand a message that the mega sent it.

Note that the mega protocol isn't documented at all so the library rclone uses has been reverse engineered from the C++ code

It shouldn't have paniced though!

here is a version of rclone which should report an error rather than panic - can you give that a go?

https://beta.rclone.org/branch/v1.47.0-024-gfd6ac9ee-fix-3140-mega-panic-beta/ (uploaded in 15-30 mins)

**Comment by AssRap3r** [comment]
New error: 

2019/04/26 21:28:21 INFO  : *go-mega*: pollEvents: Error processing event "t" '{"a":"t","i":"RUhRPfipgO","t":{"f":[{"h":"7g9QxAKD","p":"f1sxGAbB","u":"S4ELTQis8To","t":1,"a":"jz5k4lo70UcQfjbdj1fOKA","k":"7g9QxAKD:BNFEtk7a_b6WnJD24ky5qg","ts":1556306897}],"u":[{"u":"S4ELTQis8To","m":"g8gi74nc4950t9t7upijgi8dyf0qpe@guerrillamailblock.com","m2":["g8gi74nc4950t9t7upijgi8dyf0qpe@guerrillamailblock.com"]}]},"ou":"S4ELTQis8To"}': crypto/aes: invalid key size 0

the upload continues this time :^)

**Comment by ncw** [comment]
I've merged the fix to the crash to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.48

This really needs a proper fix so that rclone interprets the message properly but this will make rclone usable

**Comment by NathanielHill** [comment]
New rclone user. Also experiencing this problem.

**Comment by ncw** [comment]
> New rclone user. Also experiencing this problem.

If you download [the latest beta](https://beta.rclone.org) you should find it is fixed @NathanielHill

**Comment by ivandeex** [comment]
@NathanielHill 
This bug is reported against obsolete version of rclone. Can you reproduce it with rclone 1.54?

**Comment by ivandeex** [comment]
Resolved. Closing.
