### ISSUE TITLE
rclone v1.47 - Windows builds using old go version.

### ISSUE THREAD

**Issue by Nurple** [rclone/rclone#3141]
Reposting issue here, as asked on twitter.

Heya,

The Windows builds of rclone v1.47 are using go1.11, and not go1.12.4 like the Linux builds for example.

rclone v1.47.0
- os/arch: windows/amd64
- go version: go1.11

----
Original msg.
https://twitter.com/AlmightyNurple/status/1121606164733673472

**Comment by ncw** [comment]
v1.47.0 was indeed build with go1.11
- https://ci.appveyor.com/project/ncw/rclone/builds/23821679

It seems that Appveyor is now building with go1.12.3
- https://ci.appveyor.com/project/ncw/rclone/builds/24098779

The specific issue  of Appveyor being behind in go version appears to have been fixed here: https://github.com/appveyor/ci/issues/2875

There is a work-around in that ticket which would enable us to pick a specific version of go - perhaps we should use that.

Or maybe ditch the increasingly unreliable Travis and Appveyor both for Azure pipelines...

**Comment by ncw** [comment]
This is now fixed after moving to GitHub actions
