### ISSUE TITLE
script start rclone mount auto docker ubuntu 18.04

### ISSUE THREAD

**Issue by leopkks** [rclone/rclone#3145]
rclone mount --log-file "/tmp/rclone.log" --log-level INFO --allow-non-empty --allow-other --default-permissions --fuse-flag sync_read --tpslimit 8 --tpslimit-burst 5 --dir-cache-time=1m --cache-chunk-size=32M  --cache-info-age=168h --cache-workers=5 --buffer-size=256M --attr-timeout=1s --vfs-read-chunk-size=2M --vfs-read-chunk-size-limit=5G --vfs-cache-max-age=5m --vfs-cache-mode=writes --cache-dir "/home/cache" gdrive: /home/gdrive --config "/root/.config/rclone/rclone.conf"

i I need a script
to start
the top command when starting the docker container
thank you
I ask for a step by step command

**Comment by animosity22** [comment]
You have a bunch of stuff that doesn't go together in a mount command there. 

allow-non-empty  - is bad as it allows you to over mount things
why is dir-cache-time 1m?
buffer-size if you are using the cache backend should be 0M as it uses its own buffering/chunk management so that is waste.
all the vfs-commands do nothing if you are using the cache backend so I'd remove them.

Do you have a docker with rclone installed in it?

**Comment by leopkks** [comment]
Thanks for answering
I'll explain better
I have a centos 6.10 server
where you work with webuzo
I created a virtual machine
in docker
with a container with ubuntu version 18

use it for a video system
where it accesses an HD without leaving anything on the disk
only cache when sending to the server
It has to be quick to update it to appear
in virtual HD created
does not work with synchronization
it is accessed let's say it has a video in mp4
it convert to mvk
to make the video lighter.

if you have a better command
leave attached.


the rclone server issue
I have it installed inside ubuntu 18

I need a command to mount it when restarting the container
automatically. when the system starts
mounts the google drive external hard drive configuration.

need rclone commands
that works inside docker
or commands where it is feasible for a google drive HD
without hiding disk
because vps has only 4 of RAM
and 30GB of SSD
google drive has more than 500 GB of files.

**Comment by animosity22** [comment]
Here is an example systemd service file.

```
[felix@gemini system]$ cat gmedia-rclone.service
[Unit]
Description=RClone Service
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
Environment=RCLONE_CONFIG=/opt/rclone/rclone.conf

ExecStart=/usr/bin/rclone mount gcrypt: /GD \
--allow-other \
--dir-cache-time 96h \
--drive-chunk-size 32M \
--log-level INFO \
--log-file /opt/rclone/logs/rclone.log \
--timeout 1h \
--umask 002 \
--rc
ExecStop=/bin/fusermount -uz /GD
Restart=on-failure
User=felix
Group=felix

[Install]
WantedBy=multi-user.target
```

You can always tweak to your system config.

**Comment by leopkks** [comment]
Friend you could
make the commands
I do not understand much of rclone.
the commands that I took up I informed
Could you do in this example that you spoke now?
I do not understand
so I understood the code that you sent me

it looks like it plays the Google Drive files
to the server
as I informed
google drive has more than 500 gb
the server only has 30 GB HD

**Comment by animosity22** [comment]
Let me know if you have a question on this still and we can help out. If you post to the forums, it'll have more eyes on it.
