### ISSUE TITLE
Webdav 406 error - NextCloud

### ISSUE THREAD

**Issue by PyRo1509** [rclone/rclone#3159]
#### What is the problem you are having with rclone?

Getting a 406 error when doing a copy operation

#### What is your rclone version (output from `rclone version`)

2019/05/02 15:33:40 DEBUG : rclone: Version "v1.47.0" starting with parameters ["rclone" "copy" "-P" "-vv" "--dump" "requests,responses" "--checkers" "1" "--transfers" "1" "--low-level-retries" "1" "XXXXXXXX:/Nextcloud.mp4" "./"]

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
Bit: 64 of the best bits

####  Which cloud storage system are you using? (eg Google Drive)

NextCloud

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy -P -vv --dump requests,responses --checkers 1 --transfers 1 --low-level-retries 1 XXXXXX:/Nextcloud.mp4 ./

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2019/05/02 15:33:40 DEBUG : rclone: Version "v1.47.0" starting with parameters ["rclone" "copy" "-P" "-vv" "--dump" "requests,responses" "--checkers" "1" "--transfers" "1" "--low-level-retries" "1" "XXXXXX:/Nextcloud.mp4" "./"]
2019/05/02 15:33:40 DEBUG : Using config file from "/home/XXXXXX/.config/rclone/rclone.conf"
2019/05/02 15:33:40 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/05/02 15:33:40 DEBUG : HTTP REQUEST (req 0xc000311b00)
2019/05/02 15:33:40 DEBUG : PROPFIND /remote.php/webdav/Nextcloud.mp4 HTTP/1.1
Host: XXXXXX
User-Agent: rclone/v1.47.0
Content-Length: 287
Authorization: XXXX
Depth: 1
Accept-Encoding: gzip

<?xml version="1.0"?>
<d:propfind  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:prop>
  <d:displayname />
  <d:getlastmodified />
  <d:getcontentlength />
  <d:resourcetype />
  <d:getcontenttype />
  <oc:checksums />
 </d:prop>
</d:propfind>
2019/05/02 15:33:40 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/05/02 15:33:41 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/05/02 15:33:41 DEBUG : HTTP RESPONSE (req 0xc000311b00)
2019/05/02 15:33:41 DEBUG : HTTP/1.1 406 Not Acceptable
Transfer-Encoding: chunked
Cf-Ray: 4d0d7550df451eb1-SJC
Connection: keep-alive
Content-Type: text/html; charset=iso-8859-1
Date: Thu, 02 May 2019 22:33:41 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cfduid=XXXXXX; expires=Fri, 01-May-20 22:33:41 GMT; path=/; domain=.XXXXXX; HttpOnly; Secure
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload

e2
<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>
0

2019/05/02 15:33:41 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/05/02 15:33:41 Failed to create file system for "XXXXXX:/Nextcloud.mp4": read metadata failed: 406 Not Acceptable
```

Config File:

```
[XXXXXXX]
type = webdav
url = https://DOMAIN/remote.php/webdav/
vendor = nextcloud
user = USER
pass = ENCRYPTEDPASSSSSSSSSWORD

```

**Comment by ncw** [comment]
I take it listing and so forth works OK?

The error seems to be

> An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.

I'm pretty sure this is a mod_security rule problem...

Did you configure mod_security?  Can you try disabling it?

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
