### ISSUE TITLE
`-l` flag doesn't work with B2 or S3

### ISSUE THREAD

**Issue by Jwink3101** [rclone/rclone#3163]
#### What is the problem you are having with rclone?

The flag `-l` does not seem to work with B2 and S3 (tested on Wasabi) remotes. From #1152, I would expect that this is working now. And from the docs:

>      -l, --links  Translate symlinks to/from regular files with a '.rclonelink' extension

#### What is your rclone version (output from `rclone version`)

Tested with:
```
rclone v1.46
- os/arch: darwin/amd64
- go version: go1.11.5
```

and

```
rclone v1.47.0-032-gb9e16b36-beta
- os/arch: darwin/amd64
- go version: go1.12.4
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS 1.14.4 and 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

B2 and Wasabi vs S3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

I am trying to copy a symlink. 

    $ rclone copyto -l alink b2:bucket/newlink

(or something like that)

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

When I do it with no `-l` flag:

```
2019/05/03 14:45:19 ERROR : : error reading source directory: failed to read directory "": readdirent: invalid argument
2019/05/03 14:45:19 ERROR : Attempt 1/3 failed with 1 errors
2019/05/03 14:45:19 ERROR : : error reading source directory: failed to read directory "": readdirent: invalid argument
2019/05/03 14:45:19 ERROR : Attempt 2/3 failed with 1 errors
2019/05/03 14:45:19 ERROR : : error reading source directory: failed to read directory "": readdirent: invalid argument
2019/05/03 14:45:19 ERROR : Attempt 3/3 failed with 1 errors
```

When I use `-l` 

```
2019/05/03 14:45:41 ERROR : Attempt 1/3 failed with 0 errors and: object not found
2019/05/03 14:45:41 ERROR : Attempt 2/3 failed with 0 errors and: object not found
2019/05/03 14:45:41 ERROR : Attempt 3/3 failed with 0 errors and: object not found
2019/05/03 14:45:41 Failed to copy: object not found
```

And, for the record, `-L` works but that is not the behavior I am looking for

**Comment by ncw** [comment]
If you want to copy an individual link, then you will have to name it like this

    rclone copyto -l alink.rclonelink b2:bucket/newlink

If you just copy the source directory then it should work.

**Comment by Jwink3101** [comment]
I am trying to copy a list of specified files so it really looks like

    rclone copy --include-from list_of_files rootdir b2:bucket

where `list_of_files` looks like

```
/file1
/alink
```

etc.

But you're saying my `list_of_files` should look like

```
/file1
/alink.rclonelink
```

where I manually add the extension to the file?

Either way, I just tested:

all of the following and it it didn't work:

```
$ rclone copyto -l alink backblaze:BUCKET/link
$ rclone copyto -l alink.rclonelink backblaze:BUCKET/link
$ rclone copyto -l alink.rclonelink backblaze:BUCKET/link.rclonelink
$ rclone copyto -l alink backblaze:BUCKET/link.rclonelink
```

I guess I am (a) missing something, (b) the documentation and expected behavior is very unclear, (c) this really is a bug, and/or (d) this just isn't possible.

From the documentation, what I would have expected is that if rclone encounters any symlink with `-l`, it makes the `.rclonelink` file when copying it. Is that not the expected behavior?

**Comment by Jwink3101** [comment]
I do see it works when you copy an entire directory. I think this is a bug then. It seems to me like it should behave the same regardless of copying a single file or a directory.

Furthermore, if I do what I noted with `--include-from` it still doesn't work:

    $ rclone copy -l --files-from list_of_files . backblaze:BUCKET

with the link called `alink` and `list_of_files` is:

```
/alink
```

Interesting, I ran with `-vv` and got:

    2019/05/07 07:10:48 DEBUG : alink.rclonelink: Excluded

which is odd since I didn't name the file with `.rclonelink`

So, based on this, I renamed the file `alink.rclonelink` and changed `list_of_files` accordingly and now it worked.

Based on this empirical testing, it seems like the behavior is: (all for `-l` flag)

* when copying/syncing a directory and rclone encounters a symlink, automatically rename the file on the remote end, leaving the local copy untouched
* When copying a single file, or list of files (`copy FILE` or `copy --include-from list_of_files`) the symlink must be *already* named with  `.rclonelink` in order to be copied

Personally, I think that is very not-expected behavior. And it is very inconsistent. When rclone encounters a link with `-l` it shouldn't behave differently (and with a good bit of effort to rename everything)

Please don't get me wrong, I am amazed at the power of rclone and have been really happy using it and incorporating it into [my code](https://github.com/Jwink3101/PyFiSync/tree/rclone) (still in testing phase so it's not in master yet). I just want to make sure I understand the behavior

**Comment by ncw** [comment]
If you do `rclone ls -l src` you'll see that rclone "sees" the symlinks as `symlink.rclonelink` with the `-l` flag.  That explains what you are seeing.

It would be relatively easy to put in a workaround if you ask for a file called "symlink" and there isn't one, rclone could look for one called "symlink.rclonelink" if `-l` is in effect and return that instead.

There is [some discussion of this](https://github.com/ncw/rclone/issues/1152#issuecomment-421952563) in the original issue.
