### ISSUE TITLE
OneDrive business WebDav protocol - Cannot list files in directory

### ISSUE THREAD

**Issue by Vigo0101** [rclone/rclone#3176]
Hello,

#### What is the problem you are having with rclone?
I have managed to connect to my corporate OneDrive business account using WebDav protocol and setting user-agent to 'Mozilla/5.0 (X11; Linux i686; rv:64.0) Gecko/20100101 Firefox/64.0'.
But directory listing fails with this error:
DEBUG : : Dir.ReadDirAll error: couldn't list files: XML syntax error on line 12: attribute name without = in element
DEBUG : /: >ReadDirAll: item=-1, err=couldn't list files: XML syntax error on line 12: attribute name without = in element
DEBUG : /: Attr: 
DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
DEBUG : : Statfs: 
DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274877906944 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>

Rclone.conf setting is as follow:
[Remote]
type = webdav
url = https://corporate-my.sharepoint.com/personal/my_email_address/Documents
vendor = sharepoint
user = me@corporate_domain
pass = encrypted_password

I have set url to /, /Documents, /Document/Forms but i still get the same error.

I cannot use OneDrive protocol as it requires Rclone to be approved by corporate admin.

Any help greatly appreciated.
Thank you.

#### What is your rclone version (output from `rclone version`)
rclone v1.47.0
- os/arch: linux/amd64
- go version: go1.12.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Kubuntu 18.04 LTS AMD64

####  Which cloud storage system are you using? (eg Google Drive)
OneDrive business

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone --user-agent 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:64.0) Gecko/20100101 Firefox/64.0' -vv --dump bodies mount Remote: /home/user_home/onedrive/

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2019/05/08 16:42:57 DEBUG : rclone: Version "v1.47.0" starting with parameters ["rclone" "--user-agent" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:64.0) Gecko/20100101 Firefox/64.0" "-vv" "mount" "Remote:" "/home/user_home/onedrive/"]
2019/05/08 16:42:57 DEBUG : Using config file from "/home/user_home/.config/rclone/rclone.conf"
2019/05/08 16:42:58 DEBUG : webdav root '': Mounting on "/home/user_home/onedrive/"
2019/05/08 16:42:58 INFO  : webdav root '': poll-interval is not supported by this remote
2019/05/08 16:42:58 DEBUG : Adding path "vfs/forget" to remote control registry
2019/05/08 16:42:58 DEBUG : Adding path "vfs/refresh" to remote control registry
2019/05/08 16:42:58 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2019/05/08 16:42:58 DEBUG : : Root: 
2019/05/08 16:42:58 DEBUG : : >Root: node=/, err=<nil>
2019/05/08 16:43:07 DEBUG : /: Attr: 
2019/05/08 16:43:07 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
2019/05/08 16:43:07 DEBUG : : Statfs: 
2019/05/08 16:43:08 ERROR : webdav root '': Statfs failed: about call failed: XML syntax error on line 12: attribute name without = in element
2019/05/08 16:43:08 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274877906944 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>

**Comment by ncw** [comment]
Can you run again with `-vv --dump bodies` and that should make things clearer what is going on.  Can you  post the result? Or at least the failing transaction?

**Comment by Vigo0101** [comment]
Hello,
Thank you for you help.
Here below the requested log after issuing following command:
rclone --user-agent 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:64.0) Gecko/20100101 Firefox/64.0' -vv --dump bodies ls Remote:
Notice that my corporate and personal data have been anonymized.
[log_rclone.txt](https://github.com/ncw/rclone/files/3166521/log_rclone.txt)

**Comment by ncw** [comment]
It looks like the authentication didn't work...

When rclone tries to use auth then it gets redirected to an HTML page for login (which explains the XML error).

@hensur since you did this support originally, have you any idea why it isn't working?  It looks correctly set up to me.

**Comment by Vigo0101** [comment]
Thank you for your comments.
OneDrive Business login process is as follow :
 - first, input corporate email address on microsoftonline.com page.
 - then, Microsoft redirects login to a corporate dedicated login page with corporate email / password.

**Comment by hensur** [comment]
I'll check it! I actually haven't used my own Account in a few months now, maybe they changed something...

**Comment by hensur** [comment]
I just looked through the first XML response, it already contains
```

**Comment by ncw** [comment]
> I'll try to implement some changes in the next few days to make sure rclone stops at the first response and detects this error message right away. I'll send a PR then.

Thanks @hensur :-)

**Comment by Vigo0101** [comment]
@hensur 
Thank you for your comments.
"encrypted_password" is here to anonymized my data in the log posted here.
In the original log, both my email address and password (not encrypted) are correct.
