### ISSUE TITLE
Moves on some mounted drives don’t work

### ISSUE THREAD

**Issue by Jwink3101** [rclone/rclone#3184]
I think this is a bug since the docs say that all drives support operations but it may be considered a feature request 

#### What is the problem you are having with rclone?

Move a file on mounts that don’t support server-side copy. 

For example, I know that when you move a B2 file, it imitates it with a download+upload+ delete.

And when you mount B2 it can copy using the same steps but doesn’t support moves. 

Like I said, I think this is a bug but may be a feature

#### What is your rclone version (output from `rclone version`)

1.46 

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

B2

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

Mount

**Comment by ncw** [comment]
Unfortunately B2 is the only remote which doesn't support server side move or server side copy.  I've talked to the B2 team about this and they are planning it, but it isn't released yet.

I don't really want to make the default mount download and upload GB files just for a rename - I think people would find that quite surprising...

If you do this, you should find renames will work, albeit with download then upload.  I could potentially put that on a flag?

```patch
diff --git a/vfs/file.go b/vfs/file.go
index a20c6d525..a16969177 100644
--- a/vfs/file.go
+++ b/vfs/file.go
@@ -109,11 +109,11 @@ func (f *File) applyPendingRename() {
 // Otherwise it will queue the rename operation on the remote until no writers
 // remain.
 func (f *File) rename(destDir *Dir, newName string) error {
-	if features := f.d.f.Features(); features.Move == nil && features.Copy == nil {
-		err := errors.Errorf("Fs %q can't rename files (no server side Move or Copy)", f.d.f)
-		fs.Errorf(f.Path(), "Dir.Rename error: %v", err)
-		return err
-	}
+	// if features := f.d.f.Features(); features.Move == nil && features.Copy == nil {
+	// 	err := errors.Errorf("Fs %q can't rename files (no server side Move or Copy)", f.d.f)
+	// 	fs.Errorf(f.Path(), "Dir.Rename error: %v", err)
+	// 	return err
+	// }
 
 	renameCall := func() error {
 		newPath := path.Join(destDir.path, newName)
```

**Comment by Jwink3101** [comment]
It really stinks that they don’t support it!

But I think at the very least, rclone should document that moves are not supported when mounted (since they do “work” with the actions)

And then, I like the flag idea but if you didn’t want to go crazy with flags, I would understand.

**Comment by ncw** [comment]
@Jwink3101 do you fancy having a go at adding a flag?  There are two bits of code that would need to be disabled for file renaming (as above) and directory renaming.

**Comment by Jwink3101** [comment]
I can take a look but it would be my first look at Golang. I may be able to reverse engineer it if I have the chance. 

I may open a second ticket, but I posted about the lack of copy API [on Reddit](https://reddit.com/r/backblaze/comments/bnvjsy/any_eta_on_b2_serverside_copy/). They asked to take a look at [their proposed API](https://www.backblaze.com/b2/docs/b2_copy_file.html). Do you have thoughts on that?

**Comment by ncw** [comment]
> I can take a look but it would be my first look at Golang. I may be able to reverse engineer it if I have the chance.

:-)

> I may open a second ticket, but I posted about the lack of copy API [on Reddit](https://reddit.com/r/backblaze/comments/bnvjsy/any_eta_on_b2_serverside_copy/). They asked to take a look at [their proposed API](https://www.backblaze.com/b2/docs/b2_copy_file.html). Do you have thoughts on that?

Nice... I responded on the Reddit thread.
