### ISSUE TITLE
new remote: qiniu

### ISSUE THREAD

**Issue by cnwangjie** [rclone/rclone#3189]
#### What is your current rclone version (output from `rclone version`)?

v1.47.0

#### What problem are you are trying to solve?

Support Qiniu object storage service.

#### How do you think rclone should be changed to solve that?

It is an OSS provider from China with global CDN.

Website: https://www.qiniu.com
Here is the link of API doc: https://developer.qiniu.com/kodo/api/1731/api-overview (Chinese only)
And it has an official golang SDK: https://github.com/qiniu/api.v7

**Comment by ncw** [comment]
Looks interesting!  

Does it have an S3 compatible API?

Is it possible for non Chinese people to use it?

Do they do free accounts?

**Comment by cnwangjie** [comment]
> Does it have an S3 compatible API?

no.

> Is it possible for non Chinese people to use it?

It requires a Chinese phone number for new register. I just found that. I didn’t need it before.

> Do they do free accounts?

Each account has free 10GB storage and 10GB download traffic.

**Comment by brentybh** [comment]
> > Does it have an S3 compatible API?
> 
> no.
> 
> > Is it possible for non Chinese people to use it?
> 
> It requires a Chinese phone number for new register. I just found that. I didn’t need it before.
> 
> > Do they do free accounts?
> 
> Each account has free 10GB storage and 10GB download traffic.

Fortunately, they have S3-compatible API available now.
See: https://developer.qiniu.com/kodo/manual/4086/aws-s3-compatible

**Comment by ivandeex** [comment]
This is one of the least active provider requests.
Closing.
