### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by diman82** [rclone/rclone#3191]
#### What is the problem you are having with rclone?
Don't know how to delete cache

#### What is your rclone version (output from `rclone version`)
v1.45

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 19.04

####  Which cloud storage system are you using? (eg Google Drive)
Onedrive for Business

**Comment by ncw** [comment]
Are you using onedrive with the rclone cache?

`rclone help flags cache-dir` will show where (in the help) rclone stores its cache by default.

You can use `rclone ncdu /path/to/cache/dir` to investigate what is in there.

**Comment by animosity22** [comment]
If you still have a question, you can post to the forums and we're more than happy to help out.
