### ISSUE TITLE
cache: server side copy not supported with --cache-tmp-upload-path

### ISSUE THREAD

**Issue by jimaan** [rclone/rclone#3206]
#### What is the problem you are having with rclone?
rclone does not seem to fallback to Copy&Delete if Move is unavailable for S3/DigitalOcean Storage Spaces. This seems supported based on: https://rclone.org/overview/#move

or maby the detection of Copy support/features fails for DigitalOcean Storage Spaces?
https://github.com/ncw/rclone/blob/cff85f0b9551881be535a4847b56742451e6b476/vfs/file.go#L112
features.Copy for DigitalOcean should exist.

When trying to move an existing file the following error is thrown:
ERROR : /dodata/data/movie.mkv.partial~: Dir.Rename error: Fs "Encrypted drive 'dodata:'" can't rename files (no server side Move or Copy)

But a copy and delete works just fine. ex.:
user@HOSTNAME:/dodata/data# touch a.txt
user@HOSTNAME:/dodata/data# mv a.txt b.txt
mv: cannot move 'a.txt' to 'b.txt': Input/output error
user@HOSTNAME:/dodata/data# cp a.txt b.txt
user@HOSTNAME:/dodata/data# rm -rf a.txt

/var/log/rclone.log contains:
ERROR : data/a.txt: Dir.Rename error: Fs "Encrypted drive 'dodata:'" can't rename files (no server side Move or Copy)

Some relevance to:
https://github.com/ncw/rclone/issues/2109 --> movie.mkv.partial~ is not uploaded yet and still exists only in local cache but will be uploaded if the timer of '--cache-tmp-wait-time' comes by.

https://github.com/ncw/rclone/issues/3184 --> As said by @ncw in this issue: 'Unfortunately B2 is the only remote which doesn't support server side move or server side copy. I've talked to the B2 team about this and they are planning it, but it isn't released yet.' which seems to indicate that S3/DigitalOcean should support the fallback if Move is not supported.

https://github.com/ncw/rclone/issues/2569 --> seems to be the original issue which fixed/supported this behavior. Commit: https://github.com/ncw/rclone/commit/a9fc86f5292005c7ce4b82e7720ea20a73ce8d9f

DigitalOcean seems to support the Bucket Object Copy operation: https://developers.digitalocean.com/documentation/spaces/#copy-object

#### What is your rclone version (output from `rclone version`)
rclone v1.47.0
- os/arch: linux/amd64
- go version: go1.12.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
- os/arch: linux/amd64 --> Ubuntu 18.04 x64

####  Which cloud storage system are you using? (eg Google Drive)
DigitalOcean Storage Spaces
remotes setup: dospaces(DO) --> cache(docache) --> crypt(dodata:)
rclone.conf:
[DO]
type = s3
provider = DigitalOcean
env_auth = false
access_key_id = KEY
secret_access_key = KEY2
endpoint = ENDPOINT

[docache]
type = cache
remote = DO:BUCKETNAME
chunk_total_size = 32G

[dodata]
type = crypt
remote = docache:
filename_encryption = standard
directory_name_encryption = true
password = PASSWORD
password2 = PASSWORD2

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
/usr/bin/rclone mount dodata: /dodata \
   --allow-other \
   --dir-cache-time=20h \
   --cache-chunk-size=10M \
   --cache-info-age=24h \
   --cache-workers=4 \
   --buffer-size=100M \
   --attr-timeout=1s \
   --log-file=/var/log/rclone.log \
   --umask 002 \
   --rc \
   --cache-tmp-upload-path "/data/rclone_upload" \
   --cache-chunk-path "/data/rclone_cache" \
   --cache-db-path "/data/rclone_db" \
   --cache-tmp-wait-time 30m \
   --log-level INFO

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Relevant Lines:

> DEBUG : data/: Lookup: name="b.txt"
 DEBUG : data/: >Lookup: node=<nil>, err=no such file or directory
 DEBUG : data/: Lookup: name="a.txt"
 DEBUG : data/: >Lookup: node=data/a.txt, err=<nil>
 DEBUG : data/a.txt: Attr: 
 DEBUG : data/a.txt: >Attr: a=valid=1s ino=0 size=0 mode=-rw-rw-r--, err=<nil>
 DEBUG : data/: Lookup: name="a.txt"
 DEBUG : data/: >Lookup: node=data/a.txt, err=<nil>
 DEBUG : data/a.txt: Attr: 
 DEBUG : data/a.txt: >Attr: a=valid=1s ino=0 size=0 mode=-rw-rw-r--, err=<nil>
 DEBUG : data/: Lookup: name="b.txt"
 DEBUG : data/: >Lookup: node=<nil>, err=no such file or directory
 DEBUG : data/: Lookup: name="b.txt"
 DEBUG : data/: >Lookup: node=<nil>, err=no such file or directory
 DEBUG : data/: Rename: oldName="a.txt", newName="b.txt", newDir=data/
 ERROR : data/a.txt: Dir.Rename error: Fs "Encrypted drive 'dodata:'" can't rename files (no server side Move or Copy)
 ERROR : data/a.txt: Dir.Rename error: Fs "Encrypted drive 'dodata:'" can't rename files (no server side Move or Copy)
 DEBUG : data/: >Rename: err=Fs "Encrypted drive 'dodata:'" can't rename files (no server side Move or Copy)

**Comment by ncw** [comment]
I suspect that the fact that the remote is capable of Copy is getting lost in the Wrapping by the cache or crypt backends.

If you leave out the cache backend (create a new remote just crypt -> digital oceal) does it work?

Both crypt and cache support Copy so this should work.

The Copy is hard wired into the s3 backend so there is no detection going wrong.

**Comment by jimaan** [comment]
> I suspect that the fact that the remote is capable of Copy is getting lost in the Wrapping by the cache or crypt backends.
> 
> If you leave out the cache backend (create a new remote just crypt -> digital oceal) does it work?
> 
> Both crypt and cache support Copy so this should work.
> 
> The Copy is hard wired into the s3 backend so there is no detection going wrong.

Hi! 

Sorry for the late reply! Just tested without the cache(crypt --> DO bucket) and this works as suspected. Using OneDrive instead of Digital Ocean(crypt --> cache --> onedrive) also works fine for renaming/moving files.

user@HOSTNAME:/dodata/data# touch a.txt
user@HOSTNAME:/dodata/data# mv a.txt b.txt

This time no error: mv: cannot move 'a.txt' to 'b.txt': Input/output error

>
;DEBUG : data/: Lookup: name="a.txt"
;DEBUG : data/: >Lookup: node=data/a.txt, err=<nil>
;DEBUG : data/a.txt: Attr:
;DEBUG : data/a.txt: >Attr: a=valid=1s ino=0 size=0 mode=-rw-rw-r--, err=<nil>
;DEBUG : data/: Lookup: name="b.txt"
;DEBUG : data/: >Lookup: node=<nil>, err=no such file or directory
;DEBUG : data/a.txt: Attr:
;DEBUG : data/a.txt: >Attr: a=valid=1s ino=0 size=0 mode=-rw-rw-r--, err=<nil>
;DEBUG : data/: Lookup: name="b.txt"
;DEBUG : data/: >Lookup: node=<nil>, err=no such file or directory
;DEBUG : data/: Lookup: name="b.txt"
;DEBUG : data/: >Lookup: node=<nil>, err=no such file or directory
;DEBUG : data/: Rename: oldName="a.txt", newName="b.txt", newDir=data/
;INFO  : data/a.txt: Copied (server side copy)
;INFO  : data/a.txt: Deleted
;DEBUG : data/a.txt: Updating file with data/b.txt 0xc0004a5720
;DEBUG : data/: >Rename: err=<nil>

**Comment by ncw** [comment]
I just looked through the source of the cache backend.

It looks like if you use `--cache-tmp-upload-path` then cache turns off support for server side Copy :-(

I'm not quite sure why that is though!

**Comment by jimaan** [comment]
Thank you for investigating further. I'm going to test without --cache-tmp-upload-path as i'm not sure i need offline uploading for now.

Anything else i can help/debug with?

**Comment by jimaan** [comment]
Tested without --cache-tmp-upload-path. For my current usecase it works great! Renaming/moving objects server side works as expected.

Also found a software fix/switch on my side that makes it so renaming is no longer required after the file is written to the cache remote. Post processing happens locally that way and the last object move to the cache remote is the final destination and name. Offline uploading works fine with this method.

**Comment by itspage** [comment]
I'm also seeing this exact issue, with an S3 compatible backend (Scaleway).

Disabling `--cache-tmp-upload-path` did the trick.

**Comment by DWSR** [comment]
I did some digging on this because it's really hampering my ability to use rclone the way that I want. I'm inexperienced in Go, so bare with me:

It appears that the way that this feature is implemented is by creating a `local` backend using the path passed to `tmp_upload_path`. That is done here: https://github.com/rclone/rclone/blob/master/backend/cache/cache.go#L486

Based on my very technical and complex print statement debugging, I believe the `local` backend does not implement (or flag itself as having implemented) the `Copy` feature.

Based on the above pieces of information when the `cache` backend figures out which features are supported, it "subtracts" the unsupported features of the `local` backend from the features of the wrapped backend [here](https://github.com/rclone/rclone/blob/master/backend/cache/cache.go#L522). Thus, even though various remote backends (e.g. `b2`, `s3`) support server side copy, `cache` with `tmp_upload_path` specified does not.

Now, as to how to fix this? I mean, the most straightforward approach would be to implement the Copy feature on the `local` backend (I'm surprised this isn't there already!), but I have no idea how to do that. Hopefully someone with better knowledge of Go and/or this project can easily spot how to do this, otherwise I'll probably take a stab at it at some point.

**Comment by ncw** [comment]
> I did some digging on this because it's really hampering my ability to use rclone the way that I want. I'm inexperienced in Go, so bear with me:

:-)

> It appears that the way that this feature is implemented is by creating a `local` backend using the path passed to `tmp_upload_path`. That is done here: https://github.com/rclone/rclone/blob/master/backend/cache/cache.go#L486

So far so good.

> Based on my very technical and complex print statement debugging, I believe the `local` backend does not implement (or flag itself as having implemented) the `Copy` feature.

That is correct.

I'm a big fan of debugging with print statements myself ;-)
 
> Based on the above pieces of information when the `cache` backend figures out which features are supported, it "subtracts" the unsupported features of the `local` backend from the features of the wrapped backend [here](https://github.com/rclone/rclone/blob/master/backend/cache/cache.go#L522). Thus, even though various remote backends (e.g. `b2`, `s3`) support server side copy, `cache` with `tmp_upload_path` specified does not.

OK

> Now, as to how to fix this? I mean, the most straightforward approach would be to implement the Copy feature on the `local` backend (I'm surprised this isn't there already!), but I have no idea how to do that. Hopefully someone with better knowledge of Go and/or this project can easily spot how to do this, otherwise I'll probably take a stab at it at some point.

The local backend doesn't have `Copy` because rclone already has some very well tested code to do copies and there isn't a quicker way of doing it that just using that code, so not implementing copy is the right thing to do. However if you do implement Copy but return the error `fs.ErrorCantCopy` then rclone will use its fallback Copy as if you hadn't implemented Copy at all.

Perhaps what we should do is remove the resetting of copy here

https://github.com/rclone/rclone/blob/4006345cfbe8ef81554b0fc79aaeb765e9fbc064/backend/cache/cache.go#L523-L525

An instead in Copy if `src` is on the tempFs (so is a local object) then just return `fs.ErrorCantCopy`...

https://github.com/rclone/rclone/blob/4006345cfbe8ef81554b0fc79aaeb765e9fbc064/backend/cache/cache.go#L1528

So how to detect `src` is on the tempFs... Probably `src.Fs() == f.tempFs` is the easiest way.

So I think you need something like this - completely untested ;-)

```diff
diff --git a/backend/cache/cache.go b/backend/cache/cache.go
index 8b1263cad..98ebe79b0 100644
--- a/backend/cache/cache.go
+++ b/backend/cache/cache.go
@@ -520,9 +520,6 @@ func NewFs(name, rootPath string, m configmap.Mapper) (fs.Fs, error) {
 	// override only those features that use a temp fs and it doesn't support them
 	//f.features.ChangeNotify = f.ChangeNotify
 	if f.opt.TempWritePath != "" {
-		if f.tempFs.Features().Copy == nil {
-			f.features.Copy = nil
-		}
 		if f.tempFs.Features().Move == nil {
 			f.features.Move = nil
 		}
@@ -1533,6 +1530,9 @@ func (f *Fs) Copy(ctx context.Context, src fs.Object, remote string) (fs.Object,
 		fs.Errorf(src, "source remote (%v) doesn't support Copy", src.Fs())
 		return nil, fs.ErrorCantCopy
 	}
+	if f.opt.TempWritePath != "" && src.Fs() == f.tempFs {
+		return nil, fs.ErrorCantCopy
+	}
 	// the source must be a cached object or we abort
 	srcObj, ok := src.(*Object)
 	if !ok {
```

I note immediately after that code is 

```go
	// the source must be a cached object or we abort
	srcObj, ok := src.(*Object)
	if !ok {
		fs.Errorf(srcObj, "can't copy - not same remote type")
		return nil, fs.ErrorCantCopy
	}
```

So actually just removing the Copy masking would do the same thing modulo an ugly error message.
