### ISSUE TITLE
Add Auth-msi to Azure blob Storage backend

### ISSUE THREAD

**Issue by MasterKuat** [rclone/rclone#3213]
#### What problem are you are trying to solve?
We need to rotate access key of our azure blob storage, so we need to change configuration in rclone as often as key's change.

#### How do you think rclone should be changed to solve that?
Azure provide AAD managed identity in order to retrieve Access key from storage account so we do not need storing key in rclone config.
More information on MSI : https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-msi

**Comment by ncw** [comment]
This seems like a good idea.  This is the library we use: https://github.com/Azure/azure-storage-blob-go and here are [the docs](https://godoc.org/github.com/Azure/azure-storage-blob-go/azblob).

Any ideas how we would configure the SDK to do AAD/MSI?

@sandeepkru ?

**Comment by sandeepkru** [comment]
Sorry for late response and also got disappeared for last few months, this definitely sounds like a good idea, I'm not sure if this supported in `go sdk` yet. I'll dig more into this and update with details.

**Comment by sandeepkru** [comment]
Based on initial investigation, it doesn't look like supported to me. I've opened up an issue with client SDK team, will update more details when we hear from them.

**Comment by symgryph** [comment]
I was wondering if this actually got done?

**Comment by backerman** [comment]
The current SDK supports OAuth but doesn't actually get the token. On the gripping hand, azcopy does support MSI authentication and is MIT-licensed, so the [relevant bits](https://github.com/Azure/azure-storage-azcopy/blob/master/common/oauthTokenManager.go) can be lovingly copied into rclone.

**Comment by ncw** [comment]
@backerman is this something you want to have a go at?

**Comment by backerman** [comment]
@ncw Taking a look.

**Comment by backerman** [comment]
@ncw It actually looks easier than I thought. I need to add some tests but I've got an [initial implementation](https://github.com/backerman/rclone/tree/personal/backerman/msi) in my fork.

**Comment by ncw** [comment]
@backerman I had a look at your fork and I think you are doing very well :-)

I suggest you write lots of help under the `use_msi` definition as that is what gets built into the docs. The first line is the config flag parameter `--azureblob-use-msi` help string.

> It's currently using a dedicated boolean to enable this option, but defaulting to a system-assigned identity if there are no explicit credentials added could also work.

I think this is very similar to the [`env_auth` flag in s3](https://rclone.org/s3/#authentication) so there would be precedence for it needing to be enabled. The S3 backend default to anonymous access if no credentials are supplied.

What would most Azure users expect?

**Comment by backerman** [comment]
The same behavior as S3 should be fine.

**Comment by ncw** [comment]
I've merged this to master now - thank you @backerman - which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54

See  08b9ede for hints on how to configure which will be in the docs proper when 1.54 is released.
