### ISSUE TITLE
missing 'drive-access-token' command line parameter to create remote on the fly

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#3214]
#### What is the problem you are having with rclone?

Rclone is missing a 'drive-access-token' command line parameter for use with Google Drive.
I am unable to use my Google Drive remote on the fly using rclone command line.

#### What is your rclone version (output from `rclone version`)

rclone v1.47.0
- os/arch: windows/amd64
- go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Win10 x64

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount :drive: Z: --drive-client-id xxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com --drive-client-secret xxxxxxxxxxxxxxxxxxxxxx

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2019/05/21 18:50:01 Failed to create file system for ":drive:": drive: failed when making oauth client: failed to create oauth client: empty token found - please run rclone config again

**Comment by ivandeex** [comment]
Closed after 2 years of inactivity
