### ISSUE TITLE
Move/MoveTo implement uid,gid,umask

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#3223]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.47.0
- os/arch: linux/amd64
- go version: go1.12.4

#### What problem are you are trying to solve?
I use rclone moveto to conveniently move directory trees to another location, while excluding some paths. The script that calls rclone is running as root. The directory paths are created during this move are owned by root. I currently get around this by calling chown and chmod to fix the permissions so other tooling not running as root will work without unauthorized exceptions.

In this case I'm moving from one local file directory to another local file directory, no remotes in this move.

#### How do you think rclone should be changed to solve that?
Implement uid, gid, and umask so I can run rclone as root, but set ownership and permissions like I can do with the mount command.

**Comment by ncw** [comment]
I see..

So these would control the local backend creating files/directories/etc.

I'm sure there must be a unix way of solving this though, eg

    sudo -u USER rclone copy ...

**Comment by ncw** [comment]
I think this will be fixed as part of the preserving metadata project, so I'm going to close this issue as there are lots of others!
