### ISSUE TITLE
cryptcheck does not use all of the available --checkers slots

### ISSUE THREAD

**Issue by SL-Gundam** [rclone/rclone#3228]
#### What is the problem you are having with rclone?
cryptcheck does not use all of the available checkers slots.
The folder in question only has three root folders and because of that only three active checks are in progress
--Checkers by default is set to 8 which means it should run 8 checks concurrently. But it seems every --checkers thread is given one folder, rclone does not apply multiple --checkers threads to the same folder

On another situation i had --checkers set to 16. In the beginning all of them were active. But once all of the root folders except one were finished, there was only one --checkers thread active instead of all 16 on that one folder

#### What is your rclone version (output from `rclone version`)
rclone v1.47.0
- os/arch: windows/amd64
- go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 x64 1903

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
C:\rclone\rclone.exe cryptcheck --fast-list --one-way --exclude-from "C:/rclone/Configs/Exclusions.txt" --progress --log-file "C:\Users\User\Desktop\MirrorD Log\Rclone Check_D.log" --log-level INFO D:/ cryptGDrive:D

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
n/a

**Comment by ncw** [comment]
Yes you are right in how it works.

It would be possible to fix this with some queues as in the sync routines.

Do you want to have a go at this?

**Comment by SL-Gundam** [comment]
Tried giving it a go. But just couldn't find enough time to work on this.
Maybe if i have vacation i will give it another go

**Comment by SL-Gundam** [comment]
I believe this has been fixed since i do not see this issue with 1.53.3

**Comment by ncw** [comment]
Yes it was fixed in d55053098f98a5c6200ad2c75a05a142be96b3d8
