### ISSUE TITLE
vfs: make ReadAt for non cached files wait a small time for non sequential reads

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#3231]
#### What is your current rclone version (output from `rclone version`)?

rclone v1.47.0-076-g7ea5a3bc-fix-3210-b2-copy-beta
- os/arch: linux/amd64
- go version: go1.12.4

#### What problem are you are trying to solve?

In af030f74f5c9c49d337ad768b307e50d3cfd60fe we made the write path for vfs files wait a short time to see if a sequential write was coming before giving up.

This should be implemented for the read path too

This would help with issues like https://github.com/trapexit/mergerfs/issues/631 and also fix the problems with the `go-fuse` integration.

**Comment by robertbaker** [comment]
Will this allow async reads?

**Comment by ncw** [comment]
> Will this allow async reads?

It will speed things up but it won't allow anything new.

**Comment by ncw** [comment]
This is implemented now :-)

See --vfs-read-wait flags
