### ISSUE TITLE
Rclone will hang into copying files 

### ISSUE THREAD

**Issue by vaccarieli** [rclone/rclone#3252]
whenever I try to copy a whole folder there are files that won`t copy so I have to manually copy them and then re-run the program so it can continue copying, Idk what the issue could be.

![Capture](https://user-images.githubusercontent.com/41475411/59241582-e0f1a480-8bcd-11e9-8384-15d3e7a00d96.JPG)

**Comment by ncw** [comment]
I suspect it is something to do with the `Duplicate object found in source` errors.

Run `rclone dedupe` on the source (and the destination if it is a Google drive) then have another go.

**Comment by vaccarieli** [comment]
'2019/06/11 14:03:30 Unknown mode for dedupe "ElioTeamDGame:ROMs/Sony/PlayStation 1/Redump (20190519-020841)".
$ $HOME/rc dedupe "ElioTeamDGame:ROMs/Sony/PlayStation 1/Redump (20190519-020841)" "DylanGDrive:MyBackups/Games/Sony/PS1"
2019/06/11 14:07:07 Unknown mode for dedupe "ElioTeamDGame:ROMs/Sony/PlayStation 1/Redump (20190519-020841)".
$ $HOME/rc dedupe "ElioTeamDGame:ROMs/Sony/PlayStation 1/Redump (20190519-020841)" "DylanGDrive:MyBackups/Games/Sony/PS1" -P'

This is what I get when I run 'dedupe' command

**Comment by vaccarieli** [comment]
I just ran the "dedupe" command but unfourtunately I don't have access to the "source" I ran it as well on the "destination" but nothing happen, I guess its because I don't have any dupes in the "destination"

I tried again but still nothing happens keeps hanging it wont copy forward.

**Comment by ncw** [comment]
Try running with `-vv --log-file rclone-log.txt` then attach `rclone-log.txt` to the issue - hopefully that will give more of an idea what is happening.

**Comment by vaccarieli** [comment]
hopes this gives an answer, I made sure that my quota is not exceede cuz I tried manually to copy a 10gb file and it copied it, I went thru the log file and is referring to the quota, but not sure which quota is refering to.

Also I have 2 API Client ID and Client Secret, 1 is set up with the TeamDrive and the other with MyDrive, so that won`t be the case either. please help. :(

[rclone-log.txt](https://github.com/ncw/rclone/files/3276751/rclone-log.txt)

**Comment by ncw** [comment]
I think the problems are google rate limiting

    2019/06/11 15:44:05 DEBUG : pacer: low level retry 10/10 (error googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded)

Are you using [your own client ID](https://rclone.org/drive/#making-your-own-client-id)?

It might be that you've hit your quota which is 750GB per day I think.

**Comment by animosity22** [comment]
This seems stale. If you have any further question, you can ask on the forums and we can help out.
