### ISSUE TITLE
AWS S3 AccessDenied issue when using IAM role

### ISSUE THREAD

**Issue by ses4j** [rclone/rclone#3261]
#### What is the problem you are having with rclone?

I am on an AWS EC2 instance running Windows with an IAM Role that gives it S3 access, so I do not need tokens.  I have a vanilla aws config:

```[aws]
type = s3
provider = AWS
```

My AWS s3 instance has a bucket `my.test.bucket`.

If I try:
> aws s3 ls my.test.bucket
it works fine.

If I try:
> rclone ls my.test.bucket
it fails with:
> 2019/06/13 10:04:37 Failed to ls: AccessDenied: Access Denied
        status code: 403, request id: ..., host id: ...

However, if I do [this](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials):
> curl http://169.254.169.254/latest/meta-data/iam/security-credentials/my_iam_role
then put the token, access key, and secret returned by `curl` on the rclone commandline using `--s3-access-key-id=`, `--s3-secret-access-key=`, and `--s3-session-token`, then voila! it starts to work.

In theory that shouldn't have changed anything, but it implies there's something amiss with the rclone "use IAM Role" capability?  It seems to not be finding the role or something.  I looked at `-vv --dump auth` but there was nothing much in there, the requests it sent looked like they were anonymous...

#### What is your rclone version (output from `rclone version`)
```
rclone v1.47.0
- os/arch: windows/amd64
- go version: go1.11
```

**Comment by ncw** [comment]
I think you need `env_auth = true` in your config file.

**Comment by animosity22** [comment]
This looks to be answered and is stale. If you have a new question or follow up, please just ask in the forums and we can help out.
