### ISSUE TITLE
Manually specifying maximum disk space

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#3270]
When rclone is unable to determine how much space is available, FUSE reports the mounted drive as 1PB
![image](https://user-images.githubusercontent.com/37132025/59633165-81395300-9111-11e9-9555-98471fe0a653.png)

I would like to be able to specify how much space my mounted drive actually has manually, through the configuration or the command line.

**Comment by ncw** [comment]
That would be relatively easy to add.

Do you want to have a go?

I would add a check here

https://github.com/ncw/rclone/blob/f78cd1e0434ee597fb8937ba3cda0d5fd58becfe/vfs/vfs.go#L501

which if `total == -1` then it uses a value set in the vfs options (which should default to -1).

https://github.com/ncw/rclone/blob/f78cd1e0434ee597fb8937ba3cda0d5fd58becfe/vfs/vfsflags/vfsflags.go#L19

**Comment by ncw** [comment]
@FiloSpaTeam looks good - are you going to submit a PR?

Some docs in `vfs/help.go` would be nice also.
