### ISSUE TITLE
rc cache/expire fails on the root directory

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#3271]
Using this command works fine on the subdirectories, but if you try it on the root directory, it returns a 500 Internal Server Error.

**Comment by ncw** [comment]
Can you add a few more details?  Which version of rclone are you using? Which OS?

Can you provide a log from the mount with `-vv` please?

**Comment by animosity22** [comment]
No further information provided as the issue seems stale. Please ask on the forums if you have a question and we can help out.
