### ISSUE TITLE
fichier: server-side copy/move/rename/import

### ISSUE THREAD

**Issue by zotanmew** [rclone/rclone#3292]
1Fichier could support some more optional methods

* [ ] Copy - server side copy
* [ ] Move - server side move
* [ ] DirMove - server side directory move
* [ ] PublicLink - create public URLs for files / directories
* [ ] MergeDirs - to make `rclone dedupe` work since fichier can have duplicates
* [ ] Purge - remove a directory and its contents (not sure if the API supports this)
* [ ] CopyURL - start a remote copy (needs #3029

**Comment by zotanw** [comment]
superseded by #3312

**Comment by ivandeex** [comment]
This ticket has been celebrating 2 years on tracker without activity and without volunteers to implement it
