### ISSUE TITLE
fichier: non-ASCII characters don't behave as expected

### ISSUE THREAD

**Issue by lhaus** [rclone/rclone#3298]
non-ASCII characters fail with 1fichier, and the default (escape with \unicode) doesn't work here as backslash is also blacklisted on 1fichier. Will try to fix this after #3295 is merged

**Comment by zotanw** [comment]
it appears to be that these characters are blacklisted:

`["'<>$/´`]` as well as a space at the beginning of the folder name

**Comment by zotanw** [comment]
this is resolved on branch fichier

**Comment by lhaus** [comment]
Found some files which create duplicates on remote and fail. Will look at that now
