### ISSUE TITLE
rclone 1.48 drive side copy, with Google Drive in DSM is not working

### ISSUE THREAD

**Issue by silversegarra** [rclone/rclone#3300]
#### What is the problem you are having with rclone?
When I try a server side copy in DSM, with flag --drive-server-side-across-configs, doesn't works, neither with rclone 1.47, without flag, it doesn't works, It tries to copy, but finally, nothing is copied.
I tried with between different accounts, in both directions, with the same result.

#### What is your rclone version (output from `rclone version`)
1.47, 1.47 betas and 1.48

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
DSM 6.2

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive, Google Drive TeamDrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync -v --transfers 1 --tpslimit 8 --max-transfer 740G --retries 5 --low-level-retries 3 --ignore-case-sync --ignore-existing --drive-server-side-across-configs "Drive1:Multimedia" "Drive2:Multimedia"  > logs/backup.txt 2>&1 &

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Segarra@SegaNology:/volume3/docker/Torrents/logs$ tail -f backup.txt 
2019/06/26 17:56:18 INFO  : Starting HTTP transaction limiter: max 8 transactions/s with burst 1
2019/06/26 17:57:20 INFO  : 
Transferred:   	         0 / 37.882 GBytes, 0%, 0 Bytes/s, ETA -
Errors:                 0
Checks:             11150 / 11150, 100%
Transferred:            0 / 32, 0%
Elapsed time:      1m1.6s
Transferring:
 * xxxx/xxxx (2018…n - 01x01 - xxxx.mkv: transferring

2019/06/26 17:58:20 INFO  : 
Transferred:   	         0 / 41.645 GBytes, 0%, 0 Bytes/s, ETA -
Errors:                 0
Checks:             20052 / 20052, 100%
Transferred:            0 / 34, 0%
Elapsed time:      2m1.6s
Transferring:
 * xxxx/xxxx (2018…n - 01x01 - xxxx.mkv: transferring

2019/06/26 17:58:58 INFO  : Google drive root 'Multimedia': Waiting for checks to finish
2019/06/26 17:58:58 INFO  : Google drive root 'Multimedia': Waiting for transfers to finish
2019/06/26 17:59:20 INFO  : 
Transferred:   	         0 / 41.645 GBytes, 0%, 0 Bytes/s, ETA -
Errors:                 0
Checks:             26402 / 26402, 100%
Transferred:            0 / 34, 0%
Elapsed time:      3m1.6s
Transferring:
 * xxxx/xxxx (2018…n - 01x01 - xxxx.mkv: transferring

2019/06/26 18:00:20 INFO  : 
Transferred:   	         0 / 41.645 GBytes, 0%, 0 Bytes/s, ETA -
Errors:                 0
Checks:             26402 / 26402, 100%
Transferred:            0 / 34, 0%
Elapsed time:      4m1.6s
Transferring:
 * xxxx/xxxx (2018…n - 01x01 - xxxx.mkv: transferring

2019/06/26 18:01:20 INFO  : 
Transferred:   	         0 / 41.645 GBytes, 0%, 0 Bytes/s, ETA -
Errors:                 0
Checks:             26402 / 26402, 100%
Transferred:            0 / 34, 0%
Elapsed time:      5m1.6s
Transferring:
 *xxxx/xxxx (2018…n - 01x01 - xxxx.mkv: transferring

-------
2019/06/26 18:10:09 ERROR : xxxx/xxxx (2018)/xxxxx - 01x01 - Piloto.mkv: Failed to copy: googleapi: Error 500: Internal Error, internalError
2019/06/26 18:10:20 INFO  : 
Transferred:   	         0 / 40.601 GBytes, 0%, 0 Bytes/s, ETA -
Errors:                 1 (retrying may help)
Checks:             26402 / 26402, 100%
Transferred:            0 / 33, 0%
Elapsed time:     14m1.6s
Transferring:
 * xxxx/zzzzzz (2018… 01x02 - zzzzz.mkv: transferring

***********************************
It stays like that forever.
With the same command line and the sames accounts, under the laptop, with Linux Mint 19, works perfect.
I connect to DSM with SSH, I tried with my user, with admin user and root user, the same error.

Thanks for helping me.

**Comment by ncw** [comment]
Is `DSM` linux based? I'm guessing so.

I think it is unlikely that this is a problem with DSM or rclone running on DSM, I think it is more likely a problem with the environment being different somehow.  Some ideas at random: perhaps the IP of the DSM got blacklisted by Google and the one on your laptop wasn't or maybe one uses IPv4 and one IPv6, or maybe they use different resolvers and so are hitting different endpoints, or maybe the round robin dns gave them different endpoints...

> 2019/06/26 18:10:09 ERROR : xxxx/xxxx (2018)/xxxxx - 01x01 - Piloto.mkv: Failed to copy: googleapi: Error 500: Internal Error, internalError

There have been reports of other people gettng that error https://github.com/ncw/rclone/issues/3155 and https://github.com/ncw/rclone/issues/3070 which I haven't got to the bottom of.

**Comment by silversegarra** [comment]
> Is `DSM` linux based? I'm guessing so.
> 
> I think it is unlikely that this is a problem with DSM or rclone running on DSM, I think it is more likely a problem with the environment being different somehow. Some ideas at random: perhaps the IP of the DSM got blacklisted by Google and the one on your laptop wasn't or maybe one uses IPv4 and one IPv6, or maybe they use different resolvers and so are hitting different endpoints, or maybe the round robin dns gave them different endpoints...
> 
> > 2019/06/26 18:10:09 ERROR : xxxx/xxxx (2018)/xxxxx - 01x01 - Piloto.mkv: Failed to copy: googleapi: Error 500: Internal Error, internalError
> 
> There have been reports of other people gettng that error #3155 and #3070 which I haven't got to the bottom of.

Mmmm... Isn't IP problem, external IP, are the same for laptop, Ubuntu Docker..., because with a Ubuntu Docker, inside DSM, it works perfect. I noticed, that with qnap, doesn't works neither.
DNS, is the same, both are in IPv4....

**Comment by ncw** [comment]
> Mmmm... Isn't IP problem, external IP, are the same for laptop, Ubuntu Docker..., because with a Ubuntu Docker, inside DSM, it works perfect. I noticed, that with qnap, doesn't works neither.
DNS, is the same, both are in IPv4....

Keep digging to see if you can find something which is different. You might find adding `-vv --dump headers` helpful to see what is going on with the HTTP transactions.

**Comment by silversegarra** [comment]
> > Mmmm... Isn't IP problem, external IP, are the same for laptop, Ubuntu Docker..., because with a Ubuntu Docker, inside DSM, it works perfect. I noticed, that with qnap, doesn't works neither.
> > DNS, is the same, both are in IPv4....
> 
> Keep digging to see if you can find something which is different. You might find adding `-vv --dump headers` helpful to see what is going on with the HTTP transactions.

I'll do...
I don't know, if this will help yo, but I tried this docker
" https://hub.docker.com/r/tynor88/rclone/ "
I change the executable file, rclone version 1.45, for the newest, and It doesn't work, maybe you can check this docker... trying ti find the bug

**Comment by silversegarra** [comment]
Can I past here the debug? of is any "secret" code, that I can't show?

**Comment by ncw** [comment]
> Can I past here the debug? of is any "secret" code, that I can't show?

There shouldn't be any secrets in the debug, but there may be names of files etc which you want to keep secret.  Feel free to edit the debug before posting.

**Comment by silversegarra** [comment]
Here is... if I have to something else, please.. let me know
[backup.txt.zip](https://github.com/ncw/rclone/files/3346808/backup.txt.zip)

**Comment by ncw** [comment]
I can see these errors in the logs

```
  68945:2019/07/01 19:47:59 DEBUG : pacer: low level retry 1/3 (error googleapi: Error 500: Internal Error, internalError)
  91791:2019/07/01 19:49:31 DEBUG : pacer: low level retry 2/3 (error googleapi: Error 500: Internal Error, internalError)
  91839:2019/07/01 19:51:00 DEBUG : pacer: low level retry 3/3 (error googleapi: Error 500: Internal Error, internalError)
  91906:2019/07/01 19:52:33 DEBUG : pacer: low level retry 1/3 (error googleapi: Error 503: Backend Error, backendError)
```

As far as I can see the request looks OK

```
2019/07/01 19:46:30 DEBUG : HTTP REQUEST (req 0xc000958700)
2019/07/01 19:46:30 DEBUG : POST /drive/v3/files/17mEOBIWgq2j-RcmVaoUbwdJzJ0KlOd7M/copy?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink&keepRevisionForever=false&prettyPrint=false&supportsTeamDrives=false HTTP/1.1
Host: www.googleapis.com
User-Agent: rclone/v1.48.0
Content-Length: 211
Authorization: XXXX
Content-Type: application/json
Accept-Encoding: gzip
```

It is just that google didn't want to complete the action.  It took 90s thinking about it so maybe it was an internal timeout or something like that.

```
2019/07/01 19:47:59 DEBUG : HTTP RESPONSE (req 0xc000958700)
2019/07/01 19:47:59 DEBUG : HTTP/1.1 500 Internal Server Error
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="46,44,43,39"
Cache-Control: private, max-age=0
Content-Type: application/json; charset=UTF-8
Date: Mon, 01 Jul 2019 17:47:59 GMT
Expires: Mon, 01 Jul 2019 17:47:59 GMT
Server: GSE
Vary: Origin
Vary: X-Origin
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Xss-Protection: 1; mode=block
```

So I still think this is some sort of problem at Google, but I don't know what.

**Comment by silversegarra** [comment]
The weird thing, is that only happens under DSM... :(
Well, maybe in a future version, will work

**Comment by ncw** [comment]
I believe this will be fixed by this beta - can you give it a test?

https://beta.rclone.org/branch/v1.48.0-062-g3fcd4c69-fix-3070-drive-copy-beta/ (uploaded in 15-30 mins)

**Comment by silversegarra** [comment]
Great.. I'll try and I tell you... Thanks

**Comment by silversegarra** [comment]
It works!!!!!!! Thanks!!!! :)

**Comment by silversegarra** [comment]
Good job!!!!!

**Comment by ncw** [comment]
Excellent - thanks for testing :-)

**Comment by silversegarra** [comment]
I close issue!

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.49

**Comment by silversegarra** [comment]
Great... Do you have any PayPal account? I think you do a great job

**Comment by ncw** [comment]
> Great... Do you have any PayPal account? I think you do a great job

Thank you :-)  Donations page is here: https://rclone.org/donate/

**Comment by silversegarra** [comment]
Done!
