### ISSUE TITLE
When using a B2 remote, dirs pending in tmp_upload_path are not in cache mount

### ISSUE THREAD

**Issue by maxim** [rclone/rclone#3305]
When adding non-empty dirs into a Backblaze B2 cache mount with offline uploading, 
these directories will correctly go into `tmp_upload_path`. If you then unmount and mount the cache again, the directories will no longer show up in the mount, while they are still pending in `tmp_upload_path`. The problem is only with directories, files show up correctly.

Rclone: v1.48.0
OS: Ubuntu 18.04 LTS

Explanation from @ncw:

>  this is a combination of two issues
>    1. there is a design flaw in the cache backend which means it doesn't store pending directories in its internal db, only pending files
>    2. normally this would be fine since the cache backend creates the directories immediately, however in the case of b2, you can't have empty directories on b2 which means this scheme fails.

See [discussion and logs](https://forum.rclone.org/t/files-currently-in-tmp-upload-path-no-longer-show-up-in-mount-bug/10615) in rclone forum.

# Reproduction

**Summary:** Any directory sitting in tmp_upload_path (even non-empty) will not appear in the mounted cache remote upon re-mounting. Only files appear in the mount.

Here are the steps to reproduce.

## Step 1. Create these rclone.conf remotes

Note: Replace `<bracket>` values with your own.

```plain
[B2]
type = b2
account = <account>
key = <key>
endpoint =

[B2CacheBug]
type = cache
remote = B2:<bucket>/CacheBug
chunk_size = 10M
info_age = 1w
chunk_total_size = 10G
tmp_upload_path = /<home>/.cache/rclone/uploads_cache_bug
tmp_wait_time = 720h
```

## Step 2. Mount the cache remote

Note: Replace `<bracket>` values with your own.

```bash
~$ mkdir CacheBug
~$ rclone mount B2CacheBug: /<home>/CacheBug --config /<home>/.config/rclone/rclone.conf --fast-list --allow-other --dir-cache-time=24h --cache-workers=5 --buffer-size 0M --umask 002 --log-level INFO
```

Leave this terminal on to observe logs.

## Step 3. In another terminal, add a file and a dir with a file

```bash
~$ echo "hello world" > text_file.txt
~$ mkdir test_dir
~$ echo "hello world" > test_dir/text_file.txt
~$ mv text_file.txt CacheBug/
~$ mv test_dir CacheBug/
~$ ls CacheBug
test_dir  text_file.txt
```

## Step 4. Check to ensure that both file and dir are in tmp upload path

```bash
~$ ls ~/.cache/rclone/uploads_cache_bug/
test_dir  text_file.txt

~$ tree ~/.cache/rclone/uploads_cache_bug/
~/.cache/rclone/uploads_cache_bug/
├── test_dir
│   └── text_file.txt
└── text_file.txt
```

## Step 5. Unmount the cache remote and mount it again

- Press CTRL+C in the mount terminal and wait for unmount
- Press up arrow and enter to run the mount command again

## Step 6. Check files in the mounted path

```bash
~$ ls ~/CacheBug/
text_file.txt
```

There is no longer `test_dir` in here, only the file.

**Comment by ivandeex** [comment]
@maxim 
The _cache_ backend was deprecated a year ago in favor of VFS and is no more supported.
Feel free to reopen against VFS in rclone 1.54 if you can reproduce.
Thanks.
cc @ncw
