### ISSUE TITLE
Outdated Google Drive instructions? Screenshots for current flow.

### ISSUE THREAD

**Issue by dandv** [rclone/rclone#3318]
#### What is the problem you are having with rclone?

Haven't set up a new remote in years, so now sure I'm missing something, hence not straight submitting a PR: the [Google Drive setup instructions](https://rclone.org/drive/) seem outdated at [this step](https://rclone.org/drive/#1-create-a-service-account-for-example-com):

> 1. Create a service account for example.com
To create a service account and obtain its credentials, go to the Google Developer Console.
You must have a project - create one if you don’t.
Then go to “IAM & admin” -> “Service Accounts”.
Use the “Create Credentials” button.

I don't see a Create Credentials button there. I see CREATE SERVICE ACCOUNT:

![image](https://user-images.githubusercontent.com/33569/60468021-e31faf80-9c1d-11e9-9421-6b609c830545.png)

If I click that, the next step in the instructions matches, partially:

> Fill in “Service account name” with something that identifies your client. “Role” can be empty.

There's no "Role" though:

![image](https://user-images.githubusercontent.com/33569/60468057-034f6e80-9c1e-11e9-8871-8534430681e0.png)

There *is* a prompt for the role after I click "CREATE":

![image](https://user-images.githubusercontent.com/33569/60468123-38f45780-9c1e-11e9-95ab-4a362f236007.png)

Next, "Tick “Furnish a new private key” - select “Key type JSON”." seems to have changed to:

![image](https://user-images.githubusercontent.com/33569/60468165-650fd880-9c1e-11e9-92df-e91ece9e0490.png)

> Tick “Enable G Suite Domain-wide Delegation”.

I don't see this option?

Next, I can't find the 'Security" screen mentioned in [step 2](https://rclone.org/drive/#2-allowing-api-access-to-example-com-google-drive).

> Go into “Security” (or use the search bar)

The search bar displays a bunch of options:

![image](https://user-images.githubusercontent.com/33569/60469365-fa609c00-9c21-11e9-8ad5-e7a38c519310.png)

The "API - Cloud Security Command Center" leads to the Credentials screen, https://console.developers.google.com/apis/credentials.

Am I going the wrong route, or maybe Google Cloud changed their UI? In the latter case, feel free to use this issue to update the docs.

**Comment by dandv** [comment]
I found the "Create Credentials" in another screen, https://console.developers.google.com/apis/credentials:

![image](https://user-images.githubusercontent.com/33569/60468694-08adb880-9c20-11e9-8302-532a1f7c3676.png)

**Comment by dandv** [comment]
There's another CREATE CREDENTIALS button in the Google Drive screen at https://console.developers.google.com/apis/api/drive.googleapis.com/overview

![image](https://user-images.githubusercontent.com/33569/60468870-925d8600-9c20-11e9-8bb8-e62a42dc42fa.png)

I'm pretty confused among all the options at this point :)

**Comment by dandv** [comment]
At https://rclone.org/drive/#making-your-own-client-id, step 4, I don't see the "OAuth client ID" option in the dropdown:

> Click “Credentials” in the left-side panel (not “Create credentials”, which opens the wizard), then “Create credentials”, then “OAuth client ID”.

![image](https://user-images.githubusercontent.com/33569/60470966-0f402e00-9c28-11e9-81aa-58625ff18ced.png)

**Comment by animosity22** [comment]
You are in the wrong spot:

![image](https://user-images.githubusercontent.com/5088712/60474618-fb54f600-9c40-11e9-91c4-e26adf99f41a.png)


Once you enable the APIs, you should have that screen.

**Comment by ncw** [comment]
Google like moving things about in their control panel!

Would you like to submit a pull request to fix up the docs?

Only the [docs/content/drive.md](https://github.com/ncw/rclone/blob/master/docs/content/drive.md) files needs fixing up.

**Comment by animosity22** [comment]
@dandv  -  I had some time and wanted to get you to review this as I can do a pull request to update them:


1. Log into the Google API Console with your Google account. It doesn’t matter what Google account you use. (It need not be the same account as the Google Drive you want to access)
2. Select a project or create a new project.
3. On the left navigation menu, click APIs & Services
4. Click on “ENABLE APIS AND SERVICES” search for “Drive”, and enable the then “Google Drive API”.
5. Click on the left navigation menu and click APIs & Services -> Credentials
6. Click on “Create credentials”, then “OAuth client ID”. It will prompt you to set the OAuth consent screen product name, if you haven’t set one already.
7. Choose an application type of “other”, and click “Create”. (the default name is fine)
8. It will show you a client ID and client secret. Use these values in rclone config to add a new remote or edit an existing remote.

Does that seem right if you test?

**Comment by ncw** [comment]
@animosity22 
> Does that seem right if you test?
I did this flow recently for google photos and I'm pretty sure it is correct :-)

**Comment by ncw** [comment]
@animosity22 is your flow still correct? It never made it into the docs. I can stuff it in or you can send a PR whichever you like.

**Comment by megahall** [comment]
I looked into all of this, and none of this procedure works when you want to create the GCP Project under a non G Suite user account. If you make one of those, you have to use an External mode OAuth Client ID which requires review by Google, and possibly an expensive commercial security review. How do you configure access to Google Drive using an ID besides rclone's, based on a personal Google account and GCP project?

**Comment by animosity22** [comment]
This is being taken care of via:

https://github.com/rclone/rclone/pull/3918

**Comment by ncw** [comment]
#3918 is merged now so I'll close this :-)

I'll stick the docs up when I make a point release.
