### ISSUE TITLE
drive: config flow should not open browser when non auto config

### ISSUE THREAD

**Issue by dandv** [rclone/rclone#3323]
#### What is the problem you are having with rclone?

Running the headless config for Google Drive launches the default browser automatically.

Reproduced with rclone 1.45 on Ubuntu 18 and on Mac OS. See https://forum.rclone.org/t/option-to-disable-opening-browser/10710/2 for details.

**Comment by ncw** [comment]
This also happens in the latest master.

The problem is confined to google drive - when you answer 'N' to auto config it shows a URL rather than getting you to run `rclone authorize`.  Showing this URL opens the browser when it shouldn't.

**Comment by ncw** [comment]
This line

https://github.com/ncw/rclone/blob/37c1144b468214bff7f212e74f3a58cb9eaa6ed1/lib/oauthutil/oauthutil.go#L454

Needs to be wrapped in an `if` statement condition on one of the things in that function (haven't worked out which).

Would you like to have a go at fixing this?

**Comment by dandv** [comment]
> Would you like to have a go at fixing this?

Thanks for looking into this. To be honest, I'm completely unfamiliar with the codebase, under a deadline to (re)launch [the thing I'm currently working on](https://cryptoclimate.io), and able to deal with the current behavior of rclone in this situation :)

**Comment by ncw** [comment]
> > Would you like to have a go at fixing this?
> 
> Thanks for looking into this. To be honest, I'm completely unfamiliar with the codebase, under a deadline to (re)launch [the thing I'm currently working on](https://cryptoclimate.io), and able to deal with the current behavior of rclone in this situation :)

No worries - it would be a good first issue for someone.

**Comment by KrishnaSindhur** [comment]
can i work on this?

**Comment by ncw** [comment]
> can i work on this?

By all means :-)

**Comment by ncw** [comment]
I've merged this fix - thanks @Yexiaoxing - to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.51
