### ISSUE TITLE
HTTP REMOTE FAILED TO READ DIR. HTTP Error 503:

### ISSUE THREAD

**Issue by vaccarieli** [rclone/rclone#3324]
I am trying to get acces to a server that is on an http I have either my password and username, but the website has RECAPTCHA so I guess thats why am unable to read the directory, is there a way to bypass that ?

2019/07/02 23:24:01 ERROR : : error listing: error listing "": failed to readDir: HTTP Error 503: 503 Service Temporarily Unavailable
2019/07/02 23:24:01 Failed to lsd: error listing "": failed to readDir: HTTP Error 503: 503 Service Temporarily Unavailable

**Comment by ncw** [comment]
Rclone doesn't support RECAPTCHA it only supports plain HTTP links.

You can try using `--tpslimit` to slow everything right down, so `--tpslimit 1` for 1 transaction per second or `--tpslimit 0.1` for 1 transaction every 10s.

**Comment by vaccarieli** [comment]
The website only needs the Recaptcha to log in, only one time not by file,  once you log in one time the browser saves the info, I though would be possible to add the feature.

**Comment by ncw** [comment]
The browser is probably getting a cookie.  It wouldn't be impossible to add cookie support to the http backend.  I think rclone doing RECAPTCHA itself is too difficult though - that needs to be done in a browser.

**Comment by vaccarieli** [comment]
Thanks
