### ISSUE TITLE
[feature idea] Selective download chunking based on filetype (cache backend)

### ISSUE THREAD

**Issue by thestigma** [rclone/rclone#3331]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.48.0-063-gd7016866-beta
- os/arch: windows/amd64
- go version: go1.12.3
Windows 10

#### What problem are you are trying to solve?

Chunked downloading (like the cache backend provides) has some benefits. Most notably it is essential to quickly and smoothly stream files that support it (video and audio most commonly). For such functionality, relatively small chunks are optimal, like for example 5-10MB

However, small chunks have some significant downsides to them also. Due to the nature of how TCP works (slowly increasing the transfer window and thus transfer speed) splitting large files into loads of tiny chunks results in your download capacity never being close to fully utilized. Just look at a network utilization graph and it is obvious that the constant stopping and starting results in a transfer that constantly drops down in speed and starts to ramp up - only to drop in speed again before reaching maximum throughput because the chunk is already done and a new one has to start - and the problem keeps repeating. Additionally, all these small chunks means there are a lot of API calls, which are a limited resource. Both of these problems become worse as chunk size gets smaller.

So in short - you would ideally want streamable formats to chunk-download, and non-stremable formats that can't benefit to not chunk-download. Then you would have the best of both worlds.

#### How do you think rclone should be changed to solve that?

- Before requesting chunks - have rclone look at the file extension. Is it a known streamable format? Then chunk it according to normal parameters. Is it not a streamable? Then do an efficient monolithic transfer.

- Add optional flag / config to enable this optimized behaviour - as people with unreliable connections might prefer chunking everything in case of errors that require re-downloading chunks. Not sure what the best default behavior should be between the two...

- Add a list of known streamable formats to use as a default reference, but allow users to customize or add extensions. This could maybe be as simple as a really long flag/config string with separation characters.

#### Potential problems to overcome
If files on remote are encrypted and do not run through decryption remote before reaching cache then the cache will not be able to see the extension. While this would be solved by decrypting before cache NCW does not recommend this (see cache documentation). Also this would result in cached files being left unencrypted which may not be desirable for the user.

I think the simplest way to overcome this issue would be to let the cache also know the decryption key. It can then use this to temporarily "peek" at the file extension in the name and know how to proceed. Unless your cache runs in an insecure environment I don't really see a security problem with this. I think such a usecase would be very rare - and if need be then leave the feature off as default and add a security warning to the option in documentation.

#### How I am prepared to help
I volunteer for any beta-testing and bug-hunting.
If you need help researching the list of extensions to add to the default reference then I can probably do that work also.

**Comment by ncw** [comment]
That is an interesting idea.

Streaming things with low latency is a use diametrically opposed to maximum throughput.

What is your use case for the cache?

**Comment by thestigma** [comment]
Welcome back NCW :) Hope you had a nice holiday.

My personal usecase is mixed. Mostly backups and general storage both for short-term and long term, but of course also some media. Basically it's my alternative to having to run loads of disks in a complicated RAID locally which would be very costly and more prone to dataloss even with RAID. For me this works since I'm on a 150Mbit fiber, and that's an acceptable speed to access any data that isn't being worked on or used "right now". I would think that this sort of "mixed use" isn't all that uncommon among users.

As you say - streaming media is diametrically opposed to throughput so you either have to make your streaming extremely sluggish or bite the bullet on your bandwidth being underutilized. There is no way to do both well currently, or even reach a happy medium really (since streaming really requires small chunks for files to not open extremely sluggishly). Except maybe using 2 separate remotes with one specifically configured exclusively for media streaming, but that's both a convoluted workaround and causes lots of other problems such as needing a double cache, double mounts ect.

This idea would basically be an attempt at making a smart and configurable all-in-one, best-of-both-worlds solution.

The cache would need to have some logic to handle both chunked and non-chunked cached data, but that seems like it should be doable. That and how to handle encrypted files (as detailed above) is probably the main problems to solve.

**Comment by thestigma** [comment]
@ncw I think you can close this as your discretion.

I think at this point it is not worth spending effort on fixing the cache-backend when you could rather work on your own VFS cache enhancements.

(this still may be a relevant idea for the new VFS cache to have in mind, but probably better we start that topic anew if it is needed rather than keep this open)

**Comment by tcf909** [comment]
We at one point tried to use rclone mount as a way to build a web farm with shared eventually consistent storage. It functionality worked well (each node having a local cache of files via Cache and VFS while getting file updates as the remote received them). The challenge was just what we are talking about here -- latency ( albeit a little different in that we are talking about cached latency). File access time for the types of files a web server uses was very sluggish (400+ms and usually much higher). Our slowest NFS implementation was 20 - 40ms. So we ultimately abandoned rclone, but I still argue if the latency was on par with local disk access (through cache, etc) it would have been a much better --share nothing scalable web farm.

**Comment by ivandeex** [comment]
I am going to close this stale request due to zero traffic here.
Also, the cache backend is not supported anymore.
