### ISSUE TITLE
Google Drive to Google Drive copy without conversion (Google documents, sheets and other)

### ISSUE THREAD

**Issue by RalfG60** [rclone/rclone#3337]
#### What is your current rclone version (output from `rclone version`)?
v1.48.0

#### What problem are you are trying to solve?
Copy Google sheets without export (xlsx)/ import. Copy in original format.

#### How do you think rclone should be changed to solve that?
https://developers.google.com/drive/api/v3/reference/files/copy 

I have copied a bunch of Google sheets from 'shared with me' to 'my drive'. 
Unfortunately when comparing the original with the copy there are differences, due to conversion.
I would like to duplicate Google documents and sheets server-side, copy them to 'my drive'.

**Comment by ncw** [comment]
You will need to set `--drive-server-side-across-configs` I think to do the copy loss-lessly.

What command line did you use for the copy?

**Comment by RalfG60** [comment]
I did use it:
rclone -v -P --drive-impersonate data@domain.de --drive-server-side-across-configs --log-file=c:\Rclone\log107.txt copy Gdrive:"Sourcefolder\Anne" Gdrive:"Copyfolder\Anne"

Unfortunately it still converts, export - import.

**Comment by ncw** [comment]
> I did use it:
> rclone -v -P --drive-impersonate [data@domain.de](mailto:data@domain.de) --drive-server-side-across-configs --log-file=c:\Rclone\log107.txt copy Gdrive:"Sourcefolder\Anne" Gdrive:"Copyfolder\Anne"
> 
> Unfortunately it still converts, export - import.

Can you paste a log with `-vv` please?

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
