### ISSUE TITLE
upstream XML decoding bug.. command rclone info has broken s3 remote

### ISSUE THREAD

**Issue by SocialCrypt-Verify** [rclone/rclone#3345]
#### Output of `rclone version`
rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.6

Ubuntu 18.04.2 LTS
#### Describe the issue
My setup is S3-Compatable (Scaleway) remote >> Crypt.

After unmounting the crypt remote "encloud" using "fusermount -u", I then manually cleared the vfs cache folder, and remounted with --cache-db-purge option. But then I was unable to list the directory or perform any other action on that remote, even when mounting with bypassing the crypt remote to see the encrypted files. Object storage crashed. The Scaleway support had to apply a hotfix for this bug at their end and had coprehensively explained the issue. 

**Scaleway team replicated the same situation on Amazon S3 and got the same error from rclone.**

Mounting string:
`rclone mount encloud: /mnt/s3 --allow-other --contimeout 10m --max-read-ahead 64M --log-file "/var/www/rclone.log" --log-level NOTICE --fast-list --transfers 16 --buffer-size 64M --multi-thread-cutoff 64M --multi-thread-streams 16 --poll-interval 0 --vfs-cache-mode full --dir-cache-time 2160h --vfs-cache-max-age 720h --vfs-cache-max-size 10G --vfs-read-chunk-size 64M --vfs-read-chunk-size-limit 128M --retries 200 --retries-sleep 1s --no-gzip-encoding --stats 24h --stats-one-line --gid 33 --uid 33 --umask 007 --daemon`

Here is the rclone config:
`[cloud]
type = s3
provider = Other
access_key_id = ***
secret_access_key = ***
region = nl-ams
endpoint = s3.nl-ams.scw.cloud
acl = private
bucket_acl = private
upload_cutoff = 256M
chunk_size = 256M
upload_concurrency = 8
force_path_style = false

[encloud]
type = crypt
remote = cloud:/album/cloud
filename_encryption = standard
directory_name_encryption = true
password = ***
password2 = ***`

Scaleway Team response to he issue:

> Hello,
> 
> First of all, thank you for your report, we did have an encoding bug on our
> end, which is now fixed. The problem you are now having is on the rclone's
> side, and there is nothing we can do about it.
> 
> Rclone did upload object with control characters in the names. For example:
> 
>     data/-position-left-05
> 
> Which is:
> 
>     00000000  64 61 74 61 2f 05 2d 70  6f 73 69 74 69 6f 6e 2d  |data/.-position-|
>     00000010  6c 65 66 74 2d 30 35 0a                           |left-05.
> 
> Notice the 0x05 just before the '-'.
> 
> Now, the first time you reported the bug to us, the gateway was crashing on
> listing, because our underlying encoding library was panicking on characters
> such as this one. We now have the same comportement as Amazon, which is
> introducing the characters in the XML: "&#x05".
> 
> However, in this specific case, the 1.0 XML parsers are not compatible with
> such characters, that is why rclone is failing on mount (The same bug is
> happening to our console right now, which is why you cannot list via the web
> interface).
> 
> Amazon specifies the ?encoding-type=url parameter for such cases.
> From Amazon's documentation[1]:
> 
>     Param: encoding-type
>     Description: Requests Amazon S3 to encode the response and specifies the
>     encoding method to use.
> 
>     An object key can contain any Unicode character. However, XML 1.0 parsers
>     cannot parse some characters, such as characters with an ASCII value from 0 to
>     10. For characters that are not supported in XML 1.0, you can add this
>     parameter to request that Amazon S3 encode the keys in the response.
> 
>     Type: String
>     Default: None
>     Valid value: url
> 
> We did test on the Amazon S3 gateway, with those objects names, and rclone
> fails the same way. This is why I believe the rclone s3 crypt implementation is
> broken in this way, since it uploads special object names, without specifying
> the encoding type to url on listing.
> 
> In the meantime, I suggest you use another tool to access your data. Another
> workaround will be to list your files with `aws s3 ls` (which is using the
> encoding-type=url) and spot the files that have control characters in their
> names. You can attempt to delete them in order to be able to mount your bucket
> with rclone.
> 
> In the hope I have answered all your questions,
> 
> [1] https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html
> 
> 
> Cordialement / Best regards,
> 
> Pierre-Antoine PAGANELLI
> 
> Customer Success Specialist Advanced

Rclone logged error **before** hotfix at scaleway:
`2019/07/09 17:34:17 ERROR : /: Dir.Stat error: InternalError: We encountered an internal error. Please try again.
status code: 500, request id: tx795027a68d2d416f8d704-005d24b3f8, host id: tx795027a68d2d416f8d704-005d24b3f8`

Rclone logged error **after** hotfix at scaleway:
`2019/07/11 19:55:10 ERROR : /: Dir.Stat error: SerializationError: failed to decode REST XML response
status code: 200, request id: txc7bdb342b42a43faa97f8-005d2777fd
caused by: XML syntax error on line 2: illegal character code U+0001`

This issue cause a lot of issues for us because this set up is running in production environment...
At this moment I didn't try to interact with the storage directly through the native scaleway's cli and just restored the backup to a new bucket.

This doesn't look production ready,..
Any thoughts ?

**Comment by buengese** [comment]
The S3 backend is implemented on top of the [official aws sdk](https://github.com/aws/aws-sdk-go) which is where all the XML parsing happens so for the deserialization error we'd problem need to open an issue there. However what is bothering me is how the control character made it into the name in the first place all names encrypted by the crypt backend should be in base32 so I can't see how such an object could have been created through it.

**Comment by SocialCrypt-Verify** [comment]
So it's a core bug? Is there any plans on fixing it??
I requested addition information from the Scaleway's back-end logs, here is the reply:

> Hello,
> Here are the logs with the rclone that uploaded the said file :
> 
> `|Time|Method|Bytes received|URI|Return code| |-|-|-|-|-| |Jul 9 11:33:53|PUT|50|/data/%2501-position-left-01%3FX-Amz-Algorithm%3DAWS4-HMAC-SHA256%26X-Amz-Credential%3DSCW0CSQ8B0VMC5DS4B66%252F20190709%252Fnl-ams%252Fs3%252Faws4_request%26X-Amz-Date%3D20190709T113353Z%26X-Amz-Expires%3D900%26X-Amz-SignedHeaders%3Dcontent-type%253Bhost%253Bx-amz-acl%253Bx-amz-meta-mtime%26X-Amz-Signature%3Df8ccb969dd8b7acd192da680f03a033930410b89030f837d7309a3dfe6b6ec19|200|`
> 
> 
> At first there is a crash, and the it gives the list again.
> --
> Regards / Cordialement
> Julien S.
> Customer Success Specialist - Advanced Support
> Scaleway (Scaleway / Online by Scaleway / Scaleway Datacenter)

**Comment by buengese** [comment]
> So it's a core bug? Is there any plans on fixing it??

Definitely! The request doesn't look right to me however I'm not that familiar with the s3 backend and don't have access to Scaleway. I'll see if I can reproduce this with another S3 implementation but we may need to wait for ncw to return from vacation to fix this.

**Comment by buengese** [comment]
I'm stupid for not thinking about this earlier but it appears that you ran the rclone info command on your s3 backend. This command is specifically for testing which characters a backend supports including and the file `-position-left-05` is definetly created by this command. While unfortunate it is somewhat expected for this command to break certain backends so this isn't really a bug. However the XML encoding decoding bug in the AWS library still stands.

**Comment by SocialCrypt-Verify** [comment]
which command do you mean? During all times I only used mount, copy, sync, check, cryptcheck. Mostly on crypt remote which wraps the s3. 
Anyway this idea of creating test file on remote that might crash the server is not good )

**Comment by buengese** [comment]
The command is `rclone info` for this very reason it is not even listed in the help but the file pretty much guaranteed to be the result of this command.
https://github.com/ncw/rclone/blob/0a1169e659ec596172ac7d67acb1c9b8fc2bb385/cmd/info/info.go#L157

**Comment by SocialCrypt-Verify** [comment]
I have never run this..

**Comment by buengese** [comment]
Are you sure about that? The relevant code is not called from anywhere else.

**Comment by SocialCrypt-Verify** [comment]
I cant recall that.
I dont even see this command in bash history :S ..

**Comment by buengese** [comment]
I really can't think of anything else. For now it would be best if you'd just remove the problematic files via the web interface. I don't see anything in the code that should cause them to be created again so your setup should be fine. I'll leave this issue open because of the upstream XML decoding issue. Of course if you have any new information or should this issue arise again you should update this issue. For now this is all I can think of.

**Comment by SocialCrypt-Verify** [comment]
ok. I leave this issue to it. This command could be called.
Probably there should be a warning or simple confirmation window appear prior execution?

**Comment by SocialCrypt-Verify** [comment]
I started to get such errors in rclone logs that are not even formatted corretly:

After the last bug fix (ticket: #MHRO-3422-QMKE) at your side, my rclone logs are flooded with timeout/socket errors that are not even formatted correctly

Example:

```
2019/07/16 10:02:15 ERROR : appdata_oct3sz744045/preview/222261/256-144.jpg: Failed to copy: s3 upload: 400 Bad Request: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period.</Message><RequestId>tx14822e543e904b6d94eeb-005d2d8464</RequestId></Error>

2019/07/16 10:02:15 ERROR : appdata_oct3sz744045/preview/222261/256-144.jpg(0xc02c8603c0): failed to transfer file from cache to remote: s3 upload: 400 Bad Request: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period.</Message><RequestId>tx14822e543e904b6d94eeb-005d2d8464</RequestId></Error>

2019/07/16 10:02:15 ERROR : appdata_oct3sz744045/preview/222261/256-144.jpg(0xc02c8603c0): RWFileHandle.Flush error: failed to transfer file from cache to remote: s3 upload: 400 Bad Request: <?xml version='1.0' encoding='UTF-8'?>
<Error><Code>RequestTimeout</Code><Message>Your socket connection to the server was not read from or written to within the timeout period.</Message><RequestId>tx14822e543e904b6d94eeb-005d2d8464</RequestId></Error>
```


Using the same setup as described above.
Any thoughts ?

**Comment by ncw** [comment]
I found an issue about this here: https://github.com/aws/aws-sdk-go/issues/1914

It looks like there may be a work-around

> As a workaround I'm retrieving url-encoded keys with s3.ListObjectsV2Input.EncodingType attribute set to aws.String(s3.EncodingTypeUrl), but it will still be nice to have this properly resolved on the service end.

This would be quite easy to try if someone wants to have a go?

**Comment by ncw** [comment]
I had a go at a fix here:

https://beta.rclone.org/branch/v1.48.0-074-g7afad074-fix-3345-s3-encoding-beta/ (uploaded in 15-30 mins)

This needs to be run through the integration tests for all the other s3 backends so may need to be optional for AWS only - not sure!

**Comment by ncw** [comment]
I'm going to merge this as part of #3148

**Comment by jjriv** [comment]
We were having a similar issue using rclone and getting serialization errors with XML when trying to list or purge the contents of a bucket. So I downloaded the beta, but, we still get the same errors.

`2019/09/13 16:33:33 Failed to ls: SerializationError: failed to decode REST XML response
        status code: 200, request id: e2e74c4c-28e0-43c1-bf5f-dcbdcee6cde3
caused by: XML syntax error on line 1: illegal character code U+0003
`
Upon further investigation I think the culprit is file names that have % symbols in them, and this is breaking the XML parser. For example:
`test 60% dark.pdf.enc`

Should this fix also work for that?

**Comment by ncw** [comment]
> We were having a similar issue using rclone and getting serialization errors with XML when trying to list or purge the contents of a bucket. So I downloaded the beta, but, we still get the same errors.
> 
> `2019/09/13 16:33:33 Failed to ls: SerializationError: failed to decode REST XML response`
> `status code: 200, request id: e2e74c4c-28e0-43c1-bf5f-dcbdcee6cde3`
> `caused by: XML syntax error on line 1: illegal character code U+0003`

The error message indicated that the character it is having trouble with is 0x03 so a control character...

Could you try this beta - this is the proper fix and I think it should work...

https://beta.rclone.org/branch/v1.49.0-031-ge5c6c14b-filename-encode-beta/

**Comment by jjriv** [comment]
I've tried the recommended beta and it still does not work:
```[root@rclone ~]# rclone version
rclone v1.49.0-031-ge5c6c14b-filename-encode-beta
- os/arch: linux/amd64
- go version: go1.12.9
[root@rclone ~]# rclone -vvvv purge COS:lsntervals-documents-2/10215/0/
2019/09/16 14:24:59 DEBUG : rclone: Version "v1.49.0-031-ge5c6c14b-filename-encode-beta" starting with parameters ["rclone" "-vvvv" "ls" "COS:cos-intervals-documents-2/10215/0/"]
2019/09/16 14:24:59 DEBUG : Using config file from "/root/.rclone.conf"
2019/09/16 14:25:00 Failed to ls: SerializationError: failed to decode REST XML response
        status code: 200, request id: 76dac097-bf12-45b4-941f-59597961c84b
caused by: XML syntax error on line 1: illegal character code U+0003
```
Same thing happens with a purge:
```2019/09/16 14:27:18 DEBUG : rclone: Version "v1.49.0-031-ge5c6c14b-filename-encode-beta" starting with parameters ["rclone" "-vvvv" "purge" "COS:cos-intervals-documents-2/10215/0/"]
2019/09/16 14:27:18 DEBUG : Using config file from "/root/.rclone.conf"
2019/09/16 14:27:19 INFO  : Waiting for deletions to finish
2019/09/16 14:27:19 ERROR : failed to list: SerializationError: failed to decode REST XML response
        status code: 200, request id: a536e812-d664-478f-a909-9357359cfc04
caused by: XML syntax error on line 1: illegal character code U+0003
2019/09/16 14:27:19 ERROR : S3 bucket cos-intervals-documents-2 path 10215/0: Failed to list "": SerializationError: failed to decode REST XML response
        status code: 200, request id: 4cd441cd-655c-4490-9f5f-4530a63a6cd8
caused by: XML syntax error on line 1: illegal character code U+0003
2019/09/16 14:27:19 DEBUG : S3 bucket cos-intervals-documents-2 path 10215/0: Removing directory
2019/09/16 14:27:19 ERROR : Attempt 1/3 failed with 2 errors and: SerializationError: failed to decode REST XML response
        status code: 200, request id: 4cd441cd-655c-4490-9f5f-4530a63a6cd8
caused by: XML syntax error on line 1: illegal character code U+0003
2019/09/16 14:27:19 INFO  : Waiting for deletions to finish
2019/09/16 14:27:19 ERROR : failed to list: SerializationError: failed to decode REST XML response
        status code: 200, request id: 7801e6c8-c91f-4655-a9a4-751028d035d1
caused by: XML syntax error on line 1: illegal character code U+0003
2019/09/16 14:27:20 ERROR : S3 bucket cos-intervals-documents-2 path 10215/0: Failed to list "": SerializationError: failed to decode REST XML response
        status code: 200, request id: 2dd5b87e-b5c7-4720-8570-eab3a8d78f2e
caused by: XML syntax error on line 1: illegal character code U+0003
2019/09/16 14:27:20 DEBUG : S3 bucket cos-intervals-documents-2 path 10215/0: Removing directory
2019/09/16 14:27:20 ERROR : Attempt 2/3 failed with 2 errors and: SerializationError: failed to decode REST XML response
        status code: 200, request id: 2dd5b87e-b5c7-4720-8570-eab3a8d78f2e
caused by: XML syntax error on line 1: illegal character code U+0003
2019/09/16 14:27:20 INFO  : Waiting for deletions to finish
2019/09/16 14:27:20 ERROR : failed to list: SerializationError: failed to decode REST XML response
        status code: 200, request id: 5e6a3f00-d930-45db-a751-f0a9acc2ba0b
caused by: XML syntax error on line 1: illegal character code U+0003
2019/09/16 14:27:21 ERROR : S3 bucket cos-intervals-documents-2 path 10215/0: Failed to list "": SerializationError: failed to decode REST XML response
        status code: 200, request id: 87da27b6-75ce-440c-8721-33efbcd9dd00
caused by: XML syntax error on line 1: illegal character code U+0003
2019/09/16 14:27:21 DEBUG : S3 bucket cos-intervals-documents-2 path 10215/0: Removing directory
2019/09/16 14:27:21 ERROR : Attempt 3/3 failed with 2 errors and: SerializationError: failed to decode REST XML response
        status code: 200, request id: 87da27b6-75ce-440c-8721-33efbcd9dd00
caused by: XML syntax error on line 1: illegal character code U+0003
2019/09/16 14:27:21 Failed to purge with 2 errors: last error was: SerializationError: failed to decode REST XML response
        status code: 200, request id: 87da27b6-75ce-440c-8721-33efbcd9dd00
caused by: XML syntax error on line 1: illegal character code U+0003
```

**Comment by ncw** [comment]
@jjriv can you try this beta please? I was working on this yesterday and I think this should be good now.

If it doesn't work then can you do an `rclone ls -vv --dump bodies` and post that or email it to me nick@craig-wood.com with a link to this issue - thanks.

https://beta.rclone.org/branch/v1.49.0-097-g492483eb-filename-encode-beta/ (uploaded in 15-30 mins)

**Comment by jjriv** [comment]
Still no luck on the ls:
```[root@rclone ~]# rclone -vvv ls COS:cos-intervals-documents-2/10215/0/
2019/09/17 13:48:03 DEBUG : rclone: Version "v1.49.0-097-g492483eb-filename-encode-beta" starting with parameters ["rclone" "-vvv" "ls" "COS:cos-intervals-documents-2/10215/0/"]
2019/09/17 13:48:03 DEBUG : Using config file from "/root/.rclone.conf"
2019/09/17 13:48:04 Failed to ls: SerializationError: failed to decode REST XML response
        status code: 200, request id: 6681b1a8-5f8e-4292-af87-8c049753ebd7
caused by: XML syntax error on line 1: illegal character code U+0003
```

I've also emailed the dump file to you.

**Comment by ncw** [comment]
The problem is caused by one of your files having a control character in the name

    10215/0/51c49e5fa15e0_2650_GB_ESTER_1.7OZ_EAR_BX^C.pdf.enc

I've marked it with ^C which is that `illegal character code U+0003` that the error reports.

This is returned verbatim in the XML returned, however that is an illegal XML character and the go libraries rather strict parser rejects it.  See this [S3 SDK issue](https://github.com/aws/aws-sdk-go/issues/1914) for background.  This is 100% compatible with AWS S3 so far.

The binary I sent you works around this by setting `encoding-type=url` in the request as recommended in the issue.

```
2019/09/17 13:52:35 DEBUG : HTTP REQUEST (req 0xc000120600)
2019/09/17 13:52:35 DEBUG : GET /XXX?delimiter=&encoding-type=url&max-keys=1000&prefix=10215%2F0%2F HTTP/1.1
User-Agent: rclone/v1.49.0-097-g492483eb-filename-encode-beta
Authorization: XXXX
```

However IBM COS seems to completely ignore this!  Looking at the response, none of it is URL encoded.

According to the docs this is supported: https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-compatibility-api-bucket-operations

So maybe you are using an older IBM COS?  Or maybe there is a bug?

I think this is not a commonly used operation as I found a [bug in CEPH](https://tracker.ceph.com/issues/41870) yesterday around this too!

This also makes me re-think my strategy... Perhaps I should only list with `encoding-type=url` on AWS, other platforms should probably have to do a retry on the XML Syntax error then use `encoding-type=url`.  This won't help your problem but it will stop rclone trying to URL decode things which aren't URL encoded which is a big potential compatibility problem.

**Comment by jjriv** [comment]
Thank you for your assistance in troubleshooting this issue! I'm glad we were able to isolate the problem. I have started a ticket with IBM and I'll keep you posted as to what they say. I'm glad to hear that this will help with your strategy. And I like your idea of doing a retry on the XML Syntax error.

**Comment by jjriv** [comment]
I wanted to follow up with this. IBM informed me that the encoding-type feature had to be enabled on our account. They've since enabled it. I've downloaded the latest rclone version 1.49.5 and I'm still not able to get it to work. When I look at the bodies dump, I can see that rclone is not setting encoding-type to url when making the request. 

Here is what the GET request looks like:
`GET /cos-intervals-documents-2?delimiter=&max-keys=1000&prefix=10215%2F0%2F HTTP/1.1`

How do I get rclone to set encoding-type to url? Is there a config setting I need to specify?

**Comment by ncw** [comment]
You'll need [the latest beta](https://beta.rclone.org) for that.  This is shortly to become v1.50.

**Comment by jjriv** [comment]
Thx! I tested it and I like the improvements. Unfortunately, IBM still hasn’t enabled the encoding-type param on their side so I’ll have to keep working with them to resolve that.

Thanks again for making this update! I’ll be sure to grab v.1.50. when it becomes available.

Regards,
John
________________________________
Official Intervals help site
help.myintervals.com

The Intervals blog:
www.myintervals.com/blog/<http://www.myintervals.com/blog/>
________________________________
