### ISSUE TITLE
rclone gdrive upload max-transfer

### ISSUE THREAD

**Issue by zenjabba** [rclone/rclone#3347]
Problem: Migration of files to Google Drive (gsuite) 750GB daily upload

Modification of process. When the 750GB (or --max-transfers limit) has been met, allow rclone to continue uploading the current files in the queue since google allows those files to complete correctly rather than a hard cut off.

**Comment by buengese** [comment]
Just so I'm understanding this right the current behavior is that as soon the limit is reached rclone cancels all running transfers through fatal error while for gdrive we should allow ongoing transfers to complete and only stop the queuing of new transfers.

**Comment by zenjabba** [comment]
Bingo. Basically google drive allows you to complete your currently running file uploads, so it should just finish them and stop trying to upload anything new.

**Comment by a925sw** [comment]
I just wanted to throw some support behind this. It does indeed cut off current uploads when drive allows for the completion of active transfers.

**Comment by ncw** [comment]
This is a nice idea...  It might be need to be controlled by another flag... Say `--gracefull` or something like that.

**Comment by zenjabba** [comment]
I like seeing *Soon*

**Comment by keteflips** [comment]
You can try with --retries-sleep=TIME
Sleep your "rclone move"until your daily quota restart.

**Comment by ivandeex** [comment]
@zenjabba 
Did you try `--retry-sleep`?
Does it solve your case?

**Comment by ivandeex** [comment]
Closed after 2 months of inactivity

**Comment by ncw** [comment]
Actually I think we did this already - you can set the cutoff mode here

      --cutoff-mode string                   Mode to stop transfers when reaching the max transfer limit HARD|SOFT|CAUTIOUS (default "HARD")

**Comment by zenjabba** [comment]
Perfect. Thanks!
