### ISSUE TITLE
 (Google Drive) Shared with me can't access shared files from Team Drives

### ISSUE THREAD

**Issue by Sparoney** [rclone/rclone#3348]
#### What is the problem you are having with rclone?

When using the --drive-shared-with-me flag or the shared_with_me=true option for a remote, rclone can access files shared publicly from someone's "My Drive", but not a file shared publicly from a Team Drive.

_Files **shared** via Team Drives to the user's "Shared with me" are invisible to rclone, which is the issue._ I'm treating this is a bug because I assume this isn't intentional?

For context on Google Drive website:
Example 1: On the "Shared with me" is a "file.mp4", shared with a public URL. When right-clicking on the file on Google Drive, I can "Add to My Drive" or "Make a copy"

Example 2: On the "Shared with me" is a "video.mp4", shared with a public URL however it is stored in a Team Drive. When right-clicking on the file on Google Drive, I can "Make a copy" but can not "Add to My Drive", only "Star" it.

#### What is your rclone version (output from `rclone version`)

rclone v1.48.0-067-g0a1169e6-beta (was using latest stable)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu linux/amd64 (on Google Colab Notebook)

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone --config "/content/drive/My Drive/Files/rclone.conf" copy "gdrive_mydrive:video.mp4" "gdrive_team:/Uploads" --drive-server-side-across-configs -vv`
gdrive_team is specified as a Team Drive
gdrive_mydrive has shared_with_me=true

This command works with "file.mp4" but not "video.mp4"

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2019/07/15 07:20:21 DEBUG : rclone: Version "v1.48.0-067-g0a1169e6-beta" starting with parameters ["rclone" "--config" "/content/drive/My Drive/Files/rclone.conf" "copy" "gdrive_mydrive:video.mp4" "gdrive_team:/Uploads" "--drive-server-side-across-configs" "-vv"]
2019/07/15 07:20:21 DEBUG : Using config file from "/content/drive/My Drive/Files/rclone.conf"
2019/07/15 07:20:22 ERROR : : error reading source directory: directory not found
2019/07/15 07:20:22 INFO  : Google drive root 'Uploads': Waiting for checks to finish
2019/07/15 07:20:22 INFO  : Google drive root 'Uploads': Waiting for transfers to finish
2019/07/15 07:20:22 ERROR : Attempt 1/3 failed with 2 errors and: directory not found
2019/07/15 07:20:23 ERROR : : error reading source directory: directory not found
2019/07/15 07:20:23 INFO  : Google drive root 'Uploads': Waiting for checks to finish
2019/07/15 07:20:23 INFO  : Google drive root 'Uploads': Waiting for transfers to finish
2019/07/15 07:20:23 ERROR : Attempt 2/3 failed with 2 errors and: directory not found
2019/07/15 07:20:24 ERROR : : error reading source directory: directory not found
2019/07/15 07:20:24 INFO  : Google drive root 'Uploads': Waiting for checks to finish
2019/07/15 07:20:24 INFO  : Google drive root 'Uploads': Waiting for transfers to finish
2019/07/15 07:20:24 ERROR : Attempt 3/3 failed with 2 errors and: directory not found
2019/07/15 07:20:24 Failed to copy with 2 errors: last error was: directory not found

**Comment by animosity22** [comment]
Can you share your rclone.conf and just run a rclone ls -vv against the remote you have configured?  (With passwords and keys removed)

**Comment by Sparoney** [comment]
I did an ``rclone ls -vv`` for the shared drive, however it only lists files in "My Drive", not in "Shared with me" (bug??). I did however notice this in the output:

2019/07/16 06:34:01 DEBUG : pacer: low level retry 1/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=607739441803, userRateLimitExceeded)
2019/07/16 06:34:01 DEBUG : pacer: Rate limited, increasing sleep to 1.497788308s
2019/07/16 06:34:01 DEBUG : pacer: low level retry 2/10 (error googleapi: Error 403: User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=607739441803, userRateLimitExceeded)
2019/07/16 06:34:01 DEBUG : pacer: Rate limited, increasing sleep to 2.217568286s
2019/07/16 06:34:01 DEBUG : pacer: Reducing sleep to 0s

Here's my redacted rclone.conf
[rclone no token.zip](https://github.com/ncw/rclone/files/3395675/rclone.no.token.zip)

**Comment by animosity22** [comment]
403s can mean a few things. That particular one means you should use your own API key and set that up.

https://rclone.org/drive/#making-your-own-client-id

Can you share the full command you are running with the rclone ls -vv?

**Comment by animosity22** [comment]
Also, take note of this with the changes to team drives and shared drives.

https://gsuiteupdates.googleblog.com/2019/04/shared-drives.html

**Comment by ldzhjn** [comment]
I'm also experiencing this bug
With command "rclone ls -vv remote: --drive-shared-with-me", it only shows my private folders and files and don't show team drive shared with me.

Here's the debug log and rclone conf
2019/07/18 10:50:05 DEBUG : rclone: Version "v1.48.0" starting with parameters ["rclone" "ls" "-vv" "remote:" "--drive-shared-with-me"]
2019/07/18 10:50:05 DEBUG : Using config file from "/Users/user/.config/rclone/rclone.conf"
-----------
my private files
-----------
2019/07/18 10:50:08 DEBUG : 12 go routines active
2019/07/18 10:50:08 DEBUG : rclone: Version "v1.48.0" finishing with parameters ["rclone" "ls" "-vv" "remote:" "--drive-shared-with-me"]

Here's rclone.conf
cat /Users/rayliu/.config/rclone/rclone.conf
[remote]
type = drive
client_id = 
client_secret = 
scope = drive
token =

**Comment by Sparoney** [comment]
> 403s can mean a few things. That particular one means you should use your own API key and set that up.

I have done that already

> Also, take note of this with the changes to team drives and shared drives.

This makes no difference the only change is renaming "Team Drives" to "Shared drives"

> Can you share the full command you are running with the rclone ls -vv?

Both `rclone remote: ls --drive-shared-with-me -vv` and `rclone remote: ls -vv` list the exact same files.

**Comment by animosity22** [comment]
Can you post your rclone.conf without passwords and keys?

**Comment by Sparoney** [comment]
[gdrive_team_old]
type = drive
client_id = 
client_secret = 
scope = drive
token = 
team_drive = 
shared_with_me = false
server_side_across_configs = true

[gdrive_shared]
type = drive
client_id = 
client_secret = 
scope = drive
token = 
shared_with_me = true
server_side_across_configs = true

[gdrive_mydrive]
type = drive
client_id =
client_secret = 
scope = drive
token = 
server_side_across_configs = true

[gdrive_team_new]
type = drive
client_id = 
client_secret =
scope = drive
token =
team_drive = 
shared_with_me = false
server_side_across_configs = true

**Comment by animosity22** [comment]
You don't seem to have a remote named "remote:". Can you share the rclone.conf that is being used for the command you are running?

**Comment by animosity22** [comment]
I got a bit further as I was trying to replicate what you are doing and I think I have the same issue replicated as if I use rclone ls, it isn't working, but lsf and lsd seem fine:

```
[felix@gemini ~]$ rclone lsf GD: --drive-shared-with-me -vv
2019/07/19 09:49:37 DEBUG : rclone: Version "v1.48.0" starting with parameters ["rclone" "lsf" "GD:" "--drive-shared-with-me" "-vv"]
2019/07/19 09:49:37 DEBUG : Using config file from "/opt/rclone/rclone.conf"
Test/
2019/07/19 09:49:37 DEBUG : 5 go routines active
2019/07/19 09:49:37 DEBUG : rclone: Version "v1.48.0" finishing with parameters ["rclone" "lsf" "GD:" "--drive-shared-with-me" "-vv"]
[felix@gemini ~]$ rclone lsd GD: --drive-shared-with-me
          -1 2019-07-05 10:33:55        -1 Test
[felix@gemini ~]$ rclone ls GD: --drive-shared-with-me -vv
2019/07/19 09:49:52 DEBUG : rclone: Version "v1.48.0" starting with parameters ["rclone" "ls" "GD:" "--drive-shared-with-me" "-vv"]
2019/07/19 09:49:52 DEBUG : Using config file from "/opt/rclone/rclone.conf"
5702862585 media/n0t3rf73m837rcfpfuefg9fs3o
104883232 media/rpju5hpe3gjgr6j3jt5jtibqvc
      291 media/95tj3q4gj5ban13ppu0kisguco
```

**Comment by animosity22** [comment]
It doesn't work with 1.48/1.47 and works in 1.46:

```
[felix@gemini 146]$ ./rclone -vv ls GD: --drive-shared-with-me
2019/07/19 09:56:16 DEBUG : rclone: Version "v1.46" starting with parameters ["./rclone" "-vv" "ls" "GD:" "--drive-shared-with-me"]
2019/07/19 09:56:16 DEBUG : Using config file from "/opt/rclone/rclone.conf"
       -1 Test/(Public) U22.17.0.1 - Mastery Checklist by ／u／Sekwah.xlsx
       -1 Test/Test2.xlsx
       -1 Test/TestSheet.xlsx
2019/07/19 09:56:17 DEBUG : 4 go routines active
2019/07/19 09:56:17 DEBUG : rclone: Version "v1.46" finishing with parameters ["./rclone" "-vv" "ls" "GD:" "--drive-shared-with-me"]
```

@ncw did something change with rclone ls in later versions?

**Comment by Sparoney** [comment]
> You don't seem to have a remote named "remote:". Can you share the rclone.conf that is being used for the command you are running?

Yeah I know I was just substituting the remote name as `remote:`

> but lsf and lsd seem fine

I actually noticed that too when I was testing. I should've mentioned that sorry.


Anyway, aside from the `rclone ls` command, we need to figure out why files that have been shared in a "Team/Shared drive" to the Shared with me can't be seen in rclone.

**Comment by Sparoney** [comment]
I'm going to test if it works on 1.46

**Comment by Sparoney** [comment]
`rclone ls` does work correctly with 1.46 however files shared via Team/Shared drives still aren't shown.

**Comment by ncw** [comment]
According to the [files list API](https://developers.google.com/drive/api/v3/reference/files/list) you need to set the `supportsTeamDrives` boolean to see files from team drives.

Rclone does that when it is viewing a team drive and not when it isn't so if you share files from a team drive to a non-team drive then they won't appear if listing the non-team drive with `--drive-shared-with-me`

It looks like the API has changed slightly since we last updated the drive backend.

It looks like maybe we should be setting the includeAllDrives flag (also deprecated!) and maybe we should be setting this permanently.

The Drive API used to error if you set includeTeamDrives on non team drives and vice versa.

It looks like some work is needed on the API here which will probably fix this issue.

Can you give this a go?

https://beta.rclone.org/branch/v1.48.0-100-gaa9db160-fix-3348-teamdrive-beta/ (uploaded in 15-30 mins)

**Comment by Sparoney** [comment]
Hey @ncw, just tested this now, and it works! Thank you! Another issue I found is `rclone ls` doesn't show files from Shared with me, but `rclone lsf` does.

**Comment by ncw** [comment]
> Hey @ncw, just tested this now, and it works!

Great!  I'll merge the above now.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.49

> Another issue I found is rclone ls doesn't show files from Shared with me, but rclone lsf does.

Note that `rclone ls` doesn't show directories at all which is the main difference between `lsf` and `ls`.  I'd be suprise if there was a difference betwen the two since they use the same code underneath.  Can you post the output of the commands please?

Can you post the output

**Comment by Sparoney** [comment]
Ok I can't post the output because there's way too many files but basically, this is what happened:
`rclone ls` --> lists files/directories in My Drive only
`rclone lsf` --> lists files/directories in Shared with me only
I'm assuming that both commands should be showing files from Shared with me?

**Comment by ncw** [comment]
> Ok I can't post the output because there's way too many files but basically, this is what happened:
> `rclone ls` --> lists files/directories in My Drive only
> `rclone lsf` --> lists files/directories in Shared with me only
> I'm assuming that both commands should be showing files from Shared with me?

Can you post the command lines you used for each?
