### ISSUE TITLE
ailed to create file system for "OneDrive1:share": failed to get root: serviceNotAvailable: Service unavailable

### ISSUE THREAD

**Issue by piaoyun** [rclone/rclone#3351]
ailed to create file system for "OneDrive1:share": failed to get root: serviceNotAvailable: Service unavailable

rclone version :1.4.8 

server：ubuntu 16.04

请问下怎么解决这个错误呢

**Comment by buengese** [comment]
Could you please describe which exact command you tried to run try running it using `rclone -vv` e.g. `rclone -vv ls OneDrive1: and post the log output?

**Comment by Cnly** [comment]
To me that looks like a temporary server-side issue and should fix itself after some time. Are you still seeing the error?

**Comment by ncw** [comment]
I'm going to close this since we haven't heard back from you. Please feel free to re-open.
