### ISSUE TITLE
1fichier: Support downloading password-protected files in shared folders

### ISSUE THREAD

**Issue by treyturner** [rclone/rclone#3353]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.48.0-067-g0a1169e6-beta
- os/arch: linux/amd64
- go version: go1.12.7

#### What problem are you are trying to solve?
I'm trying to copy files out of a 1fichier shared folder that is not my own, where each file is protected with the same password.

#### How do you think rclone should be changed to solve that?
The 1fichier API seems to allow for the password to be sent along with the request, but the rclone backend for 1fichier does not yet seem to support this, which isn't surprising since 1fichier support is very new (thanks for this!)

From https://1fichier.com/api.html?lg=en:

```
{
  "url" : "https://1fichier.com/?example",
  "inline" : 0/1,
  "cdn" : 0/1,
  "restrict_ip" : 0/1/2,
  "single" : 0/1,
  "pass" : "mot_de_pass",
  "no_ssl" : 0/1,
  "folder_id" : 1234,
  "filename" : "FileName",
  "sharing_user" : "user@example.com"
}
```

```
pass : (optional) Access password to the file, if restricted by password.
```

My suggestion is that a password could be supplied via a `--fichier-shared-password` flag, similar to `--fichier-shared-folder`.

Thanks for your consideration!

**Comment by ncw** [comment]
What do you think @lhaus fancy having a go at this?

A `--fichier-shared-password` flag seems perfect!  This could be an advanced option since I don't think most users will want to set it.

**Comment by Pfuenzle** [comment]
Are there any news regardin this topic?
Im trying to download files from a 1fichier shared folder, but the files now require a password.
When I try to copy, I get this error:
`(error HTTP error 403 (403 Forbidden) returned body: "{\"status\":\"KO\",\"message\":\"Password not provided. Resource not allowed #749\"}")`
Rclone then retries the connection 7 times, after that following errer gets returned:
`(error HTTP error 403 (403 Forbidden) returned body: "{\"message\":\"IP Locked #78\",\"status\":\"KO\"}")`

**Comment by Kcchouette** [comment]
I think this ticket can be close as the PR #5333 has been merged @ivandeex

**Comment by buengese** [comment]
Looks like I did a manual squash and merge there. It's this commit 92b3518c78848d454a7352707fa7c849fd93403a

**Comment by ivandeex** [comment]
@buengese Got you. Thanks
@Kcchouette You are right, it was merged. Closing.
