### ISSUE TITLE
Box: Request change NOTICE message for can't store file with control characters to an ERROR

### ISSUE THREAD

**Issue by nexus667** [rclone/rclone#3365]
#### Output of `rclone version`
rclone v1.48.0
- os/arch: darwin/amd64
- go version: go1.12.6

#### Describe the issue

Using rclone to copy files to Box and I'm double-checking the files counts by using rclone size and comparing against the original directory using find <dir> -type f | wc -l.  And then going back to the logs to find and fix the errors.  If it can not store the file is that not the same as failed to copy which shows up as an ERROR in the log, but can not store shows up as a NOTICE.

**Comment by ncw** [comment]
This will be fixed properly by #3148 when we will be able to upload files with control chars.

**Comment by ivandeex** [comment]
@nexus667 
This bug is reported against obsolete version of rclone. Can you reproduce it with rclone 1.54?

**Comment by ivandeex** [comment]
Rclone now provides the `--backend-encoding` feature that should handle the case reported here.

Closing as the author did not reply.
