### ISSUE TITLE
(Question) exclude certain file types from rclone mount

### ISSUE THREAD

**Issue by xyphos10** [rclone/rclone#3367]
Hello

I would like to know if it is possible to disallow certain file types from being uploaded when using rclone mount with google drive. Example lets say I mounted by gdrive to /mnt/storage and I have the following directories,

/mnt/storage/info.db
/mnt/storage/info.db-shm
/mnt/storage/info.db-wal
/mnt/storage/tmp/radfakdfasdf.partial

Is it possible to tell rclone not to upload any files found on /mnt/storage/tmp and also not to upload /mnt/storage/info.db* whether or not there are any changes. Info.db is an sqlite3 database so if it is uploaded while being accessed it gets corrupted.

**Comment by ncw** [comment]
You can control which files show up in the mount using the rclone filtering options...

However I don't think this is what you want exactly.

Which vfs cache mode are you using?

**Comment by xyphos10** [comment]
I am currently using full mode. The issue I  facing is that the sqlite db is uploaded while still in use so it ends up corrupted.

**Comment by ncw** [comment]
> Ideally what I would need is a way to tell rclone mount to completely ignore any/all changes made to info.db, is this possible?

This isn't possible at the moment.

However I think this is the same request as #2109 - what do you think?

**Comment by xyphos10** [comment]
Yes #2109 is in line with the functionality needed in the case above

**Comment by ncw** [comment]
OK, I'll close this issue then.

Do you want to work on #2109?
