### ISSUE TITLE
Unset environment when RCLONE_CONFIG_PASS is read

### ISSUE THREAD

**Issue by renard** [rclone/rclone#3368]
#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.6
```

#### What problem are you are trying to solve?

When using `RCLONE_CONFIG_PASS` the password is still `accessible in /proc/<PID>/environ`. When the password is read from https://github.com/ncw/rclone/blob/ba72e62b41cbfd6f36ec089a1f58c26d31a57734/fs/config/config.go#L228, wouldn't it be safer to just unset the environment variable using something like this?

```go
_ = os.Unsetenv("RCLONE_CONFIG_PASS")
```

#### How do you think rclone should be changed to solve that?

N/A

**Comment by Cnly** [comment]
I remember having experimented something similar in this issue: https://github.com/ncw/rclone/issues/2442#issuecomment-411460942, but I don't think that works as expected. :(

**Comment by renard** [comment]
That is correct. This almost works using `RCLONE_CONFIG_KEY`.

```echo  "MY_SECRET" | ssh host "RCLONE_CONFIG_KEY=/dev/stdin rclone --config rclone.conf --ask-password ls remote:"```
This works but still displays following in stderr
```
Enter configuration password:
password:
```

Using `RCLONE_CONFIG_PASS` does not.


On the other hand, is the flag `--ask-password=false` is passed there is an error:

```
2019/07/23 21:55:55 Failed to load config file "/home/user/rclone.conf": unable to decrypt configuration and not allowed to ask for password - set RCLONE_CONFIG_PASS to your configuration password
```

Thus `RCLONE_CONFIG_PASS` and `RCLONE_CONFIG_KEY` do not have the same behaviour. Il would be great if they do and if `RCLONE_CONFIG_KEY` were documented somewhere ;-).



Thanks for the tip though.

**Comment by ncw** [comment]
> That is correct. This almost works using `RCLONE_CONFIG_KEY`.
> 
> `echo "MY_SECRET" | ssh host "RCLONE_CONFIG_KEY=/dev/stdin rclone --config rclone.conf --ask-password ls remote:"`

I had a read through the code and I don't think `RCLONE_CONFIG_KEY` is implemented, so I think what you wrote is equivalent to

`echo "MY_SECRET" | ssh host "rclone --config rclone.conf --ask-password ls remote:"`

> This works but still displays following in stderr
> 
> ```
> Enter configuration password:
> password:
> ```

Is that a problem?

**Comment by renard** [comment]
> I had a read through the code and I don't think `RCLONE_CONFIG_KEY` is implemented, so I think what you wrote is equivalent to
> 
> `echo "MY_SECRET" | ssh host "rclone --config rclone.conf --ask-password ls remote:"`

Yes this is correct.

For the 
```
Enter configuration password:
password:
```
display this not quiet a problem but since a password could have been retrieved on stdin, there is no need to display the message. This is cleaner in a non-interactive process.

**Comment by ncw** [comment]
I think the new flag

     --password-command SpaceSepList   Command for supplying password for encrypted configuration.

is probably the best solution to this.

Unfortunately Unsetenv does not change the output of /proc, eg

```go
package main

import (
	"fmt"
	"os"
	"time"
)

func main() {
	os.Unsetenv("POTATO")
	fmt.Printf("Unset in pid %d", os.Getpid())
	time.Sleep(time.Minute)
}
```

```
$ POTATO=hello go run unsetenv.go
Unset in pid 32133
```

In another terminal

```
$ cat /proc/32133/environ | tr '\000' '\n' | grep POTATO
POTATO=hello
```

:-(

So I'm going to close this now.

**Comment by renard** [comment]
> I think the new flag
> 
> ```
>  --password-command SpaceSepList   Command for supplying password for encrypted configuration.
> ```
> 


Almost yes. I think we should bind `stdin` to the process' standard input to allow `cat` as a password command.

at https://github.com/rclone/rclone/blob/master/fs/config/config.go#L284, we should add:

```go
cmd.Stdin = os.Stdin
```
(untested yet).
