### ISSUE TITLE
ncdu: show the folder empty and file empty indicator

### ISSUE THREAD

**Issue by jtagcat** [rclone/rclone#3369]
rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.

ncdu shows empty files as:
@   0.0   B [          ]  emptyfile
..and empty folders as:
e   0.0   B [          ] /emptyfolder

Could rclone ncdu get the indicators as well?

**Comment by ncw** [comment]
This would be relatively easy to add I think - we have the info already.

Is there a list of all the indicators that `ncdu` can produce?  I didn't see them in the man page

I don't see the `@` indicator when I try it with ncdu though?

![image](https://user-images.githubusercontent.com/536803/62130850-cab0bc80-b2d1-11e9-821b-fa7c3caab4aa.png)

Would you like to implement this?

**Comment by jtagcat** [comment]
Unfortunately I don't do go. If I ever get in to go, I can look in to it. Currently I would suggest marking this as good first issue.

**Comment by ncw** [comment]
Ok no probs.  WIll do :-)

**Comment by yairm** [comment]
I think I found the legend in ncdu

**Comment by ncw** [comment]
Ah ha!  We could certainly implement some of those...

**Comment by albertony** [comment]
Here's a ncdu manpage for Ubuntu, showing the same flags with a few more words in the description, as well as one additional flag `^`: http://manpages.ubuntu.com/manpages/impish/man1/ncdu.1.html#file%20flags

**Comment by jtagcat** [comment]
- [x] `!  An error occurred while reading this directory`
 - [x] `.  An error occurred while reading a subdirectory`
 - [ ] `<  File or directory is excluded from the statistics` (rclone: `--exclude`)
    - Excluded files are not listed at all.
 - [x] `e  Empty directory`
    - Currently, special files are treated as empty directories, in both
        - listings (`rclone ncdu /dev/cpu`)
        - root dirs (`rclone ncdu `/dev/full`)
 - [ ] ~~`>  Directory was on another filesystem`~~
 - [ ] ~~`@  This is not a file nor a dir (symlink, socket, ...)`~~
 - [ ] ~~`^  Excluded Linux pseudo-filesystem`~~
 - [ ] ~~`H  Same file was already counted (hard link)`~~
 - [ ] ~~`F Excluded firmlink`~~

I think most of these are not relevant, as they would pretty much only be a thing on local filesystems, where ncdu (and a variety of other clones) may be used. It is just too much out of scope.

**Comment by jtagcat** [comment]
Closing issue as it is merged, see above for possible continuations.
