### ISSUE TITLE
filter: exclude=d/ should behave alike what exclude=d/** does

### ISSUE THREAD

**Issue by pjw91** [rclone/rclone#3375]
As discussed in [the forum](https://forum.rclone.org/t/fast-list-changes-behavior-of-exclude/10946), `--exclude d/` and `--exclude 'd/**'` works differently and this difference causes `sync`/`copy` mistakenly delete some files on the remote when `--fast-list` is ON.

Making `--exclude=d/` works alike `--exclude=d/**` would be OK.

**Comment by ncw** [comment]
I've made an implementation of this here

[v1.54.0-beta.4847.51e810828.fix-3375-filter-dir](https://beta.rclone.org/branch/fix-3375-filter-dir/v1.54.0-beta.4847.51e810828.fix-3375-filter-dir/) on branch [fix-3375-filter-dir](https://github.com/rclone/rclone/tree/fix-3375-filter-dir) (uploaded in 15-30 mins)

**Comment by ivandeex** [comment]
Closed after 4 months of inactivity
@ncw appears that branch [fix-3375-filter-dir](https://github.com/rclone/rclone/tree/fix-3375-filter-dir) can be purged

**Comment by ncw** [comment]
Thanks @ivandeex  - I've now merged the above and deleted the branch!
