### ISSUE TITLE
Let rclone remember the files that were copied in the session

### ISSUE THREAD

**Issue by theghost970** [rclone/rclone#3376]
#### What is your current rclone version (output from `rclone version`)?

v1.48

#### What problem are you are trying to solve?

Check out this picture: https://i.imgur.com/n92RUU9.png
I have created ~200 Service Accounts to server-side copy from a Team Drive to a Team Drive.
What I did is I created a batch file listing all the command lines for copying (a line for each Service Account) with a bandwidth limit of 740GB, so when rclone finishes from one SA and goes to the other SA (the second line), it goes through all files and folders that have been already copied by the previous service account.
So in my case, rclone takes ~45 minutes to go through all the files that have been already copied in the previous line and ignores them, and when it comes to new, uncopied contents, it takes ~7 minutes to copy them till it hits the limit and goes to the second line.. The same happens with every line. 

#### How do you think rclone should be changed to solve that?

Let rclone list the files it copied in a certain session store it in a text file, and when the copy line is executed it goes to that text file and ignores everything that's listed there. (it'll be a lot faster in checking the text file than checking them online).

Windows 10, by the way.

Thank you for everything you're doing for us!

**Comment by theghost970** [comment]
Basically, is there a way to make rclone "remember" the files it copied in the past 24 hours and skip checking them every time with each Service Account?

**Comment by ncw** [comment]
If you have a list of files, then use `--files-from` to pass it in - that will speed things up.

You can also consider `--no-traverse` which may speed things up too.

**Comment by animosity22** [comment]
Question looks to be answered. If you need help, please ask on the forums!
