### ISSUE TITLE
Make rclone config passwd act as sudo passwd

### ISSUE THREAD

**Issue by jtagcat** [rclone/rclone#3386]
#### Output of `rclone version`
rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.6

Currently, when you use rclone, you need to enter the passwd every time. Could it maybe act like the sudo password, that it will be stored for x minutes in the terminal window? I'd actually prefer it stored until the window is closed.

**Comment by ncw** [comment]
You can do this with a small shell script or an alias

    alias rclonepass='read -s RCLONE_CONFIG_PASS; export RCLONE_CONFIG_PASS'

just run `rclonepass` to read the password into that environment variable and it will last for the duration of the terminal session.

**Comment by jtagcat** [comment]
I wish that could happen automatically before an rclone command is ran. I haven't done go before therefore I opened an issue.

**Comment by gadfly0x** [comment]
nice

**Comment by ncw** [comment]
`sudo` works by keeping an on disk database of things in `/var/run/sudo` I think.  Rclone would have to do something similar to make this work exactly like sudo, and it would have to actually store the password on disk.  I'm not dead keen on doing either.

Perhaps a better idea would be integrate rclone with the OSes keyring manager maybe using a library like this: https://github.com/zalando/go-keyring

**Comment by marco-m** [comment]
There is also another option, at the same security than integrating with the OS keyring, which can be done today with zero code changes: using a secure tool to make the `RCLONE_CONFIG_PASS`environment variable visible.

I know at least 2 such tools:

1. [envchain](https://github.com/sorah/envchain) for macOS and Linux.
2. [gopass](https://github.com/gopasspw/gopass) for macOS, Linux and Windows.

For example with `envchain`, the rclone invocation `rclone ...` would need to be prepended by

```
$ envchain MYCONFIG rclone ...
```

**Comment by marco-m** [comment]
> Perhaps a better idea would be integrate rclone with the OSes keyring manager maybe using a library like this: https://github.com/zalando/go-keyring

I investigated a bit that library. Following some PRs there, I found alternative https://github.com/keybase/go-keychain, which seems to be better maintained.

**Comment by ankur0493** [comment]
> I investigated a bit that library. Following some PRs there, I found alternative https://github.com/keybase/go-keychain, which seems to be better maintained.

https://github.com/keybase/go-keychain is only for macOS and Linux whereas https://github.com/zalando/go-keyring supports windows as well.

**Comment by ncw** [comment]
Now that rclone supports the [--password-command](https://rclone.org/docs/#password-command-spaceseplist) flag it should be easy to integrate any 3rd party password manager provided they have a cli interface.

I think that is my preferred solution for the moment, rather than attempt to integrate a myriad of password managers.

What do you think?

**Comment by ivandeex** [comment]
@jtagcat @marco-m @ankur0493 
Please try `rclone --password-command` with envchain or gopass (see links to commands above).

**Comment by marco-m** [comment]
Hello @ivandeex I think there is a misunderstanding here. Both `envchain` and `gopass` already worked with `rclone`, even before the `--password-command`, since these two tools work by setting the `RCLONE_CONFIG_PASS` environment variable. Or am I missing something ?

**Comment by ivandeex** [comment]
@marco-m 
Do you mean this issue can be closed?

**Comment by marco-m** [comment]
> Do you mean this issue can be closed?

To my understanding yes. The [first comment](https://github.com/rclone/rclone/issues/3386#issuecomment-554641150) I wrote on this issue was already to propose an alternative to the OP.

Note on the other hand that I am not the OP :-)

And thanks for your housekeeping work, closing stale stuff is good.

**Comment by ivandeex** [comment]
@jtagcat Does your problem persist?
