### ISSUE TITLE
Google Drive dedupe is case sensitive, while sync is case insensitive

### ISSUE THREAD

**Issue by leoccyao** [rclone/rclone#3389]
Similar to [#2430](https://github.com/rclone/rclone/issues/2430), but for files.

#### What is the problem you are having with rclone?

A rclone dedupe on a Google Drive folder works normally, reporting no duplicate files. However, syncing down to local disk fails as files such as "IMG_0964.JPG" and "IMG_0964.jpg" (found via rclone ncdu) still remain on Google Drive (extensions differ only in case).

#### What is your rclone version (output from `rclone version`)

rclone v1.48.0-099-gc2635e39-beta
os/arch: windows/amd64
go version: go1.12.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive (more specifically the Google Photos folder)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone dedupe rename "personaldrive:Google Photos" --tpslimit 10
then
rclone sync "personaldrive:Google Photos" "Google Photos" -P --tpslimit 10 --bwlimit=2M

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

[dedupeout-beta.txt](https://github.com/rclone/rclone/files/3447487/dedupeout-beta.txt)
[syncout-beta.txt](https://github.com/rclone/rclone/files/3447489/syncout-beta.txt)

**Comment by ncw** [comment]
The sync is case insensitive because you are using Windows.

However drive is case sensitive!

Adding a `--case-insensitive` flag to dedupe would be fairly easy - fancy having a go?

**Comment by leoccyao** [comment]
Closing as it's been a while and I no longer use this specific functionality. If it's still an issue in latest version and someone else wants to have a go feel free to do so!

**Comment by dzg** [comment]
Was anything ever done here?  
I am trying to sync a massive drive to local – and it's reporting dupes errors – where it's a difference of case on the drive side. So `dedupe` does not fix. I have thousands of these.
