### ISSUE TITLE
show available space calculated from --cache-dir instead of assuming 1P

### ISSUE THREAD

**Issue by nathanshearer** [rclone/rclone#3391]
When a mount point is setup with `--vfs-cache-mode writes` and `--cache-dir /some/path` the free space shown with `df -h` is 1P, however, the actual free space to write data at /some/path is typically much less. Please add an option to have the mount point show the free space at /some/path instead of always 1P so that tests on free space can pass/fail appropriately.

**Comment by ncw** [comment]
The free space show is that returned by the remote underneath the cache layer.

Not all remotes support showing you the free space though. 

Which backend are you using?

What does `rclone about remote:` where remote: is your backend under the crypt?

**Comment by nathanshearer** [comment]
My remote is a google drive mount, and Google drive does indeed show and probably have 1P of space available. However my writable cache-dir is only a 500GB drive, so if I have a script check free space before attempting to write 600GB then it will think there is enough space to start that lengthy task, then have some major problems when the cahe dir fills up at the 500GB mark. It would be nice if I could enable the free space to be calculated from both the remote and the cache directly, and have it use the lesser of the two. As the cache directory is used and emptied then the free space would update accordingly.

**Comment by ncw** [comment]
I think you must be using an old version of rclone, I get this on the crypted drive

```
$ rclone about TestCryptDrive:
Total:   15G
Used:    1.576G
Free:    13.424G
Trashed: 1.258G
Other:   0
```

and

```
$ df -h /mnt/tmp/
Filesystem       Size  Used Avail Use% Mounted on
TestCryptDrive:   15G  1.6G   14G  11% /mnt/tmp
```

Can you try [the latest release](https://rclone.org/downloads/) or [the latest beta](https://beta.rclone.org)?

**Comment by nathanshearer** [comment]
Sure, I'll sync my system and re-test both my free google account and my gsuite accounts

**Comment by animosity22** [comment]
This looks to be answered. If you have any questions, please use the forums.
