### ISSUE TITLE
runtime.newosproc

### ISSUE THREAD

**Issue by dannymichel** [rclone/rclone#3394]
Is this ``runtime.newosproc`` an issue because i'm trying to upload 700 files at a time?

**Comment by buengese** [comment]
Could you please try sticking to issue template? These kind of questions really don't tell us anything. Please include at least the command you were trying to run and the actual error output rclone produced.

**Comment by dannymichel** [comment]
```
runtime.startm(0x0, 0x100000000)
        /home/travis/.gimme/versions/go1.12.7.linux.amd64/src/runtime/proc.go:1977 +0x12c
runtime.injectglist(0xc0005d7ee0)
        /home/travis/.gimme/versions/go1.12.7.linux.amd64/src/runtime/proc.go:2462 +0x146
runtime.findrunnable(0xc000072f00, 0x0)
        /home/travis/.gimme/versions/go1.12.7.linux.amd64/src/runtime/proc.go:2228 +0x9dc
```
when i do
```
rclone copy --progress --fast-list --no-traverse --transfers=1700 /media/bef2/aivit/media/upload/ drive:/media/
```

**Comment by buengese** [comment]
Well yeah rclone is probably running into your process/thread limit. You really shouldn't be running 1700 transfers at same time. Something like 16 transfers should be enough to saturate even a very fast connection.

**Comment by ncw** [comment]
> Is this `runtime.newosproc` an issue because i'm trying to upload 700 files at a time?

Can you paste the complete traceback please?

**Comment by robertbaker** [comment]
The drunk-chunk-size controls upload speed. Checkers and Transfers just make things slower...

Drive-Chunk-Size default should be 128 or 256MB IMO.

**Comment by ncw** [comment]
My guess would be you are running out of memory.  It will say the cause at the very top of the traceback.

**Comment by animosity22** [comment]
If you still have a question, please use the forums and we're happy to help out.
