### ISSUE TITLE
Onedrive Shared folders not listing

### ISSUE THREAD

**Issue by necrogami** [rclone/rclone#3397]
#### What is the problem you are having with rclone?
Unable to read/list Onedrive shared folders.

#### What is your rclone version (output from `rclone version`)
```
$ rclone version
rclone v1.48.0
- os/arch: darwin/amd64
- go version: go1.12.6
```
```
$ ./rclone version
rclone v1.48.0-103-g6a3e3013-beta
- os/arch: darwin/amd64
- go version: go1.12.7
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
OSX Mojave 10.14.6/64bit

####  Which cloud storage system are you using? (eg Google Drive)
Onedrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone lsd -vv Onedrive:`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2019/08/02 19:41:31 DEBUG : rclone: Version "v1.48.0-103-g6a3e3013-beta" starting with parameters ["./rclone" "lsd" "-vv" "Onedrive:"]
2019/08/02 19:41:31 DEBUG : Using config file from "/Users/necrogami/.config/rclone/rclone.conf"
          -1 2019-03-14 23:26:09         5 2019-03-14_00-15
          -1 2019-05-10 10:04:29         1 Documents
          -1 2017-01-04 06:57:58         0 Email attachments
          -1 2019-01-09 19:55:14         1 Floatplane
          -1 2019-01-01 18:40:57        18 GoLang
          -1 2015-05-30 01:29:00         1 Laracasts
          -1 2018-09-05 19:05:26         0 Music
          -1 2016-07-31 13:39:25         5 Pictures
2019/08/02 19:41:32 DEBUG : 7 go routines active
2019/08/02 19:41:32 DEBUG : rclone: Version "v1.48.0-103-g6a3e3013-beta" finishing with parameters ["./rclone" "lsd" "-vv" "Onedrive:"]
```

**Comment by Cnly** [comment]
Hi, I just tested with the same version and it worked for me. Could you confirm that you are using OneDrive for Personal, and that you see the shared folder(s) in the "Files" tab in the web app?

**Comment by necrogami** [comment]
I am using personal, I don't see the shared folder under files i see it under shared tab.

**Comment by necrogami** [comment]
I've figured this out. I added the folder to my main files section and now it shows up. Closing
