### ISSUE TITLE
webdav reverse proxy path 

### ISSUE THREAD

**Issue by cyayon** [rclone/rclone#3398]
#### What is your current rclone version (output from `rclone version`)?
rclone 1.48

#### What problem are you are trying to solve?
When using rclone serve webdav behind a reverse proxy (nginx), it is not possible to use a location /rclone (for example). It worked perfectly if it is a vhosts on root url /.

#### How do you think rclone should be changed to solve that?
Define a new option to allow a specific url context /xxxx when using rclone serve webdav.

Thanks.

**Comment by ncw** [comment]
This should be fairly easy...

I propose to add a new flag to `rclone serve http` and `rclone serve webdav` maybe `--url-path`

This will default to "" to serve from `/` but you could change it to `/rclone`.

This will make your life proxying rclone much easier!

**Comment by cyayon** [comment]
Perfect!

**Comment by ncw** [comment]
Can you  give this a go?  I ended up calling the flag `--prefix`, so `--prefix /rclone` should do it

https://beta.rclone.org/branch/v1.48.0-109-ga39ca99d-fix-3398-url-prefix-beta/ (uploaded in 15-30 mins)

**Comment by cyayon** [comment]
Hi,

It works perfectly !
do you plan to include this feature in the next release please ?

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.49

**Comment by ncw** [comment]
Note that I'm renaming this flag `--baseurl` for the 1.49 release as it is a standard name for the flag/feature.

**Comment by ncw** [comment]
@negative0 I think think this should work shouldn't it? I'm sure I remember discussing it!

@ItsCinnabar can you put this [in a new issue](https://github.com/rclone/rclone-webui-react/issues/new) on the web GUI github? Thanks
