### ISSUE TITLE
Rclone not matching GDrive contents

### ISSUE THREAD

**Issue by WindfallProphet** [rclone/rclone#3401]
Note: Rclone Forums aren't accessible. Getting a "Corrupted Content Error" so I apologize for posting here. 
#### What is the problem you are having with rclone?

Rclone ls gdrive: shows phantom files or files which are not (or not yet) uploaded to the cloud. I ran rclone copy -vvv and got: "DEBUG : 6 go routines active" which may be relevant. 

#### What is your rclone version (output from `rclone version`)

rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.5

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Fedora Server 64bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy test.txt google:.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2019/08/03 20:15:00 DEBUG : rclone: Version "v1.48.0" starting with parameters ["rclone" "ls" "google:" "-vvv"]
2019/08/03 20:15:00 DEBUG : Using config file from "~/.config/rclone/rclone.conf"
       12 from_server.txt
  1560010 Getting started
   241754 duc.png
       12 Crypt/from_server.txt
2019/08/03 20:15:01 DEBUG : 6 go routines active
2019/08/03 20:15:01 DEBUG : rclone: Version "v1.48.0" finishing with parameters ["rclone" "ls" "google:" "-vvv"]

**Comment by ncw** [comment]
> Note: Rclone Forums aren't accessible. Getting a "Corrupted Content Error" so I apologize for posting here.

They are working for me... Try clearing cookes for forum.rclone.org?

> #### What is the problem you are having with rclone?
> Rclone ls gdrive: shows phantom files or files which are not (or not yet) uploaded to the cloud. I ran rclone copy -vvv and got: "DEBUG : 6 go routines active" which may be relevant.

Rclone is unlikely to be making up files, so either
1. you really have those files - check the web interface
2. you connected rclone to the wrong account

I presume you've ruled out 1.  2. is really easy to do if you have multiple accounts (I've done it myself many times!).  Note that you can copy the URL rclone prints when it pops up a browser windows and paste it into an incognito session to be sure you are getting the right drive.

**Comment by WindfallProphet** [comment]
Yup, seems like it was 2. When I was trying to access cloud it kept switching accounts. 

And the forums seems to be something on my end. Never saw that error before. Thanks for the help!
