### ISSUE TITLE
purge with --drive-trash-only should error out

### ISSUE THREAD

**Issue by bulls23nt** [rclone/rclone#3407]
#### What is the problem you are having with rclone?
When the purge command is used together with the --drive-trashed-only flag it still will purge non trashed items. rclone should exit with an error since --drive-trashed-only doesn't apply to the purge command. 

#### What is your rclone version (output from `rclone version`)
rclone version
rclone v1.48.0

os/arch: windows/amd64
go version: go1.12.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone purge remote: --drive-trashed-only

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

https://forum.rclone.org/t/drive-trashed-only-weird-occurrence/11066/14
@NCW asked me to create a github issue so he wouldn't forget about this.

**Comment by ncw** [comment]
This would make a great first issue for someone.

The Purge function

https://github.com/rclone/rclone/blob/99eaa76dc80e310aa1cea7bcec1de742e61de339/backend/drive/drive.go#L1940

 just needs to check the TrashedOnly flag

https://github.com/rclone/rclone/blob/99eaa76dc80e310aa1cea7bcec1de742e61de339/backend/drive/drive.go#L433 

and return a sensible error message.

**Comment by ncw** [comment]
Thanks to first time contributor @ginvine we have a fix for this :-)

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.49
