### ISSUE TITLE
Copyurl skip on 403/404 error 

### ISSUE THREAD

**Issue by nishkalprakash** [rclone/rclone#3409]
#### What is the problem you are having with rclone?
`copyurl` command seems to download the file without checking the results of the HTTP response.
Can copyurl command check the http response code and not copy on the following errors?
403 - Forbidden
404 - File does not exist

#### What is your rclone version (output from `rclone version`)
rclone v1.48.0-114-gd51a9709-beta
- os/arch: windows/amd64
- go version: go1.12.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
HTTP link storing in Local Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copyurl "http://examples.com/file_does_not_exist" E:/filename.txt -vv

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

> 
> 2019/08/05 23:19:41 DEBUG : rclone: Version "v1.48.0-114-gd51a9709-beta" starting with parameters ["rclone" "copyurl" "http://examples.com/file_does_not_exist" "E:/filename.txt" "-vv"]
> 2019/08/05 23:19:41 DEBUG : Using config file from "C:\\Users\\nishk\\Documents\\DarKSkuLL\\rclone\\rclone.conf"
> 2019/08/05 23:19:43 DEBUG : Local file system at \\?\E:\: File to upload is small (17364 bytes), uploading instead of streaming
> 2019/08/05 23:19:43 INFO  : filename.txt: Copied (new)
> 2019/08/05 23:19:43 INFO  :
> Transferred:       33.914k / 33.914 kBytes, 100%, 123.408 kBytes/s, ETA 0s
> Errors:                 0
> Checks:                 0 / 0, -
> Transferred:            2 / 2, 100%
> Elapsed time:       200ms
> 
> 2019/08/05 23:19:43 DEBUG : 7 go routines active
> 2019/08/05 23:19:43 DEBUG : rclone: Version "v1.48.0-114-gd51a9709-beta" finishing with parameters ["rclone" "copyurl" "http://examples.com/file_does_not_exist" "E:/filename.txt" "-vv"]

#### IDM download screenshot
![image](https://user-images.githubusercontent.com/42577624/62484454-d6234c80-b7d7-11e9-8937-8f9414a071d0.png)

**Comment by ncw** [comment]
CopyURL is not checking the HTTP status like it should!

https://github.com/rclone/rclone/blob/d51a970932fc5b6af551b1e663bd184f2083efe6/fs/operations/operations.go#L1574-L1584

Here is a potential fix - can you give it a go?

https://beta.rclone.org/branch/v1.48.0-114-g1d0d650e-fix-3409-copyurl-beta/ (uploaded in 15-30 mins)

**Comment by nishkalprakash** [comment]
Great!
It works just fine.

Log:
2019/08/06 06:06:09 DEBUG : rclone: Version "v1.48.0-114-g1d0d650e-fix-3409-copyurl-beta" starting with parameters ["rclone" "copyurl" "http://examples.com/file_does_not_exist" "E:/filename.txt" "-vv"]
2019/08/06 06:06:09 DEBUG : Using config file from "C:\\Users\\nishk\\Documents\\DarKSkuLL\\rclone\\rclone.conf"
2019/08/06 06:06:12 ERROR : Attempt 1/3 failed with 1 errors and: CopyURL failed: 404 Not Found
2019/08/06 06:06:17 ERROR : Attempt 2/3 failed with 1 errors and: CopyURL failed: 404 Not Found
2019/08/06 06:06:18 ERROR : Attempt 3/3 failed with 1 errors and: CopyURL failed: 404 Not Found
2019/08/06 06:06:18 Failed to copyurl: CopyURL failed: 404 Not Found

**Comment by nishkalprakash** [comment]
Hi,
Has this change been pushed with the latest beta?

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.49
