### ISSUE TITLE
GDrive config file gets erased every couple of weeks on Raspberry pi

### ISSUE THREAD

**Issue by tou2** [rclone/rclone#3411]
#### What is the problem you are having with rclone?

I have an rclone installed on a raspberry pi, I move files (2-20 MB) automatically to gdrive between 3 to 5 times everyday with one hour between each time the command run
The problem: every couple of weeks I find the config file empty and I have to create a new one manually.  

#### What is your rclone version (output from `rclone version`)

rclone v1.47.0
- os/arch: linux/arm
- go version: go1.12.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux raspberrypi 4.19.42-v7+

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

The command is executed as a part of a python script that runs in the background:

`sleep 10 && nohup rclone  move /folder1/ remote_name:remote_folder --include *.mp4 ; sleep 10 && nohup rclone  move /folder2/  remote_name:remote_folder2 --include *.ts  &>/dev/null &`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Nothing wrong now because I had to manually fix it because its in a production setting, but it have been happening constantly for the past 6 months.
I will update the log when happens again, sorry.

**Comment by ncw** [comment]
Could the rpi disk be getting full?  That might cause the empty files, though I thought we had fixed that.

Rclone writes to the config file to store the new tokens when it receives them from Google Drive.

If rclone had a problem writing the config file then there should be an ERROR log somewhere.

**Comment by tou2** [comment]
The pi never pass 25% of disk capacity and rclone didn't generate errors, the config jut becomes empty every 2- 3 weeks, I am not quite sure if its same period. 
I will try to find the OS logs, but nothing in rclone logs.

**Comment by ncw** [comment]
> The pi never pass 25% of disk capacity and rclone didn't generate errors, the config jut becomes empty every 2- 3 weeks, I am not quite sure if its same period.

Strange... 

Rclone writes a new config file like this
- it opens a temporary file in the config directory
- it writes to that file
- it renames the config to .old
- it renames the new config to the correct name

So if you look in the directory that the config file is in do you see any other files from that process?  They will all start with the name of the config file.

> I will try to find the OS logs, but nothing in rclone logs.

It might be worth trying [the latest release](https://rclone.org/downloads/) - that wil have been compiled with a later go version than 1.47.  Or [the latest beta](https://beta.rclone.org).

**Comment by animosity22** [comment]
Let us know on the forums if you are still seeing an issue and we can help debug as this issue looks stale.

**Comment by tou2** [comment]
I have installed a new raspbian OS on a brand new high endurance SD card, I have also installed the latest rclone version 1.51.0.
I also created my own google api app after reading about google's rclone quote issue.
I have followed these step to install rclone and the google api app:
https://medium.com/@artur.klauser/mounting-google-drive-on-raspberry-pi-f5002c7095c2

Everything worked perfectly for about a week then I was checking the api metrics attached below it showed that it received requests for a week. Then I checked the Raspbery Pi and the `rclone config` there was no remotes found.
I also checked the config file directory  `/.config/rclone`  and it only had an empty config file.

![GoogleApiTraffic](https://user-images.githubusercontent.com/706122/76345521-e48b9680-62d9-11ea-8c7b-ffcc7b33dfc0.png)

**Comment by ncw** [comment]
> I also checked the config file directory `/.config/rclone` and it only had an empty config file.

Config files don't normally just disappear... Did the disk get full? Was there an unclean shutdown? There may be an old version of the config file in `/.config/rclone`.

**Comment by tou2** [comment]
The disk didn't git full and there is nothing else in `/.config/rclone` other than an empty config file.

It does get unplugged by the end of the day but what would an unclean shutdown do to the content of a file on disk?

**Comment by animosity22** [comment]
Sure. Unclean shutdown have odd issues. Always best to shut down cleanly as that can cause file system oddities.

**Comment by tou2** [comment]
I will try again for another month without unclean shutdowns but it is odd the same file gets erased for the fifth time.

**Comment by ncw** [comment]
Files which get written to are in danger on an unclean shutdown.

I just realised rclone could help here by syncing the file so I've added an `fsync` to the config writing procedure which should probable help.  You can find that in [the latest beta](https://beta.rclone.org) in about 30 minutes.
