### ISSUE TITLE
Upload files through the rc

### ISSUE THREAD

**Issue by innovate-invent** [rclone/rclone#3412]
#### What problem are you are trying to solve?
The rcd REST api is useful for web clients. I am working on a javascript interface for browsers.
Currently there is no way to transfer data directly from the browser to a remote.

#### How do you think rclone should be changed to solve that?
It would be very useful if the cat and rcat options were given their own api endpoints.
rcat would need to accept multipart/form-data for large uploads.
cat would be good to support the `Range`, `Content-Range`, and `Content-Length` headers.

**Comment by ncw** [comment]
Rclone supports sending files from rc to the browser with --rc-serve.  This supports `Range` and replies with `Content-Range` and `Content-Length`.

Rclone doesn't suport sending files from the browser to the rc yet.

Would a multipart POST be easy to use from the browser?

It would be easier for me if we made it so it used POST to the desired path of the file but the body was just the file contents.  If the user supplied `Content-Length` then rclone can upload it normally otherwise it will have to use Rcat.  The user could then supply `Content-Type` and `X-Rclone-Mtime` to supply the modified time of the file in some format to be determined!

**Comment by innovate-invent** [comment]
I believe a multipart POST is readily supported by most agents. If you don't use multipart then I believe things start to have issues when the file size is large. I could be totally wrong about that though.

**Comment by ncw** [comment]
> I believe a multipart POST is readily supported by most agents. If you don't use multipart then I believe things start to have issues when the file size is large. I could be totally wrong about that though.

Multipart just means that the HTTP request has other parts to it, the file is still sent as one long blob so I think either approach will be the same for memory usage.

> Can you point me to the documentation on how to form a GET request to rc to request a remote:

https://rclone.org/rc/#rc-serve

**Comment by innovate-invent** [comment]
hm, I remember talking to someone who has experience with this. Basically the idea is that the server needs to support chunking the upload or else intermediate proxies will get angry and kill the connection. There is a mechanism that agents employ to do this transparently, and for some reason I remember it having to do with multipart/form-data. I'll see if I can contact that person again.

**Comment by ncw** [comment]
Maybe you mean [chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding)?  Rclone will support that no problem as it is part of the Go standard library.

In general you either need a `Content-Length` or you need to use chunked transfer encoding, though you can use them both.

**Comment by innovate-invent** [comment]
I honestly know know what I mean, I am just parroting a conversation I vaguely remember. It is just important for my use that this cleanly support transfers upwards of 100Gb. I am aware that http is not well suited for transfers of that scale but there will be situations where all I have is port 80.

**Comment by ncw** [comment]
> I was pointed to a PR that describes what that conversation was talking about: [galaxyproject/galaxy#5516](https://github.com/galaxyproject/galaxy/pull/5516)

Oh, I see, that is resumable uploads... That would be possible with a bit more work!

**Comment by innovate-invent** [comment]
I was looking into this a bit and found a standard with existing GO library for resumable uploads and other features: https://github.com/tus/tusd/blob/master/docs/usage-package.md
