### ISSUE TITLE
Copyurl command get file name from server

### ISSUE THREAD

**Issue by nishkalprakash** [rclone/rclone#3420]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.48.0-132-gd0c65b4c-beta
- os/arch: windows/amd64
- go version: go1.12.3

#### What problem are you are trying to solve?
Copyurl could be able to get the file name from the server.

The url looks something like:
http://example.com/download.php?id=4460

On calling the url, it returns a status 302 and redirects to:
http://example.com/filename.txt?verify=1565166562-3oMSduA%2FXDukfrcavrhUdJn0FFN%2FlxKxmRxoJ2zQa8%3D

so if the following command was used:
rclone copyurl "http://example.com/download.php?id=4460" gd:folder1/

the file `filename.txt` would get saved in folder `folder1`.

#### How do you think rclone should be changed to solve that?
Maybe it could be made, if a destination ending in / was passed, rclone would use the leaf name of the file in the URL (after any redirection).

**Comment by kfur** [comment]
@nishkalprakash  good proposal
but how do u think what must be expected behavior must be in case when url doesn't contain filename ?

**Comment by nishkalprakash** [comment]
Post redirect if the url doesn't contain a file name then rclone can fallback to the same mechanism where a filename needs to be provided.
Maybe something like:
`rclone copyurl :http: --http-url http://example.com?id=123 --default-name file1.txt`

Here, lets suppose:
If the site redirects to:
http://example.com/**ActualFile.txt**?idtoken=123ab123ef
Then rclone saves the url as `ActualFile.txt`
else 
saves the file as `file1.txt`

if rclone cant find a name in the end and --default-name is missing then maybe an error can be shown:
ERROR - Unable to find a file name, please provide --default-name to avoid this error...
or something

**Comment by nishkalprakash** [comment]
maybe we can just add a new flag to the existing `copyurl`, `--get-name-from-url` ...
`rclone` tries to get the name from the url after the last redirect, 
else does the same thing which rclone currently does with `copyurl`

**Comment by kfur** [comment]
it was resolved i think
