### ISSUE TITLE
Allow uploading by folder id on Box

### ISSUE THREAD

**Issue by YenForYang** [rclone/rclone#3422]
#### What problem are you are trying to solve?
Nearly a year ago I posted an [Allow uploading by folder id on Google Drive](https://github.com/rclone/rclone/issues/2329), which eventually lead to my discovery of `RCLONE_DRIVE_ROOT_FOLDER_ID` and `--drive-root-folder-id`. 

Well, I've been using Box lately, which also has folder ids it seems. These IDs appear to be numeric e,g,
`https://XXXXX.app.box.com/folder/1234567890`

#### How do you think rclone should be changed to solve that?

I'm not aware of any root folder id variable or flag on `rclone` for the Box remote. But I'm guessing it can be added?

**Comment by ncw** [comment]
This would be relatively easy to do - you'd need to replace `rootID` which is a constant `0` at the moment with an option `--box-root-folder-id`.

Note that you can see the IDs of folders in box with

    rclone lsf --dirs-only -F ip TestBox:

**Comment by phillipahereza** [comment]
@ncw can I work on this?

**Comment by ncw** [comment]
> @ncw can I work on this?

Absolutely :-)  Do you need any help more than the hint above?

**Comment by phillipahereza** [comment]
@ncw I think I should be able to manage with the hint above, if not I'll hit you up

**Comment by ncw** [comment]
Add it to the options in the box backend and it will appear in the configurator and as a command line option. It should probably be an advanced option.

Then people can put it in the config file or in the command line or as an environment variable whatever they choose.

**Comment by ncw** [comment]
I've merged @Sunil-P 's fix to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52
