### ISSUE TITLE
Command genautocomplete output to stdout

### ISSUE THREAD

**Issue by pataquets** [rclone/rclone#3423]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.47.0-DEV

#### What problem are you are trying to solve?
Scripting the `genautocomplete` installation

#### How do you think rclone should be changed to solve that?
Just adding a `--stdout` switch or similar to command

**Comment by ncw** [comment]
How about writing to stdout if the output file was `-`?

Fancy sending a PR for that?

**Comment by pataquets** [comment]
I think my go-fu is not quite sufficient, although I didn't tried it. Just dropped the idea and moved on, since it's marginally useful for me, atm.
I've even tried to build rclone from source inside a Dockerfile (to send it a PR later) and failed at it, so I've left it for until my skills improve. I'm pretty sure it's quite standard build, but not enough for my knowledge and a couple how-to s out there 
 Any build advice?

**Comment by ncw** [comment]
These instruction should work: https://rclone.org/install/#install-from-source

**Comment by lasombra** [comment]
@ncw I'll take a look at this one, if you don't mind

**Comment by Cnly** [comment]
Closing as the relevant PR has already been merged.
