### ISSUE TITLE
Google Play Music backend (uploader)

### ISSUE THREAD

**Issue by pataquets** [rclone/rclone#3425]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.47.0-DEV
- os/arch: linux/amd64
- go version: go1.12.6

#### What problem are you are trying to solve?
Upload music from local & remote to Google Play Music

#### How do you think rclone should be changed to solve that?
Add an (at least upload capable) Google Play Music backend

**Comment by buengese** [comment]
As far as I can tell from a quick google search there is no official API for this. There is an unoffical python implementation https://unofficial-google-music-api.readthedocs.io/en/latest/ and while it may be possible to implement this into rclone I would consider this out of scope for rclone.

**Comment by ncw** [comment]
I am reluctant to implement stuff on undocumented APIs.  The mega backend is an object lesson in this - it is full of strange bugs that I can't fix and the only API documentation is a massive C++ program :-(

**Comment by ManuelReschke** [comment]
@ncw  Google closed the Play Music service. You can close this issue now.

**Comment by pataquets** [comment]
You're right @ManuelReschke, thanks for pointing out.
@ncw, closed.
