### ISSUE TITLE
Bucket based remotes: copy should fail when source doesn't exist

### ISSUE THREAD

**Issue by Hermain** [rclone/rclone#3427]
#### What is the problem you are having with rclone?

rclone copy doesn't fail when source doesn't exist in my gstorage bucket.

I have a bucket called redacted which doesn't contain anything. however `rclone -vv copy gcloud:redacted/ICE_CREAM . ` doesn't fail and does nothing instead.

I expect a different return code than 0 and some error message stating that the files does not exist in the bucket.
#### What is your rclone version (output from rclone version)

tested with v1.48.0 and v1.45.0
#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 16.04 64 bit
#### Which cloud storage system are you using? (eg Google Drive)

Gcloud storage
#### The command you were trying to run (eg rclone copy /tmp remote:tmp)

rclone -vv copy gcloud:redacted/ICE_CREAM .
A log from the command with the -vv flag (eg output from rclone -vv copy /tmp remote:tmp)

2019/08/07 10:30:07 DEBUG : rclone: Version "v1.48.0" starting with parameters ["rclone" "-vv" "copy" "gcloud:redacted/ICE_CREAM" "."]
2019/08/07 10:30:07 DEBUG : Using config file from "/home/redacted/.config/rclone/rclone.conf"
2019/08/07 10:30:08 INFO : Local file system at /home/redacted: Waiting for checks to finish
2019/08/07 10:30:08 INFO : Local file system at /home/redacted: Waiting for transfers to finish
2019/08/07 10:30:08 INFO :
Transferred: 0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors: 0
Checks: 0 / 0, -
Transferred: 0 / 0, -
Elapsed time: 100ms

2019/08/07 10:30:08 DEBUG : 7 go routines active
2019/08/07 10:30:08 DEBUG : rclone: Version "v1.48.0" finishing with parameters ["rclone" "-vv" "copy" "gcloud:redacted/ICE_CREAM" "."]

With configuration:
[gcloud]
type = google cloud storage
service_account_file = /home/redacted/.config/rclone/s3_creds
location = eu

**Comment by ncw** [comment]
Bucket based remotes don't really understand the concept of directories as they don't have directories, only files.  So rclone synthesizes directories from the file structure.

So it is impossible to tell an empty directory from a missing directory.

That is why rclone behaves as it does.

If rclone started writing empty files ending in / eg "ICECREAM/" then it could tell, but that is something I've avoided doing as it breaks compatibility with buckets that haven't been set up like that.

**Comment by Hermain** [comment]
As you stated buckets contain only files. If you listed the files in the bucket you'd see there is no file with prefix ICE_CREAM therefore it can't be viewed as a directory. 

I assume a "directory" in a bucket would be multiple files with the same prefix and a /

**Comment by Hermain** [comment]
This is really unexpected behaviour. I'd prefer if empty folders were no supported rather than rclone assuming everything that doesn't exist is an empty dir

**Comment by ncw** [comment]
> This is really unexpected and weird behaviour. I'd prefer if empty folders were no supported rather than rclone assuming everything that doesn't exist is an empty dir

The solution to this is the empty dir markers I alluded to above.

I can't make empty directory return errors though as that will break `rclone mount` for example.  So I'm going to mark this as a Known Issue for the moment.

**Comment by ncw** [comment]
We now have

      --azureblob-directory-markers   Upload an empty object with a trailing slash when a new directory is created
      --gcs-directory-markers         Upload an empty object with a trailing slash when a new directory is created
      --s3-directory-markers          Upload an empty object with a trailing slash when a new directory is created

Which will fix this problem.
