### ISSUE TITLE
Rclone copyto command not working 

### ISSUE THREAD

**Issue by vaccarieli** [rclone/rclone#3431]
Hello, am trying to upload files directly to my google drive folder, this is the link I am using :
https://software-download.microsoft.com/pr/Win10_1903_V1_Spanish_x64.iso?t=e857c484-0a68-4565-b2d9-4285465bbd06&e=1565548002&h=25e977848878a7ef079fa0941129c7c8

My command is:

rclone copyto "https://software-download.microsoft.com/pr/Win10_1903_V1_Spanish_x64.iso?t=e857c484-0a68-4565-b2d9-4285465bbd06&e=1565548002&h=25e977848878a7ef079fa0941129c7c8" "remote:folder" -P.

But it won't work, I don"t know what am doing wrong. 

Log output errors me this:

com/pr/Win10_1903_V1_Spanish_x64.iso?t=e857c484-0a68-4565-b2d9-4285465bbd06
[2]+  Done                    e=1565548002
root@instance:/# rclone copyto "https://software-download.microsoft.com/pr/Win10_1903_V1_Spanish_x64.iso?t=e857c484-0a68-4565-b2d9-4285465bbd06&e=1565548002&h=25e977848878a7ef079fa0941129c7c8" "ElioGDrive:" -P                               2019/08/10 18:45:03 Failed to create file system for "https://software-download.microsoft.com/pr/Win10_1903_V1_Spanish_x64.iso?t=e857c484-0a68-4565-b2d9-4285465bbd06&e=1565548002&h=25e977848878a7ef079fa0941129c7c8": didn't find section in config file

**Comment by animosity22** [comment]
You want to use copyurl.

```
[felix@gemini ~]$ rclone copyurl  "https://software-download.microsoft.com/pr/Win10_1903_V1_Spanish_x64.iso?t=e857c484-0a68-4565-b2d9-4285465bbd06&e=1565548002&h=25e977848878a7ef079fa0941129c7c8" GD:test.iso -vv
2019/08/11 09:18:41 DEBUG : rclone: Version "v1.48.0" starting with parameters ["rclone" "copyurl" "https://software-download.microsoft.com/pr/Win10_1903_V1_Spanish_x64.iso?t=e857c484-0a68-4565-b2d9-4285465bbd06&e=1565548002&h=25e977848878a7ef079fa0941129c7c8" "GD:test.iso" "-vv"]
2019/08/11 09:18:41 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2019/08/11 09:18:42 DEBUG : test.iso: Sending chunk 0 length 8388608
s2019/08/11 09:18:43 DEBUG : test.iso: Sending chunk 8388608 length 8388608
```

**Comment by vaccarieli** [comment]
Thanks that worked now :)
