### ISSUE TITLE
Team drive get ID ?

### ISSUE THREAD

**Issue by IIPoliII** [rclone/rclone#3441]
Hey,

I serached a bit around and i can't find how to easily get the team drive id does anyone have an idea would help me a lot !

**Comment by olaf-b** [comment]
Add "_api/v2.0/oneDrive.drive/" to the root of your team site in a browser to get a JSON-response with the drive-ID you need.  Use this drive-ID when configuring a new OneDrive Business remote.

**Comment by IIPoliII** [comment]
Thanks for the reply i forgot to mention it's gdrive but i founded the rclone software has it in build !
