### ISSUE TITLE
Set maximum bandwidth per file

### ISSUE THREAD

**Issue by Nottt** [rclone/rclone#3444]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.48.0

#### What problem are you are trying to solve?
Enable efficient use of the bandwidth, real time live streaming, see also `https://forum.rclone.org/t/read-files-as-slow-as-possible/11245/3`

#### How do you think rclone should be changed to solve that?

You'll should be able to set a max bandwidth limit per file/read so a single open file can't consume 90% of my bandwidth for no reason.

It could be a flag for rclone mount like `--max-bandwidth-read`.  Thanks <3

**Comment by Nottt** [comment]
So is there a chance of getting this issue fixed ? 

I can propose a $100 bounty because as it is, rclone mount is not usable at all and very wasteful...

I have a server running a rclone mount, in 20 days it downloaded 100 tb of data, but only sent 50% outbound. 

I tried to reduce any kind of buffering or read ahead behavior and it's still the same. It always try to read as much as possible and as fast as possible starving my other system apps for no reason, while a global bandwidth limit would cause issues since I need every open file to be read at least at X speed for my use case ( live streaming )

**Comment by ncw** [comment]
> I tried to reduce any kind of buffering or read ahead behavior and it's still the same.

I would have thought setting `--buffer-size 0` would help as that stops the read-ahead.

Can you post your rclone command line please? And also tell me more about your use case?

**Comment by Nottt** [comment]
I found yet another use case for a bandwidth per file/transfer...

When using rclone serve http, there is no way to limit users to a specific download speed. Say I don't want anyone to download faster than 10 Mbps, there is no way to do that.

An global limit would affect everyone, when usually you just don't want a single people/server to steal all your bandwidth and starve other clients

**Comment by ncw** [comment]
> found yet another use case for a bandwidth per file/transfer...
> 
> When using rclone serve http, there is no way to limit users to a specific download speed. Say I don't want anyone to download faster than 10 Mbps, there is no way to do that.

That is a good use for this, I agree.

I had a go at implementing this. It doesn't work for `serve http` yet but it seems to work for everything else - I'd be interested to see what you think.

https://beta.rclone.org/branch/v1.52.1-105-ga51a793d-fix-3444-bwlimit-file-beta/ (uploaded in 15-30 mins)

I saw your bounty offer above - are you interested in [sponsoring the project](https://rclone.org/donate/)?

**Comment by Nottt** [comment]
How do I use it??

**Comment by ncw** [comment]
@Nott wrote
> How do I use it??

Sorry! Use `--bwlimit-file 1M` to limit the transfer for single files to 1MByte/s

You can combine this with `--bwlimit` to set a max total bandwidth

**Comment by nott** [comment]
@ncw i think you meant @nottt and not me.

**Comment by ncw** [comment]
@Nottt (correct one this time :crossed_fingers: )
 
> > How do I use it??
> 
> Sorry! Use `--bwlimit-file 1M` to limit the transfer for single files to 1MByte/s
> 
> You can combine this with `--bwlimit` to set a max total bandwidth

**Comment by Nottt** [comment]
I didn't see this mention. I was just writing another post about this very issue because it lead to a 24 hours outage for me...

So I'll test the file you uploaded here, but I'll still close this issue and concentrate everything in the new one I was already writing is that okay? 

Thanks @ncw

**Comment by ncw** [comment]
I've merged --bwlimit-file and it will be in v1.53 - happy to discuss further things on the other issue!

**Comment by Nottt** [comment]
@ncw Thanks!! Let me know what you think of the suggestions I made in the other issue. I would like to know if it's possible to implement something similar to ffmpeg -re

**Comment by ncw** [comment]
@Nott I'll reply to the other issue shortly - just trying to get 1.53 out the door at the moment
