### ISSUE TITLE
operations/getlocalurl HTTP Call.

### ISSUE THREAD

**Issue by AndyIbanez** [rclone/rclone#3447]
#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.48.0
- os/arch: darwin/amd64
- go version: go1.12.6
```

#### What problem are you are trying to solve?

I want to write an iOS wrapper around rclone's HTTP interface. I'd like to download files through this interface. Currently you can list files and directories and you can see their paths in the remote, but there's no way to generate a download link when you want to download something (at least, not that I was able to find). There's probably ways to generate the public links to files, but I figure it would be better if rclone could generate a single link to a file with a single format to make them easier to download.

#### How do you think rclone should be changed to solve that?

Rclone's HTTP interface should expose a method called `POST operations/getlocalurl` file (the name is tentative, and it could def work with a different name) (and yes, I know the semantics for GET and POST, but rclone's HTTP interface is POST only). What this method would do is download a file on the server, and then send back a URL to it so it can be downloaded by the client, directly from the server where `rclone rcd` is running.

For example, suppose I have `rclone rcd` running on the address `192.168.2.2:5572`. I do all my calls against this address, such as `https://192.168.2.2:5572/config/listremotes`. I have a remote called `myremote` and I know I have the file `photos/summer/my_image.jpg` in it. Its full rclone path is `myremote:/photos/summer/my_image.jpg`.

I want to download this through the rclone HTTP interface. The call could look like

```
POST https://192.168.2.2:5572/operations/getlocalurl

BODY
fs=myremote
remote=/photos/summer/my_image.jpg
```

rclone could send a JSON back that looks like this:

```
{
    "file_url": "https://192.168.2.2:5572/my_image.jpg"
}
```

This way I don't have to worry about what remotes support public links, and rclone can handle everything for me with the credentials it has in the config file.

**Comment by x0b** [comment]
Are you thinking of something like ```--rc-serve``` ([documentation](https://rclone.org/rc/#rc-serve))?

**Comment by AndyIbanez** [comment]
That's amazing, thanks.
