### ISSUE TITLE
Failed to copy .nomedia

### ISSUE THREAD

**Issue by Dialga** [rclone/rclone#3448]
#### What is the problem you are having with rclone?
"Failed to copy: update getinfo: object not found" for a file named .nomedia despite copying it successfully
Remote is on an microsd card served over ftp, on android.

#### What is your rclone version (output from `rclone version`)
rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.8

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
arch linux/amd64

####  Which cloud storage system are you using? (eg Google Drive)
ftp

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync Music music:/sdcard/Music --exclude '*.{bak}'

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2019/08/17 11:39:13 ERROR : Other/.nomedia: Failed to copy: update getinfo: object not found
2019/08/17 11:39:13 ERROR : ftp://10.0.0.11:8833/sdcard/Music: not deleting files as there were IO errors
2019/08/17 11:39:13 ERROR : ftp://10.0.0.11:8833/sdcard/Music: not deleting directories as there were IO errors
2019/08/17 11:39:13 ERROR : Attempt 1/3 failed with 2 errors and: update getinfo: object not found
2019/08/17 11:39:20 ERROR : Other/.nomedia: Failed to copy: update getinfo: object not found
2019/08/17 11:39:20 ERROR : ftp://10.0.0.11:8833/sdcard/Music: not deleting files as there were IO errors
2019/08/17 11:39:20 ERROR : ftp://10.0.0.11:8833/sdcard/Music: not deleting directories as there were IO errors
2019/08/17 11:39:20 ERROR : Attempt 2/3 failed with 2 errors and: update getinfo: object not found
2019/08/17 11:39:27 ERROR : Other/.nomedia: Failed to copy: update getinfo: object not found
2019/08/17 11:39:27 ERROR : ftp://10.0.0.11:8833/sdcard/Music: not deleting files as there were IO errors
2019/08/17 11:39:27 ERROR : ftp://10.0.0.11:8833/sdcard/Music: not deleting directories as there were IO errors
2019/08/17 11:39:27 ERROR : Attempt 3/3 failed with 2 errors and: update getinfo: object not found
2019/08/17 11:39:27 Failed to sync with 2 errors: last error was: update getinfo: object not found

**Comment by animosity22** [comment]
Can you run the command with -vv as asked for in the template and share the full log?

**Comment by ncw** [comment]
Also which FTP server are you using?

**Comment by Dialga** [comment]
I'm using the ftp server in Cx File Explorer.


<pre>
[acer@acer tmp]$ ll rclonefail/
total 0
drwxr-xr-x  2 acer acer  60 Aug 22 04:02 .
drwxrwxrwt 22 root root 620 Aug 22 04:04 ..
-rw-r--r--  1 acer acer   0 Aug 22 04:02 .nomedia
[acer@acer tmp]$ rclone sync rclonefail rclonefail:/sdcard/temp --exclude '*.{bak}' -vv
2019/08/22 04:06:18 DEBUG : rclone: Version "v1.48.0" starting with parameters ["rclone" "sync" "rclonefail" "rclonefail:/sdcard/temp" "--exclude" "*.{bak}" "-vv"]
2019/08/22 04:06:18 DEBUG : Using config file from "/home/acer/.config/rclone/rclone.conf"
2019/08/22 04:06:18 DEBUG : ftp://10.0.0.11:8833/sdcard/temp: Connecting to FTP server
2019/08/22 04:06:19 INFO  : ftp://10.0.0.11:8833/sdcard/temp: Waiting for checks to finish
2019/08/22 04:06:19 INFO  : ftp://10.0.0.11:8833/sdcard/temp: Waiting for transfers to finish
2019/08/22 04:06:20 ERROR : .nomedia: Failed to copy: update getinfo: object not found
2019/08/22 04:06:20 ERROR : ftp://10.0.0.11:8833/sdcard/temp: not deleting files as there were IO errors
2019/08/22 04:06:20 ERROR : ftp://10.0.0.11:8833/sdcard/temp: not deleting directories as there were IO errors
2019/08/22 04:06:20 ERROR : Attempt 1/3 failed with 2 errors and: update getinfo: object not found
2019/08/22 04:06:21 INFO  : ftp://10.0.0.11:8833/sdcard/temp: Waiting for checks to finish
2019/08/22 04:06:21 INFO  : ftp://10.0.0.11:8833/sdcard/temp: Waiting for transfers to finish
2019/08/22 04:06:22 ERROR : .nomedia: Failed to copy: update getinfo: object not found
2019/08/22 04:06:22 ERROR : ftp://10.0.0.11:8833/sdcard/temp: not deleting files as there were IO errors
2019/08/22 04:06:22 ERROR : ftp://10.0.0.11:8833/sdcard/temp: not deleting directories as there were IO errors
2019/08/22 04:06:22 ERROR : Attempt 2/3 failed with 2 errors and: update getinfo: object not found
2019/08/22 04:06:22 INFO  : ftp://10.0.0.11:8833/sdcard/temp: Waiting for checks to finish
2019/08/22 04:06:22 INFO  : ftp://10.0.0.11:8833/sdcard/temp: Waiting for transfers to finish
2019/08/22 04:06:23 ERROR : .nomedia: Failed to copy: update getinfo: object not found
2019/08/22 04:06:23 ERROR : ftp://10.0.0.11:8833/sdcard/temp: not deleting files as there were IO errors
2019/08/22 04:06:23 ERROR : ftp://10.0.0.11:8833/sdcard/temp: not deleting directories as there were IO errors
2019/08/22 04:06:23 ERROR : Attempt 3/3 failed with 2 errors and: update getinfo: object not found
2019/08/22 04:06:23 Failed to sync with 2 errors: last error was: update getinfo: object not found</pre>

**Comment by ncw** [comment]
It looks like `Cx File Explorer` can't transfer `.` files, or maybe just isn't showing them in the listings.

Can you ask the developers about that?

Can you try with a different FTP client and see if you still get the problem?

When I want to access my files on my phone on my computer I use `Termux` to start `sshd` - then I can use rclone and the `sftp` backend.

**Comment by Dialga** [comment]
Looks like I have to enable hidden files listing in Cx File Explorer.
