### ISSUE TITLE
PR proposal: Add a dockerfile

### ISSUE THREAD

**Issue by pascalandy** [rclone/rclone#3452]
I use rClone in docker for over a year. 
I'll be glad to share the Dockerfile and the docker commands I use.

I just need a maintainer to confirm he/she will have time to review my PR. 

Cheers!

**Comment by pataquets** [comment]
Thanks @pascalandy. A Dockerfile has been merged in #3459.
cc: @ncw

**Comment by ncw** [comment]
@pascalandy I'd love to have your comments on #3460

I'm going to close this now since we have merged a Dockerfile - I suspect there may be further improvements though :-)
