### ISSUE TITLE
Bucket Based Remotes: empty directories

### ISSUE THREAD

**Issue by yparitcher** [rclone/rclone#3453]
#### Progress
1. error on empty directory
- [ ] azureblob
- [ ] b2
- [x] gcs
- [ ] qingstor
- [x] s3
- [ ] swift

#### Current Situation:
Rclone does not officially support empty directories on BBR, however as many parts of the rclone api use file based systems there are many edge cases where rclone acts as if empty directories exist on BBR. 
this causes non existent paths to be validated as rclone cant tell the difference between them and empty directories. this can cause inconsistencies with `mount` etc.
this has been discussed before, see #3427 #3415

#### Proposed solutions:

**1.  enforce non support of empty directories on BBR:**
- make empty directories be an invalid path
- must fix list commands
- this will need work to make consistent with `mount` and similar commands which expect a filesystem (empty directories)

**2. support empty directories on BBR via a hidden empty file:**

- this is already done by some clients on other remotes (B2 web client, some S3 clients)
- need standardization to ensure that rclone uses the same files as others
- require refactoring of many BBR to include this logic
- cause some confusion about these files, but make filesystem commands (`mount`) work better
- requires more api calls - more expensive

**3. 1 & 2 via a flag:**

- this give the most options but will be slightly more confusing to use and require duplicate codepaths

---
if i missed anything please comment and i will add them in.

this will be a significant decision. rclone should have an policy which will help unified implementations for different backends.   

i do not mind helping will this but it will definitely require help from many people.
thanks to all those that have made these remotes work until now
@ncw Please review

**Comment by ncw** [comment]
I think we should probably do 1. first - no flag needed.

As for 2. rclone mostly just contents itself with ignoring the 0 length directory files other programs make.  Making rclone actively put them in would be quite a lot of work so if we want to do it, should probably be in phase 2.  I think it needs a backend flag so you can set it on a per backend basis.

Unifying code between BBR backends will be important!

There are 6 BBR b2, s3, gcs, swift, qingstor, azureblob.  It is possible to get free accounts for all of those except for gcs and azureblob. (you can test s3 against minio or alibabacloud).  gcs has a free tier and azureblob may too.  Signing up for free services will probably mean putting your credit card in though!

I'd love to have your help with this :-)

**Comment by Hermain** [comment]
https://privacy.com/ can be used to generate a prepaid-card for free and just put a minimal amount of money on there. This way you make sure you'll never be overcharged since its a prepaid card...

**Comment by yparitcher** [comment]
`operations.Rmdirs()` has different behavior w & w/o `--fast-list/listR`:
https://github.com/rclone/rclone/blob/693112d57e0aaece5f6ec46100bedb818794dcef/fs/operations/operations.go#L1316-L1324
- **without `listR`** errors in `walk.Walk()` are trapped by the func passed to `Walk()` and are not propagated. (if a wrong directory is listed causing an error the error is printed here and the `Rmdirs` succeeds without error.)
- **with `listR`** errors in `walk.Walk()` are **not** trapped by the func and **are** propagated. (if a wrong directory is listed causing an error `Rmdirs`errors and fails.)

**Comment by ncw** [comment]
> besides for the azureblob, b2, s3, gcs, swift, qingstor that are bucket based `Features().BucketBased`
> 
> googlephotos and hubic do not have the empty directory flag set: `Features().CanHaveEmptyDirectories`
> what is their status regarding this?

hubic is a thin wrapper around swift so that is correct.

I think the google photos is a mistake - you can have empty directories.

**Comment by ncw** [comment]
> Right now on BBR `Mkdir` is a wrapper for `createbucket` and always (if the bucket is valid) returns without error.
> 
> in order to not support empty directories,i would like to make `Mkdir` return an error on BBR when called on a non existent directory. this will require rewriting some tests etc that expect `Mkdir` to always succeed.
> 
> the same goes for `Rmdir`
> 
> does this sound reasonable?

If the directory doesn't exist when we do `rclone mkdir bbr:bucket/dir` that is probably the moment we should be creating the zero length directory marker

I think returning an error will break too much stuff - we want the directory made, we don't want an error returned saying that we can't make the directory.

**Comment by ncw** [comment]
> `operations.Rmdirs()` has different behavior w & w/o `--fast-list/listR`:
> https://github.com/rclone/rclone/blob/693112d57e0aaece5f6ec46100bedb818794dcef/fs/operations/operations.go#L1316-L1324
> 
> * **without `listR`** errors in `walk.Walk()` are trapped by the func passed to `Walk()` and are not propagated. (if a wrong directory is listed causing an error the error is printed here and the `Rmdirs` succeeds without error.)

That is so we do as much as possible and report a failure at the end.

> * **with `listR`** errors in `walk.Walk()` are **not** trapped by the func and **are** propagated. (if a wrong directory is listed causing an error `Rmdirs`errors and fails.)

Hmm, have you got a demo I can try for this?

**Comment by yparitcher** [comment]
> > besides for the azureblob, b2, s3, gcs, swift, qingstor that are bucket based `Features().BucketBased`
> > googlephotos and hubic do not have the empty directory flag set: `Features().CanHaveEmptyDirectories`
> > what is their status regarding this?
> 
> hubic is a thin wrapper around swift so that is correct.
> 
> I think the google photos is a mistake - you can have empty directories.

should hubic get `Features().BucketBased` then?

**Comment by yparitcher** [comment]
> If the directory doesn't exist when we do `rclone mkdir bbr:bucket/dir` that is probably the moment we should be creating the zero length directory marker

exactly.

> I think returning an error will break too much stuff - we want the directory made, we don't want an error returned saying that we can't make the directory.

i agree, just this is limiting `1.` to be just in the `list` command.
 also B2 does not allow objects ending in `/` so the directory marker would have to be a hidden subfile. this would require redoing all that stuff anyway to make it detect the markers properly.

i am not sure which way to go here.

**Comment by yparitcher** [comment]
> Hmm, have you got a demo I can try for this?

try running the S3 integration tests on https://github.com/yparitcher/rclone/tree/BBR-empty-dir
the operations test will succeed without `listR` and fail with `listR`

also BBR give different behavior when run from the root or from a bucket you caught most of them in #3421 however some tests i had to change to work when running from a bucket, as the tests were designed for root

**Comment by shynome** [comment]
I backup my postgres db directory to s3 storage with rclone, today I have verify the backup, it is broken because lose some empty directory like `pg_tblspc`, `pg_replslot`,  I think we should add some warning for someone who sync empty directory to s3 storage, because today we have not implemented this feature

I like support empty directories on BBR via a hidden empty file

<details>
  <summary>the full log</summary>
  
  ```log
  2020-12-20 13:26:14.201 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
  2020-12-20 13:26:14.201 UTC [1] LOG:  listening on IPv6 address "::", port 5432
  2020-12-20 13:26:14.207 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
  2020-12-20 13:26:14.222 UTC [1] LOG:  could not open directory "pg_tblspc": No such file or directory
  2020-12-20 13:26:14.226 UTC [19] LOG:  database system was interrupted; last known up at 2020-12-20 13:09:08 UTC
  2020-12-20 13:26:14.226 UTC [19] LOG:  creating missing WAL directory "pg_wal/archive_status"
  2020-12-20 13:26:14.467 UTC [19] LOG:  could not open directory "pg_tblspc": No such file or directory
  2020-12-20 13:26:14.468 UTC [19] LOG:  could not open directory "pg_tblspc": No such file or directory
  2020-12-20 13:26:14.468 UTC [19] FATAL:  could not open directory "pg_replslot": No such file or directory
  2020-12-20 13:26:14.469 UTC [1] LOG:  startup process (PID 19) exited with exit code 1
  2020-12-20 13:26:14.469 UTC [1] LOG:  aborting startup due to startup process failure
  2020-12-20 13:26:14.472 UTC [1] LOG:  database system is shut down
  ```
</details>

**Comment by Jancis** [comment]
I circled back to idea of creating empty files as directory markers and developed a change for s3 and gcs storage. This seems to work very well so far in my tests. Related issue linked above - https://github.com/rclone/rclone/pull/5323

**Comment by wanderer102** [comment]
Request further S3 empty directory support be worked into future editions of Rclone. Rclone is great software - it makes using S3 storage much more user-friendly and I like both the command line usage for copy and sync and the GUI for working on & viewing files. It is the primary method I use to connect with my S3 storage on my computer.

I noted in https://forum.rclone.org/t/empty-directories-remain/26228 of Rclone's behavior to leave empty directories behind on S3 - the sync, rmdirs, and rmdirs command have no effect on getting rid of empty directories (or ones that were previously in the source, but no longer for a sync). I have been able to work around the issue with web interface of my S3 or other APIs like Cyberduck to remove empty directories manually. Of course, I'd love rclone to clean up and remove empty directories on S3 or be able to exactly mirror another data set on a sync. But because of its stability and functionality (even more than paid products) rclone is my primary API for S3.

**Comment by ninja-** [comment]
+1

**Comment by barmaglot92** [comment]
hello, rclone v1.60, 
```rclone copy test1 remote:bucket --create-empty-src-dirs```
still not working. There is a plan to support this opportunity in future?

**Comment by barmaglot92** [comment]
rclone ```sync remote:bucket remote:bucket``` does nothing but ```sync remote:bucket/path remote:bucket/path```  works. Is there way to sync all folders automatically so?

**Comment by ncw** [comment]
We now have these to support empty directory markers

      --azureblob-directory-markers   Upload an empty object with a trailing slash when a new directory is created
      --gcs-directory-markers         Upload an empty object with a trailing slash when a new directory is created
      --s3-directory-markers          Upload an empty object with a trailing slash when a new directory is created

This covers the major bucket based backends.

I'm going to close this now. We might do `swift` and `b2` in the future depending on demand.

**Comment by lemeshovich** [comment]
> We now have these to support empty directory markers

please add `--b2-directory-markers` 🙏

**Comment by MichalisDBA** [comment]
Why there is not yet Backblaze B2 directory markers yet? Like `--b2-directory-markers` ?
