### ISSUE TITLE
Improve log output when no files / changes are needed

### ISSUE THREAD

**Issue by robertbaker** [rclone/rclone#3454]
#### What is your current rclone version (output from `rclone version`)?
v1.48

#### What problem are you are trying to solve?

When calling rclone move (or similar commands) and there is nothing for rclone to upload, it prints this log:

```
2019/08/18 06:11:43 INFO  : Starting HTTP transaction limiter: max 10 transactions/s with burst 1
2019/08/18 06:11:43 INFO  : Google drive root '': Waiting for checks to finish
2019/08/18 06:11:43 INFO  : Google drive root '': Waiting for transfers to finish
2019/08/18 06:11:43 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 0, -
Elapsed time:          0s
```

This ends up being super confusing for users, they look at this and think something is wrong, when nothing is wrong. I've so far worked around it by doing a check on the number of files in the upload directory, but it's not ideal.

They find these lines in particular confusing `Google drive root '': Waiting for checks to finish`

#### How do you think rclone should be changed to solve that?
Instead of printing this zeroed out log entry, perhaps just print "No files were found that needed action for this operation" or something along those lines.

**Comment by ncw** [comment]
> They find these lines in particular confusing Google drive root '': Waiting for checks to finish

Those should probably be debugs, I agree.

> Instead of printing this zeroed out log entry, perhaps just print "No files were found that needed action for this operation" or something along those lines.

I'd rather print something as well as that stats block, since it does have some useful info in it like `Elapsed time`. Also I wonder whether people are relying on it for scripting...

What do you think?

**Comment by ncw** [comment]
This would make a good issue for someone new to the project - hunt those Info logs down and change them to Debugs.
