### ISSUE TITLE
`rclone copy` does not respect the 503 SlowDown returned by Digital Ocean Spaces

### ISSUE THREAD

**Issue by ToddG** [rclone/rclone#3456]
#### What is the problem you are having with rclone?

`rclone copy` does not respect the 503 SlowDown returned by Digital Ocean Spaces

#### What is your rclone version (output from `rclone version`)
rclone version
rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.6

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

linux_64

####  Which cloud storage system are you using? (eg Google Drive)

Digital Ocean Spaces

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone copy data eap:/eap/energy-dashboard/data --no-traverse`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
</Error>
2019/08/19 06:42:21 Failed to copy with 25 errors: last error was: s3 upload: 503 Slow Down: <?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>SlowDown</Code>
<Message>Please reduce your request rate.</Message>
<RequestId></RequestId>
</Error>
```

**Comment by ncw** [comment]
Rclone should be using it's pacer to slow down.

Can you show a log with `-vv` please?  You should see retries and delays.

If you want to slow rclone down more than that, then use `--tpslimit` or `--bwlimit`.

**Comment by animosity22** [comment]
This seems to be stale. If this is still an item, please ask on the forums and we can help out.

**Comment by 501works** [comment]
Here is a log file from my  experience today:
2020/01/15 18:32:29 ERROR : wp-content/uploads/2019/03/noimage_thumb-6144-150x150.png: Failed to copy: s3 upload: 503 Slow Down: <?xml version="1.0" encoding="UTF-8"?>
2020/01/15 18:32:31 ERROR : wp-content/uploads/2019/03/noimage_thumb-6156-150x150.png: Failed to copy: s3 upload: 503 Slow Down: <?xml version="1.0" encoding="UTF-8"?>
2020/01/15 18:32:31 ERROR : wp-content/uploads/2019/03/noimage_thumb-6157-150x150.png: Failed to copy: s3 upload: 503 Slow Down: <?xml version="1.0" encoding="UTF-8"?>
2020/01/15 18:32:33 ERROR : wp-content/uploads/2019/03/noimage_thumb-6175.png: Failed to copy: Put https://nyc3.digitaloceanspaces.com/501works-ts-space/dev/wp-content/uploads/2019/03/noimage_thumb-6175.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F7ANKTOOJAZWFCC2AK2U%2F20200115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200115T183233Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=f1f4fc63151ed4b3ae187f96750eb5428c7c4868b9b0a93bf472607e14ef842a: file already closed
2020/01/15 18:32:40 ERROR : wp-content/uploads/2019/03/noimage_thumb-6222.png: Failed to copy: s3 upload: 503 Slow Down: <?xml version="1.0" encoding="UTF-8"?>
2020/01/15 18:32:41 ERROR : wp-content/uploads/2019/03/noimage_thumb-6230-150x150.png: Failed to copy: s3 upload: 503 Slow Down: <?xml version="1.0" encoding="UTF-8"?>
2020/01/15 18:32:41 ERROR : wp-content/uploads/2019/03/noimage_thumb-6232-150x150.png: Failed to copy: Put https://nyc3.digitaloceanspaces.com/501works-ts-space/dev/wp-content/uploads/2019/03/noimage_thumb-6232-150x150.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F7ANKTOOJAZWFCC2AK2U%2F20200115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200115T183241Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=1a08f48c9a767dbbe88825c799351e4aafa4f47e94fe6ae0c832b5f3e93d779d: file already closed
2020/01/15 18:32:41 ERROR : wp-content/uploads/2019/03/noimage_thumb-6234-150x150.png: Failed to copy: s3 upload: 503 Slow Down: <?xml version="1.0" encoding="UTF-8"?>
2020/01/15 18:32:43 ERROR : wp-content/uploads/2019/03/noimage_thumb-6245.png: Failed to copy: Put https://nyc3.digitaloceanspaces.com/501works-ts-space/dev/wp-content/uploads/2019/03/noimage_thumb-6245.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F7ANKTOOJAZWFCC2AK2U%2F20200115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200115T183242Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=4062d44191d85c8cba90efafaa775e0a58a2b0b5cb08de9b4549392fa4879e70: file already closed
2020/01/15 18:32:44 ERROR : wp-content/uploads/2019/03/noimage_thumb-6254-150x150.png: Failed to copy: s3 upload: 503 Slow Down: <?xml version="1.0" encoding="UTF-8"?>
2020/01/15 18:32:47 ERROR : wp-content/uploads/2019/03/noimage_thumb-6278-150x150.png: Failed to copy: Put https://nyc3.digitaloceanspaces.com/501works-ts-space/dev/wp-content/uploads/2019/03/noimage_thumb-6278-150x150.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F7ANKTOOJAZWFCC2AK2U%2F20200115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200115T183247Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=e65556089cfc041fc280825df1aebc1524ad156dcae10a84616dd842958e9663: file already closed
2020/01/15 18:32:48 ERROR : wp-content/uploads/2019/03/noimage_thumb-6286-150x150.png: Failed to copy: Put https://nyc3.digitaloceanspaces.com/501works-ts-space/dev/wp-content/uploads/2019/03/noimage_thumb-6286-150x150.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F7ANKTOOJAZWFCC2AK2U%2F20200115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200115T183248Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=faf079ded614eda7f2aac70bf93bf146bb54aedce4d86f4f25497af84fb0d09c: file already closed
2020/01/15 18:32:50 ERROR : wp-content/uploads/2019/03/noimage_thumb-6297.png: Failed to copy: s3 upload: 503 Slow Down: <?xml version="1.0" encoding="UTF-8"?>
2020/01/15 18:34:00 ERROR : wp-content/uploads/2019/03/noimage_thumb-6909-150x150.png: Failed to copy: Put https://nyc3.digitaloceanspaces.com/501works-ts-space/dev/wp-content/uploads/2019/03/noimage_thumb-6909-150x150.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F7ANKTOOJAZWFCC2AK2U%2F20200115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200115T183400Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=22da2524405e190b637719ba48684492368f32419bf5f7023478f3d20d4fe84f: file already closed
2020/01/15 18:34:02 ERROR : wp-content/uploads/2019/03/noimage_thumb-6923-150x150.png: Failed to copy: s3 upload: 503 Slow Down: <?xml version="1.0" encoding="UTF-8"?>
2020/01/15 18:34:02 ERROR : wp-content/uploads/2019/03/noimage_thumb-6926.png: Failed to copy: s3 upload: 503 Slow Down: <?xml version="1.0" encoding="UTF-8"?>
2020/01/15 18:34:04 ERROR : wp-content/uploads/2019/03/noimage_thumb-70-150x150.png: Failed to copy: Put https://nyc3.digitaloceanspaces.com/501works-ts-space/dev/wp-content/uploads/2019/03/noimage_thumb-70-150x150.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F7ANKTOOJAZWFCC2AK2U%2F20200115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200115T183404Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=343ff123fe5667cb87f9030dbc9ed1317c2859ad589da2dde4f43208e8fc98d3: file already closed
2020/01/15 18:34:08 ERROR : wp-content/uploads/2019/03/noimage_thumb-73.png: Failed to copy: Put https://nyc3.digitaloceanspaces.com/501works-ts-space/dev/wp-content/uploads/2019/03/noimage_thumb-73.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F7ANKTOOJAZWFCC2AK2U%2F20200115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200115T183407Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=cb16488bf44a7b2c508251a9c93754b6e0ca01ee620dc7c8f1f9e83c86c6c8c5: file already closed
2020/01/15 18:34:12 ERROR : wp-content/uploads/2019/03/noimage_thumb-765.png: Failed to copy: s3 upload: 503 Slow Down: <?xml version="1.0" encoding="UTF-8"?>
2020/01/15 18:34:12 ERROR : wp-content/uploads/2019/03/noimage_thumb-767.png: Failed to copy: s3 upload: 503 Slow Down: <?xml version="1.0" encoding="UTF-8"?>
2020/01/15 18:34:13 ERROR : wp-content/uploads/2019/03/noimage_thumb-770-150x150.png: Failed to copy: Put https://nyc3.digitaloceanspaces.com/501works-ts-space/dev/wp-content/uploads/2019/03/noimage_thumb-770-150x150.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F7ANKTOOJAZWFCC2AK2U%2F20200115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200115T183413Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=37e780cc1af3f3edcfcba028796e06949a151943dfaa14c34203cee0aa5ca43d: file already closed
2020/01/15 18:34:17 ERROR : wp-content/uploads/2019/03/noimage_thumb-800-150x150.png: Failed to copy: s3 upload: 503 Slow Down: <?xml version="1.0" encoding="UTF-8"?>
2020/01/15 18:34:18 ERROR : wp-content/uploads/2019/03/noimage_thumb-813-150x150.png: Failed to copy: Put https://nyc3.digitaloceanspaces.com/501works-ts-space/dev/wp-content/uploads/2019/03/noimage_thumb-813-150x150.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F7ANKTOOJAZWFCC2AK2U%2F20200115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200115T183418Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=abe6c376c94a4fdf171b8e59726d8778895f63367b2968221a6bd4183d84a169: file already closed
2020/01/15 18:34:34 ERROR : wp-content/uploads/2019/03/noimage_thumb-945.png: Failed to copy: Put https://nyc3.digitaloceanspaces.com/501works-ts-space/dev/wp-content/uploads/2019/03/noimage_thumb-945.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F7ANKTOOJAZWFCC2AK2U%2F20200115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200115T183434Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=dcbc87097946d9c09f70375a62b1f70a0b102cf052fa3fb210a3e9ac4858dfbe: file already closed
2020/01/15 18:34:35 ERROR : wp-content/uploads/2019/03/noimage_thumb-955-150x150.png: Failed to copy: Put https://nyc3.digitaloceanspaces.com/501works-ts-space/dev/wp-content/uploads/2019/03/noimage_thumb-955-150x150.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F7ANKTOOJAZWFCC2AK2U%2F20200115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200115T183435Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=511050ad3ce8384340e58314a8723d57196f817fb007f28136262cb03ad6c63a: file already closed
2020/01/15 18:34:36 ERROR : wp-content/uploads/2019/03/noimage_thumb-957-150x150.png: Failed to copy: Put https://nyc3.digitaloceanspaces.com/501works-ts-space/dev/wp-content/uploads/2019/03/noimage_thumb-957-150x150.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F7ANKTOOJAZWFCC2AK2U%2F20200115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200115T183436Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=f758d53e6fca17a9ca4101683f0e30c420c0b507655b4afee9a6d50e5d7f2dd7: file already closed
2020/01/15 18:34:36 ERROR : wp-content/uploads/2019/03/noimage_thumb-963-150x150.png: Failed to copy: Put https://nyc3.digitaloceanspaces.com/501works-ts-space/dev/wp-content/uploads/2019/03/noimage_thumb-963-150x150.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F7ANKTOOJAZWFCC2AK2U%2F20200115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200115T183436Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=042e05cb37bb77c07559cc733da7dcea1088351a01fa339c364bffebf16a8c17: file already closed
2020/01/15 18:34:38 ERROR : wp-content/uploads/2019/03/noimage_thumb-976.png: Failed to copy: Put https://nyc3.digitaloceanspaces.com/501works-ts-space/dev/wp-content/uploads/2019/03/noimage_thumb-976.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=F7ANKTOOJAZWFCC2AK2U%2F20200115%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200115T183438Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=fa4eee5239f53473cc3e3027a9dbe68fa73c21e4f8ec36edb4f7477b6dee4fbc: file already closed
2
