### ISSUE TITLE
[Suggestion] When configuring a Google Drive remote, hide more settings inside advanced settings.

### ISSUE THREAD

**Issue by AndyIbanez** [rclone/rclone#3463]
#### What is your current rclone version (output from `rclone version`)?

```
Andys-iMac-2:andyibanez andyibanez$ rclone version
rclone v1.48.0
- os/arch: darwin/amd64
- go version: go1.12.6
```

#### What problem are you are trying to solve?

Not a problem specific to me, but I feel some remotes should be easier to configure for first time users. In particular, a popular remote (Google Drive) has become much more difficult to configure over the past few releases. I was working on updating [my rclone guide](https://www.andyibanez.com/rclone-encryption-tutorial/) and I noticed that Google Drive now asks for many things that are going to be left blank most of the time.

#### How do you think rclone should be changed to solve that?

Some configuration options should be hidden under advanced configuration (when rclone asks you if you want to use advanced config).

The `scope` should be hidden in advanced settings.

```
Scope that rclone should use when requesting access from drive.
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
 1 / Full access all files, excluding Application Data Folder.
   \ "drive"
 2 / Read-only access to file metadata and file contents.
   \ "drive.readonly"
   / Access to files created by rclone only.
 3 | These are visible in the drive website.
   | File authorization is revoked when the user deauthorizes the app.
   \ "drive.file"
   / Allows read and write access to the Application Data folder.
 4 | This is not visible in the drive website.
   \ "drive.appfolder"
   / Allows read-only access to file metadata but
 5 | does not allow any access to read or download file content.
   \ "drive.metadata.readonly"
```

Same with `root_folder_ID`.

```
ID of the root folder
Leave blank normally.
Fill in to access "Computers" folders. (see docs).
Enter a string value. Press Enter for the default ("").
root_folder_id> 
```

`service_account_file` should definitely be an advanced setting. I don't imagine most people using rclone with Drive are using this specific setting.

```
Service Account Credentials JSON file path 
Leave blank normally.
Needed only if you want use SA instead of interactive login.
Enter a string value. Press Enter for the default ("").
service_account_file> 
```

I'm also debating whether `client_id` and `client_secret` should also be an advanced setting. On one hand I think they should be. On the other hand I think it's important people change this setting for this specific remote.

**Comment by ncw** [comment]
> Some configuration options should be hidden under advanced configuration (when rclone asks you if you want to use advanced config).

Thanks for taking a look at this :-)

> 
> The `scope` should be hidden in advanced settings.
> 
> ```
> Scope that rclone should use when requesting access from drive.
> Enter a string value. Press Enter for the default ("").
> Choose a number from below, or type in your own value
>  1 / Full access all files, excluding Application Data Folder.
>    \ "drive"
>  2 / Read-only access to file metadata and file contents.
>    \ "drive.readonly"
>    / Access to files created by rclone only.
>  3 | These are visible in the drive website.
>    | File authorization is revoked when the user deauthorizes the app.
>    \ "drive.file"
>    / Allows read and write access to the Application Data folder.
>  4 | This is not visible in the drive website.
>    \ "drive.appfolder"
>    / Allows read-only access to file metadata but
>  5 | does not allow any access to read or download file content.
>    \ "drive.metadata.readonly"
> ```

I recently got rclone approved by Google, and the scope setting is one of the really important ones in the review process, so I think we have to leave that one.

> 
> Same with `root_folder_ID`.
> 
> ```
> ID of the root folder
> Leave blank normally.
> Fill in to access "Computers" folders. (see docs).
> Enter a string value. Press Enter for the default ("").
> root_folder_id> 
> ```

Agree.  That is a niche use.

> 
> `service_account_file` should definitely be an advanced setting. I don't imagine most people using rclone with Drive are using this specific setting.
> 
> ```
> Service Account Credentials JSON file path 
> Leave blank normally.
> Needed only if you want use SA instead of interactive login.
> Enter a string value. Press Enter for the default ("").
> service_account_file> 
> ```

From what I see on the forum, lots of people use service accounts there to automate uploads.

> 
> I'm also debating whether `client_id` and `client_secret` should also be an advanced setting. On one hand I think they should be. On the other hand I think it's important people change this setting for this specific remote.

Yes they are mostly useless, but for Drive, we do recommend setting them.

**Comment by animosity22** [comment]
Is there anything left to do for this item?

**Comment by ivandeex** [comment]
@ncw
AFAICS now only `root_folder_ID` is left to be made advanced.
Please confirm.
