### ISSUE TITLE
Newbie having issues

### ISSUE THREAD

**Issue by jonnwhite1** [rclone/rclone#3464]
#### Output of `rclone version`
Latest

#### Describe the issue
Pausing issues when copying to rclone folder on windows. 
Rclone is mounted on Linux with a samba share to windows for Plex server. 
Using plex drive for plex libs

I'm still learning rclone however i'm not sure what im doing wrong. 
Attached is a photo of rclone output and what windows is doing. 

I'm mounting rclone with the attached
rclone --vfs-cache-mode writes mount --cache-chunk-size 10M --buffer-size 0M --cache-chunk-clean-interval 15m --allow-non-empty --allow-other --umask=0 GDrive: ~/mnt/GDrive -v

Using GSuite
Setup is 
Plex server - Ubuntu VM for rclone and plex drive
Google drive shared to windows with samba share so i can easily upload all content stored on local disks. 
Plex drive mounted to plex PC for plex to search libs
Sonarr and Radarr used for downloading (This issue seems to happen when it auto copies files also as it's freezes/get's stuck)
 
I think it makes sense :(

![image](https://user-images.githubusercontent.com/51175698/63378772-dd775800-c38a-11e9-9dfb-7d5f9d8dfe95.png)

**Comment by jonnwhite1** [comment]
I forgot to mention after around 5 minutes it copies some more files and then pauses again.

**Comment by ncw** [comment]
Would you mind posting this on [the rclone forum](https://forum.rclone.org/) please?

Issues are for bug reports, not help requests.

Thank you :-)

**Comment by jonnwhite1** [comment]
Thank you!
