### ISSUE TITLE
`Dedupe` could continue on errors like `insufficientFilePermisson`

### ISSUE THREAD

**Issue by nishkalprakash** [rclone/rclone#3470]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.48.0-211-g82c6c77e-beta
- os/arch: linux/amd64
- go version: go1.12.9

#### What problem are you are trying to solve?
Rclone dedupe termintates completely if it encounters an insufficientFilePermisson error,
shouldn't it just skip the files it cannot edit/delete and continue operation on the rest of the files?

#### How do you think rclone should be changed to solve that?
"rclone dedupe will terminate if any of the commands it does fail... This isn't ideal!
It could be made to continue some of the errors quite easily I think."

See: https://forum.rclone.org/t/dedupe-terminating-on-insufficientfilepermisson-error/11368

**Comment by ncw** [comment]
To do this this bit of code needs to log and count an error (like other bits of code above) rather than returning it.

This should be quite straight forward.  Fancy having a go?

https://github.com/rclone/rclone/blob/5d6593de4ffc1c492372749565c63209963e1619/fs/operations/dedupe.go#L227-L230

**Comment by nishkalprakash** [comment]
Sure,
how can i get started?

**Comment by ncw** [comment]
First [install rclone from source](https://rclone.org/install/#install-from-source).

Once you've got it building, have a go at the change I indicated above.

When you've got it working send a pull request!

Let me know if you get stuck on any of those steps and I'll try to help.

**Comment by SezalAgrawal** [comment]
Can I pick up this issue?

**Comment by nishkalprakash** [comment]
Sure go ahead,
I'll try with some other issue.

**Comment by SezalAgrawal** [comment]
@ncw,
I setup the project and connected with my google drive, initially with:
1 / Full access all files, excluding Application Data Folder.
I ran rclone dedupe, and it ran successfully.

Now, I created another connection with:
2 / Read-only access to file metadata and file contents.
But, as there are no files to dedupe, it does not throw any permission error. How can I create duplicate files to test with?

**Comment by SezalAgrawal** [comment]
@ncw, I think the issue is already fixed due to error.Wrap().
In my case, even if there is an insufficientFilePermisson error, it continues with other files and does not terminate.

**Comment by ncw** [comment]
> But, as there are no files to dedupe, it does not throw any permission error. How can I create duplicate files to test with?

I usually do this in the drive website.



> I think the issue is already fixed due to error.Wrap().
> In my case, even if there is an insufficientFilePermisson error, it continues with other files and does not terminate.

I'm not sure what you mean?  Can you point to some code?

**Comment by SezalAgrawal** [comment]
@ncw,
Following is the log. Even if there is no permission, it skips those files, and move to other files. The program is not terminated there.
Log:
>>Sezals-MacBook-Pro:rclone sezalagrawal$ **rclone dedupe first remote2: -vv**
2019/09/06 18:00:43 NOTICE: first.csv: Found 2 duplicates - deleting identical copies
2019/09/06 18:00:43 ERROR : first.csv: **_Couldn't delete: googleapi: Error 403: Insufficient Permission: Request had insufficient authentication scopes., insufficientPermissions_**
2019/09/06 18:00:43 NOTICE: first.csv: Deleted 1 extra copies
2019/09/06 18:00:43 NOTICE: 161.docx: Found 2 duplicates - deleting identical copies
2019/09/06 18:00:43 NOTICE: 161.docx: Deleting 1/2 identical duplicates (MD5 "4781d20aae0496f2d1bb102f31697e58")
2019/09/06 18:00:43 ERROR : _**161.docx: Couldn't delete: googleapi: Error 403: Insufficient Permission: Request had insufficient authentication scopes., insufficientPermissions**_
2019/09/06 18:00:43 NOTICE: 161.docx: All duplicates removed
_.....More files...._
2019/09/06 18:00:44 _**Failed to dedupe with 22 errors: last error was: googleapi: Error 403: Insufficient Permission: Request had insufficient authentication scopes., insufficientPermissions**_
>>

The issue I see, is that even if the permission is not there and file is not deleted, it shows logs like Deleted 1 extra copies, All duplicates removed.

**Comment by ncw** [comment]
I think the problem is in the merge directories phase rather than the delete duplicate files phase.

So if you create two identically named directories, one without enough permissions for rclone to delete it, then I think you'll see dedupe crash out.


> The issue I see, is that even if the permission is not there and file is not deleted, it shows logs like Deleted 1 extra copies, All duplicates removed.

That isn't ideal, certainly!

**Comment by SezalAgrawal** [comment]
@ncw, I have raised a [PR](https://github.com/rclone/rclone/pull/3527) for this.
I have also solved bug for messages like Deleted 1 extra copies, All duplicates removed as mentioned above. Should I raise an issue for this and mark it as bug? I can pick it up then.
