### ISSUE TITLE
rclone.org is down?

### ISSUE THREAD

**Issue by sstratoti** [rclone/rclone#3471]
https://downforeveryoneorjustme.com/rclone.org

**Comment by opsoyo** [comment]
I didn't see your post before making mine. Oops. Can confirm from my connections on the PNW. And a few other services like yours in my post #3473

**Comment by ncw** [comment]
Apologies for the outage! The server got rebooted and caddy didn't restart because one of the domains in the config didn't resolve. This was a mistake by me (I forgot to change the nameservers of the domain when I got it). Down for 8hrs exactly while I was asleep :-(

All working now :-)

**Comment by nguaman** [comment]
Is down again.
