### ISSUE TITLE
Can't connect to onedrive

### ISSUE THREAD

**Issue by AndrewMoscoe** [rclone/rclone#3472]
I'm trying to get rclone to connect to onedrive on a headless machine. I get the following error after I paste the auth token (I removed the request-id string from this post). It's a onedrive personal account.

` Failed to query available drives: HTTP error 401 (401 Unauthorized) returned body: "{\r\n  \"error\": {\r\n    \"code\": \"InvalidAuthenticationToken\",\r\n    \"message\": \"CompactToken parsing failed with error code: 8004920A\",\r\n    \"innerError\": {\r\n      \"request-id\": \"<long number string that I removed>\",\r\n      \"date\": \"2019-08-22T03:22:49\"\r\n    }\r\n  }\r\n}"`

I know this is an issue I've seen in the rclone issues list before. To add to this, I have rclone on this machine already configured and working fine with two other OneDrive Personal accounts (family plan).

I'm using rclone 1.45 on Debian 10.

Any ideas on how I should approach this?

**Comment by ncw** [comment]
Where I've seen this go wrong before is on macOS which has a limited cut/paste buffer size.

I suggest you try the [copying the config file ](https://rclone.org/remote_setup/#configuring-by-copying-the-config-file)method instead.

**Comment by AndrewMoscoe** [comment]
So, I had this problem when on a Win10 machine, trying to set up rclone on a remote Debian10.

I tried to do the setup earlier today using a mac to the same Debian remote, and it worked.

I have no idea what went different.

**Comment by ncw** [comment]
No me neither!  Hopefully just finger trouble.

I'll close this since you got it working :-)
