### ISSUE TITLE
rclone.org is down

### ISSUE THREAD

**Issue by opsoyo** [rclone/rclone#3473]
Haven't seen any reports about it. 

Hailing from the PNW, US.

DNS resolution works fine locally and remotely.
https://dnschecker.org/#A/rclone.org

Verified through:
https://tools.pingdom.com/#5b2ddd764e800000
http://currentlydown.com/rclone.org
https://downforeveryoneorjustme.com/rclone.org

**Comment by ncw** [comment]
Apologies for the outage! The server got rebooted and  caddy didn't restart because one of the domains in the config didn't resolve. This was a mistake by me (I forgot to change the nameservers of the domain when I got it). Down for 8hrs exactly while I was asleep :-(

All working now :-)
