### ISSUE TITLE
Add more fields to json log format

### ISSUE THREAD

**Issue by wanderleihuttel** [rclone/rclone#3474]
I guess would be interesting include some fields from summary.
````
Transferred:        7.949M / 7.949 MBytes, 100%, 1.163 MBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            2 / 2, 100%
Elapsed time:        6.8s

{
  "level": "info",
  "object": "README.md",
  "objectType": "*drive.Object",
  "msg": "Copied (new)",
  "source": "operations/operations.go:401",
  "time": "2019-07-28T12:19:09.52171+01:00"
  "fileSize": "8335608",
  "bytesPerSecond": "1221234",
  "elapsedTime" : "6800ms"
}
````
As @ncw suggested!
> I think what should be happening is that the stats logs which are written periodically should be broken out in the log as per core/stats, probably under another top level field like stats.
> 
> @wanderleihuttel - can you make a new issue about this so we can discuss further?

**Comment by ncw** [comment]
@justinalin what do you think - do you fancy working on this?

So if `--use-json-log` is in effect, make the stats log include all the info as a JSON object.

**Comment by ncw** [comment]
This has been done - the core stats are added to the JSON logs now.

```
{
  "level": "info",
  "msg": "\nTransferred:   \t    8.171k / 8.171 kBytes, 100%, 825.616 kBytes/s, ETA 0s\nTransferred:            1 / 1, 100%\nElapsed time:         0.0s\n\n",
  "source": "accounting/stats.go:355",
  "stats": {
    "bytes": 8367,
    "checks": 0,
    "deletes": 0,
    "elapsedTime": 0.02773152,
    "errors": 0,
    "fatalError": false,
    "renames": 0,
    "retryError": false,
    "speed": 845431.1051957991,
    "transferTime": 0.009896726,
    "transfers": 1
  },
  "time": "2020-09-23T17:26:23.927243+01:00"
}
```

**Comment by episquare** [comment]
Hello, if you don't mind kindly share how do you parse json string into json object like that? I always fail when parsing from json string from the log file into json object, it's always say json string is not im valid format.

This is the command that i use
Rclone copy --use-json-log /path/source dest:path/destination.

Thank you

**Comment by ncw** [comment]
@episquare can you [post on the rclone forum](https://forum.rclone.org/) about this with the example code you are using and we'll help you there.

**Comment by episquare** [comment]
> @episquare can you [post on the rclone forum](https://forum.rclone.org/) about this with the example code you are using and we'll help you there.

Hello, thanks @ncw after i dig depper looks like i know the issue, yes the issue is because rclone produce 2 line of json string even for copy operation, that's why i always fail to convert this json string, well for now i retreat from the rclone and back to manual post request to my cloud provider to send the data.
I do really hope that in the future rclone could produce or have an option to make log more simple, example just 1 line log aka message success or failed, so it's will be easy to process the log after that.
By the way, thank you for your response. 🍻
