### ISSUE TITLE
Make rclone mount follow symlinks

### ISSUE THREAD

**Issue by felisucoibi** [rclone/rclone#3476]
#### What is your current rclone version (output from `rclone version`)?

1.48

#### What problem are you are trying to solve?

Symlinks when rclone mount to work

#### How do you think rclone should be changed to solve that?

Rclone now can make .rclonelinks files in the cloud, make rclone mount to detect them and show real symlinks in mounted drives.

**Comment by ncw** [comment]
I think this is a duplicate of: https://github.com/rclone/rclone/issues/2975 ?

**Comment by felisucoibi** [comment]
It is i close it, thnx
