### ISSUE TITLE
GDrive Ban again (googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded)

### ISSUE THREAD

**Issue by snickers2k** [rclone/rclone#3477]
#### What is your rclone version (output from `rclone version`)
rclone v1.48.0
- os/arch: linux/amd64 (Ubuntu 18 LTS)
- go version: go1.12.6

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
/usr/bin/rclone mount SecretDrive: /mnt/media \
  --config /home/snikay/.config/rclone/rclone.conf \
  --log-file=/home/snikay/logs/rclone-mount.log \
  --log-level INFO \
  --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36" \
  --allow-other \
  --allow-non-empty \
  --log-level INFO \
  --uid 1000 \
  --gid 1000 \
  --umask 002 \
  --file-perms 0777 \
  --vfs-cache-mode writes \
  --vfs-cache-max-size 40G \
  --buffer-size 1G \
  --dir-cache-time 20h \
  --timeout 2h \
  --rc \
  --cache-dir /dev/shm/
```

Log

[rclone-mount.log](https://github.com/rclone/rclone/files/3535095/rclone-mount.log)

**Comment by ncw** [comment]
I'm not sure I can help with this - google ban things alas.

Did you [make your own client_id](https://rclone.org/drive/#making-your-own-client-id)?

BTW you need to fix this otherwise the token will expire.

    ERROR : Failed to save new token in config file: open /home/snikay/.config/rclone/rclone.conf: permission denied

**Comment by snickers2k** [comment]
Thank you
Okay, i'll adjust Plex further. wasn't sure.

Yes, i know that config permission problem. i don't know why this happens. i run a daily cronjob with "curl https://rclone.org/install.sh | sudo bash" to get the newest Version of your super awesome tool immediately ;) to fix this, i even have a "; chmod 775" in that cronjob.
Maybe thats the actual topic? :D

**Comment by animosity22** [comment]
What's the size of your GD?
Did the download quota just start popping up?
Are you using analyze in Sonarr/Radarr?
Do you have any deep analysis on in Plex?

**Comment by snickers2k** [comment]
thank you for helping, all good now. don't know what happened that day.
forgot to close.
