### ISSUE TITLE
Rclone installation failed

### ISSUE THREAD

**Issue by 5536086** [rclone/rclone#3479]
Rclone installation failed
Operating system: centos7_x64
Error message:
[root@avs-mv ~]# curl https://rclone.org/install.sh | sudo bash
   % Total % Received % Xferd Average Speed Time Time Time Current
                                  Dload Upload Total Spent Left Speed
100 4426 100 4426 0 0 10600 0 --:--:-- --:--:-- --:--:-- 10588
Mktemp: too few X's in template ‘rclone-install’

**Comment by ncw** [comment]
This works for me on ubuntu... Fancy debugging a bit?

**Comment by Cnly** [comment]
Did a quick test on Debian and it's the "fallback" part of this line that isn't working:

https://github.com/rclone/rclone/blob/a6387e1f81a2da09262a9b26b838554e971b2b00/docs/content/install.sh#L27-L28

This should be easy to fix. From `man mktemp`:

```
TEMPLATE must contain at least 3 consecutive 'X's in last component.
```

**Comment by ncw** [comment]
@Cnly - nice one... Fancy sending a PR?

**Comment by Cnly** [comment]
@ncw Sure. Have been lurking for a long time!

**Comment by ncw** [comment]
I updated the live install.sh on rclone.org - thanks @Cnly
