### ISSUE TITLE
Give a warning about the destination folder with sync comment

### ISSUE THREAD

**Issue by aladine** [rclone/rclone#3485]
#### What is your current rclone version (output from `rclone version`)?
v1.48.0

#### What problem are you are trying to solve?
When I run **rclone sync [source] [destination]**, my destination folder is not empty. By right, it should check if the folder is empty and show an warning for me. As the result, I accidentally delete my old data in destination.

#### How do you think rclone should be changed to solve that?
It should give a warning if the destination folder is not empty. If user gives answer Y, then the *sync* command can proceed.

**Comment by ncw** [comment]
Often syncs are run to update a folder so I don't think this ideas is practical.

I recommend using `copy` first then `sync --dry-run` before running `sync` for real.

**Comment by animosity22** [comment]
Question looks to be answered. If you have a new one, please use the forums. Thanks!
