### ISSUE TITLE
Support limited time/uploads hostings without signup,

### ISSUE THREAD

**Issue by KOLANICH** [rclone/rclone#3486]
There are some file hostings like https://uploadfiles.io/ , https://uguu.se/ and https://file.io that are without signup and store files for limited time and/or downloads. Since they allow only single files and probably their business model may involve analysis of uploaded data the obvious solution is to upload encrypted archives.

**Comment by ncw** [comment]
Do these have APIs?

One service which does have an API is [firefox send](https://send.firefox.com/)

**Comment by KOLANICH** [comment]
Not all of them. For file.io the official API is uploading with cURL.

**Comment by animosity22** [comment]
If you have a specific feature to ask for, can you open up a new issue and list out the API link and we can add that as an enhancement request. Thanks!
