### ISSUE TITLE
RAID 1/mirroring like remote

### ISSUE THREAD

**Issue by J0s3f** [rclone/rclone#3487]
It would be a great addition to have a remote that automatically mirrors all data to two (or more) other remotes. E.g. for backup of important files one could configure this to store everything on Google Drive and OneDrive, so if one of the providers loses data it is still available at the other one.
This could even be combined with the crypt remote to store encrypted backups at two locations.

                                                                                +-----------------+
                                                                                |                 |
                                                                            +--->                 |
            +----------------------+             +-----------------------+  |   |   Provider 1    |
            |                      |             |                       |  |   |                 |
    +-------->     Encrypt          +------------->   Mirror              +--+   +-----------------+
            |                      |             |                       |  |
            +----------------------+             +-----------------------+  |
                                                                            |   +-----------------+
                                                                            |   |                 |
                                                                            +--->                 |
                                                                                |   Provider 2    |
                                                                                |                 |
                                                                                +-----------------+

**Comment by x0b** [comment]
Your idea looks pretty similar to https://github.com/rclone/rclone/issues/3308

**Comment by J0s3f** [comment]
Yes, seems to be the same. I tried to search for it but only searched for raid and not mirror.
I close this issue.

**Comment by marek22k** [comment]
What is the current status?
