### ISSUE TITLE
delta synchronization like in rsync

### ISSUE THREAD

**Issue by HynekPetrak** [rclone/rclone#3488]
#### What is your current rclone version (output from `rclone version`)?
latest

#### What problem are you are trying to solve?
Synchronize large amount of big files, that change just by a few bytes.

#### How do you think rclone should be changed to solve that?
Is rclone able to sychronize just the changed portion of a file, like rsync does (using the rolling hash and block checksums)?

I.e. If I have 10 GB file and change just 10 bytes of it, then rsync will move just the small block, that includes the changed 10 bytes.

**Comment by ncw** [comment]
> Is rclone able to sychronize just the changed portion of a file, like rsync does (using the rolling hash and block checksums)?

No it can't.  Unfortunately the cloud storage providers don't support that directly.

There are ways around that though..

You could use [restic](https://restic.net/) with an [rclone backend](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#other-services-via-rclone) - this does a similar thing to rsync.  The downside being that your file will be stored in lots of chunks.

You could also use [rdiff](https://linux.die.net/man/1/rdiff) which would allow you to do the binary diff that rsync does manually.

**Comment by OmarJay1** [comment]
I'm curious about this issue.   Gsutil rsync runs a lot faster for me than rclone.  At first I thought it was because gsutil was using delta, but it doesn't.  Apparently standard cloud storage paradigm is file immutability. 

I know this is a bit of a different topic, but I think that one thing that gsutil does better than rclone is the way it creates a file update list before transferring files. 

https://github.com/GoogleCloudPlatform/gsutil/blob/a93d02d37bdfb469dd3e60fe7cc70ce2f6d52bd8/gslib/commands/rsync.py

> The gsutil rsync command copies changed files in their entirety and does
>      not employ the
>      `rsync delta-transfer algorithm <https://rsync.samba.org/tech_report/>`_
>      to transfer portions of a changed file. This is because cloud objects are
>      immutable and no facility exists to read partial cloud object checksums or
>      perform partial overwrites.

**Comment by ncw** [comment]
> I know this is a bit of a different topic, but I think that one thing that gsutil does better than rclone is the way it creates a file update list before transferring files.

This is an interesting topic but probably more one for [the rclone forum](https://forum.rclone.org/) - fancy moving it there?
