### ISSUE TITLE
Progress displays leave trailing characters from previous refreshes

### ISSUE THREAD

**Issue by BobVul** [rclone/rclone#3500]
#### What is the problem you are having with rclone?
When using the `-P` option in Windows, as the progress line shrinks (e.g. ETA is going down) the previous trailing characters are still displayed, e.g.:

```
Transferred:      713.237M / 9.181 GBytes, 8%, 1.211 MBytes/s, ETA 1h59m37s55s3ss
 *                    MyBackup_full_b1_s1_v3.tib: 12% /1.181G, 539.765k/s, 33m29sss
```

It looks like the line is not being cleared, merely overwritten with new information. I think either the line should be cleared first, or, if that is difficult, the new line should be right-padded with spaces to clear previous characters. To avoid overflow, if the line is padded then the pad length should be equal to the length of the previously displayed line.

#### What is your rclone version (output from `rclone version`)
1.49.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 64-bit

####  Which cloud storage system are you using? (eg Google Drive)
SFTP (C14) via Crypt

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
rclone copy ./ c14-enc: -P --bwlimit 3M
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Not much point in a log since the issue is with the progress display, and adding verbose logging info just makes it messier. I can still provide one if required.

**Comment by ncw** [comment]
I think we had an issue about this before but I can't find it now!

From what I remember it turned out to be a bug in Windows which was resolved by an update.

Where are you running rclone?  A cmd windows?  Or a powershell window?  Or somewhere else?

Can you try the other type of window?

**Comment by BobVul** [comment]
Hm, I forgot to mention I'm on Windows 10 v1809, latest-1, latest being v1903 (not yet available for my device due to driver issues; I can test it in a VM later).

I was running it in cmd. The exact same thing happens in powershell. I don't think it really matters because both go through conhost anyway, so the rendering should be the same. Same issue occurs via cmd via MobaXterm, though I'm not sure that doesn't just use conhost in the background.

I don't think it's worth trying WSL, because at that point I'd have to use the Linux build, defeating the purpose of having a Windows build...

**Comment by ncw** [comment]
This was working in previous versions of Windows...

I found the issue (finally!): https://github.com/rclone/rclone/issues/2623

Which indicates this is fixed in v1903

**Comment by BobVul** [comment]
Ah, I didn't find that one while searching. Suppose I'll just wait til that update comes down; this is far from critical. 

Thanks for the quick response!
