### ISSUE TITLE
Add support for Wasabi's custom MOVE API

### ISSUE THREAD

**Issue by leerspace** [rclone/rclone#3510]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.6

#### What problem are you are trying to solve?
Renames/moves made with vanilla S3 clients on Wasabi are more expensive due to Wasabi's 90 day minimum object storage charge and the S3 API's lack of a standard rename/move endpoint. This can result in temporary double-charging of objects when using the standard S3-style copy-and-delete method of moving/renaming objects that haven't yet been stored for at least 90 days.

#### How do you think rclone should be changed to solve that?
If storage type = s3 and provider = Wasabi, renames/moves for that storage should instead use Wasabi's custom MOVE endpoint instead of a copy followed by a delete.

Here's a link to Wasabi's documentation:
https://wasabi.com/wp-content/themes/wasabi/docs/API_Guide/topics/Renaming_Objects.htm

**Comment by ncw** [comment]
The first challenge with this will be working out how to call the API using the S3 golang API.

I think it is possible though.

@leerspace do you want to have a go at this?

**Comment by leerspace** [comment]
> I think it is possible though.
> 
> @leerspace do you want to have a go at this?

@ncw sure, I've started looking into how this might be possible with the S3 golang API.

**Comment by asdffdsa6131** [comment]
if you need a beta tester, please let me know.

**Comment by leerspace** [comment]
I think I need to take a step back and double check in practice, not just hypothetically, what actually happens as far as Wasabi's billing is concerned when moving objects in Wasabi with rclone. While messing around with `backend/s3/s3.go` and reading some more, I noticed this section in [Wasabi's API documentation](https://wasabi.com/wp-content/themes/wasabi/docs/API_Guide/index.html#t=topics%2FPUT_Object_Copy_Uses_Link.htm) (emphasis mine):

> PUT Object Copy Uses Link
> 
> Normally, to rename objects using AWS S3 protocol, an object is uploaded with one key value. Then, a PUT operation with the new key value copied from the original key value is given, and the object for the original key value is deleted.
> 
> **Wasabi automatically optimizes this sequence by linking the new key value object to the original data from the copy key value. This avoids making another copy of the data, which would result in higher storage charges.** Because Wasabi uses links to the original data, any size object up to the 5 TB limit may be copied and does not require the use of a multi-part upload.

This makes it sound to me like Wasabi is supposed to be handling copy operations in a special way that would avoid most (or all?) of the suspected object storage billing concerns. For all I know it still resets the clock on the new object, but I still need to test.

**Comment by leerspace** [comment]
It took a little while to see the results of my testing since Wasabi's bucket-level billing/utilization data is only calculated every 24 hours.

However, based on my testing in a brand new bucket I'm pretty convinced that moves done using the copy-and-delete method do not incur double charging in Wasabi due to copies in Wasabi not actually creating separate copies of the data on disk.

This was my test case:
```
$ ls testing/
50kb
$ rclone sync testing/ wasabi:bucket-name-here
$ rclone move wasabi:bucket-name-here/50kb wasabi:bucket-name-here/50kb_moved
```
I'm only being charged for 50KB (**not** 100KB) even though I deleted the original copy of the file before 90 days.

Sorry for my misunderstanding! I should have done this test case before creating this issue, rather than speculating based on what Duplicacy did and an incomplete reading of Wasabi's documentation.

**Comment by ncw** [comment]
Thanks for reporting back.  That makes sense since that is the only way to rename stuff with the standard S3 API.

**Comment by asdffdsa6131** [comment]
i have contacted wasabi and i sent to them some links for the forum and the link to this page.
they just replied that they are going to look into it and let me know

**Comment by keitap** [comment]
I reached out to Wasabi support team to confirm their current billing policy for object copies and wanted to share the latest update.

It turns out that copying objects **does** incur additional charges. While @leerspace's findings were correct at the time, Wasabi has since changed its billing policy. They mentioned this change happened about a year ago, though I'm not sure the exact date.

The explanation under the "PUT Object Copy Uses" link at [Wasabi Docs](https://docs.wasabi.com/docs/operations-on-objects#put-object-copy-uses-link) is outdated, and they said it will be revised.

> Normally, to rename objects using AWS S3 protocol, an object is uploaded with one key value. Then, a PUT operation with the new key value copied from the original key value is given, and the object for the original key value is deleted.
>
> Wasabi automatically optimizes this sequence by linking the new key value object to the original data from the copy key value. This avoids making another copy of the data, which would result in higher storage charges. Because Wasabi uses links to the original data, any size object up to the 5 TB limit may be copied and does not require the use of a multi-part upload.

To avoid extra charges when moving objects, you need to use the MOVE API, which is currently not supported by rclone.

Hope this information helps.

**Comment by ncw** [comment]
The new v2 S3 SDK is pretty flexible so we could probably implement the Move command for Wasabi. Let me know if anyone wants to have a go?

**Comment by museghost** [comment]
> The new v2 S3 SDK is pretty flexible so we could probably implement the Move command for Wasabi. Let me know if anyone wants to have a go?

Yes,  here !!
Although It's been a year, could you implement the Wasabi's MOVE API in rclone ?
If possible, could rclone support the MOVE api with `encrypt` as well ?
