### ISSUE TITLE
Failed to create file system: "128M is not a multiple of 320k"

### ISSUE THREAD

**Issue by lamafab** [rclone/rclone#3512]
#### What is the problem you are having with rclone?
This is a small issue: when you set the chunk size to `128M`, mounting the drive will return an error that 128M is not a multiple of 320k. When you specify the chunk size as kilobytes instead of Megabytes it works fine.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.45
- os/arch: linux/amd64
- go version: go1.10.4
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 19.04, 64bit

####  Which cloud storage system are you using? (eg Google Drive)
Microsoft OneDrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone --vfs-cache-mode writes mount onedrive: ~/OneDrive`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
`2019/09/04 22:25:23 Failed to create file system for "onedrive:": onedrive: chunk size: 128M is not a multiple of 320k`

####  => Workaround
Set chunk size to `128000k` instead of `128M`

**Comment by Cnly** [comment]
This behaviour seems expected. From the [docs](https://docs.microsoft.com/en-us/graph/api/driveitem-createuploadsession?view=graph-rest-1.0#upload-bytes-to-the-upload-session):

> the size of each byte range MUST be a multiple of 320 KiB (327,680 bytes)

So 128000k is indeed a multiple of 320k, but 128M (== 128 * 1024k) is not.

**Comment by lamafab** [comment]
> So 128000k is indeed a multiple of 320k, but 128M (== 128 * 1024k) is not.

Well, fair enough. Didn't think about the 10**24**... maybe a hint would be helpful?

I'm fine with closing this issue. It's up to you.
