### ISSUE TITLE
AWS temporary credentials for authorization?

### ISSUE THREAD

**Issue by francisreyes** [rclone/rclone#3517]
I run rclone on guest computers and I'm uncomfortable leaving my IAM access keys on it. Instead I'd like to use temporary session tokens. As of now, rclone does not request or ask for the session token in addition to the access key ID / secret key. 

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html

**Comment by ncw** [comment]
You can find the `session_token` parameter in the advanced settings in `rclone config`.

Does that help?

**Comment by francisreyes** [comment]
Yes, immensely. Apologies for the bother, google-fu didn't pick it up on the docs

**Comment by ncw** [comment]
> Yes, immensely. Apologies for the bother, google-fu didn't pick it up on the docs

No worries!
