### ISSUE TITLE
rclone mount --vfs-cache-mode full tag error 

### ISSUE THREAD

**Issue by vaccarieli** [rclone/rclone#3520]
Hi I mounted my GDrive on my linux machine path "/home/user/gdrive/" with the use of -vfs-cache-mode full tag, Idk if am confused with its use, so what am trying to do is the remux a movie while still on the cloud to avoid downloading the entire movie and then reupload it back again, and as soon as I run the command on the file (movie) using mkvmerge, I get this error 

"Error: Modification of properties in the section 'Track headers' was requested, but no corresponding level 1 element was found in the file. The file has not been modified." 

Why? is like the gdrive cloud itself or rclone is preventing to make modification under the file while still on the cloud, please help.

**Comment by ncw** [comment]
> Hi I mounted my GDrive on my linux machine path "/home/user/gdrive/" with the use of -vfs-cache-mode full tag, Idk if am confused with its use, so what am trying to do is the remux a movie while still on the cloud to avoid downloading the entire movie and then reupload it back again,

`--vfs-cache-mode full` **will** download the entire movie, so I don't think it is working as you want.

You can't work on the movie in the cloud - the cloud storage systems don't let you upload bits of files.

**Comment by animosity22** [comment]
If you have a new question, please feel free to ask on the forums and we'll help out!
