### ISSUE TITLE
Failed to set modification time: InvalidObjectState: Operation is not valid for the source object's storage class

### ISSUE THREAD

**Issue by kaihendry** [rclone/rclone#3522]
Related https://github.com/rclone/rclone/commit/1a2fb522667e2e1a61841fa994cbb3c68a192717
https://twitter.com/njcw/status/1170935966409940994

#### What is the problem you are having with rclone?

Archiving to an S3 bucket using the Glacier Deep Archive Object class.

#### What is your rclone version (output from `rclone version`)

rclone v1.49.2
- os/arch: freebsd/amd64
- go version: go1.12.9

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Freenas nightly with rclone manually updated from https://downloads.rclone.org/v1.49.2/rclone-v1.49.2-freebsd-amd64.zip

####  Which cloud storage system are you using? (eg Google Drive)

AWS S3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

Not 100% sure how to get that out.

* https://s.natalian.org/2019-09-09/1568009105_2560x1440.png
* https://s.natalian.org/2019-09-09/1568009150_2560x1440.png
* https://s.natalian.org/2019-09-09/1568009129_2560x1440.png

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

https://s.natalian.org/2019-09-09/8256.log

```
2019/09/09 10:42:01 ERROR : 2019-06-26/Europe2019.fcpbundle/.lock-info: Failed to set modification time: InvalidObjectState: Operation is not valid for the source object's storage class
```

**Comment by ncw** [comment]
I've had a go at fixing this here - can you have a go?

https://beta.rclone.org/branch/v1.49.0-035-g956055ef-fix-3522-storage-class-beta/ (uploaded in 15-30 mins)

**Comment by kaihendry** [comment]
<img src="https://s.natalian.org/2019-09-10/1568089426_2560x1440.png" alt="SUCCESS">

Success!

**Comment by ncw** [comment]
Excellent! When I get back to my desk I'll merge that.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.50

**Comment by william-gr** [comment]
Is this in 1.49.3? or will only make it for 1.50?

thanks

**Comment by ncw** [comment]
My plan was to leave it to 1.50 as it isn't a trivial fix

**Comment by william-gr** [comment]
Thanks for the update. Is there a planned release date for it? We need to figure out if we would be able to deliver that fix in time for FreeNAS 11.3 release.

**Comment by ncw** [comment]
The planned release date is October 12, 2019 - I don't guarantee it won't slip though!

If that is a problem for you I can put this in a 1.49.4 release easily enough - I have one more patch which would be useful to go in too so I could make one at the weekend.

**Comment by william-gr** [comment]
12 Oct should be good enough time wise. Thanks!

**Comment by ncw** [comment]
@william-gr I ended up putting this into a v1.49.4 which is out now

**Comment by william-gr** [comment]
Thanks! I have pushed it to our tree

https://github.com/freenas/ports/pull/414
