### ISSUE TITLE
Extremly slow http initialization

### ISSUE THREAD

**Issue by antgiant** [rclone/rclone#3523]
I am having trouble with the http backend taking excessively long on startup. It takes roughly a full minute to initialize. However, in a broswer the URL loads nearly instantly.

The behavior is the same in Windows (1.43.1) [windows.log](https://github.com/rclone/rclone/files/3590740/windows.log) and Linux (1.49.2) [rpi.log](https://github.com/rclone/rclone/files/3590761/rpi.log)

I have also confirmed the behavior with mount and lsd. In the case of mount I also experienced the issue when there was a change to the page (roughly every 10 minutes). The change triggered a roughly 1 minute pause before it would show me the files again.

**Comment by ncw** [comment]
If you add -vv -dump bodies to the command you can see what it is doing.

The answer is HEAD requests on all the contents of the directory. This is to discover the date and time of the files.

I think there are a lot of files in that directory hence the delay.

I could put in a --http-no-head flag to stop this. This would mean instant listings but rclone would no longer knows there size of any of the files. That would mean you would have troubles using the files with mount 

I could also parallelize the head requests to speed things up. That might be a better solution.

**Comment by antgiant** [comment]
Thank you. I'm not sure why -vv refuses to show me the HEAD requests. I tried that and --log-level DEBUG on both of my installs and only saw what is in the attached logs.

A few additional thoughts. Most directory lists I've seen show the file size as well. Could that be used as a temp file size and the HEAD request only verifies as needed with a lazy load? I guess even a size of "unknown" with lazy load to find out should work as well. Assuming that is a possibility in the existing code base.

Perhaps more simply, in my particular case I'm happy to use an include or exclude filter to knock down the file count to a very small number of files. Potentially as low as one. However, the HEAD requests happen before the filters kick in so the delay is the same. Can the HEAD requests occur after the filtering? Hmm, looking closer at the filtering docs I see that size is a possible filter. So maybe not. Can this be done if there is not size filter in use? My case doesn't have one.

Otherwise yes parallelization would definitely help.

Thanks again for this amazing program by the way.

**Comment by ncw** [comment]
I've implemented
- parallel HEAD requests (controlled by `--checkers`)
- the `--http-no-head` flag

Can you have a go with those and tell me what you think?

https://beta.rclone.org/branch/v1.49.0-036-g09c9027a-fix-3523-http-beta/ (uploaded in 15-30 mins)



> Perhaps more simply, in my particular case I'm happy to use an include or exclude filter to knock down the file count to a very small number of files. Potentially as low as one. However, the HEAD requests happen before the filters kick in so the delay is the same. Can the HEAD requests occur after the filtering? Hmm, looking closer at the filtering docs I see that size is a possible filter. So maybe not. Can this be done if there is not size filter in use? My case doesn't have one.

At the moment the filtering happens after the directory listings are returned from the backends.

It would be nice if optionally the backends could use the directory filtering to cut down the amount of work they need to do.

This would need a bit of re-organization of the code though...

**Comment by antgiant** [comment]
Wow! That is a crazy fast fix! Thank you! 

The default behavior is now at least twice as fast and the --http-no-head flag is amazing! That provided the instant load I was hoping for. Thank you!

I did try mounting with the --http-no-head flag and as predicted it caused some strange behavior. For instance some programs could load the files and others could not. Not a show stopper for my needs though.

**Comment by ncw** [comment]
Thanks for testing :-)

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.50
