### ISSUE TITLE
Update documentation to add an example docker-compose file

### ISSUE THREAD

**Issue by Poltergeisen** [rclone/rclone#3524]
### What is your current rclone version (output from `rclone version`)?
N/A

#### What problem are you are trying to solve?
Trying to help my friends install rclone using docker-compose

#### How do you think rclone should be changed to solve that?
The documentation should be updated to show both the docker run and docker-compose formats for creating rclone

**Comment by pataquets** [comment]
Hi, @Poltergeisen,
Check out #3521

**Comment by Poltergeisen** [comment]
@pataquets thank you! I'll look at that more in depth tonight but it seems exactly like what I was looking for.

**Comment by Poltergeisen** [comment]
I think the only change that would be better with that PR is to add it to the readme as well @pataquets

**Comment by pataquets** [comment]
I was thinking more in adding a link to this directory to the Docker wiki page, once/if it gets merged.
However, feel free to send your docs proposal PR, if you feel like it.

**Comment by ncw** [comment]
#3521 has been merged now so I'm going to close this now.

@pataquets do add links in [the rclone wiki](https://github.com/ncw/rclone/wiki) as appropriate or send PRs for the docs!

Thanks

**Comment by animosity22** [comment]
Per above, closing.
