### ISSUE TITLE
Preset files and possible daemonization

### ISSUE THREAD

**Issue by therecluse26** [rclone/rclone#3526]
Hi, I've been using RClone for a while and have been thinking about this for a while, it would be really nice to be able to save backup scripts in preset files that can be run continually by a daemon and/or just loaded ad-hoc by RClone (maybe like `rclone --run-preset=presetTitle`)

An example of what a preset file could look like (rough idea):
```json
{
  "title": "Photo-Backup",
  "remoteName": "B2",
  "action": {
    "type": "copy",
    "remotePath": "photos",
    "localPath": "/home/username/Photos",
    "direction": "upload",
    "options": [
    	"-vv"
    ]
  }
}
```

Then you could have some sort of function that enables and disables presets from the command line, similar to how something like Apache works where it just makes a symlink from `available-presets` to `enabled-presets.`

I have a decent amount of Go experience, so I could probably assist in implementing this feature if you agree that it could be useful for others :)

I anticipate that the most difficult part of this (correct me if I'm wrong) would be implementing a watcher that monitors for changes on both local and remote (if needed). I'm not sure if RClone currently has a watcher feature or not, but I haven't seen that in any of the docs.

Anyways, let me know if this is something that you think the project could benefit from and I'll see if I can whip something up!

**Comment by animosity22** [comment]
Is this still something you'd want to give a go? Was looking to see if needs to remain open or if it can be closed out.

Thanks!

**Comment by soredake** [comment]
+1 for daemon modem would be nice to daemon mode, bidirectional sync, launch systemd service and forget.

**Comment by ivandeex** [comment]
This request _blocks_ on yet unimplemented features:
- fs notify https://github.com/rclone/rclone/issues/249
- event hooks https://github.com/rclone/rclone/issues/4764
- 3-way merge https://github.com/rclone/rclone/pull/3715

**Comment by ivandeex** [comment]
@therecluse26 
Please take a look at this thread https://github.com/rclone/rclone/issues/249#issuecomment-339404550
It provides working solutions to ypur use case

**Comment by ivandeex** [comment]
Closing after 4 months of inactivity
