### ISSUE TITLE
Zip Splip on rcd.go

### ISSUE THREAD

**Issue by nicowaisman** [rclone/rclone#3529]
#### What is the problem you are having with rclone?
Hey rclone team,
We found a potentially vulnerable function to the Zip Slip vulnerability. The idea of the vulnerability is that by triggering a path transversal on a zip file you are able to write files outside of your folder (https://cwe.mitre.org/data/definitions/29.html)
Here is the vulnerable function:
https://github.com/rclone/rclone/blob/master/cmd/rcd/rcd.go#L105

We are well aware, that downloads files passed to unzip only occur from a specific URL provided by rclone, so the risk is really low, but we thought we should give you a heads up.

Regards
Nico Waisman
Semmle Security Team
PS:
Here are some examples of how other project have fix it
https://github.com/mholt/archiver/commit/d818164a438603f1ba3fa952c7d99321f924301copenshhttps://github.com/openshift/source-to-image/commit/f5cbcbc5cc6f8cc2f479a7302443bea407a700cb
https://github.com/cloudfoundry/archiver/commit/09b5706aa9367972c09144a450bb4523049ee840

Or you could check this article:
https://golangcode.com/unzip-files-in-go/
Relevant code snippet:

```  // Check for ZipSlip. More Info: http://bit.ly/2MsjAWE
        if !strings.HasPrefix(path, filepath.Clean(dest)+string(os.PathSeparator)) {
            return fmt.Errorf("%s: illegal file path", path)
        }```

**Comment by ncw** [comment]
Thank you for the heads up.

@negative0 do you want to take this one as you wrote that code? I don't think it will be hard to fix
