### ISSUE TITLE
--copy-links can not be set with an environment variable

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [rclone/rclone#3534]
#### What is the problem you are having with rclone?

Exporting RCLONE_COPY_LINKS=true to the environment seems to have no impact, I have to use -L

#### What is your rclone version (output from `rclone version`)

rclone v1.49.2
- os/arch: linux/amd64
- go version: go1.12.9

(This seems more recent than the latest beta, which is still .0)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux amd64

####  Which cloud storage system are you using? (eg Google Drive)

Backblaze B2

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

export RCLONE_TRANSFERS=24
export RCLONE_FILTER_FROM=/root/.config/rclone/filters
export RCLONE_COPY_LINKS=true
rclone sync / b2crypt:

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2019/09/13 18:48:12 DEBUG : rclone: Version "v1.49.2" starting with parameters ["rclone" "-vv" "sync" "/" "b2crypt:"]
2019/09/13 18:48:12 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2019/09/13 18:48:14 NOTICE: vmlinuz.old: Can't follow symlink without -L/--copy-links
2019/09/13 18:48:14 NOTICE: initrd.img.old: Can't follow symlink without -L/--copy-links

**Comment by ncw** [comment]
The variable you want is `RCLONE_LOCAL_COPY_LINKS` as it is part of the local backend.  This is in the [local backend docs](https://rclone.org/local/#copy-links).

This could maybe be more obvious in the docs, maybe I should call out `-x, -l, -L` and their full name equivalents here: https://rclone.org/docs/#options-1

Would that have helped you?

**Comment by ncw** [comment]
PS You aren't the first person to be caught out by this so I need to fix the docs.

**Comment by s-t-e-v-e-n-k** [comment]
That absolutely would have helped me, and I think you should call out those 3 exceptions, since they don't fit the pattern. Thanks!

**Comment by ncw** [comment]
On further reflection I've decided to fix the code instead of the docs

So I've made --copy-links be configured with both RCLONE_LOCAL_COPY_LINKS and RCLONE_COPY_LINKS which is a whole lot more logical :-)

If you want to give it a try it is here:

https://beta.rclone.org/branch/v1.49.0-060-gef7bfd3f-fix-3534-env-vars-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.50
