### ISSUE TITLE
Regression with serve http host header

### ISSUE THREAD

**Issue by lovelytwo** [rclone/rclone#3539]
While using serve http:

In previous versions http requests that specified the host header as ether localhost or 127.0.0.1 worked. However with the current version 1.49.2 request that set the host header to localhost fail but 127.0.0.1 succeed.

Request and Response using localhost:
Request:
HTTP, length: 537
	GET / HTTP/1.1
	Host: localhost:8080
	Connection: keep-alive
	Pragma: no-cache
	Cache-Control: no-cache
	Upgrade-Insecure-Requests: 1
	User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
	Sec-Fetch-Mode: navigate
	Sec-Fetch-User: ?1
	Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
	Sec-Fetch-Site: none
	Accept-Encoding: gzip, deflate, br
	Accept-Language: en-US,en;q=0.9

Response:
	HTTP/1.1 404 Not Found
	Date: Sun, 15 Sep 2019 01:53:35 GMT

Request and Response using 127.0.0.1 
Request:
	GET / HTTP/1.1
	Host: 127.0.0.1:8080
	Connection: keep-alive
	Pragma: no-cache
	Cache-Control: no-cache
	Upgrade-Insecure-Requests: 1
	User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
	Sec-Fetch-Mode: navigate
	Sec-Fetch-User: ?1
	Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
	Sec-Fetch-Site: none
	Accept-Encoding: gzip, deflate, br
	Accept-Language: en-US,en;q=0.9

Reponse:
	HTTP/1.1 200 OK
	Accept-Ranges: bytes
	Server: rclone/v1.49.2
	Date: Sun, 15 Sep 2019 01:53:20 GMT
	Content-Length: 536
	Content-Type: text/html; charset=utf-8
<redacted>

#### What is your rclone version (output from `rclone version`)
rclone v1.49.2
- os/arch: darwin/amd64
- go version: go1.13

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
OSX 10.14.6

####  Which cloud storage system are you using? (eg Google Drive)
google drive and crypt.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone serve http --read-only --fast-list --no-modtime --no-checksum data:

**Comment by ncw** [comment]
I can't replicate this.

I tried this in one terminal

    rclone serve http /tmp/ -vv

Then this in another

    curl -v --header "Host: adfasdfsdf" http://127.0.0.1:8080/

Whatever you write for the `Host:` header rclone doesn't seem to care and returns the listing.

How is your testing different from this?

**Comment by lovelytwo** [comment]
You right, it wasn't the host header at all. Assumptions :(

I ran your curl test and it worked, however when I ran the following

```
$ curl -v http://localhost:8080/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Mon, 30 Sep 2019 08:32:23 GMT
* no chunk, no close, no size. Assume close to signal end
<
* Closing connection 0
```
The one thing I notice is localhost is resolving to ::1 (ipv6 localhost) instead of 127.0.0.1. So i did a quick lsof, and found another process listening only on ::1:8080. After closing that everything fall back to trying the ipv6 first then using the ipv4 address normally.

Sorry for the false report :(
