### ISSUE TITLE
List in Package Systems

### ISSUE THREAD

**Issue by ZacharyDuBois** [rclone/rclone#354]
It would be awesome to have this listed in Homebrew, MacPorts, Deb/Ubuntu, etc repositories. This is really an awesome piece of software :) I'd contribute if I knew Go :(

**Comment by ncw** [comment]
Excellent idea!

I could really do with help with this though, so if you (or anyone you know) can package stuff then I'd love a contribution!

**Comment by harupong** [comment]
Below is the list of instructions, as a starting point.

- chocolatey(Windows)
    - [CreatePackages · chocolatey/choco Wiki](https://github.com/chocolatey/choco/wiki/CreatePackages)
- Homebrew(Mac)
    - [How to Distribute Binaries for OS X Using Homebrew](http://octavore.com/posts/2016/02/15/distributing-go-apps-os-x)
- Deb/Ubuntu
    - [Debian/dh-make-golang: Automatically creates Debian packaging for Go packages](https://github.com/Debian/dh-make-golang)

I've tried making a chocolatey package for rclone, and it seems to work. You can try it with the steps below if you have chocolatey installed:

```
git clone https://github.com/harupong/chocolatey-rclone
cd chocolatey-rclone
cpack
choco install rclone -fdv -s "%cd%"
```

**Comment by ncw** [comment]
@harupong very cool thank you! Would you like to maintain the chocolaty package for rclone on a permanent basis? Thanks Nick

**Comment by harupong** [comment]
@ncw My pleasure :) I went ahead and uploaded the package to https://chocolatey.org/packages/rclone. If there is anything to be added, just let me know.

And, on the Linux side, you might wanna check out https://packager.io/. They do packaging and hosting  for Linux for free if it's open source projects.

**Comment by ZacharyDuBois** [comment]
I can attempt the Homebrew one once I get a chance :)

**Comment by ncw** [comment]
rclone is now in just about every package manager! See https://rclone.org/install for a list.
