### ISSUE TITLE
all files being named .partial~

### ISSUE THREAD

**Issue by trippinshrumes** [rclone/rclone#3540]
#### What is the problem you are having with rclone?
I switched my rclone setup from vfs to cache, in doing so an issue has come along with it and I believe it may be something in my config file. When in vfs all works as expected. When I switch it to cache, all of a sudden every file is being named .partial~ as the ending

#### What is your rclone version (output from `rclone version`)

1.45

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 18.04 Server 64bit

####  Which cloud storage system are you using? (eg Google Drive)
Gsuite

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

None

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I don't have a log file currently, as everything goes in syslog, and I generally view with tail -f | grep rclone , I don't have a dedicated log for rclone which makes this a bit difficult. 

I was hoping by attaching the working vs the non working service file you might be able to help point out where I went wrong? 

If so they are listed below. The first is the working vfs, the 2nd is the non-working cache where EVERYTHING is being named .partial~

`[Unit]
Description=RClone Service
AssertPathIsDirectory=/DATA/FUSE/Rclone
PartOf=media.service
After=media.service
[Service]
Type=simple
ExecStart=/usr/bin/ionice -c 2 -n 0 -t /usr/bin/rclone mount gdrive: /RAID/FUSE/mergerfs/gdrive \
   --allow-other \
   --dir-cache-time=72h \
   --buffer-size=512M \
   --vfs-read-chunk-size 32M \
   --vfs-read-chunk-size-limit 0 \
   --vfs-cache-mode writes \
   --attr-timeout=1s \
   --syslog \
   --umask 002 \
   --rc \
   --modify-window 1s \
   --log-level INFO
ExecStop=/bin/fusermount -uz /RAID/FUSE/mergerfs/gdrive
Restart=on-abort
User=plex
Group=plex
[Install]
WantedBy=media.service`

![image](https://user-images.githubusercontent.com/13083581/64922644-1ee70180-d797-11e9-906a-b2722434e9de.png)

And for the cache

`[Unit]
Description=RClone Service
AssertPathIsDirectory=/DATA/FUSE/Rclone
PartOf=media.service
After=media.service
[Service]
Type=simple
ExecStart=/usr/bin/ionice -c 2 -n 0 -t /usr/bin/rclone mount cache: /RAID/FUSE/mergerfs/gdrive \
   --allow-other \
   --min-age 2m \
   --dir-cache-time=160h \
   --cache-chunk-size=10M \
   --cache-chunk-total-size=10G \
   --cache-info-age=168h \
   --cache-workers=6 \
   --attr-timeout=1s \
   --cache-tmp-upload-path /RAID/tempStorage/rclone_tmp_upload \
   --modify-window 1s \
   --drive-use-trash=false \
   --cache-chunk-path /home/plex/.cache/rclone/cache-backend \
   --cache-db-path /home/plex/.cache/rclone/cache-backend \
   --cache-dir /home/plex/.cache/rclone \
   --cache-tmp-wait-time 30m \
   --cache-writes \
   --config /home/plex/.config/rclone/rclone.conf \
   --buffer-size=0M \
   --daemon-timeout=10m \
   --tpslimit 5 \
   --syslog \
   --umask 002 \
   --rc \
   --log-level INFO
ExecStop=/bin/fusermount -uz /RAID/FUSE/mergerfs/gdrive
Restart=on-abort
User=plex
Group=plex
[Install]
WantedBy=media.service`

![image](https://user-images.githubusercontent.com/13083581/64922646-2c03f080-d797-11e9-9a65-3e17d7b3362c.png)

A bit of additional info, the /RAID is a 7 drive Raid 0. I put the ionice stuff in when I had the Raid running as a raid 5 in the past, IO was pretty high on the raid so the ionice options helped out, not sure if they're still needed but I don't think they're causing the issue. 

I also had increased the cache-tmp-wait-time to 30m to see if that would help resolve the issue, which it did not. 

If you need logs let me know and I can make it happen. 

Edited to add images of service files, as I didn't like the text formatting.

**Comment by ncw** [comment]
1.45 is quite old as rclone versions go...

Can you try with [the latest release](https://rclone.org/downloads/)?

What application is it that writes the ".partial~" files?

**Comment by trippinshrumes** [comment]
Sonarr and radarr, I have not tested with lidarr mylar or lazy librarian lately. But I imagine the result would be the same, as switching back to vfs immediately resolved the issue.

I thought I had a working script that was updating rclone automatically, apparently that is not the case. I will get rclone updated, retest, and post logs if the issue is still happening.

**Comment by trippinshrumes** [comment]
I have now upgraded to the latest rclone, rclone version displays 1.49.3

This issue still persists. I have a log file below. Did I stumble on a bug? I imagined I had something set wrong in my rclone service file that I was overlooking. 


I hosted the logfile as it was too much to copy paste, in the ~5 minutes of running created a 1gig log, 2 of the episodes were Peaky Blinders S05E05 and Deadliest Catch S15E21

https://drive.google.com/file/d/1yAF9Qk2nOCE5d-b4d5M6Z9oeOLPyscJ8/view?usp=sharing

**Comment by animosity22** [comment]
Radarr and Sonarr both write .partial files and move them afterwards. That's expected behavior from both applications as rclone doesn't write files itself on the mount :)

It's not a bug.

What's the actual issue you are seeing?

**Comment by trippinshrumes** [comment]
if rclone is mounted via cache, via service file posted above. Everyfile is named a .partial~, they even get moved to the cloud like this. 

Sonarr logs show that it moves the file to destination, then looks for the file and cannot find it. That is because the file now has a .partial~ ending. 

The second I put my rclone service file back to vfs, problem immediately resolves itself. 

Whatever is happening, is definitely due to rclone.

**Comment by animosity22** [comment]
Cache-tmp-upload definitely does not like Sonarr/Radarr in how they move files.

You can see the end of your log is where the issue as it Sonarr/Radarr are expecting something to be there and move it, but since the time different isn't quite there, it has an issue.

```
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5: list: cached object: Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E03 - Strategy WEBDL-1080p h264 AAC.mp4
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5: list: cached object: Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E03 - Strategy WEBDL-720p h264 AAC.mp4
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5: list: cached object: Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E04 - The Loop WEBDL-1080p h264 AAC.mp4.partial~
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5: list: cached directories: 0
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5: list: cached dir: 'Tv_Shows/Peaky Blinders/Season 5', cache ts: 2019-09-15 20:58:32.404930884 -0500 CDT m=+293.473960180
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5/: >Lookup: node=<nil>, err=no such file or directory
2019/09/15 20:58:32 DEBUG : &{Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E05 - The Shock WEBDL-1080p h264 AAC.mp4.partial~ (w)}: Flush:
2019/09/15 20:58:32 INFO  : Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E05 - The Shock WEBDL-1080p h264 AAC.mp4.partial~: put: uploaded in temp fs
2019/09/15 20:58:32 INFO  : Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E05 - The Shock WEBDL-1080p h264 AAC.mp4.partial~: put: queued for upload
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E05 - The Shock WEBDL-1080p h264 AAC.mp4.partial~: pending upload found
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E05 - The Shock WEBDL-1080p h264 AAC.mp4.partial~: put: added to cache
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5: cache: expired Tv_Shows/Peaky Blinders/Season 5
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5: cache: expired Tv_Shows/Peaky Blinders
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5: cache: expired Tv_Shows
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5: cache: expired
2019/09/15 20:58:32 INFO  : Tv_Shows/Peaky Blinders/Season 5: put: cache expired
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders: invalidating directory cache
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5: forgetting directory cache
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E05 - The Shock WEBDL-1080p h264 AAC.mp4.partial~: Size and modification time the same (differ by 0s, within tolerance 1s)
2019/09/15 20:58:32 DEBUG : &{Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E05 - The Shock WEBDL-1080p h264 AAC.mp4.partial~ (w)}: >Flush: err=<nil>
2019/09/15 20:58:32 DEBUG : &{Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E05 - The Shock WEBDL-1080p h264 AAC.mp4.partial~ (w)}: Flush:
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E05 - The Shock WEBDL-1080p h264 AAC.mp4.partial~: WriteFileHandle.Flush nothing to do
2019/09/15 20:58:32 DEBUG : &{Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E05 - The Shock WEBDL-1080p h264 AAC.mp4.partial~ (w)}: >Flush: err=<nil>
2019/09/15 20:58:32 DEBUG : &{Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E05 - The Shock WEBDL-1080p h264 AAC.mp4.partial~ (w)}: Release:
2019/09/15 20:58:32 DEBUG : Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E05 - The Shock WEBDL-1080p h264 AAC.mp4.partial~: WriteFileHandle.Release nothing to do
2019/09/15 20:58:32 DEBUG : &{Tv_Shows/Peaky Blinders/Season 5/Peaky Blinders - S05E05 - The Shock WEBDL-1080p h264 AAC.mp4.partial~ (w)}: >Release: err=<nil>
```

If you turn up the Sonarr or Radarr logs to trace, you can see the command bug out there, which causes the problem you are seeing.

**Comment by ncw** [comment]
I think the sequence of events should be like this
- file gets opened as `file.partial`
- file contents gets written
- file gets closed
- file gets uploaded at this point by the VFS layer
- file gets renamed to `file` (both cached version and on the backend)

What I don't see is any `Rename` logs in the log file.  What that means is that the application never asked for the file to be renamed which is why they are all called `partial`.

I don't know why that is though!

**Comment by animosity22** [comment]
Right. The issue is that Sonarr/Radarr don't actually move the partial as the command errors out. The trace logs in either would should the error from Sonarr.

It's also very dependent on the version of mono as well as we've learned from other issues :)

**Comment by trippinshrumes** [comment]
so, these are from Radarr. 

From the debug log I have

`19-9-21 11:43:57.3|Debug|MediaInfoFormatter|Formatting audio channels using 'AudioChannelPositions', with a value of: '2/0/0'
19-9-21 11:43:57.3|Debug|MediaInfoFormatter|Formatting audio channels using 'AudioChannelPositions', with a value of: '2/0/0'
19-9-21 11:43:57.3|Debug|MovieFileMovingService|Moving movie file: /DATA/radarr/nzbget/Superman.Shazam.The.Return.of.Black.Adam.2010.1080p.BluRay.H264.AAC-RARBG/cf403f12ee154e7e9e8d3261192c3e35.mp4 to /DATA/FUSE/Rclone/Movies/Superman+Shazam! The Return of Black Adam (2010)/Superman+Shazam! The Return of Black Adam (2010) Bluray-1080p x264 AAC.mp4
19-9-21 11:43:57.3|Debug|DiskTransferService|Move [/DATA/radarr/nzbget/Superman.Shazam.The.Return.of.Black.Adam.2010.1080p.BluRay.H264.AAC-RARBG/cf403f12ee154e7e9e8d3261192c3e35.mp4] > [/DATA/FUSE/Rclone/Movies/Superman+Shazam! The Return of Black Adam (2010)/Superman+Shazam! The Return of Black Adam (2010) Bluray-1080p x264 AAC.mp4]
19-9-21 11:43:57.9|Warn|ImportApprovedMovie|Couldn't import movie /DATA/radarr/nzbget/Superman.Shazam.The.Return.of.Black.Adam.2010.1080p.BluRay.H264.AAC-RARBG/cf403f12ee154e7e9e8d3261192c3e35.mp4`

What I'm seeing here, is radarr is renaming the file during the move to rclone, And then attempts to look for the file and does not see it, also it is spending .6 of a second and thinks it's moved the file.  

In the trace log during the corresponding time frame we have. 

`19-9-21 11:43:57.3|Debug|VideoFileInfoReader|Getting media info from /DATA/radarr/nzbget/Superman.Shazam.The.Return.of.Black.Adam.2010.1080p.BluRay.H264.AAC-RARBG/cf403f12ee154e7e9e8d3261192c3e35.mp4
19-9-21 11:43:57.3|Trace|MediaInfo|Read file offset 0-16384 (16384 bytes)
19-9-21 11:43:57.3|Trace|MediaInfo|Read file offset 621440515-623685912 (2245397 bytes)
19-9-21 11:43:57.3|Trace|MediaInfo|Read file offset 48-16432 (16384 bytes)
19-9-21 11:43:57.3|Trace|MediaInfo|Read file offset 623685912-623685912 (0 bytes)
19-9-21 11:43:57.3|Trace|MediaInfo|Read a total of 2278165 bytes (0.4%)
19-9-21 11:43:57.3|Debug|DetectSample|Runtime is over 90 seconds
19-9-21 11:43:57.3|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
19-9-21 11:43:57.3|Debug|ImportApprovedMovie|Decisions: 1
19-9-21 11:43:57.3|Trace|UpgradeMediaFileService|Upgrading existing movie file.
19-9-21 11:43:57.3|Debug|MediaInfoFormatter|Formatting audio channels using 'AudioChannelPositions', with a value of: '2/0/0'
19-9-21 11:43:57.3|Debug|MediaInfoFormatter|Formatting audio channels using 'AudioChannelPositions', with a value of: '2/0/0'
19-9-21 11:43:57.3|Debug|MovieFileMovingService|Moving movie file: /DATA/radarr/nzbget/Superman.Shazam.The.Return.of.Black.Adam.2010.1080p.BluRay.H264.AAC-RARBG/cf403f12ee154e7e9e8d3261192c3e35.mp4 to /DATA/FUSE/Rclone/Movies/Superman+Shazam! The Return of Black Adam (2010)/Superman+Shazam! The Return of Black Adam (2010) Bluray-1080p x264 AAC.mp4
19-9-21 11:43:57.3|Debug|DiskTransferService|Move [/DATA/radarr/nzbget/Superman.Shazam.The.Return.of.Black.Adam.2010.1080p.BluRay.H264.AAC-RARBG/cf403f12ee154e7e9e8d3261192c3e35.mp4] > [/DATA/FUSE/Rclone/Movies/Superman+Shazam! The Return of Black Adam (2010)/Superman+Shazam! The Return of Black Adam (2010) Bluray-1080p x264 AAC.mp4]
19-9-21 11:43:57.9|Warn|ImportApprovedMovie|Couldn't import movie /DATA/radarr/nzbget/Superman.Shazam.The.Return.of.Black.Adam.2010.1080p.BluRay.H264.AAC-RARBG/cf403f12ee154e7e9e8d3261192c3e35.mp4

[v0.2.0.1358] System.IO.IOException: Destination already exists [/DATA/FUSE/Rclone/Movies/Superman+Shazam! The Return of Black Adam (2010)/Superman+Shazam! The Return of Black Adam (2010) Bluray-1080p x264 AAC.mp4]
  at NzbDrone.Common.Disk.DiskTransferService.ClearTargetPath (System.String targetPath, System.Boolean overwrite) [0x00029] in <7084924a59f8492b9528f8e6bea68198>:0 
  at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, NzbDrone.Common.Disk.TransferMode mode, System.Boolean overwrite, NzbDrone.Common.Disk.DiskTransferVerificationMode verificationMode) [0x0021f] in <7084924a59f8492b9528f8e6bea68198>:0 
  at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, NzbDrone.Common.Disk.TransferMode mode, System.Boolean overwrite, System.Boolean verified) [0x0000e] in <7084924a59f8492b9528f8e6bea68198>:0 
  at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Movies.Movie movie, System.String destinationFilePath, NzbDrone.Common.Disk.TransferMode mode) [0x0012b] in <28071e62f2f449e682962e05af20a3d7>:0 
  at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Parser.Model.LocalMovie localMovie) [0x0005a] in <28071e62f2f449e682962e05af20a3d7>:0 
  at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Parser.Model.LocalMovie localMovie, System.Boolean copyOnly) [0x000b0] in <28071e62f2f449e682962e05af20a3d7>:0 
  at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import (System.Collections.Generic.List`1[T] decisions, System.Boolean newDownload, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.MediaFiles.MovieImport.ImportMode importMode) [0x00258] in <28071e62f2f449e682962e05af20a3d7>:0 

19-9-21 11:43:57.9|Trace|CommandQueueManager|Updating command status
19-9-21 11:43:57.9|Trace|EventAggregator|Publishing CommandExecutedEvent
19-9-21 11:43:57.9|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
19-9-21 11:43:57.9|Trace|TaskManager|Updating last run time for: NzbDrone.Core.MediaFiles.Commands.DownloadedMoviesScanCommand
19-9-21 11:43:57.9|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
19-9-21 11:43:57.9|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
19-9-21 11:43:57.9|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
19-9-21 11:43:57.9|Trace|CommandExecutor|DownloadedMoviesScanCommand <- DownloadedMovieCommandService [00:00:18.9059570]`

**Comment by trippinshrumes** [comment]
> of

**Comment by trippinshrumes** [comment]
This has been solved. I'm utilizing mergerfs as well, the problem lied in deleting one of the folders linked in my mergerfs setup. 

This is not related to anything with rclone or the arr applications. 

Thank you for your assistance.

**Comment by ncw** [comment]
Glad you got to the bottom of the problem :-)
