### ISSUE TITLE
Sorting files after directories changed! 

### ISSUE THREAD

**Issue by vaccarieli** [rclone/rclone#3542]
Is there a way somehow, to sort files using the sync command ? For example I have 

Gdrive1:   This is my main account which I sort every single day,  I move one file from one directory to another.

Gdrive2:  And this is my backup, which I havr setup to automatically sync all my files from Gdrive1 , as an a mirror, but the thing is that if I change the directory o a file, rclone will think is not on my Gdrive and will download it again, so this affects my quota, hope there is a command that can see thru all my acc and look for the moved file and just sync the sorted stuff made and not redownload all again.

**Comment by J0s3f** [comment]
You should ask usage questions in the forum: https://forum.rclone.org/

anyway, `--track-renames` is what you need.

**Comment by vaccarieli** [comment]
Thanks, for your response, sorry I didn't know it.

One more thing is there a way to add list of a 100 links from google drive to my drive with an Rclone command ? If so could you please tell me I've been digging about it but no luck.

**Comment by animosity22** [comment]
This seems to be a question for the forums rather than an issue. Please feel free to ask there. Thanks!
