### ISSUE TITLE
'Deleted 1 extra copies' message displayed even though duplicates were not deleted

### ISSUE THREAD

**Issue by SezalAgrawal** [rclone/rclone#3551]
#### What is the problem you are having with rclone?
When performing rclone dedupe, if it encounters an insufficientFilePermisson error and is not able to delete duplicates, it still shows message 'Deleted 1 extra copies'. This message should not be printed.

#### What is your rclone version (output from `rclone version`)
rclone v1.49.2-DEV

os/arch: darwin/amd64
go version: go1.12.6

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Mac, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone dedupe first remote2: -vv

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
System:rclone user$ rclone dedupe first remote2: -vv
2019/09/06 18:00:43 NOTICE: first.csv: Found 2 duplicates - deleting identical copies
2019/09/06 18:00:43 ERROR : first.csv: Couldn't delete: googleapi: Error 403: Insufficient Permission: Request had insufficient authentication scopes., insufficientPermissions
2019/09/06 18:00:43 NOTICE: first.csv: Deleted 1 extra copies
.....More files....
2019/09/06 18:00:44 Failed to dedupe with 22 errors: last error was: googleapi: Error 403: Insufficient Permission: Request had insufficient authentication scopes., insufficientPermissions

Discussed on [Forum](https://forum.rclone.org/t/all-duplicates-removed-message-displayed-even-though-duplicates-were-not-deleted/11902)

**Comment by SezalAgrawal** [comment]
I would like to pick this up

**Comment by ncw** [comment]
Great!
