### ISSUE TITLE
Custom Hash

### ISSUE THREAD

**Issue by bacloud14** [rclone/rclone#3556]
Hi,
I was looking for a solution to use [perceptual hash](https://en.wikipedia.org/wiki/Perceptual_hashing) for media files for my company group to be able to reduce data transfer load (to reduce CO2 footprint as a goal).
The targeted service is Microsoft OneDrive.  It seems that they only propose QuickXorHash algorithm to be used by clients to be able to later upload data. 

Of course, it would be a second hash, as hashes are used when transferring data as an integrity check.

**Question**: 
It may be helpful if **rclone** propose a space for custom hashing even if the remote service doesn't. I just came across your project, and would like to know if this is possible to invest more time on hashing on client side.

Many thanks.

**Comment by ncw** [comment]
The rclone hash framework relies on there being a common supported hash in the source and the destination.

For example both s3 and swift support MD5 so objects can be transferred between the two and the data integrity is preserved.

I think your use of a perceptual hash would be somewhat different to this.  Unfortunately most of the cloud providers are not good at searching custom metadata so I think trying to find a given perceptual hash online would be very difficult.
