### ISSUE TITLE
 couldn't connect ssh: ssh: must specify HostKeyCallback

### ISSUE THREAD

**Issue by cocoonkid** [rclone/rclone#3557]
#### What is the problem you are having with rclone?

 couldn't connect ssh: ssh: must specify HostKeyCallback

#### What is your rclone version (output from `rclone version`)

rclone v1.36

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubunut 18.04 64

####  Which cloud storage system are you using? (eg Google Drive)

sftp

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy and rclone sync

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2019/09/20 14:05:09 DEBUG : rclone: Version "v1.36" starting with parameters ["rclone" "-vv" "copy" "/mnt/" "remote://home/user-data/test"]
2019/09/20 14:05:09 Failed to create file system for "remote://home/user-data/test": couldn't connect ssh: ssh: must specify HostKeyCallback

**Comment by ncw** [comment]
This problem was fixed a long time ago in bd2cdeeeab39a6b645e5bd43e59fa67d984604f6 which was released in v1.37

So I suggest [the latest release](https://rclone.org/downloads/) will fix the problem.
