### ISSUE TITLE
SOCKS5 proxy support for FTP, SFTP

### ISSUE THREAD

**Issue by fdefilippo** [rclone/rclone#3558]
#### What is your current rclone version (output from `rclone version`)?

1.49.3

#### What problem are you are trying to solve?

By supporting the SOCKS5 type proxy rclone can connect from within enterprise dmz using any protocol.

#### How do you think rclone should be changed to solve that?

Implementing the RFC-1928 using the golang package: 

https://godoc.org/golang.org/x/net/proxy#SOCKS5

**Comment by J0s3f** [comment]
Rclone has socks5 proxy support: https://rclone.org/faq/#can-i-use-rclone-with-an-http-proxy

just start e.g. with:

	export http_proxy=socks5://proxyserver:1080
	export https_proxy=$http_proxy
	export HTTP_PROXY=$http_proxy
	export HTTPS_PROXY=$http_proxy
	rclone ...

**Comment by fdefilippo** [comment]
> Rclone has socks5 proxy support: https://rclone.org/faq/#can-i-use-rclone-with-an-http-proxy
> 
> just start e.g. with:
> 
> ```
> export http_proxy=socks5://proxyserver:1080
> export https_proxy=$http_proxy
> export HTTP_PROXY=$http_proxy
> export HTTPS_PROXY=$http_proxy
> rclone ...
> ```
> 
> Documentation is missing as described in #1861

No, unfortunately you are confusing with the support of the socks for the http/s protocol. with Socks Type proxy you can incapsulate any protocols: sftp and so on.

**Comment by ivandeex** [comment]
The FTP client library used by rclone supports custom Dial func option: https://pkg.go.dev/github.com/jlaffaye/ftp#DialWithDialFunc
and we can feed it with https://pkg.go.dev/golang.org/x/net/proxy#Dialer

**Comment by ivandeex** [comment]
I'm yet curious how we can tweak rclone test suite to add a mock of socks5 proxy.

**Comment by fdefilippo** [comment]
but is it not enough to create a dialer that uses socks if set? something like:

```
// socks user
        auth := proxy.Auth{
                User:     "user",
                Password: "password",
        }
// create a socks5 dialer
        dialer, err := proxy.SOCKS5("tcp", SOCKS + ":" + PORT, &auth, proxy.Direct)
        if err != nil {
                fmt.Fprintln(os.Stderr, "can't connect to the proxy:", err)
                os.Exit(1)
        }
        conn, err := dialer.Dial("tcp", indirizzo+":"+strconv.Itoa(porta))
        if err != nil {
                log.Fatal(err)
                //return nil, err
        }
```

**Comment by grugel-maintro** [comment]
Are there any updates on this? WOuld love to use it with a tor socks proxy?

**Comment by snowzach** [comment]
First time contributor, hopefully I caught all the ends.. #7158
