### ISSUE TITLE
superfluous response.WriteHeader call in httplib

### ISSUE THREAD

**Issue by fionera** [rclone/rclone#3559]
#### What is the problem you are having with rclone?
rclone serve http throws errors when using _lots_ of connections

#### What is your rclone version (output from `rclone version`)
1.49.0

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian 64bit

####  Which cloud storage system are you using? (eg Google Drive)
Local

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone serve http local: --transfers=9999 --checkers=9999

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
http: superfluous response.WriteHeader call from github.com/rclone/rclone/cmd/serve/httplib/serve.Error (dir.go:72)

**Comment by terorie** [comment]
@fionera Seems like whenever a directory template fails to execute (for example, when the client closes the connection while the response is being sent), `serve.Error` gets called.
https://github.com/rclone/rclone/blob/57d5de6fba12832469c27ee4eae6c2d4aa6a988f/cmd/serve/httplib/serve/dir.go#L85

`serve.Error` then tries to send a new 500 response. When the template already started a response (by calling `WriteHeader` internally), `http` will complain and print the log message.

Two ways to fix it:
 - Don't call `serve.Error`.
 - Catch errors before writing to the `http.ResponseWriter` by buffering the rendered template.

**Comment by fionera** [comment]
I prefer the buffer since this enables more detailed error messages. Also a rendered template isnt that big :)

**Comment by ncw** [comment]
Is there a way of reproducing this problem easily?

Why do the clients disconnect before reading the buffer?

What is the error message in the log?

**Comment by fionera** [comment]
I applied the patch locally and found out that "broken pipe" is the reason for the errors

**Comment by ncw** [comment]
> I applied the patch locally and found out that "broken pipe" is the reason for the errors

Ah! Maybe we could detect that error and not call Error if it is that?

**Comment by terorie** [comment]
> Maybe we could detect that error and not call Error if it is that?
@ncw As soon as the template starts a write on the underlying `http.ResponseWriter`, `res.WriteHeader(http.StatusOK)` gets automatically called. That means `serve.Error` should only be called if no writes were made. Here's an example how to detect this with a custom `io.Writer`: https://github.com/rclone/rclone/pull/3560#issuecomment-533713097

Otherwise, we could render the template to a buffer first and call `serve.Error` if the template execution failed, as implemented in #3560.
