### ISSUE TITLE
“nonempty” mount option is removed in libfuse 3

### ISSUE THREAD

**Issue by mirfatif** [rclone/rclone#3562]
Reference: https://github.com/libfuse/libfuse/commit/0bef21e8543dda7f02b5f4cb3008a7292d249842

Testing on Android:
```
~$ fusermount -V
fusermount3 version: 3.6.2
~$ rclone -V
rclone v1.49.3
- os/arch: linux/arm64
- go version: go1.12.9
~$ rclone -vv mount GDrive:/ test
2019/09/21 14:30:08 DEBUG : rclone: Version "v1.49.3" starting with parameters ["rclone" "-vv" "mount" "GDrive:/" "test"]
2019/09/21 14:30:08 DEBUG : Using config file from "/home/.config/rclone/rclone.conf"
2019/09/21 14:30:08 Fatal error: Directory is not empty: test If you want to mount it anyway use: --allow-non-empty option
~$ rclone -vv mount --allow-non-empty GDrive:/ test
2019/09/21 14:30:14 DEBUG : rclone: Version "v1.49.3" starting with parameters ["rclone" "-vv" "mount" "--allow-non-empty" "GDrive:/" "test"]
2019/09/21 14:30:14 DEBUG : Using config file from "/home/.config/rclone/rclone.conf"
2019/09/21 14:30:14 DEBUG : Google drive root '': Mounting on "test"
2019/09/21 14:30:14 mount helper error: fusermount: unknown option 'nonempty'
2019/09/21 14:30:14 Fatal error: failed to mount FUSE fs: fusermount: exit status 1
```

**Comment by ncw** [comment]
Looks like this is a check that rclone should be doing for itself now...

Fancy sending a Pull Request?

**Comment by mirfatif** [comment]
> Fancy sending a Pull Request?

I wish I could, but all that I know is `./configure && make` :smile: 
Hope someone else will.

**Comment by animosity22** [comment]
nonempty really should never ever be used as it allows for over mounting and hiding things. A bad option and you should really stay way from it.

**Comment by trapexit** [comment]
nonempty was removed from mainline libfuse because the default behavior of mount is `nonempty`.

**Comment by ncw** [comment]
> nonempty really should never ever be used as it allows for over mounting and hiding things. A bad option and you should really stay way from it.

Agreed!  However it is useful if you ever want to use rclone in an autofs mount - if you don't use it there then you get an infinite loop.

**Comment by ivandeex** [comment]
> Agreed! However it is useful if you ever want to use rclone in an autofs mount - if you don't use it there then you get an infinite loop.
@ncw I don't thunk so.
I have recently run tests with rclone mount and systemd autofs on ubuntu xenial using rclone mount wrapper from https://github.com/rclone/rclone/wiki/rclone-fstab-mount-helper-script
All tests were run on Ubuntu Xenial amd64 with latest updates.
The test matrix included:
- remote with a file vs empty remote
- fstab with allow-non-empty (passed to rclone mount via $trans) vs without this option
- backrounding done using shell's ampersand (&) in wrapper vs "rclone mount --daemon ..." without ampersand
- with or without x-systemd.automount in fstab
Results:
- "--daemon" just hangs, always (must be a flag-related bug in rclone, I added a comment in the wiki)
- empty remote just hangs - obviously due to "total 0" loop in wrapper (I added a comment in the wiki)
- allow-non-empty does not affect behaviour, mounts (with or without x-systemd.automount) work correctly with or without this option

**Comment by ivandeex** [comment]
@ncw btw, please review the forgotten https://github.com/rclone/rclone/pull/3503

**Comment by ncw** [comment]
Interesting @ivandeex - what do you think is different from #3246 - in that I was pretty convinced that not using --allow-non-empty was causing some kind of loopy funkiness with autofs.

**Comment by ivandeex** [comment]
Probably user started experimenting with an empty remote and buggy `while ... ls ... 'total 0' ...` loop in the wrapper looped forever, then user created an unnoticed test file while experimenting with fstab options. User (or you) decided that allow-non-empty is the fix.

Just a wild guess...

The loop can be slightly enhanced by using `ls -l -A $mountpoint` so that it sees dotted files too. But this leaves a big hole - no bash loop can properly tell an empty mount from empty unmounted point. 

The proper solution is a **fix** of the `--daemon`/`--daemon-timeout` option. It should fork a background rclone process, wait for "mount successful" signal from child with timeout and exit with appropriate code. This will render looping in the wrapper unneeded, just canonical "exec rclone mount --daemon translated_options...".

**Comment by ivandeex** [comment]
Btw according to this https://github.com/libfuse/libfuse/commit/0bef21e8543dda7f02b5f4cb3008a7292d249842#diff-a136a3ab0403c35496be1955335be9d9R8, now libfuse behaves as if "nonempty" is provided everytime. If it were the fix you'd only have to remove the wiki comment about allow-non-empty ;)

**Comment by mirfatif** [comment]
Actually "nonempty" is never provided, so [this](https://github.com/rclone/rclone/blob/v1.49.3/cmd/cmount/mount.go#L77) needs to be removed.

**Comment by ncw** [comment]
> The proper solution is a **fix** of the `--daemon`/`--daemon-timeout` option. It should fork a background rclone process, wait for "mount successful" signal from child with timeout and exit with appropriate code. This will render looping in the wrapper unneeded, just canonical "exec rclone mount --daemon translated_options...".

Forking is a bit difficult in go in general but doing that might be possible... We'd probably have to write a file or something like that.

Here is the code if you want to have a look

https://github.com/rclone/rclone/blob/master/cmd/mountlib/daemon_unix.go

Note that `--daemon-timeout` is an OSXFUSE feature for extending the time the kernel waits for rclone to respond, so not strictly relevant here.

**Comment by mbc0** [comment]
Hi, I had this working for ages but now the message contradicts itself! it says to use nonempty then when I do it tells me it is unknown? can somebody please explain what I can do to get this to work again? I am not very savvy with this as I copied the instructions from a youtube video.. thank you!

root@UNRAIDSERVER:~# rclone mount  --max-read-ahead 1024k --allow-other dediseedbox: /mnt/disks/dediseedbox &
[1] 59677
root@UNRAIDSERVER:~# 2019/10/15 00:04:09 Fatal error: Directory is not empty: /mnt/disks/dediseedbox If you want to mount it anyway use: --allow-non-empty option
root@UNRAIDSERVER:~# rclone mount  --max-read-ahead 1024k --allow-other --allow-non-empty dediseedbox: /mnt/disks/dediseedbox &
[2] 61241
[1]   Exit 1                  rclone mount --max-read-ahead 1024k --allow-other dediseedbox: /mnt/disks/dediseedbox
root@UNRAIDSERVER:~# 2019/10/15 00:04:26 mount helper error: fusermount: unknown option 'nonempty'
2019/10/15 00:04:26 Fatal error: failed to mount FUSE fs: fusermount: exit status 1

**Comment by mbc0** [comment]
> That is saying your fusermount doesn't support the FUSE option `nonempty` which rclone attempts to set when using `--allow-non-empty`.
> 
> This is exactly what this issue needs to fix.
> 
> In the mean time just make sure your mountpoint is empty of files.
> 
> **Update**: what version of libfuse are you using?

Hi, 
This is on my unraid server Version 6.8.0-rc1 2019-10-11 I am afraid I do not know how to tell what libfuse I am using.  

Do you know if I need to find an alternative method to be able to mount my share again or is there a way to make this work with rclone mount?  I have to use the nonempty method as what I am mounting is my VPS and I need access to it.  

Thanks in advance!

**Comment by mbc0** [comment]
ok, I have found it is libfuse 3.0.0

I hope there is a solution to mounting nonempty directories

Thank you

**Comment by ncw** [comment]
> Do you know if I need to find an alternative method to be able to mount my share again or is there a way to make this work with rclone mount? I have to use the nonempty method as what I am mounting is my VPS and I need access to it.

This needs a little patch to rclone to get it to do the checks itself.

Why cant you just make an empty directory and mount there?

**Comment by mbc0** [comment]
> > Do you know if I need to find an alternative method to be able to mount my share again or is there a way to make this work with rclone mount? I have to use the nonempty method as what I am mounting is my VPS and I need access to it.
> 
> This needs a little patch to rclone to get it to do the checks itself.
> 
> Why cant you just make an empty directory and mount there?

Many Thanks for your reply, I look forward to the patch 👍 Unless I am missing something, how can I make an empty directory on my VPS as I need to access files that are on it, do you mean make an empty folder on root? thank you

**Comment by mbc0** [comment]
Hi, just wondering if there is any news on the patch?  I am sorry to nag but my setup relied heavily on mounting with rclone and wondering if I should wait it out or find an alternative method?  Thanks so much for your time, as mentioned before I need to access files on my vps so the directories are not empty.  Thank you

**Comment by ncw** [comment]
The patch to fix this is quite simple

```patch
diff --git a/cmd/cmount/mount.go b/cmd/cmount/mount.go
index b11ad16f4..05836fbdb 100644
--- a/cmd/cmount/mount.go
+++ b/cmd/cmount/mount.go
@@ -74,9 +74,6 @@ func mountOptions(device string, mountpoint string) (options []string) {
                        options = append(options, "-o", "volname="+mountlib.VolumeName)
                }
        }
-       if mountlib.AllowNonEmpty {
-               options = append(options, "-o", "nonempty")
-       }
        if mountlib.AllowOther {
                options = append(options, "-o", "allow_other")
        }
diff --git a/cmd/mount/mount.go b/cmd/mount/mount.go
index 117eb76da..9e0982803 100644
--- a/cmd/mount/mount.go
+++ b/cmd/mount/mount.go
@@ -46,9 +46,6 @@ func mountOptions(device string) (options []fuse.MountOption) {
        if mountlib.NoAppleXattr {
                options = append(options, fuse.NoAppleXattr())
        }
-       if mountlib.AllowNonEmpty {
-               options = append(options, fuse.AllowNonEmptyMount())
-       }
        if mountlib.AllowOther {
                options = append(options, fuse.AllowOther())
        }
```

However this is backwards incompatible with fuse 2.

I haven't figured out a way of working out which fuse version we are talking to to make it adapt.

I guess I could add a `--fuse-version` flag which would be untidy.

**Comment by mbc0** [comment]
Thank you so much @ncw for taking the time to reply, I am not an expert I am afraid, but if you could please let me know what I should be doing with that reply I will work it out.. I am on unraid if that makes a difference? Again though, thanks for your time.

**Comment by mirfatif** [comment]
@mbc0 that's a patch file. You need to download rclone source code and apply the patch. It will remove a few lines from a file which are causing error. So once you compile rclone binary from the modified source code, you won't get the error any more.

What's your architecture? x86_64?

A simple solution is to use older version (< 3.0) of `fusermount` (if that's possible for you).

**Comment by mbc0** [comment]
Many thanks for your reply, I am using unraid so x64 and fusermount is a plugin so no control regarding reverting back unfortunately.  I am afraid I am not a programmer, unraid kind of does all that for me!  I would not know how to apply the patch unfortunately but thank you for your time trying to help

**Comment by mirfatif** [comment]
@mbc0 [fusermount3](https://www.androidfilehost.com/?fid=1899786940962618622), [rclone](https://www.androidfilehost.com/?fid=1899786940962618623)

**Comment by ivandeex** [comment]
@ncw
do you have any plans to merge the patch on master.
just curious

**Comment by mpartel** [comment]
[libfuse 3.10.2+ accepts and ignores "nonempty"](https://github.com/libfuse/libfuse/releases/tag/fuse-3.10.2), but this is still probably worth patching somehow, since older fuse 3 releases will live in distros for many years.

**Comment by darthShadow** [comment]
@ncw I think this will be required now that bazil/fuse uses fuse3.

**Comment by darthShadow** [comment]
Perhaps the fuse version could be determined from the fusermount version output?

Something similar to this: https://github.com/mxmlnkn/ratarmount/commit/fd9d53c2e3574db50398dbc5ecbb243985a0fc6d

**Comment by ncw** [comment]
@darthShadow It doesn't seem to be a problem for me using the beta and fuse3. Are you seeing a problem? If so which version of fuse?

**Comment by darthShadow** [comment]
It works on Ubuntu 22.04 which has fuse 3.10.5 but fails on Ubuntu 20.04 which only has fuse 3.9.0 (which doesn't support the non-empty flag per the above link).

**Comment by ncw** [comment]
Messed up the non linux builds - try this

[v1.62.0-beta.6693.fa800e336.fix-3562-fuse-nonempty](https://beta.rclone.org/branch/fix-3562-fuse-nonempty/v1.62.0-beta.6693.fa800e336.fix-3562-fuse-nonempty/) on branch [fix-3562-fuse-nonempty](https://github.com/rclone/rclone/tree/fix-3562-fuse-nonempty) (uploaded in 15-30 mins)

**Comment by darthShadow** [comment]
Working fine now, thanks.

---

```
darthshadow@server:~$ ~/temp-1/rclone-v1.62.0-beta.6691.844e8fb8b-linux-amd64/rclone version
rclone v1.62.0-beta.6691.844e8fb8b
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 6.0.6-x64v1-xanmod1 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20rc3
- go/linking: static
- go/tags: none
```
```
darthshadow@server:~$ ~/temp-1/rclone-v1.62.0-beta.6691.844e8fb8b-linux-amd64/rclone mount --allow-non-empty temp-2 temp-3
2023/01/20 13:53:44 Fatal error: failed to mount FUSE fs: fusermount: exec: "fusermount3": executable file not found in $PATH
```
```
# Installed fuse3 in another window
```
```
darthshadow@server:~$ ~/temp-1/rclone-v1.62.0-beta.6691.844e8fb8b-linux-amd64/rclone mount --allow-non-empty temp-2 temp-3
2023/01/20 13:55:23 mount helper error: fusermount3: unknown option 'nonempty'
2023/01/20 13:55:23 Fatal error: failed to mount FUSE fs: fusermount: exit status 1
```
```
darthshadow@server:~$ ~/temp-1/rclone-v1.62.0-beta.6693.fa800e336.fix-3562-fuse-nonempty-linux-amd64/rclone version
rclone v1.62.0-beta.6693.fa800e336.fix-3562-fuse-nonempty
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 6.0.6-x64v1-xanmod1 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20rc3
- go/linking: static
- go/tags: none
```
```
darthshadow@server:~$ ~/temp-1/rclone-v1.62.0-beta.6693.fa800e336.fix-3562-fuse-nonempty-linux-amd64/rclone mount --allow-non-empty temp-2 temp-3
^C2023/01/20 13:55:59 ERROR : temp-3: Unmounted rclone mount
```
```
darthshadow@server:~/temp-3$ touch a b
darthshadow@server:~/temp-3$ cd -
/home/darthshadow
```
```
darthshadow@server:~$ ~/temp-1/rclone-v1.62.0-beta.6693.fa800e336.fix-3562-fuse-nonempty-linux-amd64/rclone mount temp-2 temp-3
2023/01/20 13:56:18 Fatal error: "temp-3" is not empty, use --allow-non-empty to mount anyway
```
```
darthshadow@server:~$ ~/temp-1/rclone-v1.62.0-beta.6693.fa800e336.fix-3562-fuse-nonempty-linux-amd64/rclone mount --allow-non-empty temp-2 temp-3
^C2023/01/20 13:56:25 ERROR : temp-3: Unmounted rclone mount
```

**Comment by ncw** [comment]
@darthShadow thanks for testing.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.62

**Comment by ncw** [comment]
@pmwoodward3 please supply `rclone version` and log output - thank you.

**Comment by pmwoodward3** [comment]
@ncw I just downgraded rclone to stable, restarted the docker container and it works now, so who knows.
