### ISSUE TITLE
GCS: Allow to copy/move with createObject only permission on bucket

### ISSUE THREAD

**Issue by pataquets** [rclone/rclone#3566]
#### What is your current rclone version (output from `rclone version`)?
```$ rclone version
rclone v1.47.0
- os/arch: linux/amd64
- go version: go1.12.4
```

#### What problem are you are trying to solve?
I have a nightly backup script using rclone which moves and then deletes from source files older than X days. With r/w permissions it works ok. However, I would like to use a write-only service account for security reasons. When I run the same script, there is an initial error at listing. Adding `--no-traverse` works at first. It even lists all the (time) matching files and finishes successfully when doing a dry run. However, when run without dry run, it prints the following for each file:

```2019/09/23 14:40:53 ERROR : path/to/file/redacted-file-name: Failed to copy: failed to get bucket: googleapi: Error 403: writeonly-service-account@projectname.iam.gserviceaccount.com does not have storage.objects.list access to myproject-backups., forbidden```

I don't know if it is possible to do it with some other switches, so advice is much appreciated.

#### How do you think rclone should be changed to solve that?
A 'blind copy' kind of switch for minimal, write-only permission usage. Since GCS API's insert method has MD5/CRC32 parameters, I assume it won't break any "check if copied correctly" functionality, so no need, AFAICT to read nothing after writing.

**Comment by animosity22** [comment]
Looks to be stale. If you still have a question, please post on https://forums.rclone.org

Thanks!
