### ISSUE TITLE
Feature Request: Post-Quantum encryption support

### ISSUE THREAD

**Issue by kratosok** [rclone/rclone#3567]
Summary

Please add Post-Quantum Encryption options.
https://csrc.nist.gov/Projects/Post-Quantum-Cryptography
Motivation

With the growth of Quantum computing, it would benefit all privacy minded individuals to have encryption options that are resistant to quantum computing attacks. NIST is currently reviewing and refining the the options presented to make quantum resistant advice available.
A number of the lattice based encryption schemes don't have a significant impact on throughput. Some even have existing advice (Kybers-768 combined with say AES)
A number of the the lattice based encryption schemes are already usable in library form:
https://openquantumsafe.org/#liboqs

**Comment by ncw** [comment]
Where were you thinking this was needed?

- http/TLS?
- ssh/sftp
- the crypt backend?
- somewhere else?

The first two are a job for the go team who maintain that code. The crypt backend would be a possibility...

**Comment by felisucoibi** [comment]
for drive in the future google will see crypted content

**Comment by ivandeex** [comment]
Post-quantum cryptography is rather a buzzword not yet ready for production a.t.m. Without a generally accepted crypto-profile it's not possible to select an appropriate golang library for use in crypto backend or even setup test suite.
I suggest closing this issue.

**Comment by ivandeex** [comment]
Closing after 80 days of inactivity

cc @ncw

**Comment by Babber** [comment]
I'd like to support the idea. A quantum-resistant upgrade for the crypt backend would be very welcome.
