### ISSUE TITLE
Beta download links

### ISSUE THREAD

**Issue by justusiv** [rclone/rclone#3570]
It appears the betas have changed how they are being done with numbering etc but i would still think the contains of the "beta" should have a new versions. If the latest beta is older then the last stable should it contain the stable version?
http://beta.rclone.org/rclone-beta-latest-windows-amd64.zip
contains
rclone-v1.49.0-096-gc41812fc-beta-windows-amd64

**Comment by ncw** [comment]
The beta releases (master branch) have all the changes in the v1.49.3 branch they are just numbered incorrectly.  I backported fixes from master into the v1.49.3 branch.

It isn't quite as easy as you might think to change the beta base version to v1.49.3 as the v1.49.3 tag isn't on the master branch

I do have a fix for this in the works though!

**Comment by ivandeex** [comment]
@ncw
> It isn't quite as easy as you might think to change the beta base version to v1.49.3 as the v1.49.3 tag isn't on the master branch

You can trick travis into building off-master tags like this https://github.com/ivandeex/rclone/blob/master/.travis.yml#L7:
```
branches:
  only:
    - master
    - /^v[012]/
...snip...
deploy:
  on:
    tags: true
    all_branches: true
...snip...
```
Github actions will need a special treatment though.

**Comment by ncw** [comment]
> You can trick travis into building off-master tags like this

Building them isn't the problem, it is getting the correct version back into master...

I'll merge the fix for this in a moment!
