### ISSUE TITLE
Feature Request: serve sftp with auth proxy and public key login 

### ISSUE THREAD

**Issue by fdefilippo** [rclone/rclone#3572]
Hello, can you please add the ability to use ssh keys in the auth proxy so we can use:

rclone --auth-proxy         ~/lavoro/rclone/auth-proxy.php \
           --authorized-keys ~/lavoro/rclone/authorized.keys \
           serve sftp

**Comment by ncw** [comment]
I don't think this would be too tricky to implement

We'd need to call the auth proxy here

https://github.com/rclone/rclone/blob/6750af616758cb7ae153ff986916965ecacb786b/cmd/serve/sftp/server.go#L166

and it would have to return a list of acceptable public keys for that user.

Not 100% sure what format the keys would need to be in but that shouldn't be too hard to figure out.

The auth proxy itself would require need to be called with another key on input maybe `_use_pubkey` and another key on output `_pubkey` which should be a list of acceptable public keys.

https://github.com/rclone/rclone/blob/6750af616758cb7ae153ff986916965ecacb786b/cmd/serve/proxy/proxy.go#L229

Using the auth proxy would mean that --authorized-keys would no longer work.

How does that sound to you?

**Comment by fdefilippo** [comment]
I couldn't ask for better, using auth proxy I can get the keys from where I want, db, ldap, etcd or any other source.
