### ISSUE TITLE
Add "core/quit" to remote API

### ISSUE THREAD

**Issue by kapitainsky** [rclone/rclone#3575]
in relation to issue discussed on the [forum](https://forum.rclone.org/t/rclone-mount-progrmatic-umount-under-windows/12067)

At the moment only way to unmount rclone mounted drive in Windows is by sending "ctrl-C" to rclone process. It makes it very difficult to use rclone from within other applications e.g from [rclone-browser](https://github.com/kapitainsky/RcloneBrowser) I am working on reviving since original repo was archived.

"core/quit" would allow clean unmount by using remote control.

**Comment by ncw** [comment]
Do you fancy implementing this?  I think it would be quite easy.

It would be very similar to core/pid

https://github.com/rclone/rclone/blob/6750af616758cb7ae153ff986916965ecacb786b/fs/rc/internal.go#L77-L93

Just calling os.Exit()

I think calling the atexit handlers might be necessary too, so calling `atexit.Run()`.

Maybe it could take an optional parameter for the exit code which would default to 0.

It might be slightly "nicer" if the actual exit was done in a goroutine after a short delay so the rc returns properly?

**Comment by kapitainsky** [comment]
Ok. I will try:) Travelling all next week but when back I will install go.

**Comment by kapitainsky** [comment]
not sure though about this though

"It might be slightly "nicer" if the actual exit was done in a goroutine after a short delay so the rc returns properly?"

I am not professional dev - rather weekend hobby, and never touched golang.

**Comment by kapitainsky** [comment]
time to learn something new:) I think I start to understand

**Comment by ncw** [comment]
> "It might be slightly "nicer" if the actual exit was done in a goroutine after a short delay so the rc returns properly?"

It will be fine without it, so I wouldn't worry about it!

**Comment by ncw** [comment]
I've merged this fix to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.50

Thank you @sakshamkhanna  for fixing this.

**Comment by caspertone2003** [comment]
@ncw @sakshamkhanna @kapitainsky 
Good job!
Will solve that pesky issue of unmounting under windows!
Thanks All
CT
