### ISSUE TITLE
Google Photos: unable to correctly sync .dng files

### ISSUE THREAD

**Issue by bcmryan** [rclone/rclone#3577]
#### What is the problem you are having with rclone?

I'm using the following command (exact path modified) to sync my Google Photos folder to my local storage drive:  rclone sync -v GooglePhotos:/ "/path/to/Google Pixel XL/rclone/" --backup-dir "/path/to/Google Pixel XL/rclone_modified/$(date +%F)/". As you can see by my directory structure, I'm using a Google Pixel XL which means that I have unlimited Google Photos storage for anything uploaded from my Pixel XL. In order to take advantage of all Google's server space and retain the best possible image quality, I save my pictures (using the Google Play Android 9 version of Photos) as both .jpg and .dng (a raw image format). If I download all my all images/videos from Google Photos via Google Takeout (which was my previous backup method) or copy the folders from my phone to my computer via USB, I have no problem viewing all the images. If I use the aforementioned command, I do not get a valid .dng file, but instead Gwenview, my image viewer which supports .dng and correctly works with .dng files from the previously mentioned methods, displays a red box stating "Loading 'filename.dng' failed Loading meta information failed." Interestingly, since I'm downloading a file (although it is corrupted), I'm also not getting any errors. I would not have known about the problem if I had not manually tried to open a .dng file. (The first image below is the error message from Gwenview. The second image is the .jpg image which was correctly copied. The .zip file below that contains the corrupt .dng.)

![IMG_20190908_090358-error](https://user-images.githubusercontent.com/22618702/65816549-56c16080-e1fd-11e9-939a-34db75a7e392.png)

![IMG_20190908_090358](https://user-images.githubusercontent.com/22618702/65816551-5b861480-e1fd-11e9-8615-5c1d615ae9dc.jpg)

[IMG_20190908_090358.zip](https://github.com/rclone/rclone/files/3665457/IMG_20190908_090358.zip)

#### What is your rclone version (output from `rclone version`)

rclone v1.49.3-100-g6750af61-beta
- os/arch: linux/amd64
- go version: go1.13.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Kubuntu 18.04.3; 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

sync from Google Photos to local storage

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync -v GooglePhotos:/ "/path/to/Google Pixel XL/rclone/" --backup-dir "/path/to/Google Pixel XL/rclone_modified/$(date +%F)/"

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Interestingly, since I'm downloading a file (although it is corrupted), I'm also not getting any errors. I would not have known about the problem if I had not manually tried to open a .dng file.

(Thank you so much for your work on rclone! This is my first-ever bug report, and I'm so happy to be doing it for a program that I use nearly every day!)

**Comment by ncw** [comment]
Interestingly the dng file you attached opens fine for me with `ristretto`

Any chance you could download the file using the google photos web interface and attach that one too so we can have a look at the difference?

I tried uploading and downloading the dng file with rclone and it was bit identical after the redownload.

**Comment by bcmryan** [comment]
Thanks for getting back to me so quickly! (Sorry that it took so long for me to reply, but I had to request and download my entire Google Photos library via Takeout, so that added a bunch of time.)

Below you'll find the checksums (md5) for the images downloaded in a variety of different ways as well as the images themselves in .zip files (broken up because of the GitHub space limit for attached files). I hope this is helpful!

[GooglePixelXL.zip](https://github.com/rclone/rclone/files/3667640/GooglePixelXL.zip)
[GoogleTakeout.zip](https://github.com/rclone/rclone/files/3667641/GoogleTakeout.zip)
[webinterface.zip](https://github.com/rclone/rclone/files/3667643/webinterface.zip)
[rclone.zip](https://github.com/rclone/rclone/files/3667642/rclone.zip)

For images as they are on my phone (copied via USB to my computer), I've appended "GooglePixelXL" to the filename before the extension. For the version I downloaded from Google Takeout, they're named ending with "GoogleTakeout". And per your request, I've added web interface files aptly named with "webinterface". Finally, "rclone" is added to files downloaded via the aforementioned script. (Note that I've only included these images once even though they are found in "/path/to/Google Pixel XL/rclone/media/all/", "/path/to/Google Pixel XL/rclone/media/by-day/2019/2019-09-08", "/path/to/Google Pixel XL/rclone/media/by-month/2019/2019-09", and "/path/to/Google Pixel XL/rclone/media/by-year/2019/". The checksums are the same in all of these locations.)

Here are the md5 checksums. You'll notice that the checksums are the same for GooglePixelXL, GoogleTakeout, and webinterface for both the .jpg and .dng files. Only those downloaded with rclone have different checksums. The file sizes are also significantly smaller for the rclone downloads, i.e. 3.0 MiB instead of 4.4 MiB for the .jpg and only 1.4 MiB instead of 10.4 MiB for the .dng. (I'm disregarding the .json files that are added to Google Takeout downloads.)

a75e469212073c908fa703c325c4c898  IMG_20190908_090358-GooglePixelXL.dng
51e9d2078b3787b5a195c2fdbbb06a2f  IMG_20190908_090358-GooglePixelXL.jpg
a75e469212073c908fa703c325c4c898  IMG_20190908_090358-GoogleTakeout.dng
40f35c91d40593e91eafba5d8bdab7bf  IMG_20190908_090358-GoogleTakeout.dng.json
51e9d2078b3787b5a195c2fdbbb06a2f  IMG_20190908_090358-GoogleTakeout.jpg
3b64530bb323de222339177bb80e0449  IMG_20190908_090358-GoogleTakeout.jpg.json
4f4c93663f0d98f8f63966774fff4b8a  IMG_20190908_090358-rclone.dng
d7ebdeea881acd0aec2340ccd570efb5  IMG_20190908_090358-rclone.jpg
a75e469212073c908fa703c325c4c898  IMG_20190908_090358-webinterface.dng
51e9d2078b3787b5a195c2fdbbb06a2f  IMG_20190908_090358-webinterface.jpg

Just to clarify my "workflow": I took this photo with my stock Camera app on my Google Pixel XL running Android 9. I then uploaded it to Google Photos with the stock Photos app. Then I downloaded it using the variety of means listed above.

In the end I did realize that I could also open the original .dng with Okular (also preinstalled on Kubuntu), but for whatever reason, Gwenview doesn't like that file.

ncw, thanks again for your hard work and commitment to rclone. You're really an asset to the FOSS community!

**Comment by ncw** [comment]
Thank you for your comprehensive test - that is very useful.

I think this is all a consequence of [the google photos API not returning photos in their original format](https://issuetracker.google.com/issues/112096115).

So I think what google is doing is returning a reduced quality dng file for some reason.

This is maddening and if you look at the google bug I linked above you'll see lots of people complaining about it and some comments about RAW files actually being downloaded as jpegs.  That is what appears to have happened here, which probably explains why `gwenview` doesn't like the file.

```
$ file *.dng
IMG_20190908_090358-GooglePixelXL.dng: TIFF image data, little-endian, direntries=45, height=506, bps=554, compression=JPEG, PhotometricIntepretation=YCbCr, manufacturer=Google, model=Pixel XL, orientation=upper-left, width=676
IMG_20190908_090358-rclone.dng:        JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=44, height=506, bps=542, compression=JPEG, PhotometricIntepretation=YCbCr, manufacturer=Google, model=Pixel XL, orientation=upper-left, width=676], baseline, precision 8, 4032x3020, components 3
```

So unfortunately I don't think I can fix this in rclone - it needs google to fix their API.  Commenting on the issue might help.

I did call this out in the docs and it will be even more obvious in v1.50: https://tip.rclone.org/googlephotos/#limitations

> ncw, thanks again for your hard work and commitment to rclone. You're really an asset to the FOSS community!

:blush:

**Comment by bcmryan** [comment]
Dang. Well, thanks for looking at the problem. It does look like it is an API issue then. I had seen the "Limitations" section before posting, but I didn't understand how it applied to me at the time. I hope that it is eventually cleared up on Google's side because I think rclone's directory structure is much cleaner than anything released by Google (who naturally have a vested interested in making it hard to copy your stuff from the cloud to your own hardware). I'll post over on https://issuetracker.google.com/issues/112096115 to confirm this is still an issue on their side.

Thanks again. I guess the issue should be closed because there's nothing else you can do for the time being.

**Comment by ncw** [comment]
Thanks :-) I'll contact the google photos partner team and see what they have to say about it.
