### ISSUE TITLE
S3 Copy Timeout/Retry

### ISSUE THREAD

**Issue by jkladis** [rclone/rclone#3579]
During copies for very large objects (10's of GB) Rclone may time out, and then retry incessantly causing backend storage system resource issue, due to the tens of thousands of requests (even though the copy eventually succeeds). Is it possible to implement better handling of checking so that before a copy starts, ensure the original request was properly completed?

**Comment by ncw** [comment]
Can you post
- rclone version
- a log file of the problem with `-vv` please?

Thank you :-)

**Comment by jkladis** [comment]
Version is rclone-1.47.0-1.el7.x86_64 on CentOS 7
The workaround has been to increase the --contimeout value.

We are requesting -vv from the end user. Right now we have received their output of having used -P.
<img width="884" alt="M2" src="https://user-images.githubusercontent.com/41698889/66052523-58896d80-e4f6-11e9-9ede-fc602565e8ce.png">

**Comment by jkladis** [comment]
To recreate, performed concurrent copies of ~30 GB objects. The example copy completes but is not seen updating on the debug.
`2019/10/02 11:19:42 DEBUG : rclone: Version "v1.47.0" starting with parameters ["rclone" "-vv" "copy" "NIALL:copy-test/Downloads1.tar" "NIALL:copy-test/Download
s11115.tar"]
2019/10/02 11:19:42 DEBUG : Using config file from "C:\\Users\\jkladis\\.config\\rclone\\rclone.conf"
2019/10/02 11:19:42 INFO  : S3 bucket copy-test path Downloads11115.tar/: Waiting for checks to finish
2019/10/02 11:19:42 INFO  : S3 bucket copy-test path Downloads11115.tar/: Waiting for transfers to finish
2019/10/02 11:20:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:      1m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:21:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:      2m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:22:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:      3m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:23:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:      4m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:24:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:      5m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:25:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:      6m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:26:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:      7m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:27:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:      8m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:28:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:      9m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:29:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:     10m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:30:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:     11m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:31:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:     12m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:32:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:     13m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:33:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:     14m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:34:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:     15m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:35:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:     16m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:36:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:     17m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:37:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:     18m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:38:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:     19m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:39:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:     20m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:40:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:     21m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:41:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:     22m0.2s
Transferring:
 *                                 Downloads.tar: transferring

2019/10/02 11:42:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:     23m0.2s
Transferring:
 *                                 Downloads.tar: transferring`

**Comment by jkladis** [comment]
Here's where a retry appears to be captured from Rclone.

`2019/10/02 12:15:33 DEBUG : pacer: low level retry 1/10 (error RequestError: send request failed
caused by: Put http://ch3-02-a4105-20340.ait.cleversafe.com/copy-test/Downloads11115.tar/Downloads.tar: net/http: timeout awaiting response headers)
2019/10/02 12:15:33 DEBUG : pacer: Rate limited, increasing sleep to 10ms
2019/10/02 12:15:42 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 0 / 0, -
Transferred:            0 / 1, 0%
Elapsed time:     56m0.2s
Transferring:
 *                                 Downloads.tar: transferring`

**Comment by ncw** [comment]
> 2019/10/02 11:19:42 DEBUG : rclone: Version "v1.47.0" starting with parameters 
> ["rclone" "-vv" "copy" "NIALL:copy-test/Downloads1.tar" "NIALL:copy-test/Downloads11115.tar"]

So you are doing a server side copy of a file and in the process you get

> net/http: timeout awaiting response headers

Increasing `--conntimeout` will fix this certainly.

However I see you are copying files bigger than 5G and 5G is the max size of file you can server side copy in a single part on AWS, probably for this reason.

There is however an in progress pull request #3552 which implements this functionality which would likely fix this issue properly for you without the additional flag.

What is the storage backend BTW?

**Comment by jkladis** [comment]
The backend is IBM COS S3. My re-creation was performed using an on premise system (flat network, direct connect/no firewalls). The bug referenced in the pull is of interest, so I'll confirm this larger/unlimited copy size is unique and also confirm a multi-part copy will be accepted.

**Comment by ncw** [comment]
> The backend is IBM COS S3.

OK

> My re-creation was performed using an on premise system (flat network, direct connect/no firewalls). The bug referenced in the pull is of interest, so I'll confirm this larger/unlimited copy size is unique and also confirm a multi-part copy will be accepted.

The mutlipart copy is the "proper" solution, put increasing `--conntimeout` is a good workaround if you ask me.

**Comment by ncw** [comment]
I've merged the multipart copy to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.50

Thank you to @TennyZhuang for implementing this
