### ISSUE TITLE
fichier: cannot unmarshal number 5304527242 into Go struct field File.size of type int

### ISSUE THREAD

**Issue by muzzol** [rclone/rclone#3581]
#### What is the problem you are having with rclone?

can't operate on a remote with big files from i686 kernel

#### What is your rclone version (output from `rclone version`)
```
rclone v1.49.3
- os/arch: linux/386
- go version: go1.12.9

```

I've tried with beta too
```
rclone v1.49.4-152-gb9bd15a8-beta
- os/arch: linux/386
- go version: go1.13.1

```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

```
uname -a
Linux muzzol 4.13.13-4-pve #1 SMP PVE 4.13.13-35 (Mon, 8 Jan 2018 10:26:58 +0100) i686 GNU/Linux

```

####  Which cloud storage system are you using? (eg Google Drive)

1fichier

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

ls
copy

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```

rclone -vv ls "1f:/pelis/"
2019/10/01 13:02:32 DEBUG : rclone: Version "v1.49.3" starting with parameters ["rclone" "-vv" "ls" "1f:/pelis/"]
2019/10/01 13:02:32 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2019/10/01 13:02:33 ERROR : : error listing: couldn't list files: json: cannot unmarshal number 5304527242 into Go struct field File.size of type int
2019/10/01 13:02:33 Failed to ls with 2 errors: last error was: couldn't list files: json: cannot unmarshal number 5304527242 into Go struct field File.size of type int

```

I've seen some related issues but problem still persists for me.

**Comment by ncw** [comment]
Ah this is a 32 bit / 64 bit issue which should be easy to fix.

Try this

https://beta.rclone.org/branch/v1.49.4-153-g9d00a9dc-fix-3581-fichier-size-beta/ (uploaded in 15-30 mins)

**Comment by muzzol** [comment]
it works!

thanks for your quick response :)
