### ISSUE TITLE
Read out hash type supported on given remote

### ISSUE THREAD

**Issue by cjnaz** [rclone/rclone#3587]
#### What is your current rclone version (output from `rclone version`)?
$ rclone -V
rclone v1.49.4
- os/arch: linux/amd64
- go version: go1.13.1

#### What problem are you are trying to solve?
Determine the proper hash type to use for a given remote.

#### How do you think rclone should be changed to solve that?
`rclone config show xxx` shows specifics of the given remote.  The feature request is to add to this output what type of hash algo is supported by that remote so that 3rd party tools don't have to hard code their own table of supported hash types per remote type for use in `rclone hashsum`.  (Or please point me to an existing solution.  :>)

**Comment by ncw** [comment]
You can read this via the API.  The `--loopback` connects rclone to itself not via TCP.

```
$ rclone rc --loopback operations/fsinfo fs=drive:
{
	"Features": {
		"About": true,
		"BucketBased": false,
		"BucketBasedRootOK": false,
		"CanHaveEmptyDirectories": true,
		"CaseInsensitive": false,
		"ChangeNotify": true,
		"CleanUp": true,
		"Copy": true,
		"DirCacheFlush": true,
		"DirMove": true,
		"Disconnect": false,
		"DuplicateFiles": true,
		"GetTier": false,
		"IsLocal": false,
		"ListR": true,
		"MergeDirs": true,
		"Move": true,
		"OpenWriterAt": false,
		"PublicLink": true,
		"Purge": true,
		"PutStream": true,
		"PutUnchecked": true,
		"ReadMimeType": true,
		"ServerSideAcrossConfigs": false,
		"SetTier": false,
		"SetWrapper": false,
		"UnWrap": false,
		"UserInfo": false,
		"WrapFs": false,
		"WriteMimeType": true
	},
	"Hashes": [
		"MD5"
	],
	"Name": "drive",
	"Precision": 1000000,
	"Root": "",
	"String": "Google drive root ''"
}
```

I didn't make this into a command because I couldn't figure out where to put it!

**Comment by cjnaz** [comment]
Got it.  Thanks.  Now searching for the documentation for this.

**Comment by ncw** [comment]
The docs are here: https://rclone.org/rc/#operations/fsinfo
