### ISSUE TITLE
Feature request: rclone serve webdav with auth-proxy 

### ISSUE THREAD

**Issue by fdefilippo** [rclone/rclone#3589]
hello,  would it be possible to extend the auth-proxy functionality also to the http protocol?

**Comment by ncw** [comment]
That would be pretty easy I think...

You could also use `rclone serve webdav` with the `--read-only` flag to get pretty much the same effect as the webdav server includes the http server.

Want to have a go at this?

**Comment by fdefilippo** [comment]
hello, actually I need the webdav, but even using it I don't find the auth-proxy option or am I wrong?
