### ISSUE TITLE
Rclone doesn't support paths starting with "~"

### ISSUE THREAD

**Issue by TheFrenchGhosty** [rclone/rclone#3592]
#### What is the problem you are having with rclone?

Rclone doesn't support paths starting with ``~``.

#### What is your rclone version (output from `rclone version`)

Rclone v1.49.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux

####  Which cloud storage system are you using? (eg Google Drive)

N/A

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

``rclone move -vv '~/test.txt'  'Remote:'``

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
$ rclone move -vv '~/test.txt' 'Remote:'
2019/10/05 11:40:27 DEBUG : rclone: Version "v1.49.3" starting with parameters ["rclone" "move" "-vv" "~/test.txt" "Remote:"]
2019/10/05 11:40:27 DEBUG : Using config file from "/home/username/.config/rclone/rclone.conf"
2019/10/05 11:40:28 ERROR : : error reading source directory: directory not found
2019/10/05 11:40:28 INFO  : Encrypted drive 'Remote:': Waiting for checks to finish
2019/10/05 11:40:28 INFO  : Encrypted drive 'Remote:': Waiting for transfers to finish
2019/10/05 11:40:28 ERROR : Attempt 1/3 failed with 2 errors and: directory not found
2019/10/05 11:40:29 ERROR : : error reading source directory: directory not found
2019/10/05 11:40:29 INFO  : Encrypted drive 'Remote:': Waiting for checks to finish
2019/10/05 11:40:29 INFO  : Encrypted drive 'Remote:': Waiting for transfers to finish
2019/10/05 11:40:29 ERROR : Attempt 2/3 failed with 2 errors and: directory not found
2019/10/05 11:40:29 ERROR : : error reading source directory: directory not found
2019/10/05 11:40:29 INFO  : Encrypted drive 'Remote:': Waiting for checks to finish
2019/10/05 11:40:29 INFO  : Encrypted drive 'Remote:': Waiting for transfers to finish
2019/10/05 11:40:29 ERROR : Attempt 3/3 failed with 2 errors and: directory not found
2019/10/05 11:40:29 Failed to move with 2 errors: last error was: directory not found

```

**Comment by ncw** [comment]
It is the job of the shell to interpret `~` in paths, not rclone.  So in

> rclone move -vv '~/test.txt' 'Remote:'

You've told the shell not to interpret the `~` by putting it in single quotes.

Any of these will work

    rclone move -vv ~/test.txt 'Remote:'
    rclone move -vv ~/'test.txt' 'Remote:'
    rclone move -vv ~/"test.txt" 'Remote:'

**Comment by TheFrenchGhosty** [comment]
You're right, my bad... I guess I don't use ``~`` enough

**Comment by ncw** [comment]
> You're right, my bad... I guess I don't use `~` enough

No worries :-)
