### ISSUE TITLE
[BUG] ChangeNotify

### ISSUE THREAD

**Issue by thestigma** [rclone/rclone#3598]
**What is the problem you are having with rclone?**
ChangeNotify was unable to decrypt ... is showing up for files and folder that are not within the scope of the remote that is mounted - for example the unencrypted name of the root folder, or it's parallel folders which also have unencrypted names.

**What is your rclone version (output from rclone version)**
rclone v1.49.4-003-gb5ea6af6-v1.49-fixes-beta
    os/arch: windows/amd64
    go version: go1.12.10

Win10-64

(Still testing this fix build for NCW on another issue, but I don't think it's relevant to this error)
Which OS you are using and how many bits (eg Windows 7, 64 bit)

**Which cloud storage system are you using? (eg Google Drive)**
Google Drive

More info in related discussion thread:
https://forum.rclone.org/t/bug-changenotify-was-unable-to-decrypt/12146

**Comment by ncw** [comment]
I think this is probably a bug in the drive backend which needs to filter the change requests before passing them on.

**Comment by ncw** [comment]
I think this has been fixed by 3ef0c73826888305dcf2a40171717946efc6b070

So I'm going to close this

**Comment by orlea** [comment]
I have Google Drive mounted with encryption and am experiencing this issue.
(shared files from other Google accounts are logged as "ChangeNotify was unable to decrypt "XXX.pdf"", etc.
This is completely random and I don't know what triggers it (but it doesn't break the mount or make the file unreadable, just dirty the console.

```
% rclone --version
rclone v1.58.1
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.4.0-113-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.9
- go/linking: static
- go/tags: none
```

console log example.
```
% rclone mount google-workspace-media: google-workspace-media --allow-other --vfs-cache-mode full --vfs-cache-max-size 5G
2022/06/29 10:44:51 NOTICE: Encrypted drive 'google-workspace-media:': ChangeNotify was unable to decrypt "XXX.pdf": illegal base32 data at input byte 8
```

**Comment by ncw** [comment]
@orlea is that file "XXX.pdf" somewhere on your drive?

**Comment by thestigma** [comment]
The most common way you get this error is if you are using a crypt remote, but one or more of the files in this destination is either unencrypted or encrypted with a different password.
If you do this, the decryption will fail, this error will be shown, and also the file will not be viewable in the crypt mount.
So don't mix encrypted and unencrypted files basically.
But this is expected behavior. 

This bug report is specifically about change-notify picking up files outside the crypt remote's target path, which shouldn't happen. I just want to make sure you are not confusing this bug report with the much more common problem described above.

I thought this issue got resolved quite a long time ago, but I can't say I have tested it recently. I've been out of the loop for a while due to health issues.

**Comment by orlea** [comment]
Thanks for the reply.

I have a remote folder that is crypted under "/media/" as seen from my google drive.
I have this encrypted remote folder mounted, but the sample files output to the console are not in my google drive. (It is a file shared from another google account).

Perhaps I can look at the "shared with me" list in google drive and delete it so that I don't get useless errors in the console.
But there are quite a lot of them and I don't want to do that.

From my experience with this, it just makes the console logs dirty and doesn't seem to cause any other problems.
I was curious so I searched and found this issue so I posted this.

**Comment by thestigma** [comment]
Then you are describing the same issue as me I think: decryption errors from change-notify outside of the scope of the mount.
I haven't experienced this with shared files myself, but that seems plausible enough.
Perhaps something changed to make this bug re-emerge. I'll keep me eyes open for it.
The good news is that it should cause any real problems - outside of producing "junk errors", but I agree that's not an ideal user-experience.
