### ISSUE TITLE
[USABILITY] --files-from override all other filtering, but does not stop you from using both

### ISSUE THREAD

**Issue by thestigma** [rclone/rclone#3599]
Referring to this thread:
https://forum.rclone.org/t/why-do-we-ignore-other-filtering-rules-when-using-the-files-from-flag/12065/5

**Short synopsis of conclusion:**
--files-from overrides all other filtering. We concluded that this was intended behavior for complexity reasons, but it would be reasonable (to prevent user mistakes) to throw an error if user tries to use --files from with other filtering.

**Comment by ncw** [comment]
This would be great first issue.

The checking needs to be done here:
 https://github.com/rclone/rclone/blob/eff11b44cfc1ce233d6c971afee3e9cc25d4468a/fs/filter/filter.go#L119

**Comment by mcaci** [comment]
Hello all, I would love to contribute on this issue.
I have checked a bit your suggestion for the starting point and written some code to tackle this issue.

**Comment by ncw** [comment]
> Hello all, I would love to contribute on this issue.
> I have checked a bit your suggestion for the starting point and written some code to tackle this issue.

Thank you very much :-)

**Comment by mcaci** [comment]
I'm glad I can help :relaxed:
