### ISSUE TITLE
bug: rcserver not checking the existence of static files

### ISSUE THREAD

**Issue by Yexiaoxing** [rclone/rclone#3601]
#### What is the problem you are having with rclone?

rclone is accepting `--rc` as a global config to enable the rcserver. However, it is not checking if the web GUI exists or not and trying to serve it directly. This will cause exception if the web gui is not here.

#### What is your rclone version (output from `rclone version`)

rclone v1.49.5
- os/arch: darwin/amd64
- go version: go1.12.10

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

Minimum reproductive: `rclone config --rc --rc-web-gui`

Expected: Download the web gui tarball and unzip it

Exception: shows 404 instead.

#### Possible fix

Check if the GUI exists or not as `rclone gcd` does.

Please also refer to https://forum.rclone.org/t/beta-testing-webgui-for-rclone/11156/106 for a reproduction.

**Comment by ncw** [comment]
This is a bug :-)

The code for setting up the web gui needs to move from `cmd/rcd/rcd.go` to probably its own file in `fs/rc/webui.go` and the config needs to be called whenever `--rc` is enabled not just when `rclone rcd` is called.

**Comment by ncw** [comment]
@negative0 what do you think about this?

**Comment by Yexiaoxing** [comment]
I can take it if @negative0 does not have time - waiting for his response

**Comment by ncw** [comment]
> I can take it if @negative0 does not have time - waiting for his response

I'm happy for you to take it @Yexiaoxing if you'd like to :-)
