### ISSUE TITLE
rclone ls Z:\ works, but rclone copy "Z:\" "server:/path/" not work, Z is an network driver

### ISSUE THREAD

**Issue by muyufan** [rclone/rclone#3602]
#### What is the problem you are having with rclone?

Command copy needs 2 arguments minimum: you provided 1 non flag arguments: ["Z:\" server:/path/"]

#### What is your rclone version (output from `rclone version`)

rclone v1.48.0
- os/arch: windows/amd64
- go version: go1.12.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 7, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

SSH/SFTP

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy "Z:\" "server:/path/"

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Usage:
  rclone copy source:path dest:path [flags]

Flags:
      --create-empty-src-dirs   Create empty source dirs on destination after copy
  -h, --help                    help for copy

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.
Command copy needs 2 arguments minimum: you provided 1 non flag arguments: ["Z:\" server:/path/"]

**Comment by x0b** [comment]
Per [documentation](https://rclone.org/docs/#windows):
>If you are using the root directory on its own then don’t quote it (see #464 for why), eg
>rclone copy E:\ remote:backup

E.g. use ```Z:\``` instead of ```"Z:\"``` as source.

**Comment by animosity22** [comment]
This looks answered. Closing out.
