### ISSUE TITLE
rclone command to show all current remotes

### ISSUE THREAD

**Issue by alionar** [rclone/rclone#3606]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.49.4-165-gd21ddf28-beta
- os/arch: linux/amd64
- go version: go1.13.1

#### What problem are you are trying to solve?
 I didn't find any rclone command to print all current rclone remotes in my machine anything beside `rclone config`. I want to print all current rclone remote available on my machine **without using** `rclone config` , because i want to execute my  shell script to just print all my rclone remote without input `q` everytime my script execute `rclone config`.

#### How do you think rclone should be changed to solve that?
Can rclone add more command to show all current remote available on my machine **without using** `rclone config`?

Thanks

**Comment by x0b** [comment]
There is a [list of all available commands](https://rclone.org/commands/).

You can use ```rclone listremotes``` ([documentation](https://rclone.org/commands/rclone_listremotes/)) or the rc equivalent ```rclone rc --loopback config/listremotes``` ([documentation](https://rclone.org/rc/#config/listremotes)).

**Comment by alionar** [comment]
Ok thanks for you help, my bad.

**Comment by ncw** [comment]
I'll close this now since @x0b has answered the question perfectly :-)
