### ISSUE TITLE
Cannot mount on FreeBSD: mount_fusefs: -o timeout=: option not supported

### ISSUE THREAD

**Issue by RogerAirgood** [rclone/rclone#3610]
#### What is the problem you are having with rclone?
When running rclone mount, the following error is outputted: 
2019/10/09 21:36:19 mount helper error: mount_fusefs: -o timeout=: option not supported
I just updated today to the newest version of rclone and this issue started happening. 

#### What is your rclone version (output from `rclone version`)
rclone v1.49.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
FreeBSD 12.0-RELEASE-p10 amd64

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount -vv --log-file /var/log/rclone.log cachedrive: /mnt/gdrive

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2019/10/09 21:36:19 INFO  : cachedrive: Chunk Total Size: 15G
2019/10/09 21:36:19 INFO  : cachedrive: Chunk Clean Interval: 1m0s
2019/10/09 21:36:19 INFO  : cachedrive: Workers: 4
2019/10/09 21:36:19 INFO  : cachedrive: File Age: 6h0m0s
2019/10/09 21:36:19 DEBUG : Adding path "cache/expire" to remote control registry
2019/10/09 21:36:19 DEBUG : Adding path "cache/stats" to remote control registry
2019/10/09 21:36:19 DEBUG : Adding path "cache/fetch" to remote control registry
2019/10/09 21:36:19 DEBUG : Cache remote cachedrive:: Mounting on "/mnt/gcache"
2019/10/09 21:36:19 mount helper error: mount_fusefs: -o timeout=: option not supported
2019/10/09 21:36:19 Fatal error: failed to mount FUSE fs: mount_fusefs: exit status 1

**Comment by RogerAirgood** [comment]
I appreciate the prompt response. Your workaround did indeed fix the problem. I have reached out to see if I can get that question answered for you. Once again, thank you for the prompt response.

**Comment by asomers** [comment]
FreeBSD's FUSE maintainer here.  mount_fusefs(8) never did support a timeout option.  It looks like the kernel module intended for the mount helper to have the option, but nobody ever added it.  I could add it, if it's important to you.

**Comment by ncw** [comment]
@asomers wrote:
> FreeBSD's FUSE maintainer here. mount_fusefs(8) never did support a timeout option. It looks like the kernel module intended for the mount helper to have the option, but nobody ever added it.

Ah that probably explains the confusion...

I'll revert the default for the timeout option to 0 which means that rclone won't supply it be default and if we every need it in the future it can be set with `--daemon-timeout`.

> I could add it, if it's important to you.

I think from rclone's perspective it isn't worth spending the time on.

@RogerAirgood I've attempted to fix this here - can you try this without the --daemon-timeout flag workaround?

https://beta.rclone.org/branch/v1.49.5-209-gbc6d9647-fix-3610-freebsd-timeout-beta/ (uploaded in 15-30 mins)

Thanks

**Comment by RogerAirgood** [comment]
@ncw the new version works without issue. Appreciate the hard work!

**Comment by ncw** [comment]
Thanks for testing.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.50
