### ISSUE TITLE
Transfer as temporary file name and then rename it - `--partial` flag

### ISSUE THREAD

**Issue by husisusi** [rclone/rclone#3612]
It would be very useful to have a --partial flag to  upload/download files with temporary names and then rename in a moment to the real name when upload/download fully completed.

**Comment by ncw** [comment]
This is a nice idea and it is something rclone does.

It would only work on backends which support renaming files.

**Comment by husisusi** [comment]
> This is a nice idea and it is something rclone does.
> 
> It would only work on backends which support renaming files.

The goal is not just to be able to resume upload/download at break, the goal is to know if some upload/download process is finished. Winscp does that as default.

**Comment by rubasace** [comment]
What's the state of this issue? Is there any work in progress? It would be very useful for me if rclone could download to a tmp directory and then move the files once finished. Not sure if we can study that as part of this same issue or I can otherwise raise a new one.

**Comment by ncw** [comment]
No-one is working on this at the moment. Do you want to @rubasace ? It probably isn't too complicated. I think the feature you want is `--partial-dir` which is quite related

            --partial               keep partially transferred files
            --partial-dir=DIR       put a partially transferred file into DIR

**Comment by rubasace** [comment]
Sure I can give it a try, though I have no experience at all with go lang. Could you maybe point me in the direction of where should I touch more or less? It would make my life way easier :D

**Comment by Sander0542** [comment]
@rubasace how is the progress going? I badly need this feature.

**Comment by rubasace** [comment]
@Sander0542 I'm afraid not. I didn't have much time to allocate for it. Tried to make my mind around it in a couple of spare hours but didn't manage to understand where to touch.

**Comment by ivandeex** [comment]
We have a good advice from @ncw on implementing this feature in https://github.com/rclone/rclone/issues/3770#issuecomment-559816532

**Comment by ivandeex** [comment]
Dear all
This ticket is a complete twin of https://github.com/rclone/rclone/issues/3770, which has some good notes from @ncw
No one has yet started hacking on it. Having duplicate tickets requesting the same won't help anyway. So I'm merging this one in.
The request is still with us, just a little housekeeping.
You can subscribe to #3770 is interested.
Thank you
