### ISSUE TITLE
Environment variables not setting command line flags

### ISSUE THREAD

**Issue by rayx** [rclone/rclone#3615]
#### What is the problem you are having with rclone?

The man page says:

     Rclone  can  be configured entirely using environment variables.  These can be used to set defaults for options or config file entries.

But that isn't true. For example:

    $ RCLONE_VFS_CACHE_MODE=writes rclone mount onedrive: /onedrive
    2019/10/10 21:09:37 Couldn't find flag "vfs-cache-mode"

If I understand it correctly, setDefaultFromEnv() only looks for flag in top-level options:

    setDefaultFromEnv()
    -> pflag.Lookup()
        -> CommandLine.Lookup()

So I think command specific options can't be configured using environment variables? If so, the man page should be fixed. 

#### What is your rclone version (output from `rclone version`)

    $ rclone --version
    rclone v1.49.3-DEV
    - os/arch: linux/amd64
    - go version: go1.12.6

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
     $ lsb_release -a
    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 18.04.2 LTS
    Release:	18.04
    Codename:	bionic

####  Which cloud storage system are you using? (eg Google Drive)

onedrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

See above.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

    $ RCLONE_VFS_CACHE_MODE=writes rclone --vv mount onedrive: /onedrive
    2019/10/11 11:59:58 Couldn't find flag "vfs-cache-mode"

**Comment by ncw** [comment]
Actually I think this is a bug and it should work...

Try this

https://beta.rclone.org/branch/v1.49.5-206-g480f0e88-fix-3615-envvar-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I discovered that quite a few commands were ignoring env vars so I've fixed all the commands here

https://beta.rclone.org/branch/v1.49.5-208-g51eaec99-fix-3615-envvar-beta/ (uploaded in 15-30 mins)

**Comment by rayx** [comment]
@ncw I pull your fixes at `fix-3615-envvar` branch and build the code. I do sanity check with the two commands below. Both work fine. 

    $ RCLONE_VFS_CACHE_MODE=writes /localdata/golang/go1.12.6/site/bin/rclone --config=/skydrive/appdata/rclone/rclone.conf mount onedrive: /onedrive
    $ RCLONE_CHECK=true /localdata/golang/go1.12.6/site/src/github.com/rclone/rclone/rclone version 

A quick question. I see not all functions in fs/config/flags/flags.go have been changed. For example, `BoolVarP()` is changed, but `BoolP()` isn't. I assume that's OK because the later isn't used in rclone code, right?

Thanks for the great tool.

**Comment by ncw** [comment]
> I pull your fixes at `fix-3615-envvar` branch and build the code. I do sanity check with the two commands below. Both work fine.

Thanks for testing :-)

> A quick question. I see not all functions in fs/config/flags/flags.go have been changed. For example, `BoolVarP()` is changed, but `BoolP()` isn't. I assume that's OK because the later isn't used in rclone code, right?

As far as I can see all the flags defined in `fs/config/flags/flags.go` call `setDefaultFromEnv` so should all be working now.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.50


They are all changed now - maybe you don't have the
