### ISSUE TITLE
Mounting a Put.io volume on Catalina results in a hang affecting all applications

### ISSUE THREAD

**Issue by dnicolson** [rclone/rclone#3618]
#### What is the problem you are having with rclone?

The `rclone mount putio:` command on Catalina causes a hang for any process that touches the mount point, which results in a force restart reasonably quickly. The beta version also has the same issue. Two other machines with Mojave work as expected.

It appears to be Put.io specific as SSH works without any issues.

#### What is your rclone version (output from `rclone version`)

rclone v1.49.5
- os/arch: darwin/amd64
- go version: go1.13.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS Catalina 10.15 GM
macOS Catalina 10.15.1 Beta (19B68f)

####  Which cloud storage system are you using? (eg Google Drive)

Put.io

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone -vv mount putio2: ~/p`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

rclone -vv mount putio2: ~/p
2019/10/12 00:31:00 DEBUG : rclone: Version "v1.49.5" starting with parameters ["rclone" "-vv" "mount" "putio2:" "/Users/dave/p"]
2019/10/12 00:31:01 DEBUG : Using config file from "/Users/dave/.config/rclone/rclone.conf"
2019/10/12 00:31:01 DEBUG : Putio root '': Mounting on "/Users/dave/p"
2019/10/12 00:31:03 INFO  : Putio root '': poll-interval is not supported by this remote
2019/10/12 00:31:03 DEBUG : Adding path "vfs/forget" to remote control registry
2019/10/12 00:31:03 DEBUG : Adding path "vfs/refresh" to remote control registry
2019/10/12 00:31:03 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2019/10/12 00:31:03 DEBUG : : Root:
2019/10/12 00:31:03 DEBUG : : >Root: node=/, err=<nil>
2019/10/12 00:31:03 DEBUG : : Statfs:
2019/10/12 00:31:03 DEBUG : : Statfs:
2019/10/12 00:31:03 DEBUG : : Statfs:
2019/10/12 00:31:12 DEBUG : /: Attr:
2019/10/12 00:31:12 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
2019/10/12 00:31:20 DEBUG : /: Attr:
2019/10/12 00:31:20 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>

**Comment by ncw** [comment]
Can you make sure you've go the latest version of OSXFUSE?  Or maybe try some different versions?

Is there anything in the kernel log?

The hang is likely caused by a particular operation (let's say listing a directory) takes a very long time and the other operations for that directory all pile up behind it.

Can you try shortening the `--daemon-timeout` parameter from its default of 15m to 1m say to see if things hang for 1m and then carry on.

It would be really useful to have a complete log with `-vv` of rclone going wrong if you could post that.

**Comment by dnicolson** [comment]
The latest version of FUSE for macOS (3.10.3) was used on both Mojave and Catalina.

The following line appears in the logs a few times:
`rclone  UNIX error exception: 17`

The above `-vv` log is complete.

The log below is using the `--daemon-timeout` switch, which results in no hanging but a "Device not configured" mount that is not visible in the Finder. 

```
rclone -vv mount --daemon-timeout 1s putio2: p3
2019/10/12 19:50:19 DEBUG : rclone: Version "v1.49.5" starting with parameters ["rclone" "-vv" "mount" "--daemon-timeout" "1s" "putio2:" "p3"]
2019/10/12 19:50:19 DEBUG : Using config file from "/Users/dave/.config/rclone/rclone.conf"
2019/10/12 19:50:19 DEBUG : Putio root '': Mounting on "p3"
2019/10/12 19:50:19 INFO  : Putio root '': poll-interval is not supported by this remote
2019/10/12 19:50:19 DEBUG : Adding path "vfs/forget" to remote control registry
2019/10/12 19:50:19 DEBUG : Adding path "vfs/refresh" to remote control registry
2019/10/12 19:50:19 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2019/10/12 19:50:19 DEBUG : : Root:
2019/10/12 19:50:19 DEBUG : : >Root: node=/, err=<nil>
2019/10/12 19:50:19 DEBUG : : Statfs:
2019/10/12 19:50:19 DEBUG : : Statfs:
2019/10/12 19:50:19 DEBUG : : Statfs:
2019/10/12 19:50:22 DEBUG : : >Statfs: stat={Blocks:26214400 Bfree:12389421 Bavail:12389420 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2019/10/12 19:50:22 DEBUG : : >Statfs: stat={Blocks:26214400 Bfree:12389421 Bavail:12389420 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2019/10/12 19:50:22 DEBUG : : >Statfs: stat={Blocks:26214400 Bfree:12389421 Bavail:12389420 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2019/10/12 19:50:22 DEBUG : rclone: Version "v1.49.5" finishing with parameters ["rclone" "-vv" "mount" "--daemon-timeout" "1s" "putio2:" "p3"]
ls p3
ls: p3: Device not configured
```

**Comment by ncw** [comment]
Thanks for that, very useful.

It looks like the Statfs calls never finish.

Can you try adding --disable About to the command line. This will stop rclone trying to read the fullness from the remote and may work around the problem.

Does

    rclone about putio2:

Work? Or does it hang too? Does it take a very long time?

If it hangs can you run it with -vv --dump bodies and post the output.

**Comment by dnicolson** [comment]
Both of the following commands seem to work correctly:

`rclone about putio2:`
`rclone mount --disable About putio2: p`

**Comment by ncw** [comment]
> Both of the following commands seem to work correctly:
> 
> `rclone about putio2:`

OK

> `rclone mount --disable About putio2: p`

So this is a work-around for the problem... which is good, but we still don't know what is causing the problem...

Can you try this and attach `rclone.log`.  If you could run it until it hangs then kill it. That will show a lot more info!  You might just want to check through it and edit out any confidential bits if you see any.

    rclone mount -vv --debug-fuse --dump bodies --log-file rclone.log putio2: p

**Comment by dnicolson** [comment]
There are some TLS handshake errors, but they occur after the hang.

[rclone.log](https://github.com/rclone/rclone/files/3725599/rclone.log)

**Comment by ncw** [comment]
Thanks for that - very enlightening

First we see this

```
2019/10/14 19:11:13 DEBUG : HTTP REQUEST (req 0xc000144a00)
2019/10/14 19:11:13 DEBUG : GET /v2/account/info HTTP/1.1
Host: api.put.io
User-Agent: rclone/v1.49.5
Accept: application/json
Authorization: XXXX
Accept-Encoding: gzip

```

And then 60 seconds later

```
2019/10/14 19:12:13 DEBUG : HTTP RESPONSE (req 0xc000144a00)
2019/10/14 19:12:13 DEBUG : Error: net/http: TLS handshake timeout
2019/10/14 19:12:13 DEBUG : pacer: low level retry 1/10 (error Get https://api.put.io/v2/account/info: net/http: TLS handshake timeout)
2019/10/14 19:12:13 DEBUG : pacer: Rate limited, increasing sleep to 20ms
```

This is going to retry 10 times so pause for 10 minutes... So lock everything up for 10 minutes.

Now if you run `rclone about putio: -vv --dump bodies` you'll see exactly the same calls...

So why are those calls being blocked?

Could it be some kind of firewalling? Or security measures in the OS?

I would say this is an interaction between the OS and the go runtime...  It would be worth trying [the latest beta](https://beta.rclone.org) which is compiled with go1.13 to see if it has been fixed already.

**Comment by dnicolson** [comment]
The `rclone about putio: -vv --dump bodies` command worked correctly once, now when running it again it leads to timeouts.

It looks like the stable version and beta both use the same Go runtime:

```
./rclone --version
rclone v1.49.5-223-gdd150efd-beta
- os/arch: darwin/amd64
- go version: go1.13.1

rclone --version
rclone v1.49.5
- os/arch: darwin/amd64
- go version: go1.13.1
```

**Comment by dnicolson** [comment]
> Ah, good. If you can replicate it like that then it means that it probably isn't a kernel/runtime interaction and is just something mundane like networking, firewalling, anti virus or something like that.

The firewall is disabled and I can't think of anything that would block it, other apps work fine with Put.io.

> I tried to search to see if anything came up for catalina - this only thing I found was this relatively non technical article which suggests starting in safe mode so you could do that and see if it fixes the rclone about command.

It looks like FUSE for macOS doesn't load when using safe boot:
```
2019/10/18 18:34:19 DEBUG : rclone: Version "v1.49.5" starting with parameters ["rclone" "-vv" "mount" "putio2:" "p3"]
2019/10/18 18:34:19 DEBUG : Using config file from "/Users/dave/.config/rclone/rclone.conf"
2019/10/18 18:34:19 DEBUG : Putio root '': Mounting on "p3"
kext load failed: -603946990
2019/10/18 18:34:19 Fatal error: failed to mount FUSE fs: exit status 255
```

> That is a surprise... Where did you get rclone from? Did you compile it yourself?

Just with Homebrew, it has [v.1.49.5](https://github.com/Homebrew/homebrew-core/blob/master/Formula/rclone.rb).

**Comment by ncw** [comment]
> It looks like FUSE for macOS doesn't load when using safe boot:

If you could just try the `rclone about` command in safe boot.  Try it 10 times (say) to see if it hangs in the same way.

> Just with Homebrew, it has v.1.49.5.

Ah, that explains things.

**Comment by dnicolson** [comment]
I had to reinstall Catalina and now the problem is not reproducible. Reinstalling also resolved Photos and Messages sync issues, perhaps they were all related.

**Comment by ncw** [comment]
> I had to reinstall Catalina and now the problem is not reproducible. Reinstalling also resolved Photos and Messages sync issues, perhaps they were all related.

I'm glad you got to the bottom of it.  A strange problem indeed!
