### ISSUE TITLE
drive: New flag to track share date of files/dirs with `--drive-shared-with-me`

### ISSUE THREAD

**Issue by geart891** [rclone/rclone#3624]
#### What is your current rclone version (output from `rclone version`)?
1.49.5

#### What problem are you are trying to solve?

Generate a list of shared files and directories with `--drive-shared-with-me` tag based on share date. Since shared files/directories can be generated in a large number with a mixture of different file names and/or name patents. 

Traditionally, `--filter-from` might solve this problem, but when working with a number of over 100+ files/dirs it becomes really difficult to do.

#### How do you think rclone should be changed to solve that?
`rclone` has already had `--max-age` tag to track creation/modification time. I think implement another tag for example `--max-share-age` to track the share date would solve this problem.

**Comment by ncw** [comment]
I don't know whether this flag might help - it changes all the dates in use to the client created date

      --drive-use-created-date                     Use file created date instead of modified date.,

**Comment by geart891** [comment]
> I don't know whether this flag might help - it changes all the dates in use to the client created date
> 
> ```
>   --drive-use-created-date                     Use file created date instead of modified date.,
> ```

Thank for the tag, however this only can help in case that new files created have similar share date, in case files which have different created date, it doesnt show correct files. Command tested:
`rclone ls remote: --drive-shared-with-me --max-depth 1 --drive-use-created-date --max-age 1h`
The result is expectedly none.

**Comment by ncw** [comment]
Do you want to work on implementing a `--drive-use-shared-date` flag?

**Comment by garrmcnu** [comment]
Added `--drive-use-shared-date` flag to use share date instead of modification date. If share date is not available, then fall back to modification date as before.

One question is the expected behaviour if the user specifies both `--drive-use-created-date` and `--drive-use-shared-date`? Not sure if there is a preference either way, but created date takes precedence.

**Comment by ncw** [comment]
> Added `--drive-use-shared-date` flag to use share date instead of modification date. If share date is not available, then fall back to modification date as before.

Great

> One question is the expected behaviour if the user specifies both `--drive-use-created-date` and `--drive-use-shared-date`? Not sure if there is a preference either way, but created date takes precedence.

I don't think it matters as long as we document it!

**Comment by geart891** [comment]
> Do you want to work on implementing a `--drive-use-shared-date` flag?

Hey, I would love to, however my go experience is limited. Give me some task and I will do what I can.

**Comment by ncw** [comment]
I've merged this to master now (thank you @garrmcnu ) which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.50
