### ISSUE TITLE
Add gdrive file id support

### ISSUE THREAD

**Issue by ShixAJ** [rclone/rclone#3625]
Hello,
Adding gdrive file id support to rclone would be great.
At the moment there is only support for gdrive folders id's using "root-folder-id".
I guess a similar feature but for files would be great.

**Comment by ncw** [comment]
What I was imagining was that you'd supply `--drive-file-id` and then the remote created would be a remote which just points to that one file.

This would mean you could copy it or whatever you wanted.

Does that sound OK?

**Comment by ShixAJ** [comment]
Yeah I guess. So rclone copy —drive-file-id xxxxxxxxxxxxxxxx destination: ?

**Comment by ShixAJ** [comment]
Also now thinking about it. Have some other ideas. At the moment I have a python script that extracts folder-id's from links in a text file, changes the remote folder id in the config(making it do that because don't know how to use the --drive-root-folder-id flag hehe) and does Rclone copy using that remote as source.
So thinking maybe we could let Rclone take a txt file that has Gdrive ids as input (would need a flag) and copy them all to the destination remote. Not essential to implement since I could just do a small script for it. 
But knowing that I want to see if its possible for Rclone to distinguish between folder-ids and file-id's from the id itself and maybe make a third flag for that. Some gdrive links do say "folder" or "file" inside the URL which I could make the script change the flag depending on them, but some Gdrive links are like "/open?id=xxxxxxxxxxxxx" which will make it impossible for a script that just reads links from a text file to now which flag to use.

**Comment by fionera** [comment]
I just started to work on this. But as I see it we have to make the drive readonly when a file id is given, right?

**Comment by ncw** [comment]
@fionera 
> I just started to work on this. 

Great :-)

> But as I see it we have to make the drive readonly when a file id is given, right?

Do you think so?  I'm assuming that we return ErrIsFile and return the parent directory.

**Comment by ncw** [comment]
> Also now thinking about it. Have some other ideas. At the moment I have a python script that extracts folder-id's from links in a text file, changes the remote folder id in the config(making it do that because don't know how to use the `--drive-root-folder-id` flag hehe) and does Rclone copy using that remote as source.
> So thinking maybe we could let Rclone take a txt file that has Gdrive ids as input (would need a flag) and copy them all to the destination remote. Not essential to implement since I could just do a small script for it.

It is getting a bit specialized but maybe :-)

> But knowing that I want to see if its possible for Rclone to distinguish between folder-ids and file-id's from the id itself and maybe make a third flag for that (like `--drive-id`). Some Gdrive links do say "folder" or "file" inside the URL which I could make the script use to decide which flag to use, but some Gdrive links are like "/open?id=xxxxxxxxxxxxx" which will make it impossible for a script that just reads links from a text file to now which flag to use.

In my drive all file ID's start with `1` and directory IDs start with `0`.  No idea whether that is documented anywhere or even correct!

Use this to see IDs

    rclone lsf drive: -F ip
    rclone lsf -R drive: -F ip

It is a fairly simple query to work out what type of thing a given ID is.

**Comment by ShixAJ** [comment]
> It is getting a bit specialized but maybe :-)

Hehe, Yeah I know which is why I said its not essential to implement :)

> In my drive all file ID's start with `1` and directory IDs start with `0`. No idea whether that is documented anywhere or even correct!
> 
> Use this to see IDs
> 
> ```
> rclone lsf drive: -F ip
> rclone lsf -R drive: -F ip
> ```
> 
> It is a fairly simple query to work out what type of thing a given ID is.

Hmm, Just checked the ID's, for me seems both files and folder seem to start with a 1. So don't know if that will help in finding the type of the ID. 
[Create and populate folders](https://developers.google.com/drive/api/v3/folder)  This says that it could be known using the MIME type

**Comment by fionera** [comment]
I didnt had time to continue yet and probably wont have much, so when anyone want to implement it, please do :)

**Comment by rafaelreis-r** [comment]
> Also now thinking about it. Have some other ideas. At the moment I have a python script that extracts folder-id's from links in a text file, changes the remote folder id in the config(making it do that because don't know how to use the `--drive-root-folder-id` flag hehe) and does Rclone copy using that remote as source.
> So thinking maybe we could let Rclone take a txt file that has Gdrive ids as input (would need a flag) and copy them all to the destination remote. Not essential to implement since I could just do a small script for it.
> But knowing that I want to see if its possible for Rclone to distinguish between folder-ids and file-id's from the id itself and maybe make a third flag for that (like `--drive-id`). Some Gdrive links do say "folder" or "file" inside the URL which I could make the script use to decide which flag to use, but some Gdrive links are like "/open?id=xxxxxxxxxxxxx" which will make it impossible for a script that just reads links from a text file to now which flag to use.

Would you care to share that script?

**Comment by ShixAJ** [comment]
> Would you care to share that script?

Its really not worth sharing. I just created a remote, put it in the beginning of the conf file. The script edits the line that contains the root folder id for that remote with the inputted folderid and runs rclone :D

**Comment by ZizzyDizzyMC** [comment]
I was curious if there were any active process on adding the ability for --drive-id:<fileid> to download.

With the recent deaths of several gdrive CLI utilities, the need for single file download (for archival) is increasing and my personal options for downloading them are decreasing.

**Comment by ncw** [comment]
Rclone has the backend command framework now, so it might actually be easier to implement this as a backend command

    rclone backend copy-file-id drive: ID /path/to/dir/
    rclone backend copy-file-id drive: ID /path/to/dir/filename

What do you think? Useful enough?

**Comment by ZizzyDizzyMC** [comment]
Where `ID` is `Source` and `/path` is `Dest` yeah that'd be perfect.  Since almost all of my usage is scripted or aliased the length (or perceived complexity) of the command isn't really an issue for me.

Just need something that's at least working to download public (not directly shared with anyone) gdrive files by ID.

The old gdrive-cli I used, used to be able to download public folders as well, but those were a less common occurrence.  It'd be great to have that too, for public non-shared-with folders, but that's a future stretch goal for sure.

Really a big thanks for this, I know many people rely on this who don't really participate in Github conversations.

**Comment by ncw** [comment]
Have a go with this and let me know what you think. I haven't written the unit tests yet but it should work

[v1.54.0-beta.4772.61a166d90.fix-3625-drive-copyid](https://beta.rclone.org/branch/fix-3625-drive-copyid/v1.54.0-beta.4772.61a166d90.fix-3625-drive-copyid/) on branch [fix-3625-drive-copyid](https://github.com/rclone/rclone/tree/fix-3625-drive-copyid) (uploaded in 15-30 mins)

Here is the help

#### copyid

Copy files by ID

    rclone backend copyid remote: [options] [<arguments>+]

This command copies files by ID

Usage:

    rclone backend copyid drive: ID path
    rclone backend copyid drive: ID1 path1 ID2 path2
    rclone backend -i untrash drive:directory subdir

It copies the drive file with ID given to the path (an rclone path which
will be passed internally to rclone copyto). The ID and path pairs can be
repeated.

The path should end with a / to indicate copy the file as named to
this directory. If it doesn't end with a / then the last path
component will be used as the file name.

Use the -i flag to see what would be copied before copying.

**Comment by ZizzyDizzyMC** [comment]
Tried every option, including multiple files at once and the confirmation before transfer.

Very nice.  Took me a moment to realize that I had to set up a gdrive remote but after that it was simple enough.
Works fine with my usual option flag `--progress` 

Barring anyone finding bugs I didn't encounter it looks alright for the next incremental release.  I thank you very much for this effort.  Do you have a kofi or something that's 1 time and through PayPal?  I want to send you a token of appreciation for this when I can afford to.

**Comment by ncw** [comment]
Great! Thanks for testing.

It also works copying to a non local backend and if you copy back to your Google drive then it will do a server side copy which is neat.

I'll write some tests for this and merge it 

If you want to support the project then see https://rclone.org/donate/ thanks!

**Comment by l3chmp** [comment]
> Have a go with this and let me know what you think. I haven't written the unit tests yet but it should work
> 
> [v1.54.0-beta.4772.61a166d90.fix-3625-drive-copyid](https://beta.rclone.org/branch/fix-3625-drive-copyid/v1.54.0-beta.4772.61a166d90.fix-3625-drive-copyid/) on branch [fix-3625-drive-copyid](https://github.com/rclone/rclone/tree/fix-3625-drive-copyid) (uploaded in 15-30 mins)
> 
> Here is the help
> 
> #### copyid
> Copy files by ID
> 
> ```
> rclone backend copyid remote: [options] [<arguments>+]
> ```
> 
> This command copies files by ID
> 
> Usage:
> 
> ```
> rclone backend copyid drive: ID path
> rclone backend copyid drive: ID1 path1 ID2 path2
> rclone backend -i untrash drive:directory subdir
> ```
> 
> It copies the drive file with ID given to the path (an rclone path which
> will be passed internally to rclone copyto). The ID and path pairs can be
> repeated.
> 
> The path should end with a / to indicate copy the file as named to
> this directory. If it doesn't end with a / then the last path
> component will be used as the file name.
> 
> Use the -i flag to see what would be copied before copying.

how to use copyid

im try

rclone backend copyid remote: id /test/

error : failed to backend: command "copyid" failed: command not found.

i'm using this beta version

**Comment by l3chmp** [comment]
now aready working use this command

rclone backend copyid remote: id remote:/path/

thankyou

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54

**Comment by 0-MegaMind-0** [comment]
would adding source and dest from file possible too ? 
```
id=xxxxxx dest=remote:path1
id=x1111 dest=pathx
id=1xxxx  dest=remote1:path2
```
or any variations of this would be possible? 
`rclone backend drive-source-remote: . dest --id-dest-from 'copy-files.txt'`
since now i think only possible solution is running multiple parallel rclone instances using xargs or something similar

**Comment by ncw** [comment]
> would adding source and dest from file possible too ?

You should be able to script that very easily...

You can also run `rclone rcd` and use `rclone rc` to give commands to a single running rclone which might be more efficient.

**Comment by RaXorX** [comment]
Is this command only for drive-to-drive copy or can I copy files to local drive too? 
I tried this:
rclone backend copyid drive: FILEID C:\ and rclone backend copyid drive: FILEID C:\TMP.rar
where FILEID was the fileid for a publicly shared file.
It throws me back with this: Failed to backend: didn't find section in config file

**Comment by darthShadow** [comment]
> Failed to backend: didn't find section in config file.

That sounds like a config issue. Please open a new issue or post on the forums at https://forum.rclone.org/ rather than using a closed issue.

**Comment by ShixAJ** [comment]
@ncw Does this support gdrive server side copy?

**Comment by ncw** [comment]
> @ncw Does this support gdrive server side copy? `--drive-server-side-across-configs`

I think so

**Comment by ShixAJ** [comment]
> 
> 
> > @ncw Does this support gdrive server side copy? `--drive-server-side-across-configs`
> 
> I think so

I tried it, don't know if I am doing anything wrong but it doesn't seem like it. 
The command I am using: `rclone backend copyid remote: id , --drive-server-side-across-configs=true -P` and it seems like its sill uploading using my bandwidth. If it can be made so that it server side copies it'd be perfect

**Comment by ivandeex** [comment]
The original problem has already been solved.
Please open a new issue or post on the forums at https://forum.rclone.org/ rather than using a closed issue.
