### ISSUE TITLE
cannot copy or sync to cloud

### ISSUE THREAD

**Issue by lawmanuk** [rclone/rclone#3627]
#### What is the problem you are having with rclone?

cannot copy or sync to cloud.   tried google drive and mega with same error.   can list fine.  can mkdir fine.

when I copy manually or via rclone browser I get following error:

> [newuser@manjaro Documents]$ rclone copy mj/ gdrv:mj
> 2019/10/14 21:04:50 Failed to create file system for "mj/": couldn't parse config item "nounc" = "tmp/" as bool: parsing "tmp/" as bool failed: expected newline

#### What is your rclone version (output from `rclone version`)

> [newuser@manjaro Documents]$ rclone version
> rclone v1.49.5
> - os/arch: linux/amd64
> - go version: go1.13.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

manjaro linux 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

google drive
mega

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

> [newuser@manjaro Documents]$ rclone copy mj/ gdrv-danielc762:mj

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

> [newuser@manjaro Documents]$ rclone -vv copy mj/ gdrv:mj
> 2019/10/14 21:10:33 DEBUG : rclone: Version "v1.49.5" starting with parameters ["rclone" "-vv" "copy" "mj/" "gdrv:mj"]
> 2019/10/14 21:10:33 DEBUG : Using config file from "/home/newuser/.config/rclone/rclone.conf"
> 2019/10/14 21:10:33 Failed to create file system for "mj/": couldn't parse config item "nounc" = "tmp/" as bool: parsing "tmp/" as bool failed: expected newline

**Comment by terorie** [comment]
@lawmanuk As the error message suggests, your rclone version considers the config invalid. Edit `~/.config/rclone/rclone.conf` and remove `"nounc" = "tmp/"`.

**Comment by ncw** [comment]
I think we sorted this out on the forum so I'll close this now
