### ISSUE TITLE
problems moving on cache when using tmp_upload_path

### ISSUE THREAD

**Issue by DaveIsMe** [rclone/rclone#3635]
#### Output of `rclone version`

rclone v1.49.5-228-g38652d04-beta
- os/arch: linux/arm
- go version: go1.13.1

#### Describe the issue

Moving files not working on Cache mount when using tmp_upload_path and b2 backend. Turning off tmp_upload path allows the moving of files.

I get the following output from -vv:

```
Oct 16 16:33:24 raspberrypi rclone[1068]: 2019/10/16 16:33:24 DEBUG : media/tv/Modern Family/Season 11/: >Lookup: node=<nil>, err=no such file or directory
Oct 16 16:33:24 raspberrypi rclone[1068]: 2019/10/16 16:33:24 DEBUG : media/tv/Modern Family/Season 11/: Rename: oldName="testfile", newName="test", newDir=media/tv/Modern Family/Season 11/
Oct 16 16:33:24 raspberrypi rclone[1068]: 2019/10/16 16:33:24 ERROR : media/tv/Modern Family/Season 11/testfile: Dir.Rename error: Fs "Cache remote plexdrive:" can't rename files (no server side Move or Copy)
Oct 16 16:33:24 raspberrypi rclone[1068]: 2019/10/16 16:33:24 DEBUG : media/tv/Modern Family/Season 11/: >Rename: err=Fs "Cache remote plexdrive:" can't rename files (no server side Move or Copy)
Oct 16 16:33:24 raspberrypi rclone[1068]: 2019/10/16 16:33:24 DEBUG : media/tv/Modern Family/Season 11/: Lookup: name="test"
Oct 16 16:33:24 raspberrypi rclone[1068]: 2019/10/16 16:33:24 DEBUG : media/tv/Modern Family/Season 11/: >Lookup: node=<nil>, err=no such file or directory
Oct 16 16:33:24 raspberrypi rclone[1068]: 2019/10/16 16:33:24 DEBUG : media/tv/Modern Family/Season 11/: Lookup: name="test"
Oct 16 16:33:24 raspberrypi rclone[1068]: 2019/10/16 16:33:24 DEBUG : media/tv/Modern Family/Season 11/: >Lookup: node=<nil>, err=no such file or directory
Oct 16 16:33:29 raspberrypi rclone[1068]: 2019/10/16 16:33:29 DEBUG : media/tv/Modern Family/Season 11/: Attr:
Oct 16 16:33:29 raspberrypi rclone[1068]: 2019/10/16 16:33:29 DEBUG : media/tv/Modern Family/Season 11/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
```

**Comment by ncw** [comment]
Can you paste your config with the secrets/personal data removed please?

Also what is the command line of your mount command?

**Comment by DaveIsMe** [comment]
rclone.conf
```
[b2]
type = b2
hard_delete = true

[seedbox-cache]
type = cache
remote = seedbox:files
chunk_total_size = 50G
chunk_no_memory = true
info_age = 5m0s

[seedbox]
type = ftp
port = 21

[plexdrive]
type = cache
remote = b2:plexdrive
chunk_total_size = 500G
```

```
rclone mount plexdrive: /mnt/cache/plexdrive --allow-other --uid 1000 --gid 1000 --umask 0000 --allow-non-empty
rclone mount seedbox-cache: /mnt/cache/seedbox --allow-other
```

**Comment by ncw** [comment]
What does this output?

    rclone rc --loopback operations/fsinfo fs=plexdrive:

What about without `tmp_upload_path`?

It looks like the cache backend doesn't support Move when using tmp_upload_path unless the temporary fs does (which it should) :confused: 

https://github.com/rclone/rclone/blob/22bf8589cdaaea6a2fa15a607f4fc2f330e16157/backend/cache/cache.go#L521-L527

**Comment by DaveIsMe** [comment]
That gives
```
2019/10/18 20:15:46 ERROR : /home/pi/.cache/rclone/cache-backend/plexdrive.db: Error opening storage cache. Is there another rclone running on the same remote? failed to open a cache connection to "/home/pi/.cache/rclone/cache-backend/plexdrive.db": timeout
2019/10/18 20:15:46 Failed to rc: loopback call failed: failed to start cache db: failed to open a cache connection to "/home/pi/.cache/rclone/cache-backend/plexdrive.db": timeout
```

Without tmp_upload_path it moving works.

**Comment by ncw** [comment]
The main difference between those is this

```patch
--- /tmp/without_tmp_upload_path	2019-10-22 13:17:16.427379151 +0100
+++ /tmp/with_tmp_upload_path	2019-10-22 13:17:30.263448142 +0100
@@ -7,7 +7,7 @@
 		"CaseInsensitive": false,
 		"ChangeNotify": false,
 		"CleanUp": true,
-		"Copy": true,
+		"Copy": false,
 		"DirCacheFlush": true,
 		"DirMove": false,
 		"Disconnect": false,
```

Showing that `Copy` isn't supported with `tmp_upload_path`

The problem here is that b2: supports Copy so to move a file you Copy it then Delete the original, where as the local backend supports Move to move a file, but doesn't support Copy.

This means that if you use cache on a backend which doesn't support Move directly then you can't use `tmp_upload_path`.

I'm not sure how to fix this...  We are taking the intersection of 3 different remote types cache, b2 and local and trying to work out what they all support.

I think for the moment you'll have to disable `tmp_upload_path` if you are using b2 as a backend.

**Comment by ivandeex** [comment]
This bug suggests adding a VFS unit test.

**Comment by ivandeex** [comment]
@DaveIsMe 
The _cache_ backend was deprecated a year ago in favor of VFS and is no more supported.
Feel free to reopen against VFS in rclone 1.54 if you can reproduce.
Thanks.
cc @ncw
