### ISSUE TITLE
Feature request: enable serve ftp with TLS

### ISSUE THREAD

**Issue by fdefilippo** [rclone/rclone#3640]
hi, it would be useful to enable tls when using rclone as an ftp server.

rclone --ftp-tls serve ftp \
--client-cert ~/rclone/server.crt \
--client-key ~/rclone/server.key \
--auth-proxy ~/rclone/auth-proxy \
--no-seek

but if i try to connect using tls:

curl -vu test:test --ssl -l ftp://localhost:2121/
* About to connect() to localhost port 2121 (#0)
* Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 2121 (#0)
< 220 Welcome to Rclone v1.49.5 FTP Server
> > AUTH SSL
< 550 Action not taken
> > AUTH TLS
< 550 Action not taken

thnx a lot.

**Comment by ncw** [comment]
The underlying library supports this...

Do you want to have a go at implementing (with my guidance)?

**Comment by goku321** [comment]
can take this up.

**Comment by ncw** [comment]
> can take this up.

That would be great @goku321 - let me know what help you need.

**Comment by goku321** [comment]
Hi @ncw I believe I have to add few flags for TLS options(certificate, key) and pass their values [here](https://github.com/rclone/rclone/blob/f7efce594b113fd20b640491039457a9797de64c/cmd/serve/ftp/ftp.go#L146).

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54

Thanks @goku321 for implementing it.

The flags are `--key` and `--cert`
