### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x9a4887]

### ISSUE THREAD

**Issue by vaccarieli** [rclone/rclone#3642]
Hi I am getting this error:

``2019-10-20 10:06:35 NOTICE: ／doc1／ - 20.xlsx: Duplicate object found in destination - ignoring
Transferred:        2.119M / 2.119 MBytes, 100%, 457.414 kBytes/s, ETA 0s
Errors:                 1 (retrying may help)
Checks:                 1 / 1, 100%
Transferred:            0 / 0, -
Elapsed time:        4.7spanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x9a4887]

goroutine 36 [running]:
github.com/rclone/rclone/fs/operations.Copy(0x1875f00, 0xc00031f8c0, 0x18899a0, 0xc000001c80, 0x1889a20, 0x0, 0xc00056aea0, 0x2a, 0x1889aa0, 0xc0000e0e00, ...)
        /home/runner/work/rclone/src/github.com/rclone/rclone/fs/operations/operations.go:356 +0x1217
github.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove(0xc00046fa40, 0x1875f00, 0xc00031f8c0, 0xc00031f840, 0x18899a0, 0xc000001c80, 0xc00046fb18)
        /home/runner/work/rclone/src/github.com/rclone/rclone/fs/sync/sync.go:297 +0x21c
created by github.com/rclone/rclone/fs/sync.(*syncCopyMove).startTransfers
        /home/runner/work/rclone/src/github.com/rclone/rclone/fs/sync/sync.go:322 +0xb1``

while using this command:

``rclone sync "gdrive:folder/" "gdrive2:MyBackups/" -P "--max-transfer=720G" --exclude "Folder1/folder1/**" --exclude "Folder1/Folder6/**" --exclude "Folder3/**" --exclude "Folder5/**" | tee "/home/user/logs/Rclone-backup.log" ``

however if i remove the --exclude tag like this : 

``rclone sync "gdrive:folder/" "gdrive2:MyBackups/" -P "--max-transfer=720G" | tee "/home/user/logs/Rclone-backup.log" ``

everything works good, don`t know why but it just suddenly stopped from working for no reason.

**Comment by ncw** [comment]
Can you tell me which version of rclone you are using? (with `rclone version`).

Can you reproduce this with [the latest beta](https://beta.rclone.org)?

**Comment by vaccarieli** [comment]
Sorry I was away, thid issue was fixed in one of the latest beta version.
