### ISSUE TITLE
rclone 1.49.1 requires mutable configuration file

### ISSUE THREAD

**Issue by aanderse** [rclone/rclone#3643]
#### What is the problem you are having with rclone?
**Context:** my `rclone` configuration file is immutable as it sits on a read-only filesystem.

After upgrading from `rclone` version `1.46` to version `1.49.1` it appears the `rclone` `sync` command requires my configuration file to be mutable. I do not want my configuration file to be mutable, though... a mutable configuration file never used to be a requirement.

#### What is your rclone version (output from `rclone version`)
```
$ rclone --version
rclone v1.49.1
- os/arch: linux/amd64
- go version: go1.12.9
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
```
$ uname -a
Linux entadono 4.19.78 #1-NixOS SMP Mon Oct 7 16:57:29 UTC 2019 x86_64 GNU/Linux
$ head -n1 /etc/os-release 
NAME=NixOS
```

####  Which cloud storage system are you using? (eg Google Drive)
```
$ head -n2 /nix/store/vaim5ki5bg47j64z7bllbmycilxpniwc-rclone.conf
[moya]
type = sftp
```

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
/nix/store/lrm276ml5ff7sdnc0yiam0xz3ff41zak-rclone-1.49.1/bin/rclone --config /nix/store/vaim5ki5bg47j64z7bllbmycilxpniwc-rclone.conf -v sync moya:/srv/homevideos "/srv/Home Videos"
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
$ /nix/store/lrm276ml5ff7sdnc0yiam0xz3ff41zak-rclone-1.49.1/bin/rclone --config /nix/store/vaim5ki5bg47j64z7bllbmycilxpniwc-rclone.conf -v sync moya:/srv/homevideos "/srv/Home Videos"
2019/10/20 08:27:52 Failed to save config after 10 tries: Failed to create temp file for new config: open /nix/store/vaim5ki5bg47j64z7bllbmycilxpniwc-rclone.conf064812019: read-only file system
```

**Comment by sbrandtb** [comment]
We have the same problem, minor version change.

We want to use rclone on Kubernetes and mount the config file from a config map. Since the original file needs to be modifyable, it's pretty much impossible now without providing an ugly wrapper script that first copies it to some modifyable location.

**Comment by ncw** [comment]
@aanderse 
> After upgrading from `rclone` version `1.46` to version `1.49.1` it appears the `rclone` `sync` command requires my configuration file to be mutable.

rclone is caching the discovered sftp checksum mode in  the config file which is what is new in 1.49

if you set these in the config then rclone won't have to write to the config file

#### --sftp-md5sum-command

The command used to read md5 hashes. Leave blank for autodetect.

- Config:      md5sum_command
- Env Var:     RCLONE_SFTP_MD5SUM_COMMAND
- Type:        string
- Default:     ""

#### --sftp-sha1sum-command

The command used to read sha1 hashes. Leave blank for autodetect.

- Config:      sha1sum_command
- Env Var:     RCLONE_SFTP_SHA1SUM_COMMAND
- Type:        string
- Default:     ""

**Comment by ncw** [comment]
@sbrandtb 
> We have the same problem, minor version change.
> 
> We want to use rclone on Kubernetes and mount the config file from a config map. Since the original file needs to be modifyable, it's pretty much impossible now without providing an ugly wrapper script that first copies it to some modifyable location.

Which backend are you using? Some backends (eg google drive) need to store updated tokens in the config file.

Rclone stores everything in the config file to make things simpler for the user - all the config is in the config file.  Copy the config file from one machine to another and you have a working rclone.

This, alas, makes it more complicated for your use case.

**Comment by aanderse** [comment]
@ncw this resolves my issue. I appreciate the help! :tada: 

I'm just using the `sftp` backend, so everything works with your solution. Thanks again!

**Comment by sbrandtb** [comment]
@ncw Your workaround also helped me, but I still just consider this a workaround since it seems unpredictable for the user if the config would be changed or not. Can we do something about this?

* Introduce the rule that the config is immutable? Why should we write the found algorithm in the first place? Performance? That should not be the default if it makes the application harder to use IMO.
* Introduce immutability as an option?

**Comment by ncw** [comment]
> @ncw Your workaround also helped me, but I still just consider this a workaround since it seems unpredictable for the user if the config would be changed or not. Can we do something about this?
> 
> * Introduce the rule that the config is immutable?

I think we are too far down this road to change now!  All the backends using oauth write tokens to the config file for instance.

> Why should we write the found algorithm in the first place? Performance? That should not be the default if it makes the application harder to use IMO.

Yes it is for performance and for the majority of users the have a mutable config file so won't even notice.  You can also set this advanced settings.

> * Introduce immutability as an option?

I'd consider adding immutability as an option.  This would be saving the mutable bits of the config to a separate file I think.

**Comment by aanderse** [comment]
> I'd consider adding immutability as an option. This would be saving the mutable bits of the config to a separate file I think.

:+1:

**Comment by ncw** [comment]
@aanderse do you want to please make a [new issue](https://github.com/rclone/rclone/issues/new/choose) about this?

**Comment by aanderse** [comment]
@ncw [certainly](https://github.com/rclone/rclone/issues/3655). Thank you for your consideration and help.

**Comment by BlakeMcMurray** [comment]
Hello, 

I am likewise having issues here.  When I run rclone config, I attempt to set up google drive with all default conditions, and at the end of the process, receive the following error:

Failed to save config after 10 tries: Failed to create temp file for new config: open /Users/blakemcmurray/.config/rclone/rclone.conf458369007: permission denied

However, when I try to visit the file (/Users/blakemcmurray/.config/rclone/rclone.conf458369007), the file does not exist on my computer.  

Might someone assist me here?

I have rclone working with google drive on a remote server, and the program is phenominal. 

Kind regards,

Blake

**Comment by ncw** [comment]
Check the ownership of `/Users/blakemcmurray/.config/rclone` it should be owned by you, not root

**Comment by BlakeMcMurray** [comment]
Thank you very much.  Everything is working now.  What a hassle to change ownership though on macOS sierra...
