### ISSUE TITLE
not deleting files as there were IO errors over UNC-Path

### ISSUE THREAD

**Issue by xopez** [rclone/rclone#3647]
#### What is the problem you are having with rclone?

Rclone can't delete on my NAS. I use the Fritzbox from AVM as NAS.
Access is granted over UNC-Path
It tells me following:
```
Local file system at \\?\UNC\Fritz-nas\fritz.nas\WD-Elements25A2-01\Backup\daily\1: not deleting files as there were IO errors
```

#### What is your rclone version (output from `rclone version`)

rclone v1.49.5
- os/arch: windows/amd64
- go version: go1.12.10

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10 (1903)
Build 18362.418

####  Which cloud storage system are you using? (eg Google Drive)

Local to UNC-Path

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
C:\Users\sasch\Documents\rclone\rclone.exe sync -P -L --delete-excluded --exclude "/AppData/**" --exclude "/Nextcloud/**" --exclude "/Videos/Filme/**" C:\Users\sasch\ \\Fritz-nas\fritz.nas\WD-Elements25A2-01\Backup\daily\1
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I share the log from my Nextcloud, because it's to big for pastebin
Log: https://nx6375.your-storageshare.de/s/KjJJKLyM7rPzrxD

**Comment by ncw** [comment]
If you want rclone to move to the delete phase of the sync then you need to fix the ERROR logs

So either give rclone access to the directories or use an exclude file to exclude them.  And don't write the log (I'm assuming that is `1.txt`) to the file tree - or exclude it.

If all else fails you can use

      --ignore-errors      delete even if there are I/O errors

but I recommend fixing the errors.  There is a good reason why rclone doesn't delete files if there have been errors - if you use `--ignore-errors` and accidentally remove permissions to one directory then rclone will delete it on the destination because it will assume it doesn't exist.  This is how rsync works too...

```
2019/10/21 21:51:04 ERROR : Eigene Dateien: failed to open directory "Eigene Dateien": open \\?\C:\Users\sasch\Eigene Dateien: Access is denied.
2019/10/21 21:51:04 ERROR : Vorlagen: failed to open directory "Vorlagen": open \\?\C:\Users\sasch\Vorlagen: Access is denied.
2019/10/21 21:51:05 ERROR : 1.txt: Failed to copy: can't copy - source file is being updated (size changed from 5136871 to 5385546)
2019/10/21 21:51:05 ERROR : Documents/Eigene Bilder: failed to open directory "Documents/Eigene Bilder": open \\?\C:\Users\sasch\Documents\Eigene Bilder: Access is denied.
2019/10/21 21:51:06 ERROR : Documents/Eigene Videos: failed to open directory "Documents/Eigene Videos": open \\?\C:\Users\sasch\Documents\Eigene Videos: Access is denied.
2019/10/21 21:56:42 ERROR : Local file system at \\?\UNC\Fritz-nas\fritz.nas\WD-Elements25A2-01\Backup\daily\1: not deleting files as there were IO errors
2019/10/21 21:56:42 ERROR : Local file system at \\?\UNC\Fritz-nas\fritz.nas\WD-Elements25A2-01\Backup\daily\1: not deleting directories as there were IO errors
2019/10/21 21:56:42 ERROR : Attempt 2/3 failed with 22 errors and: can't copy - source file is being updated (size changed from 5136871 to 5385546)
```
