### ISSUE TITLE
--cache-writes with mergerfs config

### ISSUE THREAD

**Issue by GettingTechnicl** [rclone/rclone#3649]
#### What is the problem you are having with rclone?

I utilize the cache mount on my main SSD, when files are moved to rclone's local cloud directory I initially want the files stored on the drive and then uploaded. This can be accomplished utilizing --cache-tmp-upload-path, although I work with large files and this has extreme limitations such as moving a 10 gig file from ssd to RAID will take less than 30 seconds, and with tmp-upload it would take an unbearable amount of time. 

Therefore I came across a solution utilizing mergerfs and a separate rclone upload script that I was able to make work for my cause. Although I then created a problem where after files were uploaded to the cloud they were not seen locally due to cache-time/age... the reason why --cache-writes is available. 

I have attempted adding --cache-chunk-path, --cache-db-path, --cache-dir as well as adding --cache-writes to my upload script. 

This has not solved the problem I have created. I have noticed much better performance when utilizing cache and would prefer not to utilize --vfs-writes. 

#### What is your rclone version (output from `rclone version`)

v1.49.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 18.04 x64

####  Which cloud storage system are you using? (eg Google Drive)

Gsuite

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone move $FROM $TO -c --transfers=5 --checkers=10 --delete-after --cache-writes --max-transfer=700G --delete-empty-src-dirs --min-age 5m --cache-chunk-path /RAID/tempStorage/.cache/rclone/cache-backend --cache-db-path /RAID/tempStorage/.cache/rclone/cache-backend --cache-dir /RAID/tempStorage/.cache/rclone --log-level INFO --log-file=$LOGFILE

**Comment by ncw** [comment]
It would probably be best to talk about this on [the rclone forum](https://forum.rclone.org/).  There are many users who use a combination of rclone mount + mergerfs without cache to solve this problem.

I'm going to close this issue since it is more of a help query rather than something which needs fixing right now.
