### ISSUE TITLE
Implement Azure Files

### ISSUE THREAD

**Issue by mohitarora** [rclone/rclone#365]
Any plans to add Azure Storage Accounts?

**Comment by ncw** [comment]
I just had a look at the API. It looks like rclone could do blob or file storage. Which of those is more interesting to you?

**Comment by mohitarora** [comment]
Actually both

We use https://trac.cyberduck.io/wiki/help/en/howto/cli for blobs so kind of covered there. 

Azure Files will be more interesting to us.

**Comment by tracker1** [comment]
For reference...

https://github.com/Azure/azure-sdk-for-go

**Comment by ncw** [comment]
I've re-purposed this issue to be just about azure files, since rclone now implements azure blob storage.

**Comment by ncw** [comment]
I'll just note that Microsoft appear to have made a new go SDK for files: https://github.com/Azure/azure-storage-file-go which looks comprehensive and has a low level and a high level interface.

**Comment by xfdywy** [comment]
Hi, are there any updates for the support of MS azure file share? Thanks~

**Comment by ncw** [comment]
I haven't had time to work on this. Anyone want to have a go?

**Comment by ivandeex** [comment]
@ncw @mohitarora 
Aint this implemented by https://rclone.org/azureblob ?

**Comment by ncw** [comment]
> @ncw @mohitarora
> Aint this implemented by https://rclone.org/azureblob ?

No its a different thing "azure files"

I did make a start at a backend but I didn't get past the skeleton.

I think it is perfectly possible if someone would like to work on it.

**Comment by rogelioamancisidor** [comment]
It would be very helpful to add azure files. If I'm not misting, azure files is preferred over azure blobs for people using kubernetes in azure due to some functionalities.

**Comment by ncw** [comment]
If someone's company would like to sponsor this that would help move it up the TODO list! Drop me an email nick@craig-wood.com if interested.

**Comment by alextaf7** [comment]
Hi, are there any updates for the support of Azure file share? Thanks !

**Comment by daymanbpi** [comment]
any update to this? azcopy is terrible.

**Comment by ncw** [comment]
I don't think anyone is working on this @daymanbpi - do you want to? Or do you want to sponsor the work?

**Comment by daymanbpi** [comment]
> I don't think anyone is working on this @daymanbpi - do you want to? Or do you want to sponsor the work?

Yea i could sponsor. Let me know how that works.

**Comment by moong-dal** [comment]
I have been working on adding AzureFIles [repo](https://github.com/moong-dal/rclone/tree/azurefiles)
The programing style and logic is different from what the other backends use. Contrary to the recommendation in contributing.md

It passes the integration tests, and the tests under fs/operations and fs/sync. Test results are included [here](https://github.com/moong-dal/rclone/tree/azurefiles/backend/azurefiles/test_results)

Documentation, speed, accounting and some features such as mimetype and custom metadata are pending.

While I complete the above items, can someone please share test results from other backends. I want to make sure that all tests are being run.

**Comment by ncw** [comment]
@moong-dal great work! Step one is to make **all** the `TestIntegration` tests work. If you can get those ones to run without errors, then the other tests will likely make very few errors.

If you want to see the output from the other backends see https://pub.rclone.org/integration-tests/current/ Click on the logs to see the verbose output. Yes all backends should pass all integration tests all the time. We have a few troublesome ones as you'll see but that is what we aim for.

Try running `golangci-lint run` on your code - there are lots of things you need to fix up there. Don't make methods public that don't need to be public. You'll need to put back all the help for the methods that was there in the backend you started from.

If you want me to comment more, then make a PR and I can point to individual lines of code.

**Comment by moong-dal** [comment]
Thanks for the link to the test outputs.
When you say 'I need to put back all the help for the methods that was there in the backend I started from'  are you referring to documentation/docstrings or something else?

Ill make a PR later when I have improved code quality and implemented a few more features.

**Comment by ncw** [comment]
> When you say 'I need to put back all the help for the methods that was there in the backend I started from' are you referring to documentation/docstrings or something else?

I'm referring to the documentation at the start of each method. The contributing instructions say

> Create backend/remote/remote.go (copy this from a similar remote)
> - box is a good one to start from if you have a directory-based remote
> - b2 is a good one to start from if you have a bucket-based remote

In those backends all the external methods will have had comments, eg

https://github.com/rclone/rclone/blob/6255d9dfaa9322a6c3e176b7b0ec365b6ddd6b04/backend/b2/b2.go#L1062-L1067

`golangci-lint` checks that all external methods have a comment as they go towards making the documentation, eg

https://pkg.go.dev/github.com/rclone/rclone/backend/b2#Fs.Put

I can see you have external methods which will have had comments in the original backend suitable for the documentation, but now don't, eg

https://github.com/moong-dal/rclone/blob/2983d4bfead4eebc6fb2ed72b136a2723da741e1/backend/azurefiles/fs.go#L119-L124
 
> Ill make a PR later when I have improved code quality and implemented a few more features.

Great - thank you - looking forward to it :-)

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.65

Testing appreciated :-)
