### ISSUE TITLE
RClone Counts Errors twice for Copy operations

### ISSUE THREAD

**Issue by ankur0493** [rclone/rclone#3650]
#### What is the problem you are having with rclone?
RClone counts errors twice for the copy operations

#### What is your rclone version (output from `rclone version`)
RClone 1.49.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 18.04 LTS, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Developing a new backend for RClone

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
copy

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

![image](https://user-images.githubusercontent.com/7876747/67278197-201df380-f4e6-11e9-9b2f-ca719b5dcbc0.png)

This happens because `fs.CountError(err)` is called once from within the `Copy()` function in `operations.go` and is then again called as part of `tr.Done(err)`. This results in the errors being counted twice. 

It looks like `fs.CountError` is again being called once at the end of all files, though I couldn't trace from where it is called. For every error, the count is 2n+1.

**Comment by ncw** [comment]
Hmm,, the convention in rclone code is that `fs.CountError()` is called when you call `fs.Error`.  So maybe the `tr.Done()` code needs changing.

On the other hand `tr.Done()` is a nice catchall for any errors during a transfer.

Thoughts?  Would you like to help fix this?

**Comment by ankur0493** [comment]
@ncw  Apologies for the delayed response. I will take up this issue.

`tr.stats.Error` is being called from within `tr.Done`, which in turn increments the stats. So the correct change IMO would be to remove calls to `fs.CountError` wherever we are using a transfer.

Additionally, `CountError` is also called from `cmd.Run`, which increments the error count by one more. Perhaps we should remove this from `cmd.Run` as well?

**Comment by ncw** [comment]
> Apologies for the delayed response. I will take up this issue.

Great - thank you!
 
> `tr.stats.Error` is being called from within `tr.Done`, which in turn increments the stats. So the correct change IMO would be to remove calls to `fs.CountError` wherever we are using a transfer.

I think that is probably correct... Within a `tr.stats` "block" then we shouldn't be calling `fs.CountError` if we report the error in the `tr.Done`.

It probably needs a bit of careful tracing through!

I'd rather over count the errors than undercount them - if the error flag isn't set when it should be then for instance sync will move on to the deletions phase.

> Additionally, `CountError` is also called from `cmd.Run`, which increments the error count by one more. Perhaps we should remove this from `cmd.Run` as well?

Run is used for all the rclone commands and it is likely that they haven't counted errors.

Maybe we could store the last error and make `CountError` not count it if it is a duplicate?

**Comment by ankur0493** [comment]
@ncw  While working on this task, I am uncovering many inconsistencies in the stats:
- fs/sync/sync.go #pairChecker: the done on checking transfer is never called if the transfer errors out. This means that for files that end up as errors will not be included in "checks" count
- fs/operations/operations.go: We call Copy() from Move(). a `CheckingTransfer` is created in `Move()` and then a `Transfer` is created in `Copy()`. In case a error happens, both these transfer count that.
