### ISSUE TITLE
Rclone cannot share the folder with other user if you created the disk folder 

### ISSUE THREAD

**Issue by juukee** [rclone/rclone#3653]

**Comment by ncw** [comment]
Can you fill in the issue template?  I can't see what your issue is - thank you :-)

**Comment by juukee** [comment]
What is the problem you are having with rclone?
What is your rclone version (output from rclone version)
rclone v1.49.5
- os/arch: windows/amd64
- go version: go1.12.10
Which OS you are using and how many bits (eg Windows 7, 64 bit)
Window7/Window Server 2008 SP2
Which cloud storage system are you using? (eg Google Drive)
OneDrive
The command you were trying to run (eg rclone copy /tmp remote:tmp)
rclone mount 
A log from the command with the -vv flag (eg output from rclone -vv copy /tmp remote:tmp)
![图片](https://user-images.githubusercontent.com/28680837/67375218-e5cf5780-f5b4-11e9-9ed1-458de6a20229.png)
 it seems that the disk folder cannot share with others...but i cant get some debug messages why cause this reason

**Comment by ncw** [comment]
Are you trying to share a folder from an rclone mount?

What does the error say?  Can you translate for me?

**Comment by juukee** [comment]
yes. im trying to share a folder,but the error message say that is that the folder cannot share...   
in the normal folder we can share with others ,but i cant share it from an rclone mount folder or document.

**Comment by animosity22** [comment]
It's more this issue:

https://github.com/billziss-gh/winfsp/issues/145

If you want to read through that and test it out, it's more related to winfsp than rclone.

**Comment by animosity22** [comment]
This seems stale.

If you still have a question, please ask on https://forums.rclnoe.org
