### ISSUE TITLE
SFTP Error doesn't seem to be retried

### ISSUE THREAD

**Issue by sbrandtb** [rclone/rclone#3656]
#### What is the problem you are having with rclone?

We are pulling data from an apparently rather unreliable data source, hence we enabled retrying with sleep in between. That also works for most errors, but one error leads to rclone immediately exit and seemingly not retrying:

`2019/10/23 10:45:37 Failed to create file system for "foo:": NewFs: couldn't initialise SFTP: EOF`

#### What is your rclone version (output from `rclone version`)

rclone v1.49.5
- os/arch: linux/amd64
- go version: go1.13.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

linux/amd64

####  Which cloud storage system are you using? (eg Google Drive)

SFTP

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone copy foo: s3:bar`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2019/10/23 12:13:21 DEBUG : rclone: Version "v1.49.5" starting with parameters ["/usr/bin/rclone" "copy" "foo:" "s3:bar" "--config" "/root/rclone/config" "--filter" "+ /bar/**" "--filter" "+ /baz/**" "--filter" "- *" "--retries-sleep" "10s" "--backup-dir" "s3:foo/backup" "--max-delete" "0" "--size-only" "-vv"]
2019/10/23 12:13:21 DEBUG : Using config file from "/root/rclone/config"
2019/10/23 12:13:27 DEBUG : sftp://xxx@yyy:22/: New connection 100.96.2.187:51900->176.9.117.162:22 to "SSH-2.0-OpenSSH_6.7p1 Debian-5"
2019/10/23 12:13:31 Failed to create file system for "foo:": NewFs: couldn't initialise SFTP: EOF
```

**Comment by ncw** [comment]
It would be easy enough to make the sftp connection retry

A bit of retry here

https://github.com/rclone/rclone/blob/a3a5857874e8bd8839d099de7cf7f98b7e77eb23/backend/sftp/sftp.go#L310

would do the trick.

Fancy having a go at this?

**Comment by sbrandtb** [comment]
@ncw I'm no golang developer, but I'll have a look at it in my next free slot.

**Comment by sbrandtb** [comment]
@ncw Merge request is created - can I do anything else?

**Comment by ncw** [comment]
> Merge request is created - can I do anything else?

Sorry a bit behind on pull requests!  Have commented now :-)
