### ISSUE TITLE
will we develop the Baidu Disk? support for baidu pan(百度网盘)

### ISSUE THREAD

**Issue by juukee** [rclone/rclone#3658]
Dear guys:
      we are looking for the Baidu Disk support, many people use it in the China, 1T or 2T free 
so i dont know will be support in the feature or not? if you will develop it ,i can support my Baidu account.

the link: [Baidu Disk](https://pan.baidu.com)

**Comment by ContinuedBug** [comment]
#2099

**Comment by ncw** [comment]
Can you add your support to #2099 please

I'll close this one - thanks

**Comment by raymanzhang** [comment]
Baidu Pan reopens their public api now. Everyone can apply for the access via https://pan.baidu.com/union/apply . And there are docments for the api too :  https://pan.baidu.com/union/document .  Really wish rclone can support it. Thanks.
