### ISSUE TITLE
rclone's quickxorhash is not outputed with base64 encode.

### ISSUE THREAD

**Issue by landall** [rclone/rclone#3663]
#### What is the problem you are having with rclone?

"rclone.exe hashsum QuickXorHash" provide wrong hashsum.
for example:
right answer from OneDrive(MSGraph): YRGOjrsXgjL2OWgbDoPtWUIDfzs=
the answer from rclone: 61118e8ebb178232f639681b0e83ed5942037f3b
it should be outputed by base64 encoding.

#### What is your rclone version (output from `rclone version`)

rclone v1.47.0
- os/arch: windows/amd64
- go version: go1.11

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

64

####  Which cloud storage system are you using? (eg Google Drive)

OneDrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone.exe hashsum QuickXorHash <a local file>

**Comment by ncw** [comment]
The standard for the unix md5sum/sha1sum/*sum commands is to output the hash in hex.

However we could add a `--base64` option to output them in base64 easily enough...

Want to work on this?

**Comment by ncw** [comment]
You can show the hashes are the same easily enough (in python)

```
>>> "YRGOjrsXgjL2OWgbDoPtWUIDfzs=".decode("base64").encode("hex")
'61118e8ebb178232f639681b0e83ed5942037f3b'
```

**Comment by landall** [comment]
> The standard for the unix md5sum/sha1sum/*sum commands is to output the hash in hex.
> 
> However we could add a `--base64` option to output them in base64 easily enough...
> 
> Want to work on this?

It's better to do so to compare the hashsum with other software using ms graph api directly.

**Comment by ncw** [comment]
@landall would you like to implement this?

**Comment by landall** [comment]
> @landall would you like to implement this?

i can try, i am a newbie to go but i seems this is not a language-related function.  how should i write the test code?

**Comment by landall** [comment]
I try to commit a patch now.

**Comment by landall** [comment]
I need some help, what does File is not `goimports`-ed (goimports) mean?
