### ISSUE TITLE
onedrive: DirMove failing with: The bound function binding to 'microsoft.graph.driveItem' does not support the escape function annotation.

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#3664]
#### What is the problem you are having with rclone?

The integration tests [are failing on onedrive](https://pub.rclone.org/integration-tests/current/onedrive-fs.operations-TestOneDrive-5.txt)

#### What is your rclone version (output from `rclone version`)

master, though this is reproducible with v1.49.5, v1.48, v1.47 (didn't try any further back)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 19.04, amd64

####  Which cloud storage system are you using? (eg Google Drive)

OneDrive personal

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
$ cd fs/operations
$ go test -v -remote TestOneDrive: -verbose -test.run '^TestDirMove$'
2019/10/25 14:51:21 DEBUG : One drive root 'rclone-test-kurazes5xihixih2meqekeh7': Token expired but no uploads in progress - doing nothing
2019/10/25 14:51:21 DEBUG : TestOneDrive: Loaded invalid token from config file - ignoring
2019/10/25 14:51:21 DEBUG : TestOneDrive: Saved new token in config file
=== RUN   TestDirMove
2019/10/25 14:51:23 DEBUG : A1/one: Starting multipart upload
2019/10/25 14:51:23 DEBUG : A1/one: Uploading segment 0/3 size 3
2019/10/25 14:51:24 DEBUG : A1/two: Starting multipart upload
2019/10/25 14:51:24 DEBUG : A1/two: Uploading segment 0/3 size 3
2019/10/25 14:51:25 DEBUG : A1/B1/three: Starting multipart upload
2019/10/25 14:51:26 DEBUG : A1/B1/three: Uploading segment 0/5 size 5
2019/10/25 14:51:26 DEBUG : A1/B1/C1/four: Starting multipart upload
2019/10/25 14:51:27 DEBUG : A1/B1/C1/four: Uploading segment 0/4 size 4
2019/10/25 14:51:28 DEBUG : A1/B1/C2/five: Starting multipart upload
2019/10/25 14:51:28 DEBUG : A1/B1/C2/five: Uploading segment 0/4 size 4
2019/10/25 14:51:28 DEBUG : A1/B2: Making directory
2019/10/25 14:51:29 DEBUG : A1/B1/C3: Making directory
--- FAIL: TestDirMove (14.17s)
    run.go:176: Remote "One drive root 'rclone-test-kurazes5xihixih2meqekeh7'", Local "Local file system at /tmp/rclone678421448", Modify Window "1s"
    operations_test.go:1304: 
        	Error Trace:	operations_test.go:1304
        	Error:      	Received unexpected error:
        	            	BadRequest: The request URI is not valid. The bound function binding to 'microsoft.graph.driveItem' does not support the escape function annotation.
        	Test:       	TestDirMove
FAIL
2019/10/25 14:51:36 DEBUG : One drive root 'rclone-test-kurazes5xihixih2meqekeh7': Purge remote
exit status 1
FAIL	github.com/rclone/rclone/fs/operations	15.314s
```

@Cnly have you got time to take a look at this?

**Comment by ncw** [comment]
I managed to replicate this with

    rclone move onedrive:rclone-test-cuyejuj7tevutis1tifeleq1/ onedrive:rclone-test-cuyejuj7tevutis1tifeleq2/ -vv --dump bodies --low-level-retries 1 --retries 1

So I reported it as an upstream regression https://github.com/OneDrive/onedrive-api-docs/issues/1177

This is unfortunate timing as I'm just about to release the 1.50 release.

However I think there is a good chance this is a regression at OneDrive that Microsoft will fix.  If not then we can issue a point release with a fix.

**Comment by Cnly** [comment]
This is weird... And the error message doesn't make sense to me. I think we can wait for a while for a upstream response first and I'll pay attention to it.

**Comment by ncw** [comment]
> This is weird... And the error message doesn't make sense to me.

No me neither!

> I think we can wait for a while for a upstream response first and I'll pay attention to it.

:+1:

**Comment by Cnly** [comment]
Did some testing and it seems OneDrive is not quite happy with the trailing slash in the request that reads the metadata of an item by its ID. i.e.

```
GET /v1.0/drives/<DRIVEID>/items/<ITEMID>:/
```

gives 400, but 

```
GET /v1.0/drives/<DRIVEID>/items/<ITEMID>:
```

is okay. I'm still running the tests with this workaround now and they are passing so far...
