### ISSUE TITLE
Enable chunked uploads for Nextcloud

### ISSUE THREAD

**Issue by Arno500** [rclone/rclone#3666]
As quickly discussed here : https://forum.rclone.org/t/could-rclone-support-nextcloud-owncloud-chunked-uploads/7423

#### What is your current rclone version (output from `rclone version`)?
rclone v1.49.5
- os/arch: linux/amd64
- go version: go1.13.1

#### What problem are you are trying to solve?
Uploads blocked by CloudFlare (capped at 100MB for the free plan) or maximum size file uploads.
Plus, allow resuming file uploads when the connection is dropped, or a failure happened.

#### How do you think rclone should be changed to solve that?
For Nextcloud, here is the procedure : https://docs.nextcloud.com/server/stable/developer_manual/client_apis/WebDAV/chunking.html
For OwnCloud, I couldn't find anything in the docs, but on the forum : https://central.owncloud.org/t/chunked-file-upload-with-curl/21712 (it seems pretty similar to what Nextcloud does). Also found that, which seems to be the latest version of chunked uploads on OwnCloud : https://dragotin.wordpress.com/2015/06/22/owncloud-chunking-ng/
For other generics WebDav providers, it's not in the specs, so... 🤷‍♂ 
From there, you can add chunked options like "--chunk-size" or "--chunk-number".

**Comment by ncw** [comment]
That doesn't look too hard...

What would be a sensible point to switch from single part uploads to chunked uploads?  Does that need to be configurable?

I finally managed to upgrade the integration tests to use the nextcloud/owncloud latest docker containers so we can have tests too!

Do you want to help work on this?

**Comment by Arno500** [comment]
According to the officiel Nextcloud documentation, default chunksize is at 5MiB (https://docs.nextcloud.com/desktop/2.5/advancedusage.html). I think this is a bit low for a high performance tool like rclone. Maybe 50MiB by default is good ?
The switch between single file uploads and chunked should probably be at the chunk size. That way, with the Cloudflare situation, you can easily predict the maximum file upload size allowed, control it, and manage it.

I'm not against working on it, but I have little to no experience in C/C++/Go whatsoever. Anyway, I have my Nextcloud instance ready to test and upload files of 90GB ;) (and the time to do it)

**Comment by maxstoyanov** [comment]
Without this feature syncing files larger than the configured threshold in the web server stack is not possible. So this is quite important.

**Comment by Jwink3101** [comment]
While it doesn't fix this issue, using the [chunker remote](https://rclone.org/chunker/) would, in practice, solve this, right?

**Comment by iMarv** [comment]
If I did not miss any configs, as far as I can see the chunker remote does not properly join the chunks to one file again (at least on the webdav remote)
Otherwise this works well
