### ISSUE TITLE
rcd: serve static files without authentication

### ISSUE THREAD

**Issue by Yexiaoxing** [rclone/rclone#3671]
In order to solve double authentication issues (e.g. https://github.com/rclone/rclone-webui-react/issues/40) in the rclone web interface, the static files shall be served without authentication.

Please also refer to the [forum discussion](https://forum.rclone.org/t/beta-testing-webgui-for-rclone/11156/107).

Basically, the rcserver should now wrap httplib; the wrapper first check if the request is to webgui, if yes then directly serve; if no then continue with the httplib.

#### What is your current rclone version (output from `rclone version`)?

v1.50.0

**Comment by ncw** [comment]
Sounds reasonable.  Do you want to work on this?

**Comment by Yexiaoxing** [comment]
I can try.

**Comment by negative0** [comment]
@Yexiaoxing , If you need anything from the gui side, I am here to help.

**Comment by negative0** [comment]
Hey @Yexiaoxing, any updates?

**Comment by Yexiaoxing** [comment]
> Hey @Yexiaoxing, any updates?

Surviving my final exams... Will work on it after :)

**Comment by ivandeex** [comment]
Closing after 2 years of inactivity

**Comment by sjtuross** [comment]
It seems the issue still exists. Same reported in the webui repo https://github.com/rclone/rclone-webui-react/issues/40
