### ISSUE TITLE
Implement an ioctl to get a file's hash

### ISSUE THREAD

**Issue by eatnumber1** [rclone/rclone#3673]
I'm building a tool to verify files against a database of known good hashes. The files are stored in cloud storage, so it would be useful if I could leverage the cloud backend's native method of getting a file's hash without having to download the entire file.

It seems like this could be solved in a useful way by implementing some new ioctls, e.g. `RCLONE_IOC_MD5`, `RCLONE_IOC_SHA1`, etc. that my application could call on a mounted filesystem.

Does that sound reasonable / feasible? I saw issue #3170 and bazil/fuse#93, but sadly Bazil is starting to seem like an abandoned project, with its last commit more than a year ago.

**Comment by ncw** [comment]
Unless bazil/fuse supports it then will be impossible!

The other thing you could do is run your rclone mount with `--rc` and use the [rclone API to read hashes:](https://rclone.org/rc/#operations/list).

**Comment by animosity22** [comment]
This looks to be answered. If you have any other questions, please ask on https://forums.rclone.org

Thanks!
