### ISSUE TITLE
"DropboxHash" is now just "Dropbox"

### ISSUE THREAD

**Issue by Jwink3101** [rclone/rclone#3679]
#### What is the problem you are having with rclone?

Not a problem per-se but there is a missing change in the changelog that should be noted:

The hash from Drobox used to be called `DropboxHash` and now returns as `Dropbox`. This is a better name but should have been noted in the changelog!

#### What is your rclone version (output from `rclone version`)

```
rclone v1.50.0
- os/arch: darwin/amd64
- go version: go1.13.3
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS Mojave 10.14.6, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Dropbox

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`lsjson`

**Comment by ncw** [comment]
Oops, sorry, that change was unintentional...

Shall I change it back or leave it as it is in your opinion?

**Comment by Jwink3101** [comment]
I also vote change it back and release a point update sooner rather than later.

**Comment by ncw** [comment]
OK, give this a go and I'll probably make a point release at the weekend.  I also discovered that CRC-32 got renamed too so I've fixed that.

Before the fix

```patch
$ diff -u <(rclone-v1.49.5 hashsum | sort) <(rclone hashsum | sort)
--- /dev/fd/63	2019-10-30 10:37:04.365301910 +0000
+++ /dev/fd/62	2019-10-30 10:37:04.369301946 +0000
@@ -1,5 +1,6 @@
-  * CRC-32
-  * DropboxHash
+  * CRC32
+  * Dropbox
+  * MailruHash
   * MD5
   * QuickXorHash
   * SHA-1

```

After the fix

```patch
$ diff -u <(rclone-v1.49.5 hashsum | sort) <(rclone hashsum | sort)
--- /dev/fd/63	2019-10-30 10:36:25.852916602 +0000
+++ /dev/fd/62	2019-10-30 10:36:25.856916646 +0000
@@ -1,5 +1,6 @@
   * CRC-32
   * DropboxHash
+  * MailruHash
   * MD5
   * QuickXorHash
   * SHA-1
```

https://beta.rclone.org/branch/v1.50.0-010-g681db7e4-fix-3679-dropbox-hash-beta/ (uploaded in 15-30 mins)
