### ISSUE TITLE
Failed to save config after 10 tries: Failed to create temp file for new config: open <cfgfile>: read-only file system

### ISSUE THREAD

**Issue by colemickens** [rclone/rclone#3685]
I run my systems via NixOS. Thus, I can say confidently I'm running nearly identical setups across my various machines. I have one machine where I upgraded rclone to the latest release and encountered a unique issue:

```
Oct 29 03:27:10 xeep rclone[27085]: Failed to save config after 10 tries: Failed to create temp file for new config: open /nix/store/jyagkp99jxqpss0h001dsjfsldghqrlx-mixin-loremipsum-media-rclone.conf442753884: read-only file system
```

This seems to be new to the most recent release. I just rolled back the commit that bumped rclone and now the service works.

Why is rclone trying to update this file? Nothing in the file could be considered mutable. Due to how NixOS works, this file must be read-only.

**Comment by ehmry** [comment]
Looks like this is a temporary file that should be created somewhere like `/tmp`, but is instead created at whatever `$out` was set to at build time.

**Comment by ncw** [comment]
> Why is rclone trying to update this file? Nothing in the file could be considered mutable. Due to how NixOS works, this file must be read-only.

What backends are you using?  If you are using the sftp backend then you'll need to set the md5sum command and sha1sum command explicitly: https://rclone.org/sftp/#sftp-md5sum-command

**Comment by ncw** [comment]
In general rclone writes config to its config file, it stores tokens from google drive there etc.  There is an issue about making the config file read only here: https://github.com/rclone/rclone/issues/3655

**Comment by colemickens** [comment]
I guess we can close this in favor of #3655, but I'd even just take forgoing saving the token, especially given that my drive configuration uses a service account json file that can always just retrieve a fresh token on start, etc. 

I'll have to write some sort of wrapper for `rclone` for use in nixpkgs unless #3655 is resolved. Something that can move the file to a temporary or proper state-dir location and direct rclone to use it instead of the read-only config file in the Nix store.

**Comment by ncw** [comment]
As you are using drive, rclone is saving the ID of the root directory to the config (which is new in 1.50) which it will do once. So if you update your config once then rclone won't bother it again.

**Comment by colemickens** [comment]
@ncw, perfect, it's documented too, thanks for pointer and the great software!

**Comment by colemickens** [comment]
So... do I need to add the root folder id AND remove the path prefix from the target?

For example, I had "googdrv:media" before, but now that I've added the folder_id of "media" to my config file, I have a NESTED media directory instead of what I expected.

Should I have chosen a level-up for the root_dir, or removed the path prefix now that the root dir is done via ID ?

**Comment by colemickens** [comment]
I see, it looks like either option is valid, potentially. Thanks.

**Comment by ncw** [comment]
Yes you can do either.  Rclone will save the ID of the base folder if you don't specify it.
