### ISSUE TITLE
Problems with authorize in 1.50

### ISSUE THREAD

**Issue by x0b** [rclone/rclone#3686]
## What is the problem you are having with rclone?
Rclone 1.50.0 introduced a mitigation to #3573, requiring a new ```state``` parameter for rclone config, rclone config create and rclone authorize. 

This breaks third party integrations like rcloneExplorer which used to redirect users to ```http://127.0.0.1:53682/auth```. Unfortunately, this change also wasn't documented in the change log.

Could you add a flag to allow the user to supply an authentication token or the whole auth url?

#### What is your rclone version (output from `rclone version`)
```
rclone v1.50.0
- os/arch: windows/amd64
- go version: go1.12.7
```
(built from source)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
any

####  Which cloud storage system are you using? (eg Google Drive)
drive (any with oauth)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```rclone -vv config create test-2 drive scope drive```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2019/10/29 14:51:03 DEBUG : rclone: Version "v1.50.0" starting with parameters ["rclone" "-vv" "config" "create" "test-2" "drive" "scope" "drive"]
2019/10/29 14:51:03 DEBUG : Using config file from "###\\.config\\rclone\\rclone.conf"
Remote config
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
Auto confirm is set: answering Yes, override by setting config parameter config_is_local=false
2019/10/29 14:51:03 DEBUG : Starting auth server on 127.0.0.1:53682
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth?state=hg4yWMKdr5JnKAxHHxWvzw
Log in and authorize rclone for access
Waiting for code...

```

**Comment by ncw** [comment]
> This breaks third party integrations like rcloneExplorer which used to redirect users to `http://127.0.0.1:53682/auth`. Unfortunately, this change also wasn't documented in the change log.

Sorry about that!  I don't think this was ever a documented way of doing this.

Can we think of a better way of doing it?

Maybe we could write the URL to go to in a more machine readable state than this, then you could read it from the output?

    If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth?state=hg4yWMKdr5JnKAxHHxWvzw

How does your flow go at the moment?

Why doesn't the browser open automatically anyway?

**Comment by ncw** [comment]
Yes #3455 would be the best idea!

> 2\. run `rclone config create` with those details and wait for the process to exit

So you could potentially parse the output of rclone here for the URL?

> **EDIT:** So rclone uses xdg-open (https://github.com/skratchdot/open-golang/blob/master/open/exec.go#L13) which termux has symlinked to their own binary (https://wiki.termux.com/wiki/Sharing_Data).

I wonder if there is an android way of opening the browser? We could contribute that to https://github.com/skratchdot/open-golang

**Comment by x0b** [comment]
> I wonder if there is an android way of opening the browser? We could contribute that to https://github.com/skratchdot/open-golang

This should be possible and I already tried that, but my change does not seem to land in the compiled binary. I've never programmed in Go before, so thats not really surprising :(.

The code itself is quite trivial:
```go
func open(input string) *exec.Cmd {
	switch runtime.GOOS {
		case "android":
			return exec.Command("am", "start", "-a", "android.intent.action.VIEW", "-d", input)
		default:
			return exec.Command("xdg-open", input)
	}
	
}
```

**Comment by ncw** [comment]
> This should be possible and I already tried that, but my change does not seem to land in the compiled binary.

Are you editing the code under `vendor`?  If so then `export GO111MODULE=off` otherwise it won't be used.

Alternatively install [gohack](https://github.com/rogpeppe/gohack) and edit the module code.

**Comment by x0b** [comment]
Thanks for the tip.

I got it to run, but the direct route with opening the browser from golang won't work due to the android permission model. I'm going to try to to exactly the same as termux, which is shipping a script that captures xdg-open and sends the url back to the containing java application.

Since there is nothing that rclone can do here, I'd close this issue.

**Comment by ncw** [comment]
> I've switched to parsing rclone output since the other route requires shipping a lot more components due to exec() restrictions on Android 10+.

Sounds like a reasonable plan and sorry about the breakage!
