### ISSUE TITLE
OSX Catalina: “rclone” cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by motin** [rclone/rclone#3689]
#### What is the problem you are having with rclone?

Max OSX Catalina refuses to run rclone. 

<img width="417" alt="rclone" src="https://user-images.githubusercontent.com/793037/67860238-fee08700-fb25-11e9-8f71-9d2fe6622572.png">

(Are the released binaries notarized?)

#### What is your rclone version (output from `rclone version`)

Tried v1.49.5, v1.50.0 and the latest beta. (64 bit)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

OSX Catalina, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

n/a

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Not possible.

**Comment by motin** [comment]
The workaround is to attempt to run rclone as per above, and then go to System Preferences -> Security & Privacy and press "Allow Anyway":

<img width="667" alt="Banners_and_Alerts_and_Security___Privacy_and_Calc_etc__34_tabs__macOS_Catalina_error__“terraform”_cannot_be_opened_because_the_developer_cannot_be_verified__·_Issue__23033_·_hashicorp_terraform" src="https://user-images.githubusercontent.com/793037/67860507-aeb5f480-fb26-11e9-9204-937d2b8dfb08.png">

Next time you run rclone, you'll get:

<img width="455" alt="rclone" src="https://user-images.githubusercontent.com/793037/67860561-d311d100-fb26-11e9-9a23-0ab0dd393502.png">

Pressing "Open" will store the exception for you locally so that rclone once again can be used on your system.

The real fix is to sign and notarize the OSX binary releases.

**Comment by ncw** [comment]
Is there a command line way of doing the notarization?

I build the rclone releases using GitHub Actions.  I don't have a mac so unless I can do it from within GitHub actions we are out of luck!

Any help much appreciated!

**Comment by CrossR** [comment]
>Is there a command line way of doing the notarization?

There is guide on that over here: https://twocanoes.com/adding-notarization-to-xcode-builds/ which we used to setup a notarize script: https://github.com/onivim/oni2/blob/master/scripts/osx/notarize.sh

**Comment by ncw** [comment]
Thanks for that @CrossR very helpful. Getting an Apple developer ID looks like the next hurdle...

**Comment by terorie** [comment]
@ncw Please don't let Apple bully you into buying their developer license :)
I'm on 10.15.1 with rclone installed via Homebrew and don't have this problem. I didn't change any settings either. I usually only get the "developer didn't pay us $99" warning when opening `.app` bundles.
Maybe a maintainer or trusted contributor is willing to sign rclone builds for Mac?

**Comment by darthShadow** [comment]
Homebrew builds the binary on the system instead of downloading a pre-built binary, which is the reason no warning is thrown. Currently, binaries built on own systems are trusted by default.

Perhaps, we could do a fundraiser instead for buying the license? If sufficient people are interested, it should be easy enough to get the funds required without needing to spend out of pocket.

**Comment by Yexiaoxing** [comment]
Please be noted that Homebrew actually builds from source code as a bundle (called bottles) in their build farm, and end-users install the bottle instead of building from source.

**Comment by ncw** [comment]
I saw this potential work-around ([which I read about in a terraform issue](https://github.com/hashicorp/terraform/issues/23033))

    xattr -d com.apple.quarantine /path/to/rclone/binary

Does that work?

Apparently the `com.apple.quarantine` is set by the browser? Which makes me wonder if downloading the binary with curl/wget would have the same problem.

**Comment by marco-m** [comment]
I can confirm that using `brew install rclone` gives a perfectly working rclone on Catalina (no warnings no popups). Given that brew is quite popular with macOS users, I think that suggesting to use brew to get rclone is an acceptable solution.

_If_ you are considering signing and notarizing rclone, then I suggest to have a look at https://github.com/mitchellh/gon, of HashiCorp fame, which can be integrated in CI.

No matter how you download the binary (browser or curl), the same problem will happen, since the binary will lack a signature.

**Comment by ncw** [comment]
`gon` looks like a nice tool but reasonably complicated!  Not sure how I'd work around this trying to run it on GitHub Actions (I don't have a mac)

> I do not currently know how to script the approvals, so the recommendation on build machines is to run gon manually once. If anyone finds a way to automate this please open an issue, let me know, and I'll update this README.

`brew install rclone` is a good alternative certainly.

**Comment by marco-m** [comment]
> `gon` looks like a nice tool but reasonably complicated! Not sure how I'd work around this trying to run it on GitHub Actions (I don't have a mac)

Ah, very good point, I didn't consider you didn't have a mac for CI.

**Comment by Yexiaoxing** [comment]
`gon` seems to be great - except that it still requires a valid Developer ID cert, which costs some money ($99/year).

**Comment by Zirro** [comment]
I'd expect that most CLI-users on macOS are using a package manager like Homebrew already, with others presumably becoming aware of the `xattr -d com.apple.quarantine`-workaround rather quickly. Recommending `brew install rclone` should be okay as a solution.

That said, if @ncw still wants to submit `rclone` for notarization I wouldn't mind donating the $99 for this project to obtain a Developer ID. I appreciate that this project is well-managed with frequent commits, and it doesn't sit right with me that you should pay for a platform that you're not even using yourself.

While I doubt that Apple rolled this program out with the intent of squeezing money out of developers (it's not as if the $99 fee has any significant impact on their revenue), they've certainly rushed the implementation of it and likely underestimate the number of cross-platform developers without Macs which it affects.

**Comment by ncw** [comment]
@Zirro thank you for your kind offer. I think I won't do the notarizing for the moment - I'd like to let the situation settle down at bit.

I think what we should do now put a note into the [install doc](https://github.com/rclone/rclone/blob/master/docs/content/install.md#macos-installation-from-precompiled-binary) to the effect that macOS Catalina can't run rclone binaries by default and specify the `xattr` workaround provided it works OK.  Maybe another section on `brew install rclone`. I don't know who packages rclone for brew so I'm a bit nervous recommending it there, but it seems bang up to date.

Would one of you kind macOS users like to send a PR updating the docs to that effect?

I can then push that to the website as part of a patch release.

Perhaps adding the `xattr` fix to [install.sh](https://github.com/rclone/rclone/blob/master/docs/content/install.sh) would be OK too?

Can a macOS Catalina user test the `xattr -d com.apple.quarantine` fix to see if it actually works - from my reading I'm not sure it does.

Thanks

**Comment by marco-m** [comment]
@ncw I will take a stab at this.

**Comment by ncw** [comment]
Thank you @marco-m for your docs update.

I think the summary on the pull request is worth repeating here for interested parties

1. install.sh works out of the box.
2. brew install rclone works out of the box.
3. if downloading with a web browser, the xattr workaround works.

I'm happy with the workarounds so I don't think I will jump through the hoops of fire to become a macOS registered developer just yet :-)
