### ISSUE TITLE
allow specification of config password dynamically

### ISSUE THREAD

**Issue by permezel** [rclone/rclone#3694]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.50.0
- os/arch: darwin/amd64
- go version: go1.13.3

#### What problem are you are trying to solve?
I want to secure my config with a password, but I never wish to either know the password, nor imbed it in a script, nor pass it in an environment variable.

#### How do you think rclone should be changed to solve that?
There is a discussion in the Borg backup docs regarding the desirability for this feature, and for a model for implementing such.
See, for example: [here](https://borgbackup.readthedocs.io/en/stable/faq.html?highlight=borg_passcommand).  Look for the BORG_PASSCOMMAND info.

**Comment by ncw** [comment]
I propose to add a flag

          --password-command string   command to retrieve the password

The command would output the password on standard output.

Would you like to work on this @permezel ?

**Comment by permezel** [comment]
Sure.  I'll give it a whirl.

**Comment by permezel** [comment]
I have it coded.
I am not sure what sort of test(s) to create and where to put it.
The testing is simple.
I either specify --password-command or RCLONE_CONFIG_PASS_COMMAND.

When config is encrypted, it is a matter or testing some of the failure cases for the command.
Command  not found, bad exit codes, incorrect password, etc, to verify the error message I provide.
I suppose I should try it with "sleep 100000" and then possibly realise I need a timeout.  Same for "cat /dev/urandom" or something, but there is the tried and true principle of always providing the user sufficient rope to hang themselves.

Someone might want to use the supplied password mechanism to set the config password.  I don't feel that is really necessary.

Cheers.

**Comment by ncw** [comment]
> I have it coded.

Great!

> I am not sure what sort of test(s) to create and where to put it. 

Tests should go in here: https://github.com/rclone/rclone/blob/master/fs/config/config_test.go

I suggest you make a separate function for reading the password so can unit test it.

I would probably write a very small go program for testing with build constraint none and then use "go run" to execute it.  I did this in the auth proxy tests

https://github.com/rclone/rclone/blob/0eaf5475efd67e34aac902a6ca9983221c05ef31/cmd/serve/proxy/proxy_test.go#L15

With this [simple test program](https://github.com/rclone/rclone/blob/master/cmd/serve/proxy/proxy_code.go) - note the build tags at the top which ensures it doesn't get built as part of the normal build.

https://github.com/rclone/rclone/blob/0eaf5475efd67e34aac902a6ca9983221c05ef31/cmd/serve/proxy/proxy_code.go#L1

You can then add command line arguments for what you want the test binary to do.

Doing it like this rather than using bash scripts etc will make it cross platform.

**Comment by permezel** [comment]
Hi Nick.

Got some errors I don't understand from Git:

lust% git commit -a 
[password-command-feature 5ffad46f8] allow specification of config password dynamically - fixes #3694
 6 files changed, 150 insertions(+), 13 deletions(-)
lust% git status
On branch password-command-feature
nothing to commit, working tree clean
lust% git rebase master
Current branch password-command-feature is up to date.
lust% git push origin  password-command-feature
Warning: Permanently added the RSA host key for IP address '52.64.108.95' to the list of known hosts.
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I think I followed all the instructions.

lust% git log
commit 5ffad46f83ffa2a21e6e8eb067ec859cf9721bbc (HEAD -> password-command-feature)
Author: Damon Permezel <permezel@me.com>
Date:   Mon Nov 18 19:55:27 2019 +1000

    allow specification of config password dynamically - fixes #3694

commit 0eaf5475efd67e34aac902a6ca9983221c05ef31 (upstream/master, upstream/HEAD, master)
Author: Nick Craig-Wood <nick@craig-wood.com>
Date:   Sat Nov 2 15:24:58 2019 +0000

    Start v1.50.1-DEV development


lust% ssh -T git@github.com
Warning: Permanently added the RSA host key for IP address '13.236.229.21' to the list of known hosts.
Hi permezel! You've successfully authenticated, but GitHub does not provide shell access.

**Comment by permezel** [comment]
I figured it out.
I must have skipped the initial fork step.  But then, how did I manage to get as far as I did?

I'll have to make my changes again.

**Comment by ncw** [comment]
> I'll have to make my changes again.

Just fork the repo on github with the web interface then add another remote using `git remote` and push to that instead of `origin`.

So you end up with something like this

```
$ git remote -v
ncw	git@github.com:ncw/go-isatty.git (fetch)
ncw	git@github.com:ncw/go-isatty.git (push)
origin	https://github.com/mattn/go-isatty (fetch)
origin	https://github.com/mattn/go-isatty (push)
```

and you then push to `ncw` rather than `origin`.
