### ISSUE TITLE
Configurable matching criteria for --track-renames

### ISSUE THREAD

**Issue by MistarMuffin** [rclone/rclone#3696]
Hello,

In cases of many new or renamed files, --track-renames can be very slow due to it's need to checksum all of these unknown items from a local disk. In my use case it would be acceptable to forgo checksums and limit the rename matching to mod-time and file size. This has been discussed on the forum and an extra flag such as --track-renames-strategy has been proposed.

Please see the discussion here:
https://forum.rclone.org/t/can-not-use-track-renames-when-syncing-to-and-from-crypt-remotes/11063/8

Thanks.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

**Comment by MistarMuffin** [comment]
Thanks, this is a such a huge improvement! I do think I found a bug, though. In my testing, the modtime strategy successfully renamed all of my remote files except for one. I edited the case of local file but otherwise left it's filename the same. rclone performed a full re-upload of this file. When I switched back to a hashed strategy it was able to rename the file on the remote.

Example:
old filename: some.media.file.1080p.h264.mkv
new filename: Some.Media.File.1080p.H264.mkv

**Comment by MistarMuffin** [comment]
I think you're right. The timestamp looked the same but I did not investigate down to 1ms of accuracy. I ran the normal track-renames afterwards and it synced everything up so I cannot check now. Instead I changed the case on another file and it worked as intended. False alarm. One last question, even though the rename strategy is called "modtime" I assume that it still also takes the filesize into account, right? modtime on its own would not be enough to reliably match files in most cases.

**Comment by ncw** [comment]
> One last question, even though the rename strategy is called "modtime" I assume that it still also takes the filesize into account, right? modtime on its own would not be enough to reliably match files in most cases.

Yes that is correct (it is in the docs which aren't live yet!)

Note that I found a bug in the modtime strategy so I suggest you try [the latest beta](https://beta.rclone.org)
