### ISSUE TITLE
UNATUTHORIZED CLIENT ERROR

### ISSUE THREAD

**Issue by vaccarieli** [rclone/rclone#3698]
Hi am getting this error, I have configured everything as allways, and get this error:

2019/11/04 14:12:49 Failed to copy with 2 errors: last error was: couldn't list directo
ry: Get https://www.googleapis.com/drive/v3/files?alt=json&fields=files%28id%2Cname%2Cs
ize%2Cmd5Checksum%2Ctrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebView
Link%29%2CnextPageToken&includeItemsFromAllDrives=true&pageSize=1000&prettyPrint=false&
q=trashed%3Dfalse+and+%28%27root%27+in+parents%29+and+%28name%3D%27Google+Fotos%27%29+a
nd+mimeType%3D%27application%2Fvnd.google-apps.folder%27&supportsAllDrives=true: oauth2
: cannot fetch token: 401 Unauthorized                                                 
Response: {                                                                            
  "error": "unauthorized_client",                                                      
  "error_description": "Unauthorized"### 

Am using a regular account, my personal one, and I have set it up with my bussiness client id. As far as i know and of course have tried to create a client id using my regular one, but wont allow me, so that is why am using this.

**Comment by ncw** [comment]
It looks like the `client_id` you specified is invalid.  What happens if you try without setting `client_id`?

**Comment by animosity22** [comment]
This looks to be a question. If you still require assistance, please ask on the forums. Thanks!
