### ISSUE TITLE
please make a gui like expandrive.

### ISSUE THREAD

**Issue by nazar2sfive** [rclone/rclone#3700]
rclone is so great but i wish sincerely for a gui like expandrive.
https://www.expandrive.com/
![image](https://user-images.githubusercontent.com/12841320/68360076-b12bd600-0146-11ea-9937-6be5404a3a50.png)

**Comment by darthShadow** [comment]
Have you checked out [Rclone Browser](https://github.com/kapitainsky/RcloneBrowser/) & the [Rclone WebUI](https://github.com/rclone/rclone-webui-react) ?

**Comment by nazar2sfive** [comment]
both Rclone browser and Rclone WebUI is not as modular as expandrive. i wish these both were tweaked to match expandrive like gui both looks and function.

**Comment by nazar2sfive** [comment]
can i make my files to be stored locally at the same location where google drive has stored files via windows.

so i can work back and forth during my dual boot in d:\googledrive\ and \mnt\ddrive\googledrive

i want to sync the same location from both linux and windows for my dual boot

**Comment by Yexiaoxing** [comment]
I personally believe that this would require lots of work... Maybe some external developer can help, as rclone can focus on the cli part?

**Comment by ivandeex** [comment]
> both Rclone browser and Rclone WebUI is not as modular as expandrive. i wish these both were tweaked to match expandrive like gui both looks and function.

This project is about scriptable rclone cli. The ticket should be submitted to the relevant gui projects.
