### ISSUE TITLE
Entry doesn't belong in directory.. errors with Goobox (S3 API)

### ISSUE THREAD

**Issue by buxm** [rclone/rclone#3704]
#### What is the problem you are having with rclone?
I configured a Goobox remote (https://s3.goobox.io/). Goobox provides an S3 compatible API.
I tried to mount it as a Windows drive and browse it. I cannot see my directories under bdsbackuptest/BuxDiskStationTestBackup.hbk, where bdsbackuptest is the bucket name and BuxDiskStationTestBackup.hbk is the name of a directory in it.
The directory structure is:
```
bdsbackuptest
|-BuxDiskStationTestBackup.hbk
  |-Config
  |-Control
  |-Guard
  |-Pool
```

but none of the directories under BuxDiskStationTestBackup.hbk show up.
I have also tried to browse the remote using the web gui browser and obtained the same result.
In both cases, when I enter BuxDiskStationTestBackup.hbk, the rclone server shows:

```
2019/11/07 23:17:07 ERROR : bdsbackuptest/Config: Entry doesn't belong in directory "bdsbackuptest/BuxDiskStationTestBackup.hbk" (too short) - ignoring
2019/11/07 23:17:07 ERROR : bdsbackuptest/Control: Entry doesn't belong in directory "bdsbackuptest/BuxDiskStationTestBackup.hbk" (too short) - ignoring
2019/11/07 23:17:07 ERROR : bdsbackuptest/Guard: Entry doesn't belong in directory "bdsbackuptest/BuxDiskStationTestBackup.hbk" (too short) - ignoring
2019/11/07 23:17:07 ERROR : bdsbackuptest/Pool: Entry doesn't belong in directory "bdsbackuptest/BuxDiskStationTestBackup.hbk" (too short) - ignoring
2019/11/07 23:17:14 NOTICE: bdsbackuptest/BuxDiskStationTestBackup.hbk/SynologyHyperBackup.bkpi: Failed to read last modified from HEAD: <nil>
```

SynologyHyperBackup.bkpi is a 0 byte file under BuxDiskStationTestBackup.hbk

I tried to connect to my Goobox account and mount it as a drive using Mountain Duck and I can navigate all subdirectories correctly.

#### What is your rclone version (output from `rclone version`)

rclone v1.50.1
- os/arch: windows/amd64
- go version: go1.13.4

also:
rclone v1.50.1-019-g049ff1f2-beta
- os/arch: windows/amd64
- go version: go1.13.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 8 64bit

####  Which cloud storage system are you using? (eg Google Drive)
GooBox S3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount Goobox: z: --vfs-cache-mode full

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

[errlog.txt](https://github.com/rclone/rclone/files/3822008/errlog.txt)

**Comment by ncw** [comment]
This looks like it might be slightly incompatible with S3...

>  bdsbackuptest/Pool: Entry doesn't belong in directory "bdsbackuptest/BuxDiskStationTestBackup.hbk

What that means is that rclone was listing the directory `bdsbackuptest/BuxDiskStationTestBackup.hbk` and it was expecting all keys in that directory to have the name `bdsbackuptest/BuxDiskStationTestBackup.hbk/something` however it got a key `bdsbackuptest/Pool` which didn't start with that prefix so it ignored it.

So I think this might be a bug in GooBox

What happens if you do

    rclone lsf -R remote:bdsbackuptest

and

    rclone lsf -R --disable ListR remote:bdsbackuptest

If either of those shows the problem then please add `-vv --dump bodies` and post the result - thanks.

(Substitute `remote:` for whatever you are using).

**Comment by buxm** [comment]
Many thanks for getting back to me.

> What happens if you do
> 
> ```
> rclone lsf -R remote:bdsbackuptest
> ```

This is what I get on STDERR:
`2019/11/12 20:49:06 NOTICE: BuxDiskStationTestBackup.hbk/Control/@writer/v1.8.-1.0.0.none.none.cinfo: Failed to read last modified from HEAD: <nil>`
`2019/11/12 20:50:02 NOTICE: BuxDiskStationTestBackup.hbk/SynologyHyperBackup.bkpi: Failed to read last modified from HEAD: <nil>
`
Those files are 0 byte in size.

Please find attached the STDERR output with `-vv --dump bodies`.
[lsf -R err.txt](https://github.com/rclone/rclone/files/3838002/lsf.-R.err.txt)

> 
> and
> 
> ```
> rclone lsf -R --disable ListR remote:bdsbackuptest
> ```

This is what I get on STDOUT:

`BuxDiskStationTestBackup.hbk/
BuxDiskStationTestBackup.hbk/SynologyHyperBackup.bkpi
BuxDiskStationTestBackup.hbk/_Syno_TaskConfig
BuxDiskStationTestBackup.hbk/storage_statistics.db.8
BuxDiskStationTestBackup.hbk/synobkpinfo.db`

obviously subfolders are missing.

This is what I get on STDERR:

`2019/11/12 20:54:13 ERROR : Config: Entry doesn't belong in directory "BuxDiskStationTestBackup.hbk" (too short) - ignoring`
`2019/11/12 20:54:13 ERROR : Control: Entry doesn't belong in directory "BuxDiskStationTestBackup.hbk" (too short) - ignoring`
`2019/11/12 20:54:13 ERROR : Guard: Entry doesn't belong in directory "BuxDiskStationTestBackup.hbk" (too short) - ignoring`
`2019/11/12 20:54:13 ERROR : Pool: Entry doesn't belong in directory "BuxDiskStationTestBackup.hbk" (too short) - ignoring`
`2019/11/12 20:54:13 NOTICE: BuxDiskStationTestBackup.hbk/SynologyHyperBackup.bkpi: Failed to read last modified from HEAD: <nil>`

Please find attached the STDERR output with `-vv --dump bodies`.
[lsf -R --disable ListR err.txt](https://github.com/rclone/rclone/files/3838017/lsf.-R.--disable.ListR.err.txt)
Please note that in both attachments I edited the content of the <DisplayName> XML nodes which contained the email address I used to register on Goobox, replacing it with 'MYEMAILADDRESS'.

**Comment by ncw** [comment]
This is the reason the listings don't work

Rclone sends this request

```
2019/11/12 21:07:40 DEBUG : GET /bdsbackuptest?delimiter=%2F&max-keys=1000&prefix=BuxDiskStationTestBackup.hbk%2F HTTP/1.1
Host: sias3.goobox.io
User-Agent: rclone/v1.50.1-019-g049ff1f2-beta
Authorization: XXXX
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20191112T200740Z
Accept-Encoding: gzip
```

And gets this response

```
2019/11/12 21:00:03 DEBUG : HTTP RESPONSE (req 0xc000446400)
2019/11/12 21:00:04 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since, Cache-Control,Content-Type,Authorization, X-Amz-Content-Sha256,X-Amz-Date,X-Amz-User-Agent,X-AMZ-ACL
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, HEAD, OPTIONS
Access-Control-Allow-Origin: *
Cache-Control: max-age=60
Cache-Control: private
Connection: keep-alive
Content-Type: application/xml
Date: Tue, 12 Nov 2019 19:59:57 GMT
Expires: Tue, 12 Nov 2019 20:00:57 GMT
Server: Goobox-SiaS3/v0.11.1
Strict-Transport-Security: max-age=15724800; includeSubDomains
Vary: Accept-Encoding
X-Amz-Id-2: $(HOSTNAME)
X-Amz-Request-Id: ebd7be43ef8a799e11ab5813effb6947510ed3d8

1712a
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01"><Name>bdsbackuptest</Name>[snip]
```

Prettifying the XML we get

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01">
  <Name>bdsbackuptest</Name>
  <Prefix>
  </Prefix>
  <KeyCount>4</KeyCount>
  <MaxKeys>1000</MaxKeys>
  <IsTruncated>false</IsTruncated>
  <Contents>
    <Owner>
      <ID>eu-central-1:ee9570f2-ba68-470d-85bb-fecb46aca2ea</ID>
      <DisplayName>MYEMAILADDRESS</DisplayName>
    </Owner>
    <Key>BuxDiskStationTestBackup.hbk/SynologyHyperBackup.bkpi</Key>
    <Size>0</Size>
    <LastModified>2019-11-06T22:15:49.921Z</LastModified>
    <ETag>&#34;d41d8cd98f00b204e9800998ecf8427e&#34;</ETag>
    <StorageClass>STANDARD</StorageClass>
  </Contents>
[snip]
  <Contents>
    <Owner>
      <ID>eu-central-1:ee9570f2-ba68-470d-85bb-fecb46aca2ea</ID>
      <DisplayName>MYEMAILADDRESS</DisplayName>
    </Owner>
    <Key>BuxDiskStationTestBackup.hbk/synobkpinfo.db</Key>
    <Size>3072</Size>
    <LastModified>2019-11-06T22:14:57.954Z</LastModified>
    <ETag>&#34;9ef5a6d419c54c74735ecc17da329c04&#34;</ETag>
    <StorageClass>STANDARD</StorageClass>
  </Contents>
  <Delimiter>/</Delimiter>
  <CommonPrefixes>
    <Prefix>Control/</Prefix>
  </CommonPrefixes>
  <CommonPrefixes>
    <Prefix>Guard/</Prefix>
  </CommonPrefixes>
  <CommonPrefixes>
    <Prefix>Pool/</Prefix>
  </CommonPrefixes>
  <CommonPrefixes>
    <Prefix>Config/</Prefix>
  </CommonPrefixes>
</ListBucketResult>
```

The problem is the `<CommonPrefixes>` these should be the complete path so `<Prefix>Control/</Prefix>` should be `<Prefix>BuxDiskStationTestBackup.hbk/Control/</Prefix>`.

This is a bug which should be reported to Goobox I think.

If you want to email support and point them at this issue, I'm happy to answer questions, or give them my email address nick@craig-wood.com

----

In the mean time

> This is what I get on STDERR:
> `2019/11/12 20:49:06 NOTICE: BuxDiskStationTestBackup.hbk/Control/@writer/v1.8.-1.0.0.none.none.cinfo: Failed to read last modified from HEAD: <nil>`
> `2019/11/12 20:50:02 NOTICE: BuxDiskStationTestBackup.hbk/SynologyHyperBackup.bkpi: Failed to read last modified from HEAD: <nil> `
> Those files are 0 byte in size.

I would say those errors are harmless and can be ignored.

So it looked like the first command worked OK.  This means that you can use `--fast-list`  in sync/copy/move and it should work.

Unfortunately `rclone mount` can't use `--fast-list` so this won't fix the problem with rclone mount.

**Comment by buxm** [comment]
Hi @ncw 
many thanks for the thorough analysis and reply!
I will try to report this to the guys at Goobox and point them to this thread.

Cheers!

**Comment by buxm** [comment]
The guys @ s3.goobox.io managed to fix this issue. Now I can explore subdirs on my Goobox storage account after mounting this as a Windows drive using rclone mount.
Many thanks for helping out @ncw!

**Comment by ncw** [comment]
Glad it is fixed :-)
