### ISSUE TITLE
Encrypted Chunker = filename too long

### ISSUE THREAD

**Issue by lawmanuk** [rclone/rclone#3705]
https://forum.rclone.org/t/filename-too-long/12753/32

Above post explains problem that using crypted chunker on filenames creates filenames that are too long resulting in error.

Eg.   127 char filename becomes 282 char via crypted chunker.

This seems to be due to temporary filenames used during the chunking process.

At present not feasible to use chunker + crypt together until chunker issues resolved.

thanks

**Comment by ncw** [comment]
@ivandeex I think you saw this in the forum....

**Comment by ivandeex** [comment]
I will prepare a PR to reduce temporary chunk filename overhead from 16 to 7 characters.
@ncw I can also change default base name format from "*.rclone_chunk.###" to eg. "*.rclone###" or "*.chunk###" thus additionally reducing base filename overhead from 17 characters to 9-10 (ie total base+temp overhead from 33 to 16-17 by default), but this will require current users of rclone v1.50 to migrate or modify configuration, so I need your sign-off.

**Comment by ncw** [comment]
> I will prepare a PR to reduce temporary chunk filename overhead from 16 to 7 characters.

That sounds great :-)

> @ncw I can also change default base name format from "_.rclone_chunk.###" to eg. "_.rclone###" or "*.chunk###" thus additionally reducing base filename overhead from 17 characters to 9-10 (ie total base+temp overhead from 33 to 16-17 by default), but this will require current users of rclone v1.50 to migrate or modify configuration, so I need your sign-off.

I'm not that keen on breaking backwards compatibility...
- this is configurable already
- the less unique we make the suffix the more chance we get a collision.  so `.###` would be the shortest but quite likely to have a collision.

What do you think?

**Comment by ivandeex** [comment]
Aye

**Comment by ivandeex** [comment]
Fixed by https://github.com/rclone/rclone/pull/3789

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.51

Thanks @ivandeex
