### ISSUE TITLE
Rework Config System

### ISSUE THREAD

**Issue by fionera** [rclone/rclone#3706]
#### What problem are you are trying to solve?
Currently rclone uses `goconfig` to load a ini file. The implementation behind it does not allow the use of more complicated data structures, like array and maps. Currently rclone circumvents this with "CommaSepList" and "SpaceSepList". I started this because I have already changed to yaml files in my fork, to be able to use a map[string][]string structure.

#### How do you think rclone should be changed to solve that?
This is a Thread to discuss a good interface for Config and the implementation of it.

My first Suggestion would be smth like this:
```golang

// ProviderDefinition defines the supported FileTypes (the extension)
// that the Provider can handle. It will be created by calling the `NewFunc`.
// The `NewFunc` should not do any loading.
// The definitions would be registered on init, which allows endless modifications
type ProviderDefinition struct {
	NewFunc   func() Provider
	FileTypes []string
}

// The basic interface a config Provider has to implement
// String returns the raw Config
// Load reads the already decrypted config file content
// Save writes the unencrypted config file content
// GetRemoveConfig returns an implementation of the RemoteConfig interface
type Provider interface {
	String() string
	Load(io.Reader) error
	Save(io.Writer) error
	GetRemoteConfig() RemoteConfig
}

// GlobalConfigProvider is an extension for a config Provider
type GlobalConfigProvider interface {
	GetGlobalConfig() GlobalConfig
}

// GlobalConfig is an interface to allow the set of global settings like `bwlimit`
// It has to support loading and saving of string values by default
type GlobalConfig interface {
	StringSupporter
}

// RemoteConfig is an interface to use the config of the remotes
// GetRemotes returns a slice with all the remote names
// HasRemotes returns if the given remote exists in the config
// GetRemote returns the config section of the named remote or nil if it does not exist
// CreateRemote creates a remote and returns the section for it
// DeleteRemote deletes a remote
// RenameRemote renames a remote
// CopyRemote copies the config of the given remote to a clone with the given name
type RemoteConfig interface {
	GetRemotes() []string
	HasRemote(remote string) bool
	GetRemote(remote string) Section
	CreateRemote(remote string) Section
	DeleteRemote(name string)
	RenameRemote(oldName string, newName string)
	CopyRemote(source string, destination string)
}

// Section is the config of a single remote
// GetKeys returns all set options
// GetConfig returns the raw config
// Remove deletes the config option with the given name
// It has to support loading and saving of string values by default
type Section interface {
	GetKeys() []string
	GetConfig() map[string]interface{}
	Remove(name string)

	StringSupporter // A config backend has to be at least support strings
}

// InterfaceSupporter allows the loading of the raw interface{} value
type InterfaceSupporter interface {
	Get(name string) interface{}
	Set(name string, value interface{})
}

// StringSupporter allows the loading of string values
type StringSupporter interface {
	GetString(name string) string
	GetStringDefault(name string, default_ string) string
	SetString(name string, value string)
}

// IntSupporter allows the loading of int values
type IntSupporter interface {
	GetInt(name string) int
	SetInt(name string, value int)
}

// MapStringInterfaceSupporter allows the loading of map[string]interface{} values
type MapStringInterfaceSupporter interface {
	GetMapStringInterface(name string) map[string]interface{}
	SetMapStringInterface(name string, value map[string]interface{})
}
```

**Comment by caspertone2003** [comment]
Hi,
please do have a look to https://forum.rclone.org/t/piping-middleware-chaining/12737/7
and see ideas running ...
Thanks!

**Comment by fionera** [comment]
@caspertone2003 that is a completely different topic afaik, but with it a new Config system it would be easier to configure probably. Like adding a subsection to a remote config...

**Comment by caspertone2003** [comment]
@fionera
AFAIK I really do not understand... 
You said "This is a Thread to discuss a good interface for Config and the implementation of it."
And in https://forum.rclone.org/t/piping-middleware-chaining/12737/7 we are talking about changes to Config. Perhaps both things can go together... Or perhaps the information might be misleading.

Could it be that it would be "This is a Thread to discuss an update to config file structure" or ""This is a Thread to discuss a new interface for Config and the implementation of it." or .... ???

 good interface for Config and the implementation of it."

**Comment by fionera** [comment]
Ah. Yeah this is for the Interface itself. I want to make it as versatile as possible. With the current proposal, the mentioned stuff would be possible

**Comment by ncw** [comment]
I think I'd like to see something much simpler.

I don't think a config system should be supplying rclone anything but strings...  Currently we accept config from command line flags, the config file and environment variables all of which are strings.  I don't think it would be a good idea to couple rclone's internal type system for the config to an external config providers.

The minimum config could be to make an interface out of just what `Unknwon/goconfig` provides us.

I used interfacer from: https://github.com/rjeczalik/interfaces  to generate this

```
interfacer -for github.com/Unknwon/goconfig.ConfigFile
```

```go
type Interface interface {
	AppendFiles(...string) error
	Bool(string, string) (bool, error)
	DeleteKey(string, string) bool
	DeleteSection(string) bool
	Float64(string, string) (float64, error)
	GetKeyComments(string, string) string
	GetKeyList(string) []string
	GetSection(string) (map[string]string, error)
	GetSectionComments(string) string
	GetSectionList() []string
	GetValue(string, string) (string, error)
	Int(string, string) (int, error)
	Int64(string, string) (int64, error)
	MustBool(string, string, ...bool) bool
	MustFloat64(string, string, ...float64) float64
	MustInt(string, string, ...int) int
	MustInt64(string, string, ...int64) int64
	MustValue(string, string, ...string) string
	MustValueArray(string, string, string) []string
	MustValueRange(string, string, string, []string) string
	MustValueSet(string, string, ...string) (string, bool)
	Reload() error
	ReloadData(io.Reader) error
	SetKeyComments(string, string, string) bool
	SetSectionComments(string, string) bool
	SetValue(string, string, string) bool
}
```

And these are the only ones rclone actually uses

```go
type Interface interface {
	DeleteKey(string, string) bool
	DeleteSection(string) bool
	GetKeyList(string) []string
	GetSection(string) (map[string]string, error)
	GetSectionList() []string
	GetValue(string, string) (string, error)
	MustValue(string, string, ...string) string
	SetValue(string, string, string) bool
}
```

So I'd propose that as the minimum interface.  I think `MustValue` could be dropped as it is easy to make from `GetValue`.

I don't really want the config to get more complicated than a section => key => value.  Yes there are occasional comma separated lists but the bulk of the config is key/value.

What do you think?

**Comment by fionera** [comment]
I dont want to stick on this simple structure since it doesnt allow more complicated values to be stored like a mapping, without being impossible to read/edit. As I mentioned already I already implemented a remote to create a virtual file system with remotes attached to it. The config of it looks like this: https://imgur.com/QxaJpAt

Also I think the Interface itself should decouple the parts itself. When you request a remote you get a RemoteConfig. That way it would be easier to edit in the future. It would look like this then:

```golang
type Config interface {
	DeleteSection(string) bool
	GetSection(string) (*Section, error)
	GetSectionList() []string
}

type Section interface {
	GetKeyList(string) []string
	DeleteKey(string, string) bool
	GetValue(string, string) (string, error)
	SetValue(string, string, string) bool
}
```

And when we abstract it a little bit more we can allow the creation on more complex structures. That way we can move the List and Map generation to the config implementation itself and dont have to rely on external helpers. 

```golang
type Config interface {
	DeleteSection(string) bool
	GetSection(string) (*Section, error)
	GetSectionList() []string
}

type Section interface {
	GetKeyList(string) []string
	DeleteKey(string, string) bool
        StringSupporter
}

type StringSupporter interface {
	GetValue(string, string) (string, error)
	SetValue(string, string, string) bool
}
```

But I would rename the Get and Set methods to GetString and SetString. This way we can add more interfaces in the future and handle the conversion in the config implementation

**Comment by ncw** [comment]
Rclone is configured 3 different ways and you can provide all the config in any one of those ways.

1. the config file
2. environment variables
3. command line flags

Putting structure into the config file makes options 2. and 3. fail :-(

So I'd like to keep the config as section => key => value unless you can think of a way around that?

**Comment by fionera** [comment]
After a long and good talk about how it finished at about this:

```yaml
// ProviderDefinition defines a config backend.
// It will be created by calling the `NewFunc`.
// The `NewFunc` should not do any loading.
// The definitions would be registered on init, which allows endless modifications
type ProviderDefinition struct {
	NewFunc   func() Provider
}

// The basic interface a config Provider has to implement
// String returns the raw decrypted config content
// Load reads the already decrypted config file content
// Save writes the unencrypted config file content
// GetRemoveConfig returns an implementation of the RemoteConfig interface
type Provider interface {
	String() string
	Load(io.Reader) error
	Save(io.Writer) error
	GetRemoteConfig() RemoteConfig
}

// RemoteConfig is an interface to use the config of the remotes
// ListRemotes returns a slice with all the remote names
// HasRemotes returns if the given remote exists in the config
// GetRemote returns the config section of the named remote or nil if it does not exist
// CreateRemote creates a remote and returns the section for it
// DeleteRemote deletes a remote
type RemoteConfig interface {
	ListRemotes() []string
	HasRemote(remote string) bool
	GetRemote(remote string) Section
	CreateRemote(remote string) Section
	DeleteRemote(name string)
}

// Section is the config of a single remote
// GetKeys returns all set options
// GetConfig returns the raw config
// Delete deletes the config option with the given name
// It has to support loading and saving of string values by default
type Section interface {
	Keys() []string
	Delete(string) bool

	StringSupporter
}

// StringSupporter allows the loading of string values
type StringSupporter interface {
	GetString(name string) string
	SetString(name string, value string)
}
```

I readded the StringSupporter interface to keep the expansion door open without having to change everything. (I like having everyting sorted). I will make a PR to look how much work it would be

**Comment by ncw** [comment]
I think `GetString(name string) string` should return `GetString(name string) (string, bool)` where bool is whether it was found or not.  That will make it compatible with the current config system.

> I readded the StringSupporter interface to keep the expansion door open without having to change everything. (I like having everything sorted). I will make a PR to look how much work it would be

I'm more of a [YAGNI ](https://www.martinfowler.com/bliki/Yagni.html) sort of person here so my preference would be not to have it ;-)

**Comment by fionera** [comment]
I just found https://github.com/oleiade/trousseau which would also be nice as config provider so we can use pgp encryption for the config :)

**Comment by caspertone2003** [comment]
> 
> 
> I just found https://github.com/oleiade/trousseau which would also be nice as config provider so we can use pgp encryption for the config :)

nice, any windows port/alternative?

**Comment by fionera** [comment]
Since viper supports ini files now. I would rebuild this Idea by just replacing goconfig with viper.

**Comment by ncw** [comment]
> Since viper supports ini files now. I would rebuild this Idea by just replacing goconfig with viper.

What does that support look like @fionera ? Can you link some stuff?

**Comment by ivandeex** [comment]
@fionera This issue is dead for 3 months

**Comment by fionera** [comment]
> @fionera This issue is dead for 3 months

This is the issue related to https://github.com/rclone/rclone/pull/3747 and I currently just dont have much time to work on it. Since there is this pandemic thing doing pandemic things. I will continue to work on this so please dont close this issue.
