### ISSUE TITLE
[Amazon S3] Implementing Undelete

### ISSUE THREAD

**Issue by 9lives5nines** [rclone/rclone#3708]
rclone: 1.50

What problem are you are trying to solve?
Figuring out a sane way to undelete/restore files from Amazon S3.

How do you think rclone should be changed to solve that?
Some backends have the ability to undelete/restore. So this is probably a whole new feature set.

**Comment by ncw** [comment]
Are you thinking of s3 versions?  The [b2 backend supports versions](https://rclone.org/b2/#versions)  a similar thing could be done in the s3 backend.

Otherwise how does undelete work with s3?

**Comment by DoctorFez** [comment]
Restoring in S3 pretty much works the same way with b2 versions. Undeleting objects in S3 involves removing a delete marker. If an object is deleted with a version id argument, it becomes permanently deleted.

**Comment by ncw** [comment]
s3 versions is now implemented

      --s3-versions          Include old versions in directory listings

Closing this now.
