### ISSUE TITLE
Skip links sftp 

### ISSUE THREAD

**Issue by Michaelito80** [rclone/rclone#3716]
#### What is your current rclone version (output from `rclone version`)?

1.50.1

#### What problem are you are trying to solve?

I want to make a synchronization by skipping the symbolic links, if the origin in a local drive is no problem (option --skip-lines enable). But if the source is SFTP —skips-links does not work, I copy the symbolic links.

#### How do you think rclone should be changed to solve that?

I think that rclone should have an option --sftp-skip-lines

**Comment by ncw** [comment]
This would be quite easy to add.  It would mean adding a new config variable then reading it here

https://github.com/rclone/rclone/blob/c21a4fee5891d8abd8c57ff1f54727bcd0c685b2/backend/sftp/sftp.go#L596-L598

@Michaelito80 do you want to have a go at that?

**Comment by Michaelito80** [comment]
Thanks, 

I prefer it to be an official option, is it possible to enable this option in the next release?

**Comment by ncw** [comment]
> I prefer it to be an official option, is it possible to enable this option in the next release?

I'm asking if you'd like to have a go at making a pull request to implement this.  We could certainly get that into the next release :-)

**Comment by Michaelito80** [comment]
Yes, but I would like an official developer to do it :-), and be available in the next version. Thanks four your support

**Comment by Michaelito80** [comment]
> > I prefer it to be an official option, is it possible to enable this option in the next release?
> 
> I'm asking if you'd like to have a go at making a pull request to implement this. We could certainly get that into the next release :-)

Is it possible that you development it for the next version? :-)

**Comment by ncw** [comment]
Try this - it has a `--sftp-skip-links` flag

https://beta.rclone.org/branch/v1.50.1-046-g39418c74-fix-3716-sftp-links-beta/ (uploaded in 15-30 mins)

**Comment by Michaelito80** [comment]
> Try this - it has a `--sftp-skip-links` flag
> 
> https://beta.rclone.org/branch/v1.50.1-046-g39418c74-fix-3716-sftp-links-beta/ (uploaded in 15-30 mins)

Hi, I have find a bug.

option --sftp-skip-links is working correctly with symbolic links, but if I use the option to synchronize, it is deleting file in the destination that regular files

**Comment by ncw** [comment]
> option --sftp-skip-links is working correctly with symbolic links, but if I use the option to synchronize, it is deleting file in the destination that regular files

That is what `rclone sync` does - it deletes files in the destination that don't exist in the source.  By using `--sftp-skip-links` those files effectively disappear from the source so rclone deletes them in the destination.  They were probably copies of files copied through the symlink I imagine.

**Comment by Michaelito80** [comment]
> > option --sftp-skip-links is working correctly with symbolic links, but if I use the option to synchronize, it is deleting file in the destination that regular files
> 
> That is what `rclone sync` does - it deletes files in the destination that don't exist in the source. By using `--sftp-skip-links` those files effectively disappear from the source so rclone deletes them in the destination. They were probably copies of files copied through the symlink I imagine.

 Yes, I understand the sync. 

The problem is that with the option --sftp-skip-links, is deleting regular files in the destination (onedrive) that if they are in the source (sftp). If I try it with option -skip-links working correcly, destination (onedrive) / source (local).

Thanks for your help and support

**Comment by ncw** [comment]
Can you send a log with `-vv` illustrating what you mean please?

**Comment by Michaelito80** [comment]
> Can you send a log with `-vv` illustrating what you mean please?

For example, Execution with --sftp-skip-links. Delete several files in destination

<img width="679" alt="Captura de pantalla 2019-11-15 a las 15 12 13" src="https://user-images.githubusercontent.com/57587455/68963833-2d25be00-07d8-11ea-8564-014f58d21330.png">

In Source the file exists

<img width="582" alt="Captura de pantalla 2019-11-15 a las 15 12 43" src="https://user-images.githubusercontent.com/57587455/68963874-42025180-07d8-11ea-8978-34533edc8e9d.png">

It also shows these errors the execution

<img width="887" alt="Captura de pantalla 2019-11-15 a las 14 07 17" src="https://user-images.githubusercontent.com/57587455/68963923-5e9e8980-07d8-11ea-8e37-21b313e7046c.png">

Thanks for your help

Regards

**Comment by ncw** [comment]
Can you attach a complete log please?  I can't really see what is going on there.  Or if you don't want to make it public email it to nick@craig-wood.com with a link to this issue - thanks.

**Comment by Michaelito80** [comment]
> Can you attach a complete log please? I can't really see what is going on there. Or if you don't want to make it public email it to [nick@craig-wood.com](mailto:nick@craig-wood.com) with a link to this issue - thanks.

Hi, I sent to you a mail with logs. Thanks

**Comment by ncw** [comment]
Thanks for the log :-)

I have found the problem with that I think - please have a go with this

https://beta.rclone.org/branch/v1.50.2-057-g5269705c-fix-3716-sftp-links-beta/ (uploaded in 15-30 mins)

Thanks for your patience!

**Comment by Michaelito80** [comment]
> Thanks for the log :-)
> 
> I have found the problem with that I think - please have a go with this
> 
> https://beta.rclone.org/branch/v1.50.2-057-g5269705c-fix-3716-sftp-links-beta/ (uploaded in 15-30 mins)
> 
> Thanks for your patience!

I'm going to try it

Thanks

**Comment by Michaelito80** [comment]
> Thanks for the log :-)
> 
> I have found the problem with that I think - please have a go with this
> 
> https://beta.rclone.org/branch/v1.50.2-057-g5269705c-fix-3716-sftp-links-beta/ (uploaded in 15-30 mins)
> 
> Thanks for your patience!

Hi, beta version is working  correctly :-). Are you going to include it in the stable version?

Thank you very much

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.51
