### ISSUE TITLE
unable to ls inside k8s container

### ISSUE THREAD

**Issue by LeoQuote** [rclone/rclone#3717]
#### What is the problem you are having with rclone?

unable to list file inside a k8s container. I can upload some files successfully with sync command , but some of them are empty( size 0), along with some errors as follow:

```
2019/11/11 11:05:30 ERROR : index.html?p=133: Failed to copy: s3 upload: sign request: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, PutObjectInput.Key.
```

what could be the problem? what can I do to troubleshoot this?

#### What is your rclone version (output from `rclone version`)

```
bash-5.0# rclone version 
rclone v1.50.1
- os/arch: linux/amd64
- go version: go1.13.4
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

alpine latest

####  Which cloud storage system are you using? (eg Google Drive)

tencent cos

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
rclone ls remote:.
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
bash-5.0# rclone --config  /config/rclone/rclone.conf ls remote:. -vv
2019/11/11 11:27:34 DEBUG : rclone: Version "v1.50.1" starting with parameters ["rclone" "--config" "/config/rclone/rclone.conf" "ls" "site-doubanblog:." "-vv"]
2019/11/11 11:27:34 DEBUG : Using config file from "/config/rclone/rclone.conf"
2019/11/11 11:27:35 Failed to ls: directory not found
```

**Comment by ncw** [comment]
I would guess this is because you are trying to use a bucket called `.` in `remote:.`.  

You probably wanted a bucket name there...

**Comment by LeoQuote** [comment]
you're exactly right, is this related to any recent release ? I can run this with rclone 1.47, I though it would work on 1.50

**Comment by ncw** [comment]
It is probably an unintended consequence of the bucket based remote tidying that let them all work from the root.

I don't think the usage makes sense so I don't want to make it work like it did in 1.47 - is that OK?

**Comment by LeoQuote** [comment]
thanks for your reply , it would be better if this can be listed in "breaking changes", I've looked up the change list but there are too many changes.
