### ISSUE TITLE
[chunker] Add "chunk_size" entry to file metadata

### ISSUE THREAD

**Issue by comio** [rclone/rclone#3720]
#### What is your current rclone version (output from `rclone version`)?
```
rclone --version
rclone v1.50.1
- os/arch: linux/amd64
- go version: go1.13.3


```
#### What problem are you are trying to solve?

Have mixed chunk size into the same directory.

#### How do you think rclone should be changed to solve that?

- Add to chunker backend the support for file defined chunk size (ie "chunk_size: 65536")
- Update this value on write with the configuration defined value
- Use the file specific chunk_size value in order to calculate the file / offset.

**Comment by ivandeex** [comment]
Hi
What is practical use case for per-file chunk size?

**Comment by ivandeex** [comment]
Internally, chunker's Open API call allows for offsets into file without depending on chunk size. Offset is calculated on the fly, it's tested with mixed size chunks per single file, even empty chunks. The only place that reads chunk size is the Put call (file upload).

**Comment by ivandeex** [comment]
Having custom chunk size per upload is also possible via --chunker-chunk-size cli flag or RCLONE_CHUNKER_CHUNK_SIZE environment, with config value as a default.
What would be use case for that?

**Comment by comio** [comment]
> Having custom chunk size per upload is also possible via --chunker-chunk-size cli flag or RCLONE_CHUNKER_CHUNK_SIZE environment, with config value as a default.
> What would be use case for that?

Understood, then do you confirm that I can have mixed chunk sizes for different files? I started using 32M chunks, but I would like to increase this value for the next uploads (keeping the previously uploaded files). Should be not an problem. right?

**Comment by ivandeex** [comment]
Right

**Comment by comio** [comment]
I'm closing because the actual implementation fits well my user case.
Sorry for the noise.
Thanks again for your quick answers.
