### ISSUE TITLE
rclone core/quit remote call doesn't run fusermount -u /mountpoint when called

### ISSUE THREAD

**Issue by petzsch** [rclone/rclone#3721]
#### What is the problem you are having with rclone?

Whenever I stop the rclone daemon with `rclone rc core/quit exitCode=15` (assuming that's the correct procedure for a SIGTERM) it doesn't seem to cleanup the mountpoint with running `fusermount -u /mountpoint` as one would expect. This leads to the rclone binary failing to start after a close with the following error:

> Fatal error: Can not open: /home/markus/OneDrive: open /home/markus/OneDrive: transport endpoint is not connected

#### What is your rclone version (output from `rclone version`)

rclone v1.50.1
- os/arch: linux/amd64
- go version: go1.13.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian Linux 10.1 AMD64

####  Which cloud storage system are you using? (eg Google Drive)

OneDrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

see problem description.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

`2019/11/11 18:32:55 NOTICE: Serving remote control on http://127.0.0.1:5572/
2019/11/11 18:32:55 DEBUG : Using config file from "/home/markus/.config/rclone/rclone.conf"
2019/11/11 18:32:56 DEBUG : One drive root '': Mounting on "/home/markus/OneDrive"
2019/11/11 18:32:56 INFO  : One drive root '': poll-interval is not supported by this remote
2019/11/11 18:32:56 DEBUG : vfs cache root is "/home/markus/.cache/rclone/vfs/onedrive"
2019/11/11 18:32:56 DEBUG : Adding path "vfs/forget" to remote control registry
2019/11/11 18:32:56 DEBUG : Adding path "vfs/refresh" to remote control registry
2019/11/11 18:32:56 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2019/11/11 18:32:56 DEBUG : : Root:
2019/11/11 18:32:56 DEBUG : : >Root: node=/, err=<nil>
2019/11/11 18:33:40 DEBUG : rc: "core/quit": with parameters map[exitCode:15]
2019/11/11 18:33:40 DEBUG : rc: "core/quit": reply map[]: <nil>
2019/11/11 18:33:54 DEBUG : rclone: Version "v1.50.1" starting with parameters ["rclone" "-vv" "--rc" "--log-file" "/tmp/rclone.log" "--vfs-cache-mode" "writes" "mount" "onedrive:" "/home/markus/OneDrive" "--daemon"]
2019/11/11 18:33:54 NOTICE: Serving remote control on http://127.0.0.1:5572/
2019/11/11 18:33:54 DEBUG : Using config file from "/home/markus/.config/rclone/rclone.conf"
2019/11/11 18:33:54 Fatal error: Can not open: /home/markus/OneDrive: open /home/markus/OneDrive: transport endpoint is not connected
2019/11/11 18:42:24 DEBUG : rclone: Version "v1.50.1" starting with parameters ["rclone" "-vv" "--rc" "--log-file" "/tmp/rclone.log" "--vfs-cache-mode" "writes" "mount" "onedrive:" "/home/markus/OneDrive" "--daemon"]
2019/11/11 18:42:24 NOTICE: Serving remote control on http://127.0.0.1:5572/
2019/11/11 18:42:24 DEBUG : Using config file from "/home/markus/.config/rclone/rclone.conf"
2019/11/11 18:42:24 Fatal error: Can not open: /home/markus/OneDrive: open /home/markus/OneDrive: transport endpoint is not connected`

**Comment by ncw** [comment]
I can replicate this problem.

Try this fix?

https://beta.rclone.org/branch/v1.50.1-035-gc21a4fee-fix-3721-quit-umount-beta/ (uploaded in 15-30 mins)

**Comment by petzsch** [comment]
Thanks that fix worked for me. 👍

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.51
