### ISSUE TITLE
 sync of google doc loses its version history

### ISSUE THREAD

**Issue by jhnc** [rclone/rclone#3722]
#### What is your current rclone version (output from `rclone version`)?

ubuntu 1.36-3

#### What problem are you are trying to solve?

I am backing up google documents to local storage.

I have google documents each with multiple named revisions (version history) as well as the default unnamed dated versions. If I perform a sync (rclone sync drive: localpath) the result is that the localpath has the documents exported as .docx but only the current version of the file is available.

#### How do you think rclone should be changed to solve that?

It would be useful to be able to copy/sync all of the revisions from the version history, particularly named versions.

**Comment by ncw** [comment]
Rclone doesn't currently access the versions available in google drive, so you'll always get the latest version.

How would you expect to be able to access the previous versions?  Rclone would have to save each one as a separate file I think.

**Comment by animosity22** [comment]
This looks to be answered. 

If you still have a question, please ask on https://forums.rclone.org
