### ISSUE TITLE
Ceph Status 403 with v2 or v4 auth

### ISSUE THREAD

**Issue by HeroesLament** [rclone/rclone#3725]
#### Output of `rclone version`
rclone v1.50.1
- os/arch: linux/amd64
- go version: go1.13.4

#### Describe the issue
Unable to connect to Ceph storage at all, Wasabi connects fine. rclone -vv --dump bodies returns this:

root@rclone:/etc/apt# rclone ls {ceph remote name}: -vv --dump bodies --no-check-certificate
2019/11/12 20:13:06 DEBUG : rclone: Version "v1.50.1" starting with parameters ["rclone" "ls" "{remote name}" "-vv" "--dump" "bodies" "--no-check-certificate"]
2019/11/12 20:13:06 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2019/11/12 20:13:06 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/12 20:13:06 DEBUG : HTTP REQUEST (req 0xc00046f300)
2019/11/12 20:13:06 DEBUG : GET / HTTP/1.1
Host: {endpoint}
User-Agent: rclone/v1.50.1
Authorization: XXXX
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20191112T201306Z
Accept-Encoding: gzip

2019/11/12 20:13:06 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/12 20:13:06 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/12 20:13:06 DEBUG : HTTP RESPONSE (req 0xc00046f300)
2019/11/12 20:13:06 DEBUG : HTTP/1.1 403 Forbidden
Content-Length: 192
Accept-Ranges: bytes
Connection: Keep-Alive
Content-Type: application/xml
Date: Tue, 12 Nov 2019 20:13:06 GMT
X-Amz-Request-Id: tx00000000000000000387b-005dcb1252-b9a90a0-hou

<?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><RequestId>tx00000000000000000387b-005dcb1252-b9a90a0-hou</RequestId><HostId>b9a90a0-hou-central</HostId></Error>
2019/11/12 20:13:06 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/12 20:13:06 Failed to ls: SignatureDoesNotMatch:
        status code: 403, request id: tx00000000000000000387b-005dcb1252-b9a90a0-hou, host id:

I've tried v2 auth, v4 auth, playing with blank vs filled in region and location constraint for my Ceph zonegroup. Always seem to get this error.

**Comment by HeroesLament** [comment]
Also, just for information, we're running Ceph 14.2.4 Mimic. Not on Jewel.

**Comment by ncw** [comment]
What does your config look like?

Here is a working config which works with CEPH Luminous

```
[cephtest]
type = s3
provider = Ceph
env_auth = false
access_key_id = XXX
secret_access_key = XXX
endpoint = https://XXX
```

**Comment by HeroesLament** [comment]
[my-remote-name]
type = s3
provider = Ceph
env_auth = false
access_key_id = {REDACTED}
secret_access_key = {REDACTED}
endpoint = {my ceph endpoint]
region = central
location_constraint = central

That's how it stands currently, but I've also tried with blank region and location_constraint.

**Comment by ncw** [comment]
I think removing the region and location constraint is necessary...

Also note this [from the docs](https://rclone.org/s3/#ceph)

> Note also that Ceph sometimes puts / in the passwords it gives users. If you read the secret access key using the command line tools you will get a JSON blob with the / escaped as \/. Make sure you only write / in the secret access key.

**Comment by HeroesLament** [comment]
--------------------
[redacted]
type = s3
provider = Ceph
env_auth = false
access_key_id = {redacted}
secret_access_key = {redacted}
endpoint = {my-ceph-endpoint}
--------------------


That's now my current config, same 403 error.

**Comment by ncw** [comment]
Did you see my note about `/` in the keys?

**Comment by HeroesLament** [comment]
I did, and I can confirm both the access key and secret only contain numbers and letters, no slashes of any kind.

**Comment by HeroesLament** [comment]
checked via "radosgw-admin user info --uid={user-id}", so I think that should be an accurate statement.

**Comment by ncw** [comment]
Hmmm... Does the hostname of the CEPH cluster match the hostname it thinks it is serving on?

Is the date/time/timezone correct on the computer you are doing the request from?

Do any other s3 programs work with your CEPH cluster?

**Comment by HeroesLament** [comment]
s3cmd worked on the same box, but I just specified the timezone to CST and it miraculously worked! Weird that rclone needs that, and we seem to be listing buckets just fine now. Will experiment with some operations and we'll see how it works.

**Comment by HeroesLament** [comment]
So, listing content now returns a 200, but it shows nothing returned. Trying to mkdir a bucket still returns a 403, even after setting the timezone to the local timezone and ensuring the clock was accurate.

**Comment by ncw** [comment]
Can you send a log with `-vv --dump bodies` of the failed `mkdir` and the empty `ls`

**Comment by HeroesLament** [comment]
mkdir:

`root@rclone:~# rclone mkdir {remote}:main-new  -vv --dump bodies --no-check-certificate
2019/11/13 16:42:40 DEBUG : rclone: Version "v1.50.1" starting with parameters ["rclone" "mkdir" "{remote}:main-new" "-vv" "--dump" "bodies" "--no-check-certificate"]
2019/11/13 16:42:40 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2019/11/13 16:42:40 DEBUG : S3 bucket main-new: Making directory
2019/11/13 16:42:40 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/13 16:42:40 DEBUG : HTTP REQUEST (req 0xc0005c8100)
2019/11/13 16:42:40 DEBUG : PUT /main-new HTTP/1.1
Host: {endpoint}
User-Agent: rclone/v1.50.1
Content-Length: 0
Authorization: XXXX
X-Amz-Acl: public-read
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20191113T224240Z
Accept-Encoding: gzip

2019/11/13 16:42:40 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/13 16:42:41 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/13 16:42:41 DEBUG : HTTP RESPONSE (req 0xc0005c8100)
2019/11/13 16:42:41 DEBUG : HTTP/1.1 200 OK
Content-Length: 0
Connection: Keep-Alive
Date: Wed, 13 Nov 2019 22:42:41 GMT
X-Amz-Request-Id: tx00000000000000000b206-005dcc86e0-c47b445-hou

2019/11/13 16:42:41 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/13 16:42:41 INFO  : S3 bucket main-new: Bucket "main-new" created with ACL "public-read"
2019/11/13 16:42:41 DEBUG : 5 go routines active
2019/11/13 16:42:41 DEBUG : rclone: Version "v1.50.1" finishing with parameters ["rclone" "mkdir" "{remote}:main-new" "-vv" "--dump" "bodies" "--no-check-certificate"]
root@rclone:~#`

ls output
`2019/11/13 16:46:54 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/13 16:46:54 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/13 16:46:54 DEBUG : HTTP REQUEST (req 0xc000180300)
2019/11/13 16:46:54 DEBUG : GET /main-new?delimiter=&max-keys=1000&prefix= HTTP/1.1
Host: {endpoint}
User-Agent: rclone/v1.50.1
Authorization: XXXX
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20191113T224654Z
Accept-Encoding: gzip

2019/11/13 16:46:54 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/13 16:46:54 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/13 16:46:54 DEBUG : HTTP RESPONSE (req 0xc000180300)
2019/11/13 16:46:54 DEBUG : HTTP/1.1 200 OK
Transfer-Encoding: chunked
Connection: Keep-Alive
Content-Type: application/xml
Date: Wed, 13 Nov 2019 22:46:54 GMT
X-Amz-Request-Id: tx00000000000000000b471-005dcc87de-c47b445-hou

107
<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Tenant>{user}</Tenant><Name>main-new</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated></ListBucketResult>
0

2019/11/13 16:46:54 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/13 16:46:54 DEBUG : 5 go routines active
2019/11/13 16:46:54 DEBUG : rclone: Version "v1.50.1" finishing with parameters ["rclone" "ls" "{remote}:" "-vv" "--dump" "bodies" "--no-check-certificate"]
root@rclone:~#
`

Now it's returning 200 Status's, but ls doesn't show the bucket as being created... bizarre

**Comment by ncw** [comment]
That actually looks like it is working. ls only shows files and there aren't any, hence there blank output.

Do rclone lsf or rclone lsd of the root to show the buckets.

Can you upload files now?

**Comment by animosity22** [comment]
This looks to be stale.

If you still have a question, please ask on https://forums.rclone.org

Thanks!
