### ISSUE TITLE
AWS S3 -> Google Drive (goroutine ####)

### ISSUE THREAD

**Issue by mcc42** [rclone/rclone#3727]
#### What is the problem you are having with rclone?
I've seemingly correctly configured my S3 and Gdrive host configurations, and I can copy data between the two of them.

However, after about a minute of migrating data, the copy stops, and my terminal is flooded with the following errors.

https://hastebin.com/iqewegukey.cs

#### What is your rclone version (output from rclone version)

```
rclone v1.50.1
- os/arch: linux/amd64
- go version: go1.13.4
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 18.04 (64bit)

#### Which cloud storage system are you using? (eg Google Drive)

- Google Drive
- Amazon AWS S3

#### The command you were trying to run (eg rclone copy /tmp remote:tmp)
```
rclone copy --progress --ignore-existing --transfers 10 --checkers 8 --contimeout 60s --timeout 300s --retries 3 --low-level-retries 10 --stats 1s  s3:fs-bk "gdrive:AWS S3 Archive"
```

#### A log from the command with the -vv flag (eg output from rclone -vv copy /tmp remote:tmp)

Full debug log - available at request.

**Comment by ncw** [comment]
> Full debug log - available at request.

Your log doesn't show the start of the backtrace.  I'm guessing you ran out of memory but it is only a guess without the log!

Can you paste it here, or email it to me nick@craig-wood.com (with a link to this page) - thank you!

**Comment by mcc42** [comment]
So, I took a look at the debug log, and yes, it is reporting "OUT OF MEMORY"

**Comment by ncw** [comment]
What did your command line say before?

**Comment by mcc42** [comment]
> What did your command line say before?

```
rclone copy --progress --ignore-existing --transfers 10 --checkers 8 --contimeout 60s --timeout 300s --retries 3 --low-level-retries 10 --stats 1s  s3:fs-bk "gdrive:AWS S3 Archive"
```

Basically I maxed it out. Never considered RAM would be an issue.

**Comment by ncw** [comment]
Rclone will use (roughtly) per transfer
- 16 MB of RAM for the transfer buffer (size with --buffer-size)
- 5MB (`--s3-chunk-size`) * 4 (`--s3-upload-concurrency`) = 20MB for the s3 upload

So that is ~36MB RAM for 1 transfer and hence ~360MB for 10.  Go might double that as it isn't particularly efficient with its memory use sometimes!

How much memory does your computer have?

**Comment by animosity22** [comment]
If you still need support, you can ask on https://forums.rclone.org and we can help out.
