### ISSUE TITLE
Fix confusion over whether `pass` is encrypted in `rclone config create`

### ISSUE THREAD

**Issue by jusito** [rclone/rclone#3728]
Hello and thanks for your time.

#### What is the problem you are having with rclone?
rclone can't use my app password for owncloud(webdav), the account password is working fine. I verified that the app password itself is usable by mounting the owncloud root with it.
`sudo mount -t davfs -o noexec https://owncloud.example.de/owncloud/remote.php/webdav /home/user/owncloud`
I creating the config always with this command:
`rclone config create MyProfile webdav url "$TARGET_URL" vendor owncloud user "$TARGET_USER" pass "$TARGET_PASSWORD"`

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Host Ubuntu 16 lts x64 but iam using docker and gitlab runner.
`docker run --rm --entrypoint=/bin/sh -it rclone/rclone:1.50.1`

#### What is your rclone version (output from `rclone version`)
```
rclone v1.50.1 & v1.50.1-036-g2784c323-beta
- os/arch: linux/amd64
- go version: go1.13.4
```

####  Which cloud storage system are you using? (eg Google Drive)
Owncloud, webdav

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone ls MyProfile:/`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2019/11/13 20:26:28 DEBUG : rclone: Version "v1.50.1" starting with parameters ["rclone" "ls" "-vv" "MyProfile:/"]
2019/11/13 20:26:28 DEBUG : Using config file from "/config/rclone/rclone.conf"
2019/11/13 20:26:34 ERROR : : error listing: couldn't list files: Username or password was incorrect, Username or password was incorrect, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured: Sabre\DAV\Exception\NotAuthenticated: 401 Unauthorized
2019/11/13 20:26:34 Failed to ls with 2 errors: last error was: couldn't list files: Username or password was incorrect, Username or password was incorrect, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured: Sabre\DAV\Exception\NotAuthenticated: 401 Unauthorized
```

**Comment by ncw** [comment]
> I creating the config always with this command:
> `rclone config create MyProfile webdav url "$TARGET_URL" vendor owncloud user "$TARGET_USER" pass "$TARGET_PASSWORD"`

You'll need to split this into two so your config password gets obscured in the config file

```
rclone config create MyProfile webdav url "$TARGET_URL" vendor owncloud user "$TARGET_USER"
rclone config password MyProfile pass "$TARGET_PASSWORD"
```

**Comment by jusito** [comment]
This is working!
A little bit irritating, if iam using the one line config creation, it shows "pass = *** ENCRYPTED ***" as a result.
Is this behaviour intentional?

**Comment by ncw** [comment]
Sorry, I forgot that I fixed this in 903ede52cd71a85d80b2db5e98ca677e4aa54ebd so you don't need to use the two line config. This was released for v1.48.0

So I think your original config should have worked....

Can you paste the generated config (XXX out confidential stuff)?

**Comment by jusito** [comment]
Excuse me please for 19 days no reply.
Tested it with 1.50.1, 1.50.2 and current beta from Dockerhub.
docker run --rm -it --entrypoint /bin/sh rclone/rclone:xxx
Everytime the same behavior normal password is working with MyProfileOneLiner but App-Password not. The variables $Target... are always used, not just a replacement here.

```
rclone config create MyProfileOneLiner webdav url "$TARGET_URL" vendor owncloud user "$TARGET_USER" pass "$TARGET_PASSWORD"
Remote config
--------------------
[MyProfileOneLiner]
type = webdav
user = CorrectUserName
pass = *** ENCRYPTED ***
url = https://owncloud.fraunhofer.de/owncloud/remote.php/webdav
vendor = owncloud
--------------------
rclone config show MyProfileOneLiner
--------------------
[MyProfileOneLiner]
type = webdav
url = https://owncloud.fraunhofer.de/owncloud/remote.php/webdav
vendor = owncloud
user = CorrectUserName
pass = *** ENCRYPTED ***
--------------------
```

```
rclone config create MyProfileTwoLines webdav url "$TARGET_URL" vendor owncloud user "$TARGET_USER"
Remote config
--------------------
[MyProfileTwoLines]
type = webdav
url = https://owncloud.fraunhofer.de/owncloud/remote.php/webdav
vendor = owncloud
user = CorrectUserName
--------------------
rclone config password MyProfileTwoLines pass "$TARGET_PASSWORD"
Remote config
--------------------
[MyProfileTwoLines]
type = webdav
url = https://owncloud.fraunhofer.de/owncloud/remote.php/webdav
vendor = owncloud
user = CorrectUserName
pass = *** ENCRYPTED ***
--------------------
rclone config show MyProfileTwoLines
--------------------
[MyProfileTwoLines]
type = webdav
user = CorrectUserName
url = https://owncloud.fraunhofer.de/owncloud/remote.php/webdav
vendor = owncloud
pass = *** ENCRYPTED ***
--------------------
```

**Comment by jusito** [comment]
Password is not allowed to be longer as 21 characters:
Tested with: `docker run --rm -it --entrypoint /bin/sh rclone/rclone:1.51.0`

21 characters, password is encrypted:
`rclone config create P1 webdav url "https://example.com" vendor owncloud user "jd" pass "123456789012345678901" && grep "pass =" /config/rclone/rclone.conf`
```
Remote config
--------------------
[P1]
type = webdav
user = jd
pass = *** ENCRYPTED ***
url = https://example.com
vendor = owncloud
--------------------
pass = -u1Xf8eD-P96P3-FoyCB3sGlFr1Ttm14FKuO4ArAQnt7GPFFyA
```



22 characters, password is not encrypted:
`rclone config create P1 webdav url "https://example.com" vendor owncloud user "jd" pass "1234567890123456789012" && grep "pass =" /config/rclone/rclone.conf`
```
Remote config
--------------------
[P1]
type = webdav
url = https://example.com
vendor = owncloud
user = jd
pass = *** ENCRYPTED ***
--------------------
pass = 1234567890123456789012
```

**Comment by ncw** [comment]
Ah... This is because rclone thinks "1234567890123456789012" is already encrypted and it doesn't encrypt it again :-(

You can set it with `rclone config password P1 pass 1234567890123456789012`

I guess rclone needs to stop guessing whether the password is encrypted or not....

Previous uses of `rclone config update ... pass` would have assumed the argument was encrypted.

Maybe I should make some new parameters `plainpass` and `obscuredpass` which don't guess, leaving `pass` as it is for backwards compatibility?

**Comment by jusito** [comment]
> You can set it with `rclone config password P1 pass 1234567890123456789012`
This is the solution iam using.

> Maybe I should make some new parameters `plainpass` and `obscuredpass` which don't guess, leaving `pass` as it is for backwards compatibility?
In my opinion this would be a clean solution.
An output could be useful which gives a information/warning after using "rclone config create ... pass". Something like "pass has at least 22 characters assumed its already encrypted" "pass assumed unencrypted", or is there actually a documentation I missed?

**Comment by ncw** [comment]
> An output could be useful which gives a information/warning after using "rclone config create ... pass". Something like "pass has at least 22 characters assumed its already encrypted" "pass assumed unencrypted", or is there actually a documentation I missed?

That is a good idea.

I'll think some more on these unless you fancied sending a pull request?

**Comment by jusito** [comment]
I want to try it, think I know where to start but I don't know how much time I will need.

**Comment by ncw** [comment]
Great! No time pressure.

The problem code is here:

https://github.com/rclone/rclone/blob/964f1f6a7e4cf150331344c40efc516756683509/fs/config/config.go#L1057-L1066

We need to figure out a way of signalling

1. the password may or may not be obscured (current behaviour)
2. the password **is** obscured
3. the password **is not** obscured

Easy fix might be to prefix the password with `:plaintext:` for 3 and `:obscured:` for 2. This of course potentially clashes with 1 in a minor way...

**Comment by alexanderadam** [comment]
In that case it probably would make sense to update the documentation. Because [currently it says](https://rclone.org/commands/rclone_config_create/):

> If any of the parameters passed is a password field, then rclone will automatically obscure them before putting them in the config file.

Which is obviously _not_ automatically the case until this issue is solved. :wink:

**Comment by ncw** [comment]
OK I have fixed this properly here

https://beta.rclone.org/branch/v1.51.0-303-gc0755056-fix-3728-config-obscure-beta/ (uploaded in 15-30 mins)

This has updated docs and two new flags - let me know if this works for you! It is also available over the rc.

      --no-obscure   Force any passwords not to be obscured.
      --obscure      Force any passwords to be obscured.

> If any of the parameters passed is a password field, then rclone will
> automatically obscure them if they aren't already obscured before
> putting them in the config file.
> 
> **NB** If the password parameter is 22 characters or longer and
> consists only of base64 characters then rclone can get confused about
> whether the password is already obscured or not and put unobscured
> passwords into the config file. If you want to be 100% certain that
> the passwords get obscured then use the "--obscure" flag, or if you
> are 100% certain you are already passing obscured passwords then use
> "--no-obscure".  You can also set osbscured passwords using the
> "rclone config password" command.
>

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

**Comment by rajeshgoyalg** [comment]
@ncw 

Looks like there is still issue with pass encryption. 

I am using `rclone config create` to create remote - 

```rclone config create 5e7b896190ef80a3ed3d4674-ftp ftp host XXX.XXX.XXX.XXX user user@example.in pass ?faZsBEuNY$x```

and then to transfer file -

```rclone copy --stats-one-line /abc.txt 5e7b896190ef80a3ed3d4674-ftp:/abc -P --no-traverse```

It throws error - "Failed to create file system for "5e7b896190ef80a3ed3d4674-ftp:/abc": NewFs: ftpConnection Login: 530 Login authentication failed"

However, same works fine when rclone remote created interactively.
 
I have even tried by passing option --obscure
```rclone config create 5e7b896190ef80a3ed3d4674-ftp ftp host XXX.XXX.XXX.XXX user user@example.in pass ?faZsBEuNY$x --obscure```

#### What is the problem you are having with rclone?

There is some issue only with specific passwords (with some special chars).

#### What is your rclone version (output from `rclone version`)

rclone v1.53.2

- os/arch: linux/amd64

- go version: go1.15.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux TESTNODE1-DEV 4.15.0-1098-azure #109~16.04.1-Ubuntu SMP Wed Sep 30 18:53:14 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

####  Which cloud storage system are you using? (eg Google Drive)

FTP / SFTP

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)  


```
rclone config create 5e7b896190ef80a3ed3d4674-ftp ftp host XXX.XXX.XXX.XXX user user@example.in pass ?faZsBEuNY$x
```

```
rclone copy --stats-one-line /abc.txt 5e7b896190ef80a3ed3d4674-ftp:/abc -P --no-traverse
```


#### The rclone config contents with secrets removed.  


```
[5e7b896190ef80a3ed3d4674-ftp]

type = ftp

user = user@example.in

pass = cC6W-jc9WtV2caO9WPZJ3AZmigQ8bfWyqkc

host = XXX.XXX.XXX.XXX
```



#### A log from the command with the `-vv` flag  


```
2020/11/30 08:54:45 DEBUG : rclone: Version "v1.53.2" starting with parameters ["rclone" "copy" "--stats-one-line" "/abc.txt" "5e7b896190ef80a3ed3d4674-ftp:/abc” "-P" "--no-traverse" "-vv"]

2020/11/30 08:54:45 DEBUG : Creating backend with remote "/abc.txt"

2020/11/30 08:54:45 DEBUG : Using config file from "/.config/rclone/rclone.conf"

2020/11/30 08:54:45 DEBUG : fs cache: adding new entry for parent of "/abc.txt", "/"

2020/11/30 08:54:45 DEBUG : Creating backend with remote "5e7b896190ef80a3ed3d4674-ftp:/abc”

2020/11/30 08:54:45 DEBUG : ftp://XXX.XXX.XXX.XXX:21/abc: Connecting to FTP server

2020/11/30 08:54:50 ERROR : ftp://XXX.XXX.XXX.XXX:21/abc: Error while Logging in into XXX.XXX.XXX.XXX:21: 530 Login authentication failed

2020/11/30 08:54:50 Failed to create file system for "5e7b896190ef80a3ed3d4674-ftp:/a”bc: NewFs: ftpConnection Login: 530 Login authentication failed
```

**Comment by ncw** [comment]
> I am using `rclone config create` to create remote -
> 
> `rclone config create 5e7b896190ef80a3ed3d4674-ftp ftp host XXX.XXX.XXX.XXX user user@example.in pass ?faZsBEuNY$x`

The shell is interpreting the `$x` - you need quotes round that

    rclone config create 5e7b896190ef80a3ed3d4674-ftp ftp host XXX.XXX.XXX.XXX user user@example.in pass '?faZsBEuNY$x'
