### ISSUE TITLE
google Photos 429 RESOURCE_EXHAUSTED

### ISSUE THREAD

**Issue by joseaguardia** [rclone/rclone#3736]
Hello.

I sync one small album everyday from Google Photos, but today I'm getting:

`2019/11/15 07:51:26 ERROR : : error reading source directory: couldn't list albums: Quota exceeded for quota metric 'All requests' and limit 'All requests per day' of service 'photoslibrary.googleapis.com' for consumer 'project_number:202264815000'. (429 RESOURCE_EXHAUSTED)
2019/11/15 07:51:26 ERROR : Local file system at /home/pi/MagicMirror/modules/MMM-ImageSlideshow/fotos: not deleting files as there were IO errors
2019/11/15 07:51:26 ERROR : Local file system at /home/pi/MagicMirror/modules/MMM-ImageSlideshow/fotos: not deleting directories as there were IO errors
2019/11/15 07:51:26 ERROR : Attempt 1/3 failed with 2 errors and: couldn't list albums: Quota exceeded for quota metric 'All requests' and limit 'All requests per day' of service 'photoslibrary.googleapis.com' for consumer 'project_number:202264815000'. (429 RESOURCE_EXHAUSTED)`

Regards

**Comment by ncw** [comment]
I have asked google for some more quota which should help!

**Comment by dlang123** [comment]
I too get the same error.  I am using my own API I thought for it, and it has been days since I last tried to back it up.  

error reading destination directory: couldn't list albums: Quota exceeded for quota metric 'All requests' and limit 'All requests per day' of service 'photoslibrary.googleapis.com' for

Tried to back it up again with the last attempt happening on 1/6/2020 and today being 1/11/2020 and still resource is exhausted showing max api calls.  Is there something else that is causing tons of api calls?

**Comment by ncw** [comment]
I've asked for some more quota again.

> Tried to back it up again with the last attempt happening on 1/6/2020 and today being 1/11/2020 and still resource is exhausted showing max api calls. Is there something else that is causing tons of api calls?

You can see in the console which API calls you are using.

Which path of google photos are you backing up?  The by-day is very intensive on API calls.

**Comment by dlang123** [comment]
I noticed a couple of things, once I start hitting the errors for API exceeded (I am trying to do it by Albums but I have several folders deep Pictures/Year/Day/Event so the Albums are long named) if I cancel the upload my API's barely decrease, guessing this is something to do with the way Unraid is running the script.  If I restart my server, then wait a day or two, the api calls decrease.

**Comment by dlang123** [comment]
Hmm just verified that yeah, it keeps running even though I thought I cancelled it.  No wonder the quota never drops.  The logs just show copys, and some xmp files that fail to copy, before I was getting failures on album creations.

**Comment by ncw** [comment]
Ah ha!

**Comment by animosity22** [comment]
This looks to be answered.

If you have anymore questions, please ask on https://forums.rclone.org

Thanks!
