### ISSUE TITLE
rclone verbose transfer output does not allow to track individual transfers - ID needed

### ISSUE THREAD

**Issue by kapitainsky** [rclone/rclone#3738]
I am working on [Rclone Browser](https://github.com/kapitainsky/RcloneBrowser) GUI and recently it has been pointed out to me (kapitainsky/RcloneBrowser#32) that sometimes individual transfers' progress is missing.

What Rclone Browser normally does is showing user progress of their transfers

<img width="1121" alt="screenshot24" src="https://user-images.githubusercontent.com/15635386/68934083-eca15280-078d-11ea-83f9-38f1ce621fa5.png">

I run transfer with verbose option on and then scrap details from rclone output to display progress bars.

The issue has been identified by @nagleaidan as related to rclone output files names shortening. If files names have to be shortened it can happen that shown names are no longer unique (even when in reality they are)

For example:

![68891108-3c304180-06ee-11ea-9836-dc02fbaa049f](https://user-images.githubusercontent.com/15635386/68934000-c085d180-078d-11ea-8b7f-55c464ea2820.png)

Would it be possible to add to transfers output file names some unique ID? So output would look like that:

```
* 1: Elements/Elements/tmp/…EB-DL x265 RZeroX).mkv: 5% /2.212G, 860.607k/s, 42m18s
* 2: Elements/Elements/tmp/…EB-DL x265 RZeroX).mkv: 21% /2.217G, 1.242M/s, 23m51s
* 3: Elements/Elements/tmp/…EB-DL x265 RZeroX).mkv: 42% /2.234G,  1.118M/s, 19m41s
* 4: Elements/Elements/tmp/…EB-DL x265 RZeroX).mkv: 90% /2.245G, 1.307M/s, 2m47s
```

Important part would be to keep ID intact until transfer is finished so e.g. when transfer 3 finishes and new one starts it will have ID 3 as well.

**Comment by ncw** [comment]
Does this flag help?

      --stats-file-name-length int   Max file name length in stats. 0 for no limit (default 45)

If you set it to 0 then rclone won't truncate the file names.

**Comment by kapitainsky** [comment]
yeap.  then I can track individual files as all lines will be unique

**Comment by ncw** [comment]
Super :-)

I'll close this then.

**Comment by kapitainsky** [comment]
sorry. next time should study available options more carefully.

**Comment by ncw** [comment]
> sorry. next time should study available options more carefully.

Note that `rclone help flags <regexp>` is useful for grepping rclone's flags!

Note also 

```
$ rclone help flags .  | wc -l
377
```

So don't feel bad about missing it!
