### ISSUE TITLE
zsh autosuggests arguments

### ISSUE THREAD

**Issue by agncr** [rclone/rclone#3739]
#### What is the problem you are having with rclone?
After running "rclone genautocomplete zsh", rclone automatically suggests arguments (like --progress). So entering "rclone copy " and then hitting on tab it automatically adds a '-' and tries to show me all possible arguments. I can't chose a local file nor can i choose a storage. When a file exists in my actual dir (e.g. local_file.test) and i enter "rclone copy local_" and click on tab it won't autocomplete the filename. I'm just getting an "Completing `arg' ". I've had to manually enter the filename and/or storage.

I don't have this problem on bash. As long as i don't enter "-" it won't suggest me any arguments and i can choose from my storages in my rclone config or choose a local file and autocomplete its name.

#### What is your rclone version (output from `rclone version`)
rclone v1.50.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 19.10 (zsh 5.7.1)
Debian Bullseye (zsh 5.7.1)

#### How i tested 
Create new container in Docker (debian:bullseye, ubuntu:eoan, ubuntu:disco)
apt update && apt install -y zsh  curl  unzip
adduser test --shell /usr/bin/zsh
curl https://rclone.org/install.sh | bash
rclone genautocomplete zsh
su test (tested with nothing in .zshrc and populated by zsh's recommended settings (choosing 2 after login))
rclone copy \<tab\> (it shows "-" and tries to list all arguments)

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy \<tab\>

**Comment by ncw** [comment]
When I try it on my local machine I get a different incorrect behaviour - it won't complete any commands only local files even if I type `-`.

There are a few issues open about zsh completion in cobra (the library rclone uses): eg https://github.com/spf13/cobra/issues/881

It might be worth you looking through those for some insights...

**Comment by xaque** [comment]
I am having the same behavior as agncr. With default installation, rclone package provides `/usr/share/zsh/site-functions/_rclone` for autocompletion. Both this file and the one generated by `rclone genautocomplete zsh` have the same issue.

I downloaded an old version of rclone that looked like it could be older than the cobra issue mentioned, generated the autocomplete file, and loaded it with my installed version of rclone (1.50.2) and it is able to autocomplete local paths and rclone commands but not flags.
e.g
`rclone cop<tab>`
`rclone copy`
`rclone copy De<tab>`
`rclone copy Desktop/`
autocompletes fine, but
`rclone copy --dry<tab>`
shows no autocomplete

It seems the change in behavior happens between v1.48.0 and v1.49.0.

**Comment by Cnly** [comment]
I'm unable to reproduce this on 1.56. Perhaps this is now something fixed? Please feel free to comment or reopen if it isn't.

**Comment by xaque** [comment]
Awesome, autocompletion is working as expected for me on v1.56 as well now
