### ISSUE TITLE
Failed to create file system for "mega2:dev": couldn't login: crypto/aes: invalid key size 0

### ISSUE THREAD

**Issue by khubenbecker** [rclone/rclone#3740]
#### What is the problem you are having with rclone?

I have a Mega.nz business plan with 3 accounts, to test rclone, and installing in our system I added an account with "rclone config", all commandos worked as desired.

Now I've added 2 other mega accounts from the same business plan, now works only 1 account without problems, the other 2 accounts have the following output for each command:

I tried the latest beta version without success.

`Failed to create file system for "mega:dev2": couldn't login: crypto/aes: invalid key size 0`

#### What is your rclone version (output from `rclone version`)

rclone v1.50.1-046-gb5bb4c2a-beta
- os/arch: linux/amd64
- go version: go1.13.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Distributor ID: Ubuntu, 64 bit
Description: Ubuntu 18.04.3 LTS
Release: 18.04
Codename: bionic

####  Which cloud storage system are you using? (eg Google Drive)

Mega.nz

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy /tmp/testfile.mp4 mega:dev

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2019/11/15 14:27:21 DEBUG : rclone: Version "v1.50.1-046-gb5bb4c2a-beta" starting with parameters ["rclone" "ls" "mega1:" "-vv"]
2019/11/15 14:27:21 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2019/11/15 14:27:22 Failed to create file system for "mega1:": couldn't login: crypto/aes: invalid key size 0

**Comment by ncw** [comment]
Can you email me ( nick@craig-wood.com ) the result of `rclone ls mega1: -vv --dump bodies` please with a link to this issue please?  Then I can try to work out what is going on.

The mega protocol was reverse engineered from their C++ program so there are still a few rough edges.

I note also that it is possible to use rclone with the webdav backend and the mega tools- see: https://github.com/rclone/rclone/issues/3660

**Comment by khubenbecker** [comment]
> Can you email me ( [nick@craig-wood.com](mailto:nick@craig-wood.com) ) the result of `rclone ls mega1: -vv --dump bodies` please with a link to this issue please? Then I can try to work out what is going on.
> 
> The mega protocol was reverse engineered from their C++ program so there are still a few rough edges.
> 
> I note also that it is possible to use rclone with the webdav backend and the mega tools- see: #3660

I sent you the issue by e-mail, thank you.

The rclone with the webdav backend can be used, I had seen, only there is currently the problem that you can not use several mega remotes, see: https://github.com/rclone/rclone/issues/3660#issuecomment- 548969666

**Comment by ncw** [comment]
Thanks for the log.

I can see that the login works and mega has sent you the file system listing.  It looks like rclone failed to decode one of the entries though and blew up.

Here is a test binary which will carry on after a decoding failure, logging `"couldn't decode FSNode %+v: %v "`.  It might be that there is only 1 or a few nodes which rclone doesn't understand in which case I think this will be a good fix.  Or it might be that they all don't work!

If you could run this and send me the log with `-vv` - I don't think I'll need `--dump bodies` this time.

https://beta.rclone.org/branch/v1.50.1-048-g18444676-fix-3740-mega-decode-beta/ (uploaded in 15-30 mins)

> The rclone with the webdav backend can be used, I had seen, only there is currently the problem that you can not use several mega remotes, see: #3660 (comment) 548969666

I think that is a solvable problem - I just haven't put any effort into it yet!

**Comment by khubenbecker** [comment]
Glad to hear, thanks for the fast processing.

I need a release for Linux "-linux-amd64.deb", that is currently missing unfortunately, you can upload the file please.

A solution for https://github.com/rclone/rclone/issues/3660, would be very nice, the transfer rate should be much better, if you find time for it.

thx

**Comment by ncw** [comment]
The build failed, I've given it a kick - hopefully the binary will be there in 15-30 mins!

**Comment by khubenbecker** [comment]
Great thanks, it works so far everything, in Verbose are still errors included.

Have you sent the code by mail.

**Comment by ncw** [comment]
Thanks for the log - got it!

This appeared to drop 634 items from the listing.  Do you know what was missing? Maybe a shared folder or something like that?

Did the other items list OK?

**Comment by ncw** [comment]
A bit of looking through the source code makes me think that the missing files are Shared files.  Is that correct?

**Comment by ncw** [comment]
I did a deeper analysis...

The files that are missing are shared files, however the decryption key has gone.  It looks like the owner has been deleted.  So I think it is OK to skip these files.

Can you give this a go - this should skip the troublesome shared files.

If it works OK for you I'll merge it into the mega library and pull it back into rclone.

https://beta.rclone.org/branch/v1.50.2-057-gc48424c0-fix-3740-mega-decode-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
Did you have a go with the above code?

**Comment by ncw** [comment]
I've merged this into the mega library now, so I'm going to close this
