### ISSUE TITLE
GoogleDrive Server Side move adds spurious . to file and folder IDs

### ISSUE THREAD

**Issue by BazzaCuda** [rclone/rclone#3741]
#### What is the problem you are having with rclone?
A server-side move between two Google Drives adds a spurious . to the end of the file and folder IDs and consequently reports the source files and folders as 404 - not found.
Adding --dry-run, rclone correctly lists all the files it would have moved.
Removing the --drive-server-side-across-configs works but is obviously doing a download/upload operation.
All the IDs it reports are correct except for the spurious .  in the error message (see attached log file)

Bizarrely, it correctly creates the source folder/subfolder structure on the destination drive before then reporting that it can't find the source folders and files.

#### What is your rclone version (output from `rclone version`)
v1.50.1-046-gb5bb4c2a-beta

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 Pro 64-bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone move bn:AudioLibrary\.local\.mapper\.files\.y bo:AudioLibrary\.local\.mapper\.files\.y --progress -vv --log-file=log.txt

The source folder ".y" contains the following files:
yamsee.db
yard.db

and a "youtube" subfolder containing:
yt01.db
yt02.db
yt03.db

You can see these all mentioned in the log file.
I've included the first few log entries where I'd removed the --drive-server-side-across-configs option and it was doing a standard move, just to show that removing the option was the only change to the command and suddenly rclone was able to find the source folders and files.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
attached, showing
1. server side move command with --dry-run: lists folders and files correctly
2. same command but with --dry-run removed: correct IDs plus "." 
3. same command but with --drive-server-side-across-configs removed: works.
[log.txt](https://github.com/rclone/rclone/files/3851935/log.txt)

Please note, in the first error line in the log file, trying to move the yamsee.db file, the reported ID is for the ".y" folder

2019/11/15 14:26:22 ERROR : yamsee.db: Couldn't move: googleapi: Error 404: File not found: 174DCpp82TMcVtq5z0jTU1YILy3E8VIlA., notFound

Actually, all the reported IDs are for the two source .folders:
.y = 174DCpp82TMcVtq5z0jTU1YILy3E8VIlA + .
youtube = 1Hu7g0yenFvQj9IgbC0kejmU5akrSivn0 + .

**Comment by BazzaCuda** [comment]
Please, in the first error line, trying to move the yamsee.db file, the reported ID is for the ".y" folder

2019/11/15 14:26:22 ERROR : yamsee.db: Couldn't move: googleapi: Error 404: File not found: 174DCpp82TMcVtq5z0jTU1YILy3E8VIlA., notFound

**Comment by ncw** [comment]
> 2019/11/15 14:26:22 ERROR : yamsee.db: Couldn't move: googleapi: Error 404: File not found: 174DCpp82TMcVtq5z0jTU1YILy3E8VIlA., notFound

This 404 error (very confusingly) means that the user for the destination drive does not have permission to read files from the source drive.

If you remove --drive-server-side-across-configs then rclone will do a download then upload.

So can you give the user for the destination drive permissions to access the source drive? Try sharing the source files with the destination user.

> All the IDs it reports are correct except for the spurious . in the error message (see attached log file)

I think the spurious `.` is just that, it comes back from Google - here is the raw response which has the `.` on the end.

```
{"error":{"errors":[{"domain":"global","reason":"notFound","message":"File not found: 0ADSw5cyzKmgvUk9PVA.","locationType":"parameter","location":"fileId"}],"code":404,"message":"File not found: 0ADSw5cyzKmgvUk9PVA."}}
```

**Comment by BazzaCuda** [comment]
Ah, I see. Ok, thanks - I'll try altering the permissions. Thanks for your prompt response.

**Comment by BazzaCuda** [comment]
That's exactly what the problem was. I shared the ".y" folder with the other account with full edit permissions and the entire contents of the folder has moved. Easy when you know how isn't it :D
Thanks again.

**Comment by ncw** [comment]
Great!  I just wish that 404 message from google was a bit more informative - like permission denied or something like that!
