### ISSUE TITLE
Rclone is not following the root folder ID specified for a remote.

### ISSUE THREAD

**Issue by piratetub** [rclone/rclone#3742]
#### What is the problem you are having with rclone?
I'm Running Rclone on a headless Linux machine. rclone is not obeying the root folder ID I've specified in the config, for a Google Drive Team Drive "Shared Drive". To be clear, I'm running rclone with the exact same config on a Windows machine, and rclone follows the Root Folder ID perfectly fine.

#### What is your rclone version (output from `rclone version`)
rclone v1.50.1
- os/arch: linux/amd64
- go version: go1.13.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 18.04.3 LTS 

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive ("Shared Drive" to be more specific)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
N/A (All commands exhibit the same behavior since rclone is somehow disregarding the root folder ID I've provided)

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
N/A

**Comment by ncw** [comment]
Can you paste your config with the secrets in it XXXed out please?

I think for a team drive you'll need to put the root_folder_id into the `team_drive` config value - not sure.

**Comment by piratetub** [comment]
Hi Nick, thanks for the response! I've pasted below my config file with all the credentials and non-important remotes struck off.
I should also emphasize that this config file **works correctly on Windows**, so the issue seems to be with the Linux build for rclone. 
```
[shared]
type = drive
keep_revision_forever = true
server_side_across_configs = true
client_id = XX
client_secret = XX
scope = drive
token = XXX
team_drive = XXX
root_folder_id = 28dxxxxxxxxxxxxxxxxx

[shared_crypt]
type = crypt
remote = X:e
filename_encryption = standard
directory_name_encryption = true
password = XXX
password2 = XXX


[drive]
type = drive
server_side_across_configs = true
client_id = XX
client_secret = XX
scope = drive
root_folder_id = 17jxxxxxxxxxxxx
token = XXX
```

**Comment by ncw** [comment]
I managed to replicate this....  It is a regression from v1.49.5

Git bisect indicates that this is the problem ba7c2ac443233ec4b73eed1054bd68c59eb3d8dd

I had a go at fixing this here

https://beta.rclone.org/branch/v1.50.1-047-g19229b12-fix-3742-team-drive-root-beta/ (uploaded in 15-30 mins)

If it checks out for you I'll stick this in a point release

> I should also emphasize that this config file **works correctly on Windows**, pointing to my intended root folder, so the issue seems to be just with the Linux build for rclone.

Can you double check that the config is the same on Windows and Linux and that you are using the same rclone versions in both places?

I find it very hard to understand how there could be an OS dependent difference!

**Comment by piratetub** [comment]
I'm glad it could be replicated on your end!

> Can you double check that the config is the same on Windows and Linux and that you are using the same rclone versions in both places?

Turns out on my Windows machine, I'd been using **V1.49.4** for rclone, which as it appears is 1 release behind the point the regression showed up! I apologize if that was confusing as I didn't before consider that the issue could've manifested through a recent change.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.51

I'll put it in a point release v1.50.2 also

**Comment by ncw** [comment]
Thanks for testing :-)

**Comment by ltkun** [comment]
My rclone version is 1.50.2. It still has this bug which is from Ubuntu 20.04.

**Comment by Yexiaoxing** [comment]
@ltkun Hi could you please open a new issue and give us some more details (as indicated in issue template), instead of raising in a closed issue? Thanks :)
