### ISSUE TITLE
Bug when listing directories

### ISSUE THREAD

**Issue by LeoSpyke96** [rclone/rclone#3746]
#### What is the problem you are having with rclone?
Error got while trying to listing a remote structure.

2019/11/18 14:17:45 ERROR : : error listing: directory not found
2019/11/18 14:17:46 Failed to tree with 2 errors: last error was: directory not found

#### What is your rclone version (output from `rclone version`)
rclone v1.50.1
- os/arch: windows/amd64
- go version: go1.13.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 Pro 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive with a crypt remote

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
Any `ls*`, `tree` command for listing directories

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
My remote is called "A:" and it perfectly works on Linux (tested with Debian and Raspbian). 
I tried to rename it with a name more than 1 char long (ex. "Ac"), and it worked on Windows 10 too.
So, apparently, there is a bug with remotes' name one char long on Windows.

Here the -vv command:
2019/11/18 14:20:45 DEBUG : rclone: Version "v1.50.1" starting with parameters ["C:\\rclone\\rclone.exe" "tree" "A:/" "--max-depth=1" "-vv"]
2019/11/18 14:20:46 DEBUG : Using config file from "C:\\Users\\Leonardo\\.config\\rclone\\rclone.conf"
2019/11/18 14:20:46 ERROR : : error listing: directory not found
2019/11/18 14:20:46 Failed to tree with 2 errors: last error was: directory not found

**Comment by ncw** [comment]
Yes, you can't have single letter remotes on Windows as these can be confused with drive names, eg `C:`.

**Comment by animosity22** [comment]
Looks to be solved. If you have a new question, please ask on the forums.
