### ISSUE TITLE
Add a --description flag to set description for uploaded files for capable remotes (eg drive)

### ISSUE THREAD

**Issue by canonlp** [rclone/rclone#375]
I haven't seen anything in the documentation about it, and I'm not sure if it is possible, but is there support for changing or adding custom descriptions to files?

**Comment by ncw** [comment]
There isn't at the moment. What would you like to see?

I could imagine passing in a `--description ` flag which set the description for all files uploaded in one session?

**Comment by canonlp** [comment]
Yes, that would work. Currently I think it does add a description, but that description is the name of the file but no way of changing it.

**Comment by ncw** [comment]
I was confusing drive with one of the other cloud storage systems.  In drive the file name is the description - and I don't think there isn't any other sort of description or comment you can set

Here is a list of things you can set on a file

https://developers.google.com/drive/v3/reference/files

So I don't think this is possible with drive.

**Comment by canonlp** [comment]
Just had a look at the API, wouldn't it be this?:

description	string	A short description of the file.	writable

**Comment by ncw** [comment]
Yes you are right!  Looking at the code we set the Name (called Title in v2 API) to the name of the file.  This is the name you see when you look at the drive web interface.  We also set the Description to the name of the file.

So my original idea of a `--description` flag would work just fine!

Sorry for the confusion!

**Comment by robjlg** [comment]
The original Nick's idea of --description flag is good and I had envisaged an use for this.

Now I was thinking about another use. I use posix ACL to control users access to files and I have to save it (using getfacl) on text file for backup when syncing files to DRIVE.

It would be very useful if RCLONE (in sync or copy) could, for each file or folder to be transferred,  get it's ACL (getfacl) and store it as description.  And also, restore it (setfacl) when  syncing back.

I manually tested if DRIVE description could handle a very long getfacl output and yes, it can. Then I did a restore test like bellow

echo -e  "ACL RETRIEVED FROM DESCRIPTION"  |  setfacl --set-file-  TST

and that worked well.  Please see below my test commands:

1 - Get ACL and store it on DRIVE

drive  edit-desc --description "`getfacl   Estagiarios`"  -id 0BzCak_XXXXX

2 - Make a local test folder

mkdir   tst

3 - Retrieve the ACL stored on DRIVE file description

ACL=$(drive stat  -id 0BzCak_XXXXX   |   grep Description |  awk -F ' '  '{$1=""; print $0}' | sed 's/"//g')

4 - Set test folder's ACL

echo -e $ACL   |   setfacl --set-file=-    tst


But this would generate too much programming work to ask for. Maybe a more workable solution that would allow me (and others) to be able to make scripts for post processing based on an special new log that RCLONE  could generate.

This special log  could list all updated files and folders local name and remote id in a format that could be easily processed. Like below

"TST/"                                                0BzCak_XXXXXzzzzz
"TST/FOLDER  2"                               0BzCYk_VVVAAzzzz
"TST/FOLDER  2/FILE_1.TXT"           0BzCRk_TTBAAzzzz
"TST/FOLDER  2/FILE_2.TXT"           0BzCSk_FFAAzzzz

This option could be    --transfer-log 

This would allow us to do a lot of post processing  on the transferred files and folders

Thank you very much  for  your  RCLONE program and your attention 

Roberto

**Comment by YenForYang** [comment]
Not sure how things are exactly in Go, but in Java, _for uploading_, this is done using v3 API like so:

```javascript
var fileMetadata = new com.google.api.services.drive.model.File() // fully qualified name here for illustration
                          .setName("photo.jpg")
                          .setDescription("This is a description");

var mediaContent = new com.google.api.client.http.FileContent(
                     "image/jpeg", new java.io.File("path/to/file.jpg"));
var response = driveService.files().create(fileMetadata, mediaContent).execute();
```
**EDIT:**
Actually, from what I can make out, it seems to be that the description is already being set (to be the same as the name):

https://github.com/ncw/rclone/blob/7712a0e111c7a37571f3fb796fe29dd9f44e5cfa/backend/drive/drive.go#L773-L779
https://github.com/ncw/rclone/blob/7712a0e111c7a37571f3fb796fe29dd9f44e5cfa/backend/drive/drive.go#L1128-L1135

Maybe, for starters, a flag for setting the description of a new file/folder upload could be made (i.e. an option to change the value of `Description` above)

**Comment by ncw** [comment]
Does anyone want to have a go at this?

A backend specific flag might be easier, eg `--drive-description`?

**Comment by animosity22** [comment]
This looks pretty stale so closing out as it doesn't seem to have any takers. Let me know and I can always re-open.

Thanks!
