### ISSUE TITLE
Oauth2 using passwordCredentials supported?

### ISSUE THREAD

**Issue by clearcodecn** [rclone/rclone#3750]
#### What is your current rclone version (output from `rclone version`)?
build from source 

#### What problem are you are trying to solve?
I want to sync my server files into onedrive. The problem I face to is that:
1. microsoft now only can add platforms with `https` schema
2. `http://localhost:53768/auth`  seems does't work in this scene. 
3. I have tried to using this code to get my access_token, and it works when I refresh them every one hour in a goroutine. : 
```
	config := oauth2.Config{
		ClientID:     "client_id",
		ClientSecret: "client_secret",
		Endpoint:     microsoft.AzureADEndpoint(`organizations`),
		RedirectURL:  "",
		Scopes:       []string{"Files.ReadWrite.All"},
	}

	token, _ := config.PasswordCredentialsToken(context.Background(), `my username`, `my password`)
	d, _ := json.Marshal(token)
	os.Stdout.Write(d)
```
this can provide my token: 
```
{"access_token":"token","token_type":"Bearer","expiry":"2019-11-20T00:15:24.8193429+08:00"}

// I don't know why microsoft don't return refresh_token. whether I using password credentials or code credentials.  
```
4. I can not refresh my access_token. 

#### How do you think rclone should be changed to solve that?
If rclone can support `passwordCredentials` I only should provide my username & password then I can get my access_token easier.

**Comment by ncw** [comment]
The redirect URL should be just `http://localhost:53682/` I think. I have that configured in my onedrive app.

If you want to use an https one then you can use `https://oauth.rclone.org` which redirects to the localhost URL.

**Comment by clearcodecn** [comment]
@ncw that's cool. 
`https://oauth.rclone.org`  is greate. 

![image](https://user-images.githubusercontent.com/34591322/69305492-a3457d00-0c3d-11ea-9f82-1c9a03baf2b7.png)

**Comment by clearcodecn** [comment]
but there are no refresh token. 
how can I refresh them by this way ? @ncw
