### ISSUE TITLE
Webdav with BEARER token does not work

### ISSUE THREAD

**Issue by appanp** [rclone/rclone#3751]
#### What is the problem you are having with rclone?

Accessing Apache based webdav server with bearer token gives "401 Authorization Required" error. I tried the same PROPFIND command using curl but with header as "Bearer: <bearer-token>" and it works, but if I change it to all-caps BEARER, it gives error.

#### What is your rclone version (output from `rclone version`)

rclone v1.49.1
- os/arch: linux/amd64
- go version: go1.12.9

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu, 64-bit

####  Which cloud storage system are you using? (eg Google Drive)

Proprietary, Salesforce Webdav server

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync <remote> <dest-dir> -P --webdav-bearer-token <my-bearer-tkn>

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2019/11/20 23:33:27 DEBUG : HTTP REQUEST (req 0xc000192100)
2019/11/20 23:33:27 DEBUG : PROPFIND /on/demandware.servlet/webdav/Sites/Logs/ HTTP/1.1^M
Host: <host-name>
User-Agent: rclone/v1.49.1
Authorization: BEARER 58147ecb-be4c-42be-a76b-8aefa76ed02d
Depth: 1
Accept-Encoding: gzip

2019/11/20 23:33:27 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/20 23:33:28 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/20 23:33:28 DEBUG : HTTP RESPONSE (req 0xc000192100)
2019/11/20 23:33:28 DEBUG : HTTP/1.1 401 ^M

**Comment by ncw** [comment]
[The RFC](https://tools.ietf.org/html/rfc6750#section-2.1) is quite specific about the case of `Bearer` in the examples so I think `BEARER` is a bug!

Can you give this a go?

https://beta.rclone.org/branch/v1.50.2-057-g77723ed9-fix-3751-webdav-bearer-beta/ (uploaded in 15-30 mins)

**Comment by appanp** [comment]
Yes, this fixes the problem. Thank you for a quick turn-around !!

**Comment by ncw** [comment]
Thanks for testing :-)

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.51
