### ISSUE TITLE
asyncread: WriteTo EOF

### ISSUE THREAD

**Issue by buengese** [rclone/rclone#3752]
While debugging some stuff related to my mirror backend I noticed an inexplicable EOF error from io.Copy(). Looking into it this appears to be caused by rclone's asyncreader.WriteTo() method. The documentation for io.Copy() states that a successful copy should be indicated by err == nil and not err == EOF. When WriteTo() is available io.Copy() directly propagates the error from WriteTo(). So I don't think asyncreader.WriteTo() should return an EOF error.

@ncw

**Comment by ncw** [comment]
Well spotted.

Want to send a fix?

**Comment by buengese** [comment]
Sure

**Comment by ncw** [comment]
I found [the official docs](https://golang.org/pkg/io/#WriterTo)

> WriterTo is the interface that wraps the WriteTo method.
>
> WriteTo writes data to w until there's no more data to write or when an error occurs. The return value n is the number of bytes written. Any error encountered during the write is also returned.

I think `until there's no more data to write` is a strong indicator that it should never return io.EOF.

**Comment by ncw** [comment]
This is fixed now - thank you @buengese :-)
