### ISSUE TITLE
[AWS] Support assume role via AWS_WEB_IDENTITY_TOKEN_FILE and AWS_ROLE_ARN environment variables when running on EKS

### ISSUE THREAD

**Issue by jlerche** [rclone/rclone#3753]
#### What is your current rclone version (output from `rclone version`)?
```
# ./rclone version
rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.4
```

#### What problem are you are trying to solve?
We run workloads on AWS EKS using [IAM roles for (kubernetes) service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html). When a kubernetes pod runs under a (kubernetes) service account with this feature, two environment variables get populated automatically:
```
# env | grep AWS
AWS_ROLE_ARN=<snip>
AWS_WEB_IDENTITY_TOKEN_FILE=<snip>
```
which can then be used to authenticate.

#### How do you think rclone should be changed to solve that?
As of https://github.com/rclone/rclone/commit/479c803fd9034a38d01be0aa8c55a8881b01406c#diff-37aff102a57d3d7b797f152915a6dc16 the aws sdk in `go.mod` supports this feature (we use it in our own code). It would be great if `rclone` could support it as well. With this feature supported, I would expect a minimal config like:
```
[remote]
type = s3
provider = AWS
env_auth = true
region = us-west-2
```
to work, assuming the two environment variables listed above are populated with valid values.

In principle, creating a provider via [`stscreds.NewWebIdentityRoleProvider`](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/stscreds/#NewWebIdentityRoleProvider) and adding it to the [credentials provider chain here](https://github.com/rclone/rclone/blob/master/backend/s3/s3.go#L954) should work.

**Comment by ncw** [comment]
Would you like to send a pull request for this?

I recently updated the SDK in master so it should just be a matter of adding that?

**Comment by ncw** [comment]
This is fixed now so will close this issue.
