### ISSUE TITLE
Small update to the commands page

### ISSUE THREAD

**Issue by ljk5403** [rclone/rclone#3756]
When I read the commands page for [rclone copy](https://rclone.org/commands/rclone_copy/), I found an example that tell me add --no-traverse to speed up copy. However, when I practice it I get a massage says that "NOTICE: --no-traverse is obsolete and no longer needed - please remove", so maybe we should remove that example?

Just a suggestion, if there is no need, just close this issue🤣

**Comment by ncw** [comment]
I suspect you are using an old version of rclone - what does `rclone version` say?

**Comment by ljk5403** [comment]
Oh you are right, I just upgraded my rclone to newest due to some other problems few days ago, and I can not get this notification anymore. Thank you a lot!

**Comment by ljk5403** [comment]
> I suspect you are using an old version of rclone - what does `rclone version` say?

Oh you are right, I just upgraded my rclone to newest due to some other problems few days ago, and I can not get this notification anymore. Thank you a lot!
