### ISSUE TITLE
[Question] Can you sync 2 google photo accounts?

### ISSUE THREAD

**Issue by eihns** [rclone/rclone#3760]
Hey, before i try and destroy everything...

Is it possible to sync 2 Google photo accounts?

Because problem atm is, we want to have same gallery, it does work except that if you delete something, it wont get deleted from the 2. account. 

So i thought i sync the 1. account to the 2. account (so that account 2 has the same items as acc 1?)

rclone sync "Google Fotos sync1":/ "Google Fotos sync2":/

will that work?

**Comment by ncw** [comment]
`sync` only works well with albums in google photos because you can't delete folders.  So if you put all the photos you want synced in an album then

    rclone sync "Google Fotos sync1":album/albumname "Google Fotos sync2":album/albumname

should work.

Try with --dry-run first!

**Comment by eihns** [comment]
No, i dont want to sync albums (or lets say, that is not needed bc album sync seems to work just fine) (in the way that album on acc1 and acc2 look the same)

I want to have the stream of pictures under https://photos.google.com/ the same on both accounts. Like if acc1 delete picture, on acc2 it also get deleted, so we see the same.. you know?

**Comment by eihns** [comment]
Is that possible? Or not becasue you cant delete via rclone?

**Comment by ncw** [comment]
> No, i dont want to sync albums (or lets say, that is not needed bc album sync seems to work just fine) (in the way that album on acc1 and acc2 look the same)
> 
> I want to have the stream of pictures under https://photos.google.com/ the same on both accounts. Like if acc1 delete picture, on acc2 it also get deleted, so we see the same.. you know?
> 
> Is that possible?

Unless you put it in an album rclone can't delete things.  However deleting files from an album doesn't actually delete the media.  There is no way via the API to permanently delete media :-(

Things in albums do appear in the main stream of photos though so maybe you could make something work that was good enough.

Trying to sync things outside of albums is not going to work as it is as rclone doesn't have enough control via the API.

If you didn't want to sync deletes too then what you want might be possible via the API.

**Comment by eihns** [comment]
I cant understand why google is not doing what it says.

I have connected 2 accounts and share everything.

I go to a picture and click remove. Google says it delete it on all platforms/devices...  BUT ITS NOT... xD

If youre sharing something, dont you want that both of the accs have the same data?!?! 

But thanks for clarifying that this is not possible with rclone.
