### ISSUE TITLE
Problems with folder name contains "：" on Windows.

### ISSUE THREAD

**Issue by axzxc1236** [rclone/rclone#3761]
#### What is the problem you are having with rclone?

When you have folder with "：" you can't access the folder with `rclone ncdu` or copy the folder. (you can however access the parent directory and then navigate to the problematic folder)

#### What is your rclone version (output from `rclone version`)

Tested on Windows: 1.50.1, 1.50.2-059-g1db31d71-beta

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10 1903 64bit

Can't replicate on Ubuntu 16.04.

####  Which cloud storage system are you using? (eg Google Drive)

local harddrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone ncdu "test：a"

(or cd into "test：a" and do rclone ncdu .)

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

> 2019/11/24 20:33:17 ERROR : : error listing: directory not found

terminal is cleared so the log isn't useful...

I've ran `mkdir "test：a"` before running that command so folder "test：a" does exist.

**Comment by geart891** [comment]
I think this is the restriction that windows puts on all directory names. IMO, your best bet is to rename the folder before copy it in windows platform.

**Comment by ncw** [comment]
I think this is the same issue as #3723

The work-around would be to add a ‛ before the ： so

rclone ncdu "test‛：a"

I need to think of a work-around for this!

**Comment by ncw** [comment]
Please can you try this with the `--local-encoding None` flag?  You can put that as `encoding = None` in your config.

That disables the character name conversion and should fix the problem for you.

https://beta.rclone.org/branch/v1.50.2-140-g222f1e7d-fix-encodings-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.51
