### ISSUE TITLE
pcloud error 410

### ISSUE THREAD

**Issue by cyayon** [rclone/rclone#3764]
Hello,

I am unable to copy/sync pcloud.
I get an error : 
toto.txt: Failed to copy: failed to open source object: pcloud error: 410 Gone (410)

here is the log  :  

2019/11/26 08:45:58 DEBUG : rclone: Version "v1.50.2" starting with parameters ["/usr/bin/rclone" "copy" "-vv" "--config" "/etc/rclone.conf" "pcloud_xxx:/" "."]
2019/11/26 08:45:58 DEBUG : Using config file from "/etc/rclone.conf"
2019/11/26 08:46:00 INFO  : Local file system at /mnt/volbak/backup/datas/pcloud: Waiting for checks to finish
2019/11/26 08:46:00 INFO  : Local file system at /mnt/volbak/backup/datas/pcloud/: Waiting for transfers to finish
2019/11/26 08:46:00 DEBUG : Couldn't parse Date: from server p-par1.pcloud.com: "Tue, 26 Nov 2019 07:46:00 +0000": parsing time "Tue, 26 Nov 2019 07:46:00 +0000" as "Mon Jan _2 15:04:05 2006": cannot parse ", 26 Nov 2019 07:46:00 +0000" as " "
2019/11/26 08:46:00 DEBUG : Couldn't decode error response: invalid character '<' looking for beginning of value
2019/11/26 08:46:00 ERROR : toto.txt: Failed to copy: failed to open source object: pcloud error: 410 Gone (410)
2019/11/26 08:46:00 DEBUG : Couldn't parse Date: from server p-par1.pcloud.com: "Tue, 26 Nov 2019 07:46:00 +0000": parsing time "Tue, 26 Nov 2019 07:46:00 +0000" as "Mon Jan _2 15:04:05 2006": cannot parse ", 26 Nov 2019 07:46:00 +0000" as " "
2019/11/26 08:46:00 DEBUG : Couldn't decode error response: invalid character '<' looking for beginning of value
2019/11/26 08:46:00 ERROR : windows-node_rev2.json: Failed to copy: failed to open source object: pcloud error: 410 Gone (410)
2019/11/26 08:46:00 ERROR : Attempt 1/3 failed with 5 errors and: failed to open source object: pcloud error: 410 Gone (410)
2019/11/26 08:46:01 INFO  : Local file system at /mnt/volbak/backup/datas/pcloud/: Waiting for checks to finish
2019/11/26 08:46:01 INFO  : Local file system at /mnt/volbak/backup/datas/pcloud/: Waiting for transfers to finish

Thanks.

**Comment by ncw** [comment]
Can you try to replicate this with a single file and post the output of this?

    /usr/bin/rclone copy -vv --dump bodies --retries 1 --low-level-retries 1 --config /etc/rclone.conf pcloud_xxx:/toto.txt .

Feel free to edit for privacy - thanks!

**Comment by cyayon** [comment]
Hi, 

thanks, here is the log : 


`2019/11/26 12:30:23 DEBUG : rclone: Version "v1.50.2" starting with parameters ["/usr/bin/rclone" "copy" "-vv" "--dump" "bodies" "--retries" "1" "--low-level-retries" "1" "--config" "/etc/rclone.conf" "pcloud_xxx:/toto.txt" "."]
2019/11/26 12:30:23 DEBUG : Using config file from "/etc/rclone.conf"
2019/11/26 12:30:23 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/26 12:30:23 DEBUG : HTTP REQUEST (req 0xc000615800)
2019/11/26 12:30:23 DEBUG : GET /listfolder?folderid=0 HTTP/1.1
Host: api.pcloud.com
User-Agent: rclone/v1.50.2
Authorization: XXXX
Accept-Encoding: gzip

2019/11/26 12:30:23 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/26 12:30:24 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/26 12:30:24 DEBUG : HTTP RESPONSE (req 0xc000615800)
2019/11/26 12:30:24 DEBUG : HTTP/1.1 200 OK
Connection: close
Cache-Control: private, max-age=0
Content-Type: application/json; charset=utf-8
Date: Tue, 26 Nov 2019 11:30:24 GMT
Etag: "BccTd74OTW0gYbX6Tj6a1ScYbjtX"
Server: CloudHTTPd-API v1.1
Vary: Accept-Encoding

{
	"result": 0,
	"metadata": {
		"path": "\/",
		"name": "\/",
		"created": "Thu, 09 Aug 2018 06:20:06 +0000",
		"ismine": true,
		"thumb": false,
		"modified": "Thu, 09 Aug 2018 06:20:06 +0000",
		"id": "d0",
		"isshared": false,
		"icon": "folder",
		"isfolder": true,
		"folderid": 0,
		"contents": [
			{
				"path": "\/Crypto Folder",
				"name": "Crypto Folder",
				"created": "Fri, 16 Nov 2018 18:39:54 +0000",
				"ismine": true,
				"thumb": false,
				"modified": "Fri, 05 Apr 2019 04:06:09 +0000",
				"comments": 0,
				"encrypted": true,
				"id": "d2458294616",
				"isshared": false,
				"icon": "folder",
				"isfolder": true,
				"parentfolderid": 0,
				"folderid": 2458294616
			},
			{
				"name": "toto.txt",
				"created": "Tue, 26 Nov 2019 07:16:38 +0000",
				"thumb": false,
				"modified": "Tue, 26 Nov 2019 07:16:38 +0000",
				"isfolder": false,
				"fileid": 17109536202,
				"hash": 2543652759283584763,
				"comments": 0,
				"path": "\/toto.txt",
				"category": 4,
				"id": "f17109536202",
				"isshared": false,
				"ismine": true,
				"size": 0,
				"parentfolderid": 0,
				"contenttype": "text\/plain",
				"icon": "document"
			},
			{
				"name": "windows-node_rev2.json",
				"created": "Tue, 16 Apr 2019 12:06:18 +0000",
				"thumb": false,
				"modified": "Tue, 16 Apr 2019 12:06:18 +0000",
				"isfolder": false,
				"fileid": 17109448575,
				"hash": 13293101707176146072,
				"comments": 0,
				"path": "\/windows-node_rev2.json",
				"category": 0,
				"id": "f17109448575",
				"isshared": false,
				"ismine": true,
				"size": 54197,
				"parentfolderid": 0,
				"contenttype": "application\/json",
				"icon": "file"
			}
		]
	}
}
2019/11/26 12:30:24 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/26 12:30:24 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/26 12:30:24 DEBUG : HTTP REQUEST (req 0xc000614900)
2019/11/26 12:30:24 DEBUG : GET /listfolder?folderid=0 HTTP/1.1
Host: api.pcloud.com
User-Agent: rclone/v1.50.2
Authorization: XXXX
Accept-Encoding: gzip

2019/11/26 12:30:24 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/26 12:30:25 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/26 12:30:25 DEBUG : HTTP RESPONSE (req 0xc000614900)
2019/11/26 12:30:25 DEBUG : HTTP/1.1 200 OK
Connection: close
Cache-Control: private, max-age=0
Content-Type: application/json; charset=utf-8
Date: Tue, 26 Nov 2019 11:30:25 GMT
Etag: "BccTd74OTW0gYbX6Tj6a1ScYbjtX"
Server: CloudHTTPd-API v1.1
Vary: Accept-Encoding

{
	"result": 0,
	"metadata": {
		"path": "\/",
		"name": "\/",
		"created": "Thu, 09 Aug 2018 06:20:06 +0000",
		"ismine": true,
		"thumb": false,
		"modified": "Thu, 09 Aug 2018 06:20:06 +0000",
		"id": "d0",
		"isshared": false,
		"icon": "folder",
		"isfolder": true,
		"folderid": 0,
		"contents": [
			{
				"path": "\/Crypto Folder",
				"name": "Crypto Folder",
				"created": "Fri, 16 Nov 2018 18:39:54 +0000",
				"ismine": true,
				"thumb": false,
				"modified": "Fri, 05 Apr 2019 04:06:09 +0000",
				"comments": 0,
				"encrypted": true,
				"id": "d2458294616",
				"isshared": false,
				"icon": "folder",
				"isfolder": true,
				"parentfolderid": 0,
				"folderid": 2458294616
			},
			{
				"name": "toto.txt",
				"created": "Tue, 26 Nov 2019 07:16:38 +0000",
				"thumb": false,
				"modified": "Tue, 26 Nov 2019 07:16:38 +0000",
				"isfolder": false,
				"fileid": 17109536202,
				"hash": 2543652759283584763,
				"comments": 0,
				"path": "\/toto.txt",
				"category": 4,
				"id": "f17109536202",
				"isshared": false,
				"ismine": true,
				"size": 0,
				"parentfolderid": 0,
				"contenttype": "text\/plain",
				"icon": "document"
			},
			{
				"name": "windows-node_rev2.json",
				"created": "Tue, 16 Apr 2019 12:06:18 +0000",
				"thumb": false,
				"modified": "Tue, 16 Apr 2019 12:06:18 +0000",
				"isfolder": false,
				"fileid": 17109448575,
				"hash": 13293101707176146072,
				"comments": 0,
				"path": "\/windows-node_rev2.json",
				"category": 0,
				"id": "f17109448575",
				"isshared": false,
				"ismine": true,
				"size": 54197,
				"parentfolderid": 0,
				"contenttype": "application\/json",
				"icon": "file"
			}
		]
	}
}
2019/11/26 12:30:25 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/26 12:30:25 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/26 12:30:25 DEBUG : HTTP REQUEST (req 0xc0004f8900)
2019/11/26 12:30:25 DEBUG : GET /listfolder?folderid=0 HTTP/1.1
Host: api.pcloud.com
User-Agent: rclone/v1.50.2
Authorization: XXXX
Accept-Encoding: gzip

2019/11/26 12:30:25 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/26 12:30:26 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/26 12:30:26 DEBUG : HTTP RESPONSE (req 0xc0004f8900)
2019/11/26 12:30:26 DEBUG : HTTP/1.1 200 OK
Connection: close
Cache-Control: private, max-age=0
Content-Type: application/json; charset=utf-8
Date: Tue, 26 Nov 2019 11:30:26 GMT
Etag: "BccTd74OTW0gYbX6Tj6a1ScYbjtX"
Server: CloudHTTPd-API v1.1
Vary: Accept-Encoding

{
	"result": 0,
	"metadata": {
		"path": "\/",
		"name": "\/",
		"created": "Thu, 09 Aug 2018 06:20:06 +0000",
		"ismine": true,
		"thumb": false,
		"modified": "Thu, 09 Aug 2018 06:20:06 +0000",
		"id": "d0",
		"isshared": false,
		"icon": "folder",
		"isfolder": true,
		"folderid": 0,
		"contents": [
			{
				"path": "\/Crypto Folder",
				"name": "Crypto Folder",
				"created": "Fri, 16 Nov 2018 18:39:54 +0000",
				"ismine": true,
				"thumb": false,
				"modified": "Fri, 05 Apr 2019 04:06:09 +0000",
				"comments": 0,
				"encrypted": true,
				"id": "d2458294616",
				"isshared": false,
				"icon": "folder",
				"isfolder": true,
				"parentfolderid": 0,
				"folderid": 2458294616
			},
			{
				"name": "toto.txt",
				"created": "Tue, 26 Nov 2019 07:16:38 +0000",
				"thumb": false,
				"modified": "Tue, 26 Nov 2019 07:16:38 +0000",
				"isfolder": false,
				"fileid": 17109536202,
				"hash": 2543652759283584763,
				"comments": 0,
				"path": "\/toto.txt",
				"category": 4,
				"id": "f17109536202",
				"isshared": false,
				"ismine": true,
				"size": 0,
				"parentfolderid": 0,
				"contenttype": "text\/plain",
				"icon": "document"
			},
			{
				"name": "windows-node_rev2.json",
				"created": "Tue, 16 Apr 2019 12:06:18 +0000",
				"thumb": false,
				"modified": "Tue, 16 Apr 2019 12:06:18 +0000",
				"isfolder": false,
				"fileid": 17109448575,
				"hash": 13293101707176146072,
				"comments": 0,
				"path": "\/windows-node_rev2.json",
				"category": 0,
				"id": "f17109448575",
				"isshared": false,
				"ismine": true,
				"size": 54197,
				"parentfolderid": 0,
				"contenttype": "application\/json",
				"icon": "file"
			}
		]
	}
}
2019/11/26 12:30:26 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/26 12:30:26 DEBUG : toto.txt: Need to transfer - File not found at Destination
2019/11/26 12:30:26 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/26 12:30:26 DEBUG : HTTP REQUEST (req 0xc000866200)
2019/11/26 12:30:26 DEBUG : GET /getfilelink?fileid=17109536202 HTTP/1.1
Host: api.pcloud.com
User-Agent: rclone/v1.50.2
Authorization: XXXX
Accept-Encoding: gzip

2019/11/26 12:30:26 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/26 12:30:27 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/26 12:30:27 DEBUG : HTTP RESPONSE (req 0xc000866200)
2019/11/26 12:30:27 DEBUG : HTTP/1.1 200 OK
Connection: close
Content-Length: 299
Cache-Control: private, max-age=0
Content-Type: application/json; charset=utf-8
Date: Tue, 26 Nov 2019 11:30:26 GMT
Etag: "mSVMoGcuQ8FmlXIh6vMsG8c8n0o7"
Server: CloudHTTPd-API v1.1
Vary: Accept-Encoding

{
	"result": 0,
	"dwltag": "2mtCFYe8a6Ypia0Tx2x4by",
	"hash": 2543652759283584763,
	"size": 0,
	"expires": "Tue, 26 Nov 2019 17:30:26 +0000",
	"path": "\/DLZZkxdd8hZ2rzAZZ5qcqN7Zg0ZZqFRZZZlVZbVZGXZCvmsRCgRCzzUhHk61PIuhR2XxRD7\/toto.txt",
	"hosts": [
		"p-par1.pcloud.com",
		"p-ams1.pcloud.com"
	]
}
2019/11/26 12:30:27 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/26 12:30:27 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/26 12:30:27 DEBUG : HTTP REQUEST (req 0xc0004f8b00)
2019/11/26 12:30:27 DEBUG : GET /DLZZkxdd8hZ2rzAZZ5qcqN7Zg0ZZqFRZZZlVZbVZGXZCvmsRCgRCzzUhHk61PIuhR2XxRD7/toto.txt HTTP/1.1
Host: p-par1.pcloud.com
User-Agent: rclone/v1.50.2
Authorization: XXXX
Accept-Encoding: gzip

2019/11/26 12:30:27 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2019/11/26 12:30:27 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2019/11/26 12:30:27 DEBUG : HTTP RESPONSE (req 0xc0004f8b00)
2019/11/26 12:30:27 DEBUG : HTTP/1.1 410 Gone
Connection: close
Content-Length: 4096
Content-Type: text/html
Date: Tue, 26 Nov 2019 11:30:27 +0000
Server: CacheHTTPd v1.0

<html><head><title>Invalid link</title></head><body>This link was generated for another IP address. Try previous step again.</body></html>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     `

**Comment by ncw** [comment]
Ah, so the meat of the error is actually

> Invalid link
> This link was generated for another IP address. Try previous step again.

Are you using some kind of proxy or firewall which could change your outgoing IP address for different HTTP requests?

**Comment by cyayon** [comment]
that'it !
i had a bad multiwan load balancing rule ... 
thank you very much.

**Comment by ncw** [comment]
No probs!

**Comment by RalMay** [comment]
Please excuse reopening the issue to add information.

I experienced the same with split tunnel VPN.
pCloud appears to use 'control' servers (ATM 6 servers at eapi.pcloud.com (45.131.244.7 - 12)) and dozens separate 'data' servers (at evcXYZ.pcloud.com).
In split tunnel setup it appears necessary to handle _45.131.244.0/24_ and _45.131.245.0/24_ the same (tunnel all or exclude all from tunneling).

Hope that helps other users!
