### ISSUE TITLE
Install from source fails with import errors, later version required?

### ISSUE THREAD

**Issue by eharris** [rclone/rclone#3765]
The installation from source instructions from https://rclone.org/install/ specify that Go 1.7 or later is sufficient for install, but trying to install using the given command: `go get -u -v github.com/rclone/rclone` results in:

```
> go get -u -v github.com/rclone/rclone
github.com/rclone/rclone (download)
package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)
package github.com/rclone/rclone/vendor/google.golang.org/api/transport/http/internal/propagation: no buildable Go source files in /home/eharris/prg/go/src/github.com/rclone/rclone/vendor/google.golang.org/api/transport/http/internal/propagation
package plugin: unrecognized import path "plugin" (import path does not begin with hostname)
```

This was generated using Go 1.7.4 on Debian Stretch 9.

**Comment by ncw** [comment]
Go 1.9 is the minimum required so the docs are wrong, sorry.

Does go 1.7 come with stretch? 

The pre compiled versions should all work fine on stretch

**Comment by eharris** [comment]
Yes, 1.7.4 is standard with Stretch.  Luckily 1.11.5 is in stretch-backports.

https://packages.debian.org/search?keywords=golang&searchon=names&suite=stretch&section=all

**Comment by ncw** [comment]
> Yes, 1.7.4 is standard with Stretch. Luckily 1.11.5 is in stretch-backports.

I hadn't noticed this - I always install go from golang.org

Fancy sending a PR to update the docs?  You only need to patch [install.md](https://github.com/rclone/rclone/blob/master/docs/content/install.md) the other files are auto generated.
