### ISSUE TITLE
Uninformative error message when filename is too long

### ISSUE THREAD

**Issue by eharris** [rclone/rclone#3768]
When using the crypt overlay with "standard" filename encryption on top of another remote, longer filenames result in "Failed to copy: object not found" errors.  The filename length limit (of the source file, unencrypted) appears to be 143 characters, which is consistent with the docs for the crypt target.

The issue is with the "object not found" portion of the error, which doesn't help at all in letting the user know what the actual cause of the failure is.  I think the error message should be improved to be more informative.

Using rclone v1.50.2-DEV on Debian Stretch 9 amd64 -

```
> rclone copy <some really long filename greater than 143 chars> secret:
2019/11/27 14:44:20 ERROR : some_long_filename: Failed to copy: object not found
2019/11/27 14:44:20 ERROR : Attempt 1/3 failed with 1 errors and: object not found
2019/11/27 14:44:59 ERROR : some_long_filename: Failed to copy: object not found
2019/11/27 14:44:59 ERROR : Attempt 2/3 failed with 1 errors and: object not found
2019/11/27 14:45:28 ERROR : some_long_filename: Failed to copy: object not found
2019/11/27 14:45:28 ERROR : Attempt 3/3 failed with 1 errors and: object not found
2019/11/27 14:45:28 Failed to copy: object not found
```

**Comment by animosity22** [comment]
It is documented in the crypt remote page and if you run with -vv, you can see the error.

**Comment by eharris** [comment]
This is a request for improvement.  The message as is in normal operation is not informative, and should be able to be made more so.  Having to run with double verbose to see something more useful should not be required.

**Comment by calisro** [comment]
rclone doesn't store the length that a filename or path can be.  That all depends on the provider and what message they return.  The local host may return an informative message but I believe most providers will simply fail.

**Comment by eharris** [comment]
You're missing my point.  I know the provider controls the limit.  I know that rclone can't exceed the limit imposed by the provider.  What I'm saying needs improvement is the way rclone's crypt remote encrypts the name of files, which is currently very inefficient and wastes lots of space (length), which then unnecessarily limits the length of storable filenames no matter what remote is in use.

**Comment by calisro** [comment]
I believe I understand the point.  You'd like a more constructive message that you know if the file name length was exceeded.  What i'm saying is the error coming back from the provider doesn't give enough detail to make the error specific like you asked.

The "inefficiency" is a result of encryption which takes more bytes to encrypt.  
https://rclone.org/crypt/

**Comment by eharris** [comment]
Then perhaps rclone needs to have a better idea of what limits are imposed by what endpoints.  I'm not saying the message has to be completely correct, just that it should indicate likely causes so that users have a better chance at figuring out what the issue is.

**Comment by ncw** [comment]
Figuring out file name limits for backends is fairly complicated!

Backends have different limits - these are some of the ones I've seen

- total number of UTF-8 bytes in the total path (s3)
- total number of UTF-8 bytes in each path element (drive)
- total number of unicode characters in each path element (forgotten which one)

It would be nice to put this info into the backend Features.
