### ISSUE TITLE
Improve crypt overlay standard filename encryption to handle longer names

### ISSUE THREAD

**Issue by eharris** [rclone/rclone#3769]
Using rclone v1.50.2-DEV, when using crypt overlay with "standard" filename encryption, the usable filename length limit seems to be 143 characters.  In my testing, a 143-char long original filename ends up as a 231-char long "encrypted" filename on a remote with a 255-char real filename length limit.  That's a 44% reduction in usable filename length (255 to 143), which seems quite excessive.

Isn't there some more reasonable way to encode the filenames without so much space wasted on overhead?  For instance, I think a 20% loss to encoding overhead would be an absolute maximum limit, which would still allow for more than 200-chars of usable filename length compared to the current 143-char limit.  But even with an added 128bits of base64 encoded salt should only take up 22 chars, which should leave 233 chars of filename length usable.

**Comment by animosity22** [comment]
If you want to discuss, please use the forums https://forums.rclone.org as this isn't really an issue.

Thanks!

**Comment by eharris** [comment]
This is a request for improvement, and I don't think this should have been closed.

It is still the case that the filename encoding overhead is excessive, making it too limited to handle many cases of real filesystems.

**Comment by animosity22** [comment]
Please check the feature request template and refer to #2 as it requires a discussion.

Thanks!
