### ISSUE TITLE
Hubic token refresh problem - oauth2: cannot fetch token: 301 Moved Permanently

### ISSUE THREAD

**Issue by Thinkscape** [rclone/rclone#377]
> 2016/03/03 16:01:15 Failed to create file system for "hubic:backup": Error authenticating swift connection: Get https://api.hubic.com/1.0/account/credentials: oauth2: cannot fetch token: 301 Moved Permanently

Hubic access tokens expire after 6 hours.
In order for rclone to be usable for backup (or any form of automation) rclone must be able to refresh the token automatically.

---

The process is described here: https://api.hubic.com/sandbox/

Here's the key part:

> Refreshing an access token looks like getting a new one, but some parameter's values change.
> First, you need to authenticate your application, with Authorization: Basic header or passing your credentials (client_id, client_secret) in POST data. Remember, we only support application/x-www-form-urlencoded POST data.
> 
> POST https://api.hubic.com/oauth/token/ HTTP/1.1
> Authorization: Basic 
> [...]
> refresh_token=XYZ&grant_type=refresh_token

**Comment by ncw** [comment]
The oauth2 framework that rclone uses will refresh the token automatically. I guess the problem is that after the token is received rclone switches to using the swift API and never touches the oauth server again. 

It looked like you got that message immediately you ran rclone which I don't understand. As part of the initial connection rclone will refresh the token. At least that is what it does here!

**Comment by Thinkscape** [comment]
hmm... I've configured and run it 3 days ago (finishing successfully), then tried again today and it gave me that. I've run `config` again and refreshed the token this way (config wizard asked me about that, used the in-browser auth again). Let me try syncing again tomorrow morning and we'll see what happens.

**Comment by Thinkscape** [comment]
Working fine today. I'll report back when I see it again ... 

btw: what about the mid-transfer refresh? 
Why not add something trivial, like calling the (already implemented) refresh function every 7200 seconds when switching file context. It's not as smart as inspecting the token lifetime but it'd effectively allow long-lasting `sync` with hubic :-) (i'm about to start a 5-7 day transfer)

**Comment by ncw** [comment]
> btw: what about the mid-transfer refresh? 

This should work already - when the swift token expires it will run through getting a new one from the hubic api.  If the oauth token has expired then it will refresh that first.

When I wrote

> I guess the problem is that after the token is received rclone switches to using the swift API and never touches the oauth server again

I was wrong and really should have looked at the code first ;-)

**Comment by Thinkscape** [comment]
:+1:  Thanks!

**Comment by Thinkscape** [comment]
Something is not right still ... 
Here's what I've encountered today:
````shell
$ rclone sync /Volumes/Data hubic:container-name
2016/03/09 12:06:05 Failed to create file system for "container-name": Error authenticating swift connection: Get https://api.hubic.com/1.0/account/credentials: oauth2: cannot fetch token: 301 Moved Permanently
Response: <html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
````

Then, when I attempted the exact same command again (with `-v`), it started working:

````shell
rclone -v sync /Volumes/Data hubic:container-name
2016/03/09 12:06:35 hubic: Saving new token in config file
2016/03/09 12:06:38 Hubic: Got swift credentials (expiry 2016-03-10 12:06:38 +0100 CET in 23h59m59.0401908s)
2016/03/09 12:06:38 Hubic Swift container container-name: Modify window is 1s
2016/03/09 12:06:39 Hubic Swift container container-name: Building file list
[...]
````

It's almost like it was invoking an invalid URL or something. I wish I'd run the first attempt with -v, maybe I'd get the url being called .... is there a `--debug` flag equivalent? I couldn't find it ...

**Comment by ncw** [comment]
I have seen this too occasionally.  I've been assuming it is a temporary Hubic problem, but maybe I'm wrong about that.

If you can catch this using `--dump-bodies` that would be very useful. Be careful posting the output directly though as it will have authentication stuff in it.  Probably best to try a simpler command like `rclone --dump-bodies lsd hubic:` too otherwise you'll get too much log!

I will try to replicate too.

I made an issue here golang/oauth2#177 as I think it is probably a bug in that library, but I'm not certain.

**Comment by Thinkscape** [comment]
A thought: maybe some or most of the response errors during auth could also be retried? 
As per `--retries` it could try a few times (default 3) in case the backend is temporarily misbehaving.

Naturally not a solution, but would save those backup runs from temp. problems. We'd need to isolate hard auth errors though (i.e. invalid token).

**Comment by ncw** [comment]
@Thinkscape good idea!

**Comment by pichouk** [comment]
Anything new on this ? I'm stuck with this error
```
Failed to create file system for "my-container: error authenticating swift connection: failed to get credentials: 401
```
The only way I found to fix this is to reset the Token manually with the browser...

**Comment by ncw** [comment]
@pichouk that is a different problem - not the 301 moved permanently.  Was it a one off problem, or do you get it continuously.  If the latter then please make a [new issue on github](https://github.com/ncw/rclone/issues/new).

**Comment by ivandeex** [comment]
@ncw This issue is stale for 3 years. Let's close it.

**Comment by ivandeex** [comment]
Closed after 3 years of inactivity.
