### ISSUE TITLE
Dealing with weird responses in Webdav

### ISSUE THREAD

**Issue by Zottelchen** [rclone/rclone#3772]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.50.2
- os/arch: windows/amd64
- go version: go1.13.4

#### What problem are you are trying to solve?
I've got a Nextcloud Instance at Hetzner.de ([Storage Share](https://www.hetzner.de/storage/storage-share)). I access it with rclone. Sometimes hetzner delivers a HTML response which leads to rclone stopping but not exiting. This error happens exactly once and no retries are happening.
Example:
```html
rclone: 2019/11/29 00:49:08 ERROR : data/d9/d967a92e3e4e44b34844e7b2fcd387b22b986d4563c9e0ee40c74ebac384423b: Post request put error: <!DOCTYPE html>
rclone: <html>
rclone: <head>
rclone:     <title>Requested page locked - Storage Share - Hetzner Online GmbH</title>
rclone:     <meta charset="UTF-8">
rclone:     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
rclone:     <meta http-equiv="X-UA-Compatible" content="IE=edge">
rclone:     <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
rclone:     <link rel="apple-touch-icon" sizes="180x180" href="[removed]">
rclone:     <link rel="icon" type="image/png" sizes="32x32" href="[removed]">
rclone:     <link rel="icon" type="image/png" sizes="16x16" href="[removed]">
rclone:     <link rel="icon" type="image/x-icon" href="[removed]">
rclone:     <style>/*!
rclone:  * Bootstrap v3.4.1 (https://getbootstrap.com/)
rclone:  * Copyright 2011-2019 Twitter, Inc.
rclone:  * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
rclone:  */
rclone: /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
rclone: html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section,summary{display:block}audio,canvas,progress,video{display:inline-block;vertical-align:baseline}audio:not([controls]){display:none;height:0}[hidden],template{display:none}a{background-color:transparent}a:active,a:hover{outline:0}abbr[title]{border-bottom:none;-webkit-text-decoration:underline dotted;-moz-text-decoration:underline dotted;text-decoration:underline dotted}b,strong{font-weight:700}dfn{font-style:italic}h1{font-size:2em;margin:.67em 0}mark{background:#ff0;color:#000}small{font-size:80%}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline}sup{top:-.5em}sub{bottom:-.25em}img{border:0}svg:not(:root){overflow:hidden}figure{margin:1em 40px}hr{-webkit-box-sizing:content-box;-moz-box-sizing:content-box;box-sizing:content-box;height:0}pre{overflow:auto}code,kbd,pre,samp{font-family:monospace,monospace;font-size:1em}button,input,optgroup,select,textarea{color:inherit;font:inherit;margin:0}button{overflow:visible}button,select{text-transform:none}button,html input[type=button],input[type=reset],input[type=submit]{-webkit-appearance:button;cursor:pointer}button[disabled],html input[disabled]{cursor:default}button::-moz-focus-inner,input::-moz-focus-inner{border:0;padding:0}input{line-height:normal}input[type=checkbox],input[type=radio]{-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:0}input[type=number]::-webkit-inner-spin-button,input[type=number]::-webkit-outer-spin-button{height:auto}input[type=search]{-webkit-appearance:textfield;-webkit-box-sizing:content-box;-moz-box-sizing:content-box;box-sizing:content-box}input[type=search]::-webkit-search-cancel-button,input[type=search]::-webkit-search-decoration{-webkit-appearance:none}fieldset{border:1px solid silver;margin:0 2px;padding:.35em .625em .75em}legend{border:0}textarea{overflow:auto}optgroup{font-weight:700}table{border-collapse:collapse;border-spacing:0}legend,td,th{padding:0}
rclone: /*! Source: https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css */
```
End of log. [removed] are base64 encoded images I cut to save some space here.

#### How do you think rclone should be changed to solve that?

I think a flag to retry in case of unexpected responses could solve this problem quite nicely.

Thank you.

**Comment by ncw** [comment]
An error like that should be retried... What is your command line? Have you set --retries or --low-level-retries to something other than their default?

> Sometimes hetzner delivers a HTML response which leads to rclone stopping but not exiting. 

What happens here - does rclone just stop?

If so can you `kill -QUIT` the process and paste the traceback from the log?

**Comment by Zottelchen** [comment]
I am using rclone in combination with restic. As far as I know restic changing the number of retries (https://github.com/restic/restic/blob/aaa1cc2c26f838f630fffbb6751d7797ad8a64fa/internal/backend/rclone/config.go#L18-L22), since other upload failures are retried.
Full command line: `restic -r rclone:drive:/Backup/ --verbose --password-file C:/PW --cleanup-cache backup C:/`

 And yes it just stops, nothing further happens. So far I couldn't reproduce the html response, maybe they fixed their servers?

**Comment by ncw** [comment]
Hmmm... Well rclone shouldn't stop so I wonder if was some problem with the server?

Do you want to leave this open or shall we close it and you can re-open if you manage to reproduce?

**Comment by Zottelchen** [comment]
I'll close this for now and I'll reopen when needed. Thank you.

**Comment by Zottelchen** [comment]
The error happened again, however taskkill (Windows) couldn't gracefully quit rclone or restic, both had to be forced, so sadly no traceback.
