### ISSUE TITLE
Failed to copy: Update Create failed: sftp: "Cannot open file in mode: CREATE|READ|TRUNCATE|WRITE" (SSH_FX_OP_UNSUPPORTED)

### ISSUE THREAD

**Issue by svyotov** [rclone/rclone#3776]
#### What is the problem you are having with rclone?

I cannot copy files to AWS SFTP transfer files. I believe the issue I am experiencing might be related to this https://github.com/pkg/sftp/issues/305 and should be resolved here https://github.com/pkg/sftp/pull/310. Hopefully updating the `sftp` dependency of `rclone` should resolve the issue.

#### What is your rclone version (output from `rclone version`)

```
 rclone version
rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.4
```

and

```
rclone version
rclone v1.50.2-073-ge2773b3b-beta
- os/arch: linux/amd64
- go version: go1.13.4
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Fedora release 31 (Thirty One)

####  Which cloud storage system are you using? (eg Google Drive)

AWS SFTP Transfer server

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy local.txt aws-sftp-transfer-server:remote.txt

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2019/12/01 18:56:11 ERROR : local.txt: Failed to copy: Update Create failed: sftp: "Cannot open file in mode: CREATE|READ|TRUNCATE|WRITE" (SSH_FX_OP_UNSUPPORTED)
2019/12/01 18:56:11 ERROR : Attempt 1/3 failed with 3 errors and: Update Create failed: sftp: "Cannot open file in mode: CREATE|READ|TRUNCATE|WRITE" (SSH_FX_OP_UNSUPPORTED)
2019/12/01 18:56:11 ERROR : local.txt: Failed to copy: Update Create failed: sftp: "Cannot open file in mode: CREATE|READ|TRUNCATE|WRITE" (SSH_FX_OP_UNSUPPORTED)
2019/12/01 18:56:11 ERROR : Attempt 2/3 failed with 3 errors and: Update Create failed: sftp: "Cannot open file in mode: CREATE|READ|TRUNCATE|WRITE" (SSH_FX_OP_UNSUPPORTED)
2019/12/01 18:56:11 ERROR : local.txt: Failed to copy: Update Create failed: sftp: "Cannot open file in mode: CREATE|READ|TRUNCATE|WRITE" (SSH_FX_OP_UNSUPPORTED)
2019/12/01 18:56:11 ERROR : Attempt 3/3 failed with 3 errors and: Update Create failed: sftp: "Cannot open file in mode: CREATE|READ|TRUNCATE|WRITE" (SSH_FX_OP_UNSUPPORTED)
2019/12/01 18:56:11 Failed to copy with 3 errors: last error was: Update Create failed: sftp: "Cannot open file in mode: CREATE|READ|TRUNCATE|WRITE" (SSH_FX_OP_UNSUPPORTED)
```

**Comment by ncw** [comment]
The update you pointed out was a comment describing what needed to be done!

I did that - it was just a one line change - can you have a go with this?

https://beta.rclone.org/branch/v1.50.2-073-g172c70cf-fix-3776-sftp-update-beta/ (uploaded in 15-30 mins)

**Comment by 99ACA** [comment]
Hi,
I am working with docker image **rclone/rclone:1.51.0**, copy file from local into AWS SFTP.
Getting the same problem.

Error message:
f1/example.file-5: Failed to copy: Update SetModTime failed: SetModTime failed: sftp: "SETSTAT unsupported" (SSH_FX_OP_UNSUPPORTED)

P.S - RClone is an amazing.
