### ISSUE TITLE
rclone not following rsync behaviour

### ISSUE THREAD

**Issue by axet** [rclone/rclone#3779]
#### What is the problem you are having with rclone?
rclone does not follow rsync behaviour

#### What is your rclone version (output from `rclone version`)
v1.47.0

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
linux

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -P sync drive:notes 123/
vs
rclone -P sync drive:notes/ 123/

'rsync notes 123/' vs 'rsync notes/ 123/' has different output, first command copy folder content (notes/* -> 123), second command copy whole folder (notes -> 123). rclone does not follow this behaviour, it allays copy folder content.

**Comment by ncw** [comment]
Yes rclone always copies DIR -> DIR so the equivalent of `rsync source/ dest/`

The rsync behaviour is very confusing for newcomers to rsync so I decided to diverge from what rsync does.

Hopefully this is explained in the docs well enough - eg here: https://rclone.org/commands/rclone_copy/

I'm afraid it is too late to change rclone's behaviour here - it would break too many scripts and users.

I'll close this now :-)
