### ISSUE TITLE
[web-GUI feature] Implement a flag or setting for non auto-open browser

### ISSUE THREAD

**Issue by thestigma** [rclone/rclone#3785]
This is a really basic feature request for the rclone web-gui.

Currently the web-gui auto-opens (and launches the default browser) any time it is launched.
For advanced users this can be much more annoying than helpful, although I see why it might be helpful to keep as default for less experienced users.

**Your mission - should you choose to accept it:**
Implement a flag or other option to shortcut the code that calls the browser to open the web-GUI page.

Since this is only side-stepping an existing function and not adding something new it should not have to involve a lot of code - probably just a simple if-statement in the appropriate place. Hopefully not a lot of work.

**Comment by Yexiaoxing** [comment]
It should not be a hard job. I will work on it later - or are you interested in creating a pull request? Similar PR can be found https://github.com/rclone/rclone/pull/3669

**Comment by thestigma** [comment]
Thank you. I am still not quite confident in working with go. I will work on improving that in the future so I can help more directly on coding.

Your related issue seems very closely tied to this. It seems like a natural extension to that.

**Comment by Yexiaoxing** [comment]
This feature is made possible by PR #3817. You may now use the option `--rc-web-gui-no-open-browser` to disable auto-open browser.

**Comment by ncw** [comment]
We've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.51
