### ISSUE TITLE
No Instruction where put helper script for automount

### ISSUE THREAD

**Issue by mikart143** [rclone/rclone#3786]
#### Output of `rclone version`
rclone v1.50.1
- os/arch: linux/amd64
- go version: go1.13.4

#### Describe the issue
Hello ! There is no instruciton where put helper script which you can find in wiki under rclone automount. I was trying to add this to sbin as mount.rclonefs but nothing has change

**Comment by ncw** [comment]
It says on the page

    rclonefs wrapper has to be in the PATH=/usr/local/bin:/usr/bin

So try `/usr/bin`

If that works maybe you could add some more instructions to [the wiki page](https://github.com/rclone/rclone/wiki/rclone-fstab-mount-helper-script)?

**Comment by animosity22** [comment]
This looks to be answered. If you want to update the wiki page, that would be great!

Thanks.
