### ISSUE TITLE
Feature to copy empty files

### ISSUE THREAD

**Issue by niloct** [rclone/rclone#3788]
#### What is your current rclone version (output from `rclone version`)?

v.1.36

#### What problem are you are trying to solve?

There are several empty files that are important to keep in the filesystem, like `__init__.py` for instance. 

Alas, the 1.36 version of rclone issues a LOT of errors regarding empty files:

```
2019/12/05 17:36:51 ERROR : nginx/html/phpBB3/styles/prosilver/theme/index.htm: Failed to copy: MissingContentLength:
	status code: 411, request id: tx00000000000009a6093ec-005de96a63-3cbf3-nyc3b

```

It would be nice to have a flag in which you could allow copying of empty files to remote space (I'm using digital ocean's spaces).

Thanks for you attention,

**Comment by ncw** [comment]
Rclone should cope with empty files just fine - the integration tests include copying empty files so all backends should cope with them.

Which backend are you using?

I suggest you try [a newer version](https://rclone.org/downloads/) as 1.36 is quite old!

**Comment by niloct** [comment]
I'm running an Ubuntu 18.10 droplet and that old version was installed via apt-get.

Indeed, running latest version dropped all the MissingContentLength errors, thanks!

I'm actually experiencing another error in some files but that's offtopic I will open another issue.
