### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by 5536086** [rclone/rclone#3791]
[root@~]# curl https://rclone.org/install.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 2a02:24e0:8:61f9::1: Network is unreachable

**Comment by Yexiaoxing** [comment]
It seems that the server was down.

**Comment by 5536086** [comment]
The official website is also closed

**Comment by Yexiaoxing** [comment]
It works for me now. Could you please have a try? @5536086

**Comment by ncw** [comment]
The website had a period of downtime (my fault - not checking my email - have signed up for SMS alerts.).

All should be working now though

I'll close this now.
