### ISSUE TITLE
dlna: option to disable/enable external subtitles

### ISSUE THREAD

**Issue by beredim** [rclone/rclone#3794]
Even if the default is to search and add external subtitles to a served item, there should be an option available to disable this feature.
I think such a feature can be beneficial in reducing unwanted scraping/traffic of the served remote:folder.

**Comment by ncw** [comment]
I think you can do this with `--exclude "*.srt"` can't you?

**Comment by animosity22** [comment]
Looks to be answered.

Any questions, please use https://forums.rclone.org and we can help out.

Thanks!
