### ISSUE TITLE
dlna: Default (static) list of file extensions to serve, and option to add or remove from that list

### ISSUE THREAD

**Issue by beredim** [rclone/rclone#3796]
I think (but may be wrong) that the majority of users would want the dlna feature to stream video, and to a lesser extent music and/or photos.
Other use cases are probably minimal.

Currently 
```
Rclone will list all files present in the remote, without filtering based on media formats or file extensions
```

I suggest altering the default behavior, to include only a (comprehensive) list of media files (based on file extension), while giving the user the option to add or remove from that list,
OR
keeping the current behavior, but giving the user the option to alter it (serve only specific file extensions)
OR 
something along those lines.

This should be beneficial in reducing unwanted scraping/traffic of the served remote:folder,
allow the user to present to the dlna clients only content they understand,
and only content the user intents to serve.

**Comment by ncw** [comment]
It is possible to cut down the files examined with the `--include` and `--exclude` flags.  For example you can add `--include "*.{mp4,avi}"` to restrict to just those types of files.

I wouldn't have thought examining non media files would make a lot of overhead though - it is listing the directory that is the expensive part rather than checking out the files.

Though I might have overlooked something there? @sretlawd - thoughts?

**Comment by beredim** [comment]
Wow, somehow I totally misunderstood what the `--include` flag does.
Apologies.

So the mechanism is already there, what's to be done is create (or copy from another project) a comprehensive list of default file extensions and post it somewhere on the wiki/forum.

**Comment by ncw** [comment]
I'm not 100% sure excluding all the non audio/video files will buy you anything though - what do you see in your tests if you try using `--include`.  Does it improve things?  If so how?

**Comment by sretlawd** [comment]
Only real overhead should be listing the directory, yeah.  The entire remote is available over http (same as "serve http"), dlna just provides some extra metadata on top of that.  Only place file extensions really come into play is that for said metadata we do have to know whether it's a video/audio/image/subtitle..  (And if can't be identified as one of those, it's omitted.)

> Rclone will list all files present in the remote, without filtering based on media formats or file extensions

Should probably rephrase the documentation on this - I think the main point is we're just trying to be somewhat equivalent to putting the same files on a USB flash drive and putting that in your TV.  We don't do any transcoding (and really don't want to), any fancier media server stuff that would require inspecting the contents of files (ID3 tags, media durations in HH:MM:SS, etc.), and nothing that would require keeping a separate database.

**Comment by animosity22** [comment]
This looks to be answered. If there is still a question, you can always ask on https://forums.rclone.org
