### ISSUE TITLE
Hard Link Support in Google Drive

### ISSUE THREAD

**Issue by eatnumber1** [rclone/rclone#3800]
I was searching for an existing request for this, but couldn't find one. Upon some investigation, it actually looks like it can't be done, so I'm mostly filing this FR to document my findings.

Google Drive supports a single file having multiple parents via the `addParents` parameter to [update](https://developers.google.com/drive/api/v3/reference/files/update), which seems to suggest that it might be possible to implement hard linking support for mounted GDrive filesystems.

Unfortunately, a real hardlinked file has its own metadata (e.g. name, mode, etc.), whereas a GDrive file with multiple parents can still only have a single name. That means that if implemented, when you rename a hardlinked file, it would rename all links to that file, which would be surprising behavior.

As I said, I'm mostly just filing this to document that finding, so I'll just close this FR. Please reopen or comment if you can think of a better way to achieve this without surprising behaviors.

**Comment by diyism** [comment]
I found that JuiceFS(with go-fuse lib, that support hard link) can mount as a full POSIX file system with the remote s3 storage server(for example MinIO, StorJ etc)

**Comment by Masamune3210** [comment]
It's probably locally caching any excess things that GDrive doesn't support. As they said, multi-parent links have been depreciated

**Comment by Bra1nsen** [comment]
sorry I don't see through here completely. is it now possible to set hardlinks via rclone and gdrive? and if so how?

**Comment by ncw** [comment]
@Bra1nsen no, hardlinks don't work with rclone
