### ISSUE TITLE
There is a bug in configuring onedrive

### ISSUE THREAD

**Issue by 5536086** [rclone/rclone#3801]
![TIM截图20191211141300](https://user-images.githubusercontent.com/20472307/70596341-9efaf700-1c20-11ea-819d-84ffcf450c9a.png)

When I configured onedrive, rclone did not return me the authorized address of rclone

**Comment by Cnly** [comment]
To authorise yourself on a headless machine, you need to run the given command on another machine that has a web browser, just as said in your screenshot: `rclone authorize "onedrive"`. That command will give you the result you need to paste.

**Comment by 5536086** [comment]
> 要在无头计算机上进行授权，您需要在另一台具有网络浏览器的计算机上运行给定命令，如屏幕截图所示：`rclone authorize "onedrive"`。该命令将为您提供需要粘贴的结果。

I authorized in win but got this error
：
![TIM截图20191211143607](https://user-images.githubusercontent.com/20472307/70597617-bd162680-1c23-11ea-9a74-6a86acf0eb1f.png)

**Comment by Cnly** [comment]
I think your screenshot has once again made it clear. Please ensure rclone has the permission to listen on the address `127.0.0.1:53682`. We won't be able to help you with that since it's probably your local firewall settings and it's unrelated to rclone.

**Comment by Cnly** [comment]
I'm closing this because it seems unrelated to rclone. Please feel free to reopen if you found something new.
