### ISSUE TITLE
OneDrive: support national versions of Office 365

### ISSUE THREAD

**Issue by Yexiaoxing** [rclone/rclone#3804]
**To contributors**: We have got several PRs on this issue: #3973 #4072 #4131, please think twice if you want to open a new PR on it. Instead, consider help review these PRs.

#### What is your current rclone version (output from `rclone version`)?
latest

#### What problem are you are trying to solve?
National (Germany, Chinese, and US Government) version of Office 365 requires a different API endpoint. Please refer to https://docs.microsoft.com/en-us/graph/deployments

**Comment by Cnly** [comment]
This should not be hard to implement; adding an `endpoint` option to the backend should do it. The S3 backend has done something similar:

https://github.com/rclone/rclone/blob/0ecb8bc2f97a2c3715b41bf7188d97dca5d2a3b5/backend/s3/s3.go#L178-L189

@Yexiaoxing do you want to open a PR for this? :)

**Comment by xytoki** [comment]
I found a patch in this [Gist](https://gist.github.com/ShadeShady/81b6fecca82c289e8e5ae0637918e7e6) but it supports office 365 China version only.
Hope it could be helpful.

**Comment by Cnly** [comment]
Since we've already got a few PRs working on this and it's actually harder to implement than it seemed, I'm taking away the `good first issue` badge.

**Comment by Sunil-P** [comment]
I am unable to test my PR because of restrictions in accessing country specific cloud. Usually these country specific ids are business specific, I can't register a personal id to test.
Anyone willing to help me out with this. Thnx!

**Comment by ncw** [comment]
We've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54
