### ISSUE TITLE
install.sh defaults to /usr/bin on Linux

### ISSUE THREAD

**Issue by shoogle** [rclone/rclone#3805]
The [install.sh](https://github.com/rclone/rclone/blob/0ecb8bc2f97a2c3715b41bf7188d97dca5d2a3b5/docs/content/install.sh#L149-L153) script puts rclone in `/usr/bin`. It should go in `/usr/local/bin`.

On Linux, `/usr/bin` is [reserved](https://askubuntu.com/a/955971) for binaries installed by distro package managers (`apt`, `yum`, etc.). Nothing should mess with the files in those directories except via the package manager. `/usr/local/bin` is [available](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html) for programs not installed via a package manager.

Note that the manuals are [correctly installed](https://github.com/rclone/rclone/blob/0ecb8bc2f97a2c3715b41bf7188d97dca5d2a3b5/docs/content/install.sh#L154-L161) to `/usr/local/share`.

**Comment by Yexiaoxing** [comment]
dup #3695

**Comment by animosity22** [comment]
Closing duplicate.
