### ISSUE TITLE
Exclude not being applied

### ISSUE THREAD

**Issue by mike391** [rclone/rclone#3808]
I cant seem to get exclude working on the latest version of rclone:

My command is as follows:
```
 rclone sync /data/Raid OneDrive:/Raid --config /config/rclone.conf -v --exclude "plx/**"
```

And this is the output:
```
INFO: Starting rclone sync /data/Raid OneDrive:/Raid --config /config/rclone.conf -v --exclude "plx/**"

19/12/16 16:22:14 NOTICE: Docker/.config/plx/Library/Application Support/Plex Media Server/Metadata/TV Shows/9/f2b20ca02469837ee98064cbc911f0f0b0d2ebd.bundle/Contents/_combined/seasons/29/episodes/9/thumbs/com.plexapp.agents.thetvdb_104893ee196e1ddda0441f8fcc13f786de5ac0fc: Can't follow symlink without -L/--copy-links

```

As you can see its still going into the ```plx``` folder even though its been excluded...

**Comment by naeloob** [comment]
Try --exclude **/plx/**

**Comment by ncw** [comment]
I think `--exclude "plx/**"` is correct.  What version of rclone are you using?

**Comment by animosity22** [comment]
Closing out since this looks to be answered.

If you still have a question on a filter, please use https://forums.rclone.org and we can help out.
