### ISSUE TITLE
exceeding limit of 150 wakeups per second over 300 seconds

### ISSUE THREAD

**Issue by mathieucarbou** [rclone/rclone#3809]
```
❯  rclone --version
rclone v1.50.2
- os/arch: darwin/amd64
- go version: go1.13.4
```

Seems like a recursive function of rclone (makeListDir) is causing Catalina spindump process to dump some diagnostics of rclone while it is running.

This might make a computer crash or unresponsive if too many process have the issue.

[rclone_2019-12-16-171704_C02YJ2F2JGH6.wakeups_resource.txt](https://github.com/rclone/rclone/files/3970470/rclone_2019-12-16-171704_C02YJ2F2JGH6.wakeups_resource.txt)

**Comment by animosity22** [comment]
You can use the forums to ask a question, https://forums.rclone.org and we can help out as this seems more like a question.
