### ISSUE TITLE
Flag --drive-root-folder-id not working with rclone config

### ISSUE THREAD

**Issue by rootorchild** [rclone/rclone#3810]
#### What is the problem you are having with rclone?
Command `rclone config` not working with flag `--drive-root-folder-id`

#### What is your rclone version (output from `rclone version`)
```
butdr@ubuntu1804:~$ rclone version
rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.4
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 18.04 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`/home/butdr/bin/rclone config create googledrive2 drive config_is_local false --drive-client-id xxxxxx --drive-client-secret xxxxxx --drive-root-folder-id 1Ve6CuTWG_qIO2CgEBFBJG5UdY4MUo-cq`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
butdr@ubuntu1804:~$ /home/butdr/bin/rclone -vv config create googledrive2 drive config_is_local false --drive-client-id xxxxxx --drive-client-secret xxxxxx --drive-root-folder-id 1Ve6CuTWG_qIO2CgEBFBJG5UdY4MUo-cq
2019/12/17 11:26:31 DEBUG : rclone: Version "v1.50.2" starting with parameters ["/home/butdr/bin/rclone" "-vv" "config" "create" "googledrive2" "drive" "config_is_local" "false" "--drive-client-id" "xxxxxx" "--drive-client-secret" "xxxxxx" "--drive-root-folder-id" "1Ve6CuTWG_qIO2CgEBFBJG5UdY4MUo-cq"]
2019/12/17 11:26:31 DEBUG : Using config file from "/home/butdr/.config/rclone/rclone.conf"
Remote config
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
Auto confirm is set: answering No, override by setting config parameter config_is_local=true
If your browser doesn't open automatically go to the following link: https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=xxxxxx&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=QMJDweU7lOkDUyRbghmQdg
Log in and authorize rclone for access
Enter verification code> 4/xxxxxx
2019/12/17 11:27:15 DEBUG : googledrive2: Added new token to config, still needs to be saved
--------------------
[googledrive2]
type = drive
config_is_local = false
token = {"access_token":"ya29.Il-xxxxxx","token_type":"Bearer","refresh_token":"1xxxxxx","expiry":"2019-12-17T12:27:15.174689384+07:00"}
--------------------
2019/12/17 11:27:15 DEBUG : rclone: Version "v1.50.2" finishing with parameters ["/home/butdr/bin/rclone" "-vv" "config" "create" "googledrive2" "drive" "config_is_local" "false" "--drive-client-id" "xxxxxx" "--drive-client-secret" "xxxxxx" "--drive-root-folder-id" "1Ve6CuTWG_qIO2CgEBFBJG5UdY4MUo-cq"]
```

**Comment by darthShadow** [comment]
Any arguments for the config parameters need to be passed as the keys required in the config file, i.e. `root_folder_id` instead of `--drive-root-folder-id`.

Your command would then be: `/home/butdr/bin/rclone config create googledrive2 drive config_is_local false client_id xxxxxx client_secret xxxxxx root_folder_id 1Ve6CuTWG_qIO2CgEBFBJG5UdY4MUo-cq`

**Comment by rootorchild** [comment]
@darthShadow 

Thanks for help. I wonder why flag `--drive-client-id` & `--drive-client-secret` work with command `rclone config` but `--drive-root-folder-id` does not?

Example I can run this command & it's working well:
```
/home/butdr/bin/rclone config create googledrive2 drive config_is_local false --drive-client-id xxxxxx --drive-client-secret xxxxxx root_folder_id 1Ve6CuTWG_qIO2CgEBFBJG5UdY4MUo-cq
```

**Comment by darthShadow** [comment]
> Example I can run this command & it's working well:
> `/home/butdr/bin/rclone config create googledrive2 drive config_is_local false --drive-client-id xxxxxx --drive-client-secret xxxxxx root_folder_id 1Ve6CuTWG_qIO2CgEBFBJG5UdY4MUo-cq`

This doesn't work as you expect. If you check the final configuration that is generated, it doesn't include the client-id & client-secret, meaning that any subsequent requests will use the default rclone credentials and not the ones specified by you.

**Comment by rootorchild** [comment]
@darthShadow,

Thank you very much!
