### ISSUE TITLE
Support for created date on Windows for local to local backups

### ISSUE THREAD

**Issue by oO0XX0Oo** [rclone/rclone#3811]
Hi,

reference thread on the rclone forum: https://forum.rclone.org/t/keep-created-date-at-least-on-nounc/13340

It would be nice if rclone could support keeping the created date for files / folders when doing a backup (source and destination are local drives) on Windows OS. At the moment it sets the created date to the time when the backup is taken instead...

Possible library (if not used already): https://github.com/djherbis/times

Thanks a lot!

**Comment by ivandeex** [comment]
Unfortunately internal rclone guts support only modtime.
A framework for ad-hoc metadata is not even in mid-term plans.
Sorry.
