### ISSUE TITLE
Space used is always reported as 0 for team drives

### ISSUE THREAD

**Issue by PortNumber53** [rclone/rclone#3813]
#### What is the problem you are having with rclone?
All my rclone mounts of Google Shared Drives show usage as 0 (zero)

#### What is your rclone version (output from `rclone version`)
rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.4

and 
rclone v1.50.2
- os/arch: linux/arm
- go version: go1.13.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Archlinux and Raspbian

####  Which cloud storage system are you using? (eg Google Drive)
Google Shared Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount storagehub_aa:/ /mnt/testing

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2019/12/18 17:49:40 DEBUG : rclone: Version "v1.50.2" starting with parameters ["rclone" "mount" "-vv" "storagehub_aa:/" "/mnt/testing"]
2019/12/18 17:49:40 DEBUG : Using config file from "/home/grimlock/.config/rclone/rclone.conf"
2019/12/18 17:49:40 DEBUG : Google drive root '': Mounting on "/mnt/testing"
2019/12/18 17:49:41 DEBUG : Adding path "vfs/forget" to remote control registry
2019/12/18 17:49:41 DEBUG : Adding path "vfs/refresh" to remote control registry
2019/12/18 17:49:41 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2019/12/18 17:49:41 DEBUG : : Root:
2019/12/18 17:49:41 DEBUG : : >Root: node=/, err=<nil>

**Comment by animosity22** [comment]
I'm thinking the space is reported by the same routine that rclone about uses:

```
felix@gemini:~$ rclone about GD:
rUsed:    102.680T
Trashed: 0
Other:   159.438M
felix@gemini:~$ rclone about TDTest:
felix@gemini:~$ rclone size TDTest:
Total objects: 1
Total size: 1.402 GBytes (1504953150 Bytes)
```

or perhaps a regression of this one:

https://github.com/rclone/rclone/issues/2288

**Comment by ncw** [comment]
Team drives don't have an API for reporting the total used as far as I can see which is why the team drives show 0 usage and a size of 1PB.

animosity22 is correct it is the same code as rclone about.

**Comment by PortNumber53** [comment]
Thanks for looking into this ncw! And thanks for the help animosity22
Hopefully google adds an api call for that
