### ISSUE TITLE
Value for "Checks" in log always zero

### ISSUE THREAD

**Issue by chrissv** [rclone/rclone#3814]
#### What is the problem you are having with rclone?
The value for "Checks" in the log report is always 0 / something.

#### What is your rclone version (output from `rclone version`)
rclone v1.50.2-089-g1ab49850-beta
- os/arch: windows/amd64
- go version: go1.13.5

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, but the same problem happens on Raspberry Pi

####  Which cloud storage system are you using? (eg Google Drive)
None - all tests done with local drives.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -vv sync /temp/rclonesource /temp/rclonelocal

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

`The source directory simply has 5 files. The destination directory initially is empty`
$ ls -lsa rclonesource/
total 5
0 drwxrwxr-x+ 1 STEVEN None 0 Dec 18 18:47 .
0 drwxrwx---+ 1 STEVEN None 0 Dec 18 18:54 ..
1 -rw-rw-r--+ 1 STEVEN None 6 Dec 18 18:47 file.1
1 -rw-rw-r--+ 1 STEVEN None 6 Dec 18 18:47 file.2
1 -rw-rw-r--+ 1 STEVEN None 6 Dec 18 18:47 file.3
1 -rw-rw-r--+ 1 STEVEN None 6 Dec 18 18:47 file.4
1 -rw-rw-r--+ 1 STEVEN None 6 Dec 18 18:47 file.5

`initial sync command, where all 5 files are copied`
$ rclone -vv sync /temp/rclonesource /temp/rclonedest
2019/12/18 18:54:38 DEBUG : rclone: Version "v1.50.2-089-g1ab49850-beta" starting with parameters ["C:\\bin\\rclone.exe" "-vv" "sync" "/temp/rclonesource" "/temp/rclonedest"]
2019/12/18 18:54:38 DEBUG : Using config file from "C:\\Users\\STEVEN\\.config\\rclone\\rclone.conf"
2019/12/18 18:54:38 INFO  : Local file system at //?/C:/temp/rclonedest: Waiting for checks to finish
2019/12/18 18:54:38 INFO  : Local file system at //?/C:/temp/rclonedest: Waiting for transfers to finish
2019/12/18 18:54:38 DEBUG : file.2: MD5 = b1946ac92492d2347c6235b4d2611184 OK
2019/12/18 18:54:38 INFO  : file.2: Copied (new)
2019/12/18 18:54:38 DEBUG : file.1: MD5 = b1946ac92492d2347c6235b4d2611184 OK
2019/12/18 18:54:38 INFO  : file.1: Copied (new)
2019/12/18 18:54:38 DEBUG : file.3: MD5 = b1946ac92492d2347c6235b4d2611184 OK
2019/12/18 18:54:38 INFO  : file.3: Copied (new)
2019/12/18 18:54:38 DEBUG : file.4: MD5 = b1946ac92492d2347c6235b4d2611184 OK
2019/12/18 18:54:38 INFO  : file.4: Copied (new)
2019/12/18 18:54:38 DEBUG : file.5: MD5 = b1946ac92492d2347c6235b4d2611184 OK
2019/12/18 18:54:38 INFO  : file.5: Copied (new)
2019/12/18 18:54:38 INFO  : Waiting for deletions to finish
2019/12/18 18:54:38 INFO  :
Transferred:            30 / 30 Bytes, 100%, 9.790 kBytes/s, ETA 0s
Transferred:            5 / 5, 100%
Elapsed time:          0s

2019/12/18 18:54:38 DEBUG : 3 go routines active
2019/12/18 18:54:38 DEBUG : rclone: Version "v1.50.2-089-g1ab49850-beta" finishing with parameters ["C:\\bin\\rclone.exe" "-vv" "sync" "/temp/rclonesource" "/temp/rclonedest"]

`Repeating the same command. No files will be copied`
$ rclone -vv sync /temp/rclonesource /temp/rclonedest
2019/12/18 18:54:41 DEBUG : rclone: Version "v1.50.2-089-g1ab49850-beta" starting with parameters ["C:\\bin\\rclone.exe" "-vv" "sync" "/temp/rclonesource" "/temp/rclonedest"]
2019/12/18 18:54:41 DEBUG : Using config file from "C:\\Users\\STEVEN\\.config\\rclone\\rclone.conf"
2019/12/18 18:54:41 INFO  : Local file system at //?/C:/temp/rclonedest: Waiting for checks to finish
2019/12/18 18:54:41 DEBUG : file.1: Size and modification time the same (differ by 0s, within tolerance 100ns)
2019/12/18 18:54:41 DEBUG : file.1: Unchanged skipping
2019/12/18 18:54:41 DEBUG : file.3: Size and modification time the same (differ by 0s, within tolerance 100ns)
2019/12/18 18:54:41 DEBUG : file.2: Size and modification time the same (differ by 0s, within tolerance 100ns)
2019/12/18 18:54:41 DEBUG : file.2: Unchanged skipping
2019/12/18 18:54:41 DEBUG : file.4: Size and modification time the same (differ by 0s, within tolerance 100ns)
2019/12/18 18:54:41 DEBUG : file.3: Unchanged skipping
2019/12/18 18:54:41 DEBUG : file.4: Unchanged skipping
2019/12/18 18:54:41 DEBUG : file.5: Size and modification time the same (differ by 0s, within tolerance 100ns)
2019/12/18 18:54:41 DEBUG : file.5: Unchanged skipping
2019/12/18 18:54:41 INFO  : Local file system at //?/C:/temp/rclonedest: Waiting for transfers to finish
2019/12/18 18:54:41 INFO  : Waiting for deletions to finish
2019/12/18 18:54:41 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Checks:                 0 / 5, 100%
Elapsed time:          0s

2019/12/18 18:54:41 DEBUG : 3 go routines active
2019/12/18 18:54:41 DEBUG : rclone: Version "v1.50.2-089-g1ab49850-beta" finishing with parameters ["C:\\bin\\rclone.exe" "-vv" "sync" "/temp/rclonesource" "/temp/rclonedest"]

`The line for "Checks:" should show "5 / 5" but it always shows "0" as the first value.`
The problem also shows up when using other back ends (like OneDrive).

This used to work a while ago - don't know exactly when the problem crept in. I regularly update to use the latest beta, and it's been a while.

**Comment by Cnly** [comment]
Thanks, just did a bisect and found the bug:

https://github.com/rclone/rclone/blob/0ecb8bc2f97a2c3715b41bf7188d97dca5d2a3b5/fs/accounting/stats.go#L322-L323

where `s.errors` should be `s.checks` instead. This came from commit https://github.com/rclone/rclone/commit/7e602dbf393b793ac804b219cc5dadc3692fb363.

I've made a patch and the built binaries should be available at https://beta.rclone.org/branch/v1.50.2-091-g4948bfa8-fix-zero-checks-beta/. Would you mind helping to see if the problem's fixed?

**Comment by chrissv** [comment]
Looks like that fixed the problem! Here's a section of the log:
Transferred:      629.845M / 1.244 TBytes, 0%, 599.414 kBytes/s, ETA 3w4d18h54m32s
Checks:               621 / 621, 100%
Transferred:          129 / 269872, 0%
Elapsed time:    17m55.9s

**Comment by Cnly** [comment]
Thanks, I've merged it now.
