### ISSUE TITLE
No 'Authorization: Digest' header found

### ISSUE THREAD

**Issue by q409640976** [rclone/rclone#3820]
is rclone support digest authenticaton yet?
when i mount ,there is a  error:
`webdav root '': Statfs failed: about call failed: No 'Authorization: Digest' header found. Either the client didn't send one, or the server is misconfigured: Sabre\DAV\Exception\NotAuthenticated: 401 Unauthorized`

**Comment by ncw** [comment]
It doesn't yet, sorry :-(

The base issue is #2110 so I'll close this one.

Would you like to work on adding digest support?  If so please comment on #2110
