### ISSUE TITLE
Can not list or read files from Google Team Drive

### ISSUE THREAD

**Issue by tyde7** [rclone/rclone#3821]
#### What is the problem you are having with rclone?

I cannot correctly lsd, mount or doing other operation that needs reading Google Team Drive.
Tried refreshing my token, using my own client-id.

#### What is your rclone version (output from `rclone version`)

rclone v1.50.2-089-g1ab49850-beta, and v1.50.2 Released version, both tried.

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10, 64bit 18363.535

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive (Team Drive)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```bash
rclone mkdir "Google Drive:/123"
```

> there is a folder named 123 in web page.

```bash
rclone lsd "Google Drive:"
```

> No output

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```bash
rclone mkdir "Google Drive:/123"
```

2019/12/21 23:55:59 DEBUG : rclone: Version "v1.50.2-089-g1ab49850-beta" starting with parameters ["rclone" "mkdir" "Google Drive:/123" "-vv"]
2019/12/21 23:55:59 DEBUG : Using config file from "C:\\Users\\Username\\.config\\rclone\\rclone.conf"
2019/12/21 23:56:00 DEBUG : Google drive root '123': Making directory
2019/12/21 23:56:05 DEBUG : 5 go routines active
2019/12/21 23:56:05 DEBUG : rclone: Version "v1.50.2-089-g1ab49850-beta" finishing with parameters ["rclone" "mkdir" "Google Drive:/123" "-vv"]

```bash
rclone lsd "Google Drive:"
```

2019/12/21 23:57:36 DEBUG : rclone: Version "v1.50.2-089-g1ab49850-beta" starting with parameters ["rclone" "lsd" "Google Drive:" "-vv"]
2019/12/21 23:57:36 DEBUG : Using config file from "C:\\Users\\Username\\.config\\rclone\\rclone.conf"
2019/12/21 23:57:37 DEBUG : Google drive root '': read info from team drive "My Drive Name"
2019/12/21 23:57:37 DEBUG : 5 go routines active
2019/12/21 23:57:37 DEBUG : rclone: Version "v1.50.2-089-g1ab49850-beta" finishing with parameters ["rclone" "lsd" "Google Drive:" "-vv"]

#### My config

```ini
[Google Drive]
type = drive
client_id = <ID>.apps.googleusercontent.com
client_secret = <Secret>
scope = drive
shared_with_me = true
token = {"access_token":"<token>","token_type":"Bearer","refresh_token":"<token 2>","expiry":"2019-12-22T00:50:15.6702721+08:00"}
team_drive = <Team Drive ID>
root_folder_id = <Dump from url or auto-generation both tried>
```

**Comment by tyde7** [comment]
After I comment 
```ini
[Google Drive]
...
team_drive = <Team Drive ID>
...
```
Everything is fine now...

**Comment by ncw** [comment]
Apologies for the delay responding...

Is this working OK now?  I'm not sure why commenting the `team_drive` fixed it - that would mean you are looking at the base drive not the team drive.

**Comment by tyde7** [comment]
> Apologies for the delay responding...
> 
> Is this working OK now? I'm not sure why commenting the `team_drive` fixed it - that would mean you are looking at the base drive not the team drive.

Well I just want to show it works properly when I'm using my own drive, but it doesn't work when I'm using team drive. When I'm using my own client id, mounting team drive is totally not working. When I'm using client id from rclone, it works sometimes but not stable. 

And not only the command `mount`, other command like `lsd`, `ls` have same issue.

Now I have to use rclone with OneDrive, it works perfectly.

**Comment by ncw** [comment]
You might need to delete the `root_folder_id` from your config when switching between team drive and normal drive.

I'm not sure why using your own client_id and client_secret for a team drive should make any difference.

Can you try dumping the responses with `-vv --dump bodies` to see what google actually returns?

**Comment by animosity22** [comment]
If you still have a question or concern, you can always on the forums as this seems to be a use question rather than an issue and we are happy to help out!
