### ISSUE TITLE
Google Photos: create multiple MediaItems per batchCreate API call

### ISSUE THREAD

**Issue by desliner** [rclone/rclone#3824]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.50.2

#### What problem are you are trying to solve?
Upload more than 10k items per day to Google Photos.

#### How do you think rclone should be changed to solve that?
Currently rclone calls mediaItems.batchCreate once per uploaded file with one MediaItem.
Since every API call counts towards 10k calls/day limit, it's impossible to upload more than 10k files in a single day.
rclone should be changed to call batchCreate with multiple uploaded MediaItems at once to reduce the number of API calls.

**Comment by ivandeex** [comment]
Inactive for 2 years
