### ISSUE TITLE
rclone genautocomplete for Windows

### ISSUE THREAD

**Issue by bingoxo** [rclone/rclone#3825]
#### What is your current rclone version (output from `rclone version`)?
1.50.2

#### What problem are you are trying to solve?

running rclone genautocomplete (bash) on Windows

it says "open /etc/bash_completion.d/rclone: The system cannot find the path specified"  because it's not a linux enviorement

**Comment by ncw** [comment]
You should be able to write the autocomplete file to another place and source it.

    rclone genautocomplete bash rclone-autocomplete.sh
    . rclone-autocomplete.sh

Does that work?

**Comment by bingoxo** [comment]
you can't run bash files in windows , i installed wsl (Windows Subsystem for Linux) but i still need to install a linux distro for bash to work which defeats the whole purpose , so i hope there is anoter way to run that script on Windows

**Comment by ncw** [comment]
Sorry I thought you were running under WSL.

As far as I know there isn't a way of doing command line completions in Windows itself (eg in CMD)

**Comment by animosity22** [comment]
This seems to be answered as auto complete is more a Linux thing than Windows. If you find some other way to do or a different suggestion, you can always ask on the forums.
