### ISSUE TITLE
sync: source Team Drive got removed (inaccessible), rclone deleted everything on the destination

### ISSUE THREAD

**Issue by minhng99** [rclone/rclone#3829]
Hi, I was experiencing a minor data loss with rclone and syncing Team Drive (Google drive):

I've set up a crontab to do `rclone sync` periodically between a Team Drive and a second GDrive account, when the Team Drive got removed from the source account, rclone thought I've deleted all of the files in it and started to delete it on the destination (second GDrive) as well.

I think rclone should've checked to see if the Team Drive actually exists before attempt to do any file retrieval/sync from it.

Fortunately, the deleted files are located in Trash so I've managed to restore them.

Thanks for this wonderful tool!

**Comment by Dibbyo456** [comment]
I’ve had the exact same issue before when I using it with a `.edu` account.

Next time use the syncing with `--backup-dir` to prevent data loss.

**Comment by ncw** [comment]
> I think rclone should've checked to see if the Team Drive actually exists before attempt to do any file retrieval/sync from it.

I think so too!

Are you saying that when you did `rclone ls` on the non existent team drive, rclone didn't return any errors?

If so I fixed something quite similar recently so could you try with [the latest beta](https://beta.rclone.org) to see if it is any different?

**Comment by minhng99** [comment]
Right! I've actually do a `lsd` to see if it would return any error but there's nothing returned at all, that makes me think that rclone has mistakenly thought the files is deleted but not because of the Team Drive is inaccessible. 

I'll try the beta version and will report back later.
Thanks
29 Dec 2019, 11:29 pm by notifications@github.com:

**Comment by minhng99** [comment]
Yup, that's worked, thank you.
Test result rclone v1.50.2-099-g69ac04fe-beta:
```
[user@E5-575 rclone-v1.50.2-099-g69ac04fe-beta-linux-amd64]$ ./rclone lsd glo_test:

2020/01/02 14:53:04 ERROR : : error listing: failed to get Team/Shared Drive info: googleapi: Error 404: Shared drive not found: xxx, notFound
2020/01/02 14:53:04 Failed to lsd with 2 errors: last error was: failed to get Team/Shared Drive info: googleapi: Error 404: Shared drive not found: xxx, notFound

```

**Comment by Dibbyo456** [comment]
@ncw thank you for the fix. However I was wondering what would happened when a google account (not team drive) is deleted/suspended (drive too), will rclone throw errors? Or it will delete files in the destination just like the OP’s issue?

**Comment by ncw** [comment]
@Dibbyo456  wrote:
> I was wondering what would happened when a google account (not team drive) is deleted/suspended (including drive), will rclone throw errors? Or it will delete files in the destination just like the OP’s issue?

If the account is suspended / deleted then rclone will throw authorization errors and stop.
