### ISSUE TITLE
The two docs are different

### ISSUE THREAD

**Issue by woytu** [rclone/rclone#3830]
* [https://tip.rclone.org/flags](https://tip.rclone.org/flags)
![image](https://user-images.githubusercontent.com/30252550/71544285-3cdc1900-29b8-11ea-812f-a0b8f889ccba.png)

* [https://rclone.org/flags](https://rclone.org/flags)
![image](https://user-images.githubusercontent.com/30252550/71544288-57ae8d80-29b8-11ea-8ac2-8dc1c2a31684.png)

**Comment by Cnly** [comment]
I think it's because the contents on tip.rclone.org are generated from the tip (master branch), and those from rclone.org from the latest release.

**Comment by ncw** [comment]
@Cnly is spot on.

I only update rclone.org on releases whereas tip.rclone.org gets generated once per day from the master branch.

I'll close this now.
