### ISSUE TITLE
rclone is re-copying files to AWS S3 Deep Archive even if they already exist

### ISSUE THREAD

**Issue by alexandernst** [rclone/rclone#3834]
#### What is the problem you are having with rclone?

rclone is re-copying files to AWS S3 Deep Archive even if they already exist

#### What is your rclone version (output from `rclone version`)

rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian 7
Linux xxxxxx 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux

####  Which cloud storage system are you using? (eg Google Drive)

AWS S3 Deep Archive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

    rclone copy --ignore-existing --progress --max-delete 0 "/var/vmail" foo-backups:foo-backups/vmail

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Unfortunately, I'm not able to provide a useful debug output.

Let me explain briefly what's happening: I have around 400.000 files (all the files in Dovecot's vmail dir). I'm trying to backup them all using rclone. The entire folder is 60GB (give or take a few MBs). I launched the command (the same that I provided a few lines ago) and let it finish copying the entire folder. I checked the total transferred size, the total received size in S3 and the total number of files in the bucket. They all matched up, which means that the copy process was finished successfully (there were no warnings/errores during the process).

Then I launched the command one more time and rclone started copying some files, while skipping other files. For granted, it started copying some `.log`, `.index` and `.cache` files, which I guess changes between the time the first command was run and the second command started running, but then it started copying some email files which I'm 100% confident that were already copied during the previous run.

**Comment by seizedengine** [comment]
Install this beta version, that fixes it. It is an issue with S3 pages. If your data has folders, youll likely notice that any folder with <999 items doesnt have any issues.

https://beta.rclone.org/branch/v1.50.2-085-g2dddcc52-fix-3799-s3-nextmarker-beta/

I just went though the same issue and this beta version is the fix.

**Comment by alexandernst** [comment]
Oh, great! When will that be available as a stable release?

**Comment by seizedengine** [comment]
I would assume quite soon, but I have no other issues with this beta one.

**Comment by ncw** [comment]
I'm winding up to do a release in the next week or two so quite soon!  The beta should be stable though.

**Comment by animosity22** [comment]
This looks to be fixed in the last stable release. If there is still a question, you can always ask on https://forums.rclone.org
