### ISSUE TITLE
Problem with encrypting certain unicode characters

### ISSUE THREAD

**Issue by SL-Gundam** [rclone/rclone#3836]
#### What is the problem you are having with rclone?
I was upgrading from 1.49.5  to 1.50.2 and Rclone suddenly wanted to reupload multiple files it shouldn't.
So after checking i found out that Rclone 1.50.2 does not like these filenames

> 1 a？a.zip
> 2 aaa？ ？ 01-04(a・a).zip
> 3 aaaaaa＊ aaaa.zip

It changes ＊ to * and ？to ? 
This is only an issue with the upload since data uploaded with 1.49.5 can be read just fine on another machine running 1.50.2 but data uploaded with 1.50.2 gets incorrect filenames

Uploaded using 1.49.5 and read using 1.50.2 (or 1.49.5 since it is the same) (mounted):
![Upload 1 49 5 read on 1 50 2](https://user-images.githubusercontent.com/912973/71607374-2fba5800-2b79-11ea-8d69-1143f03c1289.png)
Uploaded using 1.50.2 and read using 1.50.2 (mounted):
![Upload 1 50 2 read on 1 50 2](https://user-images.githubusercontent.com/912973/71607373-2f21c180-2b79-11ea-8650-48769d4c2666.png)

Rclonebrowser shows it like this.
TEST is uploaded using 1.49.5.
TEST2 is uploaded using 1.50.2.
Both were read using 1.50.2
![image](https://user-images.githubusercontent.com/912973/71607581-d0f5de00-2b7a-11ea-8a3b-64a267dcb76e.png)

#### What is your rclone version (output from `rclone version`)
rclone v1.49.5
- os/arch: windows/amd64
- go version: go1.12.10

Tested on 1.50.2 stable and latest beta (see below)
rclone v1.50.2-094-g207474ab-beta
- os/arch: windows/amd64
- go version: go1.13.5

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 1909 x64

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
"C:\\rclone\\rclone.exe" "sync" "--bwlimit" "3M" "--delete-after" "--delete-excluded" "--exclude-from" "C:/rclone/Configs/Exclusions.txt" "--progress" "--log-file" "C:\\Users\\Monkey\\Desktop\\MirrorD Log\\Rclone TEST 2019-12-31  24203.log" "--log-level" "DEBUG" "E:/Rclone test/" "cryptGDrive:TEST"

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
[Rclone 1.49.5 TEST 2019-12-31  24203.log.txt](https://github.com/rclone/rclone/files/4011695/Rclone.1.49.5.TEST.2019-12-31.24203.log.txt)
[Rclone 1.50.2 TEST 2019-12-31  24205.log.txt](https://github.com/rclone/rclone/files/4011696/Rclone.1.50.2.TEST.2019-12-31.24205.log.txt)

#### Sidenote
The output console is also showing issues again with unicode characters (japanese in this case). This was fixed here https://github.com/rclone/rclone/issues/2501 and worked fine until 1.49.5. Should i create a separate issue for that or is the above related?
![Output console issue](https://user-images.githubusercontent.com/912973/71607444-d0a91300-2b79-11ea-9a03-2c9090893add.png)

**Comment by SL-Gundam** [comment]
Apparently this is an issue having to do with this: https://rclone.org/local/#restricted-characters

Based on this it seems Rclone does not normalize anymore (deprecation of https://rclone.org/local/#local-no-unicode-normalization). Should not be an issue. But instead it de-normalizes things which is an issue.

**Comment by ncw** [comment]
> Apparently this is an issue having to do with this: https://rclone.org/local/#restricted-characters

That is correct.  Rclone is doing translations of file characters on cloud storage systems that have restricted characters.

In this case it is Windows that has the restricted file name characters.  So if you download a file from google drive with 1.50 that has a `*` in then rclone will translate it into `＊` for windows.  It also does the translations in the other direction.

I think this is what you are seeing.

So you could rename the troublesome files on the google drive web interface from  `＊` to `*` etc and rclone syncing will work from there on with v1.50 (or you could get rclone to do it for you with --track-renames).

Is this a good solution for you?

**Comment by SL-Gundam** [comment]
In this case i have local windows filenames that have ＊ that are uploaded as * and downloaded as *
So it does it the incorrect way (de-normalization)
--track-renames does not work with crypt

I only upload files from local to gdrive. So rclone should grab the filenames as-is

**Comment by SL-Gundam** [comment]
Just to clarify.
I understand this conversion during upload if the situation applies for the destination (which isn't the case for CRYPT if filename encryption is turned ON): * -> ＊
I do not understand this one during upload: ＊ -> *
Rclone should only change filenames when it has no choice

The reason this is an issue for me is that i have a NAS running a variant of linux. I've mounted Rclone on there. Linux apparently has no issues with * and ?
But i'm accessing the mounted rclone through an SMB share from a windows system. SMB and Windows don't like it very much

**Comment by ncw** [comment]
Ah, I see...

To fix the problem without doing anything to rclone, what you'd do is rename your local files by putting a `‛` character in front of the troublesome characters, so `＊` would become `‛＊`.  This tells rclone not to translate the `＊` so the file will have a `＊` in on drive.

I understand you probably don't want to do this though!

I'm thinking about adding a flag to disable all the character mappings - would that suit you?

**Comment by SL-Gundam** [comment]
I think its easier that i just keep on running 1.49.5. There is no real reason for me to upgrade to 1.50.2 other then running the latest version.

I think the suggested change should suit me just fine. Thank you

**Comment by ncw** [comment]
OK I'll do that change then you can update to 1.51 :-)

**Comment by ncw** [comment]
Please can you try this with the `--local-encoding None` flag?  You can put that as `encoding = None` in your config.

That disables the character name conversion and should fix the problem for you.

https://beta.rclone.org/branch/v1.50.2-140-g222f1e7d-fix-encodings-beta/ (uploaded in 15-30 mins)

**Comment by SL-Gundam** [comment]
--local-encoding None -> Works
encoding = None -> Does not work. I expect thats because i have the path for the local source in commandline and its not a source in the config file like GDrive

**Comment by ncw** [comment]
> --local-encoding None -> Works

great!

> encoding = None -> Does not work. I expect thats because i have the path for the local source in commandline and its not a source in the config file like GDrive

You can set an environmnent variable `RCLONE_LOCAL_ENCODING=None` or you can make a local backend in the config, say

```
[local]
type = local
encoding = None
```

And use `rclone copy local:/path/to/files remote:dir` etc

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.51

**Comment by SL-Gundam** [comment]
One small thing I've found.
The mount on the NAS gets situations like these: ‛／
It should have only been this: ／
I think this is because the mount does not use a local source/destination and ignores the local encoding parameter. Also tried the local encoding on the command line but makes no difference.

**Comment by ncw** [comment]
> I think this is because the mount does not use a local source/destination and ignores the local encoding parameter. Also tried the local encoding on the command line but makes no difference.

Are you mounting a google drive? If so then you might want to try `--drive-encoding Slash,InvalidUtf8` to see if that helps.

**Comment by SL-Gundam** [comment]
Yes its google drive

Hmmm did some testing.
The quote is added during the upload before unicode slash characters (／)
Should "encoding = None" have prevented that?
The quote is not removed when the google drive is mounted on my NAS.

rclone mount --umask 0 --allow-other --daemon --local-encoding None --drive-encoding Slash,InvalidUtf8 --log-file "/share/rCloneMount/Rclone Mount.log" --log-level INFO cryptGDcache: /share/rCloneMount/Crypt

**Comment by ncw** [comment]
I'm confused now about what you started with and what you got! Can you make step by step instructions for me please - thanks!

**Comment by SL-Gundam** [comment]
This command syncs a file called "aaa ／aaa／.mp4" to Google drive
```
C:\rclone\rclone.exe sync --bwlimit 3M --delete-after --delete-excluded --exclude-from "C:/rclone/Configs/Exclusions.txt" --progress --log-file "C:\Users\Name\Desktop\MirrorD Log\Rclone TEST.log" --log-level DEBUG "local:E:/Rclone test/" cryptGDrive:TEST
```

The local part of the config file
```
[local]
type = local
encoding = None
```

The earlier mount does not remove the quote that is added during the upload with the sync command above. Would not be an issue if the upload would never add it in the first place.

Here is the debug log of rclone sync

> 2020/02/06 17:50:52 DEBUG : rclone: Version "v1.51.0" starting with parameters ["C:\\rclone\\rclone.exe" "sync" "--bwlimit" "3M" "--delete-after" "--delete-excluded" "--exclude-from" "C:/rclone/Configs/Exclusions.txt" "--progress" "--log-file" "C:\\Users\\Name\\Desktop\\MirrorD Log\\Rclone TEST 2020-02-06 175052.log" "--log-level" "DEBUG" "local:E:/Rclone test/" "cryptGDrive:TEST"]
> 2020/02/06 17:50:52 DEBUG : Using config file from "C:\\Users\\Name\\.config\\rclone\\rclone.conf"
> 2020/02/06 17:50:52 INFO  : Starting bandwidth limiter at 3MBytes/s
> 2020/02/06 17:50:52 DEBUG : remoteGDrive: Loaded invalid token from config file - ignoring
> 2020/02/06 17:50:53 DEBUG : Keeping previous permissions for config file: -rw-rw-rw-
> 2020/02/06 17:50:53 DEBUG : remoteGDrive: Saved new token in config file
> 2020/02/06 17:50:55 INFO  : Encrypted drive 'cryptGDrive:TEST': Waiting for checks to finish
> 2020/02/06 17:50:55 INFO  : Encrypted drive 'cryptGDrive:TEST': Waiting for transfers to finish
> 2020/02/06 17:50:56 DEBUG : m70bedopcrqk037bhmeb8tjquqaav3286rlnnjdiafbe2pads8tg: Sending chunk 0 length 8388608
> 2020/02/06 17:50:58 DEBUG : m70bedopcrqk037bhmeb8tjquqaav3286rlnnjdiafbe2pads8tg: Sending chunk 8388608 length 8388608
> ...
> 2020/02/06 17:58:21 DEBUG : m70bedopcrqk037bhmeb8tjquqaav3286rlnnjdiafbe2pads8tg: Sending chunk 1384120320 length 8388608
> 2020/02/06 17:58:24 DEBUG : m70bedopcrqk037bhmeb8tjquqaav3286rlnnjdiafbe2pads8tg: Sending chunk 1392508928 length 6567566
> 2020/02/06 17:58:28 INFO  : aaa ‛／aaa‛／.mp4: Copied (new)
> 2020/02/06 17:58:28 INFO  : Waiting for deletions to finish
> 2020/02/06 17:58:29 INFO  : bbb.mp4: Deleted
> 2020/02/06 17:58:29 INFO  : 
> Transferred:   	    1.303G / 1.303 GBytes, 100%, 2.943 MBytes/s, ETA 0s
> Checks:                 1 / 1, 100%
> Deleted:                1
> Transferred:            1 / 1, 100%
> Elapsed time:      7m33.4s
> 
> 2020/02/06 17:58:29 DEBUG : 5 go routines active
> 2020/02/06 17:58:29 DEBUG : rclone: Version "v1.51.0" finishing with parameters ["C:\\rclone\\rclone.exe" "sync" "--bwlimit" "3M" "--delete-after" "--delete-excluded" "--exclude-from" "C:/rclone/Configs/Exclusions.txt" "--progress" "--log-file" "C:\\Users\\Name\\Desktop\\MirrorD Log\\Rclone TEST 2020-02-06 175052.log" "--log-level" "DEBUG" "local:E:/Rclone test/" "cryptGDrive:TEST"]
>

**Comment by SL-Gundam** [comment]
Do you prefer i open a new issue for this?
