### ISSUE TITLE
rclonelink failure on fat32 usb drive [solved]

### ISSUE THREAD

**Issue by DoctorSubtilis** [rclone/rclone#3838]
#### 1 problem
when I try to copy/sync my folder from local (Pc with KDE Neon) to an usb fat32 pen-drive, I get errors with symlinks:

`ERROR : letteratura/Claudel, Le soulier de satin.epub.rclonelink: Failed to copy: symlink in francese/Claudel, Le soulier de satin.epub /media/duns/likebook/ebooks/letteratura/Claudel, Le soulier de satin.epub: operation not permitted`

#### 2 problem
Besides, the sync operation seems in loop (never ending, because of updating "modification time" of many (maybe all) the files).  
This problem is avoided if I add --no-update-modtime, but this way syncro is still working?

#### What is your rclone version (output from `rclone version`)

rclone v1.50.2  
- os/arch: linux/amd64  
- go version: go1.13.4  

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux KDE Neon

This is the row of fstab:  
`LABEL=SCHEDA-LIKE /media/duns/likebook vfat user,rw,noauto,uid=1000,gid=1000,utf8 1 2`

####  Which cloud storage system are you using? (eg Google Drive)

local  
* usb pen-drive fat32
* usb e-book (mass storage)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync /mnt/zippati/ebooks/ebooks likebook:/media/duns/likebook/ebooks -l -v

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I am not able to find it, sorry

**Comment by ncw** [comment]
Fat32 file systems don't support symlinks so remove -l

Adding --modify-window 2s should fix the other problem as fat32 file systems only store times accurate to 1 or 2 seconds

**Comment by DoctorSubtilis** [comment]
Thank you!
Any way it's strange, because how can system recognise a .rclonelink file as a symlink, while Dolphin, i.g. see it as a plain text file?  
So, the only way to get symlinks on fat32 filesystem is posixovl? Any possible workaround for rclone symlinks on fat32?

**Comment by ncw** [comment]
> Any way it's strange, because how can system recognise a .rclonelink file as a symlink, while Dolphin, i.g. see it as a plain text file?

Cloud storage providers don't understand symlinks so rclone converted them back and forth between the `.rclonelink` format.



> So, the only way to get symlinks on fat32 filesystem is posixovl? Any possible workaround for rclone symlinks on fat32?

What would you think about being able to copy the .rclonelink files onto the fat32 then convert them back into symlinks when copying them off?

You could probably do that by two new `local` backends, one with `links` and one without and copying between them.

**Comment by DoctorSubtilis** [comment]
Thank you.
1. I don't understand how it is impossible a direct copy of the (plain text) file .rclonelink. Why posixovl can dupe, so to say, the system (copying hidden files as symlinks) and rclone can't? I don't understand why it is impossible to copy a trivial plain text file...
2. I will try your workaround, even I'm not sure to understand what you mean.

**Comment by ncw** [comment]
> 1. I don't understand how it is impossible a direct copy of the (plain text) file .rclonelink. Why posixovl can dupe, so to say, the system (copying hidden files as symlinks) and rclone can't? I don't understand why it is impossible to copy a trivial plain text file...

It is because you are copying from `local` backend to `local` backend.  when you set `-l` the local backend shows the links as `file.rclonelink` and also writes files it receives like that as symlinks.

Try this

** /tmp/rclone.conf **

```
[link]
type = local
links = true

[nolink]
type = local
```

then

    rclone sync --config /tmp/rclone.conf link:/path/to/files nolink:/path/to/usb/fat32 -v

**Comment by DoctorSubtilis** [comment]
Perfect! So it works. And it is better than posixovl, because is more simply: as said [Ockham](https://en.wikipedia.org/wiki/Occam%27s_razor), _frustra fit per multa quod fieri potest per pauciora_ ("Entities should not be multiplied without necessity").
Thank you very much!

**Comment by DoctorSubtilis** [comment]
Sorry: there is another problem. The sign "**:**" not correctly "translated" to fat32: it become "**%(3A)**".
What could I do to avoid this?

**Comment by ncw** [comment]
What you need is to be able to set the encoding for your fat32 remote:.  This isn't available yet, but I'm working on it very soon!

**Comment by DoctorSubtilis** [comment]
OK, thank you!

**Comment by animosity22** [comment]
This was solved.

**Comment by animosity22** [comment]
Oh sorry, I misread as the title was updated, but there is still an issue. Sorry!

**Comment by animosity22** [comment]
I can't tell if I'm losing my mind. The title says solved  so I had closed it, but I re-opened it so not sure if I had a senior moment or not.

If it should be open, please let me know.
