### ISSUE TITLE
onedrive: Problem on interpreting "＃"

### ISSUE THREAD

**Issue by outloudvi** [rclone/rclone#3841]
#### What is the problem you are having with rclone?

Onedrive backend had some problems interpreting filenames including "＃". When I was uploading a file containing "＃" - let's say, "p136_心拍数＃0822.mp3" - I see a file named "p136_心拍数‛＃0822.mp3" (with an extra quotation mark before the full-width number sign) on OneDrive WebUI.

This problem doesn't happen on S3 backend AFAIK, so I think it's a problem on OneDrive backend.

#### What is your rclone version (output from `rclone version`)

v1.50.2-DEV, as well as [`207474aba`](https://github.com/rclone/rclone/commit/207474ababb22a1c2f85bf26c8f2e4dffd258c0e).

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Arch Linux, 64 bit,

####  Which cloud storage system are you using? (eg Google Drive)

OneDrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
rclone copy p136_心拍数＃0822.mp3 t:/test
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2020/01/01 22:33:02 DEBUG : rclone: Version "v1.50.2-DEV" starting with parameters ["/home/user/go/bin/rclone" "copy" "p136_心拍数＃0822.mp3" "t:/test" "-vv"]
2020/01/01 22:33:02 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2020/01/01 22:33:02 DEBUG : t: Loaded invalid token from config file - ignoring
2020/01/01 22:33:06 DEBUG : Keeping previous permissions for config file: -rw-r--r--
2020/01/01 22:33:06 DEBUG : t: Saved new token in config file
2020/01/01 22:33:11 DEBUG : p136_心拍数＃0822.mp3: Need to transfer - File not found at Destination
2020/01/01 22:33:11 DEBUG : p136_心拍数＃0822.mp3: Starting multipart upload
2020/01/01 22:33:12 DEBUG : p136_心拍数＃0822.mp3: Uploading segment 0/12810405 size 10485760
2020/01/01 22:33:26 DEBUG : p136_心拍数＃0822.mp3: Uploading segment 10485760/12810405 size 2324645
2020/01/01 22:33:29 DEBUG : p136_心拍数＃0822.mp3: SHA-1 = e7e2efdf3513204f9ceacecc64c5062d8f01ce90 OK
2020/01/01 22:33:29 INFO  : p136_心拍数＃0822.mp3: Copied (new)
2020/01/01 22:33:29 INFO  : 
Transferred:       12.217M / 12.217 MBytes, 100%, 711.002 kBytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:       17.5s

2020/01/01 22:33:29 DEBUG : 10 go routines active
2020/01/01 22:33:29 DEBUG : rclone: Version "v1.50.2-DEV" finishing with parameters ["/home/user/go/bin/rclone" "copy" "p136_心拍数＃0822.mp3" "t:/test" "-vv"]
```

**Comment by outloudvi** [comment]
Here are some tests:

| Changes | On OneDrive WebUI | On rclone |
| --- | --- | --- |
| None | foo‛＃bar.txt | foo＃bar.txt |
| None | foo＃baz.txt | foo#baz.txt |
| Remove `EncodeHash`* | foo‛＃bar.txt | foo‛‛＃bar.txt |
| Remove `EncodeHash`* | foo＃baz.txt | foo＃baz.txt (which is the same) |

\* means replacing `encoder.EncodeHashPercent` [here](https://github.com/rclone/rclone/blob/master/fs/encodings/encodings.go#L190) to `encoder.EncodePercent`.

**Comment by Cnly** [comment]
Just a quick thought but it looks #3723 may be related.

**Comment by ncw** [comment]
Onedrive filenames can't have `#` characters in them.  So to allow this rclone encodes them as `＃` (the full width unicode equivalent.

However if you do have files with `＃` in like you do then rclone will escape them with  `‛` so making `‛＃` as you've seen.

These files will round-trip back and forth with rclone properly, however will appear in the onedrive listing with the extra  `‛` 

So provided you use rclone to list/transfer files you'll never notice the extra  `‛` .

What problem is this causing you?

Maybe I should allow the escaping to be disabled - what do you think?

**Comment by outloudvi** [comment]
I think that OneDrive is now accepting `#` as part of the filename. I'm able to upload files with such filename and the filename of that file can be correctly displayed on Windows (at least non-UWP) client, Android client and WebUI.

From documentation and discussions on Microsoft, it seems that [# and % can be supported](https://techcommunity.microsoft.com/t5/microsoft-sharepoint-blog/new-support-for-and-in-sharepoint-online-and-onedrive-for/ba-p/60357) by Sharepoint administrators flipping a switch.

Another documentation listed [here](https://support.office.com/en-us/article/Invalid-file-names-and-file-types-in-OneDrive-OneDrive-for-Business-and-SharePoint-64883a5d-228e-48f5-b3d2-eb39e07630fa#invalidcharacters) also confirms that `#` and `%` are allowed for new versions of OneDrive. So maybe we can allow the escaping to be disabled, or even just remove the escaping altogether.

**Comment by ncw** [comment]
Thanks for looking that up!  So it looks like I need to make the encoding configurable - if I change it it will break the usage for existing users probably....

**Comment by ncw** [comment]
Please can you try this with the `--onedrive-encoding None` flag?  You can put that as `encoding = None` in your config.

That disables the character name conversion and should fix the problem for you.

https://beta.rclone.org/branch/v1.50.2-140-g222f1e7d-fix-encodings-beta/ (uploaded in 15-30 mins)

**Comment by outloudvi** [comment]
With the build you mentioned above, I can confirm that:
* Uploading/downloading file whose name contains "#" is working.
* Uploading/downloading file whose name contains "＃" is working.
* Uploading/downloading file whose name contains "＃" and "#" is working, in which case both of the symbols are intact.

**Comment by ncw** [comment]
Great :-)  Thanks for testing.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.51

**Comment by zhucan** [comment]
> Please can you try this with the `--onedrive-encoding None` flag? You can put that as `encoding = None` in your config.
> 
> That disables the character name conversion and should fix the problem for you.
> 
> https://beta.rclone.org/branch/v1.50.2-140-g222f1e7d-fix-encodings-beta/ (uploaded in 15-30 mins)

how to deal with 's3: Problem on interpreting "." ' ?

**Comment by ncw** [comment]
> how to deal with 's3: Problem on interpreting "." ' ?

@zhucan Can you ask on [the rclone forum](https://forum.rclone.org/) with more details please? - Thanks
