### ISSUE TITLE
If rclone.conf is a symlink, it is rewrited on 'rclone config'

### ISSUE THREAD

**Issue by acs-ferreira** [rclone/rclone#3845]
1. Make `rclone.conf` a symlink
2. Run `rclone config` and write a new remote
3. `rclone.conf` is no more a symlink

**Comment by ncw** [comment]
Rclone uses a two phase strategy for updating the config file
- write a new `config.new`
- rename `config` to `config.old` and rename `config.new` to config`

This is to make sure there is always a valid config file and it doesn't get corrupted if the disk gets full (for example).

Now that doesn't work if the config file is a symlink...

What do you think rclone should do if the config is a symlink?

Alternatively you could put the actual config in the `--config` parameter?

**Comment by acs-ferreira** [comment]
I'm sharing the config between many hosts, so a symlink to a mount point was an option.
I'm using `lsyncd` now, but i believe that destroying a symlink on a file edit/update is not a good behavior.

If that's not you opinion, feel free to close :)

**Comment by ncw** [comment]
> I'm sharing the config between many hosts, so a symlink to a mount point was an option.

I see!

I think since you've solved this problem with `lsyncd` I'll close this and see if anyone else has the problem since I'm not sure of the best solution!
