### ISSUE TITLE
Memory Leak when used heavily

### ISSUE THREAD

**Issue by fionera** [rclone/rclone#3846]
#### What is the problem you are having with rclone?
After about 3 Days of using `serve http` with about 7Gbit continuously you can observe that rclone leaks memory. I dont know where yet :tm:, but even after multiple restarts it still happens.

#### What is your rclone version (output from `rclone version`)
1.50.2

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu Server 64bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone serve http drive:

**Comment by ncw** [comment]
Can you run with the `--rc` parameter and grab some memory dumps as per here: https://rclone.org/rc/#debugging-memory-use - also go routine dumps would be useful too https://rclone.org/rc/#debugging-go-routine-leaks

If you could do one when it has built up a bit and another when it has built up a bit more that would be perfect.

Thanks

**Comment by animosity22** [comment]
@fionera  - any update?

**Comment by fionera** [comment]
I currently cannot test this as I dont have a node with the free capacity. As soon as I have it running again I will report

**Comment by animosity22** [comment]
@fionera  - any updates?

**Comment by animosity22** [comment]
This seems to be stale. If you want to troubleshoot, we can help out on the forums. Please post on https://forums.rclone.org and we can assist. 

Thanks!
