### ISSUE TITLE
Issue with speed of upload to mega / Windows 10

### ISSUE THREAD

**Issue by caspertone2003** [rclone/rclone#3849]
Windows 10, x64
RClone 1.50.2

While I have already searched in the issue track and forum, and there are some threads there, I believe the issue has not been really identified and solved.
Topic is related to uploads to mega remote. Have not tested with other remotes though.
Upload seems to start with nice transfer speed, then to reduce to zero exponentially. I tried with several --bwlimit values to no avail. Note that logging with -vv is not producing any interesting output.

I checked down/up throughput (via http using some webs) and got 3.5/2 MiB/s (usually I got ten times but now I moved away of the AP - note that issues where already taking place before getting away)
I did same uploading to mega using megatools, and got around 3MiB/s upload speeds.

Why happens with rclone? Look to the following log:

====================================================
move to remote, -vv, without -bwlimit specified

Transferred:   	       79M / 906.059 MBytes, 9%, 1.317 MBytes/s, ETA 10m28s
Errors:                 0
Checks:                 0 / 2, 0%
Transferred:            0 / 2, 0%
Elapsed time:       59.9s
Checking:
 * Video/…236054CC9DFEBB5963.mp4:  5% /492.815M, 120.127k/s, 1h6m14s
 * Video/…3860EB26D2797AE59B.mp4: 12% /413.244M, 900.155k/s, 6m50s
Transferring:
 * Video/…236054CC9DFEBB5963.mp4:  5% /492.815M, 120.127k/s, 1h6m14s
 * Video/…3860EB26D2797AE59B.mp4: 12% /413.244M, 900.155k/s, 6m50s

2020/01/03 19:59:50 INFO  : 
Transferred:   	      130M / 906.059 MBytes, 14%, 1.083 MBytes/s, ETA 11m56s
Errors:                 0
Checks:                 0 / 2, 0%
Transferred:            0 / 2, 0%
Elapsed time:        2m0s
Checking:
 * Video/…236054CC9DFEBB5963.mp4: 12% /492.815M, 256.306k/s, 28m39s
 * Video/…3860EB26D2797AE59B.mp4: 16% /413.244M, 64.615k/s, 1h31m19s
Transferring:
 * Video/…236054CC9DFEBB5963.mp4: 12% /492.815M, 256.306k/s, 28m39s
 * Video/…3860EB26D2797AE59B.mp4: 16% /413.244M, 64.615k/s, 1h31m19s

2020/01/03 20:00:50 INFO  : 
Transferred:   	      130M / 906.059 MBytes, 14%, 739.579 kBytes/s, ETA 17m54s
Errors:                 0
Checks:                 0 / 2, 0%
Transferred:            0 / 2, 0%
Elapsed time:     2m59.9s
Checking:
 * Video/…236054CC9DFEBB5963.mp4: 12% /492.815M, 5.688k/s, 21h30m50s
 * Video/…3860EB26D2797AE59B.mp4: 16% /413.244M, 1.344k/s, 73h8m13s
Transferring:
 * Video/…236054CC9DFEBB5963.mp4: 12% /492.815M, 5.688k/s, 21h30m50s
 * Video/…3860EB26D2797AE59B.mp4: 16% /413.244M, 1.344k/s, 73h8m13s

2020/01/03 20:01:50 INFO  : 
Transferred:   	      130M / 906.059 MBytes, 14%, 554.593 kBytes/s, ETA 23m52s
Errors:                 0
Checks:                 0 / 2, 0%
Transferred:            0 / 2, 0%
Elapsed time:        4m0s
Checking:
 * Video/…236054CC9DFEBB5963.mp4: 12% /492.815M, 113/s, 1102h44m23s
 * Video/…3860EB26D2797AE59B.mp4: 16% /413.244M, 26/s, 3748h46m17s
Transferring:
 * Video/…236054CC9DFEBB5963.mp4: 12% /492.815M, 113/s, 1102h44m23s
 * Video/…3860EB26D2797AE59B.mp4: 16% /413.244M, 26/s, 3748h46m17s

aborted there!

===============================================

The usual answers I read had been that RClone "kills" LANs with issues, such as an AP that gets
blocked, or the router.
Well, I tried same above with -bwlimit=50k (yes, I know it is kBytes/s not kbits/s) and same happens.

I would be more ready to accept a lan issue should it not be that megatools is able to upload sustaniably at 3MiB/s .... 
Perhaps it is the LAN (megatools drops some times to 2MiBs/s even to zero, but raises again - it even drops a chunk almost every transfer). But megatools seems able to cope with any LAN issue while RClone (standard configuration) looks more pricky or less prepared to deal with such situation.

Is there anything I could configure in RClone to avoid the situation?
Is there any test you would propose to identify/isolate any potential bug?

TIA
CT

**Comment by caspertone2003** [comment]
I have some other information....
Some transfers died due to:

2020/01/04 02:28:50 INFO  : *go-mega*: pollEvents: Error fetching status: Post https://g.api.mega.co.nz/sc?sn=xxxxofuscatedxxxx: dial tcp 31.216.147.133:443: i/o timeout

i tested and did not *notice* any connectivity nor dns issues... but know nows...

**Comment by ncw** [comment]
> 2020/01/04 02:28:50 INFO : _go-mega_: pollEvents: Error fetching status: Post https://g.api.mega.co.nz/sc?sn=xxxxofuscatedxxxx: dial tcp 31.216.147.133:443: i/o timeout

I don't think that should be a fatal error - rclone should carry on after that.

I wonder whether the whole situation is caused by rate limiting by mega?  Is that possible do you think?

**Comment by caspertone2003** [comment]
As said, megatools was uploading consistently well while rclone was showing those issues.
I use regularly my own user-agent so to try to avoid any profiling of mega to rclone.
So, no, I do not believe it is a rate limiting thing.
Thanks

**Comment by ncw** [comment]
The upload for mega isn't as efficient as it could be, I know that, but it should perform OK.

> 2020/01/04 02:14:14 INFO : _go-mega_: pollEvents: Error fetching status: Post https://g.api.mega.co.nz/sc?sn=xxxxxofuscatedxxxxx: dial tcp: lookup g.api.mega.co.nz: no such host

That looks like maybe a local networking with the resolver on your network which is very odd.

One thing to note is that rclone will use IPv6 if it is available so that could be a difference. Use the `--bind` parameter to bind to an IPv4 address to avoid this.

**Comment by animosity22** [comment]
If you still have a performance type use question, please just ask on the forums https://forums.rclone.org as this seems stale.
