### ISSUE TITLE
drive: --fast-list/ListR doesn't work with root_folder_id = appDataFolder

### ISSUE THREAD

**Issue by 1xe** [rclone/rclone#3851]
#### What is the problem you are having with rclone?
`--fast-list/ListR` doesn't work with `root_folder_id = appDataFolder`.

See https://forum.rclone.org/t/rclone-rc-vfs-refresh-recursive-true-seems-to-clear-the-directory-cache/13657 for more information.

#### What is your rclone version (output from `rclone version`)
    rclone v1.50.2
    - os/arch: linux/amd64
    - go version: go1.13.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Devuan GNU/Linux 3 (beowulf) (Linux version 4.19.67, x86_64)

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
    /usr/bin/rclone mount rclone-crypt: /mnt/remote --buffer-size=256M --cache-dir=/mnt/local/.cache/rclone --config=/etc/rclone/rclone.conf --fast-list --links --rc --rc-no-auth --timeout=1h --allow-other --attr-timeout=8760h --default-permissions --dir-cache-time=8760h --poll-interval=0 --umask=002 --vfs-cache-mode=writes -vv

    /usr/bin/rclone rc vfs/refresh recursive=true --config=/etc/rclone/rclone.conf -vv

    ls -l /mnt/remote

    /usr/bin/rclone rc vfs/refresh recursive=false --config=/etc/rclone/rclone.conf -vv

    ls -l /mnt/remote

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Log for `rclone mount` (formatted for readability)

    # /usr/bin/rclone mount rclone-crypt: /mnt/remote --buffer-size=256M --cache-dir=/mnt/local/.cache/rclone --config=/etc/rclone/rclone.conf --fast-list --links --rc --rc-no-auth --timeout=1h --allow-other --attr-timeout=8760h --default-permissions --dir-cache-time=8760h --poll-interval=0 --umask=002 --vfs-cache-mode=writes -vv
    2020/01/03 16:33:19 DEBUG : rclone: Version "v1.50.2" starting with parameters ["/usr/bin/rclone" "mount" "rclone-crypt:" "/mnt/remote" "--buffer-size=256M" "--cache-dir=/mnt/local/.cache/rclone" "--config=/etc/rclone/rclone.conf" "--fast-list" "--links" "--rc" "--rc-no-auth" "--timeout=1h" "--allow-other" "--attr-timeout=8760h" "--default-permissions" "--dir-cache-time=8760h" "--poll-interval=0" "--umask=002" "--vfs-cache-mode=writes" "-vv"]
    2020/01/03 16:33:19 NOTICE: Serving remote control on http://127.0.0.1:5572/
    2020/01/03 16:33:19 DEBUG : Using config file from "/etc/rclone/rclone.conf"
    2020/01/03 16:33:19 DEBUG : Encrypted drive 'rclone-crypt:': Mounting on "/mnt/remote"
    2020/01/03 16:33:20 DEBUG : vfs cache root is "/mnt/local/.cache/rclone/vfs/rclone-crypt"
    2020/01/03 16:33:20 DEBUG : Adding path "vfs/forget" to remote control registry
    2020/01/03 16:33:20 DEBUG : Adding path "vfs/refresh" to remote control registry
    2020/01/03 16:33:20 DEBUG : Adding path "vfs/poll-interval" to remote control registry
    2020/01/03 16:33:20 DEBUG : : Root: 
    2020/01/03 16:33:20 DEBUG : : >Root: node=/, err=<nil>

    2020/01/03 16:35:00 DEBUG : rc: "vfs/refresh": with parameters map[recursive:true]
    2020/01/03 16:35:00 DEBUG : : Reading directory tree
    2020/01/03 16:35:01 DEBUG : : Reading directory tree done in 309.447146ms
    2020/01/03 16:35:01 DEBUG : rc: "vfs/refresh": reply map[result:map[:OK]]: <nil>

    2020/01/03 16:35:51 DEBUG : /: Attr: 
    2020/01/03 16:35:51 DEBUG : /: >Attr: attr=valid=8760h0m0s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
    2020/01/03 16:35:51 DEBUG : /: ReadDirAll: 
    2020/01/03 16:35:51 DEBUG : /: >ReadDirAll: item=0, err=<nil>

    2020/01/03 16:36:21 DEBUG : rc: "vfs/refresh": with parameters map[recursive:false]
    2020/01/03 16:36:21 DEBUG : rc: "vfs/refresh": reply map[result:map[:OK]]: <nil>

    2020/01/03 16:36:52 DEBUG : /: Attr: 
    2020/01/03 16:36:52 DEBUG : /: >Attr: attr=valid=8760h0m0s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
    2020/01/03 16:36:52 DEBUG : /: ReadDirAll: 
    2020/01/03 16:36:52 DEBUG : /: >ReadDirAll: item=4, err=<nil>
    2020/01/03 16:36:52 DEBUG : /: Attr: 
    2020/01/03 16:36:52 DEBUG : /: >Attr: attr=valid=8760h0m0s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
    2020/01/03 16:36:52 DEBUG : /: Lookup: name="dir1"
    2020/01/03 16:36:52 DEBUG : /: >Lookup: node=dir1/, err=<nil>
    2020/01/03 16:36:52 DEBUG : dir1/: Attr: 
    2020/01/03 16:36:52 DEBUG : dir1/: >Attr: attr=valid=8760h0m0s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
    2020/01/03 16:36:52 DEBUG : /: Lookup: name="dir2"
    2020/01/03 16:36:52 DEBUG : /: >Lookup: node=dir2/, err=<nil>
    2020/01/03 16:36:52 DEBUG : dir2/: Attr: 
    2020/01/03 16:36:52 DEBUG : dir2/: >Attr: attr=valid=8760h0m0s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
    2020/01/03 16:36:52 DEBUG : /: Lookup: name="file1"
    2020/01/03 16:36:52 DEBUG : /: >Lookup: node=file1, err=<nil>
    2020/01/03 16:36:52 DEBUG : file1: Attr: 
    2020/01/03 16:36:52 DEBUG : file1: >Attr: a=valid=8760h0m0s ino=0 size=0 mode=-rw-rw-r--, err=<nil>
    2020/01/03 16:36:52 DEBUG : /: Lookup: name="dir3"
    2020/01/03 16:36:52 DEBUG : /: >Lookup: node=dir3/, err=<nil>
    2020/01/03 16:36:52 DEBUG : dir3/: Attr: 
    2020/01/03 16:36:52 DEBUG : dir3/: >Attr: attr=valid=8760h0m0s ino=0 size=0 mode=drwxrwxr-x, err=<nil>

    ^C2020/01/03 16:37:50 DEBUG : cache cleaner exiting
    2020/01/03 16:37:50 DEBUG : rclone: Version "v1.50.2" finishing with parameters ["/usr/bin/rclone" "mount" "rclone-crypt:" "/mnt/remote" "--buffer-size=256M" "--cache-dir=/mnt/local/.cache/rclone" "--config=/etc/rclone/rclone.conf" "--fast-list" "--links" "--rc" "--rc-no-auth" "--timeout=1h" "--allow-other" "--attr-timeout=8760h" "--default-permissions" "--dir-cache-time=8760h" "--poll-interval=0" "--umask=002" "--vfs-cache-mode=writes" "-vv"]
    # 

Log for `rclone rc` + `ls` (formatted for readability)

    # /usr/bin/rclone rc vfs/refresh recursive=true --config=/etc/rclone/rclone.conf -vv
    2020/01/03 16:35:00 DEBUG : rclone: Version "v1.50.2" starting with parameters ["/usr/bin/rclone" "rc" "vfs/refresh" "recursive=true" "--config=/etc/rclone/rclone.conf" "-vv"]
    {
        "result": {
            "": "OK"
        }
    }
    2020/01/03 16:35:01 DEBUG : 5 go routines active
    2020/01/03 16:35:01 DEBUG : rclone: Version "v1.50.2" finishing with parameters ["/usr/bin/rclone" "rc" "vfs/refresh" "recursive=true" "--config=/etc/rclone/rclone.conf" "-vv"]

    # ls -l /mnt/remote
    total 0

    # /usr/bin/rclone rc vfs/refresh recursive=false --config=/etc/rclone/rclone.conf -vv
    2020/01/03 16:36:21 DEBUG : rclone: Version "v1.50.2" starting with parameters ["/usr/bin/rclone" "rc" "vfs/refresh" "recursive=false" "--config=/etc/rclone/rclone.conf" "-vv"]
    {
        "result": {
            "": "OK"
        }
    }
    2020/01/03 16:36:21 DEBUG : 5 go routines active
    2020/01/03 16:36:21 DEBUG : rclone: Version "v1.50.2" finishing with parameters ["/usr/bin/rclone" "rc" "vfs/refresh" "recursive=false" "--config=/etc/rclone/rclone.conf" "-vv"]

    # ls -l /mnt/remote
    total 0
    drwxrwxr-x 1 root root 0 Dec 30 14:15 dir1
    drwxrwxr-x 1 root root 0 Dec 30 14:15 dir2
    -rw-rw-r-- 1 root root 0 Jan  2 23:03 file1
    drwxrwxr-x 1 root root 0 Dec 30 14:15 dir3
    # 

Config

    [rclone-drive]
    type = drive
    scope = drive,drive.appfolder
    service_account_file = <service_account_file>
    root_folder_id = appDataFolder
    impersonate = <email>

    [rclone-crypt]
    type = crypt
    remote = rclone-drive:
    filename_encryption = standard
    password = <password>
    password2 = <password2>

**Comment by ncw** [comment]
I can replicate the underlying problem very easily

```
$ rclone lsf -R drive-appfolder:
$ rclone lsf --disable ListR -R drive-appfolder:
sub/
sub/README.md
```

This is because of the root alias "appDataFolder" is not being returned in the listing the actual ID is.

Anyway this is reasonably easy to fix - can you have a go with this please?

https://beta.rclone.org/branch/v1.50.2-104-gc018ebeb-fix-3851-appdata-listr-beta/ (uploaded in 15-30 mins)

**Comment by 1xe** [comment]
The new version resolves the issue. Thanks a lot.

I had hoped that fixing this issue would also fix an issue with the `df` output, but that is not the case. At the moment, it appears that the values returned by `df` (in particular, "used" disk space) are set at the time of `rclone mount` and never updated. Is this a bug or a missing feature?

**Comment by ncw** [comment]
> The new version resolves the issue. Thanks a lot.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.51



> I had hoped that fixing this issue would also fix an issue with the `df` output, but that is not the case. At the moment, it appears that the values returned by `df` (in particular, "used" disk space) are set at the time of `rclone mount` and never updated. Is this a bug or a missing feature?

Rclone caches the disk space usage for `--dir-cache-time`  so your value of `8760h` would explain it!

I think Google drive only updates the disk space it shows every few hours. It certainly isn't instant.

**Comment by 1xe** [comment]
> I've merged this to master now which means it will be in the latest beta in 15-30 mins and released in v1.51

Sweet! Looking forward to v1.51. Looks like you have your work cut out for you. ;-)

> Rclone caches the disk space usage for --dir-cache-time so your value of 8760h would explain it!

I have it set so high because I assumed that I could force updates by running `rclone rc vfs/refresh recursive=true` at appropriate times. If this is not supposed to be the case, then the manual is not clear enough. :-)

**Comment by ncw** [comment]
> > Rclone caches the disk space usage for --dir-cache-time so your value of 8760h would explain it!
> 
> I have it set so high because I assumed that I could force updates by running `rclone rc vfs/refresh recursive=true` at appropriate times. If this is not supposed to be the case, then the manual is not clear enough. :-)

I could make vfs/refresh clear the about cache timer - that would be easy.

Or I could use a different timer.  Perhaps fix it at 1 minute or make it configurable (yet another flag!!!)

What do you think?

I used the dir cache time out of laziness I think ;-)

**Comment by 1xe** [comment]
> I could make vfs/refresh clear the about cache timer - that would be easy.
> 
> Or I could use a different timer. Perhaps fix it at 1 minute or make it configurable (yet another flag!!!)
> 
> What do you think?
> 
> I used the dir cache time out of laziness I think ;-)

Sorry about the late reply. I somehow missed your message two months ago. Anyway...

I would like to be able to run `rclone mount` like this

`rclone mount ... --rc ... --attr-timeout=-1 --dir-cache-time=-1 --poll-interval=0 ...`

i.e., with "infinite" caching and no polling because I know exactly when the remote changes. It's always the result of a (scripted) invocation of `rclone move` and said script knows what parts of the directory tree change as a result of the move and thus what parameters to pass to `rclone rc vfs/refresh` to update the cache.

I think it makes sense that disk space usage is tied to the directory cache and that if `rclone rc vfs/refresh` updates the directory cache, then disk space usage is updated as well. I don't see why you would ever want the two to potentially diverge. (And there are indeed flags enough already!)

BTW, it would simplify scripting a bit if you could run `rclone rc vfs/refresh dir=/` instead of `rclone rc vfs/refresh` to refresh the root directory, but I digress... :-)

**Comment by ncw** [comment]
> I think it makes sense that disk space usage is tied to the directory cache and that if `rclone rc vfs/refresh` updates the directory cache, then disk space usage is updated as well. I don't see why you would ever want the two to potentially diverge. (And there are indeed flags enough already!)

Do you want to make a new issue about that? It shouldn't be too hard.

**Comment by 1xe** [comment]
> > I think it makes sense that disk space usage is tied to the directory cache and that if `rclone rc vfs/refresh` updates the directory cache, then disk space usage is updated as well. I don't see why you would ever want the two to potentially diverge. (And there are indeed flags enough already!)
> 
> Do you want to make a new issue about that? It shouldn't be too hard.

Done: https://github.com/rclone/rclone/issues/4040 :-)
