### ISSUE TITLE
Expose docker webgui ?

### ISSUE THREAD

**Issue by Nosirus** [rclone/rclone#3854]
I'm trying to access the webgui on unraid docker unsuccessfully. 

rcd --rc-web-gui --rc-web-gui-update --rc-baseurl rclone --rc-user test --rc-pass test --cache-dir "/config/rclone"

I get in log Serving remote control on http://127.0.0.1:5572/rclone/ but nothing in the browser.

**Comment by ncw** [comment]
You'll need to open the browser by hand if running in Docker.

You'll also need to make sure :5572 is port forwarded.

Ask on [the rclone forum](https://forum.rclone.org/) if you want more help.

Thanks
