### ISSUE TITLE
Win2008 mount google drive failed

### ISSUE THREAD

**Issue by yuritry** [rclone/rclone#3855]
C:\Temp>rclone mount -vv --debug-fuse mysite:/ g: --allow-non-empty --allow-othe
r
2020/01/05 05:34:43 DEBUG : rclone: Version "v1.50.2" starting with parameters [
"rclone" "mount" "-vv" "--debug-fuse" "mysite:/" "g:" "--allow-non-empty" "--all
ow-other"]
2020/01/05 05:34:43 DEBUG : Using config file from "C:\\Users\\Administrator\\.c
onfig\\rclone\\rclone.conf"
2020/01/05 05:34:43 DEBUG : Google drive root '': Mounting on "g:"
2020/01/05 05:34:44 DEBUG : Adding path "vfs/forget" to remote control registry
2020/01/05 05:34:44 DEBUG : Adding path "vfs/refresh" to remote control registry

2020/01/05 05:34:44 DEBUG : Adding path "vfs/poll-interval" to remote control re
gistry
2020/01/05 05:34:44 DEBUG : Google drive root '': Mounting with options: ["-o" "
fsname=mysite:" "-o" "subtype=rclone" "-o" "max_readahead=131072" "-o" "attr_tim
eout=1" "-o" "atomic_o_trunc" "-o" "debug" "-o" "uid=-1" "-o" "gid=-1" "--FileSy
stemName=rclone" "-o" "volname=mysite" "-o" "nonempty" "-o" "allow_other"]
Cannot create WinFsp-FUSE file system: unspecified error.
2020/01/05 05:34:44 ERROR : Google drive root '': Mount failed
2020/01/05 05:34:44 Fatal error: failed to mount FUSE fs: mount stopped before c
alling Init: mount failed

**Comment by ncw** [comment]
Is WinFSP installed properly?

**Comment by yuritry** [comment]
How to check if it was installed properly?

**Comment by ncw** [comment]
Perhaps uninstall it and re-install the latest version?

Try running the mount command with fewer options and see if that helps

    rclone mount -vv --debug-fuse mysite:/ g:

**Comment by yuritry** [comment]
Thank you.

I re-installed winfsp 1.5.2002 , run:
rclone mount -vv --debug-fuse mysite:/ g:
Same error as above.

I ranit  in win2008 on a kvm vps.

**Comment by ncw** [comment]
Can you see if any of the WinFSP tools work like sshfs-win?

I'm not sure what is going on here - the error message isn't very helpful!

**Comment by yuritry** [comment]
I re-installed winfsp, and I also installed sshfs-win, but it still doesn't work.

Is it because of  VPS, or windows 2008?_

**Comment by ncw** [comment]
> I re-installed winfsp, and I also installed sshfs-win, but it still doesn't work.

Are you saying `sshfs-win` doesn't work?

If so then I think it must be a WinFSP problem.

I'm pretty sure WinFSP is supported under Windows 2008

There are no results for searching for [unspecified error](https://github.com/billziss-gh/winfsp/issues?utf8=%E2%9C%93&q=is%3Aissue+%22unspecified+error%22) in the WinFSP github.

If the sshfs-win fails then I think you should probably open an issue here as you are no longer using rclone at that point: https://github.com/billziss-gh/winfsp/

**Comment by yuritry** [comment]
Thank you for your reply.
What I mean is that Rclone Mount doesn't work.
I'm not sure which part caused the problem, rclone, WinFSP, or sshfs-win.

Is there any way that I can find which part is the problem?

**Comment by ncw** [comment]
> Thank you for your reply.
> What I mean is that Rclone Mount doesn't work.

I understand that.

> I'm not sure which part caused the problem, rclone, WinFSP, or sshfs-win.

I was hoping you would try to see if sshfs-win works or not. If sshfs-win works then this is likely rclone's problem. If sshfs-win does not work then it is likely a WinFSP problem.

**Comment by animosity22** [comment]
@yuritry  - any update?

**Comment by yuritry** [comment]
no.
I re-installed win2008,winfsp,sshfs-win, but still the same error.

**Comment by animosity22** [comment]
Does sshfs-win work or no?

**Comment by animosity22** [comment]
If you feel you need anymore help, please post on https://forums.rclone.org as this seems to be a use question.

Thanks!
