### ISSUE TITLE
Feature request: export Metrics for Prometheus

### ISSUE THREAD

**Issue by ccremer** [rclone/rclone#3858]
#### What is your current rclone version (output from `rclone version`)?

Docker image tag 1.50

#### What problem are you are trying to solve?

Getting metrics of jobs into a Prometheus scrapable format or pushing into Pushgateway. In a Kubernetes world, where rclone runs as a (Cron)job for backing up application data (e.g. S3 mirroring), the monitoring of jobs and failures is cumbersome. Usually it's done with Prometheus as it's the default monitoring solution.

#### How do you think rclone should be changed to solve that?

The current method of providing CLI flag `--rc --rc-addr "0.0.0.0:5572"` will enable a webserver that responds with a JSON when accessing `/core/stats`. It would be nice if we can alter the query (e.g. ?format=prometheus) so that it would provide the metrics in OpenMetrics/Prometheus format. That probably should also become a GET request instead of POST. Or another solution altogether.

We maintain currently a dedicated project https://github.com/vshn/rclone-exporter that does the JSON-to-prometheus translation, but we figure it's best if it's directly integrated into rclone. For testing purposes one could use this side-project in the meantime.

**Comment by ncw** [comment]
Interesting idea :-)

>  It would be nice if we can alter the query (e.g. ?format=prometheus) so that it would provide the metrics in OpenMetrics/Prometheus format.

Do you have a link for those specs?

> That probably should also become a GET request instead of POST. Or another solution altogether.

Probably a read only GET request would be a good idea for stats.

Are you interested in working on this for rclone?

**Comment by tobru** [comment]
> Do you have a link for those specs?

You can find it here: https://prometheus.io/docs/instrumenting/exposition_formats/

**Comment by ccremer** [comment]
You do not need to write the metrics "by hand" in order to comply with the specs, there are libraries for that, e.g https://github.com/prometheus/client_golang
. With this, you basically set the values of some counter regularly, and when a client accesses the metrics endpoint (`/metrics` is the Prometheus convention), the handler will print everything nicely. Ofc, this can be customized and integrated in other webserver libraries.

> Probably a read only GET request would be a good idea for stats.

Thats what the Prometheus client does out of the box. However, it might be desired to put it also behind auth if enabled, as some users might argue that it exposes possibly sensitive data.

> Are you interested in working on this for rclone?

Sadly I'm not sure I find the time to do that in the near future.

**Comment by terorie** [comment]
my 2ct: Please consider using Go's expvars which "provides a standardized interface to public variables" https://golang.org/pkg/expvar/
I believe Prometheus supports those natively, too.

**Comment by ccremer** [comment]
Hm, I'm not sure about that. The fact that there's something like https://github.com/albertito/prometheus-expvar-exporter does not give an impression that prometheus supports that natively. Although there is a "transformer" inside the prometheus client that does similar: https://github.com/prometheus/client_golang/blob/master/prometheus/expvar_collector.go. Might as well integrate prometheus client directly.

I'd prefer something that is more user friendly (i.e. Prometheus can be used natively without an additional exporter in between) and also that is language-independent. Go's expvar format is really just used in Go and not standardized across languages.

Unless expvar is already being used by rclone, then the expvar_collector just needs to be activated I guess.

**Comment by terorie** [comment]
Good to know. I thought the expvar collector was part of the server. I was hoping we could have less packages across rclone depend on some prometheus helper library and use stdlib instead. From the Prometheus source, it seems like expvar and Prometheus stats are incompatible though. :/ 
> // ExpvarCollector collects metrics from the expvar interface. It provides a
// quick way to expose numeric values that are already exported via expvar as
// Prometheus metrics. Note that the data models of expvar and Prometheus are
// fundamentally different, and that the ExpvarCollector is inherently
// slow.

**Comment by ncw** [comment]
I had a go with the https://github.com/prometheus/client_golang - it looks like that exports quite a lot of useful stats by default such as memory, http performance etc so it would probably be worth building on top of that.

Reading the docs I think rclone would have to implement a custom metrics `Collector` which reads the stats from the stats block (with the appropriate locking).

Is this the right approach do you think?

Does anyone want to take it up and make a PR from it?

**Comment by gary-kim** [comment]
I'll see if I can find some time to take a look.

**Comment by ccremer** [comment]
Nice! Thank you for looking into this.
Can you post an example output?

**Comment by gary-kim** [comment]
Here you go: https://gist.github.com/gary-kim/7e5c706364b81dcd5160e624217302da

**Comment by ccremer** [comment]
Looking good so far.

I have used rclone primarily in batch mode so far (so, cronjob where we sync from source to target and exit).
In cases where multi-job usage is running, it might make sense to use labels to differentiate between the jobs. Lines could be looking like this:
```
rclone_bytes_transferred_total{source="source-bucket",target="target-bucket"} 1546
```
Not sure if that's a use case?
