### ISSUE TITLE
rclone not syncing modified files

### ISSUE THREAD

**Issue by DoctorSubtilis** [rclone/rclone#3859]
#### What is the problem you are having with rclone?

This evening I tried to sync my files from local to mega, and I had 3 modified (audio) files to sync (lyric added, so the size is very similar, but the time is changed): instead rclone didn't see any modification.

#### What is your rclone version (output from `rclone version`)
rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

linux KDE Neon

####  Which cloud storage system are you using? (eg Google Drive)

Mega

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync /mnt/condivisa/audio mega:musica -l -v

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I'm can't find it, sorry...

**Comment by DoctorSubtilis** [comment]
Maybe it is not  a rclone bug, because krusader as well (syncing from mega to local) didn't recognise that files as changed, even though their date was claerly different. I don't understand...

**Comment by ncw** [comment]
mega doesn't support setting modification times or checksums so rclone is solely relying on the size of the file to see if it has changed.

So if the file size didn't change rclone won't notice it has changed :-(

**Comment by DoctorSubtilis** [comment]
OK, thank you (even though adding lyric should change a bit the size of a file...)

**Comment by ncw** [comment]
No probs.  I'll close this now.
