### ISSUE TITLE
Unable to copy data btw source and destination of s3 bucket

### ISSUE THREAD

**Issue by rv91** [rclone/rclone#3863]
I'm unable to copy the directories between source and destination bucket using below rclone command
![image](https://user-images.githubusercontent.com/24702792/72011946-dad9aa00-3228-11ea-8ce0-b793bd5dcc86.png)

**Comment by ncw** [comment]
Can you fill in the issue template please?  There isn't enough info there to help you.

Thanks.

**Comment by animosity22** [comment]
If you still have a question, please post on the forums and someone will give you a hand.
