### ISSUE TITLE
Windows: Can't create top level directories with a uuid UNC path

### ISSUE THREAD

**Issue by iseahound** [rclone/rclone#3864]
Hey Nick,
Windows has a lot of specific quirks, and this is another one of them 🙁.
This one is really minor (and only affects top level directories).

Using a uuid instead of a drive letter introduces an error only when creating top level directories. 

    2020/01/09 02:20:41 ERROR : string.txt: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
    2020/01/09 02:20:41 ERROR : Local file system at //?/Volume{a224c74f-da87-c295-3b90-cde0f64a29cc}/folder: not deleting files as there were IO errors
    2020/01/09 02:20:41 ERROR : Local file system at //?/Volume{a224c74f-da87-c295-3b90-cde0f64a29cc}/folder: not deleting directories as there were IO errors
    2020/01/09 02:20:41 ERROR : Attempt 1/3 failed with 1 errors and: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
    2020/01/09 02:20:41 ERROR : string.txt: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
    2020/01/09 02:20:41 ERROR : Local file system at //?/Volume{a224c74f-da87-c295-3b90-cde0f64a29cc}/folder: not deleting files as there were IO errors
    2020/01/09 02:20:41 ERROR : Local file system at //?/Volume{a224c74f-da87-c295-3b90-cde0f64a29cc}/folder: not deleting directories as there were IO errors
    2020/01/09 02:20:41 ERROR : Attempt 2/3 failed with 1 errors and: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
    2020/01/09 02:20:41 ERROR : string.txt: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
    2020/01/09 02:20:41 ERROR : Local file system at //?/Volume{a224c74f-da87-c295-3b90-cde0f64a29cc}/folder: not deleting files as there were IO errors
    2020/01/09 02:20:41 ERROR : Local file system at //?/Volume{a224c74f-da87-c295-3b90-cde0f64a29cc}/folder: not deleting directories as there were IO errors
    2020/01/09 02:20:41 ERROR : Attempt 3/3 failed with 1 errors and: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
    2020/01/09 02:20:41 Failed to sync: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.

Here's a short script demonstrating the bug:

    mkdir folder
    echo A large fawn jumped quickly over white zinc boxes. > folder\string.txt
    call rclone sync folder "\\?\Volume{a224c74f-da87-c295-3b90-cde0f64a29cc}\folder"
    pause

To get the uuid value for the volume run `mountvol` and copy and paste your unique value into the script.

Note that using a regular UNC path like `\\?\C:\` works fine.

**Comment by ncw** [comment]
What do you think rclone should be doing differently here?  I'm not an expert on Windows file systems so I'm not sure what the best fix is?  Or is it just document the quirk and move on?

**Comment by iseahound** [comment]
Document and move on. Probably something to do with curly braces in a UNC path.

**Comment by ncw** [comment]
It is strange it only doesn't work at the root.

This is almost certainly a go runtime bug - I looked at the go issues and there are lots about mkdir not working properly on Windows at the root, however they were all closed so this is probably a new issue.

I'll leave this issue open for someone else to find if they are affected by it.

**Comment by animosity22** [comment]
@iseahound - did you want to try on the later version and beta and see if it still exists? If it was a go issue, it might have been solved.

**Comment by iseahound** [comment]
Still failing on v1.51.0-353-g5f71d186-beta.

**Comment by ncw** [comment]
I think what we need to do is write a small go program to demonstrate the problem and post it as an issue on the go bug tracker.

I don't have a Windows machine to hand right now - @iseahound is that something you could help with?

**Comment by ivandeex** [comment]
Let's reproduce and document it as _Windows Caveat_.

**Comment by ivandeex** [comment]
@albertony 
Could you add a note about `//?/Volume{a224c74f-da87-c295-3b90-cde0f64a29cc}/folder` uuid paths in your windows docs?
Thank you
cc @ncw

**Comment by ncw** [comment]
I made an upstream bug about this on Go: https://github.com/golang/go/issues/39785

**Comment by albertony** [comment]
> I made an upstream bug about this on Go: [golang/go#39785](https://github.com/golang/go/issues/39785)

That ticket was closed as completed Aug 9, 2023, with commit https://github.com/golang/go/commit/cd589c8a73415afbf94a8976f20cbed9d4061ba6, included with go1.22.0 and newer. Official release Windows build of Rclone v1.67.0 is built with go1.22.4.

A quick test seem to verify this now works. Have you @iseahound tested it lately?
