### ISSUE TITLE
rclone continues uploading large file after 100%

### ISSUE THREAD

**Issue by jsirianni** [rclone/rclone#3866]
#### What is the problem you are having with rclone?

Rclone should stop uploading when it reaches 100%, however, it continues.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.50.1
- os/arch: linux/amd64
- go version: go1.13.4
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian GNU/Linux 9 (stretch)

####  Which cloud storage system are you using? (eg Google Drive)

Backblaze B2

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`$1` and `$2` are arguments passed to my script. Local directory and the remote directory
```
rclone copy $1 $2 \
--transfers=8 \
--buffer-size=25M \
--bwlimit "08:00,0.625M 23:00,2.25M" \
--fast-list \
--verbose \
--syslog
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I cannot provide this right now, but I can add it to my command and see what happens. I do have this:

```
Jan  9 16:08:08 railsidepve rclone[5522]: #012Transferred:   #011  474.929G / 289.020 GBytes, 164%, 1.209 MBytes/s, ETA -#012Errors:                 0#012Checks:                 1 / 1, 100%#012Transferred:            0 / 1, 0%#012Elapsed time:  111h41m59.5s#012Transferring:#012 *
```

Note that the progress is above 164%. I run this script weekly, and it takes around 2-3 days to finish. historically it works everytime, however, the past two weeks have run into this problem. 

I dont have this problem, on the same server, for other jobs where rclone is backing up many directories and small files.

**Comment by ncw** [comment]
This is almost certainly low level retries on chunks of the file which need to get uploaded again.

If you check the debug log you should see the chunks being retried.

If you try [the latest beta](https://beta.rclone.org) you'll see that we've fixed it so the retries aren't reported in the stats.

**Comment by jsirianni** [comment]
would a retry be network connectivity issues? While this is a possibility, the network seems stable. VPN is fine, and my users report no issues.

The underlying file is not changing during the upload, it is an archive file generated before running rclone, nothing active.

I will try the beta and report back. Thank you.

**Comment by ncw** [comment]
> would a retry be network connectivity issues? While this is a possibility, the network seems stable. VPN is fine, and my users report no issues.

Possibly, though b2 can (it is part of the protocol) move uploads between hosts when they are getting full so that could cause it.

> The underlying file is not changing during the upload, it is an archive file generated before running rclone, nothing active.

Good.
 
> I will try the beta and report back. Thank you.

Thanks

**Comment by jsirianni** [comment]
Hi Nick,

Looks like my latest backup finished without issue. I will skip the beta for now, but keep an eye out for the official release. 

I use rclone heavily, and really appreciate your work. Hopefully I can contribute sometime in the future. 

Cheers

**Comment by ncw** [comment]
Thanks for testing :-) And for the praise - always appreciated!
