### ISSUE TITLE
Google Drive mount and changeNotify issue

### ISSUE THREAD

**Issue by vesogo279** [rclone/rclone#3867]
#### What is the problem you are having with rclone?

- Google Drive encrypted share mounted with `rclone mount --fast-list --allow-other --dir-cache-time 48h --buffer-size 32M --daemon --read-only`

- New files are uploaded using `rclone move` or `rclone copy`

- `poll-interval` is default to 1 minute interval

Randomly happens that the cache is not updated with new files and folders.
API calls to `/drive/v3/changes` endpoint are correct and receive the correct response payload (verified with --dump-bodies) but "changeNotify" is not invoked/executed

#### Below some logs that show when the operation is successful:

> 2020/01/09 23:34:13 DEBUG : Google drive root 'drive': Checking for changes on remote
> 2020/01/09 23:34:13 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> 2020/01/09 23:34:13 DEBUG : HTTP REQUEST (req 0xc0008b6000)
> 2020/01/09 23:34:13 DEBUG : GET /drive/v3/changes?alt=json&fields=nextPageToken%2CnewStartPageToken%2Cchanges%28fileId%2Cfile%28name%2Cparents%2CmimeType%29%29&includeItemsFromAllDrives=true&pageSize=1000&pageToken=13597&prettyPrint=false&supportsAllDrives=true HTTP/1.1
> Host: www.googleapis.com
> User-Agent: rclone/v1.50.2
> Authorization: XXXX
> X-Goog-Api-Client: gl-go/1.11.0 gdcl/20190802
> Accept-Encoding: gzip
> 
> 2020/01/09 23:34:13 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> 2020/01/09 23:34:13 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
> 2020/01/09 23:34:13 DEBUG : HTTP RESPONSE (req 0xc0008b6000)
> 2020/01/09 23:34:13 DEBUG : HTTP/1.1 200 OK
> Transfer-Encoding: chunked
> Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
> Cache-Control: private, max-age=0, must-revalidate, no-transform
> Content-Type: application/json; charset=UTF-8
> Date: Thu, 09 Jan 2020 22:34:13 GMT
> Expires: Thu, 09 Jan 2020 22:34:13 GMT
> Server: GSE
> Vary: Origin
> Vary: X-Origin
> X-Content-Type-Options: nosniff
> X-Frame-Options: SAMEORIGIN
> X-Xss-Protection: 1; mode=block
> 
> 5a1
> {"newStartPageToken":"13597","changes":[{"fileId":...}]}
> 0
> 
> 2020/01/09 23:34:13 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
> 2020/01/09 23:34:13 DEBUG : : changeNotify: relativePath="path/to/file1", type=3
> 2020/01/09 23:34:13 DEBUG : path/to: invalidating directory cache
> 2020/01/09 23:34:13 DEBUG : : >changeNotify:
> 2020/01/09 23:34:13 DEBUG : : changeNotify: relativePath="path/to/file2", type=3
> 2020/01/09 23:34:13 DEBUG : : >changeNotify:
> 2020/01/09 23:34:13 DEBUG : : changeNotify: relativePath="path/to/file3", type=3
> 2020/01/09 23:34:13 DEBUG : : >changeNotify:
> 2020/01/09 23:34:13 DEBUG : : changeNotify: relativePath="path/to/file4", type=3
> 2020/01/09 23:34:13 DEBUG : : >changeNotify:
> 2020/01/09 23:34:13 DEBUG : : changeNotify: relativePath="path/to/file5", type=3
> 2020/01/09 23:34:13 DEBUG : : >changeNotify:

#### Below some logs that show when the operation _is NOT successful_ (as you can see no changeNotify occurr after API call):

> 2020/01/10 00:15:19 DEBUG : Google drive root 'XXX': Checking for changes on remote
> 2020/01/10 00:15:19 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> 2020/01/10 00:15:19 DEBUG : HTTP REQUEST (req 0xc0000feb00)
> 2020/01/10 00:15:19 DEBUG : GET /drive/v3/changes?alt=json&fields=nextPageToken%2CnewStartPageToken%2Cchanges%28fileId%2Cfile%28name%2Cparents%2CmimeType%29%29&includeItemsFromAllDrives=true&pageSize=1000&pageToken=15598&prettyPrint=false&supportsAllDrives=true HTTP/1.1
> Host: www.googleapis.com
> User-Agent: rclone/v1.50.2
> Authorization: XXXX
> X-Goog-Api-Client: gl-go/1.11.0 gdcl/20190802
> Accept-Encoding: gzip
> 
> 2020/01/10 00:15:19 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> 2020/01/10 00:15:19 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
> 2020/01/10 00:15:19 DEBUG : HTTP RESPONSE (req 0xc0000feb00)
> 2020/01/10 00:15:19 DEBUG : HTTP/1.1 200 OK
> Transfer-Encoding: chunked
> Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
> Cache-Control: private, max-age=0, must-revalidate, no-transform
> Content-Type: application/json; charset=UTF-8
> Date: Thu, 09 Jan 2020 23:15:19 GMT
> Expires: Thu, 09 Jan 2020 23:15:19 GMT
> Server: GSE
> Vary: Origin
> Vary: X-Origin
> X-Content-Type-Options: nosniff
> X-Frame-Options: SAMEORIGIN
> X-Xss-Protection: 1; mode=block
> 
> 6a0
> {"newStartPageToken":"15598","changes":[{"fileId":"...}]}
> 0
> 
> 2020/01/10 00:15:19 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

#### What is your rclone version (output from `rclone version`)
rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian Stretch 64bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

thank you for your awesome work :)

**Comment by ncw** [comment]
> Below some logs that show when the operation is NOT successful (as you can see no changeNotify occurr after API call):

Is there a difference you can see between successful and non successful polls that you can see?

Can you post the contents of those two changenotifies? I need to see the contents of the response.  You can redact IDs/names if you want.

**Comment by animosity22** [comment]
@vesogo279 - is this something you can provide? should I consider it stale?

**Comment by ivandeex** [comment]
@vesogo279 does the problem reproduce on latest rclone 1.53.2 ?

**Comment by ivandeex** [comment]
Topic starter is inactive for one year. Closing
