### ISSUE TITLE
Support file.io

### ISSUE THREAD

**Issue by KOLANICH** [rclone/rclone#3873]
API docs: https://www.file.io/

**Comment by ncw** [comment]
I think this probably doens't need a whole new remote.  The fact that it is write only would make that tricky.

If rclone had a command which could upload any file via a form upload then you could use this service.  What do you think @KOLANICH ?

Maybe something like?

    rclone copyurl --form-upload "file" remote:path/to/file https://file.io

**Comment by KOLANICH** [comment]
IMHO, providing impl details in CLI defeats the purpose. They should be configured separately. And probably the configurations should be shared via GH. #3876

**Comment by buengese** [comment]
Given that this is write only and has no support for anything resembling directories or listing I just don't see how that fits the scope of rclone. Everything you'd do with rclone can be accomplished with curl. So I'm in favor of closing this as out of scope.

**Comment by KOLANICH** [comment]
In fact I just wanted a software that will:
* encrypt my file
* MAC it
* splits it with some redundancy
* upload it on as many "free" file hostings as it can

Single hostings usually limit speed, size and duration on free accounts, so splitting the file between different ones can provide all of these, given enough different hostings.

Then if my hdd fails or if I just needed to get the files on a separate PC I just call the app providing it with the needed info, and the app downloads the stuff from the hostings in multistream mode and reassembles it and verifies its integrity and decrypts it.
