### ISSUE TITLE
Support uploadfiles.io

### ISSUE THREAD

**Issue by KOLANICH** [rclone/rclone#3875]
I don't know about officially-promoted API to be used by third parties, but here is a third-party client:
https://github.com/osteth/ufile-python

**Comment by ncw** [comment]
The actual upload and downlaod code looks very simple

https://github.com/osteth/ufile-python/blob/master/ufile/scripts/ufile.py

The fact that this doesn't have a list files means that it can't be a backend.

However it could be supported in a similar way to #3873
