### ISSUE TITLE
Support uploaders implemented as sxcu files for ShareX

### ISSUE THREAD

**Issue by KOLANICH** [rclone/rclone#3876]
https://github.com/ShareX/CustomUploaders

**Comment by ncw** [comment]
I'm not sure how this would be used with rclone - can you give an example of how rclone should work?

**Comment by KOLANICH** [comment]
1. Upload the file
2. Look for links looking like the ones being to the raw file in the returned page.
3. Verify that with a `Range` request.
4. Save the link into the DB.
5. Also expiration date can probably be heuristically extracted
6. Also we can probably extend the format with some data usable for us suchnas regexps and css selectors and send the PR to the original repo, if we don't want to rely on heuristics.
