### ISSUE TITLE
32K reads resulting in lots of IOPS

### ISSUE THREAD

**Issue by jkoopmann** [rclone/rclone#3877]
Hi,

I started using the cache feature incl. write cache to a GDRIVE backend. When I copy something to the drive it is copied first to the cache and then later on moved to the backend. I am also using crypt.

What I am seeing currently is that after things are copied and the "rclone move" starts, rclone is doing tons of 32K read requests on the cache drive. This result in a lot of IOPs which is slowing down the system a lot more than I expected. 

Is there any way convincing rclone to use larger read chunks?

Regards

**Comment by animosity22** [comment]
This seems to be a question rather than an issue. If you can please use the forums, we can help out. Use the question template.

**Comment by uwydoc** [comment]
based on the implementation, for most backend, rclone use `io.Copy` to copy data from src to dest, internally the default max block size is 32KB, and is NOT configurable. to make it configurable, rclone should use `io.CopyBuffer` instead and specify a buffer of custom size.
