### ISSUE TITLE
Confusing "about" space units

### ISSUE THREAD

**Issue by elig0n** [rclone/rclone#3881]
Space is shown in G/T/M units notation appearing to be measured in GB/TB/MB/etc but is actually GiB/TiB/MiB/etc See https://en.wikipedia.org/wiki/Binary_prefix#Consumer_confusion
Please use the appropriate notation to prevent confusion

**Comment by animosity22** [comment]
Can you give an example of what you are referring to?

**Comment by elig0n** [comment]
@animosity22 I specifically means this command and its output:

    felix@gemini:~$ rclone about GD:
    Used:    106.295T
    Trashed: 0
    Other:   159.438M

One who would see the 'T' and 'M' designations would naturally think they mean "Terabyte' and 'Megabyte' respectively, but in reality they are 'Tebibyte' and 'Mebibyte'.

**Comment by ncw** [comment]
The units are indeed in "binary SI" multiples of 1024

This is pretty common for disk/memory sizes.

Rclone is 100% consistent in always using the "binary SI" units whether you are inputting `--buffer-size`, or looking at disk stats or setting bandwidth limits.

```
$ rclone about .
Total:   466.771G
Used:    405.587G
Free:    37.407G
```

vs

```
$ df -h .
Filesystem                    Size  Used Avail Use% Mounted on
/dev/mapper/xubuntu--vg-root  467G  406G   38G  92% /
```

It would be fairly easy to make rclone put an `i` after every unit so you'd get

```
$ rclone about .
Total:   466.771Gi
Used:    405.587Gi
Free:    37.407Gi
```

However I suspect that would result in people creating even more issues!

Rclone could change to using 1000 multiples but that would confuse people when then use memory units `--buffer-size`, `--chunk-size` etc.

I could implement an `--si` flag to control that, however rclone stores the units in config files etc so changing the meaning of the units would be a bad idea...

If you want to avoid confusion you can always use the `--json` flag to about!

```
$ rclone about --json .
{
	"total": 501192073216,
	"used": 435492089856,
	"free": 40169467904
}
```

I don't think there is a good solution to this other than maybe adding an `--si` flag to `rclone about` only.

**Comment by animosity22** [comment]
Just re-reading this as I think the final agreement was not to make a change to rclone based on @ncw comments so I was going to close this out.
