### ISSUE TITLE
Support furk.net storage provider

### ISSUE THREAD

**Issue by sasagr** [rclone/rclone#3883]
What is your current rclone version (output from rclone version)?

Rclone v1.50.2

What problem are you are trying to solve?

there is no support for the provider furk.net (wwww.furk.net)

How do you think rclone should be changed to solve that?

rclone should access (rw or only r) the MyFiles on furk.net and mount the cloud drive.

The API is described at https://www.furk.net/t/api

**Comment by buengese** [comment]
Do you have any idea for how long theyve been in business? I'd be willing to create a backend for this but only if we can be relative sure that they don't go out of business in 3 months. Also you appear to need in invite code to register.

**Comment by sasagr** [comment]
I have an account with them since 2012, no signs till now of closing. I can give you an invitation code. Pls tell if I should put it here (public) or pass it to you somewhere else

**Comment by buengese** [comment]
You can mail it to me. (buengese@gmail.com)

**Comment by sasagr** [comment]
done! 👍

**Comment by sasagr** [comment]
@buengese hi. any progress on this? or maybe it is not possible?

**Comment by sasagr** [comment]
Hi, any progress on this or at least plan to add it?
thanks

**Comment by sasagr** [comment]
Hello. Is any developer interested in this project? Feel free to contact me if you need an invite code.

**Comment by cod3mon** [comment]
Well, it seems furk.net is defunct now. This can probably be closed.
