### ISSUE TITLE
rclone purge does not care about --drive-trashed-only

### ISSUE THREAD

**Issue by hacktek** [rclone/rclone#3893]
#### What is the problem you are having with rclone?

When using rclone purge, it will operate and delete all content even when configuration tag --drive-trashed-only is used.

#### What is your rclone version (output from `rclone version`)

rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.6

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone purge drive:path --drive-trashed-only --drive-use-trash=false --verbose=1

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

No output.

**Comment by Dibbyo456** [comment]
Known issue: https://forum.rclone.org/t/drive-trashed-only-weird-occurrence/11066/14

**Comment by ncw** [comment]
The suggestion from that thread was

> So using --drive-trashed-only with Purge is likely not to work as the user expects! What I can do is make Purge exit with an error if it is called with --drive-trashed-only. Can you please make a new issue on github 3 about this and I'll make the fix - thanks!

Either of you fancy having a go at that?

**Comment by ncw** [comment]
Actually a check of the log says we did this already in https://github.com/rclone/rclone/issues/3893

So the fix is in [the latest beta](https://beta.rclone.org) and will be released in v1.51

**Comment by Dibbyo456** [comment]
> Actually a check of the log says we did this already in #3893

You meant #3407
