### ISSUE TITLE
Feature request: ability to save credentials to seperate file

### ISSUE THREAD

**Issue by ericist** [rclone/rclone#3902]
#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.49.1
- os/arch: linux/amd64
- go version: go1.12.9
```

#### What problem are you are trying to solve?
I would like to share my rclone config file between different machines, either through source control or an automated way. However, I want to avoid sharing all secrets (logins, encryption passwords) with all machines. Seperating the secrets (auth tokens, passwords, etc.) from the main config file would allow me to share the config file between different machines without having to worry about placing secrets on insecure machines.

#### How do you think rclone should be changed to solve that?
Add a global config setting, e.g. ``secrets_store = secrets.conf``, which points to the file where settings of the type auth token, encryption password, etc. are stored. Regarding implementation, rclone could simply merge the two text files in memory before parsing them. When saving/changing a setting of the mentioned types, rclone would check if the ``secrets_store`` setting is set, and if it is write the setting to that file. A more general approach would be to allow include directives in the config file for settings in general, i.e. ``!include secrets.conf``, however the implementation would be more complex.

**Edit:** Thinking about it, include directives might be a better solution as they are more versatile, for example one could additionally include platform-specific settings when required.

**Comment by ncw** [comment]
I'm not sure this is the right approach for your problem.  It sounds like you want a master config file with all the remotes in then a little script which carves up the remotes that a given machine needs and delivers them to the destination machine? Is that about right?

**Comment by Yexiaoxing** [comment]
I am wondering... how you can deliver the "secrets" to each machine? If you can do so, why not just secretly transfer the config file? Both processes are one-time only.

**Comment by ericist** [comment]
My idea was to store on each machine the credentials it requires once, and to continually update the main config file on all machines whenever I change it on my main machine.
But I guess you're right, I'll just split my config and write a small script which concatenates the parts as needed for each machine.
I just thought this feature might be useful for other people, e.g. if they want to upload their config to Github, while keeping the credentials local. The implementation effor might not be worth it however.
