### ISSUE TITLE
Onedrive max file size

### ISSUE THREAD

**Issue by hjyoung1** [rclone/rclone#3905]
#### What is the problem you are having with rclone?

I'm trying to copy file (size 20gb) from Google drive to onedrive business account. 
But rclone everytime hits " The entity size in the request exceeds the maximum limit. "
After searching i found it's onedrive limitations but recently Microsoft updated max file size limit it's 100gb now 
https://onedrive.uservoice.com/forums/913528-onedrive-on-the-web/suggestions/31737640-increase-the-file-upload-limit
So I'm not sure why I'm still facing this issue. Is it problem with rclone? Or issue with onedrive? 
Thanks. 
#### What is your rclone version (output from `rclone version`)

rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 18.04, 64bit

####  Which cloud storage system are you using? (eg Google Drive)

Google drive and onedrive 

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone copy -P  hgdrive:file/location  honedrive:hgdrive

**Comment by Cnly** [comment]
They said the new 100GB limit would be everywhere "by the end of 2019" back in December, but now they've changed it to "early 2020:" https://support.office.com/en-us/article/invalid-file-names-and-file-types-in-onedrive-onedrive-for-business-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa?ui=en-US&rs=en-001&ad=US#individualfilesize

**Comment by hjyoung1** [comment]
Ah my bad i didn't saw that. Closing this as this is onedrive issue.
Thanks.
