### ISSUE TITLE
Elapsed time count includes blinking decimals

### ISSUE THREAD

**Issue by Zirro** [rclone/rclone#3906]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.50.2-DEV
- os/arch: darwin/amd64
- go version: go1.13.6

#### What problem are you are trying to solve?
This is just a minor enhancement request for the interface, but I've noticed that the decimals for the "Elapsed time" count tend to blink in and out of existence depending on the rounding. The changing width of the line seems to make it quite distracting while rclone is visible on my screen, as compared to numbers which merely increment in place.

![rclone_elapsed_time_blink](https://user-images.githubusercontent.com/3169418/73141126-b5e69300-4080-11ea-9b32-df4485e22be4.gif)

#### How do you think rclone should be changed to solve that?
It would be an appreciated enhancement for the count to either also show `.0s` to preserve the line width, or perhaps to not display decimals at all.

Thanks!

**Comment by ncw** [comment]
I've merged @gary-kim 's fix for this this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.51
