### ISSUE TITLE
Slow lsf with min-age flag on s3 backend

### ISSUE THREAD

**Issue by smiklos** [rclone/rclone#3908]
#### What is the problem you are having with rclone?

Trying to use lsf on s3 and it's very slow when using min-age flag. 
It probably is a similar problem to the recently merged mimetype issue where lsf would request this as an extra call to s3 for each object. The s3 listing returns the modification time so I don't see why it's taking so long to filter based on min-age. 

A folder takes around 30 seconds to list and takes around 20 minutes to do with --min-age

#### What is your rclone version (output from `rclone version`)

v1.50.2-194 (some fresh beta)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows Server 2008 R2 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

AWS S3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

lsf --files-only --fast-list --min-age 15m

**Comment by ncw** [comment]
> The s3 listing returns the modification time so I don't see why it's taking so long to filter based on min-age

The s3 listing returns the time the file was uploaded, not the modification time which rclone stores in metadata.

You can make rclone use the server time with `--use-server-modtime` - see https://rclone.org/docs/#use-server-modtime

Because rclone can't set this time, if you are syncing with `--use-server-modtime` you'll need to use the `--update` flag too.

**Comment by smiklos** [comment]
I'm not syncing but rather doing an lsf on s3 and then on a local folder to compare them and copy the diff twice down. I will give a try to this flag altough I don't really understand the meaning of server time time here. There is some modtime coming from s3 listing, so if this flag makes rclone use that than it's good.

**Comment by ncw** [comment]
> There is some modtime coming from s3 listing, so if this flag makes rclone use that than it's good.

That is exactly what the flag does, and it will work with `lsf` too.

**Comment by smiklos** [comment]
Thanks, it did indeed do the trick. Closing the issue
