### ISSUE TITLE
Use rolling average to improve ETA accuracy

### ISSUE THREAD

**Issue by sjpotter** [rclone/rclone#3909]
#### What is the problem you are having with rclone?

```
2020-01-27 17:55:29 NOTICE: Bandwidth limit set to 60M
Transferred:        1.503T / 1.544 TBytes, 97%, 33.027 MBytes/s, ETA 21m46s
Errors:                 0
Checks:                57 / 57, 100%
Transferred:           57 / 59, 97%
Elapsed time:  13h15m17.2s
Transferring:
 *            myfile 52% /87.671G, 3.922M/s, 3h2m17s
```

note how the "myfile" eta is correct, but the top ETA isn't.  This is becaues I was transferring all files at once to maximize my bandwidth, but when the last largest file is left, it calculates ETA by the same transferred speed on top.  Which is the average speed, which is useful to know, but isn't useful for calculating ETA.  At worst, ETA should be based on the current speed, which is easy to eyeball with one file left, but is hard to eyeball when one has many files going.  It be nice to have a "Realtime row" under Transfered with real time speed and a closer to real ETA moved to there from transferred.  should be a matter of just totalling the individual files speeds and calculating ETA with that

#### What is your rclone version (output from `rclone version`)

rclone v1.47.0
- os/arch: linux/amd64
- go version: go1.12.

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

ubuntu 19.10

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone move

**Comment by animosity22** [comment]
Can you update your version and validate you are seeing the same thing? There have been a number of changes to that.

**Comment by sjpotter** [comment]
same behavior with the beta (haven't tested with today's release)

**Comment by animosity22** [comment]
@ncw - is this something you want to take a look at? I believe it's because of how we read the backlog in and not sure what would change here if anything.

**Comment by ncw** [comment]
This is something it would be nice to fix I think.

We need to calculate a rolling average aggregate speed the same as we do for each individual transfer, and use that for the ETA calculations, rather than the long term average.

**Comment by sjpotter** [comment]
that's what my PR does, just sums the rolling average of the individual transfers.  probably not 100% accurate, but closer than the existing.

**Comment by ncw** [comment]
> that's what my PR does, just sums the rolling average of the individual transfers. probably not 100% accurate, but closer than the existing.

It would be better to average the total otherwise the speed will be extremely bumpy when new transfers start I think.

**Comment by agneevX** [comment]
Any update here? When using `--stats-one-line`, the inaccuracy is most noticeable.
