### ISSUE TITLE
rclone sync (& others) interference with size_as_quota configuration value

### ISSUE THREAD

**Issue by Alvaro-Santos** [rclone/rclone#3912]
#### What is the problem you are having with rclone?

rclone sync fails to upload anything to google drive using my current config (more accurately, it manages to replicate my local directory structure, but remotely deletes every file after copying it to the remote due to google drive reporting the correct size -- 45 bytes -- but rclone believing that the actual size is 0 bytes). The issue is dependent on the value of size_as_quota, although I have not tinkered with other configuration parameters to figure out whether the issue is just size_as_quota xor an interference between size_as_quota and some other parameter.

This behaviour is also present in other commands (at least copy; possibly others). However, I have only properly tested/debugged sync specifically. This behaviour seems to be independent of the number of files present either locally or remotely (i.e., various combinations of 1/multiple local files, empty/partially filled remote directories).

#### What is your rclone version (output from `rclone version`)

The issue is present on both the stable and beta versions:

> rclone v1.50.2-194-gbfd9f321-beta
> \- os/arch: linux/amd64
> \- go version: go1.13.6

> rclone v1.50.2
> \- os/arch: linux/amd64
> \- go version: go1.13.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 18.04.3 LTS, 64 bit.

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

> rclone sync . gdrive:

The issue is present even when various miscellaneous (& probably uninteresting for the issue at hand) flags are enabled. Specifically:

> --exclude .git/
> --retries X, for X = 1, 2
> -vv
> --dump-bodies and --dump-headers in any combination with -vv

For obvious reasons, the issue disappears with either of the following flags enabled:

> --dry-run
> --ignore-size

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2020/01/28 21:36:38 DEBUG : rclone: Version "v1.50.2" starting with parameters ["rclone" "sync" "." "gdrive:" "--exclude" ".git/" "-vv"]
2020/01/28 21:36:38 DEBUG : Using config file from "/home/penguin/.config/rclone/rclone.conf"
2020/01/28 21:36:38 DEBUG : .git: Excluded
2020/01/28 21:36:38 INFO  : Google drive root '': Waiting for checks to finish
2020/01/28 21:36:38 INFO  : Google drive root '': Waiting for transfers to finish
2020/01/28 21:36:42 ERROR : 1st/config: corrupted on transfer: sizes differ 45 vs 0
2020/01/28 21:36:42 INFO  : 1st/config: Removing failed copy
2020/01/28 21:36:43 ERROR : Google drive root '': not deleting files as there were IO errors
2020/01/28 21:36:43 ERROR : Google drive root '': not deleting directories as there were IO errors
2020/01/28 21:36:43 ERROR : Attempt 1/3 failed with 3 errors and: corrupted on transfer: sizes differ 45 vs 0
2020/01/28 21:36:43 DEBUG : .git: Excluded
2020/01/28 21:36:43 INFO  : Google drive root '': Waiting for checks to finish
2020/01/28 21:36:43 INFO  : Google drive root '': Waiting for transfers to finish
2020/01/28 21:36:46 ERROR : 1st/config: corrupted on transfer: sizes differ 45 vs 0
2020/01/28 21:36:46 INFO  : 1st/config: Removing failed copy
2020/01/28 21:36:46 ERROR : Google drive root '': not deleting files as there were IO errors
2020/01/28 21:36:46 ERROR : Google drive root '': not deleting directories as there were IO errors
2020/01/28 21:36:46 ERROR : Attempt 2/3 failed with 3 errors and: corrupted on transfer: sizes differ 45 vs 0
2020/01/28 21:36:46 DEBUG : .git: Excluded
2020/01/28 21:36:47 INFO  : Google drive root '': Waiting for checks to finish
2020/01/28 21:36:47 INFO  : Google drive root '': Waiting for transfers to finish
2020/01/28 21:36:49 ERROR : 1st/config: corrupted on transfer: sizes differ 45 vs 0
2020/01/28 21:36:49 INFO  : 1st/config: Removing failed copy
2020/01/28 21:36:50 ERROR : Google drive root '': not deleting files as there were IO errors
2020/01/28 21:36:50 ERROR : Google drive root '': not deleting directories as there were IO errors
2020/01/28 21:36:50 ERROR : Attempt 3/3 failed with 3 errors and: corrupted on transfer: sizes differ 45 vs 0
2020/01/28 21:36:50 Failed to sync with 3 errors: last error was: corrupted on transfer: sizes differ 45 vs 0

#### Attachments

I have attached the following files:
- A copy of the file I am trying to upload to gdrive [config.txt](https://github.com/rclone/rclone/files/4124732/config.txt). This file was kept in "./1st/" locally;
- A dump of my rclone config [rclone_config.txt](https://github.com/rclone/rclone/files/4124761/rclone_config.txt) (generated using rclone config dump; root_folder_id obtained as per https://rclone.org/drive/#root-folder-id);

#### Temporary fixes

Currently, either using --ignore-size or setting size_as_quota to false in the previously attached configuration file seem to resolve the issue, without any negative effect on the usage of rclone.

#### Keywords to help other users affected by this bug to find this issue on search engines

rclone size bug, rclone gdrive size bug, rclone size always 0, rclone sync size is wrong, rclone corrupted on transfer: sizes differ, rclone sync only works with --ignore-size

**Comment by ncw** [comment]
`size_as_quota` is only intended for listing your files so you can see the quota, not for syncing, so you don't want to set this in the config.

Do you think the docs should highlight this better?

What made you set `size_as_quota`?

**Comment by Alvaro-Santos** [comment]
I think the expected behaviour, for someone using rclone for the first time, would be for `size_as_quota` to only affect commands "read" commands (like `ls`) and not influence "write" commands at all (like `sync`). As the config is global, and not per action, I think this is a reasonable expectation. Whether you agree with this expectation or not, I think you'll agree that it's not at all expected for rclone to report local sizes at 0 if size_as_quota is set (in the sense that it's surprising for an user).

I set this config value to true because I wanted to be aware of the "true" size my files are occupying on google drive, although I'll admit I did find the documentation in general poor. As a concrete example: "[Show storage quota usage for file size.](https://rclone.org/drive/#drive-size-as-quota)" --- show it where? In what commands?

Ideally, I'd like to see `size_as_quota` simply be ignored by `sync`/`copy`/etc and only used to report sizes in commands like `ls`. However, since I'm not offering a patch to the project, I cannot impose on you. Another (less satisfying) solution would be to change the documentation (on the project site, on `rclone sync --help`, and on the interactive prompt when modifying an advanced configuration) to warn of the effects of setting `size_as_quota` and trying to use "write" commands and of the temporary fix for people who want to have it enabled while being able to write to their remotes (using `--ignore-size`).

**Comment by ncw** [comment]
> I think the expected behaviour, for someone using rclone for the first time, would be for `size_as_quota` to only affect commands "read" commands (like `ls`) and not influence "write" commands at all (like `sync`).

It does only affect the size reading, but that messes up the sync as you've seen.

> As the config is global, and not per action, I think this is a reasonable expectation.

I think the expectation is that people would only use this as a flag, eg

    rclone lsl --drive-size-as-quota drive:path

> Ideally, I'd like to see `size_as_quota` simply be ignored by `sync`/`copy`/etc and only used to report sizes in commands like `ls`.

Unfortunately that isn't possible easily. The `sync`/`copy` etc are just calling the backend interface and there is only one size interface.

> Another (less satisfying) solution would be to change the documentation (on the project site, on `rclone sync --help`, and on the interactive prompt when modifying an advanced configuration) to warn of the effects of setting `size_as_quota` and trying to use "write" commands and of the temporary fix for people who want to have it enabled while being able to write to their remotes (using `--ignore-size`).

I think this is my preferred option.

How about this for a proposed text:

----

Show storage quota usage for file size.

The storage used by a file is the size of the current version plus any older versions that have been set to keep forever.

**NB** it is not recommended to set this flag in your config - the recommended usage is using the flag form `--drive-size-as-quota` when doing `rclone ls/lsl/lsf/lsjson/etc` only.

----

I think I can take the flag out of the configurator completely so it only shows as a command line option.

**Comment by Alvaro-Santos** [comment]
>Unfortunately that isn't possible easily. The sync/copy etc are just calling the backend interface and there is only one size interface.

Perhaps I'm missing some subtlety of the implementation, but I don't understand how this could be much harder than checking if the command given is one of {sync, copy, copyto, etc} and overriding (temporarily) the flag's value with false. The backend wouldn't ever even know that the frontend had been called with the flag enabled.

>I think I can take the flag out of the configurator completely so it only shows as a command line option.

This seems ideal given your intended usage of the flag as a command line option. Your text seems to imply the possibility of still setting the flag in the config, though. If you do choose to maintain it as a config option, I'd amend your nota bene to also refer to this issue (which explains the "issue" & your rationale in depth) and add the "fix" of using --ignore-size. If you choose to drop it, then the text seems fine as is. [Would any other contributors, perhaps more technical-writing inclined, like to weigh in?]

**Comment by ncw** [comment]
I've gone with the hiding from the configurator option and more help text

97ed8db75d06ed9458862ebbb19da7b6fc9eb2f7

Thanks for reporting this.
