### ISSUE TITLE
Unable to fetch file list from index

### ISSUE THREAD

**Issue by hjyoung1** [rclone/rclone#3913]
#### What is the problem you are having with rclone?

I'm trying to add http index using http connection. But for some reason rclone is not getting any results from index.
Index I'm adding is running GDIndex (https://github.com/maple3142/GDIndex/) (example https://gdindex-demo.maple3142.workers.dev) 

#### What is your rclone version (output from `rclone version`)

rclone v1.50.2
- os/arch: android/arm64
- go version: go1.13.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Using termux to run rclone. Device arm64. 

####  Which cloud storage system are you using? (eg Google Drive)

http Connection

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone -vv ls dindex:

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

![Screenshot_20200129-161606](https://user-images.githubusercontent.com/45882061/73350980-17db0e80-42b4-11ea-82df-b81fd7dce8ce.jpg)

**Comment by ncw** [comment]
Alas that index is 100% javascript - rclone needs a static index to read.

```html
<!DOCTYPE html>
<html lang=en>
  <head>
    <meta charset=utf-8>
    <meta http-equiv=X-UA-Compatible content="IE=edge">
    <meta name=viewport content="width=device-width,initial-scale=1">
    <title>GDIndex</title>
    <link href="/~_~_gdindex/resources/css/app.css" rel=stylesheet>
  </head>
  <body>
    <script>window.props = { title: 'GDIndex', default_root_id: 'root', api: location.protocol + '//' + location.host, upload: false }</script>
    <div id=app>
    </div>
    <script src="/~_~_gdindex/resources/js/app.js">
    </script>
  </body>
</html>
```

**Comment by hjyoung1** [comment]
Oh  :(
