### ISSUE TITLE
rclone on 394k subdirectories, 2.7m files (500GB data)

### ISSUE THREAD

**Issue by alanmcg** [rclone/rclone#3914]
Version:
rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.4

Command:
rclone --stats-one-line -P --stats 2s sync . filehostingbackup:nfs-filehosting-backup

There are 394k subdirectories, 2.7m files and files average about 40kb (from 1kb to 1mb).

Problem:
Rclone still shows "0 / 0 Bytes, -, 0 Bytes/s, ETA -" since starting the command after approximately two hours, according to htop  there are 6 threads sitting idle.

The source system is a fairly slow NFS server on centos6, is it feasible to use rclone on this kind of system / number of files? I tested on a single dir with ~20 of the same files and transfer was almost instant

**Comment by alanmcg** [comment]
Problem solved, the server was behind a reverse proxy and setting HTTPS_PROXY environment variable allowed it to start immediately. 

Perhaps some faster error output when the connection times out would be a good improvement, took a couple of hours before i got a timeout error.

**Comment by animosity22** [comment]
That looks to be a networking item on your environment and not really rclone related. If you have a new question or how to use, please ask on the forums and we are happy to help out!
