### ISSUE TITLE
How to exclude ALL subdirectories from rclone copy

### ISSUE THREAD

**Issue by jshrek** [rclone/rclone#3917]
When I use rclone copy, I know I can use --exclude "/some-dir-name/**" to exlcude that specific dir.

But how do I exclude all sub dirs, and only copy the root?

Also, how can I include only specific file types from the root , like *.mp4 only?

Thanks

**Comment by ncw** [comment]
You can do it with filters like this

    --filter "+ /*" --filter "- *" 

Perhaps easier is

    --max-depth 1

> Also, how can I include only specific file types from the root , like *.mp4 only?

    --filter "- /*.mp4"

I'd prefer it if you'd ask questions in [the rclone forum](https://forum.rclone.org/) if you don't mind, so I'm going to close this now.
