### ISSUE TITLE
"--local-encoding None" flag doesn't work with full width forward slash "／" in filename

### ISSUE THREAD

**Issue by boxothing** [rclone/rclone#3921]
#### What is the problem you are having with rclone?
`--local-encoding None` doesn't work for uploading file name containing "／" character.

I tested with following set of characters and every other characters work except for "／".
`＼＊＜／？＞：＂｜`

#### What is your rclone version (output from `rclone version`)
rclone v1.51.0-007-g3dfa63b8-beta

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy "file／.jpg" remote: -vv --local-encoding None

Also renaming using moveto command does not work either for `／` character
rclone moveto remote:file.jpg remote:file／.jpg
This would rename file to "file/.jpg" instead of "file／.jpg"

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2020/02/01 15:20:41 DEBUG : rclone: Version "v1.51.0-007-g3dfa63b8-beta" starting with parameters ["rclone" "copy" "file／.jpg" "remote:" "-vv" "--local-encoding" "None"]
2020/02/01 15:20:41 DEBUG : Using config file from "C:\\Users\\usern\\.config\\rclone\\rclone.conf"
2020/02/01 15:20:42 ERROR : : error reading source directory: directory not found
2020/02/01 15:20:42 INFO  : Google drive root '': Waiting for checks to finish
2020/02/01 15:20:42 INFO  : Google drive root '': Waiting for transfers to finish
2020/02/01 15:20:42 ERROR : Attempt 1/3 failed with 1 errors and: directory not found
2020/02/01 15:20:42 ERROR : : error reading source directory: directory not found
2020/02/01 15:20:42 INFO  : Google drive root '': Waiting for checks to finish
2020/02/01 15:20:42 INFO  : Google drive root '': Waiting for transfers to finish
2020/02/01 15:20:42 ERROR : Attempt 2/3 failed with 1 errors and: directory not found
2020/02/01 15:20:42 ERROR : : error reading source directory: directory not found
2020/02/01 15:20:42 INFO  : Google drive root '': Waiting for checks to finish
2020/02/01 15:20:42 INFO  : Google drive root '': Waiting for transfers to finish
2020/02/01 15:20:42 ERROR : Attempt 3/3 failed with 1 errors and: directory not found
2020/02/01 15:20:42 Failed to copy: directory not found
```

**Comment by ncw** [comment]
I think you might need to adjust the google drive encoding, try this

    --drive-encoding Slash,InvalidUtf8

As unlike any other remotes, Google Drive can have / in file names.

**Comment by boxothing** [comment]
Unfortunately `--drive-encoding Slash,InvalidUtf8` only seem to work if filename just contains ／.
I need to be able to use with `--local-encoding None` since I have files with `＼＊＜／？＞：＂｜` these characters.

I understand the reason behind it but encoding these characters seem somewhat arbitrary because these are actual characters that are used in filenames. Users should really be responsible and use proper filenames that are compatible with their os/cloud instead relying on Rclone. Or at least give us option to keep the original filename as is (which I thought `--local-encoding None` was for).

The only work around I found so far was replacing `＼` to `‛／` in command.

**Comment by ncw** [comment]
> Unfortunately `--drive-encoding Slash,InvalidUtf8` only seem to work if filename just contains ／.
> I need to be able to use with `--local-encoding None` since I have files with `＼＊＜／？＞：＂｜` these characters.

You need to use both `--local-encoding` and `--drive-encoding`.

> The only work around I found so far was replacing ／ to ‛／ in command.

That will work too.

**Comment by boxothing** [comment]
> You need to use both `--local-encoding` and `--drive-encoding`.

Unless I missed something, using `--local-encoding None` and `--drive-encoding Slash,InvalidUtf8` together did not work for me.

`rclone copy "file＼＊＜／？＞：＂｜.txt" remote: -vv --local-encoding None --drive-encoding Slash,InvalidUtf8`

```
2020/02/03 09:06:15 DEBUG : rclone: Version "v1.51.0-007-g3dfa63b8-beta" starting with parameters ["rclone" "copy" "file＼＊＜／？＞：＂｜.txt" "remote:" "-vv" "--local-encoding" "None" "--drive-encoding" "Slash,InvalidUtf8"]
2020/02/03 09:06:15 DEBUG : Using config file from "C:\\Users\\usern\\.config\\rclone\\rclone.conf"
2020/02/03 09:06:17 ERROR : : error reading source directory: directory not found
2020/02/03 09:06:17 INFO  : Google drive root '': Waiting for checks to finish
2020/02/03 09:06:17 INFO  : Google drive root '': Waiting for transfers to finish
2020/02/03 09:06:17 ERROR : Attempt 1/3 failed with 1 errors and: directory not found
2020/02/03 09:06:18 ERROR : : error reading source directory: directory not found
2020/02/03 09:06:18 INFO  : Google drive root '': Waiting for checks to finish
2020/02/03 09:06:18 INFO  : Google drive root '': Waiting for transfers to finish
2020/02/03 09:06:18 ERROR : Attempt 2/3 failed with 1 errors and: directory not found
2020/02/03 09:06:25 ERROR : : error reading source directory: directory not found
2020/02/03 09:06:25 INFO  : Google drive root '': Waiting for checks to finish
2020/02/03 09:06:25 INFO  : Google drive root '': Waiting for transfers to finish
2020/02/03 09:06:25 ERROR : Attempt 3/3 failed with 1 errors and: directory not found
2020/02/03 09:06:25 Failed to copy: directory not found
```

**Comment by SL-Gundam** [comment]
I'm having the same issue: https://github.com/rclone/rclone/issues/3836#issuecomment-583006595

Tried --drive-encoding Slash,InvalidUtf8

> C:\rclone\rclone.exe sync --bwlimit 3M --track-renames --delete-after --delete-excluded --exclude-from "C:/rclone/Configs/Exclusions.txt" --drive-encoding Slash,InvalidUtf8 --progress --log-file "C:\Users\name\Desktop\MirrorD Log\Rclone TEST.log" --log-level DEBUG "local:E:/Rclone test/" cryptGDrive:TEST

But "aaa ／aaa／.mp4" is still uploaded as "aaa ‛／aaa‛／.mp4"

This is also mounted on a NAS system (linux based). The mount does not remove the quote. This would not be an issue if the upload would never add the quote in the first place.

**Comment by ncw** [comment]
I think what you need is `--local-encoding Slash,InvalidUtf8` and `--drive-encoding Slash,InvalidUtf8`

That seems to work in my tests.

**Comment by SL-Gundam** [comment]
Works for me as well
Thank you

**Comment by ncw** [comment]
Great - glad it is working now :-)
