### ISSUE TITLE
Install Script Does Not Work on MacOS 

### ISSUE THREAD

**Issue by jeff-geoff** [rclone/rclone#3922]
#### What is the problem you are having with rclone?

curl https://rclone.org/install.sh | sudo bash
does not install rclone on MacOS 10.15.2

#### What is your rclone version (output from `rclone version`)

rclone v1.51.0 (now, but not relevant)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
darwin/amd64

####  Which cloud storage system are you using? (eg Google Drive)
N/A

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

curl https://rclone.org/install.sh | sudo bash

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

N/A

Script terminates with:
[1]  + 17316 done                    curl https://rclone.org/install.sh | 
       17317 suspended (tty output)  sudo bash

Problem can be solved by solved by:

$wget https://rclone.org/install.sh
$chmod u+x install.sh
$sudo ./install.sh

So install.sh itself executes correctly under MacOS, just not via the instructions on the Download page.

**Comment by animosity22** [comment]
Works fine on my Mac.

```
Last login: Sat Feb  1 12:49:42 on ttys000
textere@seraphim Downloads % curl https://rclone.org/install.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4526  100  4526    0     0   8010      0 --:--:-- --:--:-- --:--:--  8010
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    15  100    15    0     0     32      0 --:--:-- --:--:-- --:--:--    32
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.2M  100 14.2M    0     0  2658k      0  0:00:05  0:00:05 --:--:-- 2974k
Archive:  rclone-current-osx-amd64.zip
   creating: tmp_unzip_dir_for_rclone/rclone-v1.51.0-osx-amd64/
 extracting: tmp_unzip_dir_for_rclone/rclone-v1.51.0-osx-amd64/git-log.txt  [empty]
  inflating: tmp_unzip_dir_for_rclone/rclone-v1.51.0-osx-amd64/rclone  [binary]
  inflating: tmp_unzip_dir_for_rclone/rclone-v1.51.0-osx-amd64/rclone.1  [text]
  inflating: tmp_unzip_dir_for_rclone/rclone-v1.51.0-osx-amd64/README.html  [text]
  inflating: tmp_unzip_dir_for_rclone/rclone-v1.51.0-osx-amd64/README.txt  [text]
mkdir: /Users/textere/.config/rclone: File exists
```

You need to type in the sudo password for it to continue.

**Comment by dr-mcgillicuddy** [comment]
Which version of MacOS are you on?

What is your default shell?  It switched to zsh in Catalina, maybe that could be a factor...?

**Comment by animosity22** [comment]
Same version.

![image](https://user-images.githubusercontent.com/5088712/73602923-8a185100-4549-11ea-8730-5e00ef8480c7.png)

**Comment by dr-mcgillicuddy** [comment]
Can reproduce.  
<img width="642" alt="Screen Shot 2020-02-01 at 10 30 46 PM" src="https://user-images.githubusercontent.com/60207520/73603004-c09e9d80-4542-11ea-9ba1-13c6695a10ed.png">

I don't know what to make of the errant "Password:"
OS X 10.15.2 here, though.

**Comment by animosity22** [comment]
It's because you are stuck trying to enter in the password. You need to sudo su -

or something and enter in the password.

**Comment by dr-mcgillicuddy** [comment]
Running `sudo curl https://rclone.org/install.sh | bash` instead of `curl https://rclone.org/install.sh | sudo bash` works.

Running su after the script has suspended the bash process doesn't do anything.

**Comment by animosity22** [comment]
It's all how your system is setup if you require a password or not.

**Comment by dr-mcgillicuddy** [comment]
I'm not sure what you mean by that.

After updating it now pauses at the password prompt for about 2 seconds and then exhibits the same behavior as before.  Standard zsh profile for me, not sure about anyone else.

**Comment by animosity22** [comment]
If you open a terminal and run a command like "sudo su", it'll ask for a password. Type in your password, type exit and you can run the install command:

curl https://rclone.org/install.sh | sudo bash

The reason it doesn't work for you is because the | in the command above is stuck waiting on a password prompt in your terminal.

You can type 'bash' first and run the command and type in your password. zsh acts a bit different from bash in terms of it just.

In zsh, you can run:

stty -tostop

and run the install

or you can even fix your sudo rules to not ask for a password.

**Comment by Yexiaoxing** [comment]
Try `sudo bash < <(curl https://rclone.org/install.sh )`.

**Comment by animosity22** [comment]
This seems to be answered. If you still have a question, please use https://forums.rclone.org

**Comment by MaBra17** [comment]
> Running `sudo curl https://rclone.org/install.sh | bash` instead of `curl https://rclone.org/install.sh | sudo bash` works.
> 
> Running su after the script has suspended the bash process doesn't do anything.

Thanks a lot, this works for me using zsh. I run: `sudo curl https://rclone.org/install.sh | zsh`

**Comment by Masamune3210** [comment]
Just a nitpick, but please dont get into the habit of piping shell scripts straight into bash. All it takes is one to hose your system if you arent careful
