### ISSUE TITLE
Consistent use of accounts in one request. Drive.

### ISSUE THREAD

**Issue by IIeTp** [rclone/rclone#3924]
#### What is your current rclone version (output from `rclone version`)?
1.51.0

In the latest update for Drive remote, a new flag was added - `--drive-stop-on-upload-limit`.
Is it possible to add multiple accounts at once in one request?
Example:
`rclone sync drive0:folder drive1:folder; drive0:folder drive2:folder; drive0:folder drive3:folder --drive-stop-on-upload-limit`

The point is, when the upload limit is reached, go to the next account with the same flags.

**Comment by ncw** [comment]
I don't want to put features in to work-around google transfer limits in rclone - sorry - that would likely cause rclone to be banned from Google Drive.
