### ISSUE TITLE
Failed to delete files during the "sync" process.

### ISSUE THREAD

**Issue by knowledge-one** [rclone/rclone#3925]
#### What is the problem you are having with rclone?
I use rclone to syne files from my onedrive to googlegrive, and **make sure the files in dest and source are strictly the same** , so I use the `rclone sync source dest` command to realize this function。

However, after several days of tests, I found the files in dest are more than that in source. For instance:
* After first sync:
  + Source: file-a, file-b, file-c
  + Dest: file-a, file-b, file-c
* After second sync (i delete file-a and add file-d):
  + Source:  file-b, file-c, file-d
  + Dest: file-a, file-b, file-c, file-d

The sync command seems won't delete the files in dest which are deleted in the source.

#### What is your rclone version (output from `rclone version`)

`rclone v1.47.0`

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
`Centos 7`

####  Which cloud storage system are you using? (eg Google Drive)

* Onedrive for Business
* Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone  sync --size-only --tpslimit 1.5 onedrive: GD:Backup/`

**Comment by ncw** [comment]
> The sync command seems won't delete the files in dest which are deleted in the source.

The sync command won't delete files if there were errors in the sync.  Check the log for ERROR lines.

I suggest you try 1.51 also which was released recently.

**Comment by knowledge-one** [comment]
Thanks so much for the suggestions. 
I checked the logs and find some errors. After all the errors are corrected, the sync process finished successfully and files are deleted.
