### ISSUE TITLE
S3 integration tests don't pass when running against Minio

### ISSUE THREAD

**Issue by buengese** [rclone/rclone#3934]
The S3 integration tests don't pass for Minio. This appears to be a problem with character encoding.  

#### rclone version
rclone v1.51.0-DEV (master)

#### minio version
minio version RELEASE.2020-01-25T02-50-51Z

#### log
https://pastebin.com/raw/i7DexU9x

**Comment by ncw** [comment]
The daily integration tests run against minio. I had to mark some tests as failing. These should probably be reported as bugs on minio, but I didn't get a chance to do that - feel free if you have time!

https://github.com/rclone/rclone/blob/fe6f4135b420fb22bafc9a25baf1ee91ec9291ac/fstest/test_all/config.yaml#L114-L121

**Comment by buengese** [comment]
I did create an [https://github.com/minio/minio/issues/8950](issue) at minio but they don't consider this a problem right now. I'm thinking of adding the necessary necessary encoder rules to the s3 backend for minio only. What do you think?

**Comment by ncw** [comment]
You can add "encoding" to your minio remote now so you could solve the problem locally quite easily like that.

Adding it to the backend means that when/if they become fully S3 compliant the encoding rules will be doing the wrong thing.

**Comment by harshavardhana** [comment]
> The daily integration tests run against minio. I had to mark some tests as failing. These should probably be reported as bugs on minio, but I didn't get a chance to do that - feel free if you have time!

@ncw how do we run them?

**Comment by ncw** [comment]
[Checkout rclone and build it](https://rclone.org/install/#install-from-source) (it is a go project so should be familiar :-)

[Set up a remote pointing at minio](https://rclone.org/s3/)

Say you called the remote `minio` then you run the tests like this

```
# in the rclone source directory
cd backend/s3
go test -v -remote minio:
```

**Comment by harshavardhana** [comment]
Looks like those characters cause routing issues in gorilla/mux @ncw - PutObject seems to become PutBucket() we need to fix this.

**Comment by buengese** [comment]
Thank you for looking into this.

**Comment by harshavardhana** [comment]
Fixed the issue relevant PR referenced here - but we also need the change from rclone 

```diff
diff --git a/backend/s3/s3.go b/backend/s3/s3.go 
index 28b1f3e..a0c021e 100644
--- a/backend/s3/s3.go
+++ b/backend/s3/s3.go
@@ -1338,7 +1338,7 @@ func (f *Fs) list(ctx context.Context, bucket, directory, prefix string, addBuck
        //
        // So we enable only on providers we know supports it properly, all others can retry when a
        // XML Syntax error is detected.
-       var urlEncodeListings = (f.opt.Provider == "AWS" || f.opt.Provider == "Wasabi" || f.opt.Provider == "Alibaba")
+       var urlEncodeListings = (f.opt.Provider == "Minio" || f.opt.Provider == "AWS" || f.opt.Provider == "Wasabi" || f.opt.Provider == "Alibaba")
        for {
                // FIXME need to implement ALL loop
                req := s3.ListObjectsInput{
```

**Comment by ncw** [comment]
@harshavardhana according to my notes this feature was merged in https://github.com/minio/minio/pull/7265 so I guess there could be minio versions in production which don't support URL encoding listings...

Does the retry on XMLSyntax error work properly?

**Comment by harshavardhana** [comment]
No it doesn't @ncw the XML is successfully decoding the values into incorrect byte representations. 

Most of our users would have already upgraded, it's been more than a year. The ones who didn't upgrade, shall be asked to upgrade.

**Comment by ncw** [comment]
Fair enough! I merged 90377f5e65dfd0311596a06017ab79a4600b6a41 with that fix in (more-or-less)

**Comment by harshavardhana** [comment]
The server PR is merged and can be tested with minio/minio:edge

**Comment by ncw** [comment]
@harshavardhana that works perfectly - well done :-)

I made a new integration test for `minio/minio:edge` as well as the one we already run for `minio/minio`.

The only test failure left is the tiering but that failure is understandable.

If you want to run all the integration tests for minio locally the best way is

```
# in rclone source root
go install ./...
test_all -remotes TestS3Minio:,TestS3MinioEdge:
```

This assumes a working docker setup on your machine. It will pull the `minio/minio` and `minio/minio:edge` docker images, test them then open a browser window with the results.

I'll close this now since I think we are done here - thank you for your help @harshavardhana
