### ISSUE TITLE
v1.51 Constantly high IOWAIT

### ISSUE THREAD

**Issue by EnorMOZ** [rclone/rclone#3937]
Bug report for tracking purpose based of https://forum.rclone.org/t/constantly-high-iowait-add-log/14156/15

#### What is the problem you are having with rclone?
Constantly high IOWAIT

#### What is your rclone version (output from `rclone version`)
v1.51

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 18.04.3 LTS / 64 Bit

####  Which cloud storage system are you using? (eg Google Drive)
Ubuntu 18.04.3 LTS / 64 Bit

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
/usr/bin/screen -dmS gc /usr/bin/rclone mount gdrive_crypt: /mnt/gc 
--config /mnt/hdd/rclone/rclone.conf 
--use-mmap --fast-list --vfs-cache-mode writes 
--cache-dir /mnt/hdd/tmp/gc/cache 
--allow-other --umask 0 --tpslimit 10 --tpslimit-burst 20
--rc --rc-user xxxx --rc-pass xxxx -vv --log-file=/mnt/hdd/tmp/rclone.log

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
http://www.mediafire.com/file/2ilu9k2nu9m9rzp/rclone_1_51.log/file
http://www.mediafire.com/file/wxbyldxn065v3vt/rclone_1_50.2.log/file

The following lines have been added.
2020/02/03 23:58:31 DEBUG : media/드라마/스토브리그.E01.191213.1080p-NEXT.mp4: waiting for in-sequence read to 1008861184 for 5ms

Netdata graph when testing
v1.51
![image](https://user-images.githubusercontent.com/13998170/73847117-a3dcc100-47f3-11ea-9871-d70945c1a72c.png)
![image](https://user-images.githubusercontent.com/13998170/73847144-ac34fc00-47f3-11ea-8028-9053f437f2b1.png)
v1.50.2
![image](https://user-images.githubusercontent.com/13998170/73847172-c1aa2600-47f3-11ea-9d3f-d61cbab812d9.png)
![image](https://user-images.githubusercontent.com/13998170/73847189-c66eda00-47f3-11ea-976f-82071e7e52e0.png)

bhpark:
below test removed crypt backend.
no difference, with or without a crypt backend.

executed 'dd if=/mnt/tmp/1g_zero of=/dev/null bs=2M'

Increasing the time decreases the error output frequency.

wait time and error output count(somewhat variable)
5ms     => 394
10ms    => 63
20ms    => 11
50ms    => 4
However, IOWAIT will not decrease over 10ms.
It is also still high compared to the --async-read=false option.
![image](https://user-images.githubusercontent.com/13998170/73847292-f74f0f00-47f3-11ea-8b32-ef37d43098ab.png)

bhpark:
Upload debug trace/profile
http://www.mediafire.com/file/h6yd7089tljhptt/pprof.zip/file

This was my first time using debug tool.
Please let me know if something is wrong
`Test method

mount  
./rclone mount --async-read=true --vfs-read-wait 10ms -vv gdrive_media: /mnt/tmp/ --rc 2>&1 | grep 'abort.*in-sequence' 

transfer
dd if=/mnt/tmp/1g_zero of=/dev/null bs=2M

get profile(In transmit)
wget http://localhost:5572/debug/pprof/trace?seconds=5
wget http://localhost:5572/debug/pprof/profile
wget http://localhost:5572/debug/pprof/goroutine?debug=1
wget http://localhost:5572/debug/pprof/block
wget http://localhost:5572/debug/pprof/mutex
wget http://localhost:5572/debug/pprof/heap`

**Comment by ferferga** [comment]
I think this is related to what I'm also experiencing with mounted remotes in Windows. Older versions made apps writing larger files to freeze for a second while writing to the cached mounted remote, however they recovered quickly. 1.51 makes it impossible to explore larger folders without hiccups or write data while exploring directories: you can do one or the other, but not both, as you could before. Doing both operations at the same time will freeze your Windows Explorer and the app that was accessing the mounted folders forever, until you restart the NSSM service.

**Comment by ncw** [comment]
@ferferga that sounds like a different issue to me - the async read stuff only affects non Windows builds. Can you make a new issue about that, filling in the issue template and making a reproduction if you can? Thanks

**Comment by moust4ki** [comment]
Same issue for me under Ubuntu: Have a VFS plex share and have a constant I/Owait of 10-15% since i'm on 1.51.
i7 7700 and NVMe.

**Comment by alexisnoria** [comment]
I had the same problem, so, I uninstalled 1.51 and install 1.45.
GCP with debian 9.

**Comment by darthShadow** [comment]
@alexisnoria You don't need to go that far back. 1.50.2 is the just previous release and doesn't have the changes that caused this issue

**Comment by ncw** [comment]
I have posted the latest beta with a fixes for this

https://beta.rclone.org/v1.51.0-336-g951099db-beta/

I've raised the read timeout to 20ms and along with another fix I think this should be much better.

Comments appreciated!

**Comment by ivandeex** [comment]
@EnorMOZ @alexisnoria 
Please try latest rclone 1.53.2
Does the problem reproduce?

**Comment by ivandeex** [comment]
@ncw 
Apparently topic starter is not interested anymore.
I think you can delete the beta branch

**Comment by ivandeex** [comment]
Closing due to topic starter inactive for 10 months!

**Comment by douglasparker** [comment]
I have an issue with extremely slow response times for media playback and high IOWAIT that seems to happen when I hit the upload rate limit to a team drive and my vfs cache starts to fill.

I am unsure if this is related to that, but I planned to open an issue with full details as soon as I get the chance.

The solution is to clear the VFS cache and media starts immediately again instead of up to 30 seconds later. High IOWAIT also disappears.
