### ISSUE TITLE
Problem with  Failed to create file system for : Outdated config - please reconfigure this backend

### ISSUE THREAD

**Issue by SlashGIP** [rclone/rclone#3939]
Hi, 

i really like to use rclone. But since yesterday ive got a problem. 

I cannot mount jottacloud anymore. 

The prompt i get is this: " Failed to create file system for "remote:": Outdated config - please reconfigure this backend" 

I tried to search github but i didnt find this problem. 

1. Version: rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7

2. it works fine on my Linux VM in the INternet
3. it does not work anymore on my linux server at home
4. I did not change the config file. 
5. i updatet to the new Version 
6. maybe i tried a lil bit with cache in the rclone.service, but dont think, that thats the problem because it doesnt even work before the service tried to start
7. I tried to reconfigure the whoe config. - It worked but I didnt see any of my crypted files anymore so thats not the solution im looking for :-)

So thanks for any support

I just dont know how to fix this.

**Comment by ncw** [comment]
You need to re-configure the jottacloud backend to make this work.

So `rclone config reconnect remote:` should do it.

Be careful answering which type of `mountpoint` you are using - that is probably why your files disappeared.

**Comment by SlashGIP** [comment]
Hi, thx for ur support. U were right. I "just" needed to reconfigure the jotta part.
