### ISSUE TITLE
OVH Public Cloud new endpoint APIs

### ISSUE THREAD

**Issue by pavethem** [rclone/rclone#3940]
I just received this e-mail from OVH, notifying me of pending changes to their backend URLs for Object Storage and Cloud Archive.

     Here is the list of endpoints that will change:
 
     Previous One  --------->  New One

     - storage.bhs1.cloud.ovh.net -> storage.bhs.cloud.ovh.net
     - storage.bhs3.cloud.ovh.net -> storage.bhs.cloud.ovh.net
     - storage.bhs5.cloud.ovh.net -> storage.bhs.cloud.ovh.net
     - storage.de1.cloud.ovh.net -> storage.de.cloud.ovh.net
     - storage.gra1.cloud.ovh.net -> storage.gra.cloud.ovh.net
     - storage.gra3.cloud.ovh.net -> storage.gra.cloud.ovh.net
     - storage.gra5.cloud.ovh.net -> storage.gra.cloud.ovh.net
     - storage.gra7.cloud.ovh.net -> storage.gra.cloud.ovh.net
     - storage.sbg1.cloud.ovh.net -> storage.sbg.cloud.ovh.net
     - storage.sbg3.cloud.ovh.net -> storage.sbg.cloud.ovh.net
     - storage.sbg5.cloud.ovh.net -> storage.sbg.cloud.ovh.net
     - storage.sgp1.cloud.ovh.net -> storage.sgp.cloud.ovh.net
     - storage.syd1.cloud.ovh.net -> storage.syd.cloud.ovh.net
     - storage.uk1.cloud.ovh.net -> storage.uk.cloud.ovh.net
     - storage.waw1.cloud.ovh.net -> storage.waw.cloud.ovh.net

[http://travaux.ovh.net/?do=details&id=42314](url)

Does rclone already support these new URLs, or is there a setting that users can change to set the new URL manually, other than (I guess) in a hosts file? I'm using rclone 1.50.2

**Comment by ncw** [comment]
Rclone reads the catalog from the auth endpoint "https://auth.cloud.ovh.net/v3" and it will pick up the new names of the storage nodes from there so you shouldn't have to do anything.

**Comment by animosity22** [comment]
@pavethem  - does that answer your question?

**Comment by pavethem** [comment]
Absolutely, this can be closed.

**Comment by animosity22** [comment]
Solvfed.
