### ISSUE TITLE
Download specific single file from Google Drive

### ISSUE THREAD

**Issue by bovirus** [rclone/rclone#3944]
I red a lot of article, help,e tc but I didn find the ansqwer to my request.

I want to downlaod a singel specific file from Google drive with rclone

https://drive.google.com/file/d/Filed

where FileID is teh FielId for specfic file.

How can download this file with rclone using command line?

**Comment by ncw** [comment]
If all you know is a file ID then rclone can't currently download it for you.

You might be able to construct a download URL though using the file ID

If you know the ID of the directory that the file is in then rclone **can** download the file for you.

**Comment by bovirus** [comment]
@ncw 
I just have a link like

https://drive.google.com/file/d/xxxxxxxx/view

where xxxxx is FileID

**Comment by ncw** [comment]
You should be able to do this

    rclone copyurl 'https://drive.google.com/uc?export=download&id=FileID' localName.ext

**Comment by Dibbyo456** [comment]
> You should be able to do this
> 
> ```
> rclone copyurl 'https://drive.google.com/uc?export=download&id=FileID' localName.ext
> ```

It is not possible to download a google drive files that way because the link is a html page not a direct link. Google drive uses some cookies authorizations before you can get the actual download link.

@bovirus Rclone can't do this yet but you can use [goodls](https://github.com/tanaikech/goodls) for now. No api key required if shared with public.

Example command:

```
goodls --url="https://drive.google.com/file/d/XXXXXXXXXXXXXXXXXXXX/view"
```

**Comment by ncw** [comment]
> It is not possible to download a google drive files that way because the link is a html page not a direct link.

If the file is shared then it will work - I tried it before writing that post!

**Comment by Dibbyo456** [comment]
> If the file is shared then it will work - I tried it before writing that post!

Ah, you are right it does it work. However if the file is large and google can't do virus scan then it won't work. But for small files it does work.

**Comment by ncw** [comment]
> Ah, you are right it does it work. However if the file is large and google can't do virus scan then it won't work. But for small files it does work.

Ah, I see - that is what the goodls tool does.

**Comment by animosity22** [comment]
This looks to be answered as best as can be.

If you still have a question, please ask on https://forums.rclone.org
