### ISSUE TITLE
jottacloud config didn't work  Failed to get oauth token

### ISSUE THREAD

**Issue by Wildvirus** [rclone/rclone#3945]
I'm using rclone on a synology nas.

Installed is rclone version 1.51.0-010-gfld9bd5e-beta

creating new remote 
Name: MyJotta
Storage: 17
advanced config - default
Login Token - I got a key from Jotta with 259 character
rclone config breaks with "Failes to get oauth token: illegal base64 data at input byte 256"

Any ideas how to use rclone on a synology nas?

**Comment by buengese** [comment]
Sadly I cannot reproduce your problem. Are you sure you copied the hole token? I’m fairly certain they should actually be longer than 259 characters.

**Comment by Wildvirus** [comment]
I tried it with Firefox and Chrome. Both received 259 character

Login with JottaCloud commandtool was successful with that key

**Comment by buengese** [comment]
This sounds very strange. Are you using normal Jottacloud or the whitelabel version(i.e. getsky.no) and when did you register your account?
You’ll probably need to send me on of you login tokens. You can just generate 2 this should invalidate the first one.  (Send it to buengese@gmail.com)

**Comment by Wildvirus** [comment]
I registered years ago, probably 2012. 
It's Jottacloud, nothing whitelabel.
I cannot generate 2 keys. Every time I click on "Create" it shows the same key. 
Attached a screenshot of the page
![grafik](https://user-images.githubusercontent.com/9499201/74093045-ee4c8f00-4acc-11ea-8d6b-a88d2945c702.png)

**Comment by buengese** [comment]
Are you it’s really the same key? Only a the last 1/5 or so is expected to change.

**Comment by Wildvirus** [comment]
It's the same key. But I stopped using it. Jottacloud is to small for the data, I switched to another provider and he is direct usable in my nas.

**Comment by Fjodor42** [comment]
I got the same the other day.

Turned out that the Base86-coded API token text was missing one or two characters at the end.

In other words, I ran it though `base64 -d`, got the same error, then tried it with the substring up until the char that was reported invalid. That produced partial JSON data, where the final `"}` was missing.

Adding that to the JSON data, and running it through `base64` and copy/pasting that into the rclone config prompt did the trick.

Somebody should probably tell Jottacloud...

**Comment by buengese** [comment]
That’s what I expected however the official client working sounds very weird. The tokens I generate are correct 100% of the time. But if anyone of you can reproduce the broken token could you try both rclone and the official client just to make sure?

**Comment by andyoslo** [comment]
I hva the same problem with two different tokens, haven't tried it on the official Jotta software

OS: Debian 10
rclone: 1.51.0

**Comment by dgjansen** [comment]
Same problem here. 
rclone v1.51.0
- os/arch: linux/arm
- go version: go1.13.7

The fix by @Fjodor42 worked great. The token ends with an `fQ` in my case. But it needs to end with `fQo=`. In other words, add `o=` at the end and you're good to go it seems.

**Comment by TruckerZer0** [comment]
Same problem here, no official client installed since there isn't an offical openSUSE package/repo;

OS: openSUSE Tumbleweed x86_64
Rclone version: 1.51.0
Go version: 1.12.16

**Comment by buengese** [comment]
Is anyone of you able to check if the official client accepts the broken token? It wouldn't be a big problem to include a workaround for this in rclone but I'd like to know if this is a bug or just another case of jottacloud weirdness.

**Comment by andyoslo** [comment]
> Is anyone of you able to check if the official client accepts the broken token? It wouldn't be a big problem to include a workaround for this in rclone but I'd like to know if this is a bug or just another case of jottacloud weirdness.

I have tested it now, the official client accepts the broken token.
Newest jotta-cli client used for testing

**Comment by buengese** [comment]
Odd. That means they handle it in the official client so it’s likely not a bug. I might have to ask jottacloud what’s up here before fixing this.

**Comment by TruckerZer0** [comment]
@buengese I can confirm that with this build Jottacloud works smooth as silk, thanks a lot!

**Comment by andyoslo** [comment]
> ~Odd. That means they handle it in the official client so it’s likely not a bug. I might have to ask jottacloud what’s up here before fixing this.~
> 
> I may just have been stupid here the entire time. Everyone having the token issues please try [this beta build](https://beta.rclone.org/branch/v1.51.0-045-gd3eadaa1-jotta_fix-beta/)

When i try to install this beta build on Debian 10 i get the following message when using sudo dpkg -i rclone-v1.51.0-045-gd3eadaa1-jotta_fix-beta-linux-amd64.deb

dpkg: error processing archive rclone-v1.51.0-045-gd3eadaa1-jotta_fix-beta-linux-amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'rclone':
 'Version' field value '1.51.0.045.gd3eadaa1.jotta_fix.beta': invalid character in version number
Errors were encountered while processing:
 rclone-v1.51.0-045-gd3eadaa1-jotta_fix-beta-linux-amd64.deb

**Comment by buengese** [comment]
I've merged this fix into master so you can just download the [latest beta](https://beta.rclone.org/) (in around 20 minutes). Your install error was likely caused by me using an underscore in the branch name which is apparently not supported by dpkg.
