### ISSUE TITLE
Hangs on mounting Google Drive

### ISSUE THREAD

**Issue by suityou01** [rclone/rclone#3946]
#### What is the problem you are having with rclone?

It hangs when trying to mount google drive

#### What is your rclone version (output from `rclone version`)
rclone v1.45
- os/arch: linux/arm
- go version: go1.11.6

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
raspbian buster

####  Which cloud storage system are you using? (eg Google Drive)
Google drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount gdrive: /home/pi/mnt/gdrive

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2020/02/08 14:23:24 DEBUG : rclone: Version "v1.45" starting with parameters ["rclone" "mount" "gdrive:" "/home/pi/mnt/gdrive" "-vv"]
2020/02/08 14:23:24 DEBUG : Using config file from "/home/pi/.config/rclone/rclone.conf"
2020/02/08 14:23:24 DEBUG : Google drive root '': Mounting on "/home/pi/mnt/gdrive"
2020/02/08 14:23:24 DEBUG : Adding path "vfs/forget" to remote control registry
2020/02/08 14:23:24 DEBUG : Adding path "vfs/refresh" to remote control registry
2020/02/08 14:23:24 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2020/02/08 14:23:24 DEBUG : : Root: 
2020/02/08 14:23:24 DEBUG : : >Root: node=/, err=<nil>
2020/02/08 14:24:24 DEBUG : Google drive root '': Checking for changes on remote
2020/02/08 14:25:24 DEBUG : Google drive root '': Checking for changes on remote
2020/02/08 14:26:24 DEBUG : Google drive root '': Checking for changes on remote

**Comment by ncw** [comment]
`rclone mount` doesn't return - it stays running to run the mount.

If you want it to daemonize then add the `--daemon` flag.

**Comment by suityou01** [comment]
Ah. Seems obvious now you mention it. I guess because a regular mount command does return I was expecting something similar. For my needs I haven't even bothered with a mount and just run the rclone commands in bash using /usr/local/bin/rclone. Thanks for the info, I will give it a try.

**Comment by suityou01** [comment]
behaviour as per design.
