### ISSUE TITLE
Directory Junctions with -L: Access denied

### ISSUE THREAD

**Issue by ltGuillaume** [rclone/rclone#3948]
#### What is the problem you are having with rclone?
As I understand it from #867 RClone _should_ handle directory junctions as regular folders and traverse them normally _if `-L` is set_. When testing this on normal directory junctions, created by Windows itself, e.g.
```
18-02-2018  00:04    <JUNCTION>     My Music [C:\Users\User\Music]
18-02-2018  00:04    <JUNCTION>     My Pictures [C:\Users\User\Pictures]
18-02-2018  00:04    <JUNCTION>     My Videos [C:\Users\User\Videos]
```
I get the following error message in RClone's log: `My Music: failed to open directory "My Music": open \\?\C:\Users\User\Documents\My Music: Access is denied.`

I found #2336, but here the user want to skip junctions. Ironically, this is what I want as well, _but I do want to follow symlinks_ (both files and folders). The reason for this is that Windows places directory junctions all over the place, and following them would often duplicate data in the backups. Symlinks, however, I use on a regular basis in order to _include_ files and folders into a backup.

So, I'm addressing this _in fear of future changes_ to this behavior, because currently junctions + `-L` give an Access denied error.

What imho would be best is if there were a separate feature for symlinks (the current `-L`/`-copy-links`) and one for following junctions (which would then also fix the Access denied issue). Since Windows puts junctions all over your drive, but symlinks can be a great tool for structuring your drives, and your backups, I think it would make sense to handle them separately.

#### What is your rclone version (output from `rclone version`)
1.51.0

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 x64 1809LTSC

####  Which cloud storage system are you using? (eg Google Drive)
None (local file system)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone sync -L -vv C:\Users\User\Documents D:\Backup`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "sync" "-L" "-vv" "C:\\Users\\User\\Documents" "D:\\Backup"]
ERROR : My Music: failed to open directory "My Music": open \\?\C:\Users\User\Documents\My Music: Access is denied.
ERROR : My Pictures: failed to open directory "My Pictures": open \\?\C:\Users\User\Documents\My Pictures: Access is denied.
ERROR : My Videos: failed to open directory "My Videos": open \\?\C:\Users\User\Documents\My Videos: Access is denied.
ERROR : Local file system at //?/D:/Backup: not deleting files as there were IO errors
ERROR : Local file system at //?/D:/Backup: not deleting directories as there were IO errors
ERROR : Attempt 1/3 failed with 4 errors and: not deleting files as there were IO errors
ERROR : My Music: failed to open directory "My Music": open \\?\C:\Users\User\Documents\My Music: Access is denied.
ERROR : My Pictures: failed to open directory "My Pictures": open \\?\C:\Users\User\Documents\My Pictures: Access is denied.
ERROR : My Videos: failed to open directory "My Videos": open \\?\C:\Users\User\Documents\My Videos: Access is denied.
INFO  : Local file system at //?/D:/Backup: Making map for --track-renames
INFO  : Local file system at //?/D:/Backup: Finished making map for --track-renames
INFO  : Local file system at //?/D:/Backup: Waiting for checks to finish
DEBUG : desktop.ini: Size and modification time the same (differ by 0s, within tolerance 100ns)
DEBUG : desktop.ini: Unchanged skipping
DEBUG : Pictures/desktop.ini: Size and modification time the same (differ by 0s, within tolerance 100ns)
DEBUG : Pictures/desktop.ini: Unchanged skipping
DEBUG : Videos/desktop.ini: Size and modification time the same (differ by 0s, within tolerance 100ns)
DEBUG : Videos/desktop.ini: Unchanged skipping
INFO  : Local file system at //?/D:/Backup: Waiting for renames to finish
INFO  : Local file system at //?/D:/Backup: Waiting for transfers to finish
ERROR : Local file system at //?/D:/Backup: not deleting files as there were IO errors
ERROR : Local file system at //?/D:/Backup: not deleting directories as there were IO errors
ERROR : Attempt 2/3 failed with 4 errors and: not deleting files as there were IO errors
DEBUG : desktop.ini: Size and modification time the same (differ by 0s, within tolerance 100ns)
DEBUG : desktop.ini: Unchanged skipping
ERROR : My Music: failed to open directory "My Music": open \\?\C:\Users\User\Documents\My Music: Access is denied.
ERROR : My Pictures: failed to open directory "My Pictures": open \\?\C:\Users\User\Documents\My Pictures: Access is denied.
ERROR : My Videos: failed to open directory "My Videos": open \\?\C:\Users\User\Documents\My Videos: Access is denied.
DEBUG : Pictures/desktop.ini: Size and modification time the same (differ by 0s, within tolerance 100ns)
DEBUG : Pictures/desktop.ini: Unchanged skipping
INFO  : Local file system at //?/D:/Backup: Making map for --track-renames
DEBUG : Videos/desktop.ini: Size and modification time the same (differ by 0s, within tolerance 100ns)
INFO  : Local file system at //?/D:/Backup: Finished making map for --track-renames
DEBUG : Videos/desktop.ini: Unchanged skipping
INFO  : Local file system at //?/D:/Backup: Waiting for checks to finish
INFO  : Local file system at //?/D:/Backup: Waiting for renames to finish
INFO  : Local file system at //?/D:/Backup: Waiting for transfers to finish
ERROR : Local file system at //?/D:/Backup: not deleting files as there were IO errors
ERROR : Local file system at //?/D:/Backup: not deleting directories as there were IO errors
ERROR : Attempt 3/3 failed with 4 errors and: not deleting files as there were IO errors
Failed to sync with 4 errors: last error was: not deleting files as there were IO errors
```

**Comment by ncw** [comment]
Rclone should be treating junction points and symlinks the same.

> I get the following error message in RClone's log: `My Music: failed to open directory "My Music": open \\?\C:\Users\User\Documents\My Music: Access is denied.`

Any ideas why it gives that error?

My instinct is to fix the access denied error and make it follow the junction. However I take your point about treating junctions and symlinks differently.

I'm not sure I can tell Junctions and Symlinks apart in the go standard library

**Comment by ltGuillaume** [comment]
The only thing I could find about it was here: https://godoc.org/github.com/docker/docker/pkg/symlink
> This version has been updated to support long paths prepended with `\\?\`.

But whatever happens with RClone concerning this, please realize that directory junctions are a potential minefield (traversing them in Windows user folders almost inherently leads to endless loops), whereas symlinks aren't used for those "legacy shortcuts" and thus could be really useful with RClone.

All in all, it seems like a "happy accident" the way RClone currently handles directory junctions when using `-L`.

**Comment by ivandeex** [comment]
> All in all, it seems like a "happy accident" the way RClone currently handles directory junctions when using -L

@ltGuillaume It seems the problem was resolved

**Comment by cr1cr1** [comment]
If the source was synced with `-l` and then use `-L` it will be a disaster on windows, will delete files under the junction. I do not really recommend it.

**Comment by ltGuillaume** [comment]
That's true. Either way, RClone has a long way to go when it comes to file system compatibility, be it junctions, symlinks or permissions.

**Comment by cr1cr1** [comment]
Well, in most cases on Windows using `-l` or a local config:

```ini
[local]
type = local
links = true
```

.. and running elevated, **most** of the times, the junctions are correctly created. Sometimes (did not figure out yet a pattern), rclone will:

1. Give `permission denied` when trying to delete a current junction
2.  Rename the current junction as `.rclonelink` and create a non-valid junction instead

I am testing this with the `scoop` directory that creates a `current` junction for every app and synchronizes via a cloud provider between 2 computers (using a simple cmd script that I run manually for now).
