### ISSUE TITLE
rclone diff as alias for rclone check

### ISSUE THREAD

**Issue by jtagcat** [rclone/rclone#3962]
#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.4
```

#### What problem are you are trying to solve?
Keep me from needing to check the docs each time I want to run `rclone check`.

#### How do you think rclone should be changed to solve that?
If you run `rclone diff`, treat it as if `rclone check` was run.

**Comment by ncw** [comment]
It is very easy to add aliases to commands.

However in this case I'd like to retain the `check` name as I could see in the future rclone having a `diff` command which shows differences inside files, like the `diff` command does.

`check` is also consistent with other tools such as `restic`.

Thank you for the suggestion.
