### ISSUE TITLE
Inefficient memory allocations during S3 multipart uploads

### ISSUE THREAD

**Issue by zimnx** [rclone/rclone#3967]
#### What is the problem you are having with rclone?
When uploading big files to S3 storage, memory graphs looks like a rollercoaster. Each upload request allocates his own memory buffers for chunks, and once file is uploaded they are garbaged.
![heap_released_bytes](https://user-images.githubusercontent.com/3951334/74548379-0483a080-4f4e-11ea-8a07-b5af1a139da1.png)
In total allocation space per function graph, we can see that multipart upload allocated 14GB in total throught workflow. This should be constant and equal to number of concurrent requests times chunk size.
![Selection_027](https://user-images.githubusercontent.com/3951334/74548441-2b41d700-4f4e-11ea-8d89-77116c5159f0.png)

#### What is your rclone version (output from `rclone version`)
master

####  Which cloud storage system are you using? (eg Google Drive)
S3

**Comment by ncw** [comment]
Rclone has a library for exactly this purpose: https://github.com/rclone/rclone/blob/master/lib/pool/pool.go

Note that chunk sizes can vary with size of file in S3 so using this would need a bit of care.

Fancy sending in a PR to use `lib/pool` in the s3 backend?

**Comment by zimnx** [comment]
@ncw yep, I'll take care of it soon. Thanks for pool reference!
