### ISSUE TITLE
Commands not working if there is space in filename or Directory name

### ISSUE THREAD

**Issue by rsa2418** [rclone/rclone#3969]
#### What is the problem you are having with rclone?
I was trying to copy files from ruTorrent to my google drive. I followed every step mentioned on Rclone site carefully, but the copy command was failing. I was using command 
rclone copy /home/mydirectory list Gdrive:Foldername. After using this command I was getting error "Command copy needs 2 arguments maximum: you provided 3 non flag arguments". I was totally confused, what could be the reason for this. So tried to rename my directory on local device and eliminating space and it worked like charm.

as you can see there was space in my last folder mydirectory list. 
#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04.6 LTS

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy /mydirectorylist remote:myotherdirectory

**Comment by Yexiaoxing** [comment]
I am assuming your directory is called "mydirectory list", then you need to quote the name like

```
rclone copy "/mydirectory list" remote:myotherdirectory
```

That's how command line works.

**Comment by rsa2418** [comment]
Thanks a ton, friend. That worked like a charm. My bad.
