### ISSUE TITLE
Extend --drive-stop-on-upload-limit to respond to teamDriveFileLimitExceeded

### ISSUE THREAD

**Issue by BinsonBuzz** [rclone/rclone#3979]
#### What is your current rclone version (output from `rclone version`)?
1.51

#### What problem are you are trying to solve?
reclone move/copy/sync not responding to` teamDriveFileLimitExceeded`

#### How do you think rclone should be changed to solve that?
Extend the new --drive-stop-on-upload-limit command to stop jobs if response from Google is `teamDriveFileLimitExceeded`

####### Detail #####################
I stupidly ended up trying to backup lots of small files e.g. plex metadata to my backup mount, which pushed me over the 400k file limit.  My script is now stuck trying to copy the remaining files, even though it can't.

Google is spitting out these error messages:
```
2020/02/18 09:15:29 ERROR : appdata/dockers/plex/Library/Application Support/Plex Media Server/Cache/PhotoTranscoder/04/04863423c1ec2f17a12569fab0348e75d8806e29.jpg: Failed to copy: googleapi: Error 403: The file limit for this shared drive has been exceeded., teamDriveFileLimitExceeded
2020/02/18 09:15:29 ERROR : appdata/dockers/lazylibrarian/cache/XMLCache/7/6/76d5f769b45e3365c7de31e44c4c49f5.xml: Failed to copy: failed to make directory: googleapi: Error 403: The file limit for this shared drive has been exceeded., teamDriveFileLimitExceeded
```

These seem to be the only 2 variations.  I think `--drive-stop-on-upload-limit` could be extended to cover this scenario, as I think it works by looking for certain syntax in Google's responses.

**Comment by ncw** [comment]
That looks like a reasonable request and it has a well defined error `teamDriveFileLimitExceeded` so should be easy to detect.

It would need a bit of extra logic here

https://github.com/rclone/rclone/blob/bde0334bd8e2c16d9fbc49758cd9374f1d741bd2/backend/drive/drive.go#L613-L618

Fancy having a go?

**Comment by BinsonBuzz** [comment]
I had a go, but I'm no coder so I just followed the example blindly:

```
		if len(gerr.Errors) > 0 {
			reason := gerr.Errors[0].Reason
			if reason == "rateLimitExceeded" || reason == "userRateLimitExceeded" {
				if f.opt.StopOnUploadLimit && gerr.Errors[0].Message == "User rate limit exceeded." {
					fs.Errorf(f, "Received upload limit error: %v", err)
					return false, fserrors.FatalError(err)
				}
				return true, err
			}
			if reason == "teamDriveFileLimitExceeded" {
				if f.opt.StopOnUploadLimit && gerr.Errors[0].Message == "Team Drive file limit exceeded." {
					fs.Errorf(f, "Received file limit error: %v", err)
					return false, fserrors.FatalError(err)
				}
				return true, err
			}
		}
```

**Comment by ncw** [comment]
That looks pretty good, I'd change this bit

```go
			if reason == "teamDriveFileLimitExceeded" {
				if f.opt.StopOnUploadLimit && gerr.Errors[0].Message == "Team Drive file limit exceeded." {
					fs.Errorf(f, "Received file limit error: %v", err)
					return false, fserrors.FatalError(err)
				}
				return true, err
			}
```

to

```go
			else if f.opt.StopOnUploadLimit && reason == "teamDriveFileLimitExceeded" {
				fs.Errorf(f, "Received team drive file limit error: %v", err)
				return false, fserrors.FatalError(err)
			}
```

As it isn't necessary to test the error string.

Fancy giving that a test and submitting a pull request?

**Comment by BinsonBuzz** [comment]
I'll give it a go....this is new territory for me as I run rclone using the rclone plugin, so I'll have to work out how to install my own version.

If I want to help test rclone union as well, do I fork this branch?

https://github.com/rclone/rclone/tree/pr-3782-union

**Comment by ncw** [comment]
> I'll give it a go....this is new territory for me as I run rclone using the rclone plugin, so I'll have to work out how to install my own version.

There are some brief instructions on a source install here: https://rclone.org/install/#install-from-source



> If I want to help test rclone union as well, do I fork this branch?
> 
> https://github.com/rclone/rclone/tree/pr-3782-union

Yes that is right

**Comment by Dibbyo456** [comment]
@BinsonBuzz Did you managed to test it? Does it work?

**Comment by BinsonBuzz** [comment]
Sorry no.  I changed the way I do my backup to using chunks now with duplicati, so I'm nowhere near the 400k mark now.

**Comment by ncw** [comment]
Anyone want to pick this up?

**Comment by Dibbyo456** [comment]
I will send a PR tomorrow.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

**Comment by chchia** [comment]
I am wondering, if i upload to a series of Team Drive under Rclone Union (TD1: TD2: TD3: TD4:), and once the TD1: drive hit this error, will it automatic go to next team drive TD2?

**Comment by ncw** [comment]
> once the TD1: drive hit this error, will it automatic go to next team drive TD2?

Not yet, but it should...

**Comment by serialpotato** [comment]
> > once the TD1: drive hit this error, will it automatic go to next team drive TD2?
> 
> Not yet, but it should...

Can you please elaborate further? what do you mean by that?

**Comment by ncw** [comment]
This is https://github.com/rclone/rclone/issues/4734
