### ISSUE TITLE
Stop Checks and Transfer calculation post 750 with option,

### ISSUE THREAD

**Issue by lloydie11sky** [rclone/rclone#3983]
Just a thought to improve the functionality. I had a search around and couldn't see anyone suggesting the same thing, so thought i'd raise it as a FR.

Would it be possible to have an rclone option to prevent rclone continuing calculating the full transfer size until fully synced/copied, and prevent the number of 'checks' if this exceeds the gdrive session limit of 750GB.

I understand there may be cases where this isn't feasible, but a option to turn off this would be great.

For example, i know i have about 8TB on my mounts that are not yet synced, but there is no point calculating this each and every time, and likely increases calls to googledrive for these checks. If i could accept that once it's checked the first 750GB for number of files, and total transfers that it quits going any further.

Does that make sense?

**Comment by darthShadow** [comment]
Probably Related to #3974 and can be closed to only have a single issue. @lloydie11sky Let me know if that issue covers your use-case.

**Comment by lloydie11sky** [comment]
Assuming sync backlog refers to it continuing to check files that either need or need not be synced, or copied, then yes that covers it.

Can you clarify @darthShadow, if so, yes we can close this off.

Thanks,

**Comment by darthShadow** [comment]
Yes, they mean the same.
