### ISSUE TITLE
Yandex client id banned

### ISSUE THREAD

**Issue by serhattsnmz** [rclone/rclone#3989]
#### What is the problem you are having with rclone?

I cannot get token from Yandex disk. 

#### What is your rclone version (output from `rclone version`)

rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Operating System: Ubuntu 18.04.4 
Kernel: Linux 4.15.0-1054-aws
Architecture: x86-64

####  Which cloud storage system are you using? (eg Google Drive)

Yandex Disk

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone config

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

<hr />

![01](https://user-images.githubusercontent.com/20886290/75037566-867f4680-54c5-11ea-8cf4-21ce925386ff.PNG)

<hr />

![02](https://user-images.githubusercontent.com/20886290/75037574-8bdc9100-54c5-11ea-84aa-7f17770d67c7.PNG)

<hr />

**Comment by misuzu** [comment]
Same issue here.

**Comment by delfer** [comment]
Got a message in terminal:

```
Waiting for code...
2020/02/21 16:46:58 Failed to configure token: Error: Auth Error
Code: ""
Description: No code returned by remote server
Help:
```

Web message:

```
Failure!

Error: Auth Error

Description: No code returned by remote server
```

**Comment by buengese** [comment]
It appears yandex has blocked our client_id. Or may it has expired? This needs @ncw

**Comment by delfer** [comment]
@buengese  maybe we can use own client_id?

**Comment by delfer** [comment]
It's still here
![image](https://user-images.githubusercontent.com/3233181/75044024-fdbad780-54d1-11ea-960c-dae6d49bb6d2.png)

**Comment by slalik** [comment]
According to [https://forum.rclone.org/t/yandexdisk-config-problem/14478/5](url) Yandex indeed blocked rclone. Because it "allows to use yandex.disk as infrastructural component". Unbelievable!

**Comment by misuzu** [comment]
Webdav is still working: https://webdav.yandex.ru

**Comment by buengese** [comment]
See [https://forum.rclone.org/t/yandexdisk-problem/14478/8](https://forum.rclone.org/t/yandexdisk-problem/14478/8) for discussion and potential workaround. This problem is not on rclone's side.

**Comment by ncw** [comment]
> It appears yandex has blocked our client_id. Or may it has expired?

I see the same thing in the integration tests. I've emailed them to ask them why and to re-instate the client ID.

**Comment by smopro** [comment]
> Webdav is still working: https://webdav.yandex.ru

webdav also blocked - they force us to use a proprietary client and paid tariffs.

**Comment by kostix** [comment]
> they force us to use <…> paid tariffs.

While I'm also bitten by this very problem, please do not make factually incorrect statements, @smopro: they do indeed force the usage of their clients (of dubious quality: for instance, the Debian packages of the `yandex-disk` CLI client have `libopenssl` statically compiled in, and add random GPG key to the APT keyring at the package installation phase) but they do not in any way force you to use paid plans.

**Comment by smopro** [comment]
> > they force us to use <…> paid tariffs.
> 
> While I'm also bitten by this very problem, please do not make factually incorrect statements, @smopro: they do indeed force the usage of their clients (of dubious quality: for instance, the Debian packages of the `yandex-disk` CLI client ship the main program binary with some version of `libopenssl` statically compiled in, and add their own GPG key to the APT keyring at the package installation phase without telling the user anything) but they do not in any way force you to use paid plans.
> 
> (To be 100% clear, I was already using paid plans via two unrelated accounts; both were used with `rclone` and both have been rendered useless.)

they force us to use not yandex.disk but yandex.cloud AND paid tariffs

**Comment by espindula** [comment]
I "registered" rclone (I suppose that is the proceding for getting my own client id). On the registration page, there was an alert message (in russian language):
"Добавлен доступ, требующий модерации. После сохранения изменений приложение не будет работать до тех пор, пока его не одобрит модератор."
**Google translator:**
"Added access requiring moderation. After saving the changes, the application will not work until it is approved by the moderator."

**Comment by espindula** [comment]
> I "registered" rclone (I suppose that is the proceding for getting my own client id). On the registration page, there was an alert message (in russian language):
> "Добавлен доступ, требующий модерации. После сохранения изменений приложение не будет работать до тех пор, пока его не одобрит модератор."
> **Google translator:**
> "Added access requiring moderation. After saving the changes, the application will not work until it is approved by the moderator."

Therefore, if I understand correctly, "registering" rclone on the OAuth server will have no effect, as this application is subject to moderation and approval.

**Comment by delfer** [comment]
I've made 3 requests for OAuth key, 2 for rclone and 1 for imagined application, they **all was rejected**.
**webdav** was hard limited: rejects some kind of files and hangs on files over 20Mb.

**Comment by delfer** [comment]
https://oauth.yandex.com/client/new
![image](https://user-images.githubusercontent.com/3233181/75109678-a3875700-5636-11ea-97bb-9d88048f9efa.png)
**How to fill this fields? Is it Web service or not? Should I set Callback URI?**

**Comment by smopro** [comment]
> https://oauth.yandex.com/client/new
> ![image](https://user-images.githubusercontent.com/3233181/75109678-a3875700-5636-11ea-97bb-9d88048f9efa.png)
> **How to fill this fields? Is it Web service or not? Should I set Callback URI?**

You can write only '*' marked fields

**Comment by ncw** [comment]
Web service: YES
Callback URI: http://127.0.0.1:53682/
Scopes:
- Yandex.Disk REST API
    - Writing in any place on Yandex.Disk
    - Read all of Yandex.Disk
    - Access to information about Yandex.Disk
    - Access to app folder in Yandex.Disk

**Comment by delfer** [comment]
We need ability to set the custom port (53682) and User-Agent.

**Comment by delfer** [comment]
@ncw thank you very much! With these properties my request Passed moderation.

**Comment by ncw** [comment]
> We need ability to set the custom port (53682) and User-Agent.

We have `--user-agent` already. I would consider a PR for setting a custom port.

**Comment by delfer** [comment]
Today I've checked again and now Yandex works with old rcloneClientID `ac39b43b9eba4cae8ffb788c06d816a8`

**Comment by ncw** [comment]
It looks like Yandex have reconsidered banning rclone. The built in oauth client_id seems to be working again :-)

**Comment by musinsky** [comment]
Yah, working ...
```
2020/02/27 18:51:50 Automatically upgraded OAuth config.
```

**Comment by buengese** [comment]
Closing this now that Yandex has unbanned our client id. Please report back if the situation changes again.
