### ISSUE TITLE
Failed to configure token: failed to get token

### ISSUE THREAD

**Issue by Loverush** [rclone/rclone#3992]
#### What is the problem you are having with rclone?
I cannot complete the config

#### What is your rclone version (output from `rclone version`)
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 18.04

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone config

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

...
Edit advanced config? (y/n)
y) Yes
n) No (default)
y/n> n
Remote config
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes (default)
n) No
y/n> n
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth?state=SbjBx2rIhU76YhObf9lJ9g
Log in and authorize rclone for access
Waiting for code...
Got code
2020/02/22 11:49:56 Failed to configure token: failed to get token: Post https://oauth2.googleapis.com/token: read tcp 10.128.136.147:60658->172.217.27.138:443: read: connection reset by peer

**Comment by Loverush** [comment]
And for onedrive:
...
Remote config
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes (default)
n) No
y/n> n
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth?state=7t2gzatM3GVn-Of6FApjaQ
Log in and authorize rclone for access
Waiting for code...
2020/02/22 12:01:17 Failed to configure token: Error: Auth Error
Code: ""
Description: No code returned by remote server
Help:

**Comment by animosity22** [comment]
If you could please post questions on the forums, we can help out easier as more people can respond. The github is more for issues rather than use case questions. 

https://forum.rclone.org/

Thanks!
