### ISSUE TITLE
Rclone Cache folder not working - cant find the cache

### ISSUE THREAD

**Issue by Friday13th87** [rclone/rclone#3993]
rclone version: v1.51.0 linux/amd64
distribution: debian buster stable 4.19.0-8-amd64

I am using rclone on my small server and on my desktop pc (both running the same debian) and especially on my server i dont like to have any writes on my small ssd so i tried to put all the cache on the RAM.

i am mounting my gdrive with a systemd service:
[Unit]
Description=GDrive
After=network-online.target
[Service]
Type=notify
User=server
Group=users
ExecStart=/usr/bin/rclone mount \
	--allow-other \
        --umask 002 \
	--log-level INFO \
	--log-file /rclone_cache/gdrive.log \
	--buffer-size 256M \
	--poll-interval 15s \
        --cache-dir /rclone_cache \
        --cache-tmp-upload-path /rclone_cache \
        --cache-chunk-path /rclone_cache \
        --cache-db-path /rclone_cache \
        --dir-cache-time 8760h \
        --allow-non-empty \
        --vfs-read-chunk-size 128M \
        --vfs-read-chunk-size-limit 2G \
        --attr-timeout 8700h \
	--vfs-cache-mode writes gdrive: /media/gdrive
ExecStop=/bin/fusermount -uz /media/gdrive
Restart=always
RestartSec=10
[Install]
WantedBy=default.target

and i am mounting rclone_cache as a tmpfs with a max of 32GB in my fstab and 0775 permission (working ofc)

if i am caching my directories now (with for example "tree /media/gdrive") or start streaming a video file, editing etc. my "rclone_cache" folder still is empty (only the log file is there)
(streaming is working good btw)

i tried the same thing with different (already created) folders for each mount entry
(so /rclone_cache/db for db, /rclone_cache/chunk/ for chunk ...) with the same result

the ~/.cache/rclone folder is not existing at all.

so what am i doing wrong, for what are those flags and where is the cache placed instead?

**Comment by Friday13th87** [comment]
i read now, that rclone is not caching at the disk at all while streaming files as long as vfs-cache-mode is not set to "full"
but where is the file/directory cache saved then? is it in the RAM anyway?

i changed my mount setup to that:
ExecStart=/usr/bin/rclone mount \
	--allow-other \
	--buffer-size 256M \
        --dir-cache-time 1000h \
	--log-level INFO \
	--log-file /rclone_cache/gdrive.log \
	--poll-interval 15s \
	--timeout 1h \
        --umask 002 \
	--user-agent main \
	--rc \
	--rc-addr 127.0.0.1:5572\
        --cache-dir /rclone_cache \
        --vfs-read-chunk-size 128M \
        --vfs-read-chunk-size-limit 2G \
	--vfs-cache-mode writes gdrive: /media/gdrive


as far as i understood it, the vfs-read-chunk stuff and cache folder is not used if i am only steaming, only if i am doping other stuff - so it has no influence in the streaming proces if i leave it inside the mount, correct?

**Comment by animosity22** [comment]
It's best to post questions like this in the forums rather than raising an issue.

There are two separate cache items in rclone.

The standard VFS caching is here:

https://rclone.org/commands/rclone_mount/#file-caching

It's documented on what flags do what and the cache-dir is where files are written if you use anything above off.

Other than that, there is no writing of files to disk or anything else as it's all done in memory. Streaming or anything else doesn't matter as it's just the vfs-cache-mode setting that is used.

**Comment by animosity22** [comment]
This looks like I answered it and if you still have a question, please ask on the forums and we're happy to help out.
