### ISSUE TITLE
Sync s3 to s3 path erases source files

### ISSUE THREAD

**Issue by loquanet** [rclone/rclone#3995]
#### What is the problem you are having with rclone?

3 issues or bugs:
1) Rclone sync s3:source s3:dest... Same bucket. 
All my files in source were deleted!
No new files to destination were created. 

2) rclone moveto doesn't move anything 
3) rclone move doesn't move anything 

#### What is your rclone version (output from `rclone version`)

Latest just downloaded last week. 

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Centos 7 latest x64

####  Which cloud storage system are you using? (eg Google Drive)

Wasabi (s3 api) 

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

1) Rclone sync s3buck:source s3buck:dest --verbose

2) Rclone moveto s3buck:source s3buck:dest --verbose

3) Rclone move s3buck:source s3buck:dest --verbose

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I didn't used the vv flag. The files are gone and I already deleted the folders.

**Comment by animosity22** [comment]
Can you put some files in the source and run the command and share the -vv output? 

A sync won't delete the source.

**Comment by loquanet** [comment]
Sure will do today.

**Comment by animosity22** [comment]
Any updates or is this stale?

**Comment by animosity22** [comment]
If you need help, you can post to https://forums.rclone.org and we are happy to help out.

**Comment by loquanet** [comment]
I've been swamped with work and solar projects for vans. Try doing this
with wasabi storage and you'll see the issue. Huge bug. Not sure if you
fixed it by now.

**Comment by ncw** [comment]
> 1. Rclone sync s3:source s3:dest... Same bucket.
>    All my files in source were deleted!
>    No new files to destination were created.

What do you mean same bucket? If you sync to the same bucket you should get this error

```
$ rclone sync -v s3:rclone-dst s3:rclone-dst
2020/05/18 20:13:18 Failed to sync: can't sync or move files on overlapping remotes
```

**Comment by loquanet** [comment]
That's not what occurred. Same bucket it deleted the source folder contents
on attempting to sync.

Luckily I had a copy of files or I would be destroyed and beyond pissed.

**Comment by animosity22** [comment]
Again, if you have some logs or want to pursue further, we're happy to help out as we can't recreate it.

Feel free to post on the forums and we can help.

**Comment by loquanet** [comment]
Where would logs be located? It's old but I didn't delete anything

**Comment by animosity22** [comment]
If you didn't specify a log file, it would be only on the screen. You have to use --log-file /tmp/something.log

Without anyway to recreate something or something to look, there isn't much to do unfortunately.
