### ISSUE TITLE
Use AWS_REGION (or AWS_DEFAULT_REGION) if S3 region is not specified in config

### ISSUE THREAD

**Issue by tgyurci** [rclone/rclone#4001]
It would be useful, if the AWS region is not set in config, then the region will be read from `AWS_REGION`, or `AWS_DEFAULT_REGION` env var, if that's specified.  Or with an additional `env_region` config setting.

 It's supported by the AWS SDK, only the client needs to be configured so.

**Comment by ncw** [comment]
If you want rclone to read AWS config from the environment then you need to set `env_auth = true` in the config, or supply the --s3-env-auth flag. If you do that, it should work.

**Comment by tgyurci** [comment]
Reading access key and secret key from the environment works with `env_auth = true`, I want to get the region from the environment too (which is not working right now).

**Comment by ncw** [comment]
> Reading access key and secret key from the environment works with `env_auth = true`, but I want to get the region from the environment too (which is not working right now).

rclone uses the AWS S3 SDK to read env vars so it will be [whatever it supports](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/)

According to a comment in the code

> AWS_DEFAULT_REGION is only read if AWS_SDK_LOAD_CONFIG is also set

You can also make a profile file

**Comment by tgyurci** [comment]
> > Reading access key and secret key from the environment works with `env_auth = true`, but I want to get the region from the environment too (which is not working right now).
> 
> rclone uses the AWS S3 SDK to read env vars so it will be [whatever it supports](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/)

AWS SDK gets region from env only when it's not configured explicitly, but
a default value is set for region at https://github.com/rclone/rclone/blob/master/backend/s3/s3.go#L1089
Commenting out that `if` solves the issue, but I'm not sure that it doesn't make something else wrong.

> According to a comment in the code
> 
> > AWS_DEFAULT_REGION is only read if AWS_SDK_LOAD_CONFIG is also set
> 
> You can also make a profile file

The AWS_DEFAULT_REGION is used regardless of the AWS_SDK_LOAD_CONFIG, according to this: https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html

**Comment by ncw** [comment]
> AWS SDK gets region from env only when it's not configured explicitly, but
> a default value is set for region at https://github.com/rclone/rclone/blob/master/backend/s3/s3.go#L1089
> Commenting out that `if` solves the issue, but I'm not sure that it doesn't make something else wrong.

Ah, I see what you mean. Changing that default is very likely to break existing config.

How about this? Only set a default region if we are not using `env_auth`

```go
if !opt.EnvAuth && opt.Region == "" {
	opt.Region = "us-east-1"
}
```

Thoughts?

**Comment by tgyurci** [comment]
> How about this? Only set a default region if we are not using `env_auth`
> 
> ```go
> if !opt.EnvAuth && opt.Region == "" {
> 	opt.Region = "us-east-1"
> }
> ```
> 
> Thoughts?

This way the `env_auth` will mean `env_auth_and_region`.  A separate `env_region` boolean option will be more expressive, but this complicates configuration with an additional option.  Ideally `env_auth` (and `env_region`) shouldn't exist, the environment variables should be used automatically when the options are absent from config file (or command line).

And I guess the implicit endpoint setting should be rethought at: https://github.com/rclone/rclone/blob/master/backend/s3/s3.go#L1086

**Comment by ncw** [comment]
I don't think this is an issue any more, but if it is, I will re-open.
