### ISSUE TITLE
Max-duration not working as intended with B2

### ISSUE THREAD

**Issue by allobrogica** [rclone/rclone#4002]
#### What is the problem you are having with rclone?

When working with a B2 remote, the max-duration does not allow existing transfers to complete and instead rclone continues running in a retry mode with deadline exceeded. The transfers do stop but mid-transfer. Rclone never exits. This is not the intended behavior of max-duration. When the option is tested against sftp for example, rclone does exit once the duration is met. So something is wrong with how it handles B2 transfers. 
The behavior is easily reproducible. 

See also: https://forum.rclone.org/t/max-duration-not-working-as-intended-with-b2/14534

#### What is your rclone version (output from `rclone version`)
1.51

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Tested on mac and ARM. 

####  Which cloud storage system are you using? (eg Google Drive)
B2

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
see below

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

-----------------------
> 2020/02/24 20:04:25 DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "-vv" "--log-file=maxdurb2" "--max-duration=20s" "copy" "uptestdir" "B2REMOTE:/tmp/uptestdir"]
> 2020/02/24 20:04:25 DEBUG : Using config file from "rclone.conf"
> 2020/02/24 20:04:28 INFO  : B2 bucket BUCKET path tmp/uptestdir: Transfer session deadline: 2020/02/24 20:04:48
> 2020/02/24 20:04:28 INFO  : B2 bucket BUCKET path tmp/uptestdir: Waiting for checks to finish
> 2020/02/24 20:04:28 INFO  : B2 bucket BUCKET path tmp/uptestdir: Waiting for transfers to finish
> 2020/02/24 20:04:29 DEBUG : mediumfile1-220M: Starting upload of large file in 3 chunks (id "<cut>")
> 2020/02/24 20:04:29 DEBUG : mediumfile1-220M: Sending chunk 1 length 100663296
> 2020/02/24 20:04:29 DEBUG : mediumfile2-220M: Starting upload of large file in 3 chunks (id "<cut>")
> 2020/02/24 20:04:29 DEBUG : mediumfile1-220M: Sending chunk 2 length 100663296
> 2020/02/24 20:04:29 DEBUG : mediumfile2-220M: Sending chunk 1 length 100663296
> 2020/02/24 20:04:29 DEBUG : mediumfile1-220M: Sending chunk 3 length 28393644
> 2020/02/24 20:04:42 DEBUG : file2-20M: SHA-1 = 746a1ca24c6f49e971222a35cb3fb7bb3d1e25f0 OK
> 2020/02/24 20:04:42 INFO  : file2-20M: Copied (new)
> 2020/02/24 20:04:42 DEBUG : file1-20M: SHA-1 = e097386b63ff70335830b74e88d76368ccd483d5 OK
> 2020/02/24 20:04:42 INFO  : file1-20M: Copied (new)
> 2020/02/24 20:04:43 DEBUG : mediumfile3-220M: Starting upload of large file in 3 chunks (id "<cut>")
> 2020/02/24 20:04:47 DEBUG : mediumfile1-220M: Done sending chunk 3
> 2020/02/24 20:04:47 DEBUG : mediumfile2-220M: Sending chunk 2 length 100663296
> 2020/02/24 20:04:48 DEBUG : upsplitac: Clearing upload URL because of error: Post https://pod-000-1041-07.backblaze.com/b2api/v1/b2_upload_file/<cut>: context deadline exceeded
> 2020/02/24 20:04:48 DEBUG : mediumfile1-220M: Error sending chunk 2 (retry=true): Post https://pod-000-1120-11.backblaze.com/b2api/v1/b2_upload_part/<cut>: context deadline exceeded: &url.Error{Op:"Post", URL:"https://pod-000-1120-11.backblaze.com/b2api/v1/b2_upload_part/<cut>", Err:context.deadlineExceededError{}}
> 2020/02/24 20:04:48 DEBUG : mediumfile1-220M: Clearing part upload URL because of error: Post https://pod-000-1120-11.backblaze.com/b2api/v1/b2_upload_part/<cut>: context deadline exceeded
> 2020/02/24 20:04:48 DEBUG : pacer: low level retry 1/10 (error Post https://pod-000-1120-11.backblaze.com/b2api/v1/b2_upload_part/<cut>: context deadline exceeded)
> <snip, lots of same errors>
> 2020/02/24 20:04:50 DEBUG : upsplitac: Clearing upload URL because of error: Post https://pod-000-1128-17.backblaze.com/b2api/v1/b2_upload_file/<cut>: context deadline exceeded
> 2020/02/24 20:04:50 DEBUG : pacer: low level retry 1/1 (error Post https://pod-000-1128-17.backblaze.com/b2api/v1/b2_upload_file/<cut>: context deadline exceeded)
> 2020/02/24 20:04:50 DEBUG : pacer: Rate limited, increasing sleep to 1.28s
> 2020/02/24 20:04:50 DEBUG : upsplitac: Received error: Post https://pod-000-1128-17.backblaze.com/b2api/v1/b2_upload_file/<cut>: context deadline exceeded - low level retry 2/10
> 2020/02/24 20:04:51 DEBUG : pacer: low level retry 1/10 (error Post https://api001.backblazeb2.com/b2api/v1/b2_get_upload_part_url: context deadline exceeded)
> 2020/02/24 20:04:51 DEBUG : pacer: Rate limited, increasing sleep to 2.56s
> 2020/02/24 20:04:52 DEBUG : pacer: low level retry 1/10 (error Post https://api001.backblazeb2.com/b2api/v1/b2_get_upload_part_url: context deadline exceeded)
> <snip, lots of same erorrs>
> 2020/02/24 20:10:17 DEBUG : pacer: low level retry 3/10 (error Post https://api001.backblazeb2.com/b2api/v1/b2_get_upload_url: context deadline exceeded)
> 2020/02/24 20:10:28 INFO  : 
> Transferred:   	  168.199M / 888.122 MBytes, 19%, 478.774 kBytes/s, ETA 25m39s
> Transferred:            2 / 14, 14%
> Elapsed time:      5m59.7s
> Transferring:
>                                       upsplitac:  0% /20M, 0/s, -
>                                mediumfile1-220M: 43% /219.078M, 0/s, 2069405h28m37.161793536s
>                                mediumfile2-220M:  9% /219.078M, 0/s, 0s
>                                mediumfile3-220M:  0% /219.078M, 0/s, -
> 
> 2020/02/24 20:11:28 INFO  : 
> Transferred:   	  168.199M / 888.122 MBytes, 19%, 410.336 kBytes/s, ETA 29m56s
> Transferred:            2 / 14, 14%
> Elapsed time:      6m59.7s
> Transferring:
>                                       upsplitac:  0% /20M, 0/s, -
>                                mediumfile1-220M: 43% /219.078M, 0/s, 0s
>                                mediumfile2-220M:  9% /219.078M, 0/s, 0s
>                                mediumfile3-220M:  0% /219.078M, 0/s, -
>  (manually terminated rclone)

**Comment by ncw** [comment]
Yes, this looks like a bug... Well two bugs actually!

1. the `--max-duration` flag doesn't work like it is documented to
2. b2 shouldn't be retrying deadline exceeded errors.

It looks like I've got the context's muddled up in the sync routine or at least I need to be a lot more careful which context is used where!

**Comment by abhishekjain14** [comment]
I've seen the same behavior occurring with a Google drive encrypted remote, so it's not just b2

**Comment by Friday13th87** [comment]
and i am having the same issue on google drive move (not encrypted).
Speed goes to zero after reaching the max time and is not finishing

**Comment by ncw** [comment]
This issue should be fixed in the v1.55 release.

If not, please open a new issue with logs - thanks!

**Comment by grizzlybassist** [comment]
Just added --max-duration to my nightly backup and am getting the same error on version 1.57
`#rclone --version
rclone v1.57.0
- os/version: slackware 14.2+ (64 bit)
- os/kernel: 5.10.28-Unraid (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.2
- go/linking: static
- go/tags: none`
`2021/12/21 13:02:04 ERROR : Attempt 3/20 failed with 4 errors and: Post "https://pod-000-1105-18.backblaze.com/b2api/v1/b2_upload_part/4_zdb4788eb8398abd751c80811_f2111a6ee848295a2_d20211221_m150330_c001_v0001105_t0040/0045": context deadline exceeded`
