### ISSUE TITLE
rclone filled almost all free space on local disk

### ISSUE THREAD

**Issue by b0ogdan** [rclone/rclone#4012]
Hi guys. I am new to rclone.
I subscribed to a gsuite account to backup some stuff for myself.
Reading on what is the best option to backup big amounts of data to google drive from MacOS i came across Rclone. I installed it and uses the default steps form the website guide but i am facing a big issue and i cannot find the answer...I read some post here but still in my case i could not find the solution.
My problem is happening now on a second different computer.
Both computers have the system installed on an 512 SSD with Mojave installed on a apfs partition.
Everything installed on both computers is roughly 100gb. After i did synced some big folders to my google drive i noticed that my divers were almost full ( on both systems it shows me 60gb free disk space) .

How can i reclaim the space back and how i can prevent this in the future?
From what i understand rclone is making some caches? But where and how?
I scanned the drives with disk utils and other app and cannot find anything on the drive? No huge folder nothing...even from recovery mode. in user/.config/rclone i don`t have any folder just a .conf file.

Please help...Already on one of the computers because i needed to get work done i cloned the system to a different ssd , did a format and put the system back on but i want to avoid doing this again on the second computer and in the future.

Thank you guys in advance and sorry if somewhere this was answered already ...I could not find the topic and the small bits i found did not help me.

What is the problem you are having with rclone?
ALMOST all disk space is filled after rclone operation but no large file on hdd.
What is your rclone version (output from rclone version)
rclone v1.51.0
os/arch: darwin/amd64
go version: go1.13.7
Which OS you are using and how many bits (eg Windows 7, 64 bit)
MacOS Mojave
Which cloud storage system are you using? (eg Google Drive)
Google Drive

**Comment by darthShadow** [comment]
Please specify all the details required in the issue template.

**Comment by ncw** [comment]
This is being discussed in the forum here: https://forum.rclone.org/t/newbie-help-needed-urgently/14586

So I'll close this issue
