### ISSUE TITLE
Incorrect sizes reported with rclone size

### ISSUE THREAD

**Issue by ferferga** [rclone/rclone#4013]
#### What is the problem you are having with rclone?

``rclone size`` command is reporting an incorrect size in the Google Drive backend. It's reporting nearly 1 TB more than what I got really.

This is the output of the command between **1.51** and **1.50.2** (the last version without issues). The rclone binary that's in my path is **1.51** and the one in the folder I'm located is **1.50.2**:

![Sin título](https://user-images.githubusercontent.com/10274099/75447207-342ca280-5969-11ea-9c54-c99dd700f071.png)

**1.51** reports nearly 1 TB +. However, with the remote also mounted with **1.51**, running a **ncdu** or **du -sch** command reports the correct size:
![Sin título](https://user-images.githubusercontent.com/10274099/75447550-e4021000-5969-11ea-9a21-6e1bf4fb1162.png)
![Sin título](https://user-images.githubusercontent.com/10274099/75447664-190e6280-596a-11ea-8559-e41daa667b7f.png)

So it seems that there is a problem with the logic of the size of the backend introduced in **1.51**, as **1.50** reported the sizes accurately.

#### What is your rclone version (output from `rclone version`)

I reproduced this in 1.51 and **latest beta (rclone v1.51.0-054-gda5cbc19-beta)**. Older versions worked fine. **1.50.2** was the latest version to work without issues, so the issue was introduced in **1.51**.

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Tests conducted in Windows 10 AMD64 and Raspberry Pi 3B+ (armhf). Tests with betas and older versions (until I found which one introduced the issue) were done in the Windows machine

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive. It's completely unknown to me if this issue is happening in other remotes.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

``rclone size GoogleDriveBackend:``

**Comment by ncw** [comment]
Can you try adding `--disable ListR` to your `rclone size` command and see if you get the same answer?

Is this a shared drive?

Might it have duplicates? Can you check with `rclone dedupe`?

Can you do

```
rclone-v1.50 lsf -R drive: | sort > old
rclone-v1.51 lsf -R drive: | sort > new
comm -13 old new > extra
```

and examine the extra file to see what the extra files are

**Comment by ferferga** [comment]
@ncw Sorry for taking so long to answer. I've lost some of the files after doing ``rclone dedupe`` (because they were in "My Computer" zone added to "My Drive", so files deleted in one place are also deleted in the other). It was my fault for no having a backup for all of them and also because the remote was not read only, but it would be great if, by default, you make ``dedupe`` not delete duplicates, just list them and ask for confirmation. 

I suppose though that the fact that there were duplicates (which in reality weren't duplicates, just links between "My Drive" and "My Computers") shouldn't matter the size, though, as the remote I'm running ``size`` against is the root of "My Drive", so "My Computers" shouldn't be handled by rclone at all.

I'm still restoring/finding the backup of some of my files, so will leave this on hold for a while until I figure some things out. Whenever I can I will post you the results of the other commands you requested.

**Comment by ncw** [comment]
> I've lost some of the files after doing `rclone dedupe` (because they were in "My Computer" zone added to "My Drive", so files deleted in one place are also deleted in the other).

I'm sorry to hear that.

Are these files effectively hard links then? In the same directory? How did that happen?

Maybe I should test if the files have the same ID before and don't delete them if they do.

Or alternatively I should be unlinking them from the directory instead: See #3998 for similar issue.

> but it would be great if, by default, you make dedupe not delete duplicates, just list them and ask for confirmation.

At the moment it prompts for most things but it doesn't prompt for identical files (with the same checksum) in the same directory :-(

**Comment by ferferga** [comment]
@ncw The files I lost were all added to "My Drive" from "My Computers", with "My Computer" holding the files backed up by Backup & Sync.

Probably the ID thing should solve this. Cool to see then that this might have a positive effect in rclone and it won't be for nothing :)

**Comment by 3xploiton3** [comment]
same issue on me, tested in shared drive (team drive)

bot & bot1 have same access but use different account

![image](https://user-images.githubusercontent.com/19517680/76370931-16007280-636b-11ea-9bdd-191c9de2f8c7.png)

**Comment by darthShadow** [comment]
Try with the `--disable ListR` argument to rclone and see if the sizes match then.

**Comment by ncw** [comment]
Also try with [the latest beta](https://beta.rclone.org) where I fixed an issue with --drive-shared-with-me if you are using that?

**Comment by ncw** [comment]
@ferferga 
> Probably the ID thing should solve this. Cool to see then that this might have a positive effect in rclone and it won't be for nothing :)

I've written some code to attempt to fix this. I'm having trouble getting the problem to appear though - you can't do it through the normal google drive site - when you move the duplicate into the target folder you only get one and the duplicate disappears.

Unfortunately being on Linux I can't use the google drive sync to test what you are doing.

I could send you a binary to test - would that be OK?

**Comment by 3xploiton3** [comment]
> Try with the `--disable ListR` argument to rclone and see if the sizes match then.

this command not showing anything
```
rclone size bot: --disable ListR       
or 
rclone size --disable ListR bot:        
```

**Comment by darthShadow** [comment]
No output at all? Can you see what adding `-vv` shows?

**Comment by 3xploiton3** [comment]
> No output at all? Can you see what adding `-vv` shows?

sorry, after a few hours i leave my computer, 

```
Total objects: 365584
Total size: 164.762 TBytes (181158069896745 Bytes)
```

thx for suggestion,

**Comment by ferferga** [comment]
@ncw Ooops, thought that I replied before! Yes, of course! Do you want me to test the dedupe thing exclusively, right? I'm copying everything to a new account and starting from scratch, so I will be able to test it in the same environment (or at least, in one 99% similar to it) that caused the removal of the items.

I'm still figuring out a lot of stuff from my collection, so I don't have any news about the size thing yet. Will update you here once it's done.

**Comment by ncw** [comment]
@ferferga 
> Ooops, thought that I replied back! Yes, of course! Do you want me to test the dedupe thing exclusively, right?

Yes please.

> I'm copying everything to a new account and starting from scratch, so I will be able to test it in the same environment (or at least, in one 99% similar to it) that caused the removal of the items.

Thank you

> I'm still figuring out a lot of stuff from my collection, so I don't have any news about the size thing yet. Will update you here once it's done.

I'm pretty sure the size thing is fixed now, but more testing always appreciated!

**Comment by ferferga** [comment]
@ncw I should test in latest beta, right?

**Comment by ncw** [comment]
@ferferga can you test this beta?

https://beta.rclone.org/branch/v1.51.0-119-g9fd8418b-fix-4013-dedupe-beta/ (uploaded in 15-30 mins)

**Comment by ferferga** [comment]
@ncw Sure! Will do once I have everything copied over to my new Google Drive account. Should take 1-2 days with my connection.

Thanks!

**Comment by ferferga** [comment]
@ncw So I finally have all my files sorted out and, luckily, I'm able to reproduce the exact same situation.

Running ``rclone dedupe --dry-run GoogleDrive:`` in 1.51.0 effectively returns the same files that were deleted the first time. Using your beta, however, returns no results. I tested adding a duplicate one in purpose and it did, so it seems that everything is correct if you also check the ID of the file! Thanks!

Now, coming back to ``rclone size``. My OS reports that my mounted remote is ``3.7 TB`` in size. ``stable`` reports 4.752TB (with 5711 objects), while ``fix-4013-dedupe-beta`` reports ``3.681TB`` (with 5511 objects), so everything seems correct in the beta.
For further checking, I tried ``rclone ncdu`` both in stable and in your beta, and (strange, yes), both stable and beta there reports ``3.681TB`` (and the same amount of objects, 5511), so it seems that the problem was only present in stable with size.

So, if all the commits made into the ``fix-4013-dedupe-beta`` made its way into the next stable version, everything is correct and solved!

Closing this. Thank you very much again for your help and patience!

**Comment by ncw** [comment]
@ferferga thanks for testing. I found the exact cause of the bug eventually and it was fixed (unintentionally) by dfc7215bf9b7840f438d006bf7b399974f5ebf42 which is in the current beta. The bug was causing duplicates of files with multiple parents to appear which would also have affected `rclone size`.

I don't think I need to merge the fix in `fix-4013-dedupe-beta` as it only kicks in when files have the same name and the same ID in the same directory which isn't possible for google drive. I could merge it anyway as it is extra checks - what do you think?

Can you try your tests with plain [the latest beta](https://beta.rclone.org) which does not have `fix-4013-dedupe-beta` code in and double check it is OK for you?

**Comment by ferferga** [comment]
@ncw You're right: It seems that the dedupe problem was caused because my files had multiple parents. So it's solved without merging that specific commit.

However, I'm not that against merging it. Basically because it's a great safeguard for unintended bugs like the one I suffered (which was completely unrelated to dedupe) and it shouldn't be expensive to check (afaik, Google returns the MD5, name and doc_id in the same request, so no additional requests should be made iirc). If it's expensive or complicates the logic too much, forget it. It's a good check to have, as Drive usually borks many things, but it's something that might be true in some edge cases - or maybe never.

**Comment by ncw** [comment]
@ferferga OK I reworked the test after working out it didn't work for docs and I've merged that. I've also merged a fix where rclone refuses to delete multiply linked files as doing so is very likely to cause data loss. This would have stopped this problem too.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

**Comment by ferferga** [comment]
Those commits looks great, even more now than Drive is now using shortcuts. They will help a lot at easing the transition! Thank you very much @ncw!

**Comment by 0xbkt** [comment]
Can somebody explain what actually does `--disable ListR` do?

**Comment by ferferga** [comment]
@0xbkt Here you have more info: https://rclone.org/overview/#features

Are you sure that you're running the latest version?

**Comment by 0xbkt** [comment]
@ferferga Thank you, I have just upgraded from `1.52.1` to `1.52.2` and it's working correctly now.
