### ISSUE TITLE
ncdu mode dies and fails when it doesn't have permission to access a remote subdirectory

### ISSUE THREAD

**Issue by ruphy** [rclone/rclone#4014]
#### What is the problem you are having with rclone?

when `rclone ncdu` can't access a subpath of a given remote, it fails and quits and provides no way to skip/ignore the directory in question, thus making it completely useless on the whole remote.

For example, suppose I have a shell where I log in as 'me', and where 'user2' has unique acess to her own subdirectory.

The filesystem looks like this:
```
$ ssh me@sftphost  ls -l
total 240
drwx------   10 19463  user2  10 Feb  3 10:08 user2
drwx------   3 19463  me   9 Feb 27 03:30 dir1
drwx------   3 19463  me   9 Feb 27 13:33 dir2
drwx------   3 19463  me   9 Feb 27 04:35 dir3
```

(sftphost is an sftp remote where i connect as user 'me')
```
$ rclone ncdu sftphost:
2020/02/27 18:25:57 Failed to ncdu with 4 errors: last error was: ncdu directory listing: ncdu listing failed: error listing "user2": sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)
$
```

#### What is your rclone version (output from `rclone version`)

```
rclone v1.49.1
- os/arch: linux/amd64
- go version: go1.12.9
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu LTS

####  Which cloud storage system are you using? (eg Google Drive)

SFTP

**Comment by ncw** [comment]
Can you try this with [the latest release](https://rclone.org/downloads/)? I think this might be fixed. It will give errors which will mess up the display but CTRL-L should refresh the display

**Comment by ruphy** [comment]
same error with:

```
$ rclone --version      
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7
```


I get the usual `sftp: "Permission denied" (SSH_FX_PERMISSION_DENIED)`
(by the way, I really think this is a bug, not an enhancement)

**Comment by ruphy** [comment]
@ncw I took the liberty of modifying the title and the description, let me know if it's better now!

I also just tried to reproduce this error with the local filesystem:
```
mkdir dir1 dir1/a dir1/b dir1/c
sudo chown root dir1/a
sudo chmod 600 dir1/a
```
but in this case I get a working interface, and I receive simply the report of a debug message once I quit `rclone`:
```2020/03/03 12:04:35 Failed to ncdu: failed to open directory "a": open /home/ruphy/LocalOnly/tt/dir1/a: permission denied```

so it really looks like it's the SFTP backend which is the culprit here!

**Comment by ncw** [comment]
I think what is required is to fix this FIXME

https://github.com/rclone/rclone/blob/4d8d1e287ba394d486bd1f7616ddb26fa4b79c89/cmd/ncdu/scan/scan.go#L172

Or maybe do something different here

https://github.com/rclone/rclone/blob/4d8d1e287ba394d486bd1f7616ddb26fa4b79c89/cmd/ncdu/ncdu.go#L690-L693

Fancy having a go at this @ruphy ?

I note that there is a special workaround in the local backend which was implemented here: 9c6f3ae82c0e03acdf961ed7ebafbf2a1c5f72b0 - this reports errors via the error variable but doesn't return them. The SFTP backend could potentially do the same thing. It might be better to check for `os.IsPermission(err)` in the FIXME code though.

**Comment by ruphy** [comment]
thanks @ncw and @ivandeex ! :tada:

**Comment by ivandeex** [comment]
thanks @rockdreamer !
