### ISSUE TITLE
Time may be set wrong - random times?

### ISSUE THREAD

**Issue by acsfer** [rclone/rclone#4016]
```
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7
```
Command

`/usr/bin/run-one /usr/bin/nice -n 19 /usr/bin/rclone move 1fichier:Data wasabi:Data`

Output
```

2020/02/28 12:00:29 NOTICE: Time may be set wrong - time from "a-34.1fichier.com" is -11m31.960380986s different from this computer
2020/02/28 12:00:29 NOTICE: Time may be set wrong - time from "a-33.1fichier.com" is 27m24.378498828s different from this computer
2020/02/28 12:02:48 NOTICE: Time may be set wrong - time from "a-8.1fichier.com" is 12m42.75588028s different from this computer
2020/02/28 12:03:15 NOTICE: Time may be set wrong - time from "a-10.1fichier.com" is 33m2.391450655s different from this computer
2020/02/28 12:03:22 NOTICE: Time may be set wrong - time from "a-13.1fichier.com" is 26m47.790932963s different from this computer
2020/02/28 12:03:47 NOTICE: Time may be set wrong - time from "a-11.1fichier.com" is 35m6.075839753s different from this computer
2020/02/28 12:03:48 NOTICE: Time may be set wrong - time from "a-12.1fichier.com" is 12m23.058900712s different from this computer
2020/02/28 12:04:32 NOTICE: Time may be set wrong - time from "a-37.1fichier.com" is 20m53.847439761s different from this computer
```
The problem here is that the gap is random, note the 1st and second lines. I believe that this is because `1fichier` download the same file from different servers at the same time?

**Comment by ncw** [comment]
Rclone reads the time from the server in the [Date: header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date).

> The Date general HTTP header contains the date and time at which the message was originated.

So I suspect that either

- the time is wrong on those servers
- 1fichier is doing something strange with the `Date` header...

**Comment by animosity22** [comment]
This looks to be answered.

If there is still a question, please ask on https://forums.rclone.org

**Comment by nyuszika7h** [comment]
Yep, I'm getting this too, but only with 1fichier. Their clock seems to be constantly off by 5-30 minutes or so.
