### ISSUE TITLE
using OneDrive with chunker and crypt results in stalled transfers

### ISSUE THREAD

**Issue by kultigspritzig** [rclone/rclone#4021]
#### What is the problem you are having with rclone?

After enabling chunker I am seeing 0/s or very low transfer – although the latter happened only once.

#### What is your rclone version (output from `rclone version`)
Tried with `1.51 release` and `v1.51.0-076-g38a4d50e-beta`

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 64bit

####  Which cloud storage system are you using? (eg Google Drive)
OneDrive Business

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`/usr/bin/rclone move /mnt/local/Media backup1_chunker:/Media --config=/home/seed/.config/rclone/rclone.conf --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36" --checkers=16 --onedrive-chunk-size=120M --stats=60s --transfers=4 -vv --skip-links --retries=1 --low-level-retries=2 --exclude=**partial~ --exclude=**_HIDDEN~ --exclude=.unionfs/** --exclude=.unionfs-fuse/** --exclude=.fuse_hidden**`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
test@box:~$ /usr/bin/rclone move /mnt/local/Media backup1_chunker:/Media --config=/home/seed/.config/rclone/rclone.conf --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36" --checkers=16 --onedrive-chunk-size=120M --stats=60s --transfers=4 -vv --skip-links --retries=1 --low-level-retries=2 --exclude=**partial~ --exclude=**_HIDDEN~ --exclude=.unionfs/** --exclude=.unionfs-fuse/** --exclude=.fuse_hidden**
2020/03/01 12:41:25 DEBUG : rclone: Version "v1.51.0-076-g38a4d50e-beta" starting with parameters ["/usr/bin/rclone" "move" "/mnt/local/Media" "backup1_chunker:/Media" "--config=/home/seed/.config/rclone/rclone.conf" "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36" "--checkers=16" "--onedrive-chunk-size=120M" "--stats=60s" "--transfers=4" "-vv" "--skip-links" "--retries=1" "--low-level-retries=2" "--exclude=**partial~" "--exclude=**_HIDDEN~" "--exclude=.unionfs/**" "--exclude=.unionfs-fuse/**" "--exclude=.fuse_hidden**"]
2020/03/01 12:41:25 DEBUG : Using config file from "/home/seed/.config/rclone/rclone.conf"
2020/03/01 12:41:29 DEBUG : Chunked 'backup1_chunker:/Media': Waiting for checks to finish
2020/03/01 12:41:29 DEBUG : Chunked 'backup1_chunker:/Media': Waiting for transfers to finish
2020/03/01 12:42:26 INFO  :
Transferred:   	         0 / 3.386 TBytes, 0%, 0 Bytes/s, ETA -
Checks:                 0 / 4, 0%
Transferred:            0 / 169, 0%
Elapsed time:        58.8s
Checking:

Transferring:
 * media1.iso:  0% /30.707G, 0/s, -
 * media2.iso:  0% /18.186G, 0/s, -
 * media3.iso:  0% /30.970G, 0/s, -
 * media4.iso:  0% /25.537G, 0/s, -
```

However, uploading to the underlying `backup1_enc:` remote directly with `/usr/bin/rclone move /mnt/local/Media backup1_enc:/Media (...)` results in correct behavior, although some media files uploaded are different:

```
Transferred:   	    1.874G / 3.386 TBytes, 0%, 32.624 MBytes/s, ETA 1d6h12m54s
Checks:                 0 / 4, 0%
Transferred:            0 / 169, 0%
Elapsed time:        58.8s
Checking:

Transferring:
 * media1.iso:  2% /18.186G, 8.326M/s, 36m20s
 * media2.iso:  1% /28.295G, 8.360M/s, 56m46s
 * media4.iso:  1% /29.382G, 8.487M/s, 58m9s
 * media5.iso:  1% /25.537G, 8.518M/s, 50m13s
```

Remotes are configured as following:
```
[backup1_enc]
type = crypt
remote = backup1:
filename_encryption = standard
directory_name_encryption = true
password = xxxx

[backup1_chunker]
type = chunker
remote = backup1_enc:
chunk_size = 600M
hash_type = md5
```

`rclone ls backup1_enc:` and `rclone ls backup1_chunker:` both correctly display the folder structure with files in it.

**Comment by ncw** [comment]
Are the transfers actually stalled or is it just the stats being wrong - can you tell by looking at your outgoing bandwidth?

@ivandeex any thoughts on this?

**Comment by kultigspritzig** [comment]
@ncw I have reverted back to using crypt only, since my OneDrive business account actually does take files up to 100GB in size now, so I no longer have use for chunker. However, I set up another of my OneDrive accounts with chunker just for testing and it worked just fine. I guess this can be closed.

**Comment by ivandeex** [comment]
@kultigspritzig ok let's mark it "does not reproduce"

@ncw maybe we can add a "onedrive + crypt + chunker" config to the integration suite?

**Comment by ncw** [comment]
> maybe we can add a "onedrive + crypt + chunker" config to the integration suite?

That is a reasonable idea!

**Comment by kultigspritzig** [comment]
I decided to go with chunker enabled after all due to a lot of my bigger uploads running out of the 24h window for token upload. I immediately run into the same issue. Therefore the problem here is that I cannot enable chunker for an en existing endpoint.

**Comment by kultigspritzig** [comment]
@ivandeex I am happy to help debugging this, just need some pointers where to start.

**Comment by Saoneth** [comment]
@kultigspritzig try setting hash_type to none

**Comment by ivandeex** [comment]
Can be related to https://github.com/rclone/rclone/issues/4176

**Comment by ivandeex** [comment]
@kultigspritzig

I believe that your pre-transfer delays occur due to chunker hashing large files (since hash_type=md5). Most remotes keep file hashsum in a special file meta-tags and return it immediately when chunker requests it before transfer, but **local** filesystem is a prominent exception. It reports to chunker that hashsum is available but calculates it on-the-fly resulting in substantial delay if the file is large. During calculation is see no traffic but high CPU load. 

I applied this https://github.com/ivandeex/rclone/commit/9751eaf02b4690f2e291b88c215016423347bc0d experimental patch and created a beta build, which you can download here https://github.com/ivandeex/rclone/releases/tag/v1.51.onedrivedelay1 to investigate your case.

The beta explicitly prints hashsum calculation time and additionally supports a special flag `--chunker-hash-nodelay`, which makes chunker revert to in-transit hashsum calculation if the source file is local, this avoiding the delay.

Example of uploading a 1GB file to onedrive+crypt+chunker with the beta:
```
$ du -hs file1
1005M   file1
$ ./rclone copy -P -v ./file1 onedrive1chunk:
2020-05-18 18:52:00 INFO  : file1: start hashing MD5 ...
2020-05-18 18:52:03 INFO  : file1: hashing MD5 took 3.053437235s
2020-05-18 18:53:37 INFO  : file1.rclone_chunk.001_jfupnt: Moved (server side)
2020-05-18 18:53:37 INFO  : file1.rclone_chunk.002_jfupnt: Moved (server side)
2020-05-18 18:53:38 INFO  : file1.rclone_chunk.003_jfupnt: Moved (server side)
2020-05-18 18:53:39 INFO  : file1: Copied (new)
Transferred:     1004.260M / 1004.260 MBytes, 100%, 10.186 MBytes/s, ETA 0s
Elapsed time:      1m38.5s
```
And this is how `--chunk-hash-nodelay` affects transfers:
```
$ ./rclone deletefile onedrive1chunk:file1
$ ./rclone copy --chunker-hash-nodelay -P -v ./build/file1 onedrive1chunk:
2020-05-18 18:05:38 INFO  : file1: skip long MD5 on local file, hashing in-transit
2020-05-18 18:06:53 INFO  : file1.rclone_chunk.001_jdpcxu: Moved (server side)
2020-05-18 18:06:53 INFO  : file1.rclone_chunk.002_jdpcxu: Moved (server side)
2020-05-18 18:06:55 INFO  : file1.rclone_chunk.003_jdpcxu: Moved (server side)
2020-05-18 18:06:56 INFO  : file1: Copied (new)
Elapsed time:      1m17.8s
```

Here is my configuration:
```
$ tail -20 ~/.config/rclone/rclone.conf
[onedrive1]
type = onedrive
token = {"access_token"...}
drive_id = ...
drive_type = personal
[onedrive1crypt]
type = crypt
remote = onedrive1:crypt
filename_encryption = standard
directory_name_encryption = true
password = ...
password2 = ...
[onedrive1chunk]
type = chunker
remote = onedrive1crypt:
chunk_size = 500M
hash_type = md5
```

Please check it out and tell me if it solves your problem.

**Comment by anaisbetts** [comment]
I think that this bug also triggers some faulty delay logic - like theoretically, once the token quota comes back it should resume, but ime it will stay wedged forever after a certain amount of time

**Comment by ivandeex** [comment]
> I think that this bug also triggers some faulty delay logic
Try the build from https://github.com/ivandeex/rclone/releases/tag/v1.51.onedrivedelay1
Does it solve your issue?

**Comment by anaisbetts** [comment]
@ivandeex I'll give it a try today

**Comment by ivandeex** [comment]
@kultigspritzig 
@anaisbetts 
Hi. Can you please try if the beta https://github.com/ivandeex/rclone/releases/tag/v1.53-chunker-prehash-02 solves your issues?

**Comment by anaisbetts** [comment]
@ivandeex This fix seems to work for me, sorry for the late reply
