### ISSUE TITLE
rclone mount fails because a generated volume name is too long

### ISSUE THREAD

**Issue by ibiruai** [rclone/rclone#4026]
#### What is the problem you are having with rclone?

When you use rclone mount, a volume name is generated if not specified with `--volname="name"`. If it is longer than 32 symbols, rclone mount will fail.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.51.0-076-g38a4d50e-beta
- os/arch: windows/amd64
- go version: go1.14
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 7, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Yandex Disk

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone mount Yandex:123456789/123456789/123456 D:\pictures`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2020/03/02 14:12:30 DEBUG : rclone: Version "v1.51.0-076-g38a4d50e-beta" starting with parameters ["rclone" "mount" "Yandex:123456789/123456789/123456" "D:\\pictures" "-vv"]
2020/03/02 14:12:30 DEBUG : Using config file from "C:\\Users\\User\\.config\\rclone\\rclone.conf"
2020/03/02 14:12:30 DEBUG : Yandex 123456789/123456789/123456: Mounting on "D:\\pictures"
2020/03/02 14:12:30 INFO  : Yandex 123456789/123456789/123456: poll-interval is not supported by this remote
2020/03/02 14:12:30 DEBUG : Adding path "vfs/forget" to remote control registry
2020/03/02 14:12:30 DEBUG : Adding path "vfs/refresh" to remote control registry
2020/03/02 14:12:30 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2020/03/02 14:12:30 DEBUG : Yandex 123456789/123456789/123456: Mounting with options: ["-o" "fsname=Yandex:123456789/123456789/123456" "-o" "subtype=rclone" "-o" "max_readahead=131072" "-o" "attr_timeout=1" "-o" "atomic_o_trunc" "-o" "uid=-1" "-o" "gid=-1" "--FileSystemName=rclone" "-o" "volname=Yandex 123456789 123456789 123456"]
2020/03/02 14:12:30 ERROR : Yandex 123456789/123456789/123456: Mount failed
2020/03/02 14:12:30 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed
```

**Comment by ncw** [comment]
This should be quite easy to fix - do you want to have a go?

**Comment by ibiruai** [comment]
I do! Does [this commit](https://github.com/ibiruai/rclone/commit/d9af33883c7f6a88ce7aa8db7d535e6d929f2322) look right? Should I pull request it?
I'm not sure if the 32 symbols limitation is right for all OSes, and if this change needs to be done in `cmd/mountlib/mount.go` or in `cmd/mount/mount.go`.

**Comment by ncw** [comment]
> Yes, I do! Does [this commit](https://github.com/ibiruai/rclone/commit/d9af33883c7f6a88ce7aa8db7d535e6d929f2322) look right?

Very good :-)

You don't need the `0` in `[0:32]`

> Should I pull request it?

Yes please!

> I'm not sure if the 32 symbols limitation is right for all OSes

I don't know whether this is a problem on non-Windows platforms... Maybe add a `runtime.GOOS == "windows" &&` in the `if` statement to be safe?

> if this change needs to be done in `cmd/mountlib/mount.go` or in `cmd/mount/mount.go`.

`mountlib` where you have it is perfect then it will apply to mount/cmount/mount2 also
