### ISSUE TITLE
azureblob mounts container to subfolder instead of root folder with SAS URL [regression]

### ISSUE THREAD

**Issue by cafarm** [rclone/rclone#4028]
#### What is the problem you are having with rclone?
The Microsoft Azure Blob Storage backend now mounts containers to subfolders of a local mount folder instead of directly in the root folder. This is a regression from rclone v1.48.

*rclone v1.48 behavior:*
```
$ rclone mount mycontainer: myfolder/ &
$ ls myfolder
myfile1  myfile2 
```

*rclone v1.51 behavior:*
```
$ rclone mount mycontainer: myfolder/ &
$ ls myfolder
mycontainer
$ ls myfolder/mycontainer
myfile1  myfile2
```

*cat rclone.conf:*
```
[mycontainer]
type = azureblob
sas_url = https://someaccount.blob.core.windows.net/mycontainer?st=...&se=...&sig=...
```

#### What is your rclone version (output from `rclone version`)
```
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Microsoft Azure Blob Storage

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone mount my-container: myfolder/`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

N/A

**Comment by ncw** [comment]
I take it your `sas_url` is limited to a single container? Is that correct?

A bit of git bisect indicates that this was introduced in 8a0775ce3c8a45890cdb8b17366e4b5134d8afe7


Here is how the old and the new version compare

```
$ rclone-v1.48 -vv lsf azureblobsas:
2020/03/02 17:47:48 DEBUG : rclone: Version "v1.48.0" starting with parameters ["rclone-v1.48" "-vv" "lsf" "azureblobsas:"]
10M
crypt/
hello.txt
```

```
$  rclone-v1.48 -vv lsf azureblobsas:rclone
2020/03/02 18:02:24 DEBUG : rclone: Version "v1.48.0" starting with parameters ["rclone-v1.48" "-vv" "lsf" "azureblobsas:"]
10M
crypt/
hello.txt
```


Here is what it looks like with v1.49.1

```
$ rclone-v1.49.1 -vv lsf azureblobsas:
2020/03/02 17:47:59 DEBUG : rclone: Version "v1.49.1" starting with parameters ["rclone-v1.49.1" "-vv" "lsf" "azureblobsas:"]
rclone/
```

```
$ rclone-v1.49.1 -vv lsf azureblobsas:rclone
2020/03/02 17:48:04 DEBUG : rclone: Version "v1.49.1" starting with parameters ["rclone-v1.49.1" "-vv" "lsf" "azureblobsas:rclone"]
10M
crypt/
hello.txt
```

This is why I think the behavior is broken

```
$ rclone-v1.48 -vv lsf azureblobsas:crypt
2020/03/02 17:59:19 DEBUG : rclone: Version "v1.48.0" starting with parameters ["rclone-v1.48" "-vv" "lsf" "azureblobsas:crypt"]
2020/03/02 17:59:19 Failed to create file system for "azureblobsas:crypt": Container name in SAS URL and container provided in command do not match
```

```
$ rclone-v1.49.1 -vv lsf azureblobsas:rclone/crypt
2020/03/02 17:59:25 DEBUG : rclone: Version "v1.49.1" starting with parameters ["rclone-v1.49.1" "-vv" "lsf" "azureblobsas:rclone/crypt"]
jhosol4a05qq5d28s0730v92c4
```

The new behavior is also the same as the b2 backend with the equivalently limited container.

So I think I'd like to remove this feature, especially since this feature was added in v1.49.1 and it hasn't been reported until now 7 months later.

It does call out this specific behaviour in [the docs](https://rclone.org/azureblob/#sas-url) though

> If You use container level SAS URL, rclone operations are permitted only on particular container, eg
> 
> rclone ls azureblob:container or rclone ls azureblob:
> Since container name already exists in SAS URL, you can leave it empty as well.

What do you think?

**Comment by cafarm** [comment]
Yes, the `sas_url` is limited to a single container.

No problem removing the feature. As long as I know to expect the container in a subfolder, it is not an issue.

So, just to confirm, you're going to keep the new behavior?

**Comment by ncw** [comment]
> Yes, the `sas_url` is limited to a single container.
> 
> No problem removing the feature. As long as I know to expect the container in a subfolder, it is not an issue.

OK

> So, just to confirm, you're going to keep the new behavior?

If you are happy then I will.

I'll update the docs in a bit with the actual behaviour.

Note that if you add the container in the path then it will work with old **and** new rclones so what we are doing is removing the "azure:" shortcut on a SAS URL meaning "azure:container".

**Comment by cafarm** [comment]
> If you are happy then I will.

Sounds great. Thanks!

> Note that if you add the container in the path then it will work with old and new rclones so what we are doing is removing the "azure:" shortcut on a SAS URL meaning "azure:container".

That's exactly what I'll do.

**Comment by ncw** [comment]
I've updated the docs so they match rclone's behaviour - thanks for reporting this :-)
