### ISSUE TITLE
获取令牌失败

### ISSUE THREAD

**Issue by Dingzhenpiyi** [rclone/rclone#4030]
在获取令牌时出现：
Failed to configure token: unexpected end of JSON input
请问该怎样解决，谢谢！

**Comment by Yexiaoxing** [comment]
Please use the [issue template](https://github.com/rclone/rclone/tree/master/.github/ISSUE_TEMPLATE) and rewrite your question.

**Comment by animosity22** [comment]
This seems just like a question rather than an issue. If you can make a post on the forums, we are happy to help out!
