### ISSUE TITLE
Drop the vendor directory

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#4032]
Now that rclone only supports go1.14, go1.13, go1.12 and go1.11 we can drop the vendor directory from rclone and rely solely on go modules (that is assuming go1.11 modules work well enough which I haven't tested yet.)

Cons of the vendor directory

- bulks the repo
- makes it harder for contributors making a separate vendor patch
- makes merges more painful
- go1.13 ignores the vendor directory so modules are in use now

Pros of the vendor directory

- all the files available for a fully reproducible build
    - we could easily add back the vendor directory as part of making the source release

There is some [useful discussion here for restic](https://github.com/restic/restic/issues/2482) which is a similar project

I think I'm probably in favour of dropping the vendor directory but adding it back with `go mod vendor` for the source release.

I'd like feedback from the team (or any other interested parties) - any thoughts?

Cc: @breunigs @buengese @Cnly @darthShadow @dibu28 @ishuah @ivandeex @klauspost @remusb @sandeepkru

**Comment by klauspost** [comment]
Seems reasonable to ditch it.

**Comment by darthShadow** [comment]
My personal opinion would be to drop it, but, considering that only go1.14 has announced modules as production-ready, it may be necessary to keep it at least till the time we support go1.11, if not go1.12 too.

**Comment by buengese** [comment]
I'm all for removing the vendor directory makes merges and rebase much more painful but it might still be to do early to. 

Actually I'd have said let's keep it until the new Ubuntu LTS version is out (or given that the current LTS still ships with go1.10 but if compile with 1.10 is already unsupported I see no reason to keep it any longer.

**Comment by ncw** [comment]
I dropped go1.10 support when go1.14 came out so we support 4 go versions. I didn't realize that about the Ubuntu LTS... The new LTS is due next month isn't it.

I was thinking of adding the result of `go mod vendor` to the source tarball. A good idea? It then means the source has diverged from being a git checkout so maybe it should be a separate tarball?

The initial attempt at removing modules mostly works, just need to figure out how the xgo build is broken!

**Comment by ncw** [comment]
Just ran into https://github.com/golang/go/issues/37436 while testing locally :-( We'll see whether it works on GitHub actions in a moment.

**Comment by Denis-Oakley** [comment]
Now Ubuntu LTS released, and golang/go#37436 doesn't seems to effect all go versions. Can we drop the vendor now?

**Comment by ncw** [comment]
In the interest of getting the very delayed 1.51 release out, I'm going to move this to 1.52

**Comment by buengese** [comment]
Are there any reasons left at this point to keep the vendor directory? golang/go#37436 shouldn't really be an issue anymore and this is something I'd really like to see happen.

**Comment by ncw** [comment]
Thanks for the nudge!

I rebased the work I've done so far and I've pushed it to the modules branch - let's see if it builds...

Comments appreciated!

[v1.52.2-224-g19d077c8-modules-beta](https://beta.rclone.org/branch/v1.52.2-224-g19d077c8-modules-beta/) on branch [modules](https://github.com/rclone/rclone/tree/modules) (uploaded in 15-30 mins)

**Comment by buengese** [comment]
That seems to be working well. Let's give this some more time in case someone else has any comments. Also pinging @Max-Sum, @creativeprojects and @calebcase specifically that weren't initially mentioned.

**Comment by calebcase** [comment]
Yes, please ;o]

**Comment by ncw** [comment]
OK I merged the above!

Vendor directory now consigned to the dusbin of history.

Open champagne :-)

:champagne:
