### ISSUE TITLE
Make filter flags (eg `--files-from`) understand `-` as a file name to mean pipe from stdin

### ISSUE THREAD

**Issue by calisro** [rclone/rclone#4034]
As discussed in the below thread, it would be convenient from a scripting perspective to allow any flag that contains a list of files to process to pass that list in via standard in with a dash as a parameter instead of creating intermediate files.  These specifically right now.

      --exclude-from stringArray             Read exclude patterns from file
      --files-from stringArray               Read list of source-file names from file

Using this as an example:
```
find ./ -name 'search_term*' -type f ! -newer /tmp/mytime | sed 's/^.\///' |
rclone delete --dry-run -files-from - remote:
```

Reference topics:
https://forum.rclone.org/t/flag-for-disabling-concurrent-checks-copy/14676/7
https://forum.rclone.org/t/pass-find-results-to-rclone-delete-command/14538/3

**Comment by ncw** [comment]
This is a great idea.  I think implementing it would be quite easy

Altering this to check `if path == "-"`` and using `os.Stdin` (remember **not** to close it) would mean all the filter `-from` flags would then understand `-`.

https://github.com/rclone/rclone/blob/1c800efbace663d5b3e889cf7f49cabb4e8b3cd6/fs/filter/filter.go#L467-L471

Any takers? Don't forget to update the docs.

**Comment by fishbullet** [comment]
I've just realized what to do if there are bunch of parameters will be provided with `-` ? 
Threre is only one sdtin.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

**Comment by calisro** [comment]
works great. thanks!!

**Comment by ncw** [comment]
Thanks to go @fishbullet which I should have said above!
