### ISSUE TITLE
Slow download from Google Cloud Storage with v1.51. Works with v.1.47.

### ISSUE THREAD

**Issue by hakong** [rclone/rclone#4035]
#### What is the problem you are having with rclone?
Slow download speeds from Google Cloud Storage with the latest version.
Screenshot of past 30 days:
![image](https://user-images.githubusercontent.com/4422113/75781740-af20ff00-5d55-11ea-9318-898c092caae9.png)
Screenshot of last 3 hours testing between v1.51 and v1.47 with different --bwlimit parameters:
![image](https://user-images.githubusercontent.com/4422113/75783301-40917080-5d58-11ea-8865-b45d107bc451.png)

#### What is your rclone version (output from `rclone version`)
Slow download: 
```
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7
```
Graph indicates throttling with burst spikes.
![image](https://user-images.githubusercontent.com/4422113/75781840-d7a8f900-5d55-11ea-9d5a-db1cdb6ddc74.png)

Fast download:
```
rclone v1.47.0        
- os/arch: linux/amd64
- go version: go1.11.5
```
![image](https://user-images.githubusercontent.com/4422113/75781802-c6f88300-5d55-11ea-8a2d-c31eac9a37a5.png)
![image](https://user-images.githubusercontent.com/4422113/75785807-38d3cb00-5d5c-11ea-84f5-16fed5c68ea0.png)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
```
Red Hat Enterprise Linux Server release 7.7 (Maipo)
3.10.0-1062.12.1.el7.x86_64
```

####  Which cloud storage system are you using? (eg Google Drive)
Google Cloud Storage

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
rclone copy --bwlimit=1750M --checkers=32 --size-only --fast-list --transfers=32 --ignore-checksum -P --stats-one-line --log-file="$log_file" --log-level=DEBUG --exclude 'xxxx*/*' --exclude 'xxxx-*/*' bucket:path/ /local/path/
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2020/03/03 13:29:23 DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "copy" "--bwlimit=1750M" "--checkers=32" "--size-only" "--fast-list" "--transfers=32" "--ignore-checksum" "-P" "--stats-one-line" "--log-file=/path/to/log.log" "--log-level=DEBUG" "--exclude" "xxxx*/*" "--exclude" "xxxx-*/*" "bucket:path/" "/local/path"]
2020/03/03 13:29:23 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2020/03/03 13:29:23 INFO  : Starting bandwidth limiter at 1.709GBytes/s
2020/03/03 13:29:30 DEBUG : directory1_xx/xx.xx: Excluded from sync (and deletion)
2020/03/03 13:29:30 DEBUG : directory1_xx/xx.xx.xx: Excluded from sync (and deletion)
2020/03/03 13:29:30 DEBUG : directory1_xx/xx.xx.xx.xx: Excluded from sync (and deletion)
2020/03/03 13:29:30 DEBUG : directory1_xx/xx.xx.xx: Excluded from sync (and deletion)
2020/03/03 13:29:30 DEBUG : directory1_xx/xx.xx.xx: Excluded from sync (and deletion)
2020/03/03 13:29:30 DEBUG : directory1_xx/xx.xx.xx: Excluded from sync (and deletion)
2020/03/03 13:29:30 DEBUG : directory1_xx/xx.xx.xx.xx: Excluded from sync (and deletion)
<600.000 lines of debug log>
2020/03/03 14:02:30 INFO  : Local file system at /local/path: Waiting for transfers to finish
2020/03/03 14:02:30 INFO  :          0 / 0 Bytes, -, 0 Bytes/s, ETA -
2020/03/03 14:02:30 DEBUG : 4 go routines active
2020/03/03 14:02:30 DEBUG : rclone: Version "v1.51.0" finishing with parameters ["rclone" "copy" "--bwlimit=1750M" "--checkers=32" "--size-only" "--fast-list" "--transfers=32" "--ignore-checksum" "-P" "--stats-one-line" "--log-file=/path/to/log.log" "--log-level=DEBUG" "--exclude" "xxxx*/*" "--exclude" "xxxx-*/*" "bucket:path/" "/local/path"]
```

Bucket is >1PB and >1M files. I have 200GB+ of debug logs since I started downloading. Log content is confidential but I can provide redacted excerpts from logs at request.

**Comment by ncw** [comment]
A 1 PB bucket with 1M files means an average file size of ~1GB - is that about right?

I wonder whether the multithread download (which will be active for files this big) is counterproductive here... Can you try `--multi-thread-streams 0` to see if that makes a difference?

It would be useful if you could try some intermediate rclone values to see which release caused the problem if it isn't `--multi-thread-streams`.

**Comment by hakong** [comment]
Each directory contains a few files:
1x 15-20GB file
1x 5-10GB file
3-4x 5M-10MB files
a few metadata and checksum files (<1KB)

I don't have time right now, but I'll test the multi-thread-stream option next week.

**Comment by animosity22** [comment]
If you want to further look at this, please use the forums and we can help troubleshoot there as this seems stale.

https://forums.rclone.org

Thanks!
