### ISSUE TITLE
Can't edit from LibreOffice

### ISSUE THREAD

**Issue by mauro-miatello** [rclone/rclone#4045]
#### What is the problem you are having with rclone?

When I edit google document/sheet or odt/ods files with LibreOffice, I see strange characters
no problem with txt

#### What is your rclone version (output from `rclone version`)

1.50.2-2

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Kubuntu 20.04

####  Which cloud storage system are you using? (eg Google Drive)

GSuite / Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount "GSuite Fsw":Lavoro GSuite_Fsw --vfs-cache-mode full -vv

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

[rclone.log](https://github.com/rclone/rclone/files/4303089/rclone.log)

**Comment by ivandeex** [comment]
@mauro-miatello 
This bug is reported against obsolete version of rclone. Can you reproduce it with rclone 1.54?

**Comment by mauro-miatello** [comment]
sorry I don't use rclone any more
