### ISSUE TITLE
Some problems of rclone incompatibility with Kingsoft Cloud KS3

### ISSUE THREAD

**Issue by JuliaWang995** [rclone/rclone#4048]
#### What is the problem you are having with rclone?

1. In case of uploading text type file, return signature verification mismatch
2. MD5 error reported when uploading m4a and files larger than 5G

####  Which cloud storage system are you using? (eg Google Drive)

Kingsoft Cloud KS3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
1. 
liupengcheng$ rclone copy /Users/liupengcheng/rclone-v1.51.0-osx-amd64/git-log.txt ks3:shanghaidemo
2020/02/17 16:25:11 ERROR : git-log.txt: Failed to copy: s3 upload: 403 Forbidden: <?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your KS3 secret access key and signing method. For more information, see REST Authentication and SOAP Authentication for details.</Message>
<Resource>/shanghaidemo/git-log.txt?X-Amz-Expires=900&X-Amz-Date=20200217T082511Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Signature=6079241e5180e0487641d84fbea6d7ed18a880b459662aa6c4bf5faedee4e9b2&X-Amz-SignedHeaders=content-md5;content-type;host;x-amz-acl;x-amz-meta-mtime&X-Amz-Credential=AKLTI5NEgRq_T5igNlCPVI446w/20200217/SHANGHAI/s3/aws4_request</Resource>
<RequestId>e4964595c31b492bae41e782defd2a8e</RequestId>
</Error>

2.
[root@vm10-16-87-6 rclone]# ./rclone copyto /root/ExchangeServer2016-x64-cu11.iso ks3-sh:fzy-shtest-181024/ExchangeServer.iso
ERROR : ExchangeServer.iso: corrupted on transfer: MD5 hash differ "6beb50a2743335e6b76f552d2bf8a533" vs "9efe4a62304a6eac0a3101eeb38ee4b9"

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

[Forum Thread: MD5 error reported when uploading m4a and files larger than 5G](https://forum.rclone.org/t/md5-error-reported-when-uploading-m4a-and-files-larger-than-5g/14753)

**Comment by ivandeex** [comment]
No comments / likes / volunteers / interest after almost 2 years.
Please reopen if the issue is still important.
