### ISSUE TITLE
Remove folders with rclone delete

### ISSUE THREAD

**Issue by agneevX** [rclone/rclone#4055]
#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.51.0
- os/arch: linux/arm
- go version: go1.13.7
```

#### What problem are you are trying to solve?
Delete all contents instead of just objects with `rclone delete`. 

#### How do you think rclone should be changed to solve that?
As [discussed](https://forum.rclone.org/t/how-do-i-delete-all-the-contents-of-a-folder/14837) on the forums, a flag, `--rmdirs` along with `rclone delete` should delete all contents of the folder, but not the folder itself.

**Comment by ncw** [comment]
I think the easiest way of implementing this would be to run`rclone rmdirs` if the `--rmdirs` flag is set.

It would be more efficient to accumulate the directories in the delete phase for a bit more code than the `rmdirs` solution

Do you want to help implement this @agneevX - I can make an outline of the work if you want?

**Comment by agneevX** [comment]
> Do you want to help implement this @agneevX - I can make an outline of the work if you want?

Not sure; I don't know much of Golang, studied Java in HS, that's all :)

**Comment by kushsharma** [comment]
@ncw looks easy enough to implement, can you elaborate on what outline you have in mind for this?

**Comment by ncw** [comment]
@kushsharma here is a brief outline - let me know if you need more :-)

In the [delete command](https://github.com/rclone/rclone/blob/master/cmd/delete/delete.go)

Add a flag called `--rmdirs` (see [cat.go](https://github.com/rclone/rclone/blob/master/cmd/cat/cat.go) for an example on how to do that)

If the flag is set then after doing the Delete

https://github.com/rclone/rclone/blob/c4572ebc91288957356de519a178e9dd21da09e3/cmd/delete/delete.go#L44

Then call `operations.Rmdirs` with `leaveRoot=true` (this could be a flag)

https://github.com/rclone/rclone/blob/c4572ebc91288957356de519a178e9dd21da09e3/fs/operations/operations.go#L1427-L1429

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

Thank you to @kushsharma  for implementing it :-)

**Comment by agneevX** [comment]
Thank you both!
