### ISSUE TITLE
Implement OneDrive server side copy

### ISSUE THREAD

**Issue by Dibbyo456** [rclone/rclone#4058]
OneDrive does have server side copy feature just like Google Drive.

Docs: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_copy?view=odsp-graph-online

**Comment by darthShadow** [comment]
rclone already uses the same API for copies and hence already supports server-side copies. Source: https://github.com/rclone/rclone/blob/6fdd7149c1b68223c42cf5fe9994a4b78fa3d9bc/backend/onedrive/onedrive.go#L972

Is there anything specific that you require that is missing?

**Comment by Dibbyo456** [comment]
> Is there anything specific that you require that is missing?

I tried to copy files between 2 onedrive accounts, but Rclone was not doing server side copy.

```
C:\Users\HARRY>rclone copy onedrive1:MyFolder onedrive2:MyFolder -vv

2020/03/13 13:58:48 DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "copy" "onedrive1:MyFolder" "onedrive2:MyFolder" "-vv"]
2020/03/13 13:58:48 DEBUG : Using config file from "C:\\Users\\HARRY\\.config\\rclone\\rclone.conf"
2020/03/13 13:58:55 INFO  : One drive root 'MyFolder': Waiting for checks to finish
2020/03/13 13:58:55 INFO  : One drive root 'MyFolder': Waiting for transfers to finish
2020/03/13 13:59:00 DEBUG : testfile.mkv: Starting multipart upload
2020/03/13 13:59:02 DEBUG : testfile.mkv: Uploading segment 0/1428477633 size 10485760
2020/03/13 13:59:12 DEBUG : testfile.mkv: Uploading segment 10485760/1428477633 size 10485760
2020/03/13 13:59:13 INFO  : Signal received: interrupt
2020/03/13 13:59:13 DEBUG : testfile.mkv: Cancelling multipart upload
2020/03/13 13:59:14 INFO  : Exiting...
```
The `MyFolder` directory from `onedrive1` is shared with `onedrive2` but still the server side copy did not work.

I guess the file/directory has to be copied from `Shared with you` listing to make the server side copy work.

**Comment by darthShadow** [comment]
Can you try copying the folder using the same remote since its shared?

**Comment by Dibbyo456** [comment]
> Can you try copying the folder using the same remote since its shared?

How do I list it?

**Comment by darthShadow** [comment]
I believe it includes the shared folders by default in the listing, so it should be as simple as replacing `onedrive1` in the copy command with `onedrive2`.

**Comment by Dibbyo456** [comment]
> I believe it includes the shared folders by default in the listing

Nope, it does not. `lsf` not returning the shared directory. This is exactly why I opened #4062

**Comment by darthShadow** [comment]
Is this OneDrive Personal or Business? According to [this](https://github.com/rclone/rclone/issues/2536), it should work fine for Personal accounts. Anyway, I will wait for someone more knowledgable about this to chime in.

Not sure if it would be helpful, but can you please specify the rclone version and add the debug logs too?

Pinging @Cnly

**Comment by Dibbyo456** [comment]
> Is this OneDrive Personal or Business?

Business

> but can you please specify the rclone version and add the debug logs too?

https://github.com/rclone/rclone/issues/4058#issuecomment-598610346

**Comment by ncw** [comment]
Hmm, looking at the code i see no reason why this shouldn't work...

I added a `--onedrive-server-side-across-configs` flag - give that a go

https://beta.rclone.org/branch/v1.51.0-101-g0b448e46-fix-4058-onedrive-across-configs-beta/ (uploaded in 15-30 mins)

**Comment by Dibbyo456** [comment]
> I added a `--onedrive-server-side-across-configs` flag - give that a go

**Error**: Failed to copy: can't copy "100MB.bin" -> "100MB.bin" as are same name when lowercase

**Full log**:
```
harry@ubuntu16:~$ ./rclone copy od21:100MB.bin od22: --onedrive-server-side-across-configs -vv
2020/03/15 21:30:01 DEBUG : rclone: Version "v1.51.0-101-g0b448e46-fix-4058-onedrive-across-configs-beta" starting with parameters ["./rclone" "copy" "od21:100MB.bin" "od22:" "--onedrive-server-side-across-configs" "-vv"]

2020/03/15 21:30:01 DEBUG : Using config file from "/home/harry/.config/rclone/rclone.conf"
2020/03/15 21:30:10 DEBUG : 100MB.bin: Need to transfer - File not found at Destination
2020/03/15 21:30:10 ERROR : 100MB.bin: Failed to copy: can't copy "100MB.bin" -> "100MB.bin" as are same name when lowercase
2020/03/15 21:30:12 ERROR : Attempt 3/3 failed with 1 errors and: can't copy "100MB.bin" -> "100MB.bin" as are same name when lowercase
2020/03/15 21:30:12 DEBUG : 6 go routines active
2020/03/15 21:30:12 Failed to copy: can't copy "100MB.bin" -> "100MB.bin" as are same name when lowercase
```

**Info**: The file `100MB.bin` from remote `od21:` is shared with remote `od22:`. Both are different accounts.

I believe to make server side copy between different accounts work, first we need to share the file, then copy it from "**Shared with me**" list from second remote (not from origin remote). However Rclone can't list shared with me files from OneDrive from Business.

**Comment by ncw** [comment]
> Error: Failed to copy: can't copy "100MB.bin" -> "100MB.bin" as are same name when lowercase

Ooops, need to remove that check for cross remote - try this

https://beta.rclone.org/branch/v1.51.0-101-g77e94be2-fix-4058-onedrive-across-configs-beta/ (uploaded in 15-30 mins)

> I believe to make server side copy between different accounts work, first we need to share the file, then copy it from "Shared with me" list from second remote (not from origin remote). However Rclone can't list shared with me files from OneDrive from Business.

Try the above - it looks like it might work... If not then we'll work on plan B

**Comment by Dibbyo456** [comment]
This time it worked. 😘

```
harry@ubuntu16:~$ ./rclone copy od21:100MB.bin od22: --onedrive-server-side-across-configs -vv
2020/03/16 03:08:05 DEBUG : Using config file from "/home/harry/.config/rclone/rclone.conf"
2020/03/16 03:08:14 DEBUG : 100MB.bin: Need to transfer - File not found at Destination
2020/03/16 03:08:33 DEBUG : 100MB.bin: QuickXorHash = 0000000000000000000000000000400600000000 OK
2020/03/16 03:08:33 INFO  : 100MB.bin: Copied (server side copy)
2020/03/16 03:08:33 DEBUG : 10 go routines active
```

**Comment by ncw** [comment]
Thanks for testing :-)

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

**Comment by Dibbyo456** [comment]
@ncw The issue needs to be reopen. The server side copy does not work on folder is shared.

## What works?

When a specific file is shared with other user, then the server side copy works. Eg:
```
./rclone copy od21:100MB.bin od22: --onedrive-server-side-across-configs -vv
```

## What does not work?

When a directory is shared with other user, then the server side copy does not work. Eg:

```
./rclone copy onedrive1:mydir onedrive2:newdir --onedrive-server-side-across-configs -vv
```

The abvoce command does not do server side copy even though `mydir` from `onedrive1` is shared with `onedrive2`

**Comment by ncw** [comment]
> When a directory is shared with other user, then the server side copy does not work. Eg:

Can you paste logs with -vv with what happens please?

**Comment by Dibbyo456** [comment]
```
2020/03/22 09:57:02 DEBUG : rclone: Version "v1.51.0-119-g23f79436-beta" starting with parameters ["./rclone-beta" "copy" "odharry:Sam" "od1:SamsungDrive" "--config=rclone.conf" "--onedrive-server-side-across-configs" "-vv" "--log-file=rc.log"]
2020/03/22 09:57:02 DEBUG : Using config file from "/home/runcloud/rclone-union/rclone.conf"
2020/03/22 09:57:15 DEBUG : One drive root 'SamsungDrive': Waiting for checks to finish
2020/03/22 09:57:15 DEBUG : One drive root 'SamsungDrive': Waiting for transfers to finish
2020/03/22 10:02:17 ERROR : 404SCSCS1CPK1_404SCSBM1CPK1_SBM.zip: Failed to copy: async operation didn't complete after 5m0s
2020/03/22 10:02:20 ERROR : A015FXXU1ASLC_A015FOXM1ASLC_CAC.zip: Failed to copy: async operation didn't complete after 5m0s
2020/03/22 10:02:20 ERROR : 404SCSCU1BPA1_404SCSBM1BPA1_SBM.zip: Failed to copy: async operation didn't complete after 5m0s
2020/03/22 10:02:20 ERROR : 404SCSCU1DQG1_404SCSBM1DQG1_SBM.zip: Failed to copy: async operation didn't complete after 5m0s
```

Files are large files; 3-4 GB each.

**Comment by darthShadow** [comment]
This is probably not related to a folder being copied but the size of the files instead.

The same bug that was being discussed here before the poster disappeared: https://forum.rclone.org/t/problem-copy-from-onedrive-to-onedrive/14603/20

@Dibbyo456 Would you mind trying to copy a folder containing smaller files and see if that works fine?

Also, would you try the same copy with a higher `--timeout` since that was the last suggestion by @ncw which we never got any results for?

**Comment by Dibbyo456** [comment]
> Would you mind trying to copy a folder containing smaller files and see if that works fine?

I tried to server side copy a folder with small size files and it worked fine. So, nothing wrong with Rclone, it's the OneDrive which taking a lot of time to copy. (it sucks)

**Comment by darthShadow** [comment]
Google is pretty instant, I think, because they just hard link to a new file, instead of a full copy. Based on the time taken, it looks like Microsoft is actually doing a full copy but even so, that's an awful amount of time taken to copy only 3.5 GB.

**Comment by darthShadow** [comment]
Google also used to time-out earlier when it was actually copying the file (because of a change in mime-type) and the current behaviour is to not change the mime-type, resulting in hard links, I think, instead of actual copies.

I wonder if there is something similar that may be possible in OneDrive too... Would you mind experimenting with the API and see if adding or skipping any parameter speeds up the copy?

**Comment by ncw** [comment]
Foo - not a lot rclone can do about onedrive being slow alas.

32 minutes to copy a 3.5 GB file is 1.8 MB/s!

I'll close this again since rclone at least seems to be working!
