### ISSUE TITLE
[Question] Google Drive change file owner/modified by

### ISSUE THREAD

**Issue by Sparoney** [rclone/rclone#4059]
Hi,

This is just a quick question, I was wondering if there is a command or way to change who last modified a file on Google Drive without making another copy? Similar to how renaming a file changes who it was lost modified by.

For example if I'm using service accounts to copy lots of files I would like them to rather say "modified by Sparon" than "modified by mfc--mm1234xxxxxw8e887xxxx" etc.

This is more of a cosmetic personal OCD thing haha sorry it's a bit of a strange request.

If there's no such way then that's completely fine I'll just do some file renames.

I'd also just like to say thanks for fixing #4018, the duplicate folders was bugging me :)

Thanks!

**Comment by Dibbyo456** [comment]
Haha. You're not alone, I was also thinking about the same. 😅
Drive does have api endpoint which can do this: [permissions/update](https://developers.google.com/drive/api/v3/reference/permissions/update)

**Comment by Sparoney** [comment]
> Haha. You are not alone, I was also thinking about the same. 😅
> Drive does have api endpoint which can do this: [permissions/update](https://developers.google.com/drive/api/v3/reference/permissions/update)

This is actually really useful @Dibbyo456, do you know of a script that can do this recursively? My current guess would be to gather all the file ID's and then make a loop to go through them all

**Comment by darthShadow** [comment]
I haven't tried it myself but this should probably do that: https://rclone.org/commands/rclone_touch/

**Comment by Dibbyo456** [comment]
> I haven't tried it myself but this should probably do that: https://rclone.org/commands/rclone_touch/

@Sparoney this worked for me. I guess problem solved then?

**Comment by Sparoney** [comment]
> > I haven't tried it myself but this should probably do that: https://rclone.org/commands/rclone_touch/
> 
> @Sparoney this worked for me. I guess problem solved then?

@Dibbyo456 it also worked for me but I can't figure out how to use this on all files in a folder. I tried putting the folder name in but it just made a new file, and tried using --include as well.

**Comment by Dibbyo456** [comment]
> but I can't figure out how to use this on all files in a folder

You can't. You need to use other scripting language to make a loop from `ls` output (such as bash, python, php).

**Comment by Sparoney** [comment]
> > but I can't figure out how to use this on all files in a folder
> 
> You can't. You need to use other scripting language to make a loop from `ls` output (such as bash, python, php).

@Dibbyo456 yep after I commented this I modified a script and got it working. Would be cool if there was a way that didnt touch the modified time at all and just the user, similar to how renaming from an rclone mount works.

**Comment by Dibbyo456** [comment]
> I modified a script and got it working

Which language?

> Would be cool if there was a way that didnt touch the modified time at all and just the user

Can you try with `--no-update-modtime` ?

**Comment by Sparoney** [comment]
> Which language?

Just Windows command line
> Can you try with `--no-update-modtime` ?

Tried this, didn't work unfortunately

**Comment by ivandeex** [comment]
Related to https://github.com/rclone/rclone/issues/4742

**Comment by ivandeex** [comment]
Closing after 10 months of inactivity
