### ISSUE TITLE
Failed to copy: multpart copy: failed to open destination: mkdir \\?

### ISSUE THREAD

**Issue by pollux105** [rclone/rclone#4065]
Hi, I experience a problem with Rclone.

I just started backing up 3 folders with 3 different but similar tasks from a win10 to a synology NAS.
All the 3 tasks are similar, as the one following :
`
start "C:\Program Files\rclone\rclone.exe" '--log-file="C:\Users\Cédric\Documents\log_backup_lightroom.txt" --log-level=INFO  sync "L:\Lightroom\Lightroom Catalog.lrcat" //10.0.1.1/lightroom/`

The 3 tasks worked fine for the first few days (6 days actually), but then stopped working with the following error : 

> Failed to copy: multpart copy: failed to open destination: mkdir \\?

More complete logs are following, with the last 2 days working and then the first day of error.

> 2020/03/01 22:00:02 NOTICE: Config file "C:\\Users\\Pollux\\.config\\rclone\\rclone.conf" not found - using defaults
2020/03/01 22:00:02 INFO  : Local file system at \\?\UNC\10.0.1.1\lightroom\: Waiting for checks to finish
2020/03/01 22:00:02 INFO  : Local file system at \\?\UNC\10.0.1.1\lightroom\: Waiting for transfers to finish
2020/03/01 22:00:02 INFO  : Waiting for deletions to finish
2020/03/01 22:00:02 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 1 / 1, 100%
Transferred:            0 / 0, -
Elapsed time:       200ms

> 2020/03/02 22:00:02 NOTICE: Config file "C:\\Users\\Pollux\\.config\\rclone\\rclone.conf" not found -  using defaults
2020/03/02 22:00:03 INFO  : Local file system at \\?\UNC\10.0.1.1\lightroom\: Waiting for checks to finish
2020/03/02 22:00:03 INFO  : Local file system at \\?\UNC\10.0.1.1\lightroom\: Waiting for transfers to finish
2020/03/02 22:00:03 INFO  : Waiting for deletions to finish
2020/03/02 22:00:03 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 0
Checks:                 1 / 1, 100%
Transferred:            0 / 0, -
Elapsed time:       800ms

> 2020/03/03 22:00:03 NOTICE: Config file "C:\\Users\\Pollux\\.config\\rclone\\rclone.conf" not found - using defaults
2020/03/03 22:00:04 ERROR : : error listing: directory not found
2020/03/03 22:00:04 INFO  : Local file system at \\?\UNC\10.0.1.1\lightroom\: Waiting for checks to finish
2020/03/03 22:00:04 INFO  : Local file system at \\?\UNC\10.0.1.1\lightroom\: Waiting for transfers to finish
2020/03/03 22:00:04 ERROR : Lightroom Catalog.lrcat: Failed to copy: multpart copy: failed to open destination: mkdir \\?: La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte.
2020/03/03 22:00:04 ERROR : Local file system at \\?\UNC\10.0.1.1\lightroom\: not deleting files as there were IO errors
2020/03/03 22:00:04 ERROR : Local file system at \\?\UNC\10.0.1.1\lightroom\: not deleting directories as there were IO errors
2020/03/03 22:00:04 ERROR : Attempt 1/3 failed with 3 errors and: multpart copy: failed to open destination: mkdir \\?: La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte.

The 2 others tasks ended with the same problem the same day.
The NAS had no "visible" problem the day the tasks got wrong. 

I have no idea why this problems occurs, as I can access my files with windows explorer, using any admin or users access...

And I had a kind of similar problem a few months ago but did not try to understand why and just restarted from draft.

**Comment by ncw** [comment]
What version of rclone are you using? Can you try [the latest release](https://rclone.org/downloads/) or [the latest beta](https://beta.rclone.org)?

**Comment by pollux105** [comment]
version 1.48, I will upgrade now

**Comment by ncw** [comment]
Glad it is working now :-)
