### ISSUE TITLE
Symlink handling broken

### ISSUE THREAD

**Issue by lpsmith** [rclone/rclone#4066]
#### Output of `rclone version`

rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.6

#### Describe the issue

I would like to copy some files out of a nix store into Google Drive.   The hitch is that the nix store sets the modification time of every file inside of it to `1970-01-01 00:00:00Z`,  so that the modification time cannot be used to break reproducible builds.   However, I would prefer to have the upload time correctly reflected in Google Drive.

1.  I could copy the file out of the nix store into another file in the local filesystem, but I would strongly prefer to avoid this step.

2.  I could pass an option to `rclone` to not preserve modification time,  not unlike `cp`'s `--no-preserve` option.  However, I'm not seeing any documentation that this option exists,  if it exists at all.

3.  I tried creating a symlink to the file inside the nix store,  hoping that rclone would pick up the modification time of the symlink, but this fails.   For example, if I try this to copy the rclone executable to google drive:

```
$ ls -lh /nix/store/kvrpcbi3ph4m9a8jjp7bd445w690wdqs-rclone-1.48.0/bin
total 17M
-r-xr-xr-x 1 root root 34M Dec 31  1969 rclone

$ ln -s /nix/store/kvrpcbi3ph4m9a8jjp7bd445w690wdqs-rclone-1.48.0/bin/rclone rclone-symlink

$ rclone copy rclone-symlink remote:
2020/03/13 12:40:42 ERROR : : error reading source directory: failed to read directory entry: readdirent: not a directory
2020/03/13 12:40:42 ERROR : Attempt 1/3 failed with 1 errors and: failed to read directory entry: readdirent: not a directory
2020/03/13 12:40:43 ERROR : : error reading source directory: failed to read directory entry: readdirent: not a directory
2020/03/13 12:40:43 ERROR : Attempt 2/3 failed with 1 errors and: failed to read directory entry: readdirent: not a directory
2020/03/13 12:40:43 ERROR : : error reading source directory: failed to read directory entry: readdirent: not a directory
2020/03/13 12:40:43 ERROR : Attempt 3/3 failed with 1 errors and: failed to read directory entry: readdirent: not a directory
2020/03/13 12:40:43 Failed to copy: failed to read directory entry: readdirent: not a directory
```

**Comment by darthShadow** [comment]
You will need the `--copy-links` or `-L` to copy the item pointed to by the symlink.

**Comment by lpsmith** [comment]
Ok, so I managed to get that to work,  however,  it's still uploading with a modification time of `1970-01-01 00:00Z`,  not the time when the symlink was created, so that doesn't actually solve the issue I was hoping it would solve :-(

**Comment by darthShadow** [comment]
Since this is more of a question rather than an issue, would you mind hopping on over to the forums at https://forum.rclone.org/ so more people can provide suggestions?

**Comment by ncw** [comment]
I made a suggestion here: https://forum.rclone.org/t/how-can-i-not-preserve-file-timestamps/14904/3

I'll close this one now.
