### ISSUE TITLE
rclone touch --timestamp using incorrect timezone Google Drive

### ISSUE THREAD

**Issue by Sparoney** [rclone/rclone#4067]
#### What is the problem you are having with rclone?

When using ``rclone touch`` with the ``--timestamp`` flag, the timezone used to change the time is incorrect.

#### What is your rclone version (output from `rclone version`)

rclone v1.51.0-098-gb03462ab-beta
- os/arch: windows/amd64
- go version: go1.14

(latest beta at time of this issue)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone touch gdrive_team:Uploads/file.txt --timestamp 2020-03-14T13:00:00

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2020/03/14 13:28:04 DEBUG : rclone: Version "v1.51.0-098-gb03462ab-beta" starting with parameters ["rclone" "touch" "gdrive_team:Uploads/file.txt" "--timestamp" "2020-03-14T13:00:00" "-vv"]
2020/03/14 13:28:04 DEBUG : Using config file from "C:\\Users\\aaron\\.config\\rclone\\rclone.conf"
2020/03/14 13:28:07 DEBUG : 4 go routines active

#

Using ``rclone touch gdrive_team:Uploads/file.txt --timestamp 2020-03-14T13:00:00`` I would expect it to set the modified time to 1:00pm, however it sets it to 12:00am (13 hours behind). I am not sure what timezone it is using to update the time on the server. My local timezone is AEDT.

**Comment by ncw** [comment]
Reading the docs a bit more carefully it appears that the timezone touch is using is UTC which makes sense with AEDT I think which is UTC+11 or 13 hours difference plus a day.

I agree that localtime would be a better thing to be using, and I think that is what touch uses

I guess some users might want UTC so it probably needs a `--utc` flag, or maybe a `--localtime` flag might be better for backwards compatibility.

Thoughts?

**Comment by Sparoney** [comment]
> I guess some users might want UTC so it probably needs a `--utc` flag, or maybe a `--localtime` flag might be better for backwards compatibility.
> 
> Thoughts?

I think a `--localtime` flag would be a perfect addition

**Comment by ncw** [comment]
OK give this a go which has a `--localtime` flag

https://beta.rclone.org/branch/v1.51.0-111-gb1221377-fix-4067-touch-time-beta/ (uploaded in 15-30 mins)

**Comment by Dibbyo456** [comment]
Since the OP did not provide any feedback, I deiced to try it myself. **It works**. 👍

**Comment by ncw** [comment]
Thanks for testing @Dibbyo456 ! I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

**Comment by Sparoney** [comment]
> Thanks for testing @Dibbyo456 ! I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

So sorry I didn't get to test this. My apologies. Thank you heaps for implementing this :)
