### ISSUE TITLE
Modification time not preserved when using Mount

### ISSUE THREAD

**Issue by amigagamer** [rclone/rclone#4070]
Timestamp is not preserved when copying files using rclone mount. However times are preserved when using rclone copy

Rclone 1.51 release ,  also tested with Version "v1.51.0-099-gdc069737-beta on x64
Linux mint 19.3 x64 and Raspbian/arm32
Koofr Cloud storage

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone mount Koofr: ~/rclone --vfs-cache-mode writes   (also tested with full)
Moving the file called pc1.txt in a file manager outputs the following.

```
2020/03/15 10:20:56 DEBUG : : Statfs: 
2020/03/15 10:20:56 DEBUG : : >Statfs: stat={Blocks:268435456 Bfree:216956672 Bavail:216956672 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
2020/03/15 10:20:57 DEBUG : test/pc1.txt: MD5 = 5e641715584068c05138decfac72281e OK
2020/03/15 10:20:57 INFO  : test/pc1.txt: Copied (new)
2020/03/15 10:20:57 DEBUG : test/pc1.txt: transferred to remote
2020/03/15 10:20:57 DEBUG : &{test/pc1.txt (rw)}: >Flush: err=<nil>
2020/03/15 10:20:57 DEBUG : &{test/pc1.txt (rw)}: Release: 
2020/03/15 10:20:57 DEBUG : test/pc1.txt(0xc0000ba2c0): RWFileHandle.Release closing
2020/03/15 10:20:57 DEBUG : test/pc1.txt(0xc0000ba2c0): close: 
2020/03/15 10:20:57 DEBUG : test/pc1.txt: File.delWriter couldn't find handle
2020/03/15 10:20:57 DEBUG : test/pc1.txt: Attr: 
2020/03/15 10:20:57 DEBUG : test/pc1.txt: >Attr: a=valid=1s ino=0 size=270 mode=-rw-r--r--, err=<nil>
2020/03/15 10:20:57 DEBUG : test/pc1.txt: Size and modification time the same (differ by -528.901µs, within tolerance 1ms)
2020/03/15 10:20:57 DEBUG : test/pc1.txt: Unchanged skipping
2020/03/15 10:20:57 DEBUG : test/pc1.txt: transferred to remote
2020/03/15 10:20:57 DEBUG : test/pc1.txt(0xc0000ba2c0): >close: err=<nil>
2020/03/15 10:20:57 DEBUG : &{test/pc1.txt (rw)}: >Release: err=<nil>
2020/03/15 10:20:57 DEBUG : test/pc1.txt: Setattr: a=Setattr [ID=0x2bc Node=0xf Uid=1000 Gid=1000 Pid=7598] mode=-rw-rw-r-- handle=INVALID-0x0
2020/03/15 10:20:57 DEBUG : test/pc1.txt: >Setattr: err=<nil>
2020/03/15 10:20:57 DEBUG : test/pc1.txt: Attr: 
2020/03/15 10:20:57 DEBUG : test/pc1.txt: >Attr: a=valid=1s ino=0 size=270 mode=-rw-r--r--, err=<nil>
2020/03/15 10:20:57 DEBUG : test/pc1.txt: Setattr: a=Setattr [ID=0x2be Node=0xf Uid=1000 Gid=1000 Pid=7598] atime=2020-03-15 10:20:56.504 +0000 GMT mtime=2020-02-17 13:48:19.180577 +0000 GMT handle=INVALID-0x0
2020/03/15 10:20:57 DEBUG : test/pc1.txt: >Setattr: err=<nil>
2020/03/15 10:20:57 DEBUG : test/pc1.txt: Attr: 
2020/03/15 10:20:57 DEBUG : test/pc1.txt: >Attr: a=valid=1s ino=0 size=270 mode=-rw-r--r--, err=<nil>
```

The file on the remote has the upload time as modified time.
I Unmount and remount the remote , it appears the cache attempts to set atime again.

`2020/03/15 10:24:05 DEBUG : test/pc1.txt: updateTime: setting atime to 2020-02-17 13:48:19.180577 +0000 GMT`

The time is still incorrect on the file.

The remote appears to support setting the modification time when using "rclone copy or sync"
example

```
rclone copy pc1.txt Koofr:test/ -vv
2020/03/15 10:26:18 DEBUG : rclone: Version "v1.51.0-099-gdc069737-beta" starting with parameters ["rclone" "copy" "pc1.txt" "Koofr:test/" "-vv"]
2020/03/15 10:26:18 DEBUG : Using config file from "/home/glc/.config/rclone/rclone.conf"
2020/03/15 10:26:18 DEBUG : pc1.txt: Need to transfer - File not found at Destination
2020/03/15 10:26:21 DEBUG : pc1.txt: MD5 = 5e641715584068c05138decfac72281e OK
2020/03/15 10:26:21 INFO  : pc1.txt: Copied (new)
2020/03/15 10:26:21 INFO  : 
Transferred:   	       270 / 270 Bytes, 100%, 87 Bytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         3.0s
```
The modified time is correct in this scenario.

**Comment by ncw** [comment]
The problem is that Koofr doesn't support setting the modification time of an existing file, you have to delete it and re-upload it.

When `rclone copy` uploads a file it knows the modification time at the start and uploads it with the file.

However when you use `mv` to copy a file into the mount, the modification time is set at the end **after** the file has been uploaded. Rclone can't set the modification time at this point :-(

Here rclone chooses to do nothing rather than re-upload the file.

**Comment by amigagamer** [comment]
Thanks for the explination @ncw 

I've read some of the discussions about "delayed write cache" #2327 #3186 
Perhaps in the future if something like this is implemented , the atime could be set correctly in the cache before the cloud transfer begins??

**Comment by ncw** [comment]
Yes a delayed write cache would fix the problem here, you are right :-)

**Comment by jkmcnk** [comment]
fwiw, this will be fixed once I get the REST API call for setting mtimes post-upload on Koofr side through the development-testing pipeline. no promises on when this happens, though. ;)
