### ISSUE TITLE
Supported copy signal file of Google Drive shared link or not

### ISSUE THREAD

**Issue by April-BOY** [rclone/rclone#4078]
#### Output of `rclone version`
![image](https://user-images.githubusercontent.com/19245482/76974833-a7c03f00-696c-11ea-8c64-3122fa64e5c5.png)
#### Describe the issue
I had used ‘rclone copyurl’ command to copy a file（not a folder）of Google Drive，but I got a problem.I have no idea how to do with it.Can you give me some suggests?
THE LINK：https://drive.google.com/file/d/1uppQdohmdMYGmPluh2rs9XtzjmOqScb1/view
![rclone复制单文件报错信息](https://user-images.githubusercontent.com/19245482/76975586-b78c5300-696d-11ea-9837-7b648dd7a813.png)

**Comment by animosity22** [comment]
Please don't post links to copyrighted content.

If you have a use case question, please use the forums as this is more for defects/bugs/etc.
