### ISSUE TITLE
Support S3 storage_class on Scaleway

### ISSUE THREAD

**Issue by BobVul** [rclone/rclone#4079]
Scaleway now supports a `GLACIER` storage class: https://www.scaleway.com/en/docs/object-storage-glacier/

Currently, rclone only exposes the `storage_class` s3 config option on [AWS](https://github.com/rclone/rclone/blob/36717c7d9828420b40de2846ea2931e79efc5d55/backend/s3/s3.go#L667) and [Alibaba](https://github.com/rclone/rclone/blob/36717c7d9828420b40de2846ea2931e79efc5d55/backend/s3/s3.go#L697) providers.

Please consider exposing it either for the Other provider or for a new Scaleway provider.

**Comment by ncw** [comment]
Adding a scaleway provider would be easy enough.

Do you want to have a go at this @BobVul

**Comment by BobVul** [comment]
I suppose I can give it a shot. Might take a bit, I don't have a Go environment yet, will need to look into that first.

**Comment by ncw** [comment]
Great! Let me know if you get stuck.

**Comment by ankur0493** [comment]
@BobVul Have you started working on this? If not, I can give it a shot. I haven't worked with Scaleway, but integrating with a SDK should be easy.
Their GO SDK seems to still be in beta: https://github.com/scaleway/scaleway-sdk-go

@ncw  Should we wait until they come out with a GA release?

Also, with which email ID do we register for API keys?

**Comment by BobVul** [comment]
Unfortunately haven't had a chance yet. It's been a surprisingly busy couple weeks.

I was intending to just pass extra options via a specialisation of the s3 provider, the same way Amazon and Alibaba have them e.g. https://github.com/rclone/rclone/blob/36717c7d9828420b40de2846ea2931e79efc5d55/backend/s3/s3.go#L667

Wasn't intending to integrate a new SDK.

**Comment by ankur0493** [comment]
>  was intending to just pass extra options via a specialisation of the s3 provider, the same way Amazon and Alibaba have them e.g.

But in order to that, you have to have a `safeway` backend first. Unless I am missing something.

**Comment by ncw** [comment]
I'd rather not have another backend if we can use the s3 backend. Maintaining backends is hard work!

I was imagining a bit of customisation of the s3 backend like has been done already for Alibaba etc.

**Comment by BobVul** [comment]
Oh wow... this completely slipped my mind, sorry!

Looks like PR #4340 would've fixed this.
