### ISSUE TITLE
rclone mount: unable to read obscured config key and unable to delete the temp file

### ISSUE THREAD

**Issue by ceuk** [rclone/rclone#4081]
Helloo, sorry to bother, been trying to fix for days now though and no luck

#### What is the problem you are having with rclone?

Typing e.g. `rclone mount google:notes /media/notes --daemon`

Gives me: 
                         
```bash
unable to read obscured config key and unable to delete the temp file: open /tmp/rclone575239279: no such file or directory
```

#### What is your rclone version (output from `rclone version`)
1.51.0

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Arch 

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount (with encrypted config)

**Comment by ceuk** [comment]
When I unencrypt my configuration it seems to start working

**Comment by ncw** [comment]
Can you try without --daemon? I think that will probably work

I tried to replicate this locally with ubuntu 19.10 and failed, so I suspect something unique about your setup.

I suspect something is wrong with writing to your temporary directory.  You can try setting a new one with `export TMPDIR=/path` and see if that makes a difference.

**Comment by ceuk** [comment]
Yeah running without --daemon does the trick, it also works with --daemon after that, I'll just use the TMPDIR workaround if it happens again - cheers :)
