### ISSUE TITLE
--delete-(before,during,after) options not working

### ISSUE THREAD

**Issue by franzinc** [rclone/rclone#4082]
#### What is the problem you are having with rclone?

Deletions are not happening on the destination.

#### What is your rclone version (output from `rclone version`)

rclone v1.51.0-094-gfdb07f2f-beta
- os/arch: linux/amd64
- go version: go1.14

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

CentOS Linux release 7.7.1908, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Backblaze B2

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone -vv --delete-before --transfers=1 --bwlimit=45M sync --files-from "/tmp/replicate-backups.tmp" /backups/ b2:franz-backup0`

Also tested with '--delete-after'.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

I won't paste the entire log, as it's lengthy and holds sensitive network info, but here's the meat:

2020/03/19 10:17:02 DEBUG : rclone: Version "v1.51.0-094-gfdb07f2f-beta" starting with parameters ["/usr/local/bin/rclone" "-vv" "--delete-before" "--transfers=1" "--bwlimit=45M" "sync" "--files-from" "/tmp/replicate-backups.tmp" "/backups/" "b2:franz-backup0"]
2020/03/19 10:17:02 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2020/03/19 10:17:02 INFO  : Starting bandwidth limiter at 45MBytes/s
2020/03/19 10:17:02 DEBUG : Waiting for deletions to finish
2020/03/19 10:17:02 DEBUG : .bash_history: Excluded
2020/03/19 10:17:04 DEBUG : B2 bucket franz-backup0: Waiting for checks to finish
2020/03/19 10:17:04 DEBUG : B2 bucket franz-backup0: Waiting for transfers to finish
2020/03/19 10:18:02 INFO  :
Transferred:      243.090M / 103.407 GBytes, 0%, 4.131 MBytes/s, ETA 7h6m13s
Checks:                26 / 26, 100%
Transferred:            0 / 62, 0%
Elapsed time:        58.8s
Transferring:
 * filelocker/2020-03-16-…-backup-client-dump.gz:  6% /3.495G, 5.300M/s, 10m29s

2020/03/19 10:19:02 INFO  :
Transferred:      579.090M / 103.407 GBytes, 1%, 4.873 MBytes/s, ETA 6h12s
Checks:                26 / 26, 100%
Transferred:            0 / 62, 0%
Elapsed time:      1m58.8s
Transferring:
 * filelocker/2020-03-16-…-backup-client-dump.gz: 16% /3.495G, 5.662M/s, 8m49s

...

2020/03/19 21:22:11 INFO  :
Transferred:      132.913G / 132.913 GBytes, 100%, 3.410 MBytes/s, ETA 0s
Checks:                26 / 26, 100%
Transferred:           62 / 62, 100%
Elapsed time:    11h5m7.6s

2020/03/19 21:22:11 DEBUG : 10 go routines active

**Comment by ncw** [comment]
I suspect this is because you are using `--files-from`. Rclone will only consider files in the files from list.

If you want rclone to delete any files which aren't in the `--files-from` list then you need `--delete-excluded` - try with --dry-run first!

What are you trying to achieve with the `--files-from`? How does that list get made?

**Comment by franzinc** [comment]
Yep, you're right, I tested a bit more and it is related to '--files-from'.

I had expected it to not take into account the other files on the filesystem when making a delete decision; only those directly involved in the sync.

At anyrate, it looks like using '--delete-excluded' is exactly the change in behavior I want.

Thanks so much for the help! :)

**Comment by ncw** [comment]
> At anyrate, it looks like using '--delete-excluded' is exactly the change in behavior I want.

Be careful with that flag, it is super dangerous! Anyway, glad it is what you wanted.
