### ISSUE TITLE
Add arm docker images

### ISSUE THREAD

**Issue by NorthIsUp** [rclone/rclone#4086]
#### What is your current rclone version (output from `rclone version`)?

all

#### What problem are you are trying to solve?

run rclone on k3s on a raspberry pi cluster

#### How do you think rclone should be changed to solve that?

add arm docker builds

**Comment by ncw** [comment]
Sounds like a good idea! How is it done? Any idea? The builds are auto built by docker hub.

**Comment by NorthIsUp** [comment]
Probably need to make another docket file that starts with `FROM alpine:arm` or something similar.

**Comment by negative0** [comment]
According to the link here, https://hub.docker.com/_/alpine, it should be `FROM arm64v8/alpine:3.7` OR `FROM arm64v8/alpine:latest`

**Comment by natelandau** [comment]
a multiarch docker image with multiple arm versions (not just 64bit) would be great.  running a cluster of pis running Armv7 and would love to run rclone

**Comment by philips** [comment]
I researched this a bit and it seems that docker hub has no automation to do this automatically.

However, docker desktop has a year old beta feature that enables ARM builds and pushes to docker hub: https://www.docker.com/blog/multi-arch-images/

**Comment by thaJeztah** [comment]
I think @tonistiigi has a blog or demo to build multi-arch images with buildkit

**Comment by ncw** [comment]
I found an article about [cross compiling with docker](https://medium.com/@carlosedp/cross-building-arm64-images-on-docker-desktop-254d1e0bc1f9)

From that it looks like rclone existing Dockerfile would "just work" with `docker buildx`.

**Comment by philips** [comment]
I can confirm with a minor tweak the current Dockerfile works fine with ARM: https://github.com/rclone/rclone/pull/4122

**Comment by ncw** [comment]
@philips so presumably you built the docker image on an ARM machine?

What I'd really like to do is work out how to build an ARM docker image on a linux machine.... Perhaps `docker buildx` is the solution?

**Comment by tiborvass** [comment]
@ncw if you want a Dockerfile for Go that works for both native compiling and cross compiling I use the following:

```
FROM --platform=$BUILDPLATFORM golang
COPY --from=tonistiigi/xx:golang / /

ARG TARGETPLATFORM
RUN go env
```

To cross build this for arm64 on x86: `docker build --platform linux/arm64 .` but you won't be able to run it, only push it.

One good reason to use buildx, is to build multiarch images: `docker buildx build --platform linux/amd64,linux/arm64 -t rclone/rclone --push .` will push a multi-arch image to rclone/rclone on Docker hub.

**Comment by philips** [comment]
On Wed, Apr 15, 2020 at 10:05 AM Nick Craig-Wood <notifications@github.com>
wrote:

> @philips <https://github.com/philips> so presumably you built the docker
> image on an ARM machine?
>
Yes

> What I'd really like to do is work out how to build an ARM docker image on
> a linux machine.... Perhaps docker buildx is the solution?
>

@tiborvass is an expert and I agree with his recommendations. If you have
access to a Mac/Windows machine with docker desktop I think buildx would be
a good way to build the releases.

https://quay.io/repository/philips/rclone-arm
<https://quay.io/repository/philips/rclone-arm?tag=latest&tab=tags> is
working fine for me ATM

**Comment by ncw** [comment]
Thankyou @tiborvass and @philips for your info.

I managed to install `docker buildx` on my linux laptop so it probably wouldn't be too hard to make sure it is installed on the GitHub actions builder which is where I'd really like to be doing the builds from....

I will have an experiment!

**Comment by philips** [comment]
@ncw just be aware that installing buildx isn't enough. You need to also have an ARM builder hooked up to buildx AFAICT. This is something that the Docker Desktop does for you on Win/macOS.

I don't have access to Linux that allows binfmt to do this but there are tutorials for setting it up: https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/getting-started-with-docker-for-arm-on-linux

**Comment by ncw** [comment]
With the help of @ilteoood fantastic pull request #4285 we've now implemented this. So you should be able to pull an ARM docker image now :-)

I'll make an image for the stable version when I release v1.52.1 but for now it is only the `beta` tag

![image](https://user-images.githubusercontent.com/536803/83429187-96df7f80-a42b-11ea-9f5a-e9699c81ee3b.png)
