### ISSUE TITLE
union: integration test failures

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#4088]
There are a few integration test failiures for the new union backend: https://pub.rclone.org/integration-tests/current/

![image](https://user-images.githubusercontent.com/536803/77412584-fbd88280-6db5-11ea-964f-6bc91b730ad1.png)

Have you got time to take a look @Max-Sum ? Thanks

**Comment by ivandeex** [comment]
@ncw  I believe this has been fixed

**Comment by ivandeex** [comment]
not a problem anymore
