### ISSUE TITLE
x-amz-meta-md5chksum of S3 for Tencent COS

### ISSUE THREAD

**Issue by sherlock99** [rclone/rclone#4094]
#### Output of `rclone version`
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7

#### Describe the issue

I use rclone copy -c from a ftp to aws S3. But I can not see any metadata of the files in S3.
I need all the files uploaded to S3 with x-amz-meta-md5chksum, How can I make this happen?
Both big files and small files.

Thanks in advance.

**Comment by ncw** [comment]
For files without x-amz-meta-md5chksum the Etag contains the md5 checksum.

You can use `rclone md5sum` to read the md5sum from either.

**Comment by sherlock99** [comment]
> For files without x-amz-meta-md5chksum the Etag contains the md5 checksum.
> 
> You can use `rclone md5sum` to read the md5sum from either.

In fact I am using Tencent Cloud COS for this situation. For Tencent Cloud COS, the Etag is not the md5 checksum. So I need the x-amz-meta-md5chksum attached when files are uploaded.

**Comment by ncw** [comment]
I see.

That would be quite easy to do - if you changed that if to be unconditional it would probably do what you want.

https://github.com/rclone/rclone/blob/ff0a299bfb4bbe9abb11b3f9dfdcf91a2a88b59c/backend/s3/s3.go#L2332-L2334

What do ETags look like on Tencent Cloud COS?

Maybe the thing to do would be to make a `Tencent` provider? It could provide that work around and make some configuration defaults.

Are you interested in working on that?

**Comment by XVilka** [comment]
@sherlock99 please retry with the master branch, specifically after the https://github.com/rclone/rclone/commit/22937e8982e2cebee1b7d955be4f7469d8d4df52 commit.

**Comment by ncw** [comment]
I'm going to assume this is fix. Will re-open if necessary!
