### ISSUE TITLE
Files not correctly moved to Teamdrive

### ISSUE THREAD

**Issue by Friday13th87** [rclone/rclone#4095]
#### What is the problem you are having with rclone?
Moving Files to TeamDrive is not working from time to time and the files are gone afterwards

#### What is your rclone version (output from `rclone version`)
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian Buster stable

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive and Google Team Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone move /local/path team:/team/path --log-file /local/logs/team.log -v --exclude-from /path/to/excludes --delete-empty-src-dirs --user-agent team --fast-list --max-transfer 100G --drive-stop-on-upload-limit --transfers 2

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2020/03/27 10:46:17 INFO  : /local/path/to/file: Copied (new)
2020/03/27 10:46:17 INFO  : /team/path/to/file: Deleted

So from time to time the rclone log tells me that certain files moved correctly to the team drive, but checking the actual team drive (via rclone mount and webside and after waiting some time) says that those files are not there actually.
The really bad thing is, that those files are completley gone, as they are deleted on the local machine, not availible at the Team Drive and they are not in any trash at the TeamDrive

is it something with the --fast-list command as i read there have been some issues with it but as i thought they are gone i was using last-list for the moves.

**Comment by Friday13th87** [comment]
I was updating to the latest beta version and had no issues since then.
maybe it was the "--drive-stop-on-upload" flag which was changed or its because i am using the new soft cutoff method now... i dont know but as i said, i hade no issues since then
thanks for your great work

**Comment by ncw** [comment]
I'd be really suprised if the files were missing completely.

Sometimes teamdrives take a while to catch up with their directory listings - how does it look now?

**Comment by animosity22** [comment]
Since there are no updates, I'm closing this out.

If you still have a question, please raise it on https://forums.rclone.org
