### ISSUE TITLE
Support new Google Drive shortcuts

### ISSUE THREAD

**Issue by ferferga** [rclone/rclone#4098]
So it seems that Google Drive finally deprecated the "Add to My Drive" option and replaced it with a better feature: shortcuts.

Currently, rclone ignores them completely.

There is more information about it in [the GSuite blog](https://gsuiteupdates.googleblog.com/2019/08/drive-shortcuts-beta.html), as the feature first rolled out to GSuite customers, but now is being [rolled out to all the accounts](https://www.androidpolice.com/2020/03/27/google-drive-file-shortcuts/). I've got them in my account, so I can help with testing if needed.

EDIT: Just found that [this has been discussed in the forums](https://forum.rclone.org/t/fyi-sep-30-new-google-drive-shortcuts-and-folder-structure/15197/6)

**Comment by ncw** [comment]
Shortcuts are currently missing from the Go SDK.  I made an issue about that here: https://github.com/googleapis/google-api-go-client/issues/464 then another issue here: https://issuetracker.google.com/issues/152865050

As soon as shortcuts hit the Go SDK then I can implement them!

In the mean time, let's discuss how they should work.

I propose that by default
- shortcuts should be de-referenced and read the original files
- there might be a flag to ignore shortcuts

Note that we can't translate these to and from symlinks in a meaningful way as conceptually these are much more like hardlinks (linking to the inode) so we don't know where in a directory tree the destination might be.

**Comment by hardlick** [comment]
+1

**Comment by ferferga** [comment]
@ncw That's the best way to go in my opinion as well.

**Comment by ncw** [comment]
My bug on the google issue tracker has been accepted and it looks like the shortcuts have arrived in the Go SDK :-)

Time for a bit of coding...

**Comment by ncw** [comment]
I've had a go at this - please give it a whirl and report back

https://beta.rclone.org/branch/v1.51.0-163-g8b5786ab-fix-4098-drive-shortcuts-beta/ (uploaded in 15-30 mins)

**Comment by agudelotmateo** [comment]
> I've had a go at this - please give it a whirl and report back
> 
> https://beta.rclone.org/branch/v1.51.0-163-g8b5786ab-fix-4098-drive-shortcuts-beta/ (uploaded in 15-30 mins)
I'm getting 404. Trying to user the browser and no luck either (latest is _v1.51.0-160-g424554bc-beta_). I'd be testing the feature right away. Thank you.

**Comment by ncw** [comment]
OK that turned out to be a lot harder than I anticipated!

https://beta.rclone.org/branch/v1.51.0-163-gf22af086-fix-4098-drive-shortcuts-beta/ (uploaded in 15-30 mins)

Here are the docs I had to make for it

### Shortcuts ###

In March 2020 Google introduced a new feature in Google Drive called [drive shortcuts](https://support.google.com/drive/answer/9700156) ([API](https://developers.google.com/drive/api/v3/shortcuts)). These will (by September 2020) [replace the ability for files or folders to be in multiple folders at once](https://cloud.google.com/blog/products/g-suite/simplifying-google-drives-folder-structure-and-sharing-models).

Shortcuts are files that link to other files on Google Drive somewhat like a symlink in unix, except they point to the underlying file data (eg the inode in unix terms) so they don't break if the source is renamed or moved about.

Be default rclone treats these as follows.

For shortcuts pointing to files:

- When listing a file shortcut appears as the destination file.
- When downloading the contents of the destination file is downloaded.
- When updating shortcut file with a non shortcut file, the shortcut is removed then a new file is uploaded in place of the shortcut.
- When server side moving (renaming) the shortcut is renamed, not the destination file.
- When server side copying the shortcut is copied, not the contents of the shortcut.
- When deleting the shortcut is deleted not the linked file.
- When setting the modification time, the modification time of the linked file will be set.

For shortcuts pointing to folders:

- When listing the shortcut appears as a folder and that folder will contain the contents of the linked folder appear (including any sub folders)
- When downloading the contents of the linked folder and sub contents are downloaded
- When uploading to a shortcut folder the file will be placed in the linked folder
- When server side moving (renaming) the shortcut is renamed, not the destination folder
- When server side copying the contents of the linked folder is copied, not the shortcut.
- When deleting with `rclone rmdir` or `rclone purge` the shortcut is deleted not the linked folder.
- **NB** When deleting with `rclone remove` or `rclone mount` the contents of the linked folder will be deleted.

It isn't currently possible to create shortcuts with rclone.

Shortcuts can be completely ignored with the `--drive-skip-shortcuts` flag
or the corresponding `skip_shortcuts` configuration setting.

**Comment by ncw** [comment]
Hopefully this one will actually build - sorry!

https://beta.rclone.org/branch/v1.51.0-171-g5d91b677-fix-4098-drive-shortcuts-beta/ (uploaded in 15-30 mins)

**Comment by agudelotmateo** [comment]
I just tested and it doesn't work. Some of the files it doesn't detect the m in the origin folder, but for the ones it does detect, the shortcut (not an actual copy of the file the shortcut points to) is created in the destination. Also, the logs shows errors and claims to not recognize the document type (visual bug?). Here's the log:
`2020/04/15 18:46:55 DEBUG : rclone: Version "v1.51.0-171-g5d91b677-fix-4098-drive-shortcuts-beta" starting with parameters ["rclone" "--config" "./rclone.conf" "copy" "--drive-server-side-across-configs" "--rc" "--rc-addr=localhost:5573" "-vv" "--ignore-existing" "--tpslimit" "3" "--transfers" "3" "--drive-chunk-size" "32M" "--drive-acknowledge-abuse" "--log-file=log_rclone.txt" "src020:test.mkv" "dst020:test"]
2020/04/15 18:46:55 NOTICE: Serving remote control on http://127.0.0.1:5573/
2020/04/15 18:46:55 DEBUG : Using config file from "/home/mateo/rclone.conf"
2020/04/15 18:46:55 INFO  : Starting HTTP transaction limiter: max 3 transactions/s with burst 1
2020/04/15 18:47:00 DEBUG : test.mkv: Need to transfer - File not found at Destination
2020/04/15 18:47:01 DEBUG : test.mkv: Ignoring unknown document type "application/vnd.google-apps.shortcut"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xa0e8c4]

goroutine 1 [running]:
github.com/rclone/rclone/fs/operations.Copy(0x1ab22e0, 0xc0001a6020, 0x1ac44a0, 0xc00018b380, 0x0, 0x0, 0x7fffd8333da6, 0x8, 0x1ac4520, 0xc0003ea680, ...)
	/home/runner/work/rclone/src/github.com/rclone/rclone/fs/operations/operations.go:375 +0x1814
github.com/rclone/rclone/fs/operations.moveOrCopyFile(0x1ab22e0, 0xc0001a6020, 0x1ac44a0, 0xc00018b380, 0x1ac44a0, 0xc00018a340, 0x7fffd8333da6, 0x8, 0x7fffd8333da6, 0x8, ...)
	/home/runner/work/rclone/src/github.com/rclone/rclone/fs/operations/operations.go:1876 +0x660
github.com/rclone/rclone/fs/operations.CopyFile(...)
	/home/runner/work/rclone/src/github.com/rclone/rclone/fs/operations/operations.go:1894
github.com/rclone/rclone/cmd/copy.glob..func1.1(0xc0007c2520, 0xc000237b10)
	/home/runner/work/rclone/src/github.com/rclone/rclone/cmd/copy/copy.go:83 +0xef
github.com/rclone/rclone/cmd.Run(0xc0000b0101, 0x25c4860, 0xc000237d38)
	/home/runner/work/rclone/src/github.com/rclone/rclone/cmd/cmd.go:242 +0xc6
github.com/rclone/rclone/cmd/copy.glob..func1(0x25c4860, 0xc0000b2240, 0x2, 0x11)
	/home/runner/work/rclone/src/github.com/rclone/rclone/cmd/copy/copy.go:79 +0x129
github.com/rclone/rclone/vendor/github.com/spf13/cobra.(*Command).execute(0x25c4860, 0xc0000b2120, 0x11, 0x12, 0x25c4860, 0xc0000b2120)
	/home/runner/work/rclone/src/github.com/rclone/rclone/vendor/github.com/spf13/cobra/command.go:844 +0x29d
github.com/rclone/rclone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x25c0c00, 0x5e979cef, 0x25d93c0, 0xc000182058)
	/home/runner/work/rclone/src/github.com/rclone/rclone/vendor/github.com/spf13/cobra/command.go:945 +0x317
github.com/rclone/rclone/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/rclone/src/github.com/rclone/rclone/vendor/github.com/spf13/cobra/command.go:885
github.com/rclone/rclone/cmd.Main()
	/home/runner/work/rclone/src/github.com/rclone/rclone/cmd/cmd.go:511 +0x92
main.main()
	/home/runner/work/rclone/src/github.com/rclone/rclone/rclone.go:14 +0x20`

**Comment by darthShadow** [comment]
For the copying of the shortcut, that's probably as expected according to the documentation above:
> When server side copying the shortcut is copied, not the contents of the shortcut.

**Comment by ncw** [comment]
@agudelotmateo thanks for testing :-)

> Some of the files it doesn't detect them in the origin folder

What does the log look like for that?

> but for the ones it does detect, a copy of the shortcut (not an actual copy of the file the shortcut points to) is created in the destination

That is what I said it would do above - a server side copy will copy the shortcut, not the contents of the shortcut.

That could be changed - I'm not sure what people expect though.

Thanks for the traceback - I've managed to reproduce that - I'll fix it tomorrow :-)

To reproduce a server side copy of an object is needed

    rclone copyto -vv drive:/test/"file2 shortcut copy 2.txt"  drive:/test/"file2 shortcut copy 4.txt"

**Comment by ncw** [comment]
OK I've fixed the above problem...

Can you have a go with this please

https://beta.rclone.org/branch/v1.51.0-228-g24c38023-fix-4098-drive-shortcuts-beta/ (uploaded in 15-30 mins)

**Comment by 88lex** [comment]
Using 228 for some light testing. Overall working very nicely.

Shared a folder from TD:test to MD:test. Visible in rclone ls and rclone mounts.
Added the folder to Emby via the MD:test share. Emby scans and streams nicely. Same as for files in MD:
Emby adds nfo/jpg files to the rclone mount and the files flow back to TD:test as expected.
rclone copy MD:test to MD:test2 copies full files to test2, as expected.

BUG/Missing functionality:
rclone copy MD:test/subfolder to MD:test2/subfolder fails with file not found 404 error.
Doesn't appear to be able to traverse/see the subfolder as a source, even though it is doing so when copying from root of the shortcut.

QUESTION:
When you say 
`It isn't currently possible to create shortcuts with rclone.`
I suppose that means that at present we cannot force rclone to create ALL shortcuts in the destination, correct?  
For example, when copying MD:test to MD:test2 we cannot force it to copy all of the contents into test2 as shortcuts.

Beautiful, quick implementation of a brand new google feature! As always, thank you!

**Comment by ncw** [comment]
> Using 228 for some light testing. Overall working very nicely.

Great!

> Shared a folder from TD:test to MD:test. Visible in rclone ls and rclone mounts.
> Added the folder to Emby via the MD:test share. Emby scans and streams nicely. Same as for files in MD:
> Emby adds nfo/jpg files to the rclone mount and the files flow back to TD:test as expected.
> rclone copy MD:test to MD:test2 copies full files to test2, as expected.

Good

> BUG/Missing functionality:
> rclone copy MD:test/subfolder to MD:test2/subfolder fails with file not found 404 error.
> Doesn't appear to be able to traverse/see the subfolder as a source, even though it is doing so when copying from root of the shortcut.

Well spotted, I fixed that now!

> QUESTION:
> When you say
> `It isn't currently possible to create shortcuts with rclone.`
> I suppose that means that at present we cannot force rclone to create ALL shortcuts in the destination, correct?
> For example, when copying MD:test to MD:test2 we cannot force it to copy all of the contents into test2 as shortcuts.

Not yet.

I'm planning a backend command something like this to create a shortcut

    rclone backend shortcut drive: source/path dest/path

With an optional -target parameter

    rclone backend shortcut drive: source/path -o target=otherremote: dest/path

> Beautiful, quick implementation of a brand new google feature! As always, thank you!

:-)

Here is the fixed version

https://beta.rclone.org/branch/v1.51.0-259-gc2e0b827-fix-4098-drive-shortcuts-beta/ (uploaded in 15-30 mins)

How badly to people want this for 1.52? I'd like to take the time to implement the backend shortcut command and write some tests, but I could merge it now in time for 1.52 and do those things later.

Thoughts?

**Comment by ferferga** [comment]
I would say that 1.52 should be out as soon as possible as it packs many fixes for huge issues (like the one with dedupe and size) and the first aim at supporting shortcuts. You can expand the functionality of them later, otherwise you will always end up in a loop holding the update "because something's missing". I think it's better to get done slowly, but eventually 🥳😉.

**Comment by tomyang001** [comment]
> > Using 228 for some light testing. Overall working very nicely.
> 
> Great!
> 
> > Shared a folder from TD:test to MD:test. Visible in rclone ls and rclone mounts.
> > Added the folder to Emby via the MD:test share. Emby scans and streams nicely. Same as for files in MD:
> > Emby adds nfo/jpg files to the rclone mount and the files flow back to TD:test as expected.
> > rclone copy MD:test to MD:test2 copies full files to test2, as expected.
> 
> Good
> 
> > BUG/Missing functionality:
> > rclone copy MD:test/subfolder to MD:test2/subfolder fails with file not found 404 error.
> > Doesn't appear to be able to traverse/see the subfolder as a source, even though it is doing so when copying from root of the shortcut.
> 
> Well spotted, I fixed that now!
> 
> > QUESTION:
> > When you say
> > `It isn't currently possible to create shortcuts with rclone.`
> > I suppose that means that at present we cannot force rclone to create ALL shortcuts in the destination, correct?
> > For example, when copying MD:test to MD:test2 we cannot force it to copy all of the contents into test2 as shortcuts.
> 
> Not yet.
> 
> I'm planning a backend command something like this to create a shortcut
> 
> ```
> rclone backend shortcut drive: source/path dest/path
> ```
> 
> With an optional -target parameter
> 
> ```
> rclone backend shortcut drive: source/path -o target=otherremote: dest/path
> ```
> 
> > Beautiful, quick implementation of a brand new google feature! As always, thank you!
> 
> :-)
> 
> Here is the fixed version
> 
> https://beta.rclone.org/branch/v1.51.0-259-gc2e0b827-fix-4098-drive-shortcuts-beta/ (uploaded in 15-30 mins)
> 
> How badly to people want this for 1.52? I'd like to take the time to implement the backend shortcut command and write some tests, but I could merge it now in time for 1.52 and do those things later.
> 
> Thoughts?

This version works fine with me to mount and read files within the directory shortcuts. Please merge it into 1.52 so it could help a lot of people who need this missing function.

**Comment by darthShadow** [comment]
Plus, there's always the possibility of point releases if there are any critical bugs discovered in the tests or enough folks want the backend command.

**Comment by 88lex** [comment]
I'd agree with the idea of including the current functionality in 1.52

The ability to mount and read with shortcuts is by itself a great option for users. :-)

**Comment by 88lex** [comment]
> > BUG/Missing functionality:
> > rclone copy MD:test/subfolder to MD:test2/subfolder fails with file not found 404 error.
> > Doesn't appear to be able to traverse/see the subfolder as a source, even though it is doing so when copying from root of the shortcut.
> 
> Well spotted, I fixed that now!
> 
> Here is the fixed version
> 
> https://beta.rclone.org/branch/v1.51.0-259-gc2e0b827-fix-4098-drive-shortcuts-beta/ (uploaded in 15-30 mins)
> 

Fixed! Thank you. The traversing works in 259 as expected - can list, copy sync files below root in a tree.

Question: 
> For shortcuts pointing to files:
> * When server side copying the shortcut is copied, not the contents of the shortcut.

Using 259:  When copying a single file within a folder that was 'shortcut linked' into My Drive `rclone copy` creates a new file in the destination rather than a link.  

This is correct/expected behavior, yes?  I can see cases for either method, but given link-creation is not possible yet it makes perfect sense :-)

**Comment by ncw** [comment]
> This is correct/expected behavior, yes? I can see cases for either method, but given link-creation is not possible yet it makes perfect sense :-)

I think by the time rclone has looked into the directory to find the file all it sees is a normal file at that point, so it is copied as a normal file.

So yes, I think that is the correct behaviour. I'm not sure I've done a good enough job of explaining it though!

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

Thanks for all your help testing :-)

**Comment by ncw** [comment]
Oops forgot the issue tag...

This is the commit

f2b1fedc4fd064a98de68a0f0d5afef5bc4e6012

**Comment by 88lex** [comment]
NOTE: 
Created a shortcut from google:test to shareddrive:test
Added subfolder shareddrive:test/sample with subfolders and files
All appears correctly as links inside the shortcut, google:test
Ran `rclone delete google:test/sample` which deletes both the shortcuts in google:test/sample and the underlying files in shareddrive:test/sample.  
This is expected behavior by default, at the moment.

If the api allows (?) perhaps a --shortcuts-only flag would be handy ?

**Comment by darthShadow** [comment]
Considering the various ways this change can cause unexpected changes, like the one mentioned above, I think we need to add a section on the website that explains the behaviour of shortcuts and how they would affect and work in different scenarios.

**Comment by 88lex** [comment]
> I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52
> 
> Thanks for all your help testing :-)

Wonderful! re merging to master/beta. Will save me a couple of manual installs :-)

And my pleasure re the testing. rclone is the bees knees.

**Comment by ncw** [comment]
> Created a shortcut from google:test to shareddrive:test
> Added subfolder shareddrive:test/sample with subfolders and files
> All appears correctly as links inside the shortcut, google:test
> Ran `rclone delete google:test/sample` which deletes both the shortcuts in google:test/sample and the underlying files in shareddrive:test/sample.
> This is expected behavior by default, at the moment.

Once rclone has looked inside a shortcut to a directory it is like it is in that directory. The same thing happens if you click on a shortcut in the drive web interface - it will put you into the directory.

It is quite dificult to work around this since at the point we are in the pointed to directory we've lost the knowledge that it was pointed to by a shortcut. A `mount bind` would work the same way on Linux.

**Comment by 88lex** [comment]
> It is quite dificult to work around this since at the point we are in the pointed to directory we've lost the knowledge that it was pointed to by a shortcut. A `mount bind` would work the same way on Linux.

Wait. You actually have to code things and use apis?  I thought all of this was magic. :-)

If I understand what you are saying if files are inside a shortcutted folder then rclone sees something akin to this:

  - shortcut2Folder
    - actualSubfolder
      - actual file1
    - actualfile2
    - actualfile3

**Comment by ncw** [comment]
> Wait. You actually have to code things and use apis? I thought all of this was magic. :-)

:laughing: 

> If I understand what you are saying if files are inside a shortcutted folder then rclone sees something akin to this:
> 
> * shortcut2Folder
>   
>   * actualSubfolder
>     
>     * actual file1
>   * actualfile2
>   * actualfile3

That is right. As soon as you've look through a shortcut to a folder everything is real...

**Comment by calisro** [comment]
Is there another issue/pr for the implementation of the shortcut backend that we can follow?   That utility would sure make it easier for creating these within crypt if that works.  Its difficult to do that now.

**Comment by 88lex** [comment]
More testing, a few observations:

Using beta 284
Created a folder in mydrive:test
Added two links inside test with the same name.  /test/test1 and /test/test1
Each of the links has a few, different test files. Say a.txt, b.txt in the first and c.txt, d.txt in the second.

#1:
rclone ls mydrive:test shows both test/test1 folders as separate items with the same name
rclone lsjson mydrive:test shows both folders with same name but unique id's
perfect!
rclone ls mydrive:test/test1 shows only a.txt and b.txt
I cannot find a simple way to navigate to the second test1
Is there a way to navigate to the second/subsequent folders that may have the same name at the same level in the tree?

#2:
Mounting mydrive: with rclone works as usual. 
However if you navigate to the mount and do a ls the result shows only one of the two folders with the duplicate name. 
```ls /mnt/g/test
test1```
Same result using Finder or Explorer. Only one instance of a folder with duplicate name shows up.

====
A workaround is to ensure that you do not create shortcuts with duplicate folder names. Then there are no problems. But would be excellent if there were a way to show and easily navigate to duplicate folder names.

**Comment by ncw** [comment]
@88lex yes rclone isn't good at handing duplicate file names on google drive. The `rclone dedupe` command exists to help you fix them which I'm sure you know already.

I could do what I did in the google photos backend which is suffix the directory name with the id if there are duplicates. It is really ugly but it does work! So a duplicate might look like

    dupe-file-{1TVbLXkijhYhjkHp1pgE4l1cxJdbAdgCs}
    dupe-file-{16qIoizGEA9iY2AvJfdwDxkikJU87hjTL}

**Comment by ncw** [comment]
I've made a backend tool to create drive shortcuts

If anyone would like to have a go I'd appreciate that!

https://beta.rclone.org/branch/v1.51.0-290-gd2e89523-fix-drive-shortcut-beta/ (uploaded in 15-30 mins)

Here is the docs

#### shortcut

Create shortcuts from files or directories

    rclone backend shortcut remote: [options] [<arguments>+]

This command creates shortcuts from files or directories.

Usage:

    rclone backend shortcut drive: source_item destination_shortcut
    rclone backend shortcut drive: source_item -o target=drive2: destination_shortcut

In the first example this creates a shortcut from the "source_item"
which can be a file or a directory to the "destination_shortcut". The
"source_item" and the "destination_shortcut" should be relative paths
from "drive:"

In the second example this creates a shortcut from the "source_item"
relative to "drive:" to the "destination_shortcut" relative to
"drive2:". This may fail with a permission error if the user
authenticated with "drive2:" can't read files from "drive:".


Options:

- "target": optional target remote for the shortcut destination

**Comment by EatDesk** [comment]
Shortcut support is failing for me if I copy any file(s) that exceed 250MB from remote to local with this error.

`Elapsed time:         0.0sException 0xc0000005 0x1 0x0 0x7fefd2cc4d2
PC=0x7fefd2cc4d2
signal arrived during external code execution`

**Comment by darthShadow** [comment]
@EatDesk Can you add the debug logs and the exact command used, please?

**Comment by EatDesk** [comment]
> 
> 
> @EatDesk Can you add the debug logs and the exact command used, please?

I'm really sorry but I was so busy testing shortcuts that I didn't realize it was happening with all files over 250MB, not specifically shortcuts. I will look for support on that elsewhere rather than here since this is for the shortcut issue.

**Comment by calisro** [comment]
So far so good with the shortcut on regular gdrives.  Is it possible to make the backend shortcut  work through crypt remotes?  It would be rather difficult to do this currently as the crypt names would have to be reversed first.

**Comment by 88lex** [comment]
Continuing tests of creating shortcuts. So far all good.

Created:
shortcut from mydrive:test1 folder to mydrive:test2 == works.

shortcut from mydrive:test1 folder to shareddrive:test2 == works.

shortcut from shareddrive:test1 folder to shareddrive:test2 == works.

shortcut from shareddrive:test1 folder to mydrive:test2 == works.

a series of nested shortcuts and folders. All seems to work well, same as a normal FS.

So far looks great, thank you.  When you are ready would be great to add this to the normal beta ... more testers :-)

**Comment by ncw** [comment]
@calisro wrote:
> So far so good with the shortcut on regular gdrives. Is it possible to make the backend shortcut work through crypt remotes? It would be rather difficult to do this currently as the crypt names would have to be reversed first.

:thinking: You could do it with a bit of shell magic..

This didn't quite work because of the "quotes" around the output from jq

    rclone backend shortcut drive:test/secret $(rclone backend encode cryptdrive: file.txt | jq '."file.txt"')  $(rclone backend encode cryptdrive: shortcut.txt | jq '."shortcut.txt"')

So this would be a lot easier if `rclone backend encode` has a `-o plain` flag which just outputed the plain file names, you could then write

    rclone backend shortcut drive:test/secret $(rclone backend encode cryptdrive: file.txt -o plain')  $(rclone backend encode cryptdrive: shortcut.txt -o plain)

However even neater might be a command that the crypt backend implements to wrap other commands. It could encode all the args and swap the remote for the underlying remote, say something like

    rclone backend runencoded cryptdrive: shortcut file.txt shortcut.txt

which would in turn do the equivalent of

    rclone backend shortcut drive:test/secret alsdkqfgja234lskjfl8478askjf oiwjo93okejlkwej93u

This is a general problem with the backend commands is that the wrapping backends (like crypt, cache) won't pass them on.


@88lex wrote:
> Continuing tests of creating shortcuts with 290 rclone shortcut backend. So far all good.
> 
> Created:
> shortcut from mydrive:test1 folder to mydrive:test2 == works.
> 
> shortcut from mydrive:test1 folder to shareddrive:test2 == works.
> 
> shortcut from shareddrive:test1 folder to shareddrive:test2 == works.
> 
> shortcut from shareddrive:test1 folder to mydrive:test2 == works.
> 
> a series of nested shortcuts and folders. All seems to work well, same as a normal FS.
> 
> So far looks great, thank you. When you are ready would be great to add this to the normal beta ... more testers :-)

Great testing thank you! I think that is enough double checking - I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

**Comment by calisro** [comment]
One thing I noticed is that if the path(s) for a shortcut has a '/' on the end(s), it has very unexpected results.  We should strip the slash before processing the shortcut I believe.

**Comment by 88lex** [comment]
> One thing I noticed is that if the path(s) for a shortcut has a '/' on the end(s), it has very unexpected results. We should strip the slash before processing the shortcut I believe.

^^ :-)

Playing with (read: mangling) the syntax I got some great new shortcuts.
e.g. a folder inside google: called `google:test/test1` which included the colon and slash in the name. I had forgotten that google allows special chars in names.

**Comment by ncw** [comment]
@calisro wrote:
> One thing I noticed is that if the path(s) for a shortcut has a '/' on the end(s), it has very unexpected results. We should strip the slash before processing the shortcut I believe.

Ah, well spotted! Very unexpected results indeed!

@88lex wrote:
> Playing with (read: mangling) the syntax I got some great new shortcuts.
> e.g. a folder inside google: called `google:test/test1` which included the colon and slash in the name. I had forgotten that google allows special chars in names.

How did you manage that? Getting the slash in a name should be impossible!

Here is a new beta for you both to test which should be a bit more defensive about what is allowed! If you can still create shortcuts with `/` in the names then please show me how!

https://beta.rclone.org/branch/v1.51.0-303-g507544e3-fix-4098-shortcuts-beta/ (uploaded in 15-30 mins)

PS you can create inception shortcuts like this - these could easily blow rclone up if you do a list recursive on them!

    rclone backend shortcut drive:test / inception

**Comment by ncw** [comment]
I found a bug - list recursive wasn't transitting shortcuts...

This should fix that plus the above!

https://beta.rclone.org/branch/v1.51.0-304-g6d3d3db2-fix-4098-shortcuts-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged the fixes to master now :-)

**Comment by drmccollum** [comment]
I'm using rclone-v1.51.0-304-g6d3d3db2-fix-4098-shortcuts-beta-linux-amd64.deb on Ubuntu 18.04 and have an issue with large zip files being corrupted. I have a 64g zip file that I can download from a shared folder in google drive and it unzips fine on my PC. When I extract in Ubuntu after using rclone to download, it's corrupted about halfway through.

**Comment by darthShadow** [comment]
@drmccollum Can you please the post the issue on the [forum](https://forum.rclone.org/) and try with the latest beta too, since the feature has been merged to the master branch already?

**Comment by TonyPuryer** [comment]
Shortcuts that point to files on other peoples Google Drives are not showing with the latest ARM beta (rclone-v1.51.0-259-gc2e0b827-fix-4098-drive-shortcuts-beta-linux-arm.zip). Previously (before Google implemented shortcuts) I could add a shared file and Rclone would see it and I could download it. Now, only locally created shortcuts are seen by Rclone. Is this expected behaviour? Many thanks.
![Capture2](https://user-images.githubusercontent.com/46962942/81893267-9e5ff580-95f0-11ea-89d1-aec017c1449e.JPG)

**Comment by darthShadow** [comment]
@TonyPuryer Since this feature has now been merged into the master branch and consequently the latest betas, can you please open a new thread on the [forum](https://forum.rclone.org/) or a new issue here on Github so we can find out what's causing the problem?

**Comment by sidhant-khamankar** [comment]
@ncw It would be great if original file is copied when copying using a file shortcut

**Comment by ncw** [comment]
@sidhant-khamankar that could be an option. I suggest you create a new issue.
