### ISSUE TITLE
Add support for explicit FTP over TLS

### ISSUE THREAD

**Issue by heikobornholdt** [rclone/rclone#4100]
The FTP backend currently does not support explicit FTP over TLS for accessing existing servers.

Update:
Unfortunately, the used FTP client library [does not support](https://github.com/jlaffaye/ftp/issues/162) this feature at the moment.

**Comment by ncw** [comment]
There seems to be some work going on here: https://github.com/jlaffaye/ftp/pull/168

**Comment by animosity22** [comment]
Linked issue was solved so closing out.

**Comment by heikobornholdt** [comment]
Issue isn‘t resolved. We‘re waiting for an action from the maintainer (https://github.com/jlaffaye/ftp/pull/156#issuecomment-608085129). Please reopen.

**Comment by animosity22** [comment]
The issue on the other side is stale/closed so not much can be done until that's resolved and it's closed out. If something fixes it, we can always open it back up.

**Comment by heikobornholdt** [comment]
The issue ist still stalled, but it looks like the maintainer has added the requested feature by himself (https://github.com/jlaffaye/ftp/commit/ac1574d38364dab95e9e4f1ee4c06954730e4dda).

We should now be able to add the requested support for explicit FTP to rclone.

**Comment by ncw** [comment]
I'll re-open this as the upstream library now does have explicit FTP support and there is a PR in progress for adding it to rclone :-)
