### ISSUE TITLE
Mount Process Hang when a Union Directory is mounted back on-itself with Union Remote

### ISSUE THREAD

**Issue by trumblejoe** [rclone/rclone#4103]
I am unable to replicate this with the latest beta. Rclone is unable to be updated when a current rclone process is running (or hung!).

#### What is the problem you are having with rclone?
I have the following set-up.
remote:
/LocalFolder
UnionRemote: (remote: & /LocalFolder)

Because I am an idiot, I mounted the UnionRemote: on /LocalFolder and the process hung in Uninterruptible Sleep. If I close out my shell, re-open and attempt to ls -la on the directory with the mount, that will also hang. So typically to remedy a stuck mount, firing off fusermount -uz mount is more then sufficient but in this case, though it unmounts, it doesn't end the process and the processes are stuck in 'D', uninterruptible sleep. I've repeated this process three times, because hey what else can I do on a system I don't have root access too, and I can't trigger the mount to unhang. I hoped that by re-mounting and waiting, the kernel would be tricked into eventually firing off whatever system call it's looking for but it didn't work. I also am unable to perform an strace or a ptrace, or fire off any type of tracer round because I lack admin credentials. If I were to wager a guess however, I would entertain func checkMountpointOverlap, is the offending function, possibly because it doesn't check that Union is mounting on one of it's source mount points? I would do a pull but Go isn't my language and I'd be more worried about mucking things up, sorry.

https://github.com/rclone/rclone/blob/66e08e0cc8972000d84a61f262286f5644d9fdee/cmd/mountlib/mount.go

rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7

Google Drive

Rclone Mount

So when you do this and it freezes up your mount, here is a great one-liner to show you all processes stuck in sleep state D.
watch -n 1 "(ps aux | awk '\$8 ~ /D/  { print \$0 }')"

**Comment by ncw** [comment]
>  If I were to wager a guess however, I would entertain func checkMountpointOverlap, is the offending function, possibly because it doesn't check that Union is mounting on one of it's source mount points?

You are probably right. That function was put in as part of #2905 which describes a similar hard hang.

Fixing this would be quite hard I think as getting the info out of the Union backend could be quite tricky...  You can use the `--allow-non-empty` flag or my recommended approach - don't do that!

(I've locked up my machine more times than I care to remember messing around with FUSE filesystems!)

**Comment by trumblejoe** [comment]
Can you not poll the config for the remote names?

**Comment by ncw** [comment]
> Can you not poll the config for the remote names?

Yes that is possible, but what if a crypt wraps a local directory, or a crypt wraps a union which wraps a local directory, etc, etc. There are myriad ways of shooting yourself in the foot :-)

**Comment by animosity22** [comment]
This looks to be answered so closing out.
