### ISSUE TITLE
GDRIVE FILE COPY 

### ISSUE THREAD

**Issue by vaccarieli** [rclone/rclone#4109]
#### Output of `rclone version`

Latest

#### Describe the issue

Rclone won`t copy files from a GDrive file shortcut as it normally did before

**Comment by Dibbyo456** [comment]
> Rclone won`t copy files from a GDrive file shortcut as it normally did before

That is a [known issue](https://forum.rclone.org/t/fyi-sep-30-new-google-drive-shortcuts-and-folder-structure/15197/6?u=harry).

**Comment by animosity22** [comment]
Duplicate as noted above.
