### ISSUE TITLE
s3 <- webdav <- PUT: OpenFile: fd=<nil>, err=file does not exist

### ISSUE THREAD

**Issue by RemiTorracinta** [rclone/rclone#4111]
#### What is the problem you are having with rclone?

```
>OpenFile: fd=<nil>, err=file does not exist
```
is presented when I try to PUT a file to rclone serving WEBDAV with an S3 backend. I only get this issue on the linux-amd64 platform, but everything works fine on macos.

#### What is your rclone version (output from `rclone version`)

I've reproduced the issue on versions 1.48, 1.50, 1.51, and the v1.51.0-151-gfc663d98 beta.

The bug does not arise when on my Mac, where I tested v1.51.0. 

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Issue is on linux-amd64. Issue doesn't occur on macos.

####  Which cloud storage system are you using? (eg Google Drive)

S3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone command:
```bash
rclone -vv --config rclone.conf serve webdav s3_cache:my_cache --vfs-cache-mode off
```
(I repro'd the issue with all cache modes)

rclone.conf:
```
[s3_cache]
type = s3
provider = AWS
env_auth = true
```
Curl command:
```bash
root@da5d22f83dc1:~/app# curl -T  ./my_file http://127.0.0.1:8080/a/c/tool/hash_key.tar.gz --verbose
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

rclone log on linux failure:
```
2020/04/05 21:50:54 DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "-vv" "--config" "rclone.conf" "serve" "webdav" "s3_cache:my_cache" "--vfs-cache-mode" "off"]
2020/04/05 21:50:54 DEBUG : Using config file from "/root/app/rclone.conf"
2020/04/05 21:50:54 INFO  : S3 bucket my_cache: poll-interval is not supported by this remote
2020/04/05 21:50:54 DEBUG : Adding path "vfs/forget" to remote control registry
2020/04/05 21:50:54 DEBUG : Adding path "vfs/refresh" to remote control registry
2020/04/05 21:50:54 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2020/04/05 21:50:54 NOTICE: S3 bucket my_cache: WebDav Server started on http://127.0.0.1:8080/
2020/04/05 21:51:08 DEBUG : /a/c/tool/hash_key.tar.gz: OpenFile: flags=O_RDWR|O_CREATE|O_TRUNC, perm=-rw-rw-rw-
2020/04/05 21:51:08 DEBUG : /a/c/tool/hash_key.tar.gz: >OpenFile: fd=<nil>, err=file does not exist
2020/04/05 21:51:08 INFO  : /a/c/tool/hash_key.tar.gz: PUT from 127.0.0.1:45018

```

Curl log on linux failure:
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> PUT /a/c/tool/hash_key.tar.gz HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Length: 4107
> Expect: 100-continue
>
< HTTP/1.1 404 Not Found
< Date: Sun, 05 Apr 2020 21:51:08 GMT
< Content-Length: 9
< Content-Type: text/plain; charset=utf-8
< Connection: close
<
* Curl_http_done: called premature == 0
* Closing connection 0
root@da5d22f83dc1:~/app#
```

rclone log on macos success:
```
2020/04/05 17:55:05 DEBUG : Using config file from "/Users/remi/app/rclone.conf"
2020/04/05 17:55:05 INFO  : S3 bucket my_cache: poll-interval is not supported by this remote
2020/04/05 17:55:05 DEBUG : Adding path "vfs/forget" to remote control registry
2020/04/05 17:55:05 DEBUG : Adding path "vfs/refresh" to remote control registry
2020/04/05 17:55:05 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2020/04/05 17:55:05 NOTICE: S3 bucket my_cache: WebDav Server started on http://127.0.0.1:8080/
2020/04/05 17:55:10 DEBUG : /a/c/tool/hash_key.tar.gz: OpenFile: flags=O_RDWR|O_CREATE|O_TRUNC, perm=-rw-rw-rw-

```

curl log on macos success:
```bash
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> PUT /a/c/tool/hash_key.tar.gz HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Length: 4107
> Expect: 100-continue
>
* Done waiting for 100-continue
* We are completely uploaded and fine

```

**Comment by ncw** [comment]
I would say that the curl error indicates the directory you were uploading to does not exist. That is what my tests indicate...

**Comment by RemiTorracinta** [comment]
Ah, that's fair enough, though it's puzzling that the two platforms produced different results. 

The nuance here is that s3 doesn't require directory objects to actually exist when putting objects in a "directory". I would have assumed that disabling the cache would therefore resolve the issue, since rclone might write directly to s3 without trying to open a non-existent directory on the filesystem first.

The webdav client I'm trying to support opts not to create directories, (not exactly webdav-compliant I suppose).

So I'm probably in undocumented rclone usage territory. One thing that would be really helpful is a feature like nginx's `create_full_put_path` :

http://nginx.org/en/docs/http/ngx_http_dav_module.html

**Comment by ncw** [comment]
I tried the webdav server on plain s3 like this

    rclone -vv serve webdav s3:rclone

Then this fails with the 404 error

```
$ curl -T  /tmp/file.txt http://127.0.0.1:8080/non-existent-dir/file.txt --verbose
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> PUT /a/c/tool/non-existent-dir/file.txt HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.65.3
> Accept: */*
> Content-Length: 6
> Expect: 100-continue
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Wed, 15 Apr 2020 16:16:21 GMT
< Content-Length: 9
< Content-Type: text/plain; charset=utf-8
< Connection: close
< 
* Closing connection 0
```

However if I "create" the directory first it does work

```
$ rclone mkdir --webdav-url http://127.0.0.1:8080/ :webdav:/a/c/tool/non-existent-dir/
$ curl -T  /tmp/file.txt http://127.0.0.1:8080/a/c/tool/non-existent-dir/file.txt --verbose
*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> PUT /a/c/tool/non-existent-dir/file.txt HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/7.65.3
> Accept: */*
> Content-Length: 6
> Expect: 100-continue
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< Etag: "16060aa786194a926"
< Date: Wed, 15 Apr 2020 16:20:33 GMT
< Content-Length: 7
< Content-Type: text/plain; charset=utf-8
< 
* Connection #0 to host 127.0.0.1 left intact
$ 
```

As you noted s3 doesn't support directories, and neither does rclone - what is happening is that the mkdir puts one in the VFS cache for a while (until the directory expiry time anyway).

I think it must be the webdav library rclone is using which is requiring the existence of the directory https://golang.org/x/net/webdav


> So I'm probably in undocumented rclone usage territory. One thing that would be really helpful is a feature like nginx's `create_full_put_path` :
> 
> http://nginx.org/en/docs/http/ngx_http_dav_module.html

I think that would probably require a patch to the upstream library.

**Comment by animosity22** [comment]
Anything else needed on this one or can it be closed out?

**Comment by RemiTorracinta** [comment]
one thing, shouldn't disabling the VFS cache fix this then? I still see an issue even when it's turned off.

**Comment by ncw** [comment]
> one thing, shouldn't disabling the VFS cache fix this then? I still see an issue even when it's turned off.

You can't disable VFS metadata caching... I think doing so probably wouldn't help though.

I'll close this now since I think we've got to the bottom of things.

**Comment by gemapayo** [comment]
I am facing this same issue.
What I don't understand is why it works on macos but not on linux
