### ISSUE TITLE
cannot sync googleapi: Error 403 does not have storage.objects.list access to sites., forbidden

### ISSUE THREAD

**Issue by aslimacc** [rclone/rclone#4112]
#### What is the problem you are having with rclone?
I am synchronizing a directory from a machine hosted in GCP to a bucket (google cloud storage). The directory contains 219543 files (images). There are many symlinks that point to files in the same directory. At the end of sync, I have error:
ERROR : Attempt 3/3 failed with 29 errors and: googleapi: Error 403: "service account" does not have storage.objects.list access to sites., forbidden

The 29 errors are the number of files that cannot be synchronized because those files are symlinked to files that doesn't exist.
I am searching to ignore these errors 

#### What is your rclone version (output from `rclone version`)
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian GNU/Linux 9 \n \l

####  Which cloud storage system are you using? (eg Google Drive)
Google cloud storage (bucket)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone -vv sync -L -P  "path_source" remote:"bucket_name"/"path_destination" --ignore-errors   --delete-during

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

At the beginning of sync:
DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "-vv" "sync" "-L" "-P" "/data/www/sites/ad4push.com/public_data/images/uploads" "remote:/sites/ad4push.com/public_data/images/uploads" "--ignore-errors" "--delete-during"]
DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
INFO  : Waiting for deletions to finish
ERROR : _360.1453909779: Listing error: symlink: stat/data/www/sites/ad4push.com/public_data/images/uploads/_360.1453909779: no such file or directory

At the end of sync:
ERROR : Attempt 3/3 failed with 29 errors and: googleapi: Error 403: "serviceaccount" does not have storage.objects.list access to sites., forbidden

**Comment by aslimacc** [comment]
any update about this issue ?

**Comment by ncw** [comment]
> ERROR : _360.1453909779: Listing error: symlink: stat/data/www/sites/ad4push.com/public_data/images/uploads/_360.1453909779: no such file or directory

Is this a dangling symlink? You said with the `-L` that you wanted symlinks but rclone couldn't copy this one.

>  googleapi: Error 403: "serviceaccount" does not have storage.objects.list access to sites., forbidden

This looks like you need to give more permissions to your service account.

**Comment by aslimacc** [comment]
Hello,
1. I have no problem if there are files that are not copied.

2. I am using a service account in my config file from "/root/.config/rclone/rclone.conf"
[remote]
type = google cloud storage
project_number = accengage-bigdata
location = eu
storage_class = MULTI_REGIONAL
service_account_file = /root/backup-key.json

the json file is the file generated when the service has been created.
And this service account has all those roles:
Editor
Storage Admin
Storage Object Admin
Storage Object Creator
Storage Object Viewer

I don't understand why the error said that the service account miss permissions ?
Is it a bug ?

Thanks

**Comment by ncw** [comment]
You need to give the account `storage.objects.list` too I think.

**Comment by aslimacc** [comment]
All the roles I gave to the service account have the permission
storage.objects.list

Think that is a bug. Is there a way to avoid this error ?

**Comment by ncw** [comment]
I'm not a GCS expert, but I'd try making a service account with more permissions to see if you can get it to work.

However we could ask @thestigma for help who does know a lot about GCP permissions!

**Comment by awesomejerry** [comment]
I have the same problem when using rclone with docker.
I have the following service defined in my `docker-compose.yml`
```
  rclone:
    image: rclone/rclone:1.53.3
    restart: "no"
    container_name: rclone
    command: ["sync", "/data", "remote:bucket"]
    networks:
      - backup
    volumes:
      - $DATA_PATH/backup:/data
      - $DATA_PATH/rclone:/config/rclone
      - $DATA_PATH/rclone-service-account.json:/config/rclone-service-account.json
 ```
When I run the service, the output error is shown:
 ```
 2021/01/05 14:32:46 ERROR : : error reading destination directory: googleapi: Error 403: [SERVICE_ACCOUNT] does not have storage.objects.list access to the Google Cloud Storage bucket., forbidden
2021/01/05 14:32:46 ERROR : GCS bucket bucket: not deleting files as there were IO errors
2021/01/05 14:32:46 ERROR : GCS bucket bucket: not deleting directories as there were IO errors
2021/01/05 14:32:46 ERROR : Attempt 1/3 failed with 1 errors and: googleapi: Error 403: [SERVICE_ACCOUNT] does not have storage.objects.list access to the Google Cloud Storage bucket., forbidden
2021/01/05 14:32:46 ERROR : : error reading destination directory: googleapi: Error 403: [SERVICE_ACCOUNT] does not have storage.objects.list access to the Google Cloud Storage bucket., forbidden
2021/01/05 14:32:46 ERROR : GCS bucket bucket: not deleting files as there were IO errors
2021/01/05 14:32:46 ERROR : GCS bucket bucket: not deleting directories as there were IO errors
2021/01/05 14:32:46 ERROR : Attempt 2/3 failed with 1 errors and: googleapi: Error 403: [SERVICE_ACCOUNT] does not have storage.objects.list access to the Google Cloud Storage bucket., forbidden
2021/01/05 14:32:46 ERROR : : error reading destination directory: googleapi: Error 403: [SERVICE_ACCOUNT] does not have storage.objects.list access to the Google Cloud Storage bucket., forbidden
2021/01/05 14:32:46 ERROR : GCS bucket bucket: not deleting files as there were IO errors
2021/01/05 14:32:46 ERROR : GCS bucket bucket: not deleting directories as there were IO errors
2021/01/05 14:32:46 ERROR : Attempt 3/3 failed with 1 errors and: googleapi: Error 403: [SERVICE_ACCOUNT] does not have storage.objects.list access to the Google Cloud Storage bucket., forbidden
2021/01/05 14:32:46 Failed to sync: googleapi: Error 403: [SERVICE_ACCOUNT] does not have storage.objects.list access to the Google Cloud Storage bucket., forbidden
 ```
My service account has `Storage Admin` and `Storage Object Admin` roles on GCP. I even created a custom role with the following permissions:
```
storage.buckets.create
storage.buckets.delete
storage.buckets.get
storage.buckets.getIamPolicy
storage.buckets.list
storage.buckets.setIamPolicy
storage.buckets.update
storage.hmacKeys.create
storage.hmacKeys.delete
storage.hmacKeys.get
storage.hmacKeys.list
storage.hmacKeys.update
storage.objects.create
storage.objects.delete
storage.objects.get
storage.objects.getIamPolicy
storage.objects.list
storage.objects.setIamPolicy
storage.objects.update
```

**Comment by aslimacc** [comment]
will close the PR due to inactivity for a long time
