### ISSUE TITLE
[Feature Request] box.com authentication using app token

### ISSUE THREAD

**Issue by lonix1** [rclone/rclone#4114]
As [discussed here](https://forum.rclone.org/t/can-i-force-rclone-to-use-boxs-cli-api/15463/6) with @ncw, it would be helpful if we could authenticate with box.com using an app token. Right now auth is performed using oauth.

When running services on a headless server, it is more convenient (and often more common) to use an app token, which is generated by hand on the service's website, then saved in scripts/code and included in every REST call to the service.

Box [has such a feature](https://developer.box.com/guides/authentication/app-token/). It's typically used in calls made with `curl`, no oauth required.

If implemented, it would greatly simplify configuration in headless environments.

(As an aside, it is quite possible many other storage services also support this auth option.)

**Comment by ncw** [comment]
Since you were currently working on box auth - I wondered if you'd like to look at this one @dbramwell  ?

It should be a question of adding the key straight to the client with `f.rest.SetHeader("Authorization", "Bearer "+f.opt.APIKey)` and disabling the oauth config.

**Comment by lonix1** [comment]
My understanding of rclone is that you support the "lowest common denominator" - i.e. those features that exist on all storage services.

Is it even possible to support this auth mechanism, just for box?

**Comment by dbramwell** [comment]
@ncw Sure, I'll take a look. Seem's simple enough, but as always, expect a bunch of questions!

**Comment by ncw** [comment]
Thank you @dbramwell  and happy to answer questions :-)

**Comment by dbramwell** [comment]
Might have jumped the gun a bit here. Between my permissions in Box at work and the £8/month cost of adding `App Token` functionality in a personal account, I have no way to create an App Token to test this.

**Comment by lonix1** [comment]
@dbramwell You can get a free account on box. Their entry-level is a free 10GiB account.

**Comment by dbramwell** [comment]
Ah Thanks. Think I was looking at "Admin Console" rather than "Dev Console". Interestingly now that I've created an app in the dev console I can also get into the admin console...

Anyway, I'll have a go at this at some point this week

**Comment by lonix1** [comment]
The thing I don't like about box's dev workflow: all files are uploaded to the dev console and can only be accessed there. So you can't see them in the normal console (was very confusing at first).

So if you upload files and don't understand why they don't show, it's because they're in the dev console.

**Comment by ncw** [comment]
I've put @dbramwell 's change into a branch so it builds a beta for you to try @lonix1 

https://beta.rclone.org/branch/v1.52.0-023-ge11a3e21-fix-4114-box-token-beta/ (uploaded in 15-30 mins)

Thanks for doing this @dbramwell

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.53

**Comment by dbramwell** [comment]
Thanks!
