### ISSUE TITLE
rclone sync from OneDrive to local : Failed to copy: chtimes no such file or directory

### ISSUE THREAD

**Issue by valeriob** [rclone/rclone#4120]
#### What is the problem you are having with rclone?
I'm using rclone sync to clone a onedrive account locally.

#### What is your rclone version (output from `rclone version`)
1.51

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Unraid 6.8.3

####  Which cloud storage system are you using? (eg Google Drive)
Onedrive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync -vv --log-file $logFile aurora:/ --backup-dir /mnt/disk1/OneDrive/Aurora/Onedrive.Rclone.Backup/$date /mnt/disk1/OneDrive/Aurora/Onedrive.Rclone

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2020/04/11 14:57:33 DEBUG : Immagini/Rullino 2018-2019/VID_20180127_211747.mp4: Sizes differ (src 113869468 vs dst 258048)
2020/04/11 14:57:33 INFO  : Immagini/Rullino 2018-2019/VID_20180127_211747.mp4: Moved (server side)
2020/04/11 15:20:42 DEBUG : Immagini/Rullino 2018-2019/VID_20180127_211747.mp4: Reopening on read failure after 524288 bytes: retry 1/10: read tcp 192.168.1.132:43936->13.107.42.12:443: read: connection reset by peer
2020/04/11 15:47:51 DEBUG : Immagini/Rullino 2018-2019/VID_20180127_211747.mp4: Reopening on read failure after 107883252 bytes: retry 2/10: stream error: stream ID 3; HTTP_1_1_REQUIRED
2020/04/11 16:02:37 DEBUG : Immagini/Rullino 2018-2019/VID_20180127_211747.mp4: Reopening on read failure after 109820201 bytes: retry 3/10: stream error: stream ID 41; HTTP_1_1_REQUIRED
2020/04/11 16:13:17 DEBUG : Immagini/Rullino 2018-2019/VID_20180127_211747.mp4: Reopening on read failure after 111811631 bytes: retry 4/10: stream error: stream ID 55; HTTP_1_1_REQUIRED
2020/04/11 16:17:25 ERROR : Immagini/Rullino 2018-2019/VID_20180127_211747.mp4: Failed to copy: chtimes /mnt/disk1/OneDrive/Aurora/Onedrive.Rclone/Immagini/Rullino 2018-2019/VID_20180127_211747.mp4: no such file or directory

**Comment by animosity22** [comment]
With the small excerpt of the log, it looks like you are having network issues.

**Comment by valeriob** [comment]
The account is about 160Gb, i have this problem only on 4 files, they are about 200Mb each, from the log it's not clear to me what parameter i could change to make it work, the retry looks like stopping at 4/10.

**Comment by animosity22** [comment]
It would be helpful to see the full log as it just looks like you are having a network error, which no parameter change would fix.

**Comment by valeriob** [comment]
Running rclone multiple time solved the issue, now even though the onedrive source did not change, i still have about 300mb in 96 files that get downloaded over and over again, i find em every time in the --backup-dir folder.
For example this one  DSC06052.JPG, i find it on both the synced local folder and in the backup dir (they are identical with size 2101211), it looks like processed multiple times, with different results, i do not even find the "Deleted" log entry

2020/04/12 13:06:25 DEBUG : Immagini/2013/scouts/vdb valdiccioli/DSC06052.JPG: Size and modification time the same (differ by 0s, within tolerance 1s)
2020/04/12 13:06:25 DEBUG : Immagini/2013/scouts/vdb valdiccioli/DSC06052.JPG: Unchanged skipping
2020/04/12 13:14:38 DEBUG : Immagini/2013/scouts/vdb valdiccioli/DSC06052.JPG: Size and modification time the same (differ by 0s, within tolerance 1s)
2020/04/12 13:14:38 DEBUG : Immagini/2013/scouts/vdb valdiccioli/DSC06052.JPG: Unchanged skipping
2020/04/12 13:22:55 DEBUG : Immagini/2013/scouts/vdb valdiccioli/DSC06052.JPG: Sizes differ (src 2101211 vs dst 1044480)
2020/04/12 13:22:55 INFO  : Immagini/2013/scouts/vdb valdiccioli/DSC06052.JPG: Moved (server side)
2020/04/12 13:23:03 DEBUG : Immagini/2013/scouts/vdb valdiccioli/DSC06052.JPG: SHA-1 = 91b3408884bf0106ad4db551b4a0daacfc333370 OK
2020/04/12 13:23:03 INFO  : Immagini/2013/scouts/vdb valdiccioli/DSC06052.JPG: Copied (new)

**Comment by animosity22** [comment]
A full log helps so much rather than a small chunk.

It says why something gets uploaded as the sizes differ as the dst size is smaller than the source.

**Comment by valeriob** [comment]
Sure thing, how can i send it to you privately ?

**Comment by animosity22** [comment]
You can send a link or a message on https://forums.rclone.org

Same username  :)

**Comment by valeriob** [comment]
So i was able to make it work by adding the --ignore-size parameter, i had problems with many files, not only documents, also video and images.
Is it safe to add this parameter ?

**Comment by ncw** [comment]
> So i was able to make it work by adding the --ignore-size parameter, i had problems with many files, not only documents, also video and images.

Anything which might have its metadata adjusted can have this problem. I think we first noticed it with images.



> Is it safe to add this parameter ?

It isn't ideal... It means that rclone will miss a document changing size. However Onedrive support modification times so rclone should notice the modification time changing.

I think the answer is reasonably safe!

**Comment by valeriob** [comment]
Thanks !
