### ISSUE TITLE
[Feature Request] add password to single entry rclone config file

### ISSUE THREAD

**Issue by ariek48** [rclone/rclone#4127]
At this moment I use an encrypted config file which works fine.
Everytime I start rclone I enter the password and all is okay

But I was wondering.
Is it possible to only encrypt single entries in a rclone.conf file, for example
I have an encrypted gdrive folder and I want to copy, ls,move,etc the drive

could something like

rclone ls password@encrypteddrive:/ be something
or 
rclone copy password@encrypteddrive:/  otherdrive:/ -vvv

The password would only encrypt the entry of encrypteddrive in the rclone.conf
In that case some entries would be unsecured and some would be secured

Look I am certainly very happy with the current rclone, but I was just wondering about this

**Comment by ncw** [comment]
This isn't possible at the moment and the way the config file works would be very hard to implement.

The best I could suggest at the moment would be to have two config files, one encrypted and one unencrypted and switch between them with the `--config` flag.

**Comment by ivandeex** [comment]
closing as WONTFIX based on the above
