### ISSUE TITLE
ls hangs on team drive?

### ISSUE THREAD

**Issue by HeroXx** [rclone/rclone#4128]
#### Output of `rclone version`
rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.6

#### Describe the issue

Up until this morning, I had been able to successfully use a team drive mounted (with encryption). Since this morning, when I issue an 'ls' it will just hang (sometimes returning after 2 or 3 minutes) but it makes anything consuming the mount error or hang.

I've tried restarting the mount, reissuing credentials and nothing has worked. Verbose logging doesn't show anything meaningful in the log and using a manual rclone ls works fine...

Using ls on another directory within the same mount also works fine.

**Comment by ncw** [comment]
Can you try [the latest release](https://rclone.org/downloads/) or [the latest beta](https://beta.rclone.org)?

**Comment by animosity22** [comment]
1.48 is a pretty old version. If you upgrade and still have issues, please ask for help on https://forums.rclone.org

Thanks!
