### ISSUE TITLE
Docs: --quiet

### ISSUE THREAD

**Issue by d7415** [rclone/rclone#4132]
#### What is the problem you are having with rclone?
[This](https://github.com/rclone/rclone/blob/master/docs/content/docs.md#-q---quiet) page says that "Normally rclone outputs stats and a completion message". For me it doesn't (on a successful run), which fits with a [2017 change](https://github.com/rclone/rclone/blob/master/docs/content/changelog.md#v136---2017-03-18) to make rclone quieter. The --quiet section above hasn't been changed since.

From GitHub's "similar issues" #91 seems related too.

#### What is your rclone version (output from `rclone version`)
rclone v1.45
- os/arch: linux/amd64
- go version: go1.11.6

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux (Debian testing) 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
S3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone sync --fast-list`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
n/a

**Comment by ncw** [comment]
Well spotted - that is stale docs. Want to send a PR to fix up?

See: https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#writing-documentation

**Comment by d7415** [comment]
Sure. I'll take a look.
