### ISSUE TITLE
Evaluate a workaround for Google Photos export

### ISSUE THREAD

**Issue by fcaponi** [rclone/rclone#4142]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.51.0
- os/arch: windows/amd64
- go version: go1.13.7

#### What problem are you are trying to solve?
Regular backup of Google Photo content on a local hard drive (through RClone), avoiding the currently documented resolution limit on this feature (due to google's api limits)

#### How do you think rclone should be changed to solve that?
Honestly I have not checked the implementation of RClone because I don't know the go language, but I have performed some searches over the available api to understand a bit more about the documented api limit.
I have found an interesting trick documented here https://stackoverflow.com/questions/54782846/how-to-download-an-original-image-or-video-with-the-baseurl-of-google-photos-api

And indeed I have noticed using Chrome that the parameters at the end of the url are widely used, For example on my desktop the current displayed image adds at the end of the url this text =w1252-h939-no and playing with the w and h parameter i have been able to download the same content "rendered" multiple times with different sizes.
Ading =d as stated in the linked resource, the browser starts a download of the image at the original size.

Please can you evaluate if this trick can be used in the current implementation?

In the mean time I will have a deeper look on the api with some java examples (because i'm more comfortable with this language).

BR
Franco

**Comment by fcaponi** [comment]
Hi all,
i have verified using the java api that the observed behavior works and it is also documented here:
https://developers.google.com/photos/library/guides/access-media-items#image-base-urls

Now I'll try to understand the go language...

**Comment by ncw** [comment]
We already add `=d` for photos and `=dv` for videos

https://github.com/rclone/rclone/blob/9d4b3580a58ca9e2695e043931b3b8937c6395c0/backend/googlephotos/googlephotos.go#L891-L898

This is as documented in [the google photos API](https://developers.google.com/photos/library/guides/access-media-items#image-base-urls)

I don't think adding `=d` is a magic bullet unfortunately, for example in [this google issue](https://issuetracker.google.com/issues/112096115) the poster states they are using the `d` parameter.

**Comment by fcaponi** [comment]
Indeed, looking better, the image urls used by google photo web site and the one returned by the api are different:
the first one is something like https://lh3.googleusercontent.com/{a big id}=d
while the api returns something like https://lh3.googleusercontent.com/lr/{another big id}=d

I suppose that the context path lr means low resolution or similar

**Comment by ncw** [comment]
Hmm. Google (unlike Amazon) are famous for not ~~eating their own dogfood~~ consuming their own APIs. They do it with the drive website and they do it with the google photos website too apparently.

The Google Photos API is very much a second class citizen.

**Comment by fcaponi** [comment]
Honestly I don't know who is worst between google and amazon.
At least with Google Drive and Google Photos i can use rclone. With Amazon Prime Photos I cannot use it anymore since they blocked its client id

**Comment by calisro** [comment]
I was looking into this today and without being able to generate that 'another big id', this wont work.  The API used to generate that is the google photos front end api which is different.  I think this can be closed unless more info is available to get the relevant data from the api.
