### ISSUE TITLE
rclone slow

### ISSUE THREAD

**Issue by CryFun** [rclone/rclone#4147]
rclone transfer speed is slow, rclone copy is about 100kb / s at first, and then 12b / s. The upload upload speed is about 60kb / s, which is very slow

**Comment by Yexiaoxing** [comment]
Thanks for your report, but the information you provided is not enough. Could you please refer to https://github.com/rclone/rclone/blob/master/.github/ISSUE_TEMPLATE/Bug.md and edit your issue? 

Also, speed can be related to the Internet you are using, the storage provider, and many other things.

**Comment by CryFun** [comment]
rclone copy slowly(about 20kb /s)

rclone v1.45
- os/arch: windows/amd64
- go version: go1.11
OneDrive
rclone copy


Xiaoxing Ye <notifications@github.com> 于2020年4月18日周六 下午8:48写道：

**Comment by Cnly** [comment]
Hi @CryFun, what is the complete command you ran, and do you have any log output for that? Without those, it's unlikely we can offer any help on this problem.

**Comment by CryFun** [comment]
where is the log?
rclone OneDrive1:/A OneDrive2:/B

Alex Chen <notifications@github.com> 于2020年4月19日周日 上午10:41写道：

**Comment by CryFun** [comment]
Where is the log?
rclone copy OneDrive1:/A OneDrive2:/B -P

Alex Chen <notifications@github.com> 于2020年4月19日周日 上午10:41写道：

**Comment by Yexiaoxing** [comment]
Then please try to run 
```
rclone -vv copy OneDrive1:/A OneDrive2:/B -P
```
and the verbose log will be shown on the console.

And, what kind of network are you using? What about the speed when you are using browser to navigate OneDrive? I am assuming that you are in China, then the speed to OneDrive is slow due to the special situation.

**Comment by CryFun** [comment]
2020/04/19 18:03:15 DEBUG : rclone: Version "v1.45" starting with
parameters ["r
clone" "-vv" "copy" "OneDriveUOE:" "OneDriveXKX:" "-P"]
2020/04/19 18:03:15 DEBUG : Using config file from
"C:\\Users\\Administrator\\.c
onfig\\rclone\\rclone.conf"
2020-04-19 18:03:17 DEBUG : ../.....rar: Size and modification time the
same (di
ffer by 0s, within tolerance 1s)
2020-04-19 18:03:17 DEBUG : ../.....rar: Unchanged skipping
2020-04-19 18:03:17 DEBUG : ../...docx: Size and modification time the same
(dif
Transferred:        1.078M / 2.825 GBytes, 0%, 26.555 kBytes/s, ETA 30h58m9s
Errors:                 0
Checks:                17 / 17, 100%
Transferred:            0 / 395, 0%
Elapsed time:       41.5s
Transferring:
 *                              ../C.../C....zip: 10% /2.468M, 5
 *              ../SSR/ShadowsocksR-4.7.0-win.7z: 45% /698.815k, 7.274k/s, 5
 *     ../CCleaner/CCleaner.v5.65.7632.zh-CHS.7z:  2% /10.963M, 5.568k/s,
 *     ../RaiDrive/RaiDrive..6.2.416(2019.4).rar:  1% /20.288M, 6.269k/s,
2020-04-19 18:03:18 DEBUG : ../South Park/SP.S02/[zmk.pw
]South.Park.S02.1080p.WE
Transferred:        1.051M / 2.825 GBytes, 0%, 26.851 kBytes/s, ETA
30h37m44s
Errors:                 0
Checks:                17 / 17, 100%
Transferred:            0 / 395, 0%
Elapsed time:         40s
Transferring:
 *                              ../C.../C....zip: 10% /2.468M, 6
 *              ../SSR/ShadowsocksR-4.7.0-win.7z: 44% /698.815k, 7.744k/s, 5
 *     ../CCleaner/CCleaner.v5.65.7632.zh-CHS.7z:  2% /10.963M, 5.939k/s,

2020-04-19 18:03:19 DEBUG :
../JetBrains/..../jetbrains-agent-latest2020.1.zip:
Size and modification time the same (differ by 0s, within tolerance 1s)
2020-04-19 18:03:19 DEBUG :
../JetBrains/..../jetbrains-agent-latest2020.1.zip:
Unchanged skipping
2020-04-19 18:03:19 DEBUG :
../JetBrains/..../jetbrains-agent-latest2019.3.4.zip
: Unchanged skipping
2020-04-19 18:03:19 DEBUG : ../Adobe2020(by
vposy)/Acrobat/Acrobat_DC_C_2020.006
.20042_SP_20200318.sha: Size and modification time the same (differ by 0s,
withi
n tolerance 1s)
2020-04-19 18:03:19 DEBUG : ../Adobe2020(by
vposy)/Acrobat/Acrobat_DC_C_2020.006
.20042_SP_20200318.sha: Unchanged skipping
2020-04-19 18:03:19 DEBUG : ../Adobe2020(by
vposy)/Acrobat/Acrobat_DC_C_MacOS_20
19.021.20058_SP_20191222.sha: Size and modification time the same (differ
by 0s,
 within tolerance 1s)
2020-04-19 18:03:19 DEBUG : ../Adobe2020(by
vposy)/Acrobat/Acrobat_XI_11.0.23_Fi
nal_SP_20190605.sha: Size and modification time the same (differ by 0s,
within t
Transferred:        1.051M / 2.825 GBytes, 0%, 27.189 kBytes/s, ETA
30h14m48s
Errors:                 0
Checks:                17 / 17, 100%
Transferred:            0 / 395, 0%
Elapsed time:       39.5s
Transferring:
 *                              ../C.../C....zip: 10% /2.468M, 6
 *              ../SSR/ShadowsocksR-4.7.0-win.7z: 44% /698.815k, 7.744k/s, 5
 *     ../CCleaner/CCleaner.v5.65.7632.zh-CHS.7z:  2% /10.963M, 6.336k/s,

WMraUo5R0VrYXlKZkJFZmtLZ1V4R2tHSytlWXI4NXVPbTVzPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiM
jk4IiwiaXNsb29wY    1.051M / 2.825 GBytes, 0%, 27.433 kBytes/s, ETA
29h58m42sxrT
Errors:
0oiLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiTldVM
Checks:                17 / 17,
100%3RORFZsWlRFM01XTmtaalZqIiwiYXBwX2Rpc3BsYXluY
Transferred:            0 / 395,
0%ImJlZHJvY2siLCJmYW1pbHlfbmFtZSI6ImRyZWFtZXIiL
Elapsed time:
39.2sVkYTYtNDA5Mi04NTM5LTBlZWMzNzZhZmQ1OSIsInRpZCI6IjBiMTk1M
Transferring:VlYy1iODgyLTc1YjVkN2Y3YTY2OCIsInVwbiI6IjE1MjY4OTkxOTBAeGt4Lm1lIiwic
 *                              ../C.../C....zip: 10% /2.468M,
62hpcHwxMDAzMjAwM
 *              ../SSR/ShadowsocksR-4.7.0-win.7z: 44% /698.815k, 8.260k/s,
4Wxlc
 *     ../CCleaner/CCleaner.v5.65.7632.zh-CHS.7z:  2% /10.963M, 6.336k/s,
1bGx9.

transport connection broken: write tcp 192.168.1.101:60841->
40.108.217.56:443: w
sasend: An existing connection was forcibly closed by the remote host.):
Uploadi

Oh! I'm in China.


Xiaoxing Ye <notifications@github.com> 于2020年4月19日周日 下午5:17写道：

**Comment by Yexiaoxing** [comment]
I am not able to see any anomaly in the log, and I don't think there is much rclone can do... Maybe you should consider to use a reliable proxy to visit OneDrive.

BTW, you are using rclone v1.45 which is quite old. You are suggested to use a latest version when it is possible - refer to https://rclone.org/install/ for upgrade.

**Comment by CryFun** [comment]
Thanks

Xiaoxing Ye <notifications@github.com> 于2020年4月19日周日 下午6:49写道：

**Comment by Yexiaoxing** [comment]
Next time you can head to our forum (https://forum.rclone.org/) if you. have problems in the usage of rclone. It should be safe to close this issue.

**Comment by animosity22** [comment]
Please use the forums for issues like this.
