### ISSUE TITLE
Systemd help

### ISSUE THREAD

**Issue by Dr0bac** [rclone/rclone#4148]
Hi i just installed rclone on raspberry pi 3b running dietpi - debian(buster) with the help of this tutorial:
https://medium.com/@artur.klauser/mounting-google-drive-on-raspberry-pi-f5002c7095c2

and i'm stuck at systemd service creation.

I installed radarr and sonarr programs and they have data directories where database files are accessed or written to every minute or similar, and to protect raspberry pi micro sd card from damaging, dietpi system creator moved data folder to external hdd by default. But then my external hdd can't go to sleep because disk is accessed every minute.
And while looking for a solution where to put these data directories i found rclone. I wish to move radarr/sonarr data folders to rclone google mount
My rclone mount will be at `/mnt/gdrive`  with `rclone mount gdrive: /mnt/gdrive`

I ask for help because i'm trying to understand cache flags, but can't figure it out.

Do i need to cache files? i saw in rclone man pages that i need cache flag if files are written and access at the same time.. 
If i must cache files, can i cache them to ram memory, to avoid writing data to micro sd card, but again raspberry pi has just 1 gb of ram memory, so can i restrict size of cache somehow?

To repeat, radarr and sonarr are accessing and writing to few database files on regular (1 minute) time intervals, so what is the best solution for me while running rclone?

**Comment by ncw** [comment]
Can you ask this question on [the rclone forum](https://forum.rclone.org/) please? We try to only put bug requests or feature requests on GitHub - thanks :-)
