### ISSUE TITLE
rclone use alone proxy

### ISSUE THREAD

**Issue by basicfu** [rclone/rclone#4149]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.51.0
- os/arch: darwin/amd64
- go version: go1.13.7

#### What problem are you are trying to solve?
I have read the proxy document
https://rclone.org/faq/#can-i-use-rclone-with-an-http-proxy
But it will be acting on the global,I hope I can be set separately rclone use the proxy,
eg curl
```
curl -x 127.0.0.1:1087 ip.gs
```
rclone can you support?

**Comment by x0b** [comment]
In general, the [forum](https://forum.rclone.org/) is a better fit for questions around rclone usage.

You can set environment variables just for a single command using [```env```](https://www.gnu.org/software/coreutils/manual/html_node/env-invocation.html) on Linux, e.g. 
**```env http_proxy=http://127.0.0.1:1087```**```rclone copy a:foo b:bar```

On Windows, **```cmd /V /C "set http_proxy=http://127.0.0.1:1087&&```**```rclone copy a:foo b:bar"``` should work.

**Comment by basicfu** [comment]
Thank you very much, it effective to me
