### ISSUE TITLE
How do I find out how much I have uploaded on a mount today?

### ISSUE THREAD

**Issue by garrit-schroeder** [rclone/rclone#4154]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.51.0

#### What problem are you are trying to solve?
Some Remotes enforce an upload limit and I would like to "ask" my mounts how much they have uploaded today and then stop the sync process of my uploads.

#### How do you think rclone should be changed to solve that?
Some king of command thats prints a json so i can word with the result would be cool.

**Comment by darthShadow** [comment]
https://rclone.org/rc/#core/stats

**Comment by ncw** [comment]
Great answer from @darthShadow - I'm going to close this now. Questions are preferred on [the rclone forum](https://forum.rclone.org/) - thanks!
