### ISSUE TITLE
scaleway (s3) multipart default settings limit streaming uploads to 5GB filesize

### ISSUE THREAD

**Issue by hex2a** [rclone/rclone#4159]
#### What is the problem you are having with rclone?
the default `--s3-chunk-size` is set to **5M**, scaleway object storage allows only 1000 parts per object (S3 allows 10,000) as stated here:
https://www.scaleway.com/en/docs/s3-multipart-upload/

This leads to a maximum filesize of 5GB when using `rclone mount` with the default settings.

#### What is your rclone version (output from `rclone version`)
v1.51.0

####  Which cloud storage system are you using? (eg Google Drive)
S3 (Scaleway)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone mount

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
ERROR : [removed]: WriteFileHandle.Flush error: multipart upload failed to upload part: InvalidArgument: Part number must be an integer between 1 and 1000, inclusive
        status code: 400, request id: [removed], host id: [removed]
```

**Comment by ncw** [comment]
I view this as a bug in Scaleway's S3 implementation!

There is no way (as far as I know) to query the maximum number of chunks for a multipart upload, but rclone needs to know it in order to raise the chunk size when the maximum number of chunks would be exceeded.

https://github.com/rclone/rclone/blob/c4572ebc91288957356de519a178e9dd21da09e3/backend/s3/s3.go#L2187-L2191

Currently this is a constant in rclone's code

https://github.com/rclone/rclone/blob/c4572ebc91288957356de519a178e9dd21da09e3/backend/s3/s3.go#L899

This could be made a config parameter.

Perhaps better would be to make a provider for "Scaleway" and provide that workaround for the Scaleway provider is detected.

A work-around might be to raise the `--s3-chunk-size`. Note that 5MB is AWS's recommended size and that raising it uses more memory.

@hex2a do you want to work on this?

**Comment by notarobot63** [comment]
I has the same proble and I used @ncw workaround: I set `--s3-chunk-size` at 20M and it works fine.
I uses more ressources but my server can handle it. 
Problem is you have to know what size is your biggest file to adjust in consequence.

**Comment by darkdragon-001** [comment]
@notarobot63 I suggested better / more intelligent defaults in #4255

**Comment by ncw** [comment]
The best solution to this IMHO would be for scaleway to bring their service into s3 compliance and allow 10,000 chunks per file.

Maybe one of you could write to their support and ask them about that? I'm not a scaleway customer alas...

I'd suggest something like

---- 

In your s3 multipart upload docs you state that the maximum number of parts allowed per file is 1,000

https://www.scaleway.com/en/docs/s3-multipart-upload/

However the defacto-standard provided by AWS allows 10,000 parts

https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html

Your service only allowing 1,000 makes it slightly incompatible with S3 and breaks various tools includind rclone - see

https://github.com/rclone/rclone/issues/4159

Would you consider increasing this number to 10,000?

**Comment by ncw** [comment]
Thanks to @ayufan this a fix for this is now merged.

You can use the `max_upload_parts = 1000` parameter in the config file.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.53

**Comment by notarobot63** [comment]
Thanks a lot @ayufan and @ncw for your help and reactivity !

**Comment by psychopatt** [comment]
@ayufan Thanks to your patch I had no problem uploading a 180GB one yesterday, so far no other problems with Scaleway !
@ncw I'm new to GitHub, pull requests and everything but I can give it a try. I'm just not sure about the "3 line patch in to reset the MaxUploadParts" so I might ask for details if it doesn't become clear reading the code.

**Comment by ncw** [comment]
> I'm new to GitHub, pull requests and everything but I can give it a try. I'm just not sure about the "3 line patch in to reset the MaxUploadParts" so I might ask for details if it doesn't become clear reading the code.

Sounds good! Ask away if you need help 😃 It might be best to open a new issue explicitly about making a scaleway provider rather than continuing this one.
