### ISSUE TITLE
System crash under OS X

### ISSUE THREAD

**Issue by tdmartin102** [rclone/rclone#4163]
Under OS X and using rclone to backup to Google Drive rclone causes a system halt **when and ONY when**  The destination Google Drive has insufficient space.

OS Version: 10.15.3 AND 10.13.6
rclone version v1.51.0
- os/arch: darwin/amd64
- go version: go1.14

config = [gdrivemine]
type = drive
client_id = VERYLONGCODE.apps.googleusercontent.com
client_secret = MYSECRET
scope = drive
service_account_file = /Library/Network/Library/Certificates/GSuite/rclone-riemer-com.json
root_folder_id = 0AN_ID

command: rclone -v --drive-impersonate xxx@xxx.xxx --auto-confirm --config $RCLONE_CONFIG sync $BACKUP_DIR gdrivemine:Backup

This happens consistently if the drive is out of space.
Obviously a work around is to assure the drive is NOT out of space.  But a system halt is pretty severe so I thought you should know.

**Comment by animosity22** [comment]
rclone uses fuse so we'd want to figure out whose causing the crash as rclone should not be able to crash itself.

Can you share a debug of what happens when it crashes?

You should raise a bug here as well:

https://osxfuse.github.io/

**Comment by animosity22** [comment]
This looks to be stale. If you need more help, you can always post to https://forums.rclone.org and we are happy to help out.
