### ISSUE TITLE
rmdir cannot --include with folder starting with . ?

### ISSUE THREAD

**Issue by chchia** [rclone/rclone#4165]
I believe this is not a bug, but i just want to know how to use the rmdir command.

i have a root folder with a lot of subfolder, and inside each subfolder there is a folder named ".ABC_store", yes there is a dot in front, and it is not empty (i want to delete it eventhough it is not empty).

i am trying to use

rclone -vv rmdir gCryptNoCache: --include=".ABC_store"

but it just doesnt find anything of folder starting with a dot.

please help guide me how to delete all the .ABC_store directory included in all subdirectory in the root folder?

thank you.

**Comment by animosity22** [comment]
Please use the forums for questions:

https://forums.rclone.org
