### ISSUE TITLE
Preserve config file

### ISSUE THREAD

**Issue by j6s** [rclone/rclone#4167]
#### What is the problem you are having with rclone?
I have my rclone configuration file in a git repository with a script that symlinks it into the correct place. I have noticed, that rclone replaces the config file with a new file (therby removing the symlinked file) instead of writing into the existing file.

It'd be nice if rclone reused the existing file, thereby allowing for symlinked configuration.

#### What is your rclone version (output from `rclone version`)
```
$ rclone version 
rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.6
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian testing, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
not applicable

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
Mainly `rclone config`, which updates the configuration file

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
not applicable

**Comment by darthShadow** [comment]
May be worth checking out this discussion: https://github.com/rclone/rclone/issues/3845

**Comment by j6s** [comment]
Wasn't aware of that issue, sorry.

**Comment by darthShadow** [comment]
I didn't mean to get your issue closed. I just want to see if your problem gets solved with that solution or you had any other suggestions for solving the problem.
