### ISSUE TITLE
Progress Percentage More Than 100%

### ISSUE THREAD

**Issue by ankur0493** [rclone/rclone#4178]
#### What is the problem you are having with rclone?
The transferred percentage for a file shown using `--progress` flag can go over 100% in case of a retry for copy/sync.

#### What is your rclone version (output from `rclone version`)
v1.50.2

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 18.04, 64 bit

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone copy`

During a copy/sync command, if an operation fails due to a network issue and is retried, the `io.Reader` is re-initialised at [operations.go #410](https://github.com/rclone/rclone/blob/master/fs/operations/operations.go#L410). This new `io.Reader` is updated in the `Transfer` object's `Account` at [operations.go #425](https://github.com/rclone/rclone/blob/master/fs/operations/operations.go#L425) through the `UpdateReader` call.

`UpdateReader` replaces the `io.Reader`, but does not reset the `Account.bytes`. Next time when a read is done during retry, the percentage goes above 100%.

This, in turn, can mess up the total stats as well.

![Screenshot from 2020-04-28 17-33-11](https://user-images.githubusercontent.com/7876747/80490780-7ed59580-897f-11ea-9be4-f8fe955178c0.png)

**Comment by ankur0493** [comment]
@ncw Once I have a confirmation that my understanding is correct, I will send a fix for this.

**Comment by ncw** [comment]
I think your analysis is good! I'd certainly like to see a fix for this 😃
