### ISSUE TITLE
--rc-enable-metrics not working

### ISSUE THREAD

**Issue by rubasace** [rclone/rclone#4183]
#### What is the problem you are having with rclone?

I'm trying to enable Prometheus metrics and I'm receiving the following message:

```
Error: unknown flag: --rc-enable-metrics
Usage:
  rclone mount remote:path /path/to/mountpoint [flags]
```

And a list of flags that doesn't contain `--rc-enable-metrics`

#### What is your rclone version (output from `rclone version`)
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Executing on Kubernetes using official image `rclone/rclone`. 

Host is Ubuntu Server 18.04.4 LTS

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`mount drive: /drive-media --config=/config/rclone.conf --uid=${PUID} --gid=${PGID} --umask=022 --allow-other --dir-cache-time=96h --drive-chunk-size=256M --log-level=INFO 
  --timeout=1h --rc --rc-addr=0.0.0.0:5572  --rc-enable-metrics`

**Comment by darthShadow** [comment]
This flag and the corresponding code is not available in the stable version atm, only in the beta versions.

**Comment by rubasace** [comment]
Thanks @darthShadow. Moved to the beta tag and it works. I assumed it was there as it's in master :)
