### ISSUE TITLE
I have a different login page for office 365

### ISSUE THREAD

**Issue by jggo1** [rclone/rclone#4185]
I have a Microsoft account provided by my college
jose.oliveira111@fatec.sp.gov.br
My login page is: login.microsoftonline.com
Not login for with: login.live.com

Auto configuration is not working with my account.

rclone v1.36

**Comment by darthShadow** [comment]
1.36 is quite a couple of years old. 1.51 is the latest version. Please try with that and report back if there are any issues. Closing the issue for now.
