### ISSUE TITLE
Add flag to show upload progress in terminal title?

### ISSUE THREAD

**Issue by orschiro** [rclone/rclone#4187]
Hi there! :-)

[Termdown](https://github.com/trehn/termdown) has this cool feature showing the countdown time in the terminal title. 

This makes it very easy to quickly read the remaining time. 

Could something similar be added to Rclone to show the remaining time to finish the upload or the percentage of upload completed?

Thanks!

![image](https://user-images.githubusercontent.com/170947/80608214-b9e6d000-8a36-11ea-807c-9de468235876.png)

**Comment by ncw** [comment]
So specifically it is the status in the terminal bar you think would be interesting?

Rclone could maybe put the single line stats in the title bar?

This should be an optional flag I think!

It is easy enough to set the terminal title using

    echo -ne "\033]0;test string\007" ; sleep 2

which will set it for 2 seconds and the terminal will undo it.

**Comment by orschiro** [comment]
> Rclone could maybe put the single line stats in the title bar?

Yeah, great!

> This should be an optional flag I think!

Agreed!

**Comment by ncw** [comment]
You want to have a go at this @orschiro ?

**Comment by orschiro** [comment]
Would love to! But don't think my coding skills are sufficient for that. Sorry. :(

**Comment by lasombra** [comment]
@ncw I can take this

**Comment by ncw** [comment]
I've merged this to master now - thank you to @lasombra  for making the patch -  which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54

**Comment by lasombra** [comment]
Thank you, @ncw. :-)

**Comment by orschiro** [comment]
@lasombra thanks so much for this! Question: can it also work with sync?

```
2021/02/18 08:05:02 Fatal error: unknown flag: --print-progress-title
rclone sync "/home/orschiro/GoogleDrive" "orschiro4:Shared/orschiro4@gmail.com/X230" --skip-links --progress --print-progress-title
```

**Comment by orschiro** [comment]
@lasombra thanks so much for this! Question: can it also work with sync?

```
2021/02/18 08:05:02 Fatal error: unknown flag: --print-progress-title
rclone sync "/home/orschiro/GoogleDrive" "orschiro4:Shared/orschiro4@gmail.com/X230" --skip-links --progress --print-progress-title
```

**Comment by lasombra** [comment]
@orschiro that's quite interesting. Can you open a new issue please?

**Comment by orschiro** [comment]
@lasombra of course, thank you!
