### ISSUE TITLE
googlephotos: offer a feature/favorites directory

### ISSUE THREAD

**Issue by philips** [rclone/rclone#4189]
#### What is your current rclone version (output from `rclone version`)?

1.51.0

#### What problem are you are trying to solve?

Backup my “Favorites” images on Google Photos

#### How do you think rclone should be changed to solve that?

Add a new “features/favorites” folder in the Google Photos backend to use the [Features API](https://developers.google.com/photos/library/reference/rest/v1/mediaItems/search#Filters)

See the forum post: https://forum.rclone.org/t/google-photos-add-features-favorites-directory/15991

**Comment by ncw** [comment]
This would be relatively easy to add... Rclone makes a synthetic directory structure for google photos anyway - adding another say `/media/starred` would fit into the framework...

Do you want to have a go at this?

**Comment by philips** [comment]
Sure, I will give it a go in a week or so!

**Comment by philips** [comment]
I implemented this feature over here: https://github.com/rclone/rclone/pull/4247

**Comment by ncw** [comment]
I've merged this feature (thanks @philips :-) to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

**Comment by philips** [comment]
Wow, thanks for the rapid merge!

**Comment by ncw** [comment]
> Wow, thanks for the rapid merge!

It is easy to merge great code :-) Thanks!
