### ISSUE TITLE
dummy image for wiki  - ignore this please

### ISSUE THREAD

**Issue by asdffdsa6131** [rclone/rclone#4195]
i need these images to stay here so i can use them for my rclone wiki.
please do not delete
if you have a question, on rclone forum i am @asdffdsa

![task](https://user-images.githubusercontent.com/42986211/80926944-6642f200-8d68-11ea-8e8b-8d637997c87d.PNG)

![zork](https://user-images.githubusercontent.com/42986211/80926987-d2255a80-8d68-11ea-9dec-5aaab00f96b8.PNG)

**Comment by ncw** [comment]
Fine :-)

I'll close this issue, but the images will remain!
