### ISSUE TITLE
Sudden (random, and temporary) upload speed drop to Google Drive

### ISSUE THREAD

**Issue by framagno** [rclone/rclone#4197]
#### What is the problem you are having with rclone?
For my scheduled backups i use duplicity with rclone (with my own client id and secret). The backup software produces sequential incremental tgz files (250MB each) that uploads one by one via rclone. Normally my delta are so small I would have never noticed anything, but in the last days I've launched a full backup (about 7 TB).

I have about 200Mbit upload speed and i can saturate my bandwidth without problems playing with chunk size (that i normally keep at 64M), but when doing full backups I set bwlimit to avoid hitting the 750GB/day limit.
**The backup starts normally, with each file correctly limited at about 8.5M/s, the suddenly the speed drops to something like 100kb/s**. When a file starts at normal speed, it will keep normal speed during all the upload, across all chunks; when a file starts slow, it will stay slow across all chunks, no matter what.

This is quite annoying because creates "holes" in bandwidth allocation that will make backup last even longer.
![bandwidth](https://user-images.githubusercontent.com/59045883/80947595-c7aea380-8df0-11ea-946e-ee4d164dbe07.png)

To be honest, my first tought was that issue was from Google side, but I'm still posting here for 3 reasons:

1. Maybe I'm doing something wrong (I don't think so, this setup is running in the past 3 years without relevans problems), and someone could notice some configuration error. And by the way I think I have no change to get help from Google.
2. If Google is throttling me in some way, I would expect some error in rclone logs, and in Google API Console. But there is nothing in any of those. Here are the metrics taken from API Console of the last 12 hours (roughly the same time window of the bandwidth screenshot).
I tried to play with tpslimit, chunk size, and no traverse, but nothing changed (and again, never had a 4xx from Google).
![gsuite](https://user-images.githubusercontent.com/59045883/80948831-2d039400-8df3-11ea-9335-d97b10b736f5.png)
3. I have noticed that, if i run rclone in daemon mode mode (_serve webdav_, _serve ftp_ or _mount_), and configure the backup software accordingly, the issue still occurs but a lot less. In _copy_ mode the problem occurs not less than once every 2 hours, in daemon mode i have experienced even 12 hours without issue. So **may** there be something rclone side.

Thank you in advance for any help.

#### What is your rclone version (output from `rclone version`)
rclone v1.51.0
- os/arch: freebsd/amd64
- go version: go1.14.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
FreeBSD 12.1-RELEASE-p4 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy --include duplicity-full.20200503T232932Z.vol365.difftar.gpg /store/maintenance/duplicity/tmp/duplicity-5zaed7qq-tempdir gsuite:darksun_backup

other options passed via environment variables:
RCLONE_DRIVE_USE_TRASH=false
RCLONE_NO_TRAVERSE=true
RCLONE_DRIVE_CHUNK_SIZE=64M
RCLONE_LOG_FILE=file.log
RCLONE_LOG_LEVEL=DEBUG
RCLONE_STATS=10m
RCLONE_STATS_ONE_LINE=true
RCLONE_BWLIMIT=8.5M

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Example without issue:
```
2020/05/04 01:30:12 DEBUG : rclone: Version "v1.51.0" starting with parameters ["/usr/local/bin/rclone" "copy" "--include" "duplicity-full.20200503T232932Z.vol2.difftar.gpg" "/store/maintenance/duplicity/tmp/duplicity-5zaed7qq-tempdir" "gsuite:darksun_backup"]
2020/05/04 01:30:12 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2020/05/04 01:30:12 INFO  : Starting bandwidth limiter at 8.500MBytes/s
2020/05/04 01:30:12 DEBUG : mkstemp-geluzslu-1: Excluded
2020/05/04 01:30:12 DEBUG : mktemp-_k2n618d-4: Excluded
2020/05/04 01:30:12 INFO  : Google drive root 'darksun_backup': Waiting for checks to finish
2020/05/04 01:30:12 INFO  : Google drive root 'darksun_backup': Waiting for transfers to finish
2020/05/04 01:30:13 DEBUG : duplicity-full.20200503T232932Z.vol2.difftar.gpg: Sending chunk 0 length 67108864
2020/05/04 01:30:20 DEBUG : duplicity-full.20200503T232932Z.vol2.difftar.gpg: Sending chunk 67108864 length 67108864
2020/05/04 01:30:27 DEBUG : duplicity-full.20200503T232932Z.vol2.difftar.gpg: Sending chunk 134217728 length 67108864
2020/05/04 01:30:35 DEBUG : duplicity-full.20200503T232932Z.vol2.difftar.gpg: Sending chunk 201326592 length 60793560
2020/05/04 01:30:43 DEBUG : duplicity-full.20200503T232932Z.vol2.difftar.gpg: MD5 = 5457e79e15b567418c5a98491e21d90c OK
2020/05/04 01:30:43 INFO  : duplicity-full.20200503T232932Z.vol2.difftar.gpg: Copied (new)
2020/05/04 01:30:43 INFO  :   249.977M / 249.977 MBytes, 100%, 8.248 MBytes/s, ETA 0s

2020/05/04 01:30:43 DEBUG : 8 go routines active
2020/05/04 01:30:43 DEBUG : rclone: Version "v1.51.0" finishing with parameters ["/usr/local/bin/rclone" "copy" "--include" "duplicity-full.20200503T232932Z.vol2.difftar.gpg" "/store/maintenance/duplicity/tmp/duplicity-5zaed7qq-tempdir" "gsuite:darksun_backup"]
```

Example with issue:
```
2020/05/04 02:43:51 DEBUG : rclone: Version "v1.51.0" starting with parameters ["/usr/local/bin/rclone" "copy" "--include" "duplicity-full.20200503T232932Z.vol75.difftar.gpg" "/store/maintenance/duplicity/tmp/duplicity-5zaed7qq-tempdir" "gsuite:darksun_backup"]
2020/05/04 02:43:51 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2020/05/04 02:43:51 INFO  : Starting bandwidth limiter at 8.500MBytes/s
2020/05/04 02:43:52 DEBUG : mktemp-uu3n2too-77: Excluded
2020/05/04 02:43:52 DEBUG : mkstemp-geluzslu-1: Excluded
2020/05/04 02:43:52 INFO  : Google drive root 'darksun_backup': Waiting for checks to finish
2020/05/04 02:43:52 INFO  : Google drive root 'darksun_backup': Waiting for transfers to finish
2020/05/04 02:43:53 DEBUG : duplicity-full.20200503T232932Z.vol75.difftar.gpg: Sending chunk 0 length 67108864
2020/05/04 02:53:51 DEBUG : duplicity-full.20200503T232932Z.vol75.difftar.gpg: Sending chunk 67108864 length 67108864
2020/05/04 02:53:52 INFO  :    64.250M / 249.990 MBytes, 26%, 109.702 kBytes/s, ETA 28m53s

2020/05/04 03:03:21 DEBUG : duplicity-full.20200503T232932Z.vol75.difftar.gpg: Sending chunk 134217728 length 67108864
2020/05/04 03:03:52 INFO  :   131.215M / 249.990 MBytes, 52%, 111.995 kBytes/s, ETA 18m5s

2020/05/04 03:13:07 DEBUG : duplicity-full.20200503T232932Z.vol75.difftar.gpg: Sending chunk 201326592 length 60807222
2020/05/04 03:13:52 INFO  :   196.965M / 249.990 MBytes, 79%, 112.067 kBytes/s, ETA 8m4s

2020/05/04 03:21:42 DEBUG : duplicity-full.20200503T232932Z.vol75.difftar.gpg: MD5 = 7799b856b205f4e6f7c5014ed191ac93 OK
2020/05/04 03:21:42 INFO  : duplicity-full.20200503T232932Z.vol75.difftar.gpg: Copied (new)
2020/05/04 03:21:42 INFO  :   249.990M / 249.990 MBytes, 100%, 112.763 kBytes/s, ETA 0s

2020/05/04 03:21:42 DEBUG : 6 go routines active
2020/05/04 03:21:42 DEBUG : rclone: Version "v1.51.0" finishing with parameters ["/usr/local/bin/rclone" "copy" "--include" "duplicity-full.20200503T232932Z.vol75.difftar.gpg" "/store/maintenance/duplicity/tmp/duplicity-5zaed7qq-tempdir" "gsuite:darksun_backup"]
```
As you can see, no errors at all, just a crap upload speed.

Here the complete log of the last night.
[rclone.log](https://github.com/rclone/rclone/files/4573495/rclone.log)

**Comment by ncw** [comment]
> As you can see, no errors at all, just a crap upload speed.

Indeed!

Here are some ideas
- Google has a slow machine in the cluster which your upload hits sometimes
- You have something doing QoS which decides to throttle that stream (eg Firewall, Router, Your ISP)
- Packet loss causing TCP throttling

Note that we are almost certainly re-using the HTTP connection to send subsequent chunks so I conjecture the whole transfer is does on a single TCP connection.

You could try `-drive-disable-http2=false` to allow rclone to use HTTP2 to mix things up a bit.

If this is a problem with rclone then I would suspect the bandwidth limiter to be the problem. I haven't had reports of the bandwidth limiter not working properly... Maybe you could try a backup without the limiter to see if you get the same problem.

Here is it is if you want to take a look

https://github.com/rclone/rclone/blob/f2b1fedc4fd064a98de68a0f0d5afef5bc4e6012/fs/accounting/token_bucket.go#L104-L108

**Comment by framagno** [comment]
Thank you for the quick answer!

Some more tests done.
- I can confirm the issue happening with `--drive-disable-http2=false` too
- I can confirm the issue happens without bwlimit, so it's not related to the bandwidth limiter
- I **do** have QoS on my system, but I can confirm that the traffic is correctly tagged, I am currently using my shaper (PF firewall, on FreeBSD) instead of the rclone's one, in order to test the previous point (and this way I can change on the fly the limit without the remote control). The queue has 61.50 Mbps guaranteed, and 85Mbps hard cap.
```
queue  rclone on eth0 bandwidth 61.50Mb qlimit 500 hfsc( upperlimit 85Mb )
  [ pkts:   95116065  bytes: 136387198489  dropped pkts:    927 bytes: 1329318 ]
  [ qlength: 251/500 ]
  [ measured:  6627.6 packets/s, 76.03Mb/s ]
```
- ISP throttling is a thing, for sure, but if I get another rclone instance while the first is going slow, the latter goes full speed. If I kill the first instance and retry the upload, it goes full speed. My bandwidth is not showing to be restricted in any way.

To be honest, the issue Google side is the only option that remains, but I still think is such an improbable scenario, still possible though.
And there is one more aspect that makes me fuzzy. Why in `copy` mode the issue occurs very soon, while in `serve` mode occurs a lot later? If there is a chance to get a connection to a crappy server, the chance should be the same, regardless the mode. Unless there is a different connection strategy in `serve` mode that I am not aware of.
Now i'm running with the following syntax:
`rclone serve webdav gsuite: --drive-use-trash=false --drive-chunk-size 64M --tpslimit 1 --cache-dir /path/to/cache --vfs-cache-mode writes --log-file /path/to/log --log-level DEBUG --stats 1m`
I will try to provide debug log if/when the issue will occurr again while serving.

Anyway, I will still be able to backup my data like I always did, I will just go slower than I could.
Thank you again for your assistance and for this great software of wich I am, anyway, an happy user.

**Comment by ncw** [comment]
Excellent debugging :-)

The one thing that this issue reminds me of is a similar issue I saw on a Windows computer where the TCP sharing strategy was set incorrectly.

Now you are using FreeBSD and I know very little about that so it may/may not be relevant!



> To be honest, the issue Google side is the only option that remains, but I still think is such an improbable scenario, still possible though.

Difficult to know for sure!

I have had a request for a `--min-bandwidth` flag which would drop connections if the bandwidth fell below a limit for a time. It would be easy enough to implement but I think the criteria of exactly when you'd drop the connection would be hard. If we had this then you could set it and rclone would drop and retry the connections.



> And there is one more aspect that makes me fuzzy. Why in `copy` mode the issue occurs very soon, while in `serve` mode occurs a lot later? If there is a chance to get a connection to a crappy server, the chance should be the same, regardless the mode. Unless there is a different connection strategy in `serve` mode that I am not aware of.

They are using slightly different rclone internals... I think that the webdav upload will be doing an upload where the size isn't known in advance whereas the copy will do.

No idea why that might make a difference though!

> Anyway, I will still be able to backup my data like I always did, I will just go slower than I could.
Thank you again for your assistance and for this great software of wich I am, anyway, an happy user.

:-) Let me know if you have any more thoughts on this!

**Comment by framagno** [comment]
More clues that is not an rclone problem. Seems **that is happening less frequently now**, without changing anything my side.
I switched to serve webdav mode and it went smoothly for more than 12 hours. It happened again only once in the last 24 hours, the last night.

![Cattura](https://user-images.githubusercontent.com/59045883/81144750-03727600-8f75-11ea-8c28-54edb3198c93.PNG)

I still prefer limiting with my firewall because, in serve mode rclone doesn't know in advance the size of each file, so it limits the average bandwith, but with spikes. And moreover there is not an option (yet?) to limit outbound traffic only.
In this scenario the firewall is doing a better job.

The `---min-bandwidth` option would be great for me, because I work with fixed size files, so I know that if the upload is not finished within X seconds, there's something wrong. Strong thumbs up on this option for me.

Lastly (then I promise I will stop annoying you), the final clue that is a Google issue (at leat at 99.99% chance) is this log fragment from tonight:
```
2020/05/06 06:05:48 INFO  :
Transferred:      121.936G / 122.314 GBytes, 100%, 9.028 MBytes/s, ETA 42s
Transferred:          501 / 503, 100%
Elapsed time:   3h50m30.4s
Transferring:
 * darksun_backup/duplici…51Z.vol500.difftar.gpg: 26% /250.008M, 93.254k/s, 33m25s
 * darksun_backup/duplici…51Z.vol501.difftar.gpg: 18% /249.982M, 9.069M/s, 22s
```
A second file started when the first was still in progress.
Same backup session, same rclone instance, same firewall settings... one transfer was normal, the other was throttled.

So my backups are going on, maybe just a little slower.
Thank you so much for your kind assistance, it has been a pleasure to talk with you, and keep up the great job you're doing.

**Comment by ncw** [comment]
Here is the issue for min-bandwidth https://github.com/rclone/rclone/issues/2122

If you want to subscribe to it (or even help implement it!)

Thanks for your kind words, and as I think we've probably gone as far as we can on this I'll close this issue. Do feel free to add to it if more info comes to light though!
