### ISSUE TITLE
Rclone hashsum does not show value with SFTP remote

### ISSUE THREAD

**Issue by AntonAleksandrov13** [rclone/rclone#4198]
I have used Rclone hashsum md5 command on S3 bucket and it seems to be working as expected. However, when I run the same command against an SFTP server, it only outputs the name of a file, and the hash value is an empty string.
Expected output:
md5_hash filename.extension

Got:
                  filename.extension

**Comment by AntonAleksandrov13** [comment]
Okay, I see. The SFTP server I am connecting to is not mine, therefore, I cannot change the path of md5sum_command. 
I have a follow-up question. Would misconfiguration in the md5sum_command path influence rclone sync or copy operations? As far as I know, rclone does check md5sum before it sending file

**Comment by ncw** [comment]
> Okay, I see. The SFTP server I am connecting to is not mine, therefore, I cannot change the path of md5sum_command.

Rclone tries to detect it in a couple of places and then sets `md5sum_command` to blank if it isn't found. If you know the server has it in a a particular place you can set it by hand.



> I have a follow-up question. Would misconfiguration in the md5sum_command path influence rclone sync or copy operations? As far as I know, rclone does check md5sum before it sending file

If the server isn't providing md5sums then rclone can't check them. It shouldn't produce any errors though.

**Comment by animosity22** [comment]
This looks to be answered. Questions can always be posted on the forums rather than opening an issue.

https://forums.rclone.org
