### ISSUE TITLE
HDFS support

### ISSUE THREAD

**Issue by mlanner** [rclone/rclone#42]
Hi,

Any thoughts or plans around HDFS support? It could be very nice to have a way to, for example, bring a given data set out of Swift into Hadoop to run jobs on.

**Comment by ncw** [comment]
Interesting idea!  I don't know anything about HDFS so I've done a small amount of reading...

rclone would work fine with HDFS if it was mounted in the file system (eg using NFS Proxy or Fuse).  rclone is very undemanding on the local filesystem it scans directories, opens and reads or writes files in sequence which I think should all be supported by HDFS.

Alternatively it could use the API.  There has been come work using go with hadoop
  * https://github.com/hortonworks/gohadoop/ (HDFS not supported yet though)

Or use [LibHDFS](http://wiki.apache.org/hadoop/LibHDFS)

I don't have access to a hadoop cluster so I can't work on this, but would be grateful for assistance or patches!

**Comment by mlanner** [comment]
Hi Nick,

Thanks for the quick response and links. I started looking at those ... and some others. I will probably spin up a test Hadoop cluster to see what I can do. I'll update this when/if I have any updates.

**Comment by seanorama** [comment]
Anyone played more with making this happen?

**Comment by ncw** [comment]
> Anyone played more with making this happen?

Not as far as I know.  Do you want to have a go?

**Comment by volth** [comment]
Using HDFS API it possible to get hashes of file chunks without reading file content.
So using FUSE is not optimal here.

**Comment by ei-grad** [comment]
Here is a native hdfs client library: https://github.com/colinmarc/hdfs

**Comment by urykhy** [comment]
I try to make HDFS support. Backend tests passed, but hashes not implemented.

**Comment by ncw** [comment]
> I try to make HDFS support. Backend tests passed, but hashes not implemented.

Great work!

- Is there a docker image we can test against?
- What have you been testing against?
- Are there hashes we could use?
- Are you going to submit a PR?

**Comment by urykhy** [comment]
> Is there a docker image we can test against?

i fail to find simple docker image, maybe [this](https://jcristharif.com/hadoop-test-cluster/) can help.

> What have you been testing against?

i run tests with [this](https://bitbucket.org/urykhy/docker/src/master/hadoop/) image.

> Are there hashes we could use?

i have read about hadoop checksums, and it's complicated:
* hadoop support different hashings methods [MD5MD5CRC and COMPOSITE_CRC](https://wideops.com/new-file-checksum-feature-lets-you-validate-data-transfers-between-hdfs-and-cloud-storage/)
* default method [MD5MD5CRC](https://issues.apache.org/jira/browse/HADOOP-3981) depends on configuration

> Are you going to submit a PR?

sure.

**Comment by ncw** [comment]
> > Is there a docker image we can test against?
> 
> i fail to find simple docker image, maybe [this](https://jcristharif.com/hadoop-test-cluster/) can help.
> 
> > What have you been testing against?
> 
> i run tests with [this](https://bitbucket.org/urykhy/docker/src/master/hadoop/) image. it's a bit heavy, spark can be removed.

OK

> > Are there hashes we could use?
> 
> i have read about hadoop checksums, and it's complicated:
> 
> * hadoop support different hashings methods [MD5MD5CRC and COMPOSITE_CRC](https://wideops.com/new-file-checksum-feature-lets-you-validate-data-transfers-between-hdfs-and-cloud-storage/)
> * default method [MD5MD5CRC](https://issues.apache.org/jira/browse/HADOOP-3981) depends on configuration

MD5MD5CRC looks like the S3 scheme of md5sums of md5sums which in practice is not at all useful since you don't know the block sizes.

Composite CRC looks like it could be useful though I didn't see how to calculate it.... Rclone supports CRC32-C already BTW.

> > Are you going to submit a PR?

I see it :-)

**Comment by urykhy** [comment]
just to note, i working on [PR](https://github.com/colinmarc/hdfs/pull/254) to support composite_crc(crc32) checksums.

**Comment by axsaucedo** [comment]
+1 - this would be extremely useful 👍

**Comment by ncw** [comment]
Thanks to @urykhy I've merged the HDFS backend into [the latest beta](https://beta.rclone.org) now.

The first beta with the code in is [v1.54.0-beta.5040.71edc75ca](https://beta.rclone.org/v1.54.0-beta.5040.71edc75ca/) on branch [master](https://github.com/rclone/rclone/tree/master) (uploaded in 15-30 mins)

Please test and put comments here - thank you :-)

Note that this doesn't support hashes yet - I think @urykhy is working on that at the moment.

**Comment by miguelpuyol** [comment]
I tested it in a kubernetes cluster to upload data to another S3 remote and it works like a charm! Thank you all for the great tool!

**Comment by RafalSkolasinski** [comment]
Thank you guys for this, I see that `beta` image is available on docker hub. We will probably test `hdfs` functionality at some point over next week or so and let you know how it goes!

**Comment by RafalSkolasinski** [comment]
Hi, I tested the beta
```
rclone v1.54.0-beta.5058.35a4de203
- os/arch: linux/amd64
- go version: go1.15.6
```
with basic file / directory operations and it worked fine.

I did test against your docker 
```
docker run --rm --name "rclone-hdfs" -p 127.0.0.1:9866:9866 -p 127.0.0.1:8020:8020 --hostname "rclone-hdfs" rclone/test-hdfs
```
using 
```
[hdfs-docker]
type = hdfs
namenode = localhost:8020
username = root
```
config as well as against k8s deployment in kind using this [helm charts](https://artifacthub.io/packages/helm/gradiant/hdfs).

For the k8s config was 
```
[hdfs-kind]
type = hdfs
namenode = localhost:8020
username = hdfs
```
after the port-forwarding: `kubectl port-forward svc/hdfs-namenode 8020:8020`.

**Comment by RafalSkolasinski** [comment]
I wonder if you have any plans to include `kerberos` auth support in the `hdfs` module?

**Comment by RafalSkolasinski** [comment]
Actually, scratch that about the `k8s` deployment. It only worked up to authentication and folder listing / creations. 
Didn't allow to `copy` file over to it - but this may be something wrong with these helm-charts...

**Comment by everpeace** [comment]
> `kerberos` auth support in the `hdfs` module?

+1

**Comment by axsaucedo** [comment]
> kerberos auth support in the hdfs module?
+1

**Comment by RafalSkolasinski** [comment]
Also would be good to know if `httpfs` support of HDFS will be something `rclone` could include?

**Comment by ncw** [comment]
@urykhy what do you think?

- kerberos auth support in the hdfs module
-  httpfs support of HDFS

**Comment by urykhy** [comment]
kerberos - supported by [library](https://godoc.org/github.com/colinmarc/hdfs#ClientOptions), so it must be simple to enable. i will play with it.

on [httpfs](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/WebHDFS.html#Introduction) - i think we can implement it as well.

**Comment by ivandeex** [comment]
@RafalSkolasinski 
 
We are close to release 1.54 with hdfs+kerberos.

> Also would be good to know if `httpfs` support of HDFS will be something `rclone` could include?

Please submit as a separate request so it does not get lost in this overgrown ticket.

Thanks

**Comment by ncw** [comment]
I'm going to close this ticket now - thank you very for implementing it @urykhy :-)

Please make new tickets with feature requests for the HDFS backend.
