### ISSUE TITLE
Run Docker image with unprivileged user

### ISSUE THREAD

**Issue by alexanderadam** [rclone/rclone#4208]
#### What is your current rclone version (output from `rclone version`)?

[`1.51.0`](https://hub.docker.com/r/rclone/rclone/tags)

#### What problem are you are trying to solve?

[Using an unprivileged user is considered best practice](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user):

> If a service can run without privileges, use `USER` to change to a non-root user.

There are many blog posts out there, which describe why this is the case (for instance [this one](https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b)).

#### How do you think rclone should be changed to solve that?

Adding a user and using it, too.
Other images like [the one from](https://github.com/tynor88/docker-rclone-mount/blob/5f4f805503a8331bed19d10b840b9ac7542f35de/Dockerfile#L53-L56) @tynor88 [are doing this](https://github.com/tynor88/docker-rclone-mount/blob/5f4f805503a8331bed19d10b840b9ac7542f35de/Dockerfile#L53-L56), in case you need a reference.

**PS:** Thank you for your work! rclone is a great tool!

**Comment by tynor88** [comment]
Feel free to [use mine af a referemce](https://github.com/tynor88/docker-rclone-mount/) . I will be happy to stop maintaning it, due to time pressure 👍

**Comment by ncw** [comment]
So you are suggesting adding something like this to the docker file?

```
RUN groupadd -g 999 rclone && \
    useradd -r -u 999 -g rclone rclone
USER rclone
```

In the [install instructions](https://rclone.org/install/) we suggest running with `--user $(id -u):$(id -g)` which presumably has much the same effect, security-wise?

What would the backwards compatibility impact be of adding a USER statement - will we break people's setups?

@tynor88 your Dockerfile doesn't actually have a USER statement in it? Is it changing the userid some other way?

**Comment by alexanderadam** [comment]
> In the [install instructions](https://rclone.org/install/) we suggest running with `--user $(id -u):$(id -g)` which presumably has much the same effect, security-wise?

Good point! I guess it's fine then.

> @tynor88 your Dockerfile doesn't actually have a USER statement in it? Is it changing the userid some other way?

He switches [in the run script](https://github.com/tynor88/docker-rclone-mount/blob/5f4f805503a8331bed19d10b840b9ac7542f35de/root/etc/services.d/rclone-mount/run#L14) with `s6-setuidgid`.
