### ISSUE TITLE
Uploading to Google drive computer folder

### ISSUE THREAD

**Issue by rpawar0703** [rclone/rclone#4212]
I'm using rclone version 1.51.0 on windows 10 64bit PC.

I want to ask if there's any way to upload to google drive's computer folder like Backup and Sync software does so that my stuff doesn't take up any space on google drive?

**Comment by darthShadow** [comment]
As per the docs: https://rclone.org/drive/#root-folder-id
the API only gives read-only access to the Computers folder. Anything else results in a 500 error code from the API.

**Comment by calisro** [comment]
You could use the application folder though.

**Comment by animosity22** [comment]
If you need some help, you can post questions to https://forum.rclone.org rather than opening an issue as we like to keep issues for bugs/feature requests and not general use questions.

**Comment by ncw** [comment]
I'll close this now since I think we've answered the original question, in the negative alas. Do ask on the forum if you need more help though.
