### ISSUE TITLE
Bidirectional synchronization

### ISSUE THREAD

**Issue by densu90** [rclone/rclone#4213]
#### What is your current rclone version (output from `rclone version`)?

1.51

#### What problem are you are trying to solve?

Bidirectional synchronization. If I use "sync" it will basically do smart backup folder1 to folder2 (sync %folder1% %folder2%).

#### How do you think rclone should be changed to solve that?

Could you advise/create command which will perform smart bidirectional synchronization by time/version stamp like, for example, "onedrive" windows app or "goodsync". Prefarebly with optionnal local logging and (version) backuping (to separate or ignorred folder).

**Comment by animosity22** [comment]
For questions on how to, please use the forums https://forums.rclone.org as this is not an issue.

**Comment by densu90** [comment]
It's not an a how-to question. It's polite way to say "everyone wait this feature from 2015 and yet it is gone. Do you intend to implement it ever?". If not - just say so slightly.

**Comment by ncw** [comment]
Here is what [I wrote in the forum](https://forum.rclone.org/t/semi-rclone-bisync-two-way-sync-with-rclone-copy/8995) last time this came up

rclone doesn’t have a bisync solution at the moment.

There are some ideas on implementing it

https://github.com/ncw/rclone/issues/2870
https://github.com/ncw/rclone/issues/118

And even a 3rd party tool or two

https://github.com/ncw/rclone/wiki/Third-Party-Integrations-with-rclone#rclonesync-v2
https://github.com/ncw/rclone/wiki/Third-Party-Integrations-with-rclone#upback

It isn't a trivial feature to implement.

**Comment by densu90** [comment]
Hi Nick,
Thx!
I had read all of that topics before write here. Unfortunately i am struggling to do it router-based, so, i will face "compatibility" or "available resources" issue if try to do it with "naked" python script (which is all of them, basically). If I missed some "more binary without dependencies" solution here point me please. I would be glad to compile present solutions for ARM v7 (entware) if it possible, but i am hugely more "security", "IT environment control", "server" and "business automation" than "linux developement" to do so.
What about "copy solution" it will be "inconvenient" (so to speak) to delete files. And every new local sync point will bring even more inconvenients. Even if it will manage files versions correctly.
For this reason i have interest if this functionallity will be expected someware in 6-7 months from now, or i should try to find something else which will fitt me, even if it will not be so good as rclone is.
Thanks again for your participation.

**Comment by ncw** [comment]
> For this reason i have interest if this functionallity will be expected someware in 6-7 months from now, or i should try to find something else which will fitt me, even if it will not be so good as rclone already is.

I'm looking for a volunteer to do the work, or failing that a lot of spare time! 

It is a feature I'd like to have in rclone but it is a lot of work!
