### ISSUE TITLE
Shortcut remote

### ISSUE THREAD

**Issue by ferferga** [rclone/rclone#4222]
#### What is your current rclone version (output from `rclone version`)?

**1.51**

#### What problem are you are trying to solve?
I have a many schedules tasks with remotes like **MyDrive:path1/path2/path3/path4**

I would like to make my commands shorter.

#### How do you think rclone should be changed to solve that?
Would be great if I could simply make **shortcut remotes** by adding this to my config file:

```
[BackupRemote]
remote = MyDrive:path1/path2/path3/path4
```
So I can do **rclone ``whatever`` *source* BackupRemote:**

And it will wrap that long command into that single sentence. The shortcut will be a root, so children paths will work as well. So, for example, **BackupRemote:LivingRoomPC** is the equivalent of **MyDrive:path1/path2/path3/path4/LivingRoomPC**

**Comment by animosity22** [comment]
You can already do that:

https://rclone.org/alias/

Please ask questions on the forums as that's step #2 on the feature request.

Thanks!

**Comment by ferferga** [comment]
@animosity22 No idea, sorry!

Thank you very much!
