### ISSUE TITLE
Leave unicode filenames de-normalized during sync

### ISSUE THREAD

**Issue by benz2012** [rclone/rclone#4228]
#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7
```

#### What problem are you are trying to solve?
As discussed on the forum post [Unique Unicode Characters lead to Duplicate object found](https://forum.rclone.org/t/unique-unicode-characters-lead-to-duplicate-object-found/16314), rclone normalizes Unicode characters in filenames during the sync routine. This has many benefits as described by Nick Craig-Wood.

It presents an unintended side-effect when you have two+ files with names that are near-identical with the exception of the _similar_ Unicode characters in that name, such as `é` and `é` which evaluate to 0x65+0x301 and 0xE9 respectively.

In my use case, I would like rclone to treat these characters as unique, but it does not.

#### How do you think rclone should be changed to solve that?
As Nick said:
> To avoid this we'd need another flag to skip the normalization in the sync routines.

So I propose we add a new _Non Backend Flag_ named `--no-unicode-normalization` however this is very similar to the currently deprecated flag named `--local-no-unicode-normalization` and that might add confusion, so I'm curious to hear if anyone thinks the flag should use another name?

**Comment by benz2012** [comment]
I will attempt to add this flag/feature.

**Comment by ncw** [comment]
Great!

Here is what needs a flag around it

https://github.com/rclone/rclone/blob/52b7337d28f93249ea3f301876f9b3c77ddd1340/fs/march/march.go#L56-L58
