### ISSUE TITLE
[minio] setup tries sub domain for bucket name, but can't find it

### ISSUE THREAD

**Issue by arthurlogilab** [rclone/rclone#4231]
#### What is the problem you are having with rclone?

```
$ rclone mount miniointra:rclone-arthur /tmp/rclone/                  
2020/05/14 10:09:51 ERROR : /: Dir.Stat error: RequestError: send request failed
caused by: Get https://rclone-arthur.minio.intra.example.org/?delimiter=%2F&max-keys=1000&prefix=: x509: certificate is valid for *.numericable.fr, numericable.fr, not rclone-arthur.minio.intra.logilab.fr
2020/05/14 10:10:45 ERROR : /: Dir.Stat error: RequestError: send request failed
caused by: Get https://rclone-arthur.minio.intra.example.org/?delimiter=%2F&max-keys=1000&prefix=: x509: certificate is valid for *.numericable.fr, numericable.fr, not rclone-arthur.minio.intra.logilab.fr
```                

The bucket name seems to generate a subdomain which we don't have in our setup (only minio.intra.example.org resolves to a DNS entry. 

Is there a parameter for this ? Is the minion setup faulty ? Does it require wildcard DNS etc?

#### What is your rclone version (output from `rclone version`)

```
rclone --version                                                     
rclone v1.48.0
- os/arch: linux/amd64
- go version: go1.12.6


```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu bionic

####  Which cloud storage system are you using? (eg Google Drive)

Self hosted minio over https (with letsencrypt certificates) 

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
$ rclone mount miniointra:rclone-arthur /tmp/rclone/                  
```

**Comment by calisro** [comment]
That looks like a server side configuration on minio.

**Comment by ncw** [comment]
> The bucket name seems to generate a subdomain which we don't have in our setup (only minio.intra.example.org resolves to a DNS entry.

This is now the default **not** to use path style - see [AWS announcement](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/)

I think setting your `provider=Minio` would fix it as would adding `force_path_style=true` in the config file, or would setting up a wildcard DNS for the minio server.

Note also rclone 1.48 is fairly old now so may well have the wrong defaults!

**Comment by animosity22** [comment]
Looks to be answered.
