### ISSUE TITLE
rclone treats empty string "" as the current directory 

### ISSUE THREAD

**Issue by fspoettel** [rclone/rclone#4239]
#### What is the problem you are having with rclone?
First things first: This is the result of a big user error & pure stupidity on my side. I figured I should still report it since it seems like a footgun. I can't quite wrap around why `rclone` would do what it did in this case.

I tried running `rclone purge "$VAR"` where $VAR should have interpolated to `remote:path` but wasn't defined (due to a typo). Before I realized my error, large parts of my home directory were gone before I could stop the command. I only had a `b2` and `crypt` remote configured, no local remote or similiar. Looking at the docs for purge, it does not seem like this should happen.

#### What is your rclone version (output from `rclone version`)
v1.51.0

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 20.04 64-bit

####  Which cloud storage system are you using? (eg Google Drive)
B2, although it does not matter here

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone purge "$ACCIDENTALLY_EMPTY_ENV_VAR"`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Don't have any, don't want to nuke my home dir again

Edit:Added missing `""` around env var in command in order to correctly illustrate the problem

**Comment by animosity22** [comment]
That doesn't do anything for me when I try that.

```
felix@gemini:~$ rclone purge $BLAH -vv --dry-run
2020/05/16 07:45:37 DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "purge" "-vv" "--dry-run"]
Usage:
  rclone purge remote:path [flags]

Flags:
  -h, --help   help for purge

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.
Command purge needs 1 arguments minimum: you provided 0 non flag arguments: []
```

It just errors out.

**Comment by fspoettel** [comment]
@animosity22 Sorry, the command should read `rclone purge "$BLAH".  `rclone purge $BLAH` doesn't do anything for me as well.

**Comment by fspoettel** [comment]
These two outputs should illustrate the problem. Sorry for the mismatch in `rclone` versions, I just re-installed the OS :wink: 

With an existing env var:
```
felix ~ $ export FOO="foo:bar/" && rclone purge "$FOO" -vv --dry-run
2020/05/16 14:05:39 DEBUG : rclone: Version "v1.50.2" starting with parameters ["rclone" "purge" "foo:bar/" "-vv" "--dry-run"]
2020/05/16 14:05:39 NOTICE: Config file "/home/felix/.config/rclone/rclone.conf" not found - using defaults
2020/05/16 14:05:39 Failed to create file system for "foo:bar/": didn't find section in config file
```

Without an existing env var:
```
2020/05/16 14:06:15 DEBUG : rclone: Version "v1.50.2" starting with parameters ["rclone" "purge" "" "-vv" "--dry-run"]
2020/05/16 14:06:15 NOTICE: Config file "/home/felix/.config/rclone/rclone.conf" not found - using defaults
2020/05/16 14:06:15 NOTICE: Local file system at /home/felix: Not purging as --dry-run set
2020/05/16 14:06:15 DEBUG : 3 go routines active
2020/05/16 14:06:15 DEBUG : rclone: Version "v1.50.2" finishing with parameters ["rclone" "purge" "" "-vv" "--dry-run"]
```

**Comment by animosity22** [comment]
Yeah, in general the commands are you running in the local path if nothing is set. You can test with any command rclone ls as an example too.

Generally, you'd want to programmatically add a check the environment variable is set to avoid things like this if you using them in code to be safe.

What is it you want to happen? Confirmation before a delete? You can add your comments to this issue.

https://github.com/rclone/rclone/issues/1574

Or are you expecting something else?

**Comment by fspoettel** [comment]
@animosity22 Thanks for clearing up why this happened.

Is this mentioned anywhere in the docs? If so I must have missed it. The `purge` documentation only mentions `remote:path` which suggests that it would actually check whether I'm working against a configured remote. The documentation also mentions `source:sourcePath` in other cases in which case this behavior seems a bit misleading?

I will add a comment to the issue that you linked, thanks a lot. Feel free to close this issue if you see this as expected behavior.

**Comment by animosity22** [comment]
In general any rclone command can be run against a local path, not sure it says that anywhere per se.

What would you want it to say instead to make it more clear? It can be updated.

**Comment by fspoettel** [comment]
Reading over the docs again, there are a few things to mention:
1. It is mentioned that a _remote_ can be a local path [here](https://rclone.org/docs/#syntax-of-remote-paths) and in detail [here](https://rclone.org/local/). The [purge](https://rclone.org/commands/rclone_purge/) command takes the argument `remote:path` so I guess this whole thing is mentioned in the docs in some way.
2. However, `rclone` lets you configure explicit _remotes_ with `config`. As a user, I now made the assumption that `rclone` would as least warn me when I try to `rm -rf` a directory that is not configured as an explicit remote. That is obviously not the case.

Would it make sense to warn when purge is called with what amounts to an empty argument? I would argue that deleting the local $CWD with `rclone purge` is almost always user error and should involve a safeguard of some sort.

**Comment by calisro** [comment]
The empty argument probably shouldn't happen.

**Comment by animosity22** [comment]
Can you explain what you mean @calisro ? I'm not sure if you mean on the OS side or rclone should not.

**Comment by calisro** [comment]
I just mean that rclone cmd "" probably should error out.

**Comment by animosity22** [comment]
Ok, that's where I thought you were going but confirmation is always good.

I'll update the title of the issue as that does seem to make sense. 

That seems to the case for any command as it is repeatable for purge / ls / copy / etc

**Comment by ncw** [comment]
I see - that is not good :-(  It looks like the path parser is willing to accept "" as a synonym for the current directory. Internally rclone uses "" to mean the root of a transfer which is probably why, but it is no good for interactions with the user!

I fixed this here if you want to have a go

https://beta.rclone.org/v1.51.0-346-geb6e9b19-beta/ (uploaded in 15-30 mins)

@fspoettel very sorry for the trouble this caused you.

**Comment by fspoettel** [comment]
Thank you very much for taking a look and fixing this quickly @ncw and all. :+1: Happy to see that my sacrifice was not in vain :laughing:
