### ISSUE TITLE
Liberapay and/or github sponsors

### ISSUE THREAD

**Issue by thibaultmol** [rclone/rclone#4243]
It would be nice if the project had also had a Liberapay account or had Github Sponsors enabled, so there are non-paypal alternatives that aren't bitcoin.

Liberapay doesn't charge any processing fees itself, only paymentprocessor fee

Github sponsors doesn't charge any fees at all

(while Paypal charges a decent amount of fees iirc)

**Comment by negative0** [comment]
@ncw

**Comment by thibaultmol** [comment]
oh, I just realized that his github account has sponsors enabled. the project doesn't. That's why I didn't see it

**Comment by ncw** [comment]
I'm just in the process of re-working all the sponsorships / librapay / patreon / paypal for the 1.52 launch :-)

**Comment by animosity22** [comment]
I think @ncw has this one handled so going to close it out.

**Comment by thibaultmol** [comment]
For anybody stumbling upon this thread. Liberapay account for Nick/Rclone is: https://liberapay.com/ncw/
