### ISSUE TITLE
Replace hard-coded HTTP status codes with stdlib provided ones

### ISSUE THREAD

**Issue by FileGo** [rclone/rclone#4246]
#### What is your current rclone version (output from `rclone version`)?

rclone v1.51.0-331-gd04d4edc-4087-beta
- os/arch: linux/amd64
- go version: go1.14.2

#### What problem are you are trying to solve?

I have noticed OneDrive backend package contains several references to hard-coded HTTP status codes:

```
// retryErrorCodes is a slice of error codes that we will retry
var retryErrorCodes = []int{
	429, // Too Many Requests.
	500, // Internal Server Error
	502, // Bad Gateway
	503, // Service Unavailable
	504, // Gateway Timeout
	509, // Bandwidth Limit Exceeded
}
```

```
switch resp.StatusCode {
		case 401:
		.....
```

#### How do you think rclone should be changed to solve that?

They should probably be replaced with status codes from [net/http](https://golang.org/src/net/http/status.go) stdlib.

**Comment by animosity22** [comment]
Is there a reason you didn't use the issue or feature template? Do we need to improve them or was something confusing?

**Comment by FileGo** [comment]
Sorry, I'm fairly new to GitHub. Updated the issue according to the template. Thanks.

**Comment by animosity22** [comment]
No worries! Just trying to make the intake a bit better so I was asking to help us improve. Appreciate the update!

**Comment by ncw** [comment]
There are hard coded HTTP status codes in a lot of rclone!

I'm not too worried about them as
- they don't change
- the provider API docs generally refer to the numbers - eg 503 so it is helpful having the numbers here rather than the opaque constants you'd have to look up into numbers...

So I'm saying I think the http status codes are the lingua franca of REST and we should probably just live with them...

**Comment by creativeprojects** [comment]
I'm usually a big fan of constants, but this one is a special case: For example there are quite often confusion between 401 and 403. I had the case recently where the API was using the wrong one in some places.

I think this is better seen as a number 👍

**Comment by ncw** [comment]
@FileGo thanks for bringing this up for discussion.

I think that we will leave the http status codes as numbers for the reasons above.

Always good to discuss things though, so thanks for making the issue.
