### ISSUE TITLE
Detect expired token (Google Drive)

### ISSUE THREAD

**Issue by tbm** [rclone/rclone#4250]
#### What is the problem you are having with rclone?

When I run rclone on a previously configured Google Drive, I get:

```
2020/05/19 15:08:34 Failed to create file system for "spi-drive:audit/2019/README.pdf": couldn't find root directory ID: Get https://www.googleapis.com/drive/v3/files/root?alt=json&fields=id&prettyPrint=false&supportsAllDrives=true: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```

This issue was previously reported in #3073 but this was closed because the bug reporter didn't reply.

In this issue @ncw said:

> I've never seen it go wrong but it does go wrong sometimes 

> So what I think you are asking for is that rclone detects this error
> And translates it into something more user friendly.

> This should definitely not be happening in normal operation though - can you replicate the problem reliably? If so can you work out why it is happening?

The same still applies.  Yes, the error should be more user friendly.

FWIW, if I removed the expired token from the config, I get:

> 2020/05/15 18:14:30 Failed to create file system for "spi-drive:": drive: failed when making oauth client: failed to create oauth client: empty token found - 
please run rclone config again

which is more user friendly.

Anyway, why is this happening?  I configured the Google Drive in rclone last year and haven't used it in 10 months.  So I guess rclone doesn't cope well with really old tokens.

I can repeat 100%.  I also saved the old config (with the old token), ran `rclone config` to get a new token; when I copy the old config in place I can reproduce this issue 100%.

#### What is your rclone version (output from `rclone version`)

I was using 1.45 and 1.50.2 from Debian previously but I've also verified that it happens with the Linux binary from GitHub: version 1.51.0.

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian, 64 bit x86

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Output with `-vv`:

```
~/rclone-v1.51.0-linux-amd64/rclone tree -vv spi-drive:audit/2019/README.pdf     
2020/05/19 15:09:48 DEBUG : rclone: Version "v1.51.0" starting with parameters ["/home/tbm/rclone-v1.51.0-linux-amd64/rclone" "tree" "-vv" "spi-drive:audit/2019/README.pdf"]
2020/05/19 15:09:48 DEBUG : Using config file from "/home/tbm/.config/rclone/rclone.conf"
2020/05/19 15:09:48 DEBUG : spi-drive: Loaded invalid token from config file - ignoring
2020/05/19 15:09:49 DEBUG : spi-drive: Token refresh failed try 1/5: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
2020/05/19 15:09:50 DEBUG : spi-drive: Loaded invalid token from config file - ignoring
2020/05/19 15:09:50 DEBUG : spi-drive: Token refresh failed try 2/5: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
2020/05/19 15:09:51 DEBUG : spi-drive: Loaded invalid token from config file - ignoring
2020/05/19 15:09:51 DEBUG : spi-drive: Token refresh failed try 3/5: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
2020/05/19 15:09:52 DEBUG : spi-drive: Loaded invalid token from config file - ignoring
2020/05/19 15:09:53 DEBUG : spi-drive: Token refresh failed try 4/5: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
2020/05/19 15:09:54 DEBUG : spi-drive: Loaded invalid token from config file - ignoring
2020/05/19 15:09:54 DEBUG : spi-drive: Token refresh failed try 5/5: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
2020/05/19 15:09:55 Failed to create file system for "spi-drive:audit/2019/README.pdf": couldn't find root directory ID: Get https://www.googleapis.com/drive/v3/files/root?alt=json&fields=id&prettyPrint=false&supportsAllDrives=true: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}
```

**Comment by ncw** [comment]
If I understand your request you'd like the error message to be more helpful.

> 2020/05/19 15:09:55 Failed to create file system for "spi-drive:audit/2019/README.pdf": couldn't find root directory ID: Get https://www.googleapis.com/drive/v3/files/root?alt=json&fields=id&prettyPrint=false&supportsAllDrives=true: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}

This message is generated in the oauth2 library rclone uses so it isn't straight forward to change.

I agree it is full of jargon someone not versed in oauth2 would have no idea what it means.

It would be easy to rclone to wrap this in an explainer, so it would end up looking like this

> 2020/05/19 15:09:55 Failed to create file system for "spi-drive:audit/2019/README.pdf": couldn't find root directory ID: Get https://www.googleapis.com/drive/v3/files/root?alt=json&fields=id&prettyPrint=false&supportsAllDrives=true: **couldn't fetch token maybe it has expired - refresh with rclone config reconnect**: oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_grant",
  "error_description": "Bad Request"
}

Would that be helpful?

**Comment by tbm** [comment]
> It would be easy to rclone to wrap this in an explainer, so it would end up looking like this

Yes, that would be lovely. Thank you!

**Comment by ncw** [comment]
I've tried to make the error messages more helpful - it should tell the user which command to run.

**Comment by caspertone2003** [comment]
Not a bad critic to an application I love but an enhancement suggestion.
Sorry for piggy-backing the thread.
===================================================
I suffered this situation and come back to github to search for help... While I already found how to renew the token using config , as well explained here https://forum.rclone.org/t/coming-back-to-rclone-after-a-year-now-nothing-works/6573/2

I wonder...
All explained there, could not be automated? I mean, when this error is detected, by offering the user the refresh of the token? Could rclone avoid the user to run config, select the remote, press enter over ten (?) times until the following question pops up:

Already have a token - refresh?
y) Yes
n) No
y/n>

So, I would like to propose the following enhancement: to just open a message to the user with the message:
"GDrive authentication token seems to have expired; would you like to obtain a new one? y/n?"

That would be much way user friendly than putting a more clear error message...

TIA
CT

**Comment by ncw** [comment]
> All explained there, could not be automated? I mean, when this error is detected, by offering the user the refresh of the token?

A fair point...

However we are not 100% certain that is the problem at that point and we can't ask for user interaction unless the user was running `rclone config` so we can't do this automatically.

Note that the error message should now say `run "rclone config reconnect remote:"` so all you need to do is run that command.

**Comment by caspertone2003** [comment]
ah!
I am always discovering new commands... should read more deeply the documentation. Reconnect is new for me... imagine shortens the questions chain...
Thanks of course.
Anyhow, I do not understand why the user is not offered the refresh and a process spawned running the reconnect command, at that moment rclone has all the needed information to launch the going through the interactive oauth flow

CT

**Comment by ncw** [comment]
> Anyhow, I do not understand why the user is not offered the refresh and a process spawned running the reconnect command, at that moment rclone has all the needed information to launch the going through the interactive oauth flow

Because the user might not be present - rclone is often used in scripts running on remote servers.
