### ISSUE TITLE
rclone config: renew token expiry without running through config

### ISSUE THREAD

**Issue by tbm** [rclone/rclone#4251]
#### What is your current rclone version (output from `rclone version`)?

1.51.0

#### What problem are you are trying to solve?

My token expired because I hadn't used rclone in months.  Running `rclone config` allows me to get a new token.

However, I have to run through all the configuration steps again.

#### How do you think rclone should be changed to solve that?

I already configured rclone.  I don't want to run through the config again.  I have no clue how to answer most of the questions.  But I had a working config before... presumably my config from a year ago still works (yes, confirmed, it does).

I *just* want to get a new token.  Can we have an option to renew a token without running through the whole config menu again?

**Comment by ncw** [comment]
This will do what you want

    rclone config reconnect remote:

:-)

**Comment by tbm** [comment]
Ok, that's excellent.

But rclone does:

```
./lib/oauthutil/oauthutil.go:		return nil, errors.New("empty token found - please run rclone config again")
```

Should that say `rclone config reconnect` or might that not work in some cases?

**Comment by ncw** [comment]
> Ok, that's excellent.
> 
> But rclone does:
> 
> ```
> ./lib/oauthutil/oauthutil.go:		return nil, errors.New("empty token found - please run rclone config again")
> ```
> 
> Should that say `rclone config reconnect` or might that not work in some cases?

That is a good idea... I'll change it now :-)

**Comment by ncw** [comment]
Done!
