### ISSUE TITLE
rclone copy/move should show total transfer speed instead of average speed

### ISSUE THREAD

**Issue by agneevX** [rclone/rclone#4256]
#### What is the problem you are having with rclone?
The "total" transfer speed `rclone copy` or `rclone move` is actually an average value that is, simply put, useless.

In case of a fluctuating speed, the average value tends to stay in the same place and adding the values of the in-progress files is cumbersome. 

If I'm transferring tens of files, the value should show the sum total of the transfer speed of all the files. 

#### What is your rclone version (output from `rclone version`)
```
rclone v1.51.0
- os/arch: linux/arm
- go version: go1.13.7
```
#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Raspbian Buster (32-bit). 

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone copy`, `rclone move`

**Comment by agneevX** [comment]
[Discussion](https://forum.rclone.org/t/incorrect-upload-speed-shown-in-rclone-copy/12403)

**Comment by agneevX** [comment]
Any update on this @ncw?

**Comment by ncw** [comment]
This is in progress here: https://github.com/rclone/rclone/pull/4329

**Comment by agneevX** [comment]
Closing in favor of #3909.
