### ISSUE TITLE
Long starting delay (reading data)

### ISSUE THREAD

**Issue by darkdragon-001** [rclone/rclone#4258]
#### What is the problem you are having with rclone?
When transferring a large file from local disk to S3 (MinIO), there is a long delay (about 30s) before the first chunk is transferred. During this time, there is heavy disk read (~ 300MiB/s).

#### What is your rclone version (output from `rclone version`)
```
rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.6
```

#### Which OS you are using and how many bits
Ubuntu 20.04

####  Which cloud storage system are you using?
S3 (MinIO)

#### The command you were trying to run
```
dd if=/dev/urandom of=10GiB.bin bs=5M count=2000 status=progress
rclone copy -vv -P --s3-upload-concurrency 1 --s3-chunk-size 512M 10GiB.bin minio:test/
```

#### A log from the command with the `-vv` flag
```
2020/05/20 14:06:04 DEBUG : rclone: Version "v1.50.2" starting with parameters ["rclone" "copy" "-vv" "-P" "--s3-upload-concurrency" "1" "--s3-chunk-size" "512M" "10GiB.bin" "minio:test/"]
2020/05/20 14:06:04 DEBUG : Using config file from "/home/USER/.config/rclone/rclone.conf"
2020-05-20 14:06:04 DEBUG : 10GiB.bin: Need to transfer - File not found at Destination
2020-05-20 14:10:55 DEBUG : 10GiB.bin: MD5 = 303babac22dee7187053c9e3166ae168 OK
2020-05-20 14:10:55 INFO  : 10GiB.bin: Copied (new)
Transferred:        9.766G / 9.766 GBytes, 100%, 34.359 MBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            1 / 1, 100%
Elapsed time:       4m51s
2020/05/20 14:10:55 DEBUG : 5 go routines active
2020/05/20 14:10:55 DEBUG : rclone: Version "v1.50.2" finishing with parameters ["rclone" "copy" "-vv" "-P" "--s3-upload-concurrency" "1" "--s3-chunk-size" "512M" "10GiB.bin" "minio:test/"]
```

**Comment by animosity22** [comment]
For use questions like, the forums a great place to start.

That being said, you didn't include any log as you deleted that from the issue. Can you please include a debug log.

**Comment by darkdragon-001** [comment]
I added the log although it doesn't contribute any information regarding the starting delay.

**Comment by animosity22** [comment]
The disk IO is the md5sum that's happening so the log actually shows that. 

When you copy a file from local to a provider that supports a MD5 sum, it has to calculate the md5sum on the local side as the remote side will compare.

```

2020-05-20 14:10:55 DEBUG : 10GiB.bin: MD5 = 303babac22dee7187053c9e3166ae168 OK
--

**Comment by darkdragon-001** [comment]
Does this need to happen beforehand or can it be done on-the-fly? Just storing the current MD5 state while adding chunks on the go should remove the need to read the whole file beforehand.

**Comment by animosity22** [comment]
I'm not quite sure I'm following.

When you upload a file to a provider that supports MD5 sums, you need to compare the MD5 from the source file and the provider calculates the MD5 sum on the other side.

If those are good, the files match.

Here is an example as it takes about 2 seconds for me to md5sum this file and if I try to copy using the checksum, it has that 2 second delay.

```
felix@gemini:/data$ rclone copy jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv GD: -vv --checksum
2020/05/20 08:32:57 DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "copy" "jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv" "GD:" "-vv" "--checksum"]
2020/05/20 08:32:57 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2020/05/20 08:33:04 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: MD5 = 9d462dd04bf1f85ed21f8d9a51c709eb OK
2020/05/20 08:33:04 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: Size and MD5 of src and dst objects identical
2020/05/20 08:33:04 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: Unchanged skipping
2020/05/20 08:33:04 INFO  :
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Checks:                 1 / 1, 100%
Elapsed time:         0.0s

2020/05/20 08:33:04 DEBUG : 5 go routines active
2020/05/20 08:33:04 DEBUG : rclone: Version "v1.51.0" finishing with parameters ["rclone" "copy" "jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv" "GD:" "-vv" "--checksum"]
```

and

```
felix@gemini:/data$ time md5sum jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
9d462dd04bf1f85ed21f8d9a51c709eb  jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv

real	0m2.707s
user	0m2.449s
sys	0m0.228s
```

At some point in the start or end, you have to calculate that md5sum on the source file.

**Comment by darkdragon-001** [comment]
But does the md5sum need to be sent to the provider before the first chunk is uploaded or can it be transferred later (since the provider can only compare it after the last chunk has been received anyways)?

You could calculate the md5sum within the pipeline:
1. Read a chunk of data
2.1. Send this chunk of data
2.2. Add this chunk to md5sum calculation

Note that 2.1. and 2.2. are processed simultaneously. After you processed the last chunk of data, you can finish the md5sum calculation. md5sum works with streams (e.g. piping in console works), so you can just add more data to md5sum when it is read anyways.

**Comment by animosity22** [comment]
I think the question has been answered.

If you want to discuss how to change/improve, that's a great place on the forums to discuss feature requests and improvements as many folks see it and offer feedback.

**Comment by darkdragon-001** [comment]
See the following [example](https://stackoverflow.com/a/37580966/3779655) | gzip -c | split -d -b 1M - file.gz) to md5sum and gzip a file while reading it only once:

    cat file | tee >(md5sum | sed 's/-/file/' > file_mybackup.md5) | gzip -c | split -d -b 1M - file.gz

This way the additional read at the beginning is just a waste of time!

**Comment by darkdragon-001** [comment]
Reference added to [Slack](https://app.slack.com/client/T408CCVEE/C40ATDF7W/thread/C40ATDF7W-1589979169.290400). Maybe someone else also thinks that reading a file twice is a wasteful process.

**Comment by darkdragon-001** [comment]
The [minio client (`mc`)](https://github.com/minio/mc) seems to implement this. The effective transfer rate is doubled since disk I/O is the slowest component.

    mc cp --md5 10GiB.bin minio/test/

**Comment by animosity22** [comment]
I'll let @ncw comment on the internals.

**Comment by animosity22** [comment]
Did you want to validate this as well on 1.51 as the behavior may have changed as well?

**Comment by darkdragon-001** [comment]
@animosity22 This behavior is still present on 1.51.

**Comment by ncw** [comment]
> But does the md5sum need to be sent to the provider before the first chunk is uploaded or can it be transferred later (since the provider can only compare it after the last chunk has been received anyways)?

The md5sum can be calculated streaming wise but then rclone needs to do a COPY to update the metadata which is an expensive operation on AWS...

It is optional the md5sum - you can disable it with 

      --s3-disable-checksum           Don't store MD5 checksum with object metadata

Or the `disable_checksum` config key.

That will mean rclone no longer has an md5sum for large files, but that might be acceptable for your use.

**Comment by darkdragon-001** [comment]
How can I disable the overall checksum, but still use checksum for the individual chunks?

I did not notice this behavior by default on AWS CLI and Minio Client. I just can't imagine that they disable checksums by default...

**Comment by ncw** [comment]
> How can I disable the overall checksum, but still use checksum for the individual chunks?

That is exactly what `--s3-disable-checksum` does.

**Comment by darkdragon-001** [comment]
So you think this is what Amazon and Minio do _by default_?

**Comment by ncw** [comment]
> How can one control the checksums for the individual chunks then?

You can't they are always on. This is recommended by the AWS SDK and it takes very little CPU and causes no delay in exchange for a guarantee of data integrity.



> So you think this is what Amazon and Minio do _by default_?

I'm pretty sure they do yes.

Rclone likes to know the MD5SUM of the entire file and for that rclone needs to calculate it in advance - hence the long delay unless you set `--s3-disable-checksum`. This does not turn off the per part checksums.

**Comment by darkdragon-001** [comment]
@ncw Thanks for the clarification. How does this play together with the global (backend independent) options? How do other backends handle the checksum?

**Comment by ncw** [comment]
> Thanks for the clarification. How does this play together with the global (backend independent) options? How do other backends handle the checksum?

It doesn't at the moment. Other backends either don't need the checksum up front (most of them) of have a similar flag, eg `--b2-disable-checksum`



> It would be nice to find a hint on the long starting delay and the proposed solution in the docs somewhere... Maybe near [s3 multipart uploads](https://rclone.org/s3/#multipart-uploads).

Good idea!

Fancy sending a pull request? It is as simple as going here: https://github.com/rclone/rclone/blob/master/docs/content/s3.md#multipart-uploads and clicking the edit icon at the top right!

**Comment by darkdragon-001** [comment]
```
  --s3-disable-checksum           Don't store MD5 checksum with object metadata
```

Is it possible to set this in the config file so that I don't have to enter it every time?

---

_Btw: I will look for the docs in the next days._

**Comment by animosity22** [comment]
Yep:

https://rclone.org/s3/#s3-disable-checksum

**Comment by ncw** [comment]
This is a relatively frequent question for the b2,s3 && azureblob backends. We should probably put a section into the relevant doc.

Those docs are getting quite long though!

I was thinking about adding a performance section on how to optimise for

- minimum memory
- max throughput
- minimum transactions

It could go in there maybe...

**Comment by darkdragon-001** [comment]
What do you mean by _section_? Do you want to create a new _page_ or add it to _which existing page_?

IMO this is a good idea, since most people is looking to improve performance for one's specific needs. This would probably avoid a lot of issues from being created.

**Comment by ncw** [comment]
Add a new section to the existing backend docs, eg https://rclone.org/s3/ or https://rclone.org/b2/

Is what I was thinking

**Comment by darkdragon-001** [comment]
One section for each backend? Which one applies when copying between two backends? Source or destination?

**Comment by ncw** [comment]
> One section for each backend? Which one applies when copying between two backends? Source or destination?

That depends what you are doing! The section would need to talk about copying from and to the backend.

**Comment by darkdragon-001** [comment]
Sounds good :+1: 

But I have no idea how the software behaves in this case (still quite a new user). Thus, I think it doesn't make sense if I write the section. I would highly appreciate if @ncw or @animosity22 or someone else would take care of it. Curious to see what I can learn from the newly introduced section!

**Comment by ncw** [comment]
OK here is a stream of consciousness first draft :-)

## Performance

There are several factors which affect performance of this backend.

This remote supports `--fast-list` which allows you to use fewer transactions in exchange for more memory. If you use `--fast-list` in a sync then rclone will do the fewest number of listing transactions possible, however it will need to store those directory listings in memory which might take as much as 1k or RAM per object.

The s3 backend stores modification times as metadata on the object. This means that syncing with mod times takes an extra HEAD request per object. This can slow syncs down and cost more. You can avoid this by using these in your sync:

- `--size-only` only checks sizes of the objects. Fast but less accurate.
- `--checksum` checks size and md5sum. Accurate but will read your local files to create the ms5sum each time.
- `--update --use-server-modtime` this uses the last modified field on the object to do the syncing and only copies the object if the local last modified time is newer than that on the server. This is very quick but relies on local modification times increasing when files are modified.

The s3 backend stores md5sums on files smaller than `--s3-upload-cutoff`. On files larger than this cutoff rclone adds some metadata to the object with the md5sum at the time of upload. This is calculated before the upload starts, so can cause large delays. If you are happy without having a record of the md5sum of the file when it was uploaded then use `--s3-disable-checksum`. Rclone could potentially add the checksum after uploading to avoid the delay, however this would involve a relatively expensive COPY operation.

Multipart uploads can be made faster by increasing `--s3-chunk-size`. These chunks are buffered in memory. If you are transferring large files over high speed links and you have enough memory, then increasing this will speed up the transfers. Rlcone does `--s3-concurrency` chunks simultaneously normally - this value can be increased for more speed at the cost of more memory.

Note that s3 backends are usually very high performance, so you can increase `--transfers` and `--checkers` to speed up transfers. Using `--transfers 64` should work fine. This will use more memory.

Memory usage for multipart transfers is roughly `--transfers` * `--s3-chunk-size` * `--s3-concurrency`. Decrease `--transfers` and `--s3-concurrency` to reduce memory usage. (The `--s3-chunk-size` is at a recommended minimum). You can also increase `--s3-cutoff` which will stream upload files without using buffers or concurrency.

**Comment by darkdragon-001** [comment]
First of all, a big thanks for your effort!

A few questions for my understanding
- This is supposed to go for the S3 backend?
- I would welcome some clarification if the description applies to S3 as _source_, _destination_ or _both_.
- Does _sync_ mean both `rclone sync` _and_ `rclone copy`?
- We should think about the relation of multipart uploads in the _Performance_ section and in the _[Multipart uploads section](https://rclone.org/s3/#multipart-uploads)_

Find below some small comments in italic:

> ## Performance
> There are several factors which affect performance of ~~this~~[the S3] backend.
> 
> This remote supports `--fast-list` which allows you to use fewer transactions in exchange for more memory. If you use `--fast-list` in a sync then rclone will do the fewest number of listing transactions possible, however it will need to store those directory listings in memory which might take as much as **1k or RAM**_(what? 1KiB of RAM?)_ per object.
> 
> The s3 backend stores modification times as metadata on the object. This means that syncing with mod times takes an extra HEAD request per object. This can slow syncs down and cost more. You can avoid this by using these in your sync:
> 
> * `--size-only` only checks sizes of the objects. Fast but less accurate.
> * `--checksum` checks size and md5sum. Accurate but will read your **local files**_(from local to S3?)_ to create the ms5sum each time.
> * `--update --use-server-modtime` this uses the last modified field on the object to do the syncing and only copies the object if the local last modified time is newer than that on the server. This is very quick but relies on local modification times increasing when files are modified.
> 
> The s3 backend stores md5sums on files smaller than `--s3-upload-cutoff`. On files larger than this cutoff rclone adds some metadata to the object with the md5sum at the time of upload. This is calculated before the upload starts, so can cause large delays. If you are happy without having a record of the md5sum of the file when it was uploaded then use `--s3-disable-checksum`. Rclone could potentially add the checksum after uploading to avoid the delay, however this would involve a relatively expensive COPY operation._(just for my understanding: how is the metadata added to the object? is it a binary sequence at the beginning of the object if this is not a feature supported by S3?)_
> 
> Multipart uploads can be made faster by increasing `--s3-chunk-size`. These chunks are buffered in memory. If you are transferring large files over high speed links and you have enough memory, then increasing this will speed up the transfers. Rlcone does `--s3-concurrency` chunks simultaneously normally - this value can be increased for more speed at the cost of more memory.
> 
> Note that s3 backends are usually very high performance, so you can increase `--transfers` and `--checkers` to speed up transfers. Using `--transfers 64` should work fine. This will use more memory.
> 
> Memory usage for multipart transfers is roughly `--transfers` * `--s3-chunk-size` * `--s3-concurrency`. Decrease `--transfers` and `--s3-concurrency` to reduce memory usage. (The `--s3-chunk-size` is at a recommended minimum). You can also increase `--s3-cutoff` which will stream upload files without using buffers or concurrency _(maybe add some clarification, that files smaller than cutoff are transferred as-is and thus don't need buffers and don't support concurrency)_.

**Comment by ncw** [comment]
> First of all, a big thanks for your effort!

:-) And thanks for taking the time to critique.

> A few questions for my understanding
> 
> * This is supposed to go for the S3 backend?

Yes this is S3 specific advice

> * I would welcome some clarification if the description applies to S3 as _source_, _destination_ or _both_.

Anything which involves listing the remote applies to both source and destination. Most of the other advice is about uploads though there could be a section on downloads and multi-thread transfers

> * Does _sync_ mean both `rclone sync` _and_ `rclone copy`?

It means `sync`/`copy` and `move` which are all essentially the same command just with a few variations.

> * We should think about the relation of multipart uploads in the _Performance_ section and in the _[Multipart uploads section](https://rclone.org/s3/#multipart-uploads)_

Yes good point.

> Find below some small comments in italic:
> 
> > ## Performance
> > There are several factors which affect performance of ~this~[the S3] backend.
> > This remote supports `--fast-list` which allows you to use fewer transactions in exchange for more memory. If you use `--fast-list` in a sync then rclone will do the fewest number of listing transactions possible, however it will need to store those directory listings in memory which might take as much as **1k or RAM**_(what? 1KiB of RAM?)_ per object.

Yes 1KiB of RAM per object.

This following bit applies to s3 as source or destination.

> > The s3 backend stores modification times as metadata on the object. This means that syncing with mod times takes an extra HEAD request per object. This can slow syncs down and cost more. You can avoid this by using these in your sync:
> > 
> > * `--size-only` only checks sizes of the objects. Fast but less accurate.
> > * `--checksum` checks size and md5sum. Accurate but will read your **local files**_(from local to S3?)_ to create the ms5sum each time.

More accurately this should say "if syncing from local disk to s3 then it will read your local files to create the md5sum each time".

In general it reads the source MD5... On S3 this is a super fast operation as they come with the directory listings.

> > * `--update --use-server-modtime` this uses the last modified field on the object to do the syncing and only copies the object if the local last modified time is newer than that on the server. This is very quick but relies on local modification times increasing when files are modified.
> > 
> > The s3 backend stores md5sums on files smaller than `--s3-upload-cutoff`. On files larger than this cutoff rclone adds some metadata to the object with the md5sum at the time of upload. This is calculated before the upload starts, so can cause large delays. If you are happy without having a record of the md5sum of the file when it was uploaded then use `--s3-disable-checksum`. Rclone could potentially add the checksum after uploading to avoid the delay, however this would involve a relatively expensive COPY operation._(just for my understanding: how is the metadata added to the object? is it a binary sequence at the beginning of the object if this is not a feature supported by S3?)_

S3 lets you store a small amount of metadata (as key, value pairs) along with each object. Rclone uses it to store the modification time and the checksum.

> > Multipart uploads can be made faster by increasing `--s3-chunk-size`. These chunks are buffered in memory. If you are transferring large files over high speed links and you have enough memory, then increasing this will speed up the transfers. Rlcone does `--s3-concurrency` chunks simultaneously normally - this value can be increased for more speed at the cost of more memory.
> > Note that s3 backends are usually very high performance, so you can increase `--transfers` and `--checkers` to speed up transfers. Using `--transfers 64` should work fine. This will use more memory.
> > Memory usage for multipart transfers is roughly `--transfers` * `--s3-chunk-size` * `--s3-concurrency`. Decrease `--transfers` and `--s3-concurrency` to reduce memory usage. (The `--s3-chunk-size` is at a recommended minimum). You can also increase `--s3-cutoff` which will stream upload files without using buffers or concurrency _(maybe add some clarification, that files smaller than cutoff are transferred as-is and thus don't need buffers and don't support concurrency)_.

Good idea!

I forgot to add `--no-traverse` which cuts down on the directory listings if you are `copy`-ing a small number of files into a large directory. This needs a whole new section but it isn't s3 specific advise so probably needs to go in a general performance doc.

There could be  section on top-up syncs with `rclone copy --max-age --no-traverse`

And there is also the easy to mis-use `--no-check-dest` flag...

In fact maybe this whole doc should be a general performance doc with some callouts for specific backends? Or I could write the doc as a template and only include the bits which are needed in each backend (think if statements on the backend name)? That might work as there are duplicated sections on `--fast-list` for example in all the bucket based remotes.

**Comment by darkdragon-001** [comment]
> In fact maybe this whole doc should be a general performance doc with some callouts for specific backends? Or I could write the doc as a template and only include the bits which are needed in each backend (think if statements on the backend name)? That might work as there are duplicated sections on `--fast-list` for example in all the bucket based remotes.

I suggest a general _Performance_ document. Some thinks which apply to multiple backends should go in there as well (e.g. _cutoff flag_ (e.g. `--s3-cutoff`, `-b2-cutoff` or similar)).
Really backend specific documentation could go to the specific backend document (with the same headline / anchor link as well as a back-link to the general performance document).

**Comment by ncw** [comment]
> I suggest a general _Performance_ document. Some thinks which apply to multiple backends should go in there as well (e.g. _cutoff flag_ (e.g. `--s3-cutoff`, `-b2-cutoff` or similar)).

OK So a top level performance doc with lots of hints and tips and backend specific ones in each backend doc.

> Really backend specific documentation could go to the specific backend document (with the same headline / anchor link as well as a back-link to the general performance document).

Yes sounds like a plan!

**Comment by animosity22** [comment]
Anything left to do for this item?

**Comment by ncw** [comment]
I'll close this now - I've made a not of the desire for a performance document.
