### ISSUE TITLE
Heavy RAM usage

### ISSUE THREAD

**Issue by darkdragon-001** [rclone/rclone#4259]
#### What is the problem you are having with rclone?
When transferring a _single_ large file from local disk to S3 (MinIO), there is a heavy RAM usage (4.2G) when it should only be [`--s3-upload-concurrency` * `--s3-chunk-size`](https://rclone.org/s3/#multipart-uploads) = 1 * 512M = 1G. This also shouldn't be a metadata problem since the file is only split into 10G / 512M = 20 chunks.

My system monitor Gnome extension, shows CPU (75s) | RAM (175s) | Network (50s): 
![system-monitor](https://user-images.githubusercontent.com/177976/82445575-5a179e00-9aa5-11ea-98b2-764b53613c78.png)
One can clearly see CPU spikes and Network spikes taking turns. Most importantly, the RAM increases steadily instead of freeing RAM for successfully transferred parts. After the program exits, the RAM is freed again.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.6
```

#### Which OS you are using and how many bits
Ubuntu 20.04

####  Which cloud storage system are you using?
S3 (MinIO)

#### The command you were trying to run
```
dd if=/dev/urandom of=10GiB.bin bs=5M count=2000 status=progress
rclone copy -vv -P --s3-upload-concurrency 1 --s3-chunk-size 512M 10GiB.bin minio:test/
```

#### A log from the command with the `-vv` flag
```
2020/05/20 14:06:04 DEBUG : rclone: Version "v1.50.2" starting with parameters ["rclone" "copy" "-vv" "-P" "--s3-upload-concurrency" "1" "--s3-chunk-size" "512M" "10GiB.bin" "minio:test/"]
2020/05/20 14:06:04 DEBUG : Using config file from "/home/USER/.config/rclone/rclone.conf"
2020-05-20 14:06:04 DEBUG : 10GiB.bin: Need to transfer - File not found at Destination
2020-05-20 14:10:55 DEBUG : 10GiB.bin: MD5 = 303babac22dee7187053c9e3166ae168 OK
2020-05-20 14:10:55 INFO  : 10GiB.bin: Copied (new)
Transferred:        9.766G / 9.766 GBytes, 100%, 34.359 MBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            1 / 1, 100%
Elapsed time:       4m51s
2020/05/20 14:10:55 DEBUG : 5 go routines active
2020/05/20 14:10:55 DEBUG : rclone: Version "v1.50.2" finishing with parameters ["rclone" "copy" "-vv" "-P" "--s3-upload-concurrency" "1" "--s3-chunk-size" "512M" "10GiB.bin" "minio:test/"]
```

**Comment by animosity22** [comment]
Please post use questions on the forums.

**Comment by darkdragon-001** [comment]
This are not use questions, but discrepancies between the way rclone is supposed to work according to documentation and the way it is actually working!

Read my first sentence:

Your [documentation](https://rclone.org/s3/#multipart-uploads) says
> Multipart uploads will use `--transfers` * `--s3-upload-concurrency` * `--s3-chunk-size` extra memory.

The following values are used:
- `--transfers` is `1` for a single file
- `--s3-upload-concurrency` is set to `1` explicitely
- `--s3-chunk-size` is set to `512M` explicitely
Therefore, rclone is supposed to use `1G` extra memory.

Instead it uses `4.2G` memory!

**Comment by animosity22** [comment]
Appreciate the feedback and it's a great question for the forums on use and we can figure out if you have a bug or a general use question.

Thanks!

**Comment by darkdragon-001** [comment]
If you prefer to collect bugs on Slack such that they can disappear in nirvana soon, [here](https://app.slack.com/client/T408CCVEE/C40ATDF7W/thread/C40ATDF7W-1589978927.288700) it is!

**Comment by Makeshift** [comment]
There are a few flags that can influence ram usage, but 4gb does seem a little high.
Could you try the below flags additionally to the ones set already?

```
--buffer-size=0 --use-mmap
```
I'm curious if `--use-mmap` would cause the memory to be released back to the OS faster, and buffersize should reduce memory usage further.

This does seem like a bug as opposed to a question though - I'm surprised I'm not seeing a reduce in memory usage every minute in line with `memoryPoolFlushTime`.

**Comment by darkdragon-001** [comment]
Unfortunately, this does still use 4.2G RAM:

```
2020/05/20 15:14:28 DEBUG : rclone: Version "v1.50.2" starting with parameters ["rclone" "copy" "-vv" "-P" "--s3-upload-concurrency" "1" "--s3-chunk-size" "512M" "--buffer-size=0" "--use-mmap" "10GiB.bin" "minio:test/"]
2020/05/20 15:14:28 DEBUG : Using config file from "/home/USER/.config/rclone/rclone.conf"
2020-05-20 15:14:28 DEBUG : 10GiB.bin: Need to transfer - File not found at Destination
2020-05-20 15:19:06 DEBUG : 10GiB.bin: MD5 = 303babac22dee7187053c9e3166ae168 OK
2020-05-20 15:19:06 INFO  : 10GiB.bin: Copied (new)
Transferred:        9.766G / 9.766 GBytes, 100%, 35.969 MBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            1 / 1, 100%
Elapsed time:       4m38s
2020/05/20 15:19:06 INFO  : 
Transferred:        9.766G / 9.766 GBytes, 100%, 35.969 MBytes/s, ETA 0s
Errors:                 0
Checks:                 0 / 0, -
Transferred:            1 / 1, 100%
Elapsed time:       4m38s

2020/05/20 15:19:06 DEBUG : 5 go routines active
2020/05/20 15:19:06 DEBUG : rclone: Version "v1.50.2" finishing with parameters ["rclone" "copy" "-vv" "-P" "--s3-upload-concurrency" "1" "--s3-chunk-size" "512M" "--buffer-size=0" "--use-mmap" "10GiB.bin" "minio:test/"]
```

**Comment by animosity22** [comment]
Sure, I'll open it back up.

**Comment by animosity22** [comment]
You can do a memory profile this route:

https://rclone.org/rc/#debugging-memory-use

and share that please.

**Comment by darkdragon-001** [comment]
Memory profiler:
```
Fetching profile over HTTP from http://localhost:5572/debug/pprof/heap
Saved profile in /home/USER/pprof/pprof.rclone.alloc_objects.alloc_space.inuse_objects.inuse_space.010.pb.gz
File: rclone
Build ID: 60c26a2430905fb383b0fbe2a241482a8d9f1063
Type: inuse_space
Time: May 20, 2020 at 4:05pm (CEST)
Showing nodes accounting for 2.50GB, 99.52% of 2.51GB total
Dropped 23 nodes (cum <= 0.01GB)
      flat  flat%   sum%        cum   cum%
    2.50GB 99.52% 99.52%     2.50GB 99.52%  github.com/aws/aws-sdk-go/service/s3/s3manager.(*uploader).init.func1
         0     0% 99.52%        2GB 79.61%  github.com/aws/aws-sdk-go/service/s3/s3manager.(*multiuploader).upload
         0     0% 99.52%     2.50GB 99.52%  github.com/aws/aws-sdk-go/service/s3/s3manager.(*uploader).nextReader
         0     0% 99.52%     2.50GB 99.52%  github.com/aws/aws-sdk-go/service/s3/s3manager.(*uploader).upload
         0     0% 99.52%     2.50GB 99.52%  github.com/aws/aws-sdk-go/service/s3/s3manager.Uploader.UploadWithContext
         0     0% 99.52%     2.50GB 99.52%  github.com/rclone/rclone/backend/s3.(*Fs).Put
         0     0% 99.52%     2.50GB 99.52%  github.com/rclone/rclone/backend/s3.(*Object).Update
         0     0% 99.52%     2.50GB 99.52%  github.com/rclone/rclone/backend/s3.(*Object).Update.func2
         0     0% 99.52%     2.50GB 99.52%  github.com/rclone/rclone/cmd.Main
         0     0% 99.52%     2.50GB 99.52%  github.com/rclone/rclone/cmd.Run
         0     0% 99.52%     2.50GB 99.52%  github.com/rclone/rclone/cmd/copy.glob..func1
         0     0% 99.52%     2.50GB 99.52%  github.com/rclone/rclone/cmd/copy.glob..func1.1
         0     0% 99.52%     2.50GB 99.52%  github.com/rclone/rclone/fs.pacerInvoker
         0     0% 99.52%     2.50GB 99.52%  github.com/rclone/rclone/fs/operations.Copy
         0     0% 99.52%     2.50GB 99.52%  github.com/rclone/rclone/fs/operations.CopyFile
         0     0% 99.52%     2.50GB 99.52%  github.com/rclone/rclone/fs/operations.moveOrCopyFile
         0     0% 99.52%     2.50GB 99.52%  github.com/rclone/rclone/lib/pacer.(*Pacer).CallNoRetry
         0     0% 99.52%     2.50GB 99.52%  github.com/rclone/rclone/lib/pacer.(*Pacer).call
         0     0% 99.52%     2.50GB 99.52%  github.com/spf13/cobra.(*Command).Execute
         0     0% 99.52%     2.50GB 99.52%  github.com/spf13/cobra.(*Command).ExecuteC
         0     0% 99.52%     2.50GB 99.52%  github.com/spf13/cobra.(*Command).execute
         0     0% 99.52%     2.50GB 99.52%  main.main
         0     0% 99.52%     2.50GB 99.58%  runtime.main
         0     0% 99.52%     2.50GB 99.52%  sync.(*Pool).Get
```

Output of `top`:
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  37461 myuser    20   0 4890904   3,7g  26916 S   6,6  48,2   2:46.93 rclone
```

**Comment by darkdragon-001** [comment]
Can someone reproduce my problem?

My setup is actually quite simple:

    docker run -p 9000:9000 -v /mnt/data:/data minio/minio server /data

where `/mnt/data` refers to a regular SATA HDD. The connection is done with a regular Gigabit Ethernet cable.

**Comment by animosity22** [comment]
The memory usage looks to be in the AWS SDK rather than rclone so might be something in there and how that is handling memory.

There were some changes in that in 1.51. Can you try on that and on the latest beta as also some changes since that as well. Would like to see if you get a consistent theme.

I'd love to reproduce it but have minio is not free.

**Comment by darkdragon-001** [comment]
I will try the AWS CLI later.

> I'd love to reproduce it but have minio is not free.
They offer the open-source version without support for _[free](https://min.io/pricing)_. So for testing clients like rclone, this is the perfect tool. When storing actual data and building a service upon, the version with support should be purchased!

**Comment by animosity22** [comment]
Sorry as I was referring to a free version I can just connect to. I did see they offer a way to setup a free version that can be installed.

**Comment by darkdragon-001** [comment]
@animosity22 Install docker and just paste the command I showed you above and you have your own object storage ready to test.

**Comment by animosity22** [comment]
Yeah, I'm good with the steps but it does take some time to spin up a test machine and put on docker and set it up. I only have my one instance at home and that is what I consider 'production' :)

I was hoping at some point since @ncw worked through a few issues very similar with S3 and the memory has an idea or knows pretty well as there have been a few issues with the S3 SDK and memory already so he's spent quite some time there.

**Comment by darkdragon-001** [comment]
The problem does not occur using the AWS CLI:

Config
```
[default]
s3 =
    multipart_threshold = 5MB
    multipart_chunksize = 512MB
    max_concurrent_requests = 1
    addressing_style = path
```

Command

    aws s3 cp 10GiB.bin s3://test --endpoint-url http://<server ip>:9000

It only uses 370MB RAM:
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
  61538 user      20   0  366944  42864   1668 S  39,9   0,5   2:06.59 aws
```

**Comment by darkdragon-001** [comment]
This issue of excessive RAM usage has been fixed in the latest version `v1.51.0` (see below for details).

Nevertheless, other clients (e.g. AWS CLI) use much less memory. I guess they are streaming data correctly instead of loading the whole chunk into memory. I think other approaches to reduce RAM usage should be explored.

---

*Details*

I was trying out the different versions within docker:

    docker run --rm -it -v ~/.config/rclone:/config/rclone -v "$PWD":/data rclone/rclone copy -P --s3-upload-concurrency 1 --s3-chunk-size 512M /data/10GiB.bin minio:test/

When using `rclone/rclone:latest` (v1.51.0), only about 600MB were used as expected. In contrast using `rclone/rclone:1.50.2` resulted in the same 4GB RAM usage.

**Comment by animosity22** [comment]
Yeah, there was a fix in 1.51:

```
S3
Re-implement multipart upload to fix memory issues (Nick Craig-Wood)
```

Which I had mentioned a bit above so I think this is fixed and still would have been a great forum question :)

**Comment by ncw** [comment]
> Nevertheless, other clients (e.g. AWS CLI) use much less memory. I guess they are streaming data correctly instead of loading the whole chunk into memory. I think other approaches to reduce RAM usage should be explored.

Rclone loads each chunk into RAM so that it can be retried on failure. Since rclone streams from one backend to another so may be from cloud to cloud, rclone would have to re-wind the incoming stream on failure. This is possible, but we haven't done it yet!

**Comment by darkdragon-001** [comment]
@ncw Thanks for your clarification. It would be nice to add a flag `cache-chunks` which might default to `true` for backwards compatibility. When false, it should stream data (and re-read on transmission failure).
