### ISSUE TITLE
Disallow remotes beginning with dash in a backwards compatible way

### ISSUE THREAD

**Issue by jtagcat** [rclone/rclone#4261]
#### What is the problem you are having with rclone?
Can't use remotes beginning with the character `-`.
 
#### What is your rclone version (output from `rclone version`)
```
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Fedora 32

####  Which cloud storage system are you using? (eg Google Drive)
Any

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone lsf -my-remote-:` or `rclone lsf "-my-remote-:"`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
Error: unknown shorthand flag: 'm' in -my-remote-:
Usage:
  rclone lsf remote:path [flags]

Flags:
      --absolute           Put a leading / in front of path names.
      --csv                Output in CSV format.
  -d, --dir-slash          Append a slash to directory names. (default true)
      --dirs-only          Only list directories.
      --files-only         Only list files.
  -F, --format string      Output format - see  help for details (default "p")
      --hash h             Use this hash when h is used in the format MD5|SHA-1|DropboxHash (default "MD5")
  -h, --help               help for lsf
  -R, --recursive          Recurse into the listing.
  -s, --separator string   Separator for the items in the format. (default ";")

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.

2020/05/20 22:46:47 Fatal error: unknown shorthand flag: 'm' in -my-remote-:
```

**Comment by animosity22** [comment]
Why do you want to start a remote name with a "-" out of curiousity?

**Comment by animosity22** [comment]
Also sorry as the work around is using -- at the end to denote you are done passing options:

```
felix@gemini:/opt/rclone$ rclone lsd -- -gcrypt:
          -1 2018-06-17 10:24:02        -1 Movies
          -1 2017-04-18 16:14:26        -1 TV
felix@gemini:/opt/rclone$
```

as an example.

**Comment by jtagcat** [comment]
> Why do you want to start a remote name with a "-" out of curiosity?

For sorting a long config:
Remotes surrounded by underscores mean that something depends on them being there, remotes surrounded by dashes are permanent remotes with semi-frequent direct human usage, remotes with other characters are temporary remotes, signifying that they are safe to purge, when the time comes. In these categories, there's also 'remote folders', categorizing remotes (often based on the type, nextclouds, gdrives, sftp, so on). Instead of / as a seperator, - is used. You can probably tell I'm a (read: me and my machines are) heavy user(s).

Thanks for reminding me about `--`. Though as `--` is not mentioned in docs (iirc), it can be assumed, that any item, what includes a `:` signifies an argument as a remote (with path). Making this undocumented behaviour.

**Comment by animosity22** [comment]
The "--" is really a standard bash/unix thing with any command and not rclone specific.

Is there a particular place you'd want to see this mentioned or a page? We can always add something. We are always looking to improve documentation or making something clearer.

I had my sysadmin hat on and was thinking more files and directory names as I wouldn't ever recommend having a dash to start something but for a remote, I can see your use case but for scripting things and such, I personally would avoid a dash.

**Comment by jtagcat** [comment]
> The "--" is really a standard bash/unix thing with any command and not rclone specific.
> I had my sysadmin hat on and was thinking more files and directory names as I wouldn't ever recommend having a dash to start something but for a remote, I can see your use case but for scripting things and such, I personally would avoid a dash.
Yea yea I know.

> Is there a particular place you'd want to see this mentioned or a page? We can always add something. We are always looking to improve documentation or making something clearer.
No, not really. Only place I can think of is the 'quickstart', but this is too technical for quickstart.

**Comment by animosity22** [comment]
Is there anything else than for this item or you can close it out?

**Comment by ncw** [comment]
We could change the definition of remotes make them start with an alphanumeric character... What do you think?

**Comment by jtagcat** [comment]
> We could change the definition of remotes make them start with an alphanumeric character... What do you think?

If so, probably better 'starts and ends with alphanumerics'. +1 on the idea, even though I'd have to rename most of my remotes.

How would you handle compatibility with older configs? Keep remotes with dashes/underlines compatible? Disallow adding new ones via rclone config? I would oppose failing on an existing config.

**Comment by ncw** [comment]
> How would you handle compatibility with older configs? Keep remotes with dashes/underlines compatible? Disallow adding new ones via rclone config? I would oppose failing on an existing config.

This is the regexp for a config name

https://github.com/rclone/rclone/blob/9db8ecbc3220ffa8bc956113e513f482989d0597/fs/fspath/path.go#L15

If we change it it will break ones which don't fit with that as you won't be able to use the on the command line any more

**Comment by jtagcat** [comment]
> > How would you handle compatibility with older configs? Keep remotes with dashes/underlines compatible? Disallow adding new ones via rclone config? I would oppose failing on an existing config.
> 
> This is the regexp for a config name
> 
> https://github.com/rclone/rclone/blob/9db8ecbc3220ffa8bc956113e513f482989d0597/fs/fspath/path.go#L15
> 
> If we change it it will break ones which don't fit with that as you won't be able to use the on the command line any more

Would it be (easily) possible to have only `rclone config` use a separate regex, what prohibits dashes and underscores? Such as adding `configNameRe2` as 'version 2', 'dropping' support for the aforementioned remotes, but only using `configNameRe2` for `rc config`, while adding or renaming a remote.

**Comment by ncw** [comment]
> Would it be (easily) possible to have only `rclone config` use a separate regex, what prohibits dashes and underscores? Such as adding `configNameRe2` as 'version 2', 'dropping' support for the aforementioned remotes, but only using `configNameRe2` for `rc config`, while adding or renaming a remote.

I see what you mean - have a futher validation when we create the name with `rclone config`. That sounds like it could be work-able and relatively easy to implement.

All that would be required is to add an additional check here

https://github.com/rclone/rclone/blob/80391fbcd47924ede512bf6bc4f3835dadc153d8/fs/config/config.go#L1086-L1091

Do you fancy having a go at this @jtagcat ?

I'd suggest the validation function was in `fspath` along with the other validation functions.

**Comment by jtagcat** [comment]
Would definitely want to have a go at it, but not now. (am not good at go(ing), don't have time, other problems indicating procrastination, and this is my current tab count)
![image](https://user-images.githubusercontent.com/38327267/83355968-5829c680-a352-11ea-9cf1-a81c8193b931.png)
Ping me if I take too long.

**Comment by ncw** [comment]
> Would definitely want to have a go at it

Great!

It should be reasonably straight forward - let me know if you need help.

Thanks!

Also no time pressure :-)

**Comment by jtagcat** [comment]
It's perplexing that remotes are called configs. The first thing I'd jump to is referring to `rclone.conf`. I had to check, if I was reading the wrong part of code, `errInvalidCharacters = errors.New("config name contains invalid characters - may only contain 0-9, A-Z ,a-z ,_ , - and space ")`. Indeed,
```
name> !)"=)¤
Can't use "!)\"=)¤" as config name contains invalid characters - may only contain 0-9, A-Z ,a-z ,_ , - and space .
```
entering a name for a remote returns an error about configs. I would recommend to change references of remotes as config to actually remotes. There is a conflict: `CheckRemoteName`.

**Comment by jtagcat** [comment]
contributors.md: `go get -u github.com/rclone/rclone`
`cmd/serve/ftp/ftp.go:154:3: unknown field 'PublicIp' in struct literal of type server.ServerOpts (but does have PublicIP)`
It shows up while testing:
```
$ go test -v
# github.com/rclone/rclone/cmd/serve/ftp
cmd/serve/ftp/ftp.go:154:3: unknown field 'PublicIp' in struct literal of type server.ServerOpts (but does have PublicIP)
```
Though the # makes me think it's commented out, but go tries to get it an

**Comment by jtagcat** [comment]
How exactly would I build/run rclone (how do I execute rclone config using my code)?

**Comment by jtagcat** [comment]
all atempts to `go run`, `go build` `go run rclone.go` `go run rclone` get me
```
# github.com/rclone/rclone/cmd/serve/ftp
cmd/serve/ftp/ftp.go:154:3: unknown field 'PublicIp' in struct literal of type server.ServerOpts (but does have PublicIP)
```

**Comment by jtagcat** [comment]
todo contributing.md:
 - how to ff your master with upstream
 - link how to squash

**Comment by jtagcat** [comment]
get something from ff: https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

**Comment by ncw** [comment]
> turns out I shouldn't try to have repos where I want them, not using ~/git/cli/rclone and instead $GOPATH/src/github.com/rclone/rclone

Which go version are you using? I can build rclone not in GOPATH just fine.

**Comment by jtagcat** [comment]
> > turns out I shouldn't try to have repos where I want them, not using ~/git/cli/rclone and instead $GOPATH/src/github.com/rclone/rclone
> 
> Which go version are you using? I can build rclone not in GOPATH just fine.

go version go1.14.3 linux/amd64 installed via dnf (fc32)

**Comment by ncw** [comment]
This is what I get

```
$ unset GOPATH
$ cd /tmp/
$ git clone https://github.com/rclone/rclone.git
Cloning into 'rclone'...
[snip]
$ cd rclone
$ go build
$ ./rclone version
rclone v1.52.1-DEV
- os/arch: linux/amd64
- go version: go1.14.3
$ go version
go version go1.14.3 linux/amd64
$ 
```

What do you get?

**Comment by jtagcat** [comment]
The same result, in the tmp folder, in the folder I tried putting it in, even when deleting everything go has ever stored.

It's a bit nuts that I can't reproduce, even while nuking everything to the same state. I'll not go as far as restoring from backups for now.

Closing as Can't reproduce/Wontfix.

**Comment by jtagcat** [comment]
> Do you fancy having a go at this [@jtagcat](https://github.com/jtagcat) ?

@ncw Thanks for the push, and effort to include, a while ago for diving in to Go. 

:necro:
