### ISSUE TITLE
Confirmation for rclone purge

### ISSUE THREAD

**Issue by RickyBubbles** [rclone/rclone#4262]
#### What is your current rclone version (output from `rclone version`)?
1.51

#### What problem are you are trying to solve?
rclone purge is highly destructive and potentially vulnerable to fat-finger mistakes

#### How do you think rclone should be changed to solve that?

rclone should, by default, give a Y/n prompt with rclone purge
or implement two different commands to delete empty and non-empty directories respectively

it's only a matter of time until I run `rclone purge remote:`
instead of `rclone purge remote:directory`

**Comment by calisro** [comment]
Duplicate of https://github.com/rclone/rclone/issues/1574

Please provide input there.

**Comment by calisro** [comment]
Closing this duplicate
