### ISSUE TITLE
Copying individual files into Azure Blob with SAS fails

### ISSUE THREAD

**Issue by kunal0137** [rclone/rclone#4263]
#### What is the problem you are having with rclone?
Copying an individual local file to azure blob using a container sas fails. This problem is similar to the one described here https://forum.rclone.org/t/copying-individual-files-to-azure-blob-storage/8397

A fix was put in for version 1.46 which indeed does work, but no longer works with the latest prod at 1.51

#### What is your rclone version (output from `rclone version`)
rclone v1.51.0
- os/arch: darwin/amd64
- go version: go1.13.7

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
MacOS, 64bit 
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G103

####  Which cloud storage system are you using? (eg Google Drive)
Azure Blob with SAS

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy /tmp/test/testFile.txt tempsas:containerfoo

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2020/05/20 18:33:17 DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "copy" "/tmp/test/testFile" "tempsas:<containerfoo>" "-vv"]
2020/05/20 18:33:17 DEBUG : Using config file from "/Users/username/.config/rclone/rclone.conf"
2020/05/20 18:33:17 DEBUG : testFile: Modification times differ by -12m56.91417506s: 2020-05-20 18:29:24.126875467 -0400 EDT, 2020-05-20 18:16:27.212700407 -0400 EDT
2020/05/20 18:33:17 DEBUG : testFile: MD5 = 9a340570098063375d0a7ad5e1fa9fa9 (Local file system at /tmp/test)
2020/05/20 18:33:17 DEBUG : testFile: MD5 = 4a2db7b4b0236d4b4149cb266d717165 (Azure container <containerfoo>)
2020/05/20 18:33:17 DEBUG : testFile: MD5 differ
2020/05/20 18:33:17 ERROR : testFile: Failed to copy: -> github.com/rclone/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /Users/runner/runners/2.164.0/work/rclone/src/github.com/rclone/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationFailure) =====
Description=This request is not authorized to perform this operation.
RequestId:7cba6354-d01e-003c-2ff6-2e1cfc000000
Time:2020-05-20T22:33:17.9702205Z, Details:
   Code: AuthorizationFailure
   PUT https://<mystorageaccount>.blob.core.windows.net/<containerfoo>?restype=container&se=2020-05-21t20%3A43%3A16z&sig=REDACTED&sp=racwdl&sr=c&st=2020-05-20t20%3A43%3A16z&sv=2019-10-10&timeout=31536001
   User-Agent: [rclone/v1.51.0]
   X-Ms-Client-Request-Id: [b36af45b-640c-4347-4326-6a7738a653f3]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Wed, 20 May 2020 22:33:17 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [7cba6354-d01e-003c-2ff6-2e1cfc000000]
   X-Ms-Version: [2018-11-09]

2020/05/20 18:33:17 ERROR : Attempt 1/3 failed with 1 errors and: -> github.com/rclone/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /Users/runner/runners/2.164.0/work/rclone/src/github.com/rclone/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationFailure) =====
Description=This request is not authorized to perform this operation.
RequestId:7cba6354-d01e-003c-2ff6-2e1cfc000000
Time:2020-05-20T22:33:17.9702205Z, Details:
   Code: AuthorizationFailure
   PUT https://<mystorageaccount>.blob.core.windows.net/<containerfoo>?restype=container&se=2020-05-21t20%3A43%3A16z&sig=REDACTED&sp=racwdl&sr=c&st=2020-05-20t20%3A43%3A16z&sv=2019-10-10&timeout=31536001
   User-Agent: [rclone/v1.51.0]
   X-Ms-Client-Request-Id: [b36af45b-640c-4347-4326-6a7738a653f3]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Wed, 20 May 2020 22:33:17 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [7cba6354-d01e-003c-2ff6-2e1cfc000000]
   X-Ms-Version: [2018-11-09]

2020/05/20 18:33:18 DEBUG : testFile: Modification times differ by -12m56.91417506s: 2020-05-20 18:29:24.126875467 -0400 EDT, 2020-05-20 18:16:27.212700407 -0400 EDT
2020/05/20 18:33:18 DEBUG : testFile: MD5 = 9a340570098063375d0a7ad5e1fa9fa9 (Local file system at /tmp/test)
2020/05/20 18:33:18 DEBUG : testFile: MD5 = 4a2db7b4b0236d4b4149cb266d717165 (Azure container <containerfoo>)
2020/05/20 18:33:18 DEBUG : testFile: MD5 differ
2020/05/20 18:33:18 ERROR : testFile: Failed to copy: -> github.com/rclone/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /Users/runner/runners/2.164.0/work/rclone/src/github.com/rclone/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationFailure) =====
Description=This request is not authorized to perform this operation.
RequestId:7cba6386-d01e-003c-52f6-2e1cfc000000
Time:2020-05-20T22:33:18.0082471Z, Details:
   Code: AuthorizationFailure
   PUT https://<mystorageaccount>.blob.core.windows.net/<containerfoo>?restype=container&se=2020-05-21t20%3A43%3A16z&sig=REDACTED&sp=racwdl&sr=c&st=2020-05-20t20%3A43%3A16z&sv=2019-10-10&timeout=31536001
   User-Agent: [rclone/v1.51.0]
   X-Ms-Client-Request-Id: [19e670ed-b1d6-4ecf-65d9-778b7ab68855]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Wed, 20 May 2020 22:33:17 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [7cba6386-d01e-003c-52f6-2e1cfc000000]
   X-Ms-Version: [2018-11-09]

2020/05/20 18:33:18 ERROR : Attempt 2/3 failed with 1 errors and: -> github.com/rclone/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /Users/runner/runners/2.164.0/work/rclone/src/github.com/rclone/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationFailure) =====
Description=This request is not authorized to perform this operation.
RequestId:7cba6386-d01e-003c-52f6-2e1cfc000000
Time:2020-05-20T22:33:18.0082471Z, Details:
   Code: AuthorizationFailure
   PUT https://<mystorageaccount>.blob.core.windows.net/<containerfoo>?restype=container&se=2020-05-21t20%3A43%3A16z&sig=REDACTED&sp=racwdl&sr=c&st=2020-05-20t20%3A43%3A16z&sv=2019-10-10&timeout=31536001
   User-Agent: [rclone/v1.51.0]
   X-Ms-Client-Request-Id: [19e670ed-b1d6-4ecf-65d9-778b7ab68855]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Wed, 20 May 2020 22:33:17 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [7cba6386-d01e-003c-52f6-2e1cfc000000]
   X-Ms-Version: [2018-11-09]

2020/05/20 18:33:18 DEBUG : testFile: Modification times differ by -12m56.91417506s: 2020-05-20 18:29:24.126875467 -0400 EDT, 2020-05-20 18:16:27.212700407 -0400 EDT
2020/05/20 18:33:18 DEBUG : testFile: MD5 = 9a340570098063375d0a7ad5e1fa9fa9 (Local file system at /tmp/test)
2020/05/20 18:33:18 DEBUG : testFile: MD5 = 4a2db7b4b0236d4b4149cb266d717165 (Azure container <containerfoo>)
2020/05/20 18:33:18 DEBUG : testFile: MD5 differ
2020/05/20 18:33:18 ERROR : testFile: Failed to copy: -> github.com/rclone/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /Users/runner/runners/2.164.0/work/rclone/src/github.com/rclone/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationFailure) =====
Description=This request is not authorized to perform this operation.
RequestId:7cba63b5-d01e-003c-76f6-2e1cfc000000
Time:2020-05-20T22:33:18.0432725Z, Details:
   Code: AuthorizationFailure
   PUT https://<mystorageaccount>.blob.core.windows.net/<containerfoo>?restype=container&se=2020-05-21t20%3A43%3A16z&sig=REDACTED&sp=racwdl&sr=c&st=2020-05-20t20%3A43%3A16z&sv=2019-10-10&timeout=31536001
   User-Agent: [rclone/v1.51.0]
   X-Ms-Client-Request-Id: [85f6307e-72ab-464f-7f7b-465cbfa23c2b]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Wed, 20 May 2020 22:33:17 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [7cba63b5-d01e-003c-76f6-2e1cfc000000]
   X-Ms-Version: [2018-11-09]

2020/05/20 18:33:18 ERROR : Attempt 3/3 failed with 1 errors and: -> github.com/rclone/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /Users/runner/runners/2.164.0/work/rclone/src/github.com/rclone/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationFailure) =====
Description=This request is not authorized to perform this operation.
RequestId:7cba63b5-d01e-003c-76f6-2e1cfc000000
Time:2020-05-20T22:33:18.0432725Z, Details:
   Code: AuthorizationFailure
   PUT https://<mystorageaccount>.blob.core.windows.net/<containerfoo>?restype=container&se=2020-05-21t20%3A43%3A16z&sig=REDACTED&sp=racwdl&sr=c&st=2020-05-20t20%3A43%3A16z&sv=2019-10-10&timeout=31536001
   User-Agent: [rclone/v1.51.0]
   X-Ms-Client-Request-Id: [85f6307e-72ab-464f-7f7b-465cbfa23c2b]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Wed, 20 May 2020 22:33:17 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [7cba63b5-d01e-003c-76f6-2e1cfc000000]
   X-Ms-Version: [2018-11-09]

2020/05/20 18:33:18 Failed to copy: -> github.com/rclone/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /Users/runner/runners/2.164.0/work/rclone/src/github.com/rclone/rclone/vendor/github.com/Azure/azure-storage-blob-go/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthorizationFailure) =====
Description=This request is not authorized to perform this operation.
RequestId:7cba63b5-d01e-003c-76f6-2e1cfc000000
Time:2020-05-20T22:33:18.0432725Z, Details:
   Code: AuthorizationFailure
   PUT https://<mystorageaccount>.blob.core.windows.net/<containerfoo>?restype=container&se=2020-05-21t20%3A43%3A16z&sig=REDACTED&sp=racwdl&sr=c&st=2020-05-20t20%3A43%3A16z&sv=2019-10-10&timeout=31536001
   User-Agent: [rclone/v1.51.0]
   X-Ms-Client-Request-Id: [85f6307e-72ab-464f-7f7b-465cbfa23c2b]
   X-Ms-Version: [2018-11-09]
   --------------------------------------------------------------------------------
   RESPONSE Status: 403 This request is not authorized to perform this operation.
   Content-Length: [246]
   Content-Type: [application/xml]
   Date: [Wed, 20 May 2020 22:33:17 GMT]
   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]
   X-Ms-Error-Code: [AuthorizationFailure]
   X-Ms-Request-Id: [7cba63b5-d01e-003c-76f6-2e1cfc000000]
   X-Ms-Version: [2018-11-09]

**Comment by animosity22** [comment]
The fix for that post in in the beta. Are you able to validate in the beta it's not working?

**Comment by kunal0137** [comment]
It is indeed fixed in the latest beta. Closing issue. Thanks.
