### ISSUE TITLE
Implement `rclone about` for Box.com

### ISSUE THREAD

**Issue by ajgrf** [rclone/rclone#4264]
#### What is your current rclone version (output from `rclone version`)?

    rclone v1.51.0
    - os/arch: linux/amd64
    - go version: go1.13.9

#### What problem are you are trying to solve?

The upcoming multiwrite union backend can choose where to write a file by looking at free space of the underlying remotes. If the rclone doesn't report this information for Box, it will be less useful as part of a union.

#### How do you think rclone should be changed to solve that?

Rclone should add `rclone about` support for Box. The Box API reports this information as part of the [user object here](https://developer.box.com/reference/resources/user/).

**Comment by animosity22** [comment]
Where are you seeing in that doc is shows size used for the drive? I'm sure I'm missing it, but wanted to validate.

**Comment by ajgrf** [comment]
If you scroll down there are 2 fields `space_amount` and `space_used`. It's a little confusing because there are four variants of "user," and two of them don't include those fields.

**Comment by animosity22** [comment]
Awesome. Thanks for pointing that out as I see it now!

**Comment by ncw** [comment]
This looks straight forward to implement - we'd have to [call /users/me](https://developer.box.com/reference/get-users-me/).

I had a quick go at this

https://beta.rclone.org/branch/v1.51.0-361-g19073993-fix-4264-box-about-beta/ (uploaded in 15-30 mins)

Does it work for you? If not please run with `-vv --dump bodies` and paste the result!

**Comment by ajgrf** [comment]
It works, thanks!

**Comment by ncw** [comment]
Great!

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

**Comment by piramiday** [comment]
I'm running the latest beta: `rclone v1.51.0-369-g4599e484-fix-4210-pcloud-oauth-beta`, which includes the last fix regarding this issue.
`BOX` is the name of my Box remote, and indeed I can successfully query the quota:
```
user@host ~$ rclone about BOX:
Total:   10G
Used:    247.980M
```
when trying a backup through `rclone sync`, though, I get a lot of NOTICE warnings:
```
user@host ~$ rclone -vP sync ~/my/local/path BOX:remote/path

NOTICE: Free Space is not supported for upstream BOX, treating as infinite
```
is this expected, given the new `about` capabilities for Box? thanks!

**Comment by animosity22** [comment]
I would think so as this request was to add in the about and not rewrite the entire backend :)

You can probably submit an feature request to get that updated as well.

**Comment by piramiday** [comment]
I thought the `union` remote would have used the information now available from `about`, since that's the quota information...

if you confirm this is expected, could you please help me out in phrasing the new feature request?
_please add support to quota information about Box.com in union remote_?

**Comment by ncw** [comment]
> ```
> user@host ~$ rclone -vP sync ~/my/local/path CRYPT-UNION:remote/path
> 
> NOTICE: Free Space is not supported for upstream BOX, treating as infinite
> ```
> 
> 
> is this expected, given the new `about` capabilities for Box? thanks!

That is possibly a bug in the union backend. I've fixed it in the box about code here c08617c70f9740d1050888489df49189160523d7 so if you try [the latest beta](https://beta.rclone.org) it should work a bit better.

**Comment by piramiday** [comment]
so it was a one-liner, after all! no need to rewrite the backend... see, @animosity22? :satisfied:

@ncw a quick test seems to be working! thanks! you really are a bug sniper! :+1:

**Comment by ncw** [comment]
The integration tests (run daily) noticed the problem first so I had fixed it before I saw your comment!
