### ISSUE TITLE
Rclone mount fails on Linux with put.io remote

### ISSUE THREAD

**Issue by aSapien** [rclone/rclone#4268]
#### What is the problem you are having with rclone?  
rclone mount fails on Arch Linux with put.io remote

#### What is your rclone version (output from `rclone version`)
```bash
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.14.2
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Linux 5.6.14-arch x86_64 GNU/Linux

####  Which cloud storage system are you using? (eg Google Drive)
put.io

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
rclone -vv mount putio: /putio
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2020/05/23 22:09:03 DEBUG : rclone: Version "v1.51.0" starting with parameters ["rclone" "-vv" "mount" "putio:" "/putio"]
2020/05/23 22:09:03 DEBUG : Using config file from "/home/localuser/.config/rclone/rclone.conf"
2020/05/23 22:09:03 DEBUG : Putio root '': Mounting on "/putio"
2020/05/23 22:09:03 Fatal error: failed to mount FUSE fs: fusermount: exec: "fusermount": executable file not found in $PATH
```

**Comment by animosity22** [comment]
This is a great forum post.

You need to install fuse for a mount to work.

**Comment by animosity22** [comment]
If you have any follow, please use the forums and we can help you out:

https://forums.rclone.org
