### ISSUE TITLE
B2 API Charges Upload

### ISSUE THREAD

**Issue by geekfred** [rclone/rclone#4269]
I'm getting quite a few charges on API calls for B2 while trying to upload files to it using rclone. I'm moving files from Wasabi to B2 and the API calls start to add up. Class B transactions to be exactly. Shouldn't I be using transactions A only while doing rclone copy wasabi:bucket b2:bucket ?

Is it possible to clarify on this and see if I'm doing something wrong? Should I be getting this charges? I thought PUT API calls were free. I'm using B2 on rclone configured to use it with the S3 API.

Thanks.

**Comment by geekfred** [comment]
To elaborate a bit more in my case. I wanted to add some info on a test I am doing right now.

My caps started at 0 for everything and after 47GB of transfer I am here:

Daily Class B Transactions Caps 
Class B transactions are related to download. 
The first 2,500 are free.Today: $0.10 (252,098)

Daily Class C Transactions Caps 
The first 2,500 are free.Today: $0.00 (888)

Daily Download Bandwidth Caps
The first 1 GB are free.
Today: $0.00 (0 bytes)

How am I getting Class B transactions from the command I am using? If someone knows, because this makes no sense. I understand that I am downloading the file from wasabi to my instance and uploading to B2 but where am I downloading from B2?

The command I ran was:

rclone copy wasabi:icloud-photos-f B2:icloud-photos-f --fast-list -v

**Comment by animosity22** [comment]
This doesn't seem like a bug or feature request, can you please post this on the forums.

https://forums.rclone.org and someone can help you out.

Many thanks in advance.
