### ISSUE TITLE
GUI doesn't search for substrings

### ISSUE THREAD

**Issue by dandv** [rclone/rclone#4270]
#### What is the problem you are having with rclone?
I'm running the GUI from the latest Beta, and the Search box, works, but only for strings that are prefixes of files or directories. For example, "oo" won't match "foo".

#### What is your rclone version (output from `rclone version`)
```
rclone v1.51.0-361-g9db8ecbc-beta
- os/arch: linux/amd64
- go version: go1.14.3
```

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive + crypt

**Comment by animosity22** [comment]
That actually has a separate github and issue list.

Can you close this one out and post it over there?

https://github.com/rclone/rclone-webui-react/issues

**Comment by dandv** [comment]
Would it be easier if an org admin transferred the issue to the other repo?

![image](https://user-images.githubusercontent.com/33569/82742345-b2eb6e80-9d11-11ea-902a-6ffeacb7e294.png)

**Comment by animosity22** [comment]
It's definitely possible but easy if you can just close and create it as well. I'd copy and paste it for you if I could rather than have ncw do it as I rather have him code than move issues.
