### ISSUE TITLE
Missing --sftp-key-pem support

### ISSUE THREAD

**Issue by insign** [rclone/rclone#4283]
#### What is the problem you are having with rclone?
The [docs shows a possible --sftp-key-pem](https://rclone.org/sftp/#sftp-key-pem) parameter but in the cli it returns an error: `Fatal error: unknown flag: --sftp-key-pem`

#### What is your rclone version (output from `rclone version`)
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7

####  Which cloud storage system are you using? (eg Google Drive)
sftp

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone lsd

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
not applicable

**Comment by darthShadow** [comment]
This was added only in the latest release i.e. 1.52. Please download that and try again.

**Comment by animosity22** [comment]
This looks to be answered as the OP had the wrong version. Closing out.

**Comment by insign** [comment]
Yeah! Thank you! There is a telegram or discord talk channel?

**Comment by ncw** [comment]
[the rclone forum](https://forum.rclone.org/) is probably the best we have at the moment!
