### ISSUE TITLE
Idea: standardized OpenPGP encryption and keys access through a system keychain for crypt 

### ISSUE THREAD

**Issue by Zvezdin** [rclone/rclone#4292]
#### What problem are you are trying to solve?

I think that it would be a good idea to support OpenPGP encryption, which for example is already used by the cloud provider mailbox.org . Furthermore supporting a public-key cryptography standard would allow for more interoperability with other drive clients and especially when it comes to sharing or collaborating with others in an encrypted manner.

For example, I could use rclone crypt to sync with Mailbox.org's WebDAV server, encrypt and upload some .docx documents, and then use their web-based .docx editor to continue editing the file, which can work with OpenPGP encrypted files. 

Furthermore such encryption keys could be gathered through system-level keychains or password managers such as KDEWallet. Currently decryption keys are stored in the centralized config. Perhaps there may be benefits of this design decision I don't see but what I can conclude is that it invalidates the purpose of having strong separate encryption keys for different crypt backends, as everything depends on the security of the config encryption password. 

#### How do you think rclone should be changed to solve that?

Add support for OpenPGP keys for crypt and allow for an external secret storage of decryption keys.

**Comment by ivandeex** [comment]
Unfortunately this feature proposal gained zero interest
from core team, volunteers, community, or random github readers
after 20 months on the tracker.
Closing.
