### ISSUE TITLE
rclone deleted everything on my computer

### ISSUE THREAD

**Issue by islandcmd** [rclone/rclone#4298]
#### What is the problem you are having with rclone?

rclone deleted everything on my computer

#### What is your rclone version (output from `rclone version`)

the latest version

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

ubuntu

####  Which cloud storage system are you using? (eg Google Drive)

google drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync GoogleDrive:drive ~

**Comment by calisro** [comment]
Sorry to hear that.  I hope you have backups of your data and can restore.

The sync command tells rclone to make the destination (~) look like the source (GoogleDrive:drive).  On Linux the '~' means the home directory of the user.

https://rclone.org/commands/rclone_sync/#synopsis

**Comment by animosity22** [comment]
If we can do anything to help out, please post on the forums and we are happy to try to assist as this really isn't an issue.

https://forum.rclone.org

**Comment by ncw** [comment]
I'm sorry to hear that :-(

I did have an idea for improving this

"sync" is the dangerous operation.  We can tell if rclone is being run at the command line so maybe we could use those two bits of info somehow...

If "sync" and "command line"
- if source is empty, stop with an error
- if deleted more than X files stop

Any other ideas?

**Comment by animosity22** [comment]
I'd recommend to add any suggestions or comments to the running issue we have going:

https://github.com/rclone/rclone/issues/1574
