### ISSUE TITLE
1.51 and newer breaks white label Jottacloud (eg Elgiganten Cloud and Com Hem Cloud)

### ISSUE THREAD

**Issue by Krakkan83** [rclone/rclone#4299]
Hi. I am reposting this issue/bug report from rclone forum here where i hope it can get some love.
Hi! I'm new but since 1.51 i can not use Elgiganten cloud, they used same login as jottacloud and their storage servers, just rebranded i guess.
From 1.52 notes: "removed remains from old auth" Is there a chance to get this back?
As Elgiganten Cloud still use the old Jottacloud login and that still works for me with 1.50.2. but 1.51 and later breaks that so i can't use with Elgiganten Cloud anymore.
Maybe reintroduce old jotta login/setup and add new remote option for Elgiganten Cloud?
I think eventually elgiganten cloud will change their login to the one Jotta currently uses, but i am unsure of that.
Heres the client from windows store, basically jotta with old login: https://i.imgur.com/XbTaH3b.png
I would love to be able to keep rclone updated past 1.50.2 and still having this remote continuing to work :)

#### What is the problem you are having with rclone?
1.51 and newer versions of rclone no longer work with jottacloud "rebrands" like Elgiganten Cloud/Com Hem Cloud

#### What is your rclone version (output from `rclone version`)
Current version in use is 1.50.2 that still works with Elgiganten Cloud

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, 64-bit

####  Which cloud storage system are you using? (eg Google Drive)
Elgiganten Cloud (jottacloud)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
A remote can not be set up due to Elgiganten cloud still using the old Jottacloud rclone remote setup that was removed/updated since version 1.51

**Comment by ncw** [comment]
There is also an report for "Com Hem Cloud" on the forum

- https://forum.rclone.org/t/com-hem-cloud-jottacloud-no-longer-working/16829

And the forum post that originated this issue for completeness

- https://forum.rclone.org/t/1-51-and-newer-breaks-elgiganten-cloud-jottaclound/16858/3

@buengese have you got time to take a look at these?

**Comment by buengese** [comment]
Yeah I've already seen these. I'm probably going to bring back the old style login as an option for the time being. 

This now makes 2 Versions of Jottacloud I wasn't aware of - does anyone if there are even more?

**Comment by albertony** [comment]
> This now makes 2 Versions of Jottacloud I wasn't aware of - does anyone if there are even more?

Just to sum up:
- [X] Get Sky (sky.get.no): Works with new login
- [ ] Elgiganten: Does not work with new login
    - Elgiganten Sweden: cloud.elgiganten.se
    - Elgiganten Denmark: cloud.elgiganten.dk
    - Giganti Cloud (cloud.gigantti.fi)
    - ELKO Clouud (cloud.elko.is)
    - Elkjøp Cloud (cloud.elkjop.no)
- [ ] Com Hem Cloud: Does not work with new login

**Comment by ncw** [comment]
> Yeah I've already seen these. I'm probably going to bring back the old style login as an option for the time being.

That sounds like a great plan - thanks
