### ISSUE TITLE
rclone sync to AWS S3 bucket - including UploadID + bucket in log file

### ISSUE THREAD

**Issue by jamesbraza** [rclone/rclone#4302]
I have another request that goes hand-in-hand with [AWS S3 CTRL-C doesn't abort multipart upload when using rclone sync, #4300](https://github.com/rclone/rclone/issues/4300).

I am running the `rclone sync` command to AWS S3 with a `--log-file` and `--log-level DEBUG`.  The file being sync'd is large enough such that it's a multipart upload.  See the other ticket for details on my OS, config, and `rclone` version.

I was hoping the `UploadID` and `bucket` would get logged in the file.  This would enable the user to easily/manually abort the upload, after the fact.

Currently, during "init" of the command, neither of these pieces of information get logged.  I think this would be a nice feature, mainly for user friendliness!

**Comment by ncw** [comment]
I think I'd rather do a command to query the exiting multipart uploads for you which wouldn't be too tricky. How does that sound?

**Comment by jamesbraza** [comment]
I think that functionality already exists in AWS CLI ([`list-multipart-uploads` docs](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/list-multipart-uploads.html))

```
aws s3api list-multipart-uploads --bucket my-bucket
```
What value would the query command you propose bring over `list-multipart-uploads`?

**Comment by jamesbraza** [comment]
Yeah I think if could log upload ID, key, and bucket name, that would be useful.  This information would make it convenient for the initiator to work with a multipart upload.

The command you list out also sounds useful to me!  Thank you again!

**Comment by ncw** [comment]
Have a go with this - is this what you expected?

[v1.52.2-134-gc35d25d9-fix-4302-s3-cleanup-beta](https://beta.rclone.org/branch/v1.52.2-134-gc35d25d9-fix-4302-s3-cleanup-beta/) on branch [fix-4302-s3-cleanup](https://github.com/rclone/rclone/tree/fix-4302-s3-cleanup) (uploaded in 15-30 mins)

and in particular with these commands

#### list-multipart-uploads

List the unfinished multipart uploads

    rclone backend list-multipart-uploads remote: [options] [<arguments>+]

This command lists the unfinished multipart uploads in JSON format.

    rclone backend list-multipart s3:bucket/path/to/object

It returns a dictionary of buckets with values as lists of unfinished
multipart uploads.

You can call it with no bucket in which case it lists all bucket, with
a bucket or with a bucket and path.

    {
      "rclone": [
        {
          "Initiated": "2020-06-26T14:20:36Z",
          "Initiator": {
            "DisplayName": "XXX",
            "ID": "arn:aws:iam::XXX:user/XXX"
          },
          "Key": "KEY",
          "Owner": {
            "DisplayName": null,
            "ID": "XXX"
          },
          "StorageClass": "STANDARD",
          "UploadId": "XXX"
        }
      ],
      "rclone-1000files": [],
      "rclone-dst": []
    }



#### cleanup

Remove unfinished multipart uploads.

    rclone backend cleanup remote: [options] [<arguments>+]

This command removes unfinished multipart uploads of age greater than
max-age which defaults to 24 hours.

Note that you can use -i/--dry-run with this command to see what it
would do.

    rclone backend cleanup s3:bucket/path/to/object
    rclone backend cleanup -o max-age=7w s3:bucket/path/to/object

Durations are parsed as per the rest of rclone, 2h, 7d, 7w etc.


Options:

- "max-age": Max age of upload to delete

**Comment by jamesbraza** [comment]
Thanks for the descriptive response.  I think `list-multipart-uploads` is really useful, especially if one has multiple background processes doing uploads.

The original issue I raised was to just list information like upload ID in the log file with `DEBUG` verbosity.  It seems instead, lots of additional functionality has been added, which I think is great stuff.

Is it possible to also have upload ID just be listed in the log file?  Or are you trying to avoid that for some reason?

I also have a two "how it works" questions on `rclone backend cleanup`:

- Would calling `rclone backend cleanup` on a live upload be like entering `CTRL-C` to abort an upload?
    - Can I confirm that "cleaning up" a live upload actually cancels it?
- Is it possible to call `rclone backend cleanup` and have it not be specific to a particular bucket?
    - What if one has multiple uploads going to several different buckets?

**Comment by ncw** [comment]
> Thanks for the descriptive response @ncw! I think `list-multipart-uploads` is really useful, especially if one has multiple background processes doing uploads.

Great!
 
> The original issue I raised was to just list information like upload ID in the log file with `DEBUG` verbosity. It seems instead, lots of additional functionality has been added, which I think is great stuff.
> 
> Is it possible to also have upload ID just be listed in the log file? Or are you trying to avoid that for some reason?

I don't mind putting it in at DEBUG level if you are OK with that?

> I also have a two "how it works" questions on `rclone backend cleanup`:
> 
> * Would calling `rclone backend cleanup` on a live upload be like entering `CTRL-C` to abort an upload?

The cleanup will normally avoid things newer than 24 hours but let's say you did try to remove a multipart upload that was in progress.

What would happen is that the uploading rclone would then get an error on the next segment it attempted to upload, so it would work pretty much like `CTRL-C` to abort the upload except you'd get a different error.

>   * Can I confirm that "cleaning up" a live upload actually cancels it?

Yes it cancels the upload which makes the ID invalid which will make anything using that ID fail.

> * Is it possible to call `rclone backend cleanup` and have it not be specific to a particular bucket?

Just call it with `rclone backend s3:` (no bucket) and it will do all the buckets.
   
>   * What if one has multiple uploads going to several different buckets?

I don't think it will be a problem.

> Then, I can test out the commits you've made.

Look forward to the results!

**Comment by ncw** [comment]
I've merged the cleanup and backend command to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.53

**Comment by jamesbraza** [comment]
Alright, so I am finally getting around to testing this!  To first answer your questions:

> I don't mind putting it in at DEBUG level if you are OK with that?

Yes `DEBUG` level is perfect.

---

**Testing Procedure**

This was run using this version (latest versioned beta): https://beta.rclone.org/v1.52.2-276-gc2f3949d-beta/rclone-v1.52.2-276-gc2f3949d-beta-osx-amd64.zip

1. Created a 22 GB `test-22gb.zip` test file by zipping up a bunch of copies of the 1 GB file from [here](https://www.thinkbroadband.com/download)
2. Made a folder structure like this:

```
.
├── file_dir
│   └── test-22gb.zip
└── logs_dir
```

3. Started multipart upload in one tab of terminal:

```
rclone sync --progress --log-file "./logs_dir/upload1.log" --log-level DEBUG ./file_dir test_aws_s3_list_uploads:jbraza-test-bucket/test-22gb
```

4. Tested `rclone backend list-multipart-uploads` for a specified bucket

```
rclone backend list-multipart-uploads test_aws_s3_list_uploads:jbraza-test-bucket/test-22gb
{
	"jbraza-test-bucket": [
		{
			"Initiated": "2020-07-31T16:43:53Z",
			"Initiator": {
				"DisplayName": "blah",
				"ID": "blah"
			},
			"Key": "test-22gb/test-22gb.zip",
			"Owner": {
				"DisplayName": "blah",
				"ID": "blah"
			},
			"StorageClass": "STANDARD",
			"UploadId": "blah"
		}
	]
}
```

5. Started a second multipart upload in another tab of terminal

```
rclone sync  --progress --log-file "./logs_dir/upload2.log" --log-level DEBUG ./file_dir test_aws_s3_list_uploads:jbraza-test-bucket-2/test-22gb
```

6. Tested `rclone backend list-multipart-uploads` for all buckets

```
rclone backend list-multipart-uploads test_aws_s3_list_uploads:
{
	"jbraza-test-bucket": [
		{
			"Initiated": "2020-07-31T16:43:53Z",
			"Initiator": {
				"DisplayName": "blah",
				"ID": "blah"
			},
			"Key": "test-22gb/test-22gb.zip",
			"Owner": {
				"DisplayName": "blah",
				"ID": "blah"
			},
			"StorageClass": "STANDARD",
			"UploadId": "blah"
		}
	],
	"jbraza-test-bucket-2": [
		{
			"Initiated": "2020-07-31T16:48:18Z",
			"Initiator": {
				"DisplayName": "blah",
				"ID": "blah"
			},
			"Key": "test-22gb/test-22gb.zip",
			"Owner": {
				"DisplayName": "blah",
				"ID": "blah"
			},
			"StorageClass": "STANDARD",
			"UploadId": "blah"
		}
	]
}
```

7. Tested `rclone backend cleanup` with a too-high max age for a specified bucket, about 11 minutes into the first upload

```
rclone backend cleanup --dry-run -o max-age=15m test_aws_s3_list_uploads:jbraza-test-bucket/test-22gb

rclone backend cleanup --dry-run -o max-age=10m test_aws_s3_list_uploads:jbraza-test-bucket/test-22gb
2020/07/31 09:53:55 NOTICE: pending multipart upload for bucket "jbraza-test-bucket" key "test-22gb/test-22gb.zip" dated 2020-07-31 16:43:53 +0000 UTC (10m2.925163s ago): Skipped remove pending upload as --dry-run is set
```

8. Then I killed the first multipart upload via CTRL-Z and then `kill %1`
9. Tested `rclone backend cleanup` with max age for a specified bucket, about 11 minutes into the first upload (this was nice functionality @ncw )

```
rclone backend cleanup -o max-age=10m test_aws_s3_list_uploads:jbraza-test-bucket/test-22gb

rclone backend list-multipart-uploads test_aws_s3_list_uploads:jbraza-test-bucket/test-22gb
{
	"jbraza-test-bucket": [],
	"jbraza-test-bucket-2": [
		{
			"Initiated": "2020-07-31T16:48:18Z",
			"Initiator": {
				"DisplayName": "blah",
				"ID": "blah"
			},
			"Key": "test-22gb/test-22gb.zip",
			"Owner": {
				"DisplayName": "blah",
				"ID": "blah"
			},
			"StorageClass": "STANDARD",
			"UploadId": "blah"
		}
	]
}
```

10. Next, I killed the second multipart upload via CTRL-Z and then `kill %1`
11. Tested `rclone backend cleanup` with max age for all buckets

```
rclone backend cleanup --dry-run -o max-age=5m test_aws_s3_list_uploads:
2020/07/31 09:56:46 NOTICE: pending multipart upload for bucket "jbraza-test-bucket-2" key "test-22gb/test-22gb.zip" dated 2020-07-31 16:48:18 +0000 UTC (8m28.834513s ago): Skipped remove pending upload as --dry-run is set

rclone backend cleanup -o max-age=5m test_aws_s3_list_uploads:

rclone backend list-multipart-uploads test_aws_s3_list_uploads:
{
	"jbraza-test-bucket": [],
	"jbraza-test-bucket-2": []
}
```

All-in-all, no hiccups.  Nice work!!  I think both commands make AWS S3 work with `rclone` even more enjoyable now.

**Comment by ncw** [comment]
> All-in-all, no hiccups. Nice work!! I think both commands make AWS S3 work with `rclone` even more enjoyable now.

Thank you for your comprehensive testing - much appreciated!

I haven't done the last bit of this issue yet the ID in the log!

**Comment by ncw** [comment]
We now have the ID in the log!

Closing this.
