### ISSUE TITLE
Add windows file properties (version info and icon resources)

### ISSUE THREAD

**Issue by albertony** [rclone/rclone#4304]
It would be nice if rclone.exe on windows would include file properties such as product name, file description, version, as well as an icon.

![](https://cloud.githubusercontent.com/assets/2394539/12073634/0b32cb04-b0f6-11e5-9d8e-f9923ca554cf.jpg)

The most useful would be the version information, then one could use PowerShell to retrieve the numerical version number `(Get-Item rclone.exe).VersionInfo.FileVersion`, and for instance compare it with latest released version by accessing GitHub API. I know I can execute `rclone version`, but then I need to perform string parsing and also I need to run a process instead of just accessing file properties.

Syncthing has implemented this in go already, so I'm thinking it wouldn't be too hard if using it as inspiration.
> On Windows generate a special file which the Go compiler will automatically use when generating Windows binaries to set things like the file icon, version, etc.

(https://github.com/syncthing/syncthing/blob/master/build.go)

Solution seems to be based on executing a command line utility, [GoVersionInfo](https://github.com/josephspurrier/goversioninfo), during the build process.

I could try to implement this myself, if you agree it is a good idea, but I am not proficient in go so may be needing some pointers along the way (for instance I am not sure if this introduces some changes to how the build process must be performed).

Another step up would be to authenticode sign the executable, but that requires a certificate etc so would need a bit more effort - and probably money. See https://github.com/syncthing/syncthing/issues/3420.

**Comment by albertony** [comment]
Perhaps something like this:
- Add execution of `go get github.com/josephspurrier/goversioninfo` to rclone's `Makefile`, to get the command line utility in place.
- Port the "syso-file" related code from Syncthing's [build.go](https://github.com/syncthing/syncthing/blob/master/build.go) into a separate .go file in bin folder of rclone repo.
- Execute the new .go file from the makefile with `go run`, to generate a .syso file.
- Continue with the existing build steps, the go build will automatically pick up the .syso file.

**Comment by ncw** [comment]
> I know I can execute `rclone version`, but then I need to perform string parsing and also I need to run a process instead of just accessing file properties.

You can also execute `rclone version --check` to see whether your version is up to date with the latest version.

> Solution seems to be based on executing a command line utility, [GoVersionInfo](https://github.com/josephspurrier/goversioninfo), during the build process.

That looks like a good tool :-)
 
> I could try to implement this myself, if you agree it is a good idea, but I am not proficient in go so may be needing some pointers along the way (for instance I am not sure if this introduces some changes to how the build process must be performed).

Yes if you'd like to have a go - that would be fantastic.

The production build is kicked off here

https://github.com/rclone/rclone/blob/fb61ed8506e68db0ea19c62a08daa9cdee59dda5/bin/cross-compile.go#L172

So you'd want to run the goversioninfo tool just once, probably in this function

https://github.com/rclone/rclone/blob/fb61ed8506e68db0ea19c62a08daa9cdee59dda5/bin/cross-compile.go#L226

You can use the runEnv command to run a binary

https://github.com/rclone/rclone/blob/fb61ed8506e68db0ea19c62a08daa9cdee59dda5/bin/cross-compile.go#L72

You can add build dependencies to rclone by adding them here - so you'd add `goversioninfo` here.

https://github.com/rclone/rclone/blob/fb61ed8506e68db0ea19c62a08daa9cdee59dda5/Makefile#L85-L87

The logos for rclone are in the top level graphics directory - I'd expect you'd need to convert one of those into an .ico file. I'd leave it in that graphics directory.

**Comment by albertony** [comment]
I will give it a try, thanks for the pointers.

> You can add build dependencies to rclone by adding them here - so you'd add goversioninfo here.

The josephspurrier/goversioninfo repo does not publish releases, so it must be built from source.  I'm a bit confused with go modules etc, so don't know if the correct way to do it is to just add a go install line like this:

```
# Get the build dependencies
build_dep:
	go run bin/get-github-release.go -extract golangci-lint golangci/golangci-lint 'golangci-lint-.*\.tar\.gz'
	go install -mod=mod github.com/josephspurrier/goversioninfo/cmd/goversioninfo
```

**Comment by ncw** [comment]
> I will give it a try, thanks for the pointers.
> 
> > You can add build dependencies to rclone by adding them here - so you'd add goversioninfo here.
> 
> The josephspurrier/goversioninfo repo does not publish releases, so it must be built from source. It is not a proper go module, so I get some issues. Tried adding it with a go install line like this, which sort of works locally, but the "modules_race" test fails with "inconsistent vendoring" (see #4305):
> 
> ```
> # Get the build dependencies
> build_dep:
> 	go run bin/get-github-release.go -extract golangci-lint golangci/golangci-lint 'golangci-lint-.*\.tar\.gz'
> 	go install -mod=mod github.com/josephspurrier/goversioninfo/cmd/goversioninfo
> ```

Here is a hacky workaround

    cd .. && go install -mod=mod github.com/josephspurrier/goversioninfo/cmd/goversioninfo

I don't know the proper way of doing this!

**Comment by albertony** [comment]
I'll probably just use that then.
(There is a pull request https://github.com/josephspurrier/goversioninfo/pull/35 from september 2019 to add go.mod, maybe that will make it easier to use, but I'm not that familiar with go modules myself).

**Comment by ncw** [comment]
I finally got this working - what a voyage!

Here are the two commits which fixed it

33c8709439ed54779ada79910a9432d509ddeea6
a1c9612d75af9c4caa922e80c423033c3af4dc8d

In 15 mins from now the beta should have nice images and version info :-)

**Comment by albertony** [comment]
Great!! I checked the latest beta right now, and it works:

![image](https://user-images.githubusercontent.com/12441419/85051716-24470180-b198-11ea-92bc-2c88d78437f2.png)
(Windows shows in its properties dialog "Product version" as the string variant ("1.52.1-094-g40611fc4-beta") and "File version" as the raw 4 part numeric variant (1.52.1.0), while PowerShell shows all 4 version variants).

PS: Sorry I did not manage to clean out those bugs before pushing my merge request, and that it turned out to be such a hard nut. Thank you for working it out!

**Comment by ncw** [comment]
> Great!! I checked the latest beta right now, and it works:

Great! I had to break out the Windows VM to crack this so I've seen it in person now too!



> PS: Sorry I did not manage to clean out those bugs before pushing my merge request, and that it turned out to be such a hard nut. Thank you for working it out!

No problems! There were several things in play here and it didn't help that I didn't notice the messages from the amd64 and the 386 builds were different. It took me such a long time to realise that the file not found error was because we'd built a 386 binary (because GOARCH was set)...

Anyway, it is done now and we can enjoy pretty binaries in Windows now 😃
