### ISSUE TITLE
Change SFTP root directory

### ISSUE THREAD

**Issue by kennyparsons** [rclone/rclone#4307]
#### What is your current rclone version (output from `rclone version`)?
v1.52.0

#### What problem are you are trying to solve?
Change the sftp path used by rclone. Currently rclone defaults to accessing the path of user's home directory. Many popular sftp/ssh clients allow you to change this. For example, if logging in with `root`, ssh defaults to `/root/` as the current directory. 
The flag `--sftp-path-override`, as far as I can tell, does not focus on this "change path" scenario. 

#### How do you think rclone should be changed to solve that?
A flag to pass the root directory to be mounted, instead of defaulting to the user's home directory. 
Flag: `--sftp-working-dir`
Example: `--sftp-working-dir /`
Assumed Limitations: the directory supplied needs to be accessible by the sftp user. This is not a limitation of rclone, but rather of the ssh server config/permissions.

This flag might be better served in the remote definition (`rclone config`), much like setting the `root_folder_id>` for the google drive backend.

**Comment by animosity22** [comment]
Can you post an example of what is happening and what you'd expect to happen?

**Comment by ncw** [comment]
You can use the alias backend for this which is what we usually recommend

https://rclone.org/alias/

**Comment by kennyparsons** [comment]
@animosity22 
Here's my remote config:
```
[sftp_test]
type = sftp
host = 192.168.2.9
user = root
port = 22
pass = *** ENCRYPTED ***
```

When I browse or mount this remote, I am seeing the path `/root`, which is the home directory of the user configured in this remote (root). This is default behavior for ssh connections. 

What I want to do is be able to specify the path I want to ssh/sftp into. Most sftp clients allow you do this by setting the path option. For example: WinSCP allows you to set the directory you want to sftp into. 
![image](https://user-images.githubusercontent.com/5930491/83931432-5ac95900-a762-11ea-8714-07656634f8c9.png)

@ncw I am not seeing alias as viable option here. Maybe I just don't get it. Take this scenario. Host A has a directory I want to access from another host, such as host B - a macbook. My macbook has a nice sftp client, such as cyberduck, so I can easily sftp to host A and browse any directory, including `/`. 
But Host C, a headless linux VM, needs a solution to also browse Host A, preferably by SFTP. 

Currently, using the config posted above, I can certainly browse Host A, but I'm limited to the user's home directory, in this case `/root/`. I'd like to be able to also browse `/`, `/srv`, `/var/`, `/etc`, and so on. With my mac or my windows machine, I can easily configure cyberduck or winscp to change the directory I SFTP into, such as `/` in the example is above.

**Comment by animosity22** [comment]
Oh ok, I see what you mean.

You'd just make an alias remote of the SFTP if you wanted to change the starting path like this:

```
[SFTP]
type = sftp
host = localhost
user = felix
port = 4022
pass = somepassword

[TEST]
type = alias
remote = SFTP:/
```

and just use the TEST remote

rclone lsd TEST:

as an example.

**Comment by kennyparsons** [comment]
ok that does work. 
Maybe this feature request can get converted to a document change? The sftp remote docs could be a little clearer to use alias to change the directory the sftp remote: uses. 

Thanks!
