### ISSUE TITLE
Cli syntax: Multiple sources for single destination

### ISSUE THREAD

**Issue by darkdragon-001** [rclone/rclone#4308]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.50.2

#### What problem are you are trying to solve?
Use shell globbing (`*`) to copy multiple files.

#### How do you think rclone should be changed to solve that?
`rclone copy` should allow multiple source arguments and a single destination argument like `rsync`, `mv`, ...

**Comment by animosity22** [comment]
That already exists via the filtering as a directory is normally the source until you want to move a single file.

Can you give an example of what you'd want to happen if I'm not understanding it?

**Comment by darkdragon-001** [comment]
I want multiple directories or files

    rclone copy /folder/prefix* backend:bucket/path/

Should copy `folder/prefix` and `/folder/prefix_something`, but fails with the message that only two non-flag arguments are allowed, but three given.

**Comment by animosity22** [comment]
You can already do that with include / filters.

Example would be:

```
felix@gemini:~/test$ rclone ls /home/felix/test
      413 prefixtest/hosts
      413 prefixblah/hosts
      413 nope/hosts
felix@gemini:~/test$ rclone ls /home/felix/test --include 'prefix**'
      413 prefixtest/hosts
      413 prefixblah/hosts
```

**Comment by darkdragon-001** [comment]
I am just saying that if you are claiming to be the `rsync` for cloud storage, I would expect to be as compatible as possible with rsync syntax. Otherwise people will use rclone/goofys only to mount the folder and continue using rsync which obviously has multiple downsides...

**Comment by animosity22** [comment]
I think that was an old line that was removed as it was confusing for me as well as rclone is not rsync and doesn't plan to be.

The goal does not seem to be equivalent rsync commands. If you check the updated pages, please let us know if something seems. off still as rclone.org has been updated recently with changes to prevent those confusing things.

**Comment by darkdragon-001** [comment]
Maybe a _migration_ guide would be helpful then, which rsync commands translate to which rclone ones...

**Comment by animosity22** [comment]
That feels like quite a rabbit hole to go down as rsync is very different from rclone in how it works and what it does imo.

That doesn't feel maintainable to me as it's hard enough to keep just documentation clean and up to date.

Perhaps @ncw and @calisro and @darthShadow  can chime and share their feedback or something like that.

**Comment by darkdragon-001** [comment]
When moving from traditional network shares (samba, nfs, ...) to cloud storage (S3, Minio, Backblaze), I was looking for a replacement of rsync to accomplish the same things (copy files and folders reliably and easily) in the cloud domain. The more I learn about rclone, the more complicated it becomes (you have seen the other issues I opened)... I just want to copy some files! Maybe rclone is not the right tool for this task...

**Comment by darkdragon-001** [comment]
I am closing the issue since it seems to be intended behavior.

**Comment by ncw** [comment]
> `rclone copy` should allow multiple source arguments and a single destination argument like `rsync`, `mv`, ...

This would work nicely for local to remote copies. It wouldn't work at all for remote to local copies though as if the shell is interpreting the globs then it won't know how to interpret them for a remote

    rclone copy *.jpg drive: # could be made to work
    rclone copy drive:*.jpg . # won't work

I could make the source files understand globbing so you'd write

    rclone copy "*.jpg" drive: # could be made to work
    rclone copy "drive:*.jpg" . # won't work

And rclone would convert that to

    rclone copy . --include "*.jpg" drive:
    rclone copy drive: --include "*.jpg" .

Multiple sources for `copy` would be relatively easy but all the source files would have to be limited to the same backend.... Maybe even limited to the local disk.

**Comment by darkdragon-001** [comment]
This is why I named the issue "multiple sources" and not "shell globbing". So I think it would be perfectly fine to just allow multiple sources. For remote wildcards, one can use the `--include` filter. If it is limited to a single backend, this is also fine when a comprehensible error message is shown when different backends are specified...

**Comment by ncw** [comment]
What do you think about the multiple sources being limited to the local disk? Is that too limiting?

**Comment by animosity22** [comment]
I think it adds more confusion and more points for failure. 

Shell globing is already done via filters and that works well.

If I had two sources to run, I can run two commands. If I really wanted to run two sources, I can already do that with a filter as well by going up a level and filtering.

**Comment by limzykenneth** [comment]
I don't see filters as the same as supplying multiple paths, and in the context of `rclone sync` the source and detination folder will need to be mirrored at the end of the command where if it is syncing just the folders provided by the wildcard pattern I can have a selection of files and folders locally without including everything that is in the source folder. To illustrate:

In source folder:
```
folder/sub1
folder/sub2
folder/sub3
```

In destination folder
```
folder/sub1
folder/sub2
folder/sub3
folder/sub4
folder/sub5
```

Now I have to run `rclone sync folder/sub1 remote:folder/sub1` then `rclone sync folder/sub2 remote:folder/sub2` then `rclone sync folder/sub3 remote:folder/sub3` to sync local changes to the remote. 

If I run `rclone sync folder/ remote:folder/ --filter-from filterFile` where `filterFile` is simply (or any other filter pattern)

```
+ *
```

On the remote `folder/sub4` and `folder/sub5` will be deleted, which is not desired. Would be nice to be able to sync all the files and folders in `folder` to the remote without having `folder` be mirrored locally and since the command `rclone sync folder/ remote:folder/` acts on `folder` itself it make sense for them to be mirrored but if for example wildcard is supported like `rclone sync folder/* remote:folder/` the wildcard would expand and applies to the content of `folder` individually, thus deleting `folder/sub4` and `folder/sub5` would make less sense.

My actual use case have dozens of folders I need to sync in the root folder and instead of running `rclone sync` dozens of times, I can just run it once with wildcard would be a great help.

**Comment by ivandeex** [comment]
From https://github.com/rclone/rclone/issues/1426#issuecomment-727675477

Currently rclone treats metacharacters (`*?`) in source file name as part of the name, while in spurce filter arguments (`--include --exclude`) they are treated as _globs_. Changing this behavior would **break** existing scripts.

The only solution I can see is a new flag like `--source-is-filter`. The flag is probably meaningful for `copy move sync delete` commands, meaningless for `copyto` and many others. It needs more investigation, looks like a pretty large task.

**Comment by ivandeex** [comment]
This request will be solved as part of #4777

**Comment by ivandeex** [comment]
@ncw @darkdragon-001 

We agree that using filters is not enough.
This request will be implemented by the new `cp`, `mv`, `rsync` commands (tickets #4777 and #4776).

All valid requirements have been copied over to #4777

@darkdragon-001 
Please subscribe to the new ticket.
As it is quite tricky to replicate the features of cp/mv we can't provide ETA yet.

**Comment by ivandeex** [comment]
I am going to close this as all requirements are collected in #4777
