### ISSUE TITLE
"Failed to copy: mkdir /Zeus: read-only file system"

### ISSUE THREAD

**Issue by gdthecomp** [rclone/rclone#4310]
#### What is the problem you are having with rclone?

When I run rclone sync I get the error "Failed to copy: mkdir/Zeus: read-only file system"
For context, Zeus is name of my mounted Synology NAS. I am trying to sync my Documents folder from my mac to a subfolder of Zeus. I am logged into Zeus and 'get info' shows I am able to read/write, which I confirmed by successfully dragging and dropping files from my mac to that folder. 

#### What is your rclone version (output from `rclone version`)

rclone v1.52.0

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Catalina 10.15.4 64-bit

####  Which cloud storage system are you using? (eg Google Drive)

Right now, none. I'm trying to sync files from my Mac laptop to my NAS, which is loaded as a network directory on my Mac. 

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Failed to copy: mkdir/Zeus: read-only file system
When I try running rclone sync with just one file in that folder, I get a different error, however: 2020/06/05 20:21:24 ERROR : Local file system at /Volumes/Zeus/Macbook/: not deleting directories as there were IO errors
2020/06/05 20:21:24 ERROR : Attempt 3/3 failed with 1 errors and: failed to read directory entry: fdopendir: not a directory
2020/06/05 20:21:24 Failed to sync: failed to read directory entry: fdopendir: not a directory

**Comment by animosity22** [comment]
For use questions, please use the forums.

If you can follow the forum template, we can help you out there.

https://forum.rclone.org

Thanks!
