### ISSUE TITLE
Request to add flag for rclone-cat to fail if path is a directory

### ISSUE THREAD

**Issue by anderspitman** [rclone/rclone#4311]
#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.14.2
```

#### What problem are you are trying to solve?

I'm building a frontend for rclone that exposes backends over a simple HTTP protocol. The two fundamental operations are listing a directory and retrieving the contents of a file. I'm able to use rclone-cat to retrieve files. The problem is, I don't know if a request path is a file or a directory (or doesn't exist) until doing rclone-ls. I never want to do a cat on directories, because rclone defaults to catting all children. It would be ideal for me if catting a directory failed, like a traditional filesystem. Currently, this requires an extra roundtrip to determine the type of the path. On slower backends like GDrive this is a significant performance hit.

#### How do you think rclone should be changed to solve that?

I think if there was something like a `--fail-on-dir` flag for rclone-cat, which fails if the path is a directory, rather than catting all the children, it would solve my problem.

**Comment by anderspitman** [comment]
Looking at https://github.com/rclone/rclone/issues/4057, making catting more efficient in general would be very appealing to me. I'd be more than happy to help out as well.

**Comment by animosity22** [comment]
Maybe a silly question, but you can already use rclone serve http to expose a remote via http.

Is this something different than that?

**Comment by anderspitman** [comment]
Yeah, I'm implementing a specific protocol, including authorization and write/delete.

**Comment by ncw** [comment]
Adding a `--file` flag to `cat` seems sensible to me. That could be implemented more efficiently without #4057 too.  Want to have a go @anderspitman ? Happy to talk you through what needs to be done.

**Comment by anderspitman** [comment]
@ncw absolutely, I'm very motivated to get rclone working for my use case.

To give a little more context, rclone currently seems to be more focused on bulk transfers, each initiated by an explicit CLI command. So even a few seconds at the beginning isn't too big a deal. My frontend, however, works more like GDrive, where you need to be able to navigate through your directory tree, upload/download files, generate lots of thumbnails, etc with as low of latency as possible.

It would be great if I can make some reasonable modifications to rclone, since then I get a ton of backends for free. If that's not feasible though I'll have to just implement wrappers for a few of the big ones (S3, GDrive, Dropbox, etc) by hand.

What are your thoughts. Will `--file` for `cat` get us most of the way there, or are there deeper architectural issues that will need to be solved (such as #4057 perhaps)?

**Comment by anderspitman** [comment]
So I implemented a first draft of this in #4328, but then I realized I actually require additional information (such as file size) so I need to do a preemptive `ls` anyway. Some basic caching should mostly solve my problem. I'm still interested in helping reduce rclone's latency for certain commands if there's reasonably low hanging fruit there.

**Comment by calisro** [comment]
What about an option to dump some json meta data to standard error while still catting to standard out which then you'd get both sets of data with one call. Slightly hacky so I'm not sure if that's even reasonable.

**Comment by anderspitman** [comment]
That would likely reduce latency in certain situations, but given that I'm optimizing for traditional directory tree navigation, In typical usage I'll have already retrieved an ls of whatever I'm trying to cat, so I just need to start caching that information and my problem is essentially solved.
