### ISSUE TITLE
Longer retry time when there is a connection problem to prevent failed upload

### ISSUE THREAD

**Issue by MagTun** [rclone/rclone#4313]
#### What is the problem you are having with rclone?
I was doing a rclone sync to an aws cloud and I briefly switch off my computer wifi (for less than a second with the keyboard shortcut) and the rclone sync failed with the error below.
I would be nice if rclone could have a longer retry time when there is this kind a problem on the internet connection (first every couple of seconds then couple of min for something like 15min or more)

For less than 1 second of interruption in my internet connection,  I lost several hours on the upload because of this. 

#### What is your rclone version (output from `rclone version`)
rclone v1.52.0
- os/arch: windows/amd64
- go version: go1.14.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
AWS (but I don't think it matters here)

#### A log from the command

2020/06/05 14:35:14 DEBUG : file.AVI: Need to transfer - File not found at Destination
2020/06/05 14:35:42 DEBUG : pacer: low level retry 1/1 (error Put "...": write tcp ...: wsasend: An existing connection was forcibly closed by the remote host.)
2020/06/05 14:35:42 DEBUG : pacer: Rate limited, increasing sleep to 10ms
2020/06/05 14:35:42 DEBUG : file.AVI: Received error: Put "....": write tcp ...: wsasend: An existing connection was forcibly closed by the remote host. - low level retry 1/10
2020/06/05 14:35:42 DEBUG : pacer: Reducing sleep to 0s
2020/06/05 14:35:42 ERROR : file.AVI: Failed to copy: Put "...": dial tcp: lookup ...: no such host
2020/06/05 14:35:42 ERROR : Attempt 1/3 failed with 1 errors and: Put "...": dial tcp: lookup ...: no such host
2020/06/05 14:35:42 ERROR : Attempt 2/3 failed with 1 errors and: RequestError: send request failed
caused by: Head "...": dial tcp: lookup ...: no such host
2020/06/05 14:35:42 ERROR : Attempt 3/3 failed with 1 errors and: RequestError: send request failed
caused by: Head "...": dial tcp: lookup ...: no such host
2020/06/05 14:35:42 INFO  :       348k / 348 kBytes, 100%, 12.672 kBytes/s, ETA 0s

2020/06/05 14:35:42 DEBUG : 3 go routines active
2020/06/05 14:35:42 Failed to copy: RequestError: send request failed
caused by: Head "...": dial tcp: lookup ...: no such host

**Comment by calisro** [comment]
I believe these will help fix your issue by increasing them:

--retries-sleep and --retries

**Comment by calisro** [comment]
If there's more we can help with here, please let us know. The forum is best for questions.

**Comment by MagTun** [comment]
Thanks a lot, it's working! Sorry for posting this here rather than on the forum.
