### ISSUE TITLE
hash output overlapping

### ISSUE THREAD

**Issue by Xyz00777** [rclone/rclone#4322]
#### What is the problem you are having with rclone?
i used `rclone hash MD5 LokalPath -P` to see the overall progress of the hashing.
while i do these i saw that the terminal output get overlapped.
![image](https://user-images.githubusercontent.com/52142054/84084792-72b00f80-a9e4-11ea-9ab0-9e467a09a878.png)

#### What is your rclone version (output from `rclone version`)
1.52

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
rasbian actuall

oh and where did the hash file get saved?
and is there a simple way for something like auto hashing for new data? because i transfered my dadta per samba to my raspi drive and i used rclone sync for syncing to my encrypted drive and it sayed that nether cloud or storage have hash values...

Greetings
Xyz00777

**Comment by animosity22** [comment]
You can't use a hash value on a crypt remote as the files are encrypted and the hash changes.

On local files, hashes are not saved as they are calculated on use. On the a cloud provider, the hash is kept via the cloud provider in their metadata.

These are great questions to post on the forums at https://forum.rclone.org

I'm also not sure what you mean by overlapping as it just seems to be wrapping on your window.

**Comment by Xyz00777** [comment]
okay i didnt know the correct word. if you say its wrapping than its wrapping :D 
could these be a problem because of tmux that its to fast and because of that its wrapping?

**Comment by animosity22** [comment]
tmux / screen both do a lot of terminal emulation and limit things on the screen. I still can't figure out what's wrong on that picture or incorrect as it seems like normal output to me.

overlapping to me means that I was writing something like:

```

Test 100%
```

and it was overlapped by something above it:

```
Somethi
ng Test 100%
```

and it hit the next line or something causing a visual bug. If you are using tmux/screen or anything though, you'd most likely see odd things like that. I'd just dump it to a log file and use the log file albeit, I'm not sure of the point of hashing local files either, but that's a different question :)

**Comment by Xyz00777** [comment]
okay...
In my opinion it should look the whole time like my third try with only updating the last line when you use the -P
![image](https://user-images.githubusercontent.com/52142054/84137775-7035d000-aa4d-11ea-8e15-df10e20c8456.png)

**Comment by animosity22** [comment]
I'm not following. Each screen looks to be right. The middle have 4 transfers going before you stop it and when you restart it, only a check is going at the bottom of the screen.

**Comment by Xyz00777** [comment]
okay but i dont understand why i get a new progress line for every new file who get checked... I would expect that i get only one transferred and check line who get updatet with the progress of all data in these folder and not for every new file 2 new lines...

**Comment by animosity22** [comment]
Let us take a step back as what are you trying to accomplish ? What output are you trying to see on the screen?

**Comment by Xyz00777** [comment]
i mean when i use any of the hash commands with the progress tag i would expect, that i get a output like my third try but with updating transfered, checks and checking line and not additional lines for them like in my first and second try at the last screen shot

**Comment by animosity22** [comment]
You get lines because you've asked and used -P so it updates progress.

You can do this:

```
felix@gemini:~/test$ rclone md5sum /home/felix/test
9d462dd04bf1f85ed21f8d9a51c709eb  test.mkv
9d462dd04bf1f85ed21f8d9a51c709eb  test1.mkv
```

You have this:

```
felix@gemini:~/test$ rclone md5sum /home/felix/test -P --stats-one-line
0 / 0 Bytes, -, 0 Bytes/s, ETA -9d462dd04bf1f85ed21f8d9a51c709eb  test.mkv
0 / 0 Bytes, -, 0 Bytes/s, ETA -9d462dd04bf1f85ed21f8d9a51c709eb  test1.mkv
0 / 0 Bytes, -, 0 Bytes/s, ETA -
```

With doing a md5sum, you have no transfers and it's only doing checks so -P is really showing progress for transfers, which you are doing 0 of.

**Comment by Xyz00777** [comment]
okay i think it's not what i expected. well then no problem :)
have a nice day
