### ISSUE TITLE
Cannot install rclone

### ISSUE THREAD

**Issue by Nicolas-V13** [rclone/rclone#4323]
#### What is the problem you are having with rclone?

[root@SERVERNAME~]# curl https://rclone.org/install.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:07 --:--:--     0curl: (7) Failed to connect to 2a02:24e0:8:61f9::1: Network is unreachable
[root@SERVERNAME~]#

#### What is your rclone version (output from `rclone version`)

N/A

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Centos7

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

curl https://rclone.org/install.sh | sudo bash

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

can ping so not from my side it looks like, is there anything wrong?

[root@SERVERNAME~]# ping rclone.org
PING rclone.org (5.153.250.7) 56(84) bytes of data.
64 bytes from nick3.miniserver.com (5.153.250.7): icmp_seq=1 ttl=43 time=22.1 ms
64 bytes from nick3.miniserver.com (5.153.250.7): icmp_seq=2 ttl=43 time=23.0 ms
^C
--- rclone.org ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 22.182/22.635/23.088/0.453 ms
[root@SERVERNAME~]#

**Comment by animosity22** [comment]
Please use the forums for use questions:

https://forum.rclone.org
