### ISSUE TITLE
Add cleanup support for Box

### ISSUE THREAD

**Issue by ambipur76** [rclone/rclone#4326]
#### What is your current rclone version (output from `rclone version`)?

1.51.0

#### What problem are you are trying to solve?

When performing an automated backup it is essential to be able to cleanup the Trash / Recycle Bin folder to free up the complete storage space.

#### How do you think rclone should be changed to solve that?

The rclone cleanup <remote> command could support this feature.

**Comment by ncw** [comment]
When we looked at this here https://github.com/rclone/rclone/issues/575#issuecomment-330028744 we decided

> **box**: The Box API provides an endpoint for [listing trashed items](https://developer.box.com/reference#get-the-items-in-the-trash) and [permanently deleting trashed items](https://developer.box.com/reference#permanently-delete-a-trashed-file). However, there's no endpoint for permanently deleting trashed items and the Box API does not support batch API calls. Cleanup is not feasible since it involves listing all trashed items and making a delete request for each item. [Docs](https://developer.box.com/reference)

So I guess we could implement it but it might take a really long time.

Is this something you'd like to help with @ambipur76
