### ISSUE TITLE
Add mount path to rclone.conf

### ISSUE THREAD

**Issue by ambipur76** [rclone/rclone#4327]
#### What is your current rclone version (output from `rclone version`)?

1.51.0

#### What problem are you are trying to solve?

When applying the rclone mount <remote> command, the path to mountpoint always has to be provided. This results in unnecessarily long command lines or when automating, eg. writing systemd units for mounting specific remotes, the mount path has to be "hardcoded" to the system unit, bash script or whatever.

#### How do you think rclone should be changed to solve that?

Optional "mountpath" configuration option in rclone.conf, for each remote separately could solve this problem.

**Comment by animosity22** [comment]
You can already use environment variables in systemd and in bash scripts so you'd could always configure that as well if it was a real issue. 

I use this in my mount:

```
Environment=RCLONE_CONFIG=/opt/rclone/rclone.conf
```

As an example and you can use an environment file if you had multiples.

**Comment by ambipur76** [comment]
I have found a more detailed documentation here: https://github.com/rclone/rclone/wiki/Systemd-rclone-mount
Based on your help and the mentioned documentation I managed to simplify my rclone mount-related systemd units.
