### ISSUE TITLE
OneDrive Business Headless Setup

### ISSUE THREAD

**Issue by mariusurbelis** [rclone/rclone#4337]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.52.1
- os/arch: linux/amd64
- go version: go1.14.4

#### What problem are you are trying to solve?
Connect to a OneDrive Business account using rclone headless setup.

#### How do you think rclone should be changed to solve that?
Any kind of prompt allowing to choose business would be nice. Now trying to authorise with `rclone authorize "onedrive"` only brings up the personal drive login and trying to input the organization email does not work.

**Comment by animosity22** [comment]
When I rclone authorize onedrive, I can see all my personal and business logins as seen by:

![image](https://user-images.githubusercontent.com/5088712/84417021-08b18900-abe3-11ea-81a8-eb9d086cee7b.png)

For general use questions, the forums are the best place for these things rather than an issue as well.

https://forum.rclone.org

**Comment by mariusurbelis** [comment]
![rclone](https://user-images.githubusercontent.com/32742633/84419554-ae2f2180-ac10-11ea-9bd8-f733e8bd0736.gif)

Thank you for a speedy response. I do not have any other options than these when prompted to login.

**Comment by animosity22** [comment]
What's the actual @domain you are trying?

**Comment by mariusurbelis** [comment]
> What's the actual @Domain you are trying?

dundee.ac.uk

Must be an issue on Microsoft's end? I remember using it for Box.com with the same email a few years ago. Now that the university has switched to OneDrive something is not right.

**Comment by animosity22** [comment]
The login page listed works with personal and business. The error message is stating that something is not right on the company site because the account is not found.

If the org is setup properly, you get the page I shared as it'll redirect for the org sign on.

Are you able to login to any MS services at all?

**Comment by mariusurbelis** [comment]
https://login.microsoftonline.com/ does prompt me for the login to the org account.
https://login.live.com/ which rclone directs me to does not transition into organization login page.

**Comment by animosity22** [comment]
I think you have something else going on as your first link does not work in an incognito window for me as it fails:

![image](https://user-images.githubusercontent.com/5088712/84423929-461b1400-abed-11ea-8394-ba9246b1cbb2.png)

**Comment by mariusurbelis** [comment]
Using a correct username for example "jbloggs" for a full email jbloggs@dundee.ac.uk does work.

**Comment by animosity22** [comment]
With a working user name, that also works for me in rclone the same way:

![image](https://user-images.githubusercontent.com/5088712/84424598-52ec3780-abee-11ea-8235-a26e8aed280f.png)

**Comment by animosity22** [comment]
The live.com is for home/personal users so that wouldn't work.

**Comment by mariusurbelis** [comment]
I have a suspicion that the computer I was running the `rclone authorize` had an older rclone version as apt installs a random old version. I shall try again with an updated version.

**Comment by animosity22** [comment]
Installing for a package repo is not recommended as a repo can do anything they want.

Best to install from rclone:

https://rclone.org/downloads/

**Comment by mariusurbelis** [comment]
My apologies for creating this issue. It was the fact that I was authorizing with an older version of rclone. Thank you for your help @animosity22

**Comment by animosity22** [comment]
Ah hah! Ok, that makes sense. No worries and happy to help and glad we got the bottom of it!
