### ISSUE TITLE
Add Scaleway to S3 providers

### ISSUE THREAD

**Issue by psychopatt** [rclone/rclone#4338]
#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.52.1
- os/arch: linux/amd64
- go version: go1.14.4
```

#### What problem are you are trying to solve?
As suggested after closing #4159, ease configuration of a remote using [Scaleway](https://www.scaleway.com/en/object-storage/) 

#### How do you think rclone should be changed to solve that?
(shamelessly [quoting](https://github.com/rclone/rclone/issues/4159#issuecomment-642243445) @ncw for the first 2 points)
- make a provider for Scaleway
- reset max_upload_parts to 1000 for this provider
- reset force_path_style to false for this provider

**Comment by ncw** [comment]
Thanks for doing this @psychopatt :-)

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.53
