### ISSUE TITLE
Add about support for Box

### ISSUE THREAD

**Issue by ambipur76** [rclone/rclone#4345]
#### What is your current rclone version (output from `rclone version`)?

1.5.10

#### What problem are you are trying to solve?

Please add support for command rclone about Box: . I am using the rclone mounted Box: storage in conjunction with mergerfs. The other merged storage is 4shared.com. Firstly the data was written to Box: storage and the drive was fully written, no space has left.

#### How do you think rclone should be changed to solve that?

 Without the ability to check the available free space on the mounted storage, mergerfs has no chance to send the data to the other merged drive when this would be needed. Google drive and Yandex both supports the rclone about command, mergerfs worked with them perfectly. Adding rclone about Box: support would solve my problem.

**Comment by animosity22** [comment]
That's already done in:

https://github.com/rclone/rclone/issues/4264

You need to update rclone.
