### ISSUE TITLE
All size informations "0" by webdav backend

### ISSUE THREAD

**Issue by ambipur76** [rclone/rclone#4348]
#### What is the problem you are having with rclone?

All size informations I got from rclone webdav backend is now "0", by rclone 1.51.0 the reported space "Available" was 1P (petabyte). From these two possibilities the 1P was better because the "0" prevents writing anything. Can you confirm that this has been change since version 1.51.0 by any reason?

#### What is your rclone version (output from `rclone version`)

1.52.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian 10 32 bit

####  Which cloud storage system are you using? (eg Google Drive)

4shared.com and T-Online Mediencenter, both via rclone's webdav backend

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

df -h -T /srv/backup/t-online.de /srv/backup/4shared.com
Filesystem     Type         Size  Used Avail Use% Mounted on
T-Online:      fuse.rclone     0     0     0    - /srv/backup/t-online.de
4shared:       fuse.rclone     0     0     0    - /srv/backup/4shared.com

**Comment by ncw** [comment]
This code did change, yes

Can you post the result of `rclone about remote:` with 1.52.1 and v1.51.0 please?

Thanks

**Comment by ambipur76** [comment]
:~# rclone version
rclone v1.52.1
- os/arch: linux/386
- go version: go1.14.4

:~# rclone about T-Online:
Total:   0
Used:    0
Free:    0

:~# rclone about 4shared:
Total:   0
Used:    0
Free:    0

Ina  few minutes I uninstall rclone version 1.52.1 and check the output of the requested command with rclone version 1.51.0 .

**Comment by ambipur76** [comment]
:~# rclone version
rclone v1.51.0
- os/arch: linux/386
- go version: go1.13.7

:~# rclone about T-Online:
NO OUTPUT, GIVES BACK THE PROMPT - strange

:~# rclone about Box:
2020/06/14 11:04:24 Failed to about: box root '' doesn't support about

Indeed, with df -h -T I get:
:~# df -h -T /srv/backup/t-online.de /srv/backup/box.com
Filesystem     Type         Size  Used Avail Use% Mounted on
T-Online:      fuse.rclone  1.0P     0  1.0P   0% /srv/backup/t-online.de
Box:           fuse.rclone  1.0P     0  1.0P   0% /srv/backup/box.com

**Comment by ambipur76** [comment]
Sorry, I have missed this:
:~# rclone about 4shared:
NO OUTPUT, GIVES BACK THE PROMPT - strange again.

**Comment by ncw** [comment]
Can you do this with rclone 1.52.1 and post the result please?

    rclone about T-Online: -vv --dump bodies

That will show exactly what T-Online is returning to make rclone think it has 0 Total, Free and Used!

**Comment by ambipur76** [comment]
I have run it, here is the debug info:
:~# rclone about T-Online: -vv --dump bodies
2020/06/14 12:23:59 DEBUG : rclone: Version "v1.52.1" starting with parameters ["rclone" "about" "T-Online:" "-vv" "--dump" "bodies"]
2020/06/14 12:23:59 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2020/06/14 12:23:59 DEBUG : You have specified to dump information. Please be noted that the Accept-Encoding as shown may not be correct in the request and the response may not show Content-Encoding if the go standard libraries auto gzip encoding was in effect. In this case the body of the request will be gunzipped before showing it.
2020/06/14 12:23:59 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/06/14 12:23:59 DEBUG : HTTP REQUEST (req 0xc498380)
2020/06/14 12:23:59 DEBUG : PROPFIND / HTTP/1.1
Host: webdav.magentacloud.de
User-Agent: rclone/v1.52.1
Content-Length: 139
Authorization: XXXX
Depth: 0
Referer: https://webdav.magentacloud.de/
Accept-Encoding: gzip

<?xml version="1.0" ?>
<D:propfind xmlns:D="DAV:">
 <D:prop>
  <D:quota-available-bytes/>
  <D:quota-used-bytes/>
 </D:prop>
</D:propfind>
2020/06/14 12:23:59 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/06/14 12:23:59 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/06/14 12:23:59 DEBUG : HTTP RESPONSE (req 0xc498380)
2020/06/14 12:23:59 DEBUG : HTTP/1.1 207 Multi-Status
Content-Length: 307
Content-Type: text/xml; charset="utf-8"
Date: Sun, 14 Jun 2020 10:23:59 GMT
Ms-Author-Via: DAV
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains

<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:" xmlns:ns0="DAV:">
<D:response xmlns:g0="DAV:">
<D:href>/</D:href>
<D:propstat>
<D:prop>
<g0:quota-available-bytes/>
<g0:quota-used-bytes/>
</D:prop>
<D:status>HTTP/1.1 404 Not Found</D:status>
</D:propstat>
</D:response>
</D:multistatus>
2020/06/14 12:23:59 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Total:   0
Used:    0
Free:    0
2020/06/14 12:23:59 DEBUG : 4 go routines active

**Comment by ncw** [comment]
Ah, it looks like we asked for the quota and it wasn't available so we treated it as 0 rather than unavailable...

The provider returned this which made rclone think the property was there

```xml
<g0:quota-available-bytes/>
<g0:quota-used-bytes/>
```

Can you try this fix to see if it works?

It should revert to printing nothing on `rclone about` hopefully!

https://beta.rclone.org/branch/v1.52.1-067-g6ccbf354-fix-4348-webdav-about-beta/ (uploaded in 15-30 mins)

**Comment by ambipur76** [comment]
I have seen there packages for many operating systems, but a linux version is unfortunately missing. Could you compile one for linux 386?

**Comment by ambipur76** [comment]
I had no other chance to test it except the Windows version (rclone-v1.52.1-067-g6ccbf354-fix-4348-webdav-about-beta-windows-amd64.zip). After getting and installing WinFSP I managed to mount my drive at T-Online:
>rclone mount T-Online: T:
The service rclone has been started.

In Windows Explorer I have seen all data copied formerly on Debian to the cloud storage. I have started another command prompt window to check the about command:
>rclone about T-Online:
Total:   0
Used:    0
Free:    0

>rclone version
rclone v1.52.1-067-g6ccbf354-fix-4348-webdav-about-beta
- os/arch: windows/amd64
- go version: go1.14.4
So this is bad news, the patch does not seem to work, unfortunately. Can you check the code again, please?

**Comment by ncw** [comment]
Thanks for testing and sorry about having to use the Windows build. The CI failed to make all the builds.

Here is a second attempt - I think this should work :crossed_fingers: 

https://beta.rclone.org/branch/v1.52.1-073-g20a3530c-fix-4348-webdav-about-beta/ (uploaded in 15-30 mins)

**Comment by ambipur76** [comment]
Hello! I have successfully finished with testing of rclone-v1.52.1-073-g20a3530c-fix-4348-webdav-about-beta-linux-386.deb . Everything works as expected. By my two webdav storages, T-Online and 4shared the rclone about command now gives back the prompt as by former versions. The output of the "df -hT" command for total and available spaces gives back 1P (1 petabyte) as before. All my 6 mounted cloud storages look like before. Thank you and the rclone team the support and the great program!

**Comment by ncw** [comment]
Thanks for testing :-)

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52.2
