### ISSUE TITLE
Bring back old elapsed time behavior

### ISSUE THREAD

**Issue by Dibbyo456** [rclone/rclone#4366]
In rclone **v1.50.2** (could be wrong) the elapsed time behavior has changed. According to nick on [#3860](https://github.com/rclone/rclone/issues/3860#issuecomment-572502504) 

> What `Elapsed time` means now is time that files are copying for and since you haven't copied any files yet that is why it is nearly zero. We made it like that so we could compute average transfer rates properly.

I asked about it on forum and [he wanted to bring back old behavior](https://forum.rclone.org/t/elapsed-time-stays-0-until-transfers-starts/15201/2?u=harry). According to him:

> The time displaying as elapsed time should really be called Transfer time - it is used to calculate the MB/s rates. I'd like to bring back elapsed time as it was!

Why not both Elapsed time & Transfer time! 😗

**Comment by ncw** [comment]
Yes, let's do this!

So relabel `Elapsed time` to `Transfer time` and don't show if it is zero

Re-implement elapsed time.

Want to have a go at this @Dibbyo456 ?

**Comment by Dibbyo456** [comment]
Fixed by: #4448

**Comment by ncw** [comment]
Oops we forgot to link the change - thanks @Dibbyo456 for pointing that out.

I've merged this to master now which means it is in [the latest beta](https://beta.rclone.org) and released in v1.53 - thanks @negative0
