### ISSUE TITLE
Rc: not found cache/stats, cache/fetch and cache/expire

### ISSUE THREAD

**Issue by ElonH** [rclone/rclone#4368]
#### What is your rclone version (output from `rclone version`)

rclone v1.52.1
- os/arch: linux/amd64
- go version: go1.14.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

ubuntu 18.06 (64 bit)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

download latest release version `wget https://github.com/rclone/rclone/releases/download/v1.52.1/rclone-v1.52.1-linux-amd64.zip`, and unzip that.

`./rclone rcd`, then
`./rclone rc cache/stats`
return
```json
{
	"error": "couldn't find method \"cache/stats\"",
	"input": {},
	"path": "cache/stats",
	"status": 404
}
```

And try to run `./rclone rc > cmd.md`, and I can't found any `cache` command in the document.

**Comment by ElonH** [comment]
I found the crux, `rc.Add` are put in `NewFs`
https://github.com/rclone/rclone/blob/3efdf5e0952950dbc1312506cb7da297ba21f9be/backend/cache/cache.go#L341-L603

**Comment by animosity22** [comment]
For cache stats to return, you need to run the a cache mount as it returns cache stats.

```
felix@gemini:~$ rclone mount cachecrypt: /home/felix/test --rc --rc-addr :5573 --rc-user felix --rc-pass felix
2020/06/18 06:35:20 NOTICE: Serving remote control on http://[::]:5573/
```
and

```
felix@gemini:~$ rclone rc cache/stats --rc-addr 127.0.0.1:5573 --rc-user felix --rc-pass felix
{
	"stats": {
		"data": {
			"newest-file": "test/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv",
			"newest-ts": "2020-05-01T13:06:04.585417733-04:00",
			"oldest-file": "crypt/smu5ej34ujbdoip1cm3mlk92q4/1tapkqt45hmif5o0165msejmk8/76rio3k1luffje8ii2j9oqv6095ove3pqlbfnhaq8v41fp9jtu7g",
			"oldest-ts": "2020-05-01T12:52:13.938533621-04:00",
			"total-chunks": 6,
			"total-size": 201326592
		},
		"files": {
			"newest-name": "",
			"newest-ts": "2020-06-18T06:35:32.231789128-04:00",
			"oldest-name": "",
			"oldest-ts": "2020-06-18T06:35:32.23178889-04:00",
			"total-dir": 4,
			"total-files": 11
		}
	},
	"status": "ok"
}
```

Trying to run cache stats on something that doesn't run cache properly does a 404

```
felix@gemini:~$ rclone rc cache/stats
2020/06/18 06:36:24 Failed to rc: Failed to read rc response: 404 Not Found: {
	"error": "couldn't find method \"cache/stats\"",
	"input": {},
	"path": "cache/stats",
	"status": 404
}
```
