### ISSUE TITLE
Rclone loses mount

### ISSUE THREAD

**Issue by cristianpanama** [rclone/rclone#4369]
#### What is the problem you are having with rclone?

Rclone loses mount.

#### What is your rclone version (output from `rclone version`)

rclone v1.52.0

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

os/arch: linux/amd64

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

sudo /share/CACHEDEV3_DATA/.qpkg/RClone/rclone mount --log-level INFO --allow-other --allow-non-empty --tpslimit 10 --tpslimit-burst 10 --dir-cache-time=48h --buffer-size=64M --attr-timeout=1s --vfs-read-chunk-size=64M --vfs-read-chunk-size-limit=2G --vfs-cache-max-age=5m --vfs-cache-mode=writes --cache-dir /share/CACHEDEV3_DATA/rclonenas --config=/share/homes/admin/.config/rclone/rclone.conf --user-agent=NAS --cache-workers 8 nasdrive: /share/homes/admin/Nasdrive &

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Hello good afternoon, my regards. I wanted to please ask for help with a unit disassembly problem, just like the other colleagues in the group. I have a qnap NAS where I have installed the rclone app from the unofficial repository, everything working perfectly until a week ago the units were disassembled.

The log file you only have these lines written to me: 2020/06/18 01:40:48 INFO: Starting HTTP transaction limiter: max 10 transactions / s with burst 10
2020/06/18 01:40:50 mount helper error: fusermount: failed to access mountpoint / share / CACHEDEV3_DATA / homes / admin / Nasdrive: Transport endpoint is not connected
2020/06/18 01:40:50 Fatal error: failed to mount FUSE fs: fusermount: exit status 1.

The command I use to mount the drives is: sudo /share/CACHEDEV3_DATA/.qpkg/RClone/rclone mount --log-level INFO --allow-other --allow-non-empty --tpslimit-burst 10 --dir-cache-time = 48h --buffer-size = 64M --attr-timeout = 1s --vfs-read-chunk-size = 64M --vfs-read-chunk-size-limit = 2G - vfs-cache-max-age = 5m --vfs-cache-mode = writes --cache-dir / share / CACHEDEV3_DATA / rclonenas --config = / share / homes / admin / .config / rclone / rclone.conf - user-agent = NAS --cache-workers 8 nasdrive: / share / homes / admin / Nasdrive &.

Any help you can give me to solve this error, or what other way do I have to mount the units since I am using this tutorial to mount the units, inside the RClone.sh in the start and stop lines, to mount and unmount after every restart.

This would be the tutorial that I use but not the mount command, since it did not work for me: https://www.forocoches.com/foro/showthread.php?t=7314691

**Comment by animosity22** [comment]
Please post use questions on the forums.

https://forum.rclone.org
