### ISSUE TITLE
Rclone storage type chunker (32) generates onedrive versions wasting 50% space

### ISSUE THREAD

**Issue by tecepeipe** [rclone/rclone#4372]
Using current version of rclone (1.40-1.50) I noticed that all my onedrive 5TB were full after filling with 2.5TB (with copy/sync). After a lot of googling and frustation I found evidences that eache chunk file was being saved twice as version history.

This might be affecting other storage types, but I'm not sure. For sure this is an issue on Onedrive.
![Capture](https://user-images.githubusercontent.com/420106/85114265-dea83880-b26c-11ea-891e-ba77e8fc8c76.PNG)

**Comment by buengese** [comment]
One issue is enough
