### ISSUE TITLE
rclone chunker is generating versions of files in OneDrive wasting 50% of space

### ISSUE THREAD

**Issue by tecepeipe** [rclone/rclone#4374]
Using current version of rclone (1.40-1.50) I noticed that all my onedrive 5TB were full after filling with 2.5TB (with copy/sync) ONLY if using the chunker to split large files. 
After a lot of googling and frustation I found evidences that each chunk file was being saved twice as version history.

This might be affecting other storage types, but I'm not sure. For sure this is an issue on Onedrive.

**Comment by buengese** [comment]
On issue is enough
