### ISSUE TITLE
Lock sqlite database before making copy

### ISSUE THREAD

**Issue by Derkades** [rclone/rclone#4377]
#### What problem are you are trying to solve?
When using rclone to sync application data containing sqlite database files, I often run into issues because of the file changing while rclone is reading it. I'd like to avoid shutting down applications if possible.

#### How do you think rclone should be changed to solve that?
Rclone can use the sqlite API to temporarily lock database files during upload (when a command line flag is present).

I realise this is probably out of scope, feel free to close the issue if it is.

**Comment by animosity22** [comment]
There's nothing rclone would do for this as you'd need to make a copy if you are going to try to make a backup.

Feel free to post on the forums https://forum.rclone.org if you'd like to ask for suggestions as you didn't mention OS or any other details. 

In general, it's best to use backup software if your goal is to backup.

I am closing this out as it isn't an issue.
