### ISSUE TITLE
slow remote mount over samba share

### ISSUE THREAD

**Issue by chchia** [rclone/rclone#4378]
#### What is the problem you are having with rclone?
When i mount the gdrive in ubuntu, i am having below problem:
1. copy file within ubuntu from remote mounted gdrive folder to local disk inside ubuntu i get 50MB/s (i have a 500m/500m fiber), this is working perfectly.
![image](https://user-images.githubusercontent.com/1291771/85258660-7048bd80-b49a-11ea-8e80-e4cc96a14fe5.png)

2. ***i share the remote mounted gdrive folder over samba, and access from Windows 10, i can browse the file, but when i want to copy the file over samba to windows 10, i get speed 2~3MB/s. which is some thing wrong.***
![image](https://user-images.githubusercontent.com/1291771/85258854-b43bc280-b49a-11ea-9611-f39e41b388e0.png)

3. i create another samba share which not pointing to remote mount, and copy file from windows 10, i get 80~90 MB/s, which is normal. 
![image](https://user-images.githubusercontent.com/1291771/85259001-e3523400-b49a-11ea-82dd-87f377c94f8e.png)

#### What is your rclone version (output from `rclone version`)
any version, stable or beta.

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
ubuntu 20.04 lts 64 bits
windows 10 64 bits

####  Which cloud storage system are you using? (eg Google Drive)
google drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)  

```
mounting remote gdrive with these command:
--fast-list --allow-other --transfers=10 --checkers=10 --buffer-size 64M --tpslimit=10 --default-permissions --copy-links --no-gzip-encoding --no-check-certificate --vfs-cache-mode writes --drive-chunk-size 32M --vfs-read-chunk-size 4M --vfs-read-chunk-size-limit 512M --vfs-read-wait 60ms
```

sorry no log file, because it is working but just with slow speed with samba share over mount.

i had tryied to play around with samba with option like tcp_nodelay etc but doesnt seems to help, can any one advise me what could be the solutions? thank you.

**Comment by animosity22** [comment]
For use questions, if you could please use the forums and we find something that is a bug or a feature request, we can certainly add it.

https://forum.rclone.org

I do see your post on the forums already and I replied there so I'm closing this out.
