### ISSUE TITLE
1Fichier : Failed to copy: couldn't finish file upload: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by TuxMiki** [rclone/rclone#4382]
#### What is the problem you are having with rclone?
Sync with latest version of rclone (stable or beta) is failing for 1Fichier Cloud.
Only new files to be uploaded are concerned and cannot be uploaded, files checks and account access are ok.
Was working with latest beta of 1.49 one month ago so I am not so sure if it's due to rclone upgrade or some cloud provider modification during this time
Tried with other remote folder on same provider, same error.

#### What is your rclone version (output from `rclone version`)
rclone v1.52.1-107-g6768f999-beta
- os/arch: linux/amd64
- go version: go1.14.4
Same result for latest stable version (v1.52.1)

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 20.04 LTS 64 bits

####  Which cloud storage system are you using? (eg Google Drive)
1Fichier

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync /XXX/YYY 1fichier_Documents: --progress

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
ERROR : Informatique/Windows/ccsetup567.exe: Failed to copy: couldn't finish file upload: invalid character '<' looking for beginning of value
ERROR : Informatique/Windows/npp.7.8.7.Installer.x64.exe: Failed to copy: couldn't finish file upload: invalid character '<' looking for beginning of value
ERROR : Informatique/Windows/TreeSizeFreeSetup.exe: Failed to copy: couldn't finish file upload: invalid character '<' looking for beginning of value
Transferred:      304.457M / 359.101 MBytes, 85%, 7.736 MBytes/s, ETA 7s
Errors:                 4 (retrying may help)
Checks:                90 / 90, 100%
Transferred:            0 / 2, 0%
Elapsed time:        39.3s

**Comment by buengese** [comment]
hmm i wasn't able to reproduce this. are you sure this happens with the latest version?

**Comment by TuxMiki** [comment]
Hello,
So without changing anything it's working tonight !
I did the try last night quite late so it's not impossible that there were some maintenance done on 1Fichier side.
Anyway, sorry for bothering you and thank you for this great piece of software, I close this (non) bug !

**Comment by ncw** [comment]
> So without changing anything it's working tonight !

Errors with `<` in are likely rclone trying to decode an HTML error page as JSON so I'd agree with you.

**Comment by jcn50** [comment]
I just had the same issue, and it is because the COLD STORAGE on 1FICHIER is OVERQUOTA! You need to free up some space and wait for the 24h cold storage update stats to run~
