### ISSUE TITLE
FTPs FileZilla Require TLS session resumption

### ISSUE THREAD

**Issue by petedressler** [rclone/rclone#4388]
#### Output of `rclone version`
rclone v1.49.5

#### Describe the issue
If FileZilla is set to Require TLS session resumption on the FTP over TLS Settings tab, rclone connections but returns no data. Turning off this setting in FileZilla allows rclone to work as it should with the remote. rclone also returns no error, the error that led towards this was in the FileZilla logs.

src: https://forum.filezilla-project.org/viewtopic.php?t=36903

**Comment by animosity22** [comment]
You have an old version, please upgrade, test out the new version and make a post on the forums. If we find a bug or issue, we can open up something here.

https://forum.rclone.org

**Comment by ncw** [comment]
Please retest with 1.52.2 and if it is still a problem then we'll reopen the issue - thanks :-)
