### ISSUE TITLE
Need wildcard on copy/move

### ISSUE THREAD

**Issue by EnziinSystem** [rclone/rclone#4389]
At now, rclone can not copy or move with wildcard files. We still copy the single file at a time.

I want to copy all files in wildcard, ex:

`rclone copy *.sh dest`

thanks.

**Comment by animosity22** [comment]
Please ask use questions on the forums and we can help out.

You'd use a filter to handle that situation:

https://rclone.org/filtering/

You'd use rclone copy /source /dest --include *.sh

https://forum.rclone.org
