### ISSUE TITLE
Display names / description field for remotes.

### ISSUE THREAD

**Issue by jtagcat** [rclone/rclone#4391]
#### What problem are you are trying to solve?
 - Have many, many remotes, with easy to type, cryptic names
 - You don't exactly remember, what all the remotes do
 - So you name everything with 30 various characters
 - but I think that's too much to type, and copy pasta isn't the fastest

#### How do you think rclone should be changed to solve that?
What about 'display names'? They would only appear in rclone config and listremotes (with optional flag, bc lsremotes could be used by scripts). Other alternative for display names could be a description field.

**Comment by ncw** [comment]
This is a nice idea - I like the name `description`

To implement we probably need to ask the user for the description at the point they make the remote.

Do you want to have a go at this?

**Comment by jtagcat** [comment]
> This is a nice idea - I like the name `description`
> 
> To implement we probably need to ask the user for the description at the point they make the remote.

I think it should be shoved under advanced (the last thing before confirming). Thoughs/do you agree?

> Do you want to have a go at this?

Suuureee.. I'll assign myself, but as with the previous time, can't promise anything.

**Comment by jtagcat** [comment]
@ncw:
> I think it should be shoved under advanced (the last thing before confirming). Thoughs/do you agree?

_digging through the backlog_ I might throw this under hacktoberfest.

Talking about backlog, I did some ~stonks~ stats. Tab count (backlog, net total compared to the previous hour online) (around ¼-⅓ of the actual measure):

![image](https://user-images.githubusercontent.com/38327267/95528968-352ab580-09c9-11eb-9dc4-569585029c6d.png)

**Comment by ncw** [comment]
@jtagcat wrote
>  I might throw this under hacktoberfest.
Go for it!

> Talking about backlog, I did some stats. Tab count (backlog, net total compared to the previous hour online) (around ¼-⅓ of the actual measure):

Nice stats! I don't know what they are measuring - can you explain more?

**Comment by jtagcat** [comment]
I made a wiki page on STG explaining it, but they disabled the wiki... I use SimpleTabGroups for my tabs, the numbers indicate tabs. I guess this could go in more detail:
![Screenshot from 2020-10-10 09-45-46](https://user-images.githubusercontent.com/38327267/95648101-4d332f80-0ac4-11eb-8967-9547f497b910.png)
![Screenshot from 2020-10-10 09-45-58](https://user-images.githubusercontent.com/38327267/95648098-4c020280-0ac4-11eb-9d92-dc6ccf6c6d91.png)

**Comment by jtagcat** [comment]
..I still didn't get the answer to: `I think it should be shoved under advanced (the last thing before confirming). Thoughs/do you agree?`

**Comment by Paul-Stern** [comment]
Hello everyone! My name is Paul and I am just starting my GitHub activity. I'm looking for my first issues to fix and found this one as it is labeled as 'good first' one. Is there anybody assigned to it now? If not, can I be assigned for it and try to fix it, providing it is suitable for beginners?

**Comment by jtagcat** [comment]
There is nobody assigned, and it's probably suitable.

I would start by looking at stuff interacting with configs. Description (I assume) is only shown in commands interacting purely with config, and not elsewhere. Look at how the config is created (can be through cli commands or interactively exists) and reading/showing the field (`$ rclone config` without doing anything). There is most likely a generic remote configuration holder. (the key-value what holds remote name, etc; non-generic: (sftp) host, (sftp) username)

Make sure you have a command to set-get the description programatically. If you have the time, maybe add an option to `$ rclone listremotes` to also print descriptions.

When stuck, I think you can ping ncw, who helped me out, including some of my first Go steps. Check README if they are still the person to ask help from.

**Comment by jtagcat** [comment]
Definitely have a look at https://github.com/rclone/rclone/pull/6019, as it is probably usable with very few minor changes.

**Comment by Paul-Stern** [comment]
Thank you so much for your feedback! I guess, I will be able to start working on it soon.
