### ISSUE TITLE
rclone process does not proceed for more than 4 minutes with --no-traverse copy --files-from-raw files_from

### ISSUE THREAD

**Issue by public-tatsuya-noyori** [rclone/rclone#4397]
rclone process does not proceed for more than 4 minutes as follows:

rclone --stats 0 --log-level DEBUG --no-traverse copy --files-from-raw files_from_raw.txt remote_s3_compatible_site:bucket local_directory
2020/06/30 07:17:44 DEBUG : Using config file from "/home/hogehoge/.config/rclone/rclone.conf"
2020/06/30 07:17:44 DEBUG : Using v2 auth
#### rclone process does not proceed for more than 4 minutes ####
2020/06/30 07:21:51 DEBUG : Local file system at /local_directory: Waiting for checks to finish
2020/06/30 07:21:51 DEBUG : Local file system at /local_directory: Waiting for transfers to finish
2020/06/30 07:21:52 DEBUG : preAllocate: got error on fallocate, trying combination 1/2: operation not supported
2020/06/30 07:21:52 DEBUG : preAllocate: got error on fallocate, trying combination 2/2: operation not supported
2020/06/30 07:21:52 INFO  : remote_file_1: Copied (new)

It would be appreciated if you could find something.

**Comment by animosity22** [comment]
Super awesome if you can post use questions on the forums.

https://forum.rclone.org

You can use the Help and Support Template as that has the information you need to populate.

Thanks!
