### ISSUE TITLE
[Question]The reason why Object and Fs structs have unexported fields in backends?

### ISSUE THREAD

**Issue by Cinerar** [rclone/rclone#4401]
Hello, i try to build my app on top of beautiful structured system of Fs an Objects on different backends, but unfortunatelly i'm limited to public functions as long as all fields of this structures are private.  
For example i have no option to transfer Objects as structs over network serialized with gob to put in some queue, as long as gob needs exported fields to serialize the struct.

The question is, does Fs and Objects really need to have private fields?

**Comment by ncw** [comment]
> The question is, does Fs and Objects really need to have private fields?

I think the fields need to stay private so the backends can change their implementations as they want.

However I do plan to implement JSON marshalling and unmarshalling on Objects soon - would that be useful?

You can't serialize an Fs it has too much stuff that needs to be re-created, but the remote name should be all you need.

**Comment by Cinerar** [comment]
I believe JSON marshalling and unmarshalling of Objects could be useful, but for me it looks like quite complicated as long as different implementations have different fields, so it wouldn't be easy to unmarshal them in standartized way.  Gob marshaling and unmarshaling for my case looks better, it would be easy to get the concrete implementation of Object (it should be registred with gob.Register),  but afaik it is limited to golang.
As example suggest you need to pass array of Objects from different implementations.

About Fs - you are right, remote name is enough.
Thanks for your time and fantastic software!

**Comment by ncw** [comment]
> I believe JSON marshalling and unmarshalling of Objects could be useful, but for me it looks like quite complicated as long as different implementations have different fields, so it wouldn't be easy to unmarshal them in standartized way.

Actually my plan was to make the marshalling look as near as we can to the output of `rclone lsjson`. Some backends will need to add a little more stuff, but it should be pretty much standardized for all the Object types.





> Gob marshaling and unmarshaling for my case looks better, it would be easy to get the concrete implementation of Object (it should be registred with gob.Register), but as a minus afaik it is limited to golang.

I'm not that familar with Gob marshalling - does having a JSON encoder/decoder help here?



> Thanks for your time and fantastic software!

You are welcome!

**Comment by Cinerar** [comment]
Finished my task with a kind of wraper around Object with basic fields, so this issue is not actual anymore, closing it.
