### ISSUE TITLE
Add a "hint-file-size" option to rcat to allow "streaming" transfers to cloud hostings which doesn't allow it directly

### ISSUE THREAD

**Issue by Evengard** [rclone/rclone#4403]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.52.2
- os/arch: linux/amd64
- go version: go1.14.4

#### What problem are you are trying to solve?
I need to transfer a HUGE... Nope, not a file. A block device image. 2 TB in size - to a remote storage which *does not support* streaming uploads.

The obvious solution is using someting like `cat /dev/sdb | rclone rcat`, but...

The problem is that it does attempt create a "spool file", except that this will end up in a failure because, well, fitting a 2 TB file on a filesystem which can never be that big is impossible, and I can't add another 4 TB drive just for the sake of backing it up. And anyway how will I then back up this 4 TB drive?...

#### How do you think rclone should be changed to solve that?
Add to "rcat" command an option "hint-file-size", which would allow to preallocate the file in advance at the remote end and then just actually stream it via standard chunked transfer mechanics (with maybe using a limited-sized cache file, but definitely not copying the whole file in the cache before actually transferring anything).

**Comment by ncw** [comment]
Internally rclone has two commands Rcat and RcatSize for exactly this purpose.

We could add a `--size` flag to `rclone rcat` which will then use `RcatSize` for upload which won't require streaming to disk.

The naive implementation would then stream as much data as you gave it which means it would likely fail if you sent more or less data than `--size`.

Is that acceptable? If so then this is a pretty easy fix

This line needs to change to `RcatSize` setting the size to `-1` if the --size flag isn't passed.

https://github.com/rclone/rclone/blob/4f7f5404cea5211c69114ffcd79931edf44b6b99/cmd/rcat/rcat.go#L54

Fancy having a go at this @Evengard ?

**Comment by Evengard** [comment]
Actually, this seems to be exactly what I need. I'll try to look into this, thanks!

**Comment by ncw** [comment]
Let me know if you need help!

**Comment by ncw** [comment]
Did you have a chance to have a go at this @Evengard ?

**Comment by Evengard** [comment]
Hello!
Unfortunately no, I worked it around with splitting the original into smaller files and uploading each file separately.
