### ISSUE TITLE
Password Creation

### ISSUE THREAD

**Issue by purpleden** [rclone/rclone#4405]
It will be great, that instead of password creation within rclone, that we can also paste a password in, along with a value for salt

**Comment by ncw** [comment]
You should be able to paste into the terminal? Doesn't that work?

**Comment by purpleden** [comment]
Unfortunately no, I did try a few times using different methods of pasting (am on a chromebook)

**Comment by ncw** [comment]
I seem to remember that working OK when I used a chromebook (I don't have one at the moment to test). Which terminal application are you using? How are you running rclone?

**Comment by TATUMTOT** [comment]
When you past in the terminal is just stays blank but the past is there. I think. just hit enter and go to the next section. then view the config and see if there is a value.

**Comment by ncw** [comment]
> When you past in the terminal is just stays blank but the past is there.

Rclone doesn't echo the input when you are typing passwords

```
Password or pass phrase for encryption.
y) Yes type in my own password
g) Generate random password
y/g> y
Enter the password:
password:
Confirm the password:
password:
```

So that is normal I think.

**Comment by animosity22** [comment]
Looks to be answered.

If you still have a question, you can ask on the forums:

https://forum.rclone.org
