### ISSUE TITLE
Google Drive browser auth error: "The server cannot process the request because it is malformed"

### ISSUE THREAD

**Issue by infokiller** [rclone/rclone#4407]
#### What is the problem you are having with rclone?

After running `rclone config create gdrive drive` and choosing an account, I get errors:

![image](https://user-images.githubusercontent.com/10516814/86511026-ec79c400-bdfd-11ea-813e-6e4cee282804.png)

![image](https://user-images.githubusercontent.com/10516814/86511028-edaaf100-bdfd-11ea-86da-a0509ea9ee4a.png)

#### What is your rclone version (output from `rclone version`)

rclone v1.52.2
- os/arch: linux/amd64
- go version: go1.14.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux 5.6.19.a-1-hardened

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone config create gdrive drive`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2020/07/04 13:56:19 DEBUG : rclone: Version "v1.52.2" starting with parameters ["rclone" "-vv" "config" "create" "gdrive" "drive"]
2020/07/04 13:56:19 NOTICE: Config file "/home/user/.config/rclone/rclone.conf" not found - using defaults
Remote config
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
Auto confirm is set: answering Yes, override by setting config parameter config_is_local=false
2020/07/04 13:56:19 DEBUG : Starting auth server on 127.0.0.1:53682
If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth?state=RPDLiOqHx1BrQKp560XGCw
Log in and authorize rclone for access
Waiting for code...
```

**Comment by infokiller** [comment]
Thanks for the quick response!
Turns out it didn't work because of Privacy Badger, apologies for the noise.

**Comment by ncw** [comment]
> Turns out it didn't work because of Privacy Badger, apologies for the noise.

No worries!
