### ISSUE TITLE
failed to resolve shortcut

### ISSUE THREAD

**Issue by raenoll** [rclone/rclone#4408]
#### What is the problem you are having with rclone?

input/output error when ls a directory

#### What is your rclone version (output from `rclone version`)

1.52.2

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian 10

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

ls

#### A log from rlcone.log

ERROR : Video/: Dir.Stat error: list: failed to resolve shortcut: googleapi: Error 404: File not found: 1vEixxxxxxxxxxxxxx., notFound

I rolled back to 1.51.0, this problem was solved.

**Comment by raenoll** [comment]
I removed some invalid shortcuts in this directory, and this problem is solved.

**Comment by ncw** [comment]
This problem is fixed in in the beta and will go in a point release shortly!
