### ISSUE TITLE
Question: How to configure rclone for backing up local directories to different google drive accounts?

### ISSUE THREAD

**Issue by 0-0eth0** [rclone/rclone#4409]
Hello Devs,
Thanks for this great project,
if possible can you please help me by answering my question?

Suppose, i have 2 folder named in my centos local i.e 1. Backup1 2. Backup2

I want them to copy on different google drive accounts, how can i do that? i have tried it by creating to different configs but it isn't working, i want them to be copied on different drives 
Backup1 in foo@bar.com'2 drive & 
Backup2 in foo2@bar2.com's drive

Thanks for the help in advance.

**Comment by 0-0eth0** [comment]
i figured it out

**Comment by ncw** [comment]
Great! Questions are best on [the rclone forum](https://forum.rclone.org/) - you'll get a speedier answer there.
