### ISSUE TITLE
verbose max level

### ISSUE THREAD

**Issue by mtnjustme** [rclone/rclone#4410]
Hello there, about the --verbose flag, normally i'd use "--verbose=x" where x is the verbose level, however, no where in the whole github and site i could find the max level of the verbose, so my question is, what is the max level of verbose?

**Comment by ncw** [comment]
The max level is 2 which is -vv

You can dump more stuff on this level with the --dump flag.

**Comment by mtnjustme** [comment]
> 
> 
> The max level is 2 which is -vv
> 
> You can dump more stuff on this level with the --dump flag.

can i use dump on the first level or no verbose at all?

**Comment by ncw** [comment]
If you want to use --dump then you will need -vv as the dump messages are output at DEBUG level.

See
- https://rclone.org/docs/#logging
- https://rclone.org/docs/#dump-flag-flag-flag

**Comment by mtnjustme** [comment]
> 
> 
> If you want to use --dump then you will need -vv as the dump messages are output at DEBUG level.
> 
> See
> 
>     * https://rclone.org/docs/#logging
> 
>     * https://rclone.org/docs/#dump-flag-flag-flag

alright, that answers all the new questions i've got to have, i guess you can close this.
thank you very much for your explanations and your time spent on answering my questions, i appreciate it a lot!

**Comment by ncw** [comment]
No probs! Questions to [the rclone forum](https://forum.rclone.org/) is prefered for next time :-)

Happy rcloning!
