### ISSUE TITLE
rclone chunker - not assembling files

### ISSUE THREAD

**Issue by akkitech** [rclone/rclone#4414]
#### What is the problem you are having with rclone?
rclone chunker is not assembling files after downloading. In docs it says `"The chunker overlay transparently splits large files into smaller chunks during upload to wrapped remote and transparently assembles them back when the file is downloaded. This allows to effectively overcome size limits imposed by storage providers."`

#### What is your rclone version (output from `rclone version`)
v1.52.2

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
WebDav Server

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone sync -v -P --bwlimit=256 --chunker-chunk-size=5M  dav_profile:\<user>\filename.txt local_chunk:\`

filename.txt file size => 19 MB

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

2020/07/07 20:38:15 INFO  : Starting bandwidth limiter at 256kBytes/s
2020-07-07 20:39:32 INFO  : filename.txt.rclone_chunk.001_3z6a2f: Moved (server side)
2020-07-07 20:39:32 INFO  : filename.txt.rclone_chunk.002_3z6a2f: Moved (server side)
2020-07-07 20:39:32 INFO  : filename.txt.rclone_chunk.003_3z6a2f: Moved (server side)
2020-07-07 20:39:32 INFO  : filename.txt.rclone_chunk.004_3z6a2f: Moved (server side)
2020-07-07 20:39:32 INFO  : filename.txt: Copied (new)
Transferred:       19.108M / 19.108 MBytes, 100%, 255.447 kBytes/s, ETA 0s
Checks:                 4 / 4, 100%
Renamed:                4
Transferred:            1 / 1, 100%
Elapsed time:      1m16.5s
2020/07/07 20:39:32 INFO  :
Transferred:       19.108M / 19.108 MBytes, 100%, 255.447 kBytes/s, ETA 0s
Checks:                 4 / 4, 100%
Renamed:                4
Transferred:            1 / 1, 100%
Elapsed time:      1m16.5s

**Comment by ncw** [comment]
It looks like chunker is working from the log.

Can you explain the problem you are having a bit more? Can you paste the rclone command and its output for the problem?

**Comment by akkitech** [comment]
Hi Nick, my problem is that after downloading a file from remote to local using chunker, rclone is not assembling / merging back the file chunks into single original file. Please see the below screenshot for the reference. 

![image](https://user-images.githubusercontent.com/11798883/87033533-02bfbf80-c204-11ea-8d56-e445954a31eb.png)

Or is that something which we need to take care of merging back these chunks into single file using our own service if rclone is not supposed to do this?

**Comment by ncw** [comment]
Did you copy from the chunker remote? Or the underlying remote?

Can you paste your config file with secrets and tokens XXXed out and I'll explain further if that isn't enough help.

**Comment by ivandeex** [comment]
@akkitech 
Could you please provide more information and paste here your rclone.conf (with secrets redacted).
Thanks.

**Comment by animosity22** [comment]
@akkitech  - anything you want to add here or we can close it out as it's getting stale :)

**Comment by ivandeex** [comment]
Closed due to lack of user interest
