### ISSUE TITLE
Python Wrapper - Failed to Copy: Object Not Found

### ISSUE THREAD

**Issue by opsoyo** [rclone/rclone#4416]
#### What is the problem you are having with rclone?

This is going to sound very niche, but I want to provide feedback in case anyone else come across this issue or finds it helpful in other issues.

I've been building a Python wrapper script that integrates with rclone over `rc` and initiates rclone through the `subprocess` module in Python. My issues exclusively happen inside this Python wrapper script, but *only* happen for certain recent versions of rclone. You can see my slow use of GitHub here: https://github.com/opsoyo/autorclone

When moving a directory of files/dirs, version 1.52.2 stable and 1.52.2-208-gbfa57150-beta error out with "failed to copy: object not found". 

When performing the exact same action using 1.51.0, that error does not present itself.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.52.2
- os/arch: linux/amd64
- go version: go1.14.4
```
```
rclone v1.52.2-208-gbfa57150-beta
- os/arch: linux/amd64
- go version: go1.14.4
```
```
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux, 64-bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
move /local/path GDRemote:/PathA/PathB --config /home/user/autorclone/rclone.conf -vv --drive-acknowledge-abuse --rc --rc-addr=localhost:0 --log-file /tmp/rclone.log --drive-service-account-file /path/to/sa.json
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Log from v1.52.2
```
DEBUG : rclone: Version "v1.52.2" starting with parameters ["/home/user/.local/bin/rclone-beta" "move" "/local/path" "GDRemote:/PathA/PathB" "--config" "/home/user/autorclone/rclone.conf" "-vv" "--drive-server-side-across-configs" "--drive-acknowledge-abuse" "--rc" "--rc-addr=localhost:0" "--log-file" "/tmp/rclone.log" "--drive-service-account-file" "/path/to/sa.json"]
NOTICE: Serving remote control on http://127.0.0.1:24637/
DEBUG : Using config file from "/home/user/autorclone/rclone.conf"
...
ERROR : VideoFile1.mp4 : Failed to copy: object not found
ERROR : VideoFile1.mp4: Not deleting source as copy failed: object not found
ERROR : VideoFile2.mp4: Failed to copy: object not found
ERROR : VideoFile2.mp4: Not deleting source as copy failed: object not found
...
```

Log from v1.52.2-208-gbfa57150-beta
```
DEBUG : rclone: Version "v1.52.2-208-gbfa57150-beta" starting with parameters ["/home/user/.local/bin/rclone-beta" "move" "/local/path" "GDRemote:/PathA/PathB" "--config" "/home/user/autorclone/rclone.conf" "-vv" "--drive-server-side-across-configs" "--drive-acknowledge-abuse" "--rc" "--rc-addr=localhost:0" "--log-file" "/tmp/rclone.log" "--drive-service-account-file" "/path/to/sa.json"]
NOTICE: Serving remote control on http://127.0.0.1:24637/
DEBUG : Using config file from "/home/user/autorclone/rclone.conf"
...
ERROR : VideoFile1.mp4 : Failed to copy: object not found
ERROR : VideoFile1.mp4: Not deleting source as copy failed: object not found
ERROR : VideoFile2.mp4: Failed to copy: object not found
ERROR : VideoFile2.mp4: Not deleting source as copy failed: object not found
...
```

Log from v1.51.0
```
DEBUG : rclone: Version "v1.51.0" starting with parameters ["/home/user/.local/bin/rclone-beta" "move" "/local/path" "GDRemote:/PathA/PathB" "--config" "/home/user/autorclone/rclone.conf" "-vv" "--drive-server-side-across-configs" "--drive-acknowledge-abuse" "--rc" "--rc-addr=localhost:0" "--log-file" "/tmp/rclone.log" "--drive-service-account-file" "/path/to/sa.json"]
...
DEBUG : subdir1/AudioFile1.mp3: MD5 = 9ee023***6162f18 OK
INFO  : subdir1/AudioFile1.mp3: Copied (new)
INFO  : subdir1/AudioFile1.mp3: Deleted
DEBUG : subdir1/AudioFile2.mp3: MD5 = 26b***c934e2e70e OK
INFO  : subdir1/AudioFile2.mp3: Copied (new)
INFO  : subdir1/AudioFile2.mp3: Deleted
DEBUG : subdir1/AudioFile3.mp3: MD5 = 21df***95a0facb4f4 OK
INFO  : subdir1/AudioFile3.mp3: Copied (new)
INFO  : subdir1/AudioFile3.mp3: Deleted
INFO  :
Transferred:             31.367G / 31.367 GBytes, 100%, 47.285 MBytes/s, ETA 0s
Checks:              1682 / 1682, 100%
Deleted:              841
Transferred:          841 / 841, 100%
Elapsed time:     11m19.2s
....
```

**Comment by ncw** [comment]
> My issues exclusively happen inside this Python wrapper script, but _only_ happen for certain recent versions of rclone.

So if you do the commands not via your program they work correctly? Could you try that?

Can you post your config with secrets XXX-ed out too please.

**Comment by opsoyo** [comment]
> > My issues exclusively happen inside this Python wrapper script, but _only_ happen for certain recent versions of rclone.
> 
> So if you do the commands not via your program they work correctly? Could you try that?
> 
> Can you post your config with secrets XXX-ed out too please.

Sorry about that. I mistakenly left that information out. All versions tested run the command successfully when used directly. 

The configuration is a bit more complicated because my script does some stuff 😄 

Configuration in `rclone.conf`:
```
...
[GD_TD_1]
type = drive
scope = drive
team_drive = *****
...
[GD_TD_2]
type = drive
scope = drive
team_drive = ****
...
[GD_TD_3]
type = drive
scope = drive
team_drive = ****
...
```

Configuration generated by the Python wrapper:
```
...
[GDRemote]
type = union
remotes = GD_TD_1: GD_TD_2: GD_TD_3: GD_TD_4: GD_TD_5:
...
```

**Comment by ncw** [comment]
The difference must be the environment then.

Have you got environment bars set on the command line or if your program?

Are the users the same? Config files?

**Comment by opsoyo** [comment]
This has been a pretty sketchy script to keep things moving on my end, so not the best practices in place. 😅 No env, just on the host system. I can do just that you're curious where this leads. Certainly isn't game breaking for me :)

I wonder if it's related to how `subprocess` works in Python with some new changes made to how rclone handles files or the filesystem. 

Ultimately, my script is only relevant until rclone can rotate service accounts while writing across unionized Team Drives. From the progress I've seen, I don't think we're too far off. Wish my Go skills were there to help.

**Comment by ncw** [comment]
> This has been a pretty sketchy script to keep things moving on my end, so not the best practices in place.  No env, just on the host system. I can do just that you're curious where this leads. Certainly isn't game breaking for me :)

When you use `subprocess`, the program run will inherit the environment vars of the parent I think.

What about users? When you run your python script does it run as the same user you used for command line testing?

**Comment by opsoyo** [comment]
As far as I know, the user is the same. The Python script has always been run by `user`, and the the output of `ps aux` suggests it's by the very same. 🤔 

I'll try playing with permissions and potentially on another system to see what happens.

**Comment by animosity22** [comment]
Anything else to do here?

**Comment by opsoyo** [comment]
No, not for now. I'll come back when I have more information to offer.
