### ISSUE TITLE
VFS-BETA: Missing Files On Upload

### ISSUE THREAD

**Issue by tcf909** [rclone/rclone#4417]
#### What is the problem you are having with rclone?
When rsync transferring files to a remote machine that has rclone mounts using the rsync option temp-path, files are made visible in the mount listing, but do not actually make their way to the remote.

RSYNC COPY -> SSH -> REMOTE SERVER -> RCLONE MOUNT (VFS CACHE) -> RCLONE CRYPT -> GOOGLE DRIVE

#### What is your rclone version (output from `rclone version`)
```
rclone v1.52.2-203-gc1780f8d-vfs-beta
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu based docker image

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
rclone mount DRIVE-B-V:/Media /mnt/Media -vv --progress --allow-other --dir-cache-time 8760h --drive-skip-gdocs --fast-list --uid 65534 --gid 100 --umask 007 --vfs-cache-mode minimal --vfs-cache-poll-interval 1m --vfs-read-chunk-size 32M --vfs-cache-max-age 8760h --vfs-cache-max-size 4G
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
Scrubbed log attached.
[scratch.txt](https://github.com/rclone/rclone/files/4887644/scratch.txt)

**Comment by ncw** [comment]
I managed to replicate this

```
$ cd /tmp
$ mkdir mount
$ rclone mount -vv /tmp/mount/ /mnt/tmp/ --vfs-cache-mode minimal 2>&1 | tee vfs.log
```

And

```
$ date > test.txt
$ ls /mnt/tmp/
$ mkdir /mnt/tmp/tempdir
$ rsync -av --temp-dir /mnt/tmp/tempdir test.txt /mnt/tmp/
sending incremental file list
test.txt

sent 133 bytes  received 35 bytes  336.00 bytes/sec
total size is 29  speedup is 0.17
$ ls -l /mnt/tmp/
total 1
drwxrwxr-x 1 ncw ncw  0 Jul  8 10:39 tempdir
-rw-rw-r-- 1 ncw ncw 29 Jul  8 10:38 test.txt
$ ls -l /mnt/tmp/tempdir/
total 0
```

So file has apparently arrived, but it hasn't been renamed on the remote

```
$ ls /tmp/mount/
tempdir
$ ls /tmp/mount/tempdir/
test.txt.Qiraev
$ 
```

I've managed to fix this (and I've added a test to make sure it won't happen again)

Can you double check please?

[v1.52.2-208-gd759c1ab-vfs-beta](https://beta.rclone.org/branch/v1.52.2-208-gd759c1ab-vfs-beta/) on branch [vfs](https://github.com/rclone/rclone/tree/vfs) (uploaded in 15-30 mins)

**Comment by tcf909** [comment]
Looks good. Thanks Nick.

**Comment by ncw** [comment]
Thanks for testing :-) I'll merge this to the beta shortly for release in 1.53
