### ISSUE TITLE
Netatalk can't browse rclone mega mounts

### ISSUE THREAD

**Issue by braindump** [rclone/rclone#4421]
#### Output of `rclone version`
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.12.12

#### Describe the issue
When I try to share a a folder that's mounted using rclone with Netatalk, all I get is an error on my client that no shares are available and a log message of Netatalk on the server `dsi_stream_read: len:0, unexpected EOF`. As soon as I unmount the Mega folder it works as expected.

**Comment by ncw** [comment]
Can you run the rclone mount with -vv and try to find the corresponding logs for the Netatalk error?

Also can you try v1.52.2 which is the latest?

**Comment by braindump** [comment]
The log shows exactly nothing I'm afraid, but same behavior with 1.52.2

**Comment by ncw** [comment]
Maybe Netatalk doesn't work with FUSE. It might be worth searching for that.

**Comment by animosity22** [comment]
If you can share the debug log from the rclone mount, that might shed some light when you try to browse.

**Comment by animosity22** [comment]
If you have a log or something to add, you can always post on the forums:

https://forum.rclone.org and we can help out there.
