### ISSUE TITLE
Implement QuickXorHash for local filesystem

### ISSUE THREAD

**Issue by Zvezdin** [rclone/rclone#4422]
To my understanding, OneDrive for Business uses QuickXorHash for checksums. When I sync files from the local filesystem, rclone successfully calculates their local checksum and compares with what onedrive responds. However when I sync files with `--track-renames` and `--track-renames-strategy hash` I get the following:
`ERROR : Chunked 'onedrive_chunk:': Ignoring --track-renames as the source and destination do not have a common hash`

I have onedrive for business atop a crypt atop a chunker. I presume that is because the local filesystem as a backend does not support that type of hash. Or it could be that since calculating the checksum would require an encryption of the file with the same salt (if it is applied), then that may create complications.

**Comment by animosity22** [comment]
You are using a cryptred remote and with a crypted remote, you can't hash until:

https://github.com/rclone/rclone/issues/1712

gets done.

If you have any further questions, please just ask on the forums:

https://forum.rclone.org

Thanks!
