### ISSUE TITLE
Google Photos: ERROR : Google Photos path "album/zPhoto_Sync": not deleting files as there were IO errors

### ISSUE THREAD

**Issue by maltokyo** [rclone/rclone#4426]
#### What is the problem you are having with rclone?

Google Photos "sync" works well, but at the end when it tries to delete the photos already on google photos that are not anymore in the source, it fails (consistently), leaving the orphan photos on Google Photos.

#### What is your rclone version (output from `rclone version`)

rclone v1.52.2
- os/arch: linux/amd64
- go version: go1.14.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian 10 64-bit (then running official Docker version of rclone)

####  Which cloud storage system are you using? (eg Google Drive)

Google Photos

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```sh
#!/bin/sh
/usr/local/bin/rclone sync --checksum --progress \
--transfers 1 \
--checkers 16 \
--contimeout 60s \
--timeout 300s \
--retries 3 \
--low-level-retries 10 \
--stats 1s \
--max-size 10G \
--exclude "*.AAE" --exclude "*.tif" --exclude "*.psd" --exclude "*.TIF" --exclude "_ToSort/**" --exclude "*.lisj" --exclude "*.pdf" --exclude "*.DS_Store" --exclude "*.xmp" --exclude "*.XMP" --exclude "*.rar" --exclude "*.zip" --exclude "*.img" --exclude "*.lij" \
--log-file=/config/rclone/photos/log_photosync.txt --log-level NOTICE \
"/media/drive1/zRClone_Backups/Photo_Library" "maltokyo-google-photos:album/zPhoto_Sync"
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Rest of command ends fine, and all uploads work well.  But these lines are repeated at the end of every run of this script.  There are about 100k photos, and maybe around 1000 should be deleted (maybe too many?).  The only details shown are:

```
2020/07/11 07:22:22 ERROR : Google Photos path "album/zPhoto_Sync": not deleting files as there were IO errors
2020/07/11 07:22:22 ERROR : Google Photos path "album/zPhoto_Sync": not deleting directories as there were IO errors
```

**Comment by animosity22** [comment]
You'd have to share the whole log as we'd have to see what happened before.

Run it with -vv and share the debug log.

**Comment by maltokyo** [comment]
Thank you, can I share in private somehow, as it contains names of 100k photos and their folders?

**Comment by animosity22** [comment]
It's probably best to email @ncw and mention this issue in the email:

nick@craig-wood.com

**Comment by maltokyo** [comment]
I'll close this issue, and make a consolidated issue for Google Photos (I had other issues too) and email @ncw the logs

**Comment by maltokyo** [comment]
made a better issue here: https://github.com/rclone/rclone/issues/4439 so closing this one
