### ISSUE TITLE
rclone sync complains of duplicate objects in destination, ignores and fails to remove them

### ISSUE THREAD

**Issue by eharris** [rclone/rclone#4429]
### What is the problem you are having with rclone?

`rclone sync <localpath> remote:path` sometimes gives errors about duplicate objects:

```
2020/07/12 02:54:56 NOTICE: 02 - Pixies - Tame.flac: Duplicate object found in destination - ignoring
2020/07/12 02:54:56 NOTICE: 03 - Pixies - Wave of Mutilation.flac: Duplicate object found in destination - ignoring
```

Successive runs of sync continue to emit these errors, and the duplicates are never cleaned up/dealt with.

Note that I'm concerned primarily with the fact that rclone isn't cleaning up the dupes when `sync` is specified.  So far I'm unclear about how the dupes occurred in the first place (probably from a run that received errors), so this ticket is only about not dealing with them once they exist.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.52.2-DEV
- os/arch: linux/amd64
- go version: go1.11.6
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian Buster amd64

####  Which cloud storage system are you using? (eg Google Drive)

Opendrive with crypt overlay (standard)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

`rclone sync 'audio/Archives_FLAC/Pixies - Doolittle' 'odc:audio/Archives_FLAC/Pixies - Doolittle'`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
> rclone sync -vv 'audio/Archives_FLAC/Pixies - Doolittle' 'odc:audio/Archives_FLAC/Pixies - Doolittle'
2020/07/12 02:54:50 DEBUG : rclone: Version "v1.52.2" starting with parameters ["rclone" "sync" "-vv" "audio/Archives_FLAC/Pixies - Doolittle" "odc:audio/Archives_FLAC/Pixies - Doolittle"]
2020/07/12 02:54:50 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2020/07/12 02:54:51 DEBUG : Starting OpenDrive session with ID: <hidden>
2020/07/12 02:54:53 DEBUG : Starting OpenDrive session with ID: <hidden>
2020/07/12 02:54:56 NOTICE: 02 - Pixies - Tame.flac: Duplicate object found in destination - ignoring
2020/07/12 02:54:56 NOTICE: 03 - Pixies - Wave of Mutilation.flac: Duplicate object found in destination - ignoring
2020/07/12 02:54:56 DEBUG : 02 - Pixies - Tame.flac: Size and modification time the same (differ by -100.856939ms, within tolerance 1s)
2020/07/12 02:54:56 DEBUG : 02 - Pixies - Tame.flac: Unchanged skipping
2020/07/12 02:54:56 DEBUG : 06 - Pixies - Dead.flac: Size and modification time the same (differ by -192.857485ms, within tolerance 1s)
2020/07/12 02:54:56 DEBUG : 06 - Pixies - Dead.flac: Unchanged skipping
...
2020/07/12 02:54:56 DEBUG : Encrypted drive 'odc:audio/Archives_FLAC/Pixies - Doolittle': Waiting for transfers to finish
2020/07/12 02:54:56 DEBUG : Waiting for deletions to finish
2020/07/12 02:54:56 INFO  : There was nothing to transfer
2020/07/12 02:54:56 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Checks:                17 / 17, 100%
Elapsed time:         0.0s

2020/07/12 02:54:56 DEBUG : 3 go routines active
```

Subsequent `rclone ls` command shows the duplicates are still present:

```
> rclone ls 'odc:audio/Archives_FLAC/Pixies - Doolittle'
 19952985 01 - Pixies - Debaser.flac
 13447621 02 - Pixies - Tame.flac
 13447621 02 - Pixies - Tame.flac
 14458628 03 - Pixies - Wave of Mutilation.flac
 14458628 03 - Pixies - Wave of Mutilation.flac
 17164063 04 - Pixies - I Bleed.flac
 23199378 05 - Pixies - Here Comes Your Man.flac
 13583485 06 - Pixies - Dead.flac
 19543610 07 - Pixies - Monkey Gone to Heaven.flac
 12500938 08 - Pixies - Mr. Grieves.flac
  9910476 09 - Pixies - Crackity Jones.flac
 19199155 10 - Pixies - La La Love You.flac
 25458291 11 - Pixies - No. 13 Baby.flac
 11818476 12 - Pixies - There Goes My Gun.flac
 20294560 13 - Pixies - Hey.flac
 13222690 14 - Pixies - Silver.flac
 18581304 15 - Pixies - Gouge Away.flac
  2944387 Cover_Front_-_Large.jpg
       11 notes.txt
```

**Comment by Dibbyo456** [comment]
Rclone sync won’t clear duplicates. You have to manually use dedupe command.

See: https://forum.rclone.org/t/sync-not-clearing-duplicates/14372

**Comment by eharris** [comment]
Thanks for the link.  However, that forum thread still suggests that although `rclone` doesn't currently have the ability to deal with duplicates as part of `rclone sync`, that that should eventually be the proper behavior.  Perhaps this ticket can provide the impetus for resolving that.

This also points out two documentation issues that need to be resolved:

1. The sync command documentation should reflect that despite the name/description/documentation, `rclone sync` is insufficient to actually perform a true "sync" (at least as regards duplicates), and should point to the dedupe command and probably also that forum post as an additional action that may be necessary to get a true "sync".
2. The `rclone dedupe` documentation incorrectly states that dupes is only a problem with Google Drive.  Since I am not using Google Drive and am having this issue, that is clearly not the case.

**Comment by animosity22** [comment]
Most file systems don't create duplicates as you generally can't. It's usually some bug along the way to get a duplicate, which is strange in itself.

You can run rclone dedupe to clean the duplicates and re-run the sync.

Dedupe was originally created for Google Drive as that allows duplicates which is also strange.

I'm not familiar with Opendrive to know if that does. If it does, you can always submit a pull request to add that to the documentation as that's a new one to me as well.

Clearing duplicates with sync is probably not something to add as there's already dedupe and it's a very one off use case.

**Comment by ncw** [comment]
I wasn't aware you could get duplicates with opendrive - they don't let you make them in the web interface. It doesn't have the extra interfaces needed to run the `dedupe` command.

![image](https://user-images.githubusercontent.com/536803/87597183-41181b80-c6e9-11ea-93df-26aa8827a12f.png)

Is it a duplicate differing in case? It doesn't look like it.

```
>>> a="02 - Pixies - Tame.flac"
>>> b="02 - Pixies - Tame.flac"
>>> a == b
True
```

**Comment by eharris** [comment]
I agree with @Dibbyo456 that `sync` by its very nature makes clear what should be done with dupes, so to me it seems like not handling/removing dupes with `sync` is a clear bug. 

@ncw You are right that their web interface prevents creation of duplicates.  However, from first hand experience, I can state definitively that the underlying storage mechanism does allow it.  Here are the characteristics I've noted so far:

* Opendrive's storage engine definitely DOES allow dupes.  It is possible this may be a bug/oversight/unsupported feature on their end.
* This is not a case sensitivity or character encoding difference issue.  The filenames are identical.
* Running `rclone dedupe` does appear to clean up the duplicates, so contrary to @ncw comment above, Opendrive does have the necessary functionality for dedupe to work.

In the course of `rclone sync`ing several thousand files to Opendrive, the creation of duplicates does not seem to be all that unusual.  My syncs so far have unintentionally resulted in about 20-30 duplicates so far.  I haven't been able to dig into how the dupes are getting created (when done unintentionally), but so far the patterns I've noticed suggest that there may occasionally be transient finalization of upload errors where the upload was successful but there was some error that causes a file to be retried, and may then result in a dupe.

I have also discovered that it is VERY easy to intentionally (or accidentally) create dupes simply by running two simultaneous identical sync operations with reasonably large files (4-5MB on a 10mbit connection) from the same source to an Opendrive destination.  This makes sense because both instances are uploading the same files at approximately the same time, before either upload completes.

**Comment by animosity22** [comment]
I don't want sync to do anything with dupes are normal operations don't generate them.

I want to report that as an error and let me choose how to deal with it as it overcomplicates sync and adds unnecessary overhead to it as there are now two places to manage dedupe instead of one.

Sync is already a destructive operation and creates challenges for folks if they aren't familiar with it as adding another destructive piece to it feels bad.

Just my two cents as I have a different perception on how it should work.

**Comment by eharris** [comment]
If you don't like the "destructiveness" of `sync`, then don't use it.  But wanting to keep it intentionally broken for everyone else such that it doesn't handle edge cases (even when what should be done is programmatically and abundantly clear) to fulfill its stated purpose of making the destination an identical copy of the source (to the extent possible) just doesn't make any sense to me.

**Comment by animosity22** [comment]
I was referring to many other comments other users have made as I wasn't referring to myself.

Things aren't always black and white and it's helpful to understand others' viewpoints rather than talking down to them.

**Comment by eharris** [comment]
Can you point to any examples where anyone has ever complained about sync removing files (which dupes are) that were not present in the source was an improper action given the description/definition of what `sync` is meant to do?  And by using the term "improper" I'm intending to make it clear that I don't consider someone doing the wrong thing by mistake/misunderstanding to be a valid reason.  Anyone can misuse a tool, but the programmers for `rm` don't refuse to provide "-r" just because some people might be careless and make a mistake.

**Comment by animosity22** [comment]
Sure:

https://github.com/rclone/rclone/issues/1574

https://github.com/rclone/rclone/issues/1327

There posts on the forums as well as those just a few examples.

rm -rf /* works as well as if you read a few of those issues, you see I do agree with your point of view.

**Comment by ncw** [comment]
> In the course of `rclone sync`ing several thousand files to Opendrive, the creation of duplicates does not seem to be all that unusual. My syncs so far have unintentionally resulted in about 20-30 duplicates so far. I haven't been able to dig into how the dupes are getting created (when done unintentionally), but so far the patterns I've noticed suggest that there may occasionally be transient finalization of upload errors where the upload was successful but there was some error that causes a file to be retried, and may then result in a dupe.

That is interesting. I think that is the same mechanism that causes Google Drive to create dupes occasionally.



> * Running `rclone dedupe` does appear to clean up the duplicates, so contrary to ncw comment above, Opendrive does have the necessary functionality for dedupe to work.

I just had a look through the source...

- We can clean up duplicate files if the remote supports `Move` which Opendrive does.
- We need the `MergeDirs` function to clean up duplicate directories which Opendrive does not support.

So provided you don't get duplicate directories `rclone dedupe` will clear up duplicates just fine!

Let's talk about sync for a moment... There are 3 cases of interest

1. Suppose we are syncing from a backend which supports dupes (like Google Drive) to one which doesn't - like local disk. If there is more than one file with the same name we don't know which one to sync, so rclone gives up.

2. However in this case you are syncing from localhost to a backend which has dupes. In this case I can see your argument that rclone should remove the duplicates on the destination. However rclone would have to find the correct match (if any) from the source to the destination which wouldn't fit into the current code very well as this is done in a different layer (see below). Rclone gives up in this case though at the moment.

3. If rclone was syncing from one backend to another and both support duplicates then rclone would have to use a different kind of sync mechanism. At the moment the listing routines pass pairs of potential files to the checking routines. If we allowed duplicate file sync then rclone would have to pass a set of source files and a set of destination files to the checking routine and it would then have to pair them off by matching size/modtime (or whatever other criteria were in use).

I think rclone's current strategy is fine for 1. Option 3. is rather complicated. Your case 2. is fairly complicated too - you'd probably end up implementing 3. to do it properly.

Backends should declare whether they can have duplicate files or not with the `DuplicateFiles` feature flag so we should set this for Opendrive. Can opendrive have duplicate directories? If so we should implement `MergeDirs`.

**Comment by eharris** [comment]
So far, I have never seen a duplicate directory, only duplicate files, and the files have been handled acceptably by `rclone dedupe`.  As I have never seen a duplicate directory occur on Opendrive, I don't know if it has that capability or not.  For now I think we can get away with assuming it does not, as the repercussions are no worse than the current situation.

In all cases I have seen so far the dupes appear to be identical and appear as if they would be handled by `rclone dedupe --dedupe-mode skip` (although I have been using `--dedupe-mode largest` just to be safe in case a dupe ever didn't get all the way uploaded).

@ncw I agree with your assessment that there are 3 cases to be handled for a complete solution.  As you say, the course of action for case 1 is unclear and the current behavior is fine.    For now, I think case 3 can be left as it is as well, as that would require a larger development overhaul and I'm not sure there is a real use case as of yet (although if one is presented, this could always be reassessed and fixed at a later date).

Case 2 is definitely the one I am most concerned with, and I don't think it is all that complicated since `rclone` already has the ability to detect the duplicates (if it did not, that might have the potential to be a harder problem to solve).  The easiest method seems like it would be to just use the same mechanism that `rclone sync` already uses when a file on the source already exists on the destination. If it looks like it is the same (using mtime, size, checksum or whatever the criteria is) then keep it, if it looks like it is not and a match doesn't already exist then delete it and re-upload it.  Once an "identical" copy has either been found or has been uploaded, any further dupes (whether they appear the same or not) will see that a match already exists on the destination and any additional dupes should just get deleted.

There is a potential inefficiency with this "easy" method, which is that if a non-match is considered first, it will get deleted and re-uploaded.  If there is a later match that hasn't yet been considered, then that file got re-uploaded when it wasn't strictly necessary. If it's easy to do within the current framework, we could avoid this potential inefficiency by traversing the list of identically-named files first to see if we can find one that appears to have identical contents, then keep that before considering the rest.  But even if that's not easy, the worst case cost is an extra upload of that one file, which seems acceptable especially since in all the cases I've seen so far, all of the duplicates have appeared to be identical.  The most important thing (IMO) is to make the end results of `rclone sync` correct in this case, so I'm ok with leaving the implementation of that optimization for a later time if needed.

**Comment by eharris** [comment]
I should also add, that as far as detecting and choosing which case methodology should be used, that also seems fairly easy.  If duplicates are present on the source for a particular filename, then it is either case 1 or case 3 and should emit a warning and (for now) not handle the dupe, leaving whatever destination duplicates might exist alone.  Whether the source supports duplicates may not be known, but I would also argue that it doesn't matter since the behavior is the same.  That is, even if the source supports dupes, if the source doesn't contain any dupes for a particular file, then it should still use the methodology for case 2.

**Comment by animosity22** [comment]
That makes sense to me as well and a very good descriptions.

This is only for OpenDrive and Google Drive I think as well or is there another one that would be impacted?

**Comment by thedaveCA** [comment]
> This is only for OpenDrive and Google Drive I think as well or is there another one that would be impacted?

I am seeing similar on [Cloudflare R2](https://www.cloudflare.com/products/r2/) (via the S3 API). I can't cause duplicates on demand so it isn't clear that they intend to allow duplicate files, but it has occurred multiple times.

```
2022/11/25 11:30:10 NOTICE: 1375947.tar.gz.asc: Duplicate object found in destination - ignoring
2022/11/25 11:30:10 NOTICE: 1375947.tar.gz.sha1: Duplicate object found in destination - ignoring
2022/11/25 11:30:10 NOTICE: 1375947.tar.gz.sha256: Duplicate object found in destination - ignoring
2022/11/25 11:30:10 INFO  : There was nothing to transfer
```
This is just an FYI of a potential other backend where this is possible.

**Comment by arushdesp** [comment]
Is this solver?I'm trying to transfer a chunk of text files via a powershell script from several users. I see some duplicates in the google drive directory. Up to know I am using the rsync copy but i noticed in some case rclone deleted by itself the duplicated but only in 3-4 cases out of 20-30.
Thanks

**Comment by Animosity022** [comment]
@arushdesp - You responded to a closed issue a few years back. If you have a question, please use the forums

https://forum.rclone.org
