### ISSUE TITLE
Build issue: go build causes local changes to checked in file

### ISSUE THREAD

**Issue by eharris** [rclone/rclone#4430]
#### What is the problem you are having with rclone?

Running `go build` within a git repo of `rclone` dirties the repo (makes changes to checked in `go.mod`), and those unstaged changes then prevent other operations like pulling new updates or changing branches unless you first do a `git reset --hard`.  This occurs when following the exact build from source instructions in the documentation.

Example session:

```
> mkdir test; cd test
> git clone https://github.com/rclone/rclone.git
Cloning into 'rclone'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 85710 (delta 5), reused 10 (delta 4), pack-reused 85691
Receiving objects: 100% (85710/85710), 137.52 MiB | 18.02 MiB/s, done.
Resolving deltas: 100% (49772/49772), done.
> cd rclone
> git diff
> go build
> git diff
diff --git a/go.mod b/go.mod
index 07cdbe945..c6b995e5e 100644
--- a/go.mod
+++ b/go.mod
@@ -37,6 +37,8 @@ require (
        github.com/mattn/go-runewidth v0.0.9
        github.com/minio/minio-go/v6 v6.0.57 // indirect
        github.com/mitchellh/go-homedir v1.1.0
+       github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
+       github.com/modern-go/reflect2 v1.0.1 // indirect
        github.com/ncw/go-acd v0.0.0-20171120105400-887eb06ab6a2
        github.com/ncw/swift v1.0.52
        github.com/nsf/termbox-go v0.0.0-20200418040025-38ba6e5628f1
@@ -70,6 +72,7 @@ require (
        golang.org/x/text v0.3.3
        golang.org/x/time v0.0.0-20200416051211-89c76fbcd5d1
        google.golang.org/api v0.28.0
+       google.golang.org/appengine v1.6.6 // indirect
        google.golang.org/genproto v0.0.0-20200626011028-ee7919e894b5 // indirect
        google.golang.org/grpc v1.30.0 // indirect
        google.golang.org/protobuf v1.25.0 // indirect
```

**Comment by animosity22** [comment]
I don't see the same thing when I replayed your steps. Did I do something incorrect?

```
textere@seraphim Downloads % mkdir test
textere@seraphim Downloads % cd test
textere@seraphim test % ls
textere@seraphim test %  git clone https://github.com/rclone/rclone.git
Cloning into 'rclone'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 85710 (delta 5), reused 10 (delta 4), pack-reused 85691
Receiving objects: 100% (85710/85710), 137.56 MiB | 42.62 MiB/s, done.
Resolving deltas: 100% (49765/49765), done.
e
textere@seraphim test % cd rclone
textere@seraphim rclone % git diff
textere@seraphim rclone % go build
textere@seraphim rclone % git diff
```

**Comment by eharris** [comment]
This problem occurs using golang 1.11.6 (stock golang from Debian Buster).  After upgrading to go1.14 (from Debian buster-backports), it doesn't seem to occur anymore, so it would appear to be an issue with older versions of golang.

**Comment by animosity22** [comment]
Right, it's not supported on that version so that's the issue.

**Comment by eharris** [comment]
According to the docs and #4411 with a very recent comment from @ncw, go 1.10 and later is supported.

**Comment by animosity22** [comment]
Is there a reason you want to build with the old version as it's two years old. We can always update the docs and he says "think" not "is supported".

**Comment by eharris** [comment]
According to golang.org, Go 1.11.6 was released 2019/03/14, just a little over a year ago.

As I stated earlier, 1.11.6 is the current version of Go in the current version of Debian stable, which is quite a lot of systems.  Even though Debian stable is known to be dated, I don't think it's unreasonable to expect that things should work on a reasonably current release of Go on a current release of a major distribution, especially when there is no evidence to the contrary in the docs.

**Comment by animosity22** [comment]
Yeah that does make sense so @ncw would need to comment.

Hardly anyone builds though as majority runs the binaries so it's a pretty niche case in that regard but it should be fixed or documents should be updated.

**Comment by ncw** [comment]
I think this is an annoyance of the evolving go module system which was still pretty new in go1.11.

I don't think I can change go.mod just for go1.11 nor fix go1.11 behaviour so the fixes we are limited to are changing the build instructions or Makefile.

What do you think would be acceptable here?

**Comment by eharris** [comment]
If the nature of the build requires modifying a checked in file (like `go.mod`), then perhaps it makes sense to either have the build make a copy of the checked-in file to a non-tracked name/location and modify that copy, or make a backup of the tracked file and then restore it to its original state after the build run finishes.

**Comment by ncw** [comment]
I've just updated the master build to build entirely from modules so it is likely this has changed again.

> If the nature of the build requires modifying a checked in file (like `go.mod`), then perhaps it makes sense to either have the build make a copy of the checked-in file to a non-tracked name/location and modify that copy, or make a backup of the tracked file and then restore it to its original state after the build run finishes.

The build shouldn't be changing go.mod - as far as I'm concerned this is a bug in go1.11.  Alas go1.11 is out of support as far as the go team is concerned - they support the current version (go1.14) and the previous version (go1.13) so I think we have very little chance of this being fixed.

As soon as go1.15 (some time in August 2020 most likely) is out I'll be dropping support for go1.11 - rclone's policy is to support the last 4 go versions which will be go1.12,go1.13,go1.14,go1.15.

Go releases come out every 6 months and are supported for 1 year by the go team. Rclone supporting the last 4 releases is just about sustainable, but I have to drop support for things sometimes when upstream libraries stop supporting go versions eg 17b4058ee944ab660b30593a858ff9d591b62a3b

**Comment by animosity22** [comment]
This looks to be answered so I'm going to close it out.
