### ISSUE TITLE
Create additional log file format options

### ISSUE THREAD

**Issue by dr-mcgillicuddy** [rclone/rclone#4436]
### What is your current rclone version (output from `rclone version`)?

1.52.2

#### What problem are you are trying to solve?
Creating and viewing logs created over long periods of time and containing output from many runs.

#### How do you think rclone should be changed to solve that?

Rclone's logs seem to be formatted the same way that output is formatted on stdout.
An option to print all output from a single run on one line would make parsing log files much easier.
See below for an example.

I have a cron job that kicks off at midnight, and I get a lot of output like this:

```
2020/07/13 12:38:16 INFO  : There was nothing to transfer

2020/07/13 12:38:16 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Checks:             44591 / 44591, 100%
Elapsed time:         0.1s
```

This is problematic because as the log files build over time, it becomes difficult to drill down by date with a log viewer.
If there was an option to have one operation print its output as one line I could feed it to any number of log viewer utilities.  In the alternative, but still hack-y, if the log file could at least be optionally tab delimited instead of return-delimited, results could be fed to a spreadsheet.

At present the only solution to tracking the long term output of multiple rclone-runs is to rotate log files by date, but that is also burdensome if one wants to keep records of more than a few weeks.

**Comment by animosity22** [comment]
There are some one line options already:

```
  --stats-one-line                       Make the stats fit on one line.
      --stats-one-line-date                  Enables --stats-one-line and add current date/time prefix.
      --stats-one-line-date-format string    Enables --stats-one-line-date and uses custom formatted date. Enclose date string in double quotes ("). See https://golang.org/pkg/time/#Time.Format
      --stats-unit string                    Show data rate in stats as either 'bits' or 'bytes'/s (default "bytes")

```

**Comment by dr-mcgillicuddy** [comment]
Is there a way to get the same output though?

`--stats-one-line` doesn't give the same info.

With `--stats-one-line`
```
2020/07/14 06:58:04 INFO  : Encrypted drive 'testdrive:test': Waiting for checks to finish
2020/07/14 06:58:04 INFO  : Encrypted drive 'testdrive:test': Waiting for transfers to finish
2020/07/14 06:58:04 INFO  :          0 / 0 Bytes, -, 0 Bytes/s, ETA -
```
without:

```
2020/07/14 06:59:04 INFO  : Encrypted drive 'testdrive:test': Waiting for checks to finish
2020/07/14 06:59:04 INFO  : Encrypted drive 'testdrive:test': Waiting for transfers to finish
2020/07/14 06:59:04 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Checks:                11 / 11, 100%
Elapsed time:         0.0s

```

**Comment by animosity22** [comment]
I can't tell what command you are running. 

I think you have -v going and you want progress to?

**Comment by dr-mcgillicuddy** [comment]
`rclone copy /localfiles/ testdrive:test --log-file=rclonelog.log --log-level INFO --stats-one-line`
and
`rclone copy /localfiles/ testdrive:test --log-file=rclonelog.log --log-level INFO`

Basically I like the info that says number of checks performed and time elapsed, as if something goes wrong and causes rclone to terminate early, I can see that in the file count, for example.

**Comment by animosity22** [comment]
What do you mean 'terminate early'? Someone kills it?

You can change the internal from one minute to something smaller:

```
 --stats duration                       Interval between printing stats, e.g 500ms, 60s, 5m. (0 to disable) (default 1m0s)
```

**Comment by dr-mcgillicuddy** [comment]
I've seen copy activities from some webdav servers terminate early with an incorrect file count.
I do not think it's rclone's fault.

However if on Monday's there are 12,000 files checked in my WebDAV share, and on Tuesday it's 6,000 then I know I need to go kick off my backup script again.

**Comment by animosity22** [comment]
So you don't care about the stats, you care about checks/transferred numbers and you'd parse that to compare a day against another day?

Wouldn't the script exit out with a non zero code if it got errors though too?

So stats-one-line isn't what you are looking for.

**Comment by dr-mcgillicuddy** [comment]
Basically, I would expect `--stats-one-line` to print this:
`2020/07/14 06:59:04 INFO  : Transferred: 0 / 0 Bytes, -, 0 Bytes/s, ETA - Checks: 11 / 11, 100% Elapsed time: 0.0s`
or similar.

But instead it just prints:
`2020/07/14 06:58:04 INFO  :          0 / 0 Bytes, -, 0 Bytes/s, ETA -` ignoring the rest of the INFO level log data

**Comment by animosity22** [comment]
Yeah, the checks and transferred aren't the stats though but I get what you are asking now.

**Comment by dr-mcgillicuddy** [comment]
Oh, I see.  Well that makes sense then.

As of now I just have the full rclone command in my crontab.
I guess my workaround is to instead run a script that will append some sort of divider text or symbols to the log between runs, unless there's a way to pull the checks and transferred items up to the previous line?

**Comment by dr-mcgillicuddy** [comment]
I see what you were after with the `--stats-duration` flag now.
There's no way to just have rclone print the stats once, when it completes the command, correct?

The proper way to do that is maybe `--stats-duration 24h` or something especially long in duration?

**Comment by ncw** [comment]
> There's no way to just have rclone print the stats once, when it completes the command, correct?
> 
> The proper way to do that is maybe `--stats-duration 24h` or something especially long in duration?

That is what I usually recommend people, except the flag is called `--stats`, so `--stats 24h`

**Comment by animosity22** [comment]
Is there anything left for this item or can it be closed out?

**Comment by animosity22** [comment]
Closing out as it looks to be stale and answered :)
