### ISSUE TITLE
Google Photos: Constantly hit Google's API rate limit when syncing photo directory

### ISSUE THREAD

**Issue by maltokyo** [rclone/rclone#4439]
#### What is the problem you are having with rclone?

Constantly hit Google's API rate limit when syncing photo directory.  I understand that there is a limit, but I am merely syncing a directory, and it uses the 10000 api limit when it is checking the sizes of the first 10k (I assume?) photos in Google Photos, and hence will not continue to upload any of the photos that it did not yet get to.

#### What is your rclone version (output from `rclone version`)

Docker (latest version) rclone:

```
rclone v1.52.2
- os/arch: linux/amd64
- go version: go1.14.4

```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian 10.4 64-bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Photos

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

Sensitive info included, so I have emailed to @ncw as instructed here: https://github.com/rclone/rclone/issues/4426

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Sensitive info included, so I have emailed to @ncw as instructed here: https://github.com/rclone/rclone/issues/4426

@ncw thank you for taking a look!!

**Comment by maltokyo** [comment]
@ncw email sent to you just now.  Thanks again.

**Comment by ncw** [comment]
Have you got `read_size` set in your config? That is really expensive in terms of transactions. If so can you try removing it. You should find the sync works without it.

There are a lot of `Failed to copy: google photos API only allows uploading to albums rclone created` errors in your log.

Alas rclone can only upload to albums it created - that is a limit of the photos API.

Are you using your own client_id? If you don't get your app approved the quota is ridiculously low.

**Comment by maltokyo** [comment]
Thank you for looking at it.  

1. Here is my config (rclone.conf) with sensitive data removed.  That's it, nothing else.  So I do not see any `read_size`.

```
[google-com-photos]
type = google photos
token = {"access_token":"XXXXX","token_type":"Bearer","refresh_token":"YYYYY","expiry":"2020-07-15T11:06:19.456789863Z"}
client_id = DDDDD.apps.googleusercontent.com
client_secret = TTTTTTTT
```

2. I used it without my own client ID previously, so I guess it used the standard RClone one.  Is that better?  Now it uses mine and cant change the albums that were uploaded with the RClone one...  Damn, that is crazy!  I guess I will delete mine and use yours, or find out how I get "approved"?  Would you know how you got yours approved?

**Comment by animosity22** [comment]
Is there anything left to do for this one? You'd have to submit a request to get it approved and it's really in Google's hand to approve it and not sure we did anything special.

I've seen many forum users have their own limits approved.

You can always ask there. I'm going to close this out as it looks answered.
