### ISSUE TITLE
documentation - service accounts

### ISSUE THREAD

**Issue by kcris** [rclone/rclone#4440]
Hi,

I just configured rclone for unattended use with gdrive.

I spent some time dealing with the following error
`
rclone -v --drive-impersonate me@mydomain.com lsf afgdrive:
2020/07/16 13:57:34 NOTICE: Google drive root '': Ignoring cached root_folder_id when using --drive-impersonate
2020/07/16 13:57:34 Failed to create file system for "my_gdrive:": couldn't find root directory ID: Get "https://www.googleapis.com/drive/v3/files/root?alt=json&fields=id&prettyPrint=false&supportsAllDrives=true": oauth2: cannot fetch token: 401 Unauthorized
Response: {
  "error": "unauthorized_client",
  "error_description": "Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested."
}
`

I had previously configured a Service Account, according to your docs. I am using GSuite.
* rclone was able to handle files in some auto-generated root folder id (which was weird since that root folder is not visible in my gdrive, I guess it belongs to the service account I created, it was only visible in rclone results)
* rclone was never able to see the folder I specified as root

My problem was fixed by "sharing" the (mydrive) folder I wanted to use as root with the user/email of the new Service Account I created.

It wasn't obvious for me at first, and I did not see this in your documentation. 
Perhaps it will help to add a note in the documentation about this.

Thanks

**Comment by animosity22** [comment]
You can help out and if there is something to change, you can always submit a pull request to update the documentation.

For discussion, it's much easier to use the forums rather than opening an issue.

If you want to share something on the forums, I'm happy to help out and submit a pull request as well.

Thanks!

**Comment by Cprakhar** [comment]
@kcris, I am not seeing the share option on my-drive folder? Can you provide more info? I am using a service account and created a client ID and secret. Facing the same issue.

**Comment by kcris** [comment]
what I did: went to my gdrive, right clicked on a specific folder, clicked Share 

and then picked the email address of my new service account

<img width="1724" height="906" alt="Image" src="https://github.com/user-attachments/assets/72e7bef5-b430-4625-b9b1-56d4c0b0656c" />
