### ISSUE TITLE
Dropbox: copy does not ignore newer files on destination

### ISSUE THREAD

**Issue by canzone** [rclone/rclone#4441]
#### What is the problem you are having with rclone?

I have a directory with a few plain text files. I change a file in my Dropbox (cloud) instance and, in my computer, I perform a copy It is overwriting the newer file in the cloud with the older version in my computer. The blogs and docs say that "copy" does not overwrite newer files in the destination.

#### What is your rclone version (output from `rclone version`)

rclone v1.52.2
- os/arch: darwin/amd64
- go version: go1.14.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

MacOS 10.15.5 64bit

####  Which cloud storage system are you using? (eg Google Drive)

Dropbox

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

"rclone copy /path/ destination:path/".

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

The changed file is named "(Clipboard).txt"

`./rclone copy "/Users/me/Dropbox/My Notes/Pessoal" "Dbox:My Notes/Pessoal" -vv
2020/07/16 18:46:47 DEBUG : rclone: Version "v1.52.2" starting with parameters ["./rclone" "copy" "/Users/me/Dropbox/My Notes/Pessoal" "Dbox:My Notes/Pessoal" "-vv"]
2020/07/16 18:46:47 DEBUG : Using config file from "/Users/me/.config/rclone/rclone.conf"
2020/07/16 18:46:48 DEBUG : Dropbox root 'My Notes/Pessoal': Waiting for checks to finish
2020/07/16 18:46:48 DEBUG : ToDo.txt: Size and modification time the same (differ by -699.088ms, within tolerance 1s)
2020/07/16 18:46:48 DEBUG : ToDo.txt: Unchanged skipping
2020/07/16 18:46:48 DEBUG : Imigracao_Italiana.txt: Size and modification time the same (differ by -473.517ms, within tolerance 1s)
2020/07/16 18:46:48 DEBUG : Imigracao_Italiana.txt: Unchanged skipping
2020/07/16 18:46:48 DEBUG : Stocks 2020.txt: Size and modification time the same (differ by -381.59ms, within tolerance 1s)
2020/07/16 18:46:48 DEBUG : Stocks 2020.txt: Unchanged skipping
2020/07/16 18:46:48 DEBUG : Contas.txt: Size and modification time the same (differ by -202.304ms, within tolerance 1s)
2020/07/16 18:46:48 DEBUG : Organizador Armarios.txt: Size and modification time the same (differ by -74.189ms, within tolerance 1s)
2020/07/16 18:46:48 DEBUG : Contas.txt: Unchanged skipping
2020/07/16 18:46:48 DEBUG : Organizador Armarios.txt: Unchanged skipping
2020/07/16 18:46:48 DEBUG : Anotacoes.txt: Size and modification time the same (differ by 0s, within tolerance 1s)
2020/07/16 18:46:48 DEBUG : (Clipboard).txt: Sizes differ (src 11403 vs dst 11531)
2020/07/16 18:46:48 DEBUG : Anotacoes.txt: Unchanged skipping
2020/07/16 18:46:48 DEBUG : Dropbox root 'My Notes/Pessoal': Waiting for transfers to finish
2020/07/16 18:46:49 DEBUG : (Clipboard).txt: DropboxHash = cab983095e88bacdabdafadf7ecdd34791d14ab8422280f0205191cb3421500b OK
2020/07/16 18:46:49 INFO  : (Clipboard).txt: Copied (replaced existing)
2020/07/16 18:46:49 INFO  : 
Transferred:   	   11.136k / 11.136 kBytes, 100%, 7.449 kBytes/s, ETA 0s
Checks:                 7 / 7, 100%
Transferred:            1 / 1, 100%
Elapsed time:         1.4s
`

**Comment by animosity22** [comment]
It's copied because the sizes are different:

```
8:46:48 DEBUG : (Clipboard).txt: Sizes differ (src 11403 vs dst 11531)
```

**Comment by canzone** [comment]
Hi @animosity22, thanks a lot for the quick answer!!
I know the sizes are different, but I've read that, using "copy", files that are newer in the target are not overwritten.  If I want a full sync I should use "sync" instead, right?

**Comment by animosity22** [comment]
The log there doesn't show an issue.

Can you replicate what you are talking about?

**Comment by animosity22** [comment]
You should see this:

```
felix@gemini:~$ rclone copyto /etc/hosts GD:hosts.txt -vv
2020/07/16 14:05:38 DEBUG : rclone: Version "v1.52.2-214-g67098511-beta" starting with parameters ["rclone" "copyto" "/etc/hosts" "GD:hosts.txt" "-vv"]
2020/07/16 14:05:38 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2020/07/16 14:05:38 DEBUG : fs cache: adding new entry for parent of "/etc/hosts", "/etc"
2020/07/16 14:05:38 DEBUG : hosts: Sizes differ (src 413 vs dst 426)
2020/07/16 14:05:39 DEBUG : hosts: MD5 = 157c632175c4251012e651322736f0ae OK
2020/07/16 14:05:39 INFO  : hosts: Copied (replaced existing)
2020/07/16 14:05:39 INFO  :
Transferred:   	       413 / 413 Bytes, 100%, 509 Bytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         0.8s

```

**Comment by canzone** [comment]
I'm assuming that this affirmation is accurate:
https://forum.rclone.org/t/sync-but-check-for-last-modifide-date/14941/2

`copy will just add everything from A to B. If file exist but has older date - it is overwritten with newest file. **If date is newer then it just skips this file**`

**Comment by animosity22** [comment]
That's from 2016, can you just replicate the issue?

**Comment by animosity22** [comment]
Here is my cloud file:

![image](https://user-images.githubusercontent.com/5088712/87707013-71ee6400-c76e-11ea-8109-8bd84c17c76d.png)


Here is my local file which is older

```
-rw-r--r-- 1 root root 413 Jun 22 07:54 /etc/hosts
```

and it replaced it.

```
felix@gemini:~$ rclone copyto /etc/hosts GD:hosts.txt -vv
2020/07/16 14:13:18 DEBUG : rclone: Version "v1.52.2-214-g67098511-beta" starting with parameters ["rclone" "copyto" "/etc/hosts" "GD:hosts.txt" "-vv"]
2020/07/16 14:13:18 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2020/07/16 14:13:18 DEBUG : fs cache: adding new entry for parent of "/etc/hosts", "/etc"
2020/07/16 14:13:19 DEBUG : hosts: Sizes differ (src 413 vs dst 427)
2020/07/16 14:13:20 DEBUG : hosts: MD5 = 157c632175c4251012e651322736f0ae OK
2020/07/16 14:13:20 INFO  : hosts: Copied (replaced existing)
2020/07/16 14:13:20 INFO  :
Transferred:   	       413 / 413 Bytes, 100%, 451 Bytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         0.9s

2020/07/16 14:13:20 DEBUG : 4 go routines active
```

**Comment by animosity22** [comment]
and the time is back to 22-Jun on the cloud file:

```
felix@gemini:~$ rclone lsl GD:hosts.txt
      413 2020-06-22 07:54:03.426000000 hosts.txt
```

![image](https://user-images.githubusercontent.com/5088712/87707159-a9f5a700-c76e-11ea-9c6c-5d364b97c529.png)

**Comment by canzone** [comment]
Ok. I got it. Maybe it changed how it works since that old post.
Long story short: is it possible to make rclone ignore files that are older in the target? My idea is to have a "pseudo bi-directional" sync. So I copy updates from destination to target, then from target to destination".

**Comment by animosity22** [comment]
```
  -u, --update                               Skip files that are newer on the destination.
```

**Comment by animosity22** [comment]
So the title says you want to ignore newer files on the destination, but that last part says you want to ignore older.

Which is it?

**Comment by canzone** [comment]
I want to ignore files that are newer on the destination.... let me test this -u option.
Thanks!

**Comment by canzone** [comment]
Yep... it worked!!!
And, you know, the option was there in the Global Flags help page... how didn't I see it?
I'm definitely getting old.
Thank you very much!!!!
