### ISSUE TITLE
Deleted Files in Remote are still visible in Cache

### ISSUE THREAD

**Issue by darthShadow** [rclone/rclone#4446]
#### What is the problem you are having with rclone?

As per my discussion with @ncw any files deleted from the remote aren't removed from the cache till the cache expiry runs which can be a couple of days now with the new vfs caching changes for the full mode.

In that case, what happens is the following sequence:

* Plex has probed the earlier file which downloads only a single chunk and caches the file entry
* User upgrades the earlier file i.e. deletes the existing file and uploads a better copy
* When Plex goes to scan it again, it sees two files, hence, creates 2 metadata entries for the same movie and shows both as playable
* When any random user goes to play the file in Plex, he can select any of those 2 copies to play, which can result in a playback issue if he selects the file that was removed from the remote but still has a chunk cached.

I am sure there can be a similar problem with a different use case too, but I faced the problem in the above use case hence the steps for the same.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.52.2-209-gca3fbdef-vfs-beta
- os/arch: linux/amd64
- go version: go1.14.4
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux amd64-bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```
rclone mount PersonalTD:Media /home/darthshadow/TDMedia --dir-cache-time=960000h --vfs-cache-mode=full --vfs-cache-max-age=120h --vfs-cache-max-size=200G --vfs-cache-poll-interval=5m --poll-interval=30s --cache-dir=/home/darthshadow/rclone/vfs/TD/ --attr-timeout=0
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

N/A

**Comment by ncw** [comment]
> As per my discussion with @ncw any files deleted from the remote aren't removed from the cache till the cache expiry runs which can be a couple of days now with the new vfs caching changes for the full mode.

Does the change notify not update the cache? I would have thought when you delete the file on the remote, the change notify should tell rclone and it will remove the file from the directory entry.

However If I use `--poll-interval 0` to turn off change notify I can replicate this problem.

What is happening is that a virtual directory entry gets made when you upload the file. The virtual entries normally get removed if you read the directory and the file is missing.

However if you don't read the directory and delete the remote file the virtual directory entry will remain indefinitely.

I have a potential fix for this but it doesn't work yet :-(

(sorry forgot to press send)

**Comment by darthShadow** [comment]
> Does the change notify not update the cache? I would have thought when you delete the file on the remote, the change notify should tell rclone and it will remove the file from the directory entry.

It doesn't seem to be removing cached files, only adding them.

Just to clarify, this is not with files that were created and then uploaded, but instead with files that were downloaded/streamed via the mount. Not sure whether that makes a difference.

**Comment by saltydk** [comment]
I use a 2 system setup (seedbox/plex) with rclone 1.53 and full cache. I am experiencing a similar issue when sonarr/radarr replaces a file that has been cached (analysis done by plex or playback) where it is not being removed from the cache on the Plex system. I am unsure if Plex had the file open at the time of the deletion but that is probable on some of the occurrences.

**Comment by Silent-Remux** [comment]
@ncw any word on updates to this?

**Comment by wiserain** [comment]
Still experiencing ghost local files with `v1.53.1`, `Ubuntu focal 20.04 amd64`, `--vfs-cache-mode=full --dir-cache-time=1000h --polling-interval=15s --vfs-cache-max-age=300h`.

**Comment by saltydk** [comment]
Even if I queue a vfs/refresh for the directory containing the "ghost" file it does not get removed. Same result using vfs/forget. I assume both of those commands relate more to the directory caching and that I probably need to do something else to trigger a recheck for the file/folder itself that is specific to the cached file.

Maybe having rclone double check the cached entries when a refresh is done could be a way? I have no idea of the performance implications of such a "solution" though.

**Comment by stokkes** [comment]
Adding this for reference as it's probably the same issue (but reversed): https://forum.rclone.org/t/missing-files-in-mount-but-present-on-remote/19399/10

I'll be patiently watching this :)

**Comment by cptv** [comment]
I'm having the same issue on Rclone v1.53.2. If I delete a file on the remote externally (say via Google Drive web), the deleted file does not get removed from my VFS mount. However if I unmount and remount, I can manually get the "ghost" files to disappear 

This does not always occur but seems to happen most often if you have very recently accessed a file via the VFS mount and then shorlty after delete it externally (via web). It will be stuck in your mount well past the set polling and dir-cache times. However if it's been a while (a few hours in my testing) since you last accessed/cached the file and you delete it externally, it will almost immediately be removed from your mount (likely at first poll). This is a bit surprising since I have the `--vfs-cache-max-age 700h` flag set on my my mount, so I'm not sure why access time seems to be a factor

Here are all the options I use in case there is a conflict causing the issue:
```
  --user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36' \
  --config=/var/lib/plexmediaserver/.config/rclone/rclone.conf \
  --allow-other \
  --vfs-cache-mode full \
  --vfs-cache-max-size 1200G \
  --vfs-cache-max-age 700h \
  --vfs-read-chunk-size=64M \
  --vfs-read-chunk-size-limit=1G \
  --vfs-read-ahead=64M \
  --umask=002 \
  --syslog \
  -v \
```

**Comment by ncw** [comment]
Here is a first attempt to fix this - testing appreciated :-)

[v1.54.0-beta.4887.226018dc2.fix-4446-vfs-virtual](https://beta.rclone.org/branch/fix-4446-vfs-virtual/v1.54.0-beta.4887.226018dc2.fix-4446-vfs-virtual/) on branch [fix-4446-vfs-virtual](https://github.com/rclone/rclone/tree/fix-4446-vfs-virtual) (uploaded in 15-30 mins)

**Comment by darthShadow** [comment]
@ncw Looks like the linux builds failed.

**Comment by ncw** [comment]
Here is a version with hopefully fixed linux builds. That was more complicated to fix than I thought!

[v1.54.0-beta.4889.45e8bea8d.fix-4446-vfs-virtual](https://beta.rclone.org/branch/fix-4446-vfs-virtual/v1.54.0-beta.4889.45e8bea8d.fix-4446-vfs-virtual/) on branch [fix-4446-vfs-virtual](https://github.com/rclone/rclone/tree/fix-4446-vfs-virtual) (uploaded in 15-30 mins)

**Comment by saltydk** [comment]
From initial testing the items do indeed no longer appear in the directory but it would've been nice if they were also deleted when present in the local cache.

**Comment by ncw** [comment]
Thanks for testing.

The items will get expired from the cache when `--vfs-cache-max-age` or `--vfs-cache-max-size` is reached. This isn't ideal but dealing with the corner cases of the backend being modified while the vfs caching it is very hard!

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54

**Comment by saltydk** [comment]
The files were indeed gone when I woke up this morning. I can live with that as long as the rest works :)

**Comment by cptv** [comment]
@ncw Thanks for the amazingly quick fix! I've been using the latest betas for the past few days and have had no issues. I've done a few tests and the VFS mount now updates instantly when a file is removed externally. Thanks again!
