### ISSUE TITLE
rclone sync only updates modification time with audio files that have different tags.

### ISSUE THREAD

**Issue by EggsAreChickenPeriods** [rclone/rclone#4451]
#### What is the problem you are having with rclone?

FolderA has audio1.flac and FolderB has audio1.flac
Changed tags in FolderA's .flac file (comment, artist, etc.).
rclone sync FolderA FolderB
Only modification time is updated, file is not copied. Tags are not present in the synced folder.

#### What is your rclone version (output from `rclone version`)

1.52.2

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Win10 64-bit

####  Which cloud storage system are you using? (eg Google Drive)

Local

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync

**Comment by animosity22** [comment]
You can always use the forums for questions rather than opening an issue:

https://forum.rclone.org

That being said, you neglected to include a debug log as that's needed to see what's going on.

**Comment by ncw** [comment]
Can you run your failing command  with `-vv` and paste the output please?

**Comment by animosity22** [comment]
If you have any follow ups on this, please just post on the forums.

Thanks!
