### ISSUE TITLE
Implement --allow-other flag as parameter of mount/mount rc command

### ISSUE THREAD

**Issue by splintax** [rclone/rclone#4455]
#### What is your current rclone version (output from `rclone version`)?

rclone v1.52.2-232-gff843516-beta
- os/arch: linux/amd64
- go version: go1.14.6

#### What problem are you are trying to solve?

I'd like to create an application which can mount and unmount rclone remotes at runtime, and monitor active mounts using the experimental web GUI. The `mount/mount` rc command gets me most of the way there, but mounts are created without the `allow_other` FUSE option, meaning they are only accessible by the user running  `rclone rcd`.

I've added `allow_other` and `user_allow_other` to my `/etc/fuse.conf`, but it seems that this isn't enough to make mounts accessible to other users by default – rclone also needs to specify the option at runtime.

#### How do you think rclone should be changed to solve that?

It seems like it would be easy to add a new `AllowOther` parameter to `MountInfo` in [cmd/mountlib/rc.go](https://github.com/rclone/rclone/blob/master/cmd/mountlib/rc.go), although I haven't worked out how to map that parameter to the `AllowOther` flag in [cmd/mountlib/mount.go](https://github.com/rclone/rclone/blob/cmd/mountlib/mount.go) yet. I could give this a try and submit a pull request.

But what I had expected to find in the code was a one-to-one mapping between the flags on the `mount` command and the parameters to the `mount/mount` rc function. I'm not familiar enough with the codebase (or Go generally) to say whether that would be a feasible solution. Is this planned, or is there a reason why the rc API is limited to a subset of the functionality exposed on the command line?

**Comment by darthShadow** [comment]
I believe this was added recently by @ncw to the master branch and consequently, the latest beta builds. Please try those out and let us know if there are any issues.

You can use this forum thread for any support related to the same: https://forum.rclone.org/t/passing-mount-options-like-vfs-cache-mode-when-using-rclone-rc-mount-mount/17863

**Comment by animosity22** [comment]
For clarity, let's focus on the thread as it's in the beta listed there so I can close this out.
