### ISSUE TITLE
ftp rclone sync

### ISSUE THREAD

**Issue by dry11orange** [rclone/rclone#4457]
#### What is the problem you are having with rclone?

download from ftp server
rclone sync

server file changed but not download
the file content is a number changed like 32 -> 33

#### What is your rclone version (output from `rclone version`)

rclone v1.51.0
- os/arch: windows/amd64
- go version: go1.13.7

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Ftp server

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone sync svn_backup:/ E:\work\backup

**Comment by animosity22** [comment]
Please use the forums for use questions and we can help there.

https://forum.rclone.org
