### ISSUE TITLE
failed: multpart copy: wrote X bytes but expected to write X + 1

### ISSUE THREAD

**Issue by filippobottega** [rclone/rclone#4459]
Error copying from WebDav to local folder.
Error:
`multi-thread copy: stream 1/2 failed: multpart copy: wrote 164560895 bytes but expected to write 164560896`

In the log I see also this error:
`Couldn't parse Date: from server 192.168.1.101:8080: "ven, 24 lug 2020 16:51:22 GMT+00:00": parsing time "ven, 24 lug 2020 16:51:22 GMT+00:00" as "Mon Jan _2 15:04:05 2006": cannot parse "ven, 24 lug 2020 16:51:22 GMT+00:00" as "Mon"`

#### What is your rclone version (output from `rclone version`)
rclone v1.52.2-246-g3286d199-beta

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
WebDav server

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone.exe copy webdav_psmart:DCIM/Camera E:\Temp\Camera

I have solved the issue running:
rclone.exe copy --multi-thread-streams 0 webdav_psmart:DCIM/Camera E:\Temp\Camera

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
See attached file:
[rclonelog.txt](https://github.com/rclone/rclone/files/4973773/rclonelog.txt)

**Comment by animosity22** [comment]
Can you try to copy one of those bad values and dump the requests and the responses? I can't tell if the server is missing sending a bit of data back or not.

**Comment by ncw** [comment]
> Error:
> `multi-thread copy: stream 1/2 failed: multpart copy: wrote 164560895 bytes but expected to write 164560896`

This kind of indicates the server has implemented the `Range` request wrong and is sending the wrong number of bytes. This is easy to do because unlike just about every other protocol when you say `Range: 0-100` you should send back 101 bytes, so sending one less is an easy to make mistake.

What is the server? Can we report a bug on it?

**Comment by filippobottega** [comment]
I'm using [Server WebDAV Pro](https://play.google.com/store/apps/details?id=com.theolivetree.webdavserverpro) on Huawei P Smart 2019.
You can use the [free](https://play.google.com/store/apps/details?id=com.theolivetree.webdavserver) version.
I suppose that the issue is only for big files like videos.

**Comment by filippobottega** [comment]
Do you have another WebDAV server for Android to suggest as alternative to  Server WebDAV Pro?

**Comment by ncw** [comment]
I dropped the author of WebDAV pro an email so we can try tracking this problem down together.

> Do you have another WebDAV server for Android to suggest as alternative to Server WebDAV Pro?

Actually rclone works on android and can act as a webdav server.

If you install [termux](https://termux.com/)

Then you can do something like

```
pkg install rclone
rclone serve webdav --addr :8080 storage
```

To run a webdav server.

That isn't as convenient as `WebDAV pro` though!

**Comment by filippobottega** [comment]
@ncw Thank you for your suggestion but using rclone with termux is not so simple: running rclone I get:
```
2020/07/27 15:17:15 NOTICE: Config file "/data/data/com.termux/files/home/.config/rclone/rclone.conf" not found - using defaults
2020/07/27 15:17:15 NOTICE: Local file system at /data/data/com.termux/files/home/storage: WebDav Server started on http://[::]:8080/

```
The problem is that in my device I'm not able to find folder /data/data/com.termux/files/home/storage.
I'll wait a patch for WebDAV pro if it will be there. In the meantime I'll use --multi-thread-streams 0 workaround.

Thank you!

**Comment by ncw** [comment]
> The problem is that in my device I'm not able to find folder /data/data/com.termux/files/home/storage.

Oh, I forgot you need to give Termux permissions to do that: https://wiki.termux.com/wiki/Termux-setup-storage





> I'll wait a patch for WebDAV pro if it will be there. In the meantime I'll use --multi-thread-streams 0 workaround.

:-)

**Comment by ivandeex** [comment]
Closing as all questions had been asnwered.
