### ISSUE TITLE
Mounting Volume with WebUI fails under macOS 10.1x

### ISSUE THREAD

**Issue by wowitsjack** [rclone/rclone#4463]
#### What is the problem you are having with rclone?

2020/07/28 00:02:52 NOTICE: Web GUI exists. Update skipped.
2020/07/28 00:02:52 NOTICE: Serving Web GUI
2020/07/28 00:02:52 NOTICE: Serving remote control on http://127.0.0.1:5572/
2020/07/28 00:02:55 ERROR : rc: "mount/listmounts": error: couldn't find method "mount/listmounts"
2020/07/28 00:03:07 ERROR : rc: "mount/listmounts": error: couldn't find method "mount/listmounts"

I've tried with both the osxfuse package from brew and the .dmg restrib from the website.

#### What is your rclone version (output from `rclone version`)
rclone v1.52.2
- os/arch: darwin/amd64
- go version: go1.14.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

macOS Mojave

####  Which cloud storage system are you using? (eg Google Drive)

The-Eye

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

Mount workflow in WebUI

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

N/A

**Comment by ncw** [comment]
> rc: "mount/listmounts": error: couldn't find method "mount/listmounts"

I think you need the beta for `mount/listmounts` it isn't in v1.52.2

**Comment by animosity22** [comment]
This looks to be answered. If you have a use question, please use the forums and we are happy to help out.

https://forum.rclone.org

Thanks!
