### ISSUE TITLE
Rclone slows the server

### ISSUE THREAD

**Issue by Easyschools** [rclone/rclone#4465]
#### What is the problem you are having with rclone?

Rclone slows my system so much that it makes my server some time down for 

#### What is your rclone version (output from `rclone version`)

rclone v1.43.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

centos

####  Which cloud storage system are you using? (eg Google Drive)

Backblaze

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone --copy-links copy /backup backblaze:easyschools-backup --local-no-check-updated --transfers 16

**Comment by animosity22** [comment]
Please use the forum for general support questions.

https://forum.rclone.org

That's a 2 year old version as well and it should be updated. You can reduce transfers if you are seeing high disk io.

**Comment by Easyschools** [comment]
when I reduced the transfer to 4. now it takes 2 days to complete the copy :/

**Comment by animosity22** [comment]
Please use the forums and use the Help and Support template.
