### ISSUE TITLE
Feature request: Add the uptobox.com backend

### ISSUE THREAD

**Issue by AlexandreBonneau** [rclone/rclone#4467]
[Uptobox.com](https://uptobox.com/) is a remote file storage website akin to 1fichier.com.
It would be great if rclone could add it in its storage providers list.

I've found a few mention of `uptobox` in the forum, [here](https://forum.rclone.org/t/1fichier-support/1995/2), [here](https://forum.rclone.org/t/upload-to-an-och-via-ftp/2972), [there](https://forum.rclone.org/t/how-can-i-upload-to-cloud-my-archives-from-external-hdd-with-raspberry-pi/1463/2) and [there](https://forum.rclone.org/t/is-it-possible-to-use-rclone-on-any-file-hosting-site/16690/6).
However since then, uptobox added an FTP backend, so you can manage your files this way.

Since uptobox is starting to become more and more popular, perhaps it could be useful for some user to add it as a storage providers? (ie. without having to specify the ftp url)

**Comment by animosity22** [comment]
Seems like they have an API:

https://docs.uptobox.com/#recent-modifications

**Comment by buengese** [comment]
If there is still interest this is something I'd be willing to implement.

**Comment by ncw** [comment]
That would be fine with me 😃

**Comment by sntran** [comment]
It probably won't affect the decision on this, but just a note that uptobox blocks access from US.

**Comment by afr-ux** [comment]
I am interesting in uptobox too. I know people that use it.
FTP in uptobox is available to upload files but is not available to browse or manage it.
API is available.

**Comment by ale4650** [comment]
esto seria muy util, mucha gente utiliza uptobox

**Comment by fonoadicto5** [comment]
como me encantaría que agregaran a uptobox!.

**Comment by jmm00044** [comment]
Deberian agregar uptobox para todos los usuarios

**Comment by KoRnEr007** [comment]
Very interested too.

**Comment by amidevous** [comment]
yes that would be really very interesting because unlike all the other systems includes uptobox and the only one not to impose any limit on the storage it would therefore allow to be able to mount a file which has no storage limit and today its would be the only host that can allow those la would it be possible to set it up very quickly complete integration via the API please as you did with 1 file thank you in advance to all

**Comment by KoRnEr007** [comment]
Any news about this topic ? 
It will be great, for the functionality "mount"

**Comment by s1dave-web** [comment]
Given the current sale prices on uptobox for unlimited storage I would also be really grateful for support to be added on rclone.

You can add as an FTP source and mount it however after file upload it keeps the folder structure but the files cannot be seen on the mount, I guess they are moved from the FTP location to some other location that can only be called with the API.

**Comment by buengese** [comment]
It's still kinda on my to-do list but I can't really give an eta. If anyone else wants to do this go ahead if not I might get to in the next few weeks.

**Comment by KoRnEr007** [comment]
@buengese lots of people wait for your dev. But we can't help you .....
Sorry

**Comment by Phaedrus-lava** [comment]
I've been using uptobox for a couple years now, and discovered rclone a few months ago.  Would be very interested in an uptobox interface for rclone, since uptobox provides unlimited storage

**Comment by wes1993** [comment]
@Phaedrus-lava 
I want to do a premium account, it's really unlimited the space for only 5€ mount?
I have 2,5TB of data.

Best Regards
Stefano

**Comment by popeye2468** [comment]
totally interested too

**Comment by buengese** [comment]
Seem to have forgotten to mention this in #5213 but Uptobox backend has been merged and is available in the current beta.

**Comment by streikpc** [comment]
VERY SLOW beta v1.56.0-beta.5505.f593558dc 
for Crypt to "uptobox", upload 50 files, 7 subfolders, 270 Mb Total., in Windows 32bits.
In download too.

rclone.exe mount uptobox_crypt:"folder_abcd" V: --vfs-cache-mode writes --allow-other --transfers 32  --vfs-cache-max-age 1m  --cache-dir "D:\path_cache"

With :
filename_encryption=standard
directory_name_encryption=true

**Comment by x3inspire** [comment]
How to add uptobox with rclone? I don't see uptobox under file host list in rclone config.

**Comment by ncw** [comment]
@x3inspire you will need to use [the latest beta](https://beta.rclone.org/)...

```
$ rclone config
...
37 / Uptobox
   \ "uptobox"
...
```

**Comment by buengese** [comment]
This is the wrong place for both of you questions. 
@x3inspire The uptobox backend is not yet available in the release version you'll have to use the [beta version](https://beta.rclone.org/). 
@streikpc Uptobox does have relatively aggressive rate limiting that make requests somewhat, so it doesn't do well with lots of small files. Using 32 transfers is also likely to be a bit much, I wouldn't recommend going past 20. Other than I've been able to pretty much max out 1gbit/s link with 16 parallel transfers of large files.

**Comment by s1dave-web** [comment]
Has been working well on my Ubuntu box just uptobox have a pretty aggressive policy on cold storage... unfortunate for me!

Really appreciate you guys working on this and making it possible.

**Comment by x3inspire** [comment]
> @x3inspire you will need to use [the latest beta](https://beta.rclone.org/)...
> 
> ```
> $ rclone config
> ...
> 37 / Uptobox
>    \ "uptobox"
> ...
> ```

Thanks, btw may i know how to mount as network drive as others?

**Comment by ncw** [comment]
This backend will be released in rclone 1.56

**Comment by xberg** [comment]
Hello,
As of January 1st I have the feeling rclone no longer works for uptobox: it copies directories but not files. Opened the issue here:
https://forum.rclone.org/t/uptobox-failed-to-copy-api-error-1-could-not-find-current-path/28284

**Comment by animosity22** [comment]
@xberg  - please don't respond to closed issue, open a new one...

**Comment by devnoname120** [comment]
@buengese 

> uptobox have a pretty aggressive policy on cold storage

Even on premium accounts? It doesn't officially state any limits. (Sorry for reviving this thread I wasn't sure how to get in touch with @buengese).
