### ISSUE TITLE
Mention support for Tencent COS cloud storage

### ISSUE THREAD

**Issue by XVilka** [rclone/rclone#4468]
#### What problem are you are trying to solve?

Currently rclone seems to have the support for Tencent COS already:

- https://cloud.tencent.com/developer/article/1520867

#### How do you think rclone should be changed to solve that?

I think it should be mentioned on the main page at https://rclone.org/#providers with a link to suitable configuration.

#### Related issues:
- https://github.com/rclone/rclone/issues/3490
- https://github.com/rclone/rclone/issues/4094

**Comment by XVilka** [comment]
@konakonall @ncw thank you!

**Comment by ncw** [comment]
This might need some more tweaks for Tencent COS... but now there is a provider it is easy to hang them off.
