### ISSUE TITLE
Feature request: rclone mount: --vfs-cache-mode writesandbackgroundreads

### ISSUE THREAD

**Issue by robinostlund** [rclone/rclone#4470]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.52.1-DEV
- os/arch: linux/amd64
- go version: go1.13.11

#### What problem are you are trying to solve?
I am using rclone to mount a folder to google drive for videos. I am currently using --vfs-cache-mode writes to cache the writes. But i would also like to cache the videos that is currently playing, but without --vfs-cache-mode full so it starts faster.

#### How do you think rclone should be changed to solve that?
Implement a new cache mode that supports to sync the whole file from the remote in the background while it is playing to support faster seeks. So when it has synced the video to the cache it starts to read from that instead of the remote.

Hope i made a good description, feel free to ask for more information :)

**Comment by darthShadow** [comment]
Use the latest beta and try again. ncw recently did an overhaul of the vfs full-mode caching so it doesn't need to download the whole file before starting to read from it.

Please go through the latest posts on this thread: https://forum.rclone.org/t/testing-for-new-vfs-cache-mode-features/16905 for any help with the same.
