### ISSUE TITLE
Azure Blob Storage - Modified Time

### ISSUE THREAD

**Issue by Whivel** [rclone/rclone#4473]
https://github.com/rclone/rclone/blob/3daa63cae8fa39c6a20c30a4db2dc79bbecf49e0/backend/azureblob/azureblob.go#L1138

Shouldn't rclone use "mtime" metadata instead of "LastModified" property when mtime is set?

**Comment by animosity22** [comment]
Questions are best on the forums:

https://forum.rclone.org rather than opening an issue.

**Comment by Whivel** [comment]
I tought that was an issue because rclone store the last modified file time in mtime metadata but it doesn't use that for operation like sync

**Comment by ncw** [comment]
Note that the line you pointed out is just in case the `mtime` medatata is missing. That is read here

https://github.com/rclone/rclone/blob/3daa63cae8fa39c6a20c30a4db2dc79bbecf49e0/backend/azureblob/azureblob.go#L1086

**Comment by ncw** [comment]
... So I think this is all OK and I'll close the issue.
