### ISSUE TITLE
b2: get rid of "upload cutoff: 200M is less than chunk size 1G" error as it is unecessary

### ISSUE THREAD

**Issue by Hescominsoon** [rclone/rclone#4475]
I am using FreeNAS 11.4.1 and I have having issues with rclone and B2.  

first is this error:
2020/07/30 18:40:54 ERROR : \mjdc01backup: Failed to copy: "\\mjdc01backup.bin" too big (8798240510000 bytes) makes too many parts 41954 > 10000 - increase --b2-chunk-size

so then i tried to raise the chink size to 1 gigabyte and i get this:
2020/07/30 18:47:31 Failed to create file system for "remote:mjcres/": b2: upload cutoff: 200M is less than chunk size 1G

**Comment by animosity22** [comment]
Please use the forums for any use questions:

http://forum.rclone.org

**Comment by Hescominsoon** [comment]
this isn't a usability question.....

**Comment by animosity22** [comment]
You are asking how to use rclone to configure a few settings.

You neglected to spend the time to fill out the template which asks for key information so the forums is a better spot.

Issues are for when you find a bug with the rclone or a feature request.

Please use the forums and use the "Help and Support" template and fill that out and we're happy to help.

**Comment by ncw** [comment]
We had a discussion about this on the forum

https://forum.rclone.org/t/b2-errors-and-uploads/18214

I think there is a usability problem here - there is no reason why the b2 backend shouldn't increase the upload cutoff automatically so I'll re-purpose this issue for that.

**Comment by ncw** [comment]
I've had a go at fixing this here so it should be no longer necessary to supply `--b2-upload-cutoff 1G` when using `--b2-chunk-size 1G`

Can you give this a test @Hescominsoon - thanks

[v1.52.2-278-g4584d4cf-fix-4475-b2-upload-cutoff-beta](https://beta.rclone.org/branch/v1.52.2-278-g4584d4cf-fix-4475-b2-upload-cutoff-beta/) on branch [fix-4475-b2-upload-cutoff](https://github.com/rclone/rclone/tree/fix-4475-b2-upload-cutoff) (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.55
