### ISSUE TITLE
Rclone creating versions also on "sync" command

### ISSUE THREAD

**Issue by Dibbyo456** [rclone/rclone#4478]
According to the [OneDrive docs](https://rclone.org/onedrive/):

> Every change in OneDrive causes the service to create a new version. This counts against a users quota. For example changing the modification time of a file creates a second version, so the file is using twice the space.
> 
> The copy is the only rclone command affected by this as we copy the file and then afterwards set the modification time to match the source file.

As it states **copy** is the only rclone command affected by this but on testing I found that "sync" command also creates versions which killing space.

![firefox_2020-08-02_08-41-02](https://user-images.githubusercontent.com/18257605/89114601-f0037800-d49b-11ea-98ae-19305e38a809.png)

I'm copying/syncing large files (4-5 Gb), imagine how much storage getting wasted for this. Can't disable versioning either because Microsoft disabled the option.

```
harry@ubuntu16:~/scripts/foo$ rclone sync . sod20:foodir -vv
2020/08/02 08:30:39 DEBUG : rclone: Version "v1.52.2-DEV" starting with parameters ["rclone" "sync" "." "sod20:foodir" "-vv"]
2020/08/02 08:30:41 DEBUG : testfile.zip: Sizes differ (src 264432 vs dst 269609)
2020/08/02 08:30:41 DEBUG : One drive root 'foodir': Waiting for checks to finish
2020/08/02 08:30:41 DEBUG : One drive root 'foodir': Waiting for transfers to finish
2020/08/02 08:30:41 DEBUG : testfile.zip: Starting multipart upload
2020/08/02 08:30:42 DEBUG : testfile.zip: Uploading segment 0/264432 size 264432
2020/08/02 08:30:44 DEBUG : testfile.zip: QuickXorHash = 9a19d8cc0a147110f30fee3deb2c2646dbd13c07 OK
2020/08/02 08:30:44 INFO  : testfile.zip: Copied (replaced existing)
2020/08/02 08:30:44 DEBUG : Waiting for deletions to finish
2020/08/02 08:30:44 DEBUG : 8 go routines active
```

For this issue OneDrive is pretty much unusable for me. The only solution I can think of is **delete old versions after each file updated** using [Saoneth's method](https://github.com/rclone/rclone/issues/4106#issuecomment-650373657).

**Comment by ncw** [comment]
I think setting the modification time counts as creating an extra version which is the problem here.

I think this issue is probably a duplicate of https://github.com/rclone/rclone/issues/1716 - what do you think?

**Comment by Dibbyo456** [comment]
> I think setting the modification time counts as creating an extra version which is the problem here.

Yes + if a file actually changed then OneDrive for Business also creates versions. I thought extra versions won't count against user storage but I was wrong. This issue is also a duplicate of #4106. The only solution is right now is remove the old versions **after the file is updated** preferably with a additional flag if not by default. 

### For listing versions for a item:

```
https://graph.microsoft.com/v1.0/drives/${DRIVE_ID}/items/${ITEM_ID}/versions
```

### For deleting a version:
```
https://graph.microsoft.com/v1.0/drives/${DRIVE_ID}/items/${ITEM_ID}/versions/${VERSION_ID}
```

**Comment by Cnly** [comment]
Yes, deleting new versions after us seems a plausible (and the only) solution. We also talked about that in #4106, so I'd prefer we continue the conversation back there. By the way @Dibbyo456 would you like to work on a PR for this?

**Comment by Dibbyo456** [comment]
I realized that it is a duplicate after creating the issue. I wish i could help but not a go programmer. :/ Closing it in favor of #4106
