### ISSUE TITLE
Add Tencent COS to provider list

### ISSUE THREAD

**Issue by konakonall** [rclone/rclone#4480]
[Tencent COS](https://intl.cloud.tencent.com/document/product/436) is a popular cloud object storage service, and is [fully compatible with S3](https://intl.cloud.tencent.com/document/product/436/32537). User can easily use the similar configuration, to make COS worked with rclone. How about add COS to the provider list ?

**Comment by XVilka** [comment]
See:
- https://github.com/rclone/rclone/issues/4468
- https://github.com/rclone/rclone/issues/4094
- https://github.com/rclone/rclone/issues/3490

**Comment by animosity22** [comment]
Duplicate Closing.

**Comment by ncw** [comment]
If someone would like to add a provider for Tencent COS then that would be great.
