### ISSUE TITLE
Rclone Failed to remove content from GCP bucket

### ISSUE THREAD

**Issue by ammad-khalid** [rclone/rclone#4481]
Hi,

I am having an issue with rclone, When i tried to remove content from mounted drive (using rclone), the content wont get removed from gcp bucket. could anyone please assist why is it not removing content from GCP bucket. I have used following command to mount the bucket:

rclone mount remote:[bucket_name] X: --vfs-cache-mode full --vfs-cache-max-age=0m --allow-other -v

In logs it showed that content is removed. This just remove the content from the mounted drive not from the bucket which results in showing the content again in the mounted drive.

**Comment by animosity22** [comment]
You already have a forum post and on the github issue, you neglected to fill in the template as well. We'll use the forum post.
