### ISSUE TITLE
Unable to build on Windows 7x64

### ISSUE THREAD

**Issue by Kein** [rclone/rclone#4484]
#### What is the problem you are having with rclone?
Unable to build on Windows

#### What is your rclone version (output from `rclone version`)
None

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 7x64

####  Which cloud storage system are you using? (eg Google Drive)
None

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`go build`

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
n:\rclone>go build
# runtime/internal/atomic
c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64x.go:18:6: Load redeclared in this block
        previous declaration at c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64.go:16:24
c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64x.go:24:6: Loadp redeclared in this block
        previous declaration at c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64.go:22:32
c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64x.go:30:6: Load64 redeclared in this block
        previous declaration at c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64.go:28:26
c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64x.go:36:6: LoadAcq redeclared in this block
        previous declaration at c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64.go:34:27
c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64x.go:41:6: Xadd redeclared in this block
        previous declaration at c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64.go:39:37
c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64x.go:44:6: Xadd64 redeclared in this block
        previous declaration at c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64.go:42:39
c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64x.go:47:6: Xadduintptr redeclared in this block
        previous declaration at c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64.go:45:47
c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64x.go:50:6: Xchg redeclared in this block
        previous declaration at c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64.go:48:36
c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64x.go:53:6: Xchg64 redeclared in this block
        previous declaration at c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64.go:51:38
c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64x.go:56:6: Xchguintptr redeclared in this block
        previous declaration at c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64.go:54:45
c:\Programs\GO\src\runtime\internal\atomic\atomic_amd64x.go:56:6: too many errors
```
## go version
```
n:\rclone>go version
go version go1.14.6 windows/amd64
```
## Additional info

This looks like GO issue? Problem is  I'm not sure what the nature of it and what to report to GO team

**Comment by animosity22** [comment]
Just for curiosity, what's the reason for the build and not just grabbing the binary? Windows 7 is out of support as well.

**Comment by darthShadow** [comment]
This may be helpful: https://stackoverflow.com/a/60448769/3476387

**Comment by Kein** [comment]
>  what's the reason for the build

I don't understand the implication of contempt in this question. Did we really reach the point where compiling the open-source product under windows is a hipster thing to do and frowned upon?
Anyway, I try to compile `go` project when I can. Here are some fun stats:
* go projects failed to compile so far on windows: 1 (this one, but issue is on my side)
* other lang projects failed to compile so far on windows: close to 90%, 70% after all dependency solved

> Windows 7 is out of support as well.

M$ still supplies 3years of ESU updates.

@darthShadow 
It was exceptionally helpful my friend, thank you!

**Comment by animosity22** [comment]
> I don't understand the implication of contempt in this question. Did we really reach the point where compiling the open-source product under windows is a hipster thing to do and frowned upon?

Huh? I asked because I was "curious" and wanted to expand my knowledge . Not sure why you are jumping to a conclusion and being aggressive as it's really not needed.
