### ISSUE TITLE
Docker - RC API Inaccessible

### ISSUE THREAD

**Issue by TaylorDale** [rclone/rclone#4486]
#### What is the problem you are having with rclone?
Unable to use the RC API, relatively following along with instructions from the docs.

#### What is your rclone version (output from `rclone version`)
v1.52.2

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
sudo docker run -d -p 5572:5572   rclone/rclone:latest rcd --rc-no-auth

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2020/08/04 05:46:31 DEBUG : rclone: Version "v1.52.2" starting with parameters ["rclone" "rcd" "--rc-no-auth" "-vv"]
2020/08/04 05:46:31 NOTICE: Serving remote control on http://127.0.0.1:5572/

Getting the current output: 
```
 curl -v -X POST 'http://127.0.0.1:5572/rc/noop?potato=1&sausage=2'
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 5572 failed: Connection refused
* Failed to connect to 127.0.0.1 port 5572: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 127.0.0.1 port 5572: Connection refused
```

I'm not sure what I'm missing, I know there are no remotes or config in this setup but when I run docker ps the docker container is running fine, and I'm only passing test params so I'd expect something atleast other than a connection error.

Thanks

**Comment by darthShadow** [comment]
If you are running rclone within a container, you need to make it listen on all interfaces via `--rc-addr=0.0.0.0:5572` in order to connect from outside the container.

Explanation about why this is necessary: https://pythonspeed.com/articles/docker-connection-refused/

**Comment by TaylorDale** [comment]
> If you are running rclone within a container, you need to make it listen on all interfaces via `--rc-addr=0.0.0.0:5572` in order to connect from outside the container.
> 
> Explanation about why this is necessary: https://pythonspeed.com/articles/docker-connection-refused/

Ah great thanks for that & the explanation - I have not had to do this before to get a webserver inside a docker container working but glad there is a fix.

**Comment by ncw** [comment]
> If you are running rclone within a container, you need to make it listen on all interfaces via `--rc-addr=0.0.0.0:5572` in order to connect from outside the container.

This should maybe go in the docs somewhere? Maybe in the docker install section?

What did you think @darthShadow ?

**Comment by darthShadow** [comment]
Sure, will send a PR shortly to update the docs.
