### ISSUE TITLE
An issue via drive using Plex scan

### ISSUE THREAD

**Issue by raenoll** [rclone/rclone#4487]
#### What is the problem you are having with rclone?

After doing plex scan for a long time, rclone mount using drive faied frequently and logged 
Fatal error: Can not open: /xxx: open /xxx: transport endpoint is not connected

#### What is your rclone version (output from `rclone version`)

1.51.0 looks fine for a long time. This problem occurred starting after being updated to 1.52.2 and v1.52.2-276-gc2f3949d-beta which I've tested. Now I rolled back to 1.51.0 and so far so good.

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian 10

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

No direct command. Plex - Scan a library or Auto scan in Plex Media Server

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

No direct command.

**Comment by darthShadow** [comment]
Please add the remaining details requested in the bug template i.e. the command & debug logs.

**Comment by raenoll** [comment]
> Please add the remaining details requested in the bug template i.e. the command & debug logs.

Updated

**Comment by darthShadow** [comment]
Please specify the rclone mount command that you are using and the debug logs that are generated by rclone when you run a Plex scan and the rclone mount stops.

You can use the [--log-file](https://rclone.org/docs/#log-file-file) and [--log-level](https://rclone.org/docs/#log-level-level) arguments to create a logfile.

**Comment by raenoll** [comment]
> Please specify the rclone mount command that you are using and the debug logs that are generated by rclone when you run a Plex scan and the rclone mount stops.
> 
> You can use the [--log-file](https://rclone.org/docs/#log-file-file) and [--log-level](https://rclone.org/docs/#log-level-level) arguments to create a logfile.

rclone mount

ExecStart=/usr/bin/rclone mount GoogleDrive: /xxx \
--allow-other \
--dir-cache-time 96h \
--log-level INFO \
--log-file /root/.config/rclone/logs/rclone.log \
--poll-interval 15s \
--timeout 1h \
--umask 002

rclone.log

2020/08/01 01:25:13 Fatal error: Can not open: /xxx: open /xxx: transport endpoint is not connected

**Comment by darthShadow** [comment]
We need the logs the caused the issue, not when the issue has already happened. So please, run the mount with the log-file and log-level arguments (with `--log-level` set to `DEBUG`) and try to reproduce the issue and send that log file.

**Comment by raenoll** [comment]
> We need the logs the caused the issue, not when the issue has already happened. So please, run the mount with the log-file and log-level arguments (with `--log-level` set to `DEBUG`) and try to reproduce the issue and send that log file.

OK. This may take some time in my test environment. I'll report later. I didn't keep the last huge debug log file.

**Comment by animosity22** [comment]
Can you post your service file?

The error you posted is something else killing rclone majority of the time.

**Comment by raenoll** [comment]
> Can you post your service file?
> 
> The error you posted is something else killing rclone majority of the time.

rclone.service

```
[Unit]
Description=RClone Service
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
Environment=RCLONE_CONFIG=/root/.config/rclone/rclone.conf
RestartSec=5
ExecStart=/usr/bin/rclone mount GoogleDrive: /var/lib/plexmediaserver/gd \
--allow-other \
--dir-cache-time 96h \
--log-level DEBUG \
--log-file /root/.config/rclone/logs/rclone.log \
--poll-interval 15s \
--timeout 1h \
--umask 002
ExecStop=/bin/fusermount -uz /var/lib/plexmediaserver/gd
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

**Comment by animosity22** [comment]
Check your journalctl log for that service and see if it has been restarted by systemd.

Without a KillMode=none, it'll kill the process and leave it in a bad state with the error you posted.

**Comment by raenoll** [comment]
> Check your journalctl log for that service and see if it has been restarted by systemd.
> 
> 
> 
> Without a KillMode=none, it'll kill the process and leave it in a bad state with the error you posted.
> 
> 
> 
> 

But it's ok with V1.51.0. I'm trying to reproduce again with V1.52.2.

**Comment by animosity22** [comment]
It's the process being killed as it would happen on any version.

**Comment by raenoll** [comment]
I can't find any detail about rclone service altered by system right now. I'll keep a eye on it.

**Comment by raenoll** [comment]
> We need the logs the caused the issue, not when the issue has already happened. So please, run the mount with the log-file and log-level arguments (with `--log-level` set to `DEBUG`) and try to reproduce the issue and send that log file.

I succeeded to reproduce and saved a recent small-log-file generated by rclone v1.52.2. I can provide large log-file in detail if needed.
[rclone0805.log](https://github.com/rclone/rclone/files/5026299/rclone0805.log)

**Comment by darthShadow** [comment]
Ok, there isn't anything that seems obviously wrong from the log. I assume this is the last few lines from the complete log?

Anything in the systemd journal about restarts etc.?

**Comment by raenoll** [comment]
> Ok, there isn't anything that seems obviously wrong from the log. I assume this is the last few lines from the complete log?

Yes

> 
> Anything in the systemd journal about restarts etc.?

I didn't find anything abnormal in journalctl.

**Comment by animosity22** [comment]
Can you share the journalctl log?

You need to figure out what's killing rclone on the system.

**Comment by raenoll** [comment]
I may run another test to save journal logs in detail in the near future. Right now I rolled back to V1.51.0 and it works smoothly.

**Comment by animosity22** [comment]
With no logs to look at, there isn't much help to offer unfortunately. 

I'd suggest if you aren't going to recreate it, just close it out as this is really a forum question anyway.

If you share some logs, I'm happy to look through them.

**Comment by raenoll** [comment]
> With no logs to look at, there isn't much help to offer unfortunately.
> 
> I'd suggest if you aren't going to recreate it, just close it out as this is really a forum question anyway.
> 
> If you share some logs, I'm happy to look through them.

Aug 06 07:10:43 localhost systemd[1]: rclone.service: Main process exited, code=killed, status=9/KILL
Aug 06 07:10:43 localhost systemd[1]: rclone.service: Failed with result 'signal'.
Aug 06 07:10:48 localhost systemd[1]: rclone.service: Service RestartSec=5s expired, scheduling restart.
Aug 06 07:10:48 localhost systemd[1]: rclone.service: Scheduled restart job, restart counter is at 1.
Aug 06 07:10:48 localhost systemd[1]: Stopped RClone Service.
Aug 06 07:10:48 localhost systemd[1]: Starting RClone Service...
Aug 06 07:10:48 localhost systemd[1]: rclone.service: Main process exited, code=exited, status=1/FAILURE
Aug 06 07:10:48 localhost systemd[1]: rclone.service: Failed with result 'exit-code'.
Aug 06 07:10:48 localhost systemd[1]: Failed to start RClone Service.

2020/08/06 07:10:48 Fatal error: Can not open: /xxx: open /xxx: transport endpoint is not connected


I think you're right. It happened on V1.51.0 again.

**Comment by raenoll** [comment]
yesterday 2020/08/05 07:47:06
today 2020/08/06 07:10:48

I set background maintenance tasks between 1am-8am in plex media server.

**Comment by animosity22** [comment]
> Aug 06 07:10:43 localhost systemd[1]: rclone.service: Main process exited, code=killed, status=9/KILL

So if the process is killed, you get the error you've described. You can put systemd in debug mode to see what's causing it to be killed as I don't believe it shows by default what is happening.

Are you running out of memory or something? From the rclone logs, rclone isn't stopping itself from what I can tell.

**Comment by raenoll** [comment]
> > Aug 06 07:10:43 localhost systemd[1]: rclone.service: Main process exited, code=killed, status=9/KILL
> 
> So if the process is killed, you get the error you've described. You can put systemd in debug mode to see what's causing it to be killed as I don't believe it shows by default what is happening.
> 
> Are you running out of memory or something? From the rclone logs, rclone isn't stopping itself from what I can tell.

After upgrading to dedicated server, I haven't got "out of memory" for a long time.

I'm trying to put systemd in debug mode and/or double the memory to test again.

**Comment by raenoll** [comment]
> So if the process is killed, you get the error you've described. You can put systemd in debug mode to see what's causing it to be killed as I don't believe it shows by default what is happening.

I added 

Environment=SYSTEMD_LOG_LEVEL=debug

to rclone.service

Is it enough to make rclone.service in debug mode? Or need I edit systemd.conf?

**Comment by animosity22** [comment]
If you check your journal output, that would validate if it's working or not.

**Comment by raenoll** [comment]
> yesterday 2020/08/05 07:47:06
> 
> today 2020/08/06 07:10:48
> 

My server was reboot once and I can't reproduce it today as expected. It seems like not related to memory.

I will close this if nothing happens tomorrow.

**Comment by animosity22** [comment]
I can't think of anything offhand that would cause systemd to stop it. Your service file only refers to the networking service and assuming the networking isn't stopping, there isn't anything else obvious.



> Aug 06 07:10:43 localhost systemd[1]: rclone.service: Main process exited, code=killed, status=9/KILL

That line makes me systemd tried to stop it and without KillMode=none, it'll sigkill the process.

I have kill mode in my service to avoid that:

```
[Service]
Type=notify
Environment=RCLONE_CONFIG=/opt/rclone/rclone.conf
KillMode=none
RestartSec=5
```

**Comment by raenoll** [comment]
OK. I'll try KillMode. Thanks.

**Comment by ncw** [comment]
It would be worth checking `dmesg` and `/var/log/kern.log` to see if there are any messages from the out of memory killer in there.

Something killed rclone with signal SIGKILL -9 - this is most likely the out of memory killer - I'm pretty sure systemd will kill with SIGTERM -15 if it needs to get rid of something and only fall back to SIGKILL -9 if the process didn't die within a reasonable time.

**Comment by animosity22** [comment]
Systemd really can't stop rclone as if you are running and you fusermount it and it has things accessing it, it never unmounts and eventually if KillMode != none, it sigkills it nice first and eventually with -9 to end it.

**Comment by raenoll** [comment]
> 2020/08/01 01:25:13 Fatal error: Can not open: /xxx: open /xxx: transport endpoint is not connected

kern.log

Aug  1 01:25:07 localhost kernel: [4461407.663290] Out of memory: Kill process 20759 (rclone) score 290 or sacrifice child
Aug  1 01:25:07 localhost kernel: [4461407.668027] Killed process 20759 (rclone) total-vm:2183172kB, anon-rss:1324112kB, file-rss:0kB, shmem-rss:0kB
Aug  1 01:25:08 localhost kernel: [4461407.847230] oom_reaper: reaped process 20759 (rclone), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

**Comment by raenoll** [comment]
> Aug 06 07:10:43 localhost systemd[1]: rclone.service: Main process exited, code=killed, status=9/KILL
> Aug 06 07:10:43 localhost systemd[1]: rclone.service: Failed with result 'signal'.
> Aug 06 07:10:48 localhost systemd[1]: rclone.service: Service RestartSec=5s expired, scheduling restart.
> Aug 06 07:10:48 localhost systemd[1]: rclone.service: Scheduled restart job, restart counter is at 1.
> Aug 06 07:10:48 localhost systemd[1]: Stopped RClone Service.
> Aug 06 07:10:48 localhost systemd[1]: Starting RClone Service...
> Aug 06 07:10:48 localhost systemd[1]: rclone.service: Main process exited, code=exited, status=1/FAILURE
> Aug 06 07:10:48 localhost systemd[1]: rclone.service: Failed with result 'exit-code'.
> Aug 06 07:10:48 localhost systemd[1]: Failed to start RClone Service.
> 
> 2020/08/06 07:10:48 Fatal error: Can not open: /xxx: open /xxx: transport endpoint is not connected

kern.log

Aug  6 07:10:43 localhost kernel: [4914151.315700] Out of memory: Kill process 5560 (rclone) score 231 or sacrifice child
Aug  6 07:10:43 localhost kernel: [4914151.317200] Killed process 5560 (rclone) total-vm:1433820kB, anon-rss:1055240kB, file-rss:0kB, shmem-rss:0kB
Aug  6 07:10:43 localhost kernel: [4914151.402137] oom_reaper: reaped process 5560 (rclone), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

**Comment by raenoll** [comment]
So I should add more memory to the server to avoid this?

**Comment by animosity22** [comment]
Yes or reduce settings in rclone.

The logs didn't have any mount commands so not sure what you are running.

**Comment by raenoll** [comment]
REASON: "Out of memory" to make rclone killed by system from kern.log, but no "out of memory" in debug mode of rclone.log.

SOLUTION: Add memory or optimize memory usage.

SERVER Debian 10, 4G Memory, rclone 1G on average.

**Comment by animosity22** [comment]
> but no "out of memory" in debug mode of rclone.log.

RClone never ran out of memory as it was killed before it did which is why there was no log entry.

**Comment by raenoll** [comment]
I saw "out of memory" in rclone.log several times when there was 2G memory installed, but none in 4G like this time.

**Comment by animosity22** [comment]
I'm not following as you contradicted your other statement where you said there were no out of memory errors in the logs.

If rclone ran out of memory, it would log it in the log.
If the system OOM killer ran, it would not be in the log.

In either event, it's a server sizing or rclone configuration issue.

**Comment by raenoll** [comment]
Last time when I saw "out of memory" in rclone.log, I doubled the memory and the problem was solved.

This time I follow that lead I don't think it's a memory issue if there is no "out of memory" in it.

**Comment by ncw** [comment]
The most common cause of out of memory with rclone is having --buffer-size set too big. Can you check that?

**Comment by raenoll** [comment]
> The most common cause of out of memory with rclone is having --buffer-size set too big. Can you check that?

I may set wrong parameter in early days. But recently I don't set any buffer in this server, all to default.

--allow-other \
--dir-cache-time 96h \
--log-level INFO \
--log-file /root/.config/rclone/logs/rclone.log \
--poll-interval 15s \
--timeout 1h \
--umask 002

**Comment by raenoll** [comment]
Process History: rclone (Past 12h)

<img width="523" alt="rclone" src="https://user-images.githubusercontent.com/6948577/89702470-25183a80-d974-11ea-8c89-f1b1ceca1cf6.png">

**Comment by ncw** [comment]
Looks ok now?

**Comment by raenoll** [comment]
OK for now. I rebooted the server once due to system upgrade since last failure. I'll monitor this if it happens again in the future.
