### ISSUE TITLE
Can't supply global parameters via RC

### ISSUE THREAD

**Issue by TaylorDale** [rclone/rclone#4489]
#### What is your current rclone version (output from `rclone version`)?
v1.53

#### What problem are you are trying to solve?
I am trying to run RClone in a docker image as part of a larger system that can backup parts of our file storage. I am trying to use the functionality that was implemented in #4419  to set the root sync to the folder Id, as I already have the ID of the particular folder I want to sync.

Currently I cannot see a way to pass the "drive-root-folder-id" param via RC. Is this a possibility with the way that RClone has been structured?

I suppose I could spin up rclone with a command but it would be much cleaner to communicate with it with the API, especially with the async job system.

#### How do you think rclone should be changed to solve that?
Add the ability to set global flags via the RC api.

**Comment by ncw** [comment]
You can set the global flags, but the flag you mentioned is a backend flag which you can't set at the moment.

You can however build a new backend over the API with this parameter in using the config/create API - does that help?

**Comment by TaylorDale** [comment]
Fantastic - this is working really well now.

There isn't a lot of practical examples of using the API in the docs so if anyone else comes across this, the following config is what I am using to clone a folder by Id, impersonating a user, with a service account, in shared drives over HTTP API:

**Create new source**
POST to :5572/config/create
```
{
	"name": "mydrive_2",
	"type": "drive",
	"parameters":{
		"client_id": "xxxxxxxxxxxxx.apps.googleusercontent.com",
		"scope": "drive",
		"service_account_file": "${RCLONE_CONFIG_DIR}/serviceaccount.json",
		"impersonate": "user@domain.com",
		"acknowledge_abuse": "true",
		"root_folder_id": "folder_id_to_clone_here"
	}
}
```

**Download the folder**
POST to :5572/sync/copy
```
{
	"srcFs": "mydrive_2:",
	"dstFs": "/data/test_copy"
}
```

**Comment by ncw** [comment]
Glad it is working and thanks for the notes on how you achieved it!

**Comment by TaylorDale** [comment]
Hi @ncw I'm trying to supply the create-empty-src-dirs flag to the backend, I've tried 1) passing it as a param when the remote is created (in both the parameters section, and the first level of the json) as such : 
```
{name: 'mydrive', type: 'drive', create-empty-src-dirs: true, parameters: {...}}
```

And I've also tried supplying it as a key in the sync/copy call to no avail. Any hints?

**Comment by ncw** [comment]
> I'm trying to supply the create-empty-src-dirs flag to the backend

Annoyingly this is a flag directly on the sync/move/copy commands rather than a global flag, and I don't think it is possible to set it at the moment.

This is definitely an oversight!

Because it is a parameter of sync/move/copy it should really go in the options for [operations/sync](https://rclone.org/rc/#sync-copy) etc

Which of `sync` `copy` `move` are you using?

**Comment by ivandeex** [comment]
@TaylorDale ?

> Which of `sync`  `copy` `move` are you using?

**Comment by ivandeex** [comment]
@TaylorDale 

> Which of `sync` `copy` `move` are you using?

**Comment by TaylorDale** [comment]
It's been a while since I worked on this but I believe it was copy? Definitely not move.

**Comment by ncw** [comment]
Thanks!

It looks like this feature is here, but it just isn't documented!

Try adding `"createEmptySrcDirs": true` to your rc command POST - that should work!

I'll fix the docs

**Comment by TaylorDale** [comment]
Awesome! Appreciate you following up.
