### ISSUE TITLE
ncdu: configuration password required to ncdu local files

### ISSUE THREAD

**Issue by leoccyao** [rclone/rclone#4492]
#### What is your current rclone version (output from `rclone version`)?

```
$ rclone -V
rclone v1.52.2
- os/arch: windows/amd64
- go version: go1.14.4
```

#### What problem are you are trying to solve?

I find the `rclone ncdu` command useful not only for looking through my remote filesystems, but also for analyzing storage on my local filesystem. However, the command asks for my configuration password even when running ncdu on a local folder, which is suboptimal.

#### How do you think rclone should be changed to solve that?

Add a check for if the target filesystem is the local filesystem, and go directly to the ncdu interface if it is (should still prompt for password for crypt I suppose)

**Comment by ncw** [comment]
Unfortunately rclone looks for config parameters of the local: backend for local paths so this isn't possible without losing the ability to configure the local backend.

**Comment by animosity22** [comment]
Just make a new remote with only the local and call that via --config instead.

**Comment by animosity22** [comment]
This looks to be answered so closing out.
