### ISSUE TITLE
vfs (writes) cache grows larger than vfs-cache-max-size

### ISSUE THREAD

**Issue by shawnbarton** [rclone/rclone#4498]
#### What is the problem you are having with rclone?

I have two system services. Each mounts a Google Drive remote using the rclone mount command and parameters below. Both mounts use the same base directory for the VFS writes cache. The sub-directories and files in each mount are uniquely named. These directories are used by Plex Media Server.

Each mount is allowed a maximum 256G cache per the specified parameters, however, the directory size has grown larger than this limit.

567G    /srv/rclone_cache/vfs/mount1
33G     /srv/rclone_cache/vfs/mount2

#### What is your rclone version (output from `rclone version`)

rclone v1.52.2
- os/arch: linux/amd64
- go version: go1.14.4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Ubuntu 18.04 LTS

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive (Team Drives)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

/usr/bin/rclone mount remote1:path/to/mount1 --gid=1000 \
        --uid=1000 \
        --allow-other \
        --cache-dir /srv/rclone_cache/ \
        --dir-cache-time 168h \
        --vfs-cache-mode writes \
        --vfs-read-chunk-size 32M \
        --vfs-read-chunk-size-limit 512M \
        --vfs-cache-max-age 730h \
        --vfs-cache-max-size 256G \
        --buffer-size 16M \
        --use-mmap \
        --log-level INFO \
        --log-file /var/log/mount1.log \
        --umask 0

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

(some INFO level logs for the larger mount1, since I have not been able to get debug logs yet)

2020/08/11 17:18:38 INFO  : Cleaned the cache: objects 327 (was 327), total size 561.103G (was 560.348G)
2020/08/11 17:19:38 INFO  : Cleaned the cache: objects 327 (was 327), total size 563.624G (was 561.103G)
2020/08/11 17:20:38 INFO  : Cleaned the cache: objects 327 (was 327), total size 563.624G (was 563.624G)
2020/08/11 17:21:03 INFO  : path/to/newfile1.mkv: Copied (new)
2020/08/11 17:21:38 INFO  : Cleaned the cache: objects 328 (was 328), total size 565.661G (was 563.624G)
2020/08/11 17:22:38 INFO  : Cleaned the cache: objects 328 (was 328), total size 566.901G (was 565.661G)
2020/08/11 17:23:38 INFO  : Cleaned the cache: objects 328 (was 328), total size 566.901G (was 566.901G)
2020/08/11 17:23:48 INFO  : path/to/newfile2.mkv: Copied (new)
2020/08/11 17:24:38 INFO  : Cleaned the cache: objects 328 (was 328), total size 566.901G (was 566.901G)
2020/08/11 17:25:38 INFO  : Cleaned the cache: objects 328 (was 328), total size 566.901G (was 566.901G)
2020/08/11 17:26:38 INFO  : Cleaned the cache: objects 328 (was 328), total size 566.901G (was 566.901G)
2020/08/11 17:27:38 INFO  : Cleaned the cache: objects 328 (was 328), total size 566.901G (was 566.901G)
2020/08/11 17:28:38 INFO  : Cleaned the cache: objects 328 (was 328), total size 566.901G (was 566.901G)
2020/08/11 17:29:38 INFO  : Cleaned the cache: objects 328 (was 328), total size 566.901G (was 566.901G)
2020/08/11 17:30:38 INFO  : Cleaned the cache: objects 328 (was 328), total size 566.901G (was 566.901G)

**Comment by darthShadow** [comment]
Could you also show the number of open files for the mount? Something like `lsof /path/to/mount`

**Comment by shawnbarton** [comment]
```
$ sudo lsof /mnt/point/mount1/ | wc -l
2
$ sudo lsof /mnt/point/mount2/ | wc -l
0
```

I just realized that I forgot to add that there are also Docker containers pointed at these mounts (volume mounts in docker-compose).

**Comment by darthShadow** [comment]
I assume you tried with the absolute paths? The relative paths don't work for `lsof`

**Comment by shawnbarton** [comment]
That's correct. To confirm, I removed the wc -l pipe. I can see the file in use which is actually being used at the moment.

**Comment by darthShadow** [comment]
Ok, that rules out the simplest cause. We will need the debug log to check anything else.

**Comment by shawnbarton** [comment]
I updated the service to use --log-level DEBUG and restarted it. 
That didn't do anything. I still only saw INFO in the log and cache cleaning notices as shown above.
I stopped the service again, added -vv, then started the service once more.

This time I got:
```
2020/08/11 20:06:38 INFO  : Cleaned the cache: objects 329 (was 329), total size 569.133G (was 569.133G)
2020/08/11 20:06:39 Fatal error: failed to umount FUSE fs: exit status 1: fusermount: failed to unmount /path/to/mount1: Invalid argument
2020/08/11 20:06:56 DEBUG : rclone: Version "v1.52.2" starting with parameters ["/usr/bin/rclone" "-vv" "mount" "remote1:" "/path/to/mount1" "--gid=1000" "--uid=1000" "--allow-other" "--cache-dir" "/srv/rclone_cache/" "--dir-cache-time" "168
h" "--vfs-cache-mode" "writes" "--vfs-read-chunk-size" "32M" "--vfs-read-chunk-size-limit" "512M" "--vfs-cache-max-age" "730h" "--vfs-cache-max-size" "256G" "--buffer-size" "16M" "--use-mmap" "--log-file" "/var/log/rclone-tv.log" "--umask" "0"]
2020/08/11 20:06:56 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2020/08/11 20:06:56 DEBUG : Encrypted drive 'remote1:': Mounting on "/path/to/mount1"
2020/08/11 20:06:57 DEBUG : vfs cache root is "/srv/rclone_cache/vfs/mount1"
2020/08/11 20:06:57 DEBUG : Adding path "vfs/forget" to remote control registry
2020/08/11 20:06:57 DEBUG : Adding path "vfs/refresh" to remote control registry
2020/08/11 20:06:57 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2020/08/11 20:06:57 DEBUG : : Root: 
2020/08/11 20:06:57 DEBUG : : >Root: node=/, err=<nil>
2020/08/11 20:06:57 DEBUG : subdir/file.mkv: updateTime: setting atime to 2020-08-10 01:21:28.120677246 +0200 CEST
```

The last line repeats many times for files that were in the cache. It then went on to remove various files and empty directories from the cache:
```
2020/08/11 20:06:57 INFO  : subdir/file.mkv: Removed from cache
2020/08/11 20:06:58 DEBUG : subdir: Removed empty directory
2020/08/11 20:06:58 INFO  : Cleaned the cache: objects 104 (was 0), total size 253.644G (was 0)
```

It appears to be working again. I'm not sure why, but will report back if I have any new information or if the issue recurs.

**Comment by animosity22** [comment]
If you have any more questions on this, you can always post on the forums for trouble shooting.

https://forum.rclone.org

Thanks!

**Comment by OlegVladimirov** [comment]
@darthShadow Hi! I have the similar problem.
I mount folder with a large file using command
```
sudo rclone mount cons:consensus/ /home/user1/sia-hostd/consensus/ --daemon --vfs-cache-mode minimal --vfs-cache-max-size 1G
```
This folder consist of two files and one of them really big - more then 80 Gb.
So when I'm launch application and it start using file - rclone's cached file increase more then 1G:
```
$ sudo ls -l /root/.cache/rclone/vfs/cons/consensus/consensus.db
-rw------- 1 root root 3204034560 May  1 22:36 /root/.cache/rclone/vfs/cons/consensus/consensus.db
```
So the question is - how to prevent increasing cache file size?


PS: I tried not to use cache at all with  `--vfs-cache-mode off` switch but application crashed with a message
```
failed to create consensus: write /home/user1/sia-hostd/consensus/consensus.log: illegal seek
```

**Comment by darthShadow** [comment]
This issue was closed 4 years ago. Please post on the forum if you have any issues.
