### ISSUE TITLE
Support using google team drives (all not one) as a backend

### ISSUE THREAD

**Issue by FlorianLudwig** [rclone/rclone#4506]
#### What problem are you are trying to solve?

Having multiple team drives and wanting to access them is quite hard as I need a config per team drive.

#### How do you think rclone should be changed to solve that?

Instead of having to select one team-drive:

> Choose a number from below, or type in your own value

Adding the option "0 | All drives" where the root folder is a list of team drives.

**Comment by ncw** [comment]
I'm pretty sure there is an issue about this somewhere...

It requires making a "synthetic" filesystem on top of google drive.

If we did that then we could include
- shared with me
- trashed
- team drives

All of which might be interesting.

**Comment by FlorianLudwig** [comment]
@ncw Hey, would you know someone who I could sponsor to work on this :) My go knowledge and even more my time is quite limited but I really would like to have this feature

**Comment by ncw** [comment]
@FlorianLudwig drop me an email to nick@craig-wood.com and we can discuss!

**Comment by amie33r** [comment]
Is this feature dropped? as there is no update from the past 5 months

**Comment by FlorianLudwig** [comment]
At our company we stopped using team drives, so the feature was not sponsored by us.

**Comment by amie33r** [comment]
> 
> 
> At our company we stopped using team drives, so the feature was not sponsored by us.

Don't misunderstand me, but what I asked was mounting the root folder of shared/team drives was dropped? and I never asked whether you or your company is sponsoring this

**Comment by FlorianLudwig** [comment]
It wasn't dropped - it was never implemented

**Comment by Masamune3210** [comment]
Can you not mount a team drive as root In the google drive type? I have done so before so unless it was removed or I'm mistaken of what you are wanting its already in

**Comment by amie33r** [comment]
> 
> 
> Can you not mount a team drive as root In the google drive type? I have done so before so unless it was removed or I'm mistaken of what you are wanting its already in
I haven't seen anything like that from the docs maybe you're talking about rclone union? I wanted to see whether it's possible the entire root directory from the google shared drive section using rclone. If it already exits could you please direct me as to how and what command to use? 
P.S I am not talking about rclone union where you combine two or more shared drives into a single remote.

**Comment by Masamune3210** [comment]
If you create a new gdrive remote in the creation process it asks you if you want to mount a team drive instead of the normal root. Unless you are talking about shared folders, and not team drives like I think you are. You simply answer yes and then it gives you a list of all the team drives you are a member of

**Comment by bulls23nt** [comment]
I think he means he wants to add his google drive as 1 remote but get this folder structure which is what you get with google’s client on your computer:

My Drive
        |---------Your Drive Contents
Shared Drives
        |---------Shared Drive 1
                                  |-----------Shared Drive 1 Contents
        |---------Shared Drive 2
                                  |-----------Shared Drive 2 Contents

[https://i0.wp.com/www.systoolsgroup.com/updates/wp-content/uploads/2018/03/1.png?resize=650,400](url)

**Comment by FlorianLudwig** [comment]
@bulls23nt thanks. Yes, that is exactly what this issue is about.

If you are having a different issue, please open a new one.

**Comment by amie33r** [comment]
> 
> 
> I think he means he wants to add his google drive as 1 remote but get this folder structure which is what you get with google’s client on your computer:
> 
> My Drive
> |---------Your Drive Contents
> Shared Drives
> |---------Shared Drive 1
> |-----------Shared Drive 1 Contents
> |---------Shared Drive 2
> |-----------Shared Drive 2 Contents
> 
> https://i0.wp.com/www.systoolsgroup.com/updates/wp-content/uploads/2018/03/1.png?resize=650,400

Yes but not the my drive only the shared drives, thanks for making it clear.
If people still don't understand my plight, here is what I wanted rclone to
> Shared Drives
> |---------Shared Drive 1
> |-----------Shared Drive 1 Contents
> |---------Shared Drive 2
> |-----------Shared Drive 2 Contents
> |----------Shared Drive3
> |-------------Shared Drive 3 Contents
and so on.
P.S I know there alternatives available on the internet but many of them are paid ones and there is freemium one which displays ads whenever I open the program

**Comment by xavierxross** [comment]
> If people still don't understand my plight, here is what I wanted rclone to
> 
> > Shared Drives
> > |---------Shared Drive 1
> > |-----------Shared Drive 1 Contents
> > |---------Shared Drive 2
> > |-----------Shared Drive 2 Contents
> > |----------Shared Drive3
> > |-------------Shared Drive 3 Contents
> > and so on.
> 
it would be the best feature to add. Helpful for people managing many team drives. I use Airexplorer (Windows), MiXplorer (android) and some python telegram bots for cloning and managing files between various teamdrives.
> P.S I know there alternatives available on the internet but many of them are paid ones and there is freemium one which displays ads whenever I open the program

Out of many google drive mounting softwares (for windows) like raidrive,airlivedrive,netdrive,mountain duck,webdrive,cloudmounter and expandrive i've tried , RaiDrive is the best imo. Iirc raidrive started showing ads after September 22, 2020 update, I use the older ver. so no-ads. [This](https://dl.uploadgram.me/6112d242694f8g?raw)

**Comment by ncw** [comment]
As far as team drives go I had this idea...

It occurred to me that I could make an option for  `rclone backend drives drive:` which would output in config file format with the names of the drives...

I had a go at exactly this

[v1.57.0-beta.5681.c135f93dd.fix-drive-drives](https://beta.rclone.org/branch/fix-drive-drives/v1.57.0-beta.5681.c135f93dd.fix-drive-drives/) on branch [fix-drive-drives](https://github.com/rclone/rclone/tree/fix-drive-drives) (uploaded in 15-30 mins)

Use it like

    rclone backend -o config drives gdrive:

And it will output an rclone config file configuring aliases for all your team drives.

This isn't exactly what this issue is about but might be helpful.

**Comment by dandar** [comment]
> As far as team drives go I had this idea...
> 
> It occurred to me that I could make an option for `rclone backend drives drive:` which would output in config file format with the names of the drives...
> 
> I had a go at exactly this
> 
> [v1.57.0-beta.5681.c135f93dd.fix-drive-drives](https://beta.rclone.org/branch/fix-drive-drives/v1.57.0-beta.5681.c135f93dd.fix-drive-drives/) on branch [fix-drive-drives](https://github.com/rclone/rclone/tree/fix-drive-drives) (uploaded in 15-30 mins)
> 
> Use it like
> 
> ```
> rclone backend -o config drives gdrive:
> ```
> 
> And it will output an rclone config file configuring aliases for all your team drives.
> 
> This isn't exactly what this issue is about but might be helpful.

Thank you Nick. This helped me a lot.  I didn't know you can mount Google shared drives our team drives as `type = alias`.

For anyone wondering how to use
`rclone backend -o config drives gdrive:
`"gdrive" is the name of your google MyDrive in your [rclone config file](https://rclone.org/commands/rclone_config_file/).
And it will output an rclone config file configuring aliases (I didn't know you can configure team shared drives as aliases, very helpful)

Nick, can we somehow mount all remotes at once? mount some or all remotes using one mount command?
If we can wrap several remotes in one named group in the config file, then a single mount command to mount the grouped remotes would be very helpful. [Mount and unmount (in Windows Ctl-C or stop task/service, or in MacOS umount or in Linux fusermount -u)](https://rclone.org/commands/rclone_mount/#installing-on-windows) should create and delete each remote's root folder under one mount point.

**Comment by ncw** [comment]
@dandar I wrote some more docs on how to use `rclone config backend -o config drives gdrive:` here: https://rclone.org/drive/#drives

> Nick, can we somehow mount all remotes at once?

You are talking about being able to mount remotes at a given path. What we'd do is add a new `-o mount` outut which would build an rclone config for an as yet nonexistent `mount` backend, which could then show the shared drives in the right places.

**Comment by ncw** [comment]
I have made a first attempt at a `combine` backend here

[v1.59.0-beta.6081.b0c54538b.fix-5600-bind](https://beta.rclone.org/branch/fix-5600-bind/v1.59.0-beta.6081.b0c54538b.fix-5600-bind/) on branch [fix-5600-bind](https://github.com/rclone/rclone/tree/fix-5600-bind) (uploaded in 15-30 mins)

You configure it like this

```
[TestCombine]
type = combine
upstreams = dir1=/tmp/dir1 dir2=/tmp/dir2 dir3=/tmp/dir3
```

I've also added a little to `rclone backend drives -o config drive:` so it makes config which combines all the shared drives into one

With the -o config parameter it will output the list in a format
suitable for adding to a config file to make aliases for all the
drives found and a combined drive.

    [My Drive]
    type = alias
    remote = drive,team_drive=0ABCDEF-01234567890,root_folder_id=:

    [Test Drive]
    type = alias
    remote = drive,team_drive=0ABCDEFabcdefghijkl,root_folder_id=:

    [AllDrives]
    type = combine
    remote = "My Drive=My Drive:" "Test Drive=Test Drive:"

Adding this to the rclone config file will cause those team drives to
be accessible with the aliases shown. Any illegal charactes will be
substituted with "_" and duplicate names will have numbers suffixed.
It will also add a remote called AllDrives which shows all the shared
drives combined into one directory tree.

**Comment by dandar** [comment]
@ncw thank you Nick, excellent work.  
It would also be very helpful and easier to maintain if we can just add following to the config file:

[All Team Drives]
type = alias
remote = drive,team_drive=ALL,root_folder_id=:

Then, I hope we will be step closer to making the default google drive mount to show 2 folders ("My Drive" and "Shared Drives").  This would be fantastic.

**Comment by ncw** [comment]
@dandar That could be done with a command interface to the combine remote, whch made the remotes programatically, so something like

```
[All Team Drives]
type = combine
command = rclone backend drives -o combine drive:
```

Where `rclone backend drives -o combine drive:` would print each remote required in the combine, one on a line

```
dir1=:drive:root_id=...
dir2=:drive:root_id=...
```

Potentially that could add the main drive in also.

The disadvantage of doing that is that every time you run the backend it would need to list the drives which takes a small amount of time.

**Comment by dandar** [comment]
@ncw See attached, my config examples, to mount a single combine drive for all the common google remotes.  Hope you can make it even easier by either a combine backend, or a config option (keeping crypts separate of course).
[rclone_gdrive_example.conf.txt](https://github.com/rclone/rclone/files/10421536/rclone_gdrive_example.conf.txt)

**Comment by ncw** [comment]
@dandar best to discuss on [on the rclone forum](https://forum.rclone.org/) about this - thanks.
