### ISSUE TITLE
filename containing full-width ntfs reserved characters are not handled correctly

### ISSUE THREAD

**Issue by affinityDrops** [rclone/rclone#4510]
#### What is the problem you are having with rclone?
I used powershell-core.

**local to local(full-width chars here)**
I have run `PS D:\> rclone copyto foo.txt ？` and for other full-width ntfs-reserved characters.
No error messages.

**result**
All characters except full-width solidus(`／`) generates unexpected backtick prefix when used as destination filename
![image](https://user-images.githubusercontent.com/39024071/90237863-ebf23580-de5f-11ea-9962-0fdbcb42481e.png)

---
**local(full-width chars here) to local**

`PS D:\> rcl copyto -vv ＜ bar.txt` (and also for `＞` `：` `＂` `＼` `｜` `？` `＊`)
```
2020/08/14 19:24:26 DEBUG : rclone: Version "v1.52.3" starting with parameters ["C:\\rclone\\rclone.exe" "copyto" "-vv" "＜" "bar.txt"]
2020/08/14 19:24:26 DEBUG : Using config file from "C:\\Users\\myname\\.config\\rclone\\rclone.conf"
2020/08/14 19:24:26 DEBUG : fs cache: renaming cache item "＜" to be canonical "//?/D:/＜"
2020/08/14 19:24:26 DEBUG : fs cache: renaming cache item "bar.txt" to be canonical "//?/D:/bar.txt"
2020/08/14 19:24:26 ERROR : : error reading source directory: directory not found
2020/08/14 19:24:26 DEBUG : Local file system at //?/D:/bar.txt: Waiting for checks to finish
2020/08/14 19:24:26 DEBUG : Local file system at //?/D:/bar.txt: Waiting for transfers to finish
2020/08/14 19:24:26 INFO  : There was nothing to transfer
2020/08/14 19:24:26 ERROR : Attempt 1/3 failed with 1 errors and: directory not found
2020/08/14 19:24:26 ERROR : : error reading source directory: directory not found
2020/08/14 19:24:26 DEBUG : Local file system at //?/D:/bar.txt: Waiting for checks to finish
2020/08/14 19:24:26 DEBUG : Local file system at //?/D:/bar.txt: Waiting for transfers to finish
2020/08/14 19:24:26 INFO  : There was nothing to transfer
2020/08/14 19:24:26 ERROR : Attempt 2/3 failed with 1 errors and: directory not found
2020/08/14 19:24:26 ERROR : : error reading source directory: directory not found
2020/08/14 19:24:26 DEBUG : Local file system at //?/D:/bar.txt: Waiting for checks to finish
2020/08/14 19:24:26 DEBUG : Local file system at //?/D:/bar.txt: Waiting for transfers to finish
2020/08/14 19:24:26 INFO  : There was nothing to transfer
2020/08/14 19:24:26 ERROR : Attempt 3/3 failed with 1 errors and: directory not found
2020/08/14 19:24:26 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         0.0s

2020/08/14 19:24:26 DEBUG : 2 go routines active
2020/08/14 19:24:26 Failed to copyto: directory not found
```

`PS D:\> rcl copyto -vv ／ bar.txt` : works as expected

---
**local to remote**
`PS D:\> rcl copyto -vv ＜ "remote:foobar"` (and also for `＞` `：` `＂` `＼` `｜` `？` `＊`)
```
2020/08/14 19:30:55 DEBUG : rclone: Version "v1.52.3" starting with parameters ["C:\\rclone\\rclone.exe" "copyto" "-vv" "＜" "remote:bar.txt"]
2020/08/14 19:30:55 DEBUG : Using config file from "C:\\Users\\myname\\.config\\rclone\\rclone.conf"
2020/08/14 19:30:55 DEBUG : fs cache: renaming cache item "＜" to be canonical "//?/D:/＜"
2020/08/14 19:30:56 DEBUG : Google drive root 'bar.txt': root_folder_id = "0ALrOExjlLorKUk9PVA" - save this in the config to speed up startup
2020/08/14 19:30:57 ERROR : : error reading source directory: directory not found
2020/08/14 19:30:57 DEBUG : Google drive root 'bar.txt': Waiting for checks to finish
2020/08/14 19:30:57 DEBUG : Google drive root 'bar.txt': Waiting for transfers to finish
2020/08/14 19:30:57 INFO  : There was nothing to transfer
2020/08/14 19:30:57 ERROR : Attempt 1/3 failed with 1 errors and: directory not found
2020/08/14 19:30:57 ERROR : : error reading source directory: directory not found
2020/08/14 19:30:57 DEBUG : Google drive root 'bar.txt': Waiting for checks to finish
2020/08/14 19:30:57 DEBUG : Google drive root 'bar.txt': Waiting for transfers to finish
2020/08/14 19:30:57 INFO  : There was nothing to transfer
2020/08/14 19:30:57 ERROR : Attempt 2/3 failed with 1 errors and: directory not found
2020/08/14 19:30:58 ERROR : : error reading source directory: directory not found
2020/08/14 19:30:58 DEBUG : Google drive root 'bar.txt': Waiting for checks to finish
2020/08/14 19:30:58 DEBUG : Google drive root 'bar.txt': Waiting for transfers to finish
2020/08/14 19:30:58 INFO  : There was nothing to transfer
2020/08/14 19:30:58 ERROR : Attempt 3/3 failed with 1 errors and: directory not found
2020/08/14 19:30:58 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         0.0s

2020/08/14 19:30:58 DEBUG : 4 go routines active
2020/08/14 19:30:58 Failed to copyto: directory not found
```

`PS D:\> rcl copyto ／ "remote:foobar"`: works as expected

---
#### What is your rclone version (output from `rclone version`)
```
rclone v1.52.3
- os/arch: windows/amd64
- go version: go1.14.7
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 (64bits) Build 19041.450

####  Which cloud storage system are you using? (eg Google Drive)
local to remote case is tested on Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
`rclone copyto`
I have not tested every case for `rclone copy`, but I believe this command also needs fix

**Comment by ncw** [comment]
Rclone uses these characters to encode filenames that Windows can't have in file names eg question mark. This means you can use Google drive, for example and see files with question marks on Windows translated to the full width version. The backquote escapes naturally occurring versions of these characters 

You can disable this - check the backend config for the encoding parameter.

**Comment by affinityDrops** [comment]
@ncw 
I found a code related to your explanation:
https://github.com/rclone/rclone/blob/master/backend/local/encode_windows.go

Although I'm golang-illiterate, I guess `defaultEnc` constant is anyhow used as default value for `--local-encoding` on windows.
I understood what is happeing here.
If the storage system flags `*`, when you name the file to contain the letter, `*` is encoded to `＊` and `＊` is to `<RUNE>*` before written into storage system. Thus `＊` characters in saved filenames are considered invalid.

Can I specify encoder options on rclone.conf?

**Comment by ncw** [comment]
> Can I specify encoder options on rclone.conf?

Yes you can - check out the docs here: https://rclone.org/local/#local-encoding

Use the backend `local:` so your config file should look like

```
[local]
encoding = None
```

**Comment by affinityDrops** [comment]
It's all on doc! I should have read carefully.
Thanks :smile:
