### ISSUE TITLE
Change beta numbering scheme to be semver compatible

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#4516]
Currently rclone uses this numbering scheme. Examples use 1.52 as the current stable release.

- 1.52.0 - first minor release
- 1.52.1 - first patch release

That isn't controversial. Where I think we may be getting it wrong is the numbering of the betas...

We've always numbered the betas as previous stable version plus a bit, so 1.52.0-beta-NNN

This worked fine until we started making point releases which means that the beta numbering changes as we make a point release from 1.52.0-beta-XXX to 1.52.1-XXX which is strange and confuses users and complicates making a point release.

Reading the [semver spec](https://semver.org/) I think we should be calling the beta releases by the name of the release that they will become, so v1.53.0-beta-XXX rather than what it is currently called v1.52.3-beta-XXX

In particular [11.3](https://semver.org/#spec-item-11) says

> When major, minor, and patch are equal, a pre-release version has lower precedence than a normal version:
> 
> Example: 1.0.0-alpha < 1.0.0.

So this says that the 1.52.3-beta-XXX should be < 1.52.3 whereas it isn't at the moment.

So I think we should change so that the betas are called 1.53.0-beta-XXX

This makes the release sequence

- 1.52.0
- 1.53.0-beta-1
- 1.53.0-beta-2
- 1.52.1
- 1.53.0-beta-3
- 1.53.0-beta-4
- 1.52.2
- 1.53.0-beta-5
- 1.53.0-beta-6
- 1.53.0
- 1.54.0-beta-1

@rclone/rclone I'd love your opinion on this!

**Comment by creativeprojects** [comment]
> Reading the [semver spec](https://semver.org/) I think we should be calling the beta releases by the name of the release that they will become, so v1.53.0-beta-XXX rather than what it is currently called v1.52.3-beta-XXX
> 

I agree it does make more sense. It's a more common way, and most users would be familiar with it 👍

**Comment by animosity22** [comment]
Looks good to me as well and a good change!

**Comment by darthShadow** [comment]
Sounds good to me.

**Comment by marcOcram** [comment]
Sounds good to me as well as I was searching for a beta which included the `--refresh-times` feature. I was a bit confused as it was stated that it will be included in v1.53 and I did not found a beta of 1.53 at beta.rclone.org. I did not understand the current scheme  (until now) but was happy that I found the feature inside 1.52.3-XXX just by trying. Therefore good change!

**Comment by ncw** [comment]
I've made the changes for this, but I thought there is one more thing that might be worth discussing

Currently the betas are named

v1.52.3-322-g2bcc66c8-beta

However I'd like to change this slightly to this where NNNN is the commit number from the very tip of the tree and CCCC is the commit ID

v1.53.0-beta-NNNN-CCCCC

eg

v1.53.0-beta-4677-c35643ae8

or this for a branch

v1.53.0-beta-4677-c35643ae8-semver

The reason for using the "commit number" is that the previous way of doing it used the number of commits since the last tag which I want to get away from as it hampers making an `-rc` tag for instance.

I just noticed this in the semver spec

> A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphens [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92, 1.0.0-x-y-z.–.

So maybe this should be

v1.53.0-beta.4677.c35643ae8.semver

Thoughts?

**Comment by ncw** [comment]
I've merged the above to master now in time for 1.53 - semver compatible beta release names FTW!
