### ISSUE TITLE
drive: Server side copy for sheets/docs does not set the correct modtime

### ISSUE THREAD

**Issue by hinterland-1** [rclone/rclone#4517]
#### What is the problem you are having with rclone?
Rclone sync with server side copy enable does not copy the modtime correctly for google files which results in duplicates being made every time rclone sync is run. 

#### What is your rclone version (output from `rclone version`)
rclone v1.52.3
- os/arch: windows/amd64
- go version: go1.14.7

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
Google Team Drive syncing to another Google Team Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync "Academic Resources:Test Folder" "Archive:Test Folder" --drive-server-side-across-configs -vv

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
**Original Command**
C:\rclone>rclone sync "Academic Resources:Test Folder" "Archive:Test Folder" --drive-server-side-across-configs -vv
2020/08/15 10:25:34 DEBUG : rclone: Version "v1.52.2" starting with parameters ["rclone" "sync" "Academic Resources:Test Folder" "Archive:Test Folder" "--drive-server-side-across-configs" "-vv"]
2020/08/15 10:25:34 DEBUG : Using config file from "C:\\Users\\Qiang\\.config\\rclone\\rclone.conf"
2020/08/15 10:25:36 DEBUG : Google drive root 'Test Folder': Waiting for checks to finish
2020/08/15 10:25:36 DEBUG : Google drive root 'Test Folder': Waiting for transfers to finish
2020/08/15 10:25:39 INFO  : Test Google Sheets.xlsx: Copied (server side copy)
2020/08/15 10:25:39 DEBUG : Waiting for deletions to finish
2020/08/15 10:25:39 INFO  :
Transferred:           off / off, -, 0 Bytes/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         3.0s

2020/08/15 10:25:39 DEBUG : 6 go routines active

C:\rclone>rclone sync "Academic Resources:Test Folder" "Archive:Test Folder" --drive-server-side-across-configs -vv
2020/08/15 10:25:40 DEBUG : rclone: Version "v1.52.2" starting with parameters ["rclone" "sync" "Academic Resources:Test Folder" "Archive:Test Folder" "--drive-server-side-across-configs" "-vv"]
2020/08/15 10:25:40 DEBUG : Using config file from "C:\\Users\\Qiang\\.config\\rclone\\rclone.conf"
2020/08/15 10:25:42 DEBUG : Google drive root 'Test Folder': Waiting for checks to finish
2020/08/15 10:25:42 DEBUG : Test Google Sheets.xlsx: Modification times differ by 8m6.607s: 2020-08-15 14:17:30.645 +0000 UTC, 2020-08-15 14:25:37.252 +0000 UTC
2020/08/15 10:25:42 DEBUG : Google drive root 'Test Folder': Waiting for transfers to finish
2020/08/15 10:25:46 INFO  : Test Google Sheets.xlsx: Copied (server side copy)
2020/08/15 10:25:46 DEBUG : Waiting for deletions to finish
2020/08/15 10:25:46 INFO  :
Transferred:           off / off, -, 0 Bytes/s, ETA -
Checks:                 1 / 1, 100%
Transferred:            1 / 1, 100%
Elapsed time:         4.1s

2020/08/15 10:25:46 DEBUG : 6 go routines active

**I Emptied the Destination Folder and Reran with the same command except I added the flag--size-only:**
C:\rclone>rclone sync "Academic Resources:Test Folder" "Archive:Test Folder" --drive-server-side-across-configs -vv --size-only
2020/08/15 10:34:08 DEBUG : rclone: Version "v1.52.2" starting with parameters ["rclone" "sync" "Academic Resources:Test Folder" "Archive:Test Folder" "--drive-server-side-across-configs" "-vv" "--size-only"]
2020/08/15 10:34:08 DEBUG : Using config file from "C:\\Users\\Qiang\\.config\\rclone\\rclone.conf"
2020/08/15 10:34:10 DEBUG : Google drive root 'Test Folder': Waiting for checks to finish
2020/08/15 10:34:10 DEBUG : Google drive root 'Test Folder': Waiting for transfers to finish
2020/08/15 10:34:14 INFO  : Test Google Sheets.xlsx: Copied (server side copy)
2020/08/15 10:34:14 DEBUG : Waiting for deletions to finish
2020/08/15 10:34:14 INFO  :
Transferred:           off / off, -, 0 Bytes/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         3.6s

2020/08/15 10:34:14 DEBUG : 6 go routines active

C:\rclone>rclone sync "Academic Resources:Test Folder" "Archive:Test Folder" --drive-server-side-across-configs -vv --size-only
2020/08/15 10:34:17 DEBUG : rclone: Version "v1.52.2" starting with parameters ["rclone" "sync" "Academic Resources:Test Folder" "Archive:Test Folder" "--drive-server-side-across-configs" "-vv" "--size-only"]
2020/08/15 10:34:17 DEBUG : Using config file from "C:\\Users\\Qiang\\.config\\rclone\\rclone.conf"
2020/08/15 10:34:18 DEBUG : Google drive root 'Test Folder': Waiting for checks to finish
2020/08/15 10:34:18 DEBUG : Test Google Sheets.xlsx: Sizes identical
2020/08/15 10:34:18 DEBUG : Test Google Sheets.xlsx: Unchanged skipping
2020/08/15 10:34:18 DEBUG : Google drive root 'Test Folder': Waiting for transfers to finish
2020/08/15 10:34:18 DEBUG : Waiting for deletions to finish
2020/08/15 10:34:18 INFO  : There was nothing to transfer
2020/08/15 10:34:18 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Checks:                 1 / 1, 100%
Elapsed time:         0.0s

2020/08/15 10:34:18 DEBUG : 6 go routines active

**I Emptied the destination folder again and I removed the flag and I turned on sharing by link on the original file:**
C:\rclone>rclone sync "Academic Resources:Test Folder" "Archive:Test Folder" --drive-server-side-across-configs -vv
2020/08/15 10:37:52 DEBUG : rclone: Version "v1.52.2" starting with parameters ["rclone" "sync" "Academic Resources:Test Folder" "Archive:Test Folder" "--drive-server-side-across-configs" "-vv"]
2020/08/15 10:37:52 DEBUG : Using config file from "C:\\Users\\Qiang\\.config\\rclone\\rclone.conf"
2020/08/15 10:37:55 DEBUG : Google drive root 'Test Folder': Waiting for checks to finish
2020/08/15 10:37:55 DEBUG : Google drive root 'Test Folder': Waiting for transfers to finish
2020/08/15 10:37:58 INFO  : Test Google Sheets.xlsx: Copied (server side copy)
2020/08/15 10:37:58 DEBUG : Waiting for deletions to finish
2020/08/15 10:37:58 INFO  :
Transferred:           off / off, -, 0 Bytes/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         3.0s

2020/08/15 10:37:58 DEBUG : 6 go routines active

C:\rclone>rclone sync "Academic Resources:Test Folder" "Archive:Test Folder" --drive-server-side-across-configs -vv
2020/08/15 10:38:00 DEBUG : rclone: Version "v1.52.2" starting with parameters ["rclone" "sync" "Academic Resources:Test Folder" "Archive:Test Folder" "--drive-server-side-across-configs" "-vv"]
2020/08/15 10:38:00 DEBUG : Using config file from "C:\\Users\\Qiang\\.config\\rclone\\rclone.conf"
2020/08/15 10:38:01 DEBUG : Google drive root 'Test Folder': Waiting for checks to finish
2020/08/15 10:38:01 DEBUG : Test Google Sheets.xlsx: Modification times differ by 1m16.902s: 2020-08-15 14:36:39.536 +0000 UTC, 2020-08-15 14:37:56.438 +0000 UTC
2020/08/15 10:38:01 DEBUG : Google drive root 'Test Folder': Waiting for transfers to finish
2020/08/15 10:38:06 INFO  : Test Google Sheets.xlsx: Copied (server side copy)
2020/08/15 10:38:06 DEBUG : Waiting for deletions to finish
2020/08/15 10:38:06 INFO  :
Transferred:           off / off, -, 0 Bytes/s, ETA -
Checks:                 1 / 1, 100%
Transferred:            1 / 1, 100%
Elapsed time:         4.5s

2020/08/15 10:38:06 DEBUG : 6 go routines active

**Comment by ncw** [comment]
It appears that server side copies of docs are losing their modtime.

I tried putting in a work-around to set the modtime after the file was copied, but this didn't work unless I put a 1 second delay in!

All of which are pointing at some kind of bug in google drive.

Try this work-around and see how it works for you

https://beta.rclone.org/branch/v1.52.3-310-g54f46abc-fix-4517-drive-doc-modtime-beta/ (uploaded in 15-30 mins)

**Comment by hinterland-1** [comment]
> Try this work-around and see how it works for you
> 
> https://beta.rclone.org/branch/v1.52.3-310-g54f46abc-fix-4517-drive-doc-modtime-beta/ (uploaded in 15-30 mins)

I used the beta windows 64 version and I ran the same command (except I think I used a different destination remote) and the same thing occurred for me.

Here is the logs

```
C:\beta>rclone sync "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" -vv --drive-server-side-across-configs
2020/08/18 15:22:27 DEBUG : rclone: Version "v1.52.3-310-g54f46abc-fix-4517-drive-doc-modtime-beta" starting with parameters ["rclone" "sync" "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" "-vv" "--drive-server-side-across-configs"]
2020/08/18 15:22:27 DEBUG : Using config file from "C:\\Users\\Qiang\\.config\\rclone\\rclone.conf"
2020/08/18 15:22:27 DEBUG : Academic Resources: Loaded invalid token from config file - ignoring
2020/08/18 15:22:28 DEBUG : Keeping previous permissions for config file: -rw-rw-rw-
2020/08/18 15:22:28 DEBUG : Academic Resources: Saved new token in config file
2020/08/18 15:22:29 DEBUG : Academic Resources Backup: Loaded invalid token from config file - ignoring
2020/08/18 15:22:30 DEBUG : Keeping previous permissions for config file: -rw-rw-rw-
2020/08/18 15:22:30 DEBUG : Academic Resources Backup: Saved new token in config file
2020/08/18 15:22:32 DEBUG : Google drive root 'Test Folder': Waiting for checks to finish
2020/08/18 15:22:32 DEBUG : Google drive root 'Test Folder': Waiting for transfers to finish
2020/08/18 15:22:40 INFO  : Test File.xlsx: Copied (server side copy)
2020/08/18 15:22:40 DEBUG : Waiting for deletions to finish
2020/08/18 15:22:40 INFO  :
Transferred:           off / off, -, 0 Bytes/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:        13.4s

2020/08/18 15:22:40 DEBUG : 10 go routines active

C:\beta>rclone sync "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" -vv --drive-server-side-across-configs
2020/08/18 15:22:49 DEBUG : rclone: Version "v1.52.3-310-g54f46abc-fix-4517-drive-doc-modtime-beta" starting with parameters ["rclone" "sync" "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" "-vv" "--drive-server-side-across-configs"]
2020/08/18 15:22:49 DEBUG : Using config file from "C:\\Users\\Qiang\\.config\\rclone\\rclone.conf"
2020/08/18 15:22:52 DEBUG : Google drive root 'Test Folder': Waiting for checks to finish
2020/08/18 15:22:52 DEBUG : Test File.xlsx: Modification times differ by 2h31m53.469s: 2020-08-18 16:50:44.735 +0000 UTC, 2020-08-18 19:22:38.204 +0000 UTC
2020/08/18 15:22:52 DEBUG : Google drive root 'Test Folder': Waiting for transfers to finish
2020/08/18 15:22:59 INFO  : Test File.xlsx: Copied (server side copy)
2020/08/18 15:22:59 DEBUG : Waiting for deletions to finish
2020/08/18 15:22:59 INFO  :
Transferred:           off / off, -, 0 Bytes/s, ETA -
Checks:                 1 / 1, 100%
Transferred:            1 / 1, 100%
Elapsed time:         9.4s

2020/08/18 15:22:59 DEBUG : 6 go routines active
```

**Comment by hinterland-1** [comment]
I ran it again except this time I put 2 google files in the folder. 1 google doc and 1 google sheets. 
Oddly, it duplicated the google doc, but not the google sheets. In the earlier test when I had just 1 google sheets in the test folder, it was duplicating the google sheets. 

New run with 1 google doc and 1 google sheets: 
```
C:\beta>rclone sync "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" -vv --drive-server-side-across-configs
2020/08/18 17:18:24 DEBUG : rclone: Version "v1.52.3-310-g54f46abc-fix-4517-drive-doc-modtime-beta" starting with parameters ["rclone" "sync" "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" "-vv" "--drive-server-side-across-configs"]
2020/08/18 17:18:24 DEBUG : Using config file from "C:\\Users\\Qiang\\.config\\rclone\\rclone.conf"
2020/08/18 17:18:26 DEBUG : Google drive root 'Test Folder': Waiting for checks to finish
2020/08/18 17:18:26 DEBUG : Google drive root 'Test Folder': Waiting for transfers to finish
2020/08/18 17:18:31 INFO  : Test Doc.docx: Copied (server side copy)
2020/08/18 17:18:32 INFO  : Test File.xlsx: Copied (server side copy)
2020/08/18 17:18:32 DEBUG : Waiting for deletions to finish
2020/08/18 17:18:32 INFO  :
Transferred:           off / off, -, 0 Bytes/s, ETA -
Transferred:            2 / 2, 100%
Elapsed time:         7.5s

2020/08/18 17:18:32 DEBUG : 10 go routines active

C:\beta>rclone sync "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" -vv --drive-server-side-across-configs
2020/08/18 17:18:34 DEBUG : rclone: Version "v1.52.3-310-g54f46abc-fix-4517-drive-doc-modtime-beta" starting with parameters ["rclone" "sync" "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" "-vv" "--drive-server-side-across-configs"]
2020/08/18 17:18:34 DEBUG : Using config file from "C:\\Users\\Qiang\\.config\\rclone\\rclone.conf"
2020/08/18 17:18:36 DEBUG : Google drive root 'Test Folder': Waiting for checks to finish
2020/08/18 17:18:36 DEBUG : Test File.xlsx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2020/08/18 17:18:36 DEBUG : Test File.xlsx: Unchanged skipping
2020/08/18 17:18:36 DEBUG : Test Doc.docx: Modification times differ by 2m43.722s: 2020-08-18 21:15:45.617 +0000 UTC, 2020-08-18 21:18:29.339 +0000 UTC
2020/08/18 17:18:36 DEBUG : Google drive root 'Test Folder': Waiting for transfers to finish
2020/08/18 17:18:42 INFO  : Test Doc.docx: Copied (server side copy)
2020/08/18 17:18:42 DEBUG : Waiting for deletions to finish
2020/08/18 17:18:42 INFO  :
Transferred:           off / off, -, 0 Bytes/s, ETA -
Checks:                 2 / 2, 100%
Transferred:            1 / 1, 100%
Elapsed time:         7.5s

2020/08/18 17:18:42 DEBUG : 6 go routines active
```

**Comment by hinterland-1** [comment]
> I used the beta windows 64 version and I ran the same command (except I think I used a different destination remote) and the same thing occurred for me. I used a test folder and 1 google sheets.

There is definitely something odd again. I tried to recreate the duplication of the google sheets from prior, but it no longer duplicates the google sheets anymore. Even when I removed the google docs and put in the same google sheets it no longer duplicates the google sheets. 

```C:\beta>rclone sync "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" -vv --drive-server-side-across-configs
2020/08/18 17:33:02 DEBUG : rclone: Version "v1.52.3-310-g54f46abc-fix-4517-drive-doc-modtime-beta" starting with parameters ["rclone" "sync" "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" "-vv" "--drive-server-side-across-configs"]
2020/08/18 17:33:02 DEBUG : Using config file from "C:\\Users\\Qiang\\.config\\rclone\\rclone.conf"
2020/08/18 17:33:04 DEBUG : Google drive root 'Test Folder': Waiting for checks to finish
2020/08/18 17:33:04 DEBUG : Google drive root 'Test Folder': Waiting for transfers to finish
2020/08/18 17:33:10 INFO  : Test File.xlsx: Copied (server side copy)
2020/08/18 17:33:10 DEBUG : Waiting for deletions to finish
2020/08/18 17:33:10 INFO  :
Transferred:           off / off, -, 0 Bytes/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         8.5s

2020/08/18 17:33:10 DEBUG : 6 go routines active

C:\beta>rclone sync "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" -vv --drive-server-side-across-configs
2020/08/18 17:33:11 DEBUG : rclone: Version "v1.52.3-310-g54f46abc-fix-4517-drive-doc-modtime-beta" starting with parameters ["rclone" "sync" "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" "-vv" "--drive-server-side-across-configs"]
2020/08/18 17:33:11 DEBUG : Using config file from "C:\\Users\\Qiang\\.config\\rclone\\rclone.conf"
2020/08/18 17:33:13 DEBUG : Google drive root 'Test Folder': Waiting for checks to finish
2020/08/18 17:33:13 DEBUG : Test File.xlsx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2020/08/18 17:33:13 DEBUG : Test File.xlsx: Unchanged skipping
2020/08/18 17:33:13 DEBUG : Google drive root 'Test Folder': Waiting for transfers to finish
2020/08/18 17:33:13 DEBUG : Waiting for deletions to finish
2020/08/18 17:33:13 INFO  : There was nothing to transfer
2020/08/18 17:33:13 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Checks:                 1 / 1, 100%
Elapsed time:         1.9s

2020/08/18 17:33:13 DEBUG : 6 go routines active

**Comment by ncw** [comment]
I've just realised there are two parts to this bug

1. not setting the modtime correctly
2. creating duplicates

I've tried to address 1. and it sounds like that is working some of the time - is that correct?

I haven't addressed 2. though - I think that is a function of the actual server side copy. When rclone decides it needs to copy the doc, it does the copy but doesn't delete the old copy of the doc.

I've fixed that and increased the timeout before setting the modtime which should help with 1 - can you give it a go?

https://beta.rclone.org/branch/v1.52.3-311-g1b5ca0c8-fix-4517-drive-doc-modtime-beta/ (uploaded in 15-30 mins)

**Comment by ncw** [comment]
Oops, messed that one up, try this

https://beta.rclone.org/branch/v1.52.3-311-g01bfea33-fix-4517-drive-doc-modtime-beta/ (uploaded in 15-30 mins)

**Comment by hinterland-1** [comment]
> Oops, messed that one up, try this
> 
> https://beta.rclone.org/branch/v1.52.3-311-g01bfea33-fix-4517-drive-doc-modtime-beta/ (uploaded in 15-30 mins)

I ran a few tests through this one and it didn't duplicate google docs or google sheets. 

```C:\beta>rclone sync "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" -vv --drive-server-side-across-configs
2020/08/19 08:37:32 DEBUG : rclone: Version "v1.52.3-311-g01bfea33-fix-4517-drive-doc-modtime-beta" starting with parameters ["rclone" "sync" "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" "-vv" "--drive-server-side-across-configs"]
2020/08/19 08:37:32 DEBUG : Using config file from "C:\\Users\\Qiang\\.config\\rclone\\rclone.conf"
2020/08/19 08:37:32 DEBUG : Academic Resources: Loaded invalid token from config file - ignoring
2020/08/19 08:37:32 DEBUG : Keeping previous permissions for config file: -rw-rw-rw-
2020/08/19 08:37:32 DEBUG : Academic Resources: Saved new token in config file
2020/08/19 08:37:33 DEBUG : Academic Resources Backup: Loaded invalid token from config file - ignoring
2020/08/19 08:37:33 DEBUG : Keeping previous permissions for config file: -rw-rw-rw-
2020/08/19 08:37:33 DEBUG : Academic Resources Backup: Saved new token in config file
2020/08/19 08:37:35 DEBUG : Google drive root 'Test Folder': Waiting for checks to finish
2020/08/19 08:37:35 DEBUG : Google drive root 'Test Folder': Waiting for transfers to finish
2020/08/19 08:37:42 DEBUG : Google drive root 'Test Folder': Sleeping for 2s before setting the modtime to work around drive bug - see #4517
2020/08/19 08:37:45 INFO  : Test File.xlsx: Copied (server side copy)
2020/08/19 08:37:45 DEBUG : Waiting for deletions to finish
2020/08/19 08:37:45 INFO  :
Transferred:           off / off, -, 0 Bytes/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:        13.6s

2020/08/19 08:37:45 DEBUG : 10 go routines active

C:\beta>rclone sync "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" -vv --drive-server-side-across-configs
2020/08/19 08:37:50 DEBUG : rclone: Version "v1.52.3-311-g01bfea33-fix-4517-drive-doc-modtime-beta" starting with parameters ["rclone" "sync" "Academic Resources:Test Folder" "Academic Resources Backup:Test Folder" "-vv" "--drive-server-side-across-configs"]
2020/08/19 08:37:50 DEBUG : Using config file from "C:\\Users\\Qiang\\.config\\rclone\\rclone.conf"
2020/08/19 08:37:55 DEBUG : Test File.xlsx: Size and modification time the same (differ by 0s, within tolerance 1ms)
2020/08/19 08:37:55 DEBUG : Test File.xlsx: Unchanged skipping
2020/08/19 08:37:55 DEBUG : Google drive root 'Test Folder': Waiting for checks to finish
2020/08/19 08:37:55 DEBUG : Google drive root 'Test Folder': Waiting for transfers to finish
2020/08/19 08:37:55 DEBUG : Waiting for deletions to finish
2020/08/19 08:37:55 INFO  : There was nothing to transfer
2020/08/19 08:37:55 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Checks:                 1 / 1, 100%
Elapsed time:         4.6s
```

**Comment by ncw** [comment]
Thanks for testing.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.53

**Comment by bschrameckCardioCast** [comment]
I still seem to be encountering this issue on my Mac using 1.53.2. I am using `--drive-server-side-across-configs=true`. Could that be contributing to this bug?

**Comment by brianschrameck** [comment]
I still seem to be encountering this issue on my Mac using 1.53.2. I am using `--drive-server-side-across-configs=true`. Could that be contributing to this bug?

**Comment by brianschrameck** [comment]
Just noticed that the OP was also using across-configs. Maybe because I am transferring from a My Drive to a Shared Drive? I do see the `"Sleeping for 2s before setting the modtime to work around drive bug - see #4517"` in the logs.

**Comment by ncw** [comment]
> Just noticed that the OP was also using across-configs. Maybe because I am transferring from a My Drive to a Shared Drive? I do see the `"Sleeping for 2s before setting the modtime to work around drive bug - see #4517"` in the logs.

Drive to shared drive could be the problem, I'm not sure. Maybe rclone needs to wait longer in that case. You could try changing the code to see if that helps?

https://github.com/rclone/rclone/blob/45e8bea8d099db946faa2af7342f8152c5c12f96/backend/drive/drive.go#L2356-L2361
