### ISSUE TITLE
Update IBM Cloud Object Storage endpoints

### ISSUE THREAD

**Issue by egmar** [rclone/rclone#4522]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.14rc1

#### What problem are you are trying to solve?

Hi, 
IBM Cloud is changing endpoints for Object Storage service, see announcement below. It would be nice to update current endpoints with new one, see announcement:

Dear Cloud Object Storage Client,

This is a kindly reminder to transition to our IBM Cloud endpoints, which were introduced on December 17, 2017, to provide a better experience for our IBM Cloud. If you have not already transitioned from our legacy endpoints, please plan to do so before the end of October 2020. We are here to help and guide you with following information.

As the final stage of the IBM Cloud endpoint transition, IBM Cloud Object Storage endpoints ending in *.objectstorage.softlayer.net, *.objectstorage.service.networklayer.com, and *.objectstorage.adn.networklayer.com will be shutdown. The end of support is scheduled for November 1, 2020.

What's changing?
After November 1, 2020 all legacy endpoints that end in in *.objectstorage.softlayer.net, *.objectstorage.service.networklayer.com, and *.objectstorage.adn.networklayer.com will no longer be accessible.

What do I need to do?
Applications that use a legacy endpoint need to be updated to use the corresponding current endpoint. The current Cloud Object Storage offering endpoints can be found here: https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints.

If you are unable to successfully update to the current offering endpoints linked above, please open a support ticket for assistance at: https://cloud.ibm.com/unifiedsupport/cases/form

/ Event Description /
This announcement is for COS customers in Sao Paulo 01, Oslo 01, Montreal 01, Mexico 01, Toronto 01, Melbourne 01, Amsterdam 03, Seoul 01, and Chennai 01.

#### How do you think rclone should be changed to solve that?

https://github.com/rclone/rclone/blob/801a820c542cb7661c4fe73199ca498d0d471cc0/backend/s3/s3.go#L200-L307 should be updated with new endpoints listed in https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints. 

Update: docs for S3 backend should be updated to reflect this change

**Comment by kaleal** [comment]
Hi @egmar,

may I fix this one?
If you are OK with that please let me know.

**Comment by kaleal** [comment]
I have posted a comment on the PR. I this is the time to have all those endpoints ordered alphabetically. They are too many making it hard to find the right one.
