### ISSUE TITLE
turn off dir-cache on local backends

### ISSUE THREAD

**Issue by robertbaker** [rclone/rclone#4526]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.52.3-326-g45afe97e-beta
- os/arch: linux/amd64
- go version: go1.15

#### What problem are you are trying to solve?
I'm using rclone union with a local backend (/local/data) and a google drive remote (mydrive:/)
I use a 2w dir-cache-time with the union mount, I only mount the union remote.
I insert files into /local/data (not using the union remote), but rclone caches the local backend, so it doesn't see it until the cache expires (polling doesn't seem to work if it should work here).

The issue is things are being processing by other apps because those apps use the union remote and need to use files that are stored in /local/data. Refreshing or clearing the dir-cache will fix the issue. A workaround is going back to the 5m default time.

Another workaround would be to mount the remote and use the union to join 2 paths, thus effectively having 2 directory caches. I don't know if that's preferred, but I'm thinking it's less performant, less clean. I don't know if there's certain advantages over using remote:/mypath vs /path/to/remote:/mypath.

My goal was to eliminate the need for mergerfs while controling the upload process, which so far I have done with the exception of this minor problem.

#### How do you think rclone should be changed to solve that?
Local backends should be excluded from the dir-cache mechanism (by default?)
flag(s) could be introduced to allow finer control over the directory cache.

**Comment by robertbaker** [comment]
@ncw a quick fix here would be to exclude local backends (including local folder upstreams in union) to not use the directory-cache. Is there even a benefit of caching the directories in the local disk?

What would be the effort level on this?

**Comment by ncw** [comment]
Rclone still needs the directory cache as it is how objects are made for the VFS layer.

If you have a union of (local, drive) say then the VFS layer sits on top of both of those so in its cache are objects from both - there isn't a separate cache for each one.

What would fix your problem is implementing change monitoring for local file systems though - see https://github.com/rclone/rclone/issues/4152 for that.

**Comment by robertbaker** [comment]
Closing in favor of #4152
