### ISSUE TITLE
Zoho WorkDrive / Docs Support

### ISSUE THREAD

**Issue by AdrianGin** [rclone/rclone#4533]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.52.3
- os/arch: windows/amd64
- go version: go1.14.7

#### What problem are you are trying to solve?
Add Zoho WorkDrive to supported cloud providers.

Here is an API: https://writer.zohopublic.com/writer/published/ankqibdb934759c6446bca8899b2f426428fc

#### How do you think rclone should be changed to solve that?
While Zoho have TrueSync Beta (Streaming) and WorkDrive Sync (Full downloads) it would be good if rclone can integrate it as a source/dest without having to mount the drive using the Zoho sync tools.

Thanks!

**Comment by creativeprojects** [comment]
Do they have a free plan? I can't see anything mentioned on their website

**Comment by AdrianGin** [comment]
It does't look like they have a free plan. I think they have an individual plan for Zoho Docs which is something similar which is for individuals and is free.
