### ISSUE TITLE
backend/local/aaaa: remove it?

### ISSUE THREAD

**Issue by lucaskanashiro** [rclone/rclone#4536]
#### What is the problem you are having with rclone?

In `backend/local` directory we have a `aaaa` file with no content. Given the not meaningful name of this file I believe this was a mistake (?). There is no reference for this file in the `local` backend.

**Comment by animosity22** [comment]
If you want to post on the help and support forums, please use the Help and Support template and fill out everything.

Thanks!

https://forum.rclone.org

**Comment by buengese** [comment]
This is not a support request but a bout the `aaaa` file in the `backend/local` directory in the git repo. Look like this was commited as part of https://github.com/rclone/rclone/commit/f39655093401c8aa4cbfcd56a16c446655fafe77. I don't see it serving any purpose either so yeah this should probably be removed.

**Comment by animosity22** [comment]
Ah some detail. Ok, since you didn't use the template, it's tough to tell as that's why the template is there so next time, if you can use it, that helps all of us out.

Thanks!

**Comment by lucaskanashiro** [comment]
> Ah some detail. Ok, since you didn't use the template, it's tough to tell as that's why the template is there so next time, if you can use it, that helps all of us out.

As you may have noticed, most of the fields of the template does not fit this bug report, this is not a runtime issue. I'd expect someone to read the content of the bug report before closing it.

**Comment by animosity22** [comment]
Maybe a better thought would be to help out, use the template so one person can read it and categorize it rather than having multiple problem figure it out.

The less time folks classify reports is more time that can be spent coding.

I do pretty well in general but I do make mistakes here and there and that's generally because folks circumvent the process and that makes more work.

Apologies for getting it wrong.

**Comment by ncw** [comment]
@lucaskanashiro I think you are correct - this file is not needed! Do you want to send a PR to remove it?

**Comment by lucaskanashiro** [comment]
> @lucaskanashiro I think you are correct - this file is not needed! Do you want to send a PR to remove it?

Sure, I will do it. Thanks for the feedback!
