### ISSUE TITLE
rclone fails to create folder when name has trailing space

### ISSUE THREAD

**Issue by arnwas** [rclone/rclone#4543]
#### Output of `rclone version`

1.52.3
Linux Ubuntu

#### Describe the issue

When making a copy from my google drive onto my fuseblk partition, folders with a trailing space cannot be created.
It says "mkdir XXX : invalid argument".

**Comment by animosity22** [comment]
Please use the forums and fill out a complete help and support template.

https://forum.rclone.org

**Comment by arnwas** [comment]
very helpful

**Comment by ncw** [comment]
We prefer to do the initial triage on the forum - if you fill out the template there then we'll be able to help you - thanks :-)

**Comment by arnwas** [comment]
Sorry no time for such here. I could not provide any further information there.

**Comment by arnwas** [comment]
This was certainly the last thing I will ever report to reclone. Needless to say that the fix for that was simple and successful.

**Comment by animosity22** [comment]
It's always a choice and using the forums and using the right methods to report things helps as majority of folks volunteer their time to help folks like you.

So we ask to folks to help out so we can help more people as we aren't trying to deter folks from reporting problems.

**Comment by arnwas** [comment]
It is always a choice to deter folks from reporting by having non obvious methods of reporting being declared the only acceptable ones. I won't bother, and you seemingly won't fix the problem by this. So, if you prefer it like this, all the best for your project and good bye

**Comment by animosity22** [comment]
By all means, but you have to reflect on yourself as well as it's a choice to ignore the template for a bug report and it's a choice to ignore the request to collect the required information to help you solve the issue you are facing.

If you want help, the request is asking you to take a step forward and provide the required information to help you. 

It's obvious I want to help you as I've spent the time to reply and try to be thoughtful about them and inquire feedback from you on how to help and improve the process.

It takes two tango and I really want to dance. You just have to want to dance too.

**Comment by arnwas** [comment]
I gave you all info i can give you. I fixed it after a git clone. So ia m helped thanks. I want to help you , so that you could fix it in your tree. Which you do not seem to want, as you keep the issue closed. As you wish.

**Comment by animosity22** [comment]
You spent more time replying to me than it would have taken to follow my first post and do what was asked of you. Looks like the time is there so if you want to help out, please do.

**Comment by arnwas** [comment]
If you wanted scare away people from doing so: At least in my case you succeeded perfectly. I would not even want to think about how terribly complicated the procedure would go on towards a PR, if that starts already as senselessly complicated as it did here. Again, you have all information at hand, feel free to fill them into whatever complicated processed you think you need. As I said, I am finished with this, and running my own patched version. Good night.

**Comment by animosity22** [comment]
With all the issues resolved on the forums and the number of PRs that come in, it does seem like having a process is working well and the more folks that help us by using it makes helping more people faster and efficient.

If you would like to submit that, it would be great.

**Comment by arnwas** [comment]
It might seem to you.

**Comment by animosity22** [comment]
That's a data driven statement as it's not based on my feelings.

I'd feel better if you'd help us out and follow the steps but I can't control that and I can only ask for your help and support.

**Comment by arnwas** [comment]
To repeat myself again: I have nothing to contribute beyond what i did already. Feel free to peruse that info as it seems fit for you. In particular, feel free to use as much time as you want to put it in whatever form you want, or need for your nice and extensive processes. And then good luck fro any solution.

**Comment by animosity22** [comment]
Thanks, but you did contribute quite a lot of feedback which is helpful and it would have been even more helpful if you wanted to post the info that actually captured all the required information as that's why we have the templates, we can take a look at.

While you feel you provided enough, it's actually missing some key information which is captured via the template so we can't really progress without that.

**Comment by arnwas** [comment]
Well, I certainly could solve the issue with exactly the info I gave you. If you don't feel like doing that as well, this is perfectly fine for me.

**Comment by animosity22** [comment]
Nope. Missing key information which is why we have the template.

**Comment by arnwas** [comment]
Which is so obvious that even after the x-th comment you did not even mention what it is. ;-) Keep banging your head :-)

**Comment by animosity22** [comment]
I'm just banging away hoping at some point you'll do the right thing, but alas, we keep circling.

**Comment by arnwas** [comment]
Obviously you know the right thing. So do it. Without me. Thanks for the nice conversation.

**Comment by animosity22** [comment]
I believe in you.

**Comment by arnwas** [comment]
No you don't. You believe in that people have to mind read unnecessary complicated processes they can't even become aware of, and mind read which completely obsolete info they should provide for no reason when the solution is possible with what is there. It's time for a fork i guess.

**Comment by animosity22** [comment]
If you have a suggestion to improve the intake and make it clearer, please suggest it as there is no mind reading needed as it's a form to fill out as 99% just help out and do what's needed.

Why not just be part of the solution and move it forward rather than go against it?

**Comment by arnwas** [comment]
I still have no clue which form you mean at all. Thanks for assuming mind reading even for this part. Not to speak you not answering all the other (sometimes implied) question you repeatedly fail or refuse to answer. You are working against solutions, not me. I already have one. Thank you for your understanding.

**Comment by animosity22** [comment]
Open issue.
Fill out template.
Profit.

You've spent how many replies fighting against the process? At this point, I'm sure you are just trolling as you just keep replying so good luck.

**Comment by ncw** [comment]
I'm locking this issue now as I think the discussion is no longer productive.
