### ISSUE TITLE
go 1.15 test failed: conversion from int to string yields a string of one rune

### ISSUE THREAD

**Issue by wenerme** [rclone/rclone#4546]
#### What is the problem you are having with rclone?

same bug as this https://github.com/prometheus/prometheus/issues/7706

#### What is your rclone version (output from `rclone version`)

1.52.3

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

AlpineLinux amd64

```
 # github.com/rclone/rclone/fs/asyncreader
 fs/asyncreader/asyncreader_test.go:149:10: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
 fs/asyncreader/asyncreader_test.go:188:10: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
 # github.com/rclone/rclone/fs/walk
 fs/walk/walk_test.go:361:11: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```

[Full build log](https://gitlab.alpinelinux.org/wener/aports/-/jobs/197361)

**Comment by wenerme** [comment]
Fixed, but not release yet.

**Comment by ncw** [comment]
I'm just about to release 1.53 so I don't want to backport this to the stable branch. However it should be there shortly!

**Comment by wenerme** [comment]
@ncw after 1.53 released I'll update the pr for alpine package. thanks.
