### ISSUE TITLE
Wrong charcher colon ‘:’  （full-width ‘：’ half-width ':' problem)

### ISSUE THREAD

**Issue by jarryson** [rclone/rclone#4551]
OS: MACOS 10.15
RCLONE VERSION: v1.51.0-091-g132ce941-beta
COMMAND: rclone lsl

my file name contains full-width colon ('：'), but rclone replace it with half-width colon(':')

and half-width colon is not allow to be used in file names.

**Comment by darthShadow** [comment]
Can you try once with the latest beta version too, please?

**Comment by jarryson** [comment]
> Can you try once with the latest beta version too, please?

I have tried it, version v1.54.0-beta.4744.7e2488af1

the problem still exist.

**Comment by ncw** [comment]
Check out the encoding docs: https://rclone.org/overview/#encoding

You don't saw what OS or backend you are using, but likely `--local-encoding None` will fix the problem.

**Comment by jarryson** [comment]
> Check out the encoding docs: https://rclone.org/overview/#encoding
> 
> You don't saw what OS or backend you are using, but likely `--local-encoding None` will fix the problem.

I have tested it,too, but adding "--local-encoding None" did not solve this。
![截屏2020-09-14 下午3 19 07](https://user-images.githubusercontent.com/2706462/93055558-bd08f280-f69d-11ea-803e-00d944be9b5e.png)

**Comment by ncw** [comment]
> I have tested it,too, but adding "--local-encoding None" did not solve this

You may need the encoding for the backend you are using too or instead.

I can help you more if you tell me
- which backend you are using
- which command you are using
- send a run of the command with the `-vv` flag

Thanks!

**Comment by jarryson** [comment]
> > I have tested it,too, but adding "--local-encoding None" did not solve this
> 
> You may need the encoding for the backend you are using too or instead.
> 
> I can help you more if you tell me
> 
> * which backend you are using
> * which command you are using
> * send a run of the command with the `-vv` flag
> 
> Thanks!

i am using onedrive bussiness. command `./rclone --config ./rclone.conf --filter-from ./filter.txt -v -vv sync -P intl:/2021 /Volumes/DATA/Onedrive/Office/2021`

`2020/09/17 13:44:48 DEBUG : rclone: Version "v1.51.0-091-g132ce941-beta" starting with parameters ["./rclone" "--config" "./rclone.conf" "--filter-from" "./filter.txt" "-v" "-vv" "sync" "-P" "intl:/2021" "/Volumes/DATA/Onedrive/Office/2021"]
2020/09/17 13:44:48 DEBUG : Using config file from "/Users/lh/Tools/rclone.conf"
2020-09-17 13:44:51 DEBUG : Local file system at /Volumes/DATA/Onedrive/Office/2021: Waiting for checks to finish
2020-09-17 13:44:51 DEBUG : Local file system at /Volumes/DATA/Onedrive/Office/2021: Waiting for transfers to finish
2020-09-17 13:44:53 INFO  : 合同:应急中心项目.docx: Copied (new)
2020-09-17 13:44:53 DEBUG : Waiting for deletions to finish
Transferred:   	   43.272k / 43.272 kBytes, 100%, 23.634 kBytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         1.8s
2020/09/17 13:44:53 INFO  : 
Transferred:   	   43.272k / 43.272 kBytes, 100%, 23.634 kBytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         1.8s

2020/09/17 13:44:53 DEBUG : 8 go routines active`

and the file name become `合同/应急中心项目` which should be `合同：应急中心项目`

**Comment by ncw** [comment]
Thank you for the info.

I think just adding `--onedrive-encoding None` should fix the problem.

**Comment by jarryson** [comment]
> Thank you for the info.
> 
> I think just adding `--onedrive-encoding None` should fix the problem.

I have tested it and it seems ok now. thanks very much!

**Comment by ncw** [comment]
Great :-)  I'll close this now then.

Note you can put that in the config file too as `encoding = None` in your onedrive remote config.

**Comment by ltGuillaume** [comment]
I'm sorry to dig this up, but isn't this the wrong way to approach this issue? Since the full width colon is simply another character, for which there's no restriction by the system, I don't understand by RClone would even try to replace it with a half-width colon, which _does_ have restrictions, or do anything to it at all.

Shouldn't RClone just leave full-width colons alone, no matter if `Colon` is included in the `*-encoding` or not? Alternatively, RClone could make a distinction between the two characters by using `FullWidthColon` and `(HalfWidth)Colon`.

My use case is a little bit different: I'm on Windows using a crypt remote and encode the filenames (as per default). If I set `--local-encoding=Slash,LtGt,DoubleQuote,Question,Asterisk,Pipe,BackSlash,Ctl,RightSpace,RightPeriod,InvalidUtf8,Dot` (so I leave out `Colon`), it works fine.
