### ISSUE TITLE
build: ARMv6 builds for 1.53.0 result in "Illegal instruction" error

### ISSUE THREAD

**Issue by darren12345** [rclone/rclone#4553]
#### What is the problem you are having with rclone?

All commands (including running rclone with no arguments) result in the error "Illegal instruction".

#### What is your rclone version (output from `rclone version`)

1.53.0

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Linux Debian, 10.5, Arm 32 bit:

```
root@serverb3:~# uname -m
armv5tel
root@serverb3:~# uname -r
4.19.117-1

root@serverb3:~# cat /proc/cpu
cpu/     cpuinfo
root@serverb3:~# cat /proc/cpuinfo
processor       : 0
model name      : Feroceon 88FR131 rev 1 (v5l)
BogoMIPS        : 111.11
Features        : swp half thumb fastmult edsp
CPU implementer : 0x56
CPU architecture: 5TE
CPU variant     : 0x2
CPU part        : 0x131
CPU revision    : 1

Hardware        : Marvell Kirkwood (Flattened Device Tree)
Revision        : 0000
Serial          : 0000000000000000
```

####  Which cloud storage system are you using? (eg Google Drive)

pCloud, not that it matters.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

Any.

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Not possible.

Downgraded to 1.52 and all works OK.

**Comment by creativeprojects** [comment]
I can't seem to find proper documentation about it but I think I remember by default Go was compiling for ARMv6 if not specified otherwise. And it looks like you have an ARMv5 architecture.

What is surprising is that it was working in 1.52 though.

Would you be able to try to compile it for ARMv5? (works from a Linux/Windows/Mac machine)

```
$ git clone https://github.com/rclone/rclone.git
$ cd rclone
$ GOARM=5 GOARCH=arm go build
```

**Comment by ncw** [comment]
I just check the build script

https://github.com/rclone/rclone/blob/7e2488af10b316115217dc8246024d3de692d283/bin/cross-compile.go#L77

We don't set GOARM explicitly unless building the ARMv7 build

And as far as I can tell, the default is to build for ARMv6 and always has been.

I looked through the Go changelog and I don't think the default has changed.

So what I think must have happened is that the startup instructions in go1.15 now include an instruction which ARMv5 can't execute.

Can you try these 3 binaries and see which (if any work)

- [rclone-v1.53.0-armv5-go1.15.gz](https://github.com/rclone/rclone/files/5167427/rclone-v1.53.0-armv5-go1.15.gz)
  - go1.15 with GOARM=5
- [rclone-v1.53.0-armunset-go1.15.gz](https://github.com/rclone/rclone/files/5167426/rclone-v1.53.0-armunset-go1.15.gz)
  - go1.15 with GOARM unset
- [rclone-v1.53.0-armunset-go1.14.gz](https://github.com/rclone/rclone/files/5167423/rclone-v1.53.0-armunset-go1.14.gz)
  - go1.14 with GOARM unset

**Comment by Steven-Thelin** [comment]
I'm experincing the exact same issue. Just downloading rclone using `rclone.org/install.sh`, however all commands results in `Illegal instruction`. As for me, I'm on deep water here. How would i go about trying your proposed binaries @ncw ?

I'm using a Raspberry Pi Zero W, and i can't find *any* online documentation addressing how i can carry on from here. I'm going to use rclone for transfering dashcam footage from my car to google drive.

**Comment by creativeprojects** [comment]
Now that's interesting! Raspberry Pi Zero is an ARMv6, and that's easy to test because I have a few of these :smile: 

So @ncw the 3 binaries you linked in the message are all working on the Raspberry Pi. Then I tried the binary from a fresh `install.sh` and I do get the same issue

```
raspberrypi:~/pi $ file /usr/bin/rclone
/usr/bin/rclone: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=yMkVTo8Dcvjomptc6Ugb/QVTNCV-uSSMnNiQeYe9K/Z_hRZbK59JC5of2yR67o/1GFdIRuvI6U-Ga0EzCrm, stripped
raspberrypi:~/pi/rclone $ file rclone-v1.53.0-armunset-go1.15
rclone-v1.53.0-armunset-go1.15: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=Qu0302aUhG-lu0PQ-Y6K/nkuThTarnMVhJtk3Y6Y8/WmZQEIWhESviIkjz47kj/olnkqBxQzj0Kj3-NY1qL, not stripped
raspberrypi:~/pi/rclone $ uname -m
armv6l
raspberrypi:~/pi/rclone $ 
```

Is the obvious difference in `stripped` and `not stripped`?

**Comment by darren12345** [comment]
> 
> 
> I just check the build script
> 
> https://github.com/rclone/rclone/blob/7e2488af10b316115217dc8246024d3de692d283/bin/cross-compile.go#L77
> 
> We don't set GOARM explicitly unless building the ARMv7 build
> 
> And as far as I can tell, the default is to build for ARMv6 and always has been.
> 
> I looked through the Go changelog and I don't think the default has changed.
> 
> So what I think must have happened is that the startup instructions in go1.15 now include an instruction which ARMv5 can't execute.
> 
> Can you try these 3 binaries and see which (if any work)
> 
>     * [rclone-v1.53.0-armv5-go1.15.gz](https://github.com/rclone/rclone/files/5167427/rclone-v1.53.0-armv5-go1.15.gz)
>       
>       * go1.15 with GOARM=5
> 
>     * [rclone-v1.53.0-armunset-go1.15.gz](https://github.com/rclone/rclone/files/5167426/rclone-v1.53.0-armunset-go1.15.gz)
>       
>       * go1.15 with GOARM unset
> 
>     * [rclone-v1.53.0-armunset-go1.14.gz](https://github.com/rclone/rclone/files/5167423/rclone-v1.53.0-armunset-go1.14.gz)
>       
>       * go1.14 with GOARM unset

All those three binaries are working OK for me too.

**Comment by Steven-Thelin** [comment]
@darren12345 How do i install the binaries? Also - should i uninstall my prior installed version first?

**Comment by darren12345** [comment]
> @darren12345 How do i install the binaries? Also - should i uninstall my prior installed version first?

I didn’t uninstall anything. Right link the links and copy the URL.
On your machine, in your home director, download the file: wget <url>
Unzip the file: gzip -d <filename>
Make it executable: chmod +x <filename>
Execute it locally: ./<filename> -options

**Comment by Steven-Thelin** [comment]
That did it for me as well, using go1.14 with armunset. Now it executes 🤔

**Comment by Steven-Thelin** [comment]
I'm experiencing the issue now, that when running the setup for the software i am installing, it uses the global "rclone" executable, and not the binary i downloaded. Do you know of a way for me to point `>_ rclone` towards my new working binary @darren12345 ? 😄

**Comment by creativeprojects** [comment]
@Steven-Thelin 
- check where it's installed by running `which rclone`(it's likely to be `/usr/bin/rclone`)
- copy the binary over the one already installed `cp rclone-v1.53.0-armunset-go1.14 /usr/bin/rclone`
and you should be good 👍

**Comment by Steven-Thelin** [comment]
Thanks @creativeprojects ! Worked like a charm 😄

**Comment by darren12345** [comment]
> Thanks @creativeprojects ! Worked like a charm 😄

I was going to say, just ./ the full file name you downloaded and extracted. ‘./rclone_build_name_whatever’

**Comment by ncw** [comment]
@creativeprojects wrote
> So the 3 binaries you linked in the message are all working on the Raspberry Pi. Then I tried the binary from a fresh `install.sh` and I do get the same issue

The same "illegal instruction" issue? But with an ARMv6 board?

I managed to reproduce that here on my raspberry pi v1

However the latest build from the CI works for me

https://beta.rclone.org/branch/v1.53-stable/v1.53.1-beta.4748.d780fcf31.v1.53-stable/

I'm thinking there was a bobble in the release build which is a bit worrying...

**Comment by creativeprojects** [comment]
> The same "illegal instruction" issue? But with an ARMv6 board?

Yes, same `Illegal instruction` with the release. But it works on a Raspberry Pi 3 (ARMv7)

> However the latest build from the CI works for me

No, I still have the issue (same as the 1.53 release)

On a Pi Zero:

```
raspberrypi:~/pi/rclone/rclone-v1.53.1-beta.4748.d780fcf31.v1.53-stable-linux-arm $ ./rclone version
Illegal instruction
```

On a Pi 3:

```
openhab:~/pi/rclone/rclone-v1.53.1-beta.4748.d780fcf31.v1.53-stable-linux-arm $ ./rclone version
rclone v1.53.1-beta.4748.d780fcf31.v1.53-stable
- os/arch: linux/arm
- go version: go1.15
```

**Comment by ncw** [comment]
What it seems is that no builds I do from the CI work on my rpi v1 (ignore my comment above!).

However building locally does work. The builds aren't reproducible though which they should be which is odd.

I'm going to try some more experiments to see if I can work out what is going on!

**Comment by darren12345** [comment]
Possible stupid question; what is CI?

**Comment by creativeprojects** [comment]
> Possible stupid question; what is CI?

It means **Continuous Integration**: basically there's a server automatically building rclone every time we push new code (or tag) into the repository.

**Comment by ncw** [comment]
I have figured out the problem. It is something to do with building the ARMv6 and the ARMv7 releases simultaneously.

I'm just trying to nail it down which will probably end in a go bug report.

In the mean time here is a build which should work!

https://beta.rclone.org/branch/fix-4553-arm-build/v1.54.0-beta.4749.ac4537104.fix-4553-arm-build/

**Comment by ncw** [comment]
Here is a beta which does work for me :-)

[v1.54.0-beta.4749.d77094384.fix-4553-arm-build](https://beta.rclone.org/branch/fix-4553-arm-build/v1.54.0-beta.4749.d77094384.fix-4553-arm-build/) on branch [fix-4553-arm-build](https://github.com/rclone/rclone/tree/fix-4553-arm-build) (uploaded in 15-30 mins)

And here is the promised Go bug https://github.com/golang/go/issues/41223

**Comment by ncw** [comment]
I'd appreciate it if you would all test this which I'll put into a point release over the weekend if it checks out.

[v1.53.1-beta.4750.087b5788e.v1.53-stable](https://beta.rclone.org/branch/v1.53-stable/v1.53.1-beta.4750.087b5788e.v1.53-stable/) on branch [v1.53-stable](https://github.com/rclone/rclone/tree/v1.53-stable) (uploaded in 15-30 mins)

**Comment by creativeprojects** [comment]
I can confirm `v1.53.1-beta.4750.087b5788e.v1.53-stable` works fine on my Raspberry Pi Zero 👍

**Comment by darren12345** [comment]
Doesn't work for me :(
```
root@serverb3:~/rclone-v1.53.1-beta.4750.087b5788e.v1.53-stable-linux-arm# ./rclone --version
Illegal instruction
root@serverb3:~/rclone-v1.53.1-beta.4750.087b5788e.v1.53-stable-linux-arm# ./rclone --version
Illegal instruction
root@serverb3:~/rclone-v1.53.1-beta.4750.087b5788e.v1.53-stable-linux-arm# ./rclone --help
Illegal instruction
```

**Comment by creativeprojects** [comment]
> Doesn't work for me :(

... but yours is an ARMv5

**Comment by alenpeter** [comment]
This works for me too. 👍
https://beta.rclone.org/branch/fix-4553-arm-build/v1.54.0-beta.4749.d77094384.fix-4553-arm-build/

**Comment by ncw** [comment]
Thanks for testing.

I don't know why the arm build worked on ARMv5 @darren12345 it really shouldn't have as it was built for ARMv6

Though I did explicitly set ARMv6 in the build, maybe I shouldn't have. Tomorrow I'll post another binary for you to try.

**Comment by darren12345** [comment]
> I don't know why the arm build worked on ARMv5 @darren12345 it really shouldn't have as it was built for ARMv6

Don’t know what to tell you. It’s always worried until now, as do the three test binaries above.

**Comment by ncw** [comment]
@darren12345 can you give this a go please?

I've unset GOARM for the `arm` build which is how it used to be built. I expect this will work as the test build above did work.

I think this must mean that leaving GOARM unset is doing an ARMv5 build when cross compiling not an ARMv6 build as we thought. [The docs](https://github.com/golang/go/wiki/GoArm) just say

> In cross compilation situations, it is recommended that you always set an appropriate GOARM value along with GOARCH.

So maybe that is what happens.

[v1.54.0-beta.4751.6465b93f0.fix-4553-arm-v5](https://beta.rclone.org/branch/fix-4553-arm-v5/v1.54.0-beta.4751.6465b93f0.fix-4553-arm-v5/) on branch [fix-4553-arm-v5](https://github.com/rclone/rclone/tree/fix-4553-arm-v5) (uploaded in 15-30 mins)

**Comment by creativeprojects** [comment]
> I think this must mean that leaving GOARM unset is doing an ARMv5 build when cross compiling not an ARMv6 build as we thought.

We were wrong: the default with go 1.14 is to build for ARMv5, or at least from an Intel Linux:

```
$ go clean
$ GOARCH=arm go build -o rclone-arm
$ GOARCH=arm GOARM=5 go build -o rclone-armv5
$ GOARCH=arm GOARM=6 go build -o rclone-armv6
$ sha1sum rclone-arm*
b6125e8a00787f8e23988be4688d44d20e3f5567  rclone-arm
b6125e8a00787f8e23988be4688d44d20e3f5567  rclone-armv5
a76e3dbd74886a9db614d88c436e433085d3ff26  rclone-armv6
$ go version
go version go1.14.4 linux/amd64
```

**Comment by ncw** [comment]
@creativeprojects great demo!

That means my patch above should definitely work on ARMv5.

I think that I don't want to change the arm build to be V6 as it has been v5 all along.

We have an ARMv7 build now which all ARMs built in the last 5 years at least can use.

**Comment by darren12345** [comment]
> 
> 
> @darren12345 can you give this a go please?
> 
> I've unset GOARM for the `arm` build which is how it used to be built. I expect this will work as the test build above did work.
> 
> I think this must mean that leaving GOARM unset is doing an ARMv5 build when cross compiling not an ARMv6 build as we thought. [The docs](https://github.com/golang/go/wiki/GoArm) just say
> 
> > In cross compilation situations, it is recommended that you always set an appropriate GOARM value along with GOARCH.
> 
> So maybe that is what happens.
> 
> [v1.54.0-beta.4751.6465b93f0.fix-4553-arm-v5](https://beta.rclone.org/branch/fix-4553-arm-v5/v1.54.0-beta.4751.6465b93f0.fix-4553-arm-v5/) on branch [fix-4553-arm-v5](https://github.com/rclone/rclone/tree/fix-4553-arm-v5) (uploaded in 15-30 mins)

Yes, that build works. Thanks.

**Comment by ncw** [comment]
Thanks for testing @darren12345 

I'll stick this into 1.53.1 shortly. In the mean time here is a rc for 1.53.1

https://beta.rclone.org/branch/v1.53-stable/v1.53.1-beta.4753.6a0398211.v1.53-stable/

**Comment by darren12345** [comment]
Thanks Nick.

**Comment by darren12345** [comment]
Sorry, not a developer so can’t dig into the source code, but I’ve just been reviewing this whole thread. It seems you specifically set the ARM version to fix it in ARM6, but then had to unset it to fix it in ARM5. Doesn’t that put us back to square one with the bug not fixed for anyone?

**Comment by creativeprojects** [comment]
Adding the option for ARMv6 was only a random guess when trying to fix it (in case ARMv7 became the default)
The actual fix was removing the "-i" when building (it's all explained in the go bug report)

**Comment by bensleveritt** [comment]
Trying to cross-compile for ARM5, `CGO_ENABLED=0 GOARM=5 GOARCH=arm GOOS=linux go build` produces a build for macOS. Is there something more I have to do to cross-compile? This on both master and v1.53-stable

**Comment by creativeprojects** [comment]
> CGO_ENABLED=0 GOARM=5 GOARCH=arm GOOS=linux go build

That's weird. It works for me from a Mac:

```
rclone % CGO_ENABLED=0 GOARM=5 GOARCH=arm GOOS=linux go build
rclone % file ./rclone
./rclone: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=BbOu3LG2X6Lb-spQQ2IH/oBLYNbpa7VTHm2_Vm5cu/h00bMoJ1mGXrTLAxbMK6/JBd5NU4cpyqwUPxG-ZB7, not stripped
```

**Comment by bensleveritt** [comment]
@creativeprojects Ah! You're right. Thanks for the tip about `file`. I deployed it to my NAS, tried to run it and saw "Illegal instruction" an assumed it was because it wasn't compiled correctly.

Maybe you'd be able to see why?

```
$ cat /proc/cpuinfo
Processor	: ARM926EJ-S rev 1 (v5l)
BogoMIPS	: 992.87
Features	: swp half thumb fastmult edsp
CPU implementer	: 0x56
CPU architecture: 5TE
CPU variant	: 0x2
CPU part	: 0x131
CPU revision	: 1
Cache type	: write-back
Cache clean	: cp15 c7 ops
Cache lockdown	: format C
Cache format	: Harvard
I size		: 16384
I assoc		: 4
I line length	: 32
I sets		: 128
D size		: 16384
D assoc		: 4
D line length	: 32
D sets		: 128

Hardware	: Feroceon-KW
Revision	: 0000
Serial		: 0000000000000000
```

**Comment by creativeprojects** [comment]
Hmmm. It looks like the CPU should be supported. Which OS is running on it?

**Comment by bensleveritt** [comment]
Thanks for looking into this. I'm a little of my depth. I'd love to be able to build for some of the ARM devices I have about the house.

It's Axentra HipServ (some wonky Red Hat-derivation for the Netgear Stora NAS).

```
-bash-3.2$ uname -a
Linux stora 2.6.22.18-Netgear #3 Wed Jan 27 16:28:58 EST 2010 armv5tejl armv5tejl armv5tejl GNU/Linux
-bash-3.2$ cat /etc/redhat-release
HipServ
```

**Comment by creativeprojects** [comment]
Your kernel is certainly ancient 😄 

I've found this bug report, which could be a *similar* issue
https://github.com/golang/go/issues/5466

basically the bug went away after installing a 3.2 kernel.

I have some old NAS lying around where the software is no longer maintained, so I know what it is. But I suppose you could maybe check if there's not an official (unofficial?) update. If it was a popular model there will certainly be some people who tried to reinstall another linux on it. For some models it's dead easy. I even have an old BT router that I use as a NAS for example 👍🏻

**Comment by bensleveritt** [comment]
@creativeprojects Thanks for the tip! I'm straight up too nervous to go changing the kernel. I see that @davecheney managed to build Go on device years ago, so I might be able to work it out

🙇 Ta~~!
