### ISSUE TITLE
drive: special oauth text has gone missing

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#4555]
In v1.52 `rclone config` says

```
Storage> drive
** See help for drive backend at: https://rclone.org/drive/ **

Google Application Client Id
Setting your own is recommended.
See https://rclone.org/drive/#making-your-own-client-id for how to create your own.
If you leave this blank, it will use an internal key which is low performance.
Enter a string value. Press Enter for the default ("").
client_id> 
```

Wheras in 1.53 it says

```
Storage> drive
** See help for drive backend at: https://rclone.org/drive/ **

OAuth Client Id
Leave blank normally.
Enter a string value. Press Enter for the default ("").
```

So when we unified the oauth config in 30eb094f286c28fdbd7ddd0a6fe39fd5bbe8e833 we forgot about this special message, which is actually quite important!

@tgallant since you did the original refactor, do you want to have a go at fixing this?

Reported here: https://forum.rclone.org/t/rclone-1-53-release/18880/15

**Comment by tgallant** [comment]
sure thing @ncw here's my PR with a fix https://github.com/rclone/rclone/pull/4572
