### ISSUE TITLE
arm-v7 is not a valid architecture for a debian package

### ISSUE THREAD

**Issue by SuperSandro2000** [rclone/rclone#4571]
#### What is the problem you are having with rclone?

I am mirroring the deb files from the release to a local reprepro instance. I have almost all arches activated but in the latest release a file named [rclone-v1.53.0-linux-arm-v7.deb](https://github.com/rclone/rclone/releases/download/v1.53.0/rclone-v1.53.0-linux-arm-v7.deb) with the architecture of ``arm-v7`` got introduced. When I try to import the file I get the following error:
```
Error looking at 'timestamp/rclone-v1.53.0-linux-arm-v7.deb': 'arm-v7' is not one of the valid architectures: 'amd64 arm64 armhf i386 mips mipsel ppc64el s390x'
```

This error is easy for me to fix the in mirror script but it does not solve the underlying issue that debian has no arch which is named ``arm-v7``. Debian only has the following arm related arches: ``arm64``, ``armel`` and ``armhf``.

I am not sure if the rpm has the same problem but I assume it.

#### What is your rclone version (output from `rclone version`)

1.53.0

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Debian

####  Which cloud storage system are you using? (eg Google Drive)

not relevant

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

not relevant

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

not relevant

**Comment by animosity22** [comment]
Looks like it goes back to this issue:

https://github.com/rclone/rclone/issues/748

I see these as valid arm architectures:

```
felix@gemini:~$ dpkg-architecture -L | grep ^arm
armhf
armel
arm64ilp32
armeb
arm
arm64
```

**Comment by ncw** [comment]
I've had a go at fixing this here - can you check to see if the debs look OK?

Thanks

[v1.54.0-beta.4754.3f2b687ce.fix-4571-arm-deb](https://beta.rclone.org/branch/fix-4571-arm-deb/v1.54.0-beta.4754.3f2b687ce.fix-4571-arm-deb/) on branch [fix-4571-arm-deb](https://github.com/rclone/rclone/tree/fix-4571-arm-deb) (uploaded in 15-30 mins)

**Comment by SuperSandro2000** [comment]
Looks good.

```
dpkg -I rclone-v1.54.0-beta.4754.3f2b687ce.fix-4571-arm-deb-linux-arm-v7.deb 
 new Debian package, version 2.0.
 size 12250276 bytes: control archive=609 bytes.
       1 bytes,     0 lines      conffiles            
     468 bytes,    14 lines      control              
     244 bytes,     4 lines      md5sums              
 Package: rclone
 Version: 1.54.0.beta.4754.3f2b687ce.fix.4571.arm.deb
 Section: default
 Priority: extra
 Architecture: armhf
 Maintainer: Nick Craig-Wood <nick@craig-wood.com>
 Vendor: rclone
 Installed-Size: 33100
 Provides: rclone
 Homepage: https://rclone.org
 Description: Rclone - "rsync for cloud storage"
     is a command line program to sync files and directories to and
     from most cloud providers. It can also mount, tree, ncdu and lots
     of other useful things.
```

**Comment by ncw** [comment]
I've merged that fix now - thanks for testing.

It will be in 1.53.1 which will be shortly!
