### ISSUE TITLE
[ErrorMaxTransferLimitReachedFatal] Stop all transferts with cut-off mode soft and cautious

### ISSUE THREAD

**Issue by bounty1342** [rclone/rclone#4576]
#### What is the problem you are having with rclone?
Issue with cutoff=soft, all in progress transferts stop after first one finished.
Issue with cutoff=cautious, all in progress transfer stop if next transfert reach max-transfert instead of skipping it.

#### What is your rclone version (output from `rclone version`)

> rclone v1.53.0
> - os/arch: linux/amd64
> - go version: go1.15

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

> $uname -a
> Linux bounty1342vm 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> 

####  Which cloud storage system are you using? (eg Google Drive)

> Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

> rclone copy 'pyplexmove1:Plex/backup/!Finished' 'pyteammove1crypt:Current/backup/!Finished' \
> --stats-file-name-length 0 \
> --checkers 4 \
> --transfers 8 \
> --size-only \
> --stats=1m \
> --max-transfer=100G \
> --cutoff-mode=soft \
> -v

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

> Transferred:   	  102.506G / 270.556 GBytes, 38%, 79.561 MBytes/s, ETA 36m2s
> Transferred:           33 / 71, 46%
> Elapsed time:      22m3.6s
> Transferring:
>  * File 7: 96% /3.906G, 9.943M/s, 14s
>  * File 8: 38% /4.219G, 9.624M/s, 4m34s
>  * File 1: 35% /4.246G, 9.977M/s, 4m40s
>  * File 2: 24% /4.043G, 10.047M/s, 5m12s
>  * File 3: 23% /4.125G, 10.232M/s, 5m17s
>  * File 4: 21% /3.892G, 10.347M/s, 5m1s
>  * File 5:  9% /4.182G, 9.612M/s, 6m42s
>  * File 6: 10% /3.974G, 10.719M/s, 5m40s
> 
> 2020/09/04 09:32:20 INFO  : File 7: Copied (new)
> 2020/09/04 09:32:20 ERROR : Cancelling sync due to fatal error: Max transfer limit reached as set by --max-transfer
> 2020/09/04 09:32:20 ERROR : File 5: Failed to copy: Post "https://www.googleapis.com/upload/drive/v3/files?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks&supportsAllDrives=true&uploadType=resumable&upload_id=ABg5-UzEf6g4-qLBdmFukaddb4PCTdwANdHOypxJl8W9sZfHaDejqy5McpzeWJL8PV_0Q-_TLjmaC6FWig4m9__TM-0H0VFp2w": context canceled
> 2020/09/04 09:32:20 ERROR : File 4: Failed to copy: Post "https://www.googleapis.com/upload/drive/v3/files?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks&supportsAllDrives=true&uploadType=resumable&upload_id=ABg5-UwyLCdE54srakSqysILlJaw6eUTDLiszc-OI0xDy7OyjnxGNPVz_iLHjceky4UFEZiTAg-oZaebA2Ad9c_P99jAdNIdjQ": context canceled
> 2020/09/04 09:32:20 ERROR : File 2: Failed to copy: Post "https://www.googleapis.com/upload/drive/v3/files?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks&supportsAllDrives=true&uploadType=resumable&upload_id=ABg5-UxWJQ2Q0-L3tZe-LN_4oG5QG-pm0Q5iWzeib1C4rZxMjeCCQIlFeqaLx3G0rdyYGy4mWNrcxBZQOrsRYLY3ioFI8dG4Kg": context canceled
> 2020/09/04 09:32:20 ERROR : File 6: Failed to copy: Post "https://www.googleapis.com/upload/drive/v3/files?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks&supportsAllDrives=true&uploadType=resumable&upload_id=ABg5-UxvQ6i7Sbm6Bb06qSxwuDZlNcveSlxK0sXwBTEN4M2ao2xHNhmLT92mEHkbrlIkwqiOVD-huGCywasLrFkfqomfMMYpsg": context canceled
> 2020/09/04 09:32:20 ERROR : File 3: Failed to copy: Post "https://www.googleapis.com/upload/drive/v3/files?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks&supportsAllDrives=true&uploadType=resumable&upload_id=ABg5-UwQfHEFEiTjJQhVoynxhNRKV-SY-wE1uE2L1kpRL45euE7VanupOwmsiHDTipCil4uyLWseNOqxiDjM14DhoLTWOe2vqQ": context canceled
> 2020/09/04 09:32:20 ERROR : File 1: Failed to copy: Post "https://www.googleapis.com/upload/drive/v3/files?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks&supportsAllDrives=true&uploadType=resumable&upload_id=ABg5-UyCejR6uc_wnmMg-VQLpEco7K2kuhQWZJsr2gAWhGA1KubooZguOLXcn793oDjDCFY6C0oG2knrUg42N77ZTY1Km32Bzw": context canceled
> 2020/09/04 09:32:20 ERROR : File 8: Failed to copy: Post "https://www.googleapis.com/upload/drive/v3/files?alt=json&fields=id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks&supportsAllDrives=true&uploadType=resumable&upload_id=ABg5-UxWhnF-YJwixjLY_m8FfsKNGPTyqfZvrLZC5Xh9jv4H7I8QRVT0RPbAvAg5Ua6lsMMzw_s-OXFKpUlgLj4wWAHD_Bsoqw": context canceled
> 2020/09/04 09:32:20 ERROR : Fatal error received - not attempting retries
> 2020/09/04 09:32:20 INFO  : 
> Transferred:   	  103.657G / 245.948 GBytes, 42%, 79.546 MBytes/s, ETA 30m31s
> Errors:                 9 (fatal error encountered)
> Transferred:           34 / 63, 54%
> Elapsed time:     22m18.7s 2020/09/04 09:32:20 Failed to copy with 9 errors: last error was: Max transfer limit reached as set by --max-transfer

For cautious, I can think of 2 behaviours :
1. Stop spawning new transfert
2. spawn new transfer if file smaller than the remaining size

Regards

See forum: https://forum.rclone.org/t/cutoff-mode-soft-not-working-as-expected-i-think/18913

**Comment by ncw** [comment]
The problem appears to be here

https://github.com/rclone/rclone/blob/c8a719ae0dbe856ebdbc1d49a99d50818ba5cd16/fs/operations/operations.go#L364-L367

Returning `ErrorMaxTransferLimitReachedFatal` stops the transfer completely, whereas it should only stop new files being put into the queue.

I've pushed a fix for this - can you give it a test? (I accidentally pushed it to master rather than a branch - eeek )

[v1.54.0-beta.4766.75de30cfa](https://beta.rclone.org/v1.54.0-beta.4766.75de30cfa/) on branch [master](https://github.com/rclone/rclone/tree/master) (uploaded in 15-30 mins)

**Comment by bounty1342** [comment]
Thanks you for this fix !

### Command with --cutoff-mode=soft :
> /home/bounty1342/test/rclone copy -vv --drive-use-trash=false --tpslimit 10 --transfers 3  -P --drive-acknowledge-abuse "/home/bounty1342/files" "b1342_TDP:/" --buffer-size=512M --max-transfer 600M --cutoff-mode=soft
> 2020/09/09 13:33:41 DEBUG : rclone: Version "v1.54.0-beta.4766.75de30cfa" starting with parameters ["/home/bounty1342/test/rclone" "copy" "-vv" "--drive-use-trash=false" "--tpslimit" "10" "--transfers" "3" "-P" "--drive-acknowledge-abuse" "/home/bounty1342/files" "b1342_TDP:/" "--buffer-size=512M" "--max-transfer" "600M" "--cutoff-mode=soft"]

Works as expected 👍 
> 2020-09-09 13:34:37 ERROR : Can't retry this error - not attempting retries
> Transferred:   	    1.399G / 3.481 GBytes, 40%, 25.619 MBytes/s, ETA 1m23s
> Errors:                 2 (no need to retry)
> Transferred:            4 / 8, 50%
> Elapsed time:        56.3s
> 2020/09/09 13:34:37 INFO  : 
> Transferred:   	    1.399G / 3.481 GBytes, 40%, 25.619 MBytes/s, ETA 1m23s
> Errors:                 2 (no need to retry)
> Transferred:            4 / 8, 50%
> Elapsed time:        56.3s
> 
> 2020/09/09 13:34:37 DEBUG : 8 go routines active
> 2020/09/09 13:34:37 Failed to copy with 2 errors: last error was: Max transfer limit reached as set by --max-transfer

### Command with --cutoff-mode=cautious :
> /home/bounty1342/test/rclone copy -vv --drive-use-trash=false --tpslimit 10 --transfers 3  -P --drive-acknowledge-abuse "/home/bounty1342/files" "b1342_TDP:/" --buffer-size=512M --max-transfer 1000M --cutoff-mode=cautious
> 2020/09/09 13:42:50 DEBUG : rclone: Version "v1.54.0-beta.4766.75de30cfa" starting with parameters ["/home/bounty1342/test/rclone" "copy" "-vv" "--drive-use-trash=false" "--tpslimit" "10" "--transfers" "3" "-P" "--drive-acknowledge-abuse" "/home/bounty1342/files" "b1342_TDP:/" "--buffer-size=512M" "--max-transfer" "1000M" "--cutoff-mode=cautious"]

Works as expected 👍 

> 2020-09-09 13:43:28 ERROR : Can't retry this error - not attempting retries
> Transferred:   	  946.145M / 3.448 GBytes, 27%, 25.262 MBytes/s, ETA 1m42s
> Errors:                 2 (no need to retry)
> Transferred:            3 / 8, 38%
> Elapsed time:        38.0s
> 2020/09/09 13:43:28 INFO  : 
> Transferred:   	  946.145M / 3.448 GBytes, 27%, 25.262 MBytes/s, ETA 1m42s
> Errors:                 2 (no need to retry)
> Transferred:            3 / 8, 38%
> Elapsed time:        38.0s
> 
> 2020/09/09 13:43:28 DEBUG : 8 go routines active
> 2020/09/09 13:43:28 Failed to copy with 2 errors: last error was: Max transfer limit reached as set by --max-transfer

### Border case - Command with --cutoff-mode=cautious :
All files sizes > --max-transfer

- Hard stop at limit
- Soft stop initialising transferts when limit reach
- cautious stop before transfering

Works as expected 👍 

### Border case - Command with --cutoff-mode=cautious :

> /home/bounty1342/test/rclone copy -vv --drive-use-trash=false --tpslimit 10 --transfers 3  -P --drive-acknowledge-abuse "/home/bounty1342/files" "b1342_TDP:/" --buffer-size=512M --max-transfer 400M --cutoff-mode=cautious
> 2020/09/09 13:51:27 DEBUG : rclone: Version "v1.54.0-beta.4766.75de30cfa" starting with parameters ["/home/bounty1342/test/rclone" "copy" "-vv" "--drive-use-trash=false" "--tpslimit" "10" "--transfers" "3" "-P" "--drive-acknowledge-abuse" "/home/bounty1342/files" "b1342_TDP:/" "--buffer-size=512M" "--max-transfer" "400M" "--cutoff-mode=cautious"]


Generate one transfert over the limit : 👎 

> 2020-09-09 13:51:52 ERROR : Can't retry this error - not attempting retries
> Transferred:   	  533.885M / 3.520 GBytes, 15%, 21.690 MBytes/s, ETA 2m21s
> Errors:                 2 (no need to retry)
> Transferred:            2 / 8, 25%
> Elapsed time:        25.0s
> 2020/09/09 13:51:52 INFO  : 
> Transferred:   	  533.885M / 3.520 GBytes, 15%, 21.690 MBytes/s, ETA 2m21s
> Errors:                 2 (no need to retry)
> Transferred:            2 / 8, 25%
> Elapsed time:        25.0s
> 
> 2020/09/09 13:51:52 DEBUG : 6 go routines active
> 2020/09/09 13:51:52 Failed to copy with 2 errors: last error was: Max transfer limit reached as set by --max-transfer

Adding more tranfert, result with only one over the limit too.

> /home/bounty1342/test/rclone copy -vv --drive-use-trash=false --tpslimit 10 --transfers 10  -P --drive-acknowledge-abuse "/home/bounty1342/files" "b1342_TDP:/" --buffer-size=512M --max-transfer 400M --cutoff-mode=cautious
> 2020/09/09 13:54:47 DEBUG : rclone: Version "v1.54.0-beta.4766.75de30cfa" starting with parameters ["/home/bounty1342/test/rclone" "copy" "-vv" "--drive-use-trash=false" "--tpslimit" "10" "--transfers" "10" "-P" "--drive-acknowledge-abuse" "/home/bounty1342/files" "b1342_TDP:/" "--buffer-size=512M" "--max-transfer" "400M" "--cutoff-mode=cautious"]

> 2020-09-09 13:58:40 ERROR : Can't retry this error - not attempting retries
> Transferred:   	  533.885M / 533.885 MBytes, 100%, 22.859 MBytes/s, ETA 0s
> Errors:                 8 (no need to retry)
> Transferred:            2 / 2, 100%
> Elapsed time:        23.8s
> 2020/09/09 13:58:40 INFO  : 
> Transferred:   	  533.885M / 533.885 MBytes, 100%, 22.859 MBytes/s, ETA 0s
> Errors:                 8 (no need to retry)
> Transferred:            2 / 2, 100%
> Elapsed time:        23.8s
> 
> 2020/09/09 13:58:40 DEBUG : 6 go routines active
> 2020/09/09 13:58:40 Failed to copy with 8 errors: last error was: Max transfer limit reached as set by --max-transfer


I'm personally please with the fix, but to avoid future issues, you might want look into it.
Regards

**Comment by ncw** [comment]
Great testing - thanks!

`--cutoff-mode cautious` has a race condition namely it checks to see if there is enough space only at the start of the transfer. However it doesn't include the files currently transferring in the space it is looking at.

So I think if you try your test with `--transfers 1` then it will work.

To fix this would need a lot of extra infrastructure so I think I will leave it as it is. The transfer limits will always be somewhat approximate due to buffering etc anyway.
