### ISSUE TITLE
rclone serve not merging Drive directories with same name

### ISSUE THREAD

**Issue by TheLastZombie** [rclone/rclone#4577]
#### What is the problem you are having with rclone?

When a Google Drive directory contains multiple subdirectories with the same name, only the contents of one directory are exposed by `rclone serve`. For example, with a directory structure like this:

```
ROOT
├ CHILD
│ └ a.txt
└ CHILD
  └ b.txt
```

`rclone ls Drive:ROOT` returns this:

```
        0 CHILD/a.txt
        0 CHILD/b.txt
```

But the `http` web interface only shows the first file:

![image](https://user-images.githubusercontent.com/8181990/92557308-2e930c00-f26c-11ea-9a3b-585bbc529b51.png)

Same with `ftp` (and any other procotols, I assume):

![image](https://user-images.githubusercontent.com/8181990/92557779-48811e80-f26d-11ea-9dba-3f0cfb96f8dd.png)

#### What is your rclone version (output from `rclone version`)

- v1.53.0
- v1.54.0-beta.4764.b3964efe4

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Windows 10, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)

Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone serve http Drive:ROOT

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
2020/09/09 07:16:35 DEBUG : rclone: Version "v1.54.0-beta.4764.b3964efe4" starting with parameters ["rclone" "serve" "http" "Drive:ROOT" "-vv"]
2020/09/09 07:16:35 DEBUG : Using config file from "C:\\Users\\Eric\\.config\\rclone\\rclone.conf"
2020/09/09 07:16:35 DEBUG : Creating backend with remote "Drive:ROOT"
2020/09/09 07:16:36 DEBUG : Google drive root 'ROOT': root_folder_id = "0ALix-E7JPJ2iUk9PVA" - save this in the config to speed up startup
2020/09/09 07:16:37 NOTICE: Google drive root 'ROOT': Serving on http://127.0.0.1:8080/
2020/09/09 07:16:59 INFO  : : 127.0.0.1:53684: Serving directory
2020/09/09 07:17:00 INFO  : favicon.ico: 127.0.0.1:53684: File not found
2020/09/09 07:17:02 INFO  : favicon.ico: 127.0.0.1:53689: File not found
```

When descending into CHILD:

```
2020/09/09 07:17:18 INFO  : CHILD: 127.0.0.1:53684: Serving directory
```

**Comment by ncw** [comment]
The official solution to this is to use [rclone dedupe](https://rclone.org/commands/rclone_dedupe/) to merge the directories.

Making the drive backend merge the directories before giving them to the VFS layer would be very complicated.

**Comment by TheLastZombie** [comment]
Ah, my mistake then. Thanks!

**Comment by ncw** [comment]
No mistake - what you suggested is perfectly reasonable. The architecture of rclone conspires against it though :-)
