### ISSUE TITLE
googlephotos cannot upload "Failed to copy: google photos API only allows uploading to albums rclone created"

### ISSUE THREAD

**Issue by jkoopmann** [rclone/rclone#4578]
Hi,

I started using google photos with rclone yesterday and started a sync with a lot of files. During the night I hit the quota. So this morning I decided to create my own client_id etc. Works like a charm. Then I start resync and now get

Failed to copy: google photos API only allows uploading to albums rclone created

This is most likely because google does not recognize the access... Is there any way to change the access to the new account? It seems crazy that I cannot manipulate my albums with rclone in the same overall account just because I am now using a different oauth_id.

Anything I can do? Or is the only option to continue to use the group client_id or delete everything and start over?

**Comment by ncw** [comment]
I agree this restriction is really, really annoying!

One thing you could try is create the new albums with the new client_id then move the images to them using the web GUI. The web GUI doesn't seem to have any restrictions like this.
