### ISSUE TITLE
–cutoff-mode=soft not working as expected

### ISSUE THREAD

**Issue by astura8** [rclone/rclone#4583]
#### Output of `rclone version`
rclone v1.53.0

os/arch: linux/amd64
go version: go1.15

#### Describe the issue
–cutoff-mode=soft not working as expected

Quoting Nick Craig-Wood in https://forum.rclone.org/t/cutoff-mode-soft-not-working-as-expected-i-think/18913/12 :
"
I have a vague memory that there is a bug in this area but I can't find it, so feel free to make an issue.

This is the bit of code you are looking for...

github.com 1
rclone/rclone/blob/c8a719ae0dbe856ebdbc1d49a99d50818ba5cd16/fs/operations/operations.go#L364-L367 1
		if fs.Config.MaxTransfer >= 0 && (accounting.Stats(ctx).GetBytes() >= int64(fs.Config.MaxTransfer) ||
			(fs.Config.CutoffMode == fs.CutoffModeCautious && accounting.Stats(ctx).GetBytesWithPending()+src.Size() >= int64(fs.Config.MaxTransfer))) {
			return nil, accounting.ErrorMaxTransferLimitReachedFatal
		}
What that says that if the transfer mode is hit then end with accounting.ErrorMaxTransferLimitReachedFatal - that isn't such a good idea as that will stop everything immediately as you've seen.

What we want is a different sort of error which signals to the sync routines that it should no longer queue any new files, or maybe this check should be in the sync routine.

If you stick it in an issue, I'll have a go at fixing it!
"

**Comment by ncw** [comment]
I already fixed this in #4576

The fixed is merged to the latest beta.
