### ISSUE TITLE
rclone 1.53.0 is passing in url encoded values (e.g. %20) into HTTP Headers, which is against rfc

### ISSUE THREAD

**Issue by yerbie** [rclone/rclone#4585]
#### What is the problem you are having with rclone?
I'm using rclone (swift) to copy objects in the container.  If the object name contains url encoded values like %20, %2F, then the copy fails because the server does not recognize % and strips out those values.  Reading information about HTTP Headers, it seems like % is not allowed in headers. https://stackoverflow.com/questions/23215227/is-it-appropriate-or-necessary-to-use-percent-encoding-with-http-headers

#### What is your rclone version (output from `rclone version`)
1.53.0

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
MacOSX Mojave

####  Which cloud storage system are you using? (eg Google Drive)
Swift Object Storage

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copyto -vv --dump headers,auth,filters,requests,responses,bodies 'destination:rclone-test-20200911093043-22204/ ** test object ** ' 'destination:rclone-test-20200911093043-22204/ ** test object ** -copy'

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2020/09/11 09:30:54 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/09/11 09:30:54 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/09/11 09:30:54 DEBUG : HTTP REQUEST (req 0xc000526400)
2020/09/11 09:30:54 DEBUG : COPY /v1/r1rqb5xi72bf/rclone-test-20200911093043-22204/%20%2A%2A%20test%20object%20%2A%2A%20 HTTP/1.1
User-Agent: rclone/v1.53.0
Transfer-Encoding: chunked
Destination: rclone-test-20200911093043-22204/%20%2A%2A%20test%20object%20%2A%2A%20-copy
Accept-Encoding: gzip

**Comment by ncw** [comment]
You appear to be doing a server side copy, is that right?

What is the name of the file you are copying?

What was the response to the http request above?

Which swift object storage are you using?

**Comment by yerbie** [comment]
> You appear to be doing a server side copy, is that right?

Yes, it's using Swift Copy Object

> What is the name of the file you are copying?

"  ** test object **  "

> What was the response to the http request above?

404 - this is because the Destination: header that is coming into the server contains % signs.  The server I'm using (Vert.x) automatically strips out the % because they are not valid characters for headers according to the RFC. 

> Which swift object storage are you using?

This is a custom created object storage from a private company that talks Swift REST API

**Comment by ncw** [comment]
According to the openstack docs URL encoding is correct

https://docs.openstack.org/api-ref/object-store/

![Screenshot_20200911-233849](https://user-images.githubusercontent.com/536803/92978678-5f4f8d00-f488-11ea-8f75-4334774ea9ec.png)

**Comment by yerbie** [comment]
Ugh, you're right.  Thanks for your input

**Comment by ncw** [comment]
No worries! This has caused issues in the past - I found several bugs in CEPH with rclone and exactly this problem.
