### ISSUE TITLE
seafile: 

### ISSUE THREAD

**Issue by MuffinK** [rclone/rclone#4588]
#### What is the problem you are having with rclone?
Cannot use seafile as backend on raspberry pi2 while it works on my mac.

#### What is your rclone version (output from `rclone version`)
rclone v1.54.0-beta.4770.a73c78545
- os/arch: linux/arm
- go version: go1.15

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
raspberry pi OS on raspberry pi 2.

####  Which cloud storage system are you using? (eg Google Drive)
seafile

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone lsd seaf: -vv
or
rclone size seaf: -vv
or etc..

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
```
2020/09/14 17:06:24 DEBUG : rclone: Version "v1.53.1" starting with parameters ["rclone" "lsd" "seaf:" "-vv"]
2020/09/14 17:06:24 DEBUG : Using config file from "/home/pi/.config/rclone/rclone.conf"
2020/09/14 17:06:24 DEBUG : Creating backend with remote "seaf:"
2020/09/14 17:06:26 DEBUG : Seafile server version 7.1.4
2020/09/14 17:06:27 Failed to create file system for "seaf:": failed to get libraries: json: cannot unmarshal number 3074844944 into Go struct field Library.size of type int
```

**Comment by darthShadow** [comment]
This should be simple enough to fix. @MuffinK Do you want to give it a try?

You should just need to change `int` to `int64` for `Size` @ https://github.com/rclone/rclone/blob/master/backend/seafile/api/types.go#L49

**Comment by MuffinK** [comment]
> This should be simple enough to fix. @MuffinK Do you want to give it a try?
> 
> You should just need to change `int` to `int64` for `Size` @ https://github.com/rclone/rclone/blob/master/backend/seafile/api/types.go#L49

Yes. It works now.  Thank you.
But I still wonder why all Size but Library Size are int64😅

**Comment by darthShadow** [comment]
Can you please also create a PR with the fix?

**Comment by MuffinK** [comment]
Ok , I will do it later

**Comment by ncw** [comment]
Cc: @creativeprojects

**Comment by creativeprojects** [comment]
> But I still wonder why all Size but Library Size are int64😅

That's a good question. It' just that I didn't realise an int would be an int32 on raspberry pi.
