### ISSUE TITLE
Avoid creating web gui configuration file on startup

### ISSUE THREAD

**Issue by albertony** [rclone/rclone#4600]
#### What is the problem you are having with rclone?

Rclone creates web gui configuration file on startup, even with a simple `rclone --version` command.

It is created in a subfolder path below cache folder, given by global flag `--cache-dir`. Default on Windows: `%LocalAppData%\rclone\webgui\plugins\config\availablePlugins.json`.

To me this seems unnecessary, at least on a setup where web gui is never going to be used anyway. It is a bit "annoying" when rclone otherwise is set up to run "portable" with a local configuration file given by global flag `--config`. I could redirect it by setting `--cache-dir`, but it would it not be better if the webgui/plugin related directories/files were not created until actually needed?

I considered trying to change this in the code myself, but noticed there was a commit specifically introducing it in the original pull request from @negative0: [Create availablePlugins config file if it does not exist](https://github.com/rclone/rclone/pull/4309/commits/b2d3ff8067b70098fb9e20bf6f0285e472e8bb53), so there is probably some reason for it that must be considered...

#### What is your rclone version (output from `rclone version`)

rclone v1.53.1
- os/arch: windows/amd64
- go version: go1.15

**Comment by darthShadow** [comment]
@negative0 Thoughts?

**Comment by negative0** [comment]
@darthShadow Thanks for pointing this out. I think the commit should fix it. Let me know.

**Comment by darthShadow** [comment]
Yes, that should fix it. Can you please create a PR so @albertony has a build to try that out?

**Comment by negative0** [comment]
Yes. I was just doing that.
