### ISSUE TITLE
Rclone pauses for about 5 minutes prior to transferring files on debian buster rclone copy from s3

### ISSUE THREAD

**Issue by munntjlx** [rclone/rclone#4619]
#### What is the problem you are having with rclone?
When using rclone sync on debian (or even redhat 7, 8) rclone pauses/hangs for about 5 minutes and then transferrs the files. This is within debian-slim docker image:latest.

#### What is your rclone version (output from `rclone version`)

rclone v1.53.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian bullseye/sid 64 amd64 

####  Which cloud storage system are you using? (eg Google Drive)
aws s3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

 rclone copy -vvvv --no-check-certificate me:my/2020/Jan/01 /share/lastweek

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2020/09/22 17:52:12 DEBUG : rclone: Version "v1.53.1" starting with parameters ["rclone" "copy" "-vvvv" "--no-check-certificate" "me:my/2020/Jan/01" "/share/lastweek"]
2020/09/22 17:52:12 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2020/09/22 17:52:12 DEBUG : Creating backend with remote "me:my/2020/Jan/01"
2020/09/22 17:54:16 DEBUG :file1.html: MD5 = 3ddddd6e17ef3a9598a9e7178476997b OK
2020/09/22 17:54:16 INFO  : file1.html Copied (new)
...Hundreds of files
Transferred:   	  644.014M / 644.014 MBytes, 100%, 47.994 MBytes/s, ETA 0s
Transferred:          387 / 387, 100%
Elapsed time:      2m17.0s

Is it the 'md5 precalculation' issue I see mentioned everywhere? I did try running with the --disable-s3-checksum, but there is still the long wait before a transfer occurs.

**Comment by darthShadow** [comment]
Try adding `--ignore-checksum`

**Comment by animosity22** [comment]
This looks to be answered. Any questions on use, you can always ask on the forums as well:

https://forum.rclone.org
