### ISSUE TITLE
issues uploading files on minio using a policy with depth

### ISSUE THREAD

**Issue by armsby** [rclone/rclone#4633]
#### What is the problem you are having with rclone?
when trying to upload a file to a sub folder im getting a 403 when using rclone
the storage system is minio,
it works if have access to write in the root, but if the policy only gives you access to write in a sub folder I get a 403
it works if im using the minio client

#### What is your rclone version (output from `rclone version`)
rclone v1.53.1
- os/arch: linux/amd64
- go version: go1.15

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
debian

####  Which cloud storage system are you using? (eg Google Drive)
own running minio server

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy mc test:bucket/folder/folder/test.bin

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
rclone log:
rclone copy -vv mc test:bucket/folder/folder/test.bin
2020/09/27 20:57:13 DEBUG : rclone: Version "v1.53.1" starting with parameters ["rclone" "copy" "-vv" "mc" "test:bucket/folder/folder/test.bin"]
2020/09/27 20:57:13 DEBUG : Creating backend with remote "mc"
2020/09/27 20:57:13 DEBUG : Using config file from "/opt/.config/rclone/rclone.conf"
2020/09/27 20:57:13 DEBUG : fs cache: adding new entry for parent of "mc", "/root"
2020/09/27 20:57:13 DEBUG : Creating backend with remote "test:bucket/folder/folder/test.bin"
2020/09/27 20:57:14 DEBUG : mc: Need to transfer - File not found at Destination
2020/09/27 20:57:14 ERROR : mc: Failed to copy: AccessDenied: Access Denied.
        status code: 403, request id: 1638B8F5F8648B78, host id:
2020/09/27 20:57:14 ERROR : Attempt 1/3 failed with 1 errors and: AccessDenied: Access Denied.
        status code: 403, request id: 1638B8F5F8648B78, host id:
2020/09/27 20:57:14 DEBUG : mc: Need to transfer - File not found at Destination
2020/09/27 20:57:15 ERROR : mc: Failed to copy: AccessDenied: Access Denied.
        status code: 403, request id: 1638B8F62B5C12EC, host id:
2020/09/27 20:57:15 ERROR : Attempt 2/3 failed with 1 errors and: AccessDenied: Access Denied.
        status code: 403, request id: 1638B8F62B5C12EC, host id:
2020/09/27 20:57:15 DEBUG : mc: Need to transfer - File not found at Destination
2020/09/27 20:57:16 ERROR : mc: Failed to copy: AccessDenied: Access Denied.
        status code: 403, request id: 1638B8F661EAD51D, host id:
2020/09/27 20:57:16 ERROR : Attempt 3/3 failed with 1 errors and: AccessDenied: Access Denied.
        status code: 403, request id: 1638B8F661EAD51D, host id:
2020/09/27 20:57:16 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         3.3s

2020/09/27 20:57:16 DEBUG : 3 go routines active
2020/09/27 20:57:16 Failed to copy: AccessDenied: Access Denied.
        status code: 403, request id: 1638B8F661EAD51D, host id:

**Comment by darthShadow** [comment]
Can you try running `rclone copyto` instead of `rclone copy`?

**Comment by armsby** [comment]
that did not make any change, same error

**Comment by darthShadow** [comment]
Can you add the debug logs for that along with the `--dump-bodies` flag?

**Comment by armsby** [comment]
this should be what you need: 
rclone copyto --dump-bodies -vv mc test:bucket/folder/folder/test.bin                                                                                                                                                                                                                                                                                                                                                   [126/1942]
2020/09/28 08:42:10 NOTICE: --dump-bodies is obsolete - please use --dump bodies instead
2020/09/28 08:42:10 DEBUG : rclone: Version "v1.53.1" starting with parameters ["rclone" "copyto" "--dump-bodies" "-vv" "mc" "test:bucket/folder/folder/test.bin"]
2020/09/28 08:42:10 DEBUG : Creating backend with remote "mc"
2020/09/28 08:42:10 DEBUG : Using config file from "/opt/.config/rclone/rclone.conf"
2020/09/28 08:42:10 DEBUG : fs cache: adding new entry for parent of "mc", "/root"
2020/09/28 08:42:10 DEBUG : Creating backend with remote "test:bucket/folder/folder/"
2020/09/28 08:42:10 DEBUG : You have specified to dump information. Please be noted that the Accept-Encoding as shown may not be correct in the request and the response may not show Content-Encoding if the go standard libraries auto gzip encoding was in effect. In this case the body of the request will be gunzipped before showing it.
2020/09/28 08:42:10 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/09/28 08:42:10 DEBUG : HTTP REQUEST (req 0xc0001f8d00)
2020/09/28 08:42:10 DEBUG : HEAD /bucket/folder/folder HTTP/1.1
Host: test.minio.io
User-Agent: rclone/v1.53.1
Authorization: XXXX
X-Amz-Content-Sha256: e3b0542428fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200928T064210Z

2020/09/28 08:42:10 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/09/28 08:42:11 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/09/28 08:42:11 DEBUG : HTTP RESPONSE (req 0xc0001f8d00)
2020/09/28 08:42:11 DEBUG : HTTP/2.0 404 Not Found
Accept-Ranges: bytes
Cf-Cache-Status: DYNAMIC
Cf-Ray: 5d9b7ba2da46d14b-GOT
Cf-Request-Id: 05750b99c60000d14b32221200000001
Content-Security-Policy: block-all-mixed-content
Date: Mon, 28 Sep 2020 06:42:11 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cfduid=ddfd825952e1e5b12c3f47643266a9ca81601275331; expires=Wed, 28-Oct-20 06:42:11 GMT; path=/; domain=.minio.io; HttpOnly; SameSite=Lax
Vary: Origin
X-Amz-Request-Id: 1638DF6E1374B38D
X-Xss-Protection: 1; mode=block
Content-Length: 0

2020/09/28 08:42:11 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/09/28 08:42:11 DEBUG : fs cache: renaming cache item "test:bucket/folder/folder/" to be canonical "test:bucket/folder/folder"
2020/09/28 08:42:11 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/09/28 08:42:11 DEBUG : HTTP REQUEST (req 0xc0001f8800)
2020/09/28 08:42:11 DEBUG : HEAD /bucket/folder/folder/test.bin HTTP/1.1
Host: test.minio.io
User-Agent: rclone/v1.53.1
Authorization: XXXX
X-Amz-Content-Sha256: e3b0542428fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200928T064211Z

2020/09/28 08:42:11 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/09/28 08:42:12 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/09/28 08:42:12 DEBUG : HTTP RESPONSE (req 0xc0001f8800)
2020/09/28 08:42:12 DEBUG : HTTP/2.0 404 Not Found
Accept-Ranges: bytes
Cf-Cache-Status: DYNAMIC
Cf-Ray: 5d9b7ba75cd3d14b-GOT
Cf-Request-Id: 05750b9c990000d14b3225a200000001
Content-Security-Policy: block-all-mixed-content
Date: Mon, 28 Sep 2020 06:42:12 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cfduid=ddfd825952e1e5b12c3f47643266a9ca81601275331; expires=Wed, 28-Oct-20 06:42:11 GMT; path=/; domain=.minio.io; HttpOnly; SameSite=Lax
Vary: Origin
X-Amz-Request-Id: 1638DF6E3E305713
X-Xss-Protection: 1; mode=block
Content-Length: 0

2020/09/28 08:42:12 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/09/28 08:42:12 DEBUG : mc: Need to transfer - File not found at Destination
2020/09/28 08:42:12 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/09/28 08:42:12 DEBUG : HTTP REQUEST (req 0xc00003cd00)
2020/09/28 08:42:12 DEBUG : PUT /bucket HTTP/1.1
Host: test.minio.io
User-Agent: rclone/v1.53.1
Content-Length: 0
Authorization: XXXX
X-Amz-Acl: private
X-Amz-Content-Sha256: e3b0542428fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200928T064212Z
Accept-Encoding: gzip

2020/09/28 08:42:12 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/09/28 08:42:13 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/09/28 08:42:13 DEBUG : HTTP RESPONSE (req 0xc00003cd00)
2020/09/28 08:42:13 DEBUG : HTTP/2.0 403 Forbidden
Cf-Cache-Status: DYNAMIC
Cf-Ray: 5d9b7babce57d14b-GOT
Cf-Request-Id: 05750b9f5b0000d14b322a5200000001
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Mon, 28 Sep 2020 06:42:13 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cfduid=d4085be3e58dcd6654d2de92ace6b239c1601275332; expires=Wed, 28-Oct-20 06:42:12 GMT; path=/; domain=.minio.io; HttpOnly; SameSite=Lax
Vary: Origin
X-Amz-Request-Id: 1638DF6E60AB82E0
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><BucketName>bucket</BucketName><Resource>/bucket</Resource><RequestId>1638DF6E60AB82E0</RequestId><HostId>ed1c8f31-29f6-437f-82b5-6c585da9ddfa</HostId></Error>
2020/09/28 08:42:13 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/09/28 08:42:13 ERROR : mc: Failed to copy: AccessDenied: Access Denied.
        status code: 403, request id: 1638DF6E60AB82E0, host id:
2020/09/28 08:42:13 ERROR : Attempt 1/3 failed with 1 errors and: AccessDenied: Access Denied.
        status code: 403, request id: 1638DF6E60AB82E0, host id:
2020/09/28 08:42:13 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/09/28 08:42:13 DEBUG : HTTP REQUEST (req 0xc00030c800)
2020/09/28 08:42:13 DEBUG : HEAD /bucket/folder/folder/test.bin HTTP/1.1
Host: test.minio.io
User-Agent: rclone/v1.53.1
Authorization: XXXX
X-Amz-Content-Sha256: e3b0542428fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200928T064213Z
2020/09/28 08:42:13 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/09/28 08:42:13 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/09/28 08:42:13 DEBUG : HTTP RESPONSE (req 0xc00030c800)
2020/09/28 08:42:13 DEBUG : HTTP/2.0 404 Not Found
Accept-Ranges: bytes
Cf-Cache-Status: DYNAMIC
Cf-Ray: 5d9b7bafcfefd14b-GOT
Cf-Request-Id: 05750ba1da0000d14b322d3200000001
Content-Security-Policy: block-all-mixed-content
Date: Mon, 28 Sep 2020 06:42:13 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cfduid=d6167b5180218d0b68fb191051e486dd51601275333; expires=Wed, 28-Oct-20 06:42:13 GMT; path=/; domain=.minio.io; HttpOnly; SameSite=Lax
Vary: Origin
X-Amz-Request-Id: 1638DF6E8DC22543
X-Xss-Protection: 1; mode=block
Content-Length: 0

2020/09/28 08:42:13 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/09/28 08:42:13 DEBUG : mc: Need to transfer - File not found at Destination
2020/09/28 08:42:13 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/09/28 08:42:13 DEBUG : HTTP REQUEST (req 0xc00030cf00)
2020/09/28 08:42:13 DEBUG : PUT /bucket HTTP/1.1
Host: test.minio.io
User-Agent: rclone/v1.53.1
Content-Length: 0
Authorization: XXXX
X-Amz-Acl: private
X-Amz-Content-Sha256: e3b0542428fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200928T064213Z
Accept-Encoding: gzip

2020/09/28 08:42:13 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/09/28 08:42:13 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/09/28 08:42:13 DEBUG : HTTP RESPONSE (req 0xc00030cf00)
2020/09/28 08:42:13 DEBUG : HTTP/2.0 403 Forbidden
Cf-Cache-Status: DYNAMIC
Cf-Ray: 5d9b7bb408fdd14b-GOT
Cf-Request-Id: 05750ba4880000d14b32314200000001
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Mon, 28 Sep 2020 06:42:13 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cfduid=d6167b5180218d0b68fb191051e486dd51601275333; expires=Wed, 28-Oct-20 06:42:13 GMT; path=/; domain=.minio.io; HttpOnly; SameSite=Lax
Vary: Origin
X-Amz-Request-Id: 1638DF6E994FF810
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><BucketName>bucket</BucketName><Resource>/bucket</Resource><RequestId>1638DF6E994FF810</RequestId><HostId>ed1c8f31-29f6-437f-82b5-6c585da9ddfa</HostId></Error>
2020/09/28 08:42:13 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/09/28 08:42:13 ERROR : mc: Failed to copy: AccessDenied: Access Denied.
        status code: 403, request id: 1638DF6E994FF810, host id:
2020/09/28 08:42:13 ERROR : Attempt 2/3 failed with 1 errors and: AccessDenied: Access Denied.
        status code: 403, request id: 1638DF6E994FF810, host id:
2020/09/28 08:42:13 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/09/28 08:42:13 DEBUG : HTTP REQUEST (req 0xc00003d100)
2020/09/28 08:42:13 DEBUG : HEAD /bucket/folder/folder/test.bin HTTP/1.1
Host: test.minio.io
User-Agent: rclone/v1.53.1
Authorization: XXXX
X-Amz-Content-Sha256: e3b0542428fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200928T064213Z

2020/09/28 08:42:13 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/09/28 08:42:14 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/09/28 08:42:14 DEBUG : HTTP RESPONSE (req 0xc00003d100)
2020/09/28 08:42:14 DEBUG : HTTP/2.0 404 Not Found
Accept-Ranges: bytes
Cf-Cache-Status: DYNAMIC
Cf-Ray: 5d9b7bb52b09d14b-GOT
Cf-Request-Id: 05750ba53d0000d14b3231d200000001
Content-Security-Policy: block-all-mixed-content
Date: Mon, 28 Sep 2020 06:42:14 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cfduid=d6167b5180218d0b68fb191051e486dd51601275333; expires=Wed, 28-Oct-20 06:42:13 GMT; path=/; domain=.minio.io; HttpOnly; SameSite=Lax
Vary: Origin
X-Amz-Request-Id: 1638DF6EA45578B7
X-Xss-Protection: 1; mode=block
Content-Length: 0

2020/09/28 08:42:14 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/09/28 08:42:14 DEBUG : mc: Need to transfer - File not found at Destination
2020/09/28 08:42:14 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/09/28 08:42:14 DEBUG : HTTP REQUEST (req 0xc00029c200)
2020/09/28 08:42:14 DEBUG : PUT /bucket HTTP/1.1
Host: test.minio.io
User-Agent: rclone/v1.53.1
Content-Length: 0
Authorization: XXXX
X-Amz-Acl: private
X-Amz-Content-Sha256: e3b0542428fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200928T064214Z
Accept-Encoding: gzip

2020/09/28 08:42:14 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/09/28 08:42:14 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/09/28 08:42:14 DEBUG : HTTP RESPONSE (req 0xc00029c200)
2020/09/28 08:42:14 DEBUG : HTTP/2.0 403 Forbidden
Cf-Cache-Status: DYNAMIC
Cf-Ray: 5d9b7bb65de6d14b-GOT
Cf-Request-Id: 05750ba5fb0000d14b3232a200000001
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Mon, 28 Sep 2020 06:42:14 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Set-Cookie: __cfduid=d98594651440e8df9b79681e3e19be2db1601275334; expires=Wed, 28-Oct-20 06:42:14 GMT; path=/; domain=.minio.io; HttpOnly; SameSite=Lax
Vary: Origin
X-Amz-Request-Id: 1638DF6ECB9A54F7
X-Xss-Protection: 1; mode=block
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><BucketName>bucket</BucketName><Resource>/bucket</Resource><RequestId>1638DF6ECB9A54F7</RequestId><HostId>ed1c8f31-29f6-437f-82b5-6c585da9ddfa</HostId></Error>
2020/09/28 08:42:14 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/09/28 08:42:14 ERROR : mc: Failed to copy: AccessDenied: Access Denied.
        status code: 403, request id: 1638DF6ECB9A54F7, host id:
2020/09/28 08:42:14 ERROR : Attempt 3/3 failed with 1 errors and: AccessDenied: Access Denied.
        status code: 403, request id: 1638DF6ECB9A54F7, host id:
2020/09/28 08:42:14 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         3.8s

2020/09/28 08:42:14 DEBUG : 3 go routines active
2020/09/28 08:42:14 Failed to copyto: AccessDenied: Access Denied.
        status code: 403, request id: 1638DF6ECB9A54F7, host id:

**Comment by ncw** [comment]
I think your strict policy is confusing rclone.

Try adding `--s3-no-check-bucket` (this can go in the config as `no_check_bucket = true` also) and see if that helps.

**Comment by armsby** [comment]
that seams to work, but I will have to do more test before I can be 100% sure

**Comment by armsby** [comment]
I can now confirm that it is working.

but it also looks like all it take to confuse rclone is that you cant create new buckets.

**Comment by ncw** [comment]
Rclone will create buckets on the fly is the problem....

I'll close this now since I think we have fixed the problem!
