### ISSUE TITLE
1fichier maximum file size

### ISSUE THREAD

**Issue by gyutw** [rclone/rclone#4634]
#### What is the problem you are having with rclone?
rclone can not upload a 114GB file to 1fichier.
vfs cache: failed to upload try #6, will retry in 5m0s: vfs cache: failed to transfer file from cache to remote: File too big, cant upload

#### What is your rclone version (output from `rclone version`)
rclone v1.53.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 20 64bit

####  Which cloud storage system are you using? (eg Google Drive)
1fichier

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone serve ftp --vfs-cache-mode writes --vfs-cache-max-age 0 --no-checksum --no-modtime --passive-port "30000-32000" --user XXX --pass 'XXX' --addr XXX:XXX 1fichier:XXX

**Comment by gyutw** [comment]
Even though 1fichier maximum allowed file size is 300GB rclone cant upload a 114GB file. giving fille too big error.

**Comment by gyutw** [comment]
Screenshot:
https://puu.sh/Gx8Pf/2b9a834d7e.png

**Comment by darthShadow** [comment]
Ok, looks like the limit was increased after the initial code from 100 GB to 300 GB.

@gyutw Do you want to send a PR for changing this?

It should be as simple as changing `100e9` to `300e9` at https://github.com/rclone/rclone/blob/41ec712aa961e01a3d8bacc3a0b17a2b73344210/backend/fichier/fichier.go#L326

**Comment by gyutw** [comment]
> Ok, looks like the limit was increased after the initial code from 100 GB to 300 GB.
> 
> @gyutw Do you want to send a PR for changing this?
> 
> It should be as simple as changing `100e9` to `300e9` at
> 
> https://github.com/rclone/rclone/blob/41ec712aa961e01a3d8bacc3a0b17a2b73344210/backend/fichier/fichier.go#L326

I cant find this file, where should it be?

**Comment by darthShadow** [comment]
Do you have the source cloned to your local system? The file is present at `backend/fichier/fichier.go`

**Comment by gyutw** [comment]
> Do you have the source cloned to your local system? The file is present at `backend/fichier/fichier.go`

I installed using the curl command.

**Comment by darthShadow** [comment]
Ok, then you can edit it online and send the PR via this method: https://docs.github.com/en/free-pro-team@latest/github/managing-files-in-a-repository/editing-files-in-your-repository

**Comment by gyutw** [comment]
> Ok, then you can edit it online and send the PR via this method: https://docs.github.com/en/free-pro-team@latest/github/managing-files-in-a-repository/editing-files-in-your-repository

File edited, now how can I update the rclone on my server? Sorry for dumb question, first time doing this in Github.

**Comment by darthShadow** [comment]
Ah, I think you did it on your fork which will require extra steps for getting usable builds. You need to do it on this repo, not the fork which will create a PR (that needs to be merged by ncw) and also the builds for testing.

**Comment by gyutw** [comment]
> Ah, I think you did it on your fork which will require extra steps for getting usable builds. You need to do it on this repo, not the fork which will create a PR (that needs to be merged by ncw) and also the builds for testing.

Now I am completely confused :))

When I tried editing it here, it says I should be on a branch, so I forked and edited the file.
Do you mean I should wait for the update from the rclone author?

**Comment by darthShadow** [comment]
No, just select the master branch in the top left section. You can use this link for the file to edit: https://github.com/rclone/rclone/blob/master/backend/fichier/fichier.go

**Comment by gyutw** [comment]
> No, just select the master branch in the top left section. You can use this link for the file to edit: https://github.com/rclone/rclone/blob/master/backend/fichier/fichier.go

This is done, now how to update the rclone in my server?

**Comment by darthShadow** [comment]
Wait for the builds to get generated after the commit is merged.

**Comment by gyutw** [comment]
> Wait for the builds to get generated after the commit is merged.

Sure. Do you mean it will update the code in my server automatically?

**Comment by darthShadow** [comment]
No, you will need to download them when they are ready after the commit is merged.

**Comment by gyutw** [comment]
> No, you will need to download them when they are ready after the commit is merged.

It is still in progress, should I run this after it got completed?
git pull rclone

**Comment by gyutw** [comment]
> No, you will need to download them when they are ready after the commit is merged.

It is failed! It was stuck on "install go" step for MAC.

**Comment by buengese** [comment]
Fix for this is in the laste beta which you can download [here](https://beta.rclone.org/).
