### ISSUE TITLE
Running rclone in Android

### ISSUE THREAD

**Issue by jd1900** [rclone/rclone#4637]
#### What is the problem you are having with rclone?
I can't run rclone in Android.

I get errors with the config file as well as the cache DIR, as Android running with root doesn't have permissions to write in $HOME folder.
For instance:
`2020/09/28 08:41:46 ERROR : error reading available plugins: Error creating : /.cache/rclone/webgui/plugins/config`

Therefore, I changed HOME to be the current dir (/data/local/rclone).
I got it working and able to create both config file and cache folder properly (or using --config=rclone.conf").

However, when trying to add a remote, it always fails.
Using the auto, I get a link like this:
http://127.0.0.1:53682/auth?state=bXXXXXXXXXXXXXXXw

And I can't end the configuration, as I get this error:
`2020/09/28 08:40:11 Failed to configure token: failed to get token: Post "https://oauth2.googleapis.com/token": dial tcp: lookup oauth2.googleapis.com on [::1]:53: read udp [::1]:43828->[::1]:53: read: connection refused`

Same when trying to copy the config file from the computer.
```
/data/local/rclone # ./rclone lsd myremote:
2020/09/28 08:42:19 Failed to create file system for "myremote:": couldn't find root directory ID: Get "https://www.googleapis.com/drive/v3/files/root?alt=json&fields=id&prettyPrint=false&supportsAllDrives=true": couldn't fetch token - maybe it has expired? - refresh with "rclone config reconnect myremote:": Post "https://oauth2.googleapis.com/token": dial tcp: lookup oauth2.googleapis.com on [::1]:53: read udp [::1]:46211->[::1]:53: read: connection refused
```

I've also tried to bind to a specific IP address with  "--bind 10.247.144.14", but it does nothing.

However, if I share my internet connection from the mobile to the computer (tethering) it works with no problems.

#### What is your rclone version (output from `rclone version`)
rclone v1.53.1
- os/arch: linux/arm64
- go version: go1.15

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Android 11.

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
./rclone lsd myremote: --vv

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
1|blueline:/data/local/rclone # ./rclone lsd myremote: -vv
2020/09/28 08:43:31 DEBUG : rclone: Version "v1.53.1" starting with parameters ["./rclone" "lsd" "myremote:" "-vv"]
2020/09/28 08:43:31 DEBUG : Using config file from "/data/local/rclone/rclone.conf"
2020/09/28 08:43:31 DEBUG : Creating backend with remote "myremote:"
2020/09/28 08:43:31 DEBUG : myremote: Loaded invalid token from config file - ignoring
2020/09/28 08:43:32 DEBUG : myremote: Token refresh failed try 1/5: Post "https://oauth2.googleapis.com/token": dial tcp: lookup oauth2.googleapis.com on [::1]:53: read udp [::1]:49320->[::1]:53: read: connection refused
2020/09/28 08:43:33 DEBUG : myremote: Loaded invalid token from config file - ignoring
2020/09/28 08:43:33 DEBUG : myremote: Token refresh failed try 2/5: Post "https://oauth2.googleapis.com/token": dial tcp: lookup oauth2.googleapis.com on [::1]:53: read udp [::1]:43427->[::1]:53: read: connection refused
2020/09/28 08:43:34 DEBUG : myremote: Loaded invalid token from config file - ignoring
2020/09/28 08:43:34 DEBUG : myremote: Token refresh failed try 3/5: Post "https://oauth2.googleapis.com/token": dial tcp: lookup oauth2.googleapis.com on [::1]:53: read udp [::1]:46656->[::1]:53: read: connection refused
2020/09/28 08:43:35 DEBUG : myremote: Loaded invalid token from config file - ignoring
2020/09/28 08:43:35 DEBUG : myremote: Token refresh failed try 4/5: Post "https://oauth2.googleapis.com/token": dial tcp: lookup oauth2.googleapis.com on [::1]:53: read udp [::1]:38692->[::1]:53: read: connection refused
2020/09/28 08:43:36 DEBUG : myremote: Loaded invalid token from config file - ignoring
2020/09/28 08:43:36 DEBUG : myremote: Token refresh failed try 5/5: Post "https://oauth2.googleapis.com/token": dial tcp: lookup oauth2.googleapis.com on [::1]:53: read udp [::1]:39367->[::1]:53: read: connection refused
2020/09/28 08:43:37 DEBUG : pacer: low level retry 1/1 (error Get "https://www.googleapis.com/drive/v3/files/root?alt=json&fields=id&prettyPrint=false&supportsAllDrives=true": couldn't fetch token - maybe it has expired? - refresh with "rclone config reconnect myremote:": Post "https://oauth2.googleapis.com/token": dial tcp: lookup oauth2.googleapis.com on [::1]:53: read udp [::1]:39367->[::1]:53: read: connection refused)
2020/09/28 08:43:37 DEBUG : pacer: Rate limited, increasing sleep to 1.574907633s
2020/09/28 08:43:37 Failed to create file system for "myremote:": couldn't find root directory ID: Get "https://www.googleapis.com/drive/v3/files/root?alt=json&fields=id&prettyPrint=false&supportsAllDrives=true": couldn't fetch token - maybe it has expired? - refresh with "rclone config reconnect myremote:": Post "https://oauth2.googleapis.com/token": dial tcp: lookup oauth2.googleapis.com on [::1]:53: read udp [::1]:39367->[::1]:53: read: connection refused

**Comment by ncw** [comment]
Which binary did you use?

The standard linux/arm binary doesn't work properly on Android - android is just too different.

I do build an android linux/arm binary which you can find in the `testbuilds` directory, eg https://beta.rclone.org/v1.54.0-beta.4791.41ec712aa/testbuilds/

I think that works properly on android

Termux also builds an rclone for android which you can install with `pkg install rclone`.

**Comment by jd1900** [comment]
> Which binary did you use?
> 
> The standard linux/arm binary doesn't work properly on Android - android is just too different.
> 
> I do build an android linux/arm binary which you can find in the `testbuilds` directory, eg https://beta.rclone.org/v1.54.0-beta.4791.41ec712aa/testbuilds/
> 
> I think that works properly on android
> 
> Termux also builds an rclone for android which you can install with `pkg install rclone`.

It works now!
Thank you!
