### ISSUE TITLE
Rclone mount throws error but connects but does not let Git run

### ISSUE THREAD

**Issue by iaxat** [rclone/rclone#4639]
#### What is the problem you are having with rclone?
Rclone mount throws an error when it is put up for mounting my gdrive. 

#### What is your rclone version (output from `rclone version`)
rclone v1.53.1-DEV
- os/arch: darwin/amd64
- go version: go1.15.2

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
I am using Macos Catalina 10.57

####  Which cloud storage system are you using? (eg Google Drive)
google drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone --vfs-cache-mode writes mount gdrive: /Users/#####/Desktop/gdrive

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)
2020/09/29 00:17:28 ERROR : Failed to create vfs cache - disabling: failed to make cache directory: make cache directory failed: - // The Rclone directory

2020/09/29 00:17:28 NOTICE: macOS users: please try "rclone cmount" as it will be the default in v1.54

**Comment by darthShadow** [comment]
These are not the debug logs. Please add `-vv` to your mount command and add the logs obtained from that.

**Comment by ivandeex** [comment]
Closing due to 4 months of inactivity.

**Comment by iaxat** [comment]
Even after updating fuse to newer version. git is not working on the mounted drive, rclone mounting throws error but mounts it anyway. After mounting git clone does not work.

**Comment by darthShadow** [comment]
Please open a new thread and make sure to add the debug logs as requested.
