### ISSUE TITLE
Access to a socket was not permitted due to the access rights of the socket

### ISSUE THREAD

**Issue by xLogiiCx** [rclone/rclone#4642]
#### Output of `rclone version`
rclone v1.53.1
- os/arch: windows/amd64
- go version: go1.15

#### Describe the issue

I cannot Copy, Sync, ls or sth like this with my Remote. I always get following error. 
2020/09/30 11:27:22 Failed to create file system for "crypt:PWDB": failed to make remote "nextcloud:" to wrap: read metadata failed: Propfind "https://.your-storageshare.de/remote.php/dav/files/user/file": dial tcp xx.4.xxx.147:443: connectex: Access to a socket was not permitted due to the access rights of the socket. My Cloud Provider (NextCloud) shows that the App Token for Rclone was used secounds ago but rclone cannot access the files.

**Comment by animosity22** [comment]
You can use the https://forum.rclone.org for any general support as this seems to be a duplicate post as you had already posted there. Closing this out.
