### ISSUE TITLE
B2 backend should be able to automatically size chunks to fit in to 10,000 chunk limit

### ISSUE THREAD

**Issue by Adam-BZ** [rclone/rclone#4643]
#### What is your current rclone version (output from `rclone version`)?
1.53.1

#### What problem are you are trying to solve?
Just like Amazon S3, Backblaze B2 has a 10,000 chunk limit per file. Any user trying to upload a file larger than 937.5G (the default chunk size of 96M * 10000 chunks) has to manually configure a chunk size.

rclone's S3 backend supports automatically increasing chunk size to fit a file within that 10000 chunk limit, however rclone's B2 backend does not currently have that feature.

#### How do you think rclone should be changed to solve that?

Add the same automatic chunk size feature to the B2 backend, so instead of failing on files that are larger than chunk_size * 10000, it would increase chunk_size to accommodate them.

ncw mentioned there might be some concerns with memory usage since it may unpredictably increase depending on what file size rclone encounters, so perhaps this could be a non-default flag, or disabled with a flag if it is default. I think since the behavior between S3 and B2 is identical, any defaults or flags should be the same between the two backends if possible, just to keep a consistent user experience.

https://forum.rclone.org/t/b2-backend-dynamically-increasing-chunk-size/19288

**Comment by ncw** [comment]
Here is the relevant bit of code in the s3 backend

https://github.com/rclone/rclone/blob/20b00db3909906d782c3ee4f3c0aa5cfb4a92f23/backend/s3/s3.go#L2794-L2808

And here is the equivalent code in the b2 backend

https://github.com/rclone/rclone/blob/20b00db3909906d782c3ee4f3c0aa5cfb4a92f23/backend/b2/upload.go#L97-L108

Fancy having a go at this @Adam-BZ ?
