### ISSUE TITLE
Google Drive delete by moving to directory not to trash

### ISSUE THREAD

**Issue by bpaczkowski** [rclone/rclone#4644]
Google released a [statement](https://gsuiteupdates.googleblog.com/2020/09/drive-trash-auto-delete-30-days.html) that files in the trash will be automatically removed after 30. An alternative way of trashing items that would keep them available for historical purposes would be nice. The solution I'm thinking of would be to provide an option to move deleted files to a separate trash directory (keeping directory structure if possible). According to the statement the new behavior starts on October 13 but first files will be deleted 30 days after that so there's a little over a month left.

**Comment by darthShadow** [comment]
That doesn't work for mounts, does it?

**Comment by ncw** [comment]
> That doesn't work for mounts, does it?

You are right, it doesn't.

However for deletes at least it would be easy to make work.

**Comment by darthShadow** [comment]
I don't have much use for trash beyond 30 days so @bpaczkowski will need to chime in whether this satisfies his requirement or not. I just wanted to point out a shortcoming since I think that's where it will see the most use as a replacement.

**Comment by bpaczkowski** [comment]
@ncw thanks! I've searched through options but did not think to search for "backup". And yes, this does solve my use case as I'm not making heavy use of mounting.

**Comment by ncw** [comment]
Great :-) Glad that is working for you @bpaczkowski
