### ISSUE TITLE
Rclone sync is re-uploading entire data after modifying file contents

### ISSUE THREAD

**Issue by akkitech** [rclone/rclone#4646]
#### What is the problem you are having with rclone?
I've a sample text file of 25MB which I am transferring to the destination using sync command. The problem is as soon as I modify the file contents (ex: adding new text in the bottom) rclone sync uploads entire 25MB of data to the destination. Is this the expected behavior? I would expect rclone should only transfer the updated data (something in bytes in this case).

#### What is your rclone version (output from `rclone version`)
1.53.0

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10, 64 bit

####  Which cloud storage system are you using? (eg Google Drive)
WebDav

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone sync --progress source:path dest:path

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Transferred:       25.389M / 25.389 MBytes, 100%, 231.426 MBytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         0.2s

**Comment by darthShadow** [comment]
Yes, this is expected, since rclone doesn't support partial updates to files.

**Comment by animosity22** [comment]
Any further questions, please just ask on the forums https://forum.rclone.org

Thanks!
