### ISSUE TITLE
sftp should only ask for a password after the SSH connection has succeeded

### ISSUE THREAD

**Issue by sweharris** [rclone/rclone#4660]
With `known_hosts_file` changes, the user may be prompted for a password but then fail to connect because the host key is incorrect.  It's a better user experience to have the user prompted only if the SSH session succeeds.  This would also help if the remote server is down or unreachable for any reason.

It's also a minor security enhancement because it means the user doesn't need to enter their password more often than is necessary.

**Comment by sweharris** [comment]
This can be achieved by changing the AskPassword conditional to call `ssh.PasswordCallback()` and have that prompt for the password. 

So now if the `known_hosts` entry is wrong the user never gets prompted.

What's interesting is that if the connection succeeds but the password is wrong then the user gets _reprompted_ to enter the password:

eg

```
$ ./rclone --config /tmp/testsftp/rclone.conf ls test2:/tmp/test
Enter SFTP password: 
Enter SFTP password: 
Enter SFTP password: 
        0 this_is_on_test2
```

This is a change in behaviour, where the user previously just got thrown out, but I think it's a worthwhile change and definitely enhances interactive behaviour.

**Comment by ncw** [comment]
> This is a change in behaviour, where the user previously just got thrown out, but I think it's a worthwhile change and definitely enhances interactive behaviour.

Yes that looks much better.

**Comment by ncw** [comment]
Thank you for doing this - these little improvements really add up to making rclone more usable. 

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54

**Comment by zanna-37** [comment]
Something weird is happening after this. rclone keeps asking me the SFTP password after the previous time (so during operations). My guess is that when the connection gets closed for some reason it asks the password again.

See row 3
```
2020/10/08 14:08:25 DEBUG : /folder/folder: >Getattr: errc=0
2020/10/08 14:08:25 DEBUG : /folder/file.extension: Getattr: fh=0xFFFFFFFFFFFFFFFF
Enter SFTP password: 2020/10/08 14:08:25 DEBUG :/folder/file.extension: >Getattr: errc=-2
2020/10/08 14:08:25 DEBUG : /folder: Releasedir: fh=0x3
2020/10/08 14:08:25 DEBUG : /folder: >Releasedir: errc=0
```

**Comment by sweharris** [comment]
Hmm, it will, yes.  

So we have two options with the SSH Library:  First is to ask for the password before hand, and just pass that to SSH as a constant.  That's the old behaviour.  The second is to let SSH call us for the password when it needs it.  That's the new behaviour.  And so if the ssh connection aborts for any reason then the library will re-ask for the password if it needs it.

I can think of one work-around, and that's to have us remember what was entered first time.  So next time SSH asks for it, we just return what was previously given.  This will remove the "got the password wrong, retry" ability.  Well, we never had that before, so it's no big loss.

**Comment by ncw** [comment]
I've merged @sweharris fix to master now - can you give a test @zanna-37 ? Thanks to you both :-)

**Comment by zanna-37** [comment]
It works for me! Thank you very much!
