### ISSUE TITLE
Move the config location on Windows to a proper directory that follows windows standards

### ISSUE THREAD

**Issue by MrCaspan** [rclone/rclone#4667]
When looking for most Windows application config files they are normally in the C:\Users\{User}\AppData\Local\  or \Roaming folder. rclone chose to use the C:\Users\{User}\.config\ folder. It's not a huge deal but it does not really help windows user that are used to this format to find configs for an app. So i was just curious if this is for a good reason why it is here and does not follow the normal windows convention? Maybe in the future we can think about moving it there?

**Comment by ncw** [comment]
It follows that convention to be consistent with rclone on other platforms. Not a great reason, I'd agree.

Note that you can find the config file on any platform with `rclone config file`

**Comment by MrCaspan** [comment]
No worries just curious if anyone had ever brought it up is all

**Comment by ncw** [comment]
I don't think it has ever been mentioned before.

It would be possible to change it as long as we look for the config in the old place too.

**Comment by MrCaspan** [comment]
Just an IT admin and I live in Windows land so this is the default place that any app data should place its data normally. Does not mean it HAS to but just food for thought is all in future builds if it even maters!

**Comment by ncw** [comment]
Can you explain what is the difference between C:\Users{User}\AppData\Local\ or \Roaming ? What is the official way of working out where to store your config?

**Comment by MrCaspan** [comment]
So in an Active Directory environment you may have what is called a roaming user that can go to any machine in the office and log in. Anything that is stored in the Roaming folder is copied back to the AD server when they log off. And any machine they log on will copy down this folder so that the next machine they log into will have this data on that machine. The Local folder is basically you installed it on this one machine and you don't want this data to travel with the user account. A lot of programmers just use the Roaming folder because it's the best of both worlds and lets say for instance we wanted to make sure rclone was installed on every machine then having the config move with the user is perfect if you forced only local then they would have to config it again on every machine they go to. Some have no idea how their app will be used so they use the roaming folder instead of the local folder. Some know exactly how they want the app to be used and it should only ever be on the machine it was installed on.

I would think in this case that the roaming folder is the best choice to place it as you don't know how rclone will be deployed it will be able to work both ways local and roaming. Just my opinion though!

**Comment by MrCaspan** [comment]
https://www.quora.com/What-is-the-difference-between-the-AppData-Roaming-Local-and-LocalLow-directories-for-in-Windows-10

**Comment by ivandeex** [comment]
@MrCaspan
1. rclone config location on Windows is explicitly documented at rclone.org
2. changing config location would break existing installations (and we don't want to make users angry)
3. in a Active Directory domain / corporate environment the user's home normally roams together with "AppData\Roaming"
4. this is just a default. if you have a strict config location policy, you are free to set user's environment `%RCLONE_CONFIG% to point elsewhere.
cc @ncw

**Comment by albertony** [comment]
I think moving to `%AppData%` or `%LocalAppData%` as default on Windows is a good idea, I agree it is much more "Windows standard" - although I do have some dot-folders in my `%USERPROFILE%` (`.dotnet`, `.nuget`, etc., annoyingly enough)


> 2. changing config location would break existing installations (and we don't want to make users angry)

Not if just changing what is the default for a new configuration file when no existing is found? Rclone already looks through a list of possible locations, and first existing config file found will be used. So by adding a new location at the end of this search-list would not break anything, I think.

I don't know which of `%AppData%` (Roaming) or `%LocalAppData%` would be better...

Cache dir is already defaulting to `%LocalAppData%\rclone`, and webgui also uses this location (last time I checked).

**Comment by ivandeex** [comment]
> I think moving to `%AppData%` or `%LocalAppData%` as default on Windows is a good idea, I agree it is much more "Windows standard" - although I do have some dot-folders in my `%USERPROFILE%` (`.dotnet`, `.nuget`, etc., annoyingly enough)

I suggest the following config search order on Windows:

1. `%AppData%` (Roaming)  - to align with Windows standards
2. ~/.config/rclone/rclone.config - for compatibility
3. ~/.rclone.conf - also for compatibility

Currently rclone supports locations 2 and 3 on any OS.
Let's prepend location 1 on Windows as the primary location.
`rclone config` and `install.sh` should by default create new configs at location 1.

_the wolves are fed, the sheep are safe_ :sheep: 

> I don't know which of `%AppData%` (Roaming) or `%LocalAppData%` would be better...

`%AppData%` (Roaming) is the right place. In corporate environments (I've been a corporate employee for years) it will be restored from a central profile storage upon user login to domain and saved thereto at logoff.

> Cache dir is already defaulting to `%LocalAppData%\rclone`, and webgui also uses this location (last time I checked).

Correct. Cache should local to the machine where rclone is running.

**Comment by albertony** [comment]
There is the local config option also, it must have top priority:

1. \<rclone_exe_dir\>/rclone.conf
2. %AppData%/rclone/rclone.conf (default when creating new)
3. ~/.config/rclone/rclone.conf
4. ~/.rclone.conf

Currently the following is also considered, even on Windows:
`%XDG_CONFIG_HOME%\rclone\rclone.conf`

You suggest we just drop this entirely - on Windows? That will potentially be a breaking change, but would be a bit surprising if it affects anyone at all...

The documentation also seems to indicate that .rclone.conf will be picked up as well as rclone.conf, but I think this is wrong - and it will only be picked up at root of home (I think maybe I wrote this myself, so not blaming anyone... :)

> Normally the config file is in your home directory as a file called .config/rclone/rclone.conf (or .rclone.conf if created with an older version). If $XDG_CONFIG_HOME is set it will be at $XDG_CONFIG_HOME/rclone/rclone.conf.

I can have a go at this..

**Comment by ivandeex** [comment]
> You suggest we just drop this entirely - on Windows? That will potentially be a breaking change, but would be a bit surprising if it affects anyone at all...

Thank you for correction. I completely forgot about XDG stuff.

**Comment by ivandeex** [comment]
> There is the local config option also, it must have top priority:
> 1. <rclone_exe_dir>/rclone.conf

Thank you for correction (2). I didn't know about that location.

**Comment by albertony** [comment]
> Thank you for correction. I completely forgot about XDG stuff.

So you think %XDG_CONFIG_HOME% should still be considered on Windows, to be 100% backwards compatible?

**Comment by ivandeex** [comment]
> So you think %XDG_CONFIG_HOME% should still be considered on Windows, to be 100% backwards compatible?

Do you think we should drop or deprecate it?
Frankly, I don't really care about supporting XDG guidelines (or standard) particularly on Windows.
OTOH if it has been documented and supported for some time, and having it supported in future doesn't cost us anything,
then why not?

With your comments the proposed search path on Windows (when `--config` is omitted) becomes:

1. <rclone_exe_dir>/rclone.conf
2. %AppData%/rclone/rclone.conf (default when creating new)
3. %XDG_CONFIG_HOME%\rclone\rclone.conf
4. ~/.config/rclone/rclone.conf
5. ~/.rclone.conf

Probably location 4 can be skipped if XDG_CONFIG_HOME is set.

**Comment by albertony** [comment]
I

> Frankly, I don't really care about supporting XDG guidelines (or standard) particularly on Windows.

totally

> OTOH if it has been documented and supported for some time, and having it supported in future doesn't cost us anything,
then why not?

agree.

And actually there is a 6. entry according to existing code 😆 

> Default to ./.rclone.conf (current working directory) if everything else fails.
