### ISSUE TITLE
PROTOCOL_ERROR on S3

### ISSUE THREAD

**Issue by armsby** [rclone/rclone#4673]
#### What is the problem you are having with rclone?
Then using rclone mount I have been seeing errors like this: Dir.Stat error: SerializationError: failed to decode REST XML response
status code: 200, request id: 163C63E6DEB02A2C
caused by: stream error: stream ID 19137; PROTOCOL_ERROR

this goes away only with a restart of the rclone mount,
after a small talk with darthShadow, it was suspected that it was http2 that is causing the issue, 
after running some test where http2 was disabled in rclone the issue has not appeared.

a flag to disable http2 for s3 would be nice

#### What is your rclone version (output from `rclone version`)
rclone v1.53.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu

####  Which cloud storage system are you using? (eg Google Drive)
S3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
stress an S3 mount and you will see it

**Comment by ncw** [comment]
Are you using this with AWS S3?

> stress an S3 mount and you will see it

Do you have a recipe for that?

This is almost certainly a bug in one of
- go http2 library
- aws s3 sdk
- s3 servers

It would be nice to get to the bottom of which...

Can you dump the response? You'd do that with `-vv --dump responses`. I relalise that may be tricky depending on how you are stressing the backend.

Which go version is your rclone compiled with? `rclone version` will tell you?

@darthShadow did you manage to reproduce this yourself?

**Comment by darthShadow** [comment]
This is with minio proxied via Cloudflare. I have heard reports of it happening directly with minio too, however.

I am guessing this is another bug with the golang http/2 library since it looks very similar to the one we are facing with google drive.

I haven't gotten a chance to reproduce it myself. I will be doing some testing for the same the next month so I will try to debug it further then.

**Comment by armsby** [comment]
that patch that darthShadow provided worked, I will try to run a rclone without it, both over cloudflare and without, and I hope that I can catch it again

**Comment by ncw** [comment]
I've merged @darthShadow 's fix for this this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54
