### ISSUE TITLE
Flag help is inconsistent wrt periods

### ISSUE THREAD

**Issue by jsoref** [rclone/rclone#4679]
#### What is the problem you are having with rclone?

The help has a couple of styles for punctuation:
https://github.com/rclone/rclone/blame/510ac341e193976171d29b8aeb81a30a37cfd2a1/docs/content/flags.md#L31-L32 (this was `master` as of the time of the creation of this report):
>      --config string                        Config file. (default "$HOME/.config/rclone/rclone.conf")
>      --contimeout duration                  Connect timeout (default 1m0s)

The first item here ends w/ a `.`, the second does not. Neither are "sentences" particularly.

There are occasionally instances of multiple sentences:
>      --disable string                       Disable a comma separated list of features.  Use help to see a list.
>      --user-agent string                    Set the user-agent to a specified string. The default is rclone/ version (default "rclone/v1.53.0")

In this second instance, it's more like 1 1/2 sentences.

**Comment by jsoref** [comment]
I understand that this is generated content, but it's a convenient way to compare the various divergent files.

I actually ran into this while using `rclone config` and creating an `s3` bucket and going through to the advanced options.
Most things were like:
```
sse_customer_key>
If using SSE-C you must provide the secret encryption key MD5 checksum.
Enter a string value. Press Enter for the default ("").
```
but later I hit:
```
sse_customer_key_md5>
Cutoff for switching to chunked upload

Any files larger than this will be uploaded in chunks of chunk_size.
```

I've started working on this here: https://github.com/jsoref/rclone/tree/grammar, but w/o knowing whether to add/remove `.`s, I'm going to pause.

One approach is to treat these items as titles, in which case it reads slightly better w/o `.`s.

**Comment by ncw** [comment]
Note that the first lines of backend help messages also go straight into the docs, eg [--s3-acl](https://rclone.org/s3/#s3-acl) so I think we need full stops here.

      --s3-acl string   Canned ACL used when creating buckets and storing or copying objects.

I looked at some unix commands to see whether they use full stops in the help

No full stop

- rsync
- ls
- as

Full stop

- gcc

One thing we could do is remove full stops from strings programatically when creating the command line flags (or add them), this would be easy to do.

I think I prefer the look of the flags without full stops probably.

But I think the backend help messages probably should have full stops.

**Comment by edwardxml** [comment]
I know this discussion sounds trivial but consistency - either way - does look so much better.
