### ISSUE TITLE
Copying file from s3 to s3 results in empty md5 checksum if source has empty checksum

### ISSUE THREAD

**Issue by ThiefMaster** [rclone/rclone#4687]
#### What is the problem you are having with rclone?

When copying a file from a s3 bucket to another s3 bucket and the source file has no (or an empty, not sure) checksum, then the target file will have no checksum either. If I manually copy the file to my local system first and then copy it to the target bucket, the checksum is present.

I would expect the checksum to be set in the first case as well. FWIW, I do not know why the checksum is missing on my source bucket. In case it matters, the file was copied there from a normal file system (AFS) with rclone as well not too long ago.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.53.0-DEV
- os/arch: linux/amd64
- go version: go1.14.7
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

Gentoo, 64-bit

####  Which cloud storage system are you using? (eg Google Drive)

Ceph S3

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

```
[adrian@blackhole:~/dev/indico/src:master $]> rclone hashsum MD5 s3-backup-prevessin:adrian-test-2/event/926804/event/3550126-3306548-2020_VS_PPFS_Ye.mp4
                                  3550126-3306548-2020_VS_PPFS_Ye.mp4

[adrian@blackhole:~/dev/indico/src:master $]> rclone copyto -vvP s3-backup-prevessin:adrian-test-2/event/926804/event/3550126-3306548-2020_VS_PPFS_Ye.mp4 s3-backup-prevessin:adrian-test-manual/md5test-direct.mp4
2020/10/15 23:08:14 DEBUG : rclone: Version "v1.53.0-DEV" starting with parameters ["rclone" "copyto" "-vvP" "s3-backup-prevessin:adrian-test-2/event/926804/event/3550126-3306548-2020_VS_PPFS_Ye.mp4" "s3-backup-prevessin:adrian-test-manual/md5test-direct.mp4"]
2020/10/15 23:08:14 DEBUG : Using config file from "/home/adrian/.config/rclone/rclone.conf"
2020/10/15 23:08:14 DEBUG : Creating backend with remote "s3-backup-prevessin:adrian-test-2/event/926804/event/3550126-3306548-2020_VS_PPFS_Ye.mp4"
2020/10/15 23:08:14 DEBUG : fs cache: adding new entry for parent of "s3-backup-prevessin:adrian-test-2/event/926804/event/3550126-3306548-2020_VS_PPFS_Ye.mp4", "s3-backup-prevessin:adrian-test-2/event/926804/event"
2020/10/15 23:08:14 DEBUG : Creating backend with remote "s3-backup-prevessin:adrian-test-manual/"
2020/10/15 23:08:14 DEBUG : fs cache: renaming cache item "s3-backup-prevessin:adrian-test-manual/" to be canonical "s3-backup-prevessin:adrian-test-manual"
2020-10-15 23:08:14 DEBUG : 3550126-3306548-2020_VS_PPFS_Ye.mp4: Need to transfer - File not found at Destination
2020-10-15 23:08:14 INFO  : S3 bucket adrian-test-manual: Bucket "adrian-test-manual" created with ACL "private"
2020-10-15 23:08:40 INFO  : 3550126-3306548-2020_VS_PPFS_Ye.mp4: Copied (server side copy)
Transferred:      616.332M / 616.332 MBytes, 100%, 23.814 MBytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:        25.9s
2020/10/15 23:08:40 INFO  :
Transferred:      616.332M / 616.332 MBytes, 100%, 23.814 MBytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:        25.9s

2020/10/15 23:08:40 DEBUG : 4 go routines active

[adrian@blackhole:~/dev/indico/src:master $]> rclone hashsum MD5 s3-backup-prevessin:adrian-test-manual/md5test-direct.mp4
                                  md5test-direct.mp4
```

If I copy the file to my local system first and then back to S3, the checksum is present. FWIW, I do not know why the checksum in the source is missing/empty.

**Comment by ThiefMaster** [comment]
This actually seems to be a bug since s3cmd shows the checksum while rclone doesn't:

```
[adrian@blackhole:~/dev/indico/src:master $]>  rclone hashsum MD5 s3-backup-prevessin:adrian-test-manual/md5test-direct.mp4
                                  md5test-direct.mp4

[adrian@blackhole:~/dev/indico/src:master $]> s3cmd -c ~/.s3cfg.backup-prevessin info s3://adrian-test-manual/md5test-direct.mp4
s3://adrian-test-manual/md5test-direct.mp4 (object):
   File size: 646271315
   Last mod:  Thu, 15 Oct 2020 21:08:40 GMT
   MIME type: video/mp4
   Storage:   STANDARD
   MD5 sum:   e160bcdc1fdf74b9df0c229b4c88fee9-124
   SSE:       none
   Policy:    none
   CORS:      none
   ACL:       Indico: FULL_CONTROL
   x-amz-meta-mtime: 1601277787.000000001
```

**Comment by ThiefMaster** [comment]
OK, I think this happens because of the `MD5 sum:   e160bcdc1fdf74b9df0c229b4c88fee9-124` which is not a valid MD5 sum (and even without the `-124` there it's nto the md5 sum of the actual file!).

A file uploaded manually via `copyto` contains `x-amz-meta-md5chksum` which contains the correct checksum. That header is missing in the file copied via the `rclone copy`...

**Comment by ThiefMaster** [comment]
The weird broken hash in the ETag field happens when rclone does a multipart upload. If I copy from my local filesystem with `--s3-upload-cutoff 5G` then it's correct in the ETag (and no `x-amz-meta-md5chksum`) gets added.

**Comment by ThiefMaster** [comment]
https://stackoverflow.com/a/33027492/298479

So the etag on S3 files with chunked upload is not just the md5. Maybe rclone should take this hash format into account and support it, so this type of hash can actually be compared during a sync?

**Comment by ncw** [comment]
> When copying a file from a s3 bucket to another s3 bucket and the source file has no (or an empty, not sure) checksum, then the target file will have no checksum either. 

For a large file the md5 sum is held as metadata (as you've discovered) and if it isn't there then rclone can't re-create it without downloading the file. So if the source didn't have `x-amz-meta-md5chksum` then the destination won't either.

> If I manually copy the file to my local system first and then copy it to the target bucket, the checksum is present.

This is because once the file is on the local system then rclone can MD5 it easily.

> FWIW, I do not know why the checksum is missing on my source bucket. In case it matters, the file was copied there from a normal file system (AFS) with rclone as well not too long ago.

This is the unexpected part for me. Rclone should have added a checksum unless you used `--s3-disable-checksum` or added `disable_checksum` into your config.

> The weird broken hash in the ETag field happens when rclone does a multipart upload. If I copy from my local filesystem with `--s3-upload-cutoff 5G` then it's correct in the ETag (and no `x-amz-meta-md5chksum`) gets added.

If you want your Etag to match your MD5sum then this is the only way you can do it for large files. Uploading like this is a bit slower since rclone can't upload multiple chunks at once but it is still quite quick.

> So the etag on S3 files with chunked upload is not the file's md5. Maybe rclone should take this hash format into account and support it, so this type of hash can actually be compared during a sync?

Unfortunately you can't (in the general case) work out what that non MD5 hash is unless you know exactly how big the chunks were used in the upload.

**Comment by ncw** [comment]
I'm going to close this since I think rclone is working as expected.
