### ISSUE TITLE
Dedupe with 3 folders

### ISSUE THREAD

**Issue by mtnjustme** [rclone/rclone#4691]
If 3 folder have the same name at a specific remote then it might delete full folders, my assumption is that the deletion is based on the folder name and not its idea (removing folders).
I've managed in my tests to delete around 95%+ from 3 folders (perhaps even possible to delete 100% if used right).
My suggestion in addition to this, since i've already experienced many issues with dedupe, is to add an option to only rename duplicated folders instead of merging them.
Thanks in advance.

Edit :
In order to reproduce such dedupe errors, run the dedupe command on the same remote multiple times

**Comment by mtnjustme** [comment]
Also if you have nested folder with the same name it might delete folders and not merge them correctly.

**Comment by Bremonterro1** [comment]
Hmm....Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: mtnjustme <notifications@github.com> Date: 10/18/20  12:31 PM  (GMT-06:00) To: rclone/rclone <rclone@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [rclone/rclone] Dedupe with 3 folders (#4691) 
Also if you have nested folder with the same name it might delete folders and not merge them correctly.

**Comment by ncw** [comment]
> If 3 folder have the same name at a specific remote then it might delete full folders, my assumption is that the deletion is based on the folder name and not its idea (removing folders).

I tried to replicate but couldn't.

Can you tell me exactly how to replicate please?

Also which version of rclone are you using?

**Comment by mtnjustme** [comment]
> 
> 
> > If 3 folder have the same name at a specific remote then it might delete full folders, my assumption is that the deletion is based on the folder name and not its idea (removing folders).
> 
> I tried to replicate but couldn't.
> 
> Can you tell me exactly how to replicate please?
> 
> Also which version of rclone are you using?

instead, can't u just change dedupe to rename the folders?
there are more problems with dedupe as i said, like nested folders with the same name.

**Comment by ncw** [comment]
> instead, can't u just change dedupe to rename the folders?

That is possible - yes

> there are more problems with dedupe as i said, like nested folders with the same name.

Ideally I'd like to see a demo of these problems and once I've worked out what they are I can fix them.

**Comment by mtnjustme** [comment]
> 
> 
> > instead, can't u just change dedupe to rename the folders?
> 
> That is possible - yes
> 
> > there are more problems with dedupe as i said, like nested folders with the same name.
> 
> Ideally I'd like to see a demo of these problems and once I've worked out what they are I can fix them.

have 3 folders with the same name, inside each have a folder that is the same sub folder copied between those 3, and have 1 sub folder inside each that is different in each, run dedupe, used google drive.
folders :
1:
test/a
test/b

2:
test/a
test/c

3:
test/a
test/d

all of the folders and the sub folders have a single file in them, the folder that's the same sub folder has files that are the same and also ones that are different (a/same.txt a/a.txt a/b.txt a/c.txt)

run dedupe.

**Comment by mtnjustme** [comment]
also this issue:
https://forum.rclone.org/t/how-to-use-dedupe-on-gdrive-correctly/4802/3

**Comment by ncw** [comment]
I made a directory tree like this all the `afile.txt` and `bfile.txt` are the same, all the `afile2.txt` are different.

```
$ rclone tree drive:test/issue-4691.bak
/
├── test
│   ├── a
│   │   ├── afile.txt
│   │   └── afile2.txt
│   └── b
│       └── bfile.txt
├── test2
│   ├── a
│   │   ├── afile.txt
│   │   └── afile2.txt
│   └── b
│       └── bfile.txt
└── test3
    ├── a
    │   ├── afile.txt
    │   └── afile2.txt
    └── b
        └── bfile.txt
```

I then renamed `test2` and `test3` to `test` in the drive web interface.

I then ran `rclone -vv dedupe` on it

```
$ rclone dedupe -vv drive:test/issue-4691
2020/11/03 11:01:53 DEBUG : rclone: Version "v1.54.0-DEV" starting with parameters ["rclone" "dedupe" "-vv" "drive:test/issue-4691"]
2020/11/03 11:01:53 DEBUG : Using config file from "/home/ncw/.rclone.conf"
2020/11/03 11:01:53 DEBUG : Creating backend with remote "drive:test/issue-4691"
2020/11/03 11:01:54 INFO  : Google drive root 'test/issue-4691': Looking for duplicates using interactive mode.
2020/11/03 11:01:55 INFO  : test: Merging contents of duplicate directories
2020/11/03 11:01:55 INFO  : test: merging "a"
2020/11/03 11:01:57 INFO  : test: merging "b"
2020/11/03 11:02:00 INFO  : test: removing empty directory
2020/11/03 11:02:01 INFO  : test: merging "b"
2020/11/03 11:02:02 INFO  : test: merging "a"
2020/11/03 11:02:02 INFO  : test: removing empty directory
2020/11/03 11:02:03 INFO  : test/a: Merging contents of duplicate directories
2020/11/03 11:02:03 INFO  : test/a: merging "afile2.txt"
2020/11/03 11:02:03 INFO  : test/a: merging "afile4.txt"
2020/11/03 11:02:05 INFO  : test/a: merging "afile3.txt"
2020/11/03 11:02:06 INFO  : test/a: merging "afile.txt"
2020/11/03 11:02:06 INFO  : test/a: removing empty directory
2020/11/03 11:02:08 INFO  : test/a: merging "afile2.txt"
2020/11/03 11:02:08 INFO  : test/a: merging "afile2.txt"
2020/11/03 11:02:09 INFO  : test/a: merging "afile4.txt"
2020/11/03 11:02:09 INFO  : test/a: merging "afile.txt"
2020/11/03 11:02:10 INFO  : test/a: removing empty directory
2020/11/03 11:02:10 INFO  : test/b: Merging contents of duplicate directories
2020/11/03 11:02:10 INFO  : test/b: merging "bfile.txt"
2020/11/03 11:02:11 INFO  : test/b: removing empty directory
2020/11/03 11:02:12 INFO  : test/b: merging "bfile.txt"
2020/11/03 11:02:12 INFO  : test/b: removing empty directory
2020/11/03 11:02:14 NOTICE: test/a/afile2.txt: Found 3 files with duplicate names
test/a/afile2.txt: 3 duplicates remain
  1:            7 bytes, 2020-11-03 11:00:17.394000000, MD5 d144b8af3d8f991bf90ed26d4ac2fc93
  2:            7 bytes, 2020-11-03 10:59:50.352000000, MD5 c50b33076305131cf486d8c599f3eb0d
  3:            7 bytes, 2020-11-03 10:57:15.446000000, MD5 a10edbbb8f28f8e98ee6b649ea2556f4
s) Skip and do nothing
k) Keep just one (choose which in next step)
r) Rename all to be different (by changing file.jpg to file-1.jpg)
s/k/r> r
2020/11/03 11:02:27 INFO  : test/a/afile2-1.txt: renamed from: test/a/afile2.txt
2020/11/03 11:02:28 INFO  : test/a/afile2-2.txt: renamed from: test/a/afile2.txt
2020/11/03 11:02:28 INFO  : test/a/afile2-3.txt: renamed from: test/a/afile2.txt
2020/11/03 11:02:28 NOTICE: test/a/afile.txt: Found 3 files with duplicate names
2020/11/03 11:02:28 NOTICE: test/a/afile.txt: Deleting 2/3 identical duplicates (MD5 b1946ac92492d2347c6235b4d2611184)
2020/11/03 11:02:29 INFO  : test/a/afile.txt: Deleted
2020/11/03 11:02:29 INFO  : test/a/afile.txt: Deleted
2020/11/03 11:02:29 NOTICE: test/a/afile.txt: All duplicates removed
2020/11/03 11:02:29 NOTICE: test/b/bfile.txt: Found 3 files with duplicate names
2020/11/03 11:02:29 NOTICE: test/b/bfile.txt: Deleting 2/3 identical duplicates (MD5 a10edbbb8f28f8e98ee6b649ea2556f4)
2020/11/03 11:02:30 INFO  : test/b/bfile.txt: Deleted
2020/11/03 11:02:30 INFO  : test/b/bfile.txt: Deleted
2020/11/03 11:02:30 NOTICE: test/b/bfile.txt: All duplicates removed
2020/11/03 11:02:30 DEBUG : 16 go routines active
```

This then left me with

```
$ rclone tree drive:test/issue-4691
/
└── test
    ├── a
    │   ├── afile.txt
    │   ├── afile2-1.txt
    │   ├── afile2-2.txt
    │   └── afile2-3.txt
    └── b
        └── bfile.txt
```

Which was what I was expecting.

I've attached a zip file of the starting directory structure (before the rename to `test`) - can you modify it to show the problem you are seeing?

[issue-4691.zip](https://github.com/rclone/rclone/files/5480796/issue-4691.zip)

**Comment by ivandeex** [comment]
@mtnjustme Please provide requested info

**Comment by ivandeex** [comment]
Closed after 3 months of inactivity
