### ISSUE TITLE
Progress shows weird characters in PowerShell

### ISSUE THREAD

**Issue by xps** [rclone/rclone#4693]
Hi

Whenever I use the -P parameter in PowerShell, I get some weird characters where, I suppose, a command to clear the current line is sent:

![rclone](https://user-images.githubusercontent.com/868945/96348726-89155880-10b3-11eb-9873-f518faa003b2.png)

I found this [similar issue](https://github.com/rclone/rclone/issues/2623) but it was supposedly resolved by a Windows update a long time ago, and I am up to date.

It works fine in the Windows Command Prompt, the problem only occurs in PowerShell.

rclone version: 1.53.1
Windows Version: Windows 10 Pro 19041.572
PowerShell version: 5.1.19041.546

**Comment by ncw** [comment]
Hmm, those are terminal escape sequences so it looks like rclone has detected your Powershell console as being a VT100 terminal by mistake.

I think that might be because you have a `TERM` environment variable set - is that the case?

**Comment by xps** [comment]
You're right, I have `TERM = cygwin`.

I do have cygwin installed (it comes with git for Windows).

Interestingly, I just tried PowerShell hosted in the new Windows Terminal (has the same environment variable) but the problem does not occur there.

**Comment by ncw** [comment]
> You're right, I have `TERM = cygwin`.

If you unset TERM then I expect it will work properly.

> Interestingly, I just tried PowerShell hosted in the new Windows Terminal (has the same environment variable) but the problem does not occur there.

Does the new Windows Terminal understand VT100 escape sequences by any chance? Reading the docs, I think it does, so that explains why it works there.

About the original issue - assuming unsetting TERM works do you think this is worth fixing in a different way?

**Comment by xps** [comment]
Yes, removing the TERM variable fixes it.

I don't know if it's worth fixing it. On the one hand it is easy to remove the variable, on the other, I don't know what impact this has on cygwin (I don't use it), and anyone with git for Windows installed would be affected.

Thanks for finding the culprit!

**Comment by ncw** [comment]
I don't think it is particularly easy for rclone to determine that it is running in a powershell console.

Paradoxically the TERM detection is the bit that makes running in git shell work properly!

I'm going to close this issue for the moment - if any other people complain about it, I'll consider whether there is a better way of fixing it!
