### ISSUE TITLE
ncdu: add sort by average size in a directory

### ISSUE THREAD

**Issue by left1000** [rclone/rclone#4699]
I love rclone ncdu, but you know what would be a cool new sort mode? size divided by count.

That's basically it. That would then let you sort by average filesize within a folder. I keep finding myself wanting to find where I can spend the least amount of my human time looking at something to gain the largest amount of disk space. I used to think sorting by size was good enough, then while I was sorted by size I found a folder with 2000 files in it, next to a folder with 10 files in it. Both of them essentially right next to each other on any du scan when sorted by size. Obviously it's a lot easier to consider freeing up 100gb if it's 10 files than if it's 2000 files.

**Comment by ncw** [comment]
This would be a reasonably good first issue if someone wanted to have a go.

It needs a new sort mode defining (`sortByAverageSize`), a new key to access it and the sorting code changing

https://github.com/rclone/rclone/blob/ffdd0719e761a3c76c06903df5daf36958dee772/cmd/ncdu/ncdu.go#L497-L506

**Comment by ncw** [comment]
This is done now thanks to @adamplansky 

[v1.54.0-beta.4848.e00bf3d72](https://beta.rclone.org/v1.54.0-beta.4848.e00bf3d72/) on branch [master](https://github.com/rclone/rclone/tree/master) (uploaded in 15-30 mins)

Try the A key :-)

I think we might need a display average size option too - but tell us what you think @left1000

**Comment by left1000** [comment]
You'd think that display average size would be required, and my OCD definitely would appreciate it, but actually.... that information isn't something I actually need. Weirdly looking at total file sizes sorted by average size... sort of just does the job. Since the job is me looking for a problem I can solve.

I'm not sure where you'd want to display that information. It would take up pretty valuable screen real estate, although, if EVERYONE liked this mode, then yeah it'd be worth displaying that information, but well, if hardly anyone but me cares? Then maybe it's best to leave it hidden?

**Comment by ncw** [comment]
> You'd think that display average size would be required, and my OCD definitely would appreciate it, but actually.... that information isn't something I actually need. Weirdly looking at total file sizes sorted by average size... sort of just does the job. Since the job is me looking for a problem I can solve.

:-)

> I'm not sure where you'd want to display that information. It would take up pretty valuable screen real estate, although, if EVERYONE liked this mode, then yeah it'd be worth displaying that information, but well, if hardly anyone but me cares? Then maybe it's best to leave it hidden?

If we did do it, then it would be another toggle to view.

> EDIT: Real world example of a problem this solved. Turns out my windows user folder was 50% aborted mega.nz downloads (despite being like 10,000 files and 2 downloads), and I was going to create backups of incompleted aborted downloads of files that would be worthless. Google chrome doesn't do a good job of showing this information as it's hidden inside a buncha random nested folders in the middle of no where, but ncdu or I admit, any du tool solves this problem easily. I like having a du tool though that I can use both on my cloud backup AND on my local files, seemlessly choosing between them without having to faff about choosing another du.

I just used it to discover I had 1 GB of vagrant files I had no idea about!

**Comment by adamplansky** [comment]
I think it is odd to be able to sort by average size in directory and not to be able to show this information in ncdu. So I implemented this toggle option in my last pull request. https://github.com/rclone/rclone/pull/4716 try the key 'a'
