### ISSUE TITLE
onedrive: remove `%` and `#` from the set of encoded characters

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#4700]
The [microsoft onedrive docs](https://support.microsoft.com/en-us/office/invalid-file-names-and-file-types-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa#invalidcharacters) has this table about invalid characters in onedrive and onedrive business

![image](https://user-images.githubusercontent.com/536803/96891876-fee93d80-1480-11eb-87b3-4e3681008c5d.png)

However the set rclone uses is

| Character | Value | Replacement |
| --------- |:-----:|:-----------:|
| "         | 0x22  | ＂          |
| *         | 0x2A  | ＊          |
| :         | 0x3A  | ：          |
| <         | 0x3C  | ＜          |
| >         | 0x3E  | ＞          |
| ?         | 0x3F  | ？          |
| \         | 0x5C  | ＼          |
| \|        | 0x7C  | ｜          |
| #         | 0x23  | ＃          |
| %         | 0x25  | ％          |

Which includes `%` and `#` where it probably shouldn't for onedrive home.

However if I actually use rclone's test program to see what characters you can store I get this

![image](https://user-images.githubusercontent.com/536803/96891961-11fc0d80-1481-11eb-8baf-9d33a342a7f2.png)

This is a little difficult to interpret but it tries each character at the Left, Middle and Right of a file and checks it can Write it, Get it and List it.

Onedrive home and business test remarkably similar with onedrive business not allowing a `'` on the end of a string but both allowing `#` and `%` which rclone currently escapes.

So probably the correct thing (ignoring backwards compatibility) would be to remove `#` and `%` from the onedrive encoding. This will then match the Windows encoding which is probably sensible and this will match what onedrive and onedrive business actually allow.

Removing characters from the encoding has the potential for rclone to have to re-upload files which can confuse users though.

@Cnly do you have any thoughts about this?

Also I haven't got a sharepoint to test.

See: https://forum.rclone.org/t/onedrive-file-names-with-converted-to-non-ascii-equivalent/19871/

**Comment by Cnly** [comment]
Sorry for the delay! Ignoring backward compatibility, I think the most correct thing to do will be to get an accurate and complete list of problematic symbols and reduce the need for changes in the future as much as possible. And you've presented a brilliant way to collect this data :)

> Also I haven't got a sharepoint to test.

I'm not sure if I get you. Since you have OneDrive for Business, doesn't it come with a Sharepoint? But btw, what do you think of the [MS365 Developer Program](https://developer.microsoft.com/en-us/microsoft-365/dev-program)? It should provide everything we need (unless you're talking about an on-premise Sharepoint) and maybe we can use that for future testing, etc.

**Comment by ncw** [comment]
> Sorry for the delay! Ignoring backward compatibility, I think the most correct thing to do will be to get an accurate and complete list of problematic symbols and reduce the need for changes in the future as much as possible. And you've presented a brilliant way to collect this data :)

I think that part is done for onedrive and onedrive business :-)
 
> > Also I haven't got a sharepoint to test.
> 
> I'm not sure if I get you. Since you have OneDrive for Business, doesn't it come with a Sharepoint?

I have a loaner OneDrive for business account.

I've never used sharepoint before - are you saying that comes with a sharepoint that I could access with rclone? Can you give me a hint how that works?

> But btw, what do you think of the [MS365 Developer Program](https://developer.microsoft.com/en-us/microsoft-365/dev-program)? It should provide everything we need (unless you're talking about an on-premise Sharepoint) and maybe we can use that for future testing, etc.

Looks useful indeed :-)

**Comment by Cnly** [comment]
> I have a loaner OneDrive for business account.
>
> I've never used sharepoint before - are you saying that comes with a sharepoint that I could access with rclone? Can you give me a hint how that works?

AFAIC usually that's true. You should be able to go to Sharepoint via the menu button at the top left corner in the OneDrive for Business webpage, or just change your OneDrive URL `contoso-my.sharepoint.com` to `contoso.sharepoint.com`. Or, if you have some kind of helper scripts to do the job I can run the tests on my side and share the results.

> Looks useful indeed :-)

If you have no problem with it let me try getting us a developer subscription :)

**Comment by Cnly** [comment]
> The script which needs running is in the contributing docs

Oh, I didn't notice it has made its way into the codebase. I'll take a look!

I've also sent you an email about the developer subscription. Not sure if you've got time recently... (seems only you can edit the config?) but I think it'd be great if we also can add Sharepoint as a daily test backend.

**Comment by Cnly** [comment]
Okay, this is what I get:

<img width="991" alt="Character Encoding Sharepoint" src="https://user-images.githubusercontent.com/3103188/99024225-122f8a80-25a1-11eb-937c-92fe04d5244d.png">

So basically Sharepoint is the same as OneDrive for Business.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54
