### ISSUE TITLE
regression between v1.52.3 and v1.53.1: rclone tries to create an existing S3 bucket

### ISSUE THREAD

**Issue by ctrlaltdel** [rclone/rclone#4703]
#### What is the problem you are having with rclone?

Copying a single file into an existing empty S3 bucket fails.

Looking at debug logs, it seems that v1.53.1 is trying to create an already existing S3 bucket. This operation is failing with `AccessDenied` because IAM policies doesn't allow this.

#### What is your rclone version (output from `rclone version`)

```console
# ~/rclone/rclone-v1.53.1-linux-amd64/rclone version
rclone v1.53.1
- os/arch: linux/amd64
- go version: go1.15
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)

```console
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.7 LTS
Release:        16.04
Codename:       xenial
```

####  Which cloud storage system are you using? (eg Google Drive)

AWS S3

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

```console
# rclone copy /tmp/toto backup-plaintext:my-bucket
```

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

Operation is failing with v1.53.1:

```console
# ~/rclone/rclone-v1.53.1-linux-amd64/rclone --log-level DEBUG --dump bodies --retries 1 copy /tmp/toto backup-plaintext:my-bucket
2020/10/23 10:39:14 DEBUG : rclone: Version "v1.53.1" starting with parameters ["/root/rclone/rclone-v1.53.1-linux-amd64/rclone" "--log-level" "DEBUG" "--dump" "bodies" "--retries" "1" "copy" "/tmp/toto" "backup-plaintext:my-bucket"]
2020/10/23 10:39:14 DEBUG : Creating backend with remote "/tmp/toto"
2020/10/23 10:39:14 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2020/10/23 10:39:14 DEBUG : fs cache: adding new entry for parent of "/tmp/toto", "/tmp"
2020/10/23 10:39:14 DEBUG : Creating backend with remote "backup-plaintext:my-bucket"
2020/10/23 10:39:14 DEBUG : You have specified to dump information. Please be noted that the Accept-Encoding as shown may not be correct in the request and the response may not show Content-Encoding if the go standard libraries auto gzip encoding was in effect. In this case the body of the request will be gunzipped before showing it.
2020/10/23 10:39:14 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/10/23 10:39:14 DEBUG : HTTP REQUEST (req 0xc00002dd00)
2020/10/23 10:39:14 DEBUG : HEAD /my-bucket/toto HTTP/1.1
Host: s3.eu-west-1.amazonaws.com
User-Agent: rclone/v1.53.1
Authorization: XXXX
X-Amz-Content-Sha256: XXXXXX
X-Amz-Date: XXXXX

2020/10/23 10:39:14 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/10/23 10:39:14 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/10/23 10:39:14 DEBUG : HTTP RESPONSE (req 0xc00002dd00)
2020/10/23 10:39:14 DEBUG : HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Fri, 23 Oct 2020 08:39:14 GMT
Server: AmazonS3
X-Amz-Id-2: XXXXXX
X-Amz-Request-Id: XXXXXX


2020/10/23 10:39:14 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/10/23 10:39:14 DEBUG : toto: Need to transfer - File not found at Destination
2020/10/23 10:39:14 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/10/23 10:39:14 DEBUG : HTTP REQUEST (req 0xc0000f7700)
2020/10/23 10:39:14 DEBUG : PUT /my-bucket HTTP/1.1
Host: s3.eu-west-1.amazonaws.com
User-Agent: rclone/v1.53.1
Content-Length: 153
Authorization: XXXX
X-Amz-Acl: private
X-Amz-Content-Sha256: XXXXX
X-Amz-Date: XXXXXX
Accept-Encoding: gzip

<CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LocationConstraint>eu-west-1</LocationConstraint></CreateBucketConfiguration>
2020/10/23 10:39:14 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/10/23 10:39:14 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/10/23 10:39:14 DEBUG : HTTP RESPONSE (req 0xc0000f7700)
2020/10/23 10:39:14 DEBUG : HTTP/1.1 403 Forbidden
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Fri, 23 Oct 2020 08:39:14 GMT
Server: AmazonS3
X-Amz-Id-2: XXXXXX
X-Amz-Request-Id: XXXXXX

f3
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>XXXXXX</RequestId><HostId>XXXXXX</HostId></Error>
0

2020/10/23 10:39:14 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/10/23 10:39:14 ERROR : toto: Failed to copy: AccessDenied: Access Denied
        status code: 403, request id: XXXXXX, host id: XXXXXX
2020/10/23 10:39:14 ERROR : Attempt 1/1 failed with 1 errors and: AccessDenied: Access Denied
        status code: 403, request id: XXXXXX, host id: XXXXXX
2020/10/23 10:39:14 INFO  : 
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         0.4s

2020/10/23 10:39:14 DEBUG : 4 go routines active
2020/10/23 10:39:14 Failed to copy: AccessDenied: Access Denied
        status code: 403, request id: XXXXXX, host id: XXXXXX
```

The exact same operation worked fine with v1.52.3.

```console
# ~/rclone/rclone-v1.52.3-linux-amd64/rclone --log-level DEBUG --dump bodies --retries 1 copy /tmp/toto backup-plaintext:my-bucket
2020/10/23 10:39:34 DEBUG : rclone: Version "v1.52.3" starting with parameters ["/root/rclone/rclone-v1.52.3-linux-amd64/rclone" "--log-level" "DEBUG" "--dump" "bodies" "--retries" "1" "copy" "/tmp/toto" "backup-plaintext:my-bucket"]
2020/10/23 10:39:34 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2020/10/23 10:39:34 DEBUG : fs cache: adding new entry for parent of "/tmp/toto", "/tmp"
2020/10/23 10:39:34 DEBUG : You have specified to dump information. Please be noted that the Accept-Encoding as shown may not be correct in the request and the response may not show Content-Encoding if the go standard libraries auto gzip encoding was in effect. In this case the body of the request will be gunzipped before showing it.
2020/10/23 10:39:34 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/10/23 10:39:34 DEBUG : HTTP REQUEST (req 0xc000291400)
2020/10/23 10:39:34 DEBUG : HEAD /my-bucket/toto HTTP/1.1
Host: s3.eu-west-1.amazonaws.com
User-Agent: rclone/v1.52.3
Authorization: XXXX
X-Amz-Content-Sha256: XXXXX
X-Amz-Date: XXXXX

2020/10/23 10:39:34 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/10/23 10:39:34 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/10/23 10:39:34 DEBUG : HTTP RESPONSE (req 0xc000291400)
2020/10/23 10:39:34 DEBUG : HTTP/1.1 404 Not Found
Connection: close
Content-Type: application/xml
Date: Fri, 23 Oct 2020 08:39:34 GMT
Server: AmazonS3
X-Amz-Id-2: XXXXX
X-Amz-Request-Id: XXXXX

2020/10/23 10:39:34 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/10/23 10:39:34 DEBUG : toto: Need to transfer - File not found at Destination
2020/10/23 10:39:34 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/10/23 10:39:34 DEBUG : HTTP REQUEST (req 0xc000185900)
2020/10/23 10:39:34 DEBUG : PUT /my-bucket/toto?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXXXX%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=XXXXX&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=XXXXX HTTP/1.1
Host: s3.eu-west-1.amazonaws.com
User-Agent: rclone/v1.52.3
Content-Length: 6
content-md5: XXXXX
content-type: application/octet-stream
x-amz-acl: private
x-amz-meta-mtime: XXXXXX
Accept-Encoding: gzip

salut
2020/10/23 10:39:34 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/10/23 10:39:34 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/10/23 10:39:34 DEBUG : HTTP RESPONSE (req 0xc000185900)
2020/10/23 10:39:34 DEBUG : HTTP/1.1 200 OK
Content-Length: 0
Date: Fri, 23 Oct 2020 08:39:35 GMT
Etag: "XXXXX"
Server: AmazonS3
X-Amz-Id-2: XXXXX
X-Amz-Request-Id: XXXXX

2020/10/23 10:39:34 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/10/23 10:39:34 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/10/23 10:39:34 DEBUG : HTTP REQUEST (req 0xc00071f100)
2020/10/23 10:39:34 DEBUG : HEAD /my-bucket/toto HTTP/1.1
Host: s3.eu-west-1.amazonaws.com
User-Agent: rclone/v1.52.3
Authorization: XXXX
X-Amz-Content-Sha256: XXXXX
X-Amz-Date: XXXXX

2020/10/23 10:39:34 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/10/23 10:39:34 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/10/23 10:39:34 DEBUG : HTTP RESPONSE (req 0xc00071f100)
2020/10/23 10:39:34 DEBUG : HTTP/1.1 200 OK
Content-Length: 6
Accept-Ranges: bytes
Content-Type: application/octet-stream
Date: Fri, 23 Oct 2020 08:39:35 GMT
Etag: "XXXXX"
Last-Modified: Fri, 23 Oct 2020 08:39:35 GMT
Server: AmazonS3
X-Amz-Id-2: XXXXX
X-Amz-Meta-Mtime: XXXXX
X-Amz-Request-Id: XXXXX

2020/10/23 10:39:34 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/10/23 10:39:34 DEBUG : toto: MD5 = 6aba532a54c9eb9aa30496fa7f22734d OK
2020/10/23 10:39:34 INFO  : toto: Copied (new)
2020/10/23 10:39:34 INFO  :
Transferred:             6 / 6 Bytes, 100%, 24 Bytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         0.2s

2020/10/23 10:39:34 DEBUG : 4 go routines active
```

**Comment by darthShadow** [comment]
`--s3-no-check-bucket` (https://rclone.org/s3/#s3-no-check-bucket) should get you going.

**Comment by ctrlaltdel** [comment]
Thanks for the pointer! Closing the issue.

**Comment by ngollan** [comment]
It would have been nice to leave this open, because it breaks the likely more common use-case of writing to an existing bucket in favour of convenience in less secure "sandbox" setups.

**Comment by dtenenba** [comment]
I don't understand why rclone is trying to create the bucket when it could simply check to see if the bucket exists. And why the error returned is a permssions error and not an error that the bucket already exists. Maybe the "bucket already exists" exception is handled but the permissions one is not. 

This seems like a bug to me and I would also like to see it reopened and fixed.

**Comment by ncw** [comment]
> I don't understand why rclone is trying to create the bucket when it could simply check to see if the bucket exists. 

Rclone does try to see if the bucket exists. It uses  HEAD bucket to see if a bucket exists. However this is a separate permission and if this is blocked then we get to the rclone trying to create the bucket.

So if you don't want to use the no_check_bucket feature, then allow rclone to HEAD buckets.

```
2020/10/23 10:39:14 DEBUG : HTTP REQUEST (req 0xc00002dd00)
2020/10/23 10:39:14 DEBUG : HEAD /my-bucket/toto HTTP/1.1
Host: s3.eu-west-1.amazonaws.com
User-Agent: rclone/v1.53.1
Authorization: XXXX
X-Amz-Content-Sha256: XXXXXX
X-Amz-Date: XXXXX

2020/10/23 10:39:14 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2020/10/23 10:39:14 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020/10/23 10:39:14 DEBUG : HTTP RESPONSE (req 0xc00002dd00)
2020/10/23 10:39:14 DEBUG : HTTP/1.1 404 Not Found
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Fri, 23 Oct 2020 08:39:14 GMT
Server: AmazonS3
X-Amz-Id-2: XXXXXX
X-Amz-Request-Id: XXXXXX
```

The other alternative would be to list the bucket to see if it exists. However this is a more expensive API operation and is also likely to be blocked for a restricted user.

> And why the error returned is a permssions error and not an error that the bucket already exists.

I would guess AWS check the permissions of what the user can do first before trying to do it. So if your user can't create buckets then you get permission denied rather than bucket already exists.

> Maybe the "bucket already exists" exception is handled but the permissions one is not.

The permission denied error can be caused by you not owning the bucket so when we get that we need to surface it to the user.

> This seems like a bug to me and I would also like to see it reopened and fixed.

It is complicated, alas.

**Comment by driskell** [comment]
@ncw I guess it is not something to change at this point but it's worth noting this was a breaking change in a minor release. Of all my usage of rclone I am involved with every single call is now failing (we locked everything down.) I do wonder if rather than a no_check_bucket option it should've been opt-in for a minor release as a --check-bucket and then just have this automatically enabled in another major version. Perhaps would have reduced impact.

I'll have all our things updated soon but just thought I'd share the impact in case it helps future additions be more backwards compatible.

**Comment by driskell** [comment]
OK so we found some places where upgrade didn't happen and they are now failing because no_check_bucket does not exist. So yes a pretty peculiar occurrence. Hopefully have it sorted soon 😬

**Comment by hsmade** [comment]
> if the bucket exists. It uses HEAD bucket to see if a bucket exists. However this is a separate permission and if this is blocked then we get to the rclone trying to cre



> > I don't understand why rclone is trying to create the bucket when it could simply check to see if the bucket exists.
> 
> Rclone does try to see if the bucket exists. It uses HEAD bucket to see if a bucket exists. However this is a separate permission and if this is blocked then we get to the rclone trying to create the bucket.
> 
> So if you don't want to use the no_check_bucket feature, then allow rclone to HEAD buckets.
> 
> ```
> 2020/10/23 10:39:14 DEBUG : HTTP REQUEST (req 0xc00002dd00)
> 2020/10/23 10:39:14 DEBUG : HEAD /my-bucket/toto HTTP/1.1
> Host: s3.eu-west-1.amazonaws.com
> User-Agent: rclone/v1.53.1
> Authorization: XXXX
> X-Amz-Content-Sha256: XXXXXX
> X-Amz-Date: XXXXX
> 
> 2020/10/23 10:39:14 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
> 2020/10/23 10:39:14 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
> 2020/10/23 10:39:14 DEBUG : HTTP RESPONSE (req 0xc00002dd00)
> 2020/10/23 10:39:14 DEBUG : HTTP/1.1 404 Not Found
> Transfer-Encoding: chunked
> Content-Type: application/xml
> Date: Fri, 23 Oct 2020 08:39:14 GMT
> Server: AmazonS3
> X-Amz-Id-2: XXXXXX
> X-Amz-Request-Id: XXXXXX
> ```
This is not checking for the bucket to exist, but the destination FILE. 
Rclone is not checking for the bucket to exist, at all. It's just assuming it's not there.

**Comment by rockliffelewis** [comment]
I just ran into this as well, theres nothing in the request log to suggest that its HEADing the bucket to see if it exists or not

```
rclone version
rclone v1.63.1
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.10.102.1-microsoft-standard-WSL2 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.6
- go/linking: static
- go/tags: none
```

The first request is HEADing the file to see if it already exists, which is reasonable
The second request is creating the bucket, which fails due to restricted access
```
DEBUG : HEAD /bucket/file.txt HTTP/1.1
...
DEBUG : PUT /bucket HTTP/1.1
```

**Comment by ncw** [comment]
Use the `--s3-no-check-bucket` flag or the `no_check_bucket = true` in your config.

**Comment by rockliffelewis** [comment]
> Use the `--s3-no-check-bucket` flag or the `no_check_bucket = true` in your config.

I'm aware of this flag, but this is not a sufficient resolution for our usecase, nor does it make sense that rclone tries to recreate a bucket that already exists and fails to copy without that permission.

**Comment by ncw** [comment]
@rockliffelewis that flag works for me. How is it not working for you?

```
$ rclone copy file.txt s3:rclone -vv --dump headers 2>&1 | grep -P "GET|HEAD|PUT"
2023/10/09 16:49:27 DEBUG : HEAD /file.txt HTTP/1.1
2023/10/09 16:49:27 DEBUG : PUT / HTTP/1.1
2023/10/09 16:49:27 DEBUG : PUT /file.txt HTTP/1.1
2023/10/09 16:49:27 DEBUG : HEAD /file.txt HTTP/1.1
```

```
$ rclone delete s3:rclone/file.txt
$ rclone copy file.txt s3:rclone -vv --s3-no-check-bucket --dump headers 2>&1 | grep -P "GET|HEAD|PUT"
2023/10/09 16:49:55 DEBUG : HEAD /file.txt HTTP/1.1
2023/10/09 16:49:56 DEBUG : PUT /file.txt HTTP/1.1
2023/10/09 16:49:56 DEBUG : HEAD /file.txt HTTP/1.1
```

**Comment by driskell** [comment]
> @rockliffelewis that flag works for me. How is it not working for you?
> 
> ```
> $ rclone copy file.txt s3:rclone -vv --dump headers 2>&1 | grep -P "GET|HEAD|PUT"
> 2023/10/09 16:49:27 DEBUG : HEAD /file.txt HTTP/1.1
> 2023/10/09 16:49:27 DEBUG : PUT / HTTP/1.1
> 2023/10/09 16:49:27 DEBUG : PUT /file.txt HTTP/1.1
> 2023/10/09 16:49:27 DEBUG : HEAD /file.txt HTTP/1.1
> ```
> 
>  ```
> $ rclone delete s3:rclone/file.txt
> $ rclone copy file.txt s3:rclone -vv --s3-no-check-bucket --dump headers 2>&1 | grep -P "GET|HEAD|PUT"
> 2023/10/09 16:49:55 DEBUG : HEAD /file.txt HTTP/1.1
> 2023/10/09 16:49:56 DEBUG : PUT /file.txt HTTP/1.1
> 2023/10/09 16:49:56 DEBUG : HEAD /file.txt HTTP/1.1
> ```

I think we are saying that although this is a solution it’s very unclear - there is no documentation except this issue. And the flag name doesn’t seem to correspond to the issue at hand as there is indeed no check that the bucket exists it just tries to create it each time. It should really be called no_create_bucket as it checks it before attempting to make the bucket

https://github.com/rclone/rclone/blob/f56ea2bee2e7552e273ff679c6f0eb429a0969d3/backend/s3/s3.go#L4224

I do think the check is indeed missing. The Mkdir is documented as checking but there is there check. It relies on being able to access bucket creation and relies on the already exists errors instead. Indeed it places an extra burden on default usage in a rather undocumented way

https://github.com/rclone/rclone/blob/f56ea2bee2e7552e273ff679c6f0eb429a0969d3/backend/s3/s3.go#L4203

**Comment by driskell** [comment]
Ok so I can’t find the exists check. It only seems to call it if there was a previous bucket deletion. So I think maybe a bug.

https://github.com/rclone/rclone/blob/master/lib/bucket/bucket.go#L93-L132

**Comment by ncw** [comment]
@driskell please make a sequence of rclone commands to demonstrate the problem like I did above - thanks!
