### ISSUE TITLE
Rclone 1.53.1 can not list buckets on KingSoft Cloud S3 Service

### ISSUE THREAD

**Issue by honest1y** [rclone/rclone#4707]
#### Output of `rclone version`
rclone v1.53.1-DEV

#### Describe the issue

When I config ksyun(https://www.ksyun.com/) accesskeyid and secret in rclone.conf, and run command "rclone lsf src:", 
rclone return an error is "2020/10/25 17:08:08 ERROR : : error listing: InvalidArgument: Invalid Argument",Does rclone temporarily not support ksyun's object storage service?

**Comment by darthShadow** [comment]
Can you try once with the latest beta, in case this has been fixed already?

**Comment by honest1y** [comment]
> Can you try once with the latest beta, in case this has been fixed already?

Yes, already try the beta version rclone v1.54.0-beta.4837.bed83b0b6, same errors error listing: InvalidArgument: Invalid Argument

**Comment by darthShadow** [comment]
Since @ncw is already replying on your forum thread, I will close this issue for now.
