### ISSUE TITLE
Can't login to GUI

### ISSUE THREAD

**Issue by OgnistyPoland** [rclone/rclone#4708]
#### What is the problem you are having with rclone?
I can't login to gui

#### What is your rclone version (output from `rclone version`)
rclone v1.53.1

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
Windows 10 20H2

####  Which cloud storage system are you using? (eg Google Drive)
Google Drive

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone rcd --rc-web-gui --rc-user gui --rc-pass gui -vv

#### A log from the command with the `-vv` flag (eg output from `rclone -vv copy /tmp remote:tmp`)

When i'm trying to login with gui login and pass i can't

rclone rcd --rc-web-gui --rc-user gui --rc-pass gui -vv
2020/10/25 12:12:58 DEBUG : rclone: Version "v1.53.1" starting with parameters ["rclone" "rcd" "--rc-web-gui" "--rc-user" "gui" "--rc-pass" "gui" "-vv"]
2020/10/25 12:12:58 NOTICE: Web GUI exists. Update skipped.
2020/10/25 12:12:58 NOTICE: Serving Web GUI
2020/10/25 12:12:58 INFO  : Using --user gui --pass XXXX as authenticated user
2020/10/25 12:12:58 NOTICE: Serving remote control on http://127.0.0.1:5572/
2020/10/25 12:12:58 DEBUG : login_token "Z3VpOmd1aQ=="
2020/10/25 12:12:58 INFO  : /core/version: 127.0.0.1:54185: Unauthorized request from gui
2020/10/25 12:12:58 INFO  : /core/stats: 127.0.0.1:54186: Unauthorized request from gui
2020/10/25 12:12:58 INFO  : /core/bwlimit: 127.0.0.1:54188: Unauthorized request from gui
2020/10/25 12:12:58 INFO  : /core/stats: 127.0.0.1:54187: Unauthorized request from gui
2020/10/25 12:13:03 INFO  : /core/stats: 127.0.0.1:54192: Unauthorized request from gui
2020/10/25 12:13:03 INFO  : /core/stats: 127.0.0.1:54193: Unauthorized request from gui
2020/10/25 12:13:07 INFO  : /core/stats: 127.0.0.1:54193: Unauthorized request from gui
2020/10/25 12:13:07 INFO  : /core/stats: 127.0.0.1:54192: Unauthorized request from gui
2020/10/25 12:13:07 INFO  : /core/stats: 127.0.0.1:54187: Unauthorized request from gui
2020/10/25 12:13:07 INFO  : /core/bwlimit: 127.0.0.1:54188: Unauthorized request from gui
2020/10/25 12:13:07 INFO  : /core/stats: 127.0.0.1:54186: Unauthorized request from gui
2020/10/25 12:13:07 INFO  : /core/version: 127.0.0.1:54185: Unauthorized request from gui
2020/10/25 12:13:09 INFO  : /core/stats: 127.0.0.1:54185: Unauthorized request from gui
2020/10/25 12:13:09 INFO  : /core/stats: 127.0.0.1:54186: Unauthorized request from gui
2020/10/25 12:13:14 INFO  : /core/stats: 127.0.0.1:54193: Unauthorized request from gui
2020/10/25 12:13:14 INFO  : /core/stats: 127.0.0.1:54192: Unauthorized request from gui
2020/10/25 12:13:19 INFO  : /core/stats: 127.0.0.1:54187: Unauthorized request from gui
2020/10/25 12:13:19 INFO  : /core/stats: 127.0.0.1:54188: Unauthorized request from gui
2020/10/25 12:14:18 INFO  : /core/stats: 127.0.0.1:54188: Unauthorized request from gui
2020/10/25 12:14:18 INFO  : /core/stats: 127.0.0.1:54187: Unauthorized request from gui
2020/10/25 12:14:18 INFO  : /core/stats: 127.0.0.1:54295: Unauthorized request from gui
2020/10/25 12:14:18 INFO  : /core/stats: 127.0.0.1:54294: Unauthorized request from gui
2020/10/25 12:14:18 INFO  : /core/stats: 127.0.0.1:54297: Unauthorized request from gui
2020/10/25 12:14:18 INFO  : /core/stats: 127.0.0.1:54296: Unauthorized request from gui

**Comment by animosity22** [comment]
What URL are you putting in the browser?
Are you using gui / gui to login with?

**Comment by OgnistyPoland** [comment]
Yes

**Comment by animosity22** [comment]
And you get:

![image](https://user-images.githubusercontent.com/5088712/97119317-c5653c00-16e5-11eb-9910-449aa1517372.png)


And you enter in gui / gui and don't get


![image](https://user-images.githubusercontent.com/5088712/97119327-d4e48500-16e5-11eb-9d38-3b75ce3ec72d.png)

**Comment by OgnistyPoland** [comment]
I'm getting login screen from your first screen and than I see dashboard but can't do anything

**Comment by animosity22** [comment]
So you can enter the user and password on the first and you can see the second?

Screenshots would be helpful.

**Comment by OgnistyPoland** [comment]
I installed Firefox instead of Chrome and now it's working, so I guess I can close it

**Comment by animosity22** [comment]
Sounds like a browser cache issue. Best to clear cache and try incognito as well.
