### ISSUE TITLE
rclone can not copy object from s3 to s3 and the key is "a//"?

### ISSUE THREAD

**Issue by zhucan** [rclone/rclone#4721]
#### What is the problem you are having with rclone?
rclone can not copy object from s3 to s3 and the key is "a//"?

#### What is your rclone version (output from `rclone version`)
![image](https://user-images.githubusercontent.com/13997135/97693674-7865d900-1adc-11eb-9982-bdc6a846414b.png)

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
CentOS Linux release 7.4.1708 (Core)

####  Which cloud storage system are you using? (e.g. Google Drive)
ceph rgw(s3)

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone copy

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
![image](https://user-images.githubusercontent.com/13997135/97693777-a21f0000-1adc-11eb-8a23-0eff33709700.png)

rclone.conf:
![image](https://user-images.githubusercontent.com/13997135/97693867-bc58de00-1adc-11eb-8a4a-a2551347786c.png)

@ncw @darthShadow  Please take a look.

**Comment by animosity22** [comment]
There is no command you are running or a debug log.

Please provide the required information.

**Comment by zhucan** [comment]
@animosity22 the cmd: ./rclone copy 7b298e946c384df3e498e47471fded98:/src-bk-15 bcd301810490e6d3da80fb3de37a64b1:/target-bk-15 --log-level DEBUG --log-file /var/log/xdrs/migration-mig1.log

**Comment by animosity22** [comment]
Can you please provide the debug log file?

**Comment by zhucan** [comment]
@animosity22 Please take a look at this, it's the logs
![image](https://user-images.githubusercontent.com/13997135/97938081-6d03fd80-1dbb-11eb-8fbc-07c337141bdd.png)

**Comment by animosity22** [comment]
Can you pretty please include the whole debug log file?

**Comment by zhucan** [comment]
@animosity22 
![image](https://user-images.githubusercontent.com/13997135/97944164-a0e12200-1dbf-11eb-956f-d37a41edc719.png)

**Comment by animosity22** [comment]
Super pretty please the full debug log in a log file and not an image?

**Comment by zhucan** [comment]
[migration-mig1.log](https://github.com/rclone/rclone/files/5478969/migration-mig1.log)

**Comment by zhucan** [comment]
@animosity22 Please take a look.

**Comment by ncw** [comment]
Thanks for the log.

Objects which have paths which aren't well formed filesystem paths - eg `a//b` rclone will struggle with at the moment. Rclone is intepreting that as "a/b" and then the object is not found.

Would it be acceptable if the object was copied as `a/b` instead of `a//b`?

**Comment by zhucan** [comment]
@ncw Thanks for your answer, But the key of the user's object is "a//b", it's unacceptable. The issue can be solved?

**Comment by ncw** [comment]
> Thanks for your answer, But the key of the user's object is "a//b", it's unacceptable.

That is what I thought you'd say!

> The issue can be solved?

There isn't a work-around for this at the moment :-(

My plan is to encode the second `/` into a unicode look-alike so `a//b` would become a directory called `a` and an object called `/b` effectively.

This would also allow me to fix objects with leading and trailing `/` which also can't be copied sensibly at the moment.

It fails at the moment because you can't copy `a//b` to your local disk. However you are copying between storage systems so it should work but doesn't yet.

**Comment by zhucan** [comment]
copy that, thanks

**Comment by ivandeex** [comment]
not a bug

**Comment by zhucan** [comment]
Is there other issue to record this problem? @ivandeex

**Comment by ivandeex** [comment]
@ncw said

> My plan is to encode the second `/` into a unicode look-alike so `a//b` would become a directory called `a` and an object called `/b` effectively.

I can't find a ticket marked with `encoding`, but it seems @ncw is working on it

**Comment by ivandeex** [comment]
@ncw ?

**Comment by zhucan** [comment]
> My plan is to encode the second `/` into a unicode look-alike so `a//b` would become a directory called `a` and an object called `/b` effectively.

I think, If backend  storage is s3, no additional processing required for object key?

**Comment by ivandeex** [comment]
Closing stale questions
