### ISSUE TITLE
Improperly trims long urls like https://seafile.foobar.example.com

### ISSUE THREAD

**Issue by fancycade** [rclone/rclone#4725]
#### What is the problem you are having with rclone?

Regex trims off the seafile prefix of the url when using urls like https://seafile.foobar.example.com

#### What is your rclone version (output from `rclone version`)

v1.53.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

64 Bit Ubuntu

####  Which cloud storage system are you using? (e.g. Google Drive)

Seafile

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

Any command, but specifically move

rclone move

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

2020/10/30 19:23:02 DEBUG : rclone: Version "v1.53.2" starting with parameters ["rclone" "-vv" "move" "foo.txt" "seafile:recordings"]
2020/10/30 19:23:02 DEBUG : Creating backend with remote "foo.txt"
2020/10/30 19:23:02 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2020/10/30 19:23:02 DEBUG : fs cache: adding new entry for parent of "foo.txt", "/root/.jitsi-meet-cfg/jibri"
2020/10/30 19:23:02 DEBUG : Creating backend with remote "seafile:recordings"
2020/10/30 19:23:02 DEBUG : Seafile server version 7.1.5
2020/10/30 19:23:02 DEBUG : foo.txt: Need to transfer - File not found at Destination
2020/10/30 19:23:03 DEBUG : pacer: low level retry 1/1 (error Post "https://petals.22rosestreet.com/seafhttp/upload-api/2356ad08-c99d-4fd2-b53d-c7f3a99a842f?ret-json=1": dial tcp: lookup petals.22rosestreet.com on 127.0.0.53:53: no such host)
2020/10/30 19:23:03 DEBUG : pacer: Rate limited, increasing sleep to 200ms

Here is my config:
[seafile]
type = seafile
url = https://seafile.petals.22rosestreet.com
user = harley@mycanofbeans.com
pass = secret
library = recordings

As you can see the url that it is posting to is not correct. It should be https://seafile.petals.22rosestreet.com not https://petals.22rosestreet.com.

Fairly certain the issue is here: https://github.com/rclone/rclone/blob/master/fs/fspath/path.go#L26

I would make a PR but I am no regex expert.

**Comment by darthShadow** [comment]
Can you please paste your config (with the secrets redacted) too?

**Comment by fancycade** [comment]
@darthShadow I have updated the issue with my config.

**Comment by darthShadow** [comment]
Can you try adding `https://` or `http://` (as appropriate) to the URL?

**Comment by fancycade** [comment]
@darthShadow I'm a bit confused. https:// is already in the url.

To be thorough, I tried with http:// and got permission denied. I don't have the server exposed via http so that is to be expected. Here is the log:

```
rclone -vv move foo.txt seafile:recordings
2020/10/31 12:15:56 DEBUG : rclone: Version "v1.53.2" starting with parameters ["rclone" "-vv" "move" "foo.txt" "seafile:recordings"]
2020/10/31 12:15:56 DEBUG : Creating backend with remote "foo.txt"
2020/10/31 12:15:56 DEBUG : Using config file from "/home/fc/.config/rclone/rclone.conf"
2020/10/31 12:15:56 DEBUG : fs cache: adding new entry for parent of "foo.txt", "/home/fc/Desktop"
2020/10/31 12:15:56 DEBUG : Creating backend with remote "seafile:recordings"
2020/10/31 12:15:57 DEBUG : Seafile server version 7.1.5
2020/10/31 12:16:03 Failed to create file system for "seafile:recordings": permission denied
```

**Comment by darthShadow** [comment]
Oh, sorry. Github hid that prefix since it's a URL so I missed that.

**Comment by darthShadow** [comment]
Cc: @creativeprojects

**Comment by fancycade** [comment]
@darthShadow Thanks for taking the time to check on this. I've edited the issue again to include the prefix in the description to make it more clear.

**Comment by adamplansky** [comment]
@fancycade Are you sure that the config file /root/.config/rclone/rclone.conf has correct url?


I tried to replicate your issue with local seafile server in docker https://github.com/rclone/rclone/blob/master/fstest/testserver/init.d/TestSeafile  

My rclone configuration:
```
[seafile]
type = seafile
url = http://seafile.petals.22rosestreet.com:8087
user = seafile@rclone.org
pass = *secret*
library = My Library
```

cat /etc/hosts
```
127.0.0.1     seafile.petals.22rosestreet.com
```


And I was not able to replicate your issue. 

My log:
```
./rclone -vv move notes.txt "seafile:/test/"
<7>DEBUG : rclone: Version "v1.54.0-DEV" starting with parameters ["./rclone" "-vv" "move" "notes.txt" "seafile:/test/"]
<7>DEBUG : rclone: systemd logging support automatically activated
<7>DEBUG : Creating backend with remote "notes.txt"
<7>DEBUG : Using config file from "/home/adam/.config/rclone/rclone.conf"
<7>DEBUG : fs cache: adding new entry for parent of "notes.txt", "/home/adam/.go/src/github.com/rclone/rclone"
<7>DEBUG : Creating backend with remote "seafile:/test/"
<7>DEBUG : Seafile server version 7.1.5
<7>DEBUG : fs cache: renaming cache item "seafile:/test/" to be canonical "seafile:test"
<7>DEBUG : notes.txt: Need to transfer - File not found at Destination
<6>INFO  : notes.txt: Copied (new)
<6>INFO  : notes.txt: Deleted
<6>INFO  :
Transferred:        1.462k / 1.462 kBytes, 100%, 6.919 kBytes/s, ETA 0s
Checks:                 2 / 2, 100%
Deleted:                1
Renamed:                1
Transferred:            1 / 1, 100%
Elapsed time:         0.5s

<7>DEBUG : 7 go routines active

```

**Comment by creativeprojects** [comment]
I think it could be something missing in the Seafile server configuration

When it needs to upload a file, it sends a request to the api, giving the path and file name you want to upload.
Then the api is returning a url where you upload that file. Typically `<server_url>/seafhttp/upload-api/2356ad08-c99d-4fd2-b53d-c7f3a99a842f`.

So the url where it's trying to upload the file to is not generated by rclone, but by Seafile.

On my server, in the configuration file `seahub_settings.py` is have these two entries:

```
FILE_SERVER_ROOT = "https://seafile.mydomain.com/seafhttp"
SITE_BASE = 'https://seafile.mydomain.com'
```

and I think you need them both

**Comment by fancycade** [comment]
@creativeprojects Well I feel silly, thanks for the hint. I forgot to set the urls in the admin settings. 

In my case it was SERVICE_URL and FILE_SERVER_ROOT. Works perfectly after setting those properly.
