### ISSUE TITLE
Add a new flag

### ISSUE THREAD

**Issue by mtnjustme** [rclone/rclone#4727]
There is a flag of "--max-duration", but there's no flag of "--min-duration" which can be helpful to avoid those 1 second and 3 seconds videos etc.
Would be nice to have a "--min-duration" flag as well.

**Comment by darthShadow** [comment]
You want rclone commands to run for a minimum amount of time even if processing has finished early? Can you please explain this use case with an example?

**Comment by mtnjustme** [comment]
> 
> 
> You want rclone commands to run for a minimum amount of time even if processing has finished early? Can you please explain this use case with an example?

oh, i thought min duration goes for min files duration, like videos and music files.

**Comment by darthShadow** [comment]
No, it's meant for limiting the runtime of the command. rclone doesn't differentiate between media files, text files or binary files so this flag would only be helpful to very specific use cases which can probably be handled better by a custom external script that you can use to feed rclone a specific list of files.

Hopefully, that helps. Closing the issue. Feel free to join the forums @ https://forum.rclone.org if you need any other help.
