### ISSUE TITLE
Support for Archived Images in Google Photos

### ISSUE THREAD

**Issue by AngelaDMerkel** [rclone/rclone#4728]
I'm currently using `v1.53.0` to try to overcome the deprecated integration between Drive and Google Photos. I feel that rclone would benefit greatly from having the ability to access photos marked as Archived. As I understand, the solution would be to add an `archived` parameter.
I know that past issues have been created and closed regarding this, but I am happy to try my hand at resolving the problem.

**Comment by ncw** [comment]
Here is how to add the archived filter: https://developers.google.com/photos/library/guides/apply-filters#archived-state

There would be two ways to do this.

One would be to add the archived filter into the directory listing - you'd change the search filter here and make a new directory path or paths with the archived flag set.

https://github.com/rclone/rclone/blob/f89ff3872d81844d4d3a9b961cc780c95caeb727/backend/googlephotos/pattern.go#L47

However I think probably the best way would be to add a backend config `--gphotos-archived` which defaults to false but can be set to true.

This would set the archived flag everywhere.

For that case you'd want to copy the api.Filter passed in here

https://github.com/rclone/rclone/blob/f89ff3872d81844d4d3a9b961cc780c95caeb727/backend/googlephotos/googlephotos.go#L493

And set the archived flag in the copy

https://github.com/rclone/rclone/blob/f89ff3872d81844d4d3a9b961cc780c95caeb727/backend/googlephotos/api/types.go#L146

Do you want to have a go at this @AngelaDMerkel ?

**Comment by AngelaDMerkel** [comment]
@ncw I'm perfectly happy to give it a shot. I have no experience with Go, but I don't think it will take too much time to learn enough. I will take a few weeks to make the free time to do it properly, but so long as there is so major rush I'll do my best and hopefully this will help some others.
Again, thanks @ncw for the guidance. I'll update when there is meaningful progress.

**Comment by ncw** [comment]
Let me know here if you need any help :-) Thanks

**Comment by ncw** [comment]
I've merged @enere 's work on this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.54 - thank you @enere :-)
