### ISSUE TITLE
[GCS] rclone refuses to list even public GCS buckets without config

### ISSUE THREAD

**Issue by Ark-kun** [rclone/rclone#4732]
#### What is the problem you are having with rclone?
I'm running rclone's official Docker container on Google Kubernetes Engine. The cluster is configured so that all containers in it have access to GCP resources without `GOOGLE_APPLICATION_CREDENTIALS`. `gsutil` works. All client libraries (Go, python) work. But rclone does not seem to try:
```
2020/11/03 09:17:10 DEBUG : rclone: Version "v1.53.2" starting with parameters ["rclone" "ls" "-vv" "gs://ml-pipeline"]
2020/11/03 09:17:10 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
2020/11/03 09:17:10 Failed to create file system for "gs://ml-pipeline": didn't find section in config file
```

It would be great if rclone worked when the client libraries work.

#### What is your rclone version (output from `rclone version`)
1.53

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Linux

####  Which cloud storage system are you using? (e.g. Google Drive)
Google Cloud STorage

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
rclond ls "gs://ml-pipeline"
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2020/11/03 09:17:10 DEBUG : rclone: Version "v1.53.2" starting with parameters ["rclone" "ls" "-vv" "gs://ml-pipeline"]
2020/11/03 09:17:10 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
2020/11/03 09:17:10 Failed to create file system for "gs://ml-pipeline": didn't find section in config file
```

```
2020/11/03 09:27:16 DEBUG : rclone: Version "v1.53.2" starting with parameters ["rclone" "ls" "-vvv" "--gcs-anonymous" "gs://ml-pipeline"]
2020/11/03 09:27:16 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
2020/11/03 09:27:16 Failed to create file system for "gs://ml-pipeline": didn't find section in config file
```

**Comment by ncw** [comment]
Try this which is the correct rclone syntax for using rclone on google cloud storage without a config file

    rclone ls -vv :gcs:ml-pipeline

I don't know whether that will work or not though as I don't know if the go SDK will pick up the credentials in the environment without further hints.

How are the credentials available in the environment?

**Comment by Ark-kun** [comment]
> Try this which is the correct rclone syntax for using rclone on google cloud storage without a config file

My bad. Thank you for the syntax hint. I read the GCS documentation page, but it does not seem to feature this syntax. https://rclone.org/googlecloudstorage/ I wish rclone understood the common URI schemas.

With this syntax it worked great.
To access private buckets I had to remove `--gcs-anonymous` and it worked.

>How are the credentials available in the environment?

I think the GKE either just makes unauthenticated HTTP calls work (maybe intercepting them and auto-adding auth) or hacks the metadata endpoint to auto-authenticate like with Workflow Identity.

Thank you.

**Comment by ncw** [comment]
> > Try this which is the correct rclone syntax for using rclone on google cloud storage without a config file
> 
> My bad. Thank you for the syntax hint. I read the GCS documentation page, but it does not seem to feature this syntax. https://rclone.org/googlecloudstorage/ 

It doesn't, you are right.

Do you think this usage of GCS is common? Maybe you could propose an addition to the docs? https://github.com/rclone/rclone/blob/master/docs/content/googlecloudstorage.md - click the pencil icon in the top right and edit if you would like :-)

The syntax or rclone's remotes is here: https://rclone.org/docs/#syntax-of-remote-paths

> I wish rclone understood the common URI schemas.

Like `gs://` ? If you called your remote `gs` then it would pretty much work like that! Is there a list of URI schemas?

> With this syntax it worked great.
> To access private buckets I had to remove `--gcs-anonymous` and it worked.

Great!
 
> > How are the credentials available in the environment?
> 
> I think the GKE either just makes unauthenticated HTTP calls work (maybe intercepting them and auto-adding auth) or hacks the metadata endpoint to auto-authenticate like with Workflow Identity.

It is working which is good which means I don't have to worry about that now :-)
