### ISSUE TITLE
Harmonise html header tag usage for toc

### ISSUE THREAD

**Issue by edwardxml** [rclone/rclone#4738]
## What is your current rclone version (output from `rclone version`)?
Current documentation at 4 November 2020
#### What problem are you are trying to solve?
The header levels for backend and command documentation pages are different so defining a single set of header levels to include in a hugo {{toc}} doesn't work tidily. Either important detail (individual command line options - flags) are missed for commands or font awesome logos intrude on backend pages.

See docs ftp.md put limitations together
#4723

#### How do you think rclone should be changed to solve that?

Harmonise the header levels across the documentation

**Comment by ivandeex** [comment]
Superseded by https://github.com/rclone/rclone/commit/7d66bfbb7c6bc3903bd8e68f96d106a422986cd2
