### ISSUE TITLE
config show only possible via interactive - contrary to docs 

### ISSUE THREAD

**Issue by chris-aeviator** [rclone/rclone#4745]
#### What is the problem you are having with rclone?

rclone documentation mentions wrong command for `rclone config show my_remote`. The resulting error is: `Command config needs 0 arguments maximum`

#### What is your rclone version (output from `rclone version`)

rclone v1.36 (latest on snap and arch)

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
tried on ubuntu 18 & arch

####  Which cloud storage system are you using? (e.g. Google Drive)

SSH/SFTP

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone config show my_remote`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
Command config needs 0 arguments maximum

**Comment by buengese** [comment]
It works for me. The version of rclone you are using is ancient. I can't speak for snaps and I don't think we have any connection to whoever maintains the rclone package there but the latest version on arch is 1.53. You can install an up-to-date version of rclone from [https://rclone.org/downloads/](https://rclone.org/downloads/)

**Comment by ncw** [comment]
We've been trying to get the rclone snap updated here BTW: https://forum.snapcraft.io/t/rclone-snap-delete-or-update/18560/15

**Comment by animosity22** [comment]
This seems to be a question that was answered so I'm going to close it out. You can follow the snap discussion for an updated snap.
