### ISSUE TITLE
Rclone Beta - Getting "invalid memory address or nil pointer dereference" errors

### ISSUE THREAD

**Issue by slickag** [rclone/rclone#4747]
#### What is the problem you are having with rclone?
I'm getting the following error when copying files from a remote to my PC:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x60 pc=0x15579df]

If I'm copying one file to my PC, it always happens at the end of the transfer. When transferring multiple files, it just happens after a seemingly random amount of transfers.

This error is only happening when using rclone beta. I noticed it began about two beta builds ago for me. When I use the standard rclone for transfers, it works as expected.

I get the same error using rclone beta on WSL (Ubuntu/Debian) also and there too the normal rclone version works without errors.

#### What is your rclone version (output from `rclone version`)
Windows shows:
rclone v1.54.0-beta.4878.6c70c4257
- os/arch: windows/amd64
- go version: go1.15.3

WSL (Ubuntu shows):
rclone v1.54.0-beta.4878.6c70c4257
- os/arch: linux/amd64
- go version: go1.15.3

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 10, 64 bit

####  Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone copy gcrypt:downloads/apps/update.rar /mnt/e/slick/Downloads/Compressed (on WSL and Windows just changed the local path to a Windows one).

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
This is from the WSL/Linux rclone beta:
2020/11/07 01:29:31 DEBUG : update.rar: Need to transfer - File not found at Destination
2020/11/07 01:29:31 DEBUG : update.rar: Starting multi-thread copy with 4 parts of size 1.340G
2020/11/07 01:29:31 DEBUG : update.rar: multi-thread copy: stream 4/4 (4317708288-5756842120) size 1.340G starting
2020/11/07 01:29:31 DEBUG : update.rar: multi-thread copy: stream 1/4 (0-1439236096) size 1.340G starting
2020/11/07 01:29:31 DEBUG : update.rar: multi-thread copy: stream 3/4 (2878472192-4317708288) size 1.340G starting
2020/11/07 01:29:31 DEBUG : update.rar: multi-thread copy: stream 2/4 (1439236096-2878472192) size 1.340G starting
2020/11/07 01:31:55 DEBUG : update.rar: multi-thread copy: stream 1/4 (0-1439236096) size 1.340G finished
2020/11/07 01:32:15 DEBUG : update.rar: multi-thread copy: stream 3/4 (2878472192-4317708288) size 1.340G finished
2020/11/07 01:32:56 DEBUG : update.rar: multi-thread copy: stream 2/4 (1439236096-2878472192) size 1.340G finished
2020/11/07 01:33:15 DEBUG : update.rar: multi-thread copy: stream 4/4 (4317708288-5756842120) size 1.340G finished
2020/11/07 01:33:15 DEBUG : update.rar: Finished multi-thread copy with 4 parts of size 1.340G
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xb2c57f]

goroutine 1 [running]:
github.com/rclone/rclone/fs/operations.Copy(0x1e0c540, 0xc000040118, 0x1e235e0, 0xc001c64c60, 0x0, 0x0, 0x7fffd19a8449, 0x21, 0x1e22ae0, 0xc001bf2240, ...)
  github.com/rclone/rclone/fs/operations/operations.go:514 +0x7bf
github.com/rclone/rclone/fs/operations.moveOrCopyFile(0x1e0c540, 0xc000040118, 0x1e235e0, 0xc001c64c60, 0x1e22a60, 0xc001c1c780, 0x7fffd19a8449, 0x21, 0x7fffd19a8449, 0x21, ...)
  github.com/rclone/rclone/fs/operations/operations.go:1670 +0x66f
github.com/rclone/rclone/fs/operations.CopyFile(...)
  github.com/rclone/rclone/fs/operations/operations.go:1688
github.com/rclone/rclone/cmd/copy.glob..func1.1(0xc001c5f0e0, 0x5)
  github.com/rclone/rclone/cmd/copy/copy.go:85 +0xef
github.com/rclone/rclone/cmd.Run(0xc000300101, 0x2890cc0, 0xc000997d38)
  github.com/rclone/rclone/cmd/cmd.go:248 +0xcb
github.com/rclone/rclone/cmd/copy.glob..func1(0x2890cc0, 0xc0003087b0, 0x2, 0x3)
  github.com/rclone/rclone/cmd/copy/copy.go:81 +0x12a
github.com/spf13/cobra.(*Command).execute(0x2890cc0, 0xc000308390, 0x3, 0x3, 0x2890cc0, 0xc000308390)
  github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x288d300, 0x5fa65ae6, 0x28a8cc0, 0xc00008a058)
  github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
  github.com/spf13/cobra@v1.1.1/command.go:895
github.com/rclone/rclone/cmd.Main()
  github.com/rclone/rclone/cmd/cmd.go:538 +0x9a
main.main()
  github.com/rclone/rclone/rclone.go:14 +0x25

The Windows error looks pretty much the same but I'm dumping it here just in case there's something useful:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x60 pc=0x15579df]

goroutine 1 [running]:
github.com/rclone/rclone/fs/operations.Copy(0x287e080, 0xc00003a0d8, 0x28958a0, 0xc0004a30e0, 0x0, 0x0, 0xc00003446f, 0x10, 0x2894da0, 0xc00162f480, ...)
        github.com/rclone/rclone/fs/operations/operations.go:514 +0x7bf
github.com/rclone/rclone/fs/operations.moveOrCopyFile(0x287e080, 0xc00003a0d8, 0x28958a0, 0xc0004a30e0, 0x2894d20, 0xc0004eca00, 0xc00003446f, 0x10, 0xc00003446f, 0x10, ...)
        github.com/rclone/rclone/fs/operations/operations.go:1670 +0x66f
github.com/rclone/rclone/fs/operations.CopyFile(...)
        github.com/rclone/rclone/fs/operations/operations.go:1688
github.com/rclone/rclone/cmd/copy.glob..func1.1(0xc0004a5f80, 0xc000035f3a)
        github.com/rclone/rclone/cmd/copy/copy.go:85 +0xf6
github.com/rclone/rclone/cmd.Run(0xc000310101, 0x2118f80, 0xc0005f7d38)
        github.com/rclone/rclone/cmd/cmd.go:248 +0xd1
github.com/rclone/rclone/cmd/copy.glob..func1(0x2118f80, 0xc0003158c0, 0x2, 0x4)
        github.com/rclone/rclone/cmd/copy/copy.go:81 +0x135
github.com/spf13/cobra.(*Command).execute(0x2118f80, 0xc000315880, 0x4, 0x4, 0x2118f80, 0xc000315880)
        github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x21155c0, 0x5fa64f37, 0x325efc0, 0xc000068058)
        github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.1/command.go:895
github.com/rclone/rclone/cmd.Main()
        github.com/rclone/rclone/cmd/cmd.go:538 +0xa5
main.main()
        github.com/rclone/rclone/rclone.go:14 +0x27

Please let me know if you need me to provide any other information.

Thanks!

Edit: Forgot to mention that uploads to the remote work fine. I do nightly uploads to google drive using rclone beta and there's no errors.

**Comment by darthShadow** [comment]
The fix for this should be simple if you want to try it:

Change the line @ https://github.com/rclone/rclone/blob/master/fs/operations/operations.go#L514

from `if src.String() != newDst.String() {` to `if newDst != nil && src.String() != newDst.String() {`

**Comment by ncw** [comment]
This was introduced in 127f0fc64c3be40e04918568a082fcf7fa1283ac

Your fix looks good @darthShadow - want to send a PR?

**Comment by darthShadow** [comment]
Sure, will send it by tomorrow if @slickag doesn't do it by then.

**Comment by darthShadow** [comment]
Closing the issue since the PR has been merged.

**Comment by ncw** [comment]
> Closing the issue since the PR has been merged.

Next time put `Fixes #4747` in the PR and it will close it for you :-) I'm sure you know this already, but if you don't it is very useful.
