### ISSUE TITLE
failed to configure token

### ISSUE THREAD

**Issue by Sanju-Thomas** [rclone/rclone#4749]
#### What is the problem you are having with rclone?

failed to configure toke: unsupported protocol scheme

#### What is your rclone version (output from `rclone version`)
rclone v1.53.2
- os/arch: linux/amd64
- go version: go1.15.3

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
arch linux

####  Which cloud storage system are you using? (e.g. Google Drive)

gdrive

**Comment by darthShadow** [comment]
Please add the following details too:

#### Redacted Config File
#### The command you were trying to run (e.g. rclone copy /tmp remote:tmp)
#### A log from the command with the -vv flag (e.g. output from rclone -vv copy /tmp remote:tmp)

**Comment by ivandeex** [comment]
Closed due to 3 months of inactivity.
