### ISSUE TITLE
rclone as docker volume plugin

### ISSUE THREAD

**Issue by ivandeex** [rclone/rclone#4750]
Here is a feature idea from https://github.com/sapk/docker-volume-rclone/issues/6.
It would be fairly possible to add a `rclone serve docker` command exposing a docker volume api if allowed by rclone maintainers.

The implentation is in fact a combination of `mount` and http server with a limited number of API commands (create, remove, mount, unmount).
Currently implemented by https://github.com/sapk/docker-volume-rclone mostly in https://github.com/sapk/docker-volume-rclone/blob/master/rclone/driver/driver.go.
As can be seen, the codebase is pretty small.

**Comment by ivandeex** [comment]
blocks on #2968

**Comment by ncw** [comment]
This looks equivalent in complexity to `rclone serve restic` so not too complex.

There seem to be a lot of boilerplate around creating images to run as a docker plugin but maybe we should put the core `rclone serve docker` into rclone itself. What do you think @sapk ?

**Comment by sapk** [comment]
I can work on it. I had already work on the `serve ftp` command so that why I suggest it.

There is two way of running docker plugin:
- Running a daemon on host, listening on a socket for docker requests.
- Package everything in a specific container that docker manage itself.

For the alter one the process is working fine but still a bit hacky to put together.

**Comment by ivandeex** [comment]
Let's start from the first bullet, which implements the `rclone serve docker` listener.
Let's think of adding the plugin container packaging into rclone makefiles later. For now this can live in the sapk/docker-volume-rclone makefiles.

**Comment by sapk** [comment]
I started working on that issue here: https://github.com/sapk-fork/rclone/tree/serve-docker
