### ISSUE TITLE
Instructions for making client ID do not work

### ISSUE THREAD

**Issue by thracyturnix** [rclone/rclone#4754]
#### What is the problem you are having with rclone?

(Google Drive)

https://rclone.org/drive/#making-your-own-client-id

says:

Click "Credentials" in the left-side panel (not "Create credentials", which opens the wizard), then "Create credentials"

If you already configured an "Oauth Consent Screen", then skip to the next step; if not, click on "CONFIGURE CONSENT SCREEN" button (near the top right corner of the right panel), then select "External" and click on "CREATE"; on the next screen, enter an "Application name" ("rclone" is OK) then click on "Save" (all other data is optional). Click again on "Credentials" on the left panel to go back to the "Credentials" screen.

-

I click on 'Credentials" in the left-hand panel, and this is what I see
http://i.imgur.com/CfTutme.png

I have not configured "Oauth Consent Screen: There is no "Configure Consent Screen" button near top right corner of right panel.

#### What is your rclone version (output from `rclone version`)

1.52.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

xubuntu 20.04 x64

####  Which cloud storage system are you using? (e.g. Google Drive)

Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

^

**Comment by animosity22** [comment]
Google frequently changes menus and such as it's hard to keep up documentation like that.

If you have suggestion or changes, please let us know and submit a PR to update it.

**Comment by thracyturnix** [comment]
Thanks for getting back to me

I would help if I could figure out how to do the task, but after about 30
minutes of messing about with your software and the instructions on your
web page I gave up. It was too confusing.

I hope you are able to resolve this in future as the app looks promising
and I would like to be able to use it.

Best wishes

Jim

**Comment by darthShadow** [comment]
Please try these instructions instead and see if that works: https://github.com/Cloudbox/Cloudbox/wiki/Google-Drive-API-Client-ID-and-Client-Secret

**Comment by tjanez** [comment]
I tried to set up my own client_id today and I got the  _Error 403: access_denied_ error.

What I was missing was to go back to [Google Developer Console, OAuth consent screen](https://console.developers.google.com/apis/credentials/consent) and set _Publishing status_ to _In production_.

**Comment by Steve-Z** [comment]
@tjanez I had the same experience. I solved it by adding myself as a test user as is described [here](https://github.com/googleapis/google-api-php-client/issues/2001#issuecomment-754136442). I had assumed that, since this I was the owner/creator of the app/project, Google would implicitly recognize me as an authorized user. Apparently it did not. When I added my email to test users, that seemed to fix this. So adding yourself as a test user is an alternative to moving to "Production". Google's documentation makes it seem that there may be a review period for production apps that authorize full-access scope (makes sense). Since I am only using this for myself, I do not see that I will ever need to move beyond "Testing" or add any other user.

@animosity22 Did you create a PR to add this instruction to [this section](https://rclone.org/drive/#making-your-own-client-id) of documentation?

**Comment by animosity22** [comment]
I have no way to recreate them as my stuff is already setup.

**Comment by Steve-Z** [comment]
@animosity22 I would be willing to create a pull request with a small edit of [these instructions](https://github.com/rclone/rclone/blob/master/docs/content/drive.md). This is the current content from the ["Making your own client ID"](https://rclone.org/drive/#making-your-own-client-id) section:

> Be aware that, due to the "enhanced security" recently introduced by Google, you are theoretically expected to "submit your app for verification" and then wait a few weeks(!) for their response; in practice, you can go right ahead and use the client ID and client secret with rclone, the only issue will be a very scary confirmation screen shown when you connect via your browser for rclone to be able to get its token-id (but as this only happens during the remote configuration, it's not such a big deal).

This is what I propose:
> Be aware that, due to the "enhanced security" recently introduced by Google, if you choose "Production" for your app, you are theoretically expected to "submit your app for verification" and then wait a few weeks(!) for their response; alternatively, you can remain in "Testing" of your app, but _you will need to add yourself as a test user_ (and possibly approve the relevant scope). Either way, you can go right ahead and use the client ID and client secret with rclone, the only issue will be a very scary confirmation screen shown when you connect via your browser for rclone to be able to get its token-id (but as this only happens during the remote configuration, it's not such a big deal).

I tried creating a new pull request, but I am not able to. Do these changes make sense? Is there any relative advantage of "Production" vs "Testing" if, as in my case, there is only a single user? (eg, does Google allow "Testing" to go on indefinitely?)

**Comment by rockliffe** [comment]
The authorization expires in 7 days in Testing mode.  
Now you are forced to submit a video for the Verification for Production Mode.

**Comment by animosity22** [comment]
I'll close this item out and finally work on doing the update as I think I have what I need (time). Once I start the pull request, I'll link it back here.

Thanks!
