### ISSUE TITLE
operations/delete with filter not work as expect with api mode

### ISSUE THREAD

**Issue by hahanonym** [rclone/rclone#4755]
#### What is the problem you are having with rclone?

Use operations/delete with filter not work as expect with api mode。
**parameter “remote” not work！！！**

![image](https://user-images.githubusercontent.com/9391031/98656914-35c5bb80-237c-11eb-97c1-256b3a5c8b1c.png)

#### What is your rclone version (output from `rclone version`)

{
	"arch": "amd64",
	"decomposed": [
		1,
		53,
		1
	],
	"goVersion": "go1.15",
	"isBeta": false,
	"isGit": false,
	"os": "windows",
	"version": "v1.53.1"
}

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

WIn10 64 bit

####  Which cloud storage system are you using? (e.g. Google Drive)

local file system（mount by nfs）

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

operations/delete api mode

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

![image](https://user-images.githubusercontent.com/9391031/98656020-24c87a80-237b-11eb-9485-fec7e900cc63.png)
![image](https://user-images.githubusercontent.com/9391031/98656070-3447c380-237b-11eb-9dff-6224fee6ecf8.png)

**Comment by hahanonym** [comment]
sorry，i debug the src，and solve this problem。
some operation(delete/uploadfile/cleanup) doesn't have remote，but use “fs” like a path （include driver and remote）

**Comment by darthShadow** [comment]
Ok, glad you were able to get it fixed.
