### ISSUE TITLE
problem in connecting to dropbox

### ISSUE THREAD

**Issue by imerelli** [rclone/rclone#4762]
Hi, 
I configured rclone for my Dropbox account without problems, but now I get:
2020/11/12 11:04:05 Failed to create file system for "hsr:/": get current account failed: invalid character '<' looking for beginning of value
Any idea of what is going wrong?

**Comment by darthShadow** [comment]
This seems like a usage question. Can you please post this on the forums at https://forum.rclone.org as we would like to keep Github for only verified issues?
