### ISSUE TITLE
rclone on Windows 10 mounting GoogleDrive suffering extended pauses

### ISSUE THREAD

**Issue by jamesdavidhoward** [rclone/rclone#4770]
#### What is the problem you are having with rclone?
`rclone` on Windows 10 occasionally suffers extended pauses / stutters upon 1st use of a mountpoint to make my Google Drive visible/available.  This can last several minutes, but seems to resolve itself - in a way not obvious to me.  Symptoms are a "`dir`" listing of the mounted Drive hanging for a while, and file opens (as by mention of a `...\GoogleDrive\random.txt` pathname in a `notepad` command) suffer a pregnant pause, then come up.

Note: other network accesses, as by CIFS/SMB mounts or https: browsing are unaffected at the same time.

#### What is your rclone version (output from `rclone version`)
rclone v1.53.1
- os/arch: windows/amd64
- go version: go1.15
also:
WinFsp 2020.1 ver 1.7.20172

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Microsoft Windows 10 Pro, version 10.0.19042.630,  build 19042.630  x86_64
(the above is a Beta Channel tier "Windows Insiders" build)

####  Which cloud storage system are you using? (e.g. Google Drive)
Google Drive, via WinFsp 'FUSE on Windows' tool

#### The command you were trying to run
The script "`userLogin.cmd`" has been set in Local Group Policies to be run upon login as an iconized `CMD.EXE` window.  It contains 1 (one) command - the rclone mount operation:
   ` rclone mount JamesDavidHoward-GoogleDrive:  C:\Users\jdhoward\CloudStores\GoogleDrive --allow-other`
Note: `...\GoogleDrive` does not pre-exist, so a Windows mount operation won't complain.  After mount, the referenced location becomes a JUNCTION:
`11/11/2020  23:39    <JUNCTION>     GoogleDrive [\Device\Volume{1b497809-24ba-11eb-9457-c025e91ee596}\]`

#### Content of rclone config file (with secrets removed)
The` rclone.config` file has been used successfully for over 6 months.  The non-commented lines are:

```
[JamesDavidHoward-GoogleDrive]
type = drive
client_id = 621***9-538***5m.apps.googleusercontent.com
client_secret = R**A***uO**U
scope = drive
root_folder_id = 0A***Uk9PVA
token = {"access_token":"ya29.***BM-YrIoL4***Xov0Nd******IdnRrP7lKyFUOuFPtR2MEcFG4bYZKZKZjcu7VlPEf3maJOpJUECTQ0E6yyYwiGRt********wcHSH1su-95******w7A","token_type":"Bearer","refresh_token":"1//06eL53eM*************G*****4***4afe-YdPSs9-L3mHs","expiry":"2020-11-14T18:12:09.7803123-08:00"}
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
The messages appearing in the `cmd.exe` window running `rclone` (after un-iconizing) tell of IO ERRORs.  I do not know if they are due to some behaviour of WinFsp. The salient thing in the log appears to be complaints that:
       ` www.googleapis.com: no such host`
I don't understand that, because when I do a "`nslookup  www.googleapis.com`" I immediately get:
```
Non-authoritative answer:
Name:    www.googleapis.com
Addresses:  2607:f8b0:4005:808::200a
          2607:f8b0:4005:80a::200a
          2607:f8b0:4005:807::200a
          172.217.6.74
          216.58.194.170
          172.217.5.106
          216.58.194.202
```

Here are the error messages.  Note that 1 appears before the announcement that the `rclone service has been started`, and the other messages afterward.

```
2020/11/11 23:39:13 ERROR : Google drive root '': Statfs failed: failed to get Drive storageQuota: Get "https://www.googleapis.com/drive/v3/about?alt=json&fields=storageQuota&prettyPrint=false": dial tcp: lookup www.googleapis.com: no such host
The service rclone has been started.
2020/11/11 23:39:15 ERROR : /: Dir.Stat error: couldn't list directory: Get "https://www.googleapis.com/drive/v3/files?alt=json&fields=files%28id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks%29%2CnextPageToken%2CincompleteSearch&includeItemsFromAllDrives=true&pageSize=1000&prettyPrint=false&q=trashed%3Dfalse+and+%28%270ACjcLC1mkxSSUk9PVA%27+in+parents%29&supportsAllDrives=true": dial tcp: lookup www.googleapis.com: no such host
2020/11/11 23:39:15 ERROR : IO error: couldn't list directory: Get "https://www.googleapis.com/drive/v3/files?alt=json&fields=files%28id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks%29%2CnextPageToken%2CincompleteSearch&includeItemsFromAllDrives=true&pageSize=1000&prettyPrint=false&q=trashed%3Dfalse+and+%28%270ACjcLC1mkxSSUk9PVA%27+in+parents%29&supportsAllDrives=true": dial tcp: lookup www.googleapis.com: no such host
2020/11/11 23:39:15 ERROR : /: Dir.Stat error: couldn't list directory: Get "https://www.googleapis.com/drive/v3/files?alt=json&fields=files%28id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks%29%2CnextPageToken%2CincompleteSearch&includeItemsFromAllDrives=true&pageSize=1000&prettyPrint=false&q=trashed%3Dfalse+and+%28%270ACjcLC1mkxSSUk9PVA%27+in+parents%29&supportsAllDrives=true": dial tcp: lookup www.googleapis.com: no such host
2020/11/11 23:39:15 ERROR : IO error: couldn't list directory: Get "https://www.googleapis.com/drive/v3/files?alt=json&fields=files%28id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks%29%2CnextPageToken%2CincompleteSearch&includeItemsFromAllDrives=true&pageSize=1000&prettyPrint=false&q=trashed%3Dfalse+and+%28%270ACjcLC1mkxSSUk9PVA%27+in+parents%29&supportsAllDrives=true": dial tcp: lookup www.googleapis.com: no such host
```

**Comment by darthShadow** [comment]
Please check your firewall settings to ensure that rclone is not getting blocked anywhere.

**Comment by ivandeex** [comment]
Closed due to user inactivity
