### ISSUE TITLE
Homebrew depreciation

### ISSUE THREAD

**Issue by xaocon** [rclone/rclone#4775]
#### What is the problem you are having with rclone?
Homebrew installation is being depreciated

#### What is your rclone version (output from `rclone version`)
rclone v1.53.2-DEV
- os/arch: darwin/amd64
- go version: go1.15.3

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

None of this other stuff applies to this issue but I read them.
I took a look for reports of this issue already but didn't see one. This seems to be a pretty new change too. The problem is related to the fact fuse is required. See https://github.com/Homebrew/homebrew-core/commit/4f0402fb80551779c603add4c8b67a51bd324f09 for more details.

**Comment by ncw** [comment]
I put a comment on commit https://github.com/Homebrew/homebrew-core/commit/4f0402fb80551779c603add4c8b67a51bd324f09#commitcomment-44223361

> Note that rclone runs fine without FUSE installed (it dynamically loads it if present), it just can't run rclone mount.

@darthShadow - do you want to follow up on this one since you know something about brew and updated the rclone recipe recently?

**Comment by darthShadow** [comment]
Sure, will do.

I was planning to anyway setup a separate tap (if nobody else does it) so we can have the mount command even once they remove support for FUSE since we will get too many issues otherwise about the missing mount command.

**Comment by darthShadow** [comment]
Once I do send the PR, we will have the binary not supporting the mount command. How do you want to handle that? Perhaps a separate build tag which can be used in Homebrew that prints out a message (on using mount) regarding the lack of mount support and to download the binary from the website if they want it?

**Comment by xaocon** [comment]
It's not up to me but I think the right thing to do is remove the depends
and the depreciated and then add something in the `caveats` stanza that
mentions that mount won't work without fuse and leave it up to the user to
decide how they want to handle.

**Comment by ncw** [comment]
> Once I do send the PR, we will have the binary not supporting the mount command. How do you want to handle that? Perhaps a separate build tag which can be used in Homebrew that prints out a message (on using mount) regarding the lack of mount support and to download the binary from the website if they want it?

That is a nice idea. So a `brew` build tag maybe?

**Comment by darthShadow** [comment]
Yep, will send a PR in the next few days if that's fine?

**Comment by xaocon** [comment]
Seems like maybe I jumped the gun on this after reading the the comments on the depreciation. I think just updating the formula to remove the fuse dependency for build is the right way to go. No reason to keep the prebuilt binaries from using fuse if it's available. Still might be worth mentioning it in `caveats`.
