### ISSUE TITLE
s3: Make rclone purge delete directory markers

### ISSUE THREAD

**Issue by trademark18** [rclone/rclone#4779]
#### What is your current rclone version (output from `rclone version`)?
1.53.2

#### What problem are you are trying to solve?
Need to be able to delete "empty folders" (directory markers) in IBM ICOS.

#### How do you think rclone should be changed to solve that?
Per @ncw description here https://github.com/rclone/rclone/issues/100#issuecomment-728105550

Note: Somehow this seems to already work fine on a Standard tier bucket, but not on a Smart Tier bucket.  This should at least be a test case for this feature.

Thanks!

**Comment by ncw** [comment]
We already do this in the swift backend for exactly this reason

https://github.com/rclone/rclone/blob/095c7bd801a8ef01bb4a9c792340fa3c0a302fe8/backend/swift/swift.go#L843-L846

This would be fairly easy I think - adapting the code from the swift backend (and updating `overview.md`) if someone would like to have a go at it?

**Comment by ivandeex** [comment]
Marking as important since a number of other tickets request the same - emulation of directories for backet remotes.

**Comment by ncw** [comment]
This particular issue needs a fix in the s3 backend - it needs Purge implementing.

**Comment by ncw** [comment]
This is now implemented.

We also now have proper directory marker support

      --azureblob-directory-markers   Upload an empty object with a trailing slash when a new directory is created
      --gcs-directory-markers         Upload an empty object with a trailing slash when a new directory is created
      --s3-directory-markers          Upload an empty object with a trailing slash when a new directory is created
