### ISSUE TITLE
rclone cache does not synchronize with onedrive

### ISSUE THREAD

**Issue by tkn777** [rclone/rclone#4780]
#### What is the problem you are having with rclone?

I am running 'rclone mount' on my server, like:

```
/usr/bin/rclone mount \
        onedrive:/ \
        /mnt/onedrive \
        --config myconfig \
        --daemon \
        --no-modtime \
        --cache-workers 8 \
        --cache-db-path /var/cache/onedrive \
        --cache-dir /var/cache/onedrive \
        --cache-chunk-path /var/cache/onedrive \
        --cache-chunk-total-size 2G \
        --vfs-cache-mode writes \   # same with full
        --vfs-cache-max-size 20G \
        --vfs-cache-poll-interval 10s \
        --vfs-cache-max-age 5m \
        --dir-cache-time 1m

```
with onedrive `myconfig`:

```
[onedrive]
type = onedrive
token = {"access_token":"EwB4A8l6BAAU6[...]}
drive_id = 18[...]
drive_type = personal
```

1. I create a file in the mounted drive on my server.

   `touch /mnt/onedrive/newfile.txt`

1. This file (`newfile.txt`) gets uploaded to my onedrive (automatically and asynchronously by rclone).

1. Then I deleted the file on the onedrive (web interface).

1. But the file is still there on my server at `/mnt/onedrive/newfile.txt` even after many, many hours.
     And if a programm tries to access the file (like `file newfile.txt`), an error is thrown:

     `ERROR: cannot read 'newfile.txt' (Input/output error)`

=> So I think there is a bug regarding the cache, or the onedrive synchronization or something like that.

Unmounting and re-mounting does 'solve' the problem.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.53.1-DEV
- os/arch: linux/amd64
- go version: go1.15.2
```
Package from debian testing (aka 'bullseye').

I got the same problem with current version from rclone (github).

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

`Linux [...] 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux`

####  Which cloud storage system are you using? (e.g. Google Drive)

Microsoft OneDrive (personal, Office365 single)

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

see above

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

Too much personal information (GDPR) ... Do you need something specific, I can search for ...

**Comment by tkn777** [comment]
Here is a log entry, I am wondering about:

`2020/11/16 20:21:48 DEBUG : vfs cache RemoveNotInUse (maxAge=300000000000, emptyOnly=false): item abc.txt not removed, freed 0 bytes`

The problem seems to be `maxAge`. It should be 5 minutes, as configured.

**Comment by animosity22** [comment]
What's the output of rclone version?

```
        --cache-workers 8 \
        --cache-db-path /var/cache/onedrive \
        --cache-dir /var/cache/onedrive \
        --cache-chunk-path /var/cache/onedrive \
```

This does nothing as it's for the cache backend.

**Comment by tkn777** [comment]
> Can you test on the stable?

I just tested it with `1.53.2` from here: `https://rclone.org/downloads/`

> ```
>         --cache-workers 8 \
>         --cache-db-path /var/cache/onedrive \
>         --cache-dir /var/cache/onedrive \
>         --cache-chunk-path /var/cache/onedrive \
> ```
> 
> This does nothing as it's for the cache backend.

What do you mean? I need to specify the location for the cache? What is the preferred/right way to do?

**Comment by animosity22** [comment]
I mean they are for the cache backend as I have a typo as cache-dir was not supposed to be pasted.

https://rclone.org/commands/rclone_mount/#vfs-file-caching are the flags as you have a bunch for the cache backend.

**Comment by tkn777** [comment]
I have tested again with 

/usr/bin/rclone mount \
        onedrive:/ \
        /mnt/onedrive \
        --config myconfig \
        --daemon \
        --cache-dir /var/cache/cloud \
        --vfs-cache-mode writes \
        --vfs-cache-max-size 20G \
        --vfs-cache-max-age 0 \
        --dir-cache-time 1m \
        --log-file=/tmp/rclone-log.log \
        --log-level=DEBUG

The files I created on the server and deleted at onedrive (web) are not cached (after writing).
There is absolutely no cache entry and no vfsmeta belonging to them.

I think it is `dir-cache-time` that is ignored. Because it is queried again. But I have no idea where it is cached, because all cache (known by me) is empty. May be it is some onedrive-api-cache?? Or some other problem? I really do not know.

**Comment by tkn777** [comment]
I have tried to set `--dir-cache-time 5s`

And here is some log, that is written, when I refresh the folder with the file `test-201116-224901.txt`, that I have deleted with onenote web client some minutes before:

It seems rclone reads the dir (somehow) and the dir contains the file. But it is not on my server, even not the metadata. May be it is a onedrive bug??

2020/11/16 22:50:51 DEBUG : /: Attr:
2020/11/16 22:50:51 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxrwx---, err=<nil>
2020/11/16 22:50:51 DEBUG : /: ReadDirAll:
2020/11/16 22:50:51 DEBUG : : Re-reading directory (31.406621925s old)
2020/11/16 22:50:52 DEBUG : /: >ReadDirAll: item=3, err=<nil>
2020/11/16 22:50:52 DEBUG : /: Attr:
2020/11/16 22:50:52 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxrwx---, err=<nil>
2020/11/16 22:50:52 DEBUG : /: Lookup: name="backup"
2020/11/16 22:50:52 DEBUG : /: >Lookup: node=backup/, err=<nil>
2020/11/16 22:50:52 DEBUG : backup/: Attr:
2020/11/16 22:50:52 DEBUG : backup/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxrwx---, err=<nil>
2020/11/16 22:50:52 DEBUG : /: Lookup: name="share"
2020/11/16 22:50:52 DEBUG : /: >Lookup: node=share/, err=<nil>
2020/11/16 22:50:52 DEBUG : share/: Attr:
2020/11/16 22:50:52 DEBUG : share/: >Attr: attr=valid=1s ino=0 size=0 mode=drwxrwx---, err=<nil>
2020/11/16 22:50:52 DEBUG : /: Lookup: name="test-201116-224901.txt"
2020/11/16 22:50:52 DEBUG : /: >Lookup: node=test-201116-224901.txt, err=<nil>
2020/11/16 22:50:52 DEBUG : test-201116-224901.txt: Attr:
2020/11/16 22:50:52 DEBUG : test-201116-224901.txt: >Attr: a=valid=1s ino=0 size=4 mode=-rw-rw----, err=<nil>

**Comment by tkn777** [comment]
Even setting `--dir-cache-time 5s` does not solve the problem.

It must not be a onedrive problem (only), because after remounting, the deleted files are gone.

**Comment by animosity22** [comment]
One Drive doesn't poll for changes but with a dir-cache-time low, it should see the new stuff.

I'm not sure offhand what else to grab.

**Comment by darthShadow** [comment]
This should be fixed in the latest beta release and is probably the same issue as #4446.

**Comment by darthShadow** [comment]
You can grab the latest beta from https://beta.rclone.org/

**Comment by tkn777** [comment]
Thank you very much. Now it works perfect! :)
