### ISSUE TITLE
compress: integration test failures

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#4797]
I was just putting the `compress` backend into the integration tester 7078311a844fe7a12b66ff6e632065d20b48b7d2

Testing with `test_all -backends compress` I get two failures

I'm not quite sure what is going on here

```
"./operations.test -test.v -test.timeout 1h0m0s -remote TestCompress: -test.run '^TestCopyFileMaxTransfer$'" - Starting (try 5/5)
=== RUN   TestCopyFileMaxTransfer
    run.go:176: Remote "Compressed: TestCompress:rclone-test-tayocel3guvefod1yitucot5", Local "Local file system at /tmp/rclone401845160", Modify Window "1ns"
2020/11/23 17:21:29 NOTICE: TestCopyFileMaxTransfer/file2.DggAAAAAAAA.gz: Removing partially written file on error: Max transfer limit reached as set by --max-transfer
2020/11/23 17:21:29 ERROR : TestCopyFileMaxTransfer/file2: Failed to copy: Max transfer limit reached as set by --max-transfer
2020/11/23 17:21:29 ERROR : TestCopyFileMaxTransfer/file4: Failed to copy: Max transfer limit reached as set by --max-transfer
    operations_test.go:1481: 
        	Error Trace:	operations_test.go:1481
        	Error:      	Received unexpected error:
        	            	Max transfer limit reached as set by --max-transfer
        	Test:       	TestCopyFileMaxTransfer
--- FAIL: TestCopyFileMaxTransfer (0.05s)
FAIL
"./operations.test -test.v -test.timeout 1h0m0s -remote TestCompress: -test.run '^TestCopyFileMaxTransfer$'" - Finished ERROR in 79.814449ms (try 5/5): exit status 1: Failed [TestCopyFileMaxTransfer]
```

Here more than one file is transferred indicating that something is up with the filename normalisation.

```
"./sync.test -test.v -test.timeout 1h0m0s -remote TestCompress: -test.run '^TestSyncUTFNorm$'" - Starting (try 5/5)
=== RUN   TestSyncUTFNorm
    run.go:176: Remote "Compressed: TestCompress:rclone-test-bucinul6bituqek0calicef6", Local "Local file system at /tmp/rclone406449674", Modify Window "1ns"
    sync_test.go:1859: 
        	Error Trace:	sync_test.go:1859
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 3
        	Test:       	TestSyncUTFNorm
--- FAIL: TestSyncUTFNorm (0.02s)
FAIL
"./sync.test -test.v -test.timeout 1h0m0s -remote TestCompress: -test.run '^TestSyncUTFNorm$'" - Finished ERROR in 50.719662ms (try 5/5): exit status 1: Failed [TestSyncUTFNorm]
```

I used this as the remote

```
[TestCompress]
type = compress
remote = /tmp/compress-test
```

Can you take a look @buengese ? Thank you :-)

**Comment by ivandeex** [comment]
_integration_ label marks issues with external software (feel free to rename to smth more appropriate)

**Comment by ncw** [comment]
I noticed that some of the docs from [writing a new backend](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#user-content-writing-a-new-backend) are missing:

  * `README.md` - main GitHub page
  * `docs/content/overview.md` - overview docs
  * `docs/content/docs.md` - list of remotes in config section
  * `docs/layouts/chrome/navbar.html` - add it to the website navigation
  * `bin/make_manual.py` - add the page to the `docs` constant

I can add these if you want @buengese

**Comment by ncw** [comment]
@ivandeex 
> _integration_ label marks issues with external software (feel free to rename to smth more appropriate).
> probably _maintenance_ will be better but I'm not sure

I think a category for integration test failures would be a good idea - what would you suggest?

**Comment by ivandeex** [comment]
🤔 _maintenance_ -> _test failure_

**Comment by ncw** [comment]
>  _maintenance_ -> _test failure_

Great :-)

**Comment by buengese** [comment]
Uh didn't see this. I actually did the doc stuff but forgot to ever commit it. Not sure what's going on with the test failures I'll look into it later.

**Comment by buengese** [comment]
@ncw 
Regarding the MaxTransfer failure. Compress calls operations.Rcat() which probably means that the transfer is accounted for twice. I guess calling operations from inside a backend isn't optimal so I'll probably have to change this.
