### ISSUE TITLE
You can't change from token to service account authentication using v. 1.29 config

### ISSUE THREAD

**Issue by gdubicki** [rclone/rclone#480]
I have been using rclone v. 1.29 with token authentication to Google Cluond Storage with the following config:

```
[root@hostname ~]# cat .rclone.conf
[gcs]
type = google cloud storage
client_id =
client_secret =
project_number = <some project number>
object_acl =
bucket_acl =
token = <some access token>
```

Recently I switched to rclone build from current source (3bdad260b012bca4a5b89dc6b357484b76f0e273) to switch to service account auth.

But when I tried to edit the current config with `rclone config` the wizard did not propose to change auth method to service account.

Only when I deleted the old config and re-run `rclone config` I was able to set up service account auth.

My OS: 

```
CentOS Linux release 7.2.1511 (Core)

Linux hostname 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ncw** [comment]
Hmm, yes, the wizard isn't that clever ;-)

Thanks for reporting - I'll have a think on what to do.

**Comment by ivandeex** [comment]
@gdubicki This issue is stale for 4 years. Let's reproduce it or clise it.

**Comment by gdubicki** [comment]
I am not using rclone anymore so...
