### ISSUE TITLE
cmount: failed when host.Unmount in macOS 11 Big Sur and rclone hangs for long time

### ISSUE THREAD

**Issue by wxiaoguang** [rclone/rclone#4804]
#### What is the problem you are having with rclone?

cmount: failed when host.Unmount in macOS 11 Big Sur and rclone hangs for long time

#### What is your rclone version (output from `rclone version`)

```
osxfuse: 3.11.1

rclone v1.53.3
- os/arch: darwin/amd64
- go version: go1.15.4
```

####  Which cloud storage system are you using? (e.g. Google Drive)

Nextcloud WebDAV

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone cmount the-name:/ ~/mnt/test`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2020/11/25 13:45:42 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2020/11/25 13:45:42 DEBUG : /: >Getattr: errc=0
2020/11/25 13:45:42 DEBUG : /: Access: mask=00
2020/11/25 13:45:42 DEBUG : /: >Access: errc=0
^C
2020/11/25 13:45:47 INFO  : Signal received: interrupt
2020/11/25 13:45:47 DEBUG : Calling host.Unmount
2020/11/25 13:45:47 DEBUG : host.Unmount failed
2020/11/25 13:45:47 DEBUG : vfs cache: cleaner exiting
2020/11/25 13:45:47 INFO  : Exiting...
2020/11/25 13:45:47 DEBUG : webdav root '': Destroy:
2020/11/25 13:45:47 DEBUG : webdav root '': >Destroy:
^C^C^C^C^C ( no response)
( after long time, rclone ends without any more outputs. )
```

**Comment by ncw** [comment]
Are there files in use on the mount? It can't unmount until there are no files in use.

**Comment by wxiaoguang** [comment]
I am not sure (is there any method do see whether the files are still in use?)

More information:

1. When `cmount` unmount failed and hangs (no response to ^C), the mounted folder is already empty, `ls ~/mnt/test` finishes immediately and shows nothing.

2. only `cmount` hangs, `mount` can unmount successfully immediately.

**Comment by ncw** [comment]
Big Sur is the latest release macOS isn't it? (Sorry not a mac user). So do you think this is a regression to do with that rather than anything else?

When rclone is hung so when it has printed `Exiting...` can you kill the rclone process with `kill -QUIT pid-of-rclone`

This should generate a backtrace which shows exactly where rclone is stuck - can you post it here please?

Here is where rclone prints that message - note the Exit immediately after which is puzzling...

https://github.com/rclone/rclone/blob/979bb07c86f9680466e9421da116aaf3af94c1da/lib/atexit/atexit.go#L45-L46

**Comment by wxiaoguang** [comment]
Sorry I didn't mean it is a regression ( I just have only macOS 11 Big Sur ....)

Very strange, the `kill -QUIT` doesn't give any output, it seems that the `rclone` process has entered a exiting state:
```
$ ps ax | grep rclone
21683 s000  ?E+    0:00.00 (rclone)
```

I think the duration of the hang time is exactly 1 minute during my several tests.

This problem may be not that serious but a little annoying ...

(I am using oh-my-zsh with timestamp on the prompt)
![image](https://user-images.githubusercontent.com/2114189/100405753-3742f380-309f-11eb-9c00-a5e84113b19d.png)

**Comment by ncw** [comment]
> Very strange, the `kill -QUIT` doesn't give any output, it seems that the `rclone` process has entered a exiting state:
> 
> ```
> $ ps ax | grep rclone
> 21683 s000  ?E+    0:00.00 (rclone)
> ```

That kind of implies the rclone process has exited. According to the (BSD) man page

> +       The process is in the foreground	process	group of its		       control terminal.
> E       The process is trying to	exit.

So I think the OS must be keeping it alive for some reason. This is probably because the `host.Unmount` didn't work properly. This has been discussed here https://github.com/billziss-gh/cgofuse/issues/6 in the past.

I wonder if this is caused by rclone intercepting CTRL-C and not letting libfuse handle it.

I traced the code and I discovered
- sometimes the unmount is called twice when a signal is received
- rclone and cgofuse/libfuse are racing to see who can shutdown the filesystem when a signal is received

I've attempted to fix both of these here - hopefully this will fix your problem - can you give it a go?

[v1.54.0-beta.4926.a98cb2da0.fix-4804-umount](https://beta.rclone.org/branch/fix-4804-umount/v1.54.0-beta.4926.a98cb2da0.fix-4804-umount/) on branch [fix-4804-umount](https://github.com/rclone/rclone/tree/fix-4804-umount) (uploaded in 15-30 mins)

**Comment by wxiaoguang** [comment]
```
2020/11/27 19:19:19 DEBUG : /: Releasedir: fh=0x0
2020/11/27 19:19:19 DEBUG : /: >Releasedir: errc=0
^C
2020/11/27 19:19:20 INFO  : Signal received: interrupt
2020/11/27 19:19:20 DEBUG : Cache remote home-storage-user-collection:: Services stopped
2020/11/27 19:19:20 DEBUG : Cache remote home-storage-user-collection:: Destroy:
2020/11/27 19:19:20 DEBUG : Not calling host.Unmount as signal received
2020/11/27 19:19:20 DEBUG : Cache remote home-storage-user-collection:: >Destroy:
2020/11/27 19:19:20 DEBUG : vfs cache: cleaner exiting
2020/11/27 19:19:20 DEBUG : Unmounted successfully
2020/11/27 19:19:20 INFO  : Exiting...
```

Result:
* No 'failed' message, but `Unmounted successfully`
* It still hangs for 1 minute exactly, the stop time is `19:20:20`

**Comment by ncw** [comment]
OK, thanks for testing. I think rclone is doing the right thing now.

Can you try the cgofuse example and see if you get the same problem? You'll need Go installed for this.

```
$ go get github.com/billziss-gh/cgofuse/examples/hellofs
$ hellofs
fuse: missing mountpoint parameter
$ hellofs /mnt/tmp/
```

In a new window

```
$ ls /mnt/tmp/
hello
$ cat /mnt/tmp/hello 
hello, world
```

Then CTRL-C the first one

**Comment by 88lex** [comment]
As another method: This command forces an unmount when rclone mount hangs (in Big Sur and other versions)

diskutil unmountDisk force /Volumes/MacDrive/Users/Username/Mountname

Insert the location of your own mount of course. I find using the full path is most effective.

Separately: I'm finding that cmount and mount do not work with Big Sur and older versions of MacFuse. However, using beta MacFuse 4.0.3 and  rclone v1.54.0-beta.4932.bcbe393af the mount is successful but then after and hour or more it randomly fails (The mount disappears. I I suspect a Fuse+Big Sur issue not an rclone issue). Using an older version of Mac OS all still works fine. Will keep playing and post separately if the problem persists.

**Comment by ncw** [comment]
@88lex useful info thanks.



> As another method: This command forces an unmount when rclone mount hangs (in Big Sur and other versions)
> 
> `diskutil unmountDisk force /Volumes/MacDrive/Users/Username/Mountname`
> 
> Insert the location of your own mount of course. I find using the full path is most effective.

Ah so it is definitely the OS keeping hold of rclone here.



> Separately: I'm finding that cmount and mount do not work with Big Sur and older versions of MacFuse. However, using beta MacFuse 4.0.3 and rclone v1.54.0-beta.4932.bcbe393af the mount is successful

That is good



> but then after an hour or more it randomly fails (The mount disappears. I I suspect a Fuse+Big Sur issue not an rclone issue).

:-(

Can you check the system logs here? Do you see stuff about rclone being killed?

**Comment by wxiaoguang** [comment]
> OK, thanks for testing. I think rclone is doing the right thing now.
> 
> Can you try the cgofuse example and see if you get the same problem? You'll need Go installed for this.
> 
> ```
> $ go get github.com/billziss-gh/cgofuse/examples/hellofs
> $ hellofs
> fuse: missing mountpoint parameter
> $ hellofs /mnt/tmp/
> ```
> 
> In a new window
> 
> ```
> $ ls /mnt/tmp/
> hello
> $ cat /mnt/tmp/hello 
> hello, world
> ```
> 
> Then CTRL-C the first one

`hellofs` works fine. During these tests, every time I hit `^C` then `hellofs` exits immediately. Even if I am in `mnt/test` directory (directory busy?), `hellofs` can still exit right after `^C`.

**Comment by ncw** [comment]
> `hellofs` works fine. During these tests, every time I hit `^C` then `hellofs` exits immediately. Even if I am in `mnt/test` directory (directory busy?), `hellofs` can still exit right after `^C`.

Thank you for testing that.

> ps: my osxfuse: 3.11.2

Can you try a newer one?

**Comment by 88lex** [comment]
> 
> Can you check the system logs here? Do you see stuff about rclone being killed?

The mount starts as expected (it's been running well for several years with the same flags across a million rclone releases on Mac OS). After a few minutes the mount disappears. Using the latest beta releases and MacFuse 4.04 (updated from 4.03) the dead mount releases from the OS after a couple minutes (allowing a remount) ... which it did not do previously. Alas, it still dies after a few minutes each time it is remounted.

Below is the end of the DEBUG log showing the failure. Everything prior to that is normal -- the mount scans/reads/writes correctly, as it has always done.

```2020/12/04 06:24:10 DEBUG : /: Access: mask=00
2020/12/04 06:24:10 DEBUG : /: >Access: errc=0
2020/12/04 06:24:10 DEBUG : /: Access: mask=00
2020/12/04 06:24:10 DEBUG : /: >Access: errc=0
2020/12/04 06:24:10 DEBUG : /: Access: mask=04
2020/12/04 06:24:10 DEBUG : /: >Access: errc=0
2020/12/04 06:24:17 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Elapsed time:       2m0.6s

2020/12/04 06:24:17 DEBUG : Google drive root 'MediaZ': Checking for changes on remote
2020/12/04 06:24:18 INFO  : vfs cache: cleaned: objects 0 (was 0) in use 0, to upload 0, uploading 0, total size 0 (was 0)
2020/12/04 06:24:32 DEBUG : Google drive root 'MediaZ': Checking for changes on remote
2020/12/04 06:24:47 DEBUG : Google drive root 'MediaZ': Checking for changes on remote
2020/12/04 06:24:57 DEBUG : /books: >Readdir: items=34471, errc=0
2020/12/04 06:24:57 DEBUG : Google drive root 'MediaZ': Destroy: 
2020/12/04 06:24:57 DEBUG : Google drive root 'MediaZ': >Destroy: 
2020/12/04 06:24:57 DEBUG : Calling host.Unmount
2020/12/04 06:24:57 DEBUG : host.Unmount failed
2020/12/04 06:24:57 DEBUG : rclone: Version "v1.54.0-beta.4939.3b24a4cad" finishing with parameters ["/usr/local/bin/rclone" "cmount" "p8:MediaZ" "/Volumes/Mac-1TB-Data/Users/88lex/MediaZ" "--daemon" "--max-read-ahead" "32M" "--transfers" "16" "--checkers" "32" "--drive-skip-gdocs" "--buffer-size" "16M" "--vfs-read-ahead" "32M" "--attr-timeout" "8760h" "--allow-other" "--drive-chunk-size" "32M" "--vfs-cache-mode" "full" "--dir-cache-time" "168h" "--cache-info-age" "168h" "--vfs-cache-max-age" "96h" "--vfs-cache-max-size" "80G" "--vfs-read-chunk-size" "32M" "--vfs-read-chunk-size-limit" "1G" "--stats" "60s" "--poll-interval" "15s" "--user-agent=lexx888" "--rc" "--rc-no-auth" "--rc-addr" ":5572" "--config" "/Volumes/Mac-1TB-Data/Users/88lex/.config/rclone/rclone.conf" "--log-level" "DEBUG"]```

**Comment by ncw** [comment]
> Below is the end of the DEBUG log showing the failure. Everything prior to that is normal -- the mount scans/reads/writes correctly, as it has always done.

What that appears to say is that the OS asked for rclone to unmount itself.

Can you think of why this might be? Maybe it is a power saving thing? Is there anything in the system logs about it?

**Comment by sntran** [comment]
I would also to chime in that I could not (c)mount any remote on Big Sur.

Here is the error if it helps:

```shell
$ rclone --version
rclone v1.53.3
- os/arch: darwin/amd64
- go version: go1.15.4
$
$ rclone cmount WEB: WEB --volname WEB --vfs-cache-mode full
kext load failed: -603947007
mount_osxfuse: the file system is not available (255)
2020/12/19 12:21:09 ERROR : Encrypted drive 'WEB:': Mount failed
2020/12/19 12:21:09 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed
```

**Comment by SenorSamuel** [comment]
Still have this problem in macOS ventura 13.1. Please help!

**What is the problem you are having with rclone?**
mount: failed when host.Unmount in macOS ventura 13.1 and rclone hangs for long time

**What is your rclone version (output from rclone version)**

macfuse: 4.4.1
rclone: v1.58.0
system version: macOS ventura 13.1  x86

**The command you were trying to run (e.g. rclone copy /tmp remote:tmp)**
rclone mount the-name:/ [myDir]

A log from the command with the -vv flag (e.g. output from rclone -vv copy /tmp remote:tmp)
2022/12/23 14:37:46 /xxxxx/rclone/cmd/cmount/fs.go:638: DEBUG : /: >Access: errc=0
2022/12/23 14:37:48 /xxxxx/rclone/extern/rpc/rpc_notifier.go:157: DEBUG : [conflict-solve] NotifyEventTypeOfPermissionPreview GroupName=R&D
2022/12/23 14:37:51 /xxxxx/rclone/cmd/help.go:34: DEBUG : rclone: Version "v1.58.0-DEV" finishing with parameters ["rclone" "mount" "xxx:xxx" "[myDir]" "--config" "[configFile]" "-vv" "--cache-dir" "[cache]" "--vfs-cache-mode" "full" "--vfs-cache-max-age" "720h0m0s" "--dir-cache-time" "5s" "--vfs-write-back" "5s" "--daemon" "--log-format" "date,time,longfile" "--log-file" "/xxxx/rclone.log"]
2022/12/23 14:38:00 /xxxx/rclone/lib/atexit/atexit.go:51: INFO  : Signal received: terminated
2022/12/23 14:38:00 /xxxx/rclone/cmd/cmount/mount.go:201: DEBUG : Not calling host.Unmount as signal received
2022/12/23 14:38:00 /xxxx/rclone/cmd/cmount/mount.go:208: DEBUG : Unmounted successfully
2022/12/23 14:38:00 /xxxx/rclone/cmd/mountlib/mount.go:304: ERROR : [myDir]: Unmounted rclone mount
2022/12/23 14:38:00 /xxxx/rclone/lib/atexit/atexit.go:53: INFO  : Exiting...

( after long time, rclone ends without any more outputs. )

**Comment by ncw** [comment]
I need someone who has a mac (not me!) to debug this problem further.

> 2022/12/23 14:38:00 /xxxx/rclone/lib/atexit/atexit.go:53: INFO : Exiting...

Is this where rclone hangs?

Can you try killing it with SIGQUIT and collecting the backtrace `kill -QUIT <rclonepid>`? That will tell us what rclone is stuck on at least.

**Comment by SenorSamuel** [comment]
>Is this where rclone hangs?

Yes. rclone process is killed. But the mountpoint is still unmounted  anyway. 
In `df`, The  disk info of mountpoint  is very weird. It shows all 0.

![image](https://user-images.githubusercontent.com/13415050/209341974-d704c55b-5f1a-42c0-b75c-d4c87c1798dd.png)

I tried `kill -3 <rclonepid> `. The problem reproduces. 
And the attachment is the error log print by rclone.
Please have a look.
Thanks a lot!

[](url)
[rclone.Error.log](https://github.com/rclone/rclone/files/10295198/rclone.Error.log)

**Comment by ncw** [comment]
@SenorSamuel can you upgrade to v1.61.0 which is the latest and try again? If that doesn't fix it then the result of kill -SIGHUP again would be very useful - thank you.

**Comment by SenorSamuel** [comment]
I tested the lastest `v1.61.1`. 

> kill rclone with TERM. 

The disk failed to unmount occasionally in both version.
 

     
> kill rclone with SIGQUIT. 

Resut: 
- `v1.58.0-DEV(my version)`: 
  - rclone killed. unmount **failed**(100% reproduce). The disk info of mountpoint still shows all 0. `diskutil unmountDisk force [mountpoint]` **failed**.

- `v1.61.1`:                               
  - rclone killed. unmount **failed**(100% reproduce). The disk info of mountpoint still shows all 0. But `diskutil unmountDisk force [mountpoint]` **works**
  - kill SIGHUP (rclone pid)   ====》 rclone killed. unmount **failed**

[1.16.1_rclone.log ](https://github.com/rclone/rclone/files/10297892/1.16.1_rclone.log)

**Comment by ncw** [comment]
There was only a single line in your log? I was hoping for a backtrace like last time??

**Comment by wxiaoguang** [comment]
This issue seems outdated, and I am not using rclone at the moment. So I think it's better to close this stale one.

**Comment by colincdean** [comment]
I observe `rclone mount` hanging if you ^C it or send a `SIGINT`, `SIGTERM`, etc. This happens for me every time on 4 different Macs running Monterey 12.7.2 (I'm connecting to OneDrive).

The `rclone` process is then no longer owned by the user who started it, becomes orphaned (PPID = 1) and `/sbin/launchd` refuses to let it die.  I'm using rclone 1.6.4 with macFUSE 4.5.0.  So I don't think the issue has gone away.

A reliable workaround for me, that works every time, is simply to run `umount [mountpoint]` as the user who mounted it.  This succeeds immediately, and causes `rclone` to terminate with a 1-line message:

`ERROR : [mountpoint]: Unmounted rclone mount`

and an exit status of 0.
