### ISSUE TITLE
SFTP Storage - Change in config parameters won't take affect until rclone is restarted

### ISSUE THREAD

**Issue by mchrisson** [rclone/rclone#4811]
#### What is the problem you are having with rclone?
**Usage:** I am using rclone to add SFTP storages (remotes) and upload, download, move files around in those storages via the rclone REST API.

**The Problem:** Change in parameters of the SFTP type storage config only take affect after rclone is restarted. Similarly if I delete a storage config, I am still able to access the files on that storage.

**Steps to Reproduce:**
1. Start rclone with `./rclone rcd --rc-user=test-user --rc-pass=test-pass --rc-web-gui --rc-addr=0.0.0.0:5572`
2. Access WebUI at `localhost:5572` and login
3. Go to Configs > Create a New Config
4. Enter Name (say 'Test-SFTP'), Select type as 'SSH/SFTP Connection'
5. Enter parameters, like ssh host, user, port, password
   ( say `{ "host": "192.168.100.9", "user": "test", "port: 22, "pass": "pass" }` )
   Click Next.
6. Config is created. Head to Explorer > Enter Storage Name 'Test-SFTP' > Hit Enter.
7. Able to see / access files on 192.168.100.9 .. Cool.
8. Head back to Configs > Click Update of 'Test-SFTP'.
9. Don't change type, click Next.
10. Change parameters,
   ( say `{ "host": "192.168.100.111", "user": "test1", "port: 22, "pass": "pass1" }` )
   Click Next.
11. Head back to Explorer. ( Or can even close web-browser and open a new incognito window, so that cache and local storage isn't used )
12. In Explorer, Enter Storage Name 'Test-SFTP' > Hit Enter.
13. Still able to see / access / download / upload files that are on 192.168.100.9. ☹

**Expectation:** Is that files on 192.168.100.111 should be accessible ( as the parameters are changed to point to this remote )

I could reproduce this scenario, with rclone running on a ubuntu system as well.
If rclone is restarted, then going to Explorer, I can see the actual files on 192.168.100.111.

I would not like to restart rclone to achieve this. Also, I use the rclone REST API to perform these operations in my NODE.js application. But this could also be reproducible using the rclone WebUI (as of course it also uses the REST API) 

Additionally, I watched the config file under `.config/rclone/rclone.conf`.
This seems to change immediately, on POST /config/update

#### What is your rclone version (output from `rclone version`)
rclone v1.54.0-beta.4920.979bb07c8
- os/arch: windows/amd64
- go version: go1.15.5

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 10, 64 bit

####  Which cloud storage system are you using? (e.g. Google Drive)
SSH/SFTP Connection

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
./rclone rcd --rc-user=test-user --rc-pass=test-pass --rc-web-gui --rc-addr=0.0.0.0:5572

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
$ ./rclone -vv rcd --rc-user=test-user --rc-pass=test-pass --rc-web-gui --rc-addr=0.0.0.0:5572
2020/11/26 23:46:19 DEBUG : rclone: Version "v1.54.0-beta.4920.979bb07c8" starting with parameters ["C:\\Users\\<user-name>\\Development\\programs\\rclone-beta\\rclone.exe" "-vv" "rcd" "--rc-user=test-user" "--rc-pass=test-pass" "--rc-web-gui" "--rc-addr=0.0.0.0:5572"]
2020/11/26 23:46:20 DEBUG : Current tag: v2.0.3, Release tag: v2.0.3
2020/11/26 23:46:20 NOTICE: Web GUI exists. Update skipped.
2020/11/26 23:46:20 NOTICE: Serving Web GUI
2020/11/26 23:46:20 INFO  : Using --user test-user --pass XXXX as authenticated user
2020/11/26 23:46:20 NOTICE: Serving remote control on http://[::]:5572/
2020/11/26 23:46:20 DEBUG : login_token "dGVzdC11c2VyOnRlc3QtcGFzcw=="

**Comment by ncw** [comment]
The created backends are cached for 5 minutes, so if you want for 5 minutes after the change it should be OK.

This isn't an ideal solution of course but can you check it works?

If it does then maybe what we need is a remote control command to clear the backend cache.

**Comment by mchrisson** [comment]
Good to know this. I also tried, and yes after 5mins the change is affected.

Would be nice to have a remote control command to clear the backend cache, But till then, Its fine with me to wait for 5mins.

Please fill free to close this as an "issue or bug". If ever this is decided to be a feature, I'll keep a watch to know.

Thanks and Cheers
Chris

**Comment by ncw** [comment]
> Good to know this. I also tried, and yes after 5mins the change is affected.

Great



> Would be nice to have a remote control command to clear the backend cache, But till then, Its fine with me to wait for 5mins.

I've had a go at this here with the `fscache/clear` rc command. (I also made an `fscache/entries` command so you can see how many items are in the cache).

Can you have a go with this?

[v1.54.0-beta.4934.c1022ff8b.fix-4811-cache-clear](https://beta.rclone.org/branch/fix-4811-cache-clear/v1.54.0-beta.4934.c1022ff8b.fix-4811-cache-clear/) on branch [fix-4811-cache-clear](https://github.com/rclone/rclone/tree/fix-4811-cache-clear) (uploaded in 15-30 mins)

It really needs to be integrated into the webui too. @negative0 ?

**Comment by negative0** [comment]
I'm looking into it.

**Comment by negative0** [comment]
Where would be the best place to place the button?

**Comment by mchrisson** [comment]
> > Good to know this. I also tried, and yes after 5mins the change is affected.
> 
> Great
> 
> > Would be nice to have a remote control command to clear the backend cache, But till then, Its fine with me to wait for 5mins.
> 
> I've had a go at this here with the `fscache/clear` rc command. (I also made an `fscache/entries` command so you can see how many items are in the cache).
> 
> Can you have a go with this?

@ncw This works well. Great.

> 
> [v1.54.0-beta.4934.c1022ff8b.fix-4811-cache-clear](https://beta.rclone.org/branch/fix-4811-cache-clear/v1.54.0-beta.4934.c1022ff8b.fix-4811-cache-clear/) on branch [fix-4811-cache-clear](https://github.com/rclone/rclone/tree/fix-4811-cache-clear) (uploaded in 15-30 mins)
> 
> It really needs to be integrated into the webui too. @negative0 ?

Just wondering if it should automatically invalidate a particular entry from the cache for which the config parameters changed.

**Comment by ncw** [comment]
> Where would be the best place to place the button?

Somewhere on the config creating page probably, however

> Just wondering if it should automatically invalidate a particular entry from the cache for which the config parameters changed. Or have mechanism to clear particular entries

Actually it occurs to me that rclone could be doing that automatically.

So if you alter a remote over the API then rclone could flush the backend cache of that item.

I had a go at this here - can you give it a test @mchrisson - if that works then we probably don't need the button @negative0 , though it might still be useful for advanced users.

[v1.54.0-beta.4947.6074a95b4.fix-4811-cache-clear](https://beta.rclone.org/branch/fix-4811-cache-clear/v1.54.0-beta.4947.6074a95b4.fix-4811-cache-clear/) on branch [fix-4811-cache-clear](https://github.com/rclone/rclone/tree/fix-4811-cache-clear) (uploaded in 15-30 mins)

**Comment by negative0** [comment]
Sounds like a plan. I think we should add it anyways.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.55
