### ISSUE TITLE
exclude-from file contains special char 'RIGHT SINGLE QUOTATION MARK'

### ISSUE THREAD

**Issue by charettemtb** [rclone/rclone#4812]
Hello, 

#### What is the problem you are having with rclone?
Error message when trying to use --exclude-from file that contains inside a line with one Unicode Character 'RIGHT SINGLE QUOTATION MARK'.
There is the specification of this character : https://www.fileformat.info/info/unicode/char/2019/index.htm

#### What is your rclone version (output from `rclone version`)
rclone v1.53.3
- os/arch: linux/amd64
- go version: go1.15.5

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Debian 10 64 bit

####  Which cloud storage system are you using? (e.g. Google Drive)
sftp

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone copy --config /home/toto/rclone.conf --exclude-from /home/toto/tohome.exclude --transfers=4 "server:/files/tohome" "/mnt/data"

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
2020/11/26 20:51:20 Failed to load filters: bad glob pattern "05 - L\\’Espérance\\.foo" (regexp "(^|/)05 - L\\’Espérance\\.foo$"): error parsing regexp: invalid escape sequence: `\’`

Thanks for your help !

**Comment by ncw** [comment]
Can you paste the `--exclude-from` file please? Or at least the line that causes the error.

It looks like you are escaping things with `\` - you don't need to do this in glob patterns - then aren't regular expressions.

**Comment by charettemtb** [comment]
You're right ! 
There is a sample file [tohome.exclude](https://github.com/rclone/rclone/files/5610549/tohome.txt)
With removing \ before special character there is no more problem.

I use `sed -e 's/.*\///' -e 's/[^a-zA-Z 0-9\-]/\\&/g'` to adapt the content of the file before executing rclone copy. I will work on it to remove \ escaping for this character.

Thanks

**Comment by ncw** [comment]
Great!

I'll close this now.
