### ISSUE TITLE
jottacloud: integration tests failing with read/write mime type

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#4817]
I recently put in a new integration test to make sure that when backends advertise that they can Read or Write MimeTypes that they actually can. See dfadd9896999813397cf7457c01ffcc789162a56

Most of the integration tests were easy to fix up, but Jottacloud is harder!

Jottacloud can apparently read MimeTypes but it isn't setting them. It is advertising them as settable though.

```
~/go/src/github.com/rclone/rclone/backend/jottacloud$ go test -v -run TestIntegration/FsMkdir/FsPutFiles/ObjectMimeType
=== RUN   TestIntegration
    fstests.go:396: Using remote "TestJottacloud:"
=== RUN   TestIntegration/FsMkdir
=== RUN   TestIntegration/FsMkdir/FsPutFiles
=== RUN   TestIntegration/FsMkdir/FsPutFiles/ObjectMimeType
    fstests.go:1303: 
        	Error Trace:	fstests.go:1303
        	Error:      	Not equal: 
        	            	expected: "text/csv"
        	            	actual  : "text/plain"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-text/csv
        	            	+text/plain
        	Test:       	TestIntegration/FsMkdir/FsPutFiles/ObjectMimeType
        	Messages:   	can read and write mime types but failed
--- FAIL: TestIntegration (5.18s)
    --- FAIL: TestIntegration/FsMkdir (4.55s)
        --- FAIL: TestIntegration/FsMkdir/FsPutFiles (3.01s)
            --- FAIL: TestIntegration/FsMkdir/FsPutFiles/ObjectMimeType (0.08s)
FAIL
exit status 1
FAIL	github.com/rclone/rclone/backend/jottacloud	5.184s
```

In `Update` it is never calling `fs.MimeType(src)` which is why the mime type never gets set.

To fix this we could either

1. Set `WriteMimeType` to `false` indicating the jottacloud backend can't set MimeTypes
2. Work out where to supply the MimeType/ContentType in `Update`.

@buengese and @albertony any ideas here?

**Comment by buengese** [comment]
If I remember it correctly writing mime type isn't actually supported. At least not when using allocate file request and a quick test seems to confirm this. So reporting ``WriteMimeType = true`` is just plain wrong here.

**Comment by ncw** [comment]
Thank you :-)
