### ISSUE TITLE
copy command rejects --min-age flag if --files-from is used 

### ISSUE THREAD

**Issue by zhucan** [rclone/rclone#4824]
#### What is the problem you are having with rclone?
why not use flags '--min-age' and '--files-from' in the same time with rclone copy?

#### What is your rclone version (output from `rclone version`)
v1.51.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
centos7.4

####  Which cloud storage system are you using? (e.g. Google Drive)
ceph rgw

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
./rclone copy src:/s3-acl-bucket-1 target:/s3-acl-bucket-4 --log-level DEBUG --log-file /var/log/xdrs/migration-mig1.log --files-from /tmp/x3ds --no-traverse  --min-age 0

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
![image](https://user-images.githubusercontent.com/13997135/100727719-971ffe00-3401-11eb-81e3-3c5610d6c618.png)

**Comment by ivandeex** [comment]
what's the use case?

**Comment by animosity22** [comment]
I would think that if you are using files-from, you are building a list of what files you want and further filtering the same list seems rather odd.

One would think you'd just use min-age when building the files-from so you aren't doing the same work again. I think files-from is an explicit list of what to move and adding filters on top of it makes it confusing.

**Comment by zhucan** [comment]
> what's the use case?

for example:
Storage backend source and target is s3, there are hundreds of millions of data in the source bucket, if we don't use flags "--files-from",  rclone needs to list all objects in source bucket, it will used many memory,  there will be big pressure on the server node. if we use "--files-from", only need to head object. we want to use '--min-age' to copy specify object.

**Comment by zhucan** [comment]
> I would think that if you are using files-from, you are building a list of what files you want and further filtering the same list seems rather odd.
> 
> One would think you'd just use min-age when building the files-from so you aren't doing the same work again. I think files-from is an explicit list of what to move and adding filters on top of it makes it confusing.

Thanks for your responses.

**Comment by ivandeex** [comment]
Resolved
@animosity22 
Thank you for prompt response
@zhucan 
I am going to close this ticket

**Comment by zhucan** [comment]
@ivandeex  I don't think we can close this ticket. Because of use 'files-from' can not store the object in the memory, we can reduce more memory,  it's import to all users; we use 'min-age' that we can do 'rclone move' to move special object. It's need to use 'files from' and 'min-age' at same time.
