### ISSUE TITLE
Dubox Cloud suport

### ISSUE THREAD

**Issue by amdaquino** [rclone/rclone#4828]
Is there any road map to suport Degoo and Dubox Cloud (https://www.dubox.com/) ?

**Comment by animosity22** [comment]
Majority of the time, they need published APIs and enough interest to warrant the effort.

A search for Degoo would lead you to this already opened feature request: 

https://github.com/rclone/rclone/issues/4424

Dubox doesn't seem to have an API from what I can find. If you see it or find it, please post a link to it.

**Comment by ivandeex** [comment]
Let's remove ticket duplication.
Feel free to thumbs up and comment on the Degoo feature request #4424

**Comment by ivandeex** [comment]
Dubox is a small provider without open API.
No plans to support it.
Closing.

**Comment by ivandeex** [comment]
Last but not least - not a single `+1` on this request for a year. No demand.

**Comment by ivandeex** [comment]
Last but not least - only one `+1` on this request since a year. No demand.
