### ISSUE TITLE
When the progress of copying files reaches 100%, the task will not stop, it will continue to copy

### ISSUE THREAD

**Issue by 5536086** [rclone/rclone#4829]
#### What is the problem you are having with rclone?
When the progress of copying files reaches 100%, the task will not stop, it will continue to copy

#### What is your rclone version (output from `rclone version`)
v1.53.3

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows10 1803 64bit

####  Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
Copy files from GD to my computer. rclone copy

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
![bug](https://user-images.githubusercontent.com/20472307/100816766-ca09d680-3481-11eb-94e1-6d8a8f1a315a.jpg)

**Comment by Masamune3210** [comment]
it's likely checking the files to make sure they uploaded correctly. when uploading to google drive, the file is uploaded, then the md5 is calculated for each to make sure they match to rule out any corrupted uploads

**Comment by 5536086** [comment]
I download the file from GD to my computer instead of uploading it to GD from my computer

**Comment by 5536086** [comment]
> it's likely checking the files to make sure they uploaded correctly. when uploading to google drive, the file is uploaded, then the md5 is calculated for each to make sure they match to rule out any corrupted uploads

I download the file from GD to my computer instead of uploading it to GD from my computer

**Comment by animosity22** [comment]
It still does the same thing as it validates the file.

If you follow the help and support template and post the logfile with -vv, you can see it on the output:

```
felix@gemini:~$ rclone copy GD:hosts hosts -vv
2020/12/01 22:27:29 DEBUG : rclone: Version "v1.53.3" starting with parameters ["rclone" "copy" "GD:hosts" "hosts" "-vv"]
2020/12/01 22:27:29 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2020/12/01 22:27:29 DEBUG : Creating backend with remote "GD:hosts"
2020/12/01 22:27:30 DEBUG : fs cache: adding new entry for parent of "GD:hosts", "GD:"
2020/12/01 22:27:30 DEBUG : Creating backend with remote "hosts"
2020/12/01 22:27:30 DEBUG : fs cache: renaming cache item "hosts" to be canonical "/home/felix/hosts"
2020/12/01 22:27:30 DEBUG : hosts: Need to transfer - File not found at Destination
2020/12/01 22:27:30 DEBUG : hosts: MD5 = 574584fa3f744ea629b956464b687c40 OK
2020/12/01 22:27:30 INFO  : hosts: Copied (new)
2020/12/01 22:27:30 INFO  :
Transferred:           221 / 221 Bytes, 100%, 852 Bytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         0.9s

2020/12/01 22:27:30 DEBUG : 5 go routines active
```

**Comment by 5536086** [comment]
> It still does the same thing as it validates the file.
> 
> If you follow the help and support template and post the logfile with -vv, you can see it on the output:
> 
> ```
> felix@gemini:~$ rclone copy GD:hosts hosts -vv
> 2020/12/01 22:27:29 DEBUG : rclone: Version "v1.53.3" starting with parameters ["rclone" "copy" "GD:hosts" "hosts" "-vv"]
> 2020/12/01 22:27:29 DEBUG : Using config file from "/opt/rclone/rclone.conf"
> 2020/12/01 22:27:29 DEBUG : Creating backend with remote "GD:hosts"
> 2020/12/01 22:27:30 DEBUG : fs cache: adding new entry for parent of "GD:hosts", "GD:"
> 2020/12/01 22:27:30 DEBUG : Creating backend with remote "hosts"
> 2020/12/01 22:27:30 DEBUG : fs cache: renaming cache item "hosts" to be canonical "/home/felix/hosts"
> 2020/12/01 22:27:30 DEBUG : hosts: Need to transfer - File not found at Destination
> 2020/12/01 22:27:30 DEBUG : hosts: MD5 = 574584fa3f744ea629b956464b687c40 OK
> 2020/12/01 22:27:30 INFO  : hosts: Copied (new)
> 2020/12/01 22:27:30 INFO  :
> Transferred:           221 / 221 Bytes, 100%, 852 Bytes/s, ETA 0s
> Transferred:            1 / 1, 100%
> Elapsed time:         0.9s
> 
> 2020/12/01 22:27:30 DEBUG : 5 go routines active
> ```

But I waited for a long time and it was not finished yet, so I forced it to stop. I don’t know if this will damage these files

**Comment by animosity22** [comment]
If you run the command with -vv, you can see what it is doing.

You have a lot of transfers going so it's going to take time and it depends on your hardware setup / hard drive speed /etc.

**Comment by Masamune3210** [comment]
If you want to know why it takes so long, pull up task manager and watch your hard drive being slammed as fast as it can.

**Comment by ivandeex** [comment]
Closing after 2+ months of inactivity.
Feel free to submit a thread if you still think it's a problem.  Prepare to attach your config and "-vv --log-file bug.log" data.
