### ISSUE TITLE
Prevent default credentials from being generated when using htpasswd

### ISSUE THREAD

**Issue by Addvilz** [rclone/rclone#4839]
#### What is your current rclone version (output from `rclone version`)?

1.53.3

#### What problem are you are trying to solve?

Trying to prevent default password from being generated and added when `htpasswd` option is used. Since htpasswd is present, there generally should be no need for credentials besides those in htpasswd.

#### How do you think rclone should be changed to solve that?

There should either be flag or the default should be changed to when `--rc-htpasswd` is provided, default user/pass should not be generated and output to stdout.

**Comment by ncw** [comment]
Can you give an example command line which demonstrates the problem? Thanks

**Comment by Addvilz** [comment]
For example,
`rclone rcd --rc-web-gui --rc-web-gui-no-open-browser --rc-addr :8443 --rc-htpasswd /etc/htpasswd --rc-cert XXX --rc-key XXX`

**Comment by ncw** [comment]
Ah I see.

It is the `--rc-web-gui` flag which is generating the password.

```
$ rclone rcd --rc-web-gui --rc-web-gui-no-open-browser
2020/12/07 11:54:04 ERROR : Error reading tag file at /home/ncw/.cache/rclone/webgui/tag 
2020/12/07 11:54:04 NOTICE: A new release for gui (v2.0.3) is present at https://github.com/rclone/rclone-webui-react/releases/download/v2.0.3/currentbuild.zip
2020/12/07 11:54:04 NOTICE: Downloading webgui binary. Please wait. [Size: 4750769, Path :  /home/ncw/.cache/rclone/webgui/v2.0.3.zip]
2020/12/07 11:54:07 NOTICE: Unzipping webgui binary
2020/12/07 11:54:07 NOTICE: Serving Web GUI
2020/12/07 11:54:07 NOTICE: Serving remote control on http://127.0.0.1:5572/
2020/12/07 11:54:07 NOTICE: Web GUI is not automatically opening browser. Navigate to http://gui:vL2WUclJ89upzeYRdQihKg@127.0.0.1:5572/?login_token=Z3VpOnZMMldVY2xKODl1cHplWVJkUWloS2c%3D to use.
```

So what we want is to not generate the password if a `htpassword` file has been supplied.

This would be quite a simple change if you want to have a go

These lines need to be run only `if opt.HTTPOptions.HtPasswd == ""`

https://github.com/rclone/rclone/blob/1efb8ea28062253f8fd99ceac7ddd83342bd6e5c/fs/rc/rcserver/rcserver.go#L96-L107

**Comment by Addvilz** [comment]
I suspect there might be also a change needed related to opening browser automatically, and printing the URL to CLI, last line of your log output. I suspect it will fail if randomPass is not set.

**Comment by ncw** [comment]
Possibly... @Addvilz - do you want to have a go at fixing?

**Comment by Addvilz** [comment]
I can give it a try - I will note here in the task when I start working on it. Unless there is something bellow stating otherwise, whoever might want this, consider it up for grabs.
