### ISSUE TITLE
update docs for support hashes for rclone hashum

### ISSUE THREAD

**Issue by asdffdsa6131** [rclone/rclone#4841]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.53.3
- os/arch: windows/amd64
- go version: go1.15.5

#### What problem are you are trying to solve?
the documentation needs to be update for the supported hashes for command `hashsum`
 https://rclone.org/commands/rclone_hashsum/#synopsis
from 
```
Supported hashes are:
  * MD5
  * SHA-1
  * DropboxHash
  * QuickXorHash
```
to match the output of `rclone hashsum` command

```
rclone hashsum
Supported hashes are:
  * MD5
  * SHA-1
  * Whirlpool
  * CRC-32
  * DropboxHash
  * MailruHash
  * QuickXorHash
```

#### How do you think rclone should be changed to solve that?
update the documenation
thanks

**Comment by edwardxml** [comment]
It would be great if there was a Pull Request done for this Commit. It is a clear documentation error outstanding at 1.54.

**Comment by ivandeex** [comment]
if #5071lands in a pr, it will be a good idea to use `sha1` instead of `SHA-1`, `dropbox` instead of `DropboxHash` and so on, as hash names.

asking for your opinion @ncw @edwardxml

**Comment by ivandeex** [comment]
PR for **this** ticket will land this March so will use current names

**Comment by ivandeex** [comment]
Actually I'm not in time for 1.55 so we are probably good to use short names from #5071 in rclone docs 🙏
