### ISSUE TITLE
VFS Upload Status/Percentage

### ISSUE THREAD

**Issue by dr-mcgillicuddy** [rclone/rclone#4844]
If rclone is closed, crashes, or is otherwise terminated there are occasionally files left in the VFS cache that have not yet been uploaded or updated on the remote.

It would be helpful to be able to add something like --stats or -P to the mount command which would show the number of files held in the VFS cache and the amount of uploading/syncing left to do as either a percentage, a number of MB or GB or simply number of files.  Something akin to the -P output of copy, sync, etc. would be one idea.

This would also be useful in the event one wanted to close rclone but was sure that all necessary operations had been completed in the VFS layer.

My current tactics are to either use bmon to get an idea of how much bandwidth is being used, and when it drops to zero, I assume rclone is done with all of its operations; or I simply leave my mounts on overnight and assume that is enough time that anything that needs to be completed will in fact be completed.  Or just mount with -v and periodically check to see if the scroll has stopped. None of those are ideal, or even foolproof, and feel a little kludge-y.

**Comment by darthShadow** [comment]
Something like this line is printed at every tick of the `--vfs-cache-poll-interval`:

```
<6>INFO  : vfs cache: cleaned: objects 137 (was 197) in use 0, to upload 0, uploading 0, total size 12.063G (was 12.482G)
```

Is that not sufficient? Any enhancements that you would like?

**Comment by ivandeex** [comment]
Closing stale answered questions
