### ISSUE TITLE
The README file in this repo has 2 bad links - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [rclone/rclone#4849]
#### What is the problem you are having with rclone?

The markup version of the readme that is displayed for the main page in this repo contains the following bad links:

Status code [404:NotFound] - Link: https://rclone.org/filefabric/
Status code [404:NotFound] - Link: https://rclone.org/compress/

#### What is your rclone version (output from `rclone version`)
N/A

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
N/A

####  Which cloud storage system are you using? (e.g. Google Drive)
N/A

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
N/A

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
N/A

####

Re-check this Repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2frclone%2frclone

--

Theses bad links were found by a tool I recently created as part of an new experimental hobby project: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
I (a human) verified that this link is broken and have manually logged this Issue (i.e. this Issue has not been created by a bot).
If this has been in any way helpful then please consider giving the above Repo a Star.

If you have any feedback on the information provided here, or on the tool itself, then please feel free to share your thoughts and pass on the feedback, or log an “Issue”.

**Comment by ivandeex** [comment]
It's expected. The content will be added by the next release.
