### ISSUE TITLE
Can't Mount A Cloud Storage on a device that doesn't have moddep file avaliable

### ISSUE THREAD

**Issue by BluelyTASer** [rclone/rclone#4850]
All methods of mounting as drive on linux is fuse based, it becomes unusable for people with devices without a moddep file available to download on internet, It's fixable by mounting as filesystem instead but it doesn't implemented on rclone yet.

![422](https://user-images.githubusercontent.com/59511669/101295844-cd44ef80-37fe-11eb-95c2-23ab3a37ac31.PNG)

### Log

```
2020/12/06 23:07:53 DEBUG : rclone: Version "v1.45" starting with parameters ["rclone" "mount" "ftg:" "/home/jovyan/work/fths73" "-vv"]
2020/12/06 23:07:53 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2020/12/06 23:07:53 DEBUG : Google drive root '': Mounting on "/home/jovyan/work/fths73"
2020/12/06 23:07:53 mount helper error: fusermount: fuse device not found, try 'modprobe fuse' first
2020/12/06 23:07:53 Fatal error: failed to mount FUSE fs: fusermount: exit status 1
```

**Comment by ivandeex** [comment]
Yes, `fuse` is prerequisite for `mount` (commands like `copy` or `ls` will still work).
