### ISSUE TITLE
s3: multipart upload for an object,  can not use 'md5' to compare the object?

### ISSUE THREAD

**Issue by zhucan** [rclone/rclone#4855]
@ncw @ivandeex If the object was uploaded with multipart, the md5 is not same.

**Comment by ncw** [comment]
Please provide a specific example - thanks!

**Comment by zhucan** [comment]
For example:
Backend storage: ceph rgw

we use the 'rclone copy' with flags '--check-sum' or use default flags, after we copy the object from an bucket to other bucket, we want to use 'rclone check' to judge the md5 is same, but if the object was uploaded multipart, the hash is none in dest object.  there is some print like this "--checksum is in use but the source and destination have no hashes in common; falling back to --size-only".  But we want to compare md5 to make sure the src object and dest object are same.

@ncw

**Comment by zhucan** [comment]
other issue:
rclone copy can not transfer soft link file? @ncw @ivandeex

**Comment by zhucan** [comment]
soft link file:
![image](https://user-images.githubusercontent.com/13997135/101733464-e51bbc80-3af9-11eb-9ae4-12fe7592553b.png)

logs :
![image](https://user-images.githubusercontent.com/13997135/101733574-0f6d7a00-3afa-11eb-8a84-c871858cd524.png)

**Comment by ncw** [comment]
> For example:
> Backend storage: ceph rgw
> 
> we use the 'rclone copy' with flags '--check-sum' or use default flags, after we copy the object from an bucket to other bucket, we want to use 'rclone check' to judge the md5 is same, but if the object was uploaded multipart, the hash is none in dest object.

Multipart uploads don't have MD5SUMs. If rclone uploaded the object it will add some metadata with the MD5SUM in it, but if it wasn't uploaded with rclone then it won't have an MD5SUM


> rclone copy can not transfer soft link file?

You either need `-l` to copy the link or `-L` to follow the link

**Comment by zhucan** [comment]
> You either need `-l` to copy the link or `-L` to follow the link

Is there examples?

**Comment by ivandeex** [comment]
Can not find `-l` in https://rclone.org/flags, https://rclone.org/docs/#options, https://rclone.org/commands/rclone_sync, https://rclone.org/commands/rclone_copy

**Comment by ivandeex** [comment]
> other issue:
> rclone copy can not transfer soft link file? @ncw @ivandeex

How is soft-linking connected to S3 multi-part hashing?

Concrete issues have more chances of being tracked, understood, discussed and eventually fixed. Do you want me to open an issue titled "Fix everything rclone that broke at stress-tests conducted by xsky.com personnel"?

**Comment by ivandeex** [comment]
BTW, forum.rclone.org is specifically dedicated to broad-topic free-form discussions...

**Comment by darthShadow** [comment]
> Can not find -l or -L in

Just FYI, in case you are not aware, these are present in the local backend page, because they are specific to that backend, I think.

https://rclone.org/local/#copy-links-l

https://rclone.org/local/#links-l-1

**Comment by ivandeex** [comment]
Also found explicit description of the question asked by this ticket

https://rclone.org/s3/#multipart-uploads

> rclone supports multipart uploads with S3 which means that it can upload files bigger than 5GB.
> Note that files uploaded both with multipart upload and through crypt remotes do **not have MD5** sums.

Sounds reasonable, as a checksum can be only calculated by sequential access to data, which is not the case for multi-stream upload. Leaves user with a tradeoff: either slower single-threaded upload with checksum or faster multi-part upload without it,

**Comment by ivandeex** [comment]
> Just FYI, in case you are not aware, these are present in the local backend page, because they are specific to that backend, I think.
> https://rclone.org/local/#copy-links-l
> https://rclone.org/local/#links-l-1

No, I wasn't. Thanks for info.

BTW, just found a fresh ticket #4604 requesting to copy a GDrive's _shortcut_ (I guess it's some link-alike object specific to them)

Seems like what requested here is officially unsupported.

**Comment by ncw** [comment]
I think we answered the question so I'll close this issue now.

The `-l` and `-L` are local backend flags. That issue #4604 is suggestive that `-L` at least should be a global flag and then it could be implemented for google drive shortcuts...
