### ISSUE TITLE
Support installing rclone into $HOME/bin when installing as not-root-user

### ISSUE THREAD

**Issue by robertbaker** [rclone/rclone#4857]
#### What problem are you are trying to solve?
Install rclone in $HOME/bin

#### How do you think rclone should be changed to solve that?
When running the install.sh script without sudo and not-root, it should install into $HOME/bin

**Comment by ncw** [comment]
Or maybe there should be a option for the install path?

**Comment by ivandeex** [comment]
Related to #3695

**Comment by ivandeex** [comment]
Proposal #2613 is a superset of this request.
