### ISSUE TITLE
[Feature request] yahoo provider

### ISSUE THREAD

**Issue by edortigoza** [rclone/rclone#4867]
yahoo mail provide 1 tera free
https://developer.yahoo.com/api/

**Comment by buengese** [comment]
The API page you linked does not mention any kind of cloud storage service nor am I aware of any such services existing. Are you sure it's not just 1 TB storage for mails? In that case that's not something rclone can use.

**Comment by williamchai** [comment]
here is the actual mail api https://developer.verizonmedia.com/mail/

**Comment by ivandeex** [comment]
@williamchai That is again **not** the **storage** API.

**Comment by williamchai** [comment]
@ivandeex That's correct I don't think Yahoo provide storage API

**Comment by ivandeex** [comment]
Closing because no storage api can be found
