### ISSUE TITLE
'rclone check' why not compare modtime?

### ISSUE THREAD

**Issue by zhucan** [rclone/rclone#4873]
#### What is the problem you are having with rclone?
why not compare modtime when doing 'rclone check'
?

#### What is your rclone version (output from `rclone version`)
v1.53.3

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
centos7.4

####  Which cloud storage system are you using? (e.g. Google Drive)
ceph rgw

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone check

**Comment by darthShadow** [comment]
Frankly, the forums are much better suited to discussions or questions about the rclone and it's functionality so please re-post your question there. We would like to keep the Github issue tracker limited to only verified bugs otherwise it will simply become too much for anyone to make sense of it.

**Comment by zhucan** [comment]
@darthShadow Thanks, I will close the issue and discuss on rclone forums.
