### ISSUE TITLE
When json log is turned on RCLONE_STATS_ONE_LINE is not outputted in json format

### ISSUE THREAD

**Issue by arkllc** [rclone/rclone#4881]
#### What is the problem you are having with rclone?
I am using environment variables to run rclone and using JSON as an outpout for log. When I specify RCLONE_STATS_ONE_LINE, I expected the stats to come up in json format. However, they come out as regular text. 

#### What is your rclone version (output from `rclone version`)
1.53

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Its a docker image that I am using as a container on top of Amazon Linux

####  Which cloud storage system are you using? (e.g. Google Drive)
AWS S3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone copy s3:one_bucket s3:another_bucket

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

Doing -v as is relevant in this case

68.980M / 899.272 MBytes, 8%, 151.999 MBytes/s, ETA 5s196.980M / 899.272 MBytes, 22%, 206.399 MBytes/s, ETA 3s302.980M / 899.272 MBytes, 34%, 209.189 MBytes/s, ETA 2s412.980M / 899.272 MBytes, 46%, 211.948 MBytes/s, ETA 2s533.668M / 899.272 MBytes, 59%, 217.913 MBytes/s, ETA 1s643.980M / 899.272 MBytes, 72%, 218.362 MBytes/s, ETA 1s747.355M / 899.272 MBytes, 83%, 216.490 MBytes/s, ETA 0s837.188M / 899.272 MBytes, 93%, 211.889 MBytes/s, ETA 0s{"level":"info","msg":"Copied (new)","object":"15APR13081815-P2AS_R08C4-055649178020_01_P001.TIF","objectType":"*s3.Object","source":"operations/operations.go:491","time":"2020-12-21T07:42:41.762842+00:00" }
{"level":"info","msg":"Copied (new)","object":"15APR13081815-P2AS_R10C4-055649178020_01_P001.TIF","objectType":"*s3.Object","source":"operations/operations.go:491","time":"2020-12-21T07:42:41.876682+00:00"}
887.095M / 899.272 MBytes, 99%, 199.421 MBytes/s, ETA 0s{"level":"info","msg":"Copied (new)","object":"15APR13081815-P2AS_R06C4-055649178020_01_P001.TIF","objectType":"*s3.Object","source":"operations/operations.go:491","time":"2020-12-21T07:42:42.01874+00:00"  }
{"level":"info","msg":"Copied (new)","object":"15APR13081815-P2AS_R09C4-055649178020_01_P001.TIF","objectType":"*s3.Object","source":"operations/operations.go:491","time":"2020-12-21T07:42:42.275083+00:00"  }
895.095M / 899.272 MBytes, 100%, 180.887 MBytes/s, ETA 0s{"level":"info","msg":"Copied (new)","object":"15APR13081815-P2AS_R07C4-055649178020_01_P001.TIF","objectType":"*s3.Object","source":"operations/operations.go:491","time":"2020-12-21T07:42:42.651774+00:00" }
899.272M / 899.272 MBytes, 100%, 175.209 MBytes/s, ETA 0s
{"level":"info","msg":"  899.272M / 899.272 MBytes, 100%, 175.209 MBytes/s, ETA 0s\n\n","source":"accounting/stats.go:353","stats":{"bytes":942955501,"checks":0,"deletes":0,"elapsedTime":5.458960526,"errors":0,"fatalError":false,"renames":0,"retryError":false,"speed":183719645.5974158,"transferTime":5.132578489,"transfers":5},"time":"2020-12-21T07:42:42.652065+00:00" }

**Comment by ncw** [comment]
Are you maybe using `--progress` or `-P` as well?

Can you write the full command line please? Including any flags you are setting by environment vars?

Thanks

**Comment by arkllc** [comment]
Yes, I am using the progress flag as I want to know the progress at a defined interval. The challenge is that the progress appears without any machine-readable JSON format even when I have mentioned to use JSON format. I hate to do parsing of space-separated generic strings and at least sometimes do not have newline characters too...

Here are the environment variables that I am using:

RCLONE_STATS=10s
RCLONE_PROGRESS=true
RCLONE_TRANSFERS=8
RCLONE_USE_MMAP=true

## could be 1 or 2
RCLONE_VERBOSE=2
RCLONE_STATS_ONE_LINE=true
RCLONE_DRY_RUN=true
RCLONE_CHECKERS=10
RCLONE_BUFFER_SIZE=10M
RCLONE_STATS_FILE_NAME_LENGTH=0
RCLONE_PROGRESS=true
RCLONE_USE_JSON_LOG=true

**Comment by ncw** [comment]
If you stop using progress I would have thought it would work properly.

`--progress` is for human readable output and is somewhat incompatible with `--use-json-log`.

Using `--stats 10s` as you do means that the JSON log will be printed every 10s which is I think what you want.

**Comment by arkllc** [comment]
@ncw Thanks for the clarification. It would be good to update the documentation stating the same.
