### ISSUE TITLE
[Bug] 'genautocomplete bash' fails if RCLONE_VERSION env var exists [1.53.3]

### ISSUE THREAD

**Issue by whereisaaron** [rclone/rclone#4888]
#### What is the problem you are having with rclone?

The 'genautocomplete bash' command fails if RCLONE_VERSION env var exists and is set to a version number, e.g. if RCLONE_VERSION=v1.53.3 then `rclone genautocomplete bash` will exit with:
```
2020/12/28 15:00:15 Invalid value for environment variable "RCLONE_VERSION": strconv.ParseBool: parsing "v1.53.3": invalid syntax
```

This comes up regularly when rclone is included in Dockerfile builds, as `RCLONE_VERSION` is the most obvious env var name. The workaround is simply to use a different env var name, e.g. `RCLONE_VERSION_X`

#### What is your rclone version (output from `rclone version`)

```
rclone v1.53.3
- os/arch: linux/amd64
- go version: go1.15.5
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Linux amd64

####  Which cloud storage system are you using? (e.g. Google Drive)

N/A

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone genautocomplete bash`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
$ rclone -vv genautocomplete bash
2020/12/28 13:16:05 DEBUG : rclone: Version "v1.53.3" starting with parameters ["rclone" "-vv" "genautocomplete" "bash"]
2020/12/28 13:16:05 open /etc/bash_completion.d/rclone: permission denied   <--- expected

$ export RCLONE_VERSION=v1.53.3

$ rclone -vv genautocomplete bash
2020/12/28 13:08:36 Invalid value for environment variable "RCLONE_VERSION": strconv.ParseBool: parsing "v1.53.3": invalid syntax
```

Notice it fails even before `-vv` lists the arguments, so this bug may affect other `rclone` subcommands also.

**Comment by whereisaaron** [comment]
I realize the `rclone` is trying to process `RCLONE_*` env vars as options. So the correct workaround is to use env var names like `INSTALL_RCLONE_VERSION`. And this behavior is by design, even if the error is cryptic!

**Comment by ncw** [comment]
Yes this is trying to parse `RCLONE_VERSION` to fill in the `--version` flag which is expecting a boolean value `true` or `false` (or some other values).

I improved the error message a bit to help in future.

        Invalid value for environment variable "RCLONE_VERSION" when setting default for --version: strconv.ParseBool: parsing "yes": invalid syntax

**Comment by ncw** [comment]
@lorengordon I think the error message is very clear now and not parsing config / env vars for `rclone help` would be a lot of work for not much gain I think.

**Comment by lorengordon** [comment]
Oh certainly, I wasn't intending to imply the message was unclear! It got me to this issue pretty quickly. It just feels very weird, as a  user, for the `version` command to process config or envs, and leads to unexpected behavior like we're seeing here.

Totally get that the lift may not be worth it, but it did seem at least worth asking the question, as I do not know that much about the code base. In my mind, I could easily see how it would be a trivial change that just noone had yet considered! Or not, as you seem to be indicating. Would never know which it was if I didn't ask!
