### ISSUE TITLE
Rclone not delete orphan segments. 

### ISSUE THREAD

**Issue by nguyenhuuluan434** [rclone/rclone#4889]
#### What is the problem you are having with rclone?
When i umount the mount point with the command 'fusermount -u /65d4e907c8c248b099d2f63a070a41b9' during the rclone sync/upload data to remote (in this case is Openstack Swift).The error occurred when the object/file is large object (the object what has size greater than 'chunk_size'). The upload process is not clean the segments what was uploaded.

Example:
I has a file with size 100M and set up chunk_size = 20M and assume segment 1 and segment 2 upload successful and then upload segment 3 but the command umount is executed. The rclone stop process and segment 1 and segment 2 still on remote backend. In the next mount, the rclone check the file is dirty and upload process is started again.

Could we trigger delete the segments what was upload successful but it is not use any where ?
Another proposal is waiting finish the upload of the file.

#### What is your rclone version (output from `rclone version`)
rclone v1.54.0-DEV
- os/arch: linux/amd64
- go version: go1.15.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Linux LuanNH 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

####  Which cloud storage system are you using? (e.g. Google Drive)
Openstack Swift

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone mount test1-swift:container /65d4e907c8c248b099d2f63a070a41b9 --vfs-cache-mode full --vfs-cache-max-size=10000000B --debug-fuse --allow-other --file-perms 0644 --config=/home/luannh/.config/rclone/test1 --vfs-read-chunk-size=200M --umask=002 --cache-writes --vfs-cache-max-age=10s --log-file=/tmp/log --log-level=DEBUG --dir-cache-time=10s --vfs-cache-poll-interval=5s

**Comment by ncw** [comment]
I just merged a potential fix for this in 6342499c472752c3837e557f76d40a5d7f6620cf so can you try [the latest beta](https://beta.rclone.org) please?

**Comment by ivandeex** [comment]
Related to #4075

**Comment by nguyenhuuluan434** [comment]
Hi @ncw @ivandeex ,
After reading source implement for s3, I see the package atexit what we can apply to handle this case. I am rewriting for swift and commit soon. @ncw please help me review.

Thanks.

**Comment by nguyenhuuluan434** [comment]
Hi @ncw @ivandeex ,
This is my PR with detail in [link] (https://github.com/rclone/rclone/pull/4893)

Thanks,
Luan
