### ISSUE TITLE
How to solve this error: "corrupted on transfer: sizes differ 2871808 vs 2883072"

### ISSUE THREAD

**Issue by 5536086** [rclone/rclone#4890]
#### What is the problem you are having with rclone?
How to solve this error: "**corrupted on transfer: sizes differ 2871808 vs 2883072**"

#### What is your rclone version (output from `rclone version`)
rclone v1.53.3

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
- os/arch: windows/amd64
- go version: go1.15.5

####  Which cloud storage system are you using? (e.g. Google Drive)
Transfer files from gd to sharepoint

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone copy

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
![QQ截图20201228215901](https://user-images.githubusercontent.com/20472307/103219203-0254e580-4958-11eb-98c6-8ad92bb3365d.jpg)

**Comment by ncw** [comment]
I think this is sharepoint re-writing the sizes of `.doc` files which confuses rclone.

I think you can work around this with `--ignore-size`. This isn't a great solution, alas.

**Comment by ivandeex** [comment]
Closing this as the question has been answered.
