### ISSUE TITLE
rclone about remote: not showing Google Drive usage limit (quota)

### ISSUE THREAD

**Issue by hexindent** [rclone/rclone#4894]
#### What is the problem you are having with rclone?

`rclone about remote:` not showing Google Drive usage limit (quota) although the doc says so:  https://rclone.org/drive/#quota-information

#### What is your rclone version (output from `rclone version`)

rclone v1.53.3
- os/arch: darwin/amd64
- go version: go1.15.5

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

macOS Mojave 10.14.6

####  Which cloud storage system are you using? (e.g. Google Drive)

Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone about gdrive:`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
rclone -vv about gdrive:
DEBUG : rclone: Version "v1.53.3" starting with parameters ["rclone" "-vv" "about" "gdrive:"]
DEBUG : Using config file from "/Users/username/.config/rclone/rclone.conf"
DEBUG : Creating backend with remote "gdrive:"
Used:    i T
Trashed: j G
Other:   0
DEBUG : 6 go routines active
```

**Comment by hexindent** [comment]
On second thought I think I might be misunderstanding "quota". If it's not the daily 750 GiB thing, please close this issue. If it is, we still have an issue here.

**Comment by ncw** [comment]
`rclone about` measures the disk usage rather than anything else. The upload quota 750GB isn't queriable as far as I know.

Since you are on an unlimited plan you don't get a `Free` space line as it is infinite.

**Comment by hexindent** [comment]
Thank you, @ncw for the explanation! I'm closing the issue now.
