### ISSUE TITLE
zsh autocomplete : rclone config "command not found: name"

### ISSUE THREAD

**Issue by tchernomax** [rclone/rclone#4905]
```rclone genautocomplete zsh```
generate:
```
…
    commands=(
      "create:Create a new remote with name, type and options."
      "delete:Delete an existing remote `name`."
      "disconnect:Disconnects user from remote"
…
```
With the backticks around `` `name` `` and the fact the string are double-quoted (instead of single-quoted) the shell try to execute `name` and fail.

I think the simpler is to remove the backticks from the description:
https://github.com/rclone/rclone/blob/dd67a3d5f5bb67af7a54728cedbba0448a0061d3/cmd/config/config.go#L195

(it may be a spf13/cobra bug)

**Comment by ncw** [comment]
I can't replicate this with [the latest beta](https://beta.rclone.org) - can you give that a go?

I wonder if the zsh completion is broken in the beta :-(

**Comment by tchernomax** [comment]
Yes indeed, I can't replicate this in beta.
The problem seems fixed.
I am closing this issue.
Thanks.
