### ISSUE TITLE
Forcing pauses between files for FTP transfers

### ISSUE THREAD

**Issue by MadKernel** [rclone/rclone#4906]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.53.3
- os/arch: linux/arm64
- go version: go1.15.5

rclone v1.53.3
- os/arch: linux/amd64
- go version: go1.15.5

#### What problem are you are trying to solve?
Attempting to backup remote FTP sites to local folders sometimes fails with connections being refused by the remote FTP server. As the error occurs randomly in each pass this renders the backup totally unreliable as there is no way to know if a site has been completely copied or not.

#### How do you think rclone should be changed to solve that?
Hi!
I believe having a switch to force a delay between files could make the process less "aggressive" against the remote ftp server and prevent the issue from happening.
As suggested in the forum enabling the "--tpslimit " for FTP connections could be the way to go.

Thread;
[https://forum.rclone.org/t/forcing-pauses-between-files/](url)

Pastebin reference log
[https://pastebin.com/HhnTZMdC](url)

Please note that while this log does end with success at the third attempt other remote FTPs with larger amounts of small files are always failing for me regardless of any passes, checkers and transfers combinations I try. 

Thank you for rclone and any extra time you put into this issue!

**Comment by ncw** [comment]
Thanks for making the issue.

I've made --tpslimit apply to the FTP (and SFTP) backends here. I think this should solve your problem - can you give it a go?

[v1.54.0-beta.5038.0e54f750b.fix-4906-tpslimit](https://beta.rclone.org/branch/fix-4906-tpslimit/v1.54.0-beta.5038.0e54f750b.fix-4906-tpslimit/) on branch [fix-4906-tpslimit](https://github.com/rclone/rclone/tree/fix-4906-tpslimit) (uploaded in 15-30 mins)

Thanks

**Comment by MadKernel** [comment]
Hi, ok, out of the ten o so FTP remotes I am backing up two of them where presenting this issue. These two have different public IPs but are on the same provider (unlike the others, which were responding fine to begin with).

One of the "problematic" remotes seems to be responding better now. Using "--tpslimit 1 --transfers 4 --checkers 2" it seems the backup runs without errors.

But the other one is still failing with the same random connection errors:
`error reading source directory: dial tcp XXX.XX.XXX.XX:50000: connect: connection refused`

I am guessing this might exacerbated for the amount of files in this account, although I am also pretty sure that is not the main cause, as the errors start around the first minute, even before 1000 files are processed. i.e.;
```
Errors:                 1 (retrying may help)
Checks:               593 / 593, 100%
Elapsed time:       1m2.4s
```
I have tried combinations ranging from "--tpslimit 3 --transfers 4 --checkers 2" to "--tpslimit 1 --transfers 1 --checkers 1" (which o.c. took forever...) yet this remote is not playing nice, although the other one apparently is (I will run a couple more syncs to double check).

**Comment by MadKernel** [comment]
@ncw , given some time perhaps I could provide you some credentials to this remote, if you consider it worthwhile...

**Comment by ncw** [comment]
I'm glad --tpslimit is helping. I'll merge that code in a moment.

What you should try next is limiting the number of connections rclone makes using

      --ftp-concurrency int               Maximum number of FTP simultaneous connections, 0 for unlimited

Or the `concurrency` parameter in the config.

FTP servers hate too much concurrency. You may need to reduce `--transfers` and `--checkers` down.  So if you want to start from the lowest setting, try `--transfers 1` and `--checkers 1` and `--ftp-concurrency 3`. If you set concurrency too low then rclone will deadlock, but you can try `2`.

You can also use `--check-first` to make sure rclone does the directory listing before doing any transfers which can help.
