### ISSUE TITLE
下载文件时，服务崩溃--access vpsGoogleDrive: Transport endpoint is not connected

### ISSUE THREAD

**Issue by zhenfeii** [rclone/rclone#4907]
挂载Google drive，多线程下载后服务崩溃。
ssh进入服务器，cd /vpsGoogleDrive,提示Transport endpoint is not connected。

该情况， 重新挂载也会出险。

**Comment by ncw** [comment]
> The service crashed when downloading files--access vpsGoogleDrive: Transport endpoint is not connected
> 
> After mounting Google drive, the service crashed after multi-threaded download. SSH into the server, cd /vpsGoogleDrive, prompt Transport endpoint is not connected. In this case, remounting will also cause danger.

Can you provide a log with the `-vv` flag please?
