### ISSUE TITLE
能否关闭缓存

### ISSUE THREAD

**Issue by zhenfeii** [rclone/rclone#4908]
我从网上下载一个9g 的大文件到挂载磁盘。
发现会先下到缓存目录./root/.cache/rclone/vfs/，这会大大占用我的磁盘空间。能否关闭缓存？
![image](https://user-images.githubusercontent.com/30223168/103750144-512e0980-5041-11eb-9bc5-ba33b2ba91d7.png)

**Comment by ncw** [comment]
With a bit of google translate

> Can the cache be turned off
>
> I downloaded a large 9g file from the Internet to the mount disk. I found that I would first go to the cache directory ./root/.cache/rclone/vfs/, which would greatly take up my disk space. Can the cache be turned off?

I think you are using `--vfs-cache-mode writes` or `--vfs-cache-mode full`. You can stop using those, or you can set `--vfs-cache-max-size` or `--vfs-cache-max-age` to make the cache smaller.

I hope that helps.

**Comment by ivandeex** [comment]
closing as the question has been answered
