### ISSUE TITLE
May i know when v1.53.4 will be released?

### ISSUE THREAD

**Issue by wangshuang0220** [rclone/rclone#4910]
May i know when v1.53.4 will be released?

**Comment by ncw** [comment]
I was planning for v1.54.0 to be the next release before the end of January.

Was there something in particular you wanted?

**Comment by ivandeex** [comment]
@ncw Please set due date on the 1.54 milestone.

**Comment by wangshuang0220** [comment]
@ncw  I want to try compression function, is there any sample? thanks~

**Comment by ivandeex** [comment]
@wangshuang0220 get latest executable from https://beta.rclone.org

**Comment by ncw** [comment]
I set the provisional release date for 1.54 at the end of Jan 2021.

I might move it forwards or delay it ;-)

I'll close this now as I think it is answered.
