### ISSUE TITLE
rcd: memory leak?

### ISSUE THREAD

**Issue by brxie** [rclone/rclone#4911]
#### What is the problem you are having with rclone?
Hello, I'm using Rclone for the automatization job as a core engine for transferring files from S3 backend to the filesystem.
I'm observing pretty high memory consumption and "cannot allocate memory" errors that appear when transferring 100..150GB files from S3 backend to the local filesystem.

To trigger transfer I'm using rcd endpoint HTTP POST /sync/copy.

I read on the Rclone forum the expected memory usage can be calculated like `transfers * buffer-size`.
But in my case `--transfers` is set to 10 and buffer-size is the default 16MB and I'm observing memory usage up to 3Gi.
Please have a look at bellow graph showing memory usage of rclone container:

![v1 50 2_3Gi](https://user-images.githubusercontent.com/10535420/103909297-d2e66b80-5103-11eb-9a52-fabedefe9850.jpg)

Is this expected memory consumption for Rclone or is it a memory leak?

#### What is your rclone version (output from `rclone version`)
`v1.50.2` and latest beta `v1.54.0-beta.5029.add7a35e5`

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
docker container `rclone/rclone:beta`

####  Which cloud storage system are you using? (e.g. Google Drive)
S3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone -vv rcd --progress --rc-no-auth --rc-addr=:5572 --low-level-retries 10 --no-gzip-encoding --ignore-checksum --transfers 10 --bwlimit 100M`

**Comment by ncw** [comment]
How much memory rclone uses depends on what exactly you are doing with it over the rc? How many transfers are you running simultaneously?

Can you try running the memory profiling here: https://rclone.org/rc/#debugging-memory-use - that will tell us exactly what is using the memory.

**Comment by brxie** [comment]
Hello. Thanks for the reply.

> How much memory rclone uses depends on what exactly you are doing with it over the rc

Until I didn't start the job rc is consuming just about 20MiB of memory and it's stable. I left rc in this state for a few hours and the memory has not grown within this time at all.

> How many transfers are you running simultaneously?

Just a single transfer. I'm just executing a single `HTTP POST /sync/copy` request and then memory is consumed as on the attached graph.

---
> Can you try running the memory profiling here

Here it is from 17:14 where memory usage was about 1.55GiB

```
Fetching profile over HTTP from http://rclone-test-pvc:5572/debug/pprof/heap
Saved profile in /root/pprof/pprof.rclone.alloc_objects.alloc_space.inuse_objects.inuse_space.021.pb.gz
File: rclone
Type: inuse_space
Time: Jan 8, 2021 at 4:14pm (UTC)
Showing nodes accounting for 1026.05kB, 100% of 1026.05kB total
      flat  flat%   sum%        cum   cum%
     514kB 50.10% 50.10%      514kB 50.10%  bufio.NewReaderSize
  512.05kB 49.90%   100%   512.05kB 49.90%  net/http.(*persistConn).roundTrip
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/backend/s3.(*Object).Open
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/backend/s3.(*Object).Open.func1
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/fs.pacerInvoker
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/fs/fshttp.(*Transport).RoundTrip
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/fs/operations.(*multiThreadCopyState).copyStream
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/fs/operations.(*reOpen).open
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/fs/operations.multiThreadCopy.func1
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/fs/operations.newReOpen
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/lib/pacer.(*Pacer).Call
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/lib/pacer.(*Pacer).call
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/corehandlers.glob..func3
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/corehandlers.sendFollowRedirects
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/request.(*HandlerList).Run
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).Send
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/aws/request.(*Request).sendRequest
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/vendor/github.com/aws/aws-sdk-go/service/s3.(*S3).GetObjectWithContext
         0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1
         0     0%   100%   512.05kB 49.90%  net/http.(*Client).Do
         0     0%   100%   512.05kB 49.90%  net/http.(*Client).do
         0     0%   100%   512.05kB 49.90%  net/http.(*Client).send
         0     0%   100%   512.05kB 49.90%  net/http.(*Transport).RoundTrip
         0     0%   100%      514kB 50.10%  net/http.(*Transport).dialConn
         0     0%   100%      514kB 50.10%  net/http.(*Transport).dialConnFor
         0     0%   100%   512.05kB 49.90%  net/http.(*Transport).roundTrip
         0     0%   100%   512.05kB 49.90%  net/http.send
```

The number of goroutines was 149 and it was stable.

Here is the timeline of the executed job:

**17:03** - transfer operation start and got jobid 1
**17:07..17:24** - transfer is in progress and memory looks like leaking. From previous tests, I know it will be growing even up to 3GiB.
**17:24** - I've interrupted job to see what will happen with memory. Executed `HTTP POST /job/stop -d '{"jobid": "1"}'`, and to be honest I thought memory will be dumped. But it wasn't' so. One thing I observed is that rclone stopped eating more bytes of memory. I left rc in this state for almost 1h and memory usage keeps stable.


![Screenshot from 2021-01-08 17-29-45](https://user-images.githubusercontent.com/10535420/104043723-84f16680-51dc-11eb-8ae4-cdbaebe7b913.png)
![ml2](https://user-images.githubusercontent.com/10535420/104043755-8e7ace80-51dc-11eb-9654-95d700624cba.png)

**Comment by brxie** [comment]
update: memory dumped at **18:12** so almost one hour after interrupting it

![image](https://user-images.githubusercontent.com/10535420/104044847-0269a680-51de-11eb-88e2-e84c1f485c19.png)

**Comment by ncw** [comment]
> > How much memory rclone uses depends on what exactly you are doing with it over the rc
> 
> Until I didn't start the job rc is consuming just about 20MiB of memory and it's stable. I left rc in this state for a few hours and the memory has not grown within this time at all.

OK that is a good start!

> > How many transfers are you running simultaneously?
> 
> Just a single transfer. I'm just executing a single `HTTP POST /sync/copy` request and then memory is consumed as on the attached graph.

OK.

Can you tell me the source and destination remotes and how many files you are copying?

> > Can you try running the memory profiling here
> 
> Here it is from 17:14 where memory usage was about 1.55GiB
> 
> ```
> Fetching profile over HTTP from http://rclone-test-pvc:5572/debug/pprof/heap
> Saved profile in /root/pprof/pprof.rclone.alloc_objects.alloc_space.inuse_objects.inuse_space.021.pb.gz
> File: rclone
> Type: inuse_space
> Time: Jan 8, 2021 at 4:14pm (UTC)
> Showing nodes accounting for 1026.05kB, 100% of 1026.05kB total
>       flat  flat%   sum%        cum   cum%
>      514kB 50.10% 50.10%      514kB 50.10%  bufio.NewReaderSize
>   512.05kB 49.90%   100%   512.05kB 49.90%  net/http.(*persistConn).roundTrip
>          0     0%   100%   512.05kB 49.90%  github.com/rclone/rclone/backend/s3.(*Object).Open
> ```

That profile is saying there is 1M of memory in use....

So that 1.55G is mostly space that rclone allocated and then released.

> The number of goroutines was 149 and it was stable.

That seems like quite a lot of goroutines open when idle.

> Here is the timeline of the executed job:
> 
> **17:03** - executed HTTP POST /sync/copy and transfer operation started, got jobid 1
> **17:07..17:24** - transfer is in progress and memory looks like leaking. From previous tests, I know it will be growing even up to 3GiB.
> **17:24** - I've interrupted job to see what will happen with memory. Executed `HTTP POST /job/stop -d '{"jobid": "1"}'`, and to be honest I thought memory will be dumped. But it wasn't' so. One thing I observed is that rclone stopped eating more bytes of memory.

I think you'll need to dump the memory while the transfer is running so we can see what is using the memory.

From the evidence so far it sounds like the memory isn't leaked, but rclone is using 1.5G at some point and not giving unused memory back to the OS.

The go runtime should return the memory to the OS eventually if it can. It might be that it is very fragmented for some reason.

You might also try both of these flags which help with returning memory to the OS

      --use-mmap   Use mmap allocator (see docs).
      --s3-memory-pool-use-mmap   Whether to use mmap buffers in internal memory pool.

The latter help in particular will help with uploading big files to S3.

> I read on the Rclone forum the expected memory usage can be calculated like `transfers * buffer-size`.
> But in my case `--transfers` is set to 10 and buffer-size is the default 16MB and I'm observing memory usage up to 3Gi.

Note that for large file S3 uploads it buffers the file in memory so in addition to that they will use

`--s3-chunk-size` * `--s3-concurrency` * `--transfers`

Note also that there can be a max of 10,000 chunks per file so `--s3-chunk-size` will be increased to 15MB when uploading a 150GB file.

Can you show your s3 remote config (without secrets!) please?

**Comment by brxie** [comment]
I'm sorry for the late update. Testing it took pretty much time.

I tried with setting the `--use-mmap` and `--s3-memory-pool-use-mmap` flags (both at the same time) and I didn't see the difference - again I reached 3GiB of memory.

Now I'm going to check with manipulating s3 parameters like `--s3-chunk-size` and `--s3-concurrency`.
I found useful information here and based on this I will try to reduce memory consumption without serious performance impact https://github.com/rclone/rclone/blob/master/docs/content/s3.md

> Can you show your s3 remote config (without secrets!) please?

My config is pretty default

```
[SRC]
type = s3
endpoint = http://x.x.x.x
env_auth = false
provider = ceph
secret_access_key = *******************************
access_key_id = ************

[DST]
type = local
```

**Comment by ncw** [comment]
Let me know what happens :-)

**Comment by brxie** [comment]
I tried to reduce memory usage in many ways but with no luck. Nothing works and memory always grows up to 3G.

I tried everything except `--s3-concurrency` setting because there is no such flag. I guess you meant `--s3-upload-concurrency` but I'm using S3 backend as a source so in my case changing it doesn't make sense.

Last test with following configuration `rclone -vv rcd --progress --rc-no-auth --rc-addr=:5572 --low-level-retries 10 --no-gzip-encoding --ignore-checksum --transfers 1 --bwlimit 100M --s3-chunk-size 10000`

gave me results:

![Screenshot from 2021-01-15 16-39-09](https://user-images.githubusercontent.com/10535420/104747889-5847cc80-5751-11eb-8ec7-e60ac8590a4a.png)

The only difference is that memory is growing much slower, but the transfer speed is slower too.

Is this behavior expected?
If so, is there any reliable way to calculate the expected maximal memory usage of the rcd process?

**Comment by ncw** [comment]
> I tried with setting the `--use-mmap` and `--s3-memory-pool-use-mmap` flags (both at the same time) and I didn't see the difference - again I reached 3GiB of memory.

:-(

Can you do another memory profile when it has reached 3GB to see if it looks different?

> Is all this behavior expected?

No, not really.

A memory profile at 3G would help a lot.

The other thing you could try is telling the Go garbage collector to work harder by setting the environment variable `GOGC=10` and see if that helps.

**Comment by ivandeex** [comment]
@brxie do you still work on this?

**Comment by brxie** [comment]
As a workaround, I used more memory and didn't solve the root cause issue.
For now, I'm closing this ticket and will update once I will back to this topic.
