### ISSUE TITLE
Failed to copyto: corrupted on transfer: MD5 hash differ (automatic compression enabled)

### ISSUE THREAD

**Issue by jmargallo** [rclone/rclone#4912]
#### What is the problem you are having with rclone?

When copying a '.txt' or '.log' file to MinIO I get the error:
Failed to copyto: corrupted on transfer: MD5 hash differ "aaaaaaaaaaaaaa" vs "bbbbbbbbbbbbb"
This happens when automatic compression is activated, if I deactivate automatic compression, this error does not appear.

#### What is your rclone version (output from `rclone version`)

[root@****** ~]# rclone --version
rclone v1.47.0
- os/arch: linux/amd64
- go version: go1.11.5

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

CentOS Linux release 7.7.1908 (Core)

####  Which cloud storage system are you using? (e.g. Google Drive)

Minio

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone --config=/etc/rclone.conf copyto test.txt dest:destpath/test.txt

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

[root@****** tmp]# rclone --log-level DEBUG --config=/etc/rclone.conf copyto test.txt dest:destpath/test.txt
2021/01/07 18:02:54 DEBUG : rclone: Version "v1.47.0" starting with parameters ["rclone" "--log-level" "DEBUG" "--config=/etc/rclone.conf" "copyto" "test.txt" "dest:destpath/test.txt"]
2021/01/07 18:02:54 DEBUG : Using config file from "/etc/rclone.conf"
2021/01/07 18:02:54 DEBUG : test.txt: Couldn't find file - need to transfer
2021/01/07 18:02:54 ERROR : test.txt: corrupted on transfer: MD5 hash differ "3f8a62a7db3b276342d4c65dba2a5adf" vs "f3322e544bed83740514b5320f37452d"
2021/01/07 18:02:54 INFO  : test.txt: Removing failed copy
2021/01/07 18:02:54 ERROR : Attempt 1/3 failed with 2 errors and: corrupted on transfer: MD5 hash differ "3f8a62a7db3b276342d4c65dba2a5adf" vs "f3322e544bed83740514b5320f37452d"
2021/01/07 18:02:54 DEBUG : test.txt: Couldn't find file - need to transfer
2021/01/07 18:02:54 ERROR : test.txt: corrupted on transfer: MD5 hash differ "3f8a62a7db3b276342d4c65dba2a5adf" vs "f3322e544bed83740514b5320f37452d"
2021/01/07 18:02:54 INFO  : test.txt: Removing failed copy
2021/01/07 18:02:54 ERROR : Attempt 2/3 failed with 2 errors and: corrupted on transfer: MD5 hash differ "3f8a62a7db3b276342d4c65dba2a5adf" vs "f3322e544bed83740514b5320f37452d"
2021/01/07 18:02:54 DEBUG : test.txt: Couldn't find file - need to transfer
2021/01/07 18:02:54 ERROR : test.txt: corrupted on transfer: MD5 hash differ "3f8a62a7db3b276342d4c65dba2a5adf" vs "f3322e544bed83740514b5320f37452d"
2021/01/07 18:02:54 INFO  : test.txt: Removing failed copy
2021/01/07 18:02:54 ERROR : Attempt 3/3 failed with 2 errors and: corrupted on transfer: MD5 hash differ "3f8a62a7db3b276342d4c65dba2a5adf" vs "f3322e544bed83740514b5320f37452d"
2021/01/07 18:02:54 Failed to copyto: corrupted on transfer: MD5 hash differ "3f8a62a7db3b276342d4c65dba2a5adf" vs "f3322e544bed83740514b5320f37452d"

**Comment by ncw** [comment]
> #### What is the problem you are having with rclone?
> When copying a '.txt' or '.log' file to MinIO I get the error:
> Failed to copyto: corrupted on transfer: MD5 hash differ "aaaaaaaaaaaaaa" vs "bbbbbbbbbbbbb"
> This happens when automatic compression is activated, if I deactivate automatic compression, this error does not appear.
> 
> #### What is your rclone version (output from `rclone version`)
> [root@****** ~]# rclone --version
> rclone v1.47.0
> 
> * os/arch: linux/amd64
> * go version: go1.11.5
> 
> #### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
> CentOS Linux release 7.7.1908 (Core)
> 
> #### Which cloud storage system are you using? (e.g. Google Drive)
> Minio
> 
> #### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
> rclone --config=/etc/rclone.conf copyto test.txt dest:destpath/test.txt
> 
> #### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
> [root@****** tmp]# rclone --log-level DEBUG --config=/etc/rclone.conf copyto test.txt dest:destpath/test.txt
> 2021/01/07 18:02:54 DEBUG : rclone: Version "v1.47.0" starting with parameters ["rclone" "--log-level" "DEBUG" "--config=/etc/rclone.conf" "copyto" "test.txt" "dest:destpath/test.txt"]
> 2021/01/07 18:02:54 DEBUG : Using config file from "/etc/rclone.conf"
> 2021/01/07 18:02:54 DEBUG : test.txt: Couldn't find file - need to transfer
> 2021/01/07 18:02:54 ERROR : test.txt: corrupted on transfer: MD5 hash differ "3f8a62a7db3b276342d4c65dba2a5adf" vs "f3322e544bed83740514b5320f37452d"
> 2021/01/07 18:02:54 INFO : test.txt: Removing failed copy
> 2021/01/07 18:02:54 ERROR : Attempt 1/3 failed with 2 errors and: corrupted on transfer: MD5 hash differ "3f8a62a7db3b276342d4c65dba2a5adf" vs "f3322e544bed83740514b5320f37452d"
> 2021/01/07 18:02:54 DEBUG : test.txt: Couldn't find file - need to transfer
> 2021/01/07 18:02:54 ERROR : test.txt: corrupted on transfer: MD5 hash differ "3f8a62a7db3b276342d4c65dba2a5adf" vs "f3322e544bed83740514b5320f37452d"
> 2021/01/07 18:02:54 INFO : test.txt: Removing failed copy
> 2021/01/07 18:02:54 ERROR : Attempt 2/3 failed with 2 errors and: corrupted on transfer: MD5 hash differ "3f8a62a7db3b276342d4c65dba2a5adf" vs "f3322e544bed83740514b5320f37452d"
> 2021/01/07 18:02:54 DEBUG : test.txt: Couldn't find file - need to transfer
> 2021/01/07 18:02:54 ERROR : test.txt: corrupted on transfer: MD5 hash differ "3f8a62a7db3b276342d4c65dba2a5adf" vs "f3322e544bed83740514b5320f37452d"
> 2021/01/07 18:02:54 INFO : test.txt: Removing failed copy
> 2021/01/07 18:02:54 ERROR : Attempt 3/3 failed with 2 errors and: corrupted on transfer: MD5 hash differ "3f8a62a7db3b276342d4c65dba2a5adf" vs "f3322e544bed83740514b5320f37452d"
> 2021/01/07 18:02:54 Failed to copyto: corrupted on transfer: MD5 hash differ "3f8a62a7db3b276342d4c65dba2a5adf" vs "f3322e544bed83740514b5320f37452d"

Is this a setting you enable in minio? It sounds like when you enable it the MD5 is no longer correct.

You can use --ignore-checksum in that case if you want.

**Comment by jmargallo** [comment]
> 
> Is this a setting you enable in minio? It sounds like when you enable it the MD5 is no longer correct.
> 
Yes, it is a Minio setting
> You can use --ignore-checksum in that case if you want.
> 
--ignore-checksum doesn't seem like a good option to me since I need the transactions to be verified
Isn't it possible to have the 'auto compression' setting and not fail the MD5?

**Comment by ncw** [comment]
> > Is this a setting you enable in minio? It sounds like when you enable it the MD5 is no longer correct.
> 
> Yes, it is a Minio setting

OK

> > You can use --ignore-checksum in that case if you want.
> 
> --ignore-checksum doesn't seem like a good option to me since I need the transactions to be verified
> Isn't it possible to have the 'auto compression' setting and not fail the MD5?

The transfers will still be verified with SHA256 as part of the s3 protocol. The post transfer verification with the MD5 is the one that is failing.

**Comment by ivandeex** [comment]
@jmargallo 
As Nick explained, rclone can't guess Minio post-compression checksum.
The workaround proposed above still performs in-the-fly consistency check so you can be sure that compression source was valid.

AFAIK `--ignore-checksum` is recomnended in other situations when server transforms content on receival. For example, Google Photos can recompress JPEGs or Gdrive/Onedrive can convert office documents.

@animosity22 
Can we propose anything else here?

**Comment by ivandeex** [comment]
Closing inactive answered requests
