### ISSUE TITLE
1.53.2+ fails to upload file to Wasabi S3 - works with 1.47.0

### ISSUE THREAD

**Issue by AlexHeylin** [rclone/rclone#4913]
#### What is the problem you are having with rclone?
File fails to copy using 1.53.2+ but works with 1.47.0

We have a script that takes application backups and uploads them to Wasabi S3.  This has been working for at least a year. Most installs are using rclone 1.47.0 and these all work.   Some recent installs installed 1.53.2 & 1.53.3 (via your script) and these fail to upload stating lack of permission to create a bucket. Replacing the rclone binary with 1.47.0 makes these instances work as expected. 

Please note the bucket already exists - so permissions to create it seem irrelevant, especially as swapping the rclone binary to version 1.47.0 makes it work and swapping to version 1.53.2+ makes it fail.

#### What is your rclone version (output from `rclone version`)
rclone v1.53.3
- os/arch: linux/amd64
- go version: go1.15.5

rclone v1.47.0
- os/arch: linux/amd64
- go version: go1.12.4

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Linux - Debian AMD64
Debian GNU/Linux 9.13 (stretch)

####  Which cloud storage system are you using? (e.g. Google Drive)
Wasabi S3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone copy /var/lib/RE/DA/CT/ED.zip REDACTED:/REDACTED-backups/RE/DA/CT/ED/ -v --retries 10 --retries-sleep=15s  2>&1

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

s3_upload_result is 2021/01/08 14:02:15 DEBUG : rclone: Version "v1.53.3" starting with parameters ["/usr/bin/rclone" "copy" "/var/lib/REDACTED.zip" "REDACTED.s3-eu1:/REDACTED-backups/REDACTED/REDACTED/SERVERNAME/" "-vv" "--retries" "10" "--retries-sleep=15s"]
2021/01/08 14:02:15 DEBUG : Creating backend with remote "/var/lib/REDACTED.zip"
2021/01/08 14:02:15 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2021/01/08 14:02:15 DEBUG : fs cache: adding new entry for parent of "/var/lib/REDACTED.zip", "/var/lib/REDACTED/REDACTED/REDACTED/Backups"
2021/01/08 14:02:15 DEBUG : Creating backend with remote "REDACTED-s3-eu1:/REDACTED-backups/REDACTED/REDACTED/SERVERNAME/"
2021/01/08 14:02:15 DEBUG : fs cache: renaming cache item "REDACTED-s3-eu1:/REDACTED-backups/REDACTED/REDACTED/SERVERNAME/" to be canonical "REDACTED-s3-eu1:REDACTED-backups/REDACTED/REDACTED/SERVERNAME"
2021/01/08 14:02:15 DEBUG : REDACTED.zip: Need to transfer - File not found at Destination
2021/01/08 14:02:15 ERROR : REDACTED.zip: Failed to copy: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 356C55CCE6D56B17, host id: P8qEBCtTws/AIsDpDpCI9Xil0YXUztW1Mo/0qQNlpEipBgbIZG0VDvCPd5wy IYkbEAJp26Nkmoj
2021/01/08 14:02:15 ERROR : Attempt 1/10 failed with 1 errors and: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 356C55CCE6D56B17, host id: P8qEBCtTws/AIsDpDpCI9Xil0YXUztW1Mo/0qQNlpEipBgbIZG0VDvCPd5wy IYkbEAJp26Nkmoj
2021/01/08 14:02:30 DEBUG : REDACTED.zip: Need to transfer - File not found at Destination
2021/01/08 14:02:30 ERROR : REDACTED.zip: Failed to copy: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: DCB723B24501ED1B, host id: 9hhfbtZr6prxkLlbArurN8MES96AasDX pqK8NrNLUc7qWpzcDPVNDbvRxXxwe1GEAAtaCUGDif2
2021/01/08 14:02:30 ERROR : Attempt 2/10 failed with 1 errors and: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: DCB723B24501ED1B, host id: 9hhfbtZr6prxkLlbArurN8MES96AasDX pqK8NrNLUc7qWpzcDPVNDbvRxXxwe1GEAAtaCUGDif2
2021/01/08 14:02:46 DEBUG : REDACTED.zip: Need to transfer - File not found at Destination
2021/01/08 14:02:46 ERROR : REDACTED.zip: Failed to copy: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 7684F07B245A8678, host id: HElJUr2BBM8coQyC9cCHRlU0lgWJaU62O3GIpKtY6/jDfaw9qP/4AsMagNjmaU2M2ppeOFDzTtcg
2021/01/08 14:02:46 ERROR : Attempt 3/10 failed with 1 errors and: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 7684F07B245A8678, host id: HElJUr2BBM8coQyC9cCHRlU0lgWJaU62O3GIpKtY6/jDfaw9qP/4AsMagNjmaU2M2ppeOFDzTtcg
2021/01/08 14:03:01 DEBUG : REDACTED.zip: Need to transfer - File not found at Destination
2021/01/08 14:03:01 ERROR : REDACTED.zip: Failed to copy: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 0497854D10FC8BA1, host id: 7qBtFRTekvdZU0Vj88kmtSNCqHIg2hYTWp7uqt568t45fbGJtyBZsc3muKGFXgN67JsF8JHLB0ON
2021/01/08 14:03:01 ERROR : Attempt 4/10 failed with 1 errors and: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 0497854D10FC8BA1, host id: 7qBtFRTekvdZU0Vj88kmtSNCqHIg2hYTWp7uqt568t45fbGJtyBZsc3muKGFXgN67JsF8JHLB0ON
2021/01/08 14:03:15 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Elapsed time:       1m0.2s

2021/01/08 14:03:16 DEBUG : REDACTED.zip: Need to transfer - File not found at Destination
2021/01/08 14:03:16 ERROR : REDACTED.zip: Failed to copy: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: FD0F32C389F36BE6, host id: mLAYqi3q4RnscTcHSt/hes2YNSGFdAtw R8Sa8RsGKg151mwtf8 rhTDn7h31 EDDc1ieOKc1UWd
2021/01/08 14:03:16 ERROR : Attempt 5/10 failed with 1 errors and: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: FD0F32C389F36BE6, host id: mLAYqi3q4RnscTcHSt/hes2YNSGFdAtw R8Sa8RsGKg151mwtf8 rhTDn7h31 EDDc1ieOKc1UWd
2021/01/08 14:03:31 DEBUG : REDACTED.zip: Need to transfer - File not found at Destination
2021/01/08 14:03:31 ERROR : REDACTED.zip: Failed to copy: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: B612B2E836075112, host id: Qdwf50Rkv/sN/fegTSVNODcQGjCMMQWrbHVtnsQb0My38mWSMFMceL6kkIcd9EBH9mWbVioEUKGL
2021/01/08 14:03:31 ERROR : Attempt 6/10 failed with 1 errors and: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: B612B2E836075112, host id: Qdwf50Rkv/sN/fegTSVNODcQGjCMMQWrbHVtnsQb0My38mWSMFMceL6kkIcd9EBH9mWbVioEUKGL
2021/01/08 14:03:46 DEBUG : REDACTED.zip: Need to transfer - File not found at Destination
2021/01/08 14:03:46 ERROR : REDACTED.zip: Failed to copy: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 170E60329D2ED522, host id: w21s1B8ni4dNj0GfC0fBgcJp0pAQjmqiVB3eVtCM6V1toJ0zfQcF6Coz5n5PQLRdRUUdOxy04u1H
2021/01/08 14:03:46 ERROR : Attempt 7/10 failed with 1 errors and: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 170E60329D2ED522, host id: w21s1B8ni4dNj0GfC0fBgcJp0pAQjmqiVB3eVtCM6V1toJ0zfQcF6Coz5n5PQLRdRUUdOxy04u1H
2021/01/08 14:04:01 DEBUG : REDACTED.zip: Need to transfer - File not found at Destination
2021/01/08 14:04:01 ERROR : REDACTED.zip: Failed to copy: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 51DF3C1314F69AD0, host id: Ul00SF0YCJ/nEmu2JWj9mM/9dPLqhjBaVRJZ8TAdOwnYoRFKHCzUbDwlbMjlajjsl/VTzPR909rg
2021/01/08 14:04:01 ERROR : Attempt 8/10 failed with 1 errors and: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 51DF3C1314F69AD0, host id: Ul00SF0YCJ/nEmu2JWj9mM/9dPLqhjBaVRJZ8TAdOwnYoRFKHCzUbDwlbMjlajjsl/VTzPR909rg
2021/01/08 14:04:15 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Elapsed time:       2m0.2s

2021/01/08 14:04:16 DEBUG : REDACTED.zip: Need to transfer - File not found at Destination
2021/01/08 14:04:16 ERROR : REDACTED.zip: Failed to copy: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 55097E4C644B3D49, host id: OCAfaNkfjGR7mM6Ptj7uYsyphiuwKcczGCssqIH6Cqn4gXm 2uCjLwL caMzA7bbHvKoB/20LZ11
2021/01/08 14:04:16 ERROR : Attempt 9/10 failed with 1 errors and: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 55097E4C644B3D49, host id: OCAfaNkfjGR7mM6Ptj7uYsyphiuwKcczGCssqIH6Cqn4gXm 2uCjLwL caMzA7bbHvKoB/20LZ11
2021/01/08 14:04:31 DEBUG : REDACTED.zip: Need to transfer - File not found at Destination
2021/01/08 14:04:31 ERROR : REDACTED.zip: Failed to copy: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 68515FF8DB278146, host id: g5SZVhv1YzWEwW4X uhm8xe9TISeLR7IwJ4W2F1Y12KMSpvdf/G2SORLDLOC5wesCFSakJ3Loin9
2021/01/08 14:04:31 ERROR : Attempt 10/10 failed with 1 errors and: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 68515FF8DB278146, host id: g5SZVhv1YzWEwW4X uhm8xe9TISeLR7IwJ4W2F1Y12KMSpvdf/G2SORLDLOC5wesCFSakJ3Loin9
2021/01/08 14:04:46 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:      2m30.6s

2021/01/08 14:04:46 DEBUG : 4 go routines active
2021/01/08 14:04:46 Failed to copy: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 68515FF8DB278146, host id: g5SZVhv1YzWEwW4X uhm8xe9TISeLR7IwJ4W2F1Y12KMSpvdf/G2SORLDLOC5wesCFSakJ3Loin9

**Comment by AlexHeylin** [comment]
Possibly similar / same issue as #3819 (which I only found after creating this)

**Comment by ncw** [comment]
Can you try this so we can see the HTTP transaction.

    rclone mkdir REDACTED:/REDACTED-backups/RE/DA/CT/ED/ -vv --retries 1 --low-level-retries 1 --dump bodies

Does the user have permission to create buckets? Rclone tries to create the bucket as a shorthand for see if the bucket exists, create it if it doesn't. It relies on the error codes returned from the API which I guess may be different for wasabi.

You can almost certainly work around this with 

      --s3-no-check-bucket     If set, don't attempt to check the bucket exists or create it

However I'd like to get to the bottom of this!

I note that wasabi is returning the wrong error code here if I try to `mkdir` an existing bucket.

```
$ rclone mkdir -vv wasabi:rclone-secrets --dump bodies
2021/01/08 16:59:49 DEBUG : rclone: Version "v1.54.0-beta.5044.d58fdb10d.fix-onedrive-link" starting with parameters ["rclone" "mkdir" "-vv" "wasabi:rclone-secrets" "--dump" "bodies"]
2021/01/08 16:59:49 DEBUG : S3 bucket rclone-secrets: Making directory
2021/01/08 16:59:49 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021/01/08 16:59:49 DEBUG : HTTP REQUEST (req 0xc000710000)
2021/01/08 16:59:49 DEBUG : PUT /rclone-secrets HTTP/1.1
Host: s3.wasabisys.com
User-Agent: rclone/v1.54.0-beta.5044.d58fdb10d.fix-onedrive-link
Content-Length: 0
Authorization: XXXX
X-Amz-Acl: private
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210108T165949Z
Accept-Encoding: gzip

2021/01/08 16:59:49 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021/01/08 16:59:50 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2021/01/08 16:59:50 DEBUG : HTTP RESPONSE (req 0xc000710000)
2021/01/08 16:59:50 DEBUG : HTTP/1.1 200 OK
Content-Length: 0
Date: Fri, 08 Jan 2021 16:59:50 GMT
Location: /rclone-secrets
Server: WasabiS3/6.2.3461-2020-11-17-58b1c3e (head03)
X-Amz-Id-2: 34e9HOAc76LQZ5soR9rqSzz9h/ktFYV5IoMOl8ikeP2zHCBcpotSw5LiRNmTmzwxreyqzAczAjeU
X-Amz-Request-Id: C7EDFF9EA0FC0B0C

2021/01/08 16:59:50 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2021/01/08 16:59:50 INFO  : S3 bucket rclone-secrets: Bucket "rclone-secrets" created with ACL "private"
```

Note that it printed it created the bucket when it clearly didn't!

If I try the same on s3 I get a 409 Conflict error which is how rclone knows that the bucket exists already.

```
$ rclone mkdir -vv s3:rclone --dump bodies
2021/01/08 17:01:02 DEBUG : rclone: Version "v1.54.0-beta.5044.d58fdb10d.fix-onedrive-link" starting with parameters ["rclone" "mkdir" "-vv" "s3:rclone" "--dump" "bodies"]
2021/01/08 17:01:02 DEBUG : S3 bucket rclone: Making directory
2021/01/08 17:01:02 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021/01/08 17:01:02 DEBUG : HTTP REQUEST (req 0xc0000c6500)
2021/01/08 17:01:02 DEBUG : PUT / HTTP/1.1
Host: rclone.s3.eu-west-2.amazonaws.com
User-Agent: rclone/v1.54.0-beta.5044.d58fdb10d.fix-onedrive-link
Content-Length: 153
Authorization: XXXX
X-Amz-Acl: private
X-Amz-Content-Sha256: 45eae6f2cfced3c33c28eae76e8027a92fef08be88f823a1dfa67ef5c433666f
X-Amz-Date: 20210108T170102Z
Accept-Encoding: gzip

<CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LocationConstraint>eu-west-2</LocationConstraint></CreateBucketConfiguration>
2021/01/08 17:01:02 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021/01/08 17:01:02 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2021/01/08 17:01:02 DEBUG : HTTP RESPONSE (req 0xc0000c6500)
2021/01/08 17:01:02 DEBUG : HTTP/1.1 409 Conflict
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Fri, 08 Jan 2021 17:01:01 GMT
Server: AmazonS3
X-Amz-Bucket-Region: eu-west-2
X-Amz-Id-2: yBvJg6flBIH8QAZojbiu+owb/m2i56T9SMp9kkkuYbHX3r13A7Zsuk9TZiijLaPXq7kW4uRt9Fg=
X-Amz-Request-Id: 0287B449F685F199

162
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>BucketAlreadyOwnedByYou</Code><Message>Your previous request to create the named bucket succeeded and you already own it.</Message><BucketName>rclone</BucketName><RequestId>0287B449F685F199</RequestId><HostId>yBvJg6flBIH8QAZojbiu+owb/m2i56T9SMp9kkkuYbHX3r13A7Zsuk9TZiijLaPXq7kW4uRt9Fg=</HostId></Error>
0

2021/01/08 17:01:02 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
```

So I suspect a Wasabi S3 incompatibility here

**Comment by AlexHeylin** [comment]
Thanks for the speedy response. 
Here's the output you asked for. Sorry about the redactions, I realise they may make reading it harder but they are necessary,

2021/01/08 20:53:56 DEBUG : rclone: Version "v1.53.3" starting with parameters ["/usr/bin/rclone" "copy" "/var/lib/REDACTED/REDACTED/Data/Backups/REDACTED_20210108-2052_REDACTED.zip" "REDACTED-s3-eu1:/REDACTED-backups/REDACTED/REDACTED/REDACTED/" "-vv" "--retries" "1" "--low-level-retries" "1" "--dump" "bodies"]
2021/01/08 20:53:56 DEBUG : Creating backend with remote "/var/lib/REDACTED/REDACTED/Data/Backups/REDACTED_20210108-2052_REDACTED.zip"
2021/01/08 20:53:56 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2021/01/08 20:53:56 DEBUG : fs cache: adding new entry for parent of "/var/lib/REDACTED/REDACTED/Data/Backups/REDACTED_20210108-2052_REDACTED.zip", "/var/lib/REDACTED/REDACTED/Data/Backups"
2021/01/08 20:53:56 DEBUG : Creating backend with remote "REDACTED-s3-eu1:/REDACTED-backups/REDACTED/REDACTED/REDACTED/"
2021/01/08 20:53:56 DEBUG : You have specified to dump information. Please be noted that the Accept-Encoding as shown may not be correct in the request and the response may not show Content-Encoding if the go standard libraries auto gzip encoding was in effect. In this case the body of the request will be gunzipped before showing it.
2021/01/08 20:53:56 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021/01/08 20:53:56 DEBUG : HTTP REQUEST (req 0xc000123400)
2021/01/08 20:53:56 DEBUG : HEAD /REDACTED-backups/REDACTED/REDACTED/REDACTED HTTP/1.1
Host: s3.eu-central-1.wasabisys.com
User-Agent: rclone/v1.53.3
Authorization: XXXX
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210108T205356Z

2021/01/08 20:53:56 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021/01/08 20:53:56 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2021/01/08 20:53:56 DEBUG : HTTP RESPONSE (req 0xc000123400)
2021/01/08 20:53:56 DEBUG : HTTP/1.1 404 Not Found
Connection: close
Content-Type: application/xml
Date: Fri, 08 Jan 2021 20:53:56 GMT
Server: WasabiS3/6.2.3223-2020-10-14-51cd02c (head03)
X-Amz-Id-2: afRShpXgcgNdiO75mR4zyHmE9c50vVuH6BPZTx9z6NINv3xxWJHh1LunkdC90w92qh4Wcm1y/o92
X-Amz-Request-Id: F227A8221E061C79

2021/01/08 20:53:56 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2021/01/08 20:53:56 DEBUG : fs cache: renaming cache item "REDACTED-s3-eu1:/REDACTED-backups/REDACTED/REDACTED/REDACTED/" to be canonical "REDACTED-s3-eu1:REDACTED-backups/REDACTED/REDACTED/REDACTED"
2021/01/08 20:53:56 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021/01/08 20:53:56 DEBUG : HTTP REQUEST (req 0xc000122200)
2021/01/08 20:53:56 DEBUG : HEAD /REDACTED-backups/REDACTED/REDACTED/REDACTED/REDACTED_20210108-2052_REDACTED.zip HTTP/1.1
Host: s3.eu-central-1.wasabisys.com
User-Agent: rclone/v1.53.3
Authorization: XXXX
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210108T205356Z

2021/01/08 20:53:56 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021/01/08 20:53:56 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2021/01/08 20:53:56 DEBUG : HTTP RESPONSE (req 0xc000122200)
2021/01/08 20:53:56 DEBUG : HTTP/1.1 404 Not Found
Connection: close
Content-Type: application/xml
Date: Fri, 08 Jan 2021 20:53:56 GMT
Server: WasabiS3/6.2.3223-2020-10-14-51cd02c (head03)
X-Amz-Id-2: 5UdcN798C6kt1L096asaOlRwY6Vt0wkL8e6hAdWFwlV0rBZqH U1RFsBbic4n2H3hFRtYSgJGNTD
X-Amz-Request-Id: 0187B30D91170B93

2021/01/08 20:53:56 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2021/01/08 20:53:56 DEBUG : REDACTED_20210108-2052_REDACTED.zip: Need to transfer - File not found at Destination
2021/01/08 20:53:56 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021/01/08 20:53:56 DEBUG : HTTP REQUEST (req 0xc000122b00)
2021/01/08 20:53:56 DEBUG : PUT /REDACTED-backups HTTP/1.1
Host: s3.eu-central-1.wasabisys.com
User-Agent: rclone/v1.53.3
Content-Length: 0
Authorization: XXXX
X-Amz-Acl: private
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210108T205356Z
Accept-Encoding: gzip

2021/01/08 20:53:56 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021/01/08 20:53:56 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2021/01/08 20:53:56 DEBUG : HTTP RESPONSE (req 0xc000122b00)
2021/01/08 20:53:56 DEBUG : HTTP/1.1 403 Forbidden
Transfer-Encoding: chunked
Content-Type: application/xml
Date: Fri, 08 Jan 2021 20:53:56 GMT
Server: WasabiS3/6.2.3223-2020-10-14-51cd02c (head03)
X-Amz-Id-2: tMEtLLdQAvts2pnKym1w Hso3u/0Vy81O292DYquJvKNZiLUzwhSzF24WJB9fQxChZsQinm/wK1b
X-Amz-Request-Id: 4F9FBE8F1AD2F430

176
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups</Message><RequestId>4F9FBE8F1AD2F430</RequestId><HostId>tMEtLLdQAvts2pnKym1w Hso3u/0Vy81O292DYquJvKNZiLUzwhSzF24WJB9fQxChZsQinm/wK1b</HostId></Error>
0

2021/01/08 20:53:56 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2021/01/08 20:53:56 ERROR : REDACTED_20210108-2052_REDACTED.zip: Failed to copy: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 4F9FBE8F1AD2F430, host id: tMEtLLdQAvts2pnKym1w Hso3u/0Vy81O292DYquJvKNZiLUzwhSzF24WJB9fQxChZsQinm/wK1b
2021/01/08 20:53:56 ERROR : Attempt 1/1 failed with 1 errors and: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 4F9FBE8F1AD2F430, host id: tMEtLLdQAvts2pnKym1w Hso3u/0Vy81O292DYquJvKNZiLUzwhSzF24WJB9fQxChZsQinm/wK1b
2021/01/08 20:53:56 INFO  : 
Transferred:   	         0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         0.8s

2021/01/08 20:53:56 DEBUG : 5 go routines active
2021/01/08 20:53:56 Failed to copy: AccessDenied: User: arn:aws:iam::100000025565:user/REDACTED-backups/REDACTED is not authorized to perform: s3:CreateBucket on resource: arn:aws:s3:::REDACTED-backups
	status code: 403, request id: 4F9FBE8F1AD2F430, host id: tMEtLLdQAvts2pnKym1w Hso3u/0Vy81O292DYquJvKNZiLUzwhSzF24WJB9fQxChZsQinm/wK1b

The user does not have permissions to create a bucket.  However the bucket already exists so they don't need that permission, and it works with v1.47.0.  It has permissions to create folders and files within the bucket, but not to delete them which is what we require for this key / secret pair. 

It's entirely possible Wasabi is either "incompatible" or at least different to AWS S3 - unfortunately I don't know S3 well enough to comment on that.  I can tell you the same operation using the same key / secret pair works fine using CyberDuck 7.5.2 using "Amazon S3" settings, and it works using rclone 1.47.0.  So as a wise boss of mine used to say "what changed?" between 1.47.0 and 1.52.2 - that's where I'd look. 

For now I've downgraded everything to rclone 1.47.0 (and modified our install process to install only 1.47.0) because that's easier and quicker than upgrading everything and trying to get it to work.  As this is all scripted and the script is the shared across all machines we need one set of config / commands to work for everything.  We don't need any new things, so 1.47.0 is fine for us for now. However, I'd like to help you get to the bottom of this and iron out whatever that breaking change is. 

So, for us - we don't need a different config that works with Wasabi right now - I've opened this to make you aware it "broke" and potentially needs "fixing" (revert to old behaviour), or docs to cover how to get this to work in a situation like this (including documenting which is the boundary version where this changes).  .

Thanks

**Comment by ncw** [comment]
Did you try the `--s3-no-check-bucket` flag? Which you can put into the config as `no_check_bucket = true`?

I'm pretty sure that will work around the problem

As to why...

The ultimate cause of this was a bug in rclone f8039deb7 which was letting bucket creation errors pass silently which is why it worked in 1.47.

This means that rclone now checks the return of the create bucket call. Attempting to create the bucket with a user with limited permissions is returning `AccessDenied` instead of `BucketAlreadyOwnedByYou` or `BucketAlreadyExists`. Hence the need for the `no_check_bucket` permission.

I've added another paragraph to the docs with some more explanations: 3877df4e62dad93ef0309011896ae77262c22690

**Comment by AlexHeylin** [comment]
Sorry for the delay in coming back to this. I've now had a chance to test this and with v1.54.0 and ```no_check_bucket = true``` in the config this works as expected. 

I've tested this on v1.47.0 and it works on that too.  

So, yes Wasabi requires use of ```no_check_bucket = true``` even though this used to work without in <= 1.47.0

Many thanks for your help!

**Comment by CoolCold** [comment]
thanks for guys bringing it up, was crashing my head over the table, trying to understand WTH CreateBucket when I just copy file to Wasabi .
With config changes, it works fine now.
