### ISSUE TITLE
Error while mounting Gdrive on Windows 10

### ISSUE THREAD

**Issue by infinity-plus** [rclone/rclone#4916]
#### What is the problem you are having with rclone?
rclone mount won't mount my Google Drive to the specified path.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.53.3
- os/arch: windows/amd64
- go version: go1.15.5
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 10 64 bit
Version 20H2 (OS Build 19042.685)

####  Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone mount pu: G:\ --fuse-flag --VolumePrefix=\\server\pu\`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2021/01/09 13:17:05 DEBUG : rclone: Version "v1.53.3" starting with parameters ["rclone" "-vv" "mount" "pu:" "G:\\drive" "--fuse-flag" "--VolumePrefix=\\\\server\\pu\\"]
2021/01/09 13:17:05 DEBUG : Creating backend with remote "pu:"
2021/01/09 13:17:05 DEBUG : Using config file from "C:\\Users\\ASUS\\.config\\rclone\\rclone.conf"
2021/01/09 13:17:06 DEBUG : Google drive root '': Mounting on "G:\\drive"
2021/01/09 13:17:06 DEBUG : Google drive root '': Mounting with options: ["-o" "fsname=pu:" "-o" "subtype=rclone" "-o" "max_readahead=131072" "-o" "attr_timeout=1" "-o" "atomic_o_trunc" "-o" "uid=-1" "-o" "gid=-1" "--FileSystemName=rclone" "-o" "volname=pu" "--VolumePrefix=\\\\server\\pu\\"]
Cannot create WinFsp-FUSE file system: invalid mount point.
2021/01/09 13:17:06 ERROR : Google drive root '': Mount failed
2021/01/09 13:17:06 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed
```

**Comment by Masamune3210** [comment]
pretty sure it's something to do with your requested mount point, as it's failing in Win-FSP, which then fails to init, causing rclone to throw it's hands up and error out

**Comment by infinity-plus** [comment]
>  it's something to do with your requested mount point, as it's failing in Win-FSP, which then fails to init
What should I do? My Aim is to mount GDrive as G:, and access it from 'This PC'

**Comment by infinity-plus** [comment]
While I tried deleting and adding the config for my drive again, and then mount it, I get the `following` error:

```
Cannot create WinFsp-FUSE file system.
The service rclone has failed to start (Status=c000000d).
2021/01/09 15:23:26 ERROR : Google drive root '': Mount failed
2021/01/09 15:23:36 ERROR : mountpoint "G:" didn't became available on mount - continuing anyway
2021/01/09 15:23:36 Fatal error: failed to umount FUSE fs: mount failed

D:\Harsh>rclone mount pu: G: --fuse-flag --VolumePrefix=\\server\pu\ -vv
2021/01/09 15:26:51 DEBUG : rclone: Version "v1.53.3" starting with parameters ["rclone" "mount" "pu:" "G:" "--fuse-flag" "--VolumePrefix=\\\\server\\pu\\" "-vv"]
2021/01/09 15:26:51 DEBUG : Creating backend with remote "pu:"
2021/01/09 15:26:51 DEBUG : Using config file from "C:\\Users\\ASUS\\.config\\rclone\\rclone.conf"
2021/01/09 15:26:53 DEBUG : Google drive root '': root_folder_id = "0AC4P0MHuVlUlUk9PVA" - save this in the config to speed up startup
2021/01/09 15:26:54 DEBUG : Google drive root '': Mounting on "G:"
2021/01/09 15:26:54 DEBUG : Google drive root '': Mounting with options: ["-o" "fsname=pu:" "-o" "subtype=rclone" "-o" "max_readahead=131072" "-o" "attr_timeout=1" "-o" "atomic_o_trunc" "-o" "uid=-1" "-o" "gid=-1" "--FileSystemName=rclone" "-o" "volname=pu" "--VolumePrefix=\\\\server\\pu\\"]
2021/01/09 15:26:54 DEBUG : Google drive root '': Init:
2021/01/09 15:26:54 DEBUG : Google drive root '': >Init:
2021/01/09 15:26:54 DEBUG : /: Statfs:
2021/01/09 15:26:55 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:274886138170 Bfree:274877906944 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2021/01/09 15:26:55 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 15:26:55 DEBUG : /: >Getattr: errc=0
2021/01/09 15:26:55 DEBUG : /: Readlink:
2021/01/09 15:26:55 DEBUG : /: >Readlink: linkPath="", errc=-40
Cannot create WinFsp-FUSE file system.
2021/01/09 15:26:55 DEBUG : Google drive root '': Destroy:
2021/01/09 15:26:55 DEBUG : Google drive root '': >Destroy:
The service rclone has failed to start (Status=c000000d).
2021/01/09 15:26:55 ERROR : Google drive root '': Mount failed
2021/01/09 15:27:05 ERROR : mountpoint "G:" didn't became available on mount - continuing anyway
2021/01/09 15:27:05 DEBUG : Calling host.Unmount
2021/01/09 15:27:05 DEBUG : host.Unmount failed
2021/01/09 15:27:05 Fatal error: failed to umount FUSE fs: mount failed
```

**Comment by ncw** [comment]
> #### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
> `rclone mount pu: G:\ --fuse-flag --VolumePrefix=\\server\pu\`

Does it work without the `--fuse-flag --VolumePrefix=\\server\pu\`?

I think you might want [the latest beta](https://beta.rclone.org) which has much better support for this.

Here is the help for the beta

#### Mounting modes on windows

Unlike other operating systems, Microsoft Windows provides a different filesystem
type for network and fixed drives. It optimises access on the assumption fixed
disk drives are fast and reliable, while network drives have relatively high latency
and less reliability. Some settings can also be differentiated between the two types,
for example that Windows Explorer should just display icons and not create preview
thumbnails for image and video files on network drives.

In most cases, rclone will mount the remote as a normal, fixed disk drive by default.
However, you can also choose to mount it as a remote network drive, often described
as a network share. If you mount an rclone remote using the default, fixed drive mode
and experience unexpected program errors, freezes or other issues, consider mounting
as a network drive instead.

When mounting as a fixed disk drive you can either mount to an unused drive letter,
or to a path - which must be **non-existent** subdirectory of an **existing** parent
directory or drive. Using the special value `*` will tell rclone to
automatically assign the next available drive letter, starting with Z: and moving backward.
Examples:

    rclone mount remote:path/to/files *
    rclone mount remote:path/to/files X:
    rclone mount remote:path/to/files C:\path\to\nonexistent\directory
    rclone mount remote:path/to/files X:

Option `--volname` can be used to set a custom volume name for the mounted
file system. The default is to use the remote name and path.

To mount as network drive, you can add option `--network-mode`
to your mount command. Mounting to a directory path is not supported in
this mode, it is a limitation Windows imposes on junctions, so the remote must always
be mounted to a drive letter.

    rclone mount remote:path/to/files X: --network-mode

A volume name specified with `--volname` will be used to create the network share path.
A complete UNC path, such as `\\cloud\remote`, optionally with path
`\\cloud\remote\madeup\path`, will be used as is. Any other
string will be used as the share part, after a default prefix `\\server\`.
If no volume name is specified then `\\server\share` will be used.
You must make sure the volume name is unique when you are mounting more than one drive,
or else the mount command will fail. The share name will treated as the volume label for
the mapped drive, shown in Windows Explorer etc, while the complete
`\\server\share` will be reported as the remote UNC path by
`net use` etc, just like a normal network drive mapping.

If you specify a full network share UNC path with `--volname`, this will implicitely
set the `--network-mode` option, so the following two examples have same result:

    rclone mount remote:path/to/files X: --network-mode
    rclone mount remote:path/to/files X: --volname \\server\share

You may also specify the network share UNC path as the mountpoint itself. Then rclone
will automatically assign a drive letter, same as with `*` and use that as
mountpoint, and instead use the UNC path specified as the volume name, as if it were
specified with the `--volname` option. This will also implicitely set
the `--network-mode` option. This means the following two examples have same result:

    rclone mount remote:path/to/files \\cloud\remote
    rclone mount remote:path/to/files * --volname \\cloud\remote

There is yet another way to enable network mode, and to set the share path,
and that is to pass the "native" libfuse/WinFsp option directly:
`--fuse-flag --VolumePrefix=\server\share`. Note that the path
must be with just a single backslash prefix in this case.


*Note:* In previous versions of rclone this was the only supported method.

[Read more about drive mapping](https://en.wikipedia.org/wiki/Drive_mapping)

**Comment by infinity-plus** [comment]
@ncw thank you so much for the update.
I successfully managed to make the command successful, but...
I can't mount it. It says the drive is mounted at Z: but Z: is not accessible anywhere on the machine.
Trying to mount a network drive with path: \\server\share doesn't work either.
Below is what I did and what I got.


**C:\Windows\system32>rclone mount pu: * --fuse-flag --VolumePrefix=\server\share -vvv**
```
2021/01/09 23:04:25 DEBUG : rclone: Version "v1.54.0-beta.5050.ef2bfb971" starting with parameters ["rclone" "mount" "pu:" "*" "--fuse-flag" "--VolumePrefix=\\server\\share" "-vvv"]
2021/01/09 23:04:25 DEBUG : Creating backend with remote "pu:"
2021/01/09 23:04:25 DEBUG : Using config file from "C:\\Users\\ASUS\\.config\\rclone\\rclone.conf"
2021/01/09 23:04:27 DEBUG : Google drive root '': root_folder_id = "0AC4P0MHuVlUlUk9PVA" - save this in the config to speed up startup
2021/01/09 23:04:27 NOTICE: Assigning drive letter "Z:"
2021/01/09 23:04:27 DEBUG : Network mode mounting is disabled
2021/01/09 23:04:27 DEBUG : Mounting on "Z:" ("pu")
2021/01/09 23:04:27 DEBUG : Google drive root '': Mounting with options: ["-o" "attr_timeout=1" "-o" "uid=-1" "-o" "gid=-1" "--FileSystemName=rclone" "-o" "volname=pu" "--VolumePrefix=\\server\\share"]
2021/01/09 23:04:27 DEBUG : Google drive root '': Init:
2021/01/09 23:04:27 DEBUG : Google drive root '': >Init:
2021/01/09 23:04:27 DEBUG : /: Statfs:
2021/01/09 23:04:28 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:274886138170 Bfree:274877906944 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2021/01/09 23:04:28 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 23:04:28 DEBUG : /: >Getattr: errc=0
2021/01/09 23:04:28 DEBUG : /: Readlink:
2021/01/09 23:04:28 DEBUG : /: >Readlink: linkPath="", errc=-40
The service rclone has been started.
2021/01/09 23:04:28 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 23:04:28 DEBUG : /: >Getattr: errc=0
2021/01/09 23:04:28 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 23:04:28 DEBUG : /: >Getattr: errc=0
2021/01/09 23:04:28 DEBUG : /: Opendir:
2021/01/09 23:04:28 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2021/01/09 23:04:28 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2021/01/09 23:04:28 DEBUG : /: >Opendir: errc=0, fh=0x0
2021/01/09 23:04:28 DEBUG : /: Releasedir: fh=0x0
2021/01/09 23:04:28 DEBUG : /: >Releasedir: errc=0
2021/01/09 23:04:28 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 23:04:28 DEBUG : /: >Getattr: errc=0
2021/01/09 23:04:28 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 23:04:28 DEBUG : /: >Getattr: errc=0
2021/01/09 23:04:28 DEBUG : /: Opendir:
2021/01/09 23:04:28 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2021/01/09 23:04:28 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2021/01/09 23:04:28 DEBUG : /: >Opendir: errc=0, fh=0x0
2021/01/09 23:04:28 DEBUG : /: Releasedir: fh=0x0
2021/01/09 23:04:28 DEBUG : /: >Releasedir: errc=0
2021/01/09 23:04:28 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 23:04:28 DEBUG : /: >Getattr: errc=0
2021/01/09 23:04:28 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 23:04:28 DEBUG : /: >Getattr: errc=0
2021/01/09 23:04:28 DEBUG : /: Opendir:
2021/01/09 23:04:28 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2021/01/09 23:04:28 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2021/01/09 23:04:28 DEBUG : /: >Opendir: errc=0, fh=0x0
2021/01/09 23:04:28 DEBUG : /: Releasedir: fh=0x0
2021/01/09 23:04:28 DEBUG : /: >Releasedir: errc=0
2021/01/09 23:05:27 DEBUG : Google drive root '': Checking for changes on remote
2021/01/09 23:06:27 DEBUG : Google drive root '': Checking for changes on remote
2021/01/09 23:07:27 DEBUG : Google drive root '': Checking for changes on remote
2021/01/09 23:08:27 DEBUG : Google drive root '': Checking for changes on remote
2021/01/09 23:08:57 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 23:08:57 DEBUG : /: >Getattr: errc=0
2021/01/09 23:08:57 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 23:08:57 DEBUG : /: >Getattr: errc=0
2021/01/09 23:08:57 DEBUG : /: Opendir:
2021/01/09 23:08:57 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2021/01/09 23:08:57 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2021/01/09 23:08:57 DEBUG : /: >Opendir: errc=0, fh=0x0
2021/01/09 23:08:57 DEBUG : /: Releasedir: fh=0x0
2021/01/09 23:08:57 DEBUG : /: >Releasedir: errc=0
2021/01/09 23:09:00 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 23:09:00 DEBUG : /: >Getattr: errc=0
2021/01/09 23:09:00 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 23:09:00 DEBUG : /: >Getattr: errc=0
2021/01/09 23:09:00 DEBUG : /: Opendir:
2021/01/09 23:09:00 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2021/01/09 23:09:00 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2021/01/09 23:09:00 DEBUG : /: >Opendir: errc=0, fh=0x0
2021/01/09 23:09:00 DEBUG : /: Releasedir: fh=0x0
2021/01/09 23:09:00 DEBUG : /: >Releasedir: errc=0
2021/01/09 23:09:11 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 23:09:11 DEBUG : /: >Getattr: errc=0
2021/01/09 23:09:11 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 23:09:11 DEBUG : /: >Getattr: errc=0
2021/01/09 23:09:11 DEBUG : /: Opendir:
2021/01/09 23:09:11 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2021/01/09 23:09:11 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2021/01/09 23:09:11 DEBUG : /: >Opendir: errc=0, fh=0x0
2021/01/09 23:09:11 DEBUG : /: Releasedir: fh=0x0
2021/01/09 23:09:11 DEBUG : /: >Releasedir: errc=0
2021/01/09 23:09:11 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 23:09:11 DEBUG : /: >Getattr: errc=0
2021/01/09 23:09:11 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/09 23:09:11 DEBUG : /: >Getattr: errc=0
2021/01/09 23:09:11 DEBUG : /: Opendir:
2021/01/09 23:09:11 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2021/01/09 23:09:11 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2021/01/09 23:09:11 DEBUG : /: >Opendir: errc=0, fh=0x0
2021/01/09 23:09:11 DEBUG : /: Releasedir: fh=0x0
2021/01/09 23:09:11 DEBUG : /: >Releasedir: errc=0
2021/01/09 23:09:27 DEBUG : Google drive root '': Checking for changes on remote
2021/01/09 23:10:27 DEBUG : Google drive root '': Checking for changes on remote
```

**Comment by Masamune3210** [comment]
Have you tried closing the mount and reopening it? It's ultimately up to Windows to detect a new device and correctly show it in Explorer, and I've noticed it can be particularly lazy about it sometimes

**Comment by infinity-plus** [comment]
Oh yes,tried, but no luck

**Comment by ncw** [comment]
> **C:\Windows\system32>rclone mount pu: * --fuse-flag --VolumePrefix=\server\share -vvv**

I don't know whether it will make a difference, but I think you need two \\ here, so

    rclone mount pu: * --fuse-flag --VolumePrefix=\\server\share -vvv

**Comment by albertony** [comment]
> I think you need two \ here

Actually not. That is part of the confusion with the existing mount syntax. WinFsp expects "UNC prefix (single backslash)" in the VolumePrefix option. With the new syntax in rclone beta the more standard double backslash syntax "\\\\server\\share" is accepted in "native rclone" option --volname etc.

@infinity-plus: Are you running the command from an Command Prompt opened as administrator? I noticed current directory is `C:\Windows\system32`, which you typically get as default in such cases. If so, read [this](https://rclone.org/commands/rclone_mount/#windows-caveats).

**Comment by infinity-plus** [comment]
Thank you all, It worked by using the following method.

`rclone mount pu: * --volname \\server\pudrive`

![image](https://user-images.githubusercontent.com/39484407/106092449-553adc00-6154-11eb-96fd-2c4a15a978e0.png)
