### ISSUE TITLE
Suggestion: let the user customize retry timers.

### ISSUE THREAD

**Issue by left1000** [rclone/rclone#492]
In the event ACD is blocking rclone commands on purpose for a short while, the default retry settings of 1second are not really sufficient.

I'd like to be able to input my normal rclone commands, notice something is wrong after about a minute, and then re-enter my command with a flag like -retry-timer=300s

In theory this might allow users to avoid feeling any actual frustration at having their commands delayed.

There are probably some other usage applications for the flag as well.

**Comment by ivandeex** [comment]
@left1000 @ncw
rclone now supports `--retries-sleep <duration>`
I suggest closing this stale issue

**Comment by ivandeex** [comment]
Closing stale issues
