### ISSUE TITLE
rclone 1.54 version compress function demo remote is S3

### ISSUE THREAD

**Issue by Cloud-Zhang** [rclone/rclone#4920]
Could you please share one simple demo for how to use the 1.54 COMPRESS function?

**Comment by ivandeex** [comment]
get binary (e.g. _rclone-beta-latest-windows-amd64.zip_) from https://beta.rclone.org/
see docs on https://tip.rclone.org/compress/

**Comment by Cloud-Zhang** [comment]
Hi 
Thanks fro your reply. Now i already read the docs but seems it is only simple guide . there is no detail more . In our case we have the oss to store the file. now try to list the config as below .
rclone.conf 
[test]
type = s3
provider = Ceph
env_auth = false
access_key_id = zEl1os171Wsc9L9L
secret_access_key = RzsPEDLWQzsSaJhVdmoZZfw7G5jG6z
endpoint = oss-cn-north-1.unicloudsrv.com
acl = private

![image](https://user-images.githubusercontent.com/73331356/104274103-13b2fb80-54db-11eb-8a7c-a014aef4a439.png)

now if i want to make this endpoint to the compress mode how should i change it ?

Thanks

**Comment by Cloud-Zhang** [comment]
root@ubuntu:~/.config/rclone# rclone lsd test:
          -1 2020-05-25 11:07:51        -1 backup-rds-dev
          -1 2020-10-27 15:55:31        -1 moove-bigdata-server-cto
          -1 2020-05-25 13:55:49        -1 moove-nosql-backup-dev
          -1 2020-05-25 10:23:33        -1 moove-nosql-backup-pre
          -1 2020-05-25 13:55:11        -1 moove-nosql-server-dev
          -1 2020-05-25 10:20:21        -1 moove-uni-nosql-pre
          -1 2020-06-04 15:07:07        -1 old-dbaas-mysqlha-test
          -1 2020-06-04 15:07:02        -1 old-dbaas-mysqlse-test
          -1 2020-05-26 16:20:13        -1 old-dbaas-nosql-backup-test
          -1 2020-05-26 16:19:11        -1 old-dbaas-nosql-test
          -1 2020-06-04 15:06:25        -1 old-unicloud-rds
          -1 2020-05-25 10:23:38        -1 uni-backup-rds-pre
          -1 2020-05-25 10:12:38        -1 uni-rds-dev
          -1 2020-05-25 10:19:54        -1 uni-rds-pre

**Comment by Cloud-Zhang** [comment]
root@ubuntu:~/.config/rclone# rclone lsd test:
          -1 2020-05-25 11:07:51        -1 backup-rds-dev
          -1 2020-10-27 15:55:31        -1 moove-bigdata-server-cto
          -1 2020-05-25 13:55:49        -1 moove-nosql-backup-dev
          -1 2020-05-25 10:23:33        -1 moove-nosql-backup-pre
          -1 2020-05-25 13:55:11        -1 moove-nosql-server-dev
          -1 2020-05-25 10:20:21        -1 moove-uni-nosql-pre
          -1 2020-06-04 15:07:07        -1 old-dbaas-mysqlha-test
          -1 2020-06-04 15:07:02        -1 old-dbaas-mysqlse-test
          -1 2020-05-26 16:20:13        -1 old-dbaas-nosql-backup-test
          -1 2020-05-26 16:19:11        -1 old-dbaas-nosql-test
          -1 2020-06-04 15:06:25        -1 old-unicloud-rds
          -1 2020-05-25 10:23:38        -1 uni-backup-rds-pre
          -1 2020-05-25 10:12:38        -1 uni-rds-dev
          -1 2020-05-25 10:19:54        -1 uni-rds-pre

**Comment by Cloud-Zhang** [comment]
In fact now we use the Amazon S3 as the Storage. Can we also use this as the compress function?

**Comment by ivandeex** [comment]
Compress should work for most backends supported by rclone, but remember that this feature is still in its infancy, not even released officially. For support questions you'd better use https://forum.rclone.org

**Comment by Cloud-Zhang** [comment]
@ivandeex  Thanks for your support. just want to check this function in advance. By the way do you have any simple guide how to use it. Of course i read the compress.md it is just a configure process. how to use the command if we use the S3 as the storage how to use it ? Do you have any idea?

**Comment by ivandeex** [comment]
As a prerequisite I have an S3 remote called `TestS3`.
I downloaded latest rclone beta as I explained above.
I create a `test.txt` file locally with content `123` using a text editor.
Now I follow the `compress` backend documentation from the link provided above in this issue
```
$ rclone config
e) Edit existing remote
n) New remote
[snip]
e/n/d/r/c/s/q> n
name> TestCompress
Type of storage to configure.
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
 1 / 1Fichier
   \ "fichier"
[snip]
Storage> compress
** See help for compress backend at: https://rclone.org/compress/ **
Remote to compress.
Enter a string value. Press Enter for the default ("").
remote> TestS3:
Compression mode.
Enter a string value. Press Enter for the default ("gzip").
Choose a number from below, or type in your own value
 1 / Standard gzip compression with fastest parameters.
   \ "gzip"
mode>
Edit advanced config? (y/n)
y) Yes
n) No (default)
y/n> n
Remote config
--------------------
[TestCompress]
type = compress
remote = TestS3:
--------------------
y) Yes this is OK (default)
e) Edit this remote
d) Delete this remote
y/e/d> y
Current remotes:
[snip]
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> q
$ rclone ls TestCompress:
$ rclone mkdir TestCompress:ivatest20210111
$ rclone copyto test.txt TestCompress:ivatest20210111/test.txt
2021/01/13 23:06:30 ERROR : test.txt: Failed to copy: s3 upload: 400 Bad Request: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>BadDigest</Code><Message>The Content-MD5 you specified did not match what we received.</Message><ExpectedDigest>d577273ff885c3f84dadb8578bb41399</ExpectedDigest><CalculatedDigest>Cr3pWSEOQp0EYXU/Aj4L5g==</CalculatedDigest><Reques
tId>F60726F088D106CF</RequestId><HostId>vaDHpvjQSvz+Fmv1ag1WsoH4V3oB/2TKcMzFWqcyNbcQPnodNT2gEPtNEC/swt+NEDu2tOd3TZw=</Hos
tId></Error>
```
@Cloud-Zhang This has been indeed a simple (failed) guide requested by you :)

**Comment by ivandeex** [comment]
Closing this as the question was answered
