### ISSUE TITLE
vfs/refresh times out

### ISSUE THREAD

**Issue by zenjabba** [rclone/rclone#4922]
+ rclone rc vfs/refresh -vvv --rc-addr=localhost:5590 recursive=true dir=zd-tv2/tv/10s/
2021/01/11 15:19:30 DEBUG : rclone: Version "v1.54.0-beta.4965.cb16f4207" starting with parameters ["rclone" "rc" "vfs/refresh" "-vvv" "--rc-addr=localhost:5590" "recursive=true" "dir=zd-tv2/tv/10s/"]
{
	"result": {
		"zd-tv2/tv/10s/": "RequestError: send request failed\ncaused by: Get \"https://XXX/zd-tv2?delimiter=\u0026encoding-type=url\u0026max-keys=1000\u0026prefix=tv%2F10s%2F\": net/http: timeout awaiting response headers"

endpoint: s3

Would like a way to force rclone to retry or continue.

**Comment by ncw** [comment]
The easiest thing to do here is to make the request asynchronous, so run with an extra parameter `_async=true` this will cause the request to carry on in the background and return immediately.

You can poll it for completion with the job ID if you want, but I suspect just having it run in the background will be enough.

You can also increase the `--timeout` parameter.

**Comment by ivandeex** [comment]
Closing due to user inactivity after the question has been answered.
