### ISSUE TITLE
Availability of Compress backend for S3 remotes

### ISSUE THREAD

**Issue by wangshuang0220** [rclone/rclone#4923]
Is the compression function compatible with Alibaba cloud

**Comment by ncw** [comment]
Do you mean the [compress backend](https://tip.rclone.org/compress/)? That is compatible with all backends.

**Comment by wangshuang0220** [comment]
> Do you mean the [compress backend](https://tip.rclone.org/compress/)? That is compatible with all backends.
Can I compress while uploading files with the  [compress fuction]

**Comment by ivandeex** [comment]
@wangshuang0220 
yes

**Comment by wangshuang0220** [comment]
May i get some samples?

**Comment by ivandeex** [comment]
```
$ mkdir /tmp/compress
$ rclone config
n) New remote
[snip]
e/n/d/r/c/s/q> n
name> TestCompress
Type of storage to configure.
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
 1 / 1Fichier
   \ "fichier"
[snip]
Storage> compress
** See help for compress backend at: https://rclone.org/compress/ **
Remote to compress.
Enter a string value. Press Enter for the default ("").
remote> /tmp/compress
Compression mode.
Enter a string value. Press Enter for the default ("gzip").
Choose a number from below, or type in your own value
 1 / Standard gzip compression with fastest parameters.
   \ "gzip"
mode>
Edit advanced config? (y/n)
y) Yes
n) No (default)
y/n> n
Remote config
--------------------
[TestCompress]
type = compress
remote = /tmp/compress
--------------------
y) Yes this is OK (default)
e) Edit this remote
d) Delete this remote
y/e/d> y
Current remotes:
[snip]
q) Quit config
e/n/d/r/c/s/q> q
$ rclone ls TestCompress:
<empty>
$ echo 12121212121212121212121212121212 | rclone rcat TestCompress:test.txt
$ rclone lsl TestCompress:
33 2021-01-19 05:08 test.txt
$ ls -l /tmp/compress/
-rw-r--r-- 1 deex deex  63 Jan 19 05:08 test.txt.IQAAAAAAAAA.gz
-rw-r--r-- 1 deex deex 165 Jan 19 05:08 test.txt.json
```

**Comment by wangshuang0220** [comment]
@ivandeex tks for support, May i know when i can get the linux os executable file for #4928,  now i  can get the windows version only.

**Comment by ivandeex** [comment]
the release is scheduled for february

**Comment by wangshuang0220** [comment]
> the release is scheduled for february
@ivandeex 
tks, got it.  May i know when i can get the beta version for linux-amd64 with compress issue fixed  #4928 from https://beta.rclone.org/

**Comment by ivandeex** [comment]
> when i can get the beta version for linux-amd64 with compress issue fixed  #4928 

now.
remember that betas are not supported.

**Comment by ivandeex** [comment]
> when i can get the beta version for linux-amd64 with compress issue fixed  #4928 

something is wrong with beta builds for linux now.
this should be fixed soon.
thank you for patience.

**Comment by ivandeex** [comment]
> when i can get the beta version for linux-amd64 with compress issue fixed  #4928 

@wangshuang0220 
something is wrong with beta builds for linux now.
this should be fixed soon.
thank you for patience.

@ncw 
the latest windows or netbsd beta on beta.rclone.org is dated 2021-01-19
the latest **linux** beta on beta.rclone.org is dated 2021-01-17
please have a look
thank you

**Comment by ivandeex** [comment]
@wangshuang0220 
https://beta.rclone.org/v1.54.0-beta.5074.eb090d354/ has linux binaries
warning! rclone beta can be used to evaluate new features but it is unsupported! never use for production data!

@ncw thank you!

**Comment by ivandeex** [comment]
closing as all questions were answered
