### ISSUE TITLE
compress is failing code quality checks

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#4941]
In d8984cd37f62a220ba784e634a3328b47c19c64f a change was introduced which causes `make check` to fail and thus the build.

https://github.com/rclone/rclone/blob/0be69018b8498f2680263ccdbbf183e92012caf9/backend/compress/compress.go#L1224-L1236

This is failing the build with

```
$ make check
go build -v --ldflags "-s -X github.com/rclone/rclone/fs.Version=v1.54.0-beta.5072.0be69018b"  
mkdir -p `go env GOPATH`/bin/
cp -av rclone`go env GOEXE` `go env GOPATH`/bin/rclone`go env GOEXE`.new
'rclone' -> '/home/ncw/go/bin/rclone.new'
mv -v `go env GOPATH`/bin/rclone`go env GOEXE`.new `go env GOPATH`/bin/rclone`go env GOEXE`
renamed '/home/ncw/go/bin/rclone.new' -> '/home/ncw/go/bin/rclone'
-- START CODE QUALITY REPORT -------------------------------
backend/compress/compress.go:1227:6: ineffectual assignment to `ok` (ineffassign)
	do, ok := o.Object.(fs.SetTierer)
	    ^
make: *** [Makefile:87: check] Error 1
```

I can see the problem, `ok` is being assigned but not checked, so the `return do.SetTier(tier)` call might panic.

I'm not sure what the solution is though - should it be looking at that object at all?

Can you fix it @buengese ?

**Comment by buengese** [comment]
arghr. I should really not be merging things late at night. 

Well I think it should keep the same storage tier for the metadata and the actual file. If the metadata file supports setTier the data file will obviously do so to so the ok can safely be ignored which is was I meant to do here.
