### ISSUE TITLE
Update rclone to accomodate the latest changes in azure blob

### ISSUE THREAD

**Issue by abhi18av** [rclone/rclone#4946]
Hi rclone team,

First off, thanks for this great tool. I can't imagine working with cloud without `rclone`!

This issue is not so organized at the moment, however I'd just like to point out that the azcopy team would be updating the CLI to accomodate some peculiarities. For more information, this issue can be reffered 
https://github.com/Azure/azure-sdk-for-java/issues/18681

Once I've had some comments on this issue and the `azcopy` tool has settled on the specific direction - it'd be a good time to update `rclone` as well.

**Comment by ncw** [comment]
I think you are talking about updating this function

https://github.com/rclone/rclone/blob/b80d49830454c48bcb35be4668123e9aeeba761d/backend/azureblob/azureblob.go#L749-L762

From a brief skim over the issue I think that should allow rclone to recognize directory markers - but I may have missed something...

**Comment by abhi18av** [comment]
Hi @ncw , yes I think that should be it. Once I have a bit more clarity over the direction `azcopy` team is taking, I'll make a PR.

**Comment by ncw** [comment]
Great - thank you :-)

**Comment by abhi18av** [comment]
Based on the conversation on the `azcopy` side Azure/azure-sdk-for-java#18681, it seems there might be much that we can do on `rclone` or can we somehow override that behavior?

**Comment by ncw** [comment]
I think this issue doesn't have definite things to fix in rclone so I will close it for now.
