### ISSUE TITLE
Filenames with symbols, symbols get changed

### ISSUE THREAD

**Issue by RioSif** [rclone/rclone#4947]
rclone v1.53.3
- os/arch: linux/amd64
- go version: go1.15.5

Hello,
I'm using rclone to copy files from one onedrive account to another. rclone replaces the symbols of the filenames with similar symbols with other symbols.
If i copy the filename to word the font of the correct symbol is same as the letters and the font of the changed symbol is MS Gothic if that gives a clue...

Here are two screenshots:
https://i.imgur.com/JUwu3JJ.png
https://i.imgur.com/wAhsU6K.png
There is no space before the symbol # and theres just one space after the symbol # in both cases. Same happens with symbol ! and other symbols.
The issue is not present when i copy from backblaze b2 to onedrive

Thanks

**Comment by Cnly** [comment]
Hi @RioSif, the problem you described should have been fixed recently. Could you try [the latest beta](https://beta.rclone.org/)? Thanks!

**Comment by RioSif** [comment]
Prolbem Solved with the use of beta version v1.54.0-beta.5088.127f48e8a

Thanks very much!
