### ISSUE TITLE
rclone 1.54 compress function

### ISSUE THREAD

**Issue by Cloud-Zhang** [rclone/rclone#4949]
one question about the compress function. Base the rclone config a compress remote it can work. But if i don't want to add a compress remote instead of it . we have a S3 remote . and i want to use the command diresctly use the comrpess funciton . As the doc provided these options . But how should i make it the command even i am not add the compress remote ? For example there is a S3 remote called testS3. Now if i want to use the compress function . If the below command is right or not.

CMD:= **rclone copy dump.rdb testS3://test-compress/redis --compress-remote=testS3: --compress-mode=gzip -vvv**

**--compress-remote** Remote to compress.

Config: remote
Env Var: RCLONE_COMPRESS_REMOTE
Type: string
Default: ""

**--compress-mode Compression mode.**
Config: mode
Env Var: RCLONE_COMPRESS_MODE
Type: string
Default: "gzip"
Examples:
"gzip"
Standard gzip compression with fastest parameters.

**Comment by ncw** [comment]
> rclone copy dump.rdb testS3://test-compress/redis --compress-remote=testS3: --compress-mode=gzip -vvv

I think you want

rclone copy dump.rdb :compress:test-compress/redis --compress-remote=testS3: --compress-mode=gzip -vvv

**Comment by ivandeex** [comment]
question has been answered
