### ISSUE TITLE
webgui location unchanged when using --cache-dir flag

### ISSUE THREAD

**Issue by trumblejoe** [rclone/rclone#4951]
#### What is the problem you are having with rclone?
rclone mount --cache-dir string  will change the vfs cache directory location and the vfsMeta directory location but .cache/rclone/webgui will still be created in the same default location. When I used the command earlier I thought it was extremely unexpected behavior as I had expected the command to create a .cache directory containing all of those items in the specified location, instead I ended up with the webgui in the default .cache location and the vfs & vfsMeta directories created as two top-level independent directories in the location I had specified.

#### What is your rclone version (output from `rclone version`)
rclone v1.53.3
- os/arch: linux/amd64
- go version: go1.15.5

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Debian

####  Which cloud storage system are you using? (e.g. Google Drive)
NA

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone mount

**Comment by ncw** [comment]
Yes this sounds like a bug...

The cache path is set in an `init()` function before the cache flag has been read

https://github.com/rclone/rclone/blob/127f48e8ad3ef85dabfbdbe15ad9149a84a690e1/fs/rc/webgui/plugins.go#L71-L72

@negative0 do you want to have a go at fixing this?

**Comment by negative0** [comment]
Yes. I will do that!

**Comment by negative0** [comment]
@ncw Do we need to read cachePath every time we want to use it?

**Comment by ncw** [comment]
> @ncw Do we need to read cachePath every time we want to use it?

That is probably a good idea I think.
