### ISSUE TITLE
How to mount a ceph s3

### ISSUE THREAD

**Issue by yule-sun** [rclone/rclone#4954]
#### How do you think rclone should be changed to solve that?

I try to use the rclone mount a bucket in my ceph cluster. I config the rclone.conf and i can use the command "rclone lsd ceph:" to list he bucket on my server , but i cann't mount the ceph as a localdrive. Anything i was wrong? Please help.

PS C:\Windows\system32> .\rclone.exe lsd ceph:
          -1 2020-12-31 10:39:19        -1 sftp

PS C:\Windows\system32> rclone mount -vv ceph:files x: --allow-other
2021/01/25 15:52:59 DEBUG : rclone: Version "v1.53.4" starting with parameters ["C:\\Windows\\system32\\rclone.exe" "mou
nt" "-vv" "ceph:files" "x:" "--allow-other"]
2021/01/25 15:52:59 DEBUG : Creating backend with remote "ceph:files"
2021/01/25 15:52:59 DEBUG : Using config file from "C:\\Users\\F3640212\\.config\\rclone\\rclone.conf"
2021/01/25 15:52:59 INFO  : S3 bucket files: poll-interval is not supported by this remote
2021/01/25 15:52:59 DEBUG : S3 bucket files: Mounting on "x:"
2021/01/25 15:52:59 DEBUG : S3 bucket files: Mounting with options: ["-o" "fsname=ceph:files" "-o" "subtype=rclone" "-o"
 "max_readahead=131072" "-o" "attr_timeout=1" "-o" "atomic_o_trunc" "-o" "uid=-1" "-o" "gid=-1" "--FileSystemName=rclone
" "-o" "volname=ceph files" "-o" "allow_other"]
2021/01/25 15:52:59 DEBUG : S3 bucket files: Init:
2021/01/25 15:52:59 DEBUG : S3 bucket files: >Init:
2021/01/25 15:52:59 DEBUG : /: Statfs:
2021/01/25 15:52:59 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:274877906944 Bfree:274877906944 Bavail:27487
7906944 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2021/01/25 15:52:59 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/25 15:52:59 DEBUG : /: >Getattr: errc=0
2021/01/25 15:52:59 DEBUG : /: Readlink:
2021/01/25 15:52:59 DEBUG : /: >Readlink: linkPath="", errc=-40
The service rclone has been started.
2021/01/25 15:52:59 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/25 15:52:59 DEBUG : /: >Getattr: errc=0
2021/01/25 15:52:59 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/25 15:52:59 DEBUG : /: >Getattr: errc=0
2021/01/25 15:52:59 DEBUG : /: Opendir:
2021/01/25 15:52:59 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2021/01/25 15:52:59 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2021/01/25 15:52:59 DEBUG : /: >Opendir: errc=0, fh=0x0
2021/01/25 15:52:59 DEBUG : /: Releasedir: fh=0x0
2021/01/25 15:52:59 DEBUG : /: >Releasedir: errc=0
2021/01/25 15:52:59 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/25 15:52:59 DEBUG : /: >Getattr: errc=0
2021/01/25 15:52:59 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/25 15:52:59 DEBUG : /: >Getattr: errc=0
2021/01/25 15:52:59 DEBUG : /: Opendir:
2021/01/25 15:52:59 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2021/01/25 15:52:59 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2021/01/25 15:52:59 DEBUG : /: >Opendir: errc=0, fh=0x0
2021/01/25 15:52:59 DEBUG : /: Releasedir: fh=0x0
2021/01/25 15:52:59 DEBUG : /: >Releasedir: errc=0
2021/01/25 15:52:59 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/25 15:52:59 DEBUG : /: >Getattr: errc=0
2021/01/25 15:52:59 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/25 15:52:59 DEBUG : /: >Getattr: errc=0
2021/01/25 15:52:59 DEBUG : /: Opendir:
2021/01/25 15:52:59 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2021/01/25 15:52:59 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2021/01/25 15:52:59 DEBUG : /: >Opendir: errc=0, fh=0x0
2021/01/25 15:52:59 DEBUG : /: Releasedir: fh=0x0
2021/01/25 15:52:59 DEBUG : /: >Releasedir: errc=0

**Comment by ncw** [comment]
What went wrong? Everything looked OK in that log.

> rclone mount -vv ceph:files x: --allow-other

Note the `files` bucket doesn't exist according to

```
> .\rclone.exe lsd ceph:
-1 2020-12-31 10:39:19 -1 sftp
```

**Comment by yule-sun** [comment]
> What went wrong? Everything looked OK in that log.
> 
> > rclone mount -vv ceph:files x: --allow-other
> 
> Note the `files` bucket doesn't exist according to
> 
> ```
> > .\rclone.exe lsd ceph:
> -1 2020-12-31 10:39:19 -1 sftp
> ```

Sorry, I copy the wrong command, I create a bucket by myself use this command .
PS C:\Windows\system32> rclone mkdir ceph:photo

And i can see the bucket now.
PS C:\Windows\system32> rclone lsd ceph:
          -1 2021-01-25 15:57:18        -1 photo
          -1 2020-12-31 10:39:19        -1 sftp

But i cann't mount the bucket that named photo. I cann't see the volume X on my server.

PS C:\Windows\system32> rclone mount -vv ceph:photo x:
2021/01/26 08:10:04 DEBUG : rclone: Version "v1.53.4" starting with parameters ["C:\\Windows\\system32\\rclone.exe" "mou
nt" "-vv" "ceph:photo" "x:"]
2021/01/26 08:10:04 DEBUG : Creating backend with remote "ceph:photo"
2021/01/26 08:10:04 DEBUG : Using config file from "C:\\Users\\F3640212\\.config\\rclone\\rclone.conf"
2021/01/26 08:10:04 INFO  : S3 bucket photo: poll-interval is not supported by this remote
2021/01/26 08:10:04 DEBUG : S3 bucket photo: Mounting on "x:"
2021/01/26 08:10:04 DEBUG : S3 bucket photo: Mounting with options: ["-o" "fsname=ceph:photo" "-o" "subtype=rclone" "-o"
 "max_readahead=131072" "-o" "attr_timeout=1" "-o" "atomic_o_trunc" "-o" "uid=-1" "-o" "gid=-1" "--FileSystemName=rclone
" "-o" "volname=ceph photo"]
2021/01/26 08:10:04 DEBUG : S3 bucket photo: Init:
2021/01/26 08:10:04 DEBUG : S3 bucket photo: >Init:
2021/01/26 08:10:04 DEBUG : /: Statfs:
2021/01/26 08:10:04 DEBUG : /: >Statfs: stat={Bsize:4096 Frsize:4096 Blocks:274877906944 Bfree:274877906944 Bavail:27487
7906944 Files:1000000000 Ffree:1000000000 Favail:0 Fsid:0 Flag:0 Namemax:255}, errc=0
2021/01/26 08:10:04 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/26 08:10:04 DEBUG : /: >Getattr: errc=0
2021/01/26 08:10:04 DEBUG : /: Readlink:
2021/01/26 08:10:04 DEBUG : /: >Readlink: linkPath="", errc=-40
The service rclone has been started.
2021/01/26 08:10:04 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/26 08:10:04 DEBUG : /: >Getattr: errc=0
2021/01/26 08:10:04 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/26 08:10:04 DEBUG : /: >Getattr: errc=0
2021/01/26 08:10:04 DEBUG : /: Opendir:
2021/01/26 08:10:04 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2021/01/26 08:10:04 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2021/01/26 08:10:04 DEBUG : /: >Opendir: errc=0, fh=0x0
2021/01/26 08:10:04 DEBUG : /: Releasedir: fh=0x0
2021/01/26 08:10:04 DEBUG : /: >Releasedir: errc=0
2021/01/26 08:10:04 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/26 08:10:04 DEBUG : /: >Getattr: errc=0
2021/01/26 08:10:04 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/26 08:10:04 DEBUG : /: >Getattr: errc=0
2021/01/26 08:10:04 DEBUG : /: Opendir:
2021/01/26 08:10:04 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2021/01/26 08:10:04 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2021/01/26 08:10:04 DEBUG : /: >Opendir: errc=0, fh=0x0
2021/01/26 08:10:04 DEBUG : /: Releasedir: fh=0x0
2021/01/26 08:10:04 DEBUG : /: >Releasedir: errc=0
2021/01/26 08:10:04 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/26 08:10:04 DEBUG : /: >Getattr: errc=0
2021/01/26 08:10:04 DEBUG : /: Getattr: fh=0xFFFFFFFFFFFFFFFF
2021/01/26 08:10:04 DEBUG : /: >Getattr: errc=0
2021/01/26 08:10:04 DEBUG : /: Opendir:
2021/01/26 08:10:04 DEBUG : /: OpenFile: flags=O_RDONLY, perm=-rwxrwxrwx
2021/01/26 08:10:04 DEBUG : /: >OpenFile: fd=/ (r), err=<nil>
2021/01/26 08:10:04 DEBUG : /: >Opendir: errc=0, fh=0x0
2021/01/26 08:10:04 DEBUG : /: Releasedir: fh=0x0
2021/01/26 08:10:04 DEBUG : /: >Releasedir: errc=0

**Comment by yule-sun** [comment]
> What went wrong? Everything looked OK in that log.
> 
> > rclone mount -vv ceph:files x: --allow-other
> 
> Note the `files` bucket doesn't exist according to
> 
> ```
> > .\rclone.exe lsd ceph:
> -1 2020-12-31 10:39:19 -1 sftp
> ```

Hi 
   I can mount the ceph object storage to a local drive after i am reboot my server .
But a new problem is i use the command "rclone copy " to put some files to the remote, i cann't see it in the local drive .
And i can see it in my linux server. What's wrong? Can you help to fix it?

**Comment by yule-sun** [comment]
> What went wrong? Everything looked OK in that log.
> 
> > rclone mount -vv ceph:files x: --allow-other
> 
> Note the `files` bucket doesn't exist according to
> 
> ```
> > .\rclone.exe lsd ceph:
> -1 2020-12-31 10:39:19 -1 sftp
> ```

Hi 
   I can mount the ceph object storage as a local drive  after i reboot my server. But i got a new problem is 
I have no way to create a folder either through commands or Windows Explorer. I got an error like this when i'm use the command to create a floder.
2021/01/26 17:15:19 NOTICE: S3 bucket photo path 123: Warning: running mkdir on a remote which can't have empty director
ies does nothing

Another question is whether I can save all operation logs when mapped to a local disk？
Looking forward to your reply, and thanks you very much.

**Comment by ncw** [comment]
> I got an error like this when i'm use the command to create a floder.
> 2021/01/26 17:15:19 NOTICE: S3 bucket photo path 123: Warning: running mkdir on a remote which can't have empty director
> ies does nothing

That isn't an error...

You don't need to create directories for s3 storage, just write the file and it will work.



> Another question is whether I can save all operation logs when mapped to a local disk？

Use --log-file to save the logs.

**Comment by yule-sun** [comment]
> > I got an error like this when i'm use the command to create a floder.
> > 2021/01/26 17:15:19 NOTICE: S3 bucket photo path 123: Warning: running mkdir on a remote which can't have empty director
> > ies does nothing
> 
> That isn't an error...
> 
> You don't need to create directories for s3 storage, just write the file and it will work.
> 
> > Another question is whether I can save all operation logs when mapped to a local disk？
> 
> Use --log-file to save the logs.

Thank you very much for your reply. I can use the parameter '--log-file' to save the log, but after I install rclone as a service using nssm, there is no way to get the log. Is this the case? Or is I using incorrectly? ?

The config of NSSM is like this:
     Path：C:\Program Files\rclone\rclone.exe
     Startup Directory：C:\Program Files\rclone
     Arguments：mmount ceph_oss_ISD:photo s: --allow-other --vfs-cache-mode full --cache-dir c:\oss\vfs\ --config "C:\Program 
                           Files\rclone\rclone.conf" --log-file c:\oss\log\ceph_oss_ISD.log
     Service name：RcloneMount
     Detail→
	Display name: Rclone Mount Remotename
	Description: Automatically mount the remote name using rclone

**Comment by ncw** [comment]
> but after I install rclone as a service using nssm, there is no way to get the log. Is this the case? Or is I using incorrectly? ?

You should find the log at `c:\oss\log\ceph_oss_ISD.log` though you might want to make sure that directory / file is writable by the user you are running rclone with.

**Comment by yule-sun** [comment]
> You should find the log at `c:\oss\log\ceph_oss_ISD.log` though you might want to make sure that directory / file is writable by the user you are running rclone with.

Yes sir, I can see the log later, maybe the log level is not set, so only the log with error can be recorded. 
Another question, when I use robocopy to synchronize more than 50 million small files to the directory I mounted, I find that this action will seriously affect the speed of the server. Is there a good way?

The last modification time of the file uploaded to the object storage has changed. I don't know what happened and I look forward to your reply.

**Comment by ncw** [comment]
> Another question, when I use robocopy to synchronize more than 50 million small files to the directory I mounted, I find that this action will seriously affect the speed of the server. Is there a good way?

The best way is to use `rclone copy` directly to the ceph storage, not use `robocopy` to the `rclone mount`.  Using `rclone copy` directoy is much more efficient.

> The last modification time of the file uploaded to the object storage has changed. I don't know what happened and I look forward to your reply.

Please provide an example - thanks!

**Comment by yule-sun** [comment]
Thank you sir , I will try to use rclone copy to test it, but our developers want to map the bucket in s3 to the local, because their iis also wants to use this bucket directory. However, if i store more than 300,000 files in a directory, and then use rclone mount to open it locally, explorer.exe will be stucked. So I am still looking for other solutions.

Regarding the last modification time of the file, it looks like this

PS C:\Users\F3640212\Desktop> dir ADReplication.ps1.txt
    Directory: C:\Users\F3640212\Desktop
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       **11/20/2020   3:12 PM**           1608 ADReplication.ps1.txt

The last modification time of this file is 11/20/2020   3:12 PM，and then I use rclone copy to upload this file to the remote directory.
PS C:\Users\F3640212\Desktop> rclone copy .\ADReplication.ps1.txt ceph_oss_ISD:photo

When I view the information of this file in the Windows system, the last modification time of this file is correct.
PS C:\Users\F3640212\Desktop> rclone lsl ceph_oss_ISD:photo/ADReplication.ps1.txt
     1608 2020-11-20 15:12:36.198741700 ADReplication.ps1.txt

But when I check the information of this file in linux, his time becomes upload time.
[root@ceph-centosclient01 ~]# s3cmd ls s3://photo/
                          DIR  s3://photo/SysUpFile/
                          DIR  s3://photo/test/
**2021-01-29 00:31         1608  s3://photo/ADReplication.ps1.txt**
2021-01-27 09:53         1652  s3://photo/FTPs127certificate.crt
Did I make a mistake?

**Comment by ncw** [comment]
> Thank you sir , I will try to use rclone copy to test it, but our developers want to map the bucket in s3 to the local, because their iis also wants to use this bucket directory. However, if i store more than 300,000 files in a directory, and then use rclone mount to open it locally, explorer.exe will be stucked. So I am still looking for other solutions.

You could do multiple mounts using `--include` so one mount for `a-c` one for `d-f` etc.

> Regarding the last modification time of the file, it looks like this
> 
> PS C:\Users\F3640212\Desktop> dir ADReplication.ps1.txt
> Directory: C:\Users\F3640212\Desktop
> Mode LastWriteTime Length Name
> 
> -a---- **11/20/2020 3:12 PM** 1608 ADReplication.ps1.txt
> 
> The last modification time of this file is 11/20/2020 3:12 PM，and then I use rclone copy to upload this file to the remote directory.
> PS C:\Users\F3640212\Desktop> rclone copy .\ADReplication.ps1.txt ceph_oss_ISD:photo
> 
> When I view the information of this file in the Windows system, the last modification time of this file is correct.
> PS C:\Users\F3640212\Desktop> rclone lsl ceph_oss_ISD:photo/ADReplication.ps1.txt
> 1608 2020-11-20 15:12:36.198741700 ADReplication.ps1.txt
> 
> But when I check the information of this file in linux, his time becomes upload time.
> [root@ceph-centosclient01 ~]# s3cmd ls s3://photo/
> DIR s3://photo/SysUpFile/
> DIR s3://photo/test/
> **2021-01-29 00:31 1608 s3://photo/ADReplication.ps1.txt**
> 2021-01-27 09:53 1652 s3://photo/FTPs127certificate.crt
> Did I make a mistake?

You can't set the upload time of a file with the s3 API and that is what `s3cmd` reads.

If you try reading the time with `rclone` you should see it is correct

    rclone lsl ceph_oss_ISD:photo

Rclone stores the modtime as some extra metadata on the object.

**Comment by yule-sun** [comment]
> > Thank you sir , I will try to use rclone copy to test it, but our developers want to map the bucket in s3 to the local, because their iis also wants to use this bucket directory. However, if i store more than 300,000 files in a directory, and then use rclone mount to open it locally, explorer.exe will be stucked. So I am still looking for other solutions.
> 
> You could do multiple mounts using `--include` so one mount for `a-c` one for `d-f` etc.
> 
> > Regarding the last modification time of the file, it looks like this
> > PS C:\Users\F3640212\Desktop> dir ADReplication.ps1.txt
> > Directory: C:\Users\F3640212\Desktop
> > Mode LastWriteTime Length Name
> > -a---- **11/20/2020 3:12 PM** 1608 ADReplication.ps1.txt
> > The last modification time of this file is 11/20/2020 3:12 PM，and then I use rclone copy to upload this file to the remote directory.
> > PS C:\Users\F3640212\Desktop> rclone copy .\ADReplication.ps1.txt ceph_oss_ISD:photo
> > When I view the information of this file in the Windows system, the last modification time of this file is correct.
> > PS C:\Users\F3640212\Desktop> rclone lsl ceph_oss_ISD:photo/ADReplication.ps1.txt
> > 1608 2020-11-20 15:12:36.198741700 ADReplication.ps1.txt
> > But when I check the information of this file in linux, his time becomes upload time.
> > [root@ceph-centosclient01 ~]# s3cmd ls s3://photo/
> > DIR s3://photo/SysUpFile/
> > DIR s3://photo/test/
> > **2021-01-29 00:31 1608 s3://photo/ADReplication.ps1.txt**
> > 2021-01-27 09:53 1652 s3://photo/FTPs127certificate.crt
> > Did I make a mistake?
> 
> You can't set the upload time of a file with the s3 API and that is what `s3cmd` reads.
> 
> If you try reading the time with `rclone` you should see it is correct
> 
> ```
> rclone lsl ceph_oss_ISD:photo
> ```
> 
> Rclone stores the modtime as some extra metadata on the object.

Thank you very much, I can get the information I need. But there are new problems to trouble you.
When I use nssm to install rclone as a service, the mapped disk cannot be written to files using explorer.exe of windows, and can only be written using the rclone command. Is there another parameter that only has incremental backup? Looking forward to your reply, thank you.

**Comment by ncw** [comment]
I suggest you ask your question on [the rclone forum](https://forum.rclone.org/) - you'll get a great answer there from Windows experts (not me!)

As this has diverged from being a bug report, I'm going to close this issue.
