### ISSUE TITLE
s3/v2Auth:  copy multipart failed with 'SignatureDoesNotMatch' 

### ISSUE THREAD

**Issue by zhucan** [rclone/rclone#4961]
#### What is the problem you are having with rclone?
s3:  copy multipart failed with 'SignatureDoesNotMatch' (with v2 auth)

#### What is your rclone version (output from `rclone version`)
![image](https://user-images.githubusercontent.com/13997135/105820421-813f4b80-5ff4-11eb-911b-0a6baaa68a48.png)

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
CentOS Linux release 7.4.1708 (Core)

####  Which cloud storage system are you using? (e.g. Google Drive)
ceph

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
./rclone sync lzn_target:lzn-desbk2/.3dsRecycle/20210125/10Gfile.20210125-200531 lzn_target:lzn-desbk2 --bwlimit Sunday-00:00,20M --checkers 16 --transfers 8 --checksum --ignore-errors --log-level DEBUG --log-file /var/log/xdrs/replication-replicate-plan55.log --stats 500ms --stats-one-line --stats-log-level DEBUG --retries 1 --retries-sleep 500ms 

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
![image](https://user-images.githubusercontent.com/13997135/105820621-be0b4280-5ff4-11eb-890f-454a4beb7a8e.png)
[replication-replicate-plan55.log](https://github.com/rclone/rclone/files/5872125/replication-replicate-plan55.log)

@ncw

**Comment by zhucan** [comment]
https://github.com/rclone/rclone/blob/cd075f1703afbc369424491da9e156ad6f5a7d8f/backend/s3/v2sign.go#L73 

I don't understand why we sort by ascending but not descending. 

I had tested on it. The "x-amz-copy-source-range" must behind the "x-amz-copy-source", After I modify the sort function with "sort.Sort(sort.Reverse(sort.StringSlice(headersToSign)))", it's successful. Please take a look at this doc:https://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html

Not modify:
![image](https://user-images.githubusercontent.com/13997135/105821745-2575c200-5ff6-11eb-8560-41f52e6dd870.png)

After modify:
![image](https://user-images.githubusercontent.com/13997135/105822193-bc427e80-5ff6-11eb-8135-008a34485fe6.png)

@ncw

**Comment by zhucan** [comment]
Can only sort 'headersToSign' by key. @ncw  I had tested it

**Comment by ncw** [comment]
Do you want to send a pull request to fix this?

**Comment by zhucan** [comment]
> Do you want to send a pull request to fix this?

ok

**Comment by ncw** [comment]
This was fixed in cdaea629326ee6254ca62db74c80d8b33210ff8b - thank you @zhucan
