### ISSUE TITLE
compress all files in folder with one archive 

### ISSUE THREAD

**Issue by wangshuang0220** [rclone/rclone#4964]
May i know the compress function in v1.54 , can  compress all files in folder with one archive ?

example:
there are 3 files [a,b,c] in directory [test], i want to get only one compressed file [test.XXxxx.gz] , this compressed file includes [a,b,c]

**Comment by ivandeex** [comment]
no

**Comment by ncw** [comment]
This isn't possible directly at the moment.

You can do this though

    tar zcvf - files | rclone rcat remote:test.tar.gz

**Comment by wangshuang0220** [comment]
got it , tks
