### ISSUE TITLE
[compress feature]there are some issue  when copy remote files to local with compress

### ISSUE THREAD

**Issue by wangshuang0220** [rclone/rclone#4969]
when copy remote files to local with compress,then met some error as below:

 ERROR : Attempt 1/3 failed with 3 errors and: multipart copy: read failed: flate: corrupt input before offset 3607\n2021/01/27 18:54:32

Failed to copy with 3 errors: last error was: multipart copy: read failed: flate: corrupt input before offset 3607

**Comment by ivandeex** [comment]
@wangshuang0220 
Please fill bug template.
We will not reproduce your bug without more data.

**Comment by ivandeex** [comment]
https://github.com/rclone/rclone/issues/4965 is a good example

Please show your interest in resolving the bug, follow the submit process.

**Comment by ncw** [comment]
I think @wangshuang0220 has resubmitted this here #4970 so I'll close this one.
