### ISSUE TITLE
Update the snap package of rclone

### ISSUE THREAD

**Issue by simos** [rclone/rclone#4971]
#### What is the problem you are having with rclone?

The available snap package of rclone is too old. It is version 1.36 from 2017.

```
$ snap info rclone
name:      rclone
summary:   rsync for cloud storage
publisher: –
store-url: https://snapcraft.io/rclone
license:   unset
description: |
  Rclone is a command line program to sync files to and from cloud storage
  providers such as Google Drive, Amazon Drive, S3, Dropbox, Backblaze B2,
  OneDrive, Swift, Hubic, Cloudfiles, Google Cloud Storage, Yandex Files.
commands:
  - rclone
channels:
  latest/stable:    1.36   2017-07-19 (466)  6MB -
  latest/candidate: ↑                            
  latest/beta:      ↑                            
  latest/edge:      ↑                            
$ 
```

#### What is your rclone version (output from `rclone version`)

1.37

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Ubuntu 20.04

#### How to update the snap package and make it better

1. `rclone` requires access to the filesystem outside of $HOME. Therefore, it has a case for `classic` confinement for snap packages. Currently, the snap package uses the `strict` confinement, though an informed user can bypass it and install with `--classic`. However, the snap package should be configured with `classic` confinement and that should be the default. 
2. To get your snap package accepted with the `classic` confinement, you have to request it on the forum.snapcraft.io forum. See, for example, this request, https://forum.snapcraft.io/t/request-classic-confinement-for-czkawka/22200
3. The instructions on what can be made `classic` and what not, can be found at https://forum.snapcraft.io/t/process-for-reviewing-classic-confinement-snaps/1460 My understanding is that `rclone` falls under `cloud agents`.

**Comment by ivandeex** [comment]
This issue is related to #4193 and older _snap_ package requests (now closed)

https://github.com/rclone/rclone/issues/4193#issuecomment-622920991 said

> I'm looking for someone to support snaps if anyone felt like volunteering

@simos
Do you want to maintain snap package for rclone?
We are still looking for volunteers :pray:

**Comment by ncw** [comment]
I opened a thread on this on the snapcraft forum a while back: https://forum.snapcraft.io/t/rclone-snap-delete-or-update/18560

**Comment by soredake** [comment]
Having snap updated would help with https://github.com/rclone/rclone/issues/3980

**Comment by boukendesho** [comment]
@ivandeex hello team, I have some experience in packaging snaps and I'm willing to become a maintainer for rclone snap package. Could you please guide me on how to proceed?

**Comment by ncw** [comment]
@boukendesho that would be great. What do you need from us?

**Comment by boukendesho** [comment]
@ncw hi, i would like to create a new repository under my account to maintain snap-related files, keeping it separate from the official repository. I need an official statement to obtain ownership of the name 'rclone' in the current snap store. I'm not sure if this way is ok for official team?

**Comment by boukendesho** [comment]
@ncw If it is allowed, i will post a issue like this: [Request for snap maintenance](https://github.com/FreeTubeApp/FreeTube/issues/3525)

**Comment by ncw** [comment]
That would be fine with me @boukendesho you have my blessing!

**Comment by boukendesho** [comment]
@ncw Thank you sir! I just open the issue https://github.com/rclone/rclone/issues/7221
