### ISSUE TITLE
Why need to 'Re-read metadata' again?

### ISSUE THREAD

**Issue by zhucan** [rclone/rclone#4973]
https://github.com/rclone/rclone/blob/7a496752f32edc147576939d89926f42466e94d5/backend/local/local.go#L1186

After exec "lstat" in SetModTime func, why need to exec "lstat" again?

**Comment by ncw** [comment]
We read the actual time set which may be different because not all filesystems can store the nS precision that rclone uses.

**Comment by ivandeex** [comment]
Closing as question was answered
