### ISSUE TITLE
One-drive repeat uploading when the folder or file includes "#" and "%"

### ISSUE THREAD

**Issue by yu-yuxuan** [rclone/rclone#4995]
#### What is the problem you are having with rclone?

One-drive repeat uploading when the folder or file includes "#" and "%"

#### What is your rclone version (output from `rclone version`)

1.54.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Mac os 64 bit

####  Which cloud storage system are you using? (e.g. Google Drive)

One drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone copy /tmp remote:tmp`

Currently, I have two folders with "COTTON100%" in the same directory

**Comment by darthShadow** [comment]
Can you please add the debug logs obtained by adding `-vv` to the command too?

**Comment by yu-yuxuan** [comment]
> Can you please add the debug logs obtained by adding `-vv` to the command too?

There is no error occurred. I am not sure which debug logs I need to paste. The strange things happen when we use rclone 1.54 while it reuploads the file and folder which contains "#" and "%".
![image](https://user-images.githubusercontent.com/8485699/106699313-9dbd2400-65b0-11eb-8287-a8f918dfaeb7.png)

**Comment by darthShadow** [comment]
This is probably related: https://forum.rclone.org/t/problem-with-beta-and-special-character/22047

Can you try after adding the encoding mentioned there i.e. `--onedrive-encoding Slash,LtGt,DoubleQuote,Colon,Question,Asterisk,Pipe,BackSlash,Del,Ctl,LeftSpace,LeftTilde,RightSpace,RightPeriod,InvalidUtf8,Dot,Hash,Percent`?

This should be added to whatever rclone command you are running.

**Comment by yu-yuxuan** [comment]
Thank you very much. I got it.
