### ISSUE TITLE
Add example of Windows FileSecurity in the mount docs

### ISSUE THREAD

**Issue by ivandeex** [rclone/rclone#4997]
Originally posted by @jeaneric in https://github.com/rclone/rclone/issues/4717#issuecomment-772738956

I would like the below solution added in the rclone mount documentation (Windows section).

> I'm mounting a remote to my file system.
```
rclone mount --config ./file.txt --file-perms 700 --dir-perms 700 --default-permissions --vfs-cache-mode full encrypt-remote: C:\...\foldername
```

> This works fine. I have access to the files and the permissions looks almost ok, but "Everyone" seems to get some permissions not specified! The 700 works ok and the permission (read-wirte) is really only to my current user which is fine. The real problem I have is when I use the files that are ssh key in visual studio code I have this error:

![image](https://user-images.githubusercontent.com/429638/97485710-d6ee5400-1930-11eb-9f6d-c87ffe46111f.png)

> I tried to change them permissions, to remove the everyone entry, but not working (no error but when reopening the properties, it's still there). I also tried to mount on a separate drive (X:\) but same problem. My best guest is that the "Everyone" entry in the security of the file cause the problem. I've tried various option, none were successful to remove it. Can it be removed?

[snip]

> @billziss-gh Thanks a lot for making this. It now works. Here are the details:

```
-o FileSecurity="D:P(A;;FA;;;<your-SID>)";
```

> So in .bat file, I'm doing something like that to avoid hard code the user SID:

```
@REM https://stackoverflow.com/a/30117236/140384
for /F "tokens=2" %%i in ('whoami /user /fo table /nh') do set usersid=%%i
rclone mount -o FileSecurity="D:P(A;;FA;;;%usersid%)" --vfs-cache-mode full encrypt-remote: C:\...\foldername
```

> Now Only my user has rights to the file:

![image](https://user-images.githubusercontent.com/429638/106924772-6bf5ab80-66dd-11eb-92ed-c74e6c69bf60.png)

**Comment by ncw** [comment]
@albertony - you did a great job on the rclone mount docs - what do you think about this?

**Comment by albertony** [comment]
Sure. Should be mentioned in the existing [Windows filesystem permissions](https://rclone.org/commands/rclone_mount/#windows-filesystem-permissions) section. Seems we have all the necessary information from the linked issue, so shouldn't be too much work. Still "only" in the beta version of WinFsp, though, so it won't reach the absolute top of my priority list just yet (but will probably have a go at it within a a week or two, if noone else does, and I don't forget)..

**Comment by billziss-gh** [comment]
@albertony unrelated to this issue, but I just noticed this in your link:

> WinFsp does not support extended attributes, see this

Just to let you know that WinFsp does support extended attributes now (and so does cgofuse). I need to update that NTFS compatibility page where it says otherwise.
