### ISSUE TITLE
Nextcloud - "The document was saved outside the editor. The changes could not be applied." 

### ISSUE THREAD

**Issue by userofgithub023897** [rclone/rclone#5003]
Hi,

my problem as described

### Expected behaviour 
Use the tool "**rclone**" to send files (*.md) via webdav to my Nextcloud so I can use the current version of the file there.

### Actual behaviour
Use the tool "**rclone**" to send files (*.md) via webdav to my Nexcloud.

rclone - no error pop up during transfer done via Terminal.

Nextcloud shows the error:

**EN**: "The document was saved outside the editor. The changes could not be applied."  

On the bottom in Nextcloud two options appear:

**EN**: "Use current version" & "Use the saved version"

When I click "*Use the save version*" then the current version which I uploaded via *rclone* is available on Nextcloud after one or two seconds. 

If I click the other option, then the uploaded version will be ignored and the "old" version is displayed on Nextcloud.

In rclone I use the webdav address provided by the Nextcloud in the format "https://nextcloud.xy/nextcloud/remote.php/dav/files/username/"

Is there an option to skip the question "*Use current version" & "Use the saved version*" so that Nextcloud always uses the newly uploaded version.

If this is related to version control it would be great to have the possibility to deactivate it by main folder and not globally for the whole Nextcloud installation.

  
#### What is your rclone version (output from `rclone version`)
rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.14.4

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Raspbian GNU/Linux 10 (buster)"

####  Which cloud storage system are you using? (e.g. Google Drive)
Nextcloud 20.0.7

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
*rclone sync ...* 
command works to transfer date properly to Nextcloud

**Comment by darthShadow** [comment]
Can you please retry with the latest version i.e. 1.54 and add the debug logs from there if you still encounter the error?

**Comment by userofgithub023897** [comment]
**Previous version was installed from OS repository**

```sudo apt install rclone```


```
~$ apt-cache policy rclone
rclone:
  Installed: 1.50.2-3
  Candidate: 1.50.2-3
  Version table:
 *** 1.50.2-3 500
        500 http://de.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
        100 /var/lib/dpkg/status
```


**New rclone version**
```
rclone version
rclone v1.54.0
- os/arch: linux/amd64
- go version: go1.15.7
```

Installed with command provided in documentation
```curl https://rclone.org/install.sh | sudo bash```


**Command to run rclone**
```rclone sync --log-file=logfilev1.54.0.txt --log-level DEBUG localstorage:/home/dev/folder/ nextcloud:/destinationfolder/```


**Log File**
```
2021/02/09 16:12:47 DEBUG : rclone: Version "v1.54.0" starting with parameters ["rclone" "sync" "--log-file=logfilev1.54.0.txt" "--log-level" "DEBUG" "localstorage:/home/dev/folder/" "nextcloud:/destinationfolder/"]
2021/02/09 16:12:47 DEBUG : Using config file from "/home/dev/.config/rclone/rclone.conf"
2021/02/09 16:12:47 DEBUG : Creating backend with remote "localstorage:/home/dev/folder/"
2021/02/09 16:12:47 DEBUG : Creating backend with remote "nextcloud:/destinationfolder/"
...
2021/02/09 16:12:47 DEBUG : README.md: Sizes differ (src 210 vs dst 263)
...
2021/02/09 16:12:49 DEBUG : README.md: SHA-1 = 2222222222222222222222222222222222222222 OK
2021/02/09 16:12:49 INFO  : README.md: Copied (replaced existing)
2021/02/09 16:12:49 DEBUG : Waiting for deletions to finish
2021/02/09 16:12:49 INFO  : 
Transferred:   	       210 / 210 Bytes, 100%, 98 Bytes/s, ETA 0s
Checks:                45 / 45, 100%
Transferred:            1 / 1, 100%
Elapsed time:         2.5s

2021/02/09 16:12:49 DEBUG : 21 go routines active
```


**Actual behaviour**
Problem still exists as described above. Nextcloud still says
***"The document was saved outside the editor. The changes could not be applied."***

On the bottom in Nextcloud two options appear:

*** "Use current version" & "Use the saved version"***

**Comment by darthShadow** [comment]
You can try this: https://help.nextcloud.com/t/how-can-i-disable-versioning-entirely/78009

**Comment by userofgithub023897** [comment]
## Nextcloud - Deactivate *version_retention_obligation*

I edited the Nextcloud *config.php* as described in the official Nextcloud manual
[https://docs.nextcloud.com/server/20/admin_manual/configuration_files/file_versioning.html](https://docs.nextcloud.com/server/20/admin_manual/configuration_files/file_versioning.html)

```
'versions_retention_obligation' => 'disable',
```

I started the *rclone* process again for a README.md file and encountered the same issue as described above.
Nextcloud asked which version it should use.

So I tried an other file named *doc.php* with some blabla in it.

I ran the sync with *rclone*, edited the file and ran rclone a second time. The file was always correct on Nextcloud.
The two options you can choose were not displayed.

So maybe this issue is related to md files in general or to md files named *README.md* in particular.


## What I did next

1. I removed the 
```
'versions_retention_obligation' => 'disable',
```

from the `config.php` again.

2. Created a new file *test.md*

3. Deactivated the *"Umfangreiche Arbeitsbereiche anzeigen"* (engl. *"Extensive work areas display"*) on Nextcloud

4. Started *rclone* 

5. Made changes to *test.md*

6. Started *rclone* again

7. Nextcloud - checked the file and it worked. The file version from rclone was displayed properly.

So this process worked for me. It is strange that Nextcloud don´t accept md files which are synced via WebDav and still requires the edit process made by the built in editor.

On *help.nextcloud.com* I found a solution to deactivate the *"Extensive work areas display"* globally for each and every user. 
[https://help.nextcloud.com/t/wie-umfangreiche-arbeitsbereiche-standardmasig-de-aktivieren/73799](https://help.nextcloud.com/t/wie-umfangreiche-arbeitsbereiche-standardmasig-de-aktivieren/73799)


There is also an app "*README.md*" available for Nextcloud that shows the *README.md* in GitHub style 
[https://apps.nextcloud.com/apps/files_readmemd](https://apps.nextcloud.com/apps/files_readmemd)

Maybe this could be an option to fix the issue or which causes the problem. 
I haven´t checked that yet.

**Comment by ivandeex** [comment]
@darthShadow 
This seems like a Nextcloud configuration issue.
I think this support request can be closed.
