### ISSUE TITLE
An error in mounting 21vianet OneDrive in version 1.54.0

### ISSUE THREAD

**Issue by 572615681** [rclone/rclone#5004]
I use version 1.54.0. When I mount OneDrive 21vianet on a Linux server without a graphical interface, I use the 【rclone authorize "onedrive" - "client ID" "secret"】 command to get the token on Windows, and the software will Jump to the login interface of OneDrive Globe (microsoftonline.com) instead of 21vianet's login interface (microsoftonline.cn)

**Comment by darthShadow** [comment]
Please add your redacted config. From a guess, you probably forgot to specify the region in your config.

https://rclone.org/onedrive/#onedrive-region

**Comment by 572615681** [comment]
[https://spcn.cyanlemon.net/onedrive/share/%E6%81%B0%E9%A5%AD%E5%9B%BE/Rclone/1.jpg](url)
[https://spcn.cyanlemon.net/onedrive/share/%E6%81%B0%E9%A5%AD%E5%9B%BE/Rclone/2.jpg](url)
[https://spcn.cyanlemon.net/onedrive/share/%E6%81%B0%E9%A5%AD%E5%9B%BE/Rclone/3.jpg](url)

In these pictures, I have captured several key configuration processes

**Comment by ivandeex** [comment]
![1](https://user-images.githubusercontent.com/9028053/107892221-c7713600-6f34-11eb-9a3b-7e9f654f06ed.jpg)

![2](https://user-images.githubusercontent.com/9028053/107892228-cdffad80-6f34-11eb-95c2-80f0ac45a3d8.jpg)

![3](https://user-images.githubusercontent.com/9028053/107892233-d3f58e80-6f34-11eb-82ba-9d315fa96140.jpg)

**Comment by ivandeex** [comment]
@darthShadow
do you understand anything???

**Comment by darthShadow** [comment]
No, the procedure seems to be correct from what I can understand unless I am missing something trivial.

@ncw ?

**Comment by ncw** [comment]
> I use version 1.54.0. When I mount OneDrive 21vianet on a Linux server without a graphical interface, I use the 【rclone authorize "onedrive" - "client ID" "secret"】 command to get the token on Windows, and the software will Jump to the login interface of OneDrive Globe (microsoftonline.com) instead of 21vianet's login interface (microsoftonline.cn)

Can you try your configuration using the copy the config file method: https://rclone.org/remote_setup/#configuring-by-copying-the-config-file

I think `rclone authorize` will be trying to use the wrong provider.

I think we need to add more parameters to the rclone authorize prompt which include the oauth server and maybe other details...

I came across another backend with this problem recently - dropbox with "impersonate" set.

So I think we should probably add clientId/ClientSecret/oauth server/scopes into `rclone authorize`.

Anyway can you try using the copy the config method @572615681 ?

**Comment by 572615681** [comment]
@ncw Although I did not test this method, I tried a similar method before. I completed the configuration on the local computer first, and got the 【access_token】 when I finally confirmed it. I filled the 【access_token】 into the remote server’s 【result】, Finally, the configuration process was successfully completed, and it can be used normally after testing.

**Comment by abc1763613206** [comment]
@ncw Same problem. If you use `rclone authorize` to remotely authorize, it will redirect you to `login.microsoftonline.com` ,instead of `login.partner.microsoftonline.cn` which is the true endpoint.    

Maybe we need more parameters?

**Comment by abc1763613206** [comment]
P.S. It works when you authorize locally and copy the config to the remote machine directly.

**Comment by ivandeex** [comment]
Resolved. Closing.
