### ISSUE TITLE
vfs/mount: minio over rclone, linked folder access failed

### ISSUE THREAD

**Issue by connected201** [rclone/rclone#5005]
OS version: windows 10, x64
rclone version: v1.54.0 - 2021-02-02
minio version: RELEASE.2021-02-07T01-31-02Z
Hi, i mounted dropbox and i try to make minio server D:\drop\dropbox
"D:\drop\dropbox" is mounted dropbox path, but minio cannot access this directory!
Manually with explorer i can copy files to my mounted dropbox path, and delete them
![image](https://user-images.githubusercontent.com/20506433/107370944-4d801d80-6aec-11eb-8626-ad650f6a707e.png)
how to fix it? best regards

**Comment by darthShadow** [comment]
Please specify your rclone mount command.

**Comment by connected201** [comment]
> 
> 
> Please specify your rclone mount command.

i mounter dropbox using Web GUI
![image](https://user-images.githubusercontent.com/20506433/107372074-aef4bc00-6aed-11eb-9c86-6f5f4fd243b9.png)

**Comment by connected201** [comment]
Maybe trouble is in symlink? i read somewhere that minio don't support symlink.

**Comment by ivandeex** [comment]
> Maybe trouble is in symlink?

Yes

#4933
