### ISSUE TITLE
Support for Get/Telia Sky

### ISSUE THREAD

**Issue by larsvinc** [rclone/rclone#5016]
#### What is your current rclone version (output from `rclone version`)?
rclone v 1.54

#### What problem are you are trying to solve?
Trying to use Telia Sky - used to be called "Get Sky". This has been an issue before:
https://github.com/rclone/rclone/issues/3818

#### How do you think rclone should be changed to solve that?
Add a config option under yottacloud with support for Telia Sky?

**Comment by larsvinc** [comment]
@patriknordlen Look at https://github.com/rclone/rclone/issues/3818

It seems to me that the token scheme is the same, but that some different address is needed?

**Comment by buengese** [comment]
As you've correctly identified we initially got getsky working with #3831. Given It's not working anymore it's likely they changed something on their end. Could you provide us a full log of your authentication attempt? Run `rclone config -vv --dump=bodies --log-file=getsky.log` and try to create a new backend.

**Comment by larsvinc** [comment]
@buengese Is the solution from #3831 in the main releases now, i.e. in 1.54. getsky.log attached (albeight with secrets removed).

[getsky.log](https://github.com/rclone/rclone/files/5968249/getsky.log)

**Comment by buengese** [comment]
Ah ok so you are using legacy authentication. Doesn't getsky offer token authentication?
The error suggest that the endpoint isn't correct for getsky or that legacy authentication is no longer supported. Does getsky offer an official client?

**Comment by larsvinc** [comment]
@buengese You are spot on. Telia sky is using tokens, and I had to delete the endpoint, and re-establish it using tokens. It now works. Thank you for the patience and support!
