### ISSUE TITLE
docs: dead link to uploadfile command

### ISSUE THREAD

**Issue by edwardxml** [rclone/rclone#5033]
#### What is the problem you are having with rclone?

The documentation page at https://rclone.org/rc contains a link to https://rclone.org/commands/rclone_uploadfile/ that is a dead link. I couldn't immediately find a suitable documented command in rclone/docs/content/commands to point it at and the sentence wouldn't make sense if I deleted the link. 
#### What is your rclone version (output from `rclone version`)

Rclone website at 1.54.0, 16 Feb 2021

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

N/a

####  Which cloud storage system are you using? (e.g. Google Drive)

N/a

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

N/a

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

N/a

**Comment by albertony** [comment]
I can't find anything it should point to either.. Not familiar with rc, but looking at code the uploadfile method just streams the file data from the http request into an [rcat](https://rclone.org/commands/rclone_rcat/) command. Perhaps just remove the sentence with the link in it? Could maybe replace it with a note or link about how to send the multipart form-data content. Seems @negative0 implemented this, so don't know if you have som input?

**Comment by ncw** [comment]
I think that the sentence ` See the uploadfile command command for more information on the above.` is a copy pasta error and should be deleted. I don't think there is an analogue of the rc call to link to.
