### ISSUE TITLE
Fuse & rclone's permission options broken?

### ISSUE THREAD

**Issue by lejeczek** [rclone/rclone#5042]
#### What is the problem you are having with rclone?
With command as below system ends up reporting mount like this:

-> $ llr /0-cloud.storage/dropbox/
ls: cannot access '/0-cloud.storage/dropbox/me': Permission denied
total 0
d????????? ? ? ? ?            ? me

Ugly?
Now, with one, well two changes - and that is quite nasty, unexpected behaviour.
Add/use:
--allow-other (and 'user_allow_other', obviously)
and you end up getting, or rather seeing:

-> $ llr /0-cloud.storage/dropbox/
total 0
drwx------. 1 me me 0 Feb 18 09:12 me

but! (big but), any user, every user who has rX to the partent (/0-cloud.storage/dropbox) have full access to that seemingly 700 dir.

Surely that must not be by design? 
regards, L

#### What is your rclone version (output from `rclone version`)
rclone-1.55.0.beta.5175.aee3bfb17.fix.dropbox.scopes-1.x86_64

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Centos Stream
Fedora 33

####  Which cloud storage system are you using? (e.g. Google Drive)
Dropbox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
-> $ rclone mount secret-us-full:me /0-cloud.storage/dropbox/me --config /etc/rclone/.me/dropbox.conf \
  --dir-perms 0700 \
  --file-perms 0600 \
  --umask 0077 \
  --dir-cache-time 168h \
  --timeout 1h \

**Comment by lejeczek** [comment]
The problem described is rather of critical nature. Can someone of devel comment please.

**Comment by darthShadow** [comment]
Unless I am misunderstanding something, the observed behaviour is as expected of fuse filesystems. 

Check the details of exactly what `allow_other` does here: https://manpages.debian.org/stretch/fuse/mount.fuse.8.en.html

**Comment by lejeczek** [comment]
If those are "limitations" of other dependencies or even rclone itself and not bugs in traditional meaning of the word then I'd suggest the following - warn the rest of us regular folks, users/admins in, ideally in man pages or places such as, eg. 'rclone mount --help' (I do not give a toss about Windows thus won't dare to suggest how to do it there)
Currently most of us (I'm sure cannot be unique in this) get false! impression that '--dir-perms' & '--file-perms' are the **only** bits which do the trick and nothing else is to worry of, which in multi-user setups if overlooked will lead to nasty things.
regards, L.

**Comment by darthShadow** [comment]
It is not a limitation or a bug given that's the exact purpose of the flag and the corresponding option in /etc/fuse.conf. And as you saw, the documentation for the fuse already has those details.

Even the rclone docs have this mentioned:

```
--allow-other                            Allow access to other users. Not supported on Windows.
```
