### ISSUE TITLE
 --print-progress-title with sync?

### ISSUE THREAD

**Issue by orschiro** [rclone/rclone#5044]
In reference to https://github.com/rclone/rclone/issues/4187#issuecomment-781378317, opening this ticket:

```
2021/02/18 08:05:02 Fatal error: unknown flag: --print-progress-title
rclone sync "/home/orschiro/GoogleDrive" "orschiro4:Shared/orschiro4@gmail.com/X230" --skip-links --progress --print-progress-title
```

**Comment by darthShadow** [comment]
The flag is `--progress-terminal-title`, not `--print-progress-title`.

The current implementation should work for sync too.

**Comment by xd003** [comment]
I just tried this too and doesn't seem to work for me as well
Am I missing something here ?
![Screenshot_20210218-225323~2](https://user-images.githubusercontent.com/26503185/108395902-44a1f100-723c-11eb-81ef-956263c42e77.jpg)

**Comment by darthShadow** [comment]
Does this: `echo -ne "\033]0;test string\007" ; sleep 2` update your terminal title to "test string"?

**Comment by xd003** [comment]
> Does this: `echo -ne "\033]0;test string\007" ; sleep 2` update your terminal title to "test string"?

Nope it didn't do anything

**Comment by darthShadow** [comment]
Then this is not going to work. Your terminal doesn't support setting the title.

**Comment by darthShadow** [comment]
Once you figure out how to get the echo statement to work in your specific terminal/OS combination, then this feature should also start working.

**Comment by xd003** [comment]
Alright , thanks for confirmation

**Comment by orschiro** [comment]
@darthShadow sadly still not working

```
Performing backup...
Error: unknown flag: --progress-terminal-title
Usage:
  rclone sync source:path dest:path [flags]

Flags:
      --create-empty-src-dirs   Create empty source dirs on destination after sync
  -h, --help                    help for sync

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.

2021/02/19 09:05:03 Fatal error: unknown flag: --progress-terminal-title
```

**Comment by darthShadow** [comment]
Check your installed rclone version. It requires the latest stable i.e. 1.54

**Comment by orschiro** [comment]
Thanks! Now the command seems to be respected. However, it doesn't work for me either.

Check this video: https://drive.google.com/file/d/1PK3LuaTVdbxcCjCTMS-viv3qixLNVZWo/view?usp=drivesdk

This is my .bashrc:

```
# .bashrc

# source fzf key bindings
if [ -f /usr/share/fzf/shell/key-bindings.bash ]; then
        . /usr/share/fzf/shell/key-bindings.bash
fi

# showing working directory in prompt
export PROMPT_COMMAND='history -a'
export PS1='${PWD/*\//} $ '

# Show running command in terminal window title
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)} \w\a\]$PS1"
    trap 'echo -ne "\033]2;$(history 1 | sed "s/^[0-9 ]* \+//")\007"' DEBUG
    ;;
*)
    ;;
esac

alias cp="cp -r"
```

**Comment by darthShadow** [comment]
Try without a bashrc once. I am guessing the `# Show running command in terminal window title` block is interfering.

**Comment by orschiro** [comment]
@darthShadow thanks, all sorted! :)
