### ISSUE TITLE
Can't Connect to Microsoft in order to sign in

### ISSUE THREAD

**Issue by KonstantMan** [rclone/rclone#5061]
#### What is the problem you are having with rclone?
Can't Connect to Microsoft in order to sign in

#### What is your rclone version (output from `rclone version`)
rclone v1.54.0
- os/arch: linux/amd64
- go version: go1.15.7

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
- os/arch: linux/amd64

####  Which cloud storage system are you using? (e.g. Google Drive)
OneDrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
If your browser doesn't open automatically go to the following link: 
Log in and authorize rclone for access
Waiting for code...
![Screenshot from 2021-02-23 21-29-38](https://user-images.githubusercontent.com/56481040/108897093-66292100-761e-11eb-9324-0cdd37f97086.png)

**Comment by darthShadow** [comment]
Can you please add your redacted config too?

**Comment by outloudvi** [comment]
![image](https://user-images.githubusercontent.com/19144373/108961718-b651c300-76b2-11eb-9fd4-68a7ebb1f17d.png)


Seeing your troubleshooting message, it seems that you inputed the string "Microsoft App Client Secret", into the `client_id` area, where you should fill in your Application (client) ID.

**Comment by ivandeex** [comment]
Closing answered questions :-)
