### ISSUE TITLE
s3: seems to not figure out bucket zone "automagically"

### ISSUE THREAD

**Issue by yarikoptic** [rclone/rclone#5066]
#### What is the problem you are having with rclone?

it works so good that I want to (ab)use it more, but it is resisting ;)

summary: having a generic s3 configuration without zone specification seems to work only for some public buckets (in `us-east-1`?) zone but not the others.

<details>
<summary>
Not sure how, but e.g. python's good old boto 2.49.0 seems to connect to sample buckets anonymously just fine without any zone specification:
</summary> 

```shell
$> python3 -c 'import boto; print(next(iter(boto.connect_s3(anon=True).get_bucket("fcp-indi").list_versions())))'
<boto.s3.deletemarker.DeleteMarker object at 0x7f81e2e679d0>

$> python3 -c 'import boto; print(next(iter(boto.connect_s3(anon=True).get_bucket("openfmri").list_versions())))'  
<Key: openfmri,corral-repl/utexas/poldracklab/openfmri/inprocess/ds113c/ds113c-gitannex/tarballs/ds113c_R1.0.0_metadata.tar.gz>

$> python3 -c 'import boto; print(next(iter(boto.connect_s3(anon=True).get_bucket("dandiarchive").list_versions())))'
<Key: dandiarchive,dandiarchive/dandiarchive/2019-10-02T04-00Z/manifest.checksum>
```
</details>

whenever rclone would work for first two but fail for the last:

```shell
$> tail -3 ~/.config/rclone/rclone.conf
[s3]
type = s3
provider = AWS

$> rclone ls s3:dandiarchive       
2021/02/24 19:16:53 ERROR : S3 bucket dandiarchive: Failed to update region for bucket: reading bucket location failed: AccessDenied: Access Denied
	status code: 403, request id: 1C82D50F1B54F94D, host id: P2abi9H9rNSseBsDWVHlgw+rRalYTtAyakieS269zt2ltlPaFzUH1WhmLS3dMhKzZZ47KRxf8fM=
2021/02/24 19:16:53 Failed to ls: BucketRegionError: incorrect region, the bucket is not in 'us-east-1' region at endpoint ''
	status code: 301, request id: , host id: 
```

For this bucket I could even query for the zone:

```shell
$> python3 -c 'import boto; print(boto.connect_s3(anon=True).get_bucket("dandiarchive").get_location())' 
us-east-2
```

And rclone does work if I use rclone config where I did specify zone:

```
[s3_us_east_2]
type = s3
provider = AWS
region = us-east-2
```

```shell
$> rclone ls s3_us_east_2:dandiarchive | head
       33 dandiarchive/dandiarchive/2019-10-02T04-00Z/manifest.checksum
      490 dandiarchive/dandiarchive/2019-10-02T04-00Z/manifest.json
...
```

#### What is your rclone version (output from `rclone version`)

rclone v1.53.3-DEV
- os/arch: linux/amd64
- go version: go1.15.5

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Debian GNU/Linux testing/unstable mix

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```shell
$> rclone ls -vvv s3:dandiarchive  
2021/02/24 19:20:55 DEBUG : rclone: Version "v1.53.3-DEV" starting with parameters ["rclone" "ls" "-vvv" "s3:dandiarchive"]
2021/02/24 19:20:55 DEBUG : Using config file from "/home/yoh/.config/rclone/rclone.conf"
2021/02/24 19:20:55 DEBUG : Creating backend with remote "s3:dandiarchive"
2021/02/24 19:20:55 ERROR : S3 bucket dandiarchive: Failed to update region for bucket: reading bucket location failed: AccessDenied: Access Denied
	status code: 403, request id: AC1347C12224B7FD, host id: ljNjKG0S3uwLJEnGMYgHt8Qe3pjGTlXU7f+Ai8LlEl7jWWEtEf+dnUXs/jdQI9OTBTK3qhcib48=
2021/02/24 19:20:55 DEBUG : 4 go routines active
2021/02/24 19:20:55 Failed to ls: BucketRegionError: incorrect region, the bucket is not in 'us-east-1' region at endpoint ''
	status code: 301, request id: , host id: 
```

**Comment by darthShadow** [comment]
This works for us-east-1 because if the region is absent, rclone automatically uses us-east-1 as the default region. This is noted in the docs here: https://rclone.org/s3/#s3-region

**Comment by panthony** [comment]
rclone region is using `GetBucketLocation` API to resolve a bucket's region when unspecified.

The problem is that using this API requires top level permissions which we may not have as often only the permission to read/write files under a prefix may be provided.

There is another (safer?) way to resolve the region of a bucket though that does not requires specific permissions, that is to send an `HeadRequest` to the bucket & check the response headers.


That's what the `boto3` libraries does and what is suggested by contributors of AWS CLI in such cases:

https://github.com/aws/aws-cli/issues/2431#issuecomment-278725415

**Comment by ncw** [comment]
@panthony nice idea. Fancy sending a PR?

**Comment by panthony** [comment]
@ncw Why not, I'll keep this in mind, not sure when I'll have enough bandwidth though :)

**Comment by panthony** [comment]
@ncw Attempted a PR for this here:

https://github.com/rclone/rclone/pull/6525

It was harder than anticipated, I always ended with an empty Header map I could not understand why.

I found my salvation when I found this piece of code:

https://github.com/aws/aws-sdk-go/blob/36e99e2d8b7f9efaa27e9665760788b3169e24bb/service/s3/s3manager/bucket_region.go#L117

Which made me discover than the logic is actually already implemented in `s3manager`.
