### ISSUE TITLE
Purge on encrypted rclone backend deleted extraneous files

### ISSUE THREAD

**Issue by eldondev** [rclone/rclone#5067]
#### Output of `rclone version`
rclone v1.54.0
- os/arch: linux/amd64
- go version: go1.15.7

#### Describe the issue
When running a "purge" on an encrypted backup with filename encryption, many unencrypted files or differently-encrypted files were also deleted.

My redacted rclone config looked like this:

[b2]
type = b2
account = XXXXXXXXXXXXXXXXXXXXXXXXX
key = XXXXXXXXXXXXXXXXXXXXXXXXXXX

[enc]
type = crypt
remote = b2:bucket-name/
filename_encryption = standard
password = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx

I did an rclone sync to move things from one place to another, then did an `rclone purge --log-file purge-log -P --transfers 100 -vvv enc:/ `. Unfortunately, this deleted hundreds of thousands of files that were not encrypted by the enc backend, but were in the b2 bucket.

**Comment by darthShadow** [comment]
I think this is as expected since rclone doesn't keep track of the files that were uploaded vs. files uploaded by a third-party. When you ask it to purge a bucket, it will remove everything on the bucket irrespective of who uploaded or encrypted it.

**Comment by eldondev** [comment]
@darthShadow If you read the rclone command I issued, I asked it to purge the encrypted remote, not the bucket. According to [the docs](https://rclone.org/crypt/) rclone does integrity verification. I would expect the encryption in a scenario when the filenames are encrypted to decrypt the filenames and perform integrity verification on them before deleting them.

**Comment by ivandeex** [comment]
purge is a strong removal tool, and this is documented.

https://rclone.org/commands/rclone_purge/

> Remove the path and all of its contents. Note that this does not obey include/exclude filters - everything will be removed. Use the delete command if you want to selectively delete files.

**Comment by ivandeex** [comment]
Not a bug.

**Comment by darthShadow** [comment]
> According to the docs rclone does integrity verification.

This is only for downloads/uploads. And even then, rclone only throws an error on the files it can't decrypt, it doesn't actually ignore them since it doesn't keep track of which files were uploaded by it.

That's why it's recommended to not mix rclone encrypted files/folders with files/folders that are unencrypted or encrypted by a third-party.

> perform integrity verification

This would involve downloading all the files which seems counter-productive, given the end goal is to delete them anyway.

**Comment by ivandeex** [comment]
This is by design

**Comment by eldondev** [comment]
@ivandeex @darthShadow I have some ideas for some things that I would consider to be improvements. I can just develop them on a fork, but I was hoping to discuss them first. Would you be interested in a PR once I've made the changes?

**Comment by darthShadow** [comment]
Contributions are always welcome. Please open a thread on the [forum](https://forum.rclone.org/) for any discussions.
