### ISSUE TITLE
--create-empty-src-dirs and --include can't work together ?

### ISSUE THREAD

**Issue by greenkero** [rclone/rclone#5069]
#### What is the problem you are having with rclone?

I have the data like this:
D:\001\004
D:\002
D:\003
D:\005

When I use command
rclone copy D:\ E:\ --include {001/＊＊,002/＊＊} --create-empty-src-dirs

It will work but will build E:\003 and E:\005 empty folder.

If I dont't want to show 003 and 005, I  must use
rclone copy D:\ E:\ --include {001/＊＊,002/＊＊} 
But I have some empty folders on D:\001 must be copy.
How could I DO ?
Thank you very much

#### What is your rclone version (output from `rclone version`)

rclone-v1.54.0-windows-amd64

**Comment by albertony** [comment]
There were some strange formatting, but assuming your command was:

`rclone copy D:\ E:\ --include {001/**,002/**} --create-empty-src-dirs`

I can reproduce your issue. But it works as expected if I change it to:

`rclone copy D:\ E:\ --include 001/** --include 002/** --create-empty-src-dirs`

Also see this for some background: https://forum.rclone.org/t/includes-empty-source-folders-when-using-slashes-in-glob-choice-patterns/20091/2

Does such a rewrite work for you?

**Comment by albertony** [comment]
Issue is sort of documented in code:

> // Can't deal with / or ** in {}

https://github.com/rclone/rclone/blob/master/fs/filter/glob.go#L124

> // Can't figure this one out so return any directory might match

https://github.com/rclone/rclone/blob/master/fs/filter/glob.go#L137

Result is that a filter such as `{001/**,002/**}` will work as expected for files, but rclone are not able to use this filter to exclude directories from being traversed. Without `--create-empty-src-dirs` you will not notice (except perhaps performance), but with it any (traversed) directories that are empty will be created, leading to a little surprise..

It is not documented in [filtering docs](https://rclone.org/filtering), as I could see. If @greenkero confirms (one of) the alternatives work, and @ncw agrees with my understanding (or can clearify it), maybe @edwardxml would like to add it to the doc?

**Comment by greenkero** [comment]
It's work！
You solved my problem.
Thank you very much.

**Comment by albertony** [comment]
Great to hear it worked out for you!
I will just close this issue as solved, and will handle the documentation independently.
