### ISSUE TITLE
systemd notify in rcd

### ISSUE THREAD

**Issue by vercas** [rclone/rclone#5073]
#### What is your current rclone version (output from `rclone version`)?

Running latest stable and a couple of betas on various machines.

#### What problem are you are trying to solve?

I've got a systemd unit that starts `rclone rcd`.  
I've got other systemd units that depend on the first one, which use `rclone rc mount/mount` in order to mount various remotes.  

Right now I have to add `sleep` commands before all the `rclone rc` commands because they run before the RCD is able to accept them.  

#### How do you think rclone should be changed to solve that?

`rclone rcd` should send systemd service notifications when it's ready and when it's quitting, just like `rclone mount` does.

**Comment by Navdevl** [comment]
Hey @darthShadow I'd like to work on this. I am very new to this, so could you please provide me an initial direction on where I should look into?

**Comment by darthShadow** [comment]
Basically, you will need to copy the notify logic from mount (https://github.com/rclone/rclone/blob/master/cmd/mountlib/mount.go#L563-L576) to rcd (https://github.com/rclone/rclone/blob/master/cmd/rcd/rcd.go#L51).

So, do the `notify` and `finalise` registering before going into the `s.Wait()` logic and manually call the `finalise` function after `s.Wait()` before returning.

---

@ncw Correct me if anything seems wrong in the above logic.

**Comment by Navdevl** [comment]
Oh, thank you @darthShadow 

I'll look into those areas of logic and get back if there's anything to clarify.
