### ISSUE TITLE
Instruct users to upgrade rclone

### ISSUE THREAD

**Issue by ivandeex** [rclone/rclone#5074]
#### What is your current rclone version (output from `rclone version`)?

1.54.0

This feature idea additionally _blocks_ on availability of the `rclone self-update` command which will be implemented by #548 

#### What problem are you are trying to solve?

https://forum.rclone.org/t/previously-working-rclone-backup-now-giving-error-unknown-command-rcat-for-rclone/22507/14

Many support requests on rclone forum or github involve an outdated / unsupported / ancient version of rclone. The Support team repeatedly ask users to upgrade, users rerun their tests, thread continues only after these spare cycles. Rinse, repeat.

We can try to save people's time here.

#### How do you think rclone should be changed to solve that?

Let's add simple upgrade instructions in three places:

1. In the rclone command line parser. Whenever it enounters unknown command it should print:

`Error: unknown command "xxx" for "rclone". You could use "rclone self-update" to get latest features.`

2. In the forum post template. It should say:

```
#### What is your rclone version (output from `rclone version`)
<!-- **STOP and  READ**: Are you on the latest version of rclone?
     Many newbie problems are solved with a quick update, just run `rclone self-update --check`.
 -->
```

3. In the github bug/feature template - ???

**Comment by darthShadow** [comment]
We should probably also update the Bug template to be similar to the "Help & Support" template on the forum.

---

<details><summary>Current Bug Template on Github:</summary>

<p>

```
<!--

Welcome :-) We understand you are having a problem with rclone; we want to help you with that!

If you've just got a question or aren't sure if you've found a bug then please use the rclone forum:

    https://forum.rclone.org/

instead of filing an issue for a quick response.

If you think you might have found a bug, please can you try to replicate it with the latest beta?

    https://beta.rclone.org/
    
If you can still replicate it with the latest beta, then please fill in the info below which makes our lives much easier.  A log with -vv will make our day :-)

Thank you

The Rclone Developers

-->
```

#### What is the problem you are having with rclone?



#### What is your rclone version (output from `rclone version`)



#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)



####  Which cloud storage system are you using? (e.g. Google Drive)



#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)



#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)


</p>

</details>

---

<details><summary>Current "Help & Support" Template on the forum:</summary>

<p>

```
<!--
**STOP and READ**
**YOUR POST WILL BE REMOVED IF IT IS LOW QUALITY**:
Please show the effort you've put in to solving the problem and please be specific -- people are volunteering their time to help you! Low effort posts are not likely to get good answers!   **DO NOT REDACT** any information except passwords/keys/personal info.  You should use 3 backticks to begin and end your paste to make it readable.  Or use a service such as https://pastebin.com or https://gist.github.com/
-->
```

#### What is the problem you are having with rclone?


#### What is your rclone version (output from `rclone version`)
```
<!--
**STOP and READ**:
Are you on the latest version of rclone? You can validate by checking the version listed here: https://rclone.org/downloads/
-->
```

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)


####  Which cloud storage system are you using? (eg Google Drive)



#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
```
<!--
You should use 3 backticks to begin and end your paste to make it readable.
-->
```

```
Paste command here
```


#### The rclone config contents with secrets removed.
```
<!--
You should use 3 backticks to begin and end your paste to make it readable.
-->
```

```
Paste config here
```



#### A log from the command with the `-vv` flag
```
<!--
You should use 3 backticks to begin and end your paste to make it readable.  Or use a service such as https://pastebin.com or https://gist.github.com/
-->
```

```
Paste  log here
```


</p>

</details>

**Comment by ivandeex** [comment]
@darthShadow
I think that your idea can be included into this request.
What would you the new templates look like?

**Comment by darthShadow** [comment]
Ideally, only issues that have been confirmed on that forum should be created here so perhaps a bot that enforces the presence of a valid forum URL in the issue body, without which the issue is closed automatically?

That may be too drastic a step, however, so perhaps the easiest/simplest thing would be to simply copy the forum template pasted above and add an additional line to post on the forum first?

**Comment by ivandeex** [comment]
The rclone cli parser message will be added by #5080. Other tasks remain.

**Comment by ivandeex** [comment]
> Ideally, only issues that have been confirmed on the forum should be created here so perhaps a bot that enforces the presence of a valid forum URL in the issue body, without which the issue is closed automatically?
> That may be too drastic a step

As far as I can see this has already happened but without any official announcement

**Comment by ivandeex** [comment]
Related to #5122
