### ISSUE TITLE
get filename with command "copyurl"

### ISSUE THREAD

**Issue by gandolfi974** [rclone/rclone#5094]
hello,

i open an issue for a option in rclone.

- i use rclone copyurl to download file from the web with -a flag (redirect url). I need to get the filename of the downloaded file in order to insert in a database.
rclone copyurl -P "https://video.com/stream/?vid=vmDZtFsMQ" gdrive:/film -a --transfers 10 --drive-chunk-size 128M

- I can't retrieve the filename. is it possible to add this option ?

thanks

**Comment by albertony** [comment]
Suggested a fix in https://github.com/rclone/rclone/pull/5095

Note: Combining with option `-P, --progress` as in your example will not give good result, as that will clutter the output (and as noted in the forum thread `--transfers` is not relevant here).

PS: I'm still wondering what problem you had without the `-a` option, mentioned in the [forum](https://forum.rclone.org/t/get-filename-from-the-command-urlcopy-a/22613). Does not the following work?
```
rclone copyurl -P "https://video.com/stream/?vid=vmDZtFsMQ" gdrive:/film/testing123.mp4 --drive-chunk-size 128M
```

**Comment by gandolfi974** [comment]
without -a or without indicate the final filename i can't copy. "command fail - "gdrive:/film/" is a directory".

it's ok with the command line `rclone copyurl -P "https://video.com/stream/?vid=vmDZtFsMQ" gdrive:/film/testing123.mp4 --drive-chunk-size 128M`

i have to create a name and don't retrieve the name
