### ISSUE TITLE
How to deal with big object? 

### ISSUE THREAD

**Issue by zhucan** [rclone/rclone#5098]
https://github.com/rclone/rclone/blob/7aa7acd926777ae149142f6dab9b15f4968f7071/fs/operations/operations.go#L442

I have a question, If the size of the object is very big(for example 200G) and exceed the memory size, write the object to the buffer 
one time may be failed,  is  there some way to avoid this problem?

Maybe we can write a part of data to the buffer and to upload one time?

@ncw @vanillajonathan

**Comment by ncw** [comment]
Rclone streams objects normally so it shouldn't fill up your memory.

How are you using that function?

**Comment by ivandeex** [comment]
@zhucan ping

**Comment by zhucan** [comment]
The func "NewReopen" will not store the data to the memeroy? @ncw

**Comment by ivandeex** [comment]
https://github.com/rclone/rclone/blob/v1.55.0/fs/operations/reopen.go#L38

NewReOpen and its underlying structure ReOpen is a _thin_ wrapper for a download stream which encapsulates ability to do "low-level" read retries. It does not allocate any buffers on its own.

**Comment by ivandeex** [comment]
If you see high memory footprint with rclone, please report it as a bug request here or on rclone forum.

**Comment by zhucan** [comment]
@ivandeex Thanks

**Comment by ivandeex** [comment]
Question answered.
