### ISSUE TITLE
Thumbnail preview on Linux

### ISSUE THREAD

**Issue by Draecal** [rclone/rclone#5101]
#### Output of `rclone version`

```
rclone v1.45
os/arch: linux/amd64
go version: go1.11.6

```

#### Describe the issue

Tried with default file explorer of my distro "Deepin OS" + Nautilus both not able to generate thumbnails.

![image](https://user-images.githubusercontent.com/8697000/110207229-0599af80-7e7a-11eb-9933-cc4a36225cb7.png)

**Comment by albertony** [comment]
Assuming this is a mount? Can you please share the complete rclone command .

**Comment by Draecal** [comment]
I'm using mount function in the GUI just with option: --vfs-cache-mode full

Enviado desde Mailspring (https://link.getmailspring.com/link/169F9B15-52D3-4B1C-A5B9-506896C9637C@getmailspring.com/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQUNDTEpLRTVUQTRCUzRLVEJNTVJLN042SjU0NzNFVkJOSEhEQ0Y2QkpRQHJlcGx5LmdpdGh1Yi5jb20%3D), la mejor aplicación de correo electrónico gratuita para trabajar

**Comment by ivandeex** [comment]
@Draecal Bienvenido
We are willing to help you but need more data to understand your issue.
Let's try as follows.
Stop your `rclone rcd` command and  mount manually from command line:
```
rclone mount YourRemote: /local/path --vfs-cache-mode full -vv --log-file /tmp/bug.log
```
Then do whatever you did before. Will the issue reproduce?
If yes, send `bug.log` and redacted config here.

**Comment by Draecal** [comment]
Good morning log file contains too many sensitive data that can't be posted. Said that, this are the main lines of the log file until reaching target file:
2021/03/07 07:47:17 DEBUG : rclone: Version "v1.45" starting with parameters ["rclone" "mount" "Onedrive:" "Onedrive" "--vfs-cache-mode" "full" "-vv" "--log-file" "tmp/bug.log"]
2021/03/07 07:47:17 DEBUG : Using config file from "/home/alfredo/.config/rclone/rclone.conf"
2021/03/07 07:47:18 DEBUG : One drive root '': Mounting on "Onedrive"
2021/03/07 07:47:18 INFO : One drive root '': poll-interval is not supported by this remote
2021/03/07 07:47:18 DEBUG : vfs cache root is "/home/alfredo/.cache/rclone/vfs/Onedrive"
2021/03/07 07:47:18 DEBUG : Adding path "vfs/forget" to remote control registry
2021/03/07 07:47:18 DEBUG : Adding path "vfs/refresh" to remote control registry
2021/03/07 07:47:18 DEBUG : Adding path "vfs/poll-interval" to remote control registry
2021/03/07 07:47:18 DEBUG : : Root:
2021/03/07 07:47:18 DEBUG : : >Root: node=/, err=<nil>
2021/03/07 07:47:18 DEBUG : Cleaning the cache
2021/03/07 07:47:18 DEBUG : Documentos/CPE/ReDesign/AEIB Digital Alfredo.jpg: updateTime: setting atime to 2021-03-07 07:44:18.506482941 +0000 WET
The issue comes with any image file not having thumbnail, so the only way to know what the image contains is both to remember by file name or to open it.

Enviado desde Mailspring (https://link.getmailspring.com/link/FF0AF399-8180-4E7A-A2B4-FD98DC19C847@getmailspring.com/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQUNDTEpLQU1INFVVSUo1NE02SjQ0N0Y2S0FYTzdFVkJOSEhEQ0Y2QkpRQHJlcGx5LmdpdGh1Yi5jb20%3D), la mejor aplicación de correo electrónico gratuita para trabajar

**Comment by albertony** [comment]
Does setting option `Edit > Preferences > Preview > Always` in Nautilus make a difference?

**Comment by Draecal** [comment]
No change. I even increased the minimum file size for previews to 1GB or less.

Enviado desde Mailspring (https://link.getmailspring.com/link/CF946C5E-23DC-485F-842C-AEEBB212161C@getmailspring.com/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQUNDTEpLQVQ0R09QTTZRSExNTFNLV042S0JaSFRFVkJOSEhEQ0Y2QkpRQHJlcGx5LmdpdGh1Yi5jb20%3D), la mejor aplicación de correo electrónico gratuita para trabajar

**Comment by ivandeex** [comment]
Release `rclone: Version "v1.45"`. Please try again with the latest `1.54` from https://rclone.org. We have substantially improved the mount code recently.

**Comment by Draecal** [comment]
Even upgrading didn't fix it. I would be good to know if its a limitation of Onedrive or just a general issue. Also, it would be great to know how many users are having this issue too, to check if related to specific distro.
Current version:

rclone v1.54.0
- os/arch: linux/amd64
- go version: go1.15.7
Mount command:

rclone mount Onedrive: Onedrive --vfs-cache-mode full -vv --log-file tmp/bug.log
Distro:

Deepin OS 220.1 Community (1030)
Kernel:
5.4.70-amd64-desktop
Enviado desde Mailspring (https://link.getmailspring.com/link/CB0BBE53-0387-46D5-BBFE-461C281A564D@getmailspring.com/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQUNDTEpLR1RBTFNPWFdHU0lMN0JZN1Y2S0RKV0JFVkJOSEhEQ0Y2QkpRQHJlcGx5LmdpdGh1Yi5jb20%3D), la mejor aplicación de correo electrónico gratuita para trabajar

**Comment by ivandeex** [comment]
@animosity22
Could you take a look at this support request?
Did you see reports like this on forum?
Problem: Nautilus on top of rclone mount does not show by default image previews for jpg/png files
OS: Debian buster 10.6 based distro (fuse3, I guess) with Gnome 3.30.x (+/-)
rclone: 1.54.0 amd64 static build (no cmount)
Backend: Onedrive (personal, I guess)
Backend config: N/A 👎 
Debug log: N/A 👎 
Command: rclone mount onedrive: ./onedrive (from home dir)

@Draecal 
Advice: If your data is sensitive, you can create a subdir on onedrive and upload stock images of similar size from the net there, then mount only it.
Note: Requests without logs and config are deemed low quality and can take long to reproduce. You can hope that someone with a similar setup and more debug data comes across this post before it gets stale.

**Comment by ivandeex** [comment]
Closing as request is incomplete.
Feel free to resubmit when you have data required for analysis.
