### ISSUE TITLE
build: Debian arm package has architecture armhf

### ISSUE THREAD

**Issue by cr1xu5** [rclone/rclone#5107]
#### What is the problem you are having with rclone?

The control file of both the [arm-v7](https://downloads.rclone.org/v1.54.1/rclone-v1.54.1-linux-arm-v7.deb) and [arm](https://downloads.rclone.org/v1.54.1/rclone-v1.54.1-linux-arm.deb) Debian package contain the same architecture: "armhf". I think the arm package should have the architecture "armel".

https://www.debian.org/releases/buster/armhf/ch02s01.en.html#idm185

Found when trying to set up up a Gitlab CI powered [Rclone Debian package repository](https://gitlab.com/cr1xu5/rclone-debian-repository).

#### What is your rclone version (output from `rclone version`)

1.54.1

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```zsh
➜  ~ dpkg -I rclone-v1.54.1-linux-arm.deb
 new Debian package, version 2.0.
 size 13332482 bytes: control archive=586 bytes.
       1 bytes,     0 lines      conffiles            
     431 bytes,    14 lines      control              
     252 bytes,     4 lines      md5sums              
 Package: rclone
 Version: 1.54.1
 Section: default
 Priority: extra
 Architecture: armhf
 Maintainer: Nick Craig-Wood <nick@craig-wood.com>
 Vendor: rclone
 Installed-Size: 36447
 Provides: rclone
 Homepage: https://rclone.org
 Description: Rclone - "rsync for cloud storage"
     is a command line program to sync files and directories to and
     from most cloud providers. It can also mount, tree, ncdu and lots
     of other useful things.
➜  ~ dpkg -I rclone-v1.54.1-linux-arm-v7.deb 
 new Debian package, version 2.0.
 size 13321880 bytes: control archive=587 bytes.
       1 bytes,     0 lines      conffiles            
     431 bytes,    14 lines      control              
     252 bytes,     4 lines      md5sums              
 Package: rclone
 Version: 1.54.1
 Section: default
 Priority: extra
 Architecture: armhf
 Maintainer: Nick Craig-Wood <nick@craig-wood.com>
 Vendor: rclone
 Installed-Size: 36383
 Provides: rclone
 Homepage: https://rclone.org
 Description: Rclone - "rsync for cloud storage"
     is a command line program to sync files and directories to and
     from most cloud providers. It can also mount, tree, ncdu and lots
     of other useful things.
➜  ~
```

**Comment by ivandeex** [comment]
I think, only ncw can address this request?

**Comment by ncw** [comment]
Rclone will require floating point. Is that provided on `armel`? I think it is but via an emulator.

I'm pretty sure the binaries will run.

I just looked at the source code of [nfpm](https://github.com/goreleaser/nfpm) which is the tool I use to make the packages

```
var archToDebian = map[string]string{
        "386":     "i386",
        "arm":     "armhf",
        "arm5":    "armel",
        "arm6":    "armhf",
        "arm7":    "armhf",
        "mipsle":  "mipsel",
        "ppc64le": "ppc64el",
}
```

So `nfpm` believes that `arm6` should be `armhf`...


I told it that arm builds were arm5 and it seems to put the armel architecture in now.

[v1.55.0-beta.5271.a5a2e02ea.fix-5107-arm-build](https://beta.rclone.org/branch/fix-5107-arm-build/v1.55.0-beta.5271.a5a2e02ea.fix-5107-arm-build/) on branch [fix-5107-arm-build](https://github.com/rclone/rclone/tree/fix-5107-arm-build) (uploaded in 15-30 mins)

What do you think?

**Comment by cr1xu5** [comment]
There is indeed an emulator added by the compiler for ARMv5: https://github.com/golang/go/wiki/GoArm#lack-of-floating-point-hardware-on-armv5

Not sure if ARMv6 should get it's own package, but for ARM Debian expects ARMv5/armel as per the Debian documentation linked above. In that respect this change is very welcomed.

**Comment by ncw** [comment]
I need someone to test the build above - see whether the debs are correct - thanks!

**Comment by cr1xu5** [comment]
I would love to, but cannot find the debs in the artifacts. Could it be that no debs were created due to a failing race test? https://github.com/rclone/rclone/actions/runs/654931501

**Comment by darthShadow** [comment]
The builds should now be available.

**Comment by ivandeex** [comment]
@cr1xu5 
Any success with https://beta.rclone.org/branch/fix-5107-arm-build/v1.55.0-beta.5271.a5a2e02ea.fix-5107-arm-build/
??

**Comment by cr1xu5** [comment]
The Debian packages are in line with Debian supported architectures now:

```zsh
➜  ~ dpkg -I rclone-v1.55.0-beta.5271.a5a2e02ea.fix-5107-arm-build-linux-arm64.deb | grep Architecture
 Architecture: arm64
➜  ~ dpkg -I rclone-v1.55.0-beta.5271.a5a2e02ea.fix-5107-arm-build-linux-arm.deb | grep Architecture 
 Architecture: armel
➜  ~ dpkg -I rclone-v1.55.0-beta.5271.a5a2e02ea.fix-5107-arm-build-linux-arm-v7.deb | grep Architecture 
 Architecture: armhf
➜  ~
```

However, I found that the [download page](https://rclone.org/downloads/) suggests the ARM Debian package was meant to be v6. Even more, I could not quickly find popular ARM v5 devices with a simple Google search (only [old NAS hardware](https://www.debian.org/ports/arm/)). Not sure if there is demand for a ARMv5 package, while ARMv6 is used in for example [the Raspberry Pi 1](https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications).

Therefore, a change in the name of the Debian package from `rclone-v1.55.0-linux-arm.deb` to `rclone-v1.55.0-linux-arm-v6.deb` could have also solved my confusion. Or, I should have looked at the official download page first instead of the Github releases..

For my Debian repository I will then just use the ARMv6 Debian package to include as it should also run on ARMv7.

**Comment by albertony** [comment]
This should now be fixed by https://github.com/rclone/rclone/pull/6528. Considering the status/age of this issue I'll close it, and we can instead reopen if it turns out my assumption was wrong.
