### ISSUE TITLE
Copy file paste in same folder on windows,  source file being a 0kb file

### ISSUE THREAD

**Issue by miludedeng** [rclone/rclone#5111]
I used webdav。 params like：
`go run --tags=cmount,cgo rclone.go mount jianguoyun:/ X: --config ./rclone.conf --vfs-cache-mode=full --cache-dir=C:/rclone_cache/ --dir-cache-time 3s -v --log-file ./rclone.log`
copy X:/folder1/a.docx  paste to X:/folder1/。 a.docx being 0kb
When i copy a file and paste in the same folder。The source file is covered by a 0kb file。I find that，when has no cache file in vfs cache folder or new file is over 5 seconds, copy the file and paste。 source file and destination file is 0kb。

**Comment by darthShadow** [comment]
Please add the requested details from the template.

**Comment by ivandeex** [comment]
duplicate of #5181
