### ISSUE TITLE
Update filtering doc with pattern-list limitation

### ISSUE THREAD

**Issue by albertony** [rclone/rclone#5112]
Given directories:
```
D:\001\004
D:\002
D:\003
D:\005
```

The following command works, but will unexpectedly create empty directories E:\003 and E:\005:

`rclone copy D:\ E:\ --include {001/**,002/**} --create-empty-src-dirs`

The following alternatives avoids the unexpected empty directories:

`rclone copy D:\ E:\ --include 001/** --include 002/** --create-empty-src-dirs`

`rclone copy D:\ E:\ --include {001,002}/** --create-empty-src-dirs`

This is a limitation in the filtering implementation, as documented in code:

> // Can't deal with / or ** in {}

https://github.com/rclone/rclone/blob/d260e3824e15702040db2cecaa49ced852d07d6d/fs/filter/glob.go#L124-L125

> // Can't figure this one out so return any directory might match

https://github.com/rclone/rclone/blob/d260e3824e15702040db2cecaa49ced852d07d6d/fs/filter/glob.go#L137

Meaning: A filter such as `{001/**,002/**}` will work as expected for files, but rclone is not able to use this filter to exclude directories from being traversed. Without `--create-empty-src-dirs` you will not notice (except perhaps performance), but with it any (traversed) directories that are empty will be created, leading to a little surprise..

This issue comes from the discussion in https://github.com/rclone/rclone/issues/5069, which were closed due to described workarounds.

**Comment by ncw** [comment]
Documenting this would be a great idea.

Fixing it would be a good idea too - however I already punted as too hard (or possibly too lazy!).

PS I updated your code links to permalinks which shows the code in question
