### ISSUE TITLE
Refactor systemd notifications for servers

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#5117]
As a follow up from https://github.com/rclone/rclone/pull/5085#issuecomment-789907801 we would like to add systemd notification for all the `rclone serve` commands.

We currently do this for `rclone mount` and `rclone rcd` but it would be great to do this for `rclone serve http` etc.

This is currently done in rcd here

https://github.com/rclone/rclone/blob/d260e3824e15702040db2cecaa49ced852d07d6d/cmd/rcd/rcd.go#L54-L70

I'd suggest we factor that into `lib/systemd` as something like

```go
// Notify systemd that the service is starting. This returns a
// function which should be called to notify that the service is
// stopping. This function will be called on exit if the service exits
// on a signal.
func Notify() func() {
	var (
		finaliseOnce sync.Once
		fnHandle = atexit.Register(finalise)
	)
	
	finalise := func() {
		atexit.Unregister(fnHandle)		
		finaliseOnce.Do(func() {
			_ = sysdnotify.Stopping()
		})
	}

	// Notify ready to systemd
	if err := sysdnotify.Ready(); err != nil {
		log.Printf("failed to notify ready to systemd: %v", err)
	}
	
	return finalise
}
```

Then this can be called just before `s.Wait` in 

- cmd/rcd/rcd.go
- cmd/serve/dlna/dlna.go
- cmd/serve/http/http.go
- cmd/serve/restic/restic.go
- cmd/serve/sftp/sftp.go
- cmd/serve/webdav/webdav.go

Like this

```go
	defer systemd.Notify()()
	s.Wait
```

Or maybe this if you prefer

```go
	finalise := systemd.Notify()
        defer finalise()
	s.Wait
```

It might be that we could use this in `mount` too, but I haven't investigated that.

**Comment by eNV25** [comment]
Can I try this?

**Comment by ncw** [comment]
@eNV25 that would be great :-) Let me know if you need any help.

**Comment by eNV25** [comment]
Unfortunately my laptop's charger just broke. I can only work on this once I buy a new one.

**Comment by eNV25** [comment]
@ncw What do you thing about the use of sysdnotify in mountlib? The finalise function here does more.

https://github.com/rclone/rclone/blob/b33140ddeb733dedece91b1dd091c4fe3f1b3c43/cmd/mountlib/mount.go#L267-L321
