### ISSUE TITLE
'go get' build failing

### ISSUE THREAD

**Issue by Makeshift** [rclone/rclone#5120]
#### What is the problem you are having with rclone?

When building the latest version from source, `go get` returns that several packages cannot be found:

```
...
#6 190.7 github.com/ncw/swift (download)
#6 191.5 github.com/koofr/go-httpclient (download)
#6 192.0 github.com/koofr/go-koofrclient (download)
#6 192.6 github.com/t3rm1n4l/go-mega (download)
#6 193.1 github.com/putdotio/go-putio (download)
#6 193.8 cannot find package "github.com/putdotio/go-putio/putio" in any of:
#6 193.8        /usr/lib/go/src/github.com/putdotio/go-putio/putio (from $GOROOT)
#6 193.8        /go/src/github.com/putdotio/go-putio/putio (from $GOPATH)
#6 193.8 github.com/yunify/qingstor-sdk-go (download)
#6 195.8 cannot find package "github.com/yunify/qingstor-sdk-go/v3/config" in any of:
#6 195.8        /usr/lib/go/src/github.com/yunify/qingstor-sdk-go/v3/config (from $GOROOT)
#6 195.8        /go/src/github.com/yunify/qingstor-sdk-go/v3/config (from $GOPATH)
#6 195.8 cannot find package "github.com/yunify/qingstor-sdk-go/v3/request/errors" in any of:
#6 195.8        /usr/lib/go/src/github.com/yunify/qingstor-sdk-go/v3/request/errors (from $GOROOT)
#6 195.8        /go/src/github.com/yunify/qingstor-sdk-go/v3/request/errors (from $GOPATH)
#6 195.8 cannot find package "github.com/yunify/qingstor-sdk-go/v3/service" in any of:
#6 195.8        /usr/lib/go/src/github.com/yunify/qingstor-sdk-go/v3/service (from $GOROOT)
#6 195.8        /go/src/github.com/yunify/qingstor-sdk-go/v3/service (from $GOPATH)
#6 195.8 github.com/aws/aws-sdk-go (download)
#6 216.3 github.com/jmespath/go-jmespath (download)
#6 217.1 github.com/pkg/sftp (download)
...
```

#### What is your rclone version (output from `rclone version`)

Latest git commit

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Alpine 64bit (go version go1.15.7 linux/amd64). Also occurs on WSL (Ubuntu) 64bit (go version go1.13.8 linux/amd64).

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`go get -v github.com/rclone/rclone`

#### Comments

This surprises me, since it appears to work fine in CI. This also worked fine a few months ago. Is CI caching some now-nonexistent packages that need to be pinned to an older version?

**Comment by darthShadow** [comment]
Please prefix `GO111MODULE=on` to your command and try again.

**Comment by Makeshift** [comment]
Hah! I'm not a Go dev and had no idea that env var existed. Had a quick google and that makes sense. Thank you!
