### ISSUE TITLE
docs: explicitly describe how to disable config reading (for automation)

### ISSUE THREAD

**Issue by noabody** [rclone/rclone#5125]
Related to [1fed2d9](https://github.com/rclone/rclone/commit/1fed2d910c674ca35310961e3e1a4ce629a902b1) [c95b580](https://github.com/rclone/rclone/commit/c95b58047825b7b35dd5f0973859c1fb7824d69f)

Running any rclone command when a password protected ```rclone.conf``` file is used, requires the password.  This makes certain scripting actions impossible, such as:

```rclone genautocomplete bash rclone.bash_completion```

The scripted action fails because a password cannot be input during headless script execution.

**Comment by ivandeex** [comment]
This is documented, please take a look
- https://rclone.org/docs/#configuration-encryption
- https://rclone.org/docs/#password-command-spaceseplist
- https://github.com/rclone/rclone/wiki/Windows-Powershell-use-rclone-password-command-for-Config-file-password

**Comment by noabody** [comment]
1) Presuming one is building rclone from source
2) Presuming one uses rclone on same system and already has password protected rclone.conf in $HOME/.config/rclone/rclone.conf

It will not be possible to run any commands without being prompted for a password.
The kludge work around is to run ```rclone --config rclone.conf```.  rclone.conf need not exist, the point is to bypass loading of the password protected rclone.conf.
```
touch rclone.conf
./rclone --config rclone.conf genautocomplete bash rclone.bash_completion
./rclone --config rclone.conf genautocomplete zsh rclone.zsh_completion
```
When I package rclone for Arch, I like to generate and properly install the auto-completion files to simplify command line usage.  This method allows me to generate those files without being prompted for a password.

**Comment by ivandeex** [comment]
The "official" no-config use is simply `rclone --config /dev/null ...`
or `export RCLONE_CONFIG=/dev/null; rclone ...`

Reference: https://github.com/rclone/rclone/issues/2879#issuecomment-450558947

**Comment by ivandeex** [comment]
Starting with 1.55 (due this April), the `rclone --config=/notfound ...` will be another OS-independent way to have a RAM-only config.

**Comment by ivandeex** [comment]
Related to #2879 (it requests a new `--no-config` flag)

**Comment by ivandeex** [comment]
Reopening because I cannot find this in documentation

**Comment by ivandeex** [comment]
as noted by @albertony, the `--config=NUL` trick works on Windows
