### ISSUE TITLE
`ncdu` reports a wrong number when file count is large

### ISSUE THREAD

**Issue by zanna-37** [rclone/rclone#5126]
#### What is the problem you are having with rclone?
`ncdu` reports a wrong number for file count when that number is large enough to require a suffix.

I'm not an expert in go, but I suspect the problem resides in the file `/cmd/ncdu/ncdu.go` at row `376`.

In particular, we are using the `SizeSuffix(...)` that are (in my opinion) intended for file size. Therefore it will use the 1024 multiplier, leading to the wrong count.
In my test, it reports 13.183k files but when I enter, the objects are 13499. Notice how 13.183*1024=13499.392.

This is the piece of code I'm talking about.

```go
if u.showCounts {
    if count > 0 {
        extras += fmt.Sprintf("%8v ", fs.SizeSuffix(count)) // <--- HERE
    } else {
        extras += "         "
    }
```

**Comment by albertony** [comment]
I agree. I can look at it as part of my https://github.com/rclone/rclone/pull/5087 work. Thanks for reporting.
