### ISSUE TITLE
Transport endpoint is not connected & lost onedrive mount

### ISSUE THREAD

**Issue by somsifuser** [rclone/rclone#5135]
#### What is the problem you are having with rclone?

Onedrive mount lost & it display Error: `/root/OneDrive`- Transport endpoint is not connected.

#### What is your rclone version (output from `rclone version`)

latest vertion

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

ubuntu server version 20.04

####  Which cloud storage system are you using? (e.g. Google Drive)

onedrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

2021/03/16 15:42:25 Failed to create file system for "remote:tmp": didn't find section in config file

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
2021/03/16 15:41:32 DEBUG : rclone: Version "v1.50.2" starting with parameters ["rclone" "-vv" "copy" "/tmp" "remote:tmp"]
2021/03/16 15:41:32 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2021/03/16 15:41:32 Failed to create file system for "remote:tmp": didn't find section in config file

**Comment by darthShadow** [comment]
Please add your config file too.
