### ISSUE TITLE
Transfer files as they arrive on STDIN when using `--files-from -`

### ISSUE THREAD

**Issue by kevin-hanselman** [rclone/rclone#5136]
#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.54.1
- os/arch: linux/amd64
- go version: go1.16
```

#### What problem are you are trying to solve?
I'm working on a CLI tool that calls out to rclone (via Go's `os/exec` package) to copy files. I'm using `--files-from -` to copy only a specific subset of files between a source and destination to save time. [Here's my code that interfaces with rclone.](https://github.com/kevin-hanselman/dud/blob/7f016d7737dd98d7841014af6240fc711b11f967/src/cache/push.go#L63)

#### How do you think rclone should be changed to solve that?
Sending rclone files to transfer via STDIN works great, but it's sub-optimal for rclone to wait for STDIN to be closed and/or receive EOF before beginning the transfer. I think it would be great if, when using `--files-from -`, files were transferred as they arrive on STDIN, without waiting for STDIN to be closed.

**Comment by ncw** [comment]
That is an interesting idea.

However it would be very difficult to plumb in as rclone uses the list of files in `--files-from` to optimize the directory access patterns before the sync starts.

You might be better off running an `rclone rcd` then submitting copy jobs with `rclone rc` (or use the API directly). This would be an efficient way of doing this.

**Comment by kevin-hanselman** [comment]
Thanks for the response, and thanks for making `rclone`!

I figured it may be a challenge, and also that I may be better served using a different interface. Ultimately I haven't done much profiling, and that is an obvious prerequisite to making optimizations. Nonetheless, I thought I'd see what the rclone community thought of this idea/use-case. Thanks for recommending `rclone rc(d)`! I'll look into that going forward.

**Comment by ncw** [comment]
Thanks for your comments.

I think that this is a nice idea, but falls into the "too difficult" category unfortunately!

Hopefully the `rclone rcd` approach will work for you.

I'll close this now.
