### ISSUE TITLE
idea: that rclone asks: there is a newer file would you like to overwrite

### ISSUE THREAD

**Issue by diettelo** [rclone/rclone#5146]
Idea

if you made a mistake and choose Rclone save _download_ instead of Rclone save _upload_,
that Rclone asks: There is a newer File would you like to Overwrite this or all file or none?
I overwrited a Save by Mistake , i wanted to backup it but choosed download instead of upload.
Rclone on Mister FPGA used

**Comment by albertony** [comment]
Have you seen the [`--interactive`](https://rclone.org/docs/#interactive) option? Is what you suggest something else?

**Comment by ivandeex** [comment]
https://rclone.org/docs/#usage

https://rclone.org/docs/#interactive
