### ISSUE TITLE
Swift: Server side copy doesn't work for large objects: Failed to copy: Too Large Object

### ISSUE THREAD

**Issue by gdacheux** [rclone/rclone#515]
Error message : "Failed to copy: Too Large Object" when i move a big file for a HUBIC container to another.
Version : rclone v1.29-48-ge2788aa?
System : Windows 7, 386

Command : 
rclone --config .rclone.conf --timeout=96h --drive-chunk-size=256M move "hubic:Disque2/127.Hours.2010.1080p.BluRay.x264-EbP.mkv" "hubic:default/Disque2/" 

LOG:
rclone --config .rclone.conf --timeout=96h --drive-chunk-size=256M -v move "hubic:Disque2/127.Hours.2010.1080p.BluRay.x2
64-EbP.mkv" "hubic:default/Disque2/"
2016/06/08 13:13:06 rclone: Starting with parameters ["rclone" "--config" ".rclo
ne.conf" "--timeout=96h" "--drive-chunk-size=256M" "-v" "move" "hubic:Disque2/12
7.Hours.2010.1080p.BluRay.x264-EbP.mkv" "hubic:default/Disque2/"]
2016/06/08 13:13:07 Hubic: Got swift credentials (expiry 2016-06-09 05:28:23 +02
00 CEST in 16h15m15.7548829s)
2016/06/08 13:13:29 Hubic: Got swift credentials (expiry 2016-06-09 05:28:23 +02
00 CEST in 16h14m53.3251954s)
2016/06/08 13:13:30 Hubic Swift container default path Disque2/: Modify window i
s 1ns
2016/06/08 13:13:31 Hubic Swift container Disque2 limited to 1 objects: Building
 file list
2016/06/08 13:13:31 Hubic Swift container Disque2 limited to 1 objects: Done bui
lding file list
2016/06/08 13:13:31 Hubic Swift container default path Disque2/: Building file l
ist
2016/06/08 13:13:34 Hubic Swift container default path Disque2/: Done building f
ile list
2016/06/08 13:13:34 Hubic Swift container default path Disque2/: Waiting for che
cks to finish
2016/06/08 13:13:34 Hubic Swift container default path Disque2/: Waiting for tra
nsfers to finish
2016/06/08 13:14:10 127.Hours.2010.1080p.BluRay.x264-EbP.mkv: Failed to copy: To
o Large Object
2016/06/08 13:14:10 Hubic Swift container default path Disque2/: Not deleting fi
les as there were IO errors
2016/06/08 13:14:10 Attempt 1/3 failed with 1 errors
2016/06/08 13:14:10 Hubic Swift container Disque2 limited to 1 objects: Building
 file list
2016/06/08 13:14:10 Hubic Swift container Disque2 limited to 1 objects: Done bui
lding file list
2016/06/08 13:14:10 Hubic Swift container default path Disque2/: Building file l
ist
2016/06/08 13:14:11 Hubic Swift container default path Disque2/: Done building f
ile list
2016/06/08 13:14:11 Hubic Swift container default path Disque2/: Waiting for che
cks to finish
2016/06/08 13:14:11 Hubic Swift container default path Disque2/: Waiting for tra
nsfers to finish
2016/06/08 13:14:30
Transferred:            0Bytes (0Byte/s)
Errors:                 0
Checks:                 0
Transferred:            1
Elapsed time:     1m24.1s
Transferring:
- 127.Hours.2010.1080p.BluRay.x264-EbP.mkv

2016/06/08 13:14:32 127.Hours.2010.1080p.BluRay.x264-EbP.mkv: Failed to copy: To
o Large Object
2016/06/08 13:14:32 Hubic Swift container default path Disque2/: Not deleting fi
les as there were IO errors
2016/06/08 13:14:32 Attempt 2/3 failed with 1 errors
2016/06/08 13:14:33 Hubic Swift container Disque2 limited to 1 objects: Building
 file list
2016/06/08 13:14:33 Hubic Swift container Disque2 limited to 1 objects: Done bui
lding file list
2016/06/08 13:14:33 Hubic Swift container default path Disque2/: Building file l
ist
2016/06/08 13:14:34 Hubic Swift container default path Disque2/: Done building f
ile list
2016/06/08 13:14:34 Hubic Swift container default path Disque2/: Waiting for che
cks to finish
2016/06/08 13:14:34 Hubic Swift container default path Disque2/: Waiting for tra
nsfers to finish
2016/06/08 13:14:45 127.Hours.2010.1080p.BluRay.x264-EbP.mkv: Failed to copy: To
o Large Object
2016/06/08 13:14:45 Hubic Swift container default path Disque2/: Not deleting fi
les as there were IO errors
2016/06/08 13:14:45 Attempt 3/3 failed with 1 errors

Transferred:            0Bytes (0Byte/s)
Errors:                 1
Checks:                 0
Transferred:            3
Elapsed time:     1m38.4s

2016/06/08 13:14:45 Go routines at exit 2

**Comment by ncw** [comment]
I see, you are attempting a server side move of a large object.

I don't think that is supported directly by swift.

rclone should move the individual parts of the static large object.

**Comment by 131** [comment]
Same issue here, large object everywhere :x

**Comment by ivandeex** [comment]
@gdacheux @131 Does the problem reproduce with rclone 1.54?

**Comment by gdacheux** [comment]
Non, plus de problème.
Merci.

Le mar. 9 févr. 2021 à 16:29, Ivan Andreev <notifications@github.com> a
écrit :

**Comment by ivandeex** [comment]
@gdacheux Merci beaucoup
Closing stale issue
