### ISSUE TITLE
Better Support for Telia Sky (jottacloud)

### ISSUE THREAD

**Issue by sarmadjari** [rclone/rclone#5153]
#### What is your current rclone version (output from `rclone version`)?

- rclone v1.54.1
- os/arch: darwin/amd64
- go version: go1.16

#### What problem are you are trying to solve?

1- Have the Telia Cloud login does not work for Telia's Norwegian Customer, currently, the login goes to the Swedish page, where the Norwegian users can not login (different system?)
2- (probably will be solved by fixing first issue?) Using the token need to be refreshed every few hours, which mean need to delete the remote and create a new one! is there any permanent solution?

#### How do you think rclone should be changed to solve that?

if the upper issues are solved, maybe to be better documented? 

Thank you so much :)

**Comment by buengese** [comment]
I need a bit more information here. Is the oauth flow for norwegian telia cloud the same as swedish telia cloud just with different urls or are there other differences? Have you checked if norwegian telia cloud supports token based authentication? Current Telia cloud setup is indeed very specific to the swedish version.

**Comment by ivandeex** [comment]
@sarmadjari ???

**Comment by ivandeex** [comment]
@sarmadjari Please provide requested data

> Have you checked if norwegian telia cloud supports token based authentication?

**Comment by ivandeex** [comment]
Timed out waiting for info.

**Comment by Mendi6** [comment]
Hey, is there any way I can help you figure out this issue?

**Comment by Mendi6** [comment]
@ivandeex 
@sarmadjari

**Comment by utz-utz** [comment]
I could not make this work, changed backend/jottacloud/jottacloud.go to the following to make it work:

	teliaCloudTokenURL = "https://sky-auth.telia.no/auth/realms/get/protocol/openid-connect/token"
	teliaCloudAuthURL  = "https://sky-auth.telia.no/auth/realms/get/protocol/openid-connect/auth"

Should i commit this?
