### ISSUE TITLE
--ftp-ask-password flag for FTP

### ISSUE THREAD

**Issue by dmotte** [rclone/rclone#5160]
#### What is your current rclone version?

```
$ rclone --version
rclone v1.54.0
- os/arch: windows/amd64
- go version: go1.15.7
```

First of all, thanks for creating this awesome software and making it open and free for everyone 😄

I have an idea: it would be a good thing to add also an `--ftp-ask-password` flag that behaves like `--sftp-ask-password`, but for FTP. Let me know what you think

**Comment by ncw** [comment]
Great idea - thanks! Want to have a go at it?

**Comment by dmotte** [comment]
Yeah maybe I will try when i have some free time 👍

**Comment by bbutkovic** [comment]
I took a shot at this, it's my first contribution to the project, so please let me know if there's something I could have done better.
