### ISSUE TITLE
dropbox: Unable to decrypt returned paths from changeNotify

### ISSUE THREAD

**Issue by dennisoderwald** [rclone/rclone#5165]
#### What is the problem you are having with rclone?

As soon as many files are tried to be read at the same time, the "too_many_requests/..: Too many requests or write operations. Trying again in 300 seconds." error occurs. From that point on, no further log entries appear and the mount seems to have hung up. Neither a timeout nor any other attribute helps. Only a restart of the service solves the problem.

An attempt at 'df -h' or an 'ls' freezes completely.

With my Google Drive mount, the problem does not occur. I get i/o errors sometimes but it does not freeze.

#### What is your rclone version (output from `rclone version`)

rclone v1.54.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Ubuntu 18.04

####  Which cloud storage system are you using? (e.g. Google Drive)

Dropbox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
/usr/bin/rclone mount \
  --user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36' \
  --config=/home/admin/.config/rclone/rclone.conf \
  --allow-other \
  --allow-non-empty \
  --rc \
  --rc-addr=localhost:5572 \
  --fast-list \
  --vfs-read-chunk-size=64M \
  --vfs-read-chunk-size-limit=2048M \
  --buffer-size=64M \
  --dir-cache-time=1h \
  --timeout=1m \
  --attr-timeout=10m \
  --dropbox-chunk-size=64M \
  --umask=002 \
  --syslog \
  -vvv \
  dropbox: /mnt/remote
```

**Comment by darthShadow** [comment]
Can you try the latest beta and see if you can reproduce the issue with it? If so, please paste the log from that.

**Comment by dennisoderwald** [comment]
@darthShadow Thank you for your quick support. I'll test it out and get back to you.

**Comment by dennisoderwald** [comment]
I am now testing with the following version:

```
rclone v1.55.0-beta.5334.d6870473a
- os/type: linux
- os/arch: amd64
- go/version: go1.16.2
- go/linking: static
- go/tags: cmount
```

A message that I did not notice before or did not appear where I am at a loss right now:

```
2021/03/24 10:53:53 NOTICE: Encrypted drive 'dropbox:': ChangeNotify was unable to decrypt "1l77gk0gcijgrei4hlvr7ugoc/569vnmue4q5nvl9s5rhu8h2bt8/u8kc3jgspqf9sgh1ndi38nopmf9n5cdnpmbugv8k9sr8b5squlnt85l00sah3gp239oear3khr8je": illegal base32 data at input byte 25
2021/03/24 10:53:53 NOTICE: Encrypted drive 'dropbox:': ChangeNotify was unable to decrypt "1l77gk0gcijgrei4hlvr7ugoc/569vnmue4q5nvl9s5rhu8h2bt8/u8kc3jgspqf9sgh1ndi38nopmf9n5cdnpmbugv8k9sr8b5squlnt85l00sah3gp239oear3khr8je/f68s6an5n2fmffai81oqumadhfcmb8qj7omahnae53u3l9sm8uut9u2pg8q525q3p1o0n34g25pgu": illegal base32 data at input byte 25
```

Otherwise, it runs just felt more stable... but I continue to observe it...

**Comment by darthShadow** [comment]
Can you please add your redacted config?

**Comment by darthShadow** [comment]
@wolveix Can you take a look at this? I am guessing the `entryPath` manipulation we are doing in the `changeNotifyRunner` function in the dropbox remote is breaking the crypt decryption logic.

**Comment by wolveix** [comment]
I'll look into this shortly.

**Comment by dennisoderwald** [comment]
> Can you please add your redacted config?

```
[dropbox_unencrypted]
type = dropbox
token = {"access_token":"XXX","token_type":"bearer","refresh_token":"XXX","expiry":"2021-03-24T14:47:11.666625156+01:00"}

[dropbox]
type = crypt
remote = dropbox_unencrypted:Folder/Folder
filename_encryption = standard
directory_name_encryption = true
password = XXX (62 length)
password2 = XXX (62 length)
```

**Comment by dennisoderwald** [comment]
Do I understand this correctly: Everything is fine with my data, but polling is supported in the beta and here decryption does not work for data checked via polling?

**Comment by darthShadow** [comment]
Yes, you are correct.

**Comment by dennisoderwald** [comment]
> Yes, you are correct.

Okay, then I am reassured :) And look forward to @wolveix his fix.

**Comment by dennisoderwald** [comment]
> I'll look into this shortly.

Have you had time to look at it? :)

**Comment by dennisoderwald** [comment]
> I'll look into this shortly.

@wolveix Have you had time to look at it? :)

**Comment by wolveix** [comment]
> > I'll look into this shortly.
> 
> @wolveix Have you had time to look at it? :)

Sorry for the wait, been a busy week. I'll make sure to review this tomorrow :)

**Comment by dennisoderwald** [comment]
By the way, the original problem is not fixed with the latest beta. :( I first thought that this is now fixed but I guess I was wrong.

**Comment by wolveix** [comment]
Working on a fix now. I believe I've resolved the decryption issue, but I'm unsure about the original issue described in this request.

**Comment by dennisoderwald** [comment]
I was able to narrow it down to something to do with API errors like "too_many_requests" and the associated rate limit. It seems that not only new requests are postponed but also entries that actually come from the cache are not answered anymore.

**Comment by wolveix** [comment]
Thanks. Yeah, I've noticed the same behaviour a couple of times. It does eventually resolve itself in my experience, but it's not ideal and I'd like to gain a better understanding as to why it's happening. I don't believe it's an issue strictly with the polling implementation, but I can't say for sure. I'll continue reviewing this prior to committing the potential fix for the decryption issue, but it'd be great if @ncw could find the time to also review this.

**Comment by wolveix** [comment]
Okay, a few interesting notes. In my testing, I create a directory containing a bunch of files (I just do `cp */*.go thisisatest/` from rclone's source and upload the resulting directory), delete a couple of files, and make sure between actions that the changes are reflected via polling to a mount. 

One thing I can consistently reproduce is this: if you touch two files, then upload them via `rclone move remote:/file_name` with about a second between the uploads, the first one will always be picked up just fine through polling. The second one will always encounter a decrypt failure. If you upload a folder with many files in, it will usually be picked up without issue. 

I'm going to spend more time going over the full existing implementation tomorrow. The strange thing is that my server (running `v1.55.0-beta.5239.b029fb591`) has been running for a month without issues (no decrypt errors in the log). But when carrying out the same testing as above, the issues are correctly reproduced. But my regular uploads are absolutely fine.

**Comment by jkristoph** [comment]
@dennisoderwald do you happen to be using this with cloudbox? I've been trying for weeks to get polling to work. Does not seem to work on encrypted or unencrypted dropbox remotes.

**Comment by dennisoderwald** [comment]
> @dennisoderwald do you happen to be using this with cloudbox? I've been trying for weeks to get polling to work. Does not seem to work on encrypted or unencrypted dropbox remotes.

No, outside of cloudbox. However, this has nothing to do with cloudbox, so the issue.

**Comment by jkristoph** [comment]
> > @dennisoderwald do you happen to be using this with cloudbox? I've been trying for weeks to get polling to work. Does not seem to work on encrypted or unencrypted dropbox remotes.
> 
> No, outside of cloudbox. However, this has nothing to do with cloudbox, so the issue.

I was just grabbing at straws, I've been unable to get polling to work. I'm pulling out my hair.

**Comment by wolveix** [comment]
> > > @dennisoderwald do you happen to be using this with cloudbox? I've been trying for weeks to get polling to work. Does not seem to work on encrypted or unencrypted dropbox remotes.
> > 
> > No, outside of cloudbox. However, this has nothing to do with cloudbox, so the issue.
> 
> I was just grabbing at straws, I've been unable to get polling to work. I'm pulling out my hair.

Please open a new issue with debug logs and we'll figure it out :)

**Comment by wolveix** [comment]
> [On the forum](https://forum.rclone.org/t/dropbox-too-many-requests-or-write-operations-trying-again-in-15-seconds/23316/15?u=ncw) PatriotM noted:
> 
> > it looks like it can't find the file path because 2 characters are cut off at the beginning cutted
> 
> Check the link for an image and more explanation.
> 
> This looks like it might be the cause of the problem @wolveix 

Huh, I'm not sure how I could've missed that, and I'm not sure why it still seems to work in my use case.

Nevertheless, I will look into this today and hopefully resolve the issue.

**Comment by dennisoderwald** [comment]
That would solve the problem with polling but probably not that it freezes at a rate limit? Or?

**Comment by wolveix** [comment]
> That would solve the problem with polling but probably not that it freezes at a rate limit? Or?

That's probably right. Are you using your own client ID with Rclone? If not, I'd start there.

**Comment by jkristoph** [comment]
Hoping this is the reason my polling has never worked! @wolveix thanks for fixing this!

**Comment by ncw** [comment]
@dennisoderwald wrote
> That would solve the problem with polling but probably not that it freezes at a rate limit?

This should affect the "unable to decrypt returned paths" problem.

See https://github.com/rclone/rclone/issues/5156 too many requests problem - there is a binary to try there too.

**Comment by dennisoderwald** [comment]
@ncw Thanks, I'll take a look.

I just noticed that when a file is broken, Dropbox refuses to upload the file. It would be good if rclone would detect this directly and offer an option to skip these files. Or?

Because that's how it tries to synchronize the file over and over again.

Log example:
> 2021-04-19 16:24:01 ERROR : 532.db: Failed to copy: upload failed: Post "https://content.dropboxapi.com/2/files/upload_session/finish": unexpected EOF

**Comment by ncw** [comment]
I think I've managed to fix this problem - can you give this a try?

[v1.56.0-beta.5412.bba3e3e4f.fix-5165-dropbox-changenotify](https://beta.rclone.org/branch/fix-5165-dropbox-changenotify/v1.56.0-beta.5412.bba3e3e4f.fix-5165-dropbox-changenotify/) on branch [fix-5165-dropbox-changenotify](https://github.com/rclone/rclone/tree/fix-5165-dropbox-changenotify) (uploaded in 15-30 mins)

**Comment by wolveix** [comment]
> I think I've managed to fix this problem - can you give this a try?
> 
> [v1.56.0-beta.5412.bba3e3e4f.fix-5165-dropbox-changenotify](https://beta.rclone.org/branch/fix-5165-dropbox-changenotify/v1.56.0-beta.5412.bba3e3e4f.fix-5165-dropbox-changenotify/) on branch [fix-5165-dropbox-changenotify](https://github.com/rclone/rclone/tree/fix-5165-dropbox-changenotify) (uploaded in 15-30 mins)

Damn, of course it was something simple. I'm unfamiliar with the differences between `TrimLeft` and `TrimPrefix`. I'll test out the fix shortly as I was able to reliably reproduce the issue in testing.

**Comment by ncw** [comment]
> Damn, of course it was something simple. I'm unfamiliar with the differences between `TrimLeft` and `TrimPrefix`. I'll test out the fix shortly as I was able to reliably reproduce the issue in testing.

I just had a quick scan through the code looking for places where the path name was manipulated and that leapt out at me! Or rather I thought - what does `strings.TrimLeft` - not used that before - do and looked up the docs for it.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.56

I'll also put it in v1.55.1

**Comment by jkristoph** [comment]
Working thank you!!

**Comment by jkristoph** [comment]
I'm seeing polling functioning perfectly for some files, where others are being omitted...

**Comment by ncw** [comment]
> I'm seeing polling functioning perfectly for some files, where others are being omitted...

Omitted as in not present in the poll? That is likely a different problem so can you make a new issue with instructions on how to reproduce?

**Comment by dennisoderwald** [comment]
@ncw Thanks a lot, the fix helped! Had you seen my comment regarding broken files or was it lost?

**Comment by ncw** [comment]
> Thanks a lot, the fix helped!

Great

>  Had you seen my comment ([#5165 (comment)](https://github.com/rclone/rclone/issues/5165#issuecomment-822527471)) regarding broken files or was it lost?

I'm not sure what the problem is here?

**Comment by dennisoderwald** [comment]
> I'm not sure what the problem is here?

@ncw Providers like Dropbox check the state of the file when uploading and if the file is corrupted, the following error is returned:

> 2021-04-19 16:24:01 ERROR : 532.db: Failed to copy: upload failed: post "https://content.dropboxapi.com/2/files/upload_session/finish": unexpected EOF

This will cause the file to be uploaded again with each execution until it finally fails with the error.

**Comment by ncw** [comment]
> Providers like Dropbox check the state of the file when uploading and if the file is corrupted, the following error is returned:
> 
> > 2021-04-19 16:24:01 ERROR : 532.db: Failed to copy: upload failed: post "https://content.dropboxapi.com/2/files/upload_session/finish": unexpected EOF
> 
> This will cause the file to be uploaded again with each execution until it finally fails with the error.

The above error might be caused by a local file that was shortened during the upload process or something like that.

If you can make a reproduction for this, can you open a [new issue](https://github.com/rclone/rclone/issues/new/choose) with this in and we can look further.

Thanks
