### ISSUE TITLE
The command is slow and returns an error

### ISSUE THREAD

**Issue by yule-sun** [rclone/rclone#5166]
#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

I mounted a ceph bucket on my windows 2019 server. But when I use the rclone command, I find that the speed is relatively slow. Especially when there are more than one thousand directories and the total number of files exceeds 10 million, an error will be reported directly, as shown below. Where is the problem? Are there any parameters that can be optimized or solve this problem? Looking forward to your help and reply.

```
PS C:\Users\F3640212> (rclone lsd --fast-list ceph_oss_ISD:SysUpFile/HRPhoto).count
2021/03/24 10:53:58 ERROR : : error listing: SerializationError: failed to unmarshal error message
        status code: 504, request id: , host id:
caused by: UnmarshalError: failed to unmarshal error message
        00000000  3c 68 74 6d 6c 3e 3c 62  6f 64 79 3e 3c 68 31 3e  |<html><body><h1>|
00000010  35 30 34 20 47 61 74 65  77 61 79 20 54 69 6d 65  |504 Gateway Time|
00000020  2d 6f 75 74 3c 2f 68 31  3e 0a 54 68 65 20 73 65  |-out</h1>.The se|
00000030  72 76 65 72 20 64 69 64  6e 27 74 20 72 65 73 70  |rver didn't resp|
00000040  6f 6e 64 20 69 6e 20 74  69 6d 65 2e 0a 3c 2f 62  |ond in time..</b|
00000050  6f 64 79 3e 3c 2f 68 74  6d 6c 3e 0a              |ody></html>.|

caused by: expected element type <Error> but have <html>
2021/03/24 10:53:58 Failed to lsd with 2 errors: last error was: SerializationError: failed to unmarshal error message
        status code: 504, request id: , host id:
caused by: UnmarshalError: failed to unmarshal error message
        00000000  3c 68 74 6d 6c 3e 3c 62  6f 64 79 3e 3c 68 31 3e  |<html><body><h1>|
00000010  35 30 34 20 47 61 74 65  77 61 79 20 54 69 6d 65  |504 Gateway Time|
00000020  2d 6f 75 74 3c 2f 68 31  3e 0a 54 68 65 20 73 65  |-out</h1>.The se|
00000030  72 76 65 72 20 64 69 64  6e 27 74 20 72 65 73 70  |rver didn't resp|
00000040  6f 6e 64 20 69 6e 20 74  69 6d 65 2e 0a 3c 2f 62  |ond in time..</b|
00000050  6f 64 79 3e 3c 2f 68 74  6d 6c 3e 0a              |ody></html>.|
```

**Comment by darthShadow** [comment]
Please add the other requested details too, i.e. a redacted config and the version of rclone.

**Comment by ncw** [comment]
It looks like the server timed out while reading the very long listing.

Either that or you have a web proxy between you and the server which timed out.

**Comment by yule-sun** [comment]
> Please add the other requested details too, i.e. a redacted config and the version of rclone.
Thank you very much for your reply，I don't know if you have ever used rclone to synchronize folders with more than 10 million files? Are there any parameters that can improve the concurrent processing capability after rclone mount?
rclone version：
PS C:\Users\F3640212> rclone version
rclone v1.53.4
- os/arch: windows/amd64
- go version: go1.15.6

rclone config：
PS C:\Users\F3640212> Get-Content 'C:\Program Files\rclone\rclone.conf'
[ceph_oss_ISD]
type = s3
provider = Ceph
env_auth = false
access_key_id = KHFSC********FTZP1JL
secret_access_key = CrjORIagjo********************QU1TcAv5
endpoint = http://172.18.218.254:6780
acl = bucket-owner-full-control

**Comment by yule-sun** [comment]
> It looks like the server timed out while reading the very long listing.
> 
> Either that or you have a web proxy between you and the server which timed out.

Yes it is time out, but i have no proxy server between my windows server and ceph cluster server. I think this must be caused by too many files in a single directory, but I don’t know the specific restrictions, and I don’t know how to improve the speed and performance of this access. Can you take the time to help me?

**Comment by darthShadow** [comment]
You can try experimenting with lower values of `list_chunk` (https://rclone.org/s3/#s3-list-chunk). It defaults to 1000 so you can try 500 and see if that works or go even lower.

You can also try removing `--fast-list` and see if that works better.

**Comment by darthShadow** [comment]
This should also help once it's merged: https://github.com/rclone/rclone/pull/5088 so subscribe to that PR to try out the latest beta once it's available.

**Comment by yule-sun** [comment]
> You can try experimenting with lower values of `list_chunk` (https://rclone.org/s3/#s3-list-chunk). It defaults to 1000 so you can try 500 and see if that works or go even lower.
> 
> You can also try removing `--fast-list` and see if that works better.

Thank you very much for your reply, sir. Sometimes I can use the command _(rclone lsd --fast-list ceph_oss_ISD:SysUpFile/HRPhoto).count_ to get the file numbers, but it will take me a long time.

Is it possible to mount a directory containing more than 10 million small files in the bucket to a local disk, and then implement sftp access?

**Comment by darthShadow** [comment]
Removing `--fast-list` and increasing `--checkers` to 8 or 16 should give you a significant speedup.

> Is it possible to mount a directory containing more than 10 million small files in the bucket to a local disk, and then implement sftp access?

It's possible but the timeouts can happen there too.

**Comment by yule-sun** [comment]
> (rclone lsd --fast-list ceph_oss_ISD:SysUpFile/HRPhoto).coun

Hi  sir
I modified the command to look like the following, but I still got this error. 
PS C:\Windows\system32> _(rclone lsd --checkers=8 ceph_oss_ISD:SysUpFile/HRPhoto).count_
2021/03/26 08:10:25 ERROR : : error listing: SerializationError: failed to unmarshal error message
        status code: 504, request id: , host id:
caused by: UnmarshalError: failed to unmarshal error message
        00000000  3c 68 74 6d 6c 3e 3c 62  6f 64 79 3e 3c 68 31 3e  |<html><body><h1>|
00000010  35 30 34 20 47 61 74 65  77 61 79 20 54 69 6d 65  |504 Gateway Time|
00000020  2d 6f 75 74 3c 2f 68 31  3e 0a 54 68 65 20 73 65  |-out</h1>.The se|
00000030  72 76 65 72 20 64 69 64  6e 27 74 20 72 65 73 70  |rver didn't resp|
00000040  6f 6e 64 20 69 6e 20 74  69 6d 65 2e 0a 3c 2f 62  |ond in time..</b|
00000050  6f 64 79 3e 3c 2f 68 74  6d 6c 3e 0a              |ody></html>.|

caused by: expected element type <Error> but have <html>
2021/03/26 08:10:26 Failed to lsd with 2 errors: last error was: SerializationError: failed to unmarshal error message
        status code: 504, request id: , host id:
caused by: UnmarshalError: failed to unmarshal error message
        00000000  3c 68 74 6d 6c 3e 3c 62  6f 64 79 3e 3c 68 31 3e  |<html><body><h1>|
00000010  35 30 34 20 47 61 74 65  77 61 79 20 54 69 6d 65  |504 Gateway Time|
00000020  2d 6f 75 74 3c 2f 68 31  3e 0a 54 68 65 20 73 65  |-out</h1>.The se|
00000030  72 76 65 72 20 64 69 64  6e 27 74 20 72 65 73 70  |rver didn't resp|
00000040  6f 6e 64 20 69 6e 20 74  69 6d 65 2e 0a 3c 2f 62  |ond in time..</b|
00000050  6f 64 79 3e 3c 2f 68 74  6d 6c 3e 0a              |ody></html>.|

caused by: expected element type <Error> but have <html>
0

However, when I use the ls command like the below , I can get the number of data in the entire directory, but it takes a long time.  （There are 9004 subdirectories and 14,390,479 files in this directory.）

PS C:\Windows\system32> measure-command {(rclone ls --fast-list ceph_oss_ISD:SysUpFile/HRPhoto).count}

Days              : 0
Hours             : 3
Minutes           : 59
Seconds           : 4
Milliseconds      : 349
Ticks             : 143443499659
TotalDays         : 0.166022569049769
TotalHours        : 3.98454165719444
TotalMinutes      : 239.072499431667
TotalSeconds      : 14344.3499659
TotalMilliseconds : 14344349.9659

**Comment by darthShadow** [comment]
Can you with reducing the `--s3-list-chunk` to `500`?

**Comment by yule-sun** [comment]
> Can you with reducing the `--s3-list-chunk` to `500`?

The same error sir
PS C:\Windows\system32> (rclone lsd --s3-list-chunk=500 ceph_oss_ISD:SysUpFile/HRPhoto).count
2021/03/26 18:52:50 ERROR : : error listing: SerializationError: failed to unmarshal error message
        status code: 504, request id: , host id:
caused by: UnmarshalError: failed to unmarshal error message
        00000000  3c 68 74 6d 6c 3e 3c 62  6f 64 79 3e 3c 68 31 3e  |<html><body><h1>|
00000010  35 30 34 20 47 61 74 65  77 61 79 20 54 69 6d 65  |504 Gateway Time|
00000020  2d 6f 75 74 3c 2f 68 31  3e 0a 54 68 65 20 73 65  |-out</h1>.The se|
00000030  72 76 65 72 20 64 69 64  6e 27 74 20 72 65 73 70  |rver didn't resp|
00000040  6f 6e 64 20 69 6e 20 74  69 6d 65 2e 0a 3c 2f 62  |ond in time..</b|
00000050  6f 64 79 3e 3c 2f 68 74  6d 6c 3e 0a              |ody></html>.|

caused by: expected element type <Error> but have <html>
2021/03/26 18:52:50 Failed to lsd with 2 errors: last error was: SerializationError: failed to unmarshal error message
        status code: 504, request id: , host id:
caused by: UnmarshalError: failed to unmarshal error message
        00000000  3c 68 74 6d 6c 3e 3c 62  6f 64 79 3e 3c 68 31 3e  |<html><body><h1>|
00000010  35 30 34 20 47 61 74 65  77 61 79 20 54 69 6d 65  |504 Gateway Time|
00000020  2d 6f 75 74 3c 2f 68 31  3e 0a 54 68 65 20 73 65  |-out</h1>.The se|
00000030  72 76 65 72 20 64 69 64  6e 27 74 20 72 65 73 70  |rver didn't resp|
00000040  6f 6e 64 20 69 6e 20 74  69 6d 65 2e 0a 3c 2f 62  |ond in time..</b|
00000050  6f 64 79 3e 3c 2f 68 74  6d 6c 3e 0a              |ody></html>.|

caused by: expected element type <Error> but have <html>

**Comment by ivandeex** [comment]
@darthShadow @ncw @animosity22 
Let's answer this or close this

**Comment by darthShadow** [comment]
@yule-sun Are you still seeing the issue on the latest release?

**Comment by ivandeex** [comment]
this one got stale :(

**Comment by ivandeex** [comment]
It's a shame no solution has been found
