### ISSUE TITLE
Onedrive URL Token Request

### ISSUE THREAD

**Issue by aayush-ag** [rclone/rclone#5170]
#### What is the problem you are having with rclone?
When using rclone with custom endpoints that is token and authorize url in headless machine the new urls are not sent which is causing issue in getting the token.

#### What is your rclone version (output from `rclone version`)

rclone v1.54.1
- os/arch: linux/amd64
- go version: go1.15.8

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 10 64 bit , Ubuntu 20 Server 64 Bit (Both latest and updated), Actually irrelevant for this problem.

####  Which cloud storage system are you using? (e.g. Google Drive)
Onedrive ( But suspect problem in another remote as well in which custom endpoints are required for token refresh)

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone config -> token update

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

irrelevant.

**Comment by Cnly** [comment]
Hi @aayush-ag, did you mean that if you've configured the remote with a custom API endpoint, the `rclone authorize` command won't work properly? But still, I'm not sure what you mean by "custom endpoint" for the OneDrive backend, as I don't think you can actually customise it...

**Comment by aayush-ag** [comment]
It has custom api endpoint for authorize, token,etc. It is asked ehile configuring for custom api endpoint this is needed otherwise error has been seen if rclone provided api is used with custom client id.

**Comment by Cnly** [comment]
@aayush-ag okay, do you mean you're using one of the regional OneDrive variants?

**Comment by aayush-ag** [comment]
--onedrive-auth-url
Auth server URL. Leave blank to use the provider defaults.

Config: auth_url
Env Var: RCLONE_ONEDRIVE_AUTH_URL
Type: string
Default: ""
--onedrive-token-url
Token server url. Leave blank to use the provider defaults.

Config: token_url
Env Var: RCLONE_ONEDRIVE_TOKEN_URL
Type: string
Default: ""

**Comment by aayush-ag** [comment]
These are not passesd.

**Comment by Cnly** [comment]
Ah, I see what you mean now. Actually, this should've been fixed by https://github.com/rclone/rclone/issues/5178. Could you please try the latest beta?

**Comment by ivandeex** [comment]
4 months of no reply from user

**Comment by aayush-ag** [comment]
it is fixed please mark it resolved.
