### ISSUE TITLE
rclone authorize not workng with zoho and others

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#5178]
I noticed just now that if you attempt to use `rclone authorize` with zoho then it fails because `region` is not set and it ends up trying to look up `auth.zoho.` (no extension).

The check for region being set needs to include `region == ""` here

https://github.com/rclone/rclone/blob/20c5ca08fbf4222178f01ccd47dca8d04c237be8/backend/zoho/zoho.go#L163-L166

Anyway, that won't fix the problem, it will just make it blow up neatly with an error message.

I think what we need to be doing is passing the whole `m` into `rclone authorize` (minus the token) otherwise `rclone authorize` won't know what the `region` is.

Zoho isn't the only backend with this problem, pcloud and sharefile have it too off the top of my head. Sharefile sets things in the config file on rclone oauth so ideally the return from `rclone authorize` should be an update to `m` including the token.

@buengese - thoughts?

**Comment by buengese** [comment]
Ah yeah, that's true. For zoho we definitely need the region. I'll push the fix to at least give the correct error. 

For fixing `rclone authorize` we could have `oauthutil.Config` output a serialized version of the config map which can then be passed to `rclone authorize`.

**Comment by ncw** [comment]
I've had a go at fixing this in the [fix-5178-authorize branch](https://github.com/rclone/rclone/tree/fix-5178-authorize).

This seems to work in my tests.

Can you have a go with it @buengese ?

This encodes the configmap into a base64 encoded JSON blob and the same is returned from `rclone authorize`. This works with zoho other than the odditiy of having to answer the post config questions twice.

Do you think the base64 encoded blobs are OK? I decided to use those rather than plain JSON as JSON is rather difficult to escape on the command line - those `""` are difficult to escape on Windows.

**Comment by buengese** [comment]
That's excellent and definitely works for me to. 
> This works with zoho other than the odditiy of having to answer the post config questions twice.
In theory, we could have `oauthutil.Config` communicate back that it ran in headless mode and skip the rest of the config function based on it.

>Do you think the base64 encoded blobs are OK?
Base64 encoded JSON is the obvious choice here and avoids all the unnecessary problems. There aren't many reasons why you'd want to read or modify it other than debugging maybe, and it's not like it takes more than a second or so to decode base64.

**Comment by ncw** [comment]
> That's excellent and definitely works for me to.
> 
> > This works with zoho other than the odditiy of having to answer the post config questions twice.
> 
> In theory, we could have `oauthutil.Config` communicate back that it ran in headless mode and skip the rest of the config function based on it.

I think we do that in the drive backend, let me check...

https://github.com/rclone/rclone/blob/0caf417779c35457f923b6d84879318711f98db5/backend/drive/drive.go#L956-L959

Not entirely sure that is sensible but that is what it does to avoid the same thing on the drive backend.

> > Do you think the base64 encoded blobs are OK?
> 
> Base64 encoded JSON is the obvious choice here and avoids all the unnecessary problems. There aren't many reasons why you'd want to read or modify it other than debugging maybe, and it's not like it takes more than a second or so to decode base64.

Great!

Thanks for testing :-)

**Comment by ncw** [comment]
I've pushed this now. I saw your fix for the above :-)

Thanks for testing.
