### ISSUE TITLE
Google Drive Team Drive Config - Error 403: Insufficient Permissions

### ISSUE THREAD

**Issue by StuffonGithub** [rclone/rclone#5179]
#### What is the problem you are having with rclone?
Error mounting a new shared drive. Using cmd just crashes, Powershell at least shows what the error is.
I've mounted dozens of shared drives before this but this is the first error I've encountered (first time mounting on this account though).

I tried adding all scopes listed under the OAuth consent screen though nothing changed. But I'm tech illiterate so I have no idea what I'm doing in the first place. Sorry.

#### What is your rclone version (output from `rclone version`)
rclone v1.54.1
- os/arch: windows/amd64
- go version: go1.15.8

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 10 64-bit

####  Which cloud storage system are you using? (e.g. Google Drive)
Google Drive (Shared Drive)

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone config

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
Every other settings are set to "default". This is the only non-default option I've set.
```
Configure this as a Shared Drive (Team Drive)?
y) Yes
n) No (default)
y/n> y
Fetching Shared Drive list...
2021/03/30 01:07:00 Failed to configure Shared Drive: listing Team Drives failed: googleapi: Error 403: Insufficient Permission: Request had insufficient authentication scopes., insufficientPermissions
```

**Comment by albertony** [comment]
> Error mounting a new shared drive. 

Are you talking about the [`rclone mount`](https://rclone.org/commands/rclone_mount/) command? If so, what is the exact command line.

> Using cmd just crashes

Or is the problem running the `rclone config` command?

**Comment by StuffonGithub** [comment]
@albertony Oh sorry for the confusion, I'm not really used to the CLI since I've been using rclonebrowser (but I've also tried doing this by running the command manually). So, it is running the `rclone config` command.

And just to add, the cmd only crashes after the `Fetching Shared Drive list...` part.

**Comment by henrypinkard** [comment]
Also having this issue:

```
Configure this as a Shared Drive (Team Drive)?
y) Yes
n) No (default)
y/n> y
Fetching Shared Drive list...
2021/04/27 19:17:51 Failed to configure Shared Drive: listing Team Drives failed: googleapi: Error 403: Insufficient Permission: Request had insufficient authentication scopes., insufficientPermissions
```

**Comment by Nnidyu** [comment]
@henrypinkard what scope did you select at the beginning? I had the exact same problem and it was caused by selecting "drive.file" scope instead of "drive".

**Comment by henrypinkard** [comment]
I tried both with no success. I did end up fixing it logging in with a different account that had access to the same team drive. I also rolled back to an earlier version of rclone, but not sure this did anything

**Comment by ivandeex** [comment]
Regular cleanup of answered tickets
