### ISSUE TITLE
using --vfs-cache-mode full is slower than not using the cache

### ISSUE THREAD

**Issue by LeendertPlas** [rclone/rclone#5182]
#### What is the problem you are having with rclone?

Using the --vfs-cache-mode X functionality makes rclone start significantly slower. 

I expect the speed using the cache mode should only be different if the file is cached and that the starting speed should be the same, however this is not the case. Using the mount without the cache works in seconds, while with the case it takes a minute or doesn't even start at all. I'm using an NVME drive as a cache so i don't expect this to be the bottleneck. 

#### What is your rclone version (output from `rclone version`)

rclone v1.55.0-beta.5349.c0c74003f
- os/type: windows
- os/arch: 386
- go/version: go1.16.2
- go/linking: dynamic
- go/tags: cmount

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 10, 64 bit

####  Which cloud storage system are you using? (e.g. Google Drive)
 Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
` mount gdrive: X: --volname Drive_Lezen --read-only --config C:\Plex\Rclone\rclone.conf --cache-dir=C:\Cache --rc --rc-web-gui --rc-user=Leen --rc-pass=LeenGui --rc-serve --rc-addr :5572 --log-file=C:\Plex\Rclone\lezenlog.txt --size-only --timeout 1h --buffer-size=512M --dir-cache-time=96h --drive-chunk-size 128M --vfs-read-chunk-size=512M --vfs-cache-max-size 350G --vfs-read-chunk-size-limit off --vfs-cache-max-age 24h --cache-db-purge --vfs-read-ahead 2G `

VS.

`` mount gdrive: X: --volname Drive_Lezen --read-only --config C:\Plex\Rclone\rclone.conf --cache-dir=C:\Cache --rc --rc-web-gui --rc-user=Leen --rc-pass=LeenGui --rc-serve --rc-addr :5572 --log-file=C:\Plex\Rclone\lezenlog.txt --size-only --timeout 1h --buffer-size=512M --dir-cache-time=96h --drive-chunk-size 128M --vfs-read-chunk-size=512M --vfs-cache-mode full --vfs-cache-max-size 350G --vfs-read-chunk-size-limit off --vfs-cache-max-age 24h --cache-db-purge --vfs-read-ahead 2G ``

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

I have compared the two mounts by playing the same files and trying to do the same adjustments. The cache is now starting faster than the none cached one. Buy playback is still different. When i jumped forward in the two files, the non cached one started again in 4 seconds, while the other one took a minute to start playing again. When i tried it again there was no difference between the two.  

The logs are to big to paste so i linked them below. https://drive.google.com/drive/folders/1RDZFTsjsS__4LzTvcWKIm2uUXDDieJe5?usp=sharing

**Comment by darthShadow** [comment]
Logs, please.

**Comment by ivandeex** [comment]
@LeendertPlas 
We ask for logs to reproduce your problem. Taking logs is explained in the template.
We do all we can to make it simple for you. Please consider it seriously.

**Comment by ivandeex** [comment]
Probably related to
- https://forum.rclone.org/t/rclone-vfs-cache-mode-full-queuing-for-upload-delays-mount-time/22293
- https://forum.rclone.org/t/long-delay-in-mount-point-showing-up-on-windows/22672/6

Or not... We need logs to confirm!

**Comment by LeendertPlas** [comment]
how would i show this exactly in the logs? Do i need to run a different command that shows the speed?

**Comment by ivandeex** [comment]
our mind reader left us long ago.
my crystal ball is lost.
no logs - no bugs.

**Comment by LeendertPlas** [comment]
> our mind reader left us long ago.
> my crystal ball is lost.
> no logs - no bugs.

i have included logs

**Comment by LeendertPlas** [comment]
does anyone know? i have included logs

**Comment by darthShadow** [comment]
Your disk is probably the bottle-neck with the cache enabled. Please remove all the extra flags and just start with the defaults to get a baseline and add flags 1 by 1 to see their impact.

Make sure to read the docs thoroughly before trying anything: https://rclone.org/commands/rclone_mount/#vfs-cache-mode-full

**Comment by LeendertPlas** [comment]
> Your disk is probably the bottle-neck with the cache enabled (especially with the large `buffer-size`). Please remove all the extra flags and just start with the defaults to get a baseline and add flags 1 by 1 to see their impact.
> 
> Make sure to read the docs thoroughly before trying anything: https://rclone.org/commands/rclone_mount/#vfs-cache-mode-full

Thank you, I'll try this. But in theory the drive shouldn't be able to act as a bottleneck as it is a 2000MB/s nvme drive

**Comment by LeendertPlas** [comment]
the default settings are a lot faster, thank you. Maybe the developers were right when determining the optimal default settings :)
