### ISSUE TITLE
rclone sync with --auto-confirm still prompt interactive

### ISSUE THREAD

**Issue by Chup4Chups** [rclone/rclone#5186]
#### What is the problem you are having with rclone?

I am trying to add rclone sync in crontab but the global flag --auto-confirm still prompt interactive

```
$ rclone sync -i test BackupStorage:backup-test -v --auto-confirm

rclone: copy "test"?
y) Yes, this is OK (default)
n) No, skip this
s) Skip all copy operations with no more questions
!) Do all copy operations with no more questions
q) Exit rclone now.
y/n/s/!/q>
```

#### What is your rclone version (output from `rclone version`)
```
rclone v1.55.0
- os/type: linux
- os/arch: amd64
- go/version: go1.16.2
- go/linking: static
- go/tags: cmount
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Ubuntu 20.04.1 LTS

#### Which cloud storage system are you using? (e.g. Google Drive)
OpenStack Swift

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone sync -i test BackupStorage:backup-test -v --auto-confirm

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2021/04/01 08:22:30 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2021/04/01 08:22:30 DEBUG : rclone: Version "v1.55.0" starting with parameters ["rclone" "sync" "-i" "test" "BackupStorage:backup-test" "-vv" "--auto-confirm"]
2021/04/01 08:22:30 DEBUG : Creating backend with remote "test"
2021/04/01 08:22:30 DEBUG : fs cache: adding new entry for parent of "test", "/srv/test"
2021/04/01 08:22:30 DEBUG : Creating backend with remote "BackupStorage:backup-test"
2021/04/01 08:22:33 DEBUG : test: Need to transfer - File not found at Destination
rclone: copy "test"?
y) Yes, this is OK (default)
n) No, skip this
s) Skip all copy operations with no more questions
!) Do all copy operations with no more questions
q) Exit rclone now.
y/n/s/!/q>
```

**Comment by albertony** [comment]
After a quick look at the code, it seems to me that `--auto-confirm` is not intended to be related to `--interactive` (`-i`), although documentation was not of much help..
May I ask why you would want both, does not simply removing `--interactive` (`-i`) do what you want?

**Comment by Chup4Chups** [comment]
My bad, I just realized the -i is for interactive and indeed, it make no sense to put both -i and --auto-confirm...

**Comment by Nakilon** [comment]
I don't use `-i` but I get asked for copying the file `.gitignore`. How do I automatically Yes this?

**Comment by Nakilon** [comment]
Just wasted like half an hour trying to find in `rclone help flags` anything like `force`, `yes`, `--y`, `copy`, `prompt`, `supress`, `interactive`, `skip`, but it appeared that the first command here https://rclone.org/s3/#configuration already includes the `-i` that you copypaste not knowing that it's the cause of the prompt...

**Comment by ncw** [comment]
@Nakilon sorry! That `-i` is there to stop accidental data loss when using `rclone sync` for the first time, eg getting source and destination mixed up. That was a hard won lesson by rclone users and I really don't want to remove it.

**Comment by benwiley4000** [comment]
> Just wasted like half an hour trying to find in `rclone help flags` anything like `force`, `yes`, `--y`, `copy`, `prompt`, `supress`, `interactive`, `skip`, but it appeared that the first command here https://rclone.org/s3/#configuration already includes the `-i` that you copypaste not knowing that it's the cause of the prompt...

Thanks this comment helped me understand what was wrong on my end!

**Comment by BrunoWinck** [comment]
> @ncw "That `-i` is there to stop accidental data loss when using `rclone sync` for the first time".

I arrived here for the same reason. How to make it non-interactive.

The intention is good but I think that if the examples were using the long version "--interactive" instead of "-i", it would catch our attention when we have used rclone a few times and wish to remove the prompts.

**Comment by albertony** [comment]
> The intention is good but I think that if the examples were using the long version "--interactive" instead of "-i", it would catch our attention when we have used rclone a few times and wish to remove the prompts.

I think that is a very good idea! It's in general much more educational to use the long descriptive versions in documentation and examples. I've suggested the change, here: https://github.com/rclone/rclone/pull/6716. Add a comment there if you find any that you think I've missed.

**Comment by gazzaluty** [comment]
Hi - I'm looking for confirmation that the --auto-confirm should suppress the prompts I am seeing. 

y) Yes, this is OK (default)
n) No, skip this
s) Skip all remove directory operations with no more questions
!) Do all remove directory operations with no more questions
q) Exit rclone now.

My command does not have the interactive flag but has others which I don't thnk should clash.

rclone sync --verbose --auto-confirm --exclude
