### ISSUE TITLE
disable selfupdate for downstream packaging

### ISSUE THREAD

**Issue by SuperSandro2000** [rclone/rclone#5187]
#### What problem are you are trying to solve?

Automatically updating packages might not work or is not desired in downstream distros/packaging like NixOS/nixpkgs. Some flag to disable that feature would be cool.

#### How do you think rclone should be changed to solve that?

Add a compile time flag to disable the feature.

**Comment by ivandeex** [comment]
Will be `go build . -tags noselfupdate`
