### ISSUE TITLE
ncdu: output to file

### ISSUE THREAD

**Issue by jtagcat** [rclone/rclone#5189]
#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.54.0-DEV
- os/arch: linux/amd64
- go version: go1.15.8
```

#### What problem are you are trying to solve?
Have a well usable index of my remote storage. (If using by hand, avoiding re-scans where not needed.)

#### How do you think rclone should be changed to solve that?
Implement ncdu's `-o` (output to file) feature. There doesn't need to be any import or related. ncdu and other tools can handle it from there.

**Comment by ivandeex** [comment]
What's wrong about `rclone lsf -R` ?

**Comment by jtagcat** [comment]
As far as I know, you can't use rclone nor ncdu to open the file up interactively. Besides being easier to use, the data from ncdu also includes size and mtime info.

From ncdu manpages:
>        Since scanning a large directory may take a while, you can scan a directory and export the results for later viewing:
>
>         ncdu -1xo- / | gzip >export.gz
>         # ...some time later:
>         zcat export.gz | ncdu -f-

**Comment by ivandeex** [comment]
You should rather familiarize youself with lsf docs
https://rclone.org/commands/rclone_lsf/

It can do all you want right now without tricky pipes.

ncdu is designed for something else

**Comment by albertony** [comment]
ncdu uses plain json format, documented [here](https://dev.yorhel.nl/ncdu/jsonfmt). It can become large, hence the doc recommends gzipping it, but basically it is just json export/import as I understand it. To me it sounds like something that potentially could prove useful..

For reference:
- https://dev.yorhel.nl/ncdu/man
- https://dev.yorhel.nl/ncdu/jsonfmt

**Comment by ivandeex** [comment]
`rclone lsjson -R`

https://rclone.org/commands/rclone_lsjson/

**Comment by albertony** [comment]
Right.. one can get the same information from that existing command. But not the ui part that ncdu provides for navigating in it later. Sure, one can use third party json tree viewers etc, or transform the json with some scripting, but still..

**Comment by jtagcat** [comment]
I looked at the ncdu format before as well. It works on inodes, not on directly parent directories etc.

For having a backup of remotes on all devices as an file index, this is somewhat acceptable; but yes, it doesn't give allow any interactivity.

For my index use case, this is a 'one person screams at the cloud' issue. I think I can pass with rclone mounts + ncdu for this.

I'd at least hope, that others could benefit from it, with better manipulation of rclone ncdu.

**Comment by jtagcat** [comment]
Closing for now as wontfix.

**Comment by ncw** [comment]
It would be relatively easy to transform the output of `rclone lsjson` into input that `ncdu -f` could use. You could probably even do it just with `jq` as that seems to be able to do anything! A 20 line python program would do it also.

**Comment by caretuse** [comment]
Use ramdisk (suck as `/dev/shm`) is recommend.

`jq` is required.

```
rm -rf K
mkdir K

rclone lsjson --copy-links --fast-list --recursive ~/ | jq -r '.[] |
select(.IsDir | not) |
[.IsDir, .Size, .Path, .Name, .Hashes.md5] |
@tsv' | while IFS=$'\t' read -r dir size path file md5
do
	echo $path
	mkdir -p "K/$(dirname "$path")"
	[ $size -ge 0 ] && echo $size >> "K/$path"
	[ $size -lt 0 ] && echo 0 >> "K/$path"
done

ncdu --follow-symlinks -o - K | sed 's/,"asize":[[:digit:]]*//g' >OK.json

rclone lsf --recursive --files-only K | while read file
do
	ino=$(ls -li "K/$file" | awk '{print $1}')
	size=$(find -inum $ino -exec cat {} \;)
	echo $ino
	sed -i s/'"dsize":[[:digit:]]*,"ino"':$ino/'"dsize":'$size',"ino"':$ino/g OK.json
done

rm -rf K
```

But I suggest rclone can dump json with ncdu format compliant, because `rclone lsjon` produces flat list, `ncdu` json is directory structure nested.

**Comment by FusionX9000** [comment]
Create a quick script for converting rclone lsjson to ncdu import file format.

```
#!/usr/bin/env python3

import datetime
import json
from pathlib import Path
import sys

# Exporting rclone lsjson:
# > rclone lsjson -R remote: > rclone-lsjson-dump

try:
    with Path(sys.argv[1]).expanduser().open("r") as f:
        data = json.load(f)
except:
    print("Usage: rclone-ncdu-export.py <rclone-json-file> [ncdu-json-file]")
    sys.exit(1)

root_tree_node = {"name": "root", "size": 0, "mtime": 0, "children": {}}

# Converting from flat to tree structure for easy parsing
for row in data:
    path_entries = row["Path"].split("/")

    tree_node = root_tree_node

    for entry in path_entries:
        if entry not in tree_node["children"]:
            tree_node["children"][entry] = {"children": {}}
        tree_node = tree_node["children"][entry]

    tree_node.update(
        {
            "name": path_entries[-1],
            "size": max(0, row["Size"]),
            "mtime": datetime.datetime.strptime(
                row["ModTime"], "%Y-%m-%dT%H:%M:%S%z"
            ).timestamp(),
        }
    )


# https://dev.yorhel.nl/ncdu/jsonfmt
def tree_to_ncdu(tree_node):
    directory = []

    infoblock = {
        "name": tree_node["name"],
        "asize": tree_node["size"],
        "dsize": tree_node["size"],
        "mtime": tree_node["mtime"],
    }

    for child_node in tree_node["children"].values():
        directory.append(tree_to_ncdu(child_node))

    if directory:
        return [infoblock] + directory
    else:
        return infoblock


ncdu_base = [1, 0, {"progname": "ncdu", "progver": "1.9", "timestamp": 1354477149}]

ncdu = ncdu_base + [tree_to_ncdu(root_tree_node)]

# Importing to ncdu
# > python3 rclone-lsjon-to-ncdu.py rclone-lsjson-dump
# > ncdu --apparent-size -ef rclone-ls-json-dump

if len(sys.argv) == 3:
    with Path(sys.argv[2]).open("w") as f:
        json.dump(ncdu, f)
else:
    print(json.dumps(ncdu))
```

How to use:
```bash
rclone lsjson -R remote: > rclone-lsjson-dump
python3 rclone-lsjon-to-ncdu.py rclone-lsjson-dump
ncdu --apparent-size -ef rclone-ls-json-dump
```
