### ISSUE TITLE
dropbox: Failed to create file system for "section": get current account failed: missing_scope/..

### ISSUE THREAD

**Issue by xdin0juvjzgch** [rclone/rclone#5193]
A new dropbox account with a new generated token, got a error message when lsd:

2021/04/02 15:18:33 DEBUG : rclone: Version "v1.54.1" starting with parameters ["rclone" "--config=rent_591_com_tw.conf" "lsd" "10_24_src_rclone:/" "-vv" "--log-file" "bug.log"]
2021/04/02 15:18:33 DEBUG : Using config file from "rent_591_com_tw.conf"
2021/04/02 15:18:33 DEBUG : Creating backend with remote "10_24_src_rclone:/"
2021/04/02 15:18:34 Failed to create file system for "10_24_src_rclone:/": get current account failed: missing_scope/..

**Comment by ivandeex** [comment]
You could see a nice shiny template when you submitted this.
You cold-heartedly wiped it out!
Please resubmit will all required data filled in.

**Comment by ncw** [comment]
Please retry with v1.55 as this has a dropbox scopes fix in.

**Comment by jkristoph** [comment]
Same issue as original poster on 1.55

**Comment by ncw** [comment]
Are you using --dropbox-impersonate?

See these docs:

https://rclone.org/dropbox/#dropbox-impersonate

You will need to `rclone config reconnect` with --dropbox-impersonate set - rclone will request the extra scope. You'll need to make your own dropbox client_id / client_secret for this I think.

**Comment by Muurilo** [comment]
@ncw can you give a example of the command? i tried to run this commands and not works, i have a app id configured

rclone config reconnect dropbox: --dropbox-impersonate
rclone config reconnect dropbox: --dropbox-impersonate true
rclone config reconnect dropbox: --dropbox-impersonate -

**Comment by ncw** [comment]
You'll need to try this with the latest beta https://beta.rclone.org as there were scopes missing which was fixed in 3e96752079c14c3a9051f52e4db4940238540d36

The expected syntax is

    rclone config reconnect dropbox: --dropbox-impersonate "email@example.com"

Though I think any value for `--dropbox-impersonate` will work at this point.

**Comment by Muurilo** [comment]
Now im getting this error after executing reconnect command

.\rclone.exe ls dropbox:/
2021/04/21 17:49:00 Failed to create file system for "dropbox:/": get current account failed: Error in call to API function "users/get_current_account": This API function operates on a single Dropbox account, but the OAuth 2 access token you provided is for an entire Dropbox Business team.  Since your API app key has team member file access permissions, you can operate on a team member's Dropbox by providing the "Dropbox-API-Select-User" HTTP header or "select_user" URL parameter to specify the exact user <https://www.dropbox.com/developers/documentation/http/teams>.

**Comment by Muurilo** [comment]
> Now im getting this error after executing reconnect command
> 
> .\rclone.exe ls dropbox:/
> 2021/04/21 17:49:00 Failed to create file system for "dropbox:/": get current account failed: Error in call to API function "users/get_current_account": This API function operates on a single Dropbox account, but the OAuth 2 access token you provided is for an entire Dropbox Business team. Since your API app key has team member file access permissions, you can operate on a team member's Dropbox by providing the "Dropbox-API-Select-User" HTTP header or "select_user" URL parameter to specify the exact user https://www.dropbox.com/developers/documentation/http/teams.

use default app id will fix this

**Comment by ncw** [comment]
> Now im getting this error after executing reconnect command
> 
> .\rclone.exe ls dropbox:/
> 2021/04/21 17:49:00 Failed to create file system for "dropbox:/": get current account failed: Error in call to API function "users/get_current_account": This API function operates on a single Dropbox account, but the OAuth 2 access token you provided is for an entire Dropbox Business team. Since your API app key has team member file access permissions, you can operate on a team member's Dropbox by providing the "Dropbox-API-Select-User" HTTP header or "select_user" URL parameter to specify the exact user https://www.dropbox.com/developers/documentation/http/teams.

I think you need to add --dropbox-impersonate to say which user you want to use. This will add the `Dropbox-API-Select-User` header.

**Comment by ivandeex** [comment]
3+ months of no reply from user
