### ISSUE TITLE
Cannot mount files, directory not found

### ISSUE THREAD

**Issue by djleo80** [rclone/rclone#5194]
#### Output of `rclone version`

rclone v1.56.0-DEV
- os/type: linux
- os/arch: amd64
- go/version: go1.16.2
- go/linking: dynamic
- go/tags: none

#### Describe the issue

Hi all, thanks for helping (or attempting to), sorry if this isn't the right place to put this.
After using rclone for a short while (maybe a few weeks) I went to mount a drive and got an error saying:

2021/04/02 09:20:20 ERROR : Local file system at /home/(username)/personal-onedrive: Statfs failed: directory not found

After trying a complete reinstall and using different kernels I seem to be out of ideas.

I am still fairly new to Linux and if I can't connect to my onedrive I will have to leave (again) :/ 
rclone is incredibly useful to me so thanks again to the developers.
sorry I don't have much to work with but if you need any logs etc I can help (hopefully)

I am using Manjaro when I got the issue and it seemed to be fine on debian

Thanks again!

**Comment by albertony** [comment]
Can you share the exact command you are using?

**Comment by djleo80** [comment]
rclone mount onedrive Onedrive/

**Comment by djleo80** [comment]
I also did rclone --vfs-cache-mode writes mount onedrive Onedrive
Then tried sync
I also changed the name of the remote to personal-onedrive and changed where it was syncing to.

**Comment by albertony** [comment]
> 2021/04/02 09:20:20 ERROR : Local file system at /home/(username)/personal-onedrive: Statfs failed: directory not found

This error was when you tried something like this, I assume:

`rclone mount personal-onedrive Onedrive/`

What you are trying to do is mount your **local** directory `/home/(username)/personal-onedrive` (via relative path) to another **local** directory `OneDrive`. And the directory `/home/(username)/personal-onedrive` does not exist, so the mount fails. Your command line is wrong.

First you need to configure a remote for OneDrive. My guess is that you already have this? If not, see https://rclone.org/onedrive/. If you do, and still have problems, please share the config as printed with command `rclone config show` - but **remove** any secrets!

Next you need to use the correct mount syntax as described here: https://rclone.org/commands/rclone_mount/

Example, where you must change the name "myonedrive" to match the actual name of your configured remote (which is not necessarily the same as the remote type which is "onedrive", and note the `:` which is important)

`rclone mount myonedrive: /home/(username)/onedrive`

**Comment by djleo80** [comment]
Ok I will try the command (I have already configured the remote correctly it's just bad naming) with the syntax and update you.
Thanks!

**Comment by djleo80** [comment]
Oh my goodness thank you so much, it was the syntax.
