### ISSUE TITLE
build: static build for linux is built with cmount tag

### ISSUE THREAD

**Issue by ivandeex** [rclone/rclone#5199]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/rclone-1-55-release/23217/18

#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.55.0

os/type: linux
os/arch: amd64
go/version: go1.16.2
go/linking: static
go/tags: cmount
```

#### What problem are you are trying to solve?

Static build for linux is built with tag `cmount` although only dynamic linked binary can really support `cmount`.

This can be seen from
- CI/CI log (`-include "^linux/" -tags "cmount"`) https://github.com/rclone/rclone/runs/2239533068?check_suite_focus=true#step:15:19
```
go run bin/cross-compile.go -release beta-latest -git-log /tmp/git-log.txt -include "^linux/" -tags "cmount"  v1.55.0
```

- Makefile https://github.com/rclone/rclone/blob/v1.55-stable/Makefile#L215
```
go run bin/cross-compile.go -release beta-latest -git-log /tmp/git-log.txt $(BUILD_FLAGS) $(BUILDTAGS) $(BUILD_ARGS) $(TAG)
```

#### How do you think rclone should be changed to solve that?

Patch `Makefile` and/or `bin/cross-compile.go` to apply `$(BUILDTAGS)` sparingly.

**Comment by ncw** [comment]
Perhaps it might be better to move this code

```
// +build cmount

package buildinfo

func init() {
	Tags = append(Tags, "cmount")
}
```

Into `cmd/cmount/mount.go` ?

`cmd/cmount` uses these build tags

```
// +build cmount
// +build cgo
// +build linux darwin freebsd windows
```

So potentially we could have this problem with combinations of non linux, windows, etc OSes.

Moving the tag into cmd/cmount would then have the advantage that the `cmount` tag means `rclone cmount` is compiled in.

What do you think?

**Comment by ivandeex** [comment]
will update the PR

**Comment by ivandeex** [comment]
will also add a comment in a file under `buildinfo` to refer to the real source with the tag

**Comment by ivandeex** [comment]
> Moving the tag into cmd/cmount would then have the advantage that the `cmount` tag means `rclone cmount` is compiled in.
> What do you think?

Done by latest commit in #5200

**Comment by ivandeex** [comment]
@ncw 
cmd/version was fixed, but this ticket requests to change the build itself.

**Comment by ncw** [comment]
> cmd/version was fixed, but this ticket requests to change the build itself. You can fix it or close with wontfix.

Ah you mean

> #### How do you think rclone should be changed to solve that?
> Patch `Makefile` and/or `bin/cross-compile.go` to apply `$(BUILDTAGS)` sparingly.

I think the fix we have now is better since it reflects whether `cmount` was actually compiled in rather than whether the tag was set in the build process and ignored because of something else. It is more of a feature flag than strictly speaking a go build tag.

Do you think we should try to remove the `cmount` tag from the places it isn't used? I can see that being quite tricky...

**Comment by ivandeex** [comment]
If you close this due to complexity, I'm fine with it. It was just a reminder.
