### ISSUE TITLE
sporadic race in TestMaxTransfer/Cautious

### ISSUE THREAD

**Issue by ivandeex** [rclone/rclone#5203]
#### The associated forum post URL from `https://forum.rclone.org`

N/A

#### What is the problem you are having with rclone?

TestMaxTransfer/Cautious fails race test with a substantial probability

#### What is your rclone version (output from `rclone version`)

1.55.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

CI/CD github runner

Current runner version: '2.277.1'
Operating System
  Ubuntu
  20.04.2
  LTS
  64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)

Local FS
Config file "/notfound" not found - using defaults

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

make racequicktest

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

- https://github.com/ivandeex/rclone/runs/2259965213?check_suite_focus=true#step:12:223
- [logs_1419.zip](https://github.com/rclone/rclone/files/6252653/logs_1419.zip)

**Comment by ncw** [comment]
I managed to get this to fail locally - this usually produces 2 or 3 test failures

    cd fs/sync
    go test -v -verbose -race -count=100  -run TestMaxTransfer/Cautious 2>&1 | tee race.log

I gave this 10,000 iterations locally so I think this fixes it.

[v1.56.0-beta.5370.54771e440.fix-5203-context-test](https://beta.rclone.org/branch/fix-5203-context-test/v1.56.0-beta.5370.54771e440.fix-5203-context-test/) on branch [fix-5203-context-test](https://github.com/rclone/rclone/tree/fix-5203-context-test) (uploaded in 15-30 mins)

I'll merge it if it passes the tests.
