### ISSUE TITLE
Some directories aren't copied from remote (pcloud) to local

### ISSUE THREAD

**Issue by N0ury** [rclone/rclone#5208]
#### Output of `rclone version`

rclone v1.53.3-DEV
- os/arch: linux/amd64
- go version: go1.15.8

#### Describe the issue

I first do a **copy** from remote (pcloud) to local (Linux) => no error, all seems ok
Then I do a **sync** from local to remote (dry-run mode) => some files are trying to be removed

Clean everything and retry first step => some files are missing (no errors), those that second step tried to remove.

The only common thin to these files is that that contain the string "/db/" in the path.

example:
2021/04/04 15:50:45 NOTICE: svn_2021-03-27/svn/formgen/db/transactions: Skipped remove directory as --dry-run is set
2021/04/04 15:50:45 NOTICE: svn_2021-03-27/svn/cours/db/txn-protorevs: Skipped remove directory as --dry-run is set
2021/04/04 15:50:45 NOTICE: svn_2021-03-27/svn/cours/db/transactions: Skipped remove directory as --dry-run is set
2021/04/04 15:50:45 NOTICE: svn_2021-03-27/svn/TP/db/txn-protorevs: Skipped remove directory as --dry-run is set
2021/04/04 15:50:45 NOTICE: svn_2021-03-27/svn/TP/db/transactions: Skipped remove directory as --dry-run is set

The problem is that some other files containing the same string are copied. Example:
svn_2021-03-27/svn/notifyme/db/revprops/0/4: Copied (new)

I'm lost!

**Comment by ncw** [comment]
> 2021/04/04 15:50:45 NOTICE: svn_2021-03-27/svn/formgen/db/transactions: Skipped remove directory as --dry-run is set
> 2021/04/04 15:50:45 NOTICE: svn_2021-03-27/svn/cours/db/txn-protorevs: Skipped remove directory as --dry-run is set
> 2021/04/04 15:50:45 NOTICE: svn_2021-03-27/svn/cours/db/transactions: Skipped remove directory as --dry-run is set
> 2021/04/04 15:50:45 NOTICE: svn_2021-03-27/svn/TP/db/txn-protorevs: Skipped remove directory as --dry-run is set
> 2021/04/04 15:50:45 NOTICE: svn_2021-03-27/svn/TP/db/transactions: Skipped remove directory as --dry-run is set

I'm guessing these are empty directories? If you want them then you'll need to add `--create-empty-src-dirs`

Can you do

    ls -l svn_2021-03-27/svn/formgen/db/transactions svn_2021-03-27/svn/cours/db/txn-protorevs

and paste the result?

**Comment by N0ury** [comment]
Bingo!
You are right @ncw these directories are empty.
I have tried with --create-empty-src-dirs and it works fine now.
I have added this option to a sync command too.
I do a copy every hours, and a sync once a day.
This way things go faster than with "mount".
I thought it was a bug.
Thanks a lot.
