### ISSUE TITLE
Local mount impossible after update

### ISSUE THREAD

**Issue by VilDegard** [rclone/rclone#5211]
#### What is the problem you are having with rclone?
Can't locally mount my drive after upgrading rclone to the latest update availalbe

#### What is your rclone version (output from `rclone version`)
rclone v1.55.0
- os/type: darwin
- os/arch: amd64
- go/version: go1.16.2
- go/linking: dynamic
- go/tags: cmount

#### Which OS you are using and how many bits (eg Windows 7, 64 bit)
macOS High Sierra version 10.13.6

####  Which cloud storage system are you using? (eg Google Drive)
Google drive ('plex-gdrive' remote for primary storage, 'plex-gdrive2' as backup/redundancy, 'plex-crypt' as encryption)

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)  

```
rclone mount plex-crypt: ~/pdrive
```
P.S: I've created the "pdrive" folder

#### The rclone config contents with secrets removed.  

```
plex-crypt           crypt
plex-gdrive          drive
plex-gdrive2         drive

[plex-crypt]
type = crypt
remote = plex-gdrive:/
filename_encryption = standard
directory_name_encryption = true
password = *** ENCRYPTED ***
password2 = *** ENCRYPTED ***
```

#### A log from the command with the `-vv` flag  

```
2021/04/04 21:20:29 DEBUG : Using config file from "/Users/USERNAME/.config/rclone/rclone.conf"
2021/04/04 21:20:29 DEBUG : rclone: Version "v1.55.0" starting with parameters ["rclone" "mount" "plex-crypt:" "/Users/nassim/pdrive" "-vv"]
2021/04/04 21:20:29 DEBUG : Creating backend with remote "plex-crypt:"
2021/04/04 21:20:29 DEBUG : Creating backend with remote "plex-gdrive:/"
2021/04/04 21:20:29 DEBUG : fs cache: renaming cache item "plex-gdrive:/" to be canonical "plex-gdrive:"
2021/04/04 21:20:30 DEBUG : Mounting on "/Users/USERNAME/pdrive" ("plex-crypt")
2021/04/04 21:20:30 DEBUG : Adding "-o modules=iconv,from_code=UTF-8,to_code=UTF-8-MAC" for macOS
2021/04/04 21:20:30 DEBUG : Encrypted drive 'plex-crypt:': Mounting with options: ["-o" "attr_timeout=1" "-o" "fsname=plex-crypt:" "-o" "subtype=rclone" "-o" "max_readahead=131072" "-o" "atomic_o_trunc" "-o" "volname=plex-crypt" "-o" "noappledouble" "-o" "modules=iconv,from_code=UTF-8,to_code=UTF-8-MAC"]
fuse: unknown option `atomic_o_trunc'
2021/04/04 21:20:30 ERROR : Encrypted drive 'plex-crypt:': Mount failed
2021/04/04 21:20:30 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed
MBP:~ USERNAME$ mount_osxfuse: failed to mount /Users/USERNAME/pdrive@/dev/osxfuse0: Socket is not connected
```

Thanks in advance for your support guys, much appreciated.

**Comment by ivandeex** [comment]
Let's dig in. Do the simple requests like `rclone about Remote:` and `rclone lsd Remote:` work with 1.55? With your previous rclone? (is it 1.54.1 btw?)

**Comment by ncw** [comment]
> fuse: unknown option `atomic_o_trunc'

This looks like the problem.

Can you make sure you are using the latest osxfuse/macfuse 4.x?

**Comment by VilDegard** [comment]
It worked, thanks Nick 👍
