### ISSUE TITLE
Issue when using with FUSE on M1 Mac

### ISSUE THREAD

**Issue by AyaanZaveri** [rclone/rclone#5216]
**Model:** M1 MacBook Air, 8GB RAM, 256 GB Storage
**Version:** macOS Big Sur 11.1 (20C69)

**Error:**
<img width="300" alt="Screen Shot 2021-04-06 at 5 45 09 PM" src="https://user-images.githubusercontent.com/63752541/113782205-d63bc400-96ff-11eb-8130-f28464f9a95c.png">

I tried to go to System Preferences and allowed Benjamin Fleischer but it didn't work.
Can I fix this?

**Comment by Zirro** [comment]
The answer you received in https://github.com/osxfuse/osxfuse/issues/795 still applies. It sounds like you'll either have to install the 11.3 beta or wait for the stable release.

**Comment by ivandeex** [comment]
It's an issue between MacOS and MacFUSE/osxFUSE.
Not much can rclone team do here.
