### ISSUE TITLE
Memory-only config file issues

### ISSUE THREAD

**Issue by albertony** [rclone/rclone#5222]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/rclone-1-55-with-config-dev-null/23355

#### What is the problem you are having with rclone?

Documentation at https://rclone.org/docs/#config-config-file:

> If the location is set to empty string "" or the special value /notfound, or the os null device represented by value NUL on Windows and /dev/null on Unix systems, then rclone will keep the config file in memory only.

##### Case 1. `--config /dev/null` on Linux

```
rclone \
    --config /dev/null \
    sync /local/path/ :sftp:remote_path/ \
    --sftp-host hidden --sftp-port hidden --sftp-user hidden --sftp-pass hidden \
    -v --bwlimit 80k:600k --max-delete 2 --transfers 1 --checkers 4 --size-only

2021/04/07 21:55:12 ERROR : Can't save config "md5sum_command" = "md5sum" for on the fly backend ":sftp"
2021/04/07 21:55:18 ERROR : Failed to save config after 10 tries: Failed to create temp file for new config: open /dev/null804515289: permission denied
2021/04/07 21:55:18 ERROR : Can't save config "sha1sum_command" = "sha1sum" for on the fly backend ":sftp"
2021/04/07 21:55:24 ERROR : Failed to save config after 10 tries: Failed to create temp file for new config: open /dev/null062934686: permission denied
```

##### Case 2. `--config NUL` on Windows

```
2021/04/08 08:47:22 ERROR : Failed to save config after 10 tries: Failed to create temp file for new config: open \NUL324278613: Access is denied.
```

##### Case 3. `--config ""`
```
rclone \
    --config "" \
    sync /local/path/ :sftp:remote_path/ \
    --sftp-host hidden --sftp-port hidden --sftp-user hidden --sftp-pass hidden \
    -v --bwlimit 80k:600k --max-delete 2 --transfers 1 --checkers 4 --size-only

2021/04/07 22:01:06 Failed to load config file "/tmp": read /tmp: is a directory
```
/tmp was the curent directory

##### Case 4. `--config /notfound`
```
rclone \
    --config /notfound \
    sync /local/path/ :sftp:remote_path/ \
    --sftp-host hidden --sftp-port hidden --sftp-user hidden --sftp-pass hidden \
    -v --bwlimit 80k:600k --max-delete 2 --transfers 1 --checkers 4 --size-only

2021/04/07 22:02:23 NOTICE: Config file "/notfound" not found - using defaults
2021/04/07 22:02:23 ERROR : Can't save config "md5sum_command" = "md5sum" for on the fly backend ":sftp"
2021/04/07 22:02:23 ERROR : Can't save config "sha1sum_command" = "sha1sum" for on the fly backend ":sftp"
#### What is your rclone version (output from `rclone version`)
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

rclone v1.55.0

os/type: linux
os/arch: amd64
go/version: go1.16.2
go/linking: static
go/tags: cmount

**Comment by albertony** [comment]
I am debugging Case 2, `--config NUL`, on Windows.

This part:

https://github.com/rclone/rclone/blob/ddb7eb6e0a9b07ad7be443b6c6f64bd7f372307d/fs/config/configflags/configflags.go#L271

Ends up in Windows API function GetFullPathNameW, which for "NUL" returns the special device path "\\\\.\\NUL", but then golang's filepath.Abs does a "Clean" before returning and it transforms it to "\\NUL".

But not only that: Even something like `--config NUL.conf` ends up being transformed to "\\NUL".



> If the path is a legacy DOS device such as CON, COM1, or LPT1, it is converted into a device path by prepending \\.\ and returned.
>
> A path that begins with a legacy device name is always interpreted as a legacy device by the Path.GetFullPath(String) method. For example, the DOS device path for CON.TXT is \\.\CON, and the DOS device path for COM1.TXT\file1.txt is \\.\COM1.

https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#handle-legacy-devices

>Do not use the following reserved names for the name of a file:
>
> CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.

https://docs.microsoft.com/en-gb/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN

@ncw: I don't know if this warrants a general fix, or its enough with quick and dirty:
- Update doc, "NUL" is no longer supported/allowed for config option on Windows as it states today.
- `if runtime.GOOS == "windows"` and then a regex to detect these names before calling filepath.Abs in configflags

**Comment by ncw** [comment]
Here is the commit that introduced the feature bb0b6432ae5d74a741815a8cc1f0cf2d46e3dddb

Note that these errors are saying you made a config with no config file `:sftp:` so we can't save it. These are to be expected. Maybe they shouldn't be ERROR though.

> 2021/04/07 22:02:23 ERROR : Can't save config "md5sum_command" = "md5sum" for on the fly backend ":sftp"
> 2021/04/07 22:02:23 ERROR : Can't save config "sha1sum_command" = "sha1sum" for on the fly backend ":sftp"

I can't immediately see the problem with 3. & 4 - are you OK to dig into this more?

With 1. & 2. maybe we should check for `os.DevNull` in `func (s *Storage) noConfig()` to fix both 1. & 2. ?

**Comment by albertony** [comment]
I can dig some more, yes.

**Comment by albertony** [comment]
@ncw ; I'm wondering about this:
https://github.com/rclone/rclone/blob/f52ae75a51a04188d728d8888112fb1fedb6c519/fs/fs.go#L1319-L1321

I'm thinking of changing it to Logf, but wondering: It does not return, but continues calling ConfigFileSet, doesn't that end up saving (or trying to) the config after all? I haven't been able to trigger it to test it yet, so just from reading the code..

**Comment by ncw** [comment]
> @ncw ; I'm wondering about this:
> https://github.com/rclone/rclone/blob/f52ae75a51a04188d728d8888112fb1fedb6c519/fs/fs.go#L1319-L1321
> 
> I'm thinking of changing it to Logf, but wondering: It does not return, but continues calling ConfigFileSet, doesn't that end up saving (or trying to) the config after all? I haven't been able to trigger it to test it yet, so just from reading the code..

Logf sounds good, and yes, duh, it needs to return and not continue!
