### ISSUE TITLE
Regression: --version requires configuration password

### ISSUE THREAD

**Issue by dandv** [rclone/rclone#5228]
In v1.50.2, running `rclone --version` with an encrypted config file would output the version.

In v1.55.0, the same command asks for the configuration password first. This should not be necessary, as none of the information output by `--version` seems related to the configuration.

```
$ rclone --version
Enter configuration password:
password:
rclone v1.55.0
- os/type: linux
- os/arch: amd64
- go/version: go1.16.2
- go/linking: static
- go/tags: cmount
```

(Also, the password prompt is doubled, but that's a separate issue.)

**Comment by ivandeex** [comment]
@ncw I guess it was caused by recent config patches.

**Comment by ncw** [comment]
> @ncw I guess it was caused by recent config patches.

Yes

>  Is it fixed by 1.55.1?

Not yet!

**Comment by albertony** [comment]
For info: v1.54.1 also does not ask for password, so its introduced with v1.55.

Workaround is to run with option for memory-only config, although it has its own [issue](https://github.com/rclone/rclone/issues/5222). But is there a plan for a better solution to this, avoiding the need for such option, for --version or even more generic?

**Comment by albertony** [comment]
Related to issue https://github.com/rclone/rclone/issues/5236, for which a *possible* solution described in comments will fix this one too.
