### ISSUE TITLE
Googledrive copy file to onedrive error, the file clearly exists

### ISSUE THREAD

**Issue by xixky** [rclone/rclone#5233]
user```rclone -P  --retries 1 copy --transfers=5   --disable copy  ss: 25:up``` Unable to copy
user```rclone -P copy --transfers=5  ss:up /mnt/gd && rclone -P copy --transfers=5  /mnt/gd 25:up``` Files can be copied

[1.log](https://github.com/rclone/rclone/files/6295492/1.log)

**Comment by darthShadow** [comment]
Removing the template of required information will only prevent us from helping you.

Please fill the full bug template.

**Comment by ncw** [comment]
Can you try doing that transfer to local disk and see if it works?

    rclone copy -vv 25:up1 /path/to/local/directory

If it doesn't work can you do 

    rclone lsf -R -vv 25:up1 --dump bodies 

And attach that result.

**Comment by xixky** [comment]
> Can you try doing that transfer to local disk and see if it works?
> 
> ```
> rclone copy -vv 25:up1 /path/to/local/directory
> ```
> 
> If it doesn't work can you do
> 
> ```
> rclone lsf -R -vv 25:up1 --dump bodies 
> ```
> 
> And attach that result.

Hello, I tested these commands in Google Cloud
run```rclone copy -vv 25:up1 ~/to/local/directory```,Generate log to 1.log。
[1.log](https://github.com/rclone/rclone/files/6300618/1.log)

run```rclone lsf -R -vv 25:up1 --dump bodies```,Generate log to 2.log。
[2.log](https://github.com/rclone/rclone/files/6300621/2.log)

**Comment by ncw** [comment]
The files definitely exists on drive.

That error `itemNotFound: Item not found` comes from onedrive not google drive.

Can you show your config please with `rclone config show`? Redact the tokens and post here please - thanks.

**Comment by xixky** [comment]
This is my onedrive configuration
[e1]
type = onedrive
client_id = 51a941f9-4c4c-4a96-b1f5-e92d269a7b3f
client_secret = xxxxxxxxxAG-H4~jxxxxxxxxxxxxxxxxxxxxxxx
token = xxxxxxxxx
drive_id = b!lxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc4iSJj0Wy3pY_Ih
drive_type = business

**Comment by xixky** [comment]
不是所有文件传输都出现错误，大概3-5%文件会出现```itemNotFound: Item not found```

**Comment by xixky** [comment]
For the files that have problems, use rclone to download and upload Google Cloud Disk again, and then synchronize with onedrive and there will be no problems.
