### ISSUE TITLE
Memory Problem

### ISSUE THREAD

**Issue by duczz** [rclone/rclone#5238]
#### What is the problem you are having with rclone?
Hey, in the current rclone Version i have a problem with my ram, with the following code the ram dont stop to grow. (he use than >3G RAM)

#### What is your rclone version (output from `rclone version`)
v1.55.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows Server 2016

#### Which cloud storage system are you using? (e.g. Google Drive)
Windows Network Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`"C:\rclone\rclone.exe" sync -i "\\XXXXXXXXX" "Z:\XXXXXXXXX" -P --checkers 1 --transfers 1 --buffer-size 0M --dry-run `

**Comment by ivandeex** [comment]
It's a pity you have problems with rclone. We are eager to fix bugs, but we need more data for analysis. Unfortunately you wiped out the bug template when you submitted this request. Please find a little time to help us fix this bug. Click "New issue / Bug ticket" and fill all relevant fields, especially "rclone version", "redacted config", and "log excerpt".

**Comment by ivandeex** [comment]
Closing as submitter disappeared.
