### ISSUE TITLE
Scan source before copy to get the real ETA

### ISSUE THREAD

**Issue by filippobottega** [rclone/rclone#5245]
Hello,
  I'm using the last version of rclone and I'm transferring ~300 GB of data.
  When I use -P option I get:

```
Transferred:       57.927G / 105.874 GBytes, 55%, 1.856 MBytes/s, ETA 7h20m59s
Checks:                40 / 40, 100%
Transferred:        12102 / 22114, 55%
Elapsed time:   8h52m47.1s
Transferring:
...
```

  The problem is that 105.874 GBytes is not the total amount to transfer and ETA 7h20m59s is wrong and changes when the total amount changes.
  I suppose that rclone is scanning the source while sending the files but I need that rclone end the source scan before starting the copy step. In this way I suppose that ETA will be correct.

  Is there a flag to get this behaviour?

  Thank you,
    Filippo.

**Comment by albertony** [comment]
Does this flag do what you want?

```
--check-first                          Do all the checks before starting transfers.
```
(https://rclone.org/flags/)

**Comment by filippobottega** [comment]
Yes! It's what i'm searching for!

Thank you @albertony !
