### ISSUE TITLE
RcloneBrowser - "Config" button not working on Ubuntu 18.04 & 20.04

### ISSUE THREAD

**Issue by Marella139** [rclone/rclone#5249]
#### What is the problem you are having with rclone?
After installing Rclone Browser on **Ubuntu 18.04 and 20.04 (x64)** I can't seem to bring up the Config option on Rclone GUI since the button is unresponsive after clicking on it.
![rclone-config-button](https://user-images.githubusercontent.com/53611626/115022894-527f9580-9ebe-11eb-905a-335006e074ed.png)

However, the same option is working normally on Ubuntu 16.04.

I would post this issue on the [RcloneBrowser repository](https://github.com/mmozeiko/RcloneBrowser) but it was archived before. Hope you understand that.

#### What is your rclone version (output from `rclone version`)
v1.53.3

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Ubuntu 18.04 & Ubuntu 20.04

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
These are the logs I got after trying to run **rclone-browser** as root on CLI:
```
user@rapidseedbox:~$ sudo rclone-browser

[sudo] password for user:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1298, resource id: 12729981, major code: 40 (TranslateCoords), minor code: 0

qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1522, resource id: 12730745, major code: 40 (TranslateCoords), minor code: 0

qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1989, resource id: 12732379, major code: 40 (TranslateCoords), minor code: 0

qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2205, resource id: 12733129, major code: 40 (TranslateCoords), minor code: 0
```

**Comment by ivandeex** [comment]
RcloneBrowser is a project independent from core rclone.
Please post this report to https://github.com/kapitainsky/RcloneBrowser/issues
