### ISSUE TITLE
OneDrive tenant-id support

### ISSUE THREAD

**Issue by TryTryAgain** [rclone/rclone#5250]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/onedrive-token-configuration-failure/13634/4

#### What is your current rclone version (output from `rclone version`)?

└❯ rclone --version
rclone v1.52.2
- os/arch: darwin/amd64
- go version: go1.14.4

and 

rclone v1.55.0
- os/type: linux
- os/arch: amd64
- go/version: go1.16.2
- go/linking: static
- go/tags: cmount

#### What problem are you are trying to solve?

Allow for specifying Azure tenant in the connection rather than needing to specify on the app registration setting. I feel opening the app registration up to multi-tenancy is unnecessary and people may be unlikely to use and could be avoided if rclone supported tenant-id.

#### How do you think rclone should be changed to solve that?

Add/support an additional OneDrive config and/or flag options for --onedrive-tenant-id?

**Comment by Cnly** [comment]
Hi @TryTryAgain, could you elaborate on why you think it's unnecessary and people may be unlikely to use this setting? Choosing the longest multi-tenant option allows the app to also work for OneDrive for Personal, and avoids the need to look up tenant properties and manually specifying an extra config item.

**Comment by TryTryAgain** [comment]
Hi @Cnly 

If tenant-id was supported a company wouldn't need to open up the app registration to multi-tenant and potentially expose to other tenants. I'm not saying it should be taken out with regards to the current way it's working similar to if you omit certain other details it works with default but if you include tenant-id it could work for an app registration that would otherwise only work by making it multi-tenant...but making it multi-tenant is unnecessary if you provide tenant-id. Hope that makes sense...

**Comment by Cnly** [comment]
From a point of view (somewhat) analogous to that of the principle of least privilege, I see what you mean. But since this addition sounds appealing only to a fraction of advanced users and does not bring significant improvements, the potential confusion caused may outweigh the benefits... I'd encourage everyone interested to +1 this issue or comment so we hear more opinions about this.

For now I think you can do that already, since the support needed for single-tenant app is (probably) just a different OAuth auth/token URL pair. You may change those by taking a look at https://rclone.org/onedrive/#onedrive-auth-url.

**Comment by TryTryAgain** [comment]
Thanks, yep completely understand. I have tried including auth and token url's specific to the tenant (replace "common" with your tenant ID in url) after reading through https://forum.rclone.org/t/rclone-on-large-scale-linux-desktops-azuread-auth/18301 but that still didn't work. I'm thinking that will still be required though with or without tenant-id working (with or without multi-tenant set up).

**Comment by Cnly** [comment]
> I have tried including auth and token url's specific to the tenant (replace "common" with your tenant ID in url) after reading through https://forum.rclone.org/t/rclone-on-large-scale-linux-desktops-azuread-auth/18301 but that still didn't work.

That's interesting. The OP in the thread you mentioned seemed to have no problem at the end. Do you have any logs for this @TryTryAgain?

**Comment by ivandeex** [comment]
4 months of no reply from user
