### ISSUE TITLE
Add app for qnap arm7

### ISSUE THREAD

**Issue by SiNaPsEr0x** [rclone/rclone#5251]
Please add app for qnap store for armv7 32bit 

Qnap ts231

**Comment by ncw** [comment]
Is rclone in the qnap store already? If so we didn't put it there.

**Comment by SiNaPsEr0x** [comment]
On alternative store is present but x64 or x32 but I have installed with opkg

Inviato da iPhone

**Comment by ncw** [comment]
I think you will have to find the maintainer for the qnap package as it isn't the rclone project.
