### ISSUE TITLE
[BUG] AWS s3 authentication via IAM role on fargate.

### ISSUE THREAD

**Issue by Xezed** [rclone/rclone#5255]
```
2021/04/18 13:14:53 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
2021/04/18 13:14:56 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
2021/04/18 13:14:56 DEBUG : rclone: Version "v1.56.0-beta.5413.31a8211af" starting with parameters ["rclone" "copy" ":sftp:hidden/hidden" "--sftp-host" "hidden" "--sftp-pass" "hidden" "--sftp-user" "hidden" ":s3:/hidden" "--s3-provider" "AWS" "--s3-env-auth" "--s3-region" "us-west-2" "--s3-acl" "bucket-owner-read" "-P" "-vv"]
2021/04/18 13:14:56 DEBUG : Creating backend with remote ":sftp:hidden/hidden"
2021/04/18 13:14:56 DEBUG : :sftp: detected overridden config - adding "{vxWIR}" suffix to name
2021/04/18 13:14:57 DEBUG : sftp://hidden@hidden:22/hidden/hidden: New connection 172.31.63.2:39344->hidden:22 to "SSH-2.0-HOSTED~FTP~ SFTP"
2021/04/18 13:14:57 DEBUG : sftp://hidden@hidden:22/hidden/hidden: Using absolute root directory "/hidden/hidden"
2021/04/18 13:14:57 DEBUG : fs cache: adding new entry for parent of ":sftp:hidden/hidden", ":sftp{vxWIR}:hidden"
2021/04/18 13:14:57 DEBUG : Creating backend with remote ":s3:/hidden"
2021/04/18 13:14:57 DEBUG : :s3: detected overridden config - adding "{R2Ag4}" suffix to name
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1305ec2]
```

Have no idea what to do with it. Version 1.54.1 behave the very same way. In 1.55 you have sftp bug so can't test.

Running it on Fargate from your image of course.

**Comment by ncw** [comment]
There should have been a backtrace after the `panic: runtime error` - can you paste that please?

**Comment by Xezed** [comment]
Sure. Anything I can help with.
```

goroutine 33 [running]:
--
github.com/aws/aws-sdk-go/aws/credentials/stscreds.(*WebIdentityRoleProvider).RetrieveWithContext(0xc0002342d0, 0x21584a8, 0xc000116000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/pkg/mod/github.com/aws/aws-sdk-go@v1.37.3/aws/credentials/stscreds/web_identity_provider.go:111 +0x62
github.com/aws/aws-sdk-go/aws/credentials/stscreds.(*WebIdentityRoleProvider).Retrieve(0xc0002342d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fb886b4bad0, ...)
/go/pkg/mod/github.com/aws/aws-sdk-go@v1.37.3/aws/credentials/stscreds/web_identity_provider.go:104 +0x96
github.com/aws/aws-sdk-go/aws/credentials.(*ChainProvider).Retrieve(0xc00012b800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/pkg/mod/github.com/aws/aws-sdk-go@v1.37.3/aws/credentials/chain_provider.go:75 +0xfe
github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).singleRetrieve(0xc0000ab500, 0x21586d8, 0xc0002a19a0, 0x0, 0x0, 0x0, 0x0)
/go/pkg/mod/github.com/aws/aws-sdk-go@v1.37.3/aws/credentials/credentials.go:279 +0x551
github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).GetWithContext.func1(0x0, 0x0, 0x0, 0x0)
/go/pkg/mod/github.com/aws/aws-sdk-go@v1.37.3/aws/credentials/credentials.go:255 +0x8a
github.com/aws/aws-sdk-go/internal/sync/singleflight.(*Group).doCall(0xc0000ab500, 0xc000137260, 0x0, 0x0, 0xc00007c180)
/go/pkg/mod/github.com/aws/aws-sdk-go@v1.37.3/internal/sync/singleflight/singleflight.go:97 +0x2e
created by github.com/aws/aws-sdk-go/internal/sync/singleflight.(*Group).DoChan
/go/pkg/mod/github.com/aws/aws-sdk-go@v1.37.3/internal/sync/singleflight/singleflight.go:90 +0x2cc
```

**Comment by ncw** [comment]
This appears to be a crash in the AWS SDK to do with fetching the credentials.

I recently made an updated rclone with the new AWS SDK - can you give this a go?

[v1.56.0-beta.5410.68e2f7432.fix-s3-sso-crash](https://beta.rclone.org/branch/fix-s3-sso-crash/v1.56.0-beta.5410.68e2f7432.fix-s3-sso-crash/) on branch [fix-s3-sso-crash](https://github.com/rclone/rclone/tree/fix-s3-sso-crash)

**Comment by Xezed** [comment]
@ncw `Segmentation fault (core dumped)`

**Comment by Xezed** [comment]
```
2021/04/20 09:59:02 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
2021/04/20 09:59:06 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
2021/04/20 09:59:06 DEBUG : rclone: Version "v1.56.0-beta.5410.68e2f7432.fix-s3-sso-crash" starting with parameters ["rclone" "copy" ":sftp:sftphidden/hidden " "--sftp-host" "hidden" "--sftp-pass" "hidden" "--sftp-user" "sftphidden" ":s3:hidden" "--s3-provider" "AWS" "--s3-env-auth" "--s3-region" "us-west-2" "--s3-acl" "bucket-owner-read" "-P" "-vv"]
2021/04/20 09:59:06 DEBUG : Creating backend with remote ":sftp:sftphidden/hidden "
2021/04/20 09:59:06 DEBUG : :sftp: detected overridden config - adding "{vxWIR}" suffix to name
2021/04/20 09:59:07 DEBUG : sftp://sftphidden@hidden:22/sftphidden/hidden : New connection 172.31.16.81:38674->hidden:22 to "SSH-2.0-HOSTED~FTP~ SFTP"
2021/04/20 09:59:07 DEBUG : sftp://sftphidden@hidden:22/sftphidden/hidden : Using absolute root directory "/sftphidden/hidden "
2021/04/20 09:59:07 DEBUG : fs cache: adding new entry for parent of ":sftp:sftphidden/hidden ", ":sftp{vxWIR}:sftphidden"
2021/04/20 09:59:07 DEBUG : Creating backend with remote ":s3:hidden"
2021/04/20 09:59:07 DEBUG : :s3: detected overridden config - adding "{R2Ag4}" suffix to name
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1302042]
goroutine 15 [running]:
github.com/aws/aws-sdk-go/aws/credentials/stscreds.(*WebIdentityRoleProvider).RetrieveWithContext(0xc000168630, 0x21644c8, 0xc00009e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/aws/aws-sdk-go@v1.38.21/aws/credentials/stscreds/web_identity_provider.go:111 +0x62
github.com/aws/aws-sdk-go/aws/credentials/stscreds.(*WebIdentityRoleProvider).Retrieve(0xc000168630, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7f2930999908, ...)
	github.com/aws/aws-sdk-go@v1.38.21/aws/credentials/stscreds/web_identity_provider.go:104 +0x96
github.com/aws/aws-sdk-go/aws/credentials.(*ChainProvider).Retrieve(0xc00054db60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/aws/aws-sdk-go@v1.38.21/aws/credentials/chain_provider.go:75 +0xfe
github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).singleRetrieve(0xc000185400, 0x21646f8, 0xc0002a6d00, 0x0, 0x0, 0x0, 0x0)
	github.com/aws/aws-sdk-go@v1.38.21/aws/credentials/credentials.go:279 +0x551
github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).GetWithContext.func1(0x0, 0x0, 0x0, 0x0)
	github.com/aws/aws-sdk-go@v1.38.21/aws/credentials/credentials.go:255 +0x8a
github.com/aws/aws-sdk-go/internal/sync/singleflight.(*Group).doCall(0xc000185400, 0xc00010d560, 0x0, 0x0, 0xc0000caec0)
	github.com/aws/aws-sdk-go@v1.38.21/internal/sync/singleflight/singleflight.go:97 +0x2e
created by github.com/aws/aws-sdk-go/internal/sync/singleflight.(*Group).DoChan
	github.com/aws/aws-sdk-go@v1.38.21/internal/sync/singleflight/singleflight.go:90 +0x2cc

```

No use :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face: :pleading_face:

**Comment by ncw** [comment]
Can you try this beta?

https://beta.rclone.org/branch/fix-s3-sso-crash/v1.56.0-beta.5417.793ba82a2.fix-s3-sso-crash/

That should fix the crash, but I think it may break the auth...

**Comment by Xezed** [comment]
Yeah, you are right.

**Comment by ncw** [comment]
No valid providers in the chain is kind of what I was expecting to see - the provider which was crashing was last in the chain.

The provider which is supposed to pick up the AWS_PROFILE is near the start.

One thing you could try is setting the env var `AWS_SDK_LOAD_CONFIG` to `1`. This shouldn't be needed as I'm setting the equivalent of this internally, but it is worth a shot.

I tried setting aws.Config.CredentialsChainVerboseErrors - can you give this a go. It might tell us something interesting!

[v1.56.0-beta.5423.6defd328b.fix-s3-sso-crash](https://beta.rclone.org/branch/fix-s3-sso-crash/v1.56.0-beta.5423.6defd328b.fix-s3-sso-crash/) on branch [fix-s3-sso-crash](https://github.com/rclone/rclone/tree/fix-s3-sso-crash) (uploaded in 15-30 mins)

**Comment by ncw** [comment]
The bit of code which is causing the crash is this

https://github.com/rclone/rclone/blob/f8884a720006403e0144c9f9a5e898877498340a/backend/s3/s3.go#L1515-L1518

As far as I can see this can never have worked because it doesn't initialise the [tokenFetcher](https://github.com/aws/aws-sdk-go/blob/64c99482708d9bab0281216769f110ae046049fc/aws/credentials/stscreds/web_identity_provider.go#L49-L73
) - that is why we get a `nil` pointer crash

The proper way to initialise this is with the [NewWebIdentityCredentials](https://github.com/aws/aws-sdk-go/blob/64c99482708d9bab0281216769f110ae046049fc/aws/credentials/stscreds/web_identity_provider.go#L77) but I have no idea where to get the other parameters from `roleARN, roleSessionName, path`

This code was originally added in 15d19131bd by @tennix - do you have any ideas on how to fix this?

**Comment by Xezed** [comment]
Never worked with go but excited to have an opportunity :smile: 
Yeah I'm pretty sure that I'll figure it out.

**Comment by ncw** [comment]
> Never worked with go but excited to have an opportunity 
> Yeah I'm pretty sure that I'll figure it out.

:-) I was talking to @tennix but if you want to have a look that would be great too!

**Comment by Xezed** [comment]
@ncw It turned out that I'm just dorky. 

Fargate tasks have 2 types of roles and I was using the wrong one assuming that it is the only one. 

Thank you for elaboration Nick. It's all working just as expected.

Your sso fix branch is providing permission error instead of crash. So you can merge it. :+1:  :)

**Comment by ncw** [comment]
> Your sso fix branch is providing permission error instead of crash. So you can merge it.  :)

So your fargate IAM role works even with that patch?

If that is the case then I will merge it.

**Comment by Xezed** [comment]
@ncw You fix providing correct error instead of vague fatal error.

**Comment by ncw** [comment]
I've merged that code to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.56 (and v1.55.2 if we make one of those)

**Comment by Xezed** [comment]
Thank you)

**Comment by nielstenboom** [comment]
> @nielstenboom what have you got in your config file? Are you using `env_auth = true` - you'll need that, or `--s3-env-auth`

Yes I'm using the env_auth=true config option. It's without a config file actually.

I did manage to make it work by doing some bash commands first (`aws sts assume-role`) to get the credentials into env variables before calling rclone and that worked, but did expect it to also work with just the credentials file I mentioned.
