### ISSUE TITLE
ERROR : Attempt n/m succeeded

### ISSUE THREAD

**Issue by black-snow** [rclone/rclone#5257]
#### What is your current rclone version (output from `rclone version`)?

I dont have access right now but it's the latest one available via default Debian buster stable channel as of writing this.

#### What problem are you are trying to solve?

Quite often, I see outputs like this popping up:
```
> 2021/04/19 13:20:06 ERROR : Unbenannt 1.pdf: Failed to copy: chtimes /xxx/Unbenannt 1.pdf: permission denied
> 2021/04/19 13:20:06 ERROR : Unbenannt 1.pdf: Not deleting source as copy failed: chtimes /xxx/Unbenannt 1.pdf: permission denied
> 2021/04/19 13:20:06 ERROR : Attempt 1/3 failed with 1 errors and: chtimes /xxx/Unbenannt 1.pdf: permission denied
> 2021/04/19 13:20:06 ERROR : Unbenannt 1.pdf: Failed to set modification time: chtimes /xxx/Unbenannt 1.pdf: permission denied
> 2021/04/19 13:20:07 ERROR : Attempt 2/3 failed with 1 errors and: chtimes /xxx/Unbenannt 1.pdf: permission denied
> 2021/04/19 13:20:07 ERROR : Attempt 3/3 succeeded
```

They usually succeed at attempt 2. But the thing is, stdout is emailed and triggers personal to look into it. Is there a way to have `rclone` not output anything to `stderr` unless it actually, terminally fails?
Or how do other people deal with this?

#### How do you think rclone should be changed to solve that?

If possible, it'd be nice if rclone only printed terminal errors to `stdout`, i.e., actions that have exceeded the retry limit or cannot be retried.

P.S.: With the forum and the many issues here it's tricky to find all the information. I'm sorry if this has come up already and I've missed it. In that case, feel free to refer & close, thanks!

**Comment by ncw** [comment]
Rclone prints warnings it thinks you need to see to stderr too, so I don't think this is feasible.

What you want to be doing is checking the return code of rclone - that should always be accurate.

**Comment by black-snow** [comment]
@ncw thanks for the quick reply!

Mhm, that's bad when anything to `stderr` triggers a reaction ... then the only somewhat reasonable solution I see is to pipe `stderr` through another script that filters out all `some error\nattempt n/m failed` with `n<m` ...
Or to write `stderr` to a temp file and cat that file to `stderr` if `$?` isn't `0`.
@ncw do you see any other feasible solution?

**Comment by ncw** [comment]
> do you see any other feasible solution?

Checking the error code is the right way to detect if rclone was successful or not, so I think your script is now correct.

**Comment by black-snow** [comment]
Today I received an email for an error that seemed to have sneaked out of my trap. It had some weird html spilled over the logs. Gotta look it up tomorrow.

**Comment by ncw** [comment]
Occasionally the backends return HTML errors instead of the nice API errors they are supposted to and these make it into rclone error logs sometimes. That is probably what you are seeing.

**Comment by jonathanMelly** [comment]
thanks it was exactly what I was looking for too ;-)
