### ISSUE TITLE
rclone ls compressed file error

### ISSUE THREAD

**Issue by linora** [rclone/rclone#5260]
#### What is the problem you are having with rclone?
When I perform the ls operation on the compressed library, I get a lot of errors.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.55.0
- os/type: linux
- os/arch: amd64
- go/version: go1.16.2
- go/linking: static
- go/tags: cmount
```

```
[db2s_file_repo01]
type = sftp
host = xxx.xx.xx.xxx
user = root
port = 22
pass = xxx
md5sum_command = md5sum
sha1sum_command = sha1sum

# END ANSIBLE MANAGED BLOCK backup_JieBan_userImage section 1
# BEGIN ANSIBLE MANAGED BLOCK backup_JieBan_userImage section 2
[db2s_file_repo01_encrypt]
type = crypt
remote = db2s_file_repo01:/opt/db2s_sync_dir
password = xxx
password2 = xxx

[db2s_file_repo01_compress]
type = compress
remote = db2s_file_repo01:/opt/db2s_sync_dir

[db2s_file_repo01_compress_encrypt]
type = compress
remote = db2s_file_repo01_encrypt:
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
centos 7.8 x86_64

#### Which cloud storage system are you using? (e.g. Google Drive)
sftp

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
 rclone ls db2s_file_repo01_compress:a.txt

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
[dummy@c7001 ~]$ rclone ls db2s_file_repo01_compress:a.txt -vv
2021/04/20 17:05:06 DEBUG : Using config file from "/home/dummy/.config/rclone/rclone.conf"
2021/04/20 17:05:06 DEBUG : rclone: Version "v1.55.0" starting with parameters ["rclone" "ls" "db2s_file_repo01_compress:a.txt" "-vv"]
2021/04/20 17:05:06 DEBUG : Creating backend with remote "db2s_file_repo01_compress:a.txt"
2021/04/20 17:05:06 DEBUG : sftp://root@172.16.13.240:22//opt/db2s_sync_dir/a.txt.json: New connection 172.16.13.254:38657->172.16.13.240:22 to "SSH-2.0-OpenSSH_7.4"
2021/04/20 17:05:06 ERROR : mysql_binlog_rsync.1617886804.-AEAAAAAAAA.gz: Error on parsing file name: Invalid filename
2021/04/20 17:05:06 ERROR : mysql_binlog_rsync.1618059604.-AEAAAAAAAA.gz: Error on parsing file name: Invalid filename
2021/04/20 17:05:06 ERROR : mysql_binlog_rsync.1617973205.-AEAAAAAAAA.gz: Error on parsing file name: Invalid filename
2021/04/20 17:05:06 ERROR : mysql_binlog_rsync.1618146004.-AEAAAAAAAA.gz: Error on parsing file name: Invalid filename
2021/04/20 17:05:06 ERROR : mysql_binlog_rsync.1617886804.-AEAAAAAAAA.gz.-AEAAAAAAAA.gz: Error on parsing file name: Invalid filename
2021/04/20 17:05:06 ERROR : mysql_binlog_rsync.1618146004.-AEAAAAAAAA.gz.-AEAAAAAAAA.gz: Error on parsing file name: Invalid filename
2021/04/20 17:05:06 ERROR : mysql_binlog_rsync.1617973205.-AEAAAAAAAA.gz.-AEAAAAAAAA.gz: Error on parsing file name: Invalid filename
2021/04/20 17:05:06 ERROR : mysql_binlog_rsync.1618059604.-AEAAAAAAAA.gz.-AEAAAAAAAA.gz: Error on parsing file name: Invalid filename
...
2021/04/20 17:05:06 ERROR : t5bi0a8h7au9jfb0645dc7isc2n2rtp4f03n9pnlsi8156jhif3h9qnb5tngiaoo2kojtapdocq3e: Error on parsing file name: File name has no extension
2021/04/20 17:05:06 DEBUG : crontabWdn574: Excluded
...
2021/04/20 17:05:06 DEBUG : a: Excluded
       38 a.txt
2021/04/20 17:05:06 DEBUG : 11 go routines active
```

**Comment by ncw** [comment]
@ivandeex this error is coming from here

https://github.com/rclone/rclone/blob/7afb4487efb8674826a05595e183a8a4982ea469/backend/compress/compress.go#L273-L277

Which in turn comes from here

https://github.com/rclone/rclone/blob/7afb4487efb8674826a05595e183a8a4982ea469/backend/compress/compress.go#L232-L235

So the file names appear to be int he wrong format somehow...

They look like they might have been compressed multiple times somehow.

**Comment by buengese** [comment]
@ncw I guess you probably meant to ping me since I worked on the compression remote?
There is one rather obvious problem in the code. The name regular expression clearly isn't working correctly even the duplication of the size shouldn't stop it from getting decoded correctly. 
I'll look into it.

**Comment by ncw** [comment]
> I guess you probably meant to ping me since I worked on the compression remote?

Sorry, brain failure!

> There is one rather obvious problem in the code. The name regular expression clearly isn't working correctly even the duplication of the size shouldn't stop it from getting decoded correctly.
> I'll look into it.
> 
> Edit: ok that's really rather obvious.
> The regular expression uses the `+` character for from the regular base64 char set for 62 instead of the `-` from the URL safe base64 char set which should have been used here.

Ah ha!

> I'm still not entirely sure how this caused the size suffix to be duplicated though..

Did it add a size again because it couldn't see that it had added one already?

**Comment by buengese** [comment]
>Did it add a size again because it couldn't see that it had added one already?
I'm not entirely sure. I can't really think of a situation in which that would've happened it would require the unprocessed name to be passed into `makeDataName()` and I'm not seeing that right now.
A copy from the underlying uncompressed remote to the compress remote could probably cause that...

@linora The latest beta contains a fix a for the obvious problem here. You can get it [here](https://beta.rclone.org/). Though you should probably still delete all files created with the previous version to avoid confusion.

**Comment by ncw** [comment]
I've put this patch into the v1.55.1 pending release

**Comment by buengese** [comment]
@linora Did you have any time to check if the fix worked for you?

**Comment by buengese** [comment]
Closing this since I've never heard back from you.
