### ISSUE TITLE
mediafire and  archive.org

### ISSUE THREAD

**Issue by MesterPerfect** [rclone/rclone#5264]
good morning
am so happy that I use rclone, it has brought me a lot of things that I thought were very difficult
It would be very nice if mediafire and archive.org were added to rclone
is that possible?

**Comment by ncw** [comment]
There is an issue about mediafire here: https://github.com/rclone/rclone/issues/1465

And there is an issue for archive.org here https://github.com/rclone/rclone/issues/1608

Can you go to those issues and click the thumbs up icon so we can guage user interest.

Are you interested in helping with these backends?

I'm going to close this issue as I think it is covered in the above issue.

Thanks

**Comment by krystian3w** [comment]
https://github.com/rclone/rclone/pull/6104
