### ISSUE TITLE
Onedrive Authorization no Longer Works

### ISSUE THREAD

**Issue by Jonatino** [rclone/rclone#5265]
#### What is the problem you are having with rclone?
Rclone onedrive auth no longer works (I've only tested with remote headless client config).

#### What is your rclone version (output from `rclone version`)
Headless server and auth client running `rclone v1.56.0-beta.5423.5d85e6bc9`

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Headless server: Unraid 6.9.2
Remote auth client: Popos 20.10

#### Which cloud storage system are you using? (e.g. Google Drive)
Onedrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone authorize "onedrive"

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
Not applicable since remote is not created in the first place.

**The following is the error after attempting to paste the auth tokens in the result>**

```
Couldn't decode response - try again (make sure you are using a matching version of rclone on both sides: decode simple map: illegal base64 data at input byte 0
```

Screen shot of input
![issue](https://i.imgur.com/Xjk6Yxm.png)

**Comment by ncw** [comment]
Make sure you are using the same version of rclone when you do the rclone authorize - that should fix it.

**Comment by Jonatino** [comment]
> Make sure you are using the same version of rclone when you do the rclone authorize - that should fix it.

They're both using `rclone v1.56.0-beta.5423.5d85e6bc9`

**Comment by Cnly** [comment]
Hi @Jonatino, it looks like this is indeed a bug not just with OneDrive - all backends may be affected. I've pushed a commit that should fix this and could you please see if the new version here solves your problem: https://beta.rclone.org/branch/auth-format-compatibility (should be available in 15-30 mins)? Thanks :)

**Comment by Jonatino** [comment]
@Cnly yup that worked perfect. Thank you
