### ISSUE TITLE
Work around for "Unable to initialize RPS" errors from OneDrive

### ISSUE THREAD

**Issue by olefrost** [rclone/rclone#5270]
OneDrive returns occasional http 401 responses with the error message: "InvalidAuthenticationToken: Unable to initialize RPS". The frequency varies and has been increasing lately. It may be related to a bug and/or high load on Microsoft servers.

The unexpected 401 response leads to sync failurers etc. for many users:
https://forum.rclone.org/t/invalidauthenticationtoken-unable-to-initalize-rps/23595

The issue impacts all commands using the OneDrive backend in rclone 1.55.0 (and earlier) on all platforms.

The issue has been reported to Microsoft in this bug report:
https://github.com/OneDrive/onedrive-api-docs/issues/1489

This enhancement will increase the robustness of the OneDrive backend by implementing the first work around in this forum post:
https://forum.rclone.org/t/invalidauthenticationtoken-unable-to-initalize-rps/23595/35

**Comment by olefrost** [comment]
The issue also impacts Microsofts own products (18apr2021):
https://twitter.com/tweetsdoba/status/1383590155093610498

and has impacted rclone in the past (13mar2021 and 19sep2019): 
https://forum.rclone.org/t/onedrive-sync-problem-invalidauthenticationtoken-unable-to-initialize-rps/22809
https://forum.rclone.org/t/onedrive-sync-fail-after-few-minutes/11916

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.56 - thank you @olefrost
