### ISSUE TITLE
Gihub action build.yml prevents updating any rclone fork

### ISSUE THREAD

**Issue by mathieucarbou** [rclone/rclone#5272]
The build.yml has a `push:` event with is triggered on every branch and every repository. But this is wrong to trigger it on forks.

Here is what happens when auto-updating a rclone fork:

```
To https://github.com/mathieucarbou/rclone
 ! [remote rejected]   master -> master (refusing to allow a GitHub App to create or update workflow `.github/workflows/build.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/mathieucarbou/rclone'
```

It seems there is a workaround by adding `paths-ignore` filters on the push even or if condition to check the repository name:

`if: github.repository == 'rclone/rclone'`

Cheers!

**Comment by mathieucarbou** [comment]
Strangely, doing a fetch from upstream and force push on my master branch allowed to push the content, but the github actions all triggered in my fork under my account, which is probably not what we would want.

Having a PR build and master build, and eventually some additional checks is fine and is something setup only in the upstrema repo but I am wondering if using GitHub actions on the upstream, which propagates to all forks, is a good idea...

**Comment by mathieucarbou** [comment]
Additional notes: not filtering the events so that they execute only on the upstream repo would also allow to not bust the usage limits of users having forked this repo.

https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#usage-limits

**Comment by ncw** [comment]
What would your suggested fix for this be?

Do you want to send a PR with that in?

**Comment by mathieucarbou** [comment]
> What would your suggested fix for this be?

There are several fixes like using `*-ignores`, specific branches (not `*`), or if conditions.

> Do you want to send a PR with that in?

I can but since I don't know what are doing the  current workflow scripts, I will juste assume they only need to be execute inside the upstream master branch. Is that right ? Or they also need to be executed for each PR sent or updated ?

**Comment by ncw** [comment]
> > What would your suggested fix for this be?
> 
> There are several fixes like using `*-ignores`, specific branches (not `*`), or if conditions.
> 
> > Do you want to send a PR with that in?
> 
> I can but since I don't know what are doing the current workflow scripts, I will just assume they only need to be execute inside the upstream master branch. Is that right ? Or they also need to be executed for each PR sent or updated ?

We need the actions to run on pushes to branches and for PR requests on the main repo.

I'm really not sure about forks. Is it useful for them to run the actions? Or maybe a subset of them?

I was looking at what other open source projects do

[Hugo](https://github.com/gohugoio/hugo/blob/master/.github/workflows/test.yml) does `on: [push, pull_request]` - is that better than what rclone has at the moment?

[Caddy](https://github.com/caddyserver/caddy/blob/master/.github/workflows/ci.yml) does something slightly different.

I made up the original code rclone is using a long time ago (rclone was one of the first users of actions) so it may be completely wrong!

https://github.com/rclone/rclone/blob/0537791d14675e9c66a2a237680f6403cba4e3f1/.github/workflows/build.yml#L8-L14

Looking at it now I can see why I get two builds one for the tag and one for the branch whenever I push a tag... So I should probably remove the `tags` section.

What do you think best practice is now?

**Comment by mathieucarbou** [comment]
Hello @ncw ,

If you look at my PR (#5275), you will see that I have only added `if:` conditions so that the script logic **is not changed** but will only be applied to the official rclone repository, not forks. This is important because otherwise these scripts could be executed under every people's account having forked rclone and will contribute in depleting user's quota for GitHub Actions.

This is [what is recommended](https://github.community/t/stop-github-actions-running-on-a-fork/17965/2) until GitHub provides users the options to partly disable workflow scripts by default when forking.

Currently, GitHub has a way to totally disable running Actions on a repository, but the option is note activated by default on forks and is not suitable in cases where a user would still want to add some workflow actions (like I do) to automatically sync from rclone repo for example. GitHub currently does not "automatically" disable actions to run when forking, and worse, there is no way to activate only custom ones, leaving the rest disabled.

So that is why adding `if:` conditions would be the more reliable way to keep the same logic and only execute those scripts under rclone account as it is right now.

Note that PR build is done under rclone account, not the user's account having sent the PR...

**Comment by mathieucarbou** [comment]
**The ideal solution would be:**

- The current scripts as they are right now with the `if:` conditions so that the jobs are not executed **automatically** on people's fork
- Another script which would be a partial copy of the current one, that would contain only a manual trigger with `workflow_dispatch:` under `on:` to allow users to access these scripts from the GitHub Actions tab on their fork so that they can **manually** run the build from their fork.

```
on:
  workflow_dispatch:
```

This would be the ideal solutions: 
- using event-driven jobs filtered with `if:` so that this event-driven jobs only execute under rclone's account and do not participate in depleting people's quota
- having manual triggers to still provide users a way to run jobs manually (those jobs would not have the `if:` condition)

**Comment by ncw** [comment]
> So that is why adding `if:` conditions would be the more reliable way to keep the same logic and only execute those scripts under rclone account as it is right now.

OK you've convinced me :-)



> This would be the ideal solutions:
> 
> * using event-driven jobs filtered with `if:` so that this event-driven jobs only execute under rclone's account and do not participate in depleting people's quota
> * having manual triggers to still provide users a way to run jobs manually (those jobs would not have the `if:` condition)

You seem to have implemented this in your PR :-)

Does it work?

**Comment by mathieucarbou** [comment]
Hello @ncw !

Yes indeed! I am testing it right now and even better I have found a way to use inputs (which can be given when running a job manually) to filter.

Magic is done thanks to:

```
  workflow_dispatch:
    inputs:
      manual:
        required: true
        default: true
```

and 

`    if: ${{ github.repository == 'rclone/rclone' || github.event.inputs.manual }}`

So this way:
- everything will run as before on rclone repo
- but on forks, nothing will run automatically
- both on rclone and forks, there will now be the ability to trigger a manual build by clicking on the build workflow and running it on a specific branch, with the `manual` parameter defaulted to true to bypass the filter when on forks.

**Comment by ncw** [comment]
Thanks for fixing that @mathieucarbou :-)

I wondered if I could pick your brain about another actions related matter....

In the action scripts we only deploy built binaries "if enabled in config && not a PR && not a fork"

https://github.com/rclone/rclone/blob/8f23cae1c0719bf72d13f874cc6f447d8b43d6ec/.github/workflows/build.yml#L210-L220

I'd like to make that a bit more flexible...

I'd like pull requests by project members only to be able to deploy build binaries.

At the moment project members push to branches to make deployments which is at cross purposes with the whole pull request system.

However there were several things I couldn't figure out

1. How to determine the user sending the pull request is a project member
2. How to determine in the Makefile that the thing it is building is a pull request and what its PR number is from the environment variables

Any ideas much appreciated!

**Comment by mathieucarbou** [comment]
> However there were several things I couldn't figure out
> 
> 1. How to determine the user sending the pull request is a project member

> 2. How to determine in the Makefile that the thing it is building is a pull request and what its PR number is from the environment variables

I haven't experience such need but I think this could be achieved by using env vars perhaps for the most part.

- https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables
- https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request

And for members: 

- `curl https://api.github.com/orgs/rclone/members`

You could perhaps add these env variables in your script and access them from your make files. 
If you have them set, you are in a PR build

```yml
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PR_AUTHOR: ${{ github.event.pull_request.user.login }}
```

And in your make file, something like:

```bash
if [ ! -z "$PR_AUTHOR" ]; then
  # PR
  FOUND=curl -s https://api.github.com/orgs/rclone/members | jq -r 'map(select(.login | test("^$PR_AUTHOR\$"))) | map(.login) | join("")'
  if [ "$PR_AUTHOR" == "$FOUND" ]; then
    # PR was created by a member
  fi
fi
```

Note: didn't test all of that, and probably needs refining, but you have most of the pieces ;-)

**Comment by ncw** [comment]
That is brilliant - thanks. I didn't realise you could get stuff out of github.event - I was only looking at the environment variables. And your jq one liner is very cool!

I think that is probably enough things indeed - thank you for the inspiration :-)

**Comment by mathieucarbou** [comment]
> That is brilliant - thanks. I didn't realise you could get stuff out of github.event - I was only looking at the environment variables. And your jq one liner is very cool!
> 
> I think that is probably enough things indeed - thank you for the inspiration :-)

You're welcome!
