### ISSUE TITLE
StatsInfo elapsed time is now globally-scoped

### ISSUE THREAD

**Issue by macklin-10x** [rclone/rclone#5282]
#### What is the problem you are having with rclone?

The elapsed time returned by `StatsInfo.RemoteStats()` is based on the application lifetime via `startTime` package var.

#### What is your rclone version (output from `rclone version`)

current master

In previous releases (at least as of 1.52) the elapsed time calculated by `StatsInfo` was based on details of the transfers overseen by that instance of the type.  In current master and 1.55, a package-scoped `startTime` var was introduced and is initialized at package init, and all elapsed times are computed since this time.  For applications that embed rclone as a library and may perform multiple transfers over the application lifetime, this value isn't relevant.  I know that library embedding isn't necessarily one of rclone's design goals, but with all the recent de-globalization of the config and filter system, this feels like a regression towards globalism.

One possible solution would be to make `startTime` scoped to a particular `StatsInfo` object, initialized at construction, and then reset along with the other counters when `StatsInfo.ResetCounters` is called.  I'm happy to file a PR with a patch that improves this if someone on the rclone team could provide a bit of guidance!

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Have you looked at the the `transferTime` property. This is the time that a given StatsInfo has been transferring data.

This isn't quite what you asked for but it is close.

> For applications that embed rclone as a library and may perform multiple transfers over the application lifetime, this value isn't relevant. I know that library embedding isn't necessarily one of rclone's design goals,

We are trying to make rclone usable as a library - it is slow progress but we are getting there!

> One possible solution would be to make `startTime` scoped to a particular `StatsInfo` object, initialized at construction


If `transferTime` doesn't work for you then this sounds like a sensible idea. So `startTime` would become the time from the initialization of this `StatsInfo`.

> and then reset along with the other counters when `StatsInfo.ResetCounters` is called.

I'm not 100% sure whether that will break something or not, but a check of the code convinces me that it probably won't!

> I'm happy to file a PR with a patch that improves this if someone on the rclone team could provide a bit of guidance!

Great!

This should be reasonably straight forward.

Move this

https://github.com/rclone/rclone/blob/9ccd870267b3bda042acc8f131becd457f37ef01/fs/accounting/stats.go#L21

into this

https://github.com/rclone/rclone/blob/9ccd870267b3bda042acc8f131becd457f37ef01/fs/accounting/stats.go#L24

Initialise here

https://github.com/rclone/rclone/blob/9ccd870267b3bda042acc8f131becd457f37ef01/fs/accounting/stats.go#L57

Reset here

https://github.com/rclone/rclone/blob/9ccd870267b3bda042acc8f131becd457f37ef01/fs/accounting/stats.go#L536

And use the compiler errors to fixup any places the `startTime` global was used.

See the [contributing guide](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#submitting-a-pull-request) for info on how to get set up.

**Comment by macklin-10x** [comment]
Ah I see that `transferTime` is what was (I think?) previously called `elapsedTime`.  I think that the deglobalized `elapsedTime` is even closer to what I'm looking for, which is the total wall clock time a transfer operation has been running (in other words, what a human sitting there with a stopwatch wondering "geez how long has this upload been running" would measure).
