### ISSUE TITLE
Please have a look at Polo file manager code

### ISSUE THREAD

**Issue by Lucaacer** [rclone/rclone#5290]
I am a google drive user and rclone mount is much better than any other linux solution, but sometimes it takes ages to reload a folder or the entire google drive filesystem.

I have beeen trying every suggested setting to improve "caching" (vfs or real caching) but nevertheless I don't always get what I need.

So I have tested an old filemanager, i.e. Polo, which has got its own implementation of rclone. I seem to understand, while digging the code, that it actually writes to the ssd the folders structure and the file names. Well, it looks like using the chrome OS file manager and everything is almost instant. Sadly, in ubuntu gnome it's not very easy to set up polo-gtk as default file manager.

As a feature request, may you please have a look at https://github.com/teejee2008/polo/blob/master/src/Common/Main.vala and eventually integrate such caching strategy as a general option for rclone? So that it'd work file manager agnostic.

Thanks and keep on working on rclone!

**Comment by Masamune3210** [comment]
if you have vfs caching on it already writes dummy versions of the file and folders, so there is something else going on here

**Comment by Lucaacer** [comment]
Thanks for replying.

That's the way I usually mount /home/luca/Gdrive

rclone mount --vfs-cache-mode full gdrive:/ /home/luca/Gdrive/ &

I have so far tried more or less any other option and they don't seem to make much difference from mounting without any option.

In my google drive storage there are about 70 gigs of files, many gdocs files in the root folder and a certain number of folders and subfolders where you can find very small files and some bigger files in the range 100-300 megabytes (scanned pdf files).

What kind of option might be the better compromise in you opinion?

**Comment by Masamune3210** [comment]
I dont know, as I also have a very large amount of files and folders in my mount and it suffers from the same issues with folder iteration and responsiveness issues

**Comment by Lucaacer** [comment]
It looks that, if I wait for a long time (3 mins) the whole folders' structure is being actually written to the ssd and it persists even when I close the lid.

**Comment by ivandeex** [comment]
Slow startup of vfs cache is a known problem

**Comment by ivandeex** [comment]
We have other requests mentioning slow performance of vfs cache with lots if files.

We plan various measures against that, in particular replace json metada storage by embedded key-value store, and more.

**Comment by ivandeex** [comment]
Would be nice if ticket author could develop a vfs patch based on "polo" code and submit a pull request.
