### ISSUE TITLE
Only showing Team Drive but not normal drive.

### ISSUE THREAD

**Issue by FatSandwich** [rclone/rclone#5291]
Before I start thank you for helping in all the things I need help in for Rclone.

When I made an Rclone config I configured a Team Drive, but now when I mount it, it doesn't show the normal one. 
Did I do something wrong.

**rclone.conf**
[drive]
type = drive
scope = drive
token = ...
team_drive = ...
root_folder_id = 

Thanks!

**Comment by Masamune3210** [comment]
Afaik you have to make two separate entries, one for the team drive and one for the normal drive if you want both to be accessible

**Comment by ncw** [comment]
That is correct, you need two config file entries, one for the team drive and one for the normal drive.

There are other ways of doing things (eg with `--drive-team-drive XXX`) but two entries is best.

We prefer this kind of question on [the rclone forum](https://forum.rclone.org/) for next time.

I'll close this one now.
