### ISSUE TITLE
Add `--recursive` to rclone touch.

### ISSUE THREAD

**Issue by aeromaxx** [rclone/rclone#5301]
Currently rclone touch only works on single files, this is fine for that task.  However when needing to bulk touch files in a directory this is only possible by first fetching all the files contained with the directory and any subdirectories and then touch each file one at a time, this is very time consuming and as a result `rclone touch` would benefit of being able to recursively touch all files within a directory.

When using rclone touch with the new `--recursive` flag it should only touch already existing files, and should not create new files by default.

**Comment by ivandeex** [comment]
Also please deliver `rclone touch mystore:mydir --include "*.new"` :smiley:

**Comment by ncw** [comment]
@ivandeex wrote:
> Also please deliver `rclone touch mystore:mydir --include "*.new"`

The current thinking is that if you did

    rclone touch -R mystore:mydir --include "*.new"

then that would "just work".

If you supply a directory without `-R` then touch will give an error. It might be that if you supply a directory without `-R` then it should touch all the files one level deep - not sure - what do you think?

**Comment by aeromaxx** [comment]
```
If you supply a directory without -R then touch will give an error. It might be that if you supply a directory without -R then it should touch all the files one level deep - not sure - what do you think?
```
Yeah I think that would be fine, but maybe with an --interactive confirmation by default.

**Comment by aeromaxx** [comment]
Any recommendations with what to do with this next?  https://github.com/rclone/rclone/pull/5313
