### ISSUE TITLE
Rclone corrupt file transfer error with latest rclone version : rclone v1.55.1

### ISSUE THREAD

**Issue by shikhasharma143** [rclone/rclone#5302]
I did full load rclone sync from Amazon S3 bucket to Minio storage bucket using two rclone configs : one for aws s3 with kms key enabled (provided key id also) and other for minio (endpoint of minio with no encryption)

The data files are of jpg and mp4 format. 
While running the sync, most of the data got synced properly except few which gave below error in log : 
Command used:
rclone --vv sync rclone-s3://bucket-name-s3 rclone-minio://minio-bucket-name
error in logs:
corrupted on transfer: MD5 hash differ "XXXX" vs "XXXXYYYYY"

What could be the reason for this error and how to resolve it.

Also, when I try --ignore-checksum in above sync command for all data sync, it doesn't sync anything.

**Comment by ivandeex** [comment]
It's a mistake to erase request template.
rclone engineers cannot investigate bugs without problem details.

**Comment by shikhasharma143** [comment]
https://github.com/rclone/rclone/issues/5304 added this
