### ISSUE TITLE
Rclone corrupt file transfer error with latest rclone version : rclone v1.55.1

### ISSUE THREAD

**Issue by shikhasharma143** [rclone/rclone#5304]
#### What is the problem you are having with rclone?
I did full load rclone sync from Amazon S3 bucket to Minio storage bucket using two rclone configs : one for aws s3 with kms key enabled (provided key id also) and other for minio (endpoint of minio with no encryption)

The data files are of jpg and mp4 format.
While running the sync, most of the data got synced properly except few which gave below error in log :
Command used:
rclone --vv sync rclone-s3://bucket-name-s3 rclone-minio://minio-bucket-name
error in logs:
corrupted on transfer: MD5 hash differ "XXXX" vs "XXXXYYYYY"

What could be the reason for this error and how to resolve it.

Also, when I try --ignore-checksum in above sync command for all data sync, it doesn't sync anything.

#### What is your rclone version (output from `rclone version`)
rclone v1.55.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Linux machine, 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
Amazon S3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone --vv sync rclone-s3://bucket-name-s3 rclone-minio://minio-bucket-name

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
corrupted on transfer: MD5 hash differ "XXXX" vs "XXXXYYYYY"

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> I did full load rclone sync from Amazon S3 bucket to Minio storage bucket using two rclone configs : one for aws s3 with kms key enabled (provided key id also) and other for minio (endpoint of minio with no encryption)

If you repeat the transfer do you get the message on the same files?

Can you show a log with `-vv` of the failing transfer please?

**Comment by ivandeex** [comment]
3 months of no reply from user.
