### ISSUE TITLE
Illegal seek when copying a file with a run of zeros into a remote Box folder

### ISSUE THREAD

**Issue by lciti** [rclone/rclone#5314]
#### Output of `rclone version`

rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.6

#### Describe the issue

I have mounted a Box folder with:
`rclone mount --daemon BoxFolder: ~/mnt/`

I have copied a number of files from my local disk into a subfolder of the remote. All files are transferred fine except for one file that gives `Illegal seek`. I have tried re-sending that file and get the same error each time.
I run `strace cp ... ...` and saw that the reason may be a seek operation, which may not be supported on the remote side.

```
read(3, "%PDF-1.5\n%\320\324\305\330\n82 0 obj\n<<\n/Type"..., 131072) = 131072
write(4, "%PDF-1.5\n%\320\324\305\330\n82 0 obj\n<<\n/Type"..., 131072) = 131072
read(3, "\1\267\35\360!\340\21\16\362a\340A\216\214!&}G\337COe\34\263\361\4\4w8*\311\207"..., 131072) = 131072
write(4, "\1\267\35\360!\340\21\16\362a\340A\216\214!&}G\337COe\34\263\361\4\4w8*\311\207"..., 131072) = 131072
read(3, "\34g\354\24568\273y\227\270M\220\237\334MAo\263\277U\1;\240j\211\23\340b8\301\204\202"..., 131072) = 131072
write(4, "\34g\354\24568\273y\227\270M\220\237\334MAo\263\277U\1;\240j\211\23\340b8\301\204\202"..., 131072) = 131072
read(3, "0l\304\v\360\267\10,@\27\262vt\16\372\257_\270\2\275\217\276\34\375-\213c\347C}\32A"..., 131072) = 131072
write(4, "0l\304\v\360\267\10,@\27\262vt\16\372\257_\270\2\275\217\276\34\375-\213c\347C}\32A"..., 131072) = 131072
read(3, "\215\313b\347\262\300vS\25\241gtG S\225\246?\223[\3\255U\321\317\255\204tV\367\331\35"..., 131072) = 131072
write(4, "\215\313b\347\262\300vS\25\241gtG S\225\246?\223[\3\255U\321\317\255\204tV\367\331\35"..., 131072) = 131072
read(3, "G\270IM5\336\346\224\0+!\312\323\0w\0356E\206\301\214h@V\206\3\321\3R\204\317\244"..., 131072) = 131072
write(4, "G\270IM5\336\346\224\0+!\312\323\0w\0356E\206\301\214h@V\206\3\321\3R\204\317\244"..., 131072) = 131072
read(3, "\342\304[\260L\232p\362\350;\307wA`\213\350\233?\317\245\373\216\325\362\33k3\3346>\207\333"..., 131072) = 131072
write(4, "\342\304[\260L\232p\362\350;\307wA`\213\350\233?\317\245\373\216\325\362\33k3\3346>\207\333"..., 131072) = 131072
read(3, "[\251'Y\331JS\325Y\3315\"\300\5\340%\3\320\361\245\20cr\0\2711\6Qi\33\347G"..., 131072) = 131072
write(4, "[\251'Y\331JS\325Y\3315\"\300\5\340%\3\320\361\245\20cr\0\2711\6Qi\33\347G"..., 131072) = 131072
read(3, "\256o!\364\r\240\273Cdo\330k<?\375\302\343]\252\264b\264\10\350\226\302\t2\27Z\r\254"..., 131072) = 131072
write(4, "\256o!\364\r\240\273Cdo\330k<?\375\302\343]\252\264b\264\10\350\226\302\t2\27Z\r\254"..., 131072) = 131072
read(3, "\236[\212;\272j\316_Y{\315\246\347z\177\355r\227\343Dn\311\7 v\6\10\237j\341\267^"..., 131072) = 131072
write(4, "\236[\212;\272j\316_Y{\315\246\347z\177\355r\227\343Dn\311\7 v\6\10\237j\341\267^"..., 131072) = 131072
read(3, "1\211\370\230\r-\33\346tf[\257L\304\365\304\206=\344\25\362\312\206\245\r-6\342tf\367\336"..., 131072) = 131072
write(4, "1\211\370\230\r-\33\346tf[\257L\304\365\304\206=\344\25\362\312\206\245\r-6\342tf\367\336"..., 114688) = 114688
lseek(4, 4096, SEEK_CUR)                = 1429504
write(4, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 12288) = -1 ESPIPE (Illegal seek)
```
Ten chunks of 131072 bytes were read and then written successfully.
The eleventh transfer was made of one read of 131072 followed by a write of 114688, a seek of 4096, then a write of the remaining 12288 bytes.

After opening the file with a hex editor, I noticed that in the source file there is a run of zeros starting at 131072*10+114688.
I guess rclone (or cp) was trying to be smart and issue a seek rather than writing zeros but that failed, possibly because seeks may not be supported by the remote storage API.

By the way, a big thank you to the developers. I only recently discovered Rclone and I found it extremely useful to mount remote storage without using proprietary tools.

**Comment by lciti** [comment]
Upon further investigation, this may be due to the fact that that the source file is located on a zfs dataset with compression enabled.
I have created an uncompressed dataset `zfs create -o compression=off rpool/tmp/aa`, then copied the file there and then tried to copy it from there to the remote Box folder. It works fine as it is not attempting the seek this time:

```
...
read(3, "1\211\370\230\r-\33\346tf[\257L\304\365\304\206=\344\25\362\312\206\245\r-6\342tf\367\336"..., 131072) = 131072
write(4, "1\211\370\230\r-\33\346tf[\257L\304\365\304\206=\344\25\362\312\206\245\r-6\342tf\367\336"..., 131072) = 131072
read(3, "\221\26\222\263*Y;\346k\276\303[\n\362\275:]4\257\351\264\243\265@U$\340\347\304\314\1H"..., 131072) = 41641
write(4, "\221\26\222\263*Y;\346k\276\303[\n\362\275:]4\257\351\264\243\265@U$\340\347\304\314\1H"..., 41641) = 41641
```

**Comment by lciti** [comment]
Same exact behaviour confirmed with:

rclone v1.55.1
- os/type: linux
- os/arch: amd64
- go/version: go1.16.3
- go/linking: static
- go/tags: none

(binary downloaded from https://downloads.rclone.org/rclone-current-linux-amd64.zip)

**Comment by lciti** [comment]
Thanks for showing how to solve the problem.
I wonder if it could be made more efficient (not requiring local cache) and user friendly (one may not expect a simple copy to require seeks) by detecting fast-forward seeks beyond the current length of the file and converting them to writes of zero bytes (while all other seeks could possibly still fail).

**Comment by ncw** [comment]
> Thanks for showing how to solve the problem.

No problems!

> I wonder if it could be made more efficient (not requiring local cache) and user friendly (one may not expect a simple copy to require seeks) by detecting fast-forward seeks beyond the current length of the file and converting them to writes of zero bytes (while all other seeks could possibly still fail).

Interesting idea.

I wonder how common seeking to beyond the end of the file is in apps that would then seek backwards. That is the concerning case that an app would waste lots of bandwidth writing zeroes only to be told ESPIPE when it seeked backwards...

Note that adding `--sparse=never` to the `cp` command should fix your problem too.

**Comment by lciti** [comment]
> I wonder how common seeking to beyond the end of the file is in apps that would then seek backwards. That is the concerning case that an app would waste lots of bandwidth writing zeroes only to be told ESPIPE when it seeked backwards...

Good point.

> Note that adding --sparse=never to the cp command should fix your problem too.

Good to know, thanks! I think this is indeed the best solution for my problem.

Thanks for your time.

**Comment by ncw** [comment]
No worries!

I'll close this now since I think we are all done :-)
