### ISSUE TITLE
Extra directories are created in cache folder!

### ISSUE THREAD

**Issue by Elixiry** [rclone/rclone#5316]
Hello, 
OS Windows
rclone ver. >rclone-v1.54.1-windows-amd64
Question: 
Why did you add {} to the name of the goal in the cache folder, now extra folders are created?

for example: 
rclone.conf
[Book]
type = local

[BookY]
type = crypt
remote = Book:B:\b
filename_encryption = obfuscate
directory_name_encryption = false
password = ***

Cache folder: D:\rc\
was: D:\rc\vfs\BookY\
became: D:\rc\vfs\BookY{Db\Y9}\
directory structure:
D:\rc\vfs\BookY{Db\
                                       Y9}\
That is, extra directories are created in cache folder!

**Comment by albertony** [comment]
Is your primary issue that the cache contains an additional subdirectory with name "Y9" within "D:\rc\vfs\BookY{Db"? This should be avoided with https://github.com/rclone/rclone/pull/5317, you will instead get a single directory "D:\rc\vfs\BookY{Db_Y9}".
