### ISSUE TITLE
VFS Upload Priority

### ISSUE THREAD

**Issue by kennyparsons** [rclone/rclone#5320]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/vfs-upload-priority-burst/24034

#### What is your current rclone version (output from `rclone version`)?
v1.55.1

#### What problem are you are trying to solve?
To set upload priorities for VFS cache, such as smaller files first.

#### How do you think rclone should be changed to solve that?
As discussed in the forum, porting the `--order-by` function to vfs/mount.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by landscapepainter** [comment]
@ncw @ivandeex Is this already implemented? Or not being implemented? Would love to have this feature as well where the order of upload from cache to cloud storage is guaranteed to follow the order of time the file was written at the cache.
