### ISSUE TITLE
Why not use AES to encrypt file contents？

### ISSUE THREAD

**Issue by linora** [rclone/rclone#5329]
Why is the password algorithm of RClone encryption not unified, that is, the file name encryption using AES algorithm, and the file content encryption using XSALSA20 POLY1305? Will XSALSA20 POLY1305 be safer than AES? As far as I know, companies like Restic and some public cloud vendors use AES to encrypt file contents

AWS S3：https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingClientSideEncryption.html
```
The following code example shows how to do these tasks:
Generate a 256-bit AES key.
Use the AES key to encrypt data on the client side before sending it to Amazon S3.
Use the AES key to decrypt data received from Amazon S3.
Print out a string representation of the decrypted object.
```

**Comment by ncw** [comment]
I use the [nacl secret box crypto](https://pkg.go.dev/golang.org/x/crypto/nacl/secretbox) to implement crypt because it combines secrecy with authentication and is hard to get wrong.

The file name encryption had to have some special properties (work in a wide ECB mode) which I couldn't get from secretbox.

Both ciphers are considered secure at the moment

**Comment by ivandeex** [comment]
question answered

**Comment by Masamune3210** [comment]
Just dropping in to say these names are hilarious lol

**Comment by tomekit** [comment]
It's worth noting that default AEAD for the very well known libsodium library: https://libsodium.gitbook.io/doc/secret-key_cryptography/aead#xchacha20-poly1305 seem to be XChaCha20-Poly1305.

Quoting:
```
XChaCha20-Poly1305 applies the construction described in Daniel Bernstein's [Extending the Salsa20 nonce](https://cr.yp.to/snuffle/xsalsa-20081128.pdf) paper to the ChaCha20 cipher in order to extend the nonce size to 192-bit. This extended nonce size allows random nonces to be safely used, and also facilitates the construction of misuse-resistant schemes.
```

We're migrating away from AES-GCM and would be happy to align our encryption [S3Drive](https://s3drive.app/) to match the one in Rclone, however given our platform (Flutter) and default bindings to libsodium, XChaCha20-Poly1305 is the natural choice.

**Comment by tomekit** [comment]
It's worth noting that default AEAD for the very well known libsodium (some say successor of Nacl) library: https://libsodium.gitbook.io/doc/secret-key_cryptography/aead#xchacha20-poly1305 seem to be XChaCha20-Poly1305.

Quoting:
> XChaCha20-Poly1305 applies the construction described in Daniel Bernstein's [Extending the Salsa20 nonce](https://cr.yp.to/snuffle/xsalsa-20081128.pdf)
>paper to the ChaCha20 cipher in order to extend the nonce size to 192-bit. This extended nonce size allows random nonces to be safely used, and also facilitates the construction of misuse-resistant schemes.

We're migrating away from AES-GCM and would be happy to align our [S3Drive](https://s3drive.app/) encryption to match the one in Rclone, however given our platform (Flutter) and default bindings to libsodium, XChaCha20-Poly1305 is the natural choice.
