### ISSUE TITLE
Google Cloud Storage: Compatibility with gsutil's modification time metadata

### ISSUE THREAD

**Issue by database64128** [rclone/rclone#5331]
#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.55.1
- os/type: windows
- os/arch: amd64
- go/version: go1.16.3
- go/linking: dynamic
- go/tags: cmount
```

#### What problem are you are trying to solve?

The [gsutil rsync](https://cloud.google.com/storage/docs/gsutil/commands/rsync) command writes modification time as a separate metadata entry `goog-reserved-file-mtime`. Attempting to use `rclone sync` to sync files uploaded by `gsutil rsync` will result in metadata updates for every single file.

#### How do you think rclone should be changed to solve that?

If `goog-reserved-file-mtime` exists in a file's metadata, use it as the modification time instead. This behavior can be opted out with an option.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by database64128** [comment]
This is documented here: https://cloud.google.com/storage-transfer/docs/metadata-preservation#posix

**Comment by ncw** [comment]
That seems like a reasonable request - want to have a go at it?
