### ISSUE TITLE
Can't access TeamDrive with service accounts.

### ISSUE THREAD

**Issue by RafiAhmadinejad** [rclone/rclone#5334]
#### What is the problem you are having with rclone?
```
2021/05/17 10:09:00 Failed to configure Shared Drive: listing Team Drives failed: googleapi: Error 404: File not found: ., notFound
```
#### What is your rclone version (output from `rclone version`)
```
rclone v1.55.1
- os/type: windows
- os/arch: amd64
- go/version: go1.16.3
- go/linking: dynamic
- go/tags: cmount
```
#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 10, 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone config

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Rclone normally supplies a list of shared drives to choose from.

For some reason that didn't work for you.

What does

    rclone backend drives drive:

show? Does it show team drives? (Repace `drive:` with whatever you called your remote).

If you know the ID of the shared drive you can put it in the config as `team_drive = XXXXX`.

What does 

    rclone

**Comment by ivandeex** [comment]
no reply from user for 2 months
