### ISSUE TITLE
--no-check-certificate is ignored with implicit tls.

### ISSUE THREAD

**Issue by ytrezq** [rclone/rclone#5335]
The only way to send files to my web hosting provider is to use ꜰᴛᴘ.

And even when I use the option, I’m still getting :

    Failed to create file system for "epiz_28633885:htdocs": NewFs: failed to make FTP connection to "ftpupload.net:21": x509: certificate signed by unknown authority

**Comment by ncw** [comment]
Try this flag instead

      --ftp-no-check-certificate   Do not verify the TLS certificate of the server

**Comment by ivandeex** [comment]
answered
