### ISSUE TITLE
Derivable config

### ISSUE THREAD

**Issue by septs** [rclone/rclone#5354]
#### The associated forum post URL from `https://forum.rclone.org`
N/A

#### What is your current rclone version (output from `rclone version`)?
```console
$ rclone version
rclone v1.55.1
- os/type: darwin
- os/arch: amd64
- go/version: go1.16.3
- go/linking: dynamic
- go/tags: none
```

#### What problem are you are trying to solve?

Derivable config
1. Set prefix path
   e.g:
   ```ini
    [upstream-drive]
    # ..... authenticated drive ...

    [infra]
    upstream = upstream-drive # field name need discuss 
    prefix-path = infrastructure
    ```
    simplify action `rclone ls 'upstream-drive:infrastructure/....'` to `rclone ls 'infra:....'`

2. Set provide specific flags configuration (simplify action parameters)
  e.g:
   ```ini
    [upstream-drive]
    type = drive # google drive
    # ..... authenticated drive ...

    [infra]
    upstream = upstream-drive
    disable-http2 = true # without prefix name, e.g: `--drive-disable-http2` -> `disable-http2`
    ```

#### How do you think rclone should be changed to solve that?
Yes, This can improve user experience.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ivandeex** [comment]
Related to #4125

**Comment by olefrost** [comment]
> 1. Set prefix path

This can be solved by an [alias remote](https://rclone.org/alias/). Example:

    [GoogleDrive]
    type = drive
    …
    [GoogleDriveFolder]
    type = alias
    remote = GoogleDrive:path/to/folder

> 2. Set provide specific flags configuration (simplify action parameters)

Agree, it would be a nice if an alias remote supported setting/changing the flags of the origin.

You can get a similar user experience with [remote specific environment variables](https://rclone.org/docs/#config-file). Example:

    export RCLONE_CONFIG_GOOGLEDRIVEFOLDER_DISABLE_HTTP2 = "true"
    rclone lsd GoogleDriveFolder:
    # Gives same result as: rclone lsd GoogleDrive,disable_http2:path/to/folder/

Please note, there are known issues with environment variables in the pipeline. See #5341
