### ISSUE TITLE
Faster rclone copy  drivewhen copying remote to remote

### ISSUE THREAD

**Issue by Ret2lib** [rclone/rclone#5356]
#### The associated forum post URL from `https://forum.rclone.org`
I am not registered on the forum.

#### What is your current rclone version (output from `rclone version`)?
1.51.1

#### What problem are you are trying to solve?
As of now when copying remote to remote where both remote are gdrives (ie rclone cp driveOne:/ driveTwo:/), rclone downloads from driveOne and pipes it to upload of driveTwo. This process can take a long time if you have a large drive and/or slow bandwidth.

There is an an alternate solution when copying from drive to drive without the files leaving the Google datacenters.
#### How do you think rclone should be changed to solve that?
Google Drive API allows COPY of a file a user has permission to read to any directory within Google Drive. 
Google Drive API allows changing permissions for sharing of a file/folder with other users.

It is possible to combine these two features to achieve extremely fast copying (1tb file in less than a second). 

1. Use the API to share driveOne's / path with driveTwo
2. Since driveTwo now has read access, they can use Google Drive API to  copy all those files without ever downloading.

The idea is from the Chrome Extension "Copy Folder". However the extension is pretty limited because you have to share the folder yourself and than go through a silly GUI.

https://chrome.google.com/webstore/detail/copy-folder/kfbicpdhiofpicipfggljdhjokjblnhl/related?hl=en

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Masamune3210** [comment]
If you are talking about accessing and copying files from one account that can access another's files, use --drive-server-side-across-configs

**Comment by Ret2lib** [comment]
I will test this option but looking at the code here
https://github.com/rclone/rclone/blob/9e2fbe0f1a9314e1330b4adc9d69de137be12ee6/backend/drive/drive.go#L2305)
 --driver-server-side-across only works if you have access to that file and when it is across the same drive 

```// Will only be called if src.Fs().Name() == f.Name()```


it is almost what I was suggesting but in this case theres an additional of granting access for src.Fs().Name() in f.Name() and than we can call the copy()

**Comment by Ret2lib** [comment]
I shared drive A in account A with account B. I created a shortcut in Account B's drive to Drive A (By default it only shows up in "shared with me" so if you do lsd driveB:/ it will not show the shared Drive A unless you create a shortcut). I was than able to copy driveB:/driveAShortcut DriveB:/copyofdriveA

If we can automate the process of providing permission of "Drive A" to Account "B", create a shortcut for "Drive A" in Account B's drive, and than call copy() where src is the shorcut, it would be an amazing feature.

**Comment by Masamune3210** [comment]
--drive-server-side-across-configs is im almost sure exactly what you are looking for, it basically tells rclone to ignore that part of code that you posted and try server-side operations anyway. Basically it tells rclone "yes i am sure that these two accounts have permission to talk to each other, please do stuff server-side instead of the fallback method"

**Comment by Ret2lib** [comment]
Yes --drive-server-side-across-configs does indeed work for my use case IF I have already shared the drive with my account. However like I said pre-step of actually sharing the folder and than removing those permissions would make it much better.

**Comment by ncw** [comment]
So the missing piece in rclone would be a backend command (a drive specific command) to share a file/dir, lets say something like

    rclone backend share drive1:path drive2:

?

**Comment by ivandeex** [comment]
Regular cleanup of answered tickets
