### ISSUE TITLE
Poll-interval is not supported by this remote - FTP and Mega

### ISSUE THREAD

**Issue by jxrse** [rclone/rclone#5359]
I'm trying to assemble a carpet with my Raspberry PI 4 4GB Ram
With Mega I work correctly after assembling it
But ftp doesn't work, it's hosted on a hosting, not on a vps

pi @ raspberrypi: ~ $ rclone lsd ftp-peliculas:
          -1 2021-05-25 22:46:25 -1 files
pi @ raspberrypi: ~ $ rclone ls ftp-peliculas:
   419833 files / Biographical Sheet_PT_ES.pdf
pi @ raspberrypi: ~ $

How can you correctly observe the connection with the ftp

Correct credentials and connection to the correct server but in time to set up the server and the next fall.

pi @ raspberrypi: ~ $ rclone mount --allow-other --allow-non-empty -v ftp-films: / docker / ftp / &
[4] 16175
[3] Done rclone mount --allow-other --allow-non-empty -v ftp-films: / docker / ftp /
pi @ raspberrypi: ~ $ 2021/05/25 22:44:27 INFO: ftp://ftp.jesusromerodj.com:21: poll-interval is not supported by this remote

Name Type
==== ====
ftp-ftp films
mega mega

How can I solve this error, Thanks

**Comment by albertony** [comment]
The `poll-interval is not supported by this remote` message is not an error, more of a warning.
I think if you disable polling by setting `--poll-interval 0` the messages will be gone.
Read some background information [here](https://rclone.org/commands/rclone_mount/#vfs-directory-cache).

Does this answer your question?

**Comment by jxrse** [comment]
Tengo el mismo error tells me that it is not supported
Also update the latest version as you can see

pi@raspberrypi:~ $ rclone mount --allow-other --allow-non-empty --poll-interval 0 -v ftp: /docker/nube &
[1] 12506
pi@raspberrypi:~ $ 2021/05/26 21:11:12 INFO  : ftp://ftp.jesusromerodj.com:21: poll-interval is not supported by this remote
pi@raspberrypi:~ $ rclone version
rclone v1.55.1
- os/type: linux
- os/arch: arm
- go/version: go1.16.3
- go/linking: static
- go/tags: none
pi@raspberrypi:~ $

@albertony

**Comment by jxrse** [comment]
The same thing is happening to me also for a second mega account it tells me that it is not supported

pi@raspberrypi:~ $ fusermount -u /docker/ampache/data/media
pi@raspberrypi:~ $ rclone mount --allow-other --allow-non-empty --vfs-cache-mode writes --poll-interval 0 -v megamusic: /docker/ampache/data/media &
pi@raspberrypi:~ $ 2021/05/28 04:26:06 INFO  : mega root '': poll-interval is not supported by this remote
2021/05/28 04:26:06 INFO  : vfs cache: cleaned: objects 0 (was 0) in use 0, to upload 0, uploading 0, total size 0 (was 0)
