### ISSUE TITLE
Rclone fails to make cache dir if file/folder name has illegal characters on Windows

### ISSUE THREAD

**Issue by 1024mb** [rclone/rclone#5360]
#### What is the problem you are having with rclone?

With a mounted remote if said remote has an illegal character in any of it's filenames rclone will fail in creating the cache dir. In my case the parent directories (parent for the mount) have the character `:` in their names which in Windows is illegal. This should be easy to reproduce, just name a folder with one of those illegal characters, mount it on Windows and try to open a file.

#### What is your rclone version (output from `rclone version`)

1.55.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 10, x64

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone mount Crypt_Remote:REDACTED U: --read-only --volname Folder --vfs-cache-mode full --network-mode`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2021/05/25 23:47:35 ERROR : HDD (Y:)/quarentine/file.jpg: vfs cache: failed to remove cache file as failed to stat cache file: CreateFile \\?\C:\Users\1024mb\AppData\Local\rclone\vfs\Crypt_Remote\REDACTED\HDD (Y:)\quarentine\file.jpg: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos.: remove \\?\C:\Users\1024mb\AppData\Local\rclone\vfs\Crypt_Remote\REDACTED\HDD (Y:)\quarentine\file.jpg: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos.
2021/05/25 23:47:35 ERROR : HDD (Y:)/quarentine/file.jpg: vfs cache: failed to remove metadata from cache as failed to stat cache file: CreateFile \\?\C:\Users\1024mb\AppData\Local\rclone\vfs\Crypt_Remote\REDACTED\HDD (Y:)\quarentine\file.jpg: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos.: remove \\?\C:\Users\1024mb\AppData\Local\rclone\vfsMeta\Crypt_Remote\REDACTED\HDD (Y:)\quarentine\file.jpg: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos.
2021/05/25 23:47:35 ERROR : HDD (Y:)/quarentine/file.jpg: vfs cache: failed to remove cache file as failed to load metadata: vfs cache item: failed to read metadata: open \\?\C:\Users\1024mb\AppData\Local\rclone\vfsMeta\Crypt_Remote\REDACTED\HDD (Y:)\quarentine\file.jpg: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos.: remove \\?\C:\Users\1024mb\AppData\Local\rclone\vfs\Crypt_Remote\REDACTED\HDD (Y:)\quarentine\file.jpg: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos.
2021/05/25 23:47:35 ERROR : HDD (Y:)/quarentine/file.jpg: vfs cache: failed to remove metadata from cache as failed to load metadata: vfs cache item: failed to read metadata: open \\?\C:\Users\1024mb\AppData\Local\rclone\vfsMeta\Crypt_Remote\REDACTED\HDD (Y:)\quarentine\file.jpg: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos.: remove \\?\C:\Users\1024mb\AppData\Local\rclone\vfsMeta\Crypt_Remote\REDACTED\HDD (Y:)\quarentine\file.jpg: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos.
2021/05/25 23:47:35 ERROR : HDD (Y:)/quarentine/file.jpg: vfs cache: failed to open item: vfs cache item: open mkdir failed: make cache REDACTED failed: mkdir \\?\C:\Users\1024mb\AppData\Local\rclone\vfs\Crypt_Remote\REDACTED\HDD (Y:): El nombre del directorio no es válido.
2021/05/25 23:47:35 ERROR : HDD (Y:)/quarentine/file.jpg: Non-out-of-space error encountered during open
2021/05/25 23:47:35 ERROR : IO error: open RW handle failed to open cache file: vfs cache item: open mkdir failed: make cache REDACTED failed: mkdir \\?\C:\Users\1024mb\AppData\Local\rclone\vfs\Crypt_Remote\REDACTED\HDD (Y:): El nombre del directorio no es válido.
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment]
I guess something like the following will also fail, if I understand the issue correctly:

`rclone lsd "Crypt_Remote:REDACTED/HDD (Y:)"`
`rclone copy "Crypt_Remote:REDACTED/HDD (Y:)/quarentine" .`

**Comment by 1024mb** [comment]
No, those two don't fail. They would if they would make rclone create a file/folder with the `:` in the name. I can list and I can copy files from the remote because rclone doesn't create the `HDD (Y:)` folder to download/list files. All what it fails in this issue is the part where rclone tries to create the directory `HDD (Y:)` inside the `REDACTED` dir because Windows doesn't acccept `:` in paths.

**Comment by albertony** [comment]
OK.. I tested with another backend, and there are some differences regarding what rclone treats as legal characters for each backend. And I'm struggling a bit to grasp the exact "flow" here, and e.g. if this is something that should have been prevented by the backend encoding..

Quick questions, just to be sure:
You have a dir with name `HDD (Y:)` in your remote? How did you create it, I mean using rclone, and from Windows, or some other way?

I did another attempt at reproducing, and think I got closer to do so. Tried a small change in cache path handling that possibly fixes it. Are you willing to run a quick test with a beta build from my fork: https://github.com/albertony/rclone/releases/tag/v1.56.0-cache-ospath-01 ?

**Comment by 1024mb** [comment]
>
>
> Quick questions, just to be sure:
> You have a dir with name `HDD (Y:)` in your remote? How did you create it, I mean using rclone, and from Windows, or some other way?

Yes. My remote is:

```
REDACTED
		/ HDD (Y:)
					/ quarentine
```

The directory was created using rclone on Windows by using something like:

`rclone copy Y:\ "Crypt_Remote:REDACTED\HDD (Y:)"`

The directory containing the `:` char doesn't exist on the local path, it was created when trasferring the files from local to remote.  
  

>
> 
> I did another attempt at reproducing, and think I got closer to do so. Tried a small change in cache path handling that possibly fixes it. Are you willing to run a quick test with a beta build from my fork: [albertony/rclone@`v1.56.0-cache-ospath-01` (release)](https://github.com/albertony/rclone/releases/tag/v1.56.0-cache-ospath-01) ?

Just tried your build and the mount works well now, I have tried opening some files and it went all well and I got nothing in the logs anymore. Thanks for looking into this.

**Comment by albertony** [comment]
>The directory was created using rclone on Windows by using something like:

I see, thanks for explaining (again).

> Just tried your build and the mount works well now, I have tried opening some files and it went all well and I got nothing in the logs anymore. 

Thats great, thanks for testing! There might be more to it before a final fix, as this was sort of a quick "proof of consept", but I will create a pull request and get to the bottom of it there.

**Comment by 1024mb** [comment]
@ncw @albertony
Hey guys please don't forget about this, I saw a new update for rclone but this wasn't included/merged.  
Thank you all for your work.

**Comment by ncw** [comment]
Sorry this fell off my radar for the release. I'll follow up on the PR.
