### ISSUE TITLE
Mount a drive in an empty folder

### ISSUE THREAD

**Issue by x3inspire** [rclone/rclone#5368]
Hi, possible for rclone to mount cloud remote to drive in an empty folder like Windows?  Cloud remote required drive letter, so we only limited up to Z folder.

https://docs.microsoft.com/en-us/windows-server/storage/disk-management/assign-a-mount-point-folder-path-to-a-drive?fbclid=IwAR33Vl3Q4v0Ja3flXs5AjK5897Sm1zl9WlKDh-dhSpvqqEEqyrjfhrBwNaQ

**Comment by albertony** [comment]
Do you mean something different than the existing:

`rclone mount remote:path/to/files C:\path\mount`

documented here https://rclone.org/commands/rclone_mount/#mounting-modes-on-windows?

**Comment by ivandeex** [comment]
2 months of no reply from user.
In august this issue will become eligible for closing...
