### ISSUE TITLE
can not mount GoogleDrive with Root: node=/, err=<nil>

### ISSUE THREAD

**Issue by xiaoluoabc123** [rclone/rclone#5371]
2021/05/30 23:17:06 DEBUG : Creating backend with remote "GoogleDrive:"
2021/05/30 23:17:06 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2021/05/30 23:17:06 DEBUG : Google drive root '': 'root_folder_id = 0ADBhbi32mZhsUk9PVA' - save this in the config to speed up startup
2021/05/30 23:17:06 DEBUG : Google drive root '': Mounting on "/etc/GDrive"
2021/05/30 23:17:06 DEBUG : : Root:
2021/05/30 23:17:06 DEBUG : : >Root: node=/, err=<nil>

**Comment by albertony** [comment]
No error messages? The mount is just not created?

Can you please include more of what the bug report issue template asks, e.g. rclone version, command line, more from the log output if possible..

**Comment by animosity22** [comment]
Please use the forums for help on how to use rclone.

https://forum.rclone.org/

The Help and Support template is what you are looking for.
