### ISSUE TITLE
Microsoft Teams config not working with newer sharepoint setups

### ISSUE THREAD

**Issue by laramy2020** [rclone/rclone#5375]
#### What is the problem you are having with rclone?
Mounting a Microsoft Teams sharepoint site. 
The config is made using the interactive prompts,
Onedrive
Global
relative path

The issue seams to stem from newer Microsoft teams group that are created. Their sharepoint url's replace site with teams.

Using the url option in onedrive fails (option 3)
Using the relative path finds the document library, and we can select the one we want. But we can not mount the drive nor browse it with ls (option 7)
if the sharepoint url is under the teams side and not site option 4 for searching fails.

#### What is your rclone version (output from `rclone version`)
rclone v1.55.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows Server 2019 64-bit

#### Which cloud storage system are you using? (e.g. Google Drive)
OneDrive/Sharepoint

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone mount $remote$ $Driveletter$
rclone ls $remote$:

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2021/06/01 13:13:08 DEBUG : Using config file from "C:\\Path\\To\Config\\rclone.conf"
2021/06/01 13:13:08 DEBUG : rclone: Version "v1.55.1" starting with parameters ["rclone.exe" "-vv" "ls" "synctest:"]
2021/06/01 13:13:08 DEBUG : Creating backend with remote "synctest:"
2021/06/01 13:13:09 DEBUG : 5 go routines active
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> #### What is the problem you are having with rclone?
> Mounting a Microsoft Teams sharepoint site.
> The config is made using the interactive prompts,
> Onedrive
> The issue seams to stem from newer Microsoft teams group that are created. Their sharepoint url's replace site with teams.

Can you give an example?
 
> Using the url option in onedrive fails (option 3)
> Using the relative path finds the document library, and we can select the one we want. But we can not mount the drive nor browse it with ls (option 7)

What errors do you get when you try to `rclone lsf -vv` the remote created?

> if the sharepoint url is under the teams side and not site option 4 for searching fails.

Could you also give [the latest beta](https://beta.rclone.org/) a try? The config system got heavily re-worked. Not sure it will fix your problem, but worth a try!

**Comment by laramy2020** [comment]
Thanks for pointing me to the beta
version  v1.56.0-beta.5550.3349b055f is working for me.

**Comment by Cnly** [comment]
Glad that your problem is solved @laramy2020! I'll close this for now and please feel free to reopen if you see the problem again.
