### ISSUE TITLE
Remote-to-Remote (different remotes) Direct copying

### ISSUE THREAD

**Issue by RaXorX** [rclone/rclone#5376]
#### What is the problem you are having with rclone?
Failed to backend: mega root '': doesn't support backend commands

#### What is your rclone version (output from `rclone version`)
1.55.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 10 64-bit

#### Which cloud storage system are you using? (e.g. Google Drive)
Mega, Google Drive, WebDav

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone backend copyid drive: FILEID C:
rclone backend copyid drive: FILEID C:\TMP.rar

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2021/06/02 01:12:16 DEBUG : rclone: Version "v1.55.1" starting with parameters ["rclone" "-vv" "backend" "copy" "Mega_H:Inkle" "AppImage.zip" "GDrive_T2:"]
2021/06/02 01:12:19 DEBUG : 8 go routines active
2021/06/02 01:12:19 Failed to backend: mega root 'Inkle': doesn't support backend commands
```

Continuing it from [here](https://github.com/rclone/rclone/issues/4737), I am afraid I forgot what I was trying to do earlier when I had posted that, but I do remember my last unsuccessful voyage with rclone that I was trying to do and supposedly that post above should have been it only. Correct me if I am wrong in assuming that backend provides support for remote to remote direct copying without it downloading the file offline (on desktop) and uploading it back to the other remote. At least that's what I understood from it and was trying to do. You can already see my command and the output it gives. Same thing happens with a webdav instead of mega. 

Also in the log above I am using copy instead of copyid but both give the same result.

EDIT: Oh well, I guess I might be wrong. I did find out what I was trying to do last time for which I had posted that issue. Copy files from a shared google drive link to desktop. 
Welps, I thought it was for remote-to-remote (different remotes) direct copying, I guess not. Is that actually a feature with rclone?

**Comment by ncw** [comment]
> Welps, I thought it was for remote-to-remote (different remotes) direct copying, I guess not. Is that actually a feature with rclone?

Rclone can't do that at the moment. A small number of remotes support it so we might add it at some point.

**Comment by animosity22** [comment]
This looks answered as well so I'm going to close it out.
