### ISSUE TITLE
docs: cache: cache&crypt order clarification

### ISSUE THREAD

**Issue by jtagcat** [rclone/rclone#5380]
/assign self

#### What is the problem you are having with rclone?

https://rclone.org/cache/#cache-and-crypt is confusing to understand

#### Which cloud storage system are you using? (e.g. Google Drive)
cache, crypt

***

I looked at it confused, with the arrows (`**cloud remote** -> **cache** -> **crypt**`).

I would conclude, that the correct way should be:
```
┌────────────────────────────────────────┐
│ crypt:      (interact with this daily) │
│   ┌─────────────────┐                  │
│   │ cache:          │                  │
│   │    ┌──────┐     │                  │
│   │    │cloud:│     │                  │
│   │    └──────┘     │                  │
│   │                 │                  │
│   └─────────────────┘                  │
│                                        │
└────────────────────────────────────────┘
```

@remusb is this correct?

/assign self, I'd like to improve the docs, by somehow demonstrating the nested order. Maybe `{crypt: {cache: {cloud:}}}` or just saying 'crypt: being the remote you usually will interact with'.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> I looked at it confused, with the arrows (`**cloud remote** -> **cache** -> **crypt**`).
> 
> I would conclude, that the correct way should be:
> 
> ```
> ┌────────────────────────────────────────┐
> │ crypt:      (interact with this daily) │
> │   ┌─────────────────┐                  │
> │   │ cache:          │                  │
> │   │    ┌──────┐     │                  │
> │   │    │cloud:│     │                  │
> │   │    └──────┘     │                  │
> │   │                 │                  │
> │   └─────────────────┘                  │
> │                                        │
> └────────────────────────────────────────┘
> ```

Love the ASCII art!

Yes that is correct.
