### ISSUE TITLE
rclone `--rc-web-gui` treats HTTP 403 from github as fatal, rather than skipping the update check

### ISSUE THREAD

**Issue by slippycheeze** [rclone/rclone#5385]
#### What is the problem you are having with rclone?

I managed to exhaust the anonymous request quota on api.github.com through a service supervisor failure combined with a bad command line argument to rclone.  ouch.

At that point I was unable to start rclone with `--rc-web-gui` at all, because it treats the 403 error as fatal -- despite having the web gui files in the appropriate path already.

```
PS C:\Users\danie> c:/Users/danie/scoop/shims/rclone.exe mount putio:/ p: --use-mmap --log-level=INFO --stats=1m --stats-one-line-date --fast-list --poll-interval=10s --vfs-cache-mode=full --vfs-cache-max-size=1G "--volname=\\\\putio\\putio" --rc --rc-user=putio --rc-pass=putio --rc-web-gui-no-open-browser --rc-web-gui
2021/06/07 20:29:18 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
```

```
{"message":"API rate limit exceeded for 178.85.91.115. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

#### What is your rclone version (output from `rclone version`)

```
rclone v1.55.1
- os/type: windows
- os/arch: amd64
- go/version: go1.16.3
- go/linking: dynamic
- go/tags: cmount
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 10 Pro, 64-bit

#### Which cloud storage system are you using? (e.g. Google Drive)

putio, but this is a generic issue.  Probably fixed by changing https://github.com/rclone/rclone/blob/41f561bf26be9a5a7360bdbdf5a820037e76b86a/fs/rc/rcserver/rcserver.go#L90 to a log level lower than fatal.

that'd be consistent, I think, with the intent -- the error message from the webgui code certainly suggests it *should* just skip the update check.

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
 c:/Users/danie/scoop/shims/rclone.exe mount putio:/ p: --use-mmap --stats=1m --stats-one-line-date --fast-list --poll-interval=10s --vfs-cache-mode=full --vfs-cache-max-size=1G "--volname=\\\\putio\\putio" --rc --rc-user=putio --rc-pass=putio --rc-web-gui-no-open-browser --rc-web-gui -vv
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2021/06/07 20:34:32 DEBUG : Using config file from "C:\\Users\\danie\\.config\\rclone\\rclone.conf"
2021/06/07 20:34:32 DEBUG : rclone: Version "v1.55.1" starting with parameters ["C:\\Users\\danie\\scoop\\apps\\rclone\\current\\rclone.exe" "mount" "putio:/" "p:" "--use-mmap" "--stats=1m" "--stats-one-line-date" "--fast-list" "--poll-interval=10s" "--vfs-cache-mode=full" "--vfs-cache-max-size=1G" "--volname=\\\\\\\\putio\\\\putio" "--rc" "--rc-user=putio" "--rc-pass=putio" "--rc-web-gui-no-open-browser" "--rc-web-gui" "-vv"]
2021/06/07 20:34:32 Error while fetching the latest release of Web GUI: Error checking for web gui release update, skipping update: bad HTTP status 403 (403 Forbidden) when fetching https://api.github.com/repos/rclone/rclone-webui-react/releases/latest
```

**Comment by ncw** [comment]
Yes I think this should be an `fs.Errorf` rather than a `log.Fatal` - do you want to send a PR?
