### ISSUE TITLE
union "upload succeeded try" not working if not first time

### ISSUE THREAD

**Issue by cberni** [rclone/rclone#5386]
rclone v1.55.1
ubuntu 20.04 lts server
google cloud storage

[union]
type = union
upstreams = remote:teste-union /local
action_policy = all
create_policy = all
search_policy = ff

[remote]
type = google cloud storage
service_account_file = /etc/union/file.json

rclone mount union --vv

2021/06/01 02:21:34 DEBUG : rclone: Version "v1.55.1" finishing with parameters ["/usr/bin/rclone" "mount" "union:" "/union" "--umask=0002" "--allow-other" "--default-permissions" "-vv"]
2021/06/01 02:21:34 INFO : Exiting...
2021/06/01 02:21:34 DEBUG : Using config file from "/etc/union/rclone.conf"
2021/06/01 02:21:34 DEBUG : rclone: Version "v1.55.1" starting with parameters ["/usr/bin/rclone" "mount" "union:" "/union" "--umask=0002" "--allow-other" "--default-permissions" "-vv"]
2021/06/01 02:21:34 DEBUG : Creating backend with remote "union:"
2021/06/01 02:21:34 DEBUG : Creating backend with remote "/local"
2021/06/01 02:21:34 DEBUG : Creating backend with remote "remote:teste-union"
2021/06/01 02:21:34 DEBUG : union root '': actionPolicy = *policy.All, createPolicy = *policy.All, searchPolicy = *policy.FF
2021/06/01 02:21:34 INFO : union root '': poll-interval is not supported by this remote
2021/06/01 02:21:34 DEBUG : vfs cache: root is "/var/cache/union/rclone/vfs/union"
2021/06/01 02:21:34 DEBUG : vfs cache: metadata root is "/var/cache/union/rclone/vfs/union"
2021/06/01 02:21:34 DEBUG : Creating backend with remote "/var/cache/union/rclone/vfs/union"
2021/06/01 02:21:34 DEBUG : union root '': Mounting on "/union"
.
.
.

all is working well. writing local and remote.
So I blocked internet connectivity to test remote actions.
than I create a new file "newfile" inside /union

2021/06/01 03:22:01 DEBUG : newfile: vfs cache: starting upload
2021/06/01 03:22:01 ERROR : newfile: Failed to copy: 1 error: remote: Get "https://storage.googleapis.com/storage/v1/b/teste-union/o/newfile?alt=json&prettyPe": oauth2: cannot fetch token: Post "https://oauth2.googleapis.com/token": dial tcp: lookup oauth2.googleapis.com on 127.0.0.53:53: write udp 127.0.0.127.0.0.53:53: write: operation not permitted
2021/06/01 03:22:01 ERROR : newfile: vfs cache: failed to upload try #5, will retry in 2m40s: vfs cache: failed to transfer file from cache to remote: 1 eote: Get "https://storage.googleapis.com/storage/v1/b/teste-union/o/newfile?alt=json&prettyPrint=false": oauth2: cannot fetch token: Post "https://oauth2.s.com/token": dial tcp: lookup oauth2.googleapis.com on 127.0.0.53:53: write udp 127.0.0.1:50596->127.0.0.53:53: write: operation not permitted
.
.
.

the error is ok because lost internet and the file was created only local.
than turn on internet again...

2021/06/01 03:22:45 DEBUG : newfile: vfs cache: starting upload
2021/06/01 03:22:50 DEBUG : newfile: MD5 = d41d8cd98f00b204e9800998ecf8427e OK
2021/06/01 03:22:50 INFO : newfile: Copied (new)
2021/06/01 03:22:50 DEBUG : newfile: vfs cache: fingerprint now "0,2021-06-01 03:20:10.150534658 +0000 UTC,d41d8cd98f00b204e9800998ecf8427e"
2021/06/01 03:22:50 DEBUG : newfile: vfs cache: writeback object to VFS layer
2021/06/01 03:22:50 DEBUG : newfile: Not setting pending mod time 2021-06-01 03:20:10.150534658 +0000 UTC as it is already set
2021/06/01 03:22:50 DEBUG : : Added virtual directory entry vAddFile: "newfile"
2021/06/01 03:22:50 INFO : newfile: vfs cache: upload succeeded try #6
.
.
.

the "newfile" is set as succeeded but nothing arrives in the backend storage.
is there a bug? or something I not doing right?

the "newfile" was created only on local in the first time and no copy to storage backend because lost connectivity. but the log stay printing "will retry" until internet connectivity turn it back and printing "succeeded" but no "newfile" in the storage backend. only in local.

**Comment by ncw** [comment]
> the "newfile" is set as succeeded but nothing arrives in the backend storage.
> is there a bug? or something I not doing right?
> 
> the "newfile" was created only on local in the first time and no copy to storage backend because lost connectivity. but the log stay printing "will retry" until internet connectivity turn it back and printing "succeeded" but no "newfile" in the storage backend. only in local.

The union backend for policy `all` doesn't (yet) have a mechanism to ensure that the content gets synced between the remotes. It will only get uploaded to available remotes.

You could do it manually with `rclone sync`

**Comment by cberni** [comment]
I can do it with rclone sync to be sure the files are synced ok. Thanks!

BUT it was a bit strange the "newfile" was written to local and kept trying write until the internet connectivity turns back to print succeeded but write only in local.

Would be a great improvement!

**Comment by cberni** [comment]
when reading files we need try get it from local every time and only if it is not in local than get it from remote.

if change search_policy = all will read files first on local every time?

**Comment by animosity22** [comment]
This is an old question. If you need more info, please feel free to use the forums as this looks answered.
