### ISSUE TITLE
Part of filtering docs doesn't have formatting

### ISSUE THREAD

**Issue by parasiteoflife** [rclone/rclone#5387]
#### What is the problem you are having with rclone?

Part of the filtering documentation doesn't have formatting, it looks like this:

https://i.imgur.com/quyMnon.png

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment]
This is the section from the screen shot:

    `*`         matches any sequence of non-separator (`/`) characters
    `**`        matches any sequence of characters including `/` separators
    `?`         matches any single non-separator (`/`) character
    `[` [ `!` ] { character-range } `]`
                character class (must be non-empty)
    `{` pattern-list `}`
                pattern alternatives
    c           matches character c (c != `*`, `**`, `?`, `\`, `[`, `{`, `}`)
    `\` c       matches character c

Do you have a suggestion for how to improve it?

**Comment by parasiteoflife** [comment]
Thank you!
