### ISSUE TITLE
Documentation for Google Drive doesn't include requirement to create test user.

### ISSUE THREAD

**Issue by darrenrhs** [rclone/rclone#5393]
This is a documentation issue.

Adding a Google Drive remote requires, in addition to the instructions listed in rclone/docs/content/drive.md, the creation of a test user in the Google dev console. See this comment: https://github.com/googleapis/google-api-php-client/issues/2001#issuecomment-754136442

Cheers

**Comment by parasiteoflife** [comment]
I've never created any test user and rclone works fine.

**Comment by darrenrhs** [comment]
Might it be a new thing since you set it up?

Before adding myself as a test user I got a 403 error when I tried to authorise rclone. It stated I wasn’t added as a user for the project.

**Comment by ncw** [comment]
I think the test credentials will mean your oauth expires after a week, so you want to get it upgraded if you can.

**Comment by darrenrhs** [comment]
@ncw upgraded how?

**Comment by darrenrhs** [comment]
Thank you for helping. The documentation states you should choose 'external.'

Attempted to start again from scratch. Internal was refused as an option because I don't have a GSuite subscription.

Setting up external again, I am told "While publishing status is set to 'Testing,' only test users are able to access the app."

I am again presented with 403 when attempting to authorise rclone.

Attempted to fix the problem by adding all available APIs to scope. Did not work, reverted.

**Attempted to fix the problem by using the button "Publish App" which presents a dialogue reading thus:** 

> Push to production?
> Your app will be available to any user with a Google Account.
> You do not need to submit your app for verification. If you change your app's configuration in the future, like adding more than 10 domains, uploading a logo or requesting sensitive or restricted scopes, you will need to submit for verification.

**SUCCESS!**

The documentation should be amended to include step to "Publish App" under the subtitle "Publishing Status" under the "OAuth Consent Screen" sidebar option.

Created pull request 5396: https://github.com/rclone/rclone/pull/5396
