### ISSUE TITLE
Problem to mount drive if rate limited.

### ISSUE THREAD

**Issue by telvenes** [rclone/rclone#5394]
#### Output of `rclone version`
rclone v1.55.1
- os/type: linux
- os/arch: amd64
- go/version: go1.16.3
- go/linking: static
- go/tags: none

#### Describe the issue
If rate limit 403 on google drive has been hit there is no way to mount the drive.

**Comment by ncw** [comment]
This would be a better question for [posting on the rclone forum](https://forum.rclone.org/). I'm going to close this one - can you ask there and add some logs please? Thanks
