### ISSUE TITLE
client-ca flag missing

### ISSUE THREAD

**Issue by thdesy** [rclone/rclone#5395]
#### What is the problem you are having with rclone?

using a non-standard root CA fails as the `--client-ca` flag is not known (while mentioned in the man pages - seems to be added with #2966)

No connection attempt is made and rclone exits immediately while evaluating the arguments

```
rclone --client-ca /cvmfs/grid.cern.ch/etc/grid-security/certificates/ ls URL
Error: unknown flag: --client-ca
Usage:
  rclone ls remote:path [flags]

Flags:
  -h, --help   help for ls

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.

2021/06/09 11:35:49 Fatal error: unknown flag: --client-ca
```

#### What is your rclone version (output from `rclone version`)
tested on Fedora 33 with `v1.55.1-DEV` and selfupdated `v1.55.1`

rclone v1.55.1
- os/type: linux
- os/arch: amd64
- go/version: go1.16.3
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Fedora 33 
5.11.17-200.fc33.x86_64

#### Which cloud storage system are you using? (e.g. Google Drive)

WebDAV/NextCloud

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
 rclone --client-ca /cvmfs/grid.cern.ch/etc/grid-security/certificates/ ls dot-dcache:pnfs/desy.de/dot/store/root_v6.18.02.Linux-centos7-x86_64-gcc4.8.tar.gz
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
> rclone -vv --client-ca /cvmfs/grid.cern.ch/etc/grid-security/certificates/ ls dot-dcache:pnfs/desy.de/dot/store/root_v6.18.02.Linux-centos7-x86_64-gcc4.8.tar.gz
Error: unknown flag: --client-ca
Usage:
  rclone ls remote:path [flags]

Flags:
  -h, --help   help for ls

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.

2021/06/09 11:40:43 Fatal error: unknown flag: --client-ca
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
The client-ca is for running an http **server** to verify the clients connecting against.

If you want to use a CA for http **client** requests then there are some hints here

https://rclone.org/faq/#rclone-gives-x509-failed-to-load-system-roots-and-no-roots-provided-error

**Comment by thdesy** [comment]
Hi,

many thanks for the fast answer - I unfortunately misunderstood the flag 😓

I can confirm, that exporting the environment variable (pointing to the directory containing the CA certificates)  solves my problem

```
> export SSL_CERT_FILE=/cvmfs/grid.cern.ch/etc/grid-security/certificates/
> rclone  ls dot-dcache:pnfs/desy.de/dot/store/root_v6.18.02.Linux-centos7-x86_64-gcc4.8.tar.gz
143472901 root_v6.18.02.Linux-centos7-x86_64-gcc4.8.tar.gz
> echo $?
0
```

Sorry for the noise,
  Thomas

**Comment by ncw** [comment]
No probs and thanks for writing the solution :-)
