### ISSUE TITLE
Abort process if source/dest drive doesn't exist

### ISSUE THREAD

**Issue by mrx23dot** [rclone/rclone#5397]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.44
- os/arch: windows/386
- go version: go1.11

#### What problem are you are trying to solve?
Sync from PC to external drive.

#### How do you think rclone should be changed to solve that?
Drive can be disconnected/offline, currently rclone still checks every file and returns error in log for eachg when I forget to connect external drive. With high CPU.

It should abort early, if source or destination drive doesn't exist.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
What command are you running?

Is the external disk the source or destination?

Can you try a newer rclone? 1.44 is very old.

**Comment by mrx23dot** [comment]
Same happens with rclone v1.55.1
It just lists everything even though destination doesn't exist.
I would say let's look before we step.
Missing destination is not a transient problem.

dir A:
The system cannot find the path specified.

```

rclone sync "C:\apps" "A:\apps"

2021/06/10 17:12:51 ERROR : IAR8301/arm/cstat/camomile/locales/ur_PK.mar: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2021/06/10 17:12:51 ERROR : IAR8301/arm/cstat/camomile/locales/uz.mar: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2021/06/10 17:12:51 ERROR : IAR8301/arm/cstat/camomile/locales/ur.mar: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2021/06/10 17:12:51 ERROR : IAR8301/arm/cstat/camomile/locales/uz_UZ.mar: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2021/06/10 17:12:51 ERROR : IAR8301/arm/cstat/camomile/locales/vi_VN.mar: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2021/06/10 17:12:51 ERROR : IAR8301/arm/cstat/camomile/locales/zh.mar: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.
2021/06/10 17:12:51 ERROR : IAR8301/arm/cstat/camomile/locales/vi.mar: Failed to copy: mkdir \\?: The filename, directory name, or volume label syntax is incorrect.


```

**Comment by albertony** [comment]
Created a separate issue for improving the strange error message, `Failed to copy: mkdir \\?`: https://github.com/rclone/rclone/issues/5400

**Comment by animosity22** [comment]
This looks to be solved and the secondary item closed as well. If not, let me know.

Thanks!

**Comment by mrx23dot** [comment]
Could we create a new exe release?

**Comment by animosity22** [comment]
You can grab the new release from the downloads.

**Comment by mrx23dot** [comment]
Just tested rclone v1.57.0
Still creates one error entry in log for each file when drive is not available (Y:).

rclone sync "D:\" "Y:\"

2022/01/01 21:48:59 ERROR : cmder/vendor/conemu-maximus5/ConEmu/Addons/utf-8-test.cmd: Failed to copy: mkdir \\?\Y:\: The parameter is incorrect.
2022/01/01 21:48:59 ERROR : cmder/vendor/conemu-maximus5/ConEmu/Addons/Lines18a.bmp: Failed to copy: mkdir \\?\Y:\: The device is not ready.
2022/01/01 21:48:59 ERROR : Attempt 3/3 failed with 573 errors and: mkdir \\?\Y:\: The device is not ready.
2022/01/01 21:48:59 Failed to sync with 573 errors: last error was: mkdir \\?\Y:\: The device is not ready.

It could simply assert that source+destination drive is accessible (listable?) as first step, and fail early.

**Comment by animosity22** [comment]
The pull was for the odd message which is merged.

You simply check if the drive exists before you sync as well as looks to be a hardware issue.e
