### ISSUE TITLE
Use move with server_side_across_configs on Google Drive?

### ISSUE THREAD

**Issue by orschiro** [rclone/rclone#5403]
Hi guys!

I am wondering what is needed to make move compatible with server_side_across_configs?

Is this a feature that can be added or simply a limitation that is not supported by Google Drive?

Thank you!

**Comment by Masamune3210** [comment]
server_side_across_configs can be used if both accounts have r/w access to the same folder on google drive

**Comment by orschiro** [comment]
They do but move still didn't change ownership which is what I had expected. 

Copy does. But then you need to delete the files manually after copy is done.

**Comment by animosity22** [comment]
Closing as this is answered.

**Comment by orschiro** [comment]
@animosity22 how is this answered?

I still don't have an answer to whether somehow move can also change ownership when using server side configs.

**Comment by animosity22** [comment]
@orschiro - server side moves you already answered it. You the source needs write in the destination to move server side. If you don't want to use server side, you can disable it. It's how the API works.

**Comment by orschiro** [comment]
I have write access in the destination but still rclone doesn't change owner when using move.
