### ISSUE TITLE
Onedrive: Cannot use rclone link on Sharepoint

### ISSUE THREAD

**Issue by Levi-Hope** [rclone/rclone#5416]
#### What is the problem you are having with rclone?
Cannot use `rclone link` on Microsoft Sharepoint.

But, rclone ls/cat works fine and I can generate share link through the website. So, there should be nothing wrong with my remote config and access permission.

And, I tried it on both Sharepoint site and team, the same error happens on both of them.

After some tests, I found that for config of 'Root Sharepoint site', rclone link works; For config of 'Sharepoint site' and 'Sharepoint team', the error occurs. This issue seems to stem from the fact that 'Anyone with the link' option is unavailable for non-root sites and teams.

#### What is your rclone version (output from `rclone version`)
rclone v1.56.0-DEV
80bccacd8

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Ubuntu 20.04.2 LTS, 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
Microsoft/Sharepoint

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```bash
rclone link oneShare2:tmp.txt
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
$ rclone link oneShare2:tmp.txt -vv
<7>DEBUG : rclone: Version "v1.56.0-DEV" starting with parameters ["rclone" "link" "oneShare2:tmp.txt" "-vv"]
<7>DEBUG : rclone: systemd logging support activated
<7>DEBUG : Creating backend with remote "oneShare2:tmp.txt"
<7>DEBUG : Using config file from "/home/levi/.config/rclone/rclone.conf"
<7>DEBUG : fs cache: adding new entry for parent of "oneShare2:tmp.txt", "oneShare2:"
invalidRequest: Invalid request
<7>DEBUG : 3 go routines active
Failed to link: invalidRequest: Invalid request
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> After some tests, I found that for config of 'Root Sharepoint site', rclone link works; For config of 'Sharepoint site' and 'Sharepoint team', the error occurs. This issue seems to stem from the fact that 'Anyone with the link' option is unavailable for non-root sites and teams.

Ah, so maybe this isn't something rclone can fix?

**Comment by Levi-Hope** [comment]
It seems so. Let's close it out.

**Comment by Cnly** [comment]
Although this is not a bug of rclone, we can probably still improve the behaviour on error :) I'm having #5419 as a WIP now.
