### ISSUE TITLE
--stats-one-line-date does not increment transfers when doing a server-side move

### ISSUE THREAD

**Issue by chscott** [rclone/rclone#5430]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/help-with-stats-logging/25023/8?u=chscott

#### What is the problem you are having with rclone?

The number of transfers and bytes transferred does not increase when using --stats-one-line-data and --drive-server-side-across-configs.

#### What is your rclone version (output from `rclone version`)

1.55.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 10, 64 bit.

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
rclone move Source: Target: --drive-server-side-across-configs --stats-one-line-date
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

I am unable to provide a full log due to privacy issues. There is a sample of the relevant information in the forum post and below. Note that the amount of data and number of transfers never changes.

```
2021/06/26 11:36:10 INFO  : 2021/06/26 11:36:10 -          0 / 0 Bytes, -, 0 Bytes/s, ETA -
2021/06/26 11:37:12 INFO  : 2021/06/26 11:37:12 -          0 / 13.309 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/4670)
2021/06/26 11:38:12 INFO  : 2021/06/26 11:38:12 -          0 / 30.140 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/8588)
2021/06/26 11:39:12 INFO  : 2021/06/26 11:39:12 -          0 / 44.259 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:40:12 INFO  : 2021/06/26 11:40:12 -          0 / 44.583 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:41:12 INFO  : 2021/06/26 11:41:12 -          0 / 45.878 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:42:12 INFO  : 2021/06/26 11:42:12 -          0 / 45.622 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:43:12 INFO  : 2021/06/26 11:43:12 -          0 / 44.982 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:44:12 INFO  : 2021/06/26 11:44:12 -          0 / 60.307 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:45:12 INFO  : 2021/06/26 11:45:12 -          0 / 60.908 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:46:12 INFO  : 2021/06/26 11:46:12 -          0 / 60.971 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:47:12 INFO  : 2021/06/26 11:47:12 -          0 / 60.617 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:48:12 INFO  : 2021/06/26 11:48:12 -          0 / 60.926 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:49:12 INFO  : 2021/06/26 11:49:12 -          0 / 60.342 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:50:12 INFO  : 2021/06/26 11:50:12 -          0 / 59.962 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:51:12 INFO  : 2021/06/26 11:51:12 -          0 / 60.092 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:52:12 INFO  : 2021/06/26 11:52:12 -          0 / 60.546 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:53:12 INFO  : 2021/06/26 11:53:12 -          0 / 61.603 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:54:12 INFO  : 2021/06/26 11:54:12 -          0 / 61.985 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:55:12 INFO  : 2021/06/26 11:55:12 -          0 / 63.051 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:56:12 INFO  : 2021/06/26 11:56:12 -          0 / 64.045 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:57:12 INFO  : 2021/06/26 11:57:12 -          0 / 64.151 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 11:58:12 INFO  : 2021/06/26 11:58:12 -          0 / 71.966 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10007)
2021/06/26 11:59:12 INFO  : 2021/06/26 11:59:12 -          0 / 71.837 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10007)
2021/06/26 12:00:12 INFO  : 2021/06/26 12:00:12 -          0 / 71.990 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 12:01:12 INFO  : 2021/06/26 12:01:12 -          0 / 72.331 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 12:02:12 INFO  : 2021/06/26 12:02:12 -          0 / 73.158 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 12:03:12 INFO  : 2021/06/26 12:03:12 -          0 / 73.312 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 12:04:12 INFO  : 2021/06/26 12:04:12 -          0 / 73.060 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 12:05:12 INFO  : 2021/06/26 12:05:12 -          0 / 73.890 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 12:06:12 INFO  : 2021/06/26 12:06:12 -          0 / 74.619 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 12:07:12 INFO  : 2021/06/26 12:07:12 -          0 / 79.854 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 12:08:12 INFO  : 2021/06/26 12:08:12 -          0 / 88.799 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 12:09:12 INFO  : 2021/06/26 12:09:12 -          0 / 100.392 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 12:10:12 INFO  : 2021/06/26 12:10:12 -          0 / 99.125 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
2021/06/26 12:11:12 INFO  : 2021/06/26 12:11:12 -          0 / 102.294 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/10008)
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
This is because you are doing a server side move which is more like a rename of a file than a copy, so rclone doesn't cound them as bytes transferred or files transferred.

Maybe it should?

**Comment by ncw** [comment]
@olefrost Reading the forum thread I see you gave some feedback. Maybe you'd like to submit a PR for this @olefrost ? The fix for server side copies was here 50a4ed8fc44184788bf06fda588efe88aa9410f8 so it "should" just be a matter of modifying the server side move code like the last chunk in that commit.

**Comment by olefrost** [comment]
@ncw Great tip, that is certainly a good starting point. I will take a deeper look after my summer vacation. It is fine with me if somebody else want to do it (before).

**Comment by ncw** [comment]
Thanks @olefrost :-)

**Comment by olefrost** [comment]
When somebody (perhaps myself) takes a deeper look into this, then it may be a good time to consider the different use cases. 

Perhaps it makes more sense to have separate stats for server-side operations, or a variation around this. There are some considerations in this thread: https://forum.rclone.org/t/get-real-transfer-size-and-path-for-moved-items-in-rclone-sync/25230

**Comment by ncw** [comment]
I'll just note that when we added the stats for server side copies it made a lot of users happy! The same might be the case for server side moves too (which are often implemented with a server side copy then a delete).
