### ISSUE TITLE
local rsync/copy is toooooooo slow

### ISSUE THREAD

**Issue by Omoinemie** [rclone/rclone#5439]
rclone ver: 1.53.3
system: debian 10
disk format: ntfs
shell: 
rclone sync /mnt/娱乐/ /mnt/Disk-Blk/娱乐/ -P --transfers 10
2021/07/05 11:22:59 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
Transferred:   	  407.837M / 26.395 GBytes, 2%, 1.337 MBytes/s, ETA 5h31m44s
Checks:               215 / 10231, 2%
Transferred:            9 / 292, 3%
Elapsed time:       5m5.0s

**Comment by ncw** [comment]
Can you discuss on [the rclone forum](https://forum.rclone.org/) please? Thanks
