### ISSUE TITLE
1.56 Release

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#5441]
Dear @rclone/rclone developers

I hope to get the code into shape for a release in the next week or so. I wanted to do this before I went on holiday, but I didn't manage to find the time.

After I came back from holiday I needed to take a little break from rclone work to preserve my mental health and try to get everything back into perspective. I've been trying to make the transition from rclone as a hobby to rclone as a day job and it has been surprisingly hard to give up the working on rclone in the evenings as well as the days which has been rather unhealthy for me and my family.

So I hope this short break has helped me get things back into perspective.

So I'd like suggestions for things in the PR backlog that you'd really like to see merged for 1.56. Given that the release is behind schedule as few as possible please!

Thank you all for your support

Nick

**Comment by ncw** [comment]
I have now made the release :fireworks: !

Unfortunately the docker volume plugin didn't build @ivandeex 

https://github.com/rclone/rclone/runs/3117675696?check_suite_focus=true

A permissions problem... I'm not sure why though, maybe we need to set something up at docker hub?

**Comment by ncw** [comment]
I shall close this issue now so I can close the milestone :-)

**Comment by ivandeex** [comment]
@ncw

> Unfortunately the docker volume plugin didn't build
> A permissions problem... I'm not sure why though, maybe we need to set something up at docker hub?

Yes we need. Here is what I just found.
`rclone` is a docker hub organization.
the release github action logs as `rclonebuild` into docker hub.
looks like this account cannot just create new repositories in this organization.
i manually created the `docker-volume-rclone` repository and granted builders with push permission.
then i made a temporary hacky rclone branch which just pushes the plugin to docker hub when pushed a commit.
docker repo permissions: https://hub.docker.com/repository/docker/rclone/docker-volume-rclone/permissions
released plugin: https://hub.docker.com/repository/docker/rclone/docker-volume-rclone/tags?page=1&ordering=last_updated
action log: https://github.com/rclone/rclone/actions/runs/1050302384
one-shot branch: https://github.com/rclone/rclone/commits/retry-docker-plugin-push
please dump it down the sink with your own hand 👊
