### ISSUE TITLE
Could not parse line: <!DOCTYPE html>

### ISSUE THREAD

**Issue by AyaanZaveri** [rclone/rclone#5453]
I put my pre-existing config file in _/home/.../.config/rclone/_ as **rclone.conf**, but everytime I run it, it says `Could not parse line: <!DOCTYPE html>`

**Comment by Masamune3210** [comment]
send your conf just in case with all the sensitive stuff removed, but it sounds like somehow your either copying the wrong file or you managed to get your conf mangled into a html file

**Comment by animosity22** [comment]
For general support, please use the forums:

https://forum.rclone.org/
