### ISSUE TITLE
why cant compile mount file on windows platform

### ISSUE THREAD

**Issue by lingluan533** [rclone/rclone#5457]
// Package mount implements a FUSE mounting system for rclone remotes.

// +build linux freebsd

package mount

import (
	"fmt"
	"runtime"

	"bazil.org/fuse"
	fusefs "bazil.org/fuse/fs"
	"github.com/rclone/rclone/cmd/mountlib"
	"github.com/rclone/rclone/fs"
	"github.com/rclone/rclone/vfs"
)
 
i noticed that the mount file hava ignored windows platform, so how could i compile mount function for my windows plaatform

**Comment by ncw** [comment]
You need to add `-tags cmount` to build `rclone mount` on Windows.

You'll need the development files for WinFSP and a C compiler too.

Here is how I set up my Windows machine to build rclone

https://github.com/rclone/rclone/blob/c0b2832509c8c1678de4982e4a91ce691091c078/bin/win-build.bat#L1-L6

**Comment by lingluan533** [comment]
> You need to add `-tags cmount` to build `rclone mount` on Windows.
> 
> You'll need the development files for WinFSP and a C compiler too.
> 
> Here is how I set up my Windows machine to build rclone
> 
> https://github.com/rclone/rclone/blob/c0b2832509c8c1678de4982e4a91ce691091c078/bin/win-build.bat#L1-L6

thank you, it can work now ~
