### ISSUE TITLE
rmdirs -v shows no output

### ISSUE THREAD

**Issue by Jwink3101** [rclone/rclone#5464]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/rmdirs-v-doesnt-show-anything-vv-works-as-expected/25422/3

#### What is the problem you are having with rclone?

    rmdirs -v

doesn't show any output. (note that `-vv` works)

#### What is your rclone version (output from `rclone version`)

rclone v1.55.1
- os/type: darwin
- os/arch: amd64
- go/version: go1.16.3
- go/linking: dynamic
- go/tags: cmount

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

macOS

#### Which cloud storage system are you using? (e.g. Google Drive)

local and OneDrive (but I suspect that doesn't matter)

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

    rclone -v rmdirs testdir

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

N/A (or see the forum post). The issue is that there isn't `-v` output

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Jwink3101** [comment]
From the thread discussion:

@ncw:

> I think this is a bug!
> 
> It is probably very easy to fix though.

And, in typical (but in a good way!) fassion:

> Maybe you could propose a fix?

I do not know go but I am trying to follow and figure out from context where it is happening.

I would have thought it was in `fs/operations/operations.go` (actually, I really thought it would be `cmd/rmdirs/rmdirs.go` but that just launches it).

My best guess is that at [fs/operations/operations.go#L104](https://github.com/rclone/rclone/blob/9e2fbe0f1a9314e1330b4adc9d69de137be12ee6/fs/operations/operations.go#L1046) should be `Infof` (*if* I am understanding things from `fs/log.go` correctly)

**Comment by ncw** [comment]
I think you are correct. Deleting a directory should make an `Infof` level log. Happy to receive a PR :-)
