### ISSUE TITLE
Support for AIX 7.1 and 7.2

### ISSUE THREAD

**Issue by surajsub** [rclone/rclone#5466]
More of a  question. Do we have  a rclone available for AIX 7.1 /7.2 ?

**Comment by ncw** [comment]
Go supports AIX

```
$ go tool dist list | grep aix
aix/ppc64
```

But you'll have to [compile rclone from source](https://rclone.org/install/#install-from-source) as we don't have a precompiled version.

**Comment by surajsub** [comment]
thanks. appreciate the response.
