### ISSUE TITLE
serve http exits directly after  starting

### ISSUE THREAD

**Issue by x0b** [rclone/rclone#5467]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/v1-56-0-http-serve-exits-directly-after-starting/25447/8

#### What is the problem you are having with rclone?
When I started to validate rclone 1.56.0 for RCX, the serve http command does not seem to work. Reproducing it on desktop shows that rclone is started and then exits without error (exit code 0).

#### What is your rclone version (output from `rclone version`)
```
rclone v1.56.0
- os/version: Microsoft Windows 10 Education 2009 (64 bit)
- os/kernel: 10.0.19043.1110 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.16.5
- go/linking: dynamic
- go/tags: cmount
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Win 10 x64

#### Which cloud storage system are you using? (e.g. Google Drive)
local

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
rclone.exe -vvv serve http --addr 127.0.0.1:8080 .
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2021/07/20 22:21:40 DEBUG : rclone: Version "v1.56.0" starting with parameters ["C:\\Users\\x0b\\apps\\rclone\\rclone.exe" "-vvv" "serve" "http" "--addr" "127.0.0.1:8080" "."]
2021/07/20 22:21:40 DEBUG : Creating backend with remote "."
2021/07/20 22:21:40 DEBUG : Using config file from "C:\\Users\\x0b\\.config\\rclone\\rclone.conf"
2021/07/20 22:21:40 DEBUG : fs cache: renaming cache item "." to be canonical "//?/C:/Users/x0b"
2021/07/20 22:21:40 INFO  : Local file system at //?/C:/Users/x0b: poll-interval is not supported by this remote
2021/07/20 22:21:40 INFO  :
Transferred:              0 / 0 Byte, -, 0 Byte/s, ETA -
Elapsed time:         0.2s

2021/07/20 22:21:40 DEBUG : 3 go routines active
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by x0b** [comment]
If that helps: bisected to 5d2e327b6fbec2e821f2b9f942bbaa1fe534c021

**Comment by ncw** [comment]
Thanks for the report and the bisect. I can replicate this.

If you have any ideas @innovate-invent that would be great. I'll have time to dig in tomorrow (busy today alas!)

**Comment by innovate-invent** [comment]
I think I am missing code that actually blocks until sigterm. Not sure why I would have to do this explicitly when it wasn't there before.

**Comment by Cnly** [comment]
> Not sure why I would have to do this explicitly when it wasn't there before.

https://github.com/rclone/rclone/commit/5d2e327b6fbec2e821f2b9f942bbaa1fe534c021#diff-075d22388024d28bd974d2d4de37ef820256fd54da61dd2af629dd67887a85beL53 I think there's this line that was doing it explicitly? I tried adding a `func Wait()` to lib/http and invoking it at the same place, and it seems to fix the problem. I can put that in a PR if @ncw isn't already writing one...

> It is troubling that the tests don't catch this..

That's true, we should probably have that fixed too :/

**Comment by ncw** [comment]
If you've got time to send a PR @Cnly that would be great.
