### ISSUE TITLE
OneDrive: text file treated as executable

### ISSUE THREAD

**Issue by yderi** [rclone/rclone#5470]
Hello everyone

After the mount of MS OneDrive, the file manager tries to execute the file despite it doesn't have the execute permission.
rclone v1.55.1
Ubuntu Mate 21.04
Mounted on the user logon by the following command
sh -c "rclone --vfs-cache-mode writes mount OneDrive: ~/OneDrive"

For example: create the "test" dir, save the text file "test01.txt" into that. Setup the Caja behavior to open all the text files in your text editor. Once completed, if you double click to you still get the prompt to execute or display the file.
Here is the ll command output:
ll
total 1
drwxrwxr-x 1 user user   0 тра 21 17:04 ./
drwxrwxr-x 1 user user   0 лип 21 14:11 ../
-rw-rw-r-- 1 user user 247 лип 21 14:46 test01.txt

Note, if I clone that text file to the user's home folder (native local fs) it acts as expected, which means opens a file in a default text editor.

Please review and advise. Can make additional tests if needed.

Thank you

**Comment by animosity22** [comment]
It doesn't sound like a rclone question as it's however the file manager you are using is acting. The permissions look fine and if you can open it with a CLI program, that would validate it would be the file manager.

**Comment by ncw** [comment]
> -rw-rw-r-- 1 user user 247 лип 21 14:46 test01.txt

The file doesn't look executable here.

Can you work out what property of the file is a causing the file manager to think it is executable?

**Comment by yderi** [comment]
Hello

It looks like the flag "--default-permissions" helps to resolve the issue.

So the final mount string looks like below:
`sh -c "rclone  --vfs-cache-mode writes mount OneDrive: ~/OneDrive --default-permissions"`

At least it helps to resolve the issue.

Thank you, everyone

**Comment by yderi** [comment]
FYI:
The permission doesn't changed in the terminal view
```
$ ll
total 1
drwxrwxr-x 1 user user   0 лип 21 14:50 ./
drwxrwxr-x 1 user user   0 лип 27 18:34 ../
-rw-rw-r-- 1 user user 247 лип 21 14:46 test01.txt
```

Regards,
rclone user

**Comment by ncw** [comment]
That is very interesting @yderi - I didn't think that flag would make any difference.

Can you do a before and after `stat test01.txt` and post the results?

**Comment by yderi** [comment]
here you go:

before use the flag:
```
stat test01.txt 
  File: test01.txt
  Size: 247       	Blocks: 1          IO Block: 4096   regular file
Device: 70h/112d	Inode: 14928533146761608624  Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/    user)   Gid: ( 1000/    user)
Access: 2021-07-21 14:46:07.000000000 +0300
Modify: 2021-07-21 14:46:07.000000000 +0300
Change: 2021-07-21 14:46:07.000000000 +0300
 Birth: -

```

after use the flag "--default-permissions":
```
stat test01.txt 
  File: test01.txt
  Size: 247       	Blocks: 1          IO Block: 4096   regular file
Device: 98h/152d	Inode: 14928533146761608624  Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/    user)   Gid: ( 1000/    user)
Access: 2021-07-21 14:46:07.000000000 +0300
Modify: 2021-07-21 14:46:07.000000000 +0300
Change: 2021-07-21 14:46:07.000000000 +0300
 Birth: -

```

**Comment by ncw** [comment]
Hmm, those stats are identical...

We have a workaround with the `--default-permissions flag` so I'm going to close this as we have enough unsolved mysteries :-)
