### ISSUE TITLE
v1.56 breaks in archlinux

### ISSUE THREAD

**Issue by tmpm697** [rclone/rclone#5486]
I blamed `linux` and `linux-lts` but turns out it's rclone version.

It worked ok with `1.55.1`, I had to downgrade it.

backend like `gg drive` completely not mount, `dropbox drive` tried to mount with error: `transport endpoint is not connected`,
`onedrive drive` didn't even mount.

**Comment by animosity22** [comment]
Please use the forums for support and use the help and support template.
