### ISSUE TITLE
pCloud integration broken

### ISSUE THREAD

**Issue by begincalendar** [rclone/rclone#5492]
#### The associated forum post URL from `https://forum.rclone.org`
N/A

#### What is the problem you are having with rclone?
pCloud integration has stopped working.

#### What is your rclone version (output from `rclone version`)
1.56.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Ubuntu 20.04 (64-bit)

#### Which cloud storage system are you using? (e.g. Google Drive)
pCloud

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone authorize pcloud`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
I'm seeing the following error message in my web browser (from the pCloud web app):
**Invalid 'client_id'.**

It looks like the pCloud config flow will need to be updated in the app and/or or the documentation will need to be updated.

>Solution (Please upvote so it rises to the top):
>
>    Go to https://docs.pcloud.com/my_apps/
>
>    Create a new App for your Rclone (it has to have a unique name)
>
>        All folders
>
>        Write Access: Yes
>
>    Click on the App that you created and navigate to Settings
>
>    Add your Rclone local URI to the approved Redirect URIs, then save changes
>
>        http://localhost:53682/
>
>    In rclone, configure your pcloud using the Client ID and Secret for the app.
>
>    It should open a web page for you to login and approve the app.
>
> EDIT: I made a video demonstrating the steps: https://youtu.be/cFD3ljeXeaM
> (Not sure why it's blurry, but what I'm typing doesn't really matter anyway. You can still get the gist of it.)

[Source](https://www.reddit.com/r/pcloud/comments/otctm7/pcloudrclone_remote_setup_invalid_client_id/h6uqblf)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
You can create your own creds/app here:

https://forum.rclone.org/t/unable-to-authorize-with-pcloud/25622/26?u=animosity022

Following the steps.

Until the regular rclone app is fixed.

**Comment by pkail** [comment]
I have exactly the same problem.

**Comment by ncw** [comment]
I've contacted pCloud support about this and will report back what they say!

**Comment by ncw** [comment]
I got an email back from support and the problem is resolved now.

They didn't go into any detail so thats all I know!

**Comment by pkail** [comment]
It works fine now.  Thanks very much for your help!
