### ISSUE TITLE
Google Docs can not be downloaded

### ISSUE THREAD

**Issue by TurtleEngr** [rclone/rclone#5494]
#### The associated forum post URL from `https://forum.rclone.org`

Related to this:

https://forum.rclone.org/t/rclone-copy-error-failed-to-open-source-object-open-file-failed-googleapi-error-403-only-f\
iles-with-binary-content-can-be-downloaded-use-export-with-docs-editors-files-filenotdownloadable/25390/4

#### What is the problem you are having with rclone?

This issue https://github.com/rclone/rclone/issues/5455 might be back.

I have been using rclone v1.56.0-beta.5589.da36ce08e. And it has been working for several days. The last datestamp on a file that was copied OK is "Jul 28, 2021 at 11:29am".

I noticed rclone with Google Drive was not working with Google Docs after "2021/07/28 20:36"

#### What is your rclone version (output from `rclone version`)

```
$ rclone --version
rclone v1.56.0-beta.5589.da36ce08e
- os/version: ubuntu 18.04 (64 bit)
- os/kernel: 4.15.0-151-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.16.5
- go/linking: static
- go/tags: none
```

I also tried with the latest stable version:

```
$ ./rclone --version
rclone v1.56.0-beta.5602.d0de42650.v1.56-stable
- os/version: ubuntu 18.04 (64 bit)
- os/kernel: 4.15.0-151-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.16.6
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

```
$ more /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ uname -a
Linux asimov 4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
$ /usr/local/bin/rclone -vv --stats 5s copy gdrive-bar:tmp/slide-map .
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

Output from: rclone v1.56.0-beta.5602.d0de42650.v1.56-stable

```
$ /usr/local/bin/rclone -vv --stats 5s copy gdrive-bar:tmp/slide-map .
2021/07/28 21:43:42 DEBUG : rclone: Version "v1.56.0-beta.5602.d0de42650.v1.56-stable" starting with parameters ["/us\
r/local/bin/rclone" "-vv" "--stats" "5s" "copy" "gdrive-bar:tmp/slide-map" "."]
2021/07/28 21:43:42 DEBUG : Creating backend with remote "gdrive-bar:tmp/slide-map"
2021/07/28 21:43:42 DEBUG : Using config file from "/home/bruce/.config/rclone/rclone.conf"
2021/07/28 21:43:42 DEBUG : Google drive root 'tmp/slide-map': 'root_folder_id = 0AHvyCLWcY-mRUk9PVA' - save this in \
the config to speed up startup
2021/07/28 21:43:43 DEBUG : Creating backend with remote "."
2021/07/28 21:43:43 DEBUG : fs cache: renaming cache item "." to be canonical "/home/bruce/Downloads"
2021/07/28 21:43:43 ERROR : Google drive root 'tmp/slide-map': error reading source root directory: directory not fou\
nd
2021/07/28 21:43:43 DEBUG : Local file system at /home/bruce/Downloads: Waiting for checks to finish
2021/07/28 21:43:43 DEBUG : Local file system at /home/bruce/Downloads: Waiting for transfers to finish
2021/07/28 21:43:43 ERROR : Attempt 1/3 failed with 1 errors and: directory not found
2021/07/28 21:43:43 ERROR : Google drive root 'tmp/slide-map': error reading source root directory: directory not fou\
nd
2021/07/28 21:43:43 DEBUG : Local file system at /home/bruce/Downloads: Waiting for checks to finish
2021/07/28 21:43:43 DEBUG : Local file system at /home/bruce/Downloads: Waiting for transfers to finish
2021/07/28 21:43:43 ERROR : Attempt 2/3 failed with 1 errors and: directory not found
2021/07/28 21:43:44 ERROR : Google drive root 'tmp/slide-map': error reading source root directory: directory not fou\
nd
2021/07/28 21:43:44 DEBUG : Local file system at /home/bruce/Downloads: Waiting for checks to finish
2021/07/28 21:43:44 DEBUG : Local file system at /home/bruce/Downloads: Waiting for transfers to finish
2021/07/28 21:43:44 ERROR : Attempt 3/3 failed with 1 errors and: directory not found
2021/07/28 21:43:44 INFO  :
Transferred:              0 / 0 Byte, -, 0 Byte/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         2.0s

2021/07/28 21:43:44 DEBUG : 4 go routines active
2021/07/28 21:43:44 Failed to copy: directory not found
bash: git_branch: command not found
```

I also ran this. The rclone.log file is attached.

```
/usr/local/bin/rclone --dump bodies --log-file rclone.log -vv --stats 5s copy gdrive-bar:tmp/slide-map .
```

[rclone.log](https://github.com/rclone/rclone/files/6898027/rclone.log)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
According to the log `slide-map` is a google sheet - I would have thought you would need an extension `.xlsx` here?

```
$ /usr/local/bin/rclone -vv --stats 5s copy gdrive-bar:tmp/slide-map.xlsx .
```

If that doesn't work, can you show the contents of you config file with secrets removed please?

**Comment by TurtleEngr** [comment]
In trying to reproduce this in other areas, I discovered the destination folder and files were not "writable". So it really was a permission error, on my end.  I.e. User Error.

I'll close this. Thanks for your time looking at this.
