### ISSUE TITLE
pcloud: need support for sha256

### ISSUE THREAD

**Issue by ivandeex** [rclone/rclone#5496]
#### The associated forum post URL from `https://forum.rclone.org`

n/a

#### What is your current rclone version (output from `rclone version`)?

1.56.0

#### What problem are you are trying to solve?

https://rclone.org/pcloud/#modified-time-and-hashes

> Note that pCloud also support SHA256 in the EU region, but rclone does not have support for that yet.

#### How do you think rclone should be changed to solve that?

add general support for sha256

i expect the patch to be straightforward

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Seems like a good idea to me :-)
