### ISSUE TITLE
Add flag for print stats without Transfering info

### ISSUE THREAD

**Issue by van9petryk** [rclone/rclone#5497]
[Original topic on forum](https://forum.rclone.org/t/progress-without-transfers-info-only-stats/25607)

The problem of **-P** flag is that it prints Transfering info. When i set -transfers 100, the terminal always scroll, down-up, down-up.

For my opinion, current behavior of -P flag, but without Transfering info make as default (so -P flag is no more needed).
In current version, user, that uses program first time want to know, what is happening, but need to read doc on how to enable progress info. Bad UX.

**Comment by ncw** [comment]
We have `--stats-one-line` which might be what you want?

**Comment by van9petryk** [comment]
> We have `--stats-one-line` which might be what you want?

`--stats-one-line` don't have info about elapsed time.

**Comment by ivandeex** [comment]
Let's not add 100500th flag, let's include elapsed time in --stats-one-line

**Comment by ivandeex** [comment]
@van9petryk Would you like to submit a patch to have it in --stats-one-line ?

**Comment by ivandeex** [comment]
Closed due to inactivity
