### ISSUE TITLE
self update's --quiet option, not quite quiet

### ISSUE THREAD

**Issue by elbaby** [rclone/rclone#5505]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/selfupdate-doesnt-seem-to-respect-the-quiet-option/25517/2

#### What is the problem you are having with rclone?
`rclone selfupdate --quiet` yelds the following output when it doesn't need to update itself:
`rclone is up to date`
(the same as _without_ the `--quiet` option)

#### What is your rclone version (output from `rclone version`)
```rclone v1.56.0
- os/version: ubuntu 18.04 (64 bit)
- os/kernel: 5.3.0-7648-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.16.5
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
`$` **`cat /etc/os-release`**
```
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

#### Which cloud storage system are you using? (e.g. Google Drive)
N/A

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`sudo rclone selfupdate --quiet`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
`2021/08/02 09:22:33 Can't set -v and -q`
:-)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by elbaby** [comment]
The issue is at line 161 in https://github.com/rclone/rclone/blob/master/cmd/selfupdate/selfupdate.go but I never wrote a line of go.

**Comment by ivandeex** [comment]
Low priority logging issue. Should be simple to fix. Waiting for volunteers.
