### ISSUE TITLE
Bwlimit is restricted to approx. 2.5Gbps

### ISSUE THREAD

**Issue by pharveybattelle** [rclone/rclone#5507]
Referencing forum post
https://forum.rclone.org/t/bwlimit-seems-to-be-restricted-to-approx-2-5gbps/25661

bwlimit does not allow speeds of >2.5Gbps 

rclone v1.56.0
os/version: Microsoft Windows Server 2019 Standard 1809 (64 bit)
os/kernel: 10.0.17763.2061 (x86_64)
os/type: windows
os/arch: amd64
go/version: go1.16.5
go/linking: dynamic
go/tags: cmount

rclone sync sourceuser:sourcebucket destuser:destbucket --bwlimit 500M --transfers 400 --checkers 500 --max-delete 10000 --log-level INFO --stats 1m --stats-log-level INFO --use-mmap --fast-list --modify-window 1s

Increasing maxBurstSize from 4*1024*1024 to 16*1024*1024 allows the maximum bandwidth limit to be 10Gbps.
https://github.com/rclone/rclone/blob/55e766f4e80c4f711353e0cd768f2a61db74ab1e/fs/accounting/token_bucket.go#L56

**Comment by ncw** [comment]
I found the discussion about this in 0d8bcc08da4419f41dfeea0ededba3f2afa1719f

> Revert "fs/accounting: make edge bandwidth limiters have smaller bursts to make smoother" #4987
>     
> This reverts commit 463a18aa0713a55e12e4cb6d201144121fc60ba5.
>     
> In practice this caused Windows to have a max bandwidth limit of 8
> MiB/s. This is because of the limited resolution (1ms) of the Windows
> timer.
>     
> This needs fixing in a different way.
>     
> See: https://forum.rclone.org/t/bug-report-for-v1-54-0-beta-5133/22015

463a18aa0713a55e12e4cb6d201144121fc60ba5 was an attempt to make the bandwidth limiter smoother by making it smaller for the "edge" bandwidth limiters.

So what that is saying is that reducing the maxBurstSize to 4k from 4M made it unusable on Windows.

Increasing it from 4M to 16M will make the bandwidth limiter less smooth.

A max bandwidth limit of 2.5Gbps for 4M is approx 74 x 4M buffers per second which is well inside the 1mS time resolution for Windows so whatever is happing here probably isn't to do with the timer resolution of Windows

Here is a beta which scales the maxBurst linearly above 2 Gbps - I think this should work for you - can you give it a try?

[v1.57.0-beta.5609.719949cf0.fix-5507-bwlimit](https://beta.rclone.org/branch/fix-5507-bwlimit/v1.57.0-beta.5609.719949cf0.fix-5507-bwlimit/) on branch [fix-5507-bwlimit](https://github.com/rclone/rclone/tree/fix-5507-bwlimit) (uploaded in 15-30 mins)

**Comment by pharveybattelle** [comment]
Thanks Nick.  I tested this 1.57 Beta and it works with bwlimit set to above 2.5Gbps.

**Comment by ncw** [comment]
Thanks for testing :-)

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.57 and in 1.56.1
