### ISSUE TITLE
S3 multipart upload initialization does not refresh credentials

### ISSUE THREAD

**Issue by macklin-10x** [rclone/rclone#5509]
#### What is the problem you are having with rclone?

The S3 backend appears to fail to refresh expired S3 credentials when initializing a multipart upload.  During a long-running transfer operation during which credentials may expire and need to be refreshed, the transfer fails to refresh AWS credentials for new multipart uploads, and the remaining uploads and overall transfer operation fail with errors like
`Failed to copy: multipart upload failed to initialise: ExpiredToken: The provided token has expired. status code: 400`. We're commonly running into this issue when uploading very large files, such that the checksum computation potentially takes longer than the token lifetime.

I would expect either rclone or the underlying call to the AWS SDK to refresh the credentials when this happens.

#### What is your rclone version (output from `rclone version`)

I'm running a fork/using rclone as a library, but it is based on v1.55.1
The fork injects a custom AWS credential provider that appears to work correctly under all other circumstances (long-running uploads refresh credentials correctly).

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 10, 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)

AWS S3

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I don't think rclone does any credential refreshes when uploading to s3 - that is all done in the SDK if required.

What sort of credentials are you using that need refreshing?

**Comment by macklin-10x** [comment]
We use the AssumeRole API to distribute tightly-scoped credentials to the service instances that have embedded rclone, and they typically expire after 1 hour.  The AWS SDK and rclone seems to do the right thing in other code paths, such as when uploading the individual multipart chunks.  But there seems to be a missing link in the initialize multipart upload code and the refresh isn't triggered.  I was wondering if it might be some problematic interaction between the fact that rclone turns off the AWS SDK retry mechanism in favor of its own retry logic, but that the way in which AWS is reporting this condition (TokenExpired/HTTP 400) is not being correctly retried which would presumably perform token refresh.

The minimum credential lifetime that AWS will return is 15 minutes, so it's a bit tricky to reproduce consistently.

**Comment by ncw** [comment]
> We use the AssumeRole API to distribute tightly-scoped credentials to the service instances that have embedded rclone, and they typically expire after 1 hour. The AWS SDK and rclone seems to do the right thing in other code paths, such as when uploading the individual multipart chunks.

OK

> But there seems to be a missing link in the initialize multipart upload code and the refresh isn't triggered.

I looked at the code and I don't think it does anything special/different. Can you see a difference?

> I was wondering if it might be some problematic interaction between the fact that rclone turns off the AWS SDK retry mechanism in favor of its own retry logic, but that the way in which AWS is reporting this condition (TokenExpired/HTTP 400) is not being correctly retried which would presumably perform token refresh.

Hmm, that sounds possible. Maybe you could enable AWS SDK retries and try it and see what happens. S3 is so reliable anyway it is unlikely to cause a problem in the short term to have each rclone retry retried by the SDK.

> The minimum credential lifetime that AWS will return is 15 minutes, so it's a bit tricky to reproduce consistently.

**Comment by macklin-10x** [comment]
It's a bit tricky to try to follow the full code path, but this unit test seems to be pretty clear in laying out the expectation that the SDK needs to retry this kind of request in order to trigger credential refresh:
https://github.com/aws/aws-sdk-go/blob/main/aws/request/request_test.go#L282

**Comment by macklin-10x** [comment]
I see two possible ways forward here:
1. Enable retry on the AWS SDK side.  I'm not clear on what the motivation was for disabling this and relying on rclone's retry - it seems like this would imply code duplication since the SDK already has extensive semantics for what it should retry.
2. Add this case to rclone's retry logic.

**Comment by macklin-10x** [comment]
See also:
https://github.com/aws/aws-sdk-go/blob/e2d6cb448883e4f4fcc5246650f89bde349041ec/aws/request/retryer.go#L101
https://github.com/aws/aws-sdk-go/blob/e2d6cb448883e4f4fcc5246650f89bde349041ec/aws/request/retryer.go#L239

**Comment by macklin-10x** [comment]
It is definitely interesting to me that the SDK has several more retry paths declared here that are effectively ignored by the more limited retry semantics from the S3 rclone backend:
https://github.com/rclone/rclone/blob/a5f277f47e597aece7829aac4f1a796a700e563a/backend/s3/s3.go#L1427

**Comment by ncw** [comment]
Here is why we turned off the AWS SDK retries dc06973796392edfa613a053f899ef869134c388

----
s3: use rclone's low level retries instead of AWS SDK to fix listing retries
 
 In 5470d34740d03e15 "backend/s3: use low-level-retries as the number
 of SDK retries" we switched over to using the AWS SDK low level
 retries instead of rclone's low level retry logic.
 
 This had the unfortunate attempt that retrying listings to correct XML
 Syntax errors failed on non S3 backends such as CEPH. The AWS SDK was
 also retrying the XML Syntax error request which doesn't make sense.
 
 This change turns off the AWS SDK retries in favour of just using
 rclone's retry logic.

----

This is a very similar case to the the AWS SDK using retries to refresh tokens - rclone uses retries to figure out the format of directory listings.

I've reverted that commit in this branch and then made us do 2 rclone retries and the normal number (10 by default) of s3 retries. Can you see if this fixes your problem?

[v1.57.0-beta.5623.7654e0950.fix-5509-s3-retries](https://beta.rclone.org/branch/fix-5509-s3-retries/v1.57.0-beta.5623.7654e0950.fix-5509-s3-retries/) on branch [fix-5509-s3-retries](https://github.com/rclone/rclone/tree/fix-5509-s3-retries) (uploaded in 15-30 mins)

**Comment by macklin-10x** [comment]
I've been trying to reproduce this in the context of a controlled development environment and so far I've been unable to trigger the bug; I know it's lurking there as I've seen it a number of times in our production environments, but there's platform splay to contend with.  I'll keep trying and update here once I either have a reliable reproduction or if I can't manage to get it to appear under controlled circumstances.

**Comment by ncw** [comment]
Great - thanks!
