### ISSUE TITLE
rclone fails when handling Unicode colon on Windows

### ISSUE THREAD

**Issue by alexkoay** [rclone/rclone#5512]
#### The associated forum post URL from `https://forum.rclone.org`
N/A

#### What is the problem you are having with rclone?
The Unicode colon character `：` causes issues when it appears in the filename as a source.

```
# these work assuming "test.txt" exists
rclone copyto C:\test.txt C:\test：a.txt    # test：a.txt is created
rclone copyto C:\test.txt C:\test:b.txt    # test：b.txt is created

# these work assuming "test：a.txt" exists
rclone copyto C:\test:a.txt C:\test：c.txt    # test：c.txt is created
rclone copyto C:\test:a.txt C:\test:d.txt    # test：d.txt is created

# these don't work even when "test：a.txt" exists
rclone copyto C:\test：a.txt C:\test：e.txt    # Local file system at //?/C:/test：a.txt: error reading source root directory: directory not found
rclone copyto C:\test：a.txt C:\test:f.txt    # Local file system at //?/C:/test：a.txt: error reading source root directory: directory not found
```

I'm guessing something is being handled incorrectly in the encoder (that causes `：` to be converted back to `:`) but I'm not proficient enough in Go to confirm and fix this.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.56.0
- os/version: Microsoft Windows 10 Home 2009 (64 bit)
- os/kernel: 10.0.19042.1110 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.16.5
- go/linking: dynamic
- go/tags: cmount
```

#### Which cloud storage system are you using? (e.g. Google Drive)
Local filesystem

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone copyto C:\test：a.txt C:\test:e.txt`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
> rclone -vv copyto C:\test：a.txt C:\test:e.txt
2021/08/05 13:33:13 DEBUG : rclone: Version "v1.56.0" starting with parameters ["rclone" "-vv" "copyto" "C:\\test：a.txt" "C:\\test:e.txt"]
2021/08/05 13:33:13 DEBUG : Creating backend with remote "C:\\test：a.txt"
2021/08/05 13:33:13 DEBUG : Using config file from "**redacted**\\rclone\\rclone.conf"
2021/08/05 13:33:13 DEBUG : fs cache: renaming cache item "C:\\test：a.txt" to be canonical "//?/C:/test：a.txt"
2021/08/05 13:33:13 DEBUG : Creating backend with remote "C:\\test:e.txt"
2021/08/05 13:33:13 DEBUG : fs cache: adding new entry for parent of "C:\\test:e.txt", "//?/C:/"
2021/08/05 13:33:13 Source doesn't exist or is a directory and destination is a file
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by jet082** [comment]
I am having the exact same issue, even with the flag ``local-no-unicode-normalization``

**Comment by albertony** [comment]
> I'm guessing something is being handled incorrectly in the encoder (that causes ： to be converted back to :)

The colon `:` character is included in the default encoding for the local backend on Windows, and according to https://rclone.org/overview/#restricted-characters:

> When a replacement character is found in a filename, this character will be escaped with the ‛ character to avoid ambiguous file names. (e.g. a file named ␀.txt would shown as ‛␀.txt)

(The escape character is `‛`, "SINGLE HIGH-REVERSED-9 QUOTATION MARK")

So if you try

```
rclone touch test：x.txt
```

You will see that it escapes the `：` into `‛：`

```
test‛：x.txt
```

> I am having the exact same issue, even with the flag `local-no-unicode-normalization`

Try with `--local-encoding None` instead, does that solve/workaround your issue?

Alternatively, to keep default encoding for the windows local backend (as shown by `rclone help flags encoding`, and documented at https://rclone.org/overview/#encoding) except for colons:
```
--local-encoding Slash,LtGt,DoubleQuote,Question,Asterisk,Pipe,BackSlash,Ctl,RightSpace,RightPeriod,InvalidUtf8,Dot
```
(removed the `Colon` entry from the default list)

Does this explain your observations, or do you still think there is an issue?

**Comment by alexkoay** [comment]
Ah, yes that seems to be the issue. Perhaps the (Local filesystem)[https://rclone.org/local/] file should provide a reference back to the overview, as it doesn't explain the escape character directly.
