### ISSUE TITLE
Add low level retries to swift

### ISSUE THREAD

**Issue by agutierrezdapda** [rclone/rclone#552]
Hi, I'm using rclone with OVH public cloud storage (swift). When I upload a big file (100 GB) and upload fail about 40%, the next upload command start with the transfer again at 0%. 

Please add support to resume uploads (and downloads) of big files.

Thanks.

Best regards

> What is your rclone version (eg output from `rclone -V`)
> v 1.30
> 
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
> Proxmox 3.4 (based in debian wheezy with redhat kernel) 64bits
> 
> Which cloud storage system are you using? (eg Google Drive)
> OVH public cloud (swift)
> 
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
> rclone sync /backups remote:backup-sbg/server_id
> 
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

2016/06/29 15:33:11 
Transferred:     621.244GBytes (25.607MByte/s)
Errors:                 1
Checks:               584
Transferred:            8
Elapsed time:   6h54m2.9s
Transferring:
-   **vzdump-qemu-102-2016_06_04-22_11_13.vma.lzo: 19% done**. avg: 7676.1, cur: 7569.7 kByte/s. ETA: 3h50m31s
-   vzdump-qemu-102-2016_06_18-22_14_31.vma.lzo: 28% done. avg: 11518.4, cur: 12059.9 kByte/s. ETA: 2h13m6s

2016/06/29 15:33:57 vzdump-qemu-102-2016_06_04-22_11_13.vma.lzo: Failed to copy: Put https://storage.sbg1.cloud.ovh.net/v1/AUTH_2f4c00ecc6e0241f983ccc13f56f9c2c/backup-sbg_segments/server_id/vzdump-qemu-102-2016_06_04-22_11_13.vma.lzo/1467203824.95980929/133672889927/00000004: write tcp 32.17.181.131:57366->5.135.208.193:443: write: broken pipe

2016/06/29 16:59:36 Local file system at /backups: Building file list
2016/06/29 16:59:36 Swift container backup-sbg path server_id/: Building file list
2016/06/29 16:59:40 Waiting for deletions to finish
2016/06/29 16:59:46 Swift container backup-sbg path server_id/: Waiting for checks to finish
2016/06/29 16:59:46 Swift container backup-sbg path server_id/: Waiting for transfers to finish
2016/06/29 17:00:35 
Transferred:       1.503GBytes (25.207MByte/s)
Errors:                 0
Checks:               196
Transferred:            0
Elapsed time:        1m1s
Transferring:
-   **vzdump-qemu-102-2016_06_04-22_11_13.vma.lzo:  0% done**. avg: 16667.3, cur: 13925.4 kByte/s. ETA: 2h35m13s

**Comment by ncw** [comment]
Thanks for the report.

Resume is tricky..

However what I can and should do is put low level retries in for swift.  This would stop the upload failing in the first place by retrying the segments multiple times.

**Comment by agutierrezdapda** [comment]
Other bug related with this is if upload failed, the next upload not delete the older uploaded files.

**Comment by Hassaan68** [comment]
i am facing same issue while uploading big files from android app to ovh server. is ovh supports pause/resume while uploading now ?

**Comment by ncw** [comment]
@Hassaan68 
Low level retries were added to the swift backend here: e84790ef7976440974cb4c4f01e4712854346dcc

This unfortunately doesn't allow retries of chunks in large files though.

**Comment by Hassaan68** [comment]
@ncw  so i cannot pause/resume upload from my apps?

**Comment by ncw** [comment]
> so i cannot pause/resume upload from my apps?

You can stop and start rclone and it will resume.  However if it was half way through a big file it will upload that big file again from the start.

The issue for resume uploads is here https://github.com/rclone/rclone/issues/87

I think I will close this one since low level retries did get added to swift.
