### ISSUE TITLE
`rclone check` does not consider empty directories (at least for Mega)

### ISSUE THREAD

**Issue by vmm86** [rclone/rclone#5523]
#### What is the problem you are having with rclone?

I've just started using `rclone` with my Mega cloud storage account, so I'm not sure whether it happens with other cloud storages. At least for Mega it seems that `rclone check` command  **does not consider empty directories on both sides** (neither on source nor on destination side).

Maybe that is actually the feature rather than a bug, but I believe that sometimes it's an unexpected behavior anyway. In my particular case I'm interested not only in files, but in any path including empty folders too, to be absolutely identical on destination side without any differences. So everything should be taken into account both for checking and for sync operations as well. Maybe not by default, but using some specific command line flag in case you need to use it.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.56.0
- os/version: raspbian 10.10
- os/kernel: 5.10.17-v7l+ (armv7l)
- os/type: linux
- os/arch: arm
- go/version: go1.16.5
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Raspbian GNU/Linux 10 (buster), 32 bit

#### Which cloud storage system are you using? (e.g. Google Drive)

Mega

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

To test such a behavior I've run the same command two times: `rclone check -vv /media/Share/Movies Mega:/Share/Movies`.

Firstly I've run this command, having `test_` empty folder in my source folder and `_test` empty folder on my destination folder (all the other folders/files on both sides were the same). The result stated that everything was in sync with no differences, that actually wasn's true.

Secondly I've run the same command having the same test folders on both sides with the empty `test.txt` file inside on both sides as well. And this time I got both files as the actual diff in between.

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

The first run (with empty test folders on both sides):

```
2021/08/10 19:32:38 DEBUG : rclone: Version "v1.56.0" starting with parameters ["rclone" "check" "-vv" "/media/Share/Movies" "Mega:/Share/Movies"]
2021/08/10 19:32:38 DEBUG : Creating backend with remote "/media/Share/Movies"
2021/08/10 19:32:38 DEBUG : Using config file from "/home/pi/.config/rclone/rclone.conf"
2021/08/10 19:32:38 DEBUG : Creating backend with remote "Mega:/Share/Movies"
2021/08/10 19:33:03 DEBUG : *go-mega*: Waiting for events to be finished for 5s
2021/08/10 19:33:03 DEBUG : *go-mega*: Signalling events received
2021/08/10 19:33:03 DEBUG : *go-mega*: Events received
2021/08/10 19:33:03 DEBUG : fs cache: renaming cache item "Mega:/Share/Movies" to be canonical "Mega:/Share/Movies"
2021/08/10 19:33:03 ERROR : No common hash found - not using a hash for checks
2021/08/10 19:33:03 DEBUG : mega root 'Share/Movies': Waiting for checks to finish
... for all of the same paths on both sides: OK - could not check hash
2021/08/10 19:33:03 NOTICE: mega root 'Share/Movies': 0 differences found
2021/08/10 19:33:03 NOTICE: mega root 'Share/Movies': 14 hashes could not be checked
2021/08/10 19:33:03 NOTICE: mega root 'Share/Movies': 14 matching files
2021/08/10 19:33:03 INFO  : 
Transferred:              0 / 0 Byte, -, 0 Byte/s, ETA -
Checks:                14 / 14, 100%
Elapsed time:        25.0s

2021/08/10 19:33:03 DEBUG : 9 go routines active
```

The second run (with non-empty test folders on both sides):

```
2021/08/10 19:26:17 DEBUG : rclone: Version "v1.56.0" starting with parameters ["rclone" "check" "-vv" "/media/Share/Movies" "Mega:/Share/Movies"]
2021/08/10 19:26:17 DEBUG : Creating backend with remote "/media/Share/Movies"
2021/08/10 19:26:17 DEBUG : Using config file from "/home/pi/.config/rclone/rclone.conf"
2021/08/10 19:26:17 DEBUG : Creating backend with remote "Mega:/Share/Movies"
2021/08/10 19:26:46 DEBUG : *go-mega*: Waiting for events to be finished for 5s
2021/08/10 19:26:46 DEBUG : *go-mega*: Signalling events received
2021/08/10 19:26:46 DEBUG : *go-mega*: Events received
2021/08/10 19:26:46 DEBUG : fs cache: renaming cache item "Mega:/Share/Movies" to be canonical "Mega:/Share/Movies"
2021/08/10 19:26:46 ERROR : No common hash found - not using a hash for checks
2021/08/10 19:26:46 DEBUG : mega root 'Share/Movies': Waiting for checks to finish
2021/08/10 19:26:46 ERROR : _test/test.txt: File not in Local file system at /media/Share/Movies
2021/08/10 19:26:46 ERROR : test_/test.txt: File not in mega root 'Share/Movies'
... for all of the same paths on both sides: OK - could not check hash
2021/08/10 19:26:46 NOTICE: mega root 'Share/Movies': 1 files missing
2021/08/10 19:26:46 NOTICE: Local file system at /media/Share/Movies: 1 files missing
2021/08/10 19:26:46 NOTICE: mega root 'Share/Movies': 2 differences found
2021/08/10 19:26:46 NOTICE: mega root 'Share/Movies': 2 errors while checking
2021/08/10 19:26:46 NOTICE: mega root 'Share/Movies': 14 hashes could not be checked
2021/08/10 19:26:46 NOTICE: mega root 'Share/Movies': 14 matching files
2021/08/10 19:26:46 INFO  : 
Transferred:              0 / 0 Byte, -, 0 Byte/s, ETA -
Errors:                 2 (retrying may help)
Checks:                14 / 14, 100%
Elapsed time:        29.3s

2021/08/10 19:26:46 DEBUG : 9 go routines active
2021/08/10 19:26:46 Failed to check with 2 errors: last error was: 2 differences found
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
`rclone check` only checks files

From: https://rclone.org/commands/rclone_check/

> Checks the files in the source and destination match. It compares sizes and hashes (MD5 or SHA1) and logs a report of files which don't match. It doesn't alter the source or destination.

However if you want to check the directory paths too then you could do something like use `rclone lsf -R` to list the source and the dest, sort the files then `diff` them.

The other alternative would be to create a file in each empty directory - say `.empty` or something like that. This is what `git` users do (`git` has the same feature!).

**Comment by vmm86** [comment]
@ncw Thank you for a quick reply and assistance!

Yes, I agree that generally it would be more reasonable to rely only on files and to have such standard "technical" files to indicate empty folders automatically.

It seems that there's no need to track empty directories specifically in 'rclone check' and possibly in other rclone commands as well, so I close my issue myself.
