### ISSUE TITLE
qnap load error

### ISSUE THREAD

**Issue by nu1ee** [rclone/rclone#5527]
webdav root '': Statfs failed: about call failed: 404 Not Found
![image](https://user-images.githubusercontent.com/5696517/129132763-c9123d7b-8d30-40a2-a7f5-228120451d5d.png)

rclone mount nunas:/ o: --cache-dir D:\Temp --allow-other --vfs-cache-mode writes --allow-non-empty

**Comment by ncw** [comment]
What does `rclone lsf -vv nunas:/` show?

**Comment by ivandeex** [comment]
2 months without activity here
