### ISSUE TITLE
Google drive - sync folder from the business drive to another business drive in a different domain

### ISSUE THREAD

**Issue by AronWaterAron** [rclone/rclone#5528]
The question is mainly about google drive. 
Does the command line support sync folder from the business drive to another business drive in a different domain?

let say the source folder in account A is Folder A. The target folder in account B is Folder B.

Without rclone. I will do it in this way, I grant account A access to a folder in the shared drive created by account B. Let this folder be Folder C.

Each time period (maybe 1 day) I use python to capture tree structure in Account A. I use the tree to copy Folder A to Folder B. And then copy Folder B to Folder C.

Could rclone do this any better?

**Comment by ncw** [comment]
You'll need to set up a remote for accountA and a remote for accountB

If you don't want to download and upload the data then you'll want to use 

      --drive-server-side-across-configs      Allow server-side operations (e.g. copy) to work across different drive configs.

This may require extra permissions - the **destination** user needs to be able to read from the **source**.

I think I've seen this question on the forum too - that's a better place for it, so I'm going to close this now.

**Comment by AronWaterAron** [comment]
> You'll need to set up a remote for accountA and a remote for accountB
> 
> If you don't want to download and upload the data then you'll want to use
> 
> ```
>   --drive-server-side-across-configs      Allow server-side operations (e.g. copy) to work across different drive configs.
> ```
> 
> This may require extra permissions - the **destination** user needs to be able to read from the **source**.
> 
> I think I've seen this question on the forum too - that's a better place for it, so I'm going to close this now.

but the account would never have read or write access to other accounts.......

**Comment by ncw** [comment]
> but the account would never have read or write access to other accounts......

If the destination can't read from the source then you can't use `--drive-server-side-across-configs`. This means that rclone will download and upload which may be OK for you.

If you don't want that, then you'll have to share the files you need to copy
