### ISSUE TITLE
[Regression] - Http serve with version 1.56.0

### ISSUE THREAD

**Issue by ilteoood** [rclone/rclone#5532]
#### What is the problem you are having with rclone?

Starting with version 1.56.0 I can't export http server as I did before

#### What is your rclone version (output from `rclone version`)

1.56.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Docker 64 bit, docker x86_64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)

Local storage

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

docker run --rm rclone/rclone:1.56.0 serve http / --addr :8888 --baseurl "rclone" -vv

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

2021/08/14 13:13:53 DEBUG : rclone: Version "v1.56.0" starting with parameters ["rclone" "serve" "http" "/" "--addr" ":8888" "--baseurl" "rclone" "-vv"]
2021/08/14 13:13:53 DEBUG : Creating backend with remote "/"
2021/08/14 13:13:53 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
2021/08/14 13:13:53 INFO  : Local file system at /: poll-interval is not supported by this remote
2021/08/14 13:13:53 INFO  : 
Transferred:   	          0 / 0 Byte, -, 0 Byte/s, ETA -
Elapsed time:         0.0s

2021/08/14 13:13:53 DEBUG : 3 go routines active

This is the result with version 1.55.1

ilteoood@pop-os:~$ docker run --rm rclone/rclone:1.55.1 serve http / --addr :8888 --baseurl "rclone" -vv
2021/08/14 13:16:35 NOTICE: Config file "/config/rclone/rclone.conf" not found - using defaults
2021/08/14 13:16:35 DEBUG : rclone: Version "v1.55.1" starting with parameters ["rclone" "serve" "http" "/" "--addr" ":8888" "--baseurl" "rclone" "-vv"]
2021/08/14 13:16:35 DEBUG : Creating backend with remote "/"
2021/08/14 13:16:35 INFO  : Local file system at /: poll-interval is not supported by this remote
2021/08/14 13:16:35 NOTICE: Local file system at /: Serving on http://[::]:8888/rclone/

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment]
I can reproduce this. But seems to work on current master, though not printing the "Serving on.." message. Can you try latest [beta](https://beta.rclone.org/)?

**Comment by albertony** [comment]
Found duplicate issue: https://github.com/rclone/rclone/issues/5467
Fixed here: https://github.com/rclone/rclone/pull/5481

Which means it will probably be included in next release, and you'll have to use a previous version or a beta until then.

Closing this issue.

**Comment by ivandeex** [comment]
@ilteoood 
The fix is scheduled for 1.56.1 which is out in  a week or two.

**Comment by ilteoood** [comment]
Thank you so much for your support guys!
