### ISSUE TITLE
cmd/version: add support for openbsd/386

### ISSUE THREAD

**Issue by ivandeex** [rclone/rclone#5537]
#### The associated forum post URL from `https://forum.rclone.org`

N/A

#### What is your current rclone version (output from `rclone version`)?

master branch

#### What problem are you are trying to solve?

`rclone version` is a stub for `openbsd/386`.

When I merged https://github.com/rclone/rclone/pull/5402 I thought that upstream issue https://github.com/tklauser/go-sysconf/issues/21 depends on the _core golang_ schedule.
Now that @tklauser closed it in less than a week I see that in fact https://github.com/tklauser/go-sysconf depends on fast-moving https://pkg.go.dev/golang.org/x/sys?tab=versions

#### How do you think rclone should be changed to solve that?

- [x] Submit pull request for [shirou/gopsutil](https://github.com/shirou/gopsutil) to upgrade to [tklauser/go-sysconf v0.3.8](https://github.com/tklauser/go-sysconf/releases/tag/v0.3.8)
- [ ] Submit pull request for [rclone](https://github.com/rclone/rclone) to upgrade [gopsutil](https://github.com/shirou/gopsutil/releases) when `v3.21.8` is out, then remove the build hack

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by tklauser** [comment]
> #### The associated forum post URL from `https://forum.rclone.org`
> 
> N/A
> #### What is your current rclone version (output from `rclone version`)?
> 
> master branch
> #### What problem are you are trying to solve?
> 
> `rclone version` is a stub for `openbsd/386`.
> 
> When I merged #5402 I thought that upstream issue [tklauser/go-sysconf#21](https://github.com/tklauser/go-sysconf/issues/21) depends on the _core golang_ schedule.
> Now that @tklauser closed it in less than a week I see that in fact https://github.com/tklauser/go-sysconf depends on fast-moving https://pkg.go.dev/golang.org/x/sys?tab=versions

FWIW, during the Go development freeze (see https://github.com/golang/go/wiki/Go-Release-Cycle for details), `x/sys` is usually frozen as well (i.e. id depends on the core Go development schedule) because is vendored into `cmd/vendor`. Thus the CL above was blocked from being merged for a week. We were lucky that the development cycle opened just today 😄.

> #### How do you think rclone should be changed to solve that?
> 
>     1. Submit pull request for https://github.com/shirou/gopsutil to upgrade to https://github.com/tklauser/go-sysconf/releases/tag/v0.3.8

I've submitted https://github.com/shirou/gopsutil/pull/1117 a few minutes ago bumping go-sysconf in gopsutil.

**Comment by ivandeex** [comment]
@tklauser Got you. Thanks a lot.

**Comment by tklauser** [comment]
@ivandeex FYI, [gopsutil v3.21.8](https://github.com/shirou/gopsutil/releases/tag/v3.21.8) was released some hours ago and should contain the bumped go-sysconf (https://github.com/shirou/gopsutil/pull/1117), hopefully allowing this issue to be fixed.
