### ISSUE TITLE
Ability to configure --drive-use-trash as the default mode

### ISSUE THREAD

**Issue by memeplex** [rclone/rclone#554]
Currently I'm using a bash alias, but I'm still a bit paranoid (having lost some files after a no use-trash sync). I believe rclone conf is limited to configure the stores.

**Comment by ncw** [comment]
I'd like to be able to configure flags in the config file in general which I've put in #643

**Comment by ncw** [comment]
As part of #616 you can now set this in the environment which is a step in the right direction, eg

    export RCLONE_DRIVE_USE_TRASH=true

for bash...

**Comment by animosity22** [comment]
As far as I can understand, this looks to be done now and in rclone so I'm going to close this out.
