### ISSUE TITLE
Enhance rclone cleanup to work around Box "quirks"

### ISSUE THREAD

**Issue by jpeshkin** [rclone/rclone#5545]
https://forum.rclone.org/t/box-bug-blocks-rclone-cleanup/25951/9

rclone 1.56.0

If there is a large number of file in Box's trash, particularly if the account the rclone remote is using has deleted files from shares folders belonging to another account, 2 Box bugs prevent cleanup from working...

1) The GET /2.0/folders/trash/items API hangs forever
2) Attempts to delete items in the remote user's trash that are actually owned by other accounts will fail

To fix this, 3 changes to cleanup behavior should help

1) Fetch the trash with ?usemarker=true

2) Attempt to delete each item returned in that first fetch but continue if the delete fails

3) At the end of the page, use the marker value to fetch the next page, (instead of offset)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Can you have a go with this and see if it solves your problem?

[v1.57.0-beta.5630.b75d324ee.fix-5545-box-cleanup](https://beta.rclone.org/branch/fix-5545-box-cleanup/v1.57.0-beta.5630.b75d324ee.fix-5545-box-cleanup/) on branch [fix-5545-box-cleanup](https://github.com/rclone/rclone/tree/fix-5545-box-cleanup) (uploaded in 15-30 mins)

This does

- use marker paging for directory listing and cleanup
- logs errors on deletion on cleanup and continues
- returns an error with total number of deletion failures at the end of cleanup

**Comment by jpeshkin** [comment]
Hi Nick,

It generally runs OK, but Box seems to intermittently Error-out with Internal Server Errors with the limit=1000.  If I drop the limit to 100 even if I ask for the extra owned_by field, I don't see the Internal Server Error from Box.   As it takes about 7 seconds to respond even with a limit of 100, that probably doesn't drop efficiency by much.

"https://api.box.com//2.0/folders/trash/items?fields=type&fields=id&fields=owned_by&limit=100&usemarker=true"

The second observation is the DELETE operations that result in a permission error take quite a while to slog through.   I'm not sure how much more feature bloat we should add to rclone to work around Box bugs, but we could predict which ones to skip very quickly by using the owned_by fields if cleanup had a way to specify --box-owned-by ncw@rclone.org or some such option.

-Joel

**Comment by ncw** [comment]
> It generally runs OK, but Box seems to intermittently Error-out with Internal Server Errors with the limit=1000.

:-(

> If I drop the limit to 100 even if I ask for the extra owned_by field, I don't see the Internal Server Error from Box.

Do we need to make this configurable? Or just use 100 by default in cleanup?

> As it takes about 7 seconds to respond even with a limit of 100, that probably doesn't drop efficiency by much.

!!
 
> "https://api.box.com//2.0/folders/trash/items?fields=type&fields=id&fields=owned_by&limit=100&usemarker=true"
> 
> The second observation is the DELETE operations that result in a permission error take quite a while to slog through. I'm not sure how much more feature bloat we should add to rclone to work around Box bugs, but we could predict which ones to skip very quickly by using the owned_by fields if cleanup had a way to specify --box-owned-by [ncw@rclone.org](mailto:ncw@rclone.org) or some such option.

Adding a parameter for use in cleanup would be easy enough. Is it useful for general listings too?

Another alternative would be to run the DELETE operations in parallel - no reason not to - that would help a lot.

What do you think?

**Comment by jpeshkin** [comment]
Making limit configurable always sounds like a good idea.  The other thing I noticed is that, once I get an Internal Server Error once, Box seems to rate limit the token for a while so it doesn't recover.

In the case of cleanup, requesting the owner and filtering it makes sense.  I could see some other operations (listings, downloads, purge, etc.. ) where it makes sense.   I think it generally helps when Box is the source.

**Comment by ncw** [comment]
OK have a go with this!

[v1.57.0-beta.5648.ecb0d9328.fix-5545-box-cleanup](https://beta.rclone.org/branch/fix-5545-box-cleanup/v1.57.0-beta.5648.ecb0d9328.fix-5545-box-cleanup/) on branch [fix-5545-box-cleanup](https://github.com/rclone/rclone/tree/fix-5545-box-cleanup) (uploaded in 15-30 mins)

It has these patches

- add `--box-owned-by` to only show items owned by the login passed
- delete items in parallel in cleanup using `--checkers` threads
- factor directory listing and cleanup listing into one function
- add `--box-list-chunk` to control listing chunk size
- when doing cleanup delete as much as possible
- make listings of heavily used directories more reliable

**Comment by jpeshkin** [comment]
Trying to download the test builds.  The webserver claims the files are many megabytes but closes the transfer at 0 bytes.   (Seen from multiple networks and web clients)

**Comment by ncw** [comment]
Ah, disk is full on the download machine. Will delete some stuff - should be OK in a couple of hours!

**Comment by jpeshkin** [comment]
It looks like the new version is doing exactly what it is supposed to be doing, but it hits Box hard enough that Box gets jammed up and may take a day or two to recover.  I've seen Box get into the state where it is still working on things it already acknowledged before.  In this case, I get an internal server error from Box even when just asking for a few entries.

So, I think the set of changes is good but we probably should have the --checkers default to 1 on box's cleanup if that is do-able.

**Comment by jpeshkin** [comment]
Let's leave the checkers mechanism enabled.   Box is being incredibly buggy.

This morning, I had limit set to 10 and checkers at 2  After about 6 DELETEs, I got this...

2021/08/23 04:49:02 ERROR : box root '': failed to delete trash item "2019-06" ("78233911438"): Error "operation_blocked_temporary" (409): The operation is blocked by another on-going operation

and the session then hung and I unfortunately did not keep the logs, after I restarted (with limit=10) I got the internal server errors again.

**Comment by ncw** [comment]
I found the [API help](https://developer.box.com/guides/api-calls/permissions-and-errors/common-errors/) for that error

Error | operation_blocked_temporary
-- | --
Message | The operation is blocked by another ongoing operation
Solution | This error is returned when trying to access a folder that is blocked by another folder operation, such as a move or copy. Try again at a later interval.

So it looks like that error is designed to be retried...

This code retries the delete if it gets that error. In my tests it seemed to work quite well.

[v1.57.0-beta.5649.c751d93e9.fix-5545-box-cleanup](https://beta.rclone.org/branch/fix-5545-box-cleanup/v1.57.0-beta.5649.c751d93e9.fix-5545-box-cleanup/) on branch [fix-5545-box-cleanup](https://github.com/rclone/rclone/tree/fix-5545-box-cleanup) (uploaded in 15-30 mins)
