### ISSUE TITLE
Multiple choice config option default handling

### ISSUE THREAD

**Issue by albertony** [rclone/rclone#5549]
#### What is the problem you are having with rclone?

For exclusive multiple choice options, handling of default value is not working according to description:

```
Authentication type
Enter a string value. Press Enter for the default ("standard").
Choose a number from below, or type in an existing value
 1 / Standard authentication - use this if you're a normal Jottacloud user.
   \ "standard"
 2 / Legacy authentication - this is only required for certain whitelabel versions of Jottacloud and not recommended for normal users.
   \ "legacy"
 3 / Telia Cloud authentication - use this if you are using Telia Cloud.
   \ "telia"
config_type>
config_type>
config_type>
config_type>
```

In contrast to what is indicated, pressing enter will not give the default - you are required to enter one of the three listed values.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Well spotted. Should be easy to fix hopefully!

**Comment by albertony** [comment]
Yes, I will look into it.
