### ISSUE TITLE
This should be an ERROR-> Failed to create file system for “”: didn’t find section in config file

### ISSUE THREAD

**Issue by asdffdsa6131** [rclone/rclone#5560]
hello and thanks,

i have a python script that scans rclone debug log for problems.
there are some failtures that should have the text `ERROR` in it.

https://forum.rclone.org/t/this-should-be-an-error-failed-to-create-file-system-for-didnt-find-section-in-config-file/22842

this
`2021/03/15 12:17:06 Failed to create file system for ": didn't find section in config file`
should be
`2021/08/30 16:25:34 ERROR : Failed to create file system for ": didn't find section in config file"`

this
`2021/08/24 10:37:34 Failed to create file system for ""`
should be
`2021/08/24 10:37:34 ERROR : Failed to create file system for ""`

**Comment by ncw** [comment]
Rclone should have exited with a non-zero exit code in those cases.

```
$ rclone lsf akdflaskdfj:
2021/08/31 13:13:32 Failed to create file system for "akdflaskdfj:": didn't find section in config file
$ echo $?
1
```

which you should be checking in your script too...

**Comment by asdffdsa6131** [comment]
hi,

non-zero exit code is not the informative when having to scroll thru a 1MB file, trying to find a needle in the haystack.

strange that some errors are ERROR and some are not.

my script will take a 1MB log and strip out most of the it and send me a summary email.
each time i find such an error that is not labeled as ERROR, i have to edit my python script to catch it.
so far i have only found two of them so this not a major problem...
i have the same issue with 7zip, fastcopy, VSS

this is my second time pointing out inconsistencies with the rclone debug log.
i understand that this is not a concern for rclone and will not raise it again.

thanks much,

**Comment by ncw** [comment]
Rclone could exit in lots of ways which would produce a non-zero error code, but no ERROR message, examples include

- running out of memory
- killed by the OS/another user
- a program logic bug causing a backtrace

So it isn't safe to assume that rclone will always write an ERROR log when things go wrong.

This line is responsible for the final error printing - it would be easy enough to make it print an ERROR. However if rclone has got to this line it will be exiting with a non-zero exit code

https://github.com/rclone/rclone/blob/f1f923a986ca193f13ec55dfef31c92f66dd6369/cmd/cmd.go#L328

**Comment by asdffdsa6131** [comment]
i agree and that is why i do no rely only on 'ERROR' text in the log file and i do use exit code.

fwiw, it is not about the final error text, but the individual error(s) in the log.
as i have mentioned a few times in the forum, i have a python script that orchestrates rclone, 7zip, fastcopy, swithmail, veeam and VSS.
each log has it quirks and i work around them.

thanks,

**Comment by animosity22** [comment]
Is this still outstanding as it looks answered or can we close it out?

**Comment by asdffdsazqqq** [comment]
i asked the question, ncw answered, i am ok to close it out.
thanks
