### ISSUE TITLE
Add functionality to stop an operation using the _group parameter

### ISSUE THREAD

**Issue by matscottseah** [rclone/rclone#5561]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/no-way-to-stop-a-group/26210

#### What is your current rclone version (output from `rclone version`)?
v1.56.0

#### What problem are you are trying to solve?
RClone does not have a way to stop a group. You can run the "job/stop" command can stop a specific job but RClone is lacking similar functionality to stop a group. By "group", I am referring to https://rclone.org/rc/#assigning-operations-to-groups-with-group-value. This could be useful for long running operations that need to be halted and returned to at a later point. 

#### How do you think rclone should be changed to solve that?
Add functionality to stop a group. The method would look something like "core/stop" and accept a parameter for the "_group" identifier. It might look similar to https://github.com/rclone/rclone/blob/master/fs/rc/jobs/job.go#L393-L408.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
That sounds like a nice idea, and not too hard to implement.

This should probably be a new rc call `job/stopgroup` which takes the standard `_group` parameter but no other parameters.

Do you want to have a go at this @matscottseah ?

**Comment by matscottseah** [comment]
@ncw sure I'll give it a shot. After adding the functionality, how do I update the documentation?

**Comment by ncw** [comment]
The docs are here: https://github.com/rclone/rclone/blob/master/docs/content/rc.md

The actual docs for the rc commands are auto generated from the help in the source code.

Do update rc.md from the source, build rclone then run `make rcdocs`. It isn't essential you do this and it will get done as part of a release anyway.
