### ISSUE TITLE
webdav does not support http://xxx.xxx.com:5006

### ISSUE THREAD

**Issue by alexallen1** [rclone/rclone#5569]
Hello, thank you guys for making rclone

Found a issue:
Rclone  v1.56
failed to mounted the following paths
http://xxx.xxx.net:5005

If change to
http://34.56.45.34:5005

The mount is successful
(example:Synology NAS webdav server)

**Comment by ncw** [comment]
What does `host xxx.xxx.net` say? how about `dig xxx.xxx.net any`?

Can you show the error message with the log?

**Comment by animosity22** [comment]
Stale. Closing.
