### ISSUE TITLE
Why not use copyBuffer? 

### ISSUE THREAD

**Issue by zhucan** [rclone/rclone#5572]
https://github.com/rclone/rclone/blob/aa0ceb6c5c66cfeb0c90f024cc3f66f6d69be1cd/backend/local/local.go#L1176

**Comment by ncw** [comment]
`io.Copy` uses a 32k buffer by default I think

https://cs.opensource.google/go/go/+/refs/tags/go1.17:src/io/io.go;l=412

I think that is probably big enough.

Do you think it makes a difference?

**Comment by zhucan** [comment]
If transfer big data, 32k is not enough,  is it needed to set it configurable?

**Comment by ncw** [comment]
Can you do a benchmark and see if it is needed?

**Comment by zhucan** [comment]
My test case:

1. iosize = 1M
![image](https://user-images.githubusercontent.com/13997135/132274753-e82d02e4-9ed9-4318-a0a1-13d55e99cc45.png)

2. iosize = 32k
![image](https://user-images.githubusercontent.com/13997135/132274794-72ee5b1b-24ae-459b-9e0e-13694543ce57.png)

less than 10s

@ncw

**Comment by ncw** [comment]
Hmm, so it make a small difference (12%) in elapsed time.

But the transfer speed is very different 101.836 MiByte/s vs 45.237 MiByte/s which I don't understand - do you?

**Comment by ncw** [comment]
I suspect this might be calculating the checksum @zhucan can you try with `--ignore-checksum`?

**Comment by zhucan** [comment]
only suitable for big file. @ncw @ivandeex

**Comment by ivandeex** [comment]
> only suitable for big file. @ncw @ivandeex 

@ncw
Did you understand it or just :O like me?

**Comment by animosity22** [comment]
Are there any more questions on this item? Can it be closed out?

**Comment by zhucan** [comment]
CopyBuffer let’s you allocate your own buffer. It is otherwise the same as Copy. If you look at Copy, it just calls CopyBuffer.

CopyBuffer let's you choose your own buffer size. io.Copy by default uses a 32K buffer. If you know your copy will be large, a larger buffer may be more performant. In addition to allowing the caller to control the size of the buffer, a caller can use a single buffer for multiple copy operations.

https://github.com/filecoin-project/lotus/pull/5177/files
