### ISSUE TITLE
vfs cache: failed to download: vfs reader: failed to write to cache file: open file failed:

### ISSUE THREAD

**Issue by nathanshearer** [rclone/rclone#5573]
I am having an issue where a file is being access many times, so often that it is triggering `googleapi: Error 403: The download quota for this file has been exceeded.`

As a result, a larger dataset becomes unusable until that quota has expired. I have enabled vfs caching and set aggressively large values in an attempt to minimize all access to google and prefer local cached data. I even limited by bandwidh to only 4MB to keep my usage below 350GB per day (well under 750GB per day).

rclone \
        --daemon \
        --log-file=/var/log/rclone.googledrive.log \
        mount \
        googledrive:/ \
        --bwlimit 4000000 \
        --drive-impersonate mail@example.com \
        --drive-use-trash=false \
        --fast-list \
        --vfs-cache-mode full \
        --vfs-cache-max-size 48G \
        --vfs-cache-max-age 96h \
        --vfs-write-back 48h \
        --allow-other \
        --umask 0 \
        /mnt/googledrive

Since the cache remote has been removed from rclone, is there an option/mechanism to tell rclone to stop hammering google for recently used data that should be kept in the cache. It would be great if I could give this thing a large cache (like 1TB) to limit the access to google as much as possible.

```
2021/09/03 08:09:58 ERROR : 000/000/000/532: vfs cache: failed to download: vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:58 ERROR : 000/000/000/532: vfs cache: failed to download: vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:58 ERROR : 000/000/008/516: vfs cache: failed to download: vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:58 ERROR : 000/000/000/532: vfs cache: failed to download: vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:59 ERROR : 000/000/008/516: vfs cache: failed to download: vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:59 ERROR : 000/000/000/532: vfs cache: failed to download: vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:59 ERROR : 000/000/000/532: vfs cache: failed to download: vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:59 ERROR : 000/000/008/516: vfs cache: failed to download: vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:59 ERROR : 000/000/000/532: vfs cache: failed to download: vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:59 ERROR : 000/000/000/532: vfs cache: too many errors 11/10: last error: vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:59 ERROR : 000/000/000/532: vfs cache: failed to kick waiters: vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:59 ERROR : 000/000/000/532: vfs cache: failed to _ensure cache vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:59 ERROR : 000/000/008/516: vfs cache: failed to download: vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:59 ERROR : 000/000/000/532: vfs cache: failed to download: vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:59 ERROR : 000/000/000/532: vfs cache: too many errors 12/10: last error: vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:59 ERROR : 000/000/000/532: vfs cache: failed to kick waiters: vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2021/09/03 08:09:59 ERROR : 000/000/000/532: vfs cache: failed to _ensure cache vfs reader: failed to write to cache file: open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> I am having an issue where a file is being access many times, so often that it is triggering `googleapi: Error 403: The download quota for this file has been exceeded.`

Is rclone caching this file or not?

> As a result, a larger dataset becomes unusable until that quota has expired. I have enabled vfs caching and set aggressively large values in an attempt to minimize all access to google and prefer local cached data. I even limited by bandwidh to only 4MB to keep my usage below 350GB per day (well under 750GB per day).
> 
> rclone
> --daemon
> --log-file=/var/log/rclone.googledrive.log
> mount
> googledrive:/
> --bwlimit 4000000

This is a bwlimit of 4000000kByte/s - you probably want `--bwlimit 4M` here.

> --drive-impersonate [mail@example.com](mailto:mail@example.com)
> --drive-use-trash=false
> --fast-list
> --vfs-cache-mode full
> --vfs-cache-max-size 48G

Change 48G to 1T if you want a TB of cache.

> --vfs-cache-max-age 96h
> --vfs-write-back 48h

This means that rclone won't write back modified files to the google drive for 48h which seems like a very long time to me.

> --allow-other
> --umask 0
> /mnt/googledrive
> 
> Since the cache remote has been removed from rclone,

It is still there if you want to use it. It isn't maintained though...

> is there an option/mechanism to tell rclone to stop hammering google for recently used data that should be kept in the cache. It would be great if I could give this thing a large cache (like 1TB) to limit the access to google as much as possible.

The VFS cache should be keeping recently used files on disk for you just fine.

Can you tell me more about the file in question and how it is accessed? Is it very big? Maybe each access is only downloading a small part of the file so there are lots and lots of accesses? If so then you could precache the file (just `cat` it to /dev/null or something) to get it on the disk.

I need more info from you about what you are doing and your access patterns to know exactly what is happening.

Thanks

**Comment by nathanshearer** [comment]
Thanks for the quick response. I will modify my command to use `--bwlimit 4M` and verify that the file is present in the `/root/.cache/rclone` directory.

So, technically, what I have is a collection of 8MB files, that when concatenated together form a single large (sparse) block device, which has a normal filesystem on it (specifically ZFS). The intermediate layer simply translates the files into a single block device in such a way that file handles are closed allowing rclone to sync closed and unused blocks to my google drive. The entire file set is sparse, such that 8MiB files of 0x00 do not exist on disk. This configuration also allows me to enable compression in zfs and deduplication in zfs, and detect read/write/io errors -- of which there are many due to transient network failures and throttling etc.

I spoke to a google support agent a while ago regarding a >1TB virtual machine I had backed up and uploaded, and apparently they calculate your quota based on the total size of the file*hits, so reading 1 byte of a 1TB file will immediately consume the 750GB quota -- which is the problem I had previously encountered. They specifically say that an upload/download that is started will complete, allowing you to exceeds the quota to maintain file consistency, but then all subsequent requests will be over-quota until it resets.

In this bug report, I started a zfs resilver and scrub on 3 of these sparse loop devices, which is migrating the data from one loop device to another, and that seems to be hammering a few of those 8MB files (probably metadata blocks near the root of the zfs filesystem), and google is limiting my access to those files. Then rclone produces IO errors and that kills zfs and faults the virtual loop device.

I enabled some extreme caching in an attempt to limit the access to google and effectively only sync old data, or data that is write-mostly read-rarely. But I am guessing that rclone is syncing the same block file repeatedly to google to flush the cache.

I am experimenting with dm-cache to work aroudn this. My test setup will be ZFS on dm-cache on sparse-loop-device on rclone on google drive. It's a crazy setup, but the zfs layer is giving me good features like a real filesystem with compression, deduplication, redundancy, and even local caching to an ssd.

**Comment by ncw** [comment]
I think this scheme should work OK with the settings you have. `--vfs-write-back` is what protects you from lots of writes of the same file so it shouldn't be hammering the same file over and over again.... Can you see this in the logs?

I did write a mount mode for rclone which created a sparse block backed file for mounting as a loop device, as, like you, I recognized the utility of having a proper file system. I didn't finish it and I crashed my machine a lot of times while developing it!

How do you set up a sparse loop device on rclone mount? I'd like to have a play with it.

**Comment by nathanshearer** [comment]
It's been a long road in an attempt to stack a sparse block device on top of rclone. My first attempt was just a simple collection of loop devices that I would then map together into a single block device with dmsetup (device mapper). However both the loop device and device mapper consume memory for each structure. So once I started creating thousands of loop devices, the kernel would run out of memory and begin to freeze the whole system. Creating fewer and larger files worked, but the write amplification made it impossible to scale.

What finally allowed me to get it working is https://github.com/libguestfs/nbdkit

It has plugin support that let me implement the sparse file backed device -- and in a way that does not keep file handles opened for unused blocks. This is important because it reduces the active memory usage to only blocks that are being accessed and allows rclone to detect closed files then act accordingly. A bonus is it works over the network, or loopback for better performance, and in userspace (for the server side). I can isolate the google drive and rclone stack to one system and actually mount the filesystem on another system over the network similar to how iscsi is used.

I published my setup here so you can give it a try and let me know how it works for you: https://github.com/nathanshearer/nbdfs

I have one zfs instance that is super broken because of my repeated testing, force rebooting, and scribbing (plus the remote throttling). And I have another basic zfs instance that is actually very stable, likely because I haven't used it that much.

**Comment by nathanshearer** [comment]
Thinking back on this, I had several things in play that may have contributed to some write amplification and repeated rapid reads of some of the backing files.

- I had two sparse block devices, configured as a zfs raid 1 mirror. This doubles the space requirements, and was an ugly testing hack to detect errors. I doubt this was the root cause.
- I had compression enabled on the zfs filesystem. I do not think this contributed to the problem. If anything it may have actually helped by reducing IO to the rclone remote.
- I had deduplication enabled in zfs, just as an experiment to see if it would work. It did work, however I imagine the hash table for deduplication was being read a lot because my test system does not have much ram. This could be why some backing files were being read so much that they were throttled.
- My vfs cache is deliberately small at 48GB for testing. I'm not sure how rclone behaves when the writeback cache is full, new data is being written to the rclone mount and a bandwidth throttle is also enabled. Will rclone throttle new writes at the speed it is evicting things from the cache and writing them to the remote?
- I also tried enabling local file-backed l2arch and log files for zfs. I did not notice any improvement, but these files were relatively small at only 8GiB. I would prefer to avoid using these so that the whole filesystem remains consistent on the underlying rclone remote mountpoint. Having portions of the data writeback cached locally and the rest of the filesystem on the remote will likely result in corruption over long term use.

If a file is in an rclone writeback cache, and it is repeatedly used. Will rclone never ever sync it to the remote? This could be a problem as that would mean any higher-use files would never be uploaded and the complete dataset on the remote would be invalid most of the time and potentially always invalid.

**Comment by ncw** [comment]
> * My vfs cache is deliberately small at 48GB for testing. I'm not sure how rclone behaves when the writeback cache is full, new data is being written to the rclone mount and a bandwidth throttle is also enabled. Will rclone throttle new writes at the speed it is evicting things from the cache and writing them to the remote?

If the VFS cache is full of dirty data, rclone will flush out all the clean data. The cache will keep growing though - this is an area that needs improvement - rclone should reallly throttle the writers at this point.

> If a file is in an rclone writeback cache, and it is repeatedly used. Will rclone never ever sync it to the remote? 

Potentially not.

> This could be a problem as that would mean any higher-use files would never be uploaded and the complete dataset on the remote would be invalid most of the time and potentially always invalid.

The problem with syncing an in-use file is making sure it is consistent.

**Comment by nathanshearer** [comment]
> If the VFS cache is full of dirty data, rclone will flush out all the clean data. The cache will keep growing though - this is an area that needs improvement - rclone should reallly throttle the writers at this point.

I've completed some more testing and this may be the root cause of the problem. I was wiring data to the mountpoint faster than rclone could upload it to the remote, and the cache grew to the point where it ran out of space on the backing drive. Then everything fell apart from there since the write cache was corrupted.

In my latest test, these are the settings I have for the rclone mount:
```
#!/bin/bash

# --attr-timeout                        The default is "1s". The kernel will call back to rclone less often making it more efficient for '10s' or '1m' or longer.
# --cache-dir string                    Directory rclone will use for caching. Default is /root/.cache/rclone
# --vfs-cache-mode CacheMode            Cache mode off|minimal|writes|full (default off)
# --vfs-cache-poll-interval duration    Interval to poll the cache for stale objects. (default 1m0s)
# --vfs-cache-max-size SizeSuffix       Max total size of objects in the cache. (default off)
# --vfs-cache-max-age duration          Max age of objects in the cache. (default 1h0m0s)
# --vfs-write-back duration             Time to writeback files after last use when using cache. (default 5s)

rclone \
        --daemon \
        --log-file=/var/log/rclone.googledrive.log \
        --cache-dir /mnt/local01/rclonecache \
        mount \
        googledrive:/ \
        --bwlimit 4M \
        --drive-impersonate admin@example.com \
        --drive-use-trash=false \
        --fast-list \
        --vfs-cache-mode full \
        --vfs-cache-poll-interval 10m \
        --vfs-cache-max-size 8G \
        --vfs-cache-max-age 10h \
        --vfs-write-back 1h \
        --allow-other \
        --umask 0 \
        /mnt/googledrive
```
Although my vfs-cache-max-size is set to 8G, it is currently 262G while rclone is uploading as fast as it can. The two sparse block devices are part of a ZFS mirror and clean:
```
# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       117G   39G   73G  35% /
devtmpfs         10M     0   10M   0% /dev
tmpfs           392M  572K  392M   1% /run
cgroup_root      10M     0   10M   0% /sys/fs/cgroup
shm             2.0G     0  2.0G   0% /dev/shm
/dev/vdb1       687G  278G  375G  43% /mnt/local01
googledrive:    1.1P   39T  1.0P   4% /mnt/googledrive
archive03       924T  320G  924T   1% /mnt/archive03
# du -hs /mnt/local01/rclonecache
262G    /mnt/local01/rclonecache
# time du -hs /mnt/googledrive/archive03
677G    /mnt/googledrive/archive03

real    45m46.255s
user    0m0.878s
sys     0m7.867s
# zpool status
  pool: archive03
 state: ONLINE
config:

        NAME            STATE     READ WRITE CKSUM
        archive03       ONLINE       0     0     0
          mirror-0      ONLINE       0     0     0
            nbd0cached  ONLINE       0     0     0
            nbd1cached  ONLINE       0     0     0

errors: No known data errors
```
