### ISSUE TITLE
Setting dry-run in librclone is not working

### ISSUE THREAD

**Issue by co42** [rclone/rclone#5577]
#### What is the problem you are having with rclone?

`options/set` `{"main":{"DryRun":true}}` is not working in librclone, I got the error :
```
unknown option block "main"
```

Is does with rclone remote control :
`rclone rc options/set --json '{"main":{"DryRun":true}}'`

#### What is your rclone version (output from `rclone version`)

`rclone v1.56.0`

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

`darwin arm64`

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Hmm, I think the best way to do this would be to pass in `_config` with your request.

See https://rclone.org/rc/#setting-config-flags-with-config for more info.

Setting the global state probably isn't such a good idea for a library. It probably could be made to work if you are desperate!

**Comment by co42** [comment]
I didn't know you could use it directly it the config, thanks !
