### ISSUE TITLE
Copy original file when server side copying using a shared file shortcut in Google Drive

### ISSUE THREAD

**Issue by sidhant-khamankar** [rclone/rclone#5599]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/copy-the-contents-of-the-shortcut-when-server-side-copying-google-drive/19094

#### What is your current rclone version (output from `rclone version`)?
rclone v1.56.0

#### What problem are you are trying to solve?
Copy original file when server side copying using a shared file shortcut in Google Drive
Currently, it just copies the file shortcut and not the actual file

#### How do you think rclone should be changed to solve that?
I guess implementation would be similar to copying contents from inside of a folder shortcut.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I'd be happy to have this behaviour on a flag.

Is this something you'd like to work on @sidhant-khamankar ?

**Comment by sidhant-khamankar** [comment]
> Is this something you'd like to work on @sidhant-khamankar ?
Sorry, but I don't have knowledge of this application right now. 
I will try to contribute to open source once I complete my education and get a job.

**Comment by kenmorel** [comment]
I'll like to take this one. Any suggestions on a flag name @ncw ?

**Comment by kenmorel** [comment]
I'll like to take this one.

**Comment by ncw** [comment]
@kenmorel that would be great - thank you. I'll assign you the issue.

Let me know if you need any help.

**Comment by abhiraj2** [comment]
@ncw I believe PR #5977 fixes this issue right? or am I missing something?

**Comment by ncw** [comment]
Yes I think that does fix it.

I'll close this issue.
