### ISSUE TITLE
Failed to create file system for "remote:": didn't find section in config file

### ISSUE THREAD

**Issue by chenqichen** [rclone/rclone#5608]
rclone lsd remote:

Failed to create file system for "remote:": didn't find section in config file

**Comment by albertony** [comment]
Did you create a remote with name "remote"?
See documentation: here: https://rclone.org/docs/

If you think there is an error in rclone, we need more informtion - such as output from `rclone version`, `rclone config show` (passwords and other secrets removed), log...

**Comment by ncw** [comment]
@chenqichen - this would be a better question for [the rclone forum](https://forum.rclone.org/) as it isn't specifically a bug.

@albertony has given some good hints - if that isn't enough, please post on the forum.

I'm going to close this now, thank you.
