### ISSUE TITLE
Rclone serve http no authorization

### ISSUE THREAD

**Issue by ink0gnito** [rclone/rclone#5620]
#### What is the problem you are having with rclone?

I generated a htpasswd, when I start rclone serve I can access the files but without authorization.
I posted this problem also in rclone forum. NCW replied to me that he thinks the version has a bug and I should create an issue in github.
#### What is your rclone version (output from `rclone version`)

rclone v1.56.1

    os/version: debian 10.10 (64 bit)
    os/kernel: 4.19.0-17-amd64 (x86_64)
    os/type: linux
    os/arch: amd64
    go/version: go1.16.8
    go/linking: static
    go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Debian 10

#### Which cloud storage system are you using? (e.g. Google Drive)

GoogleDrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone serve http --addr :8080 --htpasswd /path/to/htpasswd gdrive:

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
`rclone serve http` is ignoring the auth in my tests, but `rclone serve webdav` isn't. It works in v1.55.1 but not in v1.56.1

It looks like this is a consequence of the http refactor.

Git bisect blames this commit 5d2e327b6fbec2e821f2b9f942bbaa1fe534c021 but the http serve just died on start after that commit so it may not be the correct one.

@innovate-invent do you have an idea what is going on?

**Comment by innovate-invent** [comment]
I haven't migrated the webdav service yet. I was slowly working through them (still waiting on a response for https://github.com/rclone/rclone/pull/5294 and https://github.com/rclone/rclone/pull/5299). It looks like there was an oversight/disconnect on where the auth middleware should be inserted. I think when I wrote the refactor I intended each service to instantiate auth on its own. But by the time I got to refactoring the services I thought I had the default http server loading auth by default.

Do you think it is better to just have auth enabled in the default server for all services? or should we add it per service route?

**Comment by innovate-invent** [comment]
I went with adding it in the service to avoid a dependency loop from the fact that it was originally designed to be imported from the service. Like you said, this is more flexible in the long run.

**Comment by ncw** [comment]
I've merged your fix now.

> One issue is that if a user does not configure auth, then it will not be enabled. Is there a default auth mechanism we should be requiring?

I'm just going to write a bit of "test the auth is working" tests on http/webdav/etc so this doesn't happen again - I think that is the correct mechanism.

**Comment by ncw** [comment]
@innovate-invent 

I've just noticed that the refactor in 5d2e327b6fbec2e821f2b9f942bbaa1fe534c021 took away the ability to configure the http server by passing an options block in which has made writing this test hard!

This means that these lines are doing nothing at all so the servers are being run on the same port and if they run concurrently the tests will fail

https://github.com/rclone/rclone/blob/b30731c9d04d03faee84e78f0e0f16357996e6dc/cmd/serve/http/http_test.go#L33-L34

The idea was that you could pass in options to create the server - these options can be from the command line, but they don't need to be. Servers shouldn't be configured only from the command line.

So I think we should kill the concept of the default server and only run servers where all the options are passed in.

I'd like to finish the http refactor. This includes  #5294 I think. We need to get to a point where we can delete `cmd/serve/httplib` as having two copies of flags is driving me nuts, eg

```
$ git grep flags.*HtPasswd
cmd/serve/httplib/httpflags/httpflags.go:       flags.StringVarP(flagSet, &Opt.HtPasswd, prefix+"htpasswd", "", Opt.HtPasswd, "htpasswd file - if not provided no authentication is done")
lib/http/auth/auth.go:  flags.StringVarP(flagSet, &Opt.HtPasswd, prefix+"htpasswd", "", Opt.HtPasswd, "htpasswd file - if not provided no authentication is done")
```

I think there is quite a bit of stuff which is ignoring the flags.

Thoughts?

**Comment by ncw** [comment]
@ink0gnito can you try [the latest beta](https://beta.rclone.org/) which should be fixed now.

**Comment by ncw** [comment]
I'll push this into v1.56.2 very soon.

**Comment by innovate-invent** [comment]
The core idea was to separate the concept of server and service.
The http service `newServer` function should probably be renamed `newService`.
If you want to run a new server for each test, that is actually just a one line change. I'll submit that later today. 
#5294 is part of that refactor, it is waiting for feedback as I am not clear what that error is related to.
I think once #5294 is merged there is one other dependency of the old httplib that will need to be refactored.

**Comment by ncw** [comment]
> The core idea was to separate the concept of server and service.
> The http service `newServer` function should probably be renamed `newService`.

I see.

> If you want to run a new server for each test, that is actually just a one line change. I'll submit that later today.

Great. We need to be able to pass the options in so they are different for every invocation.

> #5294 is part of that refactor, it is waiting for feedback as I am not clear what that error is related to.

I think you fixed the error by the look of the build. (other than the windows/386 which is probably not related to your code)

> I think once #5294 is merged there is one other dependency of the old httplib that will need to be refactored.

Do you know what that is?

**Comment by innovate-invent** [comment]
I have submitted #5648 to allow parallel execution of tests.

the remaining dependencies on the old httplib are webdav and rc:
```
Package
    httplib
Found usages  (30 usages found)
    Field declaration  (4 usages found)
        rclone  (4 usages found)
            cmd/serve/restic  (1 usage found)
                restic.go  (1 usage found)
                    Server  (1 usage found)
                        170 *httplib.Server
            cmd/serve/webdav  (1 usage found)
                webdav.go  (1 usage found)
                    WebDAV  (1 usage found)
                        112 *httplib.Server
            fs/rc  (1 usage found)
                rc.go  (1 usage found)
                    Options  (1 usage found)
                        21 HTTPOptions              httplib.Options
            fs/rc/rcserver  (1 usage found)
                rcserver.go  (1 usage found)
                    Server  (1 usage found)
                        65 *httplib.Server
    Import  (9 usages found)
        rclone  (9 usages found)
            cmd/serve/httplib/httpflags  (1 usage found)
                httpflags.go  (1 usage found)
                    4 "github.com/rclone/rclone/cmd/serve/httplib"
            cmd/serve/restic  (3 usages found)
                restic.go  (1 usage found)
                    16 "github.com/rclone/rclone/cmd/serve/httplib"
                restic_privaterepos_test.go  (1 usage found)
                    13 "github.com/rclone/rclone/cmd/serve/httplib"
                restic_test.go  (1 usage found)
                    13 "github.com/rclone/rclone/cmd/serve/httplib"
            cmd/serve/webdav  (2 usages found)
                webdav.go  (1 usage found)
                    12 "github.com/rclone/rclone/cmd/serve/httplib"
                webdav_test.go  (1 usage found)
                    22 "github.com/rclone/rclone/cmd/serve/httplib"
            fs/rc  (2 usages found)
                config_test.go  (1 usage found)
                    10 "github.com/rclone/rclone/cmd/serve/httplib"
                rc.go  (1 usage found)
                    16 "github.com/rclone/rclone/cmd/serve/httplib"
            fs/rc/rcserver  (1 usage found)
                rcserver.go  (1 usage found)
                    28 "github.com/rclone/rclone/cmd/serve/httplib"
    Parameter declaration  (3 usages found)
        rclone  (3 usages found)
            cmd/serve/httplib/httpflags  (1 usage found)
                httpflags.go  (1 usage found)
                    AddFlagsPrefix  (1 usage found)
                        16 func AddFlagsPrefix(flagSet *pflag.FlagSet, prefix string, Opt *httplib.Options) {
            cmd/serve/restic  (1 usage found)
                restic.go  (1 usage found)
                    NewServer  (1 usage found)
                        176 func NewServer(f fs.Fs, opt *httplib.Options) *Server {
            cmd/serve/webdav  (1 usage found)
                webdav.go  (1 usage found)
                    newWebDAV  (1 usage found)
                        124 func newWebDAV(ctx context.Context, f fs.Fs, opt *httplib.Options) *WebDAV {
    Unclassified  (14 usages found)
        rclone  (14 usages found)
            cmd/serve/httplib/httpflags  (1 usage found)
                httpflags.go  (1 usage found)
                    12 Opt = httplib.DefaultOpt
            cmd/serve/restic  (5 usages found)
                restic.go  (3 usages found)
                    NewServer  (1 usage found)
                        179 Server: httplib.NewServer(mux, opt),
                    ServeHTTP  (1 usage found)
                        230 v := r.Context().Value(httplib.ContextUserKey)
                    131 ` + httplib.Help,
                restic_privaterepos_test.go  (1 usage found)
                    newAuthenticatedRequest  (1 usage found)
                        23 req = req.WithContext(context.WithValue(req.Context(), httplib.ContextUserKey, "test"))
                restic_test.go  (1 usage found)
                    TestRestic  (1 usage found)
                        31 opt := httplib.DefaultOpt
            cmd/serve/webdav  (5 usages found)
                webdav.go  (3 usages found)
                    getVFS  (1 usage found)
                        154 value := ctx.Value(httplib.ContextAuthKey)
                    newWebDAV  (1 usage found)
                        138 w.Server = httplib.NewServer(http.HandlerFunc(w.handler), opt)
                    65 ` + httplib.Help + vfs.Help + proxy.Help,
                webdav_test.go  (2 usages found)
                    TestHTTPFunction  (1 usage found)
                        101 opt := httplib.DefaultOpt
                    TestWebDav  (1 usage found)
                        53 opt := httplib.DefaultOpt
            fs/rc  (2 usages found)
                config_test.go  (1 usage found)
                    TestOptionsGetMarshal  (1 usage found)
                        82 AddOption("http", &httplib.DefaultOpt)
                rc.go  (1 usage found)
                    39 HTTPOptions:       httplib.DefaultOpt,
            fs/rc/rcserver  (1 usage found)
                rcserver.go  (1 usage found)
                    newServer  (1 usage found)
                        117 Server:         httplib.NewServer(mux, &opt.HTTPOptions),
```
