### ISSUE TITLE
-–bwlimit not work on latest beta

### ISSUE THREAD

**Issue by amidevous** [rclone/rclone#5631]
system linux ubuntu 18.04

rclone latest installed using deb file

https://beta.rclone.org/rclone-beta-latest-linux-amd64.deb

rclone v1.57.0-beta.5664.1409b89f6
- os/version: ubuntu 18.04 (64 bit)
- os/kernel: 4.15.0-158-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.1
- go/linking: static
- go/tags: none

-–bwlimit not work

rclone -–bwlimit 10M copy uptobox:file.xlsx uptobox2: -vv
Error: unknown command "10M" for "rclone"
Run 'rclone --help' for usage.
You could use 'rclone selfupdate' to get latest features.

2021/09/26 16:27:28 Fatal error: unknown command "10M" for "rclone"

rclone copy -–bwlimit 10M uptobox:file.xlsx uptobox2: -vv

Error: unknown shorthand flag: 'â' in -–bwlimit
Usage:
  rclone copy source:path dest:path [flags]

Flags:
      --create-empty-src-dirs   Create empty source dirs on destination after copy
  -h, --help                    help for copy

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.

2021/09/26 16:28:53 Fatal error: unknown shorthand flag: 'â' in -–bwlimit

rclone copy uptobox:file.xlsx -–bwlimit 10M uptobox2: -vv

Error: unknown shorthand flag: 'â' in -–bwlimit
Usage:
  rclone copy source:path dest:path [flags]

Flags:
      --create-empty-src-dirs   Create empty source dirs on destination after copy
  -h, --help                    help for copy

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.

2021/09/26 16:30:27 Fatal error: unknown shorthand flag: 'â' in -–bwlimit

rclone copy uptobox:file.xlsx uptobox2:  -–bwlimit 10M -vv

Error: unknown shorthand flag: 'â' in -–bwlimit
Usage:
  rclone copy source:path dest:path [flags]

Flags:
      --create-empty-src-dirs   Create empty source dirs on destination after copy
  -h, --help                    help for copy

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.

2021/09/26 16:31:41 Fatal error: unknown shorthand flag: 'â' in -–bwlimit

rclone help flags | grep bwlimit
      --bwlimit BwTimetable                  Bandwidth limit in KiB/s, or use suffix B|K|M|G|T|P or a full timetable.
      --bwlimit-file BwTimetable             Bandwidth limit per file in KiB/s, or use suffix B|K|M|G|T|P or a full timetable.

please solve this problem

I absolutely need to be able to limit the flow on this transfer because it is absolutely necessary to preserve the bp for the clients

**Comment by ivandeex** [comment]
you keyboard replaced symbol
`--`
with
`-–`
:)

please copy-paste below command.
it's gonna work fine

```
rclone copy --bwlimit 10M uptobox:file.xlsx uptobox2: -vv
```

:)

**Comment by ivandeex** [comment]
you keyboard replaced symbol
`--`
with long dash
`-–`
:)

please copy-paste below command.
it's gonna work fine

```
rclone copy --bwlimit 10M uptobox:file.xlsx uptobox2:
```

:)

**Comment by ivandeex** [comment]
answered
