### ISSUE TITLE
can’t move inside union rclone mount

### ISSUE THREAD

**Issue by cberni** [rclone/rclone#5632]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/cant-move-inside-union-rclone-mount/26645

#### What is the problem you are having with rclone?

In order to rename a file you need to be able to Move it or Copy it then delete it (used in s3/gcs/swift/b2/etc as you can't rename an object)
The local backend can Move but not Copy
The bucket can Copy but not Move
The union's features are the AND of the underlying remotes so the union can't Move or Copy
So when rclone tries to move a file in the union it can't Move or Copy so it gives up.

The best solution that I can think of is for the union to advertise Move if all the underlying remotes support Move or Copy. Then in its own implementation of Move it should be turning Move into Copy+Delete on remotes which only support Copy.

#### What is your rclone version (output from `rclone version`)

rclone v1.56.1
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.4.0-86-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.16.8
- go/linking: static
- go/tags: none

#### Which cloud storage system are you using? (e.g. Google Drive)

union of "local" and "google cloud storate"

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

root@client:/union# mv a b
mv: cannot move 'a' to 'b': Input/output error

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

2021/09/22 13:05:13 DEBUG : /: Attr:
2021/09/22 13:05:13 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
2021/09/22 13:05:13 DEBUG : /: Lookup: name="a"
2021/09/22 13:05:13 DEBUG : /: >Lookup: node=a, err=<nil>
2021/09/22 13:05:13 DEBUG : a: Attr:
2021/09/22 13:05:13 DEBUG : a: >Attr: a=valid=1s ino=0 size=0 mode=-rw-rw-r--, err=<nil>
2021/09/22 13:05:13 DEBUG : /: Lookup: name="b"
2021/09/22 13:05:13 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2021/09/22 13:05:13 DEBUG : /: Lookup: name="b"
2021/09/22 13:05:13 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2021/09/22 13:05:13 DEBUG : /: Lookup: name="b"
2021/09/22 13:05:13 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2021/09/22 13:05:13 DEBUG : /: Rename: oldName="a", newName="b", newDir=/
2021/09/22 13:05:13 ERROR : a: Dir.Rename error: Fs "union root ''" can't rename files (no server-side Move or Copy)
2021/09/22 13:05:13 ERROR : a: Dir.Rename error: Fs "union root ''" can't rename files (no server-side Move or Copy)
2021/09/22 13:05:13 DEBUG : /: >Rename: err=Fs "union root ''" can't rename files (no server-side Move or Copy)
2021/09/22 13:05:13 DEBUG : /: Lookup: name="b"
2021/09/22 13:05:13 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory
2021/09/22 13:05:13 DEBUG : /: Lookup: name="b"
2021/09/22 13:05:13 DEBUG : /: >Lookup: node=<nil>, err=no such file or directory

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Can you try this beta please? I think it should fix the problem for you

[v1.57.0-beta.5667.85a4c848a.fix-5632-union](https://beta.rclone.org/branch/fix-5632-union/v1.57.0-beta.5667.85a4c848a.fix-5632-union/) on branch [fix-5632-union](https://github.com/rclone/rclone/tree/fix-5632-union) (uploaded in 15-30 mins)

**Comment by cberni** [comment]
tested and works like a charm.
Thank you very much!

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.57

Thanks for testing :-)
