### ISSUE TITLE
rclone check ends with packet too large error on Jottacloud

### ISSUE THREAD

**Issue by Zettt** [rclone/rclone#5639]
#### What is the problem you are having with rclone?
I'm trying to check whether the copy of a folder has completed successfully. It contains about 8TB of data. I'm trying to execute the following command:

```
rclone check gdrive:folder jotta:folder --one-way 
```

#### What is your rclone version (output from `rclone version`)
```
rclone v1.56.1
- os/version: darwin 11.6 (64 bit)
- os/kernel: 20.6.0 (arm64)
- os/type: darwin
- os/arch: arm64
- go/version: go1.17.1
- go/linking: dynamic
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
macOS 11.6 (20G165)

#### Which cloud storage system are you using? (e.g. Google Drive)

I believe Google Drive is the problem here. I'm on an ex G Suite plan. The error starts like outline below, then continues for a very long time with question marks, until it gives the packet too large error at the end.

```
Failed to create file system for "jotta:Arq Backup Data/52832173-5218-4409-92C7-79ECE1AE8191/objects": read metadata failed: error 500: org.springframework.dao.TransientDataAccessResourceException: PreparedStatementCallback; SQL [SELECT jc_id, jc_publicuri, jc_file, jc_path FROM jt_shared_file WHERE jc_username = ? AND jc_active = 1 AND jc_file IN (?, ?, ?, ?, ?…
Packet for query is too large (20,718,525 > 16,777,216). You can change this value on the server by setting the 'max_allowed_packet' variable.; nested exception is com.mysql.cj.jdbc.exceptions.PacketTooBigException: Packet for query is too large (20,718,525 > 16,777,216). You can change this value on the server by setting the 'max_allowed_packet' variable. (Internal Server Error)
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2021/09/27 16:07:52 DEBUG : rclone: Version "v1.56.1" starting with parameters ["rclone" "check" "gdrive:Arq Backup Data" "jotta:Arq Backup Data" "--one-way" "-vv"]
2021/09/27 16:07:52 DEBUG : Creating backend with remote "gdrive:Arq Backup Data"
2021/09/27 16:07:52 DEBUG : Using config file from "/Users/me/.config/rclone/rclone.conf"
2021/09/27 16:07:52 DEBUG : Google drive root 'Arq Backup Data': 'root_folder_id = 0AKoSAEy1eXD9Uk9PVA' - save this in the config to speed up startup
2021/09/27 16:07:53 DEBUG : Creating backend with remote "jotta:Arq Backup Data"
2021/09/27 16:09:36 DEBUG : pacer: low level retry 1/10 (error error 500: org.springframework.dao.TransientDataAccessResourceException: PreparedStatementCallback; SQL [SELECT jc_id, jc_publicuri, jc_file, jc_path FROM jt_shared_file WHERE jc_username = ? AND jc_active = 1 AND jc_file IN (?, ?, ?, ?,…
?, ?)]; Packet for query is too large (20,718,525 > 16,777,216). You can change this value on the server by setting the 'max_allowed_packet' variable.; nested exception is com.mysql.cj.jdbc.exceptions.PacketTooBigException: Packet for query is too large (20,718,525 > 16,777,216). You can change this value on the server by setting the 'max_allowed_packet' variable. (Internal Server Error))
2021/09/27 16:10:32 DEBUG : pacer: Rate limited, increasing sleep to 40ms
```
I did not wait for this command to complete, but I see it's increasing its sleep time.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by darthShadow** [comment]
This looks like an issue with jottacloud, not Google Drive. Please reach out to their support to see if they can tweak their config to allow larger packets.

**Comment by Zettt** [comment]
Thanks. I'll have a chat with their support to see if they can chance anything.

**Comment by albertony** [comment]
@Zettt Did you have any more information on this issue? Maybe Jottacloud fixed the problem on their side since this was reported?

**Comment by Zettt** [comment]
> @Zettt Did you have any more information on this issue? Maybe Jottacloud fixed the problem on their side since this was reported?

To be honest, I don't know anymore. I remember that I got in touch with the Jottacloud support, and they told me to use the `jotta-cli` because with large transfers, like the one I was attempting, it would *eventually* finish its job. So I'm assuming that other apps have some sort of limitation(?) when using their API. Obviously, I can't be sure of that.

**Comment by albertony** [comment]
Could be. Or maybe they meant that it is a transient error and that jotta-cli would retry it. And since their API is not officially public, they did not want to dig further into how rclone or others handles such things..

Anyway, since this issue is 2 years old, and I haven't seen similar reports, maybe we can close it? Should you or someone else actually be able to reproduce a similar case, we could reopen it.

**Comment by Zettt** [comment]
Yes, we can close this. Thanks for getting in touch.
