### ISSUE TITLE
ftp/docs: improve description of anonymous ftp

### ISSUE THREAD

**Issue by jyeric** [rclone/rclone#5650]
#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.50.2
- os/arch: windows/amd64
- go version: go1.13.4
```

#### What problem are you are trying to solve?

Support FTP annoymous mode with no password

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment]
Are you talking about client (i.e. a ftp backend), or server (i.e. the serve command)?

I think strictly speaking there is no concept of anonymous mode in ftp, but there is a de-facto standard to allow login of an account with name "anonymous" and typically same password. Do you agree? See e.g. https://datatracker.ietf.org/doc/html/rfc1635.

**Comment by jyeric** [comment]
> Are you talking about client (i.e. a ftp backend), or server (i.e. the serve command)?
> 
> I think strictly speaking there is no concept of ![Uploading image.png…]() mode in ftp, but there is a de-facto standard to allow login of an account with name "anonymous" and typically same password. Do you agree? See e.g. https://datatracker.ietf.org/doc/html/rfc1635.

I thought I may be talked about anonymous login. It is supported by Explorer on Windows. With the username of "Anonymous" and no password

**Comment by albertony** [comment]
Do you mean running `rclone serve ftp`, and then be able to access it anonymously, for example from Windows Explorer?
Or do you mean running `rclone copy remote:\Temp C:\Temp` and similar, where you have configured `remote:` as an remote of type ftp to access a external ftp server anonymously?

**Comment by jyeric** [comment]
I want to use rclone to connect to the FTP server anonymously. However, rclone must type/generate a password when adding a remote service of FTP. It seems that rclone doesn't support connecting to FTP anonymously now.

I think I mean the second one. I want to use `rclone mount remote:/ X:`

```
FTP password
y) Yes type in my own password
g) Generate random password
y/g>
```

**Comment by albertony** [comment]
Thanks. Now; in that case I would expect you could enter `anonymous` as username, or possibly `ftp`. And then the same as password, or possibly an email address. Can you try if any of those combinations work?

**Comment by ivandeex** [comment]
This probably needs a mention in the backend docs.

**Comment by albertony** [comment]
Agreed. Though, I'm not sure how standardized the username/password combo is? Seems `anonymous` as username is quite standard, but not password. Do @ivandeex have more insight on this?

Rclone's serve ftp, by the way, defaults to anonymous access: Clients must supply username `anonymous`, but it accepts *any* password. If accessing it from a rclone ftp remote you have to set a password (required option), and you have to go through the obscure, it seems. So a bit awkward, at least for ad-hoc access, e.g. connection string syntax.

**Comment by jyeric** [comment]
> Thanks. Now; in that case I would expect you could enter `anonymous` as username, or possibly `ftp`. And then the same as password, or possibly empty string, or (something that looks like) an email address. Can you try if any of those combinations work?

I test it locally by randomly generating a password and it works fine. I'll try it later on 10.8 after the vacation is over.

**Comment by ivandeex** [comment]
> Seems `anonymous` as username is quite standard, but not password.

Password can be _any_.

> So a bit awkward, at least for ad-hoc access, e.g. connection string syntax.

Just a bit. We could provide in the docs an example of connection string with a random short word obscured, like `:ftp,host=localhost,user=anonymous,pass=pVuLAfCeU9n7abDpktw3rU7T` (I obscured `hi`).

**Comment by albertony** [comment]
On a closer look, backend docs already mentions anonymous two places already:

> For an anonymous FTP server, use anonymous as username and your email address as password.

> rclone lsf :ftp: --ftp-host=speedtest.tele2.net --ftp-user=anonymous --ftp-pass=\`rclone obscure dummy\`

The second is just shown as an example of usage without config file, not explicitely mentioning anonymous access, and it will not work for Windows users. Something like this would be a variant for Windows/PowerShell:
```
rclone lsf :ftp: --ftp-host=speedtest.tele2.net --ftp-user=anonymous --ftp-pass=$(rclone obscure dummy)
```

An example with a "pre-obscured" password like you suggested would also be convenient.

So, to conclude: Anonymous access is supported, and documented. Although docs on it could be made more clear.

**Comment by ivandeex** [comment]
Let's find time sometime later to correct the docs.
