### ISSUE TITLE
sftp serve fails due to ssh-rsa deprecation

### ISSUE THREAD

**Issue by goldmund256** [rclone/rclone#5671]
**What is the problem you are having with rclone?**

OpenSSH has [deprecated the ssh-rsa](https://www.openssh.com/txt/release-8.8) algorithm, hence the command below fails. [A solution has been found as discussed here](https://forum.rclone.org/t/ssh-rsa-deprecated/26839/7), but this bug should get properly fixed.

#### What is your rclone version (output from `rclone version`)

v1.56.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Arch Linux 64bit

#### Which cloud storage system are you using? (e.g. Google Drive)

b2

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`$ rclone serve -vv sftp b2: --user user --pass test --addr 127.0.0.1:2020`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
<7>DEBUG : rclone: Version "v1.56.2" starting with parameters ["rclone" "serve" "-vv" "sftp" "b2:" "--user" "user" "--pass" "test" "--addr" "127.0.0.1:2020"]
<7>DEBUG : rclone: systemd logging support activated
<7>DEBUG : Creating backend with remote "b2:"
<7>DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
<7>DEBUG : Creating backend with remote "b2decrypted:"
<6>INFO  : Encrypted drive 'b2:': poll-interval is not supported by this remote
<5>NOTICE: Loaded 2 authorized keys from "/home/user/.ssh/authorized_keys"
<7>DEBUG : Loaded private key from "/home/user/.cache/rclone/serve-sftp/id_rsa"
<5>NOTICE: SFTP server listening on 127.0.0.1:2020
<3>ERROR : serve sftp 127.0.0.1:43030->127.0.0.1:2020: SSH login failed: ssh: no common algorithm for host key; client offered: [ecdsa-sha2-nistp256-cert-v01@openssh.com ecdsa-sha2-nistp256 ssh-ed25519-cert-v01@openssh.com ecdsa-sha2-nistp384-cert-v01@openssh.com ecdsa-sha2-nistp521-cert-v01@openssh.com sk-ssh-ed25519-cert-v01@openssh.com sk-ecdsa-sha2-nistp256-cert-v01@openssh.com rsa-sha2-512-cert-v01@openssh.com rsa-sha2-256-cert-v01@openssh.com ssh-ed25519 ecdsa-sha2-nistp384 ecdsa-sha2-nistp521 sk-ssh-ed25519@openssh.com sk-ecdsa-sha2-nistp256@openssh.com rsa-sha2-512 rsa-sha2-256], server offered: [ssh-rsa]
```

**Log from sftp**
```
$ sftp -P 2020 user@127.0.0.1
Unable to negotiate with 127.0.0.1 port 2020: no matching host key type found. Their offer: ssh-rsa
Connection closed.
Connection closed
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment]
@ncw Should we add support for Ed25519 while we're at it? My impression is that this is the most recommended alternative at the moment, supported in OpenSSH since version 6.5 (January 2014): `ssh-keygen -t ed25519`, default filename `id_ed25519`.
