### ISSUE TITLE
bisync: honor `--checksum` and `--ignore-checksum`

### ISSUE THREAD

**Issue by ivandeex** [rclone/rclone#5683]
## Synopsis

Delta engine in the _bisync beta_ can only use `modtime` to detect changes.
We should take hashsums into consideration too, respect the `--checksum` flag (and probably `--ignore-checksum`, but this has to be confirmed).

## Prior discussions

See https://github.com/cjnaz/rclonesync-V2/issues/5 and...

### https://github.com/rclone/rclone/pull/5164#issuecomment-859114705 (cjnaz)

Data point...
The TiBU directory has 19GB of files.  Path2 is a local dir.  2+ minutes for the `Path2 checking for diffs` step.

I tried the --ignore-checksum switch to no avail.

```
2021/06/10 14:36:26 INFO  : Synching Path1 "owncloud:TiBU/" with Path2 "/.../TiBU/"
2021/06/10 14:36:26 INFO  : Path1 checking for diffs
2021/06/10 14:36:26 INFO  : Path2 checking for diffs
2021/06/10 14:38:37 INFO  : No changes found
```

### https://github.com/rclone/rclone/pull/5164#issuecomment-859691994 (ivandeex) -> (ncw)

Current beta contains a [quick fix](https://github.com/ivandeex/rclone/commit/66b175d4dcd7ed56e9d79c25cd6cf5364686074b): in presence of --ignore-checksum the hashes will never be calculated (be it local fs, remote fs, or whatever). This is not a real solution but a kludge for your test.
For a real solution we have to develop a number of _rclonic_ rules for all case combinations: what to do if listings contain hash but user flagged ignore, how future name tracker will interact with this flag, should we treat backends with fast and slow hashsums differently, how --checksum and --ignore-checksum interact, etc, etc... It's a separate discussion and I'll drop this quick fix after all questions get solved.
For now you can try `--ignore-checksum` and evaluate the speed.

### https://github.com/rclone/rclone/pull/5164#issuecomment-859744308 (cjnaz)

--ignore-checksum brought the 19GB no-changes run down from 2 minutes to less than 1 second. Thanks for the interim hack.

## How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by nielash** [comment]
> Current beta contains a [quick fix](https://github.com/ivandeex/rclone/commit/66b175d4dcd7ed56e9d79c25cd6cf5364686074b): in presence of --ignore-checksum the hashes will never be calculated (be it local fs, remote fs, or whatever). This is not a real solution but a kludge for your test.

I think the `--ignore-checksum` part of this ticket is mostly addressed by https://github.com/rclone/rclone/pull/6971/commits/66ccc7c8509e6131db98c626521e2fca46525079.

The `--checksum` part remains an important to-do. Among other things, it will help us lift the [ban on backends that don't support `modtime`](https://rclone.org/bisync/#supported-backends).
