### ISSUE TITLE
bisync: add size checks to the delta engine and unit tests

### ISSUE THREAD

**Issue by ivandeex** [rclone/rclone#5684]
## Synopsis

Delta engine in the _bisync beta_ can only use `modtime` to detect changes.
We _could_ take file size into consideration too (especially in cases when modtime is not supported),
and add relevant test cases.

### https://github.com/rclone/rclone/pull/5164#issuecomment-842512914 (ivandeex)

> This is an issue with the overall algorithm of some sync tools but there is no reason you _need_ modtime to decide what to sync.

Theoretically, no. The bisync change detection in its current state is all about [bit masks](https://github.com/rclone/rclone/pull/5164/files#diff-25f7d45d3740899fdbbb93ff87a682943b7085b9c2f7f67b9cc58756c90e3630R31) (as opposed to "rclonic" [Equal](https://github.com/rclone/rclone/blob/v1.55.1/fs/operations/operations.go#L167)). But it needs more testing.

### https://github.com/rclone/rclone/pull/5164#issuecomment-843406665 (cjnaz)

Detecting on size change only leaves out the case where a file is changed but is the same size.  This could happen when a process writes a time string to a file, for example.  Other than this case, in practice changed-but-same-size is relatively rare; however, I'd be submitting a bug report if such a file was missed in the sync.

### https://github.com/rclone/rclone/pull/5164#issuecomment-843426747 (JWink3101)

Yep. I agree. It is a bad method but it is the same one, to my knowledge, used my rclone already for remotes that do not provide ModTime or a hash

## How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by cjnaz** [comment]
Best to follow the rclone precedent for change detection based on size.
