### ISSUE TITLE
bisync: print summary of operations

### ISSUE THREAD

**Issue by ivandeex** [rclone/rclone#5688]
## What problem are you are trying to solve?

@Rav830 wrote in https://github.com/rclone/rclone/pull/5164#issuecomment-906769729

I have been using `rclonesync` for around a year now and I have been surprised when certain files had a conflict and split into `Path1/Path2` versions when I didn't expect them to. Also, tracking the changes in the stdout can be difficult if many files have changed. 

Having a summary stating how many files have moved from A to B and vice versa, files deleted, files with conflicts and maybe other states that I am not thinking of would be appreciated. This can easily be extended include options to describe what has been touched in each category.

## How do you think rclone should be changed to solve that?

:thinking:

## How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by nielash** [comment]
> I have been using `rclonesync` for around a year now and I have been surprised when certain files had a conflict and split into `Path1/Path2` versions when I didn't expect them to.

I think this part was completed in https://github.com/rclone/rclone/pull/6971/commits/add917cfac363bd49ac718123f29f764ea5531c0.

> Having a summary stating how many files have moved from A to B and vice versa, files deleted, files with conflicts and maybe other states that I am not thinking of would be appreciated.

I think this is also done:
(note: requires `-v`)

https://github.com/rclone/rclone/blob/94a320f23cd9e6ad27a03a2ac3c833f8871129f8/docs/content/bisync.md?plain=1#L30-L64

So I think maybe this issue can just be closed?

**Comment by nielash** [comment]
Closing as completed (see explanation [here](https://github.com/rclone/rclone/issues/5688#issuecomment-1689710283).) If anyone disagrees, please feel free to reply / reopen.
