### ISSUE TITLE
Suspicious user check (always true) in basic auth

### ISSUE THREAD

**Issue by quasilyte** [rclone/rclone#5707]
#### What is the problem you are having with rclone?

In the code below we always return `pass` in `secretProvider`.

https://github.com/rclone/rclone/blob/85074f8f8866ae0f46db148008a9a0dd0d5912a2/lib/http/auth/basic.go#L88-L99

Look closely to this line:

https://github.com/rclone/rclone/blob/85074f8f8866ae0f46db148008a9a0dd0d5912a2/lib/http/auth/basic.go#L92

I would assume that we wanted to compare the `SingleAuth` param `user` and `secretProvider` closure param `user`, but since they have identical names, we have "always true" condition and `secretProvider` would always return `pass`.

#### What is your rclone version (output from `rclone version`)

Master tree source code contains this issue.

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Irrelevant.

#### Which cloud storage system are you using? (e.g. Google Drive)

Irrelevant.

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

Irrelevant.

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

Irrelevant.

**Comment by ncw** [comment]
Hmm, that's annoying!

What are the security implications?

Thoughts @innovate-invent ?

**Comment by innovate-invent** [comment]
The implication is that it ignores the username but still checks the password. Sorry for the copypasta, I have submitted a PR that corrects this.
