### ISSUE TITLE
dropbox operation canceled

### ISSUE THREAD

**Issue by jonathan-adams-fullstack** [rclone/rclone#5709]
rclone --version
rclone v1.56.2
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.11.0-1020-gcp (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.16.8
- go/linking: static
- go/tags: none

I have been using rclone for about a week now and have moved about 35TB of data to dropbox.  the files are exactly the same file type and around 110GB each. 

We use the exact same copy command line to start the transfer of usually 50 files at a time. Starting 2 days ago now when we upload its runs what seems fine until it hits about 50-60% then errors each file with 

2021-10-11 22:08:06 ERROR : file: Failed to copy: upload failed: Post "https://content.dropboxapi.com/2/files/upload_session/append_v2": read /mnt/nvme/dir/file: operation canceled

dropbox says this is not any error on their end. Any thoughts?

**Comment by Masamune3210** [comment]
Just my guess though so who knows

**Comment by ncw** [comment]
> operation canceled

This is some sort of socket error, so something to do with networking.

Could a firewall be cutting off the connection? Or your ISP?
