### ISSUE TITLE
Support S3 authorisation headers

### ISSUE THREAD

**Issue by r0kk3rz** [rclone/rclone#5720]
#### What is the problem you are having with rclone?
I am trying to configure rclone for use with an amazon snowball edge device using s3.

It appears this device does not support using signed URLs for authentication and requires an authentication header to be sent, and it seems there is no option to configure this behavior in rclone.

the request from rclone is:
```
2021/10/14 00:28:34 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021/10/14 00:28:34 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2021/10/14 00:28:34 DEBUG : HTTP REQUEST (req 0xc000698200)
2021/10/14 00:28:34 DEBUG : PUT /sealog/CS2001_eventTemplates.json?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[redacted]%2Faws4_request&X-Amz-Date=20211014T002834Z&X-Amz-Expires=900&X-Amz-SignedHeaders=content-md5%3Bcontent-type%3Bhost%3Bx-amz-acl%3Bx-amz-meta-mtime&X-Amz-Signature=[redacted] HTTP/1.1
Host: 147.66.81.30:8080
User-Agent: rclone/v1.56.2
Content-Length: 2679
content-md5: kM3xyCS2sV//fqKm1Q98QA==
content-type: application/json
x-amz-acl: private
x-amz-meta-mtime: 1611752214
Accept-Encoding: gzip
```

the http response from the device is:
```
<Error xsi:schemaLocation="http://s3.amazonaws.com/doc/2006-03-01/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Code>InvalidPart</Code>
    <Message>Authorization header cannot be null or empty</Message>
</Error>
```

#### What is your rclone version (output from `rclone version`)
rclone v1.56.2
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.4.0-72-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.16.8
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Ubuntu 20.04.2 LTS 64bit

#### Which cloud storage system are you using? (e.g. Google Drive)
Amazon Snowball Edge

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone sync --checksum [src] [dest]

**Comment by ncw** [comment]
This is unfortunately due to a deficit in the s3 SDK

The simple object upload

https://pkg.go.dev/github.com/aws/aws-sdk-go/service/s3#PutObjectInput

Takes the parameters

```
// Object data.
Body io.ReadSeeker `type:"blob"`
```

And rclone doesn't have an `io.ReadSeeker` it only has an `io.Reader`. The API seeks the file to a) find out how long it is and b) to calculate the sha checksum.

However there is a work-around

If you set `--s3-upload-cutoff 0` or set it in the config file with `upload_cutoff = 0`

      --s3-upload-cutoff SizeSuffix          Cutoff for switching to chunked upload (default 200Mi)
 
Then rclone will upload all the files as multipart uploads which will work.

**Comment by r0kk3rz** [comment]
> If that workaround works for you then it should go in the S3 docs I think!

Yes this works, and definitely worth documenting

**Comment by ncw** [comment]
Do you fancy making a fix to the docs @r0kk3rz ? You can click the pencil icon on this page and propose a pull request from your browser!

https://github.com/rclone/rclone/blob/master/docs/content/s3.md
