### ISSUE TITLE
v1.57 release

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#5734]
Dear @rclone/rclone 

The v1.57 release is overdue! I've pushed it back until the end of the month (12 days from now) to give us a little breathing space.

In those days I'd like to

- merge any outstanding PRs we should have in this release
- fix [the integration tests](https://pub.rclone.org/integration-tests/current/)

## PRs

I'd like a list of PRs that you'd like merged for the release. In particular from @ivandeex and @albertony I have lots of outstanding PRs which need reveiwing so which of those do you want for v1.57. And any other candidates!

## Integration tests

As far as the integration tests go there are 35 failing tests which is more than I'm happy with (I've beaten this down from 126 already!), so I'd like some help with those if possible.

- @buengese have you got time to look at the `zoho` and `compress` ones?
- @ivandeex can you have a look at the `chunker` ones?
- There are quite a few `TestSyncConcurrentTruncate` failures - since you introduced this test @ivandeex would you mind looking at those?
- I'll look at the `azureblob` ones and the `filefabric` ones
- There is also `TestCopyFileMaxTransfer` which should fix `TestDrive` and `TestCryptDrive` - any takers for that? @albertony ?

That should bring the list down to a more manageable level. I'll just note that the integration tests for `mega` are often broken as are the ones for `qingcloud`. The Onedrive china tests are broken because the access token needs refreshing - I'll try to sort that out!

**Comment by ivandeex** [comment]
#5735 will fix integration tests for chunker

**Comment by buengese** [comment]
I've been rather absent from rclone related things for a while, so there are quite a few things I want to catch up on. I'll look into the failing zoho and compress tests first. If I have the time I'm also going to look into the failing encoding tests for 1fichier.

**Comment by ncw** [comment]
@buengese I had a quick go at fixing 1fichier in 9742648fce294315da8afe347e923dd2f64bdb81 - my local tests indicated more list retries will fix the problem - we'll see tomorrow!

**Comment by ivandeex** [comment]
https://github.com/rclone/rclone/pull/5462 has got open questions...

**Comment by ncw** [comment]
After a lot of bashing on bugs, the integration test scores are as follows...

| backend | remote | test | failure | comments |
|----|----|----|----|----|
| compress | TestCompressDrive: | backend/compress | FsChangeNotify | @buengese  - not that important |
| fichier | TestFichier: | backend/fichier | Lots | API rate limiter is killing the tests |
| filefabric | TestFileFabric: | fs/sync | Didn't finish | Not finishing in 2hr time limit |
| mega | TestMega: | fs/operations | Login Fail | Test account over API quota |
| onedrive | TestOneDriveBusiness: | fs/sync | TestSyncConcurrentTruncate | @ivandeex investigating |
| onedrive | TestOneDriveCn: | backend/onedrive | All | test account broken |
| uptobox | TestUptobox: | fs/sync | TestSyncConcurrentTruncate | @ivandeex ? |
| zoho | TestZoho: | backend/zoho | All | test account broken |

I deem these good enough to make a release :-)

I'm going to merge any doc fix PRs that looks safe then make the release!

**Comment by ncw** [comment]
Release released!

Minor glitch on webside: https://rclone.org/downloads/ which I'll see if I can fix in a moment!

![image](https://user-images.githubusercontent.com/536803/139707370-8a6bdd63-7752-40f5-b8fa-057b65ef0df4.png)

Release announcement here: https://forum.rclone.org/t/rclone-1-57-0-release/27244

**Comment by ncw** [comment]
Fixed above website glitch in 19dfaf7440e212563dd5c63a4dc00b6408d79e19

I'm declaring this done!
