### ISSUE TITLE
Windows sha1sum via SFTP

### ISSUE THREAD

**Issue by SteveBox0** [rclone/rclone#5758]
#### What is the problem you are having with rclone?

I am using the official OpenSSH that is now part of windows (link below). This works well for file transfer but hash checks do not seem to work. 
https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse

I have tested using both sha1sum and md5sums. 

https://www.adaic.org/resources/add_content/standards/sha1sum.exe
--sftp-sha1sum-command "sha1sum"

http://www.pc-tools.net/files/win32/freeware/md5sums-1.2.zip
--sftp-md5sum-command "md5sums -u"

The first issue seems to be the path being different to sftp and i got around this using --sftp-path-override "C:\test folder". 

Looking at the console output the issue seems to be the way rclone handles the escape characters and backslashes. 

I think the best way forward would most likely just be an OS detection on SSH connect or a optional flag for Windows.

#### What is your rclone version (output from `rclone version`)

v1.57.0-beta.5801.bb11803f1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Client - Ubuntu 21.10
Server - Windows Server 2019

#### Which cloud storage system are you using? (e.g. Google Drive)

SFTP

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone sha1sum "windows:/C:/test folder/example1/" --sftp-sha1sum-command "sha1sum" -vv

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2021/10/26 18:08:39 DEBUG : rclone: Version "v1.57.0-beta.5801.bb11803f1" starting with parameters ["rclone" "sha1sum" "windows:/C:/test folder/example1/" "--sftp-sha1sum-command" "sha1sum" "-vv"]
2021/10/26 18:08:39 DEBUG : Creating backend with remote "windows:/C:/test folder/example1/"
2021/10/26 18:08:39 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2021/10/26 18:08:39 DEBUG : windows: detected overridden config - adding "{h5EBD}" suffix to name
2021/10/26 18:08:40 DEBUG : sftp://*****@*****//C:/test folder/example1/: New connection *****:39518->*****:22 to "SSH-2.0-OpenSSH_for_Windows_8.1"
2021/10/26 18:08:40 DEBUG : fs cache: renaming cache item "windows:/C:/test folder/example1/" to be canonical "windows{h5EBD}:/C:/test folder/example1/"
2021/10/26 18:08:40 DEBUG : sftp cmd = /C:/test\ folder/example1/file1.txt
2021/10/26 18:08:40 DEBUG : file1.txt: Failed to calculate sha1 hash: Process exited with status 1 (can't open `/C:/test\': Invalid argument)
                                          file1.txt
2021/10/26 18:08:40 DEBUG : 11 go routines active

```

**Comment by albertony** [comment]
That is true.
Actually, I was referring to only the first part, as the reason why the "/" was added. But you are right; using path/filepath is not a solution!

**Comment by albertony** [comment]
The sftp third party package is returning the `/C:/..` paths from `Getwd`. There are some issues and pr's related to it, e.g. https://github.com/pkg/sftp/issues/217, and https://github.com/pkg/sftp/pull/445, will look more into these later.

**Comment by albertony** [comment]
> I "loved" how CMD works with encoding, especially this part `╥Ёш шфшюЄр 2009.mkv`
> It's gonna be yet another problem :(

Yeah, that is a can of worms! But in Windows 10 you can set UTF-8 as code page in the console, e.g. for a single session by executing `chcp 65001`, hopefully that improves the situation some..

**Comment by ivandeex** [comment]
`chcp 65001` changed the Conemu output :)

```
C:\Users\ivandeex>chcp 65001
Active code page: 65001

C:\Users\ivandeex>C:\abyss\bin\sha1sum.exe "/C:/Users/ivandeex/Videos/Три идиота 2009.mkv"
can't open `/C:/Users/ivandeex/Videos/��� ������ 2009.mkv': Invalid argument
```

Hopefully OpenSSH is not affected and rclone will be able file names.
At any rate codepage support is out of scope for this PR. You can safely pass worms to a future PR.
```
C:\Users\ivandeex>echo %ComSpec%
C:\WINDOWS\system32\cmd.exe
C:\Users\ivandeex>C:\abyss\bin\sha1sum.exe "C:\Users\ivandeex\Videos\Tri idiota 2009.mkv"
ea1ea25a4e964196d67869039218ab8fefac99e5  C:\Users\ivandeex\Videos\Tri idiota 2009.mkv
```

**Comment by SteveBox0** [comment]
The build (rclone-v1.57.0-beta.5809.af17cbe72.sftp-windows-server-linux-amd64) seems to be working fine but with one odd side effect. Using SHA1 and around 1000 small files the Window server kernel time is over 50% during the test.

**Comment by SteveBox0** [comment]
Also, tested rclone v1.57.0-beta.5806.a238877ad and rclone-v1.57.0-beta.5750.a3d16b4f8 with hasher backend. Should i create a new issue for this or is it related? 

```
rclone cat "Hasher:/C:/test folder/" -vv 
<7>DEBUG : rclone: Version "v1.57.0-beta.5806.a238877ad" starting with parameters ["rclone" "cat" "Hasher:/C:/test folder/" "-vv"]
<7>DEBUG : rclone: systemd logging support activated
<7>DEBUG : Creating backend with remote "Hasher:/C:/test folder/"
<7>DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
<6>INFO  : Hasher is EXPERIMENTAL!
<7>DEBUG : Creating backend with remote "windows/C:/test folder"
<7>DEBUG : fs cache: renaming cache item "windows/C:/test folder" to be canonical "/home/user/Documents/windows/C:/test folder"
<7>DEBUG : hasher::Hasher:/C:/test folder/: Groups by usage: cached [sha1], passed [], auto [], slow [md5, sha1, whirlpool, crc32, sha256, dropbox, mailru, quickxor], supported [md5, sha1, whirlpool, crc32, sha256, dropbox, mailru, quickxor]
<3>ERROR : : error listing: directory not found
<7>DEBUG : 3 go routines active
Failed to cat with 2 errors: last error was: directory not found
```
```
[Hasher]
type = hasher
remote = windows
hashes = sha1
max_age = 1d
```

**Comment by ivandeex** [comment]
> Should i create a new issue for this

No

> remote = windows

This means local directory `windows` below current dir
You actually want another remote named `windows:` (with trailing colon)
```
remote = windows:
```

**Comment by albertony** [comment]
> Using SHA1 and around 1000 small files the Window server kernel time is over 50% during the test.

Which shell? Default/cmd, with sha1sum_command configured? Or PowerShell, with the built in script sum commands, or something else configured?

**Comment by ivandeex** [comment]
@SteveBox0 

> Also, tested rclone [...] with hasher backend. Should i create a new issue for this or is it related?

Let me correct myself after thinking over it.
Hasher is brand new (experimental) and may well be under-tested. It's not productive to mix bug reports involving hasher with anything else, especially other new features like windows support in SFTP backend.
Mixing threads is counter-productive.

Can I ask you to submit a separate ticket where I can look into your problem in isolation.

Thanks

**Comment by ivandeex** [comment]
@SteveBox0 

In the mean time you can provide more info requested by Albertony.

**Comment by albertony** [comment]
(What I'm curious about is if the built-in PowerShell hash calculation is too slow to be a good alternative to external tools)

New beta coming up, which hopefully fixes the issue with relative paths you encountered @ivandeex (https://github.com/rclone/rclone/pull/5763#issuecomment-955287745)

**Comment by albertony** [comment]
@ivandeex  A bit off topic: Do you know if use statvfs SSH_FXP_EXTENDED feature (https://pkg.go.dev/github.com/pkg/sftp#StatVFS) has been considered for the about command, instead of executing `df` in shell? It seems at least the Windows OpenSSH port implements it (https://github.com/PowerShell/openssh-portable/blob/942e993fac6a48924244e124f7a133f7e0c18f8d/contrib/win32/win32compat/misc.c#L1140-L1180). Should probably try this first in the about command, and fallback to existing behavior for servers not implementing it. But this is for another time/issue/PR.

**Comment by ivandeex** [comment]
> Do you know if use statvfs SSH_FXP_EXTENDED feature has been considered for the about command, instead of executing `df` in shell? It seems at least the Windows OpenSSH port implements it.

Have not heard about it. Maybe @ncw knows?

**Comment by SteveBox0** [comment]
> > Using SHA1 and around 1000 small files the Window server kernel time is over 50% during the test.
> 
> Which shell? Default/cmd, with sha1sum_command configured? Or PowerShell, with the built in script sum commands, or something else configured?

Default shell with 
--sftp-sha1sum-command "sha1sum"

**Comment by ivandeex** [comment]
@albertony 
Congrats!
The latest commit works fine for my Windows-8.1+CMD remote.
No problems with Russian characters - Not affected by the above Conemu2+CMD+Russian problem.
In the test below I check absolute dir `C:\abyss\test` and relative one `C:\Users\ivandeex\test`:

```
$ git log -1
commit a3fb35f8e20a89a81b26021592f32d10c6332208 (HEAD -> sftp-windows-server, upstream/sftp-windows-server)
Author: albertony <12441419+albertony@users.noreply.github.com>
Date:   Sat Oct 30 23:31:13 2021 +0200
    sftp: fix a corner case variant where absolute remote shell path was still having slash prefix on windows
$ go build

$ ./rclone config show evan
--------------------
[evan]
type = sftp
host = 10.33.3.5
port = 22
user = ivandeex
key_file = xxx
encoding = Slash,LtGt,DoubleQuote,Colon,Question,Asterisk,Pipe,BackSlash,Ctl,RightSpace,RightPeriod,InvalidUtf8
md5sum_command = none
sha1sum_command = C:\abyss\bin\sha1sum.exe
remote_shell = cmd
--------------------

$ ./rclone sha1sum evan:/abyss/test -vv
2021/10/31 12:35:16 DEBUG : rclone: Version "v1.57.0-DEV" starting with parameters ["./rclone" "sha1sum" "evan:/abyss/test" "-vv"]
2021/10/31 12:35:16 DEBUG : Creating backend with remote "evan:/abyss/test"
2021/10/31 12:35:16 DEBUG : Using config file from "/home/deex/.rclone.conf"
2021/10/31 12:35:17 DEBUG : sftp://ivandeex@10.33.3.5:22//abyss/test: New connection 10.33.3.43:51122->10.33.3.5:22 to "SSH-2.0-OpenSSH_for_Windows_8.0"
2021/10/31 12:35:18 DEBUG : sftp://ivandeex@10.33.3.5:22//abyss/test: Shell type "cmd" set from config
2021/10/31 12:35:18 DEBUG : sftp://ivandeex@10.33.3.5:22//abyss/test: Using root directory "/abyss/test"
2021/10/31 12:35:19 DEBUG : its-lama.png: Executing shell hash comand: C:\abyss\bin\sha1sum.exe "/abyss/test/its-lama.png"
2021/10/31 12:35:19 DEBUG : its-lama.png: Command output: 971890f1b5a2cf99c6dcb193113834e27db30ea0  /abyss/test/its-lama.png
2021/10/31 12:35:19 DEBUG : its-lama.png: Parsed hash: 971890f1b5a2cf99c6dcb193113834e27db30ea0
971890f1b5a2cf99c6dcb193113834e27db30ea0  its-lama.png
2021/10/31 12:35:20 DEBUG : sftp://ivandeex@10.33.3.5:22//abyss/test: New connection 10.33.3.43:51134->10.33.3.5:22 to "SSH-2.0-OpenSSH_for_Windows_8.0"
2021/10/31 12:35:20 DEBUG : sftp://ivandeex@10.33.3.5:22//abyss/test: New connection 10.33.3.43:51136->10.33.3.5:22 to "SSH-2.0-OpenSSH_for_Windows_8.0"
2021/10/31 12:35:21 DEBUG : это лама.png: Executing shell hash comand: C:\abyss\bin\sha1sum.exe "/abyss/test/это лама.png"
2021/10/31 12:35:21 DEBUG : Thumbs.db: Executing shell hash comand: C:\abyss\bin\sha1sum.exe "/abyss/test/Thumbs.db"
2021/10/31 12:35:21 DEBUG : это лама.png: Command output: 971890f1b5a2cf99c6dcb193113834e27db30ea0  /abyss/test/ .png
2021/10/31 12:35:21 DEBUG : это лама.png: Parsed hash: 971890f1b5a2cf99c6dcb193113834e27db30ea0
971890f1b5a2cf99c6dcb193113834e27db30ea0  это лама.png
2021/10/31 12:35:21 DEBUG : Thumbs.db: Command output: 652320bed47536d00feae9dad528ea87e4c7bf83  /abyss/test/Thumbs.db
2021/10/31 12:35:21 DEBUG : Thumbs.db: Parsed hash: 652320bed47536d00feae9dad528ea87e4c7bf83
652320bed47536d00feae9dad528ea87e4c7bf83  Thumbs.db
2021/10/31 12:35:21 DEBUG : 29 go routines active

$ ./rclone sha1sum evan:test -vv
2021/10/31 12:36:41 DEBUG : rclone: Version "v1.57.0-DEV" starting with parameters ["./rclone" "sha1sum" "evan:test" "-vv"]
2021/10/31 12:36:41 DEBUG : Creating backend with remote "evan:test"
2021/10/31 12:36:41 DEBUG : Using config file from "/home/deex/.rclone.conf"
2021/10/31 12:36:42 DEBUG : sftp://ivandeex@10.33.3.5:22/test: New connection 10.33.3.43:51284->10.33.3.5:22 to "SSH-2.0-OpenSSH_for_Windows_8.0"
2021/10/31 12:36:43 DEBUG : sftp://ivandeex@10.33.3.5:22/test: Shell type "cmd" set from config
2021/10/31 12:36:43 DEBUG : sftp://ivandeex@10.33.3.5:22/test: Relative path resolved to "/C:/Users/ivandeex/test"
2021/10/31 12:36:43 DEBUG : sftp://ivandeex@10.33.3.5:22/test: Using root directory "/C:/Users/ivandeex/test"
2021/10/31 12:36:44 DEBUG : sftp://ivandeex@10.33.3.5:22/test: Shell path adjusted (set option path_override to override): C:/Users/ivandeex/test/its-lama.png
2021/10/31 12:36:44 DEBUG : its-lama.png: Executing shell hash comand: C:\abyss\bin\sha1sum.exe "C:/Users/ivandeex/test/its-lama.png"
2021/10/31 12:36:44 DEBUG : its-lama.png: Command output: 971890f1b5a2cf99c6dcb193113834e27db30ea0  C:/Users/ivandeex/test/its-lama.png
2021/10/31 12:36:44 DEBUG : its-lama.png: Parsed hash: 971890f1b5a2cf99c6dcb193113834e27db30ea0
971890f1b5a2cf99c6dcb193113834e27db30ea0  its-lama.png
2021/10/31 12:36:45 DEBUG : sftp://ivandeex@10.33.3.5:22/test: New connection 10.33.3.43:51298->10.33.3.5:22 to "SSH-2.0-OpenSSH_for_Windows_8.0"
2021/10/31 12:36:45 DEBUG : sftp://ivandeex@10.33.3.5:22/test: New connection 10.33.3.43:51300->10.33.3.5:22 to "SSH-2.0-OpenSSH_for_Windows_8.0"
2021/10/31 12:36:46 DEBUG : sftp://ivandeex@10.33.3.5:22/test: Shell path adjusted (set option path_override to override): C:/Users/ivandeex/test/Thumbs.db
2021/10/31 12:36:46 DEBUG : Thumbs.db: Executing shell hash comand: C:\abyss\bin\sha1sum.exe "C:/Users/ivandeex/test/Thumbs.db"
2021/10/31 12:36:46 DEBUG : sftp://ivandeex@10.33.3.5:22/test: Shell path adjusted (set option path_override to override): C:/Users/ivandeex/test/это
лама.png
2021/10/31 12:36:46 DEBUG : это лама.png: Executing shell hash comand: C:\abyss\bin\sha1sum.exe "C:/Users/ivandeex/test/это лама.png"
2021/10/31 12:36:46 DEBUG : Thumbs.db: Command output: 652320bed47536d00feae9dad528ea87e4c7bf83  C:/Users/ivandeex/test/Thumbs.db
2021/10/31 12:36:46 DEBUG : Thumbs.db: Parsed hash: 652320bed47536d00feae9dad528ea87e4c7bf83
652320bed47536d00feae9dad528ea87e4c7bf83  Thumbs.db
2021/10/31 12:36:46 DEBUG : это лама.png: Command output: 971890f1b5a2cf99c6dcb193113834e27db30ea0  C:/Users/ivandeex/test/ .png
2021/10/31 12:36:46 DEBUG : это лама.png: Parsed hash: 971890f1b5a2cf99c6dcb193113834e27db30ea0
971890f1b5a2cf99c6dcb193113834e27db30ea0  это лама.png
2021/10/31 12:36:46 DEBUG : 29 go routines active
```

**Comment by albertony** [comment]
@ivandeex: I noticed you set this option, which I suspect does nothing on sftp:

> encoding = Slash,LtGt,DoubleQuote,Colon,Question,Asterisk,Pipe,BackSlash,Ctl,RightSpace,RightPeriod,InvalidUtf8

Trying to set it as command line argument throws:

> Fatal error: unknown flag: --sftp-encoding

I noticed it during my work on the code also; I think encoding is not implemented for this backend.
