### ISSUE TITLE
GCP with composite objects to S3 with object-lock enabled doesn't work

### ISSUE THREAD

**Issue by paulopontesm** [rclone/rclone#5765]
#### What is the problem you are having with rclone?

It might be a bit of an edge case, but I am trying to copy composite objects from GCP to an S3 bucket with object-lock enabled.

This is where I got so far:

* Looking at google's [documentation for composite objects](https://cloud.google.com/storage/docs/composite-objects), I can see this:

    > Composite objects do not have an MD5 hash metadata field.

* According to AWS's docs 

   >  The Content-MD5 header is required for any request to upload an object with a retention period configured using Amazon S3 Object Lock. For more information about Amazon S3 Object Lock, see Amazon S3 Object Lock Overview in the Amazon S3 User Guide.

I've tracked down the problem to this line so far:

https://github.com/rclone/rclone/blob/master/backend/googlecloudstorage/googlecloudstorage.go#L914

For composite objects, that returns an empty hash, and it is propagated all the way up to the S3 put.

#### What is your rclone version (output from `rclone version`)

```bash
✗ rclone --version
rclone v1.56.2
- os/version: darwin 12.0.1 (64 bit)
- os/kernel: 21.1.0 (x86_64)
- os/type: darwin
- os/arch: amd64
- go/version: go1.17.2
- go/linking: dynamic
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

MacOS

#### Which cloud storage system are you using? (e.g. Google Drive)

GCP to S3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
rclone --s3-server-side-encryption "aws:kms" --s3-sse-kms-key-id "{arn_kms_key}" --config rclone.conf copy gcs:{source_bucket}/{composite_object_name} s3://{target_s3_bucket_with_object_lock}

2021-10-28 15:24:18 ERROR : {composite_object_name}: Failed to copy: s3 upload: 400 Bad Request: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>Content-MD5 HTTP header is required for Put Object requests with Object Lock parameters</Message><RequestId>xxxx</RequestId><HostId>xxxx</HostId></Error>
```

```
# rclone.conf
[gcs]
type = google cloud storage
project_number = {project_number}

[s3]
type = s3
provider = AWS
env_auth = true
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by paulopontesm** [comment]
I am not 100% sure, but I think that header is only usefull when deleting objects. The `object-lock` theoretically prevents anyone from deleting object, but it can be overriden on `Governance mode`.

I actually have my bucket setup with `Compliance mode` instead of `Governance mode`, which is my final goal. The problem described above happens on both modes.

The command I left above enables `Governance mode` because it is possible to override and delete objects, it's better for testing. Using `Compliance mode` for testing is a trap, if you set it for 1 year, you have to wait 1 year to delete your objects 😅

**Comment by ncw** [comment]
> I am not 100% sure, but I think that header is only usefull when deleting objects. The `object-lock` theoretically prevents anyone from deleting object, but it can be overriden on `Governance mode`.

Yes, that's what I meant, use that header when deleting objects and you can do it from rclone.

> I actually have my bucket setup with `Compliance mode` instead of `Governance mode`, which is my final goal. The problem described above happens on both modes.
> 
> The command I left above enables `Governance mode` because it is possible to override and delete objects, it's better for testing. Using `Compliance mode` for testing is a trap, if you set it for 1 year, you have to wait 1 year to delete your objects sweat_smile

Arg!

So what shall we do about this issue? Do you want to propose a doc change for https://github.com/rclone/rclone/blob/master/docs/content/s3.md ?

**Comment by animosity22** [comment]
@paulopontesm  - would you like to propose a doc change or I can close this out if you want.
