### ISSUE TITLE
Windows cannot open the exe file. My win2012 server is normal and my win10 system is wrong

### ISSUE THREAD

**Issue by bbhxwl** [rclone/rclone#5769]
#### What is the problem you are having with rclone?
Windows cannot open the EXE file. My win2012 server is normal and my win10 system is wrong

![LXF(%U 22$(SA((DE%_$SE1](https://user-images.githubusercontent.com/26525599/139406475-12d1b14c-36c5-4111-bf55-2478b3c424dc.png)

#### What is your rclone version (output from `rclone version`)

1.56.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
win10

#### Which cloud storage system are you using? (e.g. Google Drive)

china onedrive 

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone mount od:/AiDeLi/Share x: --volname CompanyShare --cache-dir D:\onedrive\RCloneCaChe --file-perms 0777 --vfs-cache-mode full

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ivandeex** [comment]
I am going to close this ticket as the discussion has moved to the forum

https://forum.rclone.org/t/cant-double-click-to-open-the-exe-file-when-windows-is-in-use/27213/23
