### ISSUE TITLE
Feature request - Custom service API endpoints (base URL) config.

### ISSUE THREAD

**Issue by LittleJake** [rclone/rclone#5776]
#### What is your current rclone version (output from `rclone version`)?

`go version go1.17.2 windows/amd64`

#### What problem are you are trying to solve?

Hi.

Is there any idea that make the services API Base URL configurable?

Something like: Google APIs and Microsoft Sharepoint, etc.

In some case, we have some reverse proxies to proxy the endpoint API through CDN networks.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
You can use an http/https proxy with rclone - see the docs here https://rclone.org/faq/#can-i-use-rclone-with-an-http-proxy - would that work for you?

**Comment by LittleJake** [comment]
thanks, @ncw.

I think the forward proxy is not as stable as the reverse proxy with a CDN network. Just like the Golang is using env "GOPROXY" to proxy the dependencies downloading. Besides, different networks have different connectivity among proxies. So the CDN network is a great solution not only for the bad connectivity areas but also for the areas where some services are blocked.

**Comment by animosity22** [comment]
For Google Drive as an example, if you try to make it CDN aware, you have to customize your own app keys and URIs for authentication and whatnot.

For many of the URL based items, you can already pick a custom URL.

If you really wanted to, you can always configure a server / client system to point to your CDN for the API URLs by overriding  the DNS.

For blocked areas, a VPN would also work with a Proxy.

If there is a specific backend or something, let's open a request and you can try to get that adjusted if there is enough interest.

Happy to help or discuss on the forums as well if you have further follow up qestions.

Thanks!
