### ISSUE TITLE
backend/cache test failure on linux/386

### ISSUE THREAD

**Issue by 4ricci** [rclone/rclone#5784]
#### What is the problem you are having with rclone?

The test for `backend/cache` fails since 09fd258b5c1c52a9515cf09f6cf088af5a463a6f (according to `git bisect`).

#### Which OS you are using and how many bits

Void Linux i686, go1.17.2
Alpine 3.14 i386 (container), go1.16.8

#### The command you were trying to run

```
$ git checkout 454574e2cc974a3cacff6ea48e3eeb899d592ec5
$ RCLONE_CONFIG="/notfound" go test -v ./backend/cache
```
Log is attached because it contains binary data.
[log_backend_cache.txt](https://github.com/rclone/rclone/files/7471921/log_backend_cache.txt)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
This looks like a timing related issue, similar to #5768 

Is there something odd about the VM you are running these on? Is it very slow, or have an unusual time source, or low timer resolution or...?

**Comment by ivandeex** [comment]
I remember I once seen this case fail with timeout in quick race test on github.

**Comment by ivandeex** [comment]
Nowadays linux/386 implies something like RaspberryPI or embedded board.

**Comment by 4ricci** [comment]
> Nowadays linux/386 implies something like RaspberryPI or embedded board.

"386" actually means x86 32-bit (aka i386/i486/i586/i686). I put "386" in the title because this is the name used by the Go compiler.
The physical machine has a 64bit Intel CPU.


> Is there something odd about the VM you are running these on? Is it very slow, or have an unusual time source, or low timer resolution or...?

The machine is quite slow, but I doubt it's an hardware issue because the tests pass if I compile for 64bit (this is also true for #5783).

**Comment by 4ricci** [comment]
> > the tests pass if I compile for 64bit (this is also true for #5783)

I tested both `backend/cache` and `cmd/serve/ftp`, with both 32 and 64 bit compilers, with both 32 and 64 bit `GOARCH`, on the same physical machine. Theese two tests always fail if the target is 32 bit and always pass if it is 64 bit.

**Comment by ivandeex** [comment]
I can't recall other requests on tracker or forum to officially support 386. I don't think there is substantial demand.
Do you want to maintain port of rclone to this architecture?

**Comment by ivandeex** [comment]
Also we marked `cache` backend as deprecated in the docs and recently added a runtime deprecation notice.
I don't think we will allocate developers to support deprecated backend on rarely demanded platform.
If you wish you can submit a fix or even maintain this combo.

**Comment by 4ricci** [comment]
> Do you want to maintain port of rclone to this architecture?

I'm packaging rclone for Void Linux and I noticed the tests fail on CI, so I reported the issue, I will not maintain a port.

> I don't think we will allocate developers to support deprecated backend on rarely demanded platform.

Understand. Thanks for yout time. If no one has something to add, this can be closed.

**Comment by ncw** [comment]
There could be a timeout we could increase to make the test pass which might be an easy fix.

If not then as @ivandeex suggests, I think we'll ignore this.

**Comment by animosity22** [comment]
Is this ignored or more work here? Can it be closed out?
