### ISSUE TITLE
Cache Chunk Path not working?

### ISSUE THREAD

**Issue by chchia** [rclone/rclone#5803]
Using latest rclone, with below mount command:

```
sudo /usr/bin/rclone --config /volume1/docker/rclone/rclone.conf mount gCryptQSvfs: /volume2/downloads/media/ --allow-other --umask 000 --transfers=10 --checkers=30 --buffer-size 4M --tpslimit=10 --default-permissions --copy-links --no-gzip-encoding --no-check-certificate --vfs-read-wait 60ms --dir-cache-time 9999h --vfs-cache-mode full --use-mmap --attr-timeout 9999h --no-checksum --no-modtime --poll-interval 1m --cache-chunk-path=/volume2/downloads/vfs/ --cache-db-path=/volume1/docker/rclone/vfs/ --cache-dir=/volume2/downloads/vfs/ --cache-tmp-upload-path=/volume2/downloads/vfs/tmp_upload --vfs-read-ahead 32M --cache-chunk-total-size 2G -vvP
```

but actually it seem **cache-chunk-path** is not set, the chunk-path is appear in my volume1 while it suppose to be in volume2.
![image](https://user-images.githubusercontent.com/1291771/141258084-c8548444-5b69-4242-bc42-32d5de0f1e67.png)

previously using CACHE backend i can use different chunk-path, is VFS mode not support this? 
it seems VFS is following only **--cache-dir**

**Comment by chchia** [comment]
the reason i need to split it because:

volume1 is SSD, previously with cache backend i stored the db files here for fastest access.

volume2 is HDD, previously with cache backend i stored the cache-chunk-path here for larger size and no ssd wear out.

kindly please teach me with VFS, how do i use separate path for cache-chunk-path. thanks.

**Comment by animosity22** [comment]
I can't figure out quite what you are asking.

The cache backend is going away at some point so no changes will happen there.

The cache-chunk-path is used for that backend.

The Cache-dir is where the new VFS cache-mode stores its items. That is used for caching files and there isn't a metadata cache like in the cache backend as they aren't the same.

There are a few requests out there for metadata caching and optimizations for the new VFS cache so I'm marking this as answered and closing out.

If you have a question, please just ask on the forums as it's easier as we like to track bugs/defects/enhancements here.

Thanks!
