### ISSUE TITLE
sed operation on sync

### ISSUE THREAD

**Issue by tooptoop4** [rclone/rclone#5807]
is there any option to apply some replace operation on contents of files? ie sync folder A to B but before writing the files to B allow a sed style command to replace foo with bar.

**Comment by ivandeex** [comment]
no

**Comment by ivandeex** [comment]
you'll have to write a shell script

**Comment by animosity22** [comment]
This looks answered and you can use the forums for use questions rather than making an issue.

https://forum.rclone.org/
