### ISSUE TITLE
rclone mount helper does not ignore _netdev

### ISSUE THREAD

**Issue by akdev1l** [rclone/rclone#5808]
#### The associated forum post URL from `https://forum.rclone.org`
I do not frequent the forums, I could not find a thread that discusses the issue at hand though.

#### What is the problem you are having with rclone?

when using rclone as a mount helper (by simlinking to /usr/sbin/mount.rclone as described [here](https://rclone.org/commands/rclone_mount/#rclone-as-unix-mount-helper)

The relevant example in the documentation does not work, specifically it recommend adding an fstab line like the following:

    sftp1:subdir /mnt/data rclone rw,noauto,nofail,_netdev,x-systemd.automount,args2env,vfs_cache_mode=writes,config=/etc/rclone.conf,cache_dir=/var/cache/rclone 0 0

this results in rclone failing as it doesn't seem to handle the leading underscore of `_netdev` properly. When using this configuration I get an error message:

    [root@virt0 ~]# mount /var/lib/external/wasabi/public
    2021/11/11 19:22:51 Failed to parse command line: option name can't start with `-` or `_`

the actual line in my fstab:

    wasabi-public:stuff.public /var/lib/external/wasabi/public rclone rw,noauto,nofail,_netdev,x-systemd-automount,x-systemd.mount-timeout=30,args2env,vfs_cache_mode=writes,config=/etc/rclone/wasabi/rclone.conf,cache_dir=/var/cache/rclone,env.AWS_SHARED_CREDENTIALS_FILE=/etc/rclone/wasabi/aws/credentials,env.AWS_CONFIG_FILE=/etc/rclone/wasabi/aws/config,allow_other 0 0

changing it to:

```
wasabi-public:xyz.akdev.public /var/lib/external/wasabi/public rclone rw,noauto,nofail,x-systemd-automount,x-systemd.mount-timeout=30,args2env,vfs_cache_mode=writes,config=/etc/rclone/wasabi/rclone.conf,cache_dir=/var/cache/rclone,env.AWS_SHARED_CREDENTIALS_FILE=/etc/rclone/wasabi/aws/credentials,env.AWS_CONFIG_FILE=/etc/rclone/wasabi/aws/config,allow_other 0 0
```

allows the volume to be mounted successfully.

#### What is your rclone version (output from `rclone version`)

```
[root@virt0 ~]# rclone --version
rclone v1.57.0
- os/version: centos 8 (64 bit)
- os/kernel: 4.18.0-348.el8.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.2
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

answered above, centos 8 stream 64bit 

#### Which cloud storage system are you using? (e.g. Google Drive)

wasabi - s3 provider

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
mount /var/lib/external/wasabi/public
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

Adding `vvv` to the mount opts did not seem to create more logs than observed above. Seems like the main rclone process is not even getting executed.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Looking at the man mount page

       _netdev
              The  filesystem resides on a device that requires network access
              (used to prevent the  system  from  attempting  to  mount  these
              filesystems until the network has been enabled on the system).

This seems to be more of a tag for `mount`  rather than an actual kernel option so rclone should probably just ignore options starting with `_` - do you think that is correct @ivandeex 

The answers to this post seem to confirm that https://unix.stackexchange.com/q/169697/94054

**Comment by swordfish90s** [comment]
I confirm this issue on Rocky Linux 8.4,  removing `_netdev` [and `noauto`] allows `mount` to mount the volume.

**Comment by ivandeex** [comment]
> rclone should probably just ignore options starting with `_` - do you think that is correct?

@ncw
I don't know if it's correct.
Could you point to something more official than q/a site?
As a rule of thumb, this looks sensible.
Also such a rule will keep lists of valid mount options tokens from growing further.
At any rate such a rule must be documented.

**Comment by akdev1l** [comment]
@ncw @ivandeex if it helps, the expected behaviour is called out in the rclone docs:

>standard mount options like x-systemd.automount, _netdev, nosuid and alike are intended only for Automountd and ignored by rclone.

regarding `_netdev` I believe it comes from sysvinit, it's mostly used to indicate to the init system that the filesystem is networked such that it can be mounted after the network has come up.  You can see documentation confirming this here: [man systemd.mount\(5\)](https://www.freedesktop.org/software/systemd/man/systemd.mount.html#_netdev) and here: [ubuntu community wiki](https://help.ubuntu.com/community/Fstab)

I extracted this list from my system (Fedora 35)

```
akde@host $ man mount | sed -ne '/FILESYSTEM-INDEPENDENT MOUNT OPTIONS/,/FILESYSTEM-SPECIFIC MOUNT OPTIONS/p' | awk 'NF == 1 && !($1 ~ /^-/ || $1 ~ /\.$/)'
       async
       atime
       noatime
       auto
       noauto
       defaults
       dev
       nodev
       diratime
       nodiratime
       dirsync
       exec
       noexec
       group
       iversion
       noiversion
       mand
       nomand
       _netdev
       nofail
       relatime
       norelatime
       strictatime
       nostrictatime
       lazytime
       nolazytime
       suid
       nosuid
       silent
       loud
       owner
       remount
       ro
       rw
       sync
       user
       nouser
       users
       X-*
       x-*
       X-mount.mkdir[=mode]
       nosymfollow
```

**Comment by ncw** [comment]
> > rclone should probably just ignore options starting with `_` - do you think that is correct?
> 
> @ncw I don't know if it's correct. Could you point to something more official than q/a site?

I looked at the mount source code for linux...

I found `_netdev` defined here

https://github.com/util-linux/util-linux/blob/cb49adb703b2a0b0cb4dcad0b985e186149ce65c/libmount/src/optmap.c#L168

Which looks like the mount conmmand names all the mount options and doesn't take shortcuts :-(

I thought maybe we should just relax this check and allow options starting with `_` through. They will get passed to fusermount...

https://github.com/rclone/rclone/blob/4c93378f0e67fd65167abbd25e0b20d668102f1f/fs/mount_helper.go#L211-L213

However that doesn't work for `cmount` at least

```
$ ./rclone -vv cmount -o _netdev s3:rclone /mnt/tmp/
[snip]
fuse: unknown option `_netdev'
```

So I guess mount must filter out all the [user space mount options](https://github.com/util-linux/util-linux/blob/cb49adb703b2a0b0cb4dcad0b985e186149ce65c/libmount/src/optmap.c#L143) before passing them to fusermount as none of them seemed to work with fusermount directly, though I couldn't find out how/where this happens in the source.

So I suppose the minimal change would be to ignore `_netdev` in the options. We might consider some/all of the [user space mount options](https://github.com/util-linux/util-linux/blob/cb49adb703b2a0b0cb4dcad0b985e186149ce65c/libmount/src/optmap.c#L143)  too. That is putting more policy into rclone which is annoying, so keeping it to the minimum would be good!

**Comment by swordfish90s** [comment]
Is there a specific reason `_` is tested in `rclone/fs/mount_helper.go` ?
Given the parameters are being passed through to `mount`, leave the policy to it.

> @ncw @ivandeex if it helps, the expected behaviour is called out in the rclone docs:
>> standard mount options like x-systemd.automount, _netdev, nosuid and alike are intended only for Automountd and ignored by rclone.

It would seem that the intent was to ignore and pass through `_` options, but `mount_helper.go` didn't get the memo.

**Comment by ivandeex** [comment]
Thanks all.
I have enough data to produce a fix.

However, you will not see the fix in 1.58
If you are affected by this bug, please postpone using mount helper.
In the end, it's a brand new feature

My personal scheduling policy is FIFO
and I have had pretty large tasks planned for 1.58 before this report landed.
After that I plan to dedicate some time to review old PRs. We already have too much, and people are waiting for months.

Fixing new bugs in priority would make technical debt grow.
Thanks for understanding.

**Comment by ivandeex** [comment]
Thanks all.
I have enough data to produce a fix.

However, you will not see it fixed in 1.58
If you are affected by this bug, please postpone using mount helper.
In the end, it's a brand new feature

I have had pretty large tasks planned for 1.58 before this report landed.
Also I plan to dedicate some time to push through some very old PRs.
We already have too much, and people are waiting for months.

Fixing new bugs in LIFO order would make technical debt grow so my personal policy is FIFO
Thanks for understanding.

**Comment by ncw** [comment]
I think the fix for this is as simple as not checking for options starting with `_` and letting mount filter them out.

Can you give this a go? It worked in my simple tests.

[v1.58.0-beta.5892.1792d0c73.fix-5808-mount-netdev](https://beta.rclone.org/branch/fix-5808-mount-netdev/v1.58.0-beta.5892.1792d0c73.fix-5808-mount-netdev/) on branch [fix-5808-mount-netdev](https://github.com/rclone/rclone/tree/fix-5808-mount-netdev) (uploaded in 15-30 mins)

Is there any reason why that isn't a good fix @ivandeex ?

**Comment by ivandeex** [comment]
@ncw
It's not so simple because `--daemon` will convert `_xxx` to `-xxx` and pass to background process.
At least this needs a thorough unit test with combinations of `_` and `-` in synthetic options
and practical test with `--daemon`.
I think this can be postponed.

**Comment by ncw** [comment]
> It's not so simple because `--daemon` will convert `_xxx` to `-xxx` and pass to background process.

Ah, OK, I thought I must have missed something!

> At least this needs a thorough unit test with combinations of `_` and `-` in synthetic options and practical test with `--daemon`. I think this can be postponed.

We should at minimum take the `_netdev` out of the `/etc/fstab` example here:

https://github.com/rclone/rclone/blob/ba6730720d74f6ccc0031285cbc06b76cadfffbc/cmd/mountlib/help.go#L358

and here

https://github.com/rclone/rclone/blob/ba6730720d74f6ccc0031285cbc06b76cadfffbc/cmd/mountlib/help.go#L382

Or note that they don't work yet.

**Comment by ivandeex** [comment]
@ncw
Ok I will take care of this before 1.58

In the meantime I refreshed labels on pull requests submitted before July 2021.
Stale ones are marked by `waiting for reply`. They can be skipped for now. I posted reminders for people.
If they don't reply in 6 months, I'll close out the abandoned ones later.

The ones waiting for your review have you assigned.
If you don't have time to review this much code, I will share some burden this December.

**Comment by HarriL** [comment]
You may overcome the **_netdev** issue by using e.g. **fuse.rclone** in /etc/fstab:
` sftp1:subdir /mnt/data fuse.rclone rw,noauto,...`

Here are source code snippets of systemd that are executed during the bootup.  Hopefully, this shall solve the issue without code changes. 

In [systemd mount.c](https://github.com/systemd/systemd/blob/main/src/core/mount.c)
```
static bool mount_is_network(const MountParameters *p) {
        assert(p);

        if (fstab_test_option(p->options, "_netdev\0"))
                return true;

        if (p->fstype && fstype_is_network(p->fstype))
                return true;

        return false;
}
```
and in [systemd util.c](https://github.com/systemd/systemd/blob/main/src/basic/mountpoint-util.c)
```
bool fstype_is_network(const char *fstype) {
        const char *x;

        x = startswith(fstype, "fuse.");
        if (x)
                fstype = x;

        if (nulstr_contains(filesystem_sets[FILESYSTEM_SET_NETWORK].value, fstype))
                return true;

        /* Filesystems not present in the internal database */
        return STR_IN_SET(fstype,
                          "davfs",
                          "glusterfs",
                          "lustre",
                          "sshfs");
}
```

**Comment by ivandeex** [comment]
> You may overcome the **_netdev** issue by using e.g. **fuse.rclone** in /etc/fstab:

Thank you for insight. This deserves to be documented.

**Comment by HarriL** [comment]
After testings, this seems to be a bug or a missing feature depending on if there was an aim to support Linux boot time mounting or not. Here is how I came to my conclusion:

### 1. Rclone compatibility to Linux 

According to Linux systemd.mount manual the preferred mount is through /etc/fstab
`$ man systemd.mount`

> FSTAB
> 	Mount units may either be configured via unit files, or via /etc/fstab (see
> 	fstab(5) for details). Mounts listed in /etc/fstab will be converted into
> 	native units dynamically at boot and when the configuration of the system
> 	manager is reloaded. **In general, configuring mount points through /etc/fstab
> 	is the preferred approach.** See systemd-fstab-generator(8) for details about
> 	the conversion.

### 2. My test environment
The aim is to gather arguments the linux systemd command is sending to rclone during the boot phase.
OS: CentOS 7.9 

**2.1 Remote host:	remote1**
```
$ mkdir /tmp/test
$ chown user1:user1 /tmp/test
```

**2.2 Local host: local1**
```
$ mkdir /tmp/test
$ chown user1:user1 /tmp/test
```

### 3. Create bash script ”clone-mount”
Created a small ”logger” into /bin (not a safe but I am running  test in a ephemeral VMware guest)
`$ cat /bin/rclone-mount`

> #!/bin/bash
> echo "/bin/rclone  $*" >/tmp/test.log

`$ ls -al /bin/rclone*`

> -rwxr-xr-x. 1 root root 41893888 Dec  1 19:53 /bin/rclone
> -rwxr-xr-x. 1 root root       93 Dec  1 20:58 /bin/rclone-mount

### 4. Create rclone.conf
`$ cat /tmp/rclone.conf`

> [remote1]
> type = sftp
> host = remote1
> user = user1
> remote = /tmp/test
> key_file = /home/user1/.ssh/id_remote1
> known_hosts_file = /home/user1/.ssh/known_hosts
> md5sum_command = md5sum

### 5. Created minimal /etc/fstab mount directive
Note: the name  of a test script _rclone-mount_ 
`$ tail -1 /etc/fstab`

> remote1:/tmp/test /tmp/test fuse.rclone-mount config=/tmp/rclone.conf 0 0

### 6. Run test
The _mount -a_  uses directives from  _/etc/fstab_
`$ sudo mount -a`

### 7. Outcome
`$ cat /tmp/test.log`

> /bin/rclone remote1:/tmp/test /tmp/test -o rw,config=/tmp/rclone.conf,dev,suid

- Proper command should be: _/bin/rclone mount remote1:/tmp/test …_
- Note that rclone should handle properly /etc/fstab arguments e.g. ro (read-only) 

### 9. Analysis
- rclone is not  Linux distro /etc/fstab compatible

### 10. Conclusion 
- Mainstream linux distros use _systemd_ for mounts during the boot. And _systemd.mount_ man page proposes to use _/etc/fstab_ this should be fixed as an important feature or as an error.

### 11. Possible workaround  for this error
Create a script /bin/rclone-mount to handle this. This is a proposal and not tested one.
```
#!/bin/bash
# You must parse all arguments systemd sends from /etc/fstab during bootup
# This is not optimal, permanent nor secure solution
for argval in "$@"
do
	argval=<do something for each argument>
       arguments=”$arguments  $argval”
done
/bin/rclone mount --daemon $arguments
```

**Comment by HarriL** [comment]
Today I had time to test rclone mount in Linux. This is the proper method for rclone mount on Linux /etc/fstab.
Do not use the __netdev_ in /etc/fstab.

### Rclone mount on Linux  /etc/fstab
**1. Select mount method**
1.1 /etc/fstab
According to Linux systemd.mount manual the preferred mount method is trough /etc/fstab.
`$ man systemd.mount`

> FSTAB
> 	Mount units may either be configured via unit files, or via /etc/fstab (see
> 	fstab(5) for details). Mounts listed in /etc/fstab will be converted into
> 	native units dynamically at boot and when the configuration of the system
> 	manager is reloaded. **_In general, configuring mount points through /etc/fstab
> 	is the preferred approach._** See systemd-fstab-generator(8) for details about
> 	the conversion.

1.2 systemd
You may also use the systemd. It is not the scope of this guide. 

**2. Create mountable rclone link**
2.1 Select the directory for link
There is a document called The Filesystem Hierarchy Standard you should follow: https://refspecs.linuxfoundation.org/fhs.shtml
> Deciding what things go into "sbin" directories is simple: if a normal (not a system administrator) user will ever run it directly, then it must be placed in one of the "bin" directories. Ordinary users should not have to place any of the sbin directories in their path.

B/c rclone is installed in the /bin, it is convenient to do the link to /bin. (If you are an administrator you should use /usr/sbin if the rclone mount is not for users to run.)
2.2 Create link rclonefs
Rclone manual proposes a symbolic link. Let's do it:
```
$ sudo ln -s /bin/rclone /bin/rclonefs
$ ls -ld /bin/rclone*
-rwxr-xr-x. 1 root root 41893888 Dec  3 09:36 /bin/rclone
lrwxrwxrwx. 1 root root       11 Dec  3 10:29 /bin/rclonefs -> /bin/rclone
```

**3. Update /etc/fstab for test**
Add to the last line in /etc/fstab. Change path /tmp if necessary.
`remote1:/tmp/test /tmp/test fuse.rclonefs rw,nosuid,nodev,config=/tmp/rclone.conf,args2env,dir-cache-time=10s 0 0`

**4. Create a testing environment**
The aim is to gather the command line systemd is executing during the boot (init) phase. Change path /tmp if necessary.
4.1 Remote host:	remote1
```
$ sudo mkdir /tmp/test
$ ls -ald /tmp/test
drwxrwxr-x. 2 root root 17  3.12. 10:13 /tmp/test
```
4.2 Local host: local1
```
$ sudo mkdir /tmp/test
$ ls -ld /tmp/test
drwxrwxr-x. 2 root root 17  3.12. 10:13 /tmp/test
```
4.3 Create rclone.conf
```
$ cat /tmp/rclone.conf
[remote1]
type = sftp
host = remote1
user = user1
remote = /tmp/test
key_file = /tmp/id_remote1
known_hosts_file = /tmp/known_hosts
md5sum_command = md5sum
```

**5. Run a test**
5.1 Mount rclonefs
The mount -a  uses directives from  /etc/fstab
`$ sudo mount -a`
5.2 Check mount
$ mount
`eva1:/tmp/test on /tmp/test type fuse.rclone (rw,nosuid,nodev,relatime,user_id=0,group_id=0)`
or  
```
$ grep rclone /etc/mtab
eva1:/tmp/test on /tmp/test type fuse.rclone (rw,nosuid,nodev,relatime,user_id=0,group_id=0)
```
NOTE: in /etc/fstab you have fuse.rclonefs, but in /etc/mtab shows that it is fuse.rclone indeed that is running the mount.
5.3 Server local1
Open a terminal to local1 (ssh local1) and watch the /tmp/test:
`$ sudo watch ls -l /tmp/test`
5.4 Server remote1
Open another terminal to remote1 and do a test file
`$ sudo cp /etc/groups /tmp/test/testfile.txt`
5.5 Wait 5-10 seconds
You should see the testfile.txt on the terminal of the server local1. 

That's all folks!

**Comment by akdev1l** [comment]
Hi, I'm the original reporter for this issue

I may have some free time - if there is a defined plan for a solution I'd love to lend a hand.
