### ISSUE TITLE
Storj / tardigrade remote - new mv function - object moves not detected by rclone

### ISSUE THREAD

**Issue by fredcwells** [rclone/rclone#5812]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/storj-tardigrade-remote-new-mv-function-object-move-not-detected-by-rclone/27436?u=fredcwells

#### What is the problem you are having with rclone?

Storj DCS just introduced server side move (mv) function to their uplink CLI.
After uplink mv ... <source_object> <target_object>, Storj Web and uplink CLI reflect the changes, but rclone does not.

#### What is your rclone version (output from `rclone version`)

1.55.1
1.58.0-beta

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Linux, 64 bit (Fedora)

#### Which cloud storage system are you using? (e.g. Google Drive)

Storj DCS (tardigrade)

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

** Rclone command:
rclone ls -vv Storj-p1a1:backups/Duplicati/mypc1-Windows

** Corresponding Storj uplink command:
uplink ls --access **** sj://backups/Duplicati/mypc1-Windows/ 

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

** Rclone command output:
rclone ls -vv Storj-p1a1:backups/Duplicati/mypc1-Windows
<7>DEBUG : Using config file from "/home/fred/Backups/Borg/etc/.rclone.conf"
<7>DEBUG : rclone: Version "v1.55.1-DEV" starting with parameters ["rclone" "ls" "-vv" "Storj-p1a1:backups/Duplicati/mypc1-Windows"]
<7>DEBUG : rclone: systemd logging support activated
<7>DEBUG : Creating backend with remote "Storj-p1a1:backups/Duplicati/mypc1-Windows"
<7>DEBUG : FS sj://backups/Duplicati/mypc1-Windows: connecting...
<7>DEBUG : FS sj://backups/Duplicati/mypc1-Windows: connected: <nil>
<7>DEBUG : FS sj://backups/Duplicati/mypc1-Windows: ls -R ./
<7>DEBUG : FS sj://backups/Duplicati/mypc1-Windows: OBJ ls -R ./ ("backups", "Duplicati/mypc1-Windows")
<7>DEBUG : 5 go routines active

** Corresponding uplink command output:
OBJ 2021-11-03 22:16:36            0 Duplicati/mypc1-Windows/duplicati-b558e2d10c06744dab8305bfcb23f2885.dblock.zip
. . . . . .
OBJ 2021-08-03 21:58:15            0 Duplicati/mypc1-Windows/duplicati-b5686d613c7ec47c29be38092d69b91ab.dblock.zip

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by fredcwells** [comment]
Notably, Storj uplink command has same behavior when trying to list expanded objects, as...
_uplink ls --expanded ..._

**Comment by ncw** [comment]
Let us know what happens here - thanks.

**Comment by fredcwells** [comment]
Storj uplink version 1.46.3 appears to have resolved the issue.

I am able to successfully mv and access/list old and new objects across multiple paths with rclone, regardless how the object was created.

Reference: https://github.com/storj/storj/issues/4286

**Comment by ncw** [comment]
Great :-)

I'll close this issue now then - thank you for updating us.

**Comment by nickreserved** [comment]
Please reopen the issue.

I have mount a Storj storage with command `rclone.exe" mount --vfs-cache-mode=writes Storj_ntua1: Z:`
Now I am trying to rename file:
Z:/ntua/Οδηγίες.pdf
to
Z:/ntua/folder/Οδηγίες.pdf
where ntua is the Storj bucket.

It fails with
2022/01/25 20:43:41 ERROR : ntua/Οδηγίες.pdf: Dir.Rename error: Fs "FS sj://" can't rename files (no server-side Move or Copy)
2022/01/25 20:43:41 ERROR : IO error: Fs "FS sj://" can't rename files (no server-side Move or Copy)

**Comment by ncw** [comment]
@nickreserved are you trying with [the latest beta](https://beta.rclone.org/)?

**Comment by nickreserved** [comment]
With versions:
rclone-v1.57.0-windows-amd64
rclone-v1.58.0-beta.5960.a667e03fc-windows-amd64

both fail

**Comment by nickreserved** [comment]
Reproduce:
Just mount a storj storage, upload a file and try to RENAME it or MOVE it to another directory.
Copy works fine.

**Comment by ncw** [comment]
@nickreserved I think this is a different, but related problem. You are saying that Storj have now implemented `mv` in their api, but the tardigrade backend does not support it - is that correct?

If so can you make a new issue please?

Thanks
