### ISSUE TITLE
creating new remote with config_is_local=false gives localhost URL

### ISSUE THREAD

**Issue by wholtz** [rclone/rclone#5825]
#### What is the problem you are having with rclone?
Per the [docs on creating remotes](https://rclone.org/commands/rclone_config_create/), I am trying to make use of `config_is_local=false` to setup a Google Drive remote on a headless machine. However, a localhost URL is still displayed instead of the non-localhost URL I was expecting.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.57.0-DEV
- os/version: sles 15-SP1 (64 bit)
- os/kernel: 4.12.14-197.78_9.1.65-cray_shasta_c (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.16.9
- go/linking: static
- go/tags: none
```

I pulled this binary from conda-forge, where it was listed as v1.57.0

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Drive ("drive")

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone -vv config create mydrive drive config_is_local false`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2021/11/17 15:22:27 DEBUG : rclone: Version "v1.57.0-DEV" starting with parameters ["rclone" "-vv" "config" "create" "mydrive" "drive" "config_is_local" "false"]
2021/11/17 15:22:27 NOTICE: Config file "/home/my_username/.config/rclone/rclone.conf" not found - using defaults
2021/11/17 15:22:27 DEBUG : mydrive: config in: state="", result=""
2021/11/17 15:22:27 DEBUG : mydrive: config out: out=&{State:*oauth,teamdrive,, Option:<nil> OAuth:<nil> Error: Result:}, err=<nil>
2021/11/17 15:22:27 DEBUG : mydrive: config in: state="*oauth,teamdrive,,", result=""
2021/11/17 15:22:27 DEBUG : mydrive: config out: out=&{State:*oauth-confirm,teamdrive,, Option:<nil> OAuth:<nil> Error: Result:}, err=<nil>
2021/11/17 15:22:27 DEBUG : mydrive: config in: state="*oauth-confirm,teamdrive,,", result=""
2021/11/17 15:22:27 DEBUG : Override value found, choosing value "false" for state "*oauth-islocal,teamdrive,,"
2021/11/17 15:22:27 DEBUG : mydrive: config out: out=&{State:*oauth-islocal,teamdrive,, Option:<nil> OAuth:<nil> Error: Result:false}, err=<nil>
2021/11/17 15:22:27 DEBUG : mydrive: config in: state="*oauth-islocal,teamdrive,,", result="false"
2021/11/17 15:22:27 DEBUG : mydrive: config out: out=&{State:*oauth-remote,teamdrive,, Option:<nil> OAuth:<nil> Error: Result:}, err=<nil>
2021/11/17 15:22:27 DEBUG : mydrive: config in: state="*oauth-remote,teamdrive,,", result=""
2021/11/17 15:22:27 DEBUG : Auto confirm is set, choosing default "" for state "*oauth-do,teamdrive,,", override by setting config parameter "config_verification_code"
2021/11/17 15:22:27 DEBUG : mydrive: config out: out=&{State:*oauth-do,teamdrive,, Option:<nil> OAuth:<nil> Error: Result:}, err=<nil>
2021/11/17 15:22:27 DEBUG : mydrive: config in: state="*oauth-do,teamdrive,,", result=""
2021/11/17 15:22:27 DEBUG : Starting auth server on 127.0.0.1:53682
2021/11/17 15:22:27 NOTICE: If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth?state=BzX8fII5ZdBIvZQ85cQPZw
2021/11/17 15:22:27 NOTICE: Log in and authorize rclone for access
2021/11/17 15:22:27 NOTICE: Waiting for code...
^C
$
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by wholtz** [comment]
I did some further investigation. The command works as expected with v1.55.1 and is broken in v1.56.0. This is not too surprising given that there were substantial changes to the config system between those versions. Looks like @ncw did a lot of the config system re-work.

**Comment by ncw** [comment]
I'm not sure your exact workflow is possible any more with the new config system - it would be helpful if you could explain what you are doing.

What is happening is that the `config_is_local=false` setting is working - you can see that in the debug here

> Override value found, choosing value "false" for state "*oauth-islocal,teamdrive,,"

However because auto confirm is set then rclone doesn't stop to ask for the parameter.

> Auto confirm is set, choosing default "" for state "*oauth-do,teamdrive,,", override by setting config parameter "config_verification_code"

Auto confirm is set when you use `rclone config create` unless you use the `--all` flag - it is expected to be non interactive now - this was causing a problem with some uses of it asking the user questions unexpectedly.

The problem happens when rclone wants to supply you with a `config_verification_code` parameter and this defaults to "". This causes the webserver to be started as you saw.

If you could somehow know what the code was in advance then you could supply it with `config_verification_code XXXXX`.

Perhaps this workflow might work for you

```
$ rclone config create --non-interactive mydrive drive config_is_local false
{
	"State": "*oauth-do,teamdrive,,",
	"Option": {
		"Name": "config_verification_code",
		"Help": "Verification code\n\nGo to this URL, authenticate then paste the code here.\n\nhttps://accounts.google.com/o/oauth2/auth?access_type=offline\u0026client_id=XXX.apps.googleusercontent.com\u0026redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob\u0026response_type=code\u0026scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive\u0026state=XXX\n",
		"Provider": "",
		"Default": "",
		"Value": null,
		"ShortOpt": "",
		"Hide": 0,
		"Required": true,
		"IsPassword": false,
		"NoPrefix": false,
		"Advanced": false,
		"Exclusive": false,
		"DefaultStr": "",
		"ValueStr": "",
		"Type": "string"
	},
	"Error": "",
	"Result": ""
}
```

Read the URL from the JSON blob (note that it is JSON string encoded), get the user to get the token then run

```
$ rclone config create mydrive drive config_is_local false config_verification_code XXXX
```

Alternatively you could use the `--all` flag but you'll have to answer all the drive questions...

Note that it is intended the new config system will pass URLs for the configuring program to do something with at some point - that bit of the design isn't quite finished yet.

**Comment by wholtz** [comment]
Hi @ncw -- thanks for the extensive follow up. Unfortunately, the behavior of v1.55.1 was exactly what I wanted.

I have a project workflow that I will be onboarding people onto. Part of this onboarding is to configure rclone to have a google drive remote on a headless machine.  I'm trying to make the instructions as simple as possible, so I want to include all the parameters I can in a single command. With v1.55.1, the users copied and pasted:
```
rclone config create mydrive drive root_folder_id XXXXX-EXAMPLE_ID-XXXXX config_is_local false
```
then they copied the displayed (non-localhost) oauth URL to a web browser, got the auth code, and pasted that back into the same instance of rclone execution to complete the remote configuration. 

Of course, I could use the current version of rclone with `--non-interactive` and write a program that does several invocations of rclone to accomplish this same behavior. But I was hoping to not have to do that.

**Comment by ncw** [comment]
I think your best option would be to use the `--all` flag, but provide answers to all the questions rather than relying on the defaults. I think this should work for you

    rclone config create --all mydrive drive config_is_local false client_id "" client_secret "" scope "" root_folder_id "SOMETHING" service_account_file "" config_fs_advanced false

**Comment by wholtz** [comment]
Thanks. This is exactly what I needed. I didn't realize that I could still supply parameters and their values on the command line when using the `--all` flag. But I now do see that is stated in the docs.  In case anyone else tries this in the future, I also needed `config_change_team_drive false`. I added a tiny PR (#5830) to make the documentation for `--all` a little more explicit.

**Comment by ncw** [comment]
Thanks for the PR :-)

I tried very hard not to break existing workflows doing the config changes, but I knew since the existing workflow wasn't properly defined there would be bound to be a few.

I'm glad we've found a work-around though :-)
