### ISSUE TITLE
Can't report an error for write transaction on Windows

### ISSUE THREAD

**Issue by kalemas** [rclone/rclone#5827]
There is discussion on rclone forum:

https://forum.rclone.org/t/rclone-mount-synchonous-write-transaction/23771/33

and related discussion with CGoFuse developer, that ended with Can't Fix resolution:

https://github.com/billziss-gh/winfsp/issues/365

#### What is the problem you are having with rclone?

Problem from user point of view is that if there is a rclone mounted filesystem on windows, the error for write transaction is not propagated to user. So there is no guarantee that data was transferred, for example readonly file on remote webdav will never be overwritten.

#### What is your rclone version (output from `rclone version`)

1.55

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 10 x64 19*** build

On windows we can report error only before returning from write transaction so there is suggestion to do synchronous write operation rather then putting data into queue and upload on flush that cant report an error on windows.

**Comment by ncw** [comment]
If Bill can't come up with a fix for WinFSP then I don't think I can fix it in rclone unless you have any brilliant ideas @kalemas ?

**Comment by kalemas** [comment]
sorry, i started to read rclone forum after Bill closed issue on his tracker, and found your last suggestion to create an issue but there is already [rclone issue ](https://github.com/rclone/rclone/issues/5465) so i think we should close this.

there will no fix for winfsp, i do not see any option rather than report write error in write operation. We discussed that in thread that thread.
