### ISSUE TITLE
[Doc] Update Seafile version support

### ISSUE THREAD

**Issue by dimejo** [rclone/rclone#5837]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/seafile-8-support/27679

#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.57.0
- os/version: fedora 35 (64 bit)
- os/kernel: 5.14.14-300.fc35.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.2
- go/linking: static
- go/tags: none
```

#### What problem are you are trying to solve?
I want to use rclone with current versions of Seafile (8 and 9) but the documentation only mentions versions 6 and 7:

> Seafile versions 6.x and 7.x are all supported.

> Compatibility
> 
> It has been actively tested using the seafile docker image of these versions:
> 
>     6.3.4 community edition
>     7.0.5 community edition
>     7.1.3 community edition

#### How do you think rclone should be changed to solve that?
Please clarify if newer versions are currently untested or unsupported.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
@creativeprojects What version of seafile do we support? Do we need to update the docs / integration tests?

**Comment by creativeprojects** [comment]
It hasn't changed, we support 6 and 7: but it's only because I haven't updated mine 😞 

I would say it probably works with 8 or 9, but it's better if I run the tests on these versions.
I'll try locally first and send a PR with the new tests 👍🏻

**Comment by creativeprojects** [comment]
No I'm an idiot 😆 

The tests are using the docker container `seafileltd/seafile-mc` tagged `latest` so the integration tests have been running successfully with various new versions since I set it up.

Latest test run used version 8.0.7, because I suppose the build runner doesn't check for new docker images every time:
https://pub.rclone.org/integration-tests/current/seafile-backend.seafile-TestSeafile-1.txt

So @dimejo you can definitely use version 8 👍🏻 

In the meantime I'll try to run the tests on my machine with the version 9 and update the documentation accordingly 😄

**Comment by ncw** [comment]
The test runner updates all the images once a week I think.

I can do a manual update easily if you want.

**Comment by creativeprojects** [comment]
> I can do a manual update easily if you want.

@ncw yes that would be nice actually, thanks 🙇🏻‍♂️

**Comment by creativeprojects** [comment]
@ncw wait no, I just noticed the `latest` tag still points to 8.0.7, that explains it 😄

**Comment by dimejo** [comment]
> So @dimejo you can definitely use version 8 👍🏻

Great!

> In the meantime I'll try to run the tests on my machine with the version 9 and update the documentation accordingly 😄

I will leave this issue open then.

PS: Huge thanks for your work on rclone to both of you!

**Comment by dimejo** [comment]
Quick note: I had some difficulties syncing files from a pCloud account to a newly installed Seafile instance. I received lots of errors like 'file size does not match'. This happened with Seafile 8 and 9. Interestingly the errors went away when I enabled the 'go fileserver' (new in Seafile 9). Other than that rclone seems to run smoothly so far.

**Comment by dimejo** [comment]
> Interestingly the errors went away when I enabled the 'go fileserver' (new in Seafile 9).

Ignore that. I've started to see lots of errors with the 'go fileserver' aswell. 😞
