### ISSUE TITLE
Install script hangs with no output

### ISSUE THREAD

**Issue by xmready** [rclone/rclone#5839]
#### What is the problem you are having with rclone?

Install script hangs indefinitely with no output, must use CTRL+c to return to prompt. Both using the command from the website or downloading the script gets the same result. I tried changing the shebang to #!/usr/bin/bash with no luck. I searched the /usr/bin directory for rclone to see if the script did something, but it's not there.

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Ubuntu Linux 5.13.0-21-generic x86_64

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`curl https://rclone.org/install.sh | sudo bash`

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Please use the forums for generic support quetsions.

https://forum.rclone.org/

**Comment by xmready** [comment]
> Please use the forums for generic support questions.
> 
> https://forum.rclone.org/

Seemed like a bug to me, but ok, i'll try the forum

**Comment by animosity22** [comment]
Seems more like a very localized issue / server issue and we're happy to help you debug it on the forums.

**Comment by xmready** [comment]
> Seems more like a very localized issue / server issue and we're happy to help you debug it on the forums.

I downloaded the script directly, and ran it with sudo on afresh ubuntu install. I doubt it's a server issue. But I understand it may be localized in some way

**Comment by animosity22** [comment]
The script works fine.

```
 curl https://rclone.org/install.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4497  100  4497    0     0  12186      0 --:--:-- --:--:-- --:--:-- 12186

The latest version of rclone rclone v1.57.0 is already installed.
```

 Happy to help on the forum as I've suggested to help with your issue.

**Comment by xmready** [comment]
> The script works fine.
> 
> ```
>  curl https://rclone.org/install.sh | sudo bash
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  4497  100  4497    0     0  12186      0 --:--:-- --:--:-- --:--:-- 12186
> 
> The latest version of rclone rclone v1.57.0 is already installed.
> ```
> 
> Happy to help on the forum as I've suggested to help with your issue.

The .deb worked fine, I'm all good for now
