### ISSUE TITLE
union backend 'ro' attribute does not works as expected

### ISSUE THREAD

**Issue by pasnox** [rclone/rclone#5840]
#### What is the problem you are having with rclone?
Writing into 'ro' (read only) upstreams subfolders in an union backend is possible.
The documentation say to add attribute 'ro' in the remote end to make it read only.
While it make read only this folder, subfolders still get writable.
Subfolders should *not* be writable.

#### What is your rclone version (output from `rclone version`)
rclone v1.57.0
- os/version: libreelec 9.2.6-#201025
- os/kernel: 4.19.127 (armv7l)
- os/type: linux
- os/arch: arm
- go/version: go1.17.2
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Linux (rpi3)

#### Which cloud storage system are you using? (e.g. Google Drive)
Union, backed by 'mega' providers

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
No command, i'm using an application that save states in the document folder mounted by rclone.
Those states get uploaded to my providers.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Please use the forums for use case questions as you didn't include a command / log file or anything to look at as well.

We can figure out if it is a bug or a use question first.

https://forum.rclone.org/

Thanks!
