### ISSUE TITLE
A simple "example" backend module should be written

### ISSUE THREAD

**Issue by mgrzybek** [rclone/rclone#5846]
#### What problem are you are trying to solve?

I would like to write a backend module for Hitachi HCP REST API.

#### How do you think rclone should be changed to solve that?

Rclone should provide a simple module called *example* to help developers make new modules.

**Comment by animosity22** [comment]
That already exists:

https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#writing-a-new-backend

I'll close this out as answered.
