### ISSUE TITLE
rclone is not Linux /etc/fstab compatible as it should be eg. see man systemd.mount

### ISSUE THREAD

**Issue by HarriL** [rclone/rclone#5851]
After testings, this seems to be a bug or a missing feature depending on if there was an aim to support Linux boot time mounting or not. Here is how I came to my conclusion:

### 1. Rclone compatibility to Linux 

According to Linux systemd.mount manual the preferred mount is through /etc/fstab
`$ man systemd.mount`

> FSTAB
> 	Mount units may either be configured via unit files, or via /etc/fstab (see
> 	fstab(5) for details). Mounts listed in /etc/fstab will be converted into
> 	native units dynamically at boot and when the configuration of the system
> 	manager is reloaded. **In general, configuring mount points through /etc/fstab
> 	is the preferred approach.** See systemd-fstab-generator(8) for details about
> 	the conversion.

### 2. My test environment
The aim is to gather arguments the linux systemd command is sending to rclone during the boot phase.
OS: CentOS 7.9 

**2.1 Remote host:	remote1**
```
$ mkdir /tmp/test
$ chown user1:user1 /tmp/test
```

**2.2 Local host: local1**
```
$ mkdir /tmp/test
$ chown user1:user1 /tmp/test
```

### 3. Create bash script ”clone-mount”
Created a small ”logger” into /bin (not a safe but I am running  test in an ephemeral VMware guest)
`$ cat /bin/rclone-mount`

> #!/bin/bash
> echo "/bin/rclone  $*" >/tmp/test.log

`$ ls -al /bin/rclone*`

> -rwxr-xr-x. 1 root root 41893888 Dec  1 19:53 /bin/rclone
> -rwxr-xr-x. 1 root root       93 Dec  1 20:58 /bin/rclone-mount

### 4. Create rclone.conf
`$ cat /tmp/rclone.conf`

> [remote1]
> type = sftp
> host = remote1
> user = user1
> remote = /tmp/test
> key_file = /home/user1/.ssh/id_remote1
> known_hosts_file = /home/user1/.ssh/known_hosts
> md5sum_command = md5sum

### 5. Created minimal /etc/fstab mount directive
Note: the name  of a test script _rclone-mount_ 
`$ tail -1 /etc/fstab`

> remote1:/tmp/test /tmp/test fuse.rclone-mount config=/tmp/rclone.conf 0 0

### 6. Run test
The _mount -a_  uses directives from  _/etc/fstab_
`$ sudo mount -a`

### 7. Outcome
`$ cat /tmp/test.log`

> /bin/rclone remote1:/tmp/test /tmp/test -o rw,config=/tmp/rclone.conf,dev,suid

- Proper command should be: _/bin/rclone mount remote1:/tmp/test …_
- Note that rclone should handle properly /etc/fstab arguments e.g. ro (read-only) 

### 9. Analysis
- rclone is not  Linux distro /etc/fstab compatible

### 10. Conclusion 
- Mainstream linux distros use _systemd_ for mounts during the boot. And _systemd.mount_ man page proposes to use _/etc/fstab_. So this should be fixed as an important feature or as an error.

### 11. Possible workaround  for this error
Create a script /bin/rclone-mount to handle this. This is a proposal and not tested one.
```
#!/bin/bash
# You must parse all arguments systemd sends from /etc/fstab during bootup
# This is not optimal, permanent nor secure solution
for argval in "$@"
do
   argval=<do something for each argument>
   arguments=”$arguments  $argval”
done
/bin/rclone mount --daemon $arguments
```

_Originally posted by @HarriL in https://github.com/rclone/rclone/issues/5808#issuecomment-984028967_

**Comment by ivandeex** [comment]
I want to see https://github.com/rclone/rclone/wiki/rclone-mount-helper-script

**Comment by ivandeex** [comment]
Also in the official docs
https://rclone.org/commands/rclone_mount/#rclone-as-unix-mount-helper

We just miss `_netdev` option support.

**Comment by Mon-ius** [comment]
I see `sftp1:subdir /mnt/data rclone rw,noauto,nofail,_netdev,x-systemd.automount,args2env,vfs_cache_mode=writes,config=/etc/rclone.conf,cache_dir=/var/cache/rclone 0 0` for `/etc/fstab` is for `systemd` only, how to do with `openrc` based `/etc/fstab`.
