### ISSUE TITLE
Also in the official docs

### ISSUE THREAD

**Issue by HarriL** [rclone/rclone#5856]
Also in the official docs
https://rclone.org/commands/rclone_mount/#rclone-as-unix-mount-helper

We just miss `_netdev` option support.

_Originally posted by @ivandeex in https://github.com/rclone/rclone/issues/5851#issuecomment-984539137_

Could you kindly add this "Rclone mount on Linux /etc/fstab" to rclone documentation. This is fully tested and repeatable method with some linux guiding for Linux community.

https://github.com/rclone/rclone/issues/5808#issuecomment-985334170

**Comment by ivandeex** [comment]
![Screenshot_20211203-124035~2.jpg](https://user-images.githubusercontent.com/9028053/144580893-31354827-36e8-42f9-9a48-ee9ca05b61c6.jpg)

https://github.com/rclone/rclone/blob/v1.57.0/cmd/mountlib/help.go#L355

Feel free to submit a patch to improve and elaborate the paragraph

**Comment by animosity22** [comment]
This looks answered.
