### ISSUE TITLE
Make  a build for a Mac M1 (that's ARM64)

### ISSUE THREAD

**Issue by MarcelXia** [rclone/rclone#5857]
There are binary downloads for a lot of platforms, but the Mac ARM64 is missing.
I downloaded rclone and compiled it myself: it all works on this platform, so it must be a piece of cake :-)

**Comment by animosity22** [comment]
Closing this out as it already exists:

https://downloads.rclone.org/v1.57.0/rclone-v1.57.0-osx-arm64.zip

![image](https://user-images.githubusercontent.com/5088712/144609896-19dda38c-5e02-437f-a4c5-02904f09c398.png)
