### ISSUE TITLE
Feature request: globstar

### ISSUE THREAD

**Issue by urain39** [rclone/rclone#5860]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.57.0

#### What problem are you are trying to solve?
Use globstar (`**`) to match any subdirectory (including itself).

#### How do you think rclone should be changed to solve that?
rclone should support use `**` as a shortcut instead something like `{.,*,*/*,*/*/*}` (Actually this is not supported in rclone too, you should use `{,*/,*/*/,*/*/*/}` to make it like `**/`).

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by urain39** [comment]
I have checked the docs again, i notice the docs has `**`, but it doesn't like globstar in bash. The problem is rclone does **NOT** really look the `./` directory :(

**Comment by urain39** [comment]
In bash
```sh
$ ls -- **/*.jpg | wc -l
98
```

In rclone:
```sh
$ rclone ls . --include '**/*.jpg' | wc -l
0
```

**Comment by animosity22** [comment]
Rclone uses GO regular expressions which are not the same.

https://pkg.go.dev/regexp/syntax

and cloud file systems won't have a "./" as you are looking on a local machine.

**Comment by animosity22** [comment]
Answered a few days back.

If you need anything else, let me know.

Thanks!

**Comment by urain39** [comment]
> Rclone uses GO regular expressions which are not the same.
> 
> https://pkg.go.dev/regexp/syntax
> 
> and cloud file systems won't have a "./" as you are looking on a local machine.
> 
> ```
> felix@gemini:~$ rclone ls /home/felix/test
>         0 four.jpg
>         0 three.jpg
>         0 here/one
>         0 here/one.jpg
>        10 here/two
>         0 here/two.jpg
> felix@gemini:~$ rclone ls /home/felix/test --include '**/*.jpg'
>         0 here/one.jpg
>         0 here/two.jpg
> felix@gemini:~$ rclone ls /home/felix/test --include '*.jpg'
>         0 four.jpg
>         0 three.jpg
>         0 here/one.jpg
>         0 here/two.jpg
> ```

`./` directory is just for the convenience of explanation ` **/'.

In fact, what I want to say is that this pattern should match (directory) itself.

But considering that this is an extension rule, I won't force it...

Anyway, thanks reply :)

**Comment by animosity22** [comment]
There isn't a "./" in the ls output as it's not included so can't be matched.

**Comment by urain39** [comment]
> 

But empty equals the "./" in this point, that is what the shell did. Did I misunderstand something?

**Comment by urain39** [comment]
> There isn't a "./" in the ls output as it's not included so can't be matched.

But empty equals the "./" in this point, that is what the shell did. Or I misunderstand something?

**Comment by animosity22** [comment]
It's just the shell returning it.

```
felix@gemini:~/test$ rclone ls ./
        0 notexcluded/test
        0 Mailspring/Cache/test
        0 joplin-desktop/cache/testtwo
        0 .cache/blah
felix@gemini:~/test$ rclone ls /home/felix/test
        0 notexcluded/test
        0 .cache/blah
        0 Mailspring/Cache/test
        0 joplin-desktop/cache/testtwo
```

I'm not sure what point you are trying to make either as "./" doesn't exist for anything but a local file system as cloud remotes don't have that.

```
felix@gemini:~$ rclone ls DB:./
2021/12/10 11:32:04 ERROR : : error listing: directory not found
2021/12/10 11:32:04 Failed to ls with 2 errors: last error was: directory not found
```

**Comment by urain39** [comment]
@animosity22 I didn't say `./` existing in remote file systems, i just want to say `/path/to/**/*.jpg` should matches `/path/to/file.jpg` and `/path/to/another/file.jpg` in remote, just like it can matches `/path/to/file.jpg` and `/path/to/another/file.jpg` in local.

And you confused with `./` because i said:
> The problem is rclone does NOT really look the ./ directory :(  

But i am not really mean `./`, i mean the directory who are `**`'s parent.

Sorry for this :(

**Comment by animosity22** [comment]
Feel free to make a post on the forums and use the help and support template and fill everything out as that should work.

Thanks!

**Comment by urain39** [comment]
Ok.
