### ISSUE TITLE
Something like "du", to measure disk usage in cloud

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [rclone/rclone#5863]
I don't know how many other cloud providers are like this, but Google Drive does not provide a way to measure a folder's disk usage -- only files. It would be cool if rclone could do that.

I use version 1.57.0.

Thanks!

**Comment by animosity22** [comment]
rclone size
rclone about

Already do that.

For general questions, please use the forums or if you have a request, please fill out the template.

**Comment by JeffreyBenjaminBrown** [comment]
Thanks and sorry! 

(I had searched for "du", "disk", and "usage" in the docs. I may have only searched for "du" in the forum.)
