### ISSUE TITLE
Using rclone to access (anonymously) a shared dropbox folder

### ISSUE THREAD

**Issue by jypeter** [rclone/rclone#5864]
#### What is your current rclone version (output from `rclone version`)?

```
$ rclone version
rclone v1.57.0
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 4.4.0-19041-Microsoft (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.2
- go/linking: static
- go/tags: none
```

#### What problem are you are trying to solve?

I have spent time reading the rclone documentation and forum, ran some tests, used Google, read some dropbox documentation as well, and I have not found which `rclone` command line options or `rclone config` options to access anonymously the URL (a _public url_ ?) of a shared folder

I would like to know if this is possible (detailed use case below) and just not correctly documented, or not possible. The references I have found on that were not clear

As a test, I have created a subfolder on my sharebox account with 2 test files. I have also followed the required steps to use `rclone config` for creating a `db_jyp` dropbox configuration with **my dropbox credentials**

I can use rclone to access the content of **my sharebox account**
```
$ rclone lsl db_jyp:rclone_share_test
    49345 2021-12-09 15:45:42.000000000 rclone_test_someplot.pdf
       81 2021-12-09 15:30:38.000000000 readme_rclone.txt
```

I have then _shared_ the `rclone_share_test` folder, and created **a link that anybody can use in a browser to access the read-only content of this folder**: https://www.dropbox.com/sh/wxfcwife6gdzxfp/AAAAgG8Pp07nXUKqVpJFuFZFa?dl=0

People wanting to access the content of this folder will **not need a dropbox account and associated credentials**, they just need the URL

How can I tell rclone to access the content of https://www.dropbox.com/sh/wxfcwife6gdzxfp/AAAAgG8Pp07nXUKqVpJFuFZFa?dl=0 ?? Maybe it's just a matter of using rclone config and providing dummy credentials and the _sharing URL_. Or using rclone with the appropriate command line options and a `:dropbox:` backend. Or a combination of this, i.e. dummy credentials in the `config` file and providing the URL on the command line

It seems I'm almost there, but I don't know how to put things together !

#### How do you think rclone should be changed to solve that?

The (very nice) **documentation** should clearly say if what I need if not (yet) possible, or provide an example and a simple use case

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Those aren't really public URL though as they are javascript on the background.

So something like:

```
rclone ls --http-url https://www.dropbox.com/sh/wxfcwife6gdzxfp/AAAAgG8Pp07nXUKqVpJFuFZFa?dl=0 :http:
```

Returns nothing.

Where as something like this on a regular webserver works like:

```
rclone lsd --http-url https://beta.rclone.org :http:
```

And will spit out the directories.

To use the API for dropbox, I do believe you need to be authenticated as listed here:

https://www.dropbox.com/developers/reference/auth-types

So unless I'm missing something (always possible), I don't think you can do what you want since the links are not a normal webserver and javascript and to use the API, you need to be authenticated.

Best to start questions like this on the forums as well..

**Comment by jypeter** [comment]
OK, I would have thought that specifying `:dropbox:` as a backend (instead of `:http:` in your example) would trigger some _magical_ settings (e.g. provide some generic authentication), but when I do that, rclone complains about an `empty token` instead of automatically producing an appropriate one (if that is even possible)

```

$ rclone -vv ls --http-url https://www.dropbox.com/sh/wxfcwife6gdzxfp/AAAAgG8Pp07nXUKqVpJFuFZFa?dl=0 :dropbox:

2021/12/10 13:54:12 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "-vv" "ls" "--http-url" "https://www.dropbox.com/sh/wxfcwife6gdzxfp/AAAAgG8Pp07nXUKqVpJFuFZFa?dl=0" ":dropbox:"]
2021/12/10 13:54:12 DEBUG : Creating backend with remote ":dropbox:"
2021/12/10 13:54:12 DEBUG : Using config file from "[removed]/.config/rclone/rclone.conf"
2021/12/10 13:54:12 Failed to create file system for ":dropbox:": failed to configure dropbox: empty token found - please run "rclone config reconnect :dropbox:"
```

Note that if I use an existing dropbox profile in `.config/rclone/rclone.conf` **rclone ignores the URL specified with `--http-url`** and just lists what is my dropbox
```
$ rclone -vv ls --http-url https://www.dropbox.com/sh/wxfcwife6gdzxfp/AAAAgG8Pp07nXUKqVpJFuFZFa?dl=0 existing_db_config:

2021/12/10 14:02:54 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "-vv" "ls" "--http-url" "https://www.dropbox.com/sh/wxfcwife6gdzxfp/AAAAgG8Pp07nXUKqVpJFuFZFa?dl=0" "existing_db_config:"]
2021/12/10 14:02:54 DEBUG : Creating backend with remote "existing_db_config:"
2021/12/10 14:02:54 DEBUG : Using config file from "[removed]/.config/rclone/rclone.conf"
[... the content of my dropbox]
2021/12/10 14:02:54 DEBUG : 6 go routines active
2021/12/10 14:02:54 INFO  : Dropbox root '': Commiting uploads - please wait...
```

Well, I'm really out of my depth with this _oauth2_ token stuff

Unfortunately, I don't have much more time to spend on this, but maybe this issue will help someone later

If using rclone for anonymous access of shared dropbox folders is not possible (at the moment), this should probably be added to the [rclone dropbox page](https://rclone.org/dropbox/)

I have added some possible useful links related to my issue below
- [Access free folders and files with Dropbox.Api 4.9.4 in .Net](https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Access-free-folders-and-files-with-Dropbox-Api-4-9-4-in-Net/td-p/360378) from the dropbox community
- [How to force a shared link to download or render](https://help.dropbox.com/files-folders/share/force-download). This is kind of a dirty workaround, but you can at least bypass the web interface by using `wget dropbox_url?dl=1` instead of the default `wget dropbox_url?dl=0` to download a zip file of the dropbox content behind the URL...
- the official [dropbox Share files & folders](https://help.dropbox.com/files-folders/share) page

**Comment by animosity22** [comment]
http-url is for :http: remotes so that wouldn't do anything with a dropbox remote, drive remote, onedrive remote, etc.

**Comment by jypeter** [comment]
Oh, OK, thanks!

It makes sense that `--http-XXX` options are to be used with the `:http:` backend. It's nice to have something consistent

**Comment by animosity22** [comment]
This looks answered so closing it out.

**Comment by fmagin** [comment]
I am currently also trying to use rclone to access a dropbox folder someone shared with me and this issue and the documentation still leave me somewhat confused about whether this is possible or not. I currently do not have a dropbox account, but even if I create one, I am not sure how I would then access a folder someone shared via a link.

**Comment by animosity22** [comment]
@fmagin - Feel free to make a help and support post on the forum rather than commenting on a closed issue.
