### ISSUE TITLE
rclone trying to sync infinitely if there is IO error (symlink)

### ISSUE THREAD

**Issue by yur1xpp** [rclone/rclone#5869]
#### What is the problem you are having with rclone?
Whenever rclone encounter IO error, it keep trying infinitely (see screenshots below). The screenshot shows it's been doing that for 10mins, but it's not stopping. 27mins later it just proceed to 2/3 attempts and same behavior repeating, not sure is this a bug or intended design. (If this is a intended design, if there's anyway to reduce this?)

#### What is your rclone version (output from `rclone version`)
1.57

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Win 10 x64

#### Which cloud storage system are you using? (e.g. Google Drive)
OneDrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone sync --verbose --copy-links --drive-use-trash=false source destination:`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

The error:
![image](https://user-images.githubusercontent.com/34767893/145703352-52e95a1a-70e6-42a4-937b-703c0bf5cf1f.png)

Infinite syncing:
![image](https://user-images.githubusercontent.com/34767893/145703313-0063a0e5-48e1-4a2a-ac0d-d1861db7421f.png)

21mins later still persist:
![image](https://user-images.githubusercontent.com/34767893/145703483-f1583ea0-1b08-4734-8d3b-383528f0c541.png)

27mins later:
![image](https://user-images.githubusercontent.com/34767893/145703520-fc408ea0-ea1a-4ab9-af59-c5d857175516.png)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
There's no debug log so no idea what's going on. Would have been better to post on the forums first and ask..

**Comment by animosity22** [comment]
Closing out as no response. Please open a few forum post if you require asstiance.
