### ISSUE TITLE
Union: Can I choose specific upstream or the order of upstream for writing file

### ISSUE THREAD

**Issue by jmjoo** [rclone/rclone#5873]
#### What is your current rclone version (output from `rclone version`)?
v1.57

#### What problem are you are trying to solve?
I merged multiple upstreams for NAS dir and Object storage bucket using union.
If I just use default option to make union and I try to write file to the union, I confirmed that the file is written to the last upstream of upstream string.
but when I made some sub-dir in one of upstreams and file is written to the sub-dir of union, the file is written to the upstream which I made sub-dir.
It means that the target for file write can be changed where I don't expect.

#### How do you think rclone should be changed to solve that?
I think that if there is a option to choose one of upstream for writing file or to adjust the order of upstream for writing file, the problem will be solved.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Please use the forums for general use questions.

https://forum.rclone.org

You can check out the policies here:

https://rclone.org/union/#policy-descriptions

So you can pick the policy that works with what you want for your writing needs. Closing out..
