### ISSUE TITLE
Uploaded video to google drive cannot preview

### ISSUE THREAD

**Issue by cykac04** [rclone/rclone#5876]
#### What is the problem you are having with rclone?
```
Old version 1.51 can upload video to google drive as video with preview.
Version 1.57 uploaded video as kind of document and cannto preview.
```
![螢幕擷取畫面 2021-12-20 142311](https://user-images.githubusercontent.com/66108509/146721167-1402f81b-643b-4d54-bd60-3bdb9223b9ad.png)
```
{"Path":"0001.ts","Name":"0001.ts","Size":153972,"MimeType":"text/vnd.qt.linguist","ModTime":"2021-12-20T01:11:06.756Z","IsDir":false,"ID":"1tEpAY20nkdjwGr0eW3-casHcN8g65A7V"},
{"Path":"0002.ts","Name":"0002.ts","Size":93624,"MimeType":"video/mp2t","ModTime":"2021-12-20T01:11:06.802Z","IsDir":false,"ID":"1rfsw9OihQQg-HfsaL2mN-XFkApbnD-YY"},

```
#### What is your rclone version (output from `rclone version`)
```
~/rclone-v1.51.0-linux-amd64
⟩ ./rclone version
rclone v1.51.0
- os/arch: linux/amd64
- go version: go1.13.7
```

```
~/rclone-v1.51.0-linux-amd64
⟩ rclone version
rclone v1.57.0
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.11.0-38-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.2
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
```
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.11.0-38-generic (x86_64)
- os/type: linux
- os/arch: amd64
```

#### Which cloud storage system are you using? (e.g. Google Drive)
`Google Drive`

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone copy 0001.ts gdrive:/Rclone`

` ./rclone copy 0002.ts gdrive:/Rclone`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2021/12/20 14:25:02 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "-vv" "copy" 0001.ts" "gdrive:/Rclone"]
2021/12/20 14:25:02 DEBUG : Creating backend with remote "0001.ts"
2021/12/20 14:25:02 DEBUG : Using config file from "rclone.conf"
2021/12/20 14:25:02 DEBUG : fs cache: adding new entry for parent of "0001.ts", "/"
2021/12/20 14:25:02 DEBUG : Creating backend with remote "gdrive:/Rclone"
2021/12/20 14:25:03 DEBUG : fs cache: renaming cache item "gdrive:/Rclone" to be canonical "gdrive:Rclone"
2021/12/20 14:25:03 DEBUG : 0001.ts: Size and modification time the same (differ by -704.1µs, within tolerance 1ms)
2021/12/20 14:25:03 DEBUG : 0001.ts: Unchanged skipping
2021/12/20 14:25:03 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Checks:                 1 / 1, 100%
Elapsed time:         1.1s

2021/12/20 14:25:03 DEBUG : 4 go routines active
```

```
2021/12/20 14:26:01 DEBUG : rclone: Version "v1.51.0" starting with parameters ["./rclone" "-vv" "copy" 0002.ts" "gdrive:/Rclone"]
2021/12/20 14:26:01 DEBUG : Using config file from "rclone.conf"
2021/12/20 14:26:02 DEBUG : 0002.ts: Size and modification time the same (differ by -547.6µs, within tolerance 1ms)
2021/12/20 14:26:02 DEBUG : 0002.ts: Unchanged skipping
2021/12/20 14:26:02 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Checks:                 1 / 1, 100%
Elapsed time:         0.0s

2021/12/20 14:26:02 DEBUG : 5 go routines active
2021/12/20 14:26:02 DEBUG : rclone: Version "v1.51.0" finishing with parameters ["./rclone" "-vv" "copy" "0002.ts" "gdrive:/Rclone"]
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment]
What is happening here is that rclone relies on your operating system to provide MIME type, and your OS reports `text/vnd.qt.linguist` for file extension `.ts`. This comes from file `/etc/mime.types` on linux. In previous versions of rclone it forced a default type for the most common extensions, and would then change the mime type to `video/mp2t`. This functionality was intended to just augment the built-in mime database for environments that did not have a proper database (such as Termux on Android), but it had the unintended effect of overriding existing settings. This was changed in one of the newer versions of rclone, and the reason you see the difference.

So, to sum up, rclone relies on the OS to supply correct MIME information for local files. And therefore, if it does not, you have to fix it there, e.g. modify the mime database in your system. First hit on google lead me to this, which may lead you closer to a workaround? https://stackoverflow.com/questions/14230396/ts-files-always-get-recognized-as-text-vnd-trolltech-linguist-and-never-as-vide

PS: I have investigated the possibility to extend rclone with a feature for overriding the default/OS mime database, which probably could have been usefull here. At the time, I did not go through with this idea and moved to other topics, but may pick it up again at a later time...

**Comment by cykac04** [comment]
> What is happening here is that rclone relies on your operating system to provide MIME type, and your OS reports `text/vnd.qt.linguist` for file extension `.ts`. This comes from file `/etc/mime.types` on linux. In previous versions of rclone it forced a default type for the most common extensions, and would then change the mime type to `video/mp2t`. This functionality was intended to just augment the built-in mime database for environments that did not have a proper database (such as Termux on Android), but it had the unintended effect of overriding existing settings. This was changed in one of the newer versions of rclone, and the reason you see the difference.
> 
> So, to sum up, rclone relies on the OS to supply correct MIME information for local files. And therefore, if it does not, you have to fix it there, e.g. modify the mime database in your system. First hit on google lead me to this, which may lead you closer to a workaround? https://stackoverflow.com/questions/14230396/ts-files-always-get-recognized-as-text-vnd-trolltech-linguist-and-never-as-vide
> 
> PS: I have investigated the possibility to extend rclone with a feature for overriding the default/OS mime database, which probably could have been usefull here. At the time, I did not go through with this idea and moved to other topics, but may pick it up again at a later time...

Thank you for your reply. The `/etc/mime.types` does have `video/MP2T`. But I find some `.ts` download by wget or ffmpeg have mime type of `application/octet-stream`. It seems the OS does not overrides the file settings?

**Comment by albertony** [comment]
> The `/etc/mime.types` does have `video/MP2T`

That is strange. Where does the `text/vnd.qt.linguist` come from then.. Maybe I'm confusing local filesystem with google drive or something..

What if you run `file --mime-type 0001.ts` or something (I'm not native Linux-er, so perhaps you know a better way), can you confirm what mime type it reports?
And then with `rclone lsjson` against same file *in local file system*, what does it report?
And then `rclone lsjson` against your google drive?

**Comment by albertony** [comment]
> file --mime-type 0001.ts `0001.ts: application/octet-stream`

> file --mime-type ./210703_172753.ts `./210703_172753.ts: video/MP2T`

That confuses me (different mime type for same file extension)! But maybe the `fìle` command does not simply look up into mime database, but instead using some magic - literaly: https://linux.die.net/man/1/file

If you have the `mimetype` command, maybe you can try that instead?

(Sorry for the chaotic support from my part, I'm trying my best until a linux expert jumps in).

**Comment by cykac04** [comment]
> > file --mime-type 0001.ts `0001.ts: application/octet-stream`
> 
> > file --mime-type ./210703_172753.ts `./210703_172753.ts: video/MP2T`
> 
> That confuses me (different mime type for same file extension)! But maybe the `fìle` command does not simply look up into mime database, but instead using some magic - literaly: https://linux.die.net/man/1/file
> 
> If you have the `mimetype` command, maybe you can try that instead?
> 
> (Sorry for the chaotic support from my part, I'm trying my best until a linux expert jumps in).

mimetype 0001.ts
`0001.ts: text/vnd.qt.linguist`

mimetype ./210703_172753.ts
`./210703_172753.ts: text/vnd.qt.linguist`

I would think `file` command gets the real one as only it gets different results.

**Comment by albertony** [comment]
Thanks.

That was useful information. I'm still leaning towards my [first reply](https://github.com/rclone/rclone/issues/5876#issuecomment-997871808) being the explanation here, although I do not yet have a clear view of the complete case...

I see now that mimetype command with argument `--all` lists both information from mime database as well as information from the "magic" that the file command uses, but that is not so important now, I think.

Previously you mentioned:

> The /etc/mime.types does have video/MP2T

I think an explanation here is that you have another file part of your mime database overriding this with `text/vnd.qt.linguist`.

This is 

> But I find some .ts download by wget or ffmpeg have mime type of application/octet-stream. It seems the OS does not overrides the file settings?

How did you get the mime type of the mentioned files? I would expect same version of rclone with lsjson against local filesystem to always give the same mime type for all files with same extension, and in v1.57 to always give the value from your mime database (`text/vnd.qt.linguist`), while in v1.51 always the hard coded default (`video/MP2T`).

**Comment by cykac04** [comment]
> Thanks.
> 
> That was useful information. I'm still leaning towards my [first reply](https://github.com/rclone/rclone/issues/5876#issuecomment-997871808) being the explanation here, although I do not yet have a clear view of the complete case...
> 
> I see now that mimetype command with argument `--all` lists both information from mime database as well as information from the "magic" that the file command uses, but that is not so important now, I think.
> 
> Previously you mentioned:
> 
> > The /etc/mime.types does have video/MP2T
> 
> I think an explanation here is that you have another file part of your mime database overriding this with `text/vnd.qt.linguist`.
> 
> This is
> 
> > But I find some .ts download by wget or ffmpeg have mime type of application/octet-stream. It seems the OS does not overrides the file settings?
> 
> How did you get the mime type of the mentioned files? I would expect same version of rclone with lsjson against local filesystem to always give the same mime type for all files with same extension, and in v1.57 to always give the value from your mime database (`text/vnd.qt.linguist`), while in v1.51 always the hard coded default (`video/MP2T`).

I found something different from `/etc/mime.types`

from `/usr/share/mime/packages/freedesktop.org.xml`:
```
 <mime-type type="text/vnd.qt.linguist">
    <comment>message catalog</comment>
...
    <sub-class-of type="application/xml"/>
    <magic>
      <match type="string" value="&lt;TS" offset="0:256"/>
    </magic>
    <glob pattern="*.ts"/>
    <alias type="application/x-linguist"/>
    <alias type="text/vnd.trolltech.linguist"/>
  </mime-type>
```

**Comment by albertony** [comment]
Bingo. That was the missing piece.

> So, to sum up, rclone relies on the OS to supply correct MIME information for local files. And therefore, if it does not, you have to fix it there, e.g. modify the mime database in your system.

Do you agree?

**Comment by big-F** [comment]
centos7.9

**edit** /usr/share/mime/packages/freedesktop.org.xml
**delete this code**
```
<mime-type type="text/vnd.trolltech.linguist">
...
<glob pattern="*.ts"/>
...
</mime-type>
```
shell execute command
**update-mime-database /usr/share/mime**

I also did one more step, I downloaded this rpm file and extracted it to get **mime.types**
http://mirror.centos.org/centos/7/os/x86_64/Packages/mailcap-2.1.41-2.el7.noarch.rpm
Use this command to decompress the rpm file：**rpm2cpio mailcap-2.1.41-2.el7.noarch.rpm | cpio -div**
**edit** mime.types
Replace "text/vnd.trolltech.linguist			ts" with "video/mp2t			ts"
**Move** the mime.types file to /etc/

**Reboot system**

I solved the problem, thank you all
