### ISSUE TITLE
Feature request:  add quit to interactive dedupe

### ISSUE THREAD

**Issue by BobBagwill** [rclone/rclone#5881]
#### Output of `rclone version`

rclone v1.50.2
- os/arch: linux/amd64
- go version: go1.13.6

#### Describe the issue

I don't know how to quit gracefully from interactive dedupe.

How about adding quit <q/s/k/r> to the prompt?

**Comment by animosity22** [comment]
Just hit control c and exit out.

**Comment by albertony** [comment]
> Just hit control c and exit out.

I do agree with that!
Still, I found it easy enough to add a quit option, and I think it improves the ux a tiny bit, and is consistent with config commands where there is a quit option.. So I created a PR adding it.
