### ISSUE TITLE
google Drive issue

### ISSUE THREAD

**Issue by TomaszMyszak** [rclone/rclone#5886]
#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by TomaszMyszak** [comment]
Hello,
i'm trying to synch onedrive to google drive. I connect corectly to onedrive rclone bud they don't wona connect to google drive. I use your instuction from this site:
https://rclone.org/drive/

but answer form server google is: 

bug '404'

can you have other accurate instructions?

thenks for help

**Comment by animosity22** [comment]
Makes forum post.

**Comment by TomaszMyszak** [comment]
this is not issue, this is bug. Because rclone work corectly but you mus have change instrucions..

**Comment by animosity22** [comment]
Please make a forum post.

https://forum.rclone.org/
