### ISSUE TITLE
Suggestion: delete MD5 duplicates by path location ?

### ISSUE THREAD

**Issue by doplu** [rclone/rclone#589]
Hello,

Suggestion: delete MD5 duplicates by path location ?

_Example :_ Using dedupe (http://rclone.org/docs/) between 2 folders: 
ACD/photos/
and
ACD/new_photos/

Like the software "Duplicate Cleaner" (http://www.duplicatecleaner.com/), add an option "Select by location: preserve the files in this path" : "ACD/photos/"
so it will delete duplicates (MD5 checks) only in "ACD/new_photos/"

See image: 
![2016-07-16_172858duplicatecleaner](https://cloud.githubusercontent.com/assets/14937727/16895717/8179dc34-4b7f-11e6-99d0-6b9abf21538b.jpg)

Thanks in advance ;)

**Comment by ncw** [comment]
I see what you mean.  A nice idea!

**Comment by seonghobae** [comment]
I hope this feature is implementing to the rclone. Moreover, it can make redirects automatically in Linux, That will be happy. I feel pain with the duplicated files what makes -L flag, on swift object storage. Tons of duplicates makes waste storage spaces.

**Comment by ivandeex** [comment]
@ncw

`rclone dedupe --by-hash` has long been implemented
If a concrete remote should be preferred it can be put first on command line with the flag `--dedupe-mode first`

Let's close this.
Do I miss something?

https://rclone.org/commands/rclone_dedupe/
> --by-hash is passed in then dedupe will find files with duplicate hashes instead
