### ISSUE TITLE
Corrupted encrypted file with disabled vfs-cache

### ISSUE THREAD

**Issue by avently** [rclone/rclone#5895]
#### What is the problem you are having with rclone?
Hello. Today I tried to test how Rclone works. First of all I created webdav connection and another connection with encryption that used the first connection.
I started Rclone with the default options:
```
rclone mount CryptRemote: ~/Documents/crypt
```
Then I created a file inside `~/Documents/crypt` named `Test.xlsx` by using OnlyOffice DesktopEditors. Document had just some non-important text in it. After I saved it, I saw logs:
```
2022/01/02 23:01:02 NOTICE: Encrypted drive 'CryptRemote:': --vfs-cache-mode writes or full is recommended for this remote as it can't stream
2022/01/02 23:01:59 ERROR : Test.xlsx: WriteFileHandle: Can't open for write without O_TRUNC on existing file without --vfs-cache-mode >= writes
2022/01/02 23:02:09 ERROR : Test.xlsx: WriteFileHandle: Can't open for write without O_TRUNC on existing file without --vfs-cache-mode >= writes
2022/01/02 23:02:12 ERROR : Test.xlsx: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes
2022/01/02 23:02:13 ERROR : Test.xlsx: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes
2022/01/02 23:02:14 ERROR : Test.xlsx: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes
2022/01/02 23:02:15 ERROR : Test.xlsx: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes
2022/01/02 23:02:16 ERROR : Test.xlsx: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes
2022/01/02 23:02:17 ERROR : Test.xlsx: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes
2022/01/02 23:02:18 ERROR : Test.xlsx: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes
2022/01/02 23:02:19 ERROR : Test.xlsx: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes
2022/01/02 23:02:20 ERROR : Test.xlsx: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes
2022/01/02 23:02:21 ERROR : Test.xlsx: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes
2022/01/02 23:02:22 ERROR : Test.xlsx: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes
2022/01/02 23:02:23 ERROR : Test.xlsx: WriteFileHandle.Write: can't seek in file without --vfs-cache-mode >= writes
2022/01/02 23:02:51 ERROR : Test.xlsx: WriteFileHandle: Can't open for write without O_TRUNC on existing file without --vfs-cache-mode >= writes
```

I closed the file in the editor. File size was too small, 1.5 KB but should be around 6 KBs. I opened the file again and it wasn't recognized. Instead the editor tried to open it as CSV and I saw this text inside:
```
PK
--



```
You can easily reproduce the process if you want to.

I did some tests with --vfs-cache-mode=writes and looks like no file corruptions happens. I noticed this error twice, not sure why:
```
2022/01/02 23:55:09 ERROR : Testi.xlsx: ReadFileHandle.Read error: low level retry 1/10: unexpected EOF
2022/01/02 23:55:15 ERROR : Test.xlsx: ReadFileHandle.Read error: low level retry 2/10: unexpected EOF
2022/01/02 23:55:17 ERROR : Test.xlsx: ReadFileHandle.Read error: low level retry 3/10: unexpected EOF
2022/01/02 23:55:20 ERROR : Test.xlsx: ReadFileHandle.Read error: low level retry 4/10: unexpected EOF
2022/01/02 23:55:24 ERROR : Test.xlsx: ReadFileHandle.Read error: low level retry 5/10: unexpected EOF
2022/01/02 23:55:29 ERROR : Test.xlsx: ReadFileHandle.Read error: low level retry 6/10: unexpected EOF
2022/01/02 23:55:30 ERROR : Test.xlsx: ReadFileHandle.Read error: low level retry 7/10: unexpected EOF
2022/01/02 23:55:34 ERROR : Test.xlsx: ReadFileHandle.Read error: low level retry 8/10: unexpected EOF
2022/01/02 23:55:45 ERROR : Test.xlsx: ReadFileHandle.Read error: low level retry 9/10: unexpected EOF
2022/01/02 23:55:48 ERROR : Test.xlsx: ReadFileHandle.Read error: low level retry 10/10: unexpected EOF
2022/01/02 23:55:51 ERROR : Test.xlsx: ReadFileHandle.Read error: unexpected EOF
```

After doing this experiment I'm a little bit worring about possible file corruptions in the future because I will store some important files in encrypted state. The question is how to prevent possible file corruptions when using `mount`? Am I on a safe side if I use `--vfs-cache-mode=writes` or there are some unknown problems can still happen? Does Rclone has option to backup the file before write like it has in `copy` command? I would like to have such option while still using `mount`.

#### What is your rclone version (output from `rclone version`)
rclone v1.57.0
- os/version: arch 21.1.6 (64 bit)
- os/kernel: 5.10.70-1-MANJARO (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.5
- go/linking: dynamic
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Manjaro, 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
WebDav + crypt

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone mount CryptRemote: ~/Documents/crypt

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Missing rclone.conf
Missing debug.log

**Comment by avently** [comment]
@animosity22 uploaded both files
[log.txt](https://github.com/rclone/rclone/files/7804280/log.txt)
[rclone.conf.txt](https://github.com/rclone/rclone/files/7804288/rclone.conf.txt)

Rename this one to Test.xlsx if you want to try to open it in OnlyOffice or in any other app:
[Test.xlsx.txt](https://github.com/rclone/rclone/files/7804303/Test.xlsx.txt)

**Comment by animosity22** [comment]
The log shows your writes are seeking and you need writes on. 

```
2022/01/04 00:56:57 DEBUG : Test.xlsx: WriteFileHandle.Flush unwritten handle, writing 0 bytes to avoid race conditions
2022/01/04 00:56:57 ERROR : Test.xlsx: WriteFileHandle: Can't open for write without O_TRUNC on existing file without --vfs-cache-mode >= writes
```

**Comment by animosity22** [comment]
You'd scrape the rclone log for errors to see what's going on with the mount if you do have issues in terms of writing.

All the behavior you've described is expected so I'm going to close this out as answered.

For use questions, please use the forums.
