### ISSUE TITLE
Switch to hanwen/go-fuse library

### ISSUE THREAD

**Issue by wloot** [rclone/rclone#5896]
Rclone currently uses the `bazil/fuse` library on linux, and `billziss-gh/cgofuse` on windows and mac. Unfortunately, neither of them seems to be actively maintained: `bazil/fuse` seems dead, `billziss-gh/cgofuse` has no plan to support fuse 3.
The latest fuse protocol can bring many improvements to rclone, for example, max_pages can greatly improve read and write performance.
Currently we have preliminary support for `hanwen/go-fuse`, which is mount2. Is there any plans for further development on it?

**Comment by albertony** [comment]
### Regarding:

> billziss-gh/cgofuse has no plan to support fuse 3.

Well, the author *does* say this:

> I agree that the porting work to FUSE3 will have to be done eventually

(https://github.com/billziss-gh/cgofuse/issues/50)

He mentions that a challenge is that FUSE3 is not completely cross-platform to the same extent as FUSE2. I wonder how hanwen handles this...

### Regarding:

> Currently we have preliminary support for hanwen/go-fuse, which is mount2. Is there any plans for further development on it?

Quite the opposite, it seems:

> mount2 I don't care about. I'd quite like to remove it entirely as I think it is a dead end.

(https://github.com/rclone/rclone/pull/5571#issuecomment-913007970)

**Comment by wloot** [comment]
> Well, the author _does_ say this:
> 
> > I agree that the porting work to FUSE3 will have to be done eventually

The author actually said this last year(27 Jan 2021), and there is no any development in the past year.

**Comment by ivandeex** [comment]
bilziss has been the most stable one, least buggy, the only one working on win/mac
hanwen has brought us too much pain, deadlocks and stuck tests, heaps of workarounds throughout code
bazil lies in the middle

what do you want? buggy fuse3 or stable fuse2?

**Comment by ivandeex** [comment]
bilziss has been the most stable one, least buggy, the only one working on win/mac
hanwen has brought us too much pain, deadlocks and stuck tests, heaps of workarounds throughout code
bazil lies in the middle

what do you want? buggy fuse3 because "3" or stable fuse2 because "stable"?

**Comment by ivandeex** [comment]
At any rate, if someone is ready to invest time and make all stress tests pass with hanwen fuse library... No problem :)

I think we have exchanged views on this possible direction of development
and this quick discussion can be marked as done.

**Comment by wloot** [comment]
> > max_pages can greatly improve read and write performance.
> 
> rclone's bottleneck has always been in the network, not fuse.

Bcos I am getting too much iowait during read/write workload, I thought it may related to fuse lib.

**Comment by ivandeex** [comment]
Too much compared to what?
If you use a cloud storage remote then the data path is
```
program <-> mount <-> kernel <-> fuse <-> rclone <-> network <-> cloud
```
The high `iowait` you see between program and mount is just a consequence of network delays between rclone and cloud.

To get to correct conclusions you should take network out of equation. Create a local remote

```
[test]
type=alias
remote=/some/local/dir
```

and compare iowait of `rclone mount test:` vs `rclone mount2 test:` vs `rclone cmount test:`. Now you can compare hanwen w/ bilziss.
