### ISSUE TITLE
Set additional headers using --header-upload and --header-download

### ISSUE THREAD

**Issue by pquerna** [rclone/rclone#59]
For example if your s3 bucket is being served behind CloudFront, it is common to set `Cache-Control: max-age=300,public` to reduce cache TTL, or setting `Content-Encoding: gzip` for pre-compressed files.

`s3cmd` has the `--add-header` parameters for this purpose

### Backends which have and haven't got support for `--header-upload` and `--header-download`

Backends which are ~~crossed out~~ are not HTTP based and can't support the feature

- [ ] ~~alias~~
- [ ] amazonclouddrive
- [ ] azureblob
- [x] b2
- [x] box
- [ ] ~~cache~~
- [ ] ~~chunker~~
- [ ] ~~crypt~~
- [ ] drive
- [ ] dropbox
- [x] fichier
- [ ] ~~ftp~~
- [x] googlecloudstorage
- [x] googlephotos
- [x] http
- [x] hubic
- [x] jottacloud
- [ ] koofr
- [ ] ~~local~~
- [ ] mailru
- [ ] mega
- [ ] ~~memory~~
- [x] onedrive
- [x] opendrive
- [x] pcloud
- [x] premiumizeme
- [x] putio
- [ ] qingstor
- [x] s3
- [ ] ~~sftp~~
- [x] sharefile
- [x] sugarsync
- [x] swift
- [ ] ~~union~~
- [x] webdav
- [x] yandex

**Comment by ncw** [comment]
I see.  Wouldn't be too hard!  I'd probably make an `--add-header` flag which all the remote storage systems could use not just s3.

Thanks for the suggestion.

**Comment by schickling** [comment]
+1

**Comment by ncw** [comment]
**NB** this additional header only wants to be set on the operation that actually uploaded the file - not on all the other operations (eg listing directories etc)

**Comment by nodughere** [comment]
Agreed.  

The headers should be a dictionary.

Example rclone with Swift
rclone --add-header={'x-meta-object-my-favorite-car':'ford mustang', 'X-Delete-After': 3600} copy /home/doug/data/ SwiftCluster:container

This command would add metadata and allow objects to auto delete in 1 hour as an example

Example rclone with S3
rclone --add-header={'x-amz-meta-my-favorite-car':'ford mustang'} copy /home/doug/data/ S3Cluster:bucket

**Comment by wouterv** [comment]
I have a suggestion for local file system copy actions:

What whould help with backups is to have an additional header file next to the actual file with key=value file, or a json file containing the meta data. 

And with that to use those files when uploading to a cloud provider. 

Perhaps with an extra option --copy-headers=true --head-file-extension=.header or something for both copying from/to a local file system.

**Comment by treyd** [comment]
+1 for this request, although I would like the additional header to also be set on all requests.  The reason behind this is there is some middleware that uses headers to control functionality, and it would be great if we can have rclone do this as well

**Comment by ncw** [comment]
I'm all in favour of a general purpose option to add headers...  Anyone fancy sending in a PR?

**Comment by fortunto2** [comment]
I'm sorry, but when the scheduled implementation?

**Comment by ncw** [comment]
rclone now has all the machinery to make this relatively straight forward.

I would implement two flags which could be repeated

  --upload-header "Header: String"
  --download-header "Header: String"

Which would be applied to Uploads (specifically Object.Update or Fs.Put) or Downloads (specifically Object.Open).

These would need to be applied as options (there is a general purpose HTTPOption already). A bit of work would need to be done in each remote to make this work.  The options would be applied in the Copy primitive (and possibly elsewhere - this might need factoring).

**Comment by peixotorms** [comment]
+1

**Comment by browny** [comment]
+1

**Comment by ducktype** [comment]
+1

**Comment by joakimohman** [comment]
+1

**Comment by onnozweers** [comment]
+1

**Comment by bjcone** [comment]
+1

**Comment by TrueShutDown** [comment]
+1

**Comment by guillaumechereau** [comment]
+1

**Comment by servocoder** [comment]
At the moment metadata headers is supported in both AWS S3 and Digital Ocean Spaces. Maybe it's true for some other storage providers. So it's not only about S3.

Surprised this package hasn't had copy/add metadata headers feature implemented yet.

**Comment by ncw** [comment]
Does anyone want to work on this?  Very happy to give guidance?

**Comment by develohpanda** [comment]
> 
> 
> Does anyone want to work on this? Very happy to give guidance?

I haven't set up my dev env for rclone yet, but if you could give some guidance and maybe some set requirements I could give this a crack.

Do you think this is suitable as a first-issue, given it would be my first contribution to this project?

**Comment by ncw** [comment]
> I haven't set up my dev env for rclone yet, but if you could give some guidance and maybe some set requirements I could give this a crack.

Great!
 
> Do you think this is suitable as a first-issue, given it would be my first contribution to this project?

It is a reasonably complicated issue, but it can be broken down.

Potentially it involves updating every backend which is a big job, but we can get the machinery in first and do the backends one at a time.

Here was my rough plan

> I would implement two flags which could be repeated
> 
> --upload-header "Header: String"
> --download-header "Header: String"
> 
> Which would be applied to Uploads (specifically Object.Update or Fs.Put) or Downloads (specifically Object.Open).
> 
> These would need to be applied as options (there is a general purpose HTTPOption already). A bit of work would need to be done in each remote to make this work. The options would be applied in the Copy primitive (and possibly elsewhere - this might need factoring).

So I think the steps would be
- [add the two flags](https://github.com/ncw/rclone/blob/4ee6de5c3ea9e2f9b3e5446c040640b8830ea497/fs/config/configflags/configflags.go#L32) as `[]string`
- [parse them ](https://github.com/ncw/rclone/blob/4ee6de5c3ea9e2f9b3e5446c040640b8830ea497/fs/config/configflags/configflags.go#L106)into two slices of [fs.HTTPOption](https://github.com/ncw/rclone/blob/4ee6de5c3ea9e2f9b3e5446c040640b8830ea497/fs/options.go#L180) in the `Config` struct, say `UploadOptions` and `DownloadOptions`
- Add these options to the necessary places
    - [operations.Copy](https://github.com/ncw/rclone/blob/4ee6de5c3ea9e2f9b3e5446c040640b8830ea497/fs/operations/operations.go#L253) in the Put, Update and Open calls
    - there are more places this would need to be added (eg Rcat) but Copy will get most of them!
- this then should be working for backends which use [lib/rest](https://github.com/ncw/rclone/blob/master/lib/rest/rest.go), eg b2 and box
- alter the remaining backends to read the Options in Open, Put and Update.  This should be done in seperate commits and I'm very happy to help with this bit.

That seems like quite a lot of work now I write it out!

What do you think?

**Comment by pol1000000** [comment]
+1 

think, the issue with flags `-Z` \ `-z` can be closed. 
adding additional headers is the most important feature. 
compression can always be applied with third-party utils.

affecting to AWS S3 and Google Buckets

**Comment by pataquets** [comment]
I disagree. External compression requires an extra step both when storing and accessing. Native bucket compression saves space and you can still read original data without uncompressing yourself, since bucket does it transparently when accessed.

**Comment by tgallant** [comment]
I'm interested in using this feature. I have taken a first pass at implementing this in #3951. If it's looking good so far I will continue down that path (new to the repo so happy to receive guidance).

**Comment by bjg2** [comment]
Will this come to master / release soon? I cannot use rclone because of this, I need to add content-disposition metadata....

**Comment by ncw** [comment]
> Will this come to master / release soon? I cannot use rclone because of this, I need to add content-disposition metadata....

Soon hopefully! There are a couple of little things for @tgallant to fix up on the PR.

**Comment by bjg2** [comment]
Looking forward! It would be very useful for me, as currently I can not use this great tool.

PS. I would, at the moment, upload to AWS S3 and GCS, so I'm the most interested in setting content-disposition in those two as expected.

**Comment by ncw** [comment]
I've merged this to master now - thank you very much @tgallant  for implementing it -  which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

See the top for the list of supported and unsupported backends.

**Comment by ncw** [comment]
I have also implemented the `--header` flag which affects all transactions on all backends.

**Comment by bjg2** [comment]
Hey guys, just got to the point to test / use this feature, and I'm having issues.

I'm running version: `rclone-v1.51.0-254-g74d9dabd-beta-windows-amd64`, and I use the following command:
```
copyto SOURCE DEST --header-upload "Content-Disposition: attachment; filename='randomstvar.txt'"
```

On AWS S3 headers work as expected:
![image](https://user-images.githubusercontent.com/6639273/80741747-76fe2880-8b1a-11ea-8987-2f5471eff2c9.png)

On Google Cloud Storage, not as much:
![image](https://user-images.githubusercontent.com/6639273/80741831-a14fe600-8b1a-11ea-807a-c4a4ced97b4b.png)

Is there some bug with upload headers with GCS, or am I doing something wrong? This is very important for me at the moment, I should upload a bunch of data to the GCS in few days... :)

**Comment by ncw** [comment]
s3 - good!

gcs.,, The docs are here: https://cloud.google.com/storage/docs/gsutil/addlhelp/WorkingWithObjectMetadata

I can see the `PUT` requests are OK with `-vv --dump bodies` but the headers don't get set...

Just tried a test with gsutil and it puts the headers inline in the object info :-( I'll have a go at fixing that in a bit.

**Comment by bjg2** [comment]
Thanks for looking into this!

Not to push you, but is it possible to fix this issue until Monday? In Monday I have to upload like a few milion files to GCS, and it would be great if I wouldn't have to track them down and change their content disposition as needed...

**Comment by ncw** [comment]
@bjg2 I've tracked down the problem here. Rclone needs to set the headers on the object data in the request not the actual request.

I've had a go at fixing this here - can you have a go? It works in my tests so if it works for you it should be good for your upload!

https://beta.rclone.org/branch/v1.51.0-265-gb40e997f-fix-59-gcs-headers-beta/ (uploaded in 15-30 mins)

**Comment by bjg2** [comment]
Both S3 and GCS work now! Thanks!

![image](https://user-images.githubusercontent.com/6639273/80860126-02380500-8c66-11ea-96ef-f4e83fc57a05.png)

**Comment by Shareed2k** [comment]
what about custom headers, in gcs ?

**Comment by ncw** [comment]
> what about custom headers, in gcs ?

I've added support for custom metadata? Using

    x-goog-meta-key: value

Is that what you mean?

I don't think it is possible to set any of the other headers

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.52

**Comment by Cinerar** [comment]
Am i right that this doesn't implemented for operations.CopyFile but only for operations.Copy and operations.Rcat?

**Comment by ncw** [comment]
> Am i right that this doesn't implemented for operations.CopyFile but only for operations.Copy and operations.Rcat?

@Cinerar --header-upload and --header-download should work for `copy`, `copyfile`, `cat` and `rcat`

**Comment by Cinerar** [comment]
In my experiments i found that --header-upload are not set from Env Variable RCLONE_HEADER_UPLOAD (maybe i used wrong one?), so  i was forced to use 
`fs.Config.UploadHeaders = []*fs.HTTPOption{
		&fs.HTTPOption{
			Key:   "Content-Disposition",
			Value: "attachement",
		}}`

and i confirm that it works for copyfile too.

**Comment by ncw** [comment]
This is all finished and merged now

      --header stringArray            Set HTTP header for all transactions
      --header-download stringArray   Set HTTP header for download transactions
      --header-upload stringArray     Set HTTP header for upload transactions

Please open a new issue if there is problem with it!

**Comment by Manojnaik1** [comment]
Hi, can anyone please guide me on how to upload multiple metadata

**Comment by ncw** [comment]
@Manojnaik1 repeat the flag as many times as necessary.

**Comment by Manojnaik1** [comment]
@ncw thanks for your reply. it's working.
