### ISSUE TITLE
support finding total number of objects (photos, videos) in gphotos mount (without size)

### ISSUE THREAD

**Issue by sagz** [rclone/rclone#5900]
#### What is your current rclone version (output from `rclone version`)?
```➜  ~ rclone version
rclone v1.57.0
- os/version: darwin 12.1 (64 bit)
- os/kernel: 21.2.0 (arm64)
- os/type: darwin
- os/arch: arm64
- go/version: go1.17.2
- go/linking: dynamic
- go/tags: none
```

#### What problem are you are trying to solve?
Trying to get the total number of photos, videos I have on Google Photos. 

#### How do you think rclone should be changed to solve that?
Currently, the `ls` command always requests size. Unfortunately, for gphotos backend, which doesn't support getting size directly, rclone makes an HTTP request for each file's size. Which is extremely long for 100k+ files. Would be great to get a list of files without the size. And `rclone about` also doesn't work on that backend.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
For size, it's already listed in the docs:

https://rclone.org/googlephotos/#size

**Comment by sagz** [comment]
Ah ok. `rclone ls gphotos:media/all` does work for this purpose. Takes a long time and gives no output till then. Ended up doing `rclone ls gphotos:media/all > ~/Documents/gphotos-archivedincluded-ls.txt' to sift through the filenames and get the count quickly.

Thanks!
