### ISSUE TITLE
Uptobox error: Failed to copy: api error 1

### ISSUE THREAD

**Issue by xberg** [rclone/rclone#5903]
Hello

#### What is the problem you are having with rclone?

Cannot upload to uptobox. 
Running 
`rclone copy -v rptest.zip uptobox:/`

generates the following error
` Failed to copy: api error 1: An error occured: Could not fid current path`

However looking at my files on uptobox I see that 3 files were created with different names (I for each retry)

And the following command will copy the file correctly: 

`rclone copy -v rptest.zip uptobox:`

So indicating any folder after the host will generate this error.

#### What is your rclone version (output from `rclone version`)

1.57.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

ubuntu 20

#### Which cloud storage system are you using? (e.g. Google Drive)

uptobox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`
rclone copy -v rptest.zip uptobox:/`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2022/01/06 08:30:35 DEBUG : rclone: Version "v1.57.0" starting with parameters "rclone" "copy" "-vv" "--retries" "1" "rptest.zip" "uptobox:/"]
2022/01/06 08:30:35 DEBUG : Creating backend with remote "rptest.zip"
2022/01/06 08:30:35 DEBUG : Using config file from "/root/.config/rclone/rcloneconf"
2022/01/06 08:30:35 DEBUG : fs cache: adding new entry for parent of "rptest.zi", "/my"
2022/01/06 08:30:35 DEBUG : Creating backend with remote "uptobox:/"
2022/01/06 08:30:36 DEBUG : rptest.zip: Need to transfer - File not found at Detination
2022/01/06 08:30:38 ERROR : rptest.zip: Failed to copy: api error 1: An error ocured: Could not find current path
2022/01/06 08:30:38 ERROR : Attempt 1/1 failed with 1 errors and: api error 1: n error occured: Could not find current path
2022/01/06 08:30:38 INFO  :
Transferred:       19.111 MiB / 19.111 MiB, 100%, 0 B/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         2.6s

2022/01/06 08:30:38 DEBUG : 5 go routines active
2022/01/06 08:30:38 Failed to copy: api error 1: An error occured: Could not fid current path

```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by MesterPerfect** [comment]
I can’t transfer files from uptobox
https://forum.rclone.org/t//31267

**Comment by buengese** [comment]
This seems to be a different issue. Could you create a new issue for tracking that?
