### ISSUE TITLE
webdav Magentacloud does not mount

### ISSUE THREAD

**Issue by ambipur76** [rclone/rclone#5904]
#### What is the problem you are having with rclone?
Magentacloud is not mounted at all. This cloud storage provider uses webdav backend.

#### What is your rclone version (output from `rclone version`)
rclone v1.58.0-beta.5923.b55575e62
- os/version: debian 11.2
- os/kernel: 5.10.0-10-686-pae (i686)
- os/type: linux
- os/arch: 386
- go/version: go1.17.5
- go/linking: static
- go/tags: none
but same problem occurs also with rclone v1.57.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Debian 11 bullseye x86
Linux 5.10.0-10-686-pae #1 SMP Debian 5.10.84-1 (2021-12-08) i686 GNU/Linux

#### Which cloud storage system are you using? (e.g. Google Drive)
Magentacloud
Other cloud storage providers I use (Mega, Google Drive, Yandex) can be mounted without problems.

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
mount operation is performed via the following systemd unit:
[Unit]
Description=RClone mount storage at t-online.de
Wants=network-online.target
After=network-online.target

[Service]
Type=notify
KillMode=mixed
RestartSec=5

#Set up environment
Environment=MOUNT_DIR="/srv/backup/t-online.de"
Environment=RCLONE_TEMP_DIR="/srv/backup/.cache/t-online"
Environment=RCLONE_MOUNT_VFS_CACHE_MODE="writes"

ExecStart=/usr/bin/rclone mount T-Online: "${MOUNT_DIR}" \
--allow-other \
--syslog \
--cache-dir="${RCLONE_TEMP_DIR}" \
--drive-use-trash=false \
--vfs-cache-mode="${RCLONE_MOUNT_VFS_CACHE_MODE}"
ExecStop=/bin/fusermount -uz "${MOUNT_DIR}"
Restart=on-failure

[Install]
WantedBy=multi-user.target

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
systemctl status rctonline
● rctonline.service - RClone mount storage at t-online.de
     Loaded: loaded (/etc/systemd/system/rctonline.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-01-06 22:58:15 CET; 48s ago
   Main PID: 7902 (rclone)
     Status: "[22:58] vfs cache: objects 0 (was 0) in use 0, to upload 0, uploading 0, total size 0 (was 0)"
      Tasks: 10 (limit: 4915)
     Memory: 15.0M
        CPU: 367ms
     CGroup: /system.slice/rctonline.service
             └─7902 /usr/bin/rclone mount T-Online: /srv/backup/t-online.de --allow-other --syslog --cache-dir=/srv/backup/.cache/t-online --drive-use-trash=false>

Jan 06 22:58:14 systemd[1]: Starting RClone mount storage at t-online.de...
Jan 06 22:58:15 systemd[1]: Started RClone mount storage at t-online.de.
lines 1-13/13 (END)

/srv/backup/t-online.de# ls -l
total 0

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Please make a post on the forums and use the help and support template.

https://forum.rclone.org/
