### ISSUE TITLE
add option to hashsum command to output file size

### ISSUE THREAD

**Issue by karma-sun** [rclone/rclone#5906]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.57.0

#### What problem are you are trying to solve?
output of hashsum command do not have file size(in byte),and it is needed  sometime

#### How do you think rclone should be changed to solve that?
add option to hashsum command to output file size as a third column

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ivandeex** [comment]
Solved by
```
rclone lsf --format=hsp --separator=" " remote:path 
```
https://rclone.org/commands/rclone_lsf/
