### ISSUE TITLE
Google Drive reports file size of google docs as -1 or 0, files are empty

### ISSUE THREAD

**Issue by jarrndewitt** [rclone/rclone#5908]
#### Output of `rclone version`

rclone version

> rclone v1.57.0
> - os/version: ubuntu 20.04 (64 bit)
> - os/kernel: 5.4.0-92-generic (x86_64)
> - os/type: linux
> - os/arch: amd64
> - go/version: go1.17.2
> - go/linking: static
> - go/tags: none

rclone configuration file

> [GoogleDrive]
> type = drive
> client_id = MyOwnClientID
> client_secret = DontLookHere
> scope = drive
> token = {"access_token":"TokenHere","token_type":"Bearer","refresh_token"TokenHere","expiry":"2022-01-10T13:11:44.85169607+01:00"}
> root_folder_id = 0APlarDhHMBDuUk9PVA

#### Describe the issue

I have successfully connected my google drive via rclone and am able to mount and access the files on the drive. The following issue comes up with all and only google docs files on that drive:

When I list the directory contents with `rclone lsl GoogleDrive:` these files are reported as of size -1.

If I mount the drive using `rclone mount GoogleDrive: /home/use/path/GoogleDrive --vfs-cache-mode full --daemon` the file size is reported as zero (in bash as well as in thunar). If I try to open one of these files, they come out as empty.

When I start rclone without the --daemon flag and then try to access the files, I get no error messages in the output.

**Comment by animosity22** [comment]
Can you please open a post on the forums and use the help and support template.

https://forum.rclone.org/

**Comment by Phixygamer** [comment]
If there was a post created on the forums can someone please link it here? I'm having the same issue and can't find any info about it.

**Comment by ncw** [comment]
Rclone doesn't know the size of Google docs until they have been downloaded.

This explains the size of -1 in the listings - that means size unknown. 

You can't have sizes off -1 in a mount so rclone reports 0 instead.

This is explained in the docs here

https://rclone.org/drive/#limitations-of-google-docs
