### ISSUE TITLE
Any way to manually 'throttle' speed?

### ISSUE THREAD

**Issue by Darkmaster006** [rclone/rclone#5913]
This is more of a question than a feature request, but I guess this is the place, apologies if it is not. What I would like to do is pretty basic, so maybe the functionality is there. I use rclone in Linux to mount MEGA and Google Drive so that I can stream videos I have from there, but, my internet is pretty slow (1 MB max.), and when the usage goes to the limit, it seems to disable itself for a while, some minutes, or just go really slow in general. What I'd like to be able to do is to set a throttle limit, let's say 700 kb/s, so that my internet is not saturated and the stream could load, buffer and function correctly. Is this possible? If possible, where can I change this globally? Thank you very much.

**Comment by badLABZ** [comment]
You can add the Bandwith Limit command using  **_--bwlimit_** so to set your limit to 700kbps you would set this to --bwlimit 700k in your rclone script/command.

**Comment by ncw** [comment]
`--bwlimit` is the correct answer :-)

In future questions will get answered quicker on [on the rclone forum](https://forum.rclone.org/).

I'll close this now.

**Comment by Darkmaster006** [comment]
> `--bwlimit` is the correct answer :-)
> 
> In future questions will get answered quicker on [on the rclone forum](https://forum.rclone.org/).
> 
> I'll close this now.

What if I need this for a whole 'session' in a mounted drive? Let's say I have some videos on my Drive 'A' in GDrive, so I mount it and I want all videos in there to be played with a 700kbps bandwidth limit, is that possible? Should I just set it after the mount? Thank you. And I will go to the forum in the future, thanks a lot.

**Comment by ncw** [comment]
Yes, just put `--bwlimit` on the `rclone mount` command.
