### ISSUE TITLE
Request for sync.com storage backend

### ISSUE THREAD

**Issue by JaneJeon** [rclone/rclone#5915]
Hi, I did a quick issues search and it seems no one brought it up, and I didn't see it in the rclone.org website, so I would like to formally request for sync.com to be added as a storage provider.

I see that pCloud is already supported, and sync.com IS basically pCloud with a few exceptions. The biggest difficulty is going to be getting past its encryption - because it's been built out for zero-knowledge encryption, it encrypts files _locally_ with a key based on your password (vastly oversimplifying here).

pCloud also does support such client-side encryption; however, it's optional (in fact, it's a paid add-on) and I'm guessing rclone simply doesn't have to deal with such security measures for pCloud.

There are no known sync.com linux clients, which again complicates this further.

Obviously it's going to be a royal PITA if the rclones authors do decide to tackle this and I am creating this issue not to see that it _will_ be implemented, but to track its progress and formally note interest for integration with this provider.

Thank you

**Comment by animosity22** [comment]
Unfortunately sync.com has no public API so I can log this as a feature and close it out as without a public API, there isn't anything to do.

Closing out as not able.

**Comment by rgaufman** [comment]
Frustrating, still no solution for this?

**Comment by ncw** [comment]
@rgaufman if you are a sync.com customer, then please complain to your account manager / support team that there is no API available. If sync.com's customers want a public API then that will motivate them to provide one.

**Comment by lyatziv** [comment]
Done
