### ISSUE TITLE
--use-json-log produces invalid JSON due to unescaped newlines

### ISSUE THREAD

**Issue by bdkjones** [rclone/rclone#5923]
# What is the problem you are having with rclone?

When `--use-json-log` is combined with `--stats`, the JSON output is invalid because a terminating newline character on the `msg` field is not escaped. 

Here is the truncated JSON output of `stats`:

```
{"level":"info","msg":"   78.818 KiB / 80.750 KiB, 98%, 34.313 KiB/s, ETA 0s (xfr#12/18, chk#160/683)\n","source":"accounting/stats.go:480","stats":{...}}
```

The invalid character is the unescaped newline at the end of the `msg` text. This newline should ideally not be included when JSON logging is enabled. Barring that, it should be properly escaped according to the JSON spec, here: https://www.ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf

(The relevant portion is on page 4, under "Strings" --> `U+000A` must be escaped in a string.)

This is important because JSON parsers that strictly adhere to the spec will fail to parse rClone's output with an error such as: `"Unescaped control character around line 1, column 101."`

---

# What is your rclone version (output from `rclone version`)

```
rclone v1.57.0
- os/version: darwin 12.1 (64 bit)
- os/kernel: 21.2.0 (arm64)
- os/type: darwin
- os/arch: arm64
- go/version: go1.17.2
- go/linking: dynamic
- go/tags: cmount
```

# Which OS you are using and how many bits 

macOS 12.1, 64-bit ARM

# Which cloud storage system are you using?

N/A - All are affected

# The command you were trying to run

`sync --stats=3s --log-level INFO --use-json-log /path/to/some/folder some:backend`

**Comment by albertony** [comment]
The json output you included is valid, with a newline actually escaped into `\n`, isn't it?

**Comment by bdkjones** [comment]
@albertony Negative. `\n\n` is simply two newline characters, neither of which is escaped. The JSON you've included in your post is also invalid.

The correct sequence to escape the newline would be: `\\n`

From the ECMA spec: 
<img width="1344" alt="Screen Shot 2022-01-17 at 02 54 36" src="https://user-images.githubusercontent.com/926566/149757156-befc57ec-7b12-40ef-93d9-d9d1af4e8136.png">

**Comment by bdkjones** [comment]
I'm happy to tackle a PR for this, but I cannot for the life of me figure out where the trailing `\n` and the leading whitespace are appended to `msg`. I've dug through `accounting.go` and I can see where the message text itself is constructed, but there's no leading whitespace or trailing newline at that point.

I've looked at `logrus` and found some old issues about improperly failing to escape newlines, but unless rClone is on a pre-2017 version of logrus, those should not apply.

I don't know Go, or the rClone codebase, so I'm sure I'm just missing some magic somewhere.

**Comment by albertony** [comment]
Maybe I'm being ignorant, but I do not agree.

The following is unescaped and invalid json:
```
{
    "level": "info",
    "msg": "Hello
World"
}
```

The following is properly escaped and valid json:
```
{
    "level": "info",
    "msg": "Hello\nWorld"
}
```

PowerShell is happy parsing the json output from rclone:

```
.\rclone copy src dst --use-json-log --stats 1s --verbose 2>&1 | ConvertFrom-Json
...
level  : info
msg    :
         Transferred:               4.503 MiB / 4.503 MiB, 100%, 0 B/s, ETA -
         Transferred:          205 / 205, 100%
         Elapsed time:         2.2s


source : accounting/stats.go:482
stats  : @{bytes=4721273; checks=0; deletedDirs=0; deletes=0; elapsedTime=2,2823773; errors=0; eta=; fatalError=False; renames=0; retryError=False;
          speed=0; totalBytes=4721273; totalChecks=0; totalTransfers=205; transferTime=0; transfers=205}
time   : 2022-01-17T12:04:54.101631+01:00
```

Regarding:
> I've looked at logrus and found some old issues about improperly failing to escape newlines, but unless rClone is on a pre-2017 version of logrus, those should not apply.

I did so too, but at least on master we are using v1.8.1 which is latest.

Regarding:

> The correct sequence to escape the newline would be: \\n

Well, if you wanted to represent the json in a C++ string constant for example, then you would have to add extra escaping, sure.

**Comment by bdkjones** [comment]
@albertony See: https://stackoverflow.com/a/42073/463439

**Comment by bdkjones** [comment]
@albertony To elaborate, `\n` is a **single** character in JSON, with codepoint `U+000A`. That falls within the range of codepoints that must be escaped, according to the spec.

As that SO thread demonstrates, powershell may be lenient but any standards-compliant parser will choke on the strings as they're currently printed.

(That said, if I've misconfigured rClone or have missed an option, I'm happy to be proven an idiot.)

**Comment by albertony** [comment]
That SO link doesn't conflict with what I wrote. To quote a later comment in that thread:

> As most of programming languages uses \ for quoting, you should escape the escape syntax (double-escape - once for language/platform, once for JSON itself):
>
> jsonStr = "{ \\"name\\": \\"Multi\\\nline.\\" }";

So they want to put valid json into a Javascript string variable? Then they need to escape the json-escapes.

> \n is a single character in JSON, with codepoint U+000A

This:
```

```

(newline) is codepoint U+000A, and must be escaped in json - into the two-character escape sequence `\n`.

**Comment by olefrost** [comment]
@bdkjones  I would appreciate, if you could improve your ability to explicitly acknowledge your mistakes and[ the help you are receiving from others](https://forum.rclone.org/t/move-no-change-log-messages-to-info-level/28645/3).

**Comment by bdkjones** [comment]
@olefrost I'm not sure how I've offended you, but I don't think it's a good idea to engage with comments like that. 

@albertony I think we're going in circles discussing two different things. The `\n` needs escaping when presented as a JSON string. It does not need escaping when it's merely part of the "bag of bits" that is JSON data. I think you're discussing the latter situation and I'm discussing the former?

The JSON strings I receive as output in the Shell when running rClone print `\n` instead of `\\n`. Once the JSON data is printed as a String, the newline should be escaped: `\\n` 

At any rate, I can work around the issue on my side, so I closed the report. Thanks for the discussion!

**Comment by olefrost** [comment]
Hi @bdkjones, I see a lack of acknowledgment(s) from your side and then kindly give you some feedback to let you know my perspective. You disagree and share your feedback and perspective. Both are fine and a natural part of cooperation and just shows me that we see the world differently and probably live in different cultures. Example: Some protocols expect acknowledgement (e.g. TCP) other doesn’t (e.g. UDP) - both are fine for their respective purpose, but they don’t work well together.

**Comment by albertony** [comment]
> I think we're going in circles discussing two different things. The `\n` needs escaping when presented as a JSON string. It does not need escaping when it's merely part of the "bag of bits" that is JSON data. I think you're discussing the latter situation and I'm discussing the former?
> 
> The JSON strings I receive as output in the Shell when running rClone print `\n` instead of `\\n`. Once the JSON data is printed as a String, the newline should be escaped: `\\n`

Maybe. I would still claim that rclone's output in the shell *is* json, and that `\n` is valid in json. It is not a string containing json, then you would have to escape further according to whatever is interpreting the string - and typically needs `\\n`.

> At any rate, I can work around the issue on my side, so I closed the report. Thanks for the discussion!

Great, good look! 👍

**Comment by bdkjones** [comment]
The original cause of this is that I found it necessary to convert the data rClone is dumping to `STDERR` into strings (even with JSON output) because rClone does not log one JSON object at a time. Instead, the `STDERR` buffer arrives with a chunk of data like this:

```
{"level":"warning","msg":"Can't follow symlink without -L/--copy-links","object":"Bundling/roll/node_modules/.bin/jsesc","objectType":"*local.Object","source":"local/local.go:965","time":"2022-01-16T23:52:51.827441-08:00"}
{"level":"warning","msg":"Can't follow symlink without -L/--copy-links","object":"Bundling/roll/node_modules/.bin/browserslist","objectType":"*local.Object","source":"local/local.go:965","time":"2022-01-16T23:52:51.827616-08:00"}
{"level":"warning","msg":"Can't follow symlink without -L/--copy-links","object":"Bundling/roll/node_modules/.bin/prefix","objectType":"*local.Object","source":"local/local.go:965","time":"2022-01-16T23:52:51.827823-08:00"}
```

This isn't parsable as-is; it's multiple JSON objects in a single blob of data. So in order to use this, I have to:

1. Convert the blob of data to a String.
2. Find the newlines that divide the JSON objects (but ignore the non-escaped newlines that appear in strings within the JSON objects.
3. Split on those "critical" newlines
4. Parse each substring as JSON.

This is...expensive. Doing the above for 2,000,000 entries wastes a lot of cycles and battery. I wish I could just pipe the data from `STDERR` directly into a JSON parser, but I had to go through Strings to deal with the way rClone is flushing the pipe currently.
