### ISSUE TITLE
Cannot add Onedrive connector

### ISSUE THREAD

**Issue by sharicov** [rclone/rclone#5928]
Running OpenWRT for R4S from here: https://wiki.friendlyarm.com/wiki/index.php/NanoPi_R4S
rclone version:
rclone v1.57.0
- os/version: openwrt 21.02.1 (64 bit)
- os/kernel: 5.15.11 (aarch64)
- os/type: linux
- os/arch: arm64
- go/version: go1.17.6
- go/linking: dynamic
- go/tags: none

Getting following error when trying to add onedrive connector after authorizing on another PC (R4S is headless):
`lookup graph.microsoft.com on 127.0.0.1:53: no such host`
Copying working rclone.conf doesn't work either, getting following error when trying to list onedrive:

`Failed to create file system for "onedrive:/": failed to get root: Get "https://graph.microsoft.com/v1.0/drives/***MASKED***/root": dial tcp: lookup graph.microsoft.com on 127.0.0.1:53: no such host`

On windows works perfectly.

**Comment by animosity22** [comment]
That's a local issue on the machine as you can't get DNS not a rclone issue. Please use the forums for general support requests.

https://forum.rclone.org/
