### ISSUE TITLE
drive: Skip or suppress errors for dangling shortcuts

### ISSUE THREAD

**Issue by filippobottega** [rclone/rclone#5949]
#### The associated forum post URL from `https://forum.rclone.org`

[Can I skip or suppress errors for dangling shortcuts?](https://forum.rclone.org/t/can-i-skip-or-suppress-errors-for-dangling-shortcuts/25095)

#### What is your current rclone version (output from `rclone version`)?

rclone v1.56.1

#### What problem are you are trying to solve?

I need to skip dangling shortcuts because they are been created in a folder shared with me but I don't have the rights to delete them.

#### How do you think rclone should be changed to solve that?

I need a new flag to skip dangling  shortcuts like --drive-skip-dangling-shortcuts. Another solution could be change error to warning in case of dangling  shortcuts when --drive-skip-dangling-shortcuts is used.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I assume you don't want to use `--drive-skip-shortcuts` which will skip all shortcuts?

A `--drive-skip-dangling-shortcuts` option which didn't show dangling shortcuts in the listing at all would be easy enough to implement - is that what you mean?

> Another solution could be change error to warning in case of dangling shortcuts when --drive-skip-dangling-shortcuts is used.

Rclone only gives the error when the dangling shortcut is opened for read.

Rclone would then have to supply the contents of the shortcut so make an empty file or something. I don't think that will work very well.

**Comment by filippobottega** [comment]
Hello @ncw,
  thank you for your answer.
  

> A --drive-skip-dangling-shortcuts option which didn't show dangling shortcuts in the listing at all would be easy enough to implement - is that what you mean?

Yes, that might be enough for me.

> Rclone would then have to supply the contents of the shortcut so make an empty file or something. I don't think that will work very well.

I think that is better to skip dangling shortcuts at all without creating empty files but I'd like to have a log of all skipped shortcuts, if possible.

  Thank you,
    Filippo.

**Comment by ncw** [comment]
Give this a go

[v1.58.0-beta.5977.1938ca218.fix-5948-drive-skip-dangling](https://beta.rclone.org/branch/fix-5948-drive-skip-dangling/v1.58.0-beta.5977.1938ca218.fix-5948-drive-skip-dangling/) on branch [fix-5948-drive-skip-dangling](https://github.com/rclone/rclone/tree/fix-5948-drive-skip-dangling) (uploaded in 15-30 mins)

It implements the --drive-skip-dangling-shortcuts flag which doesn't show dangling shortcuts in the listing. It will log them as it does at the moment.

**Comment by filippobottega** [comment]
Thank you very much @ncw!
I'll try this fix as soon as possibile.

**Comment by ncw** [comment]
Let me know if it works for you, then I'll merge it if it does :-)

**Comment by benthorner** [comment]
@filippobottega one way to do this is to ask someone else to create a shortcut to a document that you don't have access to - it'll behave the same way as a shortcut to a deleted document.

**Comment by benthorner** [comment]
@ncw one thing I noticed is that the new log line only prints out the name of the file, which can make it difficult to locate if the drive contains other files by the same name. Could the log include the path to the file as well?

This would be similar to the existing logs for "duplicate object...ignoring", which print the path to the file.

**Comment by filippobottega** [comment]
Doesn't works:

NOTICE: Dangling shortcut ""Documento di test (Cancellare)"" detected"
"Transferred:   	    2.986 MiB / 2.986 MiB, 100%, 7.562 KiB/s, ETA 0s"
Errors:                 1 (retrying may help)
2022/02/21 09:55:04 Failed to sync: failed to open source object: can't read dangling shortcut
Exit code: 1

**Comment by ncw** [comment]
@filippobottega did you use the ` --drive-skip-dangling-shortcuts` flag?

**Comment by ncw** [comment]
@benthorner wrote:
> one thing I noticed is that the new log line only prints out the name of the file, which can make it difficult to locate if the drive contains other files by the same name. Could the log include the path to the file as well?
> 
> This would be similar to the existing logs for "duplicate object...ignoring", which print the path to the file.

I had a go at doing this, but unfortunately the dangling shortcuts are resolved before we know the name of the directory (directories are addressed by ID not name in the google drive protocol). At the point the shortcut is resolved we only know the directory ID, and that isn't yet in the directory ID cache because the listing of that directory hasn't completed yet so we can't look up the name.

So, perhaps surprisingly, its annoyingly hard to add the path in the log message!

**Comment by filippobottega** [comment]
@ncw I'm really sorry, I have forgot to use the `--drive-skip-dangling-shortcuts` flag ... 

I have redone the test and now works like expected. Only una notice:

NOTICE: Dangling shortcut ""Documento di test (Cancellare)"" detected"

The exit code is 0.

Thank you very mutch for the new flag!

Best regards,
    Filippo.

**Comment by benthorner** [comment]
@ncw thanks for trying and explaining the difficulty ⭐.

It's not a big issue anyway - the problem itself is fixed and that's the important thing.

**Comment by ncw** [comment]
Thanks for testing everyone.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.58
