### ISSUE TITLE
googleapi: Error 403: (Only attempt one time)

### ISSUE THREAD

**Issue by vaccarieli** [rclone/rclone#5950]
#### Output of `rclone version`

Rclone Version 1.57.0 (Latest)

#### Describe the issue
Is not an issue, I just want to know IF possible to have rclone to try only once to download a file that is that User rate limit is exceeded. Because when ever I try to copy a file like that it hangs for around 3 min and then will try the another, 

I will also want to check if the file rate limit is exceeded and have only the output response.

**Comment by animosity22** [comment]
Please use the forums and the help and support template.

This is for bugs/enhancements and not general support.
