### ISSUE TITLE
build: macOS builds failing

### ISSUE THREAD

**Issue by l3v11** [rclone/rclone#5951]
GitHub workflow is failing to build for the mac-arm64 arch. Checked recent rclone Actions (workflow) too, same issue. Kindly check.

**Comment by ncw** [comment]
Thanks for making an issue about this.

It looks like the `cmount` tests are locking up on macOS sometimes both in the amd64 and the arm64 builds (which isn't suprising since they are both running the amd64 code when testing)

And if it does get through the `cmount` test, the build fails with

```
2022/01/26 10:47:04 Failed to run ["xcrun" "--sdk" "macosx11.1" "--show-sdk-path"]: exit status 1
```

I guess this is because something changed in the GitHub actions build environment...

**Comment by ncw** [comment]
I upgraded the build server to macos 11 and fix the SDK stuff. The builds are still locking up in the cmount tests, but I did managed to build an arm64 build

https://beta.rclone.org/branch/fix-5951-macos-build/v1.58.0-beta.5963.e9d9d6904.fix-5951-macos-build/rclone-v1.58.0-beta.5963.e9d9d6904.fix-5951-macos-build-osx-arm64.zip

Can you give that a quick test @l3v11 ? Does it run? Does `rclone mount` work?

I'll work more on the cmount lockup now ...

**Comment by l3v11** [comment]
Ohh man, I don't have any mac too. Actually was seeing that issue while checking the Actions. So informed you :)

**Comment by hoyho** [comment]
> I upgraded the build server to macos 11 and fix the SDK stuff. The builds are still locking up in the cmount tests, but I did managed to build an arm64 build
> 
> https://beta.rclone.org/branch/fix-5951-macos-build/v1.58.0-beta.5963.e9d9d6904.fix-5951-macos-build/rclone-v1.58.0-beta.5963.e9d9d6904.fix-5951-macos-build-osx-arm64.zip
> 
> Can you give that a quick test @l3v11 ? Does it run? Does `rclone mount` work?

I have tried it
1. `./rclone ls` works fine
here's the output:
```bash
env38 ❯ ./rclone ls phy57:/
     4096 cos1/4k
      703 hoyho/test.1
      116 hoyho/test.zip
```

2. rclone mount is requiring some other component
```bash
~/Desktop/rclone-v1.58.0-beta.5963.e9d9d6904.fix-5951-macos-build-osx-arm64
env38 ❯ ./rclone mount phy57 mnt
2022/01/27 12:24:13 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find FUSE

~/Desktop/rclone-v1.58.0-beta.5963.e9d9d6904.fix-5951-macos-build-osx-arm64
env38 ❯ ./rclone cmount phy57 mnt
2022/01/27 12:24:34 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find FUSE
```

Then I install macfuse via: `brew install macfuse`

Now It seems need more config:
```bash
env38 ❯ ./rclone version
rclone v1.58.0-beta.5963.e9d9d6904.fix-5951-macos-build
- os/version: darwin 12.0.1 (64 bit)
- os/kernel: 21.1.0 (arm64)
- os/type: darwin
- os/arch: arm64
- go/version: go1.17.6
- go/linking: dynamic
- go/tags: cmount

~/Desktop/rclone-v1.58.0-beta.5963.e9d9d6904.fix-5951-macos-build-osx-arm64
❯ ./rclone mount phy57 mnt
mount_macfuse: the file system is not available (1)
2022/01/27 13:07:03 ERROR : Local file system at /Users/hoyho/Desktop/rclone-v1.58.0-beta.5963.e9d9d6904.fix-5951-macos-build-osx-arm64/phy57: Mount failed
2022/01/27 13:07:03 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed
```

**Comment by ncw** [comment]
It looks like it is working...

This

```
./rclone mount phy57 mnt
```

Should be

```
./rclone mount phy57:/ mnt
```

Assuming that `mnt` is an empty existing directory.

If it doesn't work add `-vv` and post the output - thank you.

**Comment by ncw** [comment]
The builds are working again and you should find a working arm64 build in [the latest beta](https://beta.rclone.org/) in about 20 minutes from now :-)

The work on fixing the lockup with running the cmount tests is continuing in #5960

**Comment by ncw** [comment]
I would appreciate a quick test with mount on macOS with the beta just to make sure it is still working as we can no longer tell if the tests are locking up!

**Comment by ilyasdc** [comment]
> I would appreciate a quick test with mount on macOS with the beta just to make sure it is still working as we can no longer tell if the tests are locking up!

Hi and thank you for this great project.
Mounting works on my side: 

```
xxx@xxx ~ % rclone --version
  rclone v1.58.0-beta.5984.b0de0b460
  - os/version: darwin 12.2 (64 bit)
  - os/kernel: 21.3.0 (arm64)
  - os/type: darwin
  - os/arch: arm64
  - go/version: go1.17.6
  - go/linking: dynamic
  - go/tags: cmount
xxx@xxx ~ % rclone mount onedrive .Volumes/onedrive
2022/02/03 06:56:02 NOTICE: One drive root '': --vfs-cache-mode writes or full is recommended for this remote as it can't stream
xxx@xxx ~ % ls .Volumes/onedrive
```

Shows some files ! 

Other info: 
- MacOS version:

`xxx@xxx ~ % sw_vers
ProductName:	macOS
ProductVersion:	12.2
BuildVersion:	21D49`

- Macfuse version: 4.2.4

**Comment by ncw** [comment]
Thank you for testing @ilyasdc :-)
