### ISSUE TITLE
Rclone “touch” command fails since 1.57.0

### ISSUE THREAD

**Issue by alex-mahr** [rclone/rclone#5952]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/rclone-touch-command-fails-since-1-57-0/28890

#### What is the problem you are having with rclone?
Something changed with rclone 1.57.0 so that the rclone "touch" command is not usable for me anymore.
It all worked fine, and still does when I run rclone with 1.56.2, but it fails with newer versions.
I see that the --recursive option has been added to the "touch" command with 1.57.0, so maybe it is related to this addition?

Background: I use the "touch" command to test if the remote server is set up correctly. So I "touch" a new file that does not exist on the remote server and delete the file after success.

The errors I get with type FTP:
```
2022/01/26 12:47:06 ERROR : Attempt 1/1 failed with 1 errors and: failed to touch (create): update stor: 550 /files/ftp: Not a regular file
2022/01/26 12:47:06 Failed to touch: failed to touch (create): update stor: 550 /files/ftp: Not a regular file
```

The errors I get with type SFTP:
```
2022/01/26 13:01:26 ERROR : Attempt 1/1 failed with 1 errors and: failed to touch (create): Update Create failed: sftp: "Failure" (SSH_FX_FAILURE)
2022/01/26 13:01:26 Failed to touch: failed to touch (create): Update Create failed: sftp: "Failure" (SSH_FX_FAILURE)
```

#### What is your rclone version (output from `rclone version`)

```
rclone v1.57.0
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.4.0-94-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.2
- go/linking: static
- go/tags: none
```

I have also tested the latest Beta, but without success:

```
rclone v1.58.0-beta.5960.a667e03fc
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.4.0-94-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.6
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Ubuntu 20.04 - 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
I have tested FTP, SFTP, Dropbox -> All report the same: "failed to touch"

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
With FTP:
```
rclone --config '/tmp/rclone-ftp.config' --retries 1 touch 'rclone-storage:/files/ftp'
```
-> Result: Nothing happens on the remote side. An rclone error message is shown (see above).

With SFTP:
```
rclone --config '/tmp/rclone-sftp.config' --retries 1 touch 'rclone-storage:/files/sftp'
```
-> Result: On the remote side, a new directory "sftp" is created in "/files/" (??? Why a directory ???). An rclone error message is shown (see above).

#### The rclone config contents with secrets removed.

```
[rclone-storage]
type = ftp
host = dev23.keymachine.de
user = test
pass = <secret-pass>
explicit_tls = true
```

```
[rclone-storage]
type = sftp
host = dev23.keymachine.de
user = test
pass = <secret-pass>
md5sum_command = none
sha1sum_command = none
```

#### A log from the command with the `-vv` flag

With FTP:
```
2022/01/26 12:47:28 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "--config" "/tmp/rclone-ftp.config" "-vv" "--retries" "1" "touch" "rclone-storage:/files/ftp"]
2022/01/26 12:47:28 DEBUG : Creating backend with remote "rclone-storage:/files/ftp"
2022/01/26 12:47:28 DEBUG : Using config file from "/tmp/rclone-ftp.config"
2022/01/26 12:47:28 DEBUG : ftp://dev23.keymachine.de:21/files/ftp: Connecting to FTP server
2022/01/26 12:47:28 DEBUG : Touch time 2022-01-26 12:47:28.42150678 +0100 CET m=+0.361783329
2022/01/26 12:47:28 DEBUG : ftp://dev23.keymachine.de:21/files/ftp: Touching (creating)
2022/01/26 12:47:29 DEBUG : ftp://dev23.keymachine.de:21/files/ftp: Connecting to FTP server
2022/01/26 12:47:29 DEBUG : : Removed after failed upload: 550 /files/ftp: Not a regular file
2022/01/26 12:47:29 ERROR : Attempt 1/1 failed with 1 errors and: failed to touch (create): update stor: 550 /files/ftp: Not a regular file
2022/01/26 12:47:29 DEBUG : 2 go routines active
2022/01/26 12:47:29 Failed to touch: failed to touch (create): update stor: 550 /files/ftp: Not a regular file
```

With SFTP:
```
2022/01/26 13:04:07 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "--config" "/tmp/rclone-sftp.config" "-vv" "--retries" "1" "touch" "rclone-storage:/files/sftp"]
2022/01/26 13:04:07 DEBUG : Creating backend with remote "rclone-storage:/files/sftp"
2022/01/26 13:04:07 DEBUG : Using config file from "/tmp/rclone-sftp.config"
2022/01/26 13:04:07 DEBUG : sftp://test@dev23.keymachine.de:22//files/sftp: New connection 62.141.56.104:51682->62.141.56.45:22 to "SSH-2.0-OpenSSH_8.4p1 Debian-5"
2022/01/26 13:04:07 DEBUG : Touch time 2022-01-26 13:04:07.852656441 +0100 CET m=+0.612075729
2022/01/26 13:04:07 DEBUG : sftp://test@dev23.keymachine.de:22//files/sftp: Touching (creating)
2022/01/26 13:04:07 ERROR : Attempt 1/1 failed with 1 errors and: failed to touch (create): Update Create failed: sftp: "Failure" (SSH_FX_FAILURE)
2022/01/26 13:04:07 DEBUG : 11 go routines active
2022/01/26 13:04:07 Failed to touch: failed to touch (create): Update Create failed: sftp: "Failure" (SSH_FX_FAILURE)
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

Thank you very much for your help!
Alex

**Comment by albertony** [comment]
I'm on it. I can reproduce the error in sftp, and it actually creates an empty directory instead of a file. Maybe that happens on the others as well?

**Comment by albertony** [comment]
It works correct on local filesystem (Windows) and also on Jottacloud backend.

@alex-mahr you mention dropbox in the forum, can you confirm it is the same problem there? Can you share details for that too, like you did for ftp and sftp?

**Comment by alex-mahr** [comment]
Sure, here it comes:

Dropbox error message:
```
2022/01/26 16:02:40 ERROR : Can't retry any of the errors - not attempting retries
2022/01/26 16:02:40 Failed to touch: path/malformed_path/...
```

And with "-vv":
```
2022/01/26 16:05:00 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "--config" "/tmp/keyhelp/rclone-test-161f1631c5ed08" "--retries" "1" "-vv" "touch" "rclone-storage:/files/keyhelp-remote-storage-test-61f1631c5ede0"]
2022/01/26 16:05:00 DEBUG : Creating backend with remote "rclone-storage:/files/keyhelp-remote-storage-test-61f1631c5ede0"
2022/01/26 16:05:00 DEBUG : Using config file from "/tmp/keyhelp/rclone-test-161f1631c5ed08"
2022/01/26 16:05:00 DEBUG : rclone-storage: Loaded invalid token from config file - ignoring
2022/01/26 16:05:00 DEBUG : Saving config "token" in section "rclone-storage" of the config file
2022/01/26 16:05:00 DEBUG : rclone-storage: Saved new token in config file
2022/01/26 16:05:00 DEBUG : Dropbox root '': Using root namespace "9158470304"
2022/01/26 16:05:01 DEBUG : fs cache: renaming cache item "rclone-storage:/files/keyhelp-remote-storage-test-61f1631c5ede0" to be canonical "rclone-storage:files/keyhelp-remote-storage-test-61f1631c5ede0"
2022/01/26 16:05:01 DEBUG : Touch time 2022-01-26 16:05:01.087469047 +0100 CET m=+0.694096977
2022/01/26 16:05:01 ERROR : Can't retry any of the errors - not attempting retries
2022/01/26 16:05:01 DEBUG : 4 go routines active
2022/01/26 16:05:01 Failed to touch: path/malformed_path/..
```

Config file looked like this:
```
[rclone-storage]
type = dropbox
token = {"access_token":"<secret-access-token>","token_type":"bearer","expires_in":14400,"refresh_token":"<secret-refresh-token>","scope":"account_info.read files.content.read files.cont>
client_id' = <client-id>
client_secret = <client-secret>
batch_mode = off
```

Result:
-> No file was created in Dropbox.


Meanwhile I have also tested with WebDAV. Surprisingly, touch worked without problems ;).
Also Dropbox works without problems with 1.56.2.

**Comment by albertony** [comment]
@alex-mahr Should be fixed in latest [beta](https://beta.rclone.org/), if you want to try it out.

**Comment by alex-mahr** [comment]
Perfect, I can confirm that the "touch" command using FTPS, SFTP and Dropbox are running fine again with the latest beta.

rclone v1.58.0-beta.5979.051685baa
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.4.0-94-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.6
- go/linking: static
- go/tags: none

**Comment by albertony** [comment]
Great - thank you for testing and reporting back!
