### ISSUE TITLE
add missing regions south-america  of google cloud storage

### ISSUE THREAD

**Issue by dmusante** [rclone/rclone#5955]
Hello:

          Hello:

Today google cloud storage has new regions for South America, Sao-Pablo (Brazil) and Santiago (Chile), they could update the list of regions to continue using the rclone on linux and windows..
From already thank you very much.

https://forum.rclone.org/t/goolge-and-new-regions/28883
 
          The missing regions are Sao Pablo(Brazil) and Santiago(Chile)

daniel

**Comment by ncw** [comment]
There were lots of missing regions!

I've attempted to add them all here

[v1.58.0-beta.5961.5a74bd1f5.fix-5955-gcs-regions](https://beta.rclone.org/branch/fix-5955-gcs-regions/v1.58.0-beta.5961.5a74bd1f5.fix-5955-gcs-regions/) on branch [fix-5955-gcs-regions](https://github.com/rclone/rclone/tree/fix-5955-gcs-regions) (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.58
