### ISSUE TITLE
Remote-to-remote moving/renaming does not work on Storj (but Storj cli 'uplink' supports it)

### ISSUE THREAD

**Issue by nickreserved** [rclone/rclone#5961]
Assuming rclone v1.58.0-beta.5960.a667e03fc win64

- Mount a storj remote storage with command
rclone.exe mount --vfs-cache-mode=writes Storj_remote_storage: Z:

- Copy local file C:\anything.txt to remote Z:\bucket\anything.txt

- Rename file Z:\bucket\anything.txt to Z:\bucket\anything1.txt GIVES AN ERROR
This operation is possible with storj cli via command
uplink mv sj://bucket/anything.txt sj://bucket/anything1.txt

- Move file Z:\bucket\anything.txt to Z:\bucket\folder\anything.txt GIVES AN ERROR
This operation is possible with storj cli via command
uplink mv sj://bucket/anything.txt sj://bucket/folder/anything.txt

- Copy file Z:\bucket\anything.txt to Z:\bucket\anything1.txt doesn't give error

Log of error follows:
2022/01/27 19:06:23 ERROR : ntua/Οδηγίες.pdf: Dir.Rename error: Fs "FS sj://" can't rename files (no server-side Move or Copy)
2022/01/27 19:06:23 ERROR : ntua/Οδηγίες.pdf: Dir.Rename error: Fs "FS sj://" can't rename files (no server-side Move or Copy)
2022/01/27 19:06:23 ERROR : IO error: Fs "FS sj://" can't rename files (no server-side Move or Copy)

**Comment by acsfer** [comment]
I'm having the same problem under Linux.
```
ERROR : folder/.ASDE_16052019.pdf.URkmCr: Dir.Rename error: Fs "FS sj://bucket_name" can't rename files (no server-side Move or Copy)
```

**Comment by Erikvv** [comment]
Storj did add server-side move in the mean time, but not copy yet. 

https://pkg.go.dev/storj.io/uplink#Project.MoveObject

**Comment by Practicalbutterfly5** [comment]
It seems that now [Uplink](https://github.com/storj/uplink/releases/tag/v1.9.0)  also supports server side copy

**Comment by ncw** [comment]
Yes, server side move was implemented in bf9c68c88a980d2c98a6b51f2f015f1307e2f91b by rclone so I'm going to close this issue.

@Practicalbutterfly5 if you wanted to send a PR to implement server side copy also, that would be great! Or maybe make a separate issue to this one since it is about move.

**Comment by dominus-imperium** [comment]
@ncw Even though it is implemented I still get the sane issue. I am unable to move or rename files. The error shows:

<3>ERROR : folder/TEST.txt: Dir.Rename error: Fs "S3 root" can't rename files (no server-side Move or Copy)
<3>ERROR : folder/TEST.txt: Dir.Rename error: Fs "S3 root" can't rename files (no server-side Move or Copy)
<3>ERROR : IO error: Fs "S3 root" can't rename files (no server-side Move or Copy

rclone --version shows this:
rclone v1.60.0
- os/version: arch (64 bit)
- os/kernel: 5.15.77-1-lts (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.2
- go/linking: dynamic
- go/tags: none

**Comment by ncw** [comment]
@dominus-imperium this issue is about the storj native interface where I think you are using the s3 interface? Can you make a new issue about this please?

**Comment by dominus-imperium** [comment]
> @dominus-imperium this issue is about the storj native interface where I think you are using the s3 interface? Can you make a new issue about this please?

https://github.com/rclone/rclone/issues/6550

new issue made
