### ISSUE TITLE
Parallel running migration Logs segregation for RCD Server

### ISSUE THREAD

**Issue by kirtibajaj** [rclone/rclone#5962]
Hey,
What is the way to seggregate the logs for concurrent command running for multiple jobs for rcd server.
I am facing problem with separating the concurrent logs for parallel jobs.
Thanks

**Comment by ncw** [comment]
I don't think this is possible at the moment.

It would be possible to add the Job ID into the log using the `--log-format` command string.

However this would mean making all the logging calls take a context parameter. Which is possible and would then let each job return just its own logs.

It is a lot of work to thread context through every log though.

**Comment by animosity22** [comment]
Already answered and asked on the forums...
