### ISSUE TITLE
dedupe: be careful rewriting only source

### ISSUE THREAD

**Issue by caffeinum** [rclone/rclone#5963]
I worry about `dedupe` rewriting sometimes the only source of the data. Google Drive is a pain to work with many files in web interface, so if something goes wrong, there's virtually no way to make it back.

I would love to have either option to:
- control resulting filenames
- create a backup directory automatically

First one looks easy, basically just passing rename pattern from outside the function:
https://github.com/rclone/rclone/blob/07f53aebdc89e345ab1b693e8121846915c796b5/fs/operations/dedupe.go#L31

Second one is (almost) possible to do manually, but you still need to be careful to not mess anything up. I would go with something like this, except duplicates already weren't downloaded, so you cannot back them up!

```bash
rclone sync drive:dupes ./drive/dupes
rclone sync ./drive/dupes drive:dupes-backup
rclone dedupe drive:dupes
```

Another place where I would love this feature is that if somebody has shared a read-only directory with me, which I need to download to my . I can't edit in-place, but I can clone it to my google drive, and then dedupe.

-----

I wonder what are your thoughts on this? I don't really feel secure `dedupe`-ing 100 Gb directory, especially if these are my clients files, for example.

**Comment by caffeinum** [comment]
P.S. On a side note, it might be a good idea to allow renaming by checksum pattern instead of only number. Something like
```golang
ht := f.Hashes().GetOne()
hashValue := o.Hash(ctx, ht)
newName := fmt.Sprintf("%s-%s", base, hashValue, ext)
```

So `file.jpg` becomes: `file-deadbeef.jpg`

**Comment by ncw** [comment]
> I worry about `dedupe` rewriting sometimes the only source of the data. Google Drive is a pain to work with many files in web interface, so if something goes wrong, there's virtually no way to make it back.

Dedupe will delete identical files with the same names, hashes and sizes - this isn't usually problematic. These files are sent to the trash also (provided you haven't set hard delete) so can be recovered.

Dedupe will rename (assuming you are using  `--dedupe-mode rename` or the equivalent option in the interactive tool) the files to different names.

> I would love to have either option to:
> 
> * control resulting filenames

So control what the `--dedupe-mode rename` command uses as filenames? That doesn't sound unreasonable!

> * create a backup directory automatically

Not quite sure what you want here - to move all the duplicated files to a single directory?

Imagine we had a command line flag to do it - how would you describe it?

> ```shell
> rclone sync drive:dupes ./drive/dupes
> rclone sync ./drive/dupes drive:dupes-backup
> rclone dedupe drive:dupes
> ```
> 
> Another place where I would love this feature is that if somebody has shared a read-only directory with me, which I need to download to my . I can't edit in-place, but I can clone it to my google drive, and then dedupe.
> 
> I wonder what are your thoughts on this? I don't really feel secure `dedupe`-ing 100 Gb directory, especially if these are my clients files, for example.

dedupe has a --dry-run flag like the rest of rclone, so you can try it and examine the log to see what it would have done.

**Comment by caffeinum** [comment]
@ncw it's not that I can't recover them manually, but the thing I don't want to manually recover thousands of files. If it were just a few files in the first place, I wouldn't use a command line tool!

I guess my smallest feature request would be so that instead of renaming in-place, files would be copied to another directory, AND renamed there. Something like `rsync dedupe drive:dupes --to new_dir` (local directory) or `rsync dedupe drive:dupes --to drive:dupes-renamed` (remote directory)

Second option would be possible with `sync`, but in current implementation it DOESN'T work, because it still tries to rename them in-place.

This is also a good option for read-only directory access – that was my case where the client has shared with me 3000 files, many of which has had duplicate names. I couldn't download them to my local machine due to filesize, and couldn't `rsync` them to my Ubuntu cloud machine either because of the naming issue.

**Comment by animosity22** [comment]
Is there anything else on this one? It looks asked/answered to me but not sure.

**Comment by caffeinum** [comment]
@animosity22 actually it's not, my feature-request was to make it possible to `dedupe` a big directory in a read-only Google Drive. Right now it neither allows me to download the files (due to duplicate names) nor re-write (because I lack permissions)
