### ISSUE TITLE
optional data in onboarding process of Google Drive

### ISSUE THREAD

**Issue by viveknathani** [rclone/rclone#5967]
#### What is the problem you are having with rclone?

I was using `rclone config` and the [docs](https://rclone.org/drive/#making-your-own-client-id) to setup rclone for Google Drive. Step 5 in [this](https://rclone.org/drive/#making-your-own-client-id) section says that "all other data is optional" so it can be left empty except "Application name". But I had to enter user support email and developer contact email too. Screenshot attached below. I ended up giving my own email but I believe this aspect should be documented too. Happy to submit a PR for this.

![image](https://user-images.githubusercontent.com/52988856/151710696-b1c38e8c-1d99-48a1-aa7a-edc754bd2559.png)

#### What is your rclone version (output from `rclone version`)
v1.57.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
ubuntu 20.04 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone config`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
not needed in this case

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
By all means, submit a PR if something has changed.
