### ISSUE TITLE
obscure sdtin only first line

### ISSUE THREAD

**Issue by DEvmIb** [rclone/rclone#5968]
i am using only /dev/random for passwords and today i seen that rclone read stdin only the first line on input and as a result the password could be weak.

fixing myself to end my project. please pros check that code, i have tested the md5 after input and it seem to work for me.

#https://github.com/DEvmIb/rclone/commit/0b06789480885e791bd71de1f4820c075f7485e0

**Comment by ncw** [comment]
I don't think we can change this without a flag, as it will break lots of stuff, eg

    echo "password" | rclone obscure

Currently doesn't include the `\n` in the password which is what most people would expect.

**Comment by DEvmIb** [comment]
changed my code and adding flags, for interessed people

#https://github.com/DEvmIb/rclone/commit/b7a652e9401e95d268ce9c44d9f510b24fa1647e

rclone obscure test
echo test| rclone obscure -
rclone obscure --pass-file /file/to/read
rclone obscure --pass-cmd "mosquitto_rr -h mosquitto -t test -e test/test -m test"

**Comment by ncw** [comment]
I'd prefer a flag, say `--binary`

    --binary read all the input data including new lines into the password

Then you'd do

```
rclone obscure --binary - </file/to/read
mosquitto_rr -h mosquitto -t test -e test/test -m test | rclone obscure --binary -
```

**Comment by ncw** [comment]
I'm going to close this as it doesn't seem to be a problem for anyone else.
