### ISSUE TITLE
SFTP and new provider borgbase.com

### ISSUE THREAD

**Issue by git70** [rclone/rclone#5974]
Hi All!

The [list of providers](https://rclone.org/#providers) is Rsync.net and SFTP (SSH).
Does this mean that it can work with the [Rsync.net version for Borgbackup](https://www.rsync.net/products/borg.html)?
If so, can you add native support for [Borgbase.com](https://www.borgbase.com/)?
A fantastic service dedicated to Borg, also used SSH.
(Also developer and sponsor [Vorta](https://vorta.borgbase.com/) - GUI for Borg)

Best Regards!

**Comment by animosity22** [comment]
Rclone support rsync.net
Borg looks to have made their app also work with rsync.net

Rclone doesn't support borgbase.com native and doesn't seem there is much of an API so doubtful it will ever happen.

If you need any questions answered, please use the forums rather than asking in issues as we keep this for bugs and feature requests.

https://forum.rclone.org

Thanks!

**Comment by ncw** [comment]
> A fantastic service dedicated to Borg, also used SSH.

Does borgbase support SFTP? Or does it only support the proprietary borg protocol over SSH?

I looked at implementing the borg protocol in rclone, but it isn't documented except in the source code of borg which kind of put me off!

**Comment by git70** [comment]
We need to organize knowledge:

1. Borg may operate in two modes:
a) SFTP on the remote SSHFS file system (then all operations are performed locally by Borg)
b) Clean SSH If BorgServe is installed on the server (then part of the operation performs borg by relieving the network and client)
Quote from https://borgbackup.readthedocs.io/en/stable/index.html
"Borg Can Store Data on Any Remote Host Accessible Over SSH. IF Borg Is Installed on the Remote Host, Big Performance Gains Can Be Achieved Compared To Uting A Network Filesystem (SSHFS, NFS, ...)"
@ThomasWaldmann can you confirm?

2. It seems to me that Rsync.net works in both modes to choose from:
a) BorgServe installed on the server if you connect directly from BorgClient
b) uses SFTP if you connect via Rclone
https://rclone.org/sftp/#rsync-net
I think so because it has dedicated offers:
https://www.rsync.net/products/rclone.html
https://www.rsync.net/products/borg.html
@rsyncnet can you confirm?

3. @m3nu can you explain how Borgbase works?
If it works by SFTP, it's enough to add to the list of providers and you do not have to do anything :)
Is BorgServe running on Borgbase?

These are just my assumptions. The confirmation of the above-mentioned people are needed.

**Comment by animosity22** [comment]
Forums would be a superb spot for discussions as it gets more traffic and can be organized into an actual request..

**Comment by git70** [comment]
Yes, I know and sorry, but I just wanted to answer @ncw on his question.
In addition, it's easier to call other developers to answer questions.
Do not be angry that this one thread will carry out here :(
Actually, this is like Feature Request ;)

**Comment by animosity22** [comment]
It has nothing to do with being angry.

The goal of any process is produce a win-win outcome for both so we have a template for a feature request and bug report. We ask folks to try to follow the process as it helps you and me out to produce a desired outcome.

The feature request template has a checklist:

```
If it still isn't there, here is a checklist of things to do:

  1. Search the old issues for your idea and +1 or comment on an existing issue if possible.
  2. Discuss on the forum: https://forum.rclone.org/
  3. Make a feature request issue (this is the right place!).
  4. Be prepared to get involved making the feature :-)

```

So we're hoping to do #2, get some solid discussion and once things are formalized, a feature request is opened up.

**Comment by ThomasWaldmann** [comment]
borg **only** supports:
- client/server using ssh and a remote borg.
- a locally mounted filesystem

borg does **not** support sftp.

**Comment by git70** [comment]
Sorry, but I don't understand it anymore (maybe I'm too tired because I haven't slept for 3 days doing a deep search for backup programs):

Why is SFTP mentioned here?
https://borgbackup.readthedocs.io/en/stable/search.html?q=sftp&check_keywords=yes&area=default
https://github.com/borgbackup/borg/search?q=sftp&type=issues

In case of using Rclone it doesn't matter because Borg sees the repository as a local folder. It's more about how to connect Rclone with Borgbase.

**Comment by m3nu** [comment]
> Why is SFTP mentioned here?

This talks about FUSE and SSHFUSE. Not really related to Borg.

Regarding BorgBase.com, we do support Rsync and SFTP, but only to do small edits or import and export raw portfolio data. It's not meant for running Borg or doing backups.

> Does this mean that it can work with the [Rsync.net version for Borgbackup](https://www.rsync.net/products/borg.html)?

As Thomas said, Borg can use SSH as transport protocol. Like S3 uses HTTP as transport protocol. It still needs the Borg CLI running on both ends. Rsync.net offers this, as does BorgBase.com. SSH access + `borg serve`.

With that said, I appreciate the interest, but I don't think any feature or support can be added to Rclone here, since it does different things than Borg. (It's still great and I'm a regular user 👍)

The only thing I could see is using Rclone as SFTP client when moving data in or out of BorgBase. This is a pretty minor use case and I imagine the generic Rclone SFTP remote already supports this well. So nothing left to do.

**Comment by ncw** [comment]
Thank you @m3nu for the definitive statement.

Related: There is an issue here about making rclone into a borg provider: https://github.com/borgbackup/borg/issues/5324 and another here about getting rclone to speak the `borg serve` protocol directly: https://github.com/borgbackup/borg/issues/1070#issuecomment-553627730

So given that rclone can already (most likely) use borgbase via SFTP and that the borg native protocol is in other issues, I think we are done with this issue!

**Comment by git70** [comment]
Until now, I thought Borg in two modes to choose from:
1. Without `borg serve`
2. Along with `borg serve` (then part of the operation is executed on the remote end)

Thank you guys for your help and explanation!
You do a great job!
If you think this information will not be useful for anyone, you can delete this thread so that you do not clutter ...
