### ISSUE TITLE
Anomalous "rclone check" behavior (output is not redirected)

### ISSUE THREAD

**Issue by Salim9304** [rclone/rclone#5975]
`
rclone check source:path dest:path
`
I am getting output in terminal.  But as soon as I try to redirect the output to a file (it doesn't redirect, it prints it in the terminal again).  This is the first time I've encountered such an anomaly.

bad does not work
`
rclone check source:path dest:path > log.txt
`

**How to redirect output to "rclone check" file?**

**Comment by animosity22** [comment]
Please use the forums for general use questions:

https://forum.rclone.org

**Comment by Salim9304** [comment]
> 

It was not so much a question as a BUG!  Please fix this issue.  This is an anomaly (any program is capable of redirecting output to a file), rclone can't, it's just not possible.

**Comment by animosity22** [comment]
If you make a post on the forum and use the help and support template, we can validate if you got a bug or not and I'll personally open a proper bug report based on your post.

**Comment by Salim9304** [comment]
`rclone check source:path dest:path > log.txt #that's all it takes to check`

Likewise, the user can't do anything with the output, for example this won't work either (do you know of any cli program that can't redirect output? I don't know of any).
`rclone check ~/file dest:path | base64` #bad

The log.txt file should have terminal output (it's not there).  This is easy to check on any device and OS.  Unfortunately, I can't register on the forums.  If this is so important to you, then let the bugs live in the application.  I'm just upset.

**Comment by animosity22** [comment]
it is upsetting when folks can't follow a simple template so I'm right with you:

What is the problem you are having with rclone?
What is your rclone version (output from rclone version)
Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Which cloud storage system are you using? (e.g. Google Drive)
The command you were trying to run (e.g. rclone copy /tmp remote:tmp)
A log from the command with the -vv flag (e.g. output from rclone -vv copy /tmp remote:tmp)
How to use GitHub
Please use the 👍 reaction to show that you are affected by the same issue.
Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
You use the --log-file parameter btw:

```
2022/02/02 10:25:51 DEBUG : Setting --config "/opt/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/opt/rclone/rclone.conf"
felix@gemini:~$ cat /tmp/test.log
2022/02/02 10:25:43 NOTICE: Dropbox root 'test': 0 differences found
2022/02/02 10:25:51 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "check" "/home/felix/test" "DB:test" "--log-file" "/tmp/test.log" "-vvv"]
2022/02/02 10:25:51 DEBUG : Creating backend with remote "/home/felix/test"
2022/02/02 10:25:51 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2022/02/02 10:25:51 DEBUG : Creating backend with remote "DB:test"
2022/02/02 10:25:52 INFO  : Using dropbox for hash comparisons
2022/02/02 10:25:52 DEBUG : Dropbox root 'test': Waiting for checks to finish
2022/02/02 10:25:52 NOTICE: Dropbox root 'test': 0 differences found
2022/02/02 10:25:52 INFO  :
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:         0.2s

2022/02/02 10:25:52 DEBUG : 7 go routines active
2022/02/02 10:25:52 INFO  : Dropbox root 'test': Commiting uploads - please wait...
```

**Comment by Salim9304** [comment]
Indeed, if you replace the redirect operator ">" with "--log-file" then it works, but it is unix-contradictory (I still don't understand how this is possible, for example this command "rclone lsd dest: > file.log" successfully redirects the output  to a file (as it should be, but there is no "check" - it's just incredible).

**Comment by animosity22** [comment]
Kind of. 

It's STDERR not STDOUT.

```
felix@gemini:~$ rclone check /home/felix/test DB:test > /tmp/blah.log
2022/02/02 10:41:18 NOTICE: Dropbox root 'test': 0 differences found
felix@gemini:~$ cat /tmp/blah.log
felix@gemini:~$ rclone check /home/felix/test DB:test > /tmp/blah.log 2>&1
felix@gemini:~$ cat /tmp/blah.log
2022/02/02 10:41:27 NOTICE: Dropbox root 'test': 0 differences found
```

**Comment by Salim9304** [comment]
To summarize (for those who find this problem) here is a solution with redirecting the STDERR stream:
`rclone check source:path dest:path >> log.txt 2>&1`

**Comment by animosity22** [comment]
The general concept is log goes to stderr, output from the command goes to stdout.

Most commands don't have any output, but some do like rclone size or rclone ls.

Still love to understand why you can't register on the forums as I'm happy to help with that...
