### ISSUE TITLE
Program to request support for s90x kernel machines

### ISSUE THREAD

**Issue by xiaoxiaofeixf** [rclone/rclone#5978]
#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
What is a S90X kernel machine?

**Comment by xiaoxiaofeixf** [comment]
> What is a S90X kernel machine?

It is a unique cpu machine from ibm one company

**Comment by animosity22** [comment]
Rclone is a GO program so does the CPU/OS you are running support GO?

https://go.dev/dl/

If so, there should already be a binary for it. If it doesn't support GO, rclone can't support it.

Closing out.

**Comment by ncw** [comment]
Rclone can be compiled for linux running on a s390x - is that what you mean @xiaoxiaofeixf ?

Cross compile it on Windows or linux with

```
export GOOS=linux
export GOARCH=s390x
go build
```

**Comment by ncw** [comment]
@xiaoxiaofeixf here is an s390x binary - give it a go!

[rclone.gz](https://github.com/rclone/rclone/files/8010030/rclone.gz)
