### ISSUE TITLE
--stats-one-line not repositioning cursor when piped

### ISSUE THREAD

**Issue by peterberbec** [rclone/rclone#5980]
#### Output of `rclone version`

rclone v1.57.0
- os/version: ubuntu 21.10 (64 bit)
- os/kernel: 5.11.0-37-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.2
- go/linking: static
- go/tags: none

I'm on Ubuntu 21.04

#### Describe the issue

When using `--progress --stats-one-line(-date)` in a script that gets piped to a log file, the output does not update over the same line properly. 

#### Expected result

`2022/02/05 02:35:49 -    10.051k / 67.363 TBytes, 0%, 1.756 kBytes/s, ETA 135y38w8h44m46s580ms (xfr#1/10016)`

#### Actual Result

`2022/02/05 02:37:18 -          0 / 60.847 TBytes, 0%, 0 Bytes/s, ETA - (xfr#0/622022/02/05 02:37:19 -          0 / 60.847 TBytes, 0%, 0 Bytes/s, ETA - (xfr#0/622022/02/05 02:37:19 -          0 / 60.847 TBytes, 0%, 0 Bytes/s, ETA - (xfr#0/622022/02/05 02:37:20 -          0 / 60.847 TBytes, 0%, 0 Bytes/s, ETA - (xfr#0/622022/02/05 02:37:20 -          0 / 65.962 TBytes, 0%, 0 Bytes/s, ETA - (xfr#0/352022/02/05 02:37:21 -          0 / 65.962 TBytes, 0%, 0 Bytes/s, ETA - (xfr#0/352022/02/05 02:37:21 -          0 / 65.962 TBytes, 0%, 0 Bytes/s, ETA - (xfr#0/352022/02/05 02:37:22 -          0 / 65.962 TBytes, 0%, 0 Bytes/s, ETA - (xfr#0/3`

And yes, that is one line that I truncated: this continued for the whole trasfer.  It keeps appending the output to the end of line instead of resetting the cursor position. 

This occurs with or without `2&>1`, so it doesn't seem to be a stdout/stderr issue.

**Comment by animosity22** [comment]
Progress is meant for interactive output to a terminal.

You can use --log-file with --stats-one-line -v as an example to get information.
