### ISSUE TITLE
How to make rclone load cache indefinitely from last position (or from the start of the video)?

### ISSUE THREAD

**Issue by Darkmaster006** [rclone/rclone#5985]
This is probably a feature that's already present but I've looked and I don't know how to do it. So let's say I'm watching a video:
![image](https://user-images.githubusercontent.com/21136515/153461569-8149b763-72af-44b1-b0c5-5292d66e5530.png)
Like this, and I've closed it before and then started from another part (or I've started from the beginning, same thing), what I'd like is for that cache bar to load indefinitely so that the video could load and I could have it to watch entirely when I'm watching it, so that it loads the video cache even when I'm not playing it (my internet is slow, so that if the cache stops loading and then loads only when I start playing, the video could stutter because it loads slowly). Is there any way to set this? This is mounted on a Google Drive in Linux Mint 20.2 Uma. Thank you very much.

**Comment by Darkmaster006** [comment]
> You would have to either have a video player that supports buffering the entire file, increase the amount of blocks that rclone reads ahead, or read the whole file in manually and just increase rclone's cache expire time period

I believe MPV can buffer the entire file, as it's buffered entire MEGA files before. I guess the problem is the size, which is this case is about 3 GB. I would like to increase the amount of blocks that rclone reads ahead. As of now, it seems to be one block of around maybe 250M which might be the default, since I've not set anything regarding that, but which is the command to set the size of the blocks or the number of blocks that rclone reads ahead? Thank you.

**Comment by Masamune3210** [comment]
![image](https://user-images.githubusercontent.com/1053504/153467026-c834ef64-a5d0-42e5-8edc-1b055db641fe.png)

**Comment by Darkmaster006** [comment]
> ![image](https://user-images.githubusercontent.com/1053504/153467026-c834ef64-a5d0-42e5-8edc-1b055db641fe.png)

Thank you, I've read that in https://rclone.org/commands/rclone_mount/ now, the --vfs-cache-mode full section. Trying with 'rclone mount Drive: /media/drive --bwlimit 950k --vfs-cache-mode full --vfs-read-ahead 500M &' at the moment, which does not seem to work, buffering only resumes after the chunk is done (same chunk as before) when the file is playing.

**Comment by animosity22** [comment]
Please use your forum post for discussions and not double post:

https://forum.rclone.org/t/how-to-make-rclone-load-cache-indefinitely-from-last-position/29194
