### ISSUE TITLE
Slow local sync

### ISSUE THREAD

**Issue by mrx23dot** [rclone/rclone#5987]
#### What is the problem you are having with rclone?
Syncing 5000 (4GB) files to USB for 2nd time takes 1minutes with this:
`rclone sync "D:\\test" "Y:\\test" --progress --ignore-checksum --ignore-size `
same for
`rclone sync "D:\\test" "Y:\\test" `
in progress it says 'checking' a lot

This takes only 0.1sec: (the goal)
`rclone sync "D:\\test" "Y:\\test" --progress --size-only
`

mod.times and sizes matches, so why does it take so long?

I would expect super fast match with size+time first, and only if those differ a slow checksum check.
Also ignore-checksum for local transfer seems to still calculate it.

#### What is your rclone version (output from `rclone version`)
rclone v1.57.0
#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
win7 x64
Antivir disabled

#### Which cloud storage system are you using? (e.g. Google Drive)
USB pendrive 15MB/s

**Comment by mrx23dot** [comment]
Detailed log say:
```
2022/02/10 23:40:29 DEBUG : 1265674333_68.jpg: Modification times differ by 1.3928903s: 2012-09-05 13:06:46.6071097 +0100 BST, 2012-09-05 13:06:48 +0100 BST
2022/02/10 23:40:29 DEBUG : 1265674333_68.jpg: md5 = c968e2068e7dd0b0d10c7831399a6966 OK
2022/02/10 23:40:29 INFO  : 1265674333_68.jpg: Updated modification time in destination
2022/02/10 23:40:29 DEBUG : 1265674333_68.jpg: Unchanged skipping
```

- so after reading back modification time for the 1st time I always get 1.39s difference, why is that?
- why isn't md5  suppressed by  --ignore-checksum ?

**Comment by animosity22** [comment]
For general use questions, it's much better to use the forums.

That being said, you only have a snippet of a log so I am not sure what you ran.

Example full log:

No checksum
```
felix@gemini:~$ rclone sync /home/felix/test /home/felix/test2 -vvv --ignore-checksum --ignore-size
2022/02/10 19:58:27 DEBUG : Setting --config "/opt/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/opt/rclone/rclone.conf"
2022/02/10 19:58:27 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "sync" "/home/felix/test" "/home/felix/test2" "-vvv" "--ignore-checksum" "--ignore-size"]
2022/02/10 19:58:27 DEBUG : Creating backend with remote "/home/felix/test"
2022/02/10 19:58:27 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2022/02/10 19:58:27 DEBUG : Creating backend with remote "/home/felix/test2"
2022/02/10 19:58:27 DEBUG : Local file system at /home/felix/test2: Waiting for checks to finish
2022/02/10 19:58:27 DEBUG : Local file system at /home/felix/test2: Waiting for transfers to finish
2022/02/10 19:58:27 INFO  : hosts: Copied (new)
2022/02/10 19:58:27 DEBUG : Waiting for deletions to finish
2022/02/10 19:58:27 INFO  :
Transferred:   	        184 B / 184 B, 100%, 0 B/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         0.0s

2022/02/10 19:58:27 DEBUG : 4 go routines active
felix@gemini:~$ rm /home/felix/test2/hosts
```

Checksum
```
felix@gemini:~$ rclone sync /home/felix/test /home/felix/test2 -vvv
2022/02/10 19:59:31 DEBUG : Setting --config "/opt/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/opt/rclone/rclone.conf"
2022/02/10 19:59:31 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "sync" "/home/felix/test" "/home/felix/test2" "-vvv"]
2022/02/10 19:59:31 DEBUG : Creating backend with remote "/home/felix/test"
2022/02/10 19:59:31 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2022/02/10 19:59:31 DEBUG : Creating backend with remote "/home/felix/test2"
2022/02/10 19:59:31 DEBUG : Local file system at /home/felix/test2: Waiting for checks to finish
2022/02/10 19:59:31 DEBUG : Local file system at /home/felix/test2: Waiting for transfers to finish
2022/02/10 19:59:31 DEBUG : hosts: md5 = 0d603989599e838cf5fa5822d7257329 OK
2022/02/10 19:59:31 INFO  : hosts: Copied (new)
2022/02/10 19:59:31 DEBUG : Waiting for deletions to finish
2022/02/10 19:59:31 INFO  :
Transferred:   	        184 B / 184 B, 100%, 0 B/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         0.0s

2022/02/10 19:59:31 DEBUG : 4 go
```

**Comment by mrx23dot** [comment]
Found the reason, on FAT filesystem timestamp resolution is +-1sec, so files are always detected as modified and MD5 is calculated before transfer.

So could we auto detect filesystems and modify time window accordingly? It's already done to OS X.
We shouldn't expect every user to figure this out.

doc
```
--modify-window=TIME
The default is 1ns unless this is overridden by a remote. For example OS X only stores modification times to the nearest second so if you are reading and writing to an OS X filing system this will be 1s by default.
```

**Comment by animosity22** [comment]
See:

https://forum.rclone.org/t/having-an-issue-while-syncing-two-local-copies/4197/4?u=animosity022

Closing this out as answered. Please use the forums for general questions. Thanks!

**Comment by mrx23dot** [comment]
I wouldn't close it so fast, as said in the forum:
"Rclone uses some heuristics to guess what to use, but it doesn’t always get it right."

Looks like the look up value is not correct for FAT* filesystems.
This can be easily fixed, and prevent future complaints.

**Comment by animosity22** [comment]
Feel free to open a pull request to address.

Thanks!

**Comment by mrx23dot** [comment]
I couldn't find any reference to heuristics to figure out window.

default:
`	c.ModifyWindow = time.Nanosecond`

this don't apply to FAT:
```
dow == fs.ModTimeNotSupported {
			// Otherwise use 1 second as a safe default as
			// the resolution of the time a file was
			// uploaded.
			modifyWindow = time.Second

```

**Comment by albertony** [comment]
> I couldn't find any reference to heuristics to figure out window.

It's here:

https://github.com/rclone/rclone/blob/e43b5ce5e59b5717a9819ff81805dd431f710c10/backend/local/local.go#L608

Maybe your case is the same as [this:](https://github.com/rclone/rclone/issues/5584)

> local.go / readPrecision() is testing the wrong filesystem. It always tests the host's tmp folder, which is totally unrelated to the filesystems being used for the operations.
