### ISSUE TITLE
How I can "complete" my command?

### ISSUE THREAD

**Issue by spmoonz** [rclone/rclone#5988]
I have a multi line rclone command like that:
```
  rclone mount x:/ /volume1/myCloud/x \
  --config=/volume1/xxx/rclone.conf \
  --umask 0000 \
  --default-permissions \
  --allow-non-empty \
  --allow-other \
  --transfers 5 \
  --low-level-retries 200 \
  --dir-cache-time 12h \
  --vfs-read-chunk-size 32M \
  --vfs-read-chunk-size-limit 1G \
  --vfs-cache-mode full \
  --buffer-size 32M \
  --vfs-read-ahead 3G \
  --no-update-modtime \
  --no-modtime
```

When I finish typing the last line of command and pressed `Enter`...emm I don't know how to express it, but it just goes to the next line, and doesn't "complete" my command.
Finally, I had to use `^C` to abort, but this makes the command invalid.
So I want to know how I can "complete" my command?

My system:
Synology NAS (DSM 6.2.3-25426)

rclone v1.57.0
os/version: unknown
os/kernel: 4.4.59+ (x86_64)
os/type: linux
os/arch: amd64
go/version: go1.17.2
go/linking: static
go/tags: none

**Comment by animosity22** [comment]
Please use the forums for general use questions.

We try to keep this for bugs and feature requests.

https://forum.rclone.org/
