### ISSUE TITLE
Allow running web-ui without authentication

### ISSUE THREAD

**Issue by discordianfish** [rclone/rclone#5989]
#### What is your current rclone version (output from `rclone version`)?
v1.57.0

#### What problem are you are trying to solve?
I want to run the rcd+web-ui behind a reverse proxy that already takes care of auth.

#### How do you think rclone should be changed to solve that?
Allow running the webui and required rcd methods without auth.

I can implement that if the maintainers agree that they want to support that. Maybe it could require another flag to make it explicit and clear that this is insecure if the endpoint isn't further restricted like in my case.

**Comment by animosity22** [comment]
That's over here:

https://github.com/rclone/rclone-webui-react/issues/37

**Comment by animosity22** [comment]
Closing out as it is answered and tracked on the issue shared.

**Comment by discordianfish** [comment]
Ah sorry about the noise, I though this is a restriction implemented in rclone.
