### ISSUE TITLE
env_auth=true not working with Minio provider

### ISSUE THREAD

**Issue by EugenMayer** [rclone/rclone#5990]
#### What is the problem you are having with rclone?
Trying to authenticate with an s3 type, provider minio, while using `env_auth=true`
Hint: using access-key/secret key configurations inside `~/.config/rclone/rclone.conf` does work

i configured this in `~/.config/rclone/rclone.conf`

```
[minio1]
type = s3
provider = Minio
env_auth = true
endpoint = https://minio1.<redacted-host>:<redacted-non-default-port>
location_constraint = de
acl = authenticated-read
```

I also have the following env variables set (as by https://rclone.org/s3/)

```
RCLONE_S3_PROVIDER=Minio
RCLONE_S3_ENDPOINT=https://minio1.<redacted-host>:<redacted-non-default-port>
RCLONE_S3_LOCATION_CONSTRAINT=de
RCLONE_S3_ACL=authenticated-read
RCLONE_S3_ACCESS_KEY_ID=<redacted-access-key>
RCLONE_S3_SECRET_ACCESS_KEY=<redacted-acces-secret>
```

It seems like the authentication either fails or even the wrong endpoint is used (thus the rather long 60s timeout?).

**workarround**  
if i just add/change `~/.config/rclone/rclone.conf`

```
env_auth = false
access_key_id = <redacted-access-key>
secret_access_key = <redacted-acces-secret>
```

to my rclone alias configuration - it will work without issues. So my general access and transport layer / secrets are just fine.
It just started with the fact that i want to use env based authentication to split the secrets out of the `rclone.conf`

#### What is your rclone version (output from `rclone version`)
```
rclone --version
rclone v1.57.0
- os/version: debian 11.2 (64 bit)
- os/kernel: 5.10.0-9-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.2
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
debian 11.2 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)
The source s3 is an most recent Minio

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone sync --verbose minio1:testbucket /tmpt/test`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2022/02/13 10:13:52 INFO  : 
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:       3m0.1s

2022/02/13 10:14:52 INFO  : 
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:       4m0.1s
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by EugenMayer** [comment]
Reading https://github.com/rclone/rclone/blob/master/backend/s3/s3.go#L1843 i assume that the docs currently are a bit confusing.

For every flag there is an ENV var, but env_auth is entirely and complete AWS related and AFAICS also relies on shared config files and all this.

I'am not sure it is all by design, but i would suggest either of this options:

a) fixing the docs on env_auth and call it what it is, AWS shared secret auth in AWS only environments. It seems to be AWS only. This
  - also the env variables `RCLONE_S3_ACCESS_KEY_ID` and `RCLONE_S3_SECRET_ACCESS_KEY` should be not in the docs, or i miss read the code. There is nothing actually picking those up / there is no support for those (yet)?
  - also do not silently fallback to 'anonymous' if no credentials are found, maybe at least a hint when `--verbose` is used
b) actually implement env_auth to either do what it does right now (legacy support/aws specific support) and also support the env vars `RCLONE_S3_ACCESS_KEY_ID` and `RCLONE_S3_SECRET_ACCESS_KEY` if they exist / are set.

**Comment by EugenMayer** [comment]
I might be wrong with a) if https://github.com/rclone/rclone/blob/master/backend/s3/s3.go#L1783 actually means that the credentials should not be exposed via `RCLONE_S3_ACCESS_KEY_ID`/`RCLONE_S3_SECRET_ACCESS_KEY` but rather `AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY`

If that is really the case, i would still argue we need to do something about `RCLONE_S3_ACCESS_KEY_ID`/`RCLONE_S3_SECRET_ACCESS_KEY`  being named as the ENV based variables for `--s3-access-key-id`/ `--s3-secret-access-key` - we should rather rename them to `AWS_ACCESS_KEY_ID`/`AWS_SECRET_ACCESS_KEY` in the docs are explain, when which of this is actually used (especially the RCLONE ones are unclear to me)

**Comment by ncw** [comment]
env_auth is for picking up the s3 credentials from the environment in an s3 standard way. That's documented here

https://rclone.org/s3/#authentication

You can set any backend config parameter 
eg  `access_key_id` as an environment variable  RCLONE_S3_ACCESS_KEY_ID or a command line flag --s3-access-key-id

I see where your confusion is coming from, the docs for the env_auth parameter could be clearer.

**Comment by EugenMayer** [comment]
Setting the parameters via env, e.g. `RCLONE_S3_ACCESS_KEY_ID` does not work - might not have been stated clear enough above probably. Neither `RCLONE_S3_ACCESS_KEY_ID` nor `RCLONE_S3_SECRET_ACCESS_KEY` are used 

To be honest, i did entirely miss the section https://rclone.org/s3/#authentication - i'am confused myself, since i was skimming the docs several times, quiet a while and the section obviously makes sense.

The way it is described there is pretty clear, would have helped me a lot - sorry.

---

Still i guess we should ensure that people do not trip over the `RCLONE_S3_ACCESS_KEY_ID` / `RCLONE_S3_SECRET_ACCESS_KEY` variables, right? They seem to be there for no reason but are mentioned as the "ENV" alternatives to the configuration / cli flags - which they are not. `AWS_ACCESS_KEY_ID` /`AWS_ACCESS_KEY`/ `AWS_SECRET_ACCESS_KEY` /`AWS_SECRET_KEY` are

**Comment by ncw** [comment]
> Setting the parameters via env, e.g. `RCLONE_S3_ACCESS_KEY_ID` does not work

They should work, but you will need `env_auth = false` (the default) to make them work.

**Comment by EugenMayer** [comment]
Sorry - this is simply not working for me. Did you try that yourself? Just asking, because i can neither get it working, nor i find the code for that (yet)

**Comment by EugenMayer** [comment]
I found the issue - `source` does not work with rclone - means this if your do

```
source secrets && rclone
```

it wont work - the env vars are not read. While

```
RCLONE_S3_ACCESS_KEY_ID=XXX RCLONE_S3_SECRET_ACCESS_KEY=YYY rclone 
```

will

**Comment by EugenMayer** [comment]
By a sidenote, it seems like `RCLONE_S3_ENDPOINT` is not working

RCLONE_S3_ENDPOINT=<> rclone

seems to be ignored

**Comment by ncw** [comment]
> I found the issue - `source` does not work with rclone - means this if your do
> 
> ```
> source secrets && rclone
> ```
> 
> it wont work - the env vars are not read. While

I think if you write

```
export VAR=VALUE
```

in your source file then it will work.

**Comment by mirekphd** [comment]
@ncw there is one thing that `restic` (not recommended) achieves much simpler: it makes is possible to specify provider (like MinIO/S3) through a simple prefix (like `s3:`) before the remote repo URL. This would get rid of the dreaded config file completely.

> also have the following env variables set (as by https://rclone.org/s3/)
> 
> ```
> RCLONE_S3_PROVIDER=Minio
> RCLONE_S3_ENDPOINT=https://minio1.<redacted-host>:<redacted-non-default-port>
> RCLONE_S3_LOCATION_CONSTRAINT=de
> RCLONE_S3_ACL=authenticated-read
> RCLONE_S3_ACCESS_KEY_ID=<redacted-access-key>
> RCLONE_S3_SECRET_ACCESS_KEY=<redacted-acces-secret>
> ```

**Comment by mirekphd** [comment]
OK, I found the S3/MinIO bottleneck: chunking. As soon as I switched is off (by increasing --s3-upload-cutoff to the max limit you allow of 5000MiB - could it be increased even more?), upload speeds became very competitive indeed:)

```
Transferred:        9.290 GiB / 9.290 GiB, 100%, **120.165 MiB/s**, ETA 0s
Checks:                43 / 43, 100%
Transferred:         1983 / 1983, 100%
Elapsed time:        51.3s
```

**Comment by mirekphd** [comment]
@ncw I've also noticed that `rclone copy` unlike its `restic backup` equivalent did not not discover all files before it started uploading to MinIO, which does not inspire confidence that it ever will (it discovered only 3% in my smoke test case: 10k vs. actual 300k):

```
1.2T    /home/jovyan/data
1.2T    total
331869 # <- actual files count
Transferred:       12.026 GiB / 331.827 GiB, 4%, 291.671 MiB/s, ETA 18m42s
Transferred:           27 / 10039, 0%
```

**Comment by ncw** [comment]
>  there is one thing that `restic` (not recommended) achieves much simpler: it makes is possible to specify provider (like MinIO/S3) through a simple prefix (like `s3:`) before the remote repo URL. This would get rid of the dreaded config file completely.

You can do this already, just call your remote `:s3,provider=Minio,env_auth:` using a [connection string](https://rclone.org/docs/#connection-strings) or [configure your remote with environment vars](https://rclone.org/docs/#config-file).

> There is definitely some problem with some command line arguments (not just env vars) being ignored by `rclone copy` (to MinIO). For instance I did not manage to increase either the number of concurrent threads (as seen from progress bar) or switch off checksums calc, which makes the app appear to be uncompetitively slow (when avg speed drops during stop gaps for checksum calcs)... to illustrate:

Both command line args and environment vars are fully supported by rclone. If you run with `-vv` you'll get more of an idea what is going on.

> (but at least increasing chunk with `--s3-chunk-size` (to 100 MiB) did work and it was essential for completing the backups). Note I'm using mostly command line arguments, not env vars (except for AWS credentials).

> OK , you may be interested to know that I've just found and eliminated a huge S3/MinIO bottleneck in the current version (v1.58.1) default settings: chunking. As soon as I switched is off (by increasing `--s3-upload-cutoff` argument to the max limit you allow of 5000Mi (could it be increased BTW even more?), upload speeds became very competitive indeed:) And please note that I earlier tried to increase chunk size from 5Mi to 100Mi but it did not help.

Increasing chunk size is what normally helps with S3, however minio may behave differently. 5TiB is the maximum allowed by the protocol for single part uploads, alas.

>  I've also noticed that `rclone copy` unlike its `restic backup` equivalent did not not discover all files before it started uploading to MinIO, which does not inspire confidence that it ever will (in my smoke test case it discovered only 3% of true files count and 25% of true occupied size):

Rclone copies files as it goes along - starting the copy process as soon as possible. If you want it to find all the files first, then use `--check-first`

**Comment by mirekphd** [comment]
And memory management... boy, it's first class! I've never expected the program to be willing to release unused memory immediately when it moved to smaller files! 

Compare and contrast with:
https://www.google.com/search?q=restic+heavy+memory+usage (and I'm the one with the largest triple-digit memory usage on record in `restic` in this *very smoke test* - there peak memory usage was 220 GiB and constantly growing in a hatchet pattern vs. peak 75 GiB here (used *only* when needed, i.e. during attempted uploads of those failing 18 huge 5GB+ files and then released dynamically as soon as it's was no longer needed, when we moved to small files, I mean, this is how memory mgmt should work everywhere, you deserve a medal:):
![image](https://user-images.githubusercontent.com/36706320/169313358-9198c577-0c2e-439c-937c-cefa2d8b9d32.png)

**Comment by mirekphd** [comment]
In my tests the only scenario where `--multi-thread-streams` (value other than the default 4, e.g. 8) is respected is the "checking" phase preceding backup prestores / downloads (`rclone copy` used to restore a remote MinIO repo).

> I did not manage to increase either the number of concurrent threads (as seen from progress bar
