### ISSUE TITLE
use ETag to verify S3 file transfers

### ISSUE THREAD

**Issue by asdffdsazqqq** [rclone/rclone#5993]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/how-does-rclone-verify-file-transfer-s3-to-s3/29261

#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.57.0
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.10.60.1-microsoft-standard-WSL2 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.2
- go/linking: static
- go/tags: none
```

#### What problem are you are trying to solve?
after file transfer, rclone cannot verify the dest file matches the source file.

currently, rclone relies on
--- the https protocol
--- Content-Md5: for each chunk transferred

local -> s3
1. calculate MD5 hash
2. save `X-Amz-Meta-Md5chksum` and copy source to dest
3. rclone prints `DEBUG : file.txt: md5 = fc873c046f6fdf1384d2cba806e69d6c OK`

s3 -> s3
1. if exist, get `X-Amz-Meta-Md5chksum` from source.
2. save `X-Amz-Meta-Md5chksum` for dest file metadata and copy source to dest.
3. rclone prints `DEBUG : file.txt: md5 = fc873c046f6fdf1384d2cba806e69d6c OK`

s3 -> local
have not tested in detail, can do as needed.

#### How do you think rclone should be changed to solve that?
--- ETag is calculated by s3 provider after file transfer completes. a reliable value to verify file transfers
--- have rclone verify file transfers using ETag.
--- have `rclone check` use ETag, fallback to MD5, if needed.
--- `rclone lsf` - add `--format=E` for ETag
--- `rclone hashsum` - add `ETag`

for local -> s3
1. rclone already has to calculate the MD5 hash before the file transfers starts.
in addition, calculate ETag
2. copy the file from source to dest
3. compare the dest ETag to the source ETag.

for s3 -> s3
1. if the source file had been uploaded by rclone, read the source's `X-Amz-Meta-Md5chksum` and copy that to the dest.
3. after file transfer completes, compare the dest ETag to source ETag.

thanks much,

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
The basic idea for this would be to

- Calculate the MD5 sum of each chunk as it is being streamed through rclone (we do this anyway!)
- At the end of the transfer calculate the hash of hashes and append the number of chunks
- This should be the same as the ETag on the final object

(See https://stackoverflow.com/a/19896823/164234 for the details on how to calculate the Etag)

This is very little extra work as we are already calculating MD5s for each chunk.

This would then enable a bullet proof end to end upload check for multipart objects. (We already have this for non multipart objects). We can use the MD5 sum metadata for checks in the future, safe in the knowledge that it was correct at the time of upload since the ETag matched.

Concerns

- Is this compatible with the AWS clones?
- Could this be implemented with server side copy too? I think we may get the MD5s of each chunk.

In https://github.com/rclone/rclone/pull/4740 we had an alternate approach to this which was to redefine what the S3 checksum meant. If we uses some reasonable assumptions like

- All chunks in a file are the same size
- The chunk is a multiple of 1 MiB

Then we can check the Etag for a file. It would be possible to use the Etags in `rclone check` for example if we

- added a new hash type - `S3-Etag` say
- this would need a parameter `--s3-etag-chunk-size` say which would need to be set to the same chunk size as used to upload the files

This is a lot more complicated, and there were some good ideas in that pull request.

**Comment by ncw** [comment]
I've had a go at this

[v1.58.0-beta.6000.2d93a0989.fix-5993-s3-multipart](https://beta.rclone.org/branch/fix-5993-s3-multipart/v1.58.0-beta.6000.2d93a0989.fix-5993-s3-multipart/) on branch [fix-5993-s3-multipart](https://github.com/rclone/rclone/tree/fix-5993-s3-multipart) (uploaded in 15-30 mins)

Please give it a go!

You should see an extra DEBUG message if the ETags match and an ERROR if they don't.

**Comment by ncw** [comment]
Oops, forgot to disable the check for encrypted objects.

[v1.58.0-beta.6000.81f9fcab6.fix-5993-s3-multipart](https://beta.rclone.org/branch/fix-5993-s3-multipart/v1.58.0-beta.6000.81f9fcab6.fix-5993-s3-multipart/) on branch [fix-5993-s3-multipart](https://github.com/rclone/rclone/tree/fix-5993-s3-multipart) (uploaded in 15-30 mins)

**Comment by asdffdsazqqq** [comment]
thanks much, but did not see any changes at all.
using `DEBUG : rclone: Version "v1.58.0-beta.6000.81f9fcab6.fix-5993-s3-multipart`
1. local -> s3 single part
2. local -> s3 multi part
3. s3 -> s3 multi part server side

imho, for encrypted files, should treat it the same as regular, non-crypted file.
on the fly, calculate the MD5 and ETag, transfer completes, compare that ETag to provider ETag

**Comment by ncw** [comment]
When you upload a multipart object you should see

```
2022/02/17 11:28:49 DEBUG : blob6.test: Multipart upload Etag: 6b63b3f3450db2d555c2ee109cc9c0bd-3 OK
2022/02/17 11:28:49 DEBUG : rclone-v1.58.0-beta.5896.f9321fccb.zip: md5 = e9a99fd39b444139598f997510c24076 OK
2022/02/17 11:28:49 INFO  : rclone-v1.58.0-beta.5896.f9321fccb.zip: Copied (replaced existing) to: blob6.test
```

The first line being the new one with the new check - note the `-3` in the Etag` indicating 3 parts.



> * local -> s3 single part

This should be unchanged

> * local -> s3 multi part

This is the new code

> * s3 -> s3 multi part server side

I don't think I can use the Etag for this as AWS doesn't return the ETag after copying each chunk.

> i can post the debug logs, here or back in the forum?

Here is good. You can attach them to the issue or put them inline if short.

> imho, for encrypted file, should treat it the same as regular, non-crypted file.
> on the fly, calculate the MD5 and ETag, transfer completes, compare that ETag to provider ETag

I think it should be doing that but it would be great if you could check.

**Comment by asdffdsazqqq** [comment]
sorry, i missed the ETag in the debug log

the only changes i see so far are
- local -> s3, multipart
- s3 -> s3 - same number of parts , different providers

there are an insane number permutations i am testing for.

- source and/or dest can be local or s3
- single part, multipart same number of parts, multipart different number of parts.
- server-side, not server side
- source and/or dest, same or different provider(s)
- sse-c, rclone crypt, rclone mount

i wanted to know if we could add new debug log entries to make explicitly clear when/what/if rclone is comparing?
is rclone actually comparing anything and exactly what is compared?
or 
is rclone just printing the MD5, ETag, X-Amz-Meta-Md5chksum, stuff?

just one example, for local -> s3 single part, i have no idea what rclone is doing?

in that way, i can do most of testing on my own.

there are
- rclone calculated MD5
- rclone calculated ETag
- X-Amz-Meta-Md5chksum stored at provider
- ETag stored at provider

thanks so much,

**Comment by asdffdsazqqq** [comment]
with a multipart, server-side copy, it is no clear what rclone is doing when printing
`md5 = e9a99fd39b444139598f997510c24076 OK`
seems that rclone is simply comparing the header `X-Amz-Meta-Md5chksum` between source and dest.
to many, including me, the impression is rclone is actually checking the source contents match the dest contents.
i was hoping for rclone to let us know what it is doing, what is being compared.

and about this `--bulletproof` concept, i have a suggestion that would works for
---for server-side copy.
--- multipart between servers, even if the source was not uploaded by rclone.
-- so one way or another, that rclone will always use the provider Etag for all s3 copy operations.

1. get the file size.  
2. get the number of parts from the source Etag
3. calculate the size of each part, assume each part is the same size.
4. `rclone copy source:file.txt dest:` and set the part size to match the source
5. when the file copy is done, can directly compare the source Etag and the dest Etag.
6. of course, continue to store `X-Amz-Meta-Md5chksum` as it is needed.

**Comment by ncw** [comment]
> with a multipart, server-side copy, it is no clear what rclone is doing when printing `md5 = e9a99fd39b444139598f997510c24076 OK` seems that rclone is simply comparing the header `X-Amz-Meta-Md5chksum` between source and dest.

That is correct.

With our new Upload code we proved that the ETag was correct at the point of upload when we uploaded the `X-Amz-Meta-Md5chksum`.

> to many, including me, the impression is rclone is actually checking the source contents match the dest contents. i was hoping for rclone to let us know what it is doing, what is being compared.

For single part copies rclone would be comparing the `Etag` which, TBH is not a lot different - it is a field we read from the provider and we have to trust that it is a) as we uploaded it and b) the provider didn't corrupt the data so it doesn't match.

I'm pretty sure AWS will scan S3 looking for data inconsistencies and fix them or remove the objects so the data will never not match the `Etag` or `X-Amz-Meta-Md5chksum`

> and about this `--bulletproof` concept, i have a suggestion that would works for --- for server-side copy. --- multipart between servers, even if the source was not uploaded by rclone. --- so `--bulletproof, that rclone will always try, as much as possible, to use the provider Etag for all s3 copy operations.
> 
> 1. get the file size.
> 2. get the number of parts from the source Etag
> 3. calculate the size of each part, assume each part is the same size.

The last part can be a different size to the others, so this isn't totally well defined.

Example, file length is 9,000,000 bytes with 3 chunks. This could be 3 chunks of 3,000,000 bytes or it could be 2 chunks of 3,145,728 bytes (3 MiB) with the last chunk only having 2,708,544 bytes

If we make an assumption like the chunk size is always a multiple of 1MiB then we can calculate a single value for chunk size for a lot of cases but my intuition is telling me that for very large chunk sizes there might be two different chunk sizes which fit. Imagine a 300,000,000 byte file with 3 chunks. This could be uploaded with anything from 96MiB to 143MiB chunk size. Is a 128MiB chunk size unreasonable? Probably not.

> 4. `rclone copy source:file.txt dest:` and set the part size to match the source
> 5. when the file copy is done, can directly compare the source Etag and the dest Etag.
> 6. of course, continue to store `X-Amz-Meta-Md5chksum` as it is needed.

I think this algorithm would work but **only** if we can accurately work out the chunk size. If you get the chunk size wrong then the Etag won't match.

We could store the chunk size used for the upload as metadata on the multipart upload, but that would mean that it is an rclone only feature.

I note also that using bigger chunks for server side copy is more efficient whereas you want to use smaller chunks for multipart upload. The defaults for rclone are 5MiB and 4TB so doing a server side copy using small chunks would be less efficient. I don't know how much less though!

**Comment by asdffdsazqqq** [comment]
about the chunk size as metadata, that looks like a good idea.
then that could be used with s3 -> local, multipart downloads?
and for s3- > s3, mulitpart, different providers?

and that could solve the s3->s3, serverside, multipart.
by setting this value to chunksize, so the source and dest etag would match
`X-Amz-Copy-Source-Range: bytes=0-5242879`

**Comment by ncw** [comment]
Yes that would work :-)

I'm going to merge what we've done so far for 1.58 - I think this is going to need a bit more thought.

**Comment by asdffdsazqqq** [comment]
yes, it does need more thought.

as is, the changes deal with two main use cases
1. local -> s3, multipart
2. s3 -> s3, multipart, different providers - which was my original ask.
3. thanks much!

**Comment by asdffdsazqqq** [comment]
ok, not a problem for me, would never use them.
but if there is something specific you need me to do, please let me know.
thanks,

**Comment by asdffdsazqqq** [comment]
i decided to sign up for a free account with alibaba, so i can help you with testing.

as i do not trust them, i am not willing to provide my personal identifiable information, including phone number and billing information home address.

**Comment by ncw** [comment]
I've uploaded a fix for Alibaba here - this disables the extra checking for them and also introduces a new flag so it can be disabled by users.

[v1.58.0-beta.6009.0aa6d2ac7.fix-5993-s3-etag](https://beta.rclone.org/branch/fix-5993-s3-etag/v1.58.0-beta.6009.0aa6d2ac7.fix-5993-s3-etag/) on branch [fix-5993-s3-etag](https://github.com/rclone/rclone/tree/fix-5993-s3-etag) (uploaded in 15-30 mins)

**Comment by asdffdsazqqq** [comment]
`--s3-use-multipart-etag=true` and `--s3-use-multipart-etag=false` work as expected in these multipart cases with wasabi.
1. local -> s3
2. s3 -> s3, same provider, wasabi with `--disable=copy`
3. s3 -> s3, different provider, wasabi -> aws s3

i will do additional testing with aws s3.
imho, `--s3-use-multipart-etag` should default to false, as that is the current behavior.
1. given my dream of etag everywhere, a.k.a `--bulletproof` might need to change/add flags.
2. there might be edge cases that we not anticipated.

**Comment by ncw** [comment]
> imho, `--s3-use-multipart-etag` should default to false, as that is the current behavior.

That is a good point.

I can set it for all the providers I know work. I don't have access to all the providers in the supported list though so leaving those unset would be the safe thing to do.

**Comment by ncw** [comment]
I have tested as many providers as I can and the ones which support the ETag checking have had the checking enabled by default.

The remainder I've disabled the checking to stay with the current behaviour.

[v1.58.0-beta.6011.537b62917.fix-5993-s3-etag](https://beta.rclone.org/branch/fix-5993-s3-etag/v1.58.0-beta.6011.537b62917.fix-5993-s3-etag/) on branch [fix-5993-s3-etag](https://github.com/rclone/rclone/tree/fix-5993-s3-etag) (uploaded in 15-30 mins)

**Comment by asdffdsazqqq** [comment]
i ran my set of 20 tests, the beta looks good.

setting `--s3-use-multipart-etag` default to true, is not a problem.
rclone is just doing an addtional test and at worst, might have a false postive.

**Comment by ncw** [comment]
> i ran my set of 20 tests, the beta looks good.

Great, thank you
 
> setting `--s3-use-multipart-etag` default to true, is not a problem. rclone is just doing an addtional test and at worst, might have a false postive.

If the test fails then the upload will produce an error, so we probably don't want to set the default to true yet.

**Comment by asdffdsazqqq** [comment]
sorry, confused, in my testing `--s3-use-multipart-etag` defaults to `true`

**Comment by ncw** [comment]
What it defaults to depends on the provider. For s3 and wasabi it will default to true, for Alibaba false

**Comment by ncw** [comment]
I've merged this update master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.58.

It will get some testing in the integration tester too!

**Comment by dgouju** [comment]
Hello, it is unclear to me if it works with s3 -> local? It seems very focused on local -> s3 and s3 -> s3 ?

**Comment by ncw** [comment]
@dgouju it works for any multipart upload to s3 no matter the source.

**Comment by darthShadow** [comment]
I think the question is regarding download from S3 to another non-S3 system, specifically local here.

**Comment by ncw** [comment]
As I stated above, I don't think this can ever be 100% reliable unless we can read the chunk size from the source. I don't think this is possible but I'd love to be proved wrong.

And if it isn't 100% reliable we can't use it as an rclone hash.

We could maybe make an S3 backend command equivalent of rclone check.

**Comment by ncw** [comment]
I think we've done as much as we can here. Closing this issue.
