### ISSUE TITLE
Zoho WorkDrive backend can not upload large files (>250MB)

### ISSUE THREAD

**Issue by skredder** [rclone/rclone#5995]
#### Output of `rclone version`
rclone v1.58.0-beta.5999.f22b703a5
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.4.103-1-pve (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.6
- go/linking: static
- go/tags: none

#### Describe the issue

Zoho WorkDrive backend can not upload large files (>250MB)
I believe this may be caused by a limit Zoho has put on their API, the 'upload' endpoint does not support files larger than 250MB, and instead another endpoint needs to be used 'uploadlargefile'

Reference:
https://workdrive.zoho.com/apidocs/v1/filesfolders/uploadfile
https://workdrive.zoho.com/apidocs/v1/filesfolders/uploadlargefile

**Comment by ncw** [comment]
This doesn't look too complicated to implement, escpecially since they don't actually implement chunking!

@buengese what do you think?

**Comment by buengese** [comment]
I've attempted on 2 occasions to implement this but did not succeed. No matter what I did I always ended up with an Internal Server Error. This leads me to believe that either that endpoint broken or the documentation is incorrect. I've even gone so far as to decompile the official client to see how they do it but they use completely different endpoint for uploads.

**Comment by ser86** [comment]
There is any update about this?

**Comment by sycured** [comment]
Hello,
I received snippet codes from Zoho:

### JS
```js
var data = "<file contents here>";

var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function() {
  if(this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("POST", "https://upload.zoho.com/workdrive-api/v1/stream/upload");
xhr.setRequestHeader("x-filename", "a.jpg");
xhr.setRequestHeader("x-parent_id", "rdyhgb346d4f541de4a31965cc84387b48e19");
xhr.setRequestHeader("Authorization", "Zoho-oauthtoken <OAuth token>");
xhr.setRequestHeader("upload-id", "<Unique String for each upload>");
xhr.setRequestHeader("x-streammode", "1");

xhr.send(data);
```

### NodeJS
```js
var request = require('request');
var options = {
  'method': 'POST',
  'url': 'https://upload.zoho.com/workdrive-api/v1/stream/upload',
  'headers': {
    'x-filename': 'a.jpg',
    'x-parent_id': 'rdyhgb346d4f541de4a31965cc84387b48e19',
    'Authorization': 'Zoho-oauthtoken <OAuth token>',
    'upload-id': '<Unique String for each upload>',
    'x-streammode': '1',
    'Content-Type': 'text/plain'
  },
  body: "<file contents here>"

};
request(options, function (error, response) {
  if (error) throw new Error(error);
  console.log(response.body);
});
```

### PHP
```php
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://upload.zoho.com/workdrive-api/v1/stream/upload',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_POSTFIELDS => "<file contents here>",
  CURLOPT_HTTPHEADER => array(
    'x-filename: a.png',
    'x-parent_id: rdyhgb346d4f541de4a31965cc84387b48e19',
    'Authorization: Zoho-oauthtoken <OAuth token>',
    'upload-id: <Unique String for each upload>',
    'x-streammode: 1',
    'Content-Type: text/plain'
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;
```

### Python
```python
import requests

url = "https://upload.zoho.com/workdrive-api/v1/stream/upload"

payload=open('/Users/saravana-4651/Downloads/a.png','rb')
headers = {
  'x-filename': test.png',
  'x-parent_id': 'n6rdfd418cdb043dd4afb8b1e7ef57f67f016',
  'Authorization': 'Zoho-oauthtoken <OAuth token>',
  'upload-id': '<Unique String for each upload>',
  'x-streammode': '1',
  'Content-Type': 'text/plain'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)
```

I hope this can help you

**Comment by ncw** [comment]
I had a go at this

[v1.60.0-beta.6458.a2f55eccb.fix-5995-zoho-upload](https://beta.rclone.org/branch/fix-5995-zoho-upload/v1.60.0-beta.6458.a2f55eccb.fix-5995-zoho-upload/) on branch [fix-5995-zoho-upload](https://github.com/rclone/rclone/tree/fix-5995-zoho-upload) (uploaded in 15-30 mins)

However it didn't work giving these errors

```
2022/09/17 17:24:34 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/09/17 17:24:34 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/09/17 17:24:34 DEBUG : HTTP REQUEST (req 0xc000a34c00)
2022/09/17 17:24:34 DEBUG : POST /workdrive-api/v1/stream/upload HTTP/1.1
Host: upload.zoho.eu
User-Agent: rclone/v1.60.0-beta.6458.a2f55eccb.fix-5995-zoho-upload
Content-Length: 6
Authorization: Zoho-oauthtoken XXXX
Content-Type: text/plain; charset=utf-8
Upload-Id: meropor0yiloyen1bepu
X-Filename: file.txt
X-Parent_id: 4xrzu9ece9a669c3c4d38a009ca405a67cce9
X-Streammode: 1
Accept-Encoding: gzip

hello
2022/09/17 17:24:34 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/09/17 17:24:34 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/09/17 17:24:34 DEBUG : HTTP RESPONSE (req 0xc000a34c00)
2022/09/17 17:24:34 DEBUG : HTTP/1.1 401 INVALID_OAUTHSCOPE
Content-Length: 55
Accept-Ranges: bytes
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: upload.zoho.eu
Access-Control-Expose-Headers: x-uploadid, x-error, Content-Length, x-msg, Accept-Ranges, Content-Disposition
Content-Type: application/json
Date: Sat, 17 Sep 2022 16:24:34 UTC
Last-Modified: Sat, 17 Sep 2022 16:24:34 UTC
Request-Served-By: EU1
Server: AWServer
Strict-Transport-Security: max-age=15768000

{"ERROR_MESSAGE":"INVALID_OAUTHSCOPE","ERROR_CODE":401}
```

There doesn't seem to be an oauth scope for uploads that I can see. Maybe its not allowed with a free account.

**Comment by sycured** [comment]
@ncw I think that the error is from the scope used by rclone: https://github.com/rclone/rclone/blob/4f374bc26475316aaf9f4392c58017507de9e057/backend/zoho/zoho.go#L50-55

More exactly WorkDrive.workspace.READ
I don't see it in the list: https://workdrive.zoho.com/apidocs/v1/oauth2authentication/scopes

Maybe the correctly one is WorkDrive.members.READ

**Comment by ser86** [comment]
Hello, still no solutions for this? Do you have scheduled anything about it?
Thanks

**Comment by dannyromano** [comment]
I noticed the Zoho dev team started to communicate with @ncw late last year and again in March of this year. Has there been any movement on this topic since?

See https://forum.rclone.org/t/followup-on-the-older-topic-rclone-invokes-more-number-of-workdrive-s-files-listing-api-calls-which-exceeds-the-throttling-limit/44794/3
