### ISSUE TITLE
[sftp] can't delete empty dest dir

### ISSUE THREAD

**Issue by mrx23dot** [rclone/rclone#5997]
#### What is the problem you are having with rclone?
`rclone sync local_src sftp_dest` always tries to delete the same dirs on SFTP destination.

So I tried:
rclone -vv rmdir xx_sftp:/home/backup/xx
```
... Removing directory
2022/02/16 22:44:37 ERROR : Attempt 3/3 failed with 1 errors and: directory not empty
```
Looks like it tries to delete the dir first before removing the content.
Or if the goal is to remove the dir first then it's missing -R flag.
I tried under the same user `rm -R /same_dir` it works, so it's not a rights issue.

All I know this was never a problem on windows destinations, regardless of the content of folders.

#### What is your rclone version (output from `rclone version`)
rclone v1.57.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
source: win7 x64

#### Which cloud storage system are you using? (e.g. Google Drive)
destination: sftp debian

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone sync local_src sftp_dest` 

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
see above

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Is there a full debug log? 

Output of the directory you are trying to delete? Is it empty?

rm -R recursively deletes so that would not show if it was empty.

```
felix@gemini:~$ mkdir test
felix@gemini:~$ cp /etc/hosts test
felix@gemini:~$ rmdir test
rmdir: failed to remove 'test': Directory not empty
felix@gemini:~$ rm -R test
```

```

**Comment by animosity22** [comment]
And rclone rmdir won't remove a non empty directory:

https://rclone.org/commands/rclone_rmdir/

```
felix@gemini:~$ rclone rmdir SFTP:test -vvv
2022/02/16 22:12:05 DEBUG : Setting --config "/opt/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/opt/rclone/rclone.conf"
2022/02/16 22:12:05 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "rmdir" "SFTP:test" "-vvv"]
2022/02/16 22:12:05 DEBUG : Creating backend with remote "SFTP:test"
2022/02/16 22:12:05 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2022/02/16 22:12:05 DEBUG : sftp://felix@localhost:22/test: New connection 127.0.0.1:52418->127.0.0.1:22 to "SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.4"
2022/02/16 22:12:05 DEBUG : sftp://felix@localhost:22/test: Using absolute root directory "/home/felix/test"
2022/02/16 22:12:05 INFO  : sftp://felix@localhost:22/test: Removing directory
2022/02/16 22:12:05 ERROR : Attempt 1/3 failed with 1 errors and: directory not empty
2022/02/16 22:12:05 INFO  : sftp://felix@localhost:22/test: Removing directory
2022/02/16 22:12:05 ERROR : Attempt 2/3 failed with 1 errors and: directory not empty
2022/02/16 22:12:05 INFO  : sftp://felix@localhost:22/test: Removing directory
2022/02/16 22:12:05 ERROR : Attempt 3/3 failed with 1 errors and: directory not empty
2022/02/16 22:12:05 DEBUG : 11 go routines active
2022/02/16 22:12:05 Failed to rmdir: directory not empty
```

**Comment by animosity22** [comment]
Without a log file, it's tough to diagnose or help you out.

That's exactly what sync does if you remove a source directory.

```
felix@gemini:~$ rclone tree test
/
├── one
│   └── hosts
└── two

2 directories, 1 files
felix@gemini:~$ rclone tree test2
/
├── one
│   └── hosts
└── two

2 directories, 1 files
felix@gemini:~$ rmdir test/two
felix@gemini:~$ rclone sync SFTP:test SFTP:test2 -vvv
2022/02/17 06:00:17 DEBUG : Setting --config "/opt/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/opt/rclone/rclone.conf"
2022/02/17 06:00:17 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "sync" "SFTP:test" "SFTP:test2" "-vvv"]
2022/02/17 06:00:17 DEBUG : Creating backend with remote "SFTP:test"
2022/02/17 06:00:17 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2022/02/17 06:00:17 DEBUG : sftp://felix@localhost:22/test: New connection 127.0.0.1:52504->127.0.0.1:22 to "SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.4"
2022/02/17 06:00:17 DEBUG : sftp://felix@localhost:22/test: Using absolute root directory "/home/felix/test"
2022/02/17 06:00:17 DEBUG : Creating backend with remote "SFTP:test2"
2022/02/17 06:00:17 DEBUG : sftp://felix@localhost:22/test2: New connection 127.0.0.1:52506->127.0.0.1:22 to "SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.4"
2022/02/17 06:00:18 DEBUG : sftp://felix@localhost:22/test2: Using absolute root directory "/home/felix/test2"
2022/02/17 06:00:18 DEBUG : sftp://felix@localhost:22/test2: New connection 127.0.0.1:52508->127.0.0.1:22 to "SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.4"
2022/02/17 06:00:18 DEBUG : sftp://felix@localhost:22/test2: Waiting for checks to finish
2022/02/17 06:00:18 DEBUG : one/hosts: Size and modification time the same (differ by 0s, within tolerance 1s)
2022/02/17 06:00:18 DEBUG : one/hosts: Unchanged skipping
2022/02/17 06:00:18 DEBUG : sftp://felix@localhost:22/test2: Waiting for transfers to finish
2022/02/17 06:00:18 DEBUG : Waiting for deletions to finish
2022/02/17 06:00:18 INFO  : two: Removing directory
2022/02/17 06:00:18 DEBUG : sftp://felix@localhost:22/test2: deleted 1 directories
2022/02/17 06:00:18 INFO  : There was nothing to transfer
2022/02/17 06:00:18 INFO  :
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Checks:                 1 / 1, 100%
Deleted:                0 (files), 1 (dirs)
Elapsed time:         1.2s

2022/02/17 06:00:18 DEBUG : 30 go routines active

felix@gemini:~$ rclone tree test
/
└── one
    └── hosts

1 directories, 1 files
felix@gemini:~$ rclone tree test2
/
└── one
    └── hosts

1 directories, 1 files
felix@gemini:~$
```

Please share a log file so we can help out.

**Comment by mrx23dot** [comment]
Weird, I couldn't recreate it, something must have held it open on server I guess.

2022/02/17 21:08:36 DEBUG : Waiting for checks to finish
2022/02/17 21:08:36 DEBUG : Waiting for transfers to finish
2022/02/17 21:08:36 DEBUG : Waiting for deletions to finish
2022/02/17 21:08:36 INFO  : Projects/sgg/asdfsd.txt: Deleted
2022/02/17 21:08:36 INFO  : Projects/sdfdfgdfg.txt: Deleted
2022/02/17 21:08:36 INFO  : Projects/sgg: Removing directory
2022/02/17 21:08:36 DEBUG : deleted 1 directories

Thanks for the help!
