### ISSUE TITLE
(Repost) JuiceFS WebDAV backend does not work with Rclone WebDAV server in Windows

### ISSUE THREAD

**Issue by stevefan1999-personal** [rclone/rclone#5998]
https://github.com/juicedata/juicefs/issues/1445#issue-1141297176

Rclone version: 1.57.0

**Comment by animosity22** [comment]
No information other than a version? Can you please fill out the template as that it what is needed.

**Comment by ivandeex** [comment]
Incomplete ticket.
Please resubmit conforming to project rules.
