### ISSUE TITLE
Error 403 only the owner can download abusive files.

### ISSUE THREAD

**Issue by Scottvr1github** [rclone/rclone#6001]
#### What is the problem you are having with rclone?

Error 403 only the owner can download abusive files 

#### What is your rclone version (output from `rclone version`)
Version 1.8.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 11

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
No forum post
No version output
No command
No cloud storage shared (guessing Google)
No debug log

Please post on the forums, use the help and support template and fill out everything if you'd like assistance.

https://forum.rclone.org/
