### ISSUE TITLE
[TeleDrive] Should support teledrive, free unlimited storage

### ISSUE THREAD

**Issue by trungdn0401** [rclone/rclone#6004]
Dear Team,

TeleDrive is an open-source project to give you what you deserve. Using the Telegram API as your unlimited storage. So, you can upload as many as you want without any limit/ (https://twitter.com/telegram/status/1428703364737507332?s=20&t=o8fSxztkakRZcmYwuHz3ew)

It has supported API: https://documenter.getpostman.com/view/1778529/UV5TGf4u#intro

It's would be great if Rclone support this service.

Thank you in advance!

**Comment by animosity22** [comment]
That's quite the number of new backend requests and very few people to implement. Odds are this will sit unless you have someone that has some interest in developing it.

**Comment by jezovuk** [comment]
Note that, according to announcement on  https://teledriveapp.com/, TeleDrive is going to shut down soon.

**Comment by ivandeex** [comment]
This project looks unstable, undertested and underdocumented. I don't think it will get much traction. The first look at https://teledriveapp.com/ gave me this:
```
First of all, we need to inform you that we should shut down TeleDrive before March 2nd because of some issues that need us to forcibly do this.
```

Worse, I expect that Telegram leadership will start fighting attempts to abuse its file storage facilities as soon as it becomes wide spread.
Thumbs down.

**Comment by trungdn0401** [comment]
Ok, Thanks a lot mate!

**Comment by ncw** [comment]
Is this related to this issue? https://github.com/rclone/rclone/issues/5829 If so we should put any extra info from this issue there and close this issue.

**Comment by animosity22** [comment]
Closing as a duplicate. Let's use the one @ncw stated and add any details there.

**Comment by greengeckowizard** [comment]
Hello I'm a dev from Teledrive ready to start to integrate Rclone with the project.  We're currently working on making this possible. 
-Thank you everyone for your ideas and we'll be looking on integration

**Comment by ne0YT** [comment]
> Hello I'm a dev from Teledrive ready to start to integrate Rclone with the project. We're currently working on making this possible. -Thank you everyone for your ideas and we'll be looking on integration

any news on this journey?

**Comment by fe80Grau** [comment]
@ne0YT check @greengeckowizard repositories https://github.com/greengeckowizard/RcloneTelegram 😄 i gonna test right now

**Comment by greengeckowizard** [comment]
> @ne0YT check @greengeckowizard repositories https://github.com/greengeckowizard/RcloneTelegram 😄 i gonna test right now
You may stumble errors if so that's OK it's almost done in development.
