### ISSUE TITLE
rclone mount for Google Drive does not show as web links the google documents of the ".gmap" type

### ISSUE THREAD

**Issue by lxnglz** [rclone/rclone#6007]
I mount a Google Drive with rclone (via "rclone mount" command).
I use the following paramenter: ' --drive-export-formats "url" '
With this parameter I can see on the mapped drive the most of the Google documents as *.url files, which can be opened through a web browser.
This is true for the following Google documents:
- Text (MS Word-like) document (google extension is .gdoc)
- Spreadsheet document (.gsheet)
- Drawing document (.gdraw)
- Google Form (.gform)
- Jam board document (.gjam)
- Google Site document (.gsite)

However, Google Maps documents (seen as .gmap documents in the google native client) are invisible.
They should be also visible as *.url files (or whichever link type files), so that they can be opened in a web browser.

My OS is Windows 11.
My rclone version is 1.58 (I had to use this beta version because I need the vfs.stats command of the "rclone rc" interface).

**Comment by animosity22** [comment]
Please use the forums to make a post for general support as you didn't follow the rules here to make a bug report. 

Use the help and support template:

https://forum.rclone.org/

Closing with lack of needed information.
