### ISSUE TITLE
I can't exclude a folder via exclude-from exclude.txt

### ISSUE THREAD

**Issue by Pushkin31** [rclone/rclone#6010]
Hello. I have a problem when trying to exclude a folder in the "exclude.txt" file
Its contents look like this:

This is what the "exclude.txt" file looks like:
`- /BraveSoftware/`
Rclone version and operating system:
```
rclone v1.57.0
- os/version: arch Rolling (64 bit)
- os/kernel: 5.15.23-2-lts (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.5
- go/linking: dynamic
- go/tags: none
```
The command I'm trying to execute
`rclone ls /home/mxn/.config --exclude-from exclude.txt`
But the exception does not work not only for "ls", but also for push

When trying to exclude with the command with the flag "--exclude "FOLDERS/**" " everything works, but I don't want to use a long command to do sync when I can put everything in the file...

Here is a log proving that the "BraveSoftware" folder is still uploaded to the google drive cloud teams
[bug.log](https://github.com/rclone/rclone/files/8124680/bug.log)
p.s.: I purposely interrupted the operation myself

**Comment by Pushkin31** [comment]
I understand `--exclude-if-present ` flag is responsible for file extensions and files themselves
and the `--filter-from` flag for folders?

**Comment by Pushkin31** [comment]
I would also like to note the low download speed on "teams google drive"
```
Transferred: 459.718 KiB / 52.255 MiB, 1%, 2.157 KiB/s, ETA 6h49m48s
Checks: 1392 / 1392, 100%
Transferred: 194 / 1142, 17%
Elapsed time: 3m1.4s
```

**Comment by ncw** [comment]
> This is what the "exclude.txt" file looks like:
> `- /BraveSoftware/`

An `--exclude-from` file doesn't need the leading `+` and `-` that is for `--filter-from`

So

```
/BraveSoftware/**
```

Should do the trick.

**Comment by ncw** [comment]
That is the way it goes!

Having talked to lots of people about the filters, in general people find them quite hard. We've re-written the docs about 5 times to try to help, but I think there are just too many concepts and ways of doing things!
