### ISSUE TITLE
rclone check is skipping integrity check of objects ending with slash when both remotes are S3

### ISSUE THREAD

**Issue by buptwxd2** [rclone/rclone#6011]
#### What is the problem you are having with rclone?
I am using rclone for data integrity check.
When both remotes are S3, rclone check will skip objects ending with slash

#### What is your rclone version (output from `rclone version`)
rclone v1.57.0
- os/version: centos 7.8.2003 (64 bit)
- os/kernel: 3.10.0-1127.el7.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.2
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Centos 

#### Which cloud storage system are you using? (e.g. Google Drive)
Ceph

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone check

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
root@sds5 ~/x/test# aws s3api list-objects --bucket xd-bk-2
{
    "Contents": [
        {
            "Key": "abc/",
            "LastModified": "2022-02-24T09:36:40.813000+00:00",
            "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
            "Size": 0,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "xd",
                "ID": "0000000000000002"
            }
        }
    ]
}
root@sds5 ~/x/test# aws s3api list-objects --bucket xd-bk-3
{
    "Contents": [
        {
            "Key": "abc/",
            "LastModified": "2022-02-24T09:57:15.113000+00:00",
            "ETag": "\"b6d81b360a5672d80c27430f39153e2c\"",
            "Size": 1048576,
            "StorageClass": "STANDARD",
            "Owner": {
                "DisplayName": "xd",
                "ID": "0000000000000002"
            }
        }
    ]
}
root@sds5 ~/x/test# rclone check 55:/xd-bk-2/ 55:/xd-bk-3/ -vv
2022/02/24 17:57:29 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "check" "55:/xd-bk-2/" "55:/xd-bk-3/" "-vv"]
2022/02/24 17:57:29 DEBUG : Creating backend with remote "55:/xd-bk-2/"
2022/02/24 17:57:29 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2022/02/24 17:57:29 DEBUG : fs cache: renaming cache item "55:/xd-bk-2/" to be canonical "55:xd-bk-2"
2022/02/24 17:57:29 DEBUG : Creating backend with remote "55:/xd-bk-3/"
2022/02/24 17:57:29 DEBUG : fs cache: renaming cache item "55:/xd-bk-3/" to be canonical "55:xd-bk-3"
2022/02/24 17:57:29 INFO  : Using md5 for hash comparisons
2022/02/24 17:57:29 DEBUG : S3 bucket xd-bk-3: Waiting for checks to finish
2022/02/24 17:57:30 ERROR : abc/: Entry doesn't belong in directory "abc" (same as directory) - ignoring
2022/02/24 17:57:30 NOTICE: S3 bucket xd-bk-3: 0 differences found
2022/02/24 17:57:30 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:         0.0s

2022/02/24 17:57:30 DEBUG : 7 go routines active

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> When both remotes are S3, rclone check will skip objects ending with slash

Rclone believes objects ending with a `/` are directory markers and have no useful info in.

Is that not the case for you?

**Comment by buptwxd2** [comment]
Thanks @ncw .

But in S3 world, there is no differece between objects ending with slash and the other. And objects ending with slash can contain any number of data.

I understand there is no useful user data in directories in filesystem world.
But if the source and the destination are S3, I think it's useful and essential to compare data of objects ending with slash.

**Comment by ncw** [comment]
Rclone maps s3 to a file system model. There is a bit of an impedance mismatch there because s3 supports things that filesystems don't, for example names like `file//with///many////slashes`. In the case of objects ending in `/` rclone uses them as directory markers.

However directory markers are not needed on s3 unless you have an empty directory, so to save objects and transactions rclone does not normally write directory markers.

So when you use `rclone check` rclone will check the **files** exist. It checks the directories exist by virtue of the fact that the files exist in them but it doesn't check them directly. Rclone doesn't care whether the directory markers exist or not, so `rclone check` will completely ignore them.

Is it important to your application to have directory markers? There is an issue which adds a flag to rclone to always create directory markers - maybe that is what you want?

**Comment by buptwxd2** [comment]
Thanks @ncw for your explanation.

Could you show me the issue which adds a flag to always create directory markers?
