### ISSUE TITLE
Possible problem with rclone install script

### ISSUE THREAD

**Issue by aleksd2000** [rclone/rclone#6015]
#### What is the problem you are having with rclone?

 curl https://rclone.org/install.sh | sudo bash -s beta isn't working

#### What is your rclone version (output from `rclone version`)

0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Debian 11

#### Which cloud storage system are you using? (e.g. Google Drive)

GoogleDrive, OpenDrive, and lots of others

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

 curl https://rclone.org/install.sh | sudo bash -s beta

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

aleks@recovery1:~/GIT:Repos/rclone$ curl https://rclone.org/install.sh | sudo bash -s beta
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4497  100  4497    0     0   168k      0 --:--:-- --:--:-- --:--:--  175k
Archive:  rclone-beta-latest-linux-amd64.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of rclone-beta-latest-linux-amd64.zip or
        rclone-beta-latest-linux-amd64.zip.zip, and cannot find rclone-beta-latest-linux-amd64.zip.ZIP, period.

**Comment by ncw** [comment]
This happens occasionally when the caching messes up. I think it is OK now if you try it again.

**Comment by animosity22** [comment]
Closing out as this was answered and I tested from a few machines myself with no issues.
