### ISSUE TITLE
I am using rclone 1.45

### ISSUE THREAD

**Issue by manoflinux** [rclone/rclone#6030]
#### What is the problem you are having with rclone?
I named my remote for google drive, "google drive" and I referenced it as  "google\ drive:my-uploads" the upload happened instantly and I was unable to find it on google drive. 
Well I looked on my hard drive for it and found it in a directory called /home/user/google\\\ drive\:my-uploads/
All i did to fix this was launch rclone config again and renamed the remote to googledrive and this worked with no problem.

/usr/bin/rclone copy --update --verbose --transfers 30 --checkers 8 --contimeout 60s --timeout 300s --retries 3 --low-level-retries 10 --stats 1s /home/user/Documents/weather.txt "googledrive:my-uploads"

#### What is your rclone version (output from `rclone version`)

1.45

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

debian based linux 64bit

#### Which cloud storage system are you using? (e.g. Google Drive)

google drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

/usr/bin/rclone copy --update --verbose --transfers 30 --checkers 8 --contimeout 60s --timeout 300s --retries 3 --low-level-retries 10 --stats 1s /home/user/Documents/weather.txt "google\ drive:my-uploads"

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

would have to break things again to reproduce.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
You are on an ancient version. Upgrade it.

Please use the forum for general support questions and use the help and support template with a log file as that's what is needed to help you.

https://forum.rclone.org
