### ISSUE TITLE
Add support for Contabo S3 storage object

### ISSUE THREAD

**Issue by BreakSecurity** [rclone/rclone#6031]
#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.57.0
- os/version: debian 11.0 (64 bit)
- os/kernel: 5.16.11-76051611-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.2
- go/linking: static
- go/tags: none
```

#### What problem are you are trying to solve?
Get new offered Contabo S3 storage object run with rclone 
More details here: https://contabo.com/en/object-storage/ and here https://contabo.com/blog/introducing-all-inclusive-object-storage/

#### How do you think rclone should be changed to solve that?
Update the docs and the config script

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by vekunz** [comment]
Adding the new Contabo Object Storage should be straightforward. Currently, I use the Contabo Object Storage with the "AWS S3" "Other" option and it seems to work just fine.

**Comment by satcit-me** [comment]
> #### What is your current rclone version (output from `rclone version`)?
> ```
> rclone v1.57.0
> - os/version: debian 11.0 (64 bit)
> - os/kernel: 5.16.11-76051611-generic (x86_64)
> - os/type: linux
> - os/arch: amd64
> - go/version: go1.17.2
> - go/linking: static
> - go/tags: none
> ```
> 
> #### What problem are you are trying to solve?
> Get new offered Contabo S3 storage object run with rclone More details here: https://contabo.com/en/object-storage/ and here https://contabo.com/blog/introducing-all-inclusive-object-storage/
> 
> #### How do you think rclone should be changed to solve that?
> Update the docs and the config script
> 
> #### How to use GitHub
> * Please use the +1 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
> * Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
> * Subscribe to receive notifications on status change and new comments.

Hi... I have made a tutorial on how to connect to Contabo Object Storage via rclone. Please go through this.

https://satcit.me/index.php/2022/03/15/contabo-object-storage-rclone

**Comment by MohamedElashri** [comment]
> > #### What is your current rclone version (output from `rclone version`)?
> > ```
> > rclone v1.57.0
> > - os/version: debian 11.0 (64 bit)
> > - os/kernel: 5.16.11-76051611-generic (x86_64)
> > - os/type: linux
> > - os/arch: amd64
> > - go/version: go1.17.2
> > - go/linking: static
> > - go/tags: none
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### What problem are you are trying to solve?
> > Get new offered Contabo S3 storage object run with rclone More details here: https://contabo.com/en/object-storage/ and here https://contabo.com/blog/introducing-all-inclusive-object-storage/
> > #### How do you think rclone should be changed to solve that?
> > Update the docs and the config script
> > #### How to use GitHub
> > 
> > * Please use the +1 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
> > * Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
> > * Subscribe to receive notifications on status change and new comments.
> 
> Hi... I have made a tutorial on how to connect to Contabo Object Storage via rclone. Please go through this.
> 
> https://satcit.me/index.php/2022/03/15/contabo-object-storage-rclone

Thank you, just make sure that you delete your ID_key and Secret because they are shown in the output in your instructions if you want to avoid people use your own.

**Comment by satcit-me** [comment]
> > > #### What is your current rclone version (output from `rclone version`)?
> > > ```
> > > rclone v1.57.0
> > > - os/version: debian 11.0 (64 bit)
> > > - os/kernel: 5.16.11-76051611-generic (x86_64)
> > > - os/type: linux
> > > - os/arch: amd64
> > > - go/version: go1.17.2
> > > - go/linking: static
> > > - go/tags: none
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > #### What problem are you are trying to solve?
> > > Get new offered Contabo S3 storage object run with rclone More details here: https://contabo.com/en/object-storage/ and here https://contabo.com/blog/introducing-all-inclusive-object-storage/
> > > #### How do you think rclone should be changed to solve that?
> > > Update the docs and the config script
> > > #### How to use GitHub
> > > 
> > > * Please use the +1 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
> > > * Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
> > > * Subscribe to receive notifications on status change and new comments.
> > 
> > 
> > Hi... I have made a tutorial on how to connect to Contabo Object Storage via rclone. Please go through this.
> > https://satcit.me/index.php/2022/03/15/contabo-object-storage-rclone
> 
> Thank you, just make sure that you delete your ID_key and Secret because they are shown in the output in your instructions if you want to avoid people using your own.

Oh, God. I didn't see that. Thanks for letting me know. I have edited the blog post and also regenerated the secret key.

**Comment by vekunz** [comment]
Contabo released a documentation page where they say that they use Ceph under the hood https://docs.contabo.com/docs/Object-Storage/what-is.

Since Ceph is supported by rclone directly, it may not be needed to add Contabo explicitly to rclone. Contabo has another documentation page with configuration instructions for rclone https://docs.contabo.com/docs/Object-Storage/Tools/rclone.

**Comment by ncw** [comment]
Contabo is CEPH compatible and they document how to connect it to rclone here: https://docs.contabo.com/docs/products/Object-Storage/Tools/rclone/

If someone wanted to make a provider for Contabo that might make it easier for people but I don't think we need this issue any more.
