### ISSUE TITLE
rclone move --order-by modtime,ascending no perfect delete ordering if files already in remote backend

### ISSUE THREAD

**Issue by cberni** [rclone/rclone#6033]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/rclone-move-order-by-and-check-first-with-no-perfect-ordering/29586

#### What is the problem you are having with rclone?

rclone move with --checkers more than 1 is not deleting in perfect order --order-by modtime,ascending if the files are already in the remote backend

is there a way to have multiple checkers but only delete if order is perfect like the trasnfer?

#### What is your rclone version (output from `rclone version`)

rclone v1.57.0
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.13.0-1019-gcp (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.2
- go/linking: static
- go/tags: none

#### Which cloud storage system are you using? (e.g. Google Drive)

google cloud storage

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone move /local remote:bucket --include-from include-file.txt --order-by modtime,ascending --max-delete 1078750 --cutoff-mode soft --check-first --delete-empty-src-dirs --no-traverse --fast-list -vv

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

022/03/04 14:45:29 DEBUG : Setting --checkers "16" from environment variable RCLONE_CHECKERS="16"
2022/03/04 14:45:29 DEBUG : Setting --transfers "8" from environment variable RCLONE_TRANSFERS="8"
2022/03/04 14:45:29 DEBUG : Setting --config "/etc/rclone.conf" from environment variable RCLONE_CONFIG="/etc/rclone.conf"
2022/03/04 14:45:29 DEBUG : rclone: Version "v1.57.0" starting with parameters ["rclone" "move" "/local" "remote:bucket" "--include-from" "/etc/include-file.txt" "--order-by" "modtime,ascending" "--max-delete" "1228331" "--cutoff-mode" "soft" "--check-first" "--delete-empty-src-dirs" "--no-traverse" "--fast-list" "-vv"]
2022/03/04 14:45:29 DEBUG : Creating backend with remote "/local"
2022/03/04 14:45:29 DEBUG : Using config file from "/etc/rclone.conf"
2022/03/04 14:45:29 DEBUG : Creating backend with remote "remote:bucket"
2022/03/04 14:45:29 INFO  : GCS bucket bucket: Running all checks before starting transfers

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I've had a go at this - please give this a go

[v1.62.0-beta.6784.3b28ea0ba.fix-6033-delete-perfect-ordering](https://beta.rclone.org/branch/fix-6033-delete-perfect-ordering/v1.62.0-beta.6784.3b28ea0ba.fix-6033-delete-perfect-ordering/) on branch [fix-6033-delete-perfect-ordering](https://github.com/rclone/rclone/tree/fix-6033-delete-perfect-ordering) (uploaded in 15-30 mins)
