### ISSUE TITLE
Stops copying files with unreadable characters

### ISSUE THREAD

**Issue by pokevas** [rclone/rclone#6034]
#### What is the problem you are having with rclone?
Rclone successfully copies most files, but then at some point it hangs on some files with unreadable characters and copying does not go any further. The speed lags behind 0 bytes/s and the process hangs. So it hangs for hours and does not move anywhere.
What could be the problem?
Is it possible then to skip such files that have not been copied for several hours?

#### What is your rclone version (output from `rclone version`)
```
rclone v1.57.0
- os/version: Microsoft Windows 10 Pro 2009 (64 bit)
- os/kernel: 10.0.19044.1466 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.17.2
- go/linking: dynamic
- go/tags: cmount

```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 10, 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
`Microsoft Azure Blob Storage`

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`C:\Users\Mark\Desktop\rclone\rclone.exe --config C:\Users\Mark\Desktop\rclone\my.conf copy "D:\data" azure:backup5/data --filter-from=C:\Users\Mark\Desktop\rclone\filter.txt --bwlimit 30M --ignore-case --max-age=2y --transfers=24 --contimeout=30m -v --log-file=C:\Users\Mark\Desktop\rclone\log\copy-log.txt`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```

2022/01/07 22:57:38 INFO  : 
Transferred:   	    1.225 TiB / 1.225 TiB, 100%, 0 B/s, ETA 0s
Transferred:       332368 / 332369, 100%
Elapsed time:    10h3m1.1s
Transferring:
 * data/log1/Do…牌_完整版_视觉识别系统_v12.pdf: 42% /28.270Mi, 0/s, 0s

2022/01/07 22:58:38 INFO  : 
Transferred:   	    1.225 TiB / 1.225 TiB, 100%, 0 B/s, ETA 0s
Transferred:       332368 / 332369, 100%
Elapsed time:    10h4m1.1s
Transferring:
 * data/log1/Do…牌_完整版_视觉识别系统_v12.pdf: 42% /15.270Mi, 0/s, 0s

2022/01/07 22:59:38 INFO  : 
Transferred:   	    1.225 TiB / 1.225 TiB, 100%, 0 B/s, ETA 0s
Transferred:       332368 / 332369, 100%
Elapsed time:    10h5m1.1s
Transferring:
 * data/log1/Do…牌_完整版_视觉识别系统_v12.pdf: 42% /15.270Mi, 0/s, 0s

2022/01/07 23:00:38 INFO  : 
Transferred:   	    1.225 TiB / 1.225 TiB, 100%, 0 B/s, ETA 0s
Transferred:       332368 / 332369, 100%
Elapsed time:    10h6m1.1s
Transferring:
 * data/log1/Do…牌_完整版_视觉识别系统_v12.pdf: 42% /15.270Mi, 0/s, 0s
 * 
```

**Comment by animosity22** [comment]
If you have a single file, can you test copying the 'bad file' with a debug log?

**Comment by ncw** [comment]
I've just updated the Azure Blob backend and it has likely fixed this problem.

Please can you test again with [the latest beta](https://beta.rclone.org/).

**Comment by ncw** [comment]
I'm going to assume this is fixed. If not I'll re-open.
