### ISSUE TITLE
Errors with multipart copy from Archive.org S3 backend

### ISSUE THREAD

**Issue by EchterAgo** [rclone/rclone#6039]
I'm trying to copy an archive.org collection using the [Archive.org S3 backend](https://archive.org/services/docs/api/ias3.html) and I'm frequently getting these errors:

```
2022-03-16 03:27:02 ERROR : filename.zip: Failed to copy: multipart copy: wrote 417592680 bytes but expected to write 208797696
```

The files with the error are not transferred correctly. It seems that this related to [range requests not being supported at Archive.org S3](https://archive.org/services/docs/api/ias3.html#:~:text=HTTP%201.1%20Range%20headers%20are%20ignored) and specifying `--multi-thread-streams 0` seems to resolve the issue.

A solution would be to add an Archive.org S3 provider that disables range requests. Also it might be possible to detect this issue by checking the HTTP code that a range request returns, if it is unsupported HTTP 200 should be returned.

I tested this with rclone 1.57, 1.53.3 and the latest snapshot and they all behave the same.

**Comment by buengese** [comment]
Current beta versions of rclone have an internet archive remote that uses the s3 API for everything but downloads and accounts for all its quirks. I don't think it's in the release version of rclone yet, but you could use the beta until the next release.
