### ISSUE TITLE
https://github.com/rclone/rclone/blob/master/docs/content/downloads.md points to v1.59

### ISSUE THREAD

**Issue by didier-durand** [rclone/rclone#6043]
#### What is the problem you are having with rclone?

downloads.md currently mentions 1.59 which doesn't exist yet: downloads cannot happen.
It should be 1.58

#### What is your rclone version (output from `rclone version`)

1.57 and willing to upgrade

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

MacOs

#### Which cloud storage system are you using? (e.g. Google Drive)

S3

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I've fixed this now - sorry for the mess up.

You might need to CTRL-Refresh the page to get it to show properly.

(I hot updated the website incorrectly!)
