### ISSUE TITLE
Wrong version and links at download page https://rclone.org/downloads/

### ISSUE THREAD

**Issue by ghrasc** [rclone/rclone#6046]
Hi!

https://rclone.org/downloads/ shows "**Release v1.59.0**" whilst last release was 1.57 and change log says you released **1.58** yesterday.
All links on that site point to downloads.rclone.org/**v1.59.0**/rclone-**v1.59.0**-_platform_-_architecture_.zip whilst latest version at https://downloads.rclone.org/ is [**v1.58.0**] (https://downloads.rclone.org/v1.58.0/).

Please fix the download page so users find the new version faster/easier.
Thank you!

**Comment by ghrasc** [comment]
@ncw please see #6043 as well

**Comment by ncw** [comment]
I've fixed this now - sorry for the mess up.

You might need to CTRL-Refresh the page to get it to show properly.

(I hot updated the website incorrectly!)
