### ISSUE TITLE
Add mime-type to objects based on extension

### ISSUE THREAD

**Issue by daybug** [rclone/rclone#6052]
Sometimes user needs mime-type of objects, especially for the objects used for websites. Is there any possibility to auto detect and set mime-type when `copy` or `sync`?

**Comment by albertony** [comment]
In general, rclone uses whatever mimetype the backend provides. For `local` it utilizes the standard os mime database.

What you suggest, is that basically a way to override mime types used by rclone, and make it use your specific ones for certain extensions? That is not possible currently, but is something that has been discussed in the forum: https://forum.rclone.org/t/dlna-server-unrecognized-file-type-xxx-mkv/27028.

**Comment by daybug** [comment]
Yes. I tested with different kinds of sources and found mime types of destination kept unchanged. What I want to do is auto guess mime types for objects with a proper prefix. That should not happen on `sync` or 'copy'. Now I understood it. Thanks for your quick reply.
