### ISSUE TITLE
--transfers has no effect on single big file (b2)

### ISSUE THREAD

**Issue by hyperknot** [rclone/rclone#6057]
#### What is the problem you are having with rclone?
--transfers has no effect when downloading a single big file (18 GB).

#### What is your rclone version (output from `rclone version`)
```
rclone v1.58.0
- os/version: ubuntu 18.04 (64 bit)
- os/kernel: 4.15.0-173-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.8
- go/linking: static
- go/tags: none
```

#### Which cloud storage system are you using? (e.g. Google Drive)
Backblaze B2

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
rclone copy --config=a.conf -vvv --transfers=32 b2:a/b.gz /data/c
```

The config only contains type,  account and key.

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2022/03/23 19:17:15 DEBUG : rclone: Version "v1.58.0" starting with parameters ["rclone" "copy" "--config=a.conf" "-vvv" "--transfers=32" "b2:a/b.gz" "/data/c"]

2022/03/23 19:17:15 DEBUG : Creating backend with remote "b2:a/b.gz"
2022/03/23 19:17:15 DEBUG : Using config file from "a.conf"
2022/03/23 19:17:16 DEBUG : fs cache: adding new entry for parent of "b2:a/b.gz", "b2:a"
2022/03/23 19:17:16 DEBUG : Creating backend with remote "/data/omt_mbtiles"
2022/03/23 19:17:16 DEBUG : b.gz: Sizes differ (src 79084223957 vs dst 59313307403)
2022/03/23 19:17:16 DEBUG : b.gz: Starting multi-thread copy with 4 parts of size 18.413Gi
2022/03/23 19:17:16 DEBUG : b.gz: multi-thread copy: stream 4/4 (59313291264-79084223957) size 18.413Gi starting
2022/03/23 19:17:16 DEBUG : b.gz: multi-thread copy: stream 1/4 (0-19771097088) size 18.413Gi starting
2022/03/23 19:17:16 DEBUG : b.gz: multi-thread copy: stream 2/4 (19771097088-39542194176) size 18.413Gi starting
2022/03/23 19:17:16 DEBUG : b.gz: multi-thread copy: stream 3/4 (39542194176-59313291264) size 18.413Gi starting
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
It's not supposed to as transfers allow you to transfer more than 1 file at a time.

The default is 4.

**Comment by hyperknot** [comment]
I don't see the reason to hard code chunked file transfers to 4 while allowing any value for multiple file transfer, but if this is per design then it's obviously not a bug. Still a very strange behaviour from a user point of view.

**Comment by hyperknot** [comment]
By "default" do you mean there is a way to change it?

**Comment by animosity22** [comment]
Sure. By default it'll do 4 files at a time:

https://rclone.org/flags/

and the flag here is:

```
      --transfers int                        Number of file transfers to run in parallel (default 4)
```

The second bit is multiple streams as that also defaults to 4.

```
      --multi-thread-streams int             Max number of streams to use for multi-thread downloads (default 4)
```

You can do as many as makes sense. I'd probably try 8/12/16/etc see what is your sweet spot.

**Comment by hyperknot** [comment]
Oh, that's great! In this case please take this Issue as a documentation improvement, as I've really spent a long time searching for this everywhere, in multiple pages of the docs, and I really haven't found it. I recommend putting a link in the "transfers" section, like "look at --multi-thread-streams if you would like to control single file transfers".

**Comment by animosity22** [comment]
@hyperknot  - would you like to submit a PR for this to fix it or close it out?

**Comment by hyperknot** [comment]
Made a PR here: https://github.com/rclone/rclone/pull/6130

**Comment by ncw** [comment]
Merged - thank you @hyperknot 

I'll close this now since I think it is done.
