### ISSUE TITLE
config name contains invalid characters

### ISSUE THREAD

**Issue by dud225** [rclone/rclone#6060]
Hello

I'm just starting with rclone:
```
$ rclone lsd ":http,url='https://pub.rclone.org':"
2022/03/25 16:14:29 Failed to create file system for ":http,url='https://pub.rclone.org':": config name contains invalid characters - may only contain 0-9, A-Z ,a-z ,_ , - and space
```
https://rclone.org/docs/#connection-strings

The other syntax works though:
```
$ rclone lsd --http-url https://pub.rclone.org :http:
```

**Comment by ncw** [comment]
Can you run that command with `-vv` and post the output please?

I suspect your shell is doing something odd!

Can you post the output of `rclone version` too please?

**Comment by dud225** [comment]
I was actually using the default version shipped by Debian which is old:
```
$ rclone lsd ":http,url='https://pub.rclone.org':" -vv
2022/03/25 21:23:32 DEBUG : rclone: Version "v1.53.3-DEV" starting with parameters ["rclone" "lsd" ":http,url='https://pub.rclone.org':" "-vv"]
2022/03/25 21:23:32 Failed to create file system for ":http,url='https://pub.rclone.org':": config name contains invalid characters - may only contain 0-9, A-Z ,a-z ,_ , - and space
```

When upgrading to the latest version I don't get this error anymore.
Sorry for the inconvenience.

**Comment by Masamune3210** [comment]
Yeah, word from the wise, just ignore the packaged version unless you have no other way. Its almost chronically outdated
