### ISSUE TITLE
vfs cached file increasing size when reading already cached range and rclone reads more data from remote

### ISSUE THREAD

**Issue by DEvmIb** [rclone/rclone#6063]
#### What is the problem you are having with rclone?

wondering why my hdd's spinning always up when reading same bytes from files already in the cache.
rclone increase the size of the cached file with new bytes from source file even i read just the first byte.

example:

- root@test:~# ls -lst .cache/rclone/vfs/\:local/test/test.img
- 6308 -rw------- 1 root root 104857600 26. Mär 14:39 .cache/rclone/vfs/:local/test/test.img
- root@test:~# dd if=/mnt/test/test.img of=/dev/null bs=1 count=1 &>/dev/null
- root@test:~# ls -lst .cache/rclone/vfs/\:local/test/test.img
- 6320 -rw------- 1 root root 104857600 26. Mär 14:39 .cache/rclone/vfs/:local/test/test.img
- root@test:~# dd if=/mnt/test/test.img of=/dev/null bs=1 count=1 &>/dev/null
- root@test:~# ls -lst .cache/rclone/vfs/\:local/test/test.img
- 6348 -rw------- 1 root root 104857600 26. Mär 14:39 .cache/rclone/vfs/:local/test/test.img
- root@test:~# dd if=/mnt/test/test.img of=/dev/null bs=1 count=1 &>/dev/null
- root@test:~# ls -lst .cache/rclone/vfs/\:local/test/test.img
- 6472 -rw------- 1 root root 104857600 26. Mär 14:39 .cache/rclone/vfs/:local/test/test.img
- root@test:~# dd if=/mnt/test/test.img of=/dev/null bs=1 count=1 &>/dev/null
- root@test:~# ls -lst .cache/rclone/vfs/\:local/test/test.img
- 9540 -rw------- 1 root root 104857600 26. Mär 14:39 .cache/rclone/vfs/:local/test/test.img

#### What is your rclone version (output from `rclone version`)

latest git. but problem also exist on older version compiled last year december.

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

linux

#### Which cloud storage system are you using? (e.g. Google Drive)

local, webdav ..

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone mount --vfs-cache-mode=full
rclone mount --vfs-cache-mode=full --vfs-read-ahead=0
rclone mount --vfs-cache-mode=full --vfs-read-ahead=0 --vfs-read-chunk-size=0
rclone mount --vfs-cache-mode=full --vfs-read-ahead=0 --vfs-read-chunk-size=0  --no-seek

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

[r.log](https://github.com/rclone/rclone/files/8355634/r.log)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Best to post questions on use in the forums rather than here.

That being said, it's a disk base cache not a memory cache.

This means it's reading from disk:

```
2022/03/26 15:32:33 DEBUG : test.img: vfs cache: checking remote fingerprint "104857600,2022-03-26 13:39:07.01243445 +0000 UTC,32fee22e2eeecbea4e128f672c1d2096" against cached fingerprint "104857600,2022-03-26 13:39:07.01243445 +0000 UTC,32fee22e2eeecbea4e128f672c1d2096"
2022/03/26 15:32:33 DEBUG : test.img: vfs cache: truncate to size=104857600
2022/03/26 15:32:33 DEBUG : : Added virtual directory entry vAddFile: "test.img"
2022/03/26 15:32:33 DEBUG : test.img(0xc00005d700): >openPending: err=<nil>
2022/03/26 15:32:33 DEBUG : vfs cache: looking for range={Pos:0 Size:16384} in [{Pos:0 Size:9768960}] - present true
```

The 'present true' means it read the file from the local cached file. It's not a memory cache. If you use full, you'll see disk usage as that's how it is designed.

If you need anything else, please use the forums for questions:

https://forum.rclone.org

**Comment by DEvmIb** [comment]
sorry, you understand me wrong.

the files are on hardisks with vfs on ssd. assuming i read the first 0-1024 from the file, rclone will cache this 0-1024 in the vfs cache. 
The size in the vfs cache is now 1024. when i now do the same thing and read the file from the mount point again 0-1024 the file in the vfs cache increased and rclone read new bytes from the remote. and this goes over and over.

**Comment by animosity22** [comment]
You seem to be running a beta/dev/some custom version:

```
2022/03/26 15:32:22 DEBUG : rclone: Version "v1.59.0-DEV" starting with parameters ["rclone" "mount" "--vfs-cache-mode=full" "--vfs-read-ahead=0" "--vfs-read-chunk-size=0" "--no-seek" "-vv" ":local:/test" "/mnt/test"]
```

Rclone uses sparse files so the size on a ls command will always show the full file even though is isn't all there:

```
felix@gemini:/cachem/Movies/vfs/dcrypt-movies/Norman (2021) {tmdb-598011}$ du -sh Norman\ \(2021\)\ \{tmdb-598011\}.mkv
16M	Norman (2021) {tmdb-598011}.mkv
felix@gemini:/cachem/Movies/vfs/dcrypt-movies/Norman (2021) {tmdb-598011}$ du -sh Norman\ \(2021\)\ \{tmdb-598011\}.mkv --apparent-size
6.6G	Norman (2021) {tmdb-598011}.mkv
```

As an example, I only have 16M of the file downloaded but appears to be 6.6G.

You can see in your debug log, it's reading from cache and not redownloading that section as it's present in the cache:

```
etexter@seraphim Downloads % grep "present" r.log
2022/03/26 15:32:33 DEBUG : vfs cache: looking for range={Pos:0 Size:16384} in [{Pos:0 Size:9768960}] - present true
2022/03/26 15:32:35 DEBUG : vfs cache: looking for range={Pos:0 Size:16384} in [{Pos:0 Size:9781248}] - present true
2022/03/26 15:32:38 DEBUG : vfs cache: looking for range={Pos:0 Size:16384} in [{Pos:0 Size:9809920}] - present true
```

I'm just reading what the log says.

**Comment by DEvmIb** [comment]
yes the sparse file incresing in size. you self posted my log: [{Pos:0 Size:9768960}] [{Pos:0 Size:9781248}]  [{Pos:0 Size:9809920}]  you can see the file in the cache got bigger. but i  always read only the first byte on the mount dd if=/mnt/test/test.img count=1 bs=1. why the file in the vfs increasing? rclone reads the new bytes from the remote. but i read the first byte from the cache ...why the file increase in size? 

i have this now test on latest release:

`rclone v1.58.0
- os/version: debian bookworm/sid (64 bit)
- os/kernel: 5.10.0-9-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.8
- go/linking: static
- go/tags: none`

1. reading first byte dd if=/mnt/test.img bs=1 count=1
2. vfs sparse size 4092
3. reading first byte dd if=/mnt/test.img bs=1 count=1
4. vfs sparse size 4096
5. reading first byte dd if=/mnt/test.img bs=1 count=1
6. vfs sparse size 4100
.... on every read it got bigger and the new data comes from the remote...

**Comment by animosity22** [comment]
You'd have to post a full debug log on a stable release to compare as on the stable release, it does not:

```
felix@gemini:~/test$ dd if=/home/felix/test/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv of=/dev/null bs=1 count=1
1+0 records in
1+0 records out
1 byte copied, 1.20994 s, 0.0 kB/s
felix@gemini:~/test$ ls -al /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
-rw------- 1 felix felix 404291584 Feb  2 10:09 /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
felix@gemini:~/test$ dd if=/home/felix/test/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv of=/dev/null bs=1 count=1
1+0 records in
1+0 records out
1 byte copied, 0.000489065 s, 2.0 kB/s
felix@gemini:~/test$ ls -al /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
-rw------- 1 felix felix 404291584 Mar 26 11:42 /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
felix@gemini:~/test$ dd if=/home/felix/test/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv of=/dev/null bs=1 count=1
1+0 records in
1+0 records out
1 byte copied, 0.000485729 s, 2.1 kB/s
felix@gemini:~/test$ ls -al /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
-rw------- 1 felix felix 404291584 Feb  2 10:09 /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
felix@gemini:~/test$ ls -al /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
-rw------- 1 felix felix 404291584 Feb  2 10:09 /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
felix@gemini:~/test$ dd if=/home/felix/test/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv of=/dev/null bs=1 count=1
1+0 records in
1+0 records out
1 byte copied, 0.00168057 s, 0.6 kB/s
felix@gemini:~/test$ ls -al /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
-rw------- 1 felix felix 404291584 Feb  2 10:09 /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
felix@gemini:~/test$ dd if=/home/felix/test/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv of=/dev/null bs=1 count=1
1+0 records in
1+0 records out
1 byte copied, 0.000518937 s, 1.9 kB/s
felix@gemini:~/test$ ls -al /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
-rw------- 1 felix felix 404291584 Feb  2 10:09 /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
felix@gemini:~/test$ dd if=/home/felix/test/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv of=/dev/null bs=1 count=1
1+0 records in
1+0 records out
1 byte copied, 0.000389097 s, 2.6 kB/s
felix@gemini:~/test$ ls -al /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
-rw------- 1 felix felix 404291584 Feb  2 10:09 /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
```

Debug log:

```
2022/03/26 11:42:44 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc0000c9940): openPending:
2022/03/26 11:42:44 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: vfs cache: checking remote fingerprint "404291584,2022-02-02 15:09:56 +0000 UTC,203d9deeb61e36fb7a62a227e9c5ad5fc7f86b1bf1278a7ca4c7368dc0e0f739" against cached fingerprint "404291584,2022-02-02 15:09:56 +0000 UTC,203d9deeb61e36fb7a62a227e9c5ad5fc7f86b1bf1278a7ca4c7368dc0e0f739"
2022/03/26 11:42:44 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: vfs cache: truncate to size=404291584
2022/03/26 11:42:44 DEBUG : : Added virtual directory entry vAddFile: "jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv"
2022/03/26 11:42:44 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc0000c9940): >openPending: err=<nil>
2022/03/26 11:42:44 DEBUG : vfs cache: looking for range={Pos:0 Size:16384} in [{Pos:0 Size:274432}] - present true
2022/03/26 11:42:44 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: ChunkedReader.RangeSeek from -1 to 274432 length -1
2022/03/26 11:42:44 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc0000c9940): >_readAt: n=16384, err=<nil>
2022/03/26 11:42:44 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: >Read: read=16384, err=<nil>
2022/03/26 11:42:44 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: Flush:
```

If you want to recreate, post commands with date/timestamps, happy to look at it.

**Comment by DEvmIb** [comment]
please use ls -ls not -la 
a=shows only . entrys
s=allocated size

then you see it and we found the problem together with my bad english :)

**Comment by animosity22** [comment]
Same thing:

```
felix@gemini:~/test$ dd if=/home/felix/test/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv of=/dev/null bs=1 count=1
1+0 records in
1+0 records out
1 byte copied, 0.000650842 s, 1.5 kB/s
felix@gemini:~/test$ ls -ls /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
284 -rw------- 1 felix felix 404291584 Feb  2 10:09 /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
felix@gemini:~/test$ dd if=/home/felix/test/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv of=/dev/null bs=1 count=1
1+0 records in
1+0 records out
1 byte copied, 0.000504638 s, 2.0 kB/s
felix@gemini:~/test$ ls -ls /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
296 -rw------- 1 felix felix 404291584 Feb  2 10:09 /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
felix@gemini:~/test$ dd if=/home/felix/test/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv of=/dev/null bs=1 count=1
1+0 records in
1+0 records out
1 byte copied, 0.00051639 s, 1.9 kB/s
felix@gemini:~/test$ ls -ls /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
324 -rw------- 1 felix felix 404291584 Feb  2 10:09 /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
felix@gemini:~/test$ du -sh /home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv --apparent-size
386M	/home/felix/.cache/rclone/vfs/DB/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
```

Doesn't increase in size.

**Comment by DEvmIb** [comment]
it does
284
296
324

at the left side....

**Comment by animosity22** [comment]
Sorry as I'm misunderstanding what size you are talking about.

So example log with some time stamps.

```
felix@gemini:~/test$ date
Sat 26 Mar 2022 12:13:59 PM EDT
felix@gemini:~/test$ dd if=/home/felix/test/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv of=/dev/null bs=1 count=1
1+0 records in
1+0 records out
1 byte copied, 0.0017619 s, 0.6 kB/s
```

and

```
2022/03/26 12:14:00 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: vfs cache: checking remote fingerprint "404291584,2022-02-02 15:09:56 +0000 UTC,203d9deeb61e36fb7a62a227e9c5ad5fc7f86b1bf1278a7ca4c7368dc0e0f739" against cached fingerprint "404291584,2022-02-02 15:09:56 +0000 UTC,203d9deeb61e36fb7a62a227e9c5ad5fc7f86b1bf1278a7ca4c7368dc0e0f739"
2022/03/26 12:14:00 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: vfs cache: truncate to size=404291584
2022/03/26 12:14:00 DEBUG : : Added virtual directory entry vAddFile: "jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv"
2022/03/26 12:14:00 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc0009a4640): >openPending: err=<nil>
2022/03/26 12:14:00 DEBUG : vfs cache: looking for range={Pos:0 Size:16384} in [{Pos:0 Size:356352}] - present true
2022/03/26 12:14:00 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: ChunkedReader.RangeSeek from -1 to 356352 length -1
2022/03/26 12:14:00 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc0009a4640): >_readAt: n=16384, err=<nil>
2022/03/26 12:14:00 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: >Read: read=16384, err=<nil>
2022/03/26 12:14:00 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: ChunkedReader.Read at -1 length 4096 chunkOffset 356352 chunkSize 134217728
2022/03/26 12:14:00 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: ChunkedReader.openRange at 356352 length 134217728
```

If run the same dd command again.

```
felix@gemini:~/test$ date
Sat 26 Mar 2022 12:14:07 PM EDT
felix@gemini:~/test$ dd if=/home/felix/test/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv of=/dev/null bs=1 count=1
1+0 records in
1+0 records out
1 byte copied, 0.00044969 s, 2.2 kB/s
```

and

```
2022/03/26 12:14:08 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc000426600): _readAt: size=16384, off=0
2022/03/26 12:14:08 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc000426600): openPending:
2022/03/26 12:14:08 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: vfs cache: checking remote fingerprint "404291584,2022-02-02 15:09:56 +0000 UTC,203d9deeb61e36fb7a62a227e9c5ad5fc7f86b1bf1278a7ca4c7368dc0e0f739" against cached fingerprint "404291584,2022-02-02 15:09:56 +0000 UTC,203d9deeb61e36fb7a62a227e9c5ad5fc7f86b1bf1278a7ca4c7368dc0e0f739"
2022/03/26 12:14:08 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: vfs cache: truncate to size=404291584
2022/03/26 12:14:08 DEBUG : : Added virtual directory entry vAddFile: "jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv"
2022/03/26 12:14:08 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc000426600): >openPending: err=<nil>
2022/03/26 12:14:08 DEBUG : vfs cache: looking for range={Pos:0 Size:16384} in [{Pos:0 Size:360448}] - present true
2022/03/26 12:14:08 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: ChunkedReader.RangeSeek from -1 to 360448 length -1
2022/03/26 12:14:08 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv(0xc000426600): >_readAt: n=16384, err=<nil>
2022/03/26 12:14:08 DEBUG : &{jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv (rw)}: >Read: read=16384, err=<nil>
2022/03/26 12:14:08 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: ChunkedReader.Read at -1 length 4096 chunkOffset 360448 chunkSize 134217728
2022/03/26 12:14:08 DEBUG : jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv: ChunkedReader.openRange at 360448 length 134217728
```

When rclone does a read, it does a range request to the remote. Default is 128M range request.

Rclone will read until the file is closed, so by asking for one block/range it's going to try to grab 128M and you keep nudging it with a new read even though it's 1 block, it's grabbing a little more before it's closed.

```
--vfs-read-chunk-size SizeSuffix        Read the source objects in chunks (default 128M)
```


@ncw @ivandeex  feel free to chime in if I'm not getting something correct as all seems normal to me, but I could be missing something (again)

**Comment by DEvmIb** [comment]
ok i find it out. the vfs file get increased until buffer-size is reached. with buffer-size=0 the effect does not happen.

**Comment by animosity22** [comment]
I think it's more a combo thing as if I set the buffer size to 1M, it never grows for me on a test file.

I think it's a combo of the range request / buffer size both getting more data and dropping it to the cache.

The smaller buffer size means there isn't much to dump since the request is closed out (I think).

**Comment by DEvmIb** [comment]
yeah the summary is rclone should write the complete buffer to the vfs cache else rclone will read on every access the pieces missing from cache from the original file until the cached file is size==buffer-size or multiple of buffer-size.

**Comment by ncw** [comment]
Rclone tries to get buffer size ahead of where the read point is as it assumes that you are going to read sequentially from there.

You can set buffer size to 0 to stop this as you've discovered, but maybe there is a better fix than that.

Can you describe the actual use case that caused you to notice this? That would be very helpful.

**Comment by DEvmIb** [comment]
I've shown it as a picture because of language barriers for better understanding

![Screenshot_20220402_091915](https://user-images.githubusercontent.com/9578262/161371893-2e300a65-b68d-4be4-b880-09c04b09f3b8.png)

**Comment by animosity22** [comment]
Directory listing only list out file attributes and such and do not read any of the actual files so that would not cause a read nor any HD to spin up as that's all done in memory.

Emby uses ffprobe against a file and it reads quite a bit more than 1MB of data to get the container information on a file. I'm not sure what you mean by a 'broken' media file.

**Comment by DEvmIb** [comment]
1MB ist just an example please, and metadata inside the file like modern filemanager does. you have to think outside the box sometimes, don't be mad at me but it's really frustrating.

**Comment by animosity22** [comment]
I'm not quite sure how you connect 'being mad at you' to 'correcting a bad piece of data'.

You didn't mention a modern file manager as you shared you about Emby (which I've tested a lot and uses ffprobe and I've very familiar with).

We're trying to get a fact based use case to help understand the problem that you are getting so we can help to solve it.

You had things wrong that I was correcting like a directory read listing causing an actual file read of data. If you list a directory, it doesn't do that.

If you are using a modern file manager that does a listing and asking for file meta data, that's different from the picture you shared.

Lots of folks read things here so making sure things are accurate and not incorrect.

I can think of many ways to generate this issue but the question was how did you figure it out.

My apologies for spending time and trying to help you figure out the problem you were getting as the goal here was to be helpful to you.
