### ISSUE TITLE
Can we have python Wrapper for rclone

### ISSUE THREAD

**Issue by ShreyPatel4** [rclone/rclone#6065]
Like i want to pass inputs from python file so every time i don't need to give inputs from command prompt.

**Comment by albertony** [comment]
Its not clear to me exactly what you would want, but have you seen the Python example that uses librclone?

https://github.com/rclone/rclone/tree/master/librclone#python

**Comment by TheTechRobo** [comment]
Also @ShreyPatel4 do you know about the `subprocess` module? Specifically the `subprocess.run` function?

You can run rclone's CLI commands from Python with that function. Might be simpler than using the Python bindings.

**Comment by ShreyPatel4** [comment]
To be perfectly honest i am not that aware with subprocess, it would be
nice if you set me up on the track by giving basic idea about subprocess

**Comment by TheTechRobo** [comment]
https://docs.python.org/3/library/subprocess.html#subprocess.run

```python
subprocess.run(["rclone", "copy", "drive:", "."], shell=False)
```

There's a lot of other stuff you can do with it, too.

**Comment by ShreyPatel4** [comment]
> https://docs.python.org/3/library/subprocess.html#subprocess.run
> 
> ```python
> subprocess.run(["rclone", "copy", "drive:", "."], shell=False)
> ```
> 
> There's a lot of other stuff you can do with it, too.
LETS SUPPOSE :

I want to pass static inputs of "rclone config" instead taking inputs from interactive shell then where and how can i do that ?

**Comment by TheTechRobo** [comment]
Look up how to pass standard input into subprocess.run

**Comment by ncw** [comment]
> I want to pass static inputs of "rclone config" instead taking inputs from interactive shell then where and how can i do that ?

You should never need to do that - you can pass the input on the `rclone config create` command line: see https://rclone.org/commands/rclone_config_create/

If you need a fully interactive config, check out this example: https://github.com/rclone/rclone/blob/master/bin/config.py

**Comment by abubelinha** [comment]
I am a complete newbie so haven't really used rclone yet (just a quick test of installing and creating a google drive remote, listing a remote folder and syncing it to a local drive). Looks great.

But I am actually interested in finding a way to sync my stuff from a Python script so I googled and found this issue and some other related links. From oldest to newest comments or code updates:
- 2018 / 09: https://github.com/ddragosd/python-rclone (pip [python-rclone](https://pypi.org/project/python-rclone/) says 'Work in progress. Experimental') looks like @ddragosd did not work on this anymore
- 2021 / 11: above mentioned [librclone python](https://github.com/rclone/rclone/tree/master/librclone#python). Link says 'This needs expanding and submitting to pypi...'. Also mentioned here:
  - 2022 / 03: https://forum.rclone.org/t/python-bindings/29684/3
  - 2022 / 10: https://forum.rclone.org/t/platform-independent-use-of-librclone-python-api/33286
- 2023 / 11: https://github.com/Johannes11833/rclone_python (pip [rclone-python](https://pypi.org/project/rclone-python/)) started by @Johannes11833 2022/08, so it seems to be an actively maintained repo.

As `rclone-python` seems the most recent approach to this subject, could someone tell me how does it compare to the other options mentioned here? (specially compared to `librclone` which seems to be part of the official rclone repository)
Which one would be the easiest python-approach for rclone newbies?

Thanks a lot in advance
@abubelinha
