### ISSUE TITLE
Under Windows, the mounted drive letter is not displayed

### ISSUE THREAD

**Issue by fantastic2085** [rclone/rclone#6067]
#### What is the problem you are having with rclone?
Under Windows, the mounted drive letter is not displayed
![image](https://user-images.githubusercontent.com/4116773/160754984-dd2f333e-4c2c-4d56-8b81-671a4c0c8091.png)

It's already installed winfsp-1.10.22006.msi

#### What is your rclone version (output from `rclone version`)
rclone-v1.58.0-windows-amd64

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
![image](https://user-images.githubusercontent.com/4116773/160755044-43d642e4-3d8d-41ca-8622-7a4473ee1636.png)

Windows is 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
Ceph 16.2.7

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone mount -vv zhiyu:/fuzhiyu  Q: --cache-dir d:\temp  --allow-other --attr-timeout 5m --vfs-cache-mode full --vfs-cache-max-age 2h --vfs-cache-max-size 5G --vfs-read-chunk-size-limit 100M --buffer-size 100M --fast-list --checkers 64 --transfers 64  &

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
![image](https://user-images.githubusercontent.com/4116773/160755123-c7ba9b96-a820-48b9-a925-6c4d2204e23b.png)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment]
Did you by any chance run the mount command from an elevated command prompt (i.e. as administrator)?

**Comment by fantastic2085** [comment]
> Did you by any chance run the mount command from an elevated command prompt (i.e. as administrator)?

I'm using the Administrator account @albertony

**Comment by fantastic2085** [comment]
> Did you by any chance run the mount command from an elevated command prompt (i.e. as administrator)?

Can I not use the Administrator account in Windows？

**Comment by fantastic2085** [comment]
@albertony To execute this command, run the following command: 
New-Service -Name Rclone -BinaryPathName 'c:\rclone\rclone.exe mount remote:/files X: --config c:\rclone\config\rclone.conf --log-file c:\rclone\logs\mount.txt'

**Comment by fantastic2085** [comment]
New-Service -Name rclone -BinaryPathName 'C:\Program Files\rclone\rclone.exe mount zhiyu:/fuzhiyu F: --config C:\Users\Administrator\AppData\Roaming\rclone\rclone.conf --log-file c:\rclone\logs\mount.txt'

![image](https://user-images.githubusercontent.com/4116773/160769565-dc4712ff-282c-4eb6-831e-8b4ed85f1b42.png)

**Comment by albertony** [comment]
Yes that works, using the following which is just mounting a local folder and does not rely on any configuration:
```
New-Service -Name Rclone -BinaryPathName 'C:\rclone\rclone.exe mount C:\Temp X: --config NUL --log-file C:\Temp\rclone_mount.txt'
Start-Service Rclone
````

**Comment by albertony** [comment]
Does the command work when not creating it as a service? Make sure that works first.

**Comment by asdffdsazqqq** [comment]
hello, @fantastic2085, why not post in the public forum?

if you run a `rclone mount` with elevated privileges, then windows explorer cannot see it.

workarounds are
1. run `rclone mount` with standard elevated, then windows explorer can see it.
2. do what i do,
run `rclone mount` where the mount point to a folder, not drive letter
`rclone mount remote: b:\rclone\mount\remote`
3. run `rclone mount` as system user. tho that can create some problems.

` --allow-other` does nothing on windows.
`--fast-list` does not work on `rclone mount`
`--checkers`, as far as i know, does nothing on a `rclone mount`

**Comment by animosity22** [comment]
Answered and stale..
