### ISSUE TITLE
[Documentation] docker compose and rshared

### ISSUE THREAD

**Issue by Nalsai** [rclone/rclone#6070]
#### What is your current rclone version (output from `rclone version`)?
v1.57.0

#### What problem are you are trying to solve?
mounting cloud storage via rclone using docker compose and accessing it from outside

#### How do you think rclone should be changed to solve that?
I would like to have some documentation added to the `Install with docker` section, explaining that you need to use rshared.
Ideally, I would like to have an example docker compose file added.
https://github.com/TheNexter/Rclone-Mount-Docker-Compose/blob/main/docker-compose.yml
https://forum.rclone.org/t/docker-compose-not-working/15700

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Feel free to do a pull request to help in the documentation.

**Comment by ncw** [comment]
@Nalsai would you like to add another section in https://github.com/rclone/rclone/blob/master/docs/content/install.md ?

You can edit this page online (click pencil in top right) or do the traditional checkout and pull request.
