### ISSUE TITLE
Graceful error handling rather than Log.Fatal within cmd.go

### ISSUE THREAD

**Issue by AbdulHaseebHussainRI** [rclone/rclone#6090]
#### The associated forum post URL from `https://forum.rclone.org`
N/A

#### What is the problem you are having with rclone?
I am hitting this [error](https://github.com/rclone/rclone/blob/17f801490968f2ad0ef61e12578cacf72777f1aa/cmd/cmd.go#L119) infrequently with specific files in one drive, unfortunately given that it triggers a log.Fatal I have no way of recovering from this error and continuing to process other files. The list of files to be processed is dynamic and this is a blocking us. On deleting and re-uploading the file we get around the error on retrying our lambda but it would be good to have not have to do this through graceful error handling either by returning an error to the caller or at a minimum maybe panic.

#### What is your rclone version (output from `rclone version`)
given the log.Fatal is in the current code then this will occur in the latest version. 

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
one drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
this is before we get to this stage

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
this is before we get to this stage

**Comment by ncw** [comment]
How are you running rclone? Via the command line? If so can you paste what your command line is please?

Can you also paste a log with `-vv` of the error happening please?
