### ISSUE TITLE
Default path for --workdir on macOS

### ISSUE THREAD

**Issue by m-zheng** [rclone/rclone#6095]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/is-bisync-ready-for-prime-time/30109/3

#### What is the problem you are having with rclone?
According to the [document](https://rclone.org/bisync/), the default path for `--workdir` is `~/.cache/rclone/bisync`. However, it is actually `~/Library/Caches/rclone/bisync/` on macOS. I am not sure if this is expectd behaviour or the document needs updating since I have not encoutered any issues using it unless the `~/Library/Caches` folder is cleared.

#### What is your rclone version (output from `rclone version`)
rclone v1.58.0 installed via homebrew

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
macOS Monterey 12.3.1 - intel chip.

#### Which cloud storage system are you using? (e.g. Google Drive)
Dropbox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone bisync ~/Dropbox/Documents/Academic/Magazines/ dropbox:/Documents/Academic/Magazines/ --filters-file ~/Dropbox/.filter_file.txt -v -vv`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2022/04/09 14:10:38 DEBUG : rclone: Version "v1.58.0" starting with parameters ["rclone" "bisync" "/Users/ming/Dropbox/Documents/Academic/Magazines/" "dropbox:/Documents/Academic/Magazines/" "--filters-file" "/Users/ming/Dropbox/.filter_file.txt" "-v" "-vv"]
2022/04/09 14:10:38 DEBUG : Creating backend with remote "/Users/ming/Dropbox/Documents/Academic/Magazines/"
2022/04/09 14:10:38 DEBUG : Using config file from "/Users/ming/.config/rclone/rclone.conf"
2022/04/09 14:10:38 DEBUG : Creating backend with remote "dropbox:/Documents/Academic/Magazines/"
2022/04/09 14:10:38 DEBUG : Dropbox root '': Using root namespace "1179184587"
2022/04/09 14:10:39 DEBUG : fs cache: renaming cache item "dropbox:/Documents/Academic/Magazines/" to be canonical "dropbox:Documents/Academic/Magazines"
2022/04/09 14:10:39 NOTICE: bisync is EXPERIMENTAL. Don't use in production!
2022/04/09 14:10:39 DEBUG : Lock file created: /Users/ming/Library/Caches/rclone/bisync/Users_ming_Dropbox_Documents_Academic_Magazines..dropbox_Documents_Academic_Magazines.lck
2022/04/09 14:10:39 INFO  : Synching Path1 "/Users/ming/Dropbox/Documents/Academic/Magazines/" with Path2 "dropbox:Documents/Academic/Magazines/"
2022/04/09 14:10:39 INFO  : Using filters file /Users/ming/Dropbox/.filter_file.txt
2022/04/09 14:10:39 DEBUG : Lock file removed: /Users/ming/Library/Caches/rclone/bisync/Users_ming_Dropbox_Documents_Academic_Magazines..dropbox_Documents_Academic_Magazines.lck
2022/04/09 14:10:39 ERROR : Bisync critical error: cannot find prior Path1 or Path2 listings, likely due to critical error on prior run
2022/04/09 14:10:39 ERROR : Bisync aborted. Must run --resync to recover.
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Feel free to submit a PR to fix the MacOS as it lists Linux and Windows.

**Comment by ivandeex** [comment]
The default value of `--workdir` in bisync is derived from rclone-global `--cache-dir` setting - [see code](https://github.com/rclone/rclone/blob/v1.58.0/cmd/bisync/cmd.go#L52).
Waiting for a MacOS owner to confirm this behavior and patch rclone docs regarding `--cache-dir` and bisyn'c `--workdir`.
I don't or won't have Mac in foreseeable future.
Hey @albertony if my memory doesn't fail me, you worked on config cleanups recently so you might be aware.

**Comment by ncw** [comment]
Doing

    rclone help flags cache-dir

Will confirm the default location on macOS.

We try to use the OS defined user cache area

https://github.com/rclone/rclone/blob/f065a267f6ca66df6814520f406155087b28bbcc/fs/config/config.go#L676-L679

You can see that it is `~/Library/Caches` for macOS there.

PS It looks like the guts of that function is now in the go stdlib: https://pkg.go.dev/os#UserCacheDir so I'll refactor it now!
