### ISSUE TITLE
Rclone mount cannot process files whose filename or path contains non-Roman characters

### ISSUE THREAD

**Issue by Yunseo47** [rclone/rclone#6100]
#### What is the problem you are having with rclone?
Rclone mount cannot process files whose filename or path contains non-Roman characters.

#### What is your rclone version (output from `rclone version`)
v1.58.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
macOS 12.3.1

#### Which cloud storage system are you using? (e.g. Google Drive)
Microsoft OneDrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
~~~
rclone mount remote:path/to/files /path/to/local/mount
~~~

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
~~~
2022/04/12 00:54:07 DEBUG : rclone: Version "v1.58.0" starting with parameters ["rclone" "mount" "archive:" "/Users/yunseo/Movies/archive" "--daemon" "-vv"]
2022/04/12 00:54:07 DEBUG : Creating backend with remote "archive:"
2022/04/12 00:54:07 DEBUG : Using config file from "/Users/yunseo/.config/rclone/rclone.conf"
2022/04/12 00:54:07 DEBUG : Creating backend with remote "onedrive:Archive"
2022/04/12 00:54:12 DEBUG : rclone: Version "v1.58.0" finishing with parameters ["/usr/local/bin/rclone" "mount" "archive:" "/Users/yunseo/Movies/archive" "--daemon" "-vv"]
~~~

**Bug Description**
Hi, I am a Korean user who loves Rclone. Recently, I found that the Rclone mount function could not handle files containing non-Roman in the file name or path. I found no error on the log, so it took me a long time to spot this bug...

As a result of the experiment, at least in my environment, Rclone's ls, copy, move, and cryptdecode commands worked normally. This bug appears to occur only in the mount command.

I hope that this bug will be fixed in future versions of Rclone for i18n users. In addition, Rclone's docs should include a notice of this bug until it is corrected.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
This is might be a macOS encoding issue.

> I found no error on the log, so it took me a long time to spot this bug...

If you run the command without `--daemon` you'll get to see the log. You can use `--log-file rclone.log` to write it to a file.

Can you check there is a line like this in the debug

    Adding "-o modules=iconv,from_code=UTF-8,to_code=UTF-8-MAC" for macOS

Please attach a full log to this issue of you listing the root directory and describe what happens to the file names with Korean characters. Are they corrupted or missing?

Thanks

**Comment by animosity22** [comment]
@Yunseo47  - any updates as I'm going to close this as stale.

**Comment by animosity22** [comment]
Stale.

**Comment by Yunseo47** [comment]
Hello, sorry for the late reply.

> Can you check there is a line like this in the debug
> ~~~
> Adding "-o modules=iconv,from_code=UTF-8,to_code=UTF-8-MAC" for macOS
> ~~~
Yes, you're right; I found this line in the log file.

> Please attach a full log to this issue of you listing the root directory

Here is the full log file. [rclone.log](https://github.com/rclone/rclone/files/8647674/rclone.log)

The following is the unencrypted file name with Korean characters used for the test.
"스크린샷 2022-01-02 오전 7.27.56.png"
This file is located in 'archive:ScreenRecords'. And as the log shows, the source of crypt remote 'archive:' is 'onedrive:Archive.'
It's mounted to ```~/Movies/Archive```.

> describe what happens to the file names with Korean characters. Are they corrupted or missing?

In both macOS' finder and terminal, the system does not recognize any files containing non-Roman characters in their names; they are missing, and I cannot find or read/write them.

Thanks :)
