### ISSUE TITLE
bug: copying files to DigitalOcean Spaces using rclone causes timeout

### ISSUE THREAD

**Issue by anishghimire862** [rclone/rclone#6110]
#### What is the problem you are having with rclone?

`Copying files to DigitalOcean Spaces causes timeout`

#### What is your rclone version (output from `rclone version`)

`rclone v1.58.0`

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

`ubuntu 20.4`

#### Which cloud storage system are you using? (e.g. Google Drive)

DigitalOcean

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
rclone copy /root/foo.txt --s3-access-key-id=<ACCESS_KEY> --s3-secret-access-key=<ACCESS_SECRET> --s3-provider=DigitalOcean --s3-endpoint=https://bucket.nyc3.digitaloceanspaces.com :s3:foo --error-on-no-transfer
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2022/04/17 06:35:54 ERROR : Attempt 1/3 failed with 1 errors and: RequestError: send request failed
caused by: Head "https://foo.bucket.nyc3.digitaloceanspaces.com/foo.sh": x509: certificate is valid for *.nyc3.digitaloceanspaces.com, nyc3.digitaloceanspaces.com, not foo.bucket.nyc3.digitaloceanspaces.com
```

Now, if I run the following command the file gets copied without any issues. 

```
rclone copy /root/foo.txt --s3-access-key-id=<ACCESS_KEY> --s3-secret-access-key=<ACCESS_SECRET> --s3-provider=DigitalOcean --s3-endpoint=https://bucket.nyc3.digitaloceanspaces.com :s3:foo_bar --error-on-no-transfer
```

The only difference here is in the bucket name. The first one with issue uses a single word as bucket name which times out. The second one uses `_` in the bucket name and it makes it work.

Any help is much appreciated.

**Comment by ncw** [comment]
Can you show your config with secrets redacted please?

Also a log with `-vv` of the timeout would be useful - thanks.

**Comment by ashokgelal** [comment]
I've run into the same issue and have confirmed this issue. Here is a screenshot of -vv:

![CleanShot 2022-04-17 at 13 55 44](https://user-images.githubusercontent.com/401055/163726594-648d4f4b-983d-44a7-8b02-1306cce93a45.png)

**Comment by ashokgelal** [comment]
Same command except that this time it is `:s3:foo_bar` instead of `:s3:foo`

![CleanShot 2022-04-17 at 13 59 13](https://user-images.githubusercontent.com/401055/163726683-ecb4ef20-3f63-4865-b18c-3de19eea2b66.png)

**Comment by anishghimire862** [comment]
Hello @ncw,

Thank you for your time. 

Were you able to reproduce the issue? 

Do let me know if you need any more details related with the issue.

**Comment by Slugger** [comment]
My initial fix isn't correct -- we should not be setting a quirk for DO.  See the closed PR for more details, but the issue appears to be a bug upstream in the AWS sdk.  There is a workaround, which would be to just set `--s3-force-path-style` on your command line.  But making that the default for DO would be incorrect.

**Comment by ncw** [comment]
So what do do? Document somewhere and move on?

Some help in the force path style option might be appropriate, something like if your bucket isn't a valid DNS name, ie has `.` or `_` you'll need to set force path style to true?
