### ISSUE TITLE
File modes not set by 'install' script.

### ISSUE THREAD

**Issue by MCT-MIT-RCP** [rclone/rclone#6113]
#### The associated forum post URL from `https://forum.rclone.org`

N/A

#### What is the problem you are having with rclone?

Installation "Assumes" that the environment's mode settings are appropriate for the installed binary.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.58.0
- os/version: darwin 12.3.1 (64 bit)
- os/kernel: 21.4.0 (x86_64)
- os/type: darwin
- os/arch: amd64
- go/version: go1.17.8
- go/linking: dynamic
- go/tags: cmount
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Mac OSX (64)

#### Which cloud storage system are you using? (e.g. Google Drive)

N/A

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

'rclone'

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
rclone
-bash: /usr/local/bin/rclone: Permission denied
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Are you going to handle this via the pull? Can this be closed out?
