### ISSUE TITLE
Terabox

### ISSUE THREAD

**Issue by Syzran** [rclone/rclone#6122]
Please make cloud storage systems terabox.com

**Comment by animosity22** [comment]
It has no API so nothing to add unfortunately.

**Comment by SPDurkee** [comment]
Here is information on the Terabox API. Hopefully it can be supported by rclone.

Uploading:
https://gist.github.com/CypherpunkSamurai/58d8f2b669e101e893a6ecf3d3938412
https://github.com/yasithpiyarathne/teraboxer

Downloading:
https://github.com/maiquocthinh/Terabox-DL
https://github.com/fskhri/TeraboxDownloader

**Comment by ncw** [comment]
@SPDurkee are these reverse engineered APIs? We only take these on if we can take on a maintainer for them at the same time.

**Comment by sistematod** [comment]
![Screenshot_34](https://github.com/rclone/rclone/assets/121248957/64ef88cf-316d-4b70-b227-97f968cf9414)
![Sin título](https://github.com/rclone/rclone/assets/121248957/0f583ccc-cac8-43d2-8bb3-88a3c5eca0c2)

**Comment by lone-gunman** [comment]
Terabox provide public API 
https://www.terabox.com/integrations/docs?lang=en

**Comment by Silverbullet069** [comment]
Have anyone worked on this platform? I plan to do it now,

**Comment by Silverbullet069** [comment]
> Not sure, but see here: [#7496 (comment)](https://github.com/rclone/rclone/issues/7496#issuecomment-2741306606)

Hmm he didn't public the repository. Might be closed-source.

**Comment by fidodido48** [comment]
Anybody looking into this anymore?
Thread seems to be stalled/gone dead...

**Comment by b0rrasca** [comment]
Been using this for months without issue. It would be great if this got merged.
