### ISSUE TITLE
Make Use of IPv4 also in Dual Stack Network

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#6124]
#### The associated forum post URL

N/A

#### What is your current rclone version ?

v1.58.0

#### What problem are you are trying to solve?

Some ISPs allocate full bandwidth on both IPv4 and IPv6 Network. So, If I am on 100 Mbps Plan, I will get 100 Mbps on both IPv4 and IPv6 seperately and I can use this to get total output of 200 Mbps if software (in this case rclone) is able to make use of it. I was able to test it by running two rclone instances with one binded to IPv4 and another to IPv6. But, This is a hectic process and can be troublesome to use when trying to upload or download a folder through single instance. Would be cool thing if rclone either by default make use of it or could add a flag to enable this feature.

#### How do you think rclone should be changed to solve that?

Try and Use IPv4 and IPv6 alternatively while downloading files from services which support Dual Stack Networks like Google Drive etc.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
That's feels like a really edge use case.

Happy to make it an enhancement but doubtful it'll move.

**Comment by ncw** [comment]
I think this would need a new http transport. It could maybe be done by modifying rclone's existing transport. You'd need to modify the name resolution in the Dial command so it only returned IPv4 or IPv6 addresses.

I think it is possible, but not easy!

@SmogrHzzgn do you want to work on this?

**Comment by SmogrHzzgn** [comment]
> @SmogrHzzgn do you want to work on this?

Seems too much complicated for me as of right now.

**Comment by SmogrHzzgn** [comment]
> @SmogrHzzgn do you want to work on this?

@ncw, This seems too much complicated for me as of right now as I don't have much experience in Go.

**Comment by ncw** [comment]
I wonder if you can get an http proxy which does this? If so then you could use it via rclone.

**Comment by buengese** [comment]
We already customize the Dialer for fshttp.Client and we might achieve this with relatively minimal changes to `DialContext`. I'll look into it.

**Comment by ncw** [comment]
I've merged a fix for this this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.64 

You can use `--bind 0.0.0.0` to force rclone to use IPv4 addresses and `--bind ::0` to force rclone to use IPv6 addresses.
