### ISSUE TITLE
Compare source and destination files by checksum, ignoring the folder structure. I can sponsor for time.

### ISSUE THREAD

**Issue by henryk-radoslaw-rychlik** [rclone/rclone#6131]
Hello, I checked the docs and tried searching through the forum.

#### What is your current rclone version (output from `rclone version`)?
Newest available from v1.59.0-DEV

#### What problem are you are trying to solve?
I have a temp folder where I upload files to be brought into seafile library and segregated manually. This is my source for rclone runs. Seafile is the destination. The problem is that I have to delete the files manually after upload without a guarantee the file got properly copied. rclone can't check that because despite the file(and checksum) being the same, the path differs because the files at the destination have been organized into a different directory structure.
Also, when a file already exists at the destination as a duplicate of a file at source(already uploaded), it would be nice to automatically discard of it.

#### How do you think rclone should be changed to solve that?
Well, it already scans and compares the directory structure at source and destination, including optional checksum support. Can you add an option that will ignore the location and treat the file as copied/synced if a file with the same name/checksum exists?
This should be as simple as dropping the result of a location check.
I can script in python but go is new to me. If you could point me to a location where this could be done(operations I think), I could attempt to do it myself.

Also, cool project, how much would you like me to pay to do it ASAP?
#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> rclone can't check that because despite the file(and checksum) being the same, the path differs because the files at the destination have been organized into a different directory structure

I don't understand this bit. How to do the files get organized into a different directory structure? Do you manually move them?

Why not run `rclone check` before you move the files?

**Comment by henryk-radoslaw-rychlik** [comment]
> How to do the files get organized into a different directory structure? 
I move them around and organize after copying to seafile.

> Why not run rclone check before you move the files?
Because it doesn't check hashes only, it relies on file paths as well.

I think I just found a solution, I was so focused on the seafile web interface having upload functionality only. I can use rclone to move files to the library instead. Then dedupe them. This means files get moved instead of being manually uploaded via the web interface, there will be no need for painstaking and careful deletion of uploaded files from the local folder(this is where I was making mistakes and what I wanted to automate).
After the files get moved to the seafile library, I can dedupe them there. Seafile doesn't seem to support hashes but webdav mount does. I think I'm all set at this point.

What I originally wanted to do is remove files already copied to seafile from a local directory using hashes. This would also remove any duplicates and prevent them from being uploaded.

**Comment by ncw** [comment]
I'm glad you've found a solution. Often a little tweak of workflow and rclone can do what you want!

I'll close this now.
