### ISSUE TITLE
symbolic link stat error result in I/O error

### ISSUE THREAD

**Issue by xp-1000** [rclone/rclone#6146]
Hello, thanks for your work, rclone is a very cool tool!

#### The associated forum post URL from `https://forum.rclone.org`

I did not post my problem on the forum because I seen:
https://forum.rclone.org/t/symbolic-link-stat-error-on-excluded-file-result-in-i-o-error/23539
which seems to be the same problem (or at least related).

while I did not find opened issue about that here it is.

#### What is the problem you are having with rclone?

In my case, I do not use `sync` but rclone `mount` and when I try to copy a symlink from the filesystem I got the error:

> failed: Input/output error (5)

I read answers from the related forum post which make sens for me. I don't think I can use `--skip-links` with `mount` but I still could exclude symlinks from my copy process (`rsync` for me) as workaround.

Sadly, symlinks is crucial for me and I need to handle them as all other files.

If you want more context:
I use `rclone` as `unison` engine on local directories so you can think to rclone as a replacement for `aufs`.
Then I simply use `rsync` to backup my data (hosted on a true raid) to another server where I don't have raid (so I use rclone unison to aggregate different separate disks).
These data contain symlinks used and required by different softwares to work so in my case, skipping links would result in partial backup and a failing restoration (at least some services will not work as expected).

#### What is your rclone version (output from `rclone version`)

```
rclone --version
rclone v1.58.1
- os/version: debian 10.4 (64 bit)
- os/kernel: 4.19.0-9-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.9
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

> Debian 4.19.118-2+deb10u1

#### Which cloud storage system are you using? (e.g. Google Drive)

local with unison

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

here is a crappy process to simulate/demonstrate the error easily:

```
$ mkdir /tmp/rclone
$ cd /tmp/rclone/

$ cat <<EOF > rclone.conf
[test]
type = union
upstreams = /tmp/rclone/a /tmp/rclone/b
EOF

$ mkdir a b unison tosync
$ mount test: /tmp/rclone/unison -t rclone -o rw,allow_other,config=/tmp/rclone/rclone.conf
$ touch symlinkdest
$ cd tosync/
$ touch okfile
$ ln -s /tmp/rclone/symlinkdest kolink
$ rsync --inplace --progress -auv --delete /tmp/rclone/tosync/ /tmp/rclone/unison
sending incremental file list
deleting toto
rsync: symlink "/tmp/rclone/unison/kolink" -> "/tmp/rclone/symlinkdest" failed: Input/output error (5)
./
okfile
              0 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=0/3)

sent 156 bytes  received 153 bytes  618.00 bytes/sec
total size is 23  speedup is 0.07
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
```

I am pretty sure there are other ways to get this error with pure rclone command but I prefer to not assume to much and give you test case which fully corresponds to my problem.

I still can lead more tests if you prefer to simplify the setup (no unison, no rsync ..)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Duplicate.

You can follow - > https://github.com/rclone/rclone/issues/2975

**Comment by animosity22** [comment]
You are asking about symbolic link support on a mount as that's what the linked issue is.

Am I not understanding something (always possible - ha)?

**Comment by xp-1000** [comment]
no I just want to apologize for the inconvenience because I seen the other issue before opening this one but I did not read more than the title.

I subscribed to the other issue, thanks for your support

**Comment by animosity22** [comment]
Zero inconvenience at all as I'm wrong almost as much as I'm right so that's why I was asking :)
