### ISSUE TITLE
RClone cannot mount to file if icon is changed

### ISSUE THREAD

**Issue by Naginipython** [rclone/rclone#6149]
#### What is the problem you are having with rclone?
As stated above, let's say I have 2 files, one named "test" and another named "test2." I right-click "test" in Dolphin, click "properties" and then I click the icon box next to the name of the file and change the icon.
Then, once I run `rclone mount --daemon gdrive: /home/user/test` I get a 1 minute wait, followed by `2022/05/04 17:25:02 Fatal error: mount not ready`
However, if I use the same command except for "test2" folder, untouched, it takes a mere few seconds and it's fine and mounted.

#### What is your rclone version (output from `rclone version`)
I also attempted on the main current version, this is rclone-git.
rclone v1.59.0-DEV
- os/version: arch "rolling" (64 bit)
- os/kernel: 5.17.5-arch1-1 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.18.1
- go/linking: dynamic
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
EndeavourOS Linux 86_64
5.17.5-arch1-1

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive and One Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone mount --daemon gdrive: /home/user/test`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
NOTE: did censor user's name and root_folder_id
```
2022/05/04 17:32:36 DEBUG : rclone: Version "v1.59.0-DEV" starting with parameters ["rclone" "-vv" "mount" "--daemon" "gdrive:" "/home/user/test2"]
2022/05/04 17:32:36 DEBUG : Creating backend with remote "gdrive:"
2022/05/04 17:32:36 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2022/05/04 17:32:42 DEBUG : Google drive root '': 'root_folder_id = [CENSORED]' - save this in the config to speed up startup
2022/05/04 17:33:42 DEBUG : Daemon timed out. Terminating daemon pid 35785
2022/05/04 17:33:42 Fatal error: mount not ready
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> As stated above, let's say I have 2 files, one named "test" and another named "test2."

Do you mean two folders?

> I right-click "test" in Dolphin, click "properties" and then I click the icon box next to the name of the file and change the icon.

I suspect Dolphin is writing something in the folder to store the icon which then makes the mount fail as the directory isn't empty.

If you follow @animosity22 suggestion to remove --daemon and use -vv we'll know for sure.

If you look inside the "test" folder in the shell with `ls -la test` what do you see?

**Comment by Naginipython** [comment]
> Any reason you are using a DEV build and not a stable version?

The reason I'm using the DEV build is, as I've stated, I attempted to use the current normal version using `yay -S rclone` but since this is github, I decided to try again with the git version, I removed my rclone and did `yay -S rclone-git`
Alright, I ran the command: `rclone -vv mount gdrive: /home/user/test` with test, of course, being the folder with the changed icon. I got: 
```
2022/05/05 18:19:01 DEBUG : rclone: Version "v1.59.0-DEV" starting with parameters ["rclone" "-vv" "mount" "gdrive:" "/home/user/test"]
2022/05/05 18:19:01 DEBUG : Creating backend with remote "gdrive:"
2022/05/05 18:19:01 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2022/05/05 18:19:01 DEBUG : gdrive: Loaded invalid token from config file - ignoring
2022/05/05 18:19:06 DEBUG : Saving config "token" in section "gdrive" of the config file
2022/05/05 18:19:06 DEBUG : gdrive: Saved new token in config file
2022/05/05 18:19:12 DEBUG : Google drive root '': 'root_folder_id = [CENSORED]' - save this in the config to speed up startup
2022/05/05 18:19:12 DEBUG : Google drive root '': Mounting on "/home/user/test"
2022/05/05 18:19:12 mount helper error: fusermount: mountpoint is not empty
2022/05/05 18:19:12 mount helper error: fusermount: if you are sure this is safe, use the 'nonempty' mount option
2022/05/05 18:19:12 Fatal error: failed to mount FUSE fs: fusermount: exit status 1
```

> Do you mean two folders?

Sorry, yes I did.

> If you look inside the "test" folder in the shell with `ls -la test` what do you see?

Hmm, it does appear to add something. Test, the folder with an icon, lists this:
```
total 12
drwxr-xr-x  2 ben ben 4096 May  5 18:18 .
drwx------ 24 ben ben 4096 May  5 18:25 ..
-rw-------  1 ben ben   35 May  5 18:18 .directory
```
And the non-icon folder lists:
```
total 8
drwxr-xr-x  2 ben ben 4096 May  5 18:25 .
drwx------ 24 ben ben 4096 May  5 18:25 ..
```
Seeing how the debug for rclone says:
>2022/05/05 18:19:12 mount helper error: fusermount: mountpoint is not empty
2022/05/05 18:19:12 mount helper error: fusermount: if you are sure this is safe, use the 'nonempty' mount option

Seems like the icon adds something to the folder, making it not empty. How do I add a mount option  'nonempty'? Should I still use `--daemon` like I had?

**Comment by animosity22** [comment]
You should clear out any files and ensure the Mount point is empty as if you don't, you'll hide things.

**Comment by Naginipython** [comment]
I mean, the reason for my issue is that the file was already hidden, and I didn't realize. Seems Dolphin makes a .directory file to the folder. It would appear to need that file in order for the icon to appear... The file in question contains:
```
[Desktop Entry]
Icon=insync-folder
```
Would it be possible to keep the hidden folder, and still have it be a mount?

**Comment by animosity22** [comment]
If you over mount, it hides anything so it's a really bad idea.


You can use --allow-non-empty to Mount with files there.

**Comment by Naginipython** [comment]
So, to clarify, if it's a folder with the only thing inside being a hidden file, will that be a problem?

**Comment by animosity22** [comment]
It's up to you. I've said a few times I wouldn't but that's me so you have to decide if in your situation, it's ok. For me, it's a hard no.

**Comment by Naginipython** [comment]
kk, I'm going to conduct some tests in that case. Thank you so much for your help! And thanks to @ncw for the help as well!

**Comment by Naginipython** [comment]
kk, I'm going to conduct some tests in that case. Thank you so much for your help! And thanks to @ncw for the help as well!

**Comment by Naginipython** [comment]
K, so upon testing, it removes the icon regardless. Either I need to make the hidden folder elsewhere, or deal with it not having one. OOP

**Comment by animosity22** [comment]
For any use questions, please use the forums as well.

Thanks!
