### ISSUE TITLE
rclone mount source target (msys64)

### ISSUE THREAD

**Issue by pdj9na** [rclone/rclone#6158]
rclone v1.58.0
- os/version: Microsoft Windows 7 Ultimate Service Pack 1 (64 bit)
- os/kernel: 6.1.7601.24546 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.17.8
- go/linking: dynamic
- go/tags: cmount

===================
Execute the following command under msys64 bash
rclone mount omv.smb:/ 'C:\mnt\omv.smb'
Errors occur:
Failed to create file system for "omv.smb;C:\\\\msys64\\\\": config name contains invalid characters - may only contain `0-9`, `A-Z`, `a-z`, `_`, `-`, `.` and space

omv.smb is the alias shared by Samba

**Comment by animosity22** [comment]
Please use the forums for general support questions.

https://forum.rclone.org/
