### ISSUE TITLE
rclone mount vmwarehost:/0/C "C:\mnt\0\C"

### ISSUE THREAD

**Issue by pdj9na** [rclone/rclone#6159]
rclone v1.58.1                                             
- os/version: Microsoft Windows 10 Enterprise 20H2 (64 bit)
- os/kernel: 10.0.19042.1682 (x86_64)                      
- os/type: windows                                         
- os/arch: amd64                                           
- go/version: go1.17.9                                     
- go/linking: dynamic                                      
- go/tags: cmount                              

===================

rclone mount vmwarehost:/0/C "C:\mnt\0\C"
# vmwarehost is Windows 7
# vmwarehost:/0/C  C is the disk mount point

2022/05/09 15:51:31 ERROR : Local file system at //?/C:/Users/admin/␛[A␛[B/PC000/mnt/0/C: Statfs failed: failed to read disk usage: The system cannot find the path specified.

**Comment by animosity22** [comment]
Please use the forums for general support questions and make sure to use the help and support template.

https://forum.rclone.org/
