### ISSUE TITLE
webdav: Duplicate object/directory found in destination & 409 Conflict

### ISSUE THREAD

**Issue by geeklihui** [rclone/rclone#6161]
#### What is the problem you are having with rclone?
Errors when sync files with a webdav server:

> Duplicate object found in destination - ignoring
> Failed to copy: 409 Conflict
> Update mkParentDir failed: 409 Conflict
> Duplicate directory found in destination - ignoring

#### What is your rclone version (output from `rclone version`)
rclone v1.58

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
centos 7.8.2003 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)
webdav of [aliyun ](https://www.aliyundrive.com/drive/)by using this [docker image](https://registry.hub.docker.com/r/messense/aliyundrive-webdav).

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone sync /mnt/Sea/data/data/ aliyun:/TrueNAS/nextcloud/ --log-file /mnt/Sea/Logs/rclone/sync_data_a.log`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
Attached: (PW: DfG38$#p)
[sync_data_a_new.zip](https://github.com/rclone/rclone/files/8667321/sync_data_a_new.zip)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
1.53 is a very old version and quite the number of WebDav fixes since then.

You need to test with a recent binary.

**Comment by geeklihui** [comment]
> 1.53 is a very old version and quite the number of WebDav fixes since then.
> 
> You need to test with a recent binary.

Fine. I'll try the latest version in another machine.

**Comment by geeklihui** [comment]
> 1.53 is a very old version and quite the number of WebDav fixes since then.
> 
> You need to test with a recent binary.

I tried version 1.5.8 and unfortunately, these problems still exist. I have edited the 1st floor to include the latest logs and system configuration.

**Comment by ncw** [comment]
I had a look through the log. There are several odd things in there.

Can you confirm if there really are duplicates (maybe look at the web interface)?

There were quite a few "500 internal server errors" too which indicates the server was unhappy.

**Comment by animosity22** [comment]
Closing as stale.
