### ISSUE TITLE
Potential Doc Fix for Zoho

### ISSUE THREAD

**Issue by animosity22** [rclone/rclone#6163]
Related to forum post:

https://forum.rclone.org/t/pls-help-rclone-zoho-drive-japan-region-setup-problem/30692/17

```
etexter@seraphim ~ % rclone version
rclone v1.58.1
- os/version: darwin 12.3.1 (64 bit)
- os/kernel: 21.4.0 (arm64)
- os/type: darwin
- os/arch: arm64
- go/version: go1.17.9
- go/linking: dynamic
- go/tags: cmount


```

I setup a new account as well and tested using my own client ID/password and using 127.0.0.1 for the redirect URI causes an error but localhost works.

@buengese  - I was going to do a doc fix but wanted to confirm with you as well before I did that to just update the docs. Not sure if that is a recent change for Zoho as I have never used it before.

**Comment by ncw** [comment]
Ah yes, fixing that would be a good idea.

**Comment by buengese** [comment]
I've now documented that `http://localhost:53682/` is the correct redirect url. I don't think there are any other problems here.
