### ISSUE TITLE
1fichier: Security lockout incorrectly treated as rate limit

### ISSUE THREAD

**Issue by nyuszika7h** [rclone/rclone#6165]
#### What is the problem you are having with rclone?

When 1fichier forces me to reset my password for security reasons, rclone treats it as a rate limit and keeps retrying forever.

The "No such user #93" error here is a security lockout and when I log in on the website I get "For security reasons, you must reset your password". After doing so all is well again. (This error *might* also happen if the API key is invalid or belongs to a deleted user, I haven't tried). rclone probably shouldn't keep retrying in this case as it's pretty much futile (unless you think it makes sense to retry in case the user resets their password in meantime, but that might be a long time).

#### What is your rclone version (output from `rclone version`)
```
rclone v1.58.1
- os/version: debian 11.3 (64 bit)
- os/kernel: 5.10.0-13-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.9
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Debian 11 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive and 1fichier

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
rclone sync -vv --drive-chunk-size 256M -P --transfers 4 --checkers 1 --tpslimit 0.2 td-crypt: 1fichier:
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2022/05/12 07:01:32 INFO  : Starting transaction limiter: max 0.2 transactions/s with burst 1
2022/05/12 07:01:32 DEBUG : rclone: Version "v1.58.1" starting with parameters ["rclone" "sync" "-vv" "--drive-chunk-size" "256M" "-P" "--transfers" "4" "--checkers" "1" "--tpslimit" "0.2" "--drive-service-account-file" "/root/.config/rclone/srv1.json" "td-crypt:" "1fichier:"]
2022/05/12 07:01:32 DEBUG : Creating backend with remote "td-crypt:"
2022/05/12 07:01:32 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2022/05/12 07:01:32 DEBUG : Creating backend with remote "td:Private"
2022/05/12 07:01:32 DEBUG : td: detected overridden config - adding "{CPinw}" suffix to name
2022/05/12 07:01:39 DEBUG : fs cache: renaming cache item "td:Private" to be canonical "td{CPinw}:Private"
2022/05/12 07:01:39 DEBUG : Creating backend with remote "1fichier:"
2022-05-12 07:01:42 DEBUG : pacer: low level retry 1/10 (error HTTP error 403 
(403 Forbidden) returned body: "{\"message\":\"No such user #93\",\"status\":
"KO\"}")
2022-05-12 07:01:42 DEBUG : pacer: Rate limited, increasing sleep to 5s
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:        12.3s^C
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
In general rclone retries everything, as chances are it will start working in a bit!

This can be a bit annoying when they are auth errors that you know will never work, but it doesn't usually take rclone too long to run through the 10 low level retries and the 3 high level retries before giving up.

**Comment by buengese** [comment]
The problem is that 1fichier uses http 403 for a range of error conditions including rate limiting. There is a unique error code for each failure condition in the error message which we could parse though. Maybe we should do so in the case of 1fichier to avoid excessive retries given how tight their rate limits are.

**Comment by ncw** [comment]
@buengese that is probably a good idea if the error codes are documented somewhere.

**Comment by marco-m** [comment]
In my understanding #6266, merged, means that this issue can be closed?

**Comment by ncw** [comment]
Yes this error is explicitly handled now. Thanks for the heads up. I'll close this now.
