### ISSUE TITLE
NextCloud pacer should rely on error 429 instead of preemptively self rate-limiting

### ISSUE THREAD

**Issue by devnoname120** [rclone/rclone#6166]
https://github.com/rclone/rclone/blob/5cf9b18c20550e1a9a49d3f00be87581af423873/backend/webdav/webdav.go#L443-L443

Here is the relevant documentation: https://docs.nextcloud.com/server/12/developer_manual/app/controllers.html#rate-limiting
I'm not even sure that it applies to the API at all. Maybe the API is not rate-limited ever.

Maybe if [NGINX rate-limiting](https://www.nginx.com/blog/rate-limiting-nginx/) is enabled, in which case it's likely that [error 503 will be returned](https://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req_status).

@ncw From `git blame` I can see that you implemented the WebDAV remote. Could you elaborate on why you chose these rate limits?

**Comment by ncw** [comment]
Those rate limits are general purpose rate limits for the many webdav servers rclone supports.

Not many backends can keep up with rclone without some kind of pacing except for the bucket based ones like S3, AzureBlob (but you pay for transactions there).

Can you supply a 429 response from NextCloud please? Using `-vv --dump headers` should be enough. I'd like to know what the request that caused the 429 was - knowing that it will be possible to make rclone obey the rate limits.

**Comment by ncw** [comment]
Note that rclone is already responding to 429 errors from NextCloud by backing off the next response and doing a retry.

**Comment by devnoname120** [comment]
@ncw I haven't encountered any rate-limiting with NextCloud so error 429 is a theoretical rate-limiting error that I've found in the doc. But I'm not sure that it applies to authenticated API access at all.

**Comment by devnoname120** [comment]
@ncw Can you confirm that the paver preemptively rate-limits even before receiving any rate-limiting error?

If that's the case, could you elaborate the underlying reason why it doesn't just wait for the first error before rate-limiting?

**Comment by ncw** [comment]
> @ncw Can you confirm that the pacer preemptively rate-limits even before receiving any rate-limiting error?

The rclone pacer as it is known, is set to `minSleep      = 10 * time.Millisecond` so 100 transactions per second.

So rclone won't exceed 100 transactions per second. If 423 errors are returned it will slow down.

> If that's the case, could you elaborate the underlying reason why it doesn't just wait for the first error before rate-limiting?

100/transactions per second is more than most services can cope with (with the exception of S3 and similar where you pay by the transaction). Rclone tries to be a good network citizen and not overload servers.

You can try adjusting `minSleep` and recompiling rclone to see what difference it makes.
