### ISSUE TITLE
rcloneEncryptedClientSecret lack of document

### ISSUE THREAD

**Issue by landall** [rclone/rclone#6174]
I am trying to add a new backend for baidupan.
But lack of guide in CONTRIBUTING.md about how to set rcloneEncryptedClientSecret in backend/remote/remote.go.

**Comment by animosity22** [comment]
If you post on the forums, it's easier to get help that way as this really isn't an issue.

Startup a post on the dev dicsussion for assistance.

**Comment by landall** [comment]
> If you post on the forums, it's easier to get help that way as this really isn't an issue.
> 
> Startup a post on the dev discussion for assistance.

These are different things.
The one is how I can finish the code.
The other is how to fix a bug in the document.

**Comment by animosity22** [comment]
If you start a post:

https://forum.rclone.org/

Use dev discussions, happy to fix or improve if there is a documentation update required. Forums are a great place to have that discussion.

Thanks!

**Comment by ncw** [comment]
> I am trying to add a new backend for baidupan. But lack of guide in CONTRIBUTING.md about how to set rcloneEncryptedClientSecret in backend/remote/remote.go.

Use `rclone obscure unencryptedclientsecret"
