### ISSUE TITLE
用reclone手动获取googletoken失败

### ISSUE THREAD

**Issue by HelloMusician** [rclone/rclone#6182]
#### What is the problem you are having with rclone?

Error: failed to get token: Post "https://oauth2.googleapis.com/token": dial tcp 172.217.160.106:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

#### What is your rclone version (output from `rclone version`)

V1.58.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 10, 64bit

#### Which cloud storage system are you using? (e.g. Google Drive)

Google  Team Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

Got token

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

Error: failed to get token: Post "https://oauth2.googleapis.com/token": dial tcp 142.251.42.234:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> Error: failed to get token: Post "https://oauth2.googleapis.com/token": dial tcp 142.251.42.234:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

This looks like a networking problem - what happens if you go to the URL https://oauth2.googleapis.com/token in your browser? You should get a 404 error.

**Comment by ncw** [comment]
Can you try a different VPN?

**Comment by animosity22** [comment]
Not sure there is much else to do from a rclone perspective here as it's not a bug.

You need to adjust/fix your VPN so you have proper connectivity out. If the VPN doesn't work, you can try a proxy server as well:

https://rclone.org/faq/#can-i-use-rclone-with-an-http-proxy

Other than that, if you can't hit the oAuth page, you most likely won't be able use the API either. Any questions, please ask on the forums.

**Comment by HelloMusician** [comment]
Thank you very much boss, I'll check it out.

Best regards,

Animosity ***@***.***> 于 2022年5月20日周五 08:19写道：

**Comment by bruce2233** [comment]
Same error. I can access www.google.com but not oauth
