### ISSUE TITLE
readability

### ISSUE THREAD

**Issue by C0deGyver** [rclone/rclone#6187]
#### Output of `rclone version`
rclone v1.58.1
- os/version: Microsoft Windows 10 Pro 21H2 (64 bit)
- os/kernel: 10.0.19044.1706 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.17.9
- go/linking: dynamic
- go/tags: cmount

#### Describe the issue
When running rclone config it is difficult to tell where one setting starts and another begins. It would be more readable if one or more blank lines were between "sections" (see example below). I know not everyone may feel this way... I am dyslexic so having no spacing around sections of text makes it very difficult to read and tell where I am.

I LOVE this utility and really appreciate the hard work that has gone into creating it!

example:
```
>rclone.exe config
2022/05/20 09:19:45 NOTICE: Config file "C:\\Users\\<user>\\AppData\\Roaming\\rclone\\rclone.conf" not found - using defaults
No remotes found, make a new one?
n) New remote
s) Set configuration password
q) Quit config
n/s/q> n
name> test
    
Option Storage.
Type of storage to configure.
Choose a number from below, or type in your own value.
 1 / 1Fichier
   \ (fichier)
 2 / Akamai NetStorage
   \ (netstorage)
 3 / Alias for an existing remote
   \ (alias)
```

**Comment by ncw** [comment]
So would you prefer it to look like this?

```
 1 / 1Fichier
   \ (fichier)

 2 / Akamai NetStorage
   \ (netstorage)

 3 / Alias for an existing remote
   \ (alias)
```

I made the different section different colours to make them easier to see a while back.

Maybe

```
 1 / 1Fichier
   \ (fichier)
-----------------------------------
 2 / Akamai NetStorage
   \ (netstorage)
-----------------------------------
 3 / Alias for an existing remote
   \ (alias)
```

I did a prototype where you pressed up and down to choose the one you want from a scrolling menu which was cute, but I'm not sure it is the way to go either.

**Comment by albertony** [comment]
With "section", do you mean the individual numbered list entries of multiple choice options, or the information related to individual configuration parameters, or both?

Some versions ago I made the config output a bit more condensed than before. I found it confusing when there was empty lines within the description of a parameter, it was easy to misread which parameter the information lines related to.

E.g. in older versions:

```
Files bigger than this can be resumed if the upload fail's.
Enter a size with suffix k,M,G,T. Press Enter for the default ("10M").
upload_resume_limit>
This sets the encoding for the backend.

See: the [encoding section in the overview](/overview/#encoding) for more info.
Enter a encoder.MultiEncoder value. Press Enter for the default ("Slash,LtGt,DoubleQuote,Colon,Question,Asterisk,Pipe,Del,Ctl,InvalidUtf8,Dot").
encoding>
```

While I changed it so that in newer versions the empty lines are removed:

```
Files bigger than this can be resumed if the upload fail's.
Enter a size with suffix k,M,G,T. Press Enter for the default ("10M").
upload_resume_limit>
This sets the encoding for the backend.
See: the [encoding section in the overview](/overview/#encoding) for more info.
Enter a encoder.MultiEncoder value. Press Enter for the default ("Slash,LtGt,DoubleQuote,Colon,Question,Asterisk,Pipe,Del,Ctl,InvalidUtf8,Dot").
encoding>
```

Now perhaps a next step should be to add more space (or a separator) **between** the config parameter sections:
```
Files bigger than this can be resumed if the upload fail's.
Enter a size with suffix k,M,G,T. Press Enter for the default ("10M").
upload_resume_limit>

This sets the encoding for the backend.
See: the [encoding section in the overview](/overview/#encoding) for more info.
Enter a encoder.MultiEncoder value. Press Enter for the default ("Slash,LtGt,DoubleQuote,Colon,Question,Asterisk,Pipe,Del,Ctl,InvalidUtf8,Dot").
encoding>
```

**Comment by KaspianDev** [comment]
> So would you prefer it to look like this?
> 
> ```
>  1 / 1Fichier
>    \ (fichier)
> 
>  2 / Akamai NetStorage
>    \ (netstorage)
> 
>  3 / Alias for an existing remote
>    \ (alias)
> ```
> 
> I made the different section different colours to make them easier to see a while back.
> 
> Maybe
> 
> ```
>  1 / 1Fichier
>    \ (fichier)
> -----------------------------------
>  2 / Akamai NetStorage
>    \ (netstorage)
> -----------------------------------
>  3 / Alias for an existing remote
>    \ (alias)
> ```
> 
> I did a prototype where you pressed up and down to choose the one you want from a scrolling menu which was cute, but I'm not sure it is the way to go either.

I would prefer the second option but with just `|` character instead of `\ /`, they look weird to me.

**Comment by C0deGyver** [comment]
> With "section", do you mean the individual numbered list entries of multiple choice options, or the information related to individual configuration parameters, or both?
> 
> Some versions ago I made the config output a bit more condensed than before. I found it confusing when there was empty lines within the description of a parameter, it was easy to misread which parameter the information lines related to.
> 
> E.g. in older versions:
> 
> ```
> Files bigger than this can be resumed if the upload fail's.
> Enter a size with suffix k,M,G,T. Press Enter for the default ("10M").
> upload_resume_limit>
> This sets the encoding for the backend.
> 
> See: the [encoding section in the overview](/overview/#encoding) for more info.
> Enter a encoder.MultiEncoder value. Press Enter for the default ("Slash,LtGt,DoubleQuote,Colon,Question,Asterisk,Pipe,Del,Ctl,InvalidUtf8,Dot").
> encoding>
> ```
> 
> While I changed it so that in newer versions the empty lines are removed:
> 
> ```
> Files bigger than this can be resumed if the upload fail's.
> Enter a size with suffix k,M,G,T. Press Enter for the default ("10M").
> upload_resume_limit>
> This sets the encoding for the backend.
> See: the [encoding section in the overview](/overview/#encoding) for more info.
> Enter a encoder.MultiEncoder value. Press Enter for the default ("Slash,LtGt,DoubleQuote,Colon,Question,Asterisk,Pipe,Del,Ctl,InvalidUtf8,Dot").
> encoding>
> ```
> 
> Now perhaps a next step should be to add more space (or a separator) **between** the config parameter sections:
> 
> ```
> Files bigger than this can be resumed if the upload fail's.
> Enter a size with suffix k,M,G,T. Press Enter for the default ("10M").
> upload_resume_limit>
> 
> This sets the encoding for the backend.
> See: the [encoding section in the overview](/overview/#encoding) for more info.
> Enter a encoder.MultiEncoder value. Press Enter for the default ("Slash,LtGt,DoubleQuote,Colon,Question,Asterisk,Pipe,Del,Ctl,InvalidUtf8,Dot").
> encoding>
> ```

Of the three replies (wow) I think you were the closest to what I was talking about. I will give another example below (longer this time so it is more obvious :). Also using the separator you and the others seem to like. Either symbol or blank line would make it easier. Just want/need something to break what I am calling sections up. Thank you all for the speedy reply and understanding.

`Option client_id.
OAuth Client Id.
Leave blank normally.
Enter a value. Press Enter to leave empty.
client_id>
---------------------------------------
Option client_secret.
OAuth Client Secret.
Leave blank normally.
Enter a value. Press Enter to leave empty.
client_secret>
---------------------------------------
Option region.
Choose national cloud region for OneDrive.
Choose a number from below, or type in your own string value.
Press Enter for the default (global).
 1 / Microsoft Cloud Global
   \ (global)
 2 / Microsoft Cloud for US Government
   \ (us)
 3 / Microsoft Cloud Germany
   \ (de)
 4 / Azure and Office 365 operated by 21Vianet in China
   \ (cn)
region>
---------------------------------------
Edit advanced config?
y) Yes
n) No (default)
y/n>`

**Comment by albertony** [comment]
I now have a pull request for improving readability by (mainly) adding newlines between "sections".

My PR does *not* do anything with the multiple choice listing. I, personally, find the existing `\`, `|`, `/` format together with colorization to be quite nice. The suggestion to add `------` lines as separators between choices will be a bit too verbose and "noisy", and stand too much out from the rest of the config ui output, in my opinion... 🤔 I think.... 😂

**Comment by albertony** [comment]
Merged the mentioned PR. @C0deGyver can decide if you think it closes this issue or not... The changes will be included in next [beta](https://beta.rclone.org/) if you want to take a look.

**Comment by C0deGyver** [comment]
yes it does. THANK YOU :)
