### ISSUE TITLE
Restic Compression

### ISSUE THREAD

**Issue by guayadeque** [rclone/rclone#6194]
Hello,

Recently restic has implemented in its master branch "compression" through:
* restic init --repository-version 2
* restic backup --compression (auto|max|off) --cignore "*.zip"

Source:
* https://forum.restic.net/t/compression-support-has-landed-in-master/4997

Could rclone's restic integration include such options?
Thanks in advance.

**Comment by ncw** [comment]
Do we need to do something to rclone's restic rest server to enable respository version 2? @fd0 ?

**Comment by fd0** [comment]
No need to do anything, we didn't touch the backend interface at all. rclone should be completely agnostic to whether or not compression is enabled. I've just merged [the second PR](https://github.com/restic/restic/pull/3704) which makes repo version v2 the default (so it's not necessary to pass `--repository-version 2` to `restic init` any more).

I'm not sure what `--cignore` means though. What does it mean to for rclone's restic integration to "include such options"?

**Comment by ncw** [comment]
@fd0 wrote
> No need to do anything, we didn't touch the backend interface at all. rclone should be completely agnostic to whether or not compression is enabled. I've just merged [the second PR](https://github.com/restic/restic/pull/3704) which makes repo version v2 the default (so it's not necessary to pass `--repository-version 2` to `restic init` any more).

Great news - thank you.

**Comment by iogrt** [comment]
Stumbled upon this, if Rclone is agnostic, shouldn't the issue be closed?

**Comment by ncw** [comment]
Good idea!
