### ISSUE TITLE
Support for Qiniu object storage

### ISSUE THREAD

**Issue by bachue** [rclone/rclone#6195]
[Qiniu Cloud Storage](https://www.qiniu.com/en/products/kodo) is a popular cloud object storage service in China. User can easily use the similar configuration, to make Qiniu worked with rclone. I'm an employee from Qiniu company, can I contribute a PR to add Qiniu as a new backend? Thanks.

**Comment by animosity22** [comment]
Check out:

https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#writing-a-new-backend

You can always submit a PR.

**Comment by ncw** [comment]
@bachue it looks like Qinu is S3 compatible so what is needed is a Provider for S3. These aren't very difficult to write - here is an example of one I did for Cloudflare R2 recently 6f91198b579b73bed141e079ce4f95c7ec9712d5

**Comment by bachue** [comment]
@ncw Actually we had a discussion in our team about this before I filed this issue, the team prefers Qiniu native API for more powerful features.

**Comment by ncw** [comment]
No reason why we couldn't have both. I'd suggest doing an S3 integration which will be easy, then doing a backend which won't!
