### ISSUE TITLE
onedrive backend - support client credentials grant

### ISSUE THREAD

**Issue by gursharan001** [rclone/rclone#6197]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/onedrive-backend-client-credentials-grant/30885

#### What is your current rclone version (output from `rclone version`)?
rclone v1.58.0
- os/version: Microsoft Windows 10 Pro 21H2 (64 bit)
- os/kernel: 10.0.19044.1645 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.17.8
- go/linking: dynamic
- go/tags: cmount

#### What problem are you are trying to solve?
Automatically include onedrive/sharepoint document libraries into rclone sync without requiring human intervention to obtain access tokens

#### How do you think rclone should be changed to solve that?
[onedrive backend](https://github.com/rclone/rclone/blob/master/backend/onedrive/onedrive.go) can be modified to support client credential grant - https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Do you want to work on this @gursharan001 ?

I think this needs to be part of the config flow when running `rclone config`.

I think https://github.com/rclone/rclone/blob/master/lib/oauthutil/oauthutil.go could be modified fairly easily to do what you need.

**Comment by gursharan001** [comment]
Thank you for the pointer. I will attempt it this weekend.

**Comment by gursharan001** [comment]
clientcredentials has a separate package which defines it's own config type - https://pkg.go.dev/golang.org/x/oauth2/clientcredentials#Config 

We might have to introduce a flag in rclone config to indicate this. what do you think?

**Comment by ncw** [comment]
> clientcredentials has a separate package which defines it's own config type - https://pkg.go.dev/golang.org/x/oauth2/clientcredentials#Config

Looks annoyingly similar, but different :-(

> We might have to introduce a flag in rclone config to indicate this.

> We will also have to change rest of the code in [oauthutil.go](https://github.com/rclone/rclone/blob/master/lib/oauthutil/oauthutil.go) to create and use the right config

We need not to break the code in oauthutil as it isn't well covered by tests (and by its nature integration tests are very hard).

I'd be tempted to make a copy of oauthutils say oauthutils/clientcredentials, make it work, then we can look afterwards whether we can factor out the common functionality (like the oauth webserver) afterwards when we see what it looks like.

> I also wanted to ask - How to test oauthutil.go ?

We don't have integration tests or unit tests for this... So its hard, especially with the number of providers rclone supports.

**Comment by chscott** [comment]
I think the work for Azure Blob should work for OneDrive as well. Maybe you can get all or most of this for free?

https://github.com/rclone/rclone/issues/3230

**Comment by gursharan001** [comment]
My apologies for disappearing. @martin-redmaple, please let me know if you plan to fix the conflicts with your PR. Otherwise I will start a new PR to resolve this. 

Many Thanks.

**Comment by martin-redmaple** [comment]
@gursharan001  - done. Conflicts now resolved.

**Comment by gursharan001** [comment]
Thank you @martin-redmaple . I will also test both configurations and report soon.

**Comment by elovelan** [comment]
@gursharan001, have you had a chance to work on this? If you don't think you will, I'd be happy to take it over, though I didn't see anything on your fork yet.

**Comment by gursharan001** [comment]
Hi @elovelan , you may go ahead with this.

Cheers.

**Comment by elovelan** [comment]
> Hi @elovelan , you may go ahead with this.
> 
> Cheers.

Great @gursharan001, do you have any code I can start from? If not, I'm happy to just follow what was done for Azure Blob storage.

**Comment by gursharan001** [comment]
> > Hi @elovelan , you may go ahead with this.
> > 
> > Cheers.
> 
> Great @gursharan001, do you have any code I can start from? If not, I'm happy to just follow what was done for Azure Blob storage.

@elovelan , not really. Please start as you see fit.

**Comment by danfoxley** [comment]
At the risk of not following guidlines of posting, I think this is relevant to post. It describes OAuth2.0 as a [Microsoft Graph App-only access (access without a user)](https://learn.microsoft.com/en-us/graph/auth/auth-concepts#app-only-access-access-without-a-user)

This same is covered here [Microsoft identity platform and the OAuth 2.0 client credentials flow](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-client-creds-grant-flow) is described here as well.

[Get access without a user](https://learn.microsoft.com/en-us/graph/auth-v2-service?tabs=http) link from 
[Application permissions](https://learn.microsoft.com/en-us/graph/permissions-overview?tabs=http#application-permissions)

**Comment by ncw** [comment]
I've merged @martin-redmaple 's fix for this which I rebased and fixed up to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.69

Please test :-)

Here are the instructions from the new onedrive docs. Please send corrections here or as another PR.

### Using OAuth Client Credential flow

OAuth Client Credential flow will allow rclone to use permissions
directly associated with the Azure AD Enterprise application, rather
that adopting the context of an Azure AD user account.

This flow can be enabled by following the steps below:

1. Create the Enterprise App registration in the Azure AD portal and obtain a Client ID and Client Secret as described above.
2. Ensure that the application has the appropriate permissions and they are assigned as *Application Permissions*
3. Configure the remote, ensuring that *Client ID* and *Client Secret* are entered correctly.
4. In the *Advanced Config* section, enter `true` for `client_credentials` and in the `tenant` section enter the tenant ID.

When it comes to choosing the type of the connection work with the
client credentials flow. In particular the "onedrive" option does not
work. You can use the "sharepoint" option or if that does not find the
correct drive ID type it in manually with the "driveid" option.

**NOTE** Assigning permissions directly to the application means that
anyone with the *Client ID* and *Client Secret* can access your
OneDrive files. Take care to safeguard these credentials.

**Comment by danfoxley** [comment]
@ncw In working to test this new fucntionality

1. I can't tell if this issue is on my end or `rclcone config` not parsing the URL inputed correctly.

Entered during `rclone config`
![image](https://github.com/user-attachments/assets/9f4780ec-3848-4236-9bb4-926abd5465e7)

Error
![image](https://github.com/user-attachments/assets/e4c78e86-0f2a-4f98-85c3-8b428b88411c)

2. For this can you please confirm I can/should leave it blank?
`
Option token.
OAuth Access Token as a JSON blob.
Enter a value. Press Enter to leave empty.
token>
`

**Comment by ncw** [comment]
You should need to set any of those options. Auth URL, token URL, redirect URL etc all have defaults which should work.

**Comment by danfoxley** [comment]
@ncw Thanks, I was able to connect. 

**Q:** Should I have expected my browser to open to http://localhost:53682 (and complete OAuth), it did not and I was able to browse my SharePoint site by just completing the steps I show below?  I was expecting (incorrectly?) something similar to as shown here [Entra app consent.](https://learn.microsoft.com/en-us/entra/identity-platform/application-consent-experience)



**Steps to configure rclone to list SharePoint Document Libraries**

```
rclone config
(List of only items I changed, rest hit _enter_)

Storage> 35
client_id> FromEntraApplicationRegistration
client_secret> FromEntraApplicationRegistration
region> 1
tenant> FromEntraApplicationRegistration

Edit advanced config?
y) Yes
n) No (default)
y/n> y

     client_credentials> true
    
     (List of only items I changed, rest hit _enter_)

     Edit advanced config?
     y/n> n

2024/12/19 23:08:33 NOTICE: Make sure your Redirect URL is set to "http://localhost:53682/" in your custom config.

Option config_type.
config_type> 3  (entered SharePoint URL and selected documentlibrary listed, after complete, was able to "rclone lsd configname:"
```

**For config_type**
> When it comes to choosing the type of the connection work with the
> client credentials flow. In particular the "onedrive" option does not
> work. You can use the "sharepoint" option or if that does not find the
> correct drive ID type it in manually with the "driveid" option.

I selected config_type 3 (url) and used a url to match the example.



**Screenshots**
Entra App
![image](https://github.com/user-attachments/assets/51f5ef36-6882-495e-a50f-035e3314aadb)

API
(not sure these are at all correct, they are Applicaiton instead of Delegated, but I'm sure further permissions should be sorted out)
![image](https://github.com/user-attachments/assets/e18b0703-220d-440c-8b60-cb8e12b8a6f1)

**Comment by ncw** [comment]
@danfoxley wrote 
> Thanks, I was able to connect.

Great 

> 
> **Q:** Should I have expected my browser to open to http://localhost:53682 (and complete OAuth), it did not and I was able to browse my SharePoint site by just completing the steps I show below? I was expecting (incorrectly?) something similar to as shown here [Entra app consent.](https://learn.microsoft.com/en-us/entra/identity-platform/application-consent-experience)

The browser step isn't needed for client credentials flow.

> **Steps to configure rclone to list SharePoint Document Libraries**
> 
> ```
> rclone config
> (List of only items I changed, rest hit _enter_)
> 
> Storage> 35
> client_id> FromEntraApplicationRegistration
> client_secret> FromEntraApplicationRegistration
> region> 1
> tenant> FromEntraApplicationRegistration
> 
> Edit advanced config?
> y) Yes
> n) No (default)
> y/n> y
> 
>      client_credentials> true
>     
>      (List of only items I changed, rest hit _enter_)
> 
>      Edit advanced config?
>      y/n> n
> 
> 2024/12/19 23:08:33 NOTICE: Make sure your Redirect URL is set to "http://localhost:53682/" in your custom config.

The redirect URL isn't used for client credentials flow so I should probably remove that!

> 
> Option config_type.
> config_type> 3  (entered SharePoint URL and selected documentlibrary listed, after complete, was able to "rclone lsd configname:"
> ```

Great

> **For config_type**
> 
> > When it comes to choosing the type of the connection work with the
> > client credentials flow. In particular the "onedrive" option does not
> > work. You can use the "sharepoint" option or if that does not find the
> > correct drive ID type it in manually with the "driveid" option.
> 
> I selected config_type 3 (url) and used a url to match the example.

We should probably put that in the docs. What does the URL look like?
> 
> **Screenshots** Entra App ![image](https://private-user-images.githubusercontent.com/2074038/397649272-51f5ef36-6882-495e-a50f-035e3314aadb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0ODc0OTIsIm5iZiI6MTczNTQ4NzE5MiwicGF0aCI6Ii8yMDc0MDM4LzM5NzY0OTI3Mi01MWY1ZWYzNi02ODgyLTQ5NWUtYTUwZi0wMzVlMzMxNGFhZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjlUMTU0NjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQyM2E4ZWRjNGQ2NmVjMjk2YjVkMDRhOWYyNmEwMjBkYjg0NzQ0ZGYzN2FmMjgxYWNkYmI4MDNhMGE3ODg0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.p6bGEQ7vlqbS-7_GXDWxd0PoyDx5cNCEA9is8H89WMw)
> 
> API (not sure these are at all correct, they are Applicaiton instead of Delegated, but I'm sure further permissions should be sorted out) ![image](https://private-user-images.githubusercontent.com/2074038/397649944-e18b0703-220d-440c-8b60-cb8e12b8a6f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0ODc0OTIsIm5iZiI6MTczNTQ4NzE5MiwicGF0aCI6Ii8yMDc0MDM4LzM5NzY0OTk0NC1lMThiMDcwMy0yMjBkLTQ0MGMtOGI2MC1jYjhlMTJiOGE2ZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjlUMTU0NjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTVmNzRmNzYzZTI4Y2FhNzQ0MGU5Y2JmY2M4ZmM4ZDk5NThlMDA2ZmJjY2E3MmI4NmRiYTFiMTI5MjNlMjM5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.n2ttj58I87XisP4jlWu0yev0EtR1y68YKO5vAioSmhE)

You probably know more about this than I do - I don't know very much about the permissions needed so any corrections gratefully received!

**Comment by martin-redmaple** [comment]
Hopefully some helpful info on a couple of the queries above...

>> For config_type
>>  
>>> When it comes to choosing the type of the connection work with the
>>> client credentials flow. In particular the "onedrive" option does not
>>> work. You can use the "sharepoint" option or if that does not find the
>>> correct drive ID type it in manually with the "driveid" option.
>>
>> I selected config_type 3 (url) and used a url to match the example.
>
> We should probably put that in the docs. What does the URL look like?

The "onedrive" option will not work as this attempts to use the `/me/drives` path, however when using the client credential flow rclone operates in the context of the app, therefore me (i.e. a specific user) is not available. 

For config_type, selecting option `2 - Root Sharepoint site` should work - this will use the sharepoint site at the root of your Sharepoint subdomain (i.e. `https://<tenant_name>.sharepoint.com`) and should then present a list of the document libraries within the site.

For option `3 - Sharepoint site name or URL` you should be able to use the URLs in the format of the examples
```
- "mysite"
- "https://XXX.sharepoint.com/sites/mysite"
- "https://XXX.sharepoint.com/teams/ID"
```
For example, I can access one of my sites by entering `Retail` or `https://<tenant_name>.sharepoint.com/sites/Retail`. This then lists the site document libraries for selection.

For option `4 - Search for a Sharepoint Site` you should be able to search for a sharepoint site by name (or part of name) rather than knowing the full name/URL.

For options `5 - Type in driveID (advanced)` and `6 - Type in SiteID (advanced)` these essentially skip the steps above that attempt to determine these values by looking up based on a site name. I know these are available by poking GraphAPI directly, but not sure of an easier way to find these values directly.

>> Screenshots Entra App image
>>
>>API (not sure these are at all correct, they are Applicaiton instead of Delegated, but I'm sure further permissions should be sorted out) image
>
> You probably know more about this than I do - I don't know very much about the permissions needed so any corrections gratefully received!

The following permissions are required on the app registration (note - as we use Graph API to access the M365 tenant, these are all permissions within the *Microsoft Graph* permission set, **not** permissions from the *Sharepoint* set of permissions.

![image](https://github.com/user-attachments/assets/640d135a-270f-4c0f-9e23-db74e1f3152d)

Obviously could swap `Files.ReadWrite.All` for `Files.Read.All` to just give read only access. `Sites.Read.All` is required to be able to lookup Site/Drive IDs by site name, so is required for most of the `config_type` options above to work correctly.

NOTE - assigning the permissions above to the application will allow access to **all** sharepoint sites within a tenant so should be used with caution. If only specific site access is required, then the *Sites Selected* approach described in [this page](https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins-modernize/understanding-rsc-for-msgraph-and-sharepoint-online) can be used to limit access to s subset of sites (I have used this for other applications, but not tested with rclone)

**Comment by danfoxley** [comment]
@ncw 

> 

> > For config_type
> > When it comes to choosing the type of the connection work with the
> > client credentials flow. In particular the "onedrive" option does not
> > work. You can use the "sharepoint" option or if that does not find the
> > correct drive ID type it in manually with the "driveid" option.
> > I selected config_type 3 (url) and used a url to match the example.

> We should probably put that in the docs. **What does the URL look like?**

@martin-redmaple  Covered this, after my post, but, what rclone has in the interactive config worked for me.

`- "https://XXX.sharepoint.com/sites/mysite"`

**Comment by danfoxley** [comment]
> NOTE - assigning the permissions above to the application will allow access to **all** sharepoint sites within a tenant so should be used with caution. If only specific site access is required, then the _Sites Selected_ approach described in [this page](https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins-modernize/understanding-rsc-for-msgraph-and-sharepoint-online) can be used to limit access to s subset of sites (I have used this for other applications, but not tested with rclone)

@martin-redmaple Thanks for the added details.

To summarize my efforts in testing with Client Credentials and using RSC to configure site specific access (which all seem to be working).

### RCLone Config

```
(If not listed selected default (I hit enter)
rclone config
Storage> 35
client_id> FromEntraAppRegistration
client_secret> FromEntraAppRegistration
tenant> FromEntraAppRegistration

Edit advanced config?
y/n> y
client_credentials> true

Edit advanced config?
 y/n> n
config_type> 3  
config_site_url> https://XXX.sharepoint.com/sites/mysite

config_driveid> SelectDocumentLibrary
Drive OK?
y/n> Yes
Keep this "CONFIGNAME" remote?
y/e/d> Yes
Current remotes:
e/n/d/r/c/s/q> q

#Test
rclone lsd RCloneConfigName:
```

**Create and configure App Registration w/Resource Specific Consent**

a.k.a locked down App Registration to a single SharePoint site, vs. allowing access to all sites, as @martin-redmaple [explained](https://github.com/rclone/rclone/issues/6197#issuecomment-2567952596).

**In Entra ID - portal.azure.com**

App registration > New registration (single tenant)
**Note:** No other options requried to create App Registration.

**In newly created App Registration:**

Overview
_Application (client) ID_ (get for `rclone config`)
_Directory (tenant) ID_ (get for `rclone config`)

Certificates & Secrets > New client secret:
Create then get _Value from Client secrets_ (get for `rclone config`)
 
API Permissions
Add a permission > Microsoft Graph > Application permissions:
Sites.Selected
Select > Grant admin consent for .....

**Resource Specific Consent using MS Graph**
Oddly, my GlobalAdmin was having issues using MS Graph, but the SharePoint site user was able to apply these MS Graph permissions.

Use MS Graph - Get SharePoint SiteID
https://developer.microsoft.com/en-us/graph/graph-explorer

GET
https://graph.microsoft.com/v1.0/sites/mytenantdomaincom.sharepoint.com:/sites/mysitename

In MS Graph response get `id` 
"id": "mytenantdomaincom.sharepoint.com,somelongguidfrommsgraph"

In MS Graph assign permission
POST
https://graph.microsoft.com/v1.0/sites/mytenantdomaincom.sharepoint.com,somelongguidfrommsgraph/permissions

Request Body
```
{
  "roles": ["write"],
  "grantedToIdentities": [
    {
      "application": {
        "id": "Application (client) ID",
        "displayName": "Some Friendly Name"
      }
    }
  ]
}     
```
