### ISSUE TITLE
--fast-list for specified subfolder

### ISSUE THREAD

**Issue by TanukiAI** [rclone/rclone#6203]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/fast-list-on-subfolder-only/31001

#### What is your current rclone version (output from `rclone version`)?
rclone v1.58.1
- os/version: Microsoft Windows 10 Home 21H2 (64 bit)
- os/kernel: 10.0.19044.1706 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.17.9
- go/linking: dynamic
- go/tags: cmount

#### What problem are you are trying to solve?
Getting a --fast-list from the specified subfolder instead of the folder in the config.

My source folder is a folder with 10 shortcuts and I only need a fast-list of one of the shortcuts.
The problem is that it does a fast-list of all Shortcuts and this takes atleast 10 minutes and has 403 errors sometimes.

#### How do you think rclone should be changed to solve that?
Either adding a --fast-list-subfolder or changing --fast-list to the subfolder.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
It doesn't actually looking at your post and log.

The issue relates back to a Google Drive bug with recursive lists.

Issue marked won't fix from Google:

https://issuetracker.google.com/issues/149522397

So not much to do here. Closing out..
