### ISSUE TITLE
google team drive can upload, but cant download 

### ISSUE THREAD

**Issue by Eloco** [rclone/rclone#6214]
#### What is the problem you are having with rclone?

google team drive can upload, but cant download 

#### What is your rclone version (output from `rclone version`)

rclone v1.58.1
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.4.10-050410-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.9
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

ubuntu 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Drive team drives

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone -vv  mount googo:/ /home/xxx/rclone/google --allow-non-empty

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

i try both  my own client (id && secret) and the default client (id && secret)
```
2022/06/04 13:00:03 DEBUG : session_update.py: ChunkedReader.openRange at 0 length 134217728
2022/06/04 13:00:04 DEBUG : &{session_update.py (r)}: >Read: read=0, err=open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
2022/06/04 13:00:04 DEBUG : &{session_update.py (r)}: Read: len=4096, offset=0
2022/06/04 13:00:04 DEBUG : session_update.py: ChunkedReader.openRange at 0 length 134217728
2022/06/04 13:00:05 DEBUG : &{session_update.py (r)}: >Read: read=0, err=open file failed: googleapi: Error 403: The download quota for this file has been exceeded., downloadQuotaExceeded
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
The error is

>   The download quota for this file has been exceeded., downloadQuotaExceeded

That means that file has been downloaded too much.

If you want to know more please ask in [post on the rclone forum](https://forum.rclone.org/) about this

Thanks
