### ISSUE TITLE
Rclone mount fails to interact with file with not allowed characters in the filename

### ISSUE THREAD

**Issue by Masamune3210** [rclone/rclone#6216]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/rclone-mount-fails-to-interact-with-file-with-not-allowed-characters-in-the-filename/31068

#### What is the problem you are having with rclone?

Per the conversation on the forum, rclone currently fails to convert colons to a allowed character when using a mount with vfs caching enabled

#### What is your rclone version (output from `rclone version`)

rclone v1.57.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

os/version: Microsoft Windows 10 Pro 2009 (64 bit)
os/kernel: 10.0.22000.675 (x86_64)
os/type: windows
os/arch: amd64
go/version: go1.17.2
go/linking: dynamic
go/tags: cmount

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone mount "tknkstash:" V: -vvvvvvvv --vfs-cache-mode full --vfs-read-chunk-size 200M --vfs-cache-max-age 30m --vfs-cache-poll-interval 35m --volname 'The Archive' --attr-timeout 1h --drive-skip-gdocs --drive-skip-shortcuts --dir-cache-time 5h --cache-dir 'E:\rclone' --rc --rc-web-gui --rc-user=admin --rc-pass=admin --transfers 2 --order-by 'size,ascending'

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

https://gist.github.com/Masamune3210/32c31567d7c1a7296988f029200b616b

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Masamune3210** [comment]
Seems to be working, tried copying a file that caused a I/O error when trying to move a file to the mount with 1.57 to the mount after updating to 1.58.1 and it copied just fine!

**Comment by ncw** [comment]
Great. I should have got you to try the latest version sooner! I'll close this now.
