### ISSUE TITLE
Sugarsync support

### ISSUE THREAD

**Issue by Magissia** [rclone/rclone#622]
Hello,
it would be helpful to have sugarsync support.
https://www.sugarsync.com/developer

**Comment by ncw** [comment]
Nice idea.  Can anyone get me a free account?  I'd need one that doesn't stop working after 30 days as rclone is continuously tested.

**Comment by 4rsfed** [comment]
> Nice idea. Can anyone get me a free account? I'd need one that doesn't stop working after 30 days as rclone is continuously tested.

Yes I can provide this for you. We'd love to get rclone setup to support SugarSync.

Rob
Product Manager at SugarSync

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org) in 15-30 mins and released in v1.51

The instructions can be found here before they make it to the website: https://github.com/rclone/rclone/blob/master/docs/content/sugarsync.md

Any testing much appreciated :-)
