### ISSUE TITLE
ftp: Improve performance of --files-from-raw

### ISSUE THREAD

**Issue by panthony** [rclone/rclone#6225]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/ftp-does-not-play-well-with-files-from/31158

#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.59.0-beta.5996.3a89ee1bb
- os/version: darwin 11.5.2 (64 bit)
- os/kernel: 20.6.0 (x86_64)
- os/type: darwin
- os/arch: amd64
- go/version: go1.16.2
- go/linking: dynamic
- go/tags: none
```

#### What problem are you are trying to solve?

Rclone calls `NewObject` which in turn calls `FindItem` which in turn calls `List` on the parent directory for every single file of `--files-from-raw` which does not scale at all.

The idea is to provide a more efficient way when supported by the remote FTP server.

#### How do you think rclone should be changed to solve that?

Use a more efficient method when supported by the remote server to retrieve an item by using `MLST` command.

I'd argue that keeping the original behavior (based on List) might be unwanted and it could be useful to forbid it as an opt-in.

PR provided here: https://github.com/jlaffaye/ftp/pull/258 (or https://github.com/rclone/ftp/pull/1)

An exemple of implementation could be:

```go
// findItem finds a directory entry for the name in its parent directory
func (f *Fs) findItem(ctx context.Context, remote string) (entry *ftp.Entry, err error) {
	// defer fs.Trace(remote, "")("o=%v, err=%v", &o, &err)
	fullPath := path.Join(f.root, remote)
	if fullPath == "" || fullPath == "." || fullPath == "/" {
		// if root, assume exists and synthesize an entry
		return &ftp.Entry{
			Name: "",
			Type: ftp.EntryTypeFolder,
			Time: time.Now(),
		}, nil
	}

	c, err := f.getFtpConnection(ctx)
	if err != nil {
		return nil, fmt.Errorf("findItem: %w", err)
	}

	entry, err = c.Stat(fullPath)
	f.putFtpConnection(&c, err)

	if err != nil {
		return nil, translateErrorFile(err)
	}

	if entry != nil {
		f.entryToStandard(entry)
	}

	return entry, nil
}
```

In this context the original behavior was dropped.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by panthony** [comment]
It was the intent of this PR:

https://github.com/rclone/rclone/pull/6453

**Comment by ncw** [comment]
Just found that - thanks! Will try running the tests locally in a moment.

**Comment by ncw** [comment]
I've figured out the problems - please see the PR!
