### ISSUE TITLE
windows rclone with --no-console key, default Windows Terminal

### ISSUE THREAD

**Issue by eugenov** [rclone/rclone#6230]
#### What is the problem you are having with rclone?
When mounting with `--no-console` option, default terminal matters. If conhost is default - `--no-console` works well. If Windows Terminal - `--no-console` has no effect.

rclone v1.58.1
- os/version: Microsoft Windows 11 Pro 21H2 (64 bit)
- os/kernel: 10.0.22000.708 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.17.9
- go/linking: dynamic
- go/tags: cmount

#### Which cloud storage system are you using? (e.g. Google Drive)

SFTP

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
start %USERPROFILE%\rclone\rclone.exe --config %USERPROFILE%\rclone\rclone.conf --log-file %USERPROFILE%\rclone\logs\host.txt --cache-dir . --temp-dir . mount "host:/" "%USERPROFILE%\mounts\host" --vfs-cache-mode full --no-console

**Comment by ncw** [comment]
> If Windows Terminal - `--no-console` has no effect.

Do you mean that the terminal window still appears?

Here is the code which hides the console on Windows

https://github.com/rclone/rclone/blob/5db9a2f8313ce240daf0a1b2fa8c5337bc291c9d/lib/terminal/hidden_windows.go#L11-L20

This was by @albertony - who maybe has an idea?

**Comment by albertony** [comment]
Seems this is a known issue just recently fixed, released as Windows Terminal Preview v1.14.143 (24 May 2022).

See https://github.com/microsoft/terminal/issues/12570.

I have not tested that preview version myself, so don't know if / how well it works, yet..

**Comment by eugenov** [comment]
> fixed, released as Windows Terminal Preview v1.14.143 (24 May 2022).

Tested with 1.14.1452

> Do you mean that the terminal window still appears?

That's right

**Comment by eugenov** [comment]
Just MS Store version "Windows Terminal Preview", that easy. Version from 19th of May.
![image](https://user-images.githubusercontent.com/61651148/172839820-90d7a051-c480-4c27-9ae5-861fb3cbc909.png)

**Comment by albertony** [comment]
> Ooops, version from 19th of May 2020 :)

That was confusing, luckily you noticed the date so quickly 😌

**Comment by albertony** [comment]
Windows Terminal just released version 1.14.186 (1.14.1861.0) with fix for the mentioned issue:
> Console application windowing will now work more consistently within Terminal: when an application requests that it be hidden or minimized, we will minimize the associated terminal window.

(https://github.com/microsoft/terminal/releases/tag/v1.14.1861.0)

I just tested it with rclone's `--no-console`, and this now works. Though, it hides the entire Windows Terminal window, even if you have many tabs open (and run the rclone command from one of them). This seems a bit strange.  but it is how Windows Terminal handles the api as described in the terminal release notes. When it is was started as the default terminal I assume it will behave more as expected (I haven't tried it). Anyway, not a rclone issue - closing.

**Comment by eugenov** [comment]
Still not working with 1.15.1863.0 Preview, but it is not rclone issue, only WT. My scenario is batch file, running on startup - all WT windows remain open with running rclone processes.

**Comment by LeVraiRoiDHyrule** [comment]
Hi, I am still having the exact same issue with Terminal ver1.21.3231.0. rclone launched with --no-console, but still opens the terminal.

**Comment by albertony** [comment]
Until Microsoft fixes this (again?), you can make sure to run rclone with the legacy console, in one of two ways:

1) If using a Windows shortcut, configure it with: Properties > Options > Use Legacy Console.
2) Run it with a command which explicitly starts rclone.exe within conhost.exe, instead of explicit or implicit cmd.exe (since they redirect to wt.exe when you have Windows terminal selected as default console): `C:\Windows\System32\conhost.exe "C:\Path\To\rclone.exe" --no-console ...`

Alternatively, use any of the several generic Windows tricks to hide it, instead of --no-console. E.g. using a Windows Script wrapper. Search the rclone forum, or other sources, for hints.

**Comment by albertony** [comment]
There are similar reports from several other console applications, including Microsoft's own PowerShell - which should be able to run with hidden console when started with `-WindowStyle Hidden`, e.g. the following no longer works as expected:

```pwsh
powershell.exe -WindowStyle Hidden -Command Sleep 10
```

The issue seem to be tracked by this issue now: https://github.com/microsoft/terminal/issues/12464

**Comment by vbifonixor** [comment]
> The issue seem to be tracked by this issue now: https://github.com/microsoft/terminal/issues/12464

Workaround in [this comment](https://github.com/microsoft/terminal/issues/12464#issuecomment-3072467062) helps
