### ISSUE TITLE
Azure Storage Account use_msi do not work

### ISSUE THREAD

**Issue by MasterKuat** [rclone/rclone#6233]
#### What is the problem you are having with rclone?
When trying to use msi with rclone I get an error : Failed to create file system for "deposeCOM:": Need account+key or connectionString or sasURL

#### What is your rclone version (output from `rclone version`)
rclone v1.50.1
- os/arch: windows/amd64
- go version: go1.13.4

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows Server 2016 x64

#### Which cloud storage system are you using? (e.g. Google Drive)
Azure Storage

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
rclone lsd deposeCOM: --config "F:\Applis\Sync\rclone_deposeCOM.conf" -vv
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2022/06/10 13:55:36 DEBUG : rclone: Version "v1.50.1" starting with parameters ["C:\\ProgramData\\chocolatey\\lib\\rclone.portable\\tools\\rclone-v1.50.1-windows-amd64\\rclone.exe" "lsd" "deposeCOM:" "--config" "F:\\Applis\\Sync\\rclone_deposeCOM.conf" "-vv"]
2022/06/10 13:55:36 DEBUG : Using config file from "F:\\Applis\\Sync\\rclone_deposeCOM.conf"
2022/06/10 13:55:36 Failed to create file system for "deposeCOM:": Need account+key or connectionString or sasURL
```

rclone_deposeCOM.conf : 
```
[deposeCOM]
type = azureblob
account = mystorageaccount
use_msi = true
```

VM has identity and role needed.
```
Connect-AzAccount -Identity
Get-AzStorageContainer -Context (New-AzStorageContext -StorageAccountName $StorageAccountName -UseConnectedAccount -ErrorAction SilentlyContinue) -Name $BlobContainer -ErrorAction SilentlyContinue
```
Return my container and I able to list also blob.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Your version is from the dinosaur era, please update it.

**Comment by MasterKuat** [comment]
![image](https://user-images.githubusercontent.com/48821872/173069923-0e224fd8-aaed-4fdb-a4fd-0bf547c2d275.png)
Seems chocolatey do not remove old version.

Sorry about that. Everything fine after uninstalling and reinstall rclone.

**Comment by animosity22** [comment]
Closing as issue is fixed.
