### ISSUE TITLE
Preserve folder creation dates after rclone copy from S3 / MinIO buckets

### ISSUE THREAD

**Issue by mirekphd** [rclone/rclone#6242]
#### What is your current rclone version (output from `rclone version`)?
/ $ rclone --version
rclone v1.58.1-DEV
- os/version: alpine 3.15.4 (64 bit)
- os/kernel: 3.10.0-957.27.2.el7.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.18.2
- go/linking: dynamic
- go/tags: none

#### What problem are you are trying to solve?
Restore backup data from remote S3-compat. bucket (MinIO 2022), while preserving the original folder creation times (currently only works for files).

The command I'm using for copying data from the remote backup:
```
rclone --progress --check-first --create-empty-src-dirs --multi-thread-streams=$NTHREADS --s3-upload-concurrency=$MULTIPART_NTHREADS --s3-max-upload-parts=$MAX_PARTS --s3-chunk-size=$CHUNK_SIZE --s3-upload-cutoff=$CHUNKED_UPLOADS_CUTOFF --max-size=$MAX_FILE_SIZE --s3-disable-checksum=$DISABLE_CHECKSUM --s3-use-multipart-etag=$USE_MULTIPART_ETAG --s3-endpoint $SOURCE_URL copy minio:$SOURCE_BUCKET_NAME $TARGET_LOCAL_FOLDER
```

Illustration of the current behavior after data is restored from a MinIO bucket:
```
/ $ ls -lant /home/jovyan/python-for-data-science-knowledge-tests/tests-20210118/test-for-
bartek/
total 804
drwxr-xr-x    4 65534    65534          200 Jun 13 09:08 .
drwxr-xr-x    6 65534    65534           88 Jun 13 09:08 ..
drwxr-xr-x    2 65534    65534          163 Jun 13 09:08 .ipynb_checkpoints
drwxr-xr-x    2 65534    65534           96 Jun 13 09:08 input
-rw-r--r--    1 65534    65534       412622 Apr 27 11:53 SOLUTION-FOR-stacked-regressions-top-4-on-leaderboard.ipynb
-rw-r--r--    1 65534    65534       407205 Apr 27 11:50 EXAM-TEMPLATE-stacked-regressions-top-4-on-leaderboard.ipynb
/ $ date
Mon Jun 13 09:27:26 UTC 2022
```

#### How do you think rclone should be changed to solve that?
Mirror also for _folders_ the method currently used for storing _file_ creation timestamps (in S3 metadata).

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
S3 remotes don't actually store folders at all - they emerge from the pattern of the files.

So this actually isn't possible unless we write directory markers for each folder.
