### ISSUE TITLE
team drive disables Shared with me

### ISSUE THREAD

**Issue by nikkopante** [rclone/rclone#6247]
Hi everyone, I need to see the **Shared drives** and **Shared with me**. If I don't configure the connection with the team drive, the Shared with me files/folder appears with the flag `--drive-shared-with-me`, however, the Shared drives will not appear (i.e. rclone lsd). If I configure it to have team drive, I can now see the Shared drives, however, this time the Shared with me files/folders won't appear/visible.
Scenario 1
```
[example-drive]
type = drive
scope = drive
token = xxxx
team_drive = 0AHogtF06pKGDUk9XXX
root_folder_id = 
```

```
> rclone lsd example-drive:
-1 2021-09-21 17:52:22        -1 Products
> rclone lsd example-drive: --drive-shared-with-me

>
```

Scenario 2
```
[example-drive]
type = drive
scope = drive
token = xxxx
team_drive = 
root_folder_id = 
```

```
> rclone lsd example-drive:

> rclone lsd example-drive: --drive-shared-with-me
-1 2022-05-04 14:34:09        -1 Extracted_Images

```

OS: Windows 10
rclone version: rclone-v1.58.1-windows-amd64

**Comment by ncw** [comment]
I can reproduce this.

The queries done are:

Without team drive
```
GET /drive/v3/files?alt=json
&fields=files%28id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks%2CresourceKey%29%2CnextPageToken%2CincompleteSearch
&includeItemsFromAllDrives=true
&pageSize=1000
&prettyPrint=false
&q=trashed%3Dfalse+and+%28sharedWithMe%3Dtrue%29
&supportsAllDrives=true
```

With team drive
```
GET /drive/v3/files?alt=json
&corpora=drive
&driveId=XXXTeamDriveIDXXX
&fields=files%28id%2Cname%2Csize%2Cmd5Checksum%2Ctrashed%2CexplicitlyTrashed%2CmodifiedTime%2CcreatedTime%2CmimeType%2Cparents%2CwebViewLink%2CshortcutDetails%2CexportLinks%2CresourceKey%29%2CnextPageToken%2CincompleteSearch
&includeItemsFromAllDrives=true
&pageSize=1000
&prettyPrint=false
&q=trashed%3Dfalse+and+%28sharedWithMe%3Dtrue%29
&supportsAllDrives=true HTTP/1.1
```

So it looks like `sharedWithMe` is incompatible with `corpora=drive` or `driveId=XXXTeamDriveIDXXX`

This is easy to fix - can you try this beta please?

[v1.59.0-beta.6203.bba5ed4b1.fix-6247-sharedwithme](https://beta.rclone.org/branch/fix-6247-sharedwithme/v1.59.0-beta.6203.bba5ed4b1.fix-6247-sharedwithme/) on branch [fix-6247-sharedwithme](https://github.com/rclone/rclone/tree/fix-6247-sharedwithme) (uploaded in 15-30 mins)
