### ISSUE TITLE
Rclone size reporting size smaller than actual size on Google Team Drive

### ISSUE THREAD

**Issue by jericjan** [rclone/rclone#6249]
#### What is the problem you are having with rclone?
When I try to use `rclone size` on a folder on a Google Team drive that I'm in, it gives me a smaller size than what it actually should be. 

`rclone size` gives me:
 **9.426** GiB (10121218984 bytes)
 
Once fully downloaded to local machine, running `du` on it gives me:
 **9.484** GiB (10183401472 bytes) for disk usage
**9.433** GiB (10128620456 bytes) for apparent size.

It's larger for some reason and I don't know why. I tried checking if there was a difference in the file count and there wasn't. The remote and the local copy both had 23,797 files. I tried to check file hashes but Google Drive doesn't seem to support that. I tried running `rclone size` with `--disable ListR` but it still reported the same size.

#### What is your rclone version (output from `rclone version`)
rclone v1.58.1
- os/version: ubuntu 18.04 (64 bit)
- os/kernel: 5.4.188+ (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.9
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Ubuntu 18.04.5 LTS x86_64

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive (encrypted team drive)

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone size remote: -vv`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2022/06/14 12:09:14 DEBUG : rclone: Version "v1.58.1" starting with parameters ["rclone" "--config=/root/.rclone.conf" "size" "epic4:pipart.dbx-external-drive/" "-vv"]
2022/06/14 12:09:14 DEBUG : Creating backend with remote "epic4:pipart.dbx-external-drive/"
2022/06/14 12:09:14 DEBUG : Using config file from "/root/.rclone.conf"
2022/06/14 12:09:14 DEBUG : Creating backend with remote "pog4:epicness/0rf5ri8oka7h04ckbp02oaf9g53fj9gdbggkla7n1kgbah6jbvv0"
2022/06/14 12:09:14 DEBUG : pog4: Loaded invalid token from config file - ignoring
2022/06/14 12:09:14 DEBUG : Saving config "token" in section "pog4" of the config file
2022/06/14 12:09:14 DEBUG : Keeping previous permissions for config file: -rw-rw-rw-
2022/06/14 12:09:14 DEBUG : pog4: Saved new token in config file
Total objects: 23.797k (23797)
Total size: 9.426 GiB (10121218984 Byte)
2022/06/14 12:09:46 DEBUG : 20 go routines active
```

#### Other logs
`!du -B 1 /directory/` (filenames obfuscated)
https://pastebin.com/e04s8BX5

`!du -B 1 --apparent-size /directory/` (filenames obfuscated)
https://pastebin.com/4fuenuwW

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> Once fully downloaded to local machine, running `du` on it gives me:
> **9.484** GiB (10183401472 bytes) for disk usage
> **9.433** GiB (10128620456 bytes) for apparent size.

Try running `rclone size /path/to/local` then at least we are comparing like with like.

I think `du` counts directories which rclone doesn't.

**Comment by jericjan** [comment]
Hmm, running `rclone size` on my local directory gives me:
```
Total objects: 23.797k (23797)
Total size: 9.426 GiB (10121218984 Byte)
```

**Comment by animosity22** [comment]
That's correct, du counts directories as well so the outputs will not match.

**Comment by ncw** [comment]
Use rclone check to verify the source and destination are the same. This will check sizes and hashes.

**Comment by jericjan** [comment]
It takes way too long to check with file hashes so I ran `rclone check remote: /path/to/local --download --size-only` instead and it seems to have found 0 differences which is good to hear. I had no idea directories themselves could also take up space. An error on my part. Thanks, I will close this now.

**Comment by ncw** [comment]
`rclone check --download` is the gold standard check, so it looks like your data is good :-)
