### ISSUE TITLE
SFTP keyboard interactive ssh: handshake failed

### ISSUE THREAD

**Issue by eugenov** [rclone/rclone#6253]
#### What is the problem you are having with rclone?
Hello!
When I'm trying mount Asustor NAS, there is no methods other than keyboard-interactive. But with 

```
[home]
type = sftp
host = IP
user = root
pass = obfuscatedpass
disable_hashcheck = true
use_insecure_cipher = true
ask_password = true
```
in my config mount fails. Seems similar: https://github.com/rclone/rclone/issues/4177
#### What is your rclone version (output from `rclone version`)
rclone v1.58.1
- os/version: Microsoft Windows 11 Pro 21H2 (64 bit)
- os/kernel: 10.0.22000.708 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.17.9
- go/linking: dynamic
- go/tags: cmount

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Win11 22000.708

#### Which cloud storage system are you using? (e.g. Google Drive)
SFTP
#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`start C:\Users\user\apps\rclone\rclone.exe --config C:\Users\user\apps\rclone\rclone.conf -vv --log-file C:\Users\user\apps\rclone\logs\home.txt --cache-dir . --temp-dir . mount "home:/" "C:\Users\user\rclone\home" --vfs-cache-mode full --no-console`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
...
2022/06/15 16:13:04 DEBUG : pacer: Rate limited, increasing sleep to 2s
2022/06/15 16:13:13 DEBUG : sftp://root@IP:22//: keyboard interactive auth requested
2022/06/15 16:13:15 DEBUG : pacer: low level retry 10/10 (error couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none keyboard-interactive], no supported methods remain)
2022/06/15 16:13:15 Failed to create file system for "home:/": NewFs: couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none keyboard-interactive], no supported methods remain
```

**Comment by eugenov** [comment]
> You probably don't want this

You're right, it was one of config edits to match right options.

**Comment by ncw** [comment]
So does it work now or is there still a problem?

**Comment by eugenov** [comment]
Still an issue. This was one of many edits, no luck, though.

**Comment by ncw** [comment]
Let's start with the obvious... Are you sure the username and password are correct? Remember the password needs to be run through `rclone obscure`.

Assuming those are correct, then this is some sort of ssh handshaking problem.

Can you log in with ssh and that user and password?

If so can you do `ssh -vvv user@IP` and we can take a look at what ssh negotiates.

It would be worth trying [the latest beta](https://beta.rclone.org/) too, just in case.

**Comment by ncw** [comment]
Glad you got it working. I'd be interested if you work out what the problem was - maybe it is something we could fix / document better?

**Comment by eugenov** [comment]
Sure, I could test 1.58.1 with `rclone obscure` and write results here. BTW documentation is really good, thank you!

**Comment by eugenov** [comment]
Made some tests - something wrong with obscuring/deobscuring in 1.58.1 version. Didn't managed to mount with obscured pass again. 1.59.0 is OK though...
