### ISSUE TITLE
copying embedded google apps scripts

### ISSUE THREAD

**Issue by simonckenyon** [rclone/rclone#6255]
my task is to make daily backups of a large set of spreadsheets stored on google drive. They are continuously being developed my multiple authors.

i use rclone running on a dedicated EC2 instance to copy some 40,000 files from google drive to an S3 bucket. this works very well.

however, there are multiple spreadsheets that contain google apps script code, which i also need to backup.

i see issue 2692 so i know the idea of copying scripts is not new. however i cannot see how to configure rclone to make copies of the script embedded in a spreadsheet.

is it possible?

and if so how?

**Comment by animosity22** [comment]
Please use the forums for use questions.

https://forum.rclone.org/
