### ISSUE TITLE
Compile rclone from source fails on FreeBSD 13.1

### ISSUE THREAD

**Issue by jemail99** [rclone/rclone#6256]
#### What is the problem you are having with rclone?

I'm trying to compile rclone from source to solve (hopefully) a fuse mount problem using the following commands:
```
pkg install bash git-lite gmake go
mkdir -p /usr/local/src
cd /usr/local/src/
git clone https://github.com/rclone/rclone.git
cd rclone/
gmake GOTAGS=cmount
```
The compile fails with a Fatal error:
```
<...>
# github.com/winfsp/cgofuse/fuse
../go/pkg/mod/github.com/winfsp/cgofuse@v1.5.1-0.20220421173602-ce7e5a65cac7/fuse/host_cgo.go:117:10: fatal error: 'fuse.h' file not found
#include <fuse.h>
         ^~~~~~~~
1 error generated.
<...>
gmake: *** [Makefile:49: rclone] Error 2
```
I would appreciate any help.

#### What is your rclone version (output from `rclone version`)
Latest github version as I'm trying to compile it from source.

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
FreeBSD 13.1

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
You need to install the fuse header files. That would be fuse-dev on linux - hopefully you can find the equivalent for FreeBSD.

**Comment by jemail99** [comment]
Ah,

that would be fusefs-libs for FreeBSD 13.1.

Thank you.
