### ISSUE TITLE
Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find FUSE

### ISSUE THREAD

**Issue by jemail99** [rclone/rclone#6257]
#### What is the problem you are having with rclone?

Attempting to mount encrypted MEGA cloud drive produces the following error:

`Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find FUSE`

#### What is your rclone version (output from `rclone version`)
```
rclone v1.59.0-beta.6250.dcc128c70
- os/version: freebsd 13.1-release (64 bit)
- os/kernel: 13.1-release (arm64)
- os/type: freebsd
- os/arch: arm64
- go/version: go1.18.3
- go/linking: dynamic
- go/tags: cmount
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

FreeBSD 13.1 aarch64

#### Which cloud storage system are you using? (e.g. Google Drive)

MEGA

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
/usr/local/bin/rclone cmount -vv --config=/root/.config/rclone/rclone.conf --cache-dir=/var/cache/rclone --vfs-cache-mode full crypt: /crypt
2022/06/17 17:21:15 DEBUG : rclone: Version "v1.59.0-beta.6250.dcc128c70" starting with parameters ["/usr/local/bin/rclone" "cmount" "-vv" "--config=/root/.config/rclone/rclone.conf" "--cache-dir=/var/cache/rclone" "--vfs-cache-mode" "full" "crypt:" "/mnt"]
2022/06/17 17:21:15 DEBUG : Creating backend with remote "crypt:"
2022/06/17 17:21:15 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2022/06/17 17:21:15 DEBUG : Creating backend with remote "MEGA:Crypt"
2022/06/17 17:21:17 INFO  : Encrypted drive 'crypt:': poll-interval is not supported by this remote
2022/06/17 17:21:17 DEBUG : vfs cache: root is "/var/cache/rclone"
2022/06/17 17:21:17 DEBUG : vfs cache: data root is "/var/cache/rclone/vfs/crypt"
2022/06/17 17:21:17 DEBUG : vfs cache: metadata root is "/var/cache/rclone/vfsMeta/crypt"
2022/06/17 17:21:17 DEBUG : Creating backend with remote "/var/cache/rclone/vfs/crypt/"
2022/06/17 17:21:17 DEBUG : Creating backend with remote "/var/cache/rclone/vfsMeta/crypt/"
2022/06/17 17:21:17 DEBUG : Mounting on "/mnt" ("crypt")
2022/06/17 17:21:17 INFO  : vfs cache: cleaned: objects 0 (was 0) in use 0, to upload 0, uploading 0, total size 0 (was 0)
2022/06/17 17:21:17 DEBUG : Encrypted drive 'crypt:': Mounting with options: ["-o" "attr_timeout=1" "-o" "fsname=crypt:" "-o" "subtype=rclone" "-o" "max_readahead=131072" "-o" "atomic_o_trunc"]
2022/06/17 17:21:17 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find FUSE
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

See above.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> cgofuse: cannot find FUSE

This normally means `libfuse` isn't installed or the kernel module in needs isn't installed. Something like that!

**Comment by jemail99** [comment]
Arrrghhh,

I had fusefs-libs 3 installed but also needed fusefs-libs 2

Thank you.
