### ISSUE TITLE
rclone ncdu: Fix screen corruption when logs happen

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#6271]
#### The associated forum post URL from `https://forum.rclone.org`

This was discussed in https://github.com/rclone/rclone/pull/6259 which was an attempt to fix this problem.

#### What problem are you are trying to solve?

Currently the `rclone ncdu` screen gets corrupted if rclone logs anything. This can be fixed with CTRL-L but it would be nice if it didn't happen at all.

#### How do you think rclone should be changed to solve that?

After a bit of discussion the best approach is probably

- capture the logging in the same way `--progress` does
    - https://github.com/rclone/rclone/blob/7a909ebfb0d100187fab7949455bf74b8ce07042/cmd/progress.go#L29-L40
- store the logs as they come in up to a maximum of 1000 (say)
- show the last log in the status bar
- show the logs in the buffer when exiting ncdu

At some point we could also make a log viewing window which would allow you to view / scroll the logs so far.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by eNV25** [comment]
I implemented both approaches in #6707. I will create a final PR based on feedback.

**Comment by eNV25** [comment]
@albertony @ncw Can you take a look at #6707?
