### ISSUE TITLE
rclone ncdu: Move from Tcell's termbox compatibility layer to native Tcell

### ISSUE THREAD

**Issue by albertony** [rclone/rclone#6272]
#### What problem are you are trying to solve?

PR #6258 changed ncdu's implementation from using `termbox` (<https://github.com/nsf/termbox-go>) to `Tcell` (<https://github.com/gdamore/tcell>). It used tcell's compatibility layer for termbox, which kept the required code changes and risk on a minimum. This issue is for the natural next step: Changing to tcell's "native" api. This will prepare the ground for making use of more advanced features of Tcell.

#### How do you think rclone should be changed to solve that?

An example of a small patch that ports some functions to tcell is shown here: https://github.com/rclone/rclone/pull/6258#issuecomment-1159684288

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by eNV25** [comment]
This issue can be closed.

**Comment by albertony** [comment]
Ah yes, you are right, thanks. Consider it done! ;)
