### ISSUE TITLE
Add staticcheck to build pipeline

### ISSUE THREAD

**Issue by albertony** [rclone/rclone#6273]
#### What problem are you are trying to solve?

Add [staticcheck](<https://staticcheck.io>) based linting to the build pipeline. Maybe as an advisory to start with.

Staticcheck is the default linter in VSCode-based golang dev environment, and from my experience it gives many relevant suggestions that the current linter does not consider.

First we need to fix as many as possible of the reported "problems", and if necessary add ignores of any false positives or suggestions we for other reasons don't agree with (and then decide on the best strategy for managing such ignores, see https://staticcheck.io/docs/configuration/#ignoring-problems). I've started going through them myself, fixing in different PRs:
- https://github.com/rclone/rclone/pull/6228
- https://github.com/rclone/rclone/pull/6239
- https://github.com/rclone/rclone/pull/6238
- https://github.com/rclone/rclone/pull/6236
- https://github.com/rclone/rclone/pull/6237
- https://github.com/rclone/rclone/pull/6275
- https://github.com/rclone/rclone/pull/6276
- https://github.com/rclone/rclone/pull/6277
- https://github.com/rclone/rclone/pull/6389 (New: Deprecations starting with go 1.16, detected after minimum was raised to go 1.17)
- https://github.com/rclone/rclone/pull/6387 (New)

When I started it reported about 300 "problems", if/when all these are merged we are down to below 30 (with staticcheck v0.3.2 and go v1.18.3). Remaining includes:
- func is unused (13 occurrences)
- httplib is deprecated and has been replaced with lib/http (8 occurrences)
- infinite recursive call, here: https://github.com/rclone/rclone/blob/73e3bb09d71c31814e00ebcad2eec9be3b74ccf0/fs/pacer.go#L76
- argument err is overwritten before first use, here: https://github.com/rclone/rclone/blob/73e3bb09d71c31814e00ebcad2eec9be3b74ccf0/backend/onedrive/onedrive.go#L1670
- argument should be pointer-like to avoid allocations, here: https://github.com/rclone/rclone/blob/73e3bb09d71c31814e00ebcad2eec9be3b74ccf0/backend/crypt/cipher.go#L242

#### How do you think rclone should be changed to solve that?

See the mentioned PRs in general, and this: https://github.com/rclone/rclone/pull/6228#issuecomment-1154869610

We should probably try with `golangci-lint` (<https://golangci-lint.run/usage/quick-start>) first, instead of `staticcheck` directly, since we already are using it.  It does have a staticcheck linter (<https://golangci-lint.run/usage/linters/>), which we can add to our list:

https://github.com/rclone/rclone/blob/fdd2f8e6d21d1cf95b33fd2bb09f9c1caef0069d/.golangci.yml#L3-L15

Though its not the actual staticcheck, so must be tested and compared first:

> It's a set of rules from staticcheck. It's not the same thing as the staticcheck binary. The author of staticcheck doesn't support or approve the use of staticcheck as a library inside golangci-lint.

Would be good if the standalone staticcheck, which is also run from go integration in VSCode, do not produce different results.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I like this idea in principle.

Maybe after the 1.59 release we could integrate it into the build pipeline?

**Comment by albertony** [comment]
Sure. There have been some related discussion in issues/PRs since this (spell checkers, CodeQL etc), so would be good to get a new "base".

Don't think https://github.com/rclone/rclone/pull/6387 is too far off. Getting https://github.com/rclone/rclone/pull/6277 tested is more uncertain, though.

**Comment by ncw** [comment]
OK, let's try and get #6387 merged then :-)
