### ISSUE TITLE
rclone not working with Ceph S3 RGW

### ISSUE THREAD

**Issue by DySprozin** [rclone/rclone#6285]
#### What is the problem you are having with rclone?
rclone not working with Ceph S3 RGW

#### What is your rclone version (output from `rclone version`)
rclone-v1.58.1-linux-amd64.deb
rclone v1.58.1
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-37-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.9
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
ubuntu 22.04 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)
Ceph

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone --dump bodies copy -vv cephS3:mybucket/test.xml .

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
root@local:~# rclone --dump bodies copy -vv cephS3:mybucket/test.xml .
2022/06/29 15:04:39 DEBUG : rclone: Version "v1.58.1" starting with parameters ["rclone" "--dump" "bodies" "copy" "-vv" "cephS3:mybucket/test.xml" "."]
2022/06/29 15:04:39 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2022/06/29 15:04:39 DEBUG : Creating backend with remote "cephS3:mybucket/test.xml"
2022/06/29 15:04:39 DEBUG : You have specified to dump information. Please be noted that the Accept-Encoding as shown may not be correct in the request and the response may not show Content-Encoding if the go standard libraries auto gzip encoding was in effect. In this case the body of the request will be gunzipped before showing it.
2022/06/29 15:04:39 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/06/29 15:04:39 DEBUG : HTTP REQUEST (req 0xc000218d00)
2022/06/29 15:04:39 DEBUG : HEAD /mybucket/test.xml HTTP/1.1
Host: my.ceph3.host:18080
User-Agent: rclone/v1.58.1
Authorization: XXXX
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20220629T120439Z

2022/06/29 15:04:39 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/06/29 15:04:39 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/06/29 15:04:39 DEBUG : HTTP RESPONSE (req 0xc000218d00)
2022/06/29 15:04:39 DEBUG : HTTP/1.1 200 OK
Content-Length: 165
Accept-Ranges: bytes
Content-Type: application/xml
Date: Wed, 29 Jun 2022 12:04:39 GMT
Etag: "05bb8ceb97e8a21b103a81cd521ada5c"
Last-Modified: Tue, 28 Jun 2022 21:21:35 GMT
X-Amz-Expiration: expiry-date="Wed, 06 Jul 2022 00:00:00 GMT", rule-id="c879tn0mccft1f8ul3a0"
X-Amz-Meta-Mtime: 1656448085.172
X-Amz-Object-Lock-Mode: GOVERNANCE
X-Amz-Object-Lock-Retain-Until-Date: Wed, 29 Jun 2022 21:21:35 GMT
X-Amz-Request-Id: tx00000783e5660a83a5e9f-0062bc3fd7-13a7215-default
X-Amz-Version-Id: dCfK-BpydcH4miYgbwVeNLXEoGLjXJj
X-Rgw-Object-Type: Normal

2022/06/29 15:04:39 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/06/29 15:04:39 DEBUG : pacer: low level retry 1/10 (error SerializationError: empty response payload
	status code: 200, request id: tx00000783e5660a83a5e9f-0062bc3fd7-13a7215-default, host id: 
caused by: EOF)
2022/06/29 15:04:39 DEBUG : pacer: Rate limited, increasing sleep to 10ms
```
full log: https://paste.debian.net/1245733/

#### Config
```
[cephS3]
type = s3
provider = Ceph
access_key_id = ***************
secret_access_key = ******************
endpoint = http://my.ceph3.host:18080
acl = private
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by DySprozin** [comment]
additional error (when copy "folder" 222 with "file" test.xml)
```
rclone copy cephS3:mybucket/222 .
2022/06/29 13:44:42 ERROR : test.xml: Failed to copy: failed to open source object: SerializationError: failed to unmarshal error message
	status code: 200, request id: tx0000085b3df9eb16f1400-0062bc2d1a-1e653bc-default, host id: 
caused by: UnmarshalError: failed to unmarshal error message
	00000000  3c 3f 78 6d 6c 20 76 65  72 73 69 6f 6e 3d 22 31  |<?xml version="1|
00000010  2e 30 22 20 65 6e 63 6f  64 69 6e 67 3d 22 55 54  |.0" encoding="UT|
00000020  46 2d 38 22 3f 3e 0a 3c  6e 6f 74 65 3e 0a 20 20  |F-8"?>.<note>.  |
00000030  3c 74 6f 3e 54 6f 76 65  3c 2f 74 6f 3e 0a 20 20  |<to>Tove</to>.  |
00000040  3c 66 72 6f 6d 3e 4a 61  6e 69 3c 2f 66 72 6f 6d  |<from>Jani</from|
00000050  3e 0a 20 20 3c 68 65 61  64 69 6e 67 3e 52 65 6d  |>.  <heading>Rem|
00000060  69 6e 64 65 72 3c 2f 68  65 61 64 69 6e 67 3e 0a  |inder</heading>.|
00000070  20 20 3c 62 6f 64 79 3e  44 6f 6e 27 74 20 66 6f  |  <body>Don't fo|
00000080  72 67 65 74 20 6d 65 20  74 68 69 73 20 77 65 65  |rget me this wee|
00000090  6b 65 6e 64 21 3c 2f 62  6f 64 79 3e 0a 3c 2f 6e  |kend!</body>.</n|
000000a0  6f 74 65 3e 0a                                    |ote>.|

caused by: expected element type <Error> but have <note>
```

**Comment by ncw** [comment]
It looks like it doesn't like the bucket being HEADed.

Try adding --s3-no-check-bucket see if that helps

As for the copy problem, can you do a log with -vv -dump bodies?

**Comment by DySprozin** [comment]
the problem remains. Link to log: https://paste.debian.net/1245732/

**Comment by ncw** [comment]
Do you know which version of Ceph you are using?

What appears to be happening is that the response to the `HEAD /mybucket/test.xml` is confusing the AWS SDK into thinking it should be parsing a body which a HEAD request won't have of course. Or maybe it is trying to parse one of the headers as XML

I looked at the SDK source, and the error string "empty response payload" is in a function called `unmarshalError` indicating the SDK is trying to look for an error message, despite the 200 response.

So maybe its having trouble parsing the headers. I thought maybe the dates might be in the wrong format but they look OK.

It would be worth trying [the latest beta](https://beta.rclone.org/) which has a later version of the AWS S3 SDK which might have this fixed.
