### ISSUE TITLE
Google Drive account setup documentation out of date 

### ISSUE THREAD

**Issue by iandstanley** [rclone/rclone#6289]
#### The associated forum post URL from `https://forum.rclone.org`

n/a

#### What is the problem you are having with rclone?

I am trying to setup rclone for google drive, I follow the website documentation link at https://rclone.org/drive/

and try to follow.

However, Google appears to have drastically changed their website and particularly on the service account side (as I am trying to setup an automatic nightly encrypted backup of certain data) appears to have completely changed making the instructions extremely hard if not impossible to follow

#### What is your rclone version (output from `rclone version`)
%  rclone version
rclone v1.57.0-DEV
- os/version: freebsd 13.1-release (64 bit)
- os/kernel: 13.1-release (amd64)
- os/type: freebsd
- os/arch: amd64
- go/version: go1.17.5
- go/linking: dynamic
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

FreeBSD 13.1

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Drive using a service account

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

Never got as far as running the rclone commands.

I was trying to follow the website documentation at https://rclone.org/drive/  which does not match the Google Cloud website making rclone's instructions on setting up a service account for automated rclone uploads/sync

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

n/a

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
What's not matching?

**Comment by iandstanley** [comment]
The whole section on service accounts entitled “Use Case - Google Apps/G-suite and individual Drive”

The bullets 1. And 2. Seem to have a completely different options/labels for a individual trying to setup a service account. 

I managed to blunder my way through creating a service account from their dialogs but stuff just gets dumped somewhere accessible but not on my drive. 


It’s no longer an issue for me because I then noticed that I can auto setup (I originally tried service account method because I want to script unattended backups for my home server - but the auto setup feature does this 

I just thought you might want to check the instructions against an individual account’s view of the system

**Comment by animosity22** [comment]
I just went through bullets 1 and 2 and they were correct as I followed them to the letter.

If you are working and have nothing else, I can just close it out.

If you want to discuss what you did and share some examples, please hit me up on the forums.

https://forum.rclone.org and if something isn't matching or needs updated, we can walk you through a pull request to get that done.
