### ISSUE TITLE
Samba support and O_RDONLY|O_CREATE

### ISSUE THREAD

**Issue by splitice** [rclone/rclone#6291]
It's a strange combination but there are quite a few threads in the forum that mention this combination not working.

It appears that Linux supports it.

Some software like samba uses it.

Effectively rclone needs to create the file if it doesnt exist and return a fd thats read only (empty file if created).

Currently it returns file not found error code.

**Comment by animosity22** [comment]
For creating issues, please use the template to collect the information.

The forums are the starting point for questions so please use the help and support template and post there.

https://forum.rclone.org

Thanks for your help.
