### ISSUE TITLE
Support for oracle cloud infrastructure (oci) object storage  as native backend.

### ISSUE THREAD

**Issue by msays2000** [rclone/rclone#6299]
Support for Oracle Cloud Infrastructure Object Storage Natively. 

While OCI Object storage works in [S3 Compat mode](https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm) via User's access-key, secret-key as auth, however, it doesn't work with Instance Principals and Resource Principals. I am a developer in OCI and reached out to internal relevant team,  which confirmed that it is not supported to associate S3 compatible credentials for resource principals, instance principals. 

This makes the use of rclone on OCI instances cumbersome as user credentials needs to be pulled down, saved to local disk to make rclone work. 

I am thinking to add native backend support for OCI Object Storage. Filing this issue as a prerequisite to receive any feedback or comments. 

https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#writing-a-new-backend

**Comment by ncw** [comment]
Is there a Go library to access OCI?

Writing and maintaining a backend is a lot of work! Is there any way we could extend the s3 backend to read some auth from the native api, but use the S3 api for access?

**Comment by msays2000** [comment]
**Is there a Go library to access OCI?** 
yes there is oci-go-sdk which has all the clients to access OCI. For object storage its here https://github.com/oracle/oci-go-sdk/tree/master/objectstorage

**Writing and maintaining a backend is a lot of work! Is there any way we could extend the s3 backend to read some auth from the native api, but use the S3 api for access?**

Yes, agreed, it's a lot of work.

The [S3 Compat mode](https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/s3compatibleapi.htm) api only accepts AWS4-HMAC-SHA256 Authorization headers unfortunately. Trying to pass native Auth headers result in throwing exception that it only accepts amzn auth headers. 

So I tried to use Instance Principal security token into AWS4-HMAC-SHA256 Auth Header, which resulted in Mismatch Signature. Taking to internal teams, it appears that, it is not supported to associate S3 compatible credentials for resource principals, instance principals. Let me investigate on this more.

**Comment by msays2000** [comment]
@ncw synced with our internal team members, the s3 compat endpoint doesn't support Instance Principals and work to support is probably not going to happen to support both auth ([aws4](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html), [oci signature v1](https://docs.oracle.com/en-us/iaas/Content/API/Concepts/signingrequests.htm)). 

 So option is to add it as a new backend integrating with oci-go-sdk with [oci signature v1](https://docs.oracle.com/en-us/iaas/Content/API/Concepts/signingrequests.htm)

**Comment by ncw** [comment]
@msays2000 Ok that sounds like a reasonable argument. You have my blessing to make a new backend for this :-)

Follow the script here: https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#writing-a-new-backend

Note that s3 isn't a good backend to start from as it is very complicated though I would refer to the code. I'd probably start from one of the simpler bucket based backends like `b2` or `azureblob`.

**Comment by msays2000** [comment]
work in progress in my private remote, will post here once its ready.

**Comment by msays2000** [comment]
@ncw please take a look at the PR when you get some free time. thank you. It needs a maintainer's approval to do run the workflow.

**Comment by msays2000** [comment]
> @msays2000 Ok that sounds like a reasonable argument. You have my blessing to make a new backend for this :-)
> 
> Follow the script here: https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#writing-a-new-backend
> 
> Note that s3 isn't a good backend to start from as it is very complicated though I would refer to the code. I'd probably start from one of the simpler bucket based backends like `b2` or `azureblob`.

@ncw https://github.com/rclone/rclone/pull/6332 done..
