### ISSUE TITLE
Skynetfree support

### ISSUE THREAD

**Issue by KaspianDev** [rclone/rclone#6325]
Since we have Sia support, maybe we can get skynetfree, skynetpro support?
Skynetfree gives everyone 100GB decentralized storage so I think it would benefit everyone.

**Comment by ncw** [comment]
Does it have an API? Or maybe it runs of sia?

**Comment by KaspianDev** [comment]
> Does it have an API? Or maybe it runs of sia?

It 100% has some kind of api (there is one tool that let's you manage you files on skynetfree)
https://github.com/redsolver/vup < this is the said tool

https://sdk.skynetlabs.com/#introduction and i assume this might help (i'm not experienced with developing that kind of stuff)

**Comment by footlooseboss** [comment]
from [Skynet SDK docs linked above](https://sdk.skynetlabs.com/):

> As of April 2022 the non-JS SDKs are still under heavy construction. Use the JS libraries for the best experience.

[Skynet Go SDK](https://github.com/SkynetLabs/go-skynet) 

However they use the Go SDK for `skynet-cli`; there are man pages here:
[skynet-cli docs](https://github.com/SkynetLabs/skynet-cli/tree/master/doc)

> skynet download - Download a skylink from skynet.
> skynet skykey - Perform skykey operations.
> skynet upload - Upload a file or a directory to Skynet.
> skynet version - Print the version number of 'skynet'.

**Comment by pcfreak30** [comment]
Skynet is dead in its current form. There will likely not be any guarantee of BC for future iterations; however, the Sia community continues the Skynet idea.

I think this issue should be closed. Future sia related backends will be possible, but not right now.

Kudos.

**Comment by footlooseboss** [comment]
> I think this issue should be closed. Future sia related backends will be possible, but not right now.

I agree. [Lume web portal](https://web3portal.com) is a replacement for skynetfree. It can be used with rclone via [vup.app/advanced/rclone](https://docs.vup.app/advanced/rclone/) for now.

[Lume web roadmap](https://forum.sia.tech/t/grant-proposal-lume-web/229)

> **Proposed timeline**
> - Portal Optimization - making web3portal.com the primary community Skynet portal and improving how usage and costs are tracked and ease of use.
> ...
> - Storage Drive & Filesystem - similar to vup.app (excellent dropbox-like Skynet-powered product by @redsolver), but have different goals and focuses. We will start in 2023 based on the time available.

So either they will provide clients for using the filesystem, or a new issue should be opened if/when they provide an API rclone can use.

**Comment by pcfreak30** [comment]
> > I think this issue should be closed. Future sia related backends will be possible, but not right now.
> 
> I agree. [Lume web portal](https://web3portal.com) is a replacement for skynetfree. It can be used with rclone via [vup.app/advanced/rclone](https://docs.vup.app/advanced/rclone/) for now.
> 
> [Lume web roadmap](https://forum.sia.tech/t/grant-proposal-lume-web/229)
> 
> > **Proposed timeline**
> > 
> > * Portal Optimization - making web3portal.com the primary community Skynet portal and improving how usage and costs are tracked and ease of use.
> >   ...
> > * Storage Drive & Filesystem - similar to vup.app (excellent dropbox-like Skynet-powered product by @redsolver), but have different goals and focuses. We will start in 2023 based on the time available.
> 
> So either they will provide clients for using the filesystem, or a new issue should be opened if/when they provide an API rclone can use.

I am the founder of Lume :P. I can tell you that things will break within ~3-6 months. Thus my comments. You may want to see the December report, BTW (scroll allll... the  way down lol)

Kudos.

**Comment by NickSdot** [comment]
@KaspianDev @ncw this can be closed. Skynet on Sia does no longer exist.

**Comment by KaspianDev** [comment]
> @KaspianDev @ncw this can be closed. Skynet on Sia does no longer exist.

i'm pretty sure it's just the official instance that got shut down

**Comment by pcfreak30** [comment]
> > @KaspianDev @ncw this can be closed. Skynet on Sia does no longer exist.
> 
> i'm pretty sure it's just the official instance that got shut down

Hello, I can tell you 100% that the Skynet ecosystem no longer exists as you knew it, and all code for it is deprecated or will be no longer compatible with the ecosystem after the incoming hard fork.. I was also one of the only few Skynet community portals that ever operated.

Sia has direct S3 support too now. So while support for a L2 could be added, direct Sia support is moot right now, and the Foundation sponsored the project in march.

I am building a new portal system myself this year under the Lume project but that will function differently, even if it follows Skynet in spirit. Lume's project direction has been a bit chaotic since this was last updated, so see https://forum.sia.tech/t/standard-grant-proposal-lume-web-2024/414/35 for this year.

Kudos.

**Comment by NickSdot** [comment]
> > @KaspianDev @ncw this can be closed. Skynet on Sia does no longer exist.
> 
> i'm pretty sure it's just the official instance that got shut down

The maintaining entity, SkynetLabs, is no longer operating. The domain the linked announcement was on, is expired. If you deem it necessary you might want to tag `DavidVorick` to validate. Please note the announcement in their [org](https://github.com/SkynetLabs). Fwiw, in case this is not known here: Skynet and Sia are two different projects, and entities – they been related in the past.

<img width="955" alt="image" src="https://github.com/rclone/rclone/assets/32384907/50d3c575-df00-4c2d-b1be-a970cc7ff18b">

**Comment by buengese** [comment]
Skynet Free no longer exists.
