### ISSUE TITLE
Panic when invoking rc core/stats-reset with non-existent group

### ISSUE THREAD

**Issue by sevimo123** [rclone/rclone#6327]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/panic-when-invoking-rc-core-stats-reset-with-non-existent-group/31967/2

#### What is the problem you are having with rclone?

Panic when invoking rc core/stats-reset with group parameter that specifies non-existent group

#### What is your rclone version (output from `rclone version`)

rclone v1.58.1

os/version: debian 10.2 (64 bit)
os/kernel: 4.19.0-6-amd64 (x86_64)
os/type: linux
os/arch: amd64
go/version: go1.17.9
go/linking: static
go/tags: none

rclone v1.59.0
- os/version: Microsoft Windows 7 Ultimate Service Pack 1 (64 bit)
- os/kernel: 6.1.7601.24546 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.18.3
- go/linking: static
- go/tags: cmount

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

See above (Debian x64, Windows 7 x64)

#### Which cloud storage system are you using? (e.g. Google Drive)

Not relevant

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone rc core/stats-reset group=errors

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2022/07/18 05:24:10 Failed to rc: Failed to read rc response: 500 Internal Server Error: {
        "error": "panic received: runtime error: invalid memory address or nil pointer dereference \ngoroutine 96852455 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/rclone/rclone/fs/rc/jobs.(*Job).run.func1()\n\tgithub.com/rclone/rclone/fs/rc/jobs/job.go:91 +0x45\npanic({0x1809b00, 0x2cd6030})\n\truntime/panic.go:1038 +0x215\ngithub.com/rclone/rclone/fs/accounting.(*StatsInfo).ResetErrors(0x0)\n\tgithub.com/rclone/rclone/fs/accounting/stats.go:627 +0x2e\ngithub.com/rclone/rclone/fs/accounting.rcResetStats({0xc01cba6160, 0x0}, 0x4116d4)\n\tgithub.com/rclone/rclone/fs/accounting/stats_groups.go:193 +0x85\ngithub.com/rclone/rclone/fs/rc/jobs.(*Job).run(0xc01cba6160, {0x1f203b0, 0xc000cca700}, 0xc01b818370, 0x5)\n\tgithub.com/rclone/rclone/fs/rc/jobs/job.go:94 +0x70\ngithub.com/rclone/rclone/fs/rc/jobs.(*Jobs).NewJob(0xc00038f9b0, {0x1f203b0, 0xc003908d00}, 0x1bf2ab0, 0xc015d3fa48)\n\tgithub.com/rclone/rclone/fs/rc/jobs/job.go:287 +0x3f4\ngithub.com/rclone/rclone/fs/rc/jobs.NewJob(...)\n\tgithub.com/rclone/rclone/fs/rc/jobs/job.go:297\ngithub.com/rclone/rclone/fs/rc/rcserver.(*Server).handlePost(0xc0000aab00, {0x1f08698, 0xc01ab70058}, 0xc024940000, {0xc014ff0529, 0x10})\n\tgithub.com/rclone/rclone/fs/rc/rcserver/rcserver.go:280 +0x712\ngithub.com/rclone/rclone/fs/rc/rcserver.(*Server).handler(0xc0000aab00, {0x1f08698, 0xc01ab70058}, 0xc024940000)\n\tgithub.com/rclone/rclone/fs/rc/rcserver/rcserver.go:213 +0x4f1\nnet/http.HandlerFunc.ServeHTTP(0x2d092c0, {0x1f08698, 0xc01ab70058}, 0xc000339c08)\n\tnet/http/server.go:2047 +0x2f\nnet/http.(*ServeMux).ServeHTTP(0x0, {0x1f08698, 0xc01ab70058}, 0xc024940000)\n\tnet/http/server.go:2425 +0x149\nnet/http.serverHandler.ServeHTTP({0x0}, {0x1f08698, 0xc01ab70058}, 0xc024940000)\n\tnet/http/server.go:2879 +0x43b\nnet/http.initALPNRequest.ServeHTTP({{0x1f20458, 0xc00e1b5e00}, 0xc00bf48a80, {0xc000aea1c0}}, {0x1f08698, 0xc01ab70058}, 0xc024940000)\n\tnet/http/server.go:3480 +0x245\nnet/http.(*http2serverConn).runHandler(0xc009ec2e78, 0xc009ec2fd0, 0x0, 0x0)\n\tnet/http/h2_bundle.go:5849 +0x78\ncreated by net/http.(*http2serverConn).processHeaders\n\tnet/http/h2_bundle.go:5579 +0x510\n",
        "input": {
                "group": "errors"
        },
        "path": "core/stats-reset",
        "status": 500
}
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Thanks for reporting this. I've fixed this here and added some tests. Can you give it a go? Thanks!

[v1.60.0-beta.6367.9149a4b64.fix-6327-stats-reset](https://beta.rclone.org/branch/fix-6327-stats-reset/v1.60.0-beta.6367.9149a4b64.fix-6327-stats-reset/) on branch [fix-6327-stats-reset](https://github.com/rclone/rclone/tree/fix-6327-stats-reset) (uploaded in 15-30 mins)

**Comment by sevimo123** [comment]
Well, I can confirm that [v1.60.0-beta.6367.9149a4b64.fix-6327-stats-reset](https://beta.rclone.org/branch/fix-6327-stats-reset/v1.60.0-beta.6367.9149a4b64.fix-6327-stats-reset/) build doesn't panic under circumstances reported above. However, the behavior now is somewhat inconsistent with other core/stats operations.

So, core/stats-reset with unknown group now returns 500 error / group not found. However, for instance core/stats with unknown group seems to create that group (???) with zero stats, then return such stats. No error is reported, and the group is not undefined anymore, it does exist now.

Not sure if some of this is unintended behavior, not sure which one.

**Comment by ncw** [comment]
I could change the implementation to just ignore a non-existent stats group - do you think that would be more inline with the current implementation? That makes the operation idempotent which is probably useful.

**Comment by sevimo123** [comment]
I think ultimately it needs to be either returning an error for all cases where non-existing groups are specified (obvious semantics, easy to catch mistakes, will need a bit more error handling for the clients) or silently ignore non-existing groups (non-obvious semantics but potentially little errorhandling). I think the most confusing setup is current implementation where non-existing group reference actually silently creates an empty group.

I'd probably prefer returning errors on non-existing groups, this makes the most sense. But it changes existing implementation, so ;)

**Comment by ncw** [comment]
Yes returning errors on non existing for everything would be best.

I'm not going to change it at the moment though as I want a patch I can backport for 1.59.1 and I don't want behaviour changes there.

Do you fancy making it consistent @sevimo123 ?
