### ISSUE TITLE
Factor rclone.go so it can be called as a library

### ISSUE THREAD

**Issue by polanskya** [rclone/rclone#633]
Refactor code to pass rclone args also as a string[]  in addition to os.Args.

Currently : 

``` go
os.Args = []string{"rclone", "sync", "srcDir", "targetDir"}
if err := cmd.Root.Execute(); err != nil {
        fmt.Println(err)
        os.Exit(-1)
    }
```

Thanks

**Comment by bep** [comment]
This construction works fine, even if it is a little hackish:

```go
func main() {

	log.Println("Starting backup ...")

	os.Args = []string{"rclone", "sync"}

	flags := []string{"--config", "myconfig.conf"}

	os.Args = append(os.Args, "/my/src", "/my/dst")

	if err := cmd.Root.ParseFlags(flags); err != nil {
		log.Fatal(err)
	}

	if err := cmd.Root.Execute(); err != nil {
		log.Fatalf("Fatal error: %v", err)
	}

}
```

**Comment by venkigeek** [comment]
> This construction works fine, even if it is a little hackish:
> 
> ```go
> func main() {
> 	os.Args = []string{"rclone", "sync"}
> 
> 	flags := []string{"--config", "myconfig.conf"}
> 
> 	if err := cmd.Root.ParseFlags(flags); err != nil {
> 		log.Fatal(err)
> 	}
> 
>         os.Args = append(os.Args, "/my/src", "/my/dst")
> 
> 
> 	if err := cmd.Root.Execute(); err != nil {
> 		log.Fatalf("Fatal error: %v", err)
> 	}
> 
> }
> ```

I am getting unknown flag: --config. Can you help?

**Comment by ncw** [comment]
> I am getting unknown flag: --config. Can you help?

Try setting `os.Args` to the desired call for rclone then calling `cmd.Main()` that should work.

Ideally there would be a less hackish way of doing this - I'd welcome a PR :-)

**Comment by ivandeex** [comment]
Possibility to embed rclone was discussed in https://github.com/restic/restic/issues/2411

**Comment by ivandeex** [comment]
@ncw @bep
I guess that `librclone` recently introduced by https://github.com/rclone/rclone/issues/4891#issuecomment-786432706 will satisfy this old request 🥂

**Comment by ivandeex** [comment]
@ncw @bep @polanskya @venki-sa
I guess that `librclone` recently introduced by https://github.com/rclone/rclone/issues/4891#issuecomment-786432706 and efforts #5234 to remove Fatal throughout will finally satisfy this old request
🥂

**Comment by ivandeex** [comment]
Closed after 4  months of silence.

**Comment by ncw** [comment]
Yes I agree that librclone is the way to go here :-)
