### ISSUE TITLE
Issue with Combine backend when using 2+ Crypt backends with different filename_encoding

### ISSUE THREAD

**Issue by Forum1877621** [rclone/rclone#6330]
#### What is the problem you are having with rclone?

It doesn't appear to be possible to use two crypts mounted with the combine backend if the crypts use different filename encodings

How to reproduce:

1. Make some encrypted files with the default base32 filename_encoding
2. Make a different set of files with a different filename_encoding such as base64 or base32768
3. Combine them with the combine backend
4. When you mount them combined, you can only pass one encoding as an argument such as --crypt-filename-encoding=base32768 and the encrypted set of files with a different filename_encoding cannot be seen 

Possible solution: allow the filename_encoding to be specified in the conf file for each crypt, then it won't need to be passed via command line

#### What is your rclone version (output from `rclone version`)

1.59

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 10, 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)

rclone crypt

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> Possible solution: allow the filename_encoding to be specified in the conf file for each crypt, then it won't need to be passed via command line

This can already be part of the config: https://rclone.org/crypt/#crypt-filename-encoding ?

If you are still having trouble, please post your config file with secrets redacted, and the command line you are using to run rclone.

**Comment by Forum1877621** [comment]
Yes you're right, I was confused by the documentation. I thought filename_encoding had to be passed as command line argument. Thanks for the clarification.
