### ISSUE TITLE
Oracle Cloud Storage S3 provider with storage_class

### ISSUE THREAD

**Issue by cberni** [rclone/rclone#6334]
oracle provider in s3

provider = Oracle
storage_class = STANDARD | INFREQUENT_ACCESS | ARCHIVE

https://docs.oracle.com/en-us/iaas/api/#/en/objectstorage/20160918/Object/PutObject

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by msays2000** [comment]
hi @cberni we are adding OCI Object Storage as native backend, SetTier is not supported in this PR yet, but I will make a follow up PR to support it natively. 

https://github.com/rclone/rclone/pull/6332
