### ISSUE TITLE
rclone gdrive setup documentation for (non-organization) individual personal use?

### ISSUE THREAD

**Issue by dchmelik** [rclone/rclone#6339]
#### What is your current rclone version (output from `rclone version`)?
v1.59.0

#### What problem are you are trying to solve?
Rclone access gdrive as (non-organization) individual personal user.

#### How do you think rclone should be changed to solve that?
Document (non-organization) individual personal gdrive setup (if applicable) (current [rclone.org/drive](http://rclone.org/drive) seems only for organizations).

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
It's the same process for both as there's no difference.

Use the forums for any help you may require and we're happy to assist!
