### ISSUE TITLE
Bandwidth limiter uploading to storj not working

### ISSUE THREAD

**Issue by theretohere** [rclone/rclone#6342]
#### What is the problem you are having with rclone?
Setting a bandwidth limit on upload to storj results in no upload limit being set for storj, and the full bandwidth being saturated.

#### Run the command 'rclone version' and share the full output of the command.

rclone  version
rclone v1.59.0
- os/version: linuxmint 20.3 (64 bit)
- os/kernel: 5.15.0-33-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.18.3
- go/linking: static
- go/tags: none

####  Which cloud storage system are you using? (eg Google Drive)

storj for upload. google drive for download. its the upload that I am trying to control here.

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)  

```
rclone sync -v --bwlimit "08:00,0.2M:off 23:00,off:off" --human-readable --transfers=2 --progress --log-file ~/Apps/rclone/rclone.log gdrive: storj:bucket

rclone sync -v --bwlimit "08:00,200:off 23:00,off:off" --human-readable --transfers=2 --progress --log-file ~/Apps/rclone/rclone.log gdrive: storj:bucket

rclone sync -v --bwlimit "08:00,0.2M 23:00:off" --human-readable --transfers=2 --progress --log-file ~/Apps/rclone/rclone.log gdrive: storj:bucket

rclone sync -v --bwlimit 0.2M:off --human-readable --transfers=2 --progress --log-file ~/Apps/rclone/rclone.log gdrive: storj:bucket

rclone sync -v --bwlimit 0.2M --human-readable --transfers=2 --progress --log-file ~/Apps/rclone/rclone.log gdrive: storj:bucket

```

#### The rclone config contents with secrets removed.  

```
[gdrive]
type = drive
client_id = x
client_secret = y
scope = drive.readonly
service_account_file = 
team_drive = 
root_folder_id = a
token = b

[storj]
type = storj
access_grant = x

```

#### A log from the command with the `-vv` flag  

```
2022/07/25 18:33:48 INFO  : Starting bandwidth limiter at 204.800Ki Byte/s
2022/07/25 18:33:48 DEBUG : rclone: Version "v1.59.0" starting with parameters ["rclone" "sync" "-vv" "--bwlimit" "0.2M" "--human-readable" "--transfers=2" "--progress" "--log-file" "/home/x/Apps/rclone/rclone.log" "gdrive:" "storj:bucket"]
2022/07/25 18:33:48 DEBUG : Creating backend with remote "gdrive:"
2022/07/25 18:33:48 DEBUG : Using config file from "/home/x/.config/rclone/rclone.conf"
2022/07/25 18:33:48 DEBUG : Creating backend with remote "storj:bucket"
```

The rest of the log is file comparison and directory listings, with no mention of bandwidth limiting after that startup message.

**Comment by animosity22** [comment]
There's really no log file to indicate any problem though. Can you share than a few seconds to show the issue?

**Comment by theretohere** [comment]
I dont see anything related to bandwidth in the rclone log after that starup log message. The files are many GB large, so if there is any other mention to bandwidth on completion, it hasnt happened yet.

The issue is seen on the system monitor and router bandwidth graphs.

Full upload bandwidth is used with storj. 

Even in this single command line downloading from google drive and uploading to storj, google is being throttled at 200k but storj is not.

**Comment by animosity22** [comment]
Can you share more than a few seconds of the log please?

**Comment by ncw** [comment]
> Setting a bandwidth limit on upload to storj results in no upload limit being set for storj, and the full bandwidth being saturated.

If you are using storj native protocol then there are two things in play here

1. storj doesn't use HTTP transactions so we are relying on the core rate limiter. However the core rate limiter only limits the throughput of the file not the actual transfer to the network
2. storj uploads each part of each file more than once, in the docs it says "a 1gb upload will result in 2.68gb of data being uploaded to storage nodes across the network."

So to make the bandwidth limiter work with storj you need to divide the bandwidth you want by 2.68.

Note also that the bandwidths are in **Bytes**/s

So if you want 1.6Mbit/s upload that is 200 kByte/s and dividing by 2.68 you'd want `--bwlimit 74.6k`

I think that should work.

If it does, it should probably be in the docs!

**Comment by theretohere** [comment]
> If you are using storj native protocol then there are two things in play here
Yes, using storj native protocol.

> 2. storj uploads each part of each file more than once, in the docs it says "a 1gb upload will result in 2.68gb of data being uploaded to storage nodes across the network."
> 
> So to make the bandwidth limiter work with storj you need to divide the bandwidth you want by 2.68.

Is that how the storj multi part upload interacts with the upload file bandwidth core rate limiter? Interesting.

> So if you want 1.6Mbit/s upload that is 200 kByte/s and dividing by 2.68 you'd want `--bwlimit 74.6k`

Good idea. I like where this was going. But unfortunately this doesn't work. It ends up rate limiting the download from google drive, which long term might/will average down the storj upload to the same rate. But the storj upload still maxes out the upload bandwidth, it looks like until the bufffer of the google drive download runs out, then the storj upload speed drops down for a few seconds. Then the storj upload speed goes right back to max. Looks like a buffer being filled, emptying, repeat.

**Comment by ncw** [comment]
> But unfortunately this doesn't work. It ends up rate limiting the download from google drive, which long term might/will average down the storj upload to the same rate.

You can set the upload and download bandwidth limiters differently. with `--bwlimit UP:DOWN` which might help. Note that core bandwidth limiter is set to the minimum of UP and DOWN.

The best strategy might be to only limit the download from google and let the upload bandwidth be 2.7 x the download bandwidth, so `--bwlimit off:200k`

> But the storj upload still maxes out the upload bandwidth, it looks like until the bufffer of the google drive download runs out, then the storj upload speed drops down for a few seconds. Then the storj upload speed goes right back to max. Looks like a buffer being filled, emptying, repeat.

Is this a temporary maxing out the upload bandwidth? When I tried it the rate limiting seemed to work OK.

What is your objective here - to keep long term average bandwidth under some limit or to keep bandwidth usage below some limit always. The core bandwidth limiter is good at long term average, but the edge (http bandwidth limiters) are needed for the fine control.

Can you share what bandwidth settings you've set and what bandwidths you are measuring please?

**Comment by theretohere** [comment]
> You can set the upload and download bandwidth limiters differently. with `--bwlimit UP:DOWN` which might help. Note that core bandwidth limiter is set to the minimum of UP and DOWN.

That is included in the variations of command lines that were tried. Please see command lines above. 

 
> The best strategy might be to only limit the download from google and let the upload bandwidth be 2.7 x the download bandwidth, so `--bwlimit off:200k`

That is what I did. Please see last comment.

 
> Is this a temporary maxing out the upload bandwidth? When I tried it the rate limiting seemed to work OK.

Yes, the full upstream bandwidth to the internet is maxed out for a few seconds, then drops down low. Then repeats until the transfer completes.

 
> What is your objective here - to keep long term average bandwidth under some limit or to keep bandwidth usage below some limit always. The core bandwidth limiter is good at long term average, but the edge (http bandwidth limiters) are needed for the fine control.

Objective is to rate limit the the upload traffic to always stay under a set amount for storj transfers. rclone does this as expected with google drive.

 
> Can you share what bandwidth settings you've set and what bandwidths you are measuring please?

Bandwidth settings are same as above in the ticket:

```
rclone sync -v --bwlimit "08:00,0.2M:off 23:00,off:off" --human-readable --transfers=2 --progress --log-file ~/Apps/rclone/rclone.log gdrive: storj:bucket

rclone sync -v --bwlimit "08:00,200:off 23:00,off:off" --human-readable --transfers=2 --progress --log-file ~/Apps/rclone/rclone.log gdrive: storj:bucket

rclone sync -v --bwlimit "08:00,0.2M 23:00:off" --human-readable --transfers=2 --progress --log-file ~/Apps/rclone/rclone.log gdrive: storj:bucket

rclone sync -v --bwlimit 0.2M:off --human-readable --transfers=2 --progress --log-file ~/Apps/rclone/rclone.log gdrive: storj:bucket

rclone sync -v --bwlimit 0.2M --human-readable --transfers=2 --progress --log-file ~/Apps/rclone/rclone.log gdrive: storj:bucket
```
When google drive is the source and storj is the target, bandwidth measured at the router for the outgoing connections shows a few seconds at peak bandwidth outgoing, then drops down to almost nothing, then repeats until the file transfer completes. Incoming bandwidth is perfectly level at the set --bwlimit.

When google drive is the source and the target, the bandwidth used is almost perfectly level at the set --bwlimit for both ingress and egress.

**Comment by ncw** [comment]
> Objective is to rate limit the the upload traffic to always stay under a set amount for storj transfers. rclone does this as expected with google drive.

Unfortunately, with storj, the bandwidth limiter will only be accurate long term, and may well include large peaks.

You can try setting the limit lower.

However if you want a more accurate rate limit, then we either need to plumb rclone's rate limiting into the SDK (which probably is possible as it exposes a `DialContext` option).

You could alternatively use the Storj S3 gateway which will work correctly with the bandwidth limiter, and has the advantage that you only upload the data once rather than 3 times.

**Comment by bitcoinmeetups** [comment]
Storj normally encrypts everything, right? Does it also encrypt S3 type storage automatially?

**Comment by ncw** [comment]
> Storj normally encrypts everything, right?

Yes it does

> Does it also encrypt S3 type storage automatially?

You have to give the S3 gateway the password, but yes it does.

**Comment by brodyhoskins** [comment]
What is the solution to this issue? This problem is still happening in `rclone` 1.67.0. Setting the `--bwlimit` to any suggested value above has no effect.

**Comment by ncw** [comment]
The bandwidth limiting for rclone will work over a long term average. Set the input bandwidth limit to 1/2.68 the desired bandwidth as detailed here https://github.com/rclone/rclone/issues/6342#issuecomment-1195275779 - this will only work for long term bandwidth limiting.

You can also use the Storj S3 gateway where the bandwidth limiting will work properly and you will only upload data 1:1 not 1:2.68

I don't think there is anything rclone can do about this as the Storj module does not take an http Transport which means rclone can't apply rate limiting when sending, only when receiving from the source remote.

**Comment by brodyhoskins** [comment]
@ncw Is there a reason this isn't being implemented for the native Storj remote? I don't want to set up an S3 gateway only for bandwidth limiting.

I can confirm that over the past few weeks, the long term average is _not_ respecting `--bwlimit` as the link remains saturated for the entirety of the operation.

**Comment by ncw** [comment]
@brodyhoskins the storj library itself needs to apply the bandwidth limiting. Ideally it would take an `http.Transport` to configure it, but I think it may not use HTTP.

> I can confirm that over the past few weeks, the long term average is _not_ respecting `--bwlimit` as the link remains saturated for the entirety of the operation.

If I use

    rclone copy --bwlimit 100k -P /tmp/100M TestStorj:rclone/

I can see the read rate is limited to 100 kBytes/s. The output bandwidth should be about 2.5 x this so averages approx 250 kByte/s. However it is very peaky - it peaks to full line speed and back to 0.

Here is a bandwidth graph made with speedometer while using the above rclone command. You can see the peaks and you can see the average in the bottom right at about 355 kByte/s so a bit higher than the expected 250 KByte/s.

![image](https://github.com/user-attachments/assets/22411923-11ec-49c0-a75f-3a401da03b7d)
