### ISSUE TITLE
Rclone Error:failed to configure OneDrive:empty token found / Couldn't decode response - try again

### ISSUE THREAD

**Issue by realpg** [rclone/rclone#6346]
Everyone who use onedrive headless remote auth must have this problem.

All rclone versions do not accept tokens large than 4096 bytes.

Before 1.56, the authorize code haven't encoded, for a onedrive remote auth, 4096 is enough.

After 1.56, the authorize code are encoded. For a onedrive remote auth , it's not enough. Most onedrive remote auth codes are larger than 4096 bytes.

Plz fix this.

**Comment by animosity22** [comment]
Duplicate of

https://github.com/rclone/rclone/issues/5630

**Comment by realpg** [comment]
> Duplicate of
> 
> #5630

But in #5630, no one try to fix this, in years.
It's just a joke.
`user downgraded, so nothing happenned.`
