### ISSUE TITLE
Google Photos error quota exceeded without even using it

### ISSUE THREAD

**Issue by awojtas** [rclone/rclone#6357]
#### What is the problem you are having with rclone?
I tried to use rclone, first time ever, following the steps in this guide: https://rclone.org/googlephotos/

#### What is your rclone version (output from `rclone version`)
v1.59

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 10 Pro 21H2 64-bit

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Photos

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone config (worked)
rclone lsd GooglePhotos:album (429 error)

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
Error received was: 
ERROR : : error listing: couldn't list albums: Quota exceeded for quota metric 'All requests' and limit 'All requests per day' of service 'photoslibrary.googleapis.com' for consumer 'project_number:202264815644'. (429 RESOURCE_EXHAUSTED)
2022/08/03 18:43:32 Failed to lsd with 2 errors: last error was: couldn't list albums: Quota exceeded for quota metric 'All requests' and limit 'All requests per day' of service 'photoslibrary.googleapis.com' for consumer 'project_number:202264815644'. (429 RESOURCE_EXHAUSTED)
Screenshot:
![image](https://user-images.githubusercontent.com/3030232/182542146-0d6e31fe-0328-471c-a89d-16570bfeeb2c.png)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
That's how Google works unfortunately.

There's nothing to do but wait for the quota to reset or make your own client ID/secret and use that.

See -> https://rclone.org/drive/#making-your-own-client-id

Please use the forums for general support help.

Thanks!

**Comment by awojtas** [comment]
Thank you, that solved it. After following the steps in the link, I also needed to enable the "Photos Library API", and then it worked immediately.
