### ISSUE TITLE
Add option to NOT preserve modification time on files

### ISSUE THREAD

**Issue by kevinnoel-be** [rclone/rclone#6368]
#### The associated forum post URL from `https://forum.rclone.org`
Found a similar ask here: https://forum.rclone.org/t/how-can-i-not-preserve-file-timestamps/14904

#### What is your current rclone version (output from `rclone version`)?
```
rclone v1.58.1
- os/version: alpine 3.15.4 (64 bit)
- os/kernel: 5.4.202+ (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.18.1
- go/linking: static
- go/tags: none
```

#### What problem are you are trying to solve?
A tool we're using requires dynamically generated files to run. We've been generating those files in an object storage (S3/GCS) for sharing across different executors (containers) and are sync'ing those files every 5 min locally so they can be picked up by said tool. The tool uses modification time to detect changes so even if the files did get synced (create/update) they are not getting picked up. 
We've ended up using an ugly `touch -m *` to work around this. Also, not using mounts as we're running in containers as non-privileged user.

#### How do you think rclone should be changed to solve that?
Adding a new option as flag something like `--no-preserve-mod-time` or similar so the synced files (created/updated) are getting the sync time (now) vs the source mod-time.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> We've been generating those files in an object storage (S3/GCS) for sharing across different executors (containers) and are sync'ing those files every 5 min locally so they can be picked up by said tool.

Presumably if the tool sets the modification times, then when they are updated, they will be synced and the modification times will change.

Anyway, here is the setting you want

      --local-no-set-modtime          Disable setting modtime

You'll want to use `--checksum` with your syncs otherwise rclone will copy the files every time.

**Comment by kevinnoel-be** [comment]
Oops, I thought I had gone through all of the flags 😕 
Thanks for the tool & the help!
