### ISSUE TITLE
Extremely low speed between 1Fichier and gdrive

### ISSUE THREAD

**Issue by Sei969** [rclone/rclone#6371]
#### What is the problem you are having with rclone?

Hello, I use RClone to copy files remotely between 1Fichier and Google Drive but the transfer speed is extremely low (maximum 3.5 MiB/s).

#### What is your rclone version (output from `rclone version`)

rclone v1.59.0
- os/version: Microsoft Windows 10 Home 21H1 (64 bit)
- os/kernel: 10.0.19043.1826 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.18.3
- go/linking: static
- go/tags: cmount

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Microsoft Windows 10 Home 21H1 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)

1Fichier, Google Drive.

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone copy -P "1Fichier:/folder/myfile" "gdrive:/folder2" --drive-chunk-size 256M -vv

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

2022/08/09 16:56:42 DEBUG : Creating backend with remote "1Fichier:/folder/myfile"
2022/08/09 16:56:42 DEBUG : Using config file from "\rclone.conf"
2022/08/09 16:56:44 DEBUG : fs cache: adding new entry for parent of "1Fichier:/folder/myfile", "1Fichier:folder"
2022/08/09 16:56:44 DEBUG : Creating backend with remote "gdrive:/folder2"
2022/08/09 16:56:44 DEBUG : gdrive: detected overridden config - adding "{A6J6b}" suffix to name
2022/08/09 16:56:44 DEBUG : Google drive root 'folder2': 'root_folder_id = 0AIOokVZo4U6hUk9PVA' - save this in the config to speed up startup
2022/08/09 16:56:44 DEBUG : fs cache: renaming cache item "gdrive:/folder2" to be canonical "gdrive{A6J6b}:folder2"
2022-08-09 16:56:45 DEBUG : myfile: Need to transfer - File not found at Destination
2022-08-09 16:56:56 INFO  : myfile: Copied (new)
Transferred:        2.352 MiB / 2.352 MiB, 100%, 241.270 KiB/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:        13.2s
2022/08/09 16:56:56 INFO  :
Transferred:        2.352 MiB / 2.352 MiB, 100%, 241.270 KiB/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:        13.2s

2022/08/09 16:56:56 DEBUG : 5 go routines active

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Please use the forums for general support stuff.

https://forum.rclone.org/
