### ISSUE TITLE
ISP throttles my storj connection (uplink or rclone). Any workaround?

### ISSUE THREAD

**Issue by bitcoinmeetups** [rclone/rclone#6375]
Hello,

I'm BM. A very nice and polite guy.

It seems like my ISP throttles my storj connection (uplink or rclone). Any workaround?

If I try to upload a large file for testing purposes I will go from 2MB/s to 1.5 MB/s and all the way to zero. Then I get cut off from the Internet temporarily. Perhaps this due to the large amount of TCP connections.

Anyone knows how to fix this?

**Comment by animosity22** [comment]
For general use questions, please use the forums instead.

https://forum.rclone.org/

Thanks!
