### ISSUE TITLE
GDrive: Copy folder/file by ID - Not flag

### ISSUE THREAD

**Issue by norm-git** [rclone/rclone#6377]
#### What is your current rclone version (output from `rclone version`)?

v1.59.1 - 2022-08-08

#### What problem are you are trying to solve?

Not being able to copy easily because the copy is currently made via the specified path

#### How do you think rclone should be changed to solve that?

I think the best way is to copy via id directly. No, I'm not talking about the root-folder-id flag, it's something that doesn't work properly.
So, like, 
**remote:"paste here id source"** **remote:"paste here id dest"**
The easiest way is this, i think

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Check out:

https://github.com/rclone/rclone/issues/3625

Closing as a duplicate.
