### ISSUE TITLE
s3: rclone copy with errors "multipart upload failed to finalise: InvalidRange" when both storage backend is ceph s3

### ISSUE THREAD

**Issue by zhucan** [rclone/rclone#6386]
#### What is the problem you are having with rclone?
2022/08/19 11:27:33 ERROR : DR_MKZ_1_20220414_212047.BuildMap.bag: Failed to copy: multipart upload failed to finalise: InvalidRange: 
	status code: 416, request id: tx0000000000000005f645a-0062ff7395-c7a4f8-et_uos_master_zone, host id: 
2022/08/19 11:27:33 ERROR : Attempt 1/3 failed with 1 errors and: multipart upload failed to finalise: InvalidRange: 
	status code: 416, request id: tx0000000000000005f645a-0062ff7395-c7a4f8-et_uos_master_zone, host id: 
2022/08/19 11:27:33 DEBUG : DR_MKZ_1_20220414_212047.BuildMap.bag: Need to transfer - File not found at Destination

#### What is your rclone version (output from `rclone version`)
v1.59.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
centos7.8

#### Which cloud storage system are you using? (e.g. Google Drive)
ceph s3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
ceph:dataocean-prod-05//data/base/SentryData/2022/04/20/09/DR_MKZ_1_20220414_212047.BuildMap/bag/DR_MKZ_1_20220414_212047.BuildMap.bag ceph1:dataocean-prod-trip-operation-2//data/base/SentryData/2022/04/20/09/DR_MKZ_1_20220414_212047.BuildMap/bag/DR_MKZ_1_20220414_212047.BuildMap.bag --log-file /var/log/dataocean-prod-05.log --checkers 128 --transfers 64 --log-level DEBUG

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

2022/08/19 10:12:01 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/08/19 10:12:07 INFO  :
Transferred:       64.451 GiB / 64.451 GiB, 100%, 59.602 MiB/s, ETA 0s
Transferred:            0 / 1, 0%
Elapsed time:      16m0.0s
Transferring:
 *         DR_MKZ_1_20220414_212047.BuildMap.bag:100% /64.451Gi, 59.419Mi/s, 0s

2022/08/19 10:12:19 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/08/19 10:12:19 DEBUG : HTTP RESPONSE (req 0xc000fde500)
2022/08/19 10:12:19 DEBUG : HTTP/1.1 204 No Content^M
Connection: Keep-Alive^M
Date: Fri, 19 Aug 2022 10:12:19 GMT^M
X-Amz-Request-Id: tx0000000000000005eef17-0062ff61f1-c7a4f8-et_uos_master_zone^M
^M
2022/08/19 10:12:19 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/08/19 10:12:19 ERROR : DR_MKZ_1_20220414_212047.BuildMap.bag: Failed to copy: multipart upload failed to finalise: InvalidRange:
        status code: 416, request id: tx0000000000000005eef16-0062ff61f1-c7a4f8-et_uos_master_zone, host id:
2022/08/19 10:12:19 ERROR : Attempt 1/3 failed with 1 errors and: multipart upload failed to finalise: InvalidRange:
        status code: 416, request id: tx0000000000000005eef16-0062ff61f1-c7a4f8-et_uos_master_zone, host id:
2022/08/19 10:12:19 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/08/19 10:12:19 DEBUG : HTTP REQUEST (req 0xc000fde900)
2022/08/19 10:12:19 DEBUG : HEAD /dataocean-prod-05//data/base/SentryData/2022/04/20/09/DR_MKZ_1_20220414_212047.BuildMap/bag/DR_MKZ_1_20220414_212047.BuildMap.bag HTTP/1.1^M
Host: 10.3.2.6:7480^M
User-Agent: rclone/^M
Authorization: XXXX
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855^M
X-Amz-Date: 20220819T101219Z^M
^M
2022/08/19 10:12:19 DEBUG : >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
2022/08/19 10:12:19 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022/08/19 10:12:19 DEBUG : HTTP RESPONSE (req 0xc000fde900)
2022/08/19 10:12:19 DEBUG : HTTP/1.1 200 OK^M
Content-Length: 69204075773^M
Accept-Ranges: bytes^M
Connection: Keep-Alive^M
Content-Type: binary/octet-stream^M
Date: Fri, 19 Aug 2022 10:12:19 GMT^M
Etag: "29b26b3ae38ad557310ed8d14b12c3a5-2200"^M

**Comment by zhucan** [comment]
@ncw

**Comment by sebastienbonami** [comment]
I have a similar issue, any solution that was found?

**Comment by zhucan** [comment]
@sebastienbonami Please check the "default max part" of ceph s3, out of the max value.

**Comment by ncw** [comment]
@zhucan did you manage to fix this by adjusting CEPH? Can you explain what you did? Thanks.

**Comment by zhucan** [comment]
@ncw adjust ceph config or adjust s3 chunksize. because of the "rgw_multipart_part_upload_limit" of ceph is 10000, so we can upload the file can not beyond 50GB if we use the default chunksize.

```
[root@node01 deeproute]# ceph config get mon  rgw_multipart_part_upload_limit
10000
```

**Comment by ncw** [comment]
@zhucan we have a workaround for this for scaleway - do you think we should make this the default for the Ceph provider too?

https://github.com/rclone/rclone/blob/34333d9fa8cd0c8b9bd37fe853ccc3d319109e6b/backend/s3/s3.go#L2813-L2817

Rclone will adjust its chunk size to stay within that limit.

**Comment by zhucan** [comment]
no needed, because of we support "--s3-upload-concurrency",  no needed to limit the max parts. @ncw

**Comment by ncw** [comment]
> no needed, because of we support "--s3-upload-concurrency", no needed to limit the max parts.

@zhucan what value did you use? How does that help?

**Comment by zhucan** [comment]
32 or 128, The max limit value of the "--s3-upload-concurrency" is? but we can not controller the custom to limit the value if the cpu and mem is enough. @ncw

**Comment by sebastienbonami** [comment]
Thanks for the help. I don't understand though why we're talking about the "--s3-upload-concurrency" option. Is it not "--s3-chunk-size" that should be increased instead to avoid the mentioned issue?

**Comment by ncw** [comment]
@sebastienbonami most likely using this with a parameter of `1000` is the correct fix (or the config file equivalent `max_upload_parts`).

      --s3-max-upload-parts int   Maximum number of parts in a multipart upload (default 10000)

What do you think of the comment here https://github.com/rclone/rclone/issues/6386#issuecomment-1416112696 ?

**Comment by sebastienbonami** [comment]
If rclone option `s3-max-upload-parts` and ceph option `rgw_multipart_part_upload_limit` are both 10000, then I would expect it should be fine. In my case I can't confirm the `rgw_multipart_part_upload_limit` value of the server I'm using so I'm assuming it's 10000.

I'm trying to upload a 100GB file. Leaving all rclone options by default, it fails with the last chunk being number 9310.

Right now, I'm trying with `--s3-max-upload-parts 1000`, will let you know how it goes.

**Comment by sebastienbonami** [comment]
Simply using `--s3-max-upload-parts 1000` has fixed the issue for me.

@ncw About https://github.com/rclone/rclone/issues/6386#issuecomment-1416112696, well I would say it's a good idea for sure as we want to avoid other people from encountering the same issue. Though I don't know what the maximum value can be, I can only say that 1000 worked with the Ceph server I'm using. Thanks.
