### ISSUE TITLE
[404 - DiskNotFoundError] Resource not found with long(?) Cyrillic file names and CRYPT remote

### ISSUE THREAD

**Issue by max-dw-i** [rclone/rclone#6388]
#### What is the problem you are having with rclone?

I use Yandex Disk with crypt remote over it. If I try uploading a file with long Cyrillic name like `А абвгд абвгдежзик абвгдежзиклм абвгдежз абвгдежзи абвгдежзик абвгдежзика.html`, I get an error.
A file with one less character in the name is uploaded (eg. `А абвгд абвгдежзик абвгдежзиклм абвгдежз абвгдежзи абвгдежзик абвгдежзик.html`).
A file with the same name length (or even longer) but using the Latin alphabet (eg. `A abcde abcdefghij abcdefghijkl abcdefgh abcdefghi abcdefghij abcdefghijklm.html`) is good.
If I make shorter the whole path and not the file name itself, again - error. So the problem with the Cyrillic file name length specifically.
If I upload a file with a Cyrillic file name directly to Yandex Disk (not using the crypt remote), everything's fine.
I had a look at the [docs](https://rclone.org/crypt/) (File name encryption modes) and figured out that the max file name length is 143 characters but my example's length is less. Even the whole path length is less. And again using the Latin alphabet is fine.
So I guess there's some problem with the combination of the crypt remote and long Cyrillic file names.

#### What is your rclone version (output from `rclone version`)

rclone v1.57.0-DEV

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

fedora 36 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)

Yandex Disk with Crypt remote

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone sync -vv "/home/user/А абвгд абвгдежзик абвгдежзиклм абвгдежз абвгдежзи абвгдежзик абвгдежзика.html" ya_crypt:

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2022/08/20 14:48:55 DEBUG : rclone: Version "v1.57.0-DEV" starting with parameters ["rclone" "sync" "-vv" "/home/user/А абвгд абвгдежзик абвгдежзиклм абвгдежз абвгдежзи абвгдежзик абвгдежзика.html" "ya_crypt:"]
2022/08/20 14:48:55 DEBUG : Creating backend with remote "/home/user/А абвгд абвгдежзик абвгдежзиклм абвгдежз абвгдежзи абвгдежзик абвгдежзика.html"
2022/08/20 14:48:55 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2022/08/20 14:48:55 DEBUG : fs cache: adding new entry for parent of "/home/user/А абвгд абвгдежзик абвгдежзиклм абвгдежз абвгдежзи абвгдежзик абвгдежзика.html", "/home/user"
2022/08/20 14:48:55 DEBUG : Creating backend with remote "ya_crypt:"
2022/08/20 14:48:55 DEBUG : Creating backend with remote "ya:backup"
2022/08/20 14:48:56 DEBUG : А абвгд абвгдежзик абвгдежзиклм абвгдежз абвгдежзи абвгдежзик абвгдежзика.html: Need to transfer - File not found at Destination
2022/08/20 14:48:56 ERROR : А абвгд абвгдежзик абвгдежзиклм абвгдежз абвгдежзи абвгдежзик абвгдежзика.html: Failed to copy: [404 - DiskNotFoundError] Resource not found.
2022/08/20 14:48:56 ERROR : Attempt 1/3 failed with 1 errors and: [404 - DiskNotFoundError] Resource not found.
2022/08/20 14:48:56 DEBUG : А абвгд абвгдежзик абвгдежзиклм абвгдежз абвгдежзи абвгдежзик абвгдежзика.html: Need to transfer - File not found at Destination
2022/08/20 14:48:57 ERROR : А абвгд абвгдежзик абвгдежзиклм абвгдежз абвгдежзи абвгдежзик абвгдежзика.html: Failed to copy: [404 - DiskNotFoundError] Resource not found.
2022/08/20 14:48:57 ERROR : Attempt 2/3 failed with 1 errors and: [404 - DiskNotFoundError] Resource not found.
2022/08/20 14:48:57 DEBUG : А абвгд абвгдежзик абвгдежзиклм абвгдежз абвгдежзи абвгдежзик абвгдежзика.html: Need to transfer - File not found at Destination
2022/08/20 14:48:58 ERROR : А абвгд абвгдежзик абвгдежзиклм абвгдежз абвгдежзи абвгдежзик абвгдежзика.html: Failed to copy: [404 - DiskNotFoundError] Resource not found.
2022/08/20 14:48:58 ERROR : Attempt 3/3 failed with 1 errors and: [404 - DiskNotFoundError] Resource not found.
2022/08/20 14:48:58 INFO  : 
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         3.0s

2022/08/20 14:48:58 DEBUG : 5 go routines active
2022/08/20 14:48:58 Failed to sync: [404 - DiskNotFoundError] Resource not found.
```

**Comment by animosity22** [comment]
I'm doubtful it'll matter much, but can you test on the latest stable? 1.59.1? Seems like a unicode type issue.

**Comment by oratosquilla-oratoria** [comment]
Sadly, absolutely the same behaviour with 1.59.1

**Comment by reyaz006** [comment]
Having this issue with Japanese file names. It would seem like file name encryption does absolutely not like non-ANSI character sets? Thought it should've been Unicode-friendly.

**Comment by ncw** [comment]
The problem here is that the Cyrillic and Japanese characters are longer when encoded as utf-8. Typically a Cyrillic character will take 2 UTF-8 bytes. Not sure about Japanese characters but it will be at least 2 bytes.

The base32768 encoding helps a lot on OneDrive and Dropbox. Not sure about other backends. The base64 encoding will help a bit on all backends.

I'm going to close this sincere it isn't something we can fix in rclone.
