### ISSUE TITLE
Force sync "clean up"

### ISSUE THREAD

**Issue by DarrenPIngram** [rclone/rclone#6392]
#### What is your current rclone version (output from `rclone version`)?

1.59.1

#### What problem are you are trying to solve?

Would be nice to have a "force resync clean" feature, meaning that the source is compared to 100% on destination (remote) and anything not present on the remote is added and anything present on the remote that should not be is deleted.

I appreciate this is what sync should be, but in some sporadic cases I've found where this is not (at least "old" stuff left in remote (never have tracked down the "why" as it is noticed long after the event). Thus an occasional "clean", even of very large datastores would be nice.

#### How do you think rclone should be changed to solve that?

I presume a slight extension to the sync behaviour, possible an extra flag or something, but I would not suggest how it may be achieved. Especially if regular sync should be picking this up.

If there is such a problem, whether a compare could be easily made (compare remote to source) and delete/flag to delete could be one way.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
A sync would mirror A to B and clean up anything needed.

What isn't happening in that scenario that you are asking for? i can't figure out why another flag is needed.

**Comment by animosity22** [comment]
It already does that so not sure why another command/flag would be needed.

If it's not, you'd have to share a log/etc to answer the question of why as you'd have found a bug perhaps.

**Comment by animosity22** [comment]
That already exists as you can do --dry-run to see what will happen.

If you re-run a sync, it does the whole remote every time as that's how sync works.

A is mirrored to B.

**Comment by animosity22** [comment]
Sync is one direction. A-> B

If you an issue with something not doing what you'd expect, you'd want to share all the details for a bug report with a log file of the issue.

If you want to go two directions, check out -> https://rclone.org/bisync/

**Comment by animosity22** [comment]
The internet is always a great place as I'm volunteering my time and trying to figure out your question, help you out and you want to go with insulting me for trying to do that. 

Please raise your issue on the forums as someone else might help you out:

https://forum.rclone.org/

**Comment by Masamune3210** [comment]
You don't, go to the forum like you were told and ask for help there. People arent exactly the most accepting when they are being insulted.....
