### ISSUE TITLE
Google Photos backend hanging after corpus has grown sufficiently large

### ISSUE THREAD

**Issue by uqs** [rclone/rclone#6394]
#### What is the problem you are having with rclone?
I'm using rclone to sync photos from local storage into Google Photos and I'm only interested in a one-way sync (but including deletes). This was working fine in filling a backlog of photos over the last year or so.

I now have 300+GB of photos on Google Photos, but after adding a couple thousand more photos to upload, rclone now simply "hangs" when syncing. It is making no more progress, but still posts it's progress update every once in a while and after 72h or so it sometimes exits.

The same can be reproduced simply by using `rclone ls -v -v -v -v -v remote:album`. It will run and make sufficient progress, and then it enters this loop:

```
2022/08/22 13:19:47 DEBUG : 2015-03--05/some file.jpg: Size: 
2022/08/22 13:19:47 DEBUG : 2015-03--05/some file.jpg: >Size: 
       -1 2015-03--05/some file.jpg
2022/08/22 13:27:22 DEBUG : remote: Loaded invalid token from config file - ignoring
2022/08/22 13:27:23 DEBUG : Saving config "token" in section "remote" of the config file
2022/08/22 13:27:23 DEBUG : remote: Saved new token in config file
2022/08/22 14:27:12 DEBUG : remote: Loaded invalid token from config file - ignoring
2022/08/22 14:27:12 DEBUG : Saving config "token" in section "remote" of the config file
2022/08/22 14:27:12 DEBUG : remote: Saved new token in config file
2022/08/22 15:27:01 DEBUG : remote: Loaded invalid token from config file - ignoring
2022/08/22 15:27:02 DEBUG : Saving config "token" in section "remote" of the config file
2022/08/22 15:27:02 DEBUG : remote: Saved new token in config file
2022/08/22 16:01:43 DEBUG : pacer: low level retry 1/10 (error read tcp [XX:XX:XX::1]:31653->[2a00:1450:400a:802::200a]:443: read: connection reset by peer)
2022/08/22 16:01:43 DEBUG : pacer: Rate limited, increasing sleep to 1.428416024s
2022/08/22 16:01:43 DEBUG : pacer: Reducing sleep to 0s
2022/08/22 16:26:51 DEBUG : remote: Loaded invalid token from config file - ignoring
2022/08/22 16:26:51 DEBUG : Saving config "token" in section "remote" of the config file
2022/08/22 16:26:51 DEBUG : remote: Saved new token in config file
2022/08/22 17:26:40 DEBUG : remote: Loaded invalid token from config file - ignoring
2022/08/22 17:26:40 DEBUG : Saving config "token" in section "remote" of the config file
2022/08/22 17:26:40 DEBUG : remote: Saved new token in config file
2022/08/22 18:26:29 DEBUG : remote: Loaded invalid token from config file - ignoring
2022/08/22 18:26:29 DEBUG : Saving config "token" in section "remote" of the config file
2022/08/22 18:26:29 DEBUG : remote: Saved new token in config file
```
Is there a way to further increase the log level?

Running `lsd` is not affected, I guess because the volume of data is small.

#### What is your rclone version (output from `rclone version`)

```
% rclone --version
rclone v1.58.1-DEV
- os/version: freebsd 13.1-stable (64 bit)
- os/kernel: 13.1-stable (amd64)
- os/type: freebsd
- os/arch: amd64
- go/version: go1.18.3
- go/linking: dynamic
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

FreeBSD, 64bit

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Photos

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone ls -v -v -v -v -v remote:album

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

see relevant output above.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Can you try with the latest stable? 1.59.1?

That seems like you have a network issue based on the logs.

**Comment by uqs** [comment]
It's definitely not a network issue, note that it was already stuck for 2.5h before the connection was reset. Running truss on the process shows that it's still busy sending/receiving data.

A cleartext dump of the chat between rclone and Google would help, I guess.

1.59.0 was easily available, and I'm re-running with that one. It will take an hour or more to slog through all photos till it's gonna encounter the stuckness. I'll report back tomorrow.

Btw, before I killed the old process, it was at about 2.7GB of RSS, does that sound normal?

Oh, and what's up with the pacer? Why would it increase and decrease the sleep in the very same second?
```
2022/08/22 20:23:20 DEBUG : pacer: Rate limited, increasing sleep to 2.325779708s
2022/08/22 20:23:20 DEBUG : pacer: Reducing sleep to 0s
```

**Comment by animosity22** [comment]
Google's API for Photos is pretty bad in terms of the API rate limiting.

That does seem like a pretty strange log too as doesn't seem much is happening.

I was just commenting on that one line that is network, but to your point, might be a symptom of something else and not a cause.

**Comment by uqs** [comment]
Ok, it had an RSS of about 400MB when it hit the wall, and it's grown to 1.5GB already.

Time for a Go debugging crash course ... I'll report back later.

**Comment by uqs** [comment]
Some updates, I switched to using my own API key, which does all kinds of strangeness. As it's a new app it can't write to "older" albums, so I would have to re-upload them all, sigh. Anyway, while it throws lots of errors, it does get into this stuck loop pretty quickly and in the Cloud Console I can see that the API it keeps calling (with return code 200 though) is google.photos.library.v1.PhotosLibrary.SearchMediaItems

I also found `--dump-bodies --dump-headers` and have been playing around, but other than exhausting the quota, I have yet to trigger the "stuckness" with these combinations.

**Comment by ncw** [comment]
> I also found `--dump-bodies --dump-headers` and have been playing around, but other than exhausting the quota, I have yet to trigger the "stuckness" with these combinations.

It would be useful to see if an http response is stuck or whether rclone is looping the same or similar http request. The `--dump` options should help with this.

**Comment by uqs** [comment]
As I've written, it is looping google.photos.library.v1.PhotosLibrary.SearchMediaItems seemingly endlessly. I assume this has to do with my use of `sync` and --delete

So I can't really use --dump-bodies, as running `rclone sync` will constantly re-upload (successfully) some of the albums and images. I could imagine what happens is that some of the listing of the remote side is failing or getting throttled, and then rclone thinks that album is not there yet and starts the upload process again.

I'd like to get to a no-op sync first, so that --dump-bodies doesn't splat out 100GB of JPEG and MP4s into my logfile ...

**Comment by ncw** [comment]
You can use `-vv --dump responses` to avoid the binary splat since the binaries are in the requests if you are uploading. That would be helpful to see.

**Comment by uqs** [comment]
Yeah, no, that won't get me the body of the SearchMediaItems _requests_ that it is looping on. The response is some 200, that one I know already, but I'll give it a try, maybe it points to what was requested in the response for that one.

**Comment by uqs** [comment]
Maybe the plot thickens? Till 2014 I had Photos uploaded to Drive, back when those would sync with Photos seamlessly. I found this out, as the photo info showed "uploaded via Drive" instead of the "uploaded by rclone", even after I've deleted the photo from Photos.

So now I've also deleted the photo from Drive (& Photos). Re-uploaded them and they now show "uploaded by rclone" ... but! I still get `rclone sync` wanting to re-upload them over and over again. Why is that? What does "Excluded" mean in the output below?:

```
...
2022/09/07 17:59:03 DEBUG : Google Photos path "album": List: dir="2014-10-02 - Gokart"
...
2022/09/07 17:59:04 DEBUG : 2014-10-02 - Gokart/20141002_205355_Canon EOS 100D.JPG: Size: 
2022/09/07 17:59:04 DEBUG : 2014-10-02 - Gokart/20141002_205355_Canon EOS 100D.JPG: >Size: 
2022/09/07 17:59:04 DEBUG : 2014-10-02 - Gokart/20141002_205355_Canon EOS 100D.JPG: Excluded
2022/09/07 17:59:04 DEBUG : Google Photos path "album": Waiting for checks to finish
2022/09/07 17:59:04 DEBUG : Google Photos path "album": Waiting for transfers to finish
2022/09/07 17:59:04 DEBUG : Google Photos path "album": Put: src=2014-10-02 - Gokart/20141002_205355_Canon EOS 100D.JPG
2022/09/07 17:59:04 DEBUG : 2014-10-02 - Gokart/20141002_205355_Canon EOS 100D.JPG: Update: src=2014-10-02 - Gokart/20141002_205355_Canon EOS 100D.JPG
2022/09/07 17:59:06 DEBUG : 2014-10-02 - Gokart/20141002_205355_Canon EOS 100D.JPG: >Update: err=<nil>
2022/09/07 17:59:06 DEBUG : Google Photos path "album": >Put: 
2022/09/07 17:59:06 DEBUG : 2014-10-02 - Gokart/20141002_205355_Canon EOS 100D.JPG: Size: 
2022/09/07 17:59:06 DEBUG : 2014-10-02 - Gokart/20141002_205355_Canon EOS 100D.JPG: >Size: 
2022/09/07 17:59:06 INFO  : 2014-10-02 - Gokart/20141002_205355_Canon EOS 100D.JPG: Copied (new)
2022/09/07 17:59:06 DEBUG : Waiting for deletions to finish
2022/09/07 17:59:06 INFO  : 
Transferred:        6.084 MiB / 6.084 MiB, 100%, 6.041 MiB/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         4.7s
```

I can run this over and over again and it will re-upload the same file over and over again. Does it think there is a size difference?

**Comment by uqs** [comment]
Oh wow, so after compiling from source and adding some debug prints, I figured out at least on problem. The previously existing files get excluded, because I run with `--min-size=1` because at one point that helped in not uploading 0-sized files. And, well, it worked fine before, but now, (and without using `--gphotos-read-size`, so at the default settings), this somehow excludes some (but not all) the files and causes the re-upload.

Oh, and when running with `--gphotos-read-size` and `--min-size=1`, it sees this discrepancy:
```
2022/09/26 11:10:29 DEBUG : 20220813_122116_Pixel 6.jpg: >Size:                                                                                                 
2022/09/26 11:10:29 DEBUG : 20220813_122116_Pixel 6.jpg: Size:                                                                                                  2022/09/26 11:10:29 DEBUG : 20220813_122116_Pixel 6.jpg: >Size:                                                                                                 2022/09/26 11:10:29 DEBUG : 20220813_122116_Pixel 6.jpg: Size:                                                                                                  2022/09/26 11:10:29 DEBUG : 20220813_122116_Pixel 6.jpg: >Size:                                                                                                 2022/09/26 11:10:29 ERROR : 20220813_122116_Pixel 6.jpg: corrupted on transfer: sizes differ 3333374 vs 2473375                                                 2022/09/26 11:10:29 INFO  : 20220813_122116_Pixel 6.jpg: Removing failed copy                                                                                   
```

This is of course with the setting of "original quality" turned on.

... more testing yet to come, as my combination of flags and filters still seems to cause it to list every destination album in detail, which just takes too frigging long.

**Comment by uqs** [comment]
Sigh, still no luck with the "stuff gets reuploaded all the time". I tried on 1 specific album, and 3 items get constantly reuploaded (I deleted them on photos.google.com, they then come back as "uploaded by rclone", but they don't show up in `rclone ls` ! So another rclone run will copy them as new _again_).

Then I removed them from the Album on photos.google.com, and added them back to the album (easy enough for 3 items), and then the JPGs show up under `rclone ls`, but the MP4 still isn't seen by `rclone ls`. WTF?

It handles other MP4s just fine. Guess I'll wait for a bit for some background encoding to process the file, even though I'm using "original quality" :/

**Comment by uqs** [comment]
Ok, so it's the `--delete-excluded` that causes rclone to "hang" forever, trying to list the full remote contents, which is apparently too much.

Next I'll try a shell loop that loops over all dirs/albums that I want to sync, instead of using `.` as the source.

**Comment by uqs** [comment]
Ok, making progress. When looping over all dirs individually, I found that only on 1 directory or album does it get stuck. For that album, instead of listing the 3k items or so in it, it will never stop listing existing files again!

So clearly this is a bug in Google's API, where it can form a cycle in the pagination of the API. As it does it alphabetically, it should be easy to find the cycle point, but it's not quite so simple. Some sort|uniq -c on the --dump requests/responses log later, I see that pics from Jan/Feb that year are only getting listed once. Some filenames from March are in there 566 times (I aborted the run after 1h or so) but yet some filenames from October are in the 191 times, all of November and December seems to be returned 566 times again.

So it's not quite that it enters a perfect cycle ...

Anyway, this album is cursed. I will try to delete most of it ...

At least this explains why rclone would grow unbounded in memory. I guess it _could_ detect the fact that the API is returning duplicate filenames, but not sure that's worth to fix and flag (and error out accordingly)

**Comment by uqs** [comment]
That fixed it. Deleting the album and re-creating it from scratch avoids the "loop" in `rclone ls` and also then fixes regular `sync` and also `--delete-excluded`.

Not sure that this is a bug in rclone, it might have to be smarter in how to list all items in an album, but it looks more like some metadata got garbled on Google's side.

**Comment by ncw** [comment]
The Google API seems to be a bit broken at the moment. This may be the problem you are seeing here https://github.com/rclone/rclone/issues/6319 - or perhaps it is something different!
