### ISSUE TITLE
mailru backend giving oauth2: server response missing access_token

### ISSUE THREAD

**Issue by martyr83** [rclone/rclone#6398]
cloud mail.ru

rclone lsd -vvv mail:
DEBUG : rclone: Version "v1.59.1" starting with parameters ["rclone" "lsd" "-vvv" "mail:"]
DEBUG : Creating backend with remote "mail:"
DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
INFO  : []: Valid token not found, authorizing.
Failed to create file system for "mail:": failed to authorize: oauth2: server response missing access_token

Stopped working on 08/12/22 when the token ran out.

**Comment by animosity22** [comment]
Did you try to reconnect the remote?

```
rclone config reconnect mail:
```

If that doesn't do it, please open a support request on the forums and use the help and support template.

https://forum.rclone.org/

**Comment by dmak** [comment]
Does it support reconnect?
```
$ rclone config reconnect mail:
Error: backend doesn't support reconnect or authorize
```

**Comment by ncw** [comment]
The integration tests for mail ru started falling in the same way recently.

I think the api must have changed somehow.

Any ideas anyone? @ivandeex ?

**Comment by Alexandrsv** [comment]
figured out the fix
mailru for external applications requires a special password
<details><summary>Go to security</summary>

![image](https://user-images.githubusercontent.com/15097064/198360318-d1b450ed-e61c-47ac-a4ef-b24c4f5146f7.png)

</details>

<details><summary>Password for apps</summary>

![image](https://user-images.githubusercontent.com/15097064/198360522-e98efea4-6b2a-4bb9-82d1-3367d17e8028.png)

</details>

<details><summary>Add</summary>

![image](https://user-images.githubusercontent.com/15097064/198360621-2ecefc89-0ae5-4a35-ae6d-52f2b7b8d61a.png)
generated password works in rclone

</details>

**Comment by positron96** [comment]
Hi @Alexandrsv, the workaround asks to add a phone to the account, did it do that for you?

**Comment by ncw** [comment]
Thank you @Alexandrsv that works well for me.

I've attempted to write some notes up to go in the docs - how does this look?

When I use mail.ru I get it mostly in Russian, but with some bits in English so this may not be exactly what you see.

## Configuration

Here is an example of making a mailru configuration. First create a Mail.ru Cloud
account and choose a tariff.

You will need to log in and create an app password for rclone.

- Click on your user icon in the top right
- Go to Security / "Пароль и безопасность"
- Click password for apps / "Пароли для внешних приложений"
- Add the password - give it a name - eg "rclone"
- Copy the password and use this password below - your normal login password won't work.

Now run

    rclone config

[snip]

**Comment by dmak** [comment]
I confirm that using the application password worked just fine.
