### ISSUE TITLE
You cannot use a full binary value for sse_customer_key

### ISSUE THREAD

**Issue by taxilian** [rclone/rclone#6400]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/cant-use-sse-customer-key-with-non-printable-charactersin-config-file/32667

#### What is your current rclone version (output from `rclone version`)?

tried with v1.56.2 and v1.50.2

#### What problem are you are trying to solve?

There does not seem to be any way to put a non-printable sse_customer_key in the config file -- also, that key should probably be obscured anyway.

#### How do you think rclone should be changed to solve that?

The easiest method that occurs to me is to just allow it to be obscured; since you can obscure a non-printable key and it results in printable characters that should do it. The other option I see would be to detect in some way if it is a base64 encoded value, e.g. "this is longer than 32 bytes and it's an AES256 key, so it must be b64 encoded" or supporting `base64:<b64 encoded customer key>`

Seems like it should be a simple enough change.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Those are old versions did you try on the latest stable?

**Comment by taxilian** [comment]
I have now tested on v1.59.1 (just now installed using the install script from rclone.org) and it does the same thing.

**Comment by taxilian** [comment]
With the help of someone on the forums I was able to find a usable workaround to at least use a binary SSE-C key in the config file. This is in the linked forum post, but you can set it in the config file like so:

```bash
rclone config update yours3remote sse_customer_algorithm AES256 sse_customer_key "$(base64 -d < <(echo 'base64-encoded-string-here'))"
```

For example:
```bash
rclone config update yours3remote sse_customer_algorithm AES256 sse_customer_key "$(base64 -d < <(echo 'zUaljPkMdHujd6xSNvbDQ5L5j8fl/wU55B8dTYV2m6A='))"
```

This updates the config file and does seem to work, but it's definitely not intuitive. It seems like allowing it to be obscured and/or providing a user-editable method would be preferable.  At least there is a usable way to do it, though!

**Comment by olefrost** [comment]
> someone on the forums

That's me :)

**Comment by ncw** [comment]
> There does not seem to be any way to put a non-printable sse_customer_key in the config file

It looks like you got it in the config file eventually with the hack from @olefrost ! Which probably means you could have edited the config file in a text editor to get the key in.

What non-printable chars were in the key?

Was it trying to enter the key in the `rclone config` process that was the problem?

> also, that key should probably be obscured anyway.

What do sse_customer keys generally look like? Can they be `mypassword` - if so then that is a good argument for having them obscured.

Though we have a backwards compatibility problem potentially.

**Comment by taxilian** [comment]
an sse_customer key is any AES256 string -- meaning that it can be literally any 256 bit long (32 byte long) string. While it's probably possible to put the key into the config file using a *hex* editor, I'm more than a little shocked that it worked and I suspect it wouldn't if one of the bytes happened to be, say, a LF character =] Most tools I've found that accept the key in a text field expect it to be base64 encoded.

**Comment by taxilian** [comment]
Also, since it can be any 256 bit string, not only does that mean it can contain lots of characters which are probably not allowed in your config file (presuming there are any, and I'm guessing there are more than just LF but I don't actually know) it also means that any 32 character ASCII string is valid, e.g. `this is my password, secure data` would be valid, as would `12341234123412341234123412341234`

TBH as much as anything I was thinking that being able to obscure it would be an easy way to allow nonprintable characters in there. base64 encoding would probably be fine as well. It's also possible that there is some standard for using strings shorter than 32 characters long (pad with spaces? no idea) but I haven't actually dug into it.

**Comment by taxilian** [comment]
It's also worth noting that the spec allows for keys other than AES256. I don't know of any S3 compatible storage providers which *allow* something other than AES256 (S3 itself definitely doesn't) but it is possible that something could.

I guess another option would be to make a new parameter, something like `sse_customer_key_b64` which if provided is a base64 encoded key that gets translated into the `sse_customer_key` field? Just brainstorming.

**Comment by ncw** [comment]
> an sse_customer key is any AES256 string -- meaning that it can be literally any 256 bit long (32 byte long) string.

I see! It looks like they are passed to AWS as a base64 string.

I don't think we should be jamming binary data in the config file!

> I guess another option would be to make a new parameter, something like `sse_customer_key_b64` which if provided is a base64 encoded key that gets translated into the `sse_customer_key` field? Just brainstorming.

I think that is a good idea and easy to implement. Or it could be hex. How are the keys normally presented to the user? Ideally we'd want something the user can cut and paste.

Obscuring the key probably won't work as the de-obscuring algorithm checks for control characters in the result and throws an error since this is most likely to mean a corrupted key.

**Comment by taxilian** [comment]
> Obscuring the key probably won't work as the de-obscuring algorithm checks for control characters in the result and throws an error since this is most likely to mean a corrupted key.

That makes sense -- it seemed like it might work but I didn't dig to see how your obscure method actually works =]

As to how the keys are normally presented to the user -- I don't have much of a sample size for that question. The tools I have used have all expected that it would be base64 encoded, but since it's a customer-provided key the user generally would provide the key themselves.

I make keys using this command: `openssl rand -base64 32` -- but literally that's just a way of getting 32 random bytes and then base64 encoding it =] I have never seen them passed as hex, but I have only really used it with maybe 3 or 4 different systems at this point. I would expect that base64 encoding is close enough to a "standard" way of doing it that it's good enough, but I also don't feel like I have a broad enough view of the industry to know if that's accurate or not.

**Comment by ncw** [comment]
Base64 seems good. I note that this came up in https://github.com/rclone/rclone/issues/6418 recently for Azure blob storage and they use base64 too.

@taxilian do you want to have a go at implementing this? I can talk you through it if you want?

**Comment by taxilian** [comment]
I'm willing to take a stab at it if you want to point me in the right direction =]

**Comment by ncw** [comment]
First duplicate this configuration

https://github.com/rclone/rclone/blob/bd787e8f457705de9072335fda879f575da4f3cf/backend/s3/s3.go#L1538-L1546

with a `_base64` suffix and write some new help to go with it. The help for the non base64 key could probably do with being updated.

You'll need to add a new line here too

https://github.com/rclone/rclone/blob/bd787e8f457705de9072335fda879f575da4f3cf/backend/s3/s3.go#L2113

Just before this block of code

https://github.com/rclone/rclone/blob/bd787e8f457705de9072335fda879f575da4f3cf/backend/s3/s3.go#L2647-L2651

I'd do something like this (untested)

```go
if opt.SSECustomerKeyBase64 != "" {
    decoded, err := base64.StdEncoding.DecodeString(opt.SSECustomerKeyBase64)
    if err != nil {
        return nil, fmt.Errorf("couldn't decode sse_customer_key_base64: %w", err)
    }
    opt.SSECustomerKey = decoded
}
```

Perhaps error if both opt.SSECustomerKeyBase64 and opt.SSECustomerKey are set.

**Comment by taxilian** [comment]
PR submitted
