### ISSUE TITLE
--checkfile support for COPY command

### ISSUE THREAD

**Issue by QuAzI** [rclone/rclone#6405]
As I can see in -vv rclone calcs checksums for each file anyway. Is it possible to write hashes on the fly (--checkfile checksums) without extra usage of disk?
Right now I see that one of my disks creates badblocks and HDD manufacturer software doesn't provide information to understand which data is corrupted. And I must create copy as fast as possible (in a single run if possible)

**Comment by animosity22** [comment]
There is a hasher backend in testing already for this function so you can use that for writing checksums if that is your goal.

https://rclone.org/hasher/#:~:text=Hasher%20is%20a%20special%20overlay,local%20or%20(S)FTP%20files

Feel free to use the forums for help / general use questions.

https://forum.rclone.org/

**Comment by QuAzI** [comment]
No. Hash as it is is not my goal.
My goal is to safe my data as fast as possible and save hashes as a proof of data safety.
When you split it to two different operations:
- half of users doesn't understand how to properly use it without pain. Or even never seen this features.
- You must spent *2 time (10+ hours *2 it is not fun) and run two different commands. So you can lost more time if second command starts later than first finished.
- Target drive can be a bit broken too and your hashes will be wrong
- Overuse of PC and drives. I don't know why but some technique doesn't like when you use in too much. Mechanical drives more
