### ISSUE TITLE
Directories support for --files-from

### ISSUE THREAD

**Issue by QuAzI** [rclone/rclone#6406]
I have a lot of files on drive D: (Windows). I want to backup some files and directories. But now it is unclear how to do it when --files-from can copy only files and ignores --include/--exclude

**Comment by animosity22** [comment]
Please use the forums for support questions.

https://forum.rclone.org/

**Comment by QuAzI** [comment]
As example
```
rclone copy d: ./backup --filter-from backup_items.list --ignore-case -vv
```
and backup_items.list contains
```
+ /Downloads
+ /Games
+ /Pictures
+ /Music

- **
```

Everything is excluded. Absolutely. If I remove `- **` I will have all unexpected trash in backup
