### ISSUE TITLE
Failed to set permissions on config file

### ISSUE THREAD

**Issue by asdproton** [rclone/rclone#6407]
#### What is the problem you are having with rclone?

rclone log shows 

rclone[27561]: Failed to set permissions on config file: chmod /root/config/.rclone.conf2795095508: no such file or directory

every hour. Apart from that everything seems to work. It started after upgrading to FreeBSD 13.1. It is quite consistent app. 15 minutes after the hour. The PID corresponds to an overrunning rclone mount (same happens with cmount).

#### What is your rclone version (output from `rclone version`)

Happened with 1.59.0 and now with this as well:

- os/version: freebsd 13.1-release-p1 (64 bit)
- os/kernel: 13.1-release-p1 (amd64)
- os/type: freebsd
- os/arch: amd64
- go/version: go1.19
- go/linking: dynamic
- go/tags: cmount
- 

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

FreeBSD 13.1

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

/usr/local/bin/rclone --config=/root/config/.rclone.conf cmount TEST: /data/test --allow-other --dir-cache-time 1000h --syslog --syslog-facility LOCAL5 --log-level INFO --poll-interval 15s --umask 002 --user-agent="TMount" --rc --cache-dir=/mnt/vfscache --vfs-cache-mode full --vfs-cache-max-size 820G --vfs-cache-max-age 9999h  --vfs-read-ahead 1G --buffer-size 100M --disable-http2 --tpslimit 10 --tpslimit-burst 10 --drive-pacer-burst 200 --drive-pacer-min-sleep 10ms --bind 192.168.30.5

Nothing changed with the exception of an upgrade from FreeBSD 13.0 to 13.1.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
For support, it's much easier to use the forums first:

https://forum.rclone.org/

Please use the help and support template and share a debug log as that's the key.

Thanks!
