### ISSUE TITLE
"upload failed: batcher is shutting down" when i tried to copied a large zip file from google drive to dropbox

### ISSUE THREAD

**Issue by kanjvt** [rclone/rclone#6409]
#### What is the problem you are having with rclone?
I copied a large zip file, 11gb. from google drive to dropbox and got the error `upload failed: batcher is shutting down`

I only get this error every time I copy a large zip file

how to solve this error? i am using `rclone v1.59.1` and tried with `rclone v1.60.0-beta.6429.555def2da` and still error

![rclone](https://telegra.ph/file/528915264be73c28d218b.png)
![rclone](https://telegra.ph/file/09a857b034e2bf7817df3.png)

#### What is your rclone version (output from `rclone version`)
```
root@kode666-test-wdflxz5bujn:/workspace/test# rclone version
rclone v1.60.0-beta.6429.555def2da
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.15.0-46-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
ubuntu 20.04 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)
Google drive and dropbox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
im using rclone gui

**Comment by animosity22** [comment]
Can you not use the GUI and make a debug log please? That's the data needed.

**Comment by kanjvt** [comment]
how to debug log sir? can you type command here

**Comment by animosity22** [comment]
That's in the help and support template:

Make sure to include a log obtained with '-vv'.

You can also use '-vv --log-file bug.log' and a service such as https://pastebin.com or https://gist.github.com/

Thank you


You'd run the command with the -vv at the end of it.

rclone copy googledrive:somefile.mkv dropboxremote: -vv

**Comment by animosity22** [comment]
Are you using rclone mounts to? Those seem to be local paths not remotes.

**Comment by kanjvt** [comment]
Of course, I'm using rclone mount, I won't be able to copy the files if it's not mounted first

**Comment by animosity22** [comment]
There's no need to mount if your goal is to copy from one remote to another as it's an unneeded added layer.

**Comment by kanjvt** [comment]
wow really? please correct me. 
```
rclone copy gdrive:/BOT/nematoda folder/ dbox: -vv
```
like this?

**Comment by kanjvt** [comment]
thank you very much sir, it works.

I just found out now, I thought when I want to copy from one remote to another, I should mount it first, apparently I was wrong

I just use this command

```
rclone copy --progress gdrive:upload dbox: -vv
```

```
$ rclone copy --progress gdrive:upload dbox: -vv
2022/08/30 06:54:37 DEBUG : rclone: Version "v1.60.0-beta.6429.555def2da" starting with parameters ["rclone" "copy" "--progress" "gdrive:upload" "dbox:" "-vv"]
2022/08/30 06:54:37 DEBUG : Creating backend with remote "gdrive:upload"
2022/08/30 06:54:37 DEBUG : Using config file from "/home/gitpod/.config/rclone/rclone.conf"
2022/08/30 06:54:37 DEBUG : gdrive: Loaded invalid token from config file - ignoring
2022/08/30 06:54:37 DEBUG : Saving config "token" in section "gdrive" of the config file
2022/08/30 06:54:37 DEBUG : Keeping previous permissions for config file: -rw-r--r--
2022/08/30 06:54:37 DEBUG : gdrive: Saved new token in config file
2022/08/30 06:54:37 DEBUG : Creating backend with remote "dbox:"
2022-08-30 06:54:37 DEBUG : dbox: Loaded invalid token from config file - ignoring
2022-08-30 06:54:38 DEBUG : Saving config "token" in section "dbox" of the config file
2022-08-30 06:54:38 DEBUG : Keeping previous permissions for config file: -rw-r--r--
2022-08-30 06:54:38 DEBUG : dbox: Saved new token in config file
2022-08-30 06:54:38 DEBUG : Dropbox root '': Waiting for checks to finish
2022-08-30 06:54:38 DEBUG : Dropbox root '': Waiting for transfers to finish
2022-08-30 07:02:01 DEBUG : aria2/filem.mp4: Uploading chunk 72/77
2022-08-30 07:02:04 DEBUG : aria2/filem.mp4: Uploading chunk 73/77
2022-08-30 07:02:06 DEBUG : aria2/filem.mp4: Uploading chunk 74/77
2022-08-30 07:02:11 DEBUG : aria2/filem.mp4: Uploading chunk 75/77
2022-08-30 07:02:14 DEBUG : aria2/filem.mp4: Uploading chunk 76/77
2022-08-30 07:02:18 DEBUG : aria2/filem.mp4: Uploading chunk 77/77
2022-08-30 07:02:19 DEBUG : Dropbox root '': Adding "/aria2/filem.mp4" to batch
2022-08-30 07:02:20 DEBUG : Dropbox root '': Batch idle for 500ms so committing
2022-08-30 07:02:20 DEBUG : Dropbox root '': Committing sync batch length 1 starting with: /aria2/filem.mp4
2022-08-30 07:02:21 DEBUG : Dropbox root '': Committed sync batch length 1 starting with: /aria2/filem.mp4
2022-08-30 07:02:21 INFO  : aria2/filem.mp4: Copied (new)
Transferred:       13.547 GiB / 13.547 GiB, 100%, 13.217 MiB/s, ETA 0s
Transferred:            7 / 7, 100%
Elapsed time:      7m44.0s
2022/08/30 07:02:21 INFO  : 
Transferred:       13.547 GiB / 13.547 GiB, 100%, 13.217 MiB/s, ETA 0s
Transferred:            7 / 7, 100%
Elapsed time:      7m44.0s

2022/08/30 07:02:21 DEBUG : 11 go routines active
2022/08/30 07:02:21 INFO  : Dropbox root '': Commiting uploads - please wait...
```

This is very cool

**Comment by animosity22** [comment]
Anything else? If not, you can close it out.

**Comment by kanjvt** [comment]
it's enought, ok sir i will close it, thankyou very much
