### ISSUE TITLE
rclone mounted drive executability problem

### ISSUE THREAD

**Issue by Tewuzij** [rclone/rclone#6417]
#### What is the problem you are having with rclone?
Unable to run excutables [exe,bat,cmd,ps1] on rclone mounted drive
#### What is your rclone version (output from `rclone version`)
1.59.1
#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Microsoft Windows 10 Enterprise 22H2 (64 bit)
10.0.19045.1949 (x86_64)
#### Which cloud storage system are you using? (e.g. Google Drive)
Yandex
#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
mount Yandex: * --vfs-cache-mode full --config=%windir%\rclone.conf -vv --log-file=%windir%\Logs\rcloneYandex.log
#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
In attachment

#### How to use GitHub
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.
[rcloneYandex.log](https://github.com/rclone/rclone/files/9458540/rcloneYandex.log)
![screenshot 1](https://user-images.githubusercontent.com/99064915/187596042-6d4c5759-6baf-4e0d-bf77-6aa7189762df.jpg)

**Comment by Tewuzij** [comment]
[rclone.txt](https://github.com/rclone/rclone/files/9458583/rclone.txt)

**Comment by animosity22** [comment]
See:

https://github.com/rclone/rclone/wiki/how-to-run-.exe-application-on-rclone-mount

Please use the forums for general use questions.
https://forum.rclone.org/

Thanks!

**Comment by Tewuzij** [comment]
Thank you for the link! I tried to find it but didn't see this
