### ISSUE TITLE
Onedrive not showing folders which starts with "."

### ISSUE THREAD

**Issue by ekinyuksel12** [rclone/rclone#6419]
#### What is the problem you are having with rclone?

When I mount my onedrive remote setup non of my folders that their names start with "." show up. For example if I have a folder called ".Projects" and another folder call "images", "images" folder does show up but not the ".Project" folder. I use "." to make the folder appear higher on the file explorer. When I remove the "." from the folder name folder does show up but then does not appear high on the list.

#### What is your rclone version (output from `rclone version`)

rclone v1.53.3-DEV

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Ubuntu 22.04

#### Which cloud storage system are you using? (e.g. Google Drive)

Onedrive - Business

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone --vfs-cache-mode writes mount "onedrive - 1TB": ~/cloud/onedrive-1TB/

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
That's a really old version. Update it please.

Once that is done, please include a debug log file if the issue still persists.

**Comment by animosity22** [comment]
Feel free to follow up on the forums for help.

https://forum.rclone.org/

Thanks!
