### ISSUE TITLE
Same files are always transferred again

### ISSUE THREAD

**Issue by jmssil** [rclone/rclone#6422]
#### Output of `rclone version`

$ rclone version
rclone v1.59.0
- os/version: linuxmint 20.3 (64 bit)
- os/kernel: 5.4.0-125-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.18.3
- go/linking: static
- go/tags: none

#### Describe the issue

If I repeatedly execute the same rclone copy command, I keep getting the same files transferred, while I was expecting to see none transferred after the first full copy:

$ rclone copy Google\ Photos\ 2/Takeout/Google\ Photos/ Google\ Photos\ 2:/album/ --exclude "*.json" -P
Transferred:       81.912 MiB / 81.912 MiB, 100%, 46.876 KiB/s, ETA 0s
Checks:              3646 / 3646, 100%
Transferred:          116 / 116, 100%
Elapsed time:      3m36.3s

**Comment by Masamune3210** [comment]
rclone copy does not delete the files after they are transferred, so seeing the same file copied over and over while using a copy command is intended, are you thinking of the move command perhaps? That would automatically delete the source file once it has been verified to exist and to be correct on the destination

**Comment by jmssil** [comment]
Hum, I think rclone only copies new files, because I have 7538 files in that directory and the same 116 are being copied every time.

**Comment by animosity22** [comment]
If you share a debug log, it'll tell you why it copies over again.

**Comment by jmssil** [comment]
@animosity22, here it is:

[rclone.log](https://github.com/rclone/rclone/files/9500018/rclone.log)

**Comment by animosity22** [comment]
And what is not working properly? What's an example in that file of something that should not happen?

**Comment by jmssil** [comment]
The same 116 files are copied every time as if they were new.

**Comment by animosity22** [comment]
Pick one file.

rclone ls for that file and show it exists
rclone copy that file locally to the remote and share the debug log for that one file

That will help isolate the issue.

**Comment by jmssil** [comment]
Choosing `DSCN0031.jpg`.

Locally I have:

$ find Google\ Photos\ 2/ -name DSCN0031.jpg
Google Photos 2/Takeout/Google Photos/Photos from 2016/DSCN0031.jpg
Google Photos 2/Takeout/Google Photos/Cinquecento/DSCN0031.jpg

Remotely there is:

$ rclone ls Google\ Photos\ 2:|grep DSCN0031
2022/09/06 20:23:34 ERROR : upload: error listing: directory not found
       -1 album/Cinquecento/Takeout／Google Photos／Cinquecento／DSCN0031.jpg
       -1 media/by-month/2016/2016-06/DSCN0031.jpg
       -1 media/by-month/2016/2016-06/Takeout／Google Photos／Cinquecento／DSCN0031.jpg
       -1 media/all/DSCN0031.jpg
       -1 media/all/Takeout／Google Photos／Cinquecento／DSCN0031.jpg
       -1 media/by-year/2016/DSCN0031.jpg
       -1 media/by-year/2016/Takeout／Google Photos／Cinquecento／DSCN0031.jpg
       -1 album/Photos from 2016/Takeout／Google Photos／Cinquecento／DSCN0031.jpg

Entries related to these files in the log:

$ grep DSCN0031.jpg rclone.log 
2022/09/06 19:57:14 DEBUG : Cinquecento/DSCN0031.jpg.json: Excluded
2022/09/06 19:57:14 DEBUG : Cinquecento/Takeout／Google Photos／Cinquecento／DSCN0031.jpg: Size: 
2022/09/06 19:57:14 DEBUG : Cinquecento/Takeout／Google Photos／Cinquecento／DSCN0031.jpg: >Size: 
2022/09/06 19:57:15 DEBUG : Photos from 2016/DSCN0031.jpg.json: Excluded
2022/09/06 19:57:22 DEBUG : Photos from 2016/Takeout／Google Photos／Cinquecento／DSCN0031.jpg: Size: 
2022/09/06 19:57:22 DEBUG : Photos from 2016/Takeout／Google Photos／Cinquecento／DSCN0031.jpg: >Size: 
2022/09/06 19:57:54 DEBUG : Google Photos path "album": Put: src=Cinquecento/DSCN0031.jpg
2022/09/06 19:57:54 DEBUG : Cinquecento/DSCN0031.jpg: Update: src=Cinquecento/DSCN0031.jpg
2022/09/06 19:58:52 DEBUG : Cinquecento/DSCN0031.jpg: >Update: err=<nil>
2022/09/06 19:58:52 DEBUG : Cinquecento/DSCN0031.jpg: Size: 
2022/09/06 19:58:52 DEBUG : Cinquecento/DSCN0031.jpg: >Size: 
2022/09/06 19:58:52 INFO  : Cinquecento/DSCN0031.jpg: Copied (new)
2022/09/06 20:01:09 DEBUG : Google Photos path "album": Put: src=Photos from 2016/DSCN0031.jpg
2022/09/06 20:01:09 DEBUG : Photos from 2016/DSCN0031.jpg: Update: src=Photos from 2016/DSCN0031.jpg
2022/09/06 20:01:14 DEBUG : Photos from 2016/DSCN0031.jpg: >Update: err=<nil>
2022/09/06 20:01:14 DEBUG : Photos from 2016/DSCN0031.jpg: Size: 
2022/09/06 20:01:14 DEBUG : Photos from 2016/DSCN0031.jpg: >Size: 
2022/09/06 20:01:14 INFO  : Photos from 2016/DSCN0031.jpg: Copied (new)

**Comment by animosity22** [comment]
Any chance you can rclone ls just the one file and copy just the one file now and share only that log?

**Comment by jmssil** [comment]
Yes. There are strange slashes in the path which are not normal ones:

$ rclone ls "Google Photos 2":album/Cinquecento/"Takeout／Google Photos／Cinquecento／DSCN0031.jpg"
       -1 Takeout／Google Photos／Cinquecento／DSCN0031.jpg

And the log:

[DSCN0031.log](https://github.com/rclone/rclone/files/9500568/DSCN0031.log)

**Comment by jmssil** [comment]
I'm not sure about rclone/GP interaction because I am uploading another directory and in this case it copies all files every time, does not skip existing ones:

$ rclone copy Pictures/ Google\ Photos\ 2:/upload -P

But the copy command should "Copy (https://rclone.org/commands/rclone_copy/) new or changed  files to cloud storage".

**Comment by animosity22** [comment]
Can you run the same copy command in the log again and share the output?

```
2022/09/06 21:37:46 DEBUG : rclone: Version "v1.59.0" starting with parameters ["rclone" "copy" "Google Photos 2/Takeout/Google Photos/Cinquecento/DSCN0031.jpg" "Google Photos 2:album/Cinquecento/" "--log-file" "DSCN0031.log" "--log-level" "DEBUG"]
2022/09/06 21:37:46 DEBUG : Creating backend with remote "Google Photos 2/Takeout/Google Photos/Cinquecento/DSCN0031.jpg"
2022/09/06 21:37:46 DEBUG : Using config file from "/home/jmss/.config/rclone/rclone.conf"
2022/09/06 21:37:46 DEBUG : fs cache: adding new entry for parent of "Google Photos 2/Takeout/Google Photos/Cinquecento/DSCN0031.jpg", "/home/jmss/Google Photos 2/Takeout/Google Photos/Cinquecento"
2022/09/06 21:37:46 DEBUG : Creating backend with remote "Google Photos 2:album/Cinquecento/"
2022/09/06 21:37:46 DEBUG : fs cache: renaming cache item "Google Photos 2:album/Cinquecento/" to be canonical "Google Photos 2:album/Cinquecento"
2022/09/06 21:37:46 DEBUG : Google Photos path "album/Cinquecento": NewObject: remote="DSCN0031.jpg"
2022/09/06 21:37:46 DEBUG : Google Photos path "album/Cinquecento": List: dir=""
2022/09/06 21:37:47 DEBUG : Google Photos path "album/Cinquecento": >List: err=<nil>
2022/09/06 21:37:47 DEBUG : Google Photos path "album/Cinquecento": >NewObject:
2022/09/06 21:37:47 DEBUG : DSCN0031.jpg: Need to transfer - File not found at Destination
2022/09/06 21:37:47 DEBUG : Google Photos path "album/Cinquecento": Put: src=DSCN0031.jpg
2022/09/06 21:37:47 DEBUG : DSCN0031.jpg: Update: src=DSCN0031.jpg
2022/09/06 21:37:49 DEBUG : DSCN0031.jpg: >Update: err=<nil>
2022/09/06 21:37:49 DEBUG : Google Photos path "album/Cinquecento": >Put:
2022/09/06 21:37:49 DEBUG : DSCN0031.jpg: Size:
2022/09/06 21:37:49 DEBUG : DSCN0031.jpg: >Size:
2022/09/06 21:37:49 INFO  : DSCN0031.jpg: Copied (new)
2022/09/06 21:37:49 INFO  :
Transferred:       78.026 KiB / 78.026 KiB, 100%, 77.987 KiB/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:         3.4s

2022/09/06 21:37:49 DEBUG : 5 go routines active
```

You can just use 3 backtics before/after and it'll code block it.

**Comment by jmssil** [comment]
Yes:

[DSCN0031_.log](https://github.com/rclone/rclone/files/9501847/DSCN0031_.log)

**Comment by jmssil** [comment]
@animosity22 , is this a bug?

As a workaround I should probably download all photos from the cloud to a local filesystem, merge the downloaded files with the local ones, eliminate duplicates with some commands/scripting and then upload all again in a flat hierarchy. The issue may be related to the way GP organizes files (views).

**Comment by ncw** [comment]
One reason this can happen is if you have duplicate images. If you do then they pick up the name of their first upload which would cause exactly this problem.



> I'm not sure about rclone/GP interaction because I am uploading another directory and in this case it copies all files every time, does not skip existing ones:
> 
> $ rclone copy Pictures/ Google\ Photos\ 2:/upload -P
> 
> But the copy command should "Copy (https://rclone.org/commands/rclone_copy/) new or changed files to cloud storage".

Note that copying to `upload` will cause duplicates:

> The upload directory is for uploading files you don't want to put into albums. This will be empty to start with and will contain the files you've uploaded for one rclone session only, becoming empty again when you restart rclone. The use case for this would be if you have a load of files you just want to once off dump into Google Photos. For repeated syncing, uploading to album will work better.

**Comment by animosity22** [comment]
@jmssil - can you close this out if answered or is there still something outstanding?
