### ISSUE TITLE
add support for pikpak

### ISSUE THREAD

**Issue by hugo-sama** [rclone/rclone#6429]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.59.1
- os/version: Microsoft Windows 10 Pro 21H1 (64 bit)
- os/kernel: 10.0.19043.1889 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.18.5
- go/linking: static
- go/tags: cmount

I also use the Linux version: 
rclone v1.59.1
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.4.0-84-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.18.5
- go/linking: static
- go/tags: none

#### What problem are you are trying to solve?
requesting for a new Storage support called pikpak. The post on forum wasn't from me, but I also want to suggest it.
Their website is: https://mypikpak.com/

#### How do you think rclone should be changed to solve that?
Add a new storage support. They seems like have no api for it yet, but [the project mentioned on the forum](https://github.com/alist-org/alist) might be help. It said they [support pikpak](https://alist.nn.ci/guide/) file listing.
The pikpak website is: https://mypikpak.com/

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Unless you have someone that will do a PR, it'll just really sit unless there is a lot of interest.

**Comment by dume2007** [comment]
Need!

**Comment by darthShadow** [comment]
@wiserain Do you want to send a PR for the pikpak backend from your fork?

**Comment by wiserain** [comment]
@darthShadow I will send a PR soon. Thanks.

**Comment by Meuko** [comment]
Following---
