### ISSUE TITLE
SyntaxError: Non-UTF-8 code starting with '\xd1' in file ../rclone on line 2, but no encoding declared

### ISSUE THREAD

**Issue by disbenovi** [rclone/rclone#6435]
#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

disisnovi@raspberrypi:~/Desktop $ python rclone-linux-arm.py > output1.txt
SyntaxError: Non-UTF-8 code starting with '\xd1' in file /home/disisnovi/Desktop/rclone-linux-arm.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Where did `rclone-linux-arm.py` come from? That isn't part of the rclone distribution.

Rclone itself is a binary, not a python program.
