### ISSUE TITLE
cryptcheck does not report problems with skipped/ignored files

### ISSUE THREAD

**Issue by eharris** [rclone/rclone#6439]
#### What is the problem you are having with rclone?

This is a follow-on to #6437.  After discovering the leftover directories that were not removed using the `sync` command, I tried using `cryptcheck` to see if it would report the problematic skipped files.  And in order to avoid errors about the directory not existing on the source, I created an empty directory to match the destination extra directory.

Here is the output when running `cryptcheck` against one of the leftover directories that `sync` did not remove:

```
> rclone cryptcheck /raid/audio/work/new/_-_Rachmaninoffs_Greatest_Hits odc:audio/work/new/_-_Rachmaninoffs_Greatest_Hits
2022/09/13 02:31:18 NOTICE: Encrypted drive 'odc:audio/work/new/_-_Rachmaninoffs_Greatest_Hits': 0 differences found
>
```

Note that it did NOT report any of the other files that are also contained in that directory, due to crypt errors.  Those files with errors can be seen only when increasing the verbosity to `-vv`:

```
> rclone cryptcheck -vv /raid/audio/work/new/_-_Rachmaninoffs_Greatest_Hits odc:audio/work/new/_-_Rachmaninoffs_Greatest_Hits
2022/09/13 02:34:11 DEBUG : rclone: Version "v1.59.2-beta.6379.603efbfe7" starting with parameters ["rclone" "cryptcheck" "-vv" "/raid/audio/work/new/_-_Rachmaninoffs_Greatest_Hits" "odc:audio/work/new/_-_Rachmaninoffs_Greatest_Hits"]
2022/09/13 02:34:11 DEBUG : Creating backend with remote "/raid/audio/work/new/_-_Rachmaninoffs_Greatest_Hits"
2022/09/13 02:34:11 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2022/09/13 02:34:11 DEBUG : Creating backend with remote "odc:audio/work/new/_-_Rachmaninoffs_Greatest_Hits"
2022/09/13 02:34:12 DEBUG : Creating backend with remote "od:bk/<redacted>"
2022/09/13 02:34:12 DEBUG : Starting OpenDrive session with ID: <redacted>
2022/09/13 02:34:14 INFO  : Using md5 for hash comparisons
2022/09/13 02:34:14 DEBUG : Encrypted drive 'odc:audio/work/new/_-_Rachmaninoffs_Greatest_Hits': Waiting for checks to finish
2022/09/13 02:34:14 DEBUG : 0ng7tk6ro4ng92fl4cc9ug44itfo38ml0q7on7d8srdlij73g7rom97q1tpvm2md7s9fo4fl8k214vss7pu02jvvt9ta85qdva30abc096et0dt899rfcldho092kubcu2bdb3bllvsdo89ph75um4brspph6vi8trcbolcdbss4ohmmjh87vrtk6plrorgn4orpgufh5l9dkjk7814utfvfs6cmulgnd4kbkc70kebva5v0gfpkvpnpddh89u9: Skipping undecryptable file name: not a multiple of blocksize
2022/09/13 02:34:14 DEBUG : 8uvg81bqc8c3ffm1bus5qcilgvijssnmca0khid3lpare1ouh6fgsa1l7d2mle9c2gq9u3q3bl416lv156mec87r1k6anava0h59bj611g7vur88h7m6t6as3oqi5emqa1rn5flg4ni31l9vj32j74ffplh5g97ha2rgffei2km7n79nukrp3gb33eod936ersetngt4vujqcer4cba6b7pf95vafcs91a7fp2tal9fioj0udoiuns86kk5varq: Skipping undecryptable file name: not a multiple of blocksize
2022/09/13 02:34:14 DEBUG : kgfjq36dhceit8khdq2kdg478096ft2h7pojsbn92n3nd8gsmti7nvr5o88ivdtid76nkgssaimdk8mg8kpe2pnlq0jgv0corsa6j6chrd0glfa216u0e82lib83d38toagm60lksnrd6o2vj72re5sp6q9kuqh4vgspo5ec1975ucmigi146ikojmcuhrtoe572rnh8rmpjcbjg7g37vbh4vkudp9vjuamb65vi8j4fiqiuj3dqm07v466oo92: Skipping undecryptable file name: not a multiple of blocksize
2022/09/13 02:34:14 DEBUG : m5ek9a3hrajnvipcgrdb2kajfngb4nv8il980e3fitnre0iau32u03l0oari4hu3suu0elfpsgdo60jgtma4e04lebu6cjfkmtc6rfup8kj2fcevt2i5j873her3frrp8mopapji7a8446rjginna0k8km1eon5pckfm8vvigk8jmk4d2i9n0i51imddl7036g04nrfmrfp1736nmr8ahsjie5frnf5mggsg08rlv8dudlnloqb04vi36m29tu0: Skipping undecryptable file name: not a multiple of blocksize
2022/09/13 02:34:14 DEBUG : uffuqr018j2cqavb3k852cvu950fuqeh97k39vkh3hs9d5m21ekua2d7lnc2gefthrih1m4nua638eejb72bk6d77o1g0e162faia4ef44qki7lr9k6jdpq5d6s9d2jsl4l50do68qt0finaapsnq63ctn1ui7ah2snfbqm9t99aan29polrt9i8rsjl62dqmbe9l9r0vgtr73l6fqp892e853k3uj1duat14bts4fkfkrt35fm5p7eh8a4o0so: Skipping undecryptable file name: not a multiple of blocksize
2022/09/13 02:34:14 NOTICE: Encrypted drive 'odc:audio/work/new/_-_Rachmaninoffs_Greatest_Hits': 0 differences found
2022/09/13 02:34:14 INFO  : 
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:         2.9s

2022/09/13 02:34:14 DEBUG : 3 go routines active
>
```

Note the `Skipping undecryptable file name: not a multiple of blocksize` DEBUG lines.  It seems like cryptcheck should report these problematic files, as the whole point of `cryptcheck` is to verify and report any differences.

#### What is your rclone version (output from `rclone version`)

rclone v1.59.2-beta.6379.603efbfe7
- os/version: debian 11.4 (64 bit)
- os/kernel: 5.10.0-17-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17
- go/linking: dynamic
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Debian 11.4, amd64

#### Which cloud storage system are you using? (e.g. Google Drive)

Opendrive with crypt remote

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
That's because you've mixed non crypt files with a crypt location which creates errors. You'd want to clean up your remote so it only contains crypted files. That happens in many spots.

**Comment by eharris** [comment]
I don't think that should matter.  The purpose of `cryptcheck` is to report differences between the source and the destination, and files that are silently ignored would seem to me to be clearly violating that that goal.
