### ISSUE TITLE
beta testbuild link returns a 0b tar.gz

### ISSUE THREAD

**Issue by Bestfast** [rclone/rclone#6450]
not a problem with rclone itself but it's website, and I'm sorry if I couldn't make a forum post about it. 
https://beta.rclone.org/test/testbuilds-latest/ links in this repository (and in general in beta.rclone.org) return a download for a 0b tar.gz 
this affects application that use https://beta.rclone.org/test/testbuilds-latest/rclone-android-21-armv8a.gz as an always-updated rclone link, making it unusable.

**Comment by animosity22** [comment]
We'll take care of as we have multiple posts on the topic already. Thanks.
