### ISSUE TITLE
rclone map drive

### ISSUE THREAD

**Issue by dinger1986** [rclone/rclone#6458]
We have created an easy to use rclone map drive script for windows your users might want to use, its great for using sharepoint instead of a fileserver and whatever else! https://github.com/techahold/Rclone-Map-Drive Wasnt sure where to put this so thiught I would share it here, I hope thats ok!

**Comment by ncw** [comment]
We normally put things like this here - you can add it there yourself if you would like.

https://github.com/rclone/rclone/wiki/Third-Party-Installers

That might not be exactly the right page though!

I think you should make this announcement on [the rclone forum](https://forum.rclone.org/) and you'll get feedback from the users.

**Comment by dinger1986** [comment]
great thanks!
