### ISSUE TITLE
Doc issue: Setting up systemd (auto)mount units like in the docs creates a dependency cycle.

### ISSUE THREAD

**Issue by wilcooo** [rclone/rclone#6459]
Creating Systemd units, exactly like described in [this section](https://rclone.org/commands/rclone_mount/#rclone-as-unix-mount-helper) of the documentation, creates a dependency cycle.

The automount is set to be `After=network-online.target` (which is fair), but also has an implicit `Before=local-fs.target` set automatically by systemd.

From `man systemd.automount`:

> Automount units automatically gain an After= dependency on
           local-fs-pre.target, and a Before= dependency on local-fs.target.

This causes one element in the cycle to randomly fail. Sometimes, it's the automount itself (causing the onedrive folder to be empty). Other times, it's the NetworkManger (another unit in the created cycle). The latter one is quite annoying, as you can imagine!

(one of) the cycles: `mnt-onedrive.automount` -> `local-fs.target` -> `ldconfig.service` -> `sysinit.target` -> `NetworkManager-wait-online.service` -> `network-online.target` -> `mnt-onedrive.automount`

I don't know much about systemd, most of it I only just learned by investigating this issue. I guess `DefaultDependencies=no` should solve this, but someone with better knowledge might need to confirm this.

#### Technical details

Clean install of Fedora 36 workstation. rclone installed via dnf.

    rclone v1.57.0-DEV
    - os/version: fedora 36 (64 bit)
    - os/kernel: 5.19.9-200.fc36.x86_64 (x86_64)
    - os/type: linux
    - os/arch: amd64
    - go/version: go1.18beta1
    - go/linking: dynamic
    - go/tags: none
 
I've setup a onedrive business mount. When an unimportant unit of the cycle happens to be failing, all works fine.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
I'm not sure what the issue as I've used that service file for years now without any issue.

I'm not following what problem happens as I use:

```
Wants=network-online.target
After=network-online.target
```

In my network related services.

**Comment by albertony** [comment]
Related: https://github.com/rclone/rclone/pull/5911

**Comment by animosity22** [comment]
Oh sorry - I see now. Thanks @albertony as it makes sense to me.

**Comment by animosity22** [comment]
I don't use automount either but that seems to be correct to me as well.

@wilcooo - does that make sense for you as well?

**Comment by wilcooo** [comment]
Yes, that makes sense! `network-online.target` is part of each cycle in my logs. I just removed the _After_ on my system, and will check the logs tomorrow after I've restarted a bunch of times again.

By the way; `DefaultDependencies=no` has worked for me as well the past day, but removing the _After_ feels like the better approach.

**Comment by wilcooo** [comment]
The logs of past day still show dependency cycles; however, they now don't include the `mnt-onedrive.automount` unit, but rather the `mnt-onedrive.mount` unit. I guess that `After=network-online.target` should be removed from the latter as well?

**Comment by maxxer** [comment]
I'll add myself to the list of people barely knowing systemd mounts. Anyway, adding to your research info (from [manual](https://www.freedesktop.org/software/systemd/man/systemd.mount.html)):

> Network mount units automatically acquire After= dependencies on remote-fs-pre.target, network.target and network-online.target, and gain a Before= dependency on remote-fs.target unless nofail mount option is set. Towards the latter a Wants= unit is added as well.

I don't know if systemd is aware that `rclone` filesystem type is remote or not, nor if that statement refers to `fstab` mountpoints only. 

If that applies, removing the `After` won't change anything, instead `DefaultDependencies=no` should be necessary.

**Comment by wilcooo** [comment]
> If that applies, removing the `After` won't change anything, instead `DefaultDependencies=no` should be necessary.

I don't think that's necessary (but I don't know why), since everything is working on my system now, without any mention of cycles in my logs. Even without `DefaultDependencies=0`. For completeness, here are my working units:

### `$ cat /etc/systemd/system/mnt-onedrive.mount`

    [Mount]
    Type=rclone
    What=onedrive-uu:
    Where=/mnt/onedrive
    Options=rw,allow_other,args2env,vfs-cache-mode=full,config=/home/myname/.config/rclone/rclone.conf,cache-dir=/var/rclone

### `$ cat /etc/systemd/system/mnt-onedrive.automount`

    [Unit]
    Before=remote-fs.target
    [Automount]
    Where=/mnt/onedrive
    TimeoutIdleSec=600
    [Install]
    WantedBy=multi-user.target

**Comment by albertony** [comment]
So, can we conclude on this?

1. Remove the following from mnt-data.automount example, like #5911 suggests:

```
After=network-online.target
```

2. Remove the following from mnt-data.mount example:

```
[Unit]
After=network-online.target
```

Based on the previous comment, if there are no objections, I will do this.
