### ISSUE TITLE
IPFS Support

### ISSUE THREAD

**Issue by ViniciusFXavier** [rclone/rclone#6460]
URL: https://ipfs.tech/
Description: A peer-to-peer hypermedia protocol designed to preserve and grow humanity's knowledge by making the web upgradeable, resilient, and more open.

Has [GO ](https://github.com/ipfs/kubo)and [JavaScript](https://js.ipfs.tech/) Support.

#### How do you think rclone should be changed to solve that?
Support [IPFS ](https://ipfs.tech/)as a sync source and destination.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment]
Is this a duplicate of https://github.com/rclone/rclone/issues/128?

**Comment by ViniciusFXavier** [comment]
Duplicate of #128
