### ISSUE TITLE
(Optionally) remove symmetric secret from crypt drive in rclone.conf

### ISSUE THREAD

**Issue by fulldecent** [rclone/rclone#6462]
Related: https://github.com/rclone/rclone/issues/737 (that issue solves this issue, but this issue in general is smaller)

# Current

If you create a crypt storage, your symmetric key is stored in rclone.conf. (Documented at https://rclone.org/crypt/)

This creates means your files are only as secure as the weakest of: rclone.conf on localhost, your plaintext files on wherever they are.

# Proposed

Running the rclone command when the passkey is not stored in rclone.sync will require the password to be input securely on the terminal while the program is running.

**Comment by animosity22** [comment]
That's already a thing as you can encrypt your rclone.conf

https://rclone.org/docs/#configuration-encryption

Or you can use environment variables if you wanted as well.

**Comment by fulldecent** [comment]
Cool, that works, thank you
