### ISSUE TITLE
Rclone Mount Error

### ISSUE THREAD

**Issue by chiragnahata** [rclone/rclone#6463]
![image](https://user-images.githubusercontent.com/63905783/191916508-aa5c0e20-7d89-4355-b03c-8b6bb5bbbb6f.png)

My rclone used to mount before but suddenly it stopped. Please help as soon as possible 

https://forum.rclone.org/t/rclone-drive-mounting-error/33158

**Comment by animosity22** [comment]
Please just use one spot and don't double post.
