### ISSUE TITLE
Use rclone mount to mount a fixed disk drive and open the folder slowly

### ISSUE THREAD

**Issue by bluespring88** [rclone/rclone#6465]
Use rclone mount to mount a fixed disk drive，When a folder is opened, it will trigger the downloading of pictures, resulting in slow opening，please
1、Can I download pictures without triggering, similar to a network drives？
2、Whether webdav can distinguish between downloaded files and open folders, and return thumbnails for open folders？

**Comment by albertony** [comment]
My first impression is that there is not much rclone can do about this, but you didn't include too much details so I may be wrong..

Regarding:

> Can I download pictures without triggering, similar to a network drives？

If on Windows, can you not mount in network mode, as described here: <https://rclone.org/commands/rclone_mount/#mounting-modes-on-windows>?

**Comment by bluespring88** [comment]
> 我的第一印象是 rclone 对此无能为力，但是您没有包含太多细节，所以我可能是错的..
> 
> 关于：
> 
> > 可以不触发下载图片，类似于网盘吗？
> 
> 如果在 Windows 上，是否可以不以网络模式挂载，如此处所述：[https](https://rclone.org/commands/rclone_mount/#mounting-modes-on-windows) ://rclone.org/commands/rclone_mount/#mounting-modes-on-windows ？

Thank you very much, but you don't want to use the network mode; Open the folder to download pictures. I don't know whether it is triggered by Windows or rclone. The rclone command I use is:
rclone.exe mount cloud:/ Z: --vfs-cache-mode full --config=C:\xxx\rclone.conf --volname="我的网盘"

**Comment by animosity22** [comment]
Double posting in the forums and here wastes a lot of folk's time.

Please use the fourms.

https://forum.rclone.org/t/use-rclone-mount-to-mount-a-fixed-disk-drive-and-open-the-folder-slowly/33241/2

as you already have that logged there.
