### ISSUE TITLE
Google drive authorization seems to be broken

### ISSUE THREAD

**Issue by korjavin** [rclone/rclone#6483]
Following https://rclone.org/drive/#making-your-own-client-id

brings to this error from google side: 

```
Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow Migration Guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob
```

rclone version
rclone v1.53.3-DEV
- os/arch: linux/amd64
- go version: go1.19

**Comment by Masamune3210** [comment]
Works just fine for me, double check you set everything up correctly according to the guide

**Comment by korjavin** [comment]
Could it be that you made credentials before Feb 16? 

According to this : https://developers.google.com/identity/protocols/oauth2/resources/oob-migration
this is the date when chages applied.

I followed how-to a few time, I create new project in gcloud, I tried different computers, and also I tryed to use default rclone client (shared) - the error is the same.
```Error 400: invalid_request
The out-of-band (OOB) flow has been blocked in order to keep users secure. Follow the Out-of-Band (OOB) flow Migration Guide linked in the developer docs below to migrate your app to an alternative method.
Request details: redirect_uri=urn:ietf:wg:oauth:2.0:oob
[Related developer documentation](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration)```

**Comment by korjavin** [comment]
Hmm. After a few more restarts, without changing anything I managed to get a token.

Just out of curiosity I tried again and it failed.

So, I suspect it's not like "damn broken" but perhaps has some issues.

**Comment by ncw** [comment]
Check out https://github.com/rclone/rclone/issues/6000 for the background 

And upgrade to rclone 1.58 or later

**Comment by animosity22** [comment]
Please upgrade and for any support, you can use the forums.

https://forum.rclone.org
