### ISSUE TITLE
Crypt remote not returning DropBox hash with lsjson

### ISSUE THREAD

**Issue by jasondavis303** [rclone/rclone#6485]
#### What is the problem you are having with rclone?
When using a Crypt remote on top of DropBox, the lsjson command does not return the file hashes

#### What is your rclone version (output from `rclone version`)
```
rclone v1.59.1
- os/version: Microsoft Windows 11 Pro 22H2 (64 bit)
- os/kernel: 10.0.22621.521 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.18.5
- go/linking: static
- go/tags: cmount
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 11, 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
DropBox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone lsjson "DPMedia:test/Big Buck Bunny.mp4" --hash -vv

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2022/10/10 09:22:37 DEBUG : rclone: Version "v1.59.1" starting with parameters ["C:\\Windows\\system32\\rclone.exe" "lsjson" "DPMedia:test/Big Buck Bunny.mp4" "--hash" "-vv"]
2022/10/10 09:22:37 DEBUG : Creating backend with remote "DPMedia:test/Big Buck Bunny.mp4"
2022/10/10 09:22:37 DEBUG : Using config file from "C:\\Users\\jason\\.config\\rclone\\rclone.conf"
2022/10/10 09:22:37 DEBUG : Creating backend with remote "DPDropbox:secure/ieva3a2uo90cqc8766inrmhv68/bhlc226cdhfeef2h5ja9m9fhhfp71sk1n47v34toevj50glqpcrg"
2022/10/10 09:22:37 DEBUG : fs cache: adding new entry for parent of "DPDropbox:secure/ieva3a2uo90cqc8766inrmhv68/bhlc226cdhfeef2h5ja9m9fhhfp71sk1n47v34toevj50glqpcrg", "DPDropbox:secure/ieva3a2uo90cqc8766inrmhv68"
[
{"Path":"Big Buck Bunny.mp4","Name":"Big Buck Bunny.mp4","Size":69819148,"MimeType":"video/mp4","ModTime":"2021-01-15T00:55:41Z","IsDir":false,"ID":"id:ZjfDck7_e84AAAAAAAV6XA"}
]
2022/10/10 09:22:38 DEBUG : 6 go routines active
2022/10/10 09:22:38 INFO  : Dropbox root 'secure/ieva3a2uo90cqc8766inrmhv68': Commiting uploads - please wait...
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
What are you trying to do with the hash once you get it?

When you copy to a crypt remote, the hash will change so you can't really check it.

**Comment by animosity22** [comment]
See hashes are not stored for crypt remotes:

https://rclone.org/crypt/#modified-time-and-hashes

**Comment by animosity22** [comment]
Closing out as answered - Any questions, you can always start on the forums:

https://forum.rclone.org
