### ISSUE TITLE
server-side copy  send request failed

### ISSUE THREAD

**Issue by thenamehasbeentake** [rclone/rclone#6489]
#### What is the problem you are having with rclone?
server side copy with rclone code with ceph rgw
cmd/lsf/testfiles/subdir/file2 file copy hang with logs   `net/http: timeout awaiting response headers`

#### What is your rclone version (output from `rclone version`)
~~~
./rclone --version
rclone v1.56.2-beta.5627.106755b12.v1.56-stable
- os/version: ubuntu 18.04 (64 bit)
- os/kernel: 5.4.0-120-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.10
- go/linking: dynamic
- go/tags: none
~~~

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
> Linux pc 5.4.0-120-generic #136~18.04.1-Ubuntu SMP Fri Jun 10 18:00:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

#### Which cloud storage system are you using? (e.g. Google Drive)
ceph rgw

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
cd rclone, make, and run commond below
1. ./rclone copy   ./ s3-backup:test1/  -vv   --log-file=logfile.log  --fast-list  --no-traverse
2. ./rclone copy   s3-backup:test1/ s3-backup:test2/  -vv   --log-file=logfile.log  --fast-list  --no-traverse

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

~~~

...
2022/10/12 18:17:18 DEBUG : pacer: low level retry 7/10 (error RequestError: send request failed
caused by: Put "https://www.xxxx.com:80/test2/cmd/lsf/testfiles/subdir/file2": net/http: timeout awaiting response headers)
2022/10/12 18:17:18 DEBUG : pacer: Rate limited, increasing sleep to 640ms
2022/10/12 18:18:00 INFO  : 
Transferred:      254.813Mi / 254.813 MiByte, 100%, 0 Byte/s, ETA 0s
Transferred:         1282 / 1283, 100%
Elapsed time:      36m0.0s
Transferring:
 *                cmd/lsf/testfiles/subdir/file2:  0% /1, 0/s, -
~~~

**Comment by ncw** [comment]
Is this a very big file? Try increasing `--timeout`

**Comment by thenamehasbeentake** [comment]
> Is this a very big file? Try increasing `--timeout`

Small file, in rclone code
