### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by kevzcr** [rclone/rclone#6491]
- help...  why?

> ![image](https://user-images.githubusercontent.com/88956040/195509568-b1937dff-51b4-4927-8e84-c18b2ca1d71b.png)

**Comment by ncw** [comment]
That error is an IO error.

What were you trying to do?

How is this rclone related?

**Comment by animosity22** [comment]
Please use the forums if you have a real question and use the help and support template filled out.

https://forum.rclone.org
