### ISSUE TITLE
rclone sync creates a directory named ".." when destination path contains /../

### ISSUE THREAD

**Issue by cyrilcourvoisier** [rclone/rclone#6493]
**What is the problem you are having with rclone?**

If you launch the command;
`rclone sync <a local path> <some dir>/parentDir/../<some dir>
`
so a synchronisation on a local machine from a local directory to another local directory, it will create a directory named ".." in parentDir instead of going one directory up.

**What is your rclone version (output from rclone version)**

All versions >= 1.50 (it works in 1.49)

**Which OS you are using and how many bits (e.g. Windows 7, 64 bit)**

Windows 11 Pro 21H2  (arch: amd64) and macOS 12.6 (arch: arm64)

**Which cloud storage system are you using? (e.g. Google Drive)**

Local filesystem

**The command you were trying to run (e.g. rclone copy /tmp remote:tmp)**

`rclone sync XXX XXX/../XXX
`

**Comment by animosity22** [comment]
This has me scratching my head as to why you'd do that?

What's the use case?

Can you share all the stuff and use the template to actually report an issue?

**Comment by cyrilcourvoisier** [comment]
I have used rclone from cmake to synchronize a source directory to build directory and the target path use '..' to access parent directory

**Comment by animosity22** [comment]
Ok - why do you use that in your rclone command though and not just the path?

**Comment by animosity22** [comment]
Is this an accurate test case like you were describing?

```
felix@gemini:~$ rclone sync /home/felix/test1 /home/felix/test2/onedir/../onedir -vv
2022/10/14 10:29:04 DEBUG : Setting --config "/opt/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/opt/rclone/rclone.conf"
2022/10/14 10:29:04 DEBUG : rclone: Version "v1.59.2" starting with parameters ["rclone" "sync" "/home/felix/test1" "/home/felix/test2/onedir/../onedir" "-vv"]
2022/10/14 10:29:04 DEBUG : Creating backend with remote "/home/felix/test1"
2022/10/14 10:29:04 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2022/10/14 10:29:04 DEBUG : Creating backend with remote "/home/felix/test2/onedir/../onedir"
2022/10/14 10:29:04 DEBUG : fs cache: renaming cache item "/home/felix/test2/onedir/../onedir" to be canonical "/home/felix/test2/onedir/．．/onedir"
2022/10/14 10:29:04 DEBUG : Local file system at /home/felix/test2/onedir/．．/onedir: Waiting for checks to finish
2022/10/14 10:29:04 DEBUG : Local file system at /home/felix/test2/onedir/．．/onedir: Waiting for transfers to finish
2022/10/14 10:29:04 DEBUG : file: md5 = d41d8cd98f00b204e9800998ecf8427e OK
2022/10/14 10:29:04 INFO  : file: Copied (new)
2022/10/14 10:29:04 DEBUG : Waiting for deletions to finish
2022/10/14 10:29:04 INFO  :
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         0.0s

2022/10/14 10:29:04 DEBUG : 4 go routines active
felix@gemini:~$ cd test2
felix@gemini:~/test2$ ls -alR
.:
total 0
drwxrwxr-x 1 felix felix  12 Oct 14 10:28 .
drwxr-x--- 1 felix felix 288 Oct 14 10:28 ..
drwxrwxr-x 1 felix felix  12 Oct 14 10:29 onedir

./onedir:
total 0
drwxrwxr-x 1 felix felix 12 Oct 14 10:29 .
drwxrwxr-x 1 felix felix 12 Oct 14 10:28 ..
drwxrwxr-x 1 felix felix 12 Oct 14 10:29 ．．

./onedir/．．:
total 0
drwxrwxr-x 1 felix felix 12 Oct 14 10:29 .
drwxrwxr-x 1 felix felix 12 Oct 14 10:29 ..
drwxrwxr-x 1 felix felix  8 Oct 14 10:29 onedir

./onedir/．．/onedir:
total 0
drwxrwxr-x 1 felix felix  8 Oct 14 10:29 .
drwxrwxr-x 1 felix felix 12 Oct 14 10:29 ..
-rw-rw-r-- 1 felix felix  0 Oct 14 10:28 file
```

I get slightly different results on Linux/MacOS. I'm testing primarily on Linux above.

**Comment by animosity22** [comment]
Gotcha - thanks!

I did a quick test with rsync and that works properly just for some sanity.

```
felix@gemini:~$ rsync -avh /home/felix/test1 /home/felix/test2/onedir/../onedir/
sending incremental file list
test1/
test1/file

sent 133 bytes  received 39 bytes  344.00 bytes/sec
total size is 0  speedup is 0.00
felix@gemini:~$ cd test2
felix@gemini:~/test2$ ls
onedir
felix@gemini:~/test2$ ls -alR
.:
total 0
drwxrwxr-x 1 felix felix  12 Oct 14 10:36 .
drwxr-x--- 1 felix felix 288 Oct 14 10:28 ..
drwxrwxr-x 1 felix felix  10 Oct 14 10:36 onedir

./onedir:
total 0
drwxrwxr-x 1 felix felix 10 Oct 14 10:36 .
drwxrwxr-x 1 felix felix 12 Oct 14 10:36 ..
drwxrwxr-x 1 felix felix  8 Oct 14 10:28 test1

./onedir/test1:
total 0
drwxrwxr-x 1 felix felix  8 Oct 14 10:28 .
drwxrwxr-x 1 felix felix 10 Oct 14 10:36 ..
-rw-rw-r-- 1 felix felix  0 Oct 14 10:28 file
```

@ncw - I think it's doing something translating the path there is something goes wrong here:

```
2022/10/14 10:29:04 DEBUG : fs cache: renaming cache item "/home/felix/test2/onedir/../onedir" to be canonical "/home/felix/test2/onedir/．．/onedir"
```

That is the path that looks wrong.

**Comment by Masamune3210** [comment]
Maybe it's accidentally converting the periods to their wide-chars? At least that's my guess from the log of the conversion having different spacing from before it's converted to after

**Comment by albertony** [comment]
> Maybe it's accidentally converting the periods to their wide-chars?

That is a very good guess. :) If the path is absolute then it will not be cleaned (resolved) by the local backend, and the periods will be encoded according to the [backend encoding](https://rclone.org/local/#filenames). A relative path is made absolute first, and this process implicitly performs clean (resolve) and would work in your case as well. I will look into fixing the missing clean of absolute paths.
