### ISSUE TITLE
when is next release?

### ISSUE THREAD

**Issue by tooptoop4** [rclone/rclone#6497]
#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Please don't open issues like this.

Thanks.
