### ISSUE TITLE
bisync removes empty dirs by default

### ISSUE THREAD

**Issue by Madrich** [rclone/rclone#6500]
WebDav NextCloud
rclone bisync D:/CloudDrives/myNC myNC: --resync --verbose

Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Checks:             41585 / 41585, 100%
Deleted:                0 (files), 13 (dirs)
Transferred:            2 / 2, 100%
Elapsed time:       6m0.0s

**Comment by animosity22** [comment]
#### What is your rclone version (output from `rclone version`)

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)


#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`

**Comment by animosity22** [comment]
Please resubmit once you have the details to share and use the template.

Thanks.
