### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by alneven** [rclone/rclone#6511]
hello there,

suddenly I have this strange **error** after using any rclone command, even version or help, or copy with -v -vv (therefore there is no log file).

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x466876]

goroutine 1 [running]:
type..hash.github.com/aws/aws-sdk-go/aws/endpoints.endpointKey(0xc000825948, 0xc00046e6d8)
        <autogenerated>:1 +0x1e
github.com/aws/aws-sdk-go/aws/endpoints.init()
        github.com/aws/aws-sdk-go@v1.42.1/aws/endpoints/defaults.go:13140 +0x4d1de
```

Do you have any idea?

#### What is the problem you are having with rclone?

panic: runtime error: invalid memory address or nil pointer dereference

for two days ago it was working well
if I use
**/usr/bin/rclone** 
it's **working** normally
rclone
**direct not**

#### What is your rclone version (output from `rclone version`)
$ /usr/bin/rclone -V
rclone v1.60.0
- os/version: ubuntu 16.04 (64 bit)
- os/kernel: 4.15.0-142-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.2
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
/etc/lsb-release
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"

#### Which cloud storage system are you using? (e.g. Google Drive)
Google drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone copy \
  --user-agent="myworld_t" \
  --transfers 3 \
  --low-level-retries 1 \
  --checkers 3 \
  --tpslimit 3 \
  --retries 10 \
  --contimeout 10m \
  --size-only \
  --exclude-from exclude-file.txt \
  --drive-stop-on-upload-limit \
  --max-size 50000M \
  --verbose \
  --log-file=Log.txt \
  /home/.../.local/...123/ gdrive:Plex/...123

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
no output as rclone just keep crashing with this message
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x466876]

goroutine 1 [running]:
type..hash.github.com/aws/aws-sdk-go/aws/endpoints.endpointKey(0xc000813948, 0xc00052c6d8)
        <autogenerated>:1 +0x1e
github.com/aws/aws-sdk-go/aws/endpoints.init()
        github.com/aws/aws-sdk-go@v1.42.1/aws/endpoints/defaults.go:13140 +0x4d1de
```

It was also the problem under 1.58.1, therefore I upgraded to 1.60.0 but the same error occurred after that as well

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by alneven** [comment]
should I post this issue also the forum?

**Comment by ncw** [comment]
Is that the whole back trace?

It appears to be crashing in the Aws SDK.

Can you post your config with secrets redacted?

Can you also run the env command and post that output.

Also try running rclone as a different user (maybe create a fresh one) and see if it works like that 

No need to post to forum as well.

**Comment by alneven** [comment]
for env:

`$ printenv
XDG_SESSION_ID=8935
PUID=1000
TERM=xterm-256color
SHELL=/bin/bash
SSH_TTY=/dev/pts/4
PGID=1000
USER=plex
MAIL=/var/mail/plex
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PWD=/home/plex
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/plex
LOGNAME=plex
USERDIR=/home/plex
LESSOPEN=| /usr/bin/lesspipe %s
XDG_RUNTIME_DIR=/run/user/1000
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/printenv
`


rclone conf:
`$ cat rclone.conf
[gdrive]
type = drive
client_id = *-*.apps.googleusercontent.com
client_secret = **
scope = drive
root_folder_id = 
service_account_file = 
token = {"access_token":"*.*_*-*_*-*-*_*","token_type":"Bearer","refresh_token":"1/*-*_*_*_*","expiry":"2022-10-23T17:35:13.547975658+02:00"}
`

**Comment by alneven** [comment]
Oh it look terrible w/o formating

**Comment by alneven** [comment]
> config & env

**printenv** from the user executing the rclone copy

`XDG_SESSION_ID=8892
PUID=1000
TERM=xterm
SHELL=/bin/bash
SSH_TTY=/dev/pts/2
PGID=1000
USER=plex
MAIL=/var/mail/plex
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
PWD=/home/plex
LANG=en_US.UTF-8
SHLVL=1
HOME=/home/plex
LOGNAME=plex
USERDIR=/home/plex
LESSOPEN=| /usr/bin/lesspipe %s
XDG_RUNTIME_DIR=/run/user/1000
LESSCLOSE=/usr/bin/lesspipe %s %s`


**rclone.conf**
`[gdrive]
type = drive
client_id = *.apps.googleusercontent.com
client_secret = ***
scope = drive
root_folder_id =
service_account_file =
token = {"access_token":*`


I'm using rclone only for copy

**Comment by alneven** [comment]
It is strange, but now it's working. BUT somehow as a user I have the "old" version, even though I have upgraded to 1.60.0

`$ rclone -V
rclone v1.58.1
- os/version: ubuntu 16.04 (64 bit)
- os/kernel: 4.15.0-142-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.9
- go/linking: static
- go/tags: none`

Maybe there is a something wrong with my env, as  the go/version is also different. Between "rclone -V" and "/usr/bin/rclone -V"

`$ whereis rclone
rclone: /usr/bin/rclone /usr/sbin/rclone`

I have two different version at the same time, and the one today was not working for a while...
What a coincidence that I have recognized this because of this error. Now I have to fix that the systems recognize only one of those. And maybe the newer version.

`root@ ~ # /usr/bin/rclone --version
rclone v1.60.0
- os/version: ubuntu 16.04 (64 bit)
- os/kernel: 4.15.0-142-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.2
- go/linking: static
- go/tags: none

root@ ~ # /usr/sbin/rclone --version
rclone v1.58.1
- os/version: ubuntu 16.04 (64 bit)
- os/kernel: 4.15.0-142-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.9
- go/linking: static
- go/tags: none`

**Comment by animosity22** [comment]
Looks like perhaps done some funky installs as /usr/sbin is a rather unique place to put it.

Are you having an issue still and can recreate it or no? If not, I'd say just close it out and open something new if you can recreate it.

**Comment by alneven** [comment]
Its working now, and cannot recreate the error even with the old version. Thanks!
