### ISSUE TITLE
"Error 400: Invalid_request" when adding a specific google drive remote

### ISSUE THREAD

**Issue by pitsi** [rclone/rclone#6514]
#### The associated forum post URL from `https://forum.rclone.org`
(I am not a member on the forum)

#### What is the problem you are having with rclone?
I am trying to add a google drive with a specific remote and I get the forementioned error regardless of where I try it. 
I have successfully added my google drive in the past on my system (debian unstable x64) and now I want to add a friend's, but on a headless system (rpi3b+ running debian stable aarch64).
No matter where I try to add it, I always get the forementioned error, as seen in the image below. As a test, I removed and re-added my google drive on my system and it was added with no issues at all.

![2022-10-22-152605_1280x1024_scrot](https://user-images.githubusercontent.com/5880037/197401396-09fc0a8a-e580-4a20-ac90-e0aeb26bb871.png)

#### What is your rclone version (output from `rclone version`)
On debian unstable x64
```
$ rclone version
rclone v1.53.3-DEV
- os/arch: linux/amd64
- go version: go1.19
```
And on debian stable aarm64
```
$ rclone version
rclone v1.53.3-DEV
- os/arch: linux/arm64
- go version: go1.15.9
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Debian unstable x64 and debian stable aarch64 respectively.

#### Which cloud storage system are you using? (e.g. Google Drive)
Google drive.

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
It's `rclone config` with the instructions about adding a google drive remote. Depending on the system, I press "y" or "n" on the last question, but the rest are identical. The log below is from the headless one, so I pressed "n" there.

Please note that both systems use an older version of rclone. I would install the newer one from the releases page, but I want to stick to what my distro provides. If the issue is not on google's end, I will install the deb for arm64 or use the binary from the zip.

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
$ rclone config -vv
2022/10/23 18:32:09 DEBUG : rclone: Version "v1.53.3-DEV" starting with parameters ["rclone" "config" "-vv"]
2022/10/23 18:32:09 NOTICE: Config file "/home/user/.config/rclone/rclone.conf" not found - using defaults
No remotes found - make a new one
n) New remote
s) Set configuration password
q) Quit config
n/s/q> n
name> peter
Type of storage to configure.
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
13 / Google Drive
   \ "drive"
Storage> 13
** See help for drive backend at: https://rclone.org/drive/ **

Google Application Client Id
Setting your own is recommended.
See https://rclone.org/drive/#making-your-own-client-id for how to create your own.
If you leave this blank, it will use an internal key which is low performance.
Enter a string value. Press Enter for the default ("").
client_id>
OAuth Client Secret
Leave blank normally.
Enter a string value. Press Enter for the default ("").
client_secret>
Scope that rclone should use when requesting access from drive.
Enter a string value. Press Enter for the default ("").
Choose a number from below, or type in your own value
 1 / Full access all files, excluding Application Data Folder.
   \ "drive"
scope> 1
ID of the root folder
Leave blank normally.

Fill in to access "Computers" folders (see docs), or for rclone to use
a non root folder as its starting point.

Enter a string value. Press Enter for the default ("").
root_folder_id>
Service Account Credentials JSON file path
Leave blank normally.
Needed only if you want use SA instead of interactive login.

Leading `~` will be expanded in the file name as will environment variables such as `${RCLONE_CONFIG_DIR}`.

Enter a string value. Press Enter for the default ("").
service_account_file>
Edit advanced config? (y/n)
y) Yes
n) No (default)
y/n>
Remote config
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine
y) Yes (default)
n) No
y/n> n
Please go to the following link: https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=202264815644.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=TObScy-wkJPW_k8yxvEFOA
Log in and authorize rclone for access
Enter verification code> ^C
```
Then the error on the screenshot comes up and I can not continue because it returns no verification code.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Update your version as that's the issue.

For support, please don't post issues here. 

Use the forums.

**Comment by pitsi** [comment]
As I said above, I would consider an upgrade, but the issue does not appear when adding a google drive remote with my credentials. I also tried another cli app for gdrive and its authentication returns the same error.

Last but not least, I do not open accounts here and there unless there is something very important.
