### ISSUE TITLE
error when specify duration like "90d"

### ISSUE THREAD

**Issue by hereisderek** [rclone/rclone#6522]
based on the document (attached below), duration like "90d" should be valid however it is now, i found that you'll have to specify to the "s" even if it was 0. e.g. "90d0m0s" works

> Time or duration options
> TIME or DURATION options can be specified as a duration string or a time string.
> 
> A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m". Default units are seconds or the following abbreviations are valid:
> 
> ms - Milliseconds
> s - Seconds
> m - Minutes
> h - Hours
> d - Days
> w - Weeks
> M - Months
> y - Years

**Comment by animosity22** [comment]
Any chance you have a version? Command you are testing that with? Basically the stuff in the bug template you've deleted.

**Comment by animosity22** [comment]
Some examples.

```
felix@gemini:~$ rclone ls GD: --min-age 1d
1504953150 jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
        0 test3/filetest
        0 linkdir/filetest
        0 test2/filetest
      375 crypt/rs88l6p51j4kp0g9if3j294ts0
      364 crypt/fns8mdipv34944sh8cv8kqpntc/vgiitg6j8vuehta15ci1ig135g/rs88l6p51j4kp0g9if3j294ts0
      364 crypt/vgiitg6j8vuehta15ci1ig135g/vgiitg6j8vuehta15ci1ig135g/rs88l6p51j4kp0g9if3j294ts0
      316 crypt/fns8mdipv34944sh8cv8kqpntc/fns8mdipv34944sh8cv8kqpntc/hosts
felix@gemini:~$ rclone version
rclone v1.60.0
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-52-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.2
- go/linking: static
- go/tags: none
```

**Comment by 7qqq** [comment]
Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by animosity22** [comment]
If you have any future questions, feel free to ask on the forums.

https://forum.rclone.org/

and we're happy to help out!
