### ISSUE TITLE
Issue of Rclone config

### ISSUE THREAD

**Issue by yulan0215** [rclone/rclone#6534]
#### What is the problem you are having with rclone?
reclone could not config.

#### What is your rclone version (output from `rclone version`)
1.58.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

windows 10

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone.exe config1

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

![image](https://user-images.githubusercontent.com/62309959/199764598-b51185cd-fb39-48dd-b353-c17d972b7d02.png)
config_type I set to be 3 here.

When I input the website here:
![image](https://user-images.githubusercontent.com/62309959/199764860-57c98ba4-6edb-4dc5-9c96-4a3013254895.png)

I had the problem like below:
![image](https://user-images.githubusercontent.com/62309959/199765048-75353af6-afb5-4328-8f1b-ef87c4e3e637.png)

Can you please give me some ideas? Thx

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
For use questions, please use the forums.

https://forum.rclone.org/
