### ISSUE TITLE
Add end-of-line marker to stats-one-line 

### ISSUE THREAD

**Issue by dustypigtv** [rclone/rclone#6535]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.60.0
- os/version: Microsoft Windows 11 Pro 22H2 (64 bit)
- os/kernel: 10.0.22621.674 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.19.2
- go/linking: static
- go/tags: cmount
PS C:\Users\jason>

#### What problem are you are trying to solve?
I have an app that monitors rclone status (when using --stats-one-line), and does some processing. However, if the processing takes too long, then the stdout buffer from stats fills up with no way to determine where 1 line ends and the next begins.  I saw that you removed the \n from the end of it back in 1.53, probably for a good reason.  But I often end up with data like this:

220.585 KiB / 21.392 GiB, 0%, 20.003 KiB/s, ETA 1w5d23h29m14s220.585 KiB / 21.392 GiB, 0%, 20.003 KiB/s, ETA 1w5d23h29m14s220.585 KiB / 21.392 GiB, 0%, 18.336 KiB/s, ETA 2w3h48m20s231.572 KiB / 21.392 GiB, 0%, 18.336 KiB/s, ETA 2w3h48m19s231.797 KiB / 21.392 GiB, 0%, 17.779 KiB/s, ETA 2w14h26m18s

#### How do you think rclone should be changed to solve that?
Add a trailing \0 to the end of every stdout write when using --stats-one-line, so we could split on the null and process completed output

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Are you using `-P` or `--progress` as well? If so try without it.

If you really want parsable output then use `--use-json-log`

**Comment by dustypigtv** [comment]
Without the --progress, no stats are shown at all.  I had previously tried the --use-json-log, but it doesn't include live progress indicators

**Comment by ncw** [comment]
You need to add -v to see stats, or change the log level of the stats with --stats-log-level NOTICE

Stats come every 60s by default, use --stats 10s to make them come every 10s.

**Comment by dustypigtv** [comment]
I must be missing something.  I tried: rclone copy src dst --progress --stats 1s --log-file log.log --use-json-log -v, but never got any stats that had percent, size transfered, total transfers, etc.  Just some info about the objects that were transfered.  I'm trying to get, in a parsable way, about once a second:   transfered files / total to transfer, transfered size / total transfer size, percent complete, and ETA.  The --stats-one-line flag is close, but there is no way to separate the end of 1 report from rclone and the beginning of the next

**Comment by ncw** [comment]
Remove the `--progress` from this and add `--stats-log-level NOTICE` and remove the `-v` if you don't want to see individual files transferred

So this if you want JSON logs

    rclone copy src dst  --stats 1s --log-file log.log --use-json-log --stats-log-level NOTICE

Or alternatively this if you want plain text logs

    rclone copy src dst  --stats 1s --log-file log.log --stats-log-level NOTICE --stats-one-line

**Comment by animosity22** [comment]
Answered.
