### ISSUE TITLE
cmd: Enable SIGINFO handler on FreeBSD

### ISSUE THREAD

**Issue by x3-apptech** [rclone/rclone#6536]
#### The associated forum post URL from `https://forum.rclone.org`
N/A

#### What is your current rclone version (output from `rclone version`)?
rclone v1.59.2-DEV
- os/version: freebsd 13.1-release-p2 (64 bit)                         - os/kernel: 13.1-release-p2 (amd64)                                   - os/type: freebsd                                                     
- os/arch: amd64                                                       
- go/version: go1.19.2                                                 
- go/linking: dynamic                                                  
- go/tags: none

(Installed from FreeBSD Ports/Quarterly)

#### What problem are you are trying to solve?
The SIGINFO handler (which is triggered when Ctrl-T is pressed) is currently only enabled for builds on Darwin. This should be enabled on FreeBSD as well (as it follows the same semantics as Darwin).

#### How do you think rclone should be changed to solve that?
The proposed enhancement requires 2 minor changes, namely:

In file https://github.com/rclone/rclone/blob/master/cmd/siginfo_darwin.go

From
`//go:build darwin`
`// +build darwin`
to
`//go:build darwin || freebsd`
`// +build darwin freebsd`

and in file https://github.com/rclone/rclone/blob/master/cmd/siginfo_others.go

From
`//go:build !darwin`
`// +build !darwin`
to
`//go:build !darwin && !freebsd`
`// +build !darwin !freebsd`

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Please send a pull request. Sounds like a good idea - thank you.
