### ISSUE TITLE
Remotes defined with env vars are not listed using config/listremotes via rcd

### ISSUE THREAD

**Issue by elthariel** [rclone/rclone#6540]
#### The associated forum post URL from `https://forum.rclone.org`

I have not found any mention of that issue on the forum, or on existing issues

#### What is the problem you are having with rclone?

I'm using `rclone rcd` on a kubernetes cluster to move my backups around and out of the cluster.

The rclone rcd have the following env vars:
```
env | grep RCLONE_CONFIG
RCLONE_CONFIG_INTERNAL_PROVIDER=Minio
RCLONE_CONFIG_INTERNAL_TYPE=s3
RCLONE_CONFIG_INTERNAL_ACCESS_KEY_ID=bH0t8Cb4b8UrPpXV
RCLONE_CONFIG_INTERNAL_SECRET_ACCESS_KEY=GMBGlXPVsLzCzzQnohBL86Il
RCLONE_CONFIG_INTERNAL_ENDPOINT=https://minio.foundation
```
> Those are temporary credentials, this is not a leak :)

Despite the variables being defined correctly running `rclone rc config/listremotes` returns an empty array.

If I use `--rc-serve`, the remote is correctly listed and working.
If I try to access the remote using `operations/list` it works correctly.

I've found this extremely confusing and spent a few hours trying to debug something that was actually working.

It seems the function `config.FileSections()` is not called when the `listremotes` operation is called via rc.

So essentially my question is: is it a bug or a feature ?If this is expected behavior, I'd like to see something added in the doc to save the next fellow the few hours I've lost. If this is a bug, let's try to fix it ?

#### What is your rclone version (output from `rclone version`)

```
rclone v1.60.0
- os/version: alpine 3.16.2 (64 bit)
- os/kernel: 5.4.0-122-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.2
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

The official rclone docker image

#### Which cloud storage system are you using? (e.g. Google Drive)

S3, but probably irrelevant here

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by elthariel** [comment]
The rc listremotes implementation here doesn't lookup env vars, just load the config file:

https://github.com/rclone/rclone/blob/53f831f40a7341cc3da199b0266ea573b6d94551/fs/config/rc.go#L74

**Comment by ncw** [comment]
Not sure whether this is a big or not!

Listremotes was introduced to look at the config file. Are remotes defined with env vars in the config file?

Why were you running listremotes? Maybe we should start there

**Comment by elthariel** [comment]
I was running listremotes to check if my configuration was correct.

> Listremotes was introduced to look at the config file. 

Fine with me. If that's not its job, that's ok. But I definitely think it should be mentionned in the documentation. That was very confusing

> Are remotes defined with env vars in the config file?

Nope. Just via env vars
