### ISSUE TITLE
Unable to move, remane files in storj s3 remote

### ISSUE THREAD

**Issue by dominus-imperium** [rclone/rclone#6550]
#### What is the problem you are having with rclone?
Unable to rename or move files in rclone s3 storj remote. 

#### What is your rclone version (output from `rclone version`)
rclone v1.60.0
- os/version: arch (64 bit)
- os/kernel: 5.15.77-1-lts (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.2
- go/linking: dynamic
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Linux (arch) 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)

Storj S3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone move or mv command when mounted

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

<3>ERROR : rajesh/tester-01.cap: Dir.Rename error: Fs "S3 root" can't rename files (no server-side Move or Copy)
<3>ERROR : rajesh/tester-01.cap: Dir.Rename error: Fs "S3 root" can't rename files (no server-side Move or Copy)
<3>ERROR : IO error: Fs "S3 root" can't rename files (no server-side Move or Copy)
<7>DEBUG : rajesh/: >Rename: err=Fs "S3 root" can't rename files (no server-side Move or Copy)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
What does your rclone.conf look like with the keys/secrets removed?

**Comment by ncw** [comment]
We don't current allow `provider = Storj` to have access to rename on s3 as when we implemented that it didn't work.

It may work now though, let me give it a test...

It did work, so here is a version of rclone which should work for you - can you give it a go please?

[v1.61.0-beta.6534.3daaeeea3.fix-6550-storj-copy](https://beta.rclone.org/branch/fix-6550-storj-copy/v1.61.0-beta.6534.3daaeeea3.fix-6550-storj-copy/) on branch [fix-6550-storj-copy](https://github.com/rclone/rclone/tree/fix-6550-storj-copy) (uploaded in 15-30 mins)

**Comment by dominus-imperium** [comment]
it works perfectly. No errors. When will this added to the stable version?

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.61 and v1.60.1 which should be out in a week or two.

**Comment by Baneeishaque** [comment]
Issue still exists on latest rclone stable version.

**Comment by ncw** [comment]
@Baneeishaque please make a new issue with full details - thanks

**Comment by dominus-imperium** [comment]
I can confirm that it does not work on the stable and just tried it also doesn't work anymore on the beta. It used to work when i used it a week before.

**Comment by ncw** [comment]
This worked fine for me on the beta

    rclone moveto -vv TestStorj:rclone/file2.txt TestStorj:rclone/file3.txt

What did you try? What error message did it give?

**Comment by dominus-imperium** [comment]
then i tried moveto:

`sj0:rajesh/"econ -main2.apkg" sj0: -P -vv`

gives output:

<7>DEBUG : rclone: Version "v1.60.1" starting with parameters ["rclone" "moveto" "sj0:rajesh/econ -main2.apkg" "sj0:" "-P" "-vv"]
<7>DEBUG : rclone: systemd logging support activated
<7>DEBUG : Creating backend with remote "sj0:rajesh/econ -main2.apkg"
<7>DEBUG : Using config file from "/home/rajesh/.config/rclone/rclone.conf"
<7>DEBUG : fs cache: adding new entry for parent of "sj0:rajesh/econ -main2.apkg", "sj0:rajesh"
"sj0:" is a directory

**Comment by dominus-imperium** [comment]
Interestingly, when i try to put that file to root of remote with moveto or move you get the respective results shown in above replies. 
However, when i try to move the file to another folder with moveto it gives the same responce as moveto to root of remote, but when using move to move to another folder it works. 

`rclone move sj0:rajesh/"econ -main2.apkg" sj0:sj-credentials/ -P -vv`

output:

<7>DEBUG : rclone: Version "v1.60.1" starting with parameters ["rclone" "move" "sj0:rajesh/econ -main2.apkg" "sj0:sj-credentials/" "-P" "-vv"]
<7>DEBUG : rclone: systemd logging support activated
<7>DEBUG : Creating backend with remote "sj0:rajesh/econ -main2.apkg"
<7>DEBUG : Using config file from "/home/rajesh/.config/rclone/rclone.conf"
<7>DEBUG : fs cache: adding new entry for parent of "sj0:rajesh/econ -main2.apkg", "sj0:rajesh"
<7>DEBUG : Creating backend with remote "sj0:sj-credentials/"
<7>DEBUG : fs cache: renaming cache item "sj0:sj-credentials/" to be canonical "sj0:sj-credentials"
2022-12-06 18:57:01 DEBUG : econ -main2.apkg: Need to transfer - File not found at Destination
2022-12-06 18:57:01 DEBUG : econ -main2.apkg: md5 = 1056876bab55ad44939e3b07a110167c OK
2022-12-06 18:57:01 INFO  : econ -main2.apkg: Copied (server-side copy)
2022-12-06 18:57:02 INFO  : econ -main2.apkg: Deleted
Transferred:       31.733 KiB / 31.733 KiB, 100%, 31.729 KiB/s, ETA 0s
Checks:                 2 / 2, 100%
Deleted:                1 (files), 0 (dirs)
Renamed:                1
Transferred:            1 / 1, 100%
Elapsed time:         2.3s
<6>INFO  : 
Transferred:       31.733 KiB / 31.733 KiB, 100%, 31.729 KiB/s, ETA 0s
Checks:                 2 / 2, 100%
Deleted:                1 (files), 0 (dirs)
Renamed:                1
Transferred:            1 / 1, 100%
Elapsed time:         2.3s

<7>DEBUG : 5 go routines active

**Comment by dominus-imperium** [comment]
Actually all the things i have done so far have been folder to folder so I never thought about this. I don't think this is a problem with rclone but how storj allows files to be stored. If i remember correctly every file has to be in a bucket and cannot exist at the root. So rclone is doing the right thing and we are doing it wrong. I think.

However, i am not sure why moveto did not work in the correct scenario, am I using it wrong?
