### ISSUE TITLE
Fish shell misdetection

### ISSUE THREAD

**Issue by blenderfreaky** [rclone/rclone#6552]
EDIT: This issue seems to come from misdetecting the fish-shell as cmd.

Original issue:
## SFTP remote not working properly with files that have a dollar sign in their filename

When copying a file with a dollar sign in its name to (or from) an SFTP remote, no file gets copied and the md5sum check fails with an empty md5sum. I assume this is because it tries to expand the dollar as a shell variable (the md5sum command in the log replaces "foo $bar" with "foo ").

I am using up-to-date Arch Linux both locally and the remote. This occurs with current rclone `v1.60.0` as well as on `v1.61.0-DEV`.
Originally I assumed this might be due to running fish shell on the server, but it happens with bash as well.

A simple repro:
```
cd ~/rclone-repro
echo "test" >> "abc \$def ghj"
rclone copy abc\ \$def\ ghj thekka:rclone-repro -vv --log-file bug.log
```
Outputs: [bug.log](https://github.com/rclone/rclone/files/9961323/bug.log)

Note that copying via the sftp command directly works without issue in both directions (uploading and downloading), so it's not an issue of the target file system not liking the name.
Downloading the file with rclone after copying via regular sftp results in basically the same error.

**Comment by albertony** [comment]
From bug log:

> Shell type "cmd" from config

That is wrong. If you try to remove the `shell_type` line from your config file and run a command against the remote it should auto-detect. And if that works as it should, you should end up with `unix` as shell type in your config file afterwards. If this is not what happens, you can force it by setting that value explicit, but if this is the case I would like to see a debug log from the auto-detection process...

**Comment by blenderfreaky** [comment]
Removing `shell_type` from the config *and* changing the shell to bash works.
However when using fish it seems like the fish shell is being misdetected as cmd:

```
<7>DEBUG : sftp://thekka@192.168.2.135:22/rclone-repro/: New connection 192.168.2.157:52944->192.168.2.135:22 to "SSH-2.0-OpenSSH_9.1"
<7>DEBUG : sftp://thekka@192.168.2.135:22/rclone-repro/: Running shell type detection remote command: echo ${ShellId}%ComSpec%
<7>DEBUG : sftp://thekka@192.168.2.135:22/rclone-repro/: Remote command result: 
<7>DEBUG : sftp://thekka@192.168.2.135:22/rclone-repro/: Shell type "cmd" detected (set option shell_type to override)
<7>DEBUG : Saving config "shell_type" in section "thekka" of the config file
```

For reference this is what fish outputs for the shell detection command:
```
thekka@thekka ~> echo ${ShellId}%ComSpec%
fish: Variables cannot be bracketed. In fish, please use {$ShellId}.
echo ${ShellId}%ComSpec%
      ^
thekka@thekka ~> echo {$ShellId}%ComSpec%

thekka@thekka ~>
```

**Comment by albertony** [comment]
Aha, that's useful info - thanks.

Seems fish shell have some special handling of percent "encoding"? In (ba)sh `echo %ABC%` prints `%ABC%` assuming a variable with name "ABC" does not exist. But this is not the case in fish?

**Comment by blenderfreaky** [comment]
I'm not entirely sure why, but it seems to not output it (or any other string) when coming directly after (no whitespace) after an unset variable:

```
~> echo {$foo}bar

~> echo {$foo} bar
bar
~> set foo ""
~> echo {$foo}bar
bar
```
Same with `%bar%` instead of `bar`

**Comment by albertony** [comment]
Ok.. I installed fish into a test environment myself now, and can confirm your observations. What I see is surrounding with quotes changes the result:

```
~> echo {$foo}%bar%

~> echo "{$foo}%bar%"
{}%bar%
```

But the fix is not simply adding quotes, since we still have to consider the different variable syntax `${foo}` vs `{$foo}`.

Need to think about this one. Until then, the workaround is to explicitly set value `unix` for `shell_type` in config or with command-line argument `--sftp-shell-type` (which is somewhat recommended anyway, https://rclone.org/sftp/#shell-access-considerations 🙈 ).

But thanks for the issue report, it is something we should improve.

**Comment by albertony** [comment]
I think I figured out an easy and minimalistic, i.e. low risk, fix: Simply fall-back to the default "unix" shell type when the echo command used for auto-detection produces no/empty results, like in your case:

> <7>DEBUG : sftp://thekka@192.168.2.135:22/rclone-repro/: Remote command result: 

The error message you saw when running interactively is on stderr and will not be logged in this case:

> fish: Variables cannot be bracketed. In fish, please use {$ShellId}.
> echo ${ShellId}%ComSpec%
>       ^

I created a PR for it, and a beta build should be available in a few minutes, here: https://beta.rclone.org/branch/sftp-shell-type-fish

If you are willing to test it, that would be appreciated.

Oh, and I assume fish can be treated the same way as other unix shells in rest of the code, I have not looked more into that, so it is only the auto-detection part which is fixed. The shell type is only related to file path escaping rules, used for md5/sha checksums and for the about command when it resorts to "df -k" command.

**Comment by blenderfreaky** [comment]
Can confirm that this works on my setup. I *believe* fish escaping is the same as bash. It worked for all files I tested it on and I have a few very weird filenames.

In my opinion it may be a good idea to move the shell type into the regular config instead of the advanced config, in order to avoid confusion for people using unusual shells.

Thanks for the help  ^^
