### ISSUE TITLE
update docs for using proxy server

### ISSUE THREAD

**Issue by asdffdsazqqq** [rclone/rclone#6565]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/windows-proxy-with-user-password/33860/5

#### What is your current rclone version (output from `rclone version`)?
does not matter. as this is about updating documentation.

#### What problem are you are trying to solve?
need to update docs, to make clear how to use a proxy with username + password

#### How do you think rclone should be changed to solve that?
[https://rclone.org/faq/#can-i-use-rclone-with-an-http-proxy](https://rclone.org/faq/#can-i-use-rclone-with-an-http-proxy)
change "export http_proxy=http://proxyserver:12345"
to
"export http_proxy=http://proxyserver:12345

Note: if the proxy server requires a username and password, then use
export http_proxy=http://username:password@proxyserver:12345"

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Sounds good. Want to propose a change? You can do that by clicking the pencil icon here: https://github.com/rclone/rclone/blob/master/docs/content/faq.md
