### ISSUE TITLE
"fuse device not found" encountered during trying to mount a WebDAV

### ISSUE THREAD

**Issue by stucowade** [rclone/rclone#6566]
#### What is your current rclone version (output from `rclone version`)?

Docker image: rclone/rclone:latest
rclone v1.60.0
- os/version: alpine 3.16.2 (64 bit)
- os/kernel: 4.12.9-041209-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.2
- go/linking: static
- go/tags: none

#### What problem are you are trying to solve?
I ran into a headache while I was trying to mount my WebDAV in Linux by using the latest docker images, output as below:
2022/11/14 08:49:46 mount helper error: fusermount: fuse device not found, try 'modprobe fuse' first
2022/11/14 08:49:46 Fatal error: failed to mount FUSE fs: fusermount: exit status 1

I have tried to delete the fuse on the host, install it again and reboot but it doesn't work.
The "modprobe fuse" is done on the host too.

#### How do you think rclone should be changed to solve that?
I have tried to read the documentation and search on the forum but I can''t find any useful information.
Can anyone help me with this?
Many thanks.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Forums would have been a great place to get support for general questions rather than posting an issue.

https://rclone.org/docker/

Did you follow that or do something else?

**Comment by stucowade** [comment]
> Forums would have been a great place to get support for general questions rather than posting an issue.
> 
> https://rclone.org/docker/
> 
> Did you follow that or do something else?

Thank you for your instruction. 
I read and did it following the steps out there but it did not work either.
output remains: 
mount helper error: fusermount: fuse device not found, try 'modprobe fuse' first
 Fatal error: failed to mount FUSE fs: fusermount: exit status 1

I created a volumn, linked it into the rclone container, and when I tried to mount the WebDAV, it failed again.
I really have no idea and get lost, can you help on this?
Thank you,

**Comment by stucowade** [comment]
> You did this?
> 
> ```
> The FUSE driver is a prerequisite for rclone mounting and should be installed on host:
> 
> sudo apt-get -y install fuse
> ```

Yes I did it.
Now the problem is solved, by "apt-get update" and "apt-get upgrade" and reboot.
It's weird but I am glad to see it works.
Thanks to all!
