### ISSUE TITLE
Issue with rclone status output starting from 1.50

### ISSUE THREAD

**Issue by sneak** [rclone/rclone#6574]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/issue-with-rclone-output-starting-from-1-50/15764

#### What is the problem you are having with rclone?

Status output is displayed incorrectly when output is not a tty (e.g. when using `script` or `tee` etc).

Here is an example gif: https://imgur.com/b3jS92a

#### What is your rclone version (output from `rclone version`)

cyberdyne:~$ rclone version
rclone 1.60.0
- os/version: darwin 12.5 (64 bit)
- os/kernel: 21.6.0 (arm64)
- os/type: darwin
- os/arch: arm64
- go/version: go1.19.3
- go/linking: dynamic
- go/tags: cmount
cyberdyne:~$

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

macOS 12.5 Monterey

#### Which cloud storage system are you using? (e.g. Google Drive)

sftp

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone sync`

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Adding a `2>&1` will fix your command I think

    rclone sync -P .... 2>&1 | tee ...

There has been some discussion as to whether rclone should be using stdout or stderr for its --progress output.

**Comment by animosity22** [comment]
Can you share what you ran and what the output was?

**Comment by sneak** [comment]
`exec > >(tee -a $LOGDIR/$YYYYMMDD.$(date -u +%s).tocloud-backup.log) 2>&1`

followed by any rclone command that outputs status, eg:

```
 14     rclone sync \
 13         --retries 99999 \
 12         --progress \
 11         --progress-terminal-title \
 10         --stats-unit bits \
  9         "$TD/$BACKUPNAME" \
  8         fsn1-storagebox-10T:"$BACKUPNAME"/ 2>&1
  ```
  
  Same issue with and without the `2>&1` on the command.  This is mentioned in the linked thread.

**Comment by animosity22** [comment]
What's the goal for progress anyway as it's really meant for the terminal and not for scripts?

I'd just use.

```
--stats-one-line -v
```

**Comment by sneak** [comment]
Logging the output in a non-corrupted manner should be possible even with interactive usage, which is my use case.  I use the program non-interactively (in a script, that makes a log) but I still want progress/status output while it runs.

Using the command line options you've proposed, along with `--progress`, still exhibits the problem:

```
0 B / 44.226 KiB, 0%, 0 bit/s, ETA - (xfr#0/7)125 B / 44.226 KiB, 0%, 0 bit/s, ETA - (xfr#0/7)
2022-11-19 19:18:48 INFO  : SHASUMS.txt: Copied (new)
125 B / 44.226 KiB, 0%, 998 bit/s, ETA 6m1s (xfr#0/7)125 B / 44.226 KiB, 0%, 998 bit/s, ETA 6m1s (xfr#1/7)125 B / 44.226 KiB, 0%, 998 bit/s, ETA 6m1s (xfr#1/7)691 B / 44.226 KiB, 2%, 499 bit/s, ETA 11m54s (xfr#1/7)1.055 KiB / 44.226 KiB, 2%, 499 bit/s, ETA 11m48s (xfr#1/7)
2022-11-19 19:18:50 INFO  : SHASUMS.txt.gpg: Copied (new)
1.055 KiB / 44.226 KiB, 2%, 499 bit/s, ETA 11m48s (xfr#1/7)
2022-11-19 19:18:50 INFO  : priv.age: Copied (new)
1.055 KiB / 44.226 KiB, 2%, 2.812 Kibit/s, ETA 2m2s (xfr#2/7)1.055 KiB / 44.226 KiB, 2%, 2.812 Kibit/s, ETA 2m2s1.055 KiB / 44.226 KiB, 2%, 2.812 Kibit/s, ETA 2m2s42.850 KiB / 44.226 KiB, 97%, 2.108 Kibit/s, ETA 5s^C
```

This isn't a "you're holding it wrong", this is a bug in the output, a regression.  It happens even with `--stats-one-line`.  Per the linked discussion thread it does not happen in v1.49.5, only in 1.50+.

**Comment by animosity22** [comment]
I'm not debating on if it's a bug or not a bug as I was suggesting a workaround as the bug part was documented on the thread you linked and looks like 'leave it as is' was the option picked.

I also didn't say to use progress as that breaks it as you've shared. I use a log file and was merely trying to offer some advice/help/other ways to do something. Apologies for trying to be helpful. Good luck.

**Comment by sneak** [comment]
Sorry, tone didn't come across in the text.  Thanks for the workaround suggestion, but that doesn't solve my problem.  (I'd just use rsync as I'm rcloning to an sftp but rsync is stuck in the 80s and doesn't have good realtime status display of ETA/etc.)

**Comment by RoSk0** [comment]
I'm trying to understand if I'm affecting, so sorry in advance if the question is not relevant. I'm new to rclone.

I'm using rclone in a script and would love to see periodic output . This is how call it `rclone --stats 1m --stats-one-line-date sync REMOTE_SWIFT LOCAL`

Should I receive the output once a minute? I tested on versions v1.49.5, v1.50.2 and v1.60.1 and see not output. Suspecting tham I'm doing something wrong...

**Comment by ncw** [comment]
@RoSk0 you need to add either `-v` or `--stats-log-level NOTICE`

**Comment by RoSk0** [comment]
Thanks @ncw ! That works!

**Comment by hakong** [comment]
Any update on this? I can't get the output with newlines in the journal when running rclone in a systemd unit.

**Comment by animosity22** [comment]
This looks solved/answered.

If you have a new question, please ask on the forums:

https://forum.rclone.org

**Comment by hakong** [comment]
What commit was this fixed in?

**Comment by ncw** [comment]
`--progress` was never designed to go in the log.

Use `-v` for verbose stats and use `--stats 1s` to print the stats more often.
