### ISSUE TITLE
mount gdrive with vfs full cache - vfs cache: failed to _ensure cache internal error: downloaders is nil - reopens #5984

### ISSUE THREAD

**Issue by cad0p** [rclone/rclone#6580]
#### What is the problem you are having with rclone?

Hi and thanks for your attention :)

I am reopening https://github.com/rclone/rclone/issues/5984 with this one as I have been experiencing it.

I have a Raspberry Pi 4 and I was testing out the download of a large torrent, when I saw that it frequently errors out. It appears that the error is not fatal in the sense that if you delete and re-add the torrent, then re-check the contents, it will continue from where it left off.
Edit: you need to delete the corrupted file, though (which you can see from the logs)

The structure of this particular torrent was 75GB with individual files of about 8GB each.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.53.3-DEV
- os/arch: linux/arm64
- go version: go1.15.9
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Raspbian OS (Raspberry Pi 4), 64bit ARMv8, headless

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
rclone mount \
        --allow-other \
        --buffer-size 256M \
        --dir-cache-time 72h \
        --drive-chunk-size 32M \
        --fast-list \
        --log-file /home/pi/rclone_debug.log \
        --cache-dir /media/mybook/tmp/rclone \
        --cache-tmp-upload-path /media/mybook/tmp/rclone \
        --vfs-read-chunk-size 128M \
        --vfs-read-chunk-size-limit off \
        --vfs-cache-mode full \
        --buffer-size 32M \
        --vfs-read-ahead 10G \
        --vfs-cache-max-size 1.5T \
        --vfs-cache-max-age 1000000h \
        --vfs-cache-poll-interval 5m \
        Filesystem: /home/pi/gdrive/Filesystem &
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
This is not possible, but I have the normal logs and will upload them here:

[rclone_debug.log](https://github.com/rclone/rclone/files/10048175/rclone_debug.log)

I guess the errors regarding the "source file is being updated" are not relevant and in fact they may be downgraded to `WARNING`.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Update as your version is years old.

If you still hit issues, please post on the forums for general support.

Thanks.

https://forum.rclone.org

**Comment by cad0p** [comment]
Thanks! Didn't realize it was years old 😅

Will post on the forum if the problem reappears.
