### ISSUE TITLE
Rclone failing to authenticate to a kerberized Hadoop cluster

### ISSUE THREAD

**Issue by helpyoke** [rclone/rclone#6581]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/rclone-failing-to-authenticate-to-a-kerberized-hadoop-cluster/34253/1

#### What is the problem you are having with rclone?
I am trying to read data from a Kerberized Hadoop cluster using rclone, but it is failing with no available namenodes error message. The root cause seems to be related to kerberos.

#### What is your rclone version (output from `rclone version`)
rclone v1.60.1

os/version: redhat 7.9 (64 bit)
os/kernel: 3.10.0-1160.11.1.el7.x86_64 (x86_64)
os/type: linux
os/arch: amd64
go/version: go1.19.3
go/linking: static
go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Red Hat Enterprise Linux Server release 7.9, 64 bits

#### Which cloud storage system are you using? (e.g. Google Drive)
HDFS

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
./rclone --config=rclone.conf ls -vv remote-hdfs:<path-to-my-file>

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
./rclone --config=rclone.conf ls -vv remote-hdfs:<path-to-my-file>
2022/11/17 18:32:57 DEBUG : rclone: Version "v1.60.1" starting with parameters ["./rclone" "--config=rclone.conf" "ls" "-vv" "remote-hdfs:<path-to-my-file>"]
2022/11/17 18:32:57 DEBUG : Creating backend with remote "remote-hdfs:<path-to-my-file>"
2022/11/17 18:32:57 DEBUG : Using config file from "/tmp/rclone.conf"
2022/11/17 18:32:57 Failed to create file system for "remote-hdfs:<path-to-my-file>": no available namenodes: SASL handshake: [Root cause: KDC_Error] KDC_Error: TGS Exchange Error: kerberos error response from KDC when requesting for <my-principal-name>: KRB Error: (7) KDC_ERR_S_PRINCIPAL_UNKNOWN Server not found in Kerberos database```

Also my config file is the following
[remote-hdfs]
type = hdfs
namenode = <host>:<port>
username = <my-username>
data_transfer_protection = authentication
service_principal_name = <my-principal-name>

Based on the error message KDC_ERR_S_PRINCIPAL_UNKNOWN, it seems that the service principal name is unknown. But in my case, I can confirm that my principal is listed on the KDC server.

Any ideas how to resolve this ?

**Comment by helpyoke** [comment]
Hello :)

Thanks for your help, the issue can be closed. I was using my user principal name and not the service principal name.

**Comment by animosity22** [comment]
You can close it out @helpyoke as you don't need us to do that :)
