### ISSUE TITLE
Rclone not copying Content-Type from source file

### ISSUE THREAD

**Issue by shriDeveloper** [rclone/rclone#6586]
#### What is the problem you are having with rclone?
Rclone not copying Content-Type from source file , when i checked the destination file its type is always binary/octet-stream

#### What is your rclone version (output from `rclone version`)
rclone v1.58.0-beta.5833.5c646dff9

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
- os/version: Microsoft Windows 11 Home Single Language 22H2 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)
R2 (CLoudflare) (I am migrating objects from AWS S3)

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
C:\rclone>rclone copy s3:<source-file-url> r2demo:<destination-url>

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
C:\rclone>rclone copy s3:<source-url> r2demo:<destination-url> -vv

2022/11/27 09:09:11 DEBUG : rclone: Version "v1.58.0-beta.5833.5c646dff9" starting with parameters ["rclone" "copy" "s3:<source-url>" "r2demo:<destination-url>" "-vv"]
2022/11/27 09:09:11 DEBUG : Creating backend with remote "<source-url>"
2022/11/27 09:09:11 DEBUG : Using config file from "C:\\Users\\91721\\.config\\rclone\\rclone.conf"
2022/11/27 09:09:13 DEBUG : fs cache: adding new entry for parent of "s3:<source-url>", "s3:<destination-url>"
2022/11/27 09:09:13 DEBUG : Creating backend with remote "r2demo:sellkitedigitaldownloads/mp3"
2022/11/27 09:09:13 DEBUG : 001bj-ra03-denke_fuhle_sage_nein.mp3: Need to transfer - File not found at Destination
2022/11/27 09:10:05 INFO  : 001bj-ra03-denke_fuhle_sage_nein.mp3: Copied (new)
2022/11/27 09:10:05 INFO  :
Transferred:       68.668 MiB / 68.668 MiB, 100%, 1.817 MiB/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:        53.2s

2022/11/27 09:10:05 DEBUG : 7 go routines active

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
You seem to have some beta version.

Can you test on the latest stable?

https://rclone.org/install/

**Comment by animosity22** [comment]
Feel free to post on the forums if you run into an issue.
