### ISSUE TITLE
OracleObjectStorage: Add support for storage_class (set tier STANDARD | INFREQUENT_ACCESS | ARCHIVE)

### ISSUE THREAD

**Issue by cberni** [rclone/rclone#6588]
#### The associated forum post URL from `https://forum.rclone.org`

https://github.com/rclone/rclone/pull/6332
@msays2000 

#### What is the problem you are having with rclone?

there is no way to set storage_class (STANDARD | INFREQUENT_ACCESS | ARCHIVE)

#### What is your rclone version (output from `rclone version`)

rclone v1.60.1
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-1021-oracle (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.3
- go/linking: static
- go/tags: none

#### Which cloud storage system are you using? (e.g. Google Drive)

OracleObejctStorage

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by msays2000** [comment]
the code has support for storage_class, but I think, I forgot to expose it as an option. Please file a bug with OracleObejctStorage: Add support for storage_class (set tier STANDARD | INFREQUENT_ACCESS | ARCHIVE)

https://github.com/rclone/rclone/blob/master/backend/oracleobjectstorage/options.go#L64

you may test by adding the config property manually like this

[myoracle]
 type = oracleobjectstorage 
 namespace = id<redacted>fn 
 compartment = ocid1.compartment.oc1..aa<redacted>k7a 
 region = us-ashburn-1 
 provider = instance_principal_auth
storage_tier = ARCHIVE

but anyway, we will fix it to expose the option and test it out.

**Comment by msays2000** [comment]
fixed in https://github.com/rclone/rclone/pull/6694. Storage_Tier support is already there. Forgot to expose it in backend config. Added it now in https://github.com/rclone/rclone/pull/6694
