### ISSUE TITLE
⌂192% [root:/work] # go build /root/go/pkg/mod/golang.org/x/net@v0.2.0/http2/transport.go:19:2: package io/fs is not in GOROOT (/usr/lib/go-1.15/src/io/fs)

### ISSUE THREAD

**Issue by brendoncdrew** [rclone/rclone#6593]
#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment]
Are you trying to build with go version 1.15? If so, you need to upgrade.

> Go version 1.17 or newer is required

(https://rclone.org/install/#source)

If something else, you need to add substantially more details.

**Comment by animosity22** [comment]
Please post on the forums for general questions/help.

https://forum.rclone.org
