### ISSUE TITLE
rclone with openwrt: zero size mounted folder

### ISSUE THREAD

**Issue by laaubert** [rclone/rclone#6594]
#### What is the problem you are having with rclone?
I'm  mounting a oneDrive folder on a miniPC running openwrt. I can read/write to the mounted folder but it is mounted with a size of zero and it seems it's preventing one of my application to access to it.  This is the only difference I can find when comparing to a local folder where it is working (both with exact same ownership and permissions)

#### What is your rclone version (output from `rclone version`)

rclone v1.60.1
- os/version: openwrt 22.03.2 (64 bit)
- os/kernel: 5.10.146 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.18.8
- go/linking: dynamic
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
openwrt 22.03.2 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)

oneDrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

You can see from the command below the folder is mounted with a size of zero:
```
root@Home-box:~# ls -l /opt/jeedom/app/html/ | grep backup
drwxrwxr-x    1 33       www-data         0 Dec  2 11:36 backup
```
But in the application UI, the content of this folder is showing empty even if my application is able to write in it:

```
root@Home-box:~# ls -l /opt/jeedom/app/html/backup/
-rw-rw-r--    1 33       www-data 218608603 Dec  2 11:42 backup-Jeedom-3.3.59-2022-12-02-11h41.tar.gz
```

Below is the command I use to mount the folder:

`rclone --vfs-cache-mode writes --uid=33 --gid=33 --umask=002 mount oneDrive:HomeBox-Backup/Jeedom /opt/jeedom/app/html/backup`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

rclone doesn't have any issue to get the real size of the folder I'm mounting so I'm wondering why the local size is 0:

```
root@Home-box:~# rclone size oneDrive:HomeBox-Backup --config /etc/config/.rclone/rclone.conf
Total objects: 111 (111)
Total size: 745.381 MiB (781588268 Byte)
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
I'm not quite following the issue.

Directories always show up as zero.

**Comment by laaubert** [comment]
So it is expected in this case ? Usually default size is 4096. If it is an expected behavior then I’ll need to find another way. Thanks,Laurent. From: Animosity ***@***.***>Date: Friday, 2 December 2022 at 14:45To: rclone/rclone ***@***.***>Cc: laaubert ***@***.***>, Author ***@***.***>Subject: Re: [rclone/rclone] rclone with openwrt: zero size mounted folder (Issue #6594)I'm not quite following the issue.Directories always show up as zero.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by animosity22** [comment]
Yes, expected, for any questions, please use the forums as that's better than filing a bug report.

https://forum.rclone.org
