### ISSUE TITLE
"rclone serve webdav" with password auth can't be mounted on windows

### ISSUE THREAD

**Issue by cwyc** [rclone/rclone#6596]
#### Output of `rclone version`
```
rclone v1.61.0-DEV
- os/version: nixos 22.11 (Raccoon) (64 bit)
- os/kernel: 5.15.80 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.3
- go/linking: dynamic
- go/tags: none
```
#### Describe the issue
`rclone serve webdav` shares can't be mounted by Windows 10 if password auth is enabled, but works if password auth is disabled.

To replicate:
- Open port 8080 on firewall
- Run `htpasswd -c -B htpasswd user` and enter a password
- Run `rclone serve webdav . --addr :8080 --htpasswd htpasswd`
- On a Windows machine, select Explorer > This PC > Map network drive
- Enter `http://<server address>:8080/` in "Folder" field and select "Finish"
- A dialog appears: https://imgur.com/a/AYsqEuc
--
- Run `rclone serve webdav . --addr :8080`
- On a Windows machine, select Explorer > This PC > Map network drive
- Enter `http://<server address>:8080/` in "Folder" field and select "Finish"
- The network drive is successfully mounted

**Comment by ncw** [comment]
Is windows expecting you to put the username / password in the URL?

So this (for windows to prompt for the password)

    http://user@<server address>:8080/

Or maybe this (including the password).

    http://user:password@<server address>:8080/

Does that help?

**Comment by cwyc** [comment]
No, neither of these address schemes work. There is also an option "Connect using different credentials", which brings up a prompt for username and password, but the same error appears afterward.

**Comment by ncw** [comment]
Can you run rclone with -vv --dump bodies and see what windows is sending rclone. I think that works, if not a packet capture would be great.

**Comment by piyushgarg** [comment]
I am able to get it work,
To change the Basic Authentication Level:

Locate the following directory:

1. HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WebClient\Parameters
2. Locate value BasicAuthLevel.
The Value data box should be set to 2.
If the value is not 2, right click it and then select 'Modify'.
Change it to 2.

**Comment by ncw** [comment]
@piyushgarg good work.

Would you like to add this to the `rclone serve webdav` docs?

This needs to go in the source code here

https://github.com/rclone/rclone/blob/450c3664035007875e2ade2ab5fc37a0c8b889e5/cmd/serve/webdav/webdav.go#L62

- I'd suggest starting a new section `### Mounting webdav with auth on Windows`

**Comment by piyushgarg** [comment]
bonus tip
To access Office applications over webdav, refer to: 
[](https://learn.microsoft.com/en-us/office/troubleshoot/powerpoint/office-opens-blank-from-sharepoint)

@ncw plz give me sometime, I will send a merge request.

**Comment by ncw** [comment]
> bonus tip To access Office applications over webdav, refer to: https://learn.microsoft.com/en-us/office/troubleshoot/powerpoint/office-opens-blank-from-sharepoint

Ha! That's sharepoint.
 
> @ncw plz give me sometime, I will send a merge request.

:+1:

**Comment by piyushgarg** [comment]
> @piyushgarg good work.
> 
> Would you like to add this to the `rclone serve webdav` docs?
> 
> This needs to go in the source code here
> 
> https://github.com/rclone/rclone/blob/450c3664035007875e2ade2ab5fc37a0c8b889e5/cmd/serve/webdav/webdav.go#L62
> 
> * I'd suggest starting a new section `### Mounting webdav with auth on Windows`

https://github.com/rclone/rclone/pull/6660
