### ISSUE TITLE
rclone.org down 

### ISSUE THREAD

**Issue by sguptzz** [rclone/rclone#6599]
https://downforeveryoneorjustme.com/rclone.org

**Comment by jiemo9527** [comment]
+1

**Comment by ncw** [comment]
It's back!

Caddy crashed alas and I forgot to add the auto restart to the systemctl file when I moved web hosts.

I decided to fix this properly upstream: https://github.com/caddyserver/dist/pull/92

**Comment by ncw** [comment]
FYI this was the caddy problem

```
Dec 04 05:54:10 rclone-web caddy[28708]: runtime: failed to create new OS thread (have 513 already; errno=11)
Dec 04 05:54:10 rclone-web caddy[28708]: runtime: may need to increase max user processes (ulimit -u)
Dec 04 05:54:10 rclone-web caddy[28708]: fatal error: newosproc
Dec 04 05:54:10 rclone-web caddy[28708]: runtime stack:
```

Not sure why caddy should need > 512 OS threads - I suspect a thread leak. Happy for caddy to crash and be restarted by systemd at this point.

Caddy ran for 83 days before crashing, so if there is a leak it is quite slow!
