### ISSUE TITLE
sending oracleobjectstorage too slow

### ISSUE THREAD

**Issue by cberni** [rclone/rclone#6617]
rclone sending with type oracleobjectstorage is too slow.

rclone v1.60.1
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-1022-oracle (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.3
- go/linking: static
- go/tags: none

[remote]
type = oracleobjectstorage
provider = instance_principal_auth
namespace =
compartment =
region = sa-saopaulo-1
storage_tier = InfrequentAccess

[remote_s3]
type = s3
provider = Other
access_key_id =
secret_access_key =
storage_class = STANDARD_IA
endpoint = xxxxxxxx.compat.objectstorage.sa-saopaulo-1.oraclecloud.com

rclone sync FILES remote:bucket/FILES -v -P --checkers 16 --transfers 8 --no-traverse --fast-list --size-only
733.322 KiB/s

rclone sync FILES remote_s3:bucket/FILES -v -P --checkers 16 --transfers 8 --no-traverse --fast-list --size-only
21.107 MiB/s

S3 compatibility is sending files to bucket more than 20 times faster....

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
@msays2000 - any thoughts about this?

**Comment by msays2000** [comment]
investigating.

**Comment by msays2000** [comment]
looks like head requests to native api is a bit slow compared to s3 compat api, following up.

the file transfer speed is good in both ways. just the head request response time are slower.

**Comment by msays2000** [comment]
fixed in https://github.com/rclone/rclone/pull/6714

**Comment by msays2000** [comment]
@ncw can we please resolve this, I am unable to resolve
