### ISSUE TITLE
Can't add UTF-8 characters to alias names

### ISSUE THREAD

**Issue by vulieumang** [rclone/rclone#6618]
Hello, 
Happy we have 
`rclone backend drives -o config gdrive:`
for list all shared drive for config file, but my shared drive have utf-8 char, and with large folder with char "_" very hard to read.
To much char "_" to very confuse, 

I have > 1000 shared drive, so it very confuse, hope a people help do that
folder rclone support utf-8 very great

<img width="344" alt="image" src="https://user-images.githubusercontent.com/13487753/206748842-4b7b7236-80e6-433c-95a0-b57a4f9dea01.png">

Thank you very much

**Comment by animosity22** [comment]
For general support / use questions, please use the forums.

https://forum.rclone.org

Use the help and support template and include ALL the information.

**Comment by ncw** [comment]
This is a request to add UTF-8 characters into the names of aliases. Currently we only support a-z0-9 but there is no reason we shouldn't use UTF-8 characters in aliases.

I'll re-open this so we can think about the consequences of the change.

**Comment by vulieumang** [comment]
May this happen a problem is Alldrive not work
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/13487753/206849409-a11be5f6-deb5-4205-a72a-439254ae8664.png">
1 shared drive work
<img width="934" alt="image" src="https://user-images.githubusercontent.com/13487753/206849433-98426479-6f52-4c9e-83b1-29758d4f07aa.png">
but Alldrive not work

Am I do anything wrong?

**Comment by ncw** [comment]
@albertony can you think of a reason why we shouldn't allow UTF-8 characters in alias names?

I would suggest we use allow unicode character class `L` and `N` for letter and number.

This would change this regexp

https://github.com/rclone/rclone/blob/beea4d5119555c0424cf3bc8b3e67d625813b014/fs/fspath/path.go#L16

Into something like

    configNameRe = `[\p{L}\p{N}_. -]+`

This **is** the first time I've used unicode character classes so I'm not 100% sure that is correct.
We'd need to fix the google drive backend also where it cleans these characters from alias names it creates for the combine backend.

@vulieumang could you **cut and paste** some of the original names here so I can check that regexp would work please? Thanks

Here are the unicode character class names for reference

| Unicode character class names | general category |
| --- | --- |
| C | other |
| Cc | control |
| Cf | format |
| Cn | unassigned code points (NOT SUPPORTED) |
| Co | private use |
| Cs | surrogate |
| L | letter |
| LC | cased letter (NOT SUPPORTED) |
| L& | cased letter (NOT SUPPORTED) |
| Ll | lowercase letter |
| Lm | modifier letter |
| Lo | other letter |
| Lt | titlecase letter |
| Lu | uppercase letter |
| M | mark |
| Mc | spacing mark |
| Me | enclosing mark |
| Mn | non-spacing mark |
| N | number |
| Nd | decimal number |
| Nl | letter number |
| No | other number |
| P | punctuation |
| Pc | connector punctuation |
| Pd | dash punctuation |
| Pe | close punctuation |
| Pf | final punctuation |
| Pi | initial punctuation |
| Po | other punctuation |
| Ps | open punctuation |
| S | symbol |
| Sc | currency symbol |
| Sk | modifier symbol |
| Sm | math symbol |
| So | other symbol |
| Z | separator |
| Zl | line separator |
| Zp | paragraph separator |
| Zs | space separator |

**Comment by vulieumang** [comment]
@ncw  Yes, my pleasure


Original | convert by rclone 
-- | --
Nguyễn Nhật Lâm | Nguy_n Nh_t Lam
Hồng Thị Nhung | Ho_ng Th_ Nhung
Nguyễn Thị Phượng |  Nguy_n Th_ Ph_ng
Lâm Minh Chánh | L_ Minh Ch_nh

here is full char unicode form my country (Vietnam)

-- | -- | -- | -- | --
1 | a | A | a | a
2 | ă | Ă | á | á
3 | â | Â | ớ | ớ
4 | b | B | bê | bờ
5 | c | C | xê | cờ
6 | d | D | dê | dờ
7 | đ | Đ | đê | đờ
8 | e | E | e | e
9 | ê | Ê | ê | ê
10 | g | G | giê | giờ
11 | h | H | hát | hờ
12 | i | I | i | I
13 | k | K | ca | ca/cờ
14 | l | L | e – lờ | lờ
15 | m | M | em mờ/ e – mờ | mờ
16 | n | N | em nờ/ e – nờ | nờ
17 | o | O | o | O
18 | ô | Ô | ô | Ô
19 | ơ | Ơ | Ơ | Ơ
20 | p | P | pê | pờ
21 | q | Q | cu/quy | quờ
22 | r | R | e-rờ | rờ
23 | s | S | ét-xì | sờ
24 | t | T | Tê | tờ
25 | u | U | u | u
26 | ư | Ư | ư | ư
27 | v | V | vê | vờ
28 | x | X | ích xì | xờ
29 | y | Y | i dài | i

I am here and ready 100% for this function

**Comment by ncw** [comment]
The regexp seems to be OK for those names.

You can try it out here: https://go.dev/play/p/De14w8o1WRp with more names. It should allow all things which are considered numbers or letters in your language but it shouldn't allow any symbols.

I realise that probably what we want is to be similar to what the Go language allows as an identifier https://go.dev/ref/spec#Identifiers (but allow spaces and initial digits).

It uses 

> In [The Unicode Standard 8.0](https://www.unicode.org/versions/Unicode8.0.0/), Section 4.5 "General Category" defines a set of character categories. Go treats all characters in any of the Letter categories Lu, Ll, Lt, Lm, or Lo as Unicode letters, and those in the Number category Nd as Unicode digits.

So I think using `L` and `N` is slightly broader than that, but I don't know what the difference is.

**Comment by vulieumang** [comment]
I had test and and demo go can run successful, 
I am very very excited for update, very much, hope you make it
I very thank you so much

**Comment by aaaaaaajsjsjjsjxhhb2** [comment]
fuck off..my nigga
-------- Original message --------From: Vu ***@***.***> Date: 12/10/22  06:37  (GMT-06:00) To: rclone/rclone ***@***.***> Cc: Subscribed ***@***.***> Subject: Re: [rclone/rclone] Can't add UTF-8 characters to alias names (Issue #6618) 
I had test and and demo go can run successful,
I am very very excited for update, very much, hope you make it
I very thank you so much

**Comment by albertony** [comment]
> @albertony can you think of a reason why we shouldn't allow UTF-8 characters in alias names?

Could be that on Windows you can get yourself into trouble due to different encodings ("code page") in different shells, or different systems if you share the config, e.g. between the native Windows host and a Linux distro running in WSL. Though newer versions of Windows have built-in optional support for UTF-8 in command prompt, and maybe Windows 11 have it enabled by default. But don't think this needs to be a show-stopper, an additional note in https://rclone.org/docs/#valid-remote-names is probably enough.

> So I think using `L` and `N` is slightly broader than that, but I don't know what the difference is.

Seems the `L` is equivalent to all the mentioned letter categories, but there is a difference in the number categories where `Nl` and `No` are also included in `N`, and those represent roman numerals, fractions, and superscript/subscript digits: https://en.wikipedia.org/wiki/Unicode_character_property#General_Category.

**Comment by aaaaaaajsjsjjsjxhhb2** [comment]
how about put all in pen

**Comment by ncw** [comment]
@albertony those are nice changes :-)

Do you want to fix #6618 in this series by adding `\p{L}\p{N}` alongside the `\w` (yes there may be some overlap but at least that way we know it is 100% backwards compatible) and add some tests?

**Comment by albertony** [comment]
I can do that, yes.

**Comment by vulieumang** [comment]
@ncw 
I just test, remove all shared drive with character "_"  and Alldrive work again, So I think fix bug by your way will fix this bug too.
<img width="686" alt="image" src="https://user-images.githubusercontent.com/13487753/206857907-e4c2aa5f-3e8f-4417-be7a-adac0176ec9a.png">
Here all AllDrive work again.

**Comment by vulieumang** [comment]
@ncw 
In worst, 
`rclone backend drives -o config gdrive:` just need return exact name like "Nguyễn Văn A" 
and Rclone's user  can using other tool convert utf-8 to ascii, 
because if return "Nguy_N V_n A" user can not make sure name and it not work too.

**Comment by ncw** [comment]
@vulieumang this should be fixed now thanks to @albertony 

Please try [the latest beta](https://beta.rclone.org/) - `rclone backend drives -o config gdrive:` should produce a config which allows letters and numbers of all languages which rlcone will now accept.

**Comment by vulieumang** [comment]
@ncw 
Thank you so much 😍, I had test and it very greatttt. Have one error if shared drive have space  end but I just remove all space end in alias and in Alldrive. And it work!!! 😃

**Comment by vulieumang** [comment]
Space end character had been fixed, and work good :), Thank @ncw @albertony
