### ISSUE TITLE
Stop reading file list when --max-transfer is meet

### ISSUE THREAD

**Issue by imrebuild** [rclone/rclone#6619]
#### What is your current rclone version (output from `rclone version`)?

rclone v1.60.1

#### What problem are you are trying to solve?

Rclone keeps scanning from remote storage even they won't be transfered because  --max-transfer is set, causing unnecessary api call.

#### How do you think rclone should be changed to solve that?

Rclone should stop scanning after it gets enough files to transfer.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
It does.

Can you please share the command you ran / log file with some details.

**Comment by imrebuild** [comment]
`-vvv` seems not providing much useful info.

I'm running `rclone copy -v --stats 10s --transfers 16 --max-transfer=100G from: to:`

The printed stats shows it already gets enough data to transfer but the data is still increasing:

```
Transferred:   	  514.220 MiB / 359.194 GiB, 0%, 78.030 MiB/s, ETA 1h18m27s
Transferred:            0 / 93, 0%
Elapsed time:        11.0s
```

```
Transferred:   	    1.489 GiB / 730.807 GiB, 0%, 92.448 MiB/s, ETA 2h14m38s
Transferred:            0 / 266, 0%
Elapsed time:        21.0s
```

```
Transferred:   	    2.474 GiB / 977.493 GiB, 0%, 96.344 MiB/s, ETA 2h52m43s
Transferred:            0 / 424, 0%
Elapsed time:        31.0s
```

```
Transferred:   	    3.465 GiB / 1.234 TiB, 0%, 98.841 MiB/s, ETA 3h37m33s
Transferred:            0 / 536, 0%
Elapsed time:        41.0s
```

**Comment by animosity22** [comment]
Not sure I'm seeing any issue as you've only transferred 3G out of 100GB.

**Comment by imrebuild** [comment]
This issue is about the "wait for being transfered" part(it's already near 1TB in 30s). It didn't stop when it got 100GB file.

In fact it can reach 20TB when rclone exits as 100GB has been transfered.

I believe this can be an issue for backends like s3 when we needs to pay for the api call.

**Comment by animosity22** [comment]
You'd set max backlog lower:

```
      --max-backlog int                      Maximum number of objects in sync or check backlog (default 10000)
```

If that's your goal.

**Comment by imrebuild** [comment]
Thanks for the answer. I think this can fix my issue.
