### ISSUE TITLE
mount all remotes together / rclone serve all remotes together

### ISSUE THREAD

**Issue by pyy** [rclone/rclone#6625]
Hello,

like command `rclone rcd --rc-serve`  to list an object in any remote with `http://127.0.0.1:5572/[remote:path]/path/to/object`, is it possible to make it not `ro` (`read-only`), but `+w `writable? In another words, can we mount all remotes together?

For example, I have remote_1, remote_2, .... remote_10. 
using `rclone serve webdav` command without give specific remote, rclone then shows `[remote_1:]`, `[remote_2:]`, ... `[remote_10:]` as subfolders, which have fully read, write, list, etc functions.

Do we have a similar way to achieve it?

It would be a great function, without mounting every remote as a separate process.
Thank you.

https://rclone.org/commands/rclone_serve/
https://rclone.org/rc/

**Comment by animosity22** [comment]
For general use questions, pretty please, use the forums.

https://forum.rclone.org

**Comment by ncw** [comment]
> For example, I have remote_1, remote_2, .... remote_10. using `rclone serve webdav` command without give specific remote, rclone then shows `[remote_1:]`, `[remote_2:]`, ... `[remote_10:]` as subfolders, which have fully read, write, list, etc functions.
> 
> Do we have a similar way to achieve it?

This is what the combine backend is for https://rclone.org/combine/

If you need more help please ask on [post on the rclone forum](https://forum.rclone.org/) about this - thanks
