### ISSUE TITLE
Breaking links & IDs of files when syncing with google drive

### ISSUE THREAD

**Issue by AngelD-F** [rclone/rclone#6626]
#### What is the problem you are having with rclone?

`rclone` is breaking the links and IDs of the files it syncs with google drive.

I mounted my local directory with my remote drive and edited some files there. Some time later
I tried to access the same files through from my android and I noticed that all the links were 
broken and I have to locate the files to open them again.

Reading the logs it turned out that when `rclone` detects a modified file in the local directory
and tries to update the remote file, it uploads a whole new version of file to the cloud, erases
the old remote file and rename the newly uploaded file with the filename of the old one.
Breaking the links and IDs in the process.

This sounds like just a small issue (maybe it is) but here I have applications that only use the ID to
locate the remote files in google drive and others that only can access those files with mounting
the remote drive with `reclone`. It is getting annoying to relocate the files because the original 
link does not work anymore.

Other syncing tools don't have this problem so I was wondering if there is a way to directly update
the remote files so as not to break anything.

Please, is there anyone who can help?

#### What is your rclone version (output from `rclone version`)

rclone v1.53.3-DEV

- os/arch: linux/amd64
- go version: go1.18

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Ubuntu 22.04

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
[logs.txt](https://github.com/rclone/rclone/files/10227506/logs.txt)

while running:

`rclone drive:remote/folder/ local/directorty` 

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

[logs.txt](https://github.com/rclone/rclone/files/10227783/logs.txt)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Masamune3210** [comment]
I'm not entirely sure that GDrive supports modify-in-place, that might be why the invalidate and upload method is being used

**Comment by animosity22** [comment]
Your version is years old. You'd want to update and test on the latest.

**Comment by ncw** [comment]
> Reading the logs it turned out that when `rclone` detects a modified file in the local directory
> and tries to update the remote file, it uploads a whole new version of file to the cloud, erases
> the old remote file and rename the newly uploaded file with the filename of the old one.
> Breaking the links and IDs in the process.

As far as I know you can't upload a new google drive file and retain the same ID.

I may be wrong, so if you've got some evidence that you can do that, then please add some links and I'll see if I can implement it :-)

**Comment by darthShadow** [comment]
There is the update method available for updating the content of a specific file ID: https://developers.google.com/drive/api/v3/reference/files/update

**Comment by darthShadow** [comment]
Looks like it's already being used too: https://github.com/rclone/rclone/blob/c6ad15e3b8c171a16372450ef2d87dc9e397ddd8/backend/drive/upload.go#L65

Not sure why it didn't get called however...

**Comment by darthShadow** [comment]
Ah, this happened because a temp file was created and then renamed to the original file after deleting the original file, causing the remote file to also get deleted:

```
2022/12/14 07:42:57 DEBUG : /: Rename: oldName="AngelDB.kdbx.shpafD", newName="AngelDB.kdbx", newDir=/
2022/12/14 07:42:57 INFO  : AngelDB.kdbx: Deleted
2022/12/14 07:42:58 INFO  : AngelDB.kdbx.shpafD: Moved (server side)
2022/12/14 07:42:58 DEBUG : AngelDB.kdbx: Updating file with AngelDB.kdbx 0xc00063a240
2022/12/14 07:42:58 DEBUG : : Added virtual directory entry vDel: "AngelDB.kdbx.shpafD"
2022/12/14 07:42:58 DEBUG : : Added virtual directory entry vAdd: "AngelDB.kdbx"
2022/12/14 07:42:58 DEBUG : /: >Rename: err=<nil>
```

**Comment by darthShadow** [comment]
I believe adding `--vfs-write-back` should solve the issue.

@AngelD-F mind updating to the latest version of rclone and then  testing with `--vfs-write-back` of ~30s?

**Comment by ncw** [comment]
I'm not sure Update keeps the ID of the file does it?

Update does indeed preserve the ID, so the above should work - you can see the file changing size here but the ID remaining the same.

```
$ rclone lsf --format sip drive:test/test.txt
16;1fyrrSWWb9J9_wtuTZFtIi6k5uJ4NmriE;test.txt
$ echo hellohellohellohello > text.txt
$ rclone copyto text.txt drive:test/test.txt
$ rclone lsf --format sip drive:test/test.txt
21;1fyrrSWWb9J9_wtuTZFtIi6k5uJ4NmriE;test.txt
```

**Comment by AngelD-F** [comment]
> You'd want to add --vfs-cache-mode writes and the default of 5 seconds should be fine based on the log.

Using `--vfs-cache-mode writes` solved the issue. I updated to the latest version and it worked.
Here's the new log file: [logs.txt](https://github.com/rclone/rclone/files/10237927/logs.txt)

> I'm not sure Update keeps the ID of the file does it?
> 
> Update does indeed preserve the ID, so the above should work - you can see the file changing size here but the ID remaining the same.

It seems that when it finds an edited file (while mounting) it uploads a temp file with the modified content to the cloud with a new ID and then remove the old file which has the original ID, I imagine that this is to avoid corrupting the files. Setting `--vs-cache-mode` keeps the same behavior virtually but only uploads the file in cache, according to the [logs](https://github.com/rclone/rclone/files/10237927/logs.txt).

```
2022/12/15 10:21:56 INFO  : vfs cache: cleaned: objects 1 (was 1) in use 0, to upload 0, uploading 0, total size 411.420Ki (was 411.420Ki)
2022/12/15 10:22:23 INFO  : AngelDB.kdbx.jFmrOe: vfs cache: queuing for upload in 5s
2022/12/15 10:22:23 INFO  : AngelDB.kdbx.jFmrOe: vfs cache: renamed in cache to "AngelDB.kdbx"
2022/12/15 10:22:23 INFO  : AngelDB.kdbx: vfs cache: queuing for upload in 5s
2022/12/15 10:22:30 INFO  : AngelDB.kdbx: Copied (new)
2022/12/15 10:22:30 INFO  : AngelDB.kdbx: vfs cache: upload succeeded try #1
2022/12/15 10:22:56 INFO  : vfs cache: cleaned: objects 1 (was 1) in use 0, to upload 0, uploading 0, total size 411.420Ki (was 411.420Ki)
2022/12/15 10:23:27 INFO  : .goutputstream-WAB6W1: vfs cache: renamed in cache to "CodeExtensions.txt"
2022/12/15 10:23:27 INFO  : CodeExtensions.txt: vfs cache: queuing for upload in 5s
2022/12/15 10:23:34 INFO  : CodeExtensions.txt: Copied (new)
2022/12/15 10:23:34 INFO  : CodeExtensions.txt: vfs cache: upload succeeded try #1
2022/12/15 10:23:56 INFO  : vfs cache: cleaned: objects 2 (was 2) in use 0, to upload 0, uploading 0, total size 411.806Ki (was 411.806Ki)
2022/12/15 10:24:13 INFO  : Signal received: interrupt
2022/12/15 10:24:13 INFO  : Exiting...
```
