### ISSUE TITLE
rclone installation fail on 10.12

### ISSUE THREAD

**Issue by browserwatchtg** [rclone/rclone#6627]
installation is simply not possible anymore

macbook-pro-retina-15-inch-late-2013-telegram:~ cinema$ rclone config
dyld: Symbol not found: _SecTrustEvaluateWithError
  Referenced from: /usr/local/bin/rclone
  Expected in: flat namespace
 in /usr/local/bin/rclone
Abort trap: 6
macbook-pro-retina-15-inch-late-2013-telegram:~ cinema$

**Comment by animosity22** [comment]
Please use the forums and use the help and support template.

https://forum.rclone.org
