### ISSUE TITLE
Add support for LinkBox

### ISSUE THREAD

**Issue by nguyenzzz** [rclone/rclone#6629]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.60.1
- os/version: Microsoft Windows 11 Pro 22H2 (64 bit)
- os/kernel: 10.0.22622.521 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.19.3
- go/linking: static
- go/tags: cmount

#### What problem are you are trying to solve?
Requesting for new cloud support called LinkBox. Linkbox website: https://www.linkbox.to/

#### How do you think rclone should be changed to solve that?
Their API docs page: https://www.linkbox.to/api-docs

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by jacobmichels** [comment]
Browsing the API docs I noticed that there doesn't seem to be a way to download files through the API. Unless I missed something, I don't think it's possible to implement the required `Object` interface without being able to retrieve the file.

Also the API expects the user's auth token to be passed as a query parameter, which is just bad security practice. Wouldn't want rclone to be blamed for leaking someones credentials.

**Comment by nguyenzzz** [comment]
Thanks for adding Linkbox backend. So i close my request
