### ISSUE TITLE
Dark Mode Option is grayed out

### ISSUE THREAD

**Issue by SysAdminDoc** [rclone/rclone#6631]
Anyone know the fix to this?

![image](https://user-images.githubusercontent.com/54586742/207994677-bff8202c-9598-4c41-8a83-45a50e80f540.png)

**Comment by SysAdminDoc** [comment]
I should also add that restarting the application does not fix the issue.

**Comment by SysAdminDoc** [comment]
I'm on Windows 11 with dark mode theme enabled on the system.

**Comment by animosity22** [comment]
Please post in the forums for general questions and use the help and support template.

**Comment by SysAdminDoc** [comment]
Where's the forums?

**Comment by animosity22** [comment]
Was all listed the template you deleted.


https://forum.rclone.org

**Comment by SysAdminDoc** [comment]
Yeah, I'm not on adderall and wasn't about to read all of that. Also, dark mode is a setting in the rclone browser, not rclone itself.

**Comment by animosity22** [comment]
Bummer as reading is helpful as you'd realize this is for rclone and rclone browser is here

https://github.com/mmozeiko/RcloneBrowser

**Comment by SysAdminDoc** [comment]
I'm so dumb. My bad.
