### ISSUE TITLE
Error 403: rate_limit_exceeded - Google drive configure 

### ISSUE THREAD

**Issue by aviv926** [rclone/rclone#6633]
#### What is the problem you are having with rclone?

Unable to configure Google Drive in the first config
![image](https://user-images.githubusercontent.com/51673860/208259405-1f3373c7-06cc-4706-bde3-67b98d2a54e3.png)

#### What is your rclone version (output from `rclone version`)
rclone v1.60.1
- go/version: go1.19.3

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
- os/version: Microsoft Windows 10 Pro 22H2 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone.exe config`
#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
No, this is my first time running it

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by abhiraj2** [comment]
Do you have your own client_id set up or are you using the default client_id (rclone's client id)? Because the default one is shared between all users, it has a global rate limit.

**Comment by aviv926** [comment]
> Do you have your own client_id set up or are you using the default client_id (rclone's client id)? Because the default one is shared between all users, it has a global rate limit.

I'm use with default client_id, do you know how long the restriction ends?

**Comment by abhiraj2** [comment]
I'm not sure about that, but I think you can try again once or twice and see if it works, since it already has quite a high quota. Nevertheless it's highly recommended to make your own client_id, it'll help you out in the long run

You can follow this [guide](
https://rclone.org/drive/#making-your-own-client-id) on official docs for making your client_id

**Comment by aviv926** [comment]
Thanks!
I made one myself and it works P:
By the way, I know this is unrelated to the topic, but is the definition of encryption separate from this definition?

> I'm not sure about that, but I think you can try again once or twice and see if it works, since it already has quite a high quota. Nevertheless it's highly recommended to make your own client_id, it'll help you out in the long run
> 
> You can follow this [guide](https://rclone.org/drive/#making-your-own-client-id) on official docs for making your client_id

**Comment by abhiraj2** [comment]
> but is the definition of encryption separate from this definition?

I don't really follow, can you elaborate?

**Comment by animosity22** [comment]
We really like to keep github for bugs / feature requests.

For general support, please use the forums:

https://forum.rclone.org
