### ISSUE TITLE
Is archive.org upload very unstable?

### ISSUE THREAD

**Issue by carolynsteeves1** [rclone/rclone#6640]
Hello! I love rclone, but it seems like when uploading with rclone to internet archive can be very unstable. Somtimes it works and other times it just doesnt work at all. Is this an issue that cant be fixed? Anyone who also has experienced this?

**Comment by animosity22** [comment]
Please use the forums for general questions:

https://forum.rclone.org

We really try to keep things here for bugs/enhancements.

Thanks for your cooperation.
