### ISSUE TITLE
Failing to run rc commands against a specific rc address

### ISSUE THREAD

**Issue by darthShadow** [rclone/rclone#6641]
#### The associated forum post URL from `https://forum.rclone.org`

N/A

#### What is the problem you are having with rclone?

`rc` commands are failing when run against a specific rc address.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.61.0
- os/version: ubuntu 18.04 (64 bit)
- os/kernel: 5.18.11-xanmod1 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.4
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Ubuntu 18.04 (64-bit)

#### Which cloud storage system are you using? (e.g. Google Drive)

N/A

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone --rc-addr 127.0.0.1:5572 rc core/gc`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
darthshadow@server:~/temp/rclone-v1.61.0-linux-amd64$ ./rclone --rc-addr 127.0.0.1:5572 rc core/gc
2022/12/20 19:31:11 Failed to rc: connection failed: Post "http://[127.0.0.1:5572]/core/gc": dial tcp: lookup 127.0.0.1:5572: no such host
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by darthShadow** [comment]
@ncw This looks to be a regression from the PR adding support for multiple listeners and using the same variable for both the client & server: https://github.com/rclone/rclone/blame/496ae8adf62b0e3a4ea304ab4ff39358ebdfbec5/lib/http/server.go#L96

**Comment by darthShadow** [comment]
Sorry, missed the new `url` parameter... 😓

**Comment by darthShadow** [comment]
Missed it when `--url` became the recommended parameter instead of `--rc-addr` for connecting to a specific rc server ... 😄

**Comment by darthShadow** [comment]
Probably copied from @animosity22  a few years back and never updated those. Will raise an issue in his repo for updating those.

**Comment by darthShadow** [comment]
On second thought, this still deserves a fix or atleast a release not since the `setAlternateFlag` for mapping `rc-addr` to `url` doesn't work anymore due to different types: https://github.com/rclone/rclone/blob/496ae8adf62b0e3a4ea304ab4ff39358ebdfbec5/cmd/rc/rc.go#L121

**Comment by animosity22** [comment]
When did that change? I've been using that for some time and realized it actually doesn't work today.

```
felix@gemini:~/scripts$ rclone rc core/gc --rc-addr 127.0.0.1:5574
2022/12/20 15:08:14 Failed to rc: connection failed: Post "http://[127.0.0.1:5574]/core/gc": dial tcp: lookup 127.0.0.1:5574: no such host
felix@gemini:~/scripts$ netstat -an | grep 5574
tcp        0      0 127.0.0.1:5574          0.0.0.0:*               LISTEN
felix@gemini:~/scripts$ rclone rc core/gc --url 127.0.0.1:5574
{}
```

I use to toggle debug too and that worked without issue prior as well:

```
felix@gemini:~/scripts$ cat rclone-debug
rclone rc options/set --json '{"main": {"LogLevel": "DEBUG"}}'  --rc-addr 127.0.0.1:5574
#rclone rc options/set --json '{"main": {"LogLevel": "DEBUG"}}'  --rc-addr 127.0.0.1:5575
```

**Comment by darthShadow** [comment]
Just this release. It worked fine with the prior releases.

Support for multiple listening addresses/sockets was added in this release and since the same parameter was used for both server & client (as an alternate flag), it broke the client connectivity.

**Comment by darthShadow** [comment]
The `addr` parameter is now an array of strings whereas the `url` parameter is a single string and copying the value as-is is causing an issue.

https://github.com/rclone/rclone/blob/496ae8adf62b0e3a4ea304ab4ff39358ebdfbec5/lib/http/server.go#L96

https://github.com/rclone/rclone/blob/496ae8adf62b0e3a4ea304ab4ff39358ebdfbec5/cmd/rc/rc.go#L40

https://github.com/rclone/rclone/blob/496ae8adf62b0e3a4ea304ab4ff39358ebdfbec5/cmd/rc/rc.go#L121

**Comment by ncw** [comment]
Yes this looks like a regression. Want to prepare a PR @darthShadow ?

**Comment by darthShadow** [comment]
Assuming the fix is to just use the first value from the rc-addr array?

**Comment by ncw** [comment]
Sounds good. Let's do that 👍
