### ISSUE TITLE
Error 403: rate_limit_exceeded

### ISSUE THREAD

**Issue by SoonHiru** [rclone/rclone#6643]
```
The app has reached its login count limit for now.

Google limits how quickly apps can get new users. You can try signing in again later, or ask the developer.
(nickcw@gmail.com) to increase the limit on the number of logins in this app.
```

Hello sir, help me to login access rclone authorize drive.
Thanks

**Comment by darthShadow** [comment]
You need to make your own client_id: https://rclone.org/drive/#making-your-own-client-id

Please reach out on the forums @ https://forum.rclone.org/ if you continue to have any issues since we keep only confirmed bugs on the Github Issues Tracker.

**Comment by imran717** [comment]
Error 403: disallowed_useragent

**Comment by imran717** [comment]
Error 403: disallowed_useragent

**Comment by imran717** [comment]
Please help me my Google account access blocked authorisation error problem
