### ISSUE TITLE
"directory not found" when syncing folders ending in space

### ISSUE THREAD

**Issue by AndreKR** [rclone/rclone#6652]
#### The associated forum post URL from `https://forum.rclone.org`

This seems like an obvious bug so I didn't ask on the forum.

#### What is the problem you are having with rclone?

When using `rclone sync` and the synced directory contains subdirectories whose name ends in space a "directory not found" error is shown instead of syncing them.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.60.0
- os/version: Microsoft Windows 7 Professional Service Pack 1 (64 bit)
- os/kernel: 6.1.7601 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.19.2
- go/linking: static
- go/tags: cmount
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Microsoft Windows 7 Professional Service Pack 1 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)

This can be reproduced locally. It also happens with cloud storage though.

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

Here's the full repro:
```
cd c:\
md rclone_test\s
md "\\?\c:\rclone_test\s\This name ends in space "
echo foo > "c:\rclone_test\s\This name ends in space \foo.txt"
md rclone_test\d

rclone -P -vv sync c:\rclone_test\s c:\rclone_test\d

rd /s /q c:\rclone_test
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2022/12/23 04:58:27 DEBUG : Setting --config [REDACTED] from environment variable RCLONE_CONFIG=[REDACTED]
2022/12/23 04:58:27 DEBUG : rclone: Version "v1.60.0" starting with parameters ["rclone" "-P" "-vv" "sync" "c:\\rclone_test\\s" "c:\\rclone_test\\d"]
2022/12/23 04:58:27 DEBUG : Creating backend with remote "c:\\rclone_test\\s"
2022/12/23 04:58:27 DEBUG : Using config file from [REDACTED]
2022/12/23 04:58:27 DEBUG : fs cache: renaming cache item "c:\\rclone_test\\s" to be canonical "//?/c:/rclone_test/s" 2022/12/23 04:58:27 DEBUG : Creating backend with remote "c:\\rclone_test\\d"
2022/12/23 04:58:27 DEBUG : fs cache: renaming cache item "c:\\rclone_test\\d" to be canonical "//?/c:/rclone_test/d" 2022-12-23 04:58:27 ERROR : This name ends in space : error reading source directory: directory not found
2022-12-23 04:58:27 DEBUG : Local file system at //?/c:/rclone_test/d: Waiting for checks to finish
2022-12-23 04:58:27 DEBUG : Local file system at //?/c:/rclone_test/d: Waiting for transfers to finish
2022-12-23 04:58:27 ERROR : Local file system at //?/c:/rclone_test/d: not deleting files as there were IO errors
2022-12-23 04:58:27 ERROR : Local file system at //?/c:/rclone_test/d: not deleting directories as there were IO errors
2022-12-23 04:58:27 ERROR : Attempt 1/3 failed with 1 errors and: directory not found
2022-12-23 04:58:27 ERROR : This name ends in space : error reading source directory: directory not found
2022-12-23 04:58:27 DEBUG : Local file system at //?/c:/rclone_test/d: Waiting for checks to finish
2022-12-23 04:58:27 DEBUG : Local file system at //?/c:/rclone_test/d: Waiting for transfers to finish
2022-12-23 04:58:27 ERROR : Local file system at //?/c:/rclone_test/d: not deleting files as there were IO errors
2022-12-23 04:58:27 ERROR : Local file system at //?/c:/rclone_test/d: not deleting directories as there were IO errors
2022-12-23 04:58:27 ERROR : Attempt 2/3 failed with 1 errors and: directory not found
2022-12-23 04:58:27 ERROR : This name ends in space : error reading source directory: directory not found
2022-12-23 04:58:27 DEBUG : Local file system at //?/c:/rclone_test/d: Waiting for checks to finish
2022-12-23 04:58:27 DEBUG : Local file system at //?/c:/rclone_test/d: Waiting for transfers to finish
2022-12-23 04:58:27 ERROR : Local file system at //?/c:/rclone_test/d: not deleting files as there were IO errors
2022-12-23 04:58:27 ERROR : Local file system at //?/c:/rclone_test/d: not deleting directories as there were IO errors
2022-12-23 04:58:27 ERROR : Attempt 3/3 failed with 1 errors and: directory not found
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         0.0s
2022/12/23 04:58:27 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         0.0s

2022/12/23 04:58:27 DEBUG : 2 go routines active
2022/12/23 04:58:27 Failed to sync: directory not found
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Can you test on the latest stable? I think there was a fix in there about that.

https://rclone.org/install/

**Comment by AndreKR** [comment]
Huh, I thought this was the latest, just installed it a few days ago.

Anyway, the issue still happens with v1.16.0.

**Comment by animosity22** [comment]
You mean 1.61?

**Comment by AndreKR** [comment]
Yes:
```
$ rclone version
rclone v1.61.0
```

**Comment by animosity22** [comment]
Seems to be a Windows thing.

```
felix@gemini:~/test$ mkdir "test "
```

and

```
felix@gemini:~/test$ rclone copy test\ / three -vv
2022/12/22 23:23:53 DEBUG : Setting --config "/opt/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/opt/rclone/rclone.conf"
2022/12/22 23:23:53 DEBUG : rclone: Version "v1.61.0" starting with parameters ["rclone" "copy" "test /" "three" "-vv"]
2022/12/22 23:23:53 DEBUG : Creating backend with remote "test /"
2022/12/22 23:23:53 DEBUG : Using config file from "/opt/rclone/rclone.conf"
2022/12/22 23:23:53 DEBUG : fs cache: renaming cache item "test /" to be canonical "/home/felix/test/test "
2022/12/22 23:23:53 DEBUG : Creating backend with remote "three"
2022/12/22 23:23:53 DEBUG : fs cache: renaming cache item "three" to be canonical "/home/felix/test/three"
2022/12/22 23:23:53 DEBUG : Local file system at /home/felix/test/three: Waiting for checks to finish
2022/12/22 23:23:53 DEBUG : Local file system at /home/felix/test/three: Waiting for transfers to finish
2022/12/22 23:23:53 DEBUG : blah: md5 = d41d8cd98f00b204e9800998ecf8427e OK
2022/12/22 23:23:53 INFO  : blah: Copied (new)
2022/12/22 23:23:53 INFO  :
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:            1 / 1, 100%
Elapsed time:         0.0s

2022/12/22 23:23:53 DEBUG : 5 go routines active
```

**Comment by AndreKR** [comment]
By the way, if anyone wonders why I would have such folder names: the gallery app on my phone creates them when I create an album and then I copied them for backup reasons using `adb`.

**Comment by Masamune3210** [comment]
Unfortunately, there probably isnt a way for rclone to really handle this. Windows will not let you create a folder with a empty space at the end, it will just trim it, and all or at least almost all Windows-side stuff will either just ignore the directory or silently trim off the space when inputted only to fail to find the folder, as with the case with rclone

**Comment by Masamune3210** [comment]
Your best chance might be using WSL and using the linux version of rclone to handle folders like that

**Comment by ncw** [comment]
On Windows rclone will translate trailing spaces in file names into the unicode `␠` character. It isn't expecting to ever see files or directories on windows file systems with trailing spaces as, as far as I'm aware, that isn't allowed.

That translation is probably why your copy isn't working.

You can try disabling it - run `rclone help flags local-encoding` and take the default there into a `--local-encoding XXX` flag, but remove the `RightSpace` encoding.

**Comment by animosity22** [comment]
Looks to be answered. Closing out.

**Comment by dbrill** [comment]
I know this issue is closed, but when copying from Swift to a local SMB mount the following --local-enconding params solved my issues

`--local-encoding Slash,Dot,RightSpace`
