### ISSUE TITLE
Files unable to be uploaded to onedrive crypt backend if name contains _vti_ in any part of it

### ISSUE THREAD

**Issue by tecepeipe** [rclone/rclone#6653]
I have 200,000 files in my gdrive. I sync'ed them to onedrive and noticed that 2 files weren't copied and returned:
 Failed to copy: invalidRequest: Invalid request

As both backends are encrypted, could not be due file contents being prohibited, I checked for too long paths and after a lot of digging, I realised it's due the filename.
using cryptdecode --reverse I obtained:

223.rprIx_spIp_ItBEApIt_wDHI_Bxq_vtI_EGxCItG_IDIpA_EpvtH.MBA
IJGtH_-_StrDst_uAxGIpIxDJH_vtHIJGtH_pCs_vtI_RadhTg_id_ndjg_VdPa.BE1

I was stripping the file name until I notice that both would fail to upload to business onedrive (it works on personal) if having `_vti_` in the encrypted filename. Even in plain onedrive (as long it's business/365) it will fail to upload.

(the original files names were cacti_blah_blah.xml and some video-long-name.mp4)

If you try to upload using web UI on onedrive a file named dummy_vti_file.txt, it will fail with access denied!

Googling for `_vti_` I found this:
_The `_vti_bin` is the built-in SharePoint Web services directory_

So, my suggestion is to prevent to generate encrypted filenames containing `_vti_` altogether (it would be a hassle to avoid this IF the backend is onedrive... but ideal)

**Comment by kapitainsky** [comment]
Shouldn't this be mentioned in crypt documentation? Clearly base64 can not be used today for OneDrive as I understand this issue.

**Comment by tecepeipe** [comment]
[Issue raised](https://github.com/OneDrive/onedrive-api-docs/issues/1653) on onedrive
