### ISSUE TITLE
Size suffix compat between Windows and Linux

### ISSUE THREAD

**Issue by fetuffani** [rclone/rclone#6655]
I do share my rclone.config file between Windows and Linux and I've noticed that the size suffix are incompatible when the config is created under Windows then transfered to Linux. (there is also incompatibility when the file is created under Linux then shared to Windows)

Ways to reproduce:

1. Create a new backend that receive size as parameter under Windows using **rclone config** command (using chunker in this example) and the output will look like:
```
[my_remote]
type = chunker
remote = another_remote:
chunk_size = 20Mi
hash_type = sha1all
```

2. Save the config file then move it to a Linux environment
3. Try to load the config file on Linux and The following error message will show
**Failed to create file system for "my_remote:": couldn't parse config item "chunk_size" = "20Mi" as fs.SizeSuffix: parsing "20Mi" as fs.SizeSuffix failed: bad suffix 'i'**

It is possible to workaround this behaviour by manually removing the **i** from the chunk_size (or any other parameter that receive size as parameter), in this case from **20Mi** to **20M**.

It is a bit of pain to decrypt the config, change then encrypt again everytime I need to update the file between those environments

**Comment by Masamune3210** [comment]
Double check both versions are on the same version of rclone, preferably latest

**Comment by animosity22** [comment]
It's version based and not OS based as mentioned above.

Please use the forums for general support questions.

Thanks!

https://forum.rclone.org
