### ISSUE TITLE
Google Drive - Multiple Service Accounts

### ISSUE THREAD

**Issue by rubenvarela** [rclone/rclone#6657]
#### The associated forum post URL from `https://forum.rclone.org`

Not mine, but similar,

- https://forum.rclone.org/t/rclone-service-accounts/20634/5
- https://forum.rclone.org/t/edit-service-account-while-mounted/15760/41

#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.61.1
- os/version: unknown
- os/kernel: 4.4.180+ (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.4
- go/linking: static
- go/tags: none
```

#### What problem are you are trying to solve?

Right now, there's no way to change, for a session, a service account. This means that you have to resort to loops until the data finishes. An example of a script here,

```
#!/bin/bash

OPERATION="move"

COPY_FROM="/mnt/Data/"
# Remote name
COPY_TO="Vault:/"

for file in ~/rclone-supplemental/safire/safire/svcaccts/*.json; do
    echo "$file"
#    echo \
    rclone \
    --drive-service-account-file "$file" \
    --drive-stop-on-upload-limit \
    --drive-chunk-size 256M \
    \
    --progress \
    --checkers 6 \
    --transfers 4 \
    \
    $OPERATION \
    $COPY_FROM \
    $COPY_TO

    # rclone exits with 7 when upload limit is reached
    # if not 7, let's exit
    EXIT_STATUS=$?
    if [[ $EXIT_STATUS -ne 7 ]]; then
        echo "Exit status: "
        echo $EXIT_STATUS
        break
    fi
    echo "Exit status: 7; continuing"
    echo ""
done
```

However, the problem with this is that it triggers a new sync. It doesn't continue. If there's a lot of new data coming in, it'll start transferring that too without remembering 'what's left' from the previous queue.

#### How do you think rclone should be changed to solve that?

I understand issues on the above threads with authentication on a `mount`, but would it be possible to add this support at least for COPY/MOVE and other operations?

I'm envisioning something like `--drive-service-account-dir` and we can pass a directory containing JSON files. Or maybe `--drive-service-account-file` but have it accept a wildcard? 

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Why are you changing service accounts in the midst of transfers? What's the use case?

**Comment by rubenvarela** [comment]
Each Service Account has a limit of 750GB per 24 hour period.

So any transfer of over 750GB would require switching when the cap is reached.

Now, each time it loops (in my example code), it has to go through checkers and process the whole queue again (since it’s a copy, the files are all still there).

**Comment by animosity22** [comment]
We don't encourage breaking the TOS for Google Drive by using Service Accounts that way.

**Comment by rubenvarela** [comment]
I have data I need to transfer to Google Drive during onboarding. The initial sync of the data is large.

I have a process set up where it transfer it using service accounts, since it’s an automated process.

On subsequent runs, it uses filters to transfer new data only which helps.

I understand not wanting to support it, but breaking TOS? Can you expand on that how?

**Comment by animosity22** [comment]
You are abusing the daily upload limit per their terms of service.

**Comment by rubenvarela** [comment]
The daily upload limit is per account. Not per organization.

I could also authenticate each users on this organization, but scheduling everyone to authenticate is not realistic and would add issues. Security issues being the main one with keeping all tokens. That’s what service accounts are for.

I can amend the script if needed to use  `--drive-impersonate` but it doesn’t seem it’s needed. 

Having said that, would this be best practice? If so, I can create a structure where each key is tied to a user and on each loop updated SA and impersonated user (but would need support for this as well).
