### ISSUE TITLE
Awareness against github https://giveupgithub.org

### ISSUE THREAD

**Issue by rihaq** [rclone/rclone#6658]
#### What is your current rclone version (output from `rclone version`)?

1.58.0

#### What problem are you are trying to solve?

Not a problem actually 

#### How do you think rclone should be changed to solve that?

No changes needed on rclone

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
This is not needed..
