### ISSUE TITLE
ADD report process PID in progress line [to ionice it]

### ISSUE THREAD

**Issue by allanlaal** [rclone/rclone#6661]
ADD report process PID in progress line [to ionice it]

**Comment by ncw** [comment]
You can query rclone's PID via the rc

https://rclone.org/rc/#core-pid

I don't think it is of general enough interest to put in the progress line.

However rclone could/should be ionicing itself maybe?

Though this is easy to do in a script

```
#!/bin/bash

# lower CPU and disk priority
renice 19 $$
ionice -c 3 -p $$

rclone .....
```

**Comment by animosity22** [comment]
Question was answered. 

Closing out.
