### ISSUE TITLE
Colorizing the tree output as default causing issue on Windows Shell or PowerShell stdout

### ISSUE THREAD

**Issue by luddinho** [rclone/rclone#6668]
#### The associated forum post URL from `https://forum.rclone.org`
https://github.com/rclone/rclone/pull/6591

#### What is the problem you are having with rclone?
Since the revision 1.61.0 the colorization of the tree command has become default.
In the previous versions you must use the -C or the --color option explicit.

The issue is present on Windows Shell or PowerShell.

#### What is your rclone version (output from `rclone version`)
rclone v1.61.1
- os/version: Microsoft Windows 10 Pro 22H2 (64 bit)
- os/kernel: 10.0.19045.2364 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.19.4
- go/linking: static
- go/tags: cmount

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Microsoft Windows 10 Pro 22H2 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)

- Onedrive
- koofr
- sftp

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
Versrions before 1.61.0: `rclone tree Onedrive: -C` to colorize the output.

Since version 1.61.0 the -C option can be ignored `rclone tree Onedrive:`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
The default colorization works fine on unix systems, but not on Windows Shell or PowerShell.

The output looks like this:
```
rclone tree koofr:temp
←[1;34m/←[0m
└── ←[1;34msubdir←[0m
    ├── file_1
    ├── file_2
    ├── file_3
    └── file_4
```

On the unix terminal it looks as expected including colorization:
```
rclone tree koofr:temp
/
└── subdir
    ├── file_1
    ├── file_2
    ├── file_3
    └── file_4
```

Windows Shell does not support the unix colorization parameters.

This is the result when using the v1.59.2 binary where the colorization option is available.
Comparision between lsiting the tree as default (no colorization) and with the extra option "-C".

```
PS C:\Users\luddinho> C:\Tools\rclone-windows-amd64\rclone_1-59-2.exe tree koofr:temp
/
└── subdir
    ├── file_1
    ├── file_2
    ├── file_3
    └── file_4

1 directories, 4 files

PS C:\Users\luddinho> C:\Tools\rclone-windows-amd64\rclone_1-59-2.exe tree koofr:temp -C
←[1;34m/←[0m
└── ←[1;34msubdir←[0m
    ├── file_1
    ├── file_2
    ├── file_3
    └── file_4

1 directories, 4 files
```

**Proposal:
Do not use the colorization for tree command as default option when rclone is used from a Windows OS that is called via Shell or PowerShell.**

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by luddinho** [comment]
Maybe from now on I have to use on Windows Shell or PowerShell explicitly the Global Flags "--color NEVER" to avoid rclone to print the colorization values.

This is the result.
```
rclone tree koofr:temp --color NEVER
/
└── subdir
    ├── file_1
    ├── file_2
    ├── file_3
    └── file_4

1 directories, 4 files
```

But it is not very user-friendly to explicitly suppress colorization when working on Windows Shell.
Please provide the possibility that colorization is disabled by default for Windows.

**Comment by ncw** [comment]
The colour should work in windows shells and I think @albertony tested it?

**Comment by luddinho** [comment]
Unfortunately it does not on my environment.
For this reason I have created this issue.

If I’m doing something wrong then please let me know.

**Comment by albertony** [comment]
Coloring works fine here, even in "good old" Command Prompt, on:

```
- os/version: Microsoft Windows 10 Enterprise 21H2 (64 bit)
- os/kernel: 10.0.19044.2364 (x86_64)
```

**Comment by luddinho** [comment]
But what is the difference on my machine?
Neither the good old command prompt nor the PowerShell does not work with colors on the tree command.

**Comment by albertony** [comment]
Thats the question... I don't know. From googling I see that at one point it had to be enabled in registry;

> in HKCU\Console create a DWORD named VirtualTerminalLevel and set it to 0x1; then restart cmd.exe.

But this should be default in newer versions, and you have even newer Windows build than me. I have not this explicitely in my registry, and if I try to set this to value 0x0, to see if this would turn coloring off, the coloring still works.

I still think there must be some Windows configuration that is different in yours and mine, but not sure what...

**Comment by luddinho** [comment]
Thanks for the information. I did my own research and found exactly your proposal on this site [How-to: Use ANSI colors in the terminal](https://ss64.com/nt/syntax-ansi.html).

In my case the DWORD "VirtualTerminalLevel" was not available on the machine, even tough I'm using a newer version of Windows than yours.
But the root cause might be, that the initial installation from my system was long before this flag was introduced by default and therefore the flag was never set during OS updates.

> Enabling ANSI colors in older versions of Windows
> To use ANSI colours in the Windows terminal requires setting VirtualTerminalLevel.
> 
> VirtualTerminalLevel = 1 is now set [by default](https://github.com/microsoft/terminal/pull/2824) for the terminal and in [ConPTY](https://github.com/microsoft/terminal/commit/1c412d42b3ac7fbaaf75324936211f4b4ed0e86f).
> In Windows [versions](https://ss64.com/nt/ver.html) 1511 through to 1903 this had to be enabled in the registry at:
> 
> [HKEY_CURRENT_USER\Console]
> "VirtualTerminalLevel"=dword:00000001

The current version I'm running is:
Microsoft Windows 10 Pro, 10.0.19045

For me adding the DWORD in the Registry fixed the problem with the colorization for both, the good old Command Prompt and the PowerShell.

![image](https://user-images.githubusercontent.com/76713238/210979210-282c3308-a711-4104-809f-b8335afccdfa.png)

@albertony Thanks for your input and the hint with the registry value.
It is definitely not a rclone issue, it is the environment configuration of Windows itself that caused the difficulty with colorization.

**Comment by ncw** [comment]
@luddinho - is this a test/beta/preview version of Windows? We've seen bugs in the terminal handling before in Windows but only in beta or preview versions.

**Comment by luddinho** [comment]
> is this a test/beta/preview version of Windows?

No it isn't. It is the latest version released for my machine during the default update procedure of the OS.

Our answers overlapped and I have identified the root cause on my machine. Please see my last comment.
Thanks for your support.

**Comment by albertony** [comment]
Actually, I don't have the `HKEY_CURRENT_USER\Console\VirtualTerminalLevel` value set at all! I created it to test with value 0, as mentioned, to see if it turned it off and reproduced your issue. But it wasn't there before, and I deleted it after the test. Confusing, but it must be something related to this, after all. I think I'm gonna 🙈 🙉 and just 🥳 that you got it working..

**Comment by luddinho** [comment]
> Actually, I don't have the `HKEY_CURRENT_USER\Console\VirtualTerminalLevel` value set at all!

That is a very strange behavior.
But for now I have the solution on my side. Hopefully not too many users running into this issue.

Kind regards
