### ISSUE TITLE
 SignatureDoesNotMatch: release 1.60.0 broke the copy using S3 backend with Other (GCS) as provider

### ISSUE THREAD

**Issue by panthony** [rclone/rclone#6670]
#### The associated forum post URL from `https://forum.rclone.org`

N/A

#### What is the problem you are having with rclone?

The copy of a file using S3 backend with `Other` provider (Google Cloud Storage) started to fail with the 1.60.0 release.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.60.0
- os/version: darwin 12.5.1 (64 bit)
- os/kernel: 21.6.0 (x86_64)
- os/type: darwin
- os/arch: amd64
- go/version: go1.19.2
- go/linking: dynamic
- go/tags: cmount
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

macOS 12.5.1, x86_64

#### Which cloud storage system are you using? (e.g. Google Drive)

S3 with Other as provider.

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
./rclone --config gcs_over_s3.conf copy source:/bucket/file .
```

With a config like:
```
[source]
type = s3
access_key_id = XXX
provider = Other
secret_access_key = XXX
endpoint = https://storage.googleapis.com
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
Failed to copy: failed to open source object: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.
```

Looking at the result of `--dump headers`:

- HEAD request still works
- GET request fails

When I compare the output between 1.60.0 and 1.59.2 for the GET request the only difference I can see (despite dates,...) is the order of request headers..

FAIL
```
Host: storage.googleapis.com
User-Agent: rclone/v1.60.0
Accept-Encoding: gzip
Authorization: XXXX
X-Amz-Content-Sha256: XXXX
X-Amz-Date: 20230106T081010Z
```

WORK
```
Host: storage.googleapis.com
User-Agent: rclone/v1.59.2
Authorization: XXXX
X-Amz-Content-Sha256: XXXXXX
X-Amz-Date: 20230106T080942Z
Accept-Encoding: gzip
```

The `X-Amz-Content-Sha256` is the same value for both request.

The headers of the HEAD request (works) of v1.60.0:

```
Host: storage.googleapis.com
User-Agent: rclone/v1.60.0
Authorization: XXXX
X-Amz-Content-Sha256: XXXXXX
X-Amz-Date: 20230106T081010Z
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by panthony** [comment]
And I can't try to debug this issue because for a reason I cannot fathom rclone won't build anymore :(

Tried a fresh go install using brew and/or gvm and different go version to no avail..

```
 make
go build -v --ldflags "-s -X github.com/rclone/rclone/fs.Version=v1.62.0-beta.6672.98fa93f6d"
rclone.go:7:2: cannot find package "github.com/rclone/rclone/backend/all" in any of:
        /Users/anthony/.gvm/gos/go1.18.2/src/github.com/rclone/rclone/backend/all (from $GOROOT)
        /Users/anthony/.gvm/pkgsets/go1.18.2/global/src/github.com/rclone/rclone/backend/all (from $GOPATH)
rclone.go:8:2: cannot find package "github.com/rclone/rclone/cmd" in any of:
        /Users/anthony/.gvm/gos/go1.18.2/src/github.com/rclone/rclone/cmd (from $GOROOT)
        /Users/anthony/.gvm/pkgsets/go1.18.2/global/src/github.com/rclone/rclone/cmd (from $GOPATH)
rclone.go:9:2: cannot find package "github.com/rclone/rclone/cmd/all" in any of:
        /Users/anthony/.gvm/gos/go1.18.2/src/github.com/rclone/rclone/cmd/all (from $GOROOT)
        /Users/anthony/.gvm/pkgsets/go1.18.2/global/src/github.com/rclone/rclone/cmd/all (from $GOPATH)
rclone.go:10:2: cannot find package "github.com/rclone/rclone/lib/plugin" in any of:
        /Users/anthony/.gvm/gos/go1.18.2/src/github.com/rclone/rclone/lib/plugin (from $GOROOT)
        /Users/anthony/.gvm/pkgsets/go1.18.2/global/src/github.com/rclone/rclone/lib/plugin (from $GOPATH)
make: *** [rclone] Error 1
```

**Comment by ncw** [comment]
I have a vague memory we fixed this in v1.61 - at least I'm sure there was a ticket about using GCS via the S3 interface.

Looks like you are trying to build in GOPATH mode - I don't think rclone builds like that any more.

`git clone` rclone to a fresh directory then just run `go build` or `make` - that should be enough. make sure you don't have `GO111MODULE` or similar set in your environment.

**Comment by panthony** [comment]
> I have a vague memory we fixed this in v1.61 - at least I'm sure there was a ticket about using GCS via the S3 interface.

I discovered the issue in this version, I then tried previous versions until I could pinpoint the culprit that is `v1.60.0`.

> Looks like you are trying to build in GOPATH mode - I don't think rclone builds like that any more.

I'm a novice with Go I just followed the instructions on how to install go then how to build rclone, I don't even know what GOPATH mode is 😅 

> make sure you don't have GO111MODULE or similar set in your environment.

You pinpointed me in the right direction, thanks.

I did not have that in my environment but it worked after I forced it to `on`.

**Comment by panthony** [comment]
@ncw I confirm that the culprit is this line:

```go
	// Override the automatic decompression in the transport to
	// download compressed files as-is
	httpReq.HTTPRequest.Header.Set("Accept-Encoding", "gzip")
```

We build a request using AWS SDK, it sign the request but then we mutate the actual request, breaking the signature.

**Comment by ncw** [comment]
> We build a request using AWS SDK, it sign the request but then we mutate the actual request, breaking the signature.

Are you saying this is a problem with your code or the rclone code? Are you passing in a signature as a header?

The go transport will add `Accept-Encoding: gzip` automatically if you don't add it here as far as I know.

**Comment by panthony** [comment]
@ncw I have the issue with the latest release of rclone.

If I checkout the master and build locally it fails.

If I comment this line:
> httpReq.HTTPRequest.Header.Set("Accept-Encoding", "gzip")

Build again & re-run it works.

What I suspect is that this header is injected in such a way that it is not taken into consideration when AWS sign the request which invalidates it.

**Comment by ncw** [comment]
I've not have any other reports of this causing a problem and I certainly would have done since s3 is one of the most popular backends.

This seems to be just a problem accessing GCS via the S3 interface. I can replicate this problem with GCS over the S3 interface.

The message is definitely signed **after** the header is set.

Looking at the response

```
accept-encoding:gzip,gzip(gfe)
host:storage.googleapis.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20230106T143135Z
```

That kind of indicates that GCS is receiving two `Accept-Encoding` headers, one with value `gzip` the other with value `gzip(gfe)`.

I added 2 accept-encoding headers and got this in the reply (showing 3 `Accept-Encoding` headers)

```
accept-encoding:gzip,gzip,gzip(gfe)
```

So it seems this theory is correct.

Where is the extra Accept-Encoding header coming from? I learn from [here](https://serverfault.com/questions/588272/how-to-get-iis-to-accept-encoding-gzipgfe):

> Google's PageSpeed Service forwards requests with the accept-encoding header set to gzip(gfe). 

So maybe this `Accept-Encoding` is being injected by Google?

I checked with `tcpdump` to a local minio running on plain HTTP and rclone definitely only sends one `Accept-Encoding` header.

```
	0x0000:  4500 0214 880f 4000 4006 58af ac11 0001  E.....@.@.X.....
	0x0010:  ac11 0002 b95c 2328 0b78 aba6 2ddf 96c6  .....\#(.x..-...
	0x0020:  8018 01f5 5a2c 0000 0101 080a 9ecd e3f5  ....Z,..........
	0x0030:  8bf3 7980 4745 5420 2f72 636c 6f6e 652f  ..y.GET./rclone/
	0x0040:  6669 6c65 2e74 7874 2048 5454 502f 312e  file.txt.HTTP/1.
	0x0050:  310d 0a48 6f73 743a 2031 3732 2e31 372e  1..Host:.172.17.
	0x0060:  302e 323a 3930 3030 0d0a 5573 6572 2d41  0.2:9000..User-A
	0x0070:  6765 6e74 3a20 7263 6c6f 6e65 2f76 312e  gent:.rclone/v1.
	0x0080:  3632 2e30 2d62 6574 612e 3636 3733 2e39  62.0-beta.6673.9
	0x0090:  6633 3531 6431 3431 2e76 6673 320d 0a41  f351d141.vfs2..A
	0x00a0:  6363 6570 742d 456e 636f 6469 6e67 3a20  ccept-Encoding:.
	0x00b0:  677a 6970 0d0a 4175 7468 6f72 697a 6174  gzip..Authorizat
	0x00c0:  696f 6e3a 2041 5753 342d 484d 4143 2d53  ion:.AWS4-HMAC-S
	0x00d0:  4841 3235 3620 4372 6564 656e 7469 616c  HA256.Credential
	0x00e0:  3d72 636c 6f6e 652f 3230 3233 3031 3036  =rclone/20230106
	0x00f0:  2f75 732d 6561 7374 2d31 2f73 332f 6177  /us-east-1/s3/aw
	0x0100:  7334 5f72 6571 7565 7374 2c20 5369 676e  s4_request,.Sign
	0x0110:  6564 4865 6164 6572 733d 6163 6365 7074  edHeaders=accept
	0x0120:  2d65 6e63 6f64 696e 673b 686f 7374 3b78  -encoding;host;x
	0x0130:  2d61 6d7a 2d63 6f6e 7465 6e74 2d73 6861  -amz-content-sha
	0x0140:  3235 363b 782d 616d 7a2d 6461 7465 2c20  256;x-amz-date,.
	0x0150:  5369 676e 6174 7572 653d 3735 6566 3638  Signature=75ef68
	0x0160:  3661 6634 3730 6337 3237 6437 3966 3464  6af470c727d79f4d
	0x0170:  6534 3766 3963 3366 3834 6139 6132 3862  e47f9c3f84a9a28b
	0x0180:  6633 3365 3965 3830 3064 3534 6136 3734  f33e9e800d54a674
	0x0190:  6639 3265 3664 3738 3461 0d0a 582d 416d  f92e6d784a..X-Am
	0x01a0:  7a2d 436f 6e74 656e 742d 5368 6132 3536  z-Content-Sha256
	0x01b0:  3a20 6533 6230 6334 3432 3938 6663 3163  :.e3b0c44298fc1c
	0x01c0:  3134 3961 6662 6634 6338 3939 3666 6239  149afbf4c8996fb9
	0x01d0:  3234 3237 6165 3431 6534 3634 3962 3933  2427ae41e4649b93
	0x01e0:  3463 6134 3935 3939 3162 3738 3532 6238  4ca495991b7852b8
	0x01f0:  3535 0d0a 582d 416d 7a2d 4461 7465 3a20  55..X-Amz-Date:.
	0x0200:  3230 3233 3031 3036 5431 3434 3434 315a  20230106T144441Z
	0x0210:  0d0a 0d0a                                ....
```

So this looks like a Google GCS bug to me.

Can you ask Google support about it?

**Comment by panthony** [comment]
I found someone with a similar issue:

https://stackoverflow.com/questions/73717477/gcp-cloud-storage-golang-aws-sdk2-upload-file-with-s3-interoperability-creds

**Comment by panthony** [comment]
Out of curiosity how did you see `gzip(gfe)`? There are no accept-encoding header in the response 🤔 

```
2023/01/06 17:13:45 DEBUG : HTTP RESPONSE (req 0xc000654400)
2023/01/06 17:13:45 DEBUG : HTTP/2.0 403 Forbidden
Content-Length: 829
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Cache-Control: private, max-age=0
Content-Type: application/xml; charset=UTF-8
Date: Fri, 06 Jan 2023 16:13:45 GMT
Expires: Fri, 06 Jan 2023 16:13:45 GMT
Server: UploadServer
X-Guploader-Uploadid: XXXXXXXXXXXX
```

**Comment by ncw** [comment]
That SO question has the `gzip(gfe)` string in it which is interesting.

The github bug says

> I found the issue of the problem. When I remove accept-encoding header from signed headers, problem is solved. Instead of
> 
>     SignedHeaders=accept-encoding;amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date,
> I used
> 
>     SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date,
> Do you know the reason why accept-encoding is added as one of the SignedHeaders in aws-sdk-go-v2? It is not used in aws-sdk-go.

And then later

> Unfortunately I couldn't find a way to exclude accept-encoding without changing the source code of the sdk.

Maybe there is a way now - do you fancy having a trawl through the SDK @panthony ?

I just realised why this is a problem now and wasn't before. If you comment out the `Accept-Encoding` header, the HTTP transport adds it back in, but **after** the headers have been signed. So when Google injects the extra  `Accept-Encoding` header it isn't checked.

A permanent solution for this might be to have a `provider = GCS` and add a quirk for this.

**Comment by panthony** [comment]
> Maybe there is a way now - do you fancy having a trawl through the SDK @panthony ?

Which SDK? AWS?

Might be better to have a GCS provider even if I'm not sure what it entails 🤔 

If rclone were to move forward with the AWS SDK V2 it would probably be less painful.

**Comment by ncw** [comment]
> > Maybe there is a way now - do you fancy having a trawl through the SDK @panthony ?
> 
> Which SDK? AWS?

Yes, `github.com/aws/aws-sdk-go/service/s3`

> Might be better to have a GCS provider even if I'm not sure what it entails thinking

Its quite easy generally.

> If rclone were to move forward with the AWS SDK V2 it would probably be less painful.

Urgh! Know anyone who'd like to sponsor me to do that? Its probably a weeks work or more.

**Comment by panthony** [comment]
I saw an opened issue that could solve this issue:

https://github.com/aws/aws-sdk-go/issues/4662

**Comment by ncw** [comment]
Do you want to have a go at adding a `provider = GCS` @panthony ? That is the proper way of making a workaround.

**Comment by panthony** [comment]
I bootstrapped something here:

https://github.com/rclone/rclone/pull/6677/files

Things I'm not quite sure:
 - Is there a clean way to have a default value such as endpoint for a specific provider or the way to go is to suggest that value through the wizard and have the value explicit set in the config?

- Is it possible to have an internal flag (ex `ForceGzipHeader` here) or should they all be exposed options with a documentation? (I'm not quite sure how to describe this :D)

**Comment by ncw** [comment]
> I bootstrapped something here:
> 
> https://github.com/rclone/rclone/pull/6677/files

Very nice - I put some review comments on it.

> Things I'm not quite sure:
> 
> * Is there a clean way to have a default value such as endpoint for a specific provider or the way to go is to suggest that value through the wizard and have the value explicit set in the config?

That is what the `fs.Tristate` flags are for. There default state is `auto` rclone decides, but the user can force them true or false.

> * Is it possible to have an internal flag (ex `ForceGzipHeader` here) or should they all be exposed options with a documentation? (I'm not quite sure how to describe this :D)

Yes it is, but I always put all the options in the docs as someone inevitably ends up needing it!

**Comment by panthony** [comment]
Thanks for your feedbacks, PR updated

**Comment by panthony** [comment]
Fixed by https://github.com/rclone/rclone/pull/6677
