### ISSUE TITLE
google drive client ID error,Windows 7. Please help.

### ISSUE THREAD

**Issue by Intellectual234** [rclone/rclone#6676]
I got rclone installed & mounted,set up right, it works. It was a real pain,definitely not user friendly at all. Only problem is that i have to use default rclone ID with gdrive/rclone, which makes everything much slower. because when i try make my own client ID i get this error(see image below) when i am at this link:

https://console.cloud.google.com/rif-empty-page?project=rclone-373407

https://i.paste.pics/KRHSQ.png

Also, let me know if u need me to get a log for you, i didnt think it would help.

-Thanks!

**Comment by ncw** [comment]
This site is for confirmed bug reports only.

Can you open a thread on [the rclone forum](https://forum.rclone.org/) please and you'll get some help there.

Thank you.
