### ISSUE TITLE
--create-empty-src-dirs & runtime: VirtualAlloc of 8192 bytes failed with errno=1455  fatal error: out of memory

### ISSUE THREAD

**Issue by MJAvH** [rclone/rclone#6683]
#### Output of `rclone version`
```
E:\>rclone version
rclone v1.60.1
- os/version: Microsoft Windows Server 2019 Standard 1809 (64 bit)
- os/kernel: 10.0.17763.3770 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.19.3
- go/linking: static
- go/tags: cmount
```

Hello,

I use this command:
`rclone sync -P --transfers 64 \\my-network\shared-folder linux_server:/my-folder/ --log-file E:\log\20230110-rclone.log --log-level INFO --fast-list --exclude=/.backups`

Copy form a network share (CIFS with NTFS file system) to a linux server (via SSH) on a NFS file system.

All works correctly (all data copied and on next run synchronized) until I spotted that empty folders form  \\my-network\shared-folder are not copied/synced on linux_server:/my-folder/

So, I added this option: `--create-empty-src-dirs` Create empty source dirs on destination after sync

I tried several times with these different commands:

```
rclone sync -P --transfers 64 \\my-network\shared-folder linux_server:/my-folder/ --log-file E:\log\20230110-rclone.log --log-level INFO --fast-list --exclude=/.backups --create-empty-src-dirs
rclone sync -P --transfers 8 --create-empty-src-dirs \\my-network-shared-folder linux_server:/my-folder/ --log-file E:\log\20230110-rclone.log --log-level INFO --fast-list --exclude=/.backups
rclone sync -P --transfers 8 --create-empty-src-dirs \\my-network-shared-folder linux_server:/my-folder/ --log-file E:\log\20230110-rclone.log --log-level DEBUG --exclude=/.backups
rclone sync -P --transfers 8 --create-empty-src-dirs \\my-network-shared-folder linux_server:/my-folder/ --log-file E:\log\20230110-rclone.log --log-level INFO
```

but result is that memory RAM on my server, 16GB, is consumed up to 100% and rclone abort sync. In logs of rclone, I found this error:

```
runtime: VirtualAlloc of 8192 bytes failed with errno=1455
fatal error: out of memory
```

What I do wrongly? Any idea or suggestion?

If more details is needed, please write. Logs that rclone made when crashed have size of 33 Mb to 40 Mb.

Thank you

MJAvH

**Comment by ncw** [comment]
Rclone has to store the directories to create them at the end. This shouldn't take a lot of memory unless you have millions of directories?

Can you run rclone with the `--rc` flag and attempt to take a memory profile as documented here: https://rclone.org/rc/#debugging-memory-use

If you could attach the SVG generated by `go tool pprof -svg http://localhost:5572/debug/pprof/heap` that would be most usful.

You'll need to catch rclone after it starts using more memory than normal but before it runs the system out of memory.

**Comment by MJAvH** [comment]
Hello,

Thx @ncw for your suggestion about amount of files/folders. This is somewere documented? If yes, I didn't found :-( 

Yes, in source I have +/- 3 500 000 files and +/- 160 000 folders.

**This solution worked in my case:** I splited this one big `rclone sync` in 5 separate process and empty folders were created. Memory is used but not up to 100% as it was before.

Thx for a geat tool `rclone`!!!

**Comment by ncw** [comment]
Splitting the sync is a good idea.

I wouldn't have thought 160k folders would take more than 160M of memory.

I'm going to close this since you've found a workaround, but I'll keep it in mind for later!
