### ISSUE TITLE
Contabo bucket storage

### ISSUE THREAD

**Issue by snowboarder** [rclone/rclone#6690]
I was wondering if anyone has gotten rclone to work with [Contabo object storage](https://contabo.com/en/object-storage/)?  Its not on the list of supported services but I have found its one of the cheapest bucket storage solutions available for non-critical projects  it has worked out fine.

**Comment by ncw** [comment]
It says it has an S3-Compatible API so should configure up and work.

It is possible it could require some tweaks.

Ideally we'd make an S3 provider for it.

A bit of searching finds this: https://docs.contabo.com/docs/products/Object-Storage/Tools/rclone/ - the instructions on how to set up rclone with contabo!

**Comment by animosity22** [comment]
For the future, please use the forums for general questions.

https://forum.rclone.org

Closing as answered.

**Comment by snowboarder** [comment]
> For the future, please use the forums for general questions.
> 
> https://forum.rclone.org
> 
> Closing as answered.

Ya I was looking for the URL to the forum but was unable to find it earlier on the github page.  Thanks
