### ISSUE TITLE
rclone uploadfile command doc 404

### ISSUE THREAD

**Issue by kouhe3** [rclone/rclone#6693]
https://rclone.org/rc/#operations-uploadfile

See the [uploadfile](https://rclone.org/commands/rclone_uploadfile/) command for more information on the above.

**Comment by albertony** [comment]
I see; the "uploadfile" link is broken, it points to url https://rclone.org/commands/rclone_uploadfile/ which does not exist. I have no idea what it is supposed to point to, but looking at the implementation of the rc uploadfile - the closest match seem to be https://rclone.org/commands/rclone_rcat/.. 🤔

**Comment by ncw** [comment]
`uploadfile` doesn't have a command equivalent... The closes thing would be `rclone rcat` but I think we should just drop the link here.

**Comment by Jwink3101** [comment]
There was a regression: https://github.com/rclone/rclone/blob/23579e3b99d909c760795b798928c1545aac6298/docs/content/rc.md?plain=1#L1461

**Comment by ncw** [comment]
That is the autogenerated part of the document. We need to edit `fs/operations/rc.go` I think
