### ISSUE TITLE
Cannot mount driver letter if uploads pending or resuming when Rclone starts.

### ISSUE THREAD

**Issue by fordiy** [rclone/rclone#6696]
The problem still exist in version of 1.61.1
The mount doesn't normally start the driver letter in Windows10 when it has lots of uploads pending to finish. No matter reboot the PC to try to cancel the uploads, still always resume the uploads, and pending to finish all uploads before it can mount. Here the mount cmd:
rclone mount ALIST:/ R: --cache-dir j:\tmp\rclone --vfs-cache-mode writes --no-modtime --multi-thread-streams 8 --vfs-read-chunk-size  256M --vfs-read-chunk-size-limit 600M  --buffer-size 4096M

**Comment by animosity22** [comment]
That's known and documented.

Please use the forums for general use questions.

https://forum.rclone.org

Posts not following the template and asking questions make life tough for all of us.
