### ISSUE TITLE
Failed to create file system for "OneDrive_Business:/": didn't find section in config file

### ISSUE THREAD

**Issue by asoshnin** [rclone/rclone#6697]
I've just installed RClone with GUI on my Raspberry pi4 and configured OneDrive, GoogleDrive and DropBox connections.
All connections work perfectly well from GUI. I was able to copy files to my local storage.
But when I try **rclone lsd OneDrive_Business:** from the terminal I get an error: **"Failed to create file system for "OneDrive_Business:": didn't find section in config file".** Same command line for other connected cloud drives works fine.

I edited config for onedrive a couple of times. The issue remains. Works fine from GUI, can't access from terminal.

I'm new to Linux. Googled the subj but couldn't find a similar issue. Would appreciate any advise. 

OS:  raspbian 11.6; rclone: v1.61.1; onedrive global for business

**Comment by animosity22** [comment]
Please use the forums for general support.

https://forum.rclone.org

**Comment by asoshnin** [comment]
Found the problem. I had a typo in the config file. OneDirve instead of OneDrive.
