### ISSUE TITLE
Internet Archive upload error

### ISSUE THREAD

**Issue by a0v0** [rclone/rclone#6708]
#### What is the problem you are having with rclone?
Failed to about: about call failed: bucket or container name is needed in remote

#### What is your rclone version (output from `rclone version`)
```
rclone v1.61.1
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-1028-aws (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.4
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
ubuntu 22.04 

#### Which cloud storage system are you using? (e.g. Google Drive)
Internet Archive

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
Failed to about: about call failed: bucket or container name is needed in remote

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
You need to use a container name in the remote.

Please use the forums for general support.

https://forum.rclone.org
