### ISSUE TITLE
Docs for rclone copyto should describe how to copy a file to a directory

### ISSUE THREAD

**Issue by j13ag0** [rclone/rclone#6717]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/copyto-bug-when-destination-is-a-directory/35601/4

#### What is the problem you are having with rclone?

copyto does something different than described in [Docs](https://rclone.org/commands/rclone_copyto/).

rclone copyto Docs say:

```
rclone copyto src dst
```

then

```
if src is file
    copy it to dst, overwriting an existing file if it exists
if src is directory
    copy it to dst, overwriting existing files if they exist
    see copy command for full details
```

For the case where src is a file and dst is a directory:
- copyto  complains that  dst 

```
    <time stamp> ERROR : Attempt <x>/3 failed with 1 errors and: is a directory not a file
```

Working around it:

if you want the file copied to dst to have the same name as the one at src:
- make dst include the filename in the copyto parameters, 

#### What is your rclone version (output from `rclone version`)

rclone v1.61.1
os/version: darwin 12.5.1 (64 bit)
os/kernel: 21.6.0 (arm64)
os/type: darwin
os/arch: arm64
go/version: go1.19.4
go/linking: dynamic
go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

MacOS 12.5.1

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone copyto

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

2023/01/20 00:30:28 ERROR : Attempt 1/3 failed with 1 errors and: is a directory not a file
2023/01/20 00:30:28 ERROR : Attempt 2/3 failed with 1 errors and: is a directory not a file
2023/01/20 00:30:29 ERROR : Attempt 3/3 failed with 1 errors and: is a directory not a file
2023/01/20 00:30:29 Failed to copyto: is a directory not a file            

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Feel free to submit a PR if you'd like different wording:

https://github.com/rclone/rclone/blob/master/docs/content/commands/rclone_copyto.md

Click on the pencil and you can suggest any changes you'd like.

**Comment by j13ag0** [comment]
I'm a github noob.  How do I view the commit associated with this Closure ?
Thanks
-jg-
