### ISSUE TITLE
Google Photos backend creating hundreds of single-photo albums

### ISSUE THREAD

**Issue by dan1elhughes** [rclone/rclone#6724]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/google-photos-backend-creating-hundreds-of-single-photo-albums/35665

👋 Unsure of the etiquette here around posting on both the issue tracker *and* forum, but I have updated to the latest at the time of writing (v1.61.1) and I'm still experiencing this issue. ❤️ 

#### What is the problem you are having with rclone?

When syncing to Google Photos "album" location, it creates hundreds of albums containing one photo each, instead of an album with all the photos in for each directory as I would expect. Some albums appear to contain the right number of photos, but I now have hundreds of erroneous albums, with no bulk-delete function available. :flushed:

#### What is your rclone version (output from `rclone version`)

```
rclone v1.59.2
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.4.0-137-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.18.6
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

```
uname -a
Linux sinkhole 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Photos

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
rclone sync ~/Backups/Exports photos:album --log-level DEBUG --log-file ~/rclone/photos.txt --tpslimit 1
```

My Exports directory is structured as follows:

```
tree | tail -n 100
# ...
├── 2022-10-28 Blahblah
│   ├── DSCF4644.jpeg
│   ├── DSCF4646.jpeg
│   ├── DSCF4650.jpeg
│   ├── DSCF4695.jpeg
│   ├── DSCF4697.jpeg
│   ├── DSCF4727.jpeg
│   ├── DSCF4731.jpeg
│   └── DSCF4738.jpeg
├── 2022-11-03 Blahblah
│   ├── DSCF4782.jpeg
│   ├── DSCF4797.jpeg
│   ├── DSCF4829.jpeg
│   └── DSCF4845.jpeg
├── 2022-11-27 Blahblah
│   ├── DSCF4882.jpeg
│   ├── DSCF4891.jpeg
│   ├── DSCF4893.jpeg
│   ├── DSCF4899.jpeg
│   ├── DSCF4900.jpeg
│   ├── DSCF4903.jpeg
│   ├── DSCF4906.jpeg
│   ├── DSCF4918.jpeg
│   └── DSCF4951.jpeg
```

So I would expect each single directory to create one single album containing all the photos within that directory.

Instead, I see each photo in its own album:

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/9041370/214171354-8ea61ad1-4352-4f5b-a254-a55ffeeea949.png">

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

🔗 [Logs](https://pastebin.com/raw/ZejDJ9hp).

I killed the rsync job here as it had already created 3 new albums (per `watch 'rclone lsd photos:album | grep \{ | wc -l'`), and there's no easy way to mass-delete albums on Google Photos.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Please don't double post :(

Let's continue on the forums.
