### ISSUE TITLE
[Feature] support --network-mode on MacOS mount for devices that cannot enable system extensions

### ISSUE THREAD

**Issue by alshdavid** [rclone/rclone#6725]
#### What is your current rclone version (output from `rclone version`)?

rclone v1.60.1
- os/version: darwin 13.1 (64 bit)
- os/kernel: 22.2.0 (arm64)
- os/type: darwin
- os/arch: arm64
- go/version: go1.19.3
- go/linking: dynamic
- go/tags: cmount

#### What problem are you are trying to solve?

To use rclone on MacOS you need to install macfuse. To install macfuse you need to enable system extensions, which requires putting the OS into "reduced security" mode.

For some users this may be impossible either due to policy or account restrictions there by making it impossible to use rclone.

#### How do you think rclone should be changed to solve that?

If rclone could enable a means to use `--network-mode` on MacOS it could allow the access of rclone remotes through native MacOS capabilities (like SMB). 

The use of native capabilities would bypass the requirement for macfuse, allowing users unable to install system macfuse access to rclone remotes. 

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Users have had some success using [FUSE-T](https://www.fuse-t.org/) with macOS which doesn't require a system extension.

Check out this thread for details https://forum.rclone.org/t/fr-fuse-t-support-for-mounting-volumes-on-mac/33110

FUSE-T should work with v1.61.1 as released.

PS Note `--network-mode` is to tell the OS that the drive connected is a network drive.

**Comment by alshdavid** [comment]
That certainly solves my issue, thanks!
