### ISSUE TITLE
Can't able to verify google auth code

### ISSUE THREAD

**Issue by SharmagRit** [rclone/rclone#6729]
Pls checkout this problem, i have tried many times but same issue
![image](https://user-images.githubusercontent.com/87909274/214759369-584350e6-5931-4cb5-97b2-4fa268106210.png)

**Comment by Masamune3210** [comment]
https://rclone.org/drive/#making-your-own-client-id

**Comment by SharmagRit** [comment]
> https://rclone.org/drive/#making-your-own-client-id

Thanks sir, it's working now
but now i find that when i set team drive under rclone.conf then its not uploading to team drive and without team drive config it's uploading fine with root storage, can you help me again with this issue please sir.

**Comment by olefrost** [comment]
Please create a "Help & Support" post in the forum with all the details requested in the template:
https://forum.rclone.org/
