### ISSUE TITLE
Provider features aren't always set for Storj and IDrive

### ISSUE THREAD

**Issue by olefrost** [rclone/rclone#6734]
#### The associated forum post URL from `https://forum.rclone.org`

None, discovered while debugging/reading code to understand how `rclone cat` handles duplicate names in S3.

#### What is the problem you are having with rclone?

It seems like the code to set the provider specific features for Stroj and IDrive are placed to late in NewFS and therefore sometimes the values will not be set due to conditional returns earlier in the code.

I haven't tested, but looks like these lines:
https://github.com/rclone/rclone/blob/8e63a08d7f51f1c34f8f6e1ab72f8bbb5ebea544/backend/s3/s3.go#L3006-L3012

Should be moved up just before the `if f.rootBucket ...` statement here:

https://github.com/rclone/rclone/blob/8e63a08d7f51f1c34f8f6e1ab72f8bbb5ebea544/backend/s3/s3.go#L2988-L3015

#### What is your rclone version (output from `rclone version`)

Latest master (1.62.0-DEV)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment]
Your suggested change makes perfect sense to me, nice catch. - But I'm not familiar with these backends, so I was hoping someone who are could comment as well.

**Comment by ncw** [comment]
@olefrost your analysis looks spot on to me. The early returns are for the root path pointing to a file, so not uncommon.

Do you want to make a PR for this?

**Comment by olefrost** [comment]
Sure, I would appreciate if somebody else can do the backend testing, all I have is a free tier AWS S3 account.

**Comment by ncw** [comment]
I have all the Storj accounts so can test :-)
