### ISSUE TITLE
open("x") followed by close() and then unlink("x") leaves "x" on the FS

### ISSUE THREAD

**Issue by jaroslawr** [rclone/rclone#6739]
#### What is the problem you are having with rclone?

With a dropbox-based remote mounted with "rclone mount" under "Dropbox/", running the below test program results in "x" being present on the FS:

```c
#include <fcntl.h>

int main() {
	char* f = "Dropbox/x";
	int fd = open(f, O_CREAT | O_WRONLY);
	close(fd);
	unlink(f);
}
```

I run into this because Neovim writes temporary files with random four digit names like "1234" each time you save any file and it uses a syscall sequence roughly like above. Soon the directory is full of these files.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.60.1-DEV
- os/version: debian bookworm/sid (64 bit)
- os/kernel: 6.1.0-1-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.4
- go/linking: dynamic
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Debian Bookworm 64-bit

#### Which cloud storage system are you using? (e.g. Google Drive)

Dropbox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone mount`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2023/02/02 09:24:51 DEBUG : /: Create: name="x"
2023/02/02 09:24:51 DEBUG : x: Open: flags=O_WRONLY|O_CREATE
2023/02/02 09:24:51 DEBUG : : Added virtual directory entry vAddFile: "x"
2023/02/02 09:24:51 DEBUG : x: >Open: fd=x (w), err=<nil>
2023/02/02 09:24:51 DEBUG : /: >Create: node=x, handle=&{x (w)}, err=<nil>
2023/02/02 09:24:51 DEBUG : x: Attr: 
2023/02/02 09:24:51 DEBUG : x: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
2023/02/02 09:24:51 DEBUG : &{x (w)}: Flush: 
2023/02/02 09:24:51 DEBUG : x: WriteFileHandle.Flush unwritten handle, writing 0 bytes to avoid race conditions
2023/02/02 09:24:51 DEBUG : : Added virtual directory entry vAddFile: "x"
2023/02/02 09:24:51 DEBUG : &{x (w)}: >Flush: err=<nil>
2023/02/02 09:24:51 DEBUG : &{x (w)}: Release: 
2023/02/02 09:24:51 DEBUG : x: WriteFileHandle.Release closing
2023/02/02 09:24:51 DEBUG : /: Remove: name="x"
2023/02/02 09:24:51 DEBUG : Dropbox root '': File to upload is small (0 bytes), uploading instead of streaming
2023/02/02 09:24:51 DEBUG : x: Remove: 
2023/02/02 09:24:51 DEBUG : : Added virtual directory entry vDel: "x"
2023/02/02 09:24:51 DEBUG : x: >Remove: err=<nil>
2023/02/02 09:24:51 DEBUG : /: >Remove: err=<nil>
2023/02/02 09:24:51 DEBUG : x: Uploading chunk 1/0
2023/02/02 09:24:52 DEBUG : x: Uploading chunk 2/0
2023/02/02 09:24:52 DEBUG : Dropbox root '': Adding "/x" to batch
2023/02/02 09:24:53 DEBUG : Dropbox root '': Batch idle for 500ms so committing
2023/02/02 09:24:53 DEBUG : Dropbox root '': Committing sync batch length 1 starting with: /x
2023/02/02 09:24:53 DEBUG : Dropbox root '': Committed sync batch length 1 starting with: /x
2023/02/02 09:24:53 DEBUG : x: dropbox = e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 OK
2023/02/02 09:24:53 INFO  : x: Copied (new)
2023/02/02 09:24:53 DEBUG : : Added virtual directory entry vAddFile: "x"
2023/02/02 09:24:53 DEBUG : &{x (w)}: >Release: err=<nil>
2023/02/02 09:24:58 INFO  : Signal received: interrupt
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by jaroslawr** [comment]
FWIW it still leaves the file "x" on the FS with `--dropbox-batch-mode off`, with a log like this:

```
2023/02/02 09:40:22 DEBUG : /: Lookup: name="x"
2023/02/02 09:40:22 DEBUG : /: >Lookup: node=x, err=<nil>
2023/02/02 09:40:22 DEBUG : x: Attr: 
2023/02/02 09:40:22 DEBUG : x: >Attr: a=valid=1s ino=0 size=0 mode=-rw-r--r--, err=<nil>
2023/02/02 09:40:22 DEBUG : x: Open: flags=OpenWriteOnly
2023/02/02 09:40:22 DEBUG : x: Open: flags=O_WRONLY
2023/02/02 09:40:22 DEBUG : x: >Open: fd=x (w), err=<nil>
2023/02/02 09:40:22 DEBUG : x: >Open: fh=&{x (w)}, err=<nil>
2023/02/02 09:40:22 DEBUG : &{x (w)}: Flush: 
2023/02/02 09:40:22 DEBUG : x: WriteFileHandle.Flush unwritten handle, writing 0 bytes to avoid race conditions
2023/02/02 09:40:22 ERROR : x: WriteFileHandle: Can't open for write without O_TRUNC on existing file without --vfs-cache-mode >= writes
2023/02/02 09:40:22 DEBUG : &{x (w)}: >Flush: err=operation not permitted
2023/02/02 09:40:22 DEBUG : /: Remove: name="x"
2023/02/02 09:40:22 DEBUG : x: Remove: 
2023/02/02 09:40:22 DEBUG : : Added virtual directory entry vDel: "x"
2023/02/02 09:40:22 DEBUG : &{x (w)}: Release: 
2023/02/02 09:40:22 DEBUG : x: WriteFileHandle.Release closing
2023/02/02 09:40:23 DEBUG : x: >Remove: err=<nil>
2023/02/02 09:40:23 DEBUG : /: >Remove: err=<nil>
2023/02/02 09:40:23 DEBUG : &{x (w)}: >Release: err=<nil>
2023/02/02 09:40:24 INFO  : Signal received: interrupt
```

Adding `--vfs-cache-mode full` makes the behaviour as expected ("x" no longer left on the FS).

**Comment by ncw** [comment]
`--vfs-cache-mode writes` is necessary to avoid this most likely.

The higher you go up in VFS cache mode the more "compatible" the rclone mount gets.

As for why this happens

Here is the file being opened

    DEBUG : x: Open: flags=O_WRONLY|O_CREATE
    DEBUG : : Added virtual directory entry vAddFile: "x"
    DEBUG : x: >Open: fd=x (w), err=<nil>
    
    DEBUG : x: Attr: 
    DEBUG : x: >Attr: a=valid=1s ino=0 size=0 mode=-rw-rw-r--, err=<nil>

The OS then flushes it which is a signal that userspace closed the file, but not that the OS is finished with the file.

    DEBUG : &{x (w)}: Flush: 
    DEBUG : x: WriteFileHandle.Flush unwritten handle, writing 0 bytes to avoid race conditions
    DEBUG : : Added virtual directory entry vAddFile: "x"
    DEBUG : &{x (w)}: >Flush: err=<nil>

The OS then removed the file and started the Release pretty much simultaneously

    DEBUG : /: Remove: name="x" <-- remove started
    DEBUG : &{x (w)}: Release:   <--- release started
    DEBUG : x: Remove: 
    DEBUG : x: WriteFileHandle.Release closing
    DEBUG : : Added virtual directory entry vDel: "x"
    DEBUG : x: >Remove: err=<nil>
    DEBUG : /: >Remove: err=<nil>

And the release finishes up which actually uploads the file

    DEBUG : Local file system at /tmp/source: File to upload is small (0 bytes), uploading instead of streaming
    DEBUG : x: md5 = d41d8cd98f00b204e9800998ecf8427e OK
    INFO  : x: Copied (new)
    DEBUG : : Added virtual directory entry vAddFile: "x"
    DEBUG : &{x (w)}: >Release: err=<nil>

Interestingly if I use `rclone cmount` then it gets the operations in the correct order

    DEBUG : /x: Getattr: fh=0xFFFFFFFFFFFFFFFF
    DEBUG : /x: >Getattr: errc=-2
    DEBUG : /x: CreateEx: flags=0x8041, mode=0101510
    DEBUG : x: Open: flags=O_WRONLY|O_CREATE
    DEBUG : : Added virtual directory entry vAddFile: "x"
    DEBUG : x: >Open: fd=x (w), err=<nil>
    DEBUG : /x: >CreateEx: errc=0, fh=0x0
    DEBUG : /x: Getattr: fh=0x0
    DEBUG : /x: >Getattr: errc=0
    DEBUG : /x: Flush: fh=0x0
    DEBUG : x: WriteFileHandle.Flush unwritten handle, writing 0 bytes to avoid race conditions
    DEBUG : : Added virtual directory entry vAddFile: "x"
    DEBUG : /x: >Flush: errc=0
    DEBUG : /x: Release: fh=0x0
    DEBUG : x: WriteFileHandle.Release closing
    DEBUG : Local file system at /tmp/source: File to upload is small (0 bytes), uploading instead of streaming
    DEBUG : x: md5 = d41d8cd98f00b204e9800998ecf8427e OK
    INFO  : x: Copied (new)
    DEBUG : : Added virtual directory entry vAddFile: "x"
    DEBUG : /x: >Release: errc=0
    DEBUG : /x: Unlink: 
    DEBUG : x: Remove: 
    DEBUG : : Added virtual directory entry vDel: "x"
    DEBUG : x: >Remove: err=<nil>
    DEBUG : /x: >Unlink: errc=0

And it works fine. So you could use that (compile rclone with `-tags cmount` to get the `rclone cmount` command).

I think this is probably related to https://github.com/bazil/fuse/issues/129 - the library launches multiple workers and they race out of the clients control.

**Comment by animosity22** [comment]
Is this good to close out as it looks answered?

**Comment by ncw** [comment]
I don't think this is an rclone bug. Work around with `--vfs-cache-mode full` or use `rclone cmount`.

I'll close this.
