### ISSUE TITLE
 Customize HTML page used in responses from `rclone authorize` 

### ISSUE THREAD

**Issue by hwittenborn** [rclone/rclone#6741]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/customize-html-page-used-in-responses-from-rclone-authorize/35128/1

#### What is your current rclone version (output from `rclone version`)?
v1.53.3-DEV

#### What problem are you are trying to solve?
Customizing the HTML shown on `rclone authorize` output so that it fits my application's branding

#### How do you think rclone should be changed to solve that?
Add a flag to the `rclone authorize` command to read a Go template that will be used for output (i.e. `rclone authorize --template my-template.html`)
.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I believe you are working on that @hwittenborn is that right?

**Comment by hwittenborn** [comment]
Yeah that's correct @ncw. I'm just looking around the codebase to figure out how it's structured, but I'll send a message if I have any questions :)

**Comment by hwittenborn** [comment]
I'm looking into this a little bit but I'm getting a bit stumped: I'm needing to pass a template into the `newAuthServer` like shown at https://github.com/rclone/rclone/blob/master/lib/oauthutil/oauthutil.go#L758, but when I attempt to add a `template string` argument I get the following error in my terminal:

```
lib/oauthutil/oauthutil.go:823:22: cannot use s.handleAuth (value of type func(w http.ResponseWriter, req *http.Request, template string)) as type func(http.ResponseWriter, *http.Request) in argument to mux.HandleFunc
```

From what it's looking like it looks like some library Rclone uses is requiring a certain function signature, but I'm not exactly sure how I would get around that. Should I just make a global variable that can be accessed outside that function and then just read that inside of it?

**Comment by ncw** [comment]
> From what it's looking like it looks like some library Rclone uses is requiring a certain function signature, but I'm not exactly sure how I would get around that. Should I just make a global variable that can be accessed outside that function and then just read that inside of it?

What you want to do is get the template into the auth server struct

https://github.com/rclone/rclone/blob/34333d9fa8cd0c8b9bd37fe853ccc3d319109e6b/lib/oauthutil/oauthutil.go#L723-L732

I'd read the global config variable in here and stick it in the struct

https://github.com/rclone/rclone/blob/34333d9fa8cd0c8b9bd37fe853ccc3d319109e6b/lib/oauthutil/oauthutil.go#L734-L741

You can then use it from the handler.

**Comment by animosity22** [comment]
Do you want to close this out and just work on the PR?

**Comment by ncw** [comment]
@animosity22 its good practice to have an issue for discussion before making a PR which @hwittenborn has done. When the PR is merged it will close the issue automatically.

I should probably have put the comment above on the PR though :-)

**Comment by animosity22** [comment]
@ncw  right but my reason for asking is the PR was already made so I thought this part of that process was 'done'.
