### ISSUE TITLE
Need Rclone support to stop temp files from uploading to remote

### ISSUE THREAD

**Issue by NavdeepAVV** [rclone/rclone#6744]
What is your rclone version (output from rclone version)
```
rclone v1.61.1
- os/version: Microsoft Windows 10 Enterprise 21H2 (64 bit)
- os/kernel: 10.0.19044.2486 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.19.4
- go/linking: static
- go/tags: cmount
```

Which cloud storage system are you using? (e.g. Google Drive)
`AWS`

The command you were trying to run (e.g. rclone copy /tmp remote:tmp)
`rclone mount`

What problem are you are trying to solve?
```
rclone should be able to exclude temp files from uploading to remote. Tried filter, but that doesnt stop files from uploading.
Is there any option/flag currently supported by rclone ?
```

**Comment by ncw** [comment]
If you are using `--vfs-cache-mode writes` or `full` then setting this

    --vfs-write-back duration            Time to writeback files after last use when using cache (default 5s)

To a large enough time is usually enough to stop temporary files being uploaded.

**Comment by animosity22** [comment]
Please use the forum for general questions as well.

https://forum.rclone.org
