### ISSUE TITLE
Parse stats "Elapsed Time" into days if longer than 24 hours

### ISSUE THREAD

**Issue by bFanek** [rclone/rclone#6748]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.61.1
- os/version: darwin 13.1 (64 bit)
- os/kernel: 22.2.0 (arm64)
- os/type: darwin
- os/arch: arm64
- go/version: go1.19.4
- go/linking: dynamic
- go/tags: cmount

#### What problem are you are trying to solve?
parse stats "Elapsed Time" into days if longer than 24 hours.
Elapsed time after 24h is currently printed in hours, example:
`Elapsed time:    71h0m0.3s`

#### How do you think rclone should be changed to solve that?
Parse Elapsed Time into days after 24 hours, example:
`Elapsed time:    2d23h0m0.3s`

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment]
Thank you, good suggestion - and easy to implement, so it is available in latest [beta](https://beta.rclone.org/?sort=time&order=desc), if you want to test it.

**Comment by bFanek** [comment]
Thank you for the very quick implementation for this, cheers!
