### ISSUE TITLE
Hard to justify behaviour of config file: delete and create new one instead of modifying.

### ISSUE THREAD

**Issue by thisismygitrepo** [rclone/rclone#6754]
I have moved `rclone` config file to a different location and made a symbolic link pointing to it from original location. However, I see that `rclone` deletes this symbolic link and create a `new` config file whenever I do any modifications like editing, adding or removing sources.

If possible, can we please have a more benign and expected behaviour like the file gets *modified* instead of deleted altogether and recreated?

Thank you.

**Comment by albertony** [comment]
Thank you for reporting. This is something that has been mentioned now and then, but couldn't find an existing issue for it. There is one *somewhat* related https://github.com/rclone/rclone/issues/3759, where we concluded documenting current behaviour would suffice (not done yet), but that would not help you much I assume..

**Comment by animosity22** [comment]
There's no reason to really create a symbolic link though. Just point the config to where you want it to.

As @albertony, I recall this a few times and @ncw has listed out a few reasons why in those issues but one solution / design definitely won't work for every scenario so I think it got left what works best for the majority of scenarios.

I use a custom config location and set that via an environment variable so it takes effect for all users.

```
felix@gemini:~$ env | grep CONF
RCLONE_CONFIG=/opt/rclone/rclone.conf
```

**Comment by ncw** [comment]
There is a good reason for the way rclone works at the moment. It is to do with leaving you a correct copy of the config file when things go wrong (eg when the disk gets full).

However, what rclone could do is detect if the config file is a symlink and then read the link and use that path as the path to the config file. That would work with rclone and have the nice properties we need and work around this issue too.

What do you think @thisismygitrepo ?

**Comment by mathematician001** [comment]
@ncw Given that this happens only **once** at config time, checking for symlink won't add overhead to runtime and is a reasonble compromise between current behaviour and expected one.

Although I can't pick anything wrong with @animosity22 approach of enviroment variables, I believe implementing @ncw 's suggestion adds more ease and service to the already slick config command.

**Comment by thisismygitrepo** [comment]
@ncw Given that this happens only once at config time, checking for symlink won't add overhead to runtime and is a reasonble compromise between current behaviour and expected one.

Although I can't pick anything wrong with @animosity22 approach of enviroment variables, I believe implementing @ncw 's suggestion adds more ease and service to the already slick config command.

**Comment by ncw** [comment]
@thisismygitrepo do you want to have go at doing this?

**Comment by thisismygitrepo** [comment]
@ncw I'd love to but I have never done Go in my career.
