### ISSUE TITLE
synology ds220j `/bin/rclone` cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by harusakura924** [rclone/rclone#6774]
## The associated forum post URL from `https://forum.rclone.org`

> I saw the following article, maybe it doesn't apply to me...
> https://github.com/ravem/synology-pcloud-and-rclone/blob/main/README.md

## What is the problem you are having with rclone?

> v1.61.1

## What is the problem you are having with rclone?

> Unable to execute with the following error:
> ash: /bin/rclone: cannot execute binary file: Exec format error

## What is your rclone version (since I can't execute only the installed version)

> v1.61.1
> \# curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
> \# ...
> \# cd rclone-v1.61.1-linux-amd64

## Which OS you are using and how many bits

> \# uname -a
> \# Linux MyName_Nas 4.4.180+ #42962 SMP Tue Oct 18 15:07:11 CST 2022 aarch64 GNU/Linux synology_rtd1296_ds220j

## Which cloud storage system are you using?

> pCloud

## The command you were trying to run

> \# rclone config
> -ash: /bin/rclone: cannot execute binary file: Exec format error

## Remark

I have read similar questions: https://github.com/rclone/rclone/issues/743

Provide the following relevant information:

Before using the following installation method, I originally planned to use the method described in https://github.com/ravem/synology-pcloud-and-rclone to install, but when the execution is sent to `./install.sh` There is no response (no output or error, just stuck there), I can only jump out and change the method, only to find the following installation method.

Refer to this URL to install: https://rclone.org/install/#linux
I use the root account from installation to operation.
Since the synology ds220j could not find the unzip installation, I decompressed it through win10 and uploaded it via SFTP.
The following MD5 was obtained in the synology ds220j, and the rest of the installation process was operated according to the above URL.
> \# md5sum rclone
> b1f63d4fe847d9f86b71e13859314ba8  rclone
> \# md5sum rclone-current-linux-amd64.zip
> 3d6893531ec9f2f1ed89ef9fe38dc468  rclone-current-linux-amd64.zip

**Comment by animosity22** [comment]
Would be a great forum post.

Your OS isn't AMD64 so grabbing the AMD64 binary won't work.

aarch64

I'd imagine you want the ARM 64 bit one:

https://rclone.org/downloads/
