### ISSUE TITLE
[REQUEST] progress less verbose

### ISSUE THREAD

**Issue by Lunatik00** [rclone/rclone#6781]
Hi, I have rclone v1.61.1, to my current knowledge the --progress/-P flag does show everything related to the progress, I usually have to use it to see how a very big amount of files are being transferred in parallel, that means I have more files being transferred than the lines I can see in my terminal, all I am interested in is the general progress, not the particular file progress, so, I would welcome a feature with the progress that only shows the general progress (the first few lines) and not the progress per file, it should be easy since it is showing less than what is being shown currently and it would help people that have to transfer many files.

I do it this way because is way faster for many small files, so the bottleneck is the transfer speed and not the time starting the transfer.

**Comment by animosity22** [comment]
Progress is supposed to be used for the terminal and not really for logging / output.

You'd probably want:

```
    --stats-one-line                       Make the stats fit on one line
```

**Comment by ncw** [comment]
I think that is the correct answer to this question, so I will close this issue.
