### ISSUE TITLE
YouTube as infinite storage unit.

### ISSUE THREAD

**Issue by its0x08** [rclone/rclone#6783]
I came across this [repo](https://github.com/DvorakDwarf/Infinite-Storage-Glitch) and thought it would be great to implement it here as well.
#### The associated forum post URL from `https://forum.rclone.org`

N/A

#### What is your current rclone version (output from `rclone version`)?
N/A

#### What problem are you are trying to solve?

Add YouTube as an infinite storage.

**Comment by ncw** [comment]
This seems very likely it is against YouTube's terms of service.

**Comment by animosity22** [comment]
Just a whee bit. Safe to close this out?

**Comment by ncw** [comment]
I don't think rclone should be encouraging this - sorry @its0x08 . If it doesn't violate YouTube's exact terms and conditions it certainly violates the spirit of them and we wish the rclone project to stay on the right side of the cloud providers it has integrations with.

I'm therefore going to close this.

**Comment by its0x08** [comment]
> This seems very likely it is against YouTube's terms of service.

Well on the project's readme it is mentioned that nowhere in TOS is mentioned that it is a violation!
