### ISSUE TITLE
InternetArchive - support listing the contents of user profiles and collections like folders

### ISSUE THREAD

**Issue by upintheairsheep** [rclone/rclone#6789]
#### The associated forum post URL from `https://forum.rclone.org`
N/A

#### What is your current rclone version (output from `rclone version`)?
rclone 1.61.1

#### What problem are you are trying to solve?
It would be useful to support the user profiles and collections from archive.org with each item being a directory, and the next page being it's own folder called _nextpage otherwise it would be enormous, and slow too.

#### How do you think rclone should be changed to solve that?
Add support for internet archive user profiles and collections to the HTTP backend.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Fancy submitting a PR for it?

**Comment by ncw** [comment]
@Lesmiscore what do you think about this request?

**Comment by upintheairsheep** [comment]
OK
