### ISSUE TITLE
rclone as development cloud provider

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#6790]
#### The associated forum post URL from `https://forum.rclone.org`
N/A

#### What is your current rclone version (output from `rclone version`)?
rclone 1.61.1

#### What problem are you are trying to solve?
Every time I need to submit a module on any programming language site, I must always register. For example, if I program in nodejs/javascript there is a site called npm - where javascript modules are managed and shared.

#### How do you think rclone should be changed to solve that?
One of the annoying problems with sites like npm, pypi etc - is that you have to login to them. But something annoying is that there is no way for me to sync some data.  My general idea would be if rclone could be an awesome tool where I can just access my development sites, module. I could do something like:

- pypi: `rclone lsd --http-url https://pypi.org/ :http:`
- npmjs: `rclone lsd --http-url https://www.npmjs.com/ :http:`
- unison: `rclone lsd --http-url https://share.unison-lang.org/ :http:`
- cpp: `rclone lsd --http-url https://conan.io/center/ :http:`
- cpp: `rclone lsd --http-url https://buckaroo.pm/ :http:`
- cpp: `rclone lsd --http-url https://www.npackd.org/ :http:`
- Kubernetes: `rclone lsd --http-url https://helm.sh/ :http:`

That way I download my modules and software independent of the programming language. And then I just send the update with rclone.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Those are all very non standard HTTP sites that don't scrape easily.

Rclone is generally for cloud remotes and not really for that use as that requires quite some parsing of all those sites.

```
rclone lsd --http-url https://pypi.org/ :http:
          -1 1969-12-31 19:00:00        -1 help
          -1 1969-12-31 19:00:00        -1 search
          -1 1969-12-31 19:00:00        -1 security
          -1 1969-12-31 19:00:00        -1 sitemap
          -1 1969-12-31 19:00:00        -1 sponsors
          -1 1969-12-31 19:00:00        -1 stats
          -1 1969-12-31 19:00:00        -1 trademarks
etexter@Earls-Mac-mini ~ %
```

That really doesn't give much out as an example.

While a neat idea, I doubt it'll get picked up as the backlog is already quite huge. If you'd like to submit a PR for it though, by all means, that's not an issue.
