### ISSUE TITLE
idp1 > idp2 > microsoft 365 sharepoint business

### ISSUE THREAD

**Issue by tooptoop4** [rclone/rclone#6794]
i think this is similar to https://forum.rclone.org/t/another-onedrive-university-account-problems/29931

using webdav and personal email everything works. but for generic accounts i get "wst:FailedAuthentication: Authentication Failure (AADSTS50126: Error validating credentials due to invalid username or password.)"

what i notice when going through chrome is that the generic accounts go through several auth prompts (but personal acct just one different one) with diff identity providers before successfully going to 365 sharepoint

**Comment by animosity22** [comment]
For general support, please use the forums for help.

Please fill out the help and support template completely.

https://forum.rclone.org
