### ISSUE TITLE
sharepoint/onedrive access without manual browser step

### ISSUE THREAD

**Issue by tooptoop4** [rclone/rclone#6796]
for programmatic user wonder if expected inputs can be supplied in .conf and then rclone internally does the http calls without needing human interaction?

i thought i could do a curl beforehand and get the token result into rclone.conf but seems the token returned by https://login.microsoftonline.com/redact/oauth2/v2.0/token or https://login.microsoftonline.com/redact/tokens/OAuth/2 with grant_type=client_credentials and clientid/secret is not liked by rclone "Either scp or roles claim need to be present in the token."

**Comment by animosity22** [comment]
For questions/discussion, please use the forums.

https://forum.rclone.org

**Comment by tooptoop4** [comment]
@animosity22 this is not support, but feature. I can do this functionality in java

**Comment by ncw** [comment]
> for programmatic user wonder if expected inputs can be supplied in .conf and then rclone internally does the http calls without needing human interaction?

Yes you can pass values when you create the config. If you do `rclone config` it tells you the names of the config parameters it is looking for for each question.



> i thought i could do a curl beforehand and get the token result into rclone.conf but seems the token returned by https://login.microsoftonline.com/redact/oauth2/v2.0/token or https://login.microsoftonline.com/redact/tokens/OAuth/2 with grant_type=client_credentials and clientid/secret is not liked by rclone "Either scp or roles claim need to be present in the token."

This should work in theory I think. I'm not sure what that error message means though. Have you passed the clientid/secret to rclone? Have you used the same scopes that rclone normally uses?

**Comment by tooptoop4** [comment]
@ncw rclone is stumbling on this step:
```
2023/03/02 22:58:35 DEBUG : GET /v1.0/drives/redact/root HTTP/1.1
Host: graph.microsoft.com
2023/03/02 22:58:35 DEBUG : HTTP/1.1 401 Unauthorized
```

whereas my java app doesn't need to interact with graph.microsoft.com at all (i confirmed we are not authorized to use it too)
the java app uses API calls like ```https://redact.sharepoint.com/_api/web/GetFileByServerRelativeUrl('/sites/redact/Shared%20Documents/{filepath}')/$value```

**Comment by ncw** [comment]
I don't know how you can do any stuff with onedrive/sharepoint without using `graph.microsoft.com`?

**Comment by Cnly** [comment]
@tooptoop4 rclone interacts with SharePoint sites using the Graph API, which is also the recommended method (https://learn.microsoft.com/en-us/sharepoint/dev/apis/sharepoint-rest-graph). Maybe you could check the following:

> Have you passed the clientid/secret to rclone? Have you used the same scopes that rclone normally uses?

Or maybe you can see if this SO question solves your problem: https://stackoverflow.com/questions/35839675/graph-api-either-scp-or-roles-claim-need-to-be-present-in-the-token

**Comment by tooptoop4** [comment]
graph api is locked down in our org

**Comment by Cnly** [comment]
@tooptoop4 so if I understand correctly, you want rclone to use an externally obtained auth token? If you're following the same steps in rclone's code, I don't see how that shouldn't work. Could you reply to our questions earlier?

**Comment by tooptoop4** [comment]
I will stick with java 😄
