### ISSUE TITLE
seafile: flaky renew token test

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#6799]
Occasionally we are seeing a test failure in the seafile backend `renew_test.go`.

https://github.com/rclone/rclone/actions/runs/4305684219/jobs/7508475384

```
panic: sync: negative WaitGroup counter

goroutine 38 [running]:
sync.(*WaitGroup).Add(0xc000332d70?, 0x0?)
	/Users/runner/hostedtoolcache/go/1.20.1/x64/src/sync/waitgroup.go:62 +0xe5
sync.(*WaitGroup).Done(...)
	/Users/runner/hostedtoolcache/go/1.20.1/x64/src/sync/waitgroup.go:87
github.com/rclone/rclone/backend/seafile.TestRenewal.func1()
	/Users/runner/work/rclone/rclone/backend/seafile/renew_test.go:27 +0x33
github.com/rclone/rclone/backend/seafile.(*Renew).renewOnExpiry(0xc00031a440)
	/Users/runner/work/rclone/rclone/backend/seafile/renew.go:36 +0x7e
created by github.com/rclone/rclone/backend/seafile.NewRenew
	/Users/runner/work/rclone/rclone/backend/seafile/renew.go:28 +0x116
FAIL	github.com/rclone/rclone/backend/seafile	0.245s
```

Have you got time to look at this @creativeprojects as I think it is in the code you did recently.

Thank you :-)

**Comment by creativeprojects** [comment]
That's right, there's a race condition where a third renewal can happen between `Wait` and `Shutdown`. I thought it was possible to happen but I never managed to trigger it locally.

I'll change for a time based test, which reflects the reality better anyway 👍🏻
