### ISSUE TITLE
"Failed to copy: can't upload files here" on new google photos share

### ISSUE THREAD

**Issue by pitsi** [rclone/rclone#6802]
#### The associated forum post URL from `https://forum.rclone.org`
(none, not registered in the forum)

#### What is the problem you are having with rclone?
I made a new remote earlier so as to upload a friend's photos to his google photos account. Because I have backed up her photos on my raspberry, which has no ui and thus no web browser, I had to answer no at the relevant step and get the key from my desktop. After that, I allowed write access to rclone as asked from the page, I verified that everything was ok on the raspberry and the new remote was successfully added to rclone's config file (I also have another gdrive remote in there and they look similar, so I assume its syntax is correct).

However, when trying to upload the photos I get errors identical to this, for all the files
`2023/03/03 10:15:24 ERROR : IMG_20230116_192315.jpg: Failed to copy: can't upload files here`

Because the files are hundreds and the log that is requested later in the report is huge in size, the error for the example below is done with one file only which is just placed to the root of the remote.

#### What is your rclone version (output from `rclone version`)
On the desktop
```
$ rclone version
rclone v1.61.1
- os/version: debian bookworm/sid (64 bit)
- os/kernel: 6.1.0-5-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.4
- go/linking: static
- go/tags: none
```
On the rpi
```
$ rclone version
rclone v1.61.1
- os/version: debian 11.6 (64 bit)
- os/kernel: 5.10.0-21-arm64 (aarch64)
- os/type: linux
- os/arch: arm64
- go/version: go1.19.4
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
As seen above, it's debian testing/unstable x64 on the desktop and debian 11 stable arm64 on the raspberry.

#### Which cloud storage system are you using? (e.g. Google Drive)
Google photos.

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone copy tablet/DCIM/Camera/IMG_20230116_192315.jpg gogo:/`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
$ rclone copy tablet/DCIM/Camera/IMG_20230116_192315.jpg gogo:/ -vv
2023/03/03 10:15:24 DEBUG : rclone: Version "v1.61.1" starting with parameters ["rclone" "copy" "tablet/DCIM/Camera/IMG_20230116_192315.jpg" "gogo:/" "-vv"]
2023/03/03 10:15:24 DEBUG : Creating backend with remote "tablet/DCIM/Camera/IMG_20230116_192315.jpg"
2023/03/03 10:15:24 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2023/03/03 10:15:24 DEBUG : fs cache: adding new entry for parent of "tablet/DCIM/Camera/IMG_20230116_192315.jpg", "/home/user/gogo/tablet/DCIM/Camera"
2023/03/03 10:15:24 DEBUG : Creating backend with remote "gogo:/"
2023/03/03 10:15:24 DEBUG : fs cache: renaming cache item "gogo:/" to be canonical "gogo:"
2023/03/03 10:15:24 DEBUG : Google Photos path "": NewObject: remote="IMG_20230116_192315.jpg"
2023/03/03 10:15:24 DEBUG : Google Photos path "": >NewObject:
2023/03/03 10:15:24 DEBUG : IMG_20230116_192315.jpg: Need to transfer - File not found at Destination
2023/03/03 10:15:24 DEBUG : Google Photos path "": Put: src=IMG_20230116_192315.jpg
2023/03/03 10:15:24 DEBUG : IMG_20230116_192315.jpg: Update: src=IMG_20230116_192315.jpg
2023/03/03 10:15:24 DEBUG : IMG_20230116_192315.jpg: >Update: err=can't upload files here
2023/03/03 10:15:24 DEBUG : Google Photos path "": >Put:
2023/03/03 10:15:24 ERROR : IMG_20230116_192315.jpg: Failed to copy: can't upload files here
2023/03/03 10:15:24 ERROR : Attempt 1/3 failed with 1 errors and: can't upload files here
2023/03/03 10:15:24 DEBUG : Google Photos path "": NewObject: remote="IMG_20230116_192315.jpg"
2023/03/03 10:15:24 DEBUG : Google Photos path "": >NewObject:
2023/03/03 10:15:24 DEBUG : IMG_20230116_192315.jpg: Need to transfer - File not found at Destination
2023/03/03 10:15:24 DEBUG : Google Photos path "": Put: src=IMG_20230116_192315.jpg
2023/03/03 10:15:24 DEBUG : IMG_20230116_192315.jpg: Update: src=IMG_20230116_192315.jpg
2023/03/03 10:15:24 DEBUG : IMG_20230116_192315.jpg: >Update: err=can't upload files here
2023/03/03 10:15:24 DEBUG : Google Photos path "": >Put:
2023/03/03 10:15:24 ERROR : IMG_20230116_192315.jpg: Failed to copy: can't upload files here
2023/03/03 10:15:24 ERROR : Attempt 2/3 failed with 1 errors and: can't upload files here
2023/03/03 10:15:24 DEBUG : Google Photos path "": NewObject: remote="IMG_20230116_192315.jpg"
2023/03/03 10:15:24 DEBUG : Google Photos path "": >NewObject:
2023/03/03 10:15:24 DEBUG : IMG_20230116_192315.jpg: Need to transfer - File not found at Destination
2023/03/03 10:15:24 DEBUG : Google Photos path "": Put: src=IMG_20230116_192315.jpg
2023/03/03 10:15:24 DEBUG : IMG_20230116_192315.jpg: Update: src=IMG_20230116_192315.jpg
2023/03/03 10:15:24 DEBUG : IMG_20230116_192315.jpg: >Update: err=can't upload files here
2023/03/03 10:15:24 DEBUG : Google Photos path "": >Put:
2023/03/03 10:15:24 ERROR : IMG_20230116_192315.jpg: Failed to copy: can't upload files here
2023/03/03 10:15:24 ERROR : Attempt 3/3 failed with 1 errors and: can't upload files here
2023/03/03 10:15:24 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         0.1s

2023/03/03 10:15:24 DEBUG : 3 go routines active
2023/03/03 10:15:24 Failed to copy: can't upload files here
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by pitsi** [comment]
The same thing happens for simpler tasks like creating a folder, e.g.
```
$ rclone mkdir gogo:/tablet -vv
2023/03/03 12:50:34 DEBUG : rclone: Version "v1.61.1" starting with parameters ["rclone" "mkdir" "gogo:/tablet" "-vv"]
2023/03/03 12:50:34 DEBUG : Creating backend with remote "gogo:/tablet"
2023/03/03 12:50:34 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2023/03/03 12:50:34 DEBUG : fs cache: renaming cache item "gogo:/tablet" to be canonical "gogo:tablet"
2023/03/03 12:50:34 DEBUG : Google Photos path "tablet": Making directory
2023/03/03 12:50:34 DEBUG : Google Photos path "tablet": Mkdir: dir=""
2023/03/03 12:50:34 DEBUG : Google Photos path "tablet": >Mkdir: err=directory not found
2023/03/03 12:50:34 ERROR : Attempt 1/3 failed with 1 errors and: directory not found
2023/03/03 12:50:34 DEBUG : Google Photos path "tablet": Making directory
2023/03/03 12:50:34 DEBUG : Google Photos path "tablet": Mkdir: dir=""
2023/03/03 12:50:34 DEBUG : Google Photos path "tablet": >Mkdir: err=directory not found
2023/03/03 12:50:34 ERROR : Attempt 2/3 failed with 1 errors and: directory not found
2023/03/03 12:50:34 DEBUG : Google Photos path "tablet": Making directory
2023/03/03 12:50:34 DEBUG : Google Photos path "tablet": Mkdir: dir=""
2023/03/03 12:50:34 DEBUG : Google Photos path "tablet": >Mkdir: err=directory not found
2023/03/03 12:50:34 ERROR : Attempt 3/3 failed with 1 errors and: directory not found
2023/03/03 12:50:34 DEBUG : 2 go routines active
2023/03/03 12:50:34 Failed to mkdir: directory not found
```
or via the web interface.

**Comment by ncw** [comment]
Checkout this bit of the docs - it explains which part of the google photos tree are writable

https://rclone.org/googlephotos/#layout

**Comment by pitsi** [comment]
You are right, creating the folder inside the album (and not albumS) subfolder made rclone work like it should. I have started the transfer and, due to my slow connection, it will complete in ~6 hours from now.
However, I got an error fro a single file that looks like so
`(timestamp here) ERROR: some/random/file.jpg: Failed to copy: upload failed: Failed:There was an error while trying to create this media item (3).
and a couple of lines below it
`Errors     1 (retrying may help)`
I will retry it after it is done (or probably tomorrow morning), but how do I retry it?

**Comment by animosity22** [comment]
That's why we ask to use the forums as general support is much easier there..

We try to use Github for bugs/features.

**Comment by pitsi** [comment]
Closing as fixed. The file in question above was corrupted and that is the reason it could not be uploaded.
Now I have to tell the user to stop deleting what was uploaded until everything is completed, because rclone just reuploads deleted files since yesterday :p

As for the forums, although I appreciate the supoort provided by them, I do not create user accounts here and there unless I absolutely have to. The core reason is that I have come accross forums that have pathetic moderation and some do not allow a user to delete his account by himself.
