### ISSUE TITLE
GDrive Error 403 but should be successful

### ISSUE THREAD

**Issue by aselafernando** [rclone/rclone#6805]
#### The associated forum post URL from `https://forum.rclone.org`
Not posted on forum

#### What is the problem you are having with rclone?
This is not a post about getting around gdrive limits.

I call the rclone move command, to move a folder (which contains only one 59.8GB file) into the gdrive. The google drive upload quota is reached at some point during the transfer. The transfer doesn't error at this point which is fine. This is the expected behavior  documented at [google](https://support.google.com/a/users/answer/7338880?hl=en#:~:text=Individual%20users%20can%20only%20upload,or%20synchronize%20is%205%20TB.). It states uploads in progress when the quota is reached will continue to progress.

The issue is when the upload finishes, rclone will still mark it as failed despite it uploading successfully if the quota is hit mid transfer.

#### What is your rclone version (output from `rclone version`)
rclone v1.61.1
- os/version: debian 11.6 (64 bit)
- os/kernel: 5.10.0-19-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.4
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Debian 11 x64

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```rclone move /mnt/data/local/ gdrive_enc: -P --checkers 5 --log-file=/tmp/upload.log -v --tpslimit 5 --rc --rc-web-gui --rc-user=rclone --rc-pass=XXXX --rc-addr=0.0.0.0:5572 --rc-web-gui-no-open-browser --bwlimit=13M --transfers=1 --drive-chunk-size 128M --exclude-from rclone_exclusions.txt --delete-empty-src-dirs --drive-stop-on-upload-limit --error-on-no-transfer```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
I haven't had a chance to re-run rclone with the -vv flag, waiting for the quota to reinstate.

```
2023/03/04 14:23:21 INFO  : Starting bandwidth limiter at 13Mi Byte/s
2023/03/04 14:23:21 INFO  : Starting transaction limiter: max 5 transactions/s with burst 1
2023/03/04 14:23:21 NOTICE: Web GUI exists. Update skipped.
2023/03/04 14:23:21 NOTICE: Serving Web GUI
2023/03/04 14:23:21 INFO  : Using --user rclone --pass XXXX as authenticated user
2023/03/04 14:23:21 NOTICE: Serving remote control on http://[::]:5572/
2023/03/04 14:23:21 NOTICE: Web GUI is not automatically opening browser. Navigate to http://rclone:rclone@[::]:5572/?login_token=XXXX to use.
2023/03/04 15:42:19 ERROR : Google drive root 'X': Received upload limit error: googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded
2023/03/04 15:42:19 ERROR : file.mkv: Failed to copy: googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded
2023/03/04 15:42:19 ERROR : file.mkv: Not deleting source as copy failed: googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded
2023/03/04 15:42:19 ERROR : Cancelling sync due to fatal error: googleapi: Error 403: User rate limit exceeded., userRateLimitExceeded
2023/03/04 15:42:19 ERROR : Local file system at /mnt/data/local: not deleting directories as there were IO errors
2023/03/04 15:42:19 ERROR : Fatal error received - not attempting retries
2023/03/04 15:42:19 INFO  :
Transferred:       59.808 GiB / 59.808 GiB, 100%, 12.863 MiB/s, ETA 0s
Errors:                 1 (fatal error encountered)
Checks:                 2 / 2, 100%
Elapsed time:   1h18m58.1s
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
If you'd like to use the forums and post / use the help support template, that would be superb. Debug log is key :)

https://forum.rclone.org
