### ISSUE TITLE
mount failed on macOS, cgofuse: cannot find FUSE

### ISSUE THREAD

**Issue by KonpakuSyl** [rclone/rclone#6807]
#### What is the problem you are having with rclone?

mount failed on macOS, cgofuse: cannot find FUSE

#### What is your rclone version (output from `rclone version`)

rclone v1.61.1
- os/version: darwin 13.1 (64 bit)
- os/kernel: 22.2.0 (arm64)
- os/type: darwin
- os/arch: arm64
- go/version: go1.19.4
- go/linking: dynamic
- go/tags: cmount

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

macOS 13.1 (22C65) ,arm64

#### Which cloud storage system are you using? (e.g. Google Drive)

OneDrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone mount onedrive:/moive moive --allow-non-empty --umask 000 --allow-other --attr-timeout 10m --vfs-cache-max-age 1m --vfs-read-chunk-size-limit 100M --vfs-cache-max-size 10G --vfs-cache-mode full -vv

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

rclone mount onedrive:/moive moive --allow-non-empty --umask 000 --allow-other --attr-timeout 10m --vfs-cache-max-age 1m --vfs-read-chunk-size-limit 100M --vfs-cache-max-size 10G --vfs-cache-mode full -vv

2023/03/05 02:07:31 DEBUG : Creating backend with remote "onedrive:/moive"
2023/03/05 02:07:31 DEBUG : Using config file from "/Users/xx/.config/rclone/rclone.conf"
2023/03/05 02:07:37 DEBUG : fs cache: renaming cache item "onedrive:/moive" to be canonical "onedrive:moive"
2023/03/05 02:07:38 DEBUG : OneDrive root 'moive': Next delta token is: aTE09NjM4MTM1NDkzNTM4ODc7SUQ9M0RCQjI5MkUyN0E5OEEyQSEzNTI7TFI9NjM4MTM1NTAwNTgyOTA7RVA9MjA7U
2023/03/05 02:07:38 DEBUG : vfs cache: root is "/Users/xx/Library/Caches/rclone"
2023/03/05 02:07:38 DEBUG : vfs cache: data root is "/Users/xx/Library/Caches/rclone/vfs/onedrive/moive"
2023/03/05 02:07:38 DEBUG : vfs cache: metadata root is "/Users/xx/Library/Caches/rclone/vfsMeta/onedrive/moive"
2023/03/05 02:07:38 DEBUG : Creating backend with remote "/Users/xx/Library/Caches/rclone/vfs/onedrive/moive"
2023/03/05 02:07:38 DEBUG : Creating backend with remote "/Users/xx/Library/Caches/rclone/vfsMeta/onedrive/moive"
2023/03/05 02:07:38 DEBUG : Mounting on "moive" ("onedrive moive")
2023/03/05 02:07:38 DEBUG : Adding "-o modules=iconv,from_code=UTF-8,to_code=UTF-8-MAC" for macOS
2023/03/05 02:07:38 INFO  : vfs cache: cleaned: objects 0 (was 0) in use 0, to upload 0, uploading 0, total size 0 (was 0)
2023/03/05 02:07:38 DEBUG : OneDrive root 'moive': Mounting with options: ["-o" "attr_timeout=600" "-o" "fsname=onedrive:moive" "-o" "subtype=rclone" "-o" "max_readahead=131072" "-o" "atomic_o_trunc" "-o" "daemon_timeout=600" "-o" "nonempty" "-o" "allow_other" "-o" "volname=onedrive moive" "-o" "noappledouble" "-o" "modules=iconv,from_code=UTF-8,to_code=UTF-8-MAC"]
2023/03/05 02:07:38 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find FUSE

**Comment by animosity22** [comment]
For mounts, you need to install fuse:

https://osxfuse.github.io/

**Comment by KonpakuSyl** [comment]
> For mounts, you need to install fuse:
> 
> https://osxfuse.github.io/

Thank you, it worked.

**Comment by ncw** [comment]
@damoclark the paths rclone looks for the macFUSE library are here

https://github.com/winfsp/cgofuse/blob/f87f5db493b56c5f4ebe482a1b7d02c7e5d572fa/fuse/host_cgo.go#L172-L176

```c
	h = dlopen("/usr/local/lib/libfuse.2.dylib", RTLD_NOW); // MacFUSE/OSXFuse >= v4
	if (0 == h)
		h = dlopen("/usr/local/lib/libosxfuse.2.dylib", RTLD_NOW); // MacFUSE/OSXFuse < v4
	if (0 == h)
		h = dlopen("/usr/local/lib/libfuse-t.dylib", RTLD_NOW); // FUSE-T
```

**Comment by damoclark** [comment]
Thanks @ncw 

The following solution has rclone working for me on macOS 12 using macfuse from macports.

```bash
sudo mkdir /usr/local/lib
cd /usr/local/lib
sudo ln -s /opt/local/lib/libfuse.2.dylib 
```

There is no libfuse-t.dylib in the macports version of macfuse, but it doesn't seem to matter.

Just sharing back for others who stumble into this.

Cheers,
Damo.

**Comment by ncw** [comment]
@damoclark is this worth putting in the docs? If so you might suggest an edit here

https://github.com/rclone/rclone/blob/99dd748fec0ab38919e7ffb209b1045612516f2f/cmd/mountlib/help.go#L257

You can suggest an edit by clicking the pencil icon, or send a PR in the usual way if you prefer :-)
