### ISSUE TITLE
Would You Like Upload Your File To https://pc.woozooo.com/ ?

### ISSUE THREAD

**Issue by wonchong** [rclone/rclone#6815]
It is hard to download from your website
![123](https://user-images.githubusercontent.com/82252714/223349537-8b8412e8-dda2-4ff9-9413-53218e9db310.jpg)
We can get "70MB/S" Speed Via https://pc.woozooo.com/

**Comment by ncw** [comment]
> It is hard to download from your website

You can download rclone from https://downloads.rclone.org or from https://github.com/rclone/rclone/releases/latest - are these difficult to access for you?

**Comment by animosity22** [comment]
This really isn't a bug / feature / etc. Closing out as it's answered.

Please use the forums for questions and not the github please.

https://forum.rclone.org
