### ISSUE TITLE
null response for /operations/stat api when directory has trailing slash

### ISSUE THREAD

**Issue by hegdemahendra** [rclone/rclone#6817]
Hello Team,

First of all thanks for the wonderful tool.

I am using rclone in rc mode from few months and having great experience.

While using recently it recently found one use case where the behavior of api could have been better I felt , so raising this to provide more info.

When I am using  "/operations/stat" api with cloud remote (adls/aws) found that trailing slash(/) in directory path gives below response :

Request -
```
{
	"fs": "appsettingchanges_6019_ADLS_82c880d2_bb71_45d1_96be_08db1bc37687:",
	"remote": "o9datalake/Folder1/"
}
```
Response - 200
Response body -
```
{
	"item": null
}
```

The response could be something other than null and also when I use trailing slash with data copy api (/sync/copy) it works witout any error and able to copy/sync data.

Same above issue discussed here in this in details-
https://forum.rclone.org/t/rcd-operations-stat-is-not-as-expected-with-azure-adls-directory/36502

Thanks,
Mahendra

**Comment by ncw** [comment]
This is easy to verify - with slash `null` return

```
$ rclone rc --loopback operations/stat fs=TestAzureBlob: remote=rclone/rclone1test/
{
	"item": null
}
```

vs with no slash - useful info.

```
$ rclone rc --loopback operations/stat fs=TestAzureBlob: remote=rclone/rclone1test
{
	"item": {
		"IsDir": true,
		"MimeType": "inode/directory",
		"ModTime": "2023-03-07T17:35:30.216221163Z",
		"Name": "rclone1test",
		"Path": "rclone/rclone1test",
		"Size": -1
	}
}
```

S3 gives the same results and so does the local disk.

So this is looking very much like a bug.

I managed to fix it I think - can you give this a go please?

[v1.62.0-beta.6784.115afadd3.fix-6817-stat](https://beta.rclone.org/branch/fix-6817-stat/v1.62.0-beta.6784.115afadd3.fix-6817-stat/) on branch [fix-6817-stat](https://github.com/rclone/rclone/tree/fix-6817-stat) (uploaded in 15-30 mins)
