### ISSUE TITLE
webdav: support FastMail Files

### ISSUE THREAD

**Issue by Arnavion** [rclone/rclone#6837]
#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.61.1-DEV
- os/version: opensuse-tumbleweed (64 bit)
- os/kernel: 6.2.1-1-default (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.4
- go/linking: dynamic
- go/tags: none
```

#### What problem are you are trying to solve?

[FastMail Files](https://www.fastmail.help/hc/en-us/articles/1500000280121-About-Fastmail-file-storage) is a WebDAV implementation that supports SHA1 hashes, but in a different way than the current OwnCloud / NextCloud implementation.

Example PROPFIND response:

```xml
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:D="DAV:">
  <D:response>
    <D:href>/example.org/filename</D:href>
    <D:propstat>
      <D:prop>
        <sha1hex xmlns="ME:">86d6c70cfbef2b84394a1c59b23915d40888ebcc</sha1hex>
        <D:getcontentlength>999936</D:getcontentlength>
        <D:quota-available-bytes>7639552</D:quota-available-bytes>
        <D:displayname>filename</D:displayname>
        <D:lockdiscovery/>
        <D:supportedlock>
          <D:lockentry>
            <D:lockscope>
              <D:shared/>
            </D:lockscope>
            <D:locktype>
              <D:write/>
            </D:locktype>
          </D:lockentry>
          <D:lockentry>
            <D:lockscope>
              <D:exclusive/>
            </D:lockscope>
            <D:locktype>
              <D:write/>
            </D:locktype>
          </D:lockentry>
        </D:supportedlock>
        <D:getlastmodified>Sun, 12 Mar 2023 08:11:54 GMT</D:getlastmodified>
        <D:creationdate>2023-03-12T08:11:54Z</D:creationdate>
        <D:getcontenttype>application/octet-stream</D:getcontenttype>
        <D:getetag>a7cc87894e5f0929006f8caf7b18c6f81a5102bd</D:getetag>
        <D:quota-used-bytes>9992360448</D:quota-used-bytes>
        <D:resourcetype/>
      </D:prop>
      <D:status>HTTP/1.1 200 OK</D:status>
    </D:propstat>
  </D:response>
```

Note the `ME:sha1hex` prop. The value is indeed the `sha1sum` of the file.

#### How do you think rclone should be changed to solve that?

It would be nice to implement a new `vendor = fastmail` with support for this kind of SHA1 hash, so that syncing can use the SHA1 instead of relying on mtime. I cannot find any documentation about this property, so I assume it's specific to FastMail's server ("ME" might be "Messaging Engine", another name that FastMail uses for its domains etc). So `vendor = fastmail` should be appropriate.

FastMail also supports the `x-oc-mtime` header and uses it to set the mtime. The `PUT` response contains a `x-oc-mtime: accepted` header if the request set it. So the `useOCMtime` quirk should be set to `true` for it.

FastMail does *not* support the `oc-checksum` header in either of the two ways that [this comment](https://github.com/rclone/rclone/blob/e405ca7733b19b9430afc344324eee3b608c1466/backend/webdav/webdav.go#L1323-L1325) talks about. Specifically, the response contains the `ME:sha1hex` prop regardless of whether the client sends the header or not (ie it doesn't have the NextCloud behavior of using the client-provided value), and the server accepts the `PUT` request even if the client sends an incorrect hash (ie it doesn't have the OwnCloud behavior of using the client-provided value to validate the request body).

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.63 - thank you @Arnavion
