### ISSUE TITLE
VolumeDriver.Mount: error al montar FUSE fs: fusermount: exec: "fusermount3": archivo ejecutable no encontrado en $PATH

### ISSUE THREAD

**Issue by Cr2649** [rclone/rclone#6864]
ERROR: Fatal error: failed to mount FUSE fs: fusermount: exec: "fusermount3": executable file not found in $PATH
 OPERATING SYSTEM: UBUNTU 18.0.4

I manage to connect the rclone with the drive, once I create the mkdir /home/folder

and use: rclone mount --allow-other --allow-non-empty -v VOD: /home/VOD & to end the connection to the main xtream server ui throws the error: Fatal error: fail to mount FUSE fs: fusermount: exec: "fusermount3": executable file not found in $PATH
 OPERATING SYSTEM: UBUNTU 18.0.4

the fuse3 is not available to install on Ubuntu 18.04 and there is no output now to connect the unit to the main xtream ui server

**Comment by animosity22** [comment]
You need fuse3 installed.

**Comment by Cr2649** [comment]
> 
my friend fuse3 not avalaible for ubuntu 18.04

**Comment by animosity22** [comment]
It is.

You have to search around get it installed as 18.04 goes EOL in April 2023 anyway so may as well upgrade.

Good luck my friend!

**Comment by Cr2649** [comment]
Friend I don't have much knowledge of these issues, what will happen with the xtream ui iptv services now that 18.04 expires

**Comment by animosity22** [comment]
Sorry as I have no idea on what that is.

The goal would be either to upgrade your OS or figure out how to get fuse3 installed on a legacy OS. 

It's beyond anything on rclone.
