### ISSUE TITLE
docker rclone plugin cannot see free space on upstream local.

### ISSUE THREAD

**Issue by bugiii** [rclone/rclone#6869]
```
$ rclone version
rclone v1.62.2
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-1030-oracle (aarch64)
- os/type: linux
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.20.2
- go/linking: static
- go/tags: none

$ docker plugin ls
id name description enabled
54dd3232a50e rclone:latest Rclone volume plugin for Docker true

$ docker version
Client: Docker Engine - Community
 Version: 23.0.1
 API version: 1.42
 Go version: go1.19.5
 Git commit: a5ee5b1
 Built: Thu Feb 9 19:46:30 2023
 OS/Arch: linux/arm64
 Context: default

Server: Docker Engine - Community
 Engine:
  Version: 23.0.1
  API version: 1.42 (minimum version 1.12)
  Go version: go1.19.5
  Git commit: bc3805a
  Built: Thu Feb 9 19:46:30 2023
  OS/Arch: linux/arm64
  Experimental: false
 containerd:
  Version: 1.6.18
  GitCommit: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version: 1.1.4
  GitCommit: v1.1.4-0-g5fd4c4d
 docker-init:
  Version: 0.19.0
  GitCommit: de40ad0

$ docker-compose version
Docker Compose version v2.16.0

```
I am running an nfs server on each of the four servers, called B, C, D, and E, and exporting it to be mounted on server A for use.

I have mounted them as /mnt/nfs/b1, /mnt/nfs/c1, etc. on A server and I am using them well as a union as shown in the rclone.conf below.

```
[root]
type = union
upstreams = B1:__root__ C1:__root__ D1:__root__ E1:__root__
create_policy = mfs
[B1]
type = alias
remote = /mnt/nfs/b1
[C1]
type = alias
remote = /mnt/nfs/c1
[D1]
type = alias
remote = /mnt/nfs/d1
[E1]
type = alias
remote = /mnt/nfs/e1
```

```
$ rclone touch root:test.txt
$ rclone ls root:
        0 test.txt
$ rclone about B1:
Total: 193.629 GiB
Used: 2.215 GiB
Free: 191.398 GiB
$ rclone about root:
Total: 774.516 GiB
Used: 8.980 GiB
Free: 765.473 GiB
```

I had to use an alias to get the about command to display usage properly. Using this, I mounted docker-compose with the rclone plugin, but it is not uploading to the actual nfs directory with the following message.

```
$ cat < /run/docker/plugins/54...9be/init-stderr
...
2023/03/20 03:43:27 INFO  : vfs cache: cleaned: objects 0 (was 0) in use 0, to upload 0, uploading 0, total size 0 (was 0)
2023/03/20 03:43:39 INFO  : test.xlsx.ocTransferId1907536130.part: vfs cache: queuing for upload in 5s
2023/03/20 03:43:39 INFO  : test.xlsx.ocTransferId1907536130.part: vfs cache: renamed in cache to "test.xlsx"
2023/03/20 03:43:44 NOTICE: Free Space is not supported for upstream local, treating as infinite # <---
2023/03/20 03:43:44 NOTICE: Free Space is not supported for upstream local, treating as infinite # <---
2023/03/20 03:43:44 NOTICE: Free Space is not supported for upstream local, treating as infinite # <---
2023/03/20 03:43:44 INFO  : test.xlsx: Copied (new)
2023/03/20 03:43:44 INFO  : test.xlsx: vfs cache: upload succeeded try #1
2023/03/20 03:45:26 INFO  : test1.xlsx.ocTransferId2023620018.part: vfs cache: queuing for upload in 5s
2023/03/20 03:45:26 INFO  : test1.xlsx.ocTransferId2023620018.part: vfs cache: renamed in cache to "test1.xlsx"
2023/03/20 03:45:27 INFO  : vfs cache: cleaned: objects 2 (was 2) in use 1, to upload 1, uploading 0, total size 24.523Ki (was 24.523Ki)
...
```

```
services:
  ...
    volumes:
      - rclone-root:/data/root/
volumes:
  rclone-root:
    driver: rclone
    driver_opts:
      remote: 'root:'
      allow_other: 'true'
      poll_interval: '15s'
      vfs_cache-mode: 'full'
```

I don't know if it's because the rclone about logic you run on the command line and the about used inside the rclone plugin behave differently. Please check this issue.

**Comment by ncw** [comment]
> 2023/03/20 03:43:44 NOTICE: Free Space is not supported for upstream local, treating as infinite # <---

This message is from the union backend.

Do the paths `/mnt/nfs/b1` still work in the context of the docker plugin? That would be my guess as to what is going on.

**Comment by ncw** [comment]
> Is this a result of the change to fuse3?

I don't think so. That change is mostly about keeping up with new kernel interfaces provided by linux.

You could try an older version of rclone 1.61.1 say and see if it works - that would eliminate the fuse2/fuse3 changes.

**Comment by bugiii** [comment]
> You could try an older version of rclone 1.61.1 say and see if it works - that would eliminate the fuse2/fuse3 changes.


```
$ rclone version
rclone v1.61.1
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-1030-oracle (aarch64)
- os/type: linux
- os/arch: arm64
- go/version: go1.19.4
- go/linking: static
- go/tags: none
$ docker plugin inspect rclone:latest | grep PluginReference
        "PluginReference": "docker.io/rclone/docker-volume-rclone:arm64-1.61.1",
```

I tried again with version 1.61.1, but the result is the same.

Here is the current situation again The files seem to be going up to the VFS cache. Meanwhile, when I look at CPU utilization with TOP, rclone is showing high utilization. However, when I look at the network traffic with bmon, it doesn't appear to be transferring at all.

Maybe I'm misunderstanding something or configuring something wrong. Can anyone confirm that the rclone volume plugin is currently enabled with docker-compose?

**Comment by ncw** [comment]
> The problem seems to be when it's local storage.

This is very likely a permissions problem. Docker doesn't get permission to look at your local files unless you give it. I don't use docker compose so can't help more than that.

**Comment by bugiii** [comment]
> Docker doesn't get permission to look at your local files unless you give it.

I think your words have given me a clue. I've tried several methods and here's what I'm thinking

I think it's because docker-compose can't see the host's local storage directly. I could probably do a mapping to volumes, but I don't have the time, and even if I did, it would be complicated.

I solved it by pre-mounting it on the host before docker-compose is up.

I really appreciate your hint.

**Comment by ncw** [comment]
Thanks for the write up.

Docker is very strict on host access - this is a good thing to keep the security of the container, but it makes rclone mounts hard work sometimes! Almost all the docker queries are about something like this :-)

I'll close this now.

**Comment by mikklfr** [comment]
Hello to all of you, 👋

I was following this thread, since I have a similar issue.

Here are my configuration details:
- onedrive : standard onedrive connection
- onedrive-crypt : the same onedrive as before but with a encrypted layer
- usb: a local mount that refers to mounted storage (/media/usb for instance)
- combined: a combine configuration that exposes both onedrive-crypt and localfolders

Outside docker all commands such as ```rclone lsd combined:usb``` and ```rclone lsd combined:onedrive``` works just fine.

Inside docker: Only the onedrive and onedrive-crypt folders are accessible. Any thing using local engine is not returning data.

**It makes the volume driver not usuable for mounts referring with local engine ☠️** 

Maybe update the documentation to reflect that limitation and/or provide a sample configuration to bypass that limitation?
@ncw 

Here is my current workaround: `rclone mount` running in systemd + docker bind shared mounts... (Volume was not resilient between mount and unmounts)

Here is some docker-compose code of the mount since documentation is hard to find out in that format 🎁
```
volumes:
  storage:
    driver: local
    driver_opts:
      type: none
      device: /storage
      o: bind,uid=${PUID},gid=${PGID}

  yourService:
    image: ubuntu
    volumes:
      - storage:/storage
```
