### ISSUE TITLE
List slowly before transfer

### ISSUE THREAD

**Issue by zhucan** [rclone/rclone#6877]
#### What is the problem you are having with rclone?
Before transfer, spend more time to list all files; I want to reduce the time of list all files

#### What is your rclone version (output from `rclone version`)
```
[root@node02 ~]# rclone --version 
rclone v1.59.2
- os/version: centos 7.9.2009 (64 bit)
- os/kernel: 3.10.0-1160.45.1.el7.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.18.6
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
centos

#### Which cloud storage system are you using? (e.g. Google Drive)
local to ceph s3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone copy ./ lqs:rasmap-test-full-b1/lidar/deeproute_all/samples/trafficlane_label_v2_16_new_calib --checkers 128 --transfers 128 --s3-chunk-size 50M --s3-upload-concurrency 128 --log-level DEBUG --log-file /var/log/lqs.log --fast-list`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2023/03/22 11:47:12 DEBUG : rclone: Version "v1.59.2" starting with parameters ["rclone" "copy" "./" "lqs:rasmap-test-full-b1/lidar/deeproute_all/samples/trafficlane_label_v2_16_new_calib" "--checkers" "128" "--transfers" "128" "--s3-chunk-size" "50M" "--s3-upload-concurrency" "128" "--log-level" "DEBUG" "--log-file" "/var/log/lqs.log" "--fast-list"]
2023/03/22 11:47:12 DEBUG : Creating backend with remote "./"
2023/03/22 11:47:12 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2023/03/22 11:47:12 DEBUG : fs cache: renaming cache item "./" to be canonical "/mnt/lqs"
2023/03/22 11:47:12 DEBUG : Creating backend with remote "lqs:rasmap-test-full-b1/lidar/deeproute_all/samples/trafficlane_label_v2_16_new_calib"
2023/03/22 11:47:12 DEBUG : lqs: detected overridden config - adding "{Akmo1}" suffix to name
2023/03/22 11:47:12 DEBUG : fs cache: renaming cache item "lqs:rasmap-test-full-b1/lidar/deeproute_all/samples/trafficlane_label_v2_16_new_calib" to be canonical "lqs{Akmo1}:rasmap-test-full-b1/lidar/deeproute_all/samples/trafficlane_label_v2_16_new_calib"
2023/03/22 11:48:12 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:       1m0.1s

2023/03/22 11:49:12 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:       2m0.1s

2023/03/22 11:50:12 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:       3m0.1s

2023/03/22 11:51:12 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:       4m0.1s

2023/03/22 11:52:12 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:       5m0.1s

2023/03/22 11:53:12 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:       6m0.1s

2023/03/22 11:54:12 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:       7m0.1s

2023/03/22 11:55:12 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:       8m0.1s
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by zhucan** [comment]
@ncw

**Comment by ncw** [comment]
Sounds like you want the `--check-first` flag

      --check-first   Do all the checks before starting transfers

See the docs here: https://rclone.org/docs/#check-first

**Comment by animosity22** [comment]
@zhucan  - best to post questions/things on the forums first as that will get more conversation and generally questions answered..
