### ISSUE TITLE
rclone chunker - assembling files on remote

### ISSUE THREAD

**Issue by raqmudy** [rclone/rclone#6878]
Hi we are uploading large files to remote nextcloud hosted server and we need to assembly chunk files on remote so was more easy to proxmox ve download files and restore vm

there is a way to instruct chunks to asembly remote files on single files 

actually we use rclone copy command

Regards

**Comment by ncw** [comment]
You'll find that the latest beta has support for chunked uploads with nextcloud which may help.

There is an API call you can do with nextcloud to assemble chunks

Check out: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/chunking.html#assembling-the-chunks

**Comment by animosity22** [comment]
Please use the forums for questions and include all the details asked for.

https://forum.rclone.org
