### ISSUE TITLE
--suffix-keep-extension doesn't preserve .tar.gz

### ISSUE THREAD

**Issue by mutouloves** [rclone/rclone#6892]
--suffix-keep-extension 针对tar.gz、tar.xz、tar.bz2、img.xz等出错，如：1.tar.gz 添加后1.tar.20230325.gz

**Comment by ncw** [comment]
What is the problem? Can you explain more?

**Comment by mutouloves** [comment]
> 问题出在哪里？你能解释更多吗？

比如：
1、本地 home/backups 里面有 rclone.tar.gz 文件。

2、rclone sync home/backups google:backup --backup-dir google:old --suffix="-bak" --suffix-keep-extension

3、同步后 google 网盘 backup 文件夹有 rclone.tar.gz 【正确】，但是old 文件夹是 rclone.tar-bak.gz【bug】 而不是 rclone-bak.tar.gz

**Comment by ncw** [comment]
> For example: 1. There is an rclone.tar.gz file in the local home/backups. 2. rclone sync home/backups google:backup backup-dir google:old suffix="-bak" suffix-keep-extension 3. After synchronization, the backup folder of the google network disk has rclone.tar.gz [Correct], but the old file The folder is rclone.tar-bak.gz [bug] instead of rclone-bak.tar.gz

I understand - great explanation.

Currently rclone will only look for the first extension when preserving extensions.

Sometimes people put a `.` in their filenames which isn't an extension so it is difficult to make a rule to please everyone.

Maybe rclone should recognise .tar.xxx specifically as that seems to be the most common type of double extension. Or have a list of extensions which can be doubled.

Or maybe rclone should test the length of the xxx extension in .xxx.yyy and make sure it 3 or less characters.

What do you think? Any other ideas?

**Comment by mutouloves** [comment]
非常感谢！这个想法很好

**Comment by mutouloves** [comment]
非常感谢，测试了，很棒！
