### ISSUE TITLE
Incomplete error message when copying files to an invalid destination using b2 backend.

### ISSUE THREAD

**Issue by anakimluke** [rclone/rclone#6894]
#### What is the problem you are having with rclone?
When a user attempts to copy files to a b2 backend and specifies an invalid destination, such as `backblaze1:` or `backblaze:/foobar`, the error message that is sent does not specify to the user what was the problem with the command. Instead, it wrongfully states the bucket name is already in use.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.53.3-DEV
- os/arch: linux/amd64
- go version: go1.18.1
```
(The relevant code for this issue doesn't seem to have changed since this version, so I'm assuming it's still reproducible in master)

#### Which cloud storage system are you using? (e.g. Google Drive)

BackBlaze

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
rclone -P -vv copy foo a_backblaze_remote:
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
Failed to copy: failed to create bucket: Bucket name is already in use (400 duplicate_bucket_name) 
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
That's a super ancient version. For general support, it's really best to use the forums.

https://forum.rclone.org
