### ISSUE TITLE
rclone chunker is not assembling files after downloading

### ISSUE THREAD

**Issue by raqmudy** [rclone/rclone#6895]
actually we need the whole file on destination cloud service with 500m max file limit using chunks solve it but on destination need to assembly files 
rclone chunker is not assembling files after downloading. 

Documentation says "The chunker overlay transparently splits large files into smaller chunks during upload to wrapped remote and transparently assembles them back when the file is downloaded. This allows to effectively overcome size limits imposed by storage providers."

#### What is the problem you are having with rclone?
rclone chunker is not assembling files after downloading or there is a parameter to assembly files on destination 

#### What is your rclone version (output from `rclone version`)
rclone v1.59.1
- os/version: debian 10.13 (64 bit)
- os/kernel: 5.4.195-1-pve (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.18.5
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
debian

#### Which cloud storage system are you using? (e.g. Google Drive)
WebDav NextCloud

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone copy /source_dir next cloud: --log-file=/tmp/rclone-log.txt -P -vv --max-age 24h --no-traverse --checkers 1 --transfers 1 --low-level-retries
 3 --cache-dir /rpoolRAID10/.cache/rclone

![image](https://user-images.githubusercontent.com/44668490/227816252-92c9e7cd-110a-4482-8bd9-4cd252d1a9e0.png)

![image](https://user-images.githubusercontent.com/44668490/227816268-b809dfd7-0618-4268-a418-932c17e2877f.png)

**Comment by ncw** [comment]
Can you show your config file (with secrets redacted) please? I suspect this is a config error rather than a problem with chunker.

**Comment by animosity22** [comment]
and update to the latest version and test.

Would be a great support forum post...

https://forum.rclone.org

as it's a general help question.

**Comment by raqmudy** [comment]
> Can you show your config file (with secrets redacted) please? I suspect this is a config error rather than a problem with chunker.

![image](https://user-images.githubusercontent.com/44668490/227816360-fe17ec97-6940-4706-816f-cf213518812a.png)


![image](https://user-images.githubusercontent.com/44668490/227816343-ae62b80a-1e56-43a6-acda-1463cff6b1da.png)

**Comment by animosity22** [comment]
You want to point the chunker remote not the nextcloud remote.

So in your case, you want to overlay: and not nextcloud:

**Comment by animosity22** [comment]
Closing as answered.

Please use the forums for questions:

https://forum.rclone.org
