### ISSUE TITLE
filename encryption problem

### ISSUE THREAD

**Issue by youtehub** [rclone/rclone#6898]
#### What is the problem you are having with rclone?

When I encrypt a filename with rclone, every time I compress it with tar, some files are always lost

#### What is your rclone version (output from `rclone version`)
[rclone v1.62.2](https://github.com/rclone/rclone/releases/tag/v1.62.2)

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Ubuntu 20.04

#### Which cloud storage system are you using? (e.g. Google Drive)

local disk encryption

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
[zlocalErencrypt]
type = crypt
remote = /extdisk02/rootFolder
directory_name_encryption = false
password = [password]
password2 =[password2]
filename_encoding = base32768
filename_encryption = standard
```

```
cd /extdisk02/thunderbarrel; tar -cvf thunderbarrel.tar /extdisk02/rootFolder
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

The problem is not when using the rclone command, in other words, rclone itself is working normally, but when using the Linux command to pack and compress *.tar files, some files seem to be unable to be recognized by the compression software tar, resulting in not all The files can all be compressed into tar, and the same thing happens with the zip compression command.
I tested a method, that is, after adding a custom suffix at the end of the encrypted file name, all files can be packaged and compressed normally.
Attached below are the before and after effects of using a custom file name to see the effect of the packaged file

**before adding the suffix**
![image](https://user-images.githubusercontent.com/18629921/227822045-300c0d68-cfb9-40d2-8046-df4359b1d5d1.png)

**After adding the suffix**
![image](https://user-images.githubusercontent.com/18629921/227822500-8b999a89-c28e-4036-911c-9d931891e657.png)

#### available solutions
When encrypting a filename, add a custom suffix instead of doing nothing directly after encryption, or in other words, even if the filename is encrypted, it should support keeping the suffix *.bin used when unencrypted

```
How to encrypt the filenames.
Enter a string value. Press Enter for the default ("standard").
Choose a number from below, or type in your own value.
   / Encrypt the filenames.
 1 | See the docs for the details.
   \ "standard"
 2 / Very simple filename obfuscation.
   \ "obfuscate"
   / Don't encrypt the file names.
 3 | Adds a ".bin" extension only.
   \ "off"
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Masamune3210** [comment]
Honestly, this sounds like more of a issue that needs to be taken up with the maintainers of the compression packages and less with rclone. Extensions being omitted lends to the idea of obfuscation more than the addition imo

**Comment by youtehub** [comment]
The problem now is that if you want to move these encrypted files to another computer or operating system, or download them to the local file system, an error will be displayed directly, and you cannot move or download them.
