### ISSUE TITLE
PikPak doesn't support multithread streams

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#6915]
As part of #6429 we noted that PikPak doesn't support multithread streams.

Currently it adjusts the global multithread streams config variable which isn't desirable.

We should replace this with a new Feature flag in `fs/features.go`

I suggest `NoMultithreading`. We can then read this in the multithread copy code and disable multithreading there. We could potentially do something in the VFS layer too.

**Comment by 1265578519** [comment]
> @1265578519 The issue here is not about downloading multiple files at the same time. Multithread streams is to split a single large file into multiple segments and download them concurrently by making multiple partial requests. Is this working in the app you are using?

我明白你说的意思，比特彗星具备这种功能，如下图，单个mp4文件总共使用18个线程下载
![image](https://user-images.githubusercontent.com/6442439/230716219-a8bfcb40-f37b-486b-bfbb-51efd35618b4.png)

![image](https://user-images.githubusercontent.com/6442439/230716243-84b70d88-ed1d-4af6-8596-c69569cff261.png)

但是是认为rclone没办法具备这个功能，更多人的用途是在webdav文件管理器中，此时无法具备多线程能力，如果需要我可以提供代码参考以便开发功能实现。

**Comment by ncw** [comment]
I've added a new backend flag NoMultiThreading and made the pikpak backend set it. I've also stopped multithread copy working on backends with NoMultiThreading set.

That's enough to fix this issue as far as I am concerned and it is easy to change later if we find pikpak can support multi threads.

Note you can disable the feature flag with `--disable NoMultiThreading` also.

**Comment by Abu3safeer** [comment]
using `--disable NoMultiThreading` I was able to hit 40MB/s+ 
without it I am locked to 10MB/s

```
Transferred:        1.207 GiB / 1.308 GiB, 92%, 46.327 MiB/s, ETA 2s
Transferred:            0 / 1, 0%
Elapsed time:        26.7s
Transferring:
 * video_file.mkv: 92% /1.308Gi, 46.327Mi/s, 2s
```

while I can hit +60MB/s with IDM.
Actually I am happy with rclone, it unlock the limit of my premium account, 

![Image](https://github.com/user-attachments/assets/fa666787-f0e5-4912-b036-614a0be29ecf)
