### ISSUE TITLE
Error creating mount Error: Request failed with status code 500

### ISSUE THREAD

**Issue by 1265578519** [rclone/rclone#6927]
2023/04/07 20:22:30 mount FAILED: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:22:30 ERROR : rc: "mount/mount": error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:22:33 mount FAILED: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:22:33 ERROR : rc: "mount/mount": error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:22:38 mount FAILED: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:22:38 ERROR : rc: "mount/mount": error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:22:48 mount FAILED: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:22:48 ERROR : rc: "mount/mount": error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:22:57 mount FAILED: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:22:57 ERROR : rc: "mount/mount": error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:23:05 mount FAILED: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:23:05 ERROR : rc: "mount/mount": error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:24:44 mount FAILED: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:24:44 ERROR : rc: "mount/mount": error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:30:34 NOTICE: Assigning drive letter "Z:"
2023/04/07 20:30:34 mount FAILED: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:30:34 ERROR : rc: "mount/mount": error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:30:40 mount FAILED: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp
2023/04/07 20:30:40 ERROR : rc: "mount/mount": error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find winfsp

![image](https://user-images.githubusercontent.com/6442439/230611052-eb8987c5-251c-4afd-96e7-8de8eaf2dc2d.png)
我有安装winfsp（C:\Program Files (x86)\WinFsp\bin），为什么rclone不能使用？

**Comment by animosity22** [comment]
Please post on the forums.

Use the complete help and support template.

https://forum.rclone.org

**Comment by 1265578519** [comment]
这可能是一个bug，重新启动后这个问题已经解决了！

**Comment by ncw** [comment]
> cgofuse: cannot find winfsp

Looks like you need to install WinFSP
