### ISSUE TITLE
0x8007045D I/O设备错误

### ISSUE THREAD

**Issue by 1265578519** [rclone/rclone#6928]
2023/04/07 21:05:24 ERROR : IO error: Get "https://192.168.1.3/dm/test.mp4": tls: failed to verify certificate: x509: certificate signed by unknown authority

**Comment by animosity22** [comment]
Please use the forums and use the help and support template.

https://forum.rclone.org

**Comment by 1265578519** [comment]
--no-check-certificate 我找到解决办法了！
