### ISSUE TITLE
Dropbox requiring lower case for `rclone lsd`

### ISSUE THREAD

**Issue by gleachkr** [rclone/rclone#693]
I'm running rclone v1.33-Dev, on an arch linux 64 bit machine.

There's something strange going on with `rclone lsd Dropbox` on my system. 

If I run `rclone -v lsd Dropbox:/MusicLibrary` (this is the correct capitalization for the directory) the result is 

```
2016/09/07 11:18:03 rclone: Version "v1.33-DEV" starting with parameters ["rclone" "-v" "lsd" "Dropbox:/MusicLibrary"]
2016/09/07 11:18:03 Dropbox root 'MusicLibrary': Modify window not supported
2016/09/07 11:18:04 path "/MusicLibrary/3rd Bass" is not under root "/MusicLibrary/"
```

If I run `rclone -v lsd Dropbox:/musiclibrary`, the result is 

```
2016/09/07 11:18:03 rclone: Version "v1.33-DEV" starting with parameters ["rclone" "-v" "lsd" "Dropbox:/MusicLibrary"]
2016/09/07 11:18:03 Dropbox root 'MusicLibrary': Modify window not supported
(and then a correct listing)
```

This also affects the FUSE functionality (:thumbsup:, btw, the fuse feature is awesome), and seems to be affecting all my folders on Dropbox. The problem does not arise with `rclone ls Dropbox:MusicLibrary`.

**Comment by ncw** [comment]
This is probably the same issue as #691 which probably means dropbox have changed something in their API in a subtle way. I haven't found anything about it though. 

It might be that swapping to the Dropbox v2 API is the right solution - #349

**Comment by animosity22** [comment]
since this was back with v1 api and we're on the v2, I'm going to close this out. If there is still a problem please let me know and we can go from there.

Thanks!
