### ISSUE TITLE
Custom Cache Behavior: Delete only expired data and stop caching new data when cache is full

### ISSUE THREAD

**Issue by datong-new** [rclone/rclone#6937]
I have a specific use case that requires custom cache behavior for rclone, and I was wondering if anyone has a solution or is interested in implementing this feature.

In my scenario, users continuously read data, and I cannot interrupt their access. I would like to implement the following cache behavior:

1. When the cache is full, only delete expired data.
2. If the cache space is still insufficient after deleting expired data, stop caching new data, but continue to allow direct reads from the remote storage.
This cache behavior would help me balance between cache size and performance while ensuring users' access to the data remains uninterrupted. If there is an existing solution or any suggestions on how to achieve this, I would appreciate your help. Otherwise, I am interested in discussing the possibility of implementing this feature in rclone.

Thank you for your assistance and consideration.

**Comment by Masamune3210** [comment]
This is really better fit on the forum than in issues, should probably go ask on there instead
