### ISSUE TITLE
Use cdn fonction (1fichier remote)

### ISSUE THREAD

**Issue by hidry-git** [rclone/rclone#6943]
What problem are you are trying to solve?
I would like to have the cdn option for 1fichier

when I use the api of 1fichier I have the option to use or not but credit, when I use the remote on rclone it uses my credits by default which is not great considering that my account is premium (thanks for this!)

From https://1fichier.com/api.html?lg=en:

{
  "url" : "https://1fichier.com/?example",
  "inline" : 0/1,

  *"cdn" : 0/1,**   <<< ---------------

  "restrict_ip" : 0/1/2,
  "single" : 0/1,
  "pass" : "mot_de_pass",
  "no_ssl" : 0/1,
  "folder_id" : 1234,
  "filename" : "FileName",
  "sharing_user" : "user@example.com"
}

My suggestion would be to add an option to use the cdn 1/1 and by default let it not use so 0/1.

Thanks for your consideration!

Sorry for the translation

**Comment by ncw** [comment]
Give this a go - use the `--fichier-cdn` flag or set `cdn = true` in your config.

It sets the cdn flag correctly in the download but I didn't see any difference - maybe you will.

[v1.63.0-beta.6959.36f2ecac0.fix-6943-fichier-cdn](https://beta.rclone.org/branch/fix-6943-fichier-cdn/v1.63.0-beta.6959.36f2ecac0.fix-6943-fichier-cdn/) on branch [fix-6943-fichier-cdn](https://github.com/rclone/rclone/tree/fix-6943-fichier-cdn) (uploaded in 15-30 mins)

**Comment by hidry-git** [comment]
wow thank you very much for your reactivity, I will take the test now

**Comment by ncw** [comment]
Let me know if it works or not. You can see what rclone sends with `-vv --dump requests`

**Comment by hidry-git** [comment]
I admit to being a little blocked, I am on a dedicated server which blocks me several accesses, 
I try to update rclone with the new code in curl

**Comment by hidry-git** [comment]
I think it's perfect, I did the test on a local linux server and I get the file, just contact the admin of my main server to tell him to update and get back to you , here is the error code i was getting on the main server

IO error: couldn't list files: HTTP error 403 (403 Forbidden) returned body: "{\"message\":\"Must have CDN #875\",\"status\":\"KO\"}"

and this error is no longer on my test server and I recover my file without problem

thank you again it will really make a difference for me

**Comment by ncw** [comment]
Thanks for testing :-) I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.63

**Comment by hidry-git** [comment]
thank you it's really appreciated
