### ISSUE TITLE
S3 mount caches directory listings forever and never refreshes them

### ISSUE THREAD

**Issue by rulatir** [rclone/rclone#6944]
#### What is the problem you are having with rclone?

An S3 mount does not refresh directory listings at all.

#### Steps to reproduce

 1. Mount an S3 remote using something like `rclone mount --daemon remote: ~/mnt/s3`
 2. Using any file manager, navigate to a directory, say `~/mnt/s3/test`
 3. Using any method external to the mount (e.g. AWS console, a locally running PHP script that uses `AwsS3V3Adapter` to write to the same S3 bucket) to create a subdirectory, say `nested/`, inside the S3 location that maps to `~/mnt/s3/test` in the mount.
 4. Using the file manager still showing the contents of `~/mnt/s3/test`, try refreshing the listing.
 
#### Expected result

The `nested` subdirectory should be listed.

#### Actual result

Neither the `nested` subdirectory nor its contents are listed using any method like refreshing the file manager view, `ls` or `find`. The only way to see the new directory is to unmount the share with `fusermount -u ~/mnt/s3` and mount again.

#### My remote configuration

```
[zuu-s3]
type = s3
provider = AWS
access_key_id = [REDACTED]
secret_access_key = [REDACTED]
region = eu-central-1
```

#### What is your rclone version (output from `rclone version`)

```
rclone v1.63.0-beta.6953.99dd748fe
- os/version: arch "rolling" (64 bit)
- os/kernel: 6.2.10-arch1-1 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.3
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Linux 64bit

#### Which cloud storage system are you using? (e.g. Google Drive)

S3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
rclone mount --daemon zuu-s3: ~/mnt/s3
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2023/04/13 15:38:31 DEBUG : rclone: Version "v1.63.0-beta.6953.99dd748fe" starting with parameters ["rclone" "mount" "--daemon" "-vv" "zuu-s3:" "/home/rulatir/mnt/s3"]
2023/04/13 15:38:31 DEBUG : Creating backend with remote "zuu-s3:"
2023/04/13 15:38:31 DEBUG : Using config file from "/home/rulatir/.config/rclone/rclone.conf"
2023/04/13 15:38:31 DEBUG : rclone: Version "v1.63.0-beta.6953.99dd748fe" finishing with parameters ["/usr/bin/rclone" "mount" "--daemon" "-vv" "zuu-s3:" "/home/rulatir/mnt/s3"]
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
The dir cache times are documented here:

https://rclone.org/commands/rclone_mount/#vfs-directory-cache

If you are seeing an issue, please post on the forums and use the whole help and support template and recreate the issue.

Thanks
