### ISSUE TITLE
Uptobox flag for private file

### ISSUE THREAD

**Issue by ericlm128** [rclone/rclone#6946]
Hello,

I recently started using rclone to backup files to uptobox, unfortunately I couldn't find a flag for the files to be private and not public.

Thanks in advance and good job

**Comment by ncw** [comment]
@buengese is this something we can add from the uptobox API?

**Comment by ncw** [comment]
As part of uploading the file we are already calling that PATCH call to update its name.

https://github.com/rclone/rclone/blob/2faa4758e40d1c574ef04e99e3c80f3900eaa2a8/backend/uptobox/uptobox.go#L533-L534

By calling

https://github.com/rclone/rclone/blob/2faa4758e40d1c574ef04e99e3c80f3900eaa2a8/backend/uptobox/uptobox.go#L454

We could update its public status there too.

The struct already has a `Public` field

https://github.com/rclone/rclone/blob/2faa4758e40d1c574ef04e99e3c80f3900eaa2a8/backend/uptobox/api/types.go#L153-L159

So we'd just need to make an option for it and set it on the upload.

Do you want to have a go at this @ericlm128 ?

**Comment by ericlm128** [comment]
Nice analysis job :)
Yes of course I am ready to test a beta version if necessary.

**Comment by ncw** [comment]
@ericlm128 - I was hoping you might make the change?

**Comment by ncw** [comment]
OK give this a go

Try uploading files with and without the `--uptobox-private` flag (or stick it in the config `private = true`.

[v1.63.0-beta.6985.c30d74f1a.fix-6946-uptobox-public](https://beta.rclone.org/branch/fix-6946-uptobox-public/v1.63.0-beta.6985.c30d74f1a.fix-6946-uptobox-public/) on branch [fix-6946-uptobox-public](https://github.com/rclone/rclone/tree/fix-6946-uptobox-public) (uploaded in 15-30 mins)

**Comment by ericlm128** [comment]
Hello,

I'm on Windows 10 64 bits so I took the version `rclone-v1.63.0-beta.6985.c30d74f1a.fix-6946-uptobox-public-windows-amd64.zip`

rclone --version
Here is my previous version:
```
rclone v1.62.2
- os/version: Microsoft Windows 10 Pro 22H2 (64 bit)
- os/kernel: 10.0.19045.2846 Build 19045.2846.2846 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: cmount
```

Here is the new version:
```
rclone v1.63.0-beta.6985.c30d74f1a.fix-6946-uptobox-public
- os/version: Microsoft Windows 10 Pro 22H2 (64 bit)
- os/kernel: 10.0.19045.2846 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.20.3
- go/linking: static
- go/tags: cmount
```

The same command line (without the new option) does not work with the new version.
Command line :
`rclone sync --progress --stats 1s --create-empty-src-dirs --transfers 8 --retries 20 --retries-sleep 30s "C:\test" "uptobox:Test"`

Message :
```
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 1 [running]:
reflect.valueInterface({0x1ad1340?, 0xc0004f8410?, 0x1f44c41?}, 0x6?)
        reflect/value.go:1491 +0xd8
reflect.Value.Interface(...)
        reflect/value.go:1480
github.com/rclone/rclone/fs/config/configstruct.Items({0x1a8ba40?, 0xc0004f8400?})
        github.com/rclone/rclone/fs/config/configstruct/configstruct.go:82 +0x30f
github.com/rclone/rclone/fs/config/configstruct.Set({0x2ca3a0d8, 0xc000b1c7e0}, {0x1a8ba40?, 0xc0004f8400})
        github.com/rclone/rclone/fs/config/configstruct/configstruct.go:103 +0x5c
github.com/rclone/rclone/backend/uptobox.NewFs({0x2486e90, 0xc00004a060}, {0xc00004a200, 0x7}, {0xc00004a208, 0x4}, {0x247d210?, 0xc000b1c7e0})
        github.com/rclone/rclone/backend/uptobox/uptobox.go:200 +0xa6
github.com/rclone/rclone/fs.NewFs({0x2486e90, 0xc00004a060}, {0xc00004a200, 0xc})
        github.com/rclone/rclone/fs/newfs.go:53 +0x38a
github.com/rclone/rclone/fs/cache.GetFn.func1({0x1bb57e0?, 0xc000b1c240?})
        github.com/rclone/rclone/fs/cache/cache.go:67 +0x3b
github.com/rclone/rclone/lib/cache.(*Cache).Get(0xc000b1c210, {0xc00004a200, 0xc}, 0xc000b0fb68)
        github.com/rclone/rclone/lib/cache/cache.go:88 +0xe7
github.com/rclone/rclone/fs/cache.GetFn({0x2486e90, 0xc00004a060}, {0xc00004a200, 0xc}, 0x20ac2c8)
        github.com/rclone/rclone/fs/cache/cache.go:66 +0x12a
github.com/rclone/rclone/fs/cache.Get({0x2486e90, 0xc00004a060}, {0xc00004a200, 0xc})
        github.com/rclone/rclone/fs/cache/cache.go:132 +0x6f
github.com/rclone/rclone/cmd.newFsDir({0xc00004a200, 0xc})
        github.com/rclone/rclone/cmd/cmd.go:149 +0x45
github.com/rclone/rclone/cmd.NewFsSrcFileDst({0xc0006952c0, 0x2, 0x0?})
        github.com/rclone/rclone/cmd/cmd.go:178 +0x76
github.com/rclone/rclone/cmd/sync.glob..func1(0x33cfa00?, {0xc0006952c0, 0x2, 0xc})
        github.com/rclone/rclone/cmd/sync/sync.go:65 +0x6b
github.com/spf13/cobra.(*Command).execute(0x33cfa00, {0xc000694fc0, 0xc, 0xc})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x33c2260)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/rclone/rclone/cmd.Main()
        github.com/rclone/rclone/cmd/cmd.go:567 +0x76
main.main()
        github.com/rclone/rclone/rclone.go:14 +0x17
```

**Comment by ncw** [comment]
That was a silly mistake - sorry!

Try this

[v1.63.0-beta.6985.35d9090a4.fix-6946-uptobox-public](https://beta.rclone.org/branch/fix-6946-uptobox-public/v1.63.0-beta.6985.35d9090a4.fix-6946-uptobox-public/) on branch [fix-6946-uptobox-public](https://github.com/rclone/rclone/tree/fix-6946-uptobox-public) (uploaded in 15-30 mins)

**Comment by ericlm128** [comment]
ok, I was afraid that it came from me. 
But now I could only test in 10 days because I'm on vacation (with ADSL :/)

**Comment by ericlm128** [comment]
After testing the last delivery. I confirm that this works very well either via the parameter or via the configuration file.

So I have a question, if you set `private = true` in the configuration file can we load it in public via a parameter ?
In other words, defining it in the configuration file is a default preference or does it become mandatory?

Nice job 👍

**Comment by jesussmd** [comment]
Can someone explain to me what is the difference between private files and public?

Anyone can access to my files in public even I didn't shared the link?

**Comment by jesussmd** [comment]
Can someone explain to me what is the difference between private files and public?

Can anyone access to my files in public even I didn't shared the link?

**Comment by ericlm128** [comment]
hello 
private files cannot be shared unlike the public file. 
If you share a folder that mixes the two types, the recipient should only see public files.
 That's what I understood but I'm in degraded mode and difficult to cross again for me at the moment
Bye

**Comment by jesussmd** [comment]
> hello private files cannot be shared unlike the public file. If you share a folder that mixes the two types, the recipient should only see public files. That's what I understood but I'm in degraded mode and difficult to cross again for me at the moment Bye

Yes, I've discovered today

The public files will share when you share the folder, and the privete don't (Only shared folders); direct links always will sharing.

Perhaps the reason is the arquitecture of uptobox is a little old for folders
