### ISSUE TITLE
Publish to microsoft store in msix format

### ISSUE THREAD

**Issue by soredake** [rclone/rclone#6947]
#### What is your current rclone version (output from `rclone version`)?
❯ rclone --version
rclone v1.62.2
- os/version: Microsoft Windows 11 Pro 22H2 (64 bit)
- os/kernel: 10.0.22621.1555 Build 22621.1555.1555 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: cmount

#### What problem are you are trying to solve?

Publishing rclone to microsoft store in msix format will make installation/updating/uninstall very easy.

Example benefits of msix package format: https://github.com/felixrieseberg/windows95/issues/221 https://learn.microsoft.com/en-us/windows/msix/overview#key-features

#### How do you think rclone should be changed to solve that?

rclone should be published to microsoft store in msix format

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
You can now install rclone with `winget` on Windows. Is that not sufficient?

**Comment by soredake** [comment]
@ncw no, winget can't auto-update apps and requires admin rights to create alias which is annoying (https://github.com/microsoft/winget-cli/issues/2802)

**Comment by animosity22** [comment]
It's a single binary that you can self update. Not sure how much easier it can get than that.

**Comment by soredake** [comment]
> It's a single binary that you can self update. Not sure how much easier it can get than that.

I don't want to update anything manually, stores/package managers invented to do this automatically.

**Comment by animosity22** [comment]
> I don't want to update anything manually, stores/package managers invented to do this automatically.

Schedule rclone self-update when you want to update it.

**Comment by soredake** [comment]
> > I don't want to update anything manually, stores/package managers invented to do this automatically.
> 
> Schedule rclone self-update when you want to update it.

I don't want to schedule/manually update it, i just want to install & forget and have it auto-updated in background.

**Comment by animosity22** [comment]
> I don't want to schedule/manually update it, i just want to install & forget and have it auto-updated in background.

I'm just giving you a solution now so you can get what you want. It's incredibly easy to install and update. 

If you'd like to support and maintain the MSIX, by all means, submit a PR and help out :)

**Comment by ncw** [comment]
@soredake I don't use Windows so I don't really understand the differences between the installers, but if you wanted to create an MSIX that would be great :-)
