### ISSUE TITLE
rclone lsd returns error/return code 0 even when the file is not present.

### ISSUE THREAD

**Issue by ManisankarKanagasabapathy** [rclone/rclone#6949]
#### What is the problem you are having with rclone?

rclone lsd returning error 0 when the file is not present.

#### What is your rclone version (output from `rclone version`)

rclone --version
rclone v1.62.2
- os/version: centos 8 (64 bit)
- os/kernel: 4.18.0-448.el8.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Redhat 8

#### Which cloud storage system are you using? (e.g. Google Drive)

s3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone lsd

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

[ybdadmin@storage-central-01 ~]$ rclone lsd -vv ***********
2023/04/14 13:38:52 DEBUG : rclone: Version "v1.62.2" starting with parameters ["rclone" "lsd" "-vv" "**********"]
2023/04/14 13:38:52 DEBUG : Creating backend with remote "************"
2023/04/14 13:38:52 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2023/04/14 13:38:52 DEBUG : Resolving service "s3" region "us-east-1"
2023/04/14 13:38:53 DEBUG : 4 go routines active

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
If you want to get some general help, best to use the forums.

https://forum.rclone.org

```
etexter@Earls-Mac-mini ~ % rclone lsd DB:blah
2023/04/14 19:23:31 ERROR : : error listing: directory not found
2023/04/14 19:23:31 Failed to lsd with 2 errors: last error was: directory not found
etexter@Earls-Mac-mini ~ % echo $?
3
```
