### ISSUE TITLE
Rclone on MacOS Ventura crashes frequently

### ISSUE THREAD

**Issue by dcarnelutti** [rclone/rclone#6952]
#### What is the problem you are having with rclone?
I'm working on a new Bitcoin Node. Downloaded all the blocks and indexes into a fast nve disc. I'm cloning all the files now on my Truenas server.

My Mac crashes frequently during this process

#### What is your rclone version (output from `rclone version`)
rclone 1.62 

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Local OS MacOS Ventura Beta (latest)

#### Which cloud storage system are you using? (e.g. Google Drive)
Truenas (latest) on Proxmox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone sync -i /Volumes/Editing\ disc/Bitcoin /Volumes/umbrel/bitcoin-core/.bitcoin

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

Everytime it crashes rcloen starts checking all the files again which consumes a lot of time.

If there a way to create checkpoint and execute rclone from that point only? Like: you already checked all these files, start form here.

I don't want to move the local files as I pretend to keep this as a backup until I finally manage to make the new node works

Sample of the -v results

Transferred:   	    7.698 GiB / 28.688 GiB, 27%, 439.811 KiB/s, ETA 13h54m3s
Checks:              4783 / 10149, 47%
Transferred:         2063 / 12068, 17%
Elapsed time:      46m0.0s
Checking:
 *                           blocks/blk01786.dat: checking
 *                           blocks/blk01787.dat: checking
 *                           blocks/blk01788.dat: checking
 *                           blocks/blk01789.dat: checking
 *                           blocks/blk01790.dat: checking
 *                           blocks/blk01791.dat: checking
 *                           blocks/blk01792.dat: checking
 *                           blocks/blk01793.dat: checking
Transferring:
 *                    indexes/txindex/268243.ldb:100% /2.073Mi, 424.989Ki/s, 0s
 *                    indexes/txindex/268246.ldb:100% /2.074Mi, 0/s, -
 *                    indexes/txindex/268249.ldb:100% /2.073Mi, 2.071Mi/s, 0s
 *                    indexes/txindex/268250.ldb:  0% /2.073Mi, 0/s, -

2023/04/15 08:58:31 INFO  : indexes/txindex/268243.ldb: Copied (new)
2023/04/15 08:58:31 INFO  : blocks/blk01786.dat: Updated modification time in destination
2023/04/15 08:58:32 INFO  : blocks/blk01787.dat: Updated modification time in destination
2023/04/15 08:58:32 INFO  : blocks/blk01788.dat: Updated modification time in destination
2023/04/15 08:58:32 INFO  : indexes/txindex/268249.ldb: Copied (new)
2023/04/15 08:58:32 INFO  : blocks/blk01789.dat: Updated modification time in destination
2023/04/15 08:58:32 INFO  : indexes/txindex/268246.ldb: Copied (new)
2023/04/15 08:58:34 INFO  : blocks/blk01790.dat: Updated modification time in destination
2023/04/15 08:58:34 INFO  : indexes/txindex/268250.ldb: Copied (new)
2023/04/15 08:58:34 INFO  : indexes/txindex/268252.ldb: Copied (new)
2023/04/15 08:58:34 INFO  : blocks/blk01791.dat: Updated modification time in destination
2023/04/15 08:58:34 INFO  : indexes/txindex/268253.ldb: Copied (new)
2023/04/15 08:58:35 INFO  : blocks/blk01792.dat: Updated modification time in destination
2023/04/15 08:58:36 INFO  : indexes/txindex/268255.ldb: Copied (new)
2023/04/15 08:58:36 INFO  : indexes/txindex/268254.ldb: Copied (new)
2023/04/15 08:58:36 INFO  : indexes/txindex/268258.ldb: Copied (new)
2023/04/15 08:58:37 INFO  : indexes/txindex/268261.ldb: Copied (new)
2023/04/15 08:58:37 INFO  : indexes/txindex/268259.ldb: Copied (new)
2023/04/15 08:58:39 INFO  : indexes/txindex/268264.ldb: Copied (new)
2023/04/15 08:58:39 INFO  : indexes/txindex/268262.ldb: Copied (new)
2023/04/15 08:58:40 INFO  : blocks/blk01793.dat: Updated modification time in destination
2023/04/15 08:58:40 INFO  : indexes/txindex/268266.ldb: Copied (new)
2023/04/15 08:58:41 INFO  : indexes/txindex/268267.ldb: Copied (new)
2023/04/15 08:58:41 INFO  : indexes/txindex/268269.ldb: Copied (new)
2023/04/15 08:58:43 INFO  : indexes/txindex/268272.ldb: Copied (new)
2023/04/15 08:58:43 INFO  : indexes/txindex/268273.ldb: Copied (new)
2023/04/15 08:58:44 INFO  : blocks/blk01795.dat: Updated modification time in destination
2023/04/15 08:58:44 INFO  : blocks/blk01794.dat: Updated modification time in destination
2023/04/15 08:58:44 INFO  : blocks/blk01796.dat: Updated modification time in destination
2023/04/15 08:58:44 INFO  : indexes/txindex/268283.ldb: Copied (new)
2023/04/15 08:58:44 INFO  : indexes/txindex/268282.ldb: Copied (new)
2023/04/15 08:58:44 INFO  : blocks/blk01797.dat: Updated modification time in destination
2023/04/15 08:58:45 INFO  : indexes/txindex/268286.ldb: Copied (new)
2023/04/15 08:58:45 INFO  : indexes/txindex/268287.ldb: Copied (new)
2023/04/15 08:58:45 INFO  : indexes/txindex/268292.ldb: Copied (new)
2023/04/15 08:58:46 INFO  : blocks/blk01798.dat: Updated modification time in destination
2023/04/15 08:58:46 INFO  : blocks/blk01799.dat: Updated modification time in destination
2023/04/15 08:58:46 INFO  : indexes/txindex/268289.ldb: Copied (new)
2023/04/15 08:58:46 INFO  : indexes/txindex/268293.ldb: Copied (new)
2023/04/15 08:58:46 INFO  : blocks/blk01800.dat: Updated modification time in destination
2023/04/15 08:58:47 INFO  : indexes/txindex/268295.ldb: Copied (new)
2023/04/15 08:58:48 INFO  : indexes/txindex/268296.ldb: Copied (new)
2023/04/15 08:58:49 INFO  : indexes/txindex/268297.ldb: Copied (new)
2023/04/15 08:58:51 INFO  : indexes/txindex/268298.ldb: Copied (new)
2023/04/15 08:58:53 INFO  : indexes/txindex/268302.ldb: Copied (new)
2023/04/15 08:58:53 INFO  : indexes/txindex/268299.ldb: Copied (new)
2023/04/15 08:58:54 INFO  : indexes/txindex/268303.ldb: Copied (new)
2023/04/15 08:58:55 INFO  : blocks/blk01801.dat: Updated modification time in destination
2023/04/15 08:58:55 INFO  : indexes/txindex/268315.ldb: Copied (new)
2023/04/15 08:58:56 INFO  : indexes/txindex/268316.ldb: Copied (new)
2023/04/15 08:58:57 INFO  : indexes/txindex/268318.ldb: Copied (new)
2023/04/15 08:58:57 INFO  : indexes/txindex/268323.ldb: Copied (new)
2023/04/15 08:58:58 INFO  : indexes/txindex/268320.ldb: Copied (new)
2023/04/15 08:58:58 INFO  : indexes/txindex/268324.ldb: Copied (new)
2023/04/15 08:58:59 INFO  : blocks/blk01802.dat: Updated modification time in destination
2023/04/15 08:58:59 INFO  : blocks/blk01805.dat: Updated modification time in destination
2023/04/15 08:58:59 INFO  : blocks/blk01803.dat: Updated modification time in destination
2023/04/15 08:58:59 INFO  : blocks/blk01804.dat: Updated modification time in destination
2023/04/15 08:58:59 INFO  : indexes/txindex/268327.ldb: Copied (new)
2023/04/15 08:58:59 INFO  : indexes/txindex/268331.ldb: Copied (new)
2023/04/15 08:59:00 INFO  : indexes/txindex/268332.ldb: Copied (new)
2023/04/15 08:59:00 INFO  : blocks/blk01807.dat: Updated modification time in destination
2023/04/15 08:59:00 INFO  : indexes/txindex/268328.ldb: Copied (new)
2023/04/15 08:59:01 INFO  : indexes/txindex/268334.ldb: Copied (new)
2023/04/15 08:59:02 INFO  : indexes/txindex/268338.ldb: Copied (new)
2023/04/15 08:59:03 INFO  : indexes/txindex/268337.ldb: Copied (new)
2023/04/15 08:59:03 INFO  : blocks/blk01806.dat: Updated modification time in destination
2023/04/15 08:59:04 INFO  : indexes/txindex/268341.ldb: Copied (new)
2023/04/15 08:59:04 INFO  : indexes/txindex/268342.ldb: Copied (new)
2023/04/15 08:59:05 INFO  : blocks/blk01808.dat: Updated modification time in destination
2023/04/15 08:59:06 INFO  : indexes/txindex/268343.ldb: Copied (new)
2023/04/15 08:59:06 INFO  : indexes/txindex/268344.ldb: Copied (new)
2023/04/15 08:59:07 INFO  : indexes/txindex/268345.ldb: Copied (new)
2023/04/15 08:59:08 INFO  : blocks/blk01809.dat: Updated modification time in destination
2023/04/15 08:59:09 INFO  : indexes/txindex/268349.ldb: Copied (new)
2023/04/15 08:59:09 INFO  : indexes/txindex/268358.ldb: Copied (new)
2023/04/15 08:59:09 INFO  : indexes/txindex/268348.ldb: Copied (new)
2023/04/15 08:59:10 INFO  : blocks/blk01810.dat: Updated modification time in destination
2023/04/15 08:59:10 INFO  : blocks/blk01811.dat: Updated modification time in destination
2023/04/15 08:59:10 INFO  : blocks/blk01812.dat: Updated modification time in destination
2023/04/15 08:59:10 INFO  : blocks/blk01813.dat: Updated modification time in destination
2023/04/15 08:59:11 INFO  : indexes/txindex/268359.ldb: Copied (new)
2023/04/15 08:59:11 INFO  : indexes/txindex/268362.ldb: Copied (new)
2023/04/15 08:59:12 INFO  : indexes/txindex/268367.ldb: Copied (new)
2023/04/15 08:59:12 INFO  : indexes/txindex/268365.ldb: Copied (new)
2023/04/15 08:59:12 INFO  : blocks/blk01814.dat: Updated modification time in destination
2023/04/15 08:59:12 INFO  : indexes/txindex/268368.ldb: Copied (new)
2023/04/15 08:59:12 INFO  : indexes/txindex/268370.ldb: Copied (new)
2023/04/15 08:59:14 INFO  : indexes/txindex/268373.ldb: Copied (new)
2023/04/15 08:59:14 INFO  : indexes/txindex/268374.ldb: Copied (new)
2023/04/15 08:59:15 INFO  : indexes/txindex/268377.ldb: Copied (new)
2023/04/15 08:59:15 INFO  : blocks/blk01815.dat: Updated modification time in destination
2023/04/15 08:59:15 INFO  : indexes/txindex/268378.ldb: Copied (new)
2023/04/15 08:59:16 INFO  : indexes/txindex/268380.ldb: Copied (new)
2023/04/15 08:59:16 INFO  : blocks/blk01816.dat: Updated modification time in destination
2023/04/15 08:59:17 INFO  : indexes/txindex/268392.ldb: Copied (new)
2023/04/15 08:59:18 INFO  : indexes/txindex/268397.ldb: Copied (new)
2023/04/15 08:59:18 INFO  : indexes/txindex/268393.ldb: Copied (new)
2023/04/15 08:59:20 INFO  : indexes/txindex/268396.ldb: Copied (new)
2023/04/15 08:59:20 INFO  : indexes/txindex/268398.ldb: Copied (new)
2023/04/15 08:59:21 INFO  : blocks/blk01817.dat: Updated modification time in destination
2023/04/15 08:59:21 INFO  : blocks/blk01818.dat: Updated modification time in destination
2023/04/15 08:59:21 INFO  : indexes/txindex/268399.ldb: Copied (new)
2023/04/15 08:59:21 INFO  : indexes/txindex/268400.ldb: Copied (new)
2023/04/15 08:59:22 INFO  : blocks/blk01820.dat: Updated modification time in destination
2023/04/15 08:59:22 INFO  : blocks/blk01819.dat: Updated modification time in destination
2023/04/15 08:59:22 INFO  : indexes/txindex/268404.ldb: Copied (new)
2023/04/15 08:59:22 INFO  : indexes/txindex/268403.ldb: Copied (new)
2023/04/15 08:59:22 INFO  : blocks/blk01821.dat: Updated modification time in destination
2023/04/15 08:59:23 INFO  : indexes/txindex/268407.ldb: Copied (new)
2023/04/15 08:59:23 INFO  : indexes/txindex/268406.ldb: Copied (new)
2023/04/15 08:59:24 INFO  : blocks/blk01822.dat: Updated modification time in destination
2023/04/15 08:59:24 INFO  : indexes/txindex/268414.ldb: Copied (new)
2023/04/15 08:59:25 INFO  : indexes/txindex/268411.ldb: Copied (new)
2023/04/15 08:59:25 INFO  : indexes/txindex/268409.ldb: Copied (new)
2023/04/15 08:59:26 INFO  : indexes/txindex/268415.ldb: Copied (new)
2023/04/15 08:59:26 INFO  : indexes/txindex/268421.ldb: Copied (new)
2023/04/15 08:59:27 INFO  : blocks/blk01823.dat: Updated modification time in destination
2023/04/15 08:59:28 INFO  : indexes/txindex/268417.ldb: Copied (new)
2023/04/15 08:59:28 INFO  : indexes/txindex/268420.ldb: Copied (new)
2023/04/15 08:59:29 INFO  : blocks/blk01824.dat: Updated modification time in destination
2023/04/15 08:59:29 INFO  : indexes/txindex/268423.ldb: Copied (new)
2023/04/15 08:59:29 INFO  : indexes/txindex/268424.ldb: Copied (new)
2023/04/15 08:59:30 INFO  : indexes/txindex/268431.ldb: Copied (new)

**Comment by animosity22** [comment]
No there isn't.

If you are using local storage, why not use rsync or a local tool?

**Comment by ncw** [comment]
> My Mac crashes frequently during this process

How does it crash - does it lock up? I don't see a crash in the rclone log.

Rclone is very efficient at transferring files so it works the hardware and OS very hard.

This is very unlikely to be an rclone problem if it is crashing your machine and more likely to be an OS or hardware problem.

We very recently debugged a similar situation which turned out to be a thunderbolt enclosure

https://forum.rclone.org/t/simultaneous-freeze-of-macos-and-rclone/37170/

Its worth reading through that thread to see if it gives you any ideas.
