### ISSUE TITLE
Single tenant Sharepoint application do not ask for credentials

### ISSUE THREAD

**Issue by rdoering** [rclone/rclone#6959]
I registered a single tenant application in the Azure portal. 

Now I am able to fetch the access key **without** entering my personal credential and by using client_id with this command.

```shell
curl --location --request GET 'https://login.microsoftonline.com/8f5f7bf4-542e-41aa-8b9a-<..>/oauth2/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=3e72e39d-a253-<...>' \
--data-urlencode 'resource=https://graph.microsoft.com/' \
--data-urlencode 'client_secret=u0t8Q~sIGN<...>' \
--data-urlencode 'grant_type=client_credentials'
```

But if I want to retrieve the access token using rclone I have to enter the my personal credential. I followed this [instructions ](https://rclone.org/onedrive/#creating-client-id-for-onedrive-business) and used this command.

```shell
rclone --onedrive-drive-type "business" --onedrive-token-url 'https://login.microsoftonline.com/8f5f7bf4-542e-41aa-8b9a-<..>/oauth2/v2.0/token' -vvv --onedrive-auth-url
"https://login.microsoftonline.com/8f5f7bf4-542e-41aa-8b9a-<..>/oauth2/v2.0/authorize" authorize onedrive -- "3e72e39d-a253-<..>" "u0t8Q~sIGN<..>"
```

May I miss a detail, but at the moment I do not understand, why I need to enter my personal credentials.

#### What is your current rclone version (output from `rclone version`)?
v1.53.3-DEV

#### How do you think rclone should be changed to solve that?
May rclone could stop asking for credentials and use given token-url with client_id and secret to fetch the access-token.

**Comment by animosity22** [comment]
You are using an ancient version so please upgrade it.

Any issues, can you post on the forums first?

https://forum.rclone.org

Thanks
