### ISSUE TITLE
Webdav: server side copy or move doesn't overwrite

### ISSUE THREAD

**Issue by WeidiDeng** [rclone/rclone#6964]
Hello, I'm using webdav to sync two folders on my webdav server. But the sync always fail with 419 precondition failed.

The two folders have files with the same name and these files are causing the problems. The server is customized golang webdav server and it reproducible using `rclone serve webdav`.

After digging the request log and reading source code. I find it's because rclone specifying the wrong `Overwrite` header [here](https://github.com/rclone/rclone/blob/master/backend/webdav/webdav.go#L1050) and [here](https://github.com/rclone/rclone/blob/master/backend/webdav/webdav.go#L1150).

Golang webdav handles this header [here](https://github.com/golang/net/blob/master/webdav/webdav.go#L373) and [here](https://github.com/golang/net/blob/master/webdav/webdav.go#L390).

**Comment by ncw** [comment]
Yes I think you are right (I double checked in the RFC). I think this should be `Overwrite: "T"`.

I'm amazed no-one noticed this before.

Do you want to send a Pull Request to fix?

**Comment by WeidiDeng** [comment]
Sure, already done in [6972](https://github.com/rclone/rclone/pull/6972).

**Comment by ncw** [comment]
Thank you.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.63

**Comment by serious-angel** [comment]
Wonderful day! ✨ 

Thank you for the marvel, art you do!

To clarify, is the following flow expected, considering the specification?:  

> If the overwrite header is not included in a COPY or MOVE request, then the resource MUST treat the request as if it has an overwrite header of value "T".  
> 
> [Source](<http://web.archive.org/web/20260524111610/http://www.webdav.org/specs/rfc4918.html#HEADER_Overwrite>) [web-archive]

---

```bash
# Let's start a great server!
rclone serve webdav -vvv '/tmp/webdav' --addr 0.0.0.0:8888 --user user --pass 12345678;
```

---

```bash
# Create the first directory - HTTP 201.
curl -vX MKCOL -u 'user:12345678' 'http://192.168.1.2:8888/dir1';
# ...
# < HTTP/1.1 201 Created
# < Accept-Ranges: bytes
# < Server: rclone/v1.74.2
# ...
# Created
```

```bash
# Create the second directory - HTTP 201.
curl -vu 'user:12345678' -X MKCOL 'http://192.168.1.2:8888/dir2';
# ...
# < HTTP/1.1 201 Created
# ...
```

```bash
# Replace the second directory with the first - HTTP 412.
curl -vX MOVE -u 'user:12345678' \
  -H 'Destination: http://192.168.1.2:8888/dir1' \
  -- 'http://192.168.1.2:8888/dir2';

# *   Trying 192.168.1.2:8888...
# * Connected to 192.168.1.2 (192.168.1.2) port 8888 (#0)
# * Server auth using Basic with user 'user'
# > MOVE /dir2 HTTP/1.1
# > Host: 192.168.1.2:8888
# > Authorization: Basic dXNlcjoxMjM0NTY3OA==
# > User-Agent: curl/7.81.0
# > Accept: */*
# > Destination: http://192.168.1.2:8888/dir1
# >
# < HTTP/1.1 412 Precondition Failed
# < Accept-Ranges: bytes
# < Server: rclone/v1.74.2
# < Date: Wed, 03 Jun 2026 01:06:16 GMT
# < Content-Length: 19
# < Content-Type: text/plain; charset=utf-8
# <
# * Connection #0 to host 192.168.1.2 left intact
# Precondition Failed
```

```bash
# Replace the second directory with the first, explicitly overwriting - HTTP 204.
curl -vX MOVE -u 'user:12345678'  \
  -H 'Overwrite: T' `# Hurray! The header! ^^` \
  -H 'Destination: http://192.168.1.2:8888/dir1' \
  -- 'http://192.168.1.2:8888/dir2';

# *   Trying 192.168.1.2:8888...
# * Connected to 192.168.1.2 (192.168.1.2) port 8888 (#0)
# * Server auth using Basic with user 'user'
# > MOVE /dir2 HTTP/1.1
# > Host: 192.168.1.2:8888
# > Authorization: Basic dXNlcjoxMjM0NTY3OA==
# > User-Agent: curl/7.81.0
# > Accept: */*
# > Overwrite: T
# > Destination: http://192.168.1.2:8888/dir1
# >
# < HTTP/1.1 204 No Content
# < Accept-Ranges: bytes
# < Server: rclone/v1.74.2
# < Date: Wed, 03 Jun 2026 01:15:25 GMT
# <
# * Connection #0 to host 192.168.1.2 left intact
```

---

May your day be successful, stable, and peaceful!

Best and kind regards

**Comment by ncw** [comment]
@serious-angel This issue is about the client however your problem looks totally valid for the server. `rclone serve webdav` appears to be ignoring  `'Overwrite: T`. Can you open a new issue with this info in please? Thanks

**Comment by serious-angel** [comment]
> Can you open a new issue...

@ncw , thank you for the response! Created:
\- #9496 (*WebDav served by Rclone prohibits overwriting, unless explicitly requested*...)
