### ISSUE TITLE
failed to open source: not an encrypted file - bad magic string

### ISSUE THREAD

**Issue by andressantamaria2003** [rclone/rclone#6974]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/failed-to-open-source-not-an-encrypted-file-bad-magic-string/37790/15

#### What is the problem you are having with rclone?

Problem when opening a file in parts with RCLONE MOUNT of dropbox

Probably this will help:
https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Downloading-part-of-a-file-via-get-temporary-link-with-Range/td-p/679372

#### What is your rclone version (output from `rclone version`)

rclone v1.62.2
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.4.0-144-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

ubuntu 20.04 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)

DROPBOX

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone mount remote: path

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

2023/04/24 20:04:44 Unsolicited response received on idle HTTP channel starting with "m\x12 RCLONE\x00\x00\xf3ޔj\xdf\x04\xc69G\x82G\xbb3\b/H\xca\xc17#\xea\x89\xd4\xec"; err=<nil>
2023/04/24 20:04:44 Unsolicited response received on idle HTTP channel starting with "m\x12 RCLONE\x00\x00s\"\x90Qܵ8\x80h\x9b\x9e\xf2\x0fݶ|4aG<\xeaOc\x9d"; err=<nil>
2023/04/24 20:04:44 Unsolicited response received on idle HTTP channel starting with "m\x12 RCLONE\x00\x00\x8e\xf1\xdf\xd0N\xc3\xda4qm\x027Į\xf2\xbe\x1d\x1f>\x0ek\xfe\xdf\x17"; err=<nil>
2023/04/24 20:04:44 ERROR : Panorama - 2023-04-07.mp4: Failed to copy: multipart copy: failed to open source: not an encrypted file - bad magic string
2023/04/24 20:04:45 ERROR : Panorama - 2023-04-08.mp4: Failed to copy: multipart copy: failed to open source: not an encrypted file - bad magic string
2023/04/24 20:04:45 ERROR : Panorama - 2023-04-10.mp4: Failed to copy: multipart copy: failed to open source: not an encrypted file - bad magic string
2023/04/24 20:04:45 Unsolicited response received on idle HTTP channel starting with "m\x12 RCLONE\x00\x00\xb6\x14\x1cb\x9f\xc8l\x05\\xz\xd8b\x7f^\xf8-B\xb8\x8a`\x06\x1a\xc4"; err=<nil>

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
This is most likely a Dropbox bug.

I found a small reproducer

`file.txt` is a small file containing `shello`

    rclone cat --offset 3 dropbox:file.txt -vv --dump bodies


```
2023/04/25 11:20:46 DEBUG : HTTP REQUEST (req 0xc0009fec00)
2023/04/25 11:20:46 DEBUG : POST /2/files/download HTTP/1.1
Host: content.dropboxapi.com
User-Agent: rclone/v1.63.0-beta.6980.470db6bcd
Content-Length: 0
Authorization: XXXX
Content-Type: application/octet-stream
Dropbox-Api-Arg: {"path":"id:qqS0afUHwS0AAAAAAA6Nig"}
Range: bytes=3-6

```

```
2023/04/25 11:20:47 DEBUG : HTTP RESPONSE (req 0xc0009fec00)
2023/04/25 11:20:47 Unsolicited response received on idle HTTP channel starting with "\"\n \n\x18application/octet-stream\x12\x04llo\n"; err=<nil>
2023/04/25 11:20:47 DEBUG : HTTP/1.1 206 Partial Content
Content-Length: 4
Accept-Encoding: identity,gzip
Accept-Ranges: bytes
Content-Range: bytes 3-6/7
Content-Security-Policy: sandbox allow-forms allow-scripts
Content-Type: application/grpc
Date: Tue, 25 Apr 2023 10:20:46 GMT
Dropbox-Api-Result: {"name": "file.txt", "path_lower": "/file.txt", "path_display": "/file.txt", "id": "id:qqS0afUHwS0AAAAAAA6Nig", "client_modified": "2022-11-09T12:59:37Z", "server_modified": "2022-11-09T12:59:41Z", "rev": "5ed093ae1400f082af73a", "size": 7, "is_downloadable": true, "content_hash": "483068e5287bde73b67923dae8c200d461d80997108030841a082e628489993b"}
Etag: W/"5ed093ae1400f082af73a"
Original-Content-Length: 4
Server: envoy
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Dropbox-Request-Id: e186d6db20684aee82e1123611632a3a
X-Dropbox-Response-Origin: far_remote
X-Robots-Tag: noindex, nofollow, noimageindex


```


The body and header appear to be mixed up somehow.

**Comment by animosity22** [comment]
Dropbox item and posted on the forums. Closing out as not a rclone issue.

https://www.dropboxforum.com/t5/Dropbox-API-Support-Feedback/Downloading-part-of-a-file-via-get-temporary-link-with-Range/m-p/679395#M30581
