### ISSUE TITLE
Error on authorizing with OneDrive Client Secret

### ISSUE THREAD

**Issue by PassionPenguin** [rclone/rclone#6978]
#### Output of `rclone version`

Installed with choco manager.

```powershell
rclone v1.62.2
- os/version: Microsoft Windows 10 Pro 21H2 (64 bit)
- os/kernel: 10.0.19044.2846 Build 19044.2846.2846 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: cmount
```

##### What was expected

Authorize the rclone application with OneDrive (for Business) with App `Client ID` + `Client Secret`

##### What was executed

*(Hide some critical credentials due to privacy protection)

```powershell
rclone authorize "onedrive" "3ae56a31-****-****-****-************" "-RY8Q~**********************************"
```

##### What was happened

```powershell
Error: unknown shorthand flag: 'R' in -RY8Q~**********************************
Usage:
  rclone authorize [flags]

Flags:
      --auth-no-open-browser   Do not automatically open auth link in default browser
  -h, --help                   help for authorize
      --template string        The path to a custom Go template for generating HTML responses

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.

2023/04/26 18:29:47 Fatal error: unknown shorthand flag: 'R' in -RY8Q~**********************************
```

---

The client-secret was generated by azure portal and was legal for sure as is shown in the attached screenshot below:

![image](https://user-images.githubusercontent.com/41184947/234551207-44bf2428-9df4-448c-b363-0c72dca124c1.png)

**Comment by animosity22** [comment]
Best to use the forums for general support.

https://forum.rclone.org

The problem you are having is authorize only takes one backend.

```
rclone authorize onedrive
```

Is what you want.

**Comment by PassionPenguin** [comment]
> Best to use the forums for general support.
> 
> https://forum.rclone.org
> 
> The problem you are having is authorize only takes one backend.
> 
> ```
> rclone authorize onedrive
> ```
> 
> Is what you want.

Sincere apology for reading a outdating blog to use the deprecated, or maybe wrong, syntax... :)
