### ISSUE TITLE
Timeout error while transferring backup.

### ISSUE THREAD

**Issue by y4sh5** [rclone/rclone#6979]
#### What is the problem you are having with rclone?

I am trying to send backup from one server to another server through FTP. But getting a timeout error. I run a bash script everyday from my server which sends backup to another server. 

#### What is your rclone version (output from `rclone version`)

rclone v1.62.2
- os/version: centos 7.9.2009 (64 bit)
- os/kernel: 3.10.0-1160.81.1.el7.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Centos 7

#### Which cloud storage system are you using? (e.g. Google Drive)

SFTP

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone copy $BACKUP_DIR/$DATE mega2:/root/$SERVER_HOSTNAME/$DATE --sftp-idle-timeout=0 >

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Please just use the forums for general support help as you'll get much better responses.

https://forum.rclone.org

A log file would be key as well so use the help and support template.
