### ISSUE TITLE
sync dropbox batch_timeout documentation with code

### ISSUE THREAD

**Issue by ak2k** [rclone/rclone#6984]
These appear to be flip-flopped in the documentation:

- https://github.com/rclone/rclone/blob/master/backend/dropbox/batcher.go#L24
>	defaultTimeoutAsync   = 10 * time.Second       // kick off the batch if nothing added for this long (ssync)
> 	defaultTimeoutSync    = 500 * time.Millisecond // kick off the batch if nothing added for this long (sync)

- https://rclone.org/dropbox/#dropbox-batch-timeout
> batch_mode: async - default batch_timeout is **500ms**
> batch_mode: sync - default batch_timeout is **10s**

**Comment by ncw** [comment]
Well spotted!

Do you want to send a pull request to fix?

If so this is the only thing which needs patching (everything else is auto generated)

https://github.com/rclone/rclone/blob/2520c05c4b40f93b197ea74fef905634647d5a9b/backend/dropbox/dropbox.go#L263-L265

**Comment by ncw** [comment]
Merged - thank you :-)
