### ISSUE TITLE
Is there an error in the functional design of sync?

### ISSUE THREAD

**Issue by Winyer** [rclone/rclone#6989]
I thought the function of sync was to synchronize A to B, keeping B consistent with A's files and directories. That is to say, when I use the sync command, if A only has one more file c than B and all other directory structures and files are the same, then only A's c will be synchronized to B. However, in reality, when I use the sync function, rclone will synchronize all A's files to B, and even if there is only one file difference between the two sides, it will all be copied again? This is strange because the data I need to synchronize has several terabytes of storage space, which greatly prolongs time and reduces work efficiency. I hope to correct it or add new synchronization commands to save time and improve production efficiency.

**Comment by ncw** [comment]
> However, in reality, when I use the sync function, rclone will synchronize all A's files to B, and even if there is only one file difference between the two sides, it will all be copied again?

This is likely a problem with your setup.

Can you open an issue on [the rclone forum](https://forum.rclone.org/) about this please and include your setup details and a log - thank you.

If it turns out this is a bug in rclone then we can create a specific actionable issue when we've worked out what it is so I'll close this one for the moment.

**Comment by Winyer** [comment]
> > However, in reality, when I use the sync function, rclone will synchronize all A's files to B, and even if there is only one file difference between the two sides, it will all be copied again?
> 
> This is likely a problem with your setup.
> 
> Can you open an issue on [the rclone forum](https://forum.rclone.org/) about this please and include your setup details and a log - thank you.
> 
> If it turns out this is a bug in rclone then we can create a specific actionable issue when we've worked out what it is so I'll close this one for the moment.

But I'm still wondering, is sync designed to synchronize the differences partially rather than all of them every time, as I would like?

**Comment by ncw** [comment]
Sync is designed to sync the differences partially. So if you sync `(a,b,c)` -> `(a,B,c)` then sync will transfer `b` only.

It does traverse the entire directory structure to work this out, but this is usually a fast operation compared to copying the files.

**Comment by Winyer** [comment]
> Sync is designed to sync the differences partially. So if you sync `(a,b,c)` -> `(a,B,c)` then sync will transfer `b` only.
> 
> It does traverse the entire directory structure to work this out, but this is usually a fast operation compared to copying the files.

copy that. thks for ur answer. xD
