### ISSUE TITLE
Unable to mount after v1.62.0

### ISSUE THREAD

**Issue by sxx1314** [rclone/rclone#6994]
#### What is the problem you are having with rclone?

rclone can be mounted with the following parameters on versions prior to v1.62.0
It mounts normally under amd64 architecture, but fails under arm64.

#### What is your rclone version (output from `rclone version`)

v1.62.0, v1.62.1, and v1.62.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Debian 11 
kernel 5.10
arm64

#### Which cloud storage system are you using? (e.g. Google Drive)
onedrive business

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone mount test: /root/test --allow-other --attr-timeout 10m --vfs-cache-mode full --vfs-cache-max-age 1200s --vfs-cache-max-size 5G --vfs-read-chunk-size-limit 100M --buffer-size 100M --daemon

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

2023/05/09 01:43:50 DEBUG : Creating backend with remote "test:"
2023/05/09 01:43:50 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2023/05/09 01:44:51 DEBUG : Daemon timed out. Terminating daemon pid 11313
2023/05/09 01:44:51 Fatal error: mount not ready

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Let me see if I'm understanding you correctly

On Debian 11 with arm64 processor `rclone mount` fails with v1.62.x but succeeds with v1.61.x? Is that right?

I tried v1.62.2 on a Hetzner VM and I could mount fine using Debian 11 and arm64.

```
$ rclone version
rclone v1.62.2
- os/version: debian 11.6 (64 bit)
- os/kernel: 5.10.0-21-arm64 (aarch64)
- os/type: linux
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.20.2
- go/linking: static
- go/tags: none
```

Did you install the `fuse3` package? This requirement changed in v1.62.x though normally it gives a more helpful error message.

**Comment by sxx1314** [comment]
> Let me see if I'm understanding you correctly
> 
> On Debian 11 with arm64 processor `rclone mount` fails with v1.62.x but succeeds with v1.61.x? Is that right?
> 
> I tried v1.62.2 on a Hetzner VM and I could mount fine using Debian 11 and arm64.
> 
> ```
> $ rclone version
> rclone v1.62.2
> - os/version: debian 11.6 (64 bit)
> - os/kernel: 5.10.0-21-arm64 (aarch64)
> - os/type: linux
> - os/arch: arm64 (ARMv8 compatible)
> - go/version: go1.20.2
> - go/linking: static
> - go/tags: none
> ```
> 
> Did you install the `fuse3` package? This requirement changed in v1.62.x though normally it gives a more helpful error message.

``` 
apt-get install fuse3 libfuse3-dev 
```
After installing fuse3, the mount works fine. Thank you

**Comment by ncw** [comment]
Great - glad that works.

Will close now.
