### ISSUE TITLE
how to make it so one s3 file copied per 30 seconds? or say just transfer 500 files per run of the command?

### ISSUE THREAD

**Issue by tooptoop4** [rclone/rclone#6995]
i am copying between 2 s3 buckets
i have sqs events auto triggered for each file being uploaded...and don't want to overload the event processor that reads these events
is there any setting that can make rclone wait 30 seconds between each file transferred? ie if i am doing copy on wildcard and there are 100 files, it should copy file1, wait 30 seconds, copy file 2, wait another 30 seconds...etc OR if it could only copy the first 50 files then exit out.

i tried these but don't seem to achieve it
```--transfers 1 --tpslimit 0.1```

byte/bandwith limits don't help as these are all tiny 50kb files

https://github.com/rclone/rclone/commit/2543278c3f21c59a831b9b62e15a1be2661e8d71 pacer minsleep seems relevant but i can't see any docs on how to use it with s3?

**Comment by ncw** [comment]
I would have thought --tpslimit would work quite well. `--tpslimit 0.1` will give 1 transaction every 10 seconds. rclone needs more than one transaction per uploaded file - exactly how many depends on quite a few things, but it probably averages 3 or 4. So setting `--tpslimit 0.1` should give you a file transferred every 30 seconds on average (roughly).

**Comment by tooptoop4** [comment]
would be great to have a flag to say exit with error after x files transferred, ie if I want it to exit after first 100 files transferred. This could prevent denial-of-service type issue when a source unexpectedly has millions of new files.

**Comment by ncw** [comment]
I think there is an issue for that: https://github.com/rclone/rclone/issues/4118

In the mean time there is

      --max-delete int               When synchronizing, limit the number of deletes (default -1)
      --max-delete-size SizeSuffix   When synchronizing, limit the total size of deletes (default off)
      --max-duration Duration        Maximum duration rclone will transfer data for (default 0s)
      --max-transfer SizeSuffix      Maximum size of data to transfer (default off)

I'm going to close this issue as it is more of a discussion than specific things that need implementing / fixing with rclone.

Discussions are best [on the rclone forum](https://forum.rclone.org/) - thanks.
