### ISSUE TITLE
The pikpak copy speed is getting slower and slower

### ISSUE THREAD

**Issue by souvenp** [rclone/rclone#7003]
#### What is the problem you are having with rclone?
The pikpak synchronous speed is getting slower and slower,15m/s at the beginning, drop to 1-2m/s after a few minutes

#### What is your rclone version (output from `rclone version`)

rclone v1.62.2-73
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.15.107+ (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: noselfupdate

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

ubuntu 20.04 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)

PIKPAK to SharePoint

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

!rclone --config=/root/.config/rclone/rclone.conf copy pikpak:Pack From Shared/2023 spp:pikpak/anime --transfers 10 --checkers 4 -v --stats-one-line --stats=5s       --buffer-size 1000M --fast-list --drive-chunk-size 128M --drive-acknowledge-abuse --drive-keep-revision-forever --onedrive-chunk-size 6400K --drive-acknowledge-abuse --drive-keep-revision-forever

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

--config=/root/.config/rclone/rclone.conf copy pikpak:Pack From Shared/2023 spp:pikpak/hanime --transfers 10 --checkers 4 -v --stats-one-line --stats=5s       --buffer-size 1000M --fast-list --drive-chunk-size 128M --drive-acknowledge-abuse --drive-keep-revision-forever --onedrive-chunk-size 6400K --drive-acknowledge-abuse --drive-keep-revision-forever
2023/05/13 19:36:18 INFO  :     2.152 MiB / 26.831 GiB, 0%, 0 B/s, ETA - (xfr#0/100)
2023/05/13 19:36:23 INFO  :    54.462 MiB / 33.331 GiB, 0%, 7.780 MiB/s, ETA 1h12m59s (xfr#1/141)
2023/05/13 19:36:28 INFO  :   149.962 MiB / 33.331 GiB, 0%, 11.454 MiB/s, ETA 49m26s (xfr#1/141)
2023/05/13 19:36:33 INFO  :   235.212 MiB / 33.331 GiB, 1%, 12.707 MiB/s, ETA 44m27s (xfr#1/141)
2023/05/13 19:36:38 INFO  :   311.962 MiB / 33.331 GiB, 1%, 13.780 MiB/s, ETA 40m54s (xfr#1/141)
2023/05/13 19:36:43 INFO  :   387.849 MiB / 33.331 GiB, 1%, 14.378 MiB/s, ETA 39m6s (xfr#1/141)
2023/05/13 19:36:48 INFO  :   467.712 MiB / 33.331 GiB, 1%, 14.995 MiB/s, ETA 37m24s (xfr#1/141)
2023/05/13 19:36:53 INFO  :   515.462 MiB / 33.331 GiB, 2%, 13.261 MiB/s, ETA 42m14s (xfr#1/141)
2023/05/13 19:36:58 INFO  :   623.462 MiB / 33.331 GiB, 2%, 15.187 MiB/s, ETA 36m46s (xfr#1/141)
2023/05/13 19:37:03 INFO  :   715.556 MiB / 33.331 GiB, 2%, 16.394 MiB/s, ETA 33m58s (xfr#1/141)
2023/05/13 19:37:08 INFO  :   822.962 MiB / 33.331 GiB, 2%, 17.404 MiB/s, ETA 31m53s (xfr#1/141)
2023/05/13 19:37:13 INFO  :   939.462 MiB / 33.331 GiB, 3%, 18.672 MiB/s, ETA 29m37s (xfr#1/141)
2023/05/13 19:37:18 INFO  :  1022.462 MiB / 33.331 GiB, 3%, 18.961 MiB/s, ETA 29m6s (xfr#1/141)
2023/05/13 19:37:23 INFO  :     1.058 GiB / 33.331 GiB, 3%, 17.054 MiB/s, ETA 32m17s (xfr#1/141)
2023/05/13 19:37:28 INFO  :     1.151 GiB / 33.331 GiB, 3%, 17.256 MiB/s, ETA 31m49s (xfr#1/141)
2023/05/13 19:37:33 INFO  :     1.245 GiB / 33.331 GiB, 4%, 17.951 MiB/s, ETA 30m30s (xfr#1/141)
2023/05/13 19:37:43 INFO  :     1.450 GiB / 32.842 GiB, 4%, 18.798 MiB/s, ETA 28m30s (xfr#2/141)
2023/05/13 19:37:48 INFO  :     1.530 GiB / 33.331 GiB, 5%, 18.450 MiB/s, ETA 29m24s (xfr#2/141)
2023/05/13 19:37:53 INFO  :     1.579 GiB / 33.331 GiB, 5%, 16.446 MiB/s, ETA 32m57s (xfr#3/141)
2023/05/13 19:37:58 INFO  :     1.649 GiB / 33.331 GiB, 5%, 16.348 MiB/s, ETA 33m4s (xfr#3/141)
2023/05/13 19:38:03 INFO  :     1.727 GiB / 33.331 GiB, 5%, 15.220 MiB/s, ETA 35m26s (xfr#3/141)
2023/05/13 19:38:08 INFO  :     1.804 GiB / 33.331 GiB, 5%, 15.561 MiB/s, ETA 34m34s (xfr#3/141)
2023/05/13 19:38:13 INFO  :     1.847 GiB / 33.054 GiB, 6%, 13.979 MiB/s, ETA 38m5s (xfr#4/141)
2023/05/13 19:38:18 INFO  :     1.899 GiB / 33.331 GiB, 6%, 13.145 MiB/s, ETA 40m48s (xfr#4/141)
2023/05/13 19:38:28 INFO  :     1.988 GiB / 33.331 GiB, 6%, 11.522 MiB/s, ETA 46m25s (xfr#5/141)
2023/05/13 19:38:33 INFO  :     2.023 GiB / 33.331 GiB, 6%, 10.174 MiB/s, ETA 52m31s (xfr#5/141)
2023/05/13 19:38:38 INFO  :     2.058 GiB / 33.331 GiB, 6%, 9.157 MiB/s, ETA 58m17s (xfr#5/141)
2023/05/13 19:38:43 INFO  :     2.092 GiB / 33.331 GiB, 6%, 8.820 MiB/s, ETA 1h26s (xfr#5/141)
2023/05/13 19:38:48 INFO  :     2.133 GiB / 33.331 GiB, 6%, 8.491 MiB/s, ETA 1h2m42s (xfr#5/141)
2023/05/13 19:39:23 INFO  :     2.240 GiB / 33.331 GiB, 7%, 3.274 MiB/s, ETA 2h42m3s (xfr#6/141)
2023/05/13 19:39:28 INFO  :     2.250 GiB / 33.331 GiB, 7%, 3.046 MiB/s, ETA 2h54m6s (xfr#6/141)
2023/05/13 19:39:33 INFO  :     2.263 GiB / 33.331 GiB, 7%, 2.893 MiB/s, ETA 3h3m16s (xfr#6/141)
2023/05/13 19:39:38 INFO  :     2.275 GiB / 33.331 GiB, 7%, 2.814 MiB/s, ETA 3h8m22s (xfr#6/141)
2023/05/13 19:39:43 INFO  :     2.286 GiB / 33.331 GiB, 7%, 2.675 MiB/s, ETA 3h18m1s (xfr#6/141)
2023/05/13 19:39:48 INFO  :     2.300 GiB / 33.331 GiB, 7%, 2.599 MiB/s, ETA 3h23m47s (xfr#6/141)
2023/05/13 19:39:53 INFO  :     2.311 GiB / 33.331 GiB, 7%, 2.573 MiB/s, ETA 3h25m44s (xfr#6/141)
2023/05/13 19:39:58 INFO  :     2.323 GiB / 33.331 GiB, 7%, 2.529 MiB/s, ETA 3h29m15s (xfr#6/141)
2023/05/13 19:40:03 INFO  :     2.336 GiB / 33.331 GiB, 7%, 2.481 MiB/s, ETA 3h33m11s (xfr#6/141)
2023/05/13 19:40:08 INFO  :     2.347 GiB / 33.331 GiB, 7%, 2.445 MiB/s, ETA 3h36m13s (xfr#6/141)
2023/05/13 19:40:13 INFO  :     2.360 GiB / 33.331 GiB, 7%, 2.442 MiB/s, ETA 3h36m27s (xfr#6/141)
2023/05/13 19:40:18 INFO  :     2.370 GiB / 33.331 GiB, 7%, 2.476 MiB/s, ETA 3h33m22s (xfr#6/141)
2023/05/13 19:40:23 INFO  :     2.384 GiB / 33.331 GiB, 7%, 2.401 MiB/s, ETA 3h39m57s (xfr#6/141)
2023/05/13 19:40:28 INFO  :     2.393 GiB / 33.331 GiB, 7%, 2.387 MiB/s, ETA 3h41m14s (xfr#6/141)
2023/05/13 19:40:33 INFO  :     2.406 GiB / 33.331 GiB, 7%, 2.399 MiB/s, ETA 3h39m58s (xfr#6/141)
2023/05/13 19:40:38 INFO  :     2.418 GiB / 33.331 GiB, 7%, 2.445 MiB/s, ETA 3h35m45s (xfr#6/141)
2023/05/13 19:40:43 INFO  :     2.431 GiB / 33.331 GiB, 7%, 2.364 MiB/s, ETA 3h43m1s (xfr#6/141)
2023/05/13 19:40:48 INFO  :     2.440 GiB / 33.331 GiB, 7%, 2.433 MiB/s, ETA 3h36m41s (xfr#6/141)
2023/05/13 19:40:53 INFO  :     2.453 GiB / 33.331 GiB, 7%, 2.357 MiB/s, ETA 3h43m37s (xfr#6/141)
2023/05/13 19:40:58 INFO  :     2.466 GiB / 33.331 GiB, 7%, 2.468 MiB/s, ETA 3h33m23s (xfr#6/141)
2023/05/13 19:41:03 INFO  :     2.478 GiB / 33.331 GiB, 7%, 2.324 MiB/s, ETA 3h46m33s (xfr#6/141)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Onedrive has quit a bite of throttling on it.

Check the forums for some help as if you run in a debug, you'll see that being the issue as there are tons of posts about it.

For any general use questions, please use the forums.

https://forum.rclone.org

**Comment by souvenp** [comment]
Solution is here!!  Restart rclone execution every few minutes

**Comment by joostshao** [comment]
rclone   --stats-one-line -P --stats 1s ls   -v --include "**-520-20230730*"  "pk:aaa/"
不对，这个不正常，延迟太高了，完全没反应，vps，在日本和东京
