### ISSUE TITLE
SFTP - Add option to use external ssh client

### ISSUE THREAD

**Issue by prettySongbird** [rclone/rclone#7012]
#### What is your current rclone version (output from `rclone version`)?

rclone v1.62.2
- os/version: arch "rolling" (64 bit)
- os/kernel: 6.3.2 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.4
- go/linking: dynamic
- go/tags: none

#### What problem are you are trying to solve?

There are currently a lot of open issues for rclone due to the use of a native ssh client in rclone that does not support many features that common SSH implementations like OpenSSH support. Examples are:  https://github.com/rclone/rclone/issues/2843 https://github.com/rclone/rclone/issues/6987 https://github.com/rclone/rclone/issues/7011 

#### How do you think rclone should be changed to solve that?

All of these issues could easily be solved by providing an option to use an external ssh command instead, e.g. using the OpenSSH client on Unix hosts. 

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
It's a package used in rclone so that would have to implement it. You'd probably want to make a downstream request.

**Comment by prettySongbird** [comment]
> I think what @prettySongbird is suggesting is that instead of using the ssh library to make the connection we shell out to the ssh binary and pipe input and output to that.

Yes, thats what I would suggest.

> 
> The sftp library is flexible enough to implement this I think (we managed to use stdin/stdout as the input for the server) so I think this is possible.
> 
> Do you want to have a go at this @prettySongbird ?

I would actually love to give it a try but I am way too busy these days to make myself familiar with the rclone code to be honest. It would probably be easy to implement this though.

**Comment by ncw** [comment]
I had a go at this. It was harder than I thought it was going to be!

Please give it a test

[v1.63.0-beta.7056.02069f065.fix-7012-sftp-external-ssh](https://beta.rclone.org/branch/fix-7012-sftp-external-ssh/v1.63.0-beta.7056.02069f065.fix-7012-sftp-external-ssh/) on branch [fix-7012-sftp-external-ssh](https://github.com/rclone/rclone/tree/fix-7012-sftp-external-ssh) (uploaded in 15-30 mins)

Here is the help for the new parameter `ssh` or `--sftp-ssh`

#### --sftp-ssh

Path and arguments to external ssh binary.

Normally rclone will use its internal ssh library to connect to the
SFTP server. However it does not implement all possible ssh options so
it may be desirable to use an external ssh binary.

Rclone ignores all the internal config if you use this option and
expects you to configure the ssh binary with the host/port and any
other options you need.

**Important** The ssh command must log in without asking for a
password so needs to be configured with keys or certificates.

Rclone will run the command supplied either with "-s sftp" to access
the SFTP subsystem or with commands such as "md5sum /path/to/file"
appended.

Any arguments with spaces in should be surrounded by "double quotes".

An example setting might be:

    ssh -o ServerAliveInterval=20 user@example.com

Note that when using an external ssh binary rclone makes a new ssh
connection for every hash it calculates.


Properties:

- Config:      ssh
- Env Var:     RCLONE_SFTP_SSH
- Type:        SpaceSepList
- Default:

**Comment by prettySongbird** [comment]
Sorry for the delay, I got around to testing the beta now.

Unfortunately I still run into issues (tested with Ubuntu 22.04)

![err](https://github.com/rclone/rclone/assets/133994075/a694a786-4b56-4e9f-8369-8612b067efc5)

**Comment by ncw** [comment]
You need to add the username and hostname to the SSH command.

Maybe rclone should do this for you, I don't know.

So

    --sftp-ssh "ssh user@host"

**Comment by prettySongbird** [comment]
Ok, that worked, using the following command:

rclone --sftp-ssh "ssh testuser@testserver.local" lsd test:/

I had expected that username and hostname from the already configured "test"connection would be used by the stfp-ssh command. Maybe the default behabior should use the variables from the connection like with the internal ssh connection.

Other then that it seems to work as intended

**Comment by ncw** [comment]
Thanks for testing @prettySongbird 

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.64

I've put a warning in if you set user/host/port as it isn't straight forward to work out how to apply all the internal arguments to the ssh binary so the user should do it themselves.

**Comment by redthing1** [comment]
Thank you so much for this patch!

**Comment by thewoz** [comment]
hello i am trying to use this feature and i am having problems.
the command i run is the follow:

 ./rclone.exe --sftp-ssh "ssh user@server" copy D:\DATA Crono:Crono/RAW

(where Crono was previously configured  as sftp via rclone.exe)

the problem is that it keeps asking me for the password.
Acting as if it were wrong (I assure it is not) if i run ssh user@server from the terminal works

--sftp-ssh is in use - ignoring user/host/port from config - set in the parameters to --sftp-ssh (remove them from the config to silence this warning)
user@server's password:
user@server's password: user@server's password: user@server's password: 2024/02/27 15:36:55 ERROR : 20231018_Vetrino_finale.tif: Failed to copy: Update ReadFrom failed: sftp: "Failure" (SSH_FX_FAILURE)

Is it not possible to configure it somehow? (the password)
Isn't there a way to configure a sftp-ssh directly from rclone.exe config

**Comment by ncw** [comment]
@thewoz - this should work. Can you [post on the rclone forum](https://forum.rclone.org/) for help please - filling in the details - thanks!

**Comment by StevenSong** [comment]
I'm trying to use rclone v1.66.0 to copy between two remote sftp servers. The target server I can setup with the usual sftp config, however the source server I need to use `--sftp-ssh` as I need to use `ProxyJump` defined in my ssh config. Independently, I can use rclone to ls on either server. However when trying to do rclone copy from source to target, `--sftp-ssh` for the source seems to be overriding the config for the target sftp server. The log pretty much says as much and I also end up with the target path on the source server. The command and output are:
```
rclone --sftp-ssh "ssh source" copy \
:sftp:/path/on/source \
target:/path/on/target
2024/03/15 17:33:05 NOTICE: Can't save config "shell_type" for on the fly backend ":sftp"
2024/03/15 17:33:05 NOTICE: target{s-FZJ}: --sftp-ssh is in use - ignoring user/host/port from config - set in the parameters to --sftp-ssh (remove them from the config to silence this warning)
2024/03/15 17:33:10 NOTICE: Can't save config "md5sum_command" for on the fly backend ":sftp"
2024/03/15 17:33:10 NOTICE: Can't save config "sha1sum_command" for on the fly backend ":sftp"
```
It might be nice if you could set the ssh command for each remote independently, I think that would fix this use case?

**Comment by ncw** [comment]
@StevenSong The way to do this is to use [connection strings](https://rclone.org/docs/#connection-strings) otherwise the `--sftp-ssh` command applies to both source and destination, so something like

```
rclone copy \
':sftp,ssh="ssh source":/path/on/source' \
target:/path/on/target
```

Some care is needed with quoting but the rules are explained in the link above.

**Comment by StevenSong** [comment]
@ncw thanks so much for the tip, that worked great
