### ISSUE TITLE
Downloading the binary from the rclone website is incredibly slow

### ISSUE THREAD

**Issue by beigexperience** [rclone/rclone#7016]
#### What is the problem you are having with rclone?
Downloading the binary from the rclone website rclone.org slash downloads is incredibly slow. 

While trying to download the installer for windows intel/amd64 the download speed is on the order of 10-40 kb/s. 

This is ridiculous.  I already downloaded the binary from the release page on github in an instant. 

#### What is your rclone version (output from `rclone version`)
N/A

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
N/A

#### Which cloud storage system are you using? (e.g. Google Drive)
N/A

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
N/A

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
N/A

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Please post items like this on the forums.

Github is for bugs/features.
