### ISSUE TITLE
backend mailru and CLI arguments '--mailru-user' and '--mailru-pass' ending with 'Can't save config "token" for on the fly backend'

### ISSUE THREAD

**Issue by sp31415t1** [rclone/rclone#7017]
#### The associated forum post URL from `https://forum.rclone.org`

none

#### What is the problem you are having with rclone?

I cannot use the mailru backend with command line arguments : '--mailru-user' and '--mailru-pass'
It's failing with : Can't save config "token" for on the fly backend
When using a backend in rclone.conf, there is no issue (and token is saved).
I don't know if it's a bug or a feature request. Maybe be there is a good reason to fail, like token cannot be only in RAM (by design).

#### What is your rclone version (output from `rclone version`)

rclone v1.62.2
- os/version: debian 12.0 (64 bit)
- os/kernel: 6.1.0-9-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Linux Debian 64bit bookworm

#### Which cloud storage system are you using? (e.g. Google Drive)

mailru

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone -vv   about :mailru:  --mailru-user "hidden@mail.ru" --mailru-pass "hidden" --mailru-speedup-enable=false

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

2023/05/20 18:43:23 DEBUG : rclone: Version "v1.62.2" starting with parameters ["rclone" "-vv" "about" ":mailru:" "--mailru-user" "sp31415_cmru17@mail.ru" "--mailru-pass" "ZrPsebqdYnnXMymhmUYLqKVcUlVPbCcQQDZQivLPOmxN9Zhx" "--mailru-speedup-enable=false"]
2023/05/20 18:43:23 DEBUG : Creating backend with remote ":mailru:"
2023/05/20 18:43:23 DEBUG : Using config file from "/home/sp31415/.config/rclone/rclone.conf"
2023/05/20 18:43:23 DEBUG : :mailru: detected overridden config - adding "{KFabd}" suffix to name
2023/05/20 18:43:23 INFO  : []: Valid token not found, authorizing.
2023/05/20 18:43:24 DEBUG : Saving config "token" in section ":mailru" of the config file
2023/05/20 18:43:24 NOTICE: Can't save config "token" for on the fly backend ":mailru"
2023/05/20 18:43:24 DEBUG : :mailru{KFabd}: Saved new token in config file
2023/05/20 18:43:24 Failed to create file system for ":mailru:": empty token found - please run "rclone config reconnect :mailru{KFabd}:"

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Tokens update so it writes to a file as it has to refresh. 

Everything is working as expected.

**Comment by sp31415t1** [comment]
Thank you for the fast answer.
Is it possible to consider my submit as a feature request, and enable token to be saved in RAM only ?
pcloud and yandex backend are also using token (long living token). It would be nice to be a similar behaviour.

Is it possible to update the documentation (https://rclone.org/mailru/) and indicate clearly the limitation ?
maybe there : https://rclone.org/mailru/#mailru-user (but I'm not sure about the best/correct location)

**Comment by sp31415t1** [comment]
Sorry to be there again.
sftp backend can produce logs below (without failure) :
2023/05/20 19:19:16 NOTICE: Can't save config "shell_type" for on the fly backend ":sftp"
2023/05/20 19:19:16 NOTICE: Can't save config "md5sum_command" for on the fly backend ":sftp"
2023/05/20 19:19:16 NOTICE: Can't save config "sha1sum_command" for on the fly backend ":sftp"

**Comment by animosity22** [comment]
You don't need a rclone.conf for non token based remotes as you can do that all via parameters.

When you have a token, most backends require oAuth and authentication and you have to provide that which gets you a refresh token.

**Comment by animosity22** [comment]
Closing as answered - any questions - feel free to ask on the forums.

https://forum.rclone.org
