### ISSUE TITLE
Very slow start of mount when using --vfs-write-back

### ISSUE THREAD

**Issue by Inrego** [rclone/rclone#7024]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/rclone-vfs-cache-mode-full-queuing-for-upload-delays-mount-time/22293

#### What is the problem you are having with rclone?
If I need to restart rclone or my server reboots while having a lot of files in the cache waiting for upload, then the mount takes a very long time. In the log, I am seeing a lot of `vfs cache: queuing for upload in 1h0m0s` for the files waiting to be uploaded. It seems like it needs to queue all the files before it will mount the directory.
Right now, since I have quite a few files waiting to be uploaded, it looks like I will have to wait several hours before the drive can be mounted again.

#### What is your rclone version (output from `rclone version`)
rclone v1.62.2
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.19.0-42-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: none

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
rclone mount gcrypt: /gmedia \
--config=/docker-volumes/rclone/rclone.conf \
--allow-other \
--attr-timeout 1000h \
--buffer-size 128M \
--dir-cache-time 5000h \
--cache-dir="/docker-volumes/rclone-cache" \
--vfs-cache-mode full \
--vfs-cache-max-size 300G \
--vfs-fast-fingerprint \
--vfs-write-back 1h \
--vfs-cache-max-age 9999h \
--log-level INFO \
--log-file /docker-volumes/rclone/logs/rclone.log \
--timeout 1h \
--umask 002 \
--user-agent inregodrive \
--allow-non-empty \
--rc
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2023/05/23 15:30:02 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/0912-erik_juul_clausen-bpm-adk.mp3: vfs cache: queuing for upload in 1h0m0s
2023/05/23 15:30:02 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/0913-erik_juul_clausen-bpm-adk.mp3: vfs cache: queuing for upload in 1h0m0s
2023/05/23 15:30:02 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/0914-erik_juul_clausen-bpm-adk.mp3: vfs cache: queuing for upload in 1h0m0s
2023/05/23 15:30:02 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/0915-erik_juul_clausen-bpm-adk.mp3: vfs cache: queuing for upload in 1h0m0s
2023/05/23 15:30:03 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/0916-erik_juul_clausen-bpm-adk.mp3: vfs cache: queuing for upload in 1h0m0s
2023/05/23 15:30:03 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/0917-erik_juul_clausen-bpm-adk.mp3: vfs cache: queuing for upload in 1h0m0s
2023/05/23 15:30:03 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/0918-erik_juul_clausen-bpm-adk.mp3: vfs cache: queuing for upload in 1h0m0s
2023/05/23 15:30:04 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/0919-erik_juul_clausen-bpm-adk.mp3: vfs cache: queuing for upload in 1h0m0s
2023/05/23 15:30:04 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/1000-erik_juul_clausen-borgen_paa_manhattan-cd10-2008-adk.m3u: vfs cache: queuing for upload in 1h0m0s
2023/05/23 15:30:04 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/1001-erik_juul_clausen-bpm-adk.mp3: vfs cache: queuing for upload in 1h0m0s
2023/05/23 15:30:05 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/1002-erik_juul_clausen-bpm-adk.mp3: vfs cache: queuing for upload in 1h0m0s
2023/05/23 15:30:05 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/1003-erik_juul_clausen-bpm-adk.mp3: vfs cache: queuing for upload in 1h0m0s
2023/05/23 15:30:05 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/1004-erik_juul_clausen-bpm-adk.mp3: vfs cache: queuing for upload in 1h0m0s
2023/05/23 15:30:06 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/1005-erik_juul_clausen-bpm-adk.mp3: vfs cache: queuing for upload in 1h0m0s
2023/05/23 15:30:06 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/1006-erik_juul_clausen-bpm-adk.mp3: vfs cache: queuing for upload in 1h0m0s
2023/05/23 15:30:06 INFO  : Audiobooks/DA/Erik Juul Clausen/Borgen På Manhattan/1007-erik_juul_clausen-bpm-adk.mp3: vfs cache: queuing for upload in 1h0m0s
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
There is already an open item for this.

It's the # of items that it has to check on startup as it has to validate data locally against the remote to validate any changes. If you have a lot of files queued up, it'll take some time.

https://github.com/rclone/rclone/issues/4595

Closing as a duplicate.
