### ISSUE TITLE
dropbox: stalling upload batcher & confusing error message

### ISSUE THREAD

**Issue by NyaMisty** [rclone/rclone#7025]
#### What is the problem you are having with rclone?

Dropbox remote will stall a transfer if an error occured during commiting batch.

Additionally, the log message is not explainative for user to debug what happened. Like the following one

```
2023/05/22 17:51:42 ERROR : Dropbox root 'naifen': sync batch commit: failed to commit batch length 1: batch commit failed:
```

#### What is your rclone version (output from `rclone version`)
v1.63.0-DEV

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Linux Debian9

#### Which cloud storage system are you using? (e.g. Google Drive)
Dropbox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone copy XXXXX dropbox-misty:

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2023/05/22 17:50:28 DEBUG : Dropbox root 'naifen': Batch idle for 500ms so committing                                                                                                                                         2023/05/22 17:50:28 DEBUG : Dropbox root 'naifen': Committing sync batch length 1 starting with: /naifen/REC/Distortion2/20230201-060233-Distortion2-Testing NEW WR Potential Any Glitchless Route Runs later.mp4
2023/05/22 17:59:15 DEBUG : pacer: low level retry 1/25 (error )
2023/05/22 17:59:15 DEBUG : pacer: Rate limited, increasing sleep to 20ms
[....]
2023/05/22 17:51:42 DEBUG : pacer: low level retry 25/25 (error )
2023/05/22 17:51:42 DEBUG : pacer: Rate limited, increasing sleep to 90.188072ms
2023/05/22 17:51:42 ERROR : Dropbox root 'naifen': sync batch commit: failed to commit batch length 1: batch commit failed:
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by NyaMisty** [comment]
I believe it's highly because dropbox server's internal error, as this happens in successive for 5 files, and then everything backed to normal.

The biggest problem is that rclone stalled several transfer, which should NEVER happen, it should either success or fail.

And, I've pinpointed the buggy code location:
1. We have a look at call to `b.commitBatch`, this code checks the error returned, but it does nothing other than reporting
      https://github.com/rclone/rclone/blob/fc798d800ceef287387a6a31be55155384904d46/backend/dropbox/batcher.go#L219
2. Inside `b.commitBatch`, it directly returned the error, without taking care of opened channel
      https://github.com/rclone/rclone/blob/fc798d800ceef287387a6a31be55155384904d46/backend/dropbox/batcher.go#L159
3. That makes `Commit` blocks forever
      https://github.com/rclone/rclone/blob/fc798d800ceef287387a6a31be55155384904d46/backend/dropbox/batcher.go#L300

**Comment by NyaMisty** [comment]
I've got these's advices:
1. inside the `commitBatch`, it should DEFINITELY reply to the chan, or everything goes evil
2. inside `Commit`, it should also look at the `ctx`, like using a select to listen to context cancellation and chan receive at the same time:
    ```
    select {
	case <-ctx.Done():
		// cancelled
		break;
	case <-resp:
		// finished
		break;
	}```

**Comment by ncw** [comment]
> I've got these's advices:
> 
> 1. inside the `commitBatch`, it should DEFINITELY reply to the chan, or everything goes evil

Agree :-)

> 2. inside `Commit`, it should also look at the `ctx`, like using a select to listen to context cancellation and chan receive at the same time:
>    ```
>    select {
>    case <-ctx.Done():
>    	// cancelled
>    	break;
>    case <-resp:
>    	// finished
>    	break;
>    }```
>    ```

Yes this is a good idea too I think. Do you want to PR this one too?

**Comment by ncw** [comment]
@NyaMisty are you going to make a further PR to fix this completely?
