### ISSUE TITLE
Data direction when using --dry-run is unclear

### ISSUE THREAD

**Issue by glibg10b** [rclone/rclone#7029]
```
$ rclone bisync . remote:university --exclude='*.{log,out,aux,toc}' --dry-run
2023/05/27 09:21:59 NOTICE: bisync is EXPERIMENTAL. Don't use in production!
2023/05/27 09:22:02 NOTICE: wtw-158/notes.rnote: Skipped copy as --dry-run is set (size 313)
2023/05/27 09:22:02 NOTICE: wtw-158/examples.rnote: Skipped copy as --dry-run is set (size 2.873Mi)
2023/05/27 09:22:03 NOTICE: ebn-111/notes.pdf: Skipped copy as --dry-run is set (size 70.623Ki)
2023/05/27 09:22:03 NOTICE: ebn-111/notes.tex: Skipped copy as --dry-run is set (size 14.479Ki)
2023/05/27 09:22:03 NOTICE: has-110/notes.pdf: Skipped copy as --dry-run is set (size 45.267Ki)
2023/05/27 09:22:03 NOTICE: has-110/notes.tex: Skipped copy as --dry-run is set (size 11.756Ki)
2023/05/27 09:22:05 NOTICE: 
Transferred:   	   3.012 MiB / 3.012 MiB, 100%, 1.503 MiB/s, ETA 0s
Checks:                 6 / 6, 100%
Transferred:            6 / 6, 100%
Elapsed time:         7.8s
```

How do I know which way the files would be copied?

```
$ rclone --version
rclone v1.61.1-DEV
- os/version: gentoo 2.13 (64 bit)
- os/kernel: 6.1.24-gentoo-dist (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.3
- go/linking: dynamic
- go/tags: none
```

**Comment by nielash** [comment]
If you add `-v` you should see this:

```
2023/07/12 08:09:36 INFO  : - Path1    Queue copy to Path2                 - /path/to/your/file.txt
2023/07/12 08:09:36 INFO  : - Path1    Do queued copies to                 - Path2
```

That said, I agree this could be improved (and it's an easy fix.)

**Comment by SatyajitR** [comment]
DEV test results
`> rclone bisync ..\hello_world\ remotemc:uni --exclude='*.{log,out,aux,toc}' --resync --dry-run
2023/10/25 08:31:07 NOTICE: bisync is EXPERIMENTAL. Don't use in production!
2023/10/25 08:31:07 NOTICE: Synching Path1 "C:\Users\gayat\projects\hello_world\" with Path2 "remotemc:uni/"
2023/10/25 08:31:08 NOTICE: main.exe: Skipped copy to main.exe as --dry-run is set (size 158.500Ki)
2023/10/25 08:31:08 NOTICE: formatted_print.exe: Skipped copy to formatted_print.exe as --dry-run is set (size 184Ki)
2023/10/25 08:31:08 NOTICE: formatted_print.pdb: Skipped copy to formatted_print.pdb as --dry-run is set (size 1.457Mi)
2023/10/25 08:31:08 NOTICE: formatted_print.rs: Skipped copy to formatted_print.rs as --dry-run is set (size 2.476Ki)
2023/10/25 08:31:08 NOTICE: main.pdb: Skipped copy to main.pdb as --dry-run is set (size 1.410Mi)
2023/10/25 08:31:08 NOTICE: main.rs: Skipped copy to main.rs as --dry-run is set (size 83)
2023/10/25 08:31:08 NOTICE:
Transferred:        3.204 MiB / 3.204 MiB, 100%, 0 B/s, ETA -
Transferred:            6 / 6, 100%
Elapsed time:         2.4s
`

**Comment by glibg10b** [comment]
Thank you for your work @nielash and @KDreynolds!
