### ISSUE TITLE
GitHub Private Vulnerability Reporting  

### ISSUE THREAD

**Issue by Sim4n6** [rclone/rclone#7032]
Hi,

I may have identified a vulnerability on the latest Codebase of rclone/rclone. Could you please, consider enabling the GitHub Private Vulnerability reporting [feature](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository)? 

Regards
@sim4n6

**Comment by animosity22** [comment]
Seems pretty straight forward to setup.

@ncw - let me know if you'd like to write up something as it has a small template to turn that on and inform folks how to report them.

**Comment by Sim4n6** [comment]
I suggest setting up a SECURITY.md file.

**Comment by animosity22** [comment]
I'm aware :) as I was asking if ncw wanted to write it up or not.

**Comment by ncw** [comment]
I enabled the feature @Sim4n6 - I'm not clear if I need a SECURITY.md for you to make a report or not though.

Yes that would be great if you want to suggest a SECURITY.md file @animosity22 . I

**Comment by Sim4n6** [comment]
I'm working on the report right away ... nothing fancy it's a medium severity vuln. Anyway I am reporting it privately tonight, feel free to close this issue please.

**Comment by darthShadow** [comment]
Closing as resolved.

**Comment by Sim4n6** [comment]
I believe this advisory needs your attention about your final ruling https://github.com/rclone/rclone/security/advisories/GHSA-884f-x559-4jm9
