### ISSUE TITLE
`rmdirs` inverts the behaviour of `--max-age` and `--min-age`

### ISSUE THREAD

**Issue by BigBrainAFK** [rclone/rclone#7034]
#### What is the problem you are having with rclone?

Rclones `rmdirs` inverts the behaviour of `--max-age` and `--min-age` relative to the `delete` command

#### What is your rclone version (output from `rclone version`)

`rclone v1.62.2`
`rclone v1.63.0-beta.7045.ceb9406c2`
`rclone v1.63.0-beta.7054.51a468b2b`

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

```
- os/version: debian 11.7 (64 bit)
- os/kernel: 5.10.0-21-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.4
- go/linking: static
- go/tags: none
```

#### Which cloud storage system are you using? (e.g. Google Drive)

GDrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone rmdirs --min-age 3d Backup:/`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

[RMDIRS Min-Age Log](https://gist.github.com/BigBrainAFK/678ea0efb41520511e1d38b1381239d1)
[RMDIRS Max-Age Log](https://gist.github.com/BigBrainAFK/ad8a19d14aa6acfd7f6ef853a6ea79b3)

[DELETE Min-Age Log](https://gist.github.com/BigBrainAFK/683f4540544a06741ed444bba079671d)
[DELETE Max-Age Log](https://gist.github.com/BigBrainAFK/b3bc7a104f08523073defc0264ac9d26)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by BigBrainAFK** [comment]
> What were you hoping `--min-age` and `--max-age` would do with `rclone rmdirs`?
> 
> `--min-age` and `--max-age` applies to files only so will do nothing with `rclone rmdirs`.

Well evidentally it does something. I mainly hoped it could clean up empty folders older than age X (in my example 3days)

**Comment by BigBrainAFK** [comment]
Oh that makes sense ok. So i guess the best plan is to delete all files in the remote older than date X and then just `rmdir` to delete all the empty once. I assume rmdir doesnt touch non empty directories.

**Comment by ncw** [comment]
> Oh that makes sense ok. So i guess the best plan is to delete all files in the remote older than date X and then just `rmdir` to delete all the empty once. I assume rmdir doesnt touch non empty directories.

Yes deal with the files.

You can use `rclone rmdirs` to recursively remove empty directories which might be useful here.

I'm going to close this now since I don't think it is a bug in rclone.
