### ISSUE TITLE
can't get the google drive token

### ISSUE THREAD

**Issue by kkz12156** [rclone/rclone#7036]
2023/05/31 05:07:31 Fatal error: failed to get token: Post "https://oauth2.googleapis.com/token": EOF   
Report an error in the last step 
But the webpage pop -up during the setting prompted me:
Success!

All done. Please go back to rclone.
What can I do to let the program run normally?  please help me,tks

**Comment by animosity22** [comment]
Please post on the forums.

https://forum.rclone.org

Use the help and support template and fill it all out.
