### ISSUE TITLE
Drain uploads before canceling

### ISSUE THREAD

**Issue by SimplicityGuy** [rclone/rclone#7040]
#### The associated forum post URL from `https://forum.rclone.org`
(not posted)

#### What is your current rclone version (output from `rclone version`)?
1.62.2

#### What problem are you are trying to solve?
When canceling uploads to start a new rclone job, it would be nice to have the option to first drain all active/in-progress uploads before canceling.

#### How do you think rclone should be changed to solve that?
This could be solved in a few different ways. For instance:
- create an `RCLONE_DRAIN` environment variable, and if set will first wait and drain upon a `Ctrl-C` signal
- add ability for rclone to read input during upload, for instance, `d` would mean drain, and `q` can mean cancel/quit; in fact, this can be sort of an interactive shell during uploads for other commands too like forcing a rescan, changing number of concurrent uploads, enabling throttling, etc. HOWEVER, I understand that doing this is a much bigger feature, hence I feel the first suggestion is a smaller enhancement.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I think you are asking for a graceful way of quitting rclone which completes the current uploads and then quits. Is that right?

If so this is a duplicate of https://github.com/rclone/rclone/issues/1522

Recently I posted a potential workaround for this using the rclone API on that issue

https://github.com/rclone/rclone/issues/1522#issuecomment-1568476914

**Comment by SimplicityGuy** [comment]
Indeed. I’ll close this one out in favor of #1522
