### ISSUE TITLE
Unexpected High Data Traffic Calculation in Premiumize.me when using rclone sftp package

### ISSUE THREAD

**Issue by metaconnectdotio** [rclone/rclone#7041]
I would like to report a bug related to the rclone package (rclone/rclone) when accessing Premiumize.me using the sftp feature. It appears that when I download files from the rclone server, a significantly larger amount of data traffic is being calculated by Premiumize.me than what is actually being downloaded to my client. This issue results in an inaccurate data transfer calculation, with a ratio of approximately 1:4 between the data displayed in rclone and Premiumize.me.

### Steps to Reproduce

1.    Install rclone version v1.62.2.
2.    Run the following command: `rclone serve sftp --auth-proxy proxy.py --addr 0.0.0.0:22 --vfs-cache-mode writes`.
3.    Connect to the rclone sftp server using your client.
4.    Download files from the rclone server.

Observe the data transfer calculation on Premiumize.me and compare it with the transfer shown in rclone.

### Expected Behavior

The data transfer calculation in Premiumize.me should match the actual data downloaded through the rclone sftp server, resulting in an accurate representation of the transferred data.

### Actual Behavior

The data traffic calculated by Premiumize.me is significantly higher than the data transferred as reported by rclone. For example, while rclone shows 1636MB transferred, Premiumize.me displays 6.58GB transferred. This discrepancy indicates a substantial difference, with a ratio of approximately 1:4 between the two measurements.

### Additional Information

I have tested and confirmed that regular downloads from the website without using the sftp server result in correct traffic calculation.

I would appreciate it if the development team could investigate this issue and provide any guidance or potential fixes. If further information or logs are required, please let me know, and I will be happy to provide them.

**Comment by ncw** [comment]
> I would like to report a bug related to the rclone package (rclone/rclone) when accessing Premiumize.me using the sftp feature.

Why not use the `premiumizeme` backend?

Can you post
- a redacted copy of your rclone config
- a log from `rclone serve -vv` showing a transfer that has the problem
- the command line you are using to copy the data from the `rclone serve`

Thank you

**Comment by animosity22** [comment]
Closing as no response for more than 30 days. If you want to update with new information, please update the issue and I can open it back up.

Thanks.
