### ISSUE TITLE
rclone is causing struck our servers, we are using rclone 1.53.1 version.

### ISSUE THREAD

**Issue by shivaji8056** [rclone/rclone#7049]
Wed May 31 00:03:20 2023] INFO: task rclone:61704 blocked for more than 120 seconds.
[Wed May 31 00:03:20 2023]       Not tainted 4.18.0-477.10.1.el8_8.x86_64 #1
[Wed May 31 00:03:20 2023] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[Wed May 31 00:03:20 2023] task:rclone          state:D stack:    0 pid:61704 ppid: 61703 flags:0x00000084
[Wed May 31 00:03:20 2023] Call Trace:
[Wed May 31 00:03:20 2023]  __schedule+0xversion2d1/0x870
[Wed May 31 00:03:20 2023]  schedule+0x55/0xf0
[Wed May 31 00:03:20 2023]  io_schedule+0x12/0x40
[Wed May 31 00:03:20 2023]  migration_entry_wait_on_locked+0x1ea/0x290
[Wed May 31 00:03:20 2023]  ? filemap_map_pages+0x271/0x410
[Wed May 31 00:03:20 2023]  ? filemap_fdatawait_keep_errors+0x50/0x50
[Wed May 31 00:03:20 2023]  do_swap_page+0x5b0/0x710
[Wed May 31 00:03:20 2023]  ? pmd_devmap_trans_unstable+0x2e/0x40please 
[Wed May 31 00:03:20 2023]  ? handle_pte_fault+0x5d/0x880
[Wed May 31 00:03:20 2023]  __handle_mm_fault+0x453/0x6c0
[Wed May 31 00:03:20 2023]  handle_mm_fault+0xca/0x2a0
[Wed May 31 00:03:20 2023]  __do_page_fault+0x1f0/0x450
[Wed May 31 00:03:20 2023]  do_page_fault+0x37/0x130
[Wed May 31 00:03:20 2023]  ? page_fault+0x8/0x30
[Wed May 31 00:03:20 2023]  page_fault+0x1e/0x30
[Wed May 31 00:03:20 2023] RIP: 0033:0x4030b0
[Wed May 31 00:03:20 2023] Code: Unable to access opcode bytes at RIP 0x403086.
[Wed May 31 00:03:20 2023] RSP: 002b:000000c00063fb20 EFLAGS: 00010202
[Wed May 31 00:03:20 2023] RAX: 0000000000000400 RBX: 00000000000004e1 RCX: 0000000002733b1f
[Wed May 31 00:03:20 2023] RDX: 0000000000000031 RSI: 0000000002733b1f RDI: 0000000000000020
[Wed May 31 00:03:20 2023] RBP: 000000c00063fb70 R08: 000000c00063fb40 R09: 0000000002613dda
[Wed May 31 00:03:20 2023] R10: 000000000080417a R11: 0000000002733fe0 R12: 0000000000134ec4
[Wed May 31 00:03:20 2023] R13: 0000000000000000 R14: 0000000001d0be50 R15: 0000000000000000

**Comment by shivaji8056** [comment]
Could you please help me on this issue.

**Comment by ncw** [comment]
Please retry with the latest version 1.62.2 and if it doesn't work post on forum.rclone.org and fill in all the details in the template.

Thanks
