### ISSUE TITLE
chunker - broken or intended?

### ISSUE THREAD

**Issue by choin1** [rclone/rclone#7052]
#### What is the problem you are having with rclone?

While looking for a workaround for my issue with a certain host (assume connection issues, probably), I've been trying using chunker.
Discovered the following behavior:
- no matter what, a big file (>5GB) transfer fails somewhere at 95% in most cases. For the purpose of this issue, assume this is normal.
- files smaller than 1 GB transfer fine in most cases.
- when configured to use chunker with chunks smaller than 1 GB, the transfer still fails, somewhere between 50%-100% (of a current file) in most cases.
- all chunks that were uploaded for a failed file get deleted from cloud by rclone. Then rclone may try to start uploading the file again from scratch.

I assumed that all chunks that were successfully uploaded will remain on cloud and rclone would only retry uploading unsuccessful chunks individually.

Is this assumption wrong?

#### What is your rclone version (output from `rclone version`)
1.62.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 7/8 64-bit

#### Which cloud storage system are you using? (e.g. Google Drive)
yandex

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone copy -vv --dump responses --contimeout 10m "X:\5Gfile" yandex-chunker:folder --log-file rclone.log`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
The log is very long, here is a fragment.
```
2023/06/12 16:15:51 INFO  : 
Transferred:   	   12.454 GiB / 14.021 GiB, 89%, 1.465 MiB/s, ETA 18m14s
Transferred:            0 / 1, 0%
Elapsed time:      32m0.3s
Transferring:
*                                         5Gfile: 74% /6.086Gi, 1.447Mi/s, 18m28s

2023/06/12 16:15:54 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2023/06/12 16:15:54 DEBUG : HTTP RESPONSE (req 0xc0007b2000)
2023/06/12 16:15:54 DEBUG : Error: write tcp *:11428->*:443: wsasend: An existing connection was forcibly closed by the remote host.
2023/06/12 16:15:54 DEBUG : <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2023/06/12 16:15:54 DEBUG : pacer: low level retry 1/1 (error Put "https://uploader2o.disk.yandex.net:443/upload-target/*": write tcp *:11428->*:443: wsasend: An existing connection was forcibly closed by the remote host.)
2023/06/12 16:15:54 DEBUG : pacer: Rate limited, increasing sleep to 20ms
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> * when configured to use chunker with chunks smaller than 1 GB, the transfer still fails, somewhere between 50%-100% (of a current file) in most cases.

> wsasend: An existing connection was forcibly closed by the remote host.


I suspect this might be your ISP chopping the connection after 5 GB of transfer down one HTTP connection. By default rclone will be re-using the same HTTP connection for each chunk most likely.

We can force rclone not to re-use HTTP sessions which might help with `--disable-http-keep-alives`

This will ensure each chunk gets transferred in a different HTTP connection and hopefully your ISP will be good with that.

**Comment by choin1** [comment]
This flag doesn't change anything according to the log file.

I didn't find the real "limit" of whatever might be going on, but it's clearly lower than 5 GB. I had issues with files as small as 1.5 GB or so.

**Comment by choin1** [comment]
Here is the full log after uploading 1 file, ~6 GB in size, in 512 MB chunks.
[rclone-chunker.log](https://github.com/rclone/rclone/files/11800393/rclone-chunker.log)

The result of the operation:
- It was successful.
- It took 3 hours on 100 Mbps connection.
- 72 GB were wasted on 144 chunks that are seen in the cloud drive recycle bin.
- 1 chunk has been successfully uploaded and exists in 6 flavors in the cloud folder:

![image](https://github.com/rclone/rclone/assets/135684603/34572c6d-99d1-4709-b0a5-49bbc720f633)

**Comment by choin1** [comment]
Can someone answer the question? Is chunker supposed to discover chunks uploaded before interruption?

**Comment by ncw** [comment]
> Can someone answer the question? Is chunker supposed to discover chunks uploaded before interruption?

I don't think it does. They should probably be cleaned up but I don't think chunker does that either.

**Comment by choin1** [comment]
So if someone wants to upload a 100 GB file in chunks, rclone expects the 100 GB transfer to not be interrupted at all for success? I don't think this makes sense.
Is there any chance for this to be properly fixed?

**Comment by animosity22** [comment]
Yes, that's logged here:

https://github.com/rclone/rclone/issues/5154

Feel free to submit a PR to fix it or sponsor someone else to fix or rope a friend into fixing it :)

**Comment by kapitainsky** [comment]
To clean chunks from interrupted transfers you have to use manual method:

https://forum.rclone.org/t/chunker-remote-how-to-clean-orphaned-chunks/40070

Otherwise they will stay forever in your cloud storage.
