### ISSUE TITLE
Current rclone version in epel 9 repo planned?

### ISSUE THREAD

**Issue by mikch06** [rclone/rclone#7054]
Is there a plan to put a current rclone version to epel9 repo in the near future?

Thx in advance
mik

**Comment by kapitainsky** [comment]
wouldn't it be up to epel9 maintainers?

**Comment by mikch06** [comment]
Don't know who should push it. But there current version is a late 2021.

**Comment by animosity22** [comment]
Any repo is maintained by the repo owner so you'd have to ask them in this case as we don't recommend any repos and the install should be done via the install instructions.

For general questions, please use the forums.

https://forum.rclone.org
