### ISSUE TITLE
No verbose INFO message when creating empty directories

### ISSUE THREAD

**Issue by benasocj** [rclone/rclone#7068]
#### What is the problem you are having with rclone?
When using `rsync -v -n sync --create-empty-src-dirs` I'm told that an empty directory would've been created:
```
~% rclone -v -n sync --create-empty-src-dirs nc:foo bar -n
<5>NOTICE: dir1: Skipped make directory as --dry-run is set
<6>INFO  : There was nothing to transfer
<5>NOTICE:
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Checks:                 1 / 1, 100%
Elapsed time:         1.9s
```
However, when removing the `-n` flag, the empty directory is created but I'm no longer told about it:
```
~% ls bar
~% rclone -v sync --create-empty-src-dirs nc:foo bar
<6>INFO  : There was nothing to transfer
<6>INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Checks:                 1 / 1, 100%
Elapsed time:         2.4s
~% ls bar
dir1
~%
```

#### What is your rclone version (output from `rclone version`)
v1.62.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Linux

#### Which cloud storage system are you using? (e.g. Google Drive)
Nextcloud

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
~% rclone -vv sync --create-empty-src-dirs nc:foo bar
<7>DEBUG : rclone: Version "v1.62.2" starting with parameters ["rclone" "-vv" "sync" "--create-empty-src-dirs" "nc:foo" "bar"]
<7>DEBUG : rclone: systemd logging support activated
<7>DEBUG : Creating backend with remote "nc:foo"
<7>DEBUG : Using config file from "/home/user1/.config/rclone/rclone.conf"
<7>DEBUG : found headers:
<7>DEBUG : Creating backend with remote "bar"
<7>DEBUG : Local file system at bar: Waiting for checks to finish
<7>DEBUG : Local file system at bar: Waiting for transfers to finish
<7>DEBUG : dir1: Making directory
<7>DEBUG : Local file system at bar: copied 1 directories
<7>DEBUG : Waiting for deletions to finish
<6>INFO  : There was nothing to transfer
<6>INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Checks:                 1 / 1, 100%
Elapsed time:         2.3s
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Rclone works on files generally so a directory won't show up as that's expected.

Any questions, feel free to post on the forums.

https://forum.rclone.org
