### ISSUE TITLE
rclone mount smb server and can't upload anything

### ISSUE THREAD

**Issue by CCCAUCHY** [rclone/rclone#7070]
#### What is the problem you are having with rclone?
rclone mount smb server and can't upload anything, the error is , but rclone copy or move command can. So I think my smb server is OK.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.62.2
- os/version: Microsoft Windows 10 Home 22H2 (64 bit)
- os/kernel: 10.0.19045.3086 Build 19045.3086.3086 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: cmount
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 10, 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
[smb server on Android](https://apkpure.com/cn/smb-samba-server/alsultan.smbserver)

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`.\rclone.exe mount smb:/MainStorage/tmp D:\nas\smb  --debug-fuse`, then cannot upload anything by explore.exe
`.\rclone.exe copy D:\nas\ smb:/MainStorage/tmp` is OK
```
 .\rclone.exe about smb:/MainStorage/tmp
Total:   0 B
Used:    0 B
Free:    0 B
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
log:
```
rclone[TID=0d1c]: FFFFCD8A7E9718B0: <<Create IoStatus=0[1] UserContext=0000000000000000:00000000037A6620, GrantedAccess=100080, FileInfo={FileAttributes=10, ReparseTag=0, AllocationSize=0:0, FileSize=0:0, CreationTime=2023-06-20T09:13:33.538Z, LastAccessTime=2023-06-20T09:13:33.538Z, LastWriteTime=2023-06-20T09:13:33.538Z, ChangeTime=2023-06-20T09:13:33.538Z, IndexNumber=0:1}
rclone[TID=0d1c]: FFFFCD8A7E970040: >>Close 0000000000000000:00000000037A6620
rclone[TID=0d1c]: FFFFCD8A7E970040: <<Close IoStatus=0[0]
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> `.\rclone.exe mount smb:/MainStorage/tmp D:\nas\smb --debug-fuse`, then cannot upload anything by explore.exe `.\rclone.exe copy D:\nas\ smb:/MainStorage/tmp` is OK

This indicated a permissions problem with the rclone mount I think.

Please can you ask on [post on the rclone forum](https://forum.rclone.org/) about this and you will find lots of knowlegeable windows users there.

I'll close this for now but if we find it is an rclone bug I can reopen it.
