### ISSUE TITLE
I use rclone remote control API (https://rclone.org/rc/), sometimes meet error

### ISSUE THREAD

**Issue by schunlee** [rclone/rclone#7086]
rclone version be: 
rclone v1.62.2
- os/version: ubuntu 18.04 (64 bit)
- os/kernel: 5.3.0-1029-gcp (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: none

I use rclone remote control API to sync files, but sometimes will meet error as below:
    `2023/06/27 16:13:55 ERROR : body/hair_fornt/3_1.png: Failed to copy: Post "https://pod-000-1123-06.backblaze.com/b2api/v1/b2_upload_file/4ebce96217cffaba7f3a0e10/c002_v0001123_t0020": context canceled
2023/06/27 16:13:55 ERROR : body/hair_back_1/4_6.png: Failed to copy: Post "https://pod-000-1127-02.backblaze.com/b2api/v1/b2_upload_file/4ebce96217cffaba7f3a0e10/c002_v0001127_t0018": context canceled
2023/06/27 16:13:55 ERROR : rc: "sync/copy": error: Post "https://pod-000-1127-02.backblaze.com/b2api/v1/b2_upload_file/4ebce96217cffaba7f3a0e10/c002_v0001127_t0018": context canceled`

failed to open source object: RequestCanceled: request context canceled caused by: context canceled

**Comment by ncw** [comment]
I would guess the operation is timing out.

How long is it taking?

Investigate the [_async flag](https://rclone.org/rc/#running-asynchronous-jobs-with-async-true)

**Comment by schunlee** [comment]
task will last about 4 mins, less than 10 mins.
I use nginx as proxy to expose the service, does something on my client-proxy-timeout ?

and I not set _async true, if set true, I have to  requestly do job/status request, if I missed, I will get job not found response, I cannot know the status of my remote syncing result.

**Comment by animosity22** [comment]
Your best bet would be to post on the forums for general support.

Use the help and support template. 

Fill it out completely.

Thanks

https://forum.rclone.org
