### ISSUE TITLE
Example of a systemd templete for rclone serve in wiki ?

### ISSUE THREAD

**Issue by khurshid-alam** [rclone/rclone#7092]
Rclone has a nice systemd template for [rclone mount](https://github.com/rclone/rclone/wiki/Systemd-rclone-mount). It would be nice to have systemd template for server as well. 

So that I can just modify backend parameters (webdav, sftp, http etc) in `~/.config/rclone/rclone-serve-webdav.env` an be done with it.

Thanks. 

#### What is your current rclone version (output from `rclone version`)?
$ rclone -V
rclone v1.62.2
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.4.0-18-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.2
- go/linking: static
- go/tags: none

**Comment by animosity22** [comment]
Feel free to submit a PR to adjust and/or add anything you'd like.

For discussion, feel free on the forums.

https://forum.rclone.org
