### ISSUE TITLE
Feature request: rc api new field `execute_id` on `job/list`

### ISSUE THREAD

**Issue by yuudi** [rclone/rclone#7095]
#### The associated forum post URL from `https://forum.rclone.org`

N/A

#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.62.2
```

#### What problem are you are trying to solve?

A GUI frontend display backend jobs

#### How do you think rclone should be changed to solve that?

Currently we have rc api `job/list` to list backend jobs, but because user may restart backend or frontend at anytime, frontend cannot track job by `job_id` because it starts counting from `1` on every restart, so we need a new field to help track the job.

I thinks a new field `execute_id` would help. It will be generated on every restart and not changed during running. Frontend will know the `job_id` is no longer used when detect `execute_id` changes.

I will make a pull request on this later.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
We could just start with a random number for job id?

**Comment by yuudi** [comment]
> We could just start with a random number for job id?

This seems vague for frontend to check if backend has restarted. Frontend may not want to check if a new job-id is in range `(previous, previous + 10000)`.

So, I think a new field that use random number would be better.

**Comment by yuudi** [comment]
Thanks for merging #7096
