### ISSUE TITLE
Feature request: rc - increase async_  jobs expiry time

### ISSUE THREAD

**Issue by kapitainsky** [rclone/rclone#7098]
At the moment rc async jobs can be queried for up to 1 minute after they have finished. It requires very frequent `job/status` runs to make sure that jobs' results are not missed. 

I would like to suggest to increase existing 60s expiry to something more reasonable like 5 or even 10 min.

I am happy to create PR myself but would like to check first whether it won't break any rc design logic or create unforeseen issues.

**Comment by yuudi** [comment]
I think there is an option `--rc-job-expire-duration` allow you increase expire time ([docs](https://rclone.org/rc/#rc-job-expire-duration-duration))

**Comment by kapitainsky** [comment]
> I think there is an option `--rc-job-expire-duration` allow you increase expire time ([docs](https://rclone.org/rc/#rc-job-expire-duration-duration))

Brilliant! Thank you. Not sure how I missed it.
