### ISSUE TITLE
rclone does not produce expected result that only matches the given regex filters from a recursive listing command

### ISSUE THREAD

**Issue by ylorn** [rclone/rclone#7106]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/list-pattern-matched-dirs-only-from-the-recursive-result/39477/3

#### What is the problem you are having with rclone?

The `rclone ls[f|d] --recursive` command produces results that does not match the given regex pattern.

Take following dir structure as an example

```
test/
├── _A_
│   └── _a
│       └── a
├── _B_
│   └── b_
│       └── b
└── _C_
    └── _c_
        └── c
```

When running `rclone lsf g:test --dirs-only --recursive --fast-list`, this is the raw result:

```
_B_/
_A_/
_C_/
_B_/b_/
_A_/_a/
_C_/_c_/
```

Now I want to only list folders/subfolders that are surrounded by `_`, which means only following should be included:

```
_B_/
_A_/
_C_/
_C_/_c_/
```

The regex I intend to use is `^(_[^\/]+?_\/)+$`, which works fine on https://regex101.com with expected 4 matches:

<img width="273" alt="Screenshot 2023-07-01 at 3 06 15 PM" src="https://github.com/rclone/rclone/assets/1502810/9ec0ad13-e027-4193-aa99-f633fbb416bf">

As per rclone's [docs](https://rclone.org/filtering/#regexp):

> Here is how the `{{regexp}}` is transformed into an full regular expression to match the entire path:
> `/{{regexp}}` becomes `^(regexp)$`

I come up with the filter `--include="/{{(_[^/]+?_\/)+}}"` with `^` and `$` stripped to adapt to the transformation.

But it still gives me the unfiltered result:

```bash
❯ rclone lsf g:test --dirs-only --recursive --fast-list --include="/{{(_[^\/]+?_\/)+}}"
_B_/
_A_/
_C_/
_C_/_c_/
_B_/b_/
_A_/_a/
```

#### What is your rclone version (output from `rclone version`)

```bash
❯ rclone version
rclone v1.62.2
- os/version: arch (64 bit)
- os/kernel: 6.3.7-arch1-1 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.4
- go/linking: dynamic
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

```bash
❯ hostnamectl
 Static hostname: archlinux-latest-64-minimal
       Icon name: computer-desktop
         Chassis: desktop 🖥
      Machine ID: d9085dae32e3464a9da86d0544ae8c61
         Boot ID: b8cca2dbf20d478a9d5c34f9c4deca1e
Operating System: Arch Linux
          Kernel: Linux 6.3.7-arch1-1
    Architecture: x86-64
Firmware Version: H4.84
```

#### Which cloud storage system are you using? (e.g. Google Drive)

- Google Drive
- Dropbox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```bash
rclone lsf g:test --dirs-only --recursive --fast-list --include="/{{(_[^\/]+?_\/)+}}"
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
N/A

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
It's not supposed to work on directories as the filtering is built for files to my knowledge.

```
[felix@gemini test]$ rclone lsf /home/felix/test --dirs-only --recursive --fast-list --include="/{{(_[^\/]+?_\/)+}}" --dump filters
2023/07/01 15:22:42 NOTICE: Automatically setting -vv as --dump is enabled
2023/07/01 15:22:42 INFO  : Can't figure out directory filters from "/{{(_[^\\/]+?_\\/)+}}": looking in all directories
--- start filters ---
--- File filter rules ---
+ ^((_[^\/]+?_\/)+)$
- ^.*$
--- Directory filter rules ---
+ ^.*$
- ^.*$
--- end filters ---
2023/07/01 15:22:42 DEBUG : rclone: Version "v1.63.0" starting with parameters ["rclone" "lsf" "/home/felix/test" "--dirs-only" "--recursive" "--fast-list" "--include=/{{(_[^\\/]+?_\\/)+}}" "--dump" "filters"]
2023/07/01 15:22:42 DEBUG : Creating backend with remote "/home/felix/test"
2023/07/01 15:22:42 DEBUG : Using config file from "/opt/rclone/rclone.conf"
_A_/
_B_/
_C_/
_C_/_c_/
_B_/b_/
_A_/_a/
2023/07/01 15:22:42 DEBUG : 4 go routines active
```

**Comment by kapitainsky** [comment]
I think it is very interesting question. I know that probably not many people use regexp in their filters but it is opportunity to clarify its implementation in rclone. 

@animosity22 pointed to https://pkg.go.dev/regexp/syntax used by rclone - which on the first look seems perfectly OK and just follow Perl ideology. 

Regexp for anybody who used them across platforms and programming languages are sometimes can of warms. Not expecting many people commenting on this issue but it is one which even not mass market would be nice to make clear.

**Comment by ylorn** [comment]
> It's not supposed to work on directories as the filtering is built for files to my knowledge.
> 
> ```
> [felix@gemini test]$ rclone lsf /home/felix/test --dirs-only --recursive --fast-list --include="/{{(_[^\/]+?_\/)+}}" --dump filters
> 2023/07/01 15:22:42 NOTICE: Automatically setting -vv as --dump is enabled
> 2023/07/01 15:22:42 INFO  : Can't figure out directory filters from "/{{(_[^\\/]+?_\\/)+}}": looking in all directories
> --- start filters ---
> --- File filter rules ---
> + ^((_[^\/]+?_\/)+)$
> - ^.*$
> --- Directory filter rules ---
> + ^.*$
> - ^.*$
> --- end filters ---
> 2023/07/01 15:22:42 DEBUG : rclone: Version "v1.63.0" starting with parameters ["rclone" "lsf" "/home/felix/test" "--dirs-only" "--recursive" "--fast-list" "--include=/{{(_[^\\/]+?_\\/)+}}" "--dump" "filters"]
> 2023/07/01 15:22:42 DEBUG : Creating backend with remote "/home/felix/test"
> 2023/07/01 15:22:42 DEBUG : Using config file from "/opt/rclone/rclone.conf"
> _A_/
> _B_/
> _C_/
> _C_/_c_/
> _B_/b_/
> _A_/_a/
> 2023/07/01 15:22:42 DEBUG : 4 go routines active
> ```

Removing the `--dirs-only` is fine with me, I am just using dirs to demonstrate the issue. But even without that flag the result still is not expected:

raw listing without any filters:
```bash
❯ rclone lsf g:test --recursive --fast-list
_B_/
_A_/
_C_/
_C_/_c_/
_B_/b_/
_A_/_a/
_C_/_c_/c
_B_/b_/b
_A_/_a/a
```

adding regex filter `--include="/{{(_[^/]+?_/)+}}"`:

```bash
❯ rclone lsf g:test --recursive --fast-list --include="/{{(_[^/]+?_/)+}}"
_B_/
_A_/
_C_/
_B_/b_/
_C_/_c_/
_A_/_a/
```

**Comment by animosity22** [comment]
As noted in the docs, rclone doesn't imply directory filters with patterns.

When using pattern list syntax, if a pattern item contains either / or **, then rclone will not able to imply a directory filter rule from this pattern list.

**Comment by ylorn** [comment]
> @animosity22 pointed to https://pkg.go.dev/regexp/syntax used by rclone - which on the first look seems perfectly OK and just follow Perl ideology.

Right, I didn't see anything in my regex is not included in the mentioned link.

**Comment by animosity22** [comment]
We can continue this on the forums, this is a documented item in the filtering page:

https://rclone.org/filtering/#directory_filter

If there are suggestions on improving documentation, please feel free to submit a PR.

Thanks.

**Comment by ylorn** [comment]
I figured out the problem, the filters we tried is not recognized as directory filters, hence not applied. 

As per [doc](https://rclone.org/filtering/#directory_filter): 
> Directory filter rules are defined with a closing / separator.

So we have to surround our regex filters with `/` at the outmost layer as `/{{.*}}/` to be recognized by rclone.

As a result, we need to compose the filter like this: `--include="/{{(_[^\/]+_\/?)+}}/"` so that rclone can add it to the directory filters:

```bash
2023/07/01 22:03:36 NOTICE: Automatically setting -vv as --dump is enabled
--- start filters ---
--- File filter rules ---
- ^.*$
--- Directory filter rules ---
+ ^((_[^\/]+_\/?)+)/$
- ^.*$
--- end filters ---
```

Therefore, the following command will give us the correct result:

```bash
❯ rclone lsf g:test --dirs-only --recursive --fast-list --include="/{{(_[^\/]+_\/?)+}}/"    _A_/
_B_/
_C_/
_C_/_c_/
```
