### ISSUE TITLE
How to achieve continuous synchronization

### ISSUE THREAD

**Issue by shyding** [rclone/rclone#7111]
#### What problem are you are trying to solve?

Given a source folder and a target folder, changes in the source folder will be synchronized to the target folder in real time

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Please don't post questions here.

Please use the forums.


https://forum.rclone.org
