### ISSUE TITLE
v.1.63.0 regression on command "rclone config reconnect <theRemoteName>:"

### ISSUE THREAD

**Issue by minnieshi** [rclone/rclone#7114]
#### What is the problem you are having with rclone?
after 30th June, the release v1.63.0 is out. our rclone command stops working and below is the comparision for the command.
error message
```
Error: failed to configure token with jwt authentication: jwtutil: failed making auth request: 400 Bad Request
```

#### What is your rclone version (output from `rclone version`)
v1.63.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
linux

#### Which cloud storage system are you using? (e.g. Google Drive)
Box

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
rclone -vv config reconnect source_box:
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
**Below is the older version example, run on Mac, but it worked for linux too**

```
2023/07/03 17:43:20 DEBUG : Setting default for box-box-config-file="/Users/blahblah/.config/rclone/box_apps_config.json" from environment variable RCLONE_BOX_BOX_CONFIG_FILE
2023/07/03 17:43:20 DEBUG : rclone: Version "v1.61.1" starting with parameters ["rclone" "-vv" "config" "reconnect" "source_box:"]
2023/07/03 17:43:20 DEBUG : Using config file from "/Users/blahblah/.config/rclone/rclone.conf"
2023/07/03 17:43:20 DEBUG : source_box: config in: state="", result=""
2023/07/03 17:43:20 DEBUG : Setting box_box_config_file="/Users/blahblah/.config/rclone/box_apps_config.json" from environment variable RCLONE_BOX_BOX_CONFIG_FILE
2023/07/03 17:43:20 DEBUG : jwtutil: Response Body: {"access_token":"<blah blah blah blah purposely removed by me>CNGA4jCvXDtt0pvQZDpzNOA3lsn0WSvC5MSqnnFW0uqjbvsEqjxnQOCYHvVNd6Rg44wxw0OU","expires_in":3948,"restricted_to":[],"token_type":"bearer"}
2023/07/03 17:43:20 DEBUG : Saving config "token" in section "source_box" of the config file
2023/07/03 17:43:20 DEBUG : source_box: Saved new token in config file
2023/07/03 17:43:20 DEBUG : source_box: config out: out=<nil>, err=<nil>
2023/07/03 17:43:20 DEBUG : rclone: Version "v1.61.1" finishing with parameters ["rclone" "-vv" "config" "reconnect" "source_box:"]
```
**Below is the problematic version, which before the v1.63.0 had no issues**
```
INFO - 2023/07/03 15:41:55 DEBUG : Setting default for box-box-config-file="/etc/secret-csi-volume-box/box-config-json" from environment variable RCLONE_BOX_BOX_CONFIG_FILE
INFO - 2023/07/03 15:41:55 DEBUG : rclone: Version "v1.63.0" starting with parameters ["rclone" "-vv" "config" "reconnect" "source_box:"]
INFO - 2023/07/03 15:41:55 DEBUG : Using config file from "/config/rclone/rclone.conf"
INFO - 2023/07/03 15:41:55 DEBUG : source_box: config in: state="", result=""
INFO - 2023/07/03 15:41:55 DEBUG : Setting box_box_config_file="/etc/secret-csi-volume-box/box-config-json" from environment variable RCLONE_BOX_BOX_CONFIG_FILE
INFO - 2023/07/03 15:42:01 DEBUG : jwtutil: Response Body: {"error":"invalid_grant","error_description":"Please check the 'aud' claim. Should be a string"}
INFO - 2023/07/03 15:42:01 DEBUG : source_box: config out: out=<nil>, err=failed to configure token with jwt authentication: jwtutil: failed making auth request: 400 Bad Request
INFO - Error: failed to configure token with jwt authentication: jwtutil: failed making auth request: 400 Bad Request
INFO - Usage:
INFO -   rclone config reconnect remote: [flags]
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment]
I'm sorry to hear that. I'm pretty sure this is related to the following change: https://github.com/rclone/rclone/pull/6277. Quick search in the repo of the new jwt library we changed to seem to indicate issues and confusion related to the value type of the aud (audience) field: https://github.com/search?q=repo%3Agolang-jwt%2Fjwt+aud&type=issues

This needs to be looked into. One problem with the change was that we had problems testing it. So; I hope you would be able to test a beta build, should we come up with a possible code fix? And also; are you capable of building rclone from source yourself, so that you could try things without we having to publish a prebuilt beta binary?

**Comment by ncw** [comment]
@albertony It seems seems possible that using `StandardClaims` rather than `RegisteredClaims` will fix this?

Remember you can push to a branch on github.com/rclone/rclone to get a prebuilt binary and `make btest` will (if running on linux anyway) copy the URL of the result in markdown format to paste into an issue

**Comment by albertony** [comment]
Oh, for a patch we could use the StandardClaims, since we are still using v4 of jwt-go. And then we have time to work on longer term fix compatible with v5 later. Will see if I can do that now.

**Comment by ncw** [comment]
> Oh, for a patch we could use the StandardClaims, since we are still using v4 of jwt-go. And then we have time to work on longer term fix compatible with v5 later. Will see if I can do that now.

That looks like a nice small patch perfect for the patch release :-)

**Comment by ncw** [comment]
@minnieshi does the above work for you? I'd like to roll this into v1.63.1 but I need confirmation that it works for you first - thank you :-)

**Comment by minnieshi** [comment]
I am very sorry that I didn't respond sooner. I was a bit sick and also we just went to use v1.62 . 
I will have to remember to check/test tomorrow.

**Comment by forrie** [comment]
Perhaps related to what I'm experiencing, using the latest GIT rclone -- a couple of days ago or so, I cannot complete the API reconnect process with Google.  It just hangs.  I do not, however, get the above error -- possibly because I don't allow it to hang forever (CTRL-C).

**Comment by ncw** [comment]
@forrie please try the beta here and see if it fixes it for you

https://beta.rclone.org/branch/box-jwt-fix/v1.64.0-beta.7129.b626f3ea8.box-jwt-fix/

Thanks

**Comment by forrie** [comment]
I compiled this branch (MacOS) and it did not solve the problem that I am experiencing.  So perhaps mine is unrelated -- I don't want to hijack this ticket.    I just tried the latest master branch:

rclone v1.63.0-beta.7072.4f8dab8bc
- os/version: darwin 12.6.7 (64 bit)
- os/kernel: 21.6.0 (x86_64)
- os/type: darwin
- os/arch: amd64
- go/version: go1.20.5
- go/linking: dynamic
- go/tags: none

and the symptom I experience is the same.  I get through the dialog and "Continue" then it hangs.

**Comment by ncw** [comment]
I've merged @albertony 's quick fix to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.63.1

@forrie I don't think you are experiencing the same issue - likely you have a firewall problem. Probably best to [post on the rclone forum](https://forum.rclone.org/) about this to get some help.

**Comment by minnieshi** [comment]
we have no more problems; sorry for the so late response.

**Comment by albertony** [comment]
Great! Appreciate you taking the time to report back. Better late than never. 😄
