### ISSUE TITLE
Cant add Dropbox with Client_ID and Secret

### ISSUE THREAD

**Issue by Herobr1ne** [rclone/rclone#7122]
Cant add Dropbox with Client_ID and Secret.
Without App id and secret it works fine. 
It worked before too but I reinstall my Linux system and cant add it now.
Yes i added "http://localhost:53682/" to the redirect OAuth URL

Windows 11 64 Bit Version: rclone v1.63.0
Debian 12 64 Bit Version: rclone v1.63.0

Dropbox Appfolder

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
.\rclone.exe authorize "dropbox" "CENSORED"

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
https://pastebin.com/seRJ1F88

Some Pictures:

![chrome_m2Qa6nzcKu](https://github.com/rclone/rclone/assets/33431587/b5d23d8f-c120-44c9-9d73-999498f6ec62)

![chrome_BPyiyNCHRB](https://github.com/rclone/rclone/assets/33431587/6349c767-3078-4e8d-81c1-62f8d3fce3e5)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
For general support, please use the forums.

https://forum.rclone.org

That error generally means you've pasted in the wrong client ID and/or secret into your rclone.conf
