### ISSUE TITLE
Starting the copy task may result in inaccurate estimation of completion time and speed statistics

### ISSUE THREAD

**Issue by xukefei01** [rclone/rclone#7130]
#### What is the problem you are having with rclone?
- Starting the copy task may result in inaccurate estimation of completion time and speed statistics

#### What is your rclone version (output from `rclone version`)
- rclone1.62.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
- windows 7， 64bit

#### Which cloud storage system are you using? (e.g. Google Drive)
- aws s3

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
- ./rclone.exe copy Y:\32k dataExplorer:bucket1/asf/aaabbbbaa --transfers 8 --checkers 5 --min-age "2023-07-10 20:17:28" --progress --no-check-certificate --no-traverse --max-duration 41851893ms -vv

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

![rclone-bug](https://github.com/rclone/rclone/assets/38979207/8ccb397e-604d-4723-82df-053c206a2a6a)

![rclone-copy-setting](https://github.com/rclone/rclone/assets/38979207/06cf0a7f-2172-43d0-9aec-215526fca03c)
![rclone-source-dir](https://github.com/rclone/rclone/assets/38979207/f2eae63e-481e-48ac-a12d-f4ba9a08db6f)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by xukefei01** [comment]
My directory structure is a directory shared using cifs, with approximately 80,000-300,000 files. When copying the files from the shared directory to an S3 object storage, I encountered a problem similar to https://github.com/rclone/rclone/issues/7033

**Comment by darthShadow** [comment]
As you already found the linked issue and it's still open, is there any reason to open a new issue?

**Comment by xukefei01** [comment]
> As you already found the linked issue and it's still open, is there any reason to open a new issue?

Sorry, I will close this question and show the situation I encountered in the link found.
