### ISSUE TITLE
A long wait occurred when non-existent files were accessed from a file system mounted through "rclone mount"

### ISSUE THREAD

**Issue by qq122356** [rclone/rclone#7133]
#### Output of `rclone version`
rclone v1.63.0
- os/version: centos 7.9.2009 (64 bit)
- os/kernel: 3.10.0-1160.88.1.el7.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.5
- go/linking: static
- go/tags: none

#### Describe the issue
I use "rclone mount" to mount Huawei cloud OBS storage, the storage capacity is about 200 TB, contains more than 20 million objects, when I run the "ls -l" command to display a file, if the file does not exist, the command execution will be stuck for 7 seconds, and then an error message will be displayed. (This process is actually performed in the program of the website). This results in a poor experience for website users. So I would like to ask what can be done to solve this problem?

**Comment by ncw** [comment]
Can you ask this on [the rclone forum](https://forum.rclone.org/) please? If you fill in the template with the command you are using that would be useful.

We try to keep the github issue tracker for bugs in rclone.

Thank you.
