### ISSUE TITLE
Dropbox documentation is outdated

### ISSUE THREAD

**Issue by burner-** [rclone/rclone#7136]
Current dropbox documentation https://rclone.org/dropbox/ show how to configure dropbox with long lived access token. Anyway it had not been supported by dropbox in many years. Old tokens work but users cannot create new ones. 
With googling it is possible to find is hints front reddit that there may or may not have support on rclone for short lived tokens. Anyway with lot of try and error I did not manage get it work. 
So IF threte is feature what allow use rclone with current drop box api it would be good to document it. If it is not currently working then it is also good to document that. 
By googling you will find out that there is quite many users currently strugling with this same issue.

**Comment by kapitainsky** [comment]
> Current dropbox documentation https://rclone.org/dropbox/ show how to configure dropbox with long lived access token.

rclone uses whatever token is issued by dropbox - not sure what part of documentation you refer to when mentioning this.


> Anyway with lot of try and error I did not manage get it work.

I have created this week multiple dropbox accounts and all work without any issues. If you have problem please create new thread on the forum - https://forum.rclone.org/ - and somebody might be able to help you.

**Comment by animosity22** [comment]
@burner - if you'd like to submit a PR to fix it, that would be great as the long lived tokens are long gone :)

If you need support or have a question, please submit it on the forums and we're happy to help out.

https://forum.rclone.org
