### ISSUE TITLE
UpToBox transfers randomly stop at 0/s 

### ISSUE THREAD

**Issue by TheRadziu** [rclone/rclone#7138]
#### What is the problem you are having with rclone?
When uploading from gdrive to UpToBox files randomly stop transferring, getting stuck at `0/s` speed
For example here all 10 transfers are 'stuck' and require killing rclone and restarting the command
```
Transferring:
 * My Little Pony Friends…ubbing PL 1080p HD.mp4: 20% /810.023Mi, 0/s, 2562047h47m16s
 * Mythbusters [ENG]/Seas…- Mini Myth Mayhem.mkv: 71% /1.093Gi, 0/s, 2562047h47m16s
 * Mythbusters [ENG]/Seas… - Soda Cup Killer.mkv: 23% /1.092Gi, 0/s, 2562047h47m16s
 * My Little Pony Friends…[Dubbing PL 1080p].mp4:  4% /1.545Gi, 0/s, 2562047h47m16s
 * Mythbusters [ENG]/Seas…utomobiles Special.mkv: 40% /1.093Gi, 0/s, 2562047h47m16s
 * Parks and Recreation […B-DL.AC3.x264-TRad.mkv: 18% /1.296Gi, 0/s, 2562047h47m16s
 * Parks and Recreation […B-DL.AC3.x264-TRad.mkv:  9% /1.300Gi, 0/s, 2562047h47m16s
 * Phineas and Ferb [1080….AAC2.0.H.264-TRad.mkv: 19% /1.372Gi, 0/s, 2562047h47m16s
 * Phineas and Ferb [1080….AAC2.0.H.264-TRad.mkv: 50% /1.377Gi, 0/s, 2562047h47m16s
 * Phineas and Ferb [1080….AAC2.0.H.264-TRad.mkv: 18% /1.375Gi, 0/s, 2562047h47m16s
 ```
 Does not happen with sync between two gdrives.

#### What is your rclone version (output from `rclone version`)
```
rclone v1.63.0
- os/version: unknown
- os/kernel: 4.4.180+ (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.5
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Synology OS, linux based, 64bit

#### Which cloud storage system are you using? (e.g. Google Drive)
UpToBox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
/usr/bin/rclone --config="/volume1/Synology/rclone.conf" \
sync \
"$SOURCE$SUBDIRECTORY" \
"$DESTINATION$SUBDIRECTORY" \
--fast-list --transfers=10 --tpslimit 5 \
--drive-acknowledge-abuse \
-vv --log-file="$LOGLOCATION" \
-P
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
Will edit log back in when the bug happens again with -vv flag enabled.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by kapitainsky** [comment]
github should be used for tracking confirmed bugs not for any random issues.

Bring it to the forum https://forum.rclone.org/ where somebody will have a look on what is going on.

**Comment by darthShadow** [comment]
Closing till the bug is confirmed with debug logs.
