### ISSUE TITLE
rclone mount - 425 Unable to build data connection: TLS session of data connection not resumed

### ISSUE THREAD

**Issue by ManuelReschke** [rclone/rclone#7140]
**Hi,**

**how can i solve this issue? I read that is a bug in rclone? Is that true?**

**rclone version**
rclone v1.63.0
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-76-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.5
- go/linking: static
- go/tags: none

**Problem:**
2023/07/14 23:58:24 ERROR : MYFILE******: vfs cache: failed to upload try #6, will retry in 5m0s: vfs cache: failed to transfer file from cache to remote: update stor: 1 error occurred:
        * 425 Unable to build data connection: TLS session of data connection not resumed.

**Command:**
rclone mount *MYREMOTE*/ /home/FTP/ --umask 0 --allow-other --dir-cache-time 24h --attr-timeout 6h --poll-interval 30s --vfs-cache-max-age 3h --vfs-cache-mode full --vfs-read-chunk-size 128M --vfs-read-chunk-size-limit 512M --vfs-cache-max-size 10G --transfers 4 --checkers 4 --ftp-disable-tls13

**RClone config:**

[MYREMOTE]
type = ftp
host = *** MY HOST ****
user = *********
pass = S****************M
explicit_tls = true
no_check_certificate = true
tls_cache_size = 32

**FTP SERVER:**
Filezilla FTP Server v1.7.2

**Comment by darthShadow** [comment]
We like to keep only confirmed issues on the github issue tracker. Please open a thread on the forums at https://forum.rclone.org so someone can take a look and help you.
