### ISSUE TITLE
Doc clarification checksum

### ISSUE THREAD

**Issue by antoinetran** [rclone/rclone#7145]
Hi, this is just about this doc https://github.com/rclone/rclone/blob/master/docs/content/flags.md?plain=1#L27
```
 -c, --checksum                                    Skip based on checksum (if available) & size, not mod-time & size
```

I think this is wrong (this description describes `--ignore-checksum`) and it should be read as
```
 -c, --checksum                                    Force check based on checksum (if available) & size, instead of mod-time & size
```

Besides, what would happen if we use `--checksum --s3-disable-checksum` for S3 storage, which parameter would be really used?

**Comment by ncw** [comment]
> Skip based on checksum (if available) & size, not mod-time & size

That is confusing - I see what you mean.

Maybe something like this?

> Check for changes with checksum (if available) & size, not mod-time & size

This description has to be short as it is the command line help.

**Comment by antoinetran** [comment]
> > Check for changes with checksum (if available) & size, not mod-time & size
> 
> This description has to be short as it is the command line help.

Why not? I'm ok for that. And what would happen if checksum is not available, then would it throw an error or just fallback to "mod-time & size"? If yes
```
Check for changes with size & checksum (if available, or fallback to size & mod-time)
```

**Comment by ncw** [comment]
> Why not? I'm ok for that. And what would happen if checksum is not available, then would it throw an error or just fallback to "mod-time & size"? If yes
> 
> ```
> Check for changes with size & checksum (if available, or fallback to size & mod-time)
> ```

Actually this would be more accurate

    Check for changes with size & checksum (if available, or fallback to size only).

Do you want to make this change? You can create a pull request entirely in your browser.

This line is the source of truth

https://github.com/rclone/rclone/blob/4c5a21703e442d78fb1ab187f1bcce2b6b0d6510/fs/config/configflags/configflags.go#L55

And you can edit that file here

https://github.com/rclone/rclone/edit/master/fs/config/configflags/configflags.go

When you save it it will create a pull request.

**Comment by antoinetran** [comment]
> Actually this would be more accurate
> 
> ```
> Check for changes with size & checksum (if available, or fallback to size only).
> ```

Are you sure this is the current bahavior? Checking change based only on size and not on time seems pretty dangerous for me. I would rather have it fails.

**Comment by antoinetran** [comment]
Well, after reading the code a bit, it looks like when no common hash methods are found between source and destination, we get a comparison only with size: https://github.com/rclone/rclone/blob/88c72d1f4de94a5db75e6b685efdbe525adf70b8/fs/operations/operations.go#L207 
So will do a PR.
