### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [rclone/rclone#7148]
👋 it looks like [1.63.1](https://github.com/rclone/rclone/releases/tag/v1.63.1) did not complete successfully, raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/136810

**Comment by ncw** [comment]
What's the issue? I don't understand!

**Comment by p-linnane** [comment]
1.63.1 was tagged but a GitHub release wasn't created for it.

**Comment by ncw** [comment]
Got it! I forgot to run `make github_release` ;-)

I've done it now and the release looks OK so I'm going to close this.

Thanks for the heads up!
