### ISSUE TITLE
Can ownership and permissions be sync'd?

### ISSUE THREAD

**Issue by jcarter087** [rclone/rclone#715]
Hello

I hope this is the right place to ask support questions. Let's say if we sync to Google Drive or Amazon Drive, is it possible to retain file/directory ownership and permissions?

**Comment by jlippuner** [comment]
I was wondering exactly the same thing. It appears that using the mount option, all files get mounted with 644 and all directories with 755.

Preserving ACLs would be a great feature (if the remote cloud storage supports it, I know Dropbox does).

**Comment by nmajeran** [comment]
owner, group and modebits syncing for local to local would be super helpful if that is any easier.

**Comment by bitc** [comment]
This looks like a duplicate of #1202

**Comment by ivandeex** [comment]
This same feature (keep and synchronize object permissions) is also requested by https://github.com/rclone/rclone/issues/1202 which has a nice discussion thread, so mearging this one in.
You can subscribe to that ticket.
I'm not dismissing the request, just a little housekeeping.
Thank you.
