### ISSUE TITLE
Add rclone vendor for webdav for use with rclone serve webdav

### ISSUE THREAD

**Issue by chaoticryptidz** [rclone/rclone#7160]
#### What is your current rclone version (output from `rclone version`)?
rclone 1.63.1

#### What problem are you are trying to solve?
Add a `rclone` vendor to list of webdav vendors. This will allow modified times, hashes and other improvements that the nextcloud vendor previously provided & potentially future extensions to work when using rclone with a webdav remote connecting to a webdav server hosted by `rclone serve`

#### How do you think rclone should be changed to solve that?
For now add a `rclone` vendor to list of vendors, then allow use of those extended features (modify times, hashes, etc) using that vendor rather than only nextcloud/owncloud/fastmail

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Yes this is a good idea. Do you want to have a go at this @chaoticryptidz ?
