### ISSUE TITLE
Use `sync/atomic` types

### ISSUE THREAD

**Issue by r-ricci** [rclone/rclone#7167]
Now the minimum required go version is 1.19, so we can use the new integer types from `sync/atomic`. This would make it easier to avoid bugs such as #6311, but I'm not sure it's worth it.

There are different kinds of data accessed atomically in rclone's code.

- **Single variables**: always aligned

- **32-bit struct fields**: always aligned, but using `atomic.Int32`/`atomic.Uint32` would avoid problems if they are changed to 64-bit values in the future

- **64-bit struct fields**: using `atomic.Int64`/`atomic.Uint64` would free from the burden of manually managing the alignment of struct fields

In all cases load/store operations would be nicer:

```
y = x.Load()
x.Store(y)
```

instead of

```
y = atomic.LoadInt64(&x)
atomic.StoreInt64(&x, y)
```

But initialization would be uglier:

```
var x atomic.Int64
x.Store(y)


s := StructType {
	a: 0,
}
s.b.Store(y)
```

instead of

```
x := y


s := StructType {
	a: 0,
	b: y,
}
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I agree these are neater and less error prone. I would accept a PR if you wanted to do the work :-)
