### ISSUE TITLE
What is this situation

### ISSUE THREAD

**Issue by suger520HT** [rclone/rclone#7175]
E:\Tencent\N_m3u8DL-CLI\FFmpeg\bin>rclone mount aliyun:/ w: --vfs-cache-mode full
2023/07/26 18:22:17 ERROR : webdav root '': Statfs failed: XML syntax error on line 48: expected element name after <
The service rclone has been started.
2023/07/26 18:22:20 ERROR : /: Dir.Stat error: couldn't list files: XML syntax error on line 48: expected element name after <
2023/07/26 18:22:20 ERROR : IO error: couldn't list files: XML syntax error on line 48: expected element name after <
2023/07/26 18:22:20 ERROR : /: Dir.Stat error: couldn't list files: XML syntax error on line 48: expected element name after <
2023/07/26 18:22:20 ERROR : IO error: couldn't list files: XML syntax error on line 48: expected element name after <
2023/07/26 18:22:20 ERROR : /: Dir.Stat error: couldn't list files: XML syntax error on line 48: expected element name after <
2023/07/26 18:22:20 ERROR : IO error: couldn't list files: XML syntax error on line 48: expected element name after <
2023/07/26 18:22:20 ERROR : /: Dir.Stat error: couldn't list files: XML syntax error on line 48: expected element name after <
2023/07/26 18:22:20 ERROR : IO error: couldn't list files: XML syntax error on line 48: expected element name after <

**Comment by kapitainsky** [comment]
Please ask questions on the forum:

https://forum.rclone.org/

providing all details from `Help and support` template

github is only for confirmed bugs and enhancements tracking so this issue will be closed.

**Comment by suger520HT** [comment]
My own problem solved

**Comment by yjiang8081** [comment]
> My own problem solved

How to solve this problem?

**Comment by Lonely233233** [comment]
> > My own problem solved
> 
> How to solve this problem?

I myself http://127.0.0.1:5244/dav When there was no dav written

**Comment by kokikoku** [comment]
> > > My own problem solved
> > 
> > 
> > How to solve this problem?
> 
> I myself http://127.0.0.1:5244/dav When there was no dav written

加/dav挂载成功了。感谢！
