### ISSUE TITLE
fuse mount modules option

### ISSUE THREAD

**Issue by m-walk** [rclone/rclone#718]
Hi!
A lot of options supported by the #653. :-)
but, "modules" option did not support...
I want to use the module option.
e.g.
https://acd-cli.readthedocs.io/en/latest/FUSE.html#mount-options

**Comment by ncw** [comment]
Good list thanks. Will add modules and I see I missed nlinks also.

**Comment by fabienpks** [comment]
And I think adding --allow-other option would be great ! (I couldn't find it but perhaps it's still there)

**Comment by pmow** [comment]
Yes, it'd be really great to have at least allow-other to share with other service accounts on same system.

**Comment by Trentflix** [comment]
The new beta does have FUSE flags including --allow-other (and it works great). See `rclone mount -h` to view the options.

http://pub.rclone.org/v1.33-13-g7be4c3a-fuse-flags%CE%B2/

**Comment by pmow** [comment]
Thanks Trentflix.  My bad, I went by the previous comments - allow-other is literally in the first comment of #653 💨

**Comment by animosity22** [comment]
Since this is was way back for ACD, I think it's safe to close out :)
