### ISSUE TITLE
Ignore 255 character limit on Jottacloud when encrypting filenames

### ISSUE THREAD

**Issue by dustinwilson** [rclone/rclone#7184]
#### What is your current rclone version (output from `rclone version`)?
v1.63.1

#### What problem are you are trying to solve?
Sync errors that occur when filenames are longer than 255 characters when filenames are encrypted

#### How do you think rclone should be changed to solve that?
When filenames are encrypted they're always 26 characters long, so I'm proposing to have 255 characters not be a limitation when encrypting filenames.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
The 255 character limit is imposed by Jottacloud and not something we can work around.

Not sure exactly what you mean?

**Comment by dustinwilson** [comment]
I'm using the [Crypt](https://rclone.org/crypt/) storage system to encrypt files and filenames of files I send to Jottacloud. It works great until I run into a file that has more than 255 characters:

```
2023/07/30 04:31:09 ERROR : pictures/dog-landscapes-scenery-nature-love-four-grass-seasons-family-animals-paintings-forests-time-beautiful-flowers-lovely-spring-creative-wildlife-wolves-pre-babies-dogs-image-pictures-1366x768.jpg: Failed to copy: HTTP error 400 (400 Bad Request) returned body: "{\"code\":400,\"message\":\"InvalidArgumentException\",\"cause\":\"JFS file names may not be longer than 255 characters\",\"error_id\":\"InvalidArgumentException\",\"x-id\":\"963056430203\"}"
```

I'm aware of the filename limitation, but when encrypting filenames the files that are stored on Jottacloud **can't** have 255 characters. They will always have 26 characters:

![image](https://github.com/rclone/rclone/assets/1885928/2638d4d5-b495-4861-94bf-3bf574c4f785)

So, rclone's telling me that the filename is longer than 255 characters isn't correct. The filename on Jottacloud will have 26 characters regardless of what it is on my storage. My proposal is to lift this limitation when filename encryption is turned on.

**Comment by Masamune3210** [comment]
Something tells me this limitation isn't intentional. The backing cloud should not even be aware of the original filename, maybe a leak or a race condition?

**Comment by dustinwilson** [comment]
This error also needlessly prevents deletion of excluded files on the remote. I know we can use `--ignore-errors`, but I'd rather not have that on all the time in case there really were actual IO errors.

**Comment by kapitainsky** [comment]
> They will always have 26 characters

Encrypted names have minimum 26 characters length but not maximum.

e.g. files: 

`a` or `123.txt `

are encrypted to (both are 26 chars long)

`p0e52nreeaj0a5ea7s64m4j72s` and `l42g6771hnv3an9cgc8cr2n1ng`

but `long_long_long_long_long_long_file.txt` to

`n68he9dr89db0mh8g8mlt7vstgq6sl9sdda0n4ljvlg4tb25j57qsg2us7a87at3frg9c33kg2aq6`

you can see that encryption makes files names significantly longer.

You have to take into account when applying encryption on remote with restricted file name length. So e.g. in your case  max file length is 255 - it means that unencrypted file name length can be only 144 characters

**Comment by kapitainsky** [comment]
I think this thread should be closed and any further discussion continued on the forum if you wish - which is the right place for such topics.

**Comment by ncw** [comment]
It looks like [filename_encoding = base32768](https://rclone.org/crypt/#crypt-filename-encoding) would work well on Jottacloud which would help with the long file names.

```
// TestJottacloud
maxFileLength = 255 // for 1 byte unicode characters
maxFileLength = 255 // for 2 byte unicode characters
maxFileLength = 255 // for 3 byte unicode characters
maxFileLength = 127 // for 4 byte unicode characters
```



@kapitainsky wrote:
> I think this thread should be closed and any further discussion continued on the forum if you wish - which is the right place for such topics.

I agree. Please move discussion to [the rclone forum](https://forum.rclone.org/)  - thank you!

**Comment by kapitainsky** [comment]
> // TestJottacloud
> maxFileLength = 255 // for 1 byte unicode characters
> maxFileLength = 255 // for 2 byte unicode characters
> maxFileLength = 255 // for 3 byte unicode characters
> maxFileLength = 127 // for 4 byte unicode characters

This is at least good indication that base32768 makes sense for this remote. I would still test it first will all alphabet before using. If anybody is interested please raise an issues on the forum.

**Comment by kapitainsky** [comment]
Yes this is good idea. I will create separate git enhancement  issue and will try to have a go on it.
