### ISSUE TITLE
Improve Checking while mounting after a full cache disk faillure

### ISSUE THREAD

**Issue by christianmerges** [rclone/rclone#7187]
#### What is your current rclone version (output from `rclone version`)?
1.63 beta

#### What problem are you are trying to solve?
When the cache disk is running out of space, even after making the drive bigger, uploads are not started to free up space in the cache. When u restart the daemon and remount. Files are being checked, if they have been modified while the daemon was stopped. Only one file at the time is being read from cache disk and compared to the file in the cloud. This makes it really slow.

#### How do you think rclone should be changed to solve that?
1. Save cache metadata on separate folder or reserve space for metadata on the cache disk. So the error would resolve on it's own just by refusing reads for the period of time, where there is no space in cache drive left, but after finished uploads and flushing from cache, reads can be cached again.

2. When mounting the vfs, read as many files from disk in parallels as the variable "transfers" is set. Most cloud providers limit the bandwidth for a single transfer, but with multiple transfers, the checking goes faster and the vfs would mount much faster.

**Comment by animosity22** [comment]
1) there's already an issue for that - https://github.com/rclone/rclone/issues/5123 and maybe a few others

2) there's already an issue for this -> https://github.com/rclone/rclone/issues/5123

**Comment by christianmerges** [comment]
@animosity22 it's not the same thing, but i moved my text to the other issue.

**Comment by animosity22** [comment]
Which isn't the same thing? You have two things listed so which doesn't match?

**Comment by christianmerges** [comment]
Both don't match. The mentioned issue by you is about caching only metadata, my points r about to improve the vfs cache mode full option.

**Comment by animosity22** [comment]
1 is the same concept as it's how to implement it so please add your comments there.

2 is the same concept as it's how to start up faster so having more checkers gets faster startup.

Leaving is as a duplicate as the concepts are the same for both.

Thanks
