### ISSUE TITLE
Nextcloud: broke webdav connect in new version (due to added support for chunked uploads?)

### ISSUE THREAD

**Issue by technout** [rclone/rclone#7199]
#### What is the problem you are having with rclone?
About one month ago, i can connect from my Manjaro desktop with my transip / stackstorage cloud with rclone.
From my Ubuntu server 22.04 i still can connect to this cloud with rclone. But with the newer version of rclone on my desktop i got this error:
```Failed to create file system for "transip:": the remote url looks incorrect. Note that nextcloud chunked uploads require you to use the /dav/files/USER endpoint instead of /webdav. Please check 'rclone config show remotename' to verify that the url field ends in /dav/files/USERNAME```

When i test the url direct in browser (https://mydomain.stack.storage/remote.php/webdav) i get an OK.
And also for: https://mydomain.stack.storage/remote.php/dav/files/technout i get an OK.
Username and password are not changed en no config file was changed by me. But after this i did some testing, delete the transip entrance and added it again, but no luck, same error.

I hope i've given enough information to be helpful, and thanks for maintaining this cool project!

#### What is your rclone version (output from `rclone version`)
rclone v1.63.1 (Manajaro)
- os/version: arch "23.0.0" (64 bit)
- os/kernel: 6.1.38-1-MANJARO (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.6
- go/linking: static
- go/tags: none

Ubuntu rclone version (is working good with this same config of transip)
rclone v1.58.1
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-72-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.9
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
6.1.38-1-MANJARO (x86_64)

#### Which cloud storage system are you using? (e.g. Google Drive)
Webdav / Nextcloud / TransIP

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
sudo rclone lsd transip: -vv

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
2023/08/01 21:38:36 DEBUG : rclone: Version "v1.63.1" starting with parameters ["rclone" "lsd" "transip:" "-vv"]
2023/08/01 21:38:36 DEBUG : Creating backend with remote "transip:"
2023/08/01 21:38:36 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2023/08/01 21:38:36 DEBUG : found headers: 
2023/08/01 21:38:36 Failed to create file system for "transip:": the remote url looks incorrect. Note that nextcloud chunked uploads require you to use the /dav/files/USER endpoint instead of /webdav. Please check 'rclone config show remotename' to verify that the url field ends in /dav/files/USERNAME

sudo rclone config
[...]
Configuration complete.
Options:
- type: webdav
- url: https://mydomain.stack.storage/remote.php/webdav
- vendor: nextcloud
- user: technout
- pass: *** ENCRYPTED ***

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by technout** [comment]
I removed version 1.63.1 and installed rclone-1.59.2-1
Now it just works.

**Comment by ncw** [comment]
Can you try [the latest beta](https://beta.rclone.org/) please? Its possible we've fixed this already.

**Comment by technout** [comment]
I tried it today with the latest beta, but the error is the same:
sudo rclone lsd transip:/ -vv
```
2023/08/04 10:20:26 DEBUG : rclone: Version "v1.64.0-beta.7204.a555513c2" starting with parameters ["rclone" "lsd" "transip:/" "-vv"]
2023/08/04 10:20:26 DEBUG : Creating backend with remote "transip:/"
2023/08/04 10:20:26 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2023/08/04 10:20:26 DEBUG : found headers: 
2023/08/04 10:20:26 Failed to create file system for "transip:/": the remote url looks incorrect. Note that nextcloud chunked uploads require you to use the /dav/files/USER endpoint instead of /webdav. Please check 'rclone config show remotename' to verify that the url field ends in /dav/files/USERNAME
```

**Comment by ncw** [comment]
@devnoname120 do you have any ideas? Can the `url` be transformed?

**Comment by technout** [comment]
To be more clear: it is a bug report, not a question.

**Comment by ncw** [comment]
The error message 

> Failed to create file system for "transip:": the remote url looks incorrect. Note that nextcloud chunked uploads require you to use the /dav/files/USER endpoint instead of /webdav. Please check 'rclone config show remotename' to verify that the url field ends in /dav/files/USERNAME

Is telling you to change your URL from `https://mydomain.stack.storage/remote.php/webdav` to `https://mydomain.stack.storage/remote.php/dav/files/USERNAME` where `USERNAME` is your username.

Can you try this?

**Comment by technout** [comment]
Yes, i've tried this, this gives the same results.

**Comment by devnoname120** [comment]
@ncw I'm not entirely sure whether it's safe to automatically fix URLs from `/webdav` to `/dav/files/USERNAME`. This error message was added before I took over the NextCloud chunked uploads feature and I didn't invest the time to find out if it's legitimate or not. It's unlikely that I will be able to look into it in the coming 3 weeks.

**Comment by ncw** [comment]
@technout 
> Yes, i've tried this, this gives the same results.

Can you show the log with -vv for this please because I think this if it is going to fail, it should at least fail in a different way!

**Comment by devnoname120** [comment]
@technout Also, why did you configure the remote as a NextCloud remote? [Transit STACK](https://www.transip.nl/stack/) is based on ownCloud, not NextCloud. Chunked uploads for ownCloud is *not* supported by rclone.

**Comment by technout** [comment]
Yes, you're right! I thought it was NextCloud but configuring it as OwnCloud fixed the problem! All these years it did work with NextCloud so i was convinces it was the right setting. Sorry for my misconfiguration!
Configuring it with /webdav or /dav/files/USERNAME both work when set to OwnCloud.
```
sudo rclone lsd transip:/ -vv
2023/08/07 14:47:21 DEBUG : rclone: Version "v1.64.0-beta.7204.a555513c2" starting with parameters ["rclone" "lsd" "transip:/" "-vv"]
2023/08/07 14:47:21 DEBUG : Creating backend with remote "transip:/"
2023/08/07 14:47:21 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2023/08/07 14:47:21 DEBUG : found headers: 
2023/08/07 14:47:21 DEBUG : fs cache: renaming cache item "transip:/" to be canonical "transip:"
          -1 2023-08-01 22:54:50        -1 restic_backup
2023/08/07 14:47:23 DEBUG : 6 go routines active
```

**Comment by lightaffaire** [comment]
I just updated my base OS from Fedora 37 to Fedora 41 and the rclone package was updated as well.

Since then uploading images to a nextcloud 25(?) server in a VM here that has not changed in at least 1 year no longer worked.

$ rclone --version
-  clone v1.67.0
- os/version: fedora 41 (64 bit)
- os/kernel: 6.11.7-300.fc41.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.23.1
- go/linking: dynamic
- go/tags: none

Only when I changed the vendor to be owncloud and not nextcloud did it start working again.

$ $EDITOR ~/.config/rclone/rclone.conf
# --no-check-certificate
[nextcloud-LAN]
type = webdav
url = http://IP:PORT/remote.php/webdav/
# vendor = nextcloud   <<< OLD
vendor = owncloud      <<< NEW
user = USERNAME
pass = PASSWORD

Just another datapoint.

--Iain

**Comment by devnoname120** [comment]
@lightaffaire Can you give us the logs?
