### ISSUE TITLE
I think rclone needs some sort of inverted chunker style overlay.

### ISSUE THREAD

**Issue by left1000** [rclone/rclone#7200]
I think rclone needs some sort of inverted chunker style overlay.

Chunker takes very large files and breaks them down into smaller files. But what about people who have tons of very small files and want an overlay that somehow merges them into larger files?

This sounds pointless, who would want to have to download a 1gb file in order to access a 1kb file?

But, well, if you're using amazon deep glacier you won't be making any file downloads hardly ever. But you might be requesting too many list/head api calls and overpaying for them.  I know about --update --use-server-modtime and --s3-no-head but even getting 1000 items per 1 request using --fast-list the way my data is currently stored will generate far far too many api requests over time merely via the list api (at least that's my fear, and that's why I've never tried it before.)

I've been looking at amazon deep glacier, and it would be perfect for my usage case. EXCEPT I have too many files. I've made my backup's in a lazy fashion with million of tiny files just loose.

Since I started using google's cloud service I've only ever downloaded less than 0.1-1.0% of the data. But I am constantly checking metadata in order to update backups. I never use mount. I never use plex. I often use rclone copy and target a very large directory though. Like I said there are just too many files in my cloud storage right now. Too many small files generating too much metadata for amazon deep glacier's request policies.

Maybe I just need to be a better user of rclone. Obviously if I was smarter I'd have already set all this up. But in my imagination if chunker can exist, why not invertedchunker? rclone does so much for me, without me having to know what I'm doing, what's one more thing?

**Comment by Masamune3210** [comment]
like a zip or other archive layer? Also, this is probably better for the forums, the issue reports are kept for issues only

**Comment by left1000** [comment]
Well, the problem would be how to access the metadata for all the files inside the archive/zip that's not a feature a standard archive.zip supports or has. A second file containing all the metadata for the archive would be needed. But in order to work on deep glacier this second file would need to be sorted on an alternate remote? Or some such. It's an almost impossible problem to solve I guess?

I was going to create this on the forum, but I thought this might work better, as I've had feature requested granted via github before. I'll go make an identical post on the forum though if that's better.

**Comment by left1000** [comment]
I was going to create this on the forum, but I thought this might work better, as I've had feature requested granted via github before. I'll go make an identical post on the forum though if that's better.

https://forum.rclone.org/t/i-think-rclone-needs-some-sort-of-inverted-chunker-style-overlay/40550

**Comment by left1000** [comment]
To further clarify the issue my 134tb google drive cloud storage contained files such that lsl --> to file left me with the text file fullloggoogledrivecrypt07112023 470megabytes.

But I could download 470megabytes every time I wanted to do an lsl or lsd or even copy (which checks target to avoid uploading duplicate files)

Any remote on earth could easily store 470 megabytes and allow frequent downloading and editing of that file. And in my version instead of 134tb broken into one 470 megabyte lsl metadata file it would be like chunker...

So maybe every 5gb would have 1 metadata file. So, my remote would have a total storage of around 500megabytes and 26,800 metadata files. This overlay would simply need to know which metadata files went with which invertedchunks on glacier... it would also have to find some smart way of breaking up an upload into nothing but new inverted chunks, since deep glacier invertedchunks couldn't be edited, only deleted or replaced.

**Comment by Masamune3210** [comment]
Please move over completely to your forum post. As I said, the issues are kept for debugging and issue reports

**Comment by ncw** [comment]
I will close this in favour of the forum discussion. https://forum.rclone.org/t/i-think-rclone-needs-some-sort-of-inverted-chunker-style-overlay/40550/
