### ISSUE TITLE
pCloud does not work anymore

### ISSUE THREAD

**Issue by smschumacher** [rclone/rclone#7207]
Hello,

I have been using pCloud with rclone for years for storing backups in the cloud. A few weeks ago it stopped working: 
First, let me show you the script I have been using:
#!/bin/bash
sudo -u stefan rclone sync /mnt/btrfs-raid/Privates/ pCloud:Privates/ --transfers 1
At the moment this creates the following output:
2023/08/03 14:14:28 Failed to create file system for "pCloud:Privates/": couldn't list files: Get "https://api.pcloud.com/listfolder?folderid=0": dial tcp 74.120.8.15:443: connect: network is unreachable

The folders are all on the remote and can be viewed with a browser.

I then have recreated my configuration and tried again. This was the result:
rclone lsd pCloud:
2023/08/03 14:04:59 ERROR : : error listing: couldn't list files: Get "https://api.pcloud.com/listfolder?folderid=0": dial tcp 74.120.8.15:443: connect: network is unreachable
2023/08/03 14:04:59 Failed to lsd with 2 errors: last error was: couldn't list files: Get "https://api.pcloud.com/listfolder?folderid=0": dial tcp 74.120.8.15:443: connect: network is unreachable

Of course I wrote to pCloud first but their only answer as a "We don't support rclone" 

To me it looks like they changed something in their API and therefore rclone cant connect anymore. Could someone with more clue than me have a look at this?

Yours 
Stefan

**Comment by animosity22** [comment]
Please use the forums for support and use the help and support template.

What you've posted here is a local network error on your machine that needs to get fixed.

https://forum.rclone.org

Thanks

**Comment by smschumacher** [comment]
I can

**Comment by animosity22** [comment]
No, github isn't for general support.

Use the forums.
