### ISSUE TITLE
Need a way to fully configure the B2 custom / download URL for CloudFlare use

### ISSUE THREAD

**Issue by mikecole79** [rclone/rclone#7211]
When using CloudFlare URL for B2 download, the root URL always add /file/ but my CF proxy already accounts for that

I was using version 1.63.  Actually went so far as to download and compile myself with an edit to b2.go, but unsure if I did it correctly.  

#### What problem are you are trying to solve?
B2 provides free downloads when using a CDN.  On my CloudFlare setup, the download URL doesn't include /file/ but in rclone it adds ROOTURL + "/file/" + pathToFile

This breaks my setup.

#### How do you think rclone should be changed to solve that?
I think it would be best if you had to specify /file or /file/bucket in your URL and rclone treated the root URL you provide as everything needed before the actual file name.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
This is actually reasonably complicated to change since the /bucket/file is burnt into rclone at a low level.

Can you put redirects in your cloudflare proxy?

**Comment by mikecole79** [comment]
I will try to figure out how to change it.  It was a pain to setup, so I'll
have to dig into the documentation and figure it out.

Thank you for looking at it.

Mike Cole

**Comment by gymnae** [comment]
Have you found a solution? I just ran into the same issue

**Comment by metadaddy** [comment]
I fixed this in version 1.2.0 of the [`cloudflare-b2`](https://github.com/backblaze-b2-samples/cloudflare-b2) worker. You can now set the `RCLONE_DOWNLOAD` environment variable in the worker to `true` to have the worker strip the `file/` prefix from the incoming path.

**Comment by ncw** [comment]
Thanks @metadaddy - that sounds like a great solution and I will close this.
