### ISSUE TITLE
sync fails with s3 when syncing "folders" created using "Create Folder" operation from AWS S3 management consols

### ISSUE THREAD

**Issue by pradeepk** [rclone/rclone#722]
This was reported as #440 before. To reproduce:

```
rclone sync s3:<bucket>/<folder> <folder>  #  where <folder> is created using "Create Folder" from S3 Management console UI
```

The workaround is to use --min-size 1. But this will be a surprise to new users of rclone.

**Comment by ncw** [comment]
That should say `--min-size 1b`.

I've never used the s3 management console. What exactly gets created? Is it a 0 byte file? What is its content type?

**Comment by pradeepk** [comment]
It is a 0 byte object. No meta-data set on it.

**Comment by ncw** [comment]
I'd probably prefer to "fix" this with a bit of documentation.

Fancy supplying some?

**Comment by pielgrzym** [comment]
The `--min-size 1b` causes to silently ignore some folders while syncing. Without this rclone seems to create empty files instead of some folders. This basically means S3 support is completely broken.

**Comment by pielgrzym** [comment]
I have an S3 bucket with two folders created via AWS UI. One is empty. When I sync using `--min-size` it ommits the empty folder, when I sync without min size instead of creating folder it just creates an empty file with same name. rclone v1.36

**Comment by ivandeex** [comment]
@pradeepk @pielgrzym Does the problem reproduce with rclone 1.54?

**Comment by ivandeex** [comment]
This request was not updated for 3 years.
Please understand that rclone team cannot support releases as old as 1.36.
Closing this now.
Feel free to resubmit.
