### ISSUE TITLE
Validation For Snap Maintenance

### ISSUE THREAD

**Issue by boukendesho** [rclone/rclone#7221]
@ncw Hello team, can i please get an upstream nod or approval for maintaining snap packages, i wish to publish snap packages under the name rclone , and to get the `rclone` name, the snapcraft community is asking for upstream approval or acknowledgement officially, please comment or reply back by acknowledging that snap packages by me has received approval for unofficial way of distributing rclone in snap store, your coordination and favour will be sincerely appreciated.

Here [my snap repo](https://github.com/boukendesho/rclone-snap)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
This is an excellent idea, thank you @boukendesho 

Please go ahead and take up maintenance of the snap package.

Let me know if you need and help.

**Comment by kapitainsky** [comment]
One pence worth of advice:

please add

```
    plugs:
      - removable-media
```
to your snap `yaml`

Otherwise snap installed rclone won't be able to access any mounted drives. You will probably have to explain to snapcraft community why rclone needs it. Should be straightforward in this case.

It is something I discovered when publishing other software using snap.

**Comment by boukendesho** [comment]
@kapitainsky Got it, thank you!

**Comment by boukendesho** [comment]
Many thanks to all of you!
