### ISSUE TITLE
Uploading to Google Shared Drive is very slow

### ISSUE THREAD

**Issue by User-26** [rclone/rclone#7230]
#### The associated forum post URL from `https://forum.rclone.org`
\-

#### What is the problem you are having with rclone?
Uploading to Google Shared Drive is very slow

#### What is your rclone version (output from `rclone version`)
rclone v1.63.1
- os/version: Microsoft Windows Server 2022 Standard 21H2 (64 bit)
- os/kernel: 10.0.20348.1668 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.20.6
- go/linking: static
- go/tags: cmount

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Microsoft Windows Server 2022 Standard 21H2 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive (Shared Drive)

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
.\rclone copy --filter '- *.sig' --filter '- DPG_*'  --filter '+ **/2021/**' --filter '- /**' --dump filters E:\export\ GoogleSharedDrive:
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2023/08/15 10:46:56 INFO  :
Transferred:       23.183 GiB / 23.832 GiB, 97%, 25.931 KiB/s, ETA 7h17m8s
Checks:             12951 / 12951, 100%
Transferred:       116912 / 126923, 92%
Elapsed time:  1d20h17m0.4s
Transferring:
 * InformationSchema export…305310 05.03.21.txt:100% /3.189Ki, 0/s, -
 * InformationSchema export…414059 14.04.21.txt:  0% /79.908Ki, 0/s, -
 * InformationSchema export…423043 23.04.21.txt:  0% /82.366Ki, 0/s, -
 * InformationSchema export…426074 26.04.21.txt:  0% /79.797Ki, 0/s, -
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by animosity22** [comment]
Please use the forums for general support.

https://forum.rclone.org

Thanks
