### ISSUE TITLE
rclone with --sftp-ssh option still checks for SSH_AUTH_SOCK

### ISSUE THREAD

**Issue by davidmonro** [rclone/rclone#7235]
#### What is the problem you are having with rclone?
I am using the new --sftp-ssh option (on a system where we use HostbasedAuthentication, which isn't supported by the inbuilt ssh client). However, while the ssh command itself works without SSH_AUTH_SOCK set, rclone aborts with the message
Failed to create file system for "systemname:/": couldn't connect to ssh-agent: SSH agent requested but SSH_AUTH_SOCK not-specified
Which shouldn't be relevant in the case that external ssh is used.

#### What is your rclone version (output from `rclone version`)
rclone v1.64.0-DEV
- os/version: rocky 9.2 (64 bit)
- os/kernel: 5.14.0-284.18.1.el9_2.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.20.4
- go/linking: dynamic
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
rocky linux 9.2 64bit

#### Which cloud storage system are you using? (e.g. Google Drive)
sftp

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone --sftp-ssh "ssh user@mysystem" lsd mysystem:/

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
$ rclone -vv --sftp-ssh "ssh user@mysystem" lsd mysystem:/
2023/08/18 16:34:17 DEBUG : rclone: Version "v1.64.0-DEV" starting with parameters ["rclone" "-vv" "--sftp-ssh" "ssh user@mysystem" "lsd" "mysystem:/"]
2023/08/18 16:34:17 DEBUG : Creating backend with remote "mysystem:/"
2023/08/18 16:34:17 DEBUG : Using config file from "/home/xxxx/.config/rclone/rclone.conf"
2023/08/18 16:34:17 DEBUG : mysystem: detected overridden config - adding "{AkS2u}" suffix to name
2023/08/18 16:34:17 NOTICE: mysystem{AkS2u}: --sftp-ssh is in use - ignoring user/host/port from config - set in the parameters to --sftp-ssh (remove them from the config to silence this warning)
2023/08/18 16:34:17 Failed to create file system for "mysystem:/": couldn't connect to ssh-agent: SSH agent requested but SSH_AUTH_SOCK not-specified


```

Contents of /home/xxxx/.config/rclone/rclone.conf:
```
[mysystem]
type = sftp
shell_type = unix
```

I'd note that the NOTICE about **ignoring user/host/port from config (remove them from the config to silence this warning)** seems to be triggered regardless of what is actually in the config file since it contains none of those parameters.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
That is two easy fixes (one for the spurious log and another for trying to contact the agent). Please give this a go.

[v1.64.0-beta.7242.46e5c9349.fix-7235-sftp-ssh](https://beta.rclone.org/branch/fix-7235-sftp-ssh/v1.64.0-beta.7242.46e5c9349.fix-7235-sftp-ssh/) on branch [fix-7235-sftp-ssh](https://github.com/rclone/rclone/tree/fix-7235-sftp-ssh) (uploaded in 15-30 mins)

**Comment by davidmonro** [comment]
This does indeed fix both problems, thank you very much!

**Comment by ncw** [comment]
Thanks for testing :-)

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.64

**Comment by f-fuchs** [comment]
Hey,

is it possible that this fix got reverted? I am using version 1.67, see below and I am also getting this error.

```
./rclone version
rclone v1.67.0
- os/version: debian 11.5 (64 bit)
- os/kernel: 5.15.0-116-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.4
- go/linking: static
- go/tags: none
```

rclone.conf
```
[beehive]
type = sftp
key_use_agent = true
disable_hashcheck = true
ssh = ssh mysystem
```

```
./rclone -vv lsd beehive:
2024/07/30 14:50:09 DEBUG : rclone: Version "v1.67.0" starting with parameters ["./rclone" "-vv" "lsd" "beehive:"]
2024/07/30 14:50:09 DEBUG : Creating backend with remote "beehive:"
2024/07/30 14:50:09 DEBUG : Using config file from "/home/fuchsfa/.config/rclone/rclone.conf"
2024/07/30 14:50:09 Failed to create file system for "beehive:": couldn't connect to ssh-agent: SSH agent requested but SSH_AUTH_SOCK not-specified
```

```
./rclone -vv --sftp-ssh "ssh fuchsfa@beehive.itwm.fraunhofer.de" lsd beehive:
2024/07/30 14:55:30 DEBUG : rclone: Version "v1.67.0" starting with parameters ["./rclone" "-vv" "--sftp-ssh" "ssh fuchsfa@beehive.itwm.fraunhofer.de" "lsd" "beehive:"]
2024/07/30 14:55:30 DEBUG : Creating backend with remote "beehive:"
2024/07/30 14:55:30 DEBUG : Using config file from "/home/fuchsfa/.config/rclone/rclone.conf"
2024/07/30 14:55:30 DEBUG : beehive: detected overridden config - adding "{qToLu}" suffix to name
2024/07/30 14:55:30 Failed to create file system for "beehive:": couldn't connect to ssh-agent: SSH agent requested but SSH_AUTH_SOCK not-specified
```

**Comment by ncw** [comment]
@f-fuchs set this to false `key_use_agent = true` and hopefully it will no longer check for the agent!

**Comment by f-fuchs** [comment]
That fixed it. Thanks a lot 👍

**Comment by RyanEwen** [comment]
I am getting the same error on v1.70.1 using a config that has the host, user, and port specified. If I remove those and use `ssh = ssh home` (where `home` is a profile in my `.ssh/config` file) then it works okay. `key_use_agent = false` did not help. Not sure if this is expected.

**Comment by ncw** [comment]
@RyanEwen 
> I am getting the same error on v1.70.1 using a config that has the host, user, and port specified.

You need to specify `pass` or `key_file` or `key_pem` or `ask_password = true` if you don't want rclone to use the ssh agent.

> If I remove those and use `ssh = ssh home` (where `home` is a profile in my `.ssh/config` file) then it works okay. `key_use_agent = false` did not help. Not sure if this is expected.
