### ISSUE TITLE
Support mod_time for Zoho Workdrive

### ISSUE THREAD

**Issue by anthonycamilleri** [rclone/rclone#7239]
I've been taking a look through the Zoho API documetation, and it would seem that it does have read support for mod_time for files via the request 

`GET https://www.zohoapis.com/workdrive/api/v1/files/{resource_id}` 

which would return

`{
   data: {
      id: "cjrrrd928be6312ac408abe79ec71db3de772",
      type: "files",
      attributes: {
         modified_by_zuid: "747938014",
         is_locked: false,
         conv_engine_type: 0,
         is_fillable_resource: false,
         is_published: false,
         destination_id: "ly9zm0170fb40015f4e2297a144e2b68cfa68",
         storage_info: {
            size: "128 bytes",
            storage_used: "128 bytes",
            files_count: 0,
            folders_count: 0,
            size_in_bytes: 128,
            storage_used_in_bytes: 128
         },
         type: "file",
         created_time_i18: "Apr 13, 10:58 AM",
         modified_time_in_millisecond: 1618291695012,
         opened_time: "Apr 13, 10:58 AM",
         status_change_time: "Apr 13, 10:58 AM",`

Modified Time seems to be supported via modified_time_in_millisecond. I was therefore wondering if someone would be able to confirm that this would be the right mod_time to include in rclone, and if anyone would be able to add it to the connector?

**Comment by ncw** [comment]
rclone does read modification times for file and directory objects accurate to a millisecond on zoho already.

Eg try `rclone lsl zoho:` to see what I mean.

However rclone has no way of setting modification times and if it can't set modification times it can't use them for syncing - hence the unsupported modtimes.

As far as I know there is no way of setting the modification time via the Zoho API

I'll close this now as mod_times are supported for reading which was what you wanted :-)
