### ISSUE TITLE
Avoid transferring duplicate files

### ISSUE THREAD

**Issue by dsrbecky** [rclone/rclone#724]
I sometimes upload several copies of the same file.  It would be nice to do server side copy instead of full re-upload if a file with the same hash already exists on the server.

**Comment by ncw** [comment]
This would rely on the remote supporting server side copy.  It would be similar to the --track-renames flag.

**Comment by animosity22** [comment]
I would think this seems to be done as we have server side copies for many remotes that support it.

If I've missed something, please let me know and we can go from there.

Thanks!
