### ISSUE TITLE
log reason why a file was copied

### ISSUE THREAD

**Issue by tooptoop4** [rclone/rclone#7250]
I understand there are 4 reasons why a file could be copied by the 'copy src_folder/ dest_folder/' command:
1. file is not present on dest_folder at all
2. file size is different
3. timestamp is different
4. hash sum is different

would be good to have option to enable this reason logging so it logs which of the 4 caused a file to be copied

**Comment by animosity22** [comment]
It is logged depending on what logging level you set.

What do you want that's not here?

**Comment by animosity22** [comment]
Closing as answered.
