### ISSUE TITLE
ProtonDrive: pass in option to override pending drafts from the command line  

### ISSUE THREAD

**Issue by henrybear327** [rclone/rclone#7251]
#### The associated forum post URL from `https://forum.rclone.org`

Please see this GitHub issue [thread](https://github.com/rclone/rclone/issues/6072#issuecomment-1691902659)

#### What is your current rclone version (output from `rclone version`)?

rclone v1.64.0-beta.7291.b95bda1e9

#### What problem are you are trying to solve?

Overriding the upload draft is a destructive operation. We are proposing to implement a temporarily overriding flag from the command line, so it can be easily specified when needed instead of having to go through the advanced config option 

#### How do you think rclone should be changed to solve that?

TBD

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by henrybear327** [comment]
Thanks to [Chippit](https://github.com/Chippit) for the suggestion. 

@ncw may I ask if you think this is a good idea to implement through the command line? If so, may I ask if there is a specific backend that has this kind of specialized implementation that I can check and follow for the implementation? 

Thank you! :)

**Comment by ncw** [comment]
What you do is make this an advanced option - then it will have a command line flag.

If you don't want it to appear in the config wizard then set `Hide:     fs.OptionHideConfigurator` in the option and rclone will only make the command line flag.

Lots of backends do stuff like this :-)
