### ISSUE TITLE
ncdu rescan / reload keypress

### ISSUE THREAD

**Issue by Matt812g** [rclone/rclone#7255]
#### The associated forum post URL from `https://forum.rclone.org`
N/A
I checked, and there was nothing related.

NOTE: I don't mean 'refresh' (^L), as that is just to remove artifacts in the rendering.  I mean to start over scanning the remote.

#### What is your current rclone version (output from `rclone version`)?
v1.63.1

#### What problem are you are trying to solve?
I want to cause ncdu to rescan the remote without having to get out and back in again.  But, the effect would be the same as if you did exit and rerun the same rclone ncdu command on the same remote again.

#### How do you think rclone should be changed to solve that?
Add a keypress that will cause ncdu to rescan the remote.

My preference is 'g', but that is taken for toggling the graph (I like emacs.)  My second favorite is 'G' (I like elfeed on emacs).

However, since there is nothing for 'r', perhaps that makes the most sense.

Pressing this key would cause the program to restart as though it had just been run with the current remote.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
From the `ncdu` man page

       r   Refresh/recalculate the current directory.

So we should probably implement exactly that. The current directory implies all of its children so if you wanted everthing recalculated you just need to be in the top level directory.

Is this something you want to have a go at @Matt812g ?

**Comment by ncw** [comment]
@eNV25 maybe you'd like to have a go at this since you have mastered the `rclone ncdu` codebase?

**Comment by eNV25** [comment]
I'll take a look.

**Comment by eNV25** [comment]
Ideally it should be as simple as calling `cancel()` from `context.WithCancel()`. But unfortunately ncdu uses `context.Background()` everywhere, and doesn't pass the context down the stack.

**Comment by eNV25** [comment]
Wait actually that's probably not that important.

**Comment by eNV25** [comment]
@ncw, I think it's done.

@Matt812g, are you able to build from source and check it out?

**Comment by Matt812g** [comment]
I will try.  Is there a how-to?

**Comment by Matt812g** [comment]
Also, does this need a doc update?  Probably different repo, huh?

**Comment by eNV25** [comment]
https://rclone.org/install/#source

https://git-scm.com/
https://go.dev/

**Comment by eNV25** [comment]
> Also, does this need a doc update? Probably different repo, huh?

Oh yea I forgot.

**Comment by eNV25** [comment]
> Also, does this need a doc update? Probably different repo, huh?

Actually those are auto-generated, so there's nothing left to do.

**Comment by Matt812g** [comment]
Building now ...

**Comment by Matt812g** [comment]
Ah, okay.  So, this is not context-sensitive.  

You had me excited that it would only do the currently selected (or entered) directory!

But, it seems to do what I originally asked for: act like I exited the app and reran it as before, right?

So, just to note, this is different from ncdu.

I love it anyway!

Thanks, @eNV25 !

**Comment by eNV25** [comment]
> Ah, okay. So, this is not context-sensitive.
> 
> You had me excited that it would only do the currently selected (or entered) directory!

Yes, doing it for the current directory only would probably require large changes to the code.

> But, it seems to do what I originally asked for: act like I exited the app and reran it as before, right?
> 
> So, just to note, this is different from ncdu.

Yes. rclone ncdu has a background process/thread/go-routine that scans the directory. The keybinding simply restarts that process.

**Comment by ncw** [comment]
@eNV25 you are a star :-) I think you are probably right - rescanning a given directory might need quite a lot of surgery but rescanning everything is very useful. Are you going to send a PR?

**Comment by eNV25** [comment]
@ncw, I sent it already. I thought it was on the sidebar. https://github.com/rclone/rclone/pull/7256

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.64

Thank you @eNV25 :-)

**Comment by eNV25** [comment]
@ncw
