### ISSUE TITLE
OneDrive certificate credentials support.

### ISSUE THREAD

**Issue by DunkinDonat** [rclone/rclone#7260]
Use-Case:
As a maintainer in an organization, I want to configure rclone for OneDrive with certificate credentials, so that I don't need to update the secret frequently.
[Reference: https://learn.microsoft.com/en-gb/azure/active-directory/develop/certificate-credentials]

Background:
Every 90 days, our refresh token expires, requiring us to create a new one to continue using rclone with OneDrive. This maintenance task is inconvenient and time-consuming. Our attempts to extend the 90-day period have been unsuccessful; unfortunately, this duration cannot be changed.

[Reference: https://learn.microsoft.com/en-us/azure/active-directory/develop/configurable-token-lifetimes]

**Comment by ncw** [comment]
I think this is the same issue as https://github.com/rclone/rclone/issues/6197 ?

**Comment by animosity22** [comment]
Closing as a duplicate.
