### ISSUE TITLE
Relying on default configuration shouldn't lead to messages printed to stderr

### ISSUE THREAD

**Issue by adamroyjones** [rclone/rclone#7261]
#### The associated forum post URL from `https://forum.rclone.org`

N/A.

#### What is your current rclone version (output from `rclone version`)?

rclone 1.63.1.

#### What problem are you are trying to solve?

I principally use rclone with Google Cloud Storage (GCS), both locally and in containers running in Kubernetes clusters (GKE). I rely on Application Default Credentials and use fully-qualified commands, e.g.

```sh
rclone copyto :gcs:foo/bar/baz /tmp/baz
```

This is fine—great, even—but there's an annoying wrinkle.

The above command will, in the absence of a configuration file, print a message to stderr, e.g.

```
2023/08/31 08:53:37 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
```

As the message is printed to stderr, the message is ingested as an ERROR-level log when running in Kubernetes (at least as it's been configured).

Adding an empty configuration file (`touch /root/.config/rclone/rclone.conf` in the above) silences the message, but littering my containers with these files is unpleasant. Redirecting stderr to /dev/null isn't a reasonable mitigation, as that might lose real errors.

#### How do you think rclone should be changed to solve that?

It'd be nice if a flag could be added, say `--use-default-config`, that would silence the (non-)error.

Alternatively, the message could be written to stdout.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
You can do this already with `--config ""`

This is documented here: https://rclone.org/docs/#config-config-file and there are some other strings you can use if you prefer.

Maybe this should be signposted in the error message, but we need to be careful not to confuse new users here who may indeed have put the config file in the wrong place.

**Comment by adamroyjones** [comment]
> If the location is set to empty string "" or path to a file with name notfound, or the os null device represented by value NUL on Windows and /dev/null on Unix systems, then rclone will keep the config file in memory only.

😮‍💨 Quite right. Time for a holiday, I think. Thanks for the quick and illuminating response!
