### ISSUE TITLE
Add a key for Box user id in rclone config section.

### ISSUE THREAD

**Issue by abdullah-0** [rclone/rclone#7267]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/rclone-api-rcd-header-for-box-api/41372

#### What is your current rclone version (output from `rclone version`)?

rclone v1.63.1
- os/version: Microsoft Windows 10 Pro 22H2 (64 bit)
- os/kernel: 10.0.19045.3324 (x86_64)               
- os/type: windows                                  
- os/arch: amd64                                    
- go/version: go1.20.6
- go/linking: static
- go/tags: cmount

#### What problem are you are trying to solve?

[Box Docs](https://developer.box.com/reference/) allow to pass a specific box user id documented [here](https://developer.box.com/guides/authentication/jwt/as-user/). Currently rclone is using `"_config":{"Headers": [{"Key": "as-user","Value": "XXXXXXXXXXX"}]} ` to pass the user id and cache it. It creates issues when working with multiple copy and other operations. 

#### How do you think rclone should be changed to solve that?

rclone should add an _as-user_ or any appropriate named key in Box type config section to store the user as it is using _impersonate_ for the google drive type config to store email. So it can be passed to headers from config section.  

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I've had a go at that - please give this a try

[v1.64.0-beta.7303.ea7eb00c1.fix-7267-box-impersonate](https://beta.rclone.org/branch/fix-7267-box-impersonate/v1.64.0-beta.7303.ea7eb00c1.fix-7267-box-impersonate/) on branch [fix-7267-box-impersonate](https://github.com/rclone/rclone/tree/fix-7267-box-impersonate) (uploaded in 15-30 mins)

You can set it in the config file as `impersonate = 0000`

Its probably most useful when used as part of a config string. So let's say you have a remote set up with JWT called `box:` you could then use `box,impersonate=0000:` to impersonate that user.

#### --box-impersonate

Impersonate this user ID when using a service account.

Settng this flag allows rclone, when using a JWT service account, to
act on behalf of another user by setting the as-user header.

The user ID is the Box identifier for a user. User IDs can found for
any user via the GET /users endpoint, which is only available to
admins, or by calling the GET /users/me endpoint with an authenticated
user session.

See: https://developer.box.com/guides/authentication/jwt/as-user/


Properties:

- Config:      impersonate
- Env Var:     RCLONE_BOX_IMPERSONATE
- Type:        string
- Required:    false

**Comment by abdullah-0** [comment]
Great work @ncw . When will it be in stable version?

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.64 which should be in a few days.

It occurs to me that this would be more useful if rclone looked up the userid from the username for you. There is an API for this. How are you discovering the user ID at the moment?

**Comment by abdullah-0** [comment]
> It occurs to me that this would be more useful if rclone looked up the userid from the username for you. There is an API for this.

I am not using that API. I get the enterprise admin service account credentials. Then use [List enterprise users](https://developer.box.com/reference/get-users/) to get all the users active/inactive. [User/Me](https://api.box.com/2.0/users/me) also need a service account.

**Comment by ncw** [comment]
rclone could take `--impersonate user@example.com` as well as `--impersonate 1234567` and if it detected an email address it could use the API to look up the ID.

Useful?

**Comment by abdullah-0** [comment]
> rclone could take --impersonate user@example.com as well as --impersonate 1234567 and if it detected an email address it could use the API to look up the ID

Very useful. But google takes email to impersonate and box takes id like 1234567 to impersonate. Both of which can be found in the user listing APIs respectively. So I think rclone does not need to look for id-from-email or email-from-id. It should only accept id for box and email for google drive. 
PS: These are the only two currently I have worked with.

**Comment by ncw** [comment]
OK I'll leave this as-is but note that it could be added

If you are working on behalf of a company you might be interested in taking out a [support contract](https://rclone.com/support) which can help you get answers quicker (and I could do the above as part of) and keeps the rclone project sustainable.

**Comment by abdullah-0** [comment]
I am very grateful for your help. I will forward the support contract suggestion to the management. Thanks for helping out.
