### ISSUE TITLE
Allow multiple destinations via `--destination-file` or similar flags

### ISSUE THREAD

**Issue by kunaltyagi** [rclone/rclone#7274]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/copy-to-multiple-destinations/13173/14

#### What is your current rclone version (output from `rclone version`)?
1.60.1

#### What problem are you are trying to solve?
Downloading from cloud is slower than manual cp. So instead of performing 2 operations: one from cloud to dest A and another from dest A to dest B, we could instruct rclone to perform the 2 operations together

#### How do you think rclone should be changed to solve that?
Some potential options:
1. `--destination-file` flag reads a file with newline separated list of destinations to copy to
2. `--extra-destination DESTINATION` for adding 1 more destination on the CLI

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
You can do this by setting up a [union](https://rclone.org/union/) of destA and destB. Rclone can then copy files to both places at once.

**Comment by kunaltyagi** [comment]
Wow thanks!! Didn't know this exists
