### ISSUE TITLE
rclone requires go 1.18 to build but docs say 1.17 is minimum version

### ISSUE THREAD

**Issue by eharris** [rclone/rclone#7288]
I was just trying to update rclone to latest stable 1.63.1, but `go install github.com/rclone/rclone@latest` now complains that golang 1.18 is required.  I have golang 1.17 installed, which the docs indicate is supported.

```
> go install github.com/rclone/rclone@latest
# github.com/rclone/rclone/fs
../devel/go/pkg/mod/github.com/rclone/rclone@v1.63.1/fs/versioncheck.go:8:15: undefined: Go_version_1_18_required_for_compilation
note: module requires Go 1.18
# github.com/rivo/uniseg
../devel/go/pkg/mod/github.com/rivo/uniseg@v0.4.4/properties.go:137:6: missing function body
../devel/go/pkg/mod/github.com/rivo/uniseg@v0.4.4/properties.go:137:20: syntax error: unexpected [, expecting (
note: module requires Go 1.18
```

I see in the changelog for v1.60.0 that 1.17 was intentionally made the minimum version.

**Comment by animosity22** [comment]
Feel free to just submit a PR to fix the docs.

**Comment by ncw** [comment]
> I was just trying to update rclone to latest stable 1.63.1, but `go install github.com/rclone/rclone@latest` now complains that golang 1.18 is required. I have golang 1.17 installed, which the docs indicate is supported.

Foo, we forgot to update the docs! Sorry.

**Comment by ncw** [comment]
I've updated the docs - the fix will go live when we do the point release - thank you!
