### ISSUE TITLE
Multithreaded copy should not set concurrency to more than the number of chunks

### ISSUE THREAD

**Issue by metadaddy** [rclone/rclone#7299]
#### What is the problem you are having with rclone?

When performing a multi-threaded chunked upload to B2, debug output indicates that more parallel streams are being used than there are chunks:

```
2023/09/13 04:46:27 DEBUG : 1gigabyte-test-file: Starting multi-thread copy with 11 chunks of size 96Mi with 16 parallel streams
```

A minor bug, and easy to fix. Inspecting `multiThreadCopy()` in `fs/operations/multithread.go`, we see that `concurrency` is set to the lesser of itself and `numChunks`, then it is set to the greater of itself and the backend concurrency:

```go
	numChunks := calculateNumChunks(src.Size(), info.ChunkSize)
	if concurrency > numChunks {
		fs.Debugf(src, "multi-thread copy: number of streams %d was bigger than number of chunks %d", concurrency, numChunks)
		concurrency = numChunks
	}

	// Use the backend concurrency if it is higher than --multi-thread-streams or if --multi-thread-streams wasn't set explicitly
	if !ci.MultiThreadSet || info.Concurrency > concurrency {
		fs.Debugf(src, "multi-thread copy: using backend concurrency of %d instead of --multi-thread-streams %d", info.Concurrency, concurrency)
		concurrency = info.Concurrency
	}
```

I believe these two sections should be reversed, so that concurrency can never exceed the number of chunks:

```go
	// Use the backend concurrency if it is higher than --multi-thread-streams or if --multi-thread-streams wasn't set explicitly
	if !ci.MultiThreadSet || info.Concurrency > concurrency {
		fs.Debugf(src, "multi-thread copy: using backend concurrency of %d instead of --multi-thread-streams %d", info.Concurrency, concurrency)
		concurrency = info.Concurrency
	}

	numChunks := calculateNumChunks(src.Size(), info.ChunkSize)
	if concurrency > numChunks {
		fs.Debugf(src, "multi-thread copy: number of streams %d was bigger than number of chunks %d", concurrency, numChunks)
		concurrency = numChunks
	}
```

#### What is your rclone version (output from `rclone version`)

```
rclone v1.64.0
- os/version: debian 11.7 (64 bit)
- os/kernel: 5.10.0-23-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.1
- go/linking: static
- go/tags: none
```

#### Which cloud storage system are you using? (e.g. Google Drive)

Copying a single 1 GB file from S3 to B2

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
rclone --no-check-dest copyto s3remote:my-s3-bucket/1gigabyte-test-file b2remote:my-b2-bucket/1gigabyte-test-file
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I've merged this to master now - thank you! -  which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.65 and v1.64.1
