### ISSUE TITLE
Allow vfs/refresh to use ListR

### ISSUE THREAD

**Issue by jcastilloalonso** [rclone/rclone#7318]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/possible-listr-support-for-onedrive-sharepoint/41832/4?u=jcastill

#### What is your current rclone version (output from `rclone version`)?

1.64.0

#### What problem are you are trying to solve?

Currently --fast-list is not supported in a mount command. This results in old fashion parallel list when vfs/refresh command is given. Ideally we should support the --fast-list flag and allow vfs/refresh to use it if remote supports it. This would help minimize API calls during a cache warmup or forget/refresh mount event.

#### How do you think rclone should be changed to solve that?

If --fast-list flag is provided during mount, we would simply allow vfs/refresh command to use ListR if supported by the remote. If flag is not provided, or remote doesn't support it, then nothing changes.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
The recursive listing is implemented by the `readDirTree` method

https://github.com/rclone/rclone/blob/9277ca1e54a4877ea481616eec60470a9030a051/vfs/dir.go#L724

Which in turn calls `walk.NewDirTree`

https://github.com/rclone/rclone/blob/9277ca1e54a4877ea481616eec60470a9030a051/fs/walk/walk.go#L587

Which will use `ListR` if available.

So, this is already done :-)

At least I have the excuse that it wasn't actually me that implemented it, it was Fabian Möller.

Sorry for getting you to make the issue unnecessarily @jcastilloalonso and I'll close it now.

**Comment by jcastilloalonso** [comment]
@ncw Great to see this was already implemented. Do you know if --fast-list flag is needed, or is vfs/refresh  always using ListR if available?
