### ISSUE TITLE
ProtonDrive Sync/Copy Never Ends

### ISSUE THREAD

**Issue by adoreparler** [rclone/rclone#7322]
First off, I really appreciate the work done for ProtonDrive, its awesome !!

#### What is the problem you are having with rclone?
When running
`rclone sync ./immich-data/ ProtonDrive:Backups/Photos/immich-data -P --transfers=10 --checkers=12 -vv`
the command never ends.

It works but after its done it just never stops and no debug logs. The 503 was from another rclone command I ran in the background.

<img width="1430" alt="Screenshot 2023-09-20 at 6 52 55 AM" src="https://github.com/rclone/rclone/assets/135237656/2f7a59a0-b385-49b9-9ce5-f1f83ff20caa">

if I do a  TCPDUMP command it shows communication happening to proton.

<img width="1411" alt="Screenshot 2023-09-20 at 6 51 34 AM" src="https://github.com/rclone/rclone/assets/135237656/11070ec8-cd39-482c-83ff-023d6cf0281c">

#### What is your rclone version (output from `rclone version`)

```
~ rclone --version
rclone v1.65.0-beta.7369.af260921c
- os/version: debian 12.1 (64 bit)
- os/kernel: 6.1.0-10-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.1
- go/linking: static
- go/tags: none
```

#### Which cloud storage system are you using? (e.g. Google Drive)
ProtonDrive

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
@adoreparler can attach the full rclone log from the transfer please? This is how I would do it so you can see the log and capture it in a file.

    rclone .... 2>&1 | tee rclone.log

Unfortunately proton drive doesn't have `--dump headers` or `--dump bodies` support at the moment so it is difficult to see exactly what is going on there.

@henrybear327 what is the best way of debugging this?

**Comment by adoreparler** [comment]
One other thing, I have a smaller set of files that I use rclone / proton drive for and that one does end since its only like 20 files. This one on the other hand is like 41 thousand files at around 500GB. 

As for logging to a file and uploading it, I would have to comb through the log and make sure that there is not any personal, keys, identification information presented in the log, not sure that is feasible as its going to log for all those 41K checks. I'll run it and take a quick look though although it may take a few hours to get to the point where its not finishing.

**Comment by ncw** [comment]
The other think you could do is get it to the point where it appears locked up, then kill -QUIT it. This will produce a backtrace of exactly what rclone is doing. Post the backtrace here (as an attachment if large)

**Comment by adoreparler** [comment]
I killed it as it has seem to stop. Honestly there is nothing different than the screenshot I have above. It does a checking of a file and just kind of lingers around after.

<img width="1183" alt="Screenshot 2023-09-20 at 10 10 21 AM" src="https://github.com/rclone/rclone/assets/135237656/d697fefe-1293-47aa-b2f1-bde7678f90cc">

and just continues on outputting the elapsed time.

here is the first few debug lines

<img width="1558" alt="Screenshot 2023-09-20 at 10 12 03 AM" src="https://github.com/rclone/rclone/assets/135237656/d0c6251a-56d3-487d-8899-0210be3880b2">

if there is something particular you want me to search for in the file I can.
The only errors in the document are the API reporting "to many request, retrying after a delay" that are sprinkled through out the log file.

**Comment by ncw** [comment]
Please don't send screenshots - they are impossible to work with! Paste the info into the issue or best of all, attach a log.

> The other think you could do is get it to the point where it appears locked up, then kill -QUIT it. This will produce a backtrace of exactly what rclone is doing. Post the backtrace here (as an attachment if large)

Please can you do this so we know where it is locked up.

You can collect the backtrace by running in a terminal with

    rclone ... 2>&1 | tee rclone.log

Then send the QUIT signal which is pressing CTRL-\ (or do `killall -QUIT rclone` from another terminal) when it locks up.

Please attach the log, or at very least edit it so it has the last few lines of the log and then the entire backtrace (which may be hundreds or thousands of lines long).

Thank you.

**Comment by adoreparler** [comment]
I ran

`rclone sync ./immich-data/ ProtonDrive:Backups/Photos/immich-data -P --transfers=10 --checkers=12 -vv 2>&1 | tee rclone.log`

and when it got to a port where it seemed it was not doing anything any more I pressed CTRL + \ and the application quit. But it did not output a backtrace. That last few lines are similar to above screenshot

```
➜  immich-app tail rclone.log 
Checks:             41860 / 41860, 100%
Elapsed time:   1h39m57.7sTransferred:                    0 B / 0 B, -, 0 B/s, ETA -
Checks:             41860 / 41860, 100%
Elapsed time:   1h39m58.2sTransferred:                    0 B / 0 B, -, 0 B/s, ETA -
Checks:             41860 / 41860, 100%
Elapsed time:   1h39m58.7sTransferred:                    0 B / 0 B, -, 0 B/s, ETA -
Checks:             41860 / 41860, 100%
Elapsed time:   1h39m59.2sTransferred:                    0 B / 0 B, -, 0 B/s, ETA -
Checks:             41860 / 41860, 100%
Elapsed time:   1h39m59.7s%   
```

**Comment by ncw** [comment]
> and when it got to a part where it seemed it was not doing anything any more I pressed CTRL + \ and the application quit.

Try the `killall -QUIT rclone` from another terminal window instead of `CTRL-\` - I think that should give the backtrace.

**Comment by adoreparler** [comment]
Attached
[backtrace.log](https://github.com/rclone/rclone/files/12684281/backtrace.log)

**Comment by adoreparler** [comment]
I just noticed that the other transfer I talked about that I thought was finishing quick, is not....
Its like 13MB and maybe around 50 files total and it takes like 45 minutes before it closed out.

if I run tcpdump of port 443, there is a ton of back and forth communication happening, but not sure what since -vv does not really report anything besides the elapsed time.

**Comment by henrybear327** [comment]
Hello @adoreparler, 

Thanks for reporting this performance issue. 

During my own testing, I did encounter issues when there are lots of files and folders being uploaded (such as if you are uploading `.git` folder), the performance will be slow. It's not hanging though, just that it's slow. 

Also, at some point the 429 error will happen since the current uploading mechanism might still be too aggresive to the Proton server, which I am also improving now!

I will shift my priority to address these issues as soon as possible! 

Cheers.

Henry

**Comment by adoreparler** [comment]
@henrybear327 if you have a PR or a Repo that I can pull and build from, I am willing to test performance against my thousands of files :P

**Comment by ajgringo619** [comment]
@henrybear327 - any news? I'm also available for testing.

**Comment by ajgringo619** [comment]
As a workaround to this issue, I've found that using a backup program that understands how Rclone remotes work (in this case, I use Restic), I can now backup all of my files with no hiccups. So for me, as others have also posted, the issue seems to be directly related to the number of files.

**Comment by m0byn** [comment]
@ajgringo619 could you explain in more detail how you got it running properly? In my case, rclone and Proton Drive is insanely slow...

**Comment by ajgringo619** [comment]
> @ajgringo619 could you explain in more detail how you got it running properly? In my case, rclone and Proton Drive is insanely slow...
I used `restic` to create a remote repo on my Proton Drive, then used `restic` to back up my files. Here's how I set this up:

1. create an `rclone` setup for `Proton Drive`; we'll use `proton` for this example.
2. create a remote `restic` repo: `restic init --repo rclone:proton:ajgringo619`
3. run a backup (this backs up my entire $HOME): `restic backup /home/ajgringo619/ --one-file-system --exclude-if-present .nosync --repo rclone:proton:ajgringo619`

DM me if you have any other questions.

**Comment by m0byn** [comment]
> > @ajgringo619 could you explain in more detail how you got it running properly? In my case, rclone and Proton Drive is insanely slow...
> > I used `restic` to create a remote repo on my Proton Drive, then used `restic` to back up my files. Here's how I set this up:
> 
>     1. create an `rclone` setup for `Proton Drive`; we'll use `proton` for this example.
> 
>     2. create a remote `restic` repo: `restic init --repo rclone:proton:ajgringo619`
> 
>     3. run a backup (this backs up my entire $HOME): `restic backup /home/ajgringo619/ --one-file-system --exclude-if-present .nosync --repo rclone:proton:ajgringo619`
> 
> 
> DM me if you have any other questions.

I was just trying to DM you, but could not find an option in Github...

Running this setup, you upload the backup directly to Proton, correct? 

Is it faster to upload than using rclone by itself? I want to sync around 300GB and it is taking more than 2 days already syncing very slow. I do not know whether a second sync is going to be faster than the first sync but not really usable at these speeds.

FYI I am using Celeste right now.

**Comment by ajgringo619** [comment]
@m0byn - my daily backups are about 50 megs, which take about 30 seconds. Rclone by itself was slow because of the many super-small files. Restic stores files in its own database format, the actual number of files being transferred is much smaller.

Is 300GB a full backup? Mine was only about 4GB, no idea how long that took.

**Comment by m0byn** [comment]
Yes - my disk size is about 350GB and I backup around 300GB of it.

**Comment by ajgringo619** [comment]
> Yes - my disk size is about 350GB and I backup around 300GB of it.

How long does a straight drag-and-drop copy via the website take? Maybe if you do that first, your daily incrementals would be much faster.

**Comment by m0byn** [comment]
That`s actually the question I have. Does restic only upload the incremental backups? And how long does rescanning work?

**Comment by ajgringo619** [comment]
> That`s actually the question I have. Does restic only upload the incremental backups? And how long does rescanning take?

I used Restic from the beginning, so its initial backup was a full one. I was getting the full 30 Mbps of my internet speed.

**Comment by buengese** [comment]
Performance for ProtoDrive has improved, if there are still issues feel free to reopen.

**Comment by htv04** [comment]
I seem to be having a large issue with Proton Drive backups. For whatever reason if I'm syncing multiple files, progress will randomly be stalled as if the connection was lost, requiring a hard exit of rclone and a resync to resume progress.

My current solution is running an infinite loop with `timeout [5-10]m rclone [args]`. Obviously this should not be necessary, though.
