### ISSUE TITLE
UpToBox shutdown

### ISSUE THREAD

**Issue by blackjack4494** [rclone/rclone#7323]
https://www.linforme.com/tech-telecom/article/descente-de-police-chez-scaleway-et-opcore-pour-couler-les-pirates-d-uptobox_998.html
paywalled article in french but google translate is enough to read headline.

Police seized servers and shutdown UpToBox.  
No clue if this will be permanent (likely tho).  
So might consider to drop support for it in the future.

**Comment by animosity22** [comment]
We try to use github for bugs/enhancements and not just communication. If you have a PR to submit to remove it, by all means. If not, we can get a feature at some point once it's removed to get it out of rclone but for now, I'm going to close this out.

**Comment by ncw** [comment]
Uptobox does look down right now. Maybe it will come back? You can see the status in [the integration tests](https://pub.rclone.org/integration-tests/current/) - it passed this morning so this must be very recent news.

```
$ rclone lsf TestUptobox:
2023/09/20 21:20:51 Failed to create file system for "TestUptobox:": HTTP error 404 (404 Not Found) returned body: "<html>\n<head><title>404 Not Found</title></head>\n<body>\n<center><h1>404 Not Found</h1></center>\n<hr><center>nginx/1.24.0</center>\n</body>\n</html>\n"
```

**Comment by blackjack4494** [comment]
> Uptobox does look down right now. Maybe it will come back? You can see the status in [the integration tests](https://pub.rclone.org/integration-tests/current/) - it passed this morning so this must be very recent news.

It's just very unlikely it will come back.
Vast majority of this service was used for piracy activities.

@animosity22 
I am aware of it. This issue was meant to be a reference point. As it is unlikely the host will come back. I just don't know how "removing a backend" situation is handled. 
However submitting a PR right away didn't seem to be best option at first. 👋
