### ISSUE TITLE
Detrimental listing of Regions in S3 backend documentation

### ISSUE THREAD

**Issue by JacobCarrell** [rclone/rclone#7325]
Version: documentation published at https://rclone.org/s3/ at time of issue submission.

This isn't an issue with the executable, but rather the documentation. The documentation goes on, at extreme length, to list all the regions for the different providers.

This is actively harmful to the people maintaining the documentation, and those of us trying to use it.

Examples include:
1. Users either picked the region(s) when creating their bucket, or will need to be told which region(s) they can use by whichever entity is providing access.
2. Providing an exhaustive list of regions is impractical, maintenance heavy, and will list regions or providers that no longer exist.
3. Third, and worst, it bloats the S3 page (https://rclone.org/s3), so much that it makes it very difficult to actually read it. Especially on Phones/tablets.

I propose one of the following as a remedy, in personal order of preference:
* Remove it entirely- provide only a handful of examples (in total) from the most prominent regions of the top providers (eg. us-east-1)
* Link to providers' pages of regions
* Move the list of regions to a separate page. This addresses only the difficulty of reading through the main S3 page. It does not reduce documentation maintenance.

If approved, I'm willing to provide a PR with the agreed change.

Thanks for the consideration, and hopefully this isn't a better fit for feature request.

**Comment by JacobCarrell** [comment]
Example user case: I was/am trying to determine if rclone supports adding an arbitrary metadata tag, and gave up because I spent 2 minutes scrolling through lists of regions.

**Comment by JacobCarrell** [comment]
I'll get started now.

**Comment by ncw** [comment]
> Version: documentation published at https://rclone.org/s3/ at time of issue submission.
> 
> This isn't an issue with the executable, but rather the documentation. The documentation goes on, at extreme length, to list all the regions for the different providers.

It does, yes!

> This is actively harmful to the people maintaining the documentation, and those of us trying to use it.

Note that those docs are auto generated, so don't edit them directly.

> Examples include:
> 
> 1. Users either picked the region(s) when creating their bucket, or will need to be told which region(s) they can use by whichever entity is providing access.
> 2. Providing an exhaustive list of regions is impractical, maintenance heavy, and will list regions or providers that no longer exist.
> 3. Third, and worst, it bloats the S3 page (https://rclone.org/s3), so much that it makes it very difficult to actually read it. Especially on Phones/tablets.
> 
> I propose one of the following as a remedy, in personal order of preference:
> 
> * Remove it entirely- provide only a handful of examples (in total) from the most prominent regions of the top providers (eg. us-east-1)
> * Link to providers' pages of regions
> * Move the list of regions to a separate page. This addresses only the difficulty of reading through the main S3 page. It does not reduce documentation maintenance.

I think the best first step might be to make sure we only show one of each option type. For example we show `region` for each provider. If we just showed the first (which is AWS) then that would be sufficient.

This will need a patch to the doc generator though

In fact looking at the doc generator it appears to have that in already, but it doesn't work!

Fixing it I get this which removes 1,167 lines of documentation out of the 3,703 total.

```
$ wc -l s3.docs.0 s3.docs.1
  2536 s3.docs.0
  1167 s3.docs.1
  3703 total
```

I've attached the before and after. What do you think - good enough?

[s3.docs.1.txt](https://github.com/rclone/rclone/files/12703057/s3.docs.1.txt)
[s3.docs.0.txt](https://github.com/rclone/rclone/files/12703058/s3.docs.0.txt)

And here is the code

[v1.65.0-beta.7383.1b3d1b275.fix-7325-doc-generator](https://beta.rclone.org/branch/fix-7325-doc-generator/v1.65.0-beta.7383.1b3d1b275.fix-7325-doc-generator/) on branch [fix-7325-doc-generator](https://github.com/rclone/rclone/tree/fix-7325-doc-generator) (uploaded in 15-30 mins)

Generate the s3 docs with

    rclone help backend s3

**Comment by JacobCarrell** [comment]
Fantastic! Thank you! I was going to edit the .md file, which obviously would have been wasted effort- I didn't know the docs were generated from the executable itself. That'll make working with rclone much easier!

**Comment by ncw** [comment]
@JacobCarrell what did you think of the before and after? Good enough? Shall I merge that change? Do we need to do more work?

**Comment by JacobCarrell** [comment]
Yes, please merge it. It's addressed all the concerns I presented in this issue.

**Comment by ncw** [comment]
Great! Thanks for taking a look.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.65 . I'll put the changes up for v1.64.1 also.

**Comment by JacobCarrell** [comment]
Absolutely fantastic! Thank you for your work. Is there somewhere you'd like a small donation to go?

**Comment by ncw** [comment]
You can check the options out here: https://rclone.org/sponsor/ - thank you :-)
