### ISSUE TITLE
Set 'Last-Modified' for files served by '--rc-serve'

### ISSUE THREAD

**Issue by ShoshinNikita** [rclone/rclone#7329]
#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.64.0-DEV
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.90.1-microsoft-standard-WSL2 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.0
- go/linking: static
- go/tags: none
```

#### What problem are you are trying to solve?

Files served by `--rc-serve` don't have the `Last-Modified` header. Here you can see the comparison of response headers for the same file:

<table>
<tr>
<th>

`rclone serve http`
</th>
<th>

`rclone rcd --rc-no-auth --rc-serve`
</th>
</tr>

<tr>
<td>

```diff
Accept-Ranges: bytes



Content-Length: 73
Content-Type: text/plain; charset=utf-8
Server: rclone/v1.64.0-DEV
Date: Thu, 21 Sep 2023 23:56:15 GMT
+Last-Modified: Sat, 23 Jul 2022 15:17:10 GMT
```
</td>

<td>

```diff
Accept-Ranges: bytes
+Access-Control-Allow-Headers: authorization, Content-Type
+Access-Control-Allow-Origin: http://127.0.0.1:5572/
+Access-Control-Request-Method: POST, OPTIONS, GET, HEAD
Content-Length: 73
Content-Type: text/plain; charset=utf-8
Server: rclone/v1.64.0-DEV
Date: Thu, 21 Sep 2023 23:51:08 GMT
 
```
</td>
</tr>
</table>

#### How do you think rclone should be changed to solve that?

As I can see, we can't just set the `Last-Modified` header in the function `lib/http/serve.Object` because `(fs.DirEntry).ModTime()` can make additional requests. Maybe we can accept some query param (for example `?modTime=true`), so users who need this information would be able to access it?

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Are those headers for a `HEAD` or a `GET` request?

If you make the `Last-Modified` conditional on the `f.Features().SlowModTime` then you can be sure it won't take another transaction.

Though I note we are already reading mime type which can take another transaction. And in fact in `s3` which is the most popular backend with `SlowModTime` the act of reading the mime type will have done a transaction which pulls in the modtime already. So calling ModTime after it won't cause any transactions.

If you delay setting the `Last-Modified` header until after the `o.Open` then all the backends I can think of will have read the modtime into `o` at that point. That won't work for `HEAD` requests though.

Anyway, after thinking about it, I'd say we should probably just read the ModTime for everything and set LastModified regardless so it works for `HEAD` and `GET`.

Do you want to send a PR for that?

**Comment by ShoshinNikita** [comment]
Thanks for the detailed answer! I have sent a PR to fix this issue.
