### ISSUE TITLE
oracleobjectstorage  oos- archive storage - should allow to do a "backend restore"

### ISSUE THREAD

**Issue by jmichler** [rclone/rclone#7371]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/rclone-backed-restore-oracle-oci/32571

#### What is your current rclone version (output from `rclone version`)?
pi@raspberrypi:~ $ rclone version
rclone v1.64.0
- os/version: raspbian 11.8 (64 bit)
- os/kernel: 6.1.21-v8+ (aarch64)
- os/type: linux
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.21.1
- go/linking: static
- go/tags: none

#### What problem are you are trying to solve?
Using the Oracle Cloud Infrastructure (OCI) Object storage I'd like to backup and restore to archive storage ().
I can setup a backup to Archive storage (as also described here: https://rclone.org/oracleobjectstorage/)

#### --oos-storage-tier

The storage class to use when storing new objects in storage. https://docs.oracle.com/en-us/iaas/Content/Object/Concepts/understandingstoragetiers.htm

Properties:

- Config:      storage_tier
- Env Var:     RCLONE_OOS_STORAGE_TIER
- Type:        string
- Default:     "Standard"
- Examples:
    - "Standard"
        - Standard storage tier, this is the default tier
    - "InfrequentAccess"
        - InfrequentAccess storage tier
    - "Archive"
        - Archive storage tier

Creating backups is working fine, but restore fails:
 rclone sync -v jmichlerace_archive:archive-rclone-tests sync-tests2

 Error returned by ObjectStorage Service. Http Status Code: 409. Error Code: NotRestored. Opc request id: fra-1:0TggNoT3SZI2uWyfZEvUNIr8J72Hy0TrKAixJtFpCpQqQWY7pU-48llRfdmAfscy. Message: The object is in Archive tier and needs to be restored.

I could probably over the OCI UI "restore" every single file, but this is highly inconvenient.

I tried as in the forum post to run a backend restore; but that gives me:
pi@raspberrypi:~ $ rclone backend restore jmichlerace_archive:archive-rclone-tests/ -n
2023/10/14 23:29:46 Failed to backend: "restore" command not found

#### How do you think rclone should be changed to solve that?

dynamically restore on a failed access or provide the "rclone backend restore" command for oos as well that is available for s3.

Documentation from Oracle side is over there: https://docs.oracle.com/en-us/iaas/Content/Object/Tasks/managingobjects_topic-To_restore_objects_from_Archive_Storage.htm

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
This needs to be ported over from the s3 backend. 

@msays2000 do you want to have a go at this? Or maybe you'd like to @jmichler ?

**Comment by msays2000** [comment]
@ncw yes I can provide support for it, i will try to find another collaborator on oracle backend support. If I cannot find some collaborators in couple of weeks, I can provide the code.

**Comment by jmichler** [comment]
@msays2000 great. Should you need any support/testing with a Oracle Backend let me know. I know a bunch of things on OCI but nothing on the implementation of rclone itself unfortunately

**Comment by msays2000** [comment]
@jmichler FYI, I assume you want rclone to just trigger the restore of a object if not already restoring and not wait for it as it will be useless to wait for 1 hour. 

```
Restore an object from Archive Storage to Object Storage.

Depending on the size of the object, it can take at most an hour to restore an object from Archive Storage. You can’t download an item object until the item is fully restored.

By default, you have 24 hours to download an object after restoration. Alternatively, you can specify a download time from 1 to 240 hours. You can find out how much download time is remaining by looking at the Available for Download value in the object’s details. 
```

**Comment by jmichler** [comment]
@msays2000 the question is if a sync would trigger it implicitly or if we have a dedicated "restore" command. I think for s3 the approach is the latter one, then probably the user would need to issue the restore first and then a sync would fail if documents are not (yet) available in non-archive-storage.
How is this solved for AWS glacier?

**Comment by msays2000** [comment]
yes its the later one, where one needs to execute restore command first and then a sync would fail if documents are not (yet) available in non-archive-storage.

behavior is same as aws glacier.

**Comment by anders-swanson** [comment]
@msays2000 is this still looking for a contributor?

**Comment by msays2000** [comment]
> @msays2000 is this still looking for a contributor?

Yes, we are still looking for contributors.
