### ISSUE TITLE
When using the rclone check command to verify large directory data, the program may experience errors and crashes

### ISSUE THREAD

**Issue by xiufeng2012** [rclone/rclone#7375]
hi sir:
    I am currently using rclone check for object storage data verification, and the number of directory files that need to be verified is very large, with over 100w;

1. The commands I use are as follows:
/root/rclone/rclone check    minio-source:xx/1035IC/   s3-target:xx/1035IC/   -P

2. The error message is as follows:
`Elapsed time:    1h7m19.0sTransferred:                    0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:    1h7m19.5sTransferred:                    0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:    1h7m20.0sTransferred:                    0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:    1h7m20.5sTransferred:                    0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:    1h7m21.0sTransferred:                    0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:    1h7m21.5sTransferred:                    0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:    1h7m22.0sTransferred:                    0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:    1h7m22.5sTransferred:                    0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:    1h7m23.0sTransferred:                    0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:    1h7m23.5sTransferred:                    0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:    1h7m24.0s
2023-10-16 23:56:12 ERROR : S3 bucket xx 1035IC: error reading source root directory: SerializationError: failed to unmarshal error message
        status code: 500, request id: , host id: 
caused by: UnmarshalError: failed to unmarshal error message
        00000000  49 6e 74 65 72 6e 61 6c  20 53 65 72 76 65 72 20  |Internal Server |
00000010  45 72 72 6f 72 00 00 00  00 00 00 00 00 00 00 00  |Error...........|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000080  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000a0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000d0  00 00 00 00 00 00 00 00  00 00 00 00 00           |.............|

caused by: XML syntax error on line 1: illegal character code U+0000
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:    1h7m24.0s
2023-10-16 23:56:12 NOTICE: S3 bucket xx path 1035IC: 1 differences found
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:    1h7m24.0s
2023-10-16 23:56:12 NOTICE: S3 bucket xx path 1035IC: 1 errors while checking
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:    1h7m24.0sTransferred:                    0 B / 0 B, -, 0 B/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:    1h7m24.0s
`

3. Rclone version:
rclone v1.61.1
- os/version: centos 7.6.1810 (64 bit)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.4
- go/linking: static

4.Which cloud storage system are  using? 
minio

Thank you in advance for your time！

**Comment by kapitainsky** [comment]
Please update your rclone version to the latest available (v1.64.1) and open `Help and Support` on rclone forum - https://forum.rclone.org/ providing all requested information.

Github should be used only for tracking new features and confirmed bugs.

**Comment by Animosity022** [comment]
Closing out. Please use the forums:

https://forum.rclone.org for General Support.
