### ISSUE TITLE
Can't mount S3 on versions higher than 1.61.1

### ISSUE THREAD

**Issue by venomone** [rclone/rclone#7377]
Hello folks,

I'm using rclone within a docker container builded from "python:3.11.4-slim-bullseye" image to mount a bucket from my minio s3 storage. The problem is that I'm not able to properly mount my volume anymore if I use a rclone higher than 1.61.1. All newer versions keep failing with this error:

2023/10/19 09:35:48 DEBUG : Creating backend with remote "cdn:media"
2023/10/19 09:35:48 DEBUG : Using config file from "/home/cont/.config/rclone/rclone.conf"
2023/10/19 09:35:48 DEBUG : Resolving service "s3" region "minio"
2023/10/19 09:36:48 DEBUG : Daemon timed out. Terminating daemon pid 776
2023/10/19 09:36:48 Fatal error: mount not ready: /srv/webdav/media

The minio s3 runs within the same container as rclone on 127.0.0.1:7777 and is basically this piece of software from StorJ -> https://github.com/storj/gateway-st

This is the mount command I use:

rclone mount cdn:media /srv/webdav/"$S3_MEDIA_BUCKET" \
      --async-read \
      --buffer-size 32M \
      --cache-chunk-size 16M \
      --cache-dir /cache/media \
      --cache-tmp-wait-time 60m \
      --cache-workers=6 \
      --checkers 500 \
      --daemon \
      --dir-cache-time "$INDEX_CACHE_TIME_SEC" \
      --drive-chunk-size 256M \
      --max-read-ahead 16M \
      --poll-interval 60m0s \
      --read-only \
      --no-modtime \
      --no-checksum \
      --no-seek \
      --transfers 500 \
      --umask 0000 \
      --use-server-modtime \
      --vfs-cache-max-age 120m \
      --vfs-cache-max-size 1G \
      --vfs-cache-mode full \
      --vfs-read-ahead 16M \
      --vfs-read-chunk-size 32M \
      --volname media
      
As already mentioned, this bugs occurs since rclone versions > 1.61.1

Thanks in advance :)

**Comment by Animosity022** [comment]
Best to use the forums at https://forum.rclone.org

Please actually use the help and support template and include all the information if you'd like assistance.
