### ISSUE TITLE
Proton Drive session expires too quickly

### ISSUE THREAD

**Issue by blkqi** [rclone/rclone#7381]
#### What is the problem you are having with rclone?

Proton Drive sessions expire after approximately 1-2 days of inactivity. For accounts with 2FA enabled, this forces the user to manually provide a new 2FA code in the rclone config and acquire a new session token. This issue prevents the application from being fully automatable for 2FA-enabled accounts.

According to the documentation for [Proton session management](https://proton.me/support/log-out-all-other-sessions):
> Unless you explicitly log out of a session, all sessions expire after 60 days of inactivity. 

I've never actually used the official Proton Drive application for Windows or macOS, but I suspect that client sessions do in fact last much longer than a few days. Certainly, the sessions for Proton Mail (web) and Proton VPN for Windows do.

I expect that something similar should be achievable within rclone.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.64.0-beta.7351.fa4d171f6
- os/version: slackware 15.0+ (64 bit)
- os/kernel: 6.1.38-Unraid (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.1
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Linux, 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)

Proton Drive

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by henrybear327** [comment]
Hello @blkqi,

Thanks for reporting!

The token should be automatically renewed. May I ask if you can upload the log file when this happen again for you?

If I recall correctly, the token usually expires around 24 hours, and the token refresh will be performed. 

One case I have ran into before was if you ran more than 1 rclone instances at the same time, and the token refresh happens, the race condition will cause the refresh to fail. 

Henry

**Comment by ncw** [comment]
@henrybear327 
> One case I have ran into before was if you ran more than 1 rclone instances at the same time, and the token refresh happens, the race condition will cause the refresh to fail.

This is a solved problem if you can move the backend over to using `lib/oauthutil`!

**Comment by blkqi** [comment]
After ensuring that only one instance of `rclone` was running at a time, my login token was successfully renewed after a week of inactivity. Thanks for the assistance @henrybear327

**Comment by LivingUserError** [comment]
> @henrybear327
> 
> > One case I have ran into before was if you ran more than 1 rclone instances at the same time, and the token refresh happens, the race condition will cause the refresh to fail.
> 
> This is a solved problem if you can move the backend over to using `lib/oauthutil`!

Has this been done yet / is it possible? Because I still have this problem and I would really like to have more than one instance running (for backups + bisync).

**Comment by Freeedim** [comment]
@henrybear327 

Sorry for the maybe stupid question, but how do you ensure (or at least check) that there is only one instance of rclone?

I have placed an `rclone sync` in cron. It worked for a bit, but when turning off my laptop for a couple of days, it lost the credentials. I have never manually used rclone since the cron job was created, only the cron calls it, every 5 minutes, for a quick sync (a handful of files below 2 MB, possibly changing slightly from a sync to the next, over a very good connection).

**Comment by ncw** [comment]
> Sorry for the maybe stupid question, but how do you ensure (or at least check) that there is only one instance of rclone?

An easy, cross platform way is to add the `--rc` flag. You can only have one thing listening on that port at once.

Of you can use something like this in cron

```
* * * * * /usr/bin/flock -n /tmp/rclone.lock rclone sync ...
```

**Comment by skynw** [comment]
Hello,
I am using a cronjob for bisync every 5min and I still need to enter the 2FA every day.
As rclone is difficult to understand for me (in moment) I dont know, if its a bug, or just a wrong setting I am using. or is it a known problem?
thanks
Marcel

**Comment by LivingUserError** [comment]
> Hello, I am using a cronjob for bisync every 5min and I still need to enter the 2FA every day. As rclone is difficult to understand for me (in moment) I dont know, if its a bug, or just a wrong setting I am using. or is it a known problem? thanks Marcel

It is possible that the cronjob runs too frequently. Having two processes access Proton Drive via Rclone at the same time has caused problems in the past. If it is acceptable, try whether the problem persists with the cronjob running every 10 or 20 minutes.

If that does not solve your problem, I have [posted scripts](https://github.com/rclone/rclone/issues/7864#issuecomment-2504770236) (with instructions how to use them) that back up your session info. They are fish scripts however, so you would need to either install fish first, or adapt them to bash/powershell/whatever. They definitely work for me.
