### ISSUE TITLE
rclone copy to google drive copying data twice, first copy correct, second is into an unwanted folder structure.

### ISSUE THREAD

**Issue by thaynes2023** [rclone/rclone#7382]
#### rclone v1.64.2
- os/version: ubuntu 22.04 (64 bit)
- os/kernel: 5.15.0-86-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.3
- go/linking: static
- go/tags: none

#### The command you were trying to run (eg `rclone copy /tmp remote:tmp`)  

```
rclone copy /var/www/html/ googledrive:/appbackup/adminhtml/
```

#### Please run 'rclone config redacted' and share the full output. If you get command not found, please make sure to update rclone.

```
[googledrive]
type = drive
scope = drive
token = XXX
team_drive =
```

#### I am copying all contents of the source to the dest.
I see all the data get copied, but then it creates additional folder structure and copies the files there also.

I expect to see this structure
```
->/appdata
    ->/adminhtml
          ->files
```
but I am getting this. I don't know why it's copying the files twice and why it' building the googledrive/appbackup/adminhtml path and putting files there.
```
->/appdata
     ->/adminhtml
             ->files (desired result)
             ->/googledrive
                      ->/appbackup
                            ->/adminhtml
                                 -> another copy of files
```

example showing the files are copied twice.

```
ubuntu@sqlserver:~$ rclone ls googledrive:/appbackup/adminhtml/ | grep qcreate.php
     7637 qcreate.php
     7637 googledrive/appbackup/adminhtml/qcreate.php
```

```

```
ubuntu@sqlserver:~$ rclone ls googledrive: | grep qcreate.php
     7637 appbackup/adminhtml/qcreate.php
     7637 appbackup/adminhtml/googledrive/appbackup/adminhtml/qcreate.php
```

**Comment by ncw** [comment]
Can you make a reproduction of this with a small number of files please. Something I can try here.

I think this is probably user error (maybe you fun the copy with the wrong parameters, or maybe there is a shortcut), but if you can make a replication for me demonstrating the problem then I will fix it.

Thank you

**Comment by Animosity022** [comment]
OP has posted on the forums already for this...
