### ISSUE TITLE
Command line progress percentage

### ISSUE THREAD

**Issue by AP2020C** [rclone/rclone#7386]
I searched for similar issues but could not find any.

#### What is your current rclone version (output from `rclone version`)?
1.64.2

#### What problem are you are trying to solve?
When I run a long operation such as a command line copy, I would like to be shown the percentage of progress, MB already copied, current and average speed, number of files already copied and remaining

#### How do you think rclone should be changed to solve that?
Add lines below the sent command that update, without always adding new lines

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
You generally already get that minus the percentage.

```
      --max-backlog int                             Maximum number of objects in sync or check backlog (default 10000)
```

Rclone only works on 10k files at a clip to prevent reading too much ahead on a remote. Make that  unlimited and you get what you want.

**Comment by ncw** [comment]
> When I run a long operation such as a command line copy, I would like to be shown the percentage of progress, MB already copied, current and average speed, number of files already copied and remaining

Perhaps try the `-P` flag? This adds an updating stats for exactly those things.

**Comment by AP2020C** [comment]
Thank you!!! -P seems to do what I was looking for.
