### ISSUE TITLE
Case Sensitive when checking hash values

### ISSUE THREAD

**Issue by dgarvis** [rclone/rclone#7388]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/hash-mismatch-case-sensitive/42500

#### What is the problem you are having with rclone?

Sometimes when checking downloaded file vs server file, the hash is lowercase vs uppercase and does not match. Out of about 10K files, it happened 31 times. It appears to be the same files each time I run the command, my hypothesis is that the proton drive server sometimes stores hashes with a different case than what rclone is expecting.

#### What is your rclone version (output from `rclone version`)

rclone v1.64.2

os/version: ubuntu 22.04 (64 bit)
os/kernel: 6.2.6-76060206-generic (x86_64)
os/type: linux
os/arch: amd64
go/version: go1.21.3
go/linking: static
go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Ubuntu

#### Which cloud storage system are you using? (e.g. Google Drive)

ProtonDrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
rclone sync -P -vv --checkers=10 --size-only drive:folder folder
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

31 of these errors, just different files.
```
ERROR : myfile.partial: corrupted on transfer: sha1 hash differ "BFAC50DE6235DEAAAB7A63030EB7037AFB4143AE" vs "bfac50de6235deaaab7a63030eb7037afb4143ae"
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
@henrybear327 this sounds like a bug in the backend - it needs to lowercase the hashes.

**Comment by TheNightRider12** [comment]
I think this issue is similar to this already opened issue
https://github.com/rclone/rclone/issues/7345
He has an issue opened on the Github repo for the backend as well for this one. If this issue is to be the same as the one I linked.

**Comment by ncw** [comment]
I'll close this one as a dupe as the other seems to say the same thing.
