### ISSUE TITLE
Digipost new backend

### ISSUE THREAD

**Issue by holyhope** [rclone/rclone#7394]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/digiposte-backend/42591

#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.64.2
- os/version: darwin 13.6 (64 bit)
- os/kernel: 22.6.0 (arm64)
- os/type: darwin
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.21.3
- go/linking: dynamic
- go/tags: none
```

#### What problem are you are trying to solve?

Interacting with files stored on Digipost (<digiposte.fr>)

#### How do you think rclone should be changed to solve that?

Rclone should support a new backend configuration.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
Odds are it sits in the abyss of new backends unless you plan to PR for it or sponsor it.

**Comment by holyhope** [comment]
Thank you for the comment, I emailed the Digiposte team, they told me that they have no plan to work on that at this moment.
