### ISSUE TITLE
Folders getting "hogged" / locked by rclone.

### ISSUE THREAD

**Issue by c3m0** [rclone/rclone#7395]
#### What is the problem you are having with rclone?
I can't delete local folders that have involved rsync operations. They get locked.

#### What is your rclone version (output from `rclone version`)
rclone v1.64.0 (yeah I know both .1 and .2 are available but I havn't updated yet and changelog doesn't give the impression that this particular issue has been addressed nonetheless resolved sooo..)

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
W10 x64 Pro

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
I'm going to go a bit sideways when answering this question since my issue doesn't resolve rsync "crashing" or anything like that, but rather how the rsync executable locks local folders. In short, say I have my OneDrive mounted on O:\ and I have a folder C:\ASDF on my local machine. I move some (or even all) files from C:\ASDF to O:\ and it is successful, yaaay. Now, I think that I don't want this empty folder on my local machine any more, so I try to delete it.

_C:\>rmdir ASDF
The process cannot access the file because it is being used by another process._

I use ProcessHacker to find what software is locking a handle on the folder to speak, and it informs me that RLCONE.EXE is the culprit. Weird, since operation is done and successful. It shouldn't be locking C:\ASDF anymore. However, I pull a "TSKILL RCLONE" (terminate the run) and then the ASDF folder is free:d upp immediately so that it can be deleted.

Can this be fixed easily?

Oh, my mount command syntax (if it matters) is the following:
_RCLONE.EXE --no-console --file-perms=0777 --vfs-cache-mode full mount my-onedrive: o:_

Thanks for any input on this delicate matter.
Cheers!

**Comment by Animosity022** [comment]
Please use the forums for general support.

Use the help and support template and post the actual debug log file.

Much appreciated.
