### ISSUE TITLE
Not able to transfer empty directories from azure file shares to AWS S3 bucket using command >>>>  rclone.exe -P sync ./ s3:<my_bucket>

### ISSUE THREAD

**Issue by HimanshuGarg011** [rclone/rclone#7408]
I am trying to transfer my azure file shares data to AWS S3 bucket using RCLONE.

All the directories and subdirectories got transferred to S3 bucket which contains the files. But empty directories were missing in the destination(S3 bucket)

Using below command to perform this copy actions --
cd <folder to copy>
 rclone.exe -P sync ./ s3:<my_bucket>

I also tries to add flag --create-empty-src-dirs and use below command, but it also not transferring the empty directories to S3 bucket.
rclone.exe -P sync ./ s3:<my_bucket> --create-empty-src-dirs

Please suggest.

**Comment by albertony** [comment]
I don't think empty directories are supported by this backend, see https://rclone.org/overview/#optional-features, so there's not much one can do.

**Comment by Animosity022** [comment]
Closing as this should be a forum question.
