### ISSUE TITLE
--max-duration cuts off instantly after reaching deadline when using B2

### ISSUE THREAD

**Issue by AndyIbanez** [rclone/rclone#7409]
#### The associated forum post URL from `https://forum.rclone.org`

I have not posted this in the forums, but this old discussion is essentially the same:

https://forum.rclone.org/t/max-duration-hard-limit-changed-to-soft-limit/14938

#### What is the problem you are having with rclone?

I want to setup backup tasks that run at midnight and run for 10 hours. I have done the tests with 30 minutes and the transfer ends instantly when using B2, not allowing transfers to finish.

I have found [this issue](https://github.com/rclone/rclone/issues/4002) from 2020. Perhaps it's a regression issue?

I should mention that I'm using the Docker version from Docker Hub.

#### What is your rclone version (output from `rclone version`)

v1.64.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Synology DSM 7

#### Which cloud storage system are you using? (e.g. Google Drive)

Local hard drive to Backblaze B2.

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone sync --log-level DEBUG --log-file "$LOG_FILE" --fast-list --transfers 4 --max-duration 30m --b2-hard-delete /mnt/Plex REMOTE:BUCKET/Servers/Kokiri --backup-dir REMOTE:BUCKET/SafetyNet/Kokiri/$DATE --exclude="@eaDir/**"

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

Excerpt from my log:

```
 Failed to copy: multi-thread copy: failed to write chunk: Post "https://pod-000-1125-07.backblaze.com/b2api/v1/b2_upload_part/4_zf3ef5c4df93e32e388bc0217_f22340f765119b1fa_d20231108_m025931_c002_v0001125_t0017_u01699412371175/0019": context deadline exceeded
2023/11/08 03:07:17 ERROR : B2 bucket BUCKET path Servers/Kokiri: not deleting files as there were IO errors
2023/11/08 03:07:17 ERROR : B2 bucket BUCKET path Servers/Kokiri: not deleting directories as there were IO errors
2023/11/08 03:07:17 ERROR : B2 bucket BUCKET path Servers/Kokiri: max transfer duration reached as set by --max-duration
2023/11/08 03:07:17 ERROR : Fatal error received - not attempting retries
2023/11/08 03:07:17 INFO  : 
Transferred:   	    6.627 GiB / 8.950 TiB, 0%, 6.177 MiB/s, ETA 2w3d13h
Errors:                 5 (fatal error encountered)
Transferred:            4 / 8564, 0%
Elapsed time:      30m1.2s
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
It's neither.

The default is hard cutoff so that's expected.

https://rclone.org/docs/#cutoff-mode-hard-soft-cautious

It's documented above. Change it to what you'd want.

**Comment by AndyIbanez** [comment]
@Animosity022 thanks, no clue how I missed that. I am closing this issue.

**Comment by Animosity022** [comment]
I think it was changed maybe at some point, but I honestly can't recall so no worires at all. A quick answer is always good as I always ask if I'm not sure too!
