### ISSUE TITLE
Yandex.Disk restarts upon succesful completion

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#741]
Hi,

Thank you very much for the rclone project and your hard work.

I have an issue that comes up when my sync to Yandex completes, it starts over again.
When I cancel the retry attempt and look in Yandex, the file is there and it is completed (sha1 matches).
It will keep retrying indefinitely, even though it's completed already.

> **What is your rclone version (eg output from `rclone -V`)**
> rclone v1.33-DEV
> 
> **Which OS you are using and how many bits (eg Windows 7, 64 bit)**
> Linux 4.4.21-1-MANJARO x86_64 GNU/Linux
> 
> **Which cloud storage system are you using? (eg Google Drive)**
> Yandex.Disk
> 
> **The command you were trying to run (eg `rclone copy /tmp remote:tmp`)**
> rclone sync /home/mammoth/Yandex/  Yandex:Files
> 
> **A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)**
> 2016/09/21 19:09:19 Yandex Files: Modify window is 1ns
> 2016/09/21 19:09:20 Yandex Files: Waiting for checks to finish
> 2016/09/21 19:09:20 Yandex Files: Waiting for transfers to finish
> 2016/09/21 19:09:25 Yandex Files: Waiting for checks to finish
> 2016/09/21 19:09:26 Yandex Files: Waiting for transfers to finish
> 2016/09/21 19:09:27 Yandex Files: Waiting for checks to finish
> 2016/09/21 19:09:27 Yandex Files: Waiting for transfers to finish

Here's what it looks like when it happens:

2016/09/21 19:02:10 
Transferred:   3.730 GBytes (2.045 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     31m7.6s
Transferring:
-                                          file.7z: 97% done. avg: 2105.4, cur: 1469.2 kByte/s. ETA: 1m17s

2016/09/21 19:03:10 
Transferred:   3.838 GBytes (2.039 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     32m7.6s
Transferring:
- file.7z

2016/09/21 19:04:10 
Transferred:   3.838 GBytes (1.977 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     33m7.6s
Transferring:
- file.7z

2016/09/21 19:05:10 
Transferred:   3.838 GBytes (1.919 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     34m7.6s
Transferring:
- file.7z

2016/09/21 19:06:10 
Transferred:   3.838 GBytes (1.865 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     35m7.6s
Transferring:
- file.7z

2016/09/21 19:07:10 
Transferred:   3.838 GBytes (1.813 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     36m7.6s
Transferring:
- file.7z

2016/09/21 19:08:10 
Transferred:   3.844 GBytes (1.767 MBytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:     37m7.6s
Transferring:
-                                          file.7z:  0% done. avg:  548.2, cur:  295.0 kByte/s. ETA: 3h47m5s

**Comment by ncw** [comment]
Can you attach a log with the `-v` flag please?

**Comment by mastad0n** [comment]
Hey, sorry for the delay and thank you for not closing my ticket.

Here is the -v output:


`

> [mastadon@mastadon ~]$ rclone -v sync /home/mastadon/test/ Yandex:Files
> 2016/10/19 01:36:37 rclone: Version "v1.33-DEV" starting with parameters ["rclone" "-v" "sync" "/home/mastadon/test/" "Yandex:Files"]
> 2016/10/19 01:36:39 Yandex Files: Modify window is 1ns
> 2016/10/19 01:36:39 Yandex Files: Waiting for checks to finish
> 2016/10/19 01:36:39 Yandex Files: Waiting for transfers to finish
> 2016/10/19 01:37:39 
> Transferred:   130.562 MBytes (2.121 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:      1m1.5s
> Transferring:
>  *                         test.zip:  1% done. avg: 2403.9, cur: 2506.7 kByte/s. ETA: 51m38s
> 
> 2016/10/19 01:38:39 
> Transferred:   282.719 MBytes (2.326 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:      2m1.5s
> Transferring:
>  *                         test.zip:  3% done. avg: 2504.0, cur: 2448.1 kByte/s. ETA: 51m48s
> 
> 2016/10/19 01:39:39 
> Transferred:   432.625 MBytes (2.383 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:      3m1.5s
> Transferring:
>  *                         test.zip:  5% done. avg: 2522.6, cur: 2649.8 kByte/s. ETA: 46m54s
> 
> 2016/10/19 01:40:39 
> Transferred:   590.219 MBytes (2.443 MBytes/s)
> Errors:                 0
> Checks:                 0                                                                                                                                                                                                        
> Transferred:            0                                                                                                                                                                                                        
> Elapsed time:      4m1.5s                                                                                                                                                                                                        
> Transferring:                                                                                                                                                                                                                    
>  *                         test.zip:  7% done. avg: 2565.1, cur: 2661.8 kByte/s. ETA: 45m40s                                                                                                                        
>                                                                                                                                                                                                                                  
> 2016/10/19 01:41:39                                                                                                                                                                                                              
> Transferred:   746.188 MBytes (2.474 MBytes/s)                                                                                                                                                                                   
> Errors:                 0                                                                                                                                                                                                        
> Checks:                 0                                                                                                                                                                                                        
> Transferred:            0                                                                                                                                                                                                        
> Elapsed time:      5m1.5s                                                                                                                                                                                                        
> Transferring:                                                                                                                                                                                                                    
>  *                         test.zip:  9% done. avg: 2584.8, cur: 2669.4 kByte/s. ETA: 44m33s                                                                                                                        
>                                                                                                                                                                                                                                  
> 2016/10/19 01:42:39                                                                                                                                                                                                              
> Transferred:   896.969 MBytes (2.481 MBytes/s)                                                                                                                                                                                   
> Errors:                 0                                                                                                                                                                                                        
> Checks:                 0                                                                                                                                                                                                        
> Transferred:            0                                                                                                                                                                                                        
> Elapsed time:      6m1.5s                                                                                                                                                                                                        
> Transferring:                                                                                                                                                                                                                    
>  *                         test.zip: 11% done. avg: 2582.8, cur: 2367.1 kByte/s. ETA: 49m9s                                                                                                                         
>                                                                                                                                                                                                                                  
> 2016/10/19 01:43:39 
> Transferred:   1.020 GBytes (2.477 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:      7m1.5s
> Transferring:
>  *                         test.zip: 13% done. avg: 2573.2, cur: 2419.8 kByte/s. ETA: 47m2s
> 
> 2016/10/19 01:44:39 
> Transferred:   1.141 GBytes (2.425 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:      8m1.5s
> Transferring:
>  *                         test.zip: 15% done. avg: 2514.7, cur: 1941.2 kByte/s. ETA: 57m33s
> 
> 2016/10/19 01:45:39 
> Transferred:   1.284 GBytes (2.427 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:      9m1.5s
> Transferring:
>  *                         test.zip: 17% done. avg: 2513.3, cur: 2671.2 kByte/s. ETA: 40m53s
> 
> 2016/10/19 01:46:39 
> Transferred:   1.432 GBytes (2.437 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     10m1.5s
> Transferring:
>  *                         test.zip: 19% done. avg: 2520.5, cur: 2411.0 kByte/s. ETA: 44m14s
> 
> 2016/10/19 01:47:39 
> Transferred:   1.558 GBytes (2.412 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     11m1.5s
> Transferring:
>  *                         test.zip: 20% done. avg: 2492.2, cur: 1845.5 kByte/s. ETA: 56m35s
> 
> 2016/10/19 01:48:39 
> Transferred:   1.681 GBytes (2.386 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     12m1.5s
> Transferring:
>  *                         test.zip: 22% done. avg: 2463.5, cur: 2542.2 kByte/s. ETA: 40m14s
> 
> 2016/10/19 01:49:39 
> Transferred:   1.834 GBytes (2.403 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     13m1.5s
> Transferring:
>  *                         test.zip: 24% done. avg: 2479.6, cur: 2657.2 kByte/s. ETA: 37m29s
> 
> 2016/10/19 01:50:39 
> Transferred:   1.988 GBytes (2.419 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     14m1.5s
> Transferring:
>  *                         test.zip: 26% done. avg: 2494.9, cur: 2688.5 kByte/s. ETA: 36m3s
> 
> 2016/10/19 01:51:39 
> Transferred:   2.141 GBytes (2.432 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     15m1.5s
> Transferring:
>  *                         test.zip: 28% done. avg: 2506.9, cur: 2682.6 kByte/s. ETA: 35m8s
> 
> 2016/10/19 01:52:39 
> Transferred:   2.295 GBytes (2.444 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     16m1.5s
> Transferring:
>  *                         test.zip: 30% done. avg: 2517.9, cur: 2700.4 kByte/s. ETA: 33m54s
> 
> 2016/10/19 01:53:39 
> Transferred:   2.448 GBytes (2.454 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     17m1.5s
> Transferring:
>  *                         test.zip: 32% done. avg: 2527.3, cur: 2651.0 kByte/s. ETA: 33m31s
> 
> 2016/10/19 01:54:39 
> Transferred:   2.593 GBytes (2.455 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     18m1.5s
> Transferring:
>  *                         test.zip: 34% done. avg: 2527.9, cur: 2492.5 kByte/s. ETA: 34m38s
> 
> 2016/10/19 01:55:39 
> Transferred:   2.745 GBytes (2.462 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     19m1.5s
> Transferring:
>  *                         test.zip: 36% done. avg: 2534.2, cur: 2649.7 kByte/s. ETA: 31m35s
> 
> 2016/10/19 01:56:39 
> Transferred:   2.898 GBytes (2.470 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     20m1.5s
> Transferring:
>  *                         test.zip: 38% done. avg: 2542.0, cur: 2721.3 kByte/s. ETA: 29m46s
> 
> 2016/10/19 01:57:39 
> Transferred:   3.046 GBytes (2.473 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     21m1.5s
> Transferring:
>  *                         test.zip: 40% done. avg: 2543.8, cur: 2624.3 kByte/s. ETA: 29m53s
> 
> 2016/10/19 01:58:39 
> Transferred:   3.191 GBytes (2.473 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     22m1.5s
> Transferring:
>  *                         test.zip: 42% done. avg: 2543.6, cur: 2510.1 kByte/s. ETA: 30m14s
> 
> 2016/10/19 01:59:39 
> Transferred:   3.337 GBytes (2.473 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     23m1.5s
> Transferring:
>  *                         test.zip: 44% done. avg: 2543.4, cur: 2505.3 kByte/s. ETA: 29m16s
> 
> 2016/10/19 02:00:39 
> Transferred:   3.490 GBytes (2.479 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     24m1.5s
> Transferring:
>  *                         test.zip: 46% done. avg: 2549.4, cur: 2715.6 kByte/s. ETA: 26m1s
> 
> 2016/10/19 02:01:39 
> Transferred:   3.635 GBytes (2.479 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     25m1.5s
> Transferring:
>  *                         test.zip: 48% done. avg: 2548.7, cur: 2243.7 kByte/s. ETA: 30m22s
> 
> 2016/10/19 02:02:39 
> Transferred:   3.772 GBytes (2.474 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     26m1.5s
> Transferring:
>  *                         test.zip: 50% done. avg: 2542.7, cur: 2383.4 kByte/s. ETA: 27m35s
> 
> 2016/10/19 02:03:39 
> Transferred:   3.917 GBytes (2.473 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     27m1.5s
> Transferring:
>  *                         test.zip: 51% done. avg: 2541.9, cur: 2549.9 kByte/s. ETA: 24m47s
> 
> 2016/10/19 02:04:39 
> Transferred:   4.068 GBytes (2.477 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     28m1.5s
> Transferring:
>  *                         test.zip: 53% done. avg: 2545.6, cur: 2658.3 kByte/s. ETA: 22m47s
> 
> 2016/10/19 02:05:39 
> Transferred:   4.219 GBytes (2.481 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     29m1.5s
> Transferring:
>  *                         test.zip: 56% done. avg: 2549.0, cur: 2695.5 kByte/s. ETA: 21m29s
> 
> 2016/10/19 02:06:39 
> Transferred:   4.370 GBytes (2.484 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     30m1.5s
> Transferring:
>  *                         test.zip: 58% done. avg: 2552.2, cur: 2671.2 kByte/s. ETA: 20m41s
> 
> 2016/10/19 02:07:39 
> Transferred:   4.517 GBytes (2.485 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     31m1.5s
> Transferring:
>  *                         test.zip: 59% done. avg: 2552.3, cur: 2654.5 kByte/s. ETA: 19m51s
> 
> 2016/10/19 02:08:39 
> Transferred:   4.669 GBytes (2.488 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     32m1.5s
> Transferring:
>  *                         test.zip: 61% done. avg: 2555.6, cur: 2698.0 kByte/s. ETA: 18m33s
> 
> 2016/10/19 02:09:39 
> Transferred:   4.812 GBytes (2.487 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     33m1.5s
> Transferring:
>  *                         test.zip: 63% done. avg: 2554.2, cur: 2653.9 kByte/s. ETA: 17m55s
> 
> 2016/10/19 02:10:39 
> Transferred:   4.965 GBytes (2.490 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     34m1.5s
> Transferring:
>  *                         test.zip: 65% done. avg: 2557.4, cur: 2703.1 kByte/s. ETA: 16m36s
> 
> 2016/10/19 02:11:39 
> Transferred:   5.111 GBytes (2.490 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     35m1.5s
> Transferring:
>  *                         test.zip: 67% done. avg: 2557.3, cur: 2538.0 kByte/s. ETA: 16m41s
> 
> 2016/10/19 02:12:39 
> Transferred:   5.264 GBytes (2.494 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     36m1.5s
> Transferring:
>  *                         test.zip: 69% done. avg: 2560.4, cur: 2686.9 kByte/s. ETA: 14m46s
> 
> 2016/10/19 02:13:39 
> Transferred:   5.415 GBytes (2.496 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     37m1.5s
> Transferring:
>  *                         test.zip: 71% done. avg: 2562.6, cur: 2696.3 kByte/s. ETA: 13m44s
> 
> 2016/10/19 02:14:39 
> Transferred:   5.567 GBytes (2.499 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     38m1.5s
> Transferring:
>  *                         test.zip: 73% done. avg: 2565.4, cur: 2683.6 kByte/s. ETA: 12m48s
> 
> 2016/10/19 02:15:39 
> Transferred:   5.721 GBytes (2.502 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     39m1.5s
> Transferring:
>  *                         test.zip: 75% done. avg: 2568.2, cur: 2675.5 kByte/s. ETA: 11m50s
> 
> 2016/10/19 02:16:39 
> Transferred:   5.873 GBytes (2.504 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     40m1.5s
> Transferring:
>  *                         test.zip: 77% done. avg: 2570.7, cur: 2632.4 kByte/s. ETA: 11m1s
> 
> 2016/10/19 02:17:39 
> Transferred:   6.013 GBytes (2.502 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     41m1.5s
> Transferring:
>  *                         test.zip: 79% done. avg: 2567.8, cur: 2411.5 kByte/s. ETA: 11m1s
> 
> 2016/10/19 02:18:39 
> Transferred:   6.162 GBytes (2.502 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     42m1.5s
> Transferring:
>  *                         test.zip: 81% done. avg: 2568.5, cur: 2665.6 kByte/s. ETA: 8m59s
> 
> 2016/10/19 02:19:39 
> Transferred:   6.305 GBytes (2.501 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     43m1.5s
> Transferring:
>  *                         test.zip: 83% done. avg: 2566.9, cur: 2522.4 kByte/s. ETA: 8m30s
> 
> 2016/10/19 02:20:39 
> Transferred:   6.450 GBytes (2.500 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     44m1.5s
> Transferring:
>  *                         test.zip: 85% done. avg: 2566.2, cur: 2643.8 kByte/s. ETA: 7m9s
> 
> 2016/10/19 02:21:39 
> Transferred:   6.596 GBytes (2.500 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     45m1.5s
> Transferring:
>  *                         test.zip: 87% done. avg: 2566.0, cur: 2573.3 kByte/s. ETA: 6m22s
> 
> 2016/10/19 02:22:39 
> Transferred:   6.729 GBytes (2.495 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     46m1.5s
> Transferring:
>  *                         test.zip: 89% done. avg: 2560.4, cur: 2099.9 kByte/s. ETA: 6m42s
> 
> 2016/10/19 02:23:39 
> Transferred:   6.874 GBytes (2.495 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     47m1.5s
> Transferring:
>  *                         test.zip: 91% done. avg: 2560.1, cur: 2292.4 kByte/s. ETA: 5m1s
> 
> 2016/10/19 02:24:39 
> Transferred:   7.027 GBytes (2.497 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     48m1.5s
> Transferring:
>  *                         test.zip: 93% done. avg: 2562.5, cur: 2701.3 kByte/s. ETA: 3m16s
> 
> 2016/10/19 02:25:39 
> Transferred:   7.166 GBytes (2.495 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     49m1.5s
> Transferring:
>  *                         test.zip: 95% done. avg: 2559.6, cur: 2613.7 kByte/s. ETA: 2m27s
> 
> 2016/10/19 02:26:39 
> Transferred:   7.319 GBytes (2.497 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     50m1.5s
> Transferring:
>  *                         test.zip: 97% done. avg: 2561.8, cur: 2670.4 kByte/s. ETA: 1m24s
> 
> 2016/10/19 02:27:39 
> Transferred:   7.470 GBytes (2.498 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     51m1.5s
> Transferring:
>  *                         test.zip: 99% done. avg: 2563.3, cur: 2559.3 kByte/s. ETA: 26s
> 
> 2016/10/19 02:28:39 
> Transferred:   7.534 GBytes (2.471 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     52m1.5s
> Transferring:
>  * test.zip
> 
> 2016/10/19 02:29:39 
> Transferred:   7.534 GBytes (2.425 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     53m1.5s
> Transferring:
>  * test.zip
> 
> 2016/10/19 02:30:39 
> Transferred:   7.534 GBytes (2.380 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     54m1.5s
> Transferring:
>  * test.zip
> 
> 2016/10/19 02:31:39 
> Transferred:   7.534 GBytes (2.337 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     55m1.5s
> Transferring:
>  * test.zip
> 
> 2016/10/19 02:32:39 
> Transferred:   7.534 GBytes (2.295 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            0
> Elapsed time:     56m1.5s
> Transferring:
>  * test.zip
> 
> 2016/10/19 02:32:59 test.zip: Failed to copy: upload error [502]: <html>
> <head><title>502 Bad Gateway</title></head>
> <body bgcolor="white">
> <center><h1>502 Bad Gateway</h1></center>
> <hr><center>nginx/1.8.1</center>
> </body>
> </html>
> 2016/10/19 02:32:59 test.zip: Removing failed copy
> 2016/10/19 02:33:00 test.zip: Failed to remove failed copy: delete error [404]: {"message":"Не удалось найти запрошенный ресурс.","description":"Resource not found.","error":"DiskNotFoundError"}
> 2016/10/19 02:33:00 Yandex Files: not deleting files as there were IO errors
> 2016/10/19 02:33:00 Attempt 1/3 failed with 1 errors and: not deleting files as there were IO errors
> 2016/10/19 02:33:01 Yandex Files: Waiting for checks to finish
> 2016/10/19 02:33:01 Yandex Files: Waiting for transfers to finish
> 2016/10/19 02:33:39 
> Transferred:   7.617 GBytes (2.280 MBytes/s)
> Errors:                 0
> Checks:                 0
> Transferred:            1
> Elapsed time:     57m1.5s
> Transferring:
>  *                         test.zip:  1% done. avg: 2414.2, cur: 2389.9 kByte/s. ETA: 54m29s
> 
> ^C
> [mastadon@mastadon ~]$

**Comment by mastad0n** [comment]
This time was the first time it did not show up in Yandex.
It does however get added to folder size.

![screen](https://cloud.githubusercontent.com/assets/20113301/19513729/d5ded8e0-95a5-11e6-85ad-a014517d399d.png)

**Comment by ncw** [comment]
Do you see the file with `rclone ls yandex:` after you get one of those errors?  Or is it only visible in the web interface?

**Comment by ncw** [comment]
It looks like Yandex refused to take the upload which rclone can't really do anything about other than retry.

**Comment by tagplus5** [comment]
I use Rclone for upload backups to Yandex.Disk. In my expirience, Yandex not accept files over 2GB and sometimes not accept even 1.5GB. I use `split -b 1024MB` for my files.

https://yandex.com/support/disk/faq.html#file-size - i have never been able to upload a 9GB file.

**Comment by vitamin-caig** [comment]
Hello!

I've tried to upload to Yandex.Disk via webdav (headless server w/o browser access, so regular way is not applicable).

Simultaneous upload of two files (re)started at 15:40 approx and finished at 16:03:
`
2018/05/23 16:02:28 INFO  :
Transferred:   46.796 GBytes (15.659 MBytes/s)
Errors:                 0
Checks:                22
Transferred:            0
Elapsed time:     51m0.2s
Transferring:
 *   ...XXXXX: 93% /10.257G, 6.718M/s, 1m44s
 *   ...YYYYY: 97% /13.628G, 10.530M/s, 27s

2018/05/23 16:03:28 INFO  :
Transferred:   47.770 GBytes (15.677 MBytes/s)
Errors:                 0
Checks:                22
Transferred:            0
Elapsed time:     52m0.2s
Transferring:
 * XXXXX
 * YYYYY
`
As you can see, transferring has been finished at 16:03. But if rclone is not interrupted, it restarts transfer as no target file(s) appeared at destination. It was the second cycle, so I did interrupt. Commit timestamps were 16:28 for XXXXX (48 min since start, 25 min since finish) and 16:16 for YYYYY (36 min since start, 15 min since finish). So 3min/Gb timeout instead of currently used 5min/file is also required.

Could you please add an option to support it?

P.S. Maximum upload files size for Yandex.Disk has been increased to 50Gb https://yandex.com/support/disk/uploading.html#uploading
