### ISSUE TITLE
do you have plan to support upload resume feature

### ISSUE THREAD

**Issue by izouxv** [rclone/rclone#7415]
#### What problem are you are trying to solve?
big file can not upload sucess if the network is not good. 
so, if support upload resume feature this problem will be resolve. 
 

#### How do you think rclone should be changed to solve that?
object add a new interface as

```
type UploadCxt struct {
	ChunkSize int               //s3:5MB; local,smb,ftp:0
	Ctx       map[string]string //for token etc
}

// Object is a filesystem like object provided by an Fs
type ObjectUpload interface {
	UploadInit(ctx context.Context, src ObjectInfo) (UploadCxt, error)
	UploadRun(ctx context.Context, src ObjectInfo, uCtx UploadCxt, data io.Reader, options ...OpenOption) error
	UploadFinish(ctx context.Context, src ObjectInfo, uCtx UploadCxt) error
}
```
every upload state will be saved. if every UploadRun sucess.  and the network resume, the upload resume too

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
Duplicate.

https://github.com/rclone/rclone/issues/87
