### ISSUE TITLE
oracleobjectstorage 400 response when trying to change the tier

### ISSUE THREAD

**Issue by vbausys** [rclone/rclone#7417]
Hi Team,

I'm getting a 400 response during the settier operation with oracleobjectstorage provider, 
I observe the issue only with standard and  infrequentaccess tiers, operation to move the object to archive is successful.
 According to https://github.com/oracle/oci-go-sdk/blob/master/objectstorage/storage_tier.go all 3 tiers should be supported
 Could you please investigate?

```
vilius@debian:~$ rclone -V
rclone v1.64.2
- os/version: debian 12.2 (64 bit)
- os/kernel: 6.1.0-13-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.3
- go/linking: static
- go/tags: none
```
 
```
vbausys@debian:~$ rclone settier standard --include *-inc* oci-fra:/backup/PP_registras
2023/11/12 22:31:53 ERROR : oos:bucket backup, path PP_registras: Failed to do SetTier, Error returned by ObjectStorage Service. Http Status Code: 400. Error Code: InvalidStorageTier. Opc request id: fra-1:Pxy5cckP12lu7F0O_ikVJN1qFCaWrBItMnb0__ejr24Qgd4c_j9eWlikoRozCX_J. Message:
Operation Name: UpdateObjectStorageTier
Timestamp: 2023-11-12 20:31:48 +0000 GMT
Client Version: Oracle-GoSDK/65.45.0
Request Endpoint: POST https://objectstorage.eu-frankfurt-1.oraclecloud.com/n/friah9fs1ro8/b/backup/actions/updateObjectStorageTier
Troubleshooting Tips: See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_400__400_invalidstoragetier for more information about resolving this error.
Also see https://docs.oracle.com/iaas/api/#/en/objectstorage/20160918/Object/UpdateObjectStorageTier for details on this operation's requirements.
To get more info on the failing request, you can set OCI_GO_SDK_DEBUG env var to info or higher level to log the request/response details.
If you are unable to resolve this ObjectStorage issue, please contact Oracle support and provide them this full error message.
2023/11/12 22:31:53 ERROR : oos:bucket backup, path PP_registras: Failed to do SetTier, Error returned by ObjectStorage Service. Http Status Code: 400. Error Code: InvalidStorageTier. Opc request id: fra-1:KRJya04k7xNYtw4N4Sqcidp7K_c_Pfuvir7xqhg48IvyxwskaLt2fsLUt7Pjc3Qj. Message:
Operation Name: UpdateObjectStorageTier
Timestamp: 2023-11-12 20:31:48 +0000 GMT
Client Version: Oracle-GoSDK/65.45.0
Request Endpoint: POST https://objectstorage.eu-frankfurt-1.oraclecloud.com/n/friah9fs1ro8/b/backup/actions/updateObjectStorageTier
Troubleshooting Tips: See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_400__400_invalidstoragetier for more information about resolving this error.
Also see https://docs.oracle.com/iaas/api/#/en/objectstorage/20160918/Object/UpdateObjectStorageTier for details on this operation's requirements.
To get more info on the failing request, you can set OCI_GO_SDK_DEBUG env var to info or higher level to log the request/response details.
If you are unable to resolve this ObjectStorage issue, please contact Oracle support and provide them this full error message.
```

**Comment by msays2000** [comment]
https://docs.oracle.com/en-us/iaas/Content/Object/Concepts/understandingstoragetiers.htm

Please try UpdateObjectStorageTier from oci console for knowing the supported transitions: 

These transitions are supported. 
Standard  -> Infrequent Access
Standard  -> Archive
Infrequent Access -> Standard
Infrequent Access -> Archive

These two are not supported. 
Archive -> Standard
Archive -> Infrequent Access

Please check if after restoring the object (which may take upto 1 hour), it is possible to update the storage tier then..

**Comment by vbausys** [comment]
Not a bug. 
Tier for objects in the Archive cannot be changed by design.

OCI CLI command to loop for every object in the bucket (in real life most likely needs to be combined with --prefix) 
`oci os object list --bucket-name {bucket name}  --fields name | jq -r .data[].name | xargs -I {} oci os object restore --bucket-name backup --name {}`

**Comment by vbausys** [comment]
Not a bug. 
Tier for objects in the Archive cannot be changed by design.

OCI CLI command to loop for every object in the bucket (in real life most likely needs to be combined with --prefix) 
`oci os object list --bucket-name {bucket name}  --fields name | jq -r .data[].name | xargs -I {} oci os object restore --bucket-name backup --name {}`

**Comment by msays2000** [comment]
We will provide a rclone command to restore a bucket or path shortly
