### ISSUE TITLE
Object started with "/" was ignored when copy from S3 storage

### ISSUE THREAD

**Issue by elvislou** [rclone/rclone#7419]
Hi guys,

I have an issue when copying files from S3 to local file system.  rclone version: 1.64

here is output for "rclone ls":
/1.txt
/test/2.txt
a/b.txt
c/d.txt

when I running rclone copy command, only b.txt and d.txt was copied to local file system, /1.txt and /test/2.txt were ignored, and i can see the log "Entry doesn't belong in directory "" (same as direcotory) - ignoring".

it seems that the object which object name start with "/" was ignored, am I missing something, or is this a bug?

let me know if need more information.

**Comment by zhucan** [comment]
@elvislou it's bug, https://github.com/zhucan/rclone/commits/v1.59.1-dev  you can take a look at this updates, because of the prefix of object will be as forlder, so it will ignore extra "/".

**Comment by ncw** [comment]
This has been discussed extensively here.

https://github.com/rclone/rclone/issues/5858

Please follow that issue for progress - thanks!

I'll close this one as a duplicate.
