### ISSUE TITLE
your  documentation like shit !

### ISSUE THREAD

**Issue by marcoddddd** [rclone/rclone#7420]

**Comment by ncw** [comment]
There are over 500,000 words of documentation for rclone and a very helpful community at [the rclone forum](https://forum.rclone.org/) if you need more help.

If you'd like to contribute to the docs then please check out [CONTRIBUTING](https://github.com/rclone/rclone/blob/master/CONTRIBUTING.md#writing-documentation).

I'm going to close this issue as it doesn't contain any actionable info.
