### ISSUE TITLE
Support --auto-filename with copyto

### ISSUE THREAD

**Issue by smilingthax** [rclone/rclone#7421]
#### The associated forum post URL from `https://forum.rclone.org`

(e.g. https://forum.rclone.org/t/copyto-bug-when-destination-is-a-directory/35601/3 )

#### What is your current rclone version (output from `rclone version`)?

rclone v1.64.2
- os/version: alpine 3.18.4 (64 bit)
- os/kernel: 5.19.8-1.el7.elrepo.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.3
- go/linking: static
- go/tags: none

#### What problem are you are trying to solve?

Not having to repeat the filename at the destination when copying files.

#### How do you think rclone should be changed to solve that?

`copyurl` already supports this via `--auto-filename` / `-a`, and it would be useful for `copyto` as well.

Also, `copyurl` does not seem to support `file://...` urls ...

**Comment by ncw** [comment]
Just use rclone copy instead of copyto and make the destination be the directory that the file should go in.

**Comment by smilingthax** [comment]
> Just use rclone copy instead of copyto and make the destination be the directory that the file should go in.

At least with my S3 provider (cdn77, might be Cefs-based?), this does not work:
```
$ rclone.sh copy test.txt mys3:mybucket/

2023/11/14 23:22:21 ERROR : test.txt: Failed to copy: failed to prepare upload: AccessDenied: 
	status code: 403
```

Whereas `copyurl -a` does work, and copying directory content also does...

**Comment by ncw** [comment]
> Edit: With `--dump=headers,bodies,requests,responses,auth,filters,goroutines,openfiles`, rclone seems to try to PUT the bucket itself?

Rclone is making sure the bucket exists.

If you don't want that add `no_check_bucket = true` to the config.

**Comment by smilingthax** [comment]
Ok, thanks for the workaround.

(IMHO, the expected default for rclone should be not to fail on existing buckets (and at least give more helpful output about *what* failed(403...), without having to resort to low-level --dump ... debugging options). I don't think it shouldn't even create buckets by default (but require explicit configuration / commandline flag) -- even more so when copying to an alias... -- in my case the original copy command (simplified for the issue) used did not actually include the bucket name (`rclone copy test.txt mys3alias:` via `[mys3alias] type=alias remote=mys3:mybucket` ...). That copyurl and copyto behaves differently only added more confusion wrt. to possible solutions/workarounds).

**Comment by ncw** [comment]
Glad we've sorted that out!

Yes, I regret having rclone create the bucket if it doesn't exist, but that is backwards compatibility for you!
