### ISSUE TITLE
bisync: session name should normalize to non-canonical version for overridden configs

### ISSUE THREAD

**Issue by LivingUserError** [rclone/rclone#7423]
#### What is the problem you are having with rclone?
When calling bisync with a remote, but a leading `/` in the remote path like so

```bash
rclone bisync remote:/path/with/unneeded/slash /some/local/path --resync
```

the path will be normalized by Rclone and the command will be executed without throwing any error (or warning).

If you then try to run `bisync` without `--resync` however, it will not behave as expected. Running the exact same command without `--resync` will always yield:

```log
ERROR : Bisync critical error: cannot find prior Path1 or Path2 listings, likely due to critical error on prior run
```

This suggests that `bisync` failed previously, when in fact it didn't. It seems to name the listings after the normalized path, while checking for existing listings with the non-normalized path, as provided by the user.

This seems likely, because running the command again, but without the leading slash and `--resync`, will work:

```bash
rclone bisync remote:path/with/unneeded/slash /some/local/path
```

#### What is your rclone version (output from `rclone version`)
rclone v1.64.2
- os/version: arch Soaring (64 bit)
- os/kernel: 6.6.1-zen1-1-zen (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.3
- go/linking: dynamic
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Arch Linux, 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
Proton Drive

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by nielash** [comment]
Thank you for reporting this! I am having trouble reproducing it, though. For me, the following paths:
```
remote:/path/with/unneeded/slash
remote:path/with/unneeded/slash
```
both result in:
```
remote_path_with_unneeded_slash
```
in the listing filename. 

Are you using any backend-specific flags that could be overriding your config and adding a suffixed canonical name? ([More info](https://rclone.org/bisync/#overridden-configs))

Another thing that would be helpful is if you could try going into your workdir to see what bisync is actually naming the listing files, and whether there is any difference when you `--resync` with and without the slash. 

For example, try something like the following sequence:

```
rclone bisync remote:/path/with/unneeded/slash /some/local/path --resync
rclone lsl '~/.cache/rclone/bisync'
rclone bisync remote:path/with/unneeded/slash /some/local/path --resync
rclone lsl '~/.cache/rclone/bisync'
```
And let me know if there is any difference between the filenames output by the two `lsl`s?

If that doesn't yield clues, I'm also curious if it could be something specific to the encoding settings on Proton Drive. Any chance you could try the same thing with Google Drive and see if you get a different result?

**Comment by LivingUserError** [comment]
I am using one backend-specific option:
```bash
--protondrive-replace-existing-draft=true
```
My full command looks like this:
```bash
rclone bisync proton:sync /home/user/Proton --no-update-modtime --no-traverse --transfers 8 --protondrive-replace-existing-draft=true -v
```
`ls '~/.cache/rclone/bisync'` yields:
```bash
proton{kpshc}_sync..home_user_Proton.lck
proton{kpshc}_sync..home_user_Proton.path1.lst
proton{kpshc}_sync..home_user_Proton.path2.lst
proton_sync..home_user_Proton.path1.lst-new
proton_sync..home_user_Proton.path2.lst-new
```
This is after the command has been run with the unneeded slash and `--resync` first, and without both afterwards. If I find the time I can retry from zero, as you suggested.

I forgot to mention that I run rclone as root btw., maybe that also helps.

**Comment by nielash** [comment]
Thanks! The `{kpshc}` in the remote name is the telltale sign of an overridden config. The two that don't have it are curious to me -- are you able to tell from their modtimes whether they were created around the same time as the others? Or are they possibly just leftover from an old run, before you started using `--protondrive-replace-existing-draft=true`?

Are you using `--protondrive-replace-existing-draft=true` for both `--resync` and non-resync?

**Comment by LivingUserError** [comment]
OK, I have tried it more extensively, this time with 100% consistently the same args and clean directories. I'll post the entire sequence:

```shell
set -l args "--no-update-modtime" "--no-traverse" "--transfers" "8" "--protondrive-replace-existing-draft=true" "-v"

# Not set up
## Cmd
 sudo rclone bisync proton:/test /tmp/test $args
## Output
2023/11/19 15:36:25 NOTICE: bisync is EXPERIMENTAL. Don't use in production!
2023/11/19 15:36:25 INFO  : Synching Path1 "proton{kpshc}:test/" with Path2 "/tmp/test/"
2023/11/19 15:36:25 ERROR : Bisync critical error: cannot find prior Path1 or Path2 listings, likely due to critical error on prior run
2023/11/19 15:36:25 ERROR : Bisync aborted. Must run --resync to recover.
## sudo ls -l '/root/.cache/rclone/bisync'
### No files created (as expected)

# Setup
## Cmd
sudo rclone bisync proton:/test /tmp/test $args --resync
## Output
2023/11/19 15:37:35 NOTICE: bisync is EXPERIMENTAL. Don't use in production!
2023/11/19 15:37:35 INFO  : Synching Path1 "proton{kpshc}:test/" with Path2 "/tmp/test/"
2023/11/19 15:37:35 INFO  : Copying unique Path2 files to Path1
2023/11/19 15:37:36 INFO  : Resynching Path1 to Path2
2023/11/19 15:37:36 INFO  : There was nothing to transfer
2023/11/19 15:37:36 INFO  : Resync updating listings
2023/11/19 15:37:36 INFO  : Bisync successful
2023/11/19 15:37:36 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:         2.4s
## sudo ls -l '/root/.cache/rclone/bisync'
-rw-r--r-- 1 root root     60 Nov 19 15:37 proton{kpshc}_test..tmp_test.path1.lst
-rw-r--r-- 1 root root     60 Nov 19 15:37 proton{kpshc}_test..tmp_test.path2.lst

# Doesn't work, but should.
## Cmd
sudo rclone bisync proton:/test /tmp/test $args
## Output
sudo rclone bisync proton:/test /tmp/test $args
2023/11/19 15:37:58 NOTICE: bisync is EXPERIMENTAL. Don't use in production!
2023/11/19 15:37:58 INFO  : Synching Path1 "proton{kpshc}:test/" with Path2 "/tmp/test/"
2023/11/19 15:37:58 INFO  : Path1 checking for diffs
2023/11/19 15:37:58 ERROR : Empty prior Path1 listing. Cannot sync to an empty directory: /root/.cache/rclone/bisync/proton{kpshc}_test..tmp_test.path1.lst
2023/11/19 15:37:58 ERROR : Bisync critical error: empty prior Path1 listing: /root/.cache/rclone/bisync/proton{kpshc}_test..tmp_test.path1.lst
2023/11/19 15:37:58 ERROR : Bisync aborted. Must run --resync to recover.
## sudo ls -l '/root/.cache/rclone/bisync'
-rw-r--r-- 1 root root     60 Nov 19 15:37 proton{kpshc}_test..tmp_test.path1.lst-err
-rw-r--r-- 1 root root     60 Nov 19 15:37 proton{kpshc}_test..tmp_test.path2.lst-err



# Now try without slash
## Cmd
sudo rclone bisync proton:test /tmp/test $args
## Output
2023/11/19 16:17:53 NOTICE: bisync is EXPERIMENTAL. Don't use in production!
2023/11/19 16:17:53 INFO  : Synching Path1 "proton{kpshc}:test/" with Path2 "/tmp/test/"
2023/11/19 16:17:53 ERROR : Bisync critical error: cannot find prior Path1 or Path2 listings, likely due to critical error on prior run
2023/11/19 16:17:53 ERROR : Bisync aborted. Must run --resync to recover.
## sudo ls -l '/root/.cache/rclone/bisync'
### Nothing

# Setup
## Cmd
sudo rclone bisync proton:test /tmp/test $args --resync
## Output
2023/11/19 16:19:29 NOTICE: bisync is EXPERIMENTAL. Don't use in production!
2023/11/19 16:19:29 INFO  : Synching Path1 "proton{kpshc}:test/" with Path2 "/tmp/test/"
2023/11/19 16:19:29 INFO  : Copying unique Path2 files to Path1
2023/11/19 16:19:30 INFO  : Resynching Path1 to Path2
2023/11/19 16:19:31 INFO  : There was nothing to transfer
2023/11/19 16:19:31 INFO  : Resync updating listings
2023/11/19 16:19:33 INFO  : Bisync successful
2023/11/19 16:19:33 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Checks:                 1 / 1, 100%
Elapsed time:         6.2s
## sudo ls -l '/root/.cache/rclone/bisync'
-rw-r--r-- 1 root root    170 Nov 19 16:19 proton{kpshc}_test..tmp_test.path1.lst
-rw-r--r-- 1 root root    161 Nov 19 16:19 proton{kpshc}_test..tmp_test.path2.lst

# Works
## Cmd
sudo rclone bisync proton:test /tmp/test $args
## Output
2023/11/19 16:22:32 NOTICE: bisync is EXPERIMENTAL. Don't use in production!
2023/11/19 16:22:32 INFO  : Synching Path1 "proton{kpshc}:test/" with Path2 "/tmp/test/"
2023/11/19 16:22:32 INFO  : Path1 checking for diffs
2023/11/19 16:22:34 INFO  : Path2 checking for diffs
2023/11/19 16:22:34 INFO  : No changes found
2023/11/19 16:22:34 INFO  : Updating listings
2023/11/19 16:22:34 INFO  : Validating listings for Path1 "proton{kpshc}:test/" vs Path2 "/tmp/test/"
2023/11/19 16:22:34 INFO  : Bisync successful
2023/11/19 16:22:34 INFO  :
Transferred:              0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:         4.9s
## sudo ls -l '/root/.cache/rclone/bisync'
-rw-r--r-- 1 root root    170 Nov 19 16:22 proton{kpshc}_test..tmp_test.path1.lst
-rw-r--r-- 1 root root    161 Nov 19 16:22 proton{kpshc}_test..tmp_test.path2.lst
```

**Comment by LivingUserError** [comment]
After some extensive testing, you are probably right. I deleted my previous comment, because I noticed a mistake in the testing - didn't provide anything of value. 

 I must have added  `--protondrive-replace-existing-draft=true` after the fact and that broke it. Might still want to add a hint that similar listings (i.e. listings form running the command with different options) exist. That was quite the debug session 😅

**Comment by nielash** [comment]
> Might still want to add a hint that similar listings (i.e. listings form running the command with different options) exist. That was quite the debug session 😅

Thanks, and I agree! This is one I have tripped over myself. I [added a section to the docs](https://rclone.org/bisync/#overridden-configs) about it in `v1.64.0`, but I don't think that goes far enough, as users are continuing to stumble over it, and it can actually have serious consequences in the reverse direction (if you _remove_ a backend-specific flag and still have old listings using the alternate name.) 

The ultimate fix for this is #5678, but in the meantime I think we should normalize to the non-canonical name for listings -- it should not be possible to have more than one session name for the same pair of bisync paths. I have an idea about how to implement this in a way that is backward-compatible, which I will try out as soon as I have a chance. Thanks again for your work on this!

**Comment by LivingUserError** [comment]
Thank you for pointing me in the right direction! I could see why you would want to have multiple sessions for accessing the same remote tho - these backend-specific options could do pretty much anything, can't they? Maybe a warning/prompt is really the best one can do here, without limiting functionality.

**Comment by nielash** [comment]
When I say "session" here I'm talking specifically about the [`SessionName`](https://github.com/rclone/rclone/blob/01be5c75becc3abce0e000fa07d18824c7758fdf/cmd/bisync/operations.go#L70-L73).

In other words, if you do
```
rclone bisync a b
```
followed by
```
rclone bisync a b --protondrive-replace-existing-draft=true
```
bisync should understand that this is the same pair of paths, and that therefore the same listing file should be used. (Same as would happen today with a non-backend-specific flag.)

As opposed to:
```
rclone bisync a c
```

which is a _different_ session from `rclone bisync a b` and should use a _different_ listing file.

I don't think what I'm suggesting limits any functionality (it's more of a bug fix, really), but feel free to push back if you think I'm missing something!
