### ISSUE TITLE
move not working with --files-from

### ISSUE THREAD

**Issue by GregoryMachin** [rclone/rclone#7425]
#### What is the problem you are having with rclone?
I'm trying to move files that are listed in a file using --files-from. When the --files-from is in use nothing is moved. When --files-from is not in use everything is coped.

this is the what I'm using 
``` 
.\rclone.exe move "C:\temp\rclone\X\Data\" "C:\temp\rclone\X\Archive" --progress --metadata --log-file="C:\temp\rclone\log.txt" --log-level "DEBUG" --files-from "C:\temp\rclone\filelist.txt"
```
I have confirmed the file paths in the fileslist.txt are relative  
this is the content of the fileslist.txt
```
2019\file_2019.txt
2020\file_2020.txt
2021\file_2021.txt
```
this is the folder structure
C:.
│   .gitignore
│   Create-testdata.ps1
│   filelist.txt
│   log.txt
│   rclone.1
│   rclone.conf
│   rclone.exe
│   README.html
│   README.txt
│   Run-migration.ps1
│   Run-migrationRobocopy.ps1
│   Run-Rclone.ps1
│   Run-Rclone.test.ps1
│   Run-Robocopy.ps1
│   Set-LastAccessedModified.ps1
│
└───X
    ├───Archive
    └───Data
        ├───2019
        │       file_2019.txt
        │
        ├───2020
        │       file_2020.txt
        │
        ├───2021
        │       file_2021.txt
        │
        ├───2022
        │       file_2022.txt
        │
        ├───2023
        │       file_2023.txt
        │
        └───2024
                file_2024.txt

#### What is your rclone version (output from `rclone version`)
rclone v1.64.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
- os/version: Microsoft Windows 11 Enterprise 22H2 (64 bit)
- os/kernel: 10.0.22621.2428 (x86_64)
- os/type: windows
- os/arch: amd64

#### Which cloud storage system are you using? (e.g. Google Drive)
files are being moved locally, no cloud services in use. 

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
.\rclone.exe move "C:\temp\rclone\X\Data\" "C:\temp\rclone\X\Archive" --progress --metadata --log-file="C:\temp\rclone\log.txt" --log-level "DEBUG" --files-from "C:\temp\rclone\filelist.txt"

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
2023/11/16 14:23:27 DEBUG : rclone: Version "v1.64.2" starting with parameters ["C:\\temp\\rclone\\rclone.exe" "move" "C:\\temp\\rclone\\X\\Data\\" "C:\\temp\\rclone\\X\\Archive" "--progress" "--metadata" "--log-file=C:\\temp\\rclone\\log.txt" "--log-level" "DEBUG" "--files-from" "C:\\temp\\rclone\\filelist.txt"]
2023/11/16 14:23:27 DEBUG : Creating backend with remote "C:\\temp\\rclone\\X\\Data\\"
2023/11/16 14:23:27 DEBUG : Using config file from "C:\\temp\\rclone\\rclone.conf"
2023/11/16 14:23:27 DEBUG : fs cache: renaming cache item "C:\\temp\\rclone\\X\\Data\\" to be canonical "//?/C:/temp/rclone/X/Data"
2023/11/16 14:23:27 DEBUG : Creating backend with remote "C:\\temp\\rclone\\X\\Archive"
2023/11/16 14:23:27 DEBUG : fs cache: renaming cache item "C:\\temp\\rclone\\X\\Archive" to be canonical "//?/C:/temp/rclone/X/Archive"
2023/11/16 14:23:27 DEBUG : 2019: Excluded
2023/11/16 14:23:27 DEBUG : 2020: Excluded
2023/11/16 14:23:27 DEBUG : 2021: Excluded
2023/11/16 14:23:27 DEBUG : 2022: Excluded
2023/11/16 14:23:27 DEBUG : 2023: Excluded
2023/11/16 14:23:27 DEBUG : 2024: Excluded
2023/11/16 14:23:27 DEBUG : Local file system at //?/C:/temp/rclone/X/Archive: Waiting for checks to finish
2023/11/16 14:23:27 DEBUG : Local file system at //?/C:/temp/rclone/X/Archive: Waiting for transfers to finish
2023/11/16 14:23:27 INFO  : There was nothing to transfer
2023/11/16 14:23:27 INFO  : 
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:         2.7s

2023/11/16 14:23:27 DEBUG : 2 go routines active

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
For general support, please post on the forums.

https://forum.rclone.org

Easier to test with rclone ls.

```
etexter@macmini Downloads % cat files.txt
2019/file_2019.txt
etexter@macmini Downloads % rclone ls /Users/etexter/Downloads/test  --files-from files.txt -vv
2023/11/15 20:42:10 DEBUG : rclone: Version "v1.64.2" starting with parameters ["rclone" "ls" "/Users/etexter/Downloads/test" "--files-from" "files.txt" "-vv"]
2023/11/15 20:42:10 DEBUG : Creating backend with remote "/Users/etexter/Downloads/test"
2023/11/15 20:42:10 DEBUG : Using config file from "/Users/etexter/.config/rclone/rclone.conf"
2023/11/15 20:42:10 DEBUG : 2020: Excluded
        0 2019/file_2019.txt
2023/11/15 20:42:10 DEBUG : 5 go routines active
etexter@macmini Downloads % rclone ls /Users/etexter/Downloads/test
        0 2019/file_2019.txt
        0 2019/file_2020.txt
```

Run

```
rclone ls  "C:\temp\rclone\X\Data"
type C:\temp\rclone\filelist.txt
rclone ls  "C:\temp\rclone\X\Data" --files-from C:\temp\rclone\filelist.txt
```

**Comment by GregoryMachin** [comment]
> rclone ls  "C:\temp\rclone\X\Data" --files-from C:\temp\rclone\filelist.txt -vv

Here is the requested output:
```
PS C:\temp\rclone> .\rclone ls "C:\temp\rclone\X\Data"
  1048576 2024/file_2024.txt
  1048576 2021/file_2021.txt
  1048576 2022/file_2022.txt
  1048576 2020/file_2020.txt
  1048576 2023/file_2023.txt
  1048576 2019/file_2019.txt
PS C:\temp\rclone> type C:\temp\rclone\filelist.txt                                                 
2019\file_2019.txt
2020\file_2020.txt
2021\file_2021.txt
PS C:\temp\rclone> .\rclone ls  "C:\temp\rclone\X\Data" --files-from C:\temp\rclone\filelist.txt -vv
2023/11/16 15:50:45 DEBUG : rclone: Version "v1.64.2" starting with parameters ["C:\\temp\\rclone\\rclone.exe" "ls" "C:\\temp\\rclone\\X\\Data" "--files-from" "C:\\temp\\rclone\\filelist.txt" "-vv"]
2023/11/16 15:50:45 DEBUG : Creating backend with remote "C:\\temp\\rclone\\X\\Data"
2023/11/16 15:50:45 DEBUG : Using config file from "C:\\temp\\rclone\\rclone.conf"
2023/11/16 15:50:45 DEBUG : fs cache: renaming cache item "C:\\temp\\rclone\\X\\Data" to be canonical "//?/C:/temp/rclone/X/Data"
2023/11/16 15:50:45 DEBUG : 2019: Excluded
2023/11/16 15:50:45 DEBUG : 2020: Excluded
2023/11/16 15:50:45 DEBUG : 2021: Excluded
2023/11/16 15:50:45 DEBUG : 2022: Excluded
2023/11/16 15:50:45 DEBUG : 2023: Excluded
2023/11/16 15:50:45 DEBUG : 2024: Excluded
2023/11/16 15:50:45 DEBUG : 2 go routines active
PS C:\temp\rclone>
```

**Comment by Animosity022** [comment]
Your filter file is not correct.

Key piece from the docs:

Important Use / in path/file name patterns and not \ even if running on Microsoft Windows.

https://rclone.org/filtering/
