### ISSUE TITLE
Does the URL of WebDAV not support http://xx.com/xx/drivewebdav?

### ISSUE THREAD

**Issue by tsoil** [rclone/rclone#7427]
#### What is the problem you are having with rclone?

I am using rclone to mount WebDAV. The mount address format "http://xx.com/xx/drivewebdav" can be mounted, but when I open it, the content is empty. However, if I use "http://xx.com:20022/", there is content. Here, "http://xx.com/xx/drivewebdav" is proxying "http://xx.com:20022/".

#### What is your rclone version (output from `rclone version`)

v1.64.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 10

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by tsoil** [comment]
I have no issues using RaiDrive.

**Comment by kapitainsky** [comment]
Please post it on the forum -  https://forum.rclone.org/

Provide all details and somebody will try to help.

Github is for tracking bugs and enhancements. Not for general troubleshooting.
