### ISSUE TITLE
rclone backend cleanup-hidden on s3 does not exist 

### ISSUE THREAD

**Issue by drannex42** [rclone/rclone#7431]
I am unable to clean up on s3 versions, the docs say to use `backend cleaup-hidden s3:` and yet I am receiving the error:

```
 Failed to backend: "cleanup-hidden" command not found (try the underlying remote)
```

Was this option removed recently?

**Comment by Animosity022** [comment]
Please use the forums for questions..

**Comment by drannex42** [comment]
Not a question, filing a bug report. 

The code obviously defines it, both in the doc notice, and in the purge options, but is not being picked up by the cli for some reason.

**Comment by Animosity022** [comment]
1) You didn't fill a bug report as you ignored the whole bug report template.
2) You asked if something was removed hence the question.

Please post on the forums.

https://forum.rclone.org

**Comment by drannex42** [comment]
Yeah, I'll file a bug report then. 

I see the issue, your template has a letter at a top that stretches the entire view port, with scrollbars hidden until scroll you can't see the beginning of the bug report, so you just (I just) deleted the entire thing not even noticing that there was anything under the letter.
