### ISSUE TITLE
Latest versions no longer support  "cleanup-hidden" command on the backend

### ISSUE THREAD

**Issue by drannex42** [rclone/rclone#7433]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/cleanup-hidden-is-no-longer-available/42946

[This was implemented in Sep. 2022 w/ 1.60](https://forum.rclone.org/t/rclone-1-60-0-release/33646)

#### What is the problem you are having with rclone?
Recent versions removed access to the backend command for "cleanup-hidden". This was available in previous versions, and is still nested into the code that is released, but the backend command is not available to the cli. 

#### What is your rclone version (output from `rclone version`)
- rclone v1.65.0-beta.7504.47ca0c326
- os/version: Microsoft Windows 11 Pro 23H2 (64 bit)
- os/kernel: 10.0.22631.2715 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.21.4
- go/linking: static
- go/tags: cmount

This is also visible on my NixOS install, with the stable release and the beta release.

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 11, 64. 
NixOS, 64. 

#### Which cloud storage system are you using? (e.g. Google Drive)
S3-like

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone backend cleanup-hidden x:`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

Initial error message:

```
2023/11/19 01:05:37 Failed to backend: "cleanup-hidden" command not found (try the underlying remote)
```

Log:

```
2023/11/19 01:05:59 DEBUG : rclone: Version "v1.65.0-beta.7504.47ca0c326" starting with parameters ["C:\\Users\\Macleod Sawyer\\AppData\\Local\\Microsoft\\WinGet\\Packages\\Rclone.Rclone_Microsoft.Winget.Source_8wekyb3d8bbwe\\rclone-v1.64.2-windows-amd64\\rclone.exe" "backend" "cleanup-hidden" "idrc:" "-vv"]
2023/11/19 01:05:59 DEBUG : Using config file from "C:\\Users\\Macleod Sawyer\\AppData\\Roaming\\rclone\\rclone.conf"
2023/11/19 01:05:59 DEBUG : Creating backend with remote "idr:[redacted]"
2023/11/19 01:05:59 DEBUG : Resolving service "s3" region "us-east-1"
2023/11/19 01:05:59 DEBUG : 2 go routines active
2023/11/19 01:05:59 Failed to backend: "cleanup-hidden" command not found (try the underlying remote)
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by drannex42** [comment]
There is missing information in the docs, the issue is that this must be defined with bucket information on a non-crypt remote. This could be clearer I suppose.

**Comment by ncw** [comment]
The crypt backend could maybe give you a hint here...

If you ran 

    rclone backend cleanup-hidden x:

It could then give you an error

    Command `cleanup-hidden` not found, maybe you meant `rclone backend cleanup-hidden underlying:dir`?

Conceivably crypt could also run that command. I haven't done that in the past as the `rclone backend` commands often have parameters which would need translating and that is too hard to do automatically.
