### ISSUE TITLE
Directly using an anonymously accessible Gdrive URL

### ISSUE THREAD

**Issue by nh2** [rclone/rclone#744]
I couldn't figure out if rclone supports directly downloading from a Google Drive URL that you don't have to log in for.

Would this be possible? Or does Google Drive force you to log in to even be able to enumerate the files to download?

Thanks!

**Comment by ncw** [comment]
According to the [drive api docs](https://developers.google.com/drive/v2/web/about-auth)

> All requests to the Google Drive API must be authorized by an authenticated user. Google Drive uses the OAuth 2.0 protocol for authenticating a Google account and authorizing access to user data. You can also use OAuth 2.0 or Google+ Sign-in to provide a "sign-in with Google" authentication method for your app.

So I think that is a no unfortunately.

Amazon S3 does support anonymous use of the API though (and so does rclone).

**Comment by animosity22** [comment]
This looks to be answered. If you still have a question, please use https://forums.rclone.org
