### ISSUE TITLE
After mounting dropbox or mega cloud disk, turn off the computer agent. After waiting for a few minutes, the system will be stuck and cannot be moved.

### ISSUE THREAD

**Issue by cxm2513018185** [rclone/rclone#7441]
After mounting dropbox or mega cloud disk, turn off the computer agent. After waiting for a few minutes, the system will be stuck and cannot be moved. Is there no timeout set?

**Comment by kapitainsky** [comment]
Please post it on the https://forum.rclone.org/ and provide all details.

**Comment by cxm2513018185** [comment]
> Please post it on the https://forum.rclone.org/ and provide all details.

ok, it has been mentioned, please follow up as soon as possible, thank you！
