### ISSUE TITLE
If there is a problem with the network, df will freeze after rclone mount. I hope to add a cancellation function of about callback on dropbox and mega.

### ISSUE THREAD

**Issue by lirui-dot** [rclone/rclone#7443]

**Comment by lirui-dot** [comment]
![image](https://github.com/rclone/rclone/assets/74805870/dc0632e8-c050-4eca-8257-7695a7eccf4c)
This is a screenshot of the dropbox code. If it is not modified, the df will keep waiting.

**Comment by Animosity022** [comment]
Love the double forum and github post. Closing.
