### ISSUE TITLE
mkdir on non-permission dir successfully

### ISSUE THREAD

**Issue by ejunjsh** [rclone/rclone#7447]
#### What is the problem you are having with rclone?

i mount ftp or dav remote, the root dir on that remote cannot be modfied, but when i mkdir on that dir,  it sucess. that is very strange, it should be raise a permission denied err. my mount option is --vfs-cache-mode off (default)  so it should write directly and raise a err.

#### What is your rclone version (output from `rclone version`)

rclone v1.60.1-DEV

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

linux debian 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)

ftp or dav

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone mount

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
For questions, please use the forums and help and support template.

The biggest part is the debug log file..

https://forum.rclone.org
