### ISSUE TITLE
Shared files doesn't work with `rclone copy --drive-root-folder-id ...`

### ISSUE THREAD

**Issue by kenorb** [rclone/rclone#7458]
#### The associated forum post URL from `https://forum.rclone.org`

n/a

#### What is the problem you are having with rclone?

The following command works only for folders:

```
rclone copy -P --drive-root-folder-id 1-XYZ-ID_OF_FOLDER gdrive: dest/
```

but when you've ID of the single file (e.g. `https://drive.google.com/file/d/`), it doesn't copy anything.

#### What is your rclone version (output from `rclone version`)

```
$ rclone version
rclone v1.53.3-DEV
- os/arch: linux/amd64
- go version: go1.18.1
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

- Ubuntu 22

#### Which cloud storage system are you using? (e.g. Google Drive)

- Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
rclone copy -P --drive-root-folder-id ID gdrive: dest/
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2023-11-26 14:38:43 INFO  : There was nothing to transfer
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Elapsed time:         0.3s
2023/11/26 14:38:43 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Elapsed time:         0.3s

2023/11/26 14:38:43 DEBUG : 4 go routines active
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
The root folder is your ID and not shared with you so that seems to make sense.

That's also a 4-5 year old version..

For support, please update and use the forums.

https://forum.rclone.org
