### ISSUE TITLE
Problem with OneDrive <3>ERROR : /: Dir.Stat error: unknown object type <nil> <3>ERROR : IO error: unknown object type <nil>

### ISSUE THREAD

**Issue by ccouto** [rclone/rclone#7485]
#### What is the problem you are having with rclone?

Since version 1.65 rclone is not able to mount a OneDrive remote. Downgrading to version 1.64-2 works flawlessly.

#### What is your rclone version (output from `rclone version`)

rclone v1.65.0
- os/version: arch (64 bit)
- os/kernel: 6.1.64-1-lts (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.4
- go/linking: dynamic
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Arch Linux

#### Which cloud storage system are you using? (e.g. Google Drive)

OneDrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone -vv --vfs-cache-mode writes mount OneDriveUA: /home/ccouto/OneDrive

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

<7>DEBUG : rclone: Version "v1.65.0" starting with parameters ["rclone" "-vv" "--vfs-cache-mode" "writes" "mount" "OneDriveUA:" "/home/ccouto/OneDrive"]
<7>DEBUG : rclone: systemd logging support activated
<7>DEBUG : Creating backend with remote "OneDriveUA:"
<7>DEBUG : Using config file from "/home/ccouto/.config/rclone/rclone.conf"
<7>DEBUG : OneDrive root '': Next delta token is: NDslMjM0OyUyMzE7Mzs4ODQyMWQyYS05MzgwLTRiZDItODExMC02YzRiZTRlY2E2NjE7NjM4MzczMjU1NzQyMjAwMDAwOzQ0NTgyMjcyMDslMjM7JTIzOyUyMzA7JTIz
<7>DEBUG : vfs cache: root is "/home/ccouto/.cache/rclone"
<7>DEBUG : vfs cache: data root is "/home/ccouto/.cache/rclone/vfs/OneDriveUA"
<7>DEBUG : vfs cache: metadata root is "/home/ccouto/.cache/rclone/vfsMeta/OneDriveUA"
<7>DEBUG : Creating backend with remote "/home/ccouto/.cache/rclone/vfs/OneDriveUA/"
<7>DEBUG : fs cache: renaming cache item "/home/ccouto/.cache/rclone/vfs/OneDriveUA/" to be canonical "/home/ccouto/.cache/rclone/vfs/OneDriveUA"
<7>DEBUG : Creating backend with remote "/home/ccouto/.cache/rclone/vfsMeta/OneDriveUA/"
<7>DEBUG : fs cache: renaming cache item "/home/ccouto/.cache/rclone/vfsMeta/OneDriveUA/" to be canonical "/home/ccouto/.cache/rclone/vfsMeta/OneDriveUA"
<6>INFO  : vfs cache: cleaned: objects 0 (was 0) in use 0, to upload 0, uploading 0, total size 0 (was 0)
<7>DEBUG : OneDrive root '': Mounting on "/home/ccouto/OneDrive"
<7>DEBUG : : Root: 
<7>DEBUG : : >Root: node=/, err=<nil>
<7>DEBUG : /: Lookup: name=".Trash"
<7>DEBUG : Carlos @ Universidade de Aveiro: OneNote file not shown in directory listing
<7>DEBUG : Metal: OneNote file not shown in directory listing
<7>DEBUG : Work: OneNote file not shown in directory listing
<3>ERROR : /: Dir.Stat error: unknown object type <nil>
<3>ERROR : IO error: unknown object type <nil>
<7>DEBUG : /: >Lookup: node=<nil>, err=unknown object type <nil>
<7>DEBUG : /: Lookup: name=".xdg-volume-info"
<7>DEBUG : /: Lookup: name="BDMV"
<7>DEBUG : /: Lookup: name="autorun.inf"
<7>DEBUG : /: Attr: 
<7>DEBUG : Carlos @ Universidade de Aveiro: OneNote file not shown in directory listing
<7>DEBUG : Metal: OneNote file not shown in directory listing
<7>DEBUG : Work: OneNote file not shown in directory listing
<3>ERROR : /: Dir.Stat error: unknown object type <nil>
<3>ERROR : IO error: unknown object type <nil>
<7>DEBUG : /: >Lookup: node=<nil>, err=unknown object type <nil>
<7>DEBUG : /: Lookup: name=".Trash-1000"
<7>DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxr-xr-x, err=<nil>
<7>DEBUG : Carlos @ Universidade de Aveiro: OneNote file not shown in directory listing
<7>DEBUG : Metal: OneNote file not shown in directory listing
<7>DEBUG : Work: OneNote file not shown in directory listing
<3>ERROR : /: Dir.Stat error: unknown object type <nil>
<3>ERROR : IO error: unknown object type <nil>
<7>DEBUG : /: >Lookup: node=<nil>, err=unknown object type <nil>
<7>DEBUG : /: ReadDirAll: 

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
Already fixed in the beta and listed on the forums:

https://forum.rclone.org/t/onedrive-fails-to-list-certain-files-1-65/43104/9
