### ISSUE TITLE
Allowing "crypt" drives to reside in many other drives (not just 1 drive)

### ISSUE THREAD

**Issue by duy13** [rclone/rclone#7507]
#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.65.0
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 5.15.0-89-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.4
- go/linking: static
- go/tags: none
```

#### What problem are you are trying to solve?

Link multiple small drives and limit them to 1 larger drive using rclone's crypt drive function

#### How do you think rclone should be changed to solve that?

https://rclone.org/crypt/

I have an idea that rclone can create additional features of crypt drives, for example allowing crypt drives to reside in many other drives (not just 1 drive). Example: we have 5 mega.io accounts of 20GB, 3 Google Drive accounts of 15GB... they can combine them into (5 x 20GB) + (3 x 15GB) ~ 145GB of "crypt" drive space.
When uploading a file to a "virtual" crypt drive, it will divide the file into files for example 1MB, 10MB... written to "real" drives (5 mega.io accounts of 20GB, 3 accounts). Google Drive account 15GB...)
When the user needs to download, rclone will download small files (eg 1MB, 10MB...) that have been divided and encrypted, then reassemble and create the original file.
I think it's possible, it's pretty magical, it looks like we're creating a universe inside the little free storage packages of the storage providers.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by kapitainsky** [comment]
Have a look at:

https://rclone.org/union/

https://rclone.org/chunker/

If you have any further question please use https://forum.rclone.org and not github.

**Comment by Animosity022** [comment]
Looks to be answered.
