### ISSUE TITLE
Librclone - couldn't find method "mount/mount" on Windows/macOS; Linux is fine

### ISSUE THREAD

**Issue by tomekit** [rclone/rclone#7508]
#### What is the problem you are having with rclone?
I am getting an error: `couldn't find method \"mount/mount\"` when called from `RcloneRPC` method when called on Windows on macOS.

Problem doesn't appear on Linux.

Full output from Windows:
```
{
	"error": "couldn't find method \"mount/mount\"",
	"input": {
		"fs": "pcloud:",
		"mountOpt": {
			"NetworkMode": true
		},
		"mountPoint": "*",
		"mountType": "mount",
		"vfsOpt": {
			"CacheMode": 2
		}
	},
	"path": "mount/mount",
	"status": 404
}
```

#### What is your rclone version (output from `rclone version`)
Librclone built from: v1.65.0

# Linux
```
go build --buildmode=c-shared -o librclone.so github.com/rclone/rclone/librclone
```
# macOS
```
CGO_ENABLED=1 GOOS=darwin go build --buildmode=c-shared -o rclone.dylib github.com/rclone/rclone/librclone
```
# Windows
```
SET CGO_ENABLED=1
go build --buildmode=c-shared -o librclone.dll github.com/rclone/rclone/librclone
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Windows 11 / macOS

#### Final words
I am not entirely sure why this error appears given that when starting rclone as a server: `rclone rcd --rc-no-auth` and then executing `rclone rc mount/mount` in the other terminal seem to work just fine on both macOS and Linux.

I reported this as a bug, but there is a chance that I've built `librclone` incorrectly. I've provided my build commands above.

I would appreciate if you could point me in the right direction.

I am not sure if I've found the right thing, but in the Rclone's code I've found that this seem to be called for all platforms: https://github.com/rclone/rclone/blob/c69eb84573c85206ab028eda2987180e049ef2e4/cmd/mountlib/rc.go#L50

however this seem to be restricted to Linux only: https://github.com/rclone/rclone/blob/c69eb84573c85206ab028eda2987180e049ef2e4/cmd/mount/mount.go#L20 
I am not sure if this is actually causing the issue I am reporting and whether it's deliberate.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by nielash** [comment]
Possibly related?:

https://github.com/rclone/rclone/blob/c69eb84573c85206ab028eda2987180e049ef2e4/docs/content/install.md?plain=1#L350-L355

**Comment by ncw** [comment]
> I reported this as a bug, but there is a chance that I've built `librclone` incorrectly. I've provided my build commands above.

You will need to build with `--tags cmount` if you want mount on Windows and macOS.

This will in turn require CGO and the `libfuse` headers (from WinFSP or osxfuse).

**Comment by tomekit** [comment]
Thank you for your prompt response and I feel I should've rather opened a forum topic.

I am still getting "mount failed: cgofuse: cannot find FUSE" on macOS.

In fact I hope I can get librclone mount to run with just `FUSE-T` as it works just fine when I run: `rclone rc mount/mount mountPoint=/tmp/tomek fs=pcloud:` on my macOS (using rclone release from Github).

I've found similar issue: https://github.com/rclone/rclone/issues/6807, referencing to block that tries to load FUSE: https://github.com/winfsp/cgofuse/blob/f87f5db493b56c5f4ebe482a1b7d02c7e5d572fa/fuse/host_cgo.go#L172-L176

In my case `osxfuse` and `macFUSE` isn't available, but `FUSE-T` is.
```
ls: /usr/local/lib/libfuse.2.dylib: No such file or directory
ls: /usr/local/lib/libosxfuse.2.dylib: No such file or directory
lrwxr-xr-x  1 root  staff  22 Dec  7 21:14 /usr/local/lib/libfuse-t.dylib -> libfuse-t-1.0.32.dylib
```

This is my updated build command:
```
CGO_ENABLED=1 GOOS=darwin go build --tags cmount -trimpath -ldflags -s --buildmode=c-shared -o rclone.dylib github.com/rclone/rclone/librclone
```

I've then installed macFUSE: https://github.com/osxfuse/osxfuse/releases rebuilt my `librclone` just in case and tried to mount using `RcloneRPC`, but I am still getting the: "cannot find FUSE" error.

I would appreciate if you could point me into right direction, what else might need checking?

I've managed to run it on Windows using below build:
```
# gcc resolves to: "C:\TDM-GCC-64\bin\gcc.exe"
SET CGO_ENABLED=1
SET CPATH=C:\Program Files (x86)\WinFsp\inc\fuse
go build -trimpath -ldflags -s --tags cmount --buildmode=c-shared -o librclone.dll github.com/rclone/rclone/librclone
```
Thanks !

**Comment by tomekit** [comment]
When I compile `rclone` instead of `librclone`, I can mount just fine:
```
go build -v --tags "cmount" --ldflags -s -o rclone github.com/rclone/rclone
./rclone rcd --rc-no-auth

# In a 2nd terminal
./rclone rc mount/mount mountPoint=/tmp/tomek fs=pcloud:
```

I am not sure if this problem might be related to macOS permissions/sandbox (which I am not hugely familiar with), since when I build my app that loads the `librclone`, it doesn't seem to have permissions to read from: ` /usr/local/lib/libfuse-t.dylib`,
I assume that neither the `librclone` will have permissions to `libfuse-t.dylib` itself which is loaded from the context of an application.

**Comment by ncw** [comment]
I don't know anything about the macOS permissions, but I do know that rclone (via cgofuse) loads the shared object manually at runtime so it will need to be able to read it. Rclone does this so that you can run a mount enabled rclone on a Mac which doesn't have the shared object installed.

**Comment by tomekit** [comment]
In fact I can confirm that this issue is purely related to macOS permissions, since if I remove the "Sandbox" by removing the:
```
<key>com.apple.security.app-sandbox</key>
<true/>
```
from the Entitlements, the mount actually works fine.

Question what's the best way forward as disabling sandbox isn't really an option today (https://developer.apple.com/documentation/security/app_sandbox/)

After adding:
```
<key>com.apple.security.temporary-exception.files.absolute-path.read-only</key>
<array>
    <string>/usr/local/lib/</string>
</array>
```
the app can actually read the: `/usr/local/lib/libfuse-t.dylib`, but that's not enough to actually load the library.

Apparently there is one more protection: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_disable-library-validation
which unfortunately doesn't seem take an effect regardless of the setting:
```
<key>com.apple.security.cs.disable-library-validation</key>
<true/>
```
it's also very much unrecommended by the Apple rep anyway:  https://developer.apple.com/forums/thread/706414 as it may cause additional issues with the Gatekeeper due to different security scrutiny.

We're yet to find a reasonable way forward, but this certainly isn't an issue with Rclone nor librclone, so I am going to close this issue for now.

Thank you for your help on this !

**Comment by tomekit** [comment]
I haven't realized that there is now: https://rclone.org/commands/rclone_serve_nfs/ command available. I am going to try that out.
I'll probably have a go and try adding it as a command here: https://rclone.org/rc/ so I can run it from `librclone`, I guess that should be possible? If I am successful I am hopefully able to prepare a pull request.
