### ISSUE TITLE
copying symlinked files results in an error

### ISSUE THREAD

**Issue by thisismygitrepo** [rclone/rclone#7509]
Judging by the error, it seems that `rclone` gets confused (doens't know how to handle) symlinks. It seems to be considering it a directory and is failing at listing its contents.

```shell
rclone copyto '/home/alex/ruff.toml' 'oduq1:/home/alex/ruff.toml'

# Terminal Response:

2023/12/17 12:48:57 Failed to copyto: failed to read directory entry: readdirent /home/alex/ruff.toml: not a directory 
```

PS: `ruff.toml` is a symlink to a file in a different location. I'm on Linux Mint, latest rclone (1.64.2) and the remote is a onedrive service.

**Comment by kapitainsky** [comment]
This error code is indeed misleading and could be improved but it is expected `rclone` behaviour. 

If you want to follow symlink you have to specify [--copy-links](https://rclone.org/local/#copy-links-l) flag

**Comment by thisismygitrepo** [comment]
@kapitainsky Thanks! that indeed fixed my problem. I'll just keep this open as more people will be misled by the error message and come to report bugs.

**Comment by Animosity022** [comment]
Feel free to submit a PR if something isn't clear as the question has been answered. The best way to help someone else would be to assist and submit a PR for improving the documentation.
