### ISSUE TITLE
No access to Linkbox files and dirs

### ISSUE THREAD

**Issue by gvitali** [rclone/rclone#7542]
#### The associated forum post URL from `https://forum.rclone.org`
n/a

#### What is the problem you are having with rclone?
Rclone successfully encodes and copies dirs and files to Linkbox, but then no way to sync or list or download it.

The problem is that Linkbox allows files and folders with names of up to 100 characters. But the search in their API works with names of up to 50 ASCII characters and 25 UTF-16 characters (for example, Cyrillic) only. Thus, normal operation is possible only with very short names. For example, using base32 encoding for names, the maximum name length can be only 8 UTF-16 characters, and for base32768 - 16 UTF-16 characters. Which is, of course, very little in real life.

#### What is your rclone version (output from `rclone version`)
rclone v1.65.0 and rclone v1.66.0-beta.7594.5fa13e3e3

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Arch Linux 64 bit

#### Which cloud storage system are you using? (e.g. Google Drive)
Linkbox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`./rclone ls -vv "telebox-encoded:photos from London"`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
<7>DEBUG : rclone: Version "v1.65.0" starting with parameters ["rclone" "ls" "-vv" "telebox-encoded:photos from London"]
<7>DEBUG : rclone: systemd logging support activated
<7>DEBUG : Creating backend with remote "telebox-encoded:photos from London"
<7>DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
<7>DEBUG : Creating backend with remote "telebox:files/encoded/347ftlbc73000l927l7hbud1i77qle7j8pfi9j01c5lu0bve5k8g"
<3>ERROR : : error listing: directory not found
<7>DEBUG : 5 go routines active
Failed to ls with 2 errors: last error was: directory not found
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by kapitainsky** [comment]
And what you want rclone to do about it?

**Comment by gvitali** [comment]
> And what you want rclone to do about it?

Any possible solution would be great, I think. For example, just some ideas:

1. Limit the allowed name length and throw an error if it is exceeded. At least this will prevent the user from falling into the trap, as it is now: the files are uploaded, but there is actually no access to them.
2. Add a new encoder for file names with a function to shorten the name length, even if it is not crypto-resistant.
3. Automatically trim the names to the allowed length (warning the user about this).
4. Store the IDs of directories and files locally instead of constantly using the `api/open/file_search` request (perhaps such  option is already in rclone somewhere?)
5. Somehow, the UI Explorer (http://127.0.0.1:5572/#/remoteExplorer) can show a list of files in directories with long names, but `rclone ls` cannot. (However, the explorer fails to download these files). Perhaps it's possible somehow to use some functionality from there.

It just turns out that Linkbox is now on the list, but in fact it is not working / not usable.
