### ISSUE TITLE
Delete files permanently in Google Drive

### ISSUE THREAD

**Issue by Eversons99** [rclone/rclone#7544]
I was reading the documentation about rlcone delete (https://rclone.org/commands/rclone_delete/), I was looking for a way to permanently delete files from remote Google Drive and I didn't find anything about it in the documentation.

I asked ChatGPT about a solution to my problem and he gave me the following answer "Pass the --drive-use-trash=false argument when using rclone delete, so that your file is permanently removed", I think it's interesting to put this information in the rclone documentation delete.

**Comment by Animosity022** [comment]
Please use the forums for questions.

https://forum.rclone.org
