### ISSUE TITLE
Openstack SWIFT v3 request structure

### ISSUE THREAD

**Issue by MrCalv1n** [rclone/rclone#7556]
Hi,

I'm having some issues trying to use Openstack swift for v3.

This is the HTTP request currently made by rclone (I'm only including the relevant part):

```
POST /auth/tokens HTTP/1.1
...

{
  "auth": {
    "identity": {
      "methods": [
        "password"
      ],
      "password": {
        "user": {
          "name": "admin",
          "password": "devstacker"
        }
      }
    },
    "scope": {
      "project": {
        "name": "storage",
        "domain": {
          "name": "Default"
        }
      }
    }
  }
}
```

and this is the HTTP request currently accepted by a V3 API endpoint using Openstack (I'm only including the relevant part):

```
POST **/v3/**auth/tokens HTTP/1.1
...

{
    "auth": {
        "identity": {
            "methods": [
                "password"
            ],
            "password": {
                "user": {
                    "name": "admin",
                    **"domain": {
                        "name": "Default"
                    },**
                    "password": "devstacker"
                }
            }
        }
    }
}
```
(taken from: [here](https://docs.openstack.org/api-ref/identity/v3/index.html)) 

I don't follow the development of Openstack and I don't know if this is an isolated case and if for other storage services the current structure works, however, I would like to draw your attention to this fact, since it may be necessary to update the way swift makes requests for v3.

There may also be a way to define these changes in the rclone configuration, but I confess I'm not aware of it.

Thank you in advance.

**Comment by MrCalv1n** [comment]
Sorry about the bold thing with the asterisks. The correct requests should be:

```
POST /auth/tokens HTTP/1.1
...

{
  "auth": {
    "identity": {
      "methods": [
        "password"
      ],
      "password": {
        "user": {
          "name": "admin",
          "password": "devstacker"
        }
      }
    },
    "scope": {
      "project": {
        "name": "storage",
        "domain": {
          "name": "Default"
        }
      }
    }
  }
}
```

and: 

```
POST /v3/auth/tokens HTTP/1.1
...

{
    "auth": {
        "identity": {
            "methods": [
                "password"
            ],
            "password": {
                "user": {
                    "name": "admin",
                    "domain": {
                        "name": "Default"
                    },
                    "password": "devstacker"
                }
            }
        }
    }
}
```

**Comment by ncw** [comment]
Can you do

    rclone config redacted

And show us your config file?

Or are you configuration things with environment vars? If so then please list the variables (I don't need to see the contents), thanks

**Comment by MrCalv1n** [comment]
As requested, I'm closing the issue and forwarding the topic to the Forum.
