### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by e-ave** [rclone/rclone#7557]
I saw this quote in another issue about the docs
> Google API Console is a bit clunky indeed. If you think that rclone docs can be more clear feel free to submit PR with improvements.

So you want the people who are struggling to learn how to use the tool to write better docs so the pros don't have to? Won't that just make the docs worse?

I think the docs could have more verbose examples. I'm a Google Cloud noob but I spent a frustrating couple of hours checking examples at [googlecloudstorage](https://rclone.org/googlecloudstorage/) and [drive](https://rclone.org/drive/) and then trying every single combination of client ID, service accounts, permissions, redirect uri, javascript origins, application type, google drive root dirs and just got tons of errors about OOB and redirect uri and Google's OAuth 2.0 policy, 

The only example I could find that worked was `rclone authorize "backend"` on the [remote setup page](https://rclone.org/remote_setup/).  The only example uses amazon cloud, and like the google pages, it fails to mention that the string is referred to as backend in this context so you can know to use the [correct strings](https://rclone.org/commands/rclone_backend/) for it. That may seem obvious if you use rclone a lot but the people who benefit most from the documentation are the noobs.

The [rclone authorize](https://rclone.org/commands/rclone_authorize/) documents really confused me because they made no mention of the string that was being passed to it in the remote_setup example, or what that string is called, except one brief note at the very bottom of the page
> [rclone](https://rclone.org/commands/rclone/) - Show help for rclone commands, flags and backends.

.. Which leads to a brick wall of text that doesn't tell you the backend strings. At least the CLI recommends `rclone help backend` which lists them all.

**Comment by kapitainsky** [comment]
> > Google API Console is a bit clunky indeed. If you think that rclone docs can be more clear feel free to submit PR with improvements.
> 
> So you want the people who are struggling to learn how to use the tool to write better docs so the pros don't have to? Won't that just make the docs worse?

I think you are quoting myself from the forum:) so I feel I should explain.

Your google example is actually perfect case where everything is clear for people familiar with google API console. These people do not have slightest problem with existing documentation. So I think it is natural that if you struggled but finally made it then you can make others life easier by trying to make documentation more clear. This is very valuable to have other person point of view what is clear and what is not. More explanations, examples etc. - better.

Documentation can always be made better - this is granted. But overall it is open source project and it can only improve when people contribute. And they do - with every release you can see list of names making documentation improvements. From correcting simple type to rewriting all sections and paragraphs. I try to do this myself when I spot that something is not right or not clear enough.

**Comment by SummerGautier** [comment]
> > > Google API Console is a bit clunky indeed. If you think that rclone docs can be more clear feel free to submit PR with improvements.
> > 
> > 
> > So you want the people who are struggling to learn how to use the tool to write better docs so the pros don't have to? Won't that just make the docs worse?
> 
> I think you are quoting myself from the forum:) so I feel I should explain.
> 
> Your google example is actually perfect case where everything is clear for people familiar with google API console. These people do not have slightest problem with existing documentation. So I think it is natural that if you struggled but finally made it then you can make others life easier by trying to make documentation more clear. This is very valuable to have other person point of view what is clear and what is not. More explanations, examples etc. - better.
> 
> Documentation can always be made better - this is granted. But overall it is open source project and it can only improve when people contribute. And they do - with every release you can see list of names making documentation improvements. From correcting simple type to rewriting all sections and paragraphs. I try to do this myself when I spot that something is not right or not clear enough.

This approach makes a lot of sense I would agree. Having a new user's pain points freshly in mind helps when writing documentation towards that audience. When people onboard to a new company for example, we always say 'take notes of what was confusing' to give to their managers. People only onboard once and don't realize what is tribal knowledge. So new hires benefit from those who documented struggles before them and they can pay it forward by doing the same. The concept applies with most projects that need a ramping up stage.

**Comment by kapitainsky** [comment]
This is very wise approach your company is using. 

Challenge here is that as many open source projects it is community driven - so depends on individuals willing to contribute for "greater good".

But documentation is definitely the most boring part:) People jump on new shiny features etc. but not many do docs.

**Comment by Animosity022** [comment]
For any doc changes, just submit a pull request with whatever you'd like.

**Comment by e-ave** [comment]
> > > > Google API Console is a bit clunky indeed. If you think that rclone docs can be more clear feel free to submit PR with improvements.
> > > 
> > > 
> > > So you want the people who are struggling to learn how to use the tool to write better docs so the pros don't have to? Won't that just make the docs worse?
> > 
> > 
> > I think you are quoting myself from the forum:) so I feel I should explain.
> > Your google example is actually perfect case where everything is clear for people familiar with google API console. These people do not have slightest problem with existing documentation. So I think it is natural that if you struggled but finally made it then you can make others life easier by trying to make documentation more clear. This is very valuable to have other person point of view what is clear and what is not. More explanations, examples etc. - better.
> > Documentation can always be made better - this is granted. But overall it is open source project and it can only improve when people contribute. And they do - with every release you can see list of names making documentation improvements. From correcting simple type to rewriting all sections and paragraphs. I try to do this myself when I spot that something is not right or not clear enough.
> 
> This approach makes a lot of sense I would agree. Having a new user's pain points freshly in mind helps when writing documentation towards that audience. When people onboard to a new company for example, we always say 'take notes of what was confusing' to give to their managers. People only onboard once and don't realize what is tribal knowledge. So new hires benefit from those who documented struggles before them and they can pay it forward by doing the same. The concept applies with most projects that need a ramping up stage.

Yeah, that may be true, but that's assuming they figure out the correct solution ;)

**Comment by kapitainsky** [comment]
> Yeah, that may be true, but that's assuming they figure out the correct solution. If not, you'll just have more garbage PRs to look through

If you still struggle with google client_id create new thread on the forum and we will try to figure out how to do it
