### ISSUE TITLE
[URGENT] rclone crypt fails when using with Linkbox integration

### ISSUE THREAD

**Issue by azowrleo** [rclone/rclone#7564]
#### What is the problem you are having with rclone?
wp-rocket-3.15.6.zip: Failed to copy: object not found

#### What is your rclone version (output from `rclone version`)
rclone copy "./wp-rocket-3.15.6.zip" linkbox-crypt: --progress
Transferred:   	    3.436 MiB / 3.435 MiB, 100%, 41.018 KiB/s, ETA -
Transferred:   	    3.436 MiB / 3.435 MiB, 100%, 38.454 KiB/s, ETA -
Transferred:   	    3.436 MiB / 3.435 MiB, 100%, 36.051 KiB/s, ETA -
Transferred:   	    3.436 MiB / 3.435 MiB, 100%, 36.051 KiB/s, ETA -
Transferred:   	    3.436 MiB / 3.435 MiB, 100%, 33.797 KiB/s, ETA -
2024/01/14 21:30:22 ERROR : wp-rocket-3.15.6.zip: Failed to copy: object not found

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Macos M1

#### Which cloud storage system are you using? (e.g. Google Drive)
Linkbox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone copy "./wp-rocket-3.15.6.zip" linkbox-crypt: --progress

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
2024/01/14 21:34:18 DEBUG : rclone: Version "v1.65.1" starting with parameters ["rclone" "copy" "./wp-rocket-3.15.6.zip" "linkbox-crypt:" "--progress" "-vv"]
2024/01/14 21:34:18 DEBUG : Creating backend with remote "./wp-rocket-3.15.6.zip"
2024/01/14 21:34:18 DEBUG : Using config file from "/Users/bob/.config/rclone/rclone.conf"
2024/01/14 21:34:18 DEBUG : fs cache: adding new entry for parent of "./wp-rocket-3.15.6.zip", "/Users/bob/Downloads"
2024/01/14 21:34:18 DEBUG : Creating backend with remote "linkbox-crypt:"
2024/01/14 21:34:18 DEBUG : Creating backend with remote "remote-linkbox:bob-downloads"
2024/01/14 21:34:18 DEBUG : wp-rocket-3.15.6.zip: Need to transfer - File not found at Destination
2024/01/14 21:34:33 DEBUG : f0mp6gp2djvkfs2lq0ai6h6g7g3vp07543bmlrmo0c4fo3k3bnd0: Trying to read object after upload: try again in 100ms (1/10)
2024/01/14 21:34:34 DEBUG : f0mp6gp2djvkfs2lq0ai6h6g7g3vp07543bmlrmo0c4fo3k3bnd0: Trying to read object after upload: try again in 200ms (2/10)
2024/01/14 21:34:34 DEBUG : f0mp6gp2djvkfs2lq0ai6h6g7g3vp07543bmlrmo0c4fo3k3bnd0: Trying to read object after upload: try again in 400ms (3/10)
2024/01/14 21:34:35 DEBUG : f0mp6gp2djvkfs2lq0ai6h6g7g3vp07543bmlrmo0c4fo3k3bnd0: Trying to read object after upload: try again in 800ms (4/10)
2024/01/14 21:34:36 DEBUG : f0mp6gp2djvkfs2lq0ai6h6g7g3vp07543bmlrmo0c4fo3k3bnd0: Trying to read object after upload: try again in 1.6s (5/10)
2024/01/14 21:34:37 DEBUG : f0mp6gp2djvkfs2lq0ai6h6g7g3vp07543bmlrmo0c4fo3k3bnd0: Trying to read object after upload: try again in 3.2s (6/10)
2024/01/14 21:34:41 DEBUG : f0mp6gp2djvkfs2lq0ai6h6g7g3vp07543bmlrmo0c4fo3k3bnd0: Trying to read object after upload: try again in 6.4s (7/10)
2024/01/14 21:34:47 DEBUG : f0mp6gp2djvkfs2lq0ai6h6g7g3vp07543bmlrmo0c4fo3k3bnd0: Trying to read object after upload: try again in 12.8s (8/10)
2024/01/14 21:35:00 DEBUG : f0mp6gp2djvkfs2lq0ai6h6g7g3vp07543bmlrmo0c4fo3k3bnd0: Trying to read object after upload: try again in 25.6s (9/10)
2024/01/14 21:35:26 DEBUG : f0mp6gp2djvkfs2lq0ai6h6g7g3vp07543bmlrmo0c4fo3k3bnd0: Trying to read object after upload: try again in 51.2s (10/10)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by azowrleo** [comment]
The object _f0mp6gp2djvkfs2lq0ai6h6g7g3vp07543bmlrmo0c4fo3k3bnd0_ exists in the destination, but the rclone is stuck cannot recognize that the file is actually there

**Comment by kglaynyi** [comment]
Same issue. please fix 🙏

**Comment by ncw** [comment]
@Viktor-Yakovchuk have you got time to look at this?

**Comment by Viktor-Yakovchuk** [comment]
I made checkout to v1.65.1 tag and set up crypto with default settings and tried to copy some different files to it. All files were successfully copied without any problem. Maybe there are some not default settings (especially about file and dir name encryption), could your please send more info?

**Comment by azowrleo** [comment]
@Viktor-Yakovchuk, my crypto configuration is to encrypt folder names and file names. So when the file name has a long hash without any suffix, the copy action fails. If I skip the filename encryption, the transfer is fine.

**Comment by MrDark-code** [comment]
rclone v.165.1 loading in Linkbox file 7 gb error test on termux :
![Screenshot_2024-01-15-14-24-34-063_com termux](https://github.com/rclone/rclone/assets/137885849/7123dc74-8a46-4dc6-ac09-e0c1c9bf44cc)

**Comment by MrDark-code** [comment]
🤔
![Screenshot_2024-01-15-15-30-42-398_com termux](https://github.com/rclone/rclone/assets/137885849/cfbbdce4-742c-4318-98bb-feb3c5c41d8e)
![Screenshot_2024-01-15-15-30-24-657_com linkbox plus android](https://github.com/rclone/rclone/assets/137885849/f42b5bee-5dd5-4faf-b686-2879ac10362e)

**Comment by Viktor-Yakovchuk** [comment]
If it is about long names maybe [this](https://github.com/rclone/rclone/pull/7551) could help

**Comment by ncw** [comment]
I think this is almost certainly about long names so the above fix should fix it which is in [the latest beta](https://beta.rclone.org/) now.

If it isn't fixed then I will re-open.
