### ISSUE TITLE
Document rclone OS compatibility requirements

### ISSUE THREAD

**Issue by kapitainsky** [rclone/rclone#7571]
As discussed on the forum:

https://forum.rclone.org/t/rclone-1-65-1-runtime-exception-error-crash-immediately-after-running-the-command/44051/7

We should add to rclone docs information about rclone OS compatibility - mostly due to changing golang requirements not all rclone versions can work on some older OS.

The current (v1.65.1) requirements are:

```
OS		Minimum Version
================================
Linux		2.6.32+
macOS		10.15 (Catalina)+
Windows		10+, Server 2016+
```

For historical versions so far based on  - https://go.dev/doc/go1.20:

```
Windows:
rclone v1.63.1 is the last rclone version working for Windows 7, 8, Server 2008 and Server 2012.

macOS:
rclone v1.63.1 is the last rclone version working for macOS 10.13 High Sierra or 10.14 Mojave

```
We have to dig a bit deeper and identify as well the last Windows XP version and older macOS.

**Comment by kapitainsky** [comment]
And here some archeology including the latest rclone version using particular golang version:

```
Go 1.16 is the last release that will run on macOS 10.12 Sierra. Go 1.17 will require macOS 10.13 High Sierra or later.
rclone v1.56.0
- go/version: go1.16.6


Go 1.14 is the last release that will run on macOS 10.11 El Capitan. Go 1.15 will require macOS 10.12 Sierra or later.
rclone v1.52.0
- go version: go1.14.3


Go 1.12 is the last release that will run on macOS 10.10 Yosemite. Go 1.13 will require macOS 10.11 El Capitan or later.
rclone v1.49.0
- go version: go1.12.9


Go 1.10 is the last release that will run on OS X 10.8 Mountain Lion or OS X 10.9 Mavericks. Go 1.11 will require OS X 10.10 Yosemite or later.
Go 1.10 is the last release that will run on Windows XP or Windows Vista. Go 1.11 will require Windows 7 or later.
rclone v1.42
- go version: go1.10
```

I do not think that it is practical to go further back in time.

**Comment by ncw** [comment]
That is a great bit of research - thank you.  If we've got back to go1.10 that was released in Feb 2018 so 6 years ago. Rclone of 6 years ago is unlikely to work well with a lot of the cloud providers so that seems like a good place to stop.

> Given that current rclone version supports Linux kernels 2.6.32+ (from 2003) there is no need to dig Linux further neither IMO.

That sounds fine to me. I think they did increase the linux kernel requirement at some point but it was from one even older which is probably only of interest to RedHat enterprise users which seem to use very old kernels. I think that current rclone should run on RHEL 6 according to the kernel version.

Do you want to condense the above into some tables and make a PR for the docs? Thank you :-)

**Comment by kapitainsky** [comment]
> Do you want to condense the above into some tables and make a PR for the docs? Thank you :-)

done

https://github.com/rclone/rclone/pull/7573

**Comment by dermitza** [comment]
I did compile the last two versions ([1.66](https://github.com/rclone/rclone/tree/v1.66.0 ) and [1.67](https://github.com/rclone/rclone/tree/v1.67.0)) still allowing go 1.20 that will work with Win7 - 1.68 has link package dependencies on go 1.21 afaik. I attach them below in hopes they still might be of use to someone. 

Didn't want to create a repo for this or open a new issue as it seems that it might be quite an obsolete task/feature. If you dont think the binaries should be here please let me know and I'll delete the comment (or relocate).

[rclone-v1.66.0-go1.20.14-windows-amd64.zip](https://github.com/user-attachments/files/17558846/rclone-v1.66.0-go1.20.14-windows-amd64.zip)
[rclone-v1.67.0-go1.20.14-windows-amd64.zip](https://github.com/user-attachments/files/17558858/rclone-v1.67.0-go1.20.14-windows-amd64.zip)
