### ISSUE TITLE
rclone serve webdav custom dirs

### ISSUE THREAD

**Issue by vtolstov** [rclone/rclone#7583]
i'm using rclone for webdav serving, i know that it can run some script to provide for different user/pass combination different roots. But if i need to have something like 
user1: user1_dir, common_docs, common_music
user2: user2_dir, common_docs, common_music
user3: user3_dir, ....

**Comment by ncw** [comment]
Yes that is what the auth proxy will do for you.

Here is a simple demo program: https://github.com/rclone/rclone/blob/master/bin/test_proxy.py

You'd alter this to change the `_root` for each user.

If you wanted to add other common directories you could create a [combine](https://rclone.org/combine/) backend on the fly to access the users home directory and other folders.

**Comment by vtolstov** [comment]
thanks!
