### ISSUE TITLE
OOM Problem

### ISSUE THREAD

**Issue by huangminzi** [rclone/rclone#7587]
I currently have 10T of data, but the memory of my source machine is only 32G. Every time I transfer, it will cause OOM. Do you have any better solutions?

**Comment by huangminzi** [comment]
Regarding my files, each file is approximately 10240 bytes. When I tested it, I only tested a server with 16GB of memory, and there are about 10m files in a directory, which can also cause OOM

**Comment by Animosity022** [comment]
Please use the forums.

https://forum.rclone.org
