### ISSUE TITLE
EXT4-fs error

### ISSUE THREAD

**Issue by sharicov** [rclone/rclone#7588]
running rclone systematically using script.
Very often usb connected disk got dropped from the system (unmouted) with following errors:

EXT4-fs error (device sdd1): __ext4_find_entry:1682: inode #2: comm rclone: reading directory lblock 0

In the system disk is still shown as mounted but cannot be accessed.

mount |grep sd

/dev/sda1 on /media/usb type ext4 (rw,noatime,stripe=8191)

ls /media/usb

ls: reading directory '/media/usb': Input/output error

killing rclone processes and remounting works fine till the next time

**Comment by Animosity022** [comment]
Please use the forums.

https://forum.rclone.org
