### ISSUE TITLE
Request: Predict disk full before sync job

### ISSUE THREAD

**Issue by nagualcode** [rclone/rclone#759]
Can rclone predict there wont be enough storage to download all the files form source?
Cron run a sync job every house, from server to local hd, and if by mistake I let the server files grow more than what fits into the local HD, a whole day of cron jobs will result in lots of wa$ted data u$age in the s3 service, because it will always start sync, download a buch of data, exits in error whem disk gets full, liberate some extra free space when temp files are gone, and get ready to start again and again each hour...
Maybe the best I can do is a bash script to compare rclone --size result .vs the output of "df" command?
Thank you!

**Comment by ncw** [comment]
Unfortunately rclone doesn't know how much disk it needs until it has done the sync.

It would have to do a pre-pass which would slow things down, rather like using `--delete-before`.

**Comment by animosity22** [comment]
Just going through and cleaning some older items up.

I'm not sure this would be something inside rclone as like rsync, things like that happen with a pre check or something along those lines. The bane of many things is running out of disk space. 

I would think it's best to close this out as it's normally handled with a pre check or something along those lines and that can be done with script or something.

@nagualcode  - good to close this out?
