### ISSUE TITLE
bwlimit parsing issues

### ISSUE THREAD

**Issue by TimetravelerDD** [rclone/rclone#7595]
### Introduction

As a user of rclone, particularly in Docker environments in unRaid, I've noticed a recurring issue that affects many of us who rely on rclone's bandwidth limiting features. The use of spaces as separators in the `bwlimit` timetable syntax often leads to parsing problems within Docker configurations. This issue has been discussed on the rclone forum and various places on github, and I believe a simple yet effective change could significantly improve user experience in these scenarios.

### The associated forum post URL

https://forum.rclone.org/t/docker-volume-plugin-bwlimit-timetable/28219/4

### What is your current rclone version (output from `rclone version`)?

rclone v1.65.1
- os/version: arch (64 bit)
- os/kernel: 6.1.64-Unraid (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.6
- go/linking: dynamic
- go/tags: none

### What problem are you are trying to solve?

The problem is the conflict between rclone's `bwlimit` timetable syntax, which uses spaces as separators, and Docker's formatting. This leads to frequent parsing issues when configuring rclone within Docker environments.

### How do you think rclone should be changed to solve that?

I propose an enhancement to rclone's syntax to allow alternative characters, such as semicolons (`;`), as separators in the `bwlimit` timetable. This change would enable better compatibility with Docker and reduce the parsing issues currently experienced. The flexibility to use different separators would be a valuable addition for users working in various configurations and environments.

instead of just
`--BWLIMIT="08:00,400k:off 23:00,off"`
also allow:
`--BWLIMIT="08:00,400k:off;23:00,off"`
which would eliminate the need for the double quote characters, thus making parsing that much more predictable
`--BWLIMIT=08:00,400k:off;23:00,off`

**Comment by ncw** [comment]
That sounds like a good change provided it is backwards compatible.

Do you want to have a go at this @TimetravelerDD ?

**Comment by KDreynolds** [comment]
I can take a stab at this one.

**Comment by ncw** [comment]
I've merged a fix for this to master now (thank you @KDreynolds for implementing it) which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.68

Please give it a go @TimetravelerDD
