### ISSUE TITLE
[OneDrive] vfs reader: failed to write to cache file: unauthenticated: Unauthenticated

### ISSUE THREAD

**Issue by gitgitgithut** [rclone/rclone#7597]
#### The associated forum post URL from `https://forum.rclone.org`
None

#### What is the problem you are having with rclone?
Files in Mounted onedrive directory can not be accessed. Got error 'ERROR : [my file]: vfs cache: failed to download: vfs reader: failed to write to cache file: unauthenticated: Unauthenticated'.

#### What is your rclone version (output from `rclone version`)
rclone v1.65.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Debian 12, 64 bit, kernel 6.1.0-17-amd64

#### Which cloud storage system are you using? (e.g. Google Drive)
OneDrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone --vfs-cache-mode full --vfs-read-chunk-size 0 mount "onedrive":/ ~/OneDrive --log-file ~/log.txt'

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
[log.txt](https://github.com/rclone/rclone/files/14062072/log.txt)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by kapitainsky** [comment]
Could you please post this on the https://forum.rclone.org/ and provide all details?

You can close it here - github is not for troubleshooting.

**Comment by fayzanx** [comment]
For anyone who comes across this in the future, this particular issue appears for a subset of old OneDrive accounts because of presence of `Authorization` header. Error is gone when the header is removed.

Installing this patch solved the issue for me: https://forum.rclone.org/t/cryptcheck-on-encrypted-onedrive-personal-failed-with-unauthenticated-error/44581/6?u=gpk

**Comment by ncw** [comment]
Thank you for testing. I didn't see the replies to my message on the forum for some reason.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.67

**Comment by Jump2nj** [comment]
> For anyone who comes across this in the future, this particular issue appears for a subset of old OneDrive accounts because of presence of `Authorization` header. Error is gone when the header is removed.对于将来遇到这个问题的任何人来说，由于`Authorization`标头的存在，这个特定问题出现在旧的OneDrive帐户中。卸下标题时，错误消失了。
> 
> Installing this patch solved the issue for me: https://forum.rclone.org/t/cryptcheck-on-encrypted-onedrive-personal-failed-with-unauthenticated-error/44581/6?u=gpk安装此补丁为我解决了问题： [https：//forum.rclone.org/t/cryptcheck-on-enderpted-onedrive-personal-personal-failed-with-unauthenticated-error/444581/6?](https://forum.rclone.org/t/cryptcheck-on-encrypted-onedrive-personal-failed-with-unauthenticated-error/44581/6?u=gpk) u=gpk

Thank you for your reply, after a busy afternoon, I finally solved it.
