### ISSUE TITLE
Docs include trailing bracket into URL

### ISSUE THREAD

**Issue by claell** [rclone/rclone#7600]
https://rclone.org/koofr/#standard-options have this section:

![grafik](https://github.com/rclone/rclone/assets/6171135/ae008a3a-dc02-4fad-b379-c6412d2abe56)

As you can see, the trailing bracket `)` is included in the link of the URL, making it not working when clicking it:

`https://app.koofr.net/app/admin/preferences/password)`

The docs seem to come from https://github.com/rclone/rclone/blob/master/docs/content/koofr.md. This file doesn't have the problem:

![grafik](https://github.com/rclone/rclone/assets/6171135/f2a784bb-dce3-49b7-8a47-a87c5ad26b23)

I assume that this is some issue with the conversion of Markdown to the docs HTML. Possibly also an upstream issue.

**Comment by Animosity022** [comment]
You can just submit a PR to fix.

**Comment by kapitainsky** [comment]
> The docs seem to come from https://github.com/rclone/rclone/blob/master/docs/content/koofr.md. This file doesn't have the problem:

This section is auto generated from here:

https://github.com/rclone/rclone/blob/6e4dd2ab965b009607823b575b2e751e7648031d/backend/koofr/koofr.go#L69-L80

Feel free to fix it. If there is problem with `)` maybe just remove it? e.g.:

`Your password for rclone - generate one at https://app.koofr.net/app/admin/preferences/password`

Do the same for `digistorage` too.

**Comment by claell** [comment]
Thanks for the hints so far. The thing is, and that is why I created an issue: This seems to be a systematic bug. The bracket should not be included in the link. Of course, the quick fix is to remove the bracket. But I hoped, there would be a better fix (maybe upstream in the software used to generate the website).

**Comment by kapitainsky** [comment]
> Thanks for the hints so far. The thing is, and that is why I created an issue: This seems to be a systematic bug. The bracket should not be included in the link. Of course, the quick fix is to remove the bracket. But I hoped, there would be a better fix (maybe upstream in the software used to generate the website).

Good idea. In the meantime you can implement quick fix and then follow with upstream.

**Comment by albertony** [comment]
Hugo (https://github.com/gohugoio/hugo) is the tool used to generate the html.

I guess it is doing some automatic link detection. Did a very quick search, but couldn't find an existing issue for this, only the opposite: Links such as "https://en.wikipedia.org/wiki/Plane_(geometry)" did not include the ending `)`. We use the original description also for command line output of `rclone help backend koofr`, so we don't want to embed a lot of hugo/html specific notation either.

**Comment by ncw** [comment]
I tried upgrading hugo (the software which builds the website) to the latest version but it made no difference.

So removing the `()` or maybe putting a space before the `)` might be the way to go.

However point taken - maybe we can configure this in hugo.

The markdown rendering is done by https://github.com/yuin/goldmark which claims it can use GitHub flavoured markdown https://github.github.com/gfm/#autolinks-extension- which addresses the problem directly

> When an autolink ends in ), we scan the entire autolink for the total number of parentheses. If there is a greater number of closing parentheses than opening ones, we don’t consider the unmatched trailing parentheses part of the autolink, in order to facilitate including an autolink inside a parenthesis:

In fact Hugo claims to be Github Flavored Markdown [out of the box](https://gohugo.io/getting-started/configuration-markup/)

> Unless you need a unique capability provided by one of the alternate markdown handlers, we strongly recommend that you use the default setting. Goldmark is fast, well maintained, conforms to the [CommonMark](https://spec.commonmark.org/0.30/) specification, and is compatible with [GitHub Flavored Markdown](https://github.github.com/gfm/) (GFM).

This is how we've configured the Goldmark renderer

https://github.com/rclone/rclone/blob/ef2c5a199870bc3cfdb0b854576c7749350c7aa7/docs/config.json#L26-L35

I tried various things but I couldn't get it to do anything different!

**Comment by claell** [comment]
Alright! Then the quick workaround will need to suffice for now! I hope I can get around providing a PR, soon!

**Comment by KDreynolds** [comment]
sorry for the commit spam here, did some silly stuff on my fork, quick fix should be good to go though now.
