### ISSUE TITLE
browser not shown else 

### ISSUE THREAD

**Issue by agus-syarif** [rclone/rclone#7604]
#### Output of `rclone version`

2024/01/29 04:47:35 NOTICE: If your browser doesn't open automatically go to the following link: http://127.0.0.1:53682/auth?state=fXpJgEOFAsOSOS93GncwZA
2024/01/29 04:47:35 NOTICE: Log in and authorize rclone for access
2024/01/29 04:47:35 NOTICE: Waiting for code..

#### Describe the issue

but the url http://127.0.0.1:53682/auth?state=fXpJgEOFAsOSOS93GncwZA is blank in my browser

**Comment by Animosity022** [comment]
Use the forums.
