### ISSUE TITLE
Documentation for subcommand genautocomplete not in line with completion

### ISSUE THREAD

**Issue by albertony** [rclone/rclone#7605]
The documentation of the [completion](https://rclone.org/commands/rclone_completion/) subcommand lists PowerShell, while the [genautocomplete](https://rclone.org/commands/rclone_genautocomplete/) does not. However `genautocomplete` is [now](https://github.com/rclone/rclone/commit/51a468b2bae4ca8e21760435211623a8199a9167) simply an alias for `complete`, and therefore both supports powershell and lists it in help command output.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
When I try `rclone gendocs /tmp/content` to make the docs it only makes the `rclone_completion.md` file, so I think the `rclone_genautocomplete.md` is stale.

Perhaps we should delete the content and put a [redirect like the tardigrade one](https://github.com/rclone/rclone/blob/master/docs/content/tardigrade.md) or maybe put [an alias](https://bwaycer.github.io/hugo_tutorial.hugo/extras/aliases/) in the completion file which would be quite easy.

**Comment by albertony** [comment]
Right. Sounds like we should just delete the docs/content/commands/rclone_genautocomplete*.md then.

Regarding redirect/alias, is the reason simply to avoid dangling links somewhere? I was thinking that a possible advantage of a redirect page like used for tardigrade is that it makes more sense to keep listing it e.g. in "Storage Systems" menu, however it seems that is not done for tardigrade and then isn't the alias solution simpler (better)?

I added a suggestion here: https://github.com/rclone/rclone/pull/7606 (I found a few references to genautocomplete here and there in the docs which I replaced with completion as well).

**Comment by albertony** [comment]
Hm, doesn't look like the aliasing worked: Shouldn't we expect https://tip.rclone.org/commands/rclone_genautocomplete/ to automatically redirect to https://tip.rclone.org/commands/rclone_completion/?

**Comment by ncw** [comment]
I don't think we or cobra implements that.

We could change the config doc generator to generate something like this for aliases

```
---
title: "Tardigrade"
description: "Rclone docs for Tardigrade"
versionIntroduced: "v1.52"
---

# {{< icon "fas fa-dove" >}} Tardigrade

The Tardigrade backend has been renamed to be the [Storj backend](/storj/).
Old configuration files will continue to work.
```

**Comment by albertony** [comment]
When I run Hugo, I get in docs\public\commands both directories rclone_completion* and rclone_genautocomplete*, and the latter contains html files like this:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>https://rclone.org/commands/rclone_completion/</title>
    <link rel="canonical" href="https://rclone.org/commands/rclone_completion/">
    <meta name="robots" content="noindex">
    <meta charset="utf-8">
    <meta http-equiv="refresh" content="0; url=https://rclone.org/commands/rclone_completion/">
  </head>
</html>
```

So I think this works as I think... 😵 

Could it be something with the publishing to https://tip.rclone.org, that it does not include the generated alias folders or something? 🤔

**Comment by ncw** [comment]
> I keep forgetting the details how the source ends up in the html page,

Yes me too. But what happens is the command

```
rclone gendocs /tmp/docs
```

Gets run to make the documentation.

Looking in the generated docs, the /tmp/docs/commands/rclone_completion.md doesn't appear to have hugo aliases in it which is why it isn't working.

However we make that frontmatter so I think it would be relatively easy to add the aliases there

https://github.com/rclone/rclone/blob/70e8ad456fcc627f57c001aa82ac925bd9fb47a8/cmd/gendocs/gendocs.go#L36-L43

> but I was under the impression that with this alias attribute Hugo would generate a redirect page automatically (auto-redirect using the `http-equiv="refresh" html trick`), as explained in [How Hugo Aliases Work](https://bwaycer.github.io/hugo_tutorial.hugo/extras/aliases/):

I didn't know that! We should probably update the storj docs and delete the tardigrade bodge page I did :-)

> > When aliases are specified, Hugo creates a physical folder structure to match the alias entry, and, an html file specifying the canonical URL for the page, and a redirect target.

> When I run Hugo, I get in docs\public\commands both directories rclone_completion* and rclone_genautocomplete*, and the latter contains html files like this:
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
>   <head>
>     <title>https://rclone.org/commands/rclone_completion/</title>
>     <link rel="canonical" href="https://rclone.org/commands/rclone_completion/">
>     <meta name="robots" content="noindex">
>     <meta charset="utf-8">
>     <meta http-equiv="refresh" content="0; url=https://rclone.org/commands/rclone_completion/">
>   </head>
> </html>
> ```
> 
> So I think this works as I think... 😵

How are you creating the docs? Are you running `make commanddocs`? As that is how they get generated normally.

I am confused now :-)

> Could it be something with the publishing to https://tip.rclone.org, that it does not include the generated alias folders or something? 🤔

I checked that out and I don't think so, we just copy all the files in public

The script is here

https://github.com/rclone/integration-test/blob/master/upload-tip.sh

And the integration test server has 

```
hugo v0.127.0-74e0f3bd63c51f3c7a0f07a7c779eec9e922957e linux/amd64 BuildDate=2024-06-05T10:27:59Z VendorInfo=gohugoio
```

Which is not the very latest version but quite recent.

**Comment by albertony** [comment]
> How are you creating the docs? Are you running make commanddocs? As that is how they get generated normally.

Right... What I probably did in the test where it worked, was not running the gendocs command, only Hugo - on the existing markdown files. After a few attempts I took that shortcut because I figured I don't need to update the autogenerated sections for this test. But then I missed the part that the frontmatter is recreated - and then the aliases property is not included.

**Comment by albertony** [comment]
I'm testing out a fix, not to far away. Unless you're already on it I can create a PR in some minutes..

**Comment by albertony** [comment]
This should be fixed by https://github.com/rclone/rclone/pull/8006, currently in beta (https://tip.rclone.org/), so I will close it now.

PS:

> We should probably update the storj docs and delete the tardigrade bodge page I did :-)

Done: https://github.com/rclone/rclone/pull/8014
