### ISSUE TITLE
flushCache() in bisync_test.go never actually flushes the cache?

### ISSUE THREAD

**Issue by dmcardle** [rclone/rclone#7623]
The `flushCache()` function is called several times in bisync_test.go, but it doesn't seem to do what its name would suggest.

I would expect it to actually call `f.Features().DirCacheFlush`, but instead, it just checks whether the function pointer is nil.  Given that the tests pass without calling the `DirCacheFlush` function, I wonder whether `flushCache()` should just be deleted.

 Am I just missing something?

https://github.com/rclone/rclone/blob/2abeda5961615c304348c4886a1d42f4ae30c876/cmd/bisync/bisync_test.go#L772-L777

**Comment by dmcardle** [comment]
Hi @nielash, it looks like you added `flushCache()` a few weeks ago in 57624629d6b43177846fd64b3e252d1ad364bec4.  Maybe you can take a peek at this issue :)

**Comment by nielash** [comment]
Hi @dmcardle, I think you are right. It was an oversight on my part, and is not actually doing anything right now. Thanks for spotting that. Would you like to submit a PR to fix (or remove) it?

**Comment by dmcardle** [comment]
Thanks for confirming! Sure, I'll upload a PR in a minute.
