### ISSUE TITLE
New subcommand that allows exports from git-annex?

### ISSUE THREAD

**Issue by dmcardle** [rclone/rclone#7625]
Hi folks, is there any interest in a new rclone subcommand that acts as a [git-annex](https://git-annex.branchable.com/) remote? The term "remote" is unfortunately overloaded by git-annex and rclone; I'm describing an rclone subcommand that speaks the git-annex [external special remote protocol](https://git-annex.branchable.com/design/external_special_remote_protocol/), enabling git-annex to store and retrieve content from rclone remotes.

A similar project called [git-annex-remote-rclone](https://github.com/git-annex-remote-rclone/git-annex-remote-rclone) already exists, but my primary complaint is that it does not support [git-annex-export](https://git-annex.branchable.com/git-annex-export/), aka "tree exports". As a result, the content exported from git-annex to an rclone remote is opaque to humans -- just a bunch of files with names like "GPGHMACSHA512--${DIGEST}", not a browseable file tree.

I think there's also some potential performance improvements if we move the client into rclone. For instance, it could support git-annex's ASYNC protocol extension rather than transferring files one at a time. I assume there's also some overhead to exec-ing rclone once per file that could be eliminated with a more persistent client.

This is admittedly pretty niche, but I'd be pleasantly surprised if there's any community interest!

---

#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/new-subcommand-for-git-annex-remote/44546

#### What is your current rclone version (output from `rclone version`)?

N/a.

#### What problem are you are trying to solve?

Export content from git-annex.

#### How do you think rclone should be changed to solve that?

With a new subcommand.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
This certainly sounds interesting.

I don't know how the git annex protocol works but if it involves calling rclone many times then it would be most efficient to run an rclone server.

Is this something you are interested in writing?

**Comment by dmcardle** [comment]
Glad to see there's some interest!

> Is this something you are interested in writing?

Yep, I'm already working on it!

@ncw Would you accept this as a new subcommand, or would you prefer it to be a separate binary?

I find motivation/time in bursts, so it's hard to estimate when I'll have something worth sharing. Regardless, here's a rough sequence of milestones I'd like to hit:

1.  Minimal support for the [external special remote protocol](https://git-annex.branchable.com/design/external_special_remote_protocol/). I believe this would achieve feature parity with [git-annex-remote-rclone](https://github.com/git-annex-remote-rclone/git-annex-remote-rclone).
    * At minimum, needs to pass `git annex testremote` for some subset of rclone remotes.
    * Would also be nice to have unit tests for the new subcommand written in Go.
3. Add support for the ASYNC protocol extension. This should save us the overhead of starting up rclone N times over N transfers.
    * Maybe develop a benchmark to measure the performance improvement.
5. Add support git-annex's [simple export interface](https://git-annex.branchable.com/design/external_special_remote_protocol/export_and_import_appendix/). This will enable exporting human-browseable file trees to rclone remotes.

**Comment by yarikoptic** [comment]
So this issue would be closed whenever such functionality gets released within rclone? 
Is there documentation to point to while talking about already existing implementation? (I would like to refer visitors of https://github.com/git-annex-remote-rclone/git-annex-remote-rclone/ to it)

**Comment by dmcardle** [comment]
@yarikoptic Yeah, I was imagining keeping this open until I've implemented tree exports.

The best documentation is currently this markdown file: https://github.com/rclone/rclone/blob/master/cmd/gitannex/gitannex.md

That file is also what `rclone gitannex -h` prints to stdout. I think when there's a new release, it will show up on the website (automatically?) under <https://rclone.org/commands/>.

**Comment by stv0g** [comment]
@ncw @dmcardle I guess we can close this ticket now? The feature seems to be merged?

**Comment by dmcardle** [comment]
There's still a list of a few things I didn't get to yet in the [comment above](https://github.com/rclone/rclone/issues/7625#issuecomment-1951403856), but I think breaking this issue into bite-sized pieces is the right call.

The primary missing features are ASYNC and implementing the [simple export interface](https://git-annex.branchable.com/design/external_special_remote_protocol/export_and_import_appendix/). But I'm not sure if I'm going to get around to either of these anytime soon.
