### ISSUE TITLE
New reigion for AWS S3 "ca-west-1"

### ISSUE THREAD

**Issue by ltwcloud** [rclone/rclone#7638]
Hello,

AWS Canada West (Calgary) Region is now available. When is this location will be available in rclone?

Thanks,
user

**Comment by kapitainsky** [comment]
`rclone` allows to use any AWS regions. When you configure your remote you are given following option:

```
Region to connect to.
Choose a number from below, or type in your own value
```

So type your own value..

You can also submit PR and add this region to predefined list.

It has to be added to https://github.com/rclone/rclone/blob/master/backend/s3/s3.go file

**Comment by kapitainsky** [comment]
If you decide to add `Canada West (Calgary) ca-west-1` to predefined list in https://github.com/rclone/rclone/blob/master/backend/s3/s3.go it would be great if you could also add other missing regions.

You will find full list here - https://docs.aws.amazon.com/general/latest/gr/rande.html

Some other missing regions:

```
Israel (Tel Aviv) 	il-central-1
Asia Pacific (Hyderabad)	ap-south-2
```

**Comment by ltwcloud** [comment]
Thank you very much
