### ISSUE TITLE
Update go-mega dependency for go-1.22

### ISSUE THREAD

**Issue by finkandreas** [rclone/rclone#7639]
With the introduction of go-1.22, there is a minor problem with go-mega. This has been already fixed upstream (see https://github.com/t3rm1n4l/go-mega/issues/48).
Would it be possible to bump the version of go-mega for rclone?

Command that fails:
```bash
rclone delte my_mega:path/to/file
```

**Comment by ncw** [comment]
Good plan!

Can you try this?

[v1.66.0-beta.7705.019a09a15.fix-7639-mega-panic](https://beta.rclone.org/branch/fix-7639-mega-panic/v1.66.0-beta.7705.019a09a15.fix-7639-mega-panic/) on branch [fix-7639-mega-panic](https://github.com/rclone/rclone/tree/fix-7639-mega-panic) (uploaded in 15-30 mins)

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.66

**Comment by finkandreas** [comment]
thanks a lot for this. It works for me now again.
