### ISSUE TITLE
 selfupdate Error: failed to update rclone: invalid hashsum signature

### ISSUE THREAD

**Issue by contenidosonline** [rclone/rclone#7640]
#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Centos 7

#### Which cloud storage system are you using? (e.g. Google Drive)

rclone v1.64.0
- os/version: cloudlinux 7.9 (64 bit)
- os/kernel: 3.10.0-962.3.2.lve1.5.81.el7.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.1
- go/linking: static
- go/tags: none

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

 rclone selfupdate
2024/02/19 11:02:54 Error: failed to update rclone: invalid hashsum signature

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

 rclone selfupdate -vv
2024/02/19 11:03:16 DEBUG : rclone: Version "v1.64.0" starting with parameters ["rclone" "selfupdate" "-vv"]
2024/02/19 11:03:20 DEBUG : downloaded release archive with hashsum 2155ea2c225272a6f78b2aa4547bb587c40b007586e73b41b31c59edba64f8fe from https://downloads.rclone.org/v1.65.2/rclone-v1.65.2-linux-amd64.zip
2024/02/19 11:03:20 DEBUG : downloaded hashsum list: https://downloads.rclone.org/v1.65.2/SHA256SUMS
2024/02/19 11:03:20 Error: failed to update rclone: invalid hashsum signature

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by kapitainsky** [comment]
It is known issue and has been already fixed:

https://github.com/rclone/rclone/commit/4325a7c362ce9487d1e22ee95a09d72e9c75ee3c

Unfortunately for your version you have to update manually - download the latest version from https://rclone.org/install/

With the latest version selfupdate works again without any issues.

**Comment by contenidosonline** [comment]
thanks

**Comment by Animosity022** [comment]
Closing as answered.
