### ISSUE TITLE
Upload the difference of the changed files

### ISSUE THREAD

**Issue by srezasm** [rclone/rclone#7648]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/upload-the-difference-of-changed-files-instead-of-the-whole-thing/44774

#### What is your current rclone version (output from `rclone version`)?
v1.65.0

#### What problem are you are trying to solve?
Every time there's a slight change in a file, RClone uploads the whole file and replaces the old one, whereas it could only upload the difference.

#### How do you think rclone should be changed to solve that?
I think it should be the default way to go, but a flag such as `--upload-diff` can be added as well.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by kapitainsky** [comment]
It has been already answered on the forum in your another post.

Please do not post the same question all over the place.
