### ISSUE TITLE
Rclone checks for unnecessary files and folders when using the copyto command

### ISSUE THREAD

**Issue by superset1** [rclone/rclone#7666]
#### What is the problem you are having with rclone?

Hello! We have 2 S3 accounts. I want to copy 10 specific files as quickly as possible, which are listed in the sync_list file. Each file weighs 10-50 KB. But rclone starts checking the entire S3-bucket in the account before it starts copying the files it needs. This takes a huge amount of time as we have millions of files in S3-bucket.

#### What is your rclone version (output from `rclone version`)

```
rclone version
rclone v1.53.3-DEV
- os/arch: linux/amd64
- go version: go1.15.9
``` 

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

`Debian GNU/Linux 11 (bullseye)`

#### Which cloud storage system are you using? (e.g. Google Drive)

`ceph`

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
rclone copyto config_old:bucket_docs config_new:bucket_docs -P -vv --fast-list --no-check-dest --retries 1 --transfers 1000 --files-from sync_list
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2024/03/08 17:50:10 DEBUG : rclone: Version "v1.53.3-DEV" starting with parameters ["rclone" "copyto" "config_old:bucket_docs" "config_new:bucket_docs" "-P" "-vv" "--fast-list" "--no-check-dest" "--retries" "1" "--transfers" "1000" "--files-from" "sync_list"]
2024/03/08 17:50:10 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2024/03/08 17:50:10 DEBUG : Creating backend with remote "config_old:bucket_docs"
2024/03/08 17:50:10 DEBUG : Creating backend with remote "config_new:bucket_docs
2024-03-08 17:57:14 DEBUG : 010123/120992855: Excluded
2024-03-08 17:57:14 DEBUG : 010123/120992867: Excluded
2024-03-08 17:57:14 DEBUG : 010123/120992868: Excluded
2024-03-08 17:57:14 DEBUG : 010123/120992872: Excluded
2024-03-08 17:57:14 DEBUG : 010123/120992875: Excluded
2024-03-08 17:57:14 DEBUG : 010123/120992876: Excluded
2024-03-08 17:57:14 DEBUG : 010123/120992877: Excluded
2024-03-08 17:57:14 DEBUG : 010123/120992879: Excluded
2024-03-08 17:57:14 DEBUG : 010123/120992880: Excluded
2024-03-08 17:57:14 DEBUG : 010123/120992882: Excluded
2024-03-08 17:57:14 DEBUG : 010123/120992887: Excluded
2024-03-08 17:57:14 DEBUG : 050323/148226659: Excluded
2024-03-08 17:57:14 DEBUG : 050323/148226660: Excluded
2024-03-08 17:57:14 DEBUG : 050323/148226661: Excluded
2024-03-08 17:57:14 DEBUG : 050323/148226662: Excluded
2024-03-08 17:57:14 DEBUG : 050323/148226663: Excluded
2024-03-08 17:57:14 DEBUG : 050323/148226664: Excluded
2024-03-08 17:57:14 DEBUG : 050323/148226666: Excluded
2024-03-08 17:57:14 DEBUG : 050323/148226667: Excluded
2024-03-08 17:57:14 DEBUG : 050323/148226669: Excluded
2024-03-08 17:57:14 DEBUG : 050323/148226672: Excluded
...
...
...
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Elapsed time:      46m36.0s
```

#### Rclone config

```
rclone config show
[bucket_old]
type = s3
provider = Other
env_auth = false
access_key_id = *****
secret_access_key = *****
endpoint = *****
acl = private

[bucket_new]
type = s3
provider = Other
env_auth = false
access_key_id = *****
secret_access_key = *****
endpoint = *****
acl = private
```

#### Our list of files

```
cat sync_list
210123/23333995/23333995.txt
050323/150145599/150145599.txt
010123/23941421/23941421.txt
060123/77107102/77107102.txt
040323/118053120/118053120.txt
200223/106163744/patch_1676922509.txt
110223/91373395/patch_1676086505.txt
070323/16677173/patch_1678179158.txt
110223/106851934/patch_1676081042.txt
290323/76198099/patch_1680086978.txt
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
That might be becuase you have a version like 5-6 years old.

```
rclone v1.53.3-DEV
```

I'd suggest upgrading and posting any current questions on setup on the forums as we can help out.

Thanks!

https://forum.rclone.org

**Comment by superset1** [comment]
it didn't help, the new version works exactly the same. It also checks paths and files that are not listed in the sync_list

**Comment by superset1** [comment]
I've opened new issue with new version and log https://github.com/rclone/rclone/issues/7669
