### ISSUE TITLE
Single sign on support for Seafile

### ISSUE THREAD

**Issue by YuruiHong** [rclone/rclone#7675]
#### The associated forum post URL from `https://forum.rclone.org`

None

#### What is your current rclone version (output from `rclone version`)?

rclone v1.60.1-DEV
- os/version: debian trixie/sid (64 bit)
- os/kernel: 6.7.9-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.3
- go/linking: dynamic
- go/tags: none

#### What problem are you are trying to solve?

Single sign on support for Seafile

#### How do you think rclone should be changed to solve that?

I am not sure, but perhaps it can be solved by fetching login credentials via browser, like the process for OneDrive. The Seafile client itself launches a browser window to redirect me to the login page of the self-hosted service.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
You have an old version. Update and it would work.

For general support, please use the forums:

https://forum.rclone.org

**Comment by YuruiHong** [comment]
Tried latest v1.66.0 and v1.67.0-beta.7778.7803b4ed6, but there's still no good luck. Cannot find SSO-related posts on the forum. Please consider reopening this.😢
