### ISSUE TITLE
v1.66.0 rclone.conf token does not have refresh token

### ISSUE THREAD

**Issue by minnieshi** [rclone/rclone#7676]
#### What is the problem you are having with rclone?
rclone sync from BOX to somewhere fails due to it runs more than 1 hour, and the rclone.conf does not have refresh token.
the job starts with reconnect which creates the rclone.conf

see error message
```
token expired and there's no refresh token - manually refresh with "rclone config reconnect source_box{3ECN5}
```

#### What is your rclone version (output from `rclone version`)
v1.66.0
```
<<K9s-Shell>> Pod: the-glue-staging/rclone-sync-data-from-box-to-azure-9dn8hso0 | Container: base
/data # rclone version
rclone v1.66.0
- os/version: alpine 3.19.1 (64 bit)
- os/kernel: 5.15.0-1042-azure (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.1
- go/linking: static
- go/tags: none
/data #
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
kubenetes pods, linux, copied from above version section
```
os/version: alpine 3.19.1 (64 bit)
```

#### Which cloud storage system are you using? (e.g. Google Drive)
BOX

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

https://rclone.org/box/#invalid-refresh-token shows we should have 'refresh_token' field filled in when running reconnect, but we do not have it

```
$ rclone config reconnect source_box: 
```

below is the output to show the rclone.conf file (removed token details)

```
<<K9s-Shell>> Pod: the-glue-staging/rclone-sync-data-from-box-to-azure-xugxn6q4 | Container: base
/data # cd /config
/config # ls
rclone

/config # cd rclone/
/config/rclone # ls
rclone.conf
/config/rclone # cat rclone.conf
[source_box]
type = box
box_sub_type = enterprise
root_folder_id = 197241957669
token = {"access_token":"blah-blah-blah","token_type":"bearer","expiry":"2024-03-19T16:22:46.556100508Z"}

[target_azureblob]
type = azureblob
account = sablahblah
env_auth = true
tenant = blahblah-blah-blah-blahblah-blahblah

/config/rclone #

```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
Box is pretty specific on refresh tokens.

https://rclone.org/box/#invalid-refresh-token

Did you use it already?

**Comment by Animosity022** [comment]
For future help, please post on the forums.

https://forum.rclone.org

**Comment by minnieshi** [comment]
> Box is pretty specific on refresh tokens.
> 
> 
> 
> https://rclone.org/box/#invalid-refresh-token
> 
> 
> 
> Did you use it already? 

Yes, I did; that info is provided in the description of the issue; see the expected section.

**Comment by minnieshi** [comment]
> Box is pretty specific on refresh tokens.
> 
> 
> 
> https://rclone.org/box/#invalid-refresh-token
> 
> 
> 
> Did you use it already? 

To be exact when I say yes I did, see description in the issue, I meant here: 

![image](https://github.com/rclone/rclone/assets/11322886/ce88e3ed-cc98-4e98-9373-ad7b2a35cf4d)

**Comment by minnieshi** [comment]
@Animosity022  please see my above 2 comments. should i move the discussion to the forum like your suggested or should we reopen this?
