### ISSUE TITLE
Official rclone Github Action?

### ISSUE THREAD

**Issue by DarioSoller** [rclone/rclone#7678]
#### What problem are you are trying to solve?
The reason why I am asking for an official rclone Github action is, because my organization only allows the usage of Github actions in our Github enterprise by [verified authors of the Github.com marketplace](https://github.com/marketplace?category=&type=actions&verification=verified_creator&copilot_app=&query=sort%3Apopularity-desc). So there are [some rclone Github actions already](https://github.com/marketplace?category=&type=actions&verification=&copilot_app=&query=sort%3Apopularity-desc+rclone), but unfortunately none of them have a [rclone Github action with a verified author](https://github.com/marketplace?category=&type=actions&verification=verified_creator&copilot_app=&query=sort%3Apopularity-desc+rclone) yet.

#### How do you think rclone should be changed to solve that?
So as this is the repo under the official rclone Github org, it seems to be the right place to ask for a rclone Github action by a verified author, as of according to [this and the subsequent GH forum posts](https://github.com/orgs/community/discussions/25265#discussioncomment-3247172) only organization can be verified as needed here at the moment.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
Thats sounds potentially neat. I'd suggest posting on the forums and see if it gets picked up by smoeone  as it does require I guess someone to review actions and see if someone wants to maintain them since they are other users.

There is a quite the backlog so dunno how feasible that is.

Thanks for the suggestion!
