### ISSUE TITLE
Chinese Colon Character causes character encoding error in rlone

### ISSUE THREAD

**Issue by hahach** [rclone/rclone#7682]
Bug Description: When processing files, (rclone move or other commands). the presence of a Chinese colon character (：) causes rclone to insert an additional apostrophe (') before the colon. 
This issue has been tested on OneDrive, and confirmed not to be a bug with OneDrive’s system.

like:
original file(dir) name:   123：223
when rclone transfer this file(dir) to OneDrive,  name will change to 123‛：223

rclone version:1.66.0   on debian

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by kapitainsky** [comment]
It is not a bug.

For Chinese please add below flag to your commands:

```
--onedrive-encoding Slash,LtGt,DoubleQuote,Asterisk,Pipe,BackSlash,LeftSpace,LeftCrLfHtVt,RightSpace,RightCrLfHtVt,InvalidUtf8,Dot
```

Here more details - https://rclone.org/overview/#encoding

If you have more questions please use https://forum.rclone.org/ instead of github.

**Comment by hahach** [comment]
> It is not a bug.
> 
> For Chinese please add below flag to your commands:
> 
> ```
> --onedrive-encoding Slash,LtGt,DoubleQuote,Asterisk,Pipe,BackSlash,LeftSpace,LeftCrLfHtVt,RightSpace,RightCrLfHtVt,InvalidUtf8,Dot
> ```
> 
> Here more details - https://rclone.org/overview/#encoding
> 
> If you have more questions please use https://forum.rclone.org/ instead of github.

It works！ Thank you！

**Comment by kapitainsky** [comment]
BTW - to avoid always using this rather complicated flag you can instead add it to your config file:

```
[onedrive-remote]
type = onedrive
client_id = XXX
client_secret = XXX
drive_id = XXX
drive_type = personal
token = XXX
encoding = Slash,LtGt,DoubleQuote,Asterisk,Pipe,BackSlash,LeftSpace,LeftCrLfHtVt,RightSpace,RightCrLfHtVt,InvalidUtf8,Dot
```

then it will be always applied when you use `onedrive-remote`

**Comment by hahach** [comment]
> BTW - to avoid always using this rather complicated flag you can instead add it to your config file:
> 
> ```
> [onedrive-remote-cjv-friendly]
> type = onedrive
> client_id = XXX
> client_secret = XXX
> drive_id = XXX
> drive_type = personal
> token = XXX
> encoding = Slash,LtGt,DoubleQuote,Asterisk,Pipe,BackSlash,LeftSpace,LeftCrLfHtVt,RightSpace,RightCrLfHtVt,InvalidUtf8,Dot
> ```
> 
> then it will be always applied when you use `onedrive-remote-cjv-friendly`
> 
> This custom encoding allows to store fullwidth `：` and `？` on onedrive unchanged but has one side affect - you won't be able to store files with halfwidth `:` or `?` in their names. And you can in Linux in local filesystem. But Onedrive does not allow it and this is what default encoding tries to mitigate by using fullwidth characters as substitutes. Unfortunately default is not well suited for Chinese or Japanese where fullwidth characters are widely used.


Great！ Thank you for your detailed and helpful solution！
