### ISSUE TITLE
recursive link generation with filtering

### ISSUE THREAD

**Issue by eadmaster** [rclone/rclone#7691]
#### The associated forum post URL from `https://forum.rclone.org`

- https://forum.rclone.org/t/recursively-share-folders-google/2197/2
- https://forum.rclone.org/t/how-can-i-get-multiple-links-from-folder-with-rclone/34444
- https://forum.rclone.org/t/rclone-link-multiple-files/35397/2

#### What is your current rclone version (output from `rclone version`)?

v1.66.0

#### What problem are you are trying to solve?

Recursively generate links for all the files inside a folder.

#### How do you think rclone should be changed to solve that?

add some extra flags to the [link command](https://rclone.org/commands/rclone_link/) for recursive link generation, mutuated from the [touch command](https://rclone.org/commands/rclone_touch/):
````
     -R, --recursive          Recursively link all files

# filtering options
      --exclude stringArray                 Exclude files matching pattern
      --exclude-from stringArray            Read file exclude patterns from file (use - to read from stdin)
      --exclude-if-present stringArray      Exclude directories if filename is present
      --files-from stringArray              Read list of source-file names from file (use - to read from stdin)
      --files-from-raw stringArray          Read list of source-file names from file without any processing of lines (use - to read from stdin)
  -f, --filter stringArray                  Add a file filtering rule
      --filter-from stringArray             Read file filtering patterns from a file (use - to read from stdin)
      --ignore-case                         Ignore case in filters (case insensitive)
      --include stringArray                 Include files matching pattern
      --include-from stringArray            Read file include patterns from file (use - to read from stdin)
      --max-age Duration                    Only transfer files younger than this in s or suffix ms|s|m|h|d|w|M|y (default off)
      --max-depth int                       If set limits the recursion depth to this (default -1)
      --max-size SizeSuffix                 Only transfer files smaller than this in KiB or suffix B|K|M|G|T|P (default off)
````

example usage
````
$ rclone link my_onedrive_remote:path/to/folder/  --recursive  --include '*.mp3'
my_file_1.mp3
https://sharepoint.com/.../_layouts/15/download.aspx?share=ERsW6A-9ShhCilI-PmuJ92ks78VV8I9iuu8o_CV6Tu23BA
my_file_2.mp3
https://sharepoint.com/.../_layouts/15/download.aspx?share=UCsW6A-9ShhCilI-PmuJ92ks78VV8I9iuu8o_CV6Tu23BA
my_file_3.mp3
https://sharepoint.com/.../_layouts/15/download.aspx?share=SWsW6A-9ShhCilI-PmuJ92ks78VV8I9iuu8o_CV6Tu23BA
...
````

related:

 - https://github.com/rclone/rclone/issues/3775

**Comment by eadmaster** [comment]
following [this forum post](https://forum.rclone.org/t/rclone-link-multiple-files/35397/2) I've came up with this bash function, but it is quite slow:
````
myonedrivefolder2m3u() {
	while read -r filename; do

		rclone link "my_onedrive:$1/$filename"
		
	done <<< "$(rclone lsf my_onedrive:$1 --include '*.mp3')"
}
`````

**Comment by ncw** [comment]
Your script will run a lot quicker if you start an `rclone rcd` server then use [rclone rc operations/publiclink](https://rclone.org/rc/#operations-publiclink) as rclone won't have the overhead of starting up the backend each time.

It would be fairly easy to add `-R` to `rclone publiclink` though - is this something you'd like to help with? I could provide hints?

**Comment by eadmaster** [comment]
ok, this seems to be much faster:
````
printf "#EXTM3U\r\n"

rclone rcd --rc-no-auth &

# alwars terminate the server when finished
trap "pkill -P $$" EXIT INT

myonedrivefolder2m3u() {
	
	while read -r filename; do
		printf "#EXTINF:-1,$filename\r\n"

		rclone rc operations/publiclink fs=my_onedrive: remote="$1/$filename" | jq -r .url | sed -e 's/$/\r/'
		
	done <<< "$(rclone lsf onedrive:$1 --include '*.mp3')"  
}

myonedrivefolder2m3u  folder/to/share/recursively

````

**Comment by ncw** [comment]
> ok, this seems to be much faster:

nice!

> what is the preferred way to demonize and kill `rclone rcd` in the background? (i will be running this script only in interactive shells, so i need to catch Ctrl+C to abort)

`rclone rcd` doesn't have a `--daemon` flag like `rclone mount`. 

You can ask `rclone rcd` to stop with the [core/quit](https://rclone.org/rc/#core-quit) command.
