### ISSUE TITLE
Can not add a custom header when uploading a large file to Backblaze

### ISSUE THREAD

**Issue by thoongnv** [rclone/rclone#7698]
#### What is the problem you are having with rclone?
Can not add a custom header when uploading a large file (my test `tempfile` ~10Gb), small file is fine.
I tried to list headers with curl command but not found `x-bz-info-uncompressed-size` header

```
curl --head https://f001.backblazeb2.com/b2api/v1/b2_download_file_by_id\?fileId\=file-id
```

#### What is your rclone version (output from `rclone version`)
```
rclone v1.53.3-DEV
- os/arch: linux/amd64
- go version: go1.15.9
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Debian GNU/Linux 11 (bullseye)

#### Which cloud storage system are you using? (e.g. Google Drive)

Backblaze

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone --config rclone.conf -vv --header-upload "x-bz-info-uncompressed-size: 1000000" copy /export/tempfile b2:my-bucket

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

2024/03/28 02:59:17 DEBUG : Creating backend with remote "/export/tempfile"
2024/03/28 02:59:17 DEBUG : Using config file from "/app/rclone.conf"
2024/03/28 02:59:17 DEBUG : fs cache: adding new entry for parent of "/export/tempfile", "/export"
2024/03/28 02:59:17 DEBUG : Creating backend with remote "b2:my-bucket"
2024/03/28 02:59:17 DEBUG : tempfile: Need to transfer - File not found at Destination
2024/03/28 03:00:17 INFO  :
Transferred:   	         0 / 10 GBytes, 0%, 0 Bytes/s, ETA -
Transferred:            0 / 1, 0%
Elapsed time:       1m0.1s
Transferring:
 *                                      tempfile:  0% /10G, 0/s, -

2024/03/28 03:00:30 DEBUG : tempfile: Starting upload of large file in 107 chunks (id "4_zd3651c775aff36c062d90a15_f20282400e9f4b9c6_d20240328_m030030_c001_v0001103_t0050_u017115948xxxxx")
2024/03/28 03:00:31 DEBUG : tempfile: Sending chunk 1 length 100663296
2024/03/28 03:00:31 DEBUG : tempfile: Sending chunk 2 length 100663296
2024/03/28 03:00:32 DEBUG : tempfile: Sending chunk 3 length 100663296
2024/03/28 03:00:32 DEBUG : tempfile: Sending chunk 4 length 100663296
2024/03/28 03:00:34 DEBUG : tempfile: Done sending chunk 3
2024/03/28 03:00:34 DEBUG : tempfile: Sending chunk 5 length 100663296
2024/03/28 03:00:35 DEBUG : tempfile: Done sending chunk 2
2024/03/28 03:00:35 DEBUG : tempfile: Done sending chunk 1
2024/03/28 03:00:36 DEBUG : tempfile: Sending chunk 6 length 100663296
2024/03/28 03:00:36 DEBUG : tempfile: Done sending chunk 4
2024/03/28 03:00:36 DEBUG : tempfile: Sending chunk 7 length 100663296
2024/03/28 03:00:37 DEBUG : tempfile: Done sending chunk 5
2024/03/28 03:00:37 DEBUG : tempfile: Sending chunk 8 length 100663296
2024/03/28 03:00:37 DEBUG : tempfile: Sending chunk 9 length 100663296
2024/03/28 03:00:38 DEBUG : tempfile: Done sending chunk 6
2024/03/28 03:00:38 DEBUG : tempfile: Done sending chunk 8
2024/03/28 03:00:38 DEBUG : tempfile: Sending chunk 10 length 100663296
2024/03/28 03:00:38 DEBUG : tempfile: Done sending chunk 7
2024/03/28 03:00:39 DEBUG : tempfile: Done sending chunk 9
2024/03/28 03:00:39 DEBUG : tempfile: Sending chunk 11 length 100663296
2024/03/28 03:00:39 DEBUG : tempfile: Sending chunk 12 length 100663296
2024/03/28 03:00:40 DEBUG : tempfile: Sending chunk 13 length 100663296
2024/03/28 03:00:40 DEBUG : tempfile: Done sending chunk 10
2024/03/28 03:00:41 DEBUG : tempfile: Done sending chunk 11
2024/03/28 03:00:41 DEBUG : tempfile: Sending chunk 14 length 100663296
2024/03/28 03:00:41 DEBUG : tempfile: Sending chunk 15 length 100663296
2024/03/28 03:00:42 DEBUG : tempfile: Done sending chunk 12
2024/03/28 03:00:43 DEBUG : tempfile: Done sending chunk 13
2024/03/28 03:00:43 DEBUG : tempfile: Sending chunk 16 length 100663296
2024/03/28 03:00:43 DEBUG : tempfile: Done sending chunk 15
2024/03/28 03:00:43 DEBUG : tempfile: Sending chunk 17 length 100663296
2024/03/28 03:00:44 DEBUG : tempfile: Sending chunk 18 length 100663296
2024/03/28 03:00:45 DEBUG : tempfile: Done sending chunk 14
2024/03/28 03:00:45 DEBUG : tempfile: Sending chunk 19 length 100663296
2024/03/28 03:00:45 DEBUG : tempfile: Done sending chunk 17
2024/03/28 03:00:46 DEBUG : tempfile: Sending chunk 20 length 100663296
2024/03/28 03:00:46 DEBUG : tempfile: Done sending chunk 18
2024/03/28 03:00:46 DEBUG : tempfile: Sending chunk 21 length 100663296
2024/03/28 03:00:47 DEBUG : tempfile: Done sending chunk 19
2024/03/28 03:00:47 DEBUG : tempfile: Sending chunk 22 length 100663296
2024/03/28 03:00:49 DEBUG : tempfile: Done sending chunk 16
2024/03/28 03:00:49 DEBUG : tempfile: Done sending chunk 21
2024/03/28 03:00:49 DEBUG : tempfile: Done sending chunk 22
2024/03/28 03:00:49 DEBUG : tempfile: Sending chunk 23 length 100663296
2024/03/28 03:00:49 DEBUG : tempfile: Done sending chunk 20
2024/03/28 03:00:49 DEBUG : tempfile: Sending chunk 24 length 100663296
2024/03/28 03:00:50 DEBUG : tempfile: Sending chunk 25 length 100663296
2024/03/28 03:00:50 DEBUG : tempfile: Sending chunk 26 length 100663296
2024/03/28 03:00:51 DEBUG : tempfile: Done sending chunk 24
2024/03/28 03:00:51 DEBUG : tempfile: Done sending chunk 23
2024/03/28 03:00:52 DEBUG : tempfile: Sending chunk 27 length 100663296
2024/03/28 03:00:52 DEBUG : tempfile: Done sending chunk 25
2024/03/28 03:00:52 DEBUG : tempfile: Sending chunk 28 length 100663296
2024/03/28 03:00:53 DEBUG : tempfile: Sending chunk 29 length 100663296
2024/03/28 03:00:53 DEBUG : tempfile: Done sending chunk 27
2024/03/28 03:00:53 DEBUG : tempfile: Sending chunk 30 length 100663296
2024/03/28 03:00:54 DEBUG : tempfile: Done sending chunk 26
2024/03/28 03:00:54 DEBUG : tempfile: Done sending chunk 28
2024/03/28 03:00:54 DEBUG : tempfile: Sending chunk 31 length 100663296
2024/03/28 03:00:55 DEBUG : tempfile: Done sending chunk 30
2024/03/28 03:00:55 DEBUG : tempfile: Sending chunk 32 length 100663296
2024/03/28 03:00:55 DEBUG : tempfile: Sending chunk 33 length 100663296
2024/03/28 03:00:56 DEBUG : tempfile: Done sending chunk 31
2024/03/28 03:00:56 DEBUG : tempfile: Done sending chunk 29
2024/03/28 03:00:56 DEBUG : tempfile: Sending chunk 34 length 100663296
2024/03/28 03:00:57 DEBUG : tempfile: Sending chunk 35 length 100663296
2024/03/28 03:00:57 DEBUG : tempfile: Done sending chunk 32
2024/03/28 03:00:57 DEBUG : tempfile: Sending chunk 36 length 100663296
2024/03/28 03:00:58 DEBUG : tempfile: Done sending chunk 34
2024/03/28 03:00:59 DEBUG : tempfile: Sending chunk 37 length 100663296
2024/03/28 03:00:59 DEBUG : tempfile: Done sending chunk 33
2024/03/28 03:01:00 DEBUG : tempfile: Sending chunk 38 length 100663296
2024/03/28 03:01:00 DEBUG : tempfile: Done sending chunk 36
2024/03/28 03:01:01 DEBUG : tempfile: Done sending chunk 37
2024/03/28 03:01:01 DEBUG : tempfile: Done sending chunk 35
2024/03/28 03:01:01 DEBUG : tempfile: Done sending chunk 38
2024/03/28 03:01:01 DEBUG : tempfile: Sending chunk 39 length 100663296
2024/03/28 03:01:03 DEBUG : tempfile: Sending chunk 40 length 100663296
2024/03/28 03:01:04 DEBUG : tempfile: Sending chunk 41 length 100663296
2024/03/28 03:01:04 DEBUG : tempfile: Done sending chunk 39
2024/03/28 03:01:04 DEBUG : tempfile: Sending chunk 42 length 100663296
2024/03/28 03:01:05 DEBUG : tempfile: Sending chunk 43 length 100663296
2024/03/28 03:01:06 DEBUG : tempfile: Done sending chunk 41
2024/03/28 03:01:07 DEBUG : tempfile: Done sending chunk 42
2024/03/28 03:01:07 DEBUG : tempfile: Sending chunk 44 length 100663296
2024/03/28 03:01:07 DEBUG : tempfile: Sending chunk 45 length 100663296
2024/03/28 03:01:09 DEBUG : tempfile: Done sending chunk 43
2024/03/28 03:01:09 DEBUG : tempfile: Sending chunk 46 length 100663296
2024/03/28 03:01:09 DEBUG : tempfile: Done sending chunk 40
2024/03/28 03:01:10 DEBUG : tempfile: Sending chunk 47 length 100663296
2024/03/28 03:01:11 DEBUG : tempfile: Done sending chunk 44
2024/03/28 03:01:11 DEBUG : tempfile: Done sending chunk 47
2024/03/28 03:01:12 DEBUG : tempfile: Sending chunk 48 length 100663296
2024/03/28 03:01:12 DEBUG : tempfile: Sending chunk 49 length 100663296
2024/03/28 03:01:14 DEBUG : tempfile: Done sending chunk 49
2024/03/28 03:01:14 DEBUG : tempfile: Sending chunk 50 length 100663296
2024/03/28 03:01:15 DEBUG : tempfile: Done sending chunk 48
2024/03/28 03:01:15 DEBUG : tempfile: Sending chunk 51 length 100663296
2024/03/28 03:01:16 DEBUG : tempfile: Done sending chunk 50
2024/03/28 03:01:16 DEBUG : tempfile: Sending chunk 52 length 100663296
2024/03/28 03:01:16 DEBUG : tempfile: Done sending chunk 46
2024/03/28 03:01:17 DEBUG : tempfile: Sending chunk 53 length 100663296
2024/03/28 03:01:17 INFO  :
Transferred:   	    4.724G / 10 GBytes, 47%, 40.333 MBytes/s, ETA 2m13s
Transferred:            0 / 1, 0%
Elapsed time:       2m0.1s
Transferring:
 *                                      tempfile: 47% /10G, 91.027M/s, 59s

2024/03/28 03:01:18 DEBUG : tempfile: Done sending chunk 53
2024/03/28 03:01:18 DEBUG : tempfile: Done sending chunk 45
2024/03/28 03:01:19 DEBUG : tempfile: Sending chunk 54 length 100663296
2024/03/28 03:01:19 DEBUG : tempfile: Sending chunk 55 length 100663296
2024/03/28 03:01:20 DEBUG : tempfile: Done sending chunk 52
2024/03/28 03:01:20 DEBUG : tempfile: Done sending chunk 54
2024/03/28 03:01:20 DEBUG : tempfile: Sending chunk 56 length 100663296
2024/03/28 03:01:21 DEBUG : tempfile: Done sending chunk 51
2024/03/28 03:01:21 DEBUG : tempfile: Sending chunk 57 length 100663296
2024/03/28 03:01:21 DEBUG : tempfile: Sending chunk 58 length 100663296
2024/03/28 03:01:24 DEBUG : tempfile: Done sending chunk 58
2024/03/28 03:01:24 DEBUG : tempfile: Done sending chunk 56
2024/03/28 03:01:24 DEBUG : tempfile: Sending chunk 59 length 100663296
2024/03/28 03:01:24 DEBUG : tempfile: Done sending chunk 57
2024/03/28 03:01:24 DEBUG : tempfile: Done sending chunk 55
2024/03/28 03:01:25 DEBUG : tempfile: Sending chunk 60 length 100663296
2024/03/28 03:01:25 DEBUG : tempfile: Sending chunk 61 length 100663296
2024/03/28 03:01:26 DEBUG : tempfile: Done sending chunk 59
2024/03/28 03:01:26 DEBUG : tempfile: Sending chunk 62 length 100663296
2024/03/28 03:01:27 DEBUG : tempfile: Sending chunk 63 length 100663296
2024/03/28 03:01:27 DEBUG : tempfile: Done sending chunk 60
2024/03/28 03:01:27 DEBUG : tempfile: Sending chunk 64 length 100663296
2024/03/28 03:01:28 DEBUG : tempfile: Done sending chunk 62
2024/03/28 03:01:28 DEBUG : tempfile: Sending chunk 65 length 100663296
2024/03/28 03:01:28 DEBUG : tempfile: Done sending chunk 61
2024/03/28 03:01:29 DEBUG : tempfile: Sending chunk 66 length 100663296
2024/03/28 03:01:29 DEBUG : tempfile: Done sending chunk 64
2024/03/28 03:01:29 DEBUG : tempfile: Sending chunk 67 length 100663296
2024/03/28 03:01:30 DEBUG : tempfile: Done sending chunk 63
2024/03/28 03:01:30 DEBUG : tempfile: Done sending chunk 65
2024/03/28 03:01:30 DEBUG : tempfile: Sending chunk 68 length 100663296
2024/03/28 03:01:31 DEBUG : tempfile: Sending chunk 69 length 100663296
2024/03/28 03:01:31 DEBUG : tempfile: Done sending chunk 67
2024/03/28 03:01:31 DEBUG : tempfile: Sending chunk 70 length 100663296
2024/03/28 03:01:32 DEBUG : tempfile: Done sending chunk 66
2024/03/28 03:01:32 DEBUG : tempfile: Sending chunk 71 length 100663296
2024/03/28 03:01:33 DEBUG : tempfile: Done sending chunk 68
2024/03/28 03:01:33 DEBUG : tempfile: Done sending chunk 69
2024/03/28 03:01:33 DEBUG : tempfile: Sending chunk 72 length 100663296
2024/03/28 03:01:33 DEBUG : tempfile: Sending chunk 73 length 100663296
2024/03/28 03:01:35 DEBUG : tempfile: Done sending chunk 70
2024/03/28 03:01:35 DEBUG : tempfile: Done sending chunk 71
2024/03/28 03:01:35 DEBUG : tempfile: Sending chunk 74 length 100663296
2024/03/28 03:01:36 DEBUG : tempfile: Sending chunk 75 length 100663296
2024/03/28 03:01:36 DEBUG : tempfile: Done sending chunk 73
2024/03/28 03:01:36 DEBUG : tempfile: Sending chunk 76 length 100663296
2024/03/28 03:01:37 DEBUG : tempfile: Done sending chunk 72
2024/03/28 03:01:38 DEBUG : tempfile: Sending chunk 77 length 100663296
2024/03/28 03:01:38 DEBUG : tempfile: Done sending chunk 75
2024/03/28 03:01:38 DEBUG : tempfile: Sending chunk 78 length 100663296
2024/03/28 03:01:39 DEBUG : tempfile: Done sending chunk 74
2024/03/28 03:01:40 DEBUG : tempfile: Sending chunk 79 length 100663296
2024/03/28 03:01:41 DEBUG : tempfile: Done sending chunk 76
2024/03/28 03:01:41 DEBUG : tempfile: Sending chunk 80 length 100663296
2024/03/28 03:01:42 DEBUG : tempfile: Done sending chunk 79
2024/03/28 03:01:42 DEBUG : tempfile: Sending chunk 81 length 100663296
2024/03/28 03:01:44 DEBUG : tempfile: Done sending chunk 80
2024/03/28 03:01:44 DEBUG : tempfile: Done sending chunk 78
2024/03/28 03:01:44 DEBUG : tempfile: Sending chunk 82 length 100663296
2024/03/28 03:01:45 DEBUG : tempfile: Sending chunk 83 length 100663296
2024/03/28 03:01:46 DEBUG : tempfile: Done sending chunk 82
2024/03/28 03:01:46 DEBUG : tempfile: Done sending chunk 81
2024/03/28 03:01:46 DEBUG : tempfile: Sending chunk 84 length 100663296
2024/03/28 03:01:47 DEBUG : tempfile: Done sending chunk 77
2024/03/28 03:01:47 DEBUG : tempfile: Sending chunk 85 length 100663296
2024/03/28 03:01:48 DEBUG : tempfile: Sending chunk 86 length 100663296
2024/03/28 03:01:49 DEBUG : tempfile: Done sending chunk 84
2024/03/28 03:01:49 DEBUG : tempfile: Sending chunk 87 length 100663296
2024/03/28 03:01:49 DEBUG : tempfile: Done sending chunk 86
2024/03/28 03:01:50 DEBUG : tempfile: Sending chunk 88 length 100663296
2024/03/28 03:01:50 DEBUG : tempfile: Done sending chunk 85
2024/03/28 03:01:51 DEBUG : tempfile: Sending chunk 89 length 100663296
2024/03/28 03:01:52 DEBUG : tempfile: Done sending chunk 87
2024/03/28 03:01:52 DEBUG : tempfile: Sending chunk 90 length 100663296
2024/03/28 03:01:53 DEBUG : tempfile: Done sending chunk 89
2024/03/28 03:01:53 DEBUG : tempfile: Done sending chunk 88
2024/03/28 03:01:53 DEBUG : tempfile: Sending chunk 91 length 100663296
2024/03/28 03:01:54 DEBUG : tempfile: Sending chunk 92 length 100663296
2024/03/28 03:01:55 DEBUG : tempfile: Done sending chunk 90
2024/03/28 03:01:56 DEBUG : tempfile: Sending chunk 93 length 100663296
2024/03/28 03:01:56 DEBUG : tempfile: Done sending chunk 91
2024/03/28 03:01:57 DEBUG : tempfile: Sending chunk 94 length 100663296
2024/03/28 03:01:57 DEBUG : tempfile: Done sending chunk 93
2024/03/28 03:01:58 DEBUG : tempfile: Sending chunk 95 length 100663296
2024/03/28 03:01:58 DEBUG : tempfile: Done sending chunk 92
2024/03/28 03:01:58 DEBUG : tempfile: Sending chunk 96 length 100663296
2024/03/28 03:01:59 DEBUG : tempfile: Error sending chunk 83 (retry=true): incident id 8fed412eace4-b946994be1f17ba5 (500 internal_error): &api.Error{Status:500, Code:"internal_error", Message:"incident id 8fed412eace4-b946994be1f17ba5"}
2024/03/28 03:01:59 DEBUG : tempfile: Clearing part upload URL because of error: incident id 8fed412eace4-b946994be1f17ba5 (500 internal_error)
2024/03/28 03:01:59 DEBUG : pacer: low level retry 1/10 (error incident id 8fed412eace4-b946994be1f17ba5 (500 internal_error))
2024/03/28 03:01:59 DEBUG : pacer: Rate limited, increasing sleep to 20ms
2024/03/28 03:01:59 DEBUG : tempfile: Sending chunk 83 length 100663296
2024/03/28 03:01:59 DEBUG : pacer: Reducing sleep to 10ms
2024/03/28 03:02:01 DEBUG : tempfile: Done sending chunk 95
2024/03/28 03:02:01 DEBUG : tempfile: Done sending chunk 96
2024/03/28 03:02:01 DEBUG : tempfile: Done sending chunk 83
2024/03/28 03:02:02 DEBUG : tempfile: Sending chunk 97 length 100663296
2024/03/28 03:02:03 DEBUG : tempfile: Sending chunk 98 length 100663296
2024/03/28 03:02:04 DEBUG : tempfile: Sending chunk 99 length 100663296
2024/03/28 03:02:04 DEBUG : tempfile: Done sending chunk 94
2024/03/28 03:02:04 DEBUG : tempfile: Sending chunk 100 length 100663296
2024/03/28 03:02:05 DEBUG : tempfile: Done sending chunk 99
2024/03/28 03:02:05 DEBUG : tempfile: Done sending chunk 98
2024/03/28 03:02:06 DEBUG : tempfile: Sending chunk 101 length 100663296
2024/03/28 03:02:06 DEBUG : tempfile: Done sending chunk 97
2024/03/28 03:02:06 DEBUG : tempfile: Sending chunk 102 length 100663296
2024/03/28 03:02:07 DEBUG : tempfile: Sending chunk 103 length 100663296
2024/03/28 03:02:09 DEBUG : tempfile: Done sending chunk 102
2024/03/28 03:02:09 DEBUG : tempfile: Done sending chunk 100
2024/03/28 03:02:10 DEBUG : tempfile: Sending chunk 104 length 100663296
2024/03/28 03:02:10 DEBUG : tempfile: Sending chunk 105 length 100663296
2024/03/28 03:02:11 DEBUG : tempfile: Done sending chunk 103
2024/03/28 03:02:11 DEBUG : tempfile: Done sending chunk 101
2024/03/28 03:02:11 DEBUG : tempfile: Sending chunk 106 length 100663296
2024/03/28 03:02:12 DEBUG : tempfile: Sending chunk 107 length 67108864
2024/03/28 03:02:12 DEBUG : tempfile: Done sending chunk 105
2024/03/28 03:02:13 DEBUG : tempfile: Done sending chunk 106
2024/03/28 03:02:14 DEBUG : tempfile: Done sending chunk 107
2024/03/28 03:02:14 DEBUG : tempfile: Done sending chunk 104
2024/03/28 03:02:14 DEBUG : tempfile: Finishing large file upload with 107 parts
2024/03/28 03:02:14 DEBUG : tempfile: SHA-1 = a0b6e2ca4e28360a929943e8eb966f703a69dc44 OK
2024/03/28 03:02:14 INFO  : tempfile: Copied (new)
2024/03/28 03:02:14 INFO  :
Transferred:   	   10.094G / 10.094 GBytes, 100%, 58.338 MBytes/s, ETA 0s
Transferred:            1 / 1, 100%
Elapsed time:      2m57.3s

2024/03/28 03:02:14 DEBUG : 14 go routines active

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
You have a mega old version.

Update and use the forums for support first please.

https://forum.rclone.org
