### ISSUE TITLE
split in rclone?

### ISSUE THREAD

**Issue by lucasnuic** [rclone/rclone#7732]
#### The associated forum post URL from `https://forum.rclone.org`
None.

#### What is your current rclone version (output from `rclone version`)?
rclone v1.66.0

#### What problem are you are trying to solve?
For example, I split the keepass.db file into 3 files and then I added a folder to each one. After that, I used rclone to privately synchronize each file in each folder in a different cloud. After that, I thought if there was automation. As I couldn't find it, I based it on the existing project and just added little more than 10 or 20 lines for what I needed.

What problem are you are trying to solve?
 - Synchronization between a cloud service and a KeePass database(and split KeePass database in cloud services for security, privacy). What if each part of the file is in a different location.  
 - Suppose that I split the file KeePass.kbdx into file. I leave the first part on Google Drive, the second on Dropbox, and the third on Media Fire? How could I synchronize each part of the file individually? Is it possible to synchronize file parts in different places?

#### How do you think rclone should be changed to solve that?
1. There is no program that does this, I created software for this. However, I think this should be included in the core of the rclone project as it is something relevant. See this: [lucasnuic/krsp](https://github.com/lucasnuic/krsp): *"synchronization between a cloud service and a KeePass database(and split KeePass database in cloud services for security, privacy)"*  - I customized the rclone command line with splitch for this. is in beta phase. It might not be complicated to add it as a separate thing without remaining in the core of the project as a post-installation script.
2. The other option would be to add it to the project core, which would include a new command line. I could rewrite it and include it there, but in this case I would like to know what you think of the idea, and whether it is good or bad.
3. The [keepass community recommended ](https://github.com/keepassxreboot/keepassxc/discussions/10539) me to talk to you all rather than do a separate project. Does what I said make sense?

**Comment by ncw** [comment]
This method of splitting a file is dependent on everything working (all the cloud providers) to recover the data.

I'd probably recommend something more like this https://github.com/jesseduffield/horcrux where you don't need every copy of the data to reconstruct the original.

You could use that in a simple script - `horcrux split` then `rclone copy` for each part to the remote backends. The recovery script would do the opposite, rclone copy to retreive the parts and then `horcrux bind` to join them back together.

Ideally rclone would have a horcrux backend where you could say, split my data over these N providers in such a way that the data isn't recoverable unless you have M (<=N) parts.

There have been issues about [erasure encoded backends](https://github.com/rclone/rclone/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20erasure) which are a similar idea but not encrypted - so more like your current scheme but with redundancy.

PS I sync my keepass file to Google Drive then I can use it with KeepassXC on my computer and Keepasss2Android on my phone. The keepass file is protected with a very strong password, however Keepass2Android can store it in the secure enclave on the phone so you can unlock it with your finger print. All very convenient!

**Comment by lucasnuic** [comment]
Hi @ncw 

Thank you for your kind words. 🙂

> This method of splitting a file is dependent on everything working (all the cloud providers) to recover the data.

yes.

> I'd probably recommend something more like this https://github.com/jesseduffield/horcrux where you don't need every copy of the data to reconstruct the original.
> You could use that in a simple script - horcrux split then rclone copy for each part to the remote backends. The recovery script would do the opposite, rclone copy to retreive the parts and then horcrux bind to join them back together.
> Ideally rclone would have a horcrux backend where you could say, split my data over these N providers in such a way that the data isn't recoverable unless you have M (<=N) parts.
> There have been issues about [erasure encoded backends](https://github.com/rclone/rclone/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20erasure) which are a similar idea but not encrypted - so more like your current scheme but with redundancy.

yes.

> PS I sync my keepass file to Google Drive then I can use it with KeepassXC on my computer and Keepasss2Android on my phone. The keepass file is protected with a very strong password, however Keepass2Android can store it in the secure enclave on the phone so you can unlock it with your finger print. All very convenient!

yes.

**Comment by lucasnuic** [comment]
@ncw I left the my code public, I don't intend to implement it for now for the good reasons you mentioned. But I learned a lot and I'm grateful for the opportunity to improve.
