### ISSUE TITLE
Upgrade to Go 1.22 to avoid scoping bugs with closures in for loops?

### ISSUE THREAD

**Issue by dmcardle** [rclone/rclone#7758]
#### The associated forum post URL from `https://forum.rclone.org`

N/a

#### What is the problem you are having with rclone?

Version of Go prior to 1.22 contain a footgun related to closures in for loops: https://go.dev/blog/loopvar-preview

*[Release notes for Go 1.22](https://tip.golang.org/doc/go1.22)*

I've run into this twice so far:

* https://github.com/rclone/rclone/pull/7754#issuecomment-2050406021

* https://github.com/rclone/rclone/blob/2c7680050bb189efe1770f77585527619197b596/cmd/gitannex/gitannex_test.go#L865-L868

#### What is your rclone version (output from `rclone version`)

HEAD, currently 2c7680050bb189efe1770f77585527619197b596

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

N/a, the language semantics are cross-platform

#### Which cloud storage system are you using? (e.g. Google Drive)

N/a

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

N/a

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

N/a

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
1.66 already has Go 1.22

https://forum.rclone.org/t/rclone-v1-66-release/44987

**Comment by dmcardle** [comment]
Oh, I was going based on the go.mod file, which still says `1.20`.

https://github.com/rclone/rclone/blob/2c7680050bb189efe1770f77585527619197b596/go.mod#L3

**Comment by dmcardle** [comment]
Aha, I guess the minimum version is still 1.20, and the CI still tests go1.20. Nothing to do here. Thanks, @Animosity022!

**Comment by ncw** [comment]
@dmcardle we try to support current go and two previous versions, so currently that is go1.22, go1.21, go1.20.

However in two go versions time that support will look like go1.24, go1.23, go1.22 so at that point we can remove those unnecessary lines of code so you can re-open that issue then if you want!

Eg this (might not be all of them if we renamed the var too).

```
$ git grep -P '\b(\w+) := \1(\s|$)'
backend/azureblob/azureblob.go:         v := v
backend/b2/upload.go:           part := part // for the closure
backend/b2/upload.go:           part := part // for the closure
backend/combine/combine.go:             upstream := upstream
backend/combine/combine.go:             u := u
backend/combine/combine.go:             u := u
backend/drive/metadata.go:                              permissionID := permissionID
backend/s3/s3.go:               partNum := partNum // for closure
backend/union/policy/epff.go:           u := u // Closure
backend/union/union.go:         i := i
cmd/gitannex/gitannex_test.go:                          lineEnding := lineEnding
cmd/gitannex/gitannex_test.go:          testCase := testCase
cmd/gitannex/gitannex_test.go:          testCase := testCase
fs/config/rc.go:                name := name
fs/operations/multithread.go:           chunk := chunk
fs/operations/operations.go:                    dir := dir
fs/operations/rc.go:            copy := copy
fs/operations/rc.go:            op := op
fs/sync/rc.go:          name := name
fs/sync/sync.go:                        item := item
lib/encoder/filename/encode.go:         org := org
lib/multipart/multipart.go:             partNum := partNum
```
