### ISSUE TITLE
mailru: change default pacer to reduce transactions per second

### ISSUE THREAD

**Issue by sharicov** [rclone/rclone#7768]
lsd working properly, but then, when running copy from mailru to local disk following error starts popping:

ERROR : : error listing: invalid character '<' looking for beginning of value

copy crashes and then even lsd command not working

rclone version  v1.66.0

rclone v1.66.0
- os/version: debian 12.5 (64 bit)
- os/kernel: 6.1.86-ophub (aarch64)
- os/type: linux
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.22.1
- go/linking: static
- go/tags: none
Was working previously.
Tried to reconfigure, created new mail.ru token, doesn't help.

**Comment by ncw** [comment]
> ERROR : : error listing: invalid character '<' looking for beginning of value

This is almost certainly the server returning an error in HTML.

If you run with `-vv --dump responses` then you'll see the HTML in the log which might give a clue.

**Comment by strpc** [comment]
same error

**Comment by nielash** [comment]
It is also reproducible on the `TestChunkerMailru:` integration tests:

https://pub.rclone.org/integration-tests/2024-04-15-010011/chunker-backend.chunker-TestChunkerMailru-5.txt
https://pub.rclone.org/integration-tests/2024-04-15-010011/chunker-cmd.bisync-TestChunkerMailru-5.txt

**Comment by ncw** [comment]
I tried re-running those tests with `-dump-bodies` but they worked fine this time.

I suspect it is the server getting overloaded - something we need to retry maybe.

If we can get a log with `-vv --dump responses` that would help a lot.

**Comment by ncw** [comment]
In there is the answer...


> У вас большие запросы!
> Точнее, от вашего браузера их поступает слишком много, и сервер VK забил тревогу.
> 
> Нужно включить JavaScript, чтобы исправить проблему.
> 
> Эта страница была загружена по HTTP, вместо безопасного HTTPS, а значит телепортации обратно не будет.
> Обратитесь в поддержку сервиса.
> 
> Вы отключили сохранение Cookies, а они нужны, чтобы решить проблему.
> 
> Почему-то страница не получила всех данных, а без них она не работает.
> Обратитесь в поддержку сервиса.
> 
> Вы вернётесь на предыдущую страницу через 5 секунд.

Badly translated by Google

> You have big requests! More precisely, there are too many of them coming from your browser, and the VK server has sounded the alarm. You need to enable JavaScript to fix the problem. This page was loaded via HTTP, instead of secure HTTPS, which means there will be no teleportation back. Contact service support. You have disabled cookies, but they are needed to solve the problem. For some reason, the page did not receive all the data, and without it it does not work. Contact service support. You will return to the previous page in 5 seconds.

So the server is overloaded or we are hitting it too hard... Try slowing your requests down with `--tpslimit 10` - if that doesn't work, decrease the number, eg `--tpslimit 5` and if it does work try larger, eg `--tpslimit 20`.

**Comment by strpc** [comment]
> `--tpslimit 10`

thats worked. thanks!

**Comment by ncw** [comment]
I think we should probably adjust the default pacer here

https://github.com/rclone/rclone/blob/6a0a54ab97a5aabadf0444497629a8254dc4df3f/backend/mailru/mailru.go#L49

I need someone to experiment with it and find the best value. Using `--tpslimit 10` is equivalent to setting 100 mS - it might be there is a better value.

**Comment by cherjr** [comment]
Same problem here: err302, and even --tpslimit 1 doesn't resolve it...

**Comment by ncw** [comment]
I will set the default throttle to 100ms and push that to the beta to see if the integration tests pass shortly.

**Comment by ncw** [comment]
That seemed to work - the integrations tests passed :-)

So I'm going to close this.

This will be released in v1.67 or is in [the latest beta](https://beta.rclone.org/) now

**Comment by sharicov** [comment]
Same issue again, running v1.68
