### ISSUE TITLE
Google Drive: Rclone rewrites custom-set description on file rename in mounted drive

### ISSUE THREAD

**Issue by FurloSK** [rclone/rclone#7770]
#### What is the problem you are having with rclone?
I am using latest Rclone and having Google Drive mounted as a local drive. **_When I rename any file which has a custom description_** (by `custom` I mean `having a description different from its file name`) set in Google Drive web interface, **_the description is overridden by Rclone to the new file name._** Thus, the custom description is lost.

#### How do you think rclone should be changed to solve that?
I think the expected behavior is that Rclone should rewrite the file description to new file name only when the original description fits the original file name (or, possibly, when the description is empty). Otherwise **_the description should be honored, since it is custom-set by the user_** (this is _certainly_ the case when the description text is something completely arbitrary, and _might_ be the case when the description is empty).

Examples of expected behavior when renaming file `hello.txt` to `hello new.txt`:
* `hello.txt` with description: "" (empty) ⇒ `hello new.txt` with description: "" [empty] **_OR_** "hello new.txt"
* `hello.txt` with description: "hello.txt" ⇒ `hello new.txt` with description: "hello new.txt"
* `hello.txt` with description: "NOTE: important!" ⇒ `hello new.txt` with description: "NOTE: important!"

This _might_ be somehow related to issue #4230 – but I am not sure, since the mentioned issue is about _copying_ files, not just _renaming_ them, and the issue I am facing is when the drive is mounted.

#### What is your rclone version (output from `rclone version`)
rclone v1.66.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
macOS Ventura 13.6.6 (same effect with macOS Mojave 10.14.6)

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
We've been discussing this issue on the forum

https://forum.rclone.org/t/file-descriptions-in-google-drive-not-shown-after-dedupe/45510

Try this fix

[v1.67.0-beta.7876.91de00f94.drive-description](https://beta.rclone.org/branch/drive-description/v1.67.0-beta.7876.91de00f94.drive-description/) on branch [drive-description](https://github.com/rclone/rclone/tree/drive-description) (uploaded in 15-30 mins)

**Comment by FurloSK** [comment]
> We've been discussing this issue on the forum
> 
> https://forum.rclone.org/t/file-descriptions-in-google-drive-not-shown-after-dedupe/45510
> 
> Try this fix
> 
> [v1.67.0-beta.7876.91de00f94.drive-description](https://beta.rclone.org/branch/drive-description/v1.67.0-beta.7876.91de00f94.drive-description/) on branch [drive-description](https://github.com/rclone/rclone/tree/drive-description) (uploaded in 15-30 mins)

This works for me – that is, **it completely disables rClone's writing of description** (whether uploading a new file or cloning an existing file with description). Is this the expected behaviour?

If yes, is this already planned to be merged to 1.67 (i.e. will it suffice for me to wait until official 1.67 release and then update rClone on my productive environment)?

**Comment by ncw** [comment]
Yes this disables rclone setting descriptions completely. I don't know why it ever did that and it isn't useful. This means users can set their own descriptions and rclone won't modify them.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.67
