### ISSUE TITLE
Support Permanent delete in OneDrive/Sharepoint

### ISSUE THREAD

**Issue by jcastilloalonso** [rclone/rclone#7812]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/support-permanent-delete-in-onedrive-sharepoint/45944

#### What is your current rclone version (output from `rclone version`)?

1.66

#### What problem are you are trying to solve?

OneDrive for Business does count deleted items vs the account quota. After migrating my offsite backup to OneDrive, I now have to manually login to the account and empty the recycle bin from time to time, as uploading a replacement new backup revision will result in the old file being moved to recycle bin as rclone will delete the file before uploading the new one. This behavior is consistent even when no_versions is set to true.

#### How do you think rclone should be changed to solve that?

Adding a new flag similar to no_versions where we use this API instead of the regular delete item:
https://learn.microsoft.com/en-us/graph/api/driveitem-permanentdelete?view=graph-rest-1.0

After this, we just need to update the documentation to recommend the flag if there's no need to send to recycle bin.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by edc-w** [comment]
Hello, if you are in need of this feature being added on behalf of your business and are interested in supporting the project whilst doing so, please get in touch at sales@rclone.com.

**Comment by ncw** [comment]
I implemented --onedrive-hard-delete here (named for consistency with the other backends). You can set this in the config file with `hard_delete = true`. 

Note that this only works with onedrive business / sharepoint and does not work with onedrive personal - it gives API not found if you try it there.

[v1.67.0-beta.7957.2d125976e.fix-7812-onedrive-hard-delete](https://beta.rclone.org/branch/fix-7812-onedrive-hard-delete/v1.67.0-beta.7957.2d125976e.fix-7812-onedrive-hard-delete/) on branch [fix-7812-onedrive-hard-delete](https://github.com/rclone/rclone/tree/fix-7812-onedrive-hard-delete) (uploaded in 15-30 mins)

Please give it a test - thank you.

**Comment by gomaaz** [comment]
Thx Nick,

I'll give it a try and let you now.

**Comment by gomaaz** [comment]
is this compatible with mount command?

"--onedrive-hard-delete true"?
or just "--onedrive-hard-delete"

**Comment by gomaaz** [comment]
It seems to work!

After deleting a few big-sized folders, 
rclone about: is showing no bytes in "trashed"

Also the sharepoint-Website doesn't show any files in the trash-can!

I'm happy with that :)

Good work, Nick!

![image](https://github.com/rclone/rclone/assets/2662948/27f20675-4219-47ed-b3f7-2254996ccb36)

**Comment by jcastilloalonso** [comment]
This is working great! Tested it with both delete and purge commands and both didn't land in recycle bin. Thanks a lot Nick!

**Comment by gomaaz** [comment]
is this implemented in the beta already?

**Comment by ncw** [comment]
I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.67

Thanks for testing

**Comment by YOUSSEF-HOUIET** [comment]
Hi
how can i use it for my onedrive after reducing storage by microsoft from 2048Go to 100Go
![image](https://github.com/rclone/rclone/assets/83891667/33073c3a-bc08-49e7-8512-5fdb8184ed25)

**Comment by jcastilloalonso** [comment]
I recommend you open a topic in the forums and follow the template for assistance, this issue is closed now.
