### ISSUE TITLE
`rclone ls` does not exit with an error code on various cloud backends when file doesn't exist

### ISSUE THREAD

**Issue by aanderse** [rclone/rclone#7817]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/rclone-ls-backend-file-doesnt-exit-with-a-fail-code-when-not-existing/40124

#### What is the problem you are having with rclone?

`rclone ls remote:file-which-does-not-exist` exits with a `0` status code instead of a non zero value

#### What is your rclone version (output from `rclone version`)

```console
$ rclone version
rclone 1.64.2
- os/version: nixos 23.11 (Tapir) (64 bit)
- os/kernel: 5.15.0-101-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.4
- go/linking: dynamic
- go/tags: cmount
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

`linux`, `x86_64`

#### Which cloud storage system are you using? (e.g. Google Drive)

i have reproduced this issue on `type = s3` (`provider = AWS`), `type = b2`, and `type = google cloud storage`

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone ls remote:file-which-does-not-exist`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2024/05/01 13:13:57 DEBUG : rclone: Version "1.64.2" starting with parameters ["/nix/store/s61xmghrjig9l97v5dy5c2gsc4mdihgr-rclone-1.64.2/bin/rclone" "ls" "-vvv" "remote:bucket/file-that-does-not-exist"]
2024/05/01 13:13:57 DEBUG : Creating backend with remote "remote:bucket/file-that-does-not-exist"
2024/05/01 13:13:57 DEBUG : Using config file from "/home/aanderse/.config/rclone/rclone.conf"
2024/05/01 13:13:57 DEBUG : 5 go routines active
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
This seems fine in the later version:

```
texter@Earls-Mac-mini Downloads % rclone ls GD:adfajd
2024/05/08 14:23:01 Failed to ls: directory not found
```

Exit code
```
texter@Earls-Mac-mini Downloads % echo $?
3
```

Version
```
texter@Earls-Mac-mini Downloads % rclone version
rclone v1.66.0
- os/version: darwin 14.4.1 (64 bit)
- os/kernel: 23.4.0 (arm64)
- os/type: darwin
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.22.1
- go/linking: dynamic
- go/tags: cmount
```

**Comment by ncw** [comment]
> i have reproduced this issue on `type = s3` (`provider = AWS`), `type = b2`, and `type = google cloud storage`

These are all bucket based systems which don't really have directories.

So if you do

    rclone ls remote:file-which-does-not-exist

Rclone doesn't know if `file-which-does-not-exist` is a file or a directory. If the file isn't found it is treated as a directory, and listing a non existent directory will just give no items as s3/etc don't have directories.

I hope that clears things up!
