### ISSUE TITLE
MacOS and Linux doesn't support space character on folder name

### ISSUE THREAD

**Issue by aliosmanozturk1** [rclone/rclone#7837]
#### What is the problem you are having with rclone?
In windows 11 the command "rclone copy googledrive:Tercüman Cepte" works properly and copies the "Tercüman Cepte" folder and its contents to my computer. But on macOS and Linux the same command gives the error "google drive root 'Tercüman Cepte': error reading source root directory: directory not found". if I change the folder name from "Tercüman Cepte" to "Tercuman Cepte" the problem persists. So you can understand that the problem is not caused by the "ü" character, but by the "space" character. I don't want to go to Google Drive and delete the spaces in all my folders, that would be ugly. How can I solve this problem?

Translated with www.DeepL.com/Translator (free version)

#### What is your rclone version (output from `rclone version`)
v1.66.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
macOS Sonoma 14.4.1, Apple Silicon M1
Raspbian 64 Bit

#### Which cloud storage system are you using? (e.g. Google Drive)
Google Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone copy googledrive:Tercüman Cepte

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
(base) aliosmanozturk@Ali-MacBook-Air ~ % rclone copy googledrive:Tercüman Cepte -vv
2024/05/11 17:22:17 DEBUG : rclone: Version "v1.67.0-beta.7932.e0b38cc9a" starting with parameters ["rclone" "copy" "googledrive:Tercüman" "Cepte" "-vv"]
2024/05/11 17:22:17 DEBUG : Creating backend with remote "googledrive:Tercüman"
2024/05/11 17:22:17 DEBUG : Using config file from "/Users/aliosmanozturk/.config/rclone/rclone.conf"
2024/05/11 17:22:18 DEBUG : Google drive root 'Tercüman': 'root_folder_id = 0AECrrfN5GSQiUk9PVA' - save this in the config to speed up startup
2024/05/11 17:22:19 DEBUG : Creating backend with remote "Cepte"
2024/05/11 17:22:19 DEBUG : fs cache: renaming cache item "Cepte" to be canonical "/Users/aliosmanozturk/Cepte"
2024/05/11 17:22:20 ERROR : Google drive root 'Tercüman': error reading source root directory: directory not found
2024/05/11 17:22:20 DEBUG : Local file system at /Users/aliosmanozturk/Cepte: Waiting for checks to finish
2024/05/11 17:22:20 DEBUG : Local file system at /Users/aliosmanozturk/Cepte: Waiting for transfers to finish
2024/05/11 17:22:20 ERROR : Attempt 1/3 failed with 1 errors and: directory not found
2024/05/11 17:22:20 ERROR : Google drive root 'Tercüman': error reading source root directory: directory not found
2024/05/11 17:22:20 DEBUG : Local file system at /Users/aliosmanozturk/Cepte: Waiting for checks to finish
2024/05/11 17:22:20 DEBUG : Local file system at /Users/aliosmanozturk/Cepte: Waiting for transfers to finish
2024/05/11 17:22:20 ERROR : Attempt 2/3 failed with 1 errors and: directory not found
2024/05/11 17:22:21 ERROR : Google drive root 'Tercüman': error reading source root directory: directory not found
2024/05/11 17:22:21 DEBUG : Local file system at /Users/aliosmanozturk/Cepte: Waiting for checks to finish
2024/05/11 17:22:21 DEBUG : Local file system at /Users/aliosmanozturk/Cepte: Waiting for transfers to finish
2024/05/11 17:22:21 ERROR : Attempt 3/3 failed with 1 errors and: directory not found
2024/05/11 17:22:21 INFO  : 
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 1 (retrying may help)
Elapsed time:         3.2s

2024/05/11 17:22:21 DEBUG : 7 go routines active
2024/05/11 17:22:21 Failed to copy: directory not found

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Can you [post on the rclone forum](https://forum.rclone.org/) about this and you'll get some help troubleshooting - thank you.
