### ISSUE TITLE
Fatal error: unknown flag: --vfs-cache-mode

### ISSUE THREAD

**Issue by AtomicRobotMan0101** [rclone/rclone#7839]
#### What is the problem you are having with rclone?

With a Google Photos config and running `rclone rcd --rc-web-gui`

produces: 

`NOTICE: Google Photos path "": --vfs-cache-mode writes or full is recommended for this remote as it can't stream`

Using the suggested `--vfs-cache-mode` produces `Fatal error: unknown flag: --vfs-cache-mode`

Continuation(?) of issue [https://github.com/rclone/rclone/issues/2067](https://github.com/rclone/rclone/issues/2067)

#### What is your rclone version (output from `rclone version`)

rclone v1.66.0
- os/version: linuxmint 21.3 (64 bit)
- os/kernel: 6.5.0-28-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.1
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Linux Mint Cinnamon 21.3

#### Which cloud storage system are you using? (e.g. Google Drive)

Google Photos

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone rcd --rc-web-gui`

![Screenshot from 2024-05-13 18-24-09](https://github.com/rclone/rclone/assets/64177332/e60e25c1-a927-4fd7-b4f0-f6cdddc87ab5)

......

![2](https://github.com/rclone/rclone/assets/64177332/886031a9-f66a-48b5-beea-4c10af16fb8f)

SNIP!

![3](https://github.com/rclone/rclone/assets/64177332/93cebf52-518a-4c25-b7ed-dac6c11cac6a)

**Comment by albertony** [comment]
What you tried is not valid according to documented [basic syntax](https://rclone.org/docs/#basic-syntax), as it does not specify a subcommand:
```
rclone --vfs-cache-mode=full
```

I haven't used rcd much myself, but I'm guessing the following is what you need to do, try it out:
```
rclone rcd --rc-web-gui --vfs-cache-mode=full
```

**Comment by Animosity022** [comment]
For general use questions, please use the forums as well:

https://forum.rclone.org

**Comment by AtomicRobotMan0101** [comment]
Sorry, a bit of clarity...

This recommendation to run the parameter and subsequent error is generated FROM the program itself.

On [the page for the GUI](https://rclone.org/gui/), it is advised to run this `rclone rcd --rc-web-gui`

Upon running that, the error occurs.  I have done nothing and this is entirely reproducible.  The output advisory is incorrect.

**Comment by AtomicRobotMan0101** [comment]
The erroneous suggestion is produced by the binary.

As the user, I was simply following the directive.

I shall fork and push an update when fixed.

**Comment by albertony** [comment]
I do not see what you mean.

When you run:

> rclone rcd --rc-web-gui

It recommends:

> --vfs-cache-mode writes or full is recommended for this remote as it can't stream

And blindly following that would give you correct result:

> rclone rcd --rc-web-gui --vfs-cache-mode full

But maybe I missed your point. And you are, of course, free to submit a pull request if you think something can be improved.
