### ISSUE TITLE
Life changing simple feature for headless Oauth signin

### ISSUE THREAD

**Issue by Joyen12** [rclone/rclone#7872]
when adding an account with `rclone config`, instead of outputing the localhost url , output directly the url from google which look like that : https://accounts.google.com/o/oauth2/auth?client_id=564921029129.apps.googleusercontent.com&redirect_uri=https%3A%2F%2Fgd-ocaml-auth.appspot.com%2Foauth2callback&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force&state=aITr7Bpgp7nx860pFeQx301e7MPo8j3NWqpVN4265eo")

So that we can just copy it and paste it locally on our desktop to accept the Oauth. Because obviously the localhost one we can't use it in local on our mac or pc for example. This is something simple but really life changing for people using a headless VPS e.g droplet,etc...

(I know we can use X11 forwarding and other tricks, but it's a real pain as it is really slow if we use a good ssh encryption and also it's even harder for mac and windows user as X11 forwarding is not support by default)

Tell me what you think and if you can implement this, I'm wiling to help if necessary but I think it is just a few line changes so it would be much easier to do for someone already familiar with the code

Thank you for this amazing project btw

Best regards

**Comment by Animosity022** [comment]
You can't just copy a URL as you need the redirect URI as well which is why rclone authorize exists for headless setups.

https://rclone.org/remote_setup/

Just use that as it's already there and nothing is needed to forward.

You can also just copy rclone.conf from a machine with a browser as that works great as well.
