### ISSUE TITLE
rclone lsjson does not implement --include filter

### ISSUE THREAD

**Issue by hannasm** [rclone/rclone#7882]
I was running rclone v1.59.1. After noticing this issue i updated to 1.66.0.

I am running against an amazon s3 compatible container hosted by Wasabi.

```rclone lsjson``` is not respecting the ```-include '*filename*' ``` pattern

Instead of limiting the results to files matching the wildcard, it seems to be listing all files in the path.

Per the documentation at [https://rclone.org/commands/rclone_lsjson/#filter-options](https://rclone.org/commands/rclone_lsjson/#filter-options) this should be supported.

As an added note, it seems ```rclone lsf``` also has this issue so getting filtered results of parseable output is problematic.

```rclone ls``` does work as expected with the ```--include``` directive

**Comment by ncw** [comment]
Filtering works fine with `lsjson` and `lsf`

```
$ rclone lsjson .
[
{"Path":"a","Name":"a","Size":4096,"MimeType":"inode/directory","ModTime":"2024-04-17T11:43:53.199250343+01:00","IsDir":true},
{"Path":"a.js","Name":"a.js","Size":0,"MimeType":"text/javascript; charset=utf-8","ModTime":"2024-05-20T07:08:08.688785511+01:00","IsDir":false},
{"Path":"a.wav","Name":"a.wav","Size":0,"MimeType":"audio/x-wav","ModTime":"2024-05-20T07:08:08.688785511+01:00","IsDir":false},
{"Path":"a.zip","Name":"a.zip","Size":0,"MimeType":"application/zip","ModTime":"2024-05-20T07:08:08.688785511+01:00","IsDir":false}
]
```

```
$ rclone lsjson . --include "*.js"
[
{"Path":"a","Name":"a","Size":4096,"MimeType":"inode/directory","ModTime":"2024-04-17T11:43:53.199250343+01:00","IsDir":true},
{"Path":"a.js","Name":"a.js","Size":0,"MimeType":"text/javascript; charset=utf-8","ModTime":"2024-05-20T07:08:08.688785511+01:00","IsDir":false}
]
```

(note the directory is being shown as there could be `*.js` files in there).

This is most likely a problem with the syntax of the `--include` command but if you head over to [post on the rclone forum](https://forum.rclone.org/) about this you'll find lots of knowledgeable users there who can help you.

Thanks
