### ISSUE TITLE
DLNA Browse+BrowseMetadata not to spec, angers pedantic client.

### ISSUE THREAD

**Issue by ameuret** [rclone/rclone#7883]
#### The associated forum post URL from `https://forum.rclone.org`

Irrelevant.

#### What is the problem you are having with rclone?

Rclone DLNA server doesn't conform to [spec](https://upnp.org/specs/av/UPnP-av-ContentDirectory-v1-Service.pdf) when replying to a Browse request. Section 2.7.4.2. _Argument Descriptions_ says it should include `NumberReturned` and `TotalMatches`.

[Current rclone code](https://github.com/rclone/rclone/blob/3f3e4b055e322ed6b8c8686cc20948244d884c21/cmd/serve/dlna/cds.go#L291) only returns `Result`.

This was discovered using the [DLNA Digital Media Integration](https://www.home-assistant.io/integrations/dlna_dms) in Home Assistant.

This results in a failure to browse and inability to go further. Granted, the client could be more tolerant. But the fix seems trivial and would probably benefit everyone.

![image](https://github.com/rclone/rclone/assets/28158/cff1fe0a-4cca-4c45-be9c-2ded3442d5b3)

#### What is your rclone version (output from `rclone version`)

rclone v1.66.0
- os/version: arch 24.0.1 (64 bit)
- os/kernel: 6.7.12-1-MANJARO (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.1
- go/linking: dynamic
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

See above.

#### Which cloud storage system are you using? (e.g. Google Drive)

None

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone serve dlna --addr 0.0.0.0:8090 -vv /home/arnaud/[...]`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
[...Startup...]
2024/06/01 16:15:11 INFO  : /ctl: 192.168.1.173:51490 POST 200 "urn:schemas-upnp-org:service:ContentDirectory:1#Browse"
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment]
I see. I created a suggestion for a fix in https://github.com/rclone/rclone/pull/7885.

Maybe you would be willing to test a beta build, it should be ready in a few minutes here: https://beta.rclone.org/branch/dlna-browsemetadata-fix/

**Comment by ameuret** [comment]
I confirm that this beta build works on Linux AMD64. Thanks a lot !

![image](https://github.com/rclone/rclone/assets/28158/2fe775f8-1cf5-4ecf-977f-722f8f7bd60c)

**Comment by albertony** [comment]
Easy fix when the issue is so to the point! And thank you for testing!
Its been merged now, so it will be included in the official betas from now on, and probably next release.
