### ISSUE TITLE
rclone v1.67 became W32.Riskware.Rclone.Variant

### ISSUE THREAD

**Issue by thegeekboyz** [rclone/rclone#7915]
#### The associated forum post URL from `https://forum.rclone.org`
none

#### What is the problem you are having with rclone?
rclone v1.67 became W32.Riskware.Rclone.Variant as detected by Webroot Endpoint Protection antivirus software
prior version has no issues.
access is denied after it was detected to be infected.
tested with self-update and manual download from github.
revert to prior version and the rclone is no longer detected as infected

#### What is your rclone version (output from `rclone version`)
latest rclone v1.67

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
windows 10 64bit

#### Which cloud storage system are you using? (e.g. Google Drive)
not relevant

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
not relevant as total access denied on the rclone.exe

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
message from my antivirus scanlog
Infection detected: C:\rclone\rclone.exe [SHA256: C189595C36996BDB7DCE6EC28CF6906A00CBB5C5FE182E038BF476D74BED349E] [MD5: 316A534A8F17DE17C38EE3F7C37EEDF4] [3/00090010] [W32.Riskware.Rclone.Variant]

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
This is almost certainly a false positive. Any ideas on how to report that?

**Comment by thegeekboyz** [comment]
i am confident rclone is safe and is false positive. i have submitted the false positive report and we shall wait for their reply.
thanks. but there is something in the code that is in latest version that trigger the threat detection

**Comment by ncw** [comment]
Thanks, I'm going to assume this is OK now.
