### ISSUE TITLE
union path_policy (request)

### ISSUE THREAD

**Issue by Prankish8407** [rclone/rclone#7920]
Hi rclone, 

Before i start explaining, i've searched for this topic and haven't found this request yet.
I've also read through the rclone documentation but could not find it there either.

The idea:
When you make an rclone config file with a union mount you get something like below:
`[AIO]
type = union
upstreams = koofr_encrypted: dropbox_encrypted: pcloud_encrypted:
min_free_space = 5Gi
action_policy = epmfs
create_policy = ff
search_policy = ff`

I would love to see an option added like path_policy that allows upstream mounts to used based on the path within the union mount.
for all the above hosts i made a folder on:

Mount:                           Foldername:
koofr_encrypted            Koofr
dropbox_encrypted       Dropbox
pcloud_encrypted         Pcloud

So when i mount them via the union mount i have a single mount point that then shows 3 folders, so each folder is on a separate cloud.
with the path_policy i want to make sure no matter what, if the path is equal to "Koofr" it always uses the koofr_encrypted: mount, the same goes for "Dropbox" as a path etc.

currently with the "empty free space" option (epmfs) it will pick the most free space. when creating on "first found" (ff) it will not always use the storage provided that starts with the folder Koofr.

I noticed when i create the entire folder structure on the mount beforehand and use ff it still uploads to a random mount.

Kind regards,

**Comment by ncw** [comment]
I think you want the [combine backend](https://rclone.org/combine/) which does exactly this.

**Comment by Prankish8407** [comment]
> I think you want the [combine backend](https://rclone.org/combine/) which does exactly this.

thats exactly what i need, wauw how havent i seen this before! cheers.

**Comment by Prankish8407** [comment]
Hey Nick,

Thanks for the advice and it works really well.
I'm trying to figure out 1 more thing, i don't know if its possible but with the combine config looking like this:

[AIO_test]
type = combine
upstreams = "koofr=koofr_encrypted:koofr" "dropbox=dropbox_encrypted:dropbox" "pcloud=pcloud_encrypted:pcloud"

Is there a way to have each folder their own size of the underlying mount?
Example:
koofr folder --> 10TB
dropbox folder --> 1TB
pcloud folder --> 1TB

so for example:
so the total mount size is 12TB but since its "combined" it shows the mount size of 12 TB when i read the folder properties from pcloud is says 12TB while its 1TB.

I could not find anything about this in the documentation or the forums.
i would expect this not being possible but it doesn't hurt to ask i guess.

**Comment by ncw** [comment]
Unfortunately the internal rclone API for this makes this impossible at the moment!
