### ISSUE TITLE
Transport endpoint is not connected and auto killed

### ISSUE THREAD

**Issue by TunglinInamin** [rclone/rclone#7936]
OS: CentOS 7.9

when I mount any cloud, it's normal. about 3 minutes later, I use "cd mountfolder", it will show:
Transport endpoint is not connected

and then,  I use command "rclone mount cloud:/ mountfolder -vv

2024/07/08 03:11:25 DEBUG : rclone: Version "v1.61.1" starting with parameters ["rclone" "mount" "e5:" "e5n" "--daemon" "-vv"]
2024/07/08 03:11:25 DEBUG : Creating backend with remote "e5:"
2024/07/08 03:11:25 DEBUG : Using config file from "/root/.config/rclone/rclone.conf"
2024/07/08 03:11:27 DEBUG : rclone: Version "v1.61.1" finishing with parameters ["/usr/bin/rclone" "mount" "e5:" "e5n" "--daemon" "-vv"]
.
.readfile I used
.
Killed

I restart my server it's normal. but I don't know when will it happen again.

**Comment by Animosity022** [comment]
Please use the forums for support.

https://forum.rclone.org

Update your version.
Use the help and support template.
