### ISSUE TITLE
Listen for metrics on a separate port than the API

### ISSUE THREAD

**Issue by r10r** [rclone/rclone#7940]
Hi rclone devs,

I'd like to expose the metrics on another port than the rcd API for security reasons.
`rclone rcd` is running as a sidecar container in kubernetes and remote control should
only be possible from localhost (containers in the same pod), whereas the metrics should
be exposed in the cluster to a prometheus instance.

What do you think about an additional flag `--rc-metrics-addr` to serve the metrics
from a different port?

**Comment by ncw** [comment]
That seems like a reasonable idea. Want to have a go at implementing? I'm not sure how easy it will be though!

**Comment by hiddenmarten** [comment]
Looks like a good first issue for me.

@ncw I'll try to implement it.

**Comment by r10r** [comment]
@ncw Sorry for the late reply. @hiddenmarten I'd be pleased if you do create a PR for it.

**Comment by hiddenmarten** [comment]
Ready to review, I believe! :)

https://github.com/rclone/rclone/pull/7965

**Comment by ncw** [comment]
Thank you for implementing this @hiddenmarten 

This turned out to be a bit more involved than I thought!

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.68

Please see the new `--metrics-*` flags.
