### ISSUE TITLE
Unknown flag: --protondrive-2fa

### ISSUE THREAD

**Issue by AlexisGommet** [rclone/rclone#7943]
#### What is the problem you are having with rclone?

The [protondrive-2fa flag](https://rclone.org/protondrive/#protondrive-2fa) is unknown even tough it worked fine before.

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

```
rclone 1.64.2
- os/version: fedora 40 (64 bit)
- os/kernel: 6.9.7-200.fc40.x86_64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.21.6
- go/linking: dynamic
- go/tags: none
```

#### Which cloud storage system are you using?

Proton Drive

#### The command you were trying to run

`rclone sync -P --no-update-modtime xxx Proton:xxx --protondrive-2fa=000000`

#### A log from the command with the `-vv` flag

[Output](https://pastebin.com/8jtXmkit)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
You have to update rclone.

Use the forums for general support.
