### ISSUE TITLE
Tebi.io S3 --backup-dir name issue when move deleted files

### ISSUE THREAD

**Issue by axww** [rclone/rclone#7946]
#### What is the problem you are having with rclone?
I use rclone to sync my files into Tebi Cloud (S3 compatibility) with backup for changes/deleted files.
Local dir for backup is /www
Remote dir is :s3:bak123/bak
--backup-dir is :s3:bak123/bakbak
1. Create Bucket "bak123" on Tebi Cloud
2. Create 3 files 1, 2, 3 (without extension) in /www
3. Run sync command
4. Check Tebi Cloud, file 1, 2, 3 all synced into Bucket folder bak123/bak 
5. Delete file 2, 3 from /www
6. Run sync command again
7. Check Tebi Cloud Bucket folder bak123/bak and bak123/bakbak
8. In folder bak123/bak, there are files 1, ak/2, ak/3 ; In folder bak123/bakbak, there are files 2,3

The main issue here is, files 2, 3 should be deleted from Remote dir bak123/bak/
But their name changes into ak/2 and ak/3, not deleted.
However, backup dir works correctly.

As there are file names like "ak/2" and "ak/3", it seems there are some issue with backupDir file name detection and file move function.
I've tried add "/" behind dir path or adding quoting "" around dir path, the same issue still occurred.
If I change backup dir into ":s3:bak123/bak123" instead of ":s3:bak123/bakbak", the issue solved.

Tebi Cloud has 20GB free Tier without binding Credit Card so you can register and have a try.
Would you please help check the issue, many thanks!

#### What is your rclone version (output from `rclone version`)
rclone v1.67.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
- os/version: debian 12.6 (64 bit)
- os/kernel: 6.1.0-21-cloud-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.4
- go/linking: static
- go/tags: none

#### Which cloud storage system are you using? (e.g. Google Drive)
Tebi Cloud
https://tebi.io/

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
`rclone sync -vv -P /www ":s3:bak123/bak/" --backup-dir ":s3:bak123/bakbak/" --checksum --fast-list --s3-provider=Other --s3-endpoint=s3.tebi.io --s3-access-key-id=<hidden> --s3-secret-access-key=<hidden>`

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
```
2024/07/11 12:00:46 DEBUG : rclone: Version "v1.67.0" starting with parameters ["rclone" "sync" "-vv" "-P" "/www" ":s3:bak123/bak/" "--backup-dir" ":s3:bak123/bakbak/" "--checksum" "--fast-list" "--s3-provider=Other" "--s3-endpoint=s3.tebi.io" "--s3-access-key-id=<hidden>" "--s3-secret-access-key=<hidden>"]
2024/07/11 12:00:46 DEBUG : Creating backend with remote "/www"
2024/07/11 12:00:46 NOTICE: Config file "/root/.config/rclone/rclone.conf" not found - using defaults
2024/07/11 12:00:46 DEBUG : Creating backend with remote ":s3:bak123/bak/"
2024/07/11 12:00:46 DEBUG : :s3: detected overridden config - adding "{JA2Vj}" suffix to name
2024/07/11 12:00:46 DEBUG : Resolving service "s3" region "us-east-1"
2024/07/11 12:00:46 DEBUG : fs cache: renaming cache item ":s3:bak123/bak/" to be canonical ":s3{JA2Vj}:bak123/bak"
2024/07/11 12:00:46 DEBUG : Creating backend with remote ":s3:bak123/bakbak/"
2024/07/11 12:00:46 DEBUG : :s3: detected overridden config - adding "{JA2Vj}" suffix to name
2024/07/11 12:00:46 DEBUG : Resolving service "s3" region "us-east-1"
2024/07/11 12:00:46 DEBUG : fs cache: renaming cache item ":s3:bak123/bakbak/" to be canonical ":s3{JA2Vj}:bak123/bakbak"
2024/07/11 12:00:47 DEBUG : S3 bucket bak123 path bak: Waiting for checks to finish
2024/07/11 12:00:47 DEBUG : S3 bucket bak123 path bak: Waiting for transfers to finish
2024/07/11 12:00:47 DEBUG : Waiting for deletions to finish
2024/07/11 12:00:52 DEBUG : 2: md5 = c81e728d9d4c2f636f067f89cc14862c OK
2024/07/11 12:00:52 INFO  : 2: Copied (server-side copy)
2024/07/11 12:00:52 INFO  : 2: Deleted
2024/07/11 12:00:52 INFO  : 2: Moved into backup dir
Transferred:              1 B / 1 B, 100%, 0 B/s, ETA -
Checks:                 3 / 3, 100%
Deleted:                2 (files), 0 (dirs), 2 B (freed)
Renamed:                1
Transferred:            1 / 1, 100%
Server Side Copies:     1 @ 1 B
Elapsed time:         5.7s
2024/07/11 12:00:52 INFO  :
Transferred:              1 B / 1 B, 100%, 0 B/s, ETA -
Checks:                 3 / 3, 100%
Deleted:                2 (files), 0 (dirs), 2 B (freed)
Renamed:                1
Transferred:            1 / 1, 100%
Server Side Copies:     1 @ 1 B
Elapsed time:         5.7s
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Can you try this on one of the other S3 providers please.

This is sounding like a Tebi bug but it would be good to have confirmation.

**Comment by axww** [comment]
> Can you try this on one of the other S3 providers please.
> 
> This is sounding like a Tebi bug but it would be good to have confirmation.

Hi, I've tested multiple S3 providers.
You are right, it is a Tebi bug, I will send a feedback to them.
FYI there are other issues during test, here's results.

idrivee2.com:
Everything works fine.

backblaze.com using S3 mode:
Backup copied fine on remote.
Local deleted file didn't got deleted on remote.

synology.com:
Backup and delete both failed.
```
2024/07/11 15:20:43 ERROR : 3: Failed to copy: AccessDenied: Access Denied.
        status code: 403, request id: txf176c25546454aeba03ee-00668ff84b, host id: txf176c25546454aeba03ee-00668ff84b
2024/07/11 15:20:43 ERROR : 3: Not deleting source as copy failed: AccessDenied: Access Denied.
        status code: 403, request id: txf176c25546454aeba03ee-00668ff84b, host id: txf176c25546454aeba03ee-00668ff84b
2024/07/11 15:20:43 ERROR : 3: Couldn't move into backup dir: AccessDenied: Access Denied.
        status code: 403, request id: txf176c25546454aeba03ee-00668ff84b, host id: txf176c25546454aeba03ee-00668ff84b
2024/07/11 15:20:43 ERROR : S3 bucket bak123 path bak: not deleting directories as there were IO errors
2024/07/11 15:20:43 ERROR : Attempt 1/3 failed with 2 errors and: failed to delete 1 files
2024/07/11 15:20:43 ERROR : 3: Failed to copy: AccessDenied: Access Denied.
        status code: 403, request id: tx9b48575d11504d739af13-00668ff84b, host id: tx9b48575d11504d739af13-00668ff84b
2024/07/11 15:20:43 ERROR : 3: Not deleting source as copy failed: AccessDenied: Access Denied.
        status code: 403, request id: tx9b48575d11504d739af13-00668ff84b, host id: tx9b48575d11504d739af13-00668ff84b
2024/07/11 15:20:43 ERROR : 3: Couldn't move into backup dir: AccessDenied: Access Denied.
        status code: 403, request id: tx9b48575d11504d739af13-00668ff84b, host id: tx9b48575d11504d739af13-00668ff84b
2024/07/11 15:20:43 ERROR : S3 bucket bak123 path bak: not deleting directories as there were IO errors
2024/07/11 15:20:43 ERROR : Attempt 2/3 failed with 2 errors and: failed to delete 1 files
2024/07/11 15:20:44 ERROR : 3: Failed to copy: AccessDenied: Access Denied.
        status code: 403, request id: tx74b14ecc9bc04bb09871d-00668ff84c, host id: tx74b14ecc9bc04bb09871d-00668ff84c
2024/07/11 15:20:44 ERROR : 3: Not deleting source as copy failed: AccessDenied: Access Denied.
        status code: 403, request id: tx74b14ecc9bc04bb09871d-00668ff84c, host id: tx74b14ecc9bc04bb09871d-00668ff84c
2024/07/11 15:20:44 ERROR : 3: Couldn't move into backup dir: AccessDenied: Access Denied.
        status code: 403, request id: tx74b14ecc9bc04bb09871d-00668ff84c, host id: tx74b14ecc9bc04bb09871d-00668ff84c
2024/07/11 15:20:44 ERROR : S3 bucket bak123 path bak: not deleting directories as there were IO errors
2024/07/11 15:20:44 ERROR : Attempt 3/3 failed with 2 errors and: failed to delete 1 files
```
