### ISSUE TITLE
proton-drive remote fails due to captcha

### ISSUE THREAD

**Issue by johanbook** [rclone/rclone#7967]
#### The associated forum post URL from `https://forum.rclone.org`

I found this thread with same issue, but it has been closed and browser login is not possible for me.

https://forum.rclone.org/t/captcha-failed-to-create-file-system-for-proton/43352/6

Please close thread if inappropriate.

#### What is the problem you are having with rclone?

When attempting to use the proton-drive remote it fails due to captcha. In the docs it states

> NOTE: The Proton Drive encryption keys need to have been already generated after a regular login via the browser, otherwise attempting to use the credentials in rclone will fail.

but there is no example how to do this, especially for a remote machine with no UI.

Basically what I would expect would be to have a bit more info on this in the docs at https://rclone.org/protondrive/.

Apart from this issue, this tool seems amazing.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.67.0
- os/version: debian 11.10 (64 bit)
- os/kernel: 5.10.0-21-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.4
- go/linking: static
- go/tags: none
````

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Debian GNU/Linux 11 (bullseye)

#### Which cloud storage system are you using? (e.g. Google Drive)

Proton Drive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
rclone lsd proton-drive:
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
user@remote-machine:/srv$ rclone lsd proton-drive:
Enter configuration password:
password:
2024/07/21 08:07:12.789039 WARN RESTY 422 POST https://mail.proton.me/api/auth/v4: For security reasons, please complete CAPTCHA. If you can't pass it, please try updating your app or contact us here: https://proton.me/support/appeal-abuse (Code=9001, Status=422), Attempt 1
2024/07/21 08:07:12.789826 ERROR RESTY 422 POST https://mail.proton.me/api/auth/v4: For security reasons, please complete CAPTCHA. If you can't pass it, please try updating your app or contact us here: https://proton.me/support/appeal-abuse (Code=9001, Status=422)
2024/07/21 08:07:12 Failed to create file system for "proton-drive:": couldn't initialize a new proton drive instance: 422 POST https://mail.proton.me/api/auth/v4: For security reasons, please complete CAPTCHA. If you can't pass it, please try updating your app or contact us here: https://proton.me/support/appeal-abuse (Code=9001, Status=422)

```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Try one of the methods here: https://rclone.org/remote_setup/

Copying the config file is probably the most reliable in your case.

**Comment by johanbook** [comment]
I see I missed that piece of documentation. Thank you.

**Comment by CyberT33N** [comment]
Open `https://mail.proton.me` in new incognito browser window, sign-in and solve captcha. Then your host IP will be marked as captcha solved and you can continue

**Comment by Sewer56** [comment]
> Open https://mail.proton.me in new incognito browser window, sign-in and solve captcha. Then your host IP will be marked as captcha solved and you can continue

Great idea. I tried it, and it didn't quite work for me- but I understand the thought process, ahaha.

**Comment by billyjbryant** [comment]
This is still an issue and solving a captcha in Incognito does not seem to resolve the issue.

**Comment by Zoups67** [comment]
Same issue here. Incognito login does not work

**Comment by davidjeddy** [comment]
Dropping in here as well, Browser does not open in my use case as well.

Debian 13
Gnome terminal 
Brave browser

```sh
rclone --version
rclone v1.73.4
- os/version: debian 13.4 (64 bit)
- os/kernel: 6.12.74+deb13+1-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.25.9
- go/linking: static
- go/tags: none

2026/04/10 22:09:17 DEBUG : Creating backend with remote "protondrive:"
2026/04/10 22:09:17 DEBUG : Using config file from "/home/user/.config/rclone/rclone.conf"
2026/04/10 22:09:17 DEBUG : proton drive root link ID '': Using username and password to log in
2026/04/10 22:09:19.430420 WARN RESTY 422 POST https://mail.proton.me/api/auth/v4: For security reasons, please complete CAPTCHA. If you can't pass it, please try updating your app or contact us here: https://proton.me/support/appeal-abuse (Code=9001, Status=422), Attempt 1
2026/04/10 22:09:19.430486 ERROR RESTY 422 POST https://mail.proton.me/api/auth/v4: For security reasons, please complete CAPTCHA. If you can't pass it, please try updating your app or contact us here: https://proton.me/support/appeal-abuse (Code=9001, Status=422)
2026/04/10 22:09:19 CRITICAL: Failed to create file system for "protondrive:": couldn't initialize a new proton drive instance: 422 POST https://mail.proton.me/api/auth/v4: For security reasons, please complete CAPTCHA. If you can't pass it, please try updating your app or contact us here: https://proton.me/support/appeal-abuse (Code=9001, Status=422)
2026/04/10 22:09:20.149333 WARN RESTY 422 POST https://mail.proton.me/api/auth/v4: For security reasons, please complete CAPTCHA. If you can't pass it, please try updating your app or contact us here: https://proton.me/support/appeal-abuse (Code=9001, Status=422), Attempt 1
2026/04/10 22:09:20.149379 ERROR RESTY 422 POST https://mail.proton.me/api/auth/v4: For security reasons, please complete CAPTCHA. If you can't pass it, please try updating your app or contact us here: https://proton.me/support/appeal-abuse (Code=9001, Status=422)
2026/04/10 22:09:20 CRITICAL: Failed to create file system for "protondrive:": couldn't initialize a new proton drive instance: 422 POST https://mail.proton.me/api/auth/v4: For security reasons, please complete CAPTCHA. If you can't pass it, please try updating your app or contact us here: https://proton.me/support/appeal-abuse (Code=9001, Status=422)
```

**Comment by morceaudebois** [comment]
Still very much an issue on Rclone 1.68 :(

edit: nvm I'm an idiot, updating to 1.74.3 fixes it. Been trying to make it work since 2024, this is nothing short of a miracle
