### ISSUE TITLE
uloz.to mass spam with HTTP error 409

### ISSUE THREAD

**Issue by Betaman2k** [rclone/rclone#7969]
#### What is the problem you are having with rclone?

HTTP error 409 (409 Conflict) returned body: "{\n    \"message\": \"Error 1005: File conflict\",\n    \"return_code\": 409\n}"

#### What is your rclone version (output from `rclone version`)

--> rclone v1.68.0-beta.8116.31fabb340

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

- os/version: debian 12.6 (64 bit)
- os/kernel: 6.1.0-17-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.23rc2
- go/linking: static
- go/tags: none

#### Which cloud storage system are you using? (e.g. Google Drive)

uloz.to

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone copy /tmp remote:tmp

**Comment by ncw** [comment]
Can you provide more details please?

1. A full log with -vv
2. The output of `rclone config redacted`
3. The output of `rclone version`
4. A description of what you were trying to do

Thanks

**Comment by Betaman2k** [comment]
> Can you provide more details please?
> 
> 1. A full log with -vv
> 2. The output of `rclone config redacted`
> 3. The output of `rclone version`
> 4. A description of what you were trying to do
> 
> Thanks

Hi
3 and 4 is written there
 rclone v1.68.0-beta.8116.31fabb340
rclone copy /tmp remote:tmp

[uloz]
type = ulozto
app_token = didicated api key
username = email
password = secret password

**Comment by ncw** [comment]
We need a full log if possible.

**Comment by Betaman2k** [comment]
> We need a full log if possible.
I think the problem lies with the provider
DEBUG : Received error: HTTP error 500 (500 Internal Server Error) returned body: "{\n    \"return_code\": 500\n}" - low level retry 0/10

**Comment by ncw** [comment]
I'm going to assume this is a provider issue and close this report.

If you have evidence otherwise I will reopen.

Thank you

**Comment by jxmesth** [comment]
@ncw, @Betaman2k, I'm having the same issue. Can you please look into this a bit more before closing this?

**Comment by kapitainsky** [comment]
> @ncw, @Betaman2k, I'm having the same issue. Can you please look into this a bit more before closing this?

As it is provider issue you should contact uloz.to support. They have to fix it on their end.

**Comment by ncw** [comment]
@jxmesth assuming this is an rclone issue, which it could be, we need more detail to investigate further

1. A full log with -vv
2. The output of `rclone config redacted`
3. The output of `rclone version`
4. A description of what you were trying to do

Try to replicate the problem in the simplest way so you make the log as short as possible.

**Comment by buengese** [comment]
I think this is fixed now. Been heavily using uloz for over a month and never encountered this issue.
