### ISSUE TITLE
rclone sync from versioned s3 storage skips files

### ISSUE THREAD

**Issue by aurokk** [rclone/rclone#7972]
#### What is the problem you are having with rclone?

`rclone sync` with s3 backend and `version_at` set doesn't sync all the files, it just skips some of them (i'd say it sinks only ~chunk size files), i think there is an issue related to pagination.

Also I noticed:
1. `rclone ls` lists all files correctly (i attached sync and ls logs)
2. `rclone sync` without `version_at` works correctly
3. `--fast-list` option makes `rclone sync` with `version_at` work and stop skipping files
4. rclone 1.60 where the feature was introduced doesn't work correctly as well 

#### What is your rclone version (output from `rclone version`)
1.67.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
linux amd64, mac arm64

#### Which cloud storage system are you using? (e.g. Google Drive)
S3 (Other, https://yandex.cloud/en/services/storage)

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
```
rclone sync --s3-no-check-bucket --checksum --transfers=128 --checkers=64 --stats=15s --stats-log-level NOTICE --stats-one-line backup,version_at=\"2024-07-24T04:00:00.000Z\":data-mesh-backups-staging/staging/ProcessingOrders_Orders/ operational:data-mesh-staging/staging/ProcessingOrders_Orders_restore_local2/
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
Output of the command above
[sync.txt](https://github.com/user-attachments/files/16364993/sync.txt)

```
rclone ls -vv --s3-no-check-bucket --checksum --transfers=128 --checkers=64 --stats=15s --stats-log-level NOTICE --stats-one-line backup,version_at=\"2024-07-24T04:00:00.000Z\":data-mesh-backups-staging/staging/ProcessingOrders_Orders/stage/_delta_log/`
```
[ls.txt](https://github.com/user-attachments/files/16364992/ls.txt)

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by aurokk** [comment]
Debug logs 
```
rclone sync --s3-list-chunk=200 --s3-list-version=2 --log-file=24072110.txt -vv --dump-headers --dump-bodies --s3-no-check-bucket --checksum --transfers=128 --checkers=64 --stats=15s --stats-log-level NOTICE --stats-one-line backup,version_at=\"2024-07-24T04:00:00.000Z\":data-mesh-backups-staging/staging/ProcessingOrders_Orders/stage/_delta_log/ operational:data-mesh-staging/staging/ProcessingOrders_Orders_restore_local_24072110/stage/_delta_log/
```
[24072110.txt](https://github.com/user-attachments/files/16366155/24072110.txt)

**Comment by aurokk** [comment]
Made some tests and found out that requests made with --fast-list and without differs by delimiter param
```
/data-mesh-backups-staging?delimiter=&key-marker=staging%2FProcessingOrders_Orders%2Fstage%2F_delta_log%2F00000000000000032354.json&max-keys=1000&prefix=staging%2FProcessingOrders_Orders%2Fstage%2F_delta_log%2F&version-id-marker=00061DEBEF0F95C5&versions= HTTP/1.1
/data-mesh-backups-staging?delimiter=%2F&key-marker=staging%2FProcessingOrders_Orders%2Fstage%2F_delta_log%2F00000000000000031631.json&max-keys=200&prefix=staging%2FProcessingOrders_Orders%2Fstage%2F_delta_log%2F&version-id-marker=00061DEBEEF50845&versions= HTTP/1.1
```

**Comment by aurokk** [comment]
I made a custom build of rclone with commented out [these three lines](https://github.com/rclone/rclone/blob/f26d2c6ba86854bd1e65ebfd460a98b96db6a9e7/backend/s3/s3.go#L3933-L3935) of code (to make delimiter empty), and sync started to work as expected without --fast-list (the initial command i have complaints about).

**Comment by aurokk** [comment]
I got some more traces and I see that yandex returns <Truncated>false</Truncated> on the second call which means that there are no more files. But when there is no delimiter it returns <Truncated>true</Truncated> and everything is ok.

[withdelimiter.txt](https://github.com/user-attachments/files/16372803/withdelimiter.txt)

[withoutdelimiter.txt](https://github.com/user-attachments/files/16372805/withoutdelimiter.txt)

**Comment by aurokk** [comment]
tested yandex s3 api without rclone

in my case the folder staging/ProcessingOrders_Orders/stage/_delta_log/ contains only files and there is no any subfolders
so i expect commands return the same result

```
aws s3api list-object-versions --bucket data-mesh-backups-staging --prefix staging/ProcessingOrders_Orders/stage/_delta_log/ --debug &> ./list-object-versions.txt
```

```
aws s3api list-object-versions --bucket data-mesh-backups-staging --prefix staging/ProcessingOrders_Orders/stage/_delta_log/ --debug --delimiter=/ &> ./list-object-versions-delim.txt
```

when there is a delimiter set, the output is stripped (output contains only two pages of files), so i think the problem is on the yandex side, i contacted them

**Comment by ncw** [comment]
This kind of problem (paging not working) is usually caused by an incorrect setting of --s3-list-version however I think you've tried 1 and 2 and since you are using versions I think also that this isn't used.

Looking at your files above

> [withdelimiter.txt](https://github.com/user-attachments/files/16372803/withdelimiter.txt)

I see this for the initial requests

```xml
<NextKeyMarker>staging/ProcessingOrders_Orders/stage/_delta_log/00000000000000032354.json</NextKeyMarker>
<NextVersionIdMarker>00061DEBEF0F95C5</NextVersionIdMarker>
<MaxKeys>1000</MaxKeys>
<IsTruncated>true</IsTruncated>
```

> 
> [withoutdelimiter.txt](https://github.com/user-attachments/files/16372805/withoutdelimiter.txt)

and

```xml
<NextKeyMarker>staging/ProcessingOrders_Orders/stage/_delta_log/00000000000000032354.json</NextKeyMarker>
<NextVersionIdMarker>00061DEBEF0F95C5</NextVersionIdMarker>
<MaxKeys>1000</MaxKeys>
<IsTruncated>true</IsTruncated>
```

Which look fine.

The logs are a bit confusing as there are multiple requests going on at once for multiple directories but I think I see what you mean about it being a provider bug.

**Comment by aurokk** [comment]
Hello, @ncw.

Yeah, I reported the issue to the provider and they confirmed that there is a bug on their side. 

When there is a delimiter set `--delimiter=/` the API returns only two pages of files and the second one doesn't contain continuation information.

They said they will fix it in approx 2 week, so I'll update and close the issue when they notify me about the fix released.

Thanks!

**Comment by aurokk** [comment]
Yandex Cloud fixed the bug, so i'm closing the issue. Thanks.
