### ISSUE TITLE
Uploading files to Dropbox with `＼` in name turns to `‛＼`

### ISSUE THREAD

**Issue by YenForYang** [rclone/rclone#7979]
#### The associated forum post URL from `https://forum.rclone.org`

Not applicable at the moment

#### What is the problem you are having with rclone?

Files being uploaded to Dropbox with the character `＼` end up as files having `‛＼` in the Web UI and in the Desktop Windows app. Trying to access the files with original filename (i.e. only with `＼`, not `‛＼` fails) with rclone commands (e.g. `ls`).
This is probably an issue with encoding, as I've managed to remove the `‛` (using the Dropbox Web interface and Windows Dropbox desktop app) and setting `encoding = None` in the config file, and this allows for access (at least via `ls`) to the original filename.

#### What is your rclone version (output from `rclone version`)

v1.67.0

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 10, 64 bit.  Also applies to Debian 11.0, 64 bit. 

#### Which cloud storage system are you using? (e.g. Google Drive)

Dropbox

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

Files with the special `＼` are created with `rclone moveto`, I did confirmation with `rclone ls` to access files. 

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

Doesn't provide useful information from what I can tell. Also unclear which command to log.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
There are lots of issues about this already...

I suggest you try `--local-encoding None` and `--dropbox-encoding None` or try [the latest beta](https://beta.rclone.org/)
 with `--local-encoding Raw` and `--dropbox-encoding Raw` which is a better solution.

I'm going to close this issue as we have plenty on this subject already eg #7824

**Comment by YenForYang** [comment]
Unfortunately it looks like files that were "converted" from `＼` to `‛＼`  (uploading _without_ `encoding = None` , from Google Drive default encoding)  fails with `error listing: directory not found` when running `rclone size` _with_ `encoding = None`.  If I just use the default encodin, it actually works without error...
