### ISSUE TITLE
Different modtime is ignored in equal function

### ISSUE THREAD

**Issue by MilosR** [rclone/rclone#7990]
#### What is the problem you are having with rclone?
When using sync command for files when only date is changed (modtime), and file size remains the same (eg. only one character changed), that file isn't synchronized to destination if checksum is not supported.

Looks like the problem lies in **[equal](https://github.com/rclone/rclone/blob/1901bae4ebcbc4cdd82f6bb1862d0479f3fa386e/fs/operations/operations.go#L279-L297)** function. It doesn't return false when dates are different, it only returns when it comes to if dates are identical, or within window frame, should it return false in other cases?

Looks like there is an #911 issue related, but not sure is it properly fixed.

#### What is your rclone version (output from `rclone version`)
1.65.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Windows 10

#### Which cloud storage system are you using? (e.g. Google Drive)

PHP Sabre\DAV WebDAV server

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone sync /test-dir remote:

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
2024/08/07 14:04:59 DEBUG : rclone: Version "v1.65.2" starting with parameters ["D:\\www\\webdav-client\\node_modules\\rclone.js\\bin\\rclone" "sync" "D:\\www-new\\***REDACTED***" ":webdav,url=\"https://***REDACTED***":" "--log-level" "DEBUG" "--exclude" "node_modules/" "--exclude" "temp" "--transfers" "20" "--header" "Authorization: Bearer ***REDACTED***"]
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
The generic webdav backend does not support mod time syncing as you can't set modification times via the standard webdav protocol.

You can use this flag though which will look to see if the time on the webdav backend is older than the source file and if it is, then copy it.

  -u, --update                  Skip files that are newer on the destination

See the docs here: https://rclone.org/docs/#u-update

I'm going to close this as it isn't a bug.
