### ISSUE TITLE
`rclone listremotes --long` output changed in v1.68.0 breaks existing automation

### ISSUE THREAD

**Issue by kapitainsky** [rclone/rclone#7995]
`rclone listremotes --long` output changed in the latest beta and it creates havoc in my multiple scripts.

I do not think this change is needed at all as what is the meaning of `file`???

The key problem is that such changes break any existing automation relying on rclone output.

If required maybe it can be added behind some optional flag? Leaving `rclone listremotes --long` as it was.

in rclone v1.67.0

```
$ rclone listremotes --long
.OD01-UNION:            union
.TestWithDot:           alias
.od01_a:                onedrive       test@outlook.com
.od01_b:                onedrive       test1@outlook.com
1fichier:               fichier
CCCc:                   combine
GPhoto:                 google photos
MemTest1:               memory
OD01-ENC:               crypt
OD01-ENC-ARC:           chunker
PikPak:                 pikpak
...
```

in rclone v1.68.0
```
$ rclone-beta listremotes --long
combine:                combine       file
unionXYZ:               union         file
alias:                  alias         file
backblaze:              b2            file
crypt_od01_kapitainsky: crypt         file
.od01_a:                onedrive      file test@outlook.com
.od01_b:                onedrive      file test1@outlook.com
```

**Comment by ncw** [comment]
I think we need to make that backwards compatible @albertony

Having the environment defined ones in there too is great but we probably don't need to call them out.

**Comment by albertony** [comment]
> I do not think this change is needed at all as what is the meaning of file???

The text can be `file` or `environment`, to show where the remote definition came from - config file or environment variables. I thought it could be informative, and also there is an unlikely situation where one could have a remote with same name defined in both places and then this helps avoid any confusion regarding which one rclone considers.

> The key problem is that such changes break any existing automation relying on rclone output.

There is now `--json` for machine readable output. Hopefully that can be used for such things in future.

**Comment by kapitainsky** [comment]
> There is now `--json` for machine readable output. Hopefully that can be used for such things in future.

Sure it can and is the right way moving forward but there is no reason to change it for non json output. I have users using older rclone versions (for various reasons) and it is pain for existing automation when output format changes out of the blue.

**Comment by kapitainsky** [comment]
Thank you! I can put some less important services back on rclone beta:) Hopefully catching more serious bugs.
