### ISSUE TITLE
rclone failed continuously with WebUI

### ISSUE THREAD

**Issue by Leectan** [rclone/rclone#7999]
#### What is the problem you are having with rclone?

rclone rcd --rc-web-gui                              
2024/08/09 17:49:25 NOTICE: Web GUI exists. Update skipped.
2024/08/09 17:49:25 NOTICE: Serving Web GUI
2024/08/09 17:49:25 NOTICE: Serving remote control on http://127.0.0.1:5572/
2024/08/09 17:53:13 NOTICE: S3 bucket-example: Streaming uploads using chunk size 5Gi will have maximum file size of 48.828Ti
2024/08/09 18:30:22 ERROR : rc: "operations/uploadfile": error: multipart upload: failed to read source: context canceled

#### What is your rclone version (output from `rclone version`)
latest version

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
macos

#### Which cloud storage system are you using? (e.g. Google Drive)
AWS

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
triggered an upload file in WebUI under Explorer

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by kapitainsky** [comment]
Please use forum for support questions.

Github is for bugs and enhancement tracking.
