### ISSUE TITLE
Non-encryption support for NetStorage key

### ISSUE THREAD

**Issue by isss802** [rclone/rclone#8004]
Key information to connect to NetStorage is encrypted.
https://rclone.org/netstorage/

IAM used for AWS S3, etc. can be used without encryption.
In cases where rclone.conf is set directly, you may want to use it without encryption.
Please modify it so that the key information can be read without encryption.

**Comment by ncw** [comment]
You can create an encrypted secret using `rclone obscure`

```
$ rclone obscure secret
YCNNJ_5NenMsPtfHmfxt9yb08zGnuA
```

Also if you are creating config files with a program you can use `rclone config create` with this flag

      --obscure           Force any passwords to be obscured

And pass in cleartext passwords

```
rclone config create myremote netstorage protocol=http host=baseball-nsu.akamaihd.net/123456/content/ account=username secret=secret
```

I hope that helps.
