### ISSUE TITLE
Support OShash method

### ISSUE THREAD

**Issue by disconnect5852** [rclone/rclone#8031]
rclone is supporting several hash methods, but doesn't oshash (opensubtitles hash), which is very useful on large files, lowers the bandwidth usage dramatically on hashing.

The way how oshash works is simple, and clever. It only reads few chunks of file, and generates a hash from these chunks, so the file don't need to be fully read for compare.

Here is the main implementation for python [https://github.com/r-salas/oshash](url) but there are several go implementations too, like this: [https://github.com/trytriangles/oshash](url)

**Comment by kapitainsky** [comment]
> lowers the bandwidth usage dramatically on hashing

And what bandwidth it would save  if implemented when no remote supports it?

Maybe better to worry about it when it is really needed?:)

**Comment by ncw** [comment]
I think the os hash is useful for detecting changes, but not very useful for detecting file corruptions which is what most rclone users want.

Rclone uses modtime + size for detecting changes which is quite accurate and I think OShash would only be an improvement in a very very small percentage of cases.

I thank you for your suggestion @disconnect5852 but I don't think we will be adding this to rclone, sorry.
