### ISSUE TITLE
rclone failed to upload file to the webdav server

### ISSUE THREAD

**Issue by pseudocc** [rclone/rclone#8032]
# Environment
rclone v1.60.1-DEV
- os/version: ubuntu 24.04 (64 bit)
- os/kernel: 6.8.0-1001-oem (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.2
- go/linking: dynamic
- go/tags: none

# Steps to reproduce
```bash
echo 1 > trash
rclone copyto trash remote:trash -P
# Transferred:   	         2 B / 2 B, 100%, 1 B/s, ETA 0s
# Transferred:            1 / 1, 100%
# Elapsed time:         3.0s
echo 2 > trash
rclone copyto trash remote:trash -P
# Transferred:   	         0 B / 0 B, -, 0 B/s, ETA -
# Checks:                 1 / 1, 100%
# Elapsed time:         1.5s
```

## Some investigations
It seems that if the `webdav` server supports neither `md5sum` nor `sha1sum`, rclone will determine whether the files are identical according to their sizes, [source code: webdav.go](https://github.com/rclone/rclone/blob/v1.60.1/backend/webdav/webdav.go#L1126).
```bash
rclone md5sum remote:trash
# 2024/08/23 15:31:44 ERROR : trash: hash unsupported: hash type not supported
# 2024/08/23 15:31:44 Failed to md5sum with 2 errors: last error was: hash unsupported: hash type not supported
rclone sha1sum remote:trash
# 2024/08/23 15:32:04 ERROR : trash: hash unsupported: hash type not supported
# 2024/08/23 15:32:04 Failed to sha1sum with 2 errors: last error was: hash unsupported: hash type not supported
```

# Request
I think maybe rclone could also check the modification time for webdav backend? Or could rclone provide a `force` option?

```bash
rclone lsl remote:trash
#        2 2024-08-23 15:27:53.000000000 trash
```

**Comment by kapitainsky** [comment]
1. Github is for bugs and enhancements tracking only - support issues please use https://forum.rclone.org/
2. You are using old and custom version or rclone - test with the latest rclone otherwise there is no point to investigate anything

**Comment by ncw** [comment]
And I'd add

3. Use the [--update flag](https://rclone.org/docs/#u-update) for backends which don't support setting modification time (like plain webdav) but do record the time files are uploaded.

I'm going to close this as I don't think it is something we need to fix, but if you do thing there is a bug @pseudocc I will open of course.

Thank you

**Comment by pseudocc** [comment]
@ncw Thanks! The `--update` does help!

The rclone from Ubuntu did not show the `--update` flags from `rclone copyto --help`, actually it does not show anything useful. May be they did a bad job on packaging, thanks anyway.
