### ISSUE TITLE
rsync.net isn't listed on the cloud storage providers?

### ISSUE THREAD

**Issue by justinclift** [rclone/rclone#8038]
#### What is the problem you are having with rclone?

Trying to determine if rsync.net is still a "supported" option with rclone.

There's an [older issue](https://github.com/rclone/rclone/issues/3254) about explicit support being added.  Discussion [in that issue](https://github.com/rclone/rclone/issues/3254#issuecomment-501765997) indicates that rsync.net should be on the list of cloud providers.

However when looking at the list of cloud providers today, there's no mention of rsync.net.

Has something happened, or support been removed, etc?

#### What is your rclone version (output from `rclone version`)

n/a

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Proxmox.  It's based upon Debian 12.

#### Which cloud storage system are you using? (e.g. Google Drive)

Potentially rsync.net.

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

None yet.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
rsync.net is listed as a provider on the sftp page https://rclone.org/sftp/

It is not on the list of supported providers though which is an oversight - I'll add it now.

**Comment by justinclift** [comment]
Cool, that's reassuring.  Thanks heaps @ncw. :smile:

**Comment by ncw** [comment]
I've added rsync.net (and Hetzner storage box which was also missing) to the main README.md of the project on github and the docs page. It was in all the other places it should be.

These changes will go live when 1.68 is released but you can see a preview tomorrow at https://tip.rclone.org

Thank you for reporting.

**Comment by justinclift** [comment]
@rsyncnet Not sure if your account on GitHub is still active, but if so then this is probably relevant to you. :smile:
