### ISSUE TITLE
Fish shell completions error

### ISSUE THREAD

**Issue by dskrad** [rclone/rclone#8055]
I have used the command genautocomplete and the completions file is in my config folder.

Whenever I try to invoke the rclone command and hit tab for completions, I get the following:

```
rclone copy (standard_in) 1: syntax error
test: Missing argument at index 2
(standard_in) 1: syntax error
(standard_in) 1: syntax error
test: Missing argument at index 2
test: Missing argument at index 2
(standard_in) 1: syntax error
(standard_in) 1: syntax error
test: Missing argument at index 2
test: Missing argument at index 2
```

Using fish version 2.7.1 (latest available from my repo)

Not sure what is wrong with my fish shell, since I have no other plugins installed.

**Comment by ncw** [comment]
What version of rclone are you using?

How did you generate the completions?

**Comment by dskrad** [comment]
I just upgraded to fish 3.7.1 and the completions work.
