### ISSUE TITLE
v1.68.0 Docker image build failed

### ISSUE THREAD

**Issue by ttionya** [rclone/rclone#8062]
#### What is the problem you are having with rclone?

v1.68.0 Docker image build failed. Detailed logs at https://github.com/rclone/rclone/actions/runs/10761410173.

Can it be rebuilt?

#### What is your rclone version (output from `rclone version`)

v1.68.0

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I think this is the error

```
#48 [linux/arm64 builder 5/6] RUN   CGO_ENABLED=0   make
#48 205.2 # cd /go/src/github.com/rclone/rclone; git status --porcelain
#48 205.2 fork/exec /usr/bin/git: invalid argument
#48 205.2 error obtaining VCS status: fork/exec /usr/bin/git: invalid argument
#48 205.2 	Use -buildvcs=false to disable VCS stamping.
#48 205.3 make: *** [Makefile:54: rclone] Error 1
#48 ERROR: process "/bin/sh -c CGO_ENABLED=0   make" did not complete successfully: exit code: 2
```

Not really sure what caused that. That error message `-buildvcs=false to disable VCS stamping.` is a message from the go compiler

Why did it stop working? Was it because we went to go1.23 from go1.22?

Or maybe something simpler like `git` being missing from the build image, or a wrong architecture git.

I suspect changing to docker/build-push-action@v6 like we use for the beta build rather than https://github.com/ilteoood/docker_buildx which we use for historical reasons will fix the problem.

Any thoughts?

In the mean time I can build the docker image manually...

**Comment by ttionya** [comment]
Hi @ncw ,

Thank you for your response.

I forked the project and tried the following:

1. No modifications (**failed**, [logs](https://github.com/ttionya/rclone/actions/runs/10829568358))
2. Using the git version that was used before, git=v2.45.2-r0 (**failed**, [logs](https://github.com/ttionya/rclone/actions/runs/10829665679))
3. Not building to `linux/arm64` platform (**failed**, [logs](https://github.com/ttionya/rclone/actions/runs/10829832178))
4. Building with `golang:1.22-alpine` (**not failed, still building**, [logs](https://github.com/ttionya/rclone/actions/runs/10829985018))

Based on these attempts, I believe the compilation error only occurs with the latest version of Golang (v1.23). However, I am not familiar with Golang and cannot troubleshoot the root cause of the error.

Since the master branch already includes the content of `v1.69`, I think manually building `v1.68` is a good option.

**Comment by ncw** [comment]
@ttionya fantastic testing - thank you :-)

I just tried a very similar change on my test rig and that seems to work, so I think I will merge yours - thank you!

**Comment by ncw** [comment]
I have pushed 1.68 up to docker hub now :-)

**Comment by ttionya** [comment]
Thank you for your response.

I noticed that the new `v1.68` image is missing the build for the `linux/arm/v6` platform. Is there an issue with it?

**Comment by ncw** [comment]
Thanks @ttionya - my manual build instructions were out of date :-(

I've kicked that build off now - it should arrive shortly :crossed_fingers:

**Comment by ttionya** [comment]
@ncw ,

Oh, Docker Hub does not support incremental builds. Now it only has the build for the `linux/arm/v6` platform (https://hub.docker.com/r/rclone/rclone/tags).

You need to pass all target platforms in the `platform` option, like this: `--platform linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6`.

**Comment by ncw** [comment]
Thanks @ttionya - I did not know that. I've fixed that now :-)

**Comment by ttionya** [comment]
Now everything looks good. Thank you very much.
