### ISSUE TITLE
Backblaze with Crypt

### ISSUE THREAD

**Issue by JohnRobson** [rclone/rclone#8070]
This is my config file and the command, I tested several different ways and only this one worked.

1) necessary to inform the Bucket name on the config file
```
# rclone.conf
[backblaze]
type = b2
account = 123...
key = 321..
hard_delete = true

[backblaze-crypt]
type = crypt
remote = backblaze:MyBucket # <- mandatory to inform the Bucket name here
filename_encryption = standard
directory_name_encryption = true
```
2) necessary to put a colon in the command
```
$ rclone sync SRC backblaze-crypt: # <- notice the "colon" at the end
```

What I was expecting to be the correct way:
1) Config without a pre-selected Bucket name.
```
[backblaze-crypt]
type = crypt
remote = backblaze # <- only inform the remote without any bucket name
```
2) Buckets names on the commands, so, I can use the same Config settings for different buckets.
```
$ rclone sync SRC backblaze-crypt:MyBucket # <- inform the bucket in the command.
$ rclone sync SRC backblaze-crypt:MyBucket2
$ rclone sync SRC backblaze-crypt:MyBucket3
```

But this one and other variations won't work. I think this is a bug, please, let me know.  Thanks.
(rclone 1.67.0-1 on ArchLinux)

* an extra info: "$ rclone sync SRC backblaze:MyBucket" works perfectly, the problem is when using the "crypt" config.

**Comment by Animosity022** [comment]
For general questions, please use the forums.

https://forum.rclone.org
