### ISSUE TITLE
`--rc-addr` argument for rc command not functioning as expected in v1.68.0

### ISSUE THREAD

**Issue by wiserain** [rclone/rclone#8073]
#### The associated forum post URL from `https://forum.rclone.org`

https://forum.rclone.org/t/possible-bug-with-rclone-rc-vfs-refresh-command/47678

#### What is the problem you are having with rclone?

`--rc-addr` argument seems broken in the latest release v1.68.0. If you it is replaced by `--url`, it works fine. Please see the details in the forum thread.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.68.0
- os/version: ubuntu 24.04 (64 bit)
- os/kernel: 6.5.0-1027-oracle (aarch64)
- os/type: linux
- os/arch: arm64 (ARMv8 compatible)
- go/version: go1.23.1
- go/linking: static
- go/tags: none
```

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

ubuntu amd64

#### Which cloud storage system are you using? (e.g. Google Drive)

all backends

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```bash
rclone rc vfs/refresh --rc-addr=localhost:portNum
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

Please see forum link.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
This is working now with [the latest beta](https://beta.rclone.org/) - it was fixed by 874d66658ed3e614b8073b29299321be200a4d21 which I just merged to master.

I didn't realise this was the same issue as #8063 but the problem was the encoding of `stringArray` values which the above commit fixed.
