### ISSUE TITLE
Consider building rclone and tests with Bazel

### ISSUE THREAD

**Issue by dmcardle** [rclone/rclone#8093]
Hey @ncw, have you thought about building rclone with Bazel before?

First off, the primary *disadvantage* is that Bazel has a very steep learning curve. If you're not already familiar with it, maybe it's not worth the investment and additional complexity.

It has a number of really nice properties:

* Sandboxing.
  * While writing tests in cmd/gitannex/, I've occasionally found my buggy code creating files in surprising places, due to mangled paths/filenames. If we could run tests with Bazel, they'd be automatically sandboxed. Attempts to write files outside the sandbox would crash the test! (You can also relax the sandboxing as needed, but it's a nice default.)
  * Sandboxed builds would also help with bugs like #8092.
  * Another use case: the gitannex e2e tests require an up-to-date `rclone` binary. Currently, we just do our darnedest and [check the version output](https://github.com/rclone/rclone/blob/f8d782c02de5e42c354f281b4f32c4128fa5db1e/cmd/gitannex/e2e_test.go#L21-L24) of whichever `rclone` we find. We could actually write this dependency explicitly with Bazel and drop the heuristic. (That is, the test target, `//cmd/gitannex:gitannex_test`, would explicitly depend on the rclone binary, `//:rclone`.)

* Faster builds. Bazel is extremely good at caching. If you configure a disk cache, you would wait approximately zero seconds to build a binary that you already built months ago. This is super useful when you're bouncing back and forth between commits while debugging. (It also caches test results!)
  * More generally, Bazel enables [hermetic builds](https://bazel.build/basics/hermeticity). Perhaps we trust the go toolchain enough that binaries don't have to match byte-for-byte, but it's a nice property to have that the same inputs produce the same outputs.

* You can also use Bazel to pull in arbitrary dependencies.
  * This is a sort of half-baked idea, but I'm imagining some of the Azure pipelines stuff, which can only run in the cloud, could be Bazelified to enable running it locally.
  * We could pull in specific releases of git-annex and [git-annex-remote-rclone](https://github.com/git-annex-remote-rclone/git-annex-remote-rclone) for e2e and compat testing. Maybe not the highest priority, but I hope it illustrates the capability.

I recently discovered that [Gazelle](https://github.com/bazelbuild/bazel-gazelle) is a thing — it can mostly automatically generate the necessary `BUILD` files for a Go project. It's pretty neat and does a lot of tedious work, but it's not 100% automatic (I tried!).

**Comment by ncw** [comment]
> First off, the primary _disadvantage_ is that Bazel has a very steep learning curve. If you're not already familiar with it, maybe it's not worth the investment and additional complexity.

I have to say one of the things I like about Go is that its build and test system works well and doesn't require any config. (I guess you could think of `go.mod` as its config). That is one of the reasons I've been avoiding CGO dependencies as it breaks that nice cross compiling build system.

> It has a number of really nice properties:
[snip]

Those are certainly nice properties :-)

I do worry about the complexity though. I essentially maintain the build and testing system myself. I get lots of help with other bits of code but not so much with that.

There is quite a lot to the build and testing of rclone

- The [Makefile](https://github.com/rclone/rclone/blob/master/Makefile) for general purpose actions controller (used as a shell script with actions really!)
- [bin/cross-compile.go](https://github.com/rclone/rclone/blob/master/bin/cross-compile.go) for the release builder
- The [github actions](https://github.com/rclone/rclone/tree/master/.github/workflows) which do the actual building and the unit testing and docker stuff
- [The integration test server](https://github.com/rclone/integration-test) which does the integration testing.

Starting over with a new build system would potentially break all of that and fixing the build system is definitely one of those boring but important tasks that I'd rather avoid!

I have a feeling using Bazel would raise the barrier to entry to the project and I've always tried to keep that as low as possible.

So I have to say I'm not feeling positive about this idea, but I'd be interested to hear what you have to say.

**Comment by dmcardle** [comment]
> I have to say one of the things I like about Go is that its build and test system works well and doesn't require any config.

I think that with [Gazelle](https://github.com/bazelbuild/bazel-gazelle), the go.mod file remains the source of truth.  In theory, you just run Gazelle to synchronize the BUILD files whenever go.mod changes or you add/remove go sources. Of course, in practice, there *will* be hiccups that require some expertise to deal with.

> Starting over with a new build system would potentially break all of that and fixing the build system is definitely one of those boring but important tasks that I'd rather avoid!

Yeah, I get that! It would be foolish not to acknowledge that new tech brings new risks. I will point out that Bazel doesn't preclude you from having a Makefile. In fact, you can continue using `go build` / `go test` without Bazel ever finding out :P 

> I have a feeling using Bazel would raise the barrier to entry to the project and I've always tried to keep that as low as possible.

Bazel is a lot of things, but simple is not one of them.

> So I have to say I'm not feeling positive about this idea, but I'd be interested to hear what you have to say.

Overall, I think this is a totally valid opinion, and I won't push the issue! If at some point you want help with Bazel, let me know.

**Comment by ncw** [comment]
Thanks for the discussion @dmcardle - always good to look at new things which could help us.
