### ISSUE TITLE
Mounting a wasabi bucket leads to Netdata reporting all 1BN inodes "in use"

### ISSUE THREAD

**Issue by walt93** [rclone/rclone#8107]
#### The associated forum post URL from `https://forum.rclone.org`

A search on the forum suggests this may be the same issue as reported in 2018 (?) 

https://forum.rclone.org/t/inode-usage-maxed-out/4872

#### What is the problem you are having with rclone?

I have mounted a Wasabi bucket, and doing so causes my system to report all 1BN inodes as being used, Netdata is sending scary looking errors as a result. Things appear to be working, just, Netdata is having a fit.

![Screenshot 2024-09-26 at 11 53 33 AM](https://github.com/user-attachments/assets/303add18-e86b-4255-ae39-37ba83b2dc78)

#### What is your rclone version (output from `rclone version`)

I was on v1.53.3-DEV and immediately recognized that could be the issue, so I updated to v1.68.1 and the issue did not change.

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Ubuntu 22.04.5 LTS (jammy), 64-bit
e.g.
Linux pyron 5.15.0-112-generic #122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

#### Which cloud storage system are you using? (e.g. Google Drive)

Wasabi

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

`rclone mount truthcraft-ai:truthcraft-ai /mnt/truthcraft --daemon
`

tried variants like

`rclone mount truthcraft-ai:truthcraft-ai /mnt/truthcraft --daemon --attr-timeout 1h --dir-cache-time 1h --vfs-cache-mode full --stats 1s --vfs-read-chunk-size 1M --buffer-size 32M
`

and there is no change in behavior vis a vis inodes.

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
$ rclone mount truthcraft-ai:truthcraft-ai /mnt/truthcraft --daemon -vv
2024/09/26 18:44:53 DEBUG : rclone: Version "v1.68.1" starting with parameters ["rclone" "mount" "truthcraft-ai:truthcraft-ai" "/mnt/truthcraft" "--daemon" "-vv"]
2024/09/26 18:44:53 DEBUG : Creating backend with remote "truthcraft-ai:truthcraft-ai"
2024/09/26 18:44:53 DEBUG : Using config file from "/home/ubuntu/.config/rclone/rclone.conf"
2024/09/26 18:44:53 DEBUG : rclone: Version "v1.68.1" finishing with parameters ["/usr/bin/rclone" "mount" "truthcraft-ai:truthcraft-ai" "/mnt/truthcraft" "--daemon" "-vv"]

ubuntu@pyron:~/truthcraft_mk2$ df -i /mnt/truthcraft
Filesystem                      Inodes IUsed      IFree IUse% Mounted on
truthcraft-ai:truthcraft-ai 1000000000     0 1000000000    0% /mnt/truthcraft

ubuntu@pyron:~/truthcraft_mk2$ sudo umount /mnt/truthcraft

ubuntu@pyron:~/truthcraft_mk2$ df -i /mnt/truthcraft
Filesystem       Inodes   IUsed    IFree IUse% Mounted on
/dev/md3       58466304 4174549 54291755    8% /

$ cat /home/ubuntu/.config/rclone/rclone.conf
[socialfoo]
type = s3
provider = Wasabi
env_auth = false
access_key_id = SECRET
secret_access_key = SECRET
region = us-central-1
endpoint = s3.us-central-1.wasabisys.com

[truthcraft-ai]
type = s3
provider = Wasabi
env_auth = false
access_key_id = SECRET
secret_access_key = SECRET
region = us-east-1
endpoint = s3.us-east-1.wasabisys.com
```

I note that the socialfoo mount point has been live for probably almost a year (whenever we installed 1.5.3DEV) and has never had any issues. I added the truthcraft mount point yesterday and the "billion inodes" problem started. The truthcraft-ai bucket is a new deploy and has only 17 files on it.

Here's some more log output that I think nails where the issue is coming from:

```
$ rclone mount truthcraft-ai:truthcraft-ai /mnt/truthcraft --daemon --log-file=/tmp/rclone-truthcraft.log --log-level DEBUG
ubuntu@pyron:~/truthcraft_mk2$ df -i /mnt/truthcraft
Filesystem                      Inodes      IUsed IFree IUse% Mounted on
truthcraft-ai:truthcraft-ai 1000000000 1000000000     0  100% /mnt/truthcraft
ubuntu@pyron:~/truthcraft_mk2$ cat /tmp/rclone-truthcraft.log
2024/09/26 18:33:45 DEBUG : rclone: Version "v1.53.3-DEV" starting with parameters ["rclone" "mount" "truthcraft-ai:truthcraft-ai" "/mnt/truthcraft" "--daemon" "--log-file=/tmp/rclone-truthcraft.log" "--log-level" "DEBUG"]
2024/09/26 18:33:45 DEBUG : Creating backend with remote "truthcraft-ai:truthcraft-ai"
2024/09/26 18:33:45 DEBUG : Using config file from "/home/ubuntu/.config/rclone/rclone.conf"
2024/09/26 18:33:45 DEBUG : rclone: Version "v1.53.3-DEV" finishing with parameters ["rclone" "mount" "truthcraft-ai:truthcraft-ai" "/mnt/truthcraft" "--daemon" "--log-file=/tmp/rclone-truthcraft.log" "--log-level" "DEBUG"]
2024/09/26 18:33:45 DEBUG : rclone: Version "v1.53.3-DEV" starting with parameters ["rclone" "mount" "truthcraft-ai:truthcraft-ai" "/mnt/truthcraft" "--daemon" "--log-file=/tmp/rclone-truthcraft.log" "--log-level" "DEBUG"]
2024/09/26 18:33:45 DEBUG : Creating backend with remote "truthcraft-ai:truthcraft-ai"
2024/09/26 18:33:45 DEBUG : Using config file from "/home/ubuntu/.config/rclone/rclone.conf"
2024/09/26 18:33:45 INFO  : S3 bucket truthcraft-ai: poll-interval is not supported by this remote
2024/09/26 18:33:45 DEBUG : S3 bucket truthcraft-ai: Mounting on "/mnt/truthcraft"
2024/09/26 18:33:45 DEBUG : : Root:
2024/09/26 18:33:45 DEBUG : : >Root: node=/, err=<nil>
2024/09/26 18:33:48 DEBUG : /: Attr:
2024/09/26 18:33:48 DEBUG : /: >Attr: attr=valid=1s ino=0 size=0 mode=drwxrwxr-x, err=<nil>
2024/09/26 18:33:48 DEBUG : : Statfs:
2024/09/26 18:33:48 DEBUG : : >Statfs: stat={Blocks:274877906944 Bfree:274877906944 Bavail:274877906944 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>

```

That statfs result appears to be radically bogus, I'd look there first... 

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I'm pretty sure this is fixed already.

Please make sure you stop all the mounts, upgrade rclone, then start them again as some if your logs are from a very old version.

**Comment by Animosity022** [comment]
Answered.
