### ISSUE TITLE
Mega doesn't return 'ls' , Windows

### ISSUE THREAD

**Issue by bootlegcoal** [rclone/rclone#8116]
Hi, thank you for working on this project!! My problem: when using rclone in windows, specifically with mega, it won't return any directory information. I've tried rclone/mega on a linux computer and it worked fine. rclone with SFTP on windows and that works fine. It's only mega + windows. Thank you!

rclone v1.68.1
Microsoft Windows 11 Pro 23H2 (64 bit), 10.0.22631.4169 (x86_64)
Mega.nz
command: `rclone ls mega:`

Not sure if this is relevant, but I'm running rclone from my C:\Windows\system32 folder.
Also tested with latest beta (from a user directory, not sys32), same result.

log output doesn't say much. This is the beta but the stable version was the same.
2024/10/05 07:36:10 DEBUG : rclone: Version "v1.69.0-beta.8363.4db09331c" starting with parameters ["C:\\Users\\m\\Downloads\\rclone-beta-latest-windows-amd64\\rclone-v1.69.0-beta.8363.4db09331c-windows-amd64\\rclone.exe" "lsd" "mega-beta:" "-vv" "--log-file" "bug.log"]
2024/10/05 07:36:10 DEBUG : Creating backend with remote "mega-beta:"
2024/10/05 07:36:10 DEBUG : Using config file from "C:\\Users\\m\\AppData\\Roaming\\rclone\\rclone.conf"

**Comment by kapitainsky** [comment]
Please double check what you are doing - you once talk about `rclone ls` then show log from `rclone lsd`.

All works on Windows with mega:

```
PS C:\Users\kptsky> rclone --version
rclone v1.68.1
- os/version: Microsoft Windows 11 Pro 23H2 (64 bit)
- os/kernel: 10.0.22631.4169 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.23.1
- go/linking: static
- go/tags: cmount

PS C:\Users\kptsky> rclone config redacted mega:
[mega]
type = mega
user = XXX
pass = XXX

PS C:\Users\kptsky> rclone lsd mega:
          -1 2023-12-12 09:41:46        -1 dir1
          -1 2024-08-23 17:14:55        -1 dir2
```
