### ISSUE TITLE
Nit in Google Oauth Setup

### ISSUE THREAD

**Issue by randyqx** [rclone/rclone#8129]
in [https://rclone.org/drive/#making-your-own-client-id](https://rclone.org/drive/#making-your-own-client-id)
step 9 says "If you selected "External" at Step 5 continue to Step 9."  i believe that should be "Continue to Step 10."  Similarly, "can skip straight to Step 10" should be "can skip straight to Step 11."

**Comment by kapitainsky** [comment]
It indeed would be nice if somebody corrects these inconsistencies in docs (PR welcomed). Docs can be always made better.
