### ISSUE TITLE
Unix socket permision of serve webdav

### ISSUE THREAD

**Issue by URenko** [rclone/rclone#8141]
#### What is your current rclone version (output from `rclone version`)?

```
rclone v1.68.1
- os/version: debian 12.6 (64 bit)
- os/kernel: 6.1.0-23-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.23.1
- go/linking: static
- go/tags: none
```

#### What problem are you are trying to solve?

The default permission of the Unix socket for serve webdav is `srwxr-xr-x`, which cannot be read by other users (e.g. nginx).
See a similar discussion of uvicorn: https://github.com/encode/uvicorn/issues/337

#### How do you think rclone should be changed to solve that?

Consider set the default permission to 0666

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> Consider set the default permission to 0666

This is controlled by the `umask` of the process which creates the socket

```
$ umask 0002
$ rclone serve webdav . --addr unix://webdav.sock
2024/10/22 21:02:48 NOTICE: Local file system at /home/ncw/Go: WebDav Server started on []
```

```
$ ls -l /tmp/webdav.sock
srwxrwxr-x 1 ncw ncw 0 Oct 22 21:03 /tmp/webdav.sock
```

```
$ umask 0000
$ rclone serve webdav . --addr unix:///tmp/webdav.sock
2024/10/22 21:03:14 NOTICE: Local file system at /home/ncw/Go: WebDav Server started on []
```

```
$ ls -l /tmp/webdav.sock
srwxrwxrwx 1 ncw ncw 0 Oct 22 21:03 /tmp/webdav.sock
```
