### ISSUE TITLE
help

### ISSUE THREAD

**Issue by sec13b** [rclone/rclone#8146]
I just want copy from windows pc "C:\work\" in vps server "/root/backups/upload"
I post here , because "Rclone Forum Community Support"  delete instant the post.

Configuration rclone.conf on "C:\Users\test\AppData\Roaming\rclone"

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[linux]
type = sftp
host = 192.168.12.123
user = root
pass = XXX
key_file_pass = XXX
use_insecure_cipher = true
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

first command :

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rclone copy C:\work\ st:"/root/backups/upload" --max-age 1y --exclude-from exclude.txt -q --ignore-existing --auto-confirm --multi-thread-streams 25 --transfers 25 –P
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CRITICAL: Failed to create file system for "st:/root/backups/upload": didn't find section in config file

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rclone.exe copy C:\work\ linux:/root/backups/upload --sftp-ssh "ssh root@192.168.12.123" --sftp-path-override /volume1/backups/upload
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
NOTICE: linux{58IlU}: --sftp-ssh is in use - ignoring user/host/port from config - set in the parameters to --sftp-ssh (remove them from the config to silence this warning)
The authenticity of host '192.168.12.123 (192.168.12.123)' can't be established.
ECDSA key fingerprint is SHA256:u3ABLH/k3garCCSPRU/5Shxq37EuiwEoc/HguC5fNcg.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rclone copy "C:\work\" linux:root/test/upload
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024/10/23 01:03:32 CRITICAL: Failed to create file system for "linux:root/test/upload": NewFs: couldn't connect SSH: dial tcp 192.168.12.123: connectex: No connection could be made because the target machine actively refused it.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rclone lsd linux:/
          -1 2013-03-20 18:52:40        -1 backups
          -1 2016-06-25 12:10:44        -1 bin
          -1 2016-06-25 12:14:15        -1 boot
          -1 2021-12-04 12:53:44        -1 dev
          -1 2013-02-28 21:32:05        -1 downloads
          -1 2022-08-20 11:19:58        -1 etc
          -1 2021-11-05 08:50:22        -1 home
          -1 2016-06-25 12:10:41        -1 lib
          -1 2016-06-25 12:07:10        -1 lib64
          -1 2012-05-01 14:11:53        -1 lost+found
          -1 2012-05-01 14:11:59        -1 media
          -1 2012-04-19 02:32:07        -1 mnt
          -1 2012-05-01 14:14:53        -1 opt
          -1 2021-12-04 12:53:32        -1 proc
          -1 2024-10-23 01:11:37        -1 root
          -1 2024-10-23 01:41:20        -1 run
          -1 2016-06-25 12:11:32        -1 sbin
          -1 2012-03-05 09:54:30        -1 selinux
          -1 2012-05-01 14:14:53        -1 srv
          -1 2021-12-04 12:53:32        -1 sys
          -1 2024-10-23 01:39:01        -1 tmp
          -1 2012-05-01 14:14:53        -1 usr
          -1 2024-05-13 22:09:39        -1 var
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

can someone help me .
Thank you in advance

**Comment by ncw** [comment]
> I post here , because "Rclone Forum Community Support" delete instant the post.

Unfortunately the spam checker is sometimes a bit too vigorous.

> ```
> rclone.exe copy C:\work\ linux:/root/backups/upload --sftp-ssh "ssh root@192.168.12.123" --sftp-path-override /volume1/backups/upload
> ```
> 
> NOTICE: linux{58IlU}: --sftp-ssh is in use - ignoring user/host/port from config - set in the parameters to --sftp-ssh (remove them from the config to silence this warning)
> The authenticity of host '192.168.12.123 (192.168.12.123)' can't be established.
> ECDSA key fingerprint is SHA256:u3ABLH/k3garCCSPRU/5Shxq37EuiwEoc/HguC5fNcg.

This looked like it nearly worked.

Do `ssh root@192.168.12.123` first from the command line then accept the warnings, then try this again.

Get listing working first before attempting a file transfer

    rclone.exe lsf --sftp-ssh "ssh root@192.168.12.123" --sftp-path-override /volume1/backups/upload

> ```
> rclone copy "C:\work\" linux:root/test/upload
> ```
> 
> 2024/10/23 01:03:32 CRITICAL: Failed to create file system for "linux:root/test/upload": NewFs: couldn't connect SSH: dial tcp 192.168.12.123: connectex: No connection could be made because the target machine actively refused it.

I would have thought this should work - is there some kind of proxy in use?

**Comment by ncw** [comment]
Please answer the questions above and try the things I asked you to - thank you
