### ISSUE TITLE
support remote move across filesystems/storages

### ISSUE THREAD

**Issue by ghost** [rclone/rclone#8162]
#### What is your current rclone version (output from `rclone version`)?
rclone v1.68.1
- os/version: Microsoft Windows 11 Pro 23H2 (64 bit)
- os/kernel: 10.0.22631.4391 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.23.1
- go/linking: static
- go/tags: cmount

#### What problem are you are trying to solve?

rclone sftp can not move file across filesystems (SSH_FX_FAILURE)

#### How do you think rclone should be changed to solve that?

rclone sftp falls back to remote copy and then delete the original file

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by albertony** [comment]
I think what you describe would be covered by this?
- https://github.com/rclone/rclone/issues/6624

**Comment by albertony** [comment]
> I think what you describe would be covered by this?

Or maybe that is a bit different.... 😔 

Rclone's sftp backend should already support server-side move, as long as the server reports support for the relevant extension, from what I can see in code:

https://github.com/rclone/rclone/blob/b9207e57274cd6e7c488c5bd751a058ba0f8b3b9/backend/sftp/sftp.go#L1472-L1481


Which server are accessing? Are you sure it supports this extension?

**Comment by ncw** [comment]
If you use --disable Move then rclone will do a copy/delete instead of trying to do a server side move.

If we could reliably detect the error condition then we could do that automatically.

**Comment by ncw** [comment]
Yes it should do
