### ISSUE TITLE
base64解码错误

### ISSUE THREAD

**Issue by hackerheiye** [rclone/rclone#8169]
2024/11/09 17:00:51 CRITICAL: Failed to create file system for "sftp:ls": base64 decode failed when revealing password - is it obscured?: illegal base64 data at input byte 6

**Comment by xin1145** [comment]
发生如上问题，系统是win11版本，输入了正确的base64密码还是这样，无法解密编码

**Comment by ncw** [comment]
The password in the config file needs to be obscured.

To obscure it you run

    rclone obscure your password

Then use the output from that in the config file

**Comment by xin1145** [comment]
Thank you for the connection
