### ISSUE TITLE
Config file documentation

### ISSUE THREAD

**Issue by hmbrg** [rclone/rclone#817]
Is there any documentation on the syntax and layout (meaning all available options) of the config file?

**Comment by ncw** [comment]
No there isn't any docs on the config file.  There is a very straight forward mapping from the auto configurator to what goes in the config file so it isn't too hard to figure out, but you are right there aren't any docs on it.

Fancy writing some?

**Comment by AzureBlaze** [comment]
Is it possible to set default flags in the config file, for example drive-use-trash and stats=10s ?

**Comment by qinwf** [comment]
I want to know that too. About how to add "--drive-use-trash" as default. Or I can create a command line alias.

**Comment by ncw** [comment]
@AzureBlaze @qinwf I keep meaning to do that, so I've made an issue about it #850 - please click the subscribe button to be notified of changes there!

**Comment by ncw** [comment]
Note that you can now (if you use the latest beta) set an environment variable "RCLONE_DRIVE_USE_TRASH=true` which is a step in the right direction.

**Comment by AzureBlaze** [comment]
@ncw Setting RCLONE_DRIVE_USE_TRASH=true in my enviroment doesn't seem to have any effect on windows.

**Comment by ncw** [comment]
@AzureBlaze I beleive it should work.  How are you setting the environment variable?

You can see the difference in the help

before

```
$ rclone -h | grep trash
      --drive-use-trash                   Send files to the trash instead of deleting permanently.
```

after

```
$ RCLONE_DRIVE_USE_TRASH=true rclone -h | grep trash
      --drive-use-trash                   Send files to the trash instead of deleting permanently. (default true)
$ 
```

I tried this on Windows with

```
set RCLONE_DRIVE_USE_TRASH=true
```

And it worked for me.

**Comment by AzureBlaze** [comment]
I set it using [this ](https://i.imgur.com/Xnp9YGs.png) interface for enviroment variables. I tried it using the set command and it works for sure, but I find it a bit odd because according to [this](https://technet.microsoft.com/en-us/library/bb490998.aspx) the set command also acts on enviroment variables.

**Comment by AzureBlaze** [comment]
@ncw seems I was wrong it doesn't work even when I use the set command. I tried downloading the latest beta and it works now, seems it just hasn't made it's way to the official release.

**Comment by ncw** [comment]
@AzureBlaze it is scheduled for the 1.36 release so only in beta at the moment.  Glad you made it work.

**Comment by animosity22** [comment]
I think this one is pretty much solved as well as the documentation for the config file is all there. If there is something specific, please just post a message on the forums and we can help out!
