### ISSUE TITLE
Can rclone remove cached objects when the remote had already deleted in mount mode with vfs cache?

### ISSUE THREAD

**Issue by starmoonxp** [rclone/rclone#8178]
As title.
I'm using ftp backend. It may the right time to remove the cached objects when refereshing directory list. No matter the access time of the cached object reached.

**Comment by darthShadow** [comment]
This should already be happening. If that's not the case, then please go to [forum.rclone.org](https://forum.rclone.org/) and create a ticket in the `Help and Support` category. Please answer all questions while opening the ticket.

**Comment by starmoonxp** [comment]
Actually it didn't remove "dead" when there's no purge trigged. (e.g. I set the vfs_cache_max_age=off and vfs_cache_min_free_space=50G options when mounting. )

**Comment by starmoonxp** [comment]
@darthShadow 
I have tested for months and confirmed rclone won't delete dead objects from cache directory when the max_age or min_free_space didn't reach. This could be normal but I prefer to remove these dead ones earlier over other cached valid objects.
Could you reopen this issue?

**Comment by darthShadow** [comment]
It seems to be expected behavior for now due to complexities of the VFS layer: https://github.com/rclone/rclone/issues/4446#issuecomment-725328969

**Comment by starmoonxp** [comment]
@darthShadow 

update: 
It seems that the "purge" process only based on object aging.  It didn't remove objects that was deleted on remote.
(logs "vfs cache: removed cache file as Removing old cache file not in use", no where showing removing "dead" objects. It seems that the those deleted from remove are stalled in cache. )
I'd prefer removing these "dead" objects before purging.  

udpate2:
The "purge" process seems only to be excuted on rclone start.  The remaining free spacing keep going down without a restart of rclone.  (ignore this note, it could be a misconfiguration, i miss spelled "--vfs-cache-poll-interval=10M" which means ten month to poll the cache, it works now as expected when I change it to 10m )

Here is how did I started rclone
rclone mount starmoon:/movie/cine /mnt/movie/cine --read-only --vfs-cache-mode=full --cache-dir=/mnt/cache/ --vfs-cache-max-age=off --vfs-cache-poll-interval=10m --vfs-cache-min-free-space=50G --buffer-size=32M --vfs-read-ahead=256M --use-mmap --vfs-fast-fingerprint --allow-other --copy-links --config=/etc/rclone/rclone.conf --log-file=/var/log/rclone.mount.log --daemon -vv
(the remote is a ftp backend)
