### ISSUE TITLE
Using B2 with Crypt creates unnecessary requests

### ISSUE THREAD

**Issue by tmazur** [rclone/rclone#818]
When copying a directory to B2, with no changes in the directory - 4 requests are sent.

```
    b2_authorize_account
    b2_create_bucket
    b2_list_buckets
    b2_list_file_names
```

However when we setup an encrypted B2 we get 7 requests for the same scenario.

```
    b2_authorize_account
    b2_list_buckets
    b2_list_file_names
    b2_authorize_account
    b2_create_bucket
    b2_list_buckets
    b2_list_file_names
```

Version: rclone v1.33-72-ga4a44a4β
OS: Windows 10 x64
Storage system: B2

Quote from [rclone forum](https://forum.rclone.org/t/inner-workings-of-copy-is-the-server-queried-for-each-file/78/12?u=tmazur):

> rclone had to work out whether object i a file or a directory. It is doing this in an inefficient way at the moment by recreating the Fs. If you make an issue I'll look at fixing it.

**Comment by ncw** [comment]
This might need a new concept in the remote to fix properly - a Chroot call...

**Comment by ivandeex** [comment]
Closing after 4+ years of inactivity

**Comment by gymnae** [comment]
Could this issue be reopened?
