### ISSUE TITLE
resumable SFTP download

### ISSUE THREAD

**Issue by danya0123** [rclone/rclone#8187]
#### The associated forum post URL from `https://forum.rclone.org`

https://github.com/rclone/rclone/issues/87 but that's for upload

#### What problem are you are trying to solve?
resumable SFTP download

#### How do you think rclone should be changed to solve that?
I have tried `` --inplace`` but that doesn't work 

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
In rclone all backends are created equal, so "upload" means writing data to the backend. This means that "upload" to the local backend is really downloading!

Anyway, that is a long winded way of saying that this is covered by #87 already so I'm going to close this.
