### ISSUE TITLE
Request to upgrade to Font Awesome version 6.7.0

### ISSUE THREAD

**Issue by childish-sambino** [rclone/rclone#8198]
#### What problem are you are trying to solve?

We'd like to change the docs icon for the Filescom backend to https://fontawesome.com/icons/files-pinwheel which is available in the latest version of Font Awesome.

#### How do you think rclone should be changed to solve that?

Upgrade to using the latest version of Font Awesome.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Seems like a reasonable request to me :-)

Do you want to have a go at this? I last did it 5 years ago here 93810a739df48db1c6f4bd4b181a572e503ca81c which shows what needs to be done at least!

**Comment by childish-sambino** [comment]
I'm open to it, but not sure if/when I'd have the bandwidth.

**Comment by childish-sambino** [comment]
Looks simple enough. I'll give it a go.

**Comment by childish-sambino** [comment]
Hrm, still showing the old icon at tip.rclone.org
