### ISSUE TITLE
when installed from snap, unable to mount OneDrive

### ISSUE THREAD

**Issue by divinity76** [rclone/rclone#8208]
#### The associated forum post URL from `https://forum.rclone.org`

N/A

#### What is the problem you are having with rclone?

When rclone is installed from snap, it is unable to mount OneDrive.
If rclone is installed from apt or from https://github.com/rclone/rclone/releases `rclone-v1.68.2-linux-amd64.deb` (the *exact* same version that Snap offered during my testing) , OneDrive mount works just fine.

#### What is your rclone version (output from `rclone version`)

`snap install rclone` (broken): 1.68.2
`apt install ./rclone-v1.68.2-linux-amd64.deb` from https://github.com/rclone/rclone/releases  (working): 1.68.2
`apt-get install rclone` (working): 1.60.1

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

WSL-Ubuntu24.04 x64 running on WSL2 running on Windows 10 x64

#### Which cloud storage system are you using? (e.g. Google Drive)

OneDrive

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

```
rclone mount onedrive: /remote/onedrive/ -vvv
```

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

```
$ namei -l /remote/onedrive/
f: /remote/onedrive/
drwxr-xr-x root root /
drwxr-xr-x hans hans remote
drwxr-xr-x hans hans onedrive
$ id
uid=1000(hans) gid=1000(hans) groups=1000(hans),27(sudo),33(www-data),100(users),113(docker)
$ rclone mount onedrive: /remote/onedrive/ -vvv
2024/11/26 20:47:54 DEBUG : rclone: Version "v1.68.2" starting with parameters ["/snap/rclone/522/bin/rclone" "mount" "onedrive:" "/remote/onedrive/" "-vvv"]
2024/11/26 20:47:54 DEBUG : Creating backend with remote "onedrive:"
2024/11/26 20:47:54 DEBUG : Using config file from "/home/hans/snap/rclone/522/.config/rclone/rclone.conf"
2024/11/26 20:47:54 DEBUG : OneDrive root '': Next delta token is: NDslMjM0OyUyMzE7MzszYzA5M2RkNi05YjZiLTQ0YjMtODUzYi1lOTkwYWRhNTMyNjc7NjM4NjgyNDcyNzE5MDAwMDAwOzcxMDQzNzc4MDslMjM7JTIzOyUyMzA7JTIz
2024/11/26 20:47:54 NOTICE: OneDrive root '': --vfs-cache-mode writes or full is recommended for this remote as it can't stream
2024/11/26 20:47:54 CRITICAL: Fatal error: failed to mount FUSE fs: cannot open: /remote/onedrive/: open /remote/onedrive/: no such file or directory
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Animosity022** [comment]
See:

https://rclone.org/install/#snap

**Comment by divinity76** [comment]
@Animosity022 rclone should detect the error condition and give a better error message IMO, something like
```
CRITICAL: mounting is not supported with snap-installed rsync
```
rather than the current
```
2024/11/26 20:47:54 CRITICAL: Fatal error: failed to mount FUSE fs: cannot open: /remote/onedrive/: open /remote/onedrive/: no such file or directory
```
ideally
