### ISSUE TITLE
with --vfs-used-is-size value is calculated and then thrown away

### ISSUE THREAD

**Issue by iscilyas** [rclone/rclone#8220]
I have ssh access to a 500gb quota'd filesystem that I'm mounting using rclone. `df` on the server reports information about the entire disk. I've been trying to use `--vfs-used-is-size` in combination with `--vfs-disk-space-total-size=XXX` but that's giving me garbage values:

```
$ rclone  mount 500gb:/home/ilias/tmp /home/ilias/foo --log-level=DEBUG --vfs-used-is-size
 --vfs-disk-space-total-size=500G
$ du -h /home/ilias/foo
1.5K	/home/ilias/foo
$ df -h /home/ilias/foo
Filesystem             Size  Used Avail Use% Mounted on
500gb:/home/ilias/tmp  500G -224T  224T    - /home/ilias/foo
```
Relevant debug output:
```
2024/12/02 15:02:33 DEBUG : : >Statfs: stat={Blocks:131072000 Bfree:60049752808 Bavail:60049752808 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
```

I did some digging around, and the problem seems to be that in `vfs/vfs.go:Statfs()` we make an About() call, then properly overwrite `used` and `size` based on the command-line arguments, but keep the `free` value returned by the server. The call to `vfs/vfs.go:fillInMissingSizes()` doesn't change `free` (since it's been populated). Later on `used` (which we just spent so much time calculating) is thrown away and `statvfs(3)` returns the `size` (from `vfs-disk-space-total-size`) and the `free` (which we got from the `About()` call), and `used` is calculated (in userland) based on those.

Essentialy, `vfs-used-is-size` is a very very expensive no-op. Note that the problem always exists, and is independent of the backend and not only when used in combination with `vfs-disk-space-total-size`.

The fix is to ignore the `free` value returned by the server in the About() call, and calculate it based on `size` and `used`.

```
diff --git a/vfs/vfs.go b/vfs/vfs.go
index 9f0fc1f14..5fcfe9c4c 100644
--- a/vfs/vfs.go
+++ b/vfs/vfs.go
@@ -650,6 +650,11 @@ func (vfs *VFS) Statfs() (total, used, free int64) {
                total = int64(vfs.Opt.DiskSpaceTotalSize)
        }
 
+       // if we've calculated the "used", then we should calculate the "free"
+       if vfs.Opt.UsedIsSize {
+               free = -1
+       }
+
        total, used, free = fillInMissingSizes(total, used, free, unknownFreeBytes)
        return
 }
```

which results in:

```
$ du -h /home/ilias/foo
1.5K	/home/ilias/foo
$ df -h /home/ilias/foo
Filesystem             Size  Used Avail Use% Mounted on
500gb:/home/ilias/tmp  500G  4.0K  500G   1% /home/ilias/foo
```

With the debug output:

```
2024/12/02 15:06:08 DEBUG : : >Statfs: stat={Blocks:131072000 Bfree:131071999 Bavail:131071999 Files:1000000000 Ffree:1000000000 Bsize:4096 Namelen:255 Frsize:4096}, err=<nil>
```

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
> Essentialy, `vfs-used-is-size` is a very very expensive no-op. Note that the problem always exists, and is independent of the backend and not only when used in combination with `vfs-disk-space-total-size`.

He he! I've always thought of it as very expensive, but it isn't supposed to be a no-op!

Do you want to send a PR with a proposed fix?

**Comment by iscilyas** [comment]
> Do you want to send a PR with a proposed fix?

:) just did....

**Comment by iscilyas** [comment]
TBH if both `--vfs-used-is-size` and `--vfs-disk-space-total-size=XXX` are specified we *could* skip the `About()` call, since we're essentially ignoring what it returns. But I figured since we're just about to a recursive filetree walk over the network, who cares if we do an unnecessary `About()` call.... I don't know if it's worth the code clutter. (I guess it would depend on whether `About()` is expensive for some backends).

**Comment by iscilyas** [comment]
You know... speaking of `--vfs-used-is-size` being so expensive... at least with `sftp` it could be a *lot* cheaper if we just did a `du | tail -1` on the server instead of the recursive filetree walk over the network (i see there's already code to run `df -k` on the server if `vfsstat` isn't supported).... But that would probably require change to the backend interface to export a `Size()` in addition to an `About()`, and I don't know if other backends would have similar shortcuts or it would end up being a one-off for sftp....

**Comment by iscilyas** [comment]
> Actually I was surprised to see we called About at all - generally this gets used on backends with no About call.

:) ah i see... so maybe my assertion that "this is broken on all backends" is incorrect... if no About() call is made, it should be correct as it is

> Skipping the About if both `--vfs-used-is-size` and `--vfs-disk-space-total-size=XXX` are specified seems like a reasonable idea.
> 
> > But I figured since we're just about to a recursive filetree walk over the network, who cares if we do an unnecessary `About()` call.... I don't know if it's worth the code clutter. (I guess it would depend on whether `About()` is expensive for some backends).
> 
> Well there is that! And no, About is a single call on all backends otherwise it doesn't get implemented.

so... what's the verdict? is the code clutter justified?

**Comment by ncw** [comment]
> You know... speaking of `--vfs-used-is-size` being so expensive... at least with `sftp` it could be a _lot_ cheaper if we just did a `du | tail -1` on the server instead of the recursive filetree walk over the network (i see there's already code to run `df -k` on the server if `vfsstat` isn't supported).

That could be an option in the sftp backend quite easily to use du instead of df to implement the About call?
