### ISSUE TITLE
Proposal: Disable Unicode Normalization by Default in rclone

### ISSUE THREAD

**Issue by narfa0215** [rclone/rclone#8223]
#### What is the problem you are having with rclone?

In some file systems, especially those involving multiple language character sets (such as Chinese, Japanese, etc.), Unicode normalization can cause unexpected character transformations. For example, Chinese punctuation marks (such as ！) may be converted to their English equivalents (!). This transformation affects file comparisons and synchronization, especially when precise file name matching is required.

Currently, rclone has Unicode normalization enabled by default, which can cause unexpected behavior in certain cases.

Unicode normalization may cause certain special characters (such as full-width Chinese punctuation) to be converted into their half-width equivalents (such as English punctuation), resulting in incorrect file name comparisons and operations. For example:

Chinese exclamation mark (！) is converted to English exclamation mark (!).
Other full-width and half-width character discrepancies can also be affected.
This is particularly problematic when exact file name matching is necessary, especially when file systems use different character sets.

#### What is your rclone version (output from `rclone version`)

rclone v1.68.2
- os/version: slackware 15.0+ (64 bit)
- os/kernel: 6.1.106-Unraid (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.23.3
- go/linking: static
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Unraid 64 bit

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by kapitainsky** [comment]
> Unicode normalization may cause certain special characters (such as full-width Chinese punctuation) to be converted into their half-width equivalents (such as English punctuation)

I think it is more about characters encoding

https://rclone.org/overview/#encoding

which unfortunately many years ago was designed to use some full width characters as substitutes.

It is unfortunate legacy we have to live with. It can NOT be changed now - it would break all rclone instances relying on it.

Good think is that it is configurable and maybe rclone docs should have make it more clear in what cases it is advisable (with examples).

**Comment by ncw** [comment]
The reason rclone does normalisation by default is macOS.

macOS used to, maybe still does keep denormalised utf as it's file names. That made the unicode normalisation essential.

I'm not a Mac user so I'd like to hear what the story is today.

I don't think this is related to the character substitution scheme, but that certainly doesn't help CJK languages.

**Comment by kapitainsky** [comment]
Normalisation does not change characters - full width character won't become half width because normalisation was applied. But rclone encoding does it.

macOS APFS filesystem does not normalise but various macOS APIs do. The challenge with macOS is that it uses NFD flavour of normalisation vs rest of the world using NFC. In addition it does not do this consistently creating issues unheard on other platforms. Example [here](https://eclecticlight.co/2021/05/08/explainer-unicode-normalization-and-apfs/) of issues caused by normalisation differences.
