### ISSUE TITLE
misleading usage help for rclone serve restic with TLS

### ISSUE THREAD

**Issue by Framsfex** [rclone/rclone#8232]
#### What is the problem you are having with rclone?

I am using rclone (only) as a restic server backend, with TLS.
"rclone serve restic -h" says:

```
`--cert` should be either a PEM encoded certificate or a concatenation
of that with the CA certificate.  `--key` should be the PEM encoded
private key and `--client-ca` should be the PEM encoded client 
certificate authority certificate.
(...)
 --cert string                     SSL PEM key (concatenation of certificate and CA certificate)
 --client-ca string                Client certificate authority to verify clients with
 --key string                      SSL PEM Private key
```

This is misleading, because the argument of these options must be a filename and not a PEM string!
 It should read:

```
`--cert` should be either a file containing a PEM encoded certificate or a concatenation
of that with the CA certificate.  `--key` should be a file containing the PEM encoded
private key and `--client-ca` should be a file containing the PEM encoded client 
certificate authority certificate.
(...)
 --cert file                     SSL PEM key (concatenation of certificate and CA certificate)
 --client-ca file                Client certificate authority to verify clients with
 --key file                      SSL PEM Private key
```

#### What is your rclone version (output from `rclone version`)

rclone v1.60.1-DEV
- os/version: ubuntu 24.04 (64 bit)
- os/kernel: 6.8.0-49-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.22.2
- go/linking: dynamic
- go/tags: none

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

Ubuntu 24.04 (64 bit)

#### Which cloud storage system are you using? (e.g. Google Drive)

local filesystem

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)

rclone serve restic --cert ...

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Well spotted! Do you want to send a pr to fix? There is only one place in the code the docs need to be changed despite this help appearing many times in the docs .
