### ISSUE TITLE
Problems with 115 netdisk mounted locally and login failures

### ISSUE THREAD

**Issue by mobilesuits** [rclone/rclone#8237]
MACOS ARM64 version

I installed rclone using docker, created a webdav service for my 115 netbook, and then used the rclone mount command to mount the 115 netbook locally!

It was fine before, but recently I got the following error after mounting it.

NOTICE: 115 /: get dir id fail, not state, error: Login timeout, please relogin. , errno: 990001, resp: {Errno:990001 Error: Login timed out, please log in again. CategoryID: IsPrivate: State:false}

**Comment by kapitainsky** [comment]
Not clear at all what your issue is.

1. Please post in english - you can always use some online translation program
2. use https://forum.rclone.org/ and answer all questions when you create "Help and Support" ticket

**Comment by ncw** [comment]
The error message suggests you need to log in again. I'm not sure what system you are using though. Maybe rclone config reconnect might fix it 

I'm going to close this now as this is a problem which should go to the forum first - thank you

**Comment by LukeZhuohuiLi** [comment]
修改一下go文件从新导出一下exe就可以用了。
