### ISSUE TITLE
Azure Files missing x-ms-file-request-intent

### ISSUE THREAD

**Issue by glmacedo** [rclone/rclone#8241]
#### The associated forum post URL from `https://forum.rclone.org`
https://forum.rclone.org/t/azure-file-share-assistance-needed/48450

#### What is the problem you are having with rclone?
Access to azure files fails due to new header requirements from MSFT (https://learn.microsoft.com/en-us/azure/storage/files/authorize-oauth-rest?tabs=portal#privileged-access-and-access-permissions-for-data-operations)

#### What is your rclone version (output from `rclone version`)
rclone v1.68.2
- os/version: Microsoft Windows Server 2022 Datacenter Azure Edition 21H2 (64 bit)
- os/kernel: 10.0.20348.2819 (x86_64)
- os/type: windows
- os/arch: amd64
- go/version: go1.23.3
- go/linking: static
- go/tags: cmount

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
N/A - issue manifests on both Windows and Linux OS

#### Which cloud storage system are you using? (e.g. Google Drive)
Azure Files

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
rclone ls remote:share

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)
2024/12/10 18:51:07 DEBUG : rclone: Version "v1.68.2" starting with parameters ["rclone" "ls" "[storagename]:" "-vv"]
2024/12/10 18:51:07 DEBUG : Creating backend with remote "[storagename]:"
2024/12/10 18:51:07 DEBUG : Using config file from "C:\\Users\\user\\AppData\\Roaming\\rclone\\rclone.conf"
2024/12/10 18:51:07 ERROR : : error listing: GET https://[storagename].file.core.windows.net/share1/
--------------------------------------------------------------------------------
RESPONSE 400: 400 An HTTP header that's mandatory for this request is not specified.
ERROR CODE: MissingRequiredHeader
--------------------------------------------------------------------------------
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>MissingRequiredHeader</Code><Message>An HTTP header that's mandatory for this request is not specified.
RequestId:d2bc246e-901a-003d-3134-4bfc35000000
Time:2024-12-10T18:51:07.4729603Z</Message><HeaderName>x-ms-file-request-intent</HeaderName></Error>
--------------------------------------------------------------------------------
2024/12/10 18:51:07 DEBUG : 6 go routines active
2024/12/10 18:51:07 NOTICE: Failed to ls with 2 errors: last error was: GET https://[storagename].file.core.windows.net/share1/
--------------------------------------------------------------------------------
RESPONSE 400: 400 An HTTP header that's mandatory for this request is not specified.
ERROR CODE: MissingRequiredHeader
--------------------------------------------------------------------------------
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>MissingRequiredHeader</Code><Message>An HTTP header that's mandatory for this request is not specified.
RequestId:d2bc246e-901a-003d-3134-4bfc35000000
Time:2024-12-10T18:51:07.4729603Z</Message><HeaderName>x-ms-file-request-intent</HeaderName></Error>
--------------------------------------------------------------------------------

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
I managed to find the relevant part of the golang SDK and I have set the header.

I've done this for all types of auth - not sure if this is correct but it seems to work for me.

Can you give it a test and see if it fixes the problem for you?

[v1.69.0-beta.8454.31b874815.fix-8241-azurefiles-intent](https://beta.rclone.org/branch/fix-8241-azurefiles-intent/v1.69.0-beta.8454.31b874815.fix-8241-azurefiles-intent/) on branch [fix-8241-azurefiles-intent](https://github.com/rclone/rclone/tree/fix-8241-azurefiles-intent) (uploaded in 15-30 mins)

**Comment by glmacedo** [comment]
Gonna try to compile a binary for testing... i'm not much of a developer :) :)

**Comment by ncw** [comment]
@glmacedo you'll find the binaries in the link above :-)

**Comment by ncw** [comment]
Thanks for testing.

I've merged this to master now which means it will be in [the latest beta](https://beta.rclone.org/) in 15-30 minutes and released in v1.69

**Comment by glmacedo** [comment]
Awesome, thanks for the update!
