### ISSUE TITLE
[Documentation] rclone `copy` and `copyto` conflict descriptions

### ISSUE THREAD

**Issue by qupig** [rclone/rclone#8254]
https://github.com/rclone/rclone/blob/a78bc093de82358143719e63e771e099db91d242/docs/content/commands/rclone_copyto.md?plain=1#L16-L18

https://github.com/rclone/rclone/blob/a78bc093de82358143719e63e771e099db91d242/docs/content/commands/rclone_copyto.md?plain=1#L31-L33

https://github.com/rclone/rclone/blob/a78bc093de82358143719e63e771e099db91d242/docs/content/commands/rclone_copy.md?plain=1#L1-L8

- `rclone copyto`
  - **exactly like** `copy` (if src is directory)
  - **overwriting** existing files (if src is directory)
- `rclone copy`
  - **skipping** identical files

Now I'm not sure if it's `overwriting` or `skipping` exactly.

---

https://github.com/rclone/rclone/blob/a78bc093de82358143719e63e771e099db91d242/docs/content/commands/rclone_copyto.md?plain=1#L1-L9

https://github.com/rclone/rclone/blob/a78bc093de82358143719e63e771e099db91d242/docs/content/commands/rclone_copyto.md?plain=1#L27-L33

In fact, the subtitle of `rclone copyto` conflicts with the content itself.

**Comment by ncw** [comment]
We are happy to receive PRs if you can think of a way of clarifying the language @qupig - thanks
