### ISSUE TITLE
acd: Cache the templinks for big files

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#827]
At the moment when seeking a file > 10 GB we request the templink each time which is less efficient than it could be.  The templinks live for a certain length of time so find out how long and cache them for that long.

**Comment by jkaberg** [comment]
> A tempLink is a temporary URI provided for the purpose of downloading content from Amazon Drive. A tempLink should be used only when it is not possible to send an authentication to the server to retrieve the contents of a file. Example: If you create a gallery with photos on the web where the app lists all of the photos from the the user's Amazon Drive account and display the content.

> A tempLink is read only and allows the same functionality as a node; such as requesting modification of an image. A tempLinks is a transient URI and should be used only when all other options are not implementable. The expiry for a tempLink is shared across apps. **A tempLink expires after 48 hours; but is refreshed after 24 hours if any app sends a request**, which invalidates the old tempLink. Since the expiry is shared across apps, there is a chance for the tempLink to be requested just prior to the 24 hour (or 48 hour) expiry; so apps should send a request for a new tempLink when a response from Amazon Drive is includes an HTTP Status Code of 404 Not Found or 410 Gone.

https://developer.amazon.com/public/apis/experience/cloud-drive/content/glossary

Cheers :-)

**Comment by ncw** [comment]
@jkaberg thank you for digging that up - very useful :-) Don't know why they don't link to that in the API docs where you actually get a templink!

**Comment by ncw** [comment]
I'm going to close this since rclone no longer has any ACD keys and Amazon aren't issuing new ones.
