### ISSUE TITLE
Cannot mount MEGA anymore

### ISSUE THREAD

**Issue by OmikroN-TNS** [rclone/rclone#8270]
#### Output of `rclone version`

rclone v1.68.2
- os/version: darwin 13.7.1 (64 bit)
- os/kernel: 22.6.0 (x86_64)
- os/type: darwin
- os/arch: amd64
- go/version: go1.23.3
- go/linking: dynamic
- go/tags: cmount

#### Describe the issue

When I try to mount any MEGA remote it ends up with a "402 payment required error". Everything was working perfectly until 2 days ago (or so)

Here's the verbose output of the command:

2024/12/25 20:36:46 DEBUG : rclone: Version "v1.68.2" starting with parameters ["rclone" "-vv" "mount" "megadrive:/" "/Users/gemini/rclone" "--vfs-cache-mode" "writes" "--allow-non-empty"]
2024/12/25 20:36:46 DEBUG : Creating backend with remote "megadrive:/"
2024/12/25 20:36:46 DEBUG : Using config file from "/Users/gemini/.config/rclone/rclone.conf"
2024/12/25 20:36:57 CRITICAL: Failed to create file system for "megadrive:/": couldn't login: Http Status: 402 Payment Required

**Comment by kaoneko** [comment]
I'm curious why you think the issue is with rclone instead of the cause being a change in your MEGA account/payment status or MEGA's policy. Care to elaborate?

**Comment by ortmann** [comment]
Log in using your browser. Then, try again.

**Comment by tomjpalamattam** [comment]
Same issue here

**Comment by ortmann** [comment]
Have you tried the solution I posted above?

**Comment by tomjpalamattam** [comment]
> Have you tried the solution I posted above?

Yes, I was able to login from the browser. But the issue seems to have solved itself for me, now its working again.

**Comment by dickastic** [comment]
2024/12/27 17:48:33 CRITICAL: Failed to create file system for "mega:": couldn't login: Http Status: 402 Payment Required

same issue here

**Comment by OmikroN-TNS** [comment]
> I'm curious why you think the issue is with rclone instead of the cause being a change in your MEGA account/payment status or MEGA's policy. Care to elaborate?

The account is a free one with half of the space available. Anyway @ortmann solution did the trick

**Comment by OmikroN-TNS** [comment]
> 2024/12/27 17:48:33 CRITICAL: Failed to create file system for "mega:": couldn't login: Http Status: 402 Payment Required
> 
> same issue here

https://github.com/rclone/rclone/issues/8270#issuecomment-2562047717

fixed the issue

**Comment by AlexTMjugador** [comment]
Logging in to the MEGA account using a web browser with rclone v1.69.0 did not work for me.

**Comment by huskaramok** [comment]
Same as [AlexTMjugador](https://github.com/AlexTMjugador) , logging in doesnt work. still get the error Failed to create file system for "mega:/": couldn't login: Http Status: 402 Payment Required. rclone version 1.69

**Comment by ennevu** [comment]
Like stated in the [rclone configuration guide ](https://rclone.org/mega/) the encryption keys need to be generated before with a regular browser login. What worked for me was removing the eventual config of mega created on rclone, login on mega via browser and then recreating a config.
