### ISSUE TITLE
Path tab completions for fish won't autocomplete for paths with whitespace

### ISSUE THREAD

**Issue by starptr** [rclone/rclone#8271]
#### What is the problem you are having with rclone?

The following flow occurs:

```fish
$ rclone ls remote:/test/path<tab> # completes to
$ rclone ls remote:/test/path\ with\ spaces/
$ rclone ls remote:/test/path\ with\ spaces/child<tab> # <-- doesn't complete here
```

This is similar to the problem observed here: https://github.com/rclone/rclone/issues/3047#issuecomment-472802014, but unlike that issue thread, this happens in the fish shell.

#### What is your rclone version (output from `rclone version`)

1.68.2

#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)

MacOS 15.0.1 64bit, arm

#### Which cloud storage system are you using? (e.g. Google Drive)

Remote crypt to sftp

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

NA

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
This is an upstream bug in the cobra library.

See this issue https://github.com/rclone/rclone/issues/8056 for more details.

**Comment by ron007d** [comment]
1.64.2 bash completion works not able to get it working for the later versions
