### ISSUE TITLE
Docker volume: inotify_add_watch(/xxx failed: (Permission denied)

### ISSUE THREAD

**Issue by jehon** [rclone/rclone#8276]
#### What is the problem you are having with rclone?

I use the docker volume plugin.

#### What is your rclone version (output from `rclone version`)

```
rclone v1.69.0-beta.8466.e1748a318
- os/version: alpine 3.20.3 (64 bit)
- os/kernel: 6.8.0-51-generic (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.23.4
- go/linking: static
- go/tags: none
```
 
#### Which OS you are using and how many bits (e.g. Windows 7, 64 bit)
Distributor ID: Ubuntu
Description:     Ubuntu 24.04.1 LTS
Release:            24.04
Codename:      noble

#### Which cloud storage system are you using? (e.g. Google Drive)
PCloud

#### The command you were trying to run (e.g. `rclone copy /tmp remote:tmp`)
I use the docker volume inside a docker-compose.
The volume is used by another container. In that container, I receive:

```inotify_add_watch(/xxx failed: (Permission denied)```

I don't know the exact command the program is launching to get that error.

#### A log from the command with the `-vv` flag (e.g. output from `rclone -vv copy /tmp remote:tmp`)

I see nothing in the logs related to that problem.

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ncw** [comment]
Rclone doesn't currently support inotify so I'd be surprised if this was rclone.

Any logs available?

**Comment by jehon** [comment]
Indeed, I think it is the program that use the rclone volume that try to use inotify... The log here above is the log of the application.

So rclone does not allow clients to watch for files, right?

**Comment by ncw** [comment]
rclone mount doesn't support inotify. I don't think it is possible with a fuse filing system, but I'm not 100% sure about that.
