### ISSUE TITLE
[Feature Request] Statistics - hourly, daily, monthly

### ISSUE THREAD

**Issue by scriptzteam** [rclone/rclone#834]
Will be great if rclone will have some stats as output.

So we can do for example `rclone --stats` h or `--stats d`

Stats for uploaded count of files and uploaded mb/gb/tb (i can do upload in one day about max 3-5TB of data xD so thats why TB need)

I know there are tons of apps like `vnstat` but whats about rclone "own stats"?

Thx, keep the great work :)

**Comment by ncw** [comment]
rclone will print stats like this after each run, or at regular intervals with the `--stats` option.   These will scale up to TB too!

```
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:          0s
```

is that what you need?  rclone doesn't accumulate stats over different runs though.

**Comment by scriptzteam** [comment]
I mean just if i do for example `rclone --stats d` it will print stats for whole day not stats when running (sync or move or copy etc...)

Probably output like this:
`Transferred: 3.25 TB
Files: 512000`

Thx :)

**Comment by fionera** [comment]
What about extending this to a InfluxDB reporting system?

**Comment by fionera** [comment]
Ok I just added an Influx DB backend :) Works great https://i.imgur.com/QxuAUYw.png

**Comment by animosity22** [comment]
I think as @fionera  mentioned, there are a few ways to tackle this now as you can that from remote control as well and put it into anything you want which I believe meets the over OP's request so I'm going to close it out.

If I misunderstood something, please let me know.
