### ISSUE TITLE
[Suggestion] Transfer to Youtube ?

### ISSUE THREAD

**Issue by doplu** [rclone/rclone#843]
Dear all,

Would it be possible to add Youtube as a new storage ?

My usage : transferring (using a cheap VPS) some of my old videos that are stored in Amazon Drive into Youtube as private videos. Then I could share some of them privately with my relatives.

Thanks in advance ;)

**Comment by ncw** [comment]
Interesting idea - does YouTube have an API for doing that?

**Comment by doplu** [comment]
Hi,
I hope this may help ?
https://developers.google.com/youtube/v3/guides/uploading_a_video
(https://github.com/tokland/youtube-upload)

BTW, it is already possible to transfer videos from Google Photos into Youtube https://www.youtube.com/upload (https://productforums.google.com/forum/#!topic/drive/OoiCyN8ck14)

Thanks ;)

**Comment by reticentnz** [comment]
A quick google suggests this is already possible - https://github.com/tokland/youtube-upload.

**Comment by TaktakTaktouk** [comment]
It will be a good idea if rclone add the upload to YouTube

**Comment by TaktakTaktouk** [comment]
It will be a good idea if rclone add the upload to YouTube

**Comment by sntran** [comment]
I think a YouTube remote is a great idea. You can list videos on playlists or channels, public or private, and can upload videos if permission allowed.

Even though there are other tools to download/upload YouTube, it's nicer to just use rclone to do that.

**Comment by ivandeex** [comment]
Quick summary of user interest after 5 years on rclone tracker:
- 4 thumbs up from users (including 2 "mee too" comments)
- 0 volunteers

Overall, the interest is too low to warrant keeping the request for next 5 years
Closing

**Comment by upintheairsheep** [comment]
I think interest is high enough

**Comment by upintheairsheep** [comment]
YouTube is a really big site with billions of users, so it makes sense, and demand for an uploader like this seems big enough

**Comment by Masamune3210** [comment]
Unfortunately, if there was as such a demand as some would think, this would either have more attention or volunteers. You can always offer to add the code yourself but the lack of interaction in here hints that the want might be more niche than you think

**Comment by jamshid** [comment]
lol maybe interest in this feature will return with:
https://hackaday.com/2023/02/21/youtube-as-infinite-file-storage/

**Comment by upintheairsheep** [comment]
Yes, I was hoping for videos but files is also cool backup
