### ISSUE TITLE
Sync from shared links 

### ISSUE THREAD

**Issue by RomeSilvanus** [rclone/rclone#862]
If there is any way I'd like to request a way of downloading / one-way syncing shared folders and files from a cloud service. 
In my case I have a link to a  Dropbox, OneDrive, or Google Drive shared folder which periodically gets update with new content. It would be nice if I could just run something like "rclone sync "link to folder" "local folder"" and it would download it and keeps it in sync with the remote folder if something changes. It would save a lot of time on manually checking up and downloading them.

Also another thing I'm sure was already brought up here. Are there any plans to include a way to make rclone behave more like rsync in the way it actually syncs? E.g.:
Rclone sync transfers files and folders apparently at random.
Rsycn starts at the top and then goes folder by folder and file by file, which makes it easier to know which files and folders are already fully transfered.

**Comment by ncw** [comment]
rclone already support s3 public buckets like this.  The question would be whether the other cloud providers let you use their APIs on public shared docs.

> re there any plans to include a way to make rclone behave more like rsync in the way it actually syncs

rclone syncs many things concurrently which rsync doesn't hence getting things out of order.  If you run with `--checkers 1 --transfers 1` you'll get behaviour more like rsync at the expense of lots of speed.

**Comment by mrvik** [comment]
Any updates on syncing from Dropbox shared links?

**Comment by ncw** [comment]
I think this was implemented for 1.53 - see these flags

     --dropbox-shared-files            Instructs rclone to work on individual shared files.
      --dropbox-shared-folders          Instructs rclone to work on shared folders.

And 575f061629907027da16174ca672a3ef9be2185a

So I'll close this now :-)
