### ISSUE TITLE
API for rclone (eg for building a GUI)

### ISSUE THREAD

**Issue by hmbrg** [rclone/rclone#876]
Is there any way to use Rclone with an application interface (i. e. to build a GUI) or will there be such a feature in the future?

**Comment by jdahmen** [comment]
I messaged @ncw a few months ago about doing this. He said he thought it would be a good idea. I, however, got lost in my day job and other obligations and never got through to writing this. I don't know Go at the moment, but am trying to learn. But, I do know a decent bit about Python API design and Angular (2+) front end design. So I'd be happy to, and would like to write a UI and API for rclone, as long as a person or two don't mind giving me a little support along the way with the Go aspects of it.

**Comment by ncw** [comment]
@jdahmen Go for it!  If you need help then ask on the forum is a good plan.

**Comment by animosity22** [comment]
Since there is a webgui for this now, I think this one is safe to be closed out.

If I have something wrong, please let me know.
