### ISSUE TITLE
[Feature Request] Python API

### ISSUE THREAD

**Issue by scj643** [rclone/rclone#883]
A python API would be amazing. I could work on the API if some primatives could be exposed as a Python module.

**Comment by eilifm** [comment]
Wrapping with Subprocess and writing a series of parsers for stdout and stderr has been working well so far for a handful of use cases.

**Comment by animosity22** [comment]
I believe the majority of this is already in the remote control aspect of it as it's been around for some time without any movement, I'm going to close it out.

If there is something you'd want to move forward on this, please let me know.
