### ISSUE TITLE
[Feature Request] Low speed limit

### ISSUE THREAD

**Issue by talisto** [rclone/rclone#887]
When uploading to ACD I occasionally get really slow speeds with a single file transfer.  I'm assuming this is an issue on ACD's end, and usually killing the process and re-starting it resolves the issue, but it would be nice if there was a way for rclone to restart the transfer automatically.  

I noticed the google-drive-ocamlfuse project has configurable options for `low_speed_limit` and `low_speed_time`: https://github.com/astrada/google-drive-ocamlfuse/wiki/Configuration

> Specifies when a transfer is too slow. If speed (in bytes/second) is under low_speed_limit for low_speed_time (in seconds), the file transfer will be terminated (0 = don't check)

It would useful for rclone to have a similar option.

Thanks!!

**Comment by dia3olik** [comment]
this is actually a very good suggestion and it would help tremendously with ACD!!

**Comment by tmikaeld** [comment]
I have the same request for several cloud services, but mainly pCloud which often get stuck at a few KB/s and never recovers. Which means it's impossible to do head-less syncs using it.

**Comment by tmikaeld** [comment]
This is becoming even more of a problem now that FreeNAS has added rclone into their system, since it's running headless, it has hanging transfers at 0kb speed.

**Comment by ncw** [comment]
So this needs to be a speed limit and a time, so "abort if speed < 10k/s for 100s"

So probably two flags --bwlimit-min --bwlimit-min-time or something like that.

Does anyone want to have a go at this?

**Comment by tmikaeld** [comment]
@ncw I'm afraid I don't know low-level languages and I don't have time, any chance I can sponsor adding the feature?

**Comment by ncw** [comment]
> I'm afraid I don't know low-level languages and I don't have time, any chance I can sponsor adding the feature?

@tmikaeld drop me an email to nick@craig-wood.com and we can discuss :-)

**Comment by ivandeex** [comment]
@ncw
The request for an action triggered on minimum bandwidth is recurring through issues. I'll mark one of these as important and add cross links.

**Comment by ivandeex** [comment]
This old request is completely similar to #2122 so merging this in #2122
The request is not dismissed, just removing duplicates
You can subscribe to #2122 now
Thank you
