### ISSUE TITLE
windows: Replace control characters (eg TAB) in file names 

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#901]
It is possible to create files on drive for example with TABs in the file names.  These can't be downloaded under windows as windows can't have TABs in file names apparently.

See [the forum](https://forum.rclone.org/t/gdrive-rclone-sync-multiple-issues-found-for-rclone-windows-and-google-drive/258/4) for discussion.

**Comment by ivandeex** [comment]
Latest rclone encodes filenames. This issue needs a retest.

**Comment by ncw** [comment]
This is definitely fixed by filename encoding. The unit tests test the case of control characters specifically, so I will close this now.
