### ISSUE TITLE
[Feature Request] union FUSE mounts

### ISSUE THREAD

**Issue by aus** [rclone/rclone#909]
I'd like to propose an enhancement to FUSE where multiple sources (local and remote) could be presented as a single, merged mount point. The effect would be similar to using something like [UnionFS](http://unionfs.filesystems.org/), [aufs](http://aufs.sourceforge.net/), or [mergerfs](https://github.com/trapexit/mergerfs). Policies could be defined to give read / write priority to certain destinations (ie write only to local or prefer reads in order of local, Amazon, Google). Additionally, reads could be distributed between sources. 

For example, let's say you have data mirrored between Amazon Cloud Drive and Google Drive. And you also have your most frequently used or newest data stored locally. All data is stored in a similarly structured directory tree in each source. rclone presents these data sources as a single, merged mount point. 

At some point, you might exceed your daily quota for Google Drive making reads from that source impossible for a while. rclone could have logic to know that the file being read also exists on Amazon and read it accordingly. Any locally available file could be given first read priority. Or perhaps there could even be some sort of ongoing metrics determining which source is the speediest and give automatic preference to that source. 

But why re-invent the wheel when we already have tools like UnionFS, aufs, and mergerfs? Well, these tools treat their sources as real filesystems and have no insight to the cloud provider underneath the FUSE layer. When you experience errors with the cloud provider, those ultimately get turned into filesystem errors. For example, whenever your Google Drive quota gets exhausted, rclone/FUSE will return an `EIO` on the read. If the union logic is baked into rclone, filesystem errors could be avoided by building additional logic around the cloud API requests.  For reference, I discussed this idea a bit with the mergerfs dev @trapexit on [#338](https://github.com/trapexit/mergerfs/issues/338).

I'm sure this is a non-trivial request, but I thought I'd throw it out there to gauge interest.

**Comment by trapexit** [comment]
What's rclone's behavior when in this errored state? How would open, creat, statfs, read, etc. act?

**Comment by tjeh** [comment]
@ncw maybe you can help out [here](https://github.com/trapexit/mergerfs/issues/342)

Is there any way to "reproduce" a input/output error like an rclone mount on gdrive gives if trying to read a file with "User Limit Exceeded".

**Comment by trapexit** [comment]
I could create  simple fuse fs to do the same. I'm guessing it simply returns EIO on reads?

**Comment by trapexit** [comment]
When it's in that state... files are still presented to the user? Can they be stat'ed? open'ed?

**Comment by ivandeex** [comment]
@aus 
I believe this can be achieved with new https://rclone.org/union/
Could you try pls?

**Comment by aus** [comment]
I hadn't seen the Union backend yet. Very nice! The docs definitely support my original use case. I will close this issue and open new issues if I run into more specific problems.
