### ISSUE TITLE
rclone amazon upload error - File size exceeds account allowance.

### ISSUE THREAD

**Issue by roubles** [rclone/rclone#915]
When using rclone to upload photos to amazon I get the error:
2016/11/28 23:03:29 fooiphone302013/IMG_0206.JPG: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 403: "403 Forbidden", reponse body: {"logref":"c8debefd-b5e8-11e6-92a4-added878cb73","message":"File size exceeds account allowance.","code":"NO_ACTIVE_SUBSCRIPTION_FOUND"}
 ("403 Forbidden")

I have free unlimited storage for photos, so this should not be happening. I am not sure if this is an amazon issue or if it is specific to rclone. I am going to try acd_cli and will report back.

Let me know if you need more logs.

> What is your rclone version (eg output from `rclone -V`)
rclone v1.34

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
OS X 10.11.6

> Which cloud storage system are you using? (eg Google Drive)
amazon

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy -c -v --filter-from pics.txt /path/to/photos amazon:photos

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
2016/11/28 23:03:29 fooiphone302013/IMG_0206.JPG: Error detected after finished upload - waiting to see if object was uploaded correctly: HTTP code 403: "403 Forbidden", reponse body: {"logref":"c8debefd-b5e8-11e6-92a4-added878cb73","message":"File size exceeds account allowance.","code":"NO_ACTIVE_SUBSCRIPTION_FOUND"}
 ("403 Forbidden")

**Comment by ncw** [comment]
I think this is probably an amazon issue - is it working now?

**Comment by animosity22** [comment]
Legacy issue and closing out.
