### ISSUE TITLE
Input/output error

### ISSUE THREAD

**Issue by jpontius** [rclone/rclone#917]
Hi!

Thanks for this awesome software.  I'm using it with my university's Google Drive unlimited account, encrypted of course.  I'm getting an error after a while trying to use it as a mounted drive.  After some period of time, any file I try to read fails and complains with `Input/output error`.   Re-mounting doesn't fix it.  The only way I've found to fix it, is wait a day or two.

Attached is my -v log file.  I tried `cat duplicity.info` and got `cat: duplicity.info: Input/output error`  Its just a simple text file.

[rclone-debut.txt](https://github.com/ncw/rclone/files/622052/rclone-debut.txt)

> What is your rclone version (eg output from `rclone -V`)
**rclone v1.34**

> Which OS you are using and how many bits (eg Windows 7, 64 bit)
**Linux pontius-vps1 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux**

> Which cloud storage system are you using? (eg Google Drive)
**University unlimited Google Drive**

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
**rclone mount --max-read-ahead 200M --checkers 300 --read-only -v --allow-other g-drive-work-encrypted: plex-storage-encrypted/**
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

**Comment by cejpe** [comment]
I believe this is because you're hitting Google Drive's rate limit for number of files per user. I think you can get around this by creating your own client_id for rclone.

Try following the instructions on the bottom of the page [here](http://rclone.org/drive/)

**Comment by tjeh** [comment]
Yeah its not easy to understand what Google is limiting in the background, I ran into the same issue, see [https://forum.rclone.org/t/gdrive-download-quota-exceeded-for-this-file-so-you-cant-download-it-at-this-time/385](url)

**Comment by Cr0iX** [comment]
I have the same problem but with amazon drive. I cannot find anything in the docs about how to create my own client id? I can upload from amazon website but not from the clone mount..

**Comment by ncw** [comment]
@Cr0iX you can't create your own client id with ACD easily :-(

**Comment by animosity22** [comment]
This looks to be a use case question and if you have anything additional, please visit the forums.
