### ISSUE TITLE
[feature_request]  Expiring Object Support

### ISSUE THREAD

**Issue by cloudrkt** [rclone/rclone#918]
HI,

I am using the Rclone with the Openstack Swift Objectstore and I wonder if i could use the  [Expiring Object Support feature](http://docs.openstack.org/developer/swift/overview_expiring_objects.html) with Rclone. This will set an X-Delete-At or X-Delete-After header on the uploaded object and get's delete by the objectstore after or on that timestamp.

With this option you kan setup backup retention on your Rclone copied objects if needed.

**Comment by ncw** [comment]
Would the ability to set arbitrary headers on uploaded files work for you?  Eg #59

**Comment by rosconap** [comment]
Ah yes, that would be fantastic.

**Comment by animosity22** [comment]
Since this one is a bit stale. We can track it via the other open item so I'll close this one out.
