### ISSUE TITLE
[Feature Request] set environmental variables

### ISSUE THREAD

**Issue by bobbintb** [rclone/rclone#921]
This has sort of been touched on with questions of an API or a gui and I just kind of wanted to add my 2 cents. I think something to open it up to outside interaction with other systems or programs would be beneficial. I don't think an API would really work for rclone since being a sync tool, it isn't run continually like a service. Really, an API doesn't really make sense and is overkill for such a simple and elegant tool. A full on GUI also doesn't really fit the bill either, or rather, should be left to third parties.

It would be nice to have something that it output to give us something short of an API or GUI. Really, I think just simply outputting certain information to environmental variables would be trivial and efficient. Things like current file, file percentage complete, total percentage complete, etc. I run it on a headless server but for large sync jobs, or any sync job really, I have to keep a terminal open to get progress on it and even still, it will only show the current file. Just a simple way to get some insight of what it is doing.

**Comment by ncw** [comment]
How about a web page?  Would that work for you?  rclone could serve a simple auto refreshing web page with some stats about the current transfer in.

**Comment by bobbintb** [comment]
I was kind of thinking that might be a little out of the scope of rclone but yeah, that was the end state. I use rclone on my UnRAID NAS as a plugin and I was planning on extending the plugin to include progress information instead of just running blindly in the background. But I found there was no way to get that information from rclone.

**Comment by ncw** [comment]
Doing web pages from go is super easy...

I'd make another option called `--stats-page` which took `:port` or `host:port` which would show some read only stats while rclone was running.  The first version would probably just show exactly what the stats printer does.

**Comment by bobbintb** [comment]
Yeah, I think that would be great.

**Comment by bobbintb** [comment]
I see the new version has a `--stats` option. Is that referring to this? I have in enabled on my transfer but it looks the same. The manual has yet to reflect the change. Can I get a little ore info on this option?

**Comment by Waseh** [comment]
I think it refers to this
https://github.com/ncw/rclone/commit/43c530922aabe0ca08d490e790aeec0f64cdc6c3

**Comment by bobbintb** [comment]
Yeah, I think I see now. What are the chances of this getting added? It doesn't need to be too conplex. Just a simple way of directly reading stats from rclone instead of some sort of regex/grep kludge.

**Comment by animosity22** [comment]
Code for this looks committed and the request is very old. If there is still a question, you can ask on the forums and we can help out.
