### ISSUE TITLE
[Feature Request] local cache with modifications

### ISSUE THREAD

**Issue by Njcki** [rclone/rclone#925]
Hi there,
I state that my question is not too easy but may be very useful for some people.

I'm using (encrypted) ACD mounted to /mnt/acd/.

Currently mounting ACD implementation in rclone is not yet complete, it's still buggy.
Personally I got some very bad errors. Like when I copied a large file ~14GB to ACD using cp command; at the end I got "Unable to close file" and the written file on ACD was awfully corrupted.

So I managed to solve this problem. I thought that this could be a valid solution:
`unionfs-fuse -o allow_other,cow /mnt/local-data/=RW:/mnt/acd/=RO /mnt/Merged/`
... and periodically:
`rclone sync /mnt/Merged/ acd_e:`

But later I thought: "What will happen if ACD mounted on /mnt/acd/ is going to crash?".
The answer is that most probably since /mnt/Merged/ will contain only /mnt/local-data/ then all ACD content will be wiped as soon as the _rclone sync_ command will be executed.

Any better solution? Suggestions?
Maybe you could do a better implementation on the rclone side?

Niccolò Mencarini

**Comment by ncw** [comment]
I recommend you use `rclone copy` to upload stuff - the fuse system doesn't do any sort of retries...

> So I managed to solve this problem. I thought that this could be a valid solution:
> unionfs-fuse -o allow_other,cow /mnt/local-data/=RW:/mnt/acd/=RO /mnt/Merged/
> ... and periodically:
> rclone sync /mnt/Merged/ acd_e:

Use `rclone copy /mnt/local-data/ acd_e:` would be a better solution I think.

**Comment by Njcki** [comment]
I did so till now. The problem is that I need to also sync file deletions.

**Comment by ncw** [comment]
I would script the `rclone copy` but only do the `rclone sync` you originally suggested by hand after running it with `--dry-run` first.

**Comment by animosity22** [comment]
This looks answered. If you still have a question, please ask on the forums and we can help out.
