### ISSUE TITLE
.conf file --ask-password option

### ISSUE THREAD

**Issue by pedrosimao** [rclone/rclone#926]
This is more of a feature request than an issue, please tell me if this is the right place to write.
I have recently discover the --ask-password option which is really important to enhance security.
Non-encrypted conf files are an open door for anyone who gain access to our computer.
But having to type our passwords on every command can be annoying.
So I suggest an extra flag for the --ask-password flag.
There could be a "start"and "end" extra flags, which would temporarily create (and delete) unencrypted versions of the ".conf" file.
Like this we would not be asked to type the password everytime we want to execute a command.

**Comment by ncw** [comment]
I should probably put this in the docs...

Make a file - I called mine ~/bin/set-rclone-password with this in

```
#!/bin/echo Source this file don't run it

read -s RCLONE_CONFIG_PASS
export RCLONE_CONFIG_PASS
```

Then when you want to unlock rclone for a while do

```
. ~/bin/set-rclone-password
```

**Comment by ncw** [comment]
We've also recently added the `--password-command` flag for integration with password managers so I'm going to close this now.
