### ISSUE TITLE
403 - rclone required permissions for AWS S3

### ISSUE THREAD

**Issue by SpareShade** [rclone/rclone#930]
thank you for this great tool!!!

I am trying to sync the local storage with a single bucket on AWS S3. For this, I have IAM user with all permissions on this particular bucket + listing bucket privileges across the S3.
I get 403 response when trying to sync/copy the local files to S3, it works fine if I give all of S3 privileges.
So the question is, does rclone require all of the S3 permission just to sync/copy files to a single bucket?

I cannot find any info in the docs, nor on the web.

Any pointers would be much appreciated.

**Comment by ncw** [comment]
> thank you for this great tool!!!

:-)

> So the question is, does rclone require all of the S3 permission just to sync/copy files to a single bucket?

I doubt it needs all the permissions, but I don't know very much about S3 permissions!

I looked at: http://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html

I would have thought PutObject and and ListBucket would be sufficient for upload purposes.  You can run with --dump-headers to give you more of a clue as to what rclone was doing when it gets a 403 error.

If you fancied writing this up and adding it to the docs when you figure it out, I'd be grateful :-)

**Comment by SpareShade** [comment]
ok, will have a closer look with --dump-headers option.

I actually expressed the question wrongly.

it seems that rclone requires PutObject/ListBucket(s) across all S3's resources (ie. buckets), but does not require all of the permission as I expressed it above.

in any case i'll do more tests, and report back, and if you think they are ok we add them to the docs :)

**Comment by ncw** [comment]
Always interested in more docs! I'll close this now since I haven't heard from you for a while.
