### ISSUE TITLE
[Future: GUI for Linux]

### ISSUE THREAD

**Issue by tele1** [rclone/rclone#934]
I suggest build GUI with gtkdialog for Linux.
Easy, fast, and running from bash script, so you can edit always.
I created with this GDI (GUI for install about 14 desktop enviroments)

Examples how build
http://xpt.sourceforge.net/techdocs/language/gtkdialog/gtkde02-GtkdialogExamples/single/

Source code with examples:
https://github.com/roma0104/gtkdialog

Wiki with examples
https://github.com/roma0104/gtkdialog/blob/wiki/ProjectHome.md

More you can find on Puppy Linux forum
http://www.murga-linux.com/puppy/viewtopic.php?t=38608

**Comment by animosity22** [comment]
This is already handled via the new gui.
