### ISSUE TITLE
Upload stays at 100% ETA:0s sometimes.

### ISSUE THREAD

**Issue by chris243** [rclone/rclone#936]
When filing an issue, please include the following information if possible as well as a description of the problem.  Make sure you test with the [latest beta of rclone](http://rclone.org/downloads/).

If you've just got a question then please use the [rclone forum](https://forum.rclone.org/) instead of filing an issue.

> What is your rclone version (eg output from `rclone -V`)
1.34
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Ubuntu 16.04
> Which cloud storage system are you using? (eg Google Drive)
ACD
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone move
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

It will eventually finish but it can take anywhere from 2-10min after it gets to 0s.  The upload speed slowly starts to go down to zero once it hits 100% uploaded.

**Comment by lobianco** [comment]
Not a bug, see http://rclone.org/amazonclouddrive/#acd-upload-wait-per-gb-time.
