### ISSUE TITLE
Why is rclone writing to a read only file?

### ISSUE THREAD

**Issue by SoftNotWork** [rclone/rclone#939]
> What is your rclone version (eg output from `rclone -V`)

rclone v1.34

> Which OS you are using and how many bits (eg Windows 7, 64 bit)

CentOS 7 x86_64

> Which cloud storage system are you using? (eg Google Drive)

Amazon Drive

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

/usr/bin/rclone copy /folder/folder secret:remote

> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)

2016/12/10 12:47:45 Failed to save config file: open /root/.rclone.conf: permission denied

rclone is not being reconfigured. It should not be writing to the configuration unless it is being reconfigured. Why is it writing to a file that I do not want it writing to? Permissions and chattr are set to lock the file read only. 

Why can't I secure the file to prevent modification? What is the purpose of constantly rewriting a static file?

**Comment by ncw** [comment]
Rclone stores the token which changes every hour in the config file - that is why it rewrites it.

**Comment by animosity22** [comment]
Question was answered and if anything else is required, please ask on the forums as it's not an issue.
