### ISSUE TITLE
[Feature Request] Static Mod Time (mount)

### ISSUE THREAD

**Issue by jpat0000** [rclone/rclone#940]
Simply specifying --no-modtime results in the current system time being set as the modified time, however some applications such as Plex, will re-analyze your files if the modified time changes. This results in every file requiring a rescan after every mount. It would be very useful to me, at least at the moment, if I could specify my own static modtime for every file at mount.

Thanks!

**Comment by tjeh** [comment]
I would second that request (otherwise Plex is going crazy). As far as I experience it right now even rclone sync will:
- check if the files are identical
- will NOT sync the set mod-time, which results in having i.e. a directory in sync (content wise) but the files will show different dates?

So its either being able to set a **static mod** time or get the functionality to **completely** (content, md5, times) keep two directories in sync.

**Comment by jpat0000** [comment]
I was able to accomplish this. 

cmd/mount/file.go replacing lines 55-67
```
 	} else {
		a.Size = uint64(f.o.Size())
		if !noModTime {
			modTime := f.o.ModTime()
			a.Atime = modTime
			a.Mtime = modTime
			a.Ctime = modTime
			a.Crtime = modTime
		} else {
			var epoch = time.Unix(0, 0)
			a.Atime = epoch
			a.Mtime = epoch
			a.Ctime = epoch
			a.Crtime = epoch
		}
	}
```
cmd/mount/dir.go replacing lines 152-159
```
func (d *Dir) Attr(ctx context.Context, a *fuse.Attr) error {
	fs.Debug(d.path, "Dir.Attr")
	a.Gid = gid
	a.Uid = uid
	a.Mode = os.ModeDir | dirPerms

	if noModTime {
		var epoch = time.Unix(0, 0)
		a.Atime = epoch
		a.Mtime = epoch
		a.Ctime = epoch
        a.Crtime = epoch
	}
	// FIXME include Valid so get some caching? Also mtime
	return nil
}
```

When --no-modtime is specified, files and folders will instead have accessed/modified/creation time listed as Dec/31/1969 or Jan/01/1970 depending on the local timezone.

**Comment by flixajki** [comment]
@ncw could you compile one beta with it, this would great temporary solutions.

**Comment by ncw** [comment]
@jpat0000  Can you send a pull request with this in please?

I'd probably prefer to use the time the mount started rather than the 0 epoch time if that would work for your requirements.

Maybe with an optional flag to set the time to something specific.

If you can send a PR with what you've done with or without those changes then I can get it integrated and we can iterate the design.

**Comment by tjeh** [comment]
In terms of i.e. Plex it would be great to be able to set it to a static userdefined time

**Comment by flixajki** [comment]
As long as the time never changes it would work good for Plex.

p.s. Is there a specific reason why we dont have actual times since they are clearly supported by Amazon Cloud ?

**Comment by ncw** [comment]
@flixajki  wrote
> Is there a specific reason why we dont have actual times since they are clearly supported by Amazon Cloud ?

You'll get times that the file was uploaded if you don't use --no-mod-time and it is no slower with ACD so I'd use that.

Or are you seeing something different?

**Comment by flixajki** [comment]
All my folder / files times are set to the time I mounted drive, eg if I remount all times changes.
Mounted 

> plex       934 14.7  0.8 815124 270652 ?       Sl   Dec12 121:27 rclone mount --read-only --allow-non-empty --allow-other --dir-cache-time 5m --max-read-ahead 14G --acd-templink-threshold 0 --bwlimit 0 --checkers 32 --contimeout 15s --low-level-retries 1 --no-check-certificate --quiet --retries 3 --stats 0 --timeout 30s --transfers 32 acd:/ /storage/.acd/


File list ( offset +1h )
https://puu.sh/sNUZu/62d2015bcd.png

**Comment by ncw** [comment]
All the folder times will be set to the time you mounted the drive, however the file times should be constant.  That is what I see.

Does plex look at the folder date stamps?

```
$ rclone mount acd:test ~/mnt/tmp/
$ ls -l ~/mnt/tmp/
total 5242881
-rw-rw-r-- 1 ncw ncw 5368709121 Nov 20 14:00 5GB
drwxrwxr-x 1 ncw ncw          0 Dec 13 10:57 newsubdir
```

However

```
$ rclone lsl acd:test
5368709121 2016-11-20 14:00:44.915000000 5GB
```

**Comment by flixajki** [comment]
True, but is there a way to set folder the same time as file's last change. 
As far as I know thats how plex is detecting partial and recent changes.

**Comment by jpat0000** [comment]
@ncw 

I am not well-versed with github, but I will look into it.

@flixajki 

I needed a static mod time as I use two different mounting software, one has a static mod time of 0 epoch, I needed consistency. I am not sure if Plex re-analyzes your files if the folder has a new mod time, you'll have to test that out. If you're really interested in installing rclone with static mod time right now, you can clone the repository, make the edits to the two files, and then install with go "go get rclone/".

I believe Plex may look at the folder mod times to scan for new files, so that's a good suggestion, however I don't think it can or should be implemented with rclone. Unless I am mistaken, rclone would need to traverse every subdirectory every time you seek a folder, this would be incredibly slow. If rclone cached the entire drive structure, perhaps it would be implementable. (correct me if I am wrong)

**Comment by mrobgithub** [comment]
@flixajki

I believe the functionality you are describing is how acd_cli mounts handle folder mod times. The folder mod time is set to the mod time of the most recently modified file in the directory. I think this is the best approach for folder mod times in the rclone in-memory cache for now until/unless ACD ever supports true folder mod times.

@ncw

I see the same behavior you describe in that when mounting via rclone file times are correct (match upload time in ACD) but folder times are all set to the mount time. Plex can be finicky when scanning and seems to take folder time changes into account when determining whether to re-analyze files (which is very slow) within a folder even if the actual file times have not changed.

**Comment by ncw** [comment]
I've made a small modification which makes rclone report the actual modification times of directories as read from the remote.  Since ACD has a concept of directory and these have times then this should fix the problem for you.  Don't use `--no-mod-time` though (it doesn't buy you anything with ACD) and will confuse plex.

http://beta.rclone.org/v1.34-64-g13b705e/ (uploaded in 15-30 mins)

**Comment by tjeh** [comment]
Brilliant, this seems to solves the folder issues.

Is there any chance to get the rclone sync command to also sync the times? I have two amazon drives that are in sync from a content point of view, however the reported times differ... which in return will get plex confused when switching between the mounts.

**Comment by animosity22** [comment]
This looks merged and solved. Closing out.
