### ISSUE TITLE
Amazon Drive: Respect filename length limitation

### ISSUE THREAD

**Issue by diamondsw** [rclone/rclone#942]
> What is your rclone version (eg output from `rclone -V`)
v1.34
> Which OS you are using and how many bits (eg Windows 7, 64 bit)
Debian 8.5 64-bit
> Which cloud storage system are you using? (eg Google Drive)
Amazon Drive
> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)
rclone copy /nfs/nas/Blah amazon:private:/Blah
> A log from the command with the `-v` flag (eg output from `rclone -v copy /tmp remote:tmp`)
See below.

It would be nice if rclone could respond appropriately to the following error:
>Failed to copy: HTTP code 400: "400 Bad Request", reponse body: {"logref":"[snip]","message":"1 validation error detected: Value \u0027[snip]\u0027 at \u0027name\u0027 failed to satisfy constraint: Member must have length less than or equal to 280","code":""}

Retrying won't work, and you might as well add a check along the lines of "once we see this kind of error, check all future filenames against the max length".

The check is especially important if its a **folder name** that's long rather than an individual file name. Right now, if rclone wanders into a directory with a long name (or one that crypts to a long name) performance will die as it steadily retries attempts that are doomed to fail - perhaps thousands of times for a directory with many files.

**Comment by maciozo** [comment]
Also getting this issue, except it's stalling my entire backup because it can't get past a load of long path names.

**Comment by eharris** [comment]
I think implementing #977 would also solve this.

**Comment by ncw** [comment]
@diamondsw 

what would you like rclone to do?

Come to a halt the moment this sort of error is detected?  Or just not retry?

Either is possible by wrapping the error message in a FatalError or a NoRetryError.

**Comment by maciozo** [comment]
@ncw 

Would it perhaps be possible to implement something like what Windows does on older file systems? i.e. something like "C:\Program Files" could be accessed by legacy programs with "C:\PROG~1" or so. Though I guess it would be necessary in that case to also implement some sort of list that stores all the references and their destinations.

**Comment by ncw** [comment]
@maciozo yes a system like that would be possible, and I and others are thinking about the whole metadata issue!

**Comment by maciozo** [comment]
@ncw 

As for the question you asked @diamondsw, in my opinion, it should be a NoRetryError, since in my case, a FatalError would be no better than the current behaviour of just infinite retries.

**Comment by PeterCooks2** [comment]
Use Long Path Tool to solve the errors. It works for me.

**Comment by animosity22** [comment]
Legacy issue as Amazon isn't used anymore. closing out.
