### ISSUE TITLE
[Feature Request] copy/move to multiple remote drives

### ISSUE THREAD

**Issue by ajkis** [rclone/rclone#958]
Example 
rclone copy/move source:/ dest1:/ dest2:/ 

There is a lot of chatter now how people are making sure that their media library is backed up on multiple cloud drives ( most popular main ACD and secondary 5$ unlimited google EDU ebay/accounts )

The rclone is the main tool for most ( based on discord chats, reddit etc.. ) and most people are first copying/moving to acd then from acd to anothercloud, however Amazon can be quity picky and tend to block ( it seems its not that rare.. i got blocked 4 times in last month ) mainly because of bandwith usage.

And if we upload to acd first then stream copy to another drive the bandwith is doubled. 

#### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by Andy58** [comment]
I am in a similar situation and would very much like to see this feature.

See my post [here](https://forum.rclone.org/t/is-it-possible-to-rclone-copy-to-two-destinations-simultaneously/490).

Thank you
Andy

**Comment by gts24** [comment]
I would love to see this feature implemented. Thanks for your continued development of rclone.

**Comment by idgf** [comment]
This would be handy to have as an option.

**Comment by deliverer33** [comment]
+1 for this RFE

**Comment by 2600box** [comment]
Hopefully implemented one day soon

**Comment by spali** [comment]
other use case:
currently with google g-suite for business you get 1TB limited teamdrives (below 5 users). But you can create as much teamdrives you want (even with one user for 8$) and each teamdrive can hold another 1TB. This allows for potential unlimited space, as long as you create enough teamdrives and split it over them. And only for 8$ a month ;)
Probably this could be implemented like crypt remote (as a layer between other remotes).

**Comment by ajkis** [comment]
@spali google does not enforce 1TB limit, even with 1 account you will get unlimited space.

**Comment by spali** [comment]
It does, I hit this week the limit by backing up to a teamdrive with quota exceeded in storage.
I talked to the support chat, and he confirmed that each drive (My Drive and teamdrive) has a 1TB limit. But also told me that I just can create another teamdrive to overcome the limit of one drive.
I didn't test "My Drive" limit, but at least teamdrive seems to have this limit.
I guess, the limits are enforced in newer accounts only. Mine is 2 weeks old.

**Comment by AndreTheHunter** [comment]
... 4 years later
Yes please! +1

**Comment by calisro** [comment]
https://forum.rclone.org/t/multiwrite-union-test-beta/14458/77

That will likely close this issue as well.

**Comment by ivandeex** [comment]
Closing in favor of #5746

Pease subscribe there

:+1: marks recorded in the new ticket
