### ISSUE TITLE
Unexpected behaviour with --min-age sync to remote which doesn't support modtime 

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#978]
Copy with --min-age to acd copies files that it shouldn't.

The problem is trying to do a copy/sync which relies on modification times to a remote which doesn't support them.

The filter (`--min-age`) is applied to the destination directory traversal combined with ACD not supporting modification times causes the problem.

If ACD supported mod times then this wouldn't be a problem.

However it isn't obvious that the copy relies on modtime working on the destination.

I could produce a warning here which might not be a bad idea.

Here is an idea for a work-around

   * for a remote which doesn't support modtime used as the destination of a `sync`, `copy` or `move`
   * and the user has specified age based filters (eg `--min-age`, `--max-age`)
   * disallow it as a destination for `sync` - that just isn't going to work
   * for `move` and `copy` ignore the age based filters on the destination

See [the forum](https://forum.rclone.org/t/copy-and-delete-excluded-issues/455/6) for full discussion.

**Comment by ajkis** [comment]
what was the unexpected behavior, just asking since i was using it as well when copying from acd to gdrive and now from acd to acd.

**Comment by ncw** [comment]
@ajkis 

From the forum

> So I have been seeding for two more days and wondering why my total file count hasn't been moving, it has been re-uploading the same files because of the --min-age 14d applying to the destination.

**Comment by naeloob** [comment]
Sorry, i think i misunderstood how filter works.
I dont see how can matters the destination on a copy filter by --max/min-age.

On the docs are documented this way : 
```
 --max-age - Don’t transfer any file older than this
This option controls the maximum age of files to transfer. 
...
For example --max-age 2d means no files older than 2 days will be transferred.

--min-age - Don’t transfer any file younger than this
This option controls the minimum age of files to transfer. 
```
It does not depens on destination state.

I mean, i want to copy the files younger than 1 hour : 
  rclone copy /ToBackup/ remote: --max-age 1h

What on destination could change the behaviour?
That 1h it's the time of live on source, that is all the files created or modified last hour.
But it seems that checks that 1h with something on the destination. 
I can't see the case where this filter must apply on destination. 

Could anyone put any case where you must filter destination by max/min-age?

If you apply this filter only in source (of course, if it's a remote must support filedatetime), which problem or case could go wrong?

Now i recall --max/min-size, it depens of destination in any way?

**Comment by ncw** [comment]
@naeloob if you read the forum thread you should see what the problem is.

rclone applies the filter to the source and destination (if it didn't do that rclone sync would delete files it shouldn't).  However since the modtimes are wrong on ACD rclone doesn't see that files are uploaded and uploads them again.

The work-around above will fix the problem.

**Comment by naeloob** [comment]
Yes, i've read the forum before posting, and what i understood was that the user was uploading again a lot of files because ACD dont have FileDateTime.
What i didn't know was that sync needs the age filters on remote.

I understand that sync is complex, and thinking about it, i dont know which behaviour has to have with --max/min-age.
The "copy" part of sync is clear : it have to upload files that match the filter....
It's the "Delete" part that dont know what it have todo. Delete all files on remote that match the age filter and do not exist on source? 
if it's the case, then i would suggest for Copy and Move ignore the age filters on destination.

Well, after reread the work-around above, it's basicaly the same...
Just a small difference, you say to ignore it only on remotes which not support modtime. 
As i dont see any problem on ignore it for any remote, i suposse you will search the best/simple implementation.

Regards

**Comment by ncw** [comment]
@naeloob 
> Just a small difference, you say to ignore it only on remotes which not support modtime.
As i dont see any problem on ignore it for any remote, i suposse you will search the best/simple implementation.

You may be right - with the new syncing mechanism, it will make very little difference so leaving it out for all remotes is probably a good idea.

**Comment by ivandeex** [comment]
@ncw @naeloob 
This issue is almost 4 years old and needs a retest with latest rclone.

**Comment by ivandeex** [comment]
Closed after 4 years of inactivity
