### ISSUE TITLE
Make zsh version of genautocomplete

### ISSUE THREAD

**Issue by kyrylo-shpytsya-prism** [rclone/rclone#983]
Please implement autocompletion for zsh. Zsh's "emulation" for loading bash style autocompletion functions fails apparently due to bashisms. 

$ rclone -V
rclone v1.33-DEV

----

(unable to install fresh version due to the following error)
github.com/aws/aws-sdk-go/aws/awsutil
../../.go-code/src/github.com/ncw/rclone/vendor/github.com/aws/aws-sdk-go/aws/awsutil/path_value.go:9: can't find import: "github.com/jmespath/go-jmespath"

gentoo linux 64bit

**Comment by ncw** [comment]
The bash autocompletion script is provided by the cobra library - I suggest you add your support to this issue: https://github.com/spf13/cobra/issues/107

re the compile problems - Which go version are you trying?

Did you try `go get -u github.com/ncw/rclone` ?

The travis builds are all succeeding at the moment so it is probably an updating rclone problem, or using an old go version.

**Comment by kyrylo-shpytsya-prism** [comment]
Apparently the installation issue was some kind of a glitch: today I have successfully upgraded to "1.35-DEV" using the same "go get ..." mantra that failed for me yesterday. No relevant local system reconfiguration took place in between.
As for the issue itself: I see that it completely depends on cobra, so depending on your policy, the issue can either be closed or kept open for tracking.
Regretfully, AFAIK, github still provides no upvoting mechanism, and posting a "+1" comment does not seem appropriate, so adding myself as a watcher to that issue was the best thing I could do.
P.S. Thank you for the great product!

**Comment by ncw** [comment]
I've put this into the "Known Problems" milestone.

I subscribed to the issue too!

> P.S. Thank you for the great product!

You are welcome!

**Comment by ncw** [comment]
spf13/cobra#107 has been fixed now, so if someone enterprising wanted to add zsh support then they could now

**Comment by jccurtis** [comment]
With `rclone genautocomplete zsh` has this been resolved? Is there interest submitting this to:

https://github.com/zsh-users/zsh-completions

I could submit a PR if there is. I don't want to jump the gun and submit the autocomplete script you put together. 😄

**Comment by ncw** [comment]
> With `rclone genautocomplete zsh` has this been resolved?

I think it has :-) I'm not a zsh user so I'm relying on users to tell me whether it works or not! Most of the hard work is done by cobra.

> Is there interest submitting this to:
> 
> https://github.com/zsh-users/zsh-completions
> 
> I could submit a PR if there is. I don't want to jump the gun and submit the autocomplete script you put together.

The completion script changes quite often as is generated by rclone so changes whenever new flags or backends get added.

Since rclone generates it and it is no use without rclone it might be better to submit a mechanism for generating it from rclone?

I will close this now :-)
