### ISSUE TITLE
rclone deleting and downloading again the same files, when on weak wifi 

### ISSUE THREAD

**Issue by nagualcode** [rclone/rclone#988]
I am using lastest rclone version on arm linux board, to sync local files with Dreamobject's Ceph buckets.
I have 2 boards, one of them plugged to ethernet cable, and this one seems to work just fine.
The other board is connected to the internet via WiFi, and the signal is weak. Often during cron's scheduled sync job rclone will delete a bunch of already synced 100% ok files, just to start downloading them again.
Can I assume this is because the weak wifi signal is corrupting the information rclone receives from the server? 
Or maybe this is just bad coincidence with some other issue?  
At first I taught this was due a bad memory card on the board, but I already switched it and this behavior continues.

**Comment by fredericofs** [comment]
I was using the --delete-before flag! So I am afraid it somehow interprets the bucket is "empty" and wipes the local sync folder.

**Comment by ncw** [comment]
> I was using the --delete-before flag! So I am afraid it somehow interprets the bucket is "empty" and wipes the local sync folder.

If there are errors when listing the bucket it should stop and not delete anything.

Can you attach a log with `-v --dump-headers` of this happening please?

**Comment by ncw** [comment]
I'm going to close this now as I haven't heard from you for a while.
