### ISSUE TITLE
Feature request : Lost my ".rclone.conf" file ! ;( Add automatic backup of it when running Rclone ?

### ISSUE THREAD

**Issue by doplu** [rclone/rclone#991]
Hello,

Rclone version : 1.35
OS used: Linux on ARM32 (running on a cheap baremetal scaleway VPS https://www.scaleway.com/pricing/)

> The command you were trying to run (eg `rclone copy /tmp remote:tmp`)

rclone --checksum copy ACD:'/P2/A/REPORTS/' ACD:'/P/A/REPORTS/'

note: I made an error, and copied the folder REPORTS (from '/P2/A/REPORTS/') inside another place 'P' where it was already existing with the same content. Too bad for me as it appears to me that it deleted my "root/.rclone.conf" file to 0 byte. ;(
Is there a way to get it back without creating the rclone config again from scratch (it took me several hours last time I did it. Hopefully I took some notes to make it faster next time : see below (*)?
If not, could rclone automatically create in the future version a backup of this file alone ? It would be great if rclone itself saves a backup (or several) of it before running. 

Many thanks in advance ;)

_(*) In case this helps others:_ 
Use "Midnight Commander" for managing files. Installing this files manager : `sudo apt-get install mc`  (then just run the "`mc`" (without quotes) command to launch it.
Then, use the w3m linux browser (http://www.howtogeek.com/103574/how-to-browse-from-the-linux-terminal-with-w3m/  and https://forum.rclone.org/t/unable-to-auth-new-amazon-drive/162) in order to fill the Amazon drive form and be able to save the captcha image. Then hopefully for me I was able to previously configure Google Drive (see create your own client id : http://rclone.org/drive/) ! So I was able to copy the captcha images to my Google Drive where I was able to decipher it ! Ouch ! It was long but it worked ! ;)
edit: I was able to create a new rclone config from scratch faster today (about 30 minutes) as I had no need to get a captcha! ;)

**Comment by ncw** [comment]
Bad luck!

I'm not clear on exactly what happened though
> note: I made an error, and copied the folder REPORTS (from '/P2/A/REPORTS/') inside another place 'P' where it was already existing with the same content. Too bad for me as it appears to me that it deleted my "root/.rclone.conf" file to 0 byte. ;(

Was "root/.rclone.conf" in that directory tree anywhere?

Is it possible your disk got full at one point?  Then when rclone attempted to update the config file with a new token it wrote it out a 0 bytes?

BTW http://rclone.org/remote_setup/ has a procedure for doing remote setups which you might find easier!

**Comment by animosity22** [comment]
This looks like a one off item and solved by system backups.
