### ISSUE TITLE
Feature Request: Sync last XXXMB to cloud...

### ISSUE THREAD

**Issue by vertigo235** [rclone/rclone#993]
So this is something I want to do, I could probably create a script to do it, but I would like to know if this is possible or could be added to the rclone tool

My cloud provider only provides 1TB of space, but I have more than 1TB of stuff, so I would like to basically keep the last 1TB of data on the cloud provider at all times, kind of like a feed of the last 1TB of stuff.

So when I sync, I would like to delete the oldest stuff and upload the newer stuff all to fit on the cloud provider as close to 1TB as possible.

How about that, can this type of feature be added to rclone? This is such a great tool.

**Comment by animosity22** [comment]
It looks reading through this that is can be done via filters and a few tweaks in rclone already so I'm going to close this out. If you want some tips on how to do it, you can ask on the forums https://forums.rclone.org and we can help out.
