### ISSUE TITLE
Allow mounting crypted folders "in place" with the parent remote

### ISSUE THREAD

**Issue by jtl5770** [rclone/rclone#997]
Description of the problem from the [rclone forum article](https://forum.rclone.org/t/automatically-mount-crypted-folders-in-place-when-mounting-the-parent-remote/401)

After the discussion it turns out that changing rclone to automatically construct the folder tree in one instance is not going to be implemented. 

The alternative suggested was to implement the possibility to have one mount shadow folders in the tree of another mount which currently is only possible as root and with changing permission handling.

**Comment by ivandeex** [comment]
Closing after 4 years of inactivity
